### ISSUE TITLE
Does it exist a more accurate geoJson countries file?

### ISSUE THREAD

**Issue by VirtualisProject** [openlayers/openlayers#10002]
I am working on a project where i render a color overlay (feature) on the contries that has a node located in the country, see image below: 
![image](https://user-images.githubusercontent.com/43247999/65606845-da840e80-dfab-11e9-96b2-d6e2ab94d836.png)

I find the data which i am currently using https://raw.githubusercontent.com/bernardobelchior/openlayers-scratch-map-tutorial/start/countries.geojson to be way to inaccurate for my use case, and i would like to get access to another more detailed geoJSON file, either free or for a price. 

Does anyone know of a third-party file / more accurate file that i could use for my project? 

Thanks alot! :)

**Comment by mike-000** [comment]
You can download one from https://datahub.io/core/geo-countries

**Comment by jahow** [comment]
This issue tracker is for bugs and feature requests, thanks!
