### ISSUE TITLE
Disappearing shapes after selection

### ISSUE THREAD

**Issue by heidfeld** [openlayers/openlayers#10008]
**Describe the bug**
Sometimes shapes disappear after selection. Let's say that we have piece of map with ~1000 objects. We select one of them then move the map outside the bounding box and select another feature from loaded data. Sometimes this scenario causes an error that completely destroys the selection behavior (each selected object disappears).

The error that destroys the selection: 
![Screenshot 2019-09-26 07-40-03](https://user-images.githubusercontent.com/13362016/65666101-406ca680-e03d-11e9-99c8-231a69eb368c.png)

Here is a piece of code that I think should be wrapped with a basic condition.
```
var featureKey = getUid(feature).toString();
// if (featureKey) ??? 
this.featureChangeKeys_[featureKey].forEach(unlistenByKey);
```
As a result of an error, the flag modifyingCollection does not change the value correctly and selected object disappears. 
```
modifyingCollection = true;
this.removeFeature((evt.element)); // ERROR
modifyingCollection = false;
```
We can't fix it on our side. Catching an exception won't set modifyingCollection to the correct value.

**To Reproduce**
1. Open piece of map with about ~1000 objects or more.
2. Select any feature with single click.
3. Move the map outside the bounding box (force new data fetch)
4. Select another feature from new data.
5. Repeat until an exception will occur and the selection will stop working

**Expected behavior**
There cannot be a situation where one exception spoils the entire selection. If the user has a possibility to select the object, it means that it is currently loaded. Maybe some snippet of code is being called with delay (setTimeout for single selection waiting for double click) and for a moment there is no consistency. I think basic condition will fix this issue.

**Comment by jahow** [comment]
Hi and thanks for submitting this issue,

Investigating this would need a minimal reproduction case since it really depends on how your features are loaded/unloaded, and this is something that can't be directly inferred from your report.

The error seems to indicate that a feature wasn't correctly registered in the source. Adding a condition like you suggest would only make the error go away but not solve the underlying issue.

Could you please set up such a reproduction case so that we can look into this further? Thanks a lot.

**Comment by welltothebone** [comment]
Hi, i have the same issue. The issue may be related to layers having features with same ids and multi selection enabled.

How to reproduce:

- Add a geojson layer to the map, for example:

```
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    24.9251389,
                    59.4130278
                ]
            },
            "id": "1",
            "title": "Title"
        }
    ]
}

```

- Add another layer to the map using the same geojson as above.

- Add a select interaction to the map with properties:

```
multi: true,
hitTolerance: 10
```

- Select the feature(s) on the map by clicking on it.

- Unselect the feature on the map.

**Comment by tkohr** [comment]
Hey, 

this seems to be a bug in ol5. The following sandbox works with v6.0.0-beta.15 but shows your described behavior when switching to v5.3.3. Could you try if the latest v6.0.0-beta.15 fixes the issue for you? Thanks!
