### ISSUE TITLE
Bad performance in Citrix env.

### ISSUE THREAD

**Issue by lukaszbel** [openlayers/openlayers#10019]
Hello,
one of our clients uses Citrix environment. I saw that Open Layers works very low on this env. I found old ticket http://osgeo-org.1560.x6.nabble.com/OpenLayers-2-13-how-to-avoid-animated-zooming-td5060774.html that animated zooming should generate the problem. Now we are using 5.X version. How we can disable "animated zooming"? Did anyone have a similar problem and can give me any tips? Thanks in advance.

**Comment by mike-000** [comment]
You can set zoom durations in the default controls and interactions

https://openlayers.org/en/v4.6.5/apidoc/ol.control.html#.defaults (version 4 link as the documentation in later versions seems to be broken)
https://openlayers.org/en/latest/apidoc/module-ol_interaction.html#~defaults


for example:

```
import {defaults as defaultControls} from 'ol/control';
import {defaults as defaultInteractions} from 'ol/interaction';
  ...
  ...
  ...
var map = new Map({
  controls: defaultControls({zoomOptions: {duration: 0}}),
  interactions: defaultInteractions({zoomDuration: 0}),
  ...
  ...
  ...
});
```
