### ISSUE TITLE
Examples should link to related examples

### ISSUE THREAD

**Issue by marcjansen** [openlayers/openlayers#10022]
For example the client side reprojection examples should link to each other. Same goes for 'Layer Min/Max Resolution' and 'Layer Zoom Limits', which basically achieve the same effect but no one knows this from viewing either one.

**Comment by isthisstackoverflow** [comment]
Interlinking sounds like a lot of work to do, and could lead to inconsistencies when new examples are added. I'd propose to add some categories. Slamming sub-headings in the page to aggregate examples should be easy.

E.g. there's these examples that would more or less fit a heading "Drawing and Modifying Features"

- https://openlayers.org/en/latest/examples/draw-and-modify-features.html
- https://openlayers.org/en/latest/examples/draw-shapes.html
- https://openlayers.org/en/latest/examples/translate-features.html
- https://openlayers.org/en/latest/examples/snap.html
- https://openlayers.org/en/latest/examples/modify-features.html

I guess that there'd be a huge "Others" category, though.

While I'm here, great work on the examples! It's super to look up how to do things and I love the new style including a package.json and such.

**Comment by marcjansen** [comment]
Good idea! Would you be able to help us here? We already have tags, and these might come in handy.

**Comment by isthisstackoverflow** [comment]
I'd love to, but it'll probably take me some time. I never made a PR before, but I guess this is the way:

* Make fork
* Fiddle around in /examples folder until result looks agreeable
* Figure out how I send it back in and let you decide if it's done

Is this about right? If so, please do tell me something more about these tags, and I'll start soonish.

**Comment by simonseyock** [comment]
@isthisstackoverflow yes that is about right. To be more precise:

* make a fork
* clone fork to your computer
* make a branch
* run `npm install`
* run `npm start`
* do your thing
* commit & push to your fork
* create a pull request by visiting your fork on github

The tags are stored in the head parts of the `examples/*.html` files, which are actually front matter files: https://jekyllrb.com/docs/front-matter/

**Comment by isthisstackoverflow** [comment]
Turns out I'm too lazy* to ever do this. If anyone else feels called to act on this issue, please do so.

*If a future employer reads this, I meant to write "short on time due to all the amazing projects I'm working on right now".

**Comment by ChutipongSj** [comment]
#10495
