### ISSUE TITLE
ol v6.0.0-beta.15 stop fetching and rendering tiles

### ISSUE THREAD

**Issue by sookoll** [openlayers/openlayers#10033]
**Describe the bug**
I switched from v5.3.3 to v6.0.0-beta.15 couple of days ago. Now after short period of panning around, map just stop fetching new tiles. Other times it just get really slow and laggy. Nothing happens in browser devtools Network tab. Also no errors or warnings in console. It happens both in desktop (OSX Safari) and mobile (Android Chrome).

**To Reproduce**
1. create map, add some tiles and wms layers
2. pan around a lot

**Comment by jahow** [comment]
Hi and thanks for your report,

Could you please provide us with a minimal reproduction case? This may be related to the surrounding application code and there is no way to tell from what you are describing here. Thanks a lot!

**Comment by sookoll** [comment]
I don't have time for that. Issue exists only with v6.0.0 and not in v5.3.3. So I can't see how it can be related with app code. I switched back to 5.3.3 and it is blazing fast compared to v6.0.0.

**Comment by jahow** [comment]
> I don't have time for that

I completely understand, but how exactly do you expect anyone to improve the library based on the description you gave? There is simply not enough information to work on (like the amount of layers, how they are created, if you use event listeners, etc.).

**Comment by tschaub** [comment]
We have recently addressed an issue with the tile queue that had symptoms similar to the ones you are describing (tiles eventually stopped loading).  The issue was triggered by calling `source.setURL()` repeatedly.

If you can describe anything else that you think might be causing the issue, that would give people more hints to go on.  Are you using a custom tile URL function?  Are you adding and removing layers or sources?  Are you changing anything about the layers or sources?  How many and what type of layers and sources?

Also, you could try the latest `ol@dev` release.  If it is still present with the latest dev release (or the upcoming 6.0.0 release), adding more info as @jahow suggests would be helpful.

**Comment by jeroenvheel** [comment]
We also have this issue we are using ol@6.0.1
![tile-not-loading](https://user-images.githubusercontent.com/228655/66129928-227ce400-e5f1-11e9-8acd-6346188d2cad.png)

**Comment by tschaub** [comment]
@jeroenvheel can you describe the layer types used and the rough steps to reproduce the issue (including things like adding layers to the map, setting source url, etc)?

**Comment by jeroenvheel** [comment]
hope this works : https://codesandbox.io/s/wms-image-irg77

**Comment by yiwenzhang666999** [comment]
> We have recently addressed an issue with the tile queue that had symptoms similar to the ones you are describing (tiles eventually stopped loading). The issue was triggered by calling `source.setURL()` repeatedly (see #9855 and #9868).
> 
> If you can describe anything else that you think might be causing the issue, that would give people more hints to go on. Are you using a custom tile URL function? Are you adding and removing layers or sources? Are you changing anything about the layers or sources? How many and what type of layers and sources?
> 
> Also, you could try the latest `ol@dev` release. If it is still present with the latest dev release (or the upcoming 6.0.0 release), adding more info as @jahow suggests would be helpful.
我们用的是6.0.1版本，加载的瓦片地图，当不断缩放和移动地图时，浏览器就停止加载瓦片，控制台报的错误信息为Tile load sequence violation,但是好像不是这个问题引起的

**Comment by yiwenzhang666999** [comment]
@tschaub 
![1570672205(1)](https://user-images.githubusercontent.com/31643589/66532887-99f7c980-eb43-11e9-982c-d3deb67c40f8.png)
![1570672417](https://user-images.githubusercontent.com/31643589/66532985-ef33db00-eb43-11e9-802d-61f945d3d62f.png)

我们用的是6.0.1版本，加载的瓦片地图，当不断缩放和移动地图时，浏览器就停止加载瓦片，控制台报的错误信息为Tile load sequence violation,浏览器network中不再发送请求

**Comment by yiwenzhang666999** [comment]
@ahocevar 
我们加载的是矢量瓦片图层(pbf tiles)结合ol-mapbox-style，当我们用openlayers5的时候缩放过程中浏览器内存使用过大时会崩溃，升级到ol6.0.1后，会出现浏览器停止加载瓦片的情况，我们发现一个规律，当上面浏览器控制台的错误出现16次时，就不再请求瓦片
![image](https://user-images.githubusercontent.com/31643589/66560091-414b1f80-eb89-11e9-8124-a7fe144fb1fd.png)

**Comment by ahocevar** [comment]
@yiwenzhang666999 Can you share your tileLoadFunction? That is where the state is set, and that could cause the errors.

**Comment by yiwenzhang666999** [comment]
@ahocevar 
下面是我们用的tileLoadFunction方法，里面监听了error事件，但是只有当网络连接不上，请求不到瓦片时才会进入这个方法，按照#10112，我们修改了VectorTile.js,但是仍然还会报同样的错，这个错误出现的原因是因为，this.state = 5, state = 2
![image](https://user-images.githubusercontent.com/31643589/66622521-89665280-ec1a-11e9-8c64-f81884e5991c.png)
![image](https://user-images.githubusercontent.com/31643589/66622500-62a81c00-ec1a-11e9-9c51-79287f47e551.png)

**Comment by MukeZ** [comment]
Same issue here, only happens when I using 6.0.1.

**Comment by lzp0070007** [comment]
I use map add a vector tile  have the same error,  stop fetching and rendering tiles

**Comment by ahocevar** [comment]
@MukeZ @lzp0070007 You can install the latest ol@dev already to get a fixed version.

@yiwenzhang666999 Your custom tileLoadFunction does not look right. Why aren't you using the default? If you need a custom one, try something like the one from the [API docs](https://openlayers.org/en/latest/apidoc/module-ol_source_VectorTile-VectorTile.html).

**Comment by yiwenzhang666999** [comment]
@ahocevar
我使用默认的tileLoadFunction，并且将版本升级到最新的6.0.1-dev.1571084548232，还是会出现同样的问题，当“Uncaught Error: Tile load sequence violation”这个错误达到15次的时候，就停止加载瓦片。

**Comment by yiwenzhang666999** [comment]
@ahocevar
我使用默认的tileLoadFunction，并且将版本升级到最新的6.0.1-dev.1571084548232，还是会出现同样的问题，当“Uncaught Error: Tile load sequence violation”这个错误达到15次的时候，就停止加载瓦片。

**Comment by ahocevar** [comment]
Does the error still occur when going from state 5 to 2? Can you share a minimal example to reproduce the issue? Or does it occur with one of the official examples?

**Comment by yiwenzhang666999** [comment]
@ahocevar 
在官网的例子中会出现同样的问题，当你不断缩放的过程中
https://openlayers.org/en/latest/examples/mapbox-style.html?q=Vector+Layers
![image](https://user-images.githubusercontent.com/31643589/66820892-10e1f780-ef74-11e9-806e-536108e60f69.png)

**Comment by ahocevar** [comment]
Ok, that‘s 6.0.1, before the fix though.

**Comment by yiwenzhang666999** [comment]
ahocevar
今天我用这个版本（6.0.1-dev.1571084548232）测试了，还是有相同的问题

**Comment by yiwenzhang666999** [comment]
@ahocevar 
在这个版本中6.0.1-dev.1571174251046我看到你修复了“Uncaught Error: Tile load sequence violation”这个错误，但是还会出现停止加载矢量切片的问题

**Comment by ahocevar** [comment]
That other problem is related and should also be fixed. Can you confirm that?

**Comment by yiwenzhang666999** [comment]
我也不能确认
