### ISSUE TITLE
Documentation glitch

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10049]
**Describe the bug**
There are two unresponsive Type links in https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw.html
I would expect GeometryFunction in Options to link to the definition above Options (similar to https://openlayers.org/en/latest/apidoc/module-ol_style_Style.htm ) while PointCoordType within SketchCoordType is showing the wrong module.  Presumably the first is due to the definition order, but the second one?

**Comment by simonseyock** [comment]
This might have to do with https://github.com/openlayers/jsdoc-plugin-typescript/commit/3af3f147b1f31a85cec362588aa7dfa9e57e5517

**Comment by simonseyock** [comment]
Thanks for reporting! I will look into it.

**Comment by simonseyock** [comment]
The first problem is fixed by https://github.com/openlayers/jsdoc-plugin-typescript/pull/10/files
The second one is related to this one: https://github.com/openlayers/openlayers/issues/10044

**Comment by simonseyock** [comment]
Actually those are different problems. Your second problem is fixed by the second commit to the mentioned PR.
