### ISSUE TITLE
Use Array or Collection more consequently

### ISSUE THREAD

**Issue by flexjoly** [openlayers/openlayers#10053]
**Is your feature request related to a problem? Please describe.**
I am using the interactions Snap, Translate and Draw together on a map. For the proposed SnapEvent  (#10037) I used ol/interaction/Select as base for my code. Because that was the closest to Snap-interaction.

Select puts the selected Features in an array in the SelectEvent. So I did the same for SnapEvent. 
Now I find out that TranslateEvent uses a collection the feature-list.

When using interactions together.... **you need different ways to get a feature**. That is not nice and I don't like WET 😛 

**Describe the solution you'd like**
Use Collection OR Array consequently on corresponding properties.

But it is triggy, because it is NOT backward compatible. 
For example: 'array[key]' returns 'undefined' on a Collection. 

Since the new SnapEvent is not live yet, I will change the code so it will also use a collection. 
_Unless, this is not best-practice for OL..._ ?

At the moment I am implementing some interactions in our project. 
**_I can make a PR to change feature-array's in interaction-events to a collection._** 

- - -

**Best Practice?**
I do favor collection over array. Because it is more flexible. It can be extended better. And you can use events on it.
I have no idea what it does for performance. ❔ 

I have searched if there is any recommendation about using Collection or Array, but I could not find anything. What is preferred for OL?

**What if Collection was used for all Array's?**
Cons:
- a huge change 
- is NOT backward compatible. 
- what about performance?

**Possible fix to get backward compatibility (?)**
It can be bypassed with a magic function like in PHP __get(). 
But javascript does not have this. 
Such a function can be made but it is complicated and I guess it is bad for performance;  see: https://stackoverflow.com/questions/994143/javascript-getter-for-all-properties

**Comment by ahocevar** [comment]
My (personal) goal is to get rid of collections in the library.

**Comment by flexjoly** [comment]
Hi,
Is there any chance that this can get priority? Or that PR's are allowed to make changes towards using only array's  or only collections??

Like in SelectEvent and TranslateEvent... one uses an array of features and the other uses a collection.... So you need a different approach to get a feature out of it 😕
