### ISSUE TITLE
XYZ and TMS tiles  coordinate converting in createFromTemplate function in ol/tileurlfunction.js 

### ISSUE THREAD

**Issue by kikitte** [openlayers/openlayers#10059]
**Describe the bug**
I am recently working on vector tile in Openlayers-V6.0.0 and Geoserver TMS service.
According to the ol document, I use the '{-y}' placeholder in URL template to indicate TMS Grid.
But the url is incorrect as expected.
below is the configuration.
```typescript
    const resolutions: number[] = new Array(29).fill(0);
    resolutions.forEach((v, i , a) => {
      a[i] = 156543.03392804097 / Math.pow(2, i);
    });
    const origin = getTopLeft(getProjection('EPSG:3857').getExtent());
    const extent = [11742903.0, 3724884.75, 12383392.0, 4805854.0];
    const shaanxiCountyLayer = new VectorTileLayer({
      source: new VectorTile({
        url: 'http://127.0.0.1:8080/geoserver/gwc/service/tms/1.0.0/mygisdb%3Ashaanxi_county@EPSG%3A900913@pbf/{z}/{x}/{-y}.pbf',
        format: new MVT(),
        tileGrid: new TileGrid({
          extent,
          resolutions,
          origin,
        }),
      }),
    });
```
I got these urls with nagative y coordinate.
![image](https://user-images.githubusercontent.com/23274684/65823714-1e1d9780-e28e-11e9-9451-a74625c7b320.png)

createFromTemplate function
![image](https://user-images.githubusercontent.com/23274684/65823746-ecf19700-e28e-11e9-9445-13b247ff3617.png)
May be there is a problem when converting XYZ y to TMS y, 
```typescript
var y = range.getHeight() - tileCoord[2] - 1;
```
according to [doc](https://gist.github.com/tmcw/4954720) it should be 
```typescript
 var y = Math.pow(2, z) - tileCoord[2] - 1;
```
yes every thing works well after I do that.

**To Reproduce**
Configuring  VectorTileLayer as described in the above then check the url.

**Comment by mike-000** [comment]
An EPSG3857/EPSG:900913 grid uses the projection extent and as it is the OpenLayers default it need not be specified.  To restrict the displayed extent specify a layer extent

    const shaanxiCountyLayer = new VectorTileLayer({
      source: new VectorTile({
        url: 'http://127.0.0.1:8080/geoserver/gwc/service/tms/1.0.0/mygisdb%3Ashaanxi_county@EPSG%3A900913@pbf/{z}/{x}/{-y}.pbf',
        format: new MVT()
      }),
      extent: extent
    });

**Comment by kikitte** [comment]
Thanks a lot, it works like a charm.
