### ISSUE TITLE
RTL Problem 

### ISSUE THREAD

**Issue by esiur** [openlayers/openlayers#10058]
Incorrect features location in vector layers in RTL pages.

**To Reproduce**
1- go to https://openlayers.org/en/latest/examples/cluster.html?q=vector
2- Set dir="rtl" for HTML tag.
3- Zoom in and out to see the problem.

**Comment by simonseyock** [comment]
Thanks for reporting the issue.
I can not see a problem there, though. It does not behave differently than without `dir=rtl` for me. What browser are you using?

**Comment by simonseyock** [comment]
See https://codesandbox.io/s/cluster-11u5p

**Comment by sky93** [comment]
I have the same problem. My `<html>` tag has `dir="rtl"` property. And when I load the map I see no tiles (They get loaded. I see them in Network panel of my browser). And when I remove the `dir` property or change it to `ltr`, they will show up. This problem occurred after I migrated from version 5 to 6.

**Comment by simonseyock** [comment]
Hello @sky93, thanks for reporting. Can you provide a minimal example where this occurs? Then we can investigate the problem further. And can you tell which browser you are using?

**Comment by sky93** [comment]
I fugured out that this is because `dir='rtl'` and also `text-align` of the map element is `left`

This is my html:
```html
<!DOCTYPE html>
<html dir="rtl">
  <head>
    <title>XYZ</title>
    <style>
      .map { 
        width: 100%;
        height:400px;
        text-align: left;
      }
    </style>
  </head>
  <body>
    <div id="map" class="map"></div>
    <script src="index.js"></script>
  </body>
</html>
```

This is my index.js:

```javascript
import 'ol/ol.css';
import Map from 'ol/Map';
import View from 'ol/View';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';


new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: new XYZ({
        url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      })
    })
  ],
  view: new View({
    center: [-472202, 7530279],
    zoom: 12
  })
});
```

And this is package.json:
```
{
  "name": "cluster",
  "dependencies": {
    "ol": "6.0.1"
  },
  "devDependencies": {
    "parcel": "1.11.0"
  },
  "scripts": {
    "start": "parcel index.html",
    "build": "parcel build --experimental-scope-hoisting --public-url . index.html"
  }
}
```

Sandbox: https://codesandbox.io/s/bug-with-rtl-064bi

**Comment by fredj** [comment]
With `dir='rtl'`and `text-align: left`, the layer canvas is shifted to the left and is not visible.
Same if `text-align: right;` is set to the map (but without the `dir`): the layer canvas is shifted to the right.

**Comment by sky93** [comment]
> With `dir='rtl'`and `text-align: left`, the layer canvas is shifted to the left and is not visible.
> Same if `text-align: right;` is set to the map (but without the `dir`): the layer canvas is shifted to the right.

Yeah and this doesn't happen in version 5.3.3.

**Comment by esiur** [comment]
I'm using Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

The problem I believe still occurs in 6.0.1

Goto https://openlayers.org/en/latest/examples/cluster.html

Write the following in the console
document.body.style.direction = "rtl"
