### ISSUE TITLE
Openlayers6 typescript

### ISSUE THREAD

**Issue by Diaaz** [openlayers/openlayers#10062]
Hi,
I can't seem to get typing working in a VSCode OL6.0.0 typescript project using the steps readme. The project compiles and the application is working, but there are no types in VS-Code. Does anyone have a starter project somewhere?

Thanks

**Comment by ahocevar** [comment]
You can use this gist as a starting point:

https://gist.github.com/ahocevar/9a7253cb4712e8bf38d75d8ac898e36c

**Comment by Diaaz** [comment]
The gist works perfectly for javascript projects, but when adapting to tsconfig.json it does not work. We get javascript errors building from the ol-folder. We are reverting back to 5.3 using @types/ol for now.

**Comment by ahocevar** [comment]
See #10061 for an attempt to use the upcoming .d.ts generation capability of TypeScript.

**Comment by hanreev** [comment]
I've published v3.0.0 of [@hanreev/types-ol](https://www.npmjs.com/package/@hanreev/types-ol) for ol v6.
Need several tests before publishing to `@types/ol`

**Comment by Diaaz** [comment]
@hanreev  Thanks for the types, they work perfectly.

**Comment by timbru31** [comment]
To keep the stale bot from closing it, I'm pinging @hanreev to ask if there has been any progress in the past two months. No pressure though! :)

**Comment by idevtech** [comment]
Lack of TypeScript support for OpenLayers 6 is a show stopper for our project. Why isn't there TypeScript support given the broad use of TypeScript? When will it be provided as part of each release?

**Comment by jahow** [comment]
https://github.com/openlayers/openlayers/pull/10061 is a work in progress for automated definitions file generation, which is what is required for full typescript support in OpenLayers.

> Why isn't there TypeScript support given the broad use of TypeScript?

The whole library is written in ES6 with JSDoc annotations. Ideally Typescript would be able to understand these and provide autocompletion/typecheck for application code but this is unfortunately not always the case. Thus, a `.d.ts` definitions file has to be provided alongside the library, and maintaining such a file manually is not an option for most of us.

**Comment by hanreev** [comment]
I will publish ol v6 definitions at [@hanreev/types-ol](https://www.npmjs.com/package/@hanreev/types-ol) to official [@types/ol](https://www.npmjs.com/package/@types/ol).
I haven't used ol v6 personally, if there is a definition error please [create a new issue](https://github.com/hanreev/types-ol/issues).

**Comment by Diaaz** [comment]
Thanks @hanreev the types work perfectly and have more typedefinitions than the previous version.
