### ISSUE TITLE
Use package-lock.json for CircleCI cache checksum

### ISSUE THREAD

**Issue by DanielRuf** [openlayers/openlayers#10069]
**Describe the bug**
Currently package.json is used for the cache checksum which is not recommended.
https://circleci.com/docs/2.0/caching/#restoring-cache

https://github.com/openlayers/openlayers/blob/master/.circleci/config.yml#L14
https://github.com/openlayers/openlayers/blob/master/.circleci/config.yml#L24

**To Reproduce**
https://github.com/openlayers/openlayers/blob/master/.circleci/config.yml#L14
https://github.com/openlayers/openlayers/blob/master/.circleci/config.yml#L24

**Expected behavior**
The lockfile should be used for cache invalidation.

**Comment by DanielRuf** [comment]
Not stale.

**Comment by DanielRuf** [comment]
Not stale.

**Comment by DanielRuf** [comment]
cc @ahocevar

**Comment by ahocevar** [comment]
Are yo able to provide a pull request @DanielRuf ?
