### ISSUE TITLE
Option for Zoom control to work as in earlier versions

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10066]
**Is your feature request related to a problem? Please describe.**

In previous versions of OpenLayers the Zoom control button moved the view to an integer zoom level regardless of any constraints.  In OL6 if the view is left at  a fractional zoom set by another operation such as PinchZoom or `.fit()` or an extent constraint the Zoom control (in the absence of constraints) simply adds or subtracts the delta.

So previously with a delta of 1

 3.6, 3.0, 2.0, 1.0, 0.0

is now

 3.6, 2.6, 1.6, 0.6, 0.0

While that is not wrong it might not be what some users are expecting and image quality can be affected.

**Describe the solution you'd like**

Giving the control an option (maybe called `snapToDelta`) which instead of simply adding or subtracting the delta requests the nearest multiple of the delta in that direction would allow the control to revert to optimal resolutions while still allowing unconstrained fine tuning.  It would not be a constraint or override constraints, so fractional results might still occur if for example an extent constraint is reached but will not persist when clear of the constraint.

**Comment by hmdavidjunior** [comment]
Dont need, I had the same issue. Just set on view options

```
constrainResolution: true
multiWorld: true
```
"**constrainResolution**" value "**true**" will set zoom behaviour as it was before, with integer zoom levels, skipping the fractional zoom

"**multiWorld**" value "**true**" will allow your map to reach zoom level 2, 1 and 0

check details at
https://openlayers.org/en/latest/apidoc/module-ol_View-View.html

**Comment by mike-000** [comment]
@hmdavidjunior That is constraining the view which I don't want because it constrains everything, I want to allow PinchZoom and `fit()` to work unconstrained while the Zoom control behaves as it did in OenLayers 5.

**Comment by ahocevar** [comment]
I also think there is no need to change the new behavior. To avoid fractional zoom levels, simply set `constrainResolution: true`, or accept that you're not seeing integer zoom levels. We're using best effort to display a sharp and crisp rendered image even at fractional zoom levels.

**Comment by mike-000** [comment]
No problem, I made a custom control which temporarily constrains resolution to put the view back on an integer zoom  https://codesandbox.io/s/custom-controls-z7pxg  Notice that if you zoom in by rapidly clicking the zoom in button it becomes fractional again due to interruption of animation similar to #10071
