### ISSUE TITLE
readFeatures from WFS with gmlFormat: GML32

### ISSUE THREAD

**Issue by Dimitriio** [openlayers/openlayers#10077]
Hello,

With Angular 8, typescript 3 environment, i try convert some xml into Feature[] like that : 
`    const wfsFormat = new WFS(<Options>{featureNS : 'ms', gmlFormat: new GML32(), srsName: 'EPSG:3857'});`
`    const features: Feature[] = wfsFormat.readFeatures(text);`

But an exception is thrown :
`ERROR TypeError: "this.gmlFormat_.FEATURE_COLLECTION_PARSERS[_GMLBase_js__WEBPACK_IMPORTED_MODULE_3__.GMLNS] is undefined"`
`readFeaturesFromNode WFS.js:236`
`    readFeaturesFromDocument XMLFeature.js:127`
`    readFeatures XMLFeature.js:106`

In debug mode i see that in the `FEATURE_COLLECTION_PARSERS` there is only the namespace for GML32 'http://www.opengis.net/gml/3.2' while the value it try to get is GMLNS 'http://www.opengis.net/gml' explaining the undefined.

Its working for GML3 because it doesnt override default namespace `GMLBase.prototype.namespace = GMLNS;`

**Comment by wangjianjun0707** [comment]
have you fit it,I have same problem

**Comment by Dimitriio** [comment]
Hi, 
No I havnt, the service I use can send gml3 so I didnt needed absolutely the gml32 parser.
It seems like I cant reopen this issue as it wasnt close by me.

**Comment by wangjianjun0707** [comment]
thank you。

**Comment by Dimitriio** [comment]
Well maybe you can open a new issue and link this one in your comment. 
That way the information i provided arent lost.

**Comment by jahow** [comment]
Hi,

So, why exactly is it looking for the GML 3 namespace rather than the GML 3.2 one, considering the format used is `GML32`?

It is hard to tell what's going on without a simple reproduction case, although that may be hard considering this is in an angular app. @Dimitriio do you think you can set this up on codepen or similar? Thanks

**Comment by mike-000** [comment]
Neither the code nor the update history suggest `ol/format/WFS` has been updated to handle GML 3.2  To support GML 3.2 `GMLNS` throughout the module would need to be replaced by `this.gmlFormat_.namespace` (and other changes may also be needed).

**Comment by Dimitriio** [comment]
Yeah the problem is that in [WFS](https://github.com/openlayers/openlayers/blob/v6.1.1/src/ol/format/WFS.js) class, at method :
```
 readFeaturesFromNode(node, opt_options) {
    /** @type {import("../xml.js").NodeStackItem} */
    const context = {
      node: node
    };
    assign(context, {
      'featureType': this.featureType_,
      'featureNS': this.featureNS_
    });

    assign(context, this.getReadOptions(node, opt_options ? opt_options : {}));
    const objectStack = [context];
    this.gmlFormat_.FEATURE_COLLECTION_PARSERS[GMLNS][
      'featureMember'] =
        makeArrayPusher(GMLBase.prototype.readFeaturesInternal);
    let features = pushParseAndPop([],
      this.gmlFormat_.FEATURE_COLLECTION_PARSERS, node,
      objectStack, this.gmlFormat_);
    if (!features) {
      features = [];
    }
    return features;
  }
```
There is the default namespace use like this : `this.gmlFormat_.FEATURE_COLLECTION_PARSERS[GMLNS]` so the GML32 namespace (and from other subclasses from GMLBase) is not used. I have not searched a lot more if it implies other changes elsewhere.

**Comment by mike-000** [comment]
this.gmlFormat_.FEATURE_COLLECTION_PARSERS[this.gmlFormat_.namespace][
      'featureMember'] =
        makeArrayPusher(GMLBase.prototype.readFeaturesInternal);

might be sufficent for WFS to read GML 3.2.

However full support for GML 3.2 would require supporting the various `write...` methods.  Currently some reference `GMLNS` while others reference `GML3.prototype` and many of the functions are not called with scope which would be needed to get the required GML format.

**Comment by wangjianjun0707** [comment]
> have you fit it,I have same problem
no,I havnt, finally I use gml3
