### ISSUE TITLE
Overview control reacting strange in v6

### ISSUE THREAD

**Issue by jeroenvheel** [openlayers/openlayers#10073]
**Describe the bug**
When moving the box in the overview the the position of the map is out of place.
The map is moved to the place of the pointer instead of the center of the box.

![120593](https://user-images.githubusercontent.com/228655/65963566-53c3ab80-e45b-11e9-9ead-118a0269b402.gif)

**To Reproduce**
Open in the example page the overview example and move it around.
As you can see the the map snaps to the extent where the pointer of cursor was not then center of the box

**Expected behavior**
It will move the map to the center of the box

**Comment by mike-000** [comment]
That will be because the positioning of the overlay was changed from bottom left to center to allow the box to rotate, so a half width and height adjustment when centering the map is now wrong.
