### ISSUE TITLE
Continuous ZoomOnScroll looses the mouse position when using constrainResolution true

### ISSUE THREAD

**Issue by hmdavidjunior** [openlayers/openlayers#10071]
**Describe the bug**
on the map with constrainResolution, when zooming with scroll, the position of the map start to change like crazy, doesnt matter if its zoom in or zoom out.

**To Reproduce**
1. set View constrainResolution  true
2. place the mouse far from the map center
3. scroll fast to zoom (when zoom changes more then 2 levels, the map position of the mouse snaps )

**Expected behavior**
keep the mouse position on the map

**Comment by hmdavidjunior** [comment]
the problem lies in "ol/interaction/MouseWheelZoom". Anchor coordinate changes midway.

**Comment by jahow** [comment]
+1, have noticed this also

**Comment by mike-000** [comment]
There is a general issue with constrained anchored animations being cancelled.  Wait for this animation to stop (it is cancelled while at a fractional zoom) https://codesandbox.io/s/simple-tudh4 then attempt to zoom in on the Galapagos.  The view immediately snaps to an integer zoom using the view center as anchor so the pointer is no longer over the Galapagos.

**Comment by tschaub** [comment]
Here is an example that sets `constrainResolution: true`: https://codesandbox.io/embed/simple-nbb80 (with the `ol@6.0.1` release).  Can you see the problem in that example?  I'm not sure I'm seeing it.

If you can edit that example until the problem can be spotted, that would help verify the issue.

**Comment by mike-000** [comment]
Forcing an immediate resolving of constraints with the anchor seems to fix it https://codesandbox.io/s/simple-siywi

**Comment by richnic** [comment]
I have testet both fixes #10078 and #10120 with various browsers (Firefox, Chrome, IE). With both, "MouseWheelZoom" interacts much better with "constrainResolution: true". Is it planned to integrate one of the fixes in the next release?

**Comment by jahow** [comment]
@richnic thanks a lot for taking the time to test. I agree with you: it'd be great to have this in the next release. This bug has been there for a while now.

@tschaub what's your opinion on this? should we merge Mike's latest PR?
