### ISSUE TITLE
Small amount of rotation does not appear to stick on first rotation

### ISSUE THREAD

**Issue by elliotlarson** [openlayers/openlayers#10080]
**Describe the bug**

I'm attempting to animate the rotation of my map in increments of 5 degrees.  There are a couple of cases where there appears to be a twitch in the display.

Here are a couple of animated gifs that highlight the issue (I'm assuming they are related):

1. `Rotating from 0 to 5 degrees and clicking to pan the map resets to 0 degrees`

    I have a custom rotation button that rotates the map by 5 degrees.  The first time I click the button to rotate, the map rotates correctly.  But when I click on the map to try and pan it, it seems to reset to zero degrees rotation.  

    If I apply the rotation more than once, the subsequent rotations work and panning the map after them does not result in this reset behavior.  So, the reset behavior only appears to happen after the first 5 degree rotation.

    ![animation-twitch-on-second-rotation](https://user-images.githubusercontent.com/73437/66071299-c7bb8d80-e507-11e9-8667-72957201f122.gif)

1. `During the second rotation the map flicks back to 0 and animates to 10 degrees`

    When I click to rotate by 5 degrees the second time it appears to flick back to zero and then animate to 10 degrees.  It's as if the results for the first animation aren't correctly saved somewhere (guessing).  

    After the second click of the rotate button, this does not occur.  However, if I use the OL rotate button to go back to zero, the problem shows up again on the second rotation click.

    ![rotate-does-not-stick](https://user-images.githubusercontent.com/73437/66071537-2aad2480-e508-11e9-8288-df7339dbad0c.gif)

**To Reproduce**

I have a function I call that uses `View#animate`.  The code looks roughly like:

```javascript
function rotate(map) {
  const degrees = 5;
  const radians = (degrees * Math.PI) / 180;
  const view = map.getView();
  const currentRotation = view.getRotation();
  const newRotation = currentRotation + radians;
  view.animate({
    rotation: newRotation,
    duration: 300,
  });
}
```

The twitch occurs on the second rotation, so doing something like the following should reveal the issue:

```javascript
rotate(map); // first rotate from 0 to 5 degrees
rotate(map); // second rotate from 5 to 10 degrees where the twitch appears
```

**Comment by mike-000** [comment]
That is expected behaviour. See the API https://openlayers.org/en/latest/apidoc/module-ol_View-View.html

> Rotation constraint. false means no constraint. true means no constraint, but snap to zero near zero. A number constrains the rotation to that number of values. For example, 4 will constrain the rotation to 0, 90, 180, and 270 degrees.

The default is true **`snap to zero near zero`**  You either need to specify either  `constrainRotation: false` in the View constructor for no constraint or .`constrainRotation: 72` for 5 degree intervals.

**Comment by elliotlarson** [comment]
Ah, nice!  That was it.  Thank you so much for pointing that out.
