### ISSUE TITLE
Stop control buttons from 'remain selected' after being clicked

### ISSUE THREAD

**Issue by frasersab** [openlayers/openlayers#10084]
**Problem**
When you click zoom in/zoom out the button you just clicked remains a darkened colour, until you click away. I would like the buttons to only change colour while you are hovering over them and then go back to normal once you are no longer hovering over them.

Google maps doesn't do this, and from a user interface perspective it doesn't make sense.

**Solution**
This is all done in ol.css from lines 162 to 166
I want to get rid of the line '.ol-control button:focus' from the below code so that the same behavior that is applied to hover does not get applied to the focus.

```
.ol-control button:hover,
.ol-control button:focus {
    text-decoration: none;
    background-color: rgba(0,60,136,0.7);
}
```

**Comment by tonio** [comment]
Having visual feedback on focused button sounds like a good idea, for accessibility purpose. It's easy to override if you don't like it, but should be kept as a default in the library imho.

**Comment by frasersab** [comment]
But when you click zoom in and then move away it shouldn't remain a darker colour. That doesn't make sense, and it's not how other maps do it for that same reason.

Google, leaflet, Bing and Apple all have the behavior I'm describing

**Comment by tonio** [comment]
Bing buttons are triggerable with the keyboard (at least they're coherent in bad practices), & google maps is, in a very opinionated way:
![Screenshot from 2019-10-03 08-38-20](https://user-images.githubusercontent.com/21686/66104700-be8af900-e5b9-11e9-9da8-5b7720f8bc48.png)

Having button focused after click is the default browser behaviour, I still think it's a bad idea to avoid it, moreover when the behavior you're expecting is achievable with 2 lines of css.

But I'm open to hear other's opinion about it.

**Comment by ahocevar** [comment]
I agree with @frasersab that control buttons should not remain displayed focused after moving the pointer away from them. The default should be to not focus on a standard map, and only focus when the map container has a `tabindex` attribute, which is needed to enable accessibility options anyway.

**Comment by tonio** [comment]
> I agree with @frasersab that control buttons should not remain displayed focused after moving the pointer away from them.

It's the case if you don't focus it by clicking. If you click it, it's standard behavior to be focused.

> The default should be to not focus on a standard map, and only focus when the map container has a `tabindex` attribute, which is needed to enable accessibility options anyway.

Well, that's not true. On the [simple example](https://openlayers.org/en/master/examples/simple.html), a click on the zoom button make it have focus, meaning they are keyboard triggerable after this. If you force unfocus, you need to re-focus the button before being able to trigger.

If the focus is kept, hiding it is a [bad practice](https://checklists.opquast.com/en/qualiteweb/keyboard-focus-is-neither-removed-nor-hidden).
