### ISSUE TITLE
ol.js doesn't have WebGLPointsLayer 

### ISSUE THREAD

**Issue by Syniex** [openlayers/openlayers#10089]
To import WebGLPointsLayer using npm i used:
` import WebGLPointsLayer from 'ol/layer/WebGLPoints';
`
I am trying to use ol.layer.WebGLPoints but it doesn't work, what is the correct path?

**Comment by ahocevar** [comment]
The WebGLPointsLayer is not yet part of the stable API, so it is not included in the legacy build. To use it, change your application to use the [ol package](https://npmjs.com/package/ol) instead of the legacy build (ol.js).

**Comment by gberaudo** [comment]
@Syniex, if for some reason you can not do like @ahocevar suggested, you might want to have a look to https://github.com/geoblocks/legacylib which I used at some point to generate an OL5 "full" legacy library.

**Comment by DooMachine** [comment]
@ahocevar I used npm and installed latest version (6.0.1) but, there's no WebGLPointsLayer in downloaded file. Am I missing something?

**Comment by wiedehopf** [comment]
I was rather lost trying to build a replacement for the released, minified ol.js that can be included using <script src=, here is how i did it for my project: 
https://github.com/wiedehopf/ol-rollup/commit/d58a62d2fcfc5d1ee6ab69f0ae79843e354df63d

It's probably a terrible approach but i don't have much npm or bundling experience so i'm glad it works and functions as a drop in replacement for the library release by OpenLayers.
That way i can start trying out the WebGLPointsLayer without having to mess with npm all the time in my project but only when i want to upgrade to a new OL version.

**Comment by ahocevar** [comment]
You might be interested to hear that the legacy build now includes the whole library - not just the supported API. See #11715.
