### ISSUE TITLE
Graticule doesn't display label when using custom label style

### ISSUE THREAD

**Issue by Akuukis** [openlayers/openlayers#10092]
**Describe the bug**
Graticule doesn't display label when using custom label style

**To Reproduce**

Use Graticule, notice that labels are shown. Add LabelStyle, refresh, and notice that labels don't show at all. E.g.
```
new Graticule({
    lonLabelStyle: new Text({
        font: '12px Calibri,sans-serif',
        textAlign: 'start',
        textBaseline: 'bottom',
        fill: new Fill({
            color: 'rgba(0,0,0,1)',
        }),
        stroke: new Stroke({
            color: 'rgba(255,255,255,1)',
            width: 3,
        }),
    }),
}),
```

I checked source and it it suspicious that `text: label` is not passed anywhere when custom style is used [here](https://github.com/openlayers/openlayers/blob/master/src/ol/layer/Graticule.js#L337).

**Expected behavior**
Either apply custom style, or remove config value.

**Comment by mike-000** [comment]
If you added` text: 'some random text',` to the above it would be displayed, but anyone wanting that could use `lonLabelFormatter`.  It should be set in cached style using a clone of the option setting.
