### ISSUE TITLE
map.forEachLayerAtPixel still return image layer even though clicked outside polygon

### ISSUE THREAD

**Issue by hanifsulong** [openlayers/openlayers#10099]
I am having an issue using ol version 6.0.1, as I clicked outside imagewms polygon, its still catch that layer and when multiple layers were visibled, it will detect the top layer even if I click outside the top layer's feature. I already set transparent to true. This is not happening when I use 5.3.3 version. Please kindly help me!

**Comment by ahocevar** [comment]
See #9720 for a solution.

**Comment by hanifsulong** [comment]
Thank you! It works now

**Comment by boeckMt** [comment]
Is it possible that this Issue still exists in version 6.4.3?

I have created a codesandbox (https://codesandbox.io/s/foreach-layer-atpixel-imagelayer-pl2w7?file=/main.js:1431-1484) with an example. 
It has to layers (WMS ImageLayer and OSM TileLayer) which are clipped to a extent and both got the `className` property. So if clicking outside it shouldn't detect any layer (in `forEachLayerAtPixel`) from my understanding, but the console shows that always the image layer is hit.

**Comment by boeckMt** [comment]
I think now I got the Issue for this, it is due to 'cross-origin data'.

The [CanvasLayerRenderer](https://github.com/openlayers/openlayers/blob/v6.4.3/src/ol/renderer/canvas/Layer.js#L301) returns in the case of a `DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D'` a empty `Uint8Array`, so the [CompositeMapRenderer](https://github.com/openlayers/openlayers/blob/v6.4.3/src/ol/renderer/Composite.js#L174) is getting some data and `forEachLayerAtPixel` is executing the callback.

If CORS are enabled on the webserver and the layer source uses `crossOrigin: 'anonymous'` everything is working like expected.
Check the codesandbox (https://codesandbox.io/s/foreach-layer-atpixel-imagelayer-pl2w7?file=/main.js:1210-1234) again and set  `crossOrigin: 'anonymous'` in line: 40.

if the `CompositeMapRenderer` would also check for the following case it should work.

```js
// https://github.com/openlayers/openlayers/blob/v6.4.3/src/ol/renderer/Composite.js#L174
...
if (data && !(data instanceof Uint8Array && !data.length)) {
    const result = callback(layer, data);
    if (result) {
        return result;
    }
}
...
```
I could make a pull request if it is desired.

**Comment by ahocevar** [comment]
@boeckMt Sounds good. I think it would be enough to test for
```js
if (data && data.length) {

**Comment by boeckMt** [comment]
@ahocevar the problem is, if I click outside of a layer extent (no color value in the map)  I would not expect that the `callback` of `forEachLayerAtPixel` is executed. So clicking on an area with no layer should not detect one.

**Comment by ahocevar** [comment]
Ok @boeckMt, I see the problem now. In this case, a better fix would be to not even enter the `try` block if the pixel is outside the extent range:
```js
...
    const context = this.context;
    const canvas = context.canvas;
    if (
      renderPixel[0] < 0 ||
      renderPixel[0] > canvas.width ||
      renderPixel[1] < 0 ||
      renderPixel[1] > canvas.height
    ) {
      return null;
    }

    let data;
    try {
...
```
Feel free to create a pull request with a fix along these lines. Thanks in advance!

**Comment by boeckMt** [comment]
@ahocevar, thanks for the suggestion!

I checked it shortly, but the `canvas.width` and `canvas.height` here is the whole area not the rendered layer Extent.
I could try to get the layer and its extent in `getDataAtPixel()` and then transform this extent to the pixel coordinates, but I don't know if this is the right way in terms of performance.

**Comment by ahocevar** [comment]
@boeckMt The renderer also has access to the layer, where the extent is configured. So you could do something like
```js
    const extent = this.getLayer().getExtent();
    if (extent) {
      const coordinate = applyTransform(
        frameState.pixelToCoordinateTransform,
        pixel.slice()
      );
      if (!containsCoordinate(extent, coordinate)) {
        return null;
      }
    }

**Comment by boeckMt** [comment]
@ahocevar I did something similar https://github.com/openlayers/openlayers/compare/main...boeckMt:fix-layer-at-pixel-image but can adjust it like in your example and check for the extent.

Furthermore I have problems running the tests. Eslint is bringing up lot of errors ```error  Delete `␍`  prettier/prettier``` and also some other tests failing.

**Comment by ahocevar** [comment]
To fix the formatting, run `npm run lint -- --fix`. Some rendering tests fail locally because of different font rendering, so you shouldn't have to worry about those (the CI will complain if they also fail there). To only run the unit tests (which should also pass locally), run `npm run karma`.
