### ISSUE TITLE
Declutter text style problem

### ISSUE THREAD

**Issue by jeroenvheel** [openlayers/openlayers#10098]
**Describe the bug**
In version 5.3 and  6.0.1 we have a problem with the declutter option.
When we use a text style array with two text styles on it so we can fix the placement of the text within a border. but if w use this with declutter set to true the style is not renderd correctly.

**To Reproduce**
1. Create a basic map
2. Add a separate layer for the labels
3. Add a array of text styles

See this example : https://codesandbox.io/s/vector-label-decluttering-njpsw

**Expected behavior**
The labels are generated with declutter

without declutter on labelLayer :
![image](https://user-images.githubusercontent.com/228655/66310155-c4f7d880-e90b-11e9-9cb4-1fbafc79cd53.png)
with declutter on for labelLayer:
![image](https://user-images.githubusercontent.com/228655/66310195-dd67f300-e90b-11e9-907c-7f48b813b0d1.png)

````javascript 
import "ol/ol.css";
import Map from "ol/Map";
import View from "ol/View";
import GeoJSON from "ol/format/GeoJSON";
import VectorLayer from "ol/layer/Vector";
import VectorSource from "ol/source/Vector";
import { Fill, Stroke, Style, Text } from "ol/style";

var map = new Map({
  target: "map",
  view: new View({
    center: [0, 0],
    zoom: 1
  })
});

function stylef(feature, resolution) {
  var text = feature.get("name");
  var boxStyle = new Style({
    text: new Text({
      placement: "point",
      text: text,
      font: "12px Calibri,sans-serif",
      overflow: true,
      fill: new Fill({
        color: "rgba(0,0,0,0)"
      }),
      stroke: new Stroke({
        color: "rgba(0,0,0,0)"
      }),
      backgroundFill: new Fill({
        color: "#fff"
      }),
      backgroundStroke: new Stroke({
        color: "#000"
      })
    })
  });
  var labelStyle = new Style({
    text: new Text({
      placement: "point",
      text: text,
      font: "12px Calibri,sans-serif",
      overflow: true,
      fill: new Fill({
        color: "#000"
      }),
      stroke: new Stroke({
        color: "#fff",
        width: 3
      })
    })
  });

  return [boxStyle, labelStyle];
}

var countryStyle = new Style({
  fill: new Fill({
    color: "rgba(255, 255, 255, 0.6)"
  }),
  stroke: new Stroke({
    color: "#319FD3",
    width: 1
  })
});

var labelLayer = new VectorLayer({
  declutter: false, // <-- this will not work :'(
  source: new VectorSource({
    url: "data/geojson/countries.geojson",
    format: new GeoJSON()
  }),
  style: stylef
});

var vectorLayer = new VectorLayer({
  declutter: false,
  source: new VectorSource({
    url: "data/geojson/countries.geojson",
    format: new GeoJSON()
  }),
  style: countryStyle
});
map.addLayer(vectorLayer);
map.addLayer(labelLayer);

**Comment by mike-000** [comment]
It's not because of an array.  Even with a single layer and the polygon and text parts in a single style the background fill and stroke is only applied to one feature (in the case of the example it looks like the last country visible in alphabetic order) and often the background is empty because the label has been decluttered.  https://codesandbox.io/s/vector-label-decluttering-9jyxf

**Comment by jeroenvheel** [comment]
Shall I update the title ?

**Comment by ahocevar** [comment]
Looks like these issues are related, but not the same.
