### ISSUE TITLE
Blurry features while moving OpenLayers map

### ISSUE THREAD

**Issue by sc-dawidrutkowski** [openlayers/openlayers#10095]
I'm using OpenLayers 6.0.1 to display multiple features on the map. Everything is nice and sharp until I start moving map. The features look like that:

![image](https://user-images.githubusercontent.com/33089653/66290849-99132d80-e8e0-11e9-93b8-29c94c5bb6a5.png)

But when I will move the map they become blurry till I release the mouse button. Take a look:

![image](https://user-images.githubusercontent.com/33089653/66290895-b647fc00-e8e0-11e9-9ca2-f13e34595bef.png)

Is that normal? Can I do something about it?

I'm defining View like this:

```
view: new ol.View({
    center: ol.proj.fromLonLat([17, 52]),
    resolutions: tileLayer.tileSource.getTileGrid().getResolutions(),
    zoom: 3
})
```
I've read somewhere that missing `resolutions` property could create such effect but this didn't help in my case.
(I asked this question also here: https://stackoverflow.com/questions/58260919/blurry-features-while-moving-openlayers-map)

**Comment by ahocevar** [comment]
This is by design. When the map image is static, we want a sharp image, so we snap the icons to an integer pixel. When the map is moving, we do not want the images to jump around, so we render them at the exact calculated position, which makes them blurry.

**Comment by sc-dawidrutkowski** [comment]
Thanks for the clarification!
