### ISSUE TITLE
Events with SVG targets in custom controls are not stopped by overlayContainerStopEvent

### ISSUE THREAD

**Issue by thebluegreeny** [openlayers/openlayers#10091]
**Describe the bug**
When an SVG element is used in a custom control, its events are not stopped by the overlayContainerStopEvent. The reason seems to be a condition in  PluggableMap.prototype.handleMapBrowserEvent. Targets are checked for being an instance of HTMLElement, which is not the case for SVG elements (at least not in Chromium 76.0.3809.132 (64-bit) or Firefox Quantum 69.0.1 (64-bit)).

**To Reproduce**
Create a button with an SVG element in a custom control. Starting a drag on the SVG element allows to drag the map.

**Expected behavior**
No event with a target in overlayContainerStopEvent is propagated to the map.

**Comment by fredj** [comment]
Hi @thebluegreeny I've tried to reproduce this issue with:
https://codesandbox.io/s/svg-controls-vc7cg
But everything seems to work as expected.

The yellow div is an `svg` element and the events are correctly stopped.

**Comment by thebluegreeny** [comment]
Hi @fredj , I guess my description lacked some precision. Sorry for that. Your example code works also fine for me. As I understand it, `document.createElementNS` should be used for creating SVG elements. This is when the bug appears. See [https://codesandbox.io/s/svg-controls-u6i7e](https://codesandbox.io/s/svg-controls-u6i7e).

**Comment by fredj** [comment]
@thebluegreeny yes, I see the issue now. See #10255

**Comment by fredj** [comment]
@thebluegreeny fixed with #10091
