### ISSUE TITLE
OL6 : Canvas element not created if the map's height is set to 100%

### ISSUE THREAD

**Issue by SimonChatillon** [openlayers/openlayers#10113]
When I set the height of my map div to 100%, nothing is displayed, the canvas element doesn't appear in the DOM. 

It works if I set the height to 400px for instance, but I need my map to be responsive.

It used to work fine with OL 5.3, I saw nothing about this in the 'Backwards incompatible changes' section of the release note.

Any advice ?

**Comment by mike-000** [comment]
Try

```
html, body, .map {
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
}
```
 
as in the Full Screen Mobile example

**Comment by SimonChatillon** [comment]
I see, it was because my map were in an angular component whose element had no height nor width by default. 

It works fine now, thanks !
