### ISSUE TITLE
Fill Polygon with polylines not with image or style

### ISSUE THREAD

**Issue by mumairr** [openlayers/openlayers#10122]
Hi all,
I am looking for some possibility of automatically filling up a polygon with polylines as soon as drawing of polygon ends.
What I am looking for is something like this:[https://viglino.github.io/ol-ext/examples/style/map.style.pattern.html](url)
![addLines](https://user-images.githubusercontent.com/8802065/66731160-58cb2680-ee6f-11e9-81f5-9100ed3786c6.png)

Please guide, I am unable to find a solution.

Thank you

**Comment by fredj** [comment]
Hi @mumairr, you can use a CanvasPattern for the fill style, see:
https://openlayers.org/en/latest/examples/canvas-gradient-pattern.html

**Comment by mumairr** [comment]
> 
> 
> Hi @mumairr, you can use a CanvasPattern for the fill style, see:
> https://openlayers.org/en/latest/examples/canvas-gradient-pattern.html

As I said in the question, I am not looking for a style thing. I am looking for actual polylines, features to be precise. Not only  a stroke :)
