### ISSUE TITLE
Map in ShadowRoot without native Pointer Events: No Interactions working

### ISSUE THREAD

**Issue by DaniEll-AT** [openlayers/openlayers#10128]
**Environment**
A Browser without native support for [Pointer Events](https://caniuse.com/#feat=pointer)
e.g.: 
- Safari @ iOS with iOS < 13 (latest iOS for iPhone 6, sold [until 13 month ago](https://en.wikipedia.org/wiki/IPhone_6) is 12.4.2)
- Firefox for Android

**Describe the bug**
When an OL6 Map is inside a ShadowDOM, interactions like panning the map etc. do not work.

**To Reproduce**
1. Open this example on [codesandbox.io](https://codesandbox.io/s/simple-zzwp9) with Safari @ iOS 12 or Firefox for Android
2. Try to pan the map
3. See the whole page moving

**Expected behavior**
The map instead of the page is moving.

**Additional Notes**
The issue is not present with OL 5.3.x.
When i revert to 5.3.3 without any other change to my Code, it works as expected.

**Comment by DaniEll-AT** [comment]
I found a seemingly related issue for Leaflet: https://github.com/Leaflet/Leaflet/issues/6705

**Comment by DaniEll-AT** [comment]
can anybody reproduce this issue and confirm its a bug?

**Comment by DaniEll-AT** [comment]
This is still an issue using 6.1.1-dev.1575987960427.

@ahocevar can you help? This is the last thing stopping us from upgrading OL to Version 6.

**Comment by ahocevar** [comment]
@DaniEll-AT Can you do a `git bisect` to find the commit that broke it? Then it should be easier to fix. Another thing you could try is configure your bundler to replace `elm-pep` with a noop. For webpack, this would be https://webpack.js.org/loaders/null-loader/.
