### ISSUE TITLE
applyTransform() fails on MultiLineString

### ISSUE THREAD

**Issue by richnic** [openlayers/openlayers#10121]
**Describe the bug**
It seems to me that applyTransform() fails on MultiLineString geometries.

**To Reproduce**
In the API manual is written that applyTransform() applies a transform function to each coordinate of a geometry. Therefore in the following javascript code both variants "Snippet 1" and "Snippet 2" should produce identical output:

> var trk, mls, map = new ol.Map({
>  target: 'map',
>  layers: [new ol.layer.Tile({source: new ol.source.OSM()})],
>  view: new ol.View({center: ol.proj.fromLonLat([7,50]), zoom: 4})
>});
>if (flg) { // Snippet 1
>
>  trk = [ [[0,51],[2,48],[4,50]] , [[4,52],[13,52]] ];
>  mls = new ol.geom.MultiLineString(trk);
>
>} else { // Snippet 2
>
>  trk = [ [[51,0],[48,2],[50,4]] , [[52,4],[52,13]] ];
>  mls = new ol.geom.MultiLineString(trk);
>  mls.applyTransform(function(coordinate) { return coordinate.reverse(); });
>
>}
>var ftr = new ol.Feature({geometry: mls.transform('EPSG:4326', 'EPSG:3857')});
>var src = new ol.source.Vector({features: [ftr]});
>map.addLayer(new ol.layer.Vector({source: src}));

But the track segments displayed on the map differ:

![grafik](https://user-images.githubusercontent.com/38283296/66713006-53090e80-eda5-11e9-836d-e88c0970ac25.png)

**Tested with**
cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.0.1/css/ol.css
cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.0.1/build/ol.js

**Comment by mike-000** [comment]
Simply reversing the corrdinates will not work with most geometries.  It only works with a simple linestring (where the coordinates do not include elevation as with GPX) but it also reverses the direction of the string.  A correctly specified transform function https://openlayers.org/en/latest/apidoc/module-ol_proj.html#~TransformFunction would look like

```
mls.applyTransform(function (input, opt_output, opt_dimension) {
    var length = input.length;
    var dimension = opt_dimension !== undefined ? opt_dimension : 2;
    var output = opt_output !== undefined ? opt_output : new Array(length);
    for (i = 0; i < length; i += dimension) {
        var x = input[i];
        var y = input[i + 1];
        output[i] = y;
        output[i + 1] = x;
    }
    return output;
});
```


Don't confuse applyTransform with the forward and reverse transform functions for https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.addCoordinateTransforms which take a single coordinate pair

```
trk = [ [[51,0],[48,2],[50,4]] , [[52,4],[52,13]] ];
mls = new ol.geom.MultiLineString(trk);

var projLatLon = new ol.proj.Projection({ code: 'LatLon' });
ol.proj.addProjection(projLatLon);
ol.proj.addCoordinateTransforms(
    'EPSG:4326',
    projLatLon,
    function(coordinate) { return coordinate.reverse(); },
    function(coordinate) { return coordinate.reverse(); }
);
mls.transform('LatLon', 'EPSG:4326')

var ftr = new ol.Feature({geometry: mls.transform('EPSG:4326', 'EPSG:3857')});

```

**Comment by richnic** [comment]
I agree that the reverse() function does not work on 3-dimensional coordinates because [latitude, longitude, elevation] is converted to [elevation, longitude, latitude] which does not make sense in most cases. But for a value pair [latitude, longitude] the reserve() function returns [longitude, latitude], and that is OK.

The real problem is, that applyTransform() does not work as described in the API manual. The sentence "Apply a transform function to each coordinate of the geometry" implies that the transform function is called 5 times for a multiline string containing 5 coordinates, once for each value pair [latitude, longitude]. In reality [[[0,51],[2,48],[4,50]], [[4,52],[13,52]]] is converted to [0,51,2,48,4,50,4,52,13,52]. Afterwards the transform function is executed on this 1-dimensional array of 10 elements that results in [52,13,52,4,50,4,48,2,51,0]. Finally that is interpreted as [[[52,13],[52,4],[50,4]], [[48,2],[51,0]]].

The description in the API manual should be revised.

**Comment by mike-000** [comment]
"Apply a transform function to the coordinates of the geometry" might be more appropriate description when "A transform function accepts an array of input coordinate values".  There is also another OL6 API issue: applyTransform() is not appearing in the subclasses of SimpleGeometry as it did in previous versions (or maybe flat coordinate methods should not be in the public API when they can be achieved using projection transforms?)
