### ISSUE TITLE
Unexpected behaviour in v6.0.1 - Feature.getStyle()

### ISSUE THREAD

**Issue by wirdehall** [openlayers/openlayers#10131]
**Describe the bug**
In version 5.3.0 Feature.getStyle() returned an object, in version 6.0.1 it's now returning a function.

**To Reproduce**
1. Create a Feature and render it on the map.
2. Get the feature using VectorSource.getFeatureById().
3. Try to extract the style from the feature using Feature.getStyle().

**Expected behavior**
Previously it returned an object upon which I could call setImage() for instance.

**More information**
After debugging some more it appeares it returnes a function that is stored in the variable style_ on the feature object.
This function seams to be a static function that expects a feature as it's parameter.
When using that function and passing on the feature as a parameter i get an array of style objects back. In my case it only has one style on position 0.
Something like this:
`const style = feature.getStyle()(feature)[0]`
Or more readable:
```
const getStyleFunction = feature.getStyle();  
const stylesArray = getStyleFunction(feature);  
const style = styleArray[0];
```

Instead of previously:
`const style = feature.getStyle()`

**Comment by mike-000** [comment]
It should return whatever was set (which can be a function).  If I follow you steps 1, 2 and 3 and simply let the layer style the features it returns null.

**Comment by wirdehall** [comment]
Thank you mike-000 for your quick answer.
I'm not setting any style on the layer but actually setting it on each individual feature.
The fact remains thogh that there is a breaking change in how this code functions.
When I run the code with OL 5.3.0 it works. But if I run it with OL 6.0.1 the behaviour has changed.

Here's the code that set's the style on the feature:
```
    const styleProperties: any = {
      image: new Icon({
        src: '/assets/arrow_640_rotated_4p.png',
        scale: 0.8,
        color: this.getShipColor(asset)
      })
    };
    if (this.namesVisibleCalculated || this.speedsVisibleCalculated) {
      styleProperties.text = this.getTextStyleForName(asset);
    }

    const assetStyle = new Style(styleProperties);

    assetFeature.setStyle(assetStyle);
    assetFeature.getStyle().getImage().setOpacity(1);
    assetFeature.getStyle().getImage().setRotation(deg2rad(assetMovement.microMove.heading));
    assetFeature.setId(assetMovement.asset);
```

**Comment by mike-000** [comment]
I cannot reproduce it.  I get a single style object and can then call setImage directly https://codesandbox.io/s/icon-dxp1u

**Comment by wirdehall** [comment]
Mike-000 thank you again for your quick response and helpfullness. 
Thanks to you I now know alittle bit more about whats causing this error.

The problem seams to be that I'm not using the click event on the feature but a selection.
Apparently since the new version came out the behaviour of selections have changed.

I have replicated my code and the order I'm doing things using your example and have managed to replicate the issue:
https://codesandbox.io/s/icon-98cgy

Apparently the selection changes the style of the element.
Do you possibly know why and what to do about it?
I will continue my investigation as I'm waiting for your reply.

**Comment by wirdehall** [comment]
I think this commit changed the behaviour by giving selections a default style:
https://github.com/openlayers/openlayers/commit/2ccaed0acec464c378cae0ba90be820124b0d7c5

**Comment by wirdehall** [comment]
I think this commit might have changed the behaviour of selections styles? https://github.com/openlayers/openlayers/commit/2ccaed0acec464c378cae0ba90be820124b0d7c5

**Comment by wirdehall** [comment]
Okay so finaly figured it out. :)
Since I have multiple different types of things on my map that is selectable I can't have a single style for all selections. (They should look different from each other).

Apparently the new version changes the style of a feature in such away that it becomes a function.
It appears there is now no way to tell the selection to not set the detault style unless you override it with a new style function. Both `false` and `undefined` does not do the trick.

So to work around this I had to do this:
```
    this.selection = new Select({hitTolerance: 7, condition: click });
    this.selection.style_ = false;
    this.map.addInteraction(this.selection);
```

Now to if statement here: https://github.com/openlayers/openlayers/commit/2ccaed0acec464c378cae0ba90be820124b0d7c5#diff-9a7ba5dc076db4048de146ccd3df4127R348 resolves as false and my code works again.

**Comment by jahow** [comment]
Indeed the select interaction have been simplified and now alters the style of the selected features. I don't really see a way around this, so seeing as you're not using the style-changing powers of the Select interaction I'd advise you to rather use a pointer click event:
```js
map.on('singleclick', function(evt) {
  const features = map.getFeaturesAtPixel(evt.pixel);
  if (features) {
    // do something with features[0] here
  }
});
```

**Comment by mike-000** [comment]
ol/interaction/Select does test `if (this.style_) {` but it is meaningless because the initialisation

`this.style_ = options.style ? options.style : getDefaultStyleFunction();`

should be

`this.style_ = options.style !== undefined ? options.style : getDefaultStyleFunction();`

`null` or `false` could then be specified to prevent overriding the style

**Comment by mike-000** [comment]
The above would still need to be documented.  Previously a Select style only overrode a layer style.  If the feature already had a style that had precedence.  Backward compatibility could be maintained if the Select only sets its style on a selected feature if the feature has no style, and resets it to undefined when a feature is deselected.

**Comment by wirdehall** [comment]
@mike-000: Thank you so much for all the help. A real life saver.
I have made a merge-request and referenced this discussion.
