### ISSUE TITLE
React and Openlayers@6.x fails to render

### ISSUE THREAD

**Issue by oehm-smith** [openlayers/openlayers#10136]
**Describe the bug**
React and Openlayers@6.x fails to render.  Any version of 6 (I tried 6.0.1-dev.1571252146179, latest as of today and 6.0.0).  5.3.3 works fine.

**To Reproduce**
1. `npx create-react-app test-app`
2. Add the `Map.js` shown below
3. Update the `App.js` shown below
4. `npm i ol@6.0.1`
5. `npm start`
6. Observe that the page is blank.  React Dev tools shows there is a component.
7. `npm i ol@5.3.3`
8. Restart dev server (ctrl-c, `npm start`)
9. Observe that the map is rendering

## Map.js

    //externals
    import ReactDOM from 'react-dom';
    import React from 'react';
    
    import View from 'ol/View';
    import Projection from 'ol/proj/Projection';
    import olMap from 'ol/Map';
    import Tile from 'ol/layer/Tile';
    import OSM from 'ol/source/OSM';
    import Zoom from 'ol/control/Zoom';
    
    require('ol/ol.css');
    
    export default class Map extends React.Component {
        constructor(props) {
            super(props);
    
            this.view = new View({
                center: [-41925.302985762304, 4789880.268977703],
                zoom: 12,
                minZoom: 2,
                maxZoom: 28,
                projection: new Projection({
                    code: 'EPSG:3857',
                    units: 'm'
                })
            });
        }
    
        componentDidMount() {
            this.map =  new olMap({
                view: this.view,
                controls: [ new Zoom() ],
                layers: [new Tile({ source: new OSM() })],
                target: this.refs.mapContainer
            });
        }
    
        render() {
            console.log('-> render App')
            return (
                <div id="mapContainer" ref="mapContainer"> </div>
            );
        }
    }
    
    // module.exports = Map;
    
## App.js

    import React from 'react';
    import logo from './logo.svg';
    import './App.css';
    
    import Map from './Map'
    
    function App() {
      return (
        <div className="App">
          <Map/>
        </div>
      );
    }
    
    export default App;

**Expected behavior**

The map should render for version 6.0.0

**Comment by ahocevar** [comment]
Looks like your `mapContainer` div does not have any dimensions. You have to give it a width and height.

**Comment by oehm-smith** [comment]
Ok thanks (of course!).  Funny that `ol@5.3.3` doesn't have an issue with this.

I'm updating the code in the question with an `id` and adding the `App.css` file below for completeness for anyone following this.

    #mapContainer {
        height: 850px;
        width: 100%;
    }

**Comment by carsmie** [comment]
This might be obvious for some, for me it wasn't : 
one could use _height: 100%_ again if **all** parent container's (css elements) has a height specified, since % must be based of something.

**Comment by kamrankamrani** [comment]
i try this and my problem is in .css file, for the map container i used a min-height and min-width. i changed it to height and width and problem solved!
any ideas?
