### ISSUE TITLE
EPSG:4326 render

### ISSUE THREAD

**Issue by GarridoM** [openlayers/openlayers#10130]
**Describe the bug**
Hi! I am using openlayers to get map with openstreetmap with projection: 'EPSG:4326', but always, In the same position I see the map badly (as you can see in the photo). I am not sure how I can solve this.

**To Reproduce**
1. Basic example with projection: 'EPSG:4326' 

**Expected behavior**
See all the map with same size

**Comment by fredj** [comment]
Hi @GarridoM, if you use an osm layer (which is in 'EPSG:3857') and set the view to 'EPSG:4326', OpenLayers re-project the osm layer and the image is distorted.

If you want to interact with OpenLayers in 'EPSG:4326' only no matter what is the projection of the layers, you should use the new `useGeographic()` function.
See https://openlayers.org/en/latest/examples/geographic.html

**Comment by GarridoM** [comment]
Hi @fredj  thanks for the answer. I have tried your solution using `useGeographic()` function without set the view to 'EPSG:4326' and it solve the render in high latitudes. However, when I am use it with raster layer, the raster is not clear-cut and whitish, also It produces cuts in some parts.
