### ISSUE TITLE
Use dependabot instead of greenkeeper

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#10141]
Hi all,

I've been using [dependabot](https://dependabot.com/) instead of greenkeeper in most of my personal projects and I would propose to use it for OpenLayers.

In my opinion, the main advantages of dependabot is that the pull requests are automatically kept updated with the code base; no more manual rebase. It's also the case
when a new version of the dependency is released while the pull request is open: dependabot creates a new pull request and cleanup the old one.

**Comment by tschaub** [comment]
Sounds good to me.  Look like it will eventually be integrated (https://dependabot.com/blog/hello-github/).

**Comment by fredj** [comment]
I've installed dependabot and uninstalled greenkeeper.
It will run once a week and it can be changed here:
https://app.dependabot.com/accounts/openlayers/projects/105827

**Comment by ahocevar** [comment]
@fredj Do you have an idea how we could configure dependabot to only update packages when a new version outside the specified version range in package.json is available? Right now it is a bit aggressive.

**Comment by fredj** [comment]
The update strategy can be changed here:
https://app.dependabot.com/accounts/openlayers/projects/105827

The current value is "auto" but I guess we should change to "Increase versions only when required"
