### ISSUE TITLE
setInterval() in ol 6.0.1

### ISSUE THREAD

**Issue by Bear4** [openlayers/openlayers#10140]
In ol 6.0.1 function setInterval doesn't work
(in ol 5.3.0 works proper)
Any tip how to rewrite code to use setInterval?
Thanks in anticipation.

`var timer = setInterval(function(){ refresh_alarm_timeout(); }, 300000);`

Source, load, refresh function:

```
var vS_alarm_timeout = new ol.source.Vector({
	loader: function(extent) {
		$.ajax('/wfs_ant',{
			type: 'GET',
			data: {
				service: 'WFS',
				version: '1.1.0',
				request: 'GetFeature',
				typename: 'v_wezel_timeout',
				srsname: 'EPSG:3857',
				bbox: extent.join(',') + ',EPSG:3857'
				},
			}).done(ldFe_alarm_timeout);
		},
		strategy: ol.loadingstrategy.bbox
	});
```
```
var ldFe_alarm_timeout = function(response) {
	formatWFS = new ol.format.WFS();
	fT_alarm_timeout = formatWFS.readFeatures(response);
	vS_alarm_timeout.addFeatures(fT_alarm_timeout);
  };
```
```
function refresh_alarm_timeout(){
	vS_alarm_timeout.clear(true);
	vS_alarm_timeout.addFeatures(fT_alarm_timeout);
} 
```

**Comment by jahow** [comment]
Hi,

Maybe your issue is related to this breaking change? https://github.com/openlayers/openlayers/blob/master/changelog/v6.0.0.md#change-of-the-behavior-of-the-vector-sources-clear-and-refresh-methods

You could try changing `vS_alarm_timeout.clear(true)` to `vS_alarm_timeout.refresh()`.

**Comment by Bear4** [comment]
Thanks, but refresh() remove all features.
I want simply add new and clear old without ugly flashing effect.
Seems to not call source load (vS_alarm_timeout) to get a new features:
`vS_alarm_timeout.addFeatures(fT_alarm_timeout);`

**Comment by jahow** [comment]
Could you set up a simple reproduction case on codesandbox.io for example? Otherwise it's hard to really help you on this. Thanks.

**Comment by Bear4** [comment]
Yes, this work smootly:
`
function refresh_alarm_timeout(){
	vS_alarm_timeout.refresh();
	vS_alarm_timeout.addFeatures(fT_alarm_timeout);
} 
`
You made mi day :) huge thanks!
Yesterday I tried refresh() without addFeatures and had effect features that disappear and appear (my source exposes features every 2 min but not every features disappear some may get new data e.g. temperature).
