### ISSUE TITLE
getStyle() returns function instead of style object in ol/interaction/Select~SelectEvent

### ISSUE THREAD

**Issue by soberdor** [openlayers/openlayers#10152]
ol/interaction/Select~SelectEvent passes the feature arrays "selected" and "deselected". However, the contained features' getStyle() function doesn't return a style object but a function instead.

![grafik](https://user-images.githubusercontent.com/27883798/67208887-a0752380-f416-11e9-86a5-b5ef4b9a9db4.png)

**Comment by jahow** [comment]
Hi,

This issue is a duplicate of https://github.com/openlayers/openlayers/issues/10131

**Comment by soberdor** [comment]
Ok I understand. However, when I try to call the returned function, another error pops up:

![grafik](https://user-images.githubusercontent.com/27883798/67222443-9f9bbc00-f42d-11e9-92ef-5e8d34f56c54.png)

**Comment by jahow** [comment]
It returns a function because the Select interaction changes the style of the selected feature (to a style function). You can either set the `style` property of the select interaction to `false`, or use `map.on('singleclick')` instead.
