### ISSUE TITLE
Name collision of target_ property in Control and Target

### ISSUE THREAD

**Issue by ejn** [openlayers/openlayers#10158]
It looks like #10024 introduced a problem which leads to `ObjectEvents` dispatched on a `Control` with a custom target (parent element) having this parent element (`HTMLElement`) as their target instead of the `Control`.

The problem is caused by
 1. the `Target` class storing the target for the Event in the `target_` property, since #10024
 2. the `Control` class having always stored a custom parent element in the `target_` property
 3. `Control` inherits from `Target`. Calling `setTarget()` on a `Control` (or passing the `target` to the constructor) therefore also sets the `target` for Events generated by this `Control`, which I do not believe is the intended behaviour and is certainly a change since 5.3.x

To reproduce (e.g. with 6.0.1):
 1. Create a Control with a custom target, e.g. `new MousePosition({target: document.getElementById("pos")});`
 2. Add a `propertychange`-listener to this `Control`
 3. Inspect the `target`-property of the `ObjectEvent` received by the listener: This is the `HTMLElement` and not the `MousePosition`.

I guess the (private) `target_` property either in `Target` (introduced in #10024) or in `Control` should be renamed. Since the property in `Target` is newer, renaming this (e.g. to `eventTarget_`) would seem preferable.

**Comment by ahocevar** [comment]
Good find, thanks for reporting this. Would you be able to provide a pull request with your suggested fix?

**Comment by ejn** [comment]
Yes, I can provide a PR - just wanted to check that the suggested solution would be acceptable first.

**Comment by fredj** [comment]
fixed with #10159, thanks @ejn
