### ISSUE TITLE
OpenLayers.Layer.WMS() function implementation 

### ISSUE THREAD

**Issue by WakandaKing** [openlayers/openlayers#10164]
Does anyone know where this following function is implemented in the OpenLayer Library.

======================================

      var layer = new  OpenLayers.Layer.WMS( "WMS {{layer.name}}",
            "../service?",
            {layers: "{{layer.name}}", format: "{{format}}", srs:"{{srs}}",
             exceptions: "application/vnd.ogc.se_inimage"{{if format == 'image/png'}}, transparent: true{{endif}}},
            {singleTile: true, ratio: 1, isBaseLayer: true} );

========================================
I am trying to do a fucntion call traceback and cant find the part that does the implementation.

**Comment by mike-000** [comment]
It is part of OpenLayers 2 (a separate and now very old repository) https://github.com/openlayers/ol2/blob/master/lib/OpenLayers/Layer/WMS.js

**Comment by WakandaKing** [comment]
Thank you Mike.

I have found the function implementation, My network analyzer shows that Openlayers sends a ping (ICMP) before it requests the layer/map. I went through the code and cannot find the part where this happens. Do you have an idea where this could be implemented in the Openlayers?

**Comment by ahocevar** [comment]
Closing this, as it is OpenLayers 2 related.
