### ISSUE TITLE
Use target="_blank" in default attributions

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10167]
**Is your feature request related to a problem? Please describe.**
If the TOS permit would it be better to set links in the default attributions (OSM, Stamen, Bing) to open in a new tab or window?  Especially with the non-collapsible OSM attribution there is a risk of for example accidentally clicking a link instead of a feature or location and losing work.

**Describe the solution you'd like**
Specify `target="_blank"` in the links

**Comment by tonio** [comment]
Couldn't find any reason not to do it in [OSM Copyrights](https://www.openstreetmap.org/copyright).
