### ISSUE TITLE
Heatmap issue with GeoJSON and loadingstrategy as tile

### ISSUE THREAD

**Issue by bogdanvaduva** [openlayers/openlayers#10173]
Hi 

I am trying to create a Heatmap with a GeoJSON source and loadingstrategy.tile. I am running the code below and openlayers is not displaying anything or crashes the browser.

var source = new ol.source.Vector({
                            format: new ol.format.GeoJSON({
                                dataProjection: projectionCode,
                                geometryName: geometryName
                            }),
                            loader: function(...),
                            strategy: ol.loadingstrategy.tile(new ol.tilegrid.createXYZ({extent: getExtent() })),
                            projection: projectionCode
                        });

var vector = new ol.layer.Heatmap({
              source: source,
              blur: 25,
              radius: 15
            });

vector.getSource().on('addfeature', function(event) {
              event.feature.set('weight', 1);
});

I managed to get round the problem by using loadingstrategy.tile with a ol.layer.Vector and using loader function to fill Heatmap source.

**Comment by jahow** [comment]
How many features are you adding in the source? It looks like your code updates each feature added in the source individually, which would cause a `changed` event at the source level and trigger a rebuild of the render instructions. If there are many features, this might very well be enough to make the browser crash.

**Comment by bogdanvaduva** [comment]
I don't have many features to load ( 100 +)
The issue it's related to loadingstrategy.tile from what i gathered debuging the code.

**Comment by jahow** [comment]
Maybe if you can provide us with a reproduction case we can take a look and make sure that the library is behaving as expected. Thanks

**Comment by bogdanvaduva** [comment]
Here is an example:

<!DOCTYPE html>

<html lang="en">
  <head>
    <title>Earthquakes Heatmap</title>
    
<script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v6.0.1/build/ol.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v6.0.1/css/ol.css">   
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<style>
      .map {
        width: 100%;
        height:400px;
      }
      #mouse-position {
          height: 25px;
          width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="map"></div>
    <form>
    <div id="mouse-position"></div>
      <label>radius size</label>
      <input id="radius" type="range" min="1" max="50" step="1" value="5"/>
      <label>blur size</label>
      <input id="blur" type="range" min="1" max="50" step="1" value="15"/>
    </form>
    <script>
        $(document).ready(function() {
            var blur = document.getElementById('blur');
            var radius = document.getElementById('radius');
            
            var mousePositionControl = new ol.control.MousePosition({
              coordinateFormat: ol.coordinate.createStringXY(4),
              projection: 'EPSG:4326',
              // comment the following two lines to have the mouse position
              // be placed within the map.
              className: 'custom-mouse-position',
              target: document.getElementById('mouse-position'),
              undefinedHTML: '&nbsp;'
            });

            var raster = new ol.layer.Tile({
              source: new ol.source.Stamen({
                layer: 'toner'
              })
            });

            var map = new ol.Map({
              layers: [raster],
              controls: ol.control.defaults().extend([mousePositionControl]),
              target: 'map',
              view: new ol.View({
                projection: 'EPSG:4326',
                center: [0, 0],
                zoom: 2
              })
            });

            var source = new ol.source.Vector({
                format: new ol.format.GeoJSON({
                        dataProjection: 'EPSG:4326',
                    }),
                loader: function(extent, resolution, projection) {
                    var proj = projection.getCode();
                    var url = "https://www.chapelhillopendata.org/api/v2/catalog/datasets/bicycle-crash-data-chapel-hill-region/exports/geojson";
                    var xhr = new XMLHttpRequest();
                    xhr.open('GET', url);
                    var onError = function() {
                      source.removeLoadedExtent(extent);
                    }
                    xhr.onerror = onError;
                    xhr.onload = function() {
                      if (xhr.status == 200) {
                        source.addFeatures(
                            source.getFormat().readFeatures(xhr.responseText));
                      } else {
                        onError();
                      }
                    }
                    xhr.send();                    
                },
                strategy: ol.loadingstrategy.tile(ol.tilegrid.createXYZ({extent: map.getView().calculateExtent(map.getSize()) })),
                projection: 'EPSG:4326'
            });

            var vector = new ol.layer.Heatmap({
              source: source,
              blur: 25,
              radius: 15
            });
            
            map.addLayer(vector);
            
            var blurHandler = function() {
              vector.setBlur(parseInt(blur.value, 10));
            };
            blur.addEventListener('input', blurHandler);
            blur.addEventListener('change', blurHandler);

            var radiusHandler = function() {
              vector.setRadius(parseInt(radius.value, 10));
            };
            radius.addEventListener('input', radiusHandler);
            radius.addEventListener('change', radiusHandler);
        });        
    </script>
  </body>
</html>

**Comment by jahow** [comment]
Then maybe it's linked to the fact that you're using an XYZ tilegrid while being in EPSG:4326? Does the data render correctly with a regular vector layer?

**Comment by bogdanvaduva** [comment]
It's working in a similar way if i am  using a different epsg.
If i am using the same source ( with loading strategy and xyz) with a regular layer(vector) it works fine.

**Comment by mike-000** [comment]
There is also a problem with bbox strategy with a heatmap layer, the loader function is always passed an infinite extent https://codesandbox.io/s/heatmap-earthquakes-hslfb

In the case of tilegrid strategy that results in a loop:
![image](https://user-images.githubusercontent.com/49240900/67579066-a97a3380-f73b-11e9-90d6-98e618d4358c.png)

**Comment by jahow** [comment]
Ok, thanks @mike-000 I get it now, this line is the culprit:
https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/webgl/PointsLayer.js#L307

I'll make a PR to fix this
