### ISSUE TITLE
Minimum node.js version required for "build-legacy" is v12, not v8

### ISSUE THREAD

**Issue by TieSKey** [openlayers/openlayers#10179]
**Describe the bug**
the npm build-legacy command depends on String.matchAll which was implemented on node.js v12 but current docs state node.js 8 should work.

> shx cp src/ol/ol.css build/ol/ol.css
> 
> /media/Data/Desarrollo/Software/openlayers/node_modules/jsdoc-plugin-typescript/index.js:212
>           const typedefMatches = comment.value.replace(/\s*\*\s*/g, ' ').matchAll(typedefRegEx);
> 

**To Reproduce**
1. Clone the project on a system running node 10.x.x or older
2. run the build-legacy target

**Comment by ahocevar** [comment]
Thanks for reporting this. I have published a new version of jsdoc-plugin-typescript that does not rely on node's native matchAll implementation. I'll be updating the dependency here in a minute.
