### ISSUE TITLE
Decluttering conflict within feature styles (icon, label, shapes)

### ISSUE THREAD

**Issue by Chris1234567899** [openlayers/openlayers#10189]
When using decluttering in a vector layer, also multiple styles within a single feature have impact on each other.

For example a point that includes a label and an icon, is not displaying the label, when the icon would overlap it. Or a point with a CircleStyle and a label might run into the same thing, hiding the label if the radius of the circle is too big.
In my opinion within a feature, the decluttering should be deactivated, because it is quite possible that a label is supposed to overlap the corner of an icon with transparent background for example.
The decluttering should just affect the conflicts between features, imo.

If you think the current behavior is alright, please close this issue, it's just my 5cents.

Using ol 6.0.1

**Comment by mike-000** [comment]
Use a single style object containing the text and image styles.  If you separate them in a style array they will conflict and one will declutter the other.

**Comment by Chris1234567899** [comment]
Thanks for the hint, unfortunately this is not possible in every case.

For example I have a point feature with an icon and want to display the point together with the icon. Both use `image:`  so I would have:

```
new Style({
   image: new CircleStyle({...}),
   image: new Icon({...})
})
```
which obviously throws an error. Also, for more complex situations (eg modifying) you might want to show different geometries for the same feature (once the center, once the vertices, once the outline etc).

**Comment by ahocevar** [comment]
@Chris1234567899 In v5, it would have been possible to achieve what you want by using a MultiPoint geometry. But since #9870, it is not any more. When you look at the comments in #8954, you'll see why that change was made.
