### ISSUE TITLE
Code / documentation mismatch w.r.t. CSS colors in styles

### ISSUE THREAD

**Issue by raybellis** [openlayers/openlayers#10185]
Style functions used to be able to specify `hsla()` CSS colors (previously working in my app using 3.7) .   OL6 doesn't support this and throws exception 14, despite the documentation for that error saying "Valid colors are all CSS colors".

**Comment by mike-000** [comment]
hsla fill is working here https://codesandbox.io/s/vector-layer-407b2

**Comment by raybellis** [comment]
I'll see if I can reduce my code to a suitable test case, then.
