### ISSUE TITLE
How to split a vector feature?

### ISSUE THREAD

**Issue by orpheus** [openlayers/openlayers#10180]
**Is your feature request related to a problem? Please describe.**

I need to be able to split a feature. How would I do this manually or using a 3rd party library if Open Layers does not allow this?

**Describe the solution you'd like**

I'd like to be able add a Split interaction that allows me to draw over features and on 'splitDone', it would obviously, split, the feature into parts and return you those features as well as the original 'pre-split' feature. 

Thank you.

**Comment by orpheus** [comment]
thank you. I'll leave this open until someone else confirms that^ is the only solution

**Comment by ahocevar** [comment]
Splitting is not possible with OpenLayers directly. In addition to the above suggestion, you may want to give turf a try for splitting lines: https://turfjs.org/docs/#lineSplit. With jsts, you can also split polygons. See e.g. https://gis.stackexchange.com/questions/216977/how-to-split-the-polygon-operation-using-of-jsts.
