### ISSUE TITLE
Heatmap issue in ol6

### ISSUE THREAD

**Issue by yiwenzhang666999** [openlayers/openlayers#10183]
When I load the heat map with ol6, the heat map does not display properly, but it is normal in ol5.
Render the last data of the custom data (renderData) into the color of the heat map in the rendering in ol6
below is my main code

var renderData = [{"x":116.158,"y":40.059,"clusterCount":3277,"key":false},{"x":116.159,"y":39.8352,"clusterCount":3087,"key":false},{"x":116.159,"y":39.7424,"clusterCount":1154,"key":false},{"x":116.159,"y":39.9512,"clusterCount":1018,"key":false},{"x":116.159,"y":40.1556,"clusterCount":1108,"key":false},{"x":116.285,"y":39.9184,"clusterCount":2722,"key":false},{"x":116.301,"y":40.159,"clusterCount":2163,"key":false},{"x":116.301,"y":39.8116,"clusterCount":2064,"key":false},{"x":116.303,"y":40.045,"clusterCount":1216,"key":false},{"x":116.338,"y":39.7252,"clusterCount":341,"key":false},{"x":116.39,"y":39.959,"clusterCount":1185,"key":false},{"x":116.418,"y":39.8662,"clusterCount":2390,"key":false},{"x":116.437,"y":40.0473,"clusterCount":2668,"key":false},{"x":116.449,"y":40.1391,"clusterCount":596,"key":false},{"x":116.498,"y":39.7249,"clusterCount":1411,"key":false},{"x":116.51,"y":39.9506,"clusterCount":1182,"key":false},{"x":116.562,"y":40.0457,"clusterCount":1796,"key":false},{"x":116.572,"y":40.1645,"clusterCount":616,"key":false},{"x":116.572,"y":39.8435,"clusterCount":1508,"key":false},{"x":116.64,"y":39.7616,"clusterCount":528,"key":false},{"x":116.641,"y":39.9682,"clusterCount":802,"key":false},{"x":116.663,"y":40.1035,"clusterCount":81,"key":false},{"x":116.692,"y":39.884,"clusterCount":3,"key":false}];
   
	 var cSource= new ol.source.Vector();
	
	
        for (var index in renderData) {
            var point = renderData[index];
            var pointGeom = new ol.geom.Point([point.x, point.y]);
            var pointFeature = new ol.Feature({
                geometry: pointGeom
            });
            pointFeature.set('weight', point.clusterCount);
            cSource.addFeature(pointFeature);
        }
	var vectorHeatMap = new ol.layer.Heatmap({
		source: cSource,
		blur:15,
		radius:8,
		gradient:['#00f', '#0ff', '#0f0', '#ff0', '#f00'],
		weight:"weight",
		opacity:1
		
	});
	
	map.addlayer(vectorHeatMap
**Expected behavior**
![image](https://user-images.githubusercontent.com/31643589/67480127-fa355200-f691-11e9-8fdf-4977b3b35ac3.png)
![image](https://user-images.githubusercontent.com/31643589/67480214-13d69980-f692-11e9-9bc2-1383e315752f.png)

**Comment by fredj** [comment]
That's probable because the `weight` is not a value between 0 and 1:
https://openlayers.org/en/latest/apidoc/module-ol_layer_Heatmap-Heatmap.html

> Weight values should range from 0 to 1 (and values outside will be clamped to that range).

**Comment by jahow** [comment]
Then it would mean there is a regression since values are not clamped any more.

**Comment by fredj** [comment]
> Then it would mean there is a regression since values are not clamped any more.

You're right, and the weight should be 1 if the value is undefined:
https://github.com/openlayers/openlayers/blob/v5.3.3/src/ol/layer/Heatmap.js#L145

**Comment by yiwenzhang666999** [comment]
Thanks a lot!

**Comment by qfyn** [comment]
请问下你这个是web的还是app的？
