### ISSUE TITLE
White Tiles on bing maps

### ISSUE THREAD

**Issue by docgregt** [openlayers/openlayers#10199]
**Describe the bug**
When using Bing maps as a basemap as with following code:
`       var basemap = new TileLayer({
            visible: true,

            source: new BingMaps({
                imagerySet: 'Road',
                key: 'code',
                wrapX: true
            })
        });
`
I get the following white space when it is rendered:
![image](https://user-images.githubusercontent.com/43346207/67605558-e8a88480-f73b-11e9-9251-27229004a326.png)

If I zoom in further the white space gets filled in.

**To Reproduce**
1. use bing for basemap
2. Zoom in at least 3 levels in the Caribbean region
3. See image above.

**Expected behavior**
All tiles rendered correctly or at least provide zoom levels for which the Bing maps do work correctly. However, I did not see this issue before using Openlayers 6.01

Update: The error is not Bing maps, but rather the vector layer on top of it.
![image](https://user-images.githubusercontent.com/43346207/67608559-07ac1400-f746-11e9-951a-0b9855a31326.png)

**Comment by ahocevar** [comment]
Can you please share a minimal setup (i.e. with a vector layer) to help reproduce this issue?

**Comment by docgregt** [comment]
I went here:
https://openlayers.org/en/latest/examples/bing-maps.html?q=bing

Clicked on Edit.

Then I was able to repro it with the following changes:
import "ol/ol.css";
import Map from "ol/Map";
import View from "ol/View";
import TileLayer from "ol/layer/Tile";
import BingMaps from "ol/source/BingMaps";
import XYZ from "ol/source/XYZ.js";


var layers = [];
layers.push(
    new TileLayer({
      visible: true,
      preload: Infinity,
      source: new BingMaps({
        key: "your key",
        imagerySet: "Road"
        // use maxZoom 19 to see stretched tiles instead of the BingMaps
        // "no photos at this zoom level" tiles
        // maxZoom: 19
      })
    }),
    new TileLayer({
      source: new XYZ({
        url: "http://t1.openseamap.org/seamark/{z}/{x}/{y}.png"
      })
    })
  );

var map = new Map({
  layers: layers,
  target: "map",
  view: new View({
    projection: 'EPSG:4326',
    center: [31, 0],
    zoom: 0
})
});

and change the height to 1000px.

You have to zoom in quite far and then back out to world level a few times to get the white spaces to start showing up. They show up randomly at different zoom levels and in different places. I zoomed in around the Gibraltar area. I zoomed in until I could see the openseamap data. Then back out to world level.
I could not repro it without the projection change.

**Comment by jeroenvheel** [comment]
This also happens with other WMS / WMTS layers the same steps to reproduce this.
Zoom in and out and then randomly white tiles can appear.

**Comment by ahocevar** [comment]
@jeroenvheel So you also set a different projection in your view?

**Comment by jeroenvheel** [comment]
We have some EPSG:28992 layers
Will check if we can set them to EPSG:3857 and verify if the problems goes away.

**Comment by SinuheM** [comment]
Hello, I have the same issue with bing; but I dont see any tile.
It works with OSM and a XYZ Source

var bing = new ol.layer.Tile({
    preload: Infinity,
    source: new ol.source.BingMaps({
        key: bingKey,
        imagerySet: "Road"
    }),
    visible: false
});
var bingAerial = new ol.layer.Tile({
    preload: Infinity,
    source: new ol.source.BingMaps({
        key: bingKey,
        imagerySet: "AerialWithLabels"
    }),
    visible: false
});
var listLayers = [
    bing, bingAerial
];

var map = new ol.Map({    
    layers: listLayers,
    target: 'map',
    view: new ol.View({
        center: ol.proj.transform([-74.41177369, -9.65914919], "EPSG:4326", "EPSG:3857"),
        zoom: 6
    })
});
`

**Comment by docgregt** [comment]
I don't know if this helps, but I have several WMS and vectorTile layers on top of the bing maps and they seem to render over the white spaces. Here is an example:
![image](https://user-images.githubusercontent.com/43346207/67728955-dd13c280-f9b4-11e9-9267-b92246b01c4b.png)

Here it is without the wind vectors rendered and just a WMS SST layer:
![image](https://user-images.githubusercontent.com/43346207/67729007-0d5b6100-f9b5-11e9-918d-db3c779a7443.png)

**Comment by docgregt** [comment]
Hi @ahocevar, I am sure you are quite busy and I am not familiar with the OpenLayers development process. Is this issue something that you think will be fixed soon or is there some workaround we should use? I am not pressuring you, but just trying to find out from a planning standpoint. We are currently using OL5 in our production software and really need to switch to OL6 due to the improved way of constraining the map.

**Comment by ahocevar** [comment]
#10226 fixes this issue.

**Comment by docgregt** [comment]
I tested the dev version and the problem appears resolved. Thank you for your time.
