### ISSUE TITLE
Unable de import ol module

### ISSUE THREAD

**Issue by hexabyte23** [openlayers/openlayers#10206]
Hi all,
I am beginner in javascript and I don't succeed to use last v6.0.1-dist.zip file
I unzip the file in vendor/ dir and I try to do this in a HTML page

index.html

```
<script>
import Map from 'ol/Map';
</script>
```

Chrome ou Safari browser complains **Uncaught SyntaxError: Cannot use import statement outside a module**

then I try that way 

```
<script>
import Map from 'vendor/ol/Map';
</script>
```

with same result ... then I try to put JS code in a index.js file, same result.... 

No more ideas, before I let dow this too complex lib, could you help me please ?
thanks

**Comment by MoonE** [comment]
There's no need to use import statements when using the dist file.

Have a look at https://github.com/openlayers/openlayers/blob/master/doc/quickstart.hbs
