### ISSUE TITLE
html body using CSS(transform: scale), openlayers's event get badly

### ISSUE THREAD

**Issue by 5shell** [openlayers/openlayers#10211]
**Describe the bug**
with  <body style="transform: scale(0.8)">, then, mousePositionControl、or clickEvent，got a coordinate offset, but, it seems，correctly in leaflet、mapbox、maptalks, how can i solve it in openlayers
for example: 
 ol.source.OSM(), At BeiJing TianAnMen ,the point is [116.3913,39.9074]
but with scale(0.8), the point is [116.3896, 39.9082]

当body标签使用了css的transom scale样式后，鼠标事件会得到一个错误的坐标和事件，但是在leaflet等其他的开源框架中，这个功能是正常的
例如，使用  ol.source.OSM()图层，在北京天安门的图标处，正确的坐标是 [116.3913,39.9074]
但是当页面body被 scale(0.8)之后， 得到的坐标是[116.3896, 39.9082]

**Comment by ahocevar** [comment]
Can you please provide an example that shows the issue with https://codesandbox.io/?

**Comment by 5shell** [comment]
https://codepen.io/nShell/pen/JjjyorY?editors=0110

try and put your mouse on the center, they are show different coordinates
