### ISSUE TITLE
Missing release *.zip for v6.1.0

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#10219]
**Describe the bug**
The download links for v6.1.0-dist.zip & v6.1.0.zip are not working.

**To Reproduce**
1. Go to https://openlayers.org/download/
2. Click on either of the download links
3. See error

**Expected behavior**
Download starts for the selected file.

In the package-lock.json file the version is still 6.0.1.

**Comment by mfrederiksen-p44** [comment]
Download links appears to be working now.

**Comment by ahocevar** [comment]
Re-uploaded the release artifacts, and updated package-lock.json in master with 459efede602c994f0102882f4c0285f9a997440e
