### ISSUE TITLE
zIndex of unmanaged vector layer broken if zIndex=0 or unset

### ISSUE THREAD

**Issue by JackD83** [openlayers/openlayers#10234]
**Describe the bug**
The layer order of vector layer is broker on unmanaged layer if one layer has zIndex=0 or undefined. The order remains the order of insertion.

**To Reproduce**
- Add two unmanged layer with zIndex zero -> the order of the layers is the order of insertion
- change the zIndex of the first layer to 1 -> Layer should be on top of the second layer with index=0 but stays below
- change first layer to zIndex=2 and second layer to index=1 -> layer order is correct

You can find the example [here](https://codesandbox.io/s/icon-wnmd6?fontsize=14)

**Expected behavior**
Layer order should be correct

**Comment by Kai-W** [comment]
interestingly zIndex="0" works
