### ISSUE TITLE
Transparent OSM not working in Ol 6

### ISSUE THREAD

**Issue by Kai-W** [openlayers/openlayers#10236]
In OL 5 Open seamap was an transparent Overlay .
With OL 6 the Layer the layer is mostly opaque white

https://codesandbox.io/s/semi-transparent-layer-038nq

**Comment by jahow** [comment]
Quite weird, also putting an opacity of 0.99 makes the layer see-through again, but anything above that makes it opaque.

**Comment by fredj** [comment]
The OSM layer is `opaque` by default:
https://openlayers.org/en/latest/apidoc/module-ol_source_OSM-OSM.html
This property is then used to optimize the canvas rendering; that's why the canvas layer has no transparency.

Passing `opaque: true` in the options fixes the issue.

**Comment by Kai-W** [comment]
The OSM layer in 5.3.3 had the same API comment and it worked.
 * @property {boolean} [opaque=true] Whether the layer is opaque.
https://github.com/openlayers/openlayers/blob/v5.3.3/src/ol/source/OSM.js

**Comment by Kai-W** [comment]
Are there any plans to change it back to the old behavior?

**Comment by Kai-W** [comment]
I found an other interesteing effect. If im adding an transparent layer bevor the OSM Layer it gets transparent. I updated the example

**Comment by ahocevar** [comment]
> Are there any plans to change it back to the old behavior?

@Kai-W The old behavior was a bug, you should either use an OSM source with `opaque: false`, or an XYZ source for the open sea map layer.

> I found an other interesteing effect. If im adding an transparent layer bevor the OSM Layer it gets transparent.

This has to do with internal optimizations and combining layers to a single output canvas. In fact, the `opaque` option is nothing but an internal optimization.

**Comment by Kai-W** [comment]
For performance Reasons i do understand why the opacity is set to true. But i did like the old behavior more and is much more intuitive for an developer:
It just worked and if the performance is needed then it can be improved.
Now it is quite confusing. the default ist opaque but in some cases it is not
(a Layer with lower z-Index with opaque: false or opacity < 1)
And as far as i know there is no way the automatically find out if an OSM source contains transparent tiles. In dynamic Systems where layers can be added by the user i need to render all Layers with opacity:false

**Comment by ahocevar** [comment]
Kai-W Why don't you just use `ol/source/XYZ` for now? The OSM source is primarily meant as a convenience source for users who want to use the standard OSM base map.

Regarding confusion, I agree that exposing performance optimization properties to the user should be avoided where possible. Given the renderer changes for v6, we could possibly get rid of that option and assume everything but the first rendered layer to not be opaque. But then what if a user wants to set a background on the map viewport that should be visible in potentially transparent regions of the base layer?

So what I would suggest is this: if someone wants to do a profiling session, it would be interesting to evaluate how significant the performance impact of tile clipping is with the new v6 renderer. If it is neglectable, we could get rid of the `opaque` option and do tile clipping for all layers to support transparent tiles.

**Comment by Kai-W** [comment]
i stumbled upon my bug again and found more inconsistencies:

For the property opaque in ol/scource/
Tile
    jsdoc no default
    sets opaque to false if undefined.

UrlTile extends Tile
    jsdoc no default
    constructor passes on opaque from options to super without modification

TileImage extends UrlTile 
    jsdoc: default opaque=true
    constructor passes on opaque from options to super without modification

XYZ extends TileImage 
    jsdoc: default opaque=true
    constructor passes on opaque from options to super without modification

OSM extends XYZ 
    jsdoc: default opaque=true
    defaults to true if options.opqaue is undefined

So OSM is the only Layer scource that behaves according to the jsdoc (default is true) but is also the only one that behaves not like the others. They default to opaque=false despite the js doc says otherwise for XYZ and TileImage.
