### ISSUE TITLE
Why couldn't get geometry's coordinates in VectorTile

### ISSUE THREAD

**Issue by heavis** [openlayers/openlayers#10231]
I use ol.source.VectorTile  to display vector feature, and it support setStyle method which can return a feature function, but geometry object doesn't contain 'getGeometry' method.

I want to render geometry' path through stylish styles which depend on geometry's path, so there are any approaches that can get geometry info?

**Comment by ahocevar** [comment]
By default, when using `ol/format/MVT`, you get instances of `ol/render/Feature` as features, which are optimized for rendering performance.

To achieve what you want, you`ll need to configure your MVT format like this:
```
import MVT from 'ol/format/MVT';
import Feature from `ol/Feature`;

new MVT({
  featureClass: Feature
});
```

**Comment by heavis** [comment]
> By default, when using `ol/format/MVT`, you get instances of `ol/render/Feature` as features, which are optimized for rendering performance.
> 
> To achieve what you want, you`ll need to configure your MVT format like this:
> 
> ```js
> import MVT from 'ol/format/MVT';
> import Feature from `ol/Feature`;
> 
> new MVT({
>   featureClass: Feature
> });
> ```

Thank you for your reply, I have got the effect that I expected through your approach.
