### ISSUE TITLE
openLayer (5 /6) VectorLayer render in infinite loop

### ISSUE THREAD

**Issue by dsalasjanda** [openlayers/openlayers#10230]
**Describe the bug**
I'm usig open layers to render vector layera whit a lot of features based in IconImages which icon is a Base64 Image-URL
When the number of features increes I have the problem than a render event is trigger in a near infinite loop.
This causes a blink in the feature layer, that could causes epileptic attacks.

**To Reproduce**
this will be re relevan code of may sw: 
```js
  /**
     * add TOOLS Layer
     */
    public drawToolsFromServer() {
        this.mapToolsControllerService.getToolsUsingGET(this.mapComoponet.mapName).subscribe(response => {
            if (response != undefined && response.length > 0) {
                const olLayerVector: VectorLayer =  new VectorLayer({
                        idMapServer: this.mapComoponet.mapName,
                        name: "Tools",
                        type: "TooolsMarkers",
                        visible: true
                    });
            
                const vectorLayerSource: VectorSource = new VectorSource({
                    features: new Array()
                });
                let view = this.mapComoponet.olMap.getView();
                olLayerVector.setStyle(this.createToolStyleFuction(view).bind(this));
                olLayerVector.setSource(vectorLayerSource);

                for (let index = 0; index < response.length; index++) {
                    const tool = response[index];
                    var feature = this.mapFeaturesFactoryService.createFeature(tool);
                    feature.isTool = true;
                    vectorLayerSource.addFeature(feature);
                }
              
                this.mapComoponet.addElementLayer(olLayerVector);
            }
            console.log('Tools:' + response);
        });
    }
....
public createToolStyleFuction(view) {
        return function (feature, resolution) {
            var scaleTool = 1;
            if (view.getProjection().getCode() == "HORUS-image") {
                //si es un esquematico se adapta al tamaño de la imagen
                scaleTool = 1 / view.getResolution();
            } else {
                //en los geograficos coge la escal como un marker normal de tipo "tools"
                var zoom = 0;
                if (this.mapComoponet.getCurrentZoom()) {
                    zoom = this.mapComoponet.getCurrentZoom();
                }
                scaleTool = this.mapFeatureStylesService.getScale(this.mapComoponet.mapServerConfig.props, zoom, 'tools');
            }
            var tool = feature.get('featureInfo')
            //  var srcUrl = 'service/getToolImage/' + vm.map.mapId + '/' + tool.uid+'?lastutupdate='+tool.lastUpdate;
            var srcUrl = 'data:image/png;base64,' + tool.imgBase64;

            var newStyleIcon: Icon = new Icon({
                anchor: [0.5, 0.5],
                anchorXUnits: 'fraction',
                anchorYUnits: 'fraction',
                opacity: 1,
                points: 4,
                src: srcUrl,
                scale: scaleTool
            });
            var newStyleOl: Style = new Style({
                image: newStyleIcon,
                zIndex: 1
            });
            var styles = [];
            styles[0] = newStyleOl;
            return styles;
        };
    }
```
This hapend only when ther ar a lot of features visibles at the same time ( near to 100)
An every time the layer is move.

**Expected behavior**
Just one render for fixe like the other layers...

**Comment by jahow** [comment]
Hi,

Thanks for the report. To make it easier for people to help you and understand the issue, please provide a simple reproduction case with as few application code as possible, ideally in a code sandbox or equivalent. It is currently very hard to know where to look in the code you posted. Thanks!

**Comment by dsalasjanda** [comment]
Hi,
Sorry for, I  not used to write in this sites, and my ENglish is not good.
I write a small example in codesandbox : https://codesandbox.io/embed/angular-mjoge 
 https://mjoge.csb.app/
if the features don't star to flass, just move the map.

**Comment by jahow** [comment]
The flicker is due to the fact that you're decoding the base64 image *each time the style function is evaluated*. If you use `src: 'https://openlayers.org/en/latest/examples/data/icon.png'` when creating the icon style in line 146, the flicker will be gone.

You need to somehow cache the style objects for each feature instead of recreating them right in the style function, not only for this flicker issue but also generally for performance.

**Comment by DrChoucroute** [comment]
Hi jahow,
I'm am having a similar problem. I don't think I could use your solution though since I am recalculating styles depending on resolution. Do you know if I could still work around that problem?
The only way I could stop the flickering is to disable the update while animating.
Thanks

**Comment by jahow** [comment]
Whatever your use case, the bottom line is that you always need to cache the styles you use. Style functions should **never** create new styles on each execution. In your case, you can maybe have a cache of styles per resolution intervals and lookup the correct one based on the current resolution.

**Comment by DrChoucroute** [comment]
Ok, but wouldn't that increase considerably the loading time? 
In any case, I'll try that out. Thank you very much!

**Comment by jahow** [comment]
That should not be the case, creating and manipulating objects is an order of magnitude faster than all the other things the library has to do (rendering, decoding data etc.). Good luck!
