### ISSUE TITLE
WMS layers no longer wrap in OL6

### ISSUE THREAD

**Issue by docgregt** [openlayers/openlayers#10238]
**Describe the bug**
In OL5.x WMS single image layers would wrap. Now in OL6 they do not.

**To Reproduce**
1. Use a basemap like bing. 
2. Add a WMS layer with Tiled: False, serverType: geoserver, hdpi: false, wrapX: true
3. see image
![image](https://user-images.githubusercontent.com/43346207/67956918-7233d880-fbba-11e9-8b19-f0d4a669506a.png)

I am also using:
useGeographic();
since basemap bing is in 3857 projection. If I set view to 4326 then some wrapping occurs but then bingmaps becomes fuzzy.
Here is code for WMS layer:
 ```
       var sst = new ImageLayer({
            visible: false,
            source: new ImageWMS({
                url: geoserver + 'geoserver/metocean/wms',
                params: {
                    'LAYERS': 'metocean:sstsmooth' + wd, 'VERSION': '1.1.1', 'TRANSPARENT': 'TRUE', 'TILED': false, 'TIME': time
                },
                ratio: 1,
                serverType: 'geoserver',
                projection: 'EPSG:4326',
                hidpi: false,
                wrapX: true
            }),
            opacity: .60
        });
        useGeographic();
        var medview = new View({
            projection: 'EPSG:3857',
            center: [31, 0],
            zoom: 0
        });

        // openlayers map
        var map = new Map({
            layers: [],
            target: document.getElementById('map'),
            view: medview,
            loadTilesWhileInteracting: true,
            controls: defaultControls({
                zoom: true,
                attribution: false,
                rotate: false,
                zoomOptions: {delta: 1}
            }),
            interactions: defaults({
                altShiftDragRotate: false,
                keyboard: false,
                zoomDelta: 1
            })
        }); 
```
 

**Expected behavior**
The WMS layer wraps.

I noticed wrapX has disappeared from some documentation. Did this change? How can I make it wrap in OL6?

**Comment by ahocevar** [comment]
The `ImageWMS` source never had a `warpX` option, also not in v5.x. However, in GeoSever it is possible to request the layer for a larger extent (i.e. wrapping it on the server), which is what I'm showing here: https://codesandbox.io/s/wms-image-r3dxt.

What if you remove `projection: 'EPSG:4326',` from your WMS source configuration?

**Comment by docgregt** [comment]
If I remove the projection line then it does wrap, but it is now 1.5s slower on avg. It went from 2.5s to 4s.
I guess I can try reprojecting the source data to 3857.
The only reason I am using 3857 is because Bing maps looks fuzzy when using 4326 in OL. Is there a better approach?

**Comment by ahocevar** [comment]
If you can share your code in a codesandbox or similar, it will be easier to see if there is a better approach, or if there is a bug in the library.

**Comment by docgregt** [comment]
So if use your standard Bing Example and just change the view to:
new View({
    projection: 'EPSG:4326',
    center: [31, 0],
    zoom: 0
}
and change the height in index.html to 1000px then the Bing maps look fuzzy and not sharp. If change to:
new View({
    projection: 'EPSG:3857',
    center: [31, 0],
    zoom: 0
}
and add:
useGeographic();
Then the bing map is back to being sharp.
All the data on my Geoserver is in 4326 projection and all of our GeoJson data is as well. So that is why I was using that projection.

**Comment by ahocevar** [comment]
> All the data on my Geoserver is in 4326 projection and all of our GeoJson data is as well. So that is why I was using that projection.

That makes sense, and for that you're correctly using `useGeographic()`. But setting `'EPSG:4326'` as projection on the view will cause the Bing layer to be reprojected on the client, which makes it blurry.

**Comment by docgregt** [comment]
Ok. But now all my WMS layers slow down. I presume Geoserver is reprojecting which is slow. So is only solution to change all the data on server side?

**Comment by ahocevar** [comment]
Why not use TiledWMS?

**Comment by docgregt** [comment]
Our users do not like watching the tiles fill in so we set TILED: false on WMS query. Is there a way to have tiles fill in on like a back buffer before it gets displayed to a user? But I think it would be same speed in any case, but maybe it could be more efficient if tiles matched tiles on Geoserver.
Maybe there is some hint I am missing from your question though. I will try it out.

**Comment by docgregt** [comment]
I am closing this as the only solution is to have basemap in WGS84 which means we cant use Bingmaps.
