### ISSUE TITLE
Load Features While Interacting/Animating

### ISSUE THREAD

**Issue by mronian** [openlayers/openlayers#10241]
Is it possible to load features while interacting with the map? Currently features get loaded only after the drag is complete (onMouseUp). Also, it does not cache the features already loaded i.e. going to the same area multiple times loads the features in that area again and again.

Is there something like `loadWhileAnimating` or `loadWhileInteracting` for the Features too like  for the Map?

**Comment by ahocevar** [comment]
Sounds like you are loading your features with a bbox strategy. Switching to a tile strategy would solve the caching problem. Regarding loading, have you tried the `updateWhileAnimating` and `updateWhileInteracting` properties on the vector layer? Those won't trigger loading, but will ensure that everything that's loaded already will be displayed during animations and interactions.
