### ISSUE TITLE
fromLonLat function's conversion not accurate

### ISSUE THREAD

**Issue by elkolotfi** [openlayers/openlayers#10240]
Actually I'm not sure if this is a bug or I'm doing things the wrong way.

So here is the problem:
Let's take some address: 611 E 83rd St, NY, New York 10028, USA According to google maps, the LonLat of it is: [40.7730035,-73.9478836]

you can find the position on the map [here](https://i.stack.imgur.com/X0LFL.png)

Now I generate the map with this code:
```
const marker   = new Feature({
                         geometry: 
                             new Point(fromLonLat([-73.9478836, 40.7730035]))
                 });

this.map = new Map({
        layers: [ new Tile({ source: new OSM(), opacity: 1}) ],
        target: 'map',
        view: new View({ center: house, zoom: 17})
    });

this.map.addLayer(new VectorLayer({
      source: new VectorSource({ features: [ marker ] })
    }));

```

You can find the result [here](https://i.stack.imgur.com/Gfo0w.png)

As you can notice, the marker is not on the right spot.

Thanks for your help

**Comment by sambakk** [comment]
Can you post your code here where I can check ?

**Comment by mike-000** [comment]
Your own google maps screenshot shows it as [-73.945695, 40.773207] so why would you expect [-73.9478836, 40.7730035] to give the same result?
![image](https://user-images.githubusercontent.com/49240900/68042814-b4007400-fccb-11e9-8ca7-0fdbb08607bd.png)
