### ISSUE TITLE
ol.source.TileWMS request to server not working 

### ISSUE THREAD

**Issue by theSneeF** [openlayers/openlayers#10254]
Hi,

I have a ol map in a dojo setup, to work in episerver cms editor mode. So when an admin clicks a button a window opens and ol map i loaded in. This works fine in ol 5.3.0.

I have verified that this does not work in any of the 6.x versions. Debugging in Chrome shows me that the code runs through without any errors. But when I check network there is no call to our geoserver. Even checked in fiddler.

I have tried with some other variants from the openlayers example site. Which also doesn't work. 
https://openlayers.org/en/latest/examples/wms-custom-tilegrid-512x256.html
https://openlayers.org/en/latest/examples/wmts.html

I have attached a scaled down version of our editor script. 

Have any of you guys any suggestions what I could try? Or is this is a bug in ol 6?

[GenericMapEditor.zip](https://github.com/openlayers/openlayers/files/3807656/GenericMapEditor.zip)

**Comment by ahocevar** [comment]
Make sure your map container has a width and height.

**Comment by theSneeF** [comment]
Omg, how could I miss that. Thank you :)
