### ISSUE TITLE
PointsLayers.js in a browser without webGL

### ISSUE THREAD

**Issue by bogdanvaduva** [openlayers/openlayers#10258]
There has been added a new test for compile errors:

    if (this.getShaderCompileErrors()) {
      throw new Error(this.getShaderCompileErrors());
    }

Won't I am gone get an error if the browser doesn't support webgl? I am asking this because in the new version 6.1.1 PointsLayer.js throw an error on Firefox but not in Chrome.

**Comment by jahow** [comment]
In browsers without webgl support an error should thrown much sooner than this. This test is simply intended to prevent letting the layer render while the shaders failed to compile.

**Comment by bogdanvaduva** [comment]
I got the following error:

Error: Fragment shader compilation failed:
0:2(12): warning: extension `GL_ARB_gpu_shader5' unsupported in fragment shader
Vertex shader compilation failed:
0:2(12): warning: extension `GL_ARB_gpu_shader5' unsupported in vertex shader

**Comment by fredj** [comment]
I have the same error with the heatmap example:
https://openlayers.org/en/latest/examples/heatmap-earthquakes.html
with Firefox 70.0 (Ubuntu).

But when I reload the page the page 3-4 time the error disappear and the heatmap works as expected

**Comment by fredj** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1399501

**Comment by bogdanvaduva** [comment]
It might be the case. Thanks.

**Comment by jahow** [comment]
This is absolutely not acceptable. I've seen this warning before, it should not be preventing the render IIRC. Thanks for reporting, will try to fix this.
