### ISSUE TITLE
ImageLayer+ImageStatic does not render on Chrome/Chromium

### ISSUE THREAD

**Issue by Akuukis** [openlayers/openlayers#10252]
**Describe the bug**
Firefox displays ImageLayers ok, but Chrome/Chromium doesn't display them at all.

**To Reproduce**
1. With firefox go to http://coe-maps-dev.s3-website-eu-west-1.amazonaws.com/
2. With Chrome go to http://coe-maps-dev.s3-website-eu-west-1.amazonaws.com/
3. See png background in firefox, but all-blue background in chrome.

**Expected behavior**
ImageLayer to render in all browsers.

**Source**

Simplified excerpt from [source](https://gitlab.com/akuukis/coe-cartography-app/blob/master/src/index.ts) that still fails:
```ts
import ImageLayer from 'ol/layer/Image'
import Map from 'ol/Map'
import ImageStatic from 'ol/source/ImageStatic'
import View from 'ol/View'

const layers = [
    new ImageLayer({
        source: new ImageStatic({
            imageExtent: [-740, -1360, 860, 1640],
            url: './Selene-4.png',
        }),
    }),
]

const map = new Map({
    layers,
    target: 'map',
    view: new View({
        center: [0, 0],
        extent: [ -2880, -2880, 2880, 2880 ],
        zoom: 0,
    }),
})
```

**Comment by mike-000** [comment]
The problem seems to be related to the size of the image you are using.  If I reduce it from 6400 x 12000 to 4800 x 9000 px  it works.  There are also issues when using very large tiles (5000 x 5000) in OL6 with Chrome - about 20% of tiles fail to render but there is no error.

**Comment by Akuukis** [comment]
@mike-000 Thanks, I will think of quick workaround based on your insight.

How do we proceed to properly fix this?

**Comment by ahocevar** [comment]
These are browser limitations, so I don't think there is a good way to fix it on the library level.

**Comment by Akuukis** [comment]
@ahocevar oh, that's sad. So, let's document this behavior as expected and a recommended solution for it? I'd love to learn the best approach to solve it.

**Comment by Akoneto9** [comment]
I think so also
