### ISSUE TITLE
Rendering complex vector tiles creates many instances of Chrome Helper (Renderer)

### ISSUE THREAD

**Issue by dr-jts** [openlayers/openlayers#10253]
**Describe the bug**
A simple OL app which displays a complex vector tile layer (from an OpenMapTiles mbtile file) causes many instances of a process called "Google Chrome Helper (Renderer)".  These appear to build up over time, and stay around until Chrome is shut down.

The client application is running under Google Chrome on a Mac Air running **macOS High Sierra 10.13.6**.

**To Reproduce**
Run an application using OpenMapTiles sourced from a service based on an OMT `mbtiles` tile package, as per [this example](https://openmaptiles.org/docs/website/openlayers/).  (Note that the example uses an API key, but the actual environment in which this occurred is deployed locally, so no key is required.)

Here's the relevant code:
```javascript
const map = new ol.Map({
    target: 'map',
    overlays: [overlay],
    view: new ol.View({
      center: ol.proj.fromLonLat([-122.0283, 37.0405]),
      zoom: 16
    })
  });
const layerBase = new ol.layer.VectorTile({
    declutter: true,
    source: new ol.source.VectorTile({
        format: new ol.format.MVT(),
       url: URL.base + 'http://localhost:8081/data/v3/{z}/{x}/{y}.pbf',
        maxZoom: 14
    })
});
fetch('http://localhost:8081/styles/osm-bright/style.json').then(function(response) {
    response.json().then(function(glStyle) {
      olms.stylefunction( layerBase, glStyle,
        'openmaptiles'  // source id from style file - shows all layers
        );
    });
});
map.addLayer(layerBase);
```

To see the rendering tasks on macOS:
```
ps -ax | grep Renderer
```
which show up like this:
```
76014 ??         0:24.38 /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/77.0.3865.120/Helpers/Google Chrome Helper (Renderer).app/Contents/MacOS/Google Chrome Helper (Renderer) --type=renderer --field-trial-handle=1718379636,5928738997255947750,420293089003726739,131072 --lang=en-US --enable-auto-reload --num-raster-threads=2 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --service-request-channel-token=12876563891174922623 --renderer-client-id=1637 --no-v8-untrusted-code-mitigations --seatbelt-client=77
```

**Expected behavior**
Expectation is that rendering tasks are temporary and are removed when the page is reloaded or they are completed.

**Comment by ahocevar** [comment]
I see you are running Chrome 77, which apparently had this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=985486. It was fixed in Chrome 78.

I confirmed with Chrome 78 that when a single tab with any web page loaded, there are 3 of these tasks. When I open your example, there are still 3. When I navigate around a lot with it, there are also no additional such tasks added.

**Comment by dr-jts** [comment]
Thanks, Andreas.  I did suspect a Chrome bug, but wasn't able to find that (somewhat obscure) bug report.  I have updated and things are running better (and faster).

Keep up the great work with OpenLayers- it's a pleasure to code and use, and the vector tile capabilities are very impressive!
