### ISSUE TITLE
Pointer drag glitches when ending on an overlay element with stopEvent: true.

### ISSUE THREAD

**Issue by pbassa** [openlayers/openlayers#10268]
When one uses a Pointer interaction to handle a drag, and releases the mouse button while the pointer is over an overlay element, the interaction does not get any further event. It is not notified of the drag end, nor any other event (move, up, down, etc.)

Here is a minimal snippet showing the issue:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Drag Glitch</title>
    <link rel="stylesheet" href="ol.css">
  </head>
  <body>
    <div id="map" style="width: 100%; height: 100vh;"></div>
    <div id="overlay" style="border: solid; background: grey;">Test.</div>
    <script src="ol.js"></script>
    <script>

function CustomInteraction() {
    ol.interaction.Pointer.call(this, {
	handleDownEvent: function() {
	    console.debug("down");
	    return true;
	},
	handleUpEvent: function() {
	    console.debug("up");
	    return false;
	},
	handleMoveEvent: function() {
	    console.debug("move", event.layerX, event.layerY);
	},
	handleDragEvent: function() {
	    console.debug("drag", event.layerX, event.layerY);
	}
    });
}
CustomInteraction.prototype = Object.create(ol.interaction.Pointer.prototype);

new ol.Map({
    target: "map",
    view: new ol.View({ center: [0, 0], zoom: 3 }),
    interactions: [new CustomInteraction()],
    overlays: [new  ol.Overlay({ element: document.getElementById("overlay"),
				 position: [0, 0] })]
});

    </script>
  </body>
</html>
```

To reproduce: open this document and show the browser console.  You'll get debug messages as you hover the cursor over the map.  Then, click anywhere on the map, hold the mouse button down, and drag the cursor to the Test element; you'll get debug messages about this drag.  Then, release the mouse button; notice there are no debug messages about the button being released or anything.  If you move the mouse back over the map, no debug messages appear, thus showing that the custom Pointer interaction fails to get relevant events.

Single clicking again on the map revert to a state where the interaction works, but this is an non-intuitive glitch for users.

**Comment by arro88is** [comment]
This issue also affects default map control elements like Zoom or Scale Line. That means moving the map with holding mouse button down will cause a glitch, if the cursor is dragged over a map control element. 

The problem appears only on desktop applications, not on mobile devices.
