### ISSUE TITLE
Raster reprojection example does not work

### ISSUE THREAD

**Issue by PacoDu** [openlayers/openlayers#10267]
**Describe the bug**
Raster reprojection fails with `Uncaught TypeError: Cannot read property 'x' of null`

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/reprojection.html?q=reproject
2. set view projection to EPSG:3413
3. See error in console `Uncaught TypeError: Cannot read property 'x' of null`

**Expected behavior**
Valid example

**Comment by ahocevar** [comment]
This is caused by an issue in proj4. See proj4js/proj4js#332 for a fix.

**Comment by mike-000** [comment]
I don't think it is needed in the example if proj4 is being updated but if you are encountering reprojection errors elsewhere and cannot wait for a new release using addCoordinateTransforms to wrap error catching around the transforms is a simple workaround https://codesandbox.io/s/reprojection-m05mt

**Comment by PacoDu** [comment]
Thank you for the clean workaround ;) I will use this until proj4 is updated.
