### ISSUE TITLE
LiteralStyle API docs don't exist

### ISSUE THREAD

**Issue by megawac** [openlayers/openlayers#10260]
**Describe the bug**
The `LiteralStyle` API docs are linked to in the [`WebGLPoints` layer](https://openlayers.org/en/latest/apidoc/module-ol_layer_WebGLPoints.html) however the page errors.

**To Reproduce**

Go to 
https://openlayers.org/en/latest/apidoc/module-ol_style_LiteralStyle.html#~LiteralStyle

**Expected behavior**

Link to work

**Comment by jahow** [comment]
That's unexpected, the `WebGLPointsLayer` class does not have an `@api` tag so it should not be visible in the docs (being still experimental). Thanks for the report!

**Comment by fredj** [comment]
looks like only the `@typedef` is documented, not the class
