### ISSUE TITLE
why can't the zoom be less than 2 ,even if I set "minZoom:0" 

### ISSUE THREAD

**Issue by sinoris-dev** [openlayers/openlayers#10263]
I updated ol to 6.1.0 yesterday,it happened, but 5.3.0 worked fine
see https://openlayers.org/en/latest/examples/zoomslider.html

**Comment by jahow** [comment]
This is most likely due to this breaking change: https://github.com/openlayers/openlayers/blob/v6.0.0/changelog/v6.0.0.md#the-view-is-constrained-so-only-one-world-is-visible

**Comment by sinoris-dev** [comment]
> This is most likely due to this breaking change: https://github.com/openlayers/openlayers/blob/v6.0.0/changelog/v6.0.0.md#the-view-is-constrained-so-only-one-world-is-visible

That's true, thank you!
