### ISSUE TITLE
TileLayer is not defined

### ISSUE THREAD

**Issue by niccle27** [openlayers/openlayers#10266]
Hi, 

As i need to use php as backend, i can't use nodeJS. Therefore, i followed the counsel given here: https://github.com/openlayers/openlayers/issues/9097

Though as i specified in the title, i'm getting the following error on both firefox and chromium : 

I was trying to get the draw and modify features example : 
https://openlayers.org/en/latest/examples/draw-and-modify-features.html

I tried to minimize the html code a little, so just to show the inclusion i'm doing , 
``` html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="./v6.1.1-dist/ol.css" type="text/css">
    <title>Draw and Modify Features</title>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <h4 id="title">Draw and Modify Features</h4>
          <div id="map" class="map"></div>
          <form class="form-inline">
            <label>Geometry type &nbsp;</label>
            <select id="type">
              <option value="Point">Point</option>
              <option value="LineString">LineString</option>
              <option value="Polygon">Polygon</option>
              <option value="Circle">Circle</option>
            </select>
          </form>
        </div>
      </div>
      <script src="./v6.1.1-dist/ol.js"></script>
      <script src="draw-and-modify-features.js"></script>
  </body>
</html>
```
As specified in the linked issue, i'm using the content of the js file specified in draw and modify features example, without all the imports in draw-and-modify-features.js

I'm not very experienced in web development, can someone tell me what i'm doing wrong ?

**Comment by mike-000** [comment]
Since you are NOT importing `TileLayer` using either

`import TileLayer from 'ol/layer/Tile';`

or

`import {Tile as TileLayer} from 'ol/layer';`


instead of 

`new TileLayer({`

you must use

`new ol.layer.Tile({`

The same logic applies for any other imports in the example so your  final code will look very similar to this version 4 example https://openlayers.org/en/v4.6.5/examples/draw-and-modify-features.html

**Comment by niccle27** [comment]
Thanks a lot !

I'll try it today

**Comment by niccle27** [comment]
Indeed it is working !, 

Thanks again !
