### ISSUE TITLE
Keyboard Interactions hijack editable elements

### ISSUE THREAD

**Issue by jheijari** [openlayers/openlayers#10270]
**Describe the bug**
When user is trying to move the cursor in an input element using the arrow keys, the map pans instead.

**To Reproduce**
1. Initialize map with `keyboardEventTarget: document` and default interactions.
2. Focus to input element, type something and try to move the cursor using the arrow keys.

**Expected behavior**
The cursor moves in input field and map stays still.

I made a workaround for this by creating a custom `condition` for `KeyboardPan` and `KeyboardZoom`.

The workaround implements `targetNotEditable ` on `mapBrowserEvent.originalTarget`.
https://github.com/openlayers/openlayers/blob/master/src/ol/events/condition.js#L210

**Comment by fredj** [comment]
This issue can be reproduced with: https://codesandbox.io/s/issue-10270-iu8u6
