### ISSUE TITLE
Effectively avoid image smoothing in tile layers

### ISSUE THREAD

**Issue by forman** [openlayers/openlayers#10273]
**Is your feature request related to a problem? Please describe.**

In a project I'm using OpenLayers (btw, thanks for this great open source package!) to render satellite imagery and gridded climate datasets using tile layers. I want the imagery to be rendered without any interpolation between pixel values, so no image smoothing / blurring occurs when zooming into the map. Similar requests have been posted on OpenStack some time ago, see [here](https://stackoverflow.com/questions/35875270/turn-off-image-smoothing-in-openlayers-3) and [here](https://stackoverflow.com/questions/54083424/preventing-smoothing-of-tileimage-layer). The suggestion was altering canvas settings in a `precompose` (ol 4 and 5) or `prerender` (ol 6) event handler:

```ts
        layer.on('prerender', (event: RenderEvent) => {
            const ctx = event.context;
            ctx.imageSmoothingEnabled = false;
            const ctxAny = ctx as any;
            ctxAny.webkitImageSmoothingEnabled = false;
            ctxAny.mozImageSmoothingEnabled = false;
            ctxAny.msImageSmoothingEnabled = false;
        });
```
but that doesn't have any effect on my layers with ol 4, 5, 6.1.1. If this is still the recommended way, I'd be glad if you could share any ideas why [it does not work in my case](https://github.com/dcs4cop/xcube-viewer/blob/f94b70948baf737fd7fecd79e7c8c9c13eb57d31/src/components/ol/layer/Tile.tsx#L41)?  

**Describe the solution you'd like**

I'd like to have a tile layer options that effectively avoids image smoothing/blurring, i.e. forces nearest neighbor resampling.

I reported [something similar](https://github.com/AnalyticalGraphicsInc/cesium/issues/5846) for the Cesium project; I provided a pull request to them and [here](https://sandcastle.cesium.com/?src=Imagery%20Layers%20Texture%20Filters.html) is the result in their sandbox. Unfortunately, I currently do not have the time to do the same for OpenLayers.

**Comment by mike-000** [comment]
The prerender method does work with a simple tile layer https://codesandbox.io/s/side-by-side-w3hdq

But it doesn't work in some more complex situations such as reprojection which use an intermediate canvas https://codesandbox.io/s/side-by-side-7z7cn

In situations where the prerender method doesn't work you can override the javascript getContext prototype, but that will be applied to all canvases and cannot be used selectively https://codesandbox.io/s/side-by-side-gic2w

**Comment by forman** [comment]
Thanks @mike-000, I've overridden global getContext for time being. Hopefully I can provide a PR to OpenLayers some day for a clean, selective solution via layer (style) options.
