### ISSUE TITLE
e.dragging is updated too late when starting dragging the map

### ISSUE THREAD

**Issue by sylvainbeo** [openlayers/openlayers#10271]
In the **pointermove** callback event, we have the **e.dragging** var which is true if we are dragging the map, and false if not.

The thing is apparently that var is updated too late in the process.

Go to :  https://codepen.io/sylvainbeo/pen/Vwwdpvb
And follow the instructions in the JS code

This can be a problem, and this is a problem in my case. Because in the time the e.dragging is not updated, my code is executed, and i do a **forEachFeatureAtPixel()** which is a bit slow (i'm using vector tiles) resulting on a non fluid navigation on the map (there is an impression of the map stuck on the screen for half a second).

For infos, we have been debugging a bit OL with @elemoine, and it seems not so easy to fix (?)
I let Eric answer to give more information if he wants to.

To me, once the mouse is down, the **pointermove** event should know that we are possibily in a drag mode. And that's not the case i think. We wait until the user has really move the mouse.

Thank you.

**Comment by ahocevar** [comment]
We are using a tolerance for click events. As long as you are within that tolerance, your drag might end up being a click, so we cannot say for sure we're `e.dragging`.

You can configure your map with `moveTolerance: 0´ to get `e.dragging` set earlier, but that will make it almost impossible for the user to do a click.

**Comment by sylvainbeo** [comment]
> We are using a tolerance for click events. As long as you are within that tolerance, your drag might end up being a click, so we cannot say for sure we're `e.dragging`.

I understand.

But at least, pressing the mouse button down should set the **dragging** param to **true** after a few millisecond, don't you think so ? When you press the button for dragging, you won't release it before a certain period of time.
