### ISSUE TITLE
OL6 Vector line/poly partially drawing when left edge of map crosses dateline during pan

### ISSUE THREAD

**Issue by docgregt** [openlayers/openlayers#10289]
**Describe the bug**
We dynamically load GeoJSON lines and polygons and add them to a vector layer. We are drawing them fine even when they cross dateline. However, when panning and the left edge of the map hits the dateline then the feature partially stops drawing if it crosses the dateline.

**To Reproduce**
1. Create any geojson line with points that cross the dateline
2. add to a VectorSource
3. See error:
![image](https://user-images.githubusercontent.com/43346207/68791956-a621eb80-0607-11ea-80aa-138bbfcc60d1.png)

Pan a little left of dateline and everything draws fine:
![image](https://user-images.githubusercontent.com/43346207/68792201-1b8dbc00-0608-11ea-93aa-4ec5ed304c6e.png)

Pan one entire map to left and drawing seems to be ok:
![image](https://user-images.githubusercontent.com/43346207/68792285-4b3cc400-0608-11ea-84ff-a12aceb32a2f.png)

**Expected behavior**
Expect the feature to be drawn.
![image](https://user-images.githubusercontent.com/43346207/68792030-ce114f00-0607-11ea-813a-d428fe616e9c.png)

Or provide workaround. I did not see any way VectorTiles could be used in our use case.

**Comment by mike-000** [comment]
If wrapX is true on the vector source features will only be displayed if the part of with coordinates in the normal world extent is in the viewport.  If you draw a feature across the dateline one end will have coordinates outside that extent.  A workaround is to split the linestring into a MultiLineString containing only normal world coordinates   https://codesandbox.io/s/draw-features-njmp8  Polygons should similarly be split into a MultiPolygon.

**Comment by docgregt** [comment]
@mike-000 , Thank you for the info. For me wrapX made no difference and worked same way whether it was true or false.
In your sample code the multlinestring seemed to work but the multipolygon did not:
![image](https://user-images.githubusercontent.com/43346207/68887477-4cd4bd80-06d6-11ea-85e2-28b5c94e0ef1.png)

**Comment by mike-000** [comment]
I didn't include any code to split polygons, that would be more complex than a linestring and might need a third party utility such as turf..

**Comment by docgregt** [comment]
@mike-000 , Thank you for the line algorithm. I got it working on our system and it works great!
I do not understand why this could not be implemented in Openlayers behind the scenes.

I do not see how a polygon could be split into a multipolygon. For example a hurricane cone needs to be a polygon. Maybe a linestring and multipolygon together?

**Comment by mike-000** [comment]
Here is an implementation using turf.js which works for both linestrings and polygons https://codesandbox.io/s/draw-features-k3i5q
