### ISSUE TITLE
map export using html-to-image library doesn't work when using a vector layer

### ISSUE THREAD

**Issue by cyrilpreiss** [openlayers/openlayers#10287]
Now that there isn't any event.context.canvas available we have to use html-to-image library as shown in export to pdf example.

But the dom-to-image library is not working when the map includes a vector layer, any idea how to get a map screenshot when using a vector layer ?

**Comment by mike-000** [comment]
Can you give more details of what is not working.  The example https://openlayers.org/en/latest/examples/export-pdf.html does include a vector layer and works as long as html-to-image supports the browser (Internet Explorer and Safari are not supported, with or without vector layers).

**Comment by cyrilpreiss** [comment]
Hi,

here is may map:

`let mapa = new OlMap({
             renderer: 'canvas',
          layers: [
               new OlLayerTile({
                   source: new Zoomify({
                       url: this.zoomifyUrl,
                       size: [this.imgWidth, this.imgHeight],
                       crossOrigin: 'anonymous',
                       tileSize: 256
                     })
				 }),
				 new VectorLayer({
					source: this.vectorsource
				})
				 
               
             ],
             target: this.panoname+i,
             view: this.theview,
             logo: window.logoElement,
             controls: []
         });
`
if i leave this VectorLayer, toJpeg(map.getViewport()...) is giving me an "uncaught error (in promise"
if i remove it it's working as expected.

**Comment by mike-000** [comment]
It looks like mixed content (http images in an https application) is tainting the canvas and causing an html-to-image error.

**Comment by ZakarFin** [comment]
Not sure if relevant to this but we discovered that having _empty_ vectorlayers on the map causes canvases with 0 width to be on the DOM that seems to break html-to-image. We fixed this by filtering empty canvases out: https://github.com/oskariorg/oskari-frontend/pull/1040

**Comment by mike-000** [comment]
Thanks @ZakarFin It may not be the only problem in this case but that is reproducible in the Export PDF example.  If you zoom in to somewhere where the vector feature cannot be seen and then rotate the view the export fails.  Inserting your additional filter fixes it.  Although I could not reproduce the issue in the PNG export example, the filtering in both examples should be updated.

**Comment by ahocevar** [comment]
I think it might be easier to go back to the export method we had in version 5, and use the css transforms of the layer divs to compose them to an output canvas. Without going through svg
