### ISSUE TITLE
Incomplete reprojection when wrapX=false  

### ISSUE THREAD

**Issue by PacoDu** [openlayers/openlayers#10284]
**Describe the bug**
When a layer source is defined with `wrapX: false` the reprojection is incomplete.

**To Reproduce**
1. Go to https://codesandbox.io/s/reprojection-zb61q
2. Click on 'View projection => EPSG3413'
3. See incomplete reprojection
![image](https://user-images.githubusercontent.com/1575833/68681746-3ad30d80-0564-11ea-96ec-12e40ddf9e34.png)
If you remove `wrapX: false` for OSM source at line 105 the reprojection artifact disappears 

**Expected behavior**
wrapX shouldn't interfere with raster reprojection

**Comment by PacoDu** [comment]
I wasn't able to reproduce this issue with an other projection (only EPSG3413)

**Comment by mike-000** [comment]
At least wrapX is having effect (even if the wrong one).  There are projections where `wrapX: false` would be useful but it seems to have no effect.  With a Lambert Conic projection it should look like this

 ![image](https://user-images.githubusercontent.com/49240900/68766877-9a3e2580-0617-11ea-8ca3-22abee137fbe.png) 

but even with `wrapX false` I get this 

![image](https://user-images.githubusercontent.com/49240900/68768443-69abbb00-061a-11ea-998a-bd9ee51fb235.png)
