### ISSUE TITLE
Accessible maps with tabindex attribute not possible to pan and zoom using gestures on mobile

### ISSUE THREAD

**Issue by esseb** [openlayers/openlayers#10288]
**Describe the bug**
When using `tabindex` on a map to make it keyboard accessible the map becomes impossible to pan and zoom using gestures on mobile devices.

**To Reproduce**
1. Open https://openlayers.org/en/latest/examples/accessible.html in Chrome on Android or Safari on iPhone
2. Try to pan around the map by touching and dragging the map
3. Try to zoom the map using pinch zoom

**Expected behavior**
The map should be possible to pan using touch drag and should be possible to zoom using pinch zoom.

**Actual behavior**
Panning the map using touch drag stops after only a few pixels. Pinch zoom zooms the entire page instead of the map.

**Further information**
The `ol-viewport` element should have the style `touch-action: none`, but if the map container has a `tabindex` attribute the `ol-viewport` element gets the style `touch-action: auto` instead.

This was implemented in https://github.com/openlayers/openlayers/pull/10187 with this comment:
> So we need to put some effort into not setting that when the user might want page scrolling (which we expect to be the case when a tabindex attribute is set on the map target element).

I don't think it's correct to infer that the presence of `tabindex` means the user might want page scrolling. At least in my case, and in the accessible map example I linked to, I use `tabindex="0"` to make it possible to tab to the map and interact with it using the keyboard but I still want the map to be possible to interact with using gestures on mobile.

**Comment by ahocevar** [comment]
Good call, thanks for reporting this. I think #10291 is a nice solution to this problem.
