### ISSUE TITLE
OL 6.x incompatible with IE and Android KitKat (Math.sign)

### ISSUE THREAD

**Issue by murimere** [openlayers/openlayers#10296]
Issues old title: Icon/Cluster/Vector position is moving by map move
Issues new title: OL 6.x incompatible with IE and Android KitKat (Math.sign)

OL v6.1.0
Android 4.4.2 (KitKat)         
- cyanogenmod 11 (year ~2013-2014)        
- default browser, com.android.browser 4.4.2

Icons and Clusters (Vectors) are moving when the map is moved. The positon is everytime false, except the Icon/Cluster/Vector position is exactly at the middle of the map. One solution is the `anchor:` by Icons, but no by Clusters (Vectors). But also that not work in the Android browser. The problem is not in latest Firefox and Chrome on desktop. I have it in an older Android "com.android.browser" (4.4.2). The Android 4.4.x (KitKat) is in year 2019 worldwide in use with 7 %. Oreo 28 % (Android 8.x). Pie 10 % (Android 9.x).

I had a similar problem some time ago. The Android browser could not use a Javascript function. The hard part is finding out which function that is. After that you can possibly exchange them.

**Comment by murimere** [comment]
I have detect the JavaScript functions. This are the same that don't work in Internet Explorer.
- Math.cosh (OL 5.3.x, OL 6.x)
- Math.sign (OL 6.x)
- Math.trunc (not used in OL)

Please mark your OL as: Not fully compatible with Internet Explorer and Android KitKat default browser.

By `Math.cosh` you have a check with fallback. By `Math.sign` not.
Math.cosh: `var jt="cosh"in Math?Math.cosh:function(t)`
Math.sign: `this.getMap().getView().endInteraction(void 0,Math.sign(this.lastDelta_)`

But I have not tested if it works with a fix that works with the cluster.

**Comment by murimere** [comment]
`Math.sign` Polyfill: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign

**Comment by ahocevar** [comment]
You could simply load such a polyfill before loading OpenLayers. Does that work? Then we can document it.

**Comment by murimere** [comment]
i have no time and no know to test this. i have tested the other, is enought time to lost.

**Comment by ahocevar** [comment]
@murimere Not that I like your attitude towards an open source project that others pay for and you benefit from, but it took me 2 minutes to create #10302 and 5 minutes to write this comment and shake off the annoyance you caused me.

**Comment by murimere** [comment]
Thanks! I have no experience of Github with something like that. 2 minutes? It would take me several hours to figure out how to do that. It took me several hours to focus on Math.sign(). Several hours, for Openlayers, to make OL better! Thats my "five cents". Teamwork!

Is there yet fixed for the next version?

**Comment by ahocevar** [comment]
@murimere Yes, you can `npm install ol@dev` to get the fix.

**Comment by murimere** [comment]
I don't use npm. I'm a oldschool OL user, with implement the .css and .js im my websites directly via `<link href` and `<script src`.

I have spend more time in this problem yet. I have checked how can i use a polyfill. I have put the polyfill in a clone of my new created and yet finished website in the `<head>` before the ol.js. I have tested several versions with Android KitKat. Below the test and there result as comment after `return`.
```
if (!Math.sign) {
  Math.sign = function(x) {
//  return ((x > 0) - (x < 0)) || +x; // 0, 0, 1, -1
// return ( (x > 0) ? 1 : 0 ) || +x; // 0, 0, 1, -2
// return ( (x > 0) ? 1 : 0 ); // 0, 0, 1, 0
// return ( (x < 0) ? -1 : 0 ) || +x; // 0, 0, 2, -1
// return ( (x < 0) ? -1 : 0 ); // 0, 0, 0, -1
  };
	alert("Math.sign is not");
}
```
```
	alert(Math.sign(0));
	alert(Math.sign(-0));
	alert(Math.sign(2));
	alert(Math.sign(-2));
```
With all Ol cluster are not working in Android KitKat 4.4.2 cyanogenmod default browser.

Thats not the right way! I do not know why this function is needed in OL, or in which context it is. What should be achieved with this function? ... The right way:

Please give me a list of all used JavaScript functions in OL last version. Than i can make a test like `if (!func)` in Android KitKat.

**Comment by murimere** [comment]
This polyfill for IE 9 also do not work in KitKat: https://gist.github.com/edoardocavazza/47246856759f2273e48b

**Comment by murimere** [comment]
... that's not my area ... Also, the polyfill from mozilla works in KitKat, but with this the OL cluster still do not work.
