### ISSUE TITLE
Bing based examples fail to show map

### ISSUE THREAD

**Issue by emcastro** [openlayers/openlayers#10294]
**Describe the bug**
Bing based example on OpenLayers website show gray map zone with nothing inside.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/index.html?q=bing
2. Open any of the filtered examples
3. Map zone only show + and – zoom buttons

**Expected behavior**
Map with Bing map background?

**Comment by emcastro** [comment]
I noted that the HTTP request to 
https://dev.virtualearth.net/REST/v1/Imagery/Metadata/Aerial?uriScheme=https&include=ImageryProviders&key=As1HiMj1PvLPlqc_gtM7AqZfBL8ZL3VrjaS3zIb22Uvb9WKhuJObROC-qUpa81U5&c=en-us&jsonp=olc_18
returns `olc_18({"authenticationResultCode":"DeniedCredentials",`...

I guess the Bing Maps key is expired. Solution 1:
* get a renewed key for the web-site,
* change the type of map of these examples so that the demo works (except for Bing map centric ones)

**Comment by mike-000** [comment]
It happens most days.  The API key has probably reached its daily limit.  Using an alternative service such as ArcGIS for aerial imagery would reduce usage (and also allow some of the examples to work immediately in codesandbox without having to obtain an API key)

**Comment by ahocevar** [comment]
Glad to accept pull requests.
