### ISSUE TITLE
Example Box Selection ERROR

### ISSUE THREAD

**Issue by fabiorsodre** [openlayers/openlayers#10298]
**Describe the bug**
When applying the "Box Selection" example to my computer, I get the syntax error. I have not modified the files, they are exactly the same as the ones I downloaded.

**To Reproduce :**
1 - Link example: https://openlayers.org/en/latest/examples/box-selection.html
2 - Erro:
Uncaught SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse ()
at getObject (View.js:1707)
at GeoJSON.JSONFeature.readFeatures (View.js:1707)
at VectorSource. (View.js:1707)

**Expected behavior**
I hope to click on some region of the map and display a marking of the selected area.

**Comment by mike-000** [comment]
Can you open the data directly from your browser, for example http://localhost/yourpath/data/geojson/countries.geojson ?

You may need to configure `.geojson` in the MIME types (especially if you are using IIS).
