### ISSUE TITLE
Support touch events for DragBox interaction

### ISSUE THREAD

**Issue by mitllgreg** [openlayers/openlayers#10290]
**Is your feature request related to a problem? Please describe.**
It would be beneficial for the DragBox interaction to support touch events. I use the DragBox interaction for numerous other map interactions and it would be nice to easily support these on mobile.

**Describe the solution you'd like**
The DragBox currently supports a condition filter that defaults to always. In addition to applying that condition, it also artificially limits the events it handles to mouseOnly and mouseActionButton.
https://github.com/openlayers/openlayers/blob/8b036ba96cb3d113c7115fd24884af55ec874af4/src/ol/interaction/DragBox.js#L220-L226

I think it would be preferable for DragBox to not limit to mouseOnly and mouseActionButton conditions and only use the conditions filter. I believe the conditions filter could default to mouseActionButton to keep current compatibility and others like myself could override this default to support DragBox functionality on touch events. 

If there is agreement on this change/improvement, I would be happy to submit a PR with the described changes.

**Comment by fredj** [comment]
Hi @mitllgreg, feel free to open a pull request, thanks
