### ISSUE TITLE
Animate stops if map.updateSize() is executed while animation is running

### ISSUE THREAD

**Issue by petrovichm** [openlayers/openlayers#10313]
I am working on an app in Angular 8 for a year and i didn't have a problem with this. I guess that it has to do with some major changes in Openlayers v6.

**Describe the bug**
After upgrading to v6.1.1 from 5.3.3, i had a problem with animation process.
When i initiate `view.animate(...)` and use all parameters well, i see part of the navigation and zoomin animation, but it stops after certain time (300ms) in my case. 

**To Reproduce**
Apart from this animate code i have part of my code that executes `map.updateSize()` method and it is executed after 300ms time out because of new elements that change viewport size (300ms is just an arbitrary value).
When i found that this is causing the animation stop, i bound map size update to some click event and it stops the animation the same.

**Expected behavior**
In the previous version (5.3.3) i had this size updating and it didn't stop the animation.
Not sure if this is a bug or expected changed behavior but it could break some more projects that rely on updating size after some viewport size changes.

Since this `updateSize()` is an important method in your API, i propose that you maybe add this to your [API documentation for animation](https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#animate) along side those other methods that cancel animation that you mentioned.

Either way, i fixed it by adding map size update method as callback to `animate` sequence. But this is only because for my case, animation happens after viewport changing elements are already shown.

Thanks.

**Comment by petrovichm** [comment]
I dont want to be inpatient, but this issue is 15 day sold now.
Since i provided a problem and how to resolve it and fix it, can anyone from the dev team see if this is a bug or intended behavior? Thanks.

**Comment by ahocevar** [comment]
@jahow, can you take a look at this please?

**Comment by jahow** [comment]
Hi,

Would you be able to provide a simple reproduction case in codepen or similar? Your description is a good start but actually investigating this issue will require to reproduce it one way or another. Thanks!

**Comment by petrovichm** [comment]
@jahow thanks for getting back to me. There is an example where left side map is moving normally without updateSize(), and right one having updateSize() executed after some timeout.

**Comment by petrovichm** [comment]
I forgot to attach live example: https://codepen.io/maximilijan/pen/KKwqwxa

**Comment by romainfd** [comment]
Hello,
First, thanks for all the good work put in Open Layers!
I was wondering if there were any plan to fix this?

**Comment by jahow** [comment]
Hi, I was planning on looking into it but did not have the chance to do so yet.

**Comment by romainfd** [comment]
Hi, 
Thank you for the answer. Do you have any timeline?

**Comment by jahow** [comment]
There is no funding for this that I know of, so the answer is no.
