### ISSUE TITLE
Rendering problem when zooming (6.1.1)

### ISSUE THREAD

**Issue by samucwb** [openlayers/openlayers#10314]
Void areas show up when zoom in and out.
![bug-openlayers-6 1 1](https://user-images.githubusercontent.com/17529202/69073644-8aa25080-0a0c-11ea-9bf0-60ec444dc8f9.png)

**Comment by ahocevar** [comment]
What is your layer source? Do overview map and main map use the same source? Please share your code on https://codesandbox.io/ or similar.

**Comment by samucwb** [comment]
No. They are different. 

To reproduce the error you must zoom in , and when the blank screen shows up, you do zoom out and you'll see that the blank screen remains on the screen.  The problem occurs randomly. 

[https://codesandbox.io/embed/busy-brook-tjr3f?fontsize=14&hidenavigation=1&theme=dark](url)




![openlayes-error](https://user-images.githubusercontent.com/17529202/69146144-f7b9f280-0aad-11ea-973a-8c795b389cf0.PNG)


I get the maps from:

https://leaflet-extras.github.io/leaflet-providers/preview/



overViewControl:

` https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}`

Main Map:

`https://{a-c}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png`

**Comment by ahocevar** [comment]
This appears to be a problem with raster reprojection. When you remove the projection related settings from the view, the problem does not occur.

I think I have seen this kind of behavior before. Maybe @petrsloup can take a look at this. The problem also occurs with OpenLayers v5.x.

**Comment by ahocevar** [comment]
It appears to be related to a saturated tile cache. In older versions the problem can only be reproduced when a small `cacheSize` is set, e.g. `50`.

**Comment by ahocevar** [comment]
To see the issue in an official example, go to https://openlayers.org/en/latest/examples/scaleline-indiana-east.html

**Comment by samucwb** [comment]
Thanks. I think that we are in the right path.  Appears that when we adjusting  the cacheSize to some value like 100, e.g, the problem occur less, and when this happen the openlayers fixes the blank area when zoom in and out again. Without setting the cacheSize the OpenLayers wasn't correcting the problem.  But when I was using openlayers 5.3.3 this problem never occured.

**Comment by ahocevar** [comment]
@samucwb OpenLayers 5.x had a default cache size of 2048.
