### ISSUE TITLE
modify interaction can not be used for 'Circle'

### ISSUE THREAD

**Issue by DZG-MELODY** [openlayers/openlayers#10316]
**Describe the bug**
see https://openlayers.org/en/latest/examples/draw-and-modify-features.html

**To Reproduce**
1. Draw a circle feature
2. Modify the feature's radius
3. The feature has no change, but the center can be changed

**Comment by DZG-MELODY** [comment]
I try some cases local, I find that: using modify interaction with the snap interaction together will lead to this bug.

**Comment by mike-000** [comment]
It seems to be a regression as it works in version 5 https://openlayers.org/en/v5.3.0/examples/draw-and-modify-features.html

**Comment by mike-000** [comment]
It is still possible to modify a radius, but seemingly only at one point on the circumference (which changes at each modification).  I'm not sure what determines that point.

It appears to have last worked correctly with 6.0.0-dev.1569520841098 https://codesandbox.io/s/draw-and-modify-features-w7h3y and had problems with 6.0.0-dev.1569520952344 https://codesandbox.io/s/draw-and-modify-features-6x5ow and those timestamps would correspond to the merging of #10009

**Comment by greggian** [comment]
It looks like it may be related to the snap interaction. On master, If I disable the snap interaction I am able to modify a circle geometry.
