### ISSUE TITLE
OL 6.x need a polyfill for IE and Android

### ISSUE THREAD

**Issue by murimere** [openlayers/openlayers#10311]
Ol 6.x don't work in Android KitKat 4.4.2 cyanogenmod default browser. This browser JS is similar to IE9.
More details see here: https://github.com/openlayers/openlayers/issues/10296#issuecomment-554956453

**Comment by jahow** [comment]
Why are we trying to support a 6-years-old OS native browser again?

**Comment by murimere** [comment]
@jahow, Look at the statistics on how many people are still using them.

**Comment by gberaudo** [comment]
I guess supporting very old or exotic browsers can be achieved with a custom-built polyfill: https://github.com/zloirock/core-js/tree/master/packages/core-js-builder.
