### ISSUE TITLE
Attribution for TileLayer 

### ISSUE THREAD

**Issue by Bear4** [openlayers/openlayers#10324]
The attribution for TileLayer(source: XYZ) doesn't display at Map.
Attribution seems to not forwarded from Layer to Map.

ol v. 6.1.1 building via webpack.

**To Reproduce**
Add TileLayer source: XYZ to map.

```
let osm = new TileLayer({
  title: 'OSM',
  source: new XYZ({
    url: 'http://local_server/mapy/tiles//{z}/{x}/{y}.png'
  }),
  description: 'OpenStreetMap',
  baseLayer: true,
  visible: true,
  attributions: ['<b>&copy; autors - <a href ="http://www.openstreetmap.org/copyright">OpenStreetMap</a></b>']
});

let watercolor= new TileLayer({
    title: 'Watercolor',
    source: new Stamen({
      layer: 'watercolor',
      displayInLayerSwitcher: true
    }),
    description: 'Mapa renderowana jako akwarela',
    baseLayer: true,
    visible: false
});

let map = new Map({
  target: 'map',
  layers: [osm, watercolor],
  view: new View({
    center: [2577400.0, 7006750.0],
    zoom: 14
  }),
  controls: defaultControls().extend([scaleline, attribution])
});
```
But Tilelayer as Stamen is proper display with default attributions.
![stamen](https://user-images.githubusercontent.com/8928341/69331822-b06e6600-0c55-11ea-9640-11b071b44258.jpg)

Problem is with handed set XYZ source, I think.
![xyz](https://user-images.githubusercontent.com/8928341/69331829-b5cbb080-0c55-11ea-98c8-19e89f744cd3.jpg)

**Expected behavior**
Fix display atribution from TileLayer(source: XYZ).

**Comment by fredj** [comment]
Hi @Bear4, you need to set the attributions to the source instead of the layer

**Comment by Bear4** [comment]
Thanks!
