### ISSUE TITLE
Cannot trigger prerender and postrender of layer object

### ISSUE THREAD

**Issue by ZihengSun** [openlayers/openlayers#10323]
**Describe the bug**
I am developing a layer swipe function. It failed to trigger the "prerender" and "postrender" events on all the layers. It works standalone, but after I composed OpenLayers into big react project. It doesn't work. I tried every possible solution but no luck. Please help. My current understanding is that in some situation OpenLayers automatically render all the layers in one Canvas, rather than rendering each layer on a new canvas. 

**To Reproduce**
Go to http://cloud.csiss.gmu.edu/smap/
Click Compare bar, and choose two layers. 
Slide the bar and it doesn't work. 
However, the exact code works standalone here: https://codesandbox.io/s/layer-swipe-j4xd9

**Expected behavior**
What is the reason why it doesn't work and how to fix it?

Thank you!

**Comment by mike-000** [comment]
Your link is using OpenLayers 5 which uses precompose and postcompose events.  You could simply replace render with compose, but it is also possible to specify both event types to make your code compatible with both OpenLayers 5 and 6 https://codesandbox.io/s/layer-swipe-k5gkz

**Comment by ZihengSun** [comment]
> Your link is using OpenLayers 5 which uses precompose and postcompose events. You could simply replace render with compose, but it is also possible to specify both event types to make your code compatible with both OpenLayers 5 and 6 https://codesandbox.io/s/layer-swipe-k5gkz

This is amazing. It solves the problem! Thanks so much!

It seems v5.3.3 uses precompose, v6.4.1 uses prerender. I am referencing to the wrong API. Sorry for that.
