### ISSUE TITLE
Modify interaction with useGeographic does not interact at drawn circle circumference

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10328]
**Describe the bug**
Additionally (as observed while investigating #10316) the modify interaction does not act on the circle center as it should.

**To Reproduce**
Draw a circle in this example https://codesandbox.io/s/draw-and-modify-features-voi73  (which will be yellow and circular in the view) and the code will add a red circular polygon based on geographical coordinates which is oval in the view.  Hover over both circles and see that the modify interaction is activated only over the red oval, but modifies the radius of the yellow circle.  Also it does not activate over the circle center.

However, I cannot see any obvious link between this problem and problems using modify in conjunction with snap in view coordinates in #10316 as there is no problem with using only modify as above in view coordinates.

**Comment by mike-000** [comment]
A related issue with the draw interaction can also be seen in the example.  If a circle is drawn by moving the pointer above or below the starting point (circle center) the circle does not extend to the pointer position as it does in non-geographic mode.

**Comment by tschaub** [comment]
Thanks for the report and for the super-helpful example, @mike-000.
