### ISSUE TITLE
ol.layer.Graticule events don't fire (rendercomplete and postcompose)

### ISSUE THREAD

**Issue by ldv-dev** [openlayers/openlayers#10329]
**Describe the bug**
The events (rendercomplete and postcompose) on ol.layer.Graticule don't fire.

**To Reproduce**
I have have a map with  a few layers and a ol.layer.graticule, the graticule shows up fine, but if i move, zoom the map with a ol.map.once('rendercomplete') function waiting for the map to rendercomplete, it will never fires, it only happens if the graticule is present.

The same happens with the graticule it self.

**Expected behavior**
ol.map.once('rendercomplete') firering with a graticule in it.

Thanks

**Comment by mike-000** [comment]
Could you provide an example.  When I add listeners to the example they seem to be firing correctly https://codesandbox.io/s/graticule-d7uif

**Comment by ldv-dev** [comment]
@mike-000 

in the given example, the graticule.on("postrender" and map.on("postcompose" are firing, but, the map.on("rendercomplete" is not firing, if you comment the graticule from layers array on the map. the "rendercomplete" starts to show again.

So the graticule layers is somehow preventing the rendercomplete.

One more thing, if i make a zoom in or zoom out how many rendercomplete trigers should i have?
1 or more?

Thanks

**Comment by mike-000** [comment]
I get rendercomplete with the graticule at the end of some sequences as expected, but it is not firing reliably
![image](https://user-images.githubusercontent.com/49240900/69532123-123c1200-0f6d-11ea-9319-1fd9785290fc.png)

**Comment by ldv-dev** [comment]
i never have the rendercomplete if a graticule is on the map.

In the example above, i removed the graticule, and zooming once or moving the map without releasing it, triggers multiple rendercompletes.

**Comment by ldv-dev** [comment]
it seems every time i interact with the map, drag, double click to zoom, wheel zoom, it fires a few rendercompletes immediately and when it really finishes the full render of the map one last and true rendercomplete.

**Comment by mike-000** [comment]
The rendercomplete  not firing reliably prevents printing a map with a graticule so we should try to fix this.

**Comment by ahocevar** [comment]
@mike-000 If you're able to provide a fix, we'd appreciate a pull request.
