### ISSUE TITLE
Render HTML tags - ol/style/Text

### ISSUE THREAD

**Issue by seven4pl** [openlayers/openlayers#10331]
Currently, html tags are not rendered correctly, for example: 

![image](https://user-images.githubusercontent.com/38049952/69493909-4fdd6400-0eb5-11ea-9e70-f93d2d4f2ecb.png)

At this moment I can't create something like that:
![image](https://user-images.githubusercontent.com/38049952/69493930-9468ff80-0eb5-11ea-8f69-5e11da28a1ee.png)

**Comment by ahocevar** [comment]
One way to render HTML is to use `ol/style/Icon` instead of `ol/style/Text` and provide a data uri with an svg that contains the formatted Text to render.
