### ISSUE TITLE
can not identify line ring because calling getLinearRings() returns new instances of line ring

### ISSUE THREAD

**Issue by amenifus** [openlayers/openlayers#10341]
**Describe the bug**
I have a need to map/identify linear rings of a geometry but I could not find a way to identify them because calling `getLinearRings `return new instances of geometry's linear rings and these rings have new `ol_uid `and none of the custom properties that I have set before.

**To Reproduce**
```
var geometry = ...; // who has ol_uid 111
var linearRing = geometry .getLinearRing();
console.log(linearRing .ol_uid); // lets say this prints 99
linearRing .customProperty = 'custom_identifier';
linearRing .set('customProperty2',  'custom_identifier2');
```

**Expected behavior**
At some point I need to map/identify the linear ring I have used above but...
```
var geometry = ...; // // who has ol_uid 111
var linearRing = geometry .getLinearRing();
console.log(linearRing .ol_uid); // this does not print 99 as expected but rather some incremented value
console.log(linearRing .customProperty); // this prints undefined
console.log(linearRing .get('customProperty2); // this prints undefined
```

**Comment by mike-000** [comment]
The same applies to getPoints() for MultiPoint, getLineStrings() for MultiLineString and getPolygons() for MultiPolygon.  The parent geometries are not a collection of Points, LineStrings, Polygons or LinearRings, they are defined by a coordinate array from which those components can also be created.

**Comment by ahocevar** [comment]
@amenifus Can you elaborate a bit on your use case? What is your workflow with these rings, and where/why do you need to keep track of them?

**Comment by amenifus** [comment]
Database gives me a polygon with 3 holes in it as 4 separate geometries. Each geometry comes with additional properties: **geometry_id**, a flag wether a geometry is a hole or an outher ring and others. From that I can easily construct a single polygon and draw on the map.

This polygon might be updated: it's outer ring vertices changed removed, same for the holes.

Problem is that when I want to save this geometry it has to be sent to the database in same format: as 4 different geometries with their additional properties so that geometries and their metadata could be updated accordingly. But since there are no such objects as linear rings stored in geometry and `getLinearRings` creates new linear ring objects each time I have no identifying information to know which **geometry_id** and metadata needs to be assigned to which linear ring (when converted to geometry).

**Comment by ahocevar** [comment]
Ok, here is what you could do: create separate geometries for each of your rings. In the style function of the layer (which determines rendering), create a custom geometry that assembles the ring into your desired geometry, and set that as `geometry` property of the style. When using things like the Modify interaction, you render to a separate layer, which renders the separate geometries.

**Comment by amenifus** [comment]
If I understand correctly, then

this suggestion

> create separate geometries for each of your rings. In the style function of the layer (which determines rendering), create a custom geometry that assembles the ring into your desired geometry, and set that as geometry property of the style. 

is about making all the geometries look as one geometry. That's fine, newer thought about this way (I mean to do joining in the style) of making a single geometry from multiple geometries.


and this suggestion

> When using things like the Modify interaction, you render to a separate layer, which renders the separate geometries.

is about creating/enabling a new vector layer who would be aware about all the geometries (outer ring and those linear rings/holes expressed as geometries). That way I would not lose metadata of original geometries and would be able to modify them.
However I need all the geometries (the outer ring and those of inner holes) to look and behave like one: I mean when one geometry, let's say an inner hole, is selected for modification then all geometries of the same geometry group need to have their style changed or when one hole is dragged the whole geometry group needs to be dragged with it. I am actually working on this kind of solution but it is cumbersome thing to do and it would be easier if linear rings would exist as objects inside geometry object
