### ISSUE TITLE
UTFGrid issue with preemptive false and tileJSON

### ISSUE THREAD

**Issue by adube** [openlayers/openlayers#10342]
**Describe the bug**

I try to use an UTFGrid source with the `preemptive` option set to `false` and a `tileJSON` configuration, which requires the use of `{x}+{y}+{z}` in the url.  These get automatically replaced by the tile url and mouseoverring the layer works properly.

Something else seems to break: the tile queue.  There are tiles from UTFGrid that have keys that never leave the queue and prevents the whole map from loading tiles.

In other words, in a map where you have 2 layers, one OSM and an UTFGrid configured like mentioned above, then trying to zoom in result in the OSM tiles to not load properly.

If I try to remove the `{x}+{y}+{z}` values from the tileJSON url, then it works.  So, it seems to be an issue related with the keys... but I haven't found out the cause yet.

**To Reproduce**
1. Clone this branch: https://github.com/adube/ol3/tree/utfgrid-issue-preemptive-false, (or apply this patch: https://github.com/adube/ol3/commit/201d6d52e3eeaf1c1e3b9d18d9d9769c6cdd7f2b)
2. run the example locally (npm run serve-examples, then visit the example "utfgrid.html")
3. zoom in a couple times
4. you'll see that the tiles from OSM stop from working --> I think the queue is full, i.e. not emptied properly

**Expected behavior**
The queue should be emptied properly, and OSM tiles properly loaded.

**Comment by adube** [comment]
Does anyone have any hint about how to fix this issue?  Thanks.

**Comment by ahocevar** [comment]
This is a bug. See #10344 for a potential fix.

**Comment by adube** [comment]
Thanks Andreas.  I'll test this right away!
