### ISSUE TITLE
ol 5 ol.interaction.Draw geometryFunction auto delete last point after finish draw polygon

### ISSUE THREAD

**Issue by QianWu184** [openlayers/openlayers#10353]
I add geometryfunction to draw polygons. When finished, it does not contain dbclick points. When I do not use geometryfunction, I can draw normally

Here is my key code：
```
new ol.interaction.Draw({
    source: source,
    type: "Polygon",
     geometryFunction(coords, geom) {
       if (!geom) {
          geom = new ol.geom.Polygon(coords);
         }
       geom.setCoordinates(coords);
       return geom;
        }
});
```

Thank you very much for helping me

**Comment by mike-000** [comment]
For a Polygon you must add the first coordinate to close the ring in the geometry - see the source code https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/Draw.js#L324

**Comment by QianWu184** [comment]
> For a Polygon you must add the first coordinate to close the ring in the geometry - see the source code https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/Draw.js#L324

Yes i saw it, thank you for your help
