### ISSUE TITLE
Poor performance/lagginess when drawing a line with 2 strokes, 1 of which is dashed

### ISSUE THREAD

**Issue by wflemingnz** [openlayers/openlayers#10350]
**Describe the bug**

I previously experienced poor performance when drawing dashed lines, as commented in #10139.
@ahocevar advised to use a VectorImage layer instead of a Vector layer.

This made a significant improvement on immediate responsiveness, but there are still occasions when lagginess occurs.

**To Reproduce**

1. Go to https://codesandbox.io/s/github/wflemingnz/ol-image-vector-layer-performance
2. Zoom in rapidly and continuously using the mouse wheel, ensuring that any one line stays in the view
3. Eventuallly re-rendering of the line becomes slower. This is apparent by the delay between the scaled up pixelised line image appearing and the resized line image (see image at bottom)
4. During the delay, the map is unresponsive ie: can't pan or zoom further
5. Seemingly from this point on, the map is less responsive, ie: zoom out 1 or 2 levels then back in again

Note:
1. If the centre stroke is changed to non-dashed(use doubleLineStyleNoDashes), the symptoms above do not occur
2. If a single dashed stroke is used(singleLineStyleDashed), the symptoms above do not occur
3. Therefore in this case, it is a result of using 2 strokes, with one of them being dashed which exhibits the problem

**Expected behavior**

For lines with 2 strokes, 1 of which is dashed:
1. No lagginess when zooming/zoomed in
2. Comparable performance to lines with 2 strokes, none of which is dashed

**Appendix**
In reference to Repro step 3, here is an example point at which the map is unresponsive:
![ScreenHunter 1254](https://user-images.githubusercontent.com/15385727/69823715-a1615800-1201-11ea-841f-f8a433313f77.png)

Thanks

**Comment by ahocevar** [comment]
As mentioned before, this is a browser limitation. You should report this to the vendors of the browsers you are targeting.

That said, you can improve the situation a bit by configuring the `VectorImageLayer` with `ratio: 1`. That will reduce the area that needs to be rendered.
