### ISSUE TITLE
Full screen heatmap webgl error

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#10354]
When an heatmap layer is displayed in full screen and when a small screen (mobile device), the following error is raised:
`WebGL: INVALID_VALUE: texImage2D: width or height out of range`

This can be reproduce with https://5x9up.csb.app/ an by using the emulated device of the chrome debugger. (example source https://codesandbox.io/s/heatmap-earthquakes-5x9up)

**Comment by jahow** [comment]
I have reproduced this, it happens when the HTML page does not have a `<meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">` tag and a pixel ratio > 1. Will work on a fix ASAP.

Thanks!
