### ISSUE TITLE
Funding for openlayers

### ISSUE THREAD

**Issue by chrisvxd** [openlayers/openlayers#10359]
Hey team! 👋

Just wanted to reach out about funding `openlayers`.

@transitive-bullshit and I are both open source maintainers, and we're exploring new ways to make OSS funding a viable source of income.

We're currently looking at building SaaS APIs on top of existing OSS libraries, reserving the majority of profits for the original authors. [We've built a few](https://saasify.sh/#/showcase) at this point, but want to keep adding more.

I think an API using `openlayers` to render maps could be awesome, and I'd love to discuss building an MVP SaaS API on top of it. We'd handle the dev, auth, billing and support so you wouldn't have to do anything.

Looking forward to hearing your thoughts! 🙏

**Comment by jahow** [comment]
Hi!

Thanks for reaching out. Your offer definitely sounds interesting and we'd love to hear more details. What exactly do you have in mind in terms of usage? Would the developer still have access to the library APIs or would there be an intermediate layer?

I'm not an expert on hosted lambda and the like but I have a hard time visualizing how one could use OpenLayers in a "functional" way.
