### ISSUE TITLE
Full-screen-false button character "\u2922" is not displayed on some ? Android devices

### ISSUE THREAD

**Issue by eldk** [openlayers/openlayers#10351]
**Describe the bug**
Full-screen-false button character "\u2922" is not displayed on some ? Android

![full-screen-false-no-character](https://user-images.githubusercontent.com/11083657/69835541-a397d680-1242-11ea-94db-c38e620f0879.png)

![full-screen-false-no-character-ol-example](https://user-images.githubusercontent.com/11083657/69835544-a98db780-1242-11ea-8f16-c812ed366fcc.png)

The html source code is OK :  `<button class="ol-full-screen-false" type="button" title="Plein-écran">⤢</button>`

I have tested it on Android (Lineage OS 14.1 with Chromium 78 and Firefox lite (firefox 69) : same result.

**To Reproduce**
1 - goto https://openlayers.org/en/latest/examples/full-screen.html
2 - open url with some Android device 
3 - the ⤢ "\u2922" is not displayed but a replacement character (a square with a contained cross).

**Expected behavior**
Have the ⤢ displayed.

Maybe it should be tested with other devices and Android version to be confirmed ?

Thanks,

Eric

https://developer.android.com/guide/topics/resources/internationalization
https://stackoverflow.com/questions/52792453/unicode-character-to-represent-fullscreen

**Comment by eldk** [comment]
Hello,

I have "solved" it using : 
```
new FullScreen({
                     label: '\u26F6'
```

This unicode is displayed on both Firefox and Chromium for Android. 

Eric

**Comment by greggian** [comment]
This could be related to the font-family in use on your page? It looks like Openlayers doesn't specify a font-family in it's css file so the full-screen element will inherit the font family of the containing page.

Should OpenLayers specify a font-family known to support the Unicode characters it uses for this and other symbols?
