### ISSUE TITLE
ol.format.MVT in ol6

### ISSUE THREAD

**Issue by yiwenzhang666999** [openlayers/openlayers#10357]
When I use the readFeatures method of MVT in ol4 or ol5, I only need to pass one parameter, but I need to pass an extent parameter in ol6. I don't know how the extent is constructed? Below is my code

 var resource = Cesium.Resource.createIfNeeded(url);
 return resource.fetchArrayBuffer().then(function (arrayBuffer) {
                        var canvas = document.createElement('canvas');
                        canvas.width = 512;
                        canvas.height = 512;
                        var vectorContext = canvas.getContext('2d');
                       
                        var features = that._mvtParser.readFeatures(arrayBuffer, { extent: ？ });
                       var extent = [0, 0, 4096, 4096];
                        var styleFun = that._styleFun();

                        //var _replayGroup = new ol.render.canvas.ReplayGroup(0, extent,
                        //   8, that._pixelRatio, true, null, 100);
                        var builderGroup = new ol.render.canvas.BuilderGroup(0, extent,
                            8, that._pixelRatio, 100);
                        for (var i = 0; i < features.length; i++) {
                            var feature = features[i];
                            var styles = styleFun(features[i], that._resolutions[level]);
                            if (styles) {
                                for (var j = 0; j < styles.length; j++) {
                                    //ol.renderer.vector.renderFeature(_replayGroup, feature, styles[j], 16);
                                    ol.renderer.vector.renderFeature(builderGroup, feature, styles[i], 16, null);
                                }
                            }

                        }

                        /*function execute(builder, pixelRatio, overlaps) {
                            const executor = new ol.render.canvas.ExecutorGroup([-20037508.342789244, 20037508.342789274], 1,
                                that._pixelRatio || 1, true, builderGroup.finish());
                            executor.execute(vectorContext, that._transform, 0, false);
                          }*/
                          // -20037508.342789244, -20037508.342789274,20037508.342789244, 20037508.342789274
                        const executor = new ol.render.canvas.ExecutorGroup(null, 1,
                            that._pixelRatio || 1, true, builderGroup.finish());
                        executor.execute(vectorContext, that._transform, 0, false);

                        //var executorGroupInstructions = builderGroup.finish();
                        //var renderingReplayGroup = new ol.render.canvas.ExecutorGroup(replayExtent, resolution, pixelRatio, source.getOverlaps(), executorGroupInstructions, layer.getRenderBuffer());
                        //var renderingReplayGroup = new ol.render.canvas.ExecutorGroup(vectorContext, 8, that._pixelRatio, true, executorGroupInstructions, 0);

                        //_replayGroup.finish();

                        //_replayGroup.replay(vectorContext, that._pixelRatio, that._transform, 0, {}, that._replays, true);
                        vectorContext.restore();
                        if (that._tileQueue.count > that._cacheSize) {
                            trimTiles(that._tileQueue, that._cacheSize / 2);
                        }

                        canvas.xMvt = x;
                        canvas.yMvt = y;
                        canvas.zMvt = z;
                        that._tileQueue.markTileRendered(canvas);

                        //delete _replayGroup;
                        _replayGroup = null;

                        return canvas;
                    }).otherwise(function (error) {
                    });

**Comment by ahocevar** [comment]
You need to pass the extent of the tile that you're reading the features for:
```js
const extent = source.getTileGrid().getTileCoordExtent(tile.getTileCoord());
```

**Comment by yiwenzhang666999** [comment]
hi @ahocevar Thank you for your reply. As in the above code, I used the tiles directly requested by Cesium. No source or tile was used. Do I need to build them again, or is there another way?

[mvt.docx](https://github.com/openlayers/openlayers/files/3905398/mvt.docx)

**Comment by yiwenzhang666999** [comment]
hi @ahocevar In ol6, the screen coordinates in the read vector tile data are converted into the coordinates of the specified coordinate system. Will this not affect performance? 
I encountered a problem, I was loading vector tiles (.pbf file, stored screen coordinates), read the feature with mvt.readFeatures () method, and rendered it with ol.renderer.vector.renderFeature (), but no As a result, when I comment out 178 lines, the graphics can be rendered. Is the extent passed in by calling mvt.readFeatures () wrong?
var minX = that._resolutions[z] * 256 * x + that.originPointX;
var maxX = that._resolutions[z] * 256 * (x + 1) + that.originPointX;
var minY = that.originPointY - that._resolutions[z] * 256 * (y + 1);
var maxY = that.originPointY - that._resolutions[z] * 256 * y
var tileExtent = [minX, minY, maxX, maxY]
var extent = [0, 0, 4096, 4096];
var options = {
    featureProjection: 'EPSG:3857',
    extent: tileExtent
};

var features = that._mvtParser.readFeatures(arrayBuffer, options);
console.log("x:" + x + "  y:" + y + "  z:" + z);
var styleFun = that._styleFun();


var builderGroup = new ol.render.canvas.BuilderGroup(0, extent,
    8, that._pixelRatio, 100);
for (var i = 0; i < features.length; i++) {
    var feature = features[i];
    var styles = styleFun(features[i], that._resolutions[level]);
    if (styles) {
        for (var j = 0; j < styles.length; j++) {
            ol.renderer.vector.renderFeature(builderGroup, feature, styles[j], 16, null);
        }
    }

}
![image](https://user-images.githubusercontent.com/31643589/70609737-4423c880-1c3d-11ea-9246-e57a1b3f3a03.png)

**Comment by ahocevar** [comment]
You need to pass a `Projection` instance as `projection` option of `readFeatures()`. So not `'EPSG:3857'`, but `ol_proj_get('EPSG:3857')`.

Regarding your concern about performance: The transformation to map coordinates and back to viewport coordinates is not more expensive than the transformation from tile relative pixel coordinates to viewport coordinates

**Comment by yiwenzhang666999** [comment]
hi @ahocevar Thank you very much for your reply. I don't quite understand ol_proj_get. Is it a new ol.proj.Projection?

var extent = [0, 0, 4096, 4096];
var  pro = new ol.proj.Projection(
    {
        code:'EPSG:3857',
        units:'m',
        extent:tileExtent
    }
);
var options = {
    featureProjection: pro,
    extent: tileExtent
};

**Comment by ahocevar** [comment]
I meant
```js
import {get as ol_proj_get} from `ol/proj`.
```

**Comment by yiwenzhang666999** [comment]
Thank you very much for your reply, I understand

**Comment by yiwenzhang666999** [comment]
hi @ahocevar  i found when featureProjection and dataProjection are the same,Line 178 will also undergo coordinate conversion. The reason is that when the calculated scale of line 222 is 1, line 223 will also change the value of temTransform. Therefore, I judged the situation of level 1 in transform.js. The result is correct, I don't know if it is appropriate
![image](https://user-images.githubusercontent.com/31643589/70707166-7ce1a180-1d12-11ea-89e1-502dce2867fb.png)
![image](https://user-images.githubusercontent.com/31643589/70707190-89fe9080-1d12-11ea-8332-ee1714414802.png)

**Comment by yiwenzhang666999** [comment]
hi @ahocevar  When I use ol4's ol.renderer.vector.renderFeature method, I don't need to write a listener, the text and graphics of the graphic can be rendered correctly, but the 5th parameter after upgrading to ol6 needs to be passed into the listener. I don't know how to build This listener, because if it is not passed, the graphics can be rendered, but the text and symbols are not，There is complete code at the beginning of this question，I look forward to your reply

![image](https://user-images.githubusercontent.com/31643589/70884185-380a8300-2010-11ea-8138-0bf09622e4cb.png)

![image](https://user-images.githubusercontent.com/31643589/70883910-6176df00-200f-11ea-9dd4-75c8ea2fe578.png)

 ol.renderer.vector.renderFeature(builderGroup, feature, styles[j], 16, null);

**Comment by ahocevar** [comment]
That listener simply has to trigger a redraw of the tiles. It is called when icons are loaded.

**Comment by yiwenzhang666999** [comment]
hi @ahocevar  Thank you very much for your reply，I want to know that when the ol.renderer.vector.renderFeature method is called in ol6, the text and symbols are not rendered because of this listener? Or do you give me some ideas, what caused it?

**Comment by yiwenzhang666999** [comment]
hi @ahocevar When I constructed ol.render.canvas.BuilderGroup (0, extemtMer, resolutions [z], that._pixelRatio, 100), the third parameter I used was the resolution of the tile's level, but I found that it seemed to Correct, can you tell me how to use the third parameter?

**Comment by yiwenzhang666999** [comment]
When I set the second parameter of ol.render.canvas.BuilderGroup to the range of the tile, the third parameter is only the resolution of the current level. ], 16, null) The graphics have not been rendered. I looked at the final rendering in ol.layer.VectorTile and found that the third parameter resolution in the final builder group is not the current tile resolution. caused
