### ISSUE TITLE
Overlay stopEvent doesn't work when element is SVG

### ISSUE THREAD

**Issue by agxs** [openlayers/openlayers#10355]
**Describe the bug**

I'm trying to interact with an overlay using a click handler with an SVG icon as a button. Clicking this SVG icon causes the event to be incorrectly propagated through to the map. If I replace the SVG icon with some text then the click event is correctly stopped.

I've modified the example at https://openlayers.org/en/latest/examples/popup.html to demonstrate the problem.

**To Reproduce**

https://gist.github.com/agxs/a66b5829aab32e2093c3bd890e2f39c5
This is the example above modified to demonstrate the behaviour. The only change I've made is to `index.html`, but I've included `index.js` & `package.json` for completeness.

I replaced the `<a href="#" id="popup-closer" class="ol-popup-closer"></a>` with `<span>` + `<SVG>` element. Clicking on this element closes the overlay, but also opens up a new one due to the click event incorrectly propagating to the map.

**Expected behavior**

Clicking in the overlay when it has `stopEvent: true` should not propagate events to the underlying map, no matter what DOM element is being clicked.

**Comment by agxs** [comment]
Possibly related to https://github.com/openlayers/openlayers/issues/10162 ?

**Comment by fredj** [comment]
#10255 fixes a similar issue with SVGs and events.

**Comment by agxs** [comment]
Thanks, looks like #10255 fixed the above issue. I tested version 6.1.1-dev.1575196529512 and I'm not experiencing the problem any more.
