### ISSUE TITLE
how can i get only changed,add,remove feature from vector source

### ISSUE THREAD

**Issue by aim8526** [openlayers/openlayers#10360]
I want to know is there any way to get all updated,added and removed features together from vector source.
Here, vector source is  loaded by Url  and having data in geojson format.
It should return empty array in case of no changes done.

e.g. :-
sourceWFS = new ol.source.Vector({
        url: VectorSourceApi,
        format: new ol.format.GeoJSON(),
        strategy: ol.loadingstrategy.bbox
});

**Comment by jahow** [comment]
Hi,

Sorry but I didn't fully understand your issue. You can listen to the `addfeature`, `changefeature` and `removefeature` events on the vector source (as per the [apidoc](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html)).
