### ISSUE TITLE
tileLoadFunction in VectorTile does not load

### ISSUE THREAD

**Issue by aka512** [openlayers/openlayers#10361]
**Describe the bug**
tileLoadFunction in VectorTile does not load.

**To Reproduce**
when using a VectorTileSource the overwrite of the tileLoadFunction does not work
```
import VectorTileSource from 'ol/source/VectorTile';

let layerSource = new VectorTileSource({
        attributions: "",
        format: new MVT(),
        url: 'http://localhost/tiles/{z}/{x}/{y}',
        tileLoadFunction: function (tile, url) {
            tile.setLoader(function (extent, resolution, projection) {
                console.log(extent, resolution, projection);
                //...
            });
        },
        strategy: bbox
    });
```
the check in 
https://github.com/openlayers/openlayers/blob/master/src/ol/source/VectorTile.js#L110
is always false.

**Expected behavior**
I should be checked agains "undefined" and then use the defaultLoader.

**Comment by mike-000** [comment]
I don't know why your function isn't being called but that line doesn't prevent a custom function (which logs to prove it is being called) being set https://codesandbox.io/s/osm-vector-tiles-q4oqy

**Comment by aka512** [comment]
ideed sorry, the root issue was not having a url specified. its a bit confusing what parameter is optional and what not. I mixed that up
