### ISSUE TITLE
readFeatures method throws an error

### ISSUE THREAD

**Issue by dmenneck** [openlayers/openlayers#10364]
I am experiencing an issue with OpenLayers readFeatures method. Whenever i try to include this code...
```
const format = new OlFormatGeoJSON();
// following line throws an error
const features = format.readFeatures(buildingsData);
```
... into my react-geo application, the following error message shows up: 
```
Uncaught SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at getObject (JSONFeature.js:216)
    at GeoJSON.readFeatures (JSONFeature.js:59)
    at Module../src/components/Map.js (Map.js:107)
    (and many more) 
```
I already tried to reinstall Ol and react-geo, but the error message still remains the same. My goal is to implement the [AgFeatureGrid](https://github.com/terrestris/react-geo/blob/master/src/Grid/AgFeatureGrid/AgFeatureGrid.example.md) from react-geo, but i'm not sure if the problem stems from react-geo or Open Layers.

[here](https://github.com/dmenneck/campusmap) you can find the repo.

**Comment by ahocevar** [comment]
This error comes from invalid GeoJSON. Check your `buildingsData`.

**Comment by dmenneck** [comment]
Without the `readFeatures` method the app gets rendered and the GeoJSON file gets displayed on the map. How can the file be invalid then? 

Thanks for your help!

**Comment by mike-000** [comment]
At https://github.com/dmenneck/campusmap/blob/master/src/components/Map.js#L56 you use `buildingsData` as a url.  It cannot be both a url and a json string.

**Comment by dmenneck** [comment]
The error message still remains the same, even if i delete the url in Line 56.

**Comment by ahocevar** [comment]
As @mike-000 pointed out, `buildingsData` holds a `url`, but `readFeatures()` expects a JSON object or string. So you'd have to change your code to something like
```js
const format = new OlFormatGeoJSON();
fetch(buildingsData).then(response => response.json()).then(json => {
  const features = format.readFeatures(buildingsData);
});
```

**Comment by dmenneck** [comment]
Now it works. Thanks for your help!
