### ISSUE TITLE
chrome warning 

### ISSUE THREAD

**Issue by aegs777** [openlayers/openlayers#10372]
A cookie associated with a cross-site resource at https://openlayers.org/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

¿ Why ?

**Comment by ahocevar** [comment]
On which page exactly were you seeing this warning?
