### ISSUE TITLE
RBush class in bundle

### ISSUE THREAD

**Issue by walkermatt** [openlayers/openlayers#10379]
**Describe the bug**
`class RBush` is found in my bundle after bundling using Rollup. This appears to be due to https://github.com/mourner/rbush including a non-transpiled `index.js` in the package on npm and `package.json` specifying `"module": "index.js",`.

**To Reproduce**
1. Clone https://github.com/openlayers/ol-rollup
2. Modify `main.js` in ol-rollup so that the RBush package is used (`ol/structs/RBush~RBush` imports the `rbush` package).

```js
import {Map, View} from 'ol';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';

import RBush from 'ol/structs/RBush';

new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: new XYZ({
        url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      })
    })
  ],
  view: new View({
    center: [0, 0],
    zoom: 2
  })
});

var rbush = new RBush(9);

```
3. Run `npm run start` to create a debug bundle using Rollup
4. Open `bundle.js` and search for `class RBush`

**Expected behavior**
The transpiled version of the RBush package should be found in the bundle instead.

**Proposed solution**
Change imports in the ol source to import the transpiled version:

```diff
-import RBush from 'rbush';
+import RBush from 'rbush/rbush.js';
```

**Comment by walkermatt** [comment]
Happy to submit a PR

**Comment by ahocevar** [comment]
I tend to think the current behavior is correct, because it allows Rollup (and other bundlers) to do better tree shaking, resulting in smaller bundles. Is this causing a problem in your setup?

**Comment by walkermatt** [comment]
The issue is with the bundle containing the ES6 `class` statement which isn't supported by IE. My understanding is that it's fine to use ES6 syntax and features in your app providing it's transpiled to ES5 as part of creating a bundle but generally 3rd party code is expected to be in ES5 with the exception of using ESM modules.

**Comment by ahocevar** [comment]
@walkermatt I do see your point. This behavior of packages (i.e. specifying a `"module"` entry in `package.json` is becoming more common though, and allows bundlers to take more advantage of tree shaking.

However, in the case of RBush, it seems we are using everything from the package anyway, so please go ahead and create a pull request as you suggested.
