### ISSUE TITLE
problems with adding baidu layer

### ISSUE THREAD

**Issue by zhangjin747** [openlayers/openlayers#10374]
I want to add a layer with Baidu tiles to OpenLayers, and I saw @tschaub's  [#3522Comment](https://github.com/openlayers/openlayers/issues/3522#issuecomment-222769406) 
I'm using version 6.1.1 and I changed `y` in `tileUrlFunction` to `-tileCoord[2] - 1`.
However, only the region of China is rendered correctly. Also, there's a strip on the right side of the Map. 
![image](https://user-images.githubusercontent.com/33750515/70017872-522f7480-15bf-11ea-9ce4-1063f9e45043.png)
I don't know if I made the question clear. 
Here is the Code: [https://codesandbox.io/s/xyz-6zzh6](https://codesandbox.io/s/xyz-6zzh6)

**Comment by tschaub** [comment]
Bump

**Comment by ahocevar** [comment]
See https://codesandbox.io/s/xyz-w6i5o for a working example with OpenLayers 6.x.

**Comment by blissvisitor** [comment]
it's not soleved
