### ISSUE TITLE
Layer Swipe example does not handle view rotation in OpenLayers 6

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10371]
**Describe the bug**
For some layer types the canvas can be rotated in OpenLayers 6 and the example does not handle that.

**To Reproduce**
As the Bing layer isn't working in the online examples compare rotating the views here
with v5.3.0 https://codesandbox.io/s/layer-swipe-k35iz and with v6.1.1 https://codesandbox.io/s/layer-swipe-8i88c

**Expected behavior**
Both versions should behave similarly.

**Comment by ahocevar** [comment]
@mike-000 Thanks for reporting. Would you be able to create a pull request with a fix?

**Comment by mike-000** [comment]
The Layer Spy, Layer Clipping and possibly the Magnify examples are also affected.  I'll take at look at each of them.
