### ISSUE TITLE
When change the map zoom, position of text  is change.

### ISSUE THREAD

**Issue by SSaeedHoseini** [openlayers/openlayers#10375]
When I add some WFS feature (purple feature) to layer with style, it is pretty good but when I change the map zoom, position of text is change! 
 
Anyone can explain what is wrong?

![Screen-Recording-_12-3-2019-8-44-42-AM_](https://user-images.githubusercontent.com/47109202/70022445-7bdda100-15a9-11ea-8c1b-b38ab06ebab5.gif)

**Comment by jahow** [comment]
The behaviour is indeed weird. To help you further we need you to give us the OL version you use, as well as a minimal reproduction case using https://codesandbox.io for example.

Thanks!
