### ISSUE TITLE
hit detection per layer problem

### ISSUE THREAD

**Issue by kikitte** [openlayers/openlayers#10378]
**Describe the bug**
In the official example, [Vector Layer Hit Detection](https://openlayers.org/en/latest/examples/hitdetect-vector.html) and [Vector Tile Selection
](https://openlayers.org/en/latest/examples/vector-tile-selection.html). It looks like there is an problem when clicking or mouse over an empty area that no feature inside it , another feature is always highlighted even though it is not under the mouse pointer. 

**To Reproduce**
1. Go to [Vector Layer Hit Detection](https://openlayers.org/en/latest/examples/hitdetect-vector.html) or [Vector Tile Selection
](https://openlayers.org/en/latest/examples/vector-tile-selection.html)
2. Click or hover over an empty area the no feature inside
3. another feature is highlighted.

**Expected behavior**
No feature is hit when click or mouse over  an empty area.

**Comment by ahocevar** [comment]
This was fixed with #10308.
