### ISSUE TITLE
ImageStatic rotation issue when map is rotated

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#10382]
I have ImageStatic rotated via prerender/postrender events this way:

            result = new LayerImage({
                opacity: overlay.Asset.Opacity,
                source: new ImageStatic({
                    url: overlay.Asset.Url,
                    imageExtent: imgExtent,
                    projection: this.map.getView().getProjection(), 
                    imageLoadFunction: (image, src) => {
                        let imageElement = image.getImage() as HTMLVideoElement;
                        imageElement.src = src;
                        imageElement.width = overlay.Asset.Width;
                        imageElement.height = overlay.Asset.Height;
                    }
                }),
                zIndex: 2
            });

             // handle rotation
            result.on("prerender",
                (evt) => {
                    let ratio = evt.frameState.pixelRatio;
                    let pixel = this.map.getPixelFromCoordinate(getTopLeft(imgExtent));
                    let ctx = evt.context;
                    ctx.save();
                    ctx.translate(pixel[0] * ratio, pixel[1] * ratio);
                    ctx.rotate(overlay.Asset.Rotation);
                    ctx.translate(-pixel[0] * ratio, -pixel[1] * ratio);
                });

            result.on("postrender",
                (evt) => {
                    let ctx = evt.context;
                    ctx.restore();
                });          

If I rotate map then the ImageStatic loses it's position and jumps to wrong position even durring map moving as you can see on the attached gif. If map is not rotated then the position of the image is corr
![imageStatic](https://user-images.githubusercontent.com/3100059/70216233-6a2e0200-173f-11ea-9772-fa7ad62999a3.gif)

Check code snippet and gif. Openlayers version: 6.1.1

**Expected behavior**
ImageStatic rotates with the map without jumping to wrong position.

**Comment by mike-000** [comment]
Surely you would need to rotate around the image center? 

    let mapPixel = this.map.getPixelFromCoordinate(getCenter(imgExtent));

and to convert the mapPixel to canvas pixel use

    let canvasPixel = getRenderPixel(event, mapPixel);
    ctx.translate(canvasPixel[0], canvasPixel[1]);

as the pixelRatio for an individual layer canvas may not match the map pixel ratio - see https://openlayers.org/en/latest/examples/magnify.html

**Comment by MichalK6677** [comment]
I do not want to rotate around the image center. I want to rotate around the topLeft corner and it's not working.

**Comment by mike-000** [comment]
Regardless of where the rotation is to be centered if the view is being rotated you should use the getRenderPixel method as the canvas may be offset to accommodate the rotated view.

**Comment by MichalK6677** [comment]
The function "getRenderPixel" is the key of my success, thank you. You can close this issue.
