### ISSUE TITLE
ol/interaction/Modify Latitude and longitude after change

### ISSUE THREAD

**Issue by YuK1Game** [openlayers/openlayers#10383]
I want to display the latitude and longitude after moving when creating and moving a circle.

```jsx
const source = new VectorSource({  });
const draw = new OlDraw({ source });
const modify = new Modify({ source });
modify.on('modifyend', event => {
    // I want to display the center point of the circle here
});
```

`draw.on('drawend', event => console.log(event.target.sketchCoords_);`

in center values.

Doesn't exist in Modify?

Thanks.

**Comment by mike-000** [comment]
You can use `event.features.item(0).getGeometry().getCenter()`

and in a draw interaction `event.feature.getGeometry().getCenter()`

https://codesandbox.io/s/draw-and-modify-features-ggbbi

**Comment by YuK1Game** [comment]
ok, thanks!
