### ISSUE TITLE
Can only remove half a maps layers synchronously

### ISSUE THREAD

**Issue by megawac** [openlayers/openlayers#10388]
**Describe the bug**

In OL6, when I attempt to remove layers from a map, only half the remove events get registered when I call `removeLayer` synchronously

**To Reproduce**

https://codesandbox.io/s/geojson-vgm9p

1. Load multiple layers into a map
2. Remove all layers from the map

```js
const layers = map.getLayers();
console.log("initial layer count", layers.getLength());
// Will log `n`
layers.getArray().forEach(l => map.removeLayer(l));
console.log("layer count post remove", layers.getLength());
// Will log `n / 2`
```

3. Observe that every other layer has been removed from the map (rounding up)

**Expected behavior**

All layers should be removed.

**Comment by mike-000** [comment]
It is because you are removing entries from the array used by `forEach`.

If you clone the array all layers will be removed

`layers.getArray().slice().forEach(l => map.removeLayer(l));`

**Comment by megawac** [comment]
Whoops, thats silly of me!

**Comment by megawac** [comment]
Actual issue I was trying to figure out how to reproduce with this ticket is #10389
