### ISSUE TITLE
Removing layers from map with no target does not clean up canvas

### ISSUE THREAD

**Issue by megawac** [openlayers/openlayers#10389]
**Describe the bug**

When you attempt to remove layers from a map without a `target` element, the layers canvases do not get cleaned up. The layers are removed from the map, however if you reassign the map to a `target` element, the old layer canvas will be made visible again

**To Reproduce**
https://codesandbox.io/s/geojson-vgm9p

1. Mount a map with several layers, assign the map to a target element.
2. Unset the `map`s target (`map.setTarget(null)`)
3. Remove the layers from the map `map.getLayers().getArray().slice().forEach(layer => map.removeLayer(layer))`
4. Set the maps target again

**Expected behavior**

The canvas of the removed layers should not exist any more, or `document.querySelectorAll('canvas')`  should return no elements.

**Comment by ahocevar** [comment]
@megawac #10394 should fix this issue. Can you take a look at that to see if it satisfies? Thanks!
