### ISSUE TITLE
Extent and wrapX are incompatible

### ISSUE THREAD

**Issue by PacoDu** [openlayers/openlayers#10387]
**Describe the bug**
Defining an extent for a layer and setting wrapX to true for the source breaks wrapX behavior.
This is problematic if you want to display an XYZ service that serves data only for a small extent, you can't enable wrapX without disabling the extent which creates a lots of network overhead (useless tiles queries emitted outside of the layer extent availability).

**Expected behavior**
Allow to define extent AND wrapX to optimize network usage.

**Comment by mike-000** [comment]
Here is an example of extent and wrapX used together https://codesandbox.io/s/simple-9rtse  But you cannot have multiple extents, either on the same world or different worlds.

**Comment by PacoDu** [comment]
Sorry I got confused with wrapX and multiWorld. I meant that extent combined with wrapX and multiWorld are incompatible.

**Comment by mike-000** [comment]
multiWorld isn't compatible with a view extent, as the API says "Note that if extent is also provided it is given precedence".

With a layer extent you can only have one per layer and for example [10, 20, 30, 40] in one world would be [190, 20, 210, 40] in the next - you cannot specify both and there is currently no automatic wrapping.

**Comment by mike-000** [comment]
If your XYZ tiles are served over a limited extent you can specify that in a custom tile grid https://codesandbox.io/s/simple-91ynq
