### ISSUE TITLE
Safari: artifacts when dragging popup

### ISSUE THREAD

**Issue by bfabiszewski** [openlayers/openlayers#10390]
I observe strange traces left behind popup while dragging map with mouse.

![Screen Shot 2019-12-06 at 22 45 21](https://user-images.githubusercontent.com/3366666/70359392-183ec680-187c-11ea-9911-d1537f00ab17.png)

It happens only in Safari browser (tested with version 13.0.3 on macOS) and OpenLayers versions 6.0.0 and newer. It is not visible in 5.3.3 and below. It also cannot be reproduced in Firefox and Chrome. 

The artifacts disappear when resizing browser window.

It may be reproduced on [popup example page](https://openlayers.org/en/latest/examples/popup.html).

**Comment by ahocevar** [comment]
This sounds familiar. I had noticed this in https://github.com/openlayers/openlayers/issues/9467#issuecomment-487051322 already, but I thought @fredj's in #9701 fixed it. Well, apparently it did not.

**Comment by bfabiszewski** [comment]
I can confirm that using `box-shadow` fixes the issue, thanks!
