### ISSUE TITLE
Select interaction is bugged with Overlay

### ISSUE THREAD

**Issue by SimonChatillon** [openlayers/openlayers#10406]
Hello,

I have a vector layer with a select interaction.

On select, I display an ol.Overlay.

My overlay element has buttons, when I click on those buttons, the onSelect is triggered and my feature gets deselected.

The stopEvent parameter in my overlay is unset so it should be true by default. My OL version is 6.0.1.

Is it the normal behaviour ?

**Comment by SimonChatillon** [comment]
I couldn't manage to create a simple use case to reproduce my problem, but it has to be a combination of using an angular component which contains a svg path in my overlay. The problem appeared only when the target of the click event was a SVGPathElement, but again I couldn't reproduce this in a simple vanilla js use case, it worked fine even with a svg path element...

So I solved my problem by creating a mask with a simple div above my svg path component and then it worked...
It's weird I didn't found the origin of the problem, maybe to be continued...

**Comment by DaniEll-AT** [comment]
There were some changes recently: #10355, #10255, #10162 
None of them is in 6.0.1
