### ISSUE TITLE
Open layer doesn't work with angular 5

### ISSUE THREAD

**Issue by panagiwtis** [openlayers/openlayers#10408]
Hello I have create a web application with angular 5 to display maps using openlayers(ol) package  v5.3.3 and my own self-hosted tileserver and  it's working properly. But when I update to ol v6.1.1 maps are not rendering and there is no error in browser debugger console.  
Any suggestions??

**Comment by jahow** [comment]
> Any suggestions??

Apparently there were some issues with the map not having a size (width and height to 0) when migrating to OL 6. Maybe you could start from here?

Apart from that, to really help you we'd need a minimal reproduction case using codesandbox.io or equivalent. Thanks.
