### ISSUE TITLE
Panning and zooming issues on MobileIron Web@Work App

### ISSUE THREAD

**Issue by chrigel** [openlayers/openlayers#10403]
The OpenLayers map does not work correctly in a MobileIron Web@Work App on a iOS device. Panning and zooming are not working correctly. This behavior is hard to reproduce because a MobileIron infrastructure is needed. Also, I'm not sure if it's an issue of OpenLayers or the MobileIron Web@Work App itself. 

1. Open the OpenLayers examples in MobileIron Web@Work App
2. Zoom and pan

**Expected behavior**
OpenLayers examples should work properly

**Comment by jahow** [comment]
Hi, which version of OL do you use? Thanks

**Comment by chrigel** [comment]
The newest, 6.1.1. Issues are reproducable on the official examples site.
