### ISSUE TITLE
Openlayers and Dojo 14 ios

### ISSUE THREAD

**Issue by bucibucii** [openlayers/openlayers#10410]
There is a strange behaviour when using dojo 14 and ol 6.1.1 on iPhone.
button click event is fired multiple times without stopping.

Open the link below on iPhone and click the switch button.

[Url for test](https://jsfiddle.net/bucibucii/4s892fuh/2/show)

**Comment by ahocevar** [comment]
Sorry, I cannot reproduce with your test url. I don't see any click handler in there.

**Comment by bucibucii** [comment]
if you just click the switch button you will see the problem
