### ISSUE TITLE
GeoJSON MultiPoint not working in WebGL points examples

### ISSUE THREAD

**Issue by umbe1987** [openlayers/openlayers#10436]
**Describe the bug**
This is smilar to #8873.

Apparently, using a multipoint GeoJSON with one of the WebGL Point examples ([1](https://openlayers.org/en/latest/examples/webgl-points-layer.html), and [2](https://openlayers.org/en/latest/examples/filter-points-webgl.html)) does not seem to work as only one dot in the center of the screen is displayed all the time.

![Screenshot from 2019-12-19 11-28-43](https://user-images.githubusercontent.com/15016826/71166371-e140bb80-2252-11ea-8d75-4987dc9a4b15.png)

**To Reproduce**
Test the code with the GeoJSON uploaded (JSON both work in geojsonlint.com and http://geojson.io)

**Expected behavior**
All the points should be visible in the map rather than just one in the center of the screen.

![Screenshot from 2019-12-19 11-40-11](https://user-images.githubusercontent.com/15016826/71167062-4517b400-2254-11ea-9d22-3d3bb3eb2a40.png)

[test.zip](https://github.com/openlayers/openlayers/files/3983101/test.zip)

**Comment by jahow** [comment]
The renderer only supports Point geometries for now. Extending it to support multigeometries is not trivial since it currently assumes that the amount of points to render is the same as the amount of features in the source.
