### ISSUE TITLE
View constraints computation can cause a layout reflow

### ISSUE THREAD

**Issue by jahow** [openlayers/openlayers#10431]
The following method from the `ol/View` class reads the computed style of the viewport element, which triggers a layout reflow:
https://github.com/openlayers/openlayers/blob/2b45bc054ee2d0e95a8c4b0e98abe42cfb7da482/src/ol/View.js#L729-L745

See: https://gist.github.com/paulirish/5d52fb081b3570c81e3a#getcomputedstyle

This method is called very often now that we use the viewport size to apply view constraints.

A caching mechanism for element dimensions could be used to avoid this, provided this gives a performance/experience improvement.

**Comment by ahocevar** [comment]
Good find. You could also cache the viewport size, and only recalculate it after updateSize.
