### ISSUE TITLE
Vector Layer Memory Leak for version 6.1.1

### ISSUE THREAD

**Issue by Malgier** [openlayers/openlayers#10437]
Hi,

I'm currently experiencing an issue in my web application where vector layers are being retained in memory when leaving a page with the map, i currently have 20 vector layers on my map and everytime i leave and return to the page it retains those 20 layers and adds on a new set of the layers. It seems to be a similar issue to the one raised in issue #9556. This is my code for destroying the layers
```
const layers = this.map.getLayers();
while (layers.getLength() > 0) {
   const layer = layers.item(0);
   if (layer.get('layerSourceType') === 'VECTOR') {
      layer.getSource().clear();
   }
      layer.getRenderer().dispose();
      layer.setSource(null);
      this.map.removeLayer(layer);
}
this.map.setTarget(null);
this.map = null;
```

![Capture](https://user-images.githubusercontent.com/18699451/71178419-130f4d80-2266-11ea-9188-7e15fb89ff44.PNG)
![Capture1](https://user-images.githubusercontent.com/18699451/71178420-130f4d80-2266-11ea-9dee-da4e7485f4e8.PNG)
![Capture2](https://user-images.githubusercontent.com/18699451/71178418-130f4d80-2266-11ea-9644-3728d6a6125c.PNG)

**Comment by ahocevar** [comment]
When you leave a page, the browser will release all memory after a while. 

Also, there should not be any need to do any cleanup even on a page where you just remove the map. Only make sure to call setTarget(null) on the map.

If you still see memory not being released, can you provide an example that shows the memory leak?

**Comment by ahocevar** [comment]
Cross-posted in https://stackoverflow.com/questions/59421609/openlayers-6-1-1-vector-layer-memory-leak, closing.
