### ISSUE TITLE
GML32

### ISSUE THREAD

**Issue by wangjianjun0707** [openlayers/openlayers#10441]
Hello,

With Angular 8, typescript 3 environment, i try convert some xml into Feature[] like that :
const wfsFormat = new WFS({
        featureNS: 'http://localhost:6080/arcgis/services/demopoint/MapServer/WFSServer',
        featureType: 'SDE.LEGAL_PERSON_COLLECTION_INFO',
        schemaLocation: 'http://www.opengis.net/gml http://schemas.opengis.net/gml/3.2.1/gml.xsd http://www.opengis.net/ogc http://schemas.opengis.net/filter/2.0/filter.xsd http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsAll.xsd http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd http://www.opengis.net/fes/2.0 http://schemas.opengis.net/filter/2.0/filterAll.xsd',
        gmlFormat: new GML32({
          featureNS: 'http://localhost:6080/arcgis/services/demopoint/MapServer/WFSServer',
          featureType: 'SDE.LEGAL_PERSON_COLLECTION_INFO',
          srsName: 'EPSG:4326'
        })
      });
const features: Feature[] = wfsFormat.readFeatures(text);

But an exception is thrown :
ERROR TypeError: "this.gmlFormat_.FEATURE_COLLECTION_PARSERS[_GMLBase_js__WEBPACK_IMPORTED_MODULE_3__.GMLNS] is undefined"
readFeaturesFromNode WFS.js:236
readFeaturesFromDocument XMLFeature.js:127
readFeatures XMLFeature.js:106

In debug mode i see that in the FEATURE_COLLECTION_PARSERS there is only the namespace for GML32 'http://www.opengis.net/gml/3.2' while the value it try to get is undefined.

Its working for GML3 because it doesnt override default namespace GMLBase.prototype.namespace = GMLNS;

**Comment by Dimitriio** [comment]
Issue #10077 for other use case. (That had been close by "stale bot")

**Comment by jahow** [comment]
Hi,

I'm going to close this issue and reopen the old one as this one has exactly the same content but less readable and without a clear title.
