### ISSUE TITLE
Question: Tiled image with only one resolution

### ISSUE THREAD

**Issue by endquote** [openlayers/openlayers#10440]
I have a large image which I have divided up into tiles.

I would like to be able to zoom out such that all the tiles are visible.

As I zoom in, new tiles should not load, as there are no others available. The tiles are SVG, so scaling them up still looks good.

I'm having trouble figuring out which type of layer, source, and view settings would achieve this.

I have this working now:

```javascript
new Map({
  layers: [
    new TileLayer({
      source: new XYZ({
        url: "/drawing/{x}/{y}/{z}",
        tileSize: toSize([96, 96]),
        maxZoom: 0,
        minZoom: 0
      })
    })
  ],
  view: new View({ center: [0, 0], zoom: 0 })
})
```

I see that if XYZ maxZoom/minZoom are the same, I can zoom forever into them without more tiles loading, but I can't zoom out to see others.

I'm also not sure how I would specify the total size of my tiled image.

Source is here: https://github.com/endquote/endquote-next/blob/master/components/posts/drawing_series/DrawingMap.jsx

Current live version is here: https://endquote.com/post/drawing_series/

**Comment by mike-000** [comment]
If you have more than one tile at zoom 0 you will need to define a tile grid for the source https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_TileGrid-TileGrid.html

**Comment by endquote** [comment]
Thank you for the reply. I'm trying out TileGrid, and got this far, however I seem to be creating an infinite loop somewhere and crashing the browser. I'm attempting a grid of 64x24 tiles, each at 96x96 pixels.

For the TileGrid.extent, I'm not sure what units I'm meant to be working in -- tiles, pixels, or some sort of projection.

```javascript
new Map({
  layers: [
    new TileLayer({
      source: new XYZ({
        url: "/drawing/{x}/{y}/{z}",
        tileSize: toSize([96, 96]),
        maxZoom: 0,
        minZoom: 0,
        tileGrid: new TileGrid({
          extent: boundingExtent([
            [0, 0],
            [64, 24]
          ]),
          minZoom: 0,
          tileSize: toSize([96, 96]),
          resolutions: [96]
        })
      })
    })
  ],
  view: new View({ center: [0, 0], zoom: 0 })
})
```

**Comment by mike-000** [comment]
Something like this would work https://codesandbox.io/s/simple-zd9n8 but using a single 64 * 24 grid is going to cause a very heavy load if you zoom out to see all the tiles

**Comment by endquote** [comment]
This is perfect, thank you!

I misspoke and my grid is actually only 16x6, so not quite as bad.
