### ISSUE TITLE
RegularShape: radiuses array

### ISSUE THREAD

**Issue by Razi91** [openlayers/openlayers#10458]
Proposal to change RegularShape behavior.
Currently it has 2 options: `radius` and `radius2`. What about `radius3` etc.?

I propose change it to an array, leaving current behavior, but inside keeping it in an array, allowing using array as value for `radiuses`

It would allow defining more complex shapes, like SLD's wellknown `arrowhead`, which is half of square, but not regular triangle (it has one right angle). It could be defined as:

```js
new RegularShape({
    radiuses: [10, 10, 0, 10],
    points: 1,
    fill: new Fill({color: '#000000'})
})
```

RegularShape's constructor would check if `radiuses` exists, then keep it like that (and ignore `radius`, `radius1` and `radius2` in that case) or use both `radius`/`radius1` and `radius2` (if exists) to make an array. It would also simplify `draw_` method.

Methods `getRadius()` and `getRadius2()` could return first and second item of that array.

For `points == Infinity` I think the array should be ignored, taking only first radius from the array

// EDIT: could be used also to draw ellipses (second radius for `ol/style/Circle`), would be useful to add `angle` for it's constructor.

**Comment by Razi91** [comment]
Ok, I've made those changes, example of use:
```js
feature.setStyle(new Style({
    image: new RegularShape({
      fill: fill,
      stroke: stroke,
      points: 1,
      radiuses: [10, 10, 10, 0],
      rotation: Math.PI / 4,
      angle: 0
    })
  }));
```
gives: 
![image](https://user-images.githubusercontent.com/5995454/72461875-27e0f180-37d0-11ea-8ff2-3a8553db7cc5.png)

```js
new Style({
    image: new RegularShape({
      fill: fill,
      stroke: stroke,
      points: 4,
      radiuses: [10, 10, 5, 5],
      angle: Math.PI / 4
    })
  }),
```
gives: 
![image](https://user-images.githubusercontent.com/5995454/72461906-3e874880-37d0-11ea-9240-1281de9055bb.png)

I think if it should be still `RegularShape`. It would be useful to add also option `angleRatio`, with the same length as `radiuses`:
```js
{
  'bold-cross': new Style({
    image: new RegularShape({
      fill: fill,
      stroke: stroke,
      points: 3,
      radiuses: [15, 5, 5, 15],
      angleRatios: [0.25, 0.25, 0.75, 0.75]
    })
  }),
}
```
![image](https://user-images.githubusercontent.com/5995454/72470403-118f6180-37e1-11ea-8414-0c2fa2adc8dd.png)
(It's working example, but code is a huge mess right now).

I also think that those classes really need some refactor, there are a lot of code duplications, or not using attributes (like opacity which is in BasicShape, but not exposed in RegularShape's constructor), some fields are private, but should be protected.

`context.closePath();` should be also called right after drawing the shape, not after setting styles. It saves last loop pass while drawing the shape.

**Comment by sbrunner** [comment]
This seems difficult to understand, shouldn't it better to do something based on Bézier curve, it's not so simple but it's a standard way to draw vector graphic?
https://en.wikipedia.org/wiki/B%C3%A9zier_curve

**Comment by gberaudo** [comment]
See also https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/bezierCurveTo.

**Comment by Razi91** [comment]
This feature request is not about beziers. I think implementing bezier curves would require different solutions, maybe providing whole path. It's subject for different issue/feature.

Adding 2 optional attributes (`radiuses` that replaces `radius` and `angleRatios`, I'm not sure about this field name) is solving that. I have already changes done and ready to push, I think I'll push it later and serve on GH pages examples.

**Comment by Razi91** [comment]
Example: https://razi91.github.io/openlayers/regularshape.html
