### ISSUE TITLE
Disappearing features with 6.1.1, MVT in image mode, Windows-only

### ISSUE THREAD

**Issue by mmomtchev** [openlayers/openlayers#10454]
**Describe the bug**
I have this issue where some features will disappear when zooming the map.
The issue appears only on Windows with both Firefox and Chrome.
No problems on OS X or Linux.
5.3.0 makes the issue go away.
vector mode fixes it to.
The data is coming from a MVT server (modified geojson-vt and supercluster, both available on my Github), but I don't think this has any importance.

**To Reproduce**
https://jsfiddle.net/mmomtchev/pLchf0sk/
Start zooming in and out, best region is Northern Italy where there are lots of features. The more you zoom in and out, the more features will disappear. Some will be cut across the tile lines because of the buffering between tiles.
Happens only on Windows with both Firefox and Chrome.

**Comment by ahocevar** [comment]
I am unable to reproduce the issue, but one thing I notice is that your configuration says your view is in 'EPSG:3857', but the map looks like it is in a different projection. For vector tile layers, the tile projection needs to match the view projection.

**Comment by mmomtchev** [comment]
The projection is in fact EPSG:32663 which is almost EPSG:4326, I replaced it for the fiddle, but it should have been EPSG:4326
The tiles are in TILE_PIXELS and are EPSG:32663 too
It is clearly some sort of low-level rendering issue, because I get it only on one PC running Windows, but on it it happens with both Chrome and Firefox, so I am at loss to explain it

**Comment by ahocevar** [comment]
Please update your fiddle to use the correct projection configuration, so we can rule out issues with that. Also, a screen cast showing the issue would help, because I am unable to reproduce the issue.

From what you describe, your issue might be a memory issue with your Windows device. You have 7 layers, all of which get an image cache of a few dozen tiles. That may be too much for a device with low memory. This would also explain why setting vector render mode would solve the issue.

One thing you can try is configure your vector tile sources with a `cacheSize`. Try different sizes.

**Comment by mmomtchev** [comment]
I fixed it, sorry
https://jsfiddle.net/mmomtchev/pLchf0sk/37/

**Comment by mmomtchev** [comment]
cacheSize = 8 doesn't fix it
https://jsfiddle.net/mmomtchev/pLchf0sk/38/

**Comment by mmomtchev** [comment]
In fact, I do have a reprojection problem, some data is slightly offset
It is not the data, because it is ok on the production site (this is the production data), I will try fixing it first

**Comment by mmomtchev** [comment]
In fact, the feature are 3859-projected only inside the tiles, that's why MVT reprojection, which is normally not supported, works in this particular case. I will try to see if I can reproduce the render issue without such shenanigans, because this could be an explanation.

**Comment by mmomtchev** [comment]
I confirm, it is a projection problem
