### ISSUE TITLE
Is there any way to display feature's label in WebGL Point Layer?

### ISSUE THREAD

**Issue by comictvn** [openlayers/openlayers#10453]
Hello everyone, 

I have been re-search the document but there isn't any way to display feature's label base on property attribute of geojson so please give me the correct way to do this.
 
Expected:
![Screen Shot 2019-12-24 at 2 21 16 PM](https://user-images.githubusercontent.com/6270931/71400257-bee6dd80-2658-11ea-80bf-fab106d46cbd.png)

It will show near point feature

Thank you

**Comment by jahow** [comment]
Hi!

Unfortunately, the webgl points layer does not support text rendering yet. For that, you have to use a standard vector layer.

**Comment by comictvn** [comment]
@jahow thanks a lot

**Comment by Razi91** [comment]
You can add overlay manually. Add listener on source. But WebGL renderer is worth only if you have many points to render, otherwise just use standard VectorLayer.
