### ISSUE TITLE
a lot of polygon feature,map will freeze

### ISSUE THREAD

**Issue by Hgq1001** [openlayers/openlayers#10462]
When there are a lot of Polygon features, such as 40,000,dragging the map will freeze,How to optimize it ?
当有大量Polygon feature时，比如40000个，并且为feature设置颜色，拖动地图会卡顿

**Comment by kikitte** [comment]
Use vectorLayer instead, it is performance optimized.

**Comment by Rskut** [comment]
When the map freeze on dragging try ol.layer.VectorImage

**Comment by Hgq1001** [comment]
@Rskut  You are right！When use the VectorImage，no freeze ! Thank you
