### ISSUE TITLE
Error at VectorLayer.js:333:12after  if (vectorSource.getWrapX() && viewState.projection.canWrapX()

### ISSUE THREAD

**Issue by geomoes** [openlayers/openlayers#10464]
After switching from openlayers v 4.6.4 to v.6.1.1 I encounter the following error:
r is null  and points to the VectorLayer.js:333:12
When the page is loaded the screen stays blank (controls are visible) the error is dispayed in the web console. The map is drawn, when I pan or zoom an the error is repeated with every panning and zooming.

The page has a lot of layers, but even when I disable them all (blank page without background map) the error persists.

**Comment by mike-000** [comment]
It appears to be related to #10221 but specific to vector layers https://codesandbox.io/s/simple-kg7qt
