### ISSUE TITLE
Pieces of map do not appear when a tile layer is being reprojected.

### ISSUE THREAD

**Issue by pjsg** [openlayers/openlayers#10465]
**Describe the bug**

When zooming in and out on a map with a reprojected Tile layer, sometimes there are white areas. This turns out to be because the underlying Tile object has been disposed and is therefore excluded from the stitching process to make the source canvas for the reprojection.

**To Reproduce**
1. Go to https://pskreporter.info/testaeqd.html
2. Zoom in and out a bunch and pan around
3. See error -- example below

![image](https://user-images.githubusercontent.com/1508813/71559283-3be3cf80-2a2a-11ea-8cb7-93085d4596e1.png)

**Expected behavior**
No white area.

It seems that just modifying the loop in ol.reproj.Tile to include tiles in the ABORT state doesn't actually work -- that causes problems later on. I suspect that these tiles should not be disposed, or that some piece of code should refetch them...

**Comment by pjsg** [comment]
It turns out that the TileCache limit is exceeded and this disposes tiles. Curiously enough there are a bunch of tiles with negative coords in the cache. The actual number of real tiles fits within the 2k default limit. I think that trying to prevent the bad tiles from being cached would be good.

**Comment by ahocevar** [comment]
Thanks @pjsg for your bug report and investigation. Your observation that tiles in the reprojected tile cache get disposed too early is correct. It should help to give the tile caches created for projections in `ol/source/TileImage` a bigger cache size. I have created #10472 to fix that. Can you please test and verify that the fix works?

**Comment by ahocevar** [comment]
@pjsg #10478 is another attempt to fix this. Can you please test again?
