### ISSUE TITLE
Pan the map out of map's iframe stop the map move event.

### ISSUE THREAD

**Issue by gycwwf123** [openlayers/openlayers#10469]
Hi,
Recently we have updated OL from 4 to 6, then I met this issue. Please see:
https://codesandbox.io/s/interesting-snyder-u6f44
There are 3 maps for different version, if you press down the mouse left button pan the map out of it's iframe, and don't release the mouse button. For OL4, you can still pan the map but for OL5 and OL6, the map stop panning.
Any idea how to change OL5/6 to work like OL4, moving the mouse out of iframe still keep map panning?
Regards,
Gary

**Comment by gycwwf123** [comment]
Hi,

We have comment the code in OL

            if (mapBrowserEvent.type == MapBrowserEventType.POINTERDOWN) {
                const handled = this.handleDownEvent(mapBrowserEvent);
                if (handled) {
                    mapBrowserEvent.preventDefault();
                    //mapBrowserEvent.preventDefault();
                }
                this.handlingDownUpSequence = handled;
                stopEvent = this.stopDown(handled);

It seems changed the behavior to OL4, any potential issues on this?

Thanks,

Gary

**Comment by ahocevar** [comment]
The code you commented out above has been removed since the last release, see #10402. So you should be fine when you upgrade to the next release or the latest dev version (`npm install ol@dev`).
