### ISSUE TITLE
Does OpenLayers version 6.x.x only support node.js usage?

### ISSUE THREAD

**Issue by dw999** [openlayers/openlayers#10476]
Does OpenLayers version 6.x.x only support node.js usage? I write the following HTML tester for OpenLayers 6.1.1, it fails, but this tester works on OpenLayers 5.x.x. However, if I follow OpenLayers 6.x.x recommended approaching, i.e. install it via npm, it works flawlessly. So, I would like to ask this question.

      <!doctype html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Openlayers V6 Tester</title>
        <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v6.1.1/css/ol.css">
      </head>

      <body>
        <div>
          <h1>Openlayers V6 Tester</h1>

          <div id="map">
            
          </div>
        </div>

        <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v6.1.1/build/ol.js"></script>

        <script>
          var map = new Map({
            view: new View({
              center: [0, 0],
              zoom: 1
            }),
            layers: [
              new TileLayer({
                source: new OSM()
              })
            ],
            target: 'map'
          });        
        </script>
      </body>
      </html>

**Comment by mike-000** [comment]
See https://openlayers.org/en/latest/doc/quickstart.html  Note that you must size the map div for version 6.

**Comment by dw999** [comment]
Hi mike, 

Thanks for your help, I can now load up OpenStreet Map will OpenLayers 6.1.1. Now, If I like to put a marker on the map (like the code below), is there any example for it? I just can't find one on OpenLayers web site.

-----------------------------------------------------------------------------------------------
          //Set up an Style for the marker note the image used for marker
          var iconStyle = new ol.style.Style({
            image: new ol.style.Icon(/** @type {module:ol/style/Icon~Options} */ ({
              anchor: [0.5, 16],
              anchorXUnits: 'fraction',
              anchorYUnits: 'pixels',
              src: '../image/pinpoint.png'
            }))
          });
    
          //Adding a marker on the map
          var marker = new ol.Feature({
            geometry: new ol.geom.Point(
              ol.proj.fromLonLat([114.15769,22.28552])
            )
          });
  
          marker.setStyle(iconStyle);
  
          var vectorSource = new ol.source.Vector({
            features: [marker]
          });
        
          var markerVectorLayer = new ol.layer.Vector({
            source: vectorSource,
          });
  
          // add style to Vector layer style map
          map.addLayer(markerVectorLayer);  
-----------------------------------------------------------------------------------------------
