### ISSUE TITLE
Select style is not removed when using two Select interactions

### ISSUE THREAD

**Issue by bepremeg** [openlayers/openlayers#10486]
**Describe the bug**
We upgraded our application from OL 4.6.5 to 6.1.1. This was surprisingly smooth. However, we notice that selected features get the selection style when they're selected, but they don't revert to the default style when they're deselected.

**To Reproduce**
1. Add a `Select` with a custom style to a map. 
2. Remove the `Select`
3. Add another `Select` with a custom style to a map

**Expected behavior**
When a deselecting a feature (with shift-click if multiple selection is allowed or simple click if not), the feature should revert to its initial style.

**Code observations**
We were not sure if the bug was due our usage of OL or in OL itself, so we had a hard look with a debugger.

What happens is that when a feature is selected, first its original style (if any) is stored in `featureStyleAssociation_`, then the select style is set. However, this happens twice because the `addFeature_` function is called twice. As a result, the second time the select style (and not the default style) is copied to the `featureStyleAssociation_` map. 

So, when the feature is deselected, the style is "reverted" to the selection style, not the default style.

The `addFeature_` is called twice because the added event listener (`addEventListener` in the constructor or `Select`) is not unregistered.

We do call `removeInteraction` in our code and we do observe `setMap` being called with a `null` argument, but that does not appear to remove the `addFeature_` event listener.

**Comment by jahow** [comment]
Thanks for the detailed report. There are indeed two event listeners on the feature collection which never get unregistered:
https://github.com/openlayers/openlayers/blob/8125463e59c4c26184772e7c59de5b449807e732/src/ol/interaction/Select.js#L256-L257

Unregistering should be done like this:
https://github.com/openlayers/openlayers/blob/37f9a6a6e9f6f75bab4645257f69abbd45065dfd/src/ol/interaction/Modify.js#L374

I'll tag this as a bug, if anyone wants to offer a fix please do! Thanks.

**Comment by bepremeg** [comment]
I have created a pull request for this. I have no quick way of testing it, but it *looks* trivial...

**Comment by bepremeg** [comment]
https://github.com/openlayers/openlayers/pull/10490
