### ISSUE TITLE
Missing explicit 'title' attributes in layer options

### ISSUE THREAD

**Issue by pduchesne** [openlayers/openlayers#10489]
The 'title' attribute is not present in the BaseLayer constructor options, nor in its class accessors.
I understand this attribute is not part of the core OL object model, but it is a de facto necessary attribute in certain use cases (f.i. in the layer switcher), and is (IMHO) a legitimate core attribute of a layer.
The reason I consider this now necessary is that in a typescript context, as the OL types (https://www.npmjs.com/package/@types/ol) do not advertise that attribute, it is impossible to use it. 
It can be argued that this is the responsability of the OL types author, but he would probably be reluctant in advertising an attribute that's not officially part of the API (and rightfully so).

This issue has been raised once already (#9115), but closed automatically for the lack of an answer.

**Comment by jahow** [comment]
Hi,

This could be argued for other properties such as `name`, `label`... What would be considered acceptable or not then? This is IMO something to be dealt with in the types definition, e.g. by allowing unknown properties in the constructor options type.

**Comment by pduchesne** [comment]
Thank you for your answer.

My personal opinion as a developer is that the 'title' has become a de facto primary attribute of a layer, and maybe some others have too. Leaving those as undocumented attributes forces the typed Options class to accept unspecified attributes (as suggested in #9115 ; not good i think) 
, or to move such attributes in an untyped bag of 'extra' attributes (would break current implementations).
But being a user and not a developer in this case, I leave it up to the OL team and the types author (@hanreev ?) to come to an agreement.

My criteria as a user is : I need to be able to set a title while respecting the published types.

**Comment by jahow** [comment]
IMO the right solution would be to have the constructor accept a `TileOptions & {[prop: string]: any}` type.

**Comment by hanreev** [comment]
I have implemented those types in my personal project with ol v5.
Please take a look to this commit: hanreev/types-ol@4617c9d78c347170f24c4f6cf4e64e08476ef1b7

---

#### Pros:  
- We can set extra properties to constructor options
#### Cons:  
- If there are typos in the declared option, the compiler won't show us any alert

---

### Alternatives:
- [set](https://github.com/hanreev/types-ol/blob/4617c9d78c347170f24c4f6cf4e64e08476ef1b7/%40types/ol/Object.d.ts#L11)
- [setProperties](https://github.com/hanreev/types-ol/blob/4617c9d78c347170f24c4f6cf4e64e08476ef1b7/%40types/ol/Object.d.ts#L12)


I may publish those types to [@hanreev/types-ol](https://www.npmjs.com/package/@hanreev/types-ol) but not to [@types/ol](https://www.npmjs.com/package/@types/ol)
