### ISSUE TITLE
Heatmap setGradient doesn't change the gradient visually

### ISSUE THREAD

**Issue by amshel** [openlayers/openlayers#10483]
**Describe the bug**
I want to change the gradient of the Heatmap based on user input. When I call the method setGradient on the layer, the gradient is changed in the object but visually nothing happens.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/heatmap-earthquakes-q22oi'
2. Click on 'change gradient'
3. Map doesn't change but you can see the canvas gradient is different

**Expected behavior**
The layer should use the new gradient to generate the image

**Comment by amshel** [comment]
If I do:
vector.renderer_ = vector.createRenderer();
and Pan or zoom after setGradient, the heatmap use the new gradient.
But map.render() doesn't show the heatmap.
What do I miss?
Thanks for the help

**Comment by jahow** [comment]
Hi,

Thanks for the report and reproduction case. In my test something different happens: when I click on "change gradient" the heatmap layer disappears completely instead of changing visually. Panning/zooming the map makes it reappear.

This is most likely a bug related to how the webgl renderer handles a change of the provided texture. I'll tag this accordingly and try to work on this ASAP. Thanks again!

**Comment by amshel** [comment]
Hi Olivier,
yes compared to my first description I added in the code:
vector.renderer_ = vector.createRenderer();
that causes the heatmap to have the right renderer but it disappears until panning or zooming.
Greets,
marco

**Comment by fredj** [comment]
@jahow: what about
```diff
diff --git a/src/ol/layer/Heatmap.js b/src/ol/layer/Heatmap.js
index 646777a0d..eb7abdf0a 100644
--- a/src/ol/layer/Heatmap.js
+++ b/src/ol/layer/Heatmap.js
@@ -294,7 +294,9 @@ class Heatmap extends VectorLayer {
               gl_FragColor.rgb *= gl_FragColor.a;
             }`,
           uniforms: {
-            u_gradientTexture: this.gradient_
+            u_gradientTexture: function() {
+              return this.gradient_;
+            }.bind(this)
           }
         }
       ]
```

**Comment by jahow** [comment]
Looks very much like that would fix it @fredj :)

**Comment by fredj** [comment]
@amshel I've updated your code sandbox and it's now working as expected:
https://codesandbox.io/s/heatmap-earthquakes-md2ls

I've removed the `vector.renderer_ = vector.createRenderer();` line and changed changed the ol version to `6.1.1-dev.1578305259713` in `package.json`.

**Comment by amshel** [comment]
Hi @fredj and @jahow,
that was fast.
Thanks for fixing it!
