### ISSUE TITLE
VectorLayer prerender event is not being fired

### ISSUE THREAD

**Issue by bcvazquez** [openlayers/openlayers#10487]
While migrating from v5.2.0 to 6.1.1 I noticed that the `prerender` event does not get fired for VectorLayers, while `precompose` used to work fine. CodeSandbox with simple example: https://codesandbox.io/s/vectorlayertest-32l2p

**Comment by MoonE** [comment]
The `pre-/postrender` events are only fired if the source is not empty. The `renderFrame` function will return early in that case.
https://github.com/openlayers/openlayers/blob/c1c256040ea9bac4e42af383ea78682ab38e181e/src/ol/renderer/canvas/VectorLayer.js#L137-L142
The events would be fired after this:
https://github.com/openlayers/openlayers/blob/c1c256040ea9bac4e42af383ea78682ab38e181e/src/ol/renderer/canvas/VectorLayer.js#L157
