### ISSUE TITLE
Can the "Modify" interaction pass individual features to event callbacks?

### ISSUE THREAD

**Issue by zachsa** [openlayers/openlayers#10491]
I see in the docs that I can create a `Modify` interaction specific to a collection of features, or a source:

This works
```
new Modify({
    source: layer.getSource()
})

this.modify.on('modifyend', ev => {
    window.ev = ev
    // Then I look at the `ev`
})
```

However `ev.features` is a collection with every feature in the layer. I saw that I can create the Modify with a collection of features:

```
new Modify({
    features: new Collection(layer.getSource().getFeatures())
})

this.modify.on('modifyend', ev => {
    window.ev = ev
})
```

But similarly, `ev.features` gives me all the features in the layer. As far as I can tell, there is no way to explicitly get a single feature from the event passed to the callback. Is that correct?

Since event handles are registered per feature in the second example, would it be possible to get a single feature - the one targeted by the event? Otherwise I need to loop through all the features which is inefficient for lots of point data.

I'm using OpenLayers 6.1.1

**Comment by csdillard** [comment]
Just wanted to chime in to say that this functionality (including the feature being modified in the `ModifyEvent`) would be very helpful for me, too. While there are workarounds, they're not ideal. (One could redesign the map to use a `Select` interaction with only single-select allowed, and then examine the `Select`'s `features`.  Another possibility is to manually call `forEachFeatureAtPixel`.) The `RBush` already knows the feature in the `SegmentData`, so why not just include it?
