### ISSUE TITLE
A bug when drawing texts with different textBaseline in a VectorLayer

### ISSUE THREAD

**Issue by LarryHuang77** [openlayers/openlayers#10497]
**Describe the bug**
bug pic:
![bug](https://user-images.githubusercontent.com/48011343/72032026-3196c080-32c9-11ea-8162-8ca6015657ec.JPG)
fixed pic:
![fixed](https://user-images.githubusercontent.com/48011343/72032037-38253800-32c9-11ea-9bab-a64336762c92.JPG)

**To Reproduce**
code:
function createText(text, signX, signY, textAlign, textBaseline) {
    return new Text({
        text: text,
        placement: "point",
        offsetX: signX * 15,
        offsetY: signY * 12,
        textAlign: textAlign,
        textBaseline: textBaseline,
        backgroundStroke: new Stroke({width: 1}),
        padding: [2, 5, 2, 5],
    });
}

let feature = new Feature(new Point([0, 0]));
let label1 = new Feature(new Point([0, 0]));
label1.setStyle(new Style({text: createText("top right", 1, -1, "left", "bottom")}));
let label2 = new Feature(new Point([0, 0]));
label2.setStyle(new Style({text: createText("bottom right", 1, 1, "left", "top")}));
let label3 = new Feature(new Point([0, 0]));
label3.setStyle(new Style({text: createText("bottom left", -1, 1, "right", "top")}));
let label4 = new Feature(new Point([0, 0]));
label4.setStyle(new Style({text: createText("top left", -1, -1, "right", "bottom")}));

new Map({
    target: 'map-container',
    view: new View({center: [0, 0], zoom: 1}),
    layers: [
        new TileLayer({source: new OSM()}),
        new VectorLayer({source: new VectorSource({features: [feature, label1, label2, label3, label4]})}),
    ]
});

**To Fix**
ol/render/canvas/TextBuilder.js
line 464:
this.textKey_ = textState.font + textState.scale + (textState.textAlign || '?');
should add textState.textBaseline into this.textKey_ as below:
this.textKey_ = textState.font + textState.scale + (textState.textAlign || '?') + (textState.textBaseline || '?');

**Comment by ahocevar** [comment]
Good find, thanks for reporting this! Would you be able to provide a pull request with your suggested fix?

**Comment by gazza0** [comment]
Hi @ahocevar 
@LarryHuang77  has indicated that he's having access problem with github, i have obtained his verbel consent and created the pull request on his behalf

**Comment by ahocevar** [comment]
Fixed with #10498
