### ISSUE TITLE
Is it possible to focus the parent window onclick of child window using javascript?

### ISSUE THREAD

**Issue by ramanjiram** [openlayers/openlayers#10492]
I need on click of button in child window parent window needs to be focused and child window go to background of parent window. I tried with below options but its didn't work as expected. Any suggestions greatly appreciated.

I tried below possible ways but those are not working  : 
Window.blur();
Window.focus();
Window.opener.focus();

**Comment by ahocevar** [comment]
This is not an OpenLayers specific question. Closing
