### ISSUE TITLE
Flag constrainCenterOnly seems to be missing

### ISSUE THREAD

**Issue by fgubler** [openlayers/openlayers#10506]
In the upgrade notes to version 6 it is written that:

> The view extent option now applies to the whole viewport
Previously, this options only constrained the view center. This behaviour can still be obtained by specifying constrainCenterOnly in the view options.

However, I cannot find a place to set the constrainCenterOnly flag: It is not part of the ViewOptions interface and according to my webstorm-search, the only place it is ever mentioned in your code-base are the aforementioned upgrade notes.

Am I missing something? I would like to get the previous behavior again...

**Comment by fgubler** [comment]
Hmm it might only be a typo in the upgrade notes: a flag of the name "constrainOnlyCenter" instead of "constrainCenterOnly" does seem to exist. Will investigate further

**Comment by fredj** [comment]
Thanks for reporting this @fgubler ! Would you be able to provide a pull request to change `constrainCenterOnly` to `constrainOnlyCenter` in `changelog/upgrade-notes.md` ?

**Comment by fgubler** [comment]
Sure: will provide it shortly.
