### ISSUE TITLE
Multiple select interactions on same features corrupt style

### ISSUE THREAD

**Issue by bepremeg** [openlayers/openlayers#10501]
**Describe the bug**
It is not possible to have more than one select interaction activated on the same set of features. The select style is mistaken for the default style with the second interaction.

This has the same root cause as https://github.com/openlayers/openlayers/issues/10486, but is not solved by that fix.

**To Reproduce**
Have 2 select interactions on the same layer. E.g. one for click (`condition: ol.events.condition.click`) and one for hover (`condition: ol.events.condition.pointerMove`).

**Expected behavior**
When the pointer moves over the feature, it should get the selected style and when the pointer moves away, it should acquire the unselected style again.

**Comment by bepremeg** [comment]
One way to fix this, would be to keep a counter for the number of active selections in the feature itself. When a select style is applied, this counter would be applied. Only when the counter is 0 would the style be copied to the `featureStyleAssociation_` map.
When a feature is no longer selected by one interaction, the counter would be decreased and the regular style would be applied when the counter would reach 0. After which the counter would be erased from the feature to leave the feature as it was before it was selected.

And to go one step further, it would be also be possible to drop the `featureStyleAssociation_` map and store the regular style in the feature itself. In fact, this is necessary as otherwise the selections and deselections would have to happen strictly in reverse order (at least the first interaction to select should be the last one to deselect).

The drawback of this approach clearly is polluting the feature with fairly arbitrary keys and making sure there is no collision.

Would you accept a PR along these lines?

**Comment by bepremeg** [comment]
Another option is maintaining the `featureStyleAssociation_` in `Map`. Would that be a better approach?

**Comment by michalzielanski** [comment]
The issue has been occurring since version 6.0.0 (in 6.0.0-beta.15 works good). It began by removing the select interaction (PR #9961). Then the interaction was reverted (PR #10003) but not in full. Commit acac7a9 was not restored, and commit 2ccaed0 was added instead.

I think setting style directly in the feature through interaction is a bad idea and it breaks a lot of existing code. The interaction should not interfere with the feature in this way.

Rolling back changes from commits acac7a9 and 2ccaed0 would restore the previous interaction behavior.

**Comment by michalzielanski** [comment]
Example: https://codesandbox.io/s/simple-pyb2o

**Comment by ahocevar** [comment]
I don't think it is necessary to use two select interaction for the hover/click use case. See https://codesandbox.io/s/simple-cnbti that does the same with just one Select interaction, and works.

**Comment by bepremeg** [comment]
Sure, it may often not be necessary. 

In our case,however,  we're writing a framework on top of OpenLayers.  Depending on some dynamic settings, either one, both or none of hover/click may be required.

It is much simpler if those interactions can be regarded as distinct. Also, even if it *can* work with one, it *should* also work with distinct interactions. In practice, a map has many simultaneous interactions anyway.

**Comment by michalzielanski** [comment]
It's like @bepremeg wrote. The use of two separate interactions gives great flexibility, greater readability and easier code maintenance.
I have a general map component and activates individual interactions depending on where the map is used. The use of one interaction in my case is impossible, the code would be very difficult to maintain and further develop.

In addition, continuous setting/deleting style directly in the feature causes unnecessary generation of "change" events.
