### ISSUE TITLE
MultiPolygons don't display on map when loading mapbox vector tile with MVT format which created with ol.Feature rather than RenderFeature

### ISSUE THREAD

**Issue by heavis** [openlayers/openlayers#10500]
I use MVT with ol.Feature to load mapbox vector tile including some polygon or multiploygon geometries, but some multiploygons failed render on map.
![有问题](https://user-images.githubusercontent.com/8612147/72131064-2f5e6000-33b6-11ea-8b89-b4ced20c93aa.png)
Above picture is the render result with ol.Feature class, some multiplygon geometries don't display.
![没问题](https://user-images.githubusercontent.com/8612147/72131286-bdd2e180-33b6-11ea-848c-88c2c9cf471b.png)

Above picture is the render result with ol.RenderFeature class, all geometries display properly.

ol version is 5.1.3

**Comment by ahocevar** [comment]
Can you please try the latest 6.x version and see if the issue is still present?

**Comment by heavis** [comment]
> Can you please try the latest 6.x version and see if the issue is still present?

I have tried the lastest version 6.1.1, but this problem still exists.
