### ISSUE TITLE
Blend modes example is broken

### ISSUE THREAD

**Issue by oeway** [openlayers/openlayers#10505]
I just noticed that the Blend Modes example (https://openlayers.org/en/latest/examples/blend-modes.html) on the website is not working. 

![Screen Shot 2020-01-10 at 3 17 08 PM](https://user-images.githubusercontent.com/478667/72159268-4902a600-33bc-11ea-96d1-509d5ca1acfb.png)

No map shown on the canvas and there is an error in the console:
```
blend-modes.js:16 Uncaught TypeError: c.a is not a constructor
    at Module.235 (blend-modes.js:16)
    at a (bootstrap:79)
    at i (bootstrap:45)
    at Array.e [as push] (bootstrap:32)
    at blend-modes.js:1
```

**Comment by mike-000** [comment]
Somehow an old example has found its way into the latest directory. The last working example is https://openlayers.org/en/v5.3.0/examples/blend-modes.html  It was removed from version 6 as it cannot work unless layers use a single canvas.
