### ISSUE TITLE
Image quality degrades at rotation with 90,180 or 270 degrees

### ISSUE THREAD

**Issue by danzaharescu** [openlayers/openlayers#10503]
**Describe the bug**
If the View has the rotation set to Math.PI / 2 or Math.PI or 3 * Math.PI / 2, then apparently the quality of the image suffers (depending on image and/or image resolution, either the rendering becomes blurred - as in the attached picture, either it becomes aliased - text and lines broken) . Dragging the edge of the image (for example, the separator in the codesandbox) sometimes temporarily fixes the image, but additional dragging make the image again degraded and so on. I must mention, the quality is already much better than older OpenLayers versions (example, 4.*). The degradation appearing during the rotation leads to the image having the same rendering quality as in 4.*

**To Reproduce**
I believe the following screenshot will make it clear (I have used a rotation of 2 * Math.PI - is ALMOST EQUIVALENT TO 0, but not exactly, apparently, just to better view the differences):
![rotation](https://user-images.githubusercontent.com/17156861/72151867-105dcf00-33b2-11ea-9dc7-7154c8ecfb4f.png)

Please take into account that in other cases the image may become 'aliased' (text and lines broken)

3. See error

**Expected behavior**
The same quality image should be observable at any rotation.
As a side note, I am thinking of the problem being in the area that Math.PI is not exactly the real PI (that cannot be represented). Therefore, I am thinking that maybe supporting rotations in degrees could be helpful.

**Comment by mike-000** [comment]
Possibly browser specific, I cannot see any difference between 0 and 2*Math.PI.  However I noticed that when rotation is set to 2*Math.PI clicking the reset north button has no effect unless `duration: 0` is set in the Rotate control options.

**Comment by mike-000** [comment]
I can see the effect when resizing the map.  It is because **any** non-zero rotation uses a canvas larger the the viewport (a square with sides sqrt(2) times the largest dimension of the viewport) which is centered on the center of the viewport and rotated as necessary.  Making a special case for non-oblique rotations would need a lot of extra extra code for relatively rare scenarios.

**Comment by danzaharescu** [comment]
I agree, that if the return of investment for the fix is too low, it does not make much sense to implement it. The problem I noticed initially, was that repeated rotations by adding Math.PI/2 lead to a never recovering image (sometimes problem is reproducible with drag, but sometimes even without). However, the fix was to set the rotation again to 0 instead of 4 * Math.PI/2 which greatly decreases the severity of the problem. Maybe it worth thinking in the future of at least better supporting the 90,180,270 degrees somehow, could be that supporting these (with the idea in mind that these cases may be more frequently encountered than a random rotation) may be easier than a generic fix.     From my point of view, the rendering is mainly OK now, and for sure much better than in 4.*.* version ! Thanks.
