### ISSUE TITLE
translate interaction not show grab cursor

### ISSUE THREAD

**Issue by tltk90** [openlayers/openlayers#10524]
**Describe the bug**
When add more then one `Translate` interaction only the first one get the `grab` cursor.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-1cxqup?embed=1&hideExplorer=1
2. Click on 
   1. `add Feature` button twice
   2. hover the two feature
3. See error only the first feature get the `grab` cursor.

**Expected behavior**
all the features that has a Translate interaction get `grab` cursor when hover over them.

**Comment by mike-000** [comment]
It might be simpler to use a single Translate in conjunction with a Select interaction similar to the example https://openlayers.org/en/latest/examples/translate-features.html but use pointermove for the Select condition.  If you don't want to pick up both features as you drag one over another you would need to ignore dragging in the Select https://codesandbox.io/s/translate-features-5f9mq

**Comment by tltk90** [comment]
it's great. thx.
