### ISSUE TITLE
click marker, marker disappear

### ISSUE THREAD

**Issue by CalvinP-Cai** [openlayers/openlayers#10528]
I used version 6.1.1 to add a  vector layer. when i click the feature(Vector layer), something strange happened: the feature disappeared.When I switched to version 4.6.5, it didn`t happen again.
normal picture:
![image](https://user-images.githubusercontent.com/37281618/72306025-b0687080-36b0-11ea-8203-203a08a3cb3f.png)
issue picture:
![image](https://user-images.githubusercontent.com/37281618/72306065-d55ce380-36b0-11ea-8f11-4c99e1a9a7c6.png)

**Comment by Razi91** [comment]
Do you have Select interaction added? Or any other interaction?

**Comment by CalvinP-Cai** [comment]
I have add a city boundary, that used Select interaction. But I cancel the listen event. I try not to add that, the previous phenomenon is gone.  Is there any internal optimization due to the version upgrade?
code is as follow:
 var areaLineLayer = new ol.layer.Vector({
               title: "区域线图层",
               source: new ol.source.Vector({
                   url: url,
                   format: new ol.format.GeoJSON()
               }),
               style: areaLineStyle
           })

           var listenerKey = areaLineLayer.getSource().on('change', function () {
               if (areaLineLayer.getSource().getState() === 'ready') {    // 判定是否加载完成
                   areaLineLayer.getSource().un(listenerKey); // 注销监听器
               }
           });

           map.addLayer(areaLineLayer);

           var select = new ol.interaction.Select({
               style: areaLineStyle,
               filter: function (feature, layer) {
                   return layer != areaLineLayer;
               }
           });

           map.addInteraction(select);

           map.on('pointermove', function (evt) {
               map.getTargetElement().style.cursor = map.hasFeatureAtPixel(evt.pixel, function (layer) {
                   return layer != areaLineLayer;
               }) ? 'pointer' : '';
           });

Is there a problem?

**Comment by CalvinP-Cai** [comment]
> Do you have Select interaction added? Or any other interaction?

I have add a city boundary, that used Select interaction. But I cancel the listen event. I try not to add that, the previous phenomenon is gone. Is there any internal optimization due to the version upgrade?
code is as follow:
var areaLineLayer = new ol.layer.Vector({
title: "区域线图层",
source: new ol.source.Vector({
url: url,
format: new ol.format.GeoJSON()
}),
style: areaLineStyle
})

       var listenerKey = areaLineLayer.getSource().on('change', function () {
           if (areaLineLayer.getSource().getState() === 'ready') {    // 判定是否加载完成
               areaLineLayer.getSource().un(listenerKey); // 注销监听器
           }
       });

       map.addLayer(areaLineLayer);

       var select = new ol.interaction.Select({
           style: areaLineStyle,
           filter: function (feature, layer) {
               return layer != areaLineLayer;
           }
       });

       map.addInteraction(select);

       map.on('pointermove', function (evt) {
           map.getTargetElement().style.cursor = map.hasFeatureAtPixel(evt.pixel, function (layer) {
               return layer != areaLineLayer;
           }) ? 'pointer' : '';
       });
Is there a problem?

**Comment by Razi91** [comment]
Check console for errors, maybe your style (`areaLineStyle`) has errors.

In `filter`, shouldn't there be `return layer == areaLineLayer;`?
