### ISSUE TITLE
Hability to change specific ImageTile image src without memory leak

### ISSUE THREAD

**Issue by diogolessa** [openlayers/openlayers#10533]
Hi everyone,

First of all, thanks for the amazing lib. It is really nice and useful.

**The problem**
My scenario is basically that: I have a map which uses a TileSource - could it be TileJSON, for example - and I need to often update specific tiles on the screen based on a message sent through websocket: _"Hey, please update the tile(s) that is over this extent/coordinate. Thanks."_

I haven't find a acceptable solution for that, since the tiles are present inside tileCache.entries_, which is a private variable.

Even knowing that, I tried to used it, but I am facing **memory leak**. Little by little, the memory footprint of the application keeps growing. Based on the research I've made, it could be by the fact I keep referencing the tileCache entries, and hence the garbage collector is not able to clear things properly. But this is just a guess.

I've tried several ways to make this work, but I always run into **memory leak**.

Here is a pen so you can see the behaviour: https://codepen.io/lessadiogo/pen/vYEaxNa
Simply open the chrome task manager and observe the Subframe from cdpn.io. It won't stop increasing.

**The solution I would like**
It would be nice to have a proper way to access the ImageTile instances and call a update method, or simply change the image source of those we'd like to update. Mainly giving attention to the memory leak.

Thanks in advance,

Diogo

**Comment by ahocevar** [comment]
The API way to load new images for all tiles would be `tileSource.refresh()`. Do not keep references to tiles to avoid memory leaks. I would not recommend to update only a single tile, because you'll have to re-render the whole viewport anyway, and the browser cache is there to avoid fetching unchanged tiles from the server if headers are set properly.

**Comment by diogolessa** [comment]
I see your point, though it makes sense, I ran into memory leak using the `tileSource.refresh()` method. Here is a new fiddle: https://codepen.io/lessadiogo/pen/jOEpQwX

I call the `tileSource.refresh()` for each 3 seconds. Inside the `tileLoadFunction` I am using a range of 30 different images and calling them randomly. In few calls to the refresh method, all of them stay on browser cache, but the memory leak still persists, actually, even stronger than before.

Is it expected?

Thanks,

**Comment by ahocevar** [comment]
Looking at your code, a potential cause for a memory leak could be the onerror listener that you do not unregister.

**Comment by diogolessa** [comment]
Hmm, thanks for the catch. I'll do another test clearing these events.

**Comment by diogolessa** [comment]
Yeah, still happens... Even not listening to the onerror event, the leak persists...

It started with around 50mb, and in couple of minutes, it grew up to 298mb, and did not go down.
![Screen Shot 2020-01-16 at 08 51 22](https://user-images.githubusercontent.com/5168901/72522826-4d581480-383d-11ea-86b3-c5a66991dc13.png)

I don't see much what can be leading to it in my code now.. Is it possible to be something with openlayers? Sorry to bother..

Thanks
