### ISSUE TITLE
Get coord of feature text

### ISSUE THREAD

**Issue by unstoppablecarl** [openlayers/openlayers#10536]
working with OL  6.1.1

I would like to render a popup similar to this example https://openlayers.org/en/latest/examples/popup.html?q=vector that aligns with the center of the text of a feature. I have found examples that place the popup at the position of the mouse or click but not aligned to the feature label text.

I have not been able to find a way to get the label text coords and I have not been able to find any documentation explaining how this text is positioned either.

**Comment by mike-000** [comment]
Set the `offset` option of the Overlay to the `offsetX` and `offsetY` values of the feature's text style https://codesandbox.io/s/icon-bk3rb

**Comment by unstoppablecarl** [comment]
I am working with features that are polygons of country borders not single points. Like this example https://openlayers.org/en/latest/examples/hitdetect-vector.html?q=feature

**Comment by mike-000** [comment]
For polygons the labels are centered at the interior point, so use `feature.getGeometry().getInteriorPoint()` to position the overlay.  If you click on a MultiPolygon you would first need to use `feature.getGeometry().getPolygons()` then test each polygon with `intersectsCoordinate` to determine which part of the MutliPolygon you clicked.

**Comment by unstoppablecarl** [comment]
That appears to work for single polygon features like you said. For multi-polygon features the label is only displaying in one place. How can I determine that location?

**Comment by mike-000** [comment]
Labels may not be displayed in every polygon even for single polygon features, but there can be more than one for multi-polygons

![image](https://user-images.githubusercontent.com/49240900/72567439-cd1dc780-38ad-11ea-9d33-d5957c955c53.png)

**Comment by unstoppablecarl** [comment]
Ah that makes sense. Thanks.
