### ISSUE TITLE
Help: TileImage's tileUrlFunction not work when I change V5 to V6. 

### ISSUE THREAD

**Issue by liguoyan** [openlayers/openlayers#10535]
**Describe the bug**
when I update V5 to V6, it's not show view , and no bugs report.  when I follow code , found the
tileUrlFunction dosen't work,  my map is Baidu Map.
**To Reproduce**
`// 百度坐标系
		proj4.defs(
			'BD09',
			'+proj=merc +a=6378206 +b=6356584.314245179 +lat_ts=0.0 +lon_0=0.0 +x_0=0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs');
		register(proj4);
		let projection = projGet('BD09');

		// 分辨率
		let resolutions = [];
		for (let i = 0; i < 19; i++) {
			resolutions[i] = Math.pow(2, 18 - i);
		}

		// 中心点坐标
		let center = null;
		if (options.center) {
			center = BaiduMap.transformCoord(options.center);
		}

		// 地图边界
		let extent = null;
		if (options.extent) {
			extent = BaiduMap.transformExtent(options.extent);
		}
		let mapkeys = [];
		let maplayers = [];

		let Creatlayer = (TitUrl, filter = options.tileImageFilter) =>{
			let source = new TileImage({
				crossOrigin: 'anonymous',
				projection: projection,
				tilePixelRatio: 2,
				tileGrid: new TileGrid({
					origin: [0, 0],
					resolutions: resolutions,
					extent: extent
				}),
				tileUrlFunction: function(tileCoord) {
					if (!tileCoord) {
						return '';
					}

					let z = tileCoord[0];
					let x = tileCoord[1];
					let y = tileCoord[2];

					let tileUrl = TitUrl.replace('{z}', z).replace('{x}', x).replace('{y}', y);

					return tileUrl;
				}
			});

			// 图片变色效果
			if (filter) {
				source.setTileLoadFunction(function(imageTile, src) {
					Map.tileImageFilterFunction(imageTile, src, filter);
				});
			}
			// 地图图层
			let mapLayer = new Tile({
				source: source
			});
		`

I want to know how to put it right， thanks!~

**Comment by liguoyan** [comment]
I want to make sure this problem can be solved~~~

**Comment by ahocevar** [comment]
The internal tile coordinates have changed. You have to update your code according to the [release notes](https://github.com/openlayers/openlayers/releases/tag/v6.0.0). In particular, you will have to change the value of the `{y}` placeholder of your tile url:
```js
				let z = tileCoord[0];
				let x = tileCoord[1];
				let y = tileCoord[2] + 1; // or just `tileCoord[2]`, or  `tileCoord[2] - 1` - please experiment
```

**Comment by liguoyan** [comment]
I'm so sorry,  the code I show is old. I know what you say... my code like this :
`let z = tileCoord[0];
let x = tileCoord[1];
let y = tileCoord[2];`
it dosen't work...  TileUrlFunction can't work and Code does not enter this method。。

**Comment by liguoyan** [comment]
I can't follow it ~

**Comment by MagnetLin** [comment]
> The internal tile coordinates have changed. You have to update your code according to the [release notes](https://github.com/openlayers/openlayers/releases/tag/v6.0.0). In particular, you will have to change the value of the `{y}` placeholder of your tile url:
> 
> 内部瓦片坐标已经改变。 您必须根据发行说明更新代码。 特别是，你必须改变你的平铺网址的{ y }占位符的值:
> 
> ```js
> let z = tileCoord[0];
> let x = tileCoord[1];
> let y = tileCoord[2] + 1; // or just `tileCoord[2]`, or  `tileCoord[2] - 1` - please experiment
> ```

Thank you！

**Comment by blissvisitor** [comment]
who know how to resolve it?
