### ISSUE TITLE
KML features flicker when decluttering is enabled

### ISSUE THREAD

**Issue by welltothebone** [openlayers/openlayers#10540]
**Describe the bug**
KML features and labels flicker when decluttering is enabled and are not always visible. 

**To Reproduce**
1. Add KML layer to the map (Use attached KML sample)
2. Zoom into the layer area 
3. KML features flicker and are not always visible

**Expected behavior**
KML features do not flicker and are visible

Here is a sample:
`import 'ol/ol.css';
import {Map, View} from 'ol';
import {Tile as TileLayer, Vector as VectorLayer} from 'ol/layer.js';
import {OSM, Vector as VectorSource} from 'ol/source.js';
import KML from 'ol/format/KML.js';

let vectorLayer = new VectorLayer({
    source: new VectorSource({
        url: 'sample.kml',
        format: new KML()
    }),
    declutter: true
});

const map = new Map({
    target: 'map',
    layers: [
        new TileLayer({
            source: new OSM()
        }),
        vectorLayer
    ],
    view: new View({
        center: [0, 0],
        zoom: 0
    })
});`

[sample.zip](https://github.com/openlayers/openlayers/files/4076957/sample.zip)

**Comment by ahocevar** [comment]
The fact that not all points and texts are rendered is expected. That's the point of decluttering. Do you see the flickering during panning and zooming? If so, that's a flaw in our decluttering algorithm.

**Comment by mike-000** [comment]
It can also be seen in https://openlayers.org/en/latest/examples/kml.html if decluttering is enabled.  For many Point features the style function returns an array of styles which appear to be decluttering each other.  As well as some flickering icons during panning and zooming there are many labels without icons.

**Comment by welltothebone** [comment]
Yes, i meant the flickering during panning or zooming.
