### ISSUE TITLE
Smooth rendering ol.style.Text stroke

### ISSUE THREAD

**Issue by mattti-post** [openlayers/openlayers#10555]
**Describe the bug**
The backgroundstroke in ol.style.Text is rendered smoothed, i.e with no sharp edges.

**To Reproduce**
https://codepen.io/mattti/pen/OJPagag
It is specially visible when zooming. Sometimes the edges are sharp, on different zoom level it is smoothed.

**Expected behavior**
I would expect the edges to be sharp without smoothing.

I tried to apply this suggestions but to no avail (I had to replace the "precompose" with "prerender" because the context is missing in precompose handler):
https://stackoverflow.com/questions/35875270/turn-off-image-smoothing-in-openlayers-3

**Comment by mike-000** [comment]
In OpenLayers 6 each layer has a canvas and you need disable smoothing in `vectorLayer.on('prerender', 
 ... )`;

**Comment by mattti-post** [comment]
Hi mike,

I did as you suggested, but it is not working. You can check the codepen.

Thanks.

**Comment by mike-000** [comment]
The difference can be seen when zooming in on a raster https://codesandbox.io/s/side-by-side-w3hdq  The difference may not be so apparent when rendering vectors.

**Comment by mattti-post** [comment]
Yes I see the difference on high zoom level.

But the text backgroundstroke in my example stays visibly smoothed in any zoom level. Its edges randomly changes from smoothed to sharp by zooming. It does not look good. 

I changed the width of the circle strokes to 1 so that you can see the difference. The stroke of the circles is perfectly sharp and nice at any zoom level and without setting the smoothing variables to false.

**Comment by mike-000** [comment]
Disabling smoothing during rendering only works if the output is direct to the canvas.  In some cases an intermediate canvas is used (for example for reprojection) and labels are cached, but this recent change #10527 will be in the next release.

**Comment by mattti-post** [comment]
It is not the problem only during rendering. The stroke remains smoothed after zooming is complete. Sometimes it remains all sharp. Sometimes only two sides of the textbox are sharp and other sides are smoothed.

**Comment by mike-000** [comment]
Here is your code with the latest dev version https://codesandbox.io/s/simple-blp20 there seems to be a new problem

**Comment by mattti-post** [comment]
Yes, I tried to fiddle with it, comment style attributes and some lines of code but the green box still persists from initial zoom after fit was done. 

Is that the latest dev version including some changes made due to my issue or is it just the coincidence?

**Comment by mike-000** [comment]
No changes related to your issue, but it seems a new problem has been introduced somewhere.

**Comment by ahocevar** [comment]
The new problem might be related to #10527.

**Comment by ahocevar** [comment]
#10574 fixes the [new problem](https://github.com/openlayers/openlayers/issues/10555#issuecomment-576671176).
