### ISSUE TITLE
Would WebGLLayerRenderer implement getDataAtPixel function ?

### ISSUE THREAD

**Issue by changqingom** [openlayers/openlayers#10552]
hi

i use heatmap layer in my map then i found an error  `Unimplemented abstract method` when i excute  `map.forEachLayerAtPixel` .

i found the reason is `WebGLLayerRenderer` not implement `getDataAtPixel` .

Would the WebGLLayerRenderer implement function getDataAtPixel ?

**Comment by jahow** [comment]
https://github.com/openlayers/openlayers/pull/10101 implements this, which version of OL are you using?

**Comment by changqingom** [comment]
version is  `6.1.1`

i saw this error : [https://openlayers.org/en/v6.1.1/doc/errors/#66](https://openlayers.org/en/v6.1.1/doc/errors/#66)



![image](https://user-images.githubusercontent.com/33093289/72713177-8a0e6d80-3ba7-11ea-8898-4cf0fd8cd7e5.png)
