### ISSUE TITLE
Method ol.View.fit(ol.Extent) is ignoring the ol.style.Text in vector layer.

### ISSUE THREAD

**Issue by mattti-post** [openlayers/openlayers#10556]
**Describe the bug**
Method ol.View.fit(ol.Extent) is ignoring the ol.style.Text in vector layer.

**To Reproduce**
https://codepen.io/mattti/pen/OJPagag
The behavior is obvious when you set high values in padding or offsetY properties of ol.style.Text.

**Expected behavior**
I would expect the vectorLayer.getSource().getExtent() or ol.View.fit() methods to take into account the text style including padding and offsets.

**Comment by mike-000** [comment]
That is correct, the extent of a feature is the extent of it's geometry.

**Comment by mattti-post** [comment]
Closing this issue in favor of the issue #10554

**Comment by mattti-post** [comment]
Closing this issue in favor of the issue #10554
