### ISSUE TITLE
Layer Clipping example is not working

### ISSUE THREAD

**Issue by microspace** [openlayers/openlayers#10569]
I'm searching for example to render glsl shaders ontop of map. I found this [example ](https://openlayers.org/en/latest/examples/layer-clipping-webgl.html), but it is not working.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/layer-clipping-webgl.html
2. See error (no map)

**found bugs:**

1. change `pre/postcompose` to `pre/postrender`

**Comment by mike-000** [comment]
Similar issue to #10505  The example shouldn't be in the latest folder as ol/WebGLMap has been deprecated.

**Comment by microspace** [comment]
Yes, thank you, @mike-000, I'm downgrading to v5.3.0. 
But still, could you please give advice how to make this example work with v6.1.0?
I got stuck here on trying to return webgl context from current context: 

    osm.on('prerender', function (event) {
      var context = event.context;
      var gl = getContext(context.canvas)`
      ...

**Comment by mike-000** [comment]
ol/WebGLMap has been removed so it won't with version 6.  See **Drop of support for the experimental WebGL renderer**  in the upgrade notes https://github.com/openlayers/openlayers/releases/tag/v6.0.0

**Comment by microspace** [comment]
Is there a way to plot custom shaders on the maps with new `WebGLHelper` ?

**Comment by jahow** [comment]
Hi @microspace, what you could do is use a post processing pass on a webgl layer to exclude a part of the final render, like the layer clipping example used to do. You can take a look at the [HeatmapLayer](https://github.com/openlayers/openlayers/blob/master/src/ol/layer/Heatmap.js) class which uses custom shaders.

The webgl points layer could also offer the possibility to add custom post processing shaders, IMO that would make sense but it's not the case yet.

**Comment by microspace** [comment]
Hi @jahow thank you for pointing to HeatmapLayer!
