### ISSUE TITLE
Visual artefacts at tile junctions in OL6

### ISSUE THREAD

**Issue by crubier** [openlayers/openlayers#10568]
## Description

In OL6 there are artifacts between tiles when fully zoomed in. This is visible on all image tiles. This problem did not exist in OL5.

![Screenshot 2020-01-24 at 10 02 54](https://user-images.githubusercontent.com/2954572/73060923-d64ffb00-3e90-11ea-8314-5377a0c11084.jpg)

## Reproduction

1. Go to https://openlayers.org/en/latest/examples/stamen.html
2. Zoom in to the maximum
3. Pan the map until you find a seam between tiles

## Expected behavior

The expected behavior is the one in OL5: no visible seams between tiles, even when fully zoomed in with a resolution << 1.

Example:

Zoomify layer in OL5, correct:

![Screenshot 2020-01-24 at 10 07 00](https://user-images.githubusercontent.com/2954572/73061112-4e1e2580-3e91-11ea-9530-6ff838bd6415.jpg)

Same zoomify layer in OL6, problem:

![Screenshot 2020-01-24 at 10 06 47](https://user-images.githubusercontent.com/2954572/73061132-570ef700-3e91-11ea-9aba-1106f8930863.jpg)

**Comment by ahocevar** [comment]
This artifact comes from the image smoothing built into the canvas 2d renderer. You can disable that by configuring a prerender event for the layer, like shown in https://codesandbox.io/s/stamen-7lbfn. At the very minimum, what you have to do is
```js
layer.on('prerender', function(e) {
  e.context.imageSmoothingEnabled = false;
});
```

**Comment by crubier** [comment]
The interesting thing is that the artefact did not exist in OL5, the tile junction was smoothed then.

The solution you suggest is not adapted to my use case because it want smoothing at high zoom levels. Pixelating is not an option for us. When zoomed in, your solution gives this result:

![Screenshot 2020-01-24 at 15 52 11](https://user-images.githubusercontent.com/2954572/73082545-98b79600-3ec1-11ea-9d0a-3ec998cff904.jpg)

In my application, I apply post render filters to sharpen the image. So the pixels would be sharpened as soon as the resolution gets under 1, which is not acceptable for us.

Again, the main point here is that this is a regression from OL5, so there might be an easy fix somewhere...

**Comment by ahocevar** [comment]
In version 5, tile rendering was done with a completely different technique. It first rendered all tiles to a canvas at the tile resolution, and then rendered that canvas transformed to the output canvas. That method had a higher memory footprint and lacked performance on large viewports. So no, there is no easy fix.

**Comment by ahocevar** [comment]
A workaround would be to use a raster source with your tile source as input source.

**Comment by crubier** [comment]
Yes it makes sense, I suspected something like this was going on under the hood.
