### ISSUE TITLE
[Question] Can I merge two layers into one layer?

### ISSUE THREAD

**Issue by KRMKGOLD** [openlayers/openlayers#10567]
Let me explain with an example.
I have two image layer. Like this.

```js
var layerA = new ImageLayer({
  // ...
});
    
var layerB = new ImageLayer({
  // ...
});
```

And I want to merge this layers.

```js
var layerC = layerA + layerB // like this, not real.
```

Can I get merged layer like `layerC`?

**Comment by sbrunner** [comment]
Shouldn't you use a LayerGroup?
https://openlayers.org/en/latest/apidoc/module-ol_layer_Group-LayerGroup.html

**Comment by KRMKGOLD** [comment]
@sbrunner LayerGroup can casting Layer?

**Comment by sbrunner** [comment]
I don't know what you want to say with casting...
A layer group will let you to organize your layers as a tree and provide some operations on the tree.

**Comment by KRMKGOLD** [comment]
I don't want LayerGroup.
I want to combine the two layers into one layer.

**Comment by ThomasG77** [comment]
From my understanding, you should use raster source e.g https://openlayers.org/en/latest/examples/raster.html (demo broken due to Bing Maps API limit on official site but fork into Codesandbox and change to use your API)

**Comment by KRMKGOLD** [comment]
Raster source is not the way I want it. I want to combine two layers into one. I want to combine two layers to create one layer object. no LayerGroup...
