### ISSUE TITLE
Very slow performance with overlays/markers

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#10561]
**Describe the bug**
I want to use angular component with html template as overlay/marker on map. When I use 1000 overlays and more, performance is very slow. You can try it on example below, e.g. try to move map and you will see lags when you moving map (it's almost not possible to move map). 
Change FOR loop from 1000 iterations to 10 or 100 and then try to move map, you will see no lags. 

There is very easy html element used in overlay in the example below just for demo purposes but I use a complex ones in my app.
Is there any other way to use own html as map marker with better performance? I would need to display even more than 1000 markers.

**To Reproduce**
https://jsfiddle.net/pk7rq09t/

**Expected behavior**
Smooth working with map as map moving etc.

**Comment by ahocevar** [comment]
Overlays are not designed to hab
Be thousands of them. You’re hitting DOM manipulation limitations if web browsers if you use so many overlays.

I’d recommend considering a different visualization.
