### ISSUE TITLE
TileWMS combined with XYZ or XYZ with BBOX attribute

### ISSUE THREAD

**Issue by tomasfreres** [openlayers/openlayers#10566]
**Is your feature request related to a problem? Please describe.**

I have a WMS server, where I can get the Tilelayer with an URL like this:

https://aaaaaaa.cc/map/tile?

where I need these attributes:
bbox (EPSG: EPSG:4326)
X
Y
Z

**Describe the solution you'd like**
It'd be cool, if we could manipulate the TileURL with an tileUrlFunction the same way like with XYZ Tiles, or if we could inject a bbox attribute with {bbox} in addition to {x} {y} and {z}

**Comment by mike-000** [comment]
TileWMS has a setTileUrlFunction method, if you need a custom url with a bbox


    source.setTileUrlFunction(function (tileCoord, pixelRatio, projection) {
        var bbox = source.getTileGrid().getTileCoordExtent(tileCoord).toString();

        return customUrl + '&BBOX=' + bbox;
    });
