### ISSUE TITLE
Performance regression in ol6 vs ol5

### ISSUE THREAD

**Issue by crubier** [openlayers/openlayers#10565]
Since we switched to OL6, the FPS of our map tanked, from 25 FPS to 5 FPS. Scrolling and zooming is rally laggy when it used to be super smooth.

Our use case is really simple, just one tile layer.

There seems to be something weird going on but I can't tell what. An interesting thing is the memory usage in the profiler: it looks like scrolling panning and zooming triggers a lot of Garbage collection, and the memory usage stays really constant with of a lot of garbage collecting, when it used to vary a lot more in ol5, Garbage collecting much less frequently. 

OL5 profile when panning, 2s sample:

![Screenshot 2020-01-22 at 16 40 18](https://user-images.githubusercontent.com/2954572/72915088-a7724180-3d37-11ea-872e-26a007aec598.jpg)

OL6 profile when panning, 2s sample:

![Screenshot 2020-01-22 at 16 40 07](https://user-images.githubusercontent.com/2954572/72915113-b1944000-3d37-11ea-9ac5-95e7fc3688ea.jpg)

**Comment by crubier** [comment]
Zoom on OL5 profile:

![Screenshot 2020-01-22 at 17 36 06](https://user-images.githubusercontent.com/2954572/72918548-ba881000-3d3d-11ea-8dc4-55ad44a3ad1d.jpg)

zoom on OL6 profile (same scale):

![Screenshot 2020-01-22 at 17 36 10](https://user-images.githubusercontent.com/2954572/72918582-c83d9580-3d3d-11ea-8663-aa73dbf86daa.jpg)

**Comment by jahow** [comment]
It looks like the HTML element of the tile layer is constantly removed and recreated by another one, which might explain the GC load. Do you have a running application showcasing the problem, or a minimal reproduction case? thanks

**Comment by crubier** [comment]
Indeed @jahow you are right, when panning, I can see the div gets recreated constantly.

OL5: Only one canvas for non-selectable layers:

![Screenshot 2020-01-23 at 11 53 05](https://user-images.githubusercontent.com/2954572/72982525-2d919500-3dd7-11ea-849f-5dc7121b37d2.jpg)

OL6: the canvas is in a div in a div:

![Screenshot 2020-01-23 at 11 53 26](https://user-images.githubusercontent.com/2954572/72982551-3edaa180-3dd7-11ea-949b-9131bd347778.jpg)

And the div in question gets reloaded constantly when panning:

![2](https://user-images.githubusercontent.com/2954572/72982575-49953680-3dd7-11ea-91d0-2f7466702a04.png)

I have no idea why.

I can't provide a public usage example right now, but really it is a super simple use case. Basically, like a getting started example, but there is probably something wrong with it... But at the same time, never had a problem with OL5...

**Comment by crubier** [comment]
The problem seem to happen in `ol/renderer/canvas/Layer.js` in `useContainer`, apparently very often the container is recreated, for some reason... investigating...

**Comment by crubier** [comment]
When I add `console.log`s in `useContainer` like this:

```
useContainer = function (target, transform, opacity) {
        var layerClassName = this.getLayer().getClassName();
        var container, context;
        console.log("useContainer==================================================================");
        console.log(target, transform, opacity);
        if (target && target.style.opacity === '' && target.className === layerClassName) {
            console.log("getting canvas");
            var canvas = target.firstElementChild;
            if (canvas instanceof HTMLCanvasElement) {
                console.log("getting context");
                context = canvas.getContext('2d');
            }
        }
        if (context && context.canvas.style.transform === transform) {
            console.log("Container of the previous layer renderer can be used.");
            // Container of the previous layer renderer can be used.
            this.container = target;
            this.context = context;
            this.containerReused = true;
        }
        else if (this.containerReused) {
            console.log("Previously reused container cannot be used any more.");
            // Previously reused container cannot be used any more.
            this.container = null;
            this.context = null;
            this.containerReused = false;
        }
        if (!this.container) {
            console.log("Need to recreate container!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
            container = document.createElement('div');
            container.className = layerClassName;
            var style = container.style;
            style.position = 'absolute';
            style.width = '100%';
            style.height = '100%';
            context = createCanvasContext2D();
            var canvas = context.canvas;
            container.appendChild(canvas);
            style = canvas.style;
            style.position = 'absolute';
            style.left = '0';
            style.transformOrigin = 'top left';
            this.container = container;
            this.context = context;
        } 
    };
```

I get this output while panning, we see that each 2 renders, we recreate the div...

```
useContainer==================================================================
Layer.js:92 <div class=​"ol-layer" style=​"position:​ absolute;​ width:​ 100%;​ height:​ 100%;​">​…​</div>​ "matrix(1, 0, 0, 1, 0, 0)" 1
Layer.js:94 getting canvas
Layer.js:97 getting context
Layer.js:102 Container of the previous layer renderer can be used.
Layer.js:91 useContainer==================================================================
Layer.js:92 null "matrix(1, 0, 0, 1, 0, 0)" 1
Layer.js:109 Previously reused container cannot be used any more.
Layer.js:116 Need to recreate container!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Layer.js:91 useContainer==================================================================
Layer.js:92 <div class=​"ol-layer" style=​"position:​ absolute;​ width:​ 100%;​ height:​ 100%;​">​…​</div>​ "matrix(1, 0, 0, 1, 0, 0)" 1
Layer.js:94 getting canvas
Layer.js:97 getting context
Layer.js:102 Container of the previous layer renderer can be used.
Layer.js:91 useContainer==================================================================
Layer.js:92 null "matrix(1, 0, 0, 1, 0, 0)" 1
Layer.js:109 Previously reused container cannot be used any more.
Layer.js:116 Need to recreate container!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Layer.js:91 useContainer==================================================================
Layer.js:92 <div class=​"ol-layer" style=​"position:​ absolute;​ width:​ 100%;​ height:​ 100%;​">​…​</div>​ "matrix(1, 0, 0, 1, 0, 0)" 1
Layer.js:94 getting canvas
Layer.js:97 getting context
Layer.js:102 Container of the previous layer renderer can be used.
Layer.js:91 useContainer==================================================================
Layer.js:92 null "matrix(1, 0, 0, 1, 0, 0)" 1
Layer.js:109 Previously reused container cannot be used any more.
Layer.js:116 Need to recreate container!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Layer.js:91 useContainer==================================================================
```

**Comment by crubier** [comment]
And then commenting the following lines in `ol/renderer/canvas/Layer.js` solves the problem! 🎉 

```
else if (this.containerReused) {
            console.log("Previously reused container cannot be used any more.");
            //  // Previously reused container cannot be used any more.
            // this.container = null;      // WHY?
            // this.context = null;      // WHY?
            // this.containerReused = false;      // WHY?
        }
```

So the question ⬆️ is: why do we disable reusing the container in `ol/renderer/canvas/Layer.js` ??

**Comment by crubier** [comment]
Ok just found why these lines are here, when I remove them, I get this when zooming out fast...

![Screen Recording 2020-01-23 at 13 10 46 mov](https://user-images.githubusercontent.com/2954572/72987263-efe63980-3de1-11ea-911b-f3c26f19bcd5.gif)

There seem to be some kind of new zoom optimization somewhere in OL6 that require these lines... But dont know why and how here, I might need help...

**Comment by ahocevar** [comment]
If you need help, you need to provide a standalone example that exposes the issue. Could it be that you are using a custom renderer that might need some modifications after upgrading OpenLayers to version 6?

**Comment by crubier** [comment]
The thing is this example is when using our own proprietary package `react-openlayers` which manages openlayers through react. So I will try to reproduce it without react first. I am 99% sure that react is not involved in the problem here since it does not do a single rerender during all of this.

I'll try to make a simple reproduction... And I might find a root cause on our side while doing so, who knows? But the example is so simple I don't think we do anything special

**Comment by crubier** [comment]
Ok found the culprit. it boils down to this:

```
 const map = new Map({
      layers: [],
      target: refContainer.current,
      view: new View({
        center: [0, 0],
        zoom: 2
      })
    });

// Create a layer, with a map argument to link it to the map
const layer = new TileLayer({
  map: map,
  source: new OSM()
}));

// Link the layer to the map AGAIN, this is redundant and causes the bug
map.addLayer(layer);

```

**Comment by mike-000** [comment]
The release notes https://github.com/openlayers/openlayers/releases/tag/v6.0.0 specify "Layers can only be added to a single map".  That would probably also prevent a layer being added twice to the same map.

**Comment by ahocevar** [comment]
This is a situation that goes past the assertion that a layer can only be added once to the map's layers collection, because the layer is instantiated as unmanaged layer and then added to the map. This could be considered a bug, and we could add an assertion to avoid this.

Anyone willing to create a pull request?

**Comment by crubier** [comment]
I wish I could, but I have no idea of where to start. If you have an idea of where to start, I could give it a try.

**Comment by ahocevar** [comment]
I created #10572. @crubier, please test with your application to make sure you run into the new assertion.

**Comment by crubier** [comment]
It works, this is it! Thank you!
