### ISSUE TITLE
KML imports correctly, but data doens't show

### ISSUE THREAD

**Issue by stevemassar** [openlayers/openlayers#10571]
Our generated .KML file imports to our Open Layers application, but the data doesn't appear in the layer.

File included in zip
[layer.zip](https://github.com/openlayers/openlayers/files/4108893/layer.zip)

**Comment by mike-000** [comment]
There is a problem with the stroke style import, probably related to #10538  The data shows using`KML({extractStyles: false})`

**Comment by stevemassar** [comment]
tnx mike-000, for me you're much more than 000

Op vr 24 jan. 2020 om 16:44 schreef mike-000 <notifications@github.com>:

**Comment by mike-000** [comment]
Definitely the same as #10538  The stroke style can be imported if the Polystyle is removed from your data.
