### ISSUE TITLE
error 'getTileGridForProjection is not a function' for ImageWMS with non-default proj

### ISSUE THREAD

**Issue by ackerra** [openlayers/openlayers#10579]
Hi,

I use this code:
```js
	tn = new ol.layer.Tile({
			source: new ol.source.ImageWMS({
				url: myUrl
				,params: {'LAYERS': '0,1,2'}
				,ratio: 1.5
				})
			,extent: extent3035
			});
	EUview = new ol.View({
					center: center3035
					,zoom: initialZoom
					,projection: 'EPSG:3035'
					,resolutions: resolutions3035
					,extent: extent3035
          			});
	var map = new ol.Map({target: 'map', layers: [tn], view: EUview});
```
All variables are well defined, and the projection is created as well.

Console message: TypeError: u.getTileGridForProjection is not a function in TileLayer.js:159
for ol 6.1.1

Thanks for any help.

**Comment by ahocevar** [comment]
You're defining a tile layer (`ol.layer.Tile`) with an image source (`ol.source.ImageWMS`). But image sources cannot be used with tile layers. Use a tile source instead. In this case `ol.source.TileWMS`.

**Comment by ackerra** [comment]
But of course. Thanks for your instant reply.
