### ISSUE TITLE
Erroneous License in `src/ol/sphere.js`

### ISSUE THREAD

**Issue by garrettsickles** [openlayers/openlayers#10589]
**Is your feature request related to a problem? Please describe.**
This repo is marked as `BSD-2 Clause`, but in `src/ol/sphere.js` the license is explicitly `CC-BY-3.0`:
https://github.com/openlayers/openlayers/blob/4973281f3c457e48aa56982db6aa4123ddc37c2a/src/ol/sphere.js#L5

**Describe the solution you'd like**
`src/ol/sphere.js` should have the license removed from source and inherit the project license.

**Comment by garrettsickles** [comment]
For reference, the commit: https://github.com/openlayers/openlayers/commit/544f399e04d1716e95210240ade2d06d7bbd8eb2

**Comment by ahocevar** [comment]
Thanks for spotting this @garrettsickles. Your suggested solution is correct, because none of the code from 544f399 is in that file any more. I'll create a pull request.

**Comment by ahocevar** [comment]
See #10591.
