### ISSUE TITLE
Rename Heatmap layer

### ISSUE THREAD

**Issue by JacobBrandt** [openlayers/openlayers#10594]
No where in documentation does the layer say it's a WebGL layer.  Every other layer that is rendered using WebGL has either WebGL in the class name or the path to the class.

It's unfortunate for our project that this information is obfuscated.  Please put this class behind either a webgl path or put WebGL in the name like WebGLPointsLayer is to make this clear to developers what capabilities their end users will need to use this layer.

**Comment by jahow** [comment]
Hi! It's true that the fact that the Heatmap is webgl-rendered is in fact not advertised. Mentioning it in the documentation would make sense but I'd advise against putting it explicitly in a webgl-named module as it isn't experimental and its API is stable.

That said, webgl 1 support is around 97% these days. What browsers did you end up having trouble with?

**Comment by JacobBrandt** [comment]
It’s not a browser problem, it’s a lack of hardware to support that kind of rendering.  Theses users are running in a VDI that has no GPU pass through and the infrastructure is not something our project can control.

For consistency sake changing the module name or class name makes sense because as it stands right now the API is misleading.
