### ISSUE TITLE
Export map example doesn't work properly in Chrome and Edge

### ISSUE THREAD

**Issue by Hareck** [openlayers/openlayers#10593]
With using ‘html-to-image’ Chrome get’s a problem with the ‘data URI limit’ if a lot of details are in the map. (Zoom into a big town in the ‘map export’ example and press the ‘Download-PNG’ Button, nothing appears.)
To solve this behavior I tested the ‘html2canvas’ library (https://html2canvas.hertzen.com/). 
Pro: It works in FF, Chrome and Edge for the ‘map export’ example.
Contra: The script is still in a very experimental state.

Code snippet for map export example:

import html2canvas from 'html2canvas';
import {saveAs} from 'file-saver';
…
map.once('rendercomplete', function() {
  var target = map.getViewport();
  // options for html2canvas to filter out all the 'ol-control' elements
  var configOptions = {
    ignoreElements: function(target) {
      return (target.className.indexOf('ol-control') !== -1); },
    logging: false
  };
  html2canvas(target, configOptions)
    .then(function(canvas) {
      canvas.toBlob(function(blob) {
        saveAs(blob, 'map.png');
      });
    });
});
…

The ‘html2canvas’ library doesn’t work in the ‘Export PDF’ example because the script takes "screenshots" of webpages or parts of it, that means only what I see in my browser window is exported 
or it could be my configuration for this library is wrong.

Code snippet for pdf export example:

import html2canvas from 'html2canvas';
import * as jsPDF from 'jspdf';
…
map.once('rendercomplete', function() {
  var target = map.getViewport();
  // options for html2canvas to filter out all the 'ol-control' elements
  var configOptions = {
    ignoreElements: function(target) {
      return (target.className.indexOf('ol-control') !== -1); },
    logging: false
//    width: width,
//    height: height,
//    windowWidth: width,
//    windowHeight: height
  };
  html2canvas(target, configOptions)
    .then(function(canvas) {
      var pdf = new jsPDF('landscape', undefined, format);
      pdf.addImage(canvas, 'png', 0, 0, dim[0], dim[1]);
      pdf.save('map.pdf');
…
  });
});
…

For the future it would be great to have a function like this: 
ol.map.getCanvasFromViewport(); 
with options to filter out some classNames like ‘ol-control’.

**Comment by mike-000** [comment]
see #10541 and #10563

**Comment by Hareck** [comment]
It works after all in the ‘Export PDF’ example.
Code snippet for pdf export example with 'html2canvas' (it works in FF, Chrome and Edge):

import html2canvas from 'html2canvas';  // version 1.0.0-rc.5
import * as jsPDF from 'jspdf';

```
...
map.once('rendercomplete', function() {
  var target = map.getViewport();
  var olCanvas = document.getElementsByTagName('canvas')[0];
  // options for html2canvas
  var configOptions = {
      ignoreElements: function(target) {
        if ((target.className.indexOf('ol-control') !== -1) // to filter out all the 'ol-control' elements
          || (target.className === 'ol-scale-line-inner'))  // to filter out the scale-line element
          return true;
        else
          return false;
      },
      canvas: olCanvas,      // to use canvas from openlayers
      logging: false         // no logging
  };
  html2canvas(target, configOptions)
    .then(function(canvas) {
      var pdf = new jsPDF('landscape', undefined, format);
      pdf.addImage(canvas, 'png', 0, 0, dim[0], dim[1]);
      pdf.save('map.pdf');
...
  });
});
```

**Comment by ahocevar** [comment]
As of #10563, this example does not use html2canvas any more.
