### ISSUE TITLE
Add protobuff support for webglpoints layer

### ISSUE THREAD

**Issue by mourya09** [openlayers/openlayers#10592]
Hi team
You have added a very good solution for webgl points layer in latest version. If I have big no of points then its size must be greater than 1mb. It will be good if capability to protobuff is added.

**Comment by jahow** [comment]
Hi, thanks! what exactly would you expect to be provided by the library? Protobuf is already used by the MVT format which OL is able to parse.

**Comment by mourya09** [comment]
> Hi, thanks! what exactly would you expect to be provided by the library? Protobuf is already used by the MVT format which OL is able to parse.

I am trying to render 8 to 10 millions points on browser using open layers. And this requirement may increase in future. As the incoming file size increases then it will be problem in rendering it. It would be nice if we have a small option in webglpointlayers that incoming file is compressed/minified,so that it take care of the rest.

**Comment by pierrethiriet** [comment]
Hi team,
I know that Issues are not deigned for feature requests, but I use the opportunity of the @mourya09 comments to add one point.   

Thanks to the last development *PostgreSQL* and *PostGIS*, it became very easy to set to deal with *MVT*. It opens the doors for complex dynamic queries while sending a large amount of data with a low bandwidth footprint.
However, it raises the question of the proper visualization method for a large number of points. For now, it seems that the two best options, **clustering** and **WebGL** (heatmap/point with transparency...), are unfortunately not available for vector tile layer. 
- It is possible to cluster points earlier, in PostGIS, [Cluster F(x): Nesting PostgreSQL KMeans in DBScan for responsive maps]( https://medium.com/geolytix/cluster-f-x-nesting-postgresql-kmeans-in-dbscan-for-responsive-maps-9ed99590a439), but it seems not as efficient (fast…) than the OpenLayers clustering algorithm. Moreover, it seems more logical to split the data querying step fro the visualization one.  
- It seems also possible to convert on the fly *mvt* to *geojson* and to cluster after as stated in this [discussion]( https://stackoverflow.com/a/55171290). But in my experiment results are not 100% satisfactory.  
- The js supercluster from Mapbox does seem to support mvt neither (contrary to *Mapbox-GL* it seems).    

So, it is yet not so simple to use *mvt* with numerous points and *OpenLayers* without specific tricks. Unfortunately, I have not the skill neither the understanding to contribute to OpenLayers on that matter…

**Comment by ahocevar** [comment]
Geobuf is a format we could add, and support for ol/render/Feature for vector and WebGL data. And I do think it makes sense to do both in the short term.

For the future. I think we should support formats like MVT and Geobuf more natively, i.e. make use of their data streams and support rendering from the data directly, without the need to create and store features.

**Comment by jahow** [comment]
Also I think a few years ago there was an attempt to implement a TWKB parser in OL. That might be another binary format to read.

**Comment by pierrethiriet** [comment]
The addition of *.mvt* for a wider range of render would be a valuable addition for my type of application (lot of points to renders while dynamically changing the underlining queries)

**Comment by dahannes** [comment]
@ahocevar could you please give a brief update on the status of this feature? Rendering points in MVT format via webgl.

**Comment by ahocevar** [comment]
You can use the [geobuf](https://npmjs.com/package/geobuf) library to load data into a `Vector` source, and render that using the [WebGLPoints](https://openlayers.org/en/latest/examples/webgl-points-layer.html) layer.
