### ISSUE TITLE
Circle, Arcs and user defined Geometries and WKT conversion

### ISSUE THREAD

**Issue by eladlavi** [openlayers/openlayers#10608]
Circle geometry exists in OpenLayers but because GeometryEncoder in WKT.js (code lines 843) doesn't have a "Circle" Encoder, using writeGeometryText and readGeometryText fails at line 861 (const geometryEncoder = GeometryEncoder[type];).
Perhaps a wise solution will be to "export"  the GeometryEncoder object so users/programmers can "add" encoders to it, weather or not OpenLayers naturally support WKT conversion of those geometries.
Furthermore,  users/programmers should be able to define classes that represent geometries of their own. For instance, an Arc as a geometry that doesn't exist, a Rectangle and much more. Of course those can be represented as "Polygons" but this very inaccurate.
Looking at: https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry, there are more geometries, some are 3D that might be harder to draw, but should be supported either naturally or by user extending exists OpenLayers classes and overriding methods as necessary.

My "patch" workaround solution is to add an if statement just before WKT conversion that excludes Circle geometry type to be handles separately. For instance:

`export class ExtendedWKT extends WKT {
    
    writeGeometryText(geometry, opt_options) {
        if(geometry.getType() === 'Circle') {
            console.log('in override');
            return 'CIRCLE('+geometry.getCenter().join(' ')+')';
        }else {
            return super.writeGeometryText(geometry, opt_options);
        }
    }
}`

Keep up the good work.

**Comment by mprins** [comment]
CIRCLE is not a thing that exists in the standard: https://www.opengeospatial.org/standards/sfa
generating non-standard serializations is a bad idea

you need to look into Curves.

**Comment by ahocevar** [comment]
@eladlavi Overriding methods of a class like you do is perfectly fine. But @mprins's concern is valid.

Thanks both for the input.
