### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by jGerstmayer** [openlayers/openlayers#10610]
When is the next version of the project going to be released?

**Comment by ahocevar** [comment]
If there are no objections from @openlayers/core, I'm planning to cut a release this weekend.

**Comment by hugh-barclay** [comment]
Is there a new ETA?

**Comment by jahow** [comment]
I'd like https://github.com/openlayers/openlayers/pull/10632 to be merged before the release, since it's almost ready. I'll let @ahocevar give a more precise ETA.

**Comment by ahocevar** [comment]
I just reviewed #10632. If @jahow can address my comments today, the ETA is today. I have already prepared the release branch.

**Comment by jahow** [comment]
> I just reviewed #10632. If @jahow can address my comments today, the ETA is today. I have already prepared the release branch.

Done

**Comment by ahocevar** [comment]
v6.2.0 has been released.
