### ISSUE TITLE
Select Interaction with style function rendering issue with VectorTile

### ISSUE THREAD

**Issue by micmarcil** [openlayers/openlayers#10621]
Hello,

Since 6.1.1, I noticed an issue when using the Select Interaction style property to handle selected features style of a VectorTile layer

It worked fine in version 5.3.0

I use a ol.layer.VectorTile with a ol.source.VectorTile
The source is configured with a custom tileLoadFunction, inside of which I do some computing then I set some features on the tiles ( tile.setFeatures(...) ).
Feature are rendered without issues, as expected.
(Everything has been adjusted according to the release note)

A Select Interaction is registered on the map and configured with a style function to handle selected feature styles.

When I click on a feature on the map, nothing happens.
The style function is not even called.

The style function is called if I zoom in, but the style is still not applied. If I zoom in/zoom out, I can sometimes see the applied style on the selected feature, but the behavior is not constant.
Moreover, it seems the style is not cleared when I click elsewhere on the map (deselect).

Could it be related to the refactor/optimizations done in the 6.x on the VectorTile ?

**Comment by ahocevar** [comment]
First of all, I would not recommend using the select interaction with vector tiles. Vector tiles do not contain the original geometries of features, and the geometries are clipped. If you feel like you need to, make sure to construct the MVT format to create features instead of render features:
```js
import MVT from 'ol/format/MVT';
import Feature from 'ol/Feature';

new MVT({
  featureClass: Feature
});
```
That is important because in v6, the Select interaction sets a style on the selected feature, and that API is only available for ol/Feature, not for ol/render/Feature.

**Comment by micmarcil** [comment]
I see

My tileLoadFunction is setting **ol.Feature** specifically when calling tiles.setFeatures(...) (not ol.render.Feature)
Should it be working ?

Otherwise, should I handle the selection like in the example instead ?
[Vector Tiles Selection](https://openlayers.org/en/latest/examples/vector-tile-selection.html?q=Select)

I liked the Select Interation, seemed more simple :)

Thanks for your time

**Comment by micmarcil** [comment]
I ended up handling the selection myself with the map click event and map.forEachFeatureAtPixel

map.forEachFeatureAtPixel is conveninent for this since I have access to the feature and its layer in the callback.

I'm no longer using the Select interaction.

Thanks
