### ISSUE TITLE
Canvas renderer uses only single TextBaseline in a view

### ISSUE THREAD

**Issue by radokostelnik** [openlayers/openlayers#10635]
When displaying multiple point features with a Text with different textBaseline values, only one of them is applied at a time.

Example here
https://codesandbox.io/s/icon-color-tor47
3 points, top, middle and bottom textBaseline-s used, all features are rendered with bottom.

If the list of features contains just a single textBaseline value, it renders correctly. To test, remove 2 of 3 items on the line 66 `features: [london, madrid, rome]`

**Comment by ahocevar** [comment]
Duplicate of #10497, and fixed already.
