### ISSUE TITLE
Issue with constraints for new mousewheel zoom

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#10638]
**Describe the bug**
The smooth resolution constraint allows zooming out slightly more than 

**To Reproduce**
1. Go to https://openlayers.org/en/v6.2.0/examples/drag-rotate-and-zoom.htmland compare the zoom out behaviour to https://openlayers.org/en/v6.1.1/examples/drag-rotate-and-zoom.html
2. with v6.2.0 you can zoom out ~1 zoom level past the constraint, with v6.1.1 smooth constraints doesn't seem to have an effect on zoom.

**Expected behavior**
According to the description for `smoothResolutionConstraint`  of `ol/View` it should be possible to exceed it slightly. 
> (defaults to true) | If true, the resolution min/max values will be applied smoothly, i. e. allow the view to exceed slightly the given resolution or zoom bounds.

This sounds like the old *and* the new behaviors are wrong.

**Comment by ahocevar** [comment]
The behavior is consistent with the trackpad mode in v6.1: "slightly" means ~1z. If you set `smoothResolutionConstraint` to `false`, you won't be able to zoom out more than the restricted extent at all.

**Comment by MoonE** [comment]
It doesn't *feel* smooth because there is a little delay until it snaps back and I can scroll for a few seconds until i actually hit the limit.
I think previously there was an easing effect applied to the zooming which progressively reduced the amount that was zoomed with each mouse wheel click.

**Comment by ahocevar** [comment]
That's correct. The new wheel zoom mode is so fine-grained that the easing does not really kick in much any more.
