### ISSUE TITLE
Please provide Custom WebGL layer example

### ISSUE THREAD

**Issue by microspace** [openlayers/openlayers#10633]
I'm trying to add webgl layer to draw geometry primitives with shaders. Someone has suggested me to dive into HeatmapLayer example, but it seem to complex for me. Please provide a simple example to draw, for example,  triangle with shaders, same as [mapbox example](https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/).

**Comment by jahow** [comment]
The experimental webgl api does not currently allow drawing triangles. The only thing implemented is a points renderer, for which you can either look at the HeatmapLayer or WebGLPointsLayer classes.

The mapbox example you cited is essentially just an illustration on how to use the WebGL api. You could do pretty much the same by simply using this option of the base Layer class to create a completely custom layer element based on a WebGL canvas:
https://github.com/openlayers/openlayers/blob/fe8f7c04adcd27e331de2f963876c924aad9a3b4/src/ol/layer/Layer.js#L38-L39

**Comment by microspace** [comment]
Thank you @jahow! Is there an example how to pass data to RenderFunction?

**Comment by jahow** [comment]
[This example](https://openlayers.org/en/master/examples/mapbox-layer.html) uses a layer with custom `render` function to embed a Mapbox element inside an OpenLayers map.

You can do anything you want in this render function: read a source, transform coordinates, create a `canvas` element and render to it, etc.

**Comment by microspace** [comment]
Thank you @jahow for example link, I've also found an useful example at [openlayers workshop](https://openlayers.org/workshop/en/webgl/points.html)
