### ISSUE TITLE
Map pans with mousewheel zoom 

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#10641]
**Describe the bug**
The map pans when the mouse wheel is used during the snap-back animation of the view.

**To Reproduce**
1. Go to https://openlayers.org/en/v6.2.0/examples/drag-rotate-and-zoom.html
2. Zoom out farther than the resolution constraint allows
3. Wait a new hundred milliseconds until it snaps back.
4. Use the mouse wheel during the snap-back animation.
5. If the mouse was positioned to the left of the map center it jumps to the left, otherwise to the right. The more it was over-zoomed the farther the jump is.

**Expected behavior**
The map coordinate at the mouse pointer should not change.

**Comment by ahocevar** [comment]
I can confirm this. It is the same behavior as with a trackpad. @jahow, since you are most familiar with the view constraint code, could you take a look at this please? Or @MoonE, do you already have an idea how to fix this? A pull request would be welcome.

**Comment by jahow** [comment]
Ok, I've reproduced this as well. Thanks @MoonE for the report, I'll look into this.
