### ISSUE TITLE
Export Map example does not work in Safari

### ISSUE THREAD

**Issue by truespeed-david** [openlayers/openlayers#10643]
The example to export map is at https://openlayers.org/en/latest/examples/export-map.html

Expected Behaviour:
1. Click PNG
2. Download PNG
3. Open PNG and it contains the map viewport

Actual Behaviour in Safari Version 13.0.5 (15608.5.11) (works ok with Firefox):
1. Click PNG
2. Download PNG
3. Open PNG and it either contains no data, a completely black PNG or random data in the PNG.

![map-2](https://user-images.githubusercontent.com/32777629/74325608-d2711380-4d80-11ea-80ff-752debe7145c.png)

**Comment by ahocevar** [comment]
This could be fixed by using the same technique as introduced in #10563. A pull request would be welcome.

**Comment by mike-000** [comment]
A partial fix.  A fallback to canvas export for browsers which do not support html-to-image would not include the overlay.

**Comment by ahocevar** [comment]
I think it would also be ok to remove the overlay from the example. In v5, that example also had no overlay.
