### ISSUE TITLE
Tests fail because of updated Handlebar dependency

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#10640]
**Describe the bug**
Tests don't run because of the update from Handlebars 4.5 to 4.7
In v4.6 new security restrictions were implemented.

**To Reproduce**
1. Go to #10618
2. Click on the link to CircleCI
3. See errors:
> Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "branches" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "functions" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "lines" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details

**Expected behavior**
No failing tests.

**Comment by ahocevar** [comment]
The failed CI run in #10618 is unrelated to this, but this should be fixed regardless.

For now, I have triggered a re-run of the #10618 CI checks. So that should show up as green soon.

**Comment by MoonE** [comment]
Thank you, I think #10625 has the same problem, could you kindly look into it.

**Comment by fredj** [comment]
handlebars warnings fixed with #10703
