### ISSUE TITLE
If zoom-level of view < 3 throws error =>   Cannot read property '3' of undefined

### ISSUE THREAD

**Issue by Fiaesrsr** [openlayers/openlayers#10645]
When a vectorLayer was added to the Map and the zoom-level of the view < 3, it throws an error => 
Cannot read property '3' of undefined.

***Error-Details*** 

Executor.replayImageOrLabel_
https://m0qxk.csb.app/node_modules/ol/render/canvas/Executor.js:160:23
Executor.execute_
https://m0qxk.csb.app/node_modules/ol/render/canvas/Executor.js:463:18
Executor.execute
https://m0qxk.csb.app/node_modules/ol/render/canvas/Executor.js:620:10
ExecutorGroup.execute
https://m0qxk.csb.app/node_modules/ol/render/canvas/ExecutorGroup.js:172:20
CanvasVectorLayerRenderer.renderFrame
https://m0qxk.csb.app/node_modules/ol/renderer/canvas/VectorLayer.js:132:17
VectorLayer.Layer.render
https://m0qxk.csb.app/node_modules/ol/layer/Layer.js:101:28
CompositeMapRenderer.renderFrame
https://m0qxk.csb.app/node_modules/ol/renderer/Composite.js:97:27
Map.PluggableMap.renderFrame_
https://m0qxk.csb.app/node_modules/ol/PluggableMap.js:568:20
Map.eval
https://m0qxk.csb.app/node_modules/ol/PluggableMap.js:97:12

***To Reproduce***
1. Define a map component with a view, tileLayer  etc.
2. Set the zoom of your view to 3.
3. Define a vectorLayer with a geoJSON as vectorSource.
4. Compile and zoom out.

***Code to reproduce***

**GeoJSON-Object**
```json
{
        type: "FeatureCollection",
        crs: {
          type: "name",
          properties: {
            name: "EPSG:3857"
          }
        },
        features: [
          {
            type: "Feature",
            geometry: {
              type: "Point",
              properties: { name: "TEST2" },
              coordinates: [6.94506, 58.6917]
            }
          },
          {
            type: "Feature",
            geometry: {
              type: "Point",
              properties: { name: "TEST2" },
              coordinates: [7.622712, 60.634644]
            }
          },
          {
            type: "Feature",
            geometry: {
              type: "Point",
              properties: { name: "Test in der Nähe" },
              coordinates: [7.622712, 51.6917]
            }
          }
        ]
      }
```

**Map-Definitions**
```js
 var styles = {
      Point: new Style({
        image: new CircleStyle({
          radius: 5,
          fill: new Fill({
            color: "red"
          }),
          stroke: new Stroke({
            color: "red"
          })
        })
      })
    };
    var styleFunction = function(feature) {
      return styles[feature.getGeometry().getType()];
    };
    let view = new View({
      center: fromLonLat([6.94506, 51.6917]),
      zoom: 3,
      // minZoom: 0,
      projection: "EPSG:3857"
    });
    let tileLayer = new TileLayer({
      source: new OSM()
    });
let vectorLayer = new VectorLayer({
      source: new VectorSource({
        features: new GeoJSON().readFeatures(this.geoJSONdefault)
      }),
      style: styleFunction
    });
    let map = new Map({
      target: "map",
      layers: [tileLayer, vectorLayer],
      view: view
    });
map.render();
```

**Expected behavior**
An error occured which tells "Cannot read property '3' of undefined"

**Comment by ahocevar** [comment]
Which bundler are you using? I noticed a similar issue a while back, caused by an import that was not correctly resolved. Both your issue and the one back then, I can reproduce in https://codesandbox.io/. Locally everything works fine. Tested wit Webpack and Parcel.
