### ISSUE TITLE
Simplify the code to zoom to a GPX Layer's extent after it is rendered

### ISSUE THREAD

**Issue by bmnds** [openlayers/openlayers#10651]
As of this writing, current openlayers stable version is 6.1.1.

# the problem
The code to zoom to a GPX layer's extent after it is rendered is non-intuitive, this is the code that works:
```
var gpxLayer = new VectorLayer({
  title: 'Salto do Ipy',
  visible: false,
  source: new VectorSource({
    url: <path-to-gpx-file>,
    format: new GPX()
  })
});
// for some reason, this event never fires
gpxLayer.on('postrender', function() {
  // this block will never be executed
});
// First time the layer is rendered, 'addfeature' event will be called
gpxLayer.getSource().on('addfeature', function() {
  map.getView().fit(buffer(gpxLayer.getSource().getExtent(), 1000))
});
// From there on, 'propertychange' should be listened for 
gpxLayer.on('propertychange', function(evt) {
  if (gpxLayer.getVisible()
      && gpxLayer.getSource().getExtent()[0] !== Infinity
      && gpxLayer.getSource().getExtent()[0] !== -Infinity) {
    map.getView().fit(buffer(gpxLayer.getSource().getExtent(), 1000))
  }
});
```

# the proposed solutions
1. fix 'postrender' event to be fired when the layer is made visible or when all data from the gpx layer gets loaded
2. create a new event named 'layeradd' that gets fired on the map when a new layer is added or an existing layer is made visible
```
var gpxLayer = new VectorLayer({
  title: 'Salto do Ipy',
  visible: false,
  source: new VectorSource({
    url: <path-to-gpx-file>,
    format: new GPX()
  })
});
// first proposal is to directly listen to 'postrender' event on the layer
gpxLayer.on('postrender', function() {
  map.getView().fit(buffer(gpxLayer.getSource().getExtent(), 1000))
});
// second proposal is to listen to create a new map event 
map.on('layeradd', function(e) {
  map.getView().fit(buffer(e.target.getExtent(), 1000))
});
```

**Comment by ahocevar** [comment]
What I would use is:
```js
source.once(‘change’, () => {
  map.getView().fit(source.getExtent());
});
```
However, thanks for reporting the postrender issue. This is something that needs to be checked.

**Comment by ahocevar** [comment]
I just checked the postrender Event: it does work as expected. See https://codesandbox.io/s/tracing-cjymz:
```js
vectorLayer.once("postrender", e => {
  map.getView().fit(vectorSource.getExtent(), { padding: [20, 20, 20, 20] });
});
```

The reason why it did not work for you is probably that loading of the gpx was not triggered, because the map's view had no zoom and center yet.

**Comment by bmnds** [comment]
> I just checked the postrender event, and it does work as expected. See https://codesandbox.io/s/tracing-cjymz:
> 
> ```js
> vectorLayer.once("postrender", e => {
>   map.getView().fit(vectorSource.getExtent(), { padding: [20, 20, 20, 20] });
> });
> ```
> 
> The reason why it did not work for you is probably that loading of the gpx was not triggered, because the map's view had no zoom and center yet.

Firstly I would like to thank you for the quick response!

I was able to narrow down the scenario in which 'postrender' event doesn't fire, to:
1. create a gpxLayer with `visible: flase`;
2. create a map and center it at some point;
3. change the gpxLayer to `visible: true`.

Here is some snippet of code using LayerSwitcher to control layer visibility:
```
var gpxLayer = new VectorLayer({
  title: 'Salto do Ipy',
  visible: false,
  source: new VectorSource({
    url: <path-to-gpx-file>,
    format: new GPX()
  })
});
// for some reason, this event never fires
gpxLayer.on('postrender', function() {
  // this block will never be executed
  console.log('fired postrender on gpxLayer');
});

var basemap= <init basemap layer>

var map = new Map({
  layers: [basemap, gpxLayer],
  target: document.getElementById('map'),
  view: new View({
    center: <some random point>,
    zoom: 12
  })
});

// ol-layerswitcher
map.addControl(new LayerSwitcher());
```

**Comment by bmnds** [comment]
> What I would use is:
> 
> ```js
> source.once(‘change’, () => {
>   map.getView().fit(source.getExtent());
> });
> ```
> 
> However, thanks for reporting the postrender issue. This is something that needs to be checked.

This event on the source only fires when data is loaded. But it doesn't get fired then layer's attribute `visible` is changed to `true`. For that case I had to continue listening for 'propertychange' event on the layer.

**Comment by mike-000** [comment]
If you specifically want data being loaded you could use `source.on('addfeature', ...`
