### ISSUE TITLE
MouseWheelZoom

### ISSUE THREAD

**Issue by overkamp** [openlayers/openlayers#10652]
With openlayers 6.2.0 mouseWheelZoom and dragPan are no longer able.

I have  interactions: defaultInteractions({dragPan: true, mouseWheelZoom: true}),
in my map, but no chance to drag or zoom

**Comment by ahocevar** [comment]
You need to update (or start using) `css/ol.css` to the one of v6.2.0.

**Comment by overkamp** [comment]
Many thanks!!
