### ISSUE TITLE
Layer.getExtent() returns undefined when working with a Layer sourced by a GPX file

### ISSUE THREAD

**Issue by bmnds** [openlayers/openlayers#10650]
# the problem
When trying to work with a Layer sourced by a GPX file, I had a hard time trying to figure out why `gpxLayer.getExtent()` was `undefined`... until I found out that `gpxLayer.getSource().getExtent()` was the right way to get its extent.

# the proposed solution
I think it would be easier for newcomers if a method like `Layer.getExtent()` always return the correct extent, no matter what is behind the scenes, whether it is a Tile layer, a Vector layer or an Overlay layer.

# some sample code
```
// this is the code that works
map.getView().fit(buffer(gpxLayer.getSource().getExtent(), 1000))

// this is the code that doesn't work nowadays
map.getView().fit(buffer(gpxLayer.getExtent(), 1000))
```

**Comment by ahocevar** [comment]
The layer's `getExtent()` function returns the layer extent, if you specified one to restrict the visible area of the layer. This is documented in https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html#getExtent.

This is because in OpenLayers, the `Layer` is a lightweight container that configures things that influence the way the layer is rendered (e.g. styles, rendered extent, etc.). Whereas the `Source` represents the underlying data. So to get the extent of the data, you'll need to ask the source for the extent.

**Comment by bmnds** [comment]
I see... I will close this issue then.

But maybe this explanation could be added to VectorLayer.getExtent docs.

**Comment by adilorenzodema** [comment]
> The layer's `getExtent()` function returns the layer extent, if you specified one to restrict the visible area of the layer. This is documented in https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html#getExtent.
> 
> This is because in OpenLayers, the `Layer` is a lightweight container that configures things that influence the way the layer is rendered (e.g. styles, rendered extent, etc.). Whereas the `Source` represents the underlying data. So to get the extent of the data, you'll need to ask the source for the extent.

Hi, How I can get the layername present on map.getView().calculateExtent()  ??

**Comment by ahocevar** [comment]
You need to call `getExtent()` on the source to get the extent of the loaded features of a source.

`map.getView().calculateExtent()` just gives you the current extent of the map viewport.

**Comment by adilorenzodema** [comment]
But how can I know the layers present on my current view of map?
With map.getView().calculateExtent() I can know my actual view coordinate...
is there a solution for this?

**Comment by ahocevar** [comment]
You'd have to get all map layers with `map.getAllLayers()` and do an intersection for each vector source with the result of its `getExtent()` method.
