### ISSUE TITLE
Polyfill script in examples template loads later than in stand-alone example code

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10662]
**Describe the bug**
This can be seen in the latest Export PDF example.  Although displayed code works with Internet Explorer when stand-alone, when wrapped in the template the jspdf script (which needs the fetch polyfill to define Promise) loads before the polyfill script.

**Comment by ahocevar** [comment]
Changing that example to use jspdf from npm, like we do with proj4, might solve the issue.

**Comment by mike-000** [comment]
Would you want to create and maintain dependencies which are specific to one example?  It looks like moving the polyfill script line to above `{{{ extraHead.local }}} in `https://github.com/openlayers/openlayers/blob/master/examples/templates/example.html would be sufficient.
