### ISSUE TITLE
Text stroke uses wrong lineDash

### ISSUE THREAD

**Issue by bjoernboldt** [openlayers/openlayers#10665]
My style function is
```
function (feature, resolution) {
	return new ol.style.Style({
		stroke: new ol.style.Stroke({
			color: 'red',
			width: 3,
			lineDash: [1, 10, 1, 10, 10, 10]
		}),
		text: new ol.style.Text({
			font: '20px Arial',
			fill: new ol.style.Fill({ color: 'red' }),
			stroke: new ol.style.Stroke({
				color: 'rgba(255,255,255,1)',
				width: 5
			}),
			text: feature.get('LABEL')
		})
	});
```
For text no lineDash is defined, but the stroke arround the text is drawn with the linedash defined before in stroke (after updating from v6.0.1 to v6.2.1).
I guess, the lineDash property of the CanvasRenderingContext2D is not restored after drawing the line and before drawing the text.

**Comment by ahocevar** [comment]
Thanks for reporting this. I created #10667 with a fix.
