### ISSUE TITLE
Openlayers 5.3.0 ol.control.OverviewMap projection issue

### ISSUE THREAD

**Issue by idlemind** [openlayers/openlayers#10668]
Hi,

I wonder if you can help me. I'm currently using openlayers 5.30. and i'm trying to implement an OverviewMap. I'm also changing the projection and i get the following error _TypeError: a is null_ in proj4.js.

Here is a sample of my code:

```javascript
//Projection definition
proj4.defs("EPSG:2157", "+proj=tmerc +lat_0=53.5 +lon_0=-8 +k=0.99982 +x_0=600000 +y_0=750000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs");
ol.proj.proj4.register(proj4);
var irishProjection = ol.proj.get('EPSG:2157');

// Create overview map control using projection
var overviewMapControl = new ol.control.OverviewMap({
    layers: [baseMap],
    view: new ol.View({
        projection: irishProjection
    }),
    collapsed: false
});

// Add overview map control to the map
var map = new ol.Map({
    target: 'map',
    layers: [baseMap],
    view: new ol.View({
        center: defaultLocation.coordinates,
        extent: defaultExtent,
        projection: irishProjection,
        zoom: defaultLocation.zoom,
        minZoom: 9
    }),
    controls: ol.control.defaults().extend([
        overviewMapControl
    ])
});
```

As you can see above. Both the map and the overview map use the same projection. I do not get any problems using the map, as soon as i remove the overview map control i no longer see any error messages.

Any help is much appreciated

**Comment by AugustusKling** [comment]
Don't reuse the same layer (`baseMap` variable) for the map and the overview map. Try creating independent layer instances.

Example with Irish Projection: https://stackblitz.com/edit/typescript-liwrsh
