### ISSUE TITLE
Overview map wrong unless using same projection than main map.

### ISSUE THREAD

**Issue by AugustusKling** [openlayers/openlayers#10670]
**Describe the bug**
The OverviewMap control assumes the overview map uses the same projection than the main map. However it defaults to using EPSG:3857 regardless of the main map's view.
Thusly, the overview map shows the wrong location whenever the view projections mismatch.

**To Reproduce**
Working example where main map and overview map use EPSG:2157 as compiled for #10668 is in https://stackblitz.com/edit/typescript-liwrsh

Broken example where main map shows Ireland but overview map shows Nigeria: https://stackblitz.com/edit/typescript-iwnndr

The difference between the examples is the specification of the projection for the overview map (or lack thereof).

**Expected behavior**
Overview map should:
1.  default to using projection of main map instead of EPSG:3857,
2. transform coordinates if projections of main map and overview map differ.

The transformation could maybe done by simply transforming the center coordinate in https://github.com/openlayers/openlayers/blob/v6.2.1/src/ol/control/OverviewMap.js#L429 but this is just a guess. I didn't look into it in detail.

Similar issues raised earlier:
* #2998
* #5188

**Comment by mike-000** [comment]
It should certainly default to the main projection.  Handling different projections might be quite complex.  Differences in projection units would affect the resolutions needed, and even if the projections used the same units the point resolutions might be very different, especially at high latitudes.

**Comment by AugustusKling** [comment]
@mike-000, handling different projection for the main map and the overview map is indeed quite complex and maybe lacks useful applications in practice, too.

I've implemented it such that it makes the overview map default to the same projection as used by the main map. In case the view of the main map changes, the overview map will adapt. This should make it obsolete to specify the view in most cases.

The option to explicitly specify a view for the overview map remains so that existing code won't change it's behavior.

**Comment by AugustusKling** [comment]
@tschaub, I don't see how this ticket is closed with merging #10676. That PR only documents that the same projection for the overview map and main map must be used but doesn't change the behavior in any way. But the fix should be not defaulting to EPSG:3857 for the overview map regardless of the main map's projection.

That change of default behavior is included in #10692. I've had a brief look at the report of the failed build but can't see how the changes in the PR could prevent your CI tool from starting Chrome as part of the CI build.
Can you please check https://circleci.com/gh/openlayers/openlayers/3239 and let me know if you think the failure could be related to the code in the PR and if so how?

**Comment by mike-000** [comment]
Yes, deferring setting the view until it needs to be bound gets around the problem of the projection not being known to the constructor.

There is currently a recurring problem with CircleCI randomly affecting tests.  Any changes you make will start a new attempt (e.g. you could rebase to fix the comment conflict introduced by merging my change).
