### ISSUE TITLE
Graticule labels misplaced in rotated view

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10673]
**To Reproduce**
Open the Map Graticule example and rotate the view.  Only one label per axis is fully visible, the others are positioned at the hidden edge of the rotated convas instead of the edge of the viewport.

**Expected behavior**
Labels should be positioned where meridians and parallels intersect the edge of the viewport.

**Comment by ahocevar** [comment]
I agree it would be nice to have graticule labels that work with rotated views.
