### ISSUE TITLE
ol.layer.Vector.getFeatures(pixel) sometimes doesn't detect features

### ISSUE THREAD

**Issue by oleg-derevenetz** [openlayers/openlayers#10685]
**Describe the bug**
When calling getFeatures(pixel) on a Vector layer, sometimes it will not return the feature that intersects the given pixel. The issue is not consistently seen.

**To Reproduce**
1. Open the web page that demonstrates the issue: https://vkgeo.github.io/ol_test/
2. Zoom in/zoom out map, scroll map back and forth, hovering the mouse cursor over the features. Usually a tooltip is displayed on hover, but sometimes it does not appear for some features.

**Expected behavior**
A tooltip should be displayed for all features in all situations.

This issue looks very similar to https://github.com/openlayers/openlayers/issues/10299, but it is observed with 6.2.1 (although not observed with 6.1.0).

**Comment by ahocevar** [comment]
Thanks for reporting. #10691 fixes this issue.
