### ISSUE TITLE
How to get VectorTile features inside a polygon

### ISSUE THREAD

**Issue by matuisti** [openlayers/openlayers#10686]
**Describe the bug**
Is there a way to get all VectorTile features inside a polygon?
As this VectorLayer function does: getFeaturesInExtent().
I using openlayers version 5.3.

Is it possible?

**Comment by ahocevar** [comment]
You'll have to upgrade to OpenLayers >= v6.2.0. Then you can use [ol/source/VectorTile#getFeaturesInExtent()](https://openlayers.org/en/latest/apidoc/module-ol_source_VectorTile-VectorTile.html#getFeaturesInExtent). Make sure to read the description and understand its implications:

> Get features whose bounding box intersects the provided extent. Only features for cached tiles for the last rendered zoom level are available in the source. So this method is only suitable for requesting tiles for extents that are currently rendered.
> 
> Features are returned in random tile order and as they are included in the tiles. This means they can be clipped, duplicated across tiles, and simplified to the render resolution.

**Comment by matuisti** [comment]
I updated ol to 6.2.0 version and found a problem when I try to drag the map it doesn't move or zoom in any way.
I use WebComponent implementation for the map frame. 
If i downgrade ol version to 6.1.0, then drag events working correctly.

here's an example code:

`<html>

<head>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.1.0/build/ol.js"></script>
</head>

<body>
    <ol-map></ol-map>

    <script>
        class OLComponent extends HTMLElement {
            connectedCallback() {
                this.shadow = this.attachShadow({ mode: 'open' });
                this.render();
            }

            displayMap(div, overlayDiv) {
                const layer = new ol.layer.Tile({
                    source: new ol.source.OSM()
                });

                const map = new ol.Map({
                    layers: [layer],
                    target: div,
                    view: new ol.View({
                        center: [0, 0],
                        zoom: 2
                    })
                });

                const overlay = new ol.Overlay({
                    stopEvent: true,
                    insertFirst: true,
                    element: overlayDiv
                });

                map.addOverlay(overlay);

                map.on('singleclick', function (e) {
                    overlay.setPosition(e.coordinate);
                    overlay.element.innerHTML = '<div style="padding: 10px; background: #fff;">Testing</div>';
                });
            }

            render() {
                const div = document.createElement('div');
                div.classList.add('map');
                div.style.width = '600px';
                div.style.height = '300px';
                this.shadow.appendChild(div);

                const link = document.createElement('link');
                link.rel = 'stylesheet';
                link.type = 'text/css';
                link.href = 'https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v6.2.0/css/ol.css';
                this.shadow.appendChild(link);

                const overlay = document.createElement('div');
                this.shadow.appendChild(overlay);

                this.displayMap(div, overlay);
            }
        }

        customElements.define('ol-map', OLComponent);

    </script>
</body>

</html>`

**Comment by ahocevar** [comment]
@matuisti That's a different issue. See #10162.
