### ISSUE TITLE
Cannot read property 'usedTiles' of null

### ISSUE THREAD

**Issue by nodejayes** [openlayers/openlayers#10689]
We using Openlayers in a Angular 8 Application and use the Bing Layer with some Vector Layers.
Most of the Time all works fine but sometimes we get the following Error:

[Error: TypeError: Cannot read property 'usedTiles' of null
    at http://127.0.0.1:9030/vendor.js:368782:49
    at Map.push../node_modules/ol/PluggableMap.js.PluggableMap.handlePostRender (http://127.0.0.1:9030/vendor.js:337194:35)
    at ZoneDelegate.invokeTask (http://127.0.0.1:9030/polyfills.js:3670:35)
    at Object.onInvokeTask (http://127.0.0.1:9030/vendor.js:71918:33)
    at ZoneDelegate.invokeTask (http://127.0.0.1:9030/polyfills.js:3669:40)
    at Zone.runTask (http://127.0.0.1:9030/polyfills.js:3437:51)
    at ZoneTask.invokeTask (http://127.0.0.1:9030/polyfills.js:3752:38)
    at ZoneTask.invoke (http://127.0.0.1:9030/polyfills.js:3741:52)
    at timer (http://127.0.0.1:9030/polyfills.js:6280:33)]

This points to following Code Line in our vendor.js (ol/renderer/canvas/TileLayer.js in Openlayers)

```javascript
/**
     * @param {import("../../PluggableMap.js").FrameState} frameState Frame state.
     * @param {import("../../source/Tile.js").default} tileSource Tile source.
     * @protected
     */
    CanvasTileLayerRenderer.prototype.scheduleExpireCache = function (frameState, tileSource) {
        if (tileSource.canExpireCache()) {
            /**
             * @param {import("../../source/Tile.js").default} tileSource Tile source.
             * @param {import("../../PluggableMap.js").default} map Map.
             * @param {import("../../PluggableMap.js").FrameState} frameState Frame state.
             */
            var postRenderFunction = function (tileSource, map, frameState) {
                var tileSourceKey = getUid(tileSource);
// HERE THE frameState is null
                if (tileSourceKey in frameState.usedTiles) {
                    tileSource.expireCache(frameState.viewState.projection, frameState.usedTiles[tileSourceKey]);
                }
            }.bind(null, tileSource);
            frameState.postRenderFunctions.push(
            /** @type {import("../../PluggableMap.js").PostRenderFunction} */ (postRenderFunction));
        }
    };
```

I also think checking the frameState might solve the problem... What do you think?

```javascript
    if (frameState && tileSourceKey in frameState.usedTiles) {
                    tileSource.expireCache(frameState.viewState.projection, frameState.usedTiles[tileSourceKey]);
                }
```

**Comment by ahocevar** [comment]
Make sure you call `map.setTarget(null)` when you unmount the map. That will take care of unregistering the postrender timeout.

**Comment by nodejayes** [comment]
Thank you very much for your efforts,

We have decided not to destroy the map instance anymore but to hide it.

But I'm sure your solution will work.
