### ISSUE TITLE
UTM projections in Graticule labels

### ISSUE THREAD

**Issue by leofcj** [openlayers/openlayers#10696]
The current Map Graticule example displays the labels in LongLat values due to the default projection.
Although I would like to display these values in an UTM projection, e.g. EPSG: 31982. 

I have a code here: [This merges the reprojection-by-code and map-graticule examples](https://codesandbox.io/s/reprojection-by-codegraticule-qbyft)

I want this: 
![current](https://user-images.githubusercontent.com/52462466/74755674-406e7c80-5252-11ea-8aae-97c58494a848.png)

To become this:
![wanted](https://user-images.githubusercontent.com/52462466/74755696-46fcf400-5252-11ea-9450-a6e32883e472.jpg)

**Comment by mike-000** [comment]
The documentation needs improving as it completely fails to mention that the view projection must have both an extent _**and**_ world extent.

"**Layer that renders a grid for a coordinate system**" is misleading as currently the only coordinate system is EPSG:4326 which is hardcoded in `ol/layer/Graticle`, `ol/geom/flat/geodesic.meridian` and `ol/geom/flat/geodesic.parallel`.

There seems to be no reason why an option to base a graticule on coordinate system for other projections should not be possible with a few changes (e.g. the default intervals would not be appropriate for projection units other than degrees, nor would world extent be suitable for use in graticules which are not based on degrees).

**Comment by dehmer** [comment]
Supporting UTM independent of map projection would be much appreciated.
I guess for UTM a fixed zone might be a Graticule option. Automatically using the nearest zone from map center could be useful.

I will also look into it, provided I find the time.

**Comment by Sagie501** [comment]
I am also looking for UTM support, hope it will be added soon :)

**Comment by Centinela2go** [comment]
Do you know if you managed to make the grid of the images shown?

**Comment by yejiyang** [comment]
any progress on this issue?

**Comment by kernant** [comment]
upvoted!
