### ISSUE TITLE
String references to colors not accepted when creating RegularShapes during unit-tests (v6.2.1)

### ISSUE THREAD

**Issue by Pick-Jack** [openlayers/openlayers#10695]
Found when trying to create an instance of CircleStyle with a color string (i.e. black, blue, red etc.) as the color property for the Fill object. Traced the issue to the color.js file, specifically the fromNamed function, where the returned value is not an rgba string as it should be but rather the color string that was passed in. 

This may be a context issue as it was identified while running unit-tests and seems to successfully map a color string to an rgba value when executed from a browser. The issue therefore being when executed from a unit-test, there is no browser instance doing the mapping of the color property for the programmatically generated div element in the fromNamed function, which therefore returns the string when it is retrieved from the element properties.

**To Reproduce**
const imageStyle = new CircleStyle({
          radius: 7,
          fill: new Fill( { color: 'black' } ),
          stroke: new Stroke( { color: [255, 0, 0], width: 2 } )
});

**Comment by sambakk** [comment]
I tried it, it's working for me with your code.
