### ISSUE TITLE
GML 3.2.1 can't be parsed by ol.format.GML32

### ISSUE THREAD

**Issue by thanhdn1989** [openlayers/openlayers#10700]
**Describe the bug**
Getting the GML 3.2.1 response from a WFS 2.0 and using GML32 to parse to feature, but it always return null.

**To Reproduce**
1. using this GML response:
`<?xml version="1.0" encoding="UTF-8"?>
<wfs:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:dagi="http://data.gov.dk/schemas/dagi/2/gml3sfp" 
    xmlns:gml="http://www.opengis.net/gml/3.2" 
    xmlns:xlink="http://www.w3.org/1999/xlink" 
    xmlns:gmd="http://www.isotc211.org/2005/gmd" 
    xmlns:gco="http://www.isotc211.org/2005/gco" 
    xmlns:gss="http://www.isotc211.org/2005/gss" 
    xmlns:gts="http://www.isotc211.org/2005/gts" 
    xmlns:gsr="http://www.isotc211.org/2005/gsr" 
    xmlns:adr="http://data.gov.dk/schemas/adresse/0/gml3sfp" 
    xmlns:wfs="http://www.opengis.net/wfs/2.0" 
    xmlns:ows="http://www.opengis.net/ows/1.1" 
    xmlns:fes="http://www.opengis.net/fes/2.0" 
    xsi:schemaLocation="http://data.gov.dk/schemas/dagi/2/gml3sfp http://schemas.datafordeler.dk/schemas/1.0.0/DAGI_2000MULTIGEOM_GMLSFP/dagi_gml3sfp.xsd http://data.gov.dk/schemas/adresse/0/gml3sfp http://schemas.datafordeler.dk/schemas/1.0.0/DAGI_2000MULTIGEOM_GMLSFP/adresse_gml3sfp.xsd http://www.opengis.net/gml/3.2 http://schemas.opengis.net/gml/3.2.1/gml.xsd http://www.opengis.net/wfs/2.0 http://schemas.opengis.net/wfs/2.0/wfs.xsd" timeStamp="2020-02-19T03:20:09" numberMatched="1" numberReturned="1">
    <wfs:member>
        <dagi:Kommuneinddeling gml:id="dagi.1700389194">
            <dagi:id.namespace>http://data.gov.dk/dagi2000k</dagi:id.namespace>
            <dagi:id.lokalId>1700389194</dagi:id.lokalId>
            <dagi:status>vedtaget</dagi:status>
            <dagi:geometristatus>endelig</dagi:geometristatus>
            <dagi:virkningFra>2019-08-09T00:00:00.000+02:00</dagi:virkningFra>
            <dagi:virkningsaktoer>SDFE</dagi:virkningsaktoer>
            <dagi:forretningshaendelse>DAGIajourføring</dagi:forretningshaendelse>
            <dagi:registreringFra>2019-08-09T16:10:09.000+02:00</dagi:registreringFra>
            <dagi:registreringsaktoer>SDFE</dagi:registreringsaktoer>
            <dagi:forretningsomraade>52.20.20.27</dagi:forretningsomraade>
            <dagi:forretningsproces>DAGIafledning</dagi:forretningsproces>
            <dagi:navn>Aarhus</dagi:navn>
            <dagi:redigeringsret>SDFE</dagi:redigeringsret>
            <dagi:dataspecifikation>DAGI Objektspecifikation version 2.0</dagi:dataspecifikation>
            <dagi:landekode>DK</dagi:landekode>
            <dagi:skala>1:2.000.000</dagi:skala>
            <dagi:udtraeksdato>2020-02-19T03:20:09</dagi:udtraeksdato>
            <dagi:geometri>
                <gml:MultiSurface srsName="urn:ogc:def:crs:EPSG::25832" gml:id="LOCAL_ID_0">
                    <gml:surfaceMember>
                        <gml:Polygon srsName="urn:ogc:def:crs:EPSG::25832" gml:id="LOCAL_ID_1">
                            <gml:exterior>
                                <gml:LinearRing>
                                    ....
                                </gml:LinearRing>
                            </gml:exterior>
                        </gml:Polygon>
                    </gml:surfaceMember>
                </gml:MultiSurface>
            </dagi:geometri>
            <dagi:kommunekode>0751</dagi:kommunekode>
            <dagi:LAU1vaerdi>751</dagi:LAU1vaerdi>
            <dagi:udenforKommuneinddeling>false</dagi:udenforKommuneinddeling>
            <dagi:regionskode>1082</dagi:regionskode>
            <dagi:regionsLokalId>1700389101</dagi:regionsLokalId>
            <dagi:region xlink:href="http://data.gov.dk/dagi2000k#1700389101"/>
        </dagi:Kommuneinddeling>
    </wfs:member>
</wfs:FeatureCollection>`
2. Try:
`
var parser = new ol.format.GML32({
                featureType: 'Kommuneinddeling',
		featureNS: 'http://data.gov.dk/schemas/dagi/2/gml3sfp'
});
var feature = parser.readFeature(sampleGML);
`
3. See error
feature = null

**Expected behavior**
feature should be parse correctly

**Comment by thanhdn1989** [comment]
This is because the GML32.prototype.GEOMETRY_FLAT_COORDINATES_PARSERS did not contains the definition for coordinates .

**Comment by AlexanderKoch97** [comment]
So how did you achieve to solve this? Or did you just leave it like that?
I kinda got the same problem, even using your given example GML.
