### ISSUE TITLE
Support zIndex on WebGLPointsLayer

### ISSUE THREAD

**Issue by jellyedwards** [openlayers/openlayers#10705]
**Is your feature request related to a problem? Please describe.**
The non-WebGL layers and the previous WebGL implementation supported zIndex ordering the features so some would always appear on top of others. For example I'd like the green icon here to appear on top of the black icons:

![image](https://user-images.githubusercontent.com/14051992/74857591-ca464480-533b-11ea-8f41-15d82cc45af5.png)

However I don't see any way of specifying the zIndex in the LiteralStyle...

**Describe the solution you'd like**
Something like:

```
const webGLStyle = {
...
    zIndex: ['get', 'zIndex']
...
};
```

on the literal style to allow zIndex ordering of points.

Thanks!!

**Comment by jahow** [comment]
Duplicate of https://github.com/openlayers/openlayers/issues/10634

**Comment by jellyedwards** [comment]
Sorry I did search but didn't find that one
