### ISSUE TITLE
Map interaction on 6.2.0 and 6.2.1 not working properly

### ISSUE THREAD

**Issue by JuanCasado** [openlayers/openlayers#10712]
Map interactions do not work, when the map is clicked in order to drag it nothing happens, also zoom with both trackpad and mouse is not working.
I tried to add the corresponding interactions to the map manually with defaults.extend but did not solve the problem.

Finally I switch back to version 6.1.1 and everithing worked as intended.

Create a simple map (like the one in the [example](https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html)) in both versions.
The one in 6.1.1 is able to zoom in and the one in 6.2.0 or 6.2.1 is not.
I am using a mac laptop with safari.

**Comment by richnic** [comment]
Do you have ol/ol.css from v6.2.0 or v6.2.1 included in your build or html page? - See #10663.

**Comment by JuanCasado** [comment]
That was the problem, thanks a lot
