### ISSUE TITLE
update example with BS popover

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#10719]
HI

Just to update this example : https://openlayers.org/en/latest/examples/icon.html?q=icon

update the bootstrap call and use

I made this where you can check
https://codesandbox.io/s/icon-rwlbp

if interesting i make a PR  ...

Thanks

**Comment by mike-000** [comment]
There is a problem with that version.  When you zoom the map the overlay doesn't move with the icon

![image](https://user-images.githubusercontent.com/49240900/75063285-80e12b00-54dc-11ea-9377-e90cc0dfe6e7.png)

**Comment by jipexu** [comment]
oh yes ..

**Comment by jipexu** [comment]
[here](https://codesandbox.io/s/icon-rwlbp)  is a new working  version  (not use of popover)
i try some hours but i am still unable to use popover with the new BS version  
(i always have this zoom probleme) ...

**Comment by mike-000** [comment]
If you are not using bootstrap you don't need jquery https://codesandbox.io/s/icon-z8g0o

**Comment by jipexu** [comment]
yes sure 
so that means this example and (probably) this [one] (https://openlayers.org/en/latest/examples/overlay.html) will not work with recent version of BS ... 
i willl check for the second example
