### ISSUE TITLE
Bug in Example of CodeSandbox

### ISSUE THREAD

**Issue by gabriell273** [openlayers/openlayers#10714]
today, I went to see the example of LineString Arrows, on the OpenLayers website it works perfectly, but in the codesandbox the arrows are not placed on the lines

[Exemple of OpenLayers](https://openlayers.org/en/latest/examples/line-arrows.html)

[Example of CodeSandbox](https://codesandbox.io/s/p2ty0)

**Comment by ahocevar** [comment]
The problem is that relative `data/` paths are not converted to absolute paths or data resources when sending the code to the codesandbox.

**Comment by mike-000** [comment]
This was fixed by #11569
