### ISSUE TITLE
rawgit.com is being shutdown

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#10716]
**Describe the bug**

https://rawgit.com/

> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
> 
> GitHub repositories that served content through RawGit within the last month will continue to be 
> served until at least October of 2019. URLs for other repositories are no longer being served.
> 
> If you're currently using RawGit, please stop using it as soon as you can.

**To Reproduce**
1. Go to https://openlayers.org/download/
2. See code in section "Hosted builds for development"
3. See link to rawgit.com

**Comment by mike-000** [comment]
See #9082  It looks like that page was missed

**Comment by fredj** [comment]
Thanks for the bug report, will be fixed with https://github.com/openlayers/openlayers.github.io/pull/104
