### ISSUE TITLE
Missing Icons in Chrome

### ISSUE THREAD

**Issue by Kai-W** [openlayers/openlayers#10718]
I have a wierd bug with multiple icons as dataURL in Chrome:
https://codesandbox.io/s/jolly-oskar-9yn41
In the provided Example some icons are missing  (each feature has a circle style and an image style)
![image](https://user-images.githubusercontent.com/1429148/75023944-eca1a480-5498-11ea-91eb-4bd717048f0b.png)
The icons are correctly generated and added to the DOM as image.
In Firefox it works as expected
![image](https://user-images.githubusercontent.com/1429148/75033453-3c896700-54ab-11ea-90c1-deedb43b6f41.png)
And if i use img:canvas instead of src: dataURL to create the Icon Style it works fine as well.

**Comment by mike-000** [comment]
Your codesandbox is working on Chrome for me.  Have you tried Chrome on other devices?  It might be related to how much memory is available to the browser.

![image](https://user-images.githubusercontent.com/49240900/75038920-66448d00-54af-11ea-8e0a-8e8220081491.png)

**Comment by Kai-W** [comment]
I tested it on multiple Devices wit Chrome "Version 80.0.3987.116 (64-Bit)" and each System had at least 8GB of free System Memory. 
The CodeSandbox tab is using ~550MB of Memory according to the Chrome TaskManager (maxsize in chrome 64bit should be 4GB, and i testet with bigger tabs)
I thought about a memory problem too, but then the images shouldn't be visible in the HTML DOM as images too. They use the same dataURL and it works fine.

**Comment by Kai-W** [comment]
It works in Openlayers 5.3.3
https://codesandbox.io/s/dry-framework-r75n9

**Comment by Kai-W** [comment]
in ol/Image/listenImage an Error is caught: "DOMException: The source image cannot be decoded."
But the image src dataUrl is valid.

**Comment by Kai-W** [comment]
It looks like an Chrome Bug: I reproduced it without any libraries:
https://codesandbox.io/s/happy-gagarin-j1vjr

**Comment by Kai-W** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1055828
