### ISSUE TITLE
Unable to pan in Chrome

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#10724]
**Describe the bug**
I am unable to pan or click in latest Openlayers on Windows XP (Chrome version 49.0.2623.112).  Please note that some of my clients still uses XP with this version of Chrome.  This used to work 100% on older versions of Openlayers.

**To Reproduce**
Load openlayers in older version of Chrome and try to pan / click.

**Expected behavior**
Map needs to pan and accept clicks.

**Comment by fredj** [comment]
Maybe related to  #10712: please make sure you have ol/ol.css from v6.2.1 included in your build or html page.

**Comment by 1Map** [comment]
Same versions of js and css are in use, but still not working.

**Comment by 1Map** [comment]
Maybe it is a cache issue.  I will investigate further.

**Comment by 1Map** [comment]
No, definitely not a cache issue.  On XP it works on Firefox, but not in Chrome.

**Comment by ahocevar** [comment]
That’s a pre pointer events version of Chrome. Maybe elm-pep, the polyfill we use now, does not work with that old Chrome Version. You may need to load [PEP](https://github.com/jquery/PEP) before ol.js.

**Comment by 1Map** [comment]
Thanks, that did the trick.
