### ISSUE TITLE
Can't get map object from start drawing event

### ISSUE THREAD

**Issue by vishnu4** [openlayers/openlayers#10731]
**Describe the bug**
This works with ol 6.1.1, but it broken with version 6.2.X , but when i try to draw a point on my map i get the error " Cannot read property 'getView' of undefined"

**To Reproduce**
I have a simple map where i add drawing to my map like so:

```
const coords = fromLonLat([lon, lat]);
mapObj.addInteraction(draw);
draw.startDrawing_({ coordinate: coords });
draw.addToDrawing_({ coordinate: coords });
draw.finishDrawing();
```

and this works fine in 6.1.1 and previous versions, but when i upgrade to 6.2.x i get the error above in ol/interaction/Draw.js:

```
Draw.prototype.startDrawing_ = function (event) {
        var start = event.coordinate;
        var projection = event.map.getView().getProjection();
```
where the event.map object is undefined.  

**Expected behavior**
i expect the event passed to the startdrawing function to have a valid map defined inside it.

**Comment by ahocevar** [comment]
Note that `Draw#startDrawing_` is not part of the API and private. Please don't rely on it in applications.

**Comment by vishnu4** [comment]
@ahocevar yeah, whoops.  that is my bad.  Thanks!

**Comment by vishnu4** [comment]
@ahocevar i know that this has been a while since i closed this, but apparently it was being used this way because i wanted to add a drawing point programmatically, like https://gis.stackexchange.com/questions/256376/how-to-programmatically-start-drawing-in-openlayers-4 .  Is there another/new way to do this now?
