### ISSUE TITLE
documentation error, constrainCenterOnly vs constrainOnlyCenter

### ISSUE THREAD

**Issue by rgreenwood** [openlayers/openlayers#10737]
The 6.0 [release notes](https://github.com/openlayers/openlayers/releases/tag/v6.0.0) mention constrainCenterOnly

> Previously, this options only constrained the view center. This behaviour can still be obtained by specifying constrainCenterOnly in the view options.

But the option is actually `constrainOnlyCenter` not constrainCenterOnly.

**Comment by fredj** [comment]
Hi @rgreenwood, thanks for reporting this, it was already fixed with #10513
