### ISSUE TITLE
MVT readFeatures doesn't return complete polygon around tile border

### ISSUE THREAD

**Issue by hyuan1317** [openlayers/openlayers#10735]
**Describe the bug**
When I do MVT readFeatures, the polygon around the tile border gets cut
(seems like 100 pixels around the border)
I have tried changing the renderBuffer but there is no difference.

![Circle](https://user-images.githubusercontent.com/37610576/75214966-33a9d580-57ca-11ea-95b5-84b8c25004b2.PNG)
![top](https://user-images.githubusercontent.com/37610576/75215310-3d800880-57cb-11ea-874d-34ac50b7380a.PNG)
![bottom](https://user-images.githubusercontent.com/37610576/75215314-3f49cc00-57cb-11ea-8b67-bee8a130b17e.PNG)

**Expected behavior**
I understand that the polygon will not be displayed out of the tile,  but I want to highlight the intact polygon when hovered. 

sorry for the bad English description

**Comment by ahocevar** [comment]
The features are already cut in the tiles. To highlight features, you need to employ a technique like the one shown in https://openlayers.org/en/latest/examples/vector-tile-selection.html.

**Comment by hyuan1317** [comment]
Thanks for answering! 
Though we have plenty of layers and tons of features (might be an bad idea to clone the source),
I quite get the idea of that example and will try to work around it.

I got another question: since the circle is splitted into 3 features, there will be 3 labels on it
(if I decide to add text in style)
Is there any work around about it?
Thanks again!

**Comment by daboudii** [comment]
@hyuan1317 I'm now in a similar case as yours, need to highlight a polygon but I have plenty of source and layers. 

Have you found a solution ?
