### ISSUE TITLE
How to get Interaction Draw and Select work together

### ISSUE THREAD

**Issue by flexjoly** [openlayers/openlayers#10749]
A user can select a marker (pointer) on a map and/or draw new pointers. A new one can not be on an existing marker. 

To get this I use Draw and Select. But when Draw is enabled, Select is 'not working' anymore. I tried to find the cause to this. So far I think it is because `drawend` is triggered on `pointerup`, while Select is triggered on a `click`, which comes áfter the `pointerup`.

The Select interaction is added áfter the Draw, so Select is checked before Draw gets the event. I tried to set the `(finish)condition` in Draw to `singleclick`. But that does not help, because `finishDrawing` is handled by `handleUpEvent()`.

I am doing anything wrong here?
Or is it possible to have Select als operate on 'pointerup'? At the moment, `pointerup` is not a default `condition` so you can not just set that as you can with `click` or `singleClick`.

It would help a lot if Select could first try to select a featare and if not the event is passed to Draw.
I hope someone can help me out here. Thanks in advance.

Greetz, flexJoly

**Comment by sambakk** [comment]
Can you please share some code

**Comment by flexjoly** [comment]
Hi,

I put an sample together from the ol-examples (so forgive me the inconsistent naming etc).

I started with example: [Snap](https://openlayers.org/en/latest/examples/snap.html) 

```
var raster = new TileLayer({
  source: new OSM()
});
var iconFeature = new Feature({
  geometry: new Point([0, 0]),
  name: "test"
});

var vector = new VectorLayer({
  source: new VectorSource({
    features: [iconFeature]
  }),
  style: new Style({
    fill: new Fill({
      color: "rgba(255, 255, 255, 0.2)"
    }),
    stroke: new Stroke({
      color: "#ffcc33",
      width: 2
    }),
    image: new CircleStyle({
      radius: 7,
      fill: new Fill({
        color: "#ffcc33"
      })
    })
  })
});

var map = new Map({
  layers: [raster, vector],
  target: "map",
  view: new View({
    center: [0, 0],
    zoom: 4
  })
});

var ExampleSelect = {
  init: function() {
    this.select = new Select();
    map.addInteraction(this.select);
    this.select.setActive(true);
    this.select.on("select", selected);
  }
};

var ExampleDraw = {
  init: function() {
    map.addInteraction(this.Point);
    this.Point.setActive(true);
    this.Point.on("drawstart", startDraw);
    this.Point.on("drawend", endDraw);
  },
  Point: new Draw({
    source: vector.getSource(),
    type: "Point"
  })
};

function startDraw(e) {
 // can we do something here? to stop drawing when select is triggered?
   console.log("start draw", e);
}
function endDraw(e) {
  console.log("end draw", e,this);
  // prevent select event from triggering, but that does not work
  // because these are different triggers
  e.stopPropagation();
}
function selected(e) {
  console.log("select", e);
  // prevent draw event from triggering, but that does not work
  // because these are different triggers
  e.stopPropagation();
}

ExampleDraw.init();

// Select after draw, so it is handled before draw
// but this does NOT work, because draw is triggered on PointerDown/Up
// and select is triggered on click, which comes after pointerUp
ExampleSelect.init();

// The snap interaction must be added after the Modify and Draw interactions
// in order for its map browser event handlers to be fired first. Its handlers
// are responsible of doing the snapping.
var snap = new Snap({
  source: vector.getSource()
});
map.addInteraction(snap);

```
see working sample in [codesandbox](https://codesandbox.io/s/draw-is-handled-before-select-cg3kw) 

I hope this helps!
