### ISSUE TITLE
Issue experienced while attempting to detect "touchOnly" event

### ISSUE THREAD

**Issue by devinsimmons** [openlayers/openlayers#10759]
**Describe the bug**
I've described this bug in more detail here: 

https://stackoverflow.com/questions/60511753/why-isnt-openlayers-detecting-touch-events-from-my-laptop

Essentially my ol map object was not detecting touch events from my touch screen laptop, despite the browser detecting touches that occurred on the map container.

**To Reproduce**
- Use google chrome or microsoft edge on a touch screen laptop, add a touchOnly event handler to the ol map object, attempt touching the map using the touch screen

**Expected behavior**
I expected the touch events from my laptop to be detected by the touchOnly event handler, but they were instead picked up by the click event handler

**Comment by ahocevar** [comment]
`touchOnly` is not an event type, but a condition. You can use it to configure the `condition` options in interactions. Or you can pass an event (e.g. click) to the `touchOnly` condition function.
