### ISSUE TITLE
Android Ignored attempt to cancel a touchmove event with cancelable=false

### ISSUE THREAD

**Issue by Peter-Optiway** [openlayers/openlayers#10757]
**Describe the bug**
Can't move map while Chrome developers tools are attached.

**To Reproduce**
1. Add OpenLayers@6.2.1 to a webview in a android app.
2. Open app on phone
3. Attach chrome developer tools to the webview.
4. Try to pan the map.
5. Look in the console it spams `[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.` and the map refuses to pan.

The following code seems to cause the error
```
    /**
     * Flexible handling of a `touch-action: none` css equivalent: because calling
     * `preventDefault()` on a `pointermove` event does not stop native page scrolling
     * and zooming, we also listen for `touchmove` and call `preventDefault()` on it
     * when an interaction (currently `DragPan` handles the event.
     * @param {TouchEvent} event Event.
     * @private
     */
    MapBrowserEventHandler.prototype.handleTouchMove_ = function (event) {
        if (this.originalPointerMoveEvent_.defaultPrevented) {
            event.preventDefault(); <----
        }
    };
```

**Expected behavior**
No error should be logged and the map should be panable while developer tools are attached.

I'm running Android 8.0.0 and Chrome 80.0.3987.119

**Comment by ahocevar** [comment]
Try setting the css rule `touch-action: none` on the `target` element you are using for the OpenLayers map.

**Comment by JackD83** [comment]
> Try setting the css rule `touch-action: none` on the `target` element you are using for the OpenLayers map.

This is also fixing #10756

**Comment by danielkorosi** [comment]
Hi! Setting `touch-action: none` on the target element solved the issue functionally, but in my case the console error is still generated on touchmove. My guess is that the if condition could be extended to `this.originalPointerMoveEvent_.defaultPrevented && this.originalPointerMoveEvent_.cancelable === true`. What do you think?

**Comment by ahocevar** [comment]
Worth a try, @danielkorosi. Would you be able to create a pull request?
