### ISSUE TITLE
Select interaction with cluster

### ISSUE THREAD

**Issue by plohoj** [openlayers/openlayers#10766]
**Describe the bug**
`Select Intersection` does not preserve the style for the selected marker after rebuilding the cluster.

**To Reproduce**
1. Place a cluster on the map and add Select for this cluster. [Example](https://codepen.io/plohoj/pen/dyoVRGR?editors=0010).
2. Select any marker.
3. Zoom out map so that the cluster rebuilds.
4. No marker has a highlight style.

**Expected behavior**
The marker is expected to retain its highlight style after rebuilding the cluster.  
This worked in previous versions (5.3.3) and stopped working in the latest version (6.2.1) after updating dependencies in my project

**Comment by ahocevar** [comment]
Actually the behavior in previous versions was a bug. After re-clustering, the previously selected cluster feature is no longer in the cluster source.

**Comment by plohoj** [comment]
In this case, how do I make marker selection correctly?
I have a large number of bus stops (in prodaction). When I click on a marker cluster by a select event, I check if `Feature`'s number> 1, I clear the selection and zoom in on the map so that it captures the entire marker cluster. If `Feature`'s === 1, then I throw out the concretic bus stop selection event and the marker remains selected at any zoom.
