### ISSUE TITLE
Geolocation orientation does not work properly

### ISSUE THREAD

**Issue by pierre-josselin** [openlayers/openlayers#10760]
_Issue with **[Mobile Geolocation Tracking with Orientation](https://openlayers.org/en/latest/examples/geolocation-orientation.html)**_

**Describe the bug**
When you press the "simulate" button from a computer, or the "Geolocate Me!" button from a mobile, there is the same problem. The tracking works for about a second then the map freezes. It is then necessary to touch the map (zoom or drag) so that the tracking resumes about one second and freeze again.
While the map is blocked, tracking continues to work, so when you touch the map again you are teleported.

**To Reproduce**
1. Go to [Mobile Geolocation Tracking with Orientation](https://openlayers.org/en/latest/examples/geolocation-orientation.html).
2. Click on "simulate button".
3. The tracking works for about a second then the map freezes.

Tested with :
- Chromium and Firefox on Ubuntu Mate 18.04
- Chrome on Android 9

**Expected behavior**
I think the normal operation is that the tracking works without interruption all along the route.

**Comment by flexjoly** [comment]
I found the same (in Brave and Chrome). Also 'geolocate me' does not work for me. 
When zooming in or out, the simulation starts working again after a freeze. 

The other problem with this example I have, is that there is no code shown, like with the other examples. And looking into the code with DevTools is not very helpfull, because it is uglyfied.

**Comment by ahocevar** [comment]
#10777 fixes the simulation.

**Comment by flexjoly** [comment]
Why does this example not have the normal explanation like the other examples?

**Comment by ahocevar** [comment]
@flexjoly Because someone decided to make it fullscreen. Which it does not have to be. If you want to provide a pull request to use the example template instead, that would be welcome.
