### ISSUE TITLE
FYI: @inheritDoc produces incorrect method signatures in TypeScript

### ISSUE THREAD

**Issue by jumpinjackie** [openlayers/openlayers#10761]
**Describe the bug**

Trying out the new typings bundled with OL `6.2.2-dev.1583236579811`

Any derived class method decorated with `@inheritDoc` that involves optional parameters are generated incorrectly by the TypeScript compiler (the optionality is lost on the derived class methods)

**To Reproduce**

```ts
import LayerGroup from 'ol/layer/Group';

const group = new LayerGroup();
group.getLayersArray(); //TS error: The "opt_array" argument is required despite being documented as optional in the parent
group.getLayersArray(undefined); //Current workaround

```

**Expected behavior**

The optionality should be preserved. I've identified this as a problem in the TypeScript compiler's JSDoc processing and have filed an appropriate issue there: https://github.com/microsoft/TypeScript/issues/37210

I don't know if this issue can be reliably fixed/worked-around downstream.

This issue is more a reminder if/when this issue is fixed upstream, that you should adopt the next version of TypeScript that has the fix incorporated.

**Comment by jumpinjackie** [comment]
An update for those affected: I found a workaround for such incorrect signatures. Basically call the method through the facade of its base class. So in the case of `LayerGroup` above, the following fragment will not produce TS errors.

```ts
import LayerGroup from "ol/layer/Group";
import BaseLayer from "ol/layer/Base"; //LayerGroup extends BaseLayer

const group = new LayerGroup();
(group as BaseLayer).getLayersArray(); //Call the method through BaseLayer instead of LayerGroup
```

This has no effects on JS code emit, the resulting JS will still be the same

**Comment by ahocevar** [comment]
I think it might be worthwhile replacing all `@inheritDoc` annotations we have in the library with copies of the params/return annotations from the parent. That way, IntelliSense for library developers would also work better.

Anyone willing to provide a pull request?
