### ISSUE TITLE
Cloning a vector layer in Openlayers 6

### ISSUE THREAD

**Issue by panuchka** [openlayers/openlayers#10764]
**Describe the bug**
I have a use case where I create vector layers and store them in an array. An Openlayers map instance can then ask for the layer with specified id. Previously I've just cloned the layer using Lodash (cloneDeep function https://lodash.com/docs/4.17.15#cloneDeep).

This has worked well in past. However, after Openlayers version 6.0.0.-beta.15, something has been changed and this has something to do with Select interaction. I use click and hover interaction similarly to this issue #10501. When using any version above beta 15 and cloning vector layer with cloneDeep, the styles are not updating correctly on hover and click. You need to zoom in/out or move the map to actually update it. 

And about styling; my use case takes the cloned layer, then after that adds all the styles into it.

So, my questions are:
a) What is a correct way to clone a layer if one does not use cloneDeep?
b) Is this something that needs to be fixed or is using cloneDeep a big no no?
c) Why is this happening

**To Reproduce**
1. Enter this code sandbox (note: using the latest) https://codesandbox.io/s/select-features-k5j31
2. Try to click or hover over features (move the map a bit so feature styles appear)
3. See that styles are not updating
4. Comment line 91, uncomment line 88
5. See that everything works if cloneDeep is not used

**Expected behavior**
After a vector layer has been cloned, Select interactions work as usual (hover and click).

**Comment by AlexanderKoch97** [comment]
I'am not that experienced yet, but I think cloneDeep is not a good choice for that.

Starting with the fact, that the vector itself and even the source has the unique _ol_uid_-attribute, could end up in problems with some actions, e. g. the Select-interaction. Not quite sure if that is crucial in that case, but _unique-ids_ should be unique, right?

a) I just got it working by cloning the layer by its properties.

Just edit the line 
`var clonedVectorLayer = cloneDeep(vector);`
to
`var clonedVectorLayer = new VectorLayer(vector.getProperties());`.
Seems working fine for me. 

b) I think cloneDeep is a big no no, just of the _ol-uid_-fact.

c) I can't tell why it worked past ol6.beta15. Just wanted to show my opinion, that cloneDeep is not a good approach for this.

PS: You also need to set your default-style (the grey one) on the cloned layer.

**Comment by panuchka** [comment]
Yeah, I can see that the cloneDeep is not a good solution, since Openlayers clearly uses the unique ids for some internal stuff... Oh boy 😄 

But in my case, "cloning" the vectorlayer with just  `new VectorLayer(vector.getProperties());.` is not enough. If I have two map instances and they use the same, "cloned" vector layer, both maps show hover/click simultaniously. Here is a demo: https://codesandbox.io/s/select-features-seoot

What I want to happen is to have separate selections(click/hover) for each map (so that is why I need unique vector layers, I presume).

**Comment by AlexanderKoch97** [comment]
You are right, they actually hold the same VectorSource if you do it like this.
So I just would do it like this, cloning the sources like the layers (with the .getProperties()-thing) did not work for me.

    var originalSource = new VectorSource({
      url: "data/geojson/countries.geojson",
      format: new GeoJSON()
    })

    var sourceClone1 = new VectorSource({
      url: "data/geojson/countries.geojson",
      format: new GeoJSON()
    })

    var sourceClone2 = new VectorSource({
      url: "data/geojson/countries.geojson",
      format: new GeoJSON()
    })

    var vector = new VectorLayer({
      source: originalSource
    });

    var clonedVectorLayer1 = new VectorLayer(vector.getProperties());
    clonedVectorLayer1.setSource(sourceClone1);

    var clonedVectorLayer2 = new VectorLayer(vector.getProperties());
    clonedVectorLayer2.setSource(sourceClone2);

Or even create a function that creates you a new source, so you dont have the 

    new VectorSource({
      url: "data/geojson/countries.geojson",
      format: new GeoJSON()
    })

3 times

    function getNewSource(url) {
        return new VectorSource({
            url,
            format: new GeoJSON()
        })
    }

    var vector = new VectorLayer({
        source: getNewSource('data/geojson/countries.geojson')
    });

    var clonedVectorLayer1 = new VectorLayer(vector.getProperties());
    clonedVectorLayer1.setSource(getNewSource('data/geojson/countries.geojson'));

    var clonedVectorLayer2 = new VectorLayer(vector.getProperties());
    clonedVectorLayer2.setSource(getNewSource('data/geojson/countries.geojson'));

Hope that is correct and helps you.
If you now want, that you can select/hover one feature on map 1 and one feature on map 2, you have to create separate Select-interactions for both maps.
If you keep it like this, you just can select/hover one feature on both maps.

**Comment by panuchka** [comment]
This might be doable with a simple vector layer / source reinitializing, but in my case I have a VectorLayer with VectorSource that has 1-1000 features already in it. I would just like to "clone" these VectorLayers and add the individual Select interactions to these. If they are not individual, we will have some problems, since two maps with same layers cause weird situations.

I made a codesandbox to illustrate the problem more. This is a Vue.js application that holds three Openlayers map instances. The map instances reuse the same vector layer (or at least try to 😛). I tried to clone the layer from scratch at line 265 of Map.vue (components folder).
https://codesandbox.io/s/autumn-shadow-s1pyx

I would **really** like to know how the Openlayers contributors/creators would solve this problem. It is a bit mind-boggling to think that there isn't a feature to clone vector layers/sources in this manner (or maybe I missed something crucial).

**Comment by ahocevar** [comment]
I'm the core developer who wasted way too much time on the Select interaction already, without ever having used it in own applications.

I'd do the following:

* Create two vector layers
* Give both vector layers the same source
* For each map, use `map.getFeaturesAtPixel` to get clicked/hoveed features in a click/pointermove listener
* Store the id of the clicked/hovered feature
* Use layer style functions that style the features differently when clicked/hovered

See https://codesandbox.io/s/new-star-w95bv.

**Comment by panuchka** [comment]
I understand it may be frustrating, considering the flood of requests and weird "how to do this and that" -questions without proper code examples. Thank you for catering our needs ❤️ 

Anyway **if someone is reading this in the future, there are couple of different options you can do to clone a layer and ensure individual interactions with click/hover for example:**

1. Do not use the Select -interaction at all and use the `map.getFeaturesAtPixel` as Ahocevar instructed in the post above. https://github.com/openlayers/openlayers/issues/10764#issuecomment-596259650
2. Use the Select interaction. For this, you need to "clone" the layer using the original data. This means that you have to create new VectorLayers, VectorSources and Features from scratch with the original data. If you need to store some data, do not store VectorLayers and try to copy/clone them. Instead, store the actual raw data. https://github.com/openlayers/openlayers/issues/10764#issuecomment-595184159

I went with the option 2 in my use case, since I really wanted to use the Select interaction because of it's simplicity.

Closing this issue for now.
