### ISSUE TITLE
Wrong area measure using iiif image api

### ISSUE THREAD

**Issue by marquetd** [openlayers/openlayers#10765]
**Describe the bug**
feature.getGeometry().getArea() does not provide the good measure using iiif image example.

**To Reproduce**
I try to measure distance and area following examples :
https://openlayers.org/en/latest/examples/iiif.html
https://openlayers.org/en/latest/examples/measure.html

I get the right length measure using : 
```
const onDrawEnd = e => {
  const feature = e.feature;
  const geom = feature.getGeometry();
  const length = geom.getLength();
  const mpu = projection.getMetersPerUnit();
  const value = length * mpu; //good value
}
```

But for the area, i don't know how to do : 

```
const onDrawEnd = e => {
  const feature = e.feature;
  const geom = feature.getGeometry();
  const area= geom.getArea();
  const mpu = projection.getMetersPerUnit();
  const value = area * mpu; //bad value
}
```

The view projection is : 
```
const projection = new Projection({
  code: 'ZOOMIFY',
  units: 'PIXELS',
  metersPerUnit,
  getPointResolution: a => a,
  extent: [0, 0, imageInfo.width, imageInfo.height]
});
```

**Expected behavior**
geom.getLength() provide the good value (without having to multiply by mpu)
geom.getArea() provide the good value

**Comment by mike-000** [comment]
getLength and getArea return results in the same units the geometry coordinates (which will be the projection you are drawing in).  If that is not meters and you want meters it is normal to multiple by mpu (mpu squared for area).
