### ISSUE TITLE
[Question] Why heatmap view properties are in layer object?

### ISSUE THREAD

**Issue by bayramucuncu** [openlayers/openlayers#10776]
**Why Heatmap layer object includes the view options?**
Heatmap layer object has view properties named `radius `and `blur` etc.

**My suggestion**
I think it would be better to have these features in a `Source `object named `ol/source/heatmap`. So we can use the `ol/layer/vector` for Heatmap instead of `ol/layer/heatmap`. May be a clear solution. (For example, cluster has not its own layer object, but has own source.)

Actually, I noticed this while developing an application that generate layers using web UI.

**Comment by mike-000** [comment]
Heatmap and Cluster now work very differently.  `ol/layer/Heatmap` applies a custom WebGL based renderer to a vector source (comparable to how `ol/layer/Vector` determines how a source is rendered based on the layer's `style` property), while `ol/source/Cluster` simply generates a new intermediate source containing clusters from a standard vector source which can then be styled and rendered as required just like any other vector source.  A heatmap layer might even be used to render a cluster source https://codesandbox.io/s/heatmap-earthquakes-wkipv
