### ISSUE TITLE
Support for native javascript eventListener.handleEvent()

### ISSUE THREAD

**Issue by flexjoly** [openlayers/openlayers#10773]
Hi,

In javascript it is possible to use an Object as eventhandler. 
See: [eventListener.handleEvent()](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) on MDN

> listener
The object which receives a notification (an object that implements the Event interface) when an event of the specified type occurs. This must be an object implementing the EventListener interface, or a JavaScript function. See The event listener callback for details on the callback itself.

(Lol, a listener IS an object OR a function.... but the first is almost never explained... 🙄)

The great advantage for this that you do not need to use `bind(this)` etc, because when using an object as listener its context is kept. See [this great article on this](https://www.thecssninja.com/javascript/handleevent)

But it does not work out-of-the-box here in OL. (Or do I overlook something)
Because a listener is called with `call()` in [event/Target.js](https://github.com/openlayers/openlayers/blob/a34b22f1d9f965d90ee3fcc9e078710621b6948e/src/ol/events/Target.js#L111), and so this native feature breaks. 

Of course an OL `olObject.on(event, listener)` is different then the native javascript event-listener. But I think it would be very nice to have this, and it can be done easily. 🙂 

OL has `handleEvent()` functions in `Interactions` (and others?). As far as I can see, this will not conflict when the native handleEvent() would be implemented.

Example:
```
class MyEventHandler{
  _someProp = 'my values';
  handleEvent(e){
    alert(this._someProp);
  }
}

let oHandler = new MyEventHandler();

// initiate some interaction in OL
let oDraw = new Draw(options);
oDraw.on('drawend', oHandler); 

// or on some htmlelement
let oButton = document.getElementById('myButton');
oButton.addEventListener('click',oHandler);
```

Nicer example
```
class MyInteractionWrapper{
  _someProp = 'my values';
  _oInteraction;

  handleEvent(e){
    alert(this._someProp);
  }
  constructor(){
    // initiate some interaction in OL
    this._oInteraction = new Draw(options);
    this._oInteraction.on('drawend', this); 
  }
}

let oDraw = new MyInteractionWrapper();
```

NB!! 
This ONLY works with `addEventListener()` and not with properties like `object.onevent` which only accepts a function. see [mdn](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Event_handlers) 
But OL works only with `addEventListener()`.

At the moment I can get this working, by adding method `call(context,e)` to the eventHander-object.
Like:
```
  call(context,e){
    // context is NOT used!
    return this.handleEvent(e);
  }
```
But that is not very nice. 

One way to get this working with OL is changing the code in `target.js` like:
```
let fnPropagate;
for (let i = 0, ii = listeners.length; i < ii; ++i) {
     if(listeners[i].handleEvent){
        // do not enforce context for that would break the native functionality
	fnPropagate = listeners[i].handleEvent(evt);
     }else{
	fnPropagate = listeners[i].call(this, evt);
     }
     if (fnPropagate === false || evt.propagationStopped) {
         propagate = false;
          break;
     }
}
```
I do not know if this would create a conflict with the existing `handleEvent()` functions, but I don't think so.

I can do a PR, but need some help on getting the typedef right 😬 

I really look forward to see your reactions on this.
Greetz, flexJoly

PS. I hope the code-examples have no typos, because I did not test these exact examples.

**Comment by ahocevar** [comment]
You could also just change a single line in `target.js`:
```js
fnPropagate = listeners[i](evt);
```
That will make both functions and event listeners work.

I am not sure if we still need to call the listener with the target as `this`. But feel free to create a pull request. If no tests fail, it should be fine.

**Comment by flexjoly** [comment]
Thanks for your reply!

I am not sure if I understand you correctly. But I tried the following

```
        if (listeners[i](evt) === false || evt.propagationStopped) {
          propagate = false;
          break;
        }
```
This does not work, the `this` is needed as context for the listener in OL itself. 
It break for example directly ` this.getSource()`  in `handleSourcePropertyChange_`.

So I tried:
```
      let fnPropagate;
      for (let i = 0, ii = listeners.length; i < ii; ++i) {
        if (listeners[i].handleEvent) {
          fnPropagate = listeners[i](evt);
        } else {
          fnPropagate = listeners[i].call(this, evt);
        }
        if (fnPropagate === false || evt.propagationStopped) {
          propagate = false;
          break;
        }
      }
``` 
This does not work also, for `handleEvent()` is only called directly by the user-agent, but not with some scripting in between.

**Comment by flexjoly** [comment]
When testing my original code, I got some `typedef` error.

In `events.js` I added:
```
/**
 * Listener Object. EventListener with function handleEvent()
 * As in: https://developer.mozilla.org/en-US/docs/Web/API/EventListener/handleEvent
 * When the function returns `false`, event propagation will stop.
 *
 * @typedef {Object} ListenerObject
 * @api
 */
```

And changed `ListenerFunction` typedef to:
```
/**
 * Listener function. This function is called with an event object as argument.
 * When the function returns `false`, event propagation will stop.
 *
 * @typedef {ListenerObject.handleEvent|function((Event|import("./events/Event.js").default)): (void|boolean)} ListenerFunction
 * @api
 */
```

But I am stuck here 😿 getting the error from test:
```
src/ol/events.js:31:14 - error TS2702: 'ListenerObject' only refers to a type, but is being used as a namespace here.

31  * @typedef {ListenerObject.handleEvent|function((Event|import("./events/Event.js").default)): (void|boolean)} ListenerFunction
```

**Comment by ahocevar** [comment]
Is the rationale behind your attempts only to avoid having to bind the function to this? If so, then ES6 provides a simpler solution than adding support for `EventListener`. Just use an arrow function, which will use the `this` from the function creator:
```js
const that = this;
interaction.on('drawend', (e) => {
  console.log(that === this); // true
});
```

**Comment by flexjoly** [comment]
Hi,
No I like to have the eventListeners as a nice standalone blackbox object. 

My background is old Cobol (1989) and very clean programming 👼 
So I hate shortcuts like closures and arrow functions 😉 🤣 

And as EventObjects are native javascript I thought it would be a good idea if this is possible in OL too. 

Greetz, flexJoly

**Comment by ahocevar** [comment]
Ok, point taken. Since your suggested change does not add much code or overhead, we'd accept a pull request. Thanks in advance!

**Comment by flexjoly** [comment]
Only I do not know how to get past the typedef error as I mentioned above 😞

**Comment by ahocevar** [comment]
@flexjoly In events.js, just add `EventListener` as type to the ListenerFunction typedef:
```js
/**
 * Listener function. This function is called with an event object as argument.
 * When the function returns `false`, event propagation will stop.
 *
 * @typedef {EventListener|function((Event|import("./events/Event.js").default)): (void|boolean)} ListenerFunction
 * @api
 */
```

**Comment by flexjoly** [comment]
> In events.js, just add `EventListener` as type to the ListenerFunction typedef:
> 
> ```js
> /**
>  * Listener function. This function is called with an event object as argument.
>  * When the function returns `false`, event propagation will stop.
>  *
>  * @typedef {EventListener|function((Event|import("./events/Event.js").default)): (void|boolean)} ListenerFunction
>  * @api
>  */
> ```

This gives errors too 😣
