### ISSUE TITLE
[Question] what's the use for a z-index in a LayerGroup?

### ISSUE THREAD

**Issue by halybee** [openlayers/openlayers#10775]
Hi,

Looking over the documentation, I notice LayerGroup has a z-index : https://openlayers.org/en/latest/apidoc/module-ol_layer_Group-LayerGroup.html#setZIndex

I'm wondering what's the need / use case for this? I thought perhaps you could have multiple LayerGroups, but it doesn't seem to be the case as you can only get/set one in [PluggableMap](https://openlayers.org/en/latest/apidoc/module-ol_PluggableMap-PluggableMap.html#setLayerGroup)

So I was wondering what's the use of having a z-index?

Thanks!

**Comment by mike-000** [comment]
LayerGroup is a subclass of BaseLayer so groups can be nested and contain multiple groups, for example within the map's default layer group https://openlayers.org/en/latest/examples/layer-group.html  zIndex is an inherited property with little practical purpose as the component layers have their own settings.
