### ISSUE TITLE
Add an option to enable/disable canvas context.imageSmoothingEnabled

### ISSUE THREAD

**Issue by mbenzekri** [openlayers/openlayers#10772]
I am using a XYZ tile source whith a specific color map in conjonction with a RasterSource with pixel operations (like this ol example : [Color Manipulation](https://openlayers.org/en/latest/examples/color-manipulation.html)). 

When my XYZ tiles are displayed in intermediate scales polygon borders are smoothed by the scaling then colors which are specifiquely setted in my XYZ tiles are changed that's make my pixel operations fails due to an unknown color (out of my colormap). 

If possible, please could you add and option in XYZ class or in the correct ascendant class to set 
a boolean option like "imageSmoothing" to enable or disable smoothing (defaulting to true for compatibility).

My workarround today was to "patch" the drawTileImage method of CanvasTileLayerRenderer.prototype (see: MY CHANGE).
```
CanvasTileLayerRenderer.prototype.drawTileImage = function (tile, frameState, x, y, w, h, gutter, transition, opacity) {
    var image = this.getTileImage(tile);
    if (!image) {
        return;
    }
    var uid = getUid(this);
    var tileAlpha = transition ? tile.getAlpha(uid, frameState.time) : 1;
    var alpha = opacity * tileAlpha;
    var alphaChanged = alpha !== this.context.globalAlpha;
    if (alphaChanged) {
        this.context.save();
        this.context.globalAlpha = alpha;
    }
    // --------------------------------------------- MY CHANGE
    this.context.imageSmoothingEnabled = false // <= set option here !!!
    // --------------------------------------------- MY CHANGE
    this.context.drawImage(image, gutter, gutter, image.width - 2 * gutter, image.height - 2 * gutter, x, y, w, h);
    if (alphaChanged) {
        this.context.restore();
    }
    if (tileAlpha !== 1) {
        frameState.animate = true;
    }
    else if (transition) {
        tile.endTransition(uid);
    }
}
```
thats work, when setted like that all the tiles for all layers are impacted, adding an option seems to me a better choice.
Thanks for your attention

**Comment by mbenzekri** [comment]
**Examples with smoothing enabled**

![image](https://user-images.githubusercontent.com/7136528/76082510-e25ccb80-5fab-11ea-85f2-92ffe9fca344.png)
 
![image](https://user-images.githubusercontent.com/7136528/76082576-03bdb780-5fac-11ea-9dcd-66e3939cbbc0.png)

![image](https://user-images.githubusercontent.com/7136528/76082719-47182600-5fac-11ea-891a-e2974d81f9bc.png)

- see polygon borders (after color manipulation)

**Comment by mbenzekri** [comment]
Example with smoothing disabled:

![image](https://user-images.githubusercontent.com/7136528/76082917-afff9e00-5fac-11ea-8eff-e8178fc25e66.png)

![image](https://user-images.githubusercontent.com/7136528/76082947-c0177d80-5fac-11ea-8042-e945dfbd4473.png)

![image](https://user-images.githubusercontent.com/7136528/76082988-dae9f200-5fac-11ea-9d06-50608b74c33f.png)

- see polygon border are sharp (color manipulation successfull)

**Comment by mike-000** [comment]
It can be done using the prerender event, see https://openlayers.org/en/latest/examples/sea-level.html

However it doesn't work when a source is reprojected. There is already a PR #10429 for that but overlaps on reprojection edges causes a problem which requires another PR.
