### ISSUE TITLE
Vector Tile cut on the upper tile extent

### ISSUE THREAD

**Issue by Farkal** [openlayers/openlayers#10771]
**Describe the bug**
Points are cut but the cutting line doesn't match the current tile, it seems to match the upper tile.

**To Reproduce**
1. Go to https://codesandbox.io/s/vector-tile-info-mse72
2. Look at the points :eyes: 

**Expected behavior**
Don't cut the point :smile: 

At work we have bigger icons and the cutting is huge:

![image](https://user-images.githubusercontent.com/3998763/76076551-62306900-5f9f-11ea-8c15-3f575983c2c2.png)

**Comment by mike-000** [comment]
You need to use tiles which have a buffer.  Specifying a renderBuffer has no effect unless the tiles have a buffer.  When I substitute your url with tiles from MapTiler there is no problem https://codesandbox.io/s/vector-tile-info-bunoi
