### ISSUE TITLE
ol/source/Vector: removeFeature fails even though hasFeature returns true

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#10796]
**Describe the bug**

If two features have the same id, it's impossible to correctly use `hasFeature` with `removeFeature`. `hasFeature` checks for both feature id and uid while `removeFeature` only uses the feature uid.

**To Reproduce**

``` ts
let a = new Feature();
a.setId("123");

let b = new Feature();
b.setId("123");

source.addFeature(a);

if (source.hasFeature(b)) {
  source.removeFeature(b);
  // Uncaught TypeError: Cannot read property 'forEach' of undefined
}
```

**Expected behavior**

* `hasFeature` only returns true if the feature uid matches.
* ~~have a separate `hasFeatureId` method.~~

**Comment by icholy** [comment]
``` js
function hasFeature(source, feature) {
  let id = feature.getId();
  if (id) {
    return source.getFeatureById(id) === feature;
  }
  return source.hasFeature(feature);
}
```

**Comment by icholy** [comment]
One way to work around this would be to do an equality check against the feature returned by `getFeatureById`:

``` js
function hasFeature(source, feature) {
  let id = feature.getId();
  if (id) {
    return source.getFeatureById() === feature;
  }
  return source.hasFeature(feature);
}
```

**Comment by ahocevar** [comment]
Two distinct features should not have the same ids. This is enforced in the source's `addFeature` method, but that restriction can be circumvented by using `feature.setId`. The proper fix would be for the source to throw an exception upon handling a feature's change event when the id is set to the id of an existing feature.

**Comment by icholy** [comment]
@ahocevar In my use-case I have the same feature geojson arriving from two separate places. Even though they're the "same" feature, they're not the same instance of `ol.Feature`.

**Comment by ahocevar** [comment]
@icholy If the two GeoJSONs are loaded into the same source, then features that have the same id as a previous feature will not be added again.

**Comment by icholy** [comment]
@ahocevar I wanted the opposite behaviour, so I'm doing this:

``` js
function addFeature(source, feature) {
  let id = feature.getId();
  if (id !== undefined) {
    let duplicate = source.getFeatureById(id);
    if (duplicate) {
      source.removeFeature(duplicate);
    }
  }
  source.addFeature(feature);
}
```

However, now the removed (original) feature has no way of knowing if it's in the source.

**Comment by icholy** [comment]
Another option is to prevent `removeFeature` from throwing an exception if the source doesn't contain the `io.Feature` instance.
