### ISSUE TITLE
Openlayers in CDNJS is stuck at version 4.6.5

### ISSUE THREAD

**Issue by Tugzrida** [openlayers/openlayers#10790]
I went to use Openlayers in a project recently and found that CDNJS is stuck way back at v4.6.5. Looking into it, CDNJS is still pulling `ol.js`, `ol.css`, `ol-debug.js` and `ol-debug.css` from the old `openlayers` NPM package.

Fixing this is a little more complicated than just changing CDNJS to the `ol` NPM package, as the packaging has changed since v4.6.5 too.

There are two ways to add files to CDNJS now that manual submissions have been deprecated: either through an NPM package (preferred) or releases on a Github repo. The catch is that the compiled & minified files must be present in the package or repo in order to be included in CDNJS, so the compiled versions currently attached to Openlayers releases in a zip won't work.

When raising the issue over there in cdnjs/cdnjs#13701, we ended up reaching the conclusion that the NPM package would need to include the compiled js & css in order for it to be compatible with the CDNJS autoupdater.

If the team here is able to make changes to accomodate this, then I can PR the necessary changes in CDNJS. Thanks! :)

**Comment by ahocevar** [comment]
Starting with v5, we discourage the use of the OpenLayers full build. If you still want to use it, look at the [quickstart](https://openlayers.org/en/latest/doc/quickstart.html) to find the updated urls on cdn.jsdelivr.net.
