### ISSUE TITLE
Invisible points across the dateline

### ISSUE THREAD

**Issue by richnic** [openlayers/openlayers#10794]
**Describe the bug**
Points across the dateline are not visible but respond to snap-interaction.

**To Reproduce**
1. Open https://openlayers.org/en/latest/examples/draw-and-modify-features.html .
2. Zoom out to minimum zoom level to see as much from the world as possible.
3. Click into the map to place a point, then drag the map to the right, so that the point goes out on the right edge und comes in at the left edge.
4. Repeat step 3 for a while. After a few iterations only, a click into the map does not draw a visible point anymore. Instead it places something invisible that can not be seen but responds to snap-interaction.

**Expected behavior**
All points should be visible.

**Comment by ahocevar** [comment]
When using draw and modify interactions, I would recommend to limit the view extent to avoid this. You won't be happy with the resulting coordinates of drawings like you described anyway, because they would by far exceed the range of -180 to +180.

**Comment by richnic** [comment]
Thanks for the tip. Limiting the view extent is an acceptable solution for me.

However, a geometry that is invisible but responds to snap-interaction, is a strange behaviour that may not be desired. If you plan to fix it, I can leave this issue open. Otherwise I would close it.

**Comment by flexjoly** [comment]
Our client has something similar, but until now I have not enough information and I could not reproduce it myself.
But he sent a screenshot from the map (on mobile) on which only the text-labels are visible, but the Points are gone. He says that this happens after a while when using the map. 

'Using' is: zooming in and out, clicking on markers (with popups/modal/iframe etc), swiping the map to see the other markers (about 200 to 300 in this case) and also using other apps (fooncall, mail etc) and then coming back to the still open map in the browser. 

![image](https://user-images.githubusercontent.com/8533733/76518221-04989280-645f-11ea-997f-10e1652584e9.png)

It should be like:
![image](https://user-images.githubusercontent.com/8533733/76518551-999b8b80-645f-11ea-8cd9-2c4091133452.png)

So far, this is the only info I have, so I need to investigate more. 
But there is something weird going on. As you can see the map is pretty detailed in stead of zoomed-out.

**Comment by richnic** [comment]
@flexjoly: It seems to me, that our problems are different. The bug I have described is clearly related to the date line. The waypoints are visible on one side, but not on the other, and only half of a waypoint is drawn on the date line itself.

**Comment by richnic** [comment]
There are also problems with the visibility of LineStrings and MultiLineStrings crossing the date line.
Instead of waiting for all the bugs to be fixed, I accept acehovar's advice (to limit the view extent) and close this issue.
