### ISSUE TITLE
Lazy source ImageLayer throw an error

### ISSUE THREAD

**Issue by gilles-crealp** [openlayers/openlayers#10793]
**Describe the bug**
As shown in [Lazy Source example](https://openlayers.org/en/latest/examples/lazy-source.html), lazy source work well with [`TileLayer`](https://openlayers.org/en/latest/apidoc/module-ol_layer_Tile-TileLayer.html) but throw an error with [`ImageLayer`](https://openlayers.org/en/latest/apidoc/module-ol_layer_Image-ImageLayer.html).

> Cannot read property 'getImage' of null

**Example**
https://jsfiddle.net/f5ad38vo/

**Expected behavior**
To be able to lasy source ImageLayer.

**Comment by mike-000** [comment]
stale has closed #10474 but if reopened it should fix this

**Comment by ahocevar** [comment]
Fixed with #10474
