### ISSUE TITLE
How to set all country languages as English

### ISSUE THREAD

**Issue by narekacy** [openlayers/openlayers#10798]
I am new in React.js and Openlayers API integration. I want to set all countries view language to English. I Tried to search, did it a lot, but unfortunately nothing was found. 

Does there any way for it available? Thank you in advance

P.S. Here is my code:

```
class OpenlayersMap extends Component {
    render() {
        return (
            <Container>
                <Map view={{
                    center: transform([26.249249, 50.621957],
                        'EPSG:4326', 'EPSG:3857'),
                    zoom: 12,
                    maxZoom: 18,
                    minZoom: 4
                }}
                >
                    <Layers>
                        <layer.Tile/>
                        <col/>
                    </Layers>
                </Map>
            </Container>
        );
    }
}
```

**Comment by fredj** [comment]
OpenLayers is not providing the map. If you want to display an OSM map in a specific language please see: https://wiki.openstreetmap.org/wiki/Map_internationalization

**Comment by narekacy** [comment]
@fredj thanks!
