### ISSUE TITLE
Freehand drawing on map ends by itself after start drawing.

### ISSUE THREAD

**Issue by ar-rahimi** [openlayers/openlayers#10804]
**Describe the bug**
Freehand drawing on map ends by itself after start drawing.

**To Reproduce**
1. https://openlayers.org/en/latest/examples/draw-freehand.html?q=draw
2. go in developer tools, mobile view
3. try to draw

**Expected behavior**
it should stop drawing when touch is done.

I already found a way to fix this issue:
touch-action: None;
seems to be removed in mobile view.

**Comment by jalik** [comment]
@ar-rahimi I have this bug on real mobile devices only, but not when using the developer tools in latest Firefox for example.

I managed to reproduce the bug only in Chrome for Android (v 80.0.3987.162), it's working well in Firefox for Android.
