### ISSUE TITLE
ImageSourceEventType not available for consumers

### ISSUE THREAD

**Issue by regileeso** [openlayers/openlayers#10814]
**Describe the bug**
The `enum` ImageSourceEventType is not available for consumers, since it's simply not exported.

**To Reproduce**
`src/ol/source/Image.js` line 18, does not have an `export` keyword

**Comment by regileeso** [comment]
I've already added a pull request. https://github.com/openlayers/openlayers/pull/10805

**Comment by fredj** [comment]
The event type enums are not part of the api, they are only meant to be used internally.

**Comment by regileeso** [comment]
Could you please explain, why the type enum is not part of API, thus not exported? In other cases, for instance `ol/MapBrowserEventType`, the types are exported and usable. I have loads of hardcoded event names for these cases.

If it's not part of API and if it's out of question, to make it available, it seems like `@types/ol` is having it wrong, right?

`@types/ol/source/Image.d.ts` 

```
export enum ImageSourceEventType {
    IMAGELOADSTART = 'imageloadstart',
    IMAGELOADEND = 'imageloadend',
    IMAGELOADERROR = 'imageloaderror',
}
```

**Comment by ahocevar** [comment]
Right, `@types/ol` is not official. OpenLayers now ships with its own type definitions (use `ol@dev` until the next release)
