### ISSUE TITLE
Flip feature Icon

### ISSUE THREAD

**Issue by hdlol** [openlayers/openlayers#10817]
Hello,

I want any method or help to be able to flip (vertically and/or horizontally) the feature's icon as it is possible for rotation.

I use OL 6.1.1

**Comment by mike-000** [comment]
Currently you would need to load and flip the image (e.g. via a canvas element) before creating a new style.  There was some work started in #6100 which included allowing the scale to be an array.  If the relevant part could be revived maybe setting a negative x or y value could be used to flip?

**Comment by hdlol** [comment]
Flip the image via canvas element is not a good solution (performance issue with thousands of features). Negative values for scales for example would be great.

**Comment by hdlol** [comment]
Is it possible to add the flip feature icon ?

**Comment by mike-000** [comment]
> Is it possible to add the flip feature icon ?

#11037 allows two dimensional scales.  A negative scale for either dimension will flip the icon in that dimension https://codesandbox.io/s/icon-scale-5mzvs
