### ISSUE TITLE
Sponsor

### ISSUE THREAD

**Issue by hutch120** [openlayers/openlayers#10812]
@ahocevar @tschaub Hi Gents, Simon from Pozi here. I was wondering if we would be able to get our name on the Readme per the OpenCollective sponsor note. "Become a sponsor and get your logo on our README on Github with a link to your site."

https://opencollective.com/openlayers

Pozi helps connect communities through spatial thinking. We love Openlayers and it forms a core part of our platform. https://pozi.com/ https://app.pozi.com/

![image](https://user-images.githubusercontent.com/1034955/76800840-95d58380-6828-11ea-9318-07bcc98afa22.png)

Thanks and keep up the great work!

**Comment by tschaub** [comment]
Hi @hutch120.

Let me know what you think of https://github.com/tschaub/openlayers/blob/sponsor/README.md#sponsors

And thank you for your generous support!

**Comment by hutch120** [comment]
@tschaub Awesome! Legend.

**Comment by tschaub** [comment]
I’ll reopen this until #10813 is in.
