### ISSUE TITLE
Performance issue when using lineDash on Stroke style

### ISSUE THREAD

**Issue by geertplaisier** [openlayers/openlayers#10820]
**Describe the bug**
There seems to be a performance issue when applying lineDash to a Stroke style when zooming in/out. Created a simple example (copied over Draw Features example from the website and applied a simple styling function, see https://codesandbox.io/s/draw-features-z2e81). The issue is most apparent on Safari (almost freezes) but visible in all browsers.

**To Reproduce**
1. Go to https://codesandbox.io/s/draw-features-z2e81
2. Draw a circle
3. Zoom in and out to a low level inside the circle

**Expected behavior**
Expected to be the same with lineDash as without.

**Comment by ahocevar** [comment]
Duplicate of #10139.
