### ISSUE TITLE
Send lon & lat to lonLabelFormatter & latLabelFormatter in ol/Graticule

### ISSUE THREAD

**Issue by Sagie501** [openlayers/openlayers#10826]
The current map Graticule options lonLabelFormatter and latLabelFormatter functions get only one argument: lon or lat respectively.
Sometimes we would like to have both of the arguments for formatting the lon / lat.
For example, if we want to use different coordinate system for displaying the labels etc.

**Comment by alaluf99** [comment]
Great solution.

**Comment by SharonShrits** [comment]
Very helpful, thank you!
