### ISSUE TITLE
MousePosition show Y coordinates as wrong for ImageStatic with Pixels Projection

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#10825]
**Describe the bug**
I have a map with a pixel projection and load a static image in a layer (My image height is 4298).  When I view the coordinates in mouseposition I see that the X is showing correct, but not the Y.  For example.  If i move the cursor at the top left corner of my image it shows: 0, 4298 - Which is wrong as it is suppose to show 0, 0.  When I move my cursor at the bottom left corner of my image, it shows 0, 0 - Which is also wrong at it is suppose to show 0, 4298.  I presume that map click events will also handle the Y wrongly.  How can I correct this?

```
var imgExtent = [0, 0, 6065, 4298];
var imgProjection = new ol.proj.Projection({
	code: 'my-image',
	units: 'pixels',
	extent: imgExtent
});
var pageSource = new ol.source.ImageStatic({
	projection: imgProjection,
	url: '/url/to/my/image.png',
	imageExtent: imgExtent
});
var pageLayer = new ol.layer.Image({
	source: pageSource
});
var imgView = new ol.View({
	center: ol.extent.getCenter(imgExtent),
	minZoom: 0,
	maxZoom: 10,
	rotation: 0,
	projection: imgProjection,
	extent: imgExtent
});
var imgMap = new ol.Map({
	controls: ol.control.defaults({
		attributionOptions: {
			collapsible: true
		}
	}).extend([
		new ol.control.FullScreen(),
		new ol.control.ZoomSlider(),
		new ol.control.MousePosition({
			coordinateFormat: ol.coordinate.createStringXY(0),
			projection: imgProjection,
			undefinedHTML: '&nbsp;'
		})
	]),
	layers: [
		pageLayer
	],
	renderer: 'canvas',
	target: 'panelEditMainMap-body',
	view: imgView
});
```

**Comment by 1Map** [comment]
Anyone with a possible answer?

**Comment by 1Map** [comment]
@ahocevar Any way you can maybe help me with this?

**Comment by ahocevar** [comment]
You can do that by passing a different projection to the MousePosition control, with a transform function that adjusts the y coordinates to suit your needs.

**Comment by 1Map** [comment]
Hi, thanks for the info.  I am aware of that, but does that mean I have to do it, for example, map clicks, etc ?  Do you maybe have an example of swapping the Y axis in projection and where do I do that, as there are a lot of places where I set projection: ol.control.MousePosition, ol.source.ImageStatic as well as ol.View.

**Comment by ahocevar** [comment]
If you create a codesandbox from your above code, I can show you how to do that.

**Comment by 1Map** [comment]
No problem I got it fixed by using a sing projection right through.  Something like:

```
		var iW = myImageWidth;
		var iH = myImageHeight;

		me.imgProjection = new ol.proj.Projection({
			code: 'xkcd-image',
			units: 'pixels',
			axisOrientation: 'esu',
			extent: [0, 0, iW, iH]
		});
		ol.proj.addProjection(me.imgProjection);
		ol.proj.addCoordinateTransforms(me.imgProjection, me.imgProjection,
			function (coordinate) {
				return [coordinate[0], -coordinate[1] + iH];
			},
			function (coordinate) {
				return [coordinate[0], -coordinate[1] + iH];
			}
		);
		me.mousePosition.setProjection(me.imgProjection);
```
