### ISSUE TITLE
createHitDetectionImageData error for features with no size

### ISSUE THREAD

**Issue by gedaiu** [openlayers/openlayers#10839]
```
this.layer.getFeatures(pixel).then((features) => { });
```

triggers an error in `createHitDetectionImageData` when there is a feature with an image with no size. 

for some reason the array here is undefined:

https://github.com/openlayers/openlayers/blob/5ea0b52ba8774e8170dc18fb6453affdef43eafc/src/ol/render/canvas/hitdetect.js#L69

**Comment by ahocevar** [comment]
Thanks for reporting this. I can confirm the bug. If anyone has a fix, a pull request would be much appreciated.

**Comment by gedaiu** [comment]
I know how to fix this, but I don’t know how I could test the fix with an unittest....

**Comment by ahocevar** [comment]
@gedaiu In `test/spec/ol/layer/vector.test.js`, you could modify the existing '#getFeatures()' one, by configuring the layer in the `beforeEach()` function with a style with an image with no size.
