### ISSUE TITLE
VectorLayer how to add feature

### ISSUE THREAD

**Issue by zhipengDeng** [openlayers/openlayers#10841]
i user vectorLayer add feature, but ploygon cannot be displayed on the map. i need help.
this is my code:
refreshFeatures(val) {
     let source = layer.getSource(),
      source.clear();
      let aoiPolygon = val;
      if (!aoiPolygon) {
        return;
      }

      let feature = readWkt(aoiPolygon.the_geom);
      console.log(feature);
      feature.setId(aoiPolygon.guid);
      feature.setStyle(this.style);
      feature.setGeometryName(aoiPolygon.short_name);
      source.addFeatures([feature]);
      source.refresh()
  
    }

**Comment by dracarys26** [comment]
i guess vectorLayer should after map's layer
layers:[xxxLayer,vectorLayer]

or use z-index
