### ISSUE TITLE
Programmatically start drawing

### ISSUE THREAD

**Issue by sdfricke** [openlayers/openlayers#10844]
**Is your feature request related to a problem? Please describe.**

I would like to be able to programmatically start drawing using Draw interaction.  Right now when the user clicks I have a check to determine if the pixel is within a particular layer, and if so I want to start the drawing at that point.  So after they click on that point, I check if they should be able to draw there, and if so I want to start drawing at that same point.  I have achieved this by saving the click event that is used to determine if the click is within a feature, and if it is, I called drawInteraction.startDrawing_(mySavedClickEvent).  This doesn't seem like a very stable solution.

**Describe the solution you'd like**

It would be nice if there was an official supported method in the API for being able to programmatically start the drawing at a specified coordinate.  So a method on the Draw interaction where you could just pass a lat, lon would be nice.

**Comment by mike-000** [comment]
You could use the interaction's `condition` to determine whether a click is valid.  In this simple example if there are already features the drawing must start inside one of them https://codesandbox.io/s/draw-features-mxd9z
