### ISSUE TITLE
Raster webworkers not getting terminated

### ISSUE THREAD

**Issue by EvertEt** [openlayers/openlayers#10856]
**Describe the bug**
The raster source creates webworkers using pixelworks but these are never terminated. This can cause high memory usage/ a memory leak.

I think this is a duplicate of https://github.com/openlayers/openlayers/issues/8375 which has been closed due inactivity. 

**To Reproduce**
1. Go to https://codesandbox.io/s/react-openlayers-whlbv
2. Change the number in the input a few times
3. See chrome devtools memory tab for multiple workers (uuids)
![image](https://user-images.githubusercontent.com/9197891/78063055-e18f3d80-738f-11ea-89b3-db862796a7e3.png)

**Expected behavior**
The workers are terminated/destroyed so the memory is freed.

**Current hack**
In version 4.6.5 I am working around it using these 2 snippets:
```javascript
// Hack for https://github.com/openlayers/openlayers/issues/8375
// Warning: this will break when updating openlayers!
// The webworkers created by the rasterSource weren't terminated thus leaked memory.
this.rasterWorkers = rasterSource.B.we;
```

```javascript
if (this.rasterWorkers) {
    this.rasterWorkers.forEach((worker) => worker.terminate());
}
```

**Comment by tschaub** [comment]
Thanks for the report, @EvertEt.

**Comment by EvertEt** [comment]
In version 6.3.1, the first snippet should be 
```
rasterSource.worker_._workers
```

**Comment by tschaub** [comment]
Calling `source.dispose()` now terminates the workers.

**Comment by EvertEt** [comment]
I am not too familiar with the internal workings of OL, my apologies if this is a basic question. Do we need to call this manually or will it happen at a certain moment during GC or cleanup?

Many thanks for a fix either way.

**Comment by tschaub** [comment]
@EvertEt - yes, for now you need to manually call `source.dispose()` if you don't intend to use the source any more.

If you are reusing a single raster source and calling `setOperation` to update the source's operation, old workers will be terminated before creating new ones.  This may be an alternative to creating new sources depending on your use case.

**Comment by EvertEt** [comment]
Should dispose be called on every thing in OL or is there a list of where it will have impact? Calling dispose on the map will also propagate it I assume? Thanks in advance!

Ps. Any idea when a new version will land with the fix? Thank you again

**Comment by EvertEt** [comment]
I think I can (partially) answer my own question based on https://github.com/openlayers/openlayers/issues/11052:

`We always discouraged the use of dispose() in applications, and dispose() is not @api in any of our classes.
`

I believe when the new version lands, dispose should only be used for rastersources to clean up the workers. Correct me if I'm wrong @tschaub .

**Comment by tschaub** [comment]
Yes, that is right.

**Comment by EvertEt** [comment]
Should this also be added to the documentation of rasterSource?

**Comment by ahocevar** [comment]
That would be great @EvertEt

**Comment by EvertEt** [comment]
Should we just mention it text-wise or also add the dispose to the API docs mentioning the method?

**Comment by ahocevar** [comment]
For `ol/source/Raster`, an `@api` annotation should be added to the `dispose()` method. That could be done by specifying something like the following in `ol/source/Raster.js`:
```js
  /**
   * Clean up and unregister the worker
   * @function
   * @api
   */
  Raster.prototype.dispose;
```

**Comment by gjones84** [comment]
I've found that if I use source.dispose() on a raster source, then zoom out or pan, the layer is blank beyond the initial view. If I don't dispose of the source after creating the layer, then eventually the browser crashes due to being out of memory. Is there a better solution for this than to manually dispose of the source?

**Comment by tschaub** [comment]
@gjones84 - can you put together a simple example that demonstrates the problem you are seeing?

Workers should only be getting created when 1) you create a new raster source or 2) you call `source.setOperation()`.  If your application is creating many new sources over time (case 1), then it is the responsibility of your application to call `source.dispose()` when you no longer need an old source.  If your application is calling `source.setOperation()` repeatedly, then you shouldn't need to call `dispose` on anything, and the workers should be getting terminated.

Of course there could still be bugs.  Having a simple example that demonstrates the problem would make it easier to determine what is going on.
