### ISSUE TITLE
WFS format is not support supported GeometryCollection Type

### ISSUE THREAD

**Issue by AckWang** [openlayers/openlayers#10851]
In PostGIS，create a table of GeometryCollection.Then ,publish WFS within GeoServer.When,I post 
 a inserct  feature of GeometryType of GeometryCollection，it throw an error in line  ' serializersNS[node.namespaceURI][node.localName].call(opt_this, node, value, objectStack);'.Beacause of ,without 'GeometryCollection' key of GEOMETRY_SERIALIZERS_  in 'GML3.js'.How to resolve the issues?

**Comment by mprins** [comment]
this seems a duplicate of #4220

**Comment by AckWang** [comment]
Yeah,it is the same issue.

**Comment by AckWang** [comment]
> this seems a duplicate of #4220
Yeah,it is the same issue.
