### ISSUE TITLE
imageSource is null

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#10863]
@mike-000 

When I download the latest Openlayers ol.js (6.2.1) from https://openlayers.org/download/, I get an error when I set my ImageLayer source to null.

Although this was fixed by yourself on 2 Jan 2020:
https://github.com/openlayers/openlayers/commit/5b1df4438d89c18d162d775f0fdca91f6c782043#diff-f7ba5b4f170e888f1096c805cb481439

The distribution under: https://openlayers.org/download/ does not include this fix.

**Comment by ahocevar** [comment]
This fix will be in the 6.3.0 release, which I'm about to publish.

**Comment by 1Map** [comment]
Thanks @ahocevar  
When exactly can I expect the 6.3.0 release?  I have been refreshing the release page, but still seeing 6.2.1

**Comment by ahocevar** [comment]
Today.

**Comment by 1Map** [comment]
thx
