### ISSUE TITLE
Mousewheelzoom and DragPan not working in LitElement webcomponents

### ISSUE THREAD

**Issue by Lars-jnk** [openlayers/openlayers#10860]
The only default interaction that is working is DoubleClickZoom.

I've seen https://github.com/openlayers/openlayers/issues/10704 and https://github.com/openlayers/openlayers/pull/10698

But even with ol@dev it dosn't work.

here is the repo: https://gitlab.com/ladida/openlayer-pwa-litelement-ts
the view: https://gitlab.com/ladida/openlayer-pwa-litelement-ts/-/blob/master/src/gui/views/map-view.ts
and the working demo: https://ladida.gitlab.io/openlayer-pwa-litelement-ts/

**Comment by fredj** [comment]
Hi @Lars-jnk, you updated the code to ol@dev in the repo but the css file is still the one from v6.1.1:
https://gitlab.com/ladida/openlayer-pwa-litelement-ts/-/blob/master/src/gui/views/map-view.ts#L17
can you try to update it as well?

**Comment by Lars-jnk** [comment]
Hi fredj, never thought of this. But you are right. 6.2.1. now it is and all works fine.

Thanks!
