### ISSUE TITLE
VectorLayers are not working

### ISSUE THREAD

**Issue by BHDBvde** [openlayers/openlayers#10870]
**Describe the bug**
VectorLayers are not working in a Polymer 3 project.
This is not working after this change: https://github.com/openlayers/openlayers/pull/10385
Polymer serve gives an error in the console. TypeError: _rbush.default is not a constructor

I don't think it is good to use transpiled files: (https://www.polymer-project.org/blog/2018-05-02-roadmap-faq#dependencies-not-compatible-with-the-native-module-loader)

**To Reproduce**
1. Unzip [olinpolymer.zip](https://github.com/openlayers/openlayers/files/4427870/olinpolymer.zip)
2. Go to the unpacked folder
3. npm install
4. npm run polymerserve
5. See the error in the browser console
**Expected behavior**
Seeing a map.

**Comment by ahocevar** [comment]
Until all our dependencies come packaged as ES modules (like OpenLayers does already), you'll have to use a bundler. No need to transpile though.

**Comment by BHDBvde** [comment]
After reading https://github.com/openlayers/openlayers/issues/8974, I think I understand it. But can you explain why src/structs/RBush.js also uses this import: "import RBush_ from 'rbush/rbush.js';"
I would think you should use the rbush/index.js file because that is the untranspiled file.

**Comment by ahocevar** [comment]
If we import the untranspiled file, then users have to configure their bundlers to transpile dependencies, which is not common practice.

**Comment by BHDBvde** [comment]
Yes but I'm talking about the untranspiled es6 modules in src/ .

**Comment by ahocevar** [comment]
That might be doable. If you have any idea how (e.g. with a change in `build/tsconfig-build.json`, which is responsible for the transpilation, you could submit a pull request.

**Comment by BHDBvde** [comment]
I don't think that is possible with an change in de tsconfig-build. And for now I do not have another idea.
