### ISSUE TITLE
type definitions errors

### ISSUE THREAD

**Issue by yohny** [openlayers/openlayers#10875]
There are multiple errors reported by typescript compiler when using openlayers 6.3.0 in typescript. These error make `ol` unusable with framework like angular as compilation errors prevent successful project build.
Attached repro project has dependency only on `ol` (v6.3.0) and `typescript` (v3.8.3) and contains sample.ts file that creates a few ol objects.

**Steps To Reproduce**
1. get the attached repro project [ol_sample.zip](https://github.com/openlayers/openlayers/files/4431962/ol_sample.zip)
1. execute `npm install`
1. execute `npm run build`
3. See errors from typescript compilation

**Expected Behaviour**
there should be no errors reported

Note: if additional types were used in sample.ts, additional errors might be reported

**Comment by ahocevar** [comment]
#10871 is a similar issue. Looks like TypeScript's `"declaration": true` still does not work well enough with `"allowJs"` true.

I'll be removing the types from the package again and publish a patch release without types. Pull request to come.
