### ISSUE TITLE
Mapbox vector tiles performance

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#10883]
I don't know if this is a bug or maybe just a question for stackoverflow.

I have an angular application with openlayers with mapbox tiles provider. I use raster or static image tiles but I wanted to try vector maps. I understand that vector maps are rendered on client side therefore there is some load on client resources and raster maps are just images served from server but I feel low fps and lags for vector maps in openlayers.

Comparsion:
1. angular app with OL with raster maps:
https://stackblitz.com/edit/angular-openlayer-play-lbdcms?file=src/app/app.component.ts

2. angular app with OL with vector maps:
https://stackblitz.com/edit/angular-openlayer-play-ubncvu?file=src%2Fapp%2Fapp.component.ts

I feel a big difference and vector map has very low fps during pan and zoom to not rendered/cached parts of map (better open map on fullscreen via "Open in New Windows" button). If I am on different browser tab for couple of minutes and then I go back to tab with vector maps, it is frozen for couple of seconds.  
Am I doing something wrong in implementation? or is this expected from vector maps? Is it browser or computer limitation?

**Comment by MichalK6677** [comment]
This implementation looks much faster:
https://stackblitz.com/edit/angular-openlayer-play-bqhw6c?file=src/app/app.component.ts

How could I apply style to VectorTileLayer via ol-mapbox-style?

**Comment by ahocevar** [comment]
Complex vector tile maps tend to perform a bit slowly on OpenLayers. If you are targeting Chrome only, this can be improved by using a worker with an OffscreenCanvas, as shown in https://openlayers.org/en/latest/examples/offscreen-canvas.html.

For reference, the minimal vanilla JavaScript setup to get your map rendered is shown in https://codesandbox.io/s/mapbox-style-w1yor

**Comment by MichalK6677** [comment]
ok thanks.
Seems this is a Duplicate of #7549
