### ISSUE TITLE
Dependencies not loaded when examples opened in CodeSandbox

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10880]
**Describe the bug**
Dependencies such as proj4 and ol-mapbox-style are not loaded when v6.3.0 examples are opened in CodeSandbox 

**To Reproduce**
Open any example which uses proj4 or ol-mapbox-style and click edit.  CodeSandbox reports "Could not find dependency"

**Expected behavior**
Dependencies are included as in v6.2.1

**Comment by ahocevar** [comment]
Thanks for reporting, will be fixed with #10895
