### ISSUE TITLE
Issues with vector loaders when using useGeographic()

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10881]
**Describe the bug**
I experimented to see if the Map Graticule example was compatible with useGeographic() and unsurprisingly it isn't.  The Graticule can only work correctly if it is passed the view projection and extent.  When useGeographic() is specified it receives an EPSG:4326 extent but a view projection resolution.  I also checked the Sphere Mollweide example and while `countries-110m.geojson` loads correctly with an EPSG:3857 view in the Geographic Editing example it doesn't with Sphere Mollweide (even without the graticule).

**To Reproduce**
Specify useGeographic() in the examples.

**Expected behavior**
Either loaders should always be passed the view projection and extent and it should be the loaders responsibility to handle user projections, or there should be a layer option for the renderer to always pass view projection and extent.  The Sphere Mollweide issue (a quick fix would be `toUserExtent` passing an `opt_stops` value to `transformExtent`, but it would be better to use the real view extent) suggests that even default loaders might need to handle user projections themselves.  Regardless of the solution the resolution should be in the same units as the projection and extent.

**Comment by ahocevar** [comment]
Wouldn't it be enough to pass the user projection's resolution to the loader, instead of the view projection's resolution?

**Comment by mike-000** [comment]
Yes, if the projection and extent are user projection the resolution should also be in user projection.  Currently it is always in view projection.  With non-parallel projections such as polar and Mollweide there can be some inaccuracy in extent transforms (even using the stops option) which might cause a reduction in extent, so an option to use view projection throughout in conjunction with a custom loader would be useful, especially for the graticule which would need to transform user projection extents back to view projection.

**Comment by ahocevar** [comment]
Thinking about this more, the correct behavior for a loader would be to work with the user projection anyway. Not optionally, but always.

**Comment by mike-000** [comment]
Currently it does work with user projection if one is set.  I was suggesting an option to use view projection regardless of user projection.

**Comment by ahocevar** [comment]
I don't think we want that. A configured user projection really means that the user projection is used everywhere in the public API.

**Comment by mike-000** [comment]
The problem with that is transforms between view projection and user projection introduce errors.  e.g. when bottom of the view projection is off the world the transform to user projection places it at -61 degrees so Antarctica is not rendered

![image](https://user-images.githubusercontent.com/49240900/78567600-d8332480-7818-11ea-8e4c-b94272693c9d.png)


In this case the graticule is produced in user projection to it appears as straight lines.  Internally it could be transformed back to view projection to plot an accurate graticule, but that is potentially adding a further transformation error.  Polar projections where max or min values are inside the extent would be more difficult than Mollweide.

**Comment by ahocevar** [comment]
Maybe using vector source loader and strategy for getting graticule lines is not the right approach in the first place? An alternative would be for the graticule layer to update its source's features directly, and to use the standard loader for its source?

**Comment by tschaub** [comment]
Could we clarify the title of this ticket?  If this is specific to the graticule, I think something like @ahocevar's suggestion could make sense – and the title could be something like "Graticule doesn't work with user projection."  If vector loaders really don't work with user projections, then the current ticket title seems appropriate, and it would be nice to have a more general example of the problem (not using the graticule).

**Comment by mike-000** [comment]
There are two problems.

Some custom projections have a problem because a simple extent transform isn't adequate.  Even taking stops along the sides into consideration isn't sufficient if they are outside the projection's validity extent.  I now have a fix which works for Mollweide and polar projections to geographic, but others such as US National Atlas might intersect the user projection extent in two or more places and I don't yet have a fix for that which would be efficient for a bbox strategy.

The graticule problem is it needs to work internally with the view projection and extent, only using the user extent to transform the linestrings and label points for rendering.  As the internal workings of the graticule shouldn't concern the user the easiest fix would be to have have a private requireViewProjection() method which returns true for the gratucule while the vector layer parent class returns false.  The renderer could check that when calling the loader as it does for getUserProjection().

**Comment by mike-000** [comment]
bump

**Comment by mike-000** [comment]
No further progress, but the first issue relating to transforms between non-parallel projections would require a solution similar to how ol/layer/Graticule obtains a valid extent for a graticule from a projection's world extent.  Resolutions would also need to converted be appropriate to the projections.

```
function toUserExtentAndResolution(extent, resolution, sourceProjection) {
  const userProjection = getUserProjection();
  if (!userProjection) {
    return {extent: extent, resolution: resolution};
  }
  const projectionExtent = sourceProjection.getExtent();
  let validExtent = extent;
  if (projectionExtent) {
    validExtent = [
      clamp(extent[0], projectionExtent[0], projectionExtent[2]),
      clamp(extent[1], projectionExtent[1], projectionExtent[3]),
      clamp(extent[2], projectionExtent[0], projectionExtent[2]),
      clamp(extent[3], projectionExtent[1], projectionExtent[3])
    ];
  }
  const userProjectionExtent = userProjection.getExtent();
  const userExtent = transformExtent(validExtent, sourceProjection, userProjection, 8);
  if (userProjectionExtent) {
    const bottomLeft = transform(getBottomLeft(userProjectionExtent), userProjection, sourceProjection);
    const bottomRight = transform(getBottomRight(userProjectionExtent), userProjection, sourceProjection);
    const topLeft = transform(getTopLeft(userProjectionExtent), userProjection, sourceProjection);
    const topRight = transform(getTopRight(userProjectionExtent), userProjection, sourceProjection);
    if (containsCoordinate(validExtent, bottomLeft)) {
      userExtent[0] = userProjectionExtent[0];
      userExtent[1] = userProjectionExtent[1];
    }
    if (containsCoordinate(validExtent, bottomRight)) {
      userExtent[2] = userProjectionExtent[2];
      userExtent[1] = userProjectionExtent[1];
    }
    if (containsCoordinate(validExtent, topLeft)) {
      userExtent[0] = userProjectionExtent[0];
      userExtent[3] = userProjectionExtent[3];
    }
    if (containsCoordinate(validExtent, topRight)) {
      userExtent[2] = userProjectionExtent[2];
      userExtent[3] = userProjectionExtent[3];
    }
  }
  const userResolution = resolution * (
    getWidth(userExtent) / getWidth(validExtent) +
    getHeight(userExtent) / getHeight(validExtent)
    ) / 2;
  return {extent: userExtent, resolution: userResolution};
}
```

This would aim to avoid anything (such as an area around a pole, or the edges of a Mollweide) being missed, but it is adding a considerable overhead to the transform which in many simpler cases would not be needed.  It could also result in much more data being requested than necessary, and there is no easy solution to that,


I think the graticule should now be dealt with a separate issue.  To work correctly it needs to be calculated in the view projection regardless of whether a user projection is set.  This should done internally without exposing any options in the API, and getMeridians(), getParallels(), etc. would continue to return geometry in the user projection.
