### ISSUE TITLE
Can't pan/mousewheel zoom the map on IE 11

### ISSUE THREAD

**Issue by oterral** [openlayers/openlayers#10888]
**Describe the bug**
SInce the change of behavior with the focus/tabindex/scroll stuff added in 6.2.0, if the map element has a tabIndex, it's impossible to pan the map on IE 11 .

**To Reproduce**
1. Open https://openlayers.org/en/latest/examples/simple.html on IE 11
2. Add a tabindex="0" to the map element in the dev tools.
3. Try to pan the map
---> nothing happens because the focus is on the layer element, not on the map element.

**Expected behavior**
The user can pan the map.

If someone has a miraculous workaround. I take it.

**Comment by ahocevar** [comment]
Thanks for reporting this @oterral. I just created #10893 with a fix.

**Comment by oterral** [comment]
@ahocevar awesome !! thx for your reactivity!!!
