### ISSUE TITLE
[Android Webview] [iOS WKWebView] [OL 6.2.0 and onwards] Translating a selected feature stops abruptly and the webview becomes a scrollable window

### ISSUE THREAD

**Issue by KhatibFX** [openlayers/openlayers#10898]
**Describe the bug**
Starting from OL 6.2.0 and above, when I select a feature and use translate to change its position in both Android WebvVew and iOS WKWebView, the translateend event is triggered almost instantaneously while I haven't released the drag, and the WebView becomes slightly scrollable, and the webview no longer response to select and translate interactions. This behavior didn't exist with OL 6.1.1. I am developing and app on Flutter using OpenLayers.

**To Reproduce**
1. Create a new flutter project.
2. Create a WebView_Flutter widget with javascript enabled, use openlayers 6.2.0 and above
```dart
WebView(
                                        initialUrl: , //your html file that includes open layers as scripts,
                                        javascriptMode:
                                            JavascriptMode.unrestricted,
                                        onWebViewCreated: (WebViewController
                                            webViewController) {
                                          // save the webview controller to execute javascript commands
                                        },
                                        onPageFinished: (_) async {
                                          //run javascript commands to draw the map
await webViewController.evaluateJavascript('''
var mapView =
        new ol.View({
        projection: projection,
        center: ol.extent.getCenter(extent),
        zoom: 1,
        maxZoom: 8
        });
        var map = new ol.Map({
        target: "map",
        layers: [blueprintLayer, vectorLayer],
        view: mapView
        });
        var select = new ol.interaction.Select({
        style: selectedIconStyle,
        hitTolerance: 5
        });
        var selectKey = select.on("select", function(evt){
        
        });
        ''');
    await webViewController.evaluateJavascript('''
        var translate = new ol.interaction.Translate({
        features: select.getFeatures(),
        hitTolerance: 5
        });
        var translateKey = translate.on("translateend", evt => {
        });
        ''');
                                        },
                                      ),
```
3. Have some features on vectorLayer
4. Select and try to translate a feature
5. See the translate interaction stop immediately and the webview becomes a little scrollable vertically

**Expected behavior**
The translate interaction doesn't trigger translateend until you stop dragging the selected feature (Observable on OL 6.1.1)

Please let me know if you need more clarifications. Thanks!

**Comment by ahocevar** [comment]
Thanks for reporting this @KhatibFX. Will be fixed with #10899.
