### ISSUE TITLE
minResolution on ol/View not working as expected

### ISSUE THREAD

**Issue by cvenzin** [openlayers/openlayers#10892]
**Describe the bug**
Setting the maxResolution on the view works as expected. The user can scroll exactly to that resolution and no further. If the minResolution is set, the user can't reach that resolution, the scrolling always stops before reaching the defined minResolution. Also, calling view.getMinResolution() does not return the minResolution value that was set while creating the view.

**To Reproduce**
Create a view and set the minResolution, call view.getMinResolution() after the map with the view was created. The values are not the same (minResolution is always higher than it was set originally).

**Expected behavior**
If minResolution is set, the user should be able to scroll exactly to the defined minResolution.

**Comment by ahocevar** [comment]
@jahow, can you take a look at this please?

**Comment by mike-000** [comment]
The minimum resolution may also be constrained by the `multiWorld` constraint which defaults to true in a global projection, in which case that is expected behaviour.
