### ISSUE TITLE
when i use overview and draw,shapes will multiple rerender

### ISSUE THREAD

**Issue by dracarys26** [openlayers/openlayers#10897]
draw a box first;
if i add a drawLayer to overviewmap and zoom, shapes will multiple rerender. if i don't add the layer to overview ,it won't be happend.
the map and the overviewmap use a same layer that the box you drew can display on the overviewmap;
i don't know is it a bug? or it's my fault;
my english is bad. i hope you can understand:joy:
Example：
https://codesandbox.io/embed/trusting-frost-exzqk?fontsize=14&hidenavigation=1&theme=dark

**Comment by mike-000** [comment]
A layer should be used on only one map.  Instead of adding `drawlayer` create two VectorLayers with `source1` as you have TileLayers with `source`.

**Comment by dracarys26** [comment]
@mike-000 i want synchronous display features on overviewmap.
and my project  involve add,delete and transform

**Comment by mike-000** [comment]
If layers use the same source they will be synchronised https://codesandbox.io/s/practical-goodall-9mkte

**Comment by dracarys26** [comment]
@mike-000 wow thanks！
