### ISSUE TITLE
How to use stopPropagation

### ISSUE THREAD

**Issue by liub1934** [openlayers/openlayers#10894]
It not works，and it printed two console
```
this.markerFeature.on('click', (ev) => {
  ev.event.stopPropagation()
  console.log(ev)
})
```

```
this.polygonFeature.on('click', (ev) => {
  ev.event.stopPropagation()
  console.log(ev)
})
```

**Comment by ahocevar** [comment]
Try this:
```js
this.markerFeature.on('click', (ev) => {
  ev.stopPropagation()
  console.log(ev)
})

**Comment by liub1934** [comment]
> Try this:
> 
> ```js
> this.markerFeature.on('click', (ev) => {
>   ev.stopPropagation()
>   console.log(ev)
> })
> ```
![image](https://user-images.githubusercontent.com/29849550/78568802-354ccb80-7855-11ea-96cb-6dc23529432d.png)
`console.log(ev)`
![image](https://user-images.githubusercontent.com/29849550/78568695-10f0ef00-7855-11ea-8e58-ffbff9dfadfd.png)

**Comment by ahocevar** [comment]
Oh wait, looks like you are dispatching that click event yourself. Because features do not emit click events. Where do you emit this click event, and what do you expect to happen when you stop propagation?

**Comment by liub1934** [comment]
> Oh wait, looks like you are dispatching that click event yourself. Because features do not emit click events. Where do you emit this click event, and what do you expect to happen when you stop propagation?

I added a polygon to the map, and added some marked points within the polygon. The polygon has a click event, and the marked point also has a click event. Now clicking on the marked point will also trigger the click event of the polygon. What I want is to click on the mark  points does not trigger the click event of the polygon.
```
addPolygon (polygon) {
  const path = polygon.path.map(p => [p.lng, p.lat])
  const polygonFeature = new Feature({
    geometry: new Polygon([path])
  })
  polygonFeature.setProperties({
    extData: polygon
  })
  polygonFeature.setId(polygon.id)
  this.vector.getSource().addFeature(polygonFeature)
  polygonFeature.on('click', (ev) => {
    ev.stopPropagation()
    console.log(ev)
  })
},
addMarkers (list) {
  let markerFeatures = []
  const style = new Style({
    image: new Icon({
      src: `${this.$_public_path}/img/mark_blue.png`
    }),
    zIndex: 3
  })
  list.forEach(item => {
    let markerFeature = new Feature({
      geometry: new Point([item.lng, item.lat])
    })
    markerFeature.setStyle(style)
    markerFeature.setProperties({
      extData: item
    })
    markerFeature.setId(item.id)
    markerFeatures.push(markerFeature)
    markerFeature.on('click', (ev) => {
      ev.event.stopPropagation()
      console.log(ev)
    })
  })
  this.marksVector.getSource().addFeatures(markerFeatures)
}
```

**Comment by ahocevar** [comment]
The right way to respond to clicks is to listen to the map's click event and use e.g. `map.getFeaturesAtPixel()` to get the clicked features. See e.g. https://openlayers.org/en/latest/examples/icon.html.

I'm surprised to hear that a 'click' listener registered on a feature gets called at all. That's definitely unintentional.

**Comment by liub1934** [comment]
> The right way to respond to clicks is to listen to the map's click event and use e.g. `map.getFeaturesAtPixel()` to get the clicked features. See e.g. https://openlayers.org/en/latest/examples/icon.html.
> 
> 
> 
> I'm surprised to hear that a 'click' listener registered on a feature gets called at all. That's definitely unintentional.


Thanks I'll try it tomorrow

**Comment by liub1934** [comment]
> The right way to respond to clicks is to listen to the map's click event and use e.g. `map.getFeaturesAtPixel()` to get the clicked features. See e.g. https://openlayers.org/en/latest/examples/icon.html.
> 
> I'm surprised to hear that a 'click' listener registered on a feature gets called at all. That's definitely unintentional.

I made a simple [demo](https://codesandbox.io/s/restless-hill-foz3w?file=/src/components/HelloWorld.vue), stopPropagation still does not work.Please take a look.
You can click on the blue marked point, and it will still trigger 2 events, one is polygon and the other is marked point.

**Comment by ahocevar** [comment]
Instead of calling `ev.stopPropagation();` in the `forEachFeatureAtPixel()` handler, you have to return a truthy value from the `forEachFeatureAtPixel()` function. Your code should look something like this:
```js
      this.MAP.forEachFeatureAtPixel(ev.pixel, feature => {
        // ev.stopPropagation(); don't do this
        console.log(ev);
        alert("click");
        return feature; // do this instead
      });
```

**Comment by liub1934** [comment]
> Instead of calling `ev.stopPropagation();` in the `forEachFeatureAtPixel()` handler, you have to return a truthy value from the `forEachFeatureAtPixel()` function. Your code should look something like this:
> 
> ```js
>       this.MAP.forEachFeatureAtPixel(ev.pixel, feature => {
>         // ev.stopPropagation(); don't do this
>         console.log(ev);
>         alert("click");
>         return feature; // do this instead
>       });
> ```

:+1:Thanks.It works:+1:
