### ISSUE TITLE
Document the GeolocationError type

### ISSUE THREAD

**Issue by daboudii** [openlayers/openlayers#10905]
**Describe the bug**
An issue with the type defs.
I tried to show an error message from a 'BaseEvent'. 
But TypeScript do not appreciate it  `Property 'message' does not exist on type 'BaseEvent'. ts(2339)`

**To Reproduce**
1. 
```
Geolocation.on('error', (error) => {
      this.toastrService.error(error.message);
    });
```
2. ![Screenshot from 2020-04-08 21-33-18](https://user-images.githubusercontent.com/52279206/78820630-cef4b400-79e0-11ea-9d4f-31b5bff36d75.png)

**Expected behavior**
Type defs should allow for setting of `code` & `message` properties.

**Comment by tschaub** [comment]
I don't think this is a problem with OpenLayers.  The `GeolocationError` extends `BaseEvent` and adds `code` and `message` properties.  It looks like the problem comes from the `*.d.ts` files that you are using.

**Comment by daboudii** [comment]
Thanks, I'll have a look

**Comment by tschaub** [comment]
@daboudii - seems like it makes sense to add `@api` annotations to the [`GeolocationError`](https://github.com/openlayers/openlayers/blob/28d1e5c1ee5ee4c365ff2c00072f75d9e2a34eb4/src/ol/Geolocation.js#L33) class and the [`code`](https://github.com/openlayers/openlayers/blob/28d1e5c1ee5ee4c365ff2c00072f75d9e2a34eb4/src/ol/Geolocation.js#L43) and [`message`](https://github.com/openlayers/openlayers/blob/28d1e5c1ee5ee4c365ff2c00072f75d9e2a34eb4/src/ol/Geolocation.js#L48) properties.

I think it could also make sense to add an example to the `GeolocationError` class description to make it clear that this type is passed to listeners of the `'error'` event type.  This isn't clear from the [`@fires`](https://github.com/openlayers/openlayers/blob/28d1e5c1ee5ee4c365ff2c00072f75d9e2a34eb4/src/ol/Geolocation.js#L84) annotation.

**Comment by daboudii** [comment]
If you look the screenshot in https://github.com/openlayers/openlayers/issues/10905#issue-596782073 the error code is `1` with message `User denied location` but in the doc : https://openlayers.org/en/latest/doc/errors/ it doesn't match.

Should I create another issue for that or can be done in the same PR ?

**Comment by tschaub** [comment]
@daboudii the errors listed on https://openlayers.org/en/latest/doc/errors/ are messages for assertion errors thrown in the library.  The messages for those errors are links to that webpage (this was an effort to reduce build sizes).

The object passed to listeners for the `error` event from `ol/Geolocation` objects has a `code` property that relates to the error codes for the browser's `GeolocationPositionError` object.  See [the docs](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPositionError) for that object for a table explaining the various error codes.

The documentation for our `GeolocationError` object (which is confusingly not an `Error` itself) could include a link to the [`GeolocationPositionError` docs](https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPositionError) where the `code` is explained.

**Comment by daboudii** [comment]
@tschaub thanks for the explanation. 
It's added to the [PR.](10909). 

About the error event, maybe it would be more clear to rename it `geolocationerror` like   [`imageloaderror`](https://github.com/openlayers/openlayers/blob/28d1e5c1ee5ee4c365ff2c00072f75d9e2a34eb4/src/ol/source/Image.js#L37)
because right now there is to events call `error` in Geolocation.js

![Screenshot from 2020-04-09 18-17-06](https://user-images.githubusercontent.com/52279206/79013238-f2e6ff80-7b70-11ea-92fa-9f5359fe7e27.png)

**Comment by hanreev** [comment]
IMO, exporting the `GeolocationError` class is necessary, so it can be used outside the module
