### ISSUE TITLE
mouseover and click on a marker stopped working since 6.2.0

### ISSUE THREAD

**Issue by SNoiraud** [openlayers/openlayers#10903]
I'm used to create pages from the gramps application. I use https://openlayers.org/en/latest/... for the ol.js and ol.css. Since several weeks the mouseover and the click on a marker doesn't work.
Replacing latest by the real version, it stopped to work since v6.2.0
Are there any modifications for this in this release and how to correct this.

It seems I receive no more events (wheel nouse, mouseover, click)
The mouseover works only in the case I click down the left button and drag the mouse.

I am not a javascript specialist, but I can attach the copy of the javascript part of one html page.

**Comment by mike-000** [comment]
Have you included the css and is it from the same version of OpenLayers?  See #10732

**Comment by SNoiraud** [comment]
Yes, the css and the js use latest:
https://openlayers.org/en/latest/build/ol.js
https://openlayers.org/en/latest/css/ol.css

**Comment by SNoiraud** [comment]
I attach a tar file used to reproduce the problem:
[openlayers.bug10903.tar.txt](https://github.com/openlayers/openlayers/files/4454703/openlayers.bug10903.tar.txt)

**Comment by adunham1962** [comment]
We saw a similar issue in our project. It seems to be related to some changes made to PluggableMap in the handleBrowserEvent function. It constantly hitting the new short-circuit block:

`const target = /** @type {Node} */ (mapBrowserEvent.originalEvent.target);`

    if (!mapBrowserEvent.dragging) {
      if (this.overlayContainerStopEvent_.contains(target) || !(document.body.contains(target) || this.viewport_.getRootNode && this.viewport_.getRootNode().contains(target))) {
        // Abort if the event target is a child of the container that doesn't allow
        // event propagation or is no longer in the page. It's possible for the target to no longer
        // be in the page if it has been removed in an event listener, this might happen in a Control
        // that recreates it's content based on user interaction either manually or via a render
        // in something like https://reactjs.org/
        return;
      }
    }

Reverting that function's changes seem to do the trick for us.

**Comment by SNoiraud** [comment]
OK. I understand that. But how to solve it ?
I don't want to download the openlayers version in my project.
I only need to use the latest version.

**Comment by ahocevar** [comment]
This issue has been fixed since v6.3.1. Use `npm install ol@dev` to get the latest. Or if you use the legacy version, replace `latest` with `master` in the url you use to load ol.js and ol.css.

**Comment by SNoiraud** [comment]
Thanks. It works correctly now. Do you have an idea when the latest version will be available ?
