### ISSUE TITLE
Static image floats/does not keep position on mobile

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#10908]
Steps to reproduce:
1. open example https://codesandbox.io/s/bing-maps-11plu?file=/index.js
2. open live preview on fullscreen:
![image](https://user-images.githubusercontent.com/3100059/78895722-9c45cc80-7a6f-11ea-8e90-aee4b092666b.png)

3. pan map and check static layer (the image on map) -> it keeps possition and works as expected
4. open dev tools via F12 and open device preview via
![image](https://user-images.githubusercontent.com/3100059/78895871-d7e09680-7a6f-11ea-89f6-52b14c904b02.png)

5. use Pixel 2 preview:
![image](https://user-images.githubusercontent.com/3100059/78895922-eaf36680-7a6f-11ea-94c2-0ca70d2cd949.png)

6. refresh page (ctrl+F5) to refresh mobile code. It is a desktop version with mobile screen resolution without refresh so it must be refreshed.

7. pan a map and check position of the image. It floats:
![OL bug](https://user-images.githubusercontent.com/3100059/78896221-6bb26280-7a70-11ea-88f7-d377d7a32528.gif)

**Comment by mike-000** [comment]
`getRenderPixel` takes account of `pixelRatio` so you should remove `* ratio`

**Comment by MichalK6677** [comment]
nice :) it's working, thank you
