### ISSUE TITLE
Add 'longclick' event on map

### ISSUE THREAD

**Issue by pmulholland42** [openlayers/openlayers#10904]
**Is your feature request related to a problem? Please describe.**
My team is using OpenLayers inside a webview in a React Native mobile app. For this project we would like the user to be able to add features to the map by long pressing on a location. There is no "long press" event on the map object though. I'm currently trying to do this by keeping track of the browser's onmousedown and onmouseup events, but it doesn't seem like an ideal solution.

**Describe the solution you'd like**
I think the best solution would be if the map would fire a "longpress" or "longclick" MapBrowserEvent, in the same vein as "click" and "doubleclick". I would be willing to implement this (with some guidance) if need be.

Thank you!

**Comment by ahocevar** [comment]
Actually we use a long tap for the Draw interaction. When you click to add a vertex and then drag, the map will drag. But if you press longer, you can modify the position of the current vertex. Not sure if this is of any help for your use case,

**Comment by dbauszus-glx** [comment]
@ahocevar How do you get the 'longclick' done in the Draw interaction? I had a quick snoop in the code and found some reference to last drag time.

I notice that the mousedown type originalEvent of the singleclick 'event' has a timestamp. This seems to be from the time the event was initialised. Sadly I wasn't able to make good use of this to determine from this timestamp.

@pmulholland42 we do this to time a long click:

```
let mousedown_timestamp
map.on('singleclick', singleClick)
map_node.addEventListener('mousedown', mouseDown)

function mouseDown(){
  mousedown_timestamp = new Date().getTime()
}

function singleClick(e){
  //log roughly the time between singleClick event being fired on release and mouseDown event on map node.
  console.log(new Date().getTime() - mousedown_timestamp)
}
```

**Comment by ahocevar** [comment]
This is the commit that added the long-tap behavior for touch drawing: 2a64990a71020596b530a3ba0ceb39262b012a35

**Comment by dbauszus-glx** [comment]
@ahocevar That's really helpful. Thanks. lastDragTime would be a helpful property for the singleclick event. I have now modified our own longClick implementation like so.

@pmulholland42 I hope this is helpful for you and others.

```
map.on('singleclick', singleClick)

function singleClick(e) {
  if (longClick) return longClick(e)
  clearTimeout(timeout)
}

map.on('pointermove', pointerMove)

function pointerMove(e) {
  if (longClick) {
    delete longClick
  }
  clearTimeout(timeout)
}

map_node.addEventListener('mousedown', mouseDown)

function mouseDown(){
  clearTimeout(timeout)
  timeout = setTimeout(()=>{
    longClick = true
    // here i change the style of cursor to indicate that a longclick is active.
  }
}
```
