### ISSUE TITLE
Cluster ignores feature style function on resolution change

### ISSUE THREAD

**Issue by welltothebone** [openlayers/openlayers#10901]
**Describe the bug**
In case there are cluster features having a features style function set (used for indicating selected features), a change in resolution will invalidate the feature style and not call the style function for a feature. 

**To Reproduce**
1. Create a cluster layer with point features
2. Set feature style function on selected features
3. Zoom in or out the map

**Expected behavior**
It is kind of obvious that feature clusters are being recreated on resolution change and that previously selected features might therefore not be valid anymore but not all feature cluster are being changed and for those the style function should still be called and the feature should remain selected.

**Comment by mike-000** [comment]
All clusters are cleared before being recalculated.  You could set a property on each of the features within a selected cluster and use a layer style function to style the cluster depending whether all, some or none of its features have that property.
