### ISSUE TITLE
Image getting stretched in Image layer

### ISSUE THREAD

**Issue by Shubham-Tops** [openlayers/openlayers#10907]
HI,

I am not sure is this a bug or not, but I am facing an image get stretched issue. Might I am missing something. Below is my code for clear understanding.

var img_src = "some image url";
map = new OpenLayers.Map('map', { numZoomLevels: 4 });

    var proof = new OpenLayers.Layer.Image('proofimg', img_src, new OpenLayers.Bounds(-600, -500, 250, 600), new OpenLayers.Size(375, 750));

    proof.setIsBaseLayer(true);

    proof.display(true);

    map.addLayer(proof);

    map.setCenter(new OpenLayers.LonLat(0,0),0,false,true)

**Note : I am not allowed to change image dimensions at any cost. Image can be of any height width.**

I need a way where this height, width could be set automatically.

Below is the line where I think something could be done.
var proof = new OpenLayers.Layer.Image('proofimg', img_src, new OpenLayers.Bounds(-600, -500, 250, 600), new OpenLayers.Size(375, 750));

**Comment by mike-000** [comment]
OpenLayers 2 issues should be posted in https://github.com/openlayers/ol2/issues.  The image is stretched because the width to height ratio of the bounds (850/1100 = 0.773) not the same as the width to height ratio of the image (375/750 = 0.5).

**Comment by Shubham-Tops** [comment]
Thanks @mike-000 for sparkling reply. But your advice didn't work. I am sorry, I forget to mention that this img_src is dynamic, user can choose any image with any height width.
