### ISSUE TITLE
HTML title in ol.style.Text?

### ISSUE THREAD

**Issue by vsevjednom-cz** [openlayers/openlayers#10906]
I'm using ol.layer.Vector with ol.style.Style and ol.style.Text and I need to set HTML title for this text. You're write about it here: https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html but it doesn't work :(.

Step to reproduce:
```
	var text_with_title = new ol.layer.Vector({
		style: new ol.style.Style({
			text: new ol.style.Text({ text: 'Some text in the map' })
			})
		}),
		title: 'SOME HTML TITLE'
		source: some_JSONsource
	});

map.addLayer(text_with_title);
```

**Comment by ahocevar** [comment]
This has nothing to do with a html `title` attribute. If you want to assign your `title` to a html `title`, you need to do something like this:
```js
map.on('pointermove', e => {
  const feature = map.forEachFeatureAtPixel(e.pixel, feature => feature);
  map.getTargetElement().setAttribute('title', feature ? feature.get('title') : undefined);
});
