### ISSUE TITLE
WebGLPointsLayer

### ISSUE THREAD

**Issue by eksc** [openlayers/openlayers#10900]
Hello. I am using OL to display 250k+ points in different layers. Every layer create how WebGLPointsLayer, but it loads the graphics card a lot. If I create one WebGLPointsLayer with 250k+ points it works great. How do I need to load points correctly in different layers?

**Comment by jahow** [comment]
You could probably put all the points in the same layer with different styling. Still, that is a lot of data, how much FPS do you end up with typically?
