### ISSUE TITLE
Map stops requesting new tiles when async vector tile source is used.

### ISSUE THREAD

**Issue by WalterSharpJr** [openlayers/openlayers#10912]
I've created a map with 2 layers: a TileLayer with the standard XYZ source and a VectorTileLayer with my own VectorTile source. The data for the vector tile is pulled using an XHR request. When the map contains just the TileLayer, it works fine, but when I add the vector layer, the map retrieves an initial set of tiles, but after that, no new tiles are retrieved, despite zooming and/or panning the map.

I've noticed the problem only occurs when the VectorTile source's tileLoadFunction contains the XHR request, i.e, this code will break the map:

    tileLoadFunction = (tile, url) =>
    {
        tile.setState(TileState.LOADING);

        var request = new XMLHttpRequest();		
        request.open("GET", url, true);
        request.responseType = "json";
        request.setRequestHeader("Content-Type", "application/json");		
		
        request.onload = function(e) 
        {
            tile.setState(TileState.EMPTY);  							
        }

        request.send();
    }

However, if I simply do this, the map works fine:

    tileLoadFunction = (tile, url) =>
    {
        tile.setState(TileState.EMPTY);
    }

I've confirmed that the onload method for the tile is being fired and that no errors are being generated in the tileLoadFunction.

**Comment by ahocevar** [comment]
Please refer to the documentation for a proper `tileLoadFunction` for vector tile layers. See https://openlayers.org/en/latest/apidoc/module-ol_source_VectorTile-VectorTile.html.

You should not be using `setState()` except for load errors. Instead, just call `setFeatures()` on the tile when you have parsed the features.

**Comment by WalterSharpJr** [comment]
Unfortunately, my original approach didn't have the calls to setState, but that didn't work so I stripped out all the code and added the setState method calls in order to test (I wasn't sure if I had to set the tile state or not). If I revert back to my original code, I still get the same issue, it still stops retrieving tiles:

    tileLoadFunction = (tile, url) =>
    {
        var request = new XMLHttpRequest();
		
        request.open("GET", url, true);
        request.responseType = "json";
        request.setRequestHeader("Content-Type", "application/json");		
		
        request.onload = function(e) 
        {  							
            if(request.response != null)
	    {				
                var labels = request.response;
                var features = [];

                for(var i = 0; i < labels.length; i++)
                {					
                    var labelPoint = new Point([labels[i].x, labels[i].y]);
										
                    var label = new Feature();
                    label.setGeometry(labelPoint);
                    label.set("name", labels[i].label);
                    label.set("type", labels[i].type)

                    features.push(label);					
                }

                tile.setFeatures(features);             
            }
        }

       request.send();
    }

**Comment by WalterSharpJr** [comment]
Ah okay, no I see where I have it wrong now, some of my request responses were coming back as null, and in the code above I'm only setting features on the tile if the request response isn't null.

Once I moved the `tile.setFeatures(features)` call outside the `if(request.response != null)` block, it works fine now.

Thanks!
