### ISSUE TITLE
Freehand drawing scrolls the page on mobile Safari

### ISSUE THREAD

**Issue by soberdor** [openlayers/openlayers#10910]
I updated OpenLayers from 5.3.0 to 6.3.1. After the update, freehand drawing doesn't work anymore on mobile Safari. Horizontal movements are plotted on the map correctly, while vertical movements scroll the page. The behavior can also be observed on the latest freehand drawing example, while it still works correctly on the example for OL 5.3.0.

https://openlayers.org/en/latest/examples/draw-freehand.html

https://openlayers.org/en/v5.3.0/examples/draw-freehand.html

**Comment by ahocevar** [comment]
This has been fixed already with #10889 
To take advantage of the fix, `npm install ol@dev`. To work around the issue, configure the map's `target` element with a `touch-action: none` css.

**Comment by soberdor** [comment]
Thanks, the CSS solved it!
