### ISSUE TITLE
v6.3.1 cannot be dragged in lower versions of Google Chrome

### ISSUE THREAD

**Issue by yiwenzhang666999** [openlayers/openlayers#10926]
Google Chrome version 44.0.2403.157 (64-bit), the example on the official website can not be dragged, but v5.3.1 is no problem

**Comment by mprins** [comment]
that is too bad, but not unexpected for a chrome version release 5 years ago...

**Comment by ahocevar** [comment]
If you want to use OpenLayers v6 in very old browsers, you need a more complex pointer events polyfill. Load [pepjs](https://github.com/jquery/PEP) before loading OpenLayers.

**Comment by yiwenzhang666999** [comment]
Thanks for your response very much,I know 

发自我的 iPhone
