### ISSUE TITLE
Wrong tiles generation in geojson-vt example 

### ISSUE THREAD

**Issue by amshel** [openlayers/openlayers#10933]
**Describe the bug**
In the geojson-vt example when zooming in inside a polygon some tiles are not rendered.
You can notice this only when you give a fill color to the style.

**To Reproduce**
1. Go to 'https://codesandbox.io/s/geojson-vt-7ghcj?file=/index.js'
3. Some tiles will be empty instead of solid green

**Expected behavior**
Polygons should be filled.

The issue comes from this line of code:
 if (this.sourceTileCache.containsKey(tileUrl)) in ol/source/VectorTile
and it's because all tileUrls for a specific feature when the tile is completely contained in the polygon will look similar to this:
data:application/json;charset=UTF-8,{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-64,4160],[-64,-64],[4160,-64],[4160,4160],[-64,4160]]]},"properties":{"name":"Italy"}}]} 
It's not really a bug in OpenLayers but it's still not working properly.

As a workaround I just need to set a property unique for differentiate same features in different tiles. I use the z/x/y combined string for this.

bonus question: I couldn't figure it out why using Math.random() in the replacer doesn't render any tile at all.

If you think there is nothing to fix here, maybe it could just be mentioned in the example for future reference

**Comment by mike-000** [comment]
It happens when a polygon's perimeter lies entirely in the tile's buffer zone.  Setting the geojsonvt buffer option to -1 is a workaround which allows fill but leaves tile edges visible.  As this is not a problem for MVT format it looks like an OpenLayers issue.

**Comment by amshel** [comment]
buffer: -1 doesn't solve the issue but it makes it happen less. As I wrote in the description, the issue is related to using the tileUrl as a key to check if the sourceTileCache contains already a certain tile, usually these urls will be all different as they contains z x y somewhere in the template. In this case close tiles have exactly the same geojson content and OpenLayers doesn't do anything with them

**Comment by mike-000** [comment]
That can be fixed by using the coordinates as the url and moving the data retrieval to the tile load function by wrapping the default load function inside a custom one https://codesandbox.io/s/geojson-vt-3472w
