### ISSUE TITLE
Why use array to represent coordinates, not an object

### ISSUE THREAD

**Issue by iamplex** [openlayers/openlayers#10938]
Hi, this isn't a issues, just my personal-question, actually, I've been [fixed a bug](https://github.com/openlayers/openlayers/pull/8396) for this project a long ago

I was confusing about coordinates in this project: **why use two-dimensional array like `Array<Array<Number>>`,  not `Array<Object { x, y }>`**, is there have performance reason such as access array faster than object or something like that?

**Comment by ahocevar** [comment]
Primarily it was a design decision, but you could think of several reasons: Coordinates can also have more than two dimensions. Arrays are easier to flatten than object literals. The notation we use is closer to GeoJSON.
