### ISSUE TITLE
Surprise dependency - Map controls broken without ol.css from v6.2.0 onwards.

### ISSUE THREAD

**Issue by StereoPythonics** [openlayers/openlayers#10932]
**Describe the bug**
From v6.2.0 onwards Dragging and mouse wheel zooming will no longer work unless ol.css is also loaded.

**To Reproduce**
Included example works correctly only with stylesheet link included.

```
<html>
	<head>
		<title>CSS dependency example</title>
		<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,requestAnimationFrame,Element.prototype.classList,URL"></script>
		<link rel="stylesheet" href="https://openlayers.org/en/latest/css/ol.css">
		<script                 src="https://openlayers.org/en/latest/build/ol.js"></script>
	</head>
	<body>
		<div id="map" class="map"/>
		<script>
			var centre = ol.proj.fromLonLat([1,51]);
			var map = new ol.Map({
				view: new ol.View({
					center: centre,
					zoom: 10
				}),
				layers: [
					new ol.layer.Tile({
					source: new ol.source.OSM()
					})
				],
				target: 'map'
			});
		</script>
	</body>
</html>
    
```

**Expected behavior**
No dependency on css for basic panning and zooming functionality, as was the case before 6.2.0. 

**Suggestion**
If this hard requirement for paired css is here to stay, can the 6.2.0 release notes / getting started guide / examples reflect this more explicitly please? Current examples such as the [Interaction Options](https://openlayers.org/en/latest/examples/interaction-options.html) example don't reflect this yet.

I'm happy to muck in with documentation edits if desired by the team. Let me know what you think?

**Comment by ahocevar** [comment]
This is a valid concern @StereoPythonics. I created #10936 to make these basic interactions work without loading `ol.css` again.

**Comment by StereoPythonics** [comment]
Looks great, example now works fine with latest without ol.css. Many thanks for your efforts, I look forward to the 6.3.2 release!
