### ISSUE TITLE
Cannot modify features with touch

### ISSUE THREAD

**Issue by anthonn** [openlayers/openlayers#10940]
**Describe the bug**
If trying to modify features when using touch (tested on mobile (Android 10 and chrome) and chrome desktop debug device: pixel 2), the features do not move or move just a part of the touch movement.

**To Reproduce**
Either by using mobile or chrome desktop mobile debug try editing features in these openlayers official examples:
https://openlayers.org/en/latest/examples/draw-and-modify-features.html?q=modify
https://openlayers.org/en/latest/examples/modify-features.html?q=modify

**Comment by zj91zj** [comment]
I don‘ know how to fix it. could you tell me directly, thanks?
