### ISSUE TITLE
backgroundFill color not respected when declutter is used

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10949]
**Describe the bug**
All labels are displayed with the same backgroundFill color if declutter is specified.

**To Reproduce**
Without declutter even numbers have red backgroundFill, odd number blue
https://codesandbox.io/s/cluster-dq6it

If declutter is specified all numbers appear with the same color, either red or blue
https://codesandbox.io/s/cluster-cox1t

**Expected behavior**
The backgroundFill of the individual style should be used regardless of decluttering.

**Comment by ahocevar** [comment]
Didn't I fix this in #10738 already?

**Comment by ahocevar** [comment]
Any ideas for a fix? Pull request welcome.

**Comment by djibarian** [comment]
More light: It seems that you can have labels mixed with backgroundFill defined and undefined. What you can’t have is labels with different backgroundFills.

**Comment by d3mon187** [comment]
It appears this issue has returned, at least as of v6.9.

**Comment by mike-000** [comment]
> It appears this issue has returned, at least as of v6.9.

The example in #11189 is still working when updated to the latest version https://codesandbox.io/s/vibrant-wright-kidpb?file=/main.js

**Comment by d3mon187** [comment]
Nevermind, my test page was still using 6.3.1, while the rest of the environment is upgraded to 6.9.  SORRY!!!
