### ISSUE TITLE
ImageArcGISRest will not display when initialized outside the map view extent

### ISSUE THREAD

**Issue by johnnylc** [openlayers/openlayers#10952]
A ImageArcGISRest ImageLayer will never show on map, when the map initial extent not including it.
Here's the code forked from https://openlayers.org/en/latest/examples/arcgis-image.html

https://codesandbox.io/s/arcgis-image-dfl8c

1, I modified the map view's initial center to: fromLonLat([102, 39.91]). That is far from where the ImageLayer, so the ImageLayer cannot be seen when lauched. 
2, When moving the map to the ImageLayer's region (America), it will never show up.

**Expected behavior**
The ImageLayer will show on map when it's in the viewport, no matter how the map is initialized.

**Comment by mike-000** [comment]
You example works if you pan across Europe to America, but not if you pan across the Pacific (because image sources don't support wrapX).

**Comment by johnnylc** [comment]
> You example works if you pan across Europe to America, but not if you pan across the Pacific (because image sources don't support wrapX).

Thanks, do you have any suggestion for handling this condition, or need to modify some settings?

**Comment by mike-000** [comment]
For maps which cross the dateline one option is to use a projection centered on the dateline https://codesandbox.io/s/arcgis-image-b4cdy but that means it wouldn't wrap if you pan via Europe, and the view may not be compatible with some other sources you might wish to use (such as vector tiles).
