### ISSUE TITLE
view.fit with duration no longer works

### ISSUE THREAD

**Issue by bryanSME** [openlayers/openlayers#10959]
**Describe the bug**
Using `view.fit` with a duration greater than 0 **does not always work**.   It was previously working on version 5.x but does not work on 6.3.1. 

**To Reproduce**
```
view.fit([-1000,-1000,1000,1000], { duration: 500 })
// or use the default of 1000
view.fit([-1000,-1000,1000,1000])
```

When it does work, `updateAnimations_` in **src/View.js** gets called repeatedly.  When it doesn't work, `updateAnimations_` only gets called one time.

**Expected behavior**
the viewport pans/zooms to the extent

**Comment by ahocevar** [comment]
Can you please share a minimal example that exposes the issue?

**Comment by bryanSME** [comment]
> Can you please share a runnable

@ahocevar what is the best way to do this? Should I use something like jsfiddle or is there another preferred method?

**Comment by ahocevar** [comment]
@bryanSME https://codesandbox.io/ is what we recommend, because it works with npm packages. You can go to any example under https://openlayers.org/en/latest/examples/ and click the "Edit" button to get a codesandbox for that example as a starting point.

**Comment by hkostia** [comment]
I'm also experiencing this after upgrading from 5.x to latest 6.3.1.

**Comment by ahocevar** [comment]
@jahow, can you take a look at this please?

**Comment by hkostia** [comment]
Our implementation had calls to map.updateSize() (to fix some iOS related problems: container size gets the proper dimensions with some delay) which eventually calls view.cancelAnimations() and leads to this situation.

**Comment by jahow** [comment]
hi @bryanSME @hkostia, could you please provide a reproduction of the issue following instructions given by @ahocevar? I have attempted to reproduce it locally but failed. Thanks!

**Comment by hkostia** [comment]
To mimic the behavior we had: Call map.updateSize() while view.fit() animation is ongoing. I guess this is not a bug but a bugfix from version 5.x behavior.

**Comment by jahow** [comment]
Then I guess this should have fixed the issue you encountered: https://github.com/openlayers/openlayers/pull/10865

Unfortunately this fix didn't make it into the 6.3.1 release.

Could you please check if this is still happening using the latest build? `npm install ol@dev`

**Comment by bryanSME** [comment]
@jahow 

I just tried this on `ol@dev` and it seems to be fixed.

**Comment by ahocevar** [comment]
It might be that this only does not work when the view is not defined yet (i.e. when `View#isDef()` returns false).
