### ISSUE TITLE
forEachLayerAtPixel cannot get pixel values when there are XYZ tiles

### ISSUE THREAD

**Issue by olizhu** [openlayers/openlayers#10953]
**Describe the bug**
I am using the `forEachLayerAtPixel` function to get the rgb value of pixels on a custom XYZ tileset. However, I only get blank arrays for the pixel values.

After some testing, it appears that when XYZ tiles are on the map, pixel arrays return empty for all visible layers.

**To Reproduce**
1. Go to https://codesandbox.io/s/xyztiles-hyq92?file=/index.js
2. Hover over the map and in the console, array values should all appear empty
3. Change line 12 to `visible: false` and array values are appearing as expected

**Expected behavior**
The correct pixel values should be returned when there is an XYZ tileset present. Ideally, I need to be able to read the values on the XYZ source, but in any case, it should not be blocking other layers.

**Comment by mike-000** [comment]
You have tainted canvas because XYZ sources do not have a default `crossOrigin` setting.  You need to add `crossOrigin: 'anonymous'` to the XYZ source options.

**Comment by olizhu** [comment]
Mike, thanks very much. I hadn't considered that and your suggestion fixes the problem.
Closing the issue.
