### ISSUE TITLE
Openlayers cause runtime error when using in Angular Universal application

### ISSUE THREAD

**Issue by thanhdn1989** [openlayers/openlayers#10954]
**Describe the bug**
I have an Angular Universal application (Server side rendering), when use Openlayers inside my app, it cause the error: window is not define. Even though i have mock the window object with [Domino](https://github.com/fgnass/domino).
As far as I see, the Openlayers call some browser API (window, document in this case) directly, for ex: in has.js, Openlayers try to get devicePixelRation via window

**To Reproduce**
1. Create an angular universal app
2. Install openlayers package
3. Serve the application
4. CLI will throw the error

**Expected behavior**
Openlayers can work nicely with Server side rendering application

**Comment by ahocevar** [comment]
Duplicate of #8846.
