### ISSUE TITLE
Mouse Interactions don't work after upgraded to 6.x

### ISSUE THREAD

**Issue by bryanSME** [openlayers/openlayers#10957]
**Describe the bug**
After upgrading to OL6.x, I can't seem to get any of the mouse interactions to work.  The map still functions using things like, `View.fit(extent)` or the zoom in/out buttons.  

**To Reproduce**
```
import Map from 'ol/Map';
var map = new Map({
  layers: [
    new LayerTile({
      source: new XYZ({
        url: 'http://a.tile.openstreetmap.org/{z}/{x}/{y}.png'
      })
    })
  ],
  view: new View({ center: [0, 0], zoom: 3 }),
});
```
The Interactions all seem to be there, `map.getInteractions().getArray()`
![image](https://user-images.githubusercontent.com/16226280/80216782-9671ee80-860c-11ea-90f2-5e99cd25dd5a.png)

**Comment by fredj** [comment]
This issue was fixed with #10936
