### ISSUE TITLE
build-index TypeError: indexAll is not a function 

### ISSUE THREAD

**Issue by VINOlive** [openlayers/openlayers#10965]
build-index TypeError: indexAll is not a function 

![ol](https://user-images.githubusercontent.com/7323049/80326222-9c650b00-886a-11ea-8df2-bd34fa3e43ee.png)

anyhelp thank u
ol version :5.3.0

**Comment by ahocevar** [comment]
I think you'll need a newer version of node do build OpenLayers successfully.
