### ISSUE TITLE
Inconsistency in opacity documentation

### ISSUE THREAD

**Issue by Kai-W** [openlayers/openlayers#10964]
i stumbled upon my bug again https://github.com/openlayers/openlayers/issues/10236

The JS Doc doesnt match the implementation of the option opacity in some cases:

Js Files in ol/scource/ for property opacity:
TileSource (in Tile.js):
jsdoc no default for opacity
sets opaque to false if undefined.

UrlTile extends Tile
jsdoc no default  for opacity
constructor passes on opaque from options to super without modification

TileImage extends UrlTile
jsdoc: default opaque=true
constructor passes on opaque from options to super without modification

XYZ extends TileImage
jsdoc: default opaque=true
constructor passes on opaque from options to super without modification

OSM extends XYZ
jsdoc: default opaque=true
defaults to true if options.opqaue is undefined

So OSM is the only Layer scource that behaves according to the jsdoc (default is true) but is also the only one that behaves not like the others. They default to opaque=false despite the js doc says otherwise.

**Comment by ahocevar** [comment]
@Kai-W A pull request that fixes the API docs would be appreciated. Thanks for your continued effort on this.
