### ISSUE TITLE
Vector tiles selection bug

### ISSUE THREAD

**Issue by dioslibre** [openlayers/openlayers#10962]
**Describe the bug**
When selecting vector tiles in vector mode, a canvas element gets added to the bottom of the page, for every selected feature. See https://openlayers.org/en/latest/examples/vector-tile-selection.html

**To Reproduce**
1. Select a feature
2. A canvas element should be added to the bottom of the page

**Expected behavior**
When selecting a feature, Nothing should get added anywhere in the page.

**Comment by Janexr** [comment]
+1

And the map service used says that Taiwan's sovereignty belongs to Taiwan and violates China's sovereignty

**Comment by ahocevar** [comment]
This issue was fixed with #10879.

**Comment by mrpan** [comment]
> +1
> 
> And the map service used says that Taiwan's sovereignty belongs to Taiwan and violates China's sovereignty

+1
