### ISSUE TITLE
Not work example "Icon Sprites with WebGL" (build for browser)

### ISSUE THREAD

**Issue by cpsTinK** [openlayers/openlayers#10961]
Trying to repeat the "**Icon Sprites with WebGL**" example in the browser results in the error:
_Uncaught TypeError: ol.layer.WebGLPoints is not a constructor_

The implementation of the example: https://jsfiddle.net/freerus/sfLo8edt/

Please tell me a working example for the browser.

**Comment by kamillasak** [comment]
Same problem here

**Comment by ahocevar** [comment]
@jahow, can you take a look at this please?

**Comment by kamillasak** [comment]
Any news?

**Comment by jahow** [comment]
Duplicate of https://github.com/openlayers/openlayers/issues/10089
The webgl layer class is not part of the legacy build as it is experimental.

**Comment by kamillasak** [comment]
Are you planning in the near future add webGL to legacy build?

**Comment by jahow** [comment]
I would not say there is a precise plan, no. Eventually the webgl renderer will be considered stable and have its experimental tag removed.
