### ISSUE TITLE
WMTS optionsFromCapabilities ignores WGS84BoundingBox when creating WMTS Source

### ISSUE THREAD

**Issue by nielsmeijer** [openlayers/openlayers#10979]
Like #10974, another regression with WMTS optionsFromCapabilities between version OL 6.1.1 and 6.3.1.

In v6.1.1, the WMTS.optionsFromCapabilities creates an WMTS Source/TileGrid that respects the WGS84BoundingBox:

https://github.com/openlayers/openlayers/blob/e4be8309f7880c322c9850a634dab8b6adc30c62/src/ol/source/WMTS.js#L380-L398

In v6.3.1, the extent of the TileGrid is calculated based on the first TileMatrix.

https://github.com/openlayers/openlayers/blob/af9f26b9d343e5496ea44a729265c4002616b240/src/ol/source/WMTS.js#L381-L400

The change seems to be introduced in commit https://github.com/openlayers/openlayers/commit/98e8bec3709364b5fd14dd71a4e4e72dcf4ae1c9

This can easily create a bounding box that is too large. For example a WMTS layer containing Europe with WGS84BoundingBox

 ```xml
<ows:WGS84BoundingBox>
<ows:LowerCorner>-36.0 15.0</ows:LowerCorner>
<ows:UpperCorner>43.0 90.0</ows:UpperCorner>
</ows:WGS84BoundingBox>
```

In v6.1.1, the tile grid will have a correct extent of [-36, 15, 43, 90]. 
In v6.3.1, the tile grid will have an incorrect extent of [-180, -90, 180, 90].  The calculation is based on TileMatrixLimits level 0, which spans the whole world. 

Because of this change, there are unnecessary HTTP requests to WMTS tiles that do not exist outside the WMTS bounding box area.

**Comment by ahocevar** [comment]
@nielsmeijer Do you think you'd be able to create a pull request that fixes this issue? Also with tests? Would be much appreciated.
