### ISSUE TITLE
Panning and zooming in shadow root not working with Firefox for Android

### ISSUE THREAD

**Issue by heikkiy** [openlayers/openlayers#10978]
**Describe the bug**
Panning and zooming a map which is in a shadow root doesn't work in Firefox for Android. Tested with multiple Android devices ranging from versions 7 to 10 with Firefox for Android version 68.7.0. Related PR to this problem was: https://github.com/openlayers/openlayers/pull/10698. But this still happens on Firefox for Android.

**To Reproduce**
1. With your Android device and Firefox for Android version 68.7.0 go to: https://openlayers.org/en/latest/examples/es2015-custom-element.html
2. Try to pan and pinch zoom the map
3. For us nothing happens

**Expected behavior**
Expecting to be able to pan and pinch zoom the map.

**Comment by ahocevar** [comment]
I have no Android device to test this right now. But can you please test if the issue still occurs with https://openlayers.org/en/master/examples/es2015-custom-element.html ? Thanks.

**Comment by heikkiy** [comment]
> I have no Android device to test this right now. But can you please test if the issue still occurs with https://openlayers.org/en/master/examples/es2015-custom-element.html ? Thanks.

Unfortunately no it doesn't seem to work.

**Comment by DaniEll-AT** [comment]
See issue #10128 - Firefox on Android (like Safari on iOS12) has no native Pointer Events...

**Comment by ahocevar** [comment]
In this case it might help to load [pepjs](https://npmjs.com/package/pepjs) before OpenLayers.
