### ISSUE TITLE
WMTS optionsFromCapabilities creates invalid tile grid when coordinate system is in degrees

### ISSUE THREAD

**Issue by nielsmeijer** [openlayers/openlayers#10974]
I discovered a regression between OL 6.1.1 and 6.3.1 with WMTS sources created from a WMTS capabilities document. 
The layer tileGrid extent is reported incorrectly in v6.3.1. When calling `layer.getTileGrid().getExtent()`, `[-180, -20037418.342789233, 40074836.685578465, 90]` is returned instead of the expected result of `[-180, -90, 180, 80]` 

v6.1.1:
https://github.com/openlayers/openlayers/blob/e4be8309f7880c322c9850a634dab8b6adc30c62/src/ol/source/WMTS.js#L380-L396

v6.3.1:
https://github.com/openlayers/openlayers/blob/af9f26b9d343e5496ea44a729265c4002616b240/src/ol/source/WMTS.js#L382-L394

The matrix ScaleDenominator is multiplied by the default pixel size of 0.28mm. This returns an incorrect extent for a tile matrix with a coordinate system that is not in meters. 

The scale should be divided by projection.getMetersPerUnit() as in ol/tilegrid/WMTS
https://github.com/openlayers/openlayers/blob/e4be8309f7880c322c9850a634dab8b6adc30c62/src/ol/tilegrid/WMTS.js#L165)

**Comment by ahocevar** [comment]
@nielsmeijer Thanks for reporting this. Would you be able to provide a pull request, preferably with a regression test added so this does not happen again?

**Comment by nielsmeijer** [comment]
@ahocevar I've submitted a pull request.
