### ISSUE TITLE
Map on click event is fired when clicking on controls like the zoom-buttons

### ISSUE THREAD

**Issue by BHDBvde** [openlayers/openlayers#10980]
**Describe the bug**
Situation: Polymer 3 project
When using map.on('click', functionxxx) the function is executed when clicking on a control like th zoom-button

**To Reproduce**
1. Unzip [olinpolymer.zip](https://github.com/openlayers/openlayers/files/4552128/olinpolymer.zip)
2. Go to the unpacked folder
3. npm install
4. npm run start
5. Click on a zoom-button
6. The clicked pixel is logged in the browser console
**Expected behavior**
Not firing the event/not executing the function

**Comment by ahocevar** [comment]
Interesting. The same can be seen with the `es2015-custom-element.html` example when a click listener is added.

If anyone has an idea for a fix, please submit a pull request.

**Comment by BHDBvde** [comment]
@walkermatt 
Do you think this is related?
https://github.com/openlayers/openlayers/issues/6948#issuecomment-565375694

**Comment by walkermatt** [comment]
It certainly is strange. I've just added a `singleclick` handler to the map in the `es2015-custom-element.html` and `simple.html` examples and debugged `PlugableMap#handleMapBrowserEvent` when clicking the zoom in button. The `target` in `simple.html` is the `button` element but the `target` in the `es2015-custom-element.html` example is the `ol-map` element...

**Comment by walkermatt** [comment]
I've a feeling the event is retargeted due to the listener being added to document which is outside of the shadow DOM.

https://github.com/openlayers/openlayers/blob/master/src/ol/MapBrowserEventHandler.js#L244

**Comment by BHDBvde** [comment]
That could be it.
For now our solution/workarround is using and setting the controls with a separate target and styling it.
https://openlayers.org/en/latest/apidoc/module-ol_control_Control-Control.html: Specify a target if you want the control to be rendered outside of the map's viewport.

**Comment by ahocevar** [comment]
Thanks for the good investigations, they made it easy for me to come up with the fix I submitted as pull request #11024.

**Comment by BHDBvde** [comment]
Tested with the dev-branch and it works!

**Comment by VinoSakthi** [comment]
@ahocevar  Please tell when this will released ,
we are facing this issue with our angular project where on clicking the zoom DOM element (click) is fired

**Comment by VinoSakthi** [comment]
> Tested with the dev-branch and it works!

@ahocevar @BHDBvde   This issue still exists in angular project , if we add click for whole Card and click the zoom buttons ,click through is happening
