### ISSUE TITLE
Reprojection is broken in Internet Explorer

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#10988]
**Describe the bug**
Reprojection in master fails in Internet Explorer.

**To Reproduce**
Open https://openlayers.org/en/master/examples/index.html in Internet Explorer and search for reprojection All the examples will fail due to an unsupported call to `Math.log2()`

**Expected behavior**
For browser compatibility `Math.log2()` can be replaced by `Math.LOG2E * .Math.log()`

**Comment by ahocevar** [comment]
Pull request with a `log2()` utility function in `src/ol/math.js` welcome.
