### ISSUE TITLE
Map not respecting that the earth is round

### ISSUE THREAD

**Issue by yohny** [openlayers/openlayers#10992]
Longitude gets increased infinitely when map is moved to the east (and decreased infinitely moving to the west)

**Steps o Reproduce**
1. Go to OL example at https://openlayers.org/en/latest/examples/geographic.html
2. Remember the lat/lon coordinates written on the screen
3. Move 'around the world' to the east until you come roughly to the same spot (easier to do if you zoom out)
4. The new coordinates should be roughly the same as the ones in point 2., but that's not the case for longitude - it was increased by one earth roundtrip (360deg).

This behaviour occurs also when you calculate the lat/lon coordinates from view extent, for example in `moveend` event:
```js
map.on('moveend', function(evt) {
  var extentLatLonCoords =
    transformExtent(evt.frameState.extent, evt.map.getView().getProjection(), 'EPSG:4326');
})
```

**Expected behavior**
If you go 'around the world' and arrive at the same spot the calculated coordinates/extent should be the same and respect the fact that the earth is round :smile:

**Comment by mike-000** [comment]
"Wrapped" coordinates are intentional and allow geometries to cross the dateline https://codesandbox.io/s/geographic-b39gm

**Comment by yohny** [comment]
wrapped coordinates are fine when you are adding geometries to map, but when you 'ask the map' where a given point is (or what the map boundaries are) you expect a real coordinates

**Comment by mike-000** [comment]
`toLonLat` can be used to return "real world" values, for example
`var center = toLonLat(view.getCenter(), getUserProjection());`

**Comment by yohny** [comment]
as `toLonLat()` solves my issue, I'm fine with closing this
just one more question - `toLonLat` unwraps coordinates for EPSG:4326 projection, but is there a build in way to unwrap other projections?

**Comment by mike-000** [comment]
There is an internal (non-API) method https://github.com/openlayers/openlayers/blob/master/src/ol/coordinate.js#L412
