### ISSUE TITLE
Geolocation tracking stops after error is encountered

### ISSUE THREAD

**Issue by yohny** [openlayers/openlayers#10995]
**Describe the bug**
The Geolocation object stops emitting `change` events after the error is encountered, even when the location comes back (for example GPS signal is lost and then comes back)

**Step To Reproduce**
Its possible to simulate the issue using chrome dev tools, as they allow you to arbitrary manipulate returned location.
1. Go to https://openlayers.org/en/latest/examples/geolocation.html using Chrome browser
1. In Chrome Dev tools -> Sensors set your fake location (or use real one)
![Screenshot from 2020-05-03 21-27-17](https://user-images.githubusercontent.com/5924185/80923622-1161a480-8d85-11ea-985c-78446a3afee9.png)
1. Below the map check `track position` to start location tracking
1. Keep changing your location - the position marker on the map keeps relocating as expected
1. Change the fake location to Error Location Unavailable - error is raised
1. Change location to some other fake location - no change is propagated

**Expected behaviour**
Change events are emitted when the geolocation is restored after error.

**Comment by fredj** [comment]
Thanks for the bug report @yohny. What about stopping the tracking only if the user denied the geolocation?

**Comment by yohny** [comment]
I would not stop tracking at all when error is raised. User can reveoke the permissions just temporarily and then give it back, in which case you would like the tracking to continue. The best approach according to my opinion would be to keep raising error/change/whatever events as they happen until user explicitly stops tracking by `setTracking(false)`

**Comment by fredj** [comment]
yes, I agree that the tracking should not automatically stop on error
