### ISSUE TITLE
VectorTileLayer.getFeature adds a visible canvas and does not release the canvas

### ISSUE THREAD

**Issue by cppmyjob** [openlayers/openlayers#11009]
**Describe the bug**
VectorTileLayer.getFeature adds visible a canvas and does not release the canvas

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/vector-tile-selection.html
2. Click on any country on the map
3. Go to bottom of the page - see visible canvas
4. Change map's zoom and click on a country again
5. You will see a second canvas at the page bottom
6. Repeat steps 4,5

**Expected behavior**
Do not add visible canvas and release unused canvas

**Comment by ahocevar** [comment]
This was already fixed with #10879. See https://openlayers.org/en/master/examples/vector-tile-selection.html for the current version.
