### ISSUE TITLE
FrameState.extent has of wrong type

### ISSUE THREAD

**Issue by yohny** [openlayers/openlayers#11008]
**Describe the bug**
Documentation at https://openlayers.org/en/latest/apidoc/module-ol_PluggableMap.html#~FrameState states that FrameState's `extent` property should be of type `Extent` (https://openlayers.org/en/latest/apidoc/module-ol_extent.html#~Extent) but in reality its `number[]`

**Comment by M393** [comment]
An Extent is just a typedef for an array with numbers. It is described in the site you linked:
> https://openlayers.org/en/latest/apidoc/module-ol_extent.html#~Extent
