### ISSUE TITLE
vertortile

### ISSUE THREAD

**Issue by qmdmmbmp** [openlayers/openlayers#11016]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Comment by qmdmmbmp** [comment]
![image](https://user-images.githubusercontent.com/21305085/81280511-2b53fd80-908b-11ea-8c25-8483e2ddb4ff.png)
point Circle is cropped

**Comment by ahocevar** [comment]
Looks like the tiles you are using lack a buffer. You can work around this data problem by setting the `declutter` option on the layer to `true`, but then not all circles will be rendered of course.

**Comment by qmdmmbmp** [comment]
thanks
