### ISSUE TITLE
Heatmap is not captured v6.3.1

### ISSUE THREAD

**Issue by YuK1Game** [openlayers/openlayers#11014]
How to capture Heatmap Layer?

```App.js
import React, { useEffect, useState, useCallback, useRef } from 'react';
import styled from 'styled-components';
import { Map, View, Feature } from 'ol';
import { OSM as OSMSource, Vector as VectorSource } from 'ol/source';
import { Tile as TileLayer, Heatmap as HeatmapLayer } from 'ol/layer';
import { Point } from 'ol/geom';
import 'ol/ol.css';

const App = () => {

  const mapRef = useRef(null);

  const tileLayer = new TileLayer({
    source: new OSMSource(),
    preload : 1,
  });

  const heatmapLayer = new HeatmapLayer({
    source : new VectorSource({
      features : [
        new Feature({ geometry : new Point([ -6005420.749222653, 6000508.181331601 ]) }),
        new Feature({ geometry : new Point([ -6015421.749222653, 6010507.181331601 ]) }),
        new Feature({ geometry : new Point([ -6025422.749222653, 6020506.181331601 ]) }),
        new Feature({ geometry : new Point([ -6035423.749222653, 6030505.181331601 ]) }),
      ],
    }),
    declutter : true,
  });

  const map = new Map({
    target : undefined,
    layers : [ tileLayer, heatmapLayer ],
    view: new View({
      center: [-6005420.749222653, 6000508.181331601],
      zoom: 9
    }),
  });

  useEffect(() => {
    map.setTarget(mapRef.current);
    return () => map.setTarget(undefined);
  }, [ mapRef.current ]);

  const [ capture, setCapture ] = useState(null);

  const handleCapture = useCallback(() => {
    const canvas = document.getElementsByTagName('canvas')[0];
    setCapture(canvas.toDataURL());
  }, []);

  return (
    <Container>
      <MapLayer id={`map`} ref={ mapRef }></MapLayer>
      <button onClick={ handleCapture }>Capture</button>
      <ImageLayer>
        {capture && (
          <img src={ capture } />
        )}
      </ImageLayer>
    </Container>
    
  )
}

const Container = styled.div`
  display : flex;
`;

const MapLayer = styled.div`
  width : 640px;
  height : 480px;
`;

const ImageLayer = styled.div`
  width : 640px;
  height : 480px;
`;

export default App;

```

https://codesandbox.io/s/gracious-pascal-uu7pw?fontsize=14&hidenavigation=1&theme=dark

thanks.

**Comment by mike-000** [comment]
The heatmap layer is in the second canvas.  It is also webgl based and needs the preserveDrawingBuffer webgl context attribute to be set for toDataURL() to work https://codesandbox.io/s/gallant-water-m1n59

**Comment by mike-000** [comment]
Current export map example updated to include a Heatmap layer https://codesandbox.io/s/export-map-ol904

**Comment by 1Steamwork1** [comment]
The export map example with heatmap support seems to displace the heatmap features away from their original positions.
Is there any way to retain their positions as shown on the map? I was hoping the `transform` style attribute could be used, as it is for vector layers, but heatmaps do not appear to have a default value set for `style.transform`. Any ideas?

For reference, here is the map:
![image](https://user-images.githubusercontent.com/43868328/108916201-98df1380-7636-11eb-8b9c-54eef1db01db.png)

And here is the saved image:
![image](https://user-images.githubusercontent.com/43868328/108916274-b0b69780-7636-11eb-966a-5fcbb9de5584.png)

**Comment by mike-000** [comment]
The problem occurs when pixel ratio is not 1.  The canvas has `style.width` and `style.height` properties instead of `style.transform` as there is never any rotation, but you can use those to create a transform matrix https://codesandbox.io/s/export-map-forked-1qc33
