### ISSUE TITLE
Could ol/style/Text has a border or background with round corner?

### ISSUE THREAD

**Issue by antield** [openlayers/openlayers#11013]
Could ol/style/Text has a border or background with round corner? Such as border-radius property setting on CSS3.
![image](https://user-images.githubusercontent.com/48746947/81148766-73055700-8faf-11ea-93a6-a655e1547656.png)
The above is the effect achieved by Amap api.
By OpenLayers, I try to set backgroundFill and backgroundStroke, but I only get right-angle rectangle background.

**Comment by th30d0r** [comment]
yes please. That would be amazing :D

**Comment by Vin4er** [comment]
hello, need borderRadius on Text

I have:
<img width="132" alt="image" src="https://github.com/openlayers/openlayers/assets/1014184/011c64cc-b291-41bb-9744-aba12109ce25">

i need:
<img width="184" alt="image" src="https://github.com/openlayers/openlayers/assets/1014184/08172187-b1d4-41c7-acba-b012af6dd3c3">

**Comment by ahocevar** [comment]
Not directly. You have two options to achieve what you're looking for:

1. Use `ol/Overlay` for the labels, instead of a `Text` style.
2. Create an icon with the desired shape (rounded corners, correct width and height), and use it as additional `Icon` style.

**Comment by Vin4er** [comment]
@ahocevar hm
I don't know the exact measurements of text width

**Comment by lewayjack** [comment]
if you dont need a stroke , a Text style with  backgroundStroke: new Stroke({
        color: 'same color with background',
        width: 16,
        lineCap: 'round',
        lineJoin: 'round',
      }),

**Comment by RodolfoSilva** [comment]
> if you dont need stroke , a Text style below with backgroundStroke will do the job. `backgroundStroke: new Stroke({ color: 'same color with background', width: 16, lineCap: 'round', lineJoin: 'round', }), `

This solution works, only if you are using solid colors. Thanks @lewayjack.

**Comment by sugar3103** [comment]
> if you dont need stroke , a Text style below with backgroundStroke will do the job. `backgroundStroke: new Stroke({ color: 'same color with background', width: 16, lineCap: 'round', lineJoin: 'round', }), `

you saved my day, thank you with heart
