### ISSUE TITLE
openlayers 6 not working with vue web component

### ISSUE THREAD

**Issue by bnping** [openlayers/openlayers#11015]
Version
2.6.11

Reproduction link
https://codesandbox.io/s/bold-matsumoto-tpxsn?file=/src/App.vue

Steps to reproduce
First you can see the link to minimal production that work very well.
To produce the bug:

Download the project using or execute npm run build-component. This will run:
vue-cli-service build --target wc --name openlayers-vue ./src/components/MapContainer.vue
Go to dist, then open demo.html. As you can see, openlayer not working any more.
What is expected?
I must see the map works in dev mode and prod mode (web component)

What is actually happening?
The map is working only in dev mode .

**Comment by fredj** [comment]
Probably related to #10932: with ol version 6.3.1, `ol.css` must be included for the interaction to work.

**Comment by bnping** [comment]
@fredj  thanks but  the pb is openlayers not mount the html element as you can see here, the dev is empty.
![image](https://user-images.githubusercontent.com/63243110/81278996-c979a080-9056-11ea-910a-cf06a7da7672.png)

**Comment by fredj** [comment]
I can't help with Vue but I've loaded `dist/demo.html` and when the OpenLayers Map constructor is called, the target element is not present in the page (`document.getElementById('mapOL')` is `null`)

**Comment by bnping** [comment]
@fredj, thanks. Now i am using another method in vue that allow us to get html element. So what is have now  is mounted openlayers with zoom control but without canvas.
#DOM image:
![image](https://user-images.githubusercontent.com/63243110/81298449-14a2ac00-9075-11ea-9ae4-a028848808d2.png)
#browser result (only zoom control is showing)
![image](https://user-images.githubusercontent.com/63243110/81298634-529fd000-9075-11ea-8f58-4fb15fe0a124.png)

**Comment by Kiyoaki-w** [comment]
> @fredj, thanks. Now i am using another method in vue that allow us to get html element. So what is have now is mounted openlayers with zoom control but without canvas.
> #DOM image:
> ![image](https://user-images.githubusercontent.com/63243110/81298449-14a2ac00-9075-11ea-9ae4-a028848808d2.png)
> #browser result (only zoom control is showing)
> ![image](https://user-images.githubusercontent.com/63243110/81298634-529fd000-9075-11ea-8f58-4fb15fe0a124.png)
> 
> I can not understand why openlayers is not putting canvas inside html element.

Try to remove the style **'display: none'** of **'ol-unselectable ol-layers'** element.

**Comment by bnping** [comment]
@Kiyoaki-w same thing. No map canvas in the html DOM.
![image](https://user-images.githubusercontent.com/63243110/81432092-945a7480-9162-11ea-93fa-99a028ca9df7.png)

**Comment by ahocevar** [comment]
https://codesandbox.io/s/vibrant-kepler-6wvjb seems to work fine for me. Can you confirm?

**Comment by bnping** [comment]
@ahocevar, thank to your participation in this ticket. So the example that you indicated is  dev mode or in dev version, in this case, openlayers works.  **But in web component prod version,**  like this demo.html example https://github.com/bnping/openlayers6-web-vue, Openlayers is not putting canvas in the html dom, so their is no map. I see only the zoom control buttons.

 I asked the vue core team about this, they said that this is a pb in Openlayers and for this reason, i am here try to find a solution.

**Comment by bnping** [comment]
thanks you all, i found the solution. Here is the working example
https://codesandbox.io/s/adoring-worker-i9k3d?file=/index.html

**Comment by ahocevar** [comment]
I've been using Vue successfully with OpenLayers in production mode. But I do not use web components.

**Comment by bnping** [comment]
@ahocevar  Now we have a working example that  can used by the community.
