### ISSUE TITLE
Blend Example not working

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#11020]
**Describe the bug**
https://openlayers.org/en/latest/examples/blend-modes.html does not work

**To Reproduce**
Go to https://openlayers.org/en/latest/examples/blend-modes.html

**Expected behavior**
Example needs to work

**Comment by fredj** [comment]
Duplicate of #10505

**Comment by ahocevar** [comment]
Removed old assets from https://openlyers.org/en/latest/
