### ISSUE TITLE
got a blank view after setCenter

### ISSUE THREAD

**Issue by chenjunweii** [openlayers/openlayers#11021]
I got a blank view after

`map.getView().setCenter()`

I've tried different longitude latitude and some of them would not result in blank view but some of them did, even those lonlat is correct, 

any idea ?

**Comment by ahocevar** [comment]
Try
```
map.getView().setCenter(fromLonLat(lon, lat));
```

**Comment by chenjunweii** [comment]
@ahocevar I think I found the problem, I make a mistake at backend, which makes the order of lonlat wrong, so I got a NAN return by `fromLonLat` , still thanks for replying!
