### ISSUE TITLE
Problems with WFS and projections

### ISSUE THREAD

**Issue by runette** [openlayers/openlayers#11038]
**Describe the bug**
This is two bugs (or possibly mistakes by me) that I believe have to be closely related but I cannot see how.

I have a working map with working WFS layers in EPSG:27700 crs. See https://swbayproject.com.

I wanted to add a layer in EPSG:4326 and then use WFS-T to add locations from the phone.

When I added a working WFS 1.1.0 layer in EPSG:4326 - it draws the points in the wrong place - i.e. it uses the coords as if they were supplied in 27700 and this puts the points close to the Scilly Isles. I have looked at the packets coming from the server (which is QGIS Server) and they are correct and use the correct SRS name.

When I create the WFS-T request using WFS.writeTransaction() with srsName= 'EPSG:4326' - the node provided has the coords in lon/lat order rather than lat/lon order which is confusing the server.

Fo both of them, I tried different versions of GML and setting the srsName in GML format but nothing seemed to work.

In the end - I just converted the server to EPSG:27700 and converted the data points in script. But this should not be the way that it works.

**To Reproduce**
You cannot directly reproduce since I had to changed the crs ofthe backend layer

**Expected behavior**
That Ol should convert correctly between the projections.

**Comment by mike-000** [comment]
ol/format/WFS doesn't automatically transform features into view projection, you need to do it in the loader.  Here's some example code from a StackExchange question (it won't run in codesandbox as the source isn't https)

```
import 'ol/ol.css';
import Map from 'ol/Map';
import View from 'ol/View';
import WFS from 'ol/format/WFS';
import {Tile as TileLayer, Vector as VectorLayer} from 'ol/layer';
import {bbox as bboxStrategy} from 'ol/loadingstrategy';
import OSM from 'ol/source/OSM';
import VectorSource from 'ol/source/Vector';
import {Stroke, Style} from 'ol/style';
import {fromLonLat, transformExtent} from 'ol/proj'

var vectorSource = new VectorSource({
  loader: function(extent, resolution, projection) {
      var extent4326 = transformExtent(extent, projection, 'EPSG:4326');
      var extent4326yx = [extent4326[1], extent4326[0], extent4326[3], extent4326[2]];
      fetch('http://wms.pcn.minambiente.it/ogc?map=/ms_ogc/wfs/Bacini_idrografici.map' +
          '&service=WFS' +
          '&version=1.1.0' +
          '&request=GetFeature' +
          '&typename=ID.ACQUEFISICHE.BACINIIDROGRAFICI.PRINCIPALI' +
          '&srsname=' + 'EPSG:4326' +
          '&bbox=' + extent4326yx.join(',') + ',EPSG:4326'
      ).then(function(response) { return response.text(); }
      ).then(loadFeatures);
      function loadFeatures(response) {
          var formatWFS = new WFS();
          vectorSource.addFeatures(formatWFS.readFeatures(response, {
              dataProjection: 'EPSG:4326',
              featureProjection: projection
          }));
      }
  },
  strategy: bboxStrategy
});

var vector = new VectorLayer({
  source: vectorSource,
  style: new Style({
    stroke: new Stroke({
      color: 'rgba(0, 0, 255, 1.0)',
      width: 2
    })
  })
});

var raster = new TileLayer({
  source: new OSM()
});

var map = new Map({
  layers: [raster, vector],
  target: document.getElementById('map'),
  view: new View({
    center: fromLonLat([15, 41]),
    maxZoom: 19,
    zoom: 8
  })
});

```

**Comment by runette** [comment]
Thank you for the prompt, detailed and disappointing answer. I find it very strange that this is not part of the core functionality.

I have to say that the documentation could be much clearer about this. I also have to say that there are a number of community answers in e.g. StackOverflow that explicitly state that it does. So there is considerable confusion here.
