### ISSUE TITLE
Add waze map in openlayer

### ISSUE THREAD

**Issue by romik280** [openlayers/openlayers#11039]
Hello all!

I want to add waze maps in openlayers. Can anyone suggest me how it do?
https://www.waze.com/ru/livemap

**Comment by MtnBiker** [comment]
I don't that much about this. But usually you're adding a layer and you'd need an API from Waze. In a 15-sec. look at their website I saw free transport route planning or similar; maybe that can be adapted. Stackoverflow otherwise.
