### ISSUE TITLE
Is it a bug for getFeaturesAtPixel(pixel, opt_options)?

### ISSUE THREAD

**Issue by ChocLiu** [openlayers/openlayers#11055]
**Describe the bug**
Sometimes this function cannot get features where the features' style is at that pixel.

When I used this function to get features, I found that: If the 'Style' (like image and text) of a 'Feature' is within 100 pixels of the feature's coordinate, I can get the feature by using the pixels within the 'Style'; But If the 'Style' is too far (more than 100 pixels), I cannot get the 'Feature' by using the pixels of the 'Style'.

**To Reproduce**
1. let p = new Feature(new Point())
2. p.setStyle(new Style({text: new Text( { offsetX: 200 } )}))
3. then, if the point is at pixel-coordinate [0,0], using getFeaturesAtPixel( [200, 0] ) can get nothing.

**Expected behavior**
It should be able to get the features by clicking the features' style.

**Comment by ahocevar** [comment]
By default, OpenLayers only considers an area of 100 pixels around a feature for hit detection. When you use an offset of 200 pixels. you are outside of that region. To fix it, configure your layer with a `renderBuffer` with an appropriate size. In your case maybe `renderBuffer: 250`.

**Comment by ChocLiu** [comment]
> By default, OpenLayers only considers an area of 100 pixels around a feature for hit detection. When you use an offset of 200 pixels. you are outside of that region. To fix it, configure your layer with a `renderBuffer` with an appropriate size. In your case maybe `renderBuffer: 250`.

God, I didn't find it. My bad. Thanks so much!
