### ISSUE TITLE
The defaultInteractions does not work

### ISSUE THREAD

**Issue by xqshen** [openlayers/openlayers#11056]
**Describe the bug**
The default interations such as DragRotate,DoubleClickZoom,DragPand does not work, but DragRotate.values_.active is true.

I use     "ol": "^6.3.1","vue": "^2.6.11"

**Comment by ahocevar** [comment]
Are you including `ol/ol.css` in your build? See #10932. A quick fix is to `npm install ol@dev`, where this issue is fixed already.

**Comment by xqshen** [comment]
Thank you very much, the problem is solved
