### ISSUE TITLE
Providing the getGeometriesArray() and setGeometriesArray() methods in the public API

### ISSUE THREAD

**Issue by michalzielanski** [openlayers/openlayers#11073]
On the `ol/geom/GeometryCollection` class instance,  it is possible to call the `getGeometriesArray()` and `setGeometriesArray()` methods but there is no word about them in the [documentation](https://openlayers.org/en/v6.3.1/apidoc/module-ol_geom_GeometryCollection-GeometryCollection.html). Please add them to the public API and documentation.

Without the `getGeometriesArray()` method, it is impossible to get the original geometry passed to the constructor and requires keeping references to them in the properties (`set()` / `setProperties()`) because `getGeometries()` returns clones and not originals.

**Comment by michalzielanski** [comment]
Can I make a pull request?

**Comment by ahocevar** [comment]
I think it would make sense to revisit why we return clones in `getGeometries()`. If there is no reason for that, I'd be in favor of returning the original geometries, also because of the convenience that they could be modified independently.

**Comment by ahocevar** [comment]
That said, if you want to create a pull request, make sure you add test cases that cover modifying the geometries and making sure the GeometryCollection gets notified of the changes in its geometries.
