### ISSUE TITLE
Cloned geometry loses additional properties.

### ISSUE THREAD

**Issue by michalzielanski** [openlayers/openlayers#11071]
When we clone a geometry that has additional attributes, the clone does not contain these attributes.

```js
var geom = new ol.geom.Point([0, 0]);
geom.setProperties({foo: 'bar'});

console.log(geom.getProperties()); // {foo: 'bar'}
console.log(geom.clone().getProperties()); // return: {}, expected: {foo: 'bar'}
```

**Comment by michalzielanski** [comment]
Can I make a pull request?

**Comment by ahocevar** [comment]
@michalzielanski It would make sense to implement a `clone()` method in the `ol/Object` base class, and modify all implemented `clone()` methods to use that for cloning object properties. Feel free to submit a pull request with such a change.

**Comment by eacaps** [comment]
Just noticed this issue when attempting to use `ol/format/KML.writeFeatures` with a projection transformation. The transformation logic clones the geometry and loses any properties on the geometry (in this case the `tessellate` property which allows the geometry to display correctly in Google Earth).

<img width="680" alt="Screen Shot 2020-08-24 at 4 07 29 PM" src="https://user-images.githubusercontent.com/8252280/91091085-13958a80-e624-11ea-9031-cf9062664539.png">

**Comment by ahocevar** [comment]
@michalzielanski wanted to create a pull request, which would be much appreciated.
