### ISSUE TITLE
try to setStyle, but not work.

### ISSUE THREAD

**Issue by mikemikemikemikemmmm** [openlayers/openlayers#11070]
I try to feature.setStyle(new Style({....})) in a SourceVectorTile with React, but the setStyle doesn't execute.
I already use " format: new FormatMVT({ featureClass: Feature })" to make feature a feature, 
instead of renderFeature.

what i did wrong?
is it because i use SourceVectorTile, instead of SourceVector?
or i forget to add any variable in useEffect input dependency?

this is my stylefunction
```javascript
    const styleFunction_forHoverClicked = (feature: IFeature, resolution: number) => {
        const id = getUniqleIdByFeature(feature)
        const isHovered = hoveredFeatureId.current === id;
        const isClicked = (clickedFeatureId.current === id)
        const iconStyle = new Style({
            image: createCanvas(isHovered , isClicked, resolution),
        });
        return [iconStyle];
    };
```

and when change hoveredFeature, setStyle
```javascript
    useEffect(() => {
        if (props.hoveredFeature) {
            hoveredFeatureId.current = getUniqleIdByFeature(props.hoveredFeature)
            props.hoveredFeature.setStyle(styleFunction_forHoverClicked);
            previousHovered.current = props.hoveredFeature
        } else {
            hoveredFeatureId.current = null
        }
        if (previousHovered.current) {
            previousHovered.current.setStyle(styleFunction_forHoverClicked)
        }
    }, [props.hoveredFeature, styleFunction_forHoverClicked, createCanvas]);
```
thanks.

**Comment by ahocevar** [comment]
Other than with vector layers, vector tile layers do not listen for style changes on their features. So you have to call `layer.changed()` after altering styles.

In general, I would recommend working with layer style functions and avoid setting styles on features for vector tile layers.
