### ISSUE TITLE
OL + proj4js 2.6.1 and above issue

### ISSUE THREAD

**Issue by michalzielanski** [openlayers/openlayers#11076]
OpenLayers does not work properly with proj4js version 2.6.1 (description of this release proj4js: Fixed interpretation of axis order).

OL 6.3.2-dev.1589843798021 + proj4js 2.6.0 + View with Mercator projection - **works properly**
![01---ol-6 3 2-dev_proj4js-2 6 0_view-mercator](https://user-images.githubusercontent.com/5003/82498531-72f97100-9af0-11ea-9f99-63a2bf7bdfb1.png)

OL 6.3.2-dev.1589843798021 + proj4js 2.6.0 + View with WMTS layer projection (EPSG:2180) - **works properly**
![02---ol-6 3 2-dev_proj4js-2 6 0_view-EPSG-2180](https://user-images.githubusercontent.com/5003/82498670-af2cd180-9af0-11ea-921b-d470055006a9.png)

OL 6.3.2-dev.1589843798021 + proj4js **2.6.1** + View with Mercator projection - **works incorrectly** (the WMTS layer (EPSG:2180) is rotated)
![03---ol-6 3 2-dev_proj4js-2 6 1_view-mercator](https://user-images.githubusercontent.com/5003/82498815-e26f6080-9af0-11ea-96b0-ba5d1b29cac9.png)

OL 6.3.2-dev.1589843798021 + proj4js 2.6.1 + View with EPSG:2180 projection - **works incorrectly** (the OSM layer (Mercator) is rotated)
![04---ol-6 3 2-dev_proj4js-2 6 1_view-EPSG-2180](https://user-images.githubusercontent.com/5003/82498855-f024e600-9af0-11ea-9118-eb779f040f7e.png)

I used 6.3.2-dev.1589843798021 because versions from 6.2.2-dev.1585261480561 to 6.3.2-dev.1588437998514 contain another bug.

Source of the above examples: https://codesandbox.io/s/openlayers-ortofotomapa-myhp7

**Comment by mike-000** [comment]
proj4js 2.6.1 is swapping axes which OpenLayers isn't expecting it to do.  But OpenLayers needs to know about the axis orientation to align the tile grid correctly, and a change to that part of OpenLayers would tie specific version of OpenLayers to specific versions of proj4js.  However removing the `+axis` from the the proj4 definition and setting `axisOrientation` in the Openlayers projection definition instead seems to be compatible with both versions of proj4js https://codesandbox.io/s/openlayers-ortofotomapa-4b2vm

**Comment by ahocevar** [comment]
I think it makes sense to fix this in proj4. I'll keep the issue here updated as I make progress there.

**Comment by ahocevar** [comment]
After some investigation, I come to the conclusion that @mike-000's advice is correct. The projection definition of EPSG:2180 does not have `+axis=neu` in its definition. Now I need to investigate why setting the axisOrientation in the OpenLayers projection definition is required to make that WMTS work.

**Comment by mike-000** [comment]
Here's another example from StackOverflow.  The sources are clearly using NE notation (otherwise the TopLeftCorner of the TileMatrix would be below the LowerCorner of the BoundingBox) despite https://epsg.io defaulting the `+axis` setting and without adding it the output would be misplaced as well as rotated https://codesandbox.io/s/wmts-openlayers-bgld-bwyb3
However http://epsg-registry.org **does** define northing (x) easting (y) in its definitions of the projections used there and EPSG::2180
http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::31259
http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::2180

**Comment by ahocevar** [comment]
I created #11088 with a fix. That fix makes proj4 >= 2.6.1 work like previous versions by using a proj definition without axis, according to @mike-000's suggestion.

**Comment by ahocevar** [comment]
> However http://epsg-registry.org does define northing (x) easting (y) in its definitions of the projections used there and EPSG::2180

I saw that too, @mike-000. So when the WMTS is configured from the WKT of the official registry, it explains the behaviour described in this issue. I decided to go with the above solution, because it keeps axis order handling out out the OpenLayers core.

**Comment by michalzielanski** [comment]
@mike-000, @ahocevar thank you.
