### ISSUE TITLE
Reading/writing foreign members from/to GeoJSON

### ISSUE THREAD

**Issue by michalzielanski** [openlayers/openlayers#11072]
The GeoJSON format allows to store additional properties in objects ([RFC 7946, section 6.1](https://tools.ietf.org/html/rfc7946#section-6.1)), but OpenLayers does not read and write them.

Expected behavior:
```javascript
import GeoJSON from 'ol/format/GeoJSON';

const parser = new GeoJSON();

const geometry = parser.readGeometry({
  type: 'Point',
  coordinates: [0, 0],
  kind: 'bakery'
});

console.log(geometry.getProperties()); // currently: {}, expected: {kind: 'bakery'}
console.log(geometry.getKeys()); // currently: [], expected: ['kind']
```

**Comment by tonio** [comment]
From the link you provide: 

>  Note that support for foreign members
   can vary across implementations, and no normative processing model
   for foreign members is defined.  Accordingly, implementations that
   rely too heavily on the use of foreign members might experience
   reduced interoperability with other implementations.

I would advise you to rely on standard `properties`.

**Comment by michalzielanski** [comment]
> I would advise you to rely on standard `properties`.

The `properties` attribute is only available for `Feature` object, not for `Geometry` and collections.

**Comment by icholy** [comment]
@michalzielanski if you want properties, you need to wrap your geometry in a feature.

**Comment by michalzielanski** [comment]
@icholy this is not a good solution for me. I prefer to create geometries manually (without using `ol/format/GeoJSON`) rather than using `FeatureCollection` (to use the `properties` attribute of the `Feature`) instead of the `GeometryCollection` which I use now.

**Comment by icholy** [comment]
Your preferred way of doing it is incorrect.

**Comment by michalzielanski** [comment]
@icholy, I currently have this structure:
```json
{
    "type": "GeometryCollection",
    "geometries": [
        {
            "type": "Point",
            "coordinates": [0, 0],
            "kind": "a"
        },
        {
            "type": "Point",
            "coordinates": [1, 1],
            "kind": "b"
        },
        {
            "type": "Point",
            "coordinates": [2, 2],
            "kind": "a"
        }
    ]
}
```
with your approach I would have to have:
```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [0, 0]
            },
            "properties": {
                "kind": "a"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [1, 1]
            },
            "properties": {
                "kind": "b"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [2, 2]
            },
            "properties": {
                "kind": "a"
            }
        }
    ]
}
```
in my opinion this is not a good solution. _All three geometries are logically related to one feature in my system._

In my opinion, to the constructor of the `ol/format/GeoJSON~GeoJSON` class could be added a `readForeignMembers` parameter of `boolean` or `array` type that would decide whether foreign attributes can be read from GeoJSON objects. If the value of the attribute were an `array`, it would be a list of attribute names to be read.
