### ISSUE TITLE
KML cannot be loaded when the url is a network address, xmlns:gx doesn't work

### ISSUE THREAD

**Issue by rq0323** [openlayers/openlayers#11077]
let kmlUrl = 'https://'+this.fileServerUrl + 'lineKml/' + this.sampleData.kmlName
let kmlSource = new VectorSource({
 url: kmlUrl,
   format: new KML()
})
this.kmlLayerVector.setSource(kmlSource)

**Comment by rq0323** [comment]
Non-xmlns:gx format can be normal

**Comment by rq0323** [comment]
It is KML that can be opened with Google earth, and some cannot be loaded with OL

**Comment by psilvao** [comment]
Hi, interesting issue, because i found the same case, please see my post with a simple code https://stackoverflow.com/questions/61934070/i-cant-display-the-kml?noredirect=1#comment109547920_61934070 , regards, Pablo

**Comment by rq0323** [comment]
> 嗨，有趣的问题，因为我发现了同样的情况，请通过简单代码https://stackoverflow.com/questions/61934070/i-cant-display-the-kml?noredirect=1#comment109547920_61934070查看我的帖子，巴勃罗

Thank you very much for your reply, but I tested that this problem is not a problem of network KML, but more like a problem of supported KML version. The file openlayers of XMLNS: gx, Google, cannot be parsed?Because the other KML is normal

**Comment by psilvao** [comment]
It is strange what happens with KML and openlayers, I promise I did a series of tests with a code in the cloud, please, try the kml urls that are declared in my post, I will copy them again to follow the thread of the conversation


test code: `https://jsfiddle.net/geocodezip/yvekp0ud/1/`

KMl urls to test (just replace) and see what happens:


```
https://openlayers.org/en/latest/examples/data/kml/2012-02-10.kml

http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/kml/lines.kml

https://geo.anantara.cl/maps/kml/doc.kml

https://www.sedgeochem.uni-bremen.de/kml/borabora.kml

http://wp-osm-plugin.hanblog.net/wp-content/uploads/osm_map/OSM_02.kml
```
Regards,
Pablo

**Comment by psilvao** [comment]
Solved!

     The problem was the apache configuration, more information in [https://stackoverflow.com/questions/61934070/i-cant-display-the-kml/62097286#62097286](url)
