### ISSUE TITLE
Allow different base rotation for ol/control/Rotate

### ISSUE THREAD

**Issue by EvertEt** [openlayers/openlayers#11080]
**Is your feature request related to a problem? Please describe.**
We display images but rotate them according to the exif. Using `resetNorth` to change back to the exif angle, in v4 this behaviour looked good. In v6 we noticed the control arrow indicator also rotates now.
**Describe the solution you'd like**
Could a way to turn this off or change the default base rotation so the arrow is pointing up for an angle not equal to 0?

**Comment by EvertEt** [comment]
Would a PR be accepted?

**Comment by ahocevar** [comment]
@EvertEt Can you outline in a bit more detail what you have in mind?

**Comment by EvertEt** [comment]
So as we're currently setting the `resetNorth` to fake the north being different (as we rotate an image to really face north and not using the top of the image as north). 
It would be nice if we could also change this in the rotation of the arrow in the control (described above) or if we could provide an override so that it would not be needed for us to set `resetNorth`. Perhaps a `northAngle` or something like this. 

I agree this is a very specific use-case so I find it hard to see if it would fit well into  the code and if so, where. 

Thank you
