### ISSUE TITLE
Need ol/interaction/DragAndDrop projection change property.

### ISSUE THREAD

**Issue by bayramucuncu** [openlayers/openlayers#11086]
DragAndDrop interaction needs projection propert. If it does not set, it gets the projection of map.view and this does not change after constructed.

I want to drag and drop a file on map, and show a popup to select projection of data. But the features are already created before my popup. 

If you create an event named something like "beforeFeatureCreate", or "dragEnd" the problem will be solved. Users can sets or change the projection of interaction before features created.. Drag and drop interaction will be more useful.

**Comment by mike-000** [comment]
If you set up the DragAndDrop with a dummy projection which doesn't have any transforms defined the features will not be transformed to view projection.  You can then ask the user which projection to use before transforming them and adding them to the source https://codesandbox.io/s/drag-and-drop-drez2

**Comment by bayramucuncu** [comment]
@mike-000 , I have tried this solution before. But I may have 8 or 10 different projections. When darag and drop a file on map, handling "addfeatures" event is not solwing problem. Because the features are already created by EPSG:3857. But if I have a geojson data EPSG:5254 or EPSG:2154 or EPSG:27200, .... , what will happen. I should select conver projection before.

**Comment by mike-000** [comment]
If you specify a dummy projection the features will stay in their original data projection until you convert them yourself.   I've update my example with the projections you listed..

**Comment by bayramucuncu** [comment]
Thanks @mike-000,  I did not know that dummy projection solution. Because [original api document](https://openlayers.org/en/latest/apidoc/module-ol_interaction_DragAndDrop-DragAndDrop.html) says `Target projection. By default, the map's view's projection is used`.  I also thought that the first projection was mandatory.
I am using this in my angular based openlayers project ([b3-map](https://github.com/bayramucuncu/b3-ol-map)) which will be completed soon.
