### ISSUE TITLE
Warning when trying to create a CustomLayer with webgl PointsLayer

### ISSUE THREAD

**Issue by FractalWire** [openlayers/openlayers#11083]
I'm currently following the workshop but I'm now stuck on the WebGL rendering part.

The following code should be similar to what the [workshop](https://openlayers.org/workshop/en/webgl/points.html) propose to render meteorites:

```javascript
import 'ol/ol.css';
import {Map, View, Feature} from 'ol';

import TileLayer from 'ol/layer/Tile';
import VectorLayer from 'ol/layer/Vector';

import VectorSource from 'ol/source/Vector';
import XYZSource from 'ol/source/XYZ';

import Point from 'ol/geom/Point';

import {fromLonLat} from 'ol/proj';

import Renderer from 'ol/renderer/webgl/PointsLayer';
import {clamp} from 'ol/math';

const stamenLayer = new TileLayer({
    source: new XYZSource({
        url: 'http://tile.stamen.com/terrain/{z}/{x}/{y}.jpg'
    })
});

const meteoriteSource = new VectorSource();
const client = new XMLHttpRequest();
client.open('GET', 'data/meteorites.csv');
client.onload = function() {
    const csv = client.responseText;
    const features = [];

    let prevIndex = csv.indexOf('\n')+1;
    let curIndex;
    while ((curIndex = csv.indexOf('\n', prevIndex)) != -1) {
        const line = csv.substr(prevIndex, curIndex - prevIndex).split(',');
        prevIndex = curIndex +1;

        const coords = fromLonLat([parseFloat(line[4]), parseFloat(line[3])]);
        if (isNaN(coords[0]) || isNaN(coords[1])) {
            continue;
        }

        features.push(new Feature({
            mass: parseFloat(line[1]) || 0,
            year: parseInt(line[2]) || 0,
            geometry: new Point(coords)
        }));
    }
    meteoriteSource.addFeatures(features);
}
client.send();

const color = [1, 0, 0, 0.5];

class CustomLayer extends VectorLayer {
    createRenderer() {
        return new Renderer(this, {
            colorCallback: function(feature, vertex, component) {
                return color[component];
            },
            sizeCallback: function(feature) {
                return 18 * clamp(feature.get('mass') / 200000, 0, 1) + 8;
            }
        });
    }
}
const webglLayer = new CustomLayer({
    source: meteoriteSource,
});

const map = new Map({
    target: 'map-container',
    layers: [
        stamenLayer,
        webglLayer,
        // dynamicLayer,
        // aisLayer,
    ],
    view: new View({
        center: fromLonLat([0, 0]),
        zoom: 2
    })
});
```

Unfortunately, at this point, nothing happens and I am having a series of warning:

```
33 WebGL: INVALID_OPERATION: useProgram: program not valid
6 WebGL: INVALID_OPERATION: getUniformLocation: program not linked
2 Helper.js:642 WebGL: INVALID_OPERATION: getAttribLocation: program not linked
./node_modules/ol/webgl/Helper.js.WebGLHelper.getAttributeLocation @ Helper.js:642
./node_modules/ol/webgl/Helper.js.WebGLHelper.enableAttributeArray_ @ Helper.js:692
./node_modules/ol/webgl/Helper.js.WebGLHelper.enableAttributes @ Helper.js:712
./node_modules/ol/renderer/webgl/PointsLayer.js.WebGLPointsLayerRenderer.prepareFrame @ PointsLayer.js:374
./node_modules/ol/layer/Layer.js.Layer.render @ Layer.js:209
./node_modules/ol/renderer/Composite.js.CompositeMapRenderer.renderFrame @ Composite.js:111
./node_modules/ol/PluggableMap.js.PluggableMap.renderFrame_ @ PluggableMap.js:1120
(anonymous) @ PluggableMap.js:175
requestAnimationFrame (async)
./node_modules/ol/PluggableMap.js.PluggableMap.render @ PluggableMap.js:1042
./node_modules/ol/PluggableMap.js.PluggableMap.handleSizeChanged_ @ PluggableMap.js:901
./node_modules/ol/events/Target.js.Target.dispatchEvent @ Target.js:115
./node_modules/ol/Object.js.BaseObject.notify @ Object.js:154
./node_modules/ol/Object.js.BaseObject.set @ Object.js:173
./node_modules/ol/PluggableMap.js.PluggableMap.setSize @ PluggableMap.js:1163
./node_modules/ol/PluggableMap.js.PluggableMap.updateSize @ PluggableMap.js:1196
./node_modules/ol/PluggableMap.js.PluggableMap.handleTargetChanged_ @ PluggableMap.js:954
./node_modules/ol/events/Target.js.Target.dispatchEvent @ Target.js:115
./node_modules/ol/Object.js.BaseObject.notify @ Object.js:154
./node_modules/ol/Object.js.BaseObject.set @ Object.js:173
./node_modules/ol/Object.js.BaseObject.setProperties @ Object.js:186
PluggableMap @ PluggableMap.js:319
Map @ Map.js:83
./main.js @ main.js:69
__webpack_require__ @ bootstrap:19
0 @ log.js:47
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
Helper.js:450 WebGL: INVALID_OPERATION: drawElements: no valid shader program in use
./node_modules/ol/webgl/Helper.js.WebGLHelper.drawElements @ Helper.js:450
./node_modules/ol/renderer/webgl/PointsLayer.js.WebGLPointsLayerRenderer.renderFrame @ PointsLayer.js:330
./node_modules/ol/layer/Layer.js.Layer.render @ Layer.js:210
./node_modules/ol/renderer/Composite.js.CompositeMapRenderer.renderFrame @ Composite.js:111
./node_modules/ol/PluggableMap.js.PluggableMap.renderFrame_ @ PluggableMap.js:1120
(anonymous) @ PluggableMap.js:175
requestAnimationFrame (async)
./node_modules/ol/PluggableMap.js.PluggableMap.render @ PluggableMap.js:1042
./node_modules/ol/PluggableMap.js.PluggableMap.handleSizeChanged_ @ PluggableMap.js:901
./node_modules/ol/events/Target.js.Target.dispatchEvent @ Target.js:115
./node_modules/ol/Object.js.BaseObject.notify @ Object.js:154
./node_modules/ol/Object.js.BaseObject.set @ Object.js:173
./node_modules/ol/PluggableMap.js.PluggableMap.setSize @ PluggableMap.js:1163
./node_modules/ol/PluggableMap.js.PluggableMap.updateSize @ PluggableMap.js:1196
./node_modules/ol/PluggableMap.js.PluggableMap.handleTargetChanged_ @ PluggableMap.js:954
./node_modules/ol/events/Target.js.Target.dispatchEvent @ Target.js:115
./node_modules/ol/Object.js.BaseObject.notify @ Object.js:154
./node_modules/ol/Object.js.BaseObject.set @ Object.js:173
./node_modules/ol/Object.js.BaseObject.setProperties @ Object.js:186
PluggableMap @ PluggableMap.js:319
Map @ Map.js:83
./main.js @ main.js:69
__webpack_require__ @ bootstrap:19
0 @ log.js:47
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
12 [.WebGL-0x5628f92342e0]RENDER WARNING: there is no texture bound to the unit 0
```

Is there something missing in the workshop or is this a bug ?

**Comment by jahow** [comment]
Hi, thanks for the bug report. It looks like the code in the workshop is not working any more... I'll look into it.

**Comment by jahow** [comment]
Ok so the hosted workshop is not up to date, which is why you get these errors. You can take a look at the source of the workshop which contains working code (albeit not in a very readable way): https://github.com/openlayers/workshop/blob/master/src/en/examples/webgl/animated.js

**Comment by flors** [comment]
hi! 
Found the same errors following the same Workshop tutorial [https://openlayers.org/workshop/en/webgl/points.html](url)

With the new github solution errors dissapeared but I don't want animated points. Using only this fragment shader should work? Or I also need a simplified vertexShader?  Thank you! 


fragmentShader: `
  precision mediump float;

  varying vec2 v_texCoord;
  varying vec4 v_color;

  void main(void) {
    vec2 texCoord = v_texCoord * 2.0 - vec2(1.0, 1.0);
    float sqRadius = texCoord.x * texCoord.x + texCoord.y * texCoord.y;
    float value = 2.0 * (1.0 - sqRadius);
    float alpha = smoothstep(0.0, 1.0, value);

    gl_FragColor = v_color;
    gl_FragColor.a *= alpha;
  }`

**Comment by jahow** [comment]
For a simple use case you're better off using the WebGL Points layer class which adds some abstraction over the shader complexity, see example:
https://openlayers.org/en/master/examples/webgl-points-layer.html?q=webgl

**Comment by flors** [comment]
@jahow thank you! I was checking it... the thing is I'm using it with ElectronJS and for some reason "ol/layer/WebGLPoints" is not working. I'm loading OpenLayer using the `<script>` tag...

I also have doubts if using this WebGL Points layer I can add interaction using the `getFeaturesAtPixel() `function ?? The thing is we are loading a json data with almost 90000 points, they should be clickable... I'm looking for something that allow me load all this points and we can smoothly navigate and interact with the map....

**Comment by M393** [comment]
As @jahow mentioned [here](https://github.com/openlayers/openlayers/issues/11084#issuecomment-633425447), the WebGLPoints layer is currently only available if you use openlayers as a node module. The legacy ol.js does not include experimental classes.

Here is an example with interaction:
https://openlayers.org/en/latest/examples/icon-sprite-webgl.html?q=webgl

**Comment by FractalWire** [comment]
@flors I've got a similar use case.

For a working non-animated solution of the workshop example:

```javascript
class CustomLayer extends VectorLayer {
    createRenderer() {
        return new Renderer(this, {
            attributes: [{
                name: 'size',
                callback: function (feature) {
                    return 32 * clamp(feature.get('mass') / 200000, 0, 1) + 16;
                }
            },
                {
                    name: 'year',
                    callback: function (feature) {
                        return feature.get('year');
                    },
                }],
            uniforms: {
            },
            vertexShader: `
        precision mediump float;
        uniform mat4 u_projectionMatrix;
        uniform mat4 u_offsetScaleMatrix;
        uniform mat4 u_offsetRotateMatrix;
        attribute vec2 a_position;
        attribute float a_index;
        attribute float a_size;
        attribute float a_year;
        varying vec2 v_texCoord;
        void main(void) {
          mat4 offsetMatrix = u_offsetScaleMatrix;
          float offsetX = a_index == 0.0 || a_index == 3.0 ? -a_size / 2.0 : a_size / 2.0;
          float offsetY = a_index == 0.0 || a_index == 1.0 ? -a_size / 2.0 : a_size / 2.0;
          vec4 offsets = offsetMatrix * vec4(offsetX, offsetY, 0.0, 0.0);
          gl_Position = u_projectionMatrix * vec4(a_position, 0.0, 1.0) + offsets;
          float u = a_index == 0.0 || a_index == 3.0 ? 0.0 : 1.0;
          float v = a_index == 0.0 || a_index == 1.0 ? 0.0 : 1.0;
          v_texCoord = vec2(u, v);
        }`,
            fragmentShader: `
        precision mediump float;
        varying vec2 v_texCoord;
        void main(void) {
          vec2 texCoord = v_texCoord * 2.0 - vec2(1.0, 1.0);
          float sqRadius = texCoord.x * texCoord.x + texCoord.y * texCoord.y;
          float value = 2.0 * (1.0 - sqRadius);
          float alpha = smoothstep(0.0, 1.0, value);
          gl_FragColor = vec4(1.0, 0.0, 0.0, 0.3);
          gl_FragColor.a *= alpha;
          gl_FragColor.rgb *= gl_FragColor.a;
        }`
        });
    }
}
```

You need both `vertexShader` and `fragmentShader` for it to work, as mentionned [in the doc](https://openlayers.org/en/latest/apidoc/module-ol_renderer_webgl_PointsLayer-WebGLPointsLayerRenderer.html).
Also, note that `vertexShader` is setting the position with `gl_Position` while `fragmentShader` is setting color with `gl_FragColor`. So here, both are mandatory it seems.
Also, not sure to understand how the piping work behind the scene, but it seems like `vertexShader` is setting variable that `fragmentShader` will later use.

I'll be curious to have more clarifications or documentation link to understand a bit better how those two shaders work together and why you set the position and color in two distinct shaders instead of one.

If you want to understand a bit more how this is working, you should check out the link mentionned [in the workshop](https://thebookofshaders.com/). It looks like a pretty good introduction to shaders.


You can use `getFeaturesAtPixel()` with WebGLPointsLayer. I did that during my previous tests.

Also, as an alternative to WebGL, you might consider using [VectorImage](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorImage-VectorImageLayer.html) for fast rendering of vectors. Didn't tried that yet...

**Comment by jahow** [comment]
There are many articles about how shaders work in WebGL, you could for example start [here](https://webglfundamentals.org/webgl/lessons/webgl-shaders-and-glsl.html).

> I'll be curious to have more clarifications or documentation link to understand a bit better how those two shaders work together and why you set the position and color in two distinct shaders instead of one.

Geometries are first processed by the vertex shader (once for each vertex), and then the fragment shader will run for every pixel drawn on screen for this geometry. So yes, you need to pass vertex attributes such as color from the vertex shader to the fragment shader. `gl_Position` is the output of the vertex shader, and `gl_FragColor` the output of the fragment shader.

The webgl renderer in OpenLayers is pretty low level so it will essentially bind uniforms and attributes for you, and let you complete freedom over the vertex and fragment shaders.

**Comment by FractalWire** [comment]
@jahow Excellent link, thanks !
I start to understand a bit more what is happening in the `vertexShader`

So, if I'm not mistaken, those lines will allow to set the position of each vertices in the clip space of webgl (-1 to 1):

```
          mat4 offsetMatrix = u_offsetScaleMatrix;
          float offsetX = a_index == 0.0 || a_index == 3.0 ? -a_size / 2.0 : a_size / 2.0;
          float offsetY = a_index == 0.0 || a_index == 1.0 ? -a_size / 2.0 : a_size / 2.0;
          vec4 offsets = offsetMatrix * vec4(offsetX, offsetY, 0.0, 0.0);
          gl_Position = u_projectionMatrix * vec4(a_position, 0.0, 1.0) + offsets;
```
It seems to me that the various matrices are doing the heavy work here. It looks a bit magic to me but am I right to say those are [transformation matrix](https://en.wikipedia.org/wiki/Transformation_matrix#Rotation) ?
How could I use the last one, `uniform mat4 u_offsetRotateMatrix` ?

Also, I can't figure out in what use case the `vertexShader` would differ from what is provided in the earliest workshop example except if you want to do 3D rendering. Any example ?

**Comment by jahow** [comment]
They *are* transformation matrix, although not very complex since we're only working in 2 dimensions.

> Also, I can't figure out in what use case the vertexShader would differ from what is provided in the earliest workshop example except if you want to do 3D rendering. Any example ?

Well for one thing the vertex shader will become more complex if you want to rotate the symbols, for example. Besides, you always have to pass vertex attributes to the fragment shaders through them which means you can't just have one shader for all uses.

Other than that, there have been an attempt to actually render the features at different depth in order to do basic z-sorting with the GPU, which would probably add more complexity to the shader. That would be an awesome addition to the renderer IMO.

Working with shaders can be both exciting and very frustrating (especially when it comes to debugging), which is why the webgl layer class brings an abstraction layer over it and translates readable style objects into shaders automatically.

Note: if you enjoy shaders I encourage you to take a look at [the book of shaders](https://thebookofshaders.com/) which has some pretty awesome techniques, some of them used in OL ;)

**Comment by FractalWire** [comment]
> Other than that, there have been an attempt to actually render the features at different depth in order to do basic z-sorting with the GPU, which would probably add more complexity to the shader. 

Hum, I might still not fully understand how rendering in WebGL works. But here is how I guess the rendering is done:

```
For each feature in features: // CPU time
    render feature // GPU time: WebGL action
```

In that case, basic z-sorting could be as simple as that:

```
For each feature in (features ordered by z-index):
    render feature
```

But maybe I'm missing something here ?

> Working with shaders can be both exciting and very frustrating (especially when it comes to debugging)

To get back to something more related to the original issue. Any time my shader programs have syntax error, I get the warnings previously mentionned.
It seems that some debug informations provided by WebGL could be added whenever a shader failed to compile. [Here](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/linkProgram) for a simple example.

Something similar could be quite useful before the return statements of those lines : https://github.com/openlayers/openlayers/blob/3014b68254be3ac0c4cfce9af41d90e2aa321a1b/src/ol/webgl/Helper.js#L745-L749

**Comment by jahow** [comment]
> But maybe I'm missing something here ?

This solution will be very costly on the CPU (z-index might potentially change every frame).

> It seems that some debug informations provided by WebGL could be added whenever a shader failed to compile.

This was attempted but the problem is that sometimes some browser will output warnings even though the shaders are fine. If you're working on your own shaders you should use this:
https://github.com/openlayers/openlayers/blob/3014b68254be3ac0c4cfce9af41d90e2aa321a1b/src/ol/renderer/webgl/Layer.js#L76-L83

And print whatever is in there yourself.
