### ISSUE TITLE
Static images are clipped when cross 180 degrees meridian

### ISSUE THREAD

**Issue by mardrof** [openlayers/openlayers#11092]
**Describe the bug**
Actually putting image as ImageStatic to the map which exceeds -180/180 meridians makes that image is cut. It's very important for us to display whole image on duplicated parts of map.
It was reported in https://github.com/openlayers/openlayers/issues/7288 ticket. The idea was to implement wrapX

**Expected behavior**
Static images on map should be repeated when exceeds -180/180 meridians.

**Comment by mike-000** [comment]
I think images being clipped at the dateline and image layers not wrapping are different issues. A workaround for image layers (ImageWMS, etc. are also affected) currently not wrapping would be to set up your static image in a tile grid of one tile in a tile layer.  However even tile layers are constrained by the extent of the projection.  With a default projection if the image or tile grid crosses the dateline it exceeds the projection extent, and even if image layers did wrap you would probably need to use an appropriate projection for the layer (e.g. spherical mercator centered on the date line and wrapping at Greenwich) to avoid the image being cropped https://codesandbox.io/s/reprojection-image-dy4cn

**Comment by eric-g-97477** [comment]
I am hoping this issue can be reopened. Any chance someone can work on it?
