### ISSUE TITLE
Padding on fit function doesn't run

### ISSUE THREAD

**Issue by MaxDragonheart** [openlayers/openlayers#11090]
I'm trying to apply the padding on fit function but is seems that there aren't effect. This is my code:
```
var sourceGeoBlog = new ol.source.Vector({
  url: '{% url 'api_geopost' %}',
  format: new ol.format.GeoJSON(),
});

var geoBlog = new ol.layer.Vector({
  source: sourceGeoBlog,
  style: styleFunction,
});

sourceGeoBlog.once('change', function(evt){
  if (sourceGeoBlog.getState() === 'ready') {
    if (geoBlog.getSource().getFeatures().length > 0) {
      var padding = [500, 0, 500, 0]
      map.getView().fit(
        sourceGeoBlog.getExtent(),
        map.getSize(),
        {
          padding: padding,
        }
      );
    }
  }
});

var view = new ol.View({
  center: ol.proj.fromLonLat([4.0863647111, 48.6698370737]),
  zoom: 9,
  minZoom: 7.5,
});

var map = new ol.Map({
  controls: ol.control.defaults().extend([
    new ol.control.ScaleLine({className: 'ol-scale-line', target: document.getElementById('scale-line')}),
    new ol.control.LayerSwitcher({tipLabel: 'layer switcher'}),
  ]),
  target: 'map',
  layers: [
    basemapGroup,
    geoBlog,
  ],
  view: view,
  overlays: [overlay],
});
```

I can zoom on extents of geoBlog. What I'm doing wrong?

A user on [gis.stackexchange.com](https://gis.stackexchange.com/questions/362270/openlayers-6-add-padding-on-fit-function) told me this:

> Your map.getView().fit call does not get executed because sourceGeoBlog.once event processing function is defined after geoBlog vector layer is defined and loaded.
> 
> You should define function to be called after layer load before layer is actually defined/loaded:
> ```
> var sourceGeoBlog = new ol.source.Vector({
>   url: '{% url 'api_geopost' %}',
>   format: new ol.format.GeoJSON(),
> });
> 
> sourceGeoBlog.once('change', function(evt){
>   if (sourceGeoBlog.getState() === 'ready') {
>     if (geoBlog.getSource().getFeatures().length > 0) {
>       var padding = [500, 0, 500, 0]
>       map.getView().fit(
>         sourceGeoBlog.getExtent(),
>         map.getSize(),
>         {
>           padding: padding,
>         }
>       );
>     }
>   }
> });
> 
> var geoBlog = new ol.layer.Vector({
>   source: sourceGeoBlog,
>   style: styleFunction,
> });
> ```

His solution doesn't run for me. Maybe this is a bug?

**Comment by ahocevar** [comment]
You are calling `View#fit()` with 3 arguments, but it only takes 2. You have to change the arguments to
```js
      map.getView().fit(
        sourceGeoBlog.getExtent(),
        {
          size: map.getSize(),
          padding: padding,
        }
      );
```

See https://openlayers.org/en/v6.3.1/apidoc/module-ol_View-View.html#fit.

**Comment by MaxDragonheart** [comment]
Thank you! Now it runs! :)

**Comment by MaxDragonheart** [comment]
If you are on gis.stackexchange.com add an answer to my question. I can vote you
