### ISSUE TITLE
WebGL point does not stay visually selected when in 'Select' features array

### ISSUE THREAD

**Issue by edant92** [openlayers/openlayers#11108]
**Describe the bug**

When a feature is added to the `Select` features array (e.g. by `this.selectClick.getFeatures().push(feature);`, if using a normal canvas layer the feature is highlighted blue and stays this way until it is removed from the `Select` features array regardless of whether the mouse is over it or not.

When using WebGL, the feature only visually shows as selected when the mouse is over it.

![openlayers_feature_selected](https://user-images.githubusercontent.com/6187226/82932291-79706880-9f88-11ea-8a03-21dc8a39b828.jpg)

![openlayers_feature_unselected](https://user-images.githubusercontent.com/6187226/82932289-78d7d200-9f88-11ea-9fb0-f680110f5b93.jpg)

(the feature is still in the `Select` features array but is no longer visually selected)

**Expected behavior**

A feature added to the `Select` features array should stay visually selected when using WebGL.

**Comment by jahow** [comment]
Hi, could you please state which version of the library you are using, as well as a simple reproduction case using e.g. https://codesandbox.io to help identify the issue? thanks

**Comment by edant92** [comment]
Hi @jahow ! Sorry for taking so long to make examples.

I'm using v6.3.1 of OpenLayers.

I've created two minimal codesandboxes to demonstrate the issue.

#1: VectorLayer - The select feature works as expected 
(Click on a feature to select and it stays visibly selected until you click away)
https://codesandbox.io/s/select-features-vector-working-9ssif?file=/index.js

#2: WebGLPointsLayer - The select feature is broken
(Clicking on a feature 'selects' it, but this is not visibly shown.
https://codesandbox.io/s/select-features-web-gl-broken-spyuk?file=/index.js

Let me know if you need anything else :)

**Comment by jahow** [comment]
This is expected behaviour, although not correctly documented. The Select interaction does not maintain its own layer any more, and will attempt to switch the selected features style individually, which will have absolutely no effect in a webgl layer (where individual feature styling is not supported).

What you need to do in this situation is write a webgl style that handles this specifically, something like:
```js
const style = {
  variables: {
    selectedFeatureId: ''
  },
  symbol: {
    symbolType: 'circle',
    size: 10,
    color: ['case',
      ['==', ['get', 'featureId'], ['var', 'selectedFeatureId']], 'rgb(200, 200, 255)',
      'rgb(255, 0, 0)'
    ]
  }
};
```

Then use the events of the Select interaction to change the `seletedFeatureId` variable, something like:
```js
select.on('select', (evt) => {
  style.variables.selectedFeatureId =
    evt.selected.length ? evt.selected[0].get('featureid') : '';
});
```

**Comment by edant92** [comment]
@jahow Thank you! That's made it a lot clearer. I really appreciate the clarification.
