### ISSUE TITLE
Style zIndex not working

### ISSUE THREAD

**Issue by michalzielanski** [openlayers/openlayers#11101]
It looks like the zIndex style attribute doesn't work. The blue point and red text has zInex equal to 3, but is rendered below the black square which has zIndex equal to 2 (resulting from the layer).

Example: https://codesandbox.io/s/proud-fog-f88ru

**Comment by mike-000** [comment]
That is correct. Features are rendered by zIndex within their individual layer canvases then the canvases (including raster layers) are arranged by the layer zIndex (or layer order if zIndex is not specified). The exception is decluttered point features which are rendered to a single canvas above all other layers (add `declutter: true` to your layer1 to see that).

**Comment by michalzielanski** [comment]
OK, thanks for the explanation.
