### ISSUE TITLE
Duplicate labels (Text Style) on a Feature for VectorTiles

### ISSUE THREAD

**Issue by boeckMt** [openlayers/openlayers#11107]
**Describe the bug**
If Vector Tiles are styled with labels then there are duplicate labels due to tile boundaries.
How can this be resolved without rendering a separate point layer for the Features?

**To Reproduce**
https://codesandbox.io/s/vector-tile-selection-7mvtg?file=/index.js

**Expected behavior**
There should be the option to only use one label (Style) or multiple.

**Comment by mike-000** [comment]
It is rarely a problem as most vector tiles provide separate label points for polygons to avoid this issue, for example `country-names` are the label points for `country` polygons https://codesandbox.io/s/vector-tile-selection-4x5cy

**Comment by asdawn** [comment]
I met this problem too. One road has many labels, even I merged them in the original table and use a very large BUFFER while producing tiles using ogr2ogr.
Yes for polygons I can add a label point layer, but how can I process lines (for example a road)? If there is some way to bound the label point to a line, and let the text follow the line, that is good, but I did not find such API. And this also is important for label points of polygons, because sometimes we have to make sure the label will not exceed the boundary of the polygon.  
Besides, how to force the point labels display even they might overlap?  Sometimes the space is enough but only part of the labels will be shown. Thanks.

**Comment by boeckMt** [comment]
Thanks for the fast response @mike-000 
If that's the general way how to handle Polygon Labeling with Vector Tiles, then this Issue is more kind of a Feature request.

Would it be possible to set something like a group Index to a Feature which is splitted e.g. **part_1 ... part_n** so then the user could use one of the parts for styling or is this only possible on the creation of the tiles at the server? Maybe this would help @asdawn too.

**Comment by asdawn** [comment]
I just have some idea,  there are three ways:

1. Let the explorer maintain a set of unique names of a layer in current screen, and allows one (or N) to display.  Update the set when the content is changed. This is an on-the-fly method, and need javascript coding skills and should be familiar with the details of openlayers.

2. Delete duplicate names of tiles. It will cost a lot of time, maybe days or years, relies on the number of tiles, the efficiency of implementation and computing resource.

3. For lines, create a label point layers for each zoom level, make sure one object  have only one label. Or create a label polyline layer. Though it will be very boring, it is easy and fast using postgis.

4. @boeckMt  Maybe we should use utf-grid? It is some technique for labeling. The MVT specification mentioned it, but I do not know how to produce it now. 

Thanks @mike-000 for your advice,  modify the tiles might be the most practical way at this time.

**Comment by boeckMt** [comment]
Sorry for the late response!

@asdawn the [utf-grid technique from MVT](https://github.com/mapbox/utfgrid-spec/blob/master/1.3/utfgrid.md) sounds interesting but i think it is for something like interactions and tooltips, so i could not find out how to use it to label features from another layer. I checked out the [UTFGrid Demo](https://openlayers.org/en/latest/examples/utfgrid.html) as a starting point whith the [UTFGrid provided by OpenLayers](https://openlayers.org/en/latest/apidoc/module-ol_source_UTFGrid-UTFGrid.html) and we need some pixels from the layer where the data from the grid is placed, so it is basically like a second layer where to draw the labels, if I see it correctly.

**Comment by elhamAm** [comment]
I am also experiencing duplicate labels when I try to have a VectorTileLayer using a VectorTileSource that brings in labels for polygons. My placement for the style of text label is line. Please help fix this. These labels are repeated along the tile borders but it should not look at the tiles but rather the polygons right? I also tried using the declutter attribute that was recommended in another issue.
