### ISSUE TITLE
Mouse interactions with tabIndex set on map container do not work as expected

### ISSUE THREAD

**Issue by dellisd** [openlayers/openlayers#11102]
**Describe the bug**
Because of the change made in #10291, if a map's container element has a `tabIndex` attribute set the `DragPan` and `MouseWheelZoom` interactions no longer work until the container element has focus. While this fixes some behaviours for mobile/touch devices, the behaviour for mouse input seems (in my opinion) broken.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/accessible.html
2. Try to zoom by scrolling, or panning by dragging _without the map being focused_
3. Interactions do not occur

**Expected behavior**
Mouse input behaviour should behave as before where the map can be interacted with using the mouse without the map needing to first be focused when it has a `tabIndex` attribute set.

**Comment by ahocevar** [comment]
The behavior you are seeing is intentional. The reason is the followig: Consider a map on a scrollable page, e.g. in a blog post. You should always be able to scroll the page. Only after clicking on the map, you should be able to interact with the map.

I'd be curious to hear your use case, where the current behavior feels inappropriate.

**Comment by dellisd** [comment]
My use case is an application centered around a map with no scrolling involved. Given the way my application is laid out, there would never be an instance where a scroll or drag behaviour would interfere with what the user expected and so requiring the map to be clicked first isn't desirable. 

There are other things in the application such as text fields that could be selected by the user and cause the map to lose focus and require the map to be clicked again. Re-focusing the map any time an element is blurred might be a workaround, but it's not a great solution.

I understand the use case you described there and I think the current behaviour is useful, but I do think it should also be possible to disable it.

**Comment by ahocevar** [comment]
Good point. Since #10291, the `onFocusOnly` option of `ol/interaction#defaults` has no effect any more. #11135 restores that option, so you will be able to turn off the focus behavior again.
