### ISSUE TITLE
Dragging features not working with touch input

### ISSUE THREAD

**Issue by alasdair-macleod** [openlayers/openlayers#11111]
Hi

**Describe the bug**
The translate features example (https://openlayers.org/en/latest/examples/translate-features.html) does not work with touch input.
A user can correctly select/deselect a feature with a tap, but then attempts do move it do not work as expected.
Depending on which browser is being used, the 'grab' on the feature is lost after a small amount of movement.

Looking at this in dev tools;
within <div class="map" id="map"> , the <div class="ol-viewport"> correctly takes on class="ol-viewport ol-grabbing" with a touch and hold.
When the user drags the div reverts to class="ol-viewport"

The exact behaviour is slightly dependent.

In Chrome on winddows, Android and Ubuntu a short drag in any direction works briefly, then loses ol-grabbing and stops working.
In Firefox on windows and Ubuntu, horizontal dragging works as expected, but any vertical dragging causes the class to revert to ol-viewport, and thus functionality is lost.
Microsoft edge on windows acts in a similar manner to chrome, but loses ol-grabbing after a shorter drag.

**To Reproduce**
Go to the translate features example https://openlayers.org/en/latest/examples/translate-features.html 

select a feature using touch input (simulated touch input seems to show the same behaviour as real touch input)

attempt to move the feature.

**Expected behavior**
I would expect the feature to keep moving when you drag it until you lift your finger.

Thanks

**Comment by ahocevar** [comment]
This has been fixed already. See https://openlayers.org/en/master/examples/translate-features.html. You can `npm install ol@dev` to get a version with the fix.

**Comment by alasdair-macleod** [comment]
That's great, thanks.
