### ISSUE TITLE
Image Layer combine with Vector Layer

### ISSUE THREAD

**Issue by GeorgeCodeHub** [openlayers/openlayers#11110]
**Describe the bug**
I'm trying to have an image layer combined with a VectorLayer but when I add projection to view the vectors disappear. Am I doing something wrong?

**To Reproduce**
Here is an example:
https://stackblitz.com/edit/react-ol6

**Expected behavior**
What I expect is the combination of both layers in one view.

![image](https://user-images.githubusercontent.com/54906099/83022706-982c3900-a034-11ea-83ff-e7cebcf85f61.PNG)
+
![vectors](https://user-images.githubusercontent.com/54906099/83022709-99f5fc80-a034-11ea-889a-f90e3d374134.PNG)

**Comment by M393** [comment]
When I open the your link I see both, only the layers do not line up.
Change it to the following to align them:
```
var e = 1024;
var extent = [-e, -e, e, e];
```
