### ISSUE TITLE
Animations are stopped when window is resized

### ISSUE THREAD

**Issue by jalik** [openlayers/openlayers#11119]
**Describe the bug**
Here is the context, we have a map and a search bar.
On mobile devices, when the user focus the search input, a virtual keyboard pops up, then he enters its search and get results, when he clicks on a search result, the map is zooming to the feature, however the virtual keyboard is closing, thus triggering a resize event on the window, which causes the animation to stop. 

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/animation.html
2. Click on Take a tour
3. Resize window

**Expected behavior**
We should be able to disable animation cancel behavior on resize event.
Or if not possible, the previous state should be saved and restored after resize event, so the animation can continue where it stopped.

**Comment by jahow** [comment]
Hi! The issue is fixed on the master branch, see: https://openlayers.org/en/master/examples/animation.html

This fix will be part of the next release.

**Comment by jalik** [comment]
@jahow I cannot find the commit that fixes the issue, would you mind referencing it here ?
I try to understand how openlayers works with the goal to contribute one day. Thanks.

**Comment by jahow** [comment]
Sure! this is the PR fixing it: https://github.com/openlayers/openlayers/pull/10865

Glad you consider contributing, please don't hesitate to look for [issues tagged as PR accepted](https://github.com/openlayers/openlayers/issues?q=is%3Aopen+is%3Aissue+label%3A%22pull+request+accepted%22), and ask for directions!
