### ISSUE TITLE
visible width of the ScaleLine on the map depends on the flag 'bar' (true/false)

### ISSUE THREAD

**Issue by ThomasHalwax** [openlayers/openlayers#11118]
**Describe the bug**
When using the ScaleLine component we identified that the width on the Map varies depending whether the flag ```bar``` is set to ```true``` or ```false```.

**To Reproduce**
To reproduce the issue a map with a grid is helpful (i.e. SwissTopo http://wmts.geo.admin.ch/1.0.0/WMTSCapabilities.xml). We use Electron 8.2.0 (Chrome engine):

1) create a map with a ScaleLine and set the option ```bar``` to ```false```
2) align the ScaleLine to the grid and you can see that the 1km ScaleLine almost matches the grid
3) switch the option ```bar``` to ```true``` in order to render a ScaleBar instead of a ScaleLine
4) compare the width of the ScaleBar to the previous ScaleLine
5) seems like that the ScaleBar also fills the area left/right of the handles of the ScaleLine

I've attached images in order to visualize the issue:

ScaleLine:
![image](https://user-images.githubusercontent.com/38359572/83266119-b3c54a00-a1c2-11ea-9b8f-778dd6e50f0e.png)

ScaleBar:
<img width="956" alt="image" src="https://user-images.githubusercontent.com/38359572/83266213-d192af00-a1c2-11ea-96a0-904ea0be65d3.png">

It's worth noting that the div ```ol-scale-bar-inner``` does almost exactly match the grid:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/38359572/83269920-0e14d980-a1c8-11ea-8e8a-c185aea2b17d.png">

EDIT:
The CSS class ```.ol-scale-singlebar``` seems to apply a border of ```1px solid black``` which IMO causes the issue. By using the Chrome DevTools I can disable the style and the ScaleBar gets rendered correctly:
<img width="817" alt="image" src="https://user-images.githubusercontent.com/38359572/83272333-4ec22200-a1cb-11ea-9a7b-68da2a53f96a.png">

**Expected behavior**
Switching to a ScaleBar should not create a visual extension of the width in comparison to the ScaleLine.

**Comment by ThomasHalwax** [comment]
We are using v6.3.1. After upgrading to v6.3.2-dev.1590745992030 the issue is still present. 

Using Chrome 83.0.4103.61 on OS X I can confirm that your example works correctly. Our app uses Electron 8.20 which uses Chromium 80.0.3987.158. I'll do more research ...

**Comment by ThomasHalwax** [comment]
@mike-000 What makes the example work is ```box-sizing: border-box``` added to the ```ol-scale-singlebar``` class. Chrome tells me that this property is added by the bootstrap CSS:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/38359572/83324043-b5464f00-a262-11ea-9f48-16aea9fef488.png">

This property is not part of the OL CSS:
```css
.ol-scale-singlebar {
  position: relative;
  height: 10px;
  z-Index: 9;
  border: 1px solid black;
}
```

By adding this property I was able to make the ScaleBar work correctly.

**Comment by mike-000** [comment]
Yes, I can reproduce the problem when opening the example in codesandbox via the "edit" link  It shouldn't be relying on the examples template to display correctly.
