### ISSUE TITLE
OpenLayers is appending canvas tags to the bottom of the page body on specific events

### ISSUE THREAD

**Issue by rgoss** [openlayers/openlayers#11128]
I've run into a situation with pointermove and click events where open layers adds canvas tags to the bottom of the html document and the tags have representations of the map with apparently random colors.  I can reproduce this issue on the Open Layers examples page for Vector Tile Selection.  Just load the page, click a feature, then scroll to the bottom.

https://openlayers.org/en/latest/examples/vector-tile-selection.html

**Comment by jahow** [comment]
This was fixed by https://github.com/openlayers/openlayers/pull/10879, which will be part of the next release.

**Comment by rgoss** [comment]
great.  thanks
