### ISSUE TITLE
Problems with elm-pep because of MPL-2 license

### ISSUE THREAD

**Issue by detky** [openlayers/openlayers#11138]
Hallo,

first than nothing, thanks for your work :)

I'm working in Germany, and since last year, companies here hast to be carefull (exhaustively) with the usage of open source software. The punishments and the possible concequences for companies are giant. 
We were using openlayers since a few years, but without making active development on our own code (we stay at openlayers v4). I wanted to update to version 6 some days ago, but our foss complience tool says that you started to use a library with an MPL-2 license (elm-pep), and that's not allowed for us in the company. Our foss compliance directives (and probably the most companies that are affected by the same controls we are...also soon or late everywhere in the EU), will have problems with software using this kind of libraries, because "it could be" problematic, the lawyers said. I know that there are workarounds that in several cases would help, but unfortunately not in ours :(
It's clear to me that this is not a problem of openlayers, but i would reconsider to use such licenses because they extremly complicate the evaluation that hast to be made to give companies the "security" they normally want's to have.

In other words, when deciding between ol and other map frameworks that don't use mpl-2 libraries, openlayers is now in disadvantage situation, because the foss problem-detection-systems are now alarming about openlayers because of the usage of  elm-pep as deep dependency. The explanations of the technicians do not always find ears in managers, who generally prefer 100% security over a security that depends on how the developers and technicians worked (if they generated a correct and compliant foss report or made available the sources from the mlp-2 library, etc.). 

I would really apreciate if someone knows a way to use openlayers without elm-pep, or if anyone knows if because of the usage of a deep-reference distributed under mpl-2 license, i have to publish the source code of it beside my commercial software, or any workaround or idea...it's frustrating to leave openlayers because of that.

Thanks in advance,
Det

**Comment by fredj** [comment]
Now that the PointerEvent API [is supported](https://caniuse.com/#feat=mdn-api_pointerevent) on every recent browsers, can we consider removing this polyfill?

**Comment by ahocevar** [comment]
Yes, I think it's time to remove the polyfill!

**Comment by ahocevar** [comment]
elm-pep dependency removed with #11173
