### ISSUE TITLE
Improve performance for vector tile rendering

### ISSUE THREAD

**Issue by exotfboy** [openlayers/openlayers#11130]
Openlayers Version: 6.3.1
ol-mapbox-style:6.1.1

Openlayer support mapbox vector tiles, and there are a lot of examples, however most of them use a simple map style which will make the operation acceptable.

Now when I try to use the `mapbox-streets-11` style, there is a big latency when drag the map especially in a big screen. [Live demo](https://kbxit.csb.app/). 
> Left: openlayers, Right: mapbox-gl-js

You will find that the mapbox-gl-js have a much more better performance.

And I have tried my own map style(much more complex than mapbox-streets-11, while mapbox-gl-js will render the map as usual, but openlayers can not.

**Comment by ahocevar** [comment]
Not very convenient yet, but #10828 shows a way to boost vector tiles performance in OpenLayers.

**Comment by exotfboy** [comment]
Seems like the best solution at the moment is native mapbox-gl-js itself, like this [exmaple](https://openlayers.org/en/latest/examples/mapbox-layer.html).

**Comment by donnyv** [comment]
So this gets closed because openlayers ignores it?

**Comment by ahocevar** [comment]
Duplicate of #7549
