### ISSUE TITLE
Allow vector tile to reuse higher level tile for lower level

### ISSUE THREAD

**Issue by tom62291** [openlayers/openlayers#11139]
Hi,

I am publish a vector tile service by ArcGIS server. ArcGIS server is only to able to serve out maximum level 15 pbf. Does openlayers vector tile layer have any setting to reuse level 15 pbf to rendering in lower level such as 16,17,18,19,20,..?

Please help.

**Comment by mike-000** [comment]
You should specify `maxZoom: 15` in the VectorTileSource options

**Comment by tom62291** [comment]
seems not work even i specify maxZoom : 15 in the VectorTileSource options, it will call L16, L17 ...pbf

**Comment by tom62291** [comment]
oh, ssems work, thank you
