### ISSUE TITLE
HeatmapLayer no longer wraps X

### ISSUE THREAD

**Issue by jgalrito** [openlayers/openlayers#11136]
HeatmapLayers used to wrap X at least until 5.3.0, now they don't.

https://openlayers.org/en/v5.3.0/examples/heatmap-earthquakes.html

Tested in 6.3.1

https://openlayers.org/en/v6.3.1/examples/heatmap-earthquakes.html

**Comment by mike-000** [comment]
In v6 it uses a WebGL renderer so a fix for #11131 should also fix HeatmapLayer
