### ISSUE TITLE
Total canvas memory use exceeds the maximum limit (224 MB) on ios

### ISSUE THREAD

**Issue by alyywehby** [openlayers/openlayers#11132]
Hello, we are building an ionic app to show layers on maps using openlayers. Everything is working well on android but on ios when we load the second project we will have the following warning.
warning: Total canvas memory use exceeds the maximum limit (224 MB)

I googled it, I think that the problem on ios is caching canvas of the map and when exceed the 224MB the app don’t crash but don’t show any layer on map and gives the above warning.

So is there any way to not cache canvas on ios?

I will appreciate your help.

thank you in advance.

**Comment by ahocevar** [comment]
Which version of OpenLayers are you using? We made several improvements for v6 to reduce the memory footprint. See e.g. #9133.

**Comment by alyywehby** [comment]
Thank you for your reply.
I am using v6.1.1

**Comment by ahocevar** [comment]
You can try to upgrade to the latest version (v6.3.1). If that does not help either, you need to optimize your map configuration. Like use less layers and avoid image render mode for vector layers.

**Comment by jeroenvheel** [comment]
What you also can try is setting the pixel ratio property on the Map to 1 in most iOS devices this is 2 by default.
When it’s 2 it will render a bigger canvas.
This solved our problem and we have a lot of layers and objects on the map.

**Comment by alyywehby** [comment]
Thanks @jeroenvheel !! I set the pixel ratio to 1.

`this.map = new Map({
pixelRatio: Math.min(window.devicePixelRatio, 1),
projection: this.mapProjection,
layers: [this.googleLayer]
});`

But now I'am facing the same issue!! Is there any work around to solve it?
