### ISSUE TITLE
WebGLPointsLayer: Change src with an operator

### ISSUE THREAD

**Issue by Charl20cas** [openlayers/openlayers#11133]
I can change the color of a feature with an operator like this:

`style: {
     symbol: {
        src: 'icon.png',
        symbolType: 'image',
        color = ['match',
                ['get', 'iconStatus'],
                'hover', 'red',
                'selected', 'aqua'
        ]
    }
}
`
Is there a way to change the src with an operator?
Something like this...

`style: {
    symbol: {
        src: ['match',
                ['get', 'iconStatus'],
                'normal', 'icon01.png',
                'hover', 'icon02.png',
                'selected', 'icon03.png'
        ],
        symbolType: 'image',
        color = ['match',
                ['get', 'iconStatus'],
                'hover', 'red',
                'selected', 'aqua'
        ]
    }
}`

or, is there any way to show more than 2000 features with independent images?

Thanks

**Comment by M393** [comment]
Not sure if this will solve your problem, but you can use a sprite image to have different icons:
https://openlayers.org/en/latest/examples/icon-sprite-webgl.html
https://openlayers.org/en/latest/examples/data/ufo_shapes.png

**Comment by Charl20cas** [comment]
I've already studied those options, but they don't cover my problem. I detail my real problem. 

In openlayer 5.3.3, I am using WebGLMap to paint over 2000 features for performance issues. Each feature has an style with an icon, the icon src is a svg. When hovering over the feature, I dynamically change the colors of the svg and overwrite the srv icon on the style of the feature.

When updating to version 6.3.1, WebGLMap no longer exists, so I need a way to render those 2000 features and have the image changed. I can't use the sprite solution because the colors with which I modify the svg are dynamic, so I can't have a static image.

**Comment by ahocevar** [comment]
2000 features is not much. Those should work fine with a standard Vector layer. Just make sure you optimize the style function, i.e. do not create a new instance of `ol/style/Icon` with every call.

**Comment by Charl20cas** [comment]
@ahocevar I have tried what you say. I have used VectorLayer. I have 27 different types of icons, I have created an array with the 27 icon definitions.

I have created a style for each feature (2600) by assigning its corresponding icon. When I have all the features visible on the screen, the map moves very slowly. It is clear that I am doing something wrong, since if I do not assign the styles to the features, the map with all the visible elements (without style) is displayed without any type of delay.

**Comment by M393** [comment]
Are the svg icons very detailed? If there are many points/filters/etc. it can get quite slow because the icons are drawn from their xml source each time.

**Comment by Charl20cas** [comment]
@M393 Yes, they are very detailed icons

**Comment by M393** [comment]
Rendering the icon to a canvas and using the canvas as the icon img could improve performance in this case.

**Comment by Charl20cas** [comment]
@M393  For the test, I have replaced the svg with a png ... and show all the features ... it doesn't give any problem. I'm going to try the solution of the canvas... Thank you!!!

**Comment by Charl20cas** [comment]
@M393 No ... not working well ... there is still a delay

**Comment by M393** [comment]
Can you share an minimal example in http://codesandbox.io/?
You can use any of the examples [here](https://openlayers.org/en/latest/examples/index.html) as a starting point by clicking on 'Edit' in the top right corner.

**Comment by Charl20cas** [comment]
For company confidentiality issues I can only share the following:
1. First step: i have a method that creates the 27 types of icons by code

```
createLayerStyles(type) {
    const icon = escape(type.svgItem); // i.e. <svg>Up to 4000 characters</svg> - This is the real problem
    this.iconStyles[type.code] = new Icon({
          opacity: 1,
          src: 'data:image/svg+xml,' + icon,
          imgSize: [type.width, type.height],
          anchor: [type.anchorX, type.anchorY],
    });
}
```

2. Second step: i have a method that recursively is called 2700 times

```
assignFeature(data){
    const iconFeature = new Feature({
        id: data.id,
        geometry: new Point(fromLonLat([data.Longitude, data.Latitude])),
        code: data.code,
        zIndex: data.index
    });
    const symbolStyle = new Style({
        image: this.iconStyles[data.code]
    });
    iconFeature.setStyle(symbolStyle);    

    this.addToType(iconFeature);
}
```
3. Third step: A method that receives the features and saves them in the corresponding list:
```
addToType(feature) {
    let createNew = true;
    if (this.arrayIcons && this.arrayIcons.length > 0) {
      this.arrayIcons.forEach(element => {
        if (element.type === feature.get('code')) {
          element.icons.push(feature);
          createNew = false;
        }
      });
    }
    if (createNew === true) {
      const objectByType = {
        type: feature.get('code'),
        icons: [feature]
      };
      this.arrayIcons.push(objectByType);
    }
}
```
4. Last step: a method that goes through the list of icon types and paints the VectorLayer on the map
```
renderLayers() {
    let layer;
    let layerSource;

    this.arrayIcons.forEach(element => {
        layer = new VectorLayer({});
        layerSource = new VectorSource({});
        
        layerSource.addFeatures(element.icons);
        layer.setSource(layerSource);
        map.addLayer(layer);
    });
}
```
I hope it helps, thanks

**Comment by M393** [comment]
https://codesandbox.io/s/icon-color-0wx45?file=/index.js
Setting the `color` option of the `Icon` to 'white' will render the icon to a canvas internally and not change the color. 

Remove the `color` config to compare.

**Comment by Charl20cas** [comment]
@M393 It works perfectly. The improvement in the memory consumption of the browser is very noticeable. Thanks so much for the help.

**Comment by Charl20cas** [comment]
The most important thing is that you have helped me understand that the real problem was not the painting of the 2700 elements, but the use of svgs in great detail when painting the icons. Thanks again

**Comment by nebsar** [comment]
@Charl20cas  I think you dış not use WebGLPointsLayer at the end, is it right?
