### ISSUE TITLE
optionsFromCapabilities from 'ol/source/WMTS' does not parse resolutions/scale denominators

### ISSUE THREAD

**Issue by geekdenz** [openlayers/openlayers#11134]
**Describe the bug**
When parsing a GetCapabilities XML document from a standard WMTS MapServer implementation, the resolutions do not get inferred. I have to manually provide several parameters to a WMTS source to get things working. Since WMTS is a standard, either MapServer is not following the standard correctly or OpenLayers does not parse the document correctly in every case.

```import {optionsFromCapabilities} from 'ol/source/WMTS'```

**To Reproduce**

Note that I cannot provide complete steps at the moment, but I do not want this to be forgotten. So, I am leaving this issue slightly incomplete. This issue tripped me up at least 3 times now, which is why I find it very important. I may be able to fix it myself, but the person who did the initial implementation will probably be faster to do so.

3. See error

**Expected behavior**
Any WMTS XML capabilities document can be parsed by OpenLayers and the layer used easily.

Please see https://gis.stackexchange.com/questions/29671/mathematics-behind-converting-scale-to-resolution to know how to convert the scale denominators to resolutions.

I was using the NZTM (EPSG:2193) projection. We always work around this issue thus far, but every time we need a New Zealand map of our own with WMTS, this trips us up.

Started something here:
https://codepen.io/geekdenz/pen/eYJYgQV

**Comment by mike-000** [comment]
In version 6.3.1 if you define and register EPSG:2193 these resolutions are used

`[8960, 4480, 2240, 1120, 560, 280, 140, 70, 28, 14, 7, 2.8, 1.4, 0.7, 0.28, 0.14, 0.07]`

8960 is calculated from the ScaleDenominator in the capabilities 32000000.00000000372529029846 * 0.00028

But the current dev version fails to get options from capabilities with error
 `Cannot read property 'ScaleDenominator' of undefined`

```
 const resolution =
    (matrix.ScaleDenominator * 0.00028) / projection.getMetersPerUnit();
```

which seems to be related to the code changed in #10981

**Comment by geekdenz** [comment]
Thanks for your quick response, @mike-000 .

If what you are saying is true, how come it doesn't work though? I'm using 6.3.1.

I registered EPSG:2193 with proj4 and the register function from ol.

**Comment by mike-000** [comment]
It does display but the output is misplaced and would be off the world beyond the south pole in a global projection.  The #10981 changes appear to be intended to fix that but have introduced a new problem by failing to find the correct matrix.

**Comment by ahocevar** [comment]
If anyone has a fix, please submit a pull request.

**Comment by geekdenz** [comment]
@ahocevar does this label mean "pull requests [will be] accepted"?

I will have a look into it given I have enough time and no one else can. I have a bit of time now.

**Comment by geekdenz** [comment]
OK. Checked out the latest code.
I tried running the tests with
```npm test```
both on master (1ef103ed6) and tag v6.3.1. However, on both the tests failed.

Is this a known issue or do I need to debug my environment, @ahocevar ?

**Comment by ahocevar** [comment]
@geekdenz yes, that label means a pull request is appreciated and will be accepted.

Regarding `npm test`: The rendering tests usually fail because of cross-platform rendering engine differences. However, the unit tests should pass: `npm run karma`.

**Comment by geekdenz** [comment]
Thanks for the quick answer, @ahocevar ! I'll make some time tomorrow to look into this.

**Comment by geekdenz** [comment]
This is caused by the coordinates being in the wrong order in the origin. NZTM uses neu.

This is already fixed in master:
https://github.com/openlayers/openlayers/blob/1ef103ed6/src/ol/source/WMTS.js#L475
https://github.com/openlayers/openlayers/blob/master/src/ol/source/WMTS.js#L476

The bug still exists in production here:
https://github.com/openlayers/openlayers/blob/v6.3.1/src/ol/source/WMTS.js#L383

A work-around that works is:

`let options = optionsFromCapabilities(capabilities, wmtsOptions);
options.tileGrid['extent_'] = [274000, 3087000, 3327000, 7173000];`

for the NZTM (EPSG:2193) projection in 6.3.1.
