### ISSUE TITLE
WebGL prepareframe optimization

### ISSUE THREAD

**Issue by FractalWire** [openlayers/openlayers#11149]
As mentionned in the source code, [rebuildBuffer_](https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/webgl/PointsLayer.js#L480) is a  costly operations.
From what I understand, its main purpose is to update the attributes of every features in the vector layer. And those only need their feature (in the callback) to be properly updated.
I don't really get why the framestate is useful here, given that the information related to it is passed to the shaders via uniforms. And those seems to be updated every time the map is rendered.

In that regard, when using WebGL with a big, unique vector source (geojson or a one-time call to a wms service), I noticed some reactivity drop every time the view stopped moving.
This is due to those lines that call internally `rebuildBuffers`:

https://github.com/openlayers/openlayers/blob/db08e0562f2b72e47b5240b7b811ba363964188c/src/ol/renderer/webgl/PointsLayer.js#L446-L457

In my opinion, for a vector source that does not update everytime the extent changes, it seems wasteful to rebuild the buffers everytime the extent changes. I checked that by modifying those lines like so:

```javascript
      this.previousExtent_ = frameState.extent.slice();
      if (sourceChanged){   
        this.rebuildBuffers_(frameState);    
      }  
```

With this change it is very smooth (no lag every time the extent changes) and does not seem to be an issue with something else at first glance.

But maybe there is something that I am missing here ?

**Comment by jahow** [comment]
This was actually introduced because there would be precision-related glitches if the buffers were not rebuilt regularly. Typically, around zoom level 12 and above, the drawn features would start jumping around.

The solution was to fill geometry buffers with *relative to eye* positions, but this has to be done periodically to avoid glitches.

This is indeed a serious bottleneck and I personally am not super satisfied with the current state, since if it weren't for this the renderer would perform very well with several hundred thousand points.

Knowing precisely when to rebuild the buffers is tricky, because the precision glitches will happen if the user zooms in or out too much or pans a long distance at a high zoom level.

Also your suggestion seems to drop the logic of reloading the source content after the view moved, which is required for sources with a bbox or tile loading strategy for example.

**Comment by FractalWire** [comment]
Hum. I wasn't able to reproduce this glitch with my little modification.
If there is an existing issue related to this, I'd be curious to dig a bit more.

> Also your suggestion seems to drop the logic of reloading the source content after the view moved, which is required for sources with a bbox or tile loading strategy for example.

Well, I'm not so sure about that.
This line 
https://github.com/openlayers/openlayers/blob/db08e0562f2b72e47b5240b7b811ba363964188c/src/ol/renderer/webgl/PointsLayer.js#L453

will further call these lines :
https://github.com/openlayers/openlayers/blob/db08e0562f2b72e47b5240b7b811ba363964188c/src/ol/source/Vector.js#L906-L907

Which should ultimately call these lines if and only if the extent (or part of it) is not already loaded (which should be the case for bbox or a tile strategy if I'm not wrong):
https://github.com/openlayers/openlayers/blob/db08e0562f2b72e47b5240b7b811ba363964188c/src/ol/source/Vector.js#L371-L374

And `this.changed()` should ultimately mean that `sourceChanged` resolve to `true`.
So, the attributes should be reloaded on the next call to `prepareFrame`.

I did not try this change with a bbox strategy though.

---

Even if I'm wrong here, I think this is a worthwhile optimization, at least for the single tile source.
So if we need more control over it, an alternative like that could be something to consider:

```javascript
      if (this.shouldRebuildBufferOnViewMoveEnd_){   
        this.rebuildBuffers_(frameState);    
      }  
```

**Comment by jahow** [comment]
> Hum. I wasn't able to reproduce this glitch with my little modification.
> If there is an existing issue related to this, I'd be curious to dig a bit more.

See https://github.com/openlayers/openlayers/issues/9479 and the associated fix. Looks like the zoom level where this issue appears is closer to 20.

**Comment by FractalWire** [comment]
Ah yes, I can see it at zoom 20.

From what I understand, it is pretty much a float precision issue.
Webgl fails to give enough precision for the position at a certain zoom level so there is rounding error, while javascript have double precision and is capable to deliver the position in the current view to Webgl with enough precision.
Correct ?

If that's what is happening, there might be a solution that does not involve rebuilding the buffer everytime: [emulating double precision in WebGL](https://prideout.net/emulating-double-precision)

In that situation, the hard work would be done by the shader at the cost of complexifying the vertex shader and adding a few attributes in the buffer.

**Comment by jahow** [comment]
Emulating double precision for floats in webgl will require sending another pair of x/y values in the attributes, right? This does not seem too complex although less attributes is always better. On the other hand, I have the impression that rebuilding buffers might be done much less frequently and still solve the precision issue, which would be the low hanging fruit here.

And then there's the question of updating only parts of the features in the source, which you mention [here](https://github.com/openlayers/openlayers/issues/11169) and is IMO a very interesting topic. Doing fractional updates would mean being able to rebuild the buffers without having one blocking frame as a result.

I'll try a quick implementation of the double-precision emulation you mentioned, see how hard that would be to implement.

**Comment by FractalWire** [comment]
> Emulating double precision for floats in webgl will require sending another pair of x/y values in the attributes, right?

It depends on how precise you want your position to be. You can remove the jittering effect simply by enhancing the precision of the center position view sent to the shader. That is done with uniform only, no extra attributes needed.

e.g:

```
real_x = 123.456789
real_xview = 654.321980

a_x = 123.456
u_xview_high = 654.321
u_xview_low = 0.980

out_position = a_x - u_xview_high // jittering simple float position
out_position -= u_xview_low // no jittering, smooth transition between view change
```

floats can give at most 7 digits of precision, this means around 10m errors in the worst case (not sure, need testing here).
If that's the kind of precision we should expect doubling coordinate attribute should be used instead.

You can use that as a quick way to split floats in high/low floats for your test : https://github.com/FractalWire/openlayers/blob/webgl-norebuild/examples/ais_norebuild.js#L50-L66
There is probably a better way to do that but it works fine for testing.
