### ISSUE TITLE
Need clarification on how hit detection worked with webgl

### ISSUE THREAD

**Issue by FractalWire** [openlayers/openlayers#11145]
I just implemented hit detection with the webgl layer I'm working with.
However it seems quite imprecise when multiple features are near each other and it is more visible in my case with non-circle symbols.

Let's see a demo:

![webgl-hit-2020-06-05-215642](https://user-images.githubusercontent.com/16882885/83917907-fb764380-a777-11ea-94d4-83486e8ed1aa.gif)

My fragment shader for the hit detection is pretty much a simplified version of the normal fragment shader except a tad larger because it does not smooth its border.
It works fine when features are isolated but as shown above it has difficulty to detect a hit otherwise.
Is this an expected behaviour or is there something to improve here ?

Let me know if you want to see some of my code.

**Comment by jahow** [comment]
Hi,

This is not expected: the hit detection shader should output basically the same shapes than the main one, but with a different color for each feature. Could you please copy the relevant parts of your code, or better yet set up a live reproduction case? thanks!

**Comment by FractalWire** [comment]
I forked the repo and added an example in the branch `ais-hitissue`. [Here](https://github.com/FractalWire/openlayers/tree/ais-hitissue)
I use ol-hashed in the example so an `npm install` might be needed here

For the relevant code. In `hitais.frag`:

```glsl
vec4 getPolygon(vec2 p, vec4 polycolor){
    if (!isInPoly(p, poly, n))
        return outsidecolor;
    return polycolor;
}
```

In `optimized_ais.frag`:

```glsl
vec4 getPolygon(vec2 p,
        vec4 polycolor, vec4 strokecolor,
        float strokesize, vec2 strokeParams){

    if (!isInPoly(p, poly, n))
        return outsidecolor;

    vec2 u;
    vec2 v;
    float pDist = 0.;
    int ind = closestSegment(p, u, v, pDist);
    vec2 proj = projection(p, u, v, true);

    float sDist = distanceToSegment(p, u, v);

    if (sDist > strokesize){
        return polycolor;
    }

    pDist += distance(u, proj);

    return applyStroke(sDist, pDist, polycolor,
            strokecolor, strokesize, strokeParams);
}
```
Which could easily be simplified like so:

```glsl
vec4 getPolygon(vec2 p,
        vec4 polycolor, vec4 strokecolor,
        float strokesize, vec2 strokeParams){

    if (!isInPoly(p, poly, n))
        return outsidecolor;
    return strokecolor;
```
... but doesn't work better.

I basically use the `PointLayer` class to draw my symbols. Which means, no fancy vertex for polygon drawing, everything is done in the fragment shader.
That also means, every symbol are drawn with a large empty transparent area around it.

If Openlayers only considers the topmost symbol for color comparison for the hit detection, then, it might compare that empty transparent space and find that there is no hit.
So every symbol below the topmost one might never be checked by Openlayers.

I think this is what's happening here. You can actually see this if you change the `outsidecolor` in `optimized_ais.frag` to somehing more colorful:

```glsl
vec4 outsidecolor = vec4(1.,0.,0.,0.2);
```

**Comment by jahow** [comment]
> For the relevant code. In `hitais.frag`:
> 
> ```glsl
> vec4 getPolygon(vec2 p, vec4 polycolor){
>     if (!isInPoly(p, poly, n))
>         return outsidecolor;
>     return polycolor;
> }
> ```

This is it! The hit detection render is done *without* alpha blending, see:
https://github.com/openlayers/openlayers/blob/db08e0562f2b72e47b5240b7b811ba363964188c/src/ol/renderer/webgl/PointsLayer.js#L641-L645

This means that if you output a color that has all channels at 0 such as `outsidecolor`, it will still overwite the existing color there. To avoid this, use `discard;` instead (which skips drawing the pixel altogether).

**Comment by FractalWire** [comment]
I get it now.
Not drawing pixel when there is none is much better !

Thanks !
