### ISSUE TITLE
un() does not remove a listener added with once()

### ISSUE THREAD

**Issue by frozeng** [openlayers/openlayers#11147]
**Describe the bug**
`map.un()` does not remove a listener added with `map.once()`

```
const listenerOn = () => {
    alert('on');
};
      
map.on('singleclick', listenerOn);
map.un('singleclick', listenerOn);
      
const listenerOnce = () => {
    alert('once');
};
      
map.once('singleclick', listenerOnce);
map.un('singleclick', listenerOnce);
```

**To Reproduce**
1. Go to https://jsfiddle.net/frozenghost/jzq3cb9s/3/
2. Click on the map
3. See alert() with message 'once'

**Expected behavior**
`un()` should remove `once()` added event listener and no alert() should be shown.

**Comment by ahocevar** [comment]
This is because `once()` wraps the listener into another function, so `un()` will not find the listener.

A workaround is to use `Observable.unByKey`.
