### ISSUE TITLE
OL6 Vector Layer with GeoJSON source renders incredibly small when using React

### ISSUE THREAD

**Issue by kiddhustle** [openlayers/openlayers#11161]
**Describe the bug**
When rendering an OpenLayer 6 map with React, and loading GeoJson featurecollection (variable) as a source, the vector layer is rendered incredibly small.

Using the same data (GeoJSON) to populate a vector layer works fine when using a plain HTML page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://kiddhustle.github.io/react-openlayers-geojson/
2. See error. The blue dot in the centre of the map is the vector layer at a tiny size.
3. Zoom in multiple times to see the vector outlines of countries of the world.

**Expected behaviour**
The vector layer to outline the countries of the world at the correct stage.

**Source code**

https://github.com/kiddhustle/react-openlayers-geojson

**Comment by mike-000** [comment]
The data is in EPSG:4326 coordinates and the features need to be displayed in your view projection which is EPSG:3857.  If you are reading it using readFeatures you must specify the projections
https://github.com/kiddhustle/react-openlayers-geojson/blob/master/src/App.js#L27

```
features: new GeoJSON().readFeatures(countryFeatures, {
  dataProjection: 'EPSG:4326',
  featureProjection: 'EPSG:3857'
}),

```

**Comment by kiddhustle** [comment]
@mike-000 thanks!

I did try the featureProjection option but didn't think of the dataProjection option.

Thanks again :)
