### ISSUE TITLE
Feature.setStyle should be nullable

### ISSUE THREAD

**Issue by bkuster** [openlayers/openlayers#11160]
**This is a documentation bug.**
The doclet for `ol/Feature#setStyle` reads `@param {import("./style/Style.js").StyleLike} style`.
But the documentation cleary states to pass `null` for _unsetting_ the style (I personaly like to omit the style, so call `feature.setStyle();`). Either way: the docs should allow the style to be nullable or optional or both. I will make a PR for this if you like, just need to figure out which design you guys like `setStyle(null)`  or `setStyle()` or either.

**Comment by mike-000** [comment]
null (no style) and undefined (default style) are both valid settings and also apply to layer styles.  I think the StyleLike definition should include them.

**Comment by bkuster** [comment]
right you are! and makes total sense to add it to the typedef.

**Comment by bkuster** [comment]
I thought about this some more, not sure if I like the semantic implication of changing the `ArchType` `StyleLike` instead of the function signature.

**Comment by mike-000** [comment]
The typedef is also used for the layer style option.  In the case of layers whatever is valid for `setStyle` is also valid as a layer option https://github.com/openlayers/openlayers/blob/master/src/ol/layer/BaseVector.js#L118
and the code for `setStyle` checks for settings that the typedef doesn't include
https://github.com/openlayers/openlayers/blob/master/src/ol/layer/BaseVector.js#L235

Also `setStyle` for features does not do as the description says 
https://github.com/openlayers/openlayers/blob/master/src/ol/Feature.js#L246
`!style` does not distinguish between null and undefined so setting the style to null means the layer style is used. To suppress styling you would need to use an empty array `[]`.  That might be an oversight or regression, I think it should be genuinely nullable as it is for layers.

**Comment by ahocevar** [comment]
The type defnition for `Feature#setStyle()` should be the same as for `Layer#stStyle()`. Pull request welcome.

**Comment by mike-000** [comment]
Interaction styles also seem inconsistent.  Draw and Modify do not distinguish between undefined and null, while Select does.

**Comment by ahocevar** [comment]
I think these distinctions are legacy from times when we used Closure Compiler. If null and undefined enter the same code path with the same result, then all is good. If they do different things, we should take a closer look.

**Comment by ahocevar** [comment]
#11174 improves the types and docs. @bkuster, you can definitely call `feature.setStyle()` to unset the style. It is equivalent to `feature.setStyle(null)` or any falsey value as argument.

**Comment by bkuster** [comment]
thanks for the fix. would have opened a PR next week, but am sadly crunching at the moment.
