### ISSUE TITLE
"Blob is not defined" - using WebGLPointsLayer in Angular Universal

### ISSUE THREAD

**Issue by BogdansBodega** [openlayers/openlayers#11164]
Hello!

I'm not sure if I'm doing something wrong or if this is a bug. I'm using openlayers in my angular 9 application and i have to show around 10000 objects in the map. I had some troubles with performance until i changed my VectorLayer to a WebGLPointsLayer. Everything worked fine until i started the application with server rendering instead. I have no problems with any other layer in the application except for the WebGLPointsLayer which gives me the error: 

"var blob = new Blob([source], { type: 'application/javascript' });
           ^
ReferenceError: Blob is not defined"

My configuration for the layer is: 

```
export const webGLPointsLayer = new WebGLPointsLayer({
  source: source,
  style: {
    symbol: {
      symbolType: SymbolType.CIRCLE,
      size: [10, 10],
      opacity: 0.5,
      rotateWithView: false,
      color: '#C94A18',
    },
  },
});
```
Any ideas?

**Comment by mike-000** [comment]
WebGLPointsLayer uses a plugin https://github.com/openlayers/openlayers/blob/master/tasks/serialize-workers.js#L45 which requires browser support (or polyfills) for Blob, URL and Worker as well as support for WebGL.  Except for URL on IE11 no modern browsers should need that. Angular does have a polyfill for Blob https://angular.io/guide/browser-support#polyfills but I'm not sure of the practically of using server rendering for an interactive WebGL application.
