### ISSUE TITLE
Extent interaction prevents alt shift drag rotation

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11163]
**Describe the bug**
The extent interaction is working with alt shift drag as well as shift drag, which prevents the user rotating the view.

**To Reproduce**
Open https://openlayers.org/en/latest/examples/extent-interaction.html and attempt to rotate the view using alt shift drag. The view does not rotate as the extent interaction takes over.

**Expected behavior**
The extent interaction should not operate when keys other than shift are pressed.

**Comment by ahocevar** [comment]
Not sure if this is a bug or a feature. As default behavior, I think it is fine the way it is. Making the interaction configurable with a `condition` could make sense though.
