### ISSUE TITLE
Rotation not working correctly in dev version

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11162]
**Describe the bug**
Using alt shift drag to rotate the view in the dev version is also panning the map instead of simply rotating around the view center.

**To Reproduce**
Open https://openlayers.org/en/latest/examples/simple.html zoom in 2 levels to avoid any conflict with multiWorld: false and use alt shift drag to rotate.  The view rotates around the center as expected.  Resetting the rotation restores the view to its original setting.

Repeat with https://openlayers.org/en/master/examples/simple.htm  The view rotates apparently around a random position as it also pans.  Resetting the rotation does not restore the view to its original position.

**Expected behavior**
alt shift drag should not pan the view.

**Comment by ahocevar** [comment]
Thanks for reporting this @mike-000. 2cac6c4f39521470a899f1c6338aa47baea05392 is the first bad commit:
```
commit 2cac6c4f39521470a899f1c6338aa47baea05392
Author: Andreas Hocevar <andreas.hocevar@gmail.com>
Date:   Wed Jun 3 12:29:37 2020 +0200

    Re-enable onFocusOnly option for interaction defaults
```
Looking into a fix now.
