### ISSUE TITLE
WebGL use case: streaming lots of geometries in real-time

### ISSUE THREAD

**Issue by FractalWire** [openlayers/openlayers#11169]
Not a feature or a bug report.
It's more a discussion about what could be done in the future with WebGL for that kind of use case.

The use case in question.
Around 100K geometries have to be represented on the map.
Each of those geometry will update at most every few seconds and will be pushed toward Openlayers via Websocket for example.

As of right now, this would mean that every time a feature is updated, Openlayers has to rebuild the shaders' buffers for WebGL.
The performance would therefore be atrocious.

We can imagine that tiling capability for WebGL could enhance this. In that case, multiple buffers may exist (?) for the different tile.
But then, everytime a highly populated tile is updated this would mean a slow down.

Alternatively, we could split the geometries not with tiles but by grouping them every X geometries without considering their positions.
For example, every 1K geometries, would have their own WebGL buffer.
Here the number of geometry to group by should be choose carefully. Too large, and there is a high chance that a geometry updates, and updates at the same time the whole buffer. Too little, and I guess, this would cause memory issue, or some other weirdness, as there would be too many GPU programs running at the same time (just a guess here).

What is your take on that ?
How would you approach this problem ?
Could Openlayers propose some solution for that kind of use case in the future ?

**Comment by jahow** [comment]
Technically nothing prevents us from updating only parts of the vertex buffers in webgl. There are some things to consider though:
* currently we're only dealing with points; eventually we might have geometries with variable amount of coordinates, so having one huge buffer with all geometries inside might not be the most future-proof choice
* listening on changes on individual features will definitely be too costly

The most logical approach would be to group features by some criteria (maybe just order of appearance?) and use separate buffers for each group of features. Then, when a feature gets updated, the buffers for the whole group can be rebuilt.

An option could be offered in the API to favor either frequent updates and high rendering time (small groups), infrequent updates and low rendering times (large groups) or balanced.

**Comment by FractalWire** [comment]
> currently we're only dealing with points; eventually we might have geometries with variable amount of coordinates, so having one huge buffer with all geometries inside might not be the most future-proof choice

If I understand correctly, knowing the number of coordinates for features in the buffer is a must-be to be able to update part of the buffer easily.
Then another grouping possibilities might be to group geometries by number of coordinates.

> The most logical approach would be to group features by some criteria (maybe just order of appearance?) and use separate buffers for each group of features. Then, when a feature gets updated, the buffers for the whole group can be rebuilt.

This is indeed easy to understand how this would work.
However, this approach would always be sub-optimal. You will always do some unneeded work whenever you update a buffer.
And if the geometry updates are spread evenly among groups at any time, the performance gain might be small (or you'd need to use very small group size)

> Also if the features are grouped by proximity, a basic culling operation can be done to avoid drawing out of view groups for free. But this comes at the cost of added complexity when a feature geometry is changed (which might switch groups).

This would only makes sense for very large dataset (1M+ geometries) where you expect performance drop when all geometries are in view.
Even though reducing impact on ressource usage is always good, I'd say this would be a niche use case as this would imply the worst case scenario has bad performance.

**Comment by jahow** [comment]
> If I understand correctly, knowing the number of coordinates for features in the buffer is a must-be to be able to update part of the buffer easily.

Also, the amount of coordinates in a geometry can change. And we cannot add/remove numbers in a buffer like we would in a regular array. So there would be two cases:
1. some vertices in a geometry are updated; this can be done without rebuilding the whole buffer
2. a geometry gains or lose vertices (ie when drawing a polygon, or adding/removing to a geometry collection); this requires a full rebuild

This way having moving points in a large dataset (which is a common usecase) could be quite fast, provided it's not multi points.

**Comment by FractalWire** [comment]
Being able to stream geometries that gain/lose vertices fast could opens interesting possibilities.

If we had different buffer for each n-vertices geometries, updating or adding a geometry is not hard, if I understand well, and those operations do not require a full rebuild.
Only deleting requires the full rebuild, because then, you have old data.
If, for every geometries in the buffers, we passed a boolean attribute `a_discard`, then in the vertex buffer, the first instruction could be:
```glsl
if (a_discard){
  discard;
}
```
Skipping rendering for that geometries.
Now, to update a geometry from n vertices to n+1 vertices, you only need to set `a_discard` to `true` in the n-vertices buffer and add the geometry to the (n+1)-vertices buffer.

That way, no need to rebuild buffers at all.

On the javascript side, it would require to track the empty space in each buffer to be able to add new geometry to the first empty space instead of the end of the buffer.
And an occasionnal rebuild might be useful if the buffer become too fragmented.

**Comment by jahow** [comment]
I don't know, this sounds a bit complex regarding the expected gain. Rebuilding a buffer isn't an extraordinary thing to do, it's long if you have many features in it (> 10'000 becomes noticeable I'd say) but it's still manageable.

**Comment by FractalWire** [comment]
Without considering the number of vertices of a geometry.
If you need to remove multiple geometries in a large dataset during a short interval, you'd need to rebuild the buffer and lag would be significant. Even if you group features in different buffer, in the worst case scenario, the deletions would be spread evenly accross the buffers and so would be similar to rebuilding one big buffer.
Having a buffer with empty geometry space in it would avoid that entirely for sure.

Now, it's also possible to have a large number of multi-vertices geometry.
For example a large number of single point geometry represented by a polygon shape.

Now, will there be a lot of use cases for a large number of geometries with their number of vertices varying in real-time ?
That would definitely be a very exciting application.
Cloud-shapes updating in real-time, historical paths of multiple gps devices, various animations like replaying the historical countries borders or the icebergs breaking from the ice floe for example. I'm sure there is more even if a bit niche.
