### ISSUE TITLE
map cannot be dragged in chrome 49 

### ISSUE THREAD

**Issue by guxin0123** [openlayers/openlayers#11179]
**Describe the bug**
Found that the map cannot be dragged in chrome 49 in versions greater than v6.2.0

chrome 49 x32 is the last version that supports windows xp and windows 2003

**To Reproduce**
1. Use chrome 49 to access 'https://openlayers.org/en/v6.2.0/examples/wmts.html'
2. Dragged  on map
3. See error

**Comment by M393** [comment]
https://github.com/openlayers/openlayers/issues/10724#issuecomment-59021194 is the same issue and provides a solution.

**Comment by guxin0123** [comment]
Thanks, that did the trick.
