### ISSUE TITLE
The map event is not available in the WeChat browser

### ISSUE THREAD

**Issue by yuzhiyao** [openlayers/openlayers#11170]
**Describe the bug**
The map event is not available in the WeChat browser，

**To Reproduce**
1. OS:  Window 
2. WeChat Version: 2.90.112
3. Go to 'https://openlayers.org/en/latest/examples/hitdetect-vector.html'
4. When the mouse moves to feature，the feature can not hight light.

**Expected behavior**
The map event can support WeChat browser.  
map.on('', function(){})；  The callback function executes normally

**Comment by ahocevar** [comment]
Does it work with https://openlayers.org/en/master/examples/hitdetect-vector.html?

**Comment by yuzhiyao** [comment]
Doesn't work with https://openlayers.org/en/master/examples/hitdetect-vector.html .

**Comment by yuzhiyao** [comment]
On the PC WeChat.  the map can drag with https://openlayers.org/en/v4.6.5/examples/animation.html.  But in the latest version

can't drag map . Such as https://openlayers.org/en/master/examples/animation.html.

**Comment by ahocevar** [comment]
Please try https://deploy-preview-11192--ol-site.netlify.app/examples/animation.html and https://deploy-preview-11192--ol-site.netlify.app/examples/hitdetect-vector.html. In these versions, a more sophisticated pointer events polyfill is loaded (see #11192).
