### ISSUE TITLE
Preload an image on Icon

### ISSUE THREAD

**Issue by Charl20cas** [openlayers/openlayers#11184]
I have a Feature with an svg image. Hovering over the element, I change the style of the feature with a new image, the problem is that the current image disappears and there is a little delay in showing the new image. Is there a way to preload this new image so that the change is immediate?

Default style
```
const feature = new Feature({
.
.
.
});
const featureStyle = new Style({
    image: new Icon({
        anchor: [anchorX, anchorY],
        src: 'data:image/svg+xml,IMGE_SVG',
        size: [width, height],
        color: 'white',
        scale: 1
    });
});
feature.setStyle(featureStyle);
```
Hover on feature

```
feature.setStyle(new Style({
    image: new Icon({
        anchor: [anchorX, anchorY],
        src: 'data:image/svg+xml,HOVER_IMGE_SVG',
        size: [width, height],
        color: 'white',
        scale: 1
    });
}))
```

**Comment by mike-000** [comment]
You can preload the svgs to JavaScript Image objects and use the `img` option in the ol/style/Icon constructor

**Comment by Charl20cas** [comment]
It works, thanks!!
