### ISSUE TITLE
refresh does not reload data

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#11211]
The documentation of ol/source/Image states:
```
* Refreshes the source. The source will be cleared, and data from the server will be reloaded.
```
I created a simple example where on click a refresh for a vector source, an imagewms source and an osm source gets called. The OSM Layer flashes, but no new request is created.

See https://codesandbox.io/s/wms-image-ut9ru and check the developer console.

Either the documentation should be changed or clarified or it could actually get implemented in the way it is stated. Especially for a WMS it can be very useful to reload it (imagine an application where you can edit data that is displayed via a WMS).

**Comment by mike-000** [comment]
If you add load functions to your WMS and OSM source you will see they are refreshed

```
const wms = new ImageWMS({
  url: 'https://ahocevar.com/geoserver/wms',
  params: {'LAYERS': 'topp:states'},
  ratio: 1,
  serverType: 'geoserver',
  imageLoadFunction: function(image, src) {
    console.log('image loader called');
    image.getImage().src = src;
  }
});

const osm = new OSM({
  tileLoadFunction: function(tile, src) {
    console.log('tile loader called');
    tile.getImage().src = src;
  }
})
```

**Comment by simonseyock** [comment]
I see, thank you. I was a little confused as I assumed that a cached request would also show up in the network tab. The solution would be to add a random string then. Maybe we could enhance the documentation there?

Maybe something like:
```
* Refreshes the source. The source will be cleared, and data from the server will be reloaded. In case of image sources the browser will use the cached image if the url did not change.
```

**Comment by ahocevar** [comment]
@simonseyock Such a documentation change would not be correct. If the WMS sends proper cache headers or ETags, the images will be refetched, even if the url is the same. Proper server configuration is the solution here.

**Comment by simonseyock** [comment]
The sentence `data from the server will be reloaded` is then also not always correct. Maybe:
```
* Refreshes the source. The source will be cleared, and data from the server will be reloaded if proper cache headers or ETags are used.
```
But I can see that this lies outside the realm of openlayers.

**Comment by nboisteault** [comment]
Hi,
I can observe this cache issue with Firefox not Chromium. In FF, the same WMS request with same parameters uses the cache which is not wanted after a edition for example.
I saw that in OL2 an `_olsalt` parameter was used. Is it a good solution or are there configurations to be made browser and/or server side?

**Comment by mike-000** [comment]
The simplest way to override browser cache is to add an extra parameter to the url which will be ignored by the server but will be treated as a different url by the browser

```
tileLoadFunction: function(tile, src) {
  tile.getImage().src = src + '&TIMESTAMP=' + Date.now();
},
```

**Comment by ahocevar** [comment]
To answer @nboisteault's question: this is NOT a good solution. A better solution is to let the server send an etag header, so the browser knows when content has changed.

**Comment by nboisteault** [comment]
@ahocevar ETags are a good solution for efficient caching but what about images dynamically generated via GetMap requests? We would need to hash images to generate corresponding ETags? If there are a lot of layers and many GetMap requests with many different BBOX we would quickly fill the cache with few chances to hit some cached images don't you think?

**Comment by mike-000** [comment]
Etags do not help if third parties such as weather radar services do not use them **and** set a cache `max-age` as long as the update interval.  It may update every 15 minutes but it can take another 15 minutes to get it.

**Comment by ahocevar** [comment]
@nboisteault Most HTTP servers like nginx, and also WMS servers like GeoServer, can provide at least weak ETags for dynamic content, which - in conjunction with a `max-age: 0` header, will solve the issue. Guessing from your question, I assume you can control the server and make them send these servers.

What @mike-000 is true for servers you cannot control.

**Comment by nboisteault** [comment]
@ahocevar What do you mean by "weak" ETags?

**Comment by ahocevar** [comment]
@nboisteault Those prefixed with `W/`. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#directives.
