### ISSUE TITLE
Different computer, different canvas

### ISSUE THREAD

**Issue by Yuki-Zhao** [openlayers/openlayers#11214]
when i use laptop. i add two layers on map. so, there are two canvas . but when i use computer, also, i add two layers on map. there is only one canvas. all layer is in this canvas. so why ?

**Comment by ahocevar** [comment]
Probably because your computers have a different `devicePixelRatio`. This will cause different canvas sizes for vector and vector tile layers, and affect how the canvases are reused for subsequent layers.

**Comment by Yuki-Zhao** [comment]
OK， thanks
