### ISSUE TITLE
How to control the zoom effect on the rendered image and force a pixelated view

### ISSUE THREAD

**Issue by caillat** [openlayers/openlayers#11212]
**Is your feature request related to a problem? Please describe.**
My question is motivated by a need to avoid the interpolation which is applied on an zoomed in image so that it appears smooth. 

**Describe the solution you'd like**
I would like to have the option of displaying pixelated zoomed in image . Is there a way to do that ? I tried to play with the css property `image-rendering` applied on `img` or `canvas` element but without any success

**Comment by mike-000** [comment]
In 6.3.1 you can use the prerender event to set `evt.context.imageSmoothingEnabled = false` as in https://openlayers.org/en/latest/examples/sea-level.html

In the dev version tile and image sources have a `imageSmoothing` option

**Comment by caillat** [comment]
@mike-000 Thank you. Alas as mentioned in  #11199 I have a problem with OpenLayers above 5.2.2 for which I'm still waiting for ideas. Otherwise I'd be very happy to use your input.
