### ISSUE TITLE
getTileCoordAndZ

### ISSUE THREAD

**Issue by andrew-linck** [openlayers/openlayers#11229]
**Is your feature request related to a problem? Please describe.**
using getTileCoordForCoordAndZ() to get tile coordinates by passing through the mouse coordinates and zoom level

Documentation needs to write that for z in getTileCoordForCoordAndZ it must be a int.
**Describe the solution you'd like**

Documentation should say that you should pass getZForResolution() as the z for getTileCoordForCoordAndZ().

**Comment by ahocevar** [comment]
Thanks for reporting this @andrew-linck. Would you be able to create a pull request with the suggested documentation improvement? Thanks in advance!

**Comment by arekgotfryd** [comment]
Is pull request still being accepted for this one?

**Comment by ahocevar** [comment]
Sure! Should be a straightforward documentation only change.
