### ISSUE TITLE
WMTS tile loading unstoppable loop

### ISSUE THREAD

**Issue by wussup** [openlayers/openlayers#11223]
Hello,

I experienced a WMTS tile loading unstoppable loop when there is a huge map (ex. 4000px x 2000px):

https://codesandbox.io/s/wmts-brj86?file=/index.html

The same tiles are loading multiple times and the loop is unstoppable.

OpenLayers 6.3.1

Probably something wrong in [TileQueue](https://github.com/openlayers/openlayers/blob/main/src/ol/TileQueue.js) file or in [PluggableMap](https://github.com/openlayers/openlayers/blob/main/src/ol/PluggableMap.js) file in place, where TileQueue is creating.

Could you please help me?

**EDIT:**
If I have a smaller map (ex. 2000px x 1200px), then everything works like a charm:

https://codesandbox.io/s/wmts-b9y7l?file=/index.html

**EDIT2:**
3500px x 1750px -> working bad
3000px x 1500px -> working good

**Comment by mike-000** [comment]
Even the OSM layer alone doesn't render completely.  The default `cacheSize` is based on screen size, if your map div is significantly bigger than the screen size you will need to supply a value.  `cacheSize: 187` works for me with the OSM layer based on `(Math.ceil(4000/256)+1)*(Math.ceil(2400/256)+1)`.

**Comment by wussup** [comment]
> Even the OSM layer alone doesn't render completely. The default `cacheSize` is based on screen size, if your map div is significantly bigger than the screen size you will need to supply a value. `cacheSize: 187` works for me with the OSM layer based on `(Math.ceil(4000/256)+1)*(Math.ceil(2400/256)+1)`.

Brilliant, thank you! Everything works well!
