### ISSUE TITLE
Raster Source memory leak in Safari

### ISSUE THREAD

**Issue by BerndSchrooten** [openlayers/openlayers#11221]
**Describe the bug**
Interacting with a map that uses a raster source, causes JS memory usage to increase steadily over time in Safari. This behavior does not appear to be present in other examples on the OpenLayers website.

<img width="1490" alt="Screenshot 2020-06-26 at 09 41 26" src="https://user-images.githubusercontent.com/9282724/85833601-46411500-b792-11ea-8039-f7cc27bbbb3c.png">

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/raster.html' in Safari
2. Open developer tools -> Timelines and start recording memory usage
3. Interact with the map (pan, zoom,...)
4. See JS memory usage increase over time

**Expected behavior**
Memory usage should not increase at this rate. Chrome stays below 20MB while performing the same test.

**Comment by EvertEt** [comment]
I noticed this as well on our app, JS allocation memory snapshot only shows 150MB but the memory timeline keeps increasing until crash:
![image](https://user-images.githubusercontent.com/9197891/85836886-9a9ac380-b797-11ea-8be1-9455c81e4e63.png)
