### ISSUE TITLE
Most basic React example not rendering map

### ISSUE THREAD

**Issue by orpheus** [openlayers/openlayers#11220]
https://codesandbox.io/s/open-layers-4r2h5?file=/src/App.js

Code taken from the `README.md`

What am I missing?

**Comment by EvertEt** [comment]
It seems like your map is being rendered but now shown. Add `style={{ height: "400px", width: "400px" }}` to you map div.

**Comment by orpheus** [comment]
lol yup that was it, thank you

**Comment by orpheus** [comment]
@EvertEt if you could help out and take one more look at something - I don't want to open another ticket but by docs this should be working.

Here's a basic example of trying to render one layer with 3 features on it. The map shows that a layer and layer source was added and that the layer source has features, but nothing appears on the map. I've verified my coordinates and projection with [this map projection site.](https://epsg.io/map#srs=4326&x=-87.458832&y=20.213287&z=15&layer=streets) 

https://codesandbox.io/s/open-layers-fork-2xm6p?file=/src/Vector.js

**Comment by EvertEt** [comment]
![image](https://user-images.githubusercontent.com/9197891/85920130-74495680-b871-11ea-97d1-64cc95ff8287.png)
I see them on your example so not sure why you are not

**Comment by orpheus** [comment]
Must have changed some code, I see them now in one example and not in another. Either way thank you
