### ISSUE TITLE
Modify interaction bug

### ISSUE THREAD

**Issue by michalzielanski** [openlayers/openlayers#11222]
The interaction does not work correctly when editing geometry `GeometryCollection`.
When the same geometries are assigned to features and aggregated in `FeatureCollection`, everything works fine.

1. Go to https://codesandbox.io/s/openlayers-modify-interaction-bug-xgohm
2. Drag the common vertex of both polygons

![modify-interaction-bug](https://user-images.githubusercontent.com/5003/85848942-5c5acf80-b7aa-11ea-8b26-e3ab39f79227.gif)

**Comment by michalzielanski** [comment]
It looks like the problem is here:
https://github.com/openlayers/openlayers/blob/af9f26b9d343e5496ea44a729265c4002616b240/src/ol/interaction/Modify.js#L843
`uid` should be geometry dependent:
```js
let uid = getUid(segmentDataMatch.geometry);
```

**Comment by ahocevar** [comment]
@michalzielanski If this does not break any tests or examples, can you create a pull request with this change? Your suggested change makes sense to me.

**Comment by michalzielanski** [comment]
Yes, I will create a pull request tomorrow.
