### ISSUE TITLE
How to use WFS from GeoServer in OpenLayers 6?

### ISSUE THREAD

**Issue by Spatialghost** [openlayers/openlayers#11230]
i trying to display vector layer as WFS from local GeoServer in OpenLayers 6.3.1. When i trying add new vector layer, at the map i see only base map. However all data at GeoServer has projection EPSG:3857. How to fix this problem? My code:
````
var vectorSource = new VectorSource({
  format: new GeoJSON(),
  url: function(extent) {
    return 'http://localhost:8080/geoserver/geodata/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=geodata%3Amlink&maxFeatures=50&outputFormat=application%2Fjson';
        
  },
  
  strategy: bboxStrategy,
});


var vector = new VectorLayer({
  source: vectorSource
});




var map = new Map({
  layers: [
    new TileLayer({
      source: new OSM(), //projection: 'EPSG:3857',
      opacity: 0.7
    }),
    vector],
    target: document.getElementById('map'),
  view: new View({
    //projection: 'EPSG:3857',
    center: [6181942.5743,7443423.3883],
    zoom: 11
    //maxZoom: 19,
    //zoom: 12
  })
});`
```

**Comment by Spatialghost** [comment]
``

**Comment by mike-000** [comment]
If you are using bbox stragegy you should set the extent in the url (especially as you have set maxFeatures - try removing that) and explicitly set the SRS as in the example where the WFS is serving GeoJSON output in EPSG:3857 https://openlayers.org/en/latest/examples/vector-wfs.html
