### ISSUE TITLE
Missing named exports from ol/geom

### ISSUE THREAD

**Issue by jmacura** [openlayers/openlayers#11233]
**Is your feature request related to a problem? Please describe.**
Is there a reason why `GeometryLayout`, `GeometryType` and `SimpleGeometry` are missing as named exports from [ol/geom.js](https://github.com/openlayers/openlayers/blob/v6.3.1/src/ol/geom.js) ?

**Describe the solution you'd like**
Add these exports into the ol/geom.js file. I can make a PR, but wanted to ask, if there is an intention first.

**Comment by ahocevar** [comment]
`SimpleGeometry` is not part of the API, and `GeometryLayout` and `GeometryType` are `@enum`s which are also not part of the API. So I would say `ol/geom.js` contains everything it should contain.

Note that you can always import `GeometryLayout`, `GeometryType` or `SimpleGeometry` directly from their respective modules if you wish so, e.g.
```js
import SimpleGeometry from `ol/geom/SimpleGeometry`;
```

**Comment by jmacura** [comment]
> 
> `SimpleGeometry` is not part of the API, and `GeometryLayout` and `GeometryType` are `@enum`s which are also not part of the API. So I would say `ol/geom.js` contains everything it should contain.
> 

How comes they are not part of the API? I can see them in the API doc:

- https://openlayers.org/en/latest/apidoc/module-ol_geom_GeometryType.html
- https://openlayers.org/en/latest/apidoc/module-ol_geom_GeometryLayout.html
- https://openlayers.org/en/latest/apidoc/module-ol_geom_SimpleGeometry-SimpleGeometry.html

**Comment by ahocevar** [comment]
As it turns out, I was wrong about SimpleGeometry. It is part of the API. Sorry for the confusion. Would you be able to create a pull request that re-export `SimpleGeometry` from `ol/geom`? Thanks in advance.

Enums are only documented for reference, so users can see the allowed values. See the bottom of https://openlayers.org/en/latest/apidoc/:

> *Note*: The API change policy does not cover CSS class names that are used to style the OpenLayers UI. It also does not cover any typedefs and enums.

**Comment by jmacura** [comment]
> 
> As it turns out, I was wrong about SimpleGeometry. It is part of the API. Sorry for the confusion. Would you be able to create a pull request that re-export `SimpleGeometry` from `ol/geom`? Thanks in advance.

Sure, I will make a PR.

> 
> Enums are only documented for reference, so users can see the allowed values. See the bottom of https://openlayers.org/en/latest/apidoc/:
> 
> > _Note_: The API change policy does not cover CSS class names that are used to style the OpenLayers UI. It also does not cover any typedefs and enums.

I understood this sentence in a way that typedefs and enums are not subject to the API change policy, hence they can change within a major release, not that they are not a part of the API.

Furthermore, the same part of the site states that
> The OpenLayers API consists of
> ...
> names of constants

Technically, enums are just a type of constants.
So am I mistaken completely in this matter?

**Comment by ahocevar** [comment]
The intended use of OpenLayers enums is e.g.
```js
import Draw from 'ol/interaction/Draw';
const draw = new Draw({
  type: 'Polygon'
});
```
So as you can see, the `GeometryType` enum is not used at all. And in the future, they might even go away in favor of something like
```js
export const GeometryType = {
  Point: 'Point',
  MultiPoint: 'MultiPoint',
  LineString: 'LineString',
  MultiLineString: 'MultiLineString',
  Polygon: 'Polygon',
  MultiPolygon: 'MultiPolygon'
}
```
so we can use `@type {keyof GeometryType}` as type, which will make TypeScript and IntelliSense work in a nice way.

So as you can see, you don't want to use them, because if we make such a change, you would have to change your code too.

**Comment by jmacura** [comment]
Thanks for the explanation @ahocevar . This is good to know that our team's code should not rely on the GeometryType (which it does now).

Hence, I have made the PR for the SimpleGeometry as discussed above.
