### ISSUE TITLE
Build instructions for normal modules.

### ISSUE THREAD

**Issue by Dreamsorcerer** [openlayers/openlayers#11236]
It seems all the build instructions are for various build tools, but I'm not using any for my project. I'd like some build instructions that allow me to use this with normal JS modules (in particular, inside web components).

Expected interface to import would be something like:
```
import("./ol.js").then((ol) => {
    ol.Map(...);
});
```

Trying this with the pre-built dist version doesn't work. I'd also like to explicitly choose what components should be included in the built version, in order to have a slim production build.

Any clues on how to build such a bundle would be great.

**Comment by jahow** [comment]
Hi,

> Trying this with the pre-built dist version doesn't work.

Can you be more specific? This looks like it should work (except for the missing `new` in front of `ol.Map`, see your other issue).

Generally speaking, you'll always be better off using OpenLayers as ES6 modules. It should be possible to import these dynamically like in your snippet, although I personally have never tried that. Also this might prevent tree shaking i.e. excluding unused parts of the library.

If you want to use the full minified build (`ol.js`), you will not be able to exclude parts of the library yourself. There used to be ways to do custom builds, but not any more (since bundling ES6 modules will do that for you).

**Comment by Dreamsorcerer** [comment]
The other bug, I was using a hacky workaround, loading the script with a normal `<script>` tag, and then adding a timeout, to give it a chance to load the library. i.e. Not a module.

If I import with the above method as a module, I get `TypeError: ol.proj is undefined`. Printing out the module object from the import just outputs:
```
{…}
​
Symbol(Symbol.toStringTag): "Module"
```

There's nothing in the object.


I've just spent the last couple of hours looking at npm/parcel building, and my theory is that I could just create an index.js file containing only:
```
export {Map, View} from 'ol';
export {TileLayer} from 'ol/layer/Tile';
export {OSM} from 'ol/source/OSM';
```
and build that.

However, this still doesn't work currently. I found some indications that this should work in Parcel 2, with this added to package.json:
```
  "targets": {
    "main": {
      "outputFormat": "esmodule"
    }
  },
```
But, currently I'm stuck trying to figure out how to install a beta version of Parcel (I really have no familiarity with npm/parcel).

**Comment by Dreamsorcerer** [comment]
Depends on: https://github.com/parcel-bundler/parcel/issues/4849

**Comment by Dreamsorcerer** [comment]
Upstream bug is fixed, so hopefully we can have some working instructions once parcel beta2 is released.

**Comment by ahocevar** [comment]
We have updated the example code snippets to use Parcel 2. I tried some examples, and all seemed to work fine.

**Comment by Dreamsorcerer** [comment]
As a module? i.e. You need to add to package.json:
```
  "targets": {
    "main": {
      "outputFormat": "esmodule"
    }
  },
```

See the mentioned issue for a complete example: https://github.com/parcel-bundler/parcel/issues/4849

**Comment by ahocevar** [comment]
The goal of our example code snippets is not to generate ES modules, but a complete bundle. Maybe I'm misunderstanding this issue.

**Comment by Dreamsorcerer** [comment]
As per the initial report, the complete bundle can't be used as a vanilla JS module, like:
```
import("./ol.js").then((ol) => {
    ol.Map(...);
});
```

I was requesting instructions on how to use openlayers as a regular module, without needing to have my project built in webpack, parcel or any other tool.

My investigations have led to building openlayers using parcel with that esmodule option, which once working, I believe will allow me to use the result in vanilla JS. Once I have this working, I'd like to add these instructions so that other people don't have to go through this process too.

**Comment by Dreamsorcerer** [comment]
Still relevant until the PR is reviewed...

**Comment by Dreamsorcerer** [comment]
..

**Comment by not-a-lot** [comment]
I’ve tried to use OpenLayers as untranspiled modules like the [README](https://github.com/openlayers/openlayers/blob/main/README.md#es-modules) suggests, but it seems that not everything is included in there, for example ol/layer/BaseVector.js tries to import 'rbush' from node modules, which of course doesn’t work 🙁

**Comment by ahocevar** [comment]
@not-a-lot `rbush` is a dependency of OpenLayers, which you get when you run `npm install`. I just created this sandbox to verify that importing from `ol/src/` according to the README works fine: https://codesandbox.io/s/vector-layer-forked-jmwtd?file=/main.js

**Comment by not-a-lot** [comment]
> 
> 
> @not-a-lot `rbush` is a dependency of OpenLayers, which you get when you run `npm install`. I just created this sandbox to verify that importing from `ol/src/` according to the README works fine: https://codesandbox.io/s/vector-layer-forked-jmwtd?file=/main.js

Thanks for your answer 🙂 Yes, I understood that’s `rbush` is a dependency of OpenLayers, but I’d like to be able to use OpenLayers as modules without having to use any build tool like Parcel. Is this currently not possible at all?

**Comment by ahocevar** [comment]
That's indeed not possible, as long as our dependencies (like `rbush`) are not published as ES modules.

**Comment by Dreamsorcerer** [comment]
> Thanks for your answer slightly_smiling_face Yes, I understood that `rbush` is a dependency of OpenLayers, but I’d like to be able to use OpenLayers as modules without having to use any build tool like Parcel. Is this currently not possible at all?

Well, if you follow my alterative instructions, then you end up with a built JS file which can just be imported as a module on it's own:
https://github.com/Dreamsorcerer/ol-parcel-es6

That's probably closer to what you (and I) want.
