### ISSUE TITLE
MapBrowserEventHandler needs to be destroyed for listeners to be unregistered

### ISSUE THREAD

**Issue by EvertEt** [openlayers/openlayers#11231]
**Describe the bug**
`MouseWheelZoom.conditionInternal_` throws errors when the map target is null due to the `hasAttribute` check.
I see this is changed on master but I believe this bug will still exist (https://github.com/openlayers/openlayers/commit/2cac6c4f39521470a899f1c6338aa47baea05392#diff-a08a90960184e04e1b7384a480a81d6a).

**To Reproduce**
1. Go to https://codesandbox.io/s/react-openlayers-xni5f?file=/src/App.js which contains a simple map example reloading every 5s and setting the previous map target to null (`myMap.setTarget(null);`)
2. Click on the map to drag but don't release for 5s.
3. Next mouse movements will trigger an error:
![image](https://user-images.githubusercontent.com/9197891/86375238-b44f7580-bc85-11ea-8dd7-8316ae8e971c.png)
![image](https://user-images.githubusercontent.com/9197891/86375720-5c653e80-bc86-11ea-9135-3d6dd37f6f15.png)

What I've found so far is
- Events need a map target or they crash
- Events are not deregisterd without `map.dispose` which propagates to `disposeInternal` of `MapBrowserEventHandler` where it unlistens avoiding the events to be called.

**Expected behavior**
I am not sure which solution is preferable:
- Have events check if they have a target before checking the `hasAttribute`
- Making `map.dispose` needed for destroy (https://github.com/openlayers/openlayers/issues/10856#issuecomment-643601271 seems like it is not needed). I believe this is cleaner to avoid memory leaks everywhere. Could you tell me the reasoning to not make the dispose methods public?

Let me know what you prefer @tschaub

**Comment by ahocevar** [comment]
@EvertEt Thanks for reporting this. Great find, because it is also the reason for the strange behavior reported in https://github.com/openlayers/openlayers/issues/6948#issuecomment-565375694.

The correct solution would be to dispose of the `MapBrowserEventHandler` when the map's target is set to a falsey value in `setTarget()`. And to create a new MapBrowserEventHandler when a HTML element is set as target. This means the code that creates the `MapBrowserEventHandler` instance and registers the `handleMapBrowserEvent` listener should be moved to the `setTarget()` method.

Once that is done, we can also remove what was added with https://github.com/openlayers/openlayers/commit/34dc53812274638ceaa731c932ab5fd2f5139e76. That should make the code there a fair bit easier to understand.

Would you be able to create a pull request @EvertEt?

**Comment by EvertEt** [comment]
Out of curiosity: why is dispose not preferred? I think there might be more leaks due to not using dispose such as the listener for `EventType.CONTEXTMENU`

```js
  disposeInternal() {
    this.mapBrowserEventHandler_.dispose();
    this.viewport_.removeEventListener(EventType.CONTEXTMENU, this.boundHandleBrowserEvent_);
    this.viewport_.removeEventListener(EventType.WHEEL, this.boundHandleBrowserEvent_);
    if (this.handleResize_ !== undefined) {
      removeEventListener(EventType.RESIZE, this.handleResize_, false);
      this.handleResize_ = undefined;
    }
    this.setTarget(null);
    super.disposeInternal();
  }
```

**Comment by ahocevar** [comment]
@EvertEt You are right. But we also want to handle the case where users change the map target, right? `disposeInternal` won't be called in that case. So the best solution is to unregister all those listeners when the target is unset, and register them again when the target is set.

That said, I'm planning to release v6.4 this week. Do you think you'd be able to create a pull request? If not let me know, then I'll take this on.

**Comment by EvertEt** [comment]
I won't have time this week sadly. If you get a chance to take a look at it already, feel free to ping me on the PR

**Comment by EvertEt** [comment]
![image](https://user-images.githubusercontent.com/9197891/87050867-23394b00-c1ff-11ea-8d06-cf52867f07b7.png)
We have another similar error reported in `MouseWheelZoom` which doesn't seem fixed by using map.dispose.
We haven't had time to look into it any further. Just posting this here in case someone else will look at creating a PR
