### ISSUE TITLE
Projections for astronomical data

### ISSUE THREAD

**Issue by caillat** [openlayers/openlayers#11234]
**The context**
We are happy users of OpenLayers for a WEB application displaying (radio)-astronomical data. Here are links to 
give an idea of what the application looks like : 

http://artemix.obspm.fr/fits/visit/?relFITSFilePath=trash/nenufar.fits#

http://artemix.obspm.fr/fits/visit/?relFITSFilePath=2015/2015.1.00274.S/science_goal.uid___A001_X2d8_X361/group.uid___A001_X2d8_X362/member.uid___A001_X2d8_X363/product/calibrated_final_cont.pbcor_blobs.fits

So far we are using extremely basic projection
```
     /*
        ** A pure pixel projection
        */
        this.projection = new ol.proj.Projection({
            code: 'local_image',
            units: 'pixels',
            extent: this.extent,
            worldExtent: [...this.extent]
        });
```
where `this.extent` is defined as follows: 
```
this.extent = [0, 0, width-1, height-1];
```
where `width` and `height` are the dimensions of the image expressed as num of columns and num of rows.

So that there is absolutely no declaration of the projection the metadata provided with the image (FITS format).

**Would it be possible to declare projections commonly used in (radio)-astronomical observations ?**
We would be very interested in having the possibility to declare projection such that `gnomonic` or `orthographic`. Is that possible ? Can they be registered if they do not exist already in the library ? Here is a link to a list of projections declared in a coordinates system widely used in astronomical software, but alas without javascript implementation : 

https://docs.astropy.org/en/stable/wcs/#supported-projections

The obvious interest would be to be able to retrieve the celestial coordinates ( Right Ascension and Declination ) of a point from its pixels coordinates as the mouse moves over the image.

**Comment by mike-000** [comment]
proj4js supports both `ortho`  https://codesandbox.io/s/orthographic-2e8vl and `gnom` projections if you can adapt them for your celestial data.
