### ISSUE TITLE
TypeError: r.handleBrowserEvent is undefined

### ISSUE THREAD

**Issue by Dreamsorcerer** [openlayers/openlayers#11237]
When trying to run a minimal example using the downloaded dist build, I'm getting:
`TypeError: r.handleBrowserEvent is undefined` in PluggableMap.js:148.

My setup is a bit awkward at the moment, as I'm still trying to figure out #11236. But, basically, I have a web component which adds the script tag into a shadow DOM, and then runs:
```
window.setTimeout(() => {
    const pos = ol.proj.fromLonLat([data["vehicle"]["longitude"], data["vehicle"]["latitude"]]);
    ol.Map({
        "target": "map",
        "layers": [new ol.layer.Tile({source: new ol.source.OSM()})],
        "view": new ol.View({"center": pos, "zoom": 20})
    });
}, 1000);
```

After which I get that error.

Running in a recent release of Firefox.

**Comment by jahow** [comment]
Hi,

Looks like you're missing a `new` in front of `ol.Map({...`. This class is supposed to be instanced.

If you encounter other errors, please set up a reproduction case on codepen so people can give you a more thorough answer. Thanks!

**Comment by Dreamsorcerer** [comment]
That was dumb, thanks.
