### ISSUE TITLE
Layer reprojection broken by commit bef4d8a4

### ISSUE THREAD

**Issue by pjsg** [openlayers/openlayers#11238]
**Describe the bug**

I tried to update my app to use the current 'dev' version from npmjs. I found that it introduced rendering problems for the Azimuthal Equal Area projection in areas at the edge of the world (the world is projected into a circle with severe distortion at the edge of the circle). 

If I revert 
```
diff --git a/src/ol/proj/proj4.js b/src/ol/proj/proj4.js
index ca7c17c..f4fb255 100644
--- a/src/ol/proj/proj4.js
+++ b/src/ol/proj/proj4.js
@@ -60,8 +61,18 @@ export function register(proj4) {
           addCoordinateTransforms(
             proj1,
             proj2,
-            transform.forward,
-            transform.inverse
+            createSafeCoordinateTransform(
+              proj1,
+              proj2,
+              transform.forward,
+              transform.inverse
+            ),
+            createSafeCoordinateTransform(
+              proj2,
+              proj1,
+              transform.inverse,
+              transform.forward
+            )
           );
         }
       }
```

then it works correctly again. I'm not sure of what the use of `createSafeCoordinateTransform` is, but it seems to prevent transforms from behaving correctly at the edge of their validity. There are some transforms that repeat in `x` coordinates and I suspect that that is the case that `createSafeCoordinateTransform` handles. However, not all transforms behave like that. The reprojection code makes use of the fact that some points in the reprojected plane (i.e. the canvas) do not map to *any* valid point on the globe.

I can try and put together a jsfiddle if needed....

**Comment by ahocevar** [comment]
Thanks for reporting this @pjsg. Please provide a codesandbox with a minimal example to reproduce the problem.

The use of `createSafeCoordinateTransform` is to clamp source projection points that exceed the destination projection's validity extent to the validity extent, to avoid NaN or Infinity/-Infinity coordinates. That way, proj4 coordinate transforms should behave the same way as built-in transforms. Note that without `global` set to `true` on the OpenLayers projection object, that function should not modify proj4's transform at all.

**Comment by pjsg** [comment]
If you look at https://codesandbox.io/s/dev-ol-canvas-reproj-g99e3?file=/index.js then what you *should* see is a circle (i.e. the globe projected onto Azimuthal Equidistant'. Instead there are lots of nasty spikies:

![image](https://user-images.githubusercontent.com/1508813/86543713-1ced5b00-beef-11ea-8915-6a2e765e337d.png)

If you go back 2 dev versions of ol, then you get this:

![image](https://user-images.githubusercontent.com/1508813/86543724-39899300-beef-11ea-9012-7941b3ae9296.png)

(https://codesandbox.io/s/dev-ol-canvas-reproj-nbwni)

**Comment by mike-000** [comment]
Shouldn't `if (destExtent) {` at https://github.com/openlayers/openlayers/blob/main/src/ol/proj.js#L668 be `if (destProj.canWrapX()) {`?  If the destination is not a global projection is it quite reasonable that a coordinate from global projection is unprojectable in the local projection and it should remain unprojectable.
