### ISSUE TITLE
updateWhileInteracting not working in VectorImageLayer

### ISSUE THREAD

**Issue by yonzathuji** [openlayers/openlayers#11250]
Features in `VectorImageLayer` are not updated when interacting with the map (dragging, zooming etc..).

Steps to reproduce:
1. create a feature and update its coordinate every interval.
2. create a new `VectorSource` and add the `feature` to it.
3. create a new `VectorImageLayer` with `updateWhileInteracting: true` and add the `vectorSource` to it
4. Open the application and start zooming and dragging the map.
5. The feature will only update its coordinates when the map is not interacted with

**Expected behavior**
Like in `VectorLayer`, I expect the feature to update even the map is been interacted with.

```
const source = new VectorSource({});
const layer = new VectorImageLayer({ // bug will not happen if using VectorLayer
    source,
    updateWhileInteracting: true,
    updateWhileAnimating: true,
)};

map.addLayer(layer);

const feature  = new Feature(new Point(randomLocation());
source.addFeature(feature);

setInterval(() => {
    feature.getGeomtry().setCoordinates(randomLocation());
}, 500);

```

**Comment by ahocevar** [comment]
This is a documentation bug. `VectorImage` should not have `updateWhileAnimating` and `updateWhileInteracting` options. These would not make sense here, because `VectorImage` is a special layer type for use cases where vector rendering performance is a concern and visual quality of the output is not.

Would you be able to create a pull request that removes the two options from the JSDoc documentation?

**Comment by yonzathuji** [comment]
Is there any way for the features to update while interacting? 
Like some sort of force rendering.

I have about 1500 features with distinct Text styles (different text and color on each) and the map is really lagging when using VectorLayer

I tried the solutions you wrote over the years in other issues: like using the same style for all features and updating it, but it didn't change the performance.
Even when I'm not updating the features, just having 1500 of them is causing a lag.

I switched to ImageVectorLayer which imporoved the lagging to none, but the no-update while interacting as in issue for me,

**Comment by ahocevar** [comment]
Rendering a new viewport size canvas with every frame (which is what updateWhileAnimating and updateWhileInteracting) would do for an ImageVector layer would be even slower than with a Vector layer.

That said, 1500 features is not much. That should render without noticeable lag. Maybe you're doing something else wrong.

**Comment by yonzathuji** [comment]
I have create a [fiddle](https://codesandbox.io/s/openlayers-example-vfu3t?file=/src/index.js) for you to check it out. I used `uuidv4` to genereate random text and the color is randomly selected between 2 values.

The map is seriously lagging on 1500 feautres.

(It seems like a funny scenario but the actual application is similar to this in its requirements)

**Comment by ahocevar** [comment]
Setting a style on each feature makes the map slow. It is better to use a layer style, like I did in this [fiddle](https://codesandbox.io/s/openlayers-example-k2jop?file=/src/index.js).

Also, what is the reason for setting `updateWhileAnimating` and `updateWhileInteracting` to true in your real use case? In the example you shared, these settings do not change the visual behavior of the map, they only cause unnecessary rendering overhead.

**Comment by yonzathuji** [comment]
> Setting a style on each feature makes the map slow. It is better to use a layer style, like I did in this [fiddle](https://codesandbox.io/s/openlayers-example-k2jop?file=/src/index.js).

As I said, making this change only improved the performance a little. I expect 60fps performance in this scenario.

> Also, what is the reason for setting `updateWhileAnimating` and `updateWhileInteracting` to true in your real use case? In the example you shared, these settings do not change the visual behavior of the map, they only cause unnecessary rendering overhead.

These do not have any affect in this scenario, but they are crucial in my application, since the features will be changing their coordinates and visual properties constantly, and I need to change to be visually seen even when the user is dragging or zooming the map.

**Comment by yonzathuji** [comment]
I think the main cause of the lagging, is the low utilization of the gpu.
I opened [chrome's fps meter](https://superuser.com/questions/1436118/google-chrome-how-to-enable-fps-counter) and I noticed I'm on about 11 fps with **0.2MB** of GPU memory used.

On the other hand, when writing a similar program using CesiumJS, I got about **3MB** GPU memory usage and around 30FPS.

**Comment by ahocevar** [comment]
Cesium uses WebGL for rendering, OpenLayers the Canvas 2D API, which uses the GPU less. And `updateWhileAnimating` and `updateWhileInteracting` causes new render instructions to be created with every render frame, which is done in JavaScript. That explains why the GPU is not utilized more.

That said, for updating the map when feature coordinates changed, there are better ways than setting `updateWhileAnimating` and `updateWhileInteracting` to true: just call `layer.changed()` after updating your feature geometries and properties.

**Comment by yonzathuji** [comment]
So If I want to [use webgl as my renderer](https://stackoverflow.com/questions/45131173/openlayers-how-to-render-vector-layer-in-openlayers-with-webgl) I need to downgrade to OpenLayers 3?

**Comment by ahocevar** [comment]
Since you're just rendering points, you might be able to take advantage of the new `WebGLPoints` layer. You would have to create icons with your texts though, at least until text rendering is available in the `WebGLPoints` renderer. @jahow can tell you more about that.

**Comment by yonzathuji** [comment]
I see [here](https://github.com/openlayers/openlayers/issues/10453) that adding text to a webgl point feature is not possible yet.

So any alternative solution for my performance issue would be great.

**Comment by ahocevar** [comment]
You can create icon images from your texts using the canvas 2d api, and use the images in the WebGLPoints style.

**Comment by yonzathuji** [comment]
Can you please provide an example for how I set the `src` of the image dynamically by the feature?'

Since the `style` property in `WebGLPointsLayer` only receives `LiteralStyle`, I don't see how I can pass arguments there and set
```
symbol: {
     symbolType: SymbolType.IMAGE,
     src: <will be generated by a given feature>
}
```

**Comment by ahocevar** [comment]
@jahow should be able to help you more here. Worst case is you have to pre-generate all images so you can configure the `style` with the `src` for each text you need. But there might be a way to get more dynamic that I do not know of.

**Comment by yonzathuji** [comment]
> That said, for updating the map when feature coordinates changed, there are better ways than setting updateWhileAnimating and updateWhileInteracting to true: just call layer.changed() after updating your feature geometries and properties.

I tried using it but without luck. Could you provide an example?

I tried calling it synchronously after I changed the feature's proper its  
I also tried it by creating a `mapIsMoving` event using the `movestart` and `moveend` event (which worked well)  and called `layer.changed` when it triggered, but without much success.

**Comment by jahow** [comment]
Hi @yonzathuji,

To have a map continously rendering, you can use a loop like this:
```js
function animate() {
  map.render();
  window.requestAnimationFrame(animate);
}
animate();
```

Then if you call `layer.changed()` the changes should appear on the map.

As for using dynamically changing images for your points, this is not really doable with the webgl points layer; you will have to have to use a sprite sheet or similar, i.e. a large image containing all your images, and then have a dynamic expression for the `textureCoord` attribute. See [this example](https://openlayers.org/en/master/examples/icon-sprite-webgl.html) for a reference.

As for having text on your points as well, this is not possible with the webgl layer but you can always have another vector layer using the mainstream renderer to draw the text you want. Not sure how this would work out in terms of performance though.

**Comment by yonzathuji** [comment]
> Then if you call layer.changed() the changes should appear on the map.

Sorry but It didn't work for me...

Can you edit my [moving feature fiddle](https://codesandbox.io/s/openlayers-example-ju1cm?file=/src/index.js) so I see what you mean exactly?

**Comment by yonzathuji** [comment]
> To have a map continously rendering, you can use a loop like this

It didn't work for me.. Could please edit my [moving feature fiddle](https://codesandbox.io/s/openlayers-example-ju1cm?file=/src/index.js:0-1583) so I see what you mean exactly?
The feature should continue changing its location every 500 ms even if the user is dragging the map.

**Comment by jahow** [comment]
Well, I guess you need to set `updateWhileAnimating/Interacting` to true to have it update during a pan...
