### ISSUE TITLE
After the line feature layer label is set along the line layout, part of the text is displayed overlapping

### ISSUE THREAD

**Issue by ChenGuanglin0924** [openlayers/openlayers#11257]
**Describe the bug**
After the line feature layer label is set along the line layout, part of the text is displayed overlapping。

**To Reproduce**
1. Create a line layer
2. Add labels along the line
3. When the curvature of the line segment is large, the labels will overlap
![image](https://user-images.githubusercontent.com/22443356/87008693-ba4dd500-c1f6-11ea-9c56-52757528bcb6.png)

**Expected behavior**
Labels are displayed continuously and do not overlap。

**Solutions**
1.Solve it yourself
2.Provide interface for setting word spacing

**Comment by ahocevar** [comment]
You have several options to change this behaviour. The simplest is setting a lower `maxAngle` of the text style. The default is 45 degrees (`Math.PI / 4`). If you set that e.g. to `Math.PI / 8`, labels will be placed in straighter segments of the line.

Another option is to add letter spacing with a function similar to the one used in [ol-mapbox-style](https://npmjs.com/package/ol-mapbox-style): https://github.com/openlayers/ol-mapbox-style/blob/5872d352ac71ae96aa6d13f3bf832523072f9d36/src/util.js#L46-L61.

**Comment by ChenGuanglin0924** [comment]
Okay, got it, thank you
