### ISSUE TITLE
stroke across edge of tiles will be splited

### ISSUE THREAD

**Issue by geyanku** [openlayers/openlayers#11261]
![image](https://user-images.githubusercontent.com/6949015/87040268-0b73be00-c223-11ea-849d-94136157af53.png)
Line with big strokeWidth will be splited apart while the line cross over the tile edge. Just like the picture above. Who please tell me how to fix it.

**Comment by mike-000** [comment]
Either your have the `renderBuffer` layer option set too small, or more likely the tiles do not have sufficient buffer built in.  If the latter and you are using your own tiles you would need to generate new tiles, but there is no easy fix for third party tilesets created without buffer.

**Comment by geyanku** [comment]
Thanks for your help~ I try to add renderBuffer option，as the code below:
`this.map = new Map({
      target,
      layers: [
        new VectorTileLayer({
          declutter: true,
          source: new VectorTileSource({
            format: new MVT(),
            url: getTileUrl(AGG_TILE_URL, this.baseUrl),
          }),
          style: createAggStyle(),
          renderBuffer: 1000,
        }),
      ],
      view: new View({
        // projection: 'EPSG:4326',
        center: [13524815, 3657979],
        zoom: 16,
        maxZoom: 19,
        minZoom: 4,
      }),
    });`
Doesn't work for me. It happens only if the angel between tile edge and the yellow road is less than 15 deg.

**Comment by ahocevar** [comment]
The `renderBuffer` option won't help here. The default value is `100`, so it would only help if the stroke width of the line in question was more than 100 pixels. So you'll have to fix your tiles.
