### ISSUE TITLE
Line placement labels don't always adjust to rotation since 6.1.0

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11264]
**Describe the bug**
**To Reproduce**
See the example https://codepen.io/mike-000/pen/RwrryMv in https://github.com/openlayers/ol-mapbox-style/issues/279  Rotate the view and the street labels do not flip as they pass vertical.  It happens regardless of the declutter setting.  But change the OpenLayers build to 6.1.0 or earlier and repeat it works as expected, 6.1.1 or later is does not.  The version of olms does not affect it, and the style json works as expected with Mapbox GL, so it looks like an OpenLayers regression under some conditions as the Street Labels example works correctly in all releases.

**Expected behavior**
Line placement street labels should flip as the view is rotated so the text is not inverted.

**Comment by ahocevar** [comment]
Thanks for reporting this @mike-000. I can reproduce this issue also with https://openlayers.org/en/latest/examples/mapbox-style.html. Looks like this only affects vector tile layers, not vector layers. Because https://openlayers.org/en/latest/examples/street-labels.html works fine. Are you able to find the commit that broke this with `git bisect`?

**Comment by mike-000** [comment]
It was first broken in 6.1.0-dev.1572632106392 which corresponds to #10239

Incidentally the Mapbox Style example only works cleanly in the examples template because the `ol.css` is preloaded.  When imported as shown in the code the `.ol-rotate` change in the html is partly reset so left, bottom, top and right are all set and the control covers most of the screen (which can be demonstrated by opening in codesandbox and rotating the view).  It may need a solution similar to the Advanced View Positioning example.

**Comment by ahocevar** [comment]
Thanks for the investigation @mike-000 , I should be able to fix it from here. The template problem is not an issue any more, because that example now uses the standard template.

**Comment by mike-000** [comment]
It only affects the example when used outside the template and is another occurrence of the issue in #9911  I'll start a new issue as other examples have similar problems.
