### ISSUE TITLE
ol version in js code ?

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#11260]
Hi
Sorry i can not find the version in the js code. Miss i something or is a choice of the dev team?
For us in a cms context where ol is in a directory :  lib/ol/ol.js   is very useful to know  quickly which version is running and to process to the upgrade ...

**Describe the solution you'd like**
just a comment with the version on the top of the js ?

Thank for your advice ...

**Comment by ahocevar** [comment]
If you are using the [ol package](https://npmjs.com/package/ol), which we recommend, you can easily see your version by running

    npm ls ol

**Comment by jipexu** [comment]
@ahocevar 
thanks 
but unfortunatly until now we use as a normal script call ... ( i know this is not the best way ...) ...
