### ISSUE TITLE
OpenLayers is appending canvas tags to the bottom of the page body on specific events (One more time)

### ISSUE THREAD

**Issue by HoudGIS** [openlayers/openlayers#11266]
The bug has already been already reported in  #11128 and maybe fixed, but now it is back in ol@6.3.1 installed with "npm install ol".
You can also test it live on Openlayers example page after selecting a feature : https://openlayers.org/en/latest/examples/vector-tile-selection.html?q=select

**Comment by mike-000** [comment]
There hasn't been a full release since the fix, but it is fixed in the dev version https://openlayers.org/en/main/examples/vector-tile-selection.html
