### ISSUE TITLE
Zoom and rotation bug on Ipad in Safari

### ISSUE THREAD

**Issue by vizet-raa** [openlayers/openlayers#11278]
At first i thought we had a problem with our openlayers code which made iOS users map turn really slow and disabled the zoom and rotation functionality when pinch zooming for a while. But then i realized the same problem happened when trying the openlayers examples on an Ipad. It's not always happening right away but it's easy to trigger the problem within a few minutes of zooming/rotating. 

1. Go to https://openlayers.org/en/latest/examples/drag-rotate-and-zoom.html with an Ipad (I'm using an Ipad Air with iOS version 12.4.7)
2. Zoom in closer (Not sure it's necessary though)
3. Pinch zoom and rotate the map for a while until it flickers and the map won't respond to rotation or zoom gestures anymore. It will also be very slow to move sideways.

**Comment by vizet-raa** [comment]
Update: It seems like downgrading to v6.2.1 solved the problem for now.

**Comment by ahocevar** [comment]
You mentioned you are using iOS 12, which does not have Pointer Events enabled by default. So the problem you are seeing might have to do with the pointer events polyfill that v6.3.1 uses. Can you please try if you are getting the same behavior when you enable pointer events under Settings - Safari - Advanced - Experimental features - Pointer Events?

**Comment by tuscland** [comment]
Hello,

We have a Cordova app that uses OpenLayers 6.4.3. Our customers on iOS 12 are experiencing the same issue are described above with the slight difference that panning randomly stops working after a short while.

We have been able to reproduce the issue on the iOS 12 Simulator with an iPad Air (3rd gen).

Unfortunately, activating Point Events in Safari's Experimental features. Actually, it seems to do nothing. We tried OL 6.4.3 without the elm-pep polyfill, and the map was not moving at all.

We would be happy to help by giving more feedback if needed.

Camille

**Comment by ahocevar** [comment]
Thanks for your report @tuscland. To narrow down this issue, are you able to test on an iOS 13 device and see if the issue occurs there too?

**Comment by tuscland** [comment]
I should have been more precise: we have been testing OL 6.3.1 for about three months on iOS 13 without noticing any issue. Then we began to gradually deploy the update to our application.

A couple of customer reported this issue, so we began investigating. We found both of them were using devices running iOS 12. With the hope of finding a trivial solution, we decided to upgrade OL to 6.4.3.

**Comment by ahocevar** [comment]
Since OpenLayers 6.4 does not use a pointer events polyfill by default any more, you might have more luck with the more verbose [@openlayers/pepjs](https://npmjs.com/package/@openlayers/pepjs) polyfill.

I don't think a Cordova app will respect settings you make under Safari - Experimental features.

**Comment by tuscland** [comment]
Thank you for the tip!
I tried with elm-pep but the problem was still occurring. Now tried with @openlayers/pepjs and I have not been able to reproduce the issue in the simulator! Will try on a real device tomorrow.

**Comment by edellucien** [comment]
> Thank you for the tip!
> I tried with elm-pep but the problem was still occurring. Now tried with @openlayers/pepjs and I have not been able to reproduce the issue in the simulator! Will try on a real device tomorrow.

Did you manage to solve this with @openlayers/pepjs finally? please?

**Comment by tuscland** [comment]
Yes, thank you!
It worked as intended.

**Comment by edellucien** [comment]
> Yes, thank you!
> It worked as intended.

Could you by any chance share pseudo code on how did you integrate it?
Simply importing '@openlayers/pepjs' for us didn't solve pointer event problem on Ipad unfortunately.

**Comment by tuscland** [comment]
Yes we `import '@openlayers/pepjs';` in the file that defines the view.

**Comment by bugraaydin1** [comment]
`import "elm-pep"` solve the issue for me. (for me "pepjs" does not have any effect)
