### ISSUE TITLE
New release? More frequently going forward?

### ISSUE THREAD

**Issue by mohawk2** [openlayers/openlayers#11272]
**Is your feature request related to a problem? Please describe.**
This isn't really a problem as such, there isn't a template for this as it's a slightly "meta" question.

**Describe the solution you'd like**
I'd like to see more frequent releases. I see some "dependabot" activity was merged the last few days, and I'm assuming that's stuff that is worth getting out there. More immediately, I'd like #11224 released because then I can update the OL code in https://github.com/metacpan/metacpan-web and close the last security issue identified by CodeQL!

**Comment by ahocevar** [comment]
You can always get the latest when you `npm install ol@dev`, and I'm planning to release v6.4 within the next few days.

**Comment by tschaub** [comment]
@mohawk2 - note that the [dependabot activity](https://github.com/openlayers/openlayers/issues?q=label%3Adependencies+is%3Aclosed) on this repo is almost exclusively (maybe even exclusively) about development dependencies.  So these are changes that don’t make their way into the release.

As @ahocevar mentions, you can always install the latest passing commit by using the `ol@dev` tag.  If you wanted to try the most recent code in https://github.com/metacpan/metacpan-web/pull/2329, you could use the [`ol@6.3.2-dev.1594657169224`](https://www.npmjs.com/package/ol/v/6.3.2-dev.1594657169224) version (find the most recent release on the [versions tab](https://www.npmjs.com/package/ol?activeTab=versions)).  There is a bit more work that goes into the `latest`-tagged releases, but the `dev` releases pass the same tests.

**Comment by mohawk2** [comment]
Thanks for the detailed response. I'd prefer not to be using the dev version for https://metacpan.org/, and to wait for the next release :-)

**Comment by mohawk2** [comment]
There has certainly been a storm of releases recently. Please keep that up! :-D
