### ISSUE TITLE
'© OpenStreetMap contributors' out of place

### ISSUE THREAD

**Issue by ofir5551** [openlayers/openlayers#11279]
I am currently implementing ol's OpenSourceMap in my Angular app and the '© OpenStreetMap contributors' copyright message is misbehaving - it is awkwardly located in the top left corner of the map. (https://ibb.co/vzQN0Gb)

This is how I initialized the map in my map.component.ts file. (https://pastebin.com/4mHfhGfX)

I'm using Bootstrap 4's grid positioning in my project if that's relevant.

Thanks

**Comment by mike-000** [comment]
None of your controls are correctly styled.  You need to include the ol.css.

**Comment by ofir5551** [comment]
I apologize for the ignorance - but what do you mean by 'controls'?

Anyway, here is a link to the map component on my project. (https://github.com/ofir5551/Countries-App/tree/master/src/app/country-details/osm-view)

**Comment by mike-000** [comment]
The zoom in/out buttons, etc.  Try adding
 `import 'ol/ol.css';` 
as in the Openlayers examples.

**Comment by ofir5551** [comment]
I have tried adding "import 'ol/ol.css';" to my .ts file and the problem still persists.

**Comment by ofir5551** [comment]
> The zoom in/out buttons, etc. Try adding
> `import 'ol/ol.css';`
> as in the Openlayers examples.

This has indeed solved my issue. Thanks a lot.
