### ISSUE TITLE
How to get features in popup?

### ISSUE THREAD

**Issue by Spatialghost** [openlayers/openlayers#11276]
Hi. I developing application with Openlayers 6.3.1., and i need to display features from vector layer in popup. How can i do this?

**Comment by M393** [comment]
Have you looked at one of the examples?
https://openlayers.org/en/latest/examples/icon.html

**Comment by Spatialghost** [comment]
> 
> 
> Have you looked at one of the examples?
> https://openlayers.org/en/latest/examples/icon.html

Yes, it's working, but i need to get all object features.

**Comment by mike-000** [comment]
For all features at a click populate the popup content similar to the `showInfo` function in  https://openlayers.org/en/latest/examples/vector-tile-info.html

**Comment by Spatialghost** [comment]
> 
> 
> For all features at a click populate the popup content similar to the `showInfo` function in https://openlayers.org/en/latest/examples/vector-tile-info.html

Thanks! Its working!

**Comment by Spatialghost** [comment]
> 
> 
> For all features at a click populate the popup content similar to the `showInfo` function in https://openlayers.org/en/latest/examples/vector-tile-info.html

I have one else question, how to do this for few layers?

**Comment by Spatialghost** [comment]
Solved!
