### ISSUE TITLE
Changing background color in full screen mode

### ISSUE THREAD

**Issue by Spatialghost** [openlayers/openlayers#11280]
Hi. We are developing application with full screen mode as in example https://openlayers.org/en/latest/examples/full-screen.html . We are not using online base maps. We are found out, wheh application in full screen mode, application background changing from white to black colour. What could be reason color changing, or is it API bug?
![Screenshot_1](https://user-images.githubusercontent.com/36438927/87512715-f4a0f180-c690-11ea-8b98-4af98b52a02e.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/36438927/87512731-f9fe3c00-c690-11ea-8145-455a5254c227.jpg)

**Comment by mike-000** [comment]
By default the map div is transparent so you are seeing the browser's default background in both cases.  You just need set something in the css, e.g.

      .map {
        background: white;
      }
