### ISSUE TITLE
Layer filter is not working for map.forEachLayerAtPixel() function

### ISSUE THREAD

**Issue by vishnunossam** [openlayers/openlayers#11285]
Layer filter function is not working in Open Layers 6 is not working where as the same is working in Open Layers 3

**Comment by mike-000** [comment]
It is working for me, but as noted in the documentation to distinguish layers used in `forEachLayerAtPixel` each layer must now be constructed with a unique `className` property.

**Comment by vishnunossam** [comment]
Hi mike,
Can you please give me some code snippets how i can filter the layers
Regards,
Vishnu

**Comment by mike-000** [comment]
It is used in https://openlayers.org/en/main/examples/disable-image-smoothing.html

**Comment by vishnunossam** [comment]
mike its working, Thank you very much :)
