### ISSUE TITLE
How to switch basemaps in OL 6.3.1?

### ISSUE THREAD

**Issue by Spatialghost** [openlayers/openlayers#11307]
Hi, i working for base maps switching in OpenLayers 6.3.1. but radio buttons not workings in HTML code. I use clear layer groups and i need solution without outdoor extension, how to make it?
My code:
`<div id="layertree">
      <ul> 
            <label id="layer0" value="layer0">
            	Base maps
            </label>
        <ul>
                <label type="radio" id="layer01">
                  <input id="layer01" type="radio" name="Base maps" value="layer01" checked/>Roadmap
                </label><br>
                <label type="radio" id="layer02">
                  <input id="layer02" type="radio" name="Base maps" value="layer02"/>Alter roadmap
                </label><br>
                <label type="radio" id="layer03">
                  <input id="layer03" type="radio" name="Base maps" value="layer03"/>Terrain
                </label><br>
                <label type="radio" id="layer04">
                  <input id="layer04" type="radio" name="Base maps" value="layer04"/>Satellite
                </label><br>
                <label type="radio" id="layer05">
                  <input id="layer05" type="radio" name="Base maps" value="layer05"/>Hybrid
                </label><br>
                <label type="radio" id="layer06">
                  <input id="layer06" type="radio" name="Base maps" value="layer06"/>DEM
                </label>
        </ul>`
![Screenshot_5](https://user-images.githubusercontent.com/36438927/88177690-bb452480-cc42-11ea-8012-a683c365f07f.jpg)

**Comment by jipexu** [comment]
Hi
difficult to help there ... this html alone will not do something ...
you can use
https://github.com/walkermatt/ol-layerswitcher

**Comment by mike-000** [comment]
https://openlayers.org/en/latest/examples/bing-maps.html has an example using an HTML Select.  Radio buttons can do the same but the javascript is slightly more complex  https://codesandbox.io/s/bing-maps-fv3l5
