### ISSUE TITLE
Drag and Drop Interaction passing file content as ArrayBuffer to support custom formats

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11301]
**Is your feature request related to a problem? Please describe.**
Allow custom formats requiring ArrayBuffer (e.g. KMZ, or zipped SHP + DBF) to be integrated in the sequence of formats for the Drag and Drop interaction.

**Describe the solution you'd like**
This would require the interaction (either optionally or by default) to pass an ArrayBuffer to the readFeatures methods, and for formats which support String to check for ArrayBuffer and decode it.

**Comment by mike-000** [comment]
This can be done entirely in the interaction by calling each format's getType() method.  Developers of custom formats may need to override the inherited getType() so can it be documented in the API?  It would also be useful if the interaction could take constructed formats as well as constructors where for KML, WFS, GML, etc. options may need to be set.

**Comment by MukeZ** [comment]
In my case I need to drop a shape format, 
This change [#11300 ](https://github.com/openlayers/openlayers/pull/11300) made it only can get data from addfeatures event with certain formats.

**Comment by mike-000** [comment]
@MukeZ Before #11300 It was incorrectly firing the addfeatures event when it had no features.  Are you using a custom format where getFeatures() is asynchronous?  If you are parsing from text or an array it should be possible to do it synchronously (but many third party shapefile parsers are asynchronous).

**Comment by MukeZ** [comment]
@mike-000 Sorry for the delayed response, 
I just use ` dragAndDropInteraction.on('addfeatures', function (event) {})` to listen the event, then if it is a shape file, I will use a third party shapefile parser to do something, but I can't get the shp format in the event after [#11300 ](https://github.com/openlayers/openlayers/pull/11300), I think it only accepts formats in `formatConstructors`

**Comment by mike-000** [comment]
The documents describes `addfeatures` as "Triggered when features are added" so I would not expect it to fire without features, and if it does the application code would need to handle no features instead of throwing an error (and the event should have a more appropriate name)

You could define your own format.  Simple example here https://codesandbox.io/s/nameless-star-8i9w3?file=/main.js uses shp2geojson (there are probably better parsers available but I used that because it reads buffer input synchronously) to parse zipped shp then creates features from the geojson.  Download zipped shp data from https://www.nhc.noaa.gov/gis/ to test.  Most of the codesandbox consists of the drag and drop code patched to handle arraybuffer as well as text.

**Comment by MukeZ** [comment]
OK I see,  the shp2geojson only work with the zip file, I use [shapefile](https://www.npmjs.com/package/shapefile) can work with the shp type file, but it will use path to open file, which I used to catch it from event

**Comment by mike-000** [comment]
Sources and formats needing multiple urls would not fit easily into the current source and format design.

Are you using the Drag and Drop interaction for other formats?  If so having a file dropped but no features parsed might still be useful.  But if not it would be more efficient to add a your own listener in javascript (and it could also work alongside the current Drag and Drop interaction):

      map.getViewport().addEventListener('dragover', function(event) {
        event.preventDefault();
      });

      map.getViewport().addEventListener('drop', function(event) {
        event.preventDefault();
        const files = event.dataTransfer.files;
        for (let i = 0, ii = files.length; i < ii; ++i) {
          const file = files.item(i);
          ...

        }
      });

**Comment by MukeZ** [comment]
Thanks, I do use the Drag and Drop interaction for other formats, and add a own listener to get shape type can resolve my issue.
