### ISSUE TITLE
Style Expression Operator 'in'

### ISSUE THREAD

**Issue by RydingM** [openlayers/openlayers#11308]
Trying to use an array variable in the literal style and for filtering what to be able to check a features property is a value within the variable array. I couldn't see any operator that would allow me to this currently. I had a quick go at trying to add it into my local, following mapbox documentation ( https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#in ), but ran into issues. 

It would be great to see this as an option for the literal style.

**Comment by Pipoupi** [comment]
Did you find a way to do it? I'd like to implement a search box allowing multiple requests, and I can't find a way to perform it.

**Comment by RydingM** [comment]
> Did you find a way to do it? I'd like to implement a search box allowing multiple requests, and I can't find a way to perform it.

After trying for a couple of hours I was unsuccessful, due to my time constraints I ended up having to work around the issue using an inefficient way of filtering out the points from the display (especially when there's a lot of points). 

The workaround I ended up doing for the time being was adding a new property to the features called "show" which is a boolean and added the logic for if they should be shown in the literal style based off this. To alter the display I would then loop through all the features and change the property "show" to true or false.

**Comment by RydingM** [comment]
> Did you find a way to do it? I'd like to implement a search box allowing multiple requests, and I can't find a way to perform it.

I didn't manage to get this functionality into the expressions and due to time constraints I wasn't able to continue with it. I just used a workaround which isn't great as it involves updating the properties on the features called "show" that is boolean and have logic in the style if it should be displayed. But I have seen from other issue posts that updating the features causes a full rebuild of the buffers.
