### ISSUE TITLE
hitTolerance in meters

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#11314]
In ol.interaction.Select, how can we have the hitTolerance in other than pixels, for example in meters.

**Comment by mike-000** [comment]
You can calculate the pixels required from the resolution, and update as the resolution changes:

map.getView().on('change:resolution', function() {
  select.setHitTolerance(toleranceInMeters / map.getView().getResolution());
});

e.g. select a country by clicking within 100km of its border https://codesandbox.io/s/select-features-v3cx7
