### ISSUE TITLE
Using globalCompositeOperation to combine layers using 6.*

### ISSUE THREAD

**Issue by kevinstadler** [openlayers/openlayers#11316]
I am trying to upgrade a project from OL 5, in which I successfully used the following `precompose` strategy to visually combine data from different layers:

```
const withCompositeOperation = (layer, operation) => {
  layer.on("precompose", (e) => { e.context.globalCompositeOperation = operation; });
  return layer;
}

this.map = new Map({
  layers: [
    withCompositeOperation(transparentMonochromeRasterLayer, "source-over"),
    withCompositeOperation(monochromeVectorLayer, "source-over"),
    withCompositeOperation(colorationVectorLayer, "source-in"),
    withCompositeOperation(backgroundLayer, "destination-over"),
  ],
  ...
});
```

What you end up with is a background layer with both raster and vector objects displayed on top, where the color of the objects is controlled by yet another vector layer (whose source can be dynamically swapped in and out, so the coloration can't just be trivially applied to the underlying data sets).

I understand that the `precompose` event has been replaced by `prerender`, but using `prerender` instead does not give the desired result because every layer is now rendered to its own canvas, and the individual layer canvases appear to get combined using `source-over` by default.

My question: Is there a way in OL 6.* to control the `globalCompositeOperation` that is applied when the *already individually-rendered* layers get combined?

I've seen the workaround in https://github.com/openlayers/openlayers/issues/10838#issuecomment-602853079 suggesting that the (in my case coloration) information could be applied by manually rendering those features in the `postrender` of the layer that I want colored, but seeing as there will be at least two such layers (one raster one vector) this would mean that all of these features would needlessly get rendered at least twice...

**Comment by mike-000** [comment]
You should not rely on layers being combined.  For example, if you rotate the view the raster and vector layers will be separated (for consistent behaviour you can force layers to have their own canvas by specifying a unique className in each constructor).  Setting the layers zIndex and/or position in the layers collection will avoid needing to use destination-over.

**Comment by kevinstadler** [comment]
> You should not rely on layers being combined. For example, if you rotate the view the raster and vector layers will be separated

I'm not sure I understand what you mean, clearly any change to the viewport affects the content of all layers in the same way? The layer-compositing effect that I achieved in OL 5.* with the code above is stable even through fast viewport manipulations, or what do you mean by 'separated'?

I have attempted the alternative approach of rendering the coloration features in the raster layer's `postrender` (as demonstrated here: https://codepen.io/mike-000/pen/xxGygBP), only I've got to use `getFeaturesInExtent()` to get the vector features from my `ol/source/VectorTile`:

```
    rasterTileLayer.on('postrender', (e) => {
      e.context.globalCompositeOperation = 'source-in';
      const vectorContext = getVectorContext(e);
      vectorTileSource.getFeaturesInExtent(view.calculateExtent()).forEach((f) => {
        vectorContext.drawFeature(f, style);
      });
      e.context.globalCompositeOperation = 'source-over';
    });
```

Two issues:
1. For some reason swapping the VectorSource for a VectorTileSource works fine with all compositeOperations that I've tested (like the default `source-over`) but not `source-in`. Swapping the `clipLayer` with a `VectorTile` one in your codepen example also simply renders nothing when the compositeOperation is `source-in` but works fine with other ones which depend on having access to the existing canvas content (such as `multiply`), so this seems to be a reproducible bug.
2. Because I'm trying to add a semi-transparent overlay there is the additional problem that I now have to do the clipping of the vector tiles myself, which was previously taken care of by the `VectorTileLayer`, so this is either way not the most elegant approach...

> for consistent behaviour you can force layers to have their own canvas by specifying a unique className in each constructor

Aha that is interesting, from the docs it sounded like every layer is rendered to its own canvas either way, so I was a bit confused why I only ever saw one canvas in the DOM, but this makes more sense now.

But so if I am reading the DOM correctly then all adjacent layers which do not have their individual `className`s actually all still get rendered to one canvas, which appears within the div of `class="ol-layer"`, correct? If adjacent layers are (in some cases) still drawn to the same canvas, shouldn't it still be possible to change a layer's `globalCompositeOperation` relative to the layers that have already been written, as used to be possible with `precompose`? So would it not be possible (and in fact meaningful) to add this hook again?

**Comment by mike-000** [comment]
Image layer canvases are rotated with the view, while vector layer features are rendered on an unrotated canvas, so they will never use a single canvas if there is any rotation, but with no rotation and the same className they may be combined.  That can be seen by rotating the view in https://openlayers.org/en/latest/examples/modify-features.html  To guarantee the same behaviour at all times each layer type should have its own className.

clipLayer as used in the example works only with a single feature or overlapping features.  If you wanted to clip around a group of countries you would need to generate a single multipolygon from their geometries, which would be difficult when features are spread across multiple vector tiles.

**Comment by ahocevar** [comment]
Worth noting that setting a `className` for the layer should **only** be done in very specific cases, e.g. when using canvas operations. In other cases, performance will suffer because combining multiple layers into fewer canvases is an important optimization.

**Comment by kevinstadler** [comment]
> Image layer canvases are rotated with the view, while vector layer features are rendered on an unrotated canvas, so they will never use a single canvas if there is any rotation, but with no rotation and the same className they may be combined.

In my case I have a `TileLayer` and a `VectorTileLayer` though, which don't appear to be split into separate canvas elements as far as I can see, even with a rotated view (I've tried with all three VectorTile `renderMode`s in case that makes a difference)?

> clipLayer as used in the example works only with a single feature or overlapping features. If you wanted to clip around a group of countries you would need to generate a single multipolygon from their geometries, which would be difficult when features are spread across multiple vector tiles.

True indeed, and it also wouldn't work since my polygons are not just used for clipping but all have different colors/styles that affect the compositing.

So I tried out the opposite approach (super-imposing the monochrome `TileLayer` in the `postrender` of the `VectorTileLayer` instead of the other way around), but when I reuse the high-level `CanvasTileLayerRenderer` to do the rendering it just overwrites the entire canvas...seems ridiculous that I would have to be stuck with OL5 because of this....


@ahocevar how is the (optimized) way in which multiple layers are combined onto the same canvas different from the way layers were composited in OL5? Like would it still be possible to change the compositeOperation that is applied when one layer gets composed onto another, or do all individual layer-renderers actually re-use the same context now (so that nothing except `source-over` will meaningfully work)?

**Comment by mike-000** [comment]
Strangely if a globalCompositeOperation is set prerender it is not reset which can be confirmed by checking the postrender event.  But in OL5 the effect of the operation can be seen https://codesandbox.io/s/trusting-framework-1pjs1  while in OL6 it has no effect https://codesandbox.io/s/beautiful-brook-yvvp7  (in this example a postrender or postcompose overlay operation would achieve the same effect in both versions)

**Comment by kevinstadler** [comment]
Here is the map project in question, still running on 5.3.3 because the same compositing is not possible with OL6: https://thiswasyouridea.com/imagined-communities/

If you look at the layerswitcher on the right, it's the 'coloration' layers which should be `source-in`ned over the base layers (to add color), before the background layer is `destination-over`ed in the last step.

@mike-000 could you please explain the OL6 behaviour
> the background of tile layers is being reset, something which is not done for vector layers (reducing the opacity to 0.99 is a workaround).

a bit more? Which background is being reset, the one of the canvas? By changing the opacity, can I make vector layer backgrounds reset as well, or could I *stop* tile layer backgrounds from resetting (which is what I am trying to achieve here I suppose)?

**Comment by mike-000** [comment]
In OpenLayers 5 you could use hard-light with a black or dark gray background to intensify colours https://codesandbox.io/s/strange-maxwell-0r6p5?file=/main.js

In OpenLayers 6 that does not work with an opaque layer as the background is clipped before tiles are rendered https://github.com/openlayers/openlayers/blob/main/src/ol/renderer/canvas/TileLayer.js#L323 although the same effect can be obtained using a postrender overlay https://codesandbox.io/s/cool-kapitsa-pgi6t?file=/main.js 

The same applies with vector tile layers.  While it is common practice to set the map div to the background of a vector tile stylesheet (as ol-mapbox-style does) that is not useful if you have two layers with a layer switcher.  Setting the layer canvas background on the layer prerender event does not work with opaque layers, but using destination-over postrender does.
