### ISSUE TITLE
ol.source.WMTS can not setStyle

### ISSUE THREAD

**Issue by sunday60004** [openlayers/openlayers#11312]
I need to update the ”style“ parameter，but  no method provided，I use “tileLoadFunction” method，as a result, the style parameter was not replaced successfully

![image](https://user-images.githubusercontent.com/28419917/88265729-957e5500-cd00-11ea-9141-ea9a390c46e8.png)

**Comment by mike-000** [comment]
It can be updated if you specify it as a dimension in the source constructor

replace

`  style: 'default',`

with

`  dimensions: {style: 'default'},`

Then you can update using

`  source.updateDimensions({style: 'defaultii'});`
