### ISSUE TITLE
draw circle without useGeographic()

### ISSUE THREAD

**Issue by wanglongbiao** [openlayers/openlayers#11331]
Hi, I want to render the same effect as in this project without useGeographic(). Is there any way? Thanks!!

[draw-and-modify-features](https://codesandbox.io/s/draw-and-modify-features-g3n58?file=/index.js:523-539)

![微信截图_20200727171809](https://user-images.githubusercontent.com/7327187/88526184-31c09880-d02e-11ea-91ff-341f07c59b36.png)

**Comment by mike-000** [comment]
That was produced to demonstrate a bug where the modify interaction was acting in the wrong place (on a distorted ellipse whose y to x axis ratio increases with latitude).  How would that shape be useful?  For ways to draw a true ellipse see #9847

**Comment by wanglongbiao** [comment]
> That was produced to demonstrate a bug where the modify interaction was acting in the wrong place (on a distorted ellipse whose y to x axis ratio increases with latitude).
> 
> ![image](https://user-images.githubusercontent.com/49240900/88539008-4d18ad00-d008-11ea-86a8-fb3c6a984914.png)
> 
> How would that shape be useful?
> 
> For ways to draw a true ellipse see #9847

Hi mike-000, thank you for your relay, we drew a circle on the map, and in the backend we filtered the objects that weren't in the circle by radius.
But a circle drawn as a radius(espg:3857) on a map should actually correspond to an ellipse(espg:4326).
Now some of the targets are outside of the circle.

**Comment by wanglongbiao** [comment]
With `useGeographic()`, I can get the result I want(the green one), the ellipse rendered with some radius.
I want to know, if I don't use this function, how do I write it?

![微信截图_20200728141008](https://user-images.githubusercontent.com/7327187/88626145-b36eff80-d0dc-11ea-855f-4558f080c715.png)

Here is my test code.
```js

import "ol/ol.css";
import Map from "ol/Map";
import View from "ol/View";
import { Draw, Modify } from "ol/interaction";
import { Tile as TileLayer, Vector as VectorLayer } from "ol/layer";
import { OSM, Vector as VectorSource } from "ol/source";
import { Circle as CircleStyle, Fill, Stroke, Style } from "ol/style";
import { useGeographic, toLonLat } from "ol/proj";
import { fromCircle } from "ol/geom/Polygon";
import { fromLonLat } from 'ol/proj';
import { Circle, Point, LineString } from "ol/geom";
import { Feature } from "ol";
useGeographic();
var raster = new TileLayer({
    source: new OSM()
});

var source = new VectorSource();
var vector = new VectorLayer({
    source: source,
});

var source2 = new VectorSource();
var vector2 = new VectorLayer({
    source: source2,
    style: new Style({
        stroke: new Stroke({
            color: "green",
            width: 1
        })
    })
});

var map = new Map({
    layers: [raster, vector, vector2],
    target: "map",
    view: new View({
        center: [120, 38],
        zoom: 8
    })
});

source.addFeature(new Feature(new Point([120, 38])));
// add a line
source.addFeature(new Feature(new LineString([[120, 38], [120, 39]])));
// add a circle
source.addFeature(new Feature(new Circle([120, 38], 1)));
source2.addFeature(new Feature(fromCircle(new Circle([120, 38], 1), 128)));

```

**Comment by mike-000** [comment]
You would need to transform an EPSG:3857 circle to EPSG:4326, convert it to a polygon then transform it back to view projection

```
      var poly = fromCircle(
        geom.transform(map.getView().getProjection(), "EPSG:4326"),
        128
      ).transform("EPSG:4326", map.getView().getProjection());

```
https://codesandbox.io/s/draw-and-modify-features-9po2u

**Comment by wanglongbiao** [comment]
> You would need to transform an EPSG:3857 circle to EPSG:4326, convert it to a polygon then transform it back to view projection
> 
> ```
>       var poly = fromCircle(
>         geom.transform(map.getView().getProjection(), "EPSG:4326"),
>         128
>       ).transform("EPSG:4326", map.getView().getProjection());
> ```
> 
> https://codesandbox.io/s/draw-and-modify-features-9po2u

Thank you, mike-000!! It works perfect!
