### ISSUE TITLE
6.4.0 pointermove performance

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#11333]
Performance of pointermove event is much slower than in 6.3.1.

Example with 1000 features with non cached styles:
6.4.0.
https://codesandbox.io/s/prod-fast-hh1zd?file=/main.js:1438-1449
![640](https://user-images.githubusercontent.com/3100059/88535094-a6cda700-d009-11ea-826b-093126e3438a.gif)

6.3.1.
https://codesandbox.io/s/dazzling-varahamihira-fmzkd?file=/main.js
![631](https://user-images.githubusercontent.com/3100059/88535101-aa612e00-d009-11ea-9c84-2cc95cb310c5.gif)

It affects many operations like zoom, panning etc in my app. It's not so visible in examples above but you can see it on cursor. The cursor change in 6.3.1 is super fast but the change in 6.4.0 is much slower.

**Comment by ahocevar** [comment]
As far as I can tell, #11277 broke hit detection for regular shapes on Retina devices, i.e. the hit detection shapes are too big when the pixel ratio is > 1.

@sbrunner, can you take a look at this?

**Comment by ahocevar** [comment]
I just submitted #11336 to fix this.

**Comment by MichalK6677** [comment]
There is still the same issue even in 6.4.2.

Here is the same example with 6.4.2.
https://codesandbox.io/s/green-brook-05wg9?file=/main.js

**Comment by ahocevar** [comment]
Thanks for sharing your findings @MichalK6677. I have reopened the issues and will do a `git bisect` to see what caused this performance drop.

As far as I can tell, only Chrome is affected by the performance drop. Am I right?

**Comment by ahocevar** [comment]
This problem was introduced by #11148, and I do see how it can be fixed. Hold on, I should be able to provide a fix in a few days, maybe later today already.
