### ISSUE TITLE
ScaleBar on v6.4.0

### ISSUE THREAD

**Issue by ldv-dev** [openlayers/openlayers#11349]
**Describe the bug**
The numeric value of the ScaleBar may not be correct. 1 : xxxxxxxx

**To Reproduce**
The new ScaleBar allows the use of dynamic dpi values which should be great (didn't test it enough) and uses ol.proj.getPointResolution() to correct the ScaleBar when we are away from projection center (EPSG:3857), both in ScaleBar WIDTH and Text value.

Shouldn't it correct the WIDTH of the bar only?

In my testing i created 2 maps, 1 with zoom levels other with resolutions[] based on rounded scale values (1:10000, 1:5000, 1:2000, ...), in both maps when drag the map without zooming, the ScaleBar updates based on the distance from projection center, but my view resolution keeps the same (as intended i think).

If i am on a resolution corresponding to ex: 1:100000 my ScaleBar should give me 1:100000 (at projection center) and as i drag the map or move away from projection center the ScaleBar WIDTH should update but not the text (i think).

All this because i MUST use a Scale based Map so i can make sure what i see is on a fixed scale value in other to analyze and export data.

Am i too off on this issue?

Thanks

**Comment by mike-000** [comment]
I think that should be an option.  If you are using a map of a small part of the world most people would want the scale for that region, not thousands of km away at the equator, and when printing they would always want the paper to real world ratio.

**Comment by ldv-dev** [comment]
@mike-000 now you got me even confused.

i do want the scale for my small region, using a world wide projection like 3857.

1) the new ol.proj.getPointResolution() should address that right? compensating for the distance from equator and it looks ok...


Here it goes a crazy idea:

In the new print-to-scale example the new resolution to zoomIN takes in consideration dpi/scale/centerMapPoint.

As map resolutions are calculated before the map, they dont take in account the view center point or our live center point at each moment, this distance from projection center can be corrected and a single moment in time like an export and like in the Scalebar, but not in ZoomIN/ZoomOUT/movement of the map, would the resolutions needed to be constantly corrected in order to have a constant scale value.

or if the Scalebar text takes in consideration the current view resolution only and the Scalebar WDITH current view resolution + view center point? 


thanks

**Comment by mike-000** [comment]
Take the Bing maps example https://openlayers.org/en/latest/examples/bing-maps.html and select Ordnance Survey.  Bing have reprojected to EPSG:3857 the exact same maps that Ordnance Survey provide in EPSG:27700 https://labs.os.uk/public/os-data-hub-examples/os-maps-api/wmts-27700-basic-map (which are based on 1:50K and 1:25K paper maps)  If both display the same number of km grid squares in a map div of the same width (or even an OpenStreetMap covering the same area) I would expect the same scale to be displayed regardless of the underlying projection (any differences due to the projection would not be noticeable to the average end user).  If you have a requirement to show scale based on projection units I have no problem with that, but it seems like a specialist requirement which a typical end user wouldn't understand, which would be best done as an option in the control constructor to disregard the PointResolution.

**Comment by ldv-dev** [comment]
@mike-000 , after further testing i think the constructor should not be changed, possibly an option to disregard PointResolution.

In order to have a real scale based map it should look something like this: 
https://q5w01.csb.app/

but it couldn't be done like this, needs to be done from ground up and i don't know if it would be used by others.

The idea here is to have a Map for GIS technicians so that they can see data at a constant scale value, and also be be able to make a live preview map to print/export.

With a given W x H to export have a live frame above the map to be able to fit our content on the map, previously knowing the desired scale to export.

**Comment by mike-000** [comment]
If the requirement is to have a constant scale displayed regardless of panning an option to display nominal scale will be needed https://codesandbox.io/s/adoring-breeze-qjzpk  Preparing for print/export would be similar to the existing example https://openlayers.org/en/latest/examples/print-to-scale.html except you would not need to adjust for point resolution calculating to resolution to match the printer dpi is simplified to `var scaleResolution = scale / (resolution / 25.4);`

**Comment by ldv-dev** [comment]
@mike-000 also at getPointResolution()  the usage of (dpi / 0.0254) is giving me less accurate values then (dpi * 39.37), check my example above and try to set an high scale value to the map...

**Comment by mike-000** [comment]
I had already noticed that in my testing.  It is because the previous code used both 25.4mm/inch and and 39.37inch/meter and using both in the same calculation will cause discrepancies  The international definition is 25.4mm/inch so , so I replaced 39.37 with the more precise 1000/25.4 in the update.

**Comment by ldv-dev** [comment]
@mike-000  be careful with 1000/25.4 i had similar issues in the past because 39.37 were being used somewhere else, i believe i tried to use (39.3700787) to calculate Scale > Resolution and my scalebar was always off, i knew it was more precise but it needs to be used globally in OL.

**Comment by mike-000** [comment]
You probably found the same problem as me when my tests failed.  I have searched the code for 39.37 and the only other places (after my change to fix the tests) it is used are for US units (the pre-1959 standard as the US then adopted the international inch), and in the getLegendUrl() method for WMS sources, which isn't critical but should probably be updated for consistency.

**Comment by ahocevar** [comment]
@ldv-dev The text and the width of the bars are just a different representation of the same thing. If the one changes, the other has to change too. What you are maybe looking for is a map which keeps the point resolution constant, which results in a fixed scale.

I created a codesandbox that demonstrates how a map with a fixed scale looks: https://codesandbox.io/s/fervent-mclean-wvu2l?file=/main.js

![Aug-08-2020 23-23-32](https://user-images.githubusercontent.com/211514/89720004-3db53e80-d9ce-11ea-8f23-c46e76e85189.gif)

In this map, the resolution is always adjusted so the point resolution at the map center is constant. This is quite easy to achieve on the application level:
```js
// Keep the scale constant by adjusting the resolution to the point resolution
// at the current center
const view = map.getView();
let adjustingResolution = false;
let currentResolution = getPointResolution(
  view.getProjection(), view.getResolution(), view.getCenter()
);
view.on('change:resolution', function () {
  if (!adjustingResolution) {
    currentResolution = getPointResolution(
      view.getProjection(), view.getResolution(), view.getCenter()
    );
  }
});
view.on('change:center', function () {
  if (adjustingResolution) {
    return;
  }
  const resolution = getPointResolution(
    view.getProjection(), view.getResolution(), view.getCenter()
  );
  const adjustFactor = currentResolution / resolution;
  adjustingResolution = true;
  setTimeout(function () {
    view.setResolution(view.getResolution() * adjustFactor);
    adjustingResolution = false;
  }, 0);
});
```

**Comment by ldv-dev** [comment]
@ahocevar i have done something just like that on a comment above `https://q5w01.csb.app/`

**Comment by ahocevar** [comment]
@ldv-dev Glad to hear that my comment was useful. If you feel that this issue is resolved, please close it.

**Comment by nboisteault** [comment]
Hi,
OL2 was using 0.02540005080010160020 not 0.0254 => https://github.com/3liz/ol2/blob/master/lib/OpenLayers/Util.js#L983
In my case it allows my maps to have better rounded scales (1:500 000 not 1:500 001 for example).
Which value is correct?

**Comment by mike-000** [comment]
The international inch is defined as 0.0254 m - always used for screen sizes, dpi and paper sizes

The US survey inch is defined as 1 / 39.37 m - used as 1 / 12 of US survey foot, which is now only used as projection units in some US local projections

**Comment by nboisteault** [comment]
Thank you for those precisions.
