### ISSUE TITLE
features with style function disappear while panning after update to v6.4.0

### ISSUE THREAD

**Issue by eladlavi** [openlayers/openlayers#11347]
After update to v.6.4.0, features with style function, disappear while panning the map,
and reappear after pan stop.
This includes pointer pan and View aniamte().
Other features remain on the map and move with it.
The feature disappear including its label.

**Comment by jipexu** [comment]
Hi
Is it visible in some openlayers examples ?
Is it not in relation with #11344 ?

**Comment by eladlavi** [comment]
Hi.
I don't think it is related to #11344 because it isn't related to KML data.
This must be related to a change done on v.6.4.0 release.
to reproduce, add a vector layer with style property set to a function:
new VectorLayer({
            source: someVectorSource,
            style: styleFunction
        });


where:

function styleFunction(feature, resolution){
    return new Style({......});

}

**Comment by eladlavi** [comment]
so it is either the VectorLayer that has a style function or a feature added to the VectorSource that has a style function, rather than a Style Object.
a style function is quite useful for example if the style is resolution dependant or if we want each rendering of the map to  compute some dynamic style.

**Comment by eladlavi** [comment]
After some more testing, I believe that issue is related to have Text in the Style object.
With no Text object as a property of 'text' attribute of Style object, this problem does not happen.

**Comment by ahocevar** [comment]
@eladlavi This sounds a lot like it could have been fixed with #11346. Do your feature coordinates have three or more dimensions? If you can provide a working example that includes code and data, we can easily verify that.

**Comment by eladlavi** [comment]
@ahocevar , indeed it seems like this is it. I do have a third coordinate. And also I now noticed that when zooming in and out for some zooms it appears and for other it disappear.

**Comment by eladlavi** [comment]
To clarify, without Text in the style, the issue doesn't appear. In #11346 there is a fix but it "requires review".
Before v.6.4.0 I did not have this issue at all.

**Comment by eladlavi** [comment]
This is a very serious bug because many features have a Geometry that is composed of point/vertices with a third coordinate (the z-component), even though OpenLayers has no visual representation to the z component, data coming from WKT format certainly represent a three dimensional geometry. So for instance, a point can have Z value (or height).
WKT supports POINT-Z.

**Comment by ahocevar** [comment]
The fix in #11346 will be included in the 6.4.1 release, which I am going to publish as soon as #11346 has been reviewed by another @openlayers/core developer.

**Comment by eladlavi** [comment]
Thanks. Highly appreciated.
Without this fix, I would have to roll back from 6.4.0 as many of the features in my case, have a third component and also a label/text.
Holding my breath for 6.4.1.
