### ISSUE TITLE
Broken layout on OL website on large screens

### ISSUE THREAD

**Issue by TDesjardins** [openlayers/openlayers#11343]
**Describe the bug**
With the changes of the website a new layout issue has slipped in. If width of the window is greater than `1140px` then the new section will be wrapped (see screenshot)

![ol_website_broken_design](https://user-images.githubusercontent.com/1841306/88638627-06848a80-d0bc-11ea-81cd-35f34c0e7b23.PNG)

**To Reproduce**
1. Go to https://openlayers.org/ with window width > `1140px`

**Expected behavior**
News section shouldn't wrapped on large screens.

**Cause**
I suppose there is a bug in the media query. If I disable `max width: 1140px` in the media query then it looks fine (see screenshot below). The `min-width` is greater than `max width`.

![media_query](https://user-images.githubusercontent.com/1841306/88638625-05ebf400-d0bc-11ea-8e4e-f59a758574fc.PNG)

**Comment by jipexu** [comment]
HI
With all browser  ?

<img width="1115" alt="Capture d’écran 2020-07-28 à 10 38 27" src="https://user-images.githubusercontent.com/328101/88640843-b4913400-d0be-11ea-8f7b-ee99751a25e2.png">

**Comment by M393** [comment]
Happens for me in chrome.
Removing class 'float-right' from `#tagline` fixes it.

**Comment by jipexu** [comment]
yes !! no need ..

**Comment by TDesjardins** [comment]
> With all browser ?

Reproduced in Chrome, Firefox and Edge.

**Comment by jipexu** [comment]
yes i can also see on chrome and FF but not in safari ...

**Comment by TDesjardins** [comment]
Works for me.
