### ISSUE TITLE
Hit detection broken if view projection does not have an extent

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11356]
**Describe the bug**
getFeaturesAtPixel and forEachFeatureAtPixel are attempting to get the extent width and failing if the view projection has been set up without an extent or simply uses the code from proj4.def

**To Reproduce**
Click on the map and see the error reported https://codesandbox.io/s/confident-mcnulty-s4v0n

**Expected behavior**
As in previous versions, it should not be necessary for projections to have an extent to be used in this way.

**Comment by ahocevar** [comment]
Thanks for reporting this, @mike-000. Would you be able to provide a pull request with a fix?
