### ISSUE TITLE
VectorImageLayer disapperars when extent is set

### ISSUE THREAD

**Issue by lysek** [openlayers/openlayers#11357]
**Describe the bug**
When I set the extent of VectorImageLayer and zoom out or sometimes pan the map, the layer disappears.

**To Reproduce**
1. Go to [https://codesandbox.io/s/twilight-cookies-zz7ce?file=/src/index.js](https://codesandbox.io/s/twilight-cookies-zz7ce?file=/src/index.js)
2. Zoom out
3. See the icon and line (whole layer) disappear

**Expected behavior**
The layer should be visible

Some observations:
- It works without setting extent.
- It works with VectorLayer.
- It does not work with smaller extent.
- It works with OL v6.3.x

**Comment by jipexu** [comment]
hi in your example i  dont understand 
var ext = [...bl, ...tr];
var ext [bl,tr] seems work  The layer is visible ?

**Comment by mike-000** [comment]
@jipexu [bl,tr] is not a valid extent.  See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax
There seems to be a problem if the layer extent isn't fully contained in the view extent.  Possible related to #11193

**Comment by jipexu** [comment]
@mike-000 thanks

**Comment by ahocevar** [comment]
According to `git bisect`, 658bc0a729ca03a3bf6e061373f8fb97dbdcbb0 is the first bad commit.

**Comment by mike-000** [comment]
The simplest might be my original approach to #11193 of not clipping the image as the vector has already been clipped.

**Comment by ahocevar** [comment]
Makes sense @mike-000. But instead of adding an `opt_noClip` option to `renderFrame`, setting a member `verctorRenderer.clipping = false` would be nicer in my opinion.

Would you be able to create a pull request? And sorry for the suggestion about the identity transform back then, which was obviously not a good one.
