### ISSUE TITLE
React 16.12 with Openlayers 6.4.1

### ISSUE THREAD

**Issue by taviroquai** [openlayers/openlayers#11358]
**Describe the bug**
Quick start with build system from Openlayers website does not work.

> TypeError
> Cannot set property 'disposed' of undefined
> 

**To Reproduce**
Please see it at CodeSandbox:
https://codesandbox.io/s/determined-elion-7oh6g?file=/src/App.js

Here is without hooks:
https://codesandbox.io/s/thirsty-cherry-rtii0?file=/src/App.js

**Expected behavior**
Show OSM map on browser

Thank you! :)

**Comment by ahocevar** [comment]
Thanks for reporting this @taviroquai. Which quick start are you referring to?

**Comment by taviroquai** [comment]
Sorry my fault. Missing call NEW on OSM constructor. Sorry for the noise!
