### ISSUE TITLE
offscreen-canvas.worker.js  key parameter ?

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#11353]
Hi
in the url and style url the key  parameter have a mixed value 

key=get_your_own_D6rA4zTHduk6KOKTXzGB

is it correct ?? (it sound me confusing)

Thanks

**Comment by ahocevar** [comment]
To me it looks correct. What makes you think otherwise @jipexu ?

**Comment by jipexu** [comment]
i dont know/understand  why is mixed

i can understand :
D6rA4zTHduk6KOKTXzGB (should be a key ...)
get_your_own_key(i must give my own key...)

or i miss something ?

**Comment by ahocevar** [comment]
This is a special key we get from the smart folks at maptiler, which only works for content served from openlayers.org, and has a name that reminds you to get your own key when using that data. Sounds perfectly fine to me.

**Comment by jipexu** [comment]
ohhh !!!  ok so  get_your_own_D6rA4zTHduk6KOKTXzGB is a valid key !...

@ahocevar thanks for the explanation  !

**Comment by ahocevar** [comment]
@jipexu See #11355, which makes this example consistent with the others.
