### ISSUE TITLE
WMSCapabilities() does not parse SRS tags inside capabilities file (mapproxy).

### ISSUE THREAD

**Issue by ShelleyLake** [openlayers/openlayers#11362]
Problematic server is [https://mapproxy.vsgis.ch/proxy/service?REQUEST=GetCapabilities](url)

```
var parser = new ol.format.WMSCapabilities();

fetch('https://mapproxy.vsgis.ch/proxy/service?REQUEST=GetCapabilities')
  .then(function (response) {
    return response.text();
  })
```

WMSCapabilities() won't parse SRS tags, instead it returns `"crs": null` for every layer.

Is it a problem of "mapproxy" that uses SRS tags instead of CRS?

Thanks for any advice.

J.

**Comment by ahocevar** [comment]
Looks like our `WMSCapabilities` format only supports WMS version 1.3.0, but the service you are requisting only provides version 1.1.1.

**Comment by ShelleyLake** [comment]
Thanks for the info

**Comment by Yuki-Zhao** [comment]
So will you support 1.1.1？
