### ISSUE TITLE
Interactions don't work on iOS after updating to version 6.4.0

### ISSUE THREAD

**Issue by atm77** [openlayers/openlayers#11366]
Map interactions don't work on iOS.
can't drag, can't click on map, can't zoom.
It was working normally on OL 5.3.0
Any advices?

**Comment by ahocevar** [comment]
Probably because you are on iOS < 13? As mentioned in the [upgrade notes](https://github.com/openlayers/openlayers/releases/tag/v6.4.0/), you now need to include a pointer events polyfill in your build when targeting older platforms.

**Comment by atm77** [comment]
Ok, thank you for the fast answer @ahocevar 
I will try to add the events polyfill

**Comment by XYUNYUE** [comment]
Hello, I have also encountered this problem. I cannot drag or zoom the map using the latest version of OpenLayers in iOS. May I ask what I should do? Thank you

**Comment by ahocevar** [comment]
@XYUNYUE If you tell us which version of iOS. And make sure you have followed the advice given in this issue, i.e. include a pointer events polyfill in your build.

**Comment by XYUNYUE** [comment]
> @XYUNYUE如果您告诉我们哪个版本的 iOS。并确保您遵循了本期中给出的建议，即在您的构建中包含一个指针事件 polyfill。

@ahocevar  Do you mean I need to write zoom and move events on the map based on finger events? (I'm using ios10 and 6SP)

**Comment by XYUNYUE** [comment]
> @XYUNYUE如果您告诉我们哪个版本的 iOS。并确保您遵循了本期中给出的建议，即在您的构建中包含一个指针事件 polyfill。

The problem has been solved, thank you very much.

**Comment by XYUNYUE** [comment]
> @XYUNYUE如果您告诉我们哪个版本的 iOS。并确保您遵循了本期中给出的建议，即在您的构建中包含一个指针事件 polyfill。

@ahocevar  The problem has been solved, thank you very much.
