### ISSUE TITLE
better support/explanation of bootstrap tooltip in full screen mode

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#11369]
Hi
Actually If you want use bootstrap tooltip  (https://openlayers.org/en/latest/examples/button-title.html)  with fullscreen example
you lost the tooltip (not visible)

**To Reproduce**
mixe the 2 examples
https://codesandbox.io/s/pensive-brook-5l5o6
check the tootips behavior (ok visible and customized)
switch on full screen mode (not visible)

**Expected behavior**
- keep the tooltip visible on fullscreen mode
to make it work
add the container option of tooltip() with the same value of the target option of the  Map()

It will be good to suggest on the description (docs) of the custom tooltip example  that the container option of the tooltip() is required with the value of the target option of the Map() ...and add those options to the code ...

It was a long time that i look for this small problem on my maps ...
If ok i can make a PR 

Thanks

**Comment by ahocevar** [comment]
Yes, please submit a pull request @jipexu

**Comment by jipexu** [comment]
@ahocevar ok thanks will done in the day

**Comment by jipexu** [comment]
ok i can close thank !
