### ISSUE TITLE
Color distortion in ImageStatic despite imageSmoothing: false

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11375]
**Describe the bug**
As observed in https://github.com/openlayers/openlayers/pull/11019#issuecomment-667306514 the `imageSmoothing` option should also be applied to the canvas used to fit the image to the `imageExtent` where the image width/height ratio is different (also check if other subclasses are affected)

**To Reproduce**
See the examples in https://github.com/openlayers/openlayers/pull/11019#issuecomment-667285181

**Expected behavior**
The original colors should be preserved.

**Comment by ahocevar** [comment]
I agree that when the user chooses `imageSmoothing: false`, all canvases in the rendering pipeline should have image smoothing disabled. If you have implementation ideas or are planning to create a pull request, please share the planned approach here, @mike-000.

**Comment by mike-000** [comment]
The problem appears to be specific to ImageStatic and is easily fixed by inserting

`assign(context, this.getContextOptions());` 

in the `handleImageChange` method

https://codesandbox.io/s/hardcore-khayyam-dh1iv

**Comment by ahocevar** [comment]
Sounds good @mike-000. And please add a rendering test too.
