### ISSUE TITLE
Randomly generating symbology

### ISSUE THREAD

**Issue by shitathakin** [openlayers/openlayers#11370]
Not really a bug but I was wondering if anyone had a suggestion for an issue i'm facing. I dynamically load a set of geojson data into my my map (could be any size) and in turn create vector layers. I was wondering how I could generate unique symbology for each new layer being created. Really any advice on using symbols and icons would be appreciated. Thanks

**Comment by mike-000** [comment]
Maybe regular shapes https://openlayers.org/en/latest/examples/regularshape.html using random (within sensible ranges) values for the options and the R, G and B values for the fill and stroke colors?
