### ISSUE TITLE
High ImageCanvas ratio breaks render

### ISSUE THREAD

**Issue by EvertEt** [openlayers/openlayers#11389]
**Describe the bug**
When setting the ratio of ImageCanvas to a high value, it does not render anything at all.
**To Reproduce**
https://codesandbox.io/s/dazzling-raman-84r9e?file=/main.js
`ratio: 2` works where `20` does not show anything anymore

**Expected behavior**
It should still render. Perhaps capped to a sensible ratio if needed.

**Comment by ahocevar** [comment]
Why would you want to set `ratio: 20` on a device that does not support it?

**Comment by EvertEt** [comment]
Which devices do not support it? The ratio here is not the pixelRatio as far as I understand, but the canvas scale outside of the visible area

**Comment by ahocevar** [comment]
Correct. But each device/browser combination has a limit of the maximum canvas size. Setting `ratio` to a high value will likely cause a canvas to be created that exceeds the limit.

A `ratio` greater than `2` usually does not make sense, because `2` covers a full edge-to-edge pan in each direction without falling off the edge of the rendered image. If you thought about documenting that better, it would be a good improvement.

**Comment by EvertEt** [comment]
Thanks for the clarification. Is there any way to set the canvas to the highest possible size/ratio?

My use case:
I am rendering a georeferenced pdf and the rendering time is the same for the full pdf or only a part of it. Performance wise it would be the best to render the full page (large ratio).
So I put the ratio at 5 currently (not sure if this is too much as well then?)

Follow up question: Would there be a possibility to error when this happens instead of silently not rendering anything?

**Comment by ahocevar** [comment]
Your application could make use of e.g. https://github.com/jhildenbiddle/canvas-size to determine the maximum available size. Or in a try/catch block, it could create a canvas of the desired size and try to write and read from it. If it works and the written data can also be read, you can use a canvas of that size. Building that into the library is probably not too appropriate.

**Comment by EvertEt** [comment]
How should I relate canvas-size to the ratio? map element size times the pixelRatio of the map?

Not sure if it is worth it to do this externally, thanks anyway! 

Feel free to close this issue.

**Comment by ahocevar** [comment]
@EvertEt:

> How should I relate canvas-size to the ratio? map element size times the pixelRatio of the map?

Correct. That's the size at `ratio: 1`.
