### ISSUE TITLE
CodeQL-identified gremlins

### ISSUE THREAD

**Issue by mohawk2** [openlayers/openlayers#11399]
**Describe the bug**
CodeQL complains about these things:
- Missing `MessageEvent.origin` verification in `postMessage` handlers (https://github.com/metacpan/metacpan-web/security/code-scanning/33?query=ref%3Arefs%2Fheads%2Fmaster)
- Incomplete string escaping or encoding - "This replaces only the first occurrence of" `/%3A/i` and `#` (https://github.com/metacpan/metacpan-web/security/code-scanning/34?query=ref%3Arefs%2Fheads%2Fmaster and https://github.com/metacpan/metacpan-web/security/code-scanning/35?query=ref%3Arefs%2Fheads%2Fmaster)

**To Reproduce**
I think CodeQL is probably right. Have you considered using CodeQL, e.g. by imitating (or just copying) https://github.com/metacpan/metacpan-web/blob/master/.github/workflows/codeql-analysis.yml ?

**Expected behavior**
Not security warnings? :-)

**Comment by tschaub** [comment]
@mohawk2 the links you pasted (e.g. https://github.com/metacpan/metacpan-web/security/code-scanning/33?query=ref%3Arefs%2Fheads%2Fmaster) are 404 for me.

**Comment by sbrunner** [comment]
You can also do:
- Security tab.
- Setup code scanning button.
- CodeQL Analysis: setup this workflow button.
- ...

**Comment by mohawk2** [comment]
@tschaub Oops! The explanatory text for the first one:

> If you use cross-origin communication between Window objects and do expect to receive messages from other sites, always verify the sender's identity using the origin and possibly source properties of the recevied MessageEvent.

The second:

> Sanitizing untrusted input is an important technique for preventing injection attacks such as SQL injection or cross-site scripting. Usually, this is done by escaping meta-characters such as quotes in a domain-specific way so that they are treated as normal characters.

**Comment by tschaub** [comment]
> If you use cross-origin communication between Window objects and do expect to receive messages from other sites, always verify the sender's identity using the origin and possibly source properties of the recevied [sic] MessageEvent.

We do not use cross-origin communication between Window objects.

> Sanitizing untrusted input is an important technique for preventing injection attacks such as SQL injection or cross-site scripting. Usually, this is done by escaping meta-characters such as quotes in a domain-specific way so that they are treated as normal characters.

If you can provide detail on where these instances of "incomplete string escaping or encoding" occur, we could better gage whether there is a legitimate concern.  Otherwise, this broad truism ("sanitizing untrusted input is an important technique") isn't much to go on.

**Comment by mohawk2** [comment]
The code that triggers the first warning about `%3A`:

```
var t=this.auth||"";t&&(t=(t=encodeURIComponent(t)).replace(/%3A/i,":"),t+="@")
```

ends up in the distributed `ol.js` but doesn't seem (based on a lack of `.auth` found in the repo) to be directly from your code. Instead, it's this:

```
Url.prototype.format = function() {
  var auth = this.auth || '';
  if (auth) {
    auth = encodeURIComponent(auth);
    auth = auth.replace(/%3A/i, ':');
    auth += '@';
  }
// ...
```

from `url` version 0.11.0, apparently brought in by either node-libs-browser (it won't be from webpack-dev-server). It could be called a false positive, but it'd still probably be more correct for it to have a `/g`.

**Comment by mohawk2** [comment]
The second warning, about Worker and messages. The relevant code is in `src/ol/source/Raster.js`:

```
function createWorker(config, onMessage) {
  const lib = Object.keys(config.lib || {}).map(function (name) {
    return 'var ' + name + ' = ' + config.lib[name].toString() + ';';
  });

  const lines = lib.concat([
    'var __minion__ = (' + createMinion.toString() + ')(',
    config.operation.toString(),
    ');',
    'self.addEventListener("message", function(event) {',
    '  var buffer = __minion__(event.data);',
    '  self.postMessage({buffer: buffer, meta: event.data.meta}, [buffer]);',
    '});',
  ]);

  const blob = new Blob(lines, {type: 'text/javascript'});
  const source = URL.createObjectURL(blob);
  const worker = new Worker(source);
  worker.addEventListener('message', onMessage);
  return worker;
}
```

 The CodeQL bit says:

> # Recommendation
> Always verify the sender's identity of incoming messages.
>
> # Example
> [...]
> In the second example, the MessageEvent.origin is verified with an unsecure check. For example, using event.origin.indexOf('www.example.com') > -1 can be bypassed because the string www.example.com could appear anywhere in event.origin (i.e. www.example.com.mydomain.com)

```
function postMessageHandler(event) {
    let origin = event.origin.toLowerCase();

    let host = window.location.host;

    // BAD
    if (origin.indexOf(host) === -1)
        return;


    eval(event.data);
}

window.addEventListener('message', postMessageHandler, false);
```

The third example they give hardcodes an origin, which isn't suitable for your library code. But I'd have thought changing the check in the second example to be `event.origin.toLowerCase() === window.location.host.toLowerCase()` would be a good idea for maximum certainty?
