### ISSUE TITLE
Invalid links in navbar from examples / apidocs pages

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#11392]
**Describe the bug**
`Code > Download` and `Docs > Workshop` links are wrong when accessed from the apidoc / examples pages

**To Reproduce**
1. Go to https://openlayers.org/en/latest/apidoc/
2. Click on either `Code > Download` or `Docs > Workshop`
3. See error

**Expected behavior**
It should link to the correct page without the `en/latest/`  part in the url.

**Comment by ahocevar** [comment]
Thanks for reporting this @M393. Would you be able to provide a pull request with a fix?

**Comment by jipexu** [comment]
oh it's one of my mistake ..
