### ISSUE TITLE
Zooming while drawing polygons/lines on touch devices renders extra vertex temporarily

### ISSUE THREAD

**Issue by ludvigeriksson** [openlayers/openlayers#11397]
**Describe the bug**
If you are drawing a polygon or line on a touch device and use two finger zooming, OpenLayers will interpret one of the touch points as a hover (I assume, there might me another cause) and render an extra vertex at that point. It will not be part of the feature being drawn, but will render until another vertex is added or until zooming again (in which case another "ghost node" will appear).

**To Reproduce**
1. Setup a map with a Draw interaction of type Polygon.
2. Start drawing on a touch device.
3. Zoom with two fingers while the draw interaction is active.
4. See a "ghost node" appear.

**Expected behavior**
I expect nothing to happen when zooming while drawing. The geometry should not change until I add another vertex.

**Comment by ludvigeriksson** [comment]
This is still a bug btw

**Comment by ahocevar** [comment]
This has been fixed in the meantime. Try `npm install ol@dev`, or see https://openlayers.org/en/main/examples/draw-features.html
