### ISSUE TITLE
Adding New Geometries

### ISSUE THREAD

**Issue by eladlavi** [openlayers/openlayers#11396]
If I wish to add more geometries to my implementation, for example Arc,
the best strategy would be to extend an existing Geometry class or SimpleGeometry class.
I know that canvas supports drawing an Arc but it is unclear which method I should override in order to draw the Arc on the canvas.
It seems as if the internal drawing mechanism is disconnected from the Geometry class and uses "getType()" and some switch case that expects one of the existing "types" and therefore we cannot extend Geometry to rather new type of geometry unless internal ol code is modified.
What I did so far in order to solve this problem is to extended LineString and the Arc has a center, radius, starting angle,
and ending angle so I override getCoordinates and other methods to compute a LineString that is similar to an Arc.
This of course is inefficient and unless I break it  to huge amount of vertices, it isn't smooth and curved.
Obviously, any base geometry must be such that the browser and canvas can render.
So defining a star or a rectangle would be an easy one.
Surprisingly, there is a Circle geometry in ol.
What about a curve ? for example, Autocad has a LineString with "bulge" between vertices.

So a feature request is to have such a base geometry that supports curves, or, have a method in Geometry that can be overridden to draw directly on the canvas with "type" that is unfamilier to the drawing mechanism of ol.

**Comment by sweco-nlahoo** [comment]
@eladlavi Did you manage to extend OL with arc's and curves? We're facing a similar situation in which we would like to add support for these geometry types.

**Comment by eladlavi** [comment]
@sweco-nlahoo I ended up doing something very inefficient which is creating a class that extends one of the existing geometris defined by ol, for example LineString to represent an Arc. My Arc class extends LineString and receives in its constructor a center point, a radius, a begining angle and an ending angle (like an Arc should be defined), and I calculate many points on the Arc using basic math, and these points are set as the coords of the LineString.

The inefficiency is that if I choose too many points then there is a performance impact.
If I choose to little, the the arc is not smooth.

I know for surce that canvas, the basic technology ol relies on for rendering the map, does support natively in arcs.
I found it very hard to create a class that doesn't extend one of the existing geometries to be rendered directly on the canvas as a vector data.

This is because the set of known geometries and their type, are hard coded to some rendering functions in ol.
If I change this rendering function, I will break the ability to update ol for future updates and it requires very deep change.

If it had native support in arcs, then I guess I could extend it to many other geometries such as curves, spline and more.

**Comment by sweco-nlahoo** [comment]
@eladlavi Thank you for the detailed response.

We've thought about an approach like that. You basically stroked your arcs. For rendering that could work fine, but we're also looking to be able to interactively edit the arcs we draw.

Anyways, I'll go ahead and dig into the details a bit more and see if we can extend ol.
