### ISSUE TITLE
How to do the map initialization centered on the Pacific Ocean

### ISSUE THREAD

**Issue by mypanda** [openlayers/openlayers#11406]
I used geojson to draw the map, and then map.wrapX=false, and only rendered the map once.
 I want to draw the map with the Pacific Ocean as the center. 
What do you suggest?Thanks

**Comment by mike-000** [comment]
One option might be to use a custom projection more suited to the Pacific.  For example instead of the normal spherical mercator centered on the Greenwich meridian you could define a similar one centered on the date line https://codesandbox.io/s/modest-night-q3ixc

**Comment by mypanda** [comment]
Successful, thank you very much,
