### ISSUE TITLE
apidoc search is broken

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#11400]
**Describe the bug**
The search in the latest apidoc is not producing any results.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/apidoc/
2. Search anything
3. Nothing happens, even after pressing enter

**Comment by simonseyock** [comment]
https://openlayers.org/en/master/apidoc/ does work, though. But the former is the one that is linked from the start page https://openlayers.org

**Comment by jipexu** [comment]
oh what's happens .. sure  this worked one or two day ago ..

**Comment by M393** [comment]
Seems like the generation process crash at some point when writing the navigation html.
Press Ctrl + U to view the html source:
```html
                    <li data-name="getextent"><a href="module-ol_source_Vector-VectorSource.html#getExtent">getExtent</a>
                    <li data-name="getfeaturebyid"><a href="module-ol_source_Vector-VectorSource.html#getFeatureById">getFeatureById</a>
                    <li data-na
```

https://openlayers.org/en/master/apidoc/ is an older snapshot that is no longer updated
For a more recent version either use: https://openlayers.org/en/v6.4.2/apidoc/ or https://openlayers.org/en/main/apidoc/

**Comment by pricetula** [comment]
Maybe the link should be updated? on the main page

**Comment by jipexu** [comment]
@pricetula the url in https://github.com/openlayers/openlayers.github.io/tree/build/src/layouts/main.hbs seems correct...   ?       
`<li class="nav-item"><a class="nav-link" href="/en/latest/apidoc/"><i class="fa fa-sitemap mr-1"></i>API</a></li>
`

**Comment by pricetula** [comment]
@jipexu sorry for confusion, what i meant is if one navigates to https://openlayers.org/ clicking on the docs link will redirect to https://openlayers.org/en/latest/doc/ clicking on the api link, they are redirected to https://openlayers.org/en/latest/apidoc/ . But you are correct this link does work https://openlayers.org/en/main/apidoc/

**Comment by ahocevar** [comment]
The link is correct. https://openlayers.org/ is meant to link to https://openlayers.org/en/latest for version specific documentation. Looking into the search issue now.

**Comment by jipexu** [comment]
as @M393  wrote this crash when build navigation (and it crash always at the same place) but what i not understand is this worked slme days ago and i dont find what can be the cause in one recent modification ....

**Comment by jipexu** [comment]
it's work again now ....!
?

**Comment by ahocevar** [comment]
I had broken it with https://github.com/openlayers/openlayers.github.io/commit/375e6e4eba1d40d7e674f7249f460fe787b5eb34 when I tried to fix the links post-release, and fixed it again with https://github.com/openlayers/openlayers.github.io/commit/ec1fa0f5f23d0177669cac6ee7d8f9c4f5a8d0e6.
