### ISSUE TITLE
add CSS class name support control buttons

### ISSUE THREAD

**Issue by cazacugmihai** [openlayers/openlayers#11402]
In order to use custom icons(like [Font Awesome](https://fontawesome.com/)) for control buttons we have to deal with the button's class name and this functionality is missing. 

It would be nice to have supported this syntax:
```
new ol.control.Zoom({
  zoomInLabel: '',
  zoomInClassName: 'fa fa-plus',
  zoomOutLabel: '',
  zoomOutClassName: 'fa fa-minus'
});

new ol.control.Attribution({
  label: '',
  expandClassName: 'fa fa-info',
  collapseLabel: '',
  collapseClassName: 'fa fa-angle-double-right'
});

new ol.control.Rotate({
  label: '',
  compassClassName: 'fa fa-long-arrow-up'
});

new ol.control.FullScreen({
  label: '',
  inactiveClassName: 'fa fa-expand',
  labelActive: '',
  activeClassName: 'fa fa-compress'
});
```

Thank you!

**Comment by jipexu** [comment]
Hi
If it is only for zoom buttons
it can be hack with only a tricky  css
and the result simulate the 2 fontawesome search plus and search minus icons

```
.ol-zoom .ol-zoom-in::before {
    position: absolute ;
    font-family: "Font Awesome 5 Free";
    content: "\f002";
    font-size:1.1rem;
    margin-top:2.4px;
    margin-left: -3.2px;
}
```
and something similar for the zoom out

Hélas for the other buttons we are on the limit of the css to remove / replace
and i think if this is accepted the support must be done for all interface buttons content and not only for the zoom buttons ...?

**Comment by cazacugmihai** [comment]
@jipexu, you're right. The related PR it only wants to simplify that 'tricky' process. 

What other buttons OpenLayers have? Only the ones in `ol/control`?

**Comment by jipexu** [comment]
@cazacugmihai 
at least also rotate, full screen, attribution use some button with icons

**Comment by cazacugmihai** [comment]
Can someone look over [this](https://github.com/openlayers/openlayers/pull/11403) PR, please?
