### ISSUE TITLE
Rendering tests do not distinguish between white and transparency

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11414]
**Describe the bug**
I uploaded an image taken while designing a rendering test, but the wrong one as the background was transparent instead of while.  Despite the error the tests still passed.

Due to the white background here you will need to copy image and paste to an editor to see the difference
Wrong file:
![expectedE](https://user-images.githubusercontent.com/49240900/89729279-ee056000-da2b-11ea-86d4-6ad02e1e4549.png)
Correct file:
![expected](https://user-images.githubusercontent.com/49240900/89729288-08d7d480-da2c-11ea-8110-d3e94591e879.png)

**Expected behavior**
If the actual and expected do not match the test should fail.

**Comment by ahocevar** [comment]
Since we're comparing browser shapshots, we'll never have a transparent background. So I do not think this is something to worry about.

Out of curiosity: how did you create the image with the transparent background?

**Comment by mike-000** [comment]
It was an export from a local mock-up where I was planning what to add to the tests.

**Comment by ahocevar** [comment]
Ok, how do you go about creating rendering tests, @mike-000? I do it like this:

Let's say I create a rendering test in a folder `my-rendering-test`. Then I set up `main.js` in that folder, just like I would create the js for an example. To start debugging the test and seeing the result, I would run

    node rendering/test.js --interactive --fix --match my-rendering-test

This will open a Chrome instance where I can see the result and the bug the code.

**Comment by mike-000** [comment]
In this case I produced the tests to match the results I was expecting having already experimented in codesandbox using setScale() to get the desired effects in the example and test scripts, which I had saved via right click on the map. Somehow the prerender fill I set for the rectangle export didn't make in into the ellipse export I initially uploaded.

**Comment by ahocevar** [comment]
So I assume we can close this?

**Comment by mike-000** [comment]
Yes, if a copy of a single canvas without background works as with one with white background that should satisfy the test, but I was surprised that the image comparison software didn't pick up the difference.
