### ISSUE TITLE
Add GIF in icon

### ISSUE THREAD

**Issue by GeorgeCodeHub** [openlayers/openlayers#11412]
I'm trying to put animated icons all over my map but for some reason, it keeps them only in the first frame. Is there a certain setting that I need to add? In OpenLayers 2 it was able to do it no problem but in 6 it doesn't for some reason.

Below are two links. One with an example and the other with the link to the gif.

Example:  https://codesandbox.io/s/fervent-keller-wydlg?file=/main.js

Icon: https://i.pinimg.com/originals/a9/02/16/a902167cae8538769ad56ec7514ce73c.gif

Note: I need them to be as features and not as markers because I want to have click events on them.

Thank you for your time.

**Comment by mike-000** [comment]
Only one frame of a GIF can be rendered to canvas, so they cannot animate as features.  You could create them as features, hide the vector layer under your base map and for each feature create an overlay which will animate.  If `stopEvent` is false clicks will reach the map so you can detect the hidden features https://codesandbox.io/s/festive-bardeen-g2j3s?file=/main.js

**Comment by ahocevar** [comment]
Actually there is a way to render animated gif styles. You need a gif decoder library, e.g. [gifler](https://themadcreator.github.io/gifler/). Then you can set up an Icon style with the gifler controlled canvas, and call `render()` on the map when gifler renders a frame. See https://codesandbox.io/s/optimistic-bush-scgk3?file=/main.js for a working example.

The relevant code is:
```js
const gifUrl = "./data/a902167cae8538769ad56ec7514ce73c.gif";
const gif = gifler(gifUrl);
gif.frames(
  document.createElement("canvas"),
  (ctx, frame) => {
    if (!iconFeature.getStyle()) {
      iconFeature.setStyle(
        new Style({
          image: new Icon({
            img: ctx.canvas,
            imgSize: [frame.width, frame.height]
          })
        })
      );
    }
    ctx.drawImage(frame.buffer, frame.x, frame.y);
    map.render();
  },
  true
);
```

**Comment by mike-000** [comment]
Nice. That should be added as an example. There have been questions on here and stackoverflow and none have an answer using a feature with icon style.  When I tried it the dancing banana used in a lot of questions there was a bad ghosting effect, but adding `ctx.clearRect(0, 0, frame.width, frame.height);` before the `drawImage` fixes it.

**Comment by jipexu** [comment]
@ahocevar  so cool ! as @mike-000  said it will be a really a usefull example ...?

**Comment by GeorgeCodeHub** [comment]
Thank you very much for the quick response. The gifler approach seems very straightforward and exactly what I need. Thank you @ahocevar and @mike-000  for your examples!

**Comment by marcjansen** [comment]
@jipexu or anyone else, feel free to open a PR with an example showcasing the solution. TIA
