### ISSUE TITLE
Question: Using OpenLayers with GOJS?

### ISSUE THREAD

**Issue by personalGitRep** [openlayers/openlayers#11427]
Go.js is a library to build Diagrams. In their samples page, they already have instructions as well as example code to integrate Go.js with `leaflet` : https://gojs.net/latest/samples/leaflet.html

But for some reason, I rather use OpenLayers. But I don't know how to do that and I couldn't find anything on web. 

**What I want to do exactly?**
I need to have a map, and the user must be able to put some nodes on the map at specific locations and link them together. 
For example there is a server in the the city 'A', and there are clients in the city 'B', and the city 'C'. 
The user must be able to draw a link from these nodes to each other and these links must have the functionality to automatically go around each other to avoid overlap in case there are too many links in a small area and Go.js gives me just that. But I need OpenLayers just behind it to have the map, and I also use it's drawing tools to be able to draw vectors as well for some other purpose. I know it sounds weird but this is the functionality that I have to implement. I hope it's clear what I want and why do I want it. 

So can I use OpenLayers and Gojs on top of each other? 
Can someone here help?

**Comment by ahocevar** [comment]
It should be straightforward to use OpenLayers with GoJS. Either by extending `ol/source/ImageCanvas` when your GoJS output is a canvas element, or by doing something like in https://openlayers.org/en/latest/examples/d3.html or https://openlayers.org/en/latest/examples/svg-layer.html when it is an svg element.

**Comment by ahocevar** [comment]
I created an example that uses a plain `ol/Layer` with a `render` function that updates the diagram: https://codesandbox.io/s/lively-cdn-2zm67?file=/src/index.js

**Comment by personalGitRep** [comment]
Perfect Example I'll try it. Thank you very much.
