### ISSUE TITLE
Selective re-rendering for multi vector layer maps for high performance animations.

### ISSUE THREAD

**Issue by StereoPythonics** [openlayers/openlayers#11428]
I'm building an animation where thousands of points move along thousands of multi segment paths
My animation tweening for moving points in a vector layer is working well in isolation and rendering at a good ~60fps in isolation.
However, when I add another vector layer to show the paths (static LineStrings), the performance drops. 

My path LineStrings are unchanging, and from looking at the performance drop I'm guessing my path layer is being re-rendered along with my moving points layer. I haven't found anything in the docs yet that could let me decouple the need for these layers to re-render. Is there an approach that I've missed?

If this decoupling is currently unsupported, perhaps there's a route forward using layer rasterization/caching.
Static vector layers we could be rastered and stored in into a reused image buffer (with alpha). Then when another layer is re-rendering rapidly without any change in viewport, we can pull from this cache during the multilayer render process. 

Would anyone like to collaborate in trying this out?

**Comment by ahocevar** [comment]
One thing you can do is render the layer with the LineStrings with an `ol/layer/VectorImage` instead of `ol/layer/Vector`. This will cache the rendered linestrings on a canvas that can be drawn much faster.

**Comment by StereoPythonics** [comment]
Many thanks ahocevar. I'll give this a try!

**Comment by StereoPythonics** [comment]
This has done the trick, Excellent suggestion!

Is there any documentation I missed on the different vector layer types / their use cases? I'd be interested to read about the pro-cons of the different options!
