### ISSUE TITLE
Cannot read property 'highWaterMark' of null

### ISSUE THREAD

**Issue by rasa2k** [openlayers/openlayers#11429]
Upgraded from 6.3.1 to 6.4.0 and got a breaking change.
This comes from a VectorTileLayer with a VectorTileSouce that has a custom TileLoadFunction.

![image](https://user-images.githubusercontent.com/33285536/89899950-534f8180-dbe3-11ea-852c-e9098ae28f1c.png)

**Comment by jahow** [comment]
Looks like this line is missing a check for whether a tile cache exists or not:
https://github.com/openlayers/openlayers/blob/678a61cba0f3dfca12e5343a56c4dfce0b6d1441/src/ol/source/Tile.js#L328

**Comment by rasa2k** [comment]
> Looks like this line is missing a check for whether a tile cache exists or not:
> https://github.com/openlayers/openlayers/blob/678a61cba0f3dfca12e5343a56c4dfce0b6d1441/src/ol/source/Tile.js#L328

Thank you for a quick reply.
Is there a workaround for this? Or should I just wait for a fix?

**Comment by ahocevar** [comment]
At this point, there should be a tile cache available. @rasa2k, could it be that your source projection is misconfigured somehow? Can you share your code in a codesandbox? This issue should be easily fixable by not configuring the VectorTile source with a `projection`.

**Comment by rasa2k** [comment]
I don't have a projection on my source. It's set on the view.

Misconfigured how when the same code works in 6.3.1? Do you know of any changes regarding this?
I can try to share a sandbox example but right now the code is embeded in a larger app, so it will take a while to isolate it.

I can give some code example and hopefully you can see a flaw.

```
new VectorTileLayer({
    declutter: true,
    source: new VectorTileSource({
      maxZoom: config['MaxZoom'],
      minZoom: config['MinZoom'],
      url: 'tilematrix={z}&tilecol={x}&tilerow={y}',
      tileLoadFunction: tileLoadFunction,
      tileGrid: tileGrid,
    })
  });  
```

```
tileLoadFunction(tile, url) {
    var response = await Api.meshTileLoadGet(tile, url);
    if (response.data.length !== 0) {
      var featuresJson = new GeoJSON().readFeatures(response.data, {});
      tile.setFeatures(featuresJson);
    } else {
      tile.setFeatures([]);
    }
  }
```

```
const tileGrid = new TileGrid({
    extent: extent,
    resolutions: config['Resolutions'],
    minZoom: config['MinZoom'],
  });
```

**Comment by rasa2k** [comment]
This show's my problem.

Click on the map to trigger the problem:

OL 6.4.0 -> 6.4.3:
https://codesandbox.io/s/keen-spence-2fmx7

OL 6.3.1:
https://codesandbox.io/s/quizzical-glade-v6pgn

**Comment by pecet86** [comment]
I also picked up the version and noticed this problem.
From what I can see the problem results from changes in the method:
https://github.com/openlayers/openlayers/blob/v6.4.3/src/ol/renderer/canvas/TileLayer.js#L630
a means that if we do not have an explicitly declared projection (default if null is "EPSG: 3857") 
and it is different from the `View`, it will be this error

**Comment by ahocevar** [comment]
Correct, @pecet86. VectorTile sources with a projection different from the view projection worked more or less by chance in previous versions. But you could tell from the map flashing on zoom changes that something was wrong.

And yes, @rasa2k, your map is indeed misconfigured. You cannot use a VectorTile source for different projections. A VectorTile source's projection has to match the view projection. It does not support reprojection. Maybe we should document that better or throw an exception in such cases.

**Comment by pecet86** [comment]
@ahocevar physically, both the info in `Upgrade notes` for version 6.4.x and an exception in the console would be nice.
Due to the fact that the project in which I caught it worked in this way from version 4.x (already 4 years) and the error from the picture did not say much.
Only after tracing the thread and the source did I find out why.
