### ISSUE TITLE
Map Export not working

### ISSUE THREAD

**Issue by Spatialghost** [openlayers/openlayers#11434]
Hi. I try to export map, when i push the export button, map is not exporting. I use official example https://openlayers.org/en/latest/examples/export-map.html , its working, but when i use own data from GeoServer 2.17.2 with this sample, export not working. How to make map export for map with custom data?

**Comment by mike-000** [comment]
Exports will not work with tainted canvas.  If raster data is cross origin make sure `crossOrigin: 'anonymous'` is specified and supported by the server.

**Comment by Spatialghost** [comment]
> 
> 
> Exports will not work with tainted canvas. If raster data is cross origin make sure `crossOrigin: 'anonymous'` is specified and supported by the server.

Great Thank!
It's working!
