### ISSUE TITLE
Can't find variable: document

### ISSUE THREAD

**Issue by fros113** [openlayers/openlayers#11437]
**I just install and import open layers im trying to user the code as example**

import Map from 'ol/Map';
import View from 'ol/View';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';

new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: new XYZ({
        url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png'
      })
    })
  ],
  view: new View({
    center: [0, 0],
    zoom: 2
  })
});

and immediately I get the issue

**my code it's:**

import React, { Component } from 'react';
import { Text, TouchableOpacity, Image, ScrollView, FlatList } from 'react-native';
import AwesomeAlert from 'react-native-awesome-alerts';
import * as firebase from "firebase";
import { GlobalStyles } from '../style/global';
import firestore from '@react-native-firebase/firestore';
import addPersonIcon from '../assets/Icons/addPersonIcon.png';
import Map from 'ol/Map';
import View from 'ol/View';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';

new Map({
    target: 'map',
    
});

export default class OpenLayersScreen extends Component {
    constructor(props){
        super(props);
        this.state = {
        }
    }
   
    render() {    
        return (
                <div id="map" class="map"></div>
        );
    }   
}

**in package.json I have:**
"ol": "^6.4.3",
"react-native": "~0.61.5",

![117607678_3206551962725503_4778778803166009_n](https://user-images.githubusercontent.com/66624687/90293660-e65b1680-de84-11ea-958a-259325c1c5ae.jpg)

**Comment by tschaub** [comment]
It looks like you are trying to develop an Android app.  ReactNative lets you use React for mobile app development, but it doesn’t allow you to use browser APIs.  OpenLayers uses browser APIs.
