### ISSUE TITLE
I think that "focusWithTabindex" throws an uncatchable error for some valid use OL use-cases.

### ISSUE THREAD

**Issue by zachsa** [openlayers/openlayers#11445]
**Describe the bug**
I get a hard-to-debug console error sometimes:

```
condition.js:107 Uncaught TypeError: Cannot read property 'hasAttribute' of null
    at Arguments.focusWithTabindex (condition.js:107)
    at MouseWheelZoom.eval [as condition_] (condition.js:53)
    at MouseWheelZoom.handleEvent (MouseWheelZoom.js:169)
    at Map.PluggableMap.handleMapBrowserEvent (PluggableMap.js:887)
    at MapBrowserEventHandler.Target.dispatchEvent (Target.js:119)
    at MapBrowserEventHandler.handlePointerUp_ (MapBrowserEventHandler.js:159)
```

**To Reproduce**
I can see that `focusWithTabindex` function is executed when I hover on the map. I'm using this in a React application, where the state is updated in a callback to a `drawend` event. As this callback fires this error appears (but not always). If I were to guess, I would say that the error occurs when I move my pointer over the map just after the `drawend` event fires, asking React for a state update.

**Expected behavior**
Since I don't know exactly why the error is occurring, I don't know exactly what I am expecting. Looking at the function where the error is occurring (in `ol/events/condition`):

```
var focusWithTabindex = function (event) {
    return event.map.getTargetElement().hasAttribute('tabindex')
        ? focus(event)
        : true;
};
```

If `getTargetElement()` is returning null because the element is deleted after the event is fired, then I would prefer to just get `false` returned (or just not have the error). But I don't know if this is a reasonable request or not?

I don't know how to catch this error though, and in my case it looks like it can be ignored.

**Comment by ahocevar** [comment]
Thanks for reporting this @zachsa. #11446 should fix your problem.
