### ISSUE TITLE
Icons (scaled Canvas images?) less crisp on v6.4.3 than v4.6.5 e.g. on iPad 2017 (A1822)

### ISSUE THREAD

**Issue by Swiod** [openlayers/openlayers#11447]
Rendering of at least Icon styles (for features in VectorLayer) with Canvas images that will be scaled by 0.5 for 2x iOS devices are more blurry ("soft focus effect") in v6.4.3 than in v4.6.5. The blurriness could be further observed with example High DPI WMTS. 

Could not be reproduced on 2x Android devices (e.g. Samsung Galaxy SM-G975F) in Split-View with two Chrome Tabs. 

Reproduction
1. Get an iOS device with version 13.x (e.g. iPhone SE A1723, iPad 2017 A1822)
1.a. compare both OL versions of standard example High DPI WMTS with taking a careful look at e.g. the same street label
  * https://openlayers.org/en/latest/examples/wmts-hidpi.html (NEW)
  * https://openlayers.org/en/v4.6.5/examples/wmts-hidpi.html (OLD more crisp!)
1.b. compare both OL versions of customized example Icon Symbolizer
 * https://codesandbox.io/s/hungry-stonebraker-cqysq?file=/main.js (NEW)
 * https://codepen.io/swiod/pen/JjXKZOP (OLD more crisp!)

Would be great to getting back former crisp rendering.

**Comment by ahocevar** [comment]
Here are screenshots that compare both versions on a device with a device pixel ratio of 2:

1.a. - v6.4.3
<img alt="new" src="https://user-images.githubusercontent.com/211514/90523239-ef8e0100-e16c-11ea-98bb-a3671cb9f90a.png">

1.a. - v4.6.5
<img alt="new" src="https://user-images.githubusercontent.com/211514/90523296-fddc1d00-e16c-11ea-89e0-6ebf97b20d2d.png">

1.b. - v6.4.3
<img width="248" alt="new" src="https://user-images.githubusercontent.com/211514/90523798-970b3380-e16d-11ea-980c-dc055cb29e05.png">

1.b. - v4.6.5
<img width="248" alt="old" src="https://user-images.githubusercontent.com/211514/90523843-a38f8c00-e16d-11ea-957c-fef1c79c4db0.png">

In the case of 1.a., I do not notice a difference.

But in the case of 1.b., I do. It might have to do with the introduction of Retina support for icons (/cc @sbrunner) or x/y scaling (/cc @mike-000).

**Comment by Swiod** [comment]
Thanks for investigating it!

Are the 1.a. images really based on the two different versions? An image / pixel comparison with Beyond Compare did not show any differences at all. Please take a look at our screenshot, taken on iPad 2017 (A1822) with split view. For example the red circled label "B228", it looks more softened on latest OL version. 

![IMG_2294_withMark](https://user-images.githubusercontent.com/25922763/90609566-8e197100-e204-11ea-9f82-fcf37181c38b.PNG)

If it helps, I could provide more screenshots from other iOS devices too.

**Comment by ahocevar** [comment]
@Swiod That might be because v6 does not enforce integer zoom levels, but v4 does. I took the screenshot before performing any zoom action to make sure I look at the map at an integer zoom level.

**Comment by Swiod** [comment]
That's the same way I did proceed taking the screenshot. I did not do any zooming before taking the screenshot. But to be sure, I did adapt the examples High DPI WMTS to print the current zoom level based on resolution change event. 

  * https://codesandbox.io/s/eager-sun-zwb74?file=/main.js (NEW)
  * https://codepen.io/swiod/pen/VwaKgyw (OLD more crisp!)

Based on those little customized examples I made another screenshot that again does show the "soft focus effect" on the newer version. 

![IMG_6F7E1A6CF275-1](https://user-images.githubusercontent.com/25922763/90749379-adcb9a80-e2d3-11ea-8168-47224a343c35.jpeg)

Maybe it was meant to be like this for some kind of rendering performance gain. I would really be interested to know if there's a way to get back former crisp rendering or if we'll have to live with it for whatever reason.

**Comment by ahocevar** [comment]
Looks like something else is different in the two examples. Look at the rendering of "zoom: 11 (initial)". It is crisper in your left example. And that's definitely not related to OpenLayers.

**Comment by Swiod** [comment]
Just FYI I built the [example](https://codesandbox.io/s/cocky-pine-tvql7?file=/index.html) side by side (left: v6.4.3, right: v4.6.5) on codesandbox.io in two different css set-ups:
  * top: samples are sized per px 
  * bottom: samples (heights) are sized via viewport units vh

![IMG_0029](https://user-images.githubusercontent.com/25922763/92580426-9fe3b680-f28e-11ea-9514-faa42b453486.PNG)

What is interesting is that v4.6.5 wins over v6.4.3 in matters of crispness when sized per px. Look at label "Floridsdorf" or route shield "B14". 

Not so if sized per vh, there both seem a little blurry though v6.4.3 might even perform slightly better. 

Anyways, it probably adds up to Safari's rendering engine and I have to admit it really is a minor issue.
