### ISSUE TITLE
Automatic/dynamic/variable label placement

### ISSUE THREAD

**Issue by CarmentaVilliam** [openlayers/openlayers#11449]
First of I like to say a big thank you for all the great work on the product everyone, love it! 

**Is your feature request related to a problem? Please describe.**
I've searched both on SO and current issues here on Github for an answer but it seems i cant find anything about it other than this unanswered [SO question](https://stackoverflow.com/questions/52419615/openlayers-4-and-automatic-label-placement). 

When creating a vector layer with a set of features as input I can create a style for showing data from the features as labels, however when two features (two point geometries for example) overlap the labels are also overlapping since they are then drawn in the same position. 

**Describe the solution you'd like**
I'm suggesting there should be an option somewhere (like the _declutter_ option for a vector layer) that controls this behavior and make it possible to have the labels of overlapping features move slightly so that they no longer overlap.

**Ideas/discussion/questions**
I've been looking into it a bit and it seems to be implemented in this [MapBox PR](https://github.com/mapbox/mapbox-gl-js/pull/7596) as an example.

My idea for a workaround, until above solution exists (if accepted),  would be to use D3 to create the features and do the placement and then adding that as a layer similar to this [OL example](https://openlayers.org/en/latest/examples/d3.html). Could this be a possible workaround? Even if it is a possible workaround it seems a bit much for something which feels like it should be the default setting.

**Comment by robbitt** [comment]
This is a needed feature. There are many instances where one is confronted with many dense points and finding points via label is required.  Most desktop GIS software implements dynamic anchor points for vector labels.

**Comment by mike-000** [comment]
A partial workaround is to use decluttering and specify an array of offset text positions, close enough that only one is chosen for each feature, but it makes the alternatives available in some cases.  For example here https://codesandbox.io/s/busy-dubinsky-942kh?file=/main.js the red and blue labels are moved down and up respectively instead of using the normal label point which would conflict with another feature's label.

**Comment by newmen-git** [comment]
Don't know if anyone is reading this, but this is still a super-valid feature request.

**Comment by mike-000** [comment]
> Don't know if anyone is reading this, but this is still a super-valid feature request.

The example above is still valid.  To reproduce the behavior in Mapbox there should be nine alternative positions available https://docs.mapbox.com/help/troubleshooting/optimize-map-label-placement/#label-density  Here is the equivalent implemented in OpenLayers https://codesandbox.io/s/vector-label-decluttering-forked-cw8qd4?file=/main.js with labels displaced from the first choice center/middle position highlighted in red.  As you zoom in more labels will move to the first choice position and be shown in black.

**Comment by mike-000** [comment]
@robbitt  See also https://github.com/openlayers/openlayers/issues/14877#issuecomment-1707984118
