### ISSUE TITLE
out of GPU and system memory

### ISSUE THREAD

**Issue by k3it** [openlayers/openlayers#11456]
**Describe the bug**
When opening a specific openlayers page (link below) on Windows 10 in any browser (firefox, chrome, edge the system runs out of memory.  With h/w acceleration the GPU runs out of mem. Without the GPU  acceleration the main RAM quickly exhausts 32 GB.

I have an NVIDIA 1080 Ti with the most recent drivers.     

The page loads without any issues on an android phone or ipad (no memory leaks),
I have asked others with Win 10 and NVIDIA cards (but not the same model as mine) to attempt to recreate and they did not have a memory exhaustion problem.  So it's not 100% that it's a driver problem.   But the strange thing that multiple different browsers all have the same issue.

Windows 10, build 18363 
geforce driver 452.06

**To Reproduce**
1. Go to https://hamradiomap.com/adsb-persist/?pTracks
2. wait for the tracks to load
3. observe GPU and system memory in Windows 10 task mgr/performance

**Expected behavior**
Load page without running out of memory

![image](https://user-images.githubusercontent.com/9923389/90984356-5848f500-e542-11ea-9bb7-1ead2bc36962.png)

![image](https://user-images.githubusercontent.com/9923389/90984362-5ed76c80-e542-11ea-97d4-d0f244c6de8f.png)

**Comment by ahocevar** [comment]
The site you pointed to is not reachable.

**Comment by k3it** [comment]
sorry about that. can you please try again?
(the vpn to the 3B+ running the site dropped)

**Comment by ahocevar** [comment]
It looks like your page is loading way too much data for a web application. A 17 kB download every second is not really good practice.

That said, it does not look like there is a memory leak. And the application runs more or less fine on Safari on my Macbook.

My recommendation would be to rework the application to draw less lines, or only draw them when zoomed in. This would also improve the application from a cartographic point of view. And try to avoid downloading so much data while the application is running.

**Comment by llacb47** [comment]
@k3it is not the developer. It's an open-source flight tracking map. Repo here: https://github.com/wiedehopf/tar1090

**Comment by ahocevar** [comment]
Then the issue should be reported there. If investigations there show that OpenLayers is the culprit, a more detailled and specific error report should go in a new issue here.

**Comment by k3it** [comment]
sorry for reporting the bug from the "user" perspective, however the developer of tar1090 was not able to re-create the problem on his PC.   Despite the large number of objects the page renders fine in iOS and Android browsers.  there is something that triggers a memory leak in my specific setup but I cannot pinpoint what it is.  I would imagine someone else could run into this problem as well.  

I can run debug and provide more developer level information if you point me in the right direction.  i run the website linked to above which runs @wiedehopf's  code

**Comment by wiedehopf** [comment]
I only have the one error report about a memory leak, and by the behaviour described it sounds like a bug in the graphics driver maybe?
I wouldn't know how to start tracking down such an issue.
