### ISSUE TITLE
Any textAlign in VectorLayer text makes hasFeatureAtPixel fail

### ISSUE THREAD

**Issue by djibarian** [openlayers/openlayers#11466]
When changing the textAlign property to any other than the default ‘center’, hasFeatureAtPixel doesn’t calculate property the text area, giving a positive at aproximately half the width of the text label.

**Comment by ahocevar** [comment]
Can you provide a working example that shows the problem? I added a `hasFeatureAtPixel()` call in a `pointermove` handler in the vector-labels example, and set `renderBuffer` for all layers to `200`. The result is https://codesandbox.io/s/trusting-grass-q5q6t?file=/main.js. There you can set the alignment and see if the cursor changes when you hover over text. To me the behavior looks correct.

**Comment by djibarian** [comment]
Effectively it was the `renderBuffer` value being too low (the default `100`) for the labels length. Thank you!
