### ISSUE TITLE
Compilation issue with parcel --experimental-scope-hoisting with version 6.4.x

### ISSUE THREAD

**Issue by olsinao** [openlayers/openlayers#11476]
Compilation issue with **parcel --experimental-scope-hoisting with version 6.4.x**

I updated my npm repository to ol 6.4.x and when I run 
_parcel build code.html --experimental-scope-hoisting_ 
I get this error:
**_node_modules/@mapbox/mapbox-gl-style-spec/dist/index.es.js does not export 'function'_**

When I revert to version 6.3.x I have no problems. I also notice with version 6.4, there is a new directory added:
/node_modules/@mapbox/ which isn't there for version 6.3

The code compiles fine without the --experimental-scope-hoisting but it is too large thus I sort of need to use it.

Any recommendations on what to do?

Thanks,
Otmar

P.S. Great job on Open Layers!

**Comment by ahocevar** [comment]
I just tried to build the https://openlayers.org/en/latest/examples/mapbox-vector-layer.html example with Parcel, using copy/paste for all files in the example, and it worked fine.

Parcel tends to be a bit fragile. Sometimes it helps to delete the `.cache` and `dist` directories.

The additional directory in `node_modules` you were seeing is from a dependency of `ol-mapbox-style`, which is a dependency of `ol/layer/MapboxVector`, which was added in v6.4. The error you were seeing also comes from a dependency of that library, but I tend to think it is caused by Parcel misbehaving.

**Comment by olsinao** [comment]
Thanks for looking into it. 

After scrutinizing my code, it turned out that defining my layers and sources was the issue:

working:

import VectorTileLayer from "ol/layer/Vector";
import VectorTileSrc from 'ol/source/VectorTile';

vs NOT working:

import { VectorTile } from "ol/layer";
import { VectorTile as VectorTileSrc} from "ol/source";

**Comment by ahocevar** [comment]
That's interesting. You might want to try v2 of parcel, which you can do with `npm install parcel@next`. Note that you do not need the `--experimental-scope-hoisting` option any more in v2.

**Comment by MichaelZelensky** [comment]
Same issue here. I tried to build this example: https://openlayers.org/en/latest/examples/cluster.html as it is, and it didn't work. 

_node_modules\@mapbox\mapbox-gl-style-spec\dist\index.es.js does not export 'function'_

**Comment by ahocevar** [comment]
The proper solution is to use a newer version of Parcel. I have updated the example template in #11691.

Also see https://github.com/openlayers/openlayers/issues/11476#issuecomment-686291994.

**Comment by olsinao** [comment]
Just to mention, I did try to recompile using newer parcel, but my compiled code ended up almost 200kB larger along with my other dependencies. 

I noticed the compiled examples on the site are rather small. Is there another way to compile this that is relatively straight forward? I do like the parcel as the compilation is easy to set up compared to other methods that are more involved.

**Comment by ahocevar** [comment]
Webpack gives you more control, but the configuration is more involved if you start from scratch. If you use a framework like React, Vue or Angular, there are CLIs that will setup the whole environment with a single command though.
