### ISSUE TITLE
CollectionEvent typescript constructor declaration omits arguments

### ISSUE THREAD

**Issue by davidiamaf** [openlayers/openlayers#11477]
This is the declaration of the constructor in @types/ol 6.3.1 (there isn't a 6.4.3??)

```
export class CollectionEvent<T> extends BaseEvent {
    constructor();
    element: T;
    index: number;
}
```

This is the declaration of the event in ol 6.3.4 

```
**
 * @classdesc
 * Events emitted by {@link module:ol/Collection~Collection} instances are instances of this
 * type.
 */
var CollectionEvent = /** @class */ (function (_super) {
    __extends(CollectionEvent, _super);
    /**
     * @param {import("./CollectionEventType.js").default} type Type.
     * @param {*=} opt_element Element.
     * @param {number=} opt_index The index of the added or removed element.
     */
    function CollectionEvent(type, opt_element, opt_index) {
```

You may notice the types definition is missing the arguments for the constructor.

**To Reproduce**
Attempt to construct an Collection Event from a typescript file (my use case happens to be simulating adds to ensure that all existing collection content is updated per my ADD listener) - constructor typing errors ensue

**Expected behavior**
Type definition matches implementation, so I can create one

**Workaround**
```
new CollectionEvent(CollectionEventType.ADD, element, index) // desired
Object.assign(new BaseEvent(CollectionEventType.ADD), { element, index }) as CollectionEvent<BaseLayer> // workaround
```

**Comment by ahocevar** [comment]
The type definitions are using are maintained by a third party. I think reporting this issue at https://github.com/hanreev/types-ol or https://github.com/DefinitelyTyped/DefinitelyTyped would be more appropriate.
