### ISSUE TITLE
Overlay: null return value from PluggableMap not handled causes crash

### ISSUE THREAD

**Issue by davidiamaf** [openlayers/openlayers#11478]
Over in pluggable map, line 772 in getCoordinateFromPixelInternal there is a return null

https://github.com/openlayers/openlayers/blob/62842d550839d5fc1cdb5bfa2dfe5bca051408fe/src/ol/PluggableMap.js#L772

Which is not compensated for in Overlay.js

https://github.com/openlayers/openlayers/blob/62842d550839d5fc1cdb5bfa2dfe5bca051408fe/src/ol/Overlay.js#L460

In Overlay.js panIntoView(),  It is assumed that map.getCoordinateFromPixelInternal() will not return null, as in line 461 it immediately dereferences the return value with a [0] - this needs a guard for the murphy's law coincidence when this function gets called before the animation states are initialized.

Experimenting casually, merely refraining from any further action at this cycle/animation time finding a null value there seems to work around the issue, but I file this as bug report rather than pull request as I'm unsure if there are other side effects I might not be aware of...

**Comment by ahocevar** [comment]
Thanks for reporting this @davidiamaf. Simply returning from `Overlay#panIntoView()` when no `centerPx` could be obtained is a sensible change. Please create a pull request.
