### ISSUE TITLE
ol.interaction.Translate: Feature disappears while moving it far westward/eastward

### ISSUE THREAD

**Issue by regileeso** [openlayers/openlayers#11475]
I don't know if this is a bug or if I just don't understand the behavior, neither am I a professional geo-calculation guy.

A feature, which is moved far westward/eastward, using `ol.interaction.Translate`, disappears at a certain value of longitude.

I've prepared a https://jsfiddle.net/cha8wjgz/1/ for demonstration. While moving, it's logging the `event.coordinate` and `ol.proj.toLonLat(event.coordinate)` to the console. While latter one looks good, in terms of position, the internal OL longitude value increases and decreases respectively (east / west). I can understand that, because if it's being moved around world 1, world 2 and so on, it needs to de/increase. 

For me it looks like the feature is being moved out of OL bounds, or something. Even when the feature disappears from the map, the `event.coordinates` are still being logged and increasing/decreasing farther.

![grafik](https://user-images.githubusercontent.com/7136472/91173497-397f6580-e6de-11ea-8359-a5d256f1b5dc.png)

As stated initially, I don't fully understand this behavior or if it's even desired. So, could someone please explain that to me?

**Comment by regileeso** [comment]
Unfortunately this doesn't work for me because I do actually have 2 markers and a line between them (it's a ruler tool). If I set `wrapX: false` the lines are not drawn correctly.

I've played around a bit and started to use the `translateend` event to kind of _reset_ the feature's position to world 1.

https://jsfiddle.net/wtyjcous/

`translate.on('translateend', function(evt) { feature.getGeometry().setCoordinates(ol.proj.fromLonLat(ol.proj.toLonLat(evt.coordinate))) });`

This works for me, at least it looks like what I wanted to achieve.

But now another, at least from my perpesctive, strange thing happens.

`evt.coordinate` is **not** the coordinate of the Point feature, but the coordinate of the **click** event. So when _resetting_ the feature's position, it kind of bounces a certain amount of pixels, depending on the click position on the feature (click on the feature Style, which can be an image or something).

Can I somehow retrieve the Point position from the `Translate` process, and not the position of the click? Are there any offsets to the Point itself?

**Comment by mike-000** [comment]
You can move the feature's coordinate into the real world without using `evt.coordinate`

```
  translate.on('translateend', function(evt) {
    feature.getGeometry().setCoordinates(ol.proj.fromLonLat(ol.proj.toLonLat(feature.getGeometry().getCoordinates())))
  });

```
https://jsfiddle.net/rmujL0yg/

**Comment by regileeso** [comment]
Yes, this works. Thanks. Although I'm still not sure about the described problem/behavior. Anyway, as it's working for me now, I'll close this issue.
