### ISSUE TITLE
How to judge the tile layer loading is completed

### ISSUE THREAD

**Issue by sunday60004** [openlayers/openlayers#11487]
ol6，i created a layer with  "ol.layer.Tile" and used “postrender”  to listen，but i can't judge all tiles loaded，how can i do?

**Comment by M393** [comment]
You can track the tile load status on the tile source with the events `tileloadend`,  `tileloaderror`, `tileloadstart`

**Comment by ahocevar** [comment]
There is also a `rendercomplete` event on dispatched by the `Map` whenever all layers are rendered with their complete data. For knowing when all layers are loaded, you'll register a `once` listener when you have set or changed the source:
```js
map.once('rendercomplete', () => {
  console.log('all layers are loaded');
});
