### ISSUE TITLE
 Persian Gulf need to change to Arabian Gulf 

### ISSUE THREAD

**Issue by NaraP** [openlayers/openlayers#11489]
There is an issue with text on the map in Openlayers, the issue is we see the **Persian Gulf** instead of **Arabian Gulf** ,
we are an Arabian company and we really don't want to been seeing this in our product, can you please change the text to **Arabian Gulf**

**Comment by mprins** [comment]
talk to the people that make the map, not the people that make the toolkit to publish maps

**Comment by ahocevar** [comment]
And don't cross-post, you're wasting time of volunteers. https://stackoverflow.com/questions/63630326/change-text-of-individual-labels-on-map-openlayers/63633557?noredirect=1#comment112524754_63633557
