### ISSUE TITLE
Multiple maps in React app not cooperating

### ISSUE THREAD

**Issue by dechristopher** [openlayers/openlayers#11485]
**Describe the bug**
Our React app has mutiple pages containing OpenLayers maps. Some pages even have multiple maps in different components on the page like a tab view. The first load and render of a map works as expected but we have come to notice that subsequent map instance renders have their tile layers disappear and show as white until you hover over a feature or zoom on the map. It appears that the different map instances are having some tile storage collision or something but I don't know enough about OL under the hood to diagnose this properly. I also expect it's to do with us having a React wrapper component to use OL maps in.

**Expected behavior**
Multiple map instances on app pages to operate independently and not have their tiles disappear until interacted with.

Initial map loads fine:
![unknown2](https://user-images.githubusercontent.com/12652694/91486948-ff979600-e87a-11ea-8f54-e5678de3fb4f.png)

Subsequent instances on different pages or tabs don't show tiles:
![unknown](https://user-images.githubusercontent.com/12652694/91486952-032b1d00-e87b-11ea-9b94-8ce7606ec8da.png)

**Comment by dechristopher** [comment]
![unknown](https://user-images.githubusercontent.com/12652694/91486915-ef7fb680-e87a-11ea-97eb-ab13d3f0d8ff.png)
![unknown2](https://user-images.githubusercontent.com/12652694/91486917-f0184d00-e87a-11ea-819c-e77c3d2e89ba.png)

**Comment by ahocevar** [comment]
@dechristopher Can you share a minimal repository that exposes the issue?

A workaround could be to call `updateSize()` on the map when you switch to the other tab.

**Comment by dechristopher** [comment]
@ahocevar running updateSize in a react useEffect on tab change did the trick for us. In some cases we also have to poke the map by zooming a fraction of a zoom level in and out to force the tiles to re-render. Closing.
