### ISSUE TITLE
format GeoJSON can't parse the feauture with properties include geometry property

### ISSUE THREAD

**Issue by mrpan** [openlayers/openlayers#11484]
**Describe the bug**
**Describe the bug**
var format = new ol.format.GeoJSON();
      var data={
        "features": [
            {
                "geometry": {
                    "coordinates": [
                        104.05907,
                        30.63638
                    ],
                    "type": "Point"
                },
                "id": "test",
                "type": "Feature",
                "properties": {
                    **"geometry": "test",**
                    "_id": "119204"
                }
            }
        ],
        "type": "FeatureCollection"
    }
     var features =format.readFeatures(data);

**in new version（6.4.4-dev） it  can parse but result is not correct**

**To Reproduce**
3. See error

**Expected behavior**

Parse correctly

**Comment by ahocevar** [comment]
OpenLayers stores the geometry as feature property, like any other property. If your GeoJSON has a property named `geometry`, you need to configure `ol/format/GeoJSON` to use a different property name for the geometry. Example:
```js
import GeoJSON from 'ol/format/GeoJSON';
new GeoJSON({geometryName: 'the_geom'});
```
With this configuration, the resulting features will have the geometry in the `the_geom` property, and your `geometry` property will be properly obtained from the GeoJSON.

**Comment by mrpan** [comment]
ok，understanded, thank you !
