### ISSUE TITLE
[REQUEST] Allow text to always be on top of other styles

### ISSUE THREAD

**Issue by Nkmol** [openlayers/openlayers#11498]
**Is your feature request related to a problem? Please describe.**
Currently, I have multiple layers each corresponding to their specific feature type. Most of these features in their respective layer have, among other styles, a text style. Now it may happen, because of z-index or order of insertion of a (feature) layer that the text is shown beneath another feature style.

**Describe the solution you'd like**
In essence, I would like all the Text styles _between any layer_ to always be on top of any other feature style. As the text should always be the visible indicator that something is there, even in cases where the actual style is not visible by any visual obstruction.

**Comment by ahocevar** [comment]
When you are ok with text being decluttered, you can achieve this by setting `declutter: true` on each Vector or VectorTile layer.

**Comment by tiagoporto** [comment]
@ahocevar declutter option doesn't work for me.
I need all Text styles on Top of all layers.
Is this option available in OL?

**Comment by ahocevar** [comment]
@tiagoporto You could create and add all your layers twice. On the first occurrence, set a style without text, on the second, set a style with text only. And order them so all those without text are below those with text only. You can assign the same `source` to two or more layers.

**Comment by ahocevar** [comment]
@Frank-Chan Just put a layer with your Text style *below* the other layers in your layer stack, either by layer order or by its `zIndex`.

What was said in this issue is no longer true since v9 - decluttering no longer changes the render order.

**Comment by Frank-Chan** [comment]
OK，maybe I have to update to v9
