### ISSUE TITLE
Openlayers - faint lines between tiles in the 'Vector Tile Selection' example

### ISSUE THREAD

**Issue by thepigs** [openlayers/openlayers#11505]
**Describe the bug**
Faint lines between tiles in the 'Vector Tile Selection' example can be seen at certain zoom levels (related to fractional zoom?)

Please read my stackoverflow post here: https://stackoverflow.com/questions/63663544/openlayers-faint-lines-between-tiles-in-the-vector-tile-selection-example

**To Reproduce**

I have produced a small example showing the behaviour [here](https://thepigs.github.io/dist/).
The dark cross should not be there and shows the edges of the tiles.
[Source code](https://github.com/thepigs/thepigs.github.io) for the example. 

**Expected behavior**
Translucent vector tiles should not have borders, or the documentation should be updated to indicate under what conditions  tile borders will appear.

**Comment by ahocevar** [comment]
The cause for the lines you see at some tile borders is a lack of tile buffers in the data that comes from the server.

**Comment by thepigs** [comment]
What is interesting is if I downgrade  use ol 5.3.3 in the example then the tiles render [without borders](https://thepigs.github.io/dist5/).
So it looks like some rendering change between version 5 and 6 of openlayers causes the tile borders?

**Comment by ahocevar** [comment]
Interesting find. There were indeed many renderer changes between version 5 and 6. Are you able to do a `git bisect` to find the faulty commit?

**Comment by thepigs** [comment]
git bisect gives the following as the faulty commit:

commit 84db84bc23585d834e8b9d6d2562c215a6bdab6a
Author: ahocevar <andreas.hocevar@gmail.com>
Date:   Wed May 8 10:31:29 2019 +0200

    Avoid blurry vector tiles

 src/ol/renderer/canvas/VectorTileLayer.js | 2 ++
 1 file changed, 2 insertions(+)

@@ -614,6 +614,8 @@ class CanvasVectorTileLayerRenderer extends CanvasTileLayerRenderer {
     const tileGrid = source.getTileGridForProjection(projection);
     const resolution = tileGrid.getResolution(z);
     const context = tile.getContext(layer);
+    // Increase tile size when overzooming for low pixel ratio, to avoid blurry tiles
+    pixelRatio = Math.max(pixelRatio, renderPixelRatio / pixelRatio);
     const size = source.getTilePixelSize(z, pixelRatio, projection);
     context.canvas.width = size[0];
     context.canvas.height = size[1];

I verified that commenting the 'pixelRatio' line fixes the tile boundary issue in 6.4.3.

**Comment by thepigs** [comment]
Let me know if there is anything I can do to help with this.

**Comment by ahocevar** [comment]
@thepigs Thanks for offering help! You could test the updated example to see if my fix works as expected: https://deploy-preview-11521--ol-site.netlify.app/examples/vector-tile-selection.html.

**Comment by thepigs** [comment]
Yeah that fixes it! Thanks!
