### ISSUE TITLE
Missing points when MultiPoint is used with declutter on layer

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#11507]
**Describe the bug**
When a `MultiPoint` is decluttered the decluttering is not stable, with multiple `Point`s it is.
Some points are not drawn even though there is no other point close to it.
It only happens if some of the points are outside the current view.

**To Reproduce**
1. Go to https://codesandbox.io/s/falling-snow-ukbrh?file=/src/index.js
2. Pan the map
3. Some `Point`s appear / disappear. When clicking the 'Render' button the decluttering changes after panning.

**Expected behavior**
The decluttering should be the same as with multiple `Point`s, change the features in line 58 to compare.

**Comment by ahocevar** [comment]
You can make the declutter result more stable by increasing the `renderBuffer` of the `VectorLayer`. I played with your codesandbox, and it looks like a value of `1000` will make your points stable.

**Comment by M393** [comment]
The result seems to be the same when everything is rendered, so increasing the `renderBuffer` will help. But it seems like there is an issue with the decluttering when using a `MultiPoint`. 
E. g. in the image below there is a circle missing in the center with nothing around it.
![MultiPointDeclutter](https://user-images.githubusercontent.com/56256405/92243834-61cb4900-eec2-11ea-839f-2ce72f45a220.png)

**Comment by M393** [comment]
Looks like 00dc86c8c66dbc18ff254033c575d3040caf4e56 is the merge causing the problem.
`6.3.2-dev.1592029750381` on codesandbox

**Comment by ahocevar** [comment]
Thanks for the investigation, @M393. If you are able to provide a pull request with a fix, that would be awesome. And yes, I do know that the code involved here is not the easiest to debug.
