### ISSUE TITLE
Negative value of the calculated area

### ISSUE THREAD

**Issue by pecet86** [openlayers/openlayers#11503]
**Describe the bug**
Calculating the area of the polygon at the time of duplicate vertices produces a negative but correct value.
It does not always occur, it can be observed while drawing when the point we are drawing is aligned with the previous one.

It has been available since version 6.4.x.
Verified on EPSG:2180 and restored on 3857

Initially I thought it was supposed to indicate a geometry error, but it doesn't always occur

**To Reproduce**
Example:
[link](https://codesandbox.io/s/red-wood-dpfw4)

**Comment by ahocevar** [comment]
Thanks for reporting this regression. I can confirm the reported issue.

**Comment by ahocevar** [comment]
You may want to change your code to use the length and area calculations from `ol/sphere` to get more accurate measurements anyway. See https://openlayers.org/en/latest/examples/measure.html.

**Comment by ahocevar** [comment]
According to `git bisect`, c490745ff0774e47f4b766683f7edf9228cb23c3 is the faulty commit.
