### ISSUE TITLE
Is GML2 deprecated?

### ISSUE THREAD

**Issue by nboisteault** [openlayers/openlayers#11510]
**Describe the bug**
I'm wondering if GML2 is deprecated in OL 6.
I'm using `writeFeatures()` method of GML2 but it doesn't work. Now if I look at source code this method is in fact [here](https://github.com/openlayers/openlayers/blob/main/src/ol/format/XMLFeature.js#L258). Which calls `writeFeaturesNode` which return null.
Help me please.

**Comment by ahocevar** [comment]
GML2 is not deprecated. But for the parser to work, you need to configure it properly. `featureType` and `featureNS`need to match those in your GML document.

**Comment by nboisteault** [comment]
I did that for GML3 and it was working but looking at GML2 source code, I can't see how it can return something else than `null`.
Here is my code : 
```javascript
const GMLFormat = new GML2({
    featureNS: 'fns',
    featureType: 'ft',
    srsName: 'EPSG:4326'
});
console.log(GMLFormat.writeFeatures(OL6AllFeatures, {
    dataProjection: 'EPSG:3857',
    featureProjection	: 'EPSG:4326'
}));
```

**Comment by ahocevar** [comment]
Oh, now I see what you mean. Writing GML2 is only implemented in the WFS format. So instead of creating a `GML2` format instance, you need to create a `WFS` format instance.

**Comment by nboisteault** [comment]
Thanks a lot @ahocevar  !
