### ISSUE TITLE
GML Linearring should not have srsName attribute

### ISSUE THREAD

**Issue by fgravin** [openlayers/openlayers#11512]
**Describe the bug**
The OpenLayers GML formats have an issue serializing a geometry to GML: `<gml:LinearRing>` element should not have `srsName` attribute.

Reference: http://www.datypic.com/sc/niem21/e-gml32_LinearRing.html

**To Reproduce**
1. Create an ol geometry
2. Write features from GML format of this geometry
3. Output GML (both version 2 and 3) will have an `srsName`

```xml
<gml:exterior>
  <gml:LinearRing srsName="urn:x-ogc:def:crs:EPSG:4326">
    <gml:posList srsDimension="2">38.5571 -75.7071 38.4631 -75.6991 38.4551 -75.3501
```

**Expected behavior**
`<gml:LinearRing>` does not have `srsName` attribute.
```xml
<gml:exterior>
  <gml:LinearRing>
    <gml:posList srsDimension="2">38.5571 -75.7071 38.4631 -75.6991 38.4551 -75.3501
```

**Comment by mprins** [comment]
well that depends on the version of GML
for GML2 a geometry is defined as:
```xml
<complexType name="AbstractGeometryType" abstract="true">
<annotation>
<documentation>
All geometry elements are derived from this abstract supertype; a geometry element may have an identifying attribute (gid). It may be associated with a spatial reference system.
</documentation>
</annotation>
<complexContent>
<restriction base="anyType">
<attribute name="gid" type="ID" use="optional"/>
<attribute name="srsName" type="anyURI" use="optional"/>
</restriction>
</complexContent>
</complexType>
```
see http://schemas.opengis.net/gml/2.1.2/geometry.xsd

while for gml 3.2.1 a geometry is defined as:
```xml
<complexType name="AbstractGeometryType" abstract="true">
<annotation>
<documentation>
All geometry elements are derived directly or indirectly from this abstract supertype. A geometry element may have an identifying attribute (gml:id), one or more names (elements identifier and name) and a description (elements description and descriptionReference) . It may be associated with a spatial reference system (attribute group gml:SRSReferenceGroup). The following rules shall be adhered to: - Every geometry type shall derive from this abstract type. - Every geometry element (i.e. an element of a geometry type) shall be directly or indirectly in the substitution group of AbstractGeometry.
</documentation>
</annotation>
<complexContent>
<extension base="gml:AbstractGMLType">
<attributeGroup ref="gml:SRSReferenceGroup"/>
</extension>
</complexContent>
</complexType>
<attributeGroup name="SRSReferenceGroup">
<annotation>
<documentation>
The attribute group SRSReferenceGroup is an optional reference to the CRS used by this geometry, with optional additional information to simplify the processing of the coordinates when a more complete definition of the CRS is not needed. In general the attribute srsName points to a CRS instance of gml:AbstractCoordinateReferenceSystem. For well-known references it is not required that the CRS description exists at the location the URI points to. If no srsName attribute is given, the CRS shall be specified as part of the larger context this geometry element is part of.
</documentation>
</annotation>
<attribute name="srsName" type="anyURI"/>
<attribute name="srsDimension" type="positiveInteger"/>
<attributeGroup ref="gml:SRSInformationGroup"/>
</attributeGroup>
```
http://schemas.opengis.net/gml/3.2.1/geometryBasic0d1d.xsd so that also has a `srsName` attribute

**Comment by tschaub** [comment]
A `LinearRing` is not a substitute for an `AbstractGeometry` (a `Polygon` is).

**Comment by mprins** [comment]
@tschaub  I'm confused now because in [GML 2](view-source:http://schemas.opengis.net/gml/2.1.2/geometry.xsd) a linear ring extends (abstract) geometry, just like a polygon

```xml

<element name="_Geometry" type="gml:AbstractGeometryType" abstract="true"/>

...

<element name="LinearRing" type="gml:LinearRingType" substitutionGroup="gml:_Geometry"/>
<element name="Polygon" type="gml:PolygonType" substitutionGroup="gml:_Geometry"/>

...

<complexType name="LinearRingType">
    <annotation>
        <documentation>A LinearRing is defined by four or more coordinate tuples, with linear interpolation between them; the first and last coordinates must be coincident.</documentation>
    </annotation>
    <complexContent>
        <extension base="gml:AbstractGeometryType">
            <sequence>
                <choice>
                    <element ref="gml:coord" minOccurs="4" maxOccurs="unbounded" />
                    <element ref="gml:coordinates" />
                </choice>
            </sequence>
        </extension>
    </complexContent>
</complexType>

...

<complexType name="PolygonType">
    <annotation>
        <documentation>
            A Polygon is defined by an outer boundary and zero or more inner 
            boundaries which are in turn defined by LinearRings.
        </documentation>
    </annotation>
    <complexContent>
        <extension base="gml:AbstractGeometryType">
            <sequence>
                <element ref="gml:outerBoundaryIs" />
                <element ref="gml:innerBoundaryIs" minOccurs="0" maxOccurs="unbounded" />
            </sequence>
        </extension>
    </complexContent>
</complexType>


```

**Comment by ahocevar** [comment]
Correct. In GML2, a LinearRing is a geometry primitive, which can have a srsName, but the [spec](http://portal.opengeospatial.org/files/?artifact_id=11339) states in 4.3.3

> Since a LinearRing is used in the construction of Polygons (which specify their own SRS), the srsName attribute is not needed.

Also in GML3, a the `LinearRingPropertyType`, which is used for the rings of a polygon, is made of a sequence of `LinearRing`s, which have a hierarchy of AbstractRing -> AbstractCurve -> AbstractGeometricPrimitive -> AbstractGeometry. For that, the [spec](http://schemas.opengis.net/gml/3.2.1/geometryBasic0d1d.xsd) states

> Any geometry element that inherits the semantics of AbstractGeometryType may be viewed as a set of direct positions. All of the classes derived from AbstractGeometryType inherit an optional association to a coordinate reference system. All direct positions shall directly or indirectly be associated with a coordinate reference system. When geometry elements are aggregated in another geometry element (such as a MultiGeometry or GeometricComplex), which already has a coordinate reference system specified, then these elements are assumed to be in that same coordinate reference system unless otherwise specified.

OpenLayers also has a `LinearRing` geometry. If such a `LinearRing` is serialized in GML, its `srsName` attribute makes sense and is needed to indicate the SRS. For the rings of a polygon, there is nothing wrong about proposing the removal of the `srsName`, at least for GML2. But for both GML2 and GML3, the XML is still valid with the `srsName` on a `LinearRing`, also for the rings of a Polygon.

**Comment by fgravin** [comment]
> But for both GML2 and GML3, the XML is still valid with the `srsName` on a `LinearRing`, also for the rings of a Polygon.

Is it true ? I do propose the fix exactly because we have a metadata XML validator based on schemas, that does not validate this GML. Accordingly to the GML schema, it say that a `LinearRing` can't have a `srsName`, at least for GML3.2.

```xml
<gmd:polygon xmlns:gml="http://www.opengis.net/gml/3.2">
  <gml:MultiSurface gml:id="d1552e276" srsName="urn:ogc:def:crs:EPSG:6.6:4326">
    <gml:surfaceMember>
      <gml:Polygon gml:id="d1552e278" srsName="urn:ogc:def:crs:EPSG:6.6:4326">
        <gml:exterior>
          <gml:LinearRing srsName="urn:ogc:def:crs:EPSG:6.6:4326">
            <gml:posList srsDimension="2">-7.291649395776517 -2.959381044487454 20.441748386546323 11.315280464216622 29.274573470718252 57.620889748549295 14.129239577220375 70.85106382978722 -15.475635632969514 71.89555125725337 -7.291649395776517 -2.959381044487454</gml:posList>
          </gml:LinearRing>
        </gml:exterior>
      </gml:Polygon>
    </gml:surfaceMember>
  </gml:MultiSurface>
</gmd:polygon>
```

Also:
> AbstractRing -> AbstractCurve -> AbstractGeometricPrimitive -> AbstractGeometry

Following http://www.datypic.com/sc/niem21/e-gml32_LinearRing.html, LineraRing -> AbstractRing -> AbstractObject, so as @tschaub pointed out LineraRing is not a substitute of a geometry (as far as i understand the reading of this).

Maybe the correct fix should be just to remove `srsName` from `LinearString` for GML 3.2 ? Cause as you mention, they are allowed for GML2 and GML3.

**Comment by fgravin** [comment]
Even more specific, `LineraRing -> AbstractRing -> AbstractObject` is true only for GML 3.2.1.2.
GML 3.2.2 adds back the `AbstractRing -> AbstractCurve` substitution, that makes the `LinearRing` an `AbstractGeometry` .

3.2.1.2 schema:
![image](https://user-images.githubusercontent.com/1491924/92239761-d3ec5f80-eebb-11ea-948e-c1808548521d.png)

Schema difference between 3.2.1.2 and 3.2.2
![image](https://user-images.githubusercontent.com/1491924/92239857-f5e5e200-eebb-11ea-9939-1a3684dbf98e.png)

The pb is that they both reference the same `targetNamespace` `xmlns:gml="http://www.opengis.net/gml/3.2"`.

I guess it's not worth it to have a format for each subversion so it might be preferrable not to go further with this fix cause OpenLayers actually serialize valid GML for GML2 GML3 and GML3.2.2. 

Sorry for the noise, i guess we can close it ?

Thanks !

**Comment by mprins** [comment]
IMO it makes sense to not have `srsName` on a `LinearRing` when it is an exterior or interior ring of a polygon because that should take precedence (and because I wouldn't want to handle any that have mixed SRSs with gloves on :smiley_cat: )

**Comment by tschaub** [comment]
I had been reading the schema that @fgravin refers to I guess - where the closest common ancestor of Polygon and LinearRing is AbstractObject.  If indeed srsName is optional in some versions and disallowed in others, we could comply with all by not serializing it.  What a mess (and particularly awkward to read ogc schema on a phone).

**Comment by ahocevar** [comment]
I guess the most generic way to achieve this is a change in our GML serializers so the `srsName` is only set on the "outermost" geometric entity. So in the case of a polygon, only the `gml:Polygon` would get the attribute. Or e.g. for a `MultiPoint`, only the `gml:MultiPoint` and not its point members.
