### ISSUE TITLE
Cluster style from ol-ext is not working in v6.4.3

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#11536]
Cluster style Chart from ol-ext is not working in v6.4.3 anymore. Check examples below:
 
version 6.3.1 (working as expected):
https://codesandbox.io/s/cluster-forked-iulyw?file=/index.js
![clusters1](https://user-images.githubusercontent.com/3100059/92470830-4c626180-f1d7-11ea-874a-8c094f7592c3.gif)

version 6.4.3 (styles are not working):
https://codesandbox.io/s/cluster-forked-zrgv0
If AnimatedCluster is used then you can see styles during cluster animation after zoom:
![clusters](https://user-images.githubusercontent.com/3100059/92470653-0f966a80-f1d7-11ea-96a4-1c1c273d803a.gif)

If a standard Vector layer is used then you cannot see styles at all.

Is this an issue of openlayers or ol-ext library?

**Comment by mike-000** [comment]
What is the pixelRatio of your device?  I can reproduce it only by setting the map pixelRatio option to 2.  The ol-ext chart style subclasses RegularShape and the OpenLayers end of the problem should be fixed by #11501 but ol-ext may now need a corresponding update.

**Comment by MichalK6677** [comment]
I have Windows 10 and scale of my screen set to 125%. When I set it to 100% then it's working on both version
![image](https://user-images.githubusercontent.com/3100059/92481970-5ee49700-f1e7-11ea-8f4d-7270ea5abcd8.png)

I will copy this issue into ol-ext repository.

**Comment by mike-000** [comment]
Yes, it looks like ol-ext will need some changes to work with other pixel ratios as a result of the changes made in #11277 (and followed up by #11336 and #11501)

**Comment by natalidedik** [comment]
I have the same issue https://github.com/Viglino/ol-ext/issues/506

**Comment by Viglino** [comment]
Using ol6, images are calculated once using the current pixel ratio. 
Changing this pixel ratio (or browser zoom) after this calculation will point to non existing images...
I'll try to see what can be done...
