### ISSUE TITLE
TypeError: imageAnchor is null while trying to set icon style

### ISSUE THREAD

**Issue by danvc** [openlayers/openlayers#11539]
**Describe the bug**
I'm getting the exception related to `imageAnchor is null` while trying to set the icon style above a feature.

My goal is to drawn an icon alert 🚨 above a feature. My feature is being drawn as drone icon. 
![image](https://user-images.githubusercontent.com/24215587/92554953-f0cabf00-f23c-11ea-853e-f2e40fb7d251.png)

**To Reproduce**
For this, I'm implementing the following function:
```
// the following function is going to be triggered in the `postrender` event
export const setIconEffect = (feature: Feature, event: any) => {
    // get the current vector context
    const vectorContext = getVectorContext(event);

    // do a copy of the current feature geometry
    const flashGeom = feature.getGeometry().clone();

    // define the style for the icon that is going to appear above the feature
    const style = new Style({
        image: new Icon({
            src: 'assets/images/mapElements/warning-icon.png',
            scale: 0.2,
            anchorXUnits: IconAnchorUnits.FRACTION,
            anchorYUnits: IconAnchorUnits.FRACTION,
        }),
    });

    // set the icon
    vectorContext.setStyle(style);

    // draw the cloned geometry
    vectorContext.drawGeometry(flashGeom);

    // should call the map to get it rendered again
    // map.render();
};

// calling it
const listenerKey: any = this.state.layers[0].on('postrender', (event: RenderEvent) =>
    setIconEffect(feature, event)
);
```
However, I'm getting the following error:

![image](https://user-images.githubusercontent.com/24215587/92555367-df35e700-f23d-11ea-8c2b-22ccb6941c1c.png)

**Expected behavior**
Have the icon drawn in the feature

**Comment by mike-000** [comment]
That code is not from the latest version.  If you use the latest version there should be no error but creating a new Icon style from a src url in vector context will not work as expected as it will be loaded asynchronously and vector context is immediate.  You should preload the url into an Image object and use that for the icon img option, or (with current version) define the style object outside the postrender event.

**Comment by danvc** [comment]
Thanks @mike-000 .

Besides that issue, I've found (probably) another issue based in the same code.

I've got it working (the code above... I mean, no error) but, the result isn't the wanted one. When I clone a geometry and try to apply another icon, what happens is that, if I try to set a different icon/image (into the mark), nothing happens... BUT, if I try to use the same image (as the same that we have in the mark), it works.

Just as example, the icon in the left is the one that would be the notification.. and the right one would be the mark (but, a drone instead)
![image](https://user-images.githubusercontent.com/24215587/92665875-0c39d680-f2de-11ea-8663-b3ae6100afdf.png)
 

To draw the mark into the mark, I've implemented tools, which represent something as mark. Drones, for example, will be represented by an image. The implementation is this one:

```
const drone: ITool = {
    label: 'Drone',
    icon: NearMe,
    value: GeometryType.POINT,
    entityType: EntityType.DRONE,
    style: new Style({
        image: new Icon({
            src: 'assets/images/mapElements/drone-icon.png',
            scale: 0.2,
        }),
    }),
};
```

However, to set an alert into the drone icon, I was implementing this function which takes a feature as reference which is going to be used to be cloned and set a new icon into it:

```
export const setIconEffect = (feature: Feature, event: any, map: any) => {
    const vectorContext = getVectorContext(event);

    const flashGeom = feature.getGeometry().clone();
    // radius will be 5 at start and 30 at end.
    // set a different/injected style.. OR, a default one
    const style = new Style({
        image: new Icon({
            src: 'assets/images/mapElements/warning-icon.png',
            scale: 0.2,
            imgSize: toSize(500),
            anchorOrigin: IconOrigin.BOTTOM_LEFT,
            anchor: [1.0, 0.5],
        }),
        zIndex: 1000,
    });
    vectorContext.setStyle(style);
    vectorContext.drawGeometry(flashGeom);
    map.render();
};
```

However, as mentioned before.. if I try to set this icon with a different image.. it doesn't work.. but if I use the same as the mark has, it works (which doesn't make any sense).

Any idea how I could be applying different icons into a mark?

**Comment by danvc** [comment]
Closing this issue since it's not available as mentioned by @mike-000
