### ISSUE TITLE
[BUG] Icon style isn't applied into cloned features

### ISSUE THREAD

**Issue by danvc** [openlayers/openlayers#11546]
**Describe the bug**
Version: "@types/ol": "^6.3.1",

**To Reproduce**

1. Add a mark into the map containing a style as icon (picture);
2. Clone the feature;
3. Try to apply a different icon to the cloned feature.

Add a mark with a style similar to this one:
```
    // Geometry type
    value: GeometryType.POINT,
    // Geometry style
    style: new Style({
        image: new Icon({
            src: 'assets/images/mapElements/drone-icon.png',
            scale: 0.2,
        }),
    }),
```

Given a feature as parameter, clone it and set a different icon style
```
export const setIconEffect = (feature: Feature, event: any) => {
    const vectorContext = getVectorContext(event);

    // Clone the geometry from the Feature
    const flashGeom = feature.getGeometry().clone();
    // define a new style setting a different icon picture
    const style = new Style({
        image: new Icon({
            src: 'assets/images/mapElements/warning-icon.png',
            scale: 0.1,
            imgSize: toSize(500),
            anchorOrigin: IconOrigin.BOTTOM_RIGHT,
            anchor: [1.8, 0.05],
        }),
    });
    // apply the style and draw it into the map
    vectorContext.setStyle(style);
    vectorContext.drawGeometry(flashGeom);
};
```

**An important note**: If we use a different `src` it won't work, but if we use the same `src`, it will shown in the map (as duplicated)

Example of a cloned and styled geometry:
![image](https://user-images.githubusercontent.com/24215587/92669441-edd8d880-f2e7-11ea-8fb3-391257770012.png)

However, if we set a different `src` nothing is going to be shown:
![image](https://user-images.githubusercontent.com/24215587/92669465-06e18980-f2e8-11ea-886b-2824a1bf0fe0.png)

**Expected behavior**
Get a different icon into the cloned feature.

**Comment by mike-000** [comment]
This is the dsame problem but with a different icon.  It is only working with the same src only because of browser caching.  Rendering to vector context does not wait for an image to be loaded from a remote url.  You should predefine the styles outside the function and not create new ones every time you call your functions


```
const style1 = new Style({
    image: new Icon({
        src: 'assets/images/mapElements/warning-icon.png',
        scale: 0.2,
        imgSize: toSize(500),
        anchorOrigin: IconOrigin.BOTTOM_LEFT,
        anchor: [1.0, 0.5],
    }),
    zIndex: 1000,
});

const style2 = new Style({
    image: new Icon({
        src: 'assets/images/mapElements/drone-icon.png',
        scale: 0.2,
        imgSize: toSize(500),
        anchorOrigin: IconOrigin.BOTTOM_LEFT,
        anchor: [1.0, 0.5],
    }),
    zIndex: 1000,
});

export const setIconEffect = (feature: Feature, event: any, map: any) => {
    const vectorContext = getVectorContext(event);

    const flashGeom = feature.getGeometry().clone();
    // radius will be 5 at start and 30 at end.
    // set a different/injected style.. OR, a default one

    const style = style1; // (or style2)
    vectorContext.setStyle(style);
    vectorContext.drawGeometry(flashGeom);
    map.render();
};
```

**Comment by danvc** [comment]
Thank you for your help @mike-000 but I've tried this approach and it, in fact, didn't work for me. I've tried to create the style in a different context in order to be injected while calling the function, something like:

```
const styleDiff = new Style({
    image: new Icon({
        src: 'assets/images/mapElements/warning-icon.png',
        scale: 0.1,
        imgSize: toSize(500),
        anchorOrigin: IconOrigin.BOTTOM_RIGHT,
        anchor: [1.8, 0.05],
    }),
});

export const setIconEffect = (feature: Feature, event: any, style: any, map: any) => {
    const vectorContext = getVectorContext(event);

    const myStyle = style;
    const flashGeom = feature.getGeometry().clone();
    vectorContext.setStyle(myStyle);
    vectorContext.drawGeometry(flashGeom);
    map.render();
};
```

**Comment by mike-000** [comment]
If the style is not being used anywhere else you will need to force a load of the image

const styleDiff = new Style({
    image: new Icon({
        src: 'assets/images/mapElements/warning-icon.png',
        scale: 0.1,
        imgSize: toSize(500),
        anchorOrigin: IconOrigin.BOTTOM_RIGHT,
        anchor: [1.8, 0.05],
    }),
});
styleDiff.getImage().load();

https://codesandbox.io/s/blue-grass-7grh7?file=/main.js

**Comment by danvc** [comment]
Thank you again @mike-000 . May I buy you a 🍺? 😃
