### ISSUE TITLE
Angular | on map click event redirect error in openlayers library

### ISSUE THREAD

**Issue by CedricBojoly** [openlayers/openlayers#11541]
**Describe the bug**
If i click on a marker and then redirect the user to a another angular route an error is thrown in the console.

Error screenshot: [https://github.com/CedricBojoly/openlayers-angular-redirect-bug/blob/master/src/assets/console-error.png?raw=true](https://github.com/CedricBojoly/openlayers-angular-redirect-bug/blob/master/src/assets/console-error.png?raw=true)

**To Reproduce**
1. clone https://github.com/CedricBojoly/openlayers-angular-redirect-bug
2. start application with ng serve --aot
3. Follow instructions in HTML

**Expected behavior**
No error

**Comment by ahocevar** [comment]
It is always a good idea to decouple OpenLayers event handlers from Angular's default zone handling. Does the error go away when you change your event handler function to
```js
  this.map.on('click', (evt) => {
    this.ngZone.runOutsideAngular(() => {
      const feature = this.map.forEachFeatureAtPixel(evt.pixel, (feat, layer) => {
        // you can add a condition on layer to restrict the listener
        return feat;
      });

      if (feature) {
        this.router.navigateByUrl('/page-after-marker-click');
      }
    });
  });
}

**Comment by CedricBojoly** [comment]
> It is always a good idea to decouple OpenLayers event handlers from Angular's default zone handling. Does the error go away when you change your event handler function to
> 
> ```js
>   this.map.on('click', (evt) => {
>     this.ngZone.runOutsideAngular(() => {
>       const feature = this.map.forEachFeatureAtPixel(evt.pixel, (feat, layer) => {
>         // you can add a condition on layer to restrict the listener
>         return feat;
>       });
> 
>       if (feature) {
>         this.router.navigateByUrl('/page-after-marker-click');
>       }
>     });
>   });
> ```

Thanks! Running the code outside of the Angular zone fixed the issue.

**Comment by CedricBojoly** [comment]
I'm not sure if this is the final fix or if openlayers should change there code. In a older version of openlayers my code worked great without running it outside of the Angular zone.

**Comment by ahocevar** [comment]
#11549 avoids the reported error message when the map is detached from the DOM or Shadow DOM.
