### ISSUE TITLE
The className setting in ol.layer.HeatMap does not work

### ISSUE THREAD

**Issue by yiwenzhang666999** [openlayers/openlayers#11542]
When I customize the className of the heatmap, it does not work, and the default className is not displayed on the page
![heatMap](https://user-images.githubusercontent.com/31643589/92585825-0a651880-f2c8-11ea-9adf-55d90ee18ede.png)

**Comment by jahow** [comment]
Indeed, this is an undocumented limitation. Thanks for reporting.
