### ISSUE TITLE
TileWMS source getTileUrlFunction can not be called outside OL

### ISSUE THREAD

**Issue by keepitrealsimple** [openlayers/openlayers#11547]
**Describe the bug**
TileWMS source getTileUrlFunction can not be called from application code. Gives error 'this is undefined'. This used to work with v6.3.1 but since v6.4.0 is broken. Can be fixed by binding function to source manually. See attached code sample.
[ol-tilewms-bug.zip](https://github.com/openlayers/openlayers/files/5199551/ol-tilewms-bug.zip)

**To Reproduce**
1. Open attached html
2. Check console to see error

**Expected behavior**
Function should be callable from application code without manual binding.

**Comment by ahocevar** [comment]
Thanks for reporting this. See #11548 for a fix.

**Comment by keepitrealsimple** [comment]
That was fast. Thank you!
