### ISSUE TITLE
hasFeatureAtPixel not detecting features since OL 6.4.3

### ISSUE THREAD

**Issue by hdlol** [openlayers/openlayers#11550]
hasFeatureAtPixel not detecting features with negative scale since OL 6.4.3. 
It works with OL 6.4.2.

hasFeatureAtPixel only detects features with icon having a positive scaleX, but not detecting features with icon having a négative scaleX (vertical flip).

**Comment by M393** [comment]
See #11394, should be fixed by #11401 
As a workaround you can try setting a very small rotation until the next version is released.
