### ISSUE TITLE
When add a mapbox-gl-js layer in an openlayers map, it didn't response mouse event

### ISSUE THREAD

**Issue by TsanChao** [openlayers/openlayers#11551]
I use the demo like this:
https://openlayers.org/en/latest/examples/mapbox-layer.html#
![image](https://user-images.githubusercontent.com/10399848/92901341-fdc0fb80-f452-11ea-9c6c-1ca3a62a5536.png)

when add a mouse move event,  hope the '11111' to print but it didn't work
![image](https://user-images.githubusercontent.com/10399848/92901557-2812b900-f453-11ea-8e97-9393d2ba4ede.png)

**Comment by mike-000** [comment]
When one map is controlling another I think it is correct that the controlled map should not respond directly to user actions.  The user interaction is via the controlling OpenLayers map and its pointermove event should be used instead.

**Comment by wang10705** [comment]
> When one map is controlling another I think it is correct that the controlled map should not respond directly to user actions. The user interaction is via the controlling OpenLayers map and its pointermove event should be used instead.

but openlayer don't get mbLayer data,can't  interactive. so we can ......

**Comment by jahow** [comment]
The Mapbox map is created underneath the OpenLayers map, so it cannot be reached by user input events. This example is _experimental_ and not supposed to be the official, supported way of showing vector tiles.
