### ISSUE TITLE
Allow cancelling pending loading tiles

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#11552]
**Is your feature request related to a problem? Please describe.**

Sometimes a user will misconfigure a layer and the loading tiles hang for a long time (sometimes over a minute before a timeout occurs). When they see it's not loading they turn the layer off, change settings and try again. However, all those pending loading tiles can prevent new tiles from being loaded. I need a way to cancel the previous ones.

**Describe the solution you'd like**

Add a method to either `ol/source/UrlTile` or `ol/layer/Tile` to cancel pending requests.

**Comment by ahocevar** [comment]
The tile queue takes care of cancelling pending requests. But once a tile has started loading, it either has to finish loading or abort with an error to release the slot in the tile queue. You can control that behavior with custom tile load functions. You could, for instance, use a custom tile load function that stops trying to load a tile when the request does not complete within 5 seconds.

**Comment by vincentblandin** [comment]
> The tile queue takes care of cancelling pending requests. But once a tile has started loading, it either has to finish loading or abort with an error to release the slot in the tile queue. You can control that behavior with custom tile load functions. You could, for instance, use a custom tile load function that stops trying to load a tile when the request does not complete within 5 seconds.

Hi! Would you have an example of how to do this?
