### ISSUE TITLE
Disable Box inside OverViewMap

### ISSUE THREAD

**Issue by xdursoc** [openlayers/openlayers#11567]
**Describe the bug**
It is impossible to disable the overview-box in the OverViewMap (OM)

**Expected behavior**
The ability to set an option to disable the box inside the OM.

**Comment by mike-000** [comment]
If you mean prevent it being dragged you can enable/disable pointer-events in css or in JavaScript, for example

```
document.getElementsByClassName('ol-overviewmap-box')[0].style.pointerEvents = 'none';

document.getElementsByClassName('ol-overviewmap-box')[0].style.pointerEvents = 'auto';

```
