### ISSUE TITLE
Keyboard zoom does'tt work on chrome 

### ISSUE THREAD

**Issue by th30d0r** [openlayers/openlayers#11562]
KeyboardZoom doesn't work on Chrome as the check for which key is pressed fails ( (charCode == '+'.charCodeAt(0) || charCode == '-'.charCodeAt(0)))  ) as for any key pressed the charCode is 0. I would suggest using the same check as for KeyboardPan -> keyEvent.keyCode. Also I see that charCode is getting deprecated 
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode#:~:text=The%20charCode%20read%2Donly%20property,Use%20the%20key%20property%20instead.

**Comment by M393** [comment]
The keyboard zoom does work in this example: https://openlayers.org/en/latest/examples/accessible.html
Maybe you have not set a tabindex?

`'+'.charCodeAt(0)` returns the charCode for the first character in the string, 43 in this case.
