### ISSUE TITLE
Cannot find name 'GeolocationPositionError' in @types/ol

### ISSUE THREAD

**Issue by tomgruszowski** [openlayers/openlayers#11570]
**Describe the bug**
Using Angular 10.1, ol 6.4.3 (same as before update), updated @types/ol from 6.3.x to 6.4.1, using TypeScript 4.0.2

`ERROR in node_modules/@types/ol/Geolocation.d.ts:77:24 - error TS2304: Cannot find name 'GeolocationPositionError'.

77     constructor(error: GeolocationPositionError);`

tsconfig.json has:
`
"target": "es2015",
"module": "es2020",
"lib": ["es2018", "dom"]
`

Had to add a dummy typing for GeolocationPositionError to suppress error.

**Comment by ahocevar** [comment]
This is an issue with the `@types/ol` package, which is not maintained by OpenLayers. Please report this issue to https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by tomgruszowski** [comment]
@ahocevar is the types/ol not originally maintained in another repo then just pulled into definitley typed?

**Comment by ahocevar** [comment]
I don't know @tomgruszowski. Maybe it's maintained in https://github.com/hanreev/types-ol.

**Comment by tomgruszowski** [comment]
Looks like it, thank you.
