### ISSUE TITLE
SVG ImageStatic poor performance in chrome

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#11581]
SVG images bigger than 3-4MB in ImageStatic have poor performance in Chrome during panning and zooming. Firefox works better but you can feel poor performance during zooming as well.

Example: 
https://codesandbox.io/s/bing-maps-forked-vvssd?file=/index.js

Chrome:
![chrome](https://user-images.githubusercontent.com/3100059/93878261-11355780-fcda-11ea-94ec-3a9c6997c793.gif)

Firefox:
![firefox](https://user-images.githubusercontent.com/3100059/93878550-8c970900-fcda-11ea-9b6c-458034679d8f.gif)

**Comment by M393** [comment]
Seems like Firefox caches the svg pixels in some way. 
You could render the svg to a canvas to get better performance: https://github.com/openlayers/openlayers/issues/11133#issuecomment-638987210

**Comment by MichalK6677** [comment]
I need floor plans for buildings. They should be basically a part of map added manually by users. Floor plans can be rotated and must be resized with zoom (smaller with zoom out and bigger with zoom in). I've been using ImageStatic and thought it's the best choice for my screnario and it's a part of canvas. 

Do you think using ol.Feature (from your example) is a better choice for my scenario?

**Comment by M393** [comment]
If you need to scale the image with the map, it's probably not a good idea.
Drawing such huge svgs is slow, you'd need to rasterize it in some way to get better performance.
