### ISSUE TITLE
select.getFeatures().clear() takes a very long time to complete

### ISSUE THREAD

**Issue by bojanbizjak** [openlayers/openlayers#11582]
**Describe the bug**
The time taken by the select.getFeatures().Clear() function grows exponentially with the number of objects:
- 1000 (1s)
- 10000 (3s)
- 30000 (>120s)

If the layer is visible or not the execution time is the same. No events are attached to select or features collection.
All features shares same style instance via same styleFunction.

**To Reproduce**
Select 1000, 10000 and 30000 features and use select.getFeatures().Clear()

**Expected behavior**
select.getFeatures().Clear() should be completed within a reasonable time.

**Comment by ahocevar** [comment]
Out of curiosity, how are you selecting 30000 features with a `Select` interaction?

In order to help, you'd have to provide more context from your code. It is likely that a listener connected to the `clear()` operation takes a long time to execute.

**Comment by bojanbizjak** [comment]
Probably such a large selection of features is not the most appropriate so we do not consider this as an OL error,
therefore, you can close the issue.

The selection is made with the "polygon selection tool". 
You can test by using VectorLayer and then use select.getFeatures().push(ftr).

**Comment by bojanbizjak** [comment]
In case there is only one interaction.select, is it really necessary to check in which interaction.select the Feature is located,
because slow operation is caused by the function interaction.getFeatures().GetArray().IndexOf (feature) !== -1.

![restorePS](https://user-images.githubusercontent.com/12731463/94358774-7e166c00-00a3-11eb-8154-84d46e130086.png)
https://github.com/openlayers/openlayers/blob/246aded8192391bbeb9034dbf260e84e0f9d58a3/src/ol/interaction/Select.js#L393

It might make sense to optimize the code so that this test is performed only when there are multiple interaction.select.

**Comment by ahocevar** [comment]
Thanks for investigating this! Would you be able to provide a pull request with such an optimization? That would be great.

**Comment by bojanbizjak** [comment]
I do not have the environment setup to test changes. Would be possible for someone else to make the changes.

If I relate to https://github.com/openlayers/openlayers/pull/1069, my suggestion is something in this direction (not tested):


```
 /**
   * @param {import("../Feature.js").default} feature Feature
   * @private
   */
  restorePreviousStyle_(feature) {
    const key = getUid(feature);
    const selectInteractions = /** @type {Array<Select>} */ this.getMap()
      .getInteractions()
      .getArray()
      .filter(function (interaction) {
        return interaction instanceof Select && interaction.getStyle();
      });
    
    if (selectInteractions.length > 1) {
       const selectInteractionsLenght = selectInteractions.filter(function (interaction) {
         return interaction.getFeatures().getArray().indexOf(feature) !== -1;
       }).length;
      
      if (selectInteractionsLenght > 0) {
        feature.setStyle(
          selectInteractions[selectInteractionsLenght - 1].getStyle()
        );
        
        return;
      }
    }
    
    feature.setStyle(originalFeatureStyles[key]);
    delete originalFeatureStyles[key];
  }
```
