### ISSUE TITLE
Text alignment wrong for start and end

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#11586]
**Describe the bug**
`start` and `end` text-align are swapped.
https://github.com/openlayers/openlayers/blob/705e328fa096ee3f63fa3c609e55a32315c50c0e/src/ol/render/canvas/TextBuilder.js#L31-L36
**To Reproduce**
1. Copy+paste the data url to get a test page (CTRL + U to view source):
`data:text/html;base64,PCFET0NUWVBFIGh0bWw+CjxodG1sPgo8aGVhZD4KCTx0aXRsZT5UZXh0IGFsaWdubWVudDwvdGl0bGU+Cgk8bWV0YSBjaGFyc2V0PSJVVEYtOCIgLz4KPC9oZWFkPgo8Ym9keT4KCTxkaXYgc3R5bGU9InRleHQtYWxpZ246IGxlZnQiPmxlZnQ8L2Rpdj4KCTxkaXYgc3R5bGU9InRleHQtYWxpZ246IHN0YXJ0Ij5zdGFydDwvZGl2PgoJPGRpdiBzdHlsZT0idGV4dC1hbGlnbjogcmlnaHQiPnJpZ2h0PC9kaXY+Cgk8ZGl2IHN0eWxlPSJ0ZXh0LWFsaWduOiBlbmQiPmVuZDwvZGl2Pgo8L2JvZHk+CjwvaHRtbD4=`
2. Compare the start / left and end / right values in the page with the code in the `TEXT_ALIGN` enum and / or this example:
https://openlayers.org/en/main/examples/vector-labels.html  

**Expected behavior**
The start should be to left, end to the right, at least for normal ltr text which is the default.

**Comment by ahocevar** [comment]
Reversing this was intentional in the old (now removed) WebGL renderer, and it was meant for specifying start and end in RTL environments. Ideally, `start` and `end` would respect the LTR/RTL setting and behave accordingly.

**Comment by MoonE** [comment]
I don't see how one can specify the text direction currently. Would the be declared by css on the map target?

**Comment by ahocevar** [comment]
I *think* we advised users to do that, yes.
