### ISSUE TITLE
Upside-down text with placement: line

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#11584]
**Describe the bug**
Upside down text with `placement:  'line'`

**To Reproduce**
1. Go to https://codesandbox.io/s/line-placement-upside-down-text-wwu5z?file=/src/index.js
2. The text is upside down

**Expected behavior**
The text should be upright for better legibility.

The check if it should be reversed uses the begin and end of the entire possible placement path instead of only the section where the text is being placed. https://github.com/openlayers/openlayers/blob/705e328fa096ee3f63fa3c609e55a32315c50c0e/src/ol/geom/flat/textpath.js#L54
To get the correct result it should check the first x1 and last x2 (which would need to be calculated beforehand).
https://github.com/openlayers/openlayers/blob/705e328fa096ee3f63fa3c609e55a32315c50c0e/src/ol/geom/flat/textpath.js#L74-L82

**Comment by ahocevar** [comment]
Thanks for reporting this @M393. Would you be able to create a pull request with your suggested fix?
