### ISSUE TITLE
Add support for DZI format

### ISSUE THREAD

**Issue by abhijitgujar86** [openlayers/openlayers#11589]
https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format

DZI format is used for loading non georeferenced images. such as microscope slides. It will be great addition that will enable user to use openlayers beyond GIS . just like zoomify.

**Comment by mike-000** [comment]
It can be done by parsing the dzi file and creating a Zoomify layer.  This is an old example from StackOverflow updated to OL6 https://jsfiddle.net/ozvxsn7p/3/
