### ISSUE TITLE
please correct the Wrong pages in workshop 

### ISSUE THREAD

**Issue by csdallen** [openlayers/openlayers#11583]
I learn to use openlayers by the workshop:
https://openlayers.org/workshop/en/

But there are some wrong pages which misguide me for a long time.
I find that someone discovers them and they were correctted in github,but not in official site "www.openlayers.org".
Look the details here: https://github.com/openlayers/openlayers/issues/11083. The error appears in some pages like "https://openlayers.org/workshop/en/webgl/points.html"

So, is there anyone could fix it?

**Comment by ahocevar** [comment]
Latest workshop from the default branch released as v6.0.0-beta.en.3 and deployed.

**Comment by csdallen** [comment]
> Latest workshop from the default branch released as v6.0.0-beta.en.3 and deployed.

Thank you,but I found the workshop in _https://openlayers.org/workshop_, so I thought it is v6.4.3 which synchronizes with the code.
on the website on the website _https://openlayers.org/_ , there is no descriptions to indicate the vision of workshop,so this maybe  confuses users.

**Comment by ahocevar** [comment]
If you actually work through the workshop, the section [Setup](https://openlayers.org/workshop/en/#setup) of the introduction points you to the release page to download the [latest workshop release](https://github.com/openlayers/workshop/releases), which is 6.0.0-beta.en.3 at the time of writing.

But you are right, adding the version from package.json to the GitBook outbook, e.g. as footer of the navigation bar, would make sense. A pull request would be welcome. The workshop repository is https://github.com/openlayers/workshop/. Also, if anyone wants to update the workshop to the latest version of the library, a pull request would be welcome.
