### ISSUE TITLE
Attribution control does not return to collapsible when no attributionsCollapsible: false sources are visible

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11595]
**Describe the bug**
Unless collapsible is specified for the control it should be collapsible when no `attributionsCollapsible: false` sources are visible.  However it does not reset when all such layers are hidden or removed.

**To Reproduce**
See the Raster Reprojection example.  When the OSM layer is replaced by WMS the attributions should be collapsible, but are not.  If the example is changed to open with the WMS layer the attributions are collapsible, then if the OSM layer is the used the attributions become non-collapsible as expected, but switching the layers back again has no effect.

**Expected behavior**
The process should be reversible.

**Comment by ahocevar** [comment]
If you see a way to achieve this without a significant amount of additional code, a pull request would be welcome.
