### ISSUE TITLE
Allow modify interaction to modify only one of several features at a time

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#11608]
**Is your feature request related to a problem? Please describe.**
Currently the Modify interaction will modify more than one vertex if
- multiple Features have the same coordinates
- a new vertex is inserted on identical segments of the same / different geometries (That might be classifiable as a bug)

**Describe the solution you'd like**
If multiple lines geometries share a corner, I would like it to only modify one of the features at a time or allow a callback function to filter which will be modified.

**Comment by ahocevar** [comment]
I agree that the latter is a bug. The former can easily be achieved by setting only the feature you're modifying in the interaction's `source` or `features`.

**Comment by M393** [comment]
Thanks for your reply, @ahocevar 
I do want to allow the user to modify multiple features, but only one at a time, how can I achieve that?

**Comment by ahocevar** [comment]
> I do want to allow the user to modify multiple features, but only one at a time, how can I achieve that?

One way would be to let the user click the feature they want to modify before actually modifying it. That way there won't be any surprises, especially if you highlight the feature that is currently being modified.

**Comment by M393** [comment]
Thanks, @ahocevar, this will do fine.
