### ISSUE TITLE
GeoJson writeFeatures fails with "Unimplemented abstract method."

### ISSUE THREAD

**Issue by FrankyBoy** [openlayers/openlayers#11615]
Code that triggers this behavior (shortened)

```
let elevations = [
    [1735244.8829008248, 6174215.452648275, 197], // x / y / z in ESPG 3857
    [1735259.0098037624, 6174257.1732492745, 197],
    [1735223.2826494721, 6174288.264404694, 197];

let feature = new Feature(new LineString(elevations));
let options = {dataProjection: "EPSG:3857", featureProjection: "EPSG:3857"};
let result = new GeoJSON().writeFeatures([feature], options); // this throws an exception
```

Exception stack trace:
```
vue.runtime.esm.js?2b0e:1888 Error: Unimplemented abstract method.
    at eval (util.js?1300:9)
    at abstract (util.js?1300:10)
    at JSONFeature.writeFeaturesObject (JSONFeature.js?377d:161)
    at JSONFeature.writeFeatures (JSONFeature.js?377d:152)
    at [my code ...]
```

The same works if I export to GPX (i.e. literally only difference is `new GPX()` instead of `new GeoJSON()`)

E: fix typo in code that happened when shortening it

**Comment by mike-000** [comment]
It is working here.  https://codesandbox.io/s/admiring-meitner-ofctg?file=/main.js
Are your imports correct?  Which version are you using?

**Comment by FrankyBoy** [comment]
Aaaaah damn it, the IDE messed up the import and I didn't spot it (for some reason it did `import GeoJSON from "ol/format/JSONFeature";`). What a fail. Thanks for asking the obvious questions, I'll go facepalm myself now.
