### ISSUE TITLE
Flickering points when decluttering points with empty text style

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#11619]
**Describe the bug**
Points with a fill / stroke and a text style with empty text flicker when the map is moved

**To Reproduce**
1. Go to https://codesandbox.io/s/declutter-points-with-empty-text-style-3z9ne?file=/main.js
2. Move the map
3. The points are only drawn some frames thus creating a flicker.
I suspect that the points may be drawn twice every other frame in this case. It can be seen sometimes when the map is moved around.

**Expected behavior**
An empty text for the text style should behave the same as no text style.

**Comment by ahocevar** [comment]
Does this also happen with #11592?

**Comment by MoonE** [comment]
Yes it does.

**Comment by ahocevar** [comment]
So empty text should probably be treated like no text style at all, which would mean a change in the TextBuilder I guess. Would you feel comfortable providing a pull request, @MoonE?

**Comment by MoonE** [comment]
Fixed with #11592
