### ISSUE TITLE
After upgrade to 6.4.3 Layers do not show

### ISSUE THREAD

**Issue by RobertVogt** [openlayers/openlayers#11610]
Attempting to upgrade from OL version 5 to OL 6.4.3.
I ran npm install ol@6.4.3.
After the upgrade the map and layers no longer appears to load.

I am using this with Angular 7.3.7

The above are the steps I took to see this problem

**Expected behavior**
I expected to see the map I built over the last year and it's layers

**Comment by M393** [comment]
Have a look at the upgrade notes for all the versions between 5 and 6.4.3, especially the 6.0.0 release.
https://github.com/openlayers/openlayers/releases/tag/v6.0.0
https://github.com/openlayers/openlayers/releases
