### ISSUE TITLE
custom (my handle) tile in version 6-4-3 is not working

### ISSUE THREAD

**Issue by 1000kw** [openlayers/openlayers#11611]
I have create tile source   
  var kmlSource = new ol.source.VectorTile(
        {
            //format: new ol.format.GeoJSON(),
            tileLoadFunction: myTileFunction,
            url: 'kml_' + feature.idLocation // arbitrary url, we don't use it in the tileLoadFunction
        }
    );

and in my tile Function i set features in tile. Features i take from my base. Can to answer - Whey tile function work only one time,

**Comment by simonseyock** [comment]
Hey, this kind of question might be better suited for stackoverflow, but did might need to call `setLoader` inside of your tile to have it called multiple times. If you are sure this is a bug, please provide some more code and idealy a fiddle on codesandbox. You can use https://openlayers.org/en/latest/examples/mapbox-vector-tiles-advanced.html as a starting point and click on edit in the upper right corner to immediately start a new codesandbox.

**Comment by 1000kw** [comment]
it happens when function  parameter url not change/ If url parameter change all working.  An it provide other problem —  not enouf memory/ In version 4 openlayers such not been

**Comment by simonseyock** [comment]
Can you provide a reproduction of the bug on https://codesandbox.io ?

**Comment by 1000kw** [comment]
I can connect you to my computer via anydesc remote viewer And via whatsup you will show where openlayers have problem.
I have a lot data and code for sandbox

**Comment by simonseyock** [comment]
I am sorry but I would not want to do this. Can you provide just a minimal example where this problem occurs? That means **only** the code that is necessary to reproduce this. No extra code around it. You can use https://openlayers.org/en/latest/examples/mapbox-vector-tiles-advanced.html as a starting point and click on edit in the upper right corner to immediately start a new codesandbox.
