### ISSUE TITLE
LayerSwipe for GroupLayers

### ISSUE THREAD

**Issue by kesslerf** [openlayers/openlayers#11625]
Hey Guys,
I tried to use GroupLayers (Basemap + overlying rasters) but it did not work. Would it be possible to add this option?  Or is it already possible but I am just to dumb to do it? 

Thank you!

**Comment by mike-000** [comment]
Layer groups do not have prerender and postrender events, The individual layers in a group need to be handled https://codesandbox.io/s/quizzical-water-bhuei?file=/main.js

**Comment by kesslerf** [comment]
Thanks for the code and explanation!
