### ISSUE TITLE
TileImage/tileLoadFunction: (slow) sequentially tile loading / pause between tileloadend/start

### ISSUE THREAD

**Issue by mst2020** [openlayers/openlayers#11626]
Hello!

I'm not sure if this is a bug or i'm the first one who cares about that. :)

**Describe the bug**
When loading tiles with **tileLoadFunction**, there is a variable "pause" between two tiles (**tileloadend** and the next **tileloadstart**).
And because the tiles are loaded sequentially, it takes "too long" to render a layer.

I googled a lot and didn't find an answer or how i can change this behavior.

**To Reproduce**
See console output on https://jsfiddle.net/hdkpvrac (zoom in)
my browser: _Chrome/85.0.4183.123_

```
[3, 8, 9], 1601925605154, "tileloadstart"
[3, 8, 9], 1601925605154, "tileloadend"
"pause was (ms)", 41
[3, 8, 10], 1601925605195, "tileloadstart"
[3, 8, 10], 1601925605195, "tileloadend"
"pause was (ms)", 27
[3, 8, 11], 1601925605222, "tileloadstart"
[3, 8, 11], 1601925605223, "tileloadend"
"pause was (ms)", 23
[3, 8, 12], 1601925605246, "tileloadstart"
[3, 8, 12], 1601925605247, "tileloadend"
"rendercomplete, pause sum (ms)", 710
```

Sure, you could say that's not that much, but if you have multiple layers with many tiles, it adds up to a non user-friendly behavior.

**Expected behavior**
- Faster tile loading. :)
- There should'nt be a pause between two tiles (?)
- async/concurrent **tileloadstart**

Thanks for your time. :)

**Comment by ThorsteinnHelgi** [comment]
I've seen this too. Needs fixing

**Comment by ahocevar** [comment]
OpenLayers uses a per-map tile queue, with a default total of 16 parallel tile loads. If you have a few layers that load slowly, the tile queue will be saturated so other layers won't load fast.

You can configure the map with a higher value for `maxTilesLoading`, e.g.
```js
new Map({
  maxTilesLoading: 256
});
```

**Comment by mst2020** [comment]
> OpenLayers uses a per-map tile queue, with a default total of 16 parallel tile loads. If you have a few layers that load slowly, the tile queue will be saturated so other layers won't load fast.

Thanks for the hint, but this doesn't change anything in my example:
https://jsfiddle.net/1nhw8aec

🤷‍♂️

**Comment by mst2020** [comment]
here is an example which shows the sequential loading behavior in a better way, i hope. :)

https://jsfiddle.net/jh0a1yuw/

Why is the loading queue of openlayers waiting for one tile before triggering the next one, even if the main thread is idle?

The "setTimeout" in the example above returns immediately and i would expect that openlayers proceed with the next one, not blocking the queue. (the main thread is idle ...)

**Comment by ahocevar** [comment]
The problem with your example code is that the url `https://xyz` is the same for all tiles. That url is used as tile unique key for the tile queue. So make sure the tile url is unique for each tile, e.g. by changing it to `https://{z}/{x}/{y}`.

I have applied this change to your example, and also changed your test layer so you can see on the map when a tile is loaded: https://jsfiddle.net/xac3q84n/2/

**Comment by mst2020** [comment]
> So make sure the tile url is unique for each tile, e.g. by changing it to `https://{z}/{x}/{y}`.

Woah, thanks man!

I didn't pay much attention to the "url" because in my case its just a "dummy", "tileLoadFunction()" is doing everything (build an url and request).

Now i'm setting just the "dummy" url to "https://{z}/{x}/{y}" and all the latencys are gone, all "tileloadstart"s are triggered at once.

Did i overseen it in the manual? If not, maybe a hint when using tileLoadFuntion is necessary to avoid such "useless" tickets. 🙈

Thanks!

**Comment by ThorsteinnHelgi** [comment]
Increasing the maxTilesLoading value helped me. Thanks @ahocevar

**Comment by Makio64** [comment]
@ahocevar hello, i m currently using `tileLoadFunction: async (tile, src) => {` and hit the same problem of tiles not getting loaded all at the same time. I read this issue and other related issues but coudnt figured it out.

Is there something else to do than `maxTilesLoading: 256` ? Thanks ! 

<img width="217" alt="Image" src="https://github.com/user-attachments/assets/eb613aae-5842-4cfa-ac23-ab1cf526b9bf" />
