### ISSUE TITLE
Not all spec tests are run

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#11627]
`npm run test-spec` and `npm run karma` do not run all tests locally. It says:

`Executed 497 of 3181 SUCCESS`

A `throw new Error()` in some tests does not do anything. Is there something I need to configure?

**Comment by simonseyock** [comment]
This has something to with my branch. It happens here as well: https://github.com/openlayers/openlayers/pull/11628/checks?check_run_id=1214216334

And it also happens if I remove the new tests. This means that the code changes in `src` are responsible for tests not running. This does not seem to be the desired behaviour of the test runner.

**Comment by simonseyock** [comment]
It does not happen in the main branch locally.

**Comment by simonseyock** [comment]
I pushed a revert of the test directory to the branch and it still skips most tests, even in the CI: https://github.com/openlayers/openlayers/runs/1214605057?check_suite_focus=true

**Comment by ahocevar** [comment]
> This means that the code changes in src are responsible for tests not running. This does not seem to be the desired behaviour of the test runner.

Agreed.

**Comment by simonseyock** [comment]
The error apparently comes from some code execution after `done` is called. I can fix this, but it is really odd that the runner just stops execution and tells that he has succeeded. Maybe I should file this as a bug in karma/karma-runner ?

**Comment by ahocevar** [comment]
Can you elaborate? What change makes the issue go away? It is not unusual that code is executed after done() is called, since many things happen asynchronously. I wouldn't be surprised if the issue comes from the changes in the xhr loader, which *is* asynchronous.

**Comment by simonseyock** [comment]
This happens because of the following lines: https://github.com/openlayers/openlayers/blob/fed74c6cf71aab497914d46e43166a78d92e1406/src/ol/featureloader.js#L155-L158

addFeatures triggers the 'addfeature' which then calls done. The call of success triggers the 'featureloadend' event - but not much more.

**Comment by simonseyock** [comment]
If the lines are reversed or `done` is called in a `setTimeout` all tests run.

**Comment by ahocevar** [comment]
This is indeed a strange behavior. Not sure if this is a test runner problem. Let's leave this open for now.

**Comment by marcjansen** [comment]
Can you return a promise? Som test suites deal with that.

**Comment by simonseyock** [comment]
The problem is that the code that is executed internally in openlayers after the success function somehow makes the test runner crush in a way that it does not even report it as an error.

**Comment by marcjansen** [comment]
Ping @simonseyock, is this still an issue?
