### ISSUE TITLE
tablet issue with certain code compilation

### ISSUE THREAD

**Issue by olsinao** [openlayers/openlayers#11633]
I noticed this example:
https://openlayers.org/en/latest/examples/es2015-custom-element.html

doesn't work with Android tablet / Firefox and potentially iPad browsers. It does work in Chrome on Android tablet. It works on mobile and desktop.

Which may be similar to another issue I am experiencing with tablet users. My approach used to work prior to the 6.4.3  update; now it doesn't work with any 6.x.x release, but does work with 5.x.x version.

When I compile this code:

`
import 'ol/ol.css';
import Map from 'ol/Map';
import View from 'ol/View';
import XYZ from 'ol/source/XYZ';
import Tile from 'ol/layer/Tile'; 

export class props2 {
    public  map : Map | null = null;
    public  init() {
      this.map = new Map({
        target: 'map',
        layers: [
          new Tile({
            source: new XYZ({
              attributions: 'Copyright:© 2013 ESRI, i-cubed, GeoEye',
              url:
                'https://services.arcgisonline.com/arcgis/rest/services/' +
                'ESRI_Imagery_World_2D/MapServer/tile/{z}/{y}/{x}',
              maxZoom: 15,
              projection: 'EPSG:4326',
              tileSize: 512, // the tile size supported by the ArcGIS tile service
              maxResolution: 180 / 512, // Esri's tile grid fits 180 degrees on one 512 px tile
              wrapX: true,
            }),
          }) ],
        view: new View({
          center: [0, 0],
          projection: 'EPSG:4326',
          zoom: 2,
          minZoom: 2,
        }),
      });
    }
  }

window.onload = () => {
    var p = new props2();
    p.init();
}
`

and run parcel, it will work as long as props2 class is in the same folder as the window onload code.

However, if I move the props2 class into another folder; the compilation still works, phones and desktops still work, but tablets are frozen (can't pan / zoom).

so something like /props2/

`import { props2 } from "../project2/props2";
window.onload = () => {
    var p = new props2();
    p.init();
}
`
package.json has:
`"dependencies": {
    "@types/ol": "^6.4.1",
    "ol": "^6.4.3"
  },
  "devDependencies": {
    "typescript": "^3.9.7"
  }`

So was there some class definition / library change update that could case this behavior?
Oddly enough, it only impacts tablets! (to my knowledge)

Thank you!

**Comment by ahocevar** [comment]
For the above example to work, your browser needs to support `ShadowRoot`. See "Browser Compatibility" on https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot.

**Comment by olsinao** [comment]
I don't declare ShadowRoot anywhere in my code. Does ShadowRoot reference gets included by compiler?

The code snippet I provided is very simple, yet when loaded from a separate folder, it has issue on tablets only.



________________________________

**Comment by olsinao** [comment]
Just wanted to add.
This seems to be definitely and issue with 6.4.x version. I finally figured out how to get 6.3.1 back and while it is a bit flaky - panning and zoom is sluggish but it still works. However with 6.4.3, the map is completely frozen. (tablets)

My guess is there some conflict with touch vs mouse events?


Thanks

________________________________

**Comment by ahocevar** [comment]
Ok, that means you need to include a Pointer Events polyfill in your build, because OpenLayers does not ship with one since v6.4.0. See the [README](https://www.npmjs.com/package/ol#supported-browsers) or the [upgrade notes](https://github.com/openlayers/openlayers/releases/tag/v6.4.0) for instructions.
