### ISSUE TITLE
Updated OpenLayers on NuGet

### ISSUE THREAD

**Issue by birbilis** [openlayers/openlayers#11637]
Seems NuGet package for OpenLayers is left back at 4.x. There was a 6.1 NuGet but it seems to have been deleted

maybe these are useful in case on wants to make a newer version:
https://docs.microsoft.com/en-us/previous-versions/bb398930(v=vs.140)?redirectedfrom=MSDN
https://docs.microsoft.com/en-us/previous-versions/dd410060(v=vs.140)
https://docs.microsoft.com/en-us/previous-versions/3hc29e2a(v=vs.140)

I would be content even with a NuGet that transparently loads releated .js/.css from CDN to ease usage of OpenLayers

**Comment by tschaub** [comment]
The OpenLayers project does not maintain (or have any affiliation with)  https://www.nuget.org/packages/OpenLayers/ .  It looks like there is a “contact owners” link on that website.  I’d encourage you to contact the owners with your request.

**Comment by ahocevar** [comment]
As far as I know, we never published official packages to NuGet. Would it be possible for you to use the official [npm package](https://npmjs.com/package/ol) instead?

**Comment by birbilis** [comment]
thanks, was confused cause that pages was writing "OpenLayers Team" on the sidebar
