### ISSUE TITLE
Problem with making a 'print screen' of the map

### ISSUE THREAD

**Issue by jmekaelthas** [openlayers/openlayers#11638]
**Descrption**
In previous versions of openlayers rendering a map to an image was pretty simple.
`map.once('postcompose', function(evt) {
    // here you could get an image from evt.context ...
});
map.renderSync();
`

In one of the versions this was changed as evt.context is no longer available.
So I found a work around to this problem (as I could not find any other way to render the map to an image).
My solution was simple: find all html canvases that the map is rendered on and render their image on another image.
And this used to work fine utill I added a wms layer from other source than the origin of the website.

I have no power over the WMS server so no crossOrigin setting will help me here. But the thing is, that the WMS layers that are displayed, render themselves on canvases used for layers rendered from the site origin and thus: tainting them.

I added a cssClass to every external WMS layer I add to map. I thought it would force the layer to use one canvas with this css. Unfortunately the WMS layers tend to taint other canvases, even though they should render themselves on canvas with the specified css. But unfortunately they don't.

In my case, the css class, is only used to mark the layer somehow, but if the css changed how the canvas looks for specified layers, this might display the layer in a wrong way.

**Expected behavior**
The layers are rendered only on canvases with a css class specified for the layer.

**Additional question**
Is there a way to render the map to the image?

**Comment by mike-000** [comment]
The WMS layer is rendered on a separate canvas here https://codesandbox.io/s/fervent-bhaskara-48ho7?file=/main.js but you need to combine the canvases to export them.  To avoid tainting the final canvas you would need to check if the canvas you are adding is tainted.  Comment out the `crossOrigin: ''` and the map will still export, but without the tainted WMS layer.

**Comment by jmekaelthas** [comment]
From what I have seen, the WMS layer can render itself on a canvas used by another sources (vectors for example). I have had a single WMS and it was drawn along with other layers. I can of course skip the tainted canvas, but this way I will skip rendering a whole bunch of layers that I need on my image.

Turning off the WMS layer before the printing does not help because the canvas is still tainted.

I know that openlayers area making some optimisations to use as few canvases as possible, but I see it as a bug here.
As I have written, I marked the layers with a css class and I expected that they will be rendered only on canvases enclosed in div's with this css. But unfortunately they can skip out of it and render themselves on other canvases ignoring the css setting.

**Comment by mike-000** [comment]
Layers with the same className will be rendered on the same canvas where possible (whether it is possible depends on the layer type and view rotation).  To ensure other layers are not tainted the layer which does not support CORS should have its own unique className.

**Comment by jmekaelthas** [comment]
OK turned out it was my mistake with applying proper css class name to some layers.
I am adding special hidden layers that area groupping the WMS requests so that those layers are rendered faster.
I did not add the proper class name to the grouping layer and that is why it rendered itself on the other canvas than I expected.

So sorry, my bad :)
