### ISSUE TITLE
foreachFeatureAtPixel not working as expected for image marker

### ISSUE THREAD

**Issue by dagognatt** [openlayers/openlayers#11630]
**Describe the bug**
if wanting to detect a pointer-move/click on a feature with image-style, the hitbox of the image does not extend to the extent of the image. This is regardless of rotation, but though scale makes the hitbox larger, it still does not extend to the whole image. 

**To Reproduce**
1. Go to https://codepen.io/dagognatt/pen/XWKWXYB
2. Hover the placeholderimage in the map.
3. Observe as you paint the hitbox of the image, and that it will only hit a smaller rectangle around the coordinate. 

**Expected behavior**
The whole image is expected to hav points drawn over it, as foreachFeatureAtPixel should detect hits all over the image.

**Comment by M393** [comment]
The default `renderBuffer` of a `ol.layer.Vector` is 100 px, for larger images you need to increase it. In your example set it to 350.
