### ISSUE TITLE
Set method is not working for declutter of a vector tile layer.

### ISSUE THREAD

**Issue by mahdin75** [openlayers/openlayers#11634]
**Describe the bug**
I am using OpenLayers version 6. I want to change the declutter of a vector tile layer by using vecTileLayer.set('decluter',false).
After changing the declutter of the layer with the set method of vecTileLayer, My map is not updated and nothing changes.
I asked [a StackOverflow question](https://gis.stackexchange.com/questions/375984/how-to-refresh-vector-tile-layer-after-setting-declutter-in-openlayers-6?noredirect=1#comment614621_375984) and there was no solution for that.
Is there any way to do this in OpenLayers?

**Comment by M393** [comment]
This seems to work, but it is accessing a private property of the layer:
```js
vecTileLayer.declutter_ = true;
vecTileLayer.changed();
```
A PR adding the missing `setDeclutter(declutter)` method with the above code might make sense, unless this causes some problem which I didn't run into when I tried this ...

**Comment by mahdin75** [comment]
@M393 
I used this code and it worked truly.
```
layer.declutter_ = !layer.declutter_;
let source = layer.getSource();
source.refresh()
```

**Comment by egeofalcao** [comment]
Is there a way to setDeclutter()?

**Comment by matthias-ccri** [comment]
Note:for a VectorTileLayer, neither `layer.changed()` nor `layer.getSource().refresh()` work to rerender the vector tiles.
