### ISSUE TITLE
bug getGetFeatureInfoUrl

### ISSUE THREAD

**Issue by muhamadanjar** [openlayers/openlayers#11636]
i have issue when use source tilemws getfeatureinfourl always is not function but i check in console in browser working

```js
let layerWithWmsSource = map.forEachLayerAtPixel(evt.pixel, function (
            layer
        ) {
            let source = layer.getSource();
            if (source instanceof TileWMSSource) {
                return layer;
            }
        });
        console.log(layerWithWmsSource);

if (layerWithWmsSource) {
                $("#popup-content").empty();
                const source = layerWithWmsSource.getSource();
                    getInfo(evt, layerWithWmsSource);
            }

function getInfo(evt, layerWms) {
    var resolution = map.getView().getResolution();
    const source = layerWms.getSource();
    console.log(source, evt, resolution);
    const url = source
        .getGetFeatureInfoUrl(evt.coordinate, resolution, "EPSG:3857", {
            INFO_FORMAT: "application/json", 'buffer': 10
        })
}
```

**Comment by mike-000** [comment]
Make sure you are using the correct function name for the version you are using.  Use **getFeatureInfoUrl** in OpenLayers 6
https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html#getFeatureInfoUrl
and **getGetFeatureInfoUrl** in earlier versions
https://openlayers.org/en/v5.3.0/apidoc/module-ol_source_TileWMS-TileWMS.html#getGetFeatureInfoUrl

**Comment by muhamadanjar** [comment]
i'm using openlayers 6.4.3, btw i used webpack

**Comment by ahocevar** [comment]
Then use `getFeatureInfoUrl()`. Note: `get` instead of `getGet`.

**Comment by muhamadanjar** [comment]
okay thanks it works @ahocevar @mike-000
