### ISSUE TITLE
GeoJSON does not convert to WGS84 or specify CRS

### ISSUE THREAD

**Issue by FrankyBoy** [openlayers/openlayers#11631]
Hi! Currently working on geojson export of an elevation track. Code:

```
let feature = new Feature(new LineString(this.elevations)); // elevations being x/y/z in EPSG:3857
let options = {
  dataProjection: "EPSG:3857",
  featureProjection: "EPSG:3857"
};
let outputString = new GeoJSON().writeFeatures([feature], options);
```

Expected: coordinates in `outputString` are converted to WGS84 (the default crs for geojson), or geojson should contain a crs-element specifying EPSG:3857. 

Actual: coordinates are not converted, nor is a crs included.

**Comment by tschaub** [comment]
You should only include the `featureProjection` option.  The documentation for these options could likely be improved.

**Comment by FrankyBoy** [comment]
Aaah so basically dataProjection is the "output format" and featureProjection is the "input format". That makes sense now. Yep those docs could probably be somewhat clearer ;)

**Comment by tschaub** [comment]
> so basically dataProjection is the "output format" and featureProjection is the "input format"

@FrankyBoy - That's right for the `write*` methods.  For the `read*` methods, the "data" is the input and the "feature" is the output.  The same `dataProjection` and `featureProjection` option names are used for the constructor, the write methods, and the read methods - hence some of the awkwardness.

**Comment by FrankyBoy** [comment]
right ... makes sense ^^
