### ISSUE TITLE
How to render a large amount of data (more than 200,000) on a vector layer

### ISSUE THREAD

**Issue by LCLucky** [openlayers/openlayers#11635]
How to render a large amount of data (more than 200,000) on a vector layer?

**Comment by simonseyock** [comment]
Hello LCLucky, please ask usage questions about openlayers on stackoverflow.com . The issues are meant for bugs and features and alike. To answer your question you can look at the `VectorImageLayer`: https://openlayers.org/en/master/examples/image-vector-layer.html
