### ISSUE TITLE
Map export to PNG in Angular when map is rotated 

### ISSUE THREAD

**Issue by digoburigo** [openlayers/openlayers#11647]
**Describe the bug**
Map export to png in Angular when map it's rotated don't reflect the actual view of the map in the png image

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-ivy-ef2yc9?file=src/app/app.component.ts
2. Click on the button "to png" when map it's rotated, you will see a different location in the preview
3. Click on the button "to png" when map it's not rotated, you will see that the png file reflects the current view of the map

**Expected behavior**
I expect the same result when the map it's not rotated

**Comment by mike-000** [comment]
As in https://openlayers.org/en/latest/examples/export-map.html you need to apply the style transform of the layer canvas to the final canvas context before calling drawImage().
