### ISSUE TITLE
Attempted import error: 'ol/extent' does not contain a default export (imported as 'olExtent').

### ISSUE THREAD

**Issue by tomaszs** [openlayers/openlayers#11650]
After making update from 4.6.5 to 5.3.3 - 6.4.3:

```
yarn add ol@5.3.3 @types/ol@5.3.3
```

An error occurs:

```
Attempted import error: 'ol/extent' does not contain a default export (imported as 'olExtent').
```

While olExtend seems to be available

**Comment by M393** [comment]
The error message is correct, there is no default export. To use the methods from ol/extent you can import them like this: `import {getArea, getBottomLeft} from 'ol/extent';`

**Comment by tomaszs** [comment]
Thanks
