### ISSUE TITLE
On clicking zoom buttons DOM click is fired

### ISSUE THREAD

**Issue by VinoSakthi** [openlayers/openlayers#11659]
**Describe the bug**
We have added a click handler to the map in Angular project. on click it will navigate to another page.
On clicking zoom in/out buttons , the click handler is called and navigates to target page. so zoom buttons are useless. 
We first encountered this on May and found this issue thread #10980 so waited for it's release. But still the issue occurs in the latest release
**To Reproduce**
Demo to reproduce the issue [stackblitz demo](https://angular-tkbgum.stackblitz.io) 
Click the zoom buttons  and see the map clicked count is increasing
**Expected behavior**
The zoom buttons click should not be passed on to DOM click.

**Comment by ahocevar** [comment]
The behavior you are encountering is correct, and not related to issue #10980. That issue is not about the DOM `click` event, but the `click` MapBrowserEvent.

The zoom buttons are part of the DOM, so the event you receive is expected. I'd recommend checking `event.target` before performing your page navigation, and only navigate when the target matches the target you're expecting, with something like
```js
  onMapClick($event) {
    if ($event.target.nodeName !== 'BUTTON') {
      this.count++;
    }
  }

**Comment by VinoSakthi** [comment]
Thanks for the quick reply ,  I was not sure whether it a bug or behavior.
Because in open layers 4.6.5 above scenario works fine which we still use in our angular js project .

 I tried first approach and it worked . Second approach would not work for our case since it's displayed inside widget.

**Comment by ahocevar** [comment]
In OpenLayers 4.6.5, we called `stopPropagation()` on the container that holds control buttons. That was changed in #8982 for good reasons.

**Comment by VinoSakthi** [comment]
> In OpenLayers 4.6.5, we called `stopPropagation()` on the container that holds control buttons. That was changed in #8982 for good reasons. So I would say what you are seeing is intended behavior, but we did not document that change properly in the upgrade notes.

@ahocevar  Thank you , I will close this case now
