### ISSUE TITLE
Exception with raster source when zoomed out

### ISSUE THREAD

**Issue by tapioko** [openlayers/openlayers#11656]
**Describe the bug**
When zooming out and the layer gets so small that it's not visible, the following exception is thrown:
Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
    at getImageData
    at RasterSource.push../node_modules/ol/source/Raster.js.RasterSource.processSources_
    at RasterSource.push../node_modules/ol/source/Raster.js.RasterSource.getImage
    at CanvasImageLayerRenderer.push../node_modules/ol/renderer/canvas/ImageLayer.js.CanvasImageLayerRenderer.prepareFrame
    at ImageLayer.push../node_modules/ol/layer/Layer.js.Layer.render
    at CompositeMapRenderer.push../node_modules/ol/renderer/Composite.js.CompositeMapRenderer.renderFrame
    at Map.push../node_modules/ol/PluggableMap.js.PluggableMap.renderFrame_
    at Map.<anonymous>

This happens with ol/layer/Image and ol/source/Raster, but not with ol/layer/Tile and ol/source/TileWMS.

Maybe Raster#getImageData should return null if width or height is zero?

**To Reproduce**
Sorry, no demo.

**Expected behavior**
Nothing is shown on map and there is no exception.

**Comment by ahocevar** [comment]
Thanks for reporting this. Can you provide a working example (e.g. by clicking "Edit" in one of the official [examples](https://openlayers.org/en/latest/examples)) that shows the issue?

**Comment by tapioko** [comment]
Here you go: https://codesandbox.io/s/hopeful-shockley-mylyx?file=/main.js

Just zoom out and and error will be shown.

In Firefox the error message is a bit different: "Uncaught DOMException: Index or size is negative or greater than the allowed amount"

**Comment by ahocevar** [comment]
@tapioko Thanks! You are right, `Raster#getImageData()` should return null when `width` or `height` is `0`. Would you be able to create a pull request with that fix?
