### ISSUE TITLE
Vector Tile Layer browser inconsistency

### ISSUE THREAD

**Issue by murdocha** [openlayers/openlayers#11652]
**Describe the bug**
When adding a vector tiles layer over a raster tiled basemap layer in Chrome, I see a scaling offset. There appear to be two differently transformed open layers canvas elements in Chrome, but only a single, correctly scaled canvas element in MS Edge (and also in Firefox). 

This is similar to the behavior reported in this now closed issue:
https://github.com/openlayers/openlayers/issues/10488#issuecomment-629189410

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/geojson-vt.html
2. Compare the "inspect elements" behavior in Chrome (Version 85.0.4183.121 (Official Build) (32-bit)) to MS Edge (Version 85.0.564.63 (Official build) (64-bit)) or Firefox (Version 81.0.1 (32-bit)).

See that there is a single map canvas element in Edge/Firefox:
```
<div class="ol-layer" style="position: absolute; width: 100%; height: 100%;"><canvas width="1048" height="400" style="position: absolute; left: 0px; transform-origin: left top; transform: matrix(1, 0, 0, 1, 0, 0);"></canvas></div>
```

while there are two map canvas elements in Chrome:
```
<div class="ol-layer" style="position: absolute; width: 100%; height: 100%;"><canvas width="834" height="400" style="position: absolute; left: 0px; transform-origin: left top; transform: matrix(1, 0, 0, 1, 0, 0);"></canvas></div>
<div class="ol-layer" style="position: absolute; width: 100%; height: 100%;"><canvas width="1043" height="500" style="position: absolute; left: 0px; transform-origin: left top; transform: matrix(0.8, 0, 0, 0.8, -0.2, 0);"></canvas></div>
```

Note that the second Chrome map canvas element is transformed to 80% scaling...

This does not present as a visible error in the above "geojson-vt.html" example (overlaying OSM basemap raster tiles, with OSM GeoJSON/Vector Tiles), but it _does_ present as a visible offset error when using an Esri/ArcGIS basemap tile service (https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}), together with the OSM GeoJSON/Vector Tiles example service (https://openlayers.org/en/latest/examples/data/geojson/countries.geojson).

see this screen image of the overlay offset in my work in progress application (only in Chrome):
![image](https://user-images.githubusercontent.com/7988400/96161279-1060a180-0ee5-11eb-985a-f05f511fd3e4.png)

**Expected behavior**
Multiple services (basemap, or vector tiles) should be presented with similar scaling regardless of which modern browser is used.

If there is a simple work around, I'd love to hear it...

**Comment by ahocevar** [comment]
The second canvas with scaling usually comes from browser zooming or from a device pixel ratio different than 1. I cannot reproduce the misalignment though. Would you be able to provide a reproducible example (e.g. on https://codesandbox.io/) that shows the issue?

**Comment by murdocha** [comment]
actually, after killing Chrome and reloading the issue went away. Still two ol-layer divs in Chrome, but they now overlay correctly. 
I was _sure_ I'd found a bug! :)

Apologies. I should have listened to my inner Chris O'Dowd.

It _is_ strange however that Chrome presents the two layers (basemap and vector tiles) as _two_ separate "ol-layer" divs. While Firefox and Edge only use a single div for the same application. 
Here's an example that shows that browser difference:
https://stackblitz.com/edit/js-6apnvx?file=index.js
