### ISSUE TITLE
VectorTile  renderMode:'image' with declutter:true doesn't display labels

### ISSUE THREAD

**Issue by songyumeng** [openlayers/openlayers#11653]
**Describe the bug**
ol/layer/VectorTile  renderMode:'image'  doesn't display labels
 
But in [APIs](https://openlayers.org/en/v6.4.3/apidoc/module-ol_layer_VectorTile-VectorTileLayer.html):
_Render mode for vector tiles:
'image': Vector tiles are rendered as images. Great performance, but point symbols and texts are always rotated with the view and pixels are scaled during zoom animations. When declutter is set to true, the decluttering is done per tile resulting in labels and point symbols getting cut off at tile boundaries._

**To Reproduce**
1. Go to [demo](https://codesandbox.io/s/rendermode-iy0qy), labels is not display
2. Change `renderMode` to `hybrid`,labels is display

**Expected behavior**
ol/layer/VectorTile  renderMode:'image'  display labels

**Comment by ahocevar** [comment]
Yes, text rendering in `image` does not behave as documented. With the main branch as of today, text will be rendered, but the same way as in `hybrid` mode.
