### ISSUE TITLE
OverviewMap migration v5.3 --> v6.3

### ISSUE THREAD

**Issue by Midnnight** [openlayers/openlayers#11669]
### OverviewMap regression

Actually we migrate OL v5 to v6.3 but no layer showed in the overViewMap.
I fin in a note in release 

```
The OverviewMap requires a list of layers.
Due to the constraint above (layers can only be added to a single map), the overview map needs to be constructed with a list of layers.
```

My question is how can display the layers in both Map and overViewMap in the sameTime, 

N.B: I know from the doc and samples that we can create layers for each separately.

Man thanks.

**Comment by mike-000** [comment]
You cannot use a layer in both maps, but you can use the same source in two layers, as in the example https://openlayers.org/en/latest/examples/overviewmap.html

**Comment by Midnnight** [comment]
Thanks for your response @mike-000 
I know that we can use the same source but I need to create TileLayer, and I've  many layers and layerGroup.

Have we a way to clone all Map layers to use them in the OverviewMap ?

I already tried to use `lodash _. cloneDeep ` also the spread operation, but not working because
