### ISSUE TITLE
Cannot find file: 'Wmts.js' does not match the corresponding name on disk: '.\node_modules\ol\source\WMTS.js'.

### ISSUE THREAD

**Issue by tomaszs** [openlayers/openlayers#11667]
**Describe the bug**
When importing WMTSTileGrid an error occurs during build:

```
import WMTSTileGrid from 'ol/tilegrid/WMTS';
```

**To Reproduce**
1. Install ```"ol": "6.4.3",```
2. Import WMTSTileGrid with import WMTSTileGrid from 'ol/tilegrid/WMTS';
3. See error: Cannot find file: 'Wmts.js' does not match the corresponding name on disk: '.\node_modules\ol\source\WMTS.js'.

**Expected behavior**

WMTSTileGrid should be imported properly

**Comment by ahocevar** [comment]
Looking at the error message you get in 3., I would say the error comes from a different import, where you are trying to import `ol/source/Wmts` instead of `ol/source/WMTS`.

**Comment by tomaszs** [comment]
@ahocevar Interesting. May it be possible that capitalized filename is causing the issue?
