### ISSUE TITLE
OptionsFromCapabilities throw "can not read ScaleDenominator of null"

### ISSUE THREAD

**Issue by thanhdn1989** [openlayers/openlayers#11679]
**Describe the bug**
I'm using the latest 6.4.3 OL.
I have a map provider which expose the WMTS service, after debugging i found that, if we have the TileMatrixLimits then when compare the TileMatrixSet with Identifier we didn't ignore the prefix, hence we encounter that error.

![image](https://user-images.githubusercontent.com/16373244/96948363-ac0a9700-150f-11eb-90f8-1ba8a400c4fc.png)

In the picture above:
+ The selectedMatrixLimit.TileMatrix will be: View1:15 but the Identifier of matrixSetObj.TileMatrix is only number (1...15) without the prefix View1

**Expected behavior**
Ignore the prefix when compare the TileMatrix and Identifier

**Comment by marcjansen** [comment]
Can you share a capability xml that produces this?
