### ISSUE TITLE
Rendering of reprojected VectorImage layers seems broken from v6.3.1 -> v6.4.3

### ISSUE THREAD

**Issue by geometix** [openlayers/openlayers#11672]
**Describe the bug**
Rendering of Vector sources on a VectorImage layer seems to be broken in v6.4.3, when the vector source has EPSG:4326 projection covering the whole globe, and the map is in EPSG:3857. It seems that the reprojection goes wrong, as EPSG:4326 exceeds the extent of EPSG:3857 (at high latitudes). It results in several layers of false polygons that are drawn on top of the correct ones, sometimes covering the whole map.

**To Reproduce**
1.) create a Vector source from a GeoJSON file containing polygons in EPSG:4326 covering the whole world (-180 to 180W and -90 to 90N).
2.) create a VectorImage layer with the Vector source
3.) add that layer to a map that is created with a view with projection EPSG:3857
4.) zoom and pan around and see flickering false polygons covering the map

**Expected behavior**
Not seeing any false polygons, like it is the case if you did add the same layer to a map with a view in EPSG:4326 (not reprojecting the source).

**Comment by geometix** [comment]
It seems that most of the country polygons in the example are within the extent of EPSG:3857. I think the problem becomes more evident if a lot of features are outside of EPSG:3857. If you pan the map in the example to the southern boundary, you can at least see that the polygon of Antarctica is self-intersecting near the edge of the extent. I don't know whether this has to do with the problem. I will try to reproduce the bug either as you suggested in the example or with another minimalistic setup tomorrow.

**Comment by mike-000** [comment]
There is a data issue with Antarctica.  To display correctly polygons should be split at the dateline as they are in Russia and Fiji.  That does not happen in Antarctica resulting in a line across the world `[180,-84.71338],[-179.942499,-84.721443]` just above the base of the projection extent.

**Comment by geometix** [comment]
I have put up a most minimalistic setup where the problem can easily be seen and compared between three different scenarios. I did: setup a map with two layers, an OSM tile layer as background and a weather data layer on top, derived from a geojson file coded in EPSG:4326, covering the whole world from -90 to +90N. The polygons are drawn semi-transparent, as the effect is even more evident in these cases.

1.) map view in EPSG:3856 and ol v6.3.1 -> everything is fine. polygons are drawn only once and background ist clearly visible, no random color changes when zooming or panning as expected.
2.) map view in EPSG:3857 and ol v6.4.3 -> background is not visible any more, probably due to several layers of polygons being drawn on top of each other. colors are changing randomly depending on zoom level for certain polygons / areas. clearly visible when looking at the Great Britain area and zooming, or areas near Antarctica, where polygons are changing color from white or light blue to orange depending on zoom level.
3.) map view changed to EPSG:4326 (by adding a projection property during view object creation), and ol v6.4.3 -> everything is fine again.

I have set up these three examples on a web server, only difference is ol versions and the view's projection property in 3.). They can be seen and tested here:
1.) http://www.geometix.de/pub/olvectortest_ref/ (for reference)
2.) http://www.geometix.de/pub/olvectortest_bug/ (buggy scenario)
3.) http://www.geometix.de/pub/olvectortest_epsg4326/ (for reference, v6.4.3 in EPSG:4326)

Please let me know if I can do anything else to help finding and solving the issue.

**Comment by geometix** [comment]
> The example https://openlayers.org/en/v6.4.3/examples/image-vector-layer.html does more or less what you are describing, and appears to work fine. Would you be able to use the "Edit" button in that example and modify it so it shows your issue?

As you suggested I have now reproduced the "buggy" scenario from above (#2) in the sandbox using the example as base. The issue can be seen there as well. If you change the ol version in the "package.json" from "6.4.3" to "6.3.1" the problem is gone.

Try it here: https://codesandbox.io/s/image-vector-layer-forked-xv55i?file=/main.js

**Comment by ahocevar** [comment]
Looks like the recent wrapX changes cause this issue. @mike-000, would you be available to investigate that further?

**Comment by geometix** [comment]
Tried to set wrapX to false on the VectorSource, but that does not help.

**Comment by mike-000** [comment]
The behaviour first changed in 6.3.2-dev.1593020254368 which corresponds to the merging of #11215 so it looks like there may be a winding order issue with the transformed polygons. When setting the fills to 100% opacity some red fills can be seen on the "low" side of isobars which also suggests that.

**Comment by geometix** [comment]
@mike-000 Great progress, and thanks a lot for your effort!

**Comment by mike-000** [comment]
When using the proj4 transform for EPSG:3857 (instead of the built in one which clamps coordinates to the projection extent) there is no problem https://codesandbox.io/s/image-vector-layer-forked-47cvz?file=/main.js
Since some of your polygons are closer to the poles than latitude 85 the clamping might be breaking the updated winding order algorithm.

**Comment by geometix** [comment]
Very nice workaround, will try that, much appreciated.

Any chance that can be fixed in the algorithm that OpenLayers uses since 6.3.2 as well? Because quite a lot of data have an extent like that, not only weather data. I think it's a quite common problem and therefore would feel better if OpenLayers handled these scenarios correctly as well.

**Comment by ahocevar** [comment]
Thanks a lot for your investigation @mike-000!

So it looks like the assumptions that vertices are non-collinear and not self-intersecting are violated due to the clamping. Maybe the new clockwise check algorithm can be modified to handle these cases, but as a last resort reverting to the old algorithm would be an option, with a performance impact.

**Comment by geometix** [comment]
Sounds good. Thank you for all your great work on the project!

**Comment by mike-000** [comment]
It think the algorithm is making a valid assumption and in cases like this the clamping could be considered to be corrupting the original EPSG:4326 geometry.  An alternative workaround to avoid clamping requiring fewer code changes is to use the `dataProjection` option of the GeoJSON format with a WGS84 projection defined by proj4 https://codesandbox.io/s/image-vector-layer-forked-khuj6?file=/main.js   Maybe a similar alternative to EPSG:4326 could be built into OpenLayers to enable transforms where clamping would not be desirable?

**Comment by geometix** [comment]
That last example again shows some color changes while zooming in, e.g. near Antarctica (the red region).

**Comment by mike-000** [comment]
There seems to be a problem when zooming which is unrelated to clamping.  That is also happening in my previous example and in your EPSG:4326 reference example (where there are similar changes over SW USA and Mexico which I cannot reproduce in EPSG:3857).

**Comment by geometix** [comment]
Good catch. But still the same code works fine when bundled with OL v6.3.1, so it seems somehow related.

**Comment by ahocevar** [comment]
I created #11719 to fix this problem.

**Comment by mike-000** [comment]
I think clamping was only making the problem (which can also be seen with EPSG:4326) more obvious.  With an EPSG:4326 view there is no clamping of the origin geometry so how can zooming affect the geometry's winding algorithm?

**Comment by ahocevar** [comment]
Can you describe the steps to see the zooming problem? I was unable to reproduce that.

**Comment by ahocevar** [comment]
I saw the duplicated geometries on zooming now, also with the projection set to EPSG:4326. So that suggests that either some of the geometries violate the required topology rules (non-collinear and not self-intersecting), or there is a bug in applying the new winding order algorithm for multipolygons.

**Comment by mike-000** [comment]
I don't see the zoom issue in 6.3.1, but why would changing the resolution affect the calculation of winding even if there is a bug?  Does it use the original geometry or pixel geometry?

**Comment by ahocevar** [comment]
Good question @mike-000. The winding order is calculated from the simplified geometry, in map coordinates. Linestrings are simplified using Douglas Peucker, which could potentially produce self-intersections. This would explain the behavior we are seeing. There are versions of Douglas Peucker that avoid self-intersections. It might also be possible to use the quantizing algorithm we use for polygons, which does not produce self-intersections either.

**Comment by ahocevar** [comment]
Update: Switching from Douglas-Peucker to quantizing does not solve the problem. However, using the original geometries instead of the simplified ones makes the problem go away. So I would say the problem is indeed that simplifying geometries the way we do it (with both Douglas-Peucker and quantizing) creates either self-intersections or collinear sections.

The new winding order algorithm could easily be modified to handle colinear sections properly. Maybe also self-intersections. However, I don't know when I would be able to find time to improve that algorithm. If anyone wants to take that on, please go ahead! Otherwise I think it might be better to switch back to the old winding order algorithm.
