### ISSUE TITLE
ScaleLine with Custom projection

### ISSUE THREAD

**Issue by All4Gis** [openlayers/openlayers#11674]
**Describe the bug**

I have a problem and I don't know if it's a missing parameter or a bug. I'm using a custom projection and everything works fine, except the scale.The scale shows an incorrect value as I think it is using another projection system internally.

I had the same problem with the distance measurement, but I solved it by using the correct radius and passing the projection object, like this:

```
var length = getLength(line, {
    projection: projection,
    radius: 3396190.0
  });
```
But I can't find this option in the scale.If we do not pass this option it shows the same value as the scale ~ 1000 km.

The correct value is ~600km and we can show that with this change the measure show the correct value but the scale not.

![Screenshot from 2020-10-21 11-56-14](https://user-images.githubusercontent.com/8123225/96707833-ad658380-1398-11eb-827a-6dc982cfa283.png )

Then. **Am I missing a parameter on the scale? Is there a workarround to fix this problem?**
thanks

**To Reproduce**
I have created a sample project here :
https://codesandbox.io/s/scalebar-custom-projection-v6ljg?file=/index.html

**Expected behavior**
The expected result would be that the scale corresponds to the real average.

![olympusmons](https://user-images.githubusercontent.com/8123225/96708347-6a57e000-1399-11eb-8f00-ed5d6092f3f4.jpg)

For example in this [viewer](https://trek.nasa.gov/mars/#v=0.1&x=0&y=0&z=1&p=urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A104905&d=&locale=&b=mars&e=-252.42187029143176%2C-131.66015379406852%2C252.42187029143176%2C131.66015379406852&sfz=&w=) we see that scale show the correct value

![Screenshot from 2020-10-21 11-58-36](https://user-images.githubusercontent.com/8123225/96708386-7774cf00-1399-11eb-8f31-5e3435ed0c05.png)

**Comment by ahocevar** [comment]
You are right, there is no direct way to configure a sphere radius for the ScaleLine control. But when you do mapping for a planet other than Earth, it makes sense to adjust METERS_PER_UNIT with the radius of that planet's sphere:
```js
import { METERS_PER_UNIT } from "ol/proj/Units";
METERS_PER_UNIT['degrees'] = (2 * Math.PI * 3396190.0) / 360
```
I have forked your sandbox and added the above code: https://codesandbox.io/s/scalebar-custom-projection-forked-9hqb3

**Comment by All4Gis** [comment]
Great, good point,
Thank you very much for your help
