### ISSUE TITLE
Properties set inside Feature are not being returned when triggering the `on` `select` event from the Select interaction

### ISSUE THREAD

**Issue by danvc** [openlayers/openlayers#11677]
**Describe the bug**
Properties set inside Feature while added, are not being returned when triggering the `on` `select` event from the `Select` interaction;

As a user, I want create an array of features, setting properties inside each feature and then adding it into the source by calling the `addFeatures([])`. I'd like to get these properties set while selecting a feature;

**To Reproduce**
Create an array of features setting properties inside each feature, something like this:
```
  feature.setProperties({
    entityType: tool.entityType,
    data: row,
  });
```

After creating the array of features, add it into the source:
```
source.addFeatures(featuesFromElements)
```

Create a Select interaction and console the properties from the selected feature:
```
  const selectFeature = new Select();
  selectFeature.on('select', e => {
    console.log('select', e.selected[0].getProperties());
  });
  this.map.addInteraction(selectFeature);
```
I would expect that the properties set while adding the features would be returned while consuming the method `getProperties`.

**Expected behavior**

**Comment by mike-000** [comment]
Can you produce an example?  It is working as expected here https://codesandbox.io/s/happy-visvesvaraya-pco2t?file=/main.js

**Comment by danvc** [comment]
You're right @mike-000. My code seems the same.. but, somehow, it's not working for me. I'll carefully take a look.
