### ISSUE TITLE
DoubleClickZoom also fires when using multitouch

### ISSUE THREAD

**Issue by MarByteBeep** [openlayers/openlayers#11670]
I have a simple map with the following interaction added:

```javascript
map.addInteraction(new ol.interaction.DoubleClickZoom({delta:1}));
```

But when testing on iOS, I noticed that the map also zooms in when I simply place two fingers on the map. I think behind the scenes it registers two 'presses' (one of each finger), and therefore fires this event.

Is there anything I can do to prevent this from happening?

**Comment by ahocevar** [comment]
DoubleClickZoom is added to the map by default. If you add it again, it might cause unwanted behavior.

**Comment by MarByteBeep** [comment]
If I leave out that line, nothing happens when double clicking the map. I actually added it because of that reason. I'm using OpenLayers 6.4.3.

**Comment by ahocevar** [comment]
Then maybe you have other interactions or listeners active that stop the doubleclick propagation? See e.g. https://openlayers.org/en/latest/examples/simple.html, where doublecklick zoom works out of the box for me. Does it work for you as well?

**Comment by MarByteBeep** [comment]
That example has the same problem on iOS: when using two fingers on the map, it zooms in

**Comment by ahocevar** [comment]
I can confirm that. This could definitely be considered a bug. Looks like we only count the taps, but don't distinguish between pointers.

**Comment by MarByteBeep** [comment]
Yes that’s my thought as well. Glad it wasn’t me doing something stupid :) thanks for picking this up
