### ISSUE TITLE
Line crossing anti-meridian stops rendering when it is clipped

### ISSUE THREAD

**Issue by ashchurova** [openlayers/openlayers#11681]
We use OL to plot vessel movement history on the map, Since OL doesn't support lines crossing anti-meridian (or if it does I am not aware of it) when vessel movement line crosses anti-meridian we adjust coordinates based on direction of the movement, so for ex if it is crossing from west to east  we adjust east hemisphere coordinates by adding -360 to coordinate's longitude, and if line is crossing from east to west we add +360 to the longitude of the west hemisphere coordinates of the line.    

So while panning or zooming line stops rendering on the screen. See attached screen shots. I have added points layer based on line coordinates to help you see where the line should be rendered :

![with_line](https://user-images.githubusercontent.com/15365676/97006444-e3784400-150d-11eb-86a9-f64236480ede.png)
![without line 2](https://user-images.githubusercontent.com/15365676/97006457-e96e2500-150d-11eb-889b-455e9b27a9d0.png)
![without line](https://user-images.githubusercontent.com/15365676/97006470-ed9a4280-150d-11eb-8a51-0e70ef3b2e71.PNG)
 
The sample code that can be used to reproduce this issue can be found here: https://codepen.io/ashchurova/pen/rwXjzP

Thank you.

**Comment by MoonE** [comment]
Your line crosses the date line from the left, if the world this line belongs to is no longer in the current render extent it will not be drawn. To avoid this you can split it at each date line intersection and use a `ol/geom/MultiLineString`.
```js
function splitAtDateLine(coords) {
  const lineStrings = [];
  let lastX = Infinity
  let lineString;
  for (let i = 0, ii = coords.length; i < ii; ++i) {
    const coord = coords[i];
    const x = coord[0];
    if (Math.abs(lastX - x) > 180) { // Crossing date line will be shorter
      if (lineString) {
        const prevCoord = coords[i - 1];
        const w1 = 180 - Math.abs(lastX);
        const w2 = 180 - Math.abs(x);
        const y = (w1 / (w1 + w2)) * (coord[1] - prevCoord[1]) + prevCoord[1];
        if (Math.abs(lastX) !== 180) {
          lineString.push(ol.proj.fromLonLat([lastX > 0 ? 180 : -180, y]));
        }
        lineStrings.push(lineString = []);
        if (Math.abs(x) !== 180) {
          lineString.push(ol.proj.fromLonLat([x > 0 ? 180 : -180, y]));
        }
      } else {
        lineStrings.push(lineString = []);
      }
    }
    lastX = x;
    lineString.push(ol.proj.fromLonLat(coord));
  }
  return lineStrings;
}

const source = new ol.source.Vector({
  features: [ 
    new ol.Feature({
      geometry: new ol.geom.MultiLineString(splitAtDateLine(points)),
    }),
  ],
});
```

**Comment by ashchurova** [comment]
Ok, thanks, I will try that.
