### ISSUE TITLE
Firefox issue with evt.ctrlKey on keypress events

### ISSUE THREAD

**Issue by ger-benjamin** [openlayers/openlayers#11692]
**Describe the bug**
On Firefox: On listen keydown/keyup, sometimes the detection of `event.ctrlKey` fail. (Work everytime on Chrome).
As `ol.events.conditions.js` rely on the detection of `event.ctrlKey` a bug may append.

Update: I've opened a corresponding issue on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1673362

**To Reproduce**
I've made a codepen example: https://codepen.io/ger-benjamin/pen/ZEOeyRb (without any library). Open it with Firefox and press repeatedly the ctrl key (it append ~10% of the time on my machine.).

**Expected behavior**
I propose to use the Use W3C Modifier Keys Attributes value to detect ctrl key on Firefox.
I'll propose a PR => #11693

**Comment by ger-benjamin** [comment]
Concern only Firefox for Ubuntu (or Ubuntu 18). And too hard to fix here (see the PR).
I close.

**Comment by ali1234** [comment]
For anyone else who finds this bug:

I think I encountered this bug in another project today. It seems to affect Firefox on any Linux, but only under X11. Wayland is unaffected. Tested the reproducer on Raspberry Pi OS Bookworm running Openbox(X11) and Wayfire(Wayland) and Firefox 129.0.
