### ISSUE TITLE
Legacy build and missing packages

### ISSUE THREAD

**Issue by AleMScof** [openlayers/openlayers#11696]
Hi there,
following the docs i've tried to perform a legacy build which ended up being successful.

I am merging the legacy build with ol-cesium packages which is failing to be loaded due to some ol packages missing.
In details package ol.structs.* is not found, going through the legacy script generated the packages arent present.

Since I have no possibility of using the library with the newer syntax, how can i rebuild the script having those modules present in it?

Thanks,
A.

**Comment by MoonE** [comment]
As a last resort you can add the `@api` tag to the classdoc of the classes you need before you run the legacy build: 
```patch
 /**
  * @classdesc
  * Wrapper around the RBush by Vladimir Agafonkin.
  * See https://github.com/mourner/rbush.
  *
  * @template T
+ * @api
  */
 class RBush {
```

**Comment by AleMScof** [comment]
> As a last resort you can add the `@api` tag to the classdoc of the classes you need before you run the legacy build:
> 
> ```diff
>  /**
>   * @classdesc
>   * Wrapper around the RBush by Vladimir Agafonkin.
>   * See https://github.com/mourner/rbush.
>   *
>   * @template T
> + * @api
>   */
>  class RBush {
> ```

Thanks MoonE, 
got it working!

A.
