### ISSUE TITLE
Touch events on iOS 12

### ISSUE THREAD

**Issue by jacobwod** [openlayers/openlayers#11690]
**Describe the bug**
Map events (pan, click) don't work on touch devices with iOS 12.

Please see this [issue](https://github.com/hajkmap/Hajk/issues/606) and [especially my last comment](https://github.com/hajkmap/Hajk/issues/606#issuecomment-716440458). 

I think I've traced it down to the different behaviour between iOS versions (whether mouse pointer events are sent [as is the case on iOS 13 and above] or not). On iOS 12 (on the left in image below) we only seem to get the `touchmove` event, as [noted here](https://github.com/openlayers/openlayers/issues/10747), while iOS 14 (on the right) seems to produce a whole series of events:
![Skärmavbild 2020-10-26 kl  11 05 58](https://user-images.githubusercontent.com/110222/97159480-3c004900-177b-11eb-918e-f91da5841d8f.png)

**The question is if we can use the `touchmove` event to properly trigger map events?** I haven't investigated the code changes in detail, but I've tested my project with OL 5.3.3 and know that iOS 12 events seem to work as expected.

**Comment by jacobwod** [comment]
I noticed an idea in another (related) [issue](https://github.com/openlayers/openlayers/issues/11465) about **enabling experimental Pointer Events** in Safari's settings (on iOS 12).

**I did it and it does solve the problem, the same events show up in log on both iOS 12 and 14, and all touch events work.** The only problem is that we can't expect users to enable this experimental setting that's buried deep down iOS system settings. Is there any other solution for iOS 12 in sight?

**Comment by ahocevar** [comment]
The solution is to use a Pointer events polyfill. See https://github.com/openlayers/openlayers#supported-browsers.

**Comment by jacobwod** [comment]
Thank you, will take a look at it! 👍 

_I thought that Babel would handle all necessary polyfills as needed to support my browsers of choice (specified in `browserslist` portion of `package.json`) as my project is based on Create React App. But sure, I understand that it can't polyfill my project's dependencies._
