### ISSUE TITLE
Fire event when layer view moves outside of layers visible scale

### ISSUE THREAD

**Issue by kiastorm** [openlayers/openlayers#11694]
**Is your feature request related to a problem? Please describe.**

I am so stuck on this! I'm trying to build the following control on top of my map

![image](https://user-images.githubusercontent.com/63059016/97358902-d6ec4680-1893-11eb-9c9d-d7c9efec705b.png)

When the user zooms in/out and moves outside of a layers visible scale (min/max resolution), I want to know about it and update my own React component's state. I want my layer menu to reflect the state of all visible, rendered maps

 How can I do this? Please let me know if you have a solution.

**Describe the solution you'd like**

It would be great if a layer's 'visible' state reflected whether the map is inside its set min and max zoom. 
Or even better, a property that tells whether the layer is currently outside of its zoom / resolution bounds

**Comment by MoonE** [comment]
You can rely on `ol/View`'s `change:resolution` event.
Something like this should do the trick:
```js
view.on('change:resolution', function (evt) {
    const resolution = evt.target.getResolution();
    const visible = layer.getMinResolution() >= resolution && layer.getMaxResolution() <= resolution;
    updateLayerControl(visible);
});
```

**Comment by MoonE** [comment]
I made an example here:
https://codesandbox.io/s/layermenu-with-state-53g4r?file=/main.js

**Comment by kiastorm** [comment]
> I made an example here:
> https://codesandbox.io/s/layermenu-with-state-53g4r?file=/main.js

You're the best! Thanks so much!

**Comment by kiastorm** [comment]
I'm wondering - why isnt a layer's `change:visible` event fired when the view moves outside of its visible resolution? Or why isnt there a property for accessing the value of its true display state?
