### ISSUE TITLE
Allow Promise<boolean> types to be returned from interaction handlers

### ISSUE THREAD

**Issue by jeremy-smith-maco** [openlayers/openlayers#11695]
We are implementing the alternative hit detection method for faster results but less accuracy based on [this example](https://openlayers.org/en/latest/examples/hitdetect-vector.html). The `layer.getFeatures(pixel)` method returns a promise so to use that method in an interaction's `handleDownEvent` callback it would require returned a promise which resolves a boolean like so:

```js
return this.layer.getFeatures(event.pixel).then((features) =>
{
    return !!(features.length ? features[0] : undefined);
});
```

The return value from the handler is expecting only a boolean though so return a `Promise` object that resolves to a boolean from these handlers is not an option as when the promise is casted to a boolean it will return `true` indicating that the event was consumed when it was potentially not.

Doing this would been it would have to handle promises being returned up the call stack to the `dispatchEvent` method and the methods which call it which is a bit of an annoyance. I am not sure another way around it but there could be other possible solutions.

**Comment by jeremy-smith-maco** [comment]
I tried implementing the example that I linked to in the original issue using my PR to test with and it seemed to be a lot slower than using the `map.getFeatureAtPixel()` but that example says it is meant to be faster but less accurate. Does anyone know why it is so much slower?

I want to change the cursor to a pointer in the `mouseMoveEvent` if hovering over a feature that is clickable (determined by our local code) but it can be quite slow when dragging around the screen if it is called when another interaction is handling the dragging. I can check the `event.dragging` boolean but it is still quite slow.

**Comment by jahow** [comment]
Hi,

Can you please explain a bit more clearly _why_ you need to use the promise return value in the event handler? It seems to me you can just chain some logic to the `getFeatures` call without worrying about the event handler that much.

**Comment by jeremy-smith-maco** [comment]
Well in the `handleDownEvent` callback handler it returns back a `boolean` for whether or not the event was handled. If we use the `map.getFeatureAtPixel()` method it is synchronous so we can just run that and do logic based on whether a feature as the pixel that was clicked. If we wanted to implement something using `layer.getFeatures()` like in the [example ](https://openlayers.org/en/latest/examples/hitdetect-vector.html) from the original post then that method returns a promise which means that you are not able to do and logic on the result to determine whether or not the event was handled.

If you returned a `Promise` from the `handleDownEvent` callback which resolved to a boolean then you could then handle the promise returned and do logic on the result and then resolve the promise with a boolean indicating whether or not the event was handled or not. If all we needed to do was handle it during the `handleMoveEvent` then it would be fine to use `layer.getFeatures()` and handle all of the logic within the callback as it does not expect a return value for anything.

The example posted using the `layer.getFeatures()` method for hit detection seems a lot slower than using the `map.getFeatureAtPixel()` method anyway and I am not sure why so I was hoping someone knew why it was slower when it is intended to be better for performance. Hopefully that makes sense.

**Comment by jahow** [comment]
> The example posted using the layer.getFeatures() method for hit detection seems a lot slower than using the map.getFeatureAtPixel() method anyway and I am not sure why so I was hoping someone knew why it was slower when it is intended to be better for performance. Hopefully that makes sense.

To allow people to assist you further on this please create a minimal reproduction on https://codesandbox.io/ or equivalent (you can start from the example by clicking edit on the top right). `getFeatures` _is_ faster by design, so there may be other things degrading performance in your case.

> Well in the handleDownEvent callback handler it returns back a boolean for whether or not the event was handled.

Agreed, if using `getFeatures` you will have a hard time returning a boolean for whether features were found in the handler. There may be other solutions though, it depends on exactly _what_ you are trying to achieve. A modification of the library code such as what you offered might not be necessary.

**Comment by jeremy-smith-maco** [comment]
> getFeatures is faster by design, so there may be other things degrading performance in your case.

It may just be our implementation of it, you are correct. It may be slower because we are checking features using `getFeatures` over 4 layers so that could be what is slowing it down potentially.

This is the gist of what we currently have: https://codesandbox.io/s/floral-wood-0m1qo?file=/main.js:2284-2285

We are storing a feature the we detect in the mouse down event if there is one at the given pixel and then doing something with it later on in the `handleDragEvent` and `handleUpEvent`. We were attempting to update the hit detection code with the one from the example.

This is basically the code we would use the achieve that: https://codesandbox.io/s/sweet-ptolemy-hpdk1?file=/main.js:2284-2285

You can see that it will always cast the return value from `handleMoveEvent` to `true` since it will always return a `Promise` object so `null` will print out to console when you drag outside of a feature's boundary. This would work using my provided PR. Whether or not it is because I am using the `getFeatures` method over 4 layers to search for features or some other reason as to why it is slower than the `forEachFeatureAtPixel` method I am not sure but I think those examples should provide a basic use case.

The examples are a small implementation of our main goal. Our code has more handling code in the `handleDragEvent` listener and `handleUpEvent` listener for dragging features around and selecting features etc. but the main parts are the hit detection that we wanted to improve upon. Hopefully this will provide some insight into a use case for the feature. If there is anything else that may help, just let me know.

**Comment by jahow** [comment]
I think using `forEachFeatureAtPixel` on the down event handler is the best way to go. `getFeatures` is intended to be faster and non-blocking, and is typically useful for changing the mouse pointer appearance on move events. On the other hand, `forEachFeatureAtPixel` is great for pointer down events and it is synchronous. Most of the time calling this function only once should not be noticeable by the user.

Now, if your issue is that there is a noticeable lag between clicking on a feature and dragging it (which would supposedly not happen with `getFeatures`), then I think you're better of with not using a custom interaction and writing logic in a more basic way (follows untested code):
```js
this.draggedFeature = null;
map.on('pointermove', (evt) => {
  if (this.draggedFeature) {
    // do something with this.draggedFeature
  } else {
    getFeature(evt).then((feature) => {
      element.style.cursor = feature ? "pointer" : "default";
    });
  }
});
map.on('pointerdown', (evt) => {
  getFeature(evt).then((feature) => {
    if (feature) {
      this.draggedFeature = feature;
      element.style.cursor = "pointer";
    }
  });
});
map.on('pointerup', (evt) => {
  this.draggedFeature = null;
});
```

Hope that helps.

**Comment by jeremy-smith-maco** [comment]
Thank you for the response. I think the main performance issue wasn't the onDown event but more so when we are dragging the map around and the onMove event is running hit detection all the time whilst doing so. We can always short circuit the event handler if the `event.dragging` flag is set but there is still some noticeable lagginess when the user stops dragging and the map keeps moving due to the velocity and the user moves their mouse during this.

The main reason we are using interactions is because we want the `DragPan` functionality but if they click and drag on a feature that we deem as draggable then we want that feature to move instead so we need to be able to return back from the onDown event to stop propagation to other interactions.

I would think your example would have the same performance implications compared to doing it inside an interaction. The only problem I can potentially see with your example is if we were to handle dragging a feature around inside of the `pointermove` handler then the default `DragPan` handler that we use would kick in and drag the map around as well as our code for dragging around the feature.

I think we can just use the `forEachFeatureAtPixel` method and ignore the onMove handler if the `event.dragging` is set. This should help with performance a lot I think for our use case.

Thanks for your help.
