### ISSUE TITLE
Legacy build doesn't work as expected.

### ISSUE THREAD

**Issue by ustiloff** [openlayers/openlayers#11703]
The process of building the "legacy build" performs without errors. But the resulting library cannot be used because the browser crashes with an error. 
The last stable version (6.4.3) builds a working library.

**Comment by MoonE** [comment]
Below code works for me without error as of a1a59b4408475a65027b69c1eddf1f431ad59da2, could you provide an example code that crashes?
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Legacy</title>
    <link type="text/css" rel="stylesheet" href="build/legacy/ol.css">
    <script src="build/legacy/ol.js"></script>
    <style>
      .map {
        height: 400px;
      }
    </style>
  </head>
  <body>
    <div class="map" id="map"></div>
    <script>
      const map = new ol.Map({
        view: new ol.View({
          zoom: 10,
          center: [0,0],
        }),
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ]
      })
    </script>
  </body>
</html>
```

**Comment by ustiloff** [comment]
You're right. The error occurs when using ol.renderer.webgl.PointsLayer. Here is a sample that works fine in 6.4.3 but with an error in 6.4.4-dev:
`<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Legacy</title>
    <link type="text/css" rel="stylesheet" href="build/legacy/ol.css">
    
    <script src="build/legacy/ol.js"></script>
    <style>
      .map {
        height: 400px;
      }
    </style>
  </head>
  <body>
    <div class="map" id="map"></div>
    <script>
      const map = new ol.Map({
        view: new ol.View({
          zoom: 10,
          center: [0,0],
        }),
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ]
      })

      const webglLayer = new ol.layer.Vector({
        source: new ol.source.Vector()
      });
      webglLayer.createRenderer = function () {
           return new ol.renderer.webgl.PointsLayer(this, {
            attributes: [
              {
                name: 'size',
                callback: function(feature) {
                  return 100;
                }
              },
            ],
            vertexShader: `precision mediump float;
              uniform mat4 u_projectionMatrix;
              uniform mat4 u_offsetScaleMatrix;
              uniform mat4 u_offsetRotateMatrix;
              uniform float u_time;
              uniform float u_zoom;
              uniform float u_resolution;
              attribute vec2 a_position;
              attribute float a_index;
              varying vec2 v_texCoord;
              varying vec2 v_quadCoord;
              attribute float a_size;
              void main(void) {
                mat4 offsetMatrix = u_offsetRotateMatrix * u_offsetScaleMatrix;
                vec2 halfSize = vec2(a_size * 0.5);
                vec2 offset = vec2(0.0);
                float angle = 0.0;
                float offsetX;
                float offsetY;
                if (a_index == 0.0) {
                  offsetX = (offset.x - halfSize.x) * cos(angle) + (offset.y - halfSize.y) * sin(angle);
                  offsetY = (offset.y - halfSize.y) * cos(angle) - (offset.x - halfSize.x) * sin(angle);
                } else if (a_index == 1.0) {
                  offsetX = (offset.x + halfSize.x) * cos(angle) + (offset.y - halfSize.y) * sin(angle);
                  offsetY = (offset.y - halfSize.y) * cos(angle) - (offset.x + halfSize.x) * sin(angle);
                } else if (a_index == 2.0) {
                  offsetX = (offset.x + halfSize.x) * cos(angle) + (offset.y + halfSize.y) * sin(angle);
                  offsetY = (offset.y + halfSize.y) * cos(angle) - (offset.x + halfSize.x) * sin(angle);
                } else {
                  offsetX = (offset.x - halfSize.x) * cos(angle) + (offset.y + halfSize.y) * sin(angle);
                  offsetY = (offset.y + halfSize.y) * cos(angle) - (offset.x - halfSize.x) * sin(angle);
                }
                vec4 offsets = offsetMatrix * vec4(offsetX, offsetY, 0.0, 0.0);
                gl_Position = u_projectionMatrix * vec4(a_position, 0.0, 1.0) + offsets;
                vec4 texCoord = vec4(0.0, 0.0, 1.0, 1.0);
                float u = a_index == 0.0 || a_index == 3.0 ? texCoord.s : texCoord.p;
                float v = a_index == 2.0 || a_index == 3.0 ? texCoord.t : texCoord.q;
                v_texCoord = vec2(u, v);
                u = a_index == 0.0 || a_index == 3.0 ? 0.0 : 1.0;
                v = a_index == 2.0 || a_index == 3.0 ? 0.0 : 1.0;
                v_quadCoord = vec2(u, v);
              }`,
            fragmentShader: `precision mediump float;
            void main(void) {
              gl_FragColor = vec4( 1.0 );
            }`
          })
        }
      map.addLayer(webglLayer);
    </script>
  </body>
</html>
`
The exception message in the dev. console:

Uncaught TypeError: this.getRenderer().renderDeclutter is not a function
    renderDeclutter BaseVector.js:216
    renderFrame Composite.js:130
    renderFrame_ PluggableMap.js:1154
    animationDelay_ PluggableMap.js:174
    render PluggableMap.js:1076
    handleSizeChanged_ PluggableMap.js:924
    dispatchEvent Target.js:114
    notify Object.js:160
    set Object.js:180
    setSize PluggableMap.js:1197
    updateSize PluggableMap.js:1230
    handleTargetChanged_ PluggableMap.js:988
    dispatchEvent Target.js:114
    notify Object.js:160
    set Object.js:180
    setProperties Object.js:193
    e PluggableMap.js:319
    e Map.js:85
    <anonymous> index.html:18

Browsers: Chrome and Firefox, OS: Windows 10

**Comment by mike-000** [comment]
The same error would be seen when using imports https://codesandbox.io/s/simple-forked-10my1?file=/main.js and is caused by your code using an inappropriate renderer for the layer type.  `ol/layer/Vector` expects its renderer to have a `renderClutter()` method.  The WebGL renderer is intended to be used with `ol/layer/WebGLPoints` which does not declutter.

**Comment by ustiloff** [comment]
I see, but in the new version, it will be possible to use custom shaders, because WebGLPoints layer requires "style" config, which in this case is redundant?

This is how it works now:
![зображення](https://user-images.githubusercontent.com/13692504/97805853-35813e00-1c61-11eb-93c9-79c4551ec553.png)

**Comment by mike-000** [comment]
As a workaround you could use

      webglLayer.createRenderer = function () {
          const renderer = new ol.renderer.webgl.PointsLayer(this, {
              ...
              ...
              ...
          });
          renderer.renderDeclutter = function () {};
          return renderer;
      }

**Comment by ustiloff** [comment]
Thanks a lot

**Comment by jia-mx** [comment]
> As a workaround you could use
> 
> ```
>   webglLayer.createRenderer = function () {
>       const renderer = new ol.renderer.webgl.PointsLayer(this, {
>           ...
>           ...
>           ...
>       });
>       renderer.renderDeclutter = function () {};
>       return renderer;
>   }
> ```



> As a workaround you could use
> 
> ```
>   webglLayer.createRenderer = function () {
>       const renderer = new ol.renderer.webgl.PointsLayer(this, {
>           ...
>           ...
>           ...
>       });
>       renderer.renderDeclutter = function () {};
>       return renderer;
>   }
> ```


 https://codesandbox.io/s/simple-forked-10my1?file=/main.js 
Why in this example, I changed it according to what you said, but the map does not show any content drawn by shader.

**Comment by mike-000** [comment]
> Why in this example, I changed it according to what you said, but the map does not show any content drawn by shader.

You will need at least one point feature in the source https://codesandbox.io/s/simple-forked-1mxiet?file=/main.js

**Comment by jia-mx** [comment]
> > Why in this example, I changed it according to what you said, but the map does not show any content drawn by shader.
> 
> You will need at least one point feature in the source https://codesandbox.io/s/simple-forked-1mxiet?file=/main.js

Using version 9 ol why can't it be rendered?
