### ISSUE TITLE
styleFunc is called a lot, even when feature isn't updated

### ISSUE THREAD

**Issue by MarByteBeep** [openlayers/openlayers#11701]
Consider the following pretty trivial example with some `features`, `clusters` and a `styleFunc` that 'dressed' the features (in this case it sends a message to the console):

```javascript
const styleFunc = function(p_feature) {
	console.log("here");
}

const locations = new ol.source.Vector();

[...] fill locations with features

let cluster = new ol.source.Cluster({
	distance: 20.0,
	source: locations
});

let layer = new ol.layer.Vector({
	source: cluster ,
	style: styleFunc
});

[...] add layer to map etc.
```

I noticed that when adding a simple `ol.interaction.Select` that operates on that `layer`, every time I select a feature the `styleFunc` is called for ALL features currently in view. Why is `styleFunc` not simply called only for the selected feature? My dataset contains thousands of features, that are all flagged for change just because I select a single feature. 

Same thing happens when simply scrolling the page; in my view (pardon the pun) all features should remain the same (clustering is only affected by zoom), yet for each and every feature that enters the view, `styleFunc` is called again. 

Why is that?

**Comment by ahocevar** [comment]
I don't see a reason for style function calls when you zoom the page. For that to answer, you'd need to provide a minimal example that shows the problem, e.g. on https://codesandbox.io/

For the Select interaction (which I personally never use), the explanation is that the only way to change the visual appearance of a single feature on a layer is to re-create the render instructions for the whole layer, which requires a call to the style function for each feature. This is not a design flaw, but an optimization to get faster Canvas2D rendering: calling moveTo-lineTo-fill-stroke for each feature is much slower than finishing a bulk of geometries with the same style with moveTo-lineTo, and apply fill-stroke afterwards.

**Comment by MarByteBeep** [comment]
Thanks for the reply! I've a some other issues with the Select interaction as well (zooming deselects the selected feature for instance), so I'm curious to know your solution to highlight a feature when selected.

I'll try to make an example that shows the excessive calling of the style callback problem.

**Comment by MarByteBeep** [comment]
@ahocevar I made a sandbox here:

https://codesandbox.io/s/blissful-pine-lunty

It shows two problems:

1) observe the number of `console.logs` when simply dragging or zooming the map. Each log is a call to `styleFunc`
2) The `Select` interaction seems to be broken in 6.4.3, because when zooming the map, the selected style is removed. In 5.3.3 this still works.

Code below:

```javascript
import "ol/ol.css";
import "./index.css";
import TileLayer from "ol/layer/Tile";
import VectorLayer from "ol/layer/Vector";
import Map from "ol/Map";
import { transformExtent, fromLonLat } from "ol/proj";
import OSMSource from "ol/source/OSM";
import VectorSource from "ol/source/Vector";
import View from "ol/View";
import Feature from "ol/Feature";
import Cluster from "ol/source/Cluster";
import Point from "ol/geom/Point";
import { Circle, Style, Fill, Stroke } from "ol/style";
import Select from "ol/interaction/Select";

const locations = new VectorSource();
const features = [];
for (let i = 0; i < 40; ++i) {
  const longitude = 4 + Math.random() * 2.0;
  const latitude = 51 + Math.random() * 2.0;
  features.push(
    new Feature({
      geometry: new Point(fromLonLat([longitude, latitude]))
    })
  );
}
locations.addFeatures(features);

const cluster = new Cluster({
  distance: 20.0,
  source: locations
});

const clusterLayer = new VectorLayer({
  source: cluster,
  style: styleFunc
});

const map = new Map({
  target: "map",
  layers: [
    new TileLayer({
      source: new OSMSource()
    }),
    clusterLayer
  ],
  view: new View()
});

const style = new Style({
  image: new Circle({
    radius: 10,
    fill: new Fill({
      color: "white"
    }),
    stroke: new Stroke({ color: "green", width: 2 })
  })
});

function styleFunc(p_feature) {
  console.log("here"); // Observe this being called even when scrolling the map
  return style;
}

// This works fine in 5.3.3, but when switching to 6.4.3, the red selection dot is gone
// when zooming the map
const select = new Select({
  layers: [clusterLayer],
  hitTolerance: 10,
  style: new Style({
    image: new Circle({
      radius: 13,
      fill: new Fill({
        color: "red"
      }),
      stroke: new Stroke({ color: "red", width: 2 })
    })
  })
});
map.addInteraction(select);

// need to manually call transformExtent to make it work with lat lon coordinate pairs
map.getView().fit(transformExtent([5, 51, 5, 54], "EPSG:4326", "EPSG:3857"), {
  constrainResolution: false
});

```

**Comment by MoonE** [comment]
The `ol/interaction/Select` and `ol/source/Cluster` do not work well together. The `ol/source/Cluster`  is cleared and new Features are created on each resolution change. This includes the selected feature. The `ol/interaction/Select` does not know about the `ol/source/Cluster`'s `ol/source/Source`.

OpenLayers can't know what the selected feature should be after the `ol/source/Cluster` is clustered anew. I don't think this combination worked in v5.3.3 either.

**Comment by MarByteBeep** [comment]
@MoonE check the example in my previous post: if you switch the dependency to 5.3.3, the behavior is correct

**Comment by MoonE** [comment]
I see, this is the result of an behavior change of the Select interaction. In 5.3.3 it worked by moving the feature to a separate layer.
Since v6.0.0 it sets a style on the feature itself.
https://github.com/openlayers/openlayers/pull/10003

The behavior in 5.3.3 was not correct as the selected cluster is added a second time below after resolution change.
Here is an updated codesandbox to visualize this: https://codesandbox.io/s/select-style-ol-533-8fh2x

The select interaction does not know which features are inside a cluster, and the cluster source will generate new features on each change, so for all it knows it is a completely different feature.

**Comment by MarByteBeep** [comment]
Got it. Thanks for the explanation. I’ll see if I can somehow work around it. From a user perspective it is a bit confusing if suddenly the selection is gone while hardly anything changed. 

Do you also have have any idea what causes point 1: the excessive calls to `styleFunc`?

**Comment by MoonE** [comment]
You can keep the selection with this code in v6:
```js
let selected = select.getFeatures().getArray();
select.on('select', function () {
  selected = select.getFeatures().getArray();
});
cluster.on('addfeature', function (evt) {
  if (selected.size === 0) {
    return;
  }
  const features = new Set(evt.feature.get('features'));
  selected.forEach(function (selCluster, i) {
    const sel = selCluster.get('features');
    if (sel.some(f => features.has(f))) {
      if (features.size === sel.length && sel.every((f) => features.has(f))) {
        select.getFeatures().setAt(i, evt.feature);
      }
    }
  });
});
```

For point 1, I believe this is how openlayers is designed.
At the end of an animation/interaction all features currently in view are rendered again. The feature's style is not cached.

**Comment by MarByteBeep** [comment]
Thanks. I’ll give it a try!

Perhaps it would be an idea to cache those styles for optimization purposes? It seems a bit of a waste to constantly restyle them when nothing really happens.

**Comment by ahocevar** [comment]
@MarByteBeep:

A new set of rendering instructions is created at the end of an animation/interaction, if the center or resolution changed. This is because styling is resolution dependent, and only the current viewport is rendered.

This behavior is a good guess that will serve most purposes well. If you know more about when your styles change, you can do the caching on the application level, in the style function. This is a general recommendation we communicate frequently.

**Comment by MarByteBeep** [comment]
Thanks for the reply! I already use caching for the styles, however it still means that for every visible feature (can be 1000s) I need to compute which style it needs to apply. I think that's a bit of a waste of CPU cycles in the case of simply scrolling around the map. 

But if you don't expect it to be a problem and if it cannot be optimized, feel free to close this issue. Thanks for all the help!
