### ISSUE TITLE
Unwanted characters by the OpenStreetMap copyright notice

### ISSUE THREAD

**Issue by kazzle101** [openlayers/openlayers#11712]
Hello

In my map in the bottom right corner is the OpenStreetMap contributors copyright notice, where there are three unwanted characters; an 'a' with a circumflex, the euro character and the cent character:
<img width="241" alt="ol_char_error" src="https://user-images.githubusercontent.com/1898711/97858795-98251900-1cf7-11eb-93c0-e8dd7f7ac2fe.png">

Any ideas what is causing this and how do I get rid of them?
They don't appear when running the examples I got from downloading the v6.4.3.zip and adding to my test server. But I can't see what it is I need to do to have is appear correctly.

Thanks
Karl.

**Comment by ahocevar** [comment]
Make sure you set your application to use the UTF-8 encoding by adding the following in the head of your HTML:
```html
<meta charset="UTF-8">

**Comment by kazzle101** [comment]
> Make sure you set your application to use the UTF-8 encoding by adding the following in the head of your HTML:
> 
> ```
> <meta charset="UTF-8">
> ```

Yes, I have that, my head, I get the same on my live service:

```
<!DOCTYPE html>
  <html lang="en">
   <head>
   <meta charset="utf-8" />
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
   <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" type="text/css">
   <link rel="stylesheet" type="text/css" href="http://192.168.1.20/watermills/html/watermills.css" media="screen,print">
   <script type="text/javascript" src="http://192.168.1.20/watermills/html/jquery-3.5.1.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
   <link rel="stylesheet" href="http://192.168.1.20/watermills/ol/openlayers.bb28b584.css"></head>
   <script type="text/javascript">
   var _page = "main";
   var _siteURL = "http://192.168.1.20/watermills";
   var _sid = "i4q3sveru6o0ob7sss4onp4tnb";
   </script>
   <script type="text/javascript" src="http://192.168.1.20/watermills/html/site.js"></script>
   <title>The Water-Mills of Sheffield</title>
   </head>
```

**Comment by ahocevar** [comment]
`<meta charset="utf-8" />` is XHTML, but your document is HTML. So you'll need `<meta charset="utf-8">`.

**Comment by kazzle101** [comment]
The w3c people sat the end slash is OK on doctype HTML
https://www.w3.org/International/questions/qa-html-encoding-declarations

But I see no difference either way

**Comment by ahocevar** [comment]
Maybe your server sends wrong content encoding headers, or your browser has an override set?

**Comment by M393** [comment]
I believe the character should be `•`, but that has to come from either a custom attribution or CSS with wrong charset.
If it's css either convert the file to utf-8 or set the charset correctly. https://developer.mozilla.org/en-US/docs/Web/CSS/@charset

**Comment by kazzle101** [comment]
Found it, in my watermills.css file I had this mess:
```
li::before {
      content: "â€¢";
      padding-right: 5px;
      color: #23282D;
  } 
```
Thanks everyone for your help.
