### ISSUE TITLE
Undo when drawing Circles and using geometry functions

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11713]
**Describe the bug**
The updated example from #11698 highlights a difference between ability to undo between Circle geometry (cannot undo center) and other geometries which can be undone back to the first point.  Drawing a circle is basically the same as using a 2 point LineString with a geometry function to produce a circle https://codesandbox.io/s/pensive-einstein-05es0?file=/main.js which can be undone as long as the geometry function handles it.  The same would apply to `createRegularPolygon` and `createBox` functions (attempting to undo even a Circle draw using these functions currently results in an error).  Custom geometry functions such as star and ellipse (based on a 3 point LineString) can also be undone as long as the function is set up to handle it (although in the codesandbox the fill re-renders immediately while the stroke does not update until there is a pointer event).

**Expected behavior**
If Circles drawn using a 2 point LineString can be undone the same should apply if they are drawn as a Circle.
There should be no errors if drawing is undone when using the predefined geometry functions. 
Fill and Stroke should always show the same geometries.

**Comment by ahocevar** [comment]
Thanks for your observation @mike-000. If you see an easy way to fix circle drawing like you described, a pull request would be much appreciated.
