### ISSUE TITLE
A problem with testing geolocation on a desktop PC with Chrome

### ISSUE THREAD

**Issue by kazzle101** [openlayers/openlayers#11717]
Hello,
I've been working on adding geolocation to my map, and have come across this while doing the work on my desktop PC - when using the test geolocation in Chrome the map gives a blocked by CORS policy error. 

To reproduce:
using Chrome browser (latest version: 86.0.4240.183), go to:
https://openlayers.org/en/latest/examples/geolocation.html

press F12 - Developer tools
press Shift+Ctrl+P and search for sensors
On the Sensors tab select a location, a blue dot appears in the location then try to zoom into the map, an error appears in the console:

geolocation.html:1 Access to image at 'https://a.tile.openstreetmap.org/7/61/40.png' from origin 'https://openlayers.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

<img width="683" alt="ol_geo_blocked" src="https://user-images.githubusercontent.com/1898711/98223743-753e7300-1f4a-11eb-9551-0e15f61604ef.png">

**Comment by ahocevar** [comment]
I can reproduce this. I would guess it is a bug in the Chrome Dev Toools.

**Comment by Raza410** [comment]
Facing the same issue as well as wrong locations sometimes. These only happens on google chrome
