### ISSUE TITLE
EsriJson writes wrong wkid?

### ISSUE THREAD

**Issue by stevage** [openlayers/openlayers#11734]
**Describe the bug**

The EsriJSON feature format produces a geometry in EPSG:4326, but with a wkid of 3857.

I'm not confident that I understand the intended behaviour, but this seems wrong. By setting `dataProjection` to `EPSG:4326` and `featureProjection` to `EPSG:3857`, it converts features from the default projection to EPSG:4326 but with the wrong wkid.

**To Reproduce**

```
draw = new ol.interaction.Draw({
    source: new ol.source.Vector({wrapX: false}),
    type: 'Polygon',
});
map.addInteraction(draw);
draw.on('drawend', e => {
    const geometry = new ol.format.EsriJSON()
        .writeFeatureObject(e.feature, {
        dataProjection: 'EPSG:4326',
        featureProjection: 'EPSG:3857'
    }).geometry;
    console.log(geometry.spatialReference.wkid); //  3857
});
```

**Expected behavior**

Wkid of 4326.

**Comment by stevage** [comment]
I notice that [this example](https://openlayers.org/en/latest/examples/vector-esri-edit.html) "works": but it actually sends the data in EPSG:3857, so if this is indeed a bug, it wouldn't be apparent here.

**Comment by ahocevar** [comment]
Bug confirmed. The `writeFeatureObject` method sets the `wkid` from the `featureProjection` instead of the `dataProjection`. If you'd be able to provide a fix, a pull request would be much appreciated.

**Comment by stevage** [comment]
My experience with submitting PRs generally is that there is often a pretty big learning curve and time commitment to getting a first PR accepted, meeting various requirements etc. Given that this is literally a 1 line change, does that really make sense?
