### ISSUE TITLE
No ol/layer/WebGLPoints found in the packaged code

### ISSUE THREAD

**Issue by mylove10086** [openlayers/openlayers#11735]
You can use the source code
import WebGLPointsLayer from'ol/layer/WebGLPoints';
To use WebGLPointsLayer;
But WebGLPoints cannot be used in the packaged code
  var vectorSource = new ol.source.Vector({
             attributions:'NASA',
         });
         var wgl = new ol.layer.WebGLPoints({
             style: style,
             source: vectorSource,
             disableHitDetection: true,
         });
  ol.layer.WebGLPoints is undefined.
But the export has been seen in src/ol/layer.js.
Why is this

**Comment by mike-000** [comment]
It should be fixed by #11715
There are 6.4.4-dev versions at
https://openlayers.org/en/main/build/ol.js
https://openlayers.org/en/main/build/ol.js.map
https://openlayers.org/en/main/css/ol.css
https://openlayers.org/en/main/css/ol.css.map

**Comment by ahocevar** [comment]
Please don't use the above URLs directly in your applications. If you really need them, download and host them locally.

**Comment by dmatranga** [comment]
I also had this issue when using the packaged code for the workshop, and received the error:

`...Uncaught TypeError: ol_layer__WEBPACK_IMPORTED_MODULE_4__.WebGLPoints is not a constructor`

**Comment by ahocevar** [comment]
The workshop uses the ol package, so this is probably an unrelated issue.

**Comment by Gtrouborst** [comment]
> I also had this issue when using the packaged code for the workshop, and received the error:
> 
> `...Uncaught TypeError: ol_layer__WEBPACK_IMPORTED_MODULE_4__.WebGLPoints is not a constructor`

I cannot judge whether this is an unrelated issue, but I solved it by changing the import line.

**from:** 
```js
import {WebGLPoints as WebGLPointsLayer} from 'ol/layer';
```

**to:**
```js
import WebGLPointsLayer from 'ol/layer/WebGLPoints';
```

It looks like the original import line makes an alias for a constructer that doesn't exist (anymore). However, the suggested alias is itself a valid constructer.
