### ISSUE TITLE
Failed optionsFromCapabilities call corrupts the projection

### ISSUE THREAD

**Issue by janruo** [openlayers/openlayers#11738]
**Describe the bug**
Calling `optionsFromCapabilities` with a projection that is not supported by the WMTS server will throw an error. This is expected and documented behaviour, so I tried to use it to select a suitable projection by wrapping the call in a try-catch and calling it with different projections until one works. The problem is that those failed `optionsFromCapabilities` calls seem to somehow "corrupt" the projections. For example, creating an `ImageCanvasSource` with a projection that was used for a failed `optionsFromCapabilities` call causes the canvas function to receive invalid parameters.

**To Reproduce**

**_Edit: It seems that the WMTS server I used in the sample was closed, it returns 404 now. But this can most likely be reproduced with other WMTSs and projections as well_**

1. Clone and run the sample: https://github.com/janruo/ol-issue
2. See that it works, a red rectangle is drawn on the map.
3. See the console output, canvasFunction parameters are valid.
4. Uncomment line 101 of index.js, comment out line 104.
5. See that it no longer works, no rectangle.
6. See the console output, canvas function received invalid extent and size parameters.

**Expected behavior**
Failed `optionsFromCapabilities` calls should not cause the projection to become unusable.

**Comment by mike-000** [comment]
It will set the projection extent to the matrix extent - but only if the projection does not already have an extent https://github.com/openlayers/openlayers/blob/db180c555e7a27bef00ed52aef20b8a5eb6a2672/src/ol/source/WMTS.js#L490-L493

**Comment by janruo** [comment]
So is this a bug or expected behavior? I'm not sure whether your comment was just a note where the problem is, or if you're telling me that I shoud set an extent for the projection.

**Comment by mike-000** [comment]
In this case it is a bug.  It is expected behaviour if the projection does not already have an extent and it is supported in the WMTS. If it is not supported a documented error is thrown when attempting to create a tile grid.  So it should be setting the projection extent after creating the tile grid, not before.
