### ISSUE TITLE
Tile coordinate errors when viewing EPSG:32630 GWC WMS layer

### ISSUE THREAD

**Issue by ghtyrant** [openlayers/openlayers#11752]
**Describe the bug**
We are using OpenLayers to view a layer served by GeoWebCache using WMS. The layer is in EPSG:32630. Most of the time, we are getting errors similar to the following from GeoWebCache:
```
400: X,Y values for the tile index were calculated to be {2359.0, 35647.67455749462} which had to be rounded to {2359, 35648} and exceeds the threshold of 10%. Perhaps the client is using the wrong origin ?
```
As you can see, the X coordinate looks fine but Y is way off the expected tile grid.

Some observations:
- Everything works as expected when using GeoServer without cache - but this is just because GeoWebCache tries to fit requests to its defined grid set and implements some logic to verify the precision
- This also happens for EPSG:32631 and EPSG:32629. These coordinate systems all cover a huge vertical area (e.g. https://epsg.io/32630). That might be why X coordinates look fine but Y coordinates don't.
- Zooming in and out we can find resolutions where the requests work as expected
- Extent and resolutions defined in the example below where calculated automatically by GeoServer
- Obviously we are using proj4 for this coordinate system
- Using a smaller extent for the tile grid (e.g. the bounding box of the layer itself) does not fix the issue but at least we get expected results without zooming in or out. Zooming causes the issue again.

**My guess would be that this is caused by some floating point rounding errors.**
I am not sure wether this is an issue with OpenLayers or with proj4. If it's the later, please let me know.

**To Reproduce**
I can provide a minimal working example, unfortunately without a GeoServer backing it up:

main.js:
```js
import 'ol/ol.css';
import Map from 'ol/Map';
import TileLayer from 'ol/layer/Tile';
import TileWMS from 'ol/source/TileWMS';
import View from 'ol/View';
import OLTileGrid from 'ol/tilegrid/TileGrid';
import { getCenter, buffer, getSize } from 'ol/extent';
import { register } from 'ol/proj/proj4';
import proj4 from 'proj4';

var brokenGrid = new OLTileGrid({
  extent: [166021.4431, 0.0, 833978.5569, 9329005.1825],
  tileSize: [256, 256],
  resolutions: [2609.2074757812497, 1304.6037378906249, 652.3018689453124, 326.1509344726562, 163.0754672363281, 81.53773361816405, 40.76886680908203, 20.384433404541014, 10.192216702270507, 5.096108351135253, 2.5480541755676267, 1.2740270877838134, 0.6370135438919067, 0.3185067719459533, 0.1592533859729767, 0.0796266929864883, 0.0398133464932442]
});

var transform = '+proj=utm +zone=30 +datum=WGS84 +units=m +no_defs +type=crs';
proj4.defs('EPSG:32630', transform);
register(proj4);

var layers = [
  new TileLayer({
    source: new TileWMS({
      tileGrid: brokenGrid,
      url: 'http://xxxx/geoserver/gwc/service/wms',
      params: {
        'VERSION': '1.1.1',
        'LAYERS': 'workspace:layer_name',
        'EXCEPTIONS': 'application/vnd.ogc.se_inimage',
        'FORMAT': 'image/png8'
      },
      serverType: 'geoserver',
      transition: 1,
    }),
  })];

var extent = [537303.75, 5756588.75, 564283.25, 5870059.25];

var map = new Map({
  layers: layers,
  target: 'map',
  view: new View({
    projection: 'EPSG:32630',
    center: getCenter(extent),
    extent: buffer(extent, Math.max(...getSize(extent)) * 0.4),
    showFullExtent: true,
    resolution: 0.5,
  }),
});
```

index.html:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Tiled WMS</title>
    <!-- Pointer events polyfill for old browsers, see https://caniuse.com/#feat=pointer -->
    <script src="https://unpkg.com/elm-pep"></script>
    <style>
      .map {
        width: 100%;
        height:800px;
      }
    </style>
  </head>
  <body style="background-color: #000000;">
    <div id="map" class="map"></div>
    <script src="main.js"></script>
  </body>
</html>
```

package.json:
```json
{
  "name": "gwcissue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ol": "^6.4.3",
    "proj4": "^2.6.2"
  },
  "devDependencies": {
    "parcel": "1.11.0"
  },
  "scripts": {
    "start": "parcel --host 0.0.0.0 index.html",
    "build": "parcel build --experimental-scope-hoisting --public-url . index.html"
  }
}
```

**Expected behavior**
I expect to be able to view the map served via GWC completely without coordinate errors, even when zooming in or out.

**Comment by ahocevar** [comment]
This is probably because your TileGrid definition in OpenLayers does not match the grid definition in GeoServer. The resolutions are only one part of the equation. The second is the extent.

And just as an additional note: proj4 is not needed in your setup, because no coordinate transforms are needed.

**Comment by ghtyrant** [comment]
It does match:
![image](https://user-images.githubusercontent.com/51596/99675270-4f02f200-2a77-11eb-9331-d7d0c239259c.png)
In our real world system, we get this information directly from GeoServer before setting OpenLayers up.

Regarding proj4: You are right, nothing is actually being transformed here. Which makes me wonder, doing the following:

```js
var transform = '+proj=utm +zone=30 +datum=WGS84 +units=m +no_defs +type=crs';
var p = proj4('EPSG:32630', transform);
console.log(p.forward([166021.4431, 0.0]));
```
yields
`Array [ 166021.4431000001, 0 ]`
This should be a no-op then, but it looks like there are already some rounding errors here?

**Comment by ahocevar** [comment]
I see the problem now. Your TileWMS source misses a configuration option:
```js
  projection: 'EPSG:32630'
```

**Comment by ghtyrant** [comment]
Unfortunately, this was not the issue, as if no projection is set at the source it defaults to the view's projection, which is set correctly.

I have updated the code nevertheless:
```js
var layers = [
  new TileLayer({
    source: new TileWMS({
      tileGrid: brokenGrid,
      projection: 'EPSG:32630',
      url: 'http://geoserver.toi.bshrk.net:80/geoserver/gwc/service/wms',
      params: {
        'VERSION': '1.1.1',
        'LAYERS': 'oi-pilot:PHR1B_202005281140159_FR1_PX_W003N52_1012_08754',
        'EXCEPTIONS': 'application/vnd.ogc.se_inimage',
        'FORMAT': 'image/png8',
        'TILED': true
      },
      serverType: 'geoserver',
      transition: 1,
    }),
  })];
```

But still get have the same issue.

**Comment by ahocevar** [comment]
Well, to bring proj4 out of the equation, you could define your projection simply as follows:
```js
const projection = new Projection({
  code: 'EPSG:32630',
  units: 'm'
});
```
But I don't think this will make a difference.

If others want to look at your example, it would be good if you could use a publicly available GeoServer instance, and provide your example in a codesandbox.

**Comment by ghtyrant** [comment]
> Well, to bring proj4 out of the equation, you could define your projection simply as follows:
> 
> ```js
> const projection = new Projection({
>   code: 'EPSG:32630',
>   units: 'm'
> });
> ```
> 
> But I don't think this will make a difference.

You are right, no difference.

> If others want to look at your example, it would be good if you could use a publicly available GeoServer instance, and provide your example in a codesandbox.

I will see what I can do tomorrow.
Thanks for your help so far!

**Comment by mike-000** [comment]
The tilegrid extent width exactly matches the resolutions, but there is a small difference between the tilegrid extent height divided by 14 and the width, but enough to become significant relative to tile size as the Z increases.
As OpenLayers defaults to top left of the extent when origin is defaulted, try setting the OpenLayers origin at the bottom left `origin: [166021.4431, 0.0]` as that seems to be the GWC default.

**Comment by ghtyrant** [comment]
> The tilegrid extent width exactly matches the resolutions, but there is a small difference between the tilegrid extent height divided by 14 and the width, but enough to become significant relative to tile size as the Z increases.

My bad, the values are indeed off. I made some changes with my experiments, that's why. I have also tried to auto-generate to boundaries by GeoServer and then regenerate the resolutions - no change to the issue.

Your second suggestion makes it work though! Setting the origin to the lower left fixes my issues.
