### ISSUE TITLE
ol/Map + proj4: t.slice issue

### ISSUE THREAD

**Issue by wendellwt** [openlayers/openlayers#11768]
I'm trying to run the 'Raster Reprojection' example but am having issues.  The example code, which includes this, produces an error:

```
import Map from 'ol/Map';
import proj4 from 'proj4';
```

_Uncaught TypeError: t.slice is not a function_

However, when the import statements are re-arranged, the example code runs fine:

```
import proj4 from 'proj4';
import Map from 'ol/Map';
```

<map displays fine.>

Is there some sort of interaction between ol and proj4?  Are there certain versions that should be used?  The versions used are:
```
ol@6.4.3
proj4@2.6.2
npm: 6.14.4
node: v10.21.0
```
Thank you.

**Comment by ahocevar** [comment]
Please provide more information:
* Which bundler are you using?
* What is the full stack trace?

Ideally, you'd create a codesandbox (https://codesandbox.io) so others can see the problem.

**Comment by wendellwt** [comment]
parcel@1.11.0

Stack trace is:
```
Uncaught TypeError: t.slice is not a function
    getState              https://lego.carrotseverywhere.com/main.33570d8e.js:1
    renderFrame_          https://lego.carrotseverywhere.com/main.33570d8e.js:1
    animationDelay_       https://lego.carrotseverywhere.com/main.33570d8e.js:1
    render                https://lego.carrotseverywhere.com/main.33570d8e.js:1
    handleSizeChanged_    https://lego.carrotseverywhere.com/main.33570d8e.js:1
    dispatchEvent         https://lego.carrotseverywhere.com/main.33570d8e.js:1
    notify                https://lego.carrotseverywhere.com/main.33570d8e.js:1
    set                   https://lego.carrotseverywhere.com/main.33570d8e.js:1
    setSize               https://lego.carrotseverywhere.com/main.33570d8e.js:1
    updateSize            https://lego.carrotseverywhere.com/main.33570d8e.js:1
    handleTargetChanged_  https://lego.carrotseverywhere.com/main.33570d8e.js:1
    dispatchEvent         https://lego.carrotseverywhere.com/main.33570d8e.js:1
    notify                https://lego.carrotseverywhere.com/main.33570d8e.js:1
    set                   https://lego.carrotseverywhere.com/main.33570d8e.js:1
    setProperties         https://lego.carrotseverywhere.com/main.33570d8e.js:1
    t                     https://lego.carrotseverywhere.com/main.33570d8e.js:1
    t                     https://lego.carrotseverywhere.com/main.33570d8e.js:1
    <anonymous>           https://lego.carrotseverywhere.com/main.33570d8e.js:1
    <anonymous>           https://lego.carrotseverywhere.com/main.33570d8e.js:1

```
I'm unable to reproduce the anomaly in codesandbox, so it must be some sort of version mismatch going on. 

I'm able to work around it, it's just curious that it is a problem sometimes.  I would offer to help diagnose if I knew where to look.

**Comment by ahocevar** [comment]
This is a known issue with Parcel v1. Please use v2:

    npm install --save-dev parcel@next

We have updated the examples to use v2 as well. See #11691.

**Comment by wendellwt** [comment]
Yes, that was the problem. I should have done more research.

BTW, the Reprojection example I see [here](https://openlayers.org/en/latest/examples/reprojection-image.html) doesn't show the updated parcel v2 reference.

Thank you for all of your hard work on openlayers; it is a terrific package.
This issue should be closed.

**Comment by ahocevar** [comment]
The link to the example you provided points to the latest version, i.e. 6.4.3 at the time of writing, which does not have the fix yet. So that's expected.
