### ISSUE TITLE
Add every other filter operators from Mapbox

### ISSUE THREAD

**Issue by Pipoupi** [openlayers/openlayers#11765]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement a dynamic multiple filter and I need to have the IN operator implemented. 

Hi all, 

As I said I'm looking for an implementation of IN operator. I saw in some of your PRs that you're trying to be as close as possible to Mapbox spec, so I'm wondering why not every operators are implemented in Openlayers? Is it planned to be added or operators will stay like it is at this time ? https://github.com/openlayers/openlayers/blob/main/examples/webgl-points-layer.html

Following issue #11308 

Thanks !

**Comment by mjjurkoic** [comment]
I've created a pull request which would add the in operator according to the Mapbox specs, it's PR #11839.

**Comment by Pipoupi** [comment]
Thanks for your job and for noticing me. I'll close if PR is approved

**Comment by mjjurkoic** [comment]
If this PR is approved I'll look into adding some of the other missing Mapbox operators as well.
