### ISSUE TITLE
creating navigation app avoiding markers

### ISSUE THREAD

**Issue by BaroneLorenzo** [openlayers/openlayers#11771]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
 I would need an API or a function that allows you to create a route from point A to point B avoiding manually entered markers.
for example if I insert a marker on a bridge and want to go from one side of the bridge to the other, the api must give me an alternative route to the bridge to avoid crossing that bridge. For example, like the functionality of avoiding public transport but instead of putting public places to avoid inserted placeholders

**Comment by M393** [comment]
OpenLayers does not provide a routing functionality.

Take a look at OpenStreetMaps related projects: https://wiki.openstreetmap.org/wiki/Routing/online_routers
Once you have the route you can of course display it with OpenLayers.
