### ISSUE TITLE
Calling openLayers.view.centerOn as part of animation produces jumping behaviour

### ISSUE THREAD

**Issue by redstubble** [openlayers/openlayers#11776]
Calling openLayers.view.centerOn at approximately 20 fps causing juddering.
Lookin for the right way to implement a smooth following motion. 

**Expected behavior**
Smooth panning of map

**Comment by mike-000** [comment]
Use `view.animate()` with `center` and `duration` options

**Comment by redstubble** [comment]
Thanks Mike, really appreciate your comment. I am receiving positional data at a rate of 20hz. I want to centre the map on this device location, so animate doesn't really fulfill my needs here. 

From your comment am I correct in understanding that if I apply a padding to my map, if I recenter within the confines of the padded view will this speef things up. Also I have read up on adjustCentre in V6.4.3 does this provide any performance benefit.

https://openlayers.org/en/latest/apidoc/module-ol_View-View.html

**Comment by MoonE** [comment]
Is this what you need? 
https://codesandbox.io/s/track-position-vfdrx?file=/main.js

**Comment by redstubble** [comment]
@MoonE, Thanks for this, not quite what I am looking for though. But I will try to adapt your code, I need to centre the map on the actual coordinate so that the map moves relative to the geometery I am displaying on relevant layer.

**Comment by MoonE** [comment]
If you set the `responsivenes` to 0 the map will be centered within 1/20 second. (The animation length is then 1/20 second, same as the update interval).

In the example the animation duration get shorter when the point is further away from the center.
It will always move the point to the center of the view, but if the position is updated in between it may never reach it.
If you zoom out it behaves a bit better.

**Comment by redstubble** [comment]
Really appreciate your feeback.
But using your code I cannot get behaviour that surpasses simply calling setCenter and map.renderSync. 
Maybe I am expecting too much from inheritly expensive processes.

On a side note, when I do call setCenter (20fps) repeatedly the zoom event listener does not work properly. Is there any way to properly manage this?

**Comment by MoonE** [comment]
Please create a short example in https://codesandbox (or somewhere else) that showcases your problem.
It's hard to guess without looking at some code.

OpenLayers renders the map with requestAnimationFrame which happen at 60fps, you shouldn't need to call `renderSync`, prefer 'render` and multiple render requests will be consolidated to one to get better performance.
