### ISSUE TITLE
Prevent panning and zooming beyond map edges in OpenLayers 6

### ISSUE THREAD

**Issue by xdursoc** [openlayers/openlayers#11772]
I would like to know in which way it is possible to avoid the map to panning and zooming beyond map edges.
I posted the same question on stackoverflow, but I posted the same thing here, because in my opinion it is necessary to have this option available as option for View or I don't know where. It needs and option to not pan and zoom the map out of its border without using functions explictly etc...

![image](https://user-images.githubusercontent.com/64744341/100258564-82e28980-2f47-11eb-8d39-4ef5282076bc.png)

**Comment by ahocevar** [comment]
Just configure your `ol/View` with the `extent` you want to restrict panning/zooming to.

**Comment by xdursoc** [comment]
ok, but I need to give the extent of the map when it's created? in other words my desire is to have that at I can only see the entire world. at the maximum zoom, and then when i zoom in i can pan the map but without the possibility to go over its edges.

**Comment by ahocevar** [comment]
That's exactly what the option does. See https://codesandbox.io/s/runtime-architecture-ktiwp?file=/main.js.

**Comment by xdursoc** [comment]
thanks a lot!

**Comment by xdursoc** [comment]
There is a channel or something similar where it is possible to ask something about code ect.. regarding openlayers obviously? @ahocevar

**Comment by ahocevar** [comment]
There is: https://stackoverflow.com/. Use the `openlayers` tag.

**Comment by xdursoc** [comment]
Thanks for the replies and suggestions.
