### ISSUE TITLE
Add smooth zoom and pan effect like OpenSeaDragon when dragging and scrolling

### ISSUE THREAD

**Issue by kuige** [openlayers/openlayers#11773]
OpenSeaDragon smooth zoom and pan effect demo:

https://openseadragon.github.io

**Comment by ahocevar** [comment]
OpenLayers has that already. For `ol/interaction/DragPan`, there is a `kinetic` option that allows you to configure the exact behavior. And for `ol/interaction/MouseWheelZoom`, you can play with the `maxDelta`, `duration` and `timeout` options.

**Comment by kuige** [comment]
@ahocevar How to replace the default `DragPan` and `MouseWheelZoom` interaction ? 

I want to use the default interactions but replace the `DragPan` and `MouseWheelZoom` interaction, should I first iterate over the default interactions to find the `DragPan` and `MouseWheelZoom` interaction, remove them, and create a new `DragPan` and `MouseWheelZoom` instance and add it to the interactions ? 

Is there any other ways ?

**Comment by kuige** [comment]
> OpenLayers has that already. For `ol/interaction/DragPan`, there is a `kinetic` option that allows you to configure the exact behavior. And for `ol/interaction/MouseWheelZoom`, you can play with the `maxDelta`, `duration` and `timeout` options.

Fantastic!👍

**Comment by ahocevar** [comment]
> How to replace the default DragPan and MouseWheelZoom interaction ?
```js
import Map from 'ol/Map';
import {defaults, DragPan, MouseWheelZoom} from 'ol/interaction';

new Map({
  interactions: defaults({
    dragPan: false, mouseWheelZoom: false
  }).extend([new DragPan({/* options */ }), new MouseWheelZoom({/* options */})])
});

**Comment by kuige** [comment]
@ahocevar I have tried the kinetic option of DragPan, but it's not working, am I do something wrong ?

Here is a demo: https://codepen.io/sange/pen/dypyeep

**Comment by kuige** [comment]
I can't figure out how to tweak the kinetic option so that I can create the smooth pan effect like OpenSeaDragon.

**Comment by M393** [comment]
The values used in the default interactions are `const kinetic = new Kinetic(-0.005, 0.05, 100);`, they are per milliseconds, so should be quite small.

**Comment by kuige** [comment]
@M393 I have tried the default kinetic options, and also many other values, but still can't get the smooth effect like OpenSeaDragon. 🙁

**Comment by ahocevar** [comment]
If you cannot tweak the options to achieve the desried effect, you could also create a custom interaction. You'll probably have to dig into the OpenSeaDragon source code and do some research, then implement something equivalent as custom OpenLayers interaction.

**Comment by M393** [comment]
I think the OpenSeaDragon example has a maximum velocity, and reduces the decay if the interaction velocity was high. Maybe you can create a subclass of `ol//Kinetic` that implements this behavior.

**Comment by DEEEZIGN** [comment]
@kuige Faced the same problem, solution: change duration in ol.DragPan:

handleUpEvent(mapBrowserEvent) {
    const map = mapBrowserEvent.map;
    const view = map.getView();
    if (this.targetPointers.length === 0) {
      if (!this.noKinetic_ && this.kinetic_ && this.kinetic_.end()) {
        const distance = this.kinetic_.getDistance();
        const angle = this.kinetic_.getAngle();
        const center = view.getCenterInternal();
        const centerpx = map.getPixelFromCoordinateInternal(center);
        const dest = map.getCoordinateFromPixelInternal([
          centerpx[0] - distance * Math.cos(angle),
          centerpx[1] - distance * Math.sin(angle),
        ]);
        view.animateInternal({
          center: view.getConstrainedCenter(dest),
          **duration: 800,**
          easing: easeOut,
        });
      }
      if (this.panning_) {
        this.panning_ = false;
        view.endInteraction();
      }
      return false;
    }

**Comment by rfezzani** [comment]
Based on @kuige codepen example, simply enabling tiles preload made the zoom and pan very smooth:
```html
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/build/ol.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css">
<style>
    #container {
        width: 800px;
        height: 800px;
    }
</style>
<div id="container"></div>
<script>
    new ol.Map({
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM(),
                preload: 10
            }) ],
        target: 'container',
        view: new ol.View({
            center: [0, 0],
            zoom: 2,
        })
    })
</script>
```
