### ISSUE TITLE
Problems when selection and drawing exist at the same time

### ISSUE THREAD

**Issue by mylove10086** [openlayers/openlayers#11774]
When I register in the map at the same time
  map.addInteraction(Select); and
  map.addInteraction(draw); At the end of drawing, the figure is selected. When the select is not registered, the drawing is over and not selected.
Therefore, when I register draw and select at the same time, I hope that the drawing is not selected when the drawing ends. what should I do.

This is the example on openlsyer：
https://codesandbox.io/s/gshrm?file=/main.js
Add to 
import Select from 'ol/interaction/Select';
var selects=new Select();
map.addInteraction(selects);

**Comment by bojko108** [comment]
I had this problem before. You could set `stopClick` property to `true` when you create the draw widget:
```js
draw = new Draw({
      stopClick: true,
      source: source,
      type: typeSelect.value,
});
```

[https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html)

**Comment by EvertEt** [comment]
Possibly related to #12147
