### ISSUE TITLE
Possibility to apply a custom style to BingMaps

### ISSUE THREAD

**Issue by gastdozent91** [openlayers/openlayers#11788]
**Is your feature request related to a problem? Please describe.**
I want to add a custom map style to my integrated BingMap. For example: i have BingMap with the attribute "imagerySet":"CanvasGray" and i want to add a much more lighter version of that.

**Describe the solution you'd like**
I would like to have another BingMaps option "style" which comes as a string and this is added to the rest url for the static bing map request.

See here:
https://docs.microsoft.com/en-us/bingmaps/rest-services/imagery/get-a-static-map#map-parameters (**Map Parameters** "style")
https://docs.microsoft.com/en-us/bingmaps/articles/custom-map-styles-in-bing-maps

I would appreciate the change or an alternative solution advice, if there is any. Thanks a lot and in advance!

**Comment by mike-000** [comment]
The simplest way is to append your `'&style=......'`string to the API key
