### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.map.getTargetElement().hasAttribute')

### ISSUE THREAD

**Issue by anthonn** [openlayers/openlayers#11789]
I got this error reported from one of the angular 10 web-clients I am using OpenLayers inside. I do not know what happened more then the information that is existing from the stacktrace. 

It came in three "bursts":
sec 0: 2 errors
sec 3: 3 errors
sec 6: 4 errors

It is the first problem of this kind I see since I upgraded to ol 6.4.3, which at least was a couple of months ago. So it is not any big isssue for me at this point, but thought I should report it.

**Error**
TypeError: null is not an object (evaluating 'e.map.getTargetElement().hasAttribute')

**Stacktrace**
(webpack:///node_modules/ol/src/events/condition.js:92:38) func: h, code: return event.map.getTargetElement().hasAttribute('tabindex')
(webpack:///node_modules/ol/src/events/condition.js:30:35) func: , code: pass = pass && conditions\[i\](event);
(webpack:///node_modules/ol/src/interaction/MouseWheelZoom.js:173:25) func: , code: if (!this.condition_(mapBrowserEvent)) {
(webpack:///node_modules/ol/src/PluggableMap.js:1032:45) func: , code: const cont = interaction.handleEvent(mapBrowserEvent);
(webpack:///node_modules/ol/src/events/Target.js:111:18) func: , code: \]).call(this, evt);
(webpack:///node_modules/ol/src/MapBrowserEventHandler.js:190:23) func: , code: this.dispatchEvent(newEvent);
(webpack:///node_modules/zone.js/dist/zone-evergreen.js:167:61) func: runTask, code: return this._zoneDelegate.invokeTask(this, task, applyThis, applyArgs);
(webpack:///node_modules/zone.js/dist/zone-evergreen.js:480:45) func: invokeTask, code: return task.zone.runTask(task, target, args);
(webpack:///node_modules/zone.js/dist/zone-evergreen.js:1621:24) func: _, code: task.invoke(task, target, [event]);
(webpack:///node_modules/zone.js/dist/zone-evergreen.js:1658:35) func: k, code: invokeTask(copyTasks\[i\], target, event);

**Comment by ahocevar** [comment]
Looks like a bug we fixed already. Try to `npm install ol@dev`.

**Comment by anthonn** [comment]
So this fix is not included in 6.4.3? 
I have no idea how to reproduce it though, it happened once after 1,5 months with around 20 users per day, so if it is fixed and it will come out in a new release I will just wait.

Thanks for the info!

**Comment by ahocevar** [comment]
Would be good if you could try the dev version regardless. So we actually **know** it is the same issue that was fixed.

**Comment by anthonn** [comment]
But would that help? I do not know how to reproduce this error. It happened in production.

**Comment by ahocevar** [comment]
Ok, in this case let's leave the issue open. When you update and still get the error reported in production, please report it here.

**Comment by ahocevar** [comment]
Maybe fixed with #11446.

**Comment by anthonn** [comment]
I think it could be closed for now actually. Even if I update I would need to wait 2-3 months before I could tell if the issue was fixed, since it only happened once after 1,5 months. So the issue would only stay open.
Better to reopen a new one and referring back to this.
But either way is fine by me, you could decide.

Thanks for the help! And a very nice product!
