### ISSUE TITLE
Improvement of StaticImage example.

### ISSUE THREAD

**Issue by MtnBiker** [openlayers/openlayers#11798]
The example for static images uses `extent` which it gains from previous knowledge, that is, it is hard coded, the extent should be determined from the image. I imagine most will be dynamically loading images and not know the extent in advance. https://openlayers.org/en/latest/examples/static-image.html (in looking for a solution, I found another example with the same problem: https://openlayers.org/en/master/examples/zoomify.html)

**Describe the solution you'd like**

Rewrite the example code to determine the extent and then use that `extent` to define the `projection` and `layer`.

Thank you for these tutorials. Hopefully I'll figure this out and post the change.

**Comment by mike-000** [comment]
`imageExtent` does not need to be the same as `imageSize` (which is auto-detected, but some .svg sizes may not be auto-detected). This allows the image to be stretched either dimension as required.  For example in https://openlayers.org/en/latest/examples/reprojection-image.html the image size is 2000 x 3696 (ratio 0.541) not 700000 x 1300000 (ratio 0.538).

**Comment by MtnBiker** [comment]
Thank you for the comment. I understand extent and size can be different. I'm trying to draw on a static image, so have combined the StaticImage and the draw shapes examples. But imageSize isn't working for a .png either. The following is modification of the example. Basically I'd like to get the size to set the extent since I'm using the whole image.
```
    var docSource = new Static({
      attributions: '© <a href="http://xkcd.com/license.html">xkcd</a>',
      url: 'https://imgs.xkcd.com/comics/online_communities.png',
      projection: projection,
      imageExtent: extent
    });
    var docSize = docSource.imageSize;
    console.log('size: ', docSize); // undefined 
```

**Comment by mike-000** [comment]
The image is loaded asynchronously, and only when required for the map
```
docSource.on('imageloadend', function(event) {
  console.log(event.image.getImage().width);
  console.log(event.image.getImage().height);
});
```
To get the size before using it in the map you would need to preload the url into a JavaScript Image object and wait for the load event.

**Comment by MtnBiker** [comment]
mike-000 Thanks, I'll look into that. I'm weak in JS (probably shouldn't be dabbling in OL).
