### ISSUE TITLE
format.writeFeatures create a LOT Bigger File than original KML

### ISSUE THREAD

**Issue by Agustinzero1** [openlayers/openlayers#11797]
**Describe the bug**
well, i'm developing am online Editor using Openlayer6 and i found a strange problem, i'm from uruguay and i have an Electoral Zone Map (Lot of Polygon Features) in KML, that i'm using as example file, and i build a Upload Feature option (based on reader.readAsDataURL(file); ), and i'm using Drag and Drop Interaction, that 2 options are for upload, next, i build a Layer State Controler (a state manager for only allow 1 edit, and other controls, not important) next i build  a Download option with the next Peace of code code 

    let Layer = window.map.getLayers().getArray()[LayerID];
    let sourceDeLaLayer =  Layer.getSource();
    const featuresDelLayer = sourceDeLaLayer.getFeatures();
    const data = format.writeFeatures(featuresDelLayer, {featureProjection: 'EPSG:3857'});
    console.log(data);

Te problem, the KML File sizes 0.75 MB on upload
but when i show this console.log(data); print a 26 MB of KML data (x35 times bigger)
and if y open the result file in Qgis it works, but if i save in Qgis the result file is 0.75 MB again (i open the 26 mb File in QGis and Sizes 0.75 on save with all features, no information lose)
 
format.writeFeatures() is Making the file bigger for some motive

**To Reproduce**
Im using NodeJS 14.15.0
load KML as VectorSource of VectorLayer
Next Download as KML using const data = format.writeFeatures( Features , {featureProjection: 'EPSG:3857'});

**Expected behavior**
Expected that the Result file of similar Size that the uploaded File

(as an extra data, if i upload the 26 mb KML result of format.writeFeatures, the result file dont grows x35 times again, maintain the 26 mb size with the new poligon, the file only compared to Qgis File no compared to OL Exported File, and the file have )

[Artigas KML (original and result File).zip](https://github.com/openlayers/openlayers/files/5629211/Artigas.KML.original.and.result.File.zip)

**Comment by mike-000** [comment]
If you read the icon url http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png as a dataURL OpenLayers has no way of knowing its original path so it will be written back to the KML as a very long dataURL.

**Comment by Agustinzero1** [comment]
> If you read the icon url http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png as a dataURL OpenLayers has no way of knowing its original path so it will be written back to the KML as a very long dataURL.

and what will be the correct way to do the save ?

**Comment by Agustinzero1** [comment]
> If you read the icon url http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png as a dataURL OpenLayers has no way of knowing its original path so it will be written back to the KML as a very long dataURL.

i need to delete all symbols on save to solve this issue?

**Comment by mike-000** [comment]
Why are you reading as a dataURL?  If your features are styled using the original Google url they will be written back with that url as the icon style.

**Comment by Agustinzero1** [comment]
> dataURL
because i don't know the correct way to do, i don't have experience in download data, this is my code 

//the objective is download the layer with the LayerID and save in a file with the Name and Format sected in a form

  window.layersDelMapa.DescargarCapa = function(LayerID, nombre, formato){
    var Extension = "." + formato.toLowerCase();
    var FileMimeType;

    var filename = nombre + Extension;

    var format;

    //const download = document.getElementById('download');
    switch (formato.toLowerCase()) {
      case "kml":      
        format = new KML();
        FileMimeType = 'data:application/vnd.google-earth.kml+xml;charset=utf-8;';
        break;
      case "geojson":
        format = new GeoJSON();
        FileMimeType = 'data:text/json;charset=utf-8,';
        break;
        
      case "json":
        format = new GeoJSON();
        FileMimeType = 'data:text/json;charset=utf-8,';
        break;
    }

    let Layer = window.map.getLayers().getArray()[LayerID];
    let sourceDeLaLayer =  Layer.getSource();
    const featuresDelLayer = sourceDeLaLayer.getFeatures();
    const data = format.writeFeatures(featuresDelLayer, {featureProjection: 'EPSG:3857'});

    console.log(data);

    var file = new Blob([data], {type: FileMimeType});
    if (window.navigator.msSaveOrOpenBlob) // IE10+
        window.navigator.msSaveOrOpenBlob(file, filename);
    else { // Others
        var a = document.createElement("a"),
        url = URL.createObjectURL(file);
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        setTimeout(function() {
            document.body.removeChild(a);
            window.URL.revokeObjectURL(url);  
        }, 0); 
    }
  }

**Comment by Agustinzero1** [comment]
> Why are you reading as a dataURL? If your features are styled using the original Google url they will be written back with that url as the icon style.

sorry, based on your answare, im figured out that the problem, is here in the upload Code (the upload that i use for a Form that i can upload a file, not the drag and drop)

```
//sube una capa pasada como Archivo por parametro, tambien
  //la coloca en el mapa y dispara la actualizacion de la hud
  window.layersDelMapa.UploadLayer = function(UloadedFile) {
    
    //guardo el nimero de la ultima capa existente en el mapa
    var lastLayerNumber = (map.getLayers().getArray().length)-1;

    //el archivo a subir
    var file = UloadedFile;

    //Guardo el nombre del archivo que se dropeo
    var file_name = file.name;
    var formato = file_name.split('.')[1];
    var Datos = null;
    if (file) {

      var reader = new FileReader();
      reader.onload = function () {
      
        //CREAMOS EL SOURCE de los datos con los resultados del reader de la capa segun su formato   
        switch(formato.toLowerCase()){
          case "kml":
            Datos = new VectorSource({
              url: reader.result,
              format: new KML()
            })
            break;
      
          case "json":
          Datos = new VectorSource({
            url: reader.result,
            format: new GeoJSON()
          })
          break;

          case "geojson":
            Datos = new VectorSource({
              url: reader.result,
              format: new GeoJSON()
            })
            break;
            
          case "igc":
            Datos = new VectorSource({
              url: reader.result,
              format: new IGC()
            })
            break;
      
          case "topojson":
            Datos = new VectorSource({
              url: reader.result,
              format: new TopoJSON()
            })
            break;
        }
        

        //creamos la capa con el source
        var vector = new VectorLayer({
          source: Datos
        });
        //agrego la capa al mapa
        map.addLayer(vector);

        //creo los metadatos
        var metadato = "Metadato de la capa " + file_name;

        //agrego la capa al listado
        window.layersDelMapa.AddLayerToMap( new LayerData(lastLayerNumber + 1,true, file_name.split('.')[0], file_name.split('.')[1].toUpperCase(), map.getLayers().getArray()[lastLayerNumber + 1], false, 1, false, metadato, ""));
        //actualizo la GUI
        window.layersDelMapaGUI.UpdateLayersOnGUI();
        //trato de hacerle zoom a la capa nueva
        Test_ZoomToLastLayer( window.map.getLayers().getArray()[window.map.getLayers().getArray().length-1], 0, 5);
      }
      reader.readAsDataURL(file);

    }
  };
```

**Comment by Agustinzero1** [comment]
I make a solution, sorry for the inconvenience i do this for do it :

    ```
//el archivo a subir
    var file = UloadedFile;
    var urlfile = URL.createObjectURL(file);

switch(formato.toLowerCase()){
          case "kml":
            Datos = new VectorSource({
              url: urlfile,
              format: new KML()
            })
            break;

ETC, the rest of the code
```

**Comment by mike-000** [comment]
That results in a path such as `blob:null/5154063b-0b76-49b3-9e69-36079f2b0169#m_ylw-pushpin` being written to the output instead of a long dataURL, so the dataURLs in the output were not the icons urls as dataURLs, they were the `<styleUrl>` properties of the placemarks appended to the dataURL of the KML file.  There are several places in https://github.com/openlayers/openlayers/blob/main/src/ol/format/KML.js where `if (!baseURI || baseURI == 'about:blank') {` is used.  Maybe those conditions should be enhanced as it seems inappropriate to use a dataURL (or blob) as a baseURI?

**Comment by Agustinzero1** [comment]
this was the finla code, but i no see problems with the style...

```
    //sube una capa pasada como Archivo por parametro, tambien
    //la coloca en el mapa y dispara la actualizacion de la hud
    window.layersDelMapa.UploadLayer = function(UloadedFile) {
      
    //guardo el nimero de la ultima capa existente en el mapa
    var lastLayerNumber = (map.getLayers().getArray().length)-1;

    //el archivo a subir
    var file = UloadedFile;
    // creo una url con el archivo
    var fileURL = URL.createObjectURL(file); 

    //Guardo el nombre del archivo que se cargo
    var fileName = file.name;

    //tomo el formato del archivo subido
    var fileFormat = fileName.split('.')[1];
    
    //declaro elvector source que mas abajo se usar
    var vectorSourceFormated =  null;

    //compruebo si hay un archivo
    if (file) {
      //seteamos el formato al VectorSource que tendra la layer resiltado 
      switch(fileFormat.toLowerCase()){
        case "kml":
          vectorSourceFormated = new VectorSource({ format: new KML() });
          break;
    
        case "json":
          vectorSourceFormated = new VectorSource({ format: new GeoJSON() });
        break;

        case "geojson":
          vectorSourceFormated = new VectorSource({ format: new GeoJSON() });
          break;
          
        case "igc":
          vectorSourceFormated = new VectorSource({ format: new IGC() });
          break;
                
        case "topojson":
          vectorSourceFormated = new VectorSource({ format: new TopoJSON() });
          break;
      }
      
      //seteo el url del kml generado
      vectorSourceFormated.setUrl(fileURL);

      //creamos la capa con el source
      var vector = new VectorLayer({ source: vectorSourceFormated });

      //agrego la capa al mapa
      map.addLayer(vector);

      //creo los metadatos
      var metadato = "Metadato de la capa " + fileName;

      //agrego la capa al listado
      window.layersDelMapa.AddLayerToMap( new LayerData(lastLayerNumber + 1,true, fileName.split('.')[0], fileName.split('.')[1].toUpperCase(), map.getLayers().getArray()[lastLayerNumber + 1], false, 1, false, metadato, ""));
      
      //actualizo la GUI
      window.layersDelMapaGUI.UpdateLayersOnGUI();
      
      //trato de hacerle zoom a la capa nueva
      Test_ZoomToLastLayer( window.map.getLayers().getArray()[window.map.getLayers().getArray().length-1], 0, 5);
    }
  };
```

**Comment by mike-000** [comment]
It works and the output is much smaller but I think it would be more correct if `<styleUrl>#m_ylw-pushpin</styleUrl>` in the placemarks in the original KML was written back as `<styleUrl>#m_ylw-pushpin</styleUrl>` in the output, not as something like `<styleUrl>blob:null/5154063b-0b76-49b3-9e69-36079f2b0169#m_ylw-pushpin</styleUrl>`.

**Comment by Agustinzero1** [comment]
> It works and the output is much smaller but I think it would be more correct if `<styleUrl>#m_ylw-pushpin</styleUrl>` in the placemarks in the original KML was written back as `<styleUrl>#m_ylw-pushpin</styleUrl>` in the output, not as something like `<styleUrl>blob:null/5154063b-0b76-49b3-9e69-36079f2b0169#m_ylw-pushpin</styleUrl>`.

and how can i do that ? i need to modify the Download part ?

**Comment by mike-000** [comment]
It cannot be done in your application code, ol/format/KML would need to be updated handle data and blob urls similar to how it handles 'about:blank'
