### ISSUE TITLE
Bug: DrawGeometry on rotated map

### ISSUE THREAD

**Issue by bojanbizjak** [openlayers/openlayers#11799]
**Describe the bug**
We draw a Point geometry that is in the correct place on the urotated map. On a rotated map, points are drawn in the wrong location.

Unrotated
![urotated](https://user-images.githubusercontent.com/12731463/100979944-cc813480-3544-11eb-8e8a-39b64e2a292a.png)
Rotated
![rotated](https://user-images.githubusercontent.com/12731463/100979972-d6a33300-3544-11eb-9e1b-23d0fcd53782.png)

**To Reproduce (ol: 6.4.3)**
1. Create ol.layer.VectorImage
2. User layer postrender event
3. Obtain vectorContext with getVectorContext(event)
4. Create Point geometry -> vectorContext.setStyle(style) ->  vectorContext.drawGeometry(point)

**Comment by mike-000** [comment]
There is an problem with VectorContext for VectorImage layers.  Drawing is also misplaced if the layer` imageRatio` is not 1.
