### ISSUE TITLE
converting extent to lat long 

### ISSUE THREAD

**Issue by shitathakin** [openlayers/openlayers#11794]
Hi. 
I have a bbox extent in the form  
[-2460660.814556394,-2935181.886150768,2460660.814556394,2935181.886150768] 
I want to convert it into lon/lat coords, probably using proj.toLonLat(), but am not sure how I can do it on an entire extent. Hoping I dont have to split it up, transform it, and then reconnect it again. 
Thanks in advance.

**Comment by ahocevar** [comment]
```js
import {transformExtent} from 'ol/proj';

transform(extent, 'EPSG:3857', 'EPSG:4326');
