### ISSUE TITLE
WMTS source - default axis orientation

### ISSUE THREAD

**Issue by huberts** [openlayers/openlayers#11795]
Hello!

I would like to set default axis orientation in WMTS source, used in line:

[https://github.com/huberts/openlayers/blob/77e6c3a4ab3cac6622c61bac84ceb547ddae65e0/src/ol/source/WMTS.js#L446](url)

I work with projections from Poland, EPSG:2176 - EPSG:2180, and in the standard Proj4 definitions (obtained from epsg.io) there is nothing said about axis orientation. I assume default is 'neu', and this default should be used in the WMTS source definition.

Best regards,
Hubert

**Comment by mike-000** [comment]
The default is enu as most projections use enu.  If the WTMS is using neu you need to include `+axis=neu` in the proj4 definition.  The official epsg.org does define EPSG:2180 as Northing Easting https://epsg.org/crs_2180/ETRS89-Poland-CS92.html so epsg.io is not correct in this case.

**Comment by huberts** [comment]
@mike-000, thank you for your response. In that case I will upgrade my Proj4 configuration (as I already had, btw). I am closing the issue and withdraw my PR.
