### ISSUE TITLE
ol.layer.VectorImage: text style rotate with the view even though rotateWithView is false

### ISSUE THREAD

**Issue by bojanbizjak** [openlayers/openlayers#11802]
I would expect the text style not to rotate with the view.

ol: v6.4.3

![text](https://user-images.githubusercontent.com/12731463/101187208-5d930100-3654-11eb-97df-52890ed06a84.png)

It is to be expected that this will be settled or some other solution is suggested here.

**Comment by mike-000** [comment]
A VectorImage layer is similar to using `renderMode: 'image'` in earlier versions https://openlayers.org/en/v5.3.0/apidoc/module-ol_layer_Vector-VectorLayer.html  It is not well documented in the current version.

**Comment by bojanbizjak** [comment]
I obviously forgot about that fact. Thanks.
