### ISSUE TITLE
OpenLayers 6.4.3 vector objects misaligned with AGM(Angular Google Maps)

### ISSUE THREAD

**Issue by RobertVogt** [openlayers/openlayers#11801]
The further you get from a whole integer the more misaligned OpenLayers and AGM become.

Here is a StackOverflow explaining problem and steps taken
https://stackoverflow.com/questions/65081024/zoom-issue-between-openlayers-6-4-3-and-agm-angular-google-maps

The issue is definitely a zoom problem where the further away from a whole integer you get the worse the misalignment is.

I've created a StackBlitz here to demostrate the problem. Just use the "Draw" button and the top to trace one of the fields. Click "Stop Drawing" and pan the map.

If you comment/uncomment in app.mapValues.ts you can clearly see the problem.
//************ */ Stays aligned ***************
//public static googleZoom = 17;

//************ */ Missaligned *****************
public static googleZoom = 17.5;

https://stackblitz.com/edit/angular-openlayer-play-n5brr8?file=src%2Fapp%2Fapp.component.ts

Current behavior
Google imagery and Openlayers become misaligned on decimal zoom.

Expected/desired behavior
Google imagery and OpenLayers stay aligned

angular-google-maps, Angular, & any other relevant dependency versions

**Comment by mike-000** [comment]
It looks like the Google map is snapping to integer zoom levels so constraining the OpenLayers map resolutions may help.  Also the Google map has animations which you cannot control so turning off all OpenLayers animations might help the synchronisation

```
        MapValues.view = new View({
            center: fromLonLat([37.41, 8.82]), // [this.OlCoords[0], this.OlCoords[1]],
            zoom: MapValues.googleZoom, 
            projection: 'EPSG:3857',
            maxZoom: 20,
            minZoom: 5,
            constrainResolution: true,
            smoothResolutionConstraint: false,
        });
        MapValues.map = new Map({
            target: 'map',
            view: MapValues.view,
            layers: [this.vector],
            controls: defaultControls({
              rotate: false,
              zoomOptions: { duration: 0 }
            }),
            interactions: defaultInteractions({
              altShiftDragRotate: false,
              dragPan: false,
              zoomDuration: 0,
            }).extend([new DragPan({kinetic: null})]),
        });
```
