### ISSUE TITLE
Dashed line hit detection?

### ISSUE THREAD

**Issue by lotrmj** [openlayers/openlayers#11805]
Hi, 

What if my map's primary objects are dashed lines? Is there a nice hit detection solution? If I click on that empty area between dashes of a line I want a hit for that line object to occur. It seems the hit doesn't occur now...

I have figured out one solution to have "fake" duplicate line symbol with 0.01 color opacity underneath a dashed line, but the problem is that I can see that ghost line with my eyes... And it seems I can't set lower opacity like 0.001

Any suggestions, guys? :)

**Comment by mike-000** [comment]
Transparent fill is hit detected but that isn't helpful for LineStrings.  You can make any geometry invisible but detectable by hiding the layer below an opaque base layer, or in your case a second vector layer using the same source https://codesandbox.io/s/tender-hawking-wdlnj

**Comment by lotrmj** [comment]
> Transparent fill is hit detected but that isn't helpful for LineStrings. You can make any geometry invisible but detectable by hiding the layer below an opaque base layer, or in your case a second vector layer using the same source https://codesandbox.io/s/tender-hawking-wdlnj
> 
> If using your duplicate line approach you can improve slightly on 0.01 as JavaScript handles opacity internally as multiples of 1/255, and minimally opaque white can be defined as `'#ffffff01'`.

Thank you for great ideas!

**Comment by tschaub** [comment]
@lotrmj - in #11874, I've proposed that we change the hit detection behavior to ignore the dash style when considering lines.
