### ISSUE TITLE
 Render events for VectorImage layers

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11804]
**Describe the bug**
As well as the rotation and imageRatio context issues observed in #11799 the VectorImage layer's render events are only firing when the vector renderer updates the image. If the image is not updated (for example when the extent needed for a rotated image does not change) there are no events.

**To Reproduce**
Rotate the view in https://codesandbox.io/s/focused-goldstine-orxvu?file=/main.js and observe the background changing as events fire.  After the rotated extent reaches a maximum the background no longer changes as the rotation continues.

**Expected behavior**
Similar to other image layers for example https://codesandbox.io/s/charming-field-4o18n?file=/main.js and https://codesandbox.io/s/gifted-kepler-rh8p5?file=/main.js there should be render events for the layer whenever the map renders.  Events for the vector layer renderer rendering to the image may still be useful, but they are not true layer events.

**Comment by ahocevar** [comment]
Not sure if this is the expected behavior. Since this issue arises from obervations made in #11799, I would think that the render events just provide the wrong rendering context. They should provide the rendering context of the image (i.e. the image the vector layer renderer creates), not the context the vector image renderer passes to the map renderer.

**Comment by mike-000** [comment]
Currently I think the context is the vector layer renderer's context for the unrotated image extent it is rendering to, but the framestate is for the rotated view the image will then be then rendered to, hence the misplaced immediate rendering when rotated.  However for render events to work correctly they should fire when the image is rendered to the map.  A VectorImage layer which only fires events when the image is updated by the vector renderer would not work correctly when, for example, it was rotated when using a layer swipe, but an ImageWMS will work even when the underlying requested extent does not change https://codesandbox.io/s/polished-hill-i9oxi?file=/main.js

**Comment by ahocevar** [comment]
Layer swipe is indeed a good use case.

Well, to change this, the VectorImageLayer renderer would need to **not** override the `preRender()` and `postRender()` methods with a noop, and instead stop relaying the underlying VectorLayer renderer's render events.
