### ISSUE TITLE
The coexistence of Tile and wms map service causes tile loading freeze

### ISSUE THREAD

**Issue by mylove10086** [openlayers/openlayers#11812]
When I used the following code to load the online image map and the wms layer published by geoserver at the same time, I found a problem. If the wms layer cannot be loaded or the loading is slow, the map loaded by the tile will also be stuck and unable to load the online image map, instead of loading their own.  
var rootLayer = new ol.layer.Tile({
            source: new ol.source.XYZ({
                url: 'http://mt2.google.cn/vt/lyrs=y&hl=zh-CN&gl=CN&src=app&x={x}&y={y}&z={z}&s=G'
            }), //加载谷歌影像地图
            preload: Infinity
        });

        view = new ol.View({
            center: [113, 23],
            projection: 'EPSG:4326',
            zoom: 10
        });
        map = new ol.Map({
            layers: [rootLayer],
            target: 'map',
            view: view
        });
        var format = 'image/png';
        var wmsSource = new ol.source.TileWMS({
            url: 'http://localhost:8080/geoserver/pgis/wms',//端口号要改成自己的
            params: {
                'FORMAT': format,
                'VERSION': '1.1.1',
                tiled: true,
                "LAYERS": 'pgis:citypolygon',
                "exceptions": 'application/vnd.ogc.se_inimage',
            },
            serverType: 'geoserver',
            crossOrigin: 'anonymous',
        });
        var wmsLayer = new ol.layer.Tile({
            source: wmsSource,
        });
        map.addLayer(wmsLayer);
The map will be very stuck at this time。
If I comment out the map.addLayer(wmsLayer); line. The tile layer will not have the problem of lag.
Is there any solution so that the loading of each layer does not affect each other?

**Comment by ahocevar** [comment]
Duplicated in #11823
