### ISSUE TITLE
Kashmir Conflicts

### ISSUE THREAD

**Issue by thomas-siozos** [openlayers/openlayers#11814]
**Describe the bug**
Kashmir conflicts on Bing Maps.

**Issue**
Bing Maps from India look:
![bingmaps](https://user-images.githubusercontent.com/34145662/101504078-7b75a400-397b-11eb-8437-daea23c094b5.png)

Bing Maps through ol:
![olmaps](https://user-images.githubusercontent.com/34145662/101504161-91836480-397b-11eb-82c2-fd73bc115a21.png)

If you look closely, the borders are different, how can i fix that?

**Expected behavior**
Can you tell me if in openlayers there is any way to fix that?

**Comment by jipexu** [comment]
Hi
humm that means that bingmaps provide two versions of this borders ... 
what openlayers can do ? as is not map provider ....  perhaps point on the map version that you want on your script ??

**Comment by mike-000** [comment]
I think Bing autodetects user location although it can be overridden with the Bing `userRegion` parameter. That is not directly supported by OpenLayers but you could append `'&userRegion=IN'` to your API key.

**Comment by thomas-siozos** [comment]
@jipexu Yes, google maps and bing maps provides multiple versions of maps depending your location. More: https://en.wikipedia.org/wiki/List_of_territorial_disputes

@mike-000 Thank you. It works finally! :ok_hand:

**Comment by thomas-siozos** [comment]
@mike-000 We're using openlayers version: 2.13.1, can you tell me if there is any way to do that? In current version works but in 2.13.1 can't add parameters to api key.

**Comment by mike-000** [comment]
It looks like OpenLayers 2 called encodeURIComponent() on the API key which prevents the `&` working, but it had a `metadataParams` option you can use for additional pararmeters http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Layer/Bing-js.html#OpenLayers.Layer.Bing.metadataParams
```
            var road = new OpenLayers.Layer.Bing({
                name: "Road",
                key: apiKey,
                metadataParams: { userRegion: 'IN' },
                type: "RoadOnDemand"
            });
            var hybrid = new OpenLayers.Layer.Bing({
                name: "Hybrid",
                key: apiKey,
                metadataParams: { userRegion: 'IN' },
                type: "AerialWithLabelsOnDemand"
            });
            var aerial = new OpenLayers.Layer.Bing({
                name: "Aerial",
                key: apiKey,
                metadataParams: { userRegion: 'IN' },
                type: "Aerial"
            });
```
Having a similar option in the current API might be a nicer long term solution for this issue and #11788

**Comment by thomas-siozos** [comment]
I tried it already but didn't work, i don't know why

**Comment by mike-000** [comment]
It works for me, but it seems the `userRegion` setting only works with the `...OnDemand` types

**Comment by thomas-siozos** [comment]
Sorry, but what do you mean with ...OnDemand types?

**Comment by mike-000** [comment]
`type: "RoadOnDemand"` or `type: "AerialWithLabelsOnDemand"` or (`imagerySet` in the current API).

**Comment by thomas-siozos** [comment]
It works at least, thank you very much for your help!

**Comment by umangutkarsh** [comment]
Hey @thomas-siozos , how did you resolve this issue.

**Comment by thomas-siozos** [comment]
> Hey @thomas-siozos , how did you resolve this issue.

Hey @umangutkarsh, as far as I remember (it's been 3+ years) with @mike-000's reply [here](https://github.com/openlayers/openlayers/issues/11814#issuecomment-740728445)

**Comment by thomas-siozos** [comment]
> Hey @thomas-siozos , how did you resolve this issue.

Hey @umangutkarsh, as far as I remember with @mike-000's reply [here](https://github.com/openlayers/openlayers/issues/11814#issuecomment-740981599). I added the region in the `metadataParams` property, but I don't remember sth else tbh.
