### ISSUE TITLE
jsdeliver CDN (from quick start) does not appear to be working.

### ISSUE THREAD

**Issue by Jezternz** [openlayers/openlayers#11813]
**Describe the bug**
The recommended CDN link on the quick start page is "https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css", this however does not appear to be working as expected, it may be worth talking to jsdelivr or finding an alternative.

**To Reproduce**
Visit https://openlayers.org/en/latest/doc/quickstart.html
Use the css cdn described (or visit it directly) https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css

**Expected behavior**
Expected to return css, but instead got a message "Package size exceeded the configured limit of 50 MB. Try https://github.com/openlayers/openlayers.github.io/tree/master/en/v6.4.3/css/ol.css instead."

**Comment by fredj** [comment]
Hi @Jezternz , the link is working for me: I get the css file without any error message

**Comment by Jezternz** [comment]
@fredj your right! Maybe it was either fixed or it was my other environment, thanks!
