### ISSUE TITLE
Distribute the dist files in the npm package

### ISSUE THREAD

**Issue by williamdes** [openlayers/openlayers#11826]
Currently at phpMyAdmin we have a script that syncs node modules to a vendor folder.

But the files we have in this folder are the ones you distribute at GitHub: https://github.com/openlayers/openlayers/releases/download/v6.4.3/v6.4.3-dist.zip

The script actually avoids updating openlayers, and it is a bad idea: https://github.com/phpmyadmin/phpmyadmin/blob/251753bf4d74086639197c998e1f6f1e1fa84372/scripts/sync-js-vendor-files.sh#L17

Here are your files: https://github.com/phpmyadmin/phpmyadmin/tree/master/js/vendor/openlayers

Would you accept to distribute on the "ol" package or another one your dist files ?

**Comment by ahocevar** [comment]
Actually we try to steer users away from using what we call the legacy build, which is what you use. Looking at your package.json, it seems you run js build steps already, so this should be an easy change. Let me know if you need help with that. If so, please point me to the places in your code base where you use OpenLayers.

**Comment by williamdes** [comment]
Thank you for the response
We already upgraded from a very old version in https://github.com/phpmyadmin/phpmyadmin/pull/16303

All our code base uses should be in https://github.com/phpmyadmin/phpmyadmin/pull/16303

Thank you for helping us :)

**Comment by ahocevar** [comment]
Can you create a ticket in https://github.com/phpmyadmin/phpmyadmin for that and provide some context? I don't see when or where the script you pointed to (https://github.com/phpmyadmin/phpmyadmin/blob/251753bf4d74086639197c998e1f6f1e1fa84372/scripts/sync-js-vendor-files.sh) is run.

**Comment by williamdes** [comment]
> Can you create a ticket in https://github.com/phpmyadmin/phpmyadmin for that and provide some context? I don't see when or where the script you pointed to (https://github.com/phpmyadmin/phpmyadmin/blob/251753bf4d74086639197c998e1f6f1e1fa84372/scripts/sync-js-vendor-files.sh) is run.

Well the script is never run by robots, only humans run it after updating the node modules. Just a manual process that we hope to remove someday

**Comment by williamdes** [comment]
No idea to improve this ?

**Comment by ahocevar** [comment]
@williamdes Unfortunately I did not find time to dig deeper into this. As I said earlier, it should be easy to fix your build process, and I'm still willing to help. What I meant in my [above comment](https://github.com/openlayers/openlayers/issues/11826#issuecomment-744070775) is not where a script runs the OpenLayers update, but which scripts are involved in running the updates of other JavaScript dependencies. Because that's where I need to hook into. So you're saying `sync-js-vendor-files.sh` is only run manually? Then I'll take a quick look if I can trigger an appropriate OpenLayers build from that script.

**Comment by williamdes** [comment]
> So you're saying sync-js-vendor-files.sh is only run manually? Then I'll take a quick look if I can trigger an appropriate OpenLayers build from that script.

Yes, this is the only script that syncs installed node_modules files to the js/vendor folder

So the process is:
- install a node module using yarn
- add it to the sync script
- sync it
- push changes

For this lib, in the JS sync script there is probably more work to re-build the openlayers module from source

**Comment by ahocevar** [comment]
Alright, I just created phpmyadmin/phpmyadmin#16959. In addition to getting OpenLayers updates as part of the normal js dependency update process, you get an optimized OpenLayers build with 318kB instead of >1MB, like you have currently.

**Comment by williamdes** [comment]
Thank you so much!
Just to know, what was enabled and took so much space?

**Comment by ahocevar** [comment]
You were using the full build which contains the whole public API of OpenLayers. Usually applications only need a fraction of that, so we discourage the use of the full build. Importing only what the application needs will significantly reduce the bundle size.

**Comment by williamdes** [comment]
Thank you for all your work !
