### ISSUE TITLE
The coexistence of Tile and wms map service causes tile loading freeze

### ISSUE THREAD

**Issue by mylove10086** [openlayers/openlayers#11823]
When I used the following code to load the online image map and the wms layer published by geoserver at the same time, I found a problem. If the wms layer cannot be loaded or the loading is slow, the map loaded by the tile will also be stuck and unable to load the online image map, instead of loading their own.
var rootLayer = new ol.layer.Tile({
source: new ol.source.XYZ({
url: 'http://mt2.google.cn/vt/lyrs=y&hl=zh-CN&gl=CN&src=app&x={x}&y={y}&z={z}&s=G'
}), //加载谷歌影像地图
preload: Infinity
});

    view = new ol.View({
        center: [113, 23],
        projection: 'EPSG:4326',
        zoom: 10
    });
    map = new ol.Map({
        layers: [rootLayer],
        target: 'map',
        view: view
    });
    var format = 'image/png';
    var wmsSource = new ol.source.TileWMS({
        url: 'http://localhost:8080/geoserver/pgis/wms',//端口号要改成自己的
        params: {
            'FORMAT': format,
            'VERSION': '1.1.1',
            tiled: true,
            "LAYERS": 'pgis:citypolygon',
            "exceptions": 'application/vnd.ogc.se_inimage',
        },
        serverType: 'geoserver',
        crossOrigin: 'anonymous',
    });
    var wmsLayer = new ol.layer.Tile({
        source: wmsSource,
    });
    map.addLayer(wmsLayer);
The map will be very stuck at this time。
If I comment out the map.addLayer(wmsLayer); line. The tile layer will not have the problem of lag.
Is there any solution so that the loading of each layer does not affect each other?

**Comment by ahocevar** [comment]
The tile queue is shared across all layers. But the number of simultaneously loading tiles can ba configured with `ol/Map`'s `maxTilesLoading` parameter. The default is `16`. Set it to a higher value, or even to `Infinity` if you're not afraid of overwhelmning the browser.

**Comment by mylove10086** [comment]
But the problem is not the map freeze caused by preload: Infinity. Even if I don't set preload: Infinity. When the wms layer in geoserver fails to respond in time. google map could not be loaded.
My opinion is that openlayer is synchronized when requesting the geoserver's wms layer, and other requests cannot be sent when the request is not responding.

**Comment by mylove10086** [comment]
![image](https://user-images.githubusercontent.com/41406024/101875479-aa7f5600-3bc5-11eb-827a-a1d07fd30610.png)
The above picture I turned off is the map after geoserver, the google basemap has not been loaded
When opening geoserver, the Google basemap is very smooth

**Comment by mylove10086** [comment]
![1](https://user-images.githubusercontent.com/41406024/101875931-7b1d1900-3bc6-11eb-9f08-afd5d1cef79c.png)

**Comment by mylove10086** [comment]
![1](https://user-images.githubusercontent.com/41406024/101877714-6e4df480-3bc9-11eb-98c7-39ab66b26f91.jpg)
The above picture shows the situation where the Google basemap cannot be loaded when the geoserver is closed。
When I open the geoserver, the Google basemap is very smooth
![2](https://user-images.githubusercontent.com/41406024/101878004-cf75c800-3bc9-11eb-9d17-af53d8c306ce.jpg)

**Comment by ahocevar** [comment]
I was not expecting the `preload: Infinity` config to be the problem. My advice above was to avoid slow servers clogging the tile queue so fast servers cannot get additional tiles. If you're expecting a server to not be available at all, you'll need to configure the source with a tileLoadFunction that handles this in addition. See https://github.com/openlayers/openlayers/issues/11552#issuecomment-725544383.
