### ISSUE TITLE
Breaking PointerEvent change implemented on minor version with no errors thrown

### ISSUE THREAD

**Issue by frozeng** [openlayers/openlayers#11843]
**Describe the bug**
The [removal of the pointer-events polyfill](https://github.com/openlayers/openlayers/issues/11138) was a breaking change [on 9% of all browsers](https://caniuse.com/?search=PointerEvent), accompanied by only a minor OL semantic version increment.
> MINOR version when you add functionality in a backwards compatible manner

Under your “[Renderers and Browser Support](https://openlayers.org/en/latest/doc/tutorials/background.html)” it states: 

> OpenLayers runs on all modern browsers that support HTML5 and ECMAScript 5

Of which iOS 12 (which doesn't have PointerEvent)
* Has > 1% of global market share
* Had an update on 14 Dec 2020
* Fully supports ECMAScript 5 and HTML5

The worst part about this change is it silently breaks:

**Expected behavior**

1. Throw an Error https://openlayers.org/en/latest/doc/errors/ if the PointerEvent is not available natively.
    1. Browser feature detection errors have precedence e.g. `63: Support for the OES_element_index_uint WebGL extension is mandatory for WebGL layers.`
    1. Developers will get feedback from their error reporting that there is an issue and debugging would be made much easier.
2. Add some kind of browser support table to the documentation, with minimum browser versions which work / are polyfillable – and maybe not change this without a major version increment.

**Comment by ahocevar** [comment]
Thanks for raising this concern, @frozeng. Although the release notes [clearly mention](https://github.com/openlayers/openlayers/releases/tag/v6.4.0) the removal of the pointer events polyfill, I agree that the README could make it more clear which browsers require a polyfill. We'd appreciate a pull request for that.

Also a preflight check with a failing assertion like you suggested might make sense. But for end users, the symptoms would not change. It would only make things easier to debug.

Note that Apple turned on Pointer Events support by default in [Safari/iOS 13](https://developer.apple.com/documentation/safari-release-notes/safari-13-release-notes) already, in September 2019, not Safari/iOS 14 as your source states.

**Comment by frozeng** [comment]
Thanks for your quick response:

The completely silent nature is the real difficulty. As it’s just a listener of an event type which is never fired there is no chance of feedback anything has gone wrong.

This is different from the usual failure of using an unsupported “modern API” e.g. `'Promise' is undefined` or `Object doesn't support this action`.

The other OL `assert()` Error codes are all about helping the developer (rather fixing symptoms). Had any errors been surfaced I would have known soon after release there was a problem on legacy platforms.
