### ISSUE TITLE
ImageStyle - Fill/stroke color adjustment does not work

### ISSUE THREAD

**Issue by michalzielanski** [openlayers/openlayers#11841]
Dynamically adjustment the style while rendering features does not work.
See example: https://codesandbox.io/s/cold-silence-lbcpg?file=/main.js
The circles should be red or green, unfortunately they are gray.

**Comment by M393** [comment]
RegularShapes are rendered only once (in the constructor call) to an intermediate canvas which is cached.
Changing its style is not supported, there is also no setFill/setStroke. If you need different styles you can create multiple RegularShapes which will be better for your performance anyway.

**Comment by mike-000** [comment]
You can force a render of Circle style by calling `.setRadius()` after changing other properties.  That would typically be used to size a circle based on a feature property (e.g. population of a city), it is not an efficient way of changing between a small range of colors.

**Comment by michalzielanski** [comment]
I have a large spread of radius and colors, so I don't know if keeping separate styles in the cache makes sense. Thank you @M393, @mike-000 for the explanation.
