### ISSUE TITLE
Improve getFeaturesInExtent for Vector Tile Sources

### ISSUE THREAD

**Issue by reyemtm** [openlayers/openlayers#11840]
Currently `getFeaturesInExtent` "may include features whose geometries do not intersect the extent", which is seems odd and counterintuitive. My suggestion would be to not include features in the extent.

One idea to improve this would be to implement something like - 
 - fetch vector tiles at maxZoom using the extent as the bounding box
 - convert these to geojson
 - test the geojson features to see if they intersect the extent
 - test to see if they have already been added, if not add them to a new geojson featureCollection
 - return the geojson featureColletion

For vector tile sources with low resolution this will return spurious results, so another option would be to limit it to tile sources with a maxZoom greater than or equal to 14, with an override in the options - `force: true`.

see - https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html#getFeaturesInExtent
and - https://stackoverflow.com/questions/52209573/api-docs-getfeaturesinextent

**Comment by MoonE** [comment]
The VectorSource's getFeaturesInExtent method only checks bounding boxes. If you want to check if the geometry intersects the extent  you can do this with https://openlayers.org/en/main/apidoc/module-ol_geom_Polygon-Polygon.html#intersectsExtent
Check out this sandbox: https://codesandbox.io/s/featuresinextent-k0yrs?file=/src/index.js

**Comment by reyemtm** [comment]
Ok, that looks like what I need, I'll check it out. Still, if that method
works as expected, I wonder why not just make that method the default here,
maybe with an option to just return the bounding box features, because the
current results are very strange.

**Comment by reyemtm** [comment]
Does this work with VectorTile sources? Currently I am getting:

`f.getGeometry(...).intersectsExtent is not a function`

**Comment by mike-000** [comment]
If the source format is MVT you will need to specify `featureClass: Feature` in the MVT options to access the features' full geometry.

Vector layers have a `forEachFeatureIntersectingExtent` method (used in the Box Selection example).  Maybe vector tile sources could also have this method where the featureClass is Feature.
