### ISSUE TITLE
MapboxVectorLayer does not work with non-hosted Mapbox compatible styles

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11847]
**Describe the bug**
There seems no obvious reason why MapboxVectorLayer should not be used with other compatible styles such as hosted by MapTiler. However if not a `mapbox://` path  https://github.com/openlayers/openlayers/blob/main/src/ol/layer/MapboxVector.js#L101 uses the TileJSON url as the OpenLayers source's tile url, resulting in an invalid pbf error when attempting to use the layer (which was created without errors).

**Expected behavior**
If not a `mapbox://` path load the TileJSON and use its tile url(s) as in ol-mapbox-style's `setupVectorLayer`.

**Comment by ahocevar** [comment]
Yes, this is currently a limitation. To properly fix that, TileJSON parsing would have to be made available separate from `ol/layer/TileJSON` (which is only for raster tiles), e.g. in an `ol/format/TileJSON`. If someone wants to take that on, it would be a nice addition.

In the meantime, you could use [ol-mapbox-style](https://npmjs.com/package/ol-mapbox-style), which is used by `ol/layer/MapboxVector` anyway, directly. Something like this:
```js
import Map from `ol/Map`;
import addLayers from `ol-mapbox-style`;

const map = new Map({
  // map configuration, layers etc.
});
addLayers(map, 'path/to/your/style.json').then(() => {
  // work with the Mapbox layers that are now added to the map`s `layers` collection.
});

**Comment by mike-000** [comment]
Yes, there is certainly much more which could be done to improve TileJSON both for raster and vector. Some of the MapTiler examples hard code custom tile grids, but they could be obtained from the JSON in the same way as in this Ordnance Survey example https://github.com/OrdnanceSurvey/OS-Data-Hub-API-Demos/blob/master/OSVectorTileAPI/OpenLayers/map.js#L52-L71  Mapbox however simply assumes a standard EPSG:3857 grid, so for mapbox-gl.js compatible sources it should be sufficient to fetch the TileJSON url and use its `tiles` property to set the VectorTileSource's url(s).
