### ISSUE TITLE
512px WMS tile Layer clipped when wrapped

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/openlayers#11854]
**Describe the bug**
Section of a wrapped WMS layer is being clipped in the outermost resolution when requesting 512px tiles. 256px tiles do not have this issue.

**To Reproduce**
1. Go to https://codepen.io/benjaki/details/qBajozY
2. See error

**Expected behavior**
Imagery to not get clipped

**Comment by mike-000** [comment]
Your tile grid resolutions you are using mean the tiles do not align with the extent.  The maximum resolution for the grid should be 360/512 = 0.703125 (not 0.0703125) where a single tile is exactly one world wide.

**Comment by Benjaki2** [comment]
That works. Thanks @mike-000 !
