### ISSUE TITLE
Removing vector from group throws an error

### ISSUE THREAD

**Issue by AleMScof** [openlayers/openlayers#11857]
**Describe the bug**
Removing an ol/layer/Vector from an ol/layer/Group generates a js error when no listeners keys are associated to that specific layer

**To Reproduce**
1. Push an ol/layer/Vector to a group `group.getLayers().getArray().push(vector);`
2. Remove the same layer `groupLayer.getLayers().remove(vector);`
3. function `handleLayersRemove_` goes in error due to undefined listeners for the given layer

**Expected behavior**
It should remove the layer from the group without throwing the error

**Temporary fix**
Checking if the listeners key for the given layer are defined
`e.prototype.handleLayersRemove_ = function(t) { ` 
`  var e = o(t.element);`
      `if (typeof this.listenerKeys_[e] !== "undefined")`
           `   this.listenerKeys_[e].forEach(H),delete this.listenerKeys_[e], this.changed() }`

**Comment by MoonE** [comment]
You should use `group.getLayers().push(vector);` otherwise the `ol/Collection` won't fire the necessary events / update its length.
