### ISSUE TITLE
Overlay - stop specific events instead of stopping all events

### ISSUE THREAD

**Issue by HesamSe** [openlayers/openlayers#11861]
Currently, there is no API that we can specify events to stop. if we set `stopevent : true`, it stops all events.

It would be better if `stopevent` property in overlay get an array of events instead of boolean.
For example: 
```
const overlay = new Overlay({
  element: document.getElementById('marker'),
  stopEvent: ['click','mousedown'],
});
```

**Comment by shayantabrizi** [comment]
No news on this?
