### ISSUE TITLE
Example on Vector Tile Selection not reproducible

### ISSUE THREAD

**Issue by Biosphakus** [openlayers/openlayers#11869]
**Describe the bug**
[This](https://openlayers.org/en/latest/examples/vector-tile-selection.html) turns out to be not reproducible for me under Firefox Developer Edition 85.0b4. The map is dipslayed but an error is thrown in the console and selection of features won't work.

**To Reproduce**
1. Copy index.html and main.js and run build with node.
2. Open built index.html.
3. Error in console
`Assertion failed. See https://openlayers.org/en/v6.0.1/doc/errors/#28 for details.`
4. When removing `renderMode: 'vector'` from the example code, the error gets replaced by:
`Uncaught TypeError: s.getFeatures is not a function`

In any case, selection of features won't work. I had tried this with a custom tile server and got the same error. After that, I tried the example from the web page. Turns out the error persists. This might be an error on my end but just wanted to note: Trying to style selected features of the vector tileset with [this](https://openlayers.org/en/latest/examples/select-hover-features.html) or [that](https://openlayers.org/en/latest/examples/select-hover-features.html) approach returns an error saying that setStyle is not a function. 

**Expected behavior**
Selection of features should work, no errors should show up in the log.

**Comment by ahocevar** [comment]
> Assertion failed. See https://openlayers.org/en/v6.0.1/doc/errors/#28 for details.

Looks like you are building with an old version of OpenLayers. v6.0.1? The latest is v6.5.0.

**Comment by Biosphakus** [comment]
Turns out this was indeed the cause of the error. Sorry for not checking this before and thanks a lot for your help.
