### ISSUE TITLE
v6.5.0: Can't find variable: ol

### ISSUE THREAD

**Issue by vsevjednom-cz** [openlayers/openlayers#11870]
Everything works without problem in usual web browsers but: I'm using `cutycapt` for create printscreen of the map in terminal. It creates white page when I use version 6.5.0. Old version 6.4.3 is ok. With `wkhtmltoimage` is the same problem. It prints this warnings when I use `--debug-javascript`: 

> Warning: https://openlayers.org/en/latest/build/ol.js:1 SyntaxError: Unexpected identifier 't'. Cannot declare a lexical variable twice: 't'.
> Warning: https://viglino.github.io/ol-ext/dist/ol-ext.js:23 ReferenceError: Can't find variable: ol
> Warning: https://mywebpage ReferenceError: Can't find variable: ol

**Comment by mike-000** [comment]
That is the same legacy build error as noted in https://github.com/openlayers/openlayers/issues/11866#issuecomment-751512826 It can also be seen when opening the home page https://openlayers.org/ in Internet Explorer as the small map at the top of the page still uses the legacy build.

**Comment by MoonE** [comment]
This should be fixed by #11872, can you confirm this?

Run `npm install && npm run build-legacy` with the latest version in the main branch.
The legacy build files will be created in `build/legacy/`.

**Comment by vsevjednom-cz** [comment]
Sorry, I can't. Because I'm not using npm. And there are too much errors when I tried to install npm. Can you send me URL of the repaired version of ol?

**Comment by ahocevar** [comment]
https://openlayers.org/en/main/build/ol.js

**Comment by vsevjednom-cz** [comment]
Yes, it works! Thank you very much 🙃!

**Comment by TDesjardins** [comment]
Thanks for fixing this. Will this be released / delivered with the next version? So that it is available at: https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/vx.x.x/build/ol.js

**Comment by ahocevar** [comment]
Yes, this will be available via cdn with the next release.

**Comment by TDesjardins** [comment]
Ok, thanks @ahocevar !
