### ISSUE TITLE
ForEachFeatureAtPixel gives layer null

### ISSUE THREAD

**Issue by JNogueira92** [openlayers/openlayers#11876]
**Describe the bug**
Calling ForEachFeatureAtPixel returns layer as null when layer is added to layer group with group.getLayers().push()

**To Reproduce**
Create map with layer group
Add layer to group with function push
Try to use ForEachFeatureAtPixel
Feature is returned correctly, but layer comes as null

**Expected behavior**
Layer should be returned correctly by the function

**Comment by simonseyock** [comment]
Thanks for the report! Can you provide a minimal example on codesandbox that shows the error? You can use the edit button in any example on https://openlayers.org/en/latest/examples/ to get a starting point.

**Comment by JNogueira92** [comment]
Sorry for the delay but caught up on another project. After some more in depth research I was able to conclude the problem was not on the .push() method but it was caused by the Modify interaction. I will try to redo the steps which led to the features having a null layer when the layer was source of the modify interaction, sorry for the mistake!
