### ISSUE TITLE
How refresh some tiles realtime?

### ISSUE THREAD

**Issue by zlzforever** [openlayers/openlayers#11875]
I load a TileLayer use a TileWMS source, after I remove a Feature, i need refresh some Tiles, is there any example to do this?
I know how to refresh all tiles of a  Layer:

const params = source.getParams();
params.t = new Date().getMilliseconds();
source.updateParams(params);

But it's not the best practice.

**Comment by mike-000** [comment]
The timestamp is used to override browser caching.  If there was no browser caching calling `source.refresh();` would be sufficient but that would require appropriate cache-control headers to be sent, typically from the server (from the client it would need a custom tile load function to load via xhr).

**Comment by tiagoporto** [comment]
I think it's related #10533

**Comment by arslivinski** [comment]
I have a similar requirement where a I need to change just a few tiles, because I'm working on a machine with very limited resources.

I found a solution to do that with the default projection, just click on the map to see the tile 4/6/8 be updated.

https://jsfiddle.net/arslivinski/ry7p1Luq/38/

However, if I change de projection to EPSG:4326 the map is not being re-rendered unless I change the zoom and then zoom back.

What can I do differently to update just a specific tile on the map?

**Comment by zlzforever** [comment]
I found a solution:

1. get extent of the feature
2. create   4 points of the extent
3. get tile keys which are impacted by the feature: source.getTileGrid().getTileCoordForCoordAndResolution(feature, resolution);
4. remove timecache
5. set imageTile's state to ERROR, then the imageTile will reload from the WMTS server
      
      const source = this.editLayer.getSource();
      const extent = feature.getGeometry().getExtent();

      const coordinates = [
          [extent[0], extent[1]],
          [extent[2], extent[1]],
          [extent[0], extent[3]],
          [extent[2], extent[3]],
        ];

      coordinates.forEach((x) => {
          resolutions.forEach((resolution) => {
            const tileKeys = source
              .getTileGrid()
              .getTileCoordForCoordAndResolution(x, resolution);
            const key = tileKeys[0] + "/" + tileKeys[1] + "/" + tileKeys[2];

            if (source.tileCache.containsKey(key)) {
              const imageTile = source.tileCache.get(key);
              source.tileCache.remove(key);
              imageTile.setState(TileState.ERROR);
              imageTile.load();
            }
          });
        });
