### ISSUE TITLE
image rendered VectorTile scaling issue regression with 6.5.0

### ISSUE THREAD

**Issue by t-muko** [openlayers/openlayers#11880]
**Describe the bug**
The old bug #11464 seems to be here again with 6.5.0. 

**To Reproduce**
Steps to reproduce the behavior: See #11464
Observed with Firefox. Workaround of setting pixelratio to 1 nor removing the setting does not help.

**Expected behavior**
Street names on vector rendered image layer in the right place.

**Comment by ahocevar** [comment]
I don't think this issue ever got fixed.

**Comment by ahocevar** [comment]
Actually this is a different issue. This time, it has nothing to do with the device pixel ratio, but with fractional zooming.
