### ISSUE TITLE
Image icons are clipped at VectorTile edges

### ISSUE THREAD

**Issue by dbauszus-glx** [openlayers/openlayers#11884]
After upgrading from OL 6.4 to 6.5 image icons are clipped at tile edges.

I put together a small codepen to show the problem.

https://codepen.io/dbauszus-glx/pen/ZEpoaNx

![image](https://user-images.githubusercontent.com/22201617/103661398-9df0e200-4f66-11eb-9629-ec95d1439ddb.png)

If I replace the ol library with the previous version in the same codepen I see the icon although there is a small line through the icon.

![image](https://user-images.githubusercontent.com/22201617/103661650-dbee0600-4f66-11eb-9996-a55002d13642.png)

I wouldn't mind to have a look what might cause this issue but wouldn't know where to start since there have been quite a few changes between 6.4 and 6.5.

**Comment by MoonE** [comment]
You can find the offending commit with the help of git's bisect command. https://git-scm.com/docs/git-bisect
It does a binary search between two commits and by telling it if the commit works (good) or doesn''t (bad) it continues the search in the right direction until you find the commit introducing the problem.
```bash
git bisect start v6.5.0 v6.4.0
# Then use either
#git bisect good
# or 
#git bisect bad
# until the offending commit is found
```

**Comment by dbauszus-glx** [comment]
I found the issue not sure whether this is a bug or expected behaviour.

I found [this issue](https://github.com/openlayers/openlayers/issues/10348) while looking at the lines through the symbol in 6.4.

Setting `declutter: true` fixed the display in 6.4. Going back to 6.5 I can see now that this also fixes the display of the icon.

I guess this can be closed. Is it worth to put a note somewhere in this regard for others to not stumbled on the same issue?

**Comment by dbauszus-glx** [comment]
Unfortunately the problem happens with 6.4 as well but is less prominent. Is it possible that the renderBuffer property is not doing anything? Changing this does not have any effect on the clipping of images.

**Comment by dbauszus-glx** [comment]
I created another codepen which has a layer with much more icons.

https://codepen.io/dbauszus-glx/pen/ZEpRPoe

In this case we cannot use the declutter method which means that with 6.4 with have lines through icons and with 6.5 we have clipped symbols.

![image](https://user-images.githubusercontent.com/22201617/103937227-6037b900-5120-11eb-954f-db1119d9290f.png)

Do you have a programme where we could sponsor fixing a bug if we are unable to do so ourselves?

**Comment by ahocevar** [comment]
Thanks for your interest in sponsoring a bug fix. I would be able to fix this bug. Please see my profile page (@ahocevar) for a link to my website, where you will find my professional support offerings.

**Comment by dbauszus-glx** [comment]
@ahocevar That sounds great. I will have a try over the weekend whether I am able to make a pull request myself and get back to you on Monday if I am unable to grok the render logic.

**Comment by dbauszus-glx** [comment]
@ahocevar I am making some progress on this.

I was able to track down the pull request which causes the issue.

https://github.com/openlayers/openlayers/pull/11377

The renderBuffer will be removed when declutter is false. Oddly I can not find the merged code in the main branch. Is it possible that the main branch is not at the latest version?

**Comment by dbauszus-glx** [comment]
@ahocevar Is it possible that the new declutter implementation caused this to fail? https://github.com/openlayers/openlayers/pull/11592

I checked a few of the commits between 6.4.3 and 6.5.0 but non did change the behaviour of the dlipped image render.

I created this example script to test the behaviour.

```
import Icon from '../src/ol/style/Icon.js';
import LayerVectorTile from '../src/ol/layer/VectorTile.js';
import MVT from '../src/ol/format/MVT.js';
import Map from '../src/ol/Map.js';
import SourceVectorTile from '../src/ol/source/VectorTile.js';
import Style from '../src/ol/style/Style.js';
import View from '../src/ol/View.js';

const sourceVectorTile = new SourceVectorTile({
  format: new MVT({}),
  tileUrlFunction: (tileCoord) => {
    return `https://xyz-mvt.vercel.app/dev/api/layer/mvt/${tileCoord[0]}/${tileCoord[1]}/${tileCoord[2]}?locale=UK&srid=3857&layer=Scratch&table=dev.scratch`;
  },
});

const layerVectorTile = new LayerVectorTile({
  source: sourceVectorTile,
  renderBuffer: 200,
  declutter: false,
  style: styleFunction,
});

function styleFunction() {
  const style = new Style({
    image: new Icon({
      src: `data:image/svg+xml,%3Csvg%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%20%20%3Ccircle%20cx%3D%2213%22%20cy%3D%2213%22%20r%3D%2210%22%20fill%3D%22%23333%22%2F%3E%0A%20%20%20%20%3Ccircle%20cx%3D%2212%22%20cy%3D%2212%22%20r%3D%2210%22%20fill%3D%22%23ff1744%22%2F%3E%3C%2Fsvg%3E`,
      scale: 3,
      anchor: [0.5, 0.5],
    }),
  });

  return style;
}

new Map({
  layers: [layerVectorTile],
  target: 'map',
  view: new View({
    center: [-49213.90160174308, 6731227.370615371],
    zoom: 13,
  }),
});
```

**Comment by ahocevar** [comment]
That could definitely be the case, @dbauszus-glx, because we do not have a rendering test for point symbols crossing tile boundaries.

**Comment by gedaiu** [comment]
I can also reproduce this issue. This is a code example with one of the tiles that is not rendered properly: 


``` js
   const base64StringToArray = (s) => {
      let asciiString = atob(s);
      return new Uint8Array([...asciiString].map(char => char.charCodeAt(0)));
    }

    let data = base64StringToArray("GvEBeAIKBnBvaW50cxIWCAASCgAAAQECAgMDBAQYASIECaYZNRIXCAASCgAFAQECAgMDBAYYASIFCY4jjQEaA19pZBoEdHlwZRoLaXNQdWJsaXNoZWQaBWljb25zGgRuYW1lIhoKGDVmZjViMjVkZjc4ODc5MDEwMGFlMWQ2MiIHCgVwb2ludCIGCgR0cnVlIhoKGDVmZTg3YjY4ZTBlOTk0MDEwMGVhYmJlNiIaChhGcmVlLWxpdmluZyBuZXN0IGV4YW1wbGUiGgoYNWZlODkwNGM3MDhjNTYwMTAwY2EyZjUyIgsKCXNvbWUgbmVzdCiAIBoMeAIKBmdyb3VwcyhQGgx4AgoFbGluZXMogCAaD3gCCghwb2x5Z29ucyiAIBqrA3gCCgVkZWJ1ZxIRCAASAgAAGAIiBwkCAgoA/D8SEQgAEgIAABgCIgcJAgIK/D8AEhIIABICAAAYAiIICQL+Pwr8PwASEggAEgIAABgCIggJ/j8CCgD8PxITCAASAgABGAIiCQm0BrQGCgCYMxITCAASAgABGAIiCQm0BrQGCpgzABITCAASAgABGAIiCQm0Bsw5CpgzABITCAASAgABGAIiCQnMObQGCgCYMxITCAASAgACGAIiCQnoDOgMCgCwJhITCAASAgACGAIiCQnoDOgMCrAmABITCAASAgACGAIiCQnoDJgzCrAmABITCAASAgACGAIiCQmYM+gMCgCwJhITCAASAgADGAIiCQmaE5oTCgDMGRITCAASAgADGAIiCQmaE5oTCswZABITCAASAgADGAIiCQmaE+YsCswZABITCAASAgADGAIiCQnmLJoTCgDMGRIPCAASAgEEGAEiBQmAIIAgGgRzaXplGgRuYW1lIgkZAAAAAAAAAAAiCRkAAAAAAAAkQCIJGQAAAAAAADRAIgkZAAAAAAAAPkAiCgoIOC8xMzcvODQogCA=");

    let tileLoadFunction = (tile) => {
      tile.setLoader((extent, resolution, projection) => {
        const format = tile.getFormat();
        let features = format.readFeatures(data, {
          extent,
          featureProjection: projection
        });

        tile.setFeatures(features);
      });
    }

    const source = new VectorTileSource({
      format: new MVT(),
      url: "http://localhost:9091/tiles/{z}/{x}/{y}?format=vt",
      tileLoadFunction
    });

    const style = (feature) => {
      let properties = {};
      if(feature.getProperties) {
        properties = feature.getProperties();
      }

      if(properties["layer"] != "points" && properties["layer"] != "groups") {
        return;
      }

      const circle = new Circle({
        radius: 30,
        stroke: new Stroke({
          color: "#cc0033",
          width: 1
        }),
        fill: new Fill({
          color: "#ffffff"
        })
      });

      const style = new Style({
        image: circle
      });

      return [style];
    }

    const layers = [
      new TileLayer({
        source: new OSM(),
      }),
      new VectorTileLayer({
        source
      }),
      new VectorTileLayer({
        source,
        style
      })
    ];

    var map = new Map({
      layers,
      target
    });

    const transformedValue = transformExtent([10.924994132259753,52.039908148925804,15.364458324989526,53.37159512476504], "EPSG:4326", "EPSG:3857");
    map.getView().fit(transformedValue);
```

**Comment by ahocevar** [comment]
@dbauszus-glx Sorry for jumping ahead and fixing this in #11901.

**Comment by dbauszus-glx** [comment]
@ahocevar Amazing. Thanks for fixing this. I just pulled through the latest changes into my fork and can confirm that they work.
