### ISSUE TITLE
Line not connecting all points.

### ISSUE THREAD

**Issue by JaniniRami** [openlayers/openlayers#11885]
I am trying to draw a line between thousands of points (orbital points), but the line doesn't connect al the way, instead it goes far apart in a 360 degree angel and moves in a straight line until the end of the map:
![Screenshot_2021-01-05 Insert Name - Map(2)](https://user-images.githubusercontent.com/39865850/103665860-94727480-4f7c-11eb-98f9-5cdc08c40b3c.png)

Zoomed picture:
![Screenshot_2021-01-05 Insert Name - Map(1)](https://user-images.githubusercontent.com/39865850/103665886-9ccaaf80-4f7c-11eb-8b49-1bdf66e7e9df.png)

Here is the function that draws the line and  points is a list made from another function that only generates a list of 5400 points:
```
function demoDraw(points){

for (var i = 0; i < points.length; i++) {
    points[i] = ol.proj.transform(points[i], 'EPSG:4326', 'EPSG:3857');
}

var featureLine = new ol.Feature({
    geometry: new ol.geom.LineString(points)
});

var vectorLine = new ol.source.Vector({});
vectorLine.addFeature(featureLine);

var vectorLineLayer = new ol.layer.Vector({
    source: vectorLine,
    style: new ol.style.Style({
        fill: new ol.style.Fill({ color: '#00FF00', weight: 4}),
        stroke: new ol.style.Stroke({ color: '#00FF00', width: 2 })
    })
});
map.addLayer(vectorLineLayer)
}
```

I expect it to connect the dots but I cant find a solution or an idea of why is the line connecting all the points except the two points in the zoomed picture as the line turns in 360 degree as show in in the pictures.

Note: the error is not caused by the list as the list already worked by putting down some points without any bugs as shown in the picture.

**Comment by mike-000** [comment]
The line is correctly joining longitudes +179.9 and -179.9 in the same world. It would be best to split the geometry into a MultiLineString at the dateline. To display a continuous LineString crossing the dateline the longitude coordinates would need to exceed the range -180 to +180 in conjunction with setting the vector source `wrapX: false` option.

**Comment by JaniniRami** [comment]
Thanks a lot, I have made a new function that converts my points list into a MultiLineString and it works like charm!
