### ISSUE TITLE
VectorSource 'featuresloadend' event not firing when using custom loader.

### ISSUE THREAD

**Issue by dustinshackley** [openlayers/openlayers#11881]
When attaching the event listener 'featuresloadend' on a vector source with a custom loader, it never fires.
'featuresloadstart' works as expected and fires when attached to a vector source with a customer loader.

'featuresloadend' fires normally on a vector source without a custom loader.

Is this expected behavior?

**Comment by simonseyock** [comment]
If you use a custom loader you have to call the success and failure callbacks to have the events fired. See https://openlayers.org/en/latest/apidoc/module-ol_featureloader.html#~FeatureLoader

**Comment by simonseyock** [comment]
The example in the documentation https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html could be extended to show this. I will do a PR for this.

**Comment by adjenks** [comment]
@simonseyock Is "loader" similar to "strategy"? I'm using the build-in "bboxStrategy" and it's not firing the 'featuresloadend' event.

```js
import {bbox as bboxStrategy} from 'ol/loadingstrategy';

var	sitesVectorSource = new VectorSource({
		format: new GeoJSON(),
		url: function (extent) {
			return (
			'https://redacted/geoserver/acp-ogi/wms?service=WFS&' +
			'version=1.1.0&request=GetFeature&typename=redacted:redacted&' +
			'outputFormat=application/json&srsname=EPSG:3857&' +
			'bbox=' +
			extent.join(',') +
				',EPSG:3857'
			);
		},
		strategy: bboxStrategy,
	})
```

**Comment by adjenks** [comment]
I thought I had a similar problem, but... nevermind, sorry. I had a typo in the event name. :) I need to use the typescript event names to prevent that...
