### ISSUE TITLE
WebGLPointsLayer refuses to load icons

### ISSUE THREAD

**Issue by shub-sharma** [openlayers/openlayers#11889]
I was working on a project that uses the WebGLPointsLayer, but I was having issues loading icons. Then, I downloaded an example from the openlayers website and noticed that the example was also having issues loading the icon.

I copied the source code (with the correct csv and png) for this [example](https://openlayers.org/en/latest/examples/icon-sprite-webgl.html) and ran it locally across 3 different windows machines. They all report the same exact error on google chrome:
```
> Helper.js:622 WebGL: INVALID_VALUE: texImage2D: bad image data
(anonymous) @ Helper.js:622
> DevTools failed to load SourceMap: Could not load content for https://unpkg.com/elm-pep.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```
I have tried it on firefox too but with a slightly different error:
```
> WebGL warning: drawElementsInstanced: TEXTURE_2D at unit 0 is incomplete: The dimensions of `level_base` are not all positive. 32 Helper.js:511:7
> WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings)
```

**Comment by MoonE** [comment]
But the example you linked works for you? Can you share your code?

There is some bad data in that csv that is filtered in the linked example.
https://github.com/openlayers/openlayers/blob/bacf8c076a67ab899ba7403353c0b29ea1a0d8a3/examples/icon-sprite-webgl.js#L128-L131
Have you kept this in your code?

**Comment by shub-sharma** [comment]
The example doesn't work at all for me. I've kept the code the exact same with a similar folder structure for the png/csv location.

**Comment by MoonE** [comment]
I get the same error as you when the sprite image could not be loaded, are you sure you put it in the correct place and it gets loaded?

**Comment by shub-sharma** [comment]
Here is my folder structure: 
![image](https://user-images.githubusercontent.com/47621980/103817856-7b79ca00-5035-11eb-8ad7-535af5c40baf.png)

**Comment by shub-sharma** [comment]
I finally found the fix. The issue was that I was using parcleJS which wouldn't find the path to the specified icon. For the `src`, I had to use `require('/path/to/image')`.
