### ISSUE TITLE
SVG in StaticImage is blurry

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#11888]
Check example here:
https://codesandbox.io/s/static-image-forked-oni74?file=/main.js

Seems like method handleImageChange in ImageStatic.js does not work well for SVGs. It works fine for PNG.

Does ImageStatic support SVG? What am I doing wrong?

**Comment by mike-000** [comment]
See also #4633.  The default size of the loaded image is not sufficient, you can override it with an imageLoadFunction https://codesandbox.io/s/static-image-forked-61tn9

**Comment by MichalK6677** [comment]
I still do not understand why ImageStatic.js -> handleImageChange has this IF statemenet:
![image](https://user-images.githubusercontent.com/3100059/103890904-2e573000-50e9-11eb-9006-8e49fb862fde.png)

It seems like if targetWidth != imageWidth then it wants to change width of the image an draw it into the canvas, else let it be as is. If it is a big SVG then it has poor performance if it is not rasterized via the canvas drawing as you can see here:
https://codesandbox.io/s/bing-maps-forked-vvssd?file=/index.js:606-836

When I remove the if condition:
![image](https://user-images.githubusercontent.com/3100059/103893134-0e297000-50ed-11eb-8b71-639933f9ae87.png)

then all images are rasterized even if they do not need change of width and even big SVG works fine with the setting of size based on your example:
https://codesandbox.io/s/bing-maps-forked-lsk8e?file=/index.js

**Comment by mike-000** [comment]
The `if (targetWidth != imageWidth)` is needed to stretch the image when the image width to height ratio is different from the extent width to height ratio, for example in the Image Reprojection example the image is 2000 x 3696  (ratio 0.5411255) while the extent is 700000 x 1300000 (ratio 0.5384615).

**Comment by MichalK6677** [comment]
I understand why the logic in the IF statement is there. I do not understand why this logic cannot be used for all images. I mean for images with different ratio than extent and also with the same ratio as extent (all images would be streched even if not needed).

Current logic makes a raster image from SVG when the image ratio is different from the extent ratio but it does not raster it when the ratios are the same therefore there is a big performance difference.

**Comment by bobgravity1** [comment]
cuz gatsby image sucks
