### ISSUE TITLE
HERE Map Tile API example not working

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11895]
**Describe the bug**
The app_id app_code pair seems to be out of date.

**To Reproduce**
See the example and errors on the console.

**Expected behavior**
Up to date app_id app_code, or better to generate an apiKey which would require the url to be updated to a new path as in the latest HERE documentation

```
  'https://{1-4}.{base}.maps.ls.hereapi.com' +
  '/{type}/2.1/maptile/newest/{scheme}/{z}/{x}/{y}/256/png' +
  '?apiKey={apiKey}';.
```

**Comment by ahocevar** [comment]
@chrismayer Any chance you could ask for a new key pair?
