### ISSUE TITLE
stopClick on Draw interactions not working

### ISSUE THREAD

**Issue by mattiaspantzare** [openlayers/openlayers#11891]
**Describe the bug**
If I set stopClick too true on a Draw interaction click events should not be sent when I click on the map.
In 6.5.0 click events are sent, in 6.4.3 they are blocked.

**To Reproduce**

This should not display an alerter. 
https://codesandbox.io/s/draw-features-forked-kvoqj?file=/main.js

**Expected behavior**
No click events will fire during drawing

**Comment by ahocevar** [comment]
Thanks for reporting this, @mattiaspantzare. This is a regression introduced by #11817.
