### ISSUE TITLE
Support for altitude coord

### ISSUE THREAD

**Issue by labronico0586** [openlayers/openlayers#11898]
I'd like to have altitude dimension managed in geometries and in all coord trasformations.

Providing the third coordinate (altitude) it could be possible to render features as in a near 3d env.

**Comment by mike-000** [comment]
It is already supported by specifying XYZ or XYZM layout when creating geometry https://openlayers.org/en/latest/apidoc/module-ol_geom_GeometryLayout.html and is also automatically read from supported formats and can be used in style functions, for example https://codesandbox.io/s/gpx-forked-4s65b?file=/main.js
