### ISSUE TITLE
view.animate to center position with padding

### ISSUE THREAD

**Issue by kiastorm** [openlayers/openlayers#11906]
I want to `view.animate()` to `center` co-ordinates, but set a padding / offset using px values, the same way a `padding` array is passed to `view.fit()`

What does OpenLayers export that could help me achieve this? It would be a nice feature to have. 

Failing that, is there a way I can convert my co-ordinates to be an extent? And then use view.fit to animate to a 'center position' with an offset?

**Comment by mike-000** [comment]
`view.animate()` will work in conjunction with view padding https://codesandbox.io/s/view-padding-forked-gohcg?file=/main.js

If you don't want view padding you could use `view.fit()` with any of

```
coordinate.concat(coordinate)
boundingExtent([coordinate])
new Point(coordinate)
new Point(coordinate).getExtent()
```

Specify `minResolution: view.getResolution()` or `maxZoom: view.getZoom()` in the options to avoid zooming in

**Comment by kiastorm** [comment]
Thanks for your reply. 

Neither of those solutions are working for me unfortunately.

I have a panel floating over the map and I want to be able to offset the center position dynamically whenever the panel is open (so that is centered in the remaining space).

```
// Render button that fires positioning action. If the panel is open at time of click, add 453px of padding-left 
<ResetPosition padding={panelIsOpen ? [0, 0, 0, 453] : null} />
```

```
// function called by <ResetPosition />
const centerPoint = new Point(defaultCenterCoords);
const duration = 600;

map.getView().animate({
          zoom: defaultZoom,
          duration,
        });
        
        map.getView().fit(centerPoint, {
          duration,
          padding: options?.padding,
          maxZoom: map.getView().getZoom(), // Don't zoom to fit centerPoint
        });
```


This is exactly what I want, although it doesn't work unless you click the reset position button twice.

**Comment by mike-000** [comment]
You could do the zoom and center in a single animation

```
map.getView().fit(centerPoint, {
    duration,
    padding: options.padding,
    maxZoom: defaultZoom
});
```
