### ISSUE TITLE
Vector Tile label regressions

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#11907]
**Describe the bug**
There have been some regressions in the rendering of vector tile labels between versions 6.4.3 and 6.5.0.  I thought the issues dealt with by #11901 might be related but that has not fixed it.  The changes occurred with the merging of #11519 and #11592.

**To Reproduce**

The example is based on https://github.com/OrdnanceSurvey/OS-Data-Hub-API-Demos/tree/master/OSVectorTileAPI/OpenLayers
and with the API key having access only to open data the stylesheet https://github.com/OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets/blob/master/OS_VTS_27700_Open_Outdoor.json summarises the relevant styles for those zoom levels.

With version 6.4.3 https://codesandbox.io/s/osvectortileapi-forked-5u3kw
![image](https://user-images.githubusercontent.com/49240900/104308713-00973000-54c9-11eb-9ce9-de9d63435b9c.png)

With 6.4.4-dev.1599991456902 (merging of #11519) https://codesandbox.io/s/osvectortileapi-forked-ddqxj
Labels as above flicker during rendering before a new set appears:
![image](https://user-images.githubusercontent.com/49240900/104308845-2d4b4780-54c9-11eb-80a0-8c4e051df883.png)

With 6.4.4-dev.1602059675781 (merging of #11592) https://codesandbox.io/s/osvectortileapi-7y82c
Further changes to the set of labels, some labels are clipped, often on both sides (e.g. **Kingston on Soar** becomes **n on S**), and road labels are missing:
![image](https://user-images.githubusercontent.com/49240900/104309356-ef025800-54c9-11eb-9a1d-a1e030ac3ab3.png)

**Expected behavior**
Consistency in which labels are displayed, no clipped labels, and no flickering during render.

**Comment by ahocevar** [comment]
#11911 fixes the problem with the cropped labels. The selection of labels continues to be different from the old decluttering implementation. That comes from a different render order, because decluttering is first come first serve.

Note that your example could perform better if you'd use a projection extent whose origin is a tile corner in the tile grid your vector tile source uses.
