### ISSUE TITLE
Workshop - Vector Tiles - Outdated url 

### ISSUE THREAD

**Issue by Gtrouborst** [openlayers/openlayers#11909]
### MapTiler URL 
From the workshop instructions I've tried to construct the map as shown at the bottom of [this page](https://openlayers.org/workshop/en/vectortile/map.html). I got redirected from the URL mentioned in the instruction (https://openmaptiles.com/hosting/), to: 
https://www.maptiler.com/cloud/. There I created an account and received a API key.

### Error
When I run the code now, the map does not load. The console returns the following error message: `No server found with the specified hostname`. I guess that makes sense. This URL no longer seems to be sufficient:
```js
url: `https://free-{1-3}.tilehosting.com/data/v3/{z}/{x}/{y}.pbf.pict?key=${key}`,
```
Why using **backticks** by the way?

### How to proceed
I don't know how to proceed from this point onwards. Under the **Tiles** tab in my account, there is not something like a **Streets** tile, though something like that can be found under the **Maps** tab.

#### Attempt 1
If I a take one of the URL's from there (I took it from the OpenLayers code example):
`https://api.maptiler.com/maps/streets/style.json?key=${key}`, it doesn't work either. Probably because it is `.json` and not `.pbf`. 

#### Attempt 2
Then I tried the URL from one of the tile layers (I took the **contours** layer): 
`https://api.maptiler.com/tiles/contours/{z}/{x}/{y}.pbf?key=${key}`, but that didn't work out either. 

I ran out of options, so I hope someone can explain to me how to proceed.

**Comment by mike-000** [comment]
`https://api.maptiler.com/tiles/contours/{z}/{x}/{y}.pbf?key=${key}`  should work with a valid MapTiler key if the browser supports backticks.  Otherwise use `'https://api.maptiler.com/tiles/contours/{z}/{x}/{y}.pbf?key=' + key ` However, contours is not a good choice as it only has data for zoom levels 9 to 14.  For the OpenMapTiles migration use MapTiler Planet `https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=${key}`

**Comment by Gtrouborst** [comment]
Thank you very much @mike-000. `https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=${key}` indeed exactly does what I was looking for.

**Comment by Gtrouborst** [comment]
### Further migration consequences
In the [next step](https://openlayers.org/workshop/en/vectortile/bright.html) I'm confronted with URL/key issues again. The `main.js` file should only contain the following lines: 
```js
import 'ol/ol.css';
import {apply} from 'ol-mapbox-style';

const map = apply('map-container', './data/bright.json');
```
### Errors
When I update the page, I get four error messages (see: 'error messages' below). The first message directs me to a page telling me to _update my URLs to “api.maptiler.com” domain_. This is understandable given the aforementioned migration of the page. Additionally the 2<sup>nd</sup> and 3<sup>rd</sup> seem to be related to the API key (the shown key is from the exercise). 

### Failed attempts
The suggested `main.js` file doesn't contain any URL or key, so I had to dive into the underlaying files to find out where it goes wrong. So I did two things

#### Attempt 1
I tried to find the files containing or dealing with URL's and API keys and update them manually (see: 'consulted files' below). I found three URL's in `bright.json` two of which contain an API key. So I updated the URL's and replaced the API key with my personal key. That didn't make any difference.

#### Attempt 2
Then I checked how the `{apply}` function works (see: `index.js` below), and it seems to me that this works fine. It mentions using a key in the instructions, but as a copy of the .json is saved locally, my understanding is that no key has to be provided by me. 

<details><summary><b>Error Messages</b></summary>
<p>

![console_error_message](https://user-images.githubusercontent.com/36916421/104708968-a4c5e480-571e-11eb-8bb7-15248fc0e388.png)

</p>
</details>

<details><summary><b>Consulted files</b></summary>
<p>

1. `./data/bright.json`
2. `./node_modules/ol-mapbox-style/index.js`
3. `./node_modules/ol-mapbox-style/olms.js`

</p>
</details>

**Comment by mike-000** [comment]
Unless you need to customise the style it would be better to use the MapTiler style json directly

`const map = apply('map-container', 'https://api.maptiler.com/maps/bright/style.json?key=' + key);`

See also MapTiler's own example https://cloud.maptiler.com/maps/bright/openlayers

**Comment by ahocevar** [comment]
If someone could create a pull request with the suggested new urls, it would be much appreciated.

**Comment by Gtrouborst** [comment]
Thanks @mike-000 and @ahocevar, it works!
One final question, though. I installed the newest version and removed the old one. Is there a quicker way to do that? I tried `npm update -g`, but that probably only updates the Node Package Manager ...
