### ISSUE TITLE
VectorSource and View with different projections

### ISSUE THREAD

**Issue by umbertodistaso** [openlayers/openlayers#11923]
I'm struggeling configuring a simple map where the View is in the default projection, but the VectorSource is in 4326. I need to keep different projections because of shape drawing (i won't loose precision by transforming coordinates)

I was supposing that VectorSource, since is extending Source, was able to get a projection as option but seems not working. In changelogs i noticed this #11454 and that "has to match" doesn't sound very good... 

Reproduce
Here the example https://codesandbox.io/s/accessible-forked-u864c?file=/main.js
1. simply execute the example and look at the consolle (the 2nd log is always undefined)
2. moreover, you can try to uncomment the first "poly" (and comment the second one) to see as, transforming the polygon, it is working....but i need to keep data in the projection declared in VectorSource, not the View

Expected behavior
Draw polygon with a different projection compared to the one used by the view.

**Comment by ahocevar** [comment]
What you read in #11454 ("has to match") refers to vector tile sources, not vector sources.

For vector sources, the projection is handled on the level of the format. This means that the features are transformed during reading and writing, and the source provides them in the view projection. As soon as you edit a geometry, you need it in the view projection anyway. So this behavior makes sense.

For your use case, I'd suggest using `useGeographic()`. See https://openlayers.org/en/latest/examples/edit-geographic.html. That way, the source (and also all view coordinates) will be in geographic coordinates. Or, if you want a different projection than geographic coordinates, use `setUserProjection(projection)`

**Comment by umbertodistaso** [comment]
Thank you for the quick answer!

Are these methods available in the documentattion? I'm searching under https://openlayers.org/en/latest/apidoc/module-ol_proj.html but i didn't find any mention about useGeographic() and setUserProjection(projection)

**Comment by ahocevar** [comment]
Those are currently considered experimental, but will become part of the official API soon.

**Comment by umbertodistaso** [comment]
Ok, great. I'm closing the issue
