### ISSUE TITLE
Mark an address

### ISSUE THREAD

**Issue by robertnicjoo** [openlayers/openlayers#11924]
Hi,

Sorry if my question is so basic to you but it's my first attempt :)

How can I have marker (pin) on the map based on full address and not longitude latitude?

**What I have currently**

```javascript

<div id="map" class="map"></div>


<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/css/ol.css" type="text/css">
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.4.3/build/ol.js"></script>
<script type="text/javascript">
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([37.41, 8.82]),
          zoom: 4
        })
      });
</script>
<style>
  .map {
    height: 400px;
    width: 100%;
  }
</style>
```

**Comment by M393** [comment]
If you need to get the coordinates for an address you can first use a geocoding service like Nominatim to get the coordinates for that address.
https://nominatim.org/release-docs/develop/api/Search/

**Comment by robertnicjoo** [comment]
@M393  thanks for respond but that doesn't return any data to me.

**Comment by M393** [comment]
You need to make an ajax request like this with parameters listed in the link above:
```js
fetch('https://nominatim.openstreetmap.org/search?format=json&street=badstrasse')
    .then((result) => result.json())
    .then((data) => console.log(data))
```
If you want to use this service please be aware of the usage policy: https://operations.osmfoundation.org/policies/nominatim/

**Comment by robertnicjoo** [comment]
Apparently `openlayers` only works on some countries, because none of my addresses can be found by it but google maps finds all of them :/

Therefore I give up on using this (not suitable for my use). Thanks a lot for the helps.
