### ISSUE TITLE
JSTS example talks about meters but means EPSG:3857's fake meters

### ISSUE THREAD

**Issue by kannes** [openlayers/openlayers#11927]
**Describe the bug**
https://openlayers.org/en/latest/examples/jsts.html shows buffers around lines. It says that those buffers have a radius of 40 meters.
In reality the buffers have a radius of 40 units of EPSG:3857 which are called meters but are not corresponding to actual, real world meters. They are highly distorted pretty much everywhere on the planet.

https://gis.stackexchange.com/questions/329213/using-meters-to-buffer-with-jsts mentioned this but sadly the user filed no bug.

They also provided an image: https://i.stack.imgur.com/tIoBJ.png

To fix this the example would need to use a projection like UTM.

**Comment by mprins** [comment]
Use of the unit "meter" is correct within the scope of the projection of the map, see https://epsg.io/3857 which lists metre as Unit of Measurement

**Comment by kannes** [comment]
While that is _technically true_ for experts in map projections, those "meters" are highly distorted compared to meters as measured in reality. 1 meter in EPSG:3857 in that area is about 0.75 actual meters as measured on the ground.

Here are some measurements as done in QGIS on the example data. The top image shows a cartesian measurement (just how JSTS works) in EPSG:3857. The second one shows an ellipsoidal measurement. The last image is cartesian again, this time in UTM 52N.

The buffer is "40 meters" so the width (yellow line) of the polygon (blue) should be about 80 meters wide. It actually is a little over 60 meters wide though.

![pseudo cartesian](https://user-images.githubusercontent.com/7661092/105222867-591a9d00-5b5b-11eb-9437-0c0e5d65e564.png)
![ellipsoidal](https://user-images.githubusercontent.com/7661092/105222876-5d46ba80-5b5b-11eb-9996-c97bd311addb.png)
![utm cartesian](https://user-images.githubusercontent.com/7661092/105222887-60da4180-5b5b-11eb-8bdd-fb483e18ec93.png)


This example is misleading to any non-experts. And it will lead to wrong maps and wrong analyses if users copy it for their own "metric" buffers.

**Comment by mprins** [comment]
this is not a problem the OpenLayers toolkit can solve

**Comment by mike-000** [comment]
If you want 40 meters at the local point resolution you could use

      var buffered = jstsGeom.buffer(40 / getPointResolution(map.getView().getProjection(), 1, getCenter(feature.getGeometry().getExtent()));

**Comment by kannes** [comment]
Thank you @mike-000, I used that to update the example and made a PR.
