### ISSUE TITLE
Bad performance with multiple WMTS layers on Firefox

### ISSUE THREAD

**Issue by maltaesousa** [openlayers/openlayers#11929]
**Describe the bug**
In Firefox, with OpenLayers 6.5 and with at least two WMTS sources, Firefox performs slowly in rendering tiles. This was not the case in OpenLayers 5.3.0. I've made a simple example with 3 WMTS layers, one has ol 6.5.0, the other is in 5.3.0.

**To Reproduce**
Easier to reproduce on big screens (>1080p). **Disable cache**

1. In firefox with maximized window, go to https://sitn.ne.ch/web/openlayers/ol6/
1. Zoom in and pan around
1. It's slow: tiles are loading slowly and navigation is difficult sometimes blocking mouse

**Expected behavior**
Reproduce steps 1 to 3 with this link: https://sitn.ne.ch/web/openlayers/ol5/
Performance with 5.3.0 is good (at least not worst than your network speed)

**Comment by sbrunner** [comment]
Is it possible that this commit is in charge of this issue?
https://github.com/openlayers/openlayers/commit/9cd35d67a99c5243541c46fe95385d0c1aa858ac

**Comment by maltaesousa** [comment]
Here's the source for the examples:

https://github.com/maltaesousa/olperf.git

I did two more examples before and after https://github.com/openlayers/openlayers/commit/9cd35d67a99c5243541c46fe95385d0c1aa858ac:

https://sitn.ne.ch/web/openlayers/ol6-beta9/
https://sitn.ne.ch/web/openlayers/ol6-beta10/

But there's no difference with 6.5.0.

I've also noticed in 6.x.x versions, GPU usage is very high compared to 5.x.x

**Comment by sbrunner** [comment]
Setting `maxTilesLoading` to `Inf` incrases the performance, but OpenLayers Shouldn't stop the queue filling on bad performances on filling the `Canvas`...

**Comment by d0z4rt** [comment]
Why closing it it's still an active issue right now !

**Comment by maltaesousa** [comment]
@d0z4rt , it's ok I guess because #12134 is still open

**Comment by d0z4rt** [comment]
Why aren't there more people reporting this ? This doesn't seem to be an isolated issue...

**Comment by thetuxinator** [comment]
looks like we face the same issue, on our page https://zugmap.ch we face a high GPU issue if you click on the "Star Icon" at left and then select the middle or bottom map preview and zoom in.

**Comment by kkeri** [comment]
I also have this issue with 6.5 on Firefox 132.0.2

**Comment by ahocevar** [comment]
@kkeri Please update to a recent version of OpenLayers. We're at v10.2 currently.

**Comment by kkeri** [comment]
@ahocevar I upgraded to v10.3 and the problem still persists. The same application runs smoothly on Chrome.

**Comment by ahocevar** [comment]
Does this advice help, @kkeri? https://github.com/openlayers/openlayers/issues/12134#issuecomment-1042968042
