### ISSUE TITLE
map rendercomplete event fires multiple times

### ISSUE THREAD

**Issue by murdocha** [openlayers/openlayers#11934]
**Describe the bug**
Map "rendercomplete" event _should_ only fire once when all layers have rendered (if I understand the docs as written). 
Not sure if this is specific to Esri service layers...
I'm seeing issues when using multiple types of Esri layers (MapServer/ImageArcGISRest source, and FeatureServer/VectorSource source).
Ultimately, I want a single event to fire when the map is completely rendered for all visible layers.
Currently the rendercomplete event for the map fires multiple times, on both initial load (when VectorLayer is present, and for subsequent map renders (when any Esri service layer is present).

**To Reproduce**
1. add a VectorLayer to the map
2. log console on map rendercomplete event
3. refresh map to view multiple rendercomplete log statements for a single map render action
or:
1. add an Esri Image REST source layer to the map
2. log console on map rendercomplete event
3. refresh map to view a single map rendercomplete event on initial load
4. move/pan/zoom the map and multiple map rendercomplete events are logged to console.

**Expected behavior**
The map rendercomplete should also support any layer type (including VectorLayers) so that we can determine when the map has completed rendering all layers (without having to hook up separate layer "rendercomplete" event handlers).

Here are working examples demonstrating the issue:
with VectorLayer: https://stackblitz.com/edit/openlayers-rendercomplete-issue-vectorlayer-only
with Esri REST Image layers: https://stackblitz.com/edit/openlayers-rendercomplete-issue-esri-mapservicelayers-only
with both types of layers: https://stackblitz.com/edit/openlayers-rendercomplete-issue-demo

It looks like this should have been addressed here:
https://github.com/openlayers/openlayers/issues/6447

**Comment by ahocevar** [comment]
The `rendercomplete` event is expected to fire every time the map is rendered with all data and resources (icons, fonts) included. Maybe the documentation is not clear enough. If you make any changes (load data, change style, or whatever) and want to know when the result is fully rendered, you should register `map.once('rendercomplete', () => console.log('complete')).

**Comment by murdocha** [comment]
hmmm... I guess I don't understand. 
_Does_ the map rendercomplete get emitted _each_ time _any_ layer is rendered to the map "viewport"?
or does it render _once_ after all layers are rendered to the current map "viewport"?

Wouldn't the "map.once" handler _only_ fire/emit on the _first_ map rendercomplete event?

Does this mean that there is no way to see when _all_ map layers are fully rendered to the map? Short of hooking up individual map layer event handlers for the layer rendercomplete events?

**Comment by murdocha** [comment]
This SO post seems to report similar issues?
https://stackoverflow.com/questions/65317291/many-postrender-and-rendercomplete-events-for-a-single-vectortile-layer-load

which has an answer that refers to an openlayers PR:
https://github.com/openlayers/openlayers/pull/11859

Is this accepted PR change present in the latest OL version (6.5.0)?

**Comment by ahocevar** [comment]
That change is not relevant to your concern.

Let me start with a better explanation for when the `rendercomplete` event is supposed to be triggered: During loading of layer content (tiles, vector data, icons, fonts), the map is rendered several times to show as much of the data as available. These render cycles are  incomplete. When all data is loaded, there will eventually be a render cycle that is complete. For each complete render cycle, a `rendercomplete` event will be dispatched. This means that e.g. when you pan the map, a `rendercomplete` event will be dispatched with every `pointermove` event, until your map viewport has changed to a point where additional data (e.g. tiles) needs to be loaded. Then you have incomplete render cycles again, until the missing tiles are loaded, and then you'll get `rendercomplete` events again with every subsequent render cycle that has all data for the current viewport available.

Now looking at your examples, there is indeed an issue with the vector layer, which uses a `tile` strategy. The `loading` property of vector layers, which is used for detecting a complete render cycle, is only set properly when the `all` strategy is used. So yes, this is a bug. A fix would be to set/unset the `loading` flag properly when a loading strategy other than `all` is used.

**Comment by murdocha** [comment]
Thanks for replying!
So, in this case, can you suggest potential work-arounds to get a "view render complete" event (for all visible layers of any type, raster or vector)?

This got some discussion here:
https://github.com/openlayers/openlayers/issues/6447#issuecomment-279107489
where a user suggested that:
"A ViewRenderComplete would be an awesome feature for printing and image exporting"

But it seems that the _map_ rendercomplete event added here:
https://github.com/openlayers/openlayers/pull/8532
is not exactly what I thought? in that it is tied to an individual "render cycle" and not to a single "all done" rendering stage for all layers available to a map?

I would wish for a "view render complete" event that may (or may not) return true if (and only if) _all_ referenced layers load _and_ render to the map "view".

What would you suggest as a best path toward achieving that goal?

**Comment by ahocevar** [comment]
I would not suggest a workaround, because the existing rendercomplete event's purpose is exactly what you want - when used correctly. See e.g. the https://openlayers.org/en/latest/examples/export-pdf.html example.

The issue you're having is specific to vector layers that do not use the default `all` strategy, which is quite rare. But that issue can be fixed. We'd accept a pull request with a fix.

**Comment by ahocevar** [comment]
#11941 will fix this code, but you'll also have to update (i.e. simplify) your vector loader, because right now it does not call the `success` or `error` callbacks:
```js
const vectorSource = new VectorSource({
  format: new EsriJSON(),
  url: function (extent) {
    const url =
      featureServiceUrl +
      layer +
      '/query/?f=json&' +
      'returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=' +
      encodeURIComponent(
        '{"xmin":' +
          extent[0] +
          ',"ymin":' +
          extent[1] +
          ',"xmax":' +
          extent[2] +
          ',"ymax":' +
          extent[3] +
          ',"spatialReference":{"wkid":102100}}'
      ) +
      '&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*' +
      '&outSR=102100';
    return url;
  },
  strategy: tileStrategy(
    createXYZ({
      tileSize: 512,
    })
  ),
});
```

**Comment by MoonE** [comment]
There is still a problem with ImageLayer because it only starts loading once all animations / interactions are finished. While interacting you get rendercomplete events with an incomplete map.

**Comment by ahocevar** [comment]
@MoonE would you be able to provide a fix for that Image layer issue? That would be great.

**Comment by murdocha** [comment]
Thank you for being active on addressing these issues!

I'd also chime in here and say that this issue may still need to be fully addressed before closing. 
I did initially provide demos of the problem which reference issues with both Image Layers _and_ Vector Layers (though we did focus specifically on the Vector Layer issue in the comment thread).

**Comment by murdocha** [comment]
Just an update: 
For my particular application-specific issue, I was able to re-purpose this sample as a work-around with the current release of OpenLayers:
https://openlayers.org/en/latest/examples/image-load-events.html
to track all prerender and postrender events for all the layers I load to our map object. This lets me track when all layers on the map are rendered without having to use a "global" map rendercomplete event. This works for both imagelayers and vectorlayers, but I _do_ have to add these event handlers explicitly to each layer object separately.
Bonus, is that the UI looks nicer with the progress bar giving an indicator of how much rendering activity is taking place...
