### ISSUE TITLE
Snap interaction does not work on points drawn on the edge of a polygon

### ISSUE THREAD

**Issue by digoburigo** [openlayers/openlayers#11931]
**Describe the bug**
The snap interaction on points drawn in the edge of a polygon does not work the way I expected.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/snap.html
2. Draw a polygon, then draw points in the edge of the polygon
3. You will see that the snap does not work on points in the edge of the polygon
4. In my project I tried to disable the `edge` option on the Snap interaction, but did not work either
![image](https://user-images.githubusercontent.com/28462822/105246400-f7a20080-5b51-11eb-8b6f-81879bf33568.png)

**Expected behavior**
I want to know if it's possible to implement this behavior or i'm not doing the right way

Thanks for your time.

**Comment by mprins** [comment]
same for linestrings and circles that have points drawn over them, seems as though higher order dimensioned geometries are preferred as a snapping target
