### ISSUE TITLE
CartoDB Source documentation URLs have changed

### ISSUE THREAD

**Issue by geraldo** [openlayers/openlayers#11949]
URLs in [CartoDB API docs](https://openlayers.org/en/latest/apidoc/module-ol_source_CartoDB-CartoDB.html) are wrong, correct ones are:

- anonymous maps: https://carto.com/developers/maps-api/guides/anonymous-maps/
- named maps: https://carto.com/developers/maps-api/guides/named-maps/

**Comment by ahocevar** [comment]
Thanks for reporting this, @geraldo. It would help us a great deal if you could create a pull request with this fix.
