### ISSUE TITLE
Call Full Screen control of Map Programatically

### ISSUE THREAD

**Issue by spandanparikh** [openlayers/openlayers#11940]
I am using open layer map, I have added full screen control, using which I am displaying open layer map in full screen mode. I want call that control programatically. 

**Describe the solution you'd like**
I need a way to call full screen control of open layer map, programatically.

**Comment by MoonE** [comment]
`map.getTargetElement().requestFullscreen();` will put the map in full screen, but browsers may prohibit this as a security measure, if it is run outside a event handler for a user generated event.
