### ISSUE TITLE
Could not load a map with EPSG:404000 from GeoServer

### ISSUE THREAD

**Issue by Gannalyo** [openlayers/openlayers#11958]
I published two map in GeoServer, and one EPSG code is 'EPSG:3857' and the other is 'EPSG:404000'.
It worked to load the first one by openlayers 3, and fail for second.

**information in geoserver:**
![image](https://user-images.githubusercontent.com/34175244/106238630-2730c700-623c-11eb-99e4-6be7bc96922f.png)

**code by openlayers:**
![image](https://user-images.githubusercontent.com/34175244/106238347-ae316f80-623b-11eb-9aee-5348302d4770.png)

**Comment by mike-000** [comment]
You will need to declare EPSG:404000 in the same way as EPSG:21781 in this example https://openlayers.org/en/v4.6.5/examples/wms-no-proj.html  You will not be able to use `fromLonLat` and will need to specify the center in EPSG:404000 coordinates.

**Comment by Gannalyo** [comment]
> You will need to declare EPSG:404000 in the same way as EPSG:21781 in this example https://openlayers.org/en/v4.6.5/examples/wms-no-proj.html You will not be able to use `fromLonLat` and will need to specify the center in EPSG:404000 coordinates.

It works now, thank you very much.
