### ISSUE TITLE
How to prevent jumping to new marker?

### ISSUE THREAD

**Issue by FireWingHu** [openlayers/openlayers#11956]
Hi All,
could you help please? I'm using OSM/OL for a project, and I'm displaying some markers on the map. In the background I'm querying a MYSQL table with ajax in every minute, and modifying the location of the markers, or removing/pinning new markers, if necessary. In case of pinning a new marker (as a new div element) the map jumps to that location automaticly. Is it possible to disable this? I would like to preserve the original view with the original position and original zoom independently from the new marker.

Thanks in advance,
P

**Comment by jipexu** [comment]
Hi
Difficult to understand and try to answer  without some piece of code ..
