### ISSUE TITLE
Map::getFeaturesAtPixel() and VectorLayer::getFeatures() should return feature drawn by CanvasImmediateRenderer::drawFeature()

### ISSUE THREAD

**Issue by Antoninum** [openlayers/openlayers#11957]
**Describe the bug**
I'm not sure if this is a bug or a missing feature, feel free to edit the issue type.

The function Map::getFeaturesAtPixel() doesn't return features that have been drawn with CanvasImmediateRenderer::drawFeature() like in the [marker animation example](https://openlayers.org/en/latest/examples/feature-move-animation.html).
This is also the case for VectorLayer::getFeatures()

**To Reproduce**
1. Go to https://codesandbox.io/s/feature-move-animation-forked-kc7i6?file=/main.js
2. Start the animation then hover your mouse on the marker
3. The wanted message is not printed into the console. I also tried to log all the features founded to find if it were returned, but it is not.

**Expected behavior**
The Map::getFeaturesAtPixel() should return features drawn by CanvasImmediateRenderer::drawFeature().
The VectorLayer::getFeatures() should also do it.

I would like to change mouse pointer by hovering on this feature, or at least to be able to detect a click on it.

How can I achieve that currently ?
The only way I could think of would be to store the drawed feature coordinates, and to compare on click / hovering the pixels with one one returned by Map::getPixelFromCoordinate().
But it doesn't seem very efficient ; moreover I have several of such features (from 3 to possibly 30) moving.
As a side note, it would be good that I could detect the feature moving under the mouse pointer without moving it, (outside the on("pointermove") for example) but I'm not sure how to approach that.

Thank you for your time!

**Comment by mike-000** [comment]
There is no hit detection on vector context, you would need to update the real feature after each render (which is less efficient) https://codesandbox.io/s/feature-move-animation-forked-0f4w1  Also you `feature.type` test would not work, it needs to be `feature.get('type')` or `feature.getProperties().type`
