### ISSUE TITLE
error when import GEOJSON in typescript 

### ISSUE THREAD

**Issue by xuqinghan** [openlayers/openlayers#11966]
"@angular/cli": "^11.0.7",
"ol": "^6.5.0",
"@types/ol": "^6.4.2",
"typescript": "4.0.5"

**Describe the bug**

`import GeoJSON from 'ol/format/GeoJSON';`

> Error: src/app/pages/drive/my-map/my-map.component.ts:19:21 
> - error TS2307: Cannot find module '@type/ol/format/GeoJSON' or 
> its corresponding type declarations.
>     
>     19 import GeoJSON from '@type/ol/format/GeoJSON';
>                            ~~~~~~~~~~~~~~~~~~~~~~~~~
>     
> \ Generating browser application bundles (phase: additional asset processing)...    
>     Error: node_modules/@types/ol/format/GeoJSON.d.ts:4:5 - error TS2305: Module '"../../geojson"' has no exported member 'GeoJSON'.
>     
>     4     GeoJSON as GeoJSON_1,
>           ~~~~~~~
>     node_modules/@types/ol/format/GeoJSON.d.ts:5:5 - error TS2305: Module '"../../geojson"' has no exported member 'Geometry'.  
>     
>     5     Geometry,
>           ~~~~~~~~
>     node_modules/@types/ol/format/GeoJSON.d.ts:21:30 - error TS2707: Generic type 'Feature<G, P>' requires between 1 and 2 type 
> arguments.
>     
>     21 export type GeoJSONFeature = Feature;
>                                     ~~~~~~~
>     node_modules/@types/ol/format/GeoJSON.d.ts:22:40 - error TS2707: Generic type 'FeatureCollection<G, P>' requires between 1 and 2 type arguments.
>     
>     22 export type GeoJSONFeatureCollection = FeatureCollection;                                              ~~~~~~~~~~~~~~~~~
> 
>

**Comment by simonseyock** [comment]
This looks like you have a problem in your setup. You might try to turn on `skipLibCheck` in your tsconfig ( https://www.typescriptlang.org/tsconfig#skipLibCheck ) or try using https://github.com/hanreev/types-ol

**Comment by simonseyock** [comment]
This might also be an error in `@types/ol-types` which is not maintained by openlayers.

**Comment by xuqinghan** [comment]
> This might be an error in `@types/ol-types` which is not maintained by openlayers.

Thanks!. remove @types/ol-types, it works!

**Comment by simonseyock** [comment]
You could try https://github.com/hanreev/types-ol for a replacement
