### ISSUE TITLE
A point style with a rotated icon is in the wrong position for VectorTileLayer when pixelRatio > 1

### ISSUE THREAD

**Issue by pecet86** [openlayers/openlayers#11962]
**Describe the bug**
Rotating the style of a point element causes it to shift from the correct position if the map's pixelRatio is greater than 1

**To Reproduce**
1. OL version 6.5.0, 
6.4.3 is working only in `constrainResolution` is true
2. Create a map object with `pixelRatio` and a `vectorTileLayer` layer
```
const map = new Map({
  target: "map",
  pixelRatio: 1.25, // > 1
  layers: [
    new TileLayer({
      source: new OSMSource()
    }),
    vectorTileLayer
  ],
  view: new View()
});
```
3. Create the `vectorTileLayer` layer like this:
```
const vectorTiles = new VectorTileLayer({
  source: new VectorTileSource({
    format: new MVT(),
  }),
  style(feature) {
    const coords = feature.getGeometry().getFlatMidpoint();
    const style = new Style({
      stroke: new Stroke({
        color: "green",
        width: 5
      })
    });

    const styleArrow2 = new Style({
      geometry: new Point(coords),
      image: new Icon({
        src: "arrow.svg",
        rotateWithView: true,
        color: "blue",
        scale: 2
      })
    });
    const styleArrow3 = new Style({
      geometry: new Point(coords),
      image: new Icon({
        src: "arrow.svg",
        rotateWithView: true,
        color: "red",
        scale: 2,
        rotation: Math.PI * 2 // should be applied after full rotation
      })
    });

    return [style, styleArrow2, styleArrow3];
  },
  renderMode: 'image',
});

```
![image](https://user-images.githubusercontent.com/20416374/106300229-7e439580-6256-11eb-9807-63a62816980e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/20416374/106300146-64a24e00-6256-11eb-815b-08d0b71b9411.png)

**Comment by ahocevar** [comment]
@mike-000, would you be able to take a look at this? Thanks in advance.

**Comment by mike-000** [comment]
Integer pixel ratios > 1 work correctly.  The problem is related to fractional pixels ratios (including < 1) in triple combination with `renderMode: 'image'` and `declutter: false` (there is no problem with hybrid or vector render modes or when decluttering).

The problem became more apparent with 6.4.4-dev.1599475256503 which corresponds to PR #11521

Previously icons overlapped as expected when opening at integer zoom levels https://codesandbox.io/s/vector-tile-info-forked-4u2ty but the problem can be seen when using mousewheel zoom.

With 6.4.4-dev.1599475256503 https://codesandbox.io/s/vector-tile-info-forked-c5xlm it can be seen even at integer zoom levels.

**Comment by ahocevar** [comment]
Thanks for the investigation, @mike-000. So there are quite a few corner cases. Do you have an idea what the problem could be, and maybe even create a pull request? I think we'll also need more rendering tests, with simple tiles where we know exactly what's in there.

**Comment by mike-000** [comment]
This also affects labels, and when incorrectly placed both labels and images are incorrectly scaled.

![image](https://user-images.githubusercontent.com/49240900/106531307-e4921780-64e5-11eb-92cf-6b377a38e436.png)

The transforms produced by https://github.com/openlayers/openlayers/blob/main/src/ol/render/canvas/Executor.js#L401-L415 are not suitable for `renderMode: 'image'` as it is currently implemented.
