### ISSUE TITLE
d3 integration example no rotation for svg layer

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#11964]
Hi
In this example https://openlayers.org/en/latest/examples/d3.html 

when you rotate the map the svg layer doesnt rotate ...

I have a playground here https://observablehq.com/@jipexu/openlayers-d3js-map-svg-with-json where i try to make it work ..

any advice are welcome
Thank

**Comment by mike-000** [comment]
```
    var rotation = -frameState.viewState.rotation * 180 / Math.PI;
    d3Projection
      .scale(scale)
      .center(center)
      .translate([width / 2, height / 2])
      .rotate([rotation, rotation, 0]);
```

gets the rotation working but the offsets for the `translate` will also need to take the rotation into account

**Comment by jipexu** [comment]
@mike-000 thanks i just modified and get the rotate work but yes we need more to keep a good "scale size"

**Comment by mike-000** [comment]
There is a simpler angle method https://github.com/d3/d3-geo#projection_angle which works without needing any other changes 

```
    d3Projection
      .scale(scale)
      .center(center)
      .translate([width / 2, height / 2])
      .angle(rotation);
```

https://codesandbox.io/s/d3-forked-potcb

**Comment by jipexu** [comment]
at usually good job @mike-000 thanks it's work ! do you think we have to make a PR ?

**Comment by ahocevar** [comment]
If you were able to get rotation working as expected, please submit a pull request.

**Comment by jipexu** [comment]
@ahocevar 
seems work fine here  
https://observablehq.com/@jipexu/openlayers-d3js-map-svg-with-json 
and here
 https://codesandbox.io/s/d3-forked-potcb
@mike-000  ??
