### ISSUE TITLE
Vector tile layer cuts icons on the tile edges

### ISSUE THREAD

**Issue by sundholmm** [openlayers/openlayers#11961]
**Describe the bug**
Updating OpenLayers version from version 6.4 to 6.5 causes icons to get cut on tile edges. This did not happen on version 6.4 and can easily be reproduced on version 6.5. Cutting happens every time an icon intercects tile edge. I have tried setting render mode to all of the possible values but cutting still occurs. No code in the application was changed between the versions as changelog didnt mention any mandatory changes and major version didnt change. The icons are in SVG format if that matters. I also tried disabling webpack plugin ImageMinimizerPlugin but that didn't help either.

![image](https://user-images.githubusercontent.com/35702949/106271558-5cd3b100-6238-11eb-90d9-53652a026eb2.png)

**To Reproduce**
Update OpenLayers to version 6.5 and render icon on vector layer tile edge.

**Expected behavior**
The icon should not get cut and should be visible as whole.

**Comment by mprins** [comment]
Seems a duplicate of #11884

**Comment by sundholmm** [comment]
So it seems, sorry didn't notice!
We can expect the fix to be in the next release?

**Comment by ahocevar** [comment]
Yes, and in the meantime you can `npm install ol@dev`.

**Comment by sundholmm** [comment]
Alright, thank you!
