### ISSUE TITLE
Improve overall typing of openlayers

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#11960]
At the moment I am looking into how to improve the typing of openlayers to improve a) typechecking (also in dependent projects) and b) generation of typescript typings.

Options
----------

One huge issue that I have with the typing of openlayers are the `Options` objects of the layers. They all have a certain amount of strictly typed properties and can also accept arbitrary properties that get passed to the `BaseObject`. For typing purposes this bad.

What I would like to see is that all `Options` objects would get a property `properties` which would get passed to the `BaseObject`. I would like to look into this if you like the idea. This would be a breaking change and would only get included in v7. This mainly would affect the api of the layer types.

Nevertheless I found a way to type this properly in JSDoc, namely using
```
* @param {Options & Object<string, *>} opt_options Options.
``` 
Here is a PR for this: https://github.com/openlayers/openlayers/pull/11959

BaseObject
----------------

Maybe it is possible to incorporate `@template` Variables for the properties ( https://github.com/openlayers/openlayers/issues/11572 ).

Generic source types for layers
-----------------------------------------

I created a PR for improved generic source types of layers here: https://github.com/openlayers/openlayers/pull/11948
The `Layer` and `BaseVectorLayer` were already using it but all other types are missing it. This mainly improves the types of `getSource` and `setSource`, but also improves assignability. For example assignig an `ImageLayer` to a variable of a type `Layer<ImageSource>`.

I will continue to gather some issues here.

**Comment by simonseyock** [comment]
Sadly `{Options & Object<string, *>}` is no valid JSDoc but is a valid typescript type and is therefore supported by the tsc (See https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#type ).

Would it be possible to remove this in `jsdoc-plugin-typescript` or would there need to be an adjustment to `valid-tsdoc` of eslint as well?

**Comment by tschaub** [comment]
Another idea is to get rid of BaseObject altogether.  I would be in favor of doing this in a v7.

**Comment by simonseyock** [comment]
Yes, it could be replaced with a property `properties` with `getProperties()`, `setProperties()` and a change event. It can than be easily of a generic type.

**Comment by simonseyock** [comment]
This would only be relvant for layers and features.

**Comment by simonseyock** [comment]
I tested a simple transformation in `jsdoc-plugin-typescript` that just removes the string `& Object<string, *>` from all jsdoc comments. With this the apidoc generation does run, but the `valid-jsdoc` check of eslint will still fail.

Having this would improve the typescript types that are generated directly from the source greatly. As far as I see they could be used without any further modifications in of our greater TypeScript projects. I will check it for other projects as well.

Would you agree on having such a hack in `jsdoc-plugin-typescript` or would you rather wait till version 7 and just remove the `BaseObject`?

**Comment by ahocevar** [comment]
I'm in favor of getting rid of BaseObject too, but in the meantime I have a suggestion:
```diff
--- a/src/ol/layer/Layer.js
+++ b/src/ol/layer/Layer.js
@@ -16,7 +16,7 @@ import {listen, unlistenByKey} from '../events.js';
  */
 
 /**
- * @typedef {Object} Options
+ * @typedef {Object} LayerOptions
  * @property {string} [className='ol-layer'] A CSS class name to set to the layer element.
  * @property {number} [opacity=1] Opacity (0, 1).
  * @property {boolean} [visible=true] Visibility.
@@ -42,6 +42,10 @@ import {listen, unlistenByKey} from '../events.js';
  * HTML element. Will overwrite the default rendering for the layer.
  */
 
+/**
+ * @typedef {LayerOptions & Object<string, *>} Options
+ */
+
 /**
  * @typedef {Object} State
  * @property {import("./Layer.js").default} layer
```
This way, eslint will be happy, and all that's left to do is to submit a pull request to https://github.com/hegemonic/catharsis. Maybe you want to take a look at that. It's pretty straightforward.

**Comment by simonseyock** [comment]
I was looking into the `valid-jsdoc` rule of eslint and found that it is deprecated since version 5 (openlayers uses v7). I think it might be worth a shot to try to use https://github.com/gajus/eslint-plugin-jsdoc which is the recommended replacement (see https://eslint.org/blog/2018/11/jsdoc-end-of-life) - and should support the intersection syntax (https://github.com/gajus/eslint-plugin-jsdoc/issues/545)

I might open a PR against `eslint-config-openlayers`.

**Comment by simonseyock** [comment]
I looked into it in the mentioned PR, but while providing some benefits it also has some blocking problems for now.

**Comment by tschaub** [comment]
Note that we don’t use `valid-JSDoc` but have our own custom rule here https://github.com/openlayers/eslint-plugin/blob/master/valid-tsdoc.js.

**Comment by simonseyock** [comment]
Ok, the name was misleading me. The `eslint-jsdoc-plugin` should be able to enforce the rules that are contained in the custom rule - as far as I can see. I also recognized that there is only one issue that is blocking one of the rules that were in place before.

I ordered and commented the rules in the PR so they are a little easier to review if you like to already take a look at it.

**Comment by simonseyock** [comment]
I will look into catharsis, as the author seemed to be open to changes (https://github.com/hegemonic/catharsis/issues/64), but I assume it will take quite some time till these changes would reach a prod version of jsdoc, as the author wants to have a seperate typescript mode.

Out of curiosity I started to write a pratt-parser for jsdoc types (https://github.com/simonseyock/jsdoc-type-pratt-parser) that could be used in `jsdoc-plugin-typescript` to transform types instead of a regex. I plan on improving the parser in the future and one of the contributors of `eslint-plugin-jsdoc` also is interested in it.

In the mean time, https://github.com/openlayers/eslint-config-openlayers/pull/25 is ready for release in my opinion, it would be nice if it could get merged and released.

**Comment by ahocevar** [comment]
I created #12219 with a pragmatic solution to the problem of setting arbitrary observable properties in constructors.

**Comment by simonseyock** [comment]
Based on your commit I will see if we can introduce `@template` annotations on the options object for the properties object and the source object for layers. I tried that and it works but the jsdoc output is not generated correctly anymore. I will see what is causing that.

**Comment by simonseyock** [comment]
I think with #12219 it makes sense to publish the declarations again. I used the command `tsc --declaration --emitDeclarationOnly --noEmit false --outDir declaration` for this. It should be possible to do `tsc --declaration --emitDeclarationOnly --noEmit false --outDir build/ol`.

**Comment by simonseyock** [comment]
I opened https://github.com/openlayers/openlayers/pull/12223 for generic option types. I will add the properties as another generic parameter. Sadly it is not possible at the moment to set a default type for the generic parameter (https://github.com/Microsoft/TypeScript/issues/29401), but it might be possible in the future.

**Comment by simonseyock** [comment]
FYI: I created https://github.com/simonseyock/jsdoc-type-pratt-parser and will see what the folks at jsdoc think about it: https://github.com/jsdoc/jsdoc/issues/1917

**Comment by namedgraph** [comment]
So what's the status with the office TS typings?

**Comment by ahocevar** [comment]
They are included in v6.6.0 and higher.

**Comment by namedgraph** [comment]
@ahocevar cool! Any usage examples?

**Comment by ahocevar** [comment]
@namedgraph Just `npm install ol` and work with it, like with any other dependency. Example: https://codesandbox.io/s/rough-dew-6dwz8?file=/index.html
