### ISSUE TITLE
Typo in script tag at example

### ISSUE THREAD

**Issue by birbilis** [openlayers/openlayers#11973]
at
https://openlayers.org/en/latest/examples/vector-tiles-4326.html
it says
`    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=String.prototype.startsWith,Object.assign""></script>
`
should change the doublequote at the end to appear once, not twice (now it has a double doublequote ;-)

**Comment by mike-000** [comment]
The line can be removed completely, ol-mapbox-style no longer needs any additional polyfills.

**Comment by mike-000** [comment]
There is also an inconsistency with the default polyfills, they are only being included in the examples when there are other resources specified.

**Comment by birbilis** [comment]
Is there any way one can find which polyfills they need to use to support older browsers when using various OpenLayers features? I mean without doing trial and error and trying to get remote debug output from older devices with BrowserStack and similar services.

**Comment by mike-000** [comment]
```
    <script src="https://unpkg.com/elm-pep"></script>
    <script src="https://cdn.polyfill.io/v3/polyfill.min.js?features=fetch,requestAnimationFrame,Element.prototype.classList,URL,TextDecoder,Number.isInteger"></script>
```

should be sufficient for all supported browsers unless an example uses additional external resources (the polyfill for `fetch` includes `Promise`).  Future version might use code needing these polyfills where currently not needed, so best include all instead of trying to filter by feature.

**Comment by birbilis** [comment]
I had noticed recently that telling unpkg to bring the latest version of a library can cause delays. You should test it and consider providing an explicit version there (I know it's more troublesome though to maintain). If you enter the url for the latest version of elm-pep it does resolve it to https://unpkg.com/elm-pep@1.0.6/dist/elm-pep.js currently.

quoting
https://unpkg.com/

> Cache Behavior
>
> The CDN caches files based on their permanent URL, which includes the npm package version. This works because npm does not allow package authors to overwrite a package that has already been published with a different one at the same version number.
> 
> Browsers are instructed (via the Cache-Control header) to cache assets indefinitely (1 year).
> 
> URLs that do not specify a package version number redirect to one that does. This is the latest version when no version is specified, or the maxSatisfying version when a semver version is given. Redirects are cached for 10 minutes at the CDN, 1 minute in browsers.
> 
> If you want users to be able to use the latest version when you cut a new release, the best policy is to put the version number in the URL directly in your installation instructions. This will also load more quickly because we won't have to resolve the latest version and redirect them.

**Comment by birbilis** [comment]
Btw, just noticed that OpenLayers 6.5.0 doesn't work anymore in Internet Explorer 11 due to use of "...", use of const in for loops etc. Is this on purpose? Is there any version that works with IE11? (say pretranspiled with Babel or something)

OpenLayers 6.4.3 still works fine so moved back to that one.

**Comment by mike-000** [comment]
See #11870  You can download a dev build from https://openlayers.org/en/main/build/ol.js and https://openlayers.org/en/main/build/ol.js.map

**Comment by birbilis** [comment]
thanks for the pointer, I see the fix will go into the next release - https://github.com/openlayers/openlayers/issues/11870#issuecomment-757691016, will probably wait for that for the time being since 6.4.3 seems to work ok for my use case
