### ISSUE TITLE
[Question] Best way to save "continuously grabbed" geolocation data?

### ISSUE THREAD

**Issue by rowild** [openlayers/openlayers#11972]
I am sorry to post my question here, but it is a vague one, and it keeps getting downvoted on Stackoverflow and the commenting system gets locked. I hope someone can direct me to the proper sources (because I don't even know how to search properly... I believe I use the wrong vocabulary...)!

At the moment I am trying to put together my first PWA geolocation app with vue, openlayers and indexeddb. It should/will work much like other activity apps, where I can create an activity, record geolocation and - when finished - re-draw the path of any of my saved activities by fetching the data from the proper indexeddb entry, where - according to the current plan - geolocation data is saved as an object of arrays (for faster access compared o objects? and keeping data as small as possible?):
 
```js
geoloc {
  [16.444444,48.333333], 
  [...],
  [...]
}
```

I wonder if this is how it is supposed to be done? So far I was unable to find out how apps like Bikemap or Runtastic do that. (Does anybody?)
I have my doubts with my solution, since an activity lasting one hour could potentially save 86400 entries to the DB (if geolocation's timeout is set to 1000).

Is my approach "correct" or total BS? Are there better ways to store geolocation data? Does anybody know of a source, where this is discussed?

Thank you very much! And apologies for intruding!

**Comment by Rskut** [comment]
I would recommend asking this question on https://gis.stackexchange.com/. I think you don't need that many location points to follow a path
