### ISSUE TITLE
Mapbox Vector Layer opacity is not applied to labels

### ISSUE THREAD

**Issue by amshel** [openlayers/openlayers#11982]
Change opacity of a Mapbox Vector Layer with declutter false doesn't change labels opacity

1. Go to https://codesandbox.io/s/mapbox-vector-layer-forked-pthnb?file=/main.js
2. Opacity doesn't change for labels

**Expected behavior**
Opacity for labels should also be applied.

**Comment by mike-000** [comment]
The issue seems to apply to all VectorTile layers, for icons as well as labels, and in version 6.5.0 also with declutter true.

**Comment by ahocevar** [comment]
#11987 fixes this issue. The issue also causes layer opacity to be ignored when `renderMode: 'vector'` is used.
