### ISSUE TITLE
openlayers and cypress: drag drop and editing problems

### ISSUE THREAD

**Issue by carlosjpr-collab** [openlayers/openlayers#11985]
I try to do a E2E test for openlayers last version 6 using cypress 6. I need to select features by using box. The cypress generates the events and the browser is able to capture it. But the openlayers is not able to detect mouse events.

Openlayers detect only click events.

This is a working example. 

```
describe('test openlayers', () => {
    beforeEach(() => {
    })
  
    it('Test box selection', function () {
      cy.visit('https://openlayers.org/en/latest/examples/box-selection.html')
          // Select beacon edition
    // Check that the beacons are drawned correctly
    cy.get('canvas')
    .trigger('{ctrl}mousedown', 50, 50)
    .trigger('{ctrl}mousemove', {x:500, y:300})
    .trigger('{ctrl}mouseup', 500, 300)

    }) 

```
 same issue   but no real solution
https://stackoverflow.com/questions/62303304/cypress-with-openlayers-how-to-simulate-ctrl-mouse-drag

**Comment by ahocevar** [comment]
OpenLayers uses pointer events. Maybe you're more lucky with `pointerdown`-`pointermove`-`pointerup`, because it might be that the pointer events polyfill does not work with Cypress.
