### ISSUE TITLE
Map no longer renders unless map div height specified explicitly

### ISSUE THREAD

**Issue by robalexclark** [openlayers/openlayers#11984]
Bug spotted when upgrading from OL 5 to 6.

I did notice someone had opened a previous issue #10327 but it has gone stale. I think we do either need a fix or an explanation as it is not obvious what the issue is.

For an example using version 6 see 
https://test.floodassist.co.uk/flood-warnings/flood-area-info/cambridgeshire/055fwfpmne08/areas-near-the-river-nene-from-elton-to-wansford

For the working version (OL 5)  see
https://floodassist.co.uk/flood-warnings/flood-area-info/cambridgeshire/055fwfpmne08/areas-near-the-river-nene-from-elton-to-wansford

If I use chrome tools to change the page-map-size css class from min-height:600px to height:600px the map suddenly renders correctly.

**Comment by ahocevar** [comment]
I think you are right, @robalexclark. In #11988 I added a warning to let the user know when the container's width or height are `0`.
