### ISSUE TITLE
Problem with cluster layer

### ISSUE THREAD

**Issue by aldermoriggi** [openlayers/openlayers#11986]
Hello everyone, I have a problem with clusters when I use geographic coordinates.
If I set any distance of the cluster layer (for example 40) all the features appear concentrated in a single point (Image 1).
Only by setting the distance to 0 the features appear each with the correct coordinates, 1 to 1 however (Image 2).
I've used the same code in another project, using EPSG: 3004 as the coordinate system, and have not encountered any problems.
Can anyone help me out?

TIA
Alder

![OpenLayers_1](https://user-images.githubusercontent.com/10754641/107089149-6d6ac500-67fe-11eb-93af-918334de732c.png)

![OpenLayers_2](https://user-images.githubusercontent.com/10754641/107089169-7491d300-67fe-11eb-8f6f-08cfc3afae7b.png)

**Comment by aldermoriggi** [comment]
Here mi code:

var l_Tile = new ol.layer.Tile({ source: new ol.source.OSM() });

l_Layers.push(l_Tile);

//Feature Puntuali
var l_Features_Impianti = Get_Features_Projects();
var l_Features_Impianti_Cluster = new Array(l_Features_Impianti.length);
var l_Count = 0;
var l_Style_Cache = {};

l_Features_Impianti.forEach(function (p_Feature) {
	try {
		l_Point = new ol.geom.Point([p_Feature.values_.LONGITUDE, p_Feature.values_.LATITUDE]);
		l_Feature_2 = new ol.Feature({ geometry: l_Point });
		l_Features_Impianti_Cluster[l_Count] = l_Feature_2;
		l_Count += 1;
	}
	catch (err) {
	}
});

var l_Layer_Impianti_Cluster = new ol.layer.Vector({ source: new ol.source.Cluster({ distance: 40, source: new ol.source.Vector({ features: l_Features_Impianti_Cluster }) }) });

l_Layer_Impianti_Cluster.setProperties({ name: "Cluster" });
l_Layers.push(l_Layer_Impianti_Cluster);

l_Layer_Impianti_Cluster.setStyle(function (p_Feature) {
	var l_Size = p_Feature.get('features').length;
	var l_Style = l_Style_Cache[l_Size];

	if (!l_Style) {
		l_Style = new ol.style.Style({
			image: new ol.style.Circle({
				radius: 10,
				stroke: new ol.style.Stroke({
					color: '#fff'
				}),
				fill: new ol.style.Fill({
					color: '#3399CC'
				})
			}),
			text: new ol.style.Text({
				text: l_Size.toString(),
				fill: new ol.style.Fill({
					color: '#fff'
				})
			})
		});
		l_Style_Cache[l_Size] = l_Style;
	}
	return l_Style;
});

m_Map = new ol.Map({
	layers: l_Layers,
	target: 'map',
	view: new ol.View({
		center: [l_Longitude, l_Latitude],
		zoom: l_Zoom
	}),
	overlays: m_Overlay === undefined ? [] : [m_Overlay]
});

**Comment by MoonE** [comment]
The code you provided seems fine.

Either something is wrong with the coordinates you are using or you are you are using an outdated version.
Please provide a runnable example that shows the problem. You can use this sandbox where I pasted (and slightly modified) your code as a starting point:
https://codesandbox.io/s/openlayers-cluster-11986-nydtc?file=/src/index.js

**Comment by aldermoriggi** [comment]
Thank you MoonE, I forked the sandbox you provided and reproduced the problem

https://codesandbox.io/s/openlayers-cluster-11986-forked-xg2ns

TIA
Alder

**Comment by MoonE** [comment]
Seems like the problem is caused by `useGeographic`.
If you set a cluster distance of `0.0002` it works. Though the cluster distance on the map changes with the latitude of the position. If your features are all roughly in the same latitude it won't be noticeable.

You could also not use `useGeographic` and transform your coordinates  to `EPSG:3857`
```js
features[i] = new ol.Feature(new ol.geom.Point(ol.proj.fromLonLat(coordinates)));
```

**Comment by aldermoriggi** [comment]
Thank you MoonE, with 0.0002 as cluster distance it works ;-)

**Comment by ahocevar** [comment]
It would be nice to make `useGeographic` work here.

**Comment by aldermoriggi** [comment]
> It would be nice to make `useGeographic` work here.

I forked the sandbox [https://codesandbox.io/s/openlayers-cluster-11986-forked-sbd3p] with useGeographic and 0.0002 as cluster distance

**Comment by MoonE** [comment]
I could assume a EPSG:3857 projection for the view but that may be equally wrong.
If the cluster source should always use the view's pixel distance it needs to know the used projection, but that information is not available in the source. Do you have a suggestion on how to solve this,  @ahocevar?

**Comment by ahocevar** [comment]
@MoonE I think this needs to be solved by the renderer passing the correct resolution to the `loadFeatures()` function.  It already passes the correct projection and extent, but not yet the resolution. So a fix would look something like this:
```js
--- a/src/ol/renderer/canvas/VectorLayer.js
+++ b/src/ol/renderer/canvas/VectorLayer.js
@@ -20,6 +20,7 @@ import {
   buffer,
   containsExtent,
   createEmpty,
+  getCenter,
   getWidth,
   intersects as intersectsExtent,
   wrapX as wrapExtentX,
@@ -32,6 +33,7 @@ import {
 } from '../vector.js';
 import {
   fromUserExtent,
+  getPointResolution,
   getTransformFromProjections,
   getUserProjection,
   toUserExtent,
@@ -629,7 +631,7 @@ class CanvasVectorLayerRenderer extends CanvasLayerRenderer {
       for (let i = 0, ii = loadExtents.length; i < ii; ++i) {
         vectorSource.loadFeatures(
           toUserExtent(loadExtents[i], projection),
-          resolution,
+          resolution / getPointResolution(userProjection, 1, getCenter(extent), projection.getUnits()),
           userProjection
         );
       }
```
