### ISSUE TITLE
The values in array returning from lineSting forEachSegment are wrong

### ISSUE THREAD

**Issue by ChienShan** [openlayers/openlayers#11980]
"ol": "^6.5.0",

**Describe the bug**
I try to get the start and end point coordinates of segment using forEachSegment method, like this:
```javascript
feature.forEachSegment(function (from, to) {
   console.log('forEachSegment', from, to);
});
```

And the result in console seems correct
![image](https://user-images.githubusercontent.com/55428933/106867353-74afa700-6708-11eb-9f27-8c1319dd455a.png)

After stored the start and end point coordinates of each segment in another arrays, however, I got this:
```javascript
[ 
     [
          [3576702.088271712, 2507822.580733749],  [3576702.088271712, 2507822.580733749]
     ],
    [
          [3576702.088271712, 2507822.580733749],  [3576702.088271712, 2507822.580733749]
     ],
]
```

Then I found the values of each array in console are all same as the final one:
![image](https://user-images.githubusercontent.com/55428933/106869407-dbce5b00-670a-11eb-9d96-59b118d1b0c9.png)

**Comment by ahocevar** [comment]
See #11371

**Comment by ChienShan** [comment]
Got it, thanks.
