### ISSUE TITLE
Caching problem with devicePixelRatio and ImageCanvas combination

### ISSUE THREAD

**Issue by dbetka** [openlayers/openlayers#11983]
**Describe the bug**
While `devicePixelRatio` change (without reloading page) map doesn't update that value and works on the old one. Since that `ImageCanvas` has the same number of pixels before and after change `devicePixelRatio`. But if you reload page with map on different `devicePixelRatio` then `ImageCanvas` has different number of pixels.

Short explanation:
- `devicePixelRatio` is not updating while map is working.
- Map work different after change `devicePixelRatio` without reloading page and after reload it.

**Environment preparation**
Steps to reproduce the environment:
1. Create file `index.html` contains:
```
<!doctype html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/css/ol.css"
        type="text/css">
  <style>
      .map {
          height: 600px;
          width: 100%;
      }
  </style>
  <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js"></script>
  <title>OpenLayers example</title>
</head>
<body>
<h2>My Map</h2>
<div id="map" class="map"></div>
<script type="text/javascript">
  const map = new ol.Map({
    target: 'map',
    layers: [
      new ol.layer.Tile({
        source: new ol.source.OSM()
      })
    ],
    view: new ol.View({
      center: ol.proj.fromLonLat([37.41, 8.82]),
      zoom: 4
    }),
  });

  const canvasLayer = new ol.layer.Image({
    source: new ol.source.ImageCanvas({
      canvasFunction: () => {
        const canvas = document.createElement('canvas')
        const ctx = canvas.getContext('2d')
        const [width, height] = map.getSize()
        console.log({width, height}, window.devicePixelRatio)
        canvas.style.position = 'absolute'
        canvas.style.pointerEvents = 'none'
        canvas.style.width = String(width) + 'px'
        canvas.style.height = String(height) + 'px'
        ctx.canvas.width = width
        ctx.canvas.height = height

        ctx.clearRect(0, 0, width, height)
        ctx.strokeStyle = 'red'
        ctx.rect(50, 50, width - 100, height - 100)
        ctx.stroke()

        return canvas
      },
      projection: 'EPSG:3857',
      ratio: 1,
    }),
  })
  map.addLayer(canvasLayer)
</script>
</body>
</html>
```
2. Open `index.html` in Google Chrome browser
3. Run `Developer tools` (press F12)
4. Toggle device toolbar (press CTRL + SHIFT + M)
5. Edit list of available emulated devices
6. Add custom device 
```
name: High resolution
width: 1000
height: 800
device pixel ratio: 2
type: desktop
```
7. Add custom device again
```
name: Low resolution
width: 1000
height: 800
device pixel ratio: 1
type: desktop
```
8. Close list of available emulated devices

**To Reproduce**
1. Switch emulated device to `High resolution`
2. Reload page - now canvas has 1968x1200 size. 
3. Switch emulated device to `Low resolution`
4. Reload page - now canvas has 984x600 size.
5. Switch emulated device to `High resolution`
6. DO NOT reload page - now canvas has still 984x600 size (here should be 1968x1200)

**Other explanation**
CASE A:
Set devicePixelRatio to 1 and reload page
devicePixelRatio: 1
canvas size: 984x600 px

CASE B:
Change devicePixelRatio from 1 to 2 and reload page
devicePixelRatio: 2
canvas size: 1968x1200 px

CASE C:
Change devicePixelRatio from 1 to 2 WITHOUT reloading page
devicePixelRatio: 2
canvas size: 984x600 px (here should be 1968x1200 px)

**Expected behavior**
Map should update devicePixelRatio while running - not only on startup.

**Comment by mike-000** [comment]
All maps are created with fixed a pixel value, either a specified value or whatever the device value is at the time of creation.  There is a documentation issue, the `canvasFunction` does not receive the _device_ pixel ratio as stated at https://openlayers.org/en/latest/apidoc/module-ol_source_ImageCanvas.html#~FunctionType it receives the _**map's**_ pixel ratio which, together with the size, should be used in the function

```
canvasFunction: (extent, resolution, pixelRatio, size, projection) => {
  console.log(pixelRatio, size);
  ....
}
```
