### ISSUE TITLE
VectorLayer may use outdated hitdetect image

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#11994]
**Describe the bug**
The hitdetect image may not be updated when the map is moved horizontally and wrapX is enabled.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/hitdetect-vector.html
2. Open devtools
3. enable keyboard input with `document.getElementById('map').tabIndex = 0`
4. put focus on map by clicking on it
5. use left / right keys to  move map
6. move mouse to test hit detection

**Expected behavior**
It should hitdetect features under the mousepointer only.

**Comment by ahocevar** [comment]
Interesting issue. Do you have an idea what might be causing this, @MoonE ? Scrolling with the keyboard vertically does update the hit detect image.

**Comment by MoonE** [comment]
It is caused by the gutter calculation here:
https://github.com/openlayers/openlayers/blob/e82a86f56337cfa394235df7528da032a5afbf30/src/ol/renderer/canvas/VectorLayer.js#L547-L567
The extent min x is changed to -540 and max x to 540. Because of this the extent check here succeeds.
https://github.com/openlayers/openlayers/blob/e82a86f56337cfa394235df7528da032a5afbf30/src/ol/renderer/canvas/VectorLayer.js#L594-L603

Setting the x extent to the range -540 to 540 here once you leave world 0 will cause  replay groups for the whole world in x direction to be created even when you are at a very high zoom level.
You can see it when you drag the map from left to right. All features are drawn wheres from top to bottom only those that are in the extent at drag start will be drawn.
