### ISSUE TITLE
Non-3857 WMTS no longer fetch tiles

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers#12017]
**Describe the bug**
Looks like a regression. Up to 6.4.3, WMTS worked fine in all projections. From 6.5.0, only EPSG:3857 works.

**To Reproduce**
Try code at https://github.com/probins/testol/blob/master/wmts4326.js which uses a Polish server in 4326 (other projections need transformed coords, so are more work to test).

For browsers with import maps enabled, I've set up a test page at https://cdn.statically.io/gh/probins/testol/2a5f53c6/wmts4326.html?v=6.4.3 which loads the source from the repo (unminified, so may take a while to load depending on connection). The query string is the version/commit number, so v=6.4.3 works, but v=6.5.0 and v=98ac74e (currently the latest commit) don't.

**Expected behavior**
Tiles should be fetched from the server, but nothing happens. There are no console errors.

When I've had this problem in the past, it's generally because I've forgotten to transform the extent coords, so I'm guessing something is preventing this from happening. I took a quick look through the changes 6.4.3-6.5.0, but didn't find an obvious culprit.

WMS/TileImage continue to work fine. Only WMTS doesn't.

**Comment by mike-000** [comment]
It works if the tilegrid `sizes` option is commented out.  Before #11532 that was ignored if extent was also specified.  As you are using top left as origin the y value of the sizes should be positive.

**Comment by probins** [comment]
ok, thanks. I will test the other non-3857 projections I use. Presumably the positive/negative value change is related to the change to internal tile coords in 6.0.0. This meant I had to invert all my TileImage coords, but was hidden in WMTS tilegrids if sizes was ignored anyway. I have always defined WMTS tilegrids with both sizes and extent, but it makes definition a bit simpler if it works with extent only.

**Comment by probins** [comment]
all the WMTS servers I use work fine without sizes, so I'll close this.
