### ISSUE TITLE
MapboxVectorLayer does not correctly set additional options

### ISSUE THREAD

**Issue by roemhildtg** [openlayers/openlayers#12014]
**Describe the bug**

If I pass an additional property to a MapboxVectorLayer, layer.get('customProp') does not return it.

For example: 

```

    const layer = new MapboxVector({
      type: 'ol/layer/MapboxVector',
      styleUrl: 'mapbox://styles/mapbox/light-v10',
      accessToken: 'xxxx',
      id: 'mapbox-gray',
    });
    
    layer.get('id') // -> undefined
```

**Expected behavior**

Most (if not all) other openlayers layer objects allow this. The use case is that I can populate the layer with some additional metadata that lets me find the layer in the future. I think that to ensure consistency in the API the mapbox layer should also allow this. 

I am able to contribute a pull request if this is an acceptable solution.

**Comment by tschaub** [comment]
I think we need to decide what direction we want to go with this.  I know that there is inconsistency in that some things allow arbitrary properties to be set.  It would be nice to have more consistency.

It seems like people like the flexibility of adding arbitrary properties to things like layers.

One of the drawbacks of this is that it is a liability if the library ever chooses to add properties (that may have different meaning, types, etc than how people are using them).

Another drawback of allowing arbitrary properties is that people then assume that the library will do things like ensuring they are applied to a clone (see #11071).

Disallowing arbitrary properties makes it possible to improve type checking within the library and for application developers (see #11960).

My personal opinion is that it was a mistake to make everything extend the common `BaseObject`, to mix user set properties with things that the library depends on, and to trigger events on all property changes.

I'm curious what others have to say about it.

**Comment by ahocevar** [comment]
I totally agree with @tschaub here, and I'd be in favor of making a breaking change, getting rid of `BaseObject`.

**Comment by mike-000** [comment]
As arbitrary user properties are accessed using `getProperties()` and `setProperties()` then in constructors instead of

`name: 'My Layer',`

it would be more logical to use

`properties: {name: 'My Layer'},`

In the case of features it would make OpenLayers features more consistent with GeoJSON features and avoid ambiguities in the use of geometry, id and style.

**Comment by roemhildtg** [comment]
I'll add my two cents here and thoughts.

> It would be nice to have more consistency.

Totally agree. I'm not opposed to removing the custom properties being assigned to the class level properties if it would improve consistency and help future proof the API. I would, however, like a way to pass custom properties to be stored _somewhere_ in the class. See below.

> It seems like people like the flexibility of adding arbitrary properties to things like layers.

Yes - and I don't necessarily want to overuse this but it is necessary to be able to store some custom properties on the layer itself. If this were available somehow in the layer, like `layer.getProperties().propertyNamae`, it doesn't really matter to me so long as I can do it. The reasons are:

1. First and foremost, I need a way to identify layers in the application. Components are created as modular classes that need to be told which layers to use, so I can specify things like which layers to use in a basemap switcher, or which layer to query in a table component, for example. 
2. Having other user defined properties on a layer can be useful, for example if I reference the basemap switcher again, I might want to define a property called `thumbnailUrl` to display to the user for that layer. There are other ways around this but it makes it convenient to have it on the layer. 
3. I would also like to mention that having the ability to define these properties in the constructor is super helpful. It helps because it avoids having to perform additional initialization logic on a layer, like in a `LayerFactory` that creates layers from a generic object.

```javascript
function layerFactory(options){
    const opts = omit(options, ['type']);

    switch(options.type){
        case 'Tile':
            
            return new ol.layer.Tile(opts);
        //.....
}

const layer = layerFactory({
     type: 'Tile',
     properties: { thumbnailUrl: 'images/my-basemap.png', id: 'aerial'},
     //..... 
});

layer.getProperties().id // -> 'aerial'

```

**Comment by simonseyock** [comment]
I would also want to weigh in here. I like the idea of having a properties object that can store object related data. In typed environments it would be very nice to have them as generics, even though you would need to do casts quite often.

One thing that is lost is the event listening system on single properties. I think that is also used quite much. It can be circumvented by having an event `change:properties`, but then to trigger the event you'd have to replace the whole properties object and check for any changes by yourself.

This is not very hard in the end:
```
layer.setProperties(Object.assign({}, layer.getProperties(), { prop: 'new value' }));
layer.on('change:properties', e => {
  if (e.oldValue.prop !== layer.getProperties().prop) {
    // ... do something ...
  }
});
```

**Comment by simonseyock** [comment]
Also I would like to say that I am open to implement theses changes if wanted.
