### ISSUE TITLE
Add web raster basemaps to ol/source/CartoDB

### ISSUE THREAD

**Issue by geraldo** [openlayers/openlayers#12013]
Carto offers different raster basemaps which can be used by OL with `ol/source/XYZ` as described at https://github.com/CartoDB/basemap-styles#1-web-raster-basemaps

OL already offers custom classes to use of map providers like BingMaps and Stamen, would it make sense to add Carto base maps to `ol/source/CartoDB`?

The use isn't free so, but licensing is similar to BingMaps: 

> Free usage for up to 75,000 mapviews per month, none-commercial services only.

**Comment by mike-000** [comment]
Unlike the existing ol/source/CartoDB and BingMaps classes the CartoDB basemaps are pure XYZ and don't require any initialisation https://codesandbox.io/s/simple-forked-e3see  That is similar to the MapTiler raster tiles used in many of the examples.  Without an account or API key I presume the free use limit is based on referrer?

**Comment by geraldo** [comment]
Right, that's the same as with OSM and Stamen basemaps. But ok, XYZ CartoDB basemaps are really easy to use and there is no need for a dedicated implementation.
