### ISSUE TITLE
Overlay position isn't update while drag map

### ISSUE THREAD

**Issue by dbretschneider** [openlayers/openlayers#12026]
**Describe the bug**
I've created an overlay based on Bootstrap 5 Beta2. During drag interaction the overlay isn't move.

**To Reproduce**
1. Go to 'https://jsfiddle.net/bretsch/f5qh1y2d/1/'
2. Click on a feature. Wait until overlay is shown and dragthe map.
3. Map is moving, but the overlay not.

**Expected behavior**
If using Bootstrap 5 -> While moving the map, the overlay should move too like in the [overlay example](https://openlayers.org/en/latest/examples/overlay.html) based on Bootstrap 4.7.0.

**Comment by M393** [comment]
You have to set the `container` of the bootstrap overlay to the `ol.Overlay`'s element.
If bootstrap adds the overlay to the document body it can't be moved by OpenLayers.

**Comment by dbretschneider** [comment]
I've updated the container to ```ovrlay.getElement()``` - now it works as expected 👍 
https://jsfiddle.net/bretsch/f5qh1y2d/3/
