### ISSUE TITLE
A getUrl immediately following a setUrl will return the old url for some sources

### ISSUE THREAD

**Issue by mmomtchev** [openlayers/openlayers#12046]
The following code will produce
```
http://url1
http://url1
```
```js
const source = new ol.source.Vector({url: 'http://url1', format: new ol.format.GeoJSON()});
console.log(source.getUrl());
source.setUrl('http://url2');
console.log(source.getUrl());
```

<https://jsfiddle.net/mmomtchev/v2mo1as3/6/>

It is not really a problem outside of unit testing since the url will eventually get modified, but still, it is a puzzling behaviour. Not all sources do it - `Vector` does it.

**Comment by mike-000** [comment]
It is because `setUrl` merely creates a new default loader then calls `setLoader` https://github.com/openlayers/openlayers/blob/main/src/ol/source/Vector.js#L1056  An extra line of code `this.url_ = url;` would make the setter and getter consistent.
