### ISSUE TITLE
Vector Layer Canvas Render incorrect

### ISSUE THREAD

**Issue by WernerRaath** [openlayers/openlayers#12048]
**Describe the bug**
The following occurs intermittently on client browsers even after updating to the latest versions of their browsers. These browsers include Safari, Chrome and Firefox.

In the below screenshot we can see that the layer canvas being highlighted. It is much smaller than the map and due to the different width/height aspect ratio from the base layer, the feature moves around on pan and is spatially inconsistent.

![Screenshot from 2021-02-19 10-28-19_cropped](https://user-images.githubusercontent.com/5022650/108480003-16a1c880-729f-11eb-9283-b0f7db0048a6.png)

Here is a screenshot of how it has moved with a slight pan. Notice that the 9500 is now directly above the polygon where before it was to the right of it.

![Screenshot from 2021-02-19 10-27-01_cropped](https://user-images.githubusercontent.com/5022650/108480809-15bd6680-72a0-11eb-8544-5b1fe837c402.png)

**To Reproduce**
1. It has been incredibly hard to reproduce since this only happens with some users

**Expected behavior**
That the layer canvas covers the whole map and no longer move feature positions on pan

**OL Version**
Open Layers 3 v6.5.0

**Comment by ahocevar** [comment]
I guess this can be reproduced on all devices with a device pixel ratio !== 1. But That's handled properly by OpenLayers. So you'd need to provide a working example that exposes the issue, e.g. by clicking "Edit" on one of the examples on https://openlayers.org/en/latest/examples/

**Comment by WernerRaath** [comment]
@ahocevar I'll do so asap!
