### ISSUE TITLE
[accessibility] Attribution control accessibility improvements

### ISSUE THREAD

**Issue by Malvoz** [openlayers/openlayers#12043]
After opening the collapsed attribution, the attribution links can not be navigated to in a logical order using a keyboard:

<table><td width="400"><video src="https://user-images.githubusercontent.com/26493779/108219710-44b7c900-7136-11eb-8fa3-f3468c46ff85.mp4"></video></td></table>

This is problematic for keyboard-only users and relates to <span title="Web Content Accessibility Guidelines">WCAG 2.1</span> Success Criterion [2.4.3 Focus Order](https://www.w3.org/TR/WCAG21/#focus-order) and [1.3.2 Meaningful Sequence](https://www.w3.org/TR/WCAG21/#meaningful-sequence).

Can the attribution be placed after the `<button>` attribution control in the DOM order?

Additionally, it'd be great if the [state](https://www.w3.org/TR/WCAG21/#dfn-states) was exposed to users of assistive technology via [`aria-expanded="(true|false)"`](https://www.w3.org/TR/wai-aria-1.1/#aria-expanded) on `<button>`.

**Comment by adamcheasley** [comment]
+1

Esp. the aria-expanded/state issue.

**Comment by MoonE** [comment]
I added a PR that should solve this in #12315, please have a look if it is ok
