### ISSUE TITLE
Loading CDN resource responds with a 403 response.

### ISSUE THREAD

**Issue by Wokiri** [openlayers/openlayers#12045]
**The Issue**
The quick start tutorial in this [link](https://openlayers.org/en/latest/doc/quickstart.html) does not render the map.

**To Reproduce**
1. Visit https://openlayers.org/en/latest/doc/quickstart.html
2. Follow the instructions outlined in the tutorial
3. The console logs these results:
  GET https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.5.0/build/ol.js net::ERR_ABORTED

 Uncaught ReferenceError: ol is not defined

**Expected behavior**
Would we have the right script link resolved? Or am I missing something?

**Comment by M393** [comment]
This is the error message when you open the link in the browser:
```
Package size exceeded the configured limit of 50 MB. Try https://github.com/openlayers/openlayers.github.io/tree/master/en/v6.5.0/build/ol.js instead.
```

**Comment by mike-000** [comment]
It seems to be a jsdelivr problem.  The link is correct and there are other sites such as https://labs.os.uk/public/openspace-migration/examples/basic-map which have used the same link and are currently not working.  https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/latest/build/ol.js which is also v6.5.0 is working, as are all other versions.

**Comment by mike-000** [comment]
The v6.5.0 link is working again now

**Comment by Wokiri** [comment]
I guess the golden advice "For production, we strongly recommend bundling the application together with its dependencies" is worth our all-time consideration. Thanks, I hope the online cdn get resolved.

**Comment by sanathkatakam** [comment]
> The v6.5.0 link is working again now

It's working for only few, it's working for me but when I check on my colleague's machine it's not working

**Comment by ahocevar** [comment]
As stated in the [Quickstart](https://openlayers.org/en/latest/doc/quickstart.html), using ol.js from cdn is not meant to be used in production. Please consider using a bundler, like shown in the code snippets in all our [examples](https://openlayers.org/en/latest/examples), or at least copy ol.js and ol.css to your server.

Outages and bugs on the cdn are not something we can change.
