### ISSUE TITLE
 crossOrigin: 'anonymous' Not working of OSM

### ISSUE THREAD

**Issue by suman111sanjel** [openlayers/openlayers#12044]
Dear ol team,

OSMLayer = new ol.layer.Tile({
        id: "osm",
        title: "Open Street Map",
        visible: true,
        opacity: 0.7,
        source: new ol.source.OSM({
            crossOrigin: 'anonymous'
        }),
    });

when i have to work on pixel level source should have on  crossOrigin: 'anonymous'
This is not working for ol 6.5.0 but works for ol 4.6.5

Thank You
Suman Sanjel

**Comment by mike-000** [comment]
The default is `anonymous`.  Do you have other layers?  If so you should set a unique `className` on the layer where you wish to access pixel data so it has a separate untainted canvas.
