### ISSUE TITLE
Examples need updates?

### ISSUE THREAD

**Issue by rowild** [openlayers/openlayers#12050]
I would like to repot to observations, not knowing if this is the proper place to do so not if it is welcome at all.

1. This example:
https://openlayers.org/en/latest/doc/tutorials/raster-reprojection.html

seems to need an update, since the linked website's address changed to
https://www.planet.com/markets/federal/

Unfortunately I couldn't get `https://demo.planet.com/geoserver/wms` to work, so I cannot provide a PR. Don't know what to do, hope you will come up with a solution... :-)

2. This example:
https://openlayers.org/en/latest/examples/reprojection.html

does project certain constraint to other areas then just the intended one, as well. I included screenshots, which show that under certain circumstances the "British excerpt" is also projected on Russia and Alaska, in a very distorted manner.
Don't know if this is of any relevance...

Thank you!
![Screen Shot 2021-02-19 at 14 22 01](https://user-images.githubusercontent.com/213803/108510462-d7836f80-72be-11eb-87d9-94c3c3a206fd.png)
![Screen Shot 2021-02-19 at 14 23 25](https://user-images.githubusercontent.com/213803/108510476-dc482380-72be-11eb-92d9-469790e87aac.png)

**Comment by mike-000** [comment]
It is the same as the WMS basemap used in https://openlayers.org/en/latest/examples/reprojection.html

**Comment by rowild** [comment]
@mike-000 Thank you, mike, or your response! I updated my "question" while you answered... Can you have a quick look again, please? Thank you!

**Comment by rowild** [comment]
Actually, the "multiple display" problem is addressed in that very article. Sorry for bothering!

**Comment by mike-000** [comment]
In the example the code only sets the bng layer extent when the view is using a global projection (in this case EPSG:3857 and EPSG:4326) where the transform would be valid.  Transforming between projections which do not cover the same area is likely to cause errors.
