### ISSUE TITLE
getFeatures returns error when the layer is added but not yet rendered

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#12065]
**Describe the bug**
Calling getFeatures on a `ol/layer/VectorTile` that is not yet rendered but visible throws an error because this.renderer_ is not yet set.
https://github.com/openlayers/openlayers/blob/b6e7d617b5860aba7dd4dc8835085c415c64d731/src/ol/layer/Layer.js#L212-L214
This likely also happens with `ol/layer/Vector`.

**To Reproduce**
1. Go to https://codesandbox.io/s/getfeatures-error-after-load-qs14b?file=/main.js
2. After page is loaded move the mouse over the map until the layer is added
3. When the layer is added 3 seconds later you get an error

**Expected behavior**
There should be no error, it should always return a Promise.

**Comment by ahocevar** [comment]
Thanks for reporting this. Would you be able to provide a fix? Thanks!
