### ISSUE TITLE
Snap interation  option edge:false does not work on a ploygon

### ISSUE THREAD

**Issue by from-zero** [openlayers/openlayers#12067]
Snap interation  option edge:false does not work

I want to only snap vertices, but the option edge=false does not work
This is my code
```
   this.snap = new Snap({
        source: this.elevatorSource,
        edge:false
    });
```
I find a demo in #5081,but I cant open it.
Demo: http://jsfiddle.net/_DR_/vjxzyqx5/

**Expected behavior**
 only snap vertices, not edges，what should I do?  T_T
![image](https://user-images.githubusercontent.com/9105685/109093487-64ad4500-7753-11eb-972e-d9bbbf3889fc.png)
![image](https://user-images.githubusercontent.com/9105685/109093621-a0480f00-7753-11eb-825c-428ff9b3be09.png)

**Comment by ahocevar** [comment]
This is not done by the Snap interaction, but the Modify interaction. Configure the Modify interaction with
```js
  insertVertexCondition: () => false
```

**Comment by from-zero** [comment]
> This is not done by the Snap interaction, but the Modify interaction. Configure the Modify interaction with
> 
> ```js
>   insertVertexCondition: () => false
> ```

 (✪ω✪) Thank you ! It's work.
