### ISSUE TITLE
Example wmts-hidpi: WMTS Capabilities Fail

### ISSUE THREAD

**Issue by hweri69** [openlayers/openlayers#12069]
**Describe the bug*
retrieving WMTSCapabilities from https://www.basemap.at/wmts/1.0.0/WMTSCapabilities.xml  fails due to change on basemap.at

Use 
https://basemap.at/wmts/1.0.0/WMTSCapabilities.xml 
or
https://maps.wien.gv.at/basemap/1.0.0/WMTSCapabilities.xml
instead

**Comment by M393** [comment]
Thanks for reporting, it is already fixed for the next version by #12058
