### ISSUE TITLE
target div height is different to canvas height

### ISSUE THREAD

**Issue by Virgil-N** [openlayers/openlayers#12063]
**Describe the bug**
Target div height is different to canvas height. 
After I use updateSize(), they are still different.

**Expected behavior**
Target div height equals to canvas height.

**Comment by mike-000** [comment]
Canvas dimensions depend on pixel ratios and are related to the target div dimensions by the transform matrix

![image](https://user-images.githubusercontent.com/49240900/108983769-1c285580-7687-11eb-8473-7078a50e7d26.png)
They can also exceed the target div when the view is rotated.

**Comment by Virgil-N** [comment]
> Canvas dimensions depend on pixel ratios and are related to the target div dimensions by the transform matrix
> 
> ![image](https://user-images.githubusercontent.com/49240900/108983769-1c285580-7687-11eb-8473-7078a50e7d26.png)
> They can also exceed the target div when the view is rotated.
> 
> 

I set the target attribute to #map in new Map function. But the element with id equals to 'map' is bigger than the canvas inner. UpdateSize can't fix it.

**Comment by Virgil-N** [comment]
When I increase the height of map wrap element , the height of canvas is not changed.
My code is here:
```
mapRef.current = new Map({
      target: 'map',
      layers: [
        new TileLayer({
          source: new OSM()
        })
      ],
      view: new View({
        center: [0, 0],
        zoom: 0
      }),
      size: [mapWidth, mapHeight]
    })
```
And updateSize() does not work.

**Comment by ahocevar** [comment]
Remove the `size` option from the `Map` constructor.

**Comment by Virgil-N** [comment]
> Remove the `size` option from the `Map` constructor.

Still not work.
