### ISSUE TITLE
Add "exports" field in package.json for consumers to transpile code

### ISSUE THREAD

**Issue by ireneyiu** [openlayers/openlayers#12060]
**Is your feature request related to a problem? Please describe.**

OpenLayers currently ships modern code (that is, above ES5) and leaves the transpilation for the consumer to handle. Shipping modern Javascript is the paved way forward, as this allows the package to be more performant with less bloated code. However, on the consumer side, if transpilation is necessary (and in my case, yes), it requires a few configs changes (jest, babel, etc.) that are invasive and potentially risky. 

**Describe the solution you'd like**

One solution is to take advantage of Node’s new [exports](https://web.dev/publish-modern-javascript/#modern-javascript-on-npm) field in the `package.json`. Modules referenced by the "exports" field imply a Node version of at least 12.8, which supports ES2019. This means that any module referenced using the "exports" field can be written in modern JavaScript. Package consumers must assume modules with an "exports" field contain modern code and transpile if necessary.

The package consumer code can then indicate that the package should be transpiled by a bundler config (e.g. webpack) like this:

```js
// webpack.config.js
module.exports = {
  module: {
    rules: [
      // Transpile for your own first-party code:
      {
        test: /\.js$/i,
        loader: 'babel-loader',
        exclude: /node_modules/,
      },
      // Transpile modern dependencies:
      {
        test: /\.js$/i,
        include(file) {
          let dir = file.match(/^.*[/\\]node_modules[/\\](@.*?[/\\])?.*?[/\\]/);
          try {
            return dir && !!require(dir[0] + 'package.json').exports;
          } catch (e) {}
        },
        use: {
          loader: 'babel-loader',
          options: {
            babelrc: false,
            configFile: false,
            presets: ['@babel/preset-env'],
          },
        },
      },
    ],
  },
};
```

More details here:
https://web.dev/publish-modern-javascript/

Is this something OpenLayers could update to use?

**Comment by ahocevar** [comment]
Thanks @ireneyiu for sharing this!

Actually the ol package contains transpiled code (ES5, see https://github.com/openlayers/openlayers/blob/main/config/tsconfig-build.json#L4), but as ES modules.

Ideally, we'd ship ES6 code throughout, so what you proposed is definitely the way forward!

**Comment by ahocevar** [comment]
In the scenario you describe, I don't think checking for an "exports" field in package.json will be the right way to determine packages you need to run through `babel-loader`. However, there is a neat solution for that. You can use the [are-you-es5](https://www.npmjs.com/package/are-you-es5) package.
