### ISSUE TITLE
About loading the arcgis tile map, the map is distorted 

### ISSUE THREAD

**Issue by wfxvyps** [openlayers/openlayers#12070]
**Describe the bug**
 Recently, when I use openlayers6.4.3 to load the tile map, I found that when loading the arcgis tile map, the map will be distorted. The actual picture displayed on the page is obviously blurred than the picture in the network request. I roughly measured the size and found The pictures on the page are stretched, which makes the overall display of the page blurry .
At the same time, I also found a similar problem in the openlayers official website example (https://openlayers.org/en/latest/examples/arcgis-tiled.html) 

**Expected behavior**
Is there any way to solve the above problem

**Comment by ahocevar** [comment]
This is simply a matter of projection. If you configure the OpenLayers view to use the same projection that you use in ArcGIS, the map will look the same.
