### ISSUE TITLE
Cluster doesn't respect minimum distance

### ISSUE THREAD

**Issue by stephankn** [openlayers/openlayers#12078]
**Describe the bug**
Features are closer together than specified minimum distance.
Version 6.5.0

**To Reproduce**
Open Cluster example from documentation, potentially zoom in/out or slightly adjust distance to see overlap:
https://openlayers.org/en/v6.5.0/examples/cluster.html

Features have a radius of 10 pixels. Distance is at 40 pixels. Still some features overlap:
![image](https://user-images.githubusercontent.com/251140/109554753-ecd57680-7ad4-11eb-95a7-faa1d55e10b3.png)

**Expected behavior**
My expectation would be that the centers of the clusters are at minimum `distance` pixels apart, as stated in the documentation:
https://openlayers.org/en/v6.5.0/apidoc/module-ol_source_Cluster-Cluster.html

**Comment by MoonE** [comment]
This is due to the algorithm used for clustering, you can find a more detailed explanation in https://github.com/openlayers/openlayers/issues/10530#issuecomment-574406725

**Comment by stephankn** [comment]
Thanks for confirming the bug. Is it planned to repair the clustering algorithm?

Can you expose the "center interpolation" tunable?

If not, the documentation is broken and needs adjustment, clarifying that the "minimum distance" is no minimum distance.
If I understand the current implementation description correctly, I can never guarantee that cluster icons do not overlap, regardless how high the distance setting is set.

**Comment by MoonE** [comment]
A minimum distance is indeed not guaranteed. Depending on feature distribution clusters may more or less overlap.
I am proposing a solution with #12080.
