### ISSUE TITLE
why can't I set projection EPSG:3395 to the view?

### ISSUE THREAD

**Issue by baoxiao1990** [openlayers/openlayers#12085]
Hi, I hava a XYZ tile Layer(url: http://m12.shipxy.com/tile.c?l=Na&m=o&x={x}&y={y}&z={z}) whose projection is **EPSG:3395**, and a point:[121.37167, 30.64],which should be located in the sea,  it's weird that if I set ' **projection: "EPSG:3395"** ' to the view,  this point(which has been translated to **projection 3395**) is located on the land , which is the wrong result. But, if I do not set  ' **projection: "EPSG:3395"** ' to the view, and also remove the XYZ tile layer's projection(**3395**), then the point is located at the right position(in the sea).  Can anybody tell me why?

**Comment by mike-000** [comment]
An EPSG:3395 tile source is working for me https://codesandbox.io/s/epsg3395-qm1rc  It is good practice to explicitly set the extent even though (in projection units) EPSG:3395 should be the same as EPSG:3857.

**Comment by baoxiao1990** [comment]
Thank you very much, Mike, that really matters! But, why  your extent is not the same as [-20026376.39, -15496570.74
20026376.39, 18764656.23], I found this extent from  'https://epsg.io/3395', wheras your extent is [-20037508.342789244, -20037508.342789244, 20037508.342789244, 20037508.342789244]

**Comment by ahocevar** [comment]
Caution @baoxiao1990! Although the projection's extent (`projection.setExtent()`) is used as fallback for tile sources to create the tile grid, it is not the primary purpose of the projection extent to define a tile grid. A properly configured tile source contains a `tileGrid` configuration, which contains information to be obtained from the tile source provider.

The projection extent in projected coordinates as shown on https://epsg.io/3395 is wrong. It is better to use the WGS84 extent, which is also listed there, and use that as projection extent. For the tile grid, @mike-000's assumption was correct, but in practice that information should come from the tile source provider.

I updated @mike-000's sandbox to show what I mean, and I also added a TileDebug source so you can see the tile grid: https://codesandbox.io/s/epsg3395-forked-3705x.

To summarize projection and tile source setup for custom projections:
* Set the projection extent from the validity extent of the projection, as defined in WGS84:
   ```js
   const extent = transformExtent([-180, -80, 180, 84], "EPSG:4326", proj3395);
   proj3395.setExtent(extent);
   ```
* For the tile source, obtain information from the tile source provider, and configure the source with the correct tile grid. Even if you don't have that information, configure the source with a `tileGrid`. For Mercator, a good **guess** is a square extent based on half of the circumference of the earth at the equator in each cardinal direction from `[0, 0]`, even though the poles cannot be shown in Mercator:
   ```js
   const half = extent[2];
   const source = new XYZ({
     url: "https://m12.shipxy.com/tile.c?l=Na&m=o&x={x}&y={y}&z={z}",
     projection: proj3395,
     tileGrid: createXYZ({
       extent: [-half, -half, half, half]
     })
   });
   ```

**Comment by baoxiao1990** [comment]
Thank you very much ,  it's till now that I realized the importance of the  **tileGrid**  property! Thank you again for taking time analysing that puzzle! @ahocevar
