### ISSUE TITLE
Add iterator to Collection class

### ISSUE THREAD

**Issue by sebakerckhof** [openlayers/openlayers#12081]
**Is your feature request related to a problem? Please describe.**
The collection class is a wrapper around an array. However, while the forEach method is implemented, other ways of iterating (for...of, spread operator, etc). are not. For those you always need to first call getArray(), which can lead to a bit of a confusing API (since you get an array that is mutable, but which you should not mutate) etc.

**Describe the solution you'd like**
I think it would be a nice simple addition to add an iterator on the collection, which could be as simple as:
`[Symbol.iterator]() { return this.getArray().values() }`

I'm willing to provide a PR if this is acceptable.

**Comment by mike-000** [comment]
I think this is a bit like having a `getFeaturesIntersectingExtent` method in
https://github.com/openlayers/openlayers/issues/9647#issuecomment-499076061, maybe a nice-to-have but if anyone really needs it it is very easy to add in the application as in https://codesandbox.io/s/layer-clipping-vector-forked-s2owq  If included in the library `Array.prototype.values` and `Symbol.iterator` would need to be added to the list of polyfills needed by older browsers.

**Comment by sebakerckhof** [comment]
fair enough

**Comment by ahocevar** [comment]
In the medium term, we’ll probably be getting rid of `ol/Collection` and use `Set` instead, which could also be listened to using `Proxy`. That said, I think for now it is easy enough to follow @mike-000’s advice.
