### ISSUE TITLE
Broken url/description in docs (ImageArcGISRest)

### ISSUE THREAD

**Issue by dbretschneider** [openlayers/openlayers#12087]
**Describe the bug**
There is a broken url/description in the documentation v6.5.0 of [ImageArcGISRest](https://openlayers.org/en/latest/apidoc/module-ol_source_ImageArcGISRest-ImageArcGISRest.html)

![ImageArcGISRest-broken-link](https://user-images.githubusercontent.com/3016561/110154330-6d052000-7de4-11eb-960f-463f03a909f4.PNG)

**Comment by marcjansen** [comment]
Fixed with #12088
