### ISSUE TITLE
Document Option to style Features for Accessibility on OpenLayers

### ISSUE THREAD

**Issue by stefan123t** [openlayers/openlayers#12100]
**Is your feature request related to a problem? Please describe.**
We are providing a map service with POIs / Features that should be made accessible.
Currently the only content on OpenLayers that is accessible are the controls (+/- up/down/left/right) and the items in the overlaycontainer, ie. scale and attribution.

**Describe the solution you'd like**
Expectation from our accessibility tester would be that we can navigate through the Features using keyboard Tab key to focus all Features consecutively. For this each feature needs to be styled as a Button, Link or something semanticly similar to be accessible.
For that each Feature should be exposed as a separate DOM Element which can be styled and made accessible by specifying the HTML content and/or adding ARIA labels.

I have checked #11678 and #12042 which strive for some improvement regarding the current situation.
I have also checked the Accessible Map Example https://openlayers.org/en/latest/examples/accessible.html. 

In fact the Icon Symbolizer Example is a better startpoint, as it shows a single Feature for Null Island with additional information, i.e. Population and Rainfall. While we can expose the Details for the Feature Population and Rainfall with a custom caroussell on click, we have found no way to reach the icon using keyboard focus and trigger the caroussell code.
https://openlayers.org/en/latest/examples/icon.html

Thanks for providing this valuable Library and listening to our request.

**Comment by ahocevar** [comment]
Since icons are not rendered as DOM elements, there is no direct way to use the keyboard to navigate to them.

However, you can generate accessible content for features, using `ol/Overlay`, i.e. a DOM element positioned on a map using a coordinate. You can use https://openlayers.org/en/latest/examples/overlay.html as starting point.

**Comment by stefan123t** [comment]
@ahocevar thanks for the hint!
Interestingly the link `<a class="overlay" id="vienna" target="_blank" href="http://en.wikipedia.org/wiki/Vienna">Vienna</a>` cannot be focused with the keyboard.
However in the Popup Example https://openlayers.org/en/latest/examples/popup.html I can readily focus the Closer link `<a href="#" id="popup-closer" class="ol-popup-closer"></a>` using the keyboard.
In fact the Overlay/Popups even appear before the zoom in/out controls in my tabindex order, this might be preferred.

**Comment by ahocevar** [comment]
You can modify the example to add a `tabIndex` attribute to the overlay's element. Then you should be able to focus it with the keyboard.

**Comment by stefan123t** [comment]
@ahocevar thanks that seems to work.
We will need to decide whether we come up with a logical numbering for the tabIndex=1..N sequence on the map or if we stick to tabindex=0 and leave it to the semantic ordering in the DOM.

**Comment by Malvoz** [comment]
@stefan123t tabindex greater than 0 is generally [not recommended](https://dequeuniversity.com/rules/axe/4.2/tabindex#:~:text=Why%20it%20Matters), and tools such as Lighthouse will flag these elements: https://web.dev/tabindex/.
