### ISSUE TITLE
Text Style: placement 'line' not considering multi-line strings

### ISSUE THREAD

**Issue by luiscamachopt** [openlayers/openlayers#12101]
**Describe the bug**
Text Style: when placement is set to 'line', multi-line strings are not considered when calculating the width of the text, affecting the chosen location for the label

**To Reproduce**
1. Go to [https://8nlub.csb.app](https://8nlub.csb.app)
2. Notice how the label for the line that is most to the north is not centred. This happens when the text has more than one line - 'Roussel\nRoussel' in the example.

**Expected behavior**
For one line text the label is centred on the best segment. Same would be expected for text with multiple lines.

Problem appears to be in measureAndCacheTextWidth() in canvas.js - it's not considering multi-line text
Calculating the width using the lines in the text seems to fix the issue:
```
    const lines = text.split('\n');
    const width = measureTextWidths(font, lines, []);
```

Can create a PR if you think this seems the right fix.

**Comment by MoonE** [comment]
The text-along-path code does not properly deal with multi-line strings. You can see this when you modify the line to have some curves: 
```js
import Modify from 'ol/interaction/Modify';
map.addInteraction(new Modify({
  source: vectorLines.getSource(),
}));
```
A solution might be to replace any new-line characters with a space instead.

**Comment by luiscamachopt** [comment]
@MoonE Thanks for your reply. I understand it doesn't deal with all situations perfectly but still works for some and I think the proposed change would be an improvement. Additionally, not considering new-line characters when doing the calculations seems to be out-of-sync with the rendering being done.
I've submitted PR #12106

**Comment by luiscamachopt** [comment]
I'd like to keep this open. I submitted a PR that addresses the issue
