### ISSUE TITLE
Builded Project not working

### ISSUE THREAD

**Issue by Paul42812** [openlayers/openlayers#12105]
When opened with `parcel <file>` everything works fine but when opening the using `parcel build <file>` generted index.html with `python3 -m http.server` or uploading it to Github pages doesn't work

**To Reproduce**
Use parcel build

The website is completely white with a black X in the upper left corner

[package.json](https://github.com/openlayers/openlayers/files/6125850/package.json.txt)

**Comment by ahocevar** [comment]
Try to delete the `dist` and `.parcel-cache` folders before running `parcel build`.

**Comment by Paul42812** [comment]
Still the same error, the javascript console outputs:
`Uncaught TypeError: e is not a function<anonymous> prelude.js:1<anonymous> main.ts:72prelude.js:1:35`

**Comment by ahocevar** [comment]
Looks like a Parcel issue. You may want to report it on https://github.com/parcel-bundler/parcel/issues/.
