### ISSUE TITLE
Ignore empty gx:coord elements in KML files

### ISSUE THREAD

**Issue by voegelas** [openlayers/openlayers#12113]
**Describe the bug**
The [KML specification](https://developers.google.com/kml/documentation/kmlreference#gxtrack) allows empty gx:coord elements. [OpenTracks](https://github.com/OpenTracksApp/OpenTracks) has started to use such elements.
OpenLayers does not parse empty gx:coord elements and inserts 0 coordinates instead. If a track is rendered connections to the Null Island in the Atlantic Ocean are drawn.

I've got [a commit](https://github.com/voegelas/openlayers/commit/258d558d13544b0e1ca9c28195c3c86e495bce1d) that changes the parser in [src/ol/format/KML.js](https://github.com/openlayers/openlayers/blob/2ad578979747bc3eacaaf577eb05b65679de7fdd/src/ol/format/KML.js#L1530) and at the same time fixes another bug:
In readGxTrack() the function call `Math.min(flatCoordinates.length, whens.length)` should currently be `Math.min(flatCoordinates.length / 4, whens.length)`.

**To Reproduce**
1. Download [opentracks.zip](https://github.com/openlayers/openlayers/files/6142671/opentracks.zip), which contains three files: opentracks.kml, opentracks.html and opentracks.js
2. Unzip the archive in the root directory of a web server.
3. Put ol.css and ol.js into the directory. 
4. Open opentracks.html in a web browser.
5. See the connections to the Null Island.

**Expected behavior**
Empty gx:coord elements are ignored. No connections to the Null Island are drawn.

I would like to open a pull request.

**Comment by voegelas** [comment]
I would like to open a pull request that fixes the KML parser.

**Comment by ahocevar** [comment]
Thanks for willing to fix this. Please provide a pull request!
