### ISSUE TITLE
Can't call removeLastPoint after using appendCoordinates to reopen a polygon

### ISSUE THREAD

**Issue by zac-robinson** [openlayers/openlayers#12118]
**Describe the bug**
After calling appendCoordinates on DrawInteraction, if you then try to call removeLastPoint on the newly opened geometry, openlayers errors to the console.

**To Reproduce**
1. Go to https://codesandbox.io/s/agitated-snyder-glhwb?file=/main.js
2. Draw a polygon
3. Press any key to reopen that polygon
4. Press any key again once it is opened
5. Get the error: `Cannot read property 'setGeometry' of null`

**Expected behavior**
The last point is removed the same as if you were calling removeLastPoint whilst initially drawing the polygon

**Comment by blissvisitor** [comment]
I have the same question! I found that where call appendCoordinates  It dispatch modifyDrawing_  function but not the function createOrUpdateSketchPoint 
<img width="483" alt="image" src="https://user-images.githubusercontent.com/16833909/125248660-e2e73e00-e326-11eb-8270-5b2a9fc1c8e4.png">
that make sketchPoint_ is null. 
when I call removeLastPoint ,the sketchPoint_ is null don't have setGeometry method 
<img width="493" alt="image" src="https://user-images.githubusercontent.com/16833909/125248769-0f02bf00-e327-11eb-9348-b5d050d811a9.png">

**Comment by ahocevar** [comment]
I cannot reproduce the originally reported issue with the latest version any more, and I think what @blissvisitor reports is an unrelated issue.

**Comment by blissvisitor** [comment]
No No No I still have the same question

**Comment by ahocevar** [comment]
@blissvisitor Can you share runnable code that helps reproduce the problem? I cannot reproduce the problem with the code shared by @zac-robinson.

**Comment by zac-robinson** [comment]
@ahocevar I have still managed to reproduce it in the code sandbox I shared. A repro step I missed was that after drawing the feature you shouldn't move the mouse. If the mouse is moved after the polygon is opened it draws the "sketch line", and no longer crashes. If you reopen the polygon and then press again to remove last point without moving mouse it should crash.
