### ISSUE TITLE
Icon styles with displacement get clipped

### ISSUE THREAD

**Issue by ludvigeriksson** [openlayers/openlayers#12123]
**Describe the bug**
When using an icon style (`ol/style/Icon`) with `displacement` set, the icon gets clipped.

**To Reproduce**
1. Go to https://codesandbox.io/s/regularshape-forked-7vzx5. This is a fork of your example [Regular Shapes](https://openlayers.org/en/latest/examples/regularshape.html)
2. See that the green cross icon is clipped.
3. Check lines 74-101. The only change I've made to the example is adding an image and replacing the displaced style with an icon style.

**Expected behavior**
I expect the green cross to not get clipped, just like the regular shape in the original example.

**Comment by bridgeToVillage** [comment]
i have the same problem
