### ISSUE TITLE
Cannot get the coordinate of MapBrowserEvent

### ISSUE THREAD

**Issue by endeep** [openlayers/openlayers#12122]
In version 6.5.0,  After instantiating the map，I add the click event, but cannot get the coordinate of MapBrowserEvent in the callback function

1. let map = new Map()
2. map.on("click",(e) => {  let coordinate = e.coordinate})
3. coordinate  is null

I compared the previous version， find that coordiante enumerable is different when MapBrowserEvent from ES6 to ES5。
```
 // @6.5.0
 Object.defineProperty(MapBrowserEvent.prototype, "pixel", {
        /**
         * The map pixel relative to the viewport corresponding to the original event.
         * @type {import("./pixel.js").Pixel}
         * @api
         */
        get: function () {
            if (!this.pixel_) {
                this.pixel_ = this.map.getEventPixel(this.originalEvent);
            }
            return this.pixel_;
        },
        set: function (pixel) {
            this.pixel_ = pixel;
        },
        enumerable: false,
        configurable: true
    });
```
```
 // @6.1.0
 Object.defineProperty(MapBrowserEvent.prototype, "pixel", {
        /**
         * The map pixel relative to the viewport corresponding to the original event.
         * @type {import("./pixel.js").Pixel}
         * @api
         */
        get: function () {
            if (!this.pixel_) {
                this.pixel_ = this.map.getEventPixel(this.originalEvent);
            }
            return this.pixel_;
        },
        set: function (pixel) {
            this.pixel_ = pixel;
        },
        enumerable: true,
        configurable: true
    });
```

**Comment by ahocevar** [comment]
The code you pasted is the transpiled code from the package - the source has not changed here. But the change you're seeing there should not make a difference (note: you pasted `pixel`, but I think it's the same for `coordinate`).

What were you trying to do with the coordinate? The following minimal code works:
```js
map.on('click', e => alert(e.coordinate));
```
See https://codesandbox.io/s/simple-forked-rx5wk?file=/main.js for a live example with that code.
