### ISSUE TITLE
VectorTile labels in wrong position in version 6.5.0

### ISSUE THREAD

**Issue by digoburigo** [openlayers/openlayers#12124]
**Describe the bug**
When upgrading to version `6.5.0` the labels of a layer of type `VectorTile` are in the wrong position

OpenLayers Version `6.4.3`
![version 6 4 3](https://user-images.githubusercontent.com/28462822/111788344-be121b00-889e-11eb-9a5c-62c5f863dba9.png)

OpenLayers Version `6.5.0`
![version 6 5 0](https://user-images.githubusercontent.com/28462822/111788435-d5e99f00-889e-11eb-8cfe-c121188e67cf.png)

**Expected behavior**
I would expect the labels to be in the same position of the version `6.4.3` since there were no changes in the code, just the upgrade of the `ol` package

**Comment by ahocevar** [comment]
This should have been fixed since 6.5.0. Can you try to `npm install ol@dev`?

**Comment by digoburigo** [comment]
With version `6.5.1-dev.1616040467861` another error occurs and the layers do not load properly when zooming

![image](https://user-images.githubusercontent.com/28462822/111794760-51e6e580-88a5-11eb-9687-e60fe9b41498.png)

**Comment by digoburigo** [comment]
Yes, that was the problem, sorry for this, I didn't notice that `renderMode: 'image'` was removed. My mistake, thanks for the heads up!
