### ISSUE TITLE
DuckDuckGo Site Privacy Protection seems to affect point selection

### ISSUE THREAD

**Issue by hutch120** [openlayers/openlayers#12121]
Hi All,

Running Openlayers version 6.5.0

I traced an issue with clicking/selecting a feature back to some conflict with the popular Google Chrome extension [DuckDuckGo Privacy Essentials](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg)  (DDGPE)

When DDGPE is enabled I see the issue below, when disabled the issue goes away. Also, the code works perfectly in FF/IE/Incognito Chrome. 

The issue is when clicking a feature the selected feature is not the one under the mouse, but a nearby feature! Kind of like DDGPE is somehow offsetting the returned click position maybe. If I zoom right in, it selects the correct point.

I was able to trace it back into OpenLayers as far as the style function in this is being passed the wrong feature.

This is a strange one, it doesn't seem to affect the [select demo](https://openlayers.org/en/latest/examples/select-features.html) so I will try to see if I can get some cut down code to reproduce, but at the moment the code is buried deep in a React site.

In `ol/renderer/canvas/VectorLayer.js:550`  When styleFunction is called for the selected feature, it's not the feature that was clicked! So it highlights another nearby feature!

```
    function (feature) {
      var styles;
      var styleFunction = feature.getStyleFunction() || vectorLayer.getStyleFunction();

      if (styleFunction) {
        styles = styleFunction(feature, resolution);
      }
```

![image](https://user-images.githubusercontent.com/1034955/111616013-7e631900-8835-11eb-8a27-00759db96154.png)

I disabled SPP on live sites, and I also had to add localhost via the DDG extension settings (click cog) to the excluded sites to get it work in my development environment.

![image](https://user-images.githubusercontent.com/1034955/111616238-c5510e80-8835-11eb-8fdf-77cec47b188f.png)

**Comment by ahocevar** [comment]
This can happen with browser plugins like the one you are using. Better to report the issue there. Maybe a CSS filter gone wild.
