### ISSUE TITLE
Points flicker with no reason?

### ISSUE THREAD

**Issue by lotrmj** [openlayers/openlayers#12126]
Hi, guys!
Please look at this gif: https://gifyu.com/image/fhGB

I have a VectorLayer layer, its' features are in EPSG:3346 projection. Decluttering is turned off.
Issue is nonexistent in larger scales (when only few features are visible on the map), but it exists in smaller scales. Sometimes features flicker for a couple of seconds and then they stop. Sometimes they flicker as long as they want. As you see the map is in static position, I am not touching it :)
Sadly I don't have much time to dig deeper atm and the situation needs to be fixed quite quickly..
Any ideas what is going on here?

OL v6.5.0, by the way

Edit:
The sources of icons are not static .png files, they are generated like that -> "data:" + uniqueValueInfo.symbol.contentType + ";base64," + uniqueValueInfo.symbol.imageData

**Comment by jahow** [comment]
This might be related to feature styles. Could you please share a minimal reproduction case so that this can be investigated further? Thanks

**Comment by lotrmj** [comment]
Thank you for reply! It was hard for me to create a minimal reproduction case... The problem was I cloned too much styles I guess... I solved the problem by avoiding cloning styles :)
