### ISSUE TITLE
getResolutionForExtent returns Infinity on version 6.5.0

### ISSUE THREAD

**Issue by Ruahonen** [openlayers/openlayers#12132]
ol/View~View has method getResolutionForExtent, on version 6.0.1 getResolutionForExtent has returned the right resolution. But on version 6.5.0 it turns to return Infinity.

OL view (EPSG:3067), this view might have typos cause I edited it from ClojureScript -> JS:

```
new View({
  center: [427000, 6770000],
  zoom: 4,
  maxZoom: 15,
  projection: new Projection({
     code: "EPSG:3067",
     extent: [-548576, 6291456, 1548576, 8388608]
     units: "m"
  }),
  extent: [-548576, 6291456, 1548576, 8388608]
});
```
  
  Method getResolutionForExtent with given extent:
  [488330.982196557, 6869218.41867572, 489181.475883952, 6869233.20987028]
  , should return resolution as number.

**Comment by ahocevar** [comment]
Apart from possible ClojureScript transcript errors (missing commas in arrays), you have a projection specified using an object literal, which is not supported. You need to provide an `ol/Projection` instance or a string. If the latter, a projection with the SRS code passed as string must be registered.

**Comment by Ruahonen** [comment]
@ahocevar thank you for the notify! Unfortunately that was my typo, I added the Projection on the example.

**Comment by ahocevar** [comment]
Working on 6.5.0 too:
```js
import View from "ol/View";
import Projection from "ol/proj/Projection";

const view = new View({
  center: [427000, 6770000],
  zoom: 4,
  maxZoom: 15,
  projection: new Projection({
    code: "EPSG:3067",
    extent: [-548576, 6291456, 1548576, 8388608],
    units: "m"
  }),
  extent: [-548576, 6291456, 1548576, 8388608]
});

const resolution = view.getResolutionForExtent([
  488330.982196557,
  6869218.41867572,
  489181.475883952,
  6869233.20987028
]);
console.log(resolution);
```
yields `8.504936873950065`. See https://codesandbox.io/s/goofy-rain-n92o3 for a working example.

**Comment by Ruahonen** [comment]
Thank you @ahocevar for the example! My problem was in ol/map viewport, maps viewport was [800, 0]. And 0 is not good :)
