### ISSUE TITLE
Failed to get the extent of VectorSource inside the featuresloadend callback function

### ISSUE THREAD

**Issue by kikitte** [openlayers/openlayers#12138]
**Describe the bug**
Try to get the extent of VectorSource but the result is [Infinity,Infinity,-Infinity,-Infinity] which is incorrect. 
And I think we should add features before calling the success callback in the xhr function in src/ol/featureloader.js.

![image](https://user-images.githubusercontent.com/23274684/112334526-76541f00-8cf6-11eb-8ce5-553c8846d286.png)

**To Reproduce**
1. Go to https://codesandbox.io/s/kml-pjrvw?file=/main.js

**Expected behavior**
VectorSource.getExtent() returns the correct extent when featuresloadend event is triggered.

**Comment by ahocevar** [comment]
Thanks for reporting this, @kikitte. You are right, the success callback should be called after the features are added. Would you be able to create a pull request? Thanks in advance.

**Comment by liuvigongzuoshi** [comment]
@kikitte 
I also encountered this problem, you can try this.
```js
 Promise.resolve().then(vector.getSource().getExtent())
```
It works for me.
