### ISSUE TITLE
Laggy pan-performance with multiple tile layers (Desktop Firefox) 

### ISSUE THREAD

**Issue by Swiod** [openlayers/openlayers#12134]
The ability to interact (at least via panning, but you would probably see it too while zooming) with the map smoothly decreases a lot on Firefox Desktop under following circumstances:
  * more than one TileLayer exists with following configurations:
    * with default OL classNames!
    * with caching enabled (e.g. cacheSize 2048)
    * (with transition disabled - might not be required)
  * low-resolution tiles exist (that will be used for prerendering while loading high-resolution tiles)
  * hardware
    * the larger the screen, the worse it gets
    * the less CPU power, the worse it gets

Steps to reproduce the behavior (adapted OL example "arcgis-tiled"):
1. Go to https://codesandbox.io/s/arcgis-tiled-forked-ss1ns?file=/main.js
2. Make it a full page
3. Optional: pan around without any lag issues
4. Click button "Try laggy performance while panning" and wait a sec
5. Pan around trying to stick to newly high zoom level rendered tiles to see responsiveness drop (you might need a larger screen to actually feel responsiveness drop hard enough)

General steps to reproduce the behavior:
1. (provide two TileLayers configured like described above)
2. start from a low zoom level e.g. 4
3. go to a high zoom level e.g. 14 (you should see blurry tiles from zoom level 4)
4. pan around quite fast but try to stick around newly high zoom level rendered tiles to see responsiveness drop (if your viewport only renders the low-resolution tiles, responsiveness remains well)

Details on investigations up to now:
  * no laggy performance on Chrome Desktop
  * OpenLayers Version 6 seemed to introduce the issue, try the example above with Version 5.3.3.
  * it looks like it has something to do with CanvasRenderingContext2D.clip()
    * it seems that Firefox does perform a lot worse than Chrome
    * bypassing clipping does "fix" the laggy performance
      * maybe there is a nice way to bypass clipping?
      * or to disable pre-rendering of blurred low-resolution tiles at all via an layer option (though I would appreciate to have not to)
  * giving separate classNames for each TileLayer seems to solve the issue too, but that would mean memory consumption would increase a lot (HIDPI!) for each added TileLayer

Expected behavior:
  * the map should stay responsive no matter if there are any pre-rendered low-resolution tiles or not

**Comment by sbrunner** [comment]
Probably liked issue: https://github.com/openlayers/openlayers/issues/11929

**Comment by Flujible** [comment]
I am working on an app that uses OL4 and we experience this on FF too. When I first tried it I was on version eighty-something of FF and it was working fine for me, as soon as I upgraded to v92 (jumped straight to 92 from where I was, no versions in-between) is when I started to get these issues, so I think it could be a change in Firefox that may have exposed this issue

**Comment by BHDBvde** [comment]
Same issue here, also with zooming.

**Comment by bmanojlovic** [comment]
i have OSM and 4 more XYZ layers and performance on firefox is so bad that it becomes almost unusable.

**Comment by ahocevar** [comment]
What about using `ol/layer/WebGLTile` instead? For me, this improves the rendering performance significantly.

**Comment by ahocevar** [comment]
I'm currently working on #13391, which gets rid of the clipping that is likely to be the culprit here.

**Comment by bmanojlovic** [comment]
> What about using `ol/layer/WebGLTile` instead? For me, this improves the rendering performance significantly.

I have used it and it does work a lot faster!
but i have artifact issues which can be seen in video [here](https://map.vet.procss.org/artifacts.mp4) (download file if you can't see online)
and code with just 2 layers that shown behavior (and now with webgl) :

`import "./style.css";
import { Map, View } from "ol";
import TileLayer from "ol/layer/WebGLTile";
import OSM from "ol/source/OSM";
import XYZ from "ol/source/XYZ";

const map = new Map({
  target: "map",
  layers: [
    new TileLayer({
      source: new OSM(),
    }),
    new TileLayer({
      source: new XYZ({
        url: "https://map.vet.procss.org/tiles/svinje/webmercator/{z}/{x}/{y}.png",
        crossOrigin: "anonymous",
      }),
    }),
    new TileLayer({
      source: new XYZ({
        url: "https://map.vet.procss.org/tiles/goveda/webmercator/{z}/{x}/{y}.png",
        crossOrigin: "anonymous",
      }),
    }),
  ],
  view: new View({
    center: [0, 0],
    zoom: 2,
  }),
});
`
