### ISSUE TITLE
Improve geometry operations of openlayers

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#12146]
It would be nice if openlayers had a richer geometric interface. I find that I either have to import turf.js for just one function or rewrite some functionality. Also turf.js always uses WGS84 coordinates which can lead to warped or incorrect positioned geometries.

Some functionality I would like to see would be:
* have a parameter to `intersectsCoordinate` that enables checking for boundaries as well. Alternatively have a function `boundaryIntersectsCoordinate` which might even be better because more cases are covered.
* have a `intersectsGeometry` method.
* have a `getMAtCoordinate` for `LineString` which would be the reverse of `getCoordinateAtM`. Maybe it should be `getMAtClosestCoordinate`.
* being able to use haversine distance for `getCoordinateAtM`.
* clip geometry to extent or polygon.
* slice line string between two points or two distances.

I see that some of these might be tricky in one or the other way, but I wanted to ask if methods like this are wanted in openlayers or if they would push the library a little to far in the direction of geospatial processing. I would like to give some of these a crack.

**Comment by ahocevar** [comment]
We had more geometry operations in OpenLayers 2, and decided to leave those to external libraries when we did the rewrite. Can you add API examples for the functions you'd like to have? In particular, I'm not 100% clear what you mean by "boundary".

Personally, I'm not opposed to add more geometry operations to OpenLayers, but I'd be hesitant to make them methods of Geometry classes. Instead, I'd make them static functions that are passed geometries and work with their flat coordinates. Keeping them separate allows for better build size optimisations. If done that way, they could also be maintained as separate packages, and work with flat coordinates that do not necessarily have to come from OpenLayers geometries.

**Comment by simonseyock** [comment]
With the `intersectsCoordinate` method I was actually misled by the documentation, which states "Returns true if this geometry includes the specified coordinate. If the coordinate is on the boundary of the geometry, returns false."
I Interpreted it that if I check if a point intersects a polygon and it is right on the edge, it would return false.
But it seems, that this is not the case: https://codesandbox.io/s/intersects-coordinate-mrrhf?file=/main.js
So here it would be enough to just update the docs.

For the other methods I will think about what would be nice. I also like the idea to have a separate library, even though I don't know how much I would be able to do here.
