### ISSUE TITLE
VecotTile layers with TopoJSON format clip the style images on Tile borders

### ISSUE THREAD

**Issue by amir-ba** [openlayers/openlayers#12166]
**Describe the bug**
For Vector Tiles with TopoJSON as format the points with a image or/and Text style are clipped on their Tile boundaries. This behaviour only visible on not decluttered layers. 

**To Reproduce**
1. Go to 'https://codesandbox.io/s/osm-vector-tiles-forked-6sikm?file=/main.js'
2. This is fork of the existing OSM VectorTile example and uses the Point layers of the Mapen service.
3. The rendered ImageStyle for the point elements are clipped on the boundary of the Tiles.
4. The Renderer only renders the element correctly if the `declutter` is set to true.

** Analysis Results**
Upon creation of `CanvasExecutorGroup` for the `VectorTileLayer` the decultter is considered for setting the groups maximum extent. Blow is the mentioned section of the code. I would suggest to only check for  the rendereType and the sourceTile length.  Would that be a viable solution? 
> ```js
> // FROM src/ol/renderer/canvas/VectorTileLayer.js  line:347
>      const replayExtent =
>        layer.getRenderMode() !== VectorTileRenderType.VECTOR &&
>        declutter &&
>        sourceTiles.length === 1
>          ? null
>          : sharedExtent;
>      const renderingReplayGroup = new CanvasExecutorGroup(
>        replayExtent,
>        resolution,
>        pixelRatio,
>        source.getOverlaps(),
>        executorGroupInstructions,
>        layer.getRenderBuffer()
>      );
>``
**Expected behavior**
The Features are rendered correctly regardless of their Tile Extent when covered by a single source tile.

**Comment by amir-ba** [comment]
I have created a pull request that removes the `declutter` check.  #12167

**Comment by mike-000** [comment]
The clipping is correct.  The problem is that (unlike most MVT tiles https://docs.mapbox.com/vector-tiles/specification/#encoding-geometry) the tiles have no buffer, which is needed if features close to the edges are to be included in the adjacent tile images

![image](https://user-images.githubusercontent.com/49240900/113158970-27494500-9234-11eb-9da2-016bfcbd02e0.png)

**Comment by ahocevar** [comment]
Like @mike-000 says: this is a problem with the tiles, not with OpenLayers. As you can see when looking at the images of the failed rendering tests in your pull request #12167, clipping at tile boundaries is needed when not decluttering: it avoids duplicate points when they are contained in the tiles on either side of the tile border, which is the case for correctly generated tiles.

Expected (and actual without your change):
![expected](https://user-images.githubusercontent.com/211514/113160330-b27b0880-923d-11eb-96e1-07d818a751ff.png)
Actual (with your change):
![actual](https://user-images.githubusercontent.com/211514/113160407-c4f54200-923d-11eb-82b3-97166fa40c7d.png)
The above image shows a map centered on the intersection of 4 tiles, with a point in each corner of each tile, with tiles buffered so the rendered points are contained in all tiles.

**Comment by amir-ba** [comment]
Thank you @ahocevar and @mike-000  for your clarifications. You are right I didn't  consider the cases where the overlaps are included in multiple tiles. But in the case where the tiles don't share any features, wouldn't it be correct to clip the tiles with the extent created using the `renderbuffer` instead of the tile extent? 
for example in the following example (created from the Test case that was previously failing):
[Sandbox creating a point at a center of each tile](https://codesandbox.io/s/osm-vector-tiles-forked-t985v?file=/main.js)
the tiles are clipped from the Tile Extent. I have commited my suggestion in the same PR .  (builds are failing however :D) 
But would that be a right way to use the `renderBuffer` ?

**Comment by ahocevar** [comment]
With tiles like the ones you have, you should not be using a `VectorTile` layer, but instead a `Vector` layer with a `tile` loading strategy. Vector tiles have a buffer with duplicated features by design. Your layer definition changed from VectorTile to Vector would look like this:
```js
new VectorLayer({
  source: new VectorSource({
    attributions:
      '&copy; OpenStreetMap contributors, Who’s On First, ' +
      'Natural Earth, and openstreetmapdata.com',
    format: new TopoJSON({
      layerName: 'layer',
      layers: ['pois'],
    }),
    strategy: tile(tileGrid),
    maxZoom: 19,
    url(extent, resolution) {
      const [z, x, y] = tileGrid.getTileCoordForCoordAndResolution(
        getCenter(extent),
        resolution
      );
      const url = `https://tile.nextzen.org/tilezen/vector/v1/all/${z}/${x}/${y}.topojson?api_key=${key}`;
      console.log(url);
      return url;
    },
  }),
  style: function (feature, resolution) {
    switch (feature.get('layer')) {
      case 'pois':
        return poisStyle;
      default:
        return null;
    }
  },
})
```

**Comment by ahocevar** [comment]
Actually please disregard my above suggestion - that only works when features have unique ids across resolutions, and are not optimised for resolution.

**Comment by mike-000** [comment]
That code would work if the source was refreshed when the tile grid zoom level changes:

```
const tileGrid = createXYZ({tileSize: 512, maxZoom: 19});
let currentZ;
const source = new VectorSource({
  format: new TopoJSON(),
  strategy: tile(tileGrid),
  url(extent, resolution) {
    const [z, x, y] = tileGrid.getTileCoordForCoordAndResolution(
      getCenter(extent),
      resolution
    );
    if (z !== currentZ) {
      currentZ = z;
      source.refresh();
    }
    return `https://tile.nextzen.org/tilezen/vector/v1/all/${z}/${x}/${y}.topojson?api_key=${key}`;
  },
});

```
However, the benefits of the `VectorTile` tile cache would be lost.

A better solution (based on a question on how to use vector tile features in a cluster source) would be to keep the standard `VectorTile` source while maintaining copies (for each zoom level) of the features to be clustered (or in this case to be displayed across tile boundaries) in a separate `Vector` source https://codesandbox.io/s/osm-vector-tiles-forked-3w46r

**Comment by amir-ba** [comment]
@mike-000 thanks you for the workaround but that  would mean that i won't benefit from the tile-caching that the vector tiles bring. and I have to load everything twice which would be problematic for me since I have a big dataset. I will try to see if I can change my source TopoJson files to include the overlaps. 
But meanwhile I just realized that I have a additional problem with the tile clipping for Text styles, that occurs when I use any projection system other than the default .  
[https://codesandbox.io/s/osm-vector-tiles-forked-t985v?file=/main.js](https://codesandbox.io/s/osm-vector-tiles-forked-t985v?file=/main.js)
As shown in the example the text is clipped on the border lines of the default tilegrid for EPSG:3857 and not the defined projections `defaultTileGrid`.
I believe that's because the VectorTiles keep a reference object of all default TileGrids for different projections. But I think this should check for the `defaultTileGrid` for the projection before creating one from the projection extent. Or is there any other way that i can get the right tilegrid ?

**Comment by mike-000** [comment]
I'm not sure why vector tiles which can only be used in the source projection need a separate TileGridForProjection?  On your example the grid and projection extents are the same, and the issue seems to be related to the multiple tile sizes in your grid, as `getTileGridForProjection` is creating a grid using only the tile size of your grid's level 0.

https://github.com/openlayers/openlayers/blob/71c18d44440e2c8c4dfb2989f78b731dbfb2e522/src/ol/source/VectorTile.js#L481

**Comment by ahocevar** [comment]
For explanation: VectorTile sources have a source tile grid, which is the tile grid you configure with the source, and which you get with `getTileGrid()`. For rendering, the view projection's standard tile grid is used, and that is the tile grid you get with `getTileGridForProjection(viewProjection)`. Reprojection of vector tiles is only supported when tile borders are a rectangle in both source and view projection, e.g. between EPSG:4326 and EPSG:3857. And this is exactly what happens with Mapzen TopoJSON vector tiles.

**Comment by mike-000** [comment]
The TopoJSON vector tiles may have an EPSG:4326 data projection but they are served as tiles based on EPSG:3857 grid.  I agree reprojection would be possible if the source tiles are parallel rectangles in the view projection - and regardless of the data projection used within the tiles as even `MVT({featureClass: feature})` could be read from tile pixels to tilegrid projection and then transformed to view projection - but in practice the source tilegrid must be defined in a projection equivalent to the view projection to avoid assertion 68.  So how does OpenLayers support reprojection?  Without reprojection it might be better to use the real grid.

**Comment by ahocevar** [comment]
You are right @mike-000. With reprojection, I meant that the data is in EPSG:4326. It's not a reprojection as we do for raster layers. The reason for different view and render tile grids is the common case where vector tiles are only provided down to zoom level 14, so they can be rendered on higher zoom levels without getting tile render canvases that are too big. But this discussion belongs elsewhere.

**Comment by amir-ba** [comment]
@mike-000 @ahocevar , thank you for the infos. I understand now why it was working that way. I was able to fix it with having the correct extents.
