### ISSUE TITLE
Stroke style: semi-transparent lines should get darker on overlap

### ISSUE THREAD

**Issue by cedric-versluys** [openlayers/openlayers#12165]
**Describe the bug**
I have a map with linestring features of routes in a `VectorImage`. To be able to see which segments of routes are present a lot, I want to use transparency of the Stroke to make some kind of 'heatmap', meaning: If some segments are overlapping e.g. 20 times, it should be much darker/more opaque than segments that don't have any overlap. I have tried to apply one style to the layer as a whole, or using a style function. Both seem to merge the strokes together (unless they have a different color) with the same 0.4 opacity

**To Reproduce**
- Add a LineString `VectorImage` (or `Vector`, same problem) with overlapping lines.
- Apply transparency to the lines with stroke.color = `'rgba(..,..,..,0.4)'`

**Expected behavior**
Overlapping lines should appear darker than non-overlapping lines

**Comment by ahocevar** [comment]
Before #6981, you would have been able to achieve the desired effect by setting the layer's opacity to `0.05`, and render the lines fully opaque. This is no longer possible.

The optimisation that @mike-000 mentions is that OpenLayers only calls `stroke()` on the canvas when the `strokeStyle` of the canvas changes. This is the relevant code:

https://github.com/openlayers/openlayers/blob/58c973653454942d4542f92650dd393a32d122f5/src/ol/render/canvas/Builder.js#L539-L559

**Comment by cedric-versluys** [comment]
I get how this optimization would be desirable in most cases. However, your workaround works find! Thanks @mike-000 !
