### ISSUE TITLE
updateWhileInteracting Behaviour

### ISSUE THREAD

**Issue by EvertEt** [openlayers/openlayers#12177]
**Describe the bug**
While looking into #12171 I was confused by the behavior of `updateWhileInteracting`.
It seems when it is set to true, there is no change in behaviour, at least not in the way I was testing.

**To Reproduce**
1. Go to the vector-layer example https://openlayers.org/en/latest/examples/vector-layer.html
2. Add `map.getView().beginInteraction()`
3. Set `updateWhileInteracting` to true and the layer is still not drawn.

**Expected behavior**
I expected the layer to be drawn. Am I just mistaken in how I see the behaviour of this flag?

Related code at https://github.com/openlayers/openlayers/blob/d09e303672a7545224f22f5e52963fdbe47c1eb7/src/ol/renderer/canvas/VectorLayer.js#L526. I was wondering if the `||` should be `&&`?

**Comment by mike-000** [comment]
If you pan the map by dragging the layer is not redrawn while panning

![image](https://user-images.githubusercontent.com/49240900/113507766-5ae1e300-9544-11eb-87ee-05e97a829c27.png)

It is only redrawn when the mouse button is released.

If you set `updateWhileInteracting : true` it is continuously redrawn during the panning interaction.

**Comment by EvertEt** [comment]
<img width="1411" alt="Screenshot 2021-04-04 at 14 01 31" src="https://user-images.githubusercontent.com/9197891/113508126-8964bb80-954e-11eb-9544-98b511289d44.png">

@mike-000 I do not get the map to redraw even when it's set to true. Do you see my mistake?

**Comment by kikitte** [comment]
@EvertEt There are two vector layers in the map and you should set the counties vector layer instead of featureOverlay.

**Comment by EvertEt** [comment]
Good catch @kikitte ! I will close this issue. I see in #12171 it is also only set in the Draw interaction but not the VectorLayer in the example.
