### ISSUE TITLE
Popup close does not work with ol.Control.MousePosition

### ISSUE THREAD

**Issue by mastervanleeuwen** [openlayers/openlayers#12195]
**Describe the bug**
I use an openlayers map with popups (following the example: https://openlayers.org/en/latest/examples/popup.html ), but noticed that for popups near the edge of the map, the closing cross does not respond to clicks. The problem seems to be triggered by the use of the mouseposition control.

**To Reproduce**
1. Go to 'https://jtrackgallery.gta-trek.eu/'
2. Click on the icon on the right; a popup will show up with '-sample- Everest base camp'
3. The closing cross on the popup is not clickable

**Expected behavior**
Expect a working link to close the popup. If you click on one of the circles in Europe instead, a popup will appear for which the closing symbol is clickable.

Unfortunately, I could not reproduce this in a standalone way by modifying the popup example; there things seem to work even with the mouseposition control on, so this may be related to the more complicated site layout on my page (using Joomla!). I updated to openlayers v6.5 to see if that fixes the problem, but that does not seem to help.

Any suggestions are welcome; thanks for the help!

**Comment by mike-000** [comment]
Your mouse position div almost the height of the map div.  That is because your css contains 

```
.ol-mouse-position {
	bottom: 1.5em;
}
```

If the top is set (which is the default) the bottom should left auto.  If you want to position the control at the bottom your must also override the default top setting to auto:

```
.ol-mouse-position {
	bottom: 1.5em;
	top: auto;
}
```

**Comment by mastervanleeuwen** [comment]
Thanks for the clear explanation. That fixed it!
