### ISSUE TITLE
source/TileWMS does not support the attributionsCollapsible option

### ISSUE THREAD

**Issue by sbx320** [openlayers/openlayers#12197]
**Is your feature request related to a problem? Please describe.**
`source/TileWMS` currently does not support setting the `attributionsCollapsible` option. This currently prevents developers from disabling collapsable attributions in favor of the static attribution text when using TileWMS. 

**Describe the solution you'd like**
It should be possible to set the `attributionsCollapsible` option on an TileWMS source.

**Notes**
- The same issue also affects me when using `source/WMTS` (with an identical solution) for another map source. Should this be a separate issue?
- As the option is simply passed down to `source/TileImage` (which does support `attributionsCollapsible`), fixing it requires only a very minor change, so I've already applied it on my fork to allow me to continue working on my project. I'd be happy to make a PR out of it (or two, if you prefer a separate issue for WMTS).

**Comment by ahocevar** [comment]
Please provide a pull request. Can be a single one that makes the option available in both WMS and WMTS.
