### ISSUE TITLE
"Cannot read property 'appendChild' of null" when creating a variable of ol.style.RegularShape before document is loaded 

### ISSUE THREAD

**Issue by amenifus** [openlayers/openlayers#12191]
"`Cannot read property 'appendChild' of null`" error occurs when creating a variable of `ol.style.RegularShape` before document is loaded

1. Create `index.html` file
2. Create `someJs.js` file
2. In the `HEAD` tag include `OL6` library and someJs.js
3. In `someJs.js` file try to create `ol.style.RegularShape`. For example
```
const STYLE= new ol.style.RegularShape({
    radius: 5,
    points: 4,
    angle: Math.PI / 4,
    stroke: new ol.style.Stroke({
        color: "#333333",
        width: 1
    }),
    fill: new ol.style.Fill({
        color: 'white'
    })
});
```
4. Open `index.html` in the browser
5. See "`Cannot read property 'appendChild' of null`" in the console

Expected a variable of type `ol.style.RegularShape` created before document gets loaded but got an error.

FYI I have not executed bug reproduction sequence myself but came up with those steps because of what I have observed.
Then what I have observed?
1) error arises in this part of OL framework:
![image](https://user-images.githubusercontent.com/5813592/114085002-7557eb80-98b9-11eb-86ea-d1b81fe06bb6.png)
2) from that code I realised that error occurs because I am trying to create an instance of `ol.style.RegularShape` before document is loaded. Apparently `getComputedStyle(e)` needs a `DOM` node to be rendered
3) then I included my version of `someJs.js` file at the end of `HTML` and not in the `HEAD` tag and the error was gone

**Comment by mike-000** [comment]
That is needed to obtain the rgba value of a named color and could happen in any style definition.  Replacing `color: 'white'` with `color: '#fffff'` would avoid the error.

**Comment by amenifus** [comment]
Suggested replacement was the solution. Thank you.

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###

**Comment by GrantRynders** [comment]
###GrantRyndersTimeLog###
