### ISSUE TITLE
3D mode plan?

### ISSUE THREAD

**Issue by abigstupidbear** [openlayers/openlayers#12193]
Hi,is any plan to add 3D mode in openlayers? 
for example we can add dem service to display the terrain.
![image](https://user-images.githubusercontent.com/29300501/114199256-b538d480-9986-11eb-80b2-69ed1cd1bbef.png)
thank you for your reply.

**Comment by AugustusKling** [comment]
See https://openlayers.org/ol-cesium/

It should be possible to set your own terrain provider. See https://github.com/openlayers/ol-cesium/blob/master/examples/groundvectors.js#L141 and https://cesium.com/docs/tutorials/terrain/
