### ISSUE TITLE
Example "Tracing around a polygon" not working

### ISSUE THREAD

**Issue by magethle** [openlayers/openlayers#12190]
The example "Tracing around a polygon" (https://openlayers.org/en/latest/examples/tracing.html) is not working any more, probably because https://ahocevar.com/geoserver/wfs?service=wfs&request=getfeature&typename=topp:states&cql_filter=STATE_NAME=%27Idaho%27&outputformat=application/json responds with a 502 status code.

1. Go to https://openlayers.org/en/latest/examples/tracing.html
2. Trace around Idaho border
3. See error in console

**Comment by ahocevar** [comment]
Restored the service that responded with 502.
