### ISSUE TITLE
reexport layer and source in index.js

### ISSUE THREAD

**Issue by mmomtchev** [openlayers/openlayers#12207]
**Is your feature request related to a problem? Please describe.**
Using the syntax `ol.layer.Tile` after `import * as ol from 'ol'`

**Describe the solution you'd like**
Reexport layer, source, style, format... in index.js:
`export * as source from './source.js';`

Is there a reason why this is not the case?

**Comment by ahocevar** [comment]
I experimented with this a few weeks ago, and apparently some bundlers (notably Parcel 2) currently do not tree-shake these re-exports away.
