### ISSUE TITLE
[Documentation] Links point to 404

### ISSUE THREAD

**Issue by rowild** [openlayers/openlayers#12218]
On this page:
https://openlayers.org/en/latest/apidoc/module-ol_proj_Projection-Projection.html

the links to oengis.net are not valid anymore. I didn't find any new ones, sorry!

In case anybody takes care of this, would you mind to add the complete written out word for "SRS" somewhere? Thank you!

**Comment by ahocevar** [comment]
The "link" you are referring to (http://www.opengis.net/gml/srs/epsg.xml#3857) is not meant to be a http link, it is a SRS (spatial reference system) identifier.

**Comment by rowild** [comment]
Oha! I totally misunderstood that! How is that supposed to be used? Is it like a namespace (equivalent to, e.g., xmlns)?

**Comment by ahocevar** [comment]
It is similar to an xmlns, and it is used e.g. in WFS requests or responses to indicate the spatial reference system of the data. The list in the documentation points out the SRS identifiers that are understood by OpenLayers for its supported projections (geographic coordinates in WGS 84 and Web Mercator).

**Comment by rowild** [comment]
Thank you for the explanation!
