### ISSUE TITLE
Stroke Style pattern

### ISSUE THREAD

**Issue by sandman7920** [openlayers/openlayers#12215]
Is it possible to Style stroke with image pattern 

![image](https://user-images.githubusercontent.com/3589417/114765424-d37b4780-9d6d-11eb-8570-9b86e1d36bf9.png)

I have tried with canvas pattern and with TextStyle (utf8 arrow symbol) with little to no success.

**Comment by mike-000** [comment]
A canvas pattern would work in the same way as it does with fill https://openlayers.org/en/latest/examples/canvas-gradient-pattern.html and would be aligned to the canvas, not to the stroke.  Traffic direction arrows can be achieved by dividing the linestring into equal length (based on the resolution) sections and, at the midpoint or one end of each section, adding a icon to the styling rotated to the direction of the line at that point.  When done with a vector layer the icons should limited to the viewport extent to avoid creating an excessive number of style objects when zoomed in to a small part of a long line https://codesandbox.io/s/simple-forked-bc76b  For vector tiles one arrow per line per tile might be sufficient.  To see OpenLayers displaying traffic direction arrows with styles generated by ol-mapbox-style substitute "topo" with "bright" in https://openlayers.org/en/latest/examples/mapbox-style.html
