### ISSUE TITLE
backgroundFill is bugged when body is flex

### ISSUE THREAD

**Issue by Doskii** [openlayers/openlayers#12213]
**Describe the bug**
When the body element of the page has the style "display: flex" the backgroundFill option for text becomes very big. Having flex on anything else doesn't produce the problem. I'm using 6.4.5 but other versions I've tested have the same issue.

**To Reproduce**
1. Create a page with a map
2. Add some text
3. Add "display: flex" to the body

![image](https://user-images.githubusercontent.com/36999268/114729411-3c4bcb00-9d40-11eb-922f-e7adc018d5dc.png)

**Code example**
Here is a jsfiddle demonstrating it. Remove the flex from body and if you want add a new div inside body with flex so you can se it doesn't matter if the map is encapsulated by a flex, it's just the body that gives problems.

https://jsfiddle.net/Doskii/29hxu4bd/

**Comment by ahocevar** [comment]
Looks like our text height detection does not work with "display: flex" on the body. Can you please try if #12214 fixes the issue?

**Comment by Doskii** [comment]
I just managed to try it out (had to figure out how to build the .css/.js files from the repo, npm had "issues", so it took some trouble shooting). It unfortunately didn't seem to solve it.

**Comment by ahocevar** [comment]
I updated the pull request with a more involved fix. It seemed to work in my tests, but please try again.

**Comment by Doskii** [comment]
Yes! I works 😄 Thank you very much.
