### ISSUE TITLE
document.contains not supported in ie11

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#12225]
**Describe the bug**
`document.contains` not supported in ie11
https://developer.mozilla.org/en-US/docs/Web/API/Node/contains#browser_compatibility
https://github.com/openlayers/openlayers/blob/1554bc4cc27ed087027e23071bc0e90d643937f7/src/ol/PluggableMap.js#L990-L1000

**To Reproduce**
1. Go to https://openlayers.org/en/main/examples/box-selection.html
2. Click in the map
3. See error

**Expected behavior**
This seems to work, not sure if there is a case where this gives a different result.
```patch
diff --git a/src/ol/PluggableMap.js b/src/ol/PluggableMap.js
index 7c35c4374..fc8d9be34 100644
--- a/src/ol/PluggableMap.js
+++ b/src/ol/PluggableMap.js
@@ -996,7 +996,7 @@ class PluggableMap extends BaseObject {
         // It's possible for the target to no longer be in the page if it has been removed in an
         // event listener, this might happen in a Control that recreates it's content based on
         // user interaction either manually or via a render in something like https://reactjs.org/
-        !this.getOwnerDocument().contains(target)
+        this.getOwnerDocument().body.contains(target)
       ) {
         return;
       }
```

**Comment by ahocevar** [comment]
I think this is a safe change to make. Please create a pull request.
