### ISSUE TITLE
Mapbox satellite images won't display using MapboxVectorLayer

### ISSUE THREAD

**Issue by hms4242** [openlayers/openlayers#12228]
**Describe the bug**
Using a satellite-street style from Mapbox, I can see streets, but I can't see the satellite images.

**To Reproduce**
Use this map object:

```
let map =  new Map({
  target: 'map',
  layers: [
    new MapboxVectorLayer({
      styleUrl: 'mapbox://styles/mapbox/satellite-streets-v10',
      accessToken: 'my-mapbox-key',
    }),

  ],
  view: new View({
    center: fromLonLat([4.42, 45,4804]),
    zoom: 7
  })
});
````

**Expected behavior**
The map should show streets on top of satellite images.

**Comment by ahocevar** [comment]
As [documented](https://openlayers.org/en/latest/apidoc/module-ol_layer_MapboxVector-MapboxVectorLayer.html), `MapboxVectorLayer` only works with a single vector source. If you want to display everything that's in the `satellite-streets-v10` style, use [ol-mapbox-style](https://npmjs.com/package/ol-mapbox-style):
```js
import olms from 'ol-mapbox-style';
olms('map', 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v10?access_token=my-mapbox-key');
```

**Comment by hms4242** [comment]
Thanks for your answer & solution, sorry for having misread the documentation.
