### ISSUE TITLE
PointerEvent constructor call not supported in ie11

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#12226]
**Describe the bug**
after fixing  #12225 an error is thrown in 
https://github.com/openlayers/openlayers/blob/1554bc4cc27ed087027e23071bc0e90d643937f7/src/ol/MapBrowserEventHandler.js#L247
> Object doesn't support this action

**To Reproduce**
1. Apply patch in #12225
2. Go to box-selection.html
3. Click in map

**Expected behavior**
It should handle events without error.

**Comment by ahocevar** [comment]
Could be fixed by using `MSPointerEvent` for IE11.

**Comment by MoonE** [comment]
That's strange, it does not seem to work for me, even though it is listed as supported...

I tried the example code on the page you linked and get an error with 
`new PointerEvent(...)` `new MSPointerEvent(...)` and `document.createEvent(....)`
```js
var downEvent = new PointerEvent("pointerdown",
   {pointerId: 1,
    bubbles: true,
    cancelable: true,
    pointerType: "touch",
    width: 100,
    height: 100,
    isPrimary: true
   });
```

**Comment by ahocevar** [comment]
I'm wondering if it wouldn't be time to stop supporting Internet Explorer.

**Comment by mike-000** [comment]
Another polyfill may be needed.  Using https://cdn.jsdelivr.net/npm/events-polyfill@2.1.2 fixes the MDN example.

**Comment by MoonE** [comment]
That's better, no errors with this. But the simulated events like doubleclick still don't work. It looks like the target property can't be set here.
https://github.com/openlayers/openlayers/blob/1554bc4cc27ed087027e23071bc0e90d643937f7/src/ol/MapBrowserEventHandler.js#L247-L251

**Comment by mike-000** [comment]
#12319 gets it working in IE, but what about devices needing the elm-pep polyfill?  Is the event ever dispatched or any methods such as preventDefault/stopPropagation called?  If never dispatched an object containing the required properties and void methods typecast as PointerEvent might be sufficient.

**Comment by ahocevar** [comment]
I created #12330 as a simpler alternative to #12319.
