### ISSUE TITLE
VectorTile labels being cut in tile borders

### ISSUE THREAD

**Issue by digoburigo** [openlayers/openlayers#12236]
**Describe the bug**
When updating OpenLayers 6.4.3 to 6.5.0 my VectorTile layers with labels are being cut off by the tile border

**To Reproduce**
I just updated the openlayers, if some code is necessary, please respond with the steps that I have to make to help solve this problem

6.4.3
![old version](https://user-images.githubusercontent.com/28462822/115765160-c74e4600-a37c-11eb-9fc0-f43bffe0df69.png)

6.5.0
![new version](https://user-images.githubusercontent.com/28462822/115765665-6d9a4b80-a37d-11eb-8fa5-c2d586830863.png)

**Expected behavior**
I expect the behavior of 6.4.3

**Comment by ahocevar** [comment]
Some label issues were fixed after v6.5. Please try `npm install ol@dev` and report if the issue persists.

**Comment by digoburigo** [comment]
The issue is solved in the `dev` version, don't mind the changes in the styles
6.5.1-dev.1618770946568
![image](https://user-images.githubusercontent.com/28462822/115908541-aea76400-a440-11eb-866a-e6d52f40f0e2.png)
