### ISSUE TITLE
Why should I use openlayers instead of leaflet

### ISSUE THREAD

**Issue by johnluan** [openlayers/openlayers#12234]
Sorry guys, this maybe a wrong location. 
What is the reason that I should use openlayers instead of leaflet? 
I found a few article talk about openlayers can deal with more complexed gis issue. but what is this kind of issue? 
We used openlayers a lot, it is great, but seems more and more people are using leaflet, we are trying to review if we need to switch. 
Thanks

**Comment by rowild** [comment]
@johnluan I had that question myself and read this article to get a better understanding:
https://mapsvg.com/blog/openlayers-vs-leaflet

**Comment by TDesjardins** [comment]
I think the reason why a lot of people using Leaflet is that it is sufficient for the standard use case of showing a map with some simple info functions. That's the focus of Leaflet and therefore it is simple especially for non-developers with no GIS know how (like web designers) to setup a map in web page.
If you need more than this OpenLayers is your friend. It has a more powerful and cleaner API and a cleaner overall architecture. For example the separation of layers, datasources and formats. In Leaflet "GeoJSON" is a layer 😄 .

> I found a few article talk about openlayers can deal with more complexed gis issue. but what is this kind of issue?

You are using OL a lot but don't know it? 😉 

> We used openlayers a lot, it is great, but seems more and more people are using leaflet, we are trying to review if we need to switch.

Hehe, sounds like the only reason for you to switch is that a lot of people using Leaflet. If you think OL is great and it fits your requirements why there should be a need to switch?

**Comment by rowild** [comment]
@TDesjardins 
> If you think OL is great and it fits your requirements why there should be a need to switch?
Because it has never been a bad idea to compare with other solutions. For quite a lot of reasons...

**Comment by TDesjardins** [comment]
> @TDesjardins
> 
> > If you think OL is great and it fits your requirements why there should be a need to switch?
> 
> Because it has never been a bad idea to compare with other solutions. For quite a lot of reasons.

@rowild Sure, but comparing is another step than switching. My question is meant rhetorical and could be used to find answers that could be used for making such decisions. Other reasons than "A lot of people using it.". This could be at most an indicator because you don't know if the requirements of those peoples match yours.
