### ISSUE TITLE
StopClick option does not work in Opelayers 6.4.2

### ISSUE THREAD

**Issue by AndiDomi** [openlayers/openlayers#12232]
**Describe the bug**

I am trying to disable programmatically the ability to put a point (either point of a line or polygon) in the map through either the draw object or the map one with the click of a button. Looking at the documentation for OpenLayers 6 draw object there is an option to do this by adding:

    stopClick boolean (defaults to false) : Stop click, singleclick, and doubleclick events from firing during drawing. 

to the draw object constructor which is also present in 6.4.2.

But on implementation it did not work as expected.

I also searched on GitHub if this was a bug or opening possible one but I could not find any for this specific version of Openlayers, [even tho a bug similar was fixed in version 6.5.0](https://github.com/openlayers/openlayers/issues/12147) this bug was [not present in Openlayers 6.4.2](https://github.com/openlayers/openlayers/blob/7c934393834bb9bf87b9c7ae73698be940eda93a/src/ol/interaction/Draw.js#L635)

Is there any other way to achieve this?

**To Reproduce**
1. Go to : [https://codesandbox.io/s/min-zoom-forked-ix2i6](https://codesandbox.io/s/min-zoom-forked-ix2i6?file=/main.js)
2. Try to click on the map
3. It is possible to draw a polygon or line even tho `stopClick` is set to `true`

**Expected behavior**
Point `3.` should not be able to happen, and it should not be possible to click on the map.

**Comment by mike-000** [comment]
`stopClick` is not intended to prevent drawing, it prevents a click event handled by the draw being propagated to the map and firing any listeners you have set on the map https://codesandbox.io/s/min-zoom-forked-dz3h8  Comment out the `stopEvent: true` and clicks on the map will be logged.  If you want to control when or where a click is handled by the draw interaction you will need to use a condition function such as https://codesandbox.io/s/min-zoom-forked-ei5sf

**Comment by AndiDomi** [comment]
@mike-000 Thanks a lot! This works like a charm!
