### ISSUE TITLE
For Documentation: Add reason why "ol-overlaycontainer-stopevent" is 100%x100%

### ISSUE THREAD

**Issue by rowild** [openlayers/openlayers#12246]
I would like to propose (or actually request) a better description of the following scenario, which is very unclear to me in 2 aspects.

The documentation here:

https://openlayers.org/en/latest/apidoc/module-ol_control_Control-Control.html

states in the introducing paragraph that the Control layer handles all pointer stop events. This is done by adding a div with class" ol-overlaycontainer-stopevent" that has 100% width and 100% height with a CSS attribute of "pointer-events: none". 

But the controls do not need 100%x100%, so it is unclear as to why this background must cover the whole map area. To me it seems that it would be fine to cover simply the area of the controls. I might be wrong, but if so, then I do not understand why.

Also, if there is a way to influence the automatic addition of CSS classes via JS on that very div, it should be mentioned (more clearly?).

**Comment by mike-000** [comment]
There is only one `ol-overlaycontainer-stopevent` div and maps can have multiple controls which can be positioned all around the viewport, so 100% coverage is needed.  Overlays which pan across the viewport with the map https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html also use the same div unless `stopEvent: false` is specified.  To place controls elsewhere you can specify a `target` div as in https://openlayers.org/en/latest/examples/mouse-position.html.  Using css you could even put your "outside the viewport" target div on top of the viewport similar to the info div in https://openlayers.org/en/latest/examples/vector-tile-info.html if you needed to (e.g. for a custom control such as a search box).

**Comment by rowild** [comment]
Thank you @mike-000, also for the examples, from the I wasn't aware of the last one. 

However, if you could help me understand a little bit more, please: 

If I remove the Control layer from the DOM (simply by deleting the node in the Chrome DevTools), I still can maneuver around the map as I did before: click-dragging, rotating, mousewheel-zooming... (I have `interactions: defaultInteractions().extend([new DragRotateAndZoom()]),` activated). Same thing, when I change values on that dom element manually (e.g. width: 50%)

I still have troubles understanding, what this layer exactly does and when it should be used or not. You mentioned that there is a "stopEvent: false" option available, so I assume there is a scenario, where this Control layer is "not welcome" and others where is is most welcome...

The reason I stumbled upon this "phenomenon" is that I'd like to move all controls into a layer that only shows when a toggle button is clicked (much like a drop down list). I have serious troubles doing that with the out-of-the-box Javascript button, therefore I "removeControl" them, create my own divs, assign a clickEventListener to each of them and use the zoomIn/-Out/rotate functions from the core (except without the "createElement" sections). I am not completely there yet, but of course I am already wondering, which problems I will encounter, when I ignore the `ol-overlaycontainer-stopevent` layer.
