### ISSUE TITLE
Can't change coordinates in GeometryCollection > Geometry object

### ISSUE THREAD

**Issue by przemyslaw-szustak** [openlayers/openlayers#12253]
**Describe the bug**
I can't change coordinates in GeometryCollection. After set new coordinates on GeometryCollection nothing happend.

**To Reproduce**
I created jsfiddle: https://jsfiddle.net/t4szmwnp/1/
But you can try:
1. Add feature from GeoJson GeometryCollection.
2. Try to change geometry coordinates from GeometryCollection.

**Expected behavior**
I would like to change coordinates for geometry object that is inside GeometryCollection.

**Comment by mike-000** [comment]
`getGeometries()` returns clones of the geometries in the collection, so after making changes you need to call `setGeometries()`.

        var geometries = olFeatures1[0].getGeometry().getGeometries();
        geometries[0].setCoordinates(featureNewCoords);
        olFeatures1[0].getGeometry().setGeometries(geometries);

**Comment by przemyslaw-szustak** [comment]
Thanks a lot mike-000, it works! :)
https://jsfiddle.net/s46pyvd0/
