### ISSUE TITLE
Search box for search a location.

### ISSUE THREAD

**Issue by jitendra-inventum** [openlayers/openlayers#12252]
Hi, 
I have implemented openlayers in my project, but there is lack of features as like google map.
I have some features, which need to implement in my project. so please help me with listed below points.
> Implementing search box for search location.
> Show pointer on searched location.
> Render map with latitude and longitude.

**Comment by mike-000** [comment]
There are some third-party https://openlayers.org/3rd-party/ search boxes such as OL-Geocoder and OL-Ext available which are compatible with most geocoding APIs.
