### ISSUE TITLE
the Modify interaction cannot modify the certain linear of the polygon which is created by DropInteraction

### ISSUE THREAD

**Issue by fnlearner** [openlayers/openlayers#12260]
**Describe the bug**
I dont know why the Modify interaction cannot modify the certaion linear of the polygon which is created by the DragAndDrop interaction;
I dont knonw whether it is a bug for ol
**To Reproduce**
https://codepen.io/24kpurehandsome/pen/BapepWO?editors=0011;
u can click the link above to view the process;
u can drag the text named room into the area in the right bordered,and in fact the polygon created just now can be modifyed.
but the Modify interaction cannot work correctly  when u try to drag certain linear of the polygon .
i dont konw whether it is my fault to use ol;thx!
**Expected behavior**
all of linear of polygon can be modifyed when the Modify interaction add the item dragged onto its features

**Comment by mike-000** [comment]
You need to include `ol.css` so the controls are correctly styled.  Without the css one of the control divs is stretched across the top of the viewport preventing the modify interaction from working above the red line
![image](https://user-images.githubusercontent.com/49240900/116581490-49ee7c80-a90c-11eb-817e-6a0f2a4fd0c7.png)

Also polygon rings should be closed (start and end at the same coordinate)
```
    this.initPolygon([
      [130, 39],
      [60, 33],
      [30, 33],
      [30, 39],
      [130, 39]
    ]);
```

**Comment by fnlearner** [comment]
![image](https://user-images.githubusercontent.com/38586156/116635026-4e5c7900-a990-11eb-83df-3d9a35dd00a3.png)
Yeah. I import the css file using link tag  in html.
last and important ,thank u to solve my problem !
