### ISSUE TITLE
Legacy build broken

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#12265]
**Describe the bug**
The legacy build generation is broken since #12241.

Something like this should do, but I'm getting errors for classes that do not have a default export, before it generated only warnings ...
```patch
diff --git a/tasks/generate-index.js b/tasks/generate-index.js
index c3e12f5ac..51c00f1f4 100644
--- a/tasks/generate-index.js
+++ b/tasks/generate-index.js
@@ -24,13 +24,13 @@ function getImport(symbol, member) {
   const defaultExport = symbol.name.split('~');
   const namedExport = symbol.name.split('.');
   if (defaultExport.length > 1 && defaultExport[0].indexOf('.') === -1) {
-    const from = defaultExport[0].replace(/^module\:/, './') + '.js';
+    const from = defaultExport[0].replace(/^module\:/, './');
     const importName = from.replace(/[.\/]+/g, '$');
-    return `import ${importName} from '${from}';`;
+    return `import ${importName} from '${from}.js';`;
   } else if (namedExport.length > 1 && member) {
-    const from = namedExport[0].replace(/^module\:/, './') + '.js';
+    const from = namedExport[0].replace(/^module\:/, './');
     const importName = from.replace(/[.\/]+/g, '_');
-    return `import {${member} as ${importName}$${member}} from '${from}';`;
+    return `import {${member} as ${importName}$${member}} from '${from}.js';`;
   }
 }
 ```
Before #12241 webpack generated warnings
```
WARNING in ./build/index.js 847:11-20
export 'default' (imported as '$ol$color') was not found in './ol/color' (possible exports: asArray, asString, fromString, isStringColor, normalize, toString)
```
After #12241 it generates errors and does not finish the build
```
ERROR in ./build/index.js 847:11-20
export 'default' (imported as '$ol$color') was not found in './ol/color.js' (possible exports: asArray, asString, fromString, isStringColor, normalize, toString)
```

**To Reproduce**
1. Run `npm run build-index`
2. The imported names in build/index.js do not match the names assigned to the `ol` object.

**Expected behavior**
It should generate a working legacy build.

**Comment by tschaub** [comment]
If we’re going to continue supporting the legacy build, we’ll need to have some tests for it.  Feels like it has been too easy to break lately.  While working on #12241, I did confirm that the build script still worked, but it sounds like I broke it at some point.

**Comment by tschaub** [comment]
The `build/index.js` can be partially fixed with https://github.com/tschaub/openlayers/commit/4dc47c4fcd46fc10bc7f74b875c1877eb59fe488.

The remaining issue is that it is now an error to do something like `import $ol$color from 'ol/color.js'`.  The `ol/color.js` module doesn't have a default export, and webpack reports this as an error.  Before #12241, it looks like this was only reported as a warning.

So the next part of the fix would be to stop adding import lines to the `build/index.js` for these default exports where there there is not a default export.
