### ISSUE TITLE
StopClick in Draw intercator does not work

### ISSUE THREAD

**Issue by BenukEl** [openlayers/openlayers#12274]
**Describe the bug**
When stopClick is set to true in Draw interactor, dblclick and singleclick event on the map are still fired. 

**To Reproduce**
This sandbox reproduces the bug: https://codesandbox.io/s/draw-and-modify-features-forked-j5wsm
1. Create Draw with stopClick=true
2. Set listener to singleclick on map 
```javascript
map.on("singleclick", () => {
  alert("single click received");
});
```
3. See an alert

**Expected behavior**
When stopClick is set to true, single and double click event are not fired

**Comment by EvertEt** [comment]
Duplicate of https://github.com/openlayers/openlayers/issues/11891. You can try the dev versions for the fix (`npm install ol@dev`)

**Comment by BenukEl** [comment]
Thanks a lot ! 
Thanks ol team ! 
Sorry for duplicated issue...
