### ISSUE TITLE
Question: is it secure to use DEV builds?

### ISSUE THREAD

**Issue by MichalK6677** [openlayers/openlayers#12278]
I'm in a situation where the latest stable version (6.5.0) has regression issues which block me from upgrade from previous stale version (6.4.3). However versions 6.5.0 and newer fix/introduce features I would like to use to avoid "library hacking".

Is it secure to use DEV builds on production? Are those builds stable?

What is purpose of builds marked with "module" (6.5.1-module.1, 6.5.1-module.2)?

**Comment by ahocevar** [comment]
OpenLayers uses a stable main branch, and a `@dev` version is created with every push to the `main` branch. The `@dev` Builds run through the same test process as the official releases. The only difference is that there is no versioned API documentation on https://openlayers.org/en/ (but you can find one in every merged pull request's build artifacts), and no release notes. So yes, you can consider those builds stable.

The `@module` Builds were for testing the `"type": "module"` mode before that code was merged into the main branch, so you probably don't want to use those.
