### ISSUE TITLE
Selecting only polygon vertices with small circles

### ISSUE THREAD

**Issue by karthikbht91** [openlayers/openlayers#12276]
This is in continuation to the defect: https://github.com/openlayers/openlayers/issues/3165. I've created the vertices of a polygon with small circles as I'm trying to implement the scale, rotate functionality using OpenLayers 4.65.
Most of the part is already implemented using geom.rotate and geom.scale methods. 
![image](https://user-images.githubusercontent.com/45008585/117136083-82d39900-adc5-11eb-893d-b76196bc6d94.png)

The only catch is that the whole geometry can be clicked to scale the geometry and I need to restrict this to modify with these circles **(only)** for editing the polygon.

**Comment by mike-000** [comment]
To restrict the Modify interaction to moving vertices include

```
deleteCondition: ol.events.condition.never,
insertVertexCondition: ol.events.condition.never,
```
in the options

**Comment by karthikbht91** [comment]
Are these properties available for geom.scale?
Also I would like to select the created circles of the polygon.
