### ISSUE TITLE
ol.Overlay.getElement() does not return the rendered element

### ISSUE THREAD

**Issue by mattti-post** [openlayers/openlayers#12280]
DOM element rendered by ol.map.addOverlay(overlay) is not the same as the DOM element provided in constructor ol.Overlay() when creating the overlay. Then the method overlay.getElement() returns the DOM element provided in constructor ol.Overlay(), which is imho useless. 

I would expect this method to return the rendered DOM element.

**Comment by mike-000** [comment]
Why is it useless?  You may have multiple overlays with dynamically created elements https://codesandbox.io/s/popup-forked-v4pmz  You might want to iterate through all overlays and update the content when something changes on the map.  When OpenLayers has rendered an overlay you can use the `parentElement` property of the result of `.getElement()` to see where it has been rendered.

**Comment by mattti-post** [comment]
Yes I am sorry, I made mistake assuming that the element is not the same one rendered inside the parent ol div, while it actually is the same object. It was caused by complicated structure of my DOM element and one ahocevar post in stack where he wrote that the container element is rendered as ol overlay element(At least I understood it like that, can't find that post). 

But still, how is it granted, that I can always access the parent element? What if the rendered DOM will change in future and there will be one more nested DIV in overlay DOM? 

Anyway my motivation is very simple. I just needed to create an absolutely positioned overlay in the bottom of the map not bound to position and visible. An overlay has display: none set after added. So I needed to change that value to show the overlay. Now I am using the ol.Overlay constructor options.className property to access it, which is a little bit cumbersome, but working. 

Thanks very much.

**Comment by M393** [comment]
Overlays should always be positioned relative to a map position and not relative to the viewport.
For what you are doing [`ol/control/Control`](https://openlayers.org/en/latest/apidoc/module-ol_control_Control-Control.html) would be a better fit.

**Comment by mattti-post** [comment]
Thanks, I knew I missed the point.
