### ISSUE TITLE
View.calculateExtent is wrong with view padding

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#12281]
**Describe the bug**
`View` with `padding` returns wrong extent for `calculateExtent`.

**To Reproduce**
1. Go to https://codesandbox.io/s/calculate-extent-view-padding-kt76i?file=/main.js
3. See logged extent in console: `[-270, -90, 90, 90]`

**Expected behavior**
The calculated extent should be `[-180, -90, 180, 90]` (or alternatively `[-180, -90, 0, 90]` for the non-padded part?)

**Comment by MoonE** [comment]
Looks like this was fixed by #11938, it returns `[-180, -90, 0, 90]` now.
