### ISSUE TITLE
Investigation in canvaskit-wasm

### ISSUE THREAD

**Issue by codeart1st** [openlayers/openlayers#12285]
We all know that OffscreenCanvas may be the feature for OpenLayers and many other libraries. Furthermore we have Firefox in the list of our supported browsers. Since years there seems to be no progress at all in Firefox development to improve the current flagged OffscreenCanvas support and add the lack of 2D support.
Currently in OpenLayers the vector tiles support on the main js thread is maybe unusable from a user experience perspective. The web worker approach is not perfect but great. It's ok, because mapbox gl js exists with the WebGL pipeline. But sometimes I hope we can get shader power again in OpenLayers for vector data. But this is another story.
The second big topic these days is WebAssembly, so I decided to search for an canvas implementation in WASM. I found out that Google Chromes Skia rendering engine has an wasm port: https://skia.org/docs/user/modules/canvaskit/

Interesting I thougt. Maybe this is the way to go until Firefox...

So I tried it. Hacked a little bit inside of OpenLayers and the canvaskit-wasm binding js code and got the OpenLayer webworker example working in Firefox and Chrome basted on Skia WASM power. The amount of changes were not so much because of canvaskit-wasm has a nearly 1:1 canvas API binding.

Currently there is one big drawback I found out. Bit blitting (drawImage) without hardware acceleration is terrible slow in comparison to native OffscreenCanvas. All other draw calls seems to be ok in performance. This results in ~0,5-1s tile draw time.

What I not tried so far is what if we post all created sketches from the tile rendering pipeline to the main thread for composing on a real hardware accelerated canvas. Seems to be a lot of changes in the OpenLayers rendering pipeline.

And yeah, there is also a impact of bundle size with the wasm binary.

I want to share this experience with you and start a discussion about this approach.

**Comment by regileeso** [comment]
Would you be able to share your code? I'm very interested in it because I'm currently doing some research on such things: OpenLayers, OffscreenCanvas and Skia.

**Comment by codeart1st** [comment]
Currently I started experimenting (https://github.com/codeart1st/wgpu-layers) with WebGPU, Rust and WASM like the new upcoming maplibre-rs project. But not as a standalone aproach, more like an addon for OpenLayers.

For canvaskit-wasm my old experiment is very sketchy. You can give it a try, if you want: https://gist.github.com/codeart1st/e4a442aa0aa2835fe6440c454ccdfcab

Based on commit 7a2f87caca9ddc1912d910f56eb5637445fc11f6.
Don't know if it's working currently in this state.
