### ISSUE TITLE
Static Local Image Support for OpenLayers

### ISSUE THREAD

**Issue by cyrus01337** [openlayers/openlayers#12296]
**Is your feature request related to a problem? Please describe.**
From my experiences there is no support to portray a local static images as the map seemingly without retrieving the image from an external (or otherwise) webserver.

**Describe the solution you'd like**
For local image paths to be utilised when setting it as the URL such that the following becomes possible:
```js
let layer = new ImageLayer({
    source: new Static({
        url: "./assets/map.png",
        projection: projection,
        imageExtent: extent
    })
})
```

**Comment by mike-000** [comment]
It works here https://codesandbox.io/s/static-image-forked-2p72k?file=/main.js

**Comment by cyrus01337** [comment]
Oh. This appears to be a local issue that I am having then because this does not work on localhost. Should I make a separate issue?
