### ISSUE TITLE
[Examples] Basemap example does not work

### ISSUE THREAD

**Issue by rowild** [openlayers/openlayers#12301]
There is an example that demonstrates the usage of basemap with openLayers. The link to the example can be found at basemap.at in the help section:
https://basemap.at/#hilfe

It leads to this site:
https://openlayers.org/en/latest/examples/wmts-hidpi.html?q=wmts

Unfortunately it does not seem to work anymore. There are no errors in the console.
Is this something that can be fixed? Would be great! Thank you!

**Comment by rowild** [comment]
@MoonE You are quick! Thank you very much!!!

**Comment by rowild** [comment]
I assume this example uses version 6 - maybe basemap should be informed, so they can update their link and mention the new verion? I'd be happy to do that, if that's ok with you.

**Comment by MoonE** [comment]
The link is correct, it uses `latest` as the version, which currently points to `v6.5.0`. It won't work until the next release. Maybe they should  just not mention a version.
If you want to  notify them go ahead :+1:
