### ISSUE TITLE
Canvas never reused for layers with pixelRatio of 3

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#12305]
**Describe the bug**
When the canvas transform has more than 6 decimal places it is rounded by the browser. The comparison at
https://github.com/openlayers/openlayers/blob/fdfdc500aa041e2921c059298c04e7bad45619cf/src/ol/renderer/canvas/Layer.js#L99-L103
will fail because the transform matrix values `matrix(0.3333333333333333, 0, 0, 0.3333333333333333, 0, 0)` are rounded to `matrix(0.333333, 0, 0, 0.333333, 0, 0)`
**To Reproduce**
1. Go to https://codesandbox.io/s/pixelratio-canvas-reuse-ltz2u
2. See the number of canvas elements below the map

**Expected behavior**
The transform comparison should handle rounded numbers. Don't create additional canvas elements with different pixelRatio.

**Comment by mike-000** [comment]
Very old discussion here http://w3-org.9356.n7.nabble.com/Numeric-precision-in-CSS-numbers-td31176.html with link to test page https://bug-30341-attachments.webkit.org/attachment.cgi?id=45276
Current versions of Chrome and IE on Windows, and Opera on Android all round to 6 significant digits

**Comment by M393** [comment]
Thanks, @mike-000. I submitted a PR that would read both matrices to compare back from a DOM node. This should be safe in all browsers.
