### ISSUE TITLE
Work with VectorTileServer

### ISSUE THREAD

**Issue by NeiroNx** [openlayers/openlayers#12307]
OpenLayers do not have layer for:
https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer

and i am try
```JavaScript
new ol.layer.VectorTile({
	id:"OSMVec",
	name:"OSM Vector",
	source: new ol.source.VectorTile({
		format: new ol.format.MVT(),
		tilePixelRatio: 16,
		url: 'https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer/tile/{z}/{y}/{x}.pbf',
		maxZoom: 20,
		cacheSize:2048,
		tileGrid: new ol.tilegrid.createXYZ({maxZoom: 20}),
	}),
	styleUrl: 'https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer/resources/styles'
})
```
but no style...

Does it have any functions for build styles from [that](https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer/resources/styles) url?

**Comment by mike-000** [comment]
You can obtain the url of the style from the "View Style" link in https://www.arcgis.com/home/item.html?id=3e1a00aeae81496587988075fe529f71
which can be used with OpenLayers via ol-mapbox-style https://codesandbox.io/s/mapbox-style-forked-v981q

**Comment by NeiroNx** [comment]
I am try this, but it do not work - white fild after applying style. 
```JavaScript
var OSMVec = new ol.layer.VectorTile({
	id:"OSMVec",
	name:"OSM Vector",
	source: new ol.source.VectorTile({
		format: new ol.format.MVT(),
		tilePixelRatio: 16,
		url: 'https://basemaps.arcgis.com/arcgis/rest/services/OpenStreetMap_v2/VectorTileServer/tile/{z}/{y}/{x}.pbf',
		maxZoom: 20,
		cacheSize:2048,
		tileGrid: new ol.tilegrid.createXYZ({maxZoom: 20}),
	})
});
fetch("https://www.arcgis.com/sharing/rest/content/items/3e1a00aeae81496587988075fe529f71/resources/styles/root.json").then(r => r.json()).then((glStyle) => {olms.stylefunction(OSMVec, glStyle, 'myStyle')});
```
Why it do not work?

**Comment by ahocevar** [comment]
There is no `myStyle` source in that style. It's `esri` instead.

**Comment by ahocevar** [comment]
Also not that you'll get there more easily by using a higher level API of `ol-mapbox-style`:
```js
olms(
  'map',
  'https://www.arcgis.com/sharing/rest/content/items/3e1a00aeae81496587988075fe529f71/resources/styles/root.json'
);
```

**Comment by NeiroNx** [comment]
not easy, i am using multiple layers, iteractions and other stuff.

**Comment by ahocevar** [comment]
Then you can pass an existing `ol/Map` instance to `olms()`, instead of `'map'`. Also, `olms` returns a promise. When resolved, you have access to all layers it added to your existing map.
