### ISSUE TITLE
OL2 'zoomstart' event equivalent ?

### ISSUE THREAD

**Issue by nboisteault** [openlayers/openlayers#12302]
**Is your feature request related to a problem? Please describe.**
Is there an equivalent of [OL2 zoomstart](http://dev.openlayers.org/docs/files/OpenLayers/Map-js.html) event in current OL ?
With OL2 it was possible to 

> receive an object with center and zoom properties, for the target center and zoom level

which was very convenient.

**Describe the solution you'd like**
I'd like this event added to current OL API or some help to find a way to get this behavior with current API. Thanks.

**Comment by ahocevar** [comment]
You might be able to obtain the information you need using the `movestart` event:
```js
map.on('movestart', e => {
  const previousZoom = e.frameState.viewState.zoom;
  const currentZoom = map.getView().getZoom();
  if (previousZoom !== currentZoom) {
    console.log('zoomstart');
  } 
});
```
Because OpenLayers 3+ uses fractional zoom and animation by default, `currentZoom` will not be the target zoom, but the zoom at the current animation step.
