### ISSUE TITLE
Offscreen canvas example does not work in production mode

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#12317]
**Describe the bug**
There seem to be different minifications for the projection class with the webworker and normal example code.
These two objects cannot be compared:
![image](https://user-images.githubusercontent.com/4426597/118189367-f9b20700-b441-11eb-8990-0bc46897664c.png)

It's caused by the changes to the example webpack config in #12176

**To Reproduce**
1. Go to https://deploy-preview-12313--ol-site.netlify.app/examples/offscreen-canvas.html
2. See the failed assertion
3. Go to the previous stack frame, as in the picture above

**Expected behavior**
The projections compared here should be equivalent.

**Comment by tschaub** [comment]
I wonder if it would be enough to add a pattern for `offscreen-canvas` to the [list of examples](https://github.com/openlayers/openlayers/blob/ac9187c9bf2da21bc6e8f82f38399701f1420eba/examples/webpack/config.js#L64) to exclude from minification.

**Comment by MoonE** [comment]
I'm also getting an error for the `raster` example. `color-manipulation` and `region-growing` seem to work.
Adding `offscreen-canvas` / `offscreen-canvs\.worker` to the regex doesn't work.
