### ISSUE TITLE
Changing the default rotation on the Rotate control is very difficult

### ISSUE THREAD

**Issue by SkylerBleu** [openlayers/openlayers#12329]
When initializing a map that is not oriented north (i.e. a map rotated 180 degrees), the reset rotation control is very difficult to reorient along side it. The only way to do so currently is to redefine the render and resetNorth functions entirely at the time of the Rotate control's creation.

Can we add a parameter to the Rotate control that does one or both of the following?:

1. Add a parameter for the default orientation. Rename "resetNorth" to something more broad, like "resetRotation" and modify the reset and render functions to use the new default rather than 0
2. Add a boolean to the control (or a function) that tells it to set the default to map's current rotation.

https://github.com/openlayers/openlayers/blob/main/src/ol/control/Rotate.js#L133

**Comment by EvertEt** [comment]
See also https://github.com/openlayers/openlayers/issues/11080

**Comment by SkylerBleu** [comment]
@EvertEt I'm debating opening a PR for this myself, as it seems like a pretty easy change. I hadn't considered that the arrow's default should be adjustable as well to accommodate. That would look really clean. Maybe that could be set to a boolean param like "realignArrow"?

**Comment by mike-000** [comment]
I think all that would be needed is a `defaultRotation` option in the constructor and a `setDefaultRotation` to update it, both taking radians.  https://codesandbox.io/s/simple-forked-tzhm0  The value could also be used to control autohide.  However, the view would then need a similar option and method so `constrainRotation` snaps to the same default (or fractions offset from it) instead from 0 - that might be a bigger change.
