### ISSUE TITLE
Very slow map response when Vector layer's style is set to StyleFunction

### ISSUE THREAD

**Issue by ashchurova** [openlayers/openlayers#12331]
To change style dynamically during the runtime we set style on the Vector layer to an instance of StyleFunction. And when we plot large number of points interaction with map becomes very slow. Sometimes map is tuck and doesn't respond at all. I have reproduced this issue in the following sample:

[OL slow map interaction while using StyleLike function for style](https://codepen.io/ashchurova/pen/jOBMrVp) 

Please investigate. Thank you.

**Comment by ThomasG77** [comment]
The bug is in your code logic although it does not throw an error

Instead of 

```
var pointsVector = new ol.layer.Vector({
  source: new ol.source.Vector({ features: features }),
  style: (f) => {
    return new ol.style.Style({
      image: new ol.style.Circle({
        radius: 2,
        fill: new ol.style.Fill({ color: "red" }),
        stroke: new ol.style.Stroke({ color: "red", width: 2 })
      })
    });
  }
});
```

replace it with

```
var mystyle = new ol.style.Style({
  image: new ol.style.Circle({
    radius: 2,
    fill: new ol.style.Fill({ color: "red" }),
    stroke: new ol.style.Stroke({ color: "red", width: 2 })
  })
});

var pointsVector = new ol.layer.VectorImage({
  source: new ol.source.Vector({ features: features }),
  style: mystyle
});
```

You are consuming all the memory by instantiating as many style as there is feature but you do not need do this as you have an unique style (look at above syntax). You also use `ol.layer.Vector` whereas you should use `ol.layer.VectorImage` to avoid so many refresh. With the first one, it refreshes more than with the second. The 1st one is useful when need animation or continuous update but not here

**Comment by ashchurova** [comment]
Having style-per-feature is not a bug, it is a feature. We allow features to have their own styles because we render them on the fly. For ex. we subscribe to our ticker service and on price change we would render feature with different colors. I am aware that if I have one unique style for all features performance improves dramatically but I have to support style-per-feature.  And styles should not that much memory, Style is a small object.

Thank you for the tip for ol.layer.VectorImage. I will check it out.

**Comment by ThomasG77** [comment]
> Having style-per-feature is not a bug, it is a feature

Agree but it has a price e.g perfs, avoid it, cache style as much as you can, when possible.

> we subscribe to our ticker service and on price change we would render feature with different colors

if you already know your style output, you can create them before an reuse them instead of creating 20 times a red style. This feedback is only "right" if not too many combinations. Basic sample logic below.

```
var color1 = new ol.style.Style({
      image: new ol.style.Circle({
        radius: 2,
        fill: new ol.style.Fill({ color: "red" }),
        stroke: new ol.style.Stroke({ color: "red", width: 2 })
      })
    });

var color2 = new ol.style.Style({
      image: new ol.style.Circle({
        radius: 2,
        fill: new ol.style.Fill({ color: "green" }),
        stroke: new ol.style.Stroke({ color: "green", width: 2 })
      })
    });

var pointsVector = new ol.layer.Vector({
  source: new ol.source.Vector({ features: features }),
  style: (f) => {
    if (f.get('value') > 10000) {
      return color1;
    else {
      return color2
    }
    });
  }
});
```

**Comment by M393** [comment]
What makes this slow is `ol/style/Circle` which creates a canvas element where the image is rendered to. This canvas is used to draw on the map and recreating the circle style on each frame will be very slow. Either cache it somewhere on the layer or if you have many different styles you can cache it on the feature.

**Comment by ashchurova** [comment]
> What makes this slow is `ol/style/Circle` which creates a canvas element where the image is rendered to. This canvas is used to draw on the map and recreating the circle style on each frame will be very slow. Either cache it somewhere on the layer or if you have many different styles you can cache it on the feature.

@M393 Thank you. I know I didn't do it in my sample but we do cache style at feature level but maybe our caching mechanism has an issue because it is still slow. I will investigate further but in theory if no style properties changed meaning color, border width, etc we do not recreated style object. It is only created once when feature is been rendered for the first time and we update existing style object from that point.

**Comment by ashchurova** [comment]
@ThomasG77 yes, I see it now that being too flexible has a price. Initially we loved how OL allowed us to specify function instead of  dined style because it allowed us to databind  style properties and change them dynamically. But it is not always needed like the example I have which is vessel movement history and kills map's performance when we have to plot it on the map. We will have to rethink our design and do some optimization. Thank you for ol.layer.VectorImage, this already sped things up but not enough...

**Comment by ashchurova** [comment]
@M393 I ended up writing my own renderer function to avoid extra canvas elements. Looks very good. Thank you for your help.
