### ISSUE TITLE
[API] Import different from usage

### ISSUE THREAD

**Issue by rowild** [openlayers/openlayers#12333]
Not sure if this is a big deal. But it seams that in this example:

https://openlayers.org/en/latest/apidoc/module-ol_layer_MapboxVector-MapboxVectorLayer.html

the import is named differently - `MapboxVectorLayer ` - than its actual usage: `MapboxVector`.

(For the sake of consistency I would call it the same.)

**Comment by MoonE** [comment]
I agree and created #12334 to change this.

**Comment by rowild** [comment]
@MoonE Thank you! :-)
