### ISSUE TITLE
API to get map beginning coordinate in pixels 

### ISSUE THREAD

**Issue by davoam** [openlayers/openlayers#12332]
Hi! 

I am trying to shift the map on this zoom level to the right side of the view. I tried to somehow get coordinates of the beginning of the map (top left tile `x` coordinate) , but all in vain. 

![image](https://user-images.githubusercontent.com/9194866/118825255-327b3180-b8c3-11eb-8435-d6066694c098.png)

I don't want to set `showFullExtent: false`, because we need it to be equal to `true`.  Also I used `wrapX: false` in OSM constructor. 

Is there any API which can tell where is the beginning of the map in pixels? I can use to apply transform (at least) in order to move map to the right side.

**Comment by ahocevar** [comment]
You can use the `padding` option of the view. See https://openlayers.org/en/latest/examples/view-padding.html for an example.

**Comment by M393** [comment]
This should give you the pixel of the top-right corner of the world (untested)
`map.getPixelFromCoordinate(getTopRight(view.getProjection().getExtent()))`

**Comment by davoam** [comment]
Thanks, @M393 ! 

It does what is necessary!
