### ISSUE TITLE
Align TileWMS and XYZ tiles?

### ISSUE THREAD

**Issue by zifix** [openlayers/openlayers#12335]
Hi,
I'm using ol from NodeJS and therefore need to download URLs manually. Now I'm trying to align a WMS service with my OSM tiles.
Given an OSM tileCoord (e.g. 0/0/0), how would I use TileWMS.tileUrlFunction to fetch the same WMS tile?
I seem to get everything except the bbox atm. For me it comes out as "...&BBOX=NaN%2CNaN%2CNaN%2CNaN" at the moment :(

Thanks
Zifix

**Comment by mike-000** [comment]
You can use the `getTileCoordExtent` method of the tile grid https://codesandbox.io/s/simple-forked-7rrrn

**Comment by zifix** [comment]
Thanks for the method to do it manually. With some liberal use of console.log inside the layer I figured out the projection was missing.
I "fixed" it this way:
```
import { PROJECTIONS } from 'ol/proj/epsg3857.js'
new TileWMS({
    /* snip */
    projection: PROJECTIONS[3]
  })
```
Is this the correct way?
