### ISSUE TITLE
FPS falls dramaticly when width of stroke of lineString is more then 1

### ISSUE THREAD

**Issue by Lamzar** [openlayers/openlayers#12350]
OL 6.5. I have a lot of lineStrings on the map (> 8000) and I use simple style function which sets only stroke color with some width:
```
var styles = {
  'LineString': [
   new ol.style.Style({
		stroke: new ol.style.Stroke({
		  color: 'green',
		  width: 4,
		})
	})
   ]
};

var styleFunction = function (feature) {
  return styles[feature.getGeometry().getType()];
};
```
The questions:
1. If I set width to 1, I have sutisfying FPS. But if I change the width to any other value, even 1.0001, FPS falls dramaticly. I prepared the sample: https://jsfiddle.net/Lamzar/36zu2oay/15/ and also attached the index.html file with this sample.
2. Does anyone know why Firefox renders lines on the map about a twice or more quickly then Chrome? The described above problem with width also takes place in Firefox, but nevertheless it handles with it with greater performance.

[index.zip](https://github.com/openlayers/openlayers/files/6532468/index.zip)

**Comment by ibrierley** [comment]
I'm wondering if this is related to Skia...I think Chrome uses that behind the scenes, apologies if wrong. I noted a similar issue with Flutter I was looking at https://github.com/flutter/flutter/issues/78543#issuecomment-809640265
