### ISSUE TITLE
Include dimensional Extent in the result of the WMSCapabilities read function

### ISSUE THREAD

**Issue by dopenguin** [openlayers/openlayers#12356]
I'd like to be able to receive information regarding the time dimension of a WMS Layer. As desribed [here under Annex C](https://portal.ogc.org/files/?artifact_id=14416), the `<Dimension>`-Tag doesn't contain valid values for the Dimension. These reside in the dimensional `<Extent>`-Tag.

When using the function `read` of the `WMSCapabilities` ("ol/format/WMSCapabilities"), the above mentioned `<Extent>`-Tag doesn't get parsed, meaning the information needs to be retrieved through different means.

**Comment by OnlineInternetPerson** [comment]
This would be a nice addition
