### ISSUE TITLE
Use Parcel 2 in /doc/tutorials/bundle.html

### ISSUE THREAD

**Issue by MartinOver2** [openlayers/openlayers#12362]
Please update the tutorial since Parcel 1 is deprecated (https://www.npmjs.com/package/parcel-bundler).
Parcel 2 works fine with openLayers: npm install --save-dev parcel

**Comment by tschaub** [comment]
This was addressed by #12492.  If you run `npx create-ol-app`, you'll get a setup that uses the latest Parcel release candidate.
