### ISSUE TITLE
Broken external links in docs

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#12360]
**Describe the bug**
The links to https://developer.mozilla.org/en-US/docs/Web/API/ImageData in https://openlayers.org/en/latest/apidoc/module-ol_source_Raster.html#~Operation are broken as %7D is being added to the url.  The problem persists despite attempts to fix in #12359.

**Comment by MoonE** [comment]
You can use markdown style links for this:
`[ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData)`
