### ISSUE TITLE
Tiledebug layer and TileImage layer with inverted y {-y}

### ISSUE THREAD

**Issue by pelord** [openlayers/openlayers#12361]
**Describe the bug**
TileDebug do not represent the inverted -y coordinate for tileimage layer. 

**To Reproduce**
1. Go to 'https://geoegl.msp.gouv.qc.ca/igo2/mtq-test/?context=tile_debug&sidenav=1&tool=mapTools' 
2. In the Network console (F12), the call made to the TileImage server do not correspond to the tile debug coordinates in Y. 
3. here the layer definition
````
TileDebug
       {
            "title": "tiledebug",
            "visible": true,
            "sourceOptions": {
                "type": "tiledebug"
            }
        },
TileImage
        {
            "baselayer: "baselayer",
            "sourceOptions": {
                "url": "/service@EPSG_3857/{z}/{x}/{-y}.png",
                "type": "xyz"
            }
        }
````

**Expected behavior**
How handle a tiledebug layer with an inverted Y coordinate ( {-y} ) without having to define a custom tilegrid?
![image](https://user-images.githubusercontent.com/7397743/119842567-c9a04480-bed4-11eb-9aee-534c2827414a.png)

**Comment by pelord** [comment]
Maybe it is a feature request....

**Comment by mike-000** [comment]
The template is effectively hardcoded into TileDebug, but you could create your own using XYZ and a custom tileLoadFunction to replace the src url with a dataUrl from a canvas https://codesandbox.io/s/simple-forked-37r37

**Comment by pelord** [comment]
I have also tried to add an property to the Tiledebug (dashY (true/false) control this.

![image](https://user-images.githubusercontent.com/7397743/119868320-e5174980-beec-11eb-90de-b3fab72ca6e1.png)

Do you think it is better to  add a property or rely on a custom tileLoadFunction  ?

**Comment by mike-000** [comment]
If there is to be a change to TileDebug it might be more flexible to call the tileUrlFunction to produce text based on either a default template or one specified in the constructor https://codesandbox.io/s/simple-forked-u3w0i
