### ISSUE TITLE
Allow custom WKT string projection parameters (BBOXSR and IMAGESR) for ImageArcGISRest sources

### ISSUE THREAD

**Issue by murdocha** [openlayers/openlayers#12377]
**Is your feature request related to a problem? Please describe.**

My problem is dealing with rendering an Esri "dynamic map image service" with custom LayerDefinitions. I'm struggling to get these layers to draw Pacific-spanning Esri service datasets across the antimeridian / 180 longitude / "dateline". By default the Esri services use the 3857 web mercator projection, and they don't support any "wrapping" across the edge meridians. I found a work around that works in the Esri REST API Export image test page, but it would require me to pass custom projection parameters. I've been able to use a WKT projection string with an alternate central meridian defined. The Esri service then sends back an image that fully crosses the antimeridian centered on wherever I wanted the image centered. The parameters in question are IMAGESR and BBOXSR. 

However, the OpenLayers implementation of the ImageArcGISRest layer source does not appear to allow a custom IMAGESR or BBOXSR. It only seems to allow passing an EPSG/SRID code to the Esri service as a parameter.

Here is the documentation that indicates that the BBOXSR and IMAGESR are set "dynamically" and can't be passed to the Esri REST service as custom parameters:
https://openlayers.org/en/latest/apidoc/module-ol_source_ImageArcGISRest-ImageArcGISRest.html
"ArcGIS Rest parameters. ... **BBOX, SIZE, BBOXSR, and IMAGESR will be set dynamically.** "

It seems you can force an alternate EPSG/SRID code to be sent as a parameter to the Esri Image Service, using the ImageArcGISRest source "projection" property, but that seems to only accept a "projection-like" object.

**Describe the solution you'd like**

I'd like to send a custom projection string (in WKT format) as an optional parameter that would override these "dynamically" set REST parameters (BBOXSR and IMAGESR). 

One approach is to first check to use custom BBOXSR and IMAGESR parameters (if present) before falling back to the default BBOXSR and IMAGESR settings derived from the "projection" optional property.
This might happen in the "getRequestUrl_" method here?
https://github.com/openlayers/openlayers/blob/de81d2b7629e4331d5455c809c51a99d57202319/src/ol/source/ImageArcGISRest.js#L239

Alternatively, if there is an work around to get an Esri dynamic map service image request to span the Pacific basin crossing the antimeridian, I'm very interested!

**Comment by mike-000** [comment]
You will need to define a custom projection in OpenLayers, so you could substitute that projection code with the WKT in the image load function

```
var projectionCode = 'customprojection';

proj4.defs(projectionCode, '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=180.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs');
register(proj4);

var regexp = new RegExp(projectionCode, 'g');

var layers = [
  new ImageLayer({
    source: new ImageArcGISRest({
      ratio: 1,
      params: {},
      url: url,
      projection: projectionCode,
      imageLoadFunction: function(image, src) {
        image.getImage().src = src.replace(regexp, encodeURIComponent(wkt))
      }
    }),
  })
];
```

**Comment by murdocha** [comment]
updated custom projection code inspired by the code sandbox linked in the associated PR, that prevents duplication in the wkt or proj4 strings.
```
        const wkt =
            'PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",' +
            'SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.017453292519943295]],' +
            'PROJECTION["Mercator_Auxiliary_Sphere"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],' +
            'PARAMETER["Central_Meridian",' + centralMeridian + '],PARAMETER["Standard_Parallel_1",0.0],PARAMETER["Auxiliary_Sphere_Type",0.0],' +
            'UNIT["Meter",1.0]]';
        const customSR = JSON.stringify({ wkt: wkt });

        // used to request an image from ArcGIS REST endpoint in custom projection
        const customMapProjectionCode = 'custom:customProjDef_' + centralMeridian.toString();
        proj4.defs(customMapProjectionCode, wkt);
        register(proj4);

        // used to reproject the map view BBOX prior to sending map image request
        const currentMapProjection = this.map.getView().getProjection();
        const customProj = new Projection({
            code: customMapProjectionCode
        });
```

**Comment by murdocha** [comment]
I'm also seeing a likely related issue with this work around.
When panning across (180 degrees longitude east or west of custom central meridian defined in the custom projection), or zooming out enough for the BBOX to intersect that custom "anti-meridian", the imageLoadFunction begins to be called repeatedly, essentially spamming the target map service endpoint... hundreds of requests if you don't stop the browser client-side or the server doesn't timeout or block too many requests.

I'm thinking that this is related to the Layer object "projection" parameter? which I'm not explicitly setting.
Working on generating a repro.

**Comment by mike-000** [comment]
Try to avoid reprojecting if possible (but it will be unavoidable if you are also using vector tiles).  If you are reprojecting you should ensure all the projections have extents set.  All spherical mercators will have the same extent relative to their central meridians, so you could set from EPSG:3857

`getProjection('customMapProjectionCode').setExtent(getProjection('EPSG:3857').getExtent())`
