### ISSUE TITLE
writeGeometry from 'ol/format/WKT' outputs coordinates in wrong order.

### ISSUE THREAD

**Issue by adjenks** [openlayers/openlayers#12390]
**Describe the bug**
I understand that openlayers likes to use a particular coordinate order, and when I create a geometry and draw it it works fine, but when I use the writeGeometry() function it should put the coordinates in the correct order. It appears to be backwards, outputt.ing long,lat instead of lat,long

**To Reproduce**
This code produced coordinates in the wrong order:
```js
wkt.writeGeometry(circular([-10,10], 1000),{
  dataProjection: 'EPSG:4326',
  featureProjection: 'EPSG:4326'
})
```

**Expected behavior**
Produce a correct wkt polygon.
To get the correct coordinates, my workaround was to manually reverse them like so:
```js
var buffcirc = circular([-10,10], 1000)
buffcirc.setCoordinates([buffcirc.getCoordinates()[0].map(c=>c.reverse())])
```
I could easily draw the circle without this reversal process because OpenLayers likes them in that order, but there should be a better way to generate the correct WKT for input into CQL or other APIs.

**Comment by mike-000** [comment]
The best way would be to define a transform between lon/lat and lat/lon definitions, for example

```
import WKT from 'ol/format/WKT';
import {circular} from 'ol/geom/Polygon'
import {Projection, addCoordinateTransforms, addProjection} from 'ol/proj';

addProjection(new Projection({
  code: 'WGS84',
  units: 'degrees'
}));

addCoordinateTransforms(
  'WGS84',
  'EPSG:4326',
  function(coordinate) { return [coordinate[1], coordinate[0]]; },
  function(coordinate) { return [coordinate[1], coordinate[0]]; }
);

const wkt = new WKT();

wkt.writeGeometry(circular([-10,10], 1000),{
  featureProjection: 'WGS84',
  dataProjection: 'EPSG:4326'
});
```

**Comment by ahocevar** [comment]
What @mike-000 suggests is the correct way to handle this. Note that OpenLayers does not have a concept of axis order, so you need to deal with that using coordinate transforms.

**Comment by adjenks** [comment]
Oh, thank you, I'm not sure how I would have found the `addCoordinateTransforms` function without being pointed in that direction.

The semantics of the code seem a bit odd to me though, because WGS84 is the reference ellipsoid for EPSG:4326, so WGS84 doesn't really have a coordinate order does it?

Either way, I think some sort of function would be nice to just flip the coordinates instead of "projecting" them at all because so many tools have different preferences on coordinate order despite the SRS definition.
