### ISSUE TITLE
Question regarding layer Visibility

### ISSUE THREAD

**Issue by cplpearce** [openlayers/openlayers#12395]
Setting a layers visibility to false currently removes all the features from the source and there seems to be no way to interact with features until the layer is visible again.  Is this the expected behavior or is there an alternative way to hide a layer and still retain the ability to interact with its features?

Loading a geojson file:
![image](https://user-images.githubusercontent.com/11462961/121409005-0174a680-c92f-11eb-90bb-34f06a381f41.png)

Iterating sources and attempting to update the features:
![image](https://user-images.githubusercontent.com/11462961/121409162-2bc66400-c92f-11eb-896f-028b3532f957.png)

Features listed under the layer source *when visible*:
![image](https://user-images.githubusercontent.com/11462961/121409583-ac856000-c92f-11eb-8e76-49362d3c76ee.png)

No features listed under the layer source *when hidden*:
![image](https://user-images.githubusercontent.com/11462961/121409850-ee160b00-c92f-11eb-8d48-904e26040e6d.png)

**Comment by mike-000** [comment]
A layer will not load automatically from a url unless it is visible, but no features are removed by calling `.setVisible(false)` after is is loaded.  A vector layer can be visible without being seen if the style is set to null as in https://openlayers.org/en/latest/examples/layer-clipping-vector.html  Any layer can be hidden beneath another opaque layer by changing its `zIndex` or by setting its order in the layer stack as in the left map in https://openlayers.org/en/latest/examples/disable-image-smoothing.html.

**Comment by cplpearce** [comment]
**A layer will not load automatically from a url unless it is visible** ah okay - so to toggle layers the style should be set to null and restored when toggled back.  

That's not what I expected and I appreciate the heads up.  Out of curiosity is that mentioned anywhere specifically or is there more docs somewhere with these caveats?
