### ISSUE TITLE
Vector tile layer wrapping regression

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#12396]
**Describe the bug**
There is a problem with vector tile layers not initially wrapping when a map opens with `multiWorld` set true..

**To Reproduce**
Compare https://openlayers.org/en/main/examples/vector-tile-selection.html with the correctly wrapping version https://openlayers.org/en/latest/examples/vector-tile-selection.html when opening on a wide screen.  In the dev version only one world is initially visible, but others can be revealed by panning or zooming out.  Looking at the deploy previews it seems this was introduced by #12364  There seems to be no problem if the vector tile layer shares a canvas with another correctly wrapped layer - comment out the osm `className` in https://codesandbox.io/s/vector-tile-info-forked-4v8l7 and the vector tile layer will also wrap correctly

**Expected behavior**
The `dev` version should wrap on opening as the `latest` version did..

**Comment by ahocevar** [comment]
Thanks for reporting this, @mik-000. Should be fixed with #12405.
