### ISSUE TITLE
Wrong WMS tiling with northing easting projections, +axis=neu workaround breaks proj4 transformation

### ISSUE THREAD

**Issue by MatAlps** [openlayers/openlayers#12406]
# The issue

It seems not possible to make openlayers & proj4 work together with northing easting projections & WMS 1.3:
* either the map does not render correctly
* either transforming coordinates from +enu -> +neu does not work

https://github.com/openlayers/openlayers/issues/11632 gives already a lot of answers (thx for that), and from what I have tried, I confirm that the issue does not happen with WMS 1.1.1, see fix attempt 3 below. 

But I understand the problem is still present for WMS 1.3, and the proposed solutions do not work: adding '+axis=neu' to the proj4 projection definition or using WKT projection definition.

Is it possible to fix the issue for WMS 1.3 in ol or proj4?

## Reproduction steps
Using ol 6.5.0 and proj4 2.7.2.
See https://github.com/MatAlps/ol_proj4_axis_inversion, and explanations below.

1. Setting up the projection, it is a copy-paste of epsg.io
    ```javascript
    import proj4 from 'proj4';
    import {register} from 'ol/proj/proj4';
  
    proj4.defs("EPSG:3035","+proj=laea +lat_0=52 +lon_0=10 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs");
    register(proj4);
    ```

1. Add Tiled layer (by default WMS 1.3)
    ```javascript
    var layers = [
    new TileLayer({
        source: new OSM(),
    }),
    new TileLayer({
            source: new TileWMS({
            url: 'https://wms.inspire.geoportail.lu/geoserver/hy/wms',
            params: {'LAYERS': 'HY.Network-BDLTC', 'TILED': true},
            serverType: 'geoserver',
            projection : 'EPSG:3035',
            // Countries have transparency, so do not fade tiles:
            transition: 0,
        }),
    }) ];
    var map = new Map({
    layers: layers,
    target: 'map',
    view: new View({
        center: [4039269.72, 2952487.51],
        zoom: 4,
        projection : 'EPSG:3035'
    }),
    });
    ```
1. Test proj4 transformation
    ```javascript
    proj4("EPSG:4326", "EPSG:3035", [5, 50])  // should be [3962799,2999719] after rounding
    ```

## Expected result
1. The layer correctly renders over the Luxembourg territory at all levels of zoom
2. The transformation gives the correct result

## Observed result
1. Failure -> when zooming in the layer renders in the atlantic, north-west of England
2. Success

# Fix attempt 1

Reading https://github.com/openlayers/openlayers/issues/11632
Add +axis=neu on the projection definition

## Observed result
1. Success --> the map correctly renders the layer for all levels of zoom!
2. Failure --> the output of the transformation has the axis inverted, [2999719, 3962799] instead of [3962799, 2999719]

# Fix attempt 2

Still reading https://github.com/openlayers/openlayers/issues/11632
Use WKT definition
```javascript
proj4.defs("EPSG:3035", 'PROJCS["ETRS89 / LAEA Europe",GEOGCS["ETRS89",DATUM["European_Terrestrial_Reference_System_1989",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6258"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4258"]],PROJECTION["Lambert_Azimuthal_Equal_Area"],PARAMETER["latitude_of_center",52],PARAMETER["longitude_of_center",10],PARAMETER["false_easting",4321000],PARAMETER["false_northing",3210000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","3035"]]');`
```
Identical observed result (wrong map, correct transformation)

# Fix attempt 3

Still reading https://github.com/openlayers/openlayers/issues/11632
Use WMS 1.1.1

--> Both works

**Comment by mike-000** [comment]
The proj4 transform results are as expected.  If you swap the axes in a proj4 definition proj4 will return the axes in that order.  For consistent x y results use OpenLayers for the transform

`var transformed = transform([5, 50], "EPSG:4326", "EPSG:3035").map(x => Math.round(x));
`
or

`var transformed = fromLonLat([5, 50], "EPSG:3035").map(x => Math.round(x));
`

**Comment by ahocevar** [comment]
OpenLayers behaves correctly in this scenario. OpenLayers always transforms without swapping axis order, so like @mike-000 suggests, if you do not want to swap axis order, use OpenLayers to do the transform for your test step (3).

The problem is really WMS v1.3, which requires that the client knows about the axis order of the used CRS. It is very hard to obtain that information. It is missing or wrong for almost all projections on epsg.io or spatialreference.org. The only source that publishes it properly is epsg.org, which is the source of the official EPSG database that servers like GeoServer use. `proj4js` did not understand these WKTs until a few minutes ago, but I just added support for them in the `wkt-parser` package that `proj4js` depends on.

My advice from #11632 is still valid - use WMS v1.1.1. Anyway, to see your example working with WMS 1.3 and the WKT def from epsg.org, I created this codesandbox: https://codesandbox.io/s/elegant-mclean-5i8wt?file=/src/index.js

**Comment by MatAlps** [comment]
Thx @ahocevar & @mike-000, for the `wkt-parser` upgrade as well.

It makes the current situation much clearer. 
To summarize I get that for northing easting projections:

| Fct \ Def source | epsg.org, wkt version 1 | espg.io, wkt or proj4js | epsg.io, proj4 +axis=neu |
| --- | --- | --- | --- |
| WMS 1.3.0 | ✔️ | ❌ | ✔️ |
| WMS 1.1.1 | ✔️ | ✔️ | ✔️ |
| proj4 transform | ❌ | ✔️ | ❌ |
| openlayers transform | ✔️ | ✔️ | ✔️ |

For
* proj4 2.7.2
* ol 6.5 (import {transform} from 'ol/proj')
* epsg.org wkt v1 https://apps.epsg.org/api/v1/CoordRefSystem/3035/export/?format=wkt&formatVersion=1 (epsg.org web portal seems to only offer wkt v2 that does not work)

**Comment by ahocevar** [comment]
Again, your ❌ for the proj4 transform comes from an incorrect assumption on your end - proj4 **does** flip axis order according to the axis definition. The OpenLayers transform does not, to avoid confusion (for good reason, as it seems).

**Comment by MatAlps** [comment]
Thx, I meant it as a compatibility matrix only.
