### ISSUE TITLE
Features floating on map in Android 4.4.2/4.0.4 webview

### ISSUE THREAD

**Issue by kobbe** [openlayers/openlayers#12411]
**Describe the bug**
Features and map not moving in sync. It is like the different layers don't move the same distance.

**To Reproduce**
1. On Android 4.4.2 or 4.0.4, use the default web browser (with default webview) or App with webview to navigate to for example https://openlayers.org/en/main/examples/earthquake-clusters.html
2. Pan or zoom in the map.
3. The background map and the features does not move at the same speed.

Firefox on 4.0.4 does not have the same problem. IE11 does not seem to suffer from the same problem on W10.

Here is a gif of the problem.
![problem](https://user-images.githubusercontent.com/4288653/122556894-5a81c000-d03c-11eb-9ce3-0f0eb0312539.gif)

**Expected behavior**
I expect the features and background map to be in sync when panning and zooming.

**Bug introduced in**
The bug is visible in all versions 6.0.0 and later. The version 5.3.0 works as expected (https://openlayers.org/en/v5.3.0/examples/earthquake-clusters.html).

I hope this is enough information since I guess it will be tricky to

**Comment by M393** [comment]
Does this also happen on current main branch? 
https://deploy-preview-12409--ol-site.netlify.app/examples/earthquake-clusters.html

**Comment by kobbe** [comment]
@M393 Unfortunately the page does not work on my Android 4.0.4, some problem with https (like many other pages with https). I can try to get hold of the Android 4.4.2 device next week and see if that can handle https better.

**Comment by mike-000** [comment]
The layers are not moving out of sync, the vector layer is at the wrong scale.  Compare the cluster locations in your image with, for example Chrome on Windows, where there are no earthquakes near northern Norway.  You may see a similar problem with https://openlayers.org/en/latest/examples/modify-features.html (I do not have any way of debugging on my old device).  A workaround may be to set the map `pixelRatio` option to 1.

**Comment by kobbe** [comment]
Good news! 

The current main branch https://deploy-preview-12409--ol-site.netlify.app/examples/earthquake-clusters.html works on Android 4.4.2.

Setting pixelRatio to 1 in OL 6.3.1 does work in android 4.4.2 so I will use this workaround until the next version of OL.

Thank you for the help with debugging!
