### ISSUE TITLE
New Version For OpenLayers

### ISSUE THREAD

**Issue by m0riya42** [openlayers/openlayers#12410]
hi, I'm Working on a project using Version 6.5. but there's a bug with Fill color of Icon which wasn't in v5.3.3:  
![fill_icon](https://user-images.githubusercontent.com/44200760/122382733-dfa0a280-cf72-11eb-8168-de1f4f3bd97f.png)

we tried to use the last updated package which solved the problem, but the version 6.5 doesn't have those changes.
I wanted to know when will you release a new version, so I can use the solved one. 
(For our project we must use an official version)
We need the new version as soon as possible.

Thank you.

**Comment by EvertEt** [comment]
https://github.com/openlayers/openlayers/issues/12404#issuecomment-862705860
