### ISSUE TITLE
ol.interaction.Select doesn't work correctly with multi option enabled

### ISSUE THREAD

**Issue by blissvisitor** [openlayers/openlayers#12419]
now ol.interaction.Select doesn't work correctly with multi option enabled 
every time I selected ,the last selected is cleared.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/16833909/122742909-07687100-d2b9-11eb-99cc-5fe89d4c9be3.png">
<img width="372" alt="image" src="https://user-images.githubusercontent.com/16833909/122743004-249d3f80-d2b9-11eb-9011-90d52cdab248.png">
<img width="362" alt="image" src="https://user-images.githubusercontent.com/16833909/122743072-37b00f80-d2b9-11eb-843c-d5188d9d60f6.png">

**Comment by mike-000** [comment]
`multi` allows overlapping features to be selected with one click.  To select multiple non-overlapping features use shift (the default `toggleCondition`) and click on each feature https://openlayers.org/en/latest/examples/select-features.html  To do that without using shift set `toggleCondition` to `always` https://codesandbox.io/s/select-features-forked-wms6s

**Comment by blissvisitor** [comment]
Thanks!you solve my problem

**Comment by blissvisitor** [comment]
> `multi` allows overlapping features to be selected with one click. To select multiple non-overlapping features use shift (the default `toggleCondition`) and click on each feature https://openlayers.org/en/latest/examples/select-features.html To do that without using shift set `toggleCondition` to `always` https://codesandbox.io/s/select-features-forked-wms6s

thankyou very much!
