### ISSUE TITLE
the Custom Circle Render Cannot be selected and dragged

### ISSUE THREAD

**Issue by pan1021** [openlayers/openlayers#12434]
the use of 'ol/style/Style' render option function to render circle feature. this circle feature add drag event but cannot work
https://codesandbox.io/s/custom-circle-render-forked-2zs26?file=/main.js

**Comment by mike-000** [comment]
There is no hit detection on the custom style.  If you add a second style (transparent fill) which supports hit detection the interaction will work https://codesandbox.io/s/custom-circle-render-forked-me1e3

**Comment by matyasbach** [comment]
Since OL 6.9 it works without the need for second style. See #12646.
