### ISSUE TITLE
More robust css

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#12439]
**Is your feature request related to a problem? Please describe.**
Would it be practical to make the css more robust and set appropriate values within the ol classes to override anything from the application or other libraries it may use which might interfere with the correct operation of the map?

**Describe the solution you'd like**
For example, an OpenLayers map should not be affected by canvas size rules needed elsewhere on the page as in https://gis.stackexchange.com/questions/401776/mis-alignment-of-gpx-data-layer-on-os-map

**Comment by ahocevar** [comment]
If you'd be able to provide a fix, it would be much appreciated.
