### ISSUE TITLE
Get rid of string enums, use union types instead

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#12432]
Our string enums, like those used for `*EventType`, are code that is redundant and only used for type checking. Instead, we could use union types that ensure types just as well, without adding payload to the build.

The easiest way to get documented event types in JSDoc while making TypeScript turn them into union types is a `@typedef` in JSDoc with a `keyof` operator in TypeScript:
```js
/**
 * @typedef {Object} MapBrowserEventTypeKeys
 * @property {string} singleclick A true single click with no dragging and no double click. Note that this
 * event is delayed by 250 ms to ensure that it is not a double click.
 * @property {string} click A click with no dragging. A double click will fire two of this.
 * @property {string} dblclick A true double click, with no dragging.
 * @property {string} pointerdrag Triggered when a pointer is dragged.
 * @property {string} pointermove Triggered when a pointer is moved. Note that on touch devices this is
 * triggered when the map is panned, so is not the same as mousemove.
 */

/**
 * @typedef {keyof MapBrowserEventTypeKeys} MapBrowserEventType
 */

/** @type {MapBrowserEventType} */
const a = 'pointerdrag';
```

See also https://blog.bam.tech/developer-news/should-you-use-enums-or-union-types-in-typescript.

**Comment by simonseyock** [comment]
I am wondering if the `*EventType.js` files could be integrated into the `*Event.js` files at that go? I'd like to look into this issue after I finished https://github.com/openlayers/openlayers/pull/12430.

**Comment by ahocevar** [comment]
@simonseyock The typedefs can definitely go into the respective `*Event.js` files when making this change.

**Comment by simonseyock** [comment]
@ahocevar I am looking into this at the moment and from the typescript perspective this is no problem. I am wondering how to include this information properly into the documentation. If I just add an `@api` tag then will; not be linked and only appear in the documentation of its own module.

I do not exactly see where the code lives that picks up the events for jsdoc and populates the `fires` properties of the doclets. Also I do not see how it is specified that, say, the class `PluggableMap` fires the `MapBrowserEventTypes`. I am not able to see that connection in the code.

**Comment by ahocevar** [comment]
There are `@fires` annotations and `@event` annotations. These connect the events to the respective classes. And there is at least one plugin (`config/jsdoc/plugins/events.cjs`) that handles them. Ideally, when getting rid of event type enums, we can also get rid of this custom event handling and use the standard mechanism that JSDoc provides. To be honest, I did not look into details yet, but I'd be happy to help once you have started with a draft pull request.

**Comment by tschaub** [comment]
I think we could avoid the `keyof` syntax and simplify or remove the `@fires` and `@event` JSDoc plugins and instead just use markdown lists and links.  See 80526e30a8650028763f532ae65bfd48f7b15fe9 for an example commit that removes the `ol/render/EventType.js` module.  That change still uses `@fires` tags, but if we migrated away from event type enums everywhere, I think it would be more straightforward just to link to the event types instead of trying to pull in the descriptions for each type (for example, the map docs would link to docs for map render event types).

![image](https://user-images.githubusercontent.com/41094/132138100-356883ac-ae6b-4d44-a718-eadff80a7bca.png)

**Comment by ahocevar** [comment]
I like the direction you started in 80526e3, @tschaub!

**Comment by simonseyock** [comment]
I like the idea of not using `keyof` and `@fires`. It will probably cause less issues with typing generation. Removing the jsdoc plugins is great as well, it makes it easier to find where the actual documentation texts are. Also it reduces the dependency on jsdoc, which is not developed much anymore.
