### ISSUE TITLE
User/ developer friendly conversion of units 

### ISSUE THREAD

**Issue by abhijitgujar86** [openlayers/openlayers#12440]
**Use case / problem statement :** 
I was using measure tools from  here https://openlayers.org/en/latest/examples/measure.html , but  i ran into issue when i switched the projection to EPSG:4326, getLength()  and getArea() return in degree , while this is  technically correct, practically this units are never used. so I think its will good and useful for everyone if there is and internal conversion of units as per set by user.

**possible solution you'd like**
What i suggest is that we can keep an configuration while setting  view for example 

```
view = new View({ 
        projection : "EPSG:4326" ,
        units: 'meter'
        center: center,
        zoom: 10
        });
```
units  can be meter, feet , kilometre, miles yard etc . 

so what ever the projection default units may be when returning any measurements such as  getLength(), getArea() , the function will check for units and convert it then return it.

**Comment by mike-000** [comment]
The ol/sphere `getLength()` and `getArea()` methods will assume the geometry is EPSG:3857 unless you specify the projection in the options as in https://codesandbox.io/s/measure-forked-7eo2k The methods are not aware of the view projection by default (an application may have no map, or multiple maps using different projections). Note that EPSG:3857 projection units are not the same as meters on the ground (except at the equator) so defaulting to EPSG:3857 with geometry in degrees will give a meaningless result, not a result in degrees.
