### ISSUE TITLE
MGRS projection for Openlayers 

### ISSUE THREAD

**Issue by Kobrairaq** [openlayers/openlayers#12452]
Im trying to convert LatLon to MGRS for the mouse position control can anyone help me out here thnx .

**Comment by ahocevar** [comment]
You could use https://npmjs.com/package/mgrs.

**Comment by Kobrairaq** [comment]
> You could use https://npmjs.com/package/mgrs.

Can you please provide an example ?

**Comment by mike-000** [comment]
Use the mgrs `forward` method instead of `createStringXY` https://codesandbox.io/s/mouse-position-forked-x8tdj

**Comment by Kobrairaq** [comment]
> Use the mgrs `forward` method instead of `createStringXY` https://codesandbox.io/s/mouse-position-forked-x8tdj

Many thnx for you mate that is really helped 😃.
