### ISSUE TITLE
Unlisten doesn't work

### ISSUE THREAD

**Issue by almat65** [openlayers/openlayers#12456]
**Describe the bug**
Hi, i'm developping a swipe-tool and when I switch-off my swipe, listener stay in a layer and continues to do his job. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/84472530/124021454-9102f780-d9b9-11eb-9a33-5e2839044080.png) 
Line 8891 is newer executed. something is preventing to get in .un('prerender'...

![image](https://user-images.githubusercontent.com/84472530/124022201-7e3cf280-d9ba-11eb-865c-34ae21c9523b.png)
functions for move a swipe.

![image](https://user-images.githubusercontent.com/84472530/124022252-901e9580-d9ba-11eb-8589-9ca773ed6ef5.png)
prerender function. I've tried to put a listener inside, but I've had too much listeners, for each event. so i've met it in displaySwipe();

![image](https://user-images.githubusercontent.com/84472530/124021986-38802a00-d9ba-11eb-8b7f-c2c6c7cfbdf3.png)
un exemple, when I turn off my swipe, the layers stays swiped. 

**Expected behavior**
I want to unsubscribe the listeners.

**Comment by MoonE** [comment]
You need to pass the same function object to the `un` that you used in `on`.

```js
  onPrerender: function (event) => {
    event.context.restore();
    event.context.save();
  },
  displaySwipe: function () {
    this.layers.map((layer) => layer.on('prerender', this.onPrerender));
  },
  displaySwipeOff: function () {
    this.layers.map((layyer) => layer.un('prerender', this.onPrerender));
  },

**Comment by almat65** [comment]
@MoonE it's working! thank you so much! have a nice day!!!
