### ISSUE TITLE
Missing method "setAngle" in class ol.style.RegularShape

### ISSUE THREAD

**Issue by Apkovy** [openlayers/openlayers#12451]
In constructor of class "ol.style.RegularShape" there is an options property "angle" for which there is no corresponding set method like it is usual for other attributes.

Is it missing or just not possible by design?

Thanks.

**Comment by mike-000** [comment]
With the exception of `setRadius` for `ol/style/Circle` set methods exist only for properties which can be dynamically applied to the image in a style function without drawing a new canvas for the image.  `angle` is used in the drawing (`rotation` of the subsequent image can be used dynamically).
