### ISSUE TITLE
import {Map} from 'ol' hijacking Map xx = new Map();

### ISSUE THREAD

**Issue by treetrunkz** [openlayers/openlayers#12454]
**Describe the bug**
This is a pretty easy bug to describe, I am using typescript and creating an interactive map. I must use Map and Map in the same file.

**To Reproduce**
1. import Map from OpenLayers, import map object from javascript

**Expected behavior**
The Map openLayers object will override the datastructure

**Comment by EvertEt** [comment]
You can rename the import 
`import { Map as OlMap } from "ol";`
or `import OlMap from "ol/Map";`

**Comment by treetrunkz** [comment]
Thank you!
