### ISSUE TITLE
Text style markers are way too tall when the body is a flex container

### ISSUE THREAD

**Issue by michel404** [openlayers/openlayers#12460]
**Describe the bug**
Points that are shown with text labels on the map may not have the correct size. This is most apparent when you use `backgroundFill` or `backgroundStroke` and it also messes up the decluttering algorithm.

**To Reproduce**
1. Make a map with a vector layer and some points
2. Style the layer with a Text style and set the `backgroundFill`
3. In the CSS of the page, say something like `body { display: flex; }`
4. See the labels being super tall

See this https://codesandbox.io/s/tigrk
![Screenshot from 2021-07-02 11-13-40](https://user-images.githubusercontent.com/3996921/124251870-aba6af00-db26-11eb-8e41-d42041e2075e.png)

Using OL 6.5.0
Chrome 91.0.4472.114
Ubuntu 20.04.2 LTS

**Expected behavior**
The labels too be shown with a background no taller than the text itself.

**Comment by M393** [comment]
This should already be fixed by #12214

**Comment by michel404** [comment]
I did a little more digging and found #12213.
