### ISSUE TITLE
Modify an icon color

### ISSUE THREAD

**Issue by ineeve** [openlayers/openlayers#12462]
**Is your feature request related to a problem? Please describe.**
I would like to change the color of an Icon by using a color-picker. Currently, I'm forced to create a new Icon, which reloads the source, and the Icon flashes on the map.

**Describe the solution you'd like**
I want a setter for the icon color `Icon.setColor()`

**Comment by MoonE** [comment]
Use `img` instead of `src`.
This way the image is not reloaded.
https://codesandbox.io/s/image-color-change-zj5zh?file=/main.js:530-589
https://openlayers.org/en/main/apidoc/module-ol_style_Icon-Icon.html

**Comment by ineeve** [comment]
Hi @MoonE, thank you for the quick response and working example. Your solution worked perfectly.
The only thing I did differently was to set the style directly on input received, instead of calling `vectorLayer.changed();`. I did this because I noticed that `vectorLayer.changed()` took some time to refresh the Icon color (~500ms)
