### ISSUE TITLE
Copy to clipboard Mouse Coordinate

### ISSUE THREAD

**Issue by Kobrairaq** [openlayers/openlayers#12465]
is there a way to copy the coordinates from the ol.mouse.position div ?

**Comment by MoonE** [comment]
You can implement it like this, `mouse-position` is the id of the node which contains the coordinate text.
```js
function copyToClipboard(message) {
    const textArea = document.createElement("textarea");
    textArea.value = message;
    textArea.style.opacity = "0";
    document.body.appendChild(textArea);
    textArea.select();

    try {
        const successful = document.execCommand('copy');
        const msg = successful ? 'successful' : 'unsuccessful';
        alert('Copying text command was ' + msg);
    } catch (err) {
        alert('Unable to copy value , error : ' + err.message);
    }

    document.body.removeChild(textArea);
}
document.addEventListener('keydown', function (e) {
  if (e.ctrlKey && e.altKey && e.key === 'c') {
    e.preventDefault();
    const node = document.querySelector('#mouse-position');
    copyToClipboard(node.textContent);
  }
});
```
This will copy the text when you press `Ctrl + Alt + c`.
https://stackoverflow.com/a/67619069/14874242

**Comment by Kobrairaq** [comment]
> You can implement it like this, `mouse-position` is the id of the node which contains the coordinate text.
> 
> ```js
> function copyToClipboard(message) {
>     const textArea = document.createElement("textarea");
>     textArea.value = message;
>     textArea.style.opacity = "0";
>     document.body.appendChild(textArea);
>     textArea.select();
> 
>     try {
>         const successful = document.execCommand('copy');
>         const msg = successful ? 'successful' : 'unsuccessful';
>         alert('Copying text command was ' + msg);
>     } catch (err) {
>         alert('Unable to copy value , error : ' + err.message);
>     }
> 
>     document.body.removeChild(textArea);
> }
> document.addEventListener('keydown', function (e) {
>   if (e.ctrlKey && e.altKey && e.key === 'c') {
>     e.preventDefault();
>     const node = document.querySelector('#mouse-position');
>     copyToClipboard(node.textContent);
>   }
> });
> ```
> 
> This will copy the text when you press `Ctrl + Alt + c`.
> https://stackoverflow.com/a/67619069/14874242

thank you it's work like a pie !
