### ISSUE TITLE
Circle's animation jitter

### ISSUE THREAD

**Issue by piotr-przebieracz** [openlayers/openlayers#12461]
Recently we have updated OpenLayers from version 4.6.5 to 6.5.

In OpenLayers 4.6.5 we used `snapToPixel` option set to false for `ol.style.Circle` for "accurate" rendering mode during the animation to prevent noticable jitter. This phenomenon was also described in the documentation for the version 4.6.5:

> Using true allows for "sharp" rendering (no blur), while using false allows for "accurate" rendering. Note that accuracy is important if the circle's position is animated. Without it, the circle may jitter noticeably. Default value is true.

Unfortunately, this parameter has been removed in version 5.2.0, because it should be no longer needed according to the upgrade notes:

> The renderer now snaps to integer pixels when no interaction or animation is running to get crisp rendering. During interaction or animation, it does not snap to integer pixels to avoid jitter.

However, when we compare the same animation from version 4.6.5 to the animation from version 6.5 we can see the difference in rendering circle's animation which leads to the visible jitter (it is most visible at the end of the animation when the circle's diameter is the greatest). We prepared also a sample video with animation comparison:
https://www.youtube.com/watch?v=XGZdVtwdHMA

We are wondering if this change is related to some kind of a change in how snapping to pixels work right now? Is there anything we can do to make this animation smoother?

**Comment by ahocevar** [comment]
During each step of your animation, you could set `frameState.animate = true` to indicate that you're running an animation, and then pixel snapping will be turned off.

**Comment by piotr-przebieracz** [comment]
Thank you for your answer @ahocevar!

I tried experimenting with setting `frameState.animate` value to `true` based on the [Custom Animation example](https://openlayers.org/en/latest/examples/feature-animation.html) available on the project's page. However, I don't really think that this parameter affects the animation in any way (at least in the case of a circle style). What's more, I am pretty sure that the circle's jitter is also visible on the page with already mentioned Custom Animation example (the issue may be slightly less pronounced due to the smaller circle's width).

The second thing is that in our application we are animating features by using `StyleFunction` directly. It is most convenient for us since we have one place for all the styles, we can synchronize multiple animations for features and we have a direct access to the currently animated `Feature` object. Assuming `frameState.animate` property is working properly - is there any possibility to access current render frame state while using `StyleFunction`?

**Comment by ahocevar** [comment]
@piotr-przebieracz I was wrong about `frameState.animate`, so please scratch that. @MoonE is working on a fix, see #12467.
