### ISSUE TITLE
Openlayers Example 'Vector Tile Selection' is not work.

### ISSUE THREAD

**Issue by juner** [openlayers/openlayers#12477]
**Describe the bug**
Openlayers Example `Vector Tile Selection` is not work.
https://openlayers.org/en/latest/examples/vector-tile-selection.html

**To Reproduce**
1.  Open this page with the latest chrome, firefox or edge. 

**Expected behavior**
A CORS error occurs and the pbf file cannot be read. 

ahocevar.com is not work? (Error 502

**Comment by jipexu** [comment]
yes error 502 ... @ 7h44 ...

**Comment by ahocevar** [comment]
The vector tiles server was down. Fixed now.
