### ISSUE TITLE
how to add ipsrv client url image in zoomify

### ISSUE THREAD

**Issue by Mahesh21Virim** [openlayers/openlayers#12478]
Hello , 
  i am doing thing in which i was setup ipsrv server and with the help of this i was get http://localhost/fcgi-bin/iipsrv.fcgi?IIIF=/var/www/html/sample1.tif/info.json  this url but when i adding this url in my openlayer project  so its does not working 
please help me to resolve this or suggest any other way so i can add  my custom image in open layer zoomify.

const zoomifyUrl = 'http://localhost/fcgi-bin/iipsrv.fcgi?IIIF=/var/www/html/sample1.tif/';

**Comment by mike-000** [comment]
I cannot see the content of your localhost, but that looks like an IIIF source as in https://openlayers.org/en/main/examples/iiif.html

**Comment by Mahesh21Virim** [comment]
Hello milke Thanks for your feedback   , 
 i am doing same thing mention by you in given IIIF source but in which 
 my link don't working please once look screen shot 

in this screen shot when  i adding my ipsrv link then it  giving error  
"can not read data from url"

![Screenshot from 2021-07-06 18-55-54](https://user-images.githubusercontent.com/71004457/124608672-869a9f00-de8c-11eb-9523-2df84d98844c.png)

this screen shot include my data from ipsrv link 
![Screenshot from 2021-07-06 18-54-47](https://user-images.githubusercontent.com/71004457/124609006-de390a80-de8c-11eb-8ea5-3269215c4d47.png)

please correct me where i  wrong your feeback will be appreciate

**Comment by mike-000** [comment]
CORS access is needed to read data on your localhost from another domain.  You must either enable CORS on your localhost or copy the example to your localhost.

**Comment by Mahesh21Virim** [comment]
Thanks mike , 
issue resolved
