### ISSUE TITLE
Hi Sir.Can next version support dem data ,or 2.5D view？ if not ，in next next version,do you have plan to support this？ hope to get your reply!thanks😜

### ISSUE THREAD

**Issue by abigstupidbear** [openlayers/openlayers#12479]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by mike-000** [comment]
The use of DEM data is supported:
https://openlayers.org/en/main/examples/sea-level.html
https://openlayers.org/en/main/examples/disable-image-smoothing.html
https://openlayers.org/en/main/examples/shaded-relief.html

For extrusion support see #12193
