### ISSUE TITLE
Can't run any test

### ISSUE THREAD

**Issue by Razi91** [openlayers/openlayers#12486]
**Describe the bug**
Can't run locally any `test-browser`

**To Reproduce**
Clone repository, `npm install`, then `npm test`. Tested on node 10 and 14.

**Expected behavior**
Tests should work. It seems there are some problems with `ol-mapbox-style` package.

OS: KDE Neon (Linux 5.8)
Node versions: 10 and 14.

logs: https://pastebin.com/gVum8VNL

**Comment by ahocevar** [comment]
With node 10, our build environment does not work. With node 16, everything should work fine. Anyway, I updated `ol-mapbox-style` to also use `"type": "module"` in the package, and that makes it work with node 14 too. So #12489 fixes this issue.

**Comment by Razi91** [comment]
After those merges works fine, thanks
