### ISSUE TITLE
MousePosition Control: Allow setting empty string if coordiante is undefined

### ISSUE THREAD

**Issue by JakobMiksch** [openlayers/openlayers#12482]
MousePosition Control:
- [Docs v4.6.5](https://openlayers.org/en/v4.6.5/apidoc/ol.control.MousePosition.html)
- [Docs v6.5.0](https://openlayers.org/en/v6.5.0/apidoc/module-ol_control_MousePosition-MousePosition.html)

**Is your feature request related to a problem? Please describe.**
I upgraded an application from OL4 to OL6 and discovered the following: In OL4 the default value for an undefined coordinate was an empty string. in OL6 the default value is a whitespace. This is a problem for me, because my application relies on having an empty string when the coordinate is undefined. 

--> the problem is that in OL6 it does not seem to be possible to set an empty string via `undefinedHTML`, because it recognizes an empty string as "falsy" value. This causes the return of the last rendered position, which is not always desired.

**Describe the solution you'd like**
An option to make it possible to get an empty string in case the coordinate is undefined.

**Comment by ahocevar** [comment]
It should be straightforward to change the code to distinguish between `''` and `undefined` or `false`. Would you be able to create a pull request, @JakobMiksch?

**Comment by JakobMiksch** [comment]
@ahocevar yes, I will try in the next time.

**Comment by tschaub** [comment]
After #12491, if you want to render an empty string, use `placeholder: ''` with the mouse position control.  The `undefinedHTML` option is now deprecated and will work in the same way it did in the previous release (not rendering an empty string).
