### ISSUE TITLE
🍻  Here's to the future of OpenLayers!

### ISSUE THREAD

**Issue by jcimoch** [openlayers/openlayers#12490]
Hi, I have big project written in leaflet.js but at some point leaflet capabilities are very limited and I started looking for alternative that has better developer support and more active development happening in general. I found 2 options:
- Mapbox gl v2 (unfortunately not open source and paid)
- OpenLayers 

Does this project has some active sponsoring? How many contributors work on this project full time? 
How do you estimate the future of this library in one or two years? 
Also how would you compare it to leaflet or mapbox gl at current state? 

Thanks in advance for some feedback.

**Comment by jipexu** [comment]
Hi
To answer to one of your question
How do you estimate the future of this library in one or two years?
 
With a first release on 22 Jun 2006 it's already 15 years of life for this project ... and i see any reason to think that it will be stop soon ... a 15 years old  project means that this project as follow the languages evolutions and means that the dev team has hard work for this and continue !...

The core team will answer better than me but i just give my opinion and my hope too ...

**Comment by tschaub** [comment]
Thanks for your interest in the project, @jcimoch.  I agree with @jipexu and don't see any reason OpenLayers won't continue to be a solid choice for mapping applications.

Regarding project sponsorship, we are grateful to the folks who make contributions through https://opencollective.com/openlayers or https://github.com/sponsors/openlayers.  As you can see there, the annual budget wouldn't cover any significant development time, but we have in the past used such funds to offset costs of development sprints.

The project has also seen concentrated periods of funded development in the past.  These are typically for a specific feature and aren't necessarily the sort of thing that contributes to the long-term sustainability of the project.

If you can choose a library based on existing features, I think that makes a solid basis for a decision.  If you anticipate needing additional features developed to meet your application needs, OpenLayers has proven to be a flexible foundation, and there are a good number of people with the experience necessary to help develop that functionality – though nobody should expect that there are existing developers being paid to do this sort of thing for free.

If you anticipate needing additional features developed and you would like to make those contributions yourself, your contributions would be welcome and we can likely help steer you in the right direction (assuming you open an issue describing what you are after etc.).
