### ISSUE TITLE
Geometry disappear and no show in openlayer map

### ISSUE THREAD

**Issue by jw1996** [openlayers/openlayers#12496]
**Describe the bug**
I have a really weird behavior when I add polygon on the map. I cope the code from https://openlayers.org/en/latest/examples/geojson.html  

What I did is basically add three different sizes polygons to the map. However three polygons have three behavior .
1. one appears normally  (I put a //beijing comment right before the data for this polygon)
2. one disappear after zoom in  (I put a //ocean comment right before the data for this polygon)
3. one never shows up  (I put a //seattlecomment right before the data for this polygon)

**To Reproduce**
copy the code below and put that in any openlayer app 
```js
import "ol/ol.css";
import Circle from "ol/geom/Circle";
import Feature from "ol/Feature";
import GeoJSON from "ol/format/GeoJSON";
import Map from "ol/Map";
import View from "ol/View";
import { Circle as CircleStyle, Fill, Stroke, Style } from "ol/style";
import { OSM, Vector as VectorSource } from "ol/source";
import { Tile as TileLayer, Vector as VectorLayer } from "ol/layer";
import { Polygon } from "ol/geom";

var geojsonObject = {
  type: "FeatureCollection",
  crs: {
    type: "name",
    properties: {
      name: "EPSG:3857",
    },
  },
  features: [
    {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [0, 0],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [4e6, -2e6],
          [8e6, 2e6],
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "LineString",
        coordinates: [
          [4e6, 2e6],
          [8e6, -2e6],
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "Polygon",
        coordinates: [
          [
            [-5e6, -1e6],
            [-4e6, 1e6],
            [-3e6, -1e6],
          ],
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "MultiLineString",
        coordinates: [
          [
            [-1e6, -7.5e5],
            [-1e6, 7.5e5],
          ],
          [
            [1e6, -7.5e5],
            [1e6, 7.5e5],
          ],
          [
            [-7.5e5, -1e6],
            [7.5e5, -1e6],
          ],
          [
            [-7.5e5, 1e6],
            [7.5e5, 1e6],
          ],
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "MultiPolygon",
        coordinates: [
          [
            [
              [-5e6, 6e6],
              [-5e6, 8e6],
              [-3e6, 8e6],
              [-3e6, 6e6],
            ],
          ],
          [
            // ocean
            [
              [24450065.111636, 5579291.568592],
              [25448026.952927, 5364044.896941],
              [24816962.847405, 4507950.180147],
            ],
          ],
          [
            //beijing
            [
              [12956472.811422, 4853889.241058],
              [12956636.434435, 4853874.909115],
              [12956580.300993, 4853831.913287],
            ],
          ],
          [
            //seattle
            [
              [26455839.616239, 6042958.582169],
              [26457148.600348, 6042949.027541],
              [26456919.289263, 6041439.396232],
            ],
          ],
          [
            [
              [1e6, 6e6],
              [1e6, 8e6],
              [3e6, 8e6],
              [3e6, 6e6],
            ],
          ],
        ],
      },
    },
    {
      type: "Feature",
      geometry: {
        type: "GeometryCollection",
        geometries: [
          {
            type: "LineString",
            coordinates: [
              [-5e6, -5e6],
              [0, -5e6],
            ],
          },
          {
            type: "Point",
            coordinates: [4e6, -5e6],
          },
          {
            type: "Polygon",
            coordinates: [
              [
                [1e6, -6e6],
                [2e6, -4e6],
                [3e6, -6e6],
              ],
            ],
          },
        ],
      },
    },
  ],
};

const vectorSource = new VectorSource({
  features: new GeoJSON().readFeatures(geojsonObject),
});

var GEOLayer = new VectorLayer({
  source: vectorSource,
  //style: styleFunction,
});

const map = new Map({
  target: "map",
  layers: [
    new TileLayer({
      source: new OSM(),
    }),
  ],
  view: new View({
    center: [0, 0],
    zoom: 2,
  }),
});

map.addLayer(GEOLayer);
```

**Expected behavior**
Three polygon should all appear and will not disappear when I zoom in/out

**Comment by jw1996** [comment]
an update, I am getting coordinates using this website(https://epsg.io/map#srs=3857&x=-27118477.588921&y=4854178.865736&z=18&layer=streets)

I do not know why when I click the same geo location, their EPSG:3857 coordinate changes. So I have a new geometry that doesn't show on the openlayer map. 

here is the data for the polygon:
           [    [-27118496.698178, 4854234.999178],
                [-27118438.773243, 4854221.264400],
                [-27118477.588921, 4854178.865736]  ]

**Comment by ahocevar** [comment]
Your GeoJSON polygons are invalid. The first vertex needs to be repeated as last vertex, e.g.
```json
[//seattle
[
[26455839.616239, 6042958.582169],
[26457148.600348, 6042949.027541],
[26456919.289263, 6041439.396232],
[26455839.616239, 6042958.582169]
]
```

**Comment by jw1996** [comment]
> Your GeoJSON polygons are invalid. The first vertex needs to be repeated as last vertex, e.g.
> 
> ```json
> [
> [26455839.616239, 6042958.582169],
> [26457148.600348, 6042949.027541],
> [26456919.289263, 6041439.396232],
> [26455839.616239, 6042958.582169]
> ]
> ```

Hi Thanks for the reply.
I do not think that is the issue for the following reasons

1.                       [1e6, 6e6],
                          [1e6, 8e6],
                          [3e6, 8e6],
                          [3e6, 6e6]
Here is one of the polygon in the link (https://openlayers.org/en/latest/examples/geojson.html). The first vertex is not repeated as the last vertex. 

2.
Even if I repeated the first vertex it still not working. 

All the coordinates are obtained from the link (https://epsg.io/map#srs=3857&x=26456212.246752&y=6042203.766515&z=13&layer=streets)


I would really appreciate it if you can help with it.

**Comment by MoonE** [comment]
Your coordinates should not exceed the projection extent, for EPSG:3857 that is `-20037508.342789244` and `20037508.342789244` for both x and y.
Instead of 
```js
            // ocean
            [
              [24450065.111636, 5579291.568592],
              [25448026.952927, 5364044.896941],
              [24816962.847405, 4507950.180147],
            ],
```
it should be 
```js
            // ocean
            [
              [-15624951.57394249, 5579291.568592002],
              [-14626989.732651485, 5364044.896940996],
              [-15258053.83817349, 4507950.180147001],
              [-15624951.57394249, 5579291.568592002]
            ] 
```

**Comment by jw1996** [comment]
> 7508

Thanks for the help. I have been struggle with this for a week. One more question, I try to grab coordinates using this website(https://epsg.io/map#srs=3857&x=0.000000&y=-0.000000&z=1&layer=streets) It usually gave me coordinate that is out of the range of project extent.  I also try to use some thing like transform(coordinates[i],'EPSG:4326', 'EPSG:3857') to avoid manually have the coordinates out of project extent, however it does not work as well. 

What will be a good way to grad some coordinates that will not exceed the project extent

**Comment by MoonE** [comment]
This should do:
```js
const wrapEpsg3857 = (c) => {
  c[0] = c[0] % 40075016.68557849;
  if (c[0] < -20037508.342789244) {
    c[0] += 40075016.68557849
  }
  return c;
}

console.log(
  [
    [24450065.111636, 5579291.568592],
    [25448026.952927, 5364044.896941],
    [24816962.847405, 4507950.180147],
    [24450065.111636, 5579291.568592],
  ].map(wrapEpsg3857)
);
```

**Comment by jw1996** [comment]
> ```js
> const wrapEpsg3857 = (c) => {
>   c[0] = c[0] % 40075016.68557849;
>   if (c[0] < -20037508.342789244) {
>     c[0] += 40075016.68557849
>   }
>   return c;
> }
> ```

So helpful!!!!!!!!!!!!! Really appreciate your help!
