### ISSUE TITLE
Typings bug in PluggableMap.setTarget()

### ISSUE THREAD

**Issue by jumpinjackie** [openlayers/openlayers#12504]
**Describe the bug**

The following code sample doesn't compile due to an incorrect signature of `setTarget` on `PluggableMap`

```
import Map from 'ol/Map';

const map = new Map({ ... });
map.setTarget(undefined); // <=== TS2345: Argument of type 'undefined' is not assignable to parameter of type 'string | HTMLElement'
```

**To Reproduce**

1. Install `ol` version `6.6.0`
2. Try to compile the above code fragment with `tsc`

**Expected behavior**

I was expecting the `d.ts` of `PluggableMap` to have this signature for `setTarget`

```
PluggableMap.setTarget(target: string | HTMLElement | undefined): void
```

But the signature is actually

```
PluggableMap.setTarget(target: string | HTMLElement): void
```

I'm not up to speed with how `d.ts` files are generated for `6.6.0` but I'm guessing it is not picking up the ` | undefined` that is already in the JSDoc for this method.

**Comment by ahocevar** [comment]
Thanks @jumpinjackie for reporting this. Will be fixed with #12505.

**Comment by jumpinjackie** [comment]
Is that PR right? Are we no longer allowed to pass `undefined` or `null` to `setTarget` ?

**Comment by ahocevar** [comment]
@jumpinjackie The new type means that you can pass `undefined` (equivalent to passing nothing). And passing `null` was never intended, but not caught because OpenLayers has `strict: false` in the TypeScript configuration (and also works in applications that have set that).
