### ISSUE TITLE
The use of async/await on events callbacks

### ISSUE THREAD

**Issue by digoburigo** [openlayers/openlayers#12508]
**Is your feature request related to a problem? Please describe.**
When trying to use async/await in the new version 6.6.0 in events callbacks there is a type that prevents the use of that.

**Describe the solution you'd like**
I would like that in the types definition be able to return `Promise<void>` if is possible

![image](https://user-images.githubusercontent.com/28462822/125336611-618eac00-e324-11eb-8693-281c51ac04ab.png)

**Comment by MoonE** [comment]
I don't think it makes sense to use async here, the event callback expects a `boolean|void` as return type and with async it would return a Promise instead, which will be discarded.

**Comment by ahocevar** [comment]
Will be fixed with #12509.
