### ISSUE TITLE
ol.interaction.DragBox Render does not work in latest openlayers

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#12510]
Before I had code like below.  This does not work in latest Openlayers.  **this.boxInteraction.box_** is undefined

```
/* Flag indicating whether the postcompose listener should raw the "mask" on the map. */
this.drawMask = false;

/* Create a drag box interaction that sets drawMask to true n "boxstart" and sets drawMask to false on "boxend". */
this.boxInteraction = new ol.interaction.DragBox({
	condition: ol.events.condition.shiftKeyOnly,
	className: 'ol-zoombox'
});

this.boxInteraction.on('boxstart', function (e) {
	me.drawMask = true;
});
this.boxInteraction.on('boxend', function (e) {
	me.drawMask = false;
	var map = me.map;
	var view = me.map.getView();
	var extent = e.target.getGeometry().getExtent();
	var size = map.getSize();

	var resolution = view.getConstrainedResolution(view.getResolutionForExtent(extent, size));

	var center = ol.extent.getCenter(extent);
	if (view.constrainCenter && typeof view.constrainCenter !== 'undefined') center = view.constrainCenter(center);

	view.animate({
		resolution: resolution,
		center: center,
		duration: 200,
		easing: ol.easing.easeOut
	});
});
/* ****** ERROR ON LINE BELOW ****** */
if (typeof Object.getPrototypeOf(this.boxInteraction.box_) === 'undefined') {
	Object.setPrototypeOf(this.boxInteraction.box_, Object.getOwnPropertyNames(Object.getPrototypeOf(this.boxInteraction.box_)));
}
Object.getPrototypeOf(this.boxInteraction.box_).render_ = function () {
	var startPixel = this.startPixel_;
	var endPixel = this.endPixel_;
	var px = 'px';
	var style = this.element_.style;
	style.left = Math.min(startPixel[0], endPixel[0]) + px;
	style.top = Math.min(startPixel[1], endPixel[1]) + px;
	style.width = Math.abs(endPixel[0] - startPixel[0]) + px;
	style.height = Math.abs(endPixel[1] - startPixel[1]) + px;
	if (this.map_ && this.startPixel_ && this.endPixel_) {
		this.map_.render();
	}
};
```

**Comment by ahocevar** [comment]
You are relying on private, undocumented members here (`box_`, `map_`). We now mangle these names when creating the legacy build to decrease the package size. Please only interact with OpenLayers through the [API](https://openlayers.org/en/latest/apidoc).

I'm sure what you are trying to achieve can be done through the API. If not, you can raise a feature request. When your request is accepted, you can also submit a pull request to implement the desired functionality.

**Comment by 1Map** [comment]
Thanks, question now is: How can I extend the class to make use of box_?  I want to override the box_.render_

**Comment by ahocevar** [comment]
As far as I can tell, the only thing you change compared to the default implementation, is the addition of
```js
if (this.map_ && this.startPixel_ && this.endPixel_) {
  this.map_.render();
}
```
So my question is: what is the rationale behind this? If you just want to re-render the map when the user drags a box you can achieve the same by registering a `pointerdrag` listener on the map.

**Comment by 1Map** [comment]
Have a look at my sample above.  I need to override the box_.render_ for the ol.interaction.DragBox as I need custom styling done where I fill the outside of the box beging dragged with a mask like attached image shows:

![image](https://user-images.githubusercontent.com/1152458/125620835-5e02bc38-dac1-44ec-aa99-250494cedd37.png)

**Comment by ahocevar** [comment]
Like I thought. This can easily be done through the API. Something like this:
```js
const osm = new TileLayer({
  source: new OSM()
});
const map = new Map({
  // ...
});
const dragBox = new DragBox();
map.addInteraction(dragBox);
let box;
dragBox.on(['boxstart', 'boxdrag'], () => {
  box = dragBox.getGeometry();
  map.render();
});
dragBox.on(['boxcancel', 'boxend'], () => {
  box = undefined;
  map.render();
});
```
Now in the postrender (or whatever) function that draws your max, you can use the `box` geometry as inner ring of the mask polygon (or whatever way you choose to draw the mask).

**Comment by 1Map** [comment]
Thanks.  Ok, I did manage to get the mask part working.  The problem is that my Geometry should be a circle, not a box.  In this case I do want access to the private box_ as I need to change the geometry from box to circle.  The ol.interaction.DragBox do not have a setGeometry(), only a getGeometry(), so I cannot alter the drag box from a box to a circle.

I did try with:

`this.setGeometry(circlePoly);`

but it gives an error (as expected) because of no setGeometry() to override the geometry.

My code as follow:

```
			this.circleInteraction.on('boxdrag', function (e) {
				var geomExtent = this.getGeometry().getExtent();
				var mouseCoord = e.coordinate;
				var centerCoord;
				if (mouseCoord[0] === geomExtent[0] && mouseCoord[1] === geomExtent[1]) {
					centerCoord = [geomExtent[2], geomExtent[3]];
				} else {
					centerCoord = [geomExtent[0], geomExtent[1]];
				}
				centerCoord = ol.proj.transform(centerCoord, 'EPSG:3857', 'EPSG:4326');
				mouseCoord = ol.proj.transform(mouseCoord, 'EPSG:3857', 'EPSG:4326');
				var distance;
				var circlePoly;
				if (ol.Sphere && typeof ol.Sphere !== 'undefined') {
					var wgs84Sphere = new ol.Sphere(6378137);
					distance = wgs84Sphere.haversineDistance(centerCoord, mouseCoord);
					this.distance_ = distance;
					// eslint-disable-next-line new-cap
					circlePoly = new ol.geom.Polygon.circular(wgs84Sphere, centerCoord, distance, 360);
				} else {
					distance = ol.sphere.getDistance(centerCoord, mouseCoord);
					this.distance_ = distance;
					// eslint-disable-next-line new-cap
					circlePoly = new ol.geom.Polygon.circular(centerCoord, distance, 360);
				}
				circlePoly = circlePoly.transform('EPSG:4326', 'EPSG:3857');
				this.setGeometry(circlePoly);
				me.map.render();
			});
```

**Comment by ahocevar** [comment]
This is a contradiction to your initial description. If you're using the `DragBox` interaction for drawing a `Circle`, it seems to me you are using the wrong tool. The DragBox draws a box using a DOM element and CSS. It cannot draw a circle. And it never could. Also, your screenshot above shows a box, not a circle.

**Comment by 1Map** [comment]
Yes, the screenshot was when we were sorting out the mask problem.  The Circle was another example of overriding the private properties in the Openlayers Classes.  The fact is that there are so many examples where the private properties needs to be override.  Another example is where we need to get all the nullGeometryFeatures from a layer source:
source.nullGeometryFeatures_

Now, because nullGeometryFeatures_ is private, there is no way to just read it, except for creating your own class.

**Comment by 1Map** [comment]
I do understand that there are just ol.render.Box and not ol.render.Circle

ol.interaction.DragBox uses ol.render.Box internally.

Sometimes a user want to use ol.interaction.DragBox, but be able to override the box_ part to use his/her own custom ol.render.Circle

But, because ol.interaction.DragBox does not expose box_ (as it is private), the user now need to create a custom Class for ol.interation.DragBox as well as a custom class for ol.render.Circle

**Comment by hweri69** [comment]
I fully undertand the aim to optimize the package, but I'm sure, not only 1map and me using private, undocumented members. I do for example to work with arbitrary layer properties (which is now implemented). So I would suggest to mention this change in the release/upgrade notes.

**Comment by ahocevar** [comment]
So, for everyone wanting to use private members at their own risk: use the [ol](https://npmjs.com/package/ol) package instead of the legacy build, then you won't run into this issue.

**Comment by M393** [comment]
If you can't use modules directly in your project you can make your own custom build which will also be a lot smaller.
See https://github.com/phpmyadmin/phpmyadmin/pull/16959 for an example
