### ISSUE TITLE
Quick start shows 'email protected' in cdn link

### ISSUE THREAD

**Issue by MartinWilkerson** [openlayers/openlayers#12514]
**Describe the bug**
When viewing the quick start at https://openlayers.org/en/latest/doc/quickstart.html, the 'complete working example' links to a stylesheet and script with obfuscated URLs.

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/doc/quickstart.html'
2. See the following:

```
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/[email protected]/en/v6.6.0/css/ol.css" type="text/css">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="https://cdn.jsdelivr.net/gh/openlayers/[email protected]/en/v6.6.0/build/ol.js"></script>
```

**Expected behavior**
See `<link>` and `<script>` elements with href/src attributes that are correct and do not include `[email protected]`.

**Comment by MartinWilkerson** [comment]
On further investigation, this issue only occurs when I have javascript disabled in my browser.

**Comment by ahocevar** [comment]
Can we close this? Having JavaScript disabled will break the majority of all websites today, I guess.

**Comment by MartinWilkerson** [comment]
I'm happy for this to be closed - I agree that it's quite unusual to browse without javascript enabled and fully accept that things break when I do. If I'd realised that this was caused by no javascript I would have at least lead with that in the issue, but I would still at least want to report it to the project so you/they know it happens and can decide whether it's an important thing to fix.
