### ISSUE TITLE
Decluttering of text and images does not work anymore after upgrading to 6.6

### ISSUE THREAD

**Issue by jomalla123** [openlayers/openlayers#12523]
**Describe the bug**
After upgrading from 6.5.0 to 6.6.0, declutter set in a VectorLayer (https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html) does not work anymore. I tested with both image and text, neither works.

**To Reproduce**
1. Create a vector layer in the following way and add it to a map:
```js
        const vectorSource = new VectorSource<Geometry>();
        const layer= new VectorLayer<VectorSource<Geometry>>({
            source: vectorSource,
            declutter: true,
        });
````
2. Decluttering does not work

I switched back and forth between 6.5.0 to 6.6.0 to double check the issue. Everything works fine with the same code in 6.5.0 but not in 6.6.0. 

Or has anything changed between the versions on how to define a layer with declutter enabled that I am not aware of?

**Expected behavior**
Decluttering still works in 6.6

**Comment by ahocevar** [comment]
Can you share an example that shows the problem? If you compare https://openlayers.org/en/v6.5.0/examples/vector-label-decluttering.html and https://openlayers.org/en/v6.6.1/examples/vector-label-decluttering.html, you see that nothing has changed in the rendered result.

**Comment by jomalla123** [comment]
Hey, thanks for the example, that is curious. But see the following example I created here, which reproduces the problem: https://codesandbox.io/s/accessible-forked-b4od9

![image](https://user-images.githubusercontent.com/76176622/125914734-231ef417-b67a-4e1c-abd2-3890fd16d706.png)

With 6.5.0 decluttering seems to work also in this example.

If am misusing the library, please give me a hint what I am doing wrong. What I am trying to do is to basically just put labels at a specific point on a layer (but without a visible image/geometry).

**Comment by M393** [comment]
You need to provide options to the Circle constructor:
```js
  image: new Circle({
    radius: 10,
    fill: new Fill({
      color: 'rgba(0, 0, 255, .5)',
    }),
  }),
```

**Comment by jomalla123** [comment]
ah okay, that makes sense and it works when I remove the image option. I don't even know why I added it in the first place. Thanks a lot!
