### ISSUE TITLE
Strange behavior of ol.layer.Vector.getFeatures(pixel) while dragging

### ISSUE THREAD

**Issue by oleg-derevenetz** [openlayers/openlayers#12521]
**Describe the bug**
It seems that hit detection considers only initial position of feature (which was before the start of the drag), and not the current position.

**To Reproduce**
1. Open the test case https://vkgeo.github.io/test/
2. Move the mouse over the feature. The tooltip should be shown when mouse cursor is over the feature;
3. Move the cursor slightly away from the feature (for example, a few pixels on the left), press left mouse button and start dragging towards the feature;
4. Feature will move away to the right (as it should be), but when the mouse cursor will be over the old feature's position, you will see the tooltip again. This shouldn't be happening.

**Expected behavior**
Hit detection should consider only the actual position of the feature while dragging, not the old one.

**Comment by MoonE** [comment]
You may want to skip hit detection during a drag interaction.
```js
if (event.dragging) {
  return;
}
```

**Comment by oleg-derevenetz** [comment]
Yes, I can add this as a workaround, thanks! But is the current behavior of `getFeatures()` intentional?

**Comment by MoonE** [comment]
The map and the hit detection image are redrawn at animation frames. pointermove events may happen more frequently. So while the map's internal state is updated during dragging it is not immediately rendered and a call to getFeatures will use an outdated image to detect features.
So this may happen by design.

An alternative would be the [Map#forEachFeatureAtPixel](https://openlayers.org/en/main/apidoc/module-ol_Map-Map.html#forEachFeatureAtPixel). It's slower but should be more accurate.

**Comment by oleg-derevenetz** [comment]
> The map and the hit detection image are redrawn at animation frames. pointermove events may happen more frequently. So while the map's internal state is updated during dragging it is not immediately rendered and a call to getFeatures will use an outdated image to detect features.

It seems however that hit detection image isn't updated at all until I release the mouse button.

**Comment by MoonE** [comment]
This can be controlled by the `updateWhileInteracting` option of [ol/layer/Vector](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html)

**Comment by oleg-derevenetz** [comment]
Yeah, I added `"updateWhileInteracting": true` and now I see just a rarely flickering tooltip (apparently due to less frequently redrawn hit detection image). Thank you!
