### ISSUE TITLE
WMS Time controller 

### ISSUE THREAD

**Issue by itsgifnotjiff** [openlayers/openlayers#12526]
I work with the Canadian Government and am trying to push the adoption of OpenLayers, but the only thing left for us to fully adopt and promote it is a proper way to animate Timed WMS layers. Something like [this](https://github.com/fmidev/metoclient) in the core library that would allow to control multiple layers with multiple time steps and even synchronise them would be of great help. I would love to have methods around OGC compliant (the standard for WMSs) layers such as getStartTime, getEndTime, getTimeStepMinutes and others. I would also love to be able to pre load and cache as well as a loading flag so to make animations easier and the final thing that would absolutely blow my mind is if we can develop a way to export animations, for example a GIF of all 16 steps of a WMS Time layer. This all should be doable as the library is already so mature and well structured and most of the above I have done following the official examples and hacking my way around limitations but to implement in the official library would help so many people and would make the library so much cooler/usable.

**Comment by ahocevar** [comment]
Have you seen https://openlayers.org/en/latest/examples/wms-time.html? That's about loading and caching, which you can also do ahead of starting the animation.

That said, meteoclient looks like a decent solution, and it does make sense to combine OpenLayers with third-party libraries. What makes you hesitate?

**Comment by itsgifnotjiff** [comment]
I have seen and used the WMS time example to implement a hacky application that animates through WMS layers but I would love to have it done by the official library and better structured so it is more extensible and easy to implement. My problem is that I am trying to use the least ammount librairies (ideally supported long term like OpenLayers) along with Vue.js and others who do not all communicate well together. Besides my argument for the betterment of OpenLayers is that the functionality I want would make it much more useful and would allow developers around the world to create time sensitive application much faster and cleanner.

**Comment by ahocevar** [comment]
Personally, I think the JavaScript ecosystem has matured enough around npm packages to justify libraries that do one thing, and do that well. This was different in the times of OpenLayers 2, which was one of the reasons why so much functionality was included there. Today, there is nothing wrong about choosing add-on libraries and using them.

That said, I think full WMS Time support would make a nice add-on library, but does not necessarily need to be part of OpenLayers itself. Maybe meteoclient is that library or could be a starting point for it. If you want to lead an effort creating such a WMS Time add-on, I'd be willing to provide guidance on good practices for integration with OpenLayers.

**Comment by itsgifnotjiff** [comment]
That sounds great!. Is there a way I can contact you a part from this very public thread sir?

**Comment by ahocevar** [comment]
See my [GitHub profile](https://github.com/ahocevar) for contact information.
