### ISSUE TITLE
document is not defined in ol/source/Raster.js

### ISSUE THREAD

**Issue by PerryRylance** [openlayers/openlayers#12530]
**Describe the bug**
Will not build in a Next.js / React environment when using Raster source.

**To Reproduce**
- Use create-next-app
- Add a map
- Add any raster layer
- Try to build

**Expected behavior**
- Build

**Observed behaviour**
Will not build - document is not defined

Could a similar approach to #12160 be used here?

If that's likely to be fruitful and not break anything else, then I would be quite happy to have a go at this.

**Comment by tschaub** [comment]
We can likely make a change to only lazily access the DOM, but you may want to avoid importing OpenLayers altogether during server-side rendering.  In Next.js, you can tell the framework that some components should not be loaded during SSR with a dynamic import.  See https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr.

**Comment by PerryRylance** [comment]
Thank you very much! I'm relatively new to Next, I really appreciate it.
