### ISSUE TITLE
map.getFeaturesAtPixel does not detect 0 opacity fill features

### ISSUE THREAD

**Issue by stazrad** [openlayers/openlayers#12539]
**Describe the bug**
We have features on the map with a solid stroke but 0 opacity fill (this styling is a requirement due to z-index/feature stacking work flows).

**To Reproduce**
1. Create a feature with 0 opacity fill
2. Click the feature on the map with a `map.getFeaturesAtPixel` listener
3. No features will be returned

**Expected behavior**
I would expect this util to still return any underlying features at the click location regardless of styling. Is that not expected?

**Comment by MoonE** [comment]
It works for me.
https://codesandbox.io/s/getfeaturesatpixel-transparent-fill-8phpb?file=/src/index.js

**Comment by stazrad** [comment]
@MoonE yep that example is totally working...this must be an implementation error on our side? closing for now 🙏
