### ISSUE TITLE
Type 'RasterSource' does not satisfy the constraint 'ImageSource'.

### ISSUE THREAD

**Issue by sanasus** [openlayers/openlayers#12532]
**Describe the bug**
v6.6.1
 i couldn't pass RasterSource instance to ImageLayer constructor due to TS violations, despite of RasterSource extends ImageSource.

> TS2344: Type 'RasterSource' does not satisfy the constraint 'ImageSource'.   
> The types returned by 'getImageInternal(...)' are incompatible between these types.     
> Type 'null' is not assignable to type 'ImageBase'.
> 
> TS2322: Type 'ImageLayer<ImageSource>' is not assignable to type 'ImageLayer<RasterSource>'.   
> Type 'ImageSource' is missing the following properties from type 'RasterSource': processor_, operationType_, threads_, layers_, and 10 more.
> 
> TS2322: Type 'RasterSource | undefined' is not assignable to type 'ImageSource | undefined'.   
> Type 'RasterSource' is not assignable to type 'ImageSource'.

**To Reproduce**
1. `export const getImageLayer = (source?: RasterSource): ImageLayer<RasterSource> =>
  new ImageLayer(
    {
      visible: false,
      source
    }
  );`

**Expected behavior**
In 6.5.3 I could pass RasterSource as source argument to ImageLayer

**Comment by ahocevar** [comment]
Thanks for reporting this, @sanasus. This will be fixed with #12544.

**Comment by sanasus** [comment]
thanks)
