### ISSUE TITLE
Cluster's `geometryFunction`

### ISSUE THREAD

**Issue by Razi91** [openlayers/openlayers#12541]
**Is your feature request related to a problem? Please describe.**
https://openlayers.org/en/latest/apidoc/module-ol_source_Cluster-Cluster.html
`geometryFunction` definition says ` When a feature should not be considered for clustering, the function should return null`. It could be understood that when we return null, it won't be taken into cluster feature. But it actually won't even show up on the map.

**Describe the solution you'd like**
Some way to render not clustered feature, maybe as cluster, but with one feature inside. I need to display on map few features not clustered with others.

**Comment by mike-000** [comment]
The features which are not clustered (e.g. cities of 10 million) can be displayed in a separate layer https://codesandbox.io/s/cluster-forked-kzt16

**Comment by Razi91** [comment]
It would be easier if I had those features on the same layer, as there are many interactions. I guess I'll just merge two sources together
