### ISSUE TITLE
Image icons are clipped at VectorTile edges. Part 2

### ISSUE THREAD

**Issue by Ruahonen** [openlayers/openlayers#12567]
I was happy to see new version 6.6.1 where this (https://github.com/openlayers/openlayers/issues/11884) was fixed.
But we have still problems with icons on edges.

On the picture there is several points on the edges that are fine, but still there is quite a lot points that are not ok.

<img width="717" alt="Screenshot 2021-07-28 at 19 52 17" src="https://user-images.githubusercontent.com/12742506/127364773-cc86bf5a-8fd0-4583-8237-67202a103788.png">

I am sorry that I cannot easily do a working demo for you. (Code is clojurescript/interop javascript)
What I have done:
1. Server side that is making tiles is taking care that points should be on every tile
2. renderBuffer, I have tried values from 0 to 3000, this attribute is working but still doesn't solve the whole problem
3. Styles anchor attribute is doing also some strange behaviour on rendering (in the picture there is no anchor attribute)

Any idea? I was wondering that could this problem be in render order or something like that?

**Comment by ahocevar** [comment]
A few things to note here:

- The `renderBuffer` option can only help if the server also buffers features.
- You can use the https://openlayers.org/en/latest/examples/drag-and-drop-custom-mvt.html example to test your tiles by dragging two neighboring tiles from the above screenshot into the example map, and check if all points in question are really duplicated (visible because of the higher opacity of overlapping points).

**Comment by Ruahonen** [comment]
@ahocevar yep you were right, the problem was that neighboring tiles didn't have the same objects! Hope this helps somebody else too, if you use ElasticSearch also when generating the tiles remember that intersecting bounding box should be larger there also :)

There is still this problem with styles anchor attribute (svg icon below, I want to use this drop shape icon so thats why I need anchoring). RenderBuffer doesn't seem to solve this. Any ideas?

anchor: [0,0] ->
![Screenshot 2021-08-02 at 14 16 51](https://user-images.githubusercontent.com/12742506/127853814-b83c2dd3-574b-455d-8e37-8b90b534b154.png)

anchor: [0.5, 1] ->
![Screenshot 2021-08-02 at 14 18 00](https://user-images.githubusercontent.com/12742506/127853937-4ccc7dd8-7f43-4120-b42c-3256551ba166.png)

svg: "data:image/svg+xml,%3Csvg%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2024%2024%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%0A%20%20%20%20%3Ccircle%20cx%3D%2213%22%20cy%3D%2213%22%20r%3D%2210%22%20fill%3D%22%23333%22%2F%3E%0A%20%20%20%20%3Ccircle%20cx%3D%2212%22%20cy%3D%2212%22%20r%3D%2210%22%20fill%3D%22%23ff1744%22%2F%3E%3C%2Fsvg%3E"

**Comment by Ruahonen** [comment]
@ahocevar any ideas?

**Comment by ahocevar** [comment]
@Ruahonen It looks like the buffer of the tiles is too small to accommodate for the anchor.

**Comment by jose-zitus** [comment]
I'm not exactly sure why, but setting declutterMode to 'none' on the Icon, seems to fix the issue without the need to have the same features near the edge of neighboring tiles.

**Comment by julienrf** [comment]
I am not sure whether I am hitting this issue as well or if I should create a new one, but the symptoms look the same: the icons of my features are clipped at the tile edges, as shown here:

![Screenshot 2023-10-08 at 15-15-08 Maps](https://github.com/openlayers/openlayers/assets/332812/63a553c0-d0d3-420a-a320-07813a97493f)

(instead, we should see complete pentagons for every point)

It seems that this behavior is intended though, according to [the documentation](https://openlayers.org/en/latest/apidoc/module-ol_source_VectorTile-VectorTile.html):

> Features are optimized for rendering, their geometries are clipped at or near tile boundaries and simplified for a view resolution.

I tried using `VectorSource` instead, but it does not scale to the amount of features I need to manage (~50k).

Are there any solutions I missed to not clip the icons at tile edges?
