### ISSUE TITLE
Using typescript but can not removeEventListener with type conflict

### ISSUE THREAD

**Issue by onsummer** [openlayers/openlayers#12561]
**Describe the bug**
I use typescript and the newest openlayer lib (ver 6.6), add an `pointermove` event listener like this:

``` typescript
const eventHandler = (e: MapBrowserEvent<MouseEvent>) => {
  console.log(e)
}
map.on('pointermove', eventHandler)
```

It works well, but when I want to remove eventHandler, typescript report a type error:

``` typescript
map.removeEventListener('pointermove', eventHandler) // report a type error
```

The type "(e: MapBrowserEvent<MouseEvent>) => void" cannot be assigned to the type "(arg0: Event | BaseEvent) => boolean | void".  ts(2345)

How to write the correct event handling function? Thanks.

**Comment by onsummer** [comment]
In order to remove event handler as well, I temporary write using `any`:

``` typescript 
const onPointerMoveHandler = (e: any) => {
  console.log(e)
}
```

**Comment by ahocevar** [comment]
The counterpart of `on()` is `un()`, so you should be using
```ts
map.un('pointermove', eventHandler);
```

**Comment by onsummer** [comment]
> The counterpart of `on()` is `un()`, so you should be using
> 
> ```ts
> map.un('pointermove', eventHandler);
> ```

thanks, my fault, please close this issue
