### ISSUE TITLE
Layer disappearing when coming into vector layer with opacity set

### ISSUE THREAD

**Issue by EngineerCoding** [openlayers/openlayers#12566]
**Describe the bug**
I have two layers setup, one which is the OSM tilelayer and one is a VectorLayer with a plain VectorSource. The former layer has zIndex of 0 and the vectorlayer a zIndex of 500. To the vector layer I am dynamically adding features, for now just points with an icon as style. 

When I change the opacity to any value between 0 and 1 (but not 0 and 1 themselves), the OSM layer (and other layers which I can configure in my app, but probably not relevant) disappears to the background color when the point in the vectorlayer is in the rendered extent. When I move out of the rendered extent, the OSM layers shows up again.

I have no clue why this is happening nor am I unable to reproduce this issue in a trimmed down sample application which shows this issue in action. Any ideas on why this might be happening would be great, as this seems like a proper bug.

**To Reproduce**
Unfortunately no sample app available, as I am unable to reproduce it in a isolated app. The issue is consistent though.

**Expected behavior**
The opacity be set without the underlying OSM layer disappearing (the background color seems to be showing up)

**Comment by ahocevar** [comment]
Without a sample app this will be hard to investigate. But one thing you should double-check is that you are using the correct type and value for the opacity, i.e. no string and correct comma separator:

* Correct: `0`, `1`, `0.5`
* Incorrect: `"0"`, `"1"`, `"0,5"`, `"0.5"`.

**Comment by EngineerCoding** [comment]
I have validated that, and the opacity is working for the icon itself. When I toggle the visiblity of the layer itself, the OSM layer is visible again. So that indicates to me that the layer is drawing the background itself, and it is not omitting the other layers.

Also given that it only happens when the icon is in the rendered extent, might this something to do with feature rendering?

**Comment by mike-000** [comment]
What you describe is very similar to what happens in https://openlayers.org/en/latest/examples/layer-clipping-vector.html if an extent is not set on the OSM layer.  Are there any prerender or postrender events on either of the layers?  Giving one of the the layers a unique `className` might be a workaround.

**Comment by EngineerCoding** [comment]
I don't see how clipping is an issue, as I am able to do this in a sample app. However, I did notice something odd, when I use `.addFeatures` as opposed to `.addFeature`, I get different results:

Only showing polygon: https://codepen.io/engineercoding/pen/bGWvmxo
Showing both line and polygon: https://codepen.io/engineercoding/pen/mdmxzQO
_(A line should be showing in the Netherlands and a polygon in Germany)_

By switching my real life application to only use `.addFeature` my problem is not resolved.

After a while I stumbled upon the actual issue. Some CSS outside of my control in my particular application set background-color of a canvas, which apparently is more often than not overriden bij openlayers. I appreciate your valuable time for helping me, hopefully the issue I just posted is a different issue on it's own so that this was not a complete waste of your time. 

Thanks

**Comment by mike-000** [comment]
Yes, css from other libraries can cause some obscure errors in OpenLayers, as in #12439.  Having appropriate default css values for canvas within .ol classes might prevent that.  The clipping example only works with a single feature, or with overlapping features, see #12376.
