### ISSUE TITLE
Type mismatch with interaction  DragBox `condition`

### ISSUE THREAD

**Issue by ablakey** [openlayers/openlayers#12568]
In OL 6.6.1 I have a new type error for this case:

```
import condition from "ol/events/condition";
import OlDragBox from "ol/src/interaction/DragBox";

const exampleDragBox = new OlDragBox({ condition: condition.platformModifierKeyOnly });
```

(TypeScript gives me one of its famous massive errors, so here's the gist)

```
"Type '(mapBrowserEvent: MapBrowserEvent<any>) => boolean' is not assignable to type 'Condition'
```

Did the interface change or is this perhaps revealing a typing error?

As always, thank you.

**Comment by ahocevar** [comment]
I'm unable to reproduce this. See https://codesandbox.io/s/eloquent-mountain-mipdd?file=/src/index.ts. The one thing I notice in your code is that you are mixing imports from `ol` and `ol/src`.

**Comment by ablakey** [comment]
Thanks for the codesandbox. Didn't realise it was that easy to get OpenLayers + TS working in a sandbox . I'll do my own reproductions next time.

You're right. Removing `src` fixed it. Need to get vscode to import properly.
