### ISSUE TITLE
ol.interaction.Select.on function , does not return the expected feature

### ISSUE THREAD

**Issue by omerbrandis** [openlayers/openlayers#12569]
hello, 

these are my first steps with open layers and js, so please be gentle.
the problem I encountered is probably not a bug,  most likely I'm doing something incorrectly :-).

I'm using open layers v 6.6.1 , browsing with chrome  version 80.0.3987.132
I've managed to show a basic map , add layers,  add a ol.interaction.Select interaction . (in other words i see a map, i see the various feature polygons , when i press any of them their style changes as expecte :-) ).

I wish to add data to a feature in one part of the code, then later on once that feature has been selected, read that data.
i've tried using the set/get methods.
which works as expected in the function that reads the data and adds the layers.

but when I tried using the get method on the data in the callback function , its undefined:
var selectSingleClick = new ol.interaction.Select(); // can set the style, but the default seems good enough for now
map.addInteraction(selectSingleClick);

selectSingleClick.on('select', function(e)
{
    const SelectedFeatures = e.target.getFeatures();
    console.log('number of selected features ',SelectedFeatures.getLength()); // works as expected 

    //
    const FeautreIterator = [SelectedFeatures][Symbol.iterator]();
    for (const CurrentFeature of FeautreIterator)
    {
        console.log('current feature',CurrentFeature.ol_uid,CurrentFeature.T,CurrentFeature.get('FfrFeatureType'));
    }
});

i've used both ol_uid and setId to debug, its looks like the object returned by e.target.getFeatures() is not the one on which I've used the Set property methods.
but there is only one visible layer ( there are two other non visible layers at a similar location (controlled using layer:min/max resolution))  and it has only 1 feature  + the feature's style/outline is changed correctly on click.

please advise,
Omer.

**Comment by ahocevar** [comment]
Have you tried
```js
e.target.getFeatures().forEach(feature => {
  console.log(feature.get('FfrFeatureType'));
});
```

**Comment by omerbrandis** [comment]
It seems that using const SelectedFeatures = e.selected; works , 
( I tried using e.target.getFeatures(); due to example http://www.voades.org/sites/all/libraries/openlayers3/examples/select-features.html).

+ also an extra [] around 'SelectedFeatures', at const FeautreIterator = [SelectedFeatures][Symbol.iterator]();
did not help things. :-)

:-)

**Comment by omerbrandis** [comment]
I would like to take my previous statement back.

const SelectedFeatures = e.selected; , does not work as expected. ( only returns one element).

while 
e.target.getFeatures().forEach(feature => {
  console.log(feature.get('FfrFeatureType'));
});

works.
