### ISSUE TITLE
Why is renderMode: 'image' deprecated?

### ISSUE THREAD

**Issue by sandra-tu** [openlayers/openlayers#12562]
I am trying to render upwards of 10000 points efficiently on a map and found this thread from @ahocevar:
[https://github.com/openlayers/openlayers/issues/8392](https://github.com/openlayers/openlayers/issues/8392)

The thread was really helpful and included using `renderMode: 'image'` to vastly improve performance, the new default `renderMode` is `hybrid` and does not perform nearly as well. Why is `image` deprecated, and is there another option I can use to achieve similar results? If not, can `renderMode: 'image'` not be deprecated until there is a similar function? Thank you!

**Comment by ahocevar** [comment]
For vector layers, you can use `ol/layer/VectorImage`. For vector tile layers, you can use `declutter: true` to reduce the number of visible points when they overlap.

**Comment by sandra-tu** [comment]
Thank you, the performance of `ol/layer/VectorImage` is amazing!! Sorry for missing the replacement note in the updates, and thank you so much for responding so incredibly quickly.
