### ISSUE TITLE
e.getLayout is not a function in MultiPolygon.js:88

### ISSUE THREAD

**Issue by omerbrandis** [openlayers/openlayers#12579]
Hello 

(these are my first steps with open layers)

i'm trying to add a feature to a layer with a ol.geom.MultiPolygon source geometry.

I managed to create and display 2 circles :
const TempPointCenter2 = [....];
var CurrentSegmentGeometry2 = new ol.geom.Circle(TempPointCenter2,0.0000005);
CurrentSegmentGeometry2.transform('EPSG:4326', 'EPSG:3857');
var CurrentSegmentFeature = new ol.Feature(CurrentSegmentGeometry2);

I now wish to create 1 feature to combine both circles.

I've tried  var MultiPoly = ol.geom.MultiPolygon([ ]);
I've tried var MultiPoly = ol.geom.MultiPolygon([CurrentSegmentGeometry2 ]);
I've tried var MultiPoly = ol.geom.MultiPolygon([ol.geom.Polygon.fromCircle(CurrentSegmentGeometry)]);

all return the error in the title.

* i was not able to use ol.geom.Point / Multipoint since i was not able to control the display radius , which is very simple when using Circle

please advise.
Omer.

**Comment by mike-000** [comment]
either append polygons to a new MultiPolygon

```
var MultiPoly = new ol.geom.MultiPolygon([]);
MultiPoly.appendPolygon(ol.geom.Polygon.fromCircle(CurrentSegmentGeometry));
MultiPoly.appendPolygon(ol.geom.Polygon.fromCircle(CurrentSegmentGeometry2));
```

or create a MultiPolygon from the polygon coordinates

```
var MultiPoly = new ol.geom.MultiPolygon([
  ol.geom.Polygon.fromCircle(CurrentSegmentGeometry).getCoordinates(),
  ol.geom.Polygon.fromCircle(CurrentSegmentGeometry2).getCoordinates()
]);
```

or instead of a MultiPolygon use a GeometryCollection of circle geometries

```
var MultiCircle = new ol.geom.GeometryCollection([
  CurrentSegmentGeometry,
  CurrentSegmentGeometry2
]);
```

**Comment by omerbrandis** [comment]
Hello Mike, 
thank you very much for trying to help.

* have not mentioned before , i'm using open layers v6.6.1 , and chrome browser.

1. i've tried using ol.geom.GeometryCollection

it failed on 
var SegmentsLayer = new ol.layer.Vector(
    {
        source: new ol.source.Vector({
            //features: [SegmentsPolygonFeature],
            features: SegmentsPolygonFeaturesArray,
with :
Vector.js:371 Uncaught TypeError: n.getId is not a function
    at n.iu (Vector.js:371)
    at n.addFeaturesInternal (Vector.js:407)

SegmentsPolygonFeaturesArray contains both the MultiCircle and other polygons. ( this is not a problem for polygons + circle )


2. var MultiPoly = new ol.geom.MultiPolygon([]);  failes , 
MultiPolygon.js:88 Uncaught TypeError: e.getLayout is not a function
    at Object.n [as MultiPolygon] (MultiPolygon.js:88)


3.
var MultiPoly = new ol.geom.MultiPolygon([
              ol.geom.Polygon.fromCircle(CurrentSegmentGeometry).getCoordinates(),
              ol.geom.Polygon.fromCircle(CurrentSegmentGeometry2).getCoordinates()
            ]);

works 
:-)

Omer.
