### ISSUE TITLE
when setting map-div hidden, my ol.control.Control stays visible

### ISSUE THREAD

**Issue by omerbrandis** [openlayers/openlayers#12580]
hello

I'm using open layers v 6.6.1

I've managed to create a custom control :
```js
class DensityScaleClass extends ol.control.Control
{
    constructor(opt_options)
    {
        const options = opt_options || {};
        const DensityElement = document.createElement('div');
        DensityElement.className = 'densityLegend ol-unselectable ol-control';
        super({element: DensityElement,target: options.target,});
        this.DensityElement = DensityElement;
       // ...
    }

    HideScale()
    {
        this.DensityElement.style.visibility = "hidden";
    }

    ShowScale()
    {
        this.DensityElement.style.visibility = "visible";
    }
}
```
I am able to see it displayed on the map correctly, and hide & show it by calling methods HideScale,ShowScale.  :-)

but when I hide the container map div
 ```js
MapElement.style.visibility = 'hidden';
```

my control stays visible, while the map and its other controls ( zoom, scaleline ...) are hidden.

can someone point me in the right direction ?

thanks,
Omer.

**Comment by mike-000** [comment]
Have you tried using

```
HideScale()
{
    this.DensityElement.style.display = "none";
}

ShowScale()
{
    this.DensityElement.style.display = "";
}
```

**Comment by MoonE** [comment]
Are you using a custom target element that is outside the map?
If it is not inside the map element you need to hide your control with your own code.

**Comment by omerbrandis** [comment]
explicitly adding the control to the map div (appendChild) solved the problem.
:-)
