### ISSUE TITLE
Allow flexible tileSizes also for vector tile layer

### ISSUE THREAD

**Issue by Biosphakus** [openlayers/openlayers#12590]
I would like to use ``vectorTile`` layers with a ``tileGrid`` with flexible ``tileSizes`` expecting this to work just as it does with raster tiles. As Mike has pointed out [here](https://gis.stackexchange.com/questions/407363/openlayers-zdirection-in-raster-tiles-vs-vector-tiles), it seems that fixed ``tileSizes`` are implicitly assumed in vectorTileLayer. My use case was that I wanted to change tile sources on intermediate (non-integer zoom levels) scaling the tiles accordingly (therefore using different tile sizes). Works nicely for raster tiles; not for vector tiles, though. For more details and a code sand box see the linked thread on GIS StackExchange.

**Proposed feature**
Support flexible ``tileSizes`` in ``tileGrid`` for ``vectorTile`` layers (or, less impressive, change the docs to clarify this kind of behaviour).

**Comment by ahocevar** [comment]
The tile grid that is used for rendering vector tiles is independent of the underlying source tile grid. Just like with any other tile source, your vector tile source can use any tile grid you are able to specify with `ol/tilegrid/TileGrid`. This of course includes variable tile sizes.

**Comment by Biosphakus** [comment]
Thank you for your reply! In my case, I want to change the tile source on zoom. I have the tile source (including the grid zoom {z} value) calculated using the current view zoom and the current user selection of some buttons. As there are several combinations  (but a unified logic that works just the same as with raster tiles), I would like to avoid composite layers with min/max resolution. Instead, I'd like to use ```tileUrlFunction```, which is called as {z} changes. If I understood correctly, the problem here seems to be that grid zoom {z} cannot be influenced independently of the view zoom for vector tiles, is that correct? Is there another option to call ```tileUrlFunction``` for vector tiles on view zoom change even if {z} doesn't change? I do have some minor style changes on zoom (and these work quite effortlessly) but it doesn't seem to be a style issue because the actual data is supposed to toggle at zoom.

**Comment by ahocevar** [comment]
Strange use case. What is the rationale behind these tile source gymnastics?

**Comment by Biosphakus** [comment]
Use case: The map has different granularities (levels of detail) which you may select or unselect. Think of a world map that normally switches between continent, country, district and city borders when you zoom in. In my use case, the map has this normal mode, too, but you may also decide to look at the city level from a global map view. The ``tileUrlFunction`` came in handy for this. 

In fact, it's a zoomable taxonomic map illustrating the different classifications of life (family, genus, species etc). I could show you what it looks like (it's probably quite interesting for you to see what OpenLayers is used for, anyway) but I'm hesitant to put the link and the credentials here publicly as it's still in development.

**Comment by ahocevar** [comment]
Interesting application. The usual way to achieve the desired behaviour would be creating one source for each aspect you want to show, and switch sources of the layer. Or create one layer for each aspect, and switch layers. Both approaches work the same for raster and vector tile layers. If you want to stick with what you have, I still think that using resolution based styling for the vector tile layers is the way to go. Then your vector tiles would contain data for all aspects you want to show, and the style function decides based on resolution what to show. This way, you'd also save round trips to the server.
