### ISSUE TITLE
How to use a protected property after version 6.6?

### ISSUE THREAD

**Issue by leonardofmed** [openlayers/openlayers#12598]
I using a function that needs to get some properties from TileSource, like tileCache and tileGrid. Before this update I overridden the protection status of these properties in: `node_modules/@types/ol/source/tile.d.ts`, which then worked perfectly. Now this is no longer possible, there's no use in changing the status in @types anymore, I keep getting the error message: 
> Property 'tileCache' is protected and only accessible within class 'TileSource' and its subclasses.

I would like to know how I can manipulate these variables again in this version. 

I've already tried to add `"skipLibCheck": true` in my `tsconfig.json`, but sadly it didn't help.

**Comment by ahocevar** [comment]
Why not just use the protected property and add a `//@tsignore`? Then you are reminded every time you stumble across the code that you should not be using the protected property.

**Comment by leonardofmed** [comment]
`getTileGrid()` solved most of the problems for me, I wasn't aware of its existence until now. `tileCache` I use because of a bug in older versions of my app, where the background maps were overlaid with local background maps that the user can change, so I used tileCache.clear() to solve this problem. 

I will try to remove this old code to see if the error still persists. In any case, thank you very much for your help.

**Comment by ahocevar** [comment]
If you only need `tileCache.clear()`, that's exactly what happens when you call `tileSource.clear()`.

**Comment by leonardofmed** [comment]
Perfect! No more errors now and no need to use private properties. Thank you very much one more time!
