### ISSUE TITLE
Snap change event not working in 6.2.1

### ISSUE THREAD

**Issue by jswit** [openlayers/openlayers#12593]
```
let snap = new Snap({
  source: this.source,
});
snap.on('change', (evt) => {
   console.log(evt) // 
})
map.addInteraction(snap);
```
When modify polygon snap change event can't listen

**I think when I modify the polygon, I can know which edge is adsorbed**

Please help me, thanks!

**Comment by mike-000** [comment]
There is no event to indicate the snap interaction has snapped.  You could use the style function of a draw or modify interaction to check if its cursor feature is snapped to a feature https://codesandbox.io/s/draw-and-modify-features-forked-iw6ny
