### ISSUE TITLE
Add a getter and setter for renderBuffer_

### ISSUE THREAD

**Issue by OnlineInternetPerson** [openlayers/openlayers#12592]
**Is your feature request related to a problem? Please describe.**
The renderBuffer option on the BaseVector layer constructor is really awesome. 

I'm always frustrated when I need to change it after adding a new icon image with a different size to the layer. I'm stuck mucking about with OpenLayers private properties, which isn't great.

The docs say: `Recommended value: the size of the largest symbol, line width or label.` Unfortunately this is not known at the time of layer instantiation.

**Describe the solution you'd like**
I'd like to see some way for me to change the renderBuffer_ of a layer that inherits from BaseVector after class instantiation. 

There's already a getRenderBuffer method, but its not documented on the public API. One approach could be to:

1. make the current getter public on the API, and
2. expose a setter so that Layer instances can adjust this value on the fly

**Comment by ahocevar** [comment]
As an alternative, we could automatically adjust the render buffer, like we do for vector tile layers.

**Comment by OnlineInternetPerson** [comment]
That would also be great.
