### ISSUE TITLE
xhr is executed automatically.

### ISSUE THREAD

**Issue by AmSoMad** [openlayers/openlayers#12591]
**Describe the bug**

**To Reproduce**
3. See error
<button  name="SearchBtn" onclick="srch_danji("danji_div_code","danji_ind_code">Search</button>

function srch_danji(aa,bb){
    layerRemover("ffffff");
	var vector = new ol.layer.Vector({	
					  source: new ol.source.Vector({
					    url: function(extentArea) {
							
			                var strUrl = '/geoserver/seongjang/wfs?service=' +
			                    'WFS' +
			                    '&version=1.3.0' +
			                    '&request=GetFeature' +
			                    '&typename=sj:ji'+
			                    '&outputFormat=application/json'+
			                    '&srsname=EPSG:3857'+
								'&style=DD';			
							if(aa!= null && aa!= ''){
								strUrl +='&viewparams=ww:'+aa+';';
			
							}else{
								strUrl +="&viewparams=ww:;";
							}
							if(bb!= null && bb!= ''){
								strUrl += 'ee'+bb.substring(0,2)+';';
							}
							return strUrl;
						},
					    format: new ol.format.GeoJSON(),
						strategy: ol.loadingstrategy.bbox
					  }),					  	
					  style:new ol.style.Style({
						stroke: new ol.style.Stroke({
							//color: 'rgba(81,49,147,1.0)',
							color: 'rgba(222,0,0,1.0)',
							width: 3
						}),
						fill: new ol.style.Fill({
							//color: 'rgba(191,227,74,0.5)',
							color: 'rgba(200,0,0,0.5)',
							width: 1,
						}),	
					  }),
					  minResolution: 5,
					  maxResolution: 1000,
					  
					});
	vector.set("name","ffffff");
	map.addLayer(vector);
}

xhr request for wfs data from geoserver.
However, after the layer is added, it continues to be added when moving the map. It doesn't pass my function. It passes directly to featureloader.js 105 line.
The inner function is executed only when the button is clicked. However, only the corresponding vector polygon continues to be superimposed on the source.

**Expected behavior**

**Comment by mike-000** [comment]
If you specify `ol.loadingstrategy.bbox` the function can be called whenever the extent is changed.  If the function does not use `extentArea` you should specify `ol.loadingstrategy.all`

**Comment by AmSoMad** [comment]
@mike-000 Thank you!. you made my day
