### ISSUE TITLE
SetStyle function for select, draw and modify interactions

### ISSUE THREAD

**Issue by MelihAltintas** [openlayers/openlayers#12604]
I need to change style of select, draw and modify interactions after the initialization. But this objects don`t have setStyle method set('style',...) method with changed work in select interaction but not work in draw and modify interaction. (i think this method is not reactive) 

**Describe the solution you'd like**
Could you add the setStyle method to select, draw and modify interactions? Or can you give an advice for the change style of draw interactions after the initialization without reinitialization

**Comment by mike-000** [comment]
In the case of Draw and Modify the style in the constructor is used to style the interaction's overlay, so you can use `draw.getOverlay().setStyle(myStyle)` to change it.  You could avoid using `setStyle()` completely if you specify a style function in the constructor which returns whatever is your current preferred style.  As in https://openlayers.org/en/latest/examples/measure-style.html call draw.getOverlay().changed() to re-render if your preferred style changes,

**Comment by MelihAltintas** [comment]
Thanks a lot mike problem is solved :)
