### ISSUE TITLE
Please add a function to rotate an Image Layer

### ISSUE THREAD

**Issue by Rskut** [openlayers/openlayers#12601]
I would like to have a function to rotate the image layer. The purpose of this is that some of my users have PNG Images without any coordinates, so to georeference the images I would provide an UI to move, crop and rotate the image but unfortunately there is no setter for rotation.

**Comment by ahocevar** [comment]
You can achieve that by defining a projection for the image layer, where the transform function applies a rotation. To register a transform function, use [addCoordinateTransforms()](https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.addCoordinateTransforms).

**Comment by Rskut** [comment]
Thank you for your suggestion. I'm not sure how I would do that, is this the right approach?

```
const viewProjection = get('EPSG:3857');

const rotateProjection = new Projection({
	code: 'rotate',
	units: 'm',
});

addProjection(rotateProjection);

const rotateTransform = function(coordinate: number[]) {
	return rotate([coordinate[0], coordinate[1]], 1.57);
}

const normalTransform = function(coordinate: number[]) {
	return [coordinate[0], coordinate[1]];
}

addCoordinateTransforms(viewProjection, rotateProjection, rotateTransform, normalTransform);

const imageLayer = new ImageLayer({
	map: map,
	source: new ImageStatic({
		url: url,
		imageExtent: [855627, 6862683, 857099, 6863844],
		projection: rotateProjection,
	}),
});
```

**Comment by ahocevar** [comment]
Yes, something like that. But instead of the `normalTransform()` function you need a transform that inverts the rotate transform performed by the `rotateTransform()` function.

**Comment by mike-000** [comment]
The transforms should rotate around the center of the image extent, not coordinate [0, 0].  See https://github.com/openlayers/openlayers/issues/4949#issuecomment-525272189

**Comment by pleconte87** [comment]
Hi,
Do you have a working example for this?

**Comment by mike-000** [comment]
> Hi, Do you have a working example for this?

https://codesandbox.io/s/reprojection-image-z0uit?file=/index.js
https://codesandbox.io/s/static-image-forked-ilq4uf?file=/main.js
