### ISSUE TITLE
Move the label always to the acutal extent if the polygon/lineString is partialy outside | Dynamic labeling

### ISSUE THREAD

**Issue by andieis** [openlayers/openlayers#12622]
At the moment I can place the labels of a polygon/lineString only at the center of the feature (or move it with an offset).
If I drag the map till the label is outside but the polygon is partialy visible, the label disappears. It would be really nice, if the label would now change its position, so that it is visible again.

If I move the map till the polygon is out of the extent, then the label should disappear. This feature could be applied also to other geometries like linestring, multilinestring and multipolygon.

This feature is similar to the labeling in QGIS where this feature is already implemented.

I've tried to sketch the problem in the following document: [Dynamic_Labeling.pdf](https://github.com/openlayers/openlayers/files/6968534/Dynamic_Labeling.pdf)

Thanks a lot for your work and have a nice day!

**Comment by mike-000** [comment]
You can set a geometry in the style to override the feature geometry.  You could use turf.js to calculate a clipped geometry for text labels https://codesandbox.io/s/vector-layer-forked-jb3i4?file=/main.js  (turf can return MultiPolygons with empty polygons, which breaks the OpenLayers GeoJSON readFeature method, so a loop is needed to remove them).
