### ISSUE TITLE
Baidu map coordinate offset

### ISSUE THREAD

**Issue by JavaScript7** [openlayers/openlayers#12620]
I want to set a latitude and longitude, but this latitude and longitude deviates greatly on the Baidu map.

const baiduMapLayer = new TileLayer({
  source: new TileImage({
    tilePixelRatio: 2,
    projection: 'EPSG:3857',
    tileGrid: new TileGrid({
      origin: [0, 0],
      resolutions
    }),
    tileUrlFunction: tileCoord => {
      if (!tileCoord) {
        return ''
      }
      const z = tileCoord[0]
      let x = tileCoord[1]
      let y = tileCoord[2]
      if (x < 0) {
        x = -x
      }
      if (y < 0) {
        y = -y
      }
      return `baiduMapUrl`
    }
  })
})

new Map({
  target: 'map',
  layers: [
    baiduMapLayer
  ],
  view: new View({
    center: [118.12133, 24.437313],
    projection: 'EPSG:4326',
    zoom: 13,
    maxZoom: 18,
    minZoom: 12,
    constrainResolution: true
  }),
})

**Comment by mike-000** [comment]
The Baidu source should use the Baidu projection transform, see #10374

**Comment by JavaScript7** [comment]
@mike-000 thanks.
Although I used the Baidu projection transform, I want to set a mark point, but the mark point still has a big offset.

**Comment by JavaScript7** [comment]
@mike-000 I'm so stupid that I made a mistake about Baidu projection.I always thought it was'EPSG:3857', but it was actually'BD:09'. Thank you again!
