### ISSUE TITLE
Duplicated ol/format/XLink.js file with different case

### ISSUE THREAD

**Issue by gedaiu** [openlayers/openlayers#12623]
**Describe the bug**

It looks like using the ol 6.6.1 with Broccoli triggers a build error:

```
Build Error (BroccoliMergeTrees)

[BroccoliMergeTrees] error while merging the following:
  1.  [Funnel: Packaged Ember CLI Internal Files]
  2.  [BroccoliMergeTrees: Full Application]
  3.  [BroccoliMergeTrees: TreeMerger (custom transform: es6)]
  4.  [BroccoliMergeTrees: Packaged Tests]
Merge error: conflicting capitalizations:
node_modules/ol/format/XLink.js in /tmp/broccoli-141869LYS3IJtCjL1N/out-606-broccoli_merge_trees_full_application
node_modules/ol/format/xlink.js in /tmp/broccoli-141869LYS3IJtCjL1N/out-606-broccoli_merge_trees_full_application
Remove one of the files and re-add it with matching capitalization.
```

**To Reproduce**
1. create an ember app
2. add ol 6.6.1 as a dependency
3. build the app

**Expected behavior**
The app should just build with no errors.

**Comment by ahocevar** [comment]
We recently changed the case of that file, see f08f31101cfa0fc3dd231ef5bc4df2b333fdbc1a. Depending on your operating and file system, duplicate files with different case can occur when npm updates a package. To fix the problem, simply delete `node_modules/ol/format/XLink.js`. The `ol` package now only contains `node_modules/ol/format/xlink.js`.

**Comment by gedaiu** [comment]
Awesome! Thanks! Will there be a release any time soon?

**Comment by ahocevar** [comment]
What I described above applies to the current release (v6.6.1). This is an issue with your operating and file system, not with OpenLayers.

**Comment by gedaiu** [comment]
Yes, indeed. Everything works after I removed the node modules folder. Thanks!
