### ISSUE TITLE
OverviewMap control issues warning about zero height and width when collapsed

### ISSUE THREAD

**Issue by mossaiby** [openlayers/openlayers#12625]
**Describe the bug**
When a OverviewMap control is present and is collapsed, it issues warnings about zero height and width of map.

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/overviewmap.html'
2. Open the developer console
3. See the warnings

**Expected behavior**
No warnings when overview map is not collapsed. Try setting `collapsed: false` and there will be no error.

**Comment by mike-000** [comment]
The same happens with the main map when in a hidden tab.  The message should be relevant only if the map target element's `offsetParent` property not null.

**Comment by ahocevar** [comment]
Not sure if this would be a good indicator. `offsetParent` will also be null when the `position` of the element is `fixed`.
