### ISSUE TITLE
I can't access latitude and longitude of the map object

### ISSUE THREAD

**Issue by RobertVogt** [openlayers/openlayers#12635]
There are many places within my application where I keep OpenLayers Map and google imagery aligned.
This is done by setting the google imagery to the same center location as the map object.

Previously I was able to set latitude and longitude like this...

         //set latitude, longitude and zoom
          map.latitude = place.geometry.location.lat();
          map.longitude = place.geometry.location.lng();

I can no longer access latitude and longitude

**Comment by MoonE** [comment]
With the latest OpenLayers version you can use `map.getView().getCenter()` the coordinate will be in the view projection.
`map.getView().getProjection()`
https://openlayers.org/en/main/apidoc/module-ol_View-View.html#getCenter

**Comment by RobertVogt** [comment]
Thank you, it works but not nearly as convenient as having the properties available.
