### ISSUE TITLE
the openlayer  is support the lerc tile ? how to use lerc tile source in source/xyz

### ISSUE THREAD

**Issue by pengpeng9413** [openlayers/openlayers#12634]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Comment by mike-000** [comment]
You would need a custom tile load function as described at https://openlayers.org/en/latest/apidoc/module-ol_Tile.html#~LoadFunction
which calls the Lerc decoder https://www.npmjs.com/package/lerc  This example https://codesandbox.io/s/simple-forked-8vxfk?file=/main.js displays Esri elevation tiles in the Mapbox DEM format used in https://openlayers.org/en/latest/examples/disable-image-smoothing.html and https://openlayers.org/en/latest/examples/sea-level.html

**Comment by pengpeng9413** [comment]
@mike-000 thank you very much! very appreciate~ ,I have resolved the problem !
