### ISSUE TITLE
Access sketchLineCoords_ from Draw object

### ISSUE THREAD

**Issue by RobertVogt** [openlayers/openlayers#12637]
On my map I allow users to edit the individual nodes of a drawn vector object.

I used to perform this by accessing Draw.sketchLineCoords_  

This has been made a private property of Draw and I receive the error..."Property 'sketchLineCoords_' is private and only accessible within class 'Draw'.ts(2341)"

I assume that I would be able to create a local instance of the object and then have access to this again, something like...

localDraw: Draw = new Draw();

However the Draw object requires "options" but can't for the life of me figure out what format it wants this in...it doesn't seem 
to line up with other OpenLayers patterns.

If creating a new local Draw is the correct route, how do I go about providing "options"
If not, how do I access 'sketchLineCoords_'?

**Comment by ahocevar** [comment]
You'll find all the options in the API documentation: https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html. The draw interaction is configured the same way as everything else in OpenLayers. As for accessing the coordinates of the sketch line, the API way to do that is in a `drawstart` listener:
```js
let sketchFeature;
draw.on('drawstart', e => {
  sketchFeature = e.feature;
});
```
Now after the user starts drawing, you'll have the sketch line feature in `sketchFeature`, and can access its coordinates with the Geometry API:
```js
const geometry = sketchFeature.getGeometry();
const coordinates = geometry.getCoordinates();
```

**Comment by RobertVogt** [comment]
Thank you for the quick response, I will try this but I need to access coordinates outside of the "draw" process i.e.(drawstart, drawend, etc...).
I have a requirement to allow a user to select a "start node" and "end node" and allow them to delete all the nodes in between.
Modify does not meet these requirements

**Comment by ahocevar** [comment]
The snippet I posted above stores the sketch feature, so you can access it any time. The only requirement is that the `drawstart` event is triggered once.
