### ISSUE TITLE
TS-definition for BaseLayer.setExtent does not accept undefined

### ISSUE THREAD

**Issue by pteigen** [openlayers/openlayers#12636]
**Describe the bug**
According to the documentation the setExtent function should accept undefined:
From base.js:
`Set the extent at which the layer is visible.  If `undefined`, the layer
will be visible at all extents.
@param {import("../extent.js").Extent|undefined} extent The extent of the layer.`

From base.d.ts:
`setExtent(extent: number[]): void;`

**Expected behavior**
setExtent function in base.d.ts should accept undefined

**Comment by ahocevar** [comment]
This has been fixed already with #12595. Please verify by updating ol to the latest from the main branch with `npm install ol@dev`.

**Comment by pteigen** [comment]
Working as expected in ol@dev. Thank you
