### ISSUE TITLE
TileLayer no longer supports naming it

### ISSUE THREAD

**Issue by RobertVogt** [openlayers/openlayers#12639]
In OpenLayers 6.6.1 the "title" option is gone with no suitable replacement.

Without this I am not able to differentiate between layers.

Example:

import { Tile as TileLayer, Image as ImageLayer } from 'ol/layer';
const mapServerLayer = new TileLayer(
      {
        title: 'mapserver',
        source: new TileWMS({
          params: { 'LAYERS': 'MAP', 'FORMAT': 'image/png', 'TILED': true },
          url: fullURL,
          serverType: 'mapserver',
          tileGrid: aTileGrid,
          crossOrigin: 'anonymous',
        })
      });

**Comment by mprins** [comment]
API says you can set using the options: https://openlayers.org/en/latest/apidoc/module-ol_layer_Tile-TileLayer.html and you should use a getter to retrieve it

**Comment by RobertVogt** [comment]
Ahhh...sorry, I've been looking at so much documentation that it's all blurring together!
