### ISSUE TITLE
Add getId() to Layer

### ISSUE THREAD

**Issue by RobertVogt** [openlayers/openlayers#12645]
I know that the exposed properties are name and title for differentiating layers but it would be nice to be able to get the ol-uid
of each layer as well.

**Describe the solution you'd like**
add a getter for ol-uid on the Layer object.

**Comment by ahocevar** [comment]
Neither name nor title are special properties on the layer. But you can those (and any other) on the layer. Either directly, or - when using TypeScript - with the `properties` option.

There is also a [getUid()](https://openlayers.org/en/latest/apidoc/module-ol_util.html#.getUid) function you can use to get a unique id of an arbitrary object - also of a layer instance.

**Comment by ahocevar** [comment]
You have to use it like this:
```js
map.getLayers().forEach((layer: olLayer<VectorSource<Geometry>>) => {
  console.log(getUid(layer));
});

**Comment by RobertVogt** [comment]
No, I was expecting it as a function of the layer...I'll try this, thanks!
