### ISSUE TITLE
Auto view

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#12644]
I'm wondering if it would be a useful feature to be able to construct a map without a view and to have the view auto-generated based on layer or source information.  For example, a GeoTIFF source may provide metadata on view-related properties like projection and extent.

To create a map that would show an entire GeoTIFF, we could make it possible to do this:

```js
const layer = new TileLayer({
  source: new GeoTIFF({
    sources: [{url: 'https://example.com/cog-1.tif'}],
  }),
});

// map with no view will get one when information is available
const map = new Map({
  target: 'map',
  layers: [layer],
});
```

Then to later switch the view to render a different source, the application could do this:

```js
map.setView(null);

// this will eventually provide the map with a new view
layer.setSource(
  new GeoTIFF({
    sources: [{url: 'https://example.com/cog-2.tif'}],
  })
);
```

Before discussing details of the implementation, it would be good to decide whether this would be a worthwhile feature.  I can imagine it would be useful in situations where someone wants to build an application that lets users browse through a catalog of imagery (that would be rendered as a single layer on a map).

In terms of the implementation, I can imagine making it so that a map without a view listens (once) for a new "viewready" type event.  In the example above, this event would be fired by the source and relayed through the layer to the map.

I'm curious to hear others' thoughts.

**Comment by m-mohr** [comment]
Definitely +1 on this. I directly have use-cases in mind here:
1. STAC Browser, where we browse through STAC catalogs to show any GeoTiffs that come across. Usually the metadata has the WGS84 geometry or at least bbox available, but in many cases the projection is missing, sometimes even the geometry or box.
2. geotiff.io, where there is absolutely no metadata provided with the files (except in the file itself)
3. Similarly to STAC Browser, we have something also in openEO, but for on-demand processed GeoTiffs which sometimes lack corresponding metadata such as projection and geometry.

**Comment by ahocevar** [comment]
I like this proposal. I think this would add a lot of convenience. I'm imagining auto-configuration to work something like this:

- Use the first added layer and its source for auto-configuration.
- Take the projection from the source, and configure the view's resolutions from it.
- If the layer has an extent, take it. If not, but if the source has one, take it. Configure initial zoom and center from it.

**Comment by jahow** [comment]
Great idea, indeed this would make developer experience much easier in the mentioned scenario. Would this work for all layer types though? E.g. OGC layers (WMS, WMTS) where the extent typically requires an additional request that the source does not do by default.

Also to make this a bit less of a "magic" feature, maybe offering a `view: 'auto'` option on the map would be nice?

Last question: what would the user see while the extent is being requested? Having some sort of placeholder screen would be nice instead of nothing at all, like it is currently when no view is set (I think).

**Comment by NicolaiMogensen** [comment]
Right now the `GeoTIFF.js` code nulls the supplied projection, and grabs it from the geokey property of the image. It would be beneficial to have a way to supply projection and extent without it being overridden especially in the case where the GeoTIFF does not have a set of GeoKeys. It's possible to calculate the resolutions and tile sizes  from the `FileDirectory` attribute. I have created a working example in a branch here, by hacking in a test flag and setting the extent manually inside GeoTiff.js. I accidentally opened this pull-request #12699 against the openlayers repo, but it would be nice to have the opposite "magic" feature like a "manual" setting.  COG's work just aswell as static images.

**Comment by tschaub** [comment]
@NicolaiMogensen, could you please open a dedicated issue with a description of the problem and ideally an example that demonstrates the problem?  It sounds like an issue that should be fixed and is unrelated to this ticket.

**Comment by marcjansen** [comment]
> Would this work for all layer types though? E.g. OGC layers (WMS, WMTS) where the extent typically requires an additional request that the source does not do by default.
> 

AFAICT at least WMS needs to always support `EPSG:4326`, and we could use that in case of autodetecting. I find the idea of asking the server nice, but this sort of magic will of course also sometimes lead to unexpected results. 

> Also to make this a bit less of a "magic" feature, maybe offering a `view: 'auto'` option on the map would be nice?
> 

I think this is a good idea, how about `view: 'guess'`, and I think it shoudl behave as having `view` being `undefined` it would merely be a hint to future readers.

> Last question: what would the user see while the extent is being requested? Having some sort of placeholder screen would be nice instead of nothing at all, like it is currently when no view is set (I think).

Great idea, some sort of a loading animation, maybe?

**Comment by marcjansen** [comment]
I really like the general idea!

**Comment by tschaub** [comment]
I don't think it necessarily makes sense to add in any loading indicator/animation – we don't do this currently for sources that are not immediately "ready."  If someone wanted to add a loading indicator, this could be handled at the application level (maybe in a listener for "rendercomplete").

I also don't think I'll start with "guess" or "auto" or any other view property.  Instead, I'd like to make it just work if you configure a map like this:

```js
const map = new Map({
    target: 'map',
    layers: [layer],
});
```

That would generate a map that rendered the full extent of the configured layer – in cases where either the layer or its source could provide enough information to construct a view.  From a newcomer's perspective, I think this makes it easier than having to discover something like `view: 'auto'`.

I'll put together an implementation of what I have in mind.  We can discuss the details there.

**Comment by NicolaiMogensen** [comment]
Yes, sorry for contaminating this issue. I saw you merged #12709 and thank you for that :-)

**Comment by tschaub** [comment]
After some offline discussion, we decided to go with a promise-based approach.  This is a bit more explicit and shouldn't include any surprises.

The GeoTIFF source (and in the future others that can resolve view properties) has a new `source.getView()` method.  This method returns a promise for view properties – not a view itself but an object that can be passed to the view constructor.  The map constructor's `view` option now accepts a promise for view properties.  And `map.setView()` accepts the same.

To construct a map with a view that shows the full extent of a GeoTIFF source, you can now do this:

```js
const source = new GeoTIFF({
  sources: [{url: 'https://example.com/cog-1.tif'}],
});

const layer = new TileLayer({source});

// when the view resolves view properties, the map view will be updated
const map = new Map({
  target: 'map',
  layers: [layer],
  view: source.getView(), // <-- this is the new part
});
```

Then, if you want to later update the source of the layer and have the map view updated when the source resolves view properties, you can do this:
```js
const newSource = new GeoTIFF({
  sources: [{url: 'https://example.com/cog-2.tif'}],
});

layer.setSource(newSource);

// this will eventually provide the map with a new view
map.setView(newSource.getView());
```

The COG examples have been updated to use this new functionality.

**Comment by tschaub** [comment]
Maybe already clear, but if you want to override any of the source-resolved view properties, you have a chance to do that with something like this:
```js
// use all the source-resolved view properties except zoom
map.setView(newSource.getView().then(options => ({
  ...options,
  zoom: 10,
})));
```
