### ISSUE TITLE
Typescript errors in Visual Code

### ISSUE THREAD

**Issue by RobertVogt** [openlayers/openlayers#12640]
Running OL 6.6.1 and receiving a bunch of typescript errors for the ol library?

node_modules/ol/MapBrowserEvent.d.ts(42,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ol/MapBrowserEvent.d.ts(48,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ol/MapBrowserEvent.d.ts(49,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ol/MapBrowserEvent.d.ts(56,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ol/Tile.d.ts(131,47): error TS2694: Namespace '"C:/Source/MappingServices/GIT/repos/ngcMSComponentLibrary/node_modules/ol/TileState"' has no exported member 'default'.
    node_modules/ol/View.d.ts(543,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ol/View.d.ts(553,9): error TS1086: An accessor cannot be declared in an ambient context.
    node_modules/ol/format/GeoJSON.d.ts(105,33): error TS2304: Cannot find name 'Feature'.
    node_modules/ol/format/GeoJSON.d.ts(116,35): error TS2304: Cannot find name 'Feature'.
    node_modules/ol/geom/SimpleGeometry.d.ts(27,53): error TS2694: Namespace '"C:/Source/MappingServices/GIT/repos/ngcMSComponentLibrary/node_modules/ol/geom/GeometryLayout"' has no exported member 'default'.
    node_modules/ol/interaction/DragBox.d.ts(25,22): error TS2314: Generic type 'MapBrowserEvent<EVENT>' requires 1 type argument(s).
    node_modules/ol/interaction/Draw.d.ts(39,14): error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).
    node_modules/ol/interaction/Modify.d.ts(77,22): error TS2314: Generic type 'MapBrowserEvent<EVENT>' requires 1 type argument(s).
    node_modules/ol/interaction/Modify.d.ts(330,30): error TS2314: Generic type 'BaseVectorLayer<VectorSourceType>' requires 1 type argument(s).
    node_modules/ol/interaction/Select.d.ts(82,21): error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).
    node_modules/ol/interaction/Select.d.ts(88,23): error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).
    node_modules/ol/interaction/Select.d.ts(94,22): error TS2314: Generic type 'MapBrowserEvent<EVENT>' requires 1 type argument(s).
    node_modules/ol/interaction/Translate.d.ts(47,26): error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).
    node_modules/ol/interaction/Translate.d.ts(67,22): error TS2314: Generic type 'MapBrowserEvent<EVENT>' requires 1 type argument(s).
    node_modules/ol/proj/Units.d.ts(7,31): error TS2315: Type 'Object' is not generic.
    node_modules/ol/source/Cluster.d.ts(110,31): error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).
    node_modules/ol/source/Cluster.d.ts(121,23): error TS2314: Generic type 'VectorSource<Geometry>' requires 1 type argument(s).
    node_modules/ol/webgl/Buffer.d.ts(13,14): error TS2303: Circular definition of import alias 'STATIC_DRAW'.
    node_modules/ol/webgl/Buffer.d.ts(14,14): error TS2303: Circular definition of import alias 'STREAM_DRAW'.
    node_modules/ol/webgl/Buffer.d.ts(15,14): error TS2303: Circular definition of import alias 'DYNAMIC_DRAW'.
    node_modules/ol/webgl/Helper.d.ts(35,14): error TS2303: Circular definition of import alias 'UNSIGNED_BYTE'.
    node_modules/ol/webgl/Helper.d.ts(36,14): error TS2303: Circular definition of import alias 'UNSIGNED_SHORT'.
    node_modules/ol/webgl/Helper.d.ts(37,14): error TS2303: Circular definition of import alias 'UNSIGNED_INT'.
    node_modules/ol/webgl/Helper.d.ts(38,14): error TS2303: Circular definition of import alias 'FLOAT'.

**Comment by EvertEt** [comment]
Probably a duplicate of #12497. It suggests adding `"skipLibCheck": true` to your tsconfig.

**Comment by RobertVogt** [comment]
Adding "skipLibCheck" did not mitigate the issue

**Comment by ahocevar** [comment]
Are you sure, @RobertVogt? Maybe you have a more involved configuration than just a single `tsconfig.json`, and a different configuration is sneaking in? The errors you posted above are a typical symptom of having `skipLibCheck: false` in the `compilerOptions`.
