### ISSUE TITLE
webglpointlayer feature

### ISSUE THREAD

**Issue by abigstupidbear** [openlayers/openlayers#12658]
hi. can webglpointlayer support these？
1 draw line and polygon.
2 draw text 
3 support wrapx

if not . do you have any plan to achieve these？
wating for your reply.

**Comment by jahow** [comment]
> hi. can webglpointlayer support these？
> 1 draw line and polygon.
> 2 draw text
> 3 support wrapx

Not yet. For 1 I have planned work on an experimental renderer in the following months (no promise). 2 is more unlikely considering how much trouble text rendering in webgl is. 3 is definitely doable right now, although there is no plan for it that I know of.
