### ISSUE TITLE
Collection.push() doesn't work after Collection.clear() 

### ISSUE THREAD

**Issue by chinchillaLiao** [openlayers/openlayers#12659]
**Describe the bug**

Version 6.6.1
ol/Collection~Collection
clear() 

After executing collection.clear(): 
1. The collection.extend() becomes weird, the collection itself, the input array and the output collection all become empty after execution. 
2. The collection.push() doesn't add anything into the collection, the collection keeps being empty.

**To Reproduce**
3. See error 

**Expected behavior**
1. Don't change the input array.
2. Add elements to the collection. This pushes each item in the provided array to the end of the collection.

**Comment by ahocevar** [comment]
Please provide the complete code sequence that shows the issue.

**Comment by MoonE** [comment]
Are you providing an array to the Collection constructor and changing that array afterwards in your own code?
You should not do that, the Collection is not copying that array, changing it will cause problems.

**Comment by chinchillaLiao** [comment]
the array inputted to the extend() function might be from the collection and I didn't notice that, that's why after collection.clear() the array becomes empty. I'm Sorry for disturbance.
