### ISSUE TITLE
GeoTIFF source transition attribute

### ISSUE THREAD

**Issue by sampov2** [openlayers/openlayers#12668]
I'm using GeoTIFFs with OpenLayers and would like to control the transition option for GeoTIFF sources. However it seems the current implementation does not support this. The DataTile constructor also has many other options that could be useful for GeoTIFFs (for example opaque, cacheSize) and could also be passed to the super constructor.

What I'd like to see:

```javascript
new GeoTIFF({
  sources: [ ... ],
  transition: 0,
});
```

PS. Thanks for the great work on WebGL & GeoTIFF support!

**Comment by tschaub** [comment]
@sampov2 - Inspired by your comment about `cacheSize`, I removed it as an option from `ol/source/DataTile.js` sources and added it as an option for `ol/layer/WebGLTile.js` layers.

As @ahocevar mentioned, the WebGL tile layer renderer maintains its own cache of tile textures, and we don't need an additional cache of tiles on the source.  See #12671 (this also fixes a current issue where the WebGL tile renderer never tries to expire tiles from the source cache).

**Comment by sampov2** [comment]
Thanks for quickly working on this! I appreciate analyzing which options are really useful & meaningful in this context. I'll try this out and get back to you
