### ISSUE TITLE
KML Symbol Alignment/Placement/Size

### ISSUE THREAD

**Issue by lcrumbliss** [openlayers/openlayers#12670]
I believe there is a bug with the anchor point for some symbols when displaying a KML layer.

I'm using the latest examples, specifically this one:
https://openlayers.org/en/latest/examples/drag-and-drop-custom-kmz.html

Dragging the attached kml file into that example, I can see that point symbols seem to be anchored at the center-bottom.
This is mostly visible at the two star symbols that should be at the center point of the two red circles.

![image](https://user-images.githubusercontent.com/43833528/131180120-202b13a4-5cad-4508-83d2-86b21f78eaff.png)

I've attached a screen clipping from Google Earth to show how it is supposed to look. 
![image](https://user-images.githubusercontent.com/43833528/131180163-d67c73f5-00fa-4dbd-b559-623c8b786b92.png)

Further, the point symbols seem to be much larger in the example than how they are displayed in Google Earth.

[20180910_Sonar-Pool27.zip](https://github.com/openlayers/openlayers/files/7069077/20180910_Sonar-Pool27.zip)

**Comment by mike-000** [comment]
The anchor is an old issue #4829 with all Google icons being treated alike which was never resolved.  According to https://stackoverflow.com/a/22569590/10118270 the interpretation of scale is also inconsistent with Google Earth which scales from 32 pixels, not the 64 pixel original image.

**Comment by mike-000** [comment]
See example with fixes at https://deploy-preview-12674--ol-site.netlify.app/examples/drag-and-drop-custom-kmz.html

**Comment by lcrumbliss** [comment]
That's awesome.  Well done.

**Comment by lcrumbliss** [comment]
Actually, the label anchors are no longer correct.  Should that be another bug report?

**Comment by mike-000** [comment]
The text offset now needs to be based on the normalized 32 pixel image and the specified scale, not the original image size.  That should be done as part of this change.

**Comment by mike-000** [comment]
The labels offsets are now correctly scaled.  The precise position relative to the icon will depend on the icon anchor, as it always did.  Icons which are now correctly center anchored have a label top left while the bottom anchored parking icon has a center left label.

**Comment by lcrumbliss** [comment]
Thanks Mike!
