### ISSUE TITLE
Could the canvasFunction in ol.source.ImageCanvas load several images ?

### ISSUE THREAD

**Issue by iteayyy** [openlayers/openlayers#12673]
I add one image to the map by defining canvasFunction in ol.source.canvas, but it seems to add only one image at a time.
Is there any way to load several images to the map in the same source ?  Instead of add images in difference source in the same layer.
Any help will be appreciated.

**Comment by ahocevar** [comment]
This is definitely possible. You can use `CanvasRendeingContext2D#drawImage()` to overlay multiple images on the `ol/source/ImageCanvas`'s canvas.

**Comment by iteayyy** [comment]
Thank you so much @ahocevar ! 
But the canvas doesn't work with the OLCesium plug-in. The imgaes drawn by the CanvasRendeingContext2D can not be displayed in OLCesium when I set ol-3d enabled. 

```
var imgsource = new ol.source.ImageCanvas({
    canvasFunction: function(extent, resolution, pixelRatio, size, projection){
        ......
    }
});

map.addLayer(new ol.layer.Image({source: imgsource}));

const ol3d = new olcs.OLCesium({map: map});
ol3d.setEnabled(true);
```

I have another two questions:
How about drawing images in canvas respectively? 
And Will Openlayers support user-defined image loading mechanism, or user-defined TMS service in the future?
