### ISSUE TITLE
VectorTile rendered incorrectly

### ISSUE THREAD

**Issue by MaxDragonheart** [openlayers/openlayers#12680]
I'm using VectorTile from GeoServer and often happen something like that:
[![enter image description here][1]][1]
Polygons are partially rendered or clipped.

I use the code below for add the layer on map:

      const style_simple = new ol.style.Style({
        fill: new ol.style.Fill({
          color: '#ADD8E6',
        }),
        stroke: new ol.style.Stroke({
          color: '#880000',
          width: 1
        }),
      });
      function simpleStyle(feature, resolution) {
        return style_simple;
      };
      const layer = 'test2:project_subareaurban_polygon_8';
      const projection_epsg_no = '3857';
      const vectortile_layer = new ol.layer.VectorTile({
        declutter: true,
        style:simpleStyle,
        opacity: 0.75,
        declutter: true,
        source: new ol.source.VectorTile({
          format: new ol.format.MVT({featureClass: ol.Feature}),
          url: 'http://localhost:8600/geoserver/gwc/service/tms/1.0.0/' + layer +
                '@EPSG%3A'+projection_epsg_no+'@pbf/{z}/{x}/{-y}.pbf'
        }),
      });

Is this a bug of OL?

  [1]: https://i.stack.imgur.com/vcJyY.jpg

**Comment by ahocevar** [comment]
This looks very similar to https://openlayers.org/en/latest/examples/vector-tile-selection.html, where I do not see this problem. Have you double-checked if your tiles contain the correct polygons?

**Comment by MaxDragonheart** [comment]
It seems that the problem is solved by itself. However, yes @ahocevar I've used part of code that is on the example, all polygons are topologically correct.
