### ISSUE TITLE
Create a polygon from coordinates

### ISSUE THREAD

**Issue by MaxDragonheart** [openlayers/openlayers#12685]
I've a coordinates of a polygon:

      let coordinatesFromSelection = [
        [
          [
            1587090.6821707229,
            4991304.505822134
          ],
          [
            1587597.0774831122,
            4990783.778566942
          ],
          [
            1587377.3210267923,
            4990076.736055303
          ],
          [
            1586655.946572351,
            4989895.198113127
          ],
          [
            1586149.5512599617,
            4990415.925368319
          ],
          [
            1586364.5304020138,
            4991118.1905656895
          ],
          [
            1587090.6821707229,
            4991304.505822134
          ]
        ]
      ];

I want create a polygon with that coordinates and add it on a map:

      const selectedGeometry = new ol.geom.Polygon(coordinatesFromSelection); 
      const polygonFeature = new ol.Feature({
        geometry: selectedGeometry
      });
      const emptySource = new ol.source.Vector({
        features: polygonFeature
      });
      const vector = new ol.layer.Vector({
        source: emptySource,
        style: selectedPolygonStyle
      });
      map.addLayer(vector);

But using the code above I see this error:

> Uncaught TypeError: r.features.getArray is not a function
>     n Vector.js:296
>     <anonymous> (index):189 Vector.js:296:34

I'm trying to follow [this][1] indication to achieve my goal but I don't understand what I've done wrong.

  [1]: https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html

**Comment by Rskut** [comment]
put your polygon feature in an array:

features: [polygonFeature]

**Comment by MaxDragonheart** [comment]
Thank you @Rskut :)
