### ISSUE TITLE
How to cleanly display reprojected OSM layer

### ISSUE THREAD

**Issue by nboisteault** [openlayers/openlayers#12681]
Hi,
I'd like to display a reprojected OSM layer without having cut labels.

If I type `2154` in `Search projection` with [0], all tiles have the same `z` index so no labels are cut.

![image](https://user-images.githubusercontent.com/2145040/131361764-3e4cb479-8258-4847-bb3e-1cf747284906.png)

I forked [1] and modified source code to reproject in `EPSG:2154` and obtained [2]. Now if I Zoom to Paris (France) I get cut labels and different `z` index between tiles at top and bottom.

![image](https://user-images.githubusercontent.com/2145040/131360913-9b0e4ee6-34d5-4455-9525-ef5a6d868a00.png)

What need to be changed in second example to get desired behavior as in first one? Thanks for your help.

[0] : https://openlayers.org/en/latest/examples/reprojection-by-code.html
[1] : https://openlayers.org/en/latest/examples/reprojection-wgs84.html
[2] : https://codesandbox.io/s/reprojection-wgs84-forked-of2ux?file=/main.js

**Comment by mike-000** [comment]
The first example sets a projection extent which limits coverage to an area around France, and with only a small variation in scale across that region it is easy to use the same z level.  The second example has no projection extent and allows most of the world to be seen be in EPSG:2154 and where it is not possible to use the same z level in all places the changeover could happen anywhere.

**Comment by nboisteault** [comment]
Thanks @mike-000 !
I have modified [2] to use `setExtent()` on the projection set for the `View()` and it works nicely!
But I don't understand what the difference between this manner and setting the `extent` directly for `View()`.
And I don't understand the purpose of the `setWorldExtent()` method neither.
