### ISSUE TITLE
Problem with VectorTile selection

### ISSUE THREAD

**Issue by MaxDragonheart** [openlayers/openlayers#12692]
In my map when I select a feature from VectorTile I see the problem below at the borders of tiles.

![Screenshot from 2021-09-03 08-56-52](https://user-images.githubusercontent.com/18444902/131964051-1b9de269-50f1-4009-9ba2-b3a8f3eae985.png)

The numbers displayed are the id of the single polygon. As You can see in the origin the hexagons aren't separeted.

**Comment by MaxDragonheart** [comment]
The tiles are managed by Geoserver 2.19

**Comment by ahocevar** [comment]
Looks like you are displaying the selection in a Vector layer. You should be displaying it in a VectorTile layer. Refer to https://openlayers.org/en/latest/examples/vector-tile-selection.html for the recommended way of doing selection with vector tiles.

**Comment by MaxDragonheart** [comment]
I'm currently use `VectorTile` in my code:

```
  const vectortile_layer = new ol.layer.VectorTile({
    declutter: true,
    style:simpleStyle,
    opacity: 0.75,
    source: new ol.source.VectorTile({
      format: new ol.format.MVT({featureClass: ol.Feature}),
      url: 'http://localhost:8600/geoserver/gwc/service/tms/1.0.0/' + layer +
            '@EPSG%3A'+projection_epsg_no+'@pbf/{z}/{x}/{-y}.pbf'
    }),
    renderMode: 'vector',
  });
```

**Comment by ahocevar** [comment]
Please take a look at the example I linked. You probably tried to use the `Select` interaction, which produces the behavior you described.

**Comment by MaxDragonheart** [comment]
Yes I'm using `ol.interaction.Select`,  so this is the problem. Thank you :)
