### ISSUE TITLE
Cloud Optimized GeoTiffs (COG) without georeference can't be displayed. 

### ISSUE THREAD

**Issue by NicolaiMogensen** [openlayers/openlayers#12701]
**Describe the bug**
Cloud Optimized GeoTiffs without an explicit geoference can't be added to a map. Projection is ignored (it's set to null inside `GeoTiff.js` ) and since GeoKeys can't be set, internal methods for boundingbox and origin fails with a reference to a missing "affine transformation". 

It should be possible to use COGs like a static-image as in https://openlayers.org/en/latest/examples/static-image.html , with the "functionality" of https://openlayers.org/en/latest/examples/zoomify.html

In the images "FileDirectory" resides information about both tilesizes, resolution and dimensions so creating a TileGrid should be possible without the geokeys, if we allow projection to be local as in the "static-image" example. 

**To Reproduce**
1. Use this example COG: https://tmp-asger-public.s3.eu-central-1.amazonaws.com/2017_84_40_1_0015_00008062.cog.tif in the COG example
2. See that the layer is not added, and that the "error" property on the source complains about a missing affine transformation
3. See error

**Expected behavior**
I would expect Cloud Optimized Geotiffs to display with a local coordinate system as in the static-image example, if no georeference exists. I would expect that I would be able to show the COG in a pure local coordinate system or with a supplied projection. 

Side info: 
We have verified that this is definitely possible in an own branch, by passing a flag to `GeoTIFF.js` and gathering the information needed from the `FileDirectory` property of the tiff images, and by setting the origin point in the upper left corner `[0, h]`.

See: https://github.com/Septima/openlayers/commit/d85585275c2a56e124c6aff83e228cd1e86f2e79 for a working "hacked" example.

**Comment by tschaub** [comment]
Thanks for the report, @NicolaiMogensen.  Ideally you could add geotransform so the image could be used in conjunction with other spatial data.  But I can see how it could be nice to just display the image in pixel space if you don't control the image source.  I've put together #12709 to support rendering GeoTIFFs in pixel space when they don't have the appropriate metadata to be able to extract bounds, origin, or resolution information (in geo terms).

Note that the `projection` property belongs as an option of the `ol/source/GeoTIFF` constructor.  In your example, you have it set as a property of the first of the `sources` passed to the constructor.  But as you discovered, it is not required to make your example work.

**Comment by tschaub** [comment]
With the changes in #12709 and #12712, the complete working example looks like this:

```js
import GeoTIFF from '../src/ol/source/GeoTIFF.js';
import Map from '../src/ol/Map.js';
import Projection from '../src/ol/proj/Projection.js';
import TileLayer from '../src/ol/layer/WebGLTile.js';
import View from '../src/ol/View.js';
import {getCenter} from '../src/ol/extent.js';

const extent = [0, 0, 13470, 8670];

const projection = new Projection({
  code: 'custom',
  units: 'pixels',
  extent: extent,
});

const map = new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: new GeoTIFF({
        convertToRGB: true,
        sources: [
          {
            url: 'https://tmp-asger-public.s3.eu-central-1.amazonaws.com/2017_84_40_1_0015_00008062.cog.tif',
            nodata: 0,
          },
        ],
      }),
    }),
  ],
  view: new View({
    projection: projection,
    center: getCenter(extent),
    extent: extent,
    zoom: 1,
  }),
});
```

**Comment by aborruso** [comment]
@tschaub thank you very much for your sample code.

I have tried to use it, by I'm not able to render the image. What am I doing wrong?

https://codesandbox.io/s/cog-notgeo-u8pjtd?file=/main.js
