### ISSUE TITLE
WMS Capabilities Parsing example not working

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#12717]
**Describe the bug**
The example is not working since v6.6.0 when run directly from the template page..  It does work when opened in CodeSandbox.

**To Reproduce**
Open https://openlayers.org/en/latest/examples/wms-capabilities.html and open console to see error .

**Expected behavior**
Working example.

**Comment by tschaub** [comment]
It looks like this is an issue with `terser` improperly renaming the `readNonNegativeInteger` export from `ol/format/xsd.js` (named `o.Xr` in the exports but called as `o.t`).  Trying to find a version of `terser` that works so we can narrow down the issue.

**Comment by tschaub** [comment]
I'm seeing the same issue with `terser@5.3.4`, `terser-webpack-plugin@4.2.3`, and `webpack@5.1.0`.  That should be the same version of `terser` that worked in our [6.5.0 example](https://openlayers.org/en/v6.5.0/examples/wms-capabilities.html).  It doesn't look like there are any significant changes to our `xsd.js` or `WMSCapabilities.js`, so maybe an issue with `webpack` or `terser-webpack-plugin`.
