### ISSUE TITLE
Add or remove feature from vector source doesn't work while map is dragging or zooming 

### ISSUE THREAD

**Issue by Zigridar** [openlayers/openlayers#12724]
**Describe the bug**
I use vector layer with vector source which is asyncronously changing by adding or removeng features.
When vectorSource.addFeature/removeFeature is calling while map is dragging or zooming map doesn't update vector layer with features and they are freezing on layer.

**To Reproduce**
1. Go to https://codesandbox.io/s/qoj8o
2. Click on map and drag it more then two second
3. One feature is freezing on map

In this example feature is added/removed on/from layer every second by timer.

**Expected behavior**
Feature must be added/removed on/from layer immediatelly independing on dragging or zooming.

**Comment by ahocevar** [comment]
You can configure the vector layer with `updateWhileInteracting: true, updateWhileAnimating: true`. Then the layer should be updated immediately when you remove a feature.

**Comment by Zigridar** [comment]
> You can configure the vector layer with `updateWhileInteracting: true, updateWhileAnimating: true`. Then the layer should be updated immediately when you remove a feature.

Thank you so much for responding so quickly! It works!
