### ISSUE TITLE
Typings of Dragbox are missing boxstart

### ISSUE THREAD

**Issue by boeckMt** [openlayers/openlayers#12725]
**Describe the bug**
The Typings `DragBox.d.ts` are missing `boxstart` event.

So if I want to use something like  
```ts
const dragBox = new DragBox(dragBoxOptions);
dragBox.on('boxstart', (evt) => {
        ...
}

dragBox.on('boxend', (evt) => {
        ...
});
```
`boxend` is working but I get a TypeError for `boxstart` 

> No overload matches this call.
>  The last overload gave the following error.
>    Argument of type 'string' is not assignable to parameter of type '("error" | "change" | "propertychange" | "change:active" | >"boxdrag" | "boxend" | "boxcancel")[]'.ts(2769)
> DragBox.d.ts(66, 440): The last overload is declared here.

**To Reproduce**
You can also reproduce this on https://codesandbox.io/s/wk0bs?file=/main.js 

1. write `dragBox.on('` and the completion don't has any `boxstart`.

**Expected behavior**
The `boxstart` event should also be in `DragBoxOnSignature`

**Version**
- ol: 6.6.1

**Comment by simonseyock** [comment]
Thanks for reporting. It is fixed with the linked PR
