### ISSUE TITLE
Change in default behavior: map events are fired while hovering controls

### ISSUE THREAD

**Issue by iamvdo** [openlayers/openlayers#12721]
**Bug**
There is a change in default behavior between 6.3.0 and 6.4.0, without clear explanation.
In 6.3.0, when adding an event to the map, it is not fired when this event occurs in control or overlay. That is no longer the case since 6.4.0.

**To Reproduce**
Let' make a simple map (with 6.3.0), and a `pointermove` event

<details>
<summary>See full code</summary>
  
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.3.0/css/ol.css">
  <style>
    .map {
      height: 500px;
    }
  </style>
</head>
<body>
  <div id="app">
    <div id="map" class="map"></div>
  </div>
  <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.3.0/build/ol.js"></script>
  <script>
    let map = new ol.Map({
      layers: [
        new ol.layer.Tile({
          title: "OpenStreetMap",
          source: new ol.source.OSM()
        })
      ],
      target: document.getElementById('map'),
      view: new ol.View({
        center: [0, 0],
        zoom: 3
      })
    });

    map.on("pointermove", () => {
      console.log("move");
    });

  </script>
</body>
</html>
```
</details>

**Result**
Hover over zoom controls (pointerevent is not fired). Then, change cdn urls to get 6.4.0, now event is fired even when hover over zoom controls.

I notice that using this code
```js
document.querySelector('.ol-overlaycontainer-stopevent').addEventListener('pointermove', function(e){
  e.stopPropagation();
});
```
fixes the "problem", but is it intended? Why this change?

Thanks!

**Comment by mike-000** [comment]
That restores the behaviour from versions 3, 4 and 5.  Pointermove events are propagated, but not click and wheel events, see  #11270

**Comment by iamvdo** [comment]
Thanks for clarification!
So you're basically saying it was a bug before `6.4.0`? (even if it feels a bit strange to me :)

And what about workaround? Is there a better way to circumvent that behavior?

**Comment by ahocevar** [comment]
Depends on what you want to achieve.

**Comment by iamvdo** [comment]
Well, I don't want map events to be triggered on controls and/or overlays.

**Comment by mike-000** [comment]
There will be some side-effects.  For example a mouse position will not update while over a control (even an attribution with transparent background).

**Comment by ahocevar** [comment]
The reason for this behavior is that you usually do not want to start an interaction (e.g. DragPan) when over a control, but you want the map to continue panning when you're already panning and the pointer moves over a control. This is what other web maps do as well.

> Well, I don't want map events to be triggered on controls and/or overlays.

What do you need the event for? Maybe it is better to listen to a native DOM event and check if the event target is of interest for your event handler.

You could do something like this:
```js
map.getTargetElement().addEventListener("pointermove", (e) => {
  if (e.target instanceof HTMLCanvasElement) {
    console.log('move');      
  }
});
```

**Comment by iamvdo** [comment]
Thanks for clear explanation.

What I'm trying to achieve is related to vector layer (with points) and a basic overlay that shows on hover. I want the popup to remain open even if another point is below the popup and the mouse is hovering it.

I will be able to find a solution with your help.
