### ISSUE TITLE
Error with latest version (6.7.0) when trying to run with Angular

### ISSUE THREAD

**Issue by mhosman** [openlayers/openlayers#12729]
```
Warning: E:\.....\node_modules\geotiff\src\compression\deflate.js depends on 'pako/lib/inflate'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: E:\.....\node_modules\geotiff\src\geotiffimage.js depends on 'txml'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Warning: E:\.....\node_modules\geotiff\src\source\blockedsource.js depends on 'lru-cache'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

./node_modules/geotiff/src/source/client/http.js:2:0-24 - Error: Module not found: Error: Can't resolve 'http' in 'E:\.....\node_modules\geotiff\src\source\client'
Did you mean './http'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (E:/...../src, node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }

./node_modules/geotiff/src/source/client/http.js:3:0-26 - Error: Module not found: Error: Can't resolve 'https' in 'E:\.....\node_modules\geotiff\src\source\client'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }

./node_modules/geotiff/src/source/file.js:2:0-39 - Error: Module not found: Error: Can't resolve 'fs' in 'E:\.....\pwa\node_modules\geotiff\src\source'
```

**Comment by ryantxu** [comment]
I don't think this is a bug with openlayers -- read the message a bit more and it tells you that your webpack config needs to know what to do with http/https.  I got the same error and resolved it using:

https://github.com/grafana/grafana/pull/39057/files#diff-80463b1c065d6048b7ea4efcfd4e2ff8f79ef503f461348e57f497496c751f1eR51

**Comment by ahocevar** [comment]
Thanks for reporting this, @mhosman! These errors only occur when your application uses modules of OpenLayers that depend on geotiff.js. Like @raiyni already stated, the Webpack output tells you exactly what to do. So while I agree that this is a bit annoying, it is not a bug in OpenLayers, but a Webpack specific configuration issue that's describing itself well enough to warrant its omission in the build instructions in my opinion.

**Comment by lvenchi** [comment]
i resolved this by setting this in package.json

`"browser": {
    "fs": false,
    "http": false,
    "https": false
  }`

(those were all the modules that geotiff couldnt find)

**Comment by ahocevar** [comment]
Thanks for sharing that, @lvenchi. So the problem in OpenLayers could be fixed if geotiff.js and its dependencies (readable-stream) had the respective polyfills or fallbacks configured. readable-stream has an open issue for that already: nodejs/readable-stream#448 .

**Comment by mhosman** [comment]
Thanks guys. Anyway, adding that to the package.json doesn't solve the problem (at least for me).

**Comment by imagoiq** [comment]
I have the same issue with Angular 12 which hide and doesn't allow easy access to the webpack config. Anyway, by default, it set `node` to false in the webpack config. Should be sufficient? https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/configs/browser.ts#L97

**Comment by ahocevar** [comment]
@imagoiq Yes, that should be sufficient.

**Comment by gimerstedt** [comment]
did anyone using vitejs solve this?

i tried a few combinations of https://github.com/rollup/plugins/tree/master/packages/node-resolve and https://github.com/snowpackjs/rollup-plugin-polyfill-node without much success.

**Comment by PeterSteen01** [comment]
Same here. No joy with the package.json fix. So OL 6.7 is put on hold for the time being.

**Comment by imagoiq** [comment]
The only working fix I've found is this 😕: https://github.com/angular/angular-cli/issues/20819#issuecomment-842307462

**Comment by ahocevar** [comment]
@imagoiq That fix makes sense, and is equivalent to the Webpack configuration described above.

Also, I'm wondering if anyone is getting these errors even when the new GeoTIFF source is not used in the application. In a vanilla Webpack setup, the problem only occurs when it is used.

**Comment by PeterSteen01** [comment]
@ahocevar I got the error without using the geotiff source. Just the simplest of maps with a Tile layer and an OSM source.

**Comment by ahocevar** [comment]
@PeterSteen01 What's your setup? I just tried to reproduce this with a fresh Angular project, and for me a basic example with an OSM layer works fine without any build errors. This is what I did:

1. Run `ng new ol67-test`
1. Run `npm install ol`
1. Replace content of `src/app/app.component.html` with
    ```html
    <style>
    html, body, #map {
      width: 100%;
      height: 750px;
    }
    </style>

    <div id="map"></div>
    ```
1. Replace content of `src/app/app.component.ts` with
    ```ts
    import { Component, OnInit } from '@angular/core';
    import Map from 'ol/Map';
    import View from 'ol/View';
    import OSM from 'ol/source/OSM';
    import TileLayer from 'ol/layer/Tile';

    @Component({
      selector: 'app-root',
      templateUrl: './app.component.html',
      styleUrls: ['./app.component.css']
    })
    export class AppComponent implements OnInit {
      ngOnInit() {
        const map = new Map({
          target: 'map',
          layers: [
            new TileLayer({
              source: new OSM()
            })
          ],
          view: new View({
            center: [0, 0],
            zoom: 2
          })
        })
      }
    }
    ```
1. Modify `angular.json` to include OpenLayers styles
    ```diff
    --- a/angular.json
    +++ b/angular.json
    @@ -27,7 +27,8 @@
                   "src/assets"
                 ],
                 "styles": [
    -              "src/styles.css"
    +              "src/styles.css",
    +              "node_modules/ol/ol.css"
                 ],
                 "scripts": []
               },
    ```
1. Modified `tsconfig.json` to skip type checking of depencencies:
    ```diff
    --- a/tsconfig.json
    +++ b/tsconfig.json
    @@ -19,7 +19,8 @@
         "lib": [
           "es2018",
           "dom"
    -    ]
    +    ],
    +    "skipLibCheck": true
       },
       "angularCompilerOptions": {
         "enableI18nLegacyMessageIdFormat": false,
    ´``

With this setup, both `npm start` and `npm run build` work as expected.

Only when you add a GeoTIFF source, you need to make more changes to your Angular configuration. You can follow Digital Ocean's excellent [How To Use Custom webpack Configurations with Angular CLI Builders](https://www.digitalocean.com/community/tutorials/angular-custom-webpack-config) tutorial, with this `custom-webpack.config.js`:
```js
module.exports = {
  resolve: {
    fallback: {
      http: false,
      https: false,
      fs: false,
      buffer: false,
      url: false
    }
  }
};
```

I created a git repository with this minimal application and the working configuration: https://github.com/ahocevar/ol67-test.

**Comment by PeterSteen01** [comment]
@ahocevar You're right! The setup provided does not throw errors. Thanks a lot.

**Comment by undefinedSolutions** [comment]
@ahocevar Thanks for your setup! But you use `angular-builders/custom-webpack:browser` but in an projekt we use `@angular-devkit/build-angular:browser,` I was not able to get Ol 6.7.0 running with this builder... 

Perhaps anyone has a solutions for me.

**Comment by ahocevar** [comment]
@undefinedSolutions `@angular-builders/custom-webpack` is a drop-in replacement for `@angular-devkit/build-angular`. So all you need to do is `npm install @angular-builders/custom-webpack` and change `angular.json` accordingly.

**Comment by mhosman** [comment]
Sorry but I'm not using any GeoTIFF source and I still get the error. Don't know why this is happening. How this is "called"?

**Comment by ahocevar** [comment]
@mhosman Sorry, like I explained above, this is an issue with geotiff.js and its dependencies, so we cannot fix it in OpenLayers directly. For users not working with the GeoTIFF source, there should not be a problem. I'm surprised you're saying this also happens without using a GeoTIFF source in your application. Maybe your Webpack configuration does more work than it needs to, e.g. call loaders that load all files in `node_modules`?

**Comment by mhosman** [comment]
Thanks @ahocevar I fixed the issue. It seems I was doing the wrong import and importing all the sources:

Changed this:
`import { Vector as VectorSource, XYZ } from 'ol/source';`

To this:
```
import VectorSource from 'ol/source/Vector';
import XYZ from 'ol/source/XYZ';
```

**Comment by pelord** [comment]
@mhosman , this last solution fixed the problem !

**Comment by Morgul** [comment]
Just wanted to say that `geotiff` v1.0.6 just dropped with a fix for this. Just removing an readding openlayers to my project got the right version, and now my project compiles with vite.

**Comment by undefinedSolutions** [comment]
@Morgul Yeah with npm start etc it works fine... but we use prerender... and there it is not working
`✖ Prerendering routes to /home/.../browser failed.
Cannot find module 'fs'`
I have also tried to implement the suggestion of  @ahocevar for the server, unfortunately without success...

**Comment by Morgul** [comment]
@undefinedSolutions that's odd, because I use prerender too (or, well, vite does); and it was failing until I updated it to `geotiff` 1.0.6, and now prerendering works for me.

To be clear v1.0.6 of `geotiff` literally just dropped yesterday, a few hours before my comment. You might want to make sure that's the version you've got installed and if not update and give it another shot. 😄

**Comment by undefinedSolutions** [comment]
Out settings looks like this

- angular.json

```"prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "browserTarget": "build",
            "serverTarget": "server",
            "routes": [
              "/blog/",
               ...
              "/faq",
              "/login"
            ]
          },
          "configurations": {
            "dev": {
              "browserTarget": "build:dev",
              "serverTarget": "server:dev"
            },
            "production": {
              "browserTarget": "build:production",
              "serverTarget": "server:production"
            }
          }
        }
```

- angular.json
``` 
  "dependencies": {
    ...
    "geotiff": "1.0.6",
    "ol": "6.7.0",
    ... 
```
I deleted all node_modules and installed them again...

**Comment by ahocevar** [comment]
@undefinedSolutions You could try

    npm upgrade geotiff
    npm dedupe geotiff
