### ISSUE TITLE
Geometery accros antimeridian disappear

### ISSUE THREAD

**Issue by mlhotellerie** [openlayers/openlayers#12720]
Hello, 

When providing OL a geometry than cross antimeridian, the repeated right side can disappear.

I forked one of examples to show this :

https://codesandbox.io/s/geojson-forked-e53y7?file=/main.js

With a polygon that cross antimeridian
```
{
  'type': 'Feature',
  'geometry': {
    'type': 'Polygon',
    'coordinates': [
      [
        [-10, -50],
        [-10, 50],
        [-350, 50],
        [-350, -50],
        [-10, -50],
      ],
    ]
  }
}
```

If you pan on the right to show antimeridian, it will be displayed. Zoom/pan so we can't see it, geometry is hiddden.

![image](https://user-images.githubusercontent.com/12936338/132474830-d9e5d76a-f138-4cdc-8c89-cbe7b3e24e5b.png)
![image](https://user-images.githubusercontent.com/12936338/132474893-7f3acb55-4623-4631-93a7-7361812ab67d.png)

**Comment by mike-000** [comment]
See the description of `wrapX` in https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html  Only vectors in the normal world extent will wrap correctly.  To wrap the polygon must be split into a MultiPolygon at the antimeridian, e.g. Russia, Fiji and Antarctica in https://openlayers.org/en/latest/examples/vector-layer.html

**Comment by mlhotellerie** [comment]
Ok, as wrap is default to true I didnt saw this comment.
