### ISSUE TITLE
Typescript signatures for .on() methods don't distinguish between listening to single and multiple events

### ISSUE THREAD

**Issue by ejn** [openlayers/openlayers#12733]
The type signatures for the .on() methods (e.g. in Observable and all subclasses) don't allow correctly to distinguish between calling with a single event name (`.on('change', (e) => {...})`) which returns a single `EventsKey` and calling with multiple event names (`.on(['change', 'error'], (e) => {...})`), returning an array of `EventsKey`.

This makes using the result in Typescript somewhat inelegant as it is necessary to always cast to the correct type (`... as EventsKey` or `... as EventsKey[]` respectively).

(may also apply to other ways of attaching listeners which return one or more `EventsKey`).

Using a "pure" Typescript definition it would be fairly easy to correctly represent the overridden signature, similar to the following:
```ts
declare class Observable extends EventTarget {
    on(type: string, listener: (e: any) => any): EventsKey;
    on(type: string[], listener: (e: any) => any): EventsKey[];
    on(type: string|string[], listener: (e: any) => any): EventsKey|EventsKey[] {
        ...
    }

    ...
}
```

Is it possible to produce such overridden signatures using the JSDoc? I couldn't find a trivial way to do it, but maybe someone with more knowledge of the JSDoc -> Typescript declarations has a good solution?

**Comment by ahocevar** [comment]
Since `EventsKey` is nothing your app needs to know about in detail, we could also specify `any` as return type, no?

**Comment by ejn** [comment]
Returning `any` would only work if `unlistenByKey()` also accepts `any`! However this would also completely remove the type safety at this point, as (at least currently) it is not possible to pass an array of `EventsKey` to `unlistenByKey()`.

Maybe this could be a nice improvement which would also solve the problem - having something like `type EventsKeyLike = EventsKey|EventsKey[];`, and thus making it no longer necessary to distinguish between them.

The following (simplified, just hacked together for this reply, but based more or less on a true class) illustrates a typical use case for me. Currently the compiler complains that `Events|EventsKey[]` cannot be assigned to `EventsKey`. In `@types/ol` the signature override obviously worked correctly - but for obvious reasons I would prefer to use the inbuilt type definitions if possible.

```ts

class ExampleListener extends Disposable {

    const listeners: Set<EventsKey> = new Set();

...

    public setMap(map: PluggableMap): void {
       const layers = map.getLayers();
       this.listeners.add(layers.on('add', (e: CollectionEvent) => this.listenToLayer(e.element)));
       layers.forEach(layer => this.listenToLayer(layer));
    }

    protected listenToLayer(layer: BaseLayer): void {
        this.listeners.add(layer.on('propertychange', (e) => {...}));
    }

    protected disposeInternal(): void {
        this.listeners.forEach((key) => unlistenByKey(key));
        this.listeners.clear();
        super.disposeInternal();
    }
}
```

**Comment by ahocevar** [comment]
I'm sure @simonseyock will be able to fix this.

**Comment by simonseyock** [comment]
Yes, there should be a way. I look into it.

**Comment by simonseyock** [comment]
So I did not change the the parameter of `unlistenByKey` but let on return the more specific type.

**Comment by ejn** [comment]
thanks @ahocevar and @simonseyock !
