### ISSUE TITLE
6.7.0: Cannot declare a let variable twice: 't'

### ISSUE THREAD

**Issue by vsevjednom-cz** [openlayers/openlayers#12738]
**Describe the bug**
Webpage doesn't show anything.
`Warning: https://openlayers.org/en/main/build/ol.js:2 SyntaxError: Cannot declare a let variable twice: 't'.`

**To Reproduce**
I'm using `cutycapt` in terminal. It will do nothing. `wkhtmltoimage` writes this warning:
`wkhtmltoimage --debug-javascript https://some-url-with-OpenLayers`

**Comment by ahocevar** [comment]
Which web page are you looking at, @vsevjednom-c?

**Comment by ahocevar** [comment]
This will be fixed with #12734.
