### ISSUE TITLE
Cannot set cursor style 

### ISSUE THREAD

**Issue by dmitriykorobkov** [openlayers/openlayers#12735]
**Describe the bug**
I updated openlayers to 6.7 version and my `map.getViewport().style.cursor = 'some cursor'` stops working. Now, layers canvases have `cursor: initial` style, which force cursor to be `pointer`, cause of canvases are on top of viewport.

**Comment by mike-000** [comment]
Yes, it can be seen in the examples.  Translate should show grabber when over a selected feature https://openlayers.org/en/v6.6.1/examples/translate-features.html and the Icon example sets pointer when over an icon https://openlayers.org/en/v6.6.1/examples/icon.html  Neither work in 6.7.0.
