### ISSUE TITLE
Features from Select are not shown on top

### ISSUE THREAD

**Issue by jacekkow** [openlayers/openlayers#12742]
Features styled using Select are not on top as expected from "features added to an internal unmanaged layer".

See this demo, slightly adjusted [Layer Z-Index example](https://openlayers.org/en/latest/examples/layer-z-index.html):
https://gist.githubusercontent.com/jacekkow/68cb37d17f686b51a7ad1c75af3cb9a4/raw/52ff63d951a9086501d5a698389fed75e6d58061/ol_select.html

Clicking on the triangle does not bring it to the foreground - feature stays in the background, but according to docs of [ol.interaction.Select](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-Select.html):
> Selected features are added to an internal unmanaged layer.

and per [ol.layer.Layer](https://openlayers.org/en/latest/apidoc/module-ol_layer_Layer-Layer.html) docs:
> Components like module:ol/interaction/Select\~Select use unmanaged layers internally. These unmanaged layers are associated with the map using module:ol/layer/Layer\~Layer#setMap instead.
> (...)
> a zIndex of 0 is assumed for layers that are added to the map's layers collection, or **Infinity** when the layer's setMap() method was used.

So the triangle (becomes a circle after selection due to the custom style on Select) should be in front of everything else.

As far as I can tell there is no unmanaged layer at all in Select since commit https://github.com/openlayers/openlayers/commit/2ccaed0acec464c378cae0ba90be820124b0d7c5 in 2019, which broke the documented behavior.

**Comment by mike-000** [comment]
It seems some old documentation was not removed in #996 / #10003  There is no overlay for Select.  Other interactions such as Draw and Modify do still use overlay layers.

**Comment by jacekkow** [comment]
If this is a documentation issue, then how can I achieve previous behavior where selected features were on top? Style zIndex is applied before layer zIndex, so the selected features are still below layers with higher zIndex.

**Comment by mike-000** [comment]
An application can reproduce the old Select behavior by using its own overlay layer as in https://openlayers.org/en/latest/examples/vector-layer.html
