### ISSUE TITLE
Is WebGLTileLayer supported imageSmoothing?

### ISSUE THREAD

**Issue by whatdym** [openlayers/openlayers#12753]
I can't set imageSmoothing in WebGLTileLayer in v6.7.0.
Is WebGLTileLayer supported imageSmoothing?

I used `ol/layer/tile` before replacing it with WebGLTileLayer,
and with `ol/layer/tile`, I could switch on-off imageSmoothing by:

> layer.on('prerender', function (evt) {
>   evt.context.imageSmoothingEnabled = false;
>   evt.context.msImageSmoothingEnabled = false;
> });

if WebGLTileLayer  isn't supported imageSmoothing, is there anyway to achieve switching on-off imageSmoothing like that with WebGLTileLayer?
Thank you.

**Comment by ahocevar** [comment]
Currently there is no way to turn off image smoothing through the API. What you are trying to achieve in the `prerender` event only works with the canvas renderer. There is no `context` exposed for WebGL tile layers.

**Comment by whatdym** [comment]
Do you have any plan for imageSmoothing supported in WebGLTileLayer?
or the only way for tile layer with turning off imageSmoothing is `ol/layer/tile`.
Thank you.
