### ISSUE TITLE
Request Header for TileWMS requests

### ISSUE THREAD

**Issue by michelespinella** [openlayers/openlayers#12757]
Good day,
    we are implementing a webgis (Angular 11, Openlayers 6.6.1, Geoserver 2.19 for wms service), we are protecting geoserver with authentication.
We are using as follow TileWMS with a cascaded WMS (Italy cadastre):

```
   new TileLayer({
            source: new TileWMS({
              url: environment.geoserver_url,
              params: { 'LAYERS': 'xxxxx:province', 'TILED': true },
              serverType: 'geoserver',
              transition: 0,
            })
          }),
```

How we can add headers with auth on the WMS requests like "addHeader("Authorization", "Basic xxxxxxx")?
In the documentation there is the tileLoadFunction, but in angular seems to not work properly.
Could you please help us to implement correctly the wms request in angular?

Thank for any help
Michele Spinella

**Comment by pelord** [comment]
We do it through a interceptor (angular)

https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/auth/src/lib/shared/auth.interceptor.ts

**Comment by pelord** [comment]
I forgot to refer to the custom loader 
https://github.com/infra-geo-ouverte/igo2-lib/blob/master/packages/geo/src/lib/layer/shared/layers/image-layer.ts#L42

**Comment by michelespinella** [comment]
Thanks a lot,
    we are trying @danieladifelice with your suggestion, I will post after tests.
Thanks a lot
Michele
