### ISSUE TITLE
Decluttering is broken for specific Text style options

### ISSUE THREAD

**Issue by timoruppell** [openlayers/openlayers#12752]
**Describe the bug**
When using a `Text` style with `placement: "line"`, `overflow: true`, and `textAlign: "center"`, the labels are not decluttered above a certain zoom level.

**To Reproduce**
1. Go to https://codesandbox.io/s/declutter-text-labels-5gd9f?file=/index.js 
2. Zoom map out 
3. Observe decluttering not working

https://user-images.githubusercontent.com/461416/133225186-1ea4562b-1001-4d56-b218-c923edff3d21.mov

4. Comment out any of the `placement`, `overflow`, or `textAlign` options and see the expected behaviour.

**Expected behavior**
The Text labels to be properly decluttered.

**Comment by ahocevar** [comment]
Thanks for the detailed reproduction case! At a quick glance, I have no idea what might be causing this. But the reproduction case should help narrowing the problem down.
