### ISSUE TITLE
Typedef wrong for ImageInformationResponse in module ol/format/IIIFInfo

### ISSUE THREAD

**Issue by webwitcher** [openlayers/openlayers#12763]
**Describe the bug**
Response object for IIIF API version 2 and 3 not assignable to type `ImageInformationResponse`. `tiles` property of response object does not match any type, because it is an array of `TileInfo`. The bug has been introduced by commit: https://github.com/openlayers/openlayers/commit/bb0b94fedf0c29b30e9a3bea71f47cf557584bc7#diff-e804e2aec4eb823cdae866ee86eafb3af1ae2f190c412f698dbacebd0e344ec2

**To Reproduce**
n/a

**Expected behavior**
Typedef `ImageInformationResponse` should conform to `{Object<string,string|number|Array<number|string|IiifProfile>|Object<string, number>|Array<TileInfo>>}` in https://github.com/openlayers/openlayers/blob/15cc849febe9226e32b16ee8b08a74c6a85c7303/src/ol/format/IIIFInfo.js#L43

**Comment by marcjansen** [comment]
Can you come up with a PR, @webwitcher ? Would @simonseyock be available for a review?

**Comment by tschaub** [comment]
Fixed by #12764
