### ISSUE TITLE
What does route.json stand for

### ISSUE THREAD

**Issue by muchmeat** [openlayers/openlayers#12775]
**Is your feature request related to a problem? Please describe.**

I want to develop an historical Track Playback ，and find https://openlayers.org/en/latest/examples/feature-move-animation.html.  The code shows route.json,and the geometry key of it is string,I don't know what it mean.
and I want to use JSON to create a route just like :
```
const polylineJson = [
            [
                117.82424926757811,
                30.950524673197826
            ],
            [
                117.90115356445311,
                30.935212690426727
            ],
            [
                117.92724609375,
                30.91636380602182
            ],
            [
                117.95333862304688,
                30.91518562740828
            ],
            [
                117.99041748046875,
                30.95523555893134
            ],
            [
                118.06045532226564,
                30.97878650255722
            ],
            [
                118.07830810546875,
                31.01057105944174
            ],
            [
                118.11676025390625,
                31.016455925940644
            ],
            [
                118.18130493164061,
                31.041168396491422
            ],
            [
                118.24447631835936,
                31.068227077060858
            ],
            [
                118.311767578125,
                31.1046852937585
            ],
            [
                118.35159301757811,
                31.19283276425548
            ],
            [
                118.39828491210936,
                31.22219703210317
            ],
            [
                118.42575073242188,
                31.292634058899516
            ],
            [
                118.45870971679688,
                31.327832853583537
            ],
            [
                118.48892211914062,
                31.429834925591393
            ],
            [
                118.5205078125,
                31.47083898476439
            ],
            [
                118.5040283203125,
                31.508312698943445
            ],
            [
                118.50677490234375,
                31.525873333239655
            ],
            [
                118.46694946289064,
                31.532896662756986
            ],
            [
                118.39965820312499,
                31.460296798109564
            ],
            [
                118.3941650390625,
                31.40756806510586
            ],
            [
                118.38317871093749,
                31.39584654193847
            ],
            [
                118.39553833007812,
                31.371226579385738
            ],
            [
                118.42575073242188,
                31.36653633110671
            ]
        ];
        const polyline2 =JSON.stringify(polylineJson);


        const route1 = new ol.format.Polyline({
            factor: 1e6,
        }).readGeometry(polyline2, {
            dataProjection: 'EPSG:4326',
            featureProjection: 'EPSG:4326',
        });
```
but I can't get a track
**Describe the solution you'd like**
1.I want to know the geometry key ,what is it 
2.How can i create a track by JSON

Looking forward to reply

**Comment by MoonE** [comment]
1. Polyline is a special format used for geometry encoding, you can convert your coordinates into this by the following code.
`result` is then a string that you can read from a file like route.json
```js
const geometry = new LineString(polylineJson);
const str = new Polyline().writeGeometry(geometry, {
  dataProjection: 'EPSG:4326',
  featureProjection: 'EPSG:4326',
});
const result = JSON.encode({routes: [{geometry: str}]});
```

2. To simply use your coordinate array you can use the following code to get a Geometry 
```js
const route = new LineString(polylineJson).transform('EPSG:4326', 'EPSG:3857');
```

**Comment by mike-000** [comment]
The example uses a JSON structure similar to the responses from APIs such as https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/json/post and https://docs.mapbox.com/api/navigation/directions/

**Comment by muchmeat** [comment]
Thanks a lot ，Happy Mid-Autumn Festival

**Comment by muchmeat** [comment]
> 1. Polyline is a special format used for geometry encoding, you can convert your coordinates into this by the following code.
>    `result` is then a string that you can read from a file like route.json
> 
> ```js
> const geometry = new LineString(polylineJson);
> const str = new Polyline().writeGeometry(geometry, {
>   dataProjection: 'EPSG:4326',
>   featureProjection: 'EPSG:4326',
> });
> const result = JSON.encode({routes: [{geometry: str}]});
> ```
> 
> 1. To simply use your coordinate array you can use the following code to get a Geometry
> 
> ```js
> const route = new LineString(polylineJson).transform('EPSG:4326', 'EPSG:3857');
> ```

Thanks a lot ，Happy Mid-Autumn Festival

**Comment by muchmeat** [comment]
> The example uses a JSON structure similar to the responses from APIs such as [https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/json/post](https://openrouteservice.org/dev/#/api-docs/v2/directions/%7Bprofile%7D/json/post) and https://docs.mapbox.com/api/navigation/directions/

You are so kind ，Happy Mid-Autumn Festival
