### ISSUE TITLE
About loading vector tiles

### ISSUE THREAD

**Issue by Rain-yal** [openlayers/openlayers#12776]
I want to know if openlayers loads the vector tile map published by geoserver, it will get stuck. Is there any way to optimize it?

**Comment by ahocevar** [comment]
We have an example that loads vector tiles from GeoServer: https://openlayers.org/en/latest/examples/vector-tile-selection.html. If your code is similar and you can rule out the server as bottleneck, please provide more information, preferably your code, to increase the chance that someone here will be able to help.
