### ISSUE TITLE
Has no exported member 'default' - Issue

### ISSUE THREAD

**Issue by Dushan** [openlayers/openlayers#12788]
I'm getting the bellow mentioned runtime exceptions that cause my app to fail. What can I do to resolve this? Please help. I'm using "ol": "^6.3.1".

ERROR in node_modules/ol/ImageBase.d.ts:32:48 - error TS2694: Namespace '"/Users/cmbklap0127/projects/angularhive/node_modules/ol/ImageState"' has no exported member 'default'.

32     protected state: import("./ImageState.js").default;
                                                  ~~~~~~~
node_modules/ol/Tile.d.ts:131:47 - error TS2694: Namespace '"/Users/cmbklap0127/projects/angularhive/node_modules/ol/TileState"' has no exported member 'default'.

131     protected state: import("./TileState.js").default;
                                                  ~~~~~~~
node_modules/ol/geom/SimpleGeometry.d.ts:27:53 - error TS2694: Namespace '"/Users/cmbklap0127/projects/angularhive/node_modules/ol/geom/GeometryLayout"' has no exported member 'default'.

27     protected layout: import("./GeometryLayout.js").default;
                                                       ~~~~~~~
node_modules/ol/proj/Units.d.ts:12:31 - error TS2315: Type 'Object' is not generic.

12 export const METERS_PER_UNIT: Object<Units, number>;
                                 ~~~~~~~~~~~~~~~~~~~~~

**Comment by simonseyock** [comment]
Hello @Dushan, this can be solved by setting `skipLibCheck` to `true` in your tsconfig.json. Please refer to https://github.com/openlayers/openlayers/issues/12497 for more information.

**Comment by Dushan** [comment]
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    // "forceConsistentCasingInFileNames": false,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths" : {
      "@app/*": ["src/app/*"],
      "@env/*": ["src/environments/*"],
      "@dashboard/*": ["src/app/modules/dashboard/*"],
      "@landing/*": ["src/app/modules/landing/*"],
      "@shared/*": ["src/app/shared/*"],
      "@widgets/*": ["src/app/shared/components/dashboard/widgets/*"],
      "@data-table/*": ["src/app/shared/components/data-table/*"]

    },
    "types": ["jest"]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

```

I have included that in my tsconfig.js. but its still giving me errors.

❯ npm run config-prod         

> angular-hive@0.0.0 config-prod /Users/cmbklap0127/projects/angularhive
> node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build --configuration=qa


ERROR in src/app/shared/components/dashboard/common-widgets/mapbox-widget/mapbox-widget.component.ts:36:27 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

36   private markerFeatures: Feature[] = [];
                             ~~~~~~~
src/app/shared/components/dashboard/common-widgets/mapbox-widget/mapbox-widget.component.ts:92:21 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

92   getStyle(feature: Feature) {
                       ~~~~~~~
src/app/shared/components/mapbox/mapbox.component.ts:28:27 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

28   private markerFeatures: Feature[] = [];
                             ~~~~~~~
src/app/shared/components/mapbox/mapbox.component.ts:81:21 - error TS2314: Generic type 'Feature<Geometry>' requires 1 type argument(s).

81   getStyle(feature: Feature) {
                       ~~~~~~~

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-hive@0.0.0 config-prod: `node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build --configuration=qa`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-hive@0.0.0 config-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cmbklap0127/.npm/_logs/2021-09-21T16_39_58_298Z-debug.log

**Comment by MoonE** [comment]
Could be that you need to provide the geometry type as the generic argument.
Like `Feature<LIneString>` instead of just `Feature`.
https://github.com/openlayers/openlayers/issues/12497#issuecomment-885761481

**Comment by Dushan** [comment]
@MoonE  Thank you very much. you were right.
