### ISSUE TITLE
ReDoS OL 6.7.0

### ISSUE THREAD

**Issue by pelord** [openlayers/openlayers#12796]
**Describe the bug**
Our app is now based on ol@6.7.0 and I get an vulnerability from Snyk mentionning a Medium severity alert

![image](https://user-images.githubusercontent.com/7397743/134410642-3d4169ee-f929-42b6-b9b4-392f4e1d3e7d.png)

Does some body has the same alert/warning?

**Comment by ahocevar** [comment]
Thanks for reporting this! `content-type-parser` is a dependency of `geotiff.js`, so it would be great if you could report this issue at https://github.com/geotiffjs/geotiff.js/.

Also note that `geotiff.js` is only used when your application uses the new `GeoTIFF` source.

**Comment by pelord** [comment]
Thanks! I've already modified my app to only import the proper source instead of importing all the source type.  I will submit it to geotiff tks.

**Comment by pelord** [comment]
refer and follow this issue instead : 
https://github.com/geotiffjs/geotiff.js/issues/240

**Comment by constantinius** [comment]
The issue is fixed with v1.0.6

**Comment by constantinius** [comment]
@ahocevar I think you need to update the dependency in OL as well.

**Comment by ahocevar** [comment]
Thanks, @constantinius. Dependency updated.

**Comment by ahocevar** [comment]
@constantinius Update: After the last update, we are facing build errors in our examples, and a test fails, indicating that loading of geotiff images does not work as it used to. I haven't yet found out the details yet, but #12797 cannot be merged at this point.
