### ISSUE TITLE
Tile events and response headers

### ISSUE THREAD

**Issue by mdillon-airbus** [openlayers/openlayers#12809]
We have some cases where metadata about an image tile is returned in the HTTP response headers. 

Is there a convenient way to intercept the response headers for every tile load event?  A review of properties emitted from the tileloadend event doesn't seem to have this information.

**Comment by mike-000** [comment]
You would need to load the image by xhr or fetch to access the headers https://openlayers.org/en/latest/apidoc/module-ol_Tile.html#~LoadFunction

**Comment by mdillon-airbus** [comment]
I figured as much.  Thanks!  It appears the browser cache is used so the performance isn't horrible.
