### ISSUE TITLE
VectorImage layer does not remove features

### ISSUE THREAD

**Issue by lysek** [openlayers/openlayers#12816]
**Describe the bug**
A vector feature (Circle or Polygon) is still rendered in map when using VectorImage layer after the feature was removed.

**To Reproduce**
1. Go to https://jsfiddle.net/z87pejso/
2. Click on "Click to remove circle" button
3. See that the circle is still rendered in the map + pan or zoom the map and the feature changes its position.

**Expected behavior**
The feature should be gone.

**Comment by bojanbizjak** [comment]
Exactly the same issue on Chromium 93.0.4577.63 - macOS

**Comment by MoonE** [comment]
If no features are in the current view extent the last rendered image was reused.
#12831 should fix this.
