### ISSUE TITLE
Add the option to disable clustering in a Cluster source

### ISSUE THREAD

**Issue by Lms24** [openlayers/openlayers#12828]
Hello,

OL Version: 6.6.1
Used with: Angular 8 project

**Is your feature request related to a problem? Please describe.**

I am trying to find a clean way to enable/disable clustering in a cluster source during runtime. The current scenario is that I have a `VectorLayer` which has a `Cluster` source which in turn has a `VectorSource<Geometry>` comprising the actual features which sould be clustered. I would like to disable the visual representation of the clusters if I need to (so that all features are shown on the map without clusters) and re-enable it later on again. The hierarchy of layers and sources should stay the same, just as well as the access to the sources and the features.

**Describe the solution you'd like**
What I would like to have is either some sort of method like `clusterSource.disableClustering()` or the possibility to do that via e.g. the distance function.
Currently, when I set the distance function to return `0`, it *almost* resembles a disabled cluster source. However, features that are very close together or even have the same coordinates, are still visually represented as a cluster. 
I'd be totally fine with being able to set the distance function to e.g. `-1` to truly disable clustering.

I read on Stackoverflow, that in this situation one could simply take the cluster source out of the hierarchy. So instead of e.g.
` VectorLayer -> Cluster -> VectorSource`, i'd re-link my vector Source directly to the layer s.t. I have the hierarchy `VectorLayer -> VectorSource`. This might work but I am not entirely convinced that this is a clean solution. For instance, I'd need to additionally handle all accesses to the source:

`layer.getSource().getSource()` when clustering would be enabled that way and `layer.getSource()` when it is disabled respectively. I do not consider this an easy to use and clean approach of en/disabling clustering.

In case I have missed the proper way of how to implement the desired behaviour, I'm sorry. I'd be glad if you could point me to the solution. Otherwise, I'd be grateful for any input. 
Thanks and have a nice day.

EDIT: clarified desired behaviour

**Comment by ahocevar** [comment]
You can do what you desire, by accessing the features or the respective cluster in the style function. This is shown in the https://openlayers.org/en/latest/examples/earthquake-clusters.html example. That example only shows the original features on mouseover. In your case, you would do so when you decide to turn clustering off.

**Comment by Lms24** [comment]
I am not entirely sure if that is what I want. The way I understand this example, an interaction event (pointer move/hover) triggers the Select which in turn selects features whose style should change while they are selected. If they are selected, the cluster feature is basically set to invisible, right? 

So two questions here:
* How would I disable clustering for **all** clusters when I want to disable it via code (e.g. a boolean variable `clusteringEnabled`)?
* * In my app, the decision whether to enable/disable clustering is not controlled via interactions but rather by the condition under which the map is shown.
* Is this actually a clean way of "disabeling" clustering without changing the source structure? For me this looks like a workaround to explode one cluster but not to disable clustering entirely.

I might be wrong here, though, so sorry if I did not understand the example correctly.
