### ISSUE TITLE
GeoTiff nodata has not effect

### ISSUE THREAD

**Issue by valluzzi** [openlayers/openlayers#12832]
**Describe the bug**
GeoTiff nodata has not effect.
When reading a GeoTiff with nodata  the relative pixels are not transparent.

**To Reproduce**
```
const source = new GeoTIFF({
        sources: [
            {
                url: "dem.tif", //digital elevation model
                nodata: -9999,  // this is the nodata value also declared in band header.
            },
        ],})
```

**Expected behavior**
I will expect to see transparent pixel where pixel is marked as nodata.

Inspecting source I suspect that in GeoTiff files where the nodata is defined in band header the "sourceValue" is read as **NaN** and not as "**nodata value** (-9999 in my case). So I suggest to modify line 649 of ol/source/GeoTiff.js with something like that

```
if (sourceValue !== nodata && !isNaN(sourceValue ) ) {
    transparent = false;
    data[dataIndex] = value;
}
```

This can be a solution ... but If I had a style to GeoTiff the problem arise again. 
I think that pixels marked as nodata will be interpreted as zero by the style ( because in GeoTiff.js they are left untouched after array initialization except the alpha band) 

```
new TileLayer({
        source: source,
        style: {
          color: [
            'interpolate',
            ['linear'],
            ['band', 1],
            0,[255,0,0],
            1,[0,255,0]
          ],
        },
    }),
```

**Comment by ahocevar** [comment]
The effect of satting a `nodata` value should be that an alpha band is added to the data tiles, which you have to add to the output color to achieve the desired effect. This can e.g. be seen in the https://openlayers.org/en/latest/examples/cog-math-multisource.html example.

**Comment by valluzzi** [comment]
ok in this case It works.
Just a bit complicated but It works.
