### ISSUE TITLE
forEachLayerAtPixel gives error for WebGLTile Layer

### ISSUE THREAD

**Issue by m-mohr** [openlayers/openlayers#12833]
**Describe the bug**

I receive the following error when implementing a singleclick event for a map with a WebGLTile layer + GeoTiff source:

```
util.js:9 Uncaught Error: Unimplemented abstract method.
    at util.js:9
    at abstract (util.js:10)
    at WebGLTileLayerRenderer.push../node_modules/ol/renderer/Layer.js.LayerRenderer.getDataAtPixel (Layer.js:133)
    at CompositeMapRenderer.push../node_modules/ol/renderer/Composite.js.CompositeMapRenderer.forEachLayerAtPixel (Composite.js:167)
    at Map.push../node_modules/ol/PluggableMap.js.PluggableMap.forEachLayerAtPixel (PluggableMap.js:560)
    at Map.<anonymous> (MapViewer.vue:179)
    at Map.push../node_modules/ol/events/Target.js.Target.dispatchEvent (Target.js:116)
    at Map.push../node_modules/ol/PluggableMap.js.PluggableMap.handleMapBrowserEvent (PluggableMap.js:897)
    at MapBrowserEventHandler.push../node_modules/ol/events/Target.js.Target.dispatchEvent (Target.js:116)
    at MapBrowserEventHandler.<anonymous> (MapBrowserEventHandler.js:129)
```

**To Reproduce**

Can't provide a codesandbox right now due to the txml issue, but use the COG basic example and add something like:

```
			map.on('singleclick', evt => {
				const pixel = this.map.getEventPixel(evt.originalEvent);
				map.forEachLayerAtPixel(pixel, layer => {
					console.log(pixel);
					console.log(layer);
				});
			});
```

OpenLayers version 6.8.1.

**Expected behavior**
Be able to get pixel values.

**Comment by mike-000** [comment]
This currently affects all WebGL layers including Heatmap.  To return an RGBA array in the callback similar to 2d canvas layers would need the WebGL canvas to be created with the `preserveDrawingBuffer: true` option (which is also required to use WebGL layers in map exports, see #11014).  That is inefficient and should be an option.  As the docs say "will be null for layer types that do not currently support this argument" I think unsupported layers should be ignored, and not throw an error.

**Comment by m-mohr** [comment]
Thanks for the details. I agree that this should not throw an error.

But that means that there's no way to get the pixel value (e.g. on a click) for a GeoTiff source right now?

**Comment by mike-000** [comment]
You can access the WebGL context by non-API methods https://codesandbox.io/s/cog-forked-dqreb?file=/main.js

**Comment by valluzzi** [comment]
Is there any way to get the real data value of the pixel?  (not the styled one).   
in https://codesandbox.io/s/cog-forked-dqreb?file=/main.js example the source is a RGBA source and in this case it returns the rgba value that is also the real  value.
But in case of a style that classify the data, this example will return the color of styled pixel, not the original pixel data value.
Can anyone suggest some solution or approach?

**Comment by mike-000** [comment]
> Can anyone suggest some solution or approach?

I think you would need to include a separate hidden unstyled layer to get the original values, and perhaps also an option similar to `imageSmoothing: false` used for 2d canvases so the rendering uses `gl.NEAREST` instead `gl.LINEAR`, see #13100.

**Comment by m-mohr** [comment]
getData is available now, so I think this can be closed.
