### ISSUE TITLE
GeoTiff style avoiding normalization.

### ISSUE THREAD

**Issue by valluzzi** [openlayers/openlayers#12834]
**Is your feature request related to a problem? Please describe.**
The style of the GeoTiff need values normalized betwen [0,1] (Is It true?).
for example: https://openlayers.org/en/latest/examples/cog-math.html

GeoTiff files usually have values of any kind and in this way the developer has to translate the legend in a (normalized) style that sometime can also be unaccurate.  

**Describe the solution you'd like**
It will be possible to avoid the normalization?

so in order to define the style like a silly legend:

```
const source = new GeoTIFF({
                sources: [
                    {
                        url: "dem.tif",  //digital elevation model 
                        nodata: -9999,
                        min: 0,
                        max: 8848.86    //Everest
                    },
                ],
})
```

```
const dem = new TileLayer({
                    source: source,
                    style: {
                      color: [
                        'interpolate',
                        ['linear'],
                        ['band', 1],
                        0,[0,0,0,0],
                        10,[0,0,64],
                        100,[0,0,128],
                        1000,[0,0,255],
                        /*....*/
                        8848.86,[255,255,255],
                       ],
                    },
                }),
```

**Comment by tschaub** [comment]
The GeoTIFF source does currently normalize values.  I agree it would be nice to make this optional and can imagine making this work.  But it isn't currently supported.

**Comment by tschaub** [comment]
@valluzzi - If you try out the latest (`npm install ol@dev`), you can use the `normalize` option on the GeoTIFF source.

```js
const source = new GeoTIFF({
  normalize: false,
  sources: [
    {url: "dem.tif", nodata: -9999},
  ],
});

const dem = new TileLayer({
  source: source,
  style: {
    color: [
      'interpolate',
      ['linear'],
      ['band', 1],
      0, [0, 0, 0],
      10, [0, 0, 64],
      100, [0, 0, 128],
      1000, [0, 0, 255],
      /*....*/
      8848.86, [255, 255, 255],
     ],
  },
});
```

The `min` and `max` configuration has no effect if `normalize: false` is passed to the source constructor.

**Comment by valluzzi** [comment]
Great!
