### ISSUE TITLE
Translate modifying radius of circular polygon geometry

### ISSUE THREAD

**Issue by jt-helsinki** [openlayers/openlayers#12844]
**Describe the bug**
When moving a circular geometry north/south using a translate interaction, the radius changes. Instead, the radius should remain constant and the shape should grow/shrink. 

**To Reproduce**

EPSG:3857 (Web mercator) projection

Create a circular polygon. 

Add a translate interaction to the map. 

Move the polygon. It remains the same size. Radius changes.

**Expected behavior**

Readius remains constant. Shape shrinks when moving towards the equator and grows when moving towards the poles.

**Comment by mike-000** [comment]
Once created the geometry is just a simple polygon.  To maintain a circular polygon during translation it will need to be recalculated as in https://openlayers.org/en/latest/examples/draw-and-modify-geodesic.html
