### ISSUE TITLE
Reading very large TopoJSON files results in RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by karimbahgat** [openlayers/openlayers#12842]
**Describe the bug**
When loading very large TopoJSON files, the TopoJSON format fails on `readFeatures(data)` with the following error:

```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at YS (TopoJSON.js:182)
    at MultiPolygon (TopoJSON.js:276)
    at qS (TopoJSON.js:325)
    at WS (TopoJSON.js:300)
    at e.readFeaturesFromObject (TopoJSON.js:121)
    at e.readFeatures (JSONFeature.js:61)
    at loadFromTopoJSON (internalData.js:193)
    at internalData.js:278
```

After some debugging, it was clear this was happening specifically for very large files topojson files and specifically when processing very long arc coordinate sequences (arcs containing somewhere between 100,000 to 200,000 coordinates). The error happens in the `concatenateArcs` function at https://github.com/openlayers/openlayers/blob/78a4efab8cf53515ff44724551b3f0843e204dec/src/ol/format/TopoJSON.js#L203

Further research reveals that this happens when concatenating two arrays using `push.apply` in cases where the other array contains too many elements: https://stackoverflow.com/questions/61740599/rangeerror-maximum-call-stack-size-exceeded-with-array-push. 

The error can be fixed simply by using a for-loop to push each coordinate individually instead of using `push.apply`. I don't see any unintended consequences of this, and according to [this benchmark](https://www.measurethat.net/Benchmarks/Show/7699/0/array-concat-vs-spread-vs-push-spread-loop-apply) the for-loop is going to be just as fast as `push.apply`. The TopoJSON format reader appears to be alone in using `push.apply`, the GeoJSON format reader uses normal for-loops when extract/adding coordinates. 

Submitting a PR for this shortly. 

I know that most TopoJSON's will likely not contain arcs that long, but for noncontiguous geometry collections with only a few or no shared boundary segments, entire polygon rings often get stored in a single arc (rather than getting chopped into multiple shared arc segments). Large and complex geometries are therefore more likely to result in the maximum call stack error. 

**To Reproduce**
The equivalent of the following code is what produced the error:

```
var data = JSON.parse('read some very large topojson string')
var format = new ol.format.TopoJSON({});
var features = format.readFeatures(topoj, {
                                                dataProjection: 'EPSG:4326',
                                                featureProjection: 'EPSG:3857'
                                            }
                                        );
```

**Expected behavior**
The call to `readFeatures()` should successfully read the topojson object.

**Comment by mike-000** [comment]
Here is a simple reproduceable example https://codesandbox.io/s/simple-forked-olxo3?file=/main.js  The limit in Chrome and Edge on Windows 10 is between 122K and 123K vertices.
