### ISSUE TITLE
geometryFunction for Translate interaction

### ISSUE THREAD

**Issue by jt-helsinki** [openlayers/openlayers#12858]
**Is your feature request related to a problem? Please describe.**

When translating shapes, the coordinates/geometry does not update when moving north/south. There are no recalculations to match the projection.

For example, a circular polygon is drawn at the equator. A `Translate` interaction is used to move the shape towards the north or south pole. The radius increases instead of remaining the same. 

For many cases, this is probably OK but in the case where there is a maximum radius, the radius can go outside this limit. 

**Describe the solution you'd like**

The `Draw` and Modify` interactions have the `geometryFunction` and `style` function properties respectively. It would be very handy if the `Translate` interaction had a similar function property.

**Comment by mike-000** [comment]
The geometry can be updated in the `translating` and `translateend` events https://codesandbox.io/s/simple-forked-c55tc?file=/main.js
