### ISSUE TITLE
OL native Geodesic circle type

### ISSUE THREAD

**Issue by jt-helsinki** [openlayers/openlayers#12859]
**Is your feature request related to a problem? Please describe.**

Creating and using geodesic circles is too difficult in open layers. It's probably not such an uncommon use case and it would be very handy to have this easily used with the OL Interactions without having to write custom geometry/style functions. 

**Describe the solution you'd like**

Create an OL native GeodesicCircle type which can be used like this:

```
const circle = new GeodesicCircle(radius, coordinate, number_of_sides)
...
circle.radius()
circle.center()
...
```

**Comment by TDesjardins** [comment]
Looks for me like the existing `Polygon.circular`-function: https://github.com/openlayers/openlayers/blob/v6.8.1/src/ol/geom/Polygon.js#L426

**Comment by jt-helsinki** [comment]
Kind of but not really. Unless I am mistaken, this function just builds a polygon with n sides. It's just a representation of a circle so if you try to resize, only the point which you grab is moved. The rest of the "circle" stays put. Moreover, as this is just a polygon, there is no radius or centre coordinate attached to this circular polygon. 

Check out this example:

https://openlayers.org/en/latest/examples/draw-and-modify-geodesic.html

There's quite a bit involved with getting the radius, rescaling and dragging. Ideally, this functionality would be wrapped up inside the GeodesicCircle class.
