### ISSUE TITLE
Webgl style : the src parameter not working with a conditional operator

### ISSUE THREAD

**Issue by barbararomeo** [openlayers/openlayers#12867]
I have to display a lot of point features (up to 500-600k), so I am using Webgl.
When I use the `case` operator for color or size properties, I have no problem.
But when I use it for the symbol style source (base64) the operator is not working and it returns a black square instead of the image.
```
let srcTypeA = 'data:image/png;base64,iVBORw0 ...',
    srcTypeB = 'data:image/png;base64,iVBORw0 ...',
    srcTypeDefault = 'data:image/png;base64,iVBORw0 ...';

style = {
    symbol: {
        symbolType: 'image',
        src: [
            'case',
            ['==', ['get', 'type'], 'A'],
            srcTypeA ,
            ['==', ['get', 'type'], 'B'],
            srcTypeB,
            srcTypeDefault
        ],
        color: [
            'case',
            ['<', ['get', 'speed'], 5], '#ff14c3',
            ['between', ['get', 'speed'], 5, 10], '#ffed02',
            '#00ff67'
        ],
        size: 14
    }
};
```
![image](https://user-images.githubusercontent.com/32452479/136392333-17306231-b083-497a-9bd8-c8c18510c82d.png)

I have also tried to set the src as a feature property and get it with the `get` operator, but no more success.. 
```
style = {
   ...,
   src: ['get', 'imageSrc'],
   ...
}
```

How could I do it?

**Comment by M393** [comment]
You can only use a single source, not an expression. Here is the code reading your src.
https://github.com/openlayers/openlayers/blob/c0009d5985daf821f38c6014c6945923bc3083c9/src/ol/webgl/ShaderBuilder.js#L547-L549
You can however use subregions from one image as in this example:
https://openlayers.org/en/latest/examples/icon-sprite-webgl.html
