### ISSUE TITLE
Problem with multiple maps on same page using MapboxVector-layer

### ISSUE THREAD

**Issue by dagognatt** [openlayers/openlayers#12862]
**Describe the bug**
When 2 maps on same page use MapboxVector-layer but with different styleUrls, the styles seems randomly applied to each map. Each reload of the page might get different result. 

**To Reproduce**
1. Go to https://jsfiddle.net/Lt7jp2w6/
2. Fill in your mapbox token
3. Pan and zoom a bit. 
4. Observe that the two maps are not correctly displaying the mapbox style

**Expected behavior**
The two maps should display two different styles as set in the styleUrl (streets-v11 and dark-v10).

**Comment by ahocevar** [comment]
This issue has been fixed in ol-mapbox-style.
