### ISSUE TITLE
feature.setId() function breaks linestring modification

### ISSUE THREAD

**Issue by tyeasir** [openlayers/openlayers#12866]
If you set the id of a feature using setId() method it breaks the ability to modify a linestring.

**To Reproduce**
-Create a Linestring Geometry Feature and add some coordinates to it. 
-on the feature object use setId('feature1') to set its id
-on the map add Modify interaction and Snap interaction
-click on the linestring on the map and try to move it around (it wont work), also hold alt and click on the segment ends to delete (that also wont work)
-now comment out the code to setId() and do the step above and it will work as expected

**Expected behavior**
Modifying a linestring should allow you to drag a line string around and create new segments and delete segments using alt

**Comment by MoonE** [comment]
I can't seem to reproduce this. Please provide a runnable example showcasing this issue.
You can use [one of the examples](https://openlayers.org/en/latest/examples/draw-and-modify-features.html) as a starting point by clicking the Edit button.
