### ISSUE TITLE
ScaleLine sizes incorect in EPSG:4326（or other Geographic coordinate system）

### ISSUE THREAD

**Issue by yujinpan** [openlayers/openlayers#12898]
**Describe the bug**
ScaleLine sizes incorect in EPSG:4326（or other Geographic coordinate system）.

**To Reproduce**
- forked https://openlayers.org/en/latest/examples/measure.html
- change views projection to 'EPSG:4326'
- change `getLength` method projeciton to 'EPSG:4326'
- and the result https://codesandbox.io/embed/measure-forked-e28q5?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/20787785/137477057-1b0907a5-2060-40d2-a129-d0d7c69dd9d7.png)

**Expected behavior**

**Comment by mike-000** [comment]
Unless on the equator the scale in EPSG:4326 is different along the x and y axes.  If you measure a vertical line covering the same number of screen pixels the it would be over 200km.  The ScaleLine shows the average of the axes.
