### ISSUE TITLE
Select interaction crashes with empty vector layer when `declutter: true`

### ISSUE THREAD

**Issue by perliedman** [openlayers/openlayers#12913]
**Describe the bug**

If you have a `VectorLayer` with `declutter: true` and its `VectorSource` has no features, attempting to select with a `Select` interaction throws an exception.

**To Reproduce**
1. https://codesandbox.io/s/exciting-tdd-ywt0c
2. Click the map
3. A `TypeError` is shown ("Cannot read properties of null (reading 'all')")

**Expected behavior**
Selecting from an empty layer should work without exceptions even when declutter is set to true.

**Comment by masihsadatyyc** [comment]
@ahocevar is there any ETA for when this will be released? We're also currently facing this issue.

**Comment by MoonE** [comment]
You may want to use [patch-package](https://www.npmjs.com/package/patch-package) in the meantime.

**Comment by ahocevar** [comment]
We publish packages from the main branch automatically, using the `dev` tag. So you can simply `npm install ol@dev` to get a version which includes that change.

**Comment by ahocevar** [comment]
Fixed with #12935.

**Comment by masihsadatyyc** [comment]
Just wanted to confirm that this is fixed. Thank you!

**Comment by DrEppen** [comment]
I see that this issue is still open and I would like to know the status.

I'm still having this issue in VectorTileLayer.js, where frameState.declutterTree is null:

        const declutteredFeatures =
          executorGroups === declutterExecutorGroups
            ? frameState.declutterTree.all().map((item) => item.value)
            : null;

**Comment by ahocevar** [comment]
@DrEppen This is a separate issue, which was fixed with #15028. Please install `ol@dev` to a version which contains the fix.
