### ISSUE TITLE
Angular prerender not working with GeoTIFF

### ISSUE THREAD

**Issue by undefinedSolutions** [openlayers/openlayers#12943]
**Describe the bug**
Within Angular 12.2.0 (ng serve) embedding geotiffs works very well. 
However, as soon as pages are to be rendered using prerender, the following error occurs:
`Cannot find module 'fs`

**To Reproduce**
I built an example repo based on an [example from OL](https://openlayers.org/en/latest/examples/cog-overviews.html).

1. `git clone https://github.com/undefinedSolutions/cog-prerender-error`
2. `cd cog-prerender-error`
3. `npm install`
4. `npm run prerender:dev` -> The error is displayed

**Expected behavior**
Prerender should simply run through...

**Comment by ahocevar** [comment]
I cloned your repository and followed the instructions. I do get an error, but none that seems related to yours:
```
⠋ Generating server application bundles (phase: setup)...
⠋ Generating browser application bundles (phase: setup)...
ENOENT: no such file or directory, stat '/Users/ahocevar/projects/cog-prerender-error/dist/fe/server'
```

**Comment by undefinedSolutions** [comment]
That is strange, I also cloned the repo again and it ran through to the fs error.
Here is my `ng --version`:
```
Angular CLI: 12.2.0
Node: 14.15.5
Package Manager: npm 7.23.0
OS: linux x64

Angular: 12.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, language-service, material
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.2.0
@nguniversal/builders           12.1.0
@nguniversal/common             12.1.0
@nguniversal/express-engine     12.1.0
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by ahocevar** [comment]
Ok, with node 14 and npm 7 I was able to reproduce the error:
```
✖ Prerendering routes to /Users/ahocevar/projects/cog-prerender-error/dist/fe/browser failed.
Cannot find module 'fs'
```
To me it seems like this is an issue with either `angular-cli`, or your `angular.json`. `geotiff`'s package.json correctly configures `"browser": { "fs": false }`, but apparently it is not respected.

**Comment by undefinedSolutions** [comment]
@ahocevar Thanks for this hint. I was able to solve this problem:
https://github.com/undefinedSolutions/cog-prerender-error/tree/working

The solution is to create `cog.module.ts` and `cog-routing.module.ts`. Within the routing, reference is now made to the `cog.module.ts` using `loadChildren: () => import('./cog/cog.module').then(m => m.CogModule)`. So the prerender is running without an error...
