### ISSUE TITLE
Update country names and borders in example

### ISSUE THREAD

**Issue by dzach** [openlayers/openlayers#12940]
**The problem**
Standard policy of opensource projects regarding international borders has always been to follow what the UN recognizes as such.

In the OpenLayers example [Image Vector Layer](https://openlayers.org/en/latest/examples/image-vector-layer.html), Cyprus, the island, appears divided to two countries, Cyprus and Northern Cyprus, which is incorrect. There is no country named North Cyprus which is internationally recognized as such, or by the UN.

Following the policy mentrioned above, in the same OpenLayers example, Crimea correctly appears to be part of Ukraine, as is internationally recognized.

On the same line, there is no country internationally recognized as 'Macedonia'. The correct name is 'North Macedonia'.

The issue exists in file [countries.geojson](https://openlayers.org/en/latest/examples/data/geojson/countries.geojson)

Attached is a corrected version of the file, without the false international border line, and country name.

[countries.zip](https://github.com/openlayers/openlayers/files/7447209/countries.zip)
.
Thank you.

**Comment by dzach** [comment]
I can submit the changes with a pull request, if necessary.

**Comment by tschaub** [comment]
@dzach - Thanks for the report.  I haven't yet looked at your `countries.zip`, but it would be good to have an updated `countries.geojson` used throughout the examples.  It should be simplified in a similar way or otherwise represent the same level of generalization as the current dataset.

If you are able to create a pull request, please include details about the source for the updated dataset.  It would be good to have details in the git log about the provenance.

**Comment by mike-000** [comment]
Swaziland should be renamed to Eswatini.  It would also be useful to include the ISO A2 code in the country properties to avoid needing a third party geojson for the Style renderer example.

**Comment by dzach** [comment]
@mike-000 - I verified that Eswatini is the correct name with wikipedia and will add it to this pull request.

**Comment by dzach** [comment]
@MoonE : Thank you for reviewing this PR and for pointing to the https://github.com/nvkelso/natural-earth-vector/issues/391#issuecomment-678230303 thread. Regretfully but necessarily, this is a long reply:

**In principle:**

Natural Earth Vector appears to have developed a concept of 'worldviews'. From what little I've read in that thread, that seems to me to be a legitimate quest to record and display on maps facts that exist 'on the ground'. Even recording 'facts on the ground' can, however, become very controversial, since even the act of recognizing a 'situation on the ground', or failing to do so, is inherently political. It is naive to believe or claim that a few individuals can record and do justice on issues whole nations cannot agree and decide upon. In the case of widely adopted open source projects, this also puts significant political power in the hands of few maintainers, hence it bears the risk of becoming strongly un-democratic. A 'benevolent dictator' can quickly become just a dictator.

OL is a platform that facilitates presentation of 'worldviews' on maps. The only way for a technical project like OL to avoid getting caught in controversial political issues seems to be its adherence to principles. What data it adopts matters a lot; deciding on that helps avoid becoming unwillingly propagators of somebody else's political views. This means there are costs to be paid: a cost to decide what is suitable, and another to maintain an own dataset, where necessary.

The simple principle I propose is this: if you _have to_ use data prone to political bias, use what an international authority for such matters accepts. The international authority for statehood acceptance is the UN, and it has universally accepted rules for doing business.

**Regarding costs:**

OL is not linking directly to Natural Earth Vector's dataset; instead, it maintains its own dataset, based on external data it adopts, in this case from Natural Earth Vector; the very existence of #12942 points this out. So the cost of maintaining the dataset is already borne by OL, although is not as high as _creating_ an own dataset. That's a benefit from being an open source project.

The cost of deciding _what_ data to use is unavoidable, if a project intends to adhere to principles. Deferring this decision to other projects may end up violating its own principles and loosing its independence. Reviewer decisions may also violate a project's principles, albeit unintentionally and in good faith, while trying to avoid doing so.

**To the point of my PR:**

Having Northern Cyprus as a country in the dataset _is a strong political view_. There are numerous UN decisions declaring the Turkish act as an invasion of northern Cyprus, and asking it to withdraw. There is no nation in the world recognizing a 'Turkish Republic of Northern Cyprus', other than the invader itself. Therefore a decision for a 'Northern Cyprus' state to remain in OL's dataset asks for a reason, and the principle it adheres to.

Deferring the decision to what Natural Earth Vector does, does not make the decision less political; instead, it makes it even more political, as it adopts a specific 'worldview' from the plethora of such 'world views' Natural Earth offers, or intents to.

It is not my intention to take part in discussions about existing or past 'worldviews', not in general nor specifically in Natural Earth Vector's case. I am using OL as a technical platform to display non political maps. What I propose is a conservative, achieved by international consensus, widely adopted, neutral solution: **use whatever data agrees with the commonly recognized and accepted authority**. 

_Based on the above principle_ I requested the removal of the non UN recognized and therefore non legally existing state of 'Northern Cyprus' from the OL maintained, [countries.geojson](https://github.com/openlayers/openlayers/blob/main/examples/data/geojson/countries.geojson) file. If another decision is made, it would be good faith and democratic to state on what principles such a decision was made.

Even better, maybe it would be prudent to include a short 'principles for data use' document with OL, stating a few but necessary rules for adopting or creating data to be used within the OpenLayers project. Maybe parts of this long post can serve as a basis for something like that ?

**Comment by dzach** [comment]
After reading more about Natural Earth, it seems to me that the scopes of the two projects, Natural Earth Vector and OpenLayers are quite different, although they do have a most significant common interface: OpenLayers is a technical platform facilitating presentation of maps and metadata in a web browser, thus it is agnostic about the content that is actually displayed, while Natural Earth provides map data and metadata that is actually displayed, thus it is the content itself, and therefore cannot be agnostic.

Natural Earth cannot avoid political controversies, nor does it intend to: as it is clearly stated in the [Contributors](https://www.naturalearthdata.com/about/contributors/) page, the dataset started "for quick turnaround newspaper mapping". A newspaper's business depends on reporting about controversies and disputes, being pluralistic, progressive or conservative, or being supportive of strong views. A reporter working on Crimea needs to find quickly whether last nights events occured in Russian or Crimean territory. So the reporter needs to know the 'ground truth', where that border is. Natural Earth's interest is to dig out and collect such data, and provide the resulting dataset to its users. That's how newspapers make money. Please, don't shoot the pianist. One cannot ask a reporter not to report something that's happening, just because one may have a different view.

In doing so however, provided their dataset is widely used, the Natural Earth team takes the risk of appearing strongly biased, especially by promoting this 'ground truth' which they inherited from the newspapers business. They do indeed recognize that fact. They do not seem to have a 'principles' document published somewhere, so one cannot hold them accountable for something they do not claim to adhere to. Being free and open source can obscure the fact that the dataset can be biased toward controversy.

Why Natural Earth may be doing this seems clear to me. Why a data agnostic project like OpenLayers should choose a controversial 'worldview' dataset over a widely accepted one is a question that needs to be answered, I believe. There is nothing on earth  guaranteeing that a free and open source dataset, or project for that matter, will be unbiased.

I would say, trying to be humorous in a serious matter, that in mathematical or control systems terms, Natural Earth chose to promote (as admin-0) the derivative of the world's state instead of promoting the world's state itself, or its integral. That much is obvious.

----------
Ref: https://github.com/nvkelso/natural-earth-vector/issues/391

**Comment by ahocevar** [comment]
In my opinion, it would be wise to either use a less disputable dataset for our vector demos, i.e. nothing that has to do with countries, nations and borders. If we cannot find anything suitable, we should at least use a CORS friendly third party source, instead of maintaining our own. Same goes for #12942, #12941, #12940 and past issues regarding this data set.

I'll think about an alternative and come up with a pull request that sets up our vector examples to use a different data set.

**Comment by tschaub** [comment]
@ahocevar 100% agreement.  I did some poking around yesterday looking for suitable / interesting data.  I thought that a global biome (e.g. https://www.arcgis.com/apps/View/index.html?appid=144b1d74a5964d728b25aeb0542de485) dataset might be nice - but I haven't yet found one that is appropriately simplified.

Global watersheds (like something based on the USGS Hydro1k data https://www.wri.org/watersheds-world) might also be nice.

**Comment by MoonE** [comment]
> Why a data content agnostic project like OpenLayers should choose a controversial 'worldview' dataset over a widely accepted one is a question that needs to be answered, I believe. There is nothing on earth guaranteeing that a free and open source dataset, or project for that matter, will be unbiased.

Usage of the Natural Earth dataset is simply a matter of availability, and not an endorsement for one side of a conflict.
When searching for `countries geojson` it is in the first results and finding something else seems to be rather difficult.

A less controversial dataset for the examples will of course solve this issure in a more permanent fassion :+1: .

**Comment by dzach** [comment]
@MoonE : Yes, it's difficult, I've spent time myself trying to find one. It is unfortunate that issues like this pop up at times, but on the positive side, these may also be opportunities to re-adjust toward better solutions.

Choosing another type of dataset, e.g. one with geographical/geological features rather than features related to borders/limits conceived by humans, might be a good neutral solution. Choosing another planet would be ideal for the time being :-), but then maybe very few people would be interested in such a dataset.

I've looked through NASA's datasets this morning for pure geographical polygon data in geojson format, but haven't yet identified any.

**Comment by mike-000** [comment]
The data from https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/countries appears to reflect UN status (which might be contentious in Taiwan) and is CORS friendly https://codesandbox.io/s/vector-layer-forked-nt4z5.

**Comment by dzach** [comment]
Thanks!
