### ISSUE TITLE
How to get bounds for zonemap overlay in OpenLayers 6?

### ISSUE THREAD

**Issue by frederiknygaard** [openlayers/openlayers#12959]
I have an example of using an external zonemap, that needs the bounds as an &extends params which works in OpenLayers 2. But when using OpenLayers 6, the TMS source which emits the bounds do not exist. After searching for answers in forums, my understanding is that XYZ source should replace the TMS source. But the XYZ source only emits the tileCoord (with the x, y, z parameters) which I do not know how to translate the XYZ to the bounds for the external zonemap.

Is there anyway to get the bounds and is XYZ the correct source to use?

Old code:

```
// Open Layers 2
const get_my_url = (bounds) => {
	var pLeftBottom = new Proj4js.Point( bounds.left, bounds.bottom);
	Proj4js.transform( gProj4DKProj, gWGSMercator , pLeftBottom );

	var pRightTop = new Proj4js.Point( bounds.right, bounds.top);
	Proj4js.transform( gProj4DKProj, gWGSMercator , pRightTop );

	return `http://example.com&extends=${bounds.left},${bounds.bottom},${bounds.right},${bounds.top}`
}

new OpenLayers.Layer.TMS('desc', 'url', {
	type: 'png',
	getURL: get_my_url,
})
```

New code:

```
// Open layers 6

const url = (tileCoord, pixelRatio, projection) => {
	const [z, x, y] = tileCoord
	return ????
}

new XYZ({
	tileUrlFunction: url,
})
```

Any help is appreciated

**Comment by TDesjardins** [comment]
Hello @frederiknygaard,

I am sure this link should help you: https://github.com/openlayers/openlayers/issues/3923

**Comment by mike-000** [comment]
For the tile bounds use the `getTileCoordExtent` method of the tile grid, e.g. to implement a TileWMS source as XYZ https://codesandbox.io/s/wms-tiled-forked-i953l?file=/main.js

**Comment by frederiknygaard** [comment]
Thank you @mike-000, the `getTileCoordExtent` was just what I was missing!
