### ISSUE TITLE
Bing maps won't load

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#12951]
**Describe the bug**
The request returns an error:
>The request was forbidden.  Your credentials may be denied or suspended.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/bing-maps.html
2. See error

**Comment by mrpan** [comment]
i can't reproduce an error。
![image](https://user-images.githubusercontent.com/3354097/139783965-0f14c759-7e20-4820-856c-570eef90bbac.png)

**Comment by MoonE** [comment]
I also don't get an error anymore.

**Comment by tschaub** [comment]
We're periodically hitting a daily limit.  The examples aren't currently working.

```
curl "https://dev.virtualearth.net/REST/v1/Imagery/Metadata/RoadOnDemand?uriScheme=https&include=ImageryProviders&key=$KEY&c=en-us&jsonp=olc_3"

olc_3({"authenticationResultCode":"DeniedCredentials","brandLogoUri":"http:\/\/dev.virtualearth.net\/Branding\/logo_powered_by.png","copyright":"Copyright © 2021 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation.","errorDetails":["The request was forbidden.  Your credentials may be denied or suspended."],"resourceSets":[],"statusCode":403,"statusDescription":"Forbidden","traceId":"e146307576e642f18ed61165ac98124a|CO00004BCF|0.0.0.1"})
```

**Comment by tschaub** [comment]
I'm going to overwrite the key used in the hosted examples while awaiting a review on #12964.
