### ISSUE TITLE
Color in style does not work when there is a space after rgba

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#12953]
Note the space after **rgba** in example below:

**DOES NOT WORK:**

```
var fill = new ol.style.Fill({
        color: "rgba (100, 255, 255, 0.5)"
});
```

**WORK 100%:**

```
var fill = new ol.style.Fill({
        color: "rgba(100, 255, 255, 0.5)"
});
```

**Comment by mrpan** [comment]
The format of the rgba value has no spaces

**Comment by tschaub** [comment]
As @mrpan mentions, in CSS, the functional syntax (e.g. `rgb()`, `rgba()`, `hsl()`, etc.) does not accept a space between the function name and the parentheses.

You can check what works here: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#color_value_tester
