### ISSUE TITLE
geometry.getType() doesn't work as expected

### ISSUE THREAD

**Issue by salihkesepara** [openlayers/openlayers#12954]
**Describe the bug**
It says a polygon in the console message, even though I draw a Box on the map. 
I tried to set a different style for polygon and box.

**To Reproduce**
1. Go to 'https://jsfiddle.net/skesepara/vbc4dmjf/7/'.
2. Press F12 button to open Inspect.
3. Click Console segment.
4. Draw box in map.
5. You will see a console message as "geometry:  Polygon"

**Expected behavior**
I expected to see a console message as "geometry: Box"

**Comment by mprins** [comment]
Box does not exist, not in openlayers (https://openlayers.org/en/latest/apidoc/module-ol_geom_GeometryType.html) and not in any GIS standard

**Comment by MoonE** [comment]
You  can add this to set an additional property on the drawn geometry:
```js
draw.on('drawend', function (evt) {
	evt.feature.getGeometry().set('subtype', 'box');
});
```
Reading it in your style function:
`console.log('geometry: ', geometry.getType(), geometry.get('subtype'));`

**Comment by salihkesepara** [comment]
> You can add this to set an additional property on the drawn geometry:
> 
> ```js
> draw.on('drawend', function (evt) {
> 	evt.feature.getGeometry().set('subtype', 'box');
> });
> ```
> 
> Reading it in your style function: `console.log('geometry: ', geometry.getType(), geometry.get('subtype'));`

Worked! thnks
https://jsfiddle.net/skesepara/vbc4dmjf/10/

**Comment by tschaub** [comment]
The suggestions above are good.  I'd also encourage you to think of the feature as a place to set user or application-specific properties (e.g. `feature.set('whatever', 'here')`.  In the future, you may not be able to use geometries as an arbitrary bag of properties.
