### ISSUE TITLE
Offscreen canvas example does not work in codesandbox

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#12952]
**Describe the bug**
When editing the offscreen canvas example in codesandbox it does not work.
> Uncaught SyntaxError: Cannot use import statement outside a module

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/offscreen-canvas.html
2. Click on Edit
3. See error

**Expected behavior**
The example should not throw an error.

**Comment by MoonE** [comment]
Configuring the worker with `{type: 'module'}` seems to work.
I added it to #12893 with https://github.com/openlayers/openlayers/pull/12893/commits/46d9e8db8e916d63fc5e8310f8f12439023e98ad

**Comment by tschaub** [comment]
@MoonE, should we close this now that #12893 is in?

**Comment by MoonE** [comment]
Yes. This should work now, thanks @tschaub.
