### ISSUE TITLE
blurry raster tiles when using mouse wheel or touchpad for zoom

### ISSUE THREAD

**Issue by karussell** [openlayers/openlayers#12963]
**Describe the bug**

The raster tiles look blurry or suboptimal for mostly all zoom levels when using the mouse wheel. (I searched this issue tracker and the mailing list but wasn't able to find a similar issue or an option to disable this interpolation/resampling/antialiasing behaviour). 

**To Reproduce**

1. Go to https://jsfiddle.net/kesb6tgm/ (I used the latest example from the quickstart)
2. Now zoom in with the mouse wheel or touchpad
3. You see the blurry map labels (some zoom levels are worse than others but none seem be 100% sharp)

This happens to me when using firefox 94 under linux (or chromium too).

**Expected behavior**

I would have expected the same sharpness as it was in [earlier versions](https://openlayersbook.github.io/ch11-creating-web-map-apps/example-01.html) or as it is when using the zoom buttons.

**Comment by easbar** [comment]
Same for me, here is a screenshot:

![image](https://user-images.githubusercontent.com/17603532/140503883-c5e7d558-5fe0-47e9-8665-d1c44fc06e95.png)

For comparison the same part of the map on openstreetmap.org (using Leaflet)

![image](https://user-images.githubusercontent.com/17603532/140504209-2d3ab189-b8c2-4ca3-b53c-46dd24f28dcb.png)

**Comment by mike-000** [comment]
Set `imageSmoothing: false` in the tile source options. Alternatively you could set `constrainResolution: true` in the view options to snap to integer zoom levels

**Comment by easbar** [comment]
Nice, thanks! `constrainResolution: true` fixes this issue for me. The behavior is very similar or the same as with Leaflet then.
Would it make sense to somehow prefer the integer zoom levels even when `constrainResolution: false`? I feel like when it is disabled there is no way to set the zoom level to an integer value (and experience a sharp map image), because the step size of the mouse wheel seems too large.

**Comment by karussell** [comment]
Oh, I feared there was an option to avoid this. Thanks!
