### ISSUE TITLE
Layer opacity stacking issues after 6.8.1 version

### ISSUE THREAD

**Issue by murdocha** [openlayers/openlayers#12960]
**Describe the bug**
After updating to OL 6.9.0, the layer opacity for independent layers (tiled ArcGIS REST layers at least) will now make the top-most layer opaque (but only in reference to other OL layers (tiled ArcGIS REST layers in this case). The layer opacity _does_ allow basemaps to display through.

**To Reproduce**
1. Go to:
https://codesandbox.io/s/layer-group-forked-mokjq?file=/package.json

2. This is a screen capture using OL version 6.9.0
![image](https://user-images.githubusercontent.com/7988400/140408422-57c01614-d893-48f7-9664-70271842de15.png)

Compare the image output after changing to OL version 6.7.0.
![image](https://user-images.githubusercontent.com/7988400/140408509-050a203f-ec05-4491-b10a-931f86d4cea0.png)

3. This appears to only be an issue in version 6.8.1 and greater. 6.7.0 and below renders as I expect. I determined that version could be the issue with localhost testing, but the sandbox doesn't seem to be able to target 6.8.1...

This may be related to how the layers are rendered in the canvas element?

In the linked code sandbox, if you change the opacity values for individual layers to _NOT_ be identical then the image is rendered "correctly" with transparency for each Layer.
For example if layers are not all set to opacity of "0.5", but with values of 0.49, 0.50, 0.51 (for three separate layers) then the layers rendered "correctly".

**Comment by ahocevar** [comment]
This might be a regression introduced by #12760.
