### ISSUE TITLE
Change Shape of  Heatmap Element from Circle to Square

### ISSUE THREAD

**Issue by MeixiaZeng** [openlayers/openlayers#12961]
I'm a novice in Openlayer6. Who can tell me how to change the rendered elements of the Heatmap.js from a circle to a square? Thanks a lot!

**Comment by wr404274848** [comment]
Is there any possiable? @jahow

**Comment by MoonE** [comment]
I posted an answer on stackoverflow to this question, see the linked codesandbox example. 
https://stackoverflow.com/questions/69848505/change-shape-of-heatmap-element-from-circle-to-square/69877430#69877430

**Comment by wr404274848** [comment]
> I posted an answer on stackoverflow to this question, see the linked codesandbox example. https://stackoverflow.com/questions/69848505/change-shape-of-heatmap-element-from-circle-to-square/69877430#69877430

why it get bigger when i zoom out the map?
