### ISSUE TITLE
RenderComplete event does not fire

### ISSUE THREAD

**Issue by itsgifnotjiff** [openlayers/openlayers#12986]
**Describe the bug**
The `rendercomplete` event does not fire for the map object in a Vue serverless application.

**To Reproduce**
1. Add layers, move, zoom, update params of sources.
2. Console log the event firing

**Expected behavior**
I expect the map to fire a rendercomplete event once I update the time parameter on the ImageWMS sources and they all render.

**Comment by ahocevar** [comment]
It will be impossible to track down this problem without seeing your code. If you can go to the official examples (https://openlayers.org/en/latest/examples), choose one that is suitable to be extended to show your issue, and click the "Edit" button, you can create an application that exposes the problem.
