### ISSUE TITLE
GeoTiff WebGL: INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request error

### ISSUE THREAD

**Issue by oshawa-connection** [openlayers/openlayers#12984]
**Describe the bug**
When I attempt to add a GeoTiff layer to a map following [ this example](https://openlayers.org/en/latest/examples/cog-overviews.html), I see a black square where the tiff should appear, and I get this error message:
`256 WebGL: INVALID_OPERATION: texImage2D: ArrayBufferView not big enough for request`
`WebGL: too many errors, no more errors will be reported to the console for this context.`

When I download the tiff from [the example](https://openlayers.org/en/latest/examples/cog-overviews.html) and add it to the map in the same way, it all works fine. Therefore, my guess is that its related to the format of my data - but I can't figure out from the error message what the problem with it is.

**To Reproduce**
I have made a [small example](https://github.com/oshawa-connection/openlayersGeotiffMinReproducable) that includes the offending GeoTiff in the `images` folder. 

The bad GeoTiff was generated using QGIS `Create random raster layer` tool with pixel size of 30 and a data type of UInt16, same as the one from the example. The only difference I can spot is `AREA_OR_POINT`, not sure if this would make a difference.

**Comment by mike-000** [comment]
The error message seems to be related to #13013 and no longer occurs when using the latest dev build, but without knowing what the data represents or how to style it the output still appears black.

**Comment by oshawa-connection** [comment]
That's great news, I will close this issue if this future PR fixes it. Thanks for fixing it!
I knew my data was bad - but I was expecting a more meaningful error message.
