### ISSUE TITLE
Help required, test failures

### ISSUE THREAD

**Issue by sumitd2** [openlayers/openlayers#12981]
Hi there,

We are trying to build and test the main branch of openlayers inside a fresh RHEL 8.3 docker container using the following commands:

```
yum install git sed unzip make -y
dnf module install -y nodejs:14
cd /opt
git clone https://github.com/openlayers/openlayers.git
cd openlayers/
git checkout main
npm install
npm run build-package
dnf -y install http://mirror.centos.org/centos/8/BaseOS/ppc64le/os/Packages/centos-linux-repos-8-3.el8.noarch.rpm http://mirror.centos.org/centos/8/BaseOS/ppc64le/os/Packages/centos-gpg-keys-8-3.el8.noarch.rpm
yum install -y firefox libXScrnSaver libdrm mesa-libgbm alsa-lib libxshmfence
sed -i "s#'ChromeHeadless' : 'Chrome'#'ChromeHeadless' : 'ChromeHeadless'#g" /opt/openlayers/test/browser/karma.config.cjs
sed -i "s#'--enable-automation'#'--enable-automation', '--no-sandbox', '--headless'#g" /opt/openlayers/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js
sed -i "s#'--headless'#'--headless', '--no-sandbox'#g" $(grep -Ril './' -e "'--headless'")
sed -i "s#timeout: 2500,#timeout: 10000,#g" /opt/openlayers/test/browser/karma.config.cjs
npm run test-browser
npm run test-node
npm run test-rendering -- --force

```
**"npm run test-rendering -- --force" is failing with the following output:**

_[root@6a44fb8c2c53 openlayers]# npm run test-rendering -- --force

> ol@6.9.1-dev test-rendering /opt/openlayers
> node test/rendering/test.js "--force"

<i> [webpack-dev-middleware] wait until bundle finished: /cases/circle-style/main.js
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
97 assets
910 modules
webpack 5.62.1 compiled successfully in 16029 ms
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
case ./cases/layer-vectortile-icon-label/main.js (Vector tile layer declutters image with text correctly)': mismatch 0.014923095703125
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
case ./cases/rtl-text-align/main.js': mismatch 0.0143585205078125
RENDERING TESTS FAILED
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ol@6.9.1-dev test-rendering: `node test/rendering/test.js "--force"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ol@6.9.1-dev test-rendering script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-10T07_56_23_795Z-debug.log
[root@6a44fb8c2c53 openlayers]#_

Can you please help?

Thank you,
Sumit Dubey

**Comment by tschaub** [comment]
The significant line above is this:
> case ./cases/rtl-text-align/main.js': mismatch 0.0143585205078125

You should visually compare the expected and actual output from this rendering test - I don’t have the exact path right now, but look in the rendering test directory.

It may be that text rendering on your system is different enough that the tolerance is exceeded for that test.  We could increase the tolerance if that is the case.

**Comment by tschaub** [comment]
Oh, also this:
> case ./cases/layer-vectortile-icon-label/main.js (Vector tile layer declutters image with text correctly)': mismatch 0.014923095703125

**Comment by sumitd2** [comment]
Thank you for the quick response. We are currently testing in an environment which does not have an X display. We will get back to you once we are able to visually test the output.

**Comment by tschaub** [comment]
The rendering tests generate `actual.png` images that are compared with the `expected.png` in the repo.  If you are able to access the files after a test run, download the actual output and compare with the expected.

**Comment by sumitd2** [comment]
Hi,
We ran the rendering tests again using "npm run test-rendering -- --force", here is the output:

_[root@99694bd56f60 openlayers]# npm run test-rendering -- --force

> ol@6.7.0 test-rendering /opt/openlayers
> node test/rendering/test.js "--force"

<i> [webpack-dev-middleware] wait until bundle finished: /cases/circle-style/main.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
93 assets
1192 modules
webpack 5.52.0 compiled successfully in 26264 ms
case ./cases/immediate-pixel-ratio/main.js': mismatch 0.052734375
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
case ./cases/layer-mapbox-vector/main.js (Mapbox vector layer renders)': mismatch 0.1142730712890625
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
case ./cases/layer-vectortile-icon-label/main.js (Vector tile layer declutters image with text correctly)': mismatch 0.0927581787109375
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
case ./cases/rtl-text-align/main.js': mismatch 0.0143585205078125
RENDERING TESTS FAILED
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ol@6.7.0 test-rendering: `node test/rendering/test.js "--force"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ol@6.7.0 test-rendering script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-29T17_04_14_509Z-debug.log_

The actual and expected images for **layer-mapbox-vector** are attached. As you can see, actual.png is a blank image. Can you please tell us what went wrong? 
Thank you.

![actual](https://user-images.githubusercontent.com/91451282/143913404-f582ac39-eeb5-4acf-806f-9cf97539c7bf.png)
![expected](https://user-images.githubusercontent.com/91451282/143913409-bbfd5544-3a35-405d-b809-960e02a4527f.png)

**Comment by sumitd2** [comment]
The following is from an x86_64 one:

+ npm run test-rendering -- --force

> ol@6.7.0 test-rendering /opt/openlayers
> node test/rendering/test.js "--force"

<i> [webpack-dev-middleware] wait until bundle finished: /cases/circle-style/main.js
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
96 assets
1204 modules
webpack 5.52.0 compiled successfully in 16642 ms
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
case ./cases/layer-mapbox-vector/main.js (Mapbox vector layer renders)': mismatch 0.1142730712890625
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
case ./cases/layer-vectortile-icon-label/main.js (Vector tile layer declutters image with text correctly)': mismatch 0.0927581787109375
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
console: Failed to load resource: the server responded with a status of 404 (Not Found)
case ./cases/rtl-text-align/main.js': mismatch 0.0143585205078125
RENDERING TESTS FAILED
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ol@6.7.0 test-rendering: `node test/rendering/test.js "--force"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ol@6.7.0 test-rendering script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
