### ISSUE TITLE
Polygons not renders while dragging the map

### ISSUE THREAD

**Issue by pierluigizagaria** [openlayers/openlayers#12982]
Sorry for this issues not well writed.
I was using different services to render maps on my project and the only reason why I would like to switch from openlayers to other services is how polygons are rendered on the map.
When a polygon goes outside the map view and I move the map to show more of the polygon, it is rendered only on map release, and not during the mouse drag operation.

Is there any method to render polygons as tiles render on the map?

Thank you for reading and have a nice day!

**Comment by ahocevar** [comment]
You can configure the `Vector` layer with `updateWhileInteracting: true`. If you also want the polygons to update during zooming, add `updateWhileAnimating: true`.

**Comment by pierluigizagaria** [comment]
Well... Thank you for much!
