### ISSUE TITLE
ol.layer.Vector in ol.source.Raster causes: Unsupported rendered element: undefined

### ISSUE THREAD

**Issue by ChrisHSandN** [openlayers/openlayers#12983]
**Describe the bug**
While using a `ol.layer.Vector` (in `rendermode:image`) within an `ol.source.Raster`, once the vector extent is panned off screen OL throws an error.

**To Reproduce**
1. Go to https://jsfiddle.net/chris_h/5p3wLcvy/
2. Click on `<button>Break Me</button>` (or just pan map in any direction far enough that the white circle is well off the screen)
3. See error in console 

```
Raster.js:918 Uncaught Error: Unsupported rendered element: undefined
    at zw (Raster.js:918)
    at n.Ac (Raster.js:801)
    at n.getImage (Raster.js:779)
    at n.prepareFrame (ImageLayer.js:76)
    at n.render (Layer.js:256)
    at n.renderFrame (Composite.js:122)
    at n.Fe (PluggableMap.js:1455)
    at n.<anonymous> (PluggableMap.js:214)
```

**Expected behavior**
That once outside of the vector layer extent, the Raster layer should continue to work.

From my debugging, the issue seems to be triggered by:

1. `ol/source/raster::getImageData()` calls `renderFrame()`, 
2. `ol/renderer/canvas/VectorLayer::renderFrame()` has `replayGroup.isEmpty() === true` so returns `null`.
3. `getImageData()` receives `null` rather than the expected `HTMLCanvasElement` and errors.

**Comment by mike-000** [comment]
`renderMode: 'image'` was deprecated in version 6.0.0.  Use `ol.layer.VectorImage` instead https://jsfiddle.net/us9gaxjd/

**Comment by ChrisHSandN** [comment]
Wow, perfect - fixed the issue in one. Thanks for your help  👍
