### ISSUE TITLE
Deploy preview fails for new contributors

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#12991]
**Describe the bug**
The deploy preview task fails on PRs of new contributors before/without approval

**To Reproduce**
1. I've seen it in #12988 and #12985
2. See error

**Expected behavior**
It should either not start the deploy preview task or complete successfully

**Comment by tschaub** [comment]
It feels like a GitHub bug that `pull_request_target` jobs run for new contributors without approval while all the other jobs are pending until approval.  I'll open an issue and hear what they say (I'll use #12985 as an example, so if it can stay unapproved for a little longer that might help).  Perhaps it is a feature.  I'm not sure if there is anything we can do to keep the job pending until approval.

The workaround is to rerun the deploy preview job after approving the rest of the workflow.

**Comment by tschaub** [comment]
The support ticket pointed me to [the docs](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) (which I had read and forgotten), clarifying that

> Workflows triggered by pull_request_target events are run in the context of the base branch. Since the base branch is considered trusted, workflows triggered by these events will always run, regardless of approval settings.

Until there is better support in GitHub workflows to depend on one another (so our deploy workflow can depend on our build workflow), I think we might have to live with the issue of deploys timing out while the build is awaiting approval.

I'll keep digging to see if there is an alternative.

**Comment by tschaub** [comment]
It looks like the [`workflow_run` event](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run) should get us what we need.  I've updated the deploy preview workflow in #13009.
