### ISSUE TITLE
The map cannot show up when use tileloadfunction with basic auth to get map tile

### ISSUE THREAD

**Issue by ronaldwu** [openlayers/openlayers#12993]
I have checked below issues, and do the same with what the right answer said, but still not show up in the map div.

https://github.com/openlayers/openlayers/issues/5401

after I use F12 developer tool, I can saw the request return the image response in the preview, but it seems when assign the wrap url to the tile src, it cannot get the image.

the wrap link like below, I use .net core with react, and this is my local env to do my job.
blob:https://localhost:44352/bb50d76a-b163-4917-857d-a6f89840107f

-------------------------------------------------------------------------
function tileLoader(tile, src) {
	const client = new XMLHttpRequest();
	client.open('GET', src);
	client.responseType = 'arraybuffer';
	client.setRequestHeader('Authorization', 'Basic ' + btoa('mysecret'));
	client.onload = function () {
	  const arrayBufferView = new Uint8Array(this.response);
	  const blob = new Blob([arrayBufferView], { type: 'image/png' });
	  const urlCreator = window.URL || window.webkitURL;
	  const imageUrl = urlCreator.createObjectURL(blob);
	  tile.getImage().src = imageUrl;
	};
	client.send();
}
map = new Map({
	target: 'map',
	layers: [
	  new ImageLayer({
		source: new ImageWMS({
		  params: { SERVICE: 'WMS', VERSION: '1.3.0', REQUEST: 'GetMap', LAYERS: 'ENC', CRS: 'EPSG:3857', WIDTH: '1400', HEIGHT: '1000', BBOX: '-8251945,4917810,-8197293,4950105', FORMAT: 'image/png' },
		  url: 'https://our-map-supplier/?',
		  imageLoadFunction: tileLoader,
		  serverType: 'geoserver'
		})
	  })
	],
	view: new View({
	  center: centerPt,
	  zoom: 7
	})
});
-------------------------------------------------------------------------
I don't know how to resolve this, any one can help me?

Thanks

**Comment by mrpan** [comment]
you should create an application that exposes the problem.

**Comment by ronaldwu** [comment]
yes, I created app and I saw the issue is map image cannot display in the browser. I tried many way to resolve it, but all failed.

**Comment by ahocevar** [comment]
Does the server send CORS headers?

**Comment by ronaldwu** [comment]
seems no, when I tried send post request to map server, no CORS in the header.

Anyone can help me? Thanks

**Comment by ahocevar** [comment]
You either need a server that sends CORS header, or set up a proxy server that adds those. There is no way to fix this on the browser side.

**Comment by ronaldwu** [comment]
OK, I will try this, Thanks for you help, @ahocevar
