### ISSUE TITLE
WebGLTile Layer missing `setStyle` method

### ISSUE THREAD

**Issue by constantinius** [openlayers/openlayers#13019]
Currently, there is no way to replace the visualization of a `WebGLTile` Layer object, it is only possible to completely remove the layer and insert a new one. There are setters for other visualization properties (variables and source).

One use-case for this is letting users define the visualization dynamically, without throwing away the already downloaded raster data (e.g: in case of GeoTIFFs).

I'm aware that changing the style is more work (rebuilding shaders, re-binding buffers and textures, etc) but I think this function would be quite beneficial.

**Comment by tschaub** [comment]
I've put up a draft pull request for this at #13020.

**Comment by constantinius** [comment]
Thanks a lot for the quick response! I'm curious to see this work!

**Comment by constantinius** [comment]
@tschaub / @ahocevar: I finally got to test it, but unfortunately, when I use this I only get white images rendered. This is the App I'm using it in: https://github.com/geotiffjs/dem-app/blob/use-setStyle/src/components/Map.vue#L70

For now I have to replace the whole layer.

**Comment by constantinius** [comment]
Could now finally test it, seems to work fine, thanks!
