### ISSUE TITLE
Having a TileGrid origin bottom left instead of top left

### ISSUE THREAD

**Issue by jaslee** [openlayers/openlayers#13014]
**Is your feature request related to a problem? Please describe.**
We have a custom tile set in British grid where we assume the origin to be Bottom Left but TileGrid API documentation states "Tile coordinates increase left to right and downwards" which sounds like the API can only accept tiles with Top Left origin, is that correct?

**Describe the solution you'd like**
The Openlayers API should cater for custom tiles with alternative origins such as Bottom Left rather than just Top Left. I am sure we had no issue with this in previous Openlayers versions.

**Comment by mike-000** [comment]
TMS grids are supporting can  by specifying `-y` in the tile template https://openlayers.org/en/latest/examples/canvas-tiles-tms.html

**Comment by jaslee** [comment]
Thanks for replying Mike. Would that be the "official" way to implement this custom origin?
I did find another way using our original Openlayers 3 code, but similarly modifying the y as follows:
//===========================================
my_customTileLayer = new ol.layer.Tile({
  source: new ol.source.TileImage({
    extent: my_customBounds,
    projection: my_bng_projection,
    tileGrid: new ol.tilegrid.TileGrid({
      origin: [my_customBounds[0], my_customBounds[1]],
      resolutions: my_customResolutions
    }),
    tileUrlFunction: function(tileCoord, pixelRatio, projection) {
      var z = tileCoord[0];
      var x = tileCoord[1];
      var y = -tileCoord[2]-1;   //= Rather than: var y = tileCoord[2];
...etc.
//===========================================

**Comment by mike-000** [comment]
Either is acceptable, these example use the same tileset:

The `{-y}` placeholder works when the tiles fit into the height of the tilegrid extent, no need to specify an origin, but you may need to specify a layer extent to deal with overflow https://codesandbox.io/s/simple-forked-j34e1?file=/main.js

If you have tiles overflowing the grid extent you need will need a `tileUrlFunction`.  The origin must be specified but a layer extent will not be needed https://codesandbox.io/s/simple-forked-o33ko?file=/main.js

**Comment by jaslee** [comment]
Thanks again. The 2nd example you gave is more or less the implementation I already developed so I will keep to that.

**Comment by tschaub** [comment]
I'll close this assuming your issue is resolved.
