### ISSUE TITLE
Touch pan/zoom not working in certain cases in OL 6 on Android Chrome and Edge browsers

### ISSUE THREAD

**Issue by TomazicM** [openlayers/openlayers#13010]
**Describe the bug**
I have a map with simple raster layer and vector layer, consisting of mountain tracks. On PCs it works OK, but on Android mobile devices map panning and zooming is very slow when large number of paths are shown in vector layer. To avoid this, I catch view change events. On each pan/zoom, change event is fired twice: once before pan/zoom, once after. On first event, I set visibility of vector layer to false, so during map pan/zoom vector layer is hidden. On second event, I set visibility of vector layer to true again.

This worked great with OL 5.3.1, but now that I have switched to OL 6, it doesn't work any more on Android touch devices with Chrome and Edge browsers. Firefox works OK. I tried with OL 6.3.1 and latest 6.9.0. Any touch pan or zoom is interrupted almost immediately after start.

**To Reproduce**
Here is simple reproducible code. Source for vector layer can be any.
```
var vectorLayer = new ol.layer.Vector({
  source: vectorSource
});

var osmLayer = new ol.layer.Tile({
  source: new ol.source.OSM(),
});

var view = new ol.View({
  smoothResolutionConstraint: false,
  constrainResolution: true
});
            
var map = new ol.Map({
  layers: [osmLayer, vectorLayer],
  target: 'map',
  view: view
});     
map.getView().fit(vectorLayer.getSource().getExtent());

var firstChange = true;
view.on('change', function(evt) {
  console.log('view change: first', firstChange);
  firstChange = !firstChange;
  vectorLayer.setVisible(firstChange);
});
```

**Expected behavior**
Map touch pan and zoom should work and Android touch devices for OL 6 when vector layer is dynamically hidden at the start of pan/zoom in view change event processing function.

**Comment by TomazicM** [comment]
Finally found the reason for this behavior and a way to avoid it.

After some debugging I found out that in Chrome and Edge browsers on touch devices, after drag pan starts and some dragging is done, `pointerCancel` event is fired which causes `pointerUp` to be fired and so drag pan is stopped/canceled.

Description of `pointerCancel` event says (see https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/pointercancel_event):

> Event is fired when the browser determines that there are unlikely to be any more pointer events, or if after the pointerdown event is fired, the pointer is then used to manipulate the viewport by panning, zooming, or scrolling

The key part here is: "**after the pointerdown event is fired, the pointer is then used to manipulate the viewport by panning, zooming, or scrolling**"

This still was not enough to understand why this happens. Then finally I stumbled upon CSS property `touch-action` (see https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), where description among other things says this:

> By default, panning (scrolling) and pinching gestures are handled exclusively by the browser. An application using Pointer events will receive a pointercancel event when the browser starts handling a touch gesture. By explicitly specifying which gestures should be handled by the browser, an application can supply its own behavior in pointermove and pointerup listeners for the remaining gestures. Applications using Touch events disable the browser handling of gestures by calling preventDefault(), but should also use touch-action to ensure the browser knows the intent of the application before any event listeners have been invoked.

Since OL handles all mouse/touch actions by itself  through pointer events, all it had to be done is to add `touch-action: none;` to the `map` CSS class definition, and the problem was gone.

This probably should be included on OL CSS definitions.

**Comment by ahocevar** [comment]
Well, we had that in the CSS for a while, but changed the way we handle that to allow in-page scrolling of the map. See #10332.

But if you have a map on a page that does not need scrolling, it may make sense to add `touch-action: none` to the map target's css.
