### ISSUE TITLE
Example code for Amazon Location Services for the website

### ISSUE THREAD

**Issue by ashwallace** [openlayers/openlayers#13016]
Took me a while to figure out. Thought I would share
[open layers amazon location service example code.zip](https://github.com/openlayers/openlayers/files/7551248/open.layers.amazon.location.service.example.code.zip)
.

**Comment by tschaub** [comment]
Please reopen if you are not a bot.

**Comment by ashwallace** [comment]
> 
> 
> Please reopen if you are not a bot.

i make no guarantees about my organic or mechanical construction

**Comment by jahow** [comment]
I've opened the zip (I know) and it looks like legit code :slightly_smiling_face: Although I think this is not so much an issue as an example that could be hosted somewhere. Maybe too specific for the "official" OL examples, but would be interesting in something like observablehq.com I guess.

**Comment by ashwallace** [comment]
github doesnt let you attach html or js files so i opted to zip.  apologies if it appeared untrustworthy. i disagree with what you say about specific examples. there already is arcgis, esri, mapbox, bing. There is too many 3rd party dev culture sites to keep track of when it could simply be discoverable on the OL site. most business use AWS therefore this would be a good compliment to the example set.

**Comment by tschaub** [comment]
@ashwallace - Thanks for not taking offense at my response.  One option for sharing an example is to put it on codesandbox.io.  If you look at one of the existing examples (e.g. https://openlayers.org/en/latest/examples/simple.html), you can click the “Edit” button and get taken to an editable version of the same.  After editing an example to include the functionality you want, you can share the URL in a ticket.

Another option is to create a pull request with your proposed example.  The examples for all pull requests are built and hosted so reviewers can preview them.
