### ISSUE TITLE
Question about use of "object naming" ?

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#13024]
Hi
Sorry this is just a question for my knowledge ...
Before with the prior version < 6.6 ? i had some code that stoped to work when i use > 6.6 and 6.9 it seems due to a change of the "object naming"?
for example
 idIndex_ become Tu
values_ become A
_id become W
array_ become R
strokeStyle_.color_ become Kh.Gs
... 

so my question is somebody can explain when and why this had changed  > 6.6 ? and is it a documentation ? or give me some links to understand better ?

Many thanks

**Comment by TomazicM** [comment]
Mike answered this here: https://gis.stackexchange.com/questions/416701/web-console-result-is-not-comprehensible-when-switched-to-new-openlayers-library

**Comment by jipexu** [comment]
Thanks for the links !
Effectively the mike answer is shorter as the new private property names ... and sure the final code is less human readable... 
example

```            
graticule.strokeStyle_.color_="rgba(0,0,0,0.2)";
become
graticule.Kh.Gs="rgba(0,0,0,0.2)";
```
good it doesn’t do anything the main thing is to know it ...

**Comment by ahocevar** [comment]
Well, private means you shouldn't be using it anyway. If you want to use the legacy build know what you're doing, you can always create your own build with something like https://github.com/phpmyadmin/phpmyadmin/pull/16959. If you use a bundler and know what you are doing, you can access private properties. The latter is quite easy, e.g. with https://www.npmjs.com/package/create-ol-app, and gives you much nicer debugging thanks to source map support, nicer than with the pre-6.7 legacy build.

**Comment by jipexu** [comment]
@ahocevar many thank for your answer even if I do not understand everything (but I will try!)... I know that the applications I maintain are coded according to my knowledge and that I do not use the right method recommended ... In the above example I don’t know how to write this other than using private property to make it work... I will try to understand the two links you mentioned. I searched in the documentation and in some js files to know where and when these names are assigned but I did not find ...

**Comment by ahocevar** [comment]
Whenever you think you need to access private properties, there is a chance you're doing things wrong. In your above example, the API way to do it would be to create a graticule with the desired style
```js
new Graticule({
  strokeStyle: new Stroke({
    color: 'rgba(0,0,0,0.2)',
  });
});
```
If that isn't sufficient, you could file a feature request to make the stroke style settable after instantiation.

**Comment by ahocevar** [comment]
I realize the documentation for the `strokeStyle` property is misleading. I submitted #13026 to improve that.

**Comment by jipexu** [comment]
@ahocevar thank to take time and sorry because my example is out of context and was just to point the change ... 
the true code is more far in my js when i want modify the graticule that i have **created** according to **your** example...
```
$("#grillebox").change("click", function () {
         if(this.checked) {
            graticule.showLabels=true;
            graticule.strokeStyle_.color_="rgba(0,0,0,0.2)";
            graticule.setMap(map);
         }
         else{
            graticule.showLabels=false;
            graticule.setMap(map);
            graticule.strokeStyle_.color_="rgba(0,0,0,0)";
         }
```
or this example
`popup.setPosition(src_user.idIndex_[u].values_.geometry.flatCoordinates);`

so in this 2 examples i have just replaced the occurence and it's works of course but for this 2 examples i dont know other way to write it in my js ...

**Comment by mike-000** [comment]
If you assign the `strokeStyle` to a variable when you create the graticule you can update it using the `setColor()` method https://codesandbox.io/s/graticule-forked-eq6ut?file=/main.js

Public methods return the values of private properties.  The documented equivalent of the second example is `src_user.getFeatureById(u).getGeometry().getFlatCoordinates()`

**Comment by jipexu** [comment]
Thanks @ you both for your light ! 
So i realize that when i dont find a "native" fonction (as @mike-000 write) i use some other ways and as @ahocevar  write this can be dangerous and is not recommanded ! So conclusion i will try to follow your advices to have a better code (this will be more easy to maintain).
Thank
