### ISSUE TITLE
MapboxVector does not render dark map style

### ISSUE THREAD

**Issue by louptheron** [openlayers/openlayers#13023]
**Describe the bug**
When using  the [`mapbox/dark-v10`](https://api.mapbox.com/styles/v1/mapbox/dark-v10.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#1.07/0/0)  style with `MapboxVector` the style render with light colors on lands, in place of dark ones.

**To Reproduce**
1. Go to https://codesandbox.io/s/mapbox-vector-layer-forked-z7g4q?file=/main.js
2. Replace `YOUR_ACCESS_TOKEN` with your Mapbox access token
3. See that the colors on lands in light

**Expected behavior**
When using Mapbox GL JS, the style render correctly : https://jsfiddle.net/pj2s491b/

**Comment by ahocevar** [comment]
The problem is that the MapboxVector layer does not pick up the background. Alternatively, you could use ol-mapbox-style to create the layer, as shown in the [mapbox-style](https://openlayers.org/en/latest/examples/mapbox-style.html) example.

**Comment by louptheron** [comment]
Thank you for the quick response.

Indeed I've seen that `olms` could be used, but as I need full control on the OpenLayers instance on our project, I can't use it.
Thanks for the fix idea, keen to have your thougths !

**Comment by ahocevar** [comment]
#13025 adds the style's background color to a MapboxVector layer.

**Comment by louptheron** [comment]
Thank you !
