### ISSUE TITLE
Publish updated tutorials from this repo

### ISSUE THREAD

**Issue by WebMechanic** [openlayers/openlayers#13047]
**Is your feature request related to a problem? Please describe.**

I **reluctantly** followed the [Application setup](https://openlayers.org/en/latest/doc/tutorials/bundle.html) tutorial because it mentioned Parcel as the bundler. I have no intention to deal with yet another system just to get a peak into some example code.
However, being courageous and ready to run `rm -rf` later on, I ran the command `npx create-ol-app` and found myself with a **Vite** installation, which is entirely different from what's on the page -- and a good thing FWIW.

The README in the then generated project mentions yet another command to install the demo application using Vite, that's neither mentioned in the online tutorial nor the documentation section of this repo: `npx create-ol-app my-app --template vite`.

**Describe the solution you'd like**

Although not on par with reality of "create-ol-app", please publish the updated [documentation](https://github.com/openlayers/openlayers/blob/main/doc/tutorials/bundle.md) sources of this repo that match the current setup people get when they run the scripts so they know what to expect.

Thank you.

**Comment by ahocevar** [comment]
The docs are versioned, and by the time the latest release (v6.9.0) was updated, the tutorial was still for Parcel. https://openlayers.org/en/main/doc/tutorials/bundle.html has the updated tutorial already, and so will the docs for the next release.

**Comment by WebMechanic** [comment]
ok, thanks ... so this is already in the making?
'cos there is no link to that "main" folder or the "bundle.html" page in
 - https://openlayers.org/en/latest/doc/tutorials/
That's what the site's **main menu** points to, and it has the word "latest" in it ;-) so does the "Quick Start" 🤔

**Comment by ahocevar** [comment]
Yes, this is in the making, and will show up under https://openlayers.org/en/latest/doc/tutorials/ automatically when we publish the next release.

The docs under https://openlayers.org/en/latest/doc/tutorials/ are for the latest published version, which is the same as https://openlayers.org/en/v6.9.0/doc/tutorials/ at the time of writing.
