### ISSUE TITLE
WebGLTile pixel manipulation

### ISSUE THREAD

**Issue by All4Gis** [openlayers/openlayers#13049]
Hi

I was testing the new webglTile classes.

Well currently I'm using a raster surce to manipulate the colors of the pixels.

```
function whiteToColorLinearGradient(pixel, vectorRGBA) {
  let r = pixel[0] / 255;
  let g = pixel[1] / 255;
  let b = pixel[2] / 255;
  pixel[0] = 255 * (1 - r) + vectorRGBA[0] * r;
  pixel[1] = 255 * (1 - g) + vectorRGBA[1] * g;
  pixel[2] = 255 * (1 - b) + vectorRGBA[2] * b;
  pixel[3] = vectorRGBA[3];
  return pixel;
}

const RasterSource = source => {
  return new OlRasterSource({
    sources: [source],
    // On every render of the layer the code inside operation will be executed
    operation: function(pixels, data) {
      var pixel = pixels[0];
      if (data.rasterColor || data.palette) {
        var val = getPixelValue(pixel);
        if (val !== 0) {
          if (data.palette) {
            pixel = gradientFunction(pixel[0], data.palette);
          } else {
            pixel = whiteToColorLinearGradient(pixel, data.rasterColor);
          }
        }
      }

      return pixel;
    },
    // LOOK: getRasterSourceLib is a mandatory way of import the functions that will be used inside operation due a compiler issue
    // lib: object with the functions that the worker will receive
    lib: getRasterSourceLib([
      getPixelValue,
      whiteToColorLinearGradient,
      gradientFunction
    ])
  });
};
```

I was trying WebGLTile but I don't really know how it works or how to make the shader. Any documentation?Any help about shaders?any help that can give me a hint on how to do this?How can I access the red value of a pixel? Too many questions, hehehe. 

```
const WebGLTileSource = source => {
  let r = ["/", ["band", 1], 255];
  let g = ["/", ["band", 1], 255];
  let b = ["/", ["band", 1], 255];

  let r2 = ["*", ["var", "red"], r];
  let g2 = ["*", ["var", "green"], g];
  let b2 = ["*", ["var", "blue"], b];

  let r3 = ["*", 255, ["-", 1, r]];
  let g3 = ["*", 255, ["-", 1, g]];
  let b3 = ["*", 255, ["-", 1, b]];

  const newRed = ["+", r3, r2];
  const newGreen = ["+", g3, g2];
  const newBlue = ["+", b3, b2];

  return new TileLayer({
    source: source,
    style: {
      color: ["color", newRed, newGreen, newBlue],
      variables: {
        red: 3,
        green: 200,
        blue: 200
      }
    }
  });
};
```

Thank you very much for your help.

**Comment by mike-000** [comment]
For the original colors (which is the same as the default style) you would need

    color: [
      "color",
      ["*", 255, ["band", 1]],
      ["*", 255, ["band", 2]],
      ["*", 255, ["band", 3]]
    ]

https://codesandbox.io/s/webgl-tile-style-forked-koick?file=/main.js

Therefore you do not need to divide by 255 and I think you are trying to achieve something like

https://codesandbox.io/s/webgl-tile-style-forked-cnb1x?file=/main.js

**Comment by All4Gis** [comment]
Thanks, This is exactly what I was looking for, I was on the right track. 
https://codesandbox.io/s/webgl-tile-style-forked-cnb1x?file=/main.js
It's a bit too dark for me this part of webgl.hehehe.

Thanks again

**Comment by All4Gis** [comment]
I don't know if this is related to this ticket. https://github.com/openlayers/openlayers/issues/10457

But applying these styles, the tiles outside my area appear blank.With color expression:


![Screenshot from 2021-11-29 10-47-26](https://user-images.githubusercontent.com/8123225/143848987-6d41ac84-e22e-4cd6-a6d7-74243e2a66b1.png)

without color expression:

![Screenshot from 2021-11-29 11-10-00](https://user-images.githubusercontent.com/8123225/143849048-807bd2b6-241f-44ed-abf2-deb3f7e0c98c.png)



Maybe I need to add some options in the shader. I have tried with opaque:false in the XYZ source as well

**Comment by mike-000** [comment]
You may need to include alpha in the expression https://codesandbox.io/s/webgl-tile-style-forked-twggw?file=/main.js

**Comment by All4Gis** [comment]
mmm... I don't think it is related to the alpha value, this value is applied to everything and the white tiles still appear but with that alpha obviously applied.
![Screenshot from 2021-11-29 12-18-00](https://user-images.githubusercontent.com/8123225/143858954-9816986f-3146-4cee-9e0a-ac95d5668043.png)

It may be that when a colour expression is applied, it is applied to the whole area of the layer so that the empty tiles appear white, which I guess is the default colour? I just got caught up in my own thoughts.

**Comment by mike-000** [comment]
You could set white to transparent by defining the alpha as

`["case", ["all", ["==", ["band", 1], 1], ["==", ["band", 2], 1], ["==", ["band", 3], 1]], 0, 1]`

**Comment by All4Gis** [comment]
Finally working and applying also the alpha value.
```
const variables = {
    red: 255,
    green: 0,
    blue: 0,
    alpha: 0.5
  };

  return new TileLayer({
    source: source,
    style: {
      color: [
        "color",
        [
          "+",
          ["*", 255, ["-", 1, ["band", 1]]],
          ["*", ["var", "red"], ["band", 1]]
        ],
        [
          "+",
          ["*", 255, ["-", 1, ["band", 2]]],
          ["*", ["var", "green"], ["band", 2]]
        ],
        [
          "+",
          ["*", 255, ["-", 1, ["band", 3]]],
          ["*", ["var", "blue"], ["band", 3]]
        ],
        ["*", ["var", "alpha"], ["band", 4]]
      ],
      variables: variables
    }
  });
};
```

![Screenshot from 2021-11-29 13-10-26](https://user-images.githubusercontent.com/8123225/143865916-63a535e9-b28e-4175-9a53-603973963d5d.png)


Thank you very much for your help. Close the ticket if you want
