### ISSUE TITLE
Icons based on registry

### ISSUE THREAD

**Issue by pelord** [openlayers/openlayers#13043]
**Is your feature request related to a problem? Please describe.**
Is it possible to connect an Icon src to a icon registry?

Here the current situation:

```
rome.setStyle(
  new Style({
    image: new Icon({
      color: '#BADA55',
      crossOrigin: 'anonymous',
      // For Internet Explorer 11
      imgSize: [20, 20],
      src: 'data/square.svg',
    }),
  })
);
```
**Describe the solution you'd like**
Based an a icon registry (i.e. : https://materialdesignicons.com/ ), be able to specify an icon only by his name

```
rome.setStyle(
  new Style({
    image: new Icon({
      color: '#BADA55',
      crossOrigin: 'anonymous',
      // For Internet Explorer 11
      imgSize: [20, 20],
      src: 'romeIcon',
    }),
  })
);
```

**Comment by mike-000** [comment]
Those icons are available via jsdelivr.  You must include the path and .svg extension `https://cdn.jsdelivr.net/npm/@mdi/svg@6.5.95/svg/xxxxxxxx.svg`

https://codesandbox.io/s/icon-color-forked-pzlqb

**Comment by pelord** [comment]
Thanks! But in a offline mode, these will not work properly.

**Comment by mike-000** [comment]
You would need to download them for local use.  The easiest way to do that would be to create a local clone of the repository https://github.com/Templarian/MaterialDesign/tree/master/svg

**Comment by pelord** [comment]
Yes you are right...

Refer to this.
https://github.com/Templarian/MaterialDesign/issues/4913
