### ISSUE TITLE
Cloud Optimized GeoTIFF example is not working on codesandbox

### ISSUE THREAD

**Issue by drnextgis** [openlayers/openlayers#13046]
Cloud Optimized GeoTIFF [example](https://openlayers.org/en/latest/examples/cog.html) is not working on [codesandbox](https://codesandbox.io/s/owk4e). I [filed](https://github.com/codesandbox/codesandbox-client/issues/6313) an issue at codesandbox repository too because it's not clear on which side the problem is.

**Comment by EvertEt** [comment]
Also noticed it on https://openlayers.org/en/latest/examples/center.html and some others.
https://openlayers.org/en/latest/examples/simple.html seems to work still.

**Comment by howff** [comment]
The error is
```
TypeError
Cannot read properties of undefined (reading 'registerSerializer')
```

It occurs during
```
import GeoTIFF from "ol/source/GeoTIFF";
```

The stack trace is
```
$csb$eval
https://owk4e.csb.app/node_modules/threads/index.mjs:8:49
H
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:100070
K.evaluate
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:112781
ge.evaluateTranspiledModule
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:123151
c
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:112509
$csb$eval
https://owk4e.csb.app/node_modules/geotiff/src/pool.js:5:21
H
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:100070
K.evaluate
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:112781
ge.evaluateTranspiledModule
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:123151
c
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:112509
$csb$eval
https://owk4e.csb.app/node_modules/geotiff/src/geotiff.js:74:19
H
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:100070
K.evaluate
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:112781
ge.evaluateTranspiledModule
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:123151
c
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:112509
$csb$eval
https://owk4e.csb.app/node_modules/ol/source/GeoTIFF.js:11:21
H
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:100070
K.evaluate
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:112781
ge.evaluateTranspiledModule
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:123151
c
https://codesandbox.io/static/js/sandbox.dd729db92.js:1:112509
$csb$eval
https://owk4e.csb.app/main.js:5:16
```

**Comment by ahocevar** [comment]
I'm pretty sure this has to do with the fact that Code Sandbox cannot handle the worker that geotiff.js uses.

**Comment by drnextgis** [comment]
It was working there couple of weeks ago.

**Comment by rooby** [comment]
This one is also broken: https://openlayers.org/en/latest/examples/arcgis-tiled.html

**Comment by ahocevar** [comment]
Unfortunately, #13292 did not fix this issue. codesandbox uses the browser build of geotiff.js (`dist-browser/geotiff.js` and complains about a missing import, which is not a package at all. Need to investigate further if this is a geotiff.js problem or a codesandbox problem.

**Comment by ahocevar** [comment]
Using the latest dev version and upgrading geotiff to v2.0.4 finally fixes the problem.
