### ISSUE TITLE
With OL 6.9.0 support for IE11 ends (even with polyfills)

### ISSUE THREAD

**Issue by TomazicM** [openlayers/openlayers#13052]
This is more a finding that anything else. With OL 6.8.1 it was still possible to use OL with some polyfills in IE11.

In OL 6.9.0  module `@petamoriken/float16` is used, which in turn uses `Reflect`. Despite the fact that https://polyfill.io/v3/url-builder/ offers polyfills for `Reflect` and it's methods, these polyfills do not work.

This is also stated on `@petamoriken/float16` module on [GitHub](https://github.com/petamoriken/float16/):

> Float16Array implemented by Proxy and Reflect, so IE11 is never supported even if you use polyfills.

**Comment by mike-000** [comment]
See https://github.com/openlayers/openlayers/issues/12896#issuecomment-945623644

**Comment by ahocevar** [comment]
@TomazicM, this essentially means you can continue using IE11 after the fix that @mike-000 mentioned. You can try that with the deploy preview of #12891 or later: https://deploy-preview-12891--ol-site.netlify.app/

**Comment by TomazicM** [comment]
Mike and Andreas, thanks for your response. In the meantime I did some research myself and came to the same conclusion and solution as Mike did in his [#12896 (comment)](https://github.com/openlayers/openlayers/issues/12896#issuecomment-945623644).

My fix was almost exactly the same as Mike's one and it works. If I understand correctly the [#12891](https://github.com/openlayers/openlayers/pull/12891) pull, this mock polyfill will be included in the future OL releases?

**Comment by mike-000** [comment]
The recommended polyfills https://github.com/openlayers/openlayers#supported-browsers have been updated to include `core-js`.  However you could continue to use the much smaller `polyfill.io` alone if you include a mock polyfill for `Reflect` as currently its only purpose in pre-ES6 browsers is to allow the library to load.
