### ISSUE TITLE
You can move two objects at once

### ISSUE THREAD

**Issue by Spencehiko** [openlayers/openlayers#13059]
When I try to move a circle that is on top of another shape's edge, the circle moves and the shape is getting modified. Is there any way to restrict this? Like giving shapes z-indexes or making them non-transparent?

**To Reproduce**
You can directly go to this [openlayers example](https://openlayers.org/en/latest/examples/draw-and-modify-features.html) and draw a polygon. Then draw a circle on any edge. Then try to move the circle. During this process both circle will be moved and polygon will be edited.

![4rT7JTaLyX](https://user-images.githubusercontent.com/40501852/143889888-f7cc875a-5584-4ad2-8d2a-c286d7561a6e.gif)

As expected, I want to restrict this by enabling interaction on only the top shape, in other words the latest drawn shape.

Thanks in advance.

**Comment by ahocevar** [comment]
This is a feature, not a bug. The Modify interaction allows you to modify shared vertices of topologically adjacent edges of polygons.

To avoid this behavior, configure the `Modify` interaction with a `source` or `features` collection that only contains the features you want to modify. The easiest way to achieve that is by making use of the Select interaction, and configure both interactions with the same `features` collection.

**Comment by Spencehiko** [comment]
Thank you for your quick response @ahocevar ,

I believe your solution will make some features non editable, am I right? I want all the features to be able to be modified and translated but to remove this "modify on shared vertices" spec. Is there a way to do that?

**Comment by ahocevar** [comment]
You could configure the Modify interaction with a `features` collection, and update the contents of that collection on `pointermove`, so it only holds the last feature you hovered:
```js
const collection = new Collection();
const modify = new Modify({features: collection});
//...
map.on('pointermove', (event) => {
  if (!event.dragging) {
    const features = map.getFeaturesAtPixel(event.pixel, {
      layerFilter: (layer) => layer === vector,
    });
    if (
      features.length &&
      (collection.getLength() === 0 || collection.item(0) !== features[0])
    ) {
      collection.clear();
      collection.push(features[0]);
    }
  }
});
```
In a working example, this could look something like https://codesandbox.io/s/draw-and-modify-features-forked-6flgf.

**Comment by Spencehiko** [comment]
I appreciate your answer, it solved my problem ^^ thank you. 

Have a nice, healthy day
