### ISSUE TITLE
Creating rxjs.Observables from events

### ISSUE THREAD

**Issue by jomalla123** [openlayers/openlayers#13062]
I would like create an rxjs.Observable from events that different ol components fire, e.g. in the following way:

```typescript
fromEvent<BaseEvent>(view, 'change').subscribe(value => console.log(value))
```

How ever this will result in the following error (if typescript strict mode is enabled at least):

```
Error:(60, 30) TS2345: Argument of type 'View' is not assignable to parameter of type 'FromEventTarget<BaseEvent>'.
  Type 'View' is not assignable to type 'HasEventTargetAddRemove<BaseEvent>'.
    Types of property 'addEventListener' are incompatible.
      Type '(type: string, listener: ((arg0: Event | BaseEvent) => boolean | void) | ListenerObject) => void' is not assignable to type '(type: string, listener: ((evt: BaseEvent) => void) | null, options?: boolean | AddEventListenerOptions | undefined) => void'.
        Types of parameters 'listener' and 'listener' are incompatible.
          Type '((evt: BaseEvent) => void) | null' is not assignable to type '((arg0: Event | BaseEvent) => boolean | void) | ListenerObject'.
            Type 'null' is not assignable to type '((arg0: Event | BaseEvent) => boolean | void) | ListenerObject'.

```

Is there anything I am doing wrong or is there any better way to connect an event to an rxjs stream?

Full example code that I am using for completeness (I am using ol 6.9 and typescript 3.9) 

```typescript
import {fromEvent} from 'rxjs';

const raster: TileLayer<any> = new TileLayer({
    source: new OSM(),
});

const source: VectorSource<Geometry> = new VectorSource({wrapX: false});

const vector: VectorLayer<any> = new VectorLayer({
    source: source,
});

const layers = [raster, vector] ;
const view = new View({
    center: [-11000000, 4600000],
    zoom: 4,
});
const map = new Map({
    layers: layers,
    target: 'map',
    view: view,
});

**Comment by simonseyock** [comment]
Hey @jomalla123, sorry for the late answer. The problem is that ol and rxjs do not share the same `EventTarget` base type. You might be able to circumvent this Problem by casting the ol type to `FromEventTarget<BaseEvent>`

```
fromEvent<BaseEvent>(view as FromEventTarget<BaseEvent>, 'change').subscribe(value => console.log(value))

**Comment by pelord** [comment]
in 7.5.2, there is no mention to FromEventTarget ? Where did you find it (@simonseyock)?

**Comment by simonseyock** [comment]
That type seems to be removed from rxjs. You can have a look at the types specified here:
https://github.com/ReactiveX/rxjs/blob/c66657469dc17fbed992e273d7d121e51c00d671/packages/rxjs/src/internal/observable/fromEvent.ts#L63
Maybe `HasEventTargetAddRemove` will work.
