### ISSUE TITLE
Question about downloading functionality in openlayer

### ISSUE THREAD

**Issue by Shion1314** [openlayers/openlayers#13063]
Hi, how do you allow the user to download the data they queried from openlayer to a file? For example, after the user query, the data tables show up, how do we allow the user to download that table?

**Comment by mike-000** [comment]
OpenLayers does not have any downloading functuionality of its own as it can be done in JavaScript (note that Internet and Legacy Edge used a non-standard method).

Fetched data can be exported as an object url
https://openlayers.org/en/latest/examples/drag-and-drop.html
https://openlayers.org/en/latest/examples/drag-and-drop-custom-mvt.html
https://openlayers.org/en/latest/examples/drag-and-drop-custom-kmz.html

Canvas can be exported as data url
https://openlayers.org/en/latest/examples/export-map.html

Data urls can also be created from text (e.g. you could save drawn features as GeoJSONs using the `writeFeatures()` method of `ol​/format​/GeoJSON`) and html tables, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by Shion1314** [comment]
Ah, thank you. I will look more into that.
