### ISSUE TITLE
Icon color change

### ISSUE THREAD

**Issue by pelord** [openlayers/openlayers#13068]
**Describe the bug**
When defining an icon, a svg, the applied color is not changed in various case.
Refer to https://codesandbox.io/s/icon-color-forked-1n3wy?file=/main.js

Take a look to the comments into the sandbox
![image](https://user-images.githubusercontent.com/7397743/144269548-2b5342d8-8ab0-4919-abbb-2aace38e6c73.png)

**Expected behavior**
Despite the fill color of the svg, the color must be applied indepedently of the fill color of the svg.

**Comment by MoonE** [comment]
The color is applied with a canvas `multiply` operation, when the icon is already black (r/g/b = 0) then multiplying it will always result in a black color. Whether the svg color is explicitly set to black or it is unset makes no difference as the color is not changed with css.
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

**Comment by pelord** [comment]
Do you think there is an opportunity to add this feature to ol instead of applying a tint over a svg file?
