### ISSUE TITLE
When I turn around the world, shapes may disappear on zoom

### ISSUE THREAD

**Issue by Spencehiko** [openlayers/openlayers#13074]
When I turn around the world 1 or more times(to the left or the right doesn't matter), shapes may disappear on zoom in.

**To Reproduce**
[In this link](https://openlayers.org/en/latest/examples/draw-and-modify-features.html) you can reproduce. Just draw a shape after you turn around the world and zoom in.
![tmglMy0br1](https://user-images.githubusercontent.com/40501852/144380410-b50570d9-3564-4454-bf11-95a167af32fa.gif)

Is there a way to fix it?

Thanks in advance

**Comment by jipexu** [comment]
yes a lot of strange and unstable behaviors in this example ....

**Comment by M393** [comment]
You should only draw Features on the initially visible world. When you scroll to the next or previous world and draw there the checks whether a feature intersects the view may fail which causes it to not be rendered.

Maybe coordinates should by transformed by the Draw/Modify interaction to wrap within the configured view projection.

**Comment by ahocevar** [comment]
OpenLayers can handle coordinates with latitudes from -540 to +540. To avoid surprises in the above example, you could configure the view with a restricted extent:
```js
const extent = get("EPSG:3857").getExtent().slice();
extent[0] += extent[0];
extent[2] += extent[2];
const map = new Map({
  layers: [raster, vector],
  target: "map",
  view: new View({
    center: [-11000000, 4600000],
    zoom: 4,
    extent
  })
});
```
This way, you can only draw geometries that will work in OpenLayers.

**Comment by jipexu** [comment]
@ahocevar  thank for your light ! True if we stay in one world the example work fine ! 
However for me when we play with this example it remains confusing and therefore raises questions. Could we specify the limits you specify in the example documentation ?

**Comment by ahocevar** [comment]
@jipexu I think it would make sense to modify that example to use a restricted extent like in my example above. Would you be willing to create a pull request?

**Comment by jipexu** [comment]
good ! ok i will try...

**Comment by jipexu** [comment]
arghh it start bad ... the example not work in codesandbox ...

**Comment by jipexu** [comment]
https://deploy-preview-13077--ol-site.netlify.app/

**Comment by Spencehiko** [comment]
@ahocevar thank you for your answer. 
>  you could configure the view with a restricted extent:

What if we use a different map service in OpenLayers? How can we restrict the map in this case?

**Comment by Spencehiko** [comment]
Ok I got the solution

**Comment by Spencehiko** [comment]
Ok, I got the solution

**Comment by Spencehiko** [comment]
Ok, I got the solution
```js
const options = map.getView().options_;
options.extent = map.getView().getProjection().getExtent();
map.getView().applyOptions_(options); 
```
after you initialize the map

**Comment by ahocevar** [comment]
@Spencehiko Please don't use private properties and methods (i.e. those with a `_` suffix). Instead, do something like
```js
const options = map.getView().getProperties();
options.extent = map.getView().getProjection().getExtent();
map.setView(new View(options));
