### ISSUE TITLE
[help]stopEvent in overlay and pointermove ?

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#13078]
Hi
I can not find how to stop the pointermove above an overlay
the stopEvent (in overlay) is at true (by default) so the click is stopped but not pointermove ?

In the example below the popup and tooltip are both overlays ...
both build function (OpenPopup and voirinfo) detect feature(s) with map.forEachFeatureAtPixel ...
one function is called by  map.on("click", OpenPopup);
the other is called by map.on("pointermove", voirInfo);

So how to avoid that the markers below de popup overlay answer to the pointermove ?
What i miss ?
Thanks
 

https://user-images.githubusercontent.com/328101/144411294-52adef92-d909-4704-8317-dfa63c0957dc.mov

**Comment by ahocevar** [comment]
This can be achieved by standard DOM event handling. Simply register a `pointermove` listener on the popup container, and call `stopPropagation()` on the event:
```js
container.addEventListener("pointermove", (e) => e.stopPropagation());
```
Here is a working example: https://codesandbox.io/s/popup-forked-bo1z0?file=/main.js:359-430

**Comment by jipexu** [comment]
@ahocevar many thanks 
work fine now 
arghh it was so simple ! ;-(
