### ISSUE TITLE
Opacity, Visibility and Re-ordering on Sub Groups and layers within Sub Groups does not work

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#13080]
When setting the opacity, visibility and re-ordering on a Sub-Group or layer within a Sub-Group does not work.  It does not fire changed event on the layer or sub-group.

Example:

```
MAIN GROUP (Working)
      |
      +---- SUB GROUP (Not Working)
                   |
                   +---- LAYER (Not Working)
```

See the example codepen below (Openlayers only):

[https://codepen.io/1map/pen/MWEwdyo](https://codepen.io/1map/pen/MWEwdyo)

See the example codepen below (Openlayers with ol-ext layerswitcher):

[https://codepen.io/1map/pen/NWaqxwK](https://codepen.io/1map/pen/NWaqxwK)

**Comment by M393** [comment]
You should not modify the layer collection array directly, this will not update the collection length and not fire the necessary events.
```patch
-otherSubLayerGroup.getLayers().getArray().push(otherLayer);`
+otherSubLayerGroup.getLayers().push(otherLayer);
```

**Comment by 1Map** [comment]
Thanks, working 100%. We can close this now.
