### ISSUE TITLE
Features move when zoooming on map

### ISSUE THREAD

**Issue by jeromeBor** [openlayers/openlayers#13081]
Hello,

I'm having a bug where the map zoom does not have the same behaviour on features and layer, depending on screen / browser size configuration.

On my laptop screen, my webapp page is bigger then my screen and it create a scrollable page (in full screen browser). Whenever I zoom in or out, the bitmaplayer and the features on the map "slides" off the map, losing their real positions.

Whenever I reproduce the same step in a wider screen (23,8"), nothing specials happens.  (the scroll bar is not available if I set the browser in full screen)
Whenever I reproduce  this step on a wider screen with the browser page in smaller size (creating the scroll bar) nothing happens, but it does bug.
If I reproduce the step just before on my laptop screen, it does bug.

Notice that i'm with 2 screens, with 2 differents sizes

[Here are a link for 2 video thats show the 2 behaviours](https://we.tl/t-e7YNkwPbur)( less then 2 mb each)

Why does this behaviour happens only on my laptop screen and how can I fix this, if it can be fixed ?

Thanks by advance

**Comment by MoonE** [comment]
Could it be related to `window.devicePixelRatio`. If no pixel ratio is configured the map automatically uses this as the default.
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html

How are you drawing the image?

**Comment by jeromeBor** [comment]
Hi and thanks for your answer.

My image is created wih ol.layer.GeoImage.

I'll look into the devicePixelRatio and tell you if it  helped me
