### ISSUE TITLE
Requested ImageWMS size off by one pixel, thus extent value unexpected

### ISSUE THREAD

**Issue by DanDits** [openlayers/openlayers#13098]
**Describe the bug**
There's a bug, or maybe you could also call it inconsistency, in ImageWms in combination with PluggableMap.js in openlayers version 6.9.0:
When having an (Image)WMS layer in a map it will go the following path to calculate the request extend and size:

1.  PluggableMap.prototype.renderFrame_ (starts at line 1175) calculates an extent using getForViewAndSize, stores it and more into frameState.extent.
3. Now the ImageWMS.prototype.getImageInternal (starts at line 242) comes into play. It gets passed our previously calculated extent and uses it to calculate the center and viewWidth/viewHeight. Due to the Math.ceil involved it can now happen that due to flouting points arithmetics the viewHeight or viewWidth does not equal the actual size from step1 in PluggableMap, e.g. 432.00000000003 is ceiled up to 433.
4. This now causes an image to be requested that is by one pixel bigger than expected. Usually this would not be a problem, but in our usage of openlayers we rely on knowing the algorithm for calculating the WMS parameters so that requests required for other components can benefit from cache hits and hugely improved performance by avoiding slightly different database requests.

We have a workaround by copying the behavior, but it would be great to have this adjusted.

 

**To Reproduce**
Steps to reproduce the behavior (might involve playing around with different browser sizes and zooming to different extents and centers):
1.Have a running openlayers map, add an ImageWMS layer.
2. Inspect the map canvas size or look it up by making some temporary breakpoint where the view size is used. 
3. Create a conditional breakpoint in ImageWMS to trigger if viewWidth or viewHeight is off by one pixel.

**Expected behavior**
Reacting on layer or map events we trigger actions that need to create requests with the same WMS parameters as used for the map request. But also in other user triggered actions we need to have a reliable way of (re)constructing the WMS parameters from the current map view state.
Ideally there would be an official API for that. At the very least we would like to see a floating-arithmetic rounding error free calculation to avoid recreating a rather accidental behavior that is likely to change in upcoming versions.

Thanks and cheers!

**Comment by tschaub** [comment]
Thanks for the report, @DanDits.

I've opened #13103 with a potential fix.  If you are able to provide specific values for the extent, resolution, and viewport size where you see things fail, I could add regression tests.  Also, if you are able to try out the code from that branch, I'd be curious to hear if it addresses the issue you are seeing.

**Comment by DanDits** [comment]
Hi and huge kudos for the fast answer and action!

Some example values where it goes wrong in the 9.3.0 version following the described data flow in PluggableMap via frameSate to ImageWMS essentially looks as follows:

```
viewState.center = [ 1224885.7248147277, 6681822.177576577 ];
viewState.resolution = 354.64216525539024;
viewstate.rotation = 0;
mapSize = [ 1110, 670 ];
renderExtent = getForViewAndSize(viewState.center, viewState.resolution, viewState.rotation, mapSize); // = [ 1028059.323097986, 6563017.052216021, 1421712.1265314692, 6800627.302937133 ]
extentRatio = 1.3; // layer property set to request more than immediately visible. Problem can also appear if extentRatio = 1.0
renderWidth = Math.ceil((extentRatio * (renderExtent[2] - renderExtent[0])) /  viewState.resolution); = 1443, fine
renderHeight = Math.ceil((extentRatio * (renderExtent[3] - renderExtent[1])) / viewState.resolution); // = Math.ceil(871.0000000000016) = 872, off by one
requestExtent = getForViewAndSize(viewState.center, viewState.resolution, viewState.rotation ,[ renderWidth, renderHeight ]); // slighly bigger extent used in WMS getImage request than expected from the layer configuration and state due to off by one error in renderHeight

```

The expected renderHeight would be `mapSize[1] * extentRatio = 670 * 1.3 = 871` and Yes, using the 4 decimal fixed ceil in the mentioned issue would in fact produce the expected 871 here. 

Some random thoughts to the fix, not relevant for this bug:
The fix looks fine to me, though as usual with floating point arithmetic and precision values people will have to pay close attention when and how to use it. 4 decimal values seems fine when handling map sizes as they are pixel based.
Overall I would feel like the best idea would be to not do calculations based on calculated values (here: the renderExtent) but always base everything on the internal state which for openlayers seems to be the `center` and `resolution`.

**Comment by tschaub** [comment]
Thanks for the additional details on the case you encountered, @DanDits.  I'll leave this open until we get a fix in.

Regarding the accumulation of errors, I agree it would be ideal to avoid unnecessary calculations.  In the case of the ImageWMS source (and others) however, we can't only rely on the view size, center, and resolution.  The source may be configured with a fixed set of resolutions – in this case the requested image needs to fill the view extent but may not be the at the same resolution.  The source may also be configured with a different projection than the view – in this case the requested image needs to fill the view extent after being transformed.  In addition, the source may be configured to work with a non 1:1 pixel ratio – so the requested image may not end up being at the same resolution as the view.

I'm not suggesting that things couldn't be reworked to reduce the accumulation of floating point errors, just pointing out that it isn't trivial in all cases.

**Comment by DanDits** [comment]
Right, there's always more behind the scenes than one might hope to get a "clean" solution. And in fact I think we're using most of the things you mentioned: different projections, scale/resolution restrictions and high-dpi.
Looking forward to seeing your commit merged. Thanks for the responses.
