### ISSUE TITLE
Openlayers infinite loop called when clear()

### ISSUE THREAD

**Issue by jeromeBor** [openlayers/openlayers#13094]
I created the function that enable selection of feature from map, with 2 functions thats are called when I click on feature or when I click on map (no feature selected)

E.G

```
select = new ol.interaction.Select({
        toggleCondition: this.isMultipleSelectionEnable
          ? null
          : ol.events.condition.never,
        style: selectedStyle
      })
      this.select = select
      map.addInteraction(select)
      this.selectedFeatures = select.getFeatures()
```

Here are my functions

`this.selectedFeatures.on(['add'] function() {}  // add feature to map)`
 and
` this.selectedFeatures.on(['remove']function(){this.map.clear())`

This works well when I click on my map, but whenever I call the function clear() to clear selectedFeatures from another component, it automaticly calls the 'remove' function from OL, making an infinite loop.

How can I resolve this ? How can we can we clear the selected features from the map, without triggering the "remove" function from OL ? Or can we call directly the 'remove' from another component ?

Thanks by advance for any help

**Comment by mike-000** [comment]
You could either unset and reset the listener, or use `once` instead of `on`, for example

```
const clear = function() {
  this.selectedFeatures.clear();
  this.selectedFeatures.once(['remove'], clear);
};
this.selectedFeatures.once(['remove'], clear);
```

**Comment by jeromeBor** [comment]
Thank you for your answer.
Once doesn't work because it allow to trigger only once, and this is not what I want here. I need the remove and add function to be always working, but not when I call the clear function from another component.
What do you mean by "unset the listener" ?

**Comment by mike-000** [comment]
By unset I mean call `.un()`

```
const clear = function() {
  this.selectedFeatures.un(['remove'], clear);
  this.selectedFeatures.clear();
  this.selectedFeatures.on(['remove'], clear);
};
this.selectedFeatures.on(['remove'], clear);

```
