### ISSUE TITLE
XYZ class causes layer deviation when using html2canvas printinga a picture

### ISSUE THREAD

**Issue by nsjSxue** [openlayers/openlayers#13104]
I user XYZ class as the source to add arcgis tiled layer. The code below:
  const arcgisXYZTileSource = new XYZ({
    tileGrid: tileGrid,
    projection: `EPSG:${spatialReference.wkid}`,
    url: serverUrl,
    tilePixelRatio: 2, 
    crossOrigin: "anonymous",
  });
If I want to use html2canvas ,the layer which I added by XYZ will skew from the orign; 
![image](https://user-images.githubusercontent.com/45844804/145773361-e4e94bac-a607-4660-b746-d8a5ff6a2619.png)

If I use TileArcGISRest class as the source,the picture is normal.
  const arcgisXYZTileSource = new ArcGISTileLayer({
    tileGrid: tileGrid,
    projection: `EPSG:${spatialReference.wkid}`,
    url: serverUrl,
    tilePixelRatio: 2, 
    crossOrigin: "anonymous",
  });
![image](https://user-images.githubusercontent.com/45844804/145773280-a126f093-b7a7-4ed9-9b91-9775515e6da2.png)

**Comment by mike-000** [comment]
The same problem can be seen if `options.tilePixelRatio = 2;` is specified if https://openlayers.org/en/latest/examples/print-to-scale.html `tilePixelRatio` is not a supported option for ol/source/TileArcGISRest which suggests `tilePixelRatio: 2` is the incorrect value for the ol/source/XYZ setup regardless of whether html2canvas works with sources having differing pixel ratios.

**Comment by nsjSxue** [comment]
> The same problem can be seen if `options.tilePixelRatio = 2;` is specified if https://openlayers.org/en/latest/examples/print-to-scale.html `tilePixelRatio` is not a supported option for ol/source/TileArcGISRest which suggests `tilePixelRatio: 2` is the incorrect value for the ol/source/XYZ setup regardless of whether html2canvas works with sources having differing pixel ratios.
Thannks.I solved this problem by  `options.tilePixelRatio = 1` with XYZ source
