### ISSUE TITLE
WebGL tile edge artifacts and edges not rendered

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13116]
**Describe the bug**
When zooming beyond the maxZoom of a tile source using the WebGL render tile edges can become very noticeable due to artifacts, and when close to the viewport edges the tiles are not rendered.

**To Reproduce**
Observed when investigating #13100 but can also be seen in the Data Tiles and NumpyTiles examples if the maxZoom of the tile source is restricted (e.g. `maxZoom : 17` for NumpyTiles).

When zooming beyond the maxZoom of a tile source `gl.LINEAR` breaks down at the first and last pixels of rows and columns creating artifacts - that is probably unavoidable (there are no artifacts if the output is pixelated using `gl.NEAREST`)
https://codesandbox.io/s/disable-image-smoothing-webg-float32-forked-eo9cm
![image](https://user-images.githubusercontent.com/49240900/146179619-06f7f882-bb4b-4dc9-a3a0-ed60af4858c5.png)

Additionally the topmost or leftmost rows and columns do not render if they are the only part of the tile in the viewport - this can happen even when using `gl.NEAREST` - could this be a rounding issue?
![image](https://user-images.githubusercontent.com/49240900/146179675-b3b43dcb-d8de-4c28-8232-26f5f5af1517.png)

**Expected behavior**
Artifacts might be unavoidable but if any part of a row or column is in the viewport it should be rendered.

**Comment by tschaub** [comment]
#13155 adds an `interpolate` option for data tile sources.  This makes it possible to avoid resampling artifacts along tile edges.

The lack of data when a tile edge is near the viewport edge is due to the behavior of the `grid.getTileRangeForExtentAndZ()` method – that will be handled separately.

**Comment by tschaub** [comment]
The second issue is addressed by #13156.
