### ISSUE TITLE
WebGLTileLayer setOpacity() method not working

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13117]
**Describe the bug**
The merging of #12965 introduced an issue with WebGL layer opacity - as a minimum the `setOpacity()` method is not working as expected.

**To Reproduce**
Compare the action of the Imagery Opacity slider in
https://codesandbox.io/s/disable-image-smoothing-webg-float32-forked-eo9cm (6.9.1-dev.1636909254707)
with
https://codesandbox.io/s/disable-image-smoothing-webg-float32-forked-gmk9r (6.9.1-dev.1636919037674))

**Expected behavior**
Layer opacity should be updateable.

**Comment by tschaub** [comment]
Here is an example that shows `layer.setOpacity()` working with WebGL tile layers: https://codesandbox.io/s/layer-opacity-webgl-mg0sn.  I also confirmed that things work with a WebGL tile layer on top of a Canvas tile layer.

@mike-000 - Can you put together a simpler example that demonstrates the problem?

**Comment by mike-000** [comment]
Yes, the failing example contains numerous patches to demonstrate a different problem.  It seems the patch to the HTMLCanvasElement prototype was not compatible with the #12965 changes.  When I remove that setting opacity works (but without it I cannot verify the pixel values).
