### ISSUE TITLE
html2canvas does not work correctly with rotated view

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13125]
**Describe the bug**
Using `html2canvas` as an alternative to `dom-to-image-more` does not work with a rotated view.

**To Reproduce**
Open https://openlayers.org/en/v6.5.0/examples/print-to-scale.html and https://openlayers.org/en/latest/examples/print-to-scale.html rotate the views and export.  Compare the results.

**Expected behavior**
An export including the specified controls, and the rotated canvas correctly positioned.

**Comment by ahocevar** [comment]
Looks like this is a html2canvas bug, and it is browser specific. In Safari, I get the expected result. In Chrome, I do have all controls on the page, but the rotated map is shifted.

**Comment by mike-000** [comment]
It will work as expected in Chrome using WebGL for the tile layer (with `preserveDrawingBuffer` set) although currently a layer cannot be added to the map before the source is set.
