### ISSUE TITLE
WebGLTile color expression with array

### ISSUE THREAD

**Issue by All4Gis** [openlayers/openlayers#13122]
Hi, first of all this is not a bug, it's a question.

I'm migrating rastersource to webgl and this case the operation I was doing before is:

```
const RasterSource = source => {
  return new OlRasterSource({
    sources: [source],
    // On every render of the layer the code inside operation will be executed
    operation: function(pixels, data) {
      var pixel = pixels[0];
      if (data.rasterColor || data.palette) {
        var val = getPixelValue(pixel);
        if (val !== 0) {
          if (data.palette) {
            pixel = gradientFunction(pixel[0], data.palette);
          } else {
            pixel = whiteToColorLinearGradient(pixel, data.rasterColor);
          }
        }
      }

      return pixel;
    },
    // LOOK: getRasterSourceLib is a mandatory way of import the functions that will be used inside operation due a compiler issue
    // lib: object with the functions that the worker will receive
    lib: getRasterSourceLib([
      getPixelValue,
      whiteToColorLinearGradient,
      gradientFunction
    ])
  });
};


function gradientFunction(pixel, palette) {
  const color = palette[pixel];
  return [color[0], color[1], color[2], color[3]];
}
```

I have an object that, depending on the pixel, assigns a colour to it. The palette object is something like:

0: (4) [0, 0, 0, 0]
1: (4) [255, 253, 230, 235]
2: (4) [255, 253, 230, 235]
3: (4) [255, 253, 230, 235]
4: (4) [255, 253, 230, 235]
5: (4) [255, 253, 230, 235]
6: (4) [255, 253, 230, 235]
7: (4) [255, 253, 230, 235]
.....

My question is how to set an array as a variable:

I have tried this, but it doesn't work.

```
const variables = {
    red: palette[("band", 1)][0],
    green: palette[("band", 1)][1],
    blue: palette[("band", 1)][2],
    alpha: 1,  };

  let layer = new TileLayer({
    source: source,
    style: {
      color: [
        "color",
         ["var", "red"],
         ["var", "green"],
         ["var", "blue"],
         ["var", "alpha"]
      ],
      variables: variables
    }
  });
```
Another attempt is to create the object as a string (a very crazy method).but it doesn't work 

```
  let caseClausule = `'case',`;
  for (const property in palette) {
    caseClausule += `['==', ['band', 1], ${property}],[${palette[property]}],`;
  }
  caseClausule += `[0,0,0,0]`;

  const variables = {
    caseClausule: caseClausule
  };

  let layer = new TileLayer({
    source: source,
    style: {
      color: [`${caseClausule}`],
      variables: variables
    }
  });
```
And with this       `color: ["var", "caseClausule"],`I receive the following message

```
Error: Fragment shader compliation failed: ERROR: 0:23: '=' : dimension mismatch
ERROR: 0:23: 'assign' : cannot convert from 'uniform highp float' to 'highp 4-component vector of float'
```

Any help, how can I use an array and get some index, for example, in the colour expression instead of single value variables?is it possible?

thanks

**Comment by mike-000** [comment]
This is working for me

```
  const palette = {
    0: [0, 0, 0, 0],
    1: [255, 253, 230, 235],
    2: [255, 253, 230, 235],
    3: [255, 253, 230, 235],
    4: [255, 253, 230, 235],
    5: [255, 253, 230, 235],
    6: [255, 253, 230, 235],
    7: [255, 253, 230, 235],
  };

  let caseClausule = ['case'];
  for (const property in palette) {
    caseClausule.push(
       ['==', ['*', ['band', 1], 255], Number(property)],
       [palette[property][0], palette[property][1], palette[property][2], 1]
    );
  }
  caseClausule.push([0, 0, 0, 0]);

  let layer = new TileLayer({
    source: source,
    style: {
      color: caseClausule
    }
  });
```

**Comment by All4Gis** [comment]
mmm...With this code I receive,
`Error: Fragment shader compliation failed: ERROR: Expression too complex.
`
I don't quite understand why it is necessary to multiply by 255. Can I show by console or debug what value it returns ['band', 1]? 

The problem is that my palette object has 255 entries, so it is a crazy case condition. Maybe an interpolation would also work I guess but I think the error would be the same.

**Comment by mike-000** [comment]
RGBA bands return a value between 0 and 1, but the corresponding RGB color values are between 0 and 255.

**Comment by All4Gis** [comment]
Ah okey understood. 
Anyway I don't think that's the way to go as it's a big array and the condition is like this.

`"'case',['==', ['band', 1], 0],[0,0,0,0],['==', ['band', 1], 1],[255,253,230,235],['==', ['band', 1], 2],[255,253,230,235],['==', ['band', 1], 3],[255,253,230,235],['==', ['band', 1], 4],[255,253,230,235],['==', ['band', 1], 5],[255,253,230,235],['==', ['band', 1], 6],[255,253,230,235],['==', ['band', 1], 7],[255,253,230,235],['==', ['band', 1], 8],[255,253,230,235],['==', ['band', 1], 9],[247,232,38,235],['==', ['band', 1], 10],[247,232,38,235],['==', ['band', 1], 11],[247,232,38,235],['==', ['band', 1], 12],[247,232,38,235],['==', ['band', 1], 13],[247,232,38,235],['==', ['band', 1], 14],[247,232,38,235],['==', ['band', 1], 15],[247,232,38,235],['==', ['band', 1], 16],[247,232,38,235],['==', ['band', 1], 17],[247,232,38,235],['==', ['band', 1], 18],[247,232,38,235],['==', ['band', 1], 19],[247,232,38,235],['==', ['band', 1], 20],[247,232,38,235],['==', ['band', 1], 21],[247,232,38,235],['==', ['band', 1], 22],[247,232,38,235],['==', ['band', 1], 23],[252,215,36,235],['==', ['band', 1], 24],[254,197,39,235],['==', ['band', 1], 25],[254,182,45,235],['==', ['band', 1], 26],[254,182,45,235],['==', ['band', 1], 27],[254,182,45,235],['==', ['band', 1], 28],[254,182,45,235],['==', ['band', 1], 29],[254,182,45,235],['==', ['band', 1], 30],[254,182,45,235],['==', ['band', 1], 31],[254,182,45,235],['==', ['band', 1], 32],[254,182,45,235],['==', ['band', 1], 33],[254,182,45,235],['==', ['band', 1], 34],[254,182,45,235],['==', ['band', 1], 35],[254,182,45,235],['==', ['band', 1], 36],[254,182,45,235],['==', ['band', 1], 37],[254,182,45,235],['==', ['band', 1], 38],[254,182,45,235],['==', ['band', 1], 39],[254,182,45,235],['==', ['band', 1], 40],[254,182,45,235],['==', ['band', 1], 41],[254,182,45,235],['==', ['band', 1], 42],[254,182,45,235],['==', ['band', 1], 43],[254,182,45,235],['==', ['band', 1], 44],[254,182,45,235],['==', ['band', 1], 45],[254,182,45,235],['==', ['band', 1], 46],[254,182,45,235],['==', ['band', 1], 47],[252,167,54,235],['==', ['band', 1], 48],[249,152,63,235],['==', ['band', 1], 49],[245,138,71,235],['==', ['band', 1], 50],[245,138,71,235],['==', ['band', 1], 51],[239,125,80,235],['==', ['band', 1], 52],[239,125,80,235],['==', ['band', 1], 53],[239,125,80,235],['==', ['band', 1], 54],[239,125,80,235],['==', ['band', 1], 55],[239,125,80,235],['==', ['band', 1], 56],[239,125,80,235],['==', ['band', 1], 57],[239,125,80,235],['==', ['band', 1], 58],[239,125,80,235],['==', ['band', 1], 59],[239,125,80,235],['==', ['band', 1], 60],[239,125,80,235],['==', ['band', 1], 61],[239,125,80,235],['==', ['band', 1], 62],[239,125,80,235],['==', ['band', 1], 63],[239,125,80,235],['==', ['band', 1], 64],[239,125,80,235],['==', ['band', 1], 65],[239,125,80,235],['==', ['band', 1], 66],[239,125,80,235],['==', ['band', 1], 67],[239,125,80,235],['==', ['band', 1], 68],[239,125,80,235],['==', ['band', 1], 69],[239,125,80,235],['==', ['band', 1], 70],[239,125,80,235],['==', ['band', 1], 71],[239,125,80,235],['==', ['band', 1], 72],[239,125,80,235],['==', ['band', 1], 73],[232,112,89,235],['==', ['band', 1], 74],[225,100,97,235],['==', ['band', 1], 75],[225,100,97,235],['==', ['band', 1], 76],[225,100,97,235],['==', ['band', 1], 77],[225,100,97,235],['==', ['band', 1], 78],[225,100,97,235],['==', ['band', 1], 79],[225,100,97,235],['==', ['band', 1], 80],[225,100,97,235],['==', ['band', 1], 81],[225,100,97,235],['==', ['band', 1], 82],[225,100,97,235],['==', ['band', 1], 83],[225,100,97,235],['==', ['band', 1], 84],[225,100,97,235],['==', ['band', 1], 85],[225,100,97,235],['==', ['band', 1], 86],[225,100,97,235],['==', ['band', 1], 87],[225,100,97,235],['==', ['band', 1], 88],[225,100,97,235],['==', ['band', 1], 89],[225,100,97,235],['==', ['band', 1], 90],[225,100,97,235],['==', ['band', 1], 91],[225,100,97,235],['==', ['band', 1], 92],[225,100,97,235],['==', ['band', 1], 93],[225,100,97,235],['==', ['band', 1], 94],[225,100,97,235],['==', ['band', 1], 95],[225,100,97,235],['==', ['band', 1], 96],[225,100,97,235],['==', ['band', 1], 97],[217,88,107,235],['==', ['band', 1], 98],[208,76,115,235],['==', ['band', 1], 99],[208,76,115,235],['==', ['band', 1], 100],[208,76,115,235],['==', ['band', 1], 101],[208,76,115,235],['==', ['band', 1], 102],[208,76,115,235],['==', ['band', 1], 103],[208,76,115,235],['==', ['band', 1], 104],[208,76,115,235],['==', ['band', 1], 105],[208,76,115,235],['==', ['band', 1], 106],[208,76,115,235],['==', ['band', 1], 107],[208,76,115,235],['==', ['band', 1], 108],[208,76,115,235],['==', ['band', 1], 109],[208,76,115,235],['==', ['band', 1], 110],[208,76,115,235],['==', ['band', 1], 111],[208,76,115,235],['==', ['band', 1], 112],[208,76,115,235],['==', ['band', 1], 113],[208,76,115,235],['==', ['band', 1], 114],[208,76,115,235],['==', ['band', 1], 115],[208,76,115,235],['==', ['band', 1], 116],[208,76,115,235],['==', ['band', 1], 117],[208,76,115,235],['==', ['band', 1], 118],[208,76,115,235],['==', ['band', 1], 119],[208,76,115,235],['==', ['band', 1], 120],[208,76,115,235],['==', ['band', 1], 121],[208,76,115,235],['==', ['band', 1], 122],[208,76,115,235],['==', ['band', 1], 123],[208,76,115,235],['==', ['band', 1], 124],[208,76,115,235],['==', ['band', 1], 125],[208,76,115,235],['==', ['band', 1], 126],[208,76,115,235],['==', ['band', 1], 127],[208,76,115,235],['==', ['band', 1], 128],[208,76,115,235],['==', ['band', 1], 129],[208,76,115,235],['==', ['band', 1], 130],[208,76,115,235],['==', ['band', 1], 131],[208,76,115,235],['==', ['band', 1], 132],[208,76,115,235],['==', ['band', 1], 133],[208,76,115,235],['==', ['band', 1], 134],[208,76,115,235],['==', ['band', 1], 135],[208,76,115,235],['==', ['band', 1], 136],[208,76,115,235],['==', ['band', 1], 137],[208,76,115,235],['==', ['band', 1], 138],[208,76,115,235],['==', ['band', 1], 139],[208,76,115,235],['==', ['band', 1], 140],[208,76,115,235],['==', ['band', 1], 141],[208,76,115,235],['==', ['band', 1], 142],[208,76,115,235],['==', ['band', 1], 143],[208,76,115,235],['==', ['band', 1], 144],[208,76,115,235],['==', ['band', 1], 145],[208,76,115,235],['==', ['band', 1], 146],[208,76,115,235],['==', ['band', 1], 147],[208,76,115,235],['==', ['band', 1], 148],[208,76,115,235],['==', ['band', 1], 149],[208,76,115,235],['==', ['band', 1], 150],[208,76,115,235],['==', ['band', 1], 151],[208,76,115,235],['==', ['band', 1], 152],[208,76,115,235],['==', ['band', 1], 153],[208,76,115,235],['==', ['band', 1], 154],[208,76,115,235],['==', ['band', 1], 155],[208,76,115,235],['==', ['band', 1], 156],[199,65,125,235],['==', ['band', 1], 157],[188,53,134,235],['==', ['band', 1], 158],[188,53,134,235],['==', ['band', 1], 159],[188,53,134,235],['==', ['band', 1], 160],[188,53,134,235],['==', ['band', 1], 161],[188,53,134,235],['==', ['band', 1], 162],[188,53,134,235],['==', ['band', 1], 163],[188,53,134,235],['==', ['band', 1], 164],[188,53,134,235],['==', ['band', 1], 165],[177,42,144,235],['==', ['band', 1], 166],[177,42,144,235],['==', ['band', 1], 167],[177,42,144,235],['==', ['band', 1], 168],[177,42,144,235],['==', ['band', 1], 169],[177,42,144,235],['==', ['band', 1], 170],[177,42,144,235],['==', ['band', 1], 171],[177,42,144,235],['==', ['band', 1], 172],[177,42,144,235],['==', ['band', 1], 173],[177,42,144,235],['==', ['band', 1], 174],[177,42,144,235],['==', ['band', 1], 175],[177,42,144,235],['==', ['band', 1], 176],[177,42,144,235],['==', ['band', 1], 177],[177,42,144,235],['==', ['band', 1], 178],[177,42,144,235],['==', ['band', 1], 179],[177,42,144,235],['==', ['band', 1], 180],[164,30,153,235],['==', ['band', 1], 181],[151,18,160,235],['==', ['band', 1], 182],[151,18,160,235],['==', ['band', 1], 183],[151,18,160,235],['==', ['band', 1], 184],[151,18,160,235],['==', ['band', 1], 185],[151,18,160,235],['==', ['band', 1], 186],[151,18,160,235],['==', ['band', 1], 187],[151,18,160,235],['==', ['band', 1], 188],[151,18,160,235],['==', ['band', 1], 189],[151,18,160,235],['==', ['band', 1], 190],[151,18,160,235],['==', ['band', 1], 191],[151,18,160,235],['==', ['band', 1], 192],[151,18,160,235],['==', ['band', 1], 193],[151,18,160,235],['==', ['band', 1], 194],[151,18,160,235],['==', ['band', 1], 195],[151,18,160,235],['==', ['band', 1], 196],[151,18,160,235],['==', ['band', 1], 197],[151,18,160,235],['==', ['band', 1], 198],[151,18,160,235],['==', ['band', 1], 199],[151,18,160,235],['==', ['band', 1], 200],[151,18,160,235],['==', ['band', 1], 201],[151,18,160,235],['==', ['band', 1], 202],[151,18,160,235],['==', ['band', 1], 203],[151,18,160,235],['==', ['band', 1], 204],[137,8,166,235],['==', ['band', 1], 205],[122,1,168,235],['==', ['band', 1], 206],[107,0,168,235],['==', ['band', 1], 207],[90,0,165,235],['==', ['band', 1], 208],[90,0,165,235],['==', ['band', 1], 209],[90,0,165,235],['==', ['band', 1], 210],[90,0,165,235],['==', ['band', 1], 211],[90,0,165,235],['==', ['band', 1], 212],[90,0,165,235],['==', ['band', 1], 213],[90,0,165,235],['==', ['band', 1], 214],[90,0,165,235],['==', ['band', 1], 215],[90,0,165,235],['==', ['band', 1], 216],[90,0,165,235],['==', ['band', 1], 217],[90,0,165,235],['==', ['band', 1], 218],[90,0,165,235],['==', ['band', 1], 219],[90,0,165,235],['==', ['band', 1], 220],[90,0,165,235],['==', ['band', 1], 221],[90,0,165,235],['==', ['band', 1], 222],[90,0,165,235],['==', ['band', 1], 223],[90,0,165,235],['==', ['band', 1], 224],[90,0,165,235],['==', ['band', 1], 225],[90,0,165,235],['==', ['band', 1], 226],[90,0,165,235],['==', ['band', 1], 227],[90,0,165,235],['==', ['band', 1], 228],[90,0,165,235],['==', ['band', 1], 229],[74,2,160,235],['==', ['band', 1], 230],[56,4,154,235],['==', ['band', 1], 231],[38,5,145,235],['==', ['band', 1], 232],[38,5,145,235],['==', ['band', 1], 233],[38,5,145,235],['==', ['band', 1], 234],[38,5,145,235],['==', ['band', 1], 235],[38,5,145,235],['==', ['band', 1], 236],[38,5,145,235],['==', ['band', 1], 237],[38,5,145,235],['==', ['band', 1], 238],[38,5,145,235],['==', ['band', 1], 239],[38,5,145,235],['==', ['band', 1], 240],[38,5,145,235],['==', ['band', 1], 241],[38,5,145,235],['==', ['band', 1], 242],[38,5,145,235],['==', ['band', 1], 243],[38,5,145,235],['==', ['band', 1], 244],[38,5,145,235],['==', ['band', 1], 245],[38,5,145,235],['==', ['band', 1], 246],[38,5,145,235],['==', ['band', 1], 247],[38,5,145,235],['==', ['band', 1], 248],[38,5,145,235],['==', ['band', 1], 249],[38,5,145,235],['==', ['band', 1], 250],[38,5,145,235],['==', ['band', 1], 251],[38,5,145,235],['==', ['band', 1], 252],[38,5,145,235],['==', ['band', 1], 253],[38,5,145,235],['==', ['band', 1], 254],[38,5,145,235],['==', ['band', 1], 255],[13,8,135,235],[0,0,0,0]"`


And webgl cries with this condition.hehe

**Comment by ahocevar** [comment]
I think you'll want to use the `between` operator instead of `==`. See https://openlayers.org/en/latest/apidoc/module-ol_style_expressions.html#~ExpressionValue. Something like
```js
"'case',
['==', ['band', 1], 0],[0,0,0,0],
['between', ['band', 1], 1, 8, [255,253,230,235],
['between', ['band', 1], 9, 22, [247,232,38,235],
// and so on
```

**Comment by mike-000** [comment]
`between` is needed - but only because of rounding issues.  There is a limit on the number of conditions in a `case` (at least 128 but less than 256) but you can get around that using nested cases:

```
const caseClausules = [['case'], ['case']];
const fallback = [0, 0, 0, 0];

for (const property in palette) {
  const number = Number(property);
  let caseClausule = caseClausules[Math.floor(number / 128)];
  caseClausule.push(
    ['between', ['*', ['band', 1], 255], number - 0.5, number + 0.5],
    [palette[property][0], palette[property][1], palette[property][2], 1]
  );
}
caseClausules[0].push(fallback);
caseClausules[1].push(fallback);

const caseClausule = [
  'case',
  ['<', ['*', ['band', 1], 255], 127.5],
  caseClausules[0],
  ['>', ['*', ['band', 1], 255], 127.5],
  caseClausules[1],
  fallback
];
```

**Comment by All4Gis** [comment]
OMG, crazy speed @mike-000 . I haven't even had time to try it out, your example works perfectly.thanks

**Comment by All4Gis** [comment]
The final code to use the alpha value as well

```
const newWebGLTileLayerPalette = (source, palette) => {
  const caseClausules = [["case"], ["case"]];
  const fallback = [0, 0, 0, 0];

  for (const property in palette) {
    const number = Number(property);
    let caseClausule = caseClausules[Math.floor(number / 128)];
    caseClausule.push(
      ["between", ["*", ["band", 1], 255], number - 0.5, number + 0.5],
      [
        palette[property][0],
        palette[property][1],
        palette[property][2],
        palette[property][3] / 255
      ]
    );
  }
  caseClausules[0].push(fallback);
  caseClausules[1].push(fallback);

  const caseClausule = [
    "case",
    ["<", ["*", ["band", 1], 255], 127.5],
    caseClausules[0],
    [">", ["*", ["band", 1], 255], 127.5],
    caseClausules[1],
    fallback
  ];

  let layer = new TileLayer({
    source: source,
    style: {
      color: caseClausule
    }
  });
  return layer;
};
```

**Comment by tschaub** [comment]
If you are trying to represent a color lookup, I think the `interpolate` operator is currently the easiest way to write this:
```js
      style: {
        color: [
          "interpolate",
          ["linear"],
          ["*", ["band", 1], 255],
          0, [255, 255, 204],
          1, [255, 237, 160],
          2, [254, 217, 118],
          3, [254, 178, 76],
          4, [253, 141, 60],
          5, [252, 78, 42],
          6, [227, 26, 28],
          7, [189, 0, 38],
          8, [128, 0, 38]
        ]
      }
```

Here is an example: https://codesandbox.io/s/color-palette-irihw

**Comment by mike-000** [comment]
256 unique entries in an interpolate also throws Expression too complex, so it would still need to be nested inside two cases.

**Comment by tschaub** [comment]
I didn't see 256 unique colors.  If there are ranges of values that share the same color, that could also be interpolate:

```js
      style: {
        color: [
          "interpolate",
          ["linear"],
          ["*", ["band", 1], 255],
          0, [255, 253, 230],
          8, [255, 253, 230],
          9, [247, 232, 38],
          22, [247, 232, 38],
          // etc
        ]
      }
```

Not so pretty, but still an option.

**Comment by mike-000** [comment]
If dealing with an imported palette object that would need more programming to set up even if there were sufficient non-unique values for it to work, but two interpolates are slightly simpler to set up than nested cases.

```
const newWebGLTileLayerPalette = (source, palette) => {
  const interpolate = ["interpolate", ["linear"], ["*", ["band", 1], 255]];
  const caseClausules = [interpolate.slice(), interpolate.slice()];

  for (const property in palette) {
    const number = Number(property);
    let caseClausule = caseClausules[Math.floor(number / 128)];
    caseClausule.push(number, [
      palette[property][0],
      palette[property][1],
      palette[property][2],
      palette[property][3] / 255
    ]);
  }

  const caseClausule = [
    "case",
    ["<", ["*", ["band", 1], 255], 127.5],
    caseClausules[0],
    caseClausules[1]
  ];

  let layer = new TileLayer({
    source: source,
    style: {
      color: caseClausule
    }
  });
  return layer;
};
```

**Comment by All4Gis** [comment]
Thank. The result seems to be the same. I will see which option fits better or gives a more accurate result. Thanks again
