### ISSUE TITLE
Zoom/move map. cluster shows different value on vector than i have from WFS

### ISSUE THREAD

**Issue by anderCM** [openlayers/openlayers#13121]
I have some vectors using WFS as source, then when i move/zoom map , vector shows a different value than i have. On first view it shows real value (3), then if i zoom out number increase without limit, no matter if map is at max zoom if i try to zoom in number doesnt change.

const approvedUsersSource = new ol.source.Vector({
    format: new ol.format.GeoJSON(),
    url: function (extent) {
        return (
            'https://url/geoserver/wfs?service=WFS&' +
            'version=1.1.0&request=GetFeature&typename=approvedUser&' +
            'outputFormat=application/json&srsname=EPSG:3857&' +
            'bbox=' +
            extent.join(',') +
            ',EPSG:3857'
        );
    },
    strategy: ol.loadingstrategy.bbox,
});

const approvedUsersCluster = new ol.source.Cluster({
    distance: 50,
    source: approvedUsersSource
});
let styleCacheUser = {};
const approvedUsers = new ol.layer.Vector({
    title: 'Usuarios encuestados',
    source: approvedUsersCluster,
    style: function (feature) {
            let sizeUser = feature.get('features').length;
            let styleUser = styleCacheUser[sizeUser];
            if (!styleUser) {
                styleUser = new ol.style.Style({
                    image: new ol.style.Icon({
                        anchor: [0.5, 0.5],
                        size: [30, 30],
                        offset: [0, 0],
                        scale: 1,
                        src: 'assets/img/approvedUser.png'
                    }),
                    text: new ol.style.Text({
                        text: sizeUser.toString(),
                        fill: new ol.style.Fill({
                            color: '#fff'
                        }),
                        font: "bold 15px sans-serif",
                        /* offsetY: +2.5 */
                    })
                });
                styleCacheUser[sizeUser] = styleUser;
            }
            return styleUser;
    }
});
On first load
![image](https://user-images.githubusercontent.com/77707836/146293581-3686767d-952c-4fbd-bd8a-57ecbc379c9a.png)

max zoom-out
![image](https://user-images.githubusercontent.com/77707836/146293542-e8a38f5f-30f2-486e-960d-7bc83e81257e.png)

zoom in again
![image](https://user-images.githubusercontent.com/77707836/146293645-dd1f9be0-52ee-4488-bd06-77ddeaeebe8b.png)

**Comment by mike-000** [comment]
Do the features have id?.  If not you should not use the bbox strategy as it will not be possible to determine if they have already been loaded, and duplicates will be added.

**Comment by anderCM** [comment]
I dont have features id, so what should i use as strategy insteand of bbox? Tried using default or removing but is needed

**Comment by mike-000** [comment]
If you cannot use the default strategy (`all`) you could ensure no part of an extent is loaded more than once by using a tile strategy with a single zoom level, choosing a zoom level where the extents are small enough for the server to handle

```
const approvedUsersSource = new ol.source.Vector({
  format: new ol.format.GeoJSON(),
  url: function (extent) {
    return (
      'https://url/geoserver/wfs?service=WFS&' +
      'version=1.1.0&request=GetFeature&typename=approvedUser&' +
      'outputFormat=application/json&srsname=EPSG:3857&' +
      'bbox=' +
      extent.join(',') +
      ',EPSG:3857'
    );
  },
  strategy: ol.loadingstrategy.tile(ol.tilegrid.createXYZ({minZoom: 4, maxZoom: 4})),
});
```
