### ISSUE TITLE
How to get latitude and longitude and visual area when the map is repeated and slides in one direction

### ISSUE THREAD

**Issue by weitaoYan6515** [openlayers/openlayers#13148]
How to get latitude and longitude and visual area when the map is repeated and slides in one direction

**Comment by jipexu** [comment]
Hi 
Can you be a little more explicit to have a chance to get an answer and some help ?

**Comment by weitaoYan6515** [comment]
![837b51ef9a652fb2cd59f868dbe6108](https://user-images.githubusercontent.com/45583036/147064694-517ff4c3-0909-4f39-b194-e8c1b8f70c08.png)

**Comment by mike-000** [comment]
`toLonLat` will normalize wrapped coordinates https://codesandbox.io/s/geographic-forked-vswpi

**Comment by jipexu** [comment]
for info #13030 ...

**Comment by ahocevar** [comment]
Same. Use `ol/extent#getBottomLeft()` and `ol/extent#getTopRight()`, and `ol/proj#toLonLat()` on the results.

**Comment by weitaoYan6515** [comment]
Thank you

**Comment by weitaoYan6515** [comment]
When I render the point to the map, the map is looping, but the point does not
