### ISSUE TITLE
Heatmap layer opacity option is ignored

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13145]
**Describe the bug**
Setting the opacity option in `ol/layer/Heatmap` has no effect.

**To Reproduce**
Open the example https://codesandbox.io/s/simple-forked-novjn?file=/main.js used in #13124 where there seemed to be no problem with the heatmap overlying the OSM layer in the shared context.  Add `opacity: 0.1` to the layer options.  It has no effect.  It appears be be unrelated to the `preserveDrawingBuffer` override as removing that and refreshing has no effect.  Then change to the latest dev version - it still no no effect,  But go back to version 6.9.0 and it was working, and the opacity setting does work for a WebGL Points layer in the latest version.

**Expected behavior**
Visually as in  version 6.9.0.

**Comment by jahow** [comment]
Pretty sure this is a side effect of https://github.com/openlayers/openlayers/pull/12965 since now the layer opacity is handled in the webgl shaders.

**Comment by mike-000** [comment]
> Pretty sure this is a side effect of #12965 since now the layer opacity is handled in the webgl shaders.
Yes, unless I have missed something the layer opacity just needs to be included in the custom shader https://codesandbox.io/s/simple-forked-yrj3i?file=/main.js
