### ISSUE TITLE
Expose addFeatureLayerAssociation_ function on Select to the API

### ISSUE THREAD

**Issue by Angusross111** [openlayers/openlayers#13146]
**Is your feature request related to a problem? Please describe.**
Currently when you add a feature programmically to Select:
```
select.getFeatures().push(feature);
```
 you cannot then use 
```
select.getLayer(feature)
```
as the function that links the layer to the feature is private and only gets called when going though the mouse selection interaction.
```
  /**
   * @param {import("../Feature.js").FeatureLike} feature Feature.
   * @param {import("../layer/Layer.js").default} layer Layer.
   * @private
   */
  addFeatureLayerAssociation_(feature, layer) {
    this.featureLayerAssociation_[getUid(feature)] = layer;
  }
```

**Describe the solution you'd like**
Can we expose this function to the API for select, allowing us to link the associated layer to the pushed feature

**Comment by ahocevar** [comment]
We can do better than that. #13149 makes it so even features that are programmatically added to a Select interaction's `features` collection will be registered in the feature-layer association. So no need to expose `addFeatureLayerAssociation_` to the API.

**Comment by Angusross111** [comment]
I appreciate the quick turn around for the fix!
