### ISSUE TITLE
Unable to add vertex at one edge of the polygon

### ISSUE THREAD

**Issue by Abdul007Malik** [openlayers/openlayers#13157]
**A vertex is not coming while hovering over a edge/line of a polygon**
I have added a fiddle showing that if you hover over the polygon lines it will show the vertex to be added on the line, but one of the edge a vertex is not shown nor is a vertex added when clicked

![image](https://user-images.githubusercontent.com/15179681/147403435-5db0e246-9e0c-4e97-9f65-7a07fee1d4a8.png)

**To Reproduce**
https://jsfiddle.net/abdulmalik07/ho1msa4k/32/

**Expected behavior**
It should show the vertex as it is showing in other edges

**Comment by mike-000** [comment]
A polygon ring must be closed (first and last coordinates must be the same) https://jsfiddle.net/3L7tjz6e/
