### ISSUE TITLE
npm start, it can't run normally.

### ISSUE THREAD

**Issue by leizhangc** [openlayers/openlayers#13172]
there is an erro when execute "npm start".

1. npm start
2. then
![企业微信截图_16408557572377](https://user-images.githubusercontent.com/10084250/147738154-2cdcefc9-03a9-4b6e-9dae-6a327348dc8e.png)

**Comment by MoonE** [comment]
What version of NodeJS are you using? Does it work with the latest version?

**Comment by leizhangc** [comment]
@MoonE

**Comment by leizhangc** [comment]
@MoonE 
my nodejs version is v12.22.3 and it can work perfectly with ol6.1.1

**Comment by leizhangc** [comment]
@MoonE thank you.

**Comment by MoonE** [comment]
Thanks very much for your investigation, @leizhangc. It is fixed in the main branch.
