### ISSUE TITLE
TilematrixSets must match to render maps performant

### ISSUE THREAD

**Issue by MapAxel** [openlayers/openlayers#13187]
As we found out, Openlayers renders tiled vector layers faster if the TileMatrixSet of the view (or the projection of the view) and the vektorlayer are identical. 

So in Openlayers 6.5.0 we overloaded 
`ol.source.VectorTile.prototype.getTileGridForProjection` 
with
```js
= function(projection) {
  const code = projection.getCode();
  let tileGrid = this.tileGrids_[code];
  if (!tileGrid) {
      if (!projection.getDefaultTileGrid()) {
          const sourceTileGrid = this.tileGrid;
          tileGrid = ol.tilegrid.createForProjection(
          projection,
          undefined,
          sourceTileGrid
              ?  sourceTileGrid.getTileSize(sourceTileGrid.getMinZoom())
              : undefined
          );
          this.tileGrids_[code] = tileGrid;
      } else {
          tileGrid = projection.getDefaultTileGrid();

      }
      this.tileGrids_[code] = tileGrid;
  }
  return tileGrid;
}
```
With Openlayers 6.9.0, however, the corresponding functions and variables became private.
Is there another way to replace the projections tileMatrixSet? 
Since the poor performance makes our app unusable, especially under MS Windows, I would like to know how Openlayers can be made acceptably fast again.

**Comment by ahocevar** [comment]
I assume you're talking about the private variables `tileGrids_`? You can use `getTileGridForProjection()` and `setTileGridForProjection()`.

**Comment by MapAxel** [comment]
Yes, tileGrids_ e.g. is private now. 
As setTileGridForProjection is not a public method of ol.source.VectorTile, I cannot use it. 
In addition, of course, I cannot overload/create setTileGridForProjection either on my own.

**Comment by ahocevar** [comment]
I think it would be better to solve this by being smarter about creating a render tile grid from the source tile grid. Could you maybe provide an example of your source tile grid, and the tile grid you previously used in the override?

**Comment by mike-000** [comment]
I have a similar problem with custom grids and custom projections.  An EPSG:27700 tile grid is specified as

```
extent: [-238375, 0, 900000, 1376256]
origin: [-238375, 1376256]
maxResolution: 3584
tileSize: 512
```

The extent is not the standard extent for EPSG:27700 nor does it define the limits of a standard XYZ grid, merely the limit where tiles are served.  At level 0 the grid is two tiles wide, the second partly overflows the grid.

In 6.5.0 if I use a more drastic version of the above patch

```
  ol.source.VectorTile.prototype.getTileGridForProjection = function(projection) {
    const code = projection.getCode();
    let tileGrid = this.tileGrids_[code];
    if (!tileGrid) {
      // A tile grid that matches the tile size of the source tile grid is more
      // likely to have 1:1 relationships between source tiles and rendered tiles.
      const sourceTileGrid = this.tileGrid;
      this.tileGrids_[code] = sourceTileGrid;
    }
    return tileGrid;
  }
```

I get better results than using the one based on the projection extent.  But that might not work well for overzooming or if the tilegrid does not use a zoom factor of 2.

The same can be achieved without a patch by defining the projection extent so a standard XYZ grid will exactly match the source tilegrid (at least at zoom level 0)

```
let multiplier = 1;
while (resolutions[0] * tileSize * multiplier < extent[2] - origin[0]) {
  multiplier = multiplier * 2;
}
projection.setExtent([origin[0], extent[1], origin[0] + resolutions[0] * tileSize * multiplier, origin[1]]);
```

That is what I think should be set as the TileGridForProjection, but without having to set a meaningless projection extent to achieve it.

**Comment by MapAxel** [comment]
My TileGrid looks like e.g. like this: 
aTileGrid: t
extent_: null
fullTileRanges_: null
maxZoom: 8
minZoom: 0
origin_: (2) [4549000, 5943000]
origins_: null
resolutions_: Array(9)
	0: 23.364485981308412
	1: 11.682242990654206
	2: 5.847953216374269
	3: 2.336448598130841
	4: 1.1668611435239207
	5: 0.5847953216374269
	6: 0.23337222870478413
	7: 0.11682242990654206
	8: 0.058343057176196034
length: 9
[[Prototype]]: Array(0)
tileSize_: null
tileSizes_: Array(9)
	0: (2) [214, 214]
	1: (2) [428, 428]
	2: (2) [171, 171]
	3: (2) [428, 428]
	4: (2) [857, 857]
	5: (2) [342, 342]
	6: (2) [857, 857]
	7: (2) [428, 428]
	8: (2) [857, 857]
length: 9
[[Prototype]]: Array(0)
tmpSize_: (2) [0, 0]
zoomFactor_: undefined
[[Prototype]]: Object

Could you add "setTileGridForProjection" to the Vectortile-Source?
So this would match to the other Tile- Sources.

**Comment by ahocevar** [comment]
I don't think adding a method to the API for solving a not obviously related problem is the way forward. Instead, I'd like to improve the way we generate a render tile grid. In general, this is only about adding enough resolutions for zoom levels that are higher than the highest source zoom level. This could be achieved by taking the tile size and resolution from the highest souce tile grid zoom, and keep adding resolutions until the default maxResolution of the view is reached.

**Comment by ahocevar** [comment]
No I did not. If someone can provide a working example with a publicly available tile set that shows the problem, I can take a look and see how my suggested approach could be implemented.

**Comment by mike-000** [comment]
https://codesandbox.io/s/print-to-scale-forked-i7ur0n?file=/main.js

The tile edge artefacts might be unavoidable but the vertical line of background color should not be there.
