### ISSUE TITLE
Circular dependency in TS between `Layer` and `LayerRenderer` is solved by using `any`

### ISSUE THREAD

**Issue by mmomtchev** [openlayers/openlayers#13188]
**Is your feature request related to a problem? Please describe.**
The current implementation renders using OpenLayers impossible in an `any`-free TypeScript project

**Describe the solution you'd like**
There should be a base class - maybe `BaseLayer` - that should be used for this

Ie, the current base vector type is
`BaseVector<SourceVector<Geometry>, LayerRenderer<any>>`

it probably should be
`BaseVector<SourceVector<Geometry>, LayerRenderer<BaseLayer>>`

because it can't be
`BaseVector<SourceVector<Geometry>, LayerRenderer<BaseVector>>`
which is a circular dependency

**Comment by ahocevar** [comment]
@mmomtchev #13190 should fix this.
