### ISSUE TITLE
Load GeoTiff from Blob

### ISSUE THREAD

**Issue by m-mohr** [openlayers/openlayers#13189]
**Is your feature request related to a problem? Please describe.**
I'd like to show a GeoTiff that I only have available Blob (i.e. a dynamically generated GeoTiff that is returned as a result of a HTTP POST request). I see that fromBlob is available in geotiff.js so I'm wondering whether it could also be made available here.

**Describe the solution you'd like**
Instead of passing `url` to the GeoTiff source, I'd like to pass a Blob, e.g. in a new parameter called `blob`, and display it on a Map.

**Comment by marcjansen** [comment]
I would love to have this in the library, but would like to hear other peoples opinion. I am not so sure how tight we are coupling geotiff.js and OpenLayers (not that this was introduced here, just a random observation)

An example and a test would be nice.

**Comment by m-mohr** [comment]
I've created a draft PR with more details and an example for now: https://github.com/openlayers/openlayers/pull/13191

**Comment by ahocevar** [comment]
Is there a reason for not simply configuring the GeoTIFF source with `url: URL.createObjectUrl(blob)`?

**Comment by m-mohr** [comment]
@ahocevar I must admit I directly found fromBlob in the geotiff.js source and didn't even think about the object URLs.
I've tested them and it also works for me, but I can't really judge whether there are serious pros and cons (e.g. for larger blobs regarding memory management). What I've seen in the dev console is that for `URL.createObjectUrl(blob)` multiple "requests" appear in the network pane, but only one for the PR'ed solution.  Also, MDN seems to indicate that URL.createObjectUrl was later implemented in Browsers than the FileReader that is used by geotiff.js.

Other than that, OpenLayers should probably give an example or improve docs a bit as this potential solution is not very obvious, I'd say.

**Comment by m-mohr** [comment]
Another difference I found is that createObjectUrl seems to be synchronous and memory needs to be freed with revokeObjectURL while FileReader is asynchronous.

**Comment by mike-000** [comment]
> Also, MDN seems to indicate that URL.createObjectUrl was implemented in Browsers later than the FileReader that is used by geotiff.js.

I don't think that is significant.  For example, GeoTIFF needs a minimum of Chrome 45 for the workers to run.  `FileReader` and `URL.createObjectUrl` were both supported long before that.

**Comment by yonda-yonda** [comment]
I'm looking forward to this feature.
Glad to see the discussion is active again.

**Comment by ahocevar** [comment]
@yonda-yonda If you agree with @mike-000, then the solution is already available. Simply configure your GeoTIFF source's sources with `url: URL.createObjectUrl(blob)`.

**Comment by yonda-yonda** [comment]
@ahocevar sorry, I didn't understand English properly...
I wanted to skip thinking about when to revokeObjectURL.
But Surely you are right, `URL.createObjectUrl(blob)` is enough.

**Comment by m-mohr** [comment]
I agree, it works fine. :-)
