### ISSUE TITLE
Curve geometry types

### ISSUE THREAD

**Issue by sweco-nlahoo** [openlayers/openlayers#13193]
**Is your feature request related to a problem? Please describe.**
We've began developing a webapplication in which we're looking to not only visualize but ultimately also interactively edit our stored geometries. We're not trying to reinvent the wheel and it seemed that OpenLayers was a good fit for this purpose. It did turnout though that there's no support for geometries that contain or solely consist of arcs.

**Describe the solution you'd like**
A solution that is often brought up for this problem is to stroke any arc before adding it to any OpenLayers map. However we believe editing the arc interactively would than become troublesome. Also, we would ultimately need to convert this stroked arc back to an actual arc. In short, this seems like a far from ideal solution to us.

Therefore we've began digging and attempting to extend the list of geometry types in OpenLayers. In a first attempt we've focused on adding a CircularString geometry type (as in WKT/WKB) and being able to visualize it. So far it seems that we're doing alright. Other more complex types like a CurvePolygon are on our list.

Anyway, we're willing to build support for these geometry types ourselves. What we like to know is whether or not you would be interested in this functionality as well? If not, we might need to change our strategy a bit. If yes, we would like to contribute. In return we'd probably need a bit of guidance along the way every now and then as we're no OpenLayers or Javascript experts.

Perphaps (or hopefully in fact) you've become interested in what we're attempting to do. What we've done so far you can find [here](https://github.com/Sweco-NL/openlayers/tree/feature/circular-string-draw-support).

**Comment by nboisteault** [comment]
Hi @sweco-nlahoo. Adding WKT `CIRCULARSTRING` to OpenLayers would be a good addition.
Could you open a PR with the work you made on this subject?

**Comment by sweco-nlahoo** [comment]
@nboisteault we were actually just talking about opening a PR one of these days. My colleague has been busy these days fine-tuning our work, adding missing pieces, etc. We'll definitely come back to you on this in the upcoming weeks.
