### ISSUE TITLE
Reprojection for WebGlTile layer

### ISSUE THREAD

**Issue by m-mohr** [openlayers/openlayers#13197]
*I'm not sure I'm on the right track here and whether this is a bug or a feature or just my lack of knowledge:*

I'm trying to show a UTM COG on an EPSG:3857 (or 4326) map, but I can't get it working. Nothing shows up for the COG, but OSM and fitting the view to the COG extent works. I assume it doesn't support automatic reprojection or is there a way to do that? A potential use case could be showing two COGs from different UTM zones on a map.

Here's a repro based on the COG example:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Cloud Optimized GeoTIFF (COG)</title>    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.10.0/css/ol.css" type="text/css">
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.10.0/build/ol.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.7.5/proj4.js"></script>
  </head>
  <body>
    <div id="map" style="height: 400px; width: 100%; border: 1px solid black"></div>
    <script>
    // Add CRS definition for COG
    proj4.defs("EPSG:32636","+proj=utm +zone=36 +datum=WGS84 +units=m +no_defs");
    ol.proj.proj4.register(proj4);
    let cogProj = ol.proj.get("EPSG:32636");
  
    // COG source
    const source = new ol.source.GeoTIFF({
      sources: [
        {
          url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/2020/S2A_36QWD_20200701_0_L2A/TCI.tif',
        }
      ],
//    projection: cogProj
    });
    
    // Create map
    const map = new ol.Map({
      target: 'map',
      layers: [
        new ol.layer.Tile({
          source: new ol.source.OSM()
        }),
        new ol.layer.WebGLTile({
          source: source
        })
      ],
      view: new ol.View({
        projection: "EPSG:4326" // CRS for map
      })
    });
    
    // Fit to bounds of COG
    source.getView().then(view => {
      // Fit to COG extent
      let fromLonLat = ol.proj.getTransform(view.projection, map.getView().getProjection());
      let extent = ol.extent.applyTransform(view.extent, fromLonLat);
      map.getView().fit(extent);
    });
    </script>
  </body>
</html>
```

**Comment by mike-000** [comment]
Reprojection currently only works for RGBA image tiles.  Where there are two conflicting interpolation requirements it is possible to reproject image tiles (e.g. without interpolation) and use the reprojected canvas tiles that process produces as the source for a non-interpolated WebGL data source https://codesandbox.io/s/disable-image-smoothing-forked-ru97e?file=/main.js  I presume the opposite might also be possible, convert the data tiles from a GeoTIFF source to RGBA images and use those in an image tile source which can be reprojected.  An new API method for tile sources such as getTileImage would be nicer than using the non-API methods in that example.

**Comment by mike-000** [comment]
Yes it is possible.  Here is a very basic (no tile load error handling, etc.) reprojection to EPSG:3857  https://jsbin.com/loxohux/edit?html,js,output (GeoTIFF is not working in CodeSandbox)

**Comment by m-mohr** [comment]
Thanks a lot! I'm playing around with it right now, but for other (non-public) examples, I get weird behavior (holes, wrong colors) so need to investigate why that happens.

**Comment by m-mohr** [comment]
So with https://openeo.vito.be/openeo/1.0/jobs/fbe109fb-01ca-449c-9d48-279c93d27652/results/bW0%3D/1c2ad7dce3b43938c86ab9a9dff9639f/openEO.tif?expires=1642516600 it shows only half of the tile and the tile content seems incorrectly scaled. The number of pixels I get for the tile is exactly half the number of tiles the canvas asks for. Needs further investigation...

**Comment by mike-000** [comment]
I agree, and I have created a `ol/source/DataTileImage` which take a DataTile or GeoTIFF source and returns canvas tiles, but the example is not ready yet.  My first example assumed 4 band RGBA with default UnpackAlignment. To convert other band counts and alignments to RGBA canvas I am using:

```
function dataToCanvas(data, size) {
  if (data && !(data instanceof Float32Array)) {
    const width = size[0];
    const height = size[1];
    const bytesPerRow = data.byteLength / height;
    const bandCount = Math.floor(bytesPerRow / width);

    if (bandCount <= 4) {
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const context = canvas.getContext('2d');
      const imgData = context.getImageData(0, 0, width, height);
      const pixels = imgData.data;

      let pixelIndex = 0;
      let rowOffset = 0;
      const colCount = width * bandCount;
      for (let rowIndex = 0; rowIndex < height; ++rowIndex) {
        for (let colIndex = 0; colIndex < colCount; colIndex += bandCount) {
          const dataIndex = rowOffset + colIndex;
          pixels[pixelIndex++] = data[dataIndex];
          pixels[pixelIndex++] = data[dataIndex + (bandCount < 3 ? 0 : 1)];
          pixels[pixelIndex++] = data[dataIndex + (bandCount < 3 ? 0 : 2)];
          pixels[pixelIndex++] =
            bandCount % 2 == 1
            ? 255
            : data[dataIndex + (bandCount < 3 ? 1 : 3)];
        }
        rowOffset += bytesPerRow;
      }
      context.putImageData(imgData, 0, 0);
      return canvas;
    }
  }
}
```

**Comment by mike-000** [comment]
Here is my `ol/source/DataTileImage` approach https://jsbin.com/hesodep/edit?html,js,output  The `imageSource` could be used directly, but I have also added a `getTileImage` method for all image tile sources so reprojected tiles can be used in other sources or with different interpolation settings, or in the case of your 2 band source, converting back from RGBA to 2 band.  For data tiles interpolation of RGBA bands during reprojection should be avoided, and reprojection quality could be improved by setting a suitable TileGridForProjection to avoid over or under zooming when creating the reprojected tiles.

**Comment by mike-000** [comment]
Reprojection has been done in canvas since OpenLayers 3, and there would little to be gained by redoing it in WebGL plus canvas reprojection of `GeoTIFF` could be used with `ol/layer/Tile` on systems without WebGL..  `DataTileImage` could be like a normal source and not need any extra application code to handle the asynchronous loading as long as any projections needed were predefined and you did not want to recenter the view.

```
const map = new Map({
  target: 'map',
  layers: [
    new WebGLTileLayer({
      source: new DataTileImage({
        source: new GeoTIFF({
          sources: [{ url: './data/example.tif' }]
        }),
        interpolate: false,
        wrapX: true,
      })
    })
  ],
  view: new View({
    center: [0, 0],
    zoom: 0,
  })
});
```

**Comment by tschaub** [comment]
> there would little to be gained by redoing it in WebGL

I want to make sure nobody else mistakes this for consensus.

It is true that currently, image tile sources are reprojected in Canvas.  Reprojection of data tile sources (including GeoTIFF) is not yet supported.

**Comment by mike-000** [comment]
> It is true that currently, image tile sources are reprojected in Canvas. Reprojection of data tile sources (including GeoTIFF) is not yet supported.

Yes, converting to canvas, reprojecting using the existing code then converting back to data tiles as in my examples is limited to <=4 band Uint8Array data sources.  The 5 band Float32Array example would need a different approach, which could also be used for any data or image source.

**Comment by m-mohr** [comment]
Still a valid feature request that COGs can be reprojected on the fly so that COGs with different CRS can be shown on the same map...
