### ISSUE TITLE
Add `forEachFeatureInExtent` to VectorTile

### ISSUE THREAD

**Issue by EvertEt** [openlayers/openlayers#13194]
**Is your feature request related to a problem? Please describe.**
I think having this function (next to `getFeaturesInExtent`) in both VectorTile and Vector layers would make the dragbox example https://openlayers.org/en/latest/examples/box-selection.html work for both types.
Or is there still a problem since the features don't have a geometry? (For the oblique case?)

If this is indeed the case, I think it would be possible to make `forEachFeatureInExtent` by using `getFeaturesInExtent` (there might be a better way).

**Describe the solution you'd like**
`forEachFeatureInExtent` as a new function of the VectorTile class

**Comment by ahocevar** [comment]
Actually `getFeaturesInExtent()` was the method meant to be available in both `Vector` and `VectorTile` sources. In #13195, I updated the box-selection example to use that method instead, so you can instantly replace the `Vector` source with a `VectorTile` source.

**Comment by mike-000** [comment]
But for Box Selection you need `forEachFeatureIntersectingExtent()` which returns the subset of those features whose _geometries_ actually intersect the extent.  For  `intersectsExtent()` you would need real geometries, so the format would need to be `new MVT({featureClass: Feature})` https://codesandbox.io/s/vector-tile-selection-forked-1xes1?file=/main.js
