### ISSUE TITLE
Interpolate default changed for VectorTile source

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#13218]
**Describe the bug**
VectorTile sources have interpolate disabled by default since v6.10.0

**To Reproduce**
Interpolate enabled: https://openlayers.org/en/v6.9.0/examples/osm-vector-tiles.html
Interpolate disabled: https://openlayers.org/en/v6.10.0/examples/osm-vector-tiles.html

Interpolate is set to false by default here:
https://github.com/openlayers/openlayers/blob/e98607e3448338c08e6e4e11ec963a622c1cef4b/src/ol/source/Source.js#L100
and here:
https://github.com/openlayers/openlayers/blob/e98607e3448338c08e6e4e11ec963a622c1cef4b/src/ol/Tile.js#L132

**Expected behavior**
Vector tiles should be rendered with image smoothing enabled by default.

**Comment by mike-000** [comment]
The setting is only used for raster and data sources: `ol/source/TileImage,` `ol/source/DataTile`, `ol/source/Image` and their subclasses.

**Comment by ahocevar** [comment]
Which does not change the fact that the behavior has changed for VectorTile layers, which use the tile image renderer for rendering lines and polygons in `renderMode: 'hybrid'`.

**Comment by M393** [comment]
You are right, @mike-000. I updated the linked source.

**Comment by M393** [comment]
It seems both interpolate options are used and the one for the Tile does not matter, unless e. g. an icon would be drawn to the Tile. For the VectorTile source it should only draw lines and polygons, so it is irrelevant.

Adding `interpolate: true` to the VectorTile source seems to behave as in v6.9.0 and will draw the rendered tiles with imageSmoothing.
