### ISSUE TITLE
ModifyEvent features are null in modifyend event

### ISSUE THREAD

**Issue by EvertEt** [openlayers/openlayers#13214]
**Describe the bug**
According to the `ModifyEvent` [docs](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Modify.ModifyEvent.html), the  `modifyend` `features` will always be a collection but we've encountered a null value as well crashing our app.

**To Reproduce**
1. Go to https://codesandbox.io/s/modify-features-forked-diu40?file=/main.js
2. Click on an edge and see null is printed instead of an empty collection
3. This would cause code like `evt.features.getArray()` to error.

**Expected behavior**
I would expect an empty collection to be returned.

**Comment by ahocevar** [comment]
Thanks for the bug report, @EvertEt. I would expect no `modifyend` event to be triggered at all in this case. That should have been fixed with #12408 already, but missed one place for `modifyend`. #13219 finally fixes that.
