### ISSUE TITLE
MapboxVector layers zIndex doesn't affect labels/text

### ISSUE THREAD

**Issue by joshplaetzler** [openlayers/openlayers#13235]
**Describe the bug**
When adding vector layer on top of a MapboxVector layer the labels/text of the MapboxVector layer are always on top of the vector layer no mater the zIndex.  This seems to be the case in V6.8.0 and up and is not the case in V6.7.0.

**To Reproduce**
example of this can be created here.  Just add an API key and then draw over the labels and you will see that the drawing ends up under the label even though its on top of everything else. 
https://codesandbox.io/s/draw-features-forked-jf2u2?file=/main.js

**Expected behavior**
Setting the zIndex of a Vector Layer greater than that set for a MapboxVector layer would put the items in the Vector Layer over all items in the MapboxVector including labels/text.

**Comment by ahocevar** [comment]
This standard behavior can be turned off by giving the `MapboxVector` and `Vector` layer a different `className`. Usually it is enough to change only one. I'd recommend adding the following to the options you create the `MapboxVector` layer with:
```js
className: 'mapbox'
```

**Comment by mike-000** [comment]
See https://github.com/openlayers/openlayers/issues/10096#issuecomment-539011271  It is still not mentioned in the two most relevant places in the docs.

**Comment by ahocevar** [comment]
@mike-000 It sounds like you have an idea how this could be properly documented. Would you be able to create a pull request? Thanks in advance!

**Comment by joshplaetzler** [comment]
Thank you @ahocevar That did it.
