### ISSUE TITLE
Generic type 'Layer<SourceType, RendererType>' requires 2 type argument(s).

### ISSUE THREAD

**Issue by jmacura** [openlayers/openlayers#13230]
**Describe the bug**
After upgrading [our lib](https://github.com/hslayers/hslayers-ng) to use ol@6.10.0 or ol@6.11.0, the build fails with the above-mentioned errors.
```
Error: projects/hslayers/src/components/utils/layer-utils.service.ts:408:27 - error TS2314: Generic type 'Layer<SourceType, RendererType>' requires 2 type argument(s).

408   isLayerClustered(layer: Layer<Source>): boolean {
```

etc.

Our lib is based on Angular (i.e. TypeScript). 

There is a question from my side, rather then a direct bug report, whether there was some undocumented breaking change happening between versions 6.9 and 6.10?

**To Reproduce**
1. Use openlayers in a TS application
2. Use `Layer<Source>` as a type
3. Compile the app and see error

**Expected behavior**
No breaking changes when upgrading between minor-releases.

**Comment by ahocevar** [comment]
Apologies for this. Since this change is not a breaking change for JavaScript users, we did not increase the major version. Also see "API change policy" on https://openlayers.org/en/latest/apidoc/.

This change was made for avoiding type casts in the library, and we had not considered the implications for TypeScript users. Ideally, this change would not have been user facing.

**Comment by jmacura** [comment]
OK, that is unpleasant, but understandable. Thank you for clarifying the API change policy to me.

**Comment by jmacura** [comment]
Dear OL team,

adding to this issue. Could you guide us, TypeScript users, how to deal with the circular generics type dependency as described in this comment https://github.com/openlayers/openlayers/commit/6f80ba93c8924d1f6a38dc2d13d41f2110b779a3#r62862451 ?

I was searching in the API docs for a suitable `Renderer` type to put inside the Layer<SourceType, RendererType> definition, but some classes there seem to be not part of the public API. E.g. [`CanvasVectorLayerRenderer`](https://openlayers.org/en/latest/apidoc/module-ol_renderer_canvas_VectorLayer-CanvasVectorLayerRenderer.html) is declared as extending [`CanvasLayerRenderer`](https://openlayers.org/en/latest/apidoc/module-ol_renderer_canvas_Layer-CanvasLayerRenderer.html), which leads to nowhere...

Thank you!

**Comment by ahocevar** [comment]
Why not just `any` or `ol/renderer/Layer.js`?

**Comment by jmacura** [comment]
Because `ol/renderer/Layer.js` requires a `LayerType` as its type argument which in turn requires `SourceType` and `RendererType` and we are running in circles.

**Comment by ahocevar** [comment]
@jmacura Can you provide a piece of code where this would become a problem? I may be missing something, but I cannot figure out a case where you would need to use these generics for a layer on the application level.

**Comment by jmacura** [comment]
@ahocevar Of course. There are hundreds of occurrences in [hslayers](https://github.com/hslayers/hslayers-ng).

e.g.
```
default_layers?: Layer<Source, any>[];
```

or

```
import {Subject} from 'rxjs';
import {Layer} from 'ol/layer';
import {Source} from 'ol/source';
...
layerRemovals: Subject<Layer<Source, any>> = new Subject();
```

Some other examples:
- https://github.com/hslayers/hslayers-ng/blob/73ffc90f906724a82862451362f53581f7beb043/projects/hslayers/src/common/layer-shifting/layer-shifting.service.ts#L12
- https://github.com/hslayers/hslayers-ng/blob/73ffc90f906724a82862451362f53581f7beb043/projects/hslayers/src/common/layer-shifting/layer-shifting.service.ts#L78
- https://github.com/hslayers/hslayers-ng/blob/73ffc90f906724a82862451362f53581f7beb043/projects/hslayers/src/components/add-data/add-data.service.ts#L34
- https://github.com/hslayers/hslayers-ng/blob/73ffc90f906724a82862451362f53581f7beb043/projects/hslayers/src/components/layermanager/editor/layer-editor.service.ts#L131
- etc.

**Comment by ahocevar** [comment]
Thanks @jmacura. I just created #13291, which will fix this issue.

**Comment by jmacura** [comment]
That sounds awesome @ahocevar ! We very appreciate this change.
