### ISSUE TITLE
While dragging, rotating and zooming a while, I cant handle the map

### ISSUE THREAD

**Issue by bjoernboldt** [openlayers/openlayers#13238]
This is related only to touch screen devices!
I found a bug in updateTrackedPointers_ (File: Pointer.js Line: 191)
updateTrackedPointers_ does not listen to pointercancel-Event. Sometimes pointer events stay in trackedPointers_ list.
This happens, when the browser does not fire a pointerup event for an associated pointerdown event.
In updateActivePointers_ (File: MapBrowserEventHandler.js Line: 140) you do so.

**Comment by ahocevar** [comment]
Thanks for reporting this, @bjoernboldt. Do you think you'd be able to provide a pull request with a fix?

**Comment by bjoernboldt** [comment]
This is not as easy as it seems. More than half a line must be inserted.
PointerInteraction.updateTrackedPointers_ is called from PointerInteraction.handleEvent, but this function does not receive pointercanel events. So we have to add a listener somewhere else.

**Comment by luiscamachopt** [comment]
We're also experiencing this with iPads on iPadOS 15.5.
Workaround also seems to fix the behaviour

**Comment by luiscamachopt** [comment]
@bjoernboldt thanks for including your workaround.
From your bug description it sounds like the fix would be to change line 196 of Pointer.js from
```      
      if (mapBrowserEvent.type == MapBrowserEventType.POINTERUP) {
```
to
```
      if (
        mapBrowserEvent.type == MapBrowserEventType.POINTERUP ||
        mapBrowserEvent.type == MapBrowserEventType.POINTERCANCEL
      ) {
```
Any reason why this change wouldn't work?
