### ISSUE TITLE
cannot access to v5.1.3

### ISSUE THREAD

**Issue by ambotelloaponte** [openlayers/openlayers#13257]
Please, since a few days I cannot access to https://openlayers.org/en/v5.1.3/css/ol.css, is this a deprecated version? what do i need to solve this issue?

**Comment by ahocevar** [comment]
As stated unter "Older Versions" on https://openlayers.org, the only 5.x version hosted through that API is v5.3.0. But you can download all other versions from the Releases page on GitHub, e.g. https://github.com/openlayers/openlayers/releases/v5.1.3. You'll want the `v5.1.3-dist.zip` file.

**Comment by ambotelloaponte** [comment]
Thank you very much for your prompt reply. I'll talk to my team to consider an upgrade
