### ISSUE TITLE
about intersectsCoordinate

### ISSUE THREAD

**Issue by guzicheng90** [openlayers/openlayers#13255]
**Describe the bug**
I used lineString.intersectsCoordinate(point) to check whether the point is on the line
but I got some wrong answers

**Reproduce **
Find in openlayers/src/ol/geom/Geometry.js 
containsXY(x, y) {
   const coord = this.getClosestPoint([x, y]);
   return coord[0] === x && coord[1] === y;
}
1. if xy=[10,10]
2. this.getClosestPoint([x, y]); returns [10.00000001,10]
3. here 10 !== 10.00000001（coord[0] !== x）
4. it will return false
5. but actually, i think the inaccuracy can be ignored

**Expected behavior**
tolerance is expected

**Comment by ahocevar** [comment]
What I usually do in such cases is calculate the squared distance between `coord` and `[x, y]` and accept the result if it is less than a small value (e.g. `1e-9`).

**Comment by guzicheng90** [comment]
thanks! I will take your advice.
