### ISSUE TITLE
WebGLTile layer rendered error images outside original extent

### ISSUE THREAD

**Issue by 2sheep2simp1e** [openlayers/openlayers#13268]
![BE06CCC5-14C6-4f59-AE1C-A41C49FF1199](https://user-images.githubusercontent.com/33643503/150269611-5ce2b3c1-6875-4d28-9496-5757e2845eb6.png)
![Dingtalk_20220120114340](https://user-images.githubusercontent.com/33643503/150269629-0c04c806-af7c-4c83-9f7b-3056fa3dc7c8.jpg)
![Dingtalk_20220120114154](https://user-images.githubusercontent.com/33643503/150269637-aa61aeb8-6ebe-4446-9005-ee107ed76abc.jpg)
![Dingtalk_20220120114913](https://user-images.githubusercontent.com/33643503/150269952-528df1c0-6e4c-469f-9ba6-f3e7ff62c66e.jpg)

**Comment by mike-000** [comment]
Tiles which are partly within the layer extent are not being clipped https://codesandbox.io/s/webgl-tiles-forked-ydphy?file=/main.js
