### ISSUE TITLE
Strange behavior of Point-Icon's in OverviewMap when rotating or zooming

### ISSUE THREAD

**Issue by Rskut** [openlayers/openlayers#13264]
As you can see in the GIF, if I change the view rotation, the Icon grows and shrinks at certain angles. The other issues I have is that the Icon gets too big if I zoom in.
I'm pushing VectorImageLayer and OS TileLayer in OverviewMap.

![chrome-capture rotation](https://user-images.githubusercontent.com/34546833/150136678-b222ee0b-a69d-4871-af38-7caa6bd5d06c.gif)

![chrome-capture zoom](https://user-images.githubusercontent.com/34546833/150136704-88bfcced-bcb1-46aa-bc76-6e6b478f3990.gif)

**Comment by mike-000** [comment]
How are you styling the icon?  If you do not want it to rotate with the view using a Vector layer might be simpler.

**Comment by Rskut** [comment]
There are some custom calculation I need to review first, sry.
