### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR from openlayers.org for Kapersky users

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#13260]
**Describe the bug**
When visiting https://openlayers.org, a user reported that they saw `ERR_HTTP2_PROTOCOL_ERROR`.

**To Reproduce**
I am not able to reproduce the problem, but it sounds like the user who experienced this was seeing the same issue on Chrome and Firefox on Windows.  We don't have any additional detail from the user, but it would be good to hear from others if anybody else is experiencing the same issue.

**Expected behavior**
No `ERR_HTTP2_PROTOCOL_ERROR`.

**Comment by tschaub** [comment]
Perhaps totally unrelated, but here is a user who had a similar problem and solved it by restarting their antivirus software: https://support.google.com/chrome/thread/117505176/err-http2-protocol-error-please-help-all-browsers-including-chrome-will-not-work

**Comment by Rskut** [comment]
I have the same problem in google chrome. Works with Microsoft Edge or if I disable Kaspersky.

**Comment by jipexu** [comment]
I have not this error on mac safari, chrome and ff ....

**Comment by tschaub** [comment]
> I have the same problem in google chrome. Works with Microsoft Edge or if I disable Kaspersky.

Thanks for confirming the issue, @Rskut.

I reached out to Kapersky technical support and they confirmed that this is an issue with Kapersky Internet Security.  They have put together a patch (version 'H') and expect it to be released between January 31 and February 14.  As a workaround, Kapersky users can add openlayers.org to the list of trusted domains under **Settings** → **Network settings** → **Trusted addresses** → **Add**

I asked if openlayers.org could get added to a list of allowed sites on their side or if there was anything else we could do on our side (e.g. disable http2) to make it so Kapersky users could access the site before the patch was released (without knowing about the workaround above).  They said they would get back to me on that.

Transcript of the support chat below.

> _Support_
 Hi! This is Support and I am your representative for this chat.
Let me read your concern first.
Just give me 1-3 minutes. Thanks
Thank you for patiently waiting.
Upon reading your description request that you are having an issue to access the website?
 
> _Me_
Yes. Are you able to access https://openlayers.org with Kapersky enabled?
 
> _Support_ 
I am sorry to hear about that. I will try my best to help you with your concern.
I checked the website and unable to access too.

> _Me_
But it works as expected without Kapersky.

> _Support_
When you disabled Kaspersky, it will work?

> _Me_
It looks like other people are having similar problems here: https://community.kaspersky.com/kaspersky-internet-security-13/kaspersky-err-http2-protocol-error-on-particular-sites-22180

> _Support_
Alright
Just wanted to clarify if Kaspersky is disabled, is it working?

> _Me_
And yes, it sounds like it works without Kapersky. I’m on a phone right now and don’t have Kapersky here.

> _Support_ 
Alright
Can you please try to add the website in trusted addresss?
You may follow this guide : Settings → Network settings → Trusted addresses → Add.
As currently on the community of Kaspersky this was a temporary resolution only.

> _Me_ 
Is there another solution? I help manage the website and cannot configure all of our visitors machines.

> _Support_ 
As this was a bug and will fix on Patch H.
It will be resolved on Patch H which will be roll out starting 31st of January till 14th of February.

> _Me_
Is there another “allowed list” that the site can be added to on your side? Or is the only workaround to have all site visitors reconfigure Kapersky?

> _Support_ 
The only temporary resolution for now is to add it to trusted address in network settings.
As it will be totally fixed on Patch H.
I tried to add the website : https://openlayers.org/ and it was working from my end

> _Me_
I saw a reply about submitting the site to https://opentip.kaspersky.com/ - will this (or anything else) get it added to an allowed list on your side?

> _Support_
That is actually a website where in you can check if there's any issue on any website.
But that one is not a part of any resolution as it will be fix starting 31st of January till 14th of February 2022
If you wanted to access the websites while Kaspersky is enabled, please add the website in trusted address.

> _Me_ 
Is there anything we can do as site administrators to make the site work with Kapersky (before February)?

> _Support_
By adding website as trusted addresses.
I already provided the temporary resolution for now and that's the only resolution.

> _Me_
I’m not just interested in visiting the site myself.  I’m looking for a solution for all the other visitors who might use Kapersky.

> _Support_
I do understand but let me try to consult this matter.

> _Me_
For example, should we disable http2 until the Kapersky patch is released?

> _Support_
Let me consult our expert about this matter and will update you.
We apologies on this matter and we will make sure that the website will be added on the safe website to access.
Are you the developer of the website or from the company of this website?

> _Me_
Both (sort of)

> _Support_
Thank you for the information.
I will consult this case and will update you once I hear from our expert.
Thank you for the patience and understanding to this matter.
Would there be anything else that I can help you with?

> _Me_
That should do it. Thank you for your help.

> _Support_
You are most welcome. Have a great day and stay safe!
I will proceed to close this chat session.

**Comment by tschaub** [comment]
Latest reply from Kapersky

> We received an update from our expert, sadly, waiting a patch H is the only fixed resolution which will be rolling out in 31st of January till 14th of February 2022. Otherwise if you can't wait you can add the website from the Kaspersky application to the trusted address. And for not for user we could offer to add exclusion for this page via trafmon, but the page not so popular (alexa.com rating). Also, we do not have any other requests except this one from developers.

I don't understand what that means and asked for clarification.

**Comment by tschaub** [comment]
Final word.  It sounds like Kapersky users can either disable Kapersky or configure it as described below.

___

As per confirmation with our dev team, the only solution is to wait for Patch H update to fix the issue.

Alternatively, you may proceed to add the website to trusted list.

Please do the following steps in order to add a website to the trusted list:
1. If the main window of Kaspersky application is not on your desktop, bring it up by double-clicking the Kaspersky desktop shortcut (icon) or by double clicking on the smaller Kaspersky icon in the bottom right corner of the screen;
2. Click on the Gear icon in the bottom left corner of the Kaspersky window;
3. On the left side menu select 'Protection';
4. On the right side menu scroll down a bit and select 'Web Anti-Virus';
5. Click on 'Advanced settings';
6. Click on "Configure Trusted URLs";
7. Click on 'Add' 
8. Enter or Copy & Paste the address of the website, then tick the 'Active' circle and press 'Add' again.
