### ISSUE TITLE
Support for updating style variables of WebGLPointsLayer

### ISSUE THREAD

**Issue by hackermd** [openlayers/openlayers#13288]
**Is your feature request related to a problem? Please describe.**
The style of a `WebGLTileLayer` can be parametrized using style variables and the class provides the `updateStyleVariables()` method to update the style variables without the need to construct a new layer object.
The `WebGLPointsLayer` currently lacks this method, making it necessary to create an new layer object, adding it to the map, removing the old layer object from the map, and disposing the old layer (see [example](https://openlayers.org/en/latest/examples/webgl-points-layer.html)).

**Describe the solution you'd like**
It would be great if the API of the `WebGLTileLayer` and `WebGLPointsLayer` would be unified - at least with respect to updating style variables.

**Comment by jeroenvheel** [comment]
Would love to see this feature i was searching for and could only find it on the WebGLTileLayer

**Comment by jeroenvheel** [comment]
@ahocevar  Thanks that works!!

**Comment by ahocevar** [comment]
To make it more obvious that style variables can be changed, I created #13294.
