### ISSUE TITLE
6.10.1-dev.1641117808939 *seems* to break ts import from index.ts for jest test files.

### ISSUE THREAD

**Issue by knelson344** [openlayers/openlayers#13285]
When we upgrade from 6.10.1-dev.1641117746220 to 6.10.1-dev.1641117808939, our exports from our index.ts file are not recognized in our jest test files. I am assuming this is a weird transitive dependency. It is a problem for all such imports -- not just OL. I checked the jest version -- it is 27.4.6 in both working and non-working versions.

I discovered this strange behavior when upgrading from 6.10.0 to 6.12.0 and then narrowed it down. 

1. Install Jest
2. create a very simple Jest test
>>>>>>
 import { Util } from '../ts'

describe('convertMultiworldLongitude', () => {
  it('converts out of bounds longitudes', () => {
    const posLong = Util.convertMultiworldLongitude(1224)
  })
})
>>>>>>
3. Under the directory '../ts' there is an index.ts which exports Util. This export is recognized in the working version and not recognized in the other version.
4. When the export is not recognized, the test of course fails. I can then replace the import statement with an explicit import -- import { Util } from '../ts/util/Util'. This succeeds

I *believe* the error message is not of interest. However, I do include it below. The error has nothing to do with GeoTiFFImage.

I am hoping that the specificity of the version will be helpful. Really like OL a lot -- this is the first problem we have had in ages.

<<<<<<<<
 Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    ...

    /node_modules/geotiff/src/geotiff.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import GeoTIFFImage from './geotiffimage';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/ol/src/source/GeoTIFF.js:7:1)
<<<<<<<<<

**Comment by ahocevar** [comment]
Can you please report the status of the latest official version, after `npm install ol@latest`? Thanks.

**Comment by knelson344** [comment]
Thanks for the super fast response. I am running into some dependency issues on the install. I will fix all of that and reply.

**Comment by knelson344** [comment]
Andreas, it gives me the same error.

Kim

**Comment by ahocevar** [comment]
This issue should be fixed when geotiff.js v2.0 is released, and OpenLayers is updated to use it. See geotiffjs/geotiff.js#269.

**Comment by knelson344** [comment]
Thanks very much. I will keep an eye out.
