### ISSUE TITLE
WebGLTileLayer: updateStyleVariables is broken after using setStyle

### ISSUE THREAD

**Issue by constantinius** [openlayers/openlayers#13287]
**Describe the bug**
When using a `WebGLTileLayer`s `setStyle` function, the `updateStyleVariables` does not seem to work anymore and the 

**To Reproduce**
1. Go to https://geotiffjs.github.io/dem-app/
2. Use any slider, which should update the visualization (this is using `updateStyleVariables` underneath)
3. Set a different color ramp or visualization mode (this is using `setStyle` underneath)
4. Use the sliders again, and no changes in the visualization is to be observed

**Expected behavior**
Using `updateStyleVariables` should work after using `setStyles`

**Comment by ahocevar** [comment]
@constantinius Can you please share the source code you are using, or - even better - modify an existing example in a codesandbox so it shows the problem?

**Comment by constantinius** [comment]
@ahocevar the relevant part is here: https://github.com/geotiffjs/dem-app/blob/7809568019318443dea101c9f80284477579b32f/src/components/Map.vue#L72-L89

Will try a codesandbox too.

**Comment by constantinius** [comment]
@ahocevar This sandbox also shows the issue: https://codesandbox.io/s/strange-swartz-3pwcw?file=/main.js
The `setStyle` is invoked on line 74, thus the variable update does not work.

(Using NumpyTiles here as geotiff examples keep acting up in the sandbox)

**Comment by ahocevar** [comment]
Thanks @constantinius, I should have enough information now to investigate the issue.

Regarding geotiffs in codesandbox, we’re eagerly waiting for geotiff.js v2 to fix that 🙂
