### ISSUE TITLE
Heatmap doesn't render (v6.12)

### ISSUE THREAD

**Issue by zachsa** [openlayers/openlayers#13295]
**Describe the bug**
Heatmap layers do not appear on the screen, despite being present as layers on a map object

I should note that the heatmap DOES appear when developing on localhost. I'm using Webpack to bundle a react app - but even when I normalized the differences between the webpack = production and webpack = development environments the same behaviour occurs (not visible on production build)

Since there are so many differences between developing on localhost vs on a https domain, and using webpack with development/production mode, I thought it worth posting here as a starting point to figure out the problem. Hope that's okay!

Looking at the site - nccrd.saeon.ac.za the map clearly works as do other layers. It's just the heatmap that does not. I have also tried running `npm install` instead of `npm run ci` to see if the problem was maybe related to the lock file (it is not - this did not help)

**To Reproduce**
1. Go to https://nccrd.saeon.ac.za. There should be a yellowish heat map on top of the base map
2. Go to the developer console. the map, and other relevant objects have been attached to the window object for debugging

```js
// window objects
window.VectorSource // (import VectorSource from 'ol/source/Vector')
window.WKT // (import WKT from 'ol/format/WKT')
window.Heatmap  // import Heatmap from 'ol/layer/Heatmap'

// (1) Defined the layer making function
makeLayer = data => {
  const format = new WKT()
  return new Heatmap({
    gradient: ['#893448', '#d95850', '#eb8146', '#ffb248', '#f2d643', '#ebdba4'],
    source: new VectorSource({
      features: data.POINT_LOCATIONS.data.map(({ xy, normalizedBudget }) => {
        const feature = format.readFeature(xy, {
          dataProjection: 'EPSG:4326',
          featureProjection: 'EPSG:4326',
        })

        feature.set('normalizedBudget', normalizedBudget)
        return feature
      }),
    }),
    blur: 100,
    radius: 80,
  })
}

// (2) Create the layer
heatMapLayer = makeLayer(data)

// (3) Add the layer
map.addLayer(heatMapLayer)
```

By interrogating that map object, you can see that the heatmap layer just ... doesn't show:

```js
// Confirm that the map object is the map that is on the screen
map.getAllLayers()[0].set('opacity', 0.3) // it is!

// There are 3 layers - the 3rd is the heatmap that we just added above. delete it
map.removeLayer(map.getAllLayers()[2])

// Now there are 2 layers. The base layer and the invisible heatmap
heatmap = map.getAllLayers()[1]

// And I can see that all the features are there as supposed to be
heatmap.getSource().getFeatures() // This looks the same as on localhost
```

Also, looking at the DOM output, I can see that the `<canvas>` element seems to be correctly placed and sized. I have no idea why Heatmap layers just don't seem to appear on maps.

**Expected behavior**
I expected the heatmap to render!

**Comment by zachsa** [comment]
The source code is here, in case it is helpful: https://github.com/SAEON/national-climate-change-systems

**Comment by mike-000** [comment]
`map.getLayers().item(1).getSource().getFeatures().map(function(f){return f.getGeometry().getType()})` shows you have features with geometry collections (containing mostly one, occasionally two point geometries).  Heatmap requires features with a point geometry, not a geometry collection.

**Comment by zachsa** [comment]
Hi @mike-000. Thank you so much for a quick reply!

I can see that when I change the WKT to be `POINT` WKT instead of `GEOMETRYCOLLECTION` that things work. The API delivers points in the form of `GEOMETRYCOLLECTION ()` that defaults to `POINT ()` when my xy column is null. This happens a lot on localhost but not at all on the test deployment (I didn't realize that).

I thought the heat map wouldn't mind `GEOMETRYCOLLECTION` so long as it contained only points, but I guess that the Heatmap will at some point filter out non point locations?

This took me a fair number of hours to (not) figure out - I definitely won't make this mistake again. It may be easier to use the heatmap in general if there was a warning / error if non-point geometries are fed to it

**Comment by mike-000** [comment]
A reasonable expectation perhaps as before OpenLayers version 6 any geometry which was stylable as a point (including MultiPoint, and Point within GeometryCollection) would have worked, and other geometry types could be made to work by setting a point geometry in the style - e.g. https://stackoverflow.com/questions/56780705/creating-heatmap-in-openlayers-with-vector-source-containing-linestrings which does not work with version 6.

For both Heatmap and WebGLPointsLayer on which it is now based I think a `geometryFunction` option similar to that available in `ol/source/Cluster` https://openlayers.org/en/latest/apidoc/module-ol_source_Cluster-Cluster.html could be a useful addition to allow it to be used when sources contain features with other geometries.

**Comment by ahocevar** [comment]
Simply improving the type for the WebGLPoint layer's source, i.e. changing it from `VectorSource` to `VectorSource<Point>` would make it obvious that only point geometries work. That would be a quick fix.

**Comment by zachsa** [comment]
That would be helpful @ahocevar. Would that throw an error if something other than `VectorSource<Point>` was provided even if I were consuming the library in a non-typescript project?

**Comment by ahocevar** [comment]
@zachsa When you use an IDE with TypeScript integration (e.g. VS Code), it will show you a warning. Also when your project is in JavaScript. This is the setup I use, and I find it very helpful.

**Comment by zachsa** [comment]
Would it be possible to log that warning to the console at runtime? 

I have noticed using vs code that I get a lot of things that seem in some way to be associated with typescript (I guess). Intellisense for instance methods for one. But I don't really know how it works, and I imagine that the people who would need this type of feedback the most - people less familiar with openlayers and/or typescript - would miss this.

**Comment by ahocevar** [comment]
Well, we check the geometry already anyway, so I created #13298 to warn when a geometry is not a Point.
