### ISSUE TITLE
Draw Polygon style not applying correctly

### ISSUE THREAD

**Issue by jt-helsinki** [openlayers/openlayers#13327]
**Describe the bug**
If I apply a style to Polygon which is yet to be completed, the style is applied to the final and yet undrawn segment - thus making it visible. The style is not applied to the already drawn segments. See these images of two unclosed polygons. The red segment highlights the remaining unclosed part of the polygon.

![Screen Shot 2022-02-03 at 17 30 18](https://user-images.githubusercontent.com/20871336/152375021-9e57a392-d6de-407e-b9f5-b0eaa2c07f07.png)

![Screen Shot 2022-02-03 at 17 30 30](https://user-images.githubusercontent.com/20871336/152375077-8f1d4fdc-c9ab-45fe-8db0-2db49b55e2a9.png)

**To Reproduce**
1. Draw interaction with a type: Polygon
2. Apply style after each click interaction (e.g.. line colour red)

**Expected behavior**
Only the previously drawn segments are styled and the undrawn "closing" segment is invisible. 

**Question**, is there a workaround for this?

**Comment by mike-000** [comment]
You should set the drawing style on the Draw interaction.  The default editing style described in https://openlayers.org/en/latest/apidoc/module-ol_style_Style-Style.html consists of only Fill for an incomplete Polygon geometry and blue stroke for the drawn sketch.  By setting a red stroke for the Polygon you are showing the imcomplete edge while the drawn edges remain hidden by the blue LineString style.  Here is an example updated to use a custom drawing style, and sets the finished style on the feature at the `drawend` event - as an alternative to doing that you could have the finished style as your layer style.  https://codesandbox.io/s/draw-features-forked-nb9nl?file=/main.js

**Comment by jt-helsinki** [comment]
Thanks @mike-000, 

It looks like using the style function is the correct way to update the style whilst drawing. The style function gets called as the shape is drawn so I can validate as I draw.
