### ISSUE TITLE
Layer.setMap(null) does not work in typescript strict mode

### ISSUE THREAD

**Issue by sweepline** [openlayers/openlayers#13326]
**Describe the bug**
To remove an unmanaged layer from openlayers we are supposed to use `Layer.setMap(null)` as per the docs. Since the jsdocs for the `setMap` function in `src/ol/layer/Layer.js` is written as 
```js
   * @param {import("../PluggableMap.js").default} map Map.
   * @api
   */
  setMap(map) {
```
the types generated does not allow `null` to be passed to setMap. Which in turn makes typescript not compile.

**To Reproduce**
Make a layer and try to unset the map with `.setMap(null)` with typescript strict mode enabled

**Expected behavior**
The jsdoc for generating typescript should be defined as
```js
   * @param {import("../PluggableMap.js").default | null} map Map.
   * @api
   */
  setMap(map) {
```

**Comment by ahocevar** [comment]
You could configure your `tsconfig.json`'s `"compilerOptions"` with `"strictNullChecks": false`. Also note there are ongoing efforts to make our types work better in environments with strict null checks. This effort would include adding `|null` to the allowed values for the `map` argument here. A pull request with your suggestion would be welcome.

**Comment by EvertEt** [comment]
@ahocevar Would we also want to change the setMap (and related) to all allow `null` as the places below already accept undefined. We could leave those, change them or allow both null and undefined?
- ol/Overlay (explicit undefined)
- ol/control/Control (optional)

**Comment by ahocevar** [comment]
For clarity, I think adding `|null` would make sense for those, and also consistently state in the prose documentation what passing `null` means.
