### ISSUE TITLE
Performance issue -  MajorGC 

### ISSUE THREAD

**Issue by pierluigizagaria** [openlayers/openlayers#13324]
Hi everyone I need help,
I've implemented a socket server that sends coordinates at 10hz. The openlayers map takes this coordinates and interpolates them to make them more smooth.

```
map.on('postrender', update);
function update() {
  let features = [];
  for (const [id, player] of Object.entries(players)) {
    const { lastCoords: [_x, _y], coords: [x, y], updateTimestamp } = player;
    const t = (+ new Date() - updateTimestamp) / (1000 / 10);
    const coords = fromLonLat([lerp(_x, x, t), lerp(_y, y, t)]);
    const feature = new Feature({
      ...player,
      geometry: new Point(coords),
    });
    feature.setId(id);
    features.push(feature);
  };
  playerSource.clear();
  playerSource.addFeatures(features);
  map.render();
};
```
The player object contains all the data coming from the server. The interpolation works and everything is smooth on my PC.
But! Throttling the CPU at x4 makes the whole map freeze every x seconds and the reason is a MajorGC that occurs

Here the general performance record:

![image](https://user-images.githubusercontent.com/57801386/152325260-038e2dcb-ad34-4603-8095-1319356e7f27.png)

Here in detail for the major gc:

![image](https://user-images.githubusercontent.com/57801386/152325457-102699cf-4314-4a65-bc71-67619e843287.png)

Removing the` playerSource.addFeatures(features);` and just logging the array doesn't make any freeze at all, so I think that probably there is some underlying problem on the openlayers api

Any suggestion? Thank you for your time!

**Comment by mike-000** [comment]
There can be multiple `postrender` events for each render, and clearing and adding features will trigger a render.  I think you should be using the `rendercomplete` event, and with a only single action which triggers a new render

```
map.on('rendercomplete', update);
function update() {
  let features = [];
  for (const [id, player] of Object.entries(players)) {
    const { lastCoords: [_x, _y], coords: [x, y], updateTimestamp } = player;
    const t = (+ new Date() - updateTimestamp) / (1000 / 10);
    const coords = fromLonLat([lerp(_x, x, t), lerp(_y, y, t)]);
    const feature = new Feature({
      ...player,
      geometry: new Point(coords),
    });
    feature.setId(id);
    features.push(feature);
  };
  playerLayer.setSource(
    new VectorSource({
      features: features
    })
  );
};
```

**Comment by pierluigizagaria** [comment]
Thank you for your help, tried your solutions but nothing changes, still getting major gcs every x seconds

**Comment by ahocevar** [comment]
The reason why aou are getting major garbage collections is because your application produces major garbage. Instead of removing and re-adding all features every time, you should figure out which features were added/changed/removed, and apply a diff accordingly.

If that is not an option, the least thing you should do is call `playerSource.clear(true)` instead of just `playerSource.clear()`, to make it faster. It won't improve the garbage situation, but at least improve performance a bit.

**Comment by pierluigizagaria** [comment]
Before trying to clear and replace all the feature I was updating every single feature by changing the coordinates, but still had this issue. 
I'll just accept this, I don't think there any way to resolve this.

**Comment by mike-000** [comment]
Do you really need to refresh as fast as the application can render?  Can you listen for data cycle completion events? (or failing that and the cycle is 10Hz use a 100ms setInterval).

**Comment by pierluigizagaria** [comment]
Sure, used setIntervals at 100ms, and still had this issue, I've tried everything

**Comment by ahocevar** [comment]
@pierluigizagaria:
> Before trying to clear and replace all the feature I was updating every single feature by changing the coordinates, but still had this issue.

Ok, so this must be caused by the builder/executor. In this case, the way to solve this would be to use the Immediate renderer for the ever-changing features. Something like https://openlayers.org/en/latest/examples/flight-animation.html.

**Comment by pierluigizagaria** [comment]
I don't quite understand everything but this is the part that should help me?
```
currentLine.translate(offset * worldWidth, 0);
vectorContext.drawGeometry(currentLine);
currentLine.translate(worldWidth, 0);
vectorContext.drawGeometry(currentLine);
```

**Comment by mike-000** [comment]
Unless you are using a global projection and wrapX that can be replaced with

`vectorContext.drawGeometry(currentLine);`

**Comment by pierluigizagaria** [comment]
I don't understand how Immediate render works :/

**Comment by ahocevar** [comment]
@pierluigizagaria Something like this:
```js
map.on('postrender', update);
function update(event) {
  const vectorContext = getVectorContext(event);
  vectorContext.setStyle(style); // whatever style you want for your points

  const point = new Point([NaN, NaN]);
  for (const [id, player] of Object.entries(players)) {
    const { lastCoords: [_x, _y], coords: [x, y], updateTimestamp } = player;
    const t = (+ new Date() - updateTimestamp) / (1000 / 10);
    const coords = fromLonLat([lerp(_x, x, t), lerp(_y, y, t)]);
    point.setCoordinates(coords);
    vectorContext.drawGeometry(point);
  };
};
```
And don't add the layer with the playerSource to your map any more.

**Comment by pierluigizagaria** [comment]
Can I use functions to style the point? I have something like this
```
const player = (feature) => [
  new Style({
    image: new Circle({
      radius: 8,
      fill: new Fill({
        color: feature.get('active')
          ? feature.get('ally') == true ? COLORS.ALLY
            : COLORS.ENEMY : COLORS.NEUTRAL,
      }),
    }),
    text: new Text({
      text: feature.get('name').toString(),
      font: '16px sans-serif',
      fill: new Fill({ color: COLORS.NEUTRAL }),
      offsetY: 20,
    })
  }),
];
```

**Comment by mike-000** [comment]
You are constantly creating new style objects. You appear to have 3 basic styles which should be reused by a style function

```
const styleAlly = new Style({
    image: new Circle({
      radius: 8,
      fill: new Fill({
        color: COLORS.ALLY,
      }),
    }),
    text: new Text({
      font: '16px sans-serif',
      fill: new Fill({ color: COLORS.NEUTRAL }),
      offsetY: 20,
    })
  });

const styleEnemy = new Style({
    image: new Circle({
      radius: 8,
      fill: new Fill({
        color: ENEMY,
      }),
    }),
    text: new Text({
      font: '16px sans-serif',
      fill: new Fill({ color: COLORS.NEUTRAL }),
      offsetY: 20,
    })
  });

const styleNeutral = new Style({
    image: new Circle({
      radius: 8,
      fill: new Fill({
        color: NEUTRAL,
      }),
    }),
    text: new Text({
      font: '16px sans-serif',
      fill: new Fill({ color: COLORS.NEUTRAL }),
      offsetY: 20,
    })
  });

const player = (feature) => {
  const style = feature.get('active')
          ? feature.get('ally') == true ? styleAlly
            : styleEnemy : styleNeutral;
  style.getText().setText(feature.get('name').toString());
  return style;
};

```

**Comment by pierluigizagaria** [comment]
So this was the real problem, sorry for wasting your time...
