### ISSUE TITLE
z-Index is not a known CSS property

### ISSUE THREAD

**Issue by Jalgoczy** [openlayers/openlayers#13322]
**Describe the bug**
Building an Angular app I get a warning that "z-Index" is not a known CSS property.

**To Reproduce**
1. Go to **ol.css**
2. Check classes **ol-scale-step-text**, **ol-scale-step-marker** and **ol-scale-singlebar**

**Expected behavior**
Fix the typo by using "z-index" instead of "z-Index"

**Comment by EvertEt** [comment]
This should be fixed by https://github.com/openlayers/openlayers/pull/13319 which was merged recently. 
This fix should be available in the latest dev release (which seems to be 6.12.1-dev.1643631970817)

**Comment by Jalgoczy** [comment]
Thank you for your answer. I will wait for the update.

**Comment by tschaub** [comment]
Surprising that this typo was in there so long (see #9013).  Fixed by #13319 as @EvertEt mentions.
