### ISSUE TITLE
geometryFunction for modifyInteraction

### ISSUE THREAD

**Issue by tobias-brunner** [openlayers/openlayers#13329]
**Is your feature request related to a problem? Please describe.**
Custom geometries can be drawn in OL by providing a geometryfunction to the draw interaction. Geometries drawn this way cannot be edited in the same way (i.e. by using a standardized geometryfunction).

**Describe the solution you'd like**
Add the possibility to provide a geometryFunction when creating an instance of a modify Interaction.

**Comment by mike-000** [comment]
That would be more complex than the geometry function for Draw, where an interaction only uses one geometry type and function, as Modify can simultaneously work on multiple adjoining features of different geometry types.  Custom geometries can already be modified by creating a temporary geometry at the `modifystart` event, maintain that for styling while modifying, and set it as the final geometry at the `modifyend` event as in https://openlayers.org/en/latest/examples/draw-and-modify-geodesic.html and https://openlayers.org/en/latest/examples/modify-scale-and-rotate.html

**Comment by tobias-brunner** [comment]
that's a great workaround which suits my usecase perfectly. thanks!
