### ISSUE TITLE
Angular Web Worker KML format

### ISSUE THREAD

**Issue by digoburigo** [openlayers/openlayers#13356]
**Describe the bug**
When trying to use a web worker in Angular that convert a layer to KML format a bug occurs.

**To Reproduce**
[downloadKml.zip](https://github.com/openlayers/openlayers/files/8035665/downloadKml.zip)

1. I was not able to create the steps in StackBlitz because of web worker problems
2. I made a zip containing the Angular project with the bug

**Expected behavior**
In the zip file there is the same thing using GeoJSON format and is working fine

**Comment by mike-000** [comment]
It is unlikely any of the subclasses of `ol/format/XMLFeature` will work.  Methods based on DOM such as DOMParser and XMLSerializer are not available in web workers.
