### ISSUE TITLE
Clear map

### ISSUE THREAD

**Issue by ricef** [openlayers/openlayers#13354]
Hello, I need to create a function that have to clear my map from all the points and route that are present in the map before some user interaction.
I read a lot of documentation online but I didn't find any working solution.
I'm using openlayers 6.
How can I make it?
Thank
Andrea.

**Comment by Rskut** [comment]
You could just remove the layer:

map.removeLayer(yourLayer)

**Comment by ricef** [comment]
I just tried it but I don't know how to choose the correct layer, the result is that i remove the map and the points remain.

**Comment by Rskut** [comment]
How do you add new layers to your map? If you can't access your layer object, you can iterate all layers of your map:

for(const layer of map.getLayers().getArray()){
	if(layer.get('layerId') === 'pointLayer') {
           map.removeLayer(layer);
	}
}

**Comment by ricef** [comment]
```
var layer = new ol.layer.Vector({
    source: new ol.source.Vector({
      features: [
        new ol.Feature({
          geometry: new ol.geom.Point(lonLat)
        })
      ]
    }),
    style: new ol.style.Style({
      image: new ol.style.Icon({
        anchor: [0.5, 46],
        anchorXUnits: 'fraction',
        anchorYUnits: 'pixels',
        src: pinPath,
        scale: 1
      })
    })
  });
  if (this.map) {
    this.map.addLayer(layer);
    this.map.getView().animate({ zoom: Zoom, center: lonLat }); 
  }
```
This i the code I use to add a new pointer. Where and how I have to set the layer id? sorry but I'm not very able with openlayer.

**Comment by Rskut** [comment]
`layer.set('layerId', 'pointLayer');`

But you could make your layer variable somehow accessible from wherever you're trying to remove the layer. Just put it in the global context.

**Comment by ricef** [comment]
Thank you very much for the suggest. Now it work!!
