### ISSUE TITLE
Open popup on marker hover 

### ISSUE THREAD

**Issue by ricef** [openlayers/openlayers#13359]
Hi, I need to implement a function that can open a popup with some information by hover on a marker placed in the map.
I'm using openlayers 6 I tried to follow the example in the openlayers documetation but it doesn't work.
This is how I create a point:
```
var lonLat = ol.proj.fromLonLat([Lon, Lat])
  var layer = new ol.layer.Vector({
    source: new ol.source.Vector({
      features: [
        new ol.Feature({
          geometry: new ol.geom.Point(lonLat)
        })
      ]
    }),
    style: new ol.style.Style({
      image: new ol.style.Icon({
        anchor: [0.5, 46],
        anchorXUnits: 'fraction',
        anchorYUnits: 'pixels',
        src: pinPath,
        scale: 1
      })
    })
  });
  layer.set("layerId", "Point");
  if (this.map) {
    this.map.addLayer(layer);
    this.map.getView().animate({ zoom: Zoom, center: lonLat });

  }
```
How can I do?
Thanks, Andrea

**Comment by Rskut** [comment]
You mean this example? https://openlayers.org/en/latest/examples/icon.html
Btw. I would recommend asking this kind of questions on stackoverflow.

**Comment by Rskut** [comment]
You need to show some code, but in the example I posted you can see how the cursor being changed on hover. You can use this code to show the pop-up instead of change the cursor style.

**Comment by ricef** [comment]
Discussion on stackoverflow if someone is interested.
https://stackoverflow.com/questions/71067487/open-popup-on-marker-hover/71128376?noredirect=1#comment125766513_71128376
