### ISSUE TITLE
Android Chrome Performance issue when rendering a large ImageLayer with a static source

### ISSUE THREAD

**Issue by KhatibFX** [openlayers/openlayers#13362]
**Describe the bug**
Currently, OpenLayer's performance on an Android phone using chrome is much worse than using Firefox when rendering a large ImageLayer with a static source, say a 10,000 x 7,000 pixels image.

**To Reproduce**
1. Open the example project reproducing the issue, which was forked from the static image example, found [here](https://codesandbox.io/s/static-image-forked-prrz5?file=/main.js) on both Chrome and Firefox on Android (Tested on Oneplus 7 Pro running Android 11)
2. Run the example
3. Try pinching to zoom and panning
4. Notice that on Chrome, pinching to zoom will be smooth for a second, and then completely freeze the page for a couple seconds, back and forth, while on Firefox, the freezing doesn't occur

**Expected behavior**
Both Chrome and Firefox to be able to pinch to zoom and pan without freezing every few seconds.

**Comment by KhatibFX** [comment]
@ahocevar Sorry for disturbing, but I just wanted to know if this bug is acknowledged, or was successfully reproduced, since there has been no comment on it, so I thought it flew under the radar. Thanks.

**Comment by ahocevar** [comment]
@KhatibFX I noticed that the example is even slow on my desktop in Safari, but given the pixel size of the image, this is not a surprise. Handling huge images is obviously very different in different browsers. My recommendation would be to use a different technique than a static image, e.g. a cloud optimized GeoTIFF or create tiles.

There might be ways to make OpenLayers handle huge images better, but I personally don't have the resources to investigate that further. If you have, or know someone who has, we'd of course accept a pull request with any improvements that people could come up with.

**Comment by ahocevar** [comment]
@KhatibFX Please test if #14444 improves the situation for you.
