### ISSUE TITLE
.prettier configuration file for Prettier

### ISSUE THREAD

**Issue by MagicCrazyMan** [openlayers/openlayers#13369]
**Is your feature request related to a problem? Please describe.**
Since my VisualStudioCode has a default `Prettier` configuration in user settings, which is different from the code-styling of the openlayers. I expect to add a `.prettierrc` configuration file to specified the formatting style.

**Describe the solution you'd like**
Add `.prettierrc` file to the project. #13368

**Comment by tschaub** [comment]
OpenLayers uses ESLint for formatting.

**Comment by tschaub** [comment]
It looks like the Prettier extension for VSCode has a `prettier.requireConfig` option (added in https://github.com/prettier/prettier-vscode/pull/283).  If this does what it sounds like it does, it wouldn’t require that you make changes to every project that doesn’t use Prettier for formatting.

**Comment by MagicCrazyMan** [comment]
thanks a lot, i had set the formatter to ESLint in vsc for openlayers
