### ISSUE TITLE
How to propagate mouse events to Openlayer map

### ISSUE THREAD

**Issue by MartinPyka** [openlayers/openlayers#13375]
Hi,

I show a ThreeJS canvas on top of an OpenLayer map.  Now, the map does not respond to any mouse event (e.g mouse move or wheel). In my application, I want to toggle map adjustments on and off, which means, if the user activates map-mode, the mouse events should allow him to use the DragRotateAndZoom interactor.

How can I programmatically turn mouse events on and off for the Openlayer map given the fact that the ThreeJS canvas prevents any mouse events on the map in the first place?

Thank you,
Martin

**Comment by mike-000** [comment]
If you position any element over the map you will need to ensure its `pointer-events` style is set to 'none'

either in css

```
#canvas {
    pointer-events:none;
}
```


or javascript

`canvas.style.pointerEvents = 'none';`

**Comment by MartinPyka** [comment]
ah, thank you :-)
