### ISSUE TITLE
More trkseg tags in one GPX

### ISSUE THREAD

**Issue by vsevjednom-cz** [openlayers/openlayers#13370]
**Is your feature request related to a problem? Please describe.**
My tracking app exports gpx with `</trkseg><trkseg>` when i paused tracking. But OpenLayers shows only first `<trkseg>...</trkseg>` in the map.

**Describe the solution you'd like**
Can OpenLayers shows all `<trkseg>`, not only first?

**Comment by vsevjednom-cz** [comment]
Where's the problem?
Pause with </trkseg> does make a sense. Example: 10 km tracked in one city at the morning, then pause, then 10 km tracked in another city in the evening. Saving this without </trkseg> does not make any sense because OpenLayers count distance between pauses. I saw it many times.

**Comment by ahocevar** [comment]
When a GPX contains multiple `trkseg`s, the resulting geometry could be a `MultiLineString`.

**Comment by vsevjednom-cz** [comment]
Oh, thank you!

But:
I changed `f.getGeometry().getLineString(0)` to the `f.getGeometry().getLineStrings()` on `style` function - it shows only first `trkseg` again 😰. Where is the problem?

**Comment by jipexu** [comment]
Hi can you provide simple example or more code ? It will be probably more easy and fast to find what and where is the problem ...

**Comment by vsevjednom-cz** [comment]
Yes, of course.

Example of GPX:
```
...
<trkpt lat="49.190358" lon="16.633053"><ele>206</ele><time>2022-04-15T13:05:22.179+02:00</time></trkpt>
<trkpt lat="49.190374" lon="16.632954"><ele>206</ele><time>2022-04-15T13:05:23.027+02:00</time></trkpt>
<trkpt lat="49.190396" lon="16.632846"><ele>206</ele><time>2022-04-15T13:05:24.013+02:00</time></trkpt>
<trkpt lat="49.190425" lon="16.632716"><ele>206</ele><time>2022-04-15T13:05:24.979+02:00</time></trkpt>
</trkseg><trkseg>
<trkpt lat="49.192075" lon="16.611728"><ele>224</ele><time>2022-04-15T13:11:50.392+02:00</time></trkpt>
<trkpt lat="49.192231" lon="16.61131"><ele>224.7</ele><time>2022-04-15T13:11:51.39+02:00</time></trkpt>
<trkpt lat="49.192206" lon="16.611388"><ele>224.7</ele><time>2022-04-15T13:11:52.384+02:00</time></trkpt>
<trkpt lat="49.19223" lon="16.611389"><ele>224.3</ele><time>2022-04-15T13:11:53.41+02:00</time></trkpt>
...
```

Then:
```
var vector = new ol.layer.VectorImage(
	{	source: source,
		style: someStyle,
	});
...
  function someStyle(f) {
  
          if (f.getGeometry().getType() === \'MultiLineString\') {
          var line = f.getGeometry().getLineString(0); // f.getGeometry().getLineStrings() works the same
        } else {
          var line = f.getGeometry();
        }
...
  }
```

I hope it helps.

**Comment by ahocevar** [comment]
We have a test case that covers the case of multiple `trkseg`s:

https://github.com/openlayers/openlayers/blob/d404371417279c55cadc2d7181af8d54d45c740d/test/browser/spec/ol/format/gpx.test.js#L302-L350

**Comment by vsevjednom-cz** [comment]
But how must I edit my code? Your code is different.

**Comment by ahocevar** [comment]
Hard to tell with just the snippets you provided.

**Comment by vsevjednom-cz** [comment]
I'm looking for replacement of `var line = f.getGeometry().getLineString(0);` for more `trkseg`s.

Example is here: https://jedu.vsevjednom.cz/activity/3251
There is GPX with two `trkseg` tags. It shows only first (`getLineString(0)`) or second (`getLineString(1)`) - it's `styleFn(f) {` at line 1123. I tried `getLineStrings` without success.

**Comment by ahocevar** [comment]
The simplest fix would be to remove the `geometry` property from the style returned in `styleFn`. Then the whole MultiLineString will be rendered.

**Comment by vsevjednom-cz** [comment]
I don't see anything if I remove `geometry` 😨.

**Comment by ahocevar** [comment]
Then remove the whole `style: styleFn` assignment, to render everything with the default style.

**Comment by vsevjednom-cz** [comment]
Oh, you're right! It's a problem in `ol.style.FlowLine` from `ol-ext`. `ol.style.Style` works without problem. Thank you, thank you, thank you!
