### ISSUE TITLE
Adding more than 50 vector or raster layers makes the FPS drop below 6fps when zooming and panning

### ISSUE THREAD

**Issue by Rennzie** [openlayers/openlayers#13384]
**Describe the bug**
A map we are building is required to have many layer files, be they kml, geojson or xyz tiles. I'm noticing that once we go over 50 layers (of any type) the rendering performance degrades significantly (< 10fps). We are using OL 6.12.

I'm curious to know if this is caused by the number of canvas elements in the DOM? Is it a known issue with a work around, like using a LayerGroup? Or can I combine multiple sources of the same type into one layer? Or should I really be using a geo-server for this number of layer?

**To Reproduce**
1. Add 50 or more layers to a map
2. Using the FPS meter, pan and zoom
3. Notice the drop in frames relative to only a single layer

**Expected behavior**
Hoping I can render at 30-60fps.

**Comment by mike-000** [comment]
How many canvases do you have?  Layers share convas where possible.  The order of the layers and differences in layer type, class name, pixel ratio, opacity, background color, view rotation may prevent sharing.

**Comment by Rennzie** [comment]
It's looking like one canvas per layer. Each canvas is wrapped in a div that has a unique id on it. This could be something on our end though. I'll check. 

Is there anything else I should be having a look at?

**Comment by Rennzie** [comment]
Incase anyone comes across this:

When creating a `Layer` (Vector or Raster) we had been setting a unique `className` to every new instantiation. This causes OL to wrap the `canvas` in a `div` with the specified class name. The result being one `canvas` (plus `div` wrappers) per layer - causing a FPS slow down. By shifting the layer identifier to the `properties` property it fixed our issue. Now there is one `canvas` element shared between any number of layer - much better.
