### ISSUE TITLE
how to improve performance when draw 100 lineString that It consists of about 500 thousand points

### ISSUE THREAD

**Issue by zxw394** [openlayers/openlayers#13399]
use webGL, but found only webGLPointLayer support points not lineString。

thanks for your reminder

**Comment by ahocevar** [comment]
OpenLayers should work fine in the scenario you're mentioning, with the standard renderer. See e.g. https://openlayers.org/en/latest/examples/fractal.html, and move the slider all the way to the right to render a linestring with > 700k points.

Maybe you can share some code and your example data?

**Comment by zxw394** [comment]
> OpenLayers should work fine in the scenario you're mentioning, with the standard renderer. See e.g. https://openlayers.org/en/latest/examples/fractal.html, and move the slider all the way to the right to render a linestring with > 700k points.
> 
> Maybe you can share some code and your example data?

thank you very much. below is my code
``` 
await Promise.allSettled(
  //many request
  nodeIds.map(item => {
      let nodes = item.nodes
      //nodes include start and end，call the backend get all points on the line
      return getRouterResultsFn(nodes);
  })
).then((results) => {
  results.forEach(r => {
    features.push(r.value);//r.value is function getRouterResultsFn returns line_feature
  })
  //waiting for all request response, put all features at once，then render
  linesLayer.getSource().addFeatures([...features]);
})

function getRouterResultsFn (nodes) {
  return axios.getPathPoints(nodes).then(res => {
      let line_geom= new ol.geom.LineString(paths);
      line_feature.setGeometry(line_geom)
      line_feature.setStyle(lineArrowStyle);
      return line_feature
    }
    return null
  }).catch(() => {
    return null
  })
}
```
feature type is lineString
> feature = new ol.geom.LineString(paths);

feature style is complicated，arrows on the map road, increase or decrease according to the map zoom level

![1](https://user-images.githubusercontent.com/8643196/155051554-819a7424-8b34-46d8-97b7-55bcf71872ea.png)
```
function lineArrowStyle(feature, res) {
    let styles = [
      new ol.style.Style({
          troke: new ol.style.Stroke({
          color: 'rgba(106,221,165,0.65)',
          width: 8
       }),
        zIndex: 1
      })
    ];
    let trackLine = feature.getGeometry()
    let length = trackLine.getLength();
    let stpes = 50; 
    let geo_steps = stpes * res;
    let arrowsNum = Math.floor(length / geo_steps);
    let tree = new RBush();
    trackLine.forEachSegment(function (start, end) {
        var dx = end[0] - start[0];
        var dy = end[1] - start[1];
        let rotation = Math.atan2(dy, dx);
        let geom = new ol.geom.LineString([start, end]);
        let extent = geom.getExtent();
        var item = {
            minX: extent[0],
            minY: extent[1],
            maxX: extent[2],
            maxY: extent[3],
            geom: geom,
            rotation: rotation
        };
        tree.insert(item);
    });

    for (let i = 1; i < arrowsNum; i++) {
        let arraw_coor = trackLine.getCoordinateAt(i * 1.0 / arrowsNum);
        let tol = 0.0001;
        let arraw_coor_buffer = [arraw_coor[0] - tol, arraw_coor[1] - tol, arraw_coor[0] + tol, arraw_coor[1] + tol];
        var treeSearch = tree.search({
            minX: arraw_coor_buffer[0],
            minY: arraw_coor_buffer[1],
            maxX: arraw_coor_buffer[2],
            maxY: arraw_coor_buffer[3]
        });
        let arrow_rotation;
        if (treeSearch.length == 1)
            arrow_rotation = treeSearch[0].rotation;
        else if (treeSearch.length > 1) {
            let results = treeSearch.filter(function (item) {
                let _tol = 1/10000000;
                if (item.geom.intersectsExtent([arraw_coor[0] - _tol, arraw_coor[1] - _tol, arraw_coor[0] + _tol, arraw_coor[1] + _tol]))
                    return true;
            })
            if (results.length > 0)
                arrow_rotation = results[0].rotation;
        }
        styles.push(new ol.style.Style({
            geometry: new ol.geom.Point(arraw_coor),
            image: new ol.style.Icon({
                src: require('@/assets/images/actionControl/pathArrow.svg'),//icon addr
                anchor: [0.75, 0.5],
                rotateWithView: false,
                rotation: -arrow_rotation
            }),
            zIndex: 2
        }));
    }
    return styles;
}
```
Probably less than a few hundred thousand points, maybe millions when there are many lines to render，it is very laggy now，
I don't found the reason.

thanks for your reminder

**Comment by ahocevar** [comment]
It looks like most of the time is spent in the style function. You can verify that by removing the style from the layer. You should see everything rendering smoothly then.

To optimize the style function, the easiest thing to do is only create an `Icon` style once, and not create a new icon for every arrow. There is a `setRotation()` method on the icon to set the correct rotation for each arrow. Even better, also create the arrow `Style` only once, using the `setGeometry()` method to set the current point for the arrow.

Next, simplify how you calculate the arrow points. Use the `LineString`'s `getCoordinateAt()` method instead of building an RTree, and don't calculate that with every style function call. Instead, do it once when you load the features.

With these changes, you should be fine and get smooth rendering.

**Comment by zxw394** [comment]
> It looks like most of the time is spent in the style function. You can verify that by temporarily removing the style from the layer. You should see everything rendering smoothly then.
> 
> To optimize the style function, the easiest thing to do is only create an `Icon` style once, and not create a new icon for every arrow. There is a `setRotation()` method on the icon to set the correct rotation for each arrow. Even better, also create the arrow `Style` only once, using the `setGeometry()` method to set the current point for the arrow.
> 
> Next, simplify how you calculate the arrow points. Use the `LineString`'s `getCoordinateAt()` method instead of building an RTree, and don't calculate that with every style function call. Instead, do it once when you load the features.
> 
> With these changes, you should be fine and get smooth rendering.

thank you very much
when i remove the arrow style，the page is smoothly。
