### ISSUE TITLE
Explicit doc on EPSG:4326 used projection

### ISSUE THREAD

**Issue by christophenoel** [openlayers/openlayers#13394]
After using OpenLayers for 10 years, I still have the same question that could be explictly stated in the documentation:

Since EPSG:4326 (WGS84 unprojected) is a geographic, non-project coordinate system, what is the implicit projection used by OpenLayers when rendering  the map for this CRS ?

Is it using the Pseudo (displayed as if a degree is a linear unit of measure) Plate Carrée  (equirectangar projection) ?

Thanks for the clarification.

**Comment by ahocevar** [comment]
If you set the view projection to `EPSG:4326`, the map will be rendered with cartesian coordinates on a plane. This is what you refer to as "Pseudo".

**Comment by christophenoel** [comment]
Thanks you very much.

Pseudo Plate carrée is referred in a large set of papers (https://pro.arcgis.com/en/pro-app/latest/help/mapping/properties/plate-carree.htm, https://epsg.io/32662 , etc.)
