### ISSUE TITLE
15k image markers performance

### ISSUE THREAD

**Issue by zxwild** [openlayers/openlayers#13409]
I'm migrating from leaflet map to openlayers.
My map requires me to display about 12k markers right now and this amount could grow up to about 60k (most of markers are rotated by various angles).

In leaflet after a lot of attempts I've achived this. I combined `leaflet-canvas-markers` with my own cache implementation, so at last it's able to display 12k items without any visible glitches (on a relatively strong computer).

Now I'm trying to reimplement it with openlayers.
I see `Icon` markers and `RegularShape` display on a canvas already, it's cool, but performance is still below required, here is the codepen demo (just increase to 30k markers for example if your computer is too fast):
https://codepen.io/zxwild/pen/KKyRRKv

The question/offer is:
Does openlayers use cache this case and which type of cache is used?

On my own implementation I use a hidden canvas, which contains all possible markers variants, and rotated variants are cached too.

So when I need to redraw a marker I just retrieve a required section from this canvas cache by X and Y and copy it to a map canvas, it's a very fast operation.

**Comment by ahocevar** [comment]
You could simply try to replace `ol.layer.Vector` with `ol.layer.VectorImage`. There are other options too, but try that one first.

**Comment by zxwild** [comment]
[ahocevar](https://github.com/ahocevar), damn, that's a pure magic, thanks a lot :smile: 
But it seems I wouldn't able to find it in the docs.

Here is the fork of the demo, it works fast for 50k markers, only difference I see is `ol.layer.VectorImage` displays markers on `dragend`.

https://codepen.io/zxwild/pen/ExbLzgj

**Comment by ahocevar** [comment]
The documentation is here: https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorImage-VectorImageLayer.html.

Another option would be to use the WebGLPoints layer, as shown in the [workshop](https://openlayers.org/workshop/en/webgl/) or in this [example](https://openlayers.org/en/latest/examples/icon-sprite-webgl.html). I have created a modified version of your codepen: https://codepen.io/ahocevar/pen/MWOGMVp.
