### ISSUE TITLE
Graticule labels are misplaced when the map is rotated 45 degrees

### ISSUE THREAD

**Issue by ntamas** [openlayers/openlayers#13400]
**Describe the bug**

It seems like the graticule labels are misplaced when the map is rotated exactly at 45 degrees -- see [this example](https://codesandbox.io/s/graticule-forked-3qz4fe). Attached is a screenshot that shows how the graticule labels are drawn on my machine (macOS 12.1, Firefox 97). Changing the rotation to 44.9 or 45.1 degrees is okay. Other angles that are problematic: -45 degrees, -135 degrees and 135 degrees.

<img width="549" alt="Screenshot 2022-02-21 at 10 37 55" src="https://user-images.githubusercontent.com/195637/154928281-29b357fa-3bf5-4881-9e36-2a3473c56f24.png">

**To Reproduce**

1. Open [this code sandbox](https://codesandbox.io/s/graticule-forked-3qz4fe)
2. Note that the graticule labels are misplaced (they are in the middle of the map, not at the edges)

**Expected behavior**

The graticule labels should be placed at the edges, just like with 44.9 or 45.1 degrees or any other angle that is not 45, -45, 135 or -135 degrees.

**Additional info**

I tried to fix this myself but I haven't figured it out yet; one thing that I've noticed is that the `extent` argument passed into `Graticule.getParallelPoint_` does not seem like a valid extent because `extent[0] > extent[2]`. This happens only for 45, -45, 135 or -135 degrees.

**Comment by ntamas** [comment]
It seems like the issue also depends on the window size; making the browser window wider when looking at the CodeSandbox example will make the labels jump all around; sometimes they disappear entirely, sometimes they get rendered in the middle of the map, but never at their right positions.

**Comment by mike-000** [comment]
There will be a zero divide at https://github.com/openlayers/openlayers/blob/main/src/ol/layer/Graticule.js#L681-L682  Substituting zeros with a suitably small number should ensure a meaningful result.

**Comment by ntamas** [comment]
Seems like this is the right place to poke around, but I've tried the proposed fix and it does not seem to work. With a rotation of 45 degrees, the denominator is something around `2.2e-16`; clamping it to 0.001 or -0.001 depending on its sign will place the labels in a more predictable manner but still very close to the center of the view. I guess that the problem is that the code is trying to recover the "unrotated" width and height from the rotated extents (if I understand the code correctly), but trying to recover the original width / height is numerically unstable when you are close to a rotation of 45 degrees. (E.g., rotating a rectangle of width 300 and height 1 by 45 degrees has almost the same bounding box after rotation as rotating a rectangle of width 1 and height 300).

**Comment by mike-000** [comment]
Calculating the "unrotated" width and height from the frame size and resolution is simpler than trigonometry and avoids random values when results used in division are close to zero https://codesandbox.io/s/k89jiq?file=/main.js

**Comment by ntamas** [comment]
You beat me to it :) I did not check my emails and worked out something more complicated during the night because I did not notice that the resolution is stored in the view state. Thanks for the quick response, it seems to work on my side as well. Looking forward to seeing this in an upcoming release.
