### ISSUE TITLE
Vector tile performance - compared to MapBox

### ISSUE THREAD

**Issue by MortenHofft** [openlayers/openlayers#13414]
I struggle with performance when rendering my vector tile point layers. It isn't terrible at all, but when compared to MapBox there is a notable difference: MapBox (gl 2.7) feels smooth, OpenLayers (6.12) feels a bit more flickering and unresponsive. Edges are jagged when zooming. Tiles slower to show. Are there any settings or similar I can do to improve the performance?

My dream scenario is to use OpenLayers (especially for the projection support), but have as smooth a rendering as MapBox.

Example comparing the two: https://codepen.io/hofft/pen/dyZKezB?editors=0010

Thank you for any help and advice

**Comment by ahocevar** [comment]
Mapbox GL uses a very efficient WebGL renderer, which we cannot beat with OpenLayers's Canvas renderer. You may be able to improve things a bit by configuring the `MapboxVector` layer with `renderMode: 'vector'`. This will result in a bit more lag during panning, but better updates during zooming.

**Comment by MortenHofft** [comment]
Thank you for your quick response. I have a follow up question, feel free to say if this is better directed at StackOverflow.

The examples and API docs mention webgl often e.g. https://openlayers.org/en/latest/examples/webgl-tiles.html

I also notice [ol/layer/WebGLPoints example](https://openlayers.org/en/latest/examples/webgl-points-layer.html) using a GeoJSON - but I'm not having any luck when I try to modify it to use a vector tile source instead. Is webgl support something that is coming? If I'm reading [the docs](https://openlayers.org/en/latest/apidoc/module-ol_layer_WebGLTile-WebGLTileLayer.html) correctly, then it is currently only for raster sources?

**Comment by ahocevar** [comment]
The WebGLPoints layer is for vector sources only, and the WebGLTile layer for tile sources. There is no WebGL based renderer that can render vector tiles.

**Comment by MortenHofft** [comment]
Feel free to close this issue, or leave it open as a feature request for a "WebGL based renderer that can render vector tiles"
