### ISSUE TITLE
How can I edit or rich up the workshop pages?

### ISSUE THREAD

**Issue by onsummer** [openlayers/openlayers#13419]
Thank you for your contribution about the [workshop pages](https://openlayers.org/workshop/), it helps me a lot.

I want to contribute my own language translation, but I do not know how to do, please tell me.

**Comment by ahocevar** [comment]
@onsummer Thanks for willing to contribute! The repository to clone and submit pull requests to is https://github.com/openlayers/workshop. For a new language, create a new subfolder under `src/`, next to `src/en/`. Let me know if you need more help.

**Comment by tschaub** [comment]
If you happened to try out the openlayers/workshop development setup already, you may have had trouble getting non-en languages to build.  https://github.com/openlayers/workshop/pull/136 addresses that.  So now you should be able to `npm install && npm start` after cloning the repo.

**Comment by onsummer** [comment]
@ahocevar @tschaub Thanks! I have fork [openlayers/workshop] and started translation. I'm going to close this issue.
