### ISSUE TITLE
Question: Is it possible to manually set the transform matrix

### ISSUE THREAD

**Issue by MartinPyka** [openlayers/openlayers#13412]
Exploring the map-datastructure I realized that there are datastructures like pixelToCoordinateTransform_ and coordinateToPixelTransform_ which seem to give the transform of pixel coordinates to map-coordinates and vice versa. Is there any way  to set these transforms within my application? I want to align certain pixel coordinates with the map in the background and having control over the transform matrix would certainly give me the most direct way to solve this problem.

**Comment by tschaub** [comment]
> I want to align certain pixel coordinates with the map in the background

Can you provide additional detail on this?

**Comment by MartinPyka** [comment]
what the DragRotateAndZoom-control of OL essentially does is, it transforms the entire map in such a way that the point in the middle and the point below the mouse cursor always point to the same geo location. now I want to do the same programmatically. 
so the input would be
- two points (pixel coordinates and map coordinates)
- two new pixel coordinates

required output:
- view of the map so that the two map coordinates are now at the two new pixel coordinates

if I can control the view of the map via a 2x3 transform matrix, i can figure out the math for myself. the question is therefore: is there a possibility to configure the view of the map via a transform matrix. or is there an even easier way to accomplish this use case?

**Comment by MartinPyka** [comment]
Oh, I just see, I could use the same method, like in the interactor I mentioned: https://github.com/openlayers/openlayers/blob/ab8a16a8a716c6f65b515647b990ef37c73d5ae4/src/ol/interaction/DragRotateAndZoom.js

will give that a try...
