### ISSUE TITLE
openlayer 6.x version is causing error

### ISSUE THREAD

**Issue by mylove10086** [openlayers/openlayers#13425]
hello 
I got an error when I upgraded my code from v5.3.0 to 6.x
When adding a custom map using TileImage, everything works fine with v5.3.0 version of openlayer, but when I update to the latest version 6.x and above everything is different. When zooming the map, the layer keeps shifting in the vertical direction. I found that the value of the first parameter tileCoord of the tileUrlFunction function is not the same as that of v5.3.0, but when I change this value it is the same as that of v5.3.0. The map is not striving to be correct. 
Do you have any good suggestions?
Here is a screenshot of v5.3.0
![1](https://user-images.githubusercontent.com/41406024/155950833-3dc9ba06-0b3e-4081-b18b-eacf700ceb9e.png)
Below is the code

[百度地图2.zip](https://github.com/openlayers/openlayers/files/8151744/2.zip)

**Comment by ahocevar** [comment]
Please see the [v6.0.0 release notes](https://github.com/openlayers/openlayers/releases/tag/v6.0.0). The section "New internal tile coordinates" explains the changes you need to make in your code.
