### ISSUE TITLE
New `getLoadingOrNotReady` method since v6.13 failing when `getRenderer` does not return an object

### ISSUE THREAD

**Issue by rdewit** [openlayers/openlayers#13423]
**Describe the bug**
OL 6.13 introduced a new method `getLoadingOrNotReady` in `PluggableMap` that expects `layer.getRenderer()` to always return an object.

The basic `ol/layer/Layer`, however returns `null`, which causes errors.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/mapbox-layer.html
2. Open dev tools
3. See error

**Expected behavior**
The library either should not expect `layer.getRenderer()` to always return an object or improve the checking in `getLoadingOrNotReady`.

**Comment by ahocevar** [comment]
Thanks @rdewit for this clear bug report. #13424 will fix this issue.

**Comment by rdewit** [comment]
Thank you @ahocevar, for the extremely quick resolution for this!
