### ISSUE TITLE
New getData

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#13422]
In the past we had, for example:

```
map.on('pointermove', function (evt) {
	if (evt.dragging) {
		return;
	}
	const pixel = map.getEventPixel(evt.originalEvent);
	const hit = map.forEachLayerAtPixel(pixel, function (layer) {
		return true;
	});
	map.getTargetElement().style.cursor = hit ? 'pointer' : '';
});
```

Now, because forEachLayerAtPixel will be deprecated, how will you handle the above with getData if there are multiple dynamic layers?  It will now be impossible as you need to loop through all the layers and fire getData on each layer.

**Comment by ahocevar** [comment]
The `layer.forEachLayerAtPixel` method iterates through all layers anyway, and we now also added `map.getAllLayers()` to the API. So the above code would now look like this:
```js
map.on('pointermove', function (evt) {
	if (evt.dragging) {
		return;
	}
	const pixel = map.getEventPixel(evt.originalEvent);
	const hit = map.getAllLayers().some(function (layer) {
		return layer.getData && layer.getData(pixel);
	});
	map.getTargetElement().style.cursor = hit ? 'pointer' : '';
});
```
