### ISSUE TITLE
Unset canvas css causes controls to disappear

### ISSUE THREAD

**Issue by phelanHayes** [openlayers/openlayers#13432]
#13131 
I was not aware of the canvas.style.all = 'unset' rule until version 6.10 changed this to be implemented in css.  For some reason, adding and removing features dynamically to a managed vector layer causes all of the ol controls to disappear.  If I remove this css rule, everything works as expected.  

Is there something specifically I need to implement to work with the all: unset css rule going forward?

Thank you!

**Comment by ahocevar** [comment]
Can you share a reproducible example that shows the issue?

**Comment by phelanHayes** [comment]
> Can you share a reproducible example that shows the issue?

Thank you [ahocevar] for your reply.  I was hoping there was something in ol that might override this class from being applied.  This project uses many other libs that could certainly be causing conflicts.  I will try to reproduce an example.

**Comment by phelanHayes** [comment]
While deconstructing my project in an attempt to reproduce, I found the lib that contained the conflicting css.  I am now using ol 6.13 with no issue.  Thanks again for the quick response!
