### ISSUE TITLE
`interpolate: false` does not stop interpolation

### ISSUE THREAD

**Issue by emlys** [openlayers/openlayers#13448]
Setting `interpolate: false` does not seem to turn off interpolation. The [interpolation example](https://openlayers.org/en/latest/examples/interpolation.html) does not work for me - both maps look the same.

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/43770515/156851247-61f72f8d-0ebd-4162-87da-c8da292f46e2.png">

**To Reproduce**
I copied the `index.html` and `main.js` directly from the interpolation example. I had to add `type="module"` to the line `<script src="main.js" ></script>` to get it to work with vite.

**Expected behavior**
I expect the same results shown on the example page, I would like to display crisp pixel edges when `interpolate: false`.

**Comment by mike-000** [comment]
Are you using v6.10.0 or later? https://github.com/openlayers/openlayers/blob/main/changelog/upgrade-notes.md#new-interpolate-option-for-sources  The previous `imageSmoothing: false` is deprecated but will continue to work until the next major release (v7.0.0)

**Comment by emlys** [comment]
This was my mistake, I thought I had the latest version but I didn't. Thanks and sorry to bother you!
