### ISSUE TITLE
Snap Interaction cannot snap to Point which lies on line segment

### ISSUE THREAD

**Issue by langpavel** [openlayers/openlayers#13440]
**Describe the bug**
When different Point lies on or near to line segment, interaction cannot snap to this point.

**To Reproduce**
Steps to reproduce the behavior ([video](https://user-images.githubusercontent.com/142462/156726272-b950481f-28f6-4465-8f61-79e48f9c1d46.mp4)):
1. Go to [Snap Interaction](https://openlayers.org/en/latest/examples/snap.html)
2. Draw LineString with 2 segments
3. Draw Point snapped on one of segments
4. Try to snap to created Point

**Expected behavior**

Like the vertex on LineString attracts snapping, the Point should attract too.

**Comment by ahocevar** [comment]
Can you share a video of your described procedure? I'm failing to reproduce the problem.

**Comment by langpavel** [comment]
Hi @ahocevar.
I adjusted the repro steps, now it should be clearer.
In addition, one of my colleagues prepared a video.

**Comment by ahocevar** [comment]
Thanks @langpavel, I can reproduce this now. Probably a small logic glitch that when already snapped to an edge, we don't check any more if there's a vertex we could also snap to.

**Comment by langpavel** [comment]
Problem in code is in loop finding closest segment.
Points are represented in Snap interaction as segments with zero length, so when point lies near another segment, point is never matched, becouse segment is alwais closer than point.
I'm trying prepare PR with fix.
