### ISSUE TITLE
Google map tile(s) won't fill in Openlayer v6.12 

### ISSUE THREAD

**Issue by Mujahid-Iqbal** [openlayers/openlayers#13456]
Google base map does not draw correctly. Hybrid shows black background.

![Screenshot from 2022-03-08 13-32-18](https://user-images.githubusercontent.com/96714960/157198511-f6749595-f61c-4531-9c0d-61eb168c06d7.png)
Code:
`const baseMap = new Tile({
      source: new OSM({
        url: 'https://mt{0-3}.google.com/vt/hl=en-US&lyrs=y&x={x}&y={y}&z={z}',
        maxZoom: baseMapsData.maxzoom,
      }),
    });`

**Comment by ahocevar** [comment]
A data issue, not a library issue.

**Comment by Mujahid-Iqbal** [comment]
@ahocevar can you suggest any alternate solution?

**Comment by ahocevar** [comment]
The alternate solution is to not use Google tiles. Also because the way you're using them is probably a violation of their terms of use.
