### ISSUE TITLE
Warning is generated about calling `useGeographic()`, even when `projection` is set in map's `view`

### ISSUE THREAD

**Issue by mossaiby** [openlayers/openlayers#13462]
**Describe the bug**
A warning is generated when I create a map with view's projection set to `EPSG:4326`. Looking at commit https://github.com/openlayers/openlayers/commit/63fc00902faff8c017c600fbd8c1f04791add5d4 I can see that in `View.js` line 404, first the `center` option is checked, and if it is there, a call to `fromUserCoordinate()` is made, which will trigger the warning, before it is disabled in line 410. I suggest moving the block at line 410 to before the one at line 404.

**To Reproduce**
1. Goto https://jsfiddle.net/6038pnvm/5
2. See the generated warning in the console

**Expected behavior**
There should be no warning.

**Comment by ahocevar** [comment]
Thanks for the bug report and the suggestion, @mossaiby. Will be fixed as suggested with #13464.

**Comment by mossaiby** [comment]
You're welcome, @ahocevar!
