### ISSUE TITLE
ol-marker-feature ? is available ?

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#13465]
Hi
As i show this video :  Neues und Unbekanntes in OpenLayers
https://www.youtube.com/watch?v=-NRliSCZBK0&t=1535s
I discovered the ol-marker-feature ? 
Also my question is : where is there a link to this 3rd part-library ?
i can not find here ? https://openlayers.org/3rd-party/

Thanks

**Comment by fredj** [comment]
ol-marker-feature library repository is here: https://github.com/ahocevar/ol-marker-feature

**Comment by jipexu** [comment]
ah ok thanks @fredj .. perhaps it will be useful to add a link in this page ?  https://openlayers.org/3rd-party/

**Comment by fredj** [comment]
it will be added soon ! -> see https://github.com/openlayers/openlayers.github.io/pull/120

**Comment by jipexu** [comment]
thanks
