### ISSUE TITLE
Accept string as valid value for the Color interface

### ISSUE THREAD

**Issue by rbalet** [openlayers/openlayers#13470]
**Describe the bug**
The type `Color` only accept the object as being `number[]` 

**Expected behavior**
Also accept `string`

-> `Color: number[] | string`

**Comment by fredj** [comment]
You can use a string color (CSS color) in every vector style, for example:
```js
const style = new Style({
  fill: new Fill({
    color: '#eeeeee',
  }),
});
```
Do you have a specific use case were it's not possible?

**Comment by rbalet** [comment]
Thx for the quick response

This is the problem I face.
Here, the new Stroke doesn't accept the `color` value because this is a string and he expect a Color.
But if I set `color: Color = '#000'` then it wont work because `Color` expect `number[]`

```typescript
  drawLine(feature: Feature, color: string = '#000') {
    if (!feature) return

    this.lineVectorFeature = feature

    this.lineVectorSource = new VectorSource({
      features: [this.lineVectorFeature],
    })

    this.lineVectorLayer = new VectorLayer({
      source: this.lineVectorSource,
      style: [
        new Style({
          stroke: new Stroke({
            color: color || '#000',
            width: 4,
          }),
        }),
      ],
    })

    this._map.addLayer(this.lineVectorLayer)
    this._map.getView().fit(this.lineVectorSource.getExtent())
 }
```

**Comment by ahocevar** [comment]
The type you're looking for is not `Color`, but `ColorLike`. And that's what `stroke` expects. So
```js
color: ColorLike = '#000'
```
