### ISSUE TITLE
Property 'readGeometryFromNode' in type 'GMLBase' is not assignable to the same property in base type 'XMLFeature'

### ISSUE THREAD

**Issue by rbalet** [openlayers/openlayers#13471]
**Describe the bug**
Got the following error.  
```
Error: node_modules/ol/format/GMLBase.d.ts:243:15 - error TS2416: Property 'readGeometryFromNode' in type 'GMLBase' is not assignable to the same property in base type 'XMLFeature'.
  Type '(node: Element, opt_options?: ReadOptions) => Geometry | Extent' is not assignable to type '(node: Element, opt_options?: ReadOptions) => Geometry'.
    Type 'Geometry | Extent' is not assignable to type 'Geometry'.
      Type 'number[]' is missing the following properties from type 'Geometry': extent_, extentRevision_, simplifiedGeometryMaxMinSquaredTolerance, simplifiedGeometryRevision, and 51 more.

243     protected readGeometryFromNode(node: Element, opt_options?: import("./Feature.js").ReadOptions | undefined): import("../geom/Geometry.js").default | import("../extent.js").Extent;
              
```
**To Reproduce**
Download the following
```
"depdendencies": {
    "ol": "6.13.0",
},
"devDependencies": {
    "@types/arcgis-rest-api": "^10.4.4",
    "@types/topojson-specification": "^1.0.1",
    "@types/geojson": "^7946.0.4",
}
```

**Additional**
I've tried to fix the version ("<s>^</s>10.4.4"), but didn't work neither.

**Comment by alasdair-macleod** [comment]
Also seeing this issue after upgrading to ol 6.13.0, angular 13, typescript 4.5.5

**Comment by rbalet** [comment]
@ahocevar Thx a lot. Could you publish a new version on npm ?

**Comment by MoonE** [comment]
You can use `ol@dev` for the latest version from master.

**Comment by alasdair-macleod** [comment]
Still seeing this error in 6.14.0 & 6.14.1

**Comment by alasdair-macleod** [comment]
Still seeing this error with ol 6.14.0 & 6.14.1

**Comment by ahocevar** [comment]
@alasdair-macleod Make sure `ol` only appears with `6.14.1` in `npm ls ol`. If in doubt, run `npm dedupe ol`.

**Comment by alasdair-macleod** [comment]
Made a minimal(ish) reproduction.

https://github.com/alasdair-macleod/test-ol

Generated a fresh angular project using angular-cli and included ol in package.json, then added this class:

import GML2 from 'ol/format/GML2';

export class TestClass {
  private gml2 = new GML2();

  constructor() {
     this.gml2.readFeatures(undefined);
  }
}
`
build project by running yarn
yarn build or ng build then reproduces the error

**Comment by alasdair-macleod** [comment]
actually, just having the import is sufficient to reproduce this.

import GML2 from 'ol/format/GML2';

**Comment by alasdair-macleod** [comment]
Cool. Thanks again :)
