### ISSUE TITLE
Decouple Label Position from textAlign

### ISSUE THREAD

**Issue by rycgar** [openlayers/openlayers#13481]
# Decouple Label Position from `textAlign`

The [ol/style/Text](https://openlayers.org/en/latest/apidoc/module-ol_style_Text-Text.html) offers the `textAlign` option,
however, `textAlign` also affects the label position. You can see it in this image:

![textAlign-affects-position](https://user-images.githubusercontent.com/51781722/158227779-43265774-c425-42e8-bc1d-beb6eb0c30ff.png)

## Proposal for Point Placement

Separate `textAlign` into two option.
1. `textAlign`: only text alignment. The values stay the same: {`'left'`, `'center'`, `'right'`} (_case: point placement_)
2. `position`: introduce new option with extended values:

### Position Values
- center
- left
- left-top
- top
- right-top
- right
- right-bottom
- bottom
- left-bottom

### Few Position Examples

Few position examples, whereat, text align is set to default value `'center'`.

![label-position-examples](https://user-images.githubusercontent.com/51781722/158227562-01b5be2a-2a2d-4fba-85e2-b2596ab4a5ff.png)

## Contribution

If the proposed API is good enough, I would like to implement the solution and create a pull request. Improvements and/or concerns are welcome too.

**Comment by ahocevar** [comment]
Thanks for the suggestion! i agree the current API lacks positioning options, but this would be a breaking change. I think we could also handle this with a non-breaking change for now. At some point, we have more work to do to consolidate the style API, and when that time has come we should make all breaking changes altogether.

I think a viable solution would be to add a `justify` option. When not set, everything is as it is now, the meaning would be "justify text towards the `textAlign` anchor". When set to `left`, `center` or `right`, text justification within the box aligned by `textAlign` will change. This would also avoid confusion with the (poorly chosen) `textBaseline` option. So the examples you posted in the above image would then be:

* center: `textAlign: "center", textBaseline: "middle"`
* right: `textAlign: "left", textBaseline: "middle", justify: "center"`
* left-top: `textAlign: "right", textBaseline: "bottom", justify: "center"`
* bottom: `textAlign: "center", textBaseline: "top"`

Would this be something you could live with?

**Comment by rycgar** [comment]
For now, I agree on introducing the new option `justify`, because `position` makes less sense in case of `placement: line` and so it requires more discussion.

I will start implementing `justify`, if it is fine for you.
If there are some important things to consider while doing that, please comment.

Some thoughts for later `ol/style` refactorings: since the options differ depending on the `placement`, it might be useful to have two classes for placement, e.g. `ol/style/PointPlacement` and `ol/style/LinePlacement`. They might look like this:


```js
new PointPlacement({
  position: 'top' || 'top-right' || 'right' || 'bottom-right' || 'bottom' || 'bottom-left' || 'left' || 'top-left', 
  textAlign: 'left' || 'center' || 'right',
});

new LinePlacement({
  position: 'start' || 'center' || 'end',
  textAlign,
  textBaseline,
})
```

**Comment by ahocevar** [comment]
Thanks @rycgar. Please go ahead with the implementation and feel free to ask for assistance.

Regarding future: we're going to move away from class-based styles to an object literal based approach. And the goal is to bring it close to the [Mapbox Style specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/).
