### ISSUE TITLE
Proposed Map Event: renderstart

### ISSUE THREAD

**Issue by pkExec** [openlayers/openlayers#13489]
This would complete the already existing "rendercomplete" event, in that it should be fired whenever the map needs a new render, whether that's due to:

- Viewport change
- Layers configuration change
- A layer redraw (for example when using "updateDimensions")
- DOM change
- Any other I might be missing

**Comment by pkExec** [comment]
I think it'll just be syntactic sugar, I can achieve most of the functionality with code similar to this:

            ```
const amILoading=()=>{
                console.log("Map is loading");
                //Do something with it
                this.map.once('rendercomplete', (e)=> {
                    console.log("Finished");
                    //Do something with it
                    this.map.once('precompose',amILoading);
                });
            };
            this.map.once('precompose',amILoading);
```

**Comment by ahocevar** [comment]
What about using the map's `precompose` event?

**Comment by ahocevar** [comment]
If the goal here is to show a loading indicator for missing tiles, images or features, then a useful addition would be a `loadstart`/`loadend` event pair on the map. A `renderstart` event would cause confusion in my opinion, and I think `rendercomplete` is confusing too and might be a candidate for deprecation.

**Comment by ahocevar** [comment]
I have opened a draft pull request, #13491, which adds `loadstart` and `loadend` map events.
