### ISSUE TITLE
setStyle method on Modify interaction

### ISSUE THREAD

**Issue by sdfricke** [openlayers/openlayers#13485]
**Is your feature request related to a problem? Please describe.**
I am trying to find a way to dynamically update the style of the Modify interaction.  I have a default style that I want the modify point to use, but while actively modifying I would like the style to be different than the style when not modifying.

**Describe the solution you'd like**
I would like to be able to call a setStyle method for the modify interaction in the 'modifystart' listener.  Then in the 'modifyend' listener I would call setStyle and change the style back to the default.

**Comment by mike-000** [comment]
The style specified in the constructor is applied to the interaction's overlay layer.  To change it use

`modify.getOverlay().setStyle(newStyle);`

for example https://codesandbox.io/s/modify-features-rn5t8n

**Comment by sdfricke** [comment]
Oh, awesome!  That is what I needed.  Thanks!
