### ISSUE TITLE
Feature.getGeometry returns a Point, not a Geometry

### ISSUE THREAD

**Issue by megapctr** [openlayers/openlayers#13488]
**Describe the bug**
I was working with the [dynamic clusters example](https://openlayers.org/en/latest/examples/clusters-dynamic.html) and I noticed that TypeScript reported an error about the following line:
```js
const centerCoordinates = cluster.getGeometry().getCoordinates();
```
The error was `Property 'getCoordinates' does not exist on type 'Geometry'.`, but this is weird because the code works as expected. After some inspection, it turns out that `getGeometry` returns a `Point`.
I've been using this library for only a couple hours, so it's not clear to me how `Point` and `Geometry` relate to each other, and in turn whether it's a bug or not. But for sure the type annotations need to be improved.

**To Reproduce**
add a `console.log(cluster)` before that line in the linked example and inspect what the types are:

<img width="248" alt="javascript console history showing that Feature#getGeometry() returns a Point" src="https://user-images.githubusercontent.com/4096683/158893791-5759610b-ce2c-45d8-8628-35ccf7e92ae1.png">

**Expected behavior**
The type annotations should match the actual types being used.

**Comment by ahocevar** [comment]
A geometry can either be a `SimpleGeometry` or a `GeometryCollection`. TypeScript is correct, there is no `getCoordinates()` method on a `GeometryCollection`. Before using `getCoordinates()`, make sure you're dealing with an `instanceof SimpleGeomtry`.

**Comment by megapctr** [comment]
thanks!

**Comment by vishalsinghdhami** [comment]
`geometry: (feature) => {
        let coordinates;
        const geometry = feature.getGeometry();
        if (geometry instanceof SimpleGeometry) {
          coordinates = geometry.getCoordinates();
        } else {
          // Handle GeometryCollection or other types if needed
          coordinates = [];
        }}`

**Comment by vishalsinghdhami** [comment]
```let coordinates;
        const geometry = feature.getGeometry();
        if (geometry instanceof SimpleGeometry) {
          coordinates = geometry.getCoordinates();
        } else {
          // Handle GeometryCollection or other types if needed
          coordinates = [];
        `}``````

**Comment by vishalsinghdhami** [comment]
```

import SimpleGeometry from 'ol/geom/SimpleGeometry';

(feature) => {
        let coordinates;
        const geometry = feature.getGeometry();
        if (geometry instanceof SimpleGeometry) {
          coordinates = geometry.getCoordinates();
        } else {
          // Handle GeometryCollection or other types if needed
          coordinates = [];
        }}
```
