### ISSUE TITLE
Documentation for event postcompose wrong

### ISSUE THREAD

**Issue by geraldo** [openlayers/openlayers#13480]
Documentation for event `postcompose` at https://openlayers.org/en/latest/apidoc/module-ol_render_Event-RenderEvent.html#event:postcompose states that:

> Only WebGL layers currently dispatch this event.

But this Event actually is not dispatched by `WebGLTileLayer`, so probably this sentence should be removed.

**Comment by geraldo** [comment]
Sorry, I mixed it up. Actually `postcompose` gets triggered from WebGLTileLayer, but the event is missing at the documentation at the Fires events at https://openlayers.org/en/latest/apidoc/module-ol_layer_WebGLTile-WebGLTileLayer.html

**Comment by ahocevar** [comment]
#13482 should fix this. @geraldo, can you please check if https://deploy-preview-13482--ol-site.netlify.app/apidoc/module-ol_layer_webgltile-webgltilelayer looks as you would expectß
