### ISSUE TITLE
ScaleLine's "nautical" suffix should be in uppercase

### ISSUE THREAD

**Issue by fruchtsalat** [openlayers/openlayers#13497]
**Describe the bug**
The ScaleLine control uses "nm" as suffix for Nautical Miles. However, "nm" is the abbreviation for nanometer.

**To Reproduce**
1. https://openlayers.org/en/latest/examples/scale-line.html
2. Select "nautical mile" and "ScaleLine" from the select elements.

**Expected behavior**
ScaleLine should use "NM" as suffix for Nautical Miles.

**Comment by jipexu** [comment]
Yes NM should be better :
ol/control/ScaleLine.js
line 292

**Comment by ahocevar** [comment]
Fixed with #13554
