### ISSUE TITLE
transformExtent doesnt convert coordinates correctly from ESPG:5514 to ESPG:3857

### ISSUE THREAD

**Issue by ersi77** [openlayers/openlayers#13503]
```
this.map().setView(new View({
  projection: 'EPSG:3857',
  center: fromLonLat([50.075710, 14.472606]),
  zoom: 10,
  enableRotation: false
}))
extent = transformExtent(extent, 'EPSG:5514', this.map().getView().getProjection().getCode())
this.map().getView().fit(extent)
```
Im having problem with mapview zooming out a bit on every website refresh, it seems like transformExtent doesnt convert coordinates correctly

my coordinates in ESPG:5514

-1703543.6824992644
-649373.7717948385
-1702696.1524791967
-648498.8826321261
coordinates that I get from transformExtent from ESPG:5514 to ESPG:3857

-17013.595185768834
6712287.035442345
-15271.234295750599
6714060.781263472
coordinates that I get from epsg.io online converter of coordinates

-16528.31
6712365.39
-15713.53
6714139.10

any tips how to fix this?

**Comment by ahocevar** [comment]
How did you specify the EPSG:5514 projection?

**Comment by ersi77** [comment]
sorry I misunderstood the problem
my problem is with map.getview.fit
here is my code and here are the returned values
coordinates after view.fit are a bit different 

`const transformedExtent = transformExtent(extent, 'EPSG:5514', this.map().getView().getProjection().getCode())
console.log(transformedExtent)
this.map().getView().fit(transformedExtent, this.map().getSize())
console.log(this.map().getView().calculateExtent(this.map().getSize()))`

before fit:
0: -27186.072153485078
1: 6701982.491006854
2: -5136.804165771885
3: 6724373.669054876

after fit:
0: -27186.072153485078
1: 6701493.775314425
2: -5136.804165771886
3: 6724862.384747305

**Comment by ahocevar** [comment]
Ok. That's expected.
