### ISSUE TITLE
WARN: Bundling with parcel 2.4.0 will produce Uncaught SyntaxError

### ISSUE THREAD

**Issue by lorenzogrv** [openlayers/openlayers#13518]
**Describe the bug**
After building a project depending on latest version, with parcel v2.4.0, the bundle contains invalid JavaScript code which will produce `Uncaught SyntaxError: function statement requires a name`

**Workaround**: Downgrade to parcel 2.3.x

Please see <https://github.com/parcel-bundler/parcel/issues/7872>

**Comment by PeteDevoy** [comment]
For me it was the way Parcel 2.4 was bundling the CSS from `import ol/ol.css`.

Downgrade to 2.3 fixed for me too.

**Comment by lorenzogrv** [comment]
Issue has been fixed on [parcel@2.4.1](https://github.com/parcel-bundler/parcel/releases/tag/v2.4.1), also works well with v2.5.0.

Will close
