### ISSUE TITLE
GeoTIFF AggregateError Error

### ISSUE THREAD

**Issue by Rskut** [openlayers/openlayers#13519]
My console is getting spammed with the following Error, if I add a GeoTIFF.

> Uncaught (in promise) AggregateError: Request failed
>     at BlockedSource.fetch (blockedsource.js?df9a:155:1)
>     at async GeoTIFFImage.getTileOrStrip (geotiffimage.js?6f70:384:1)

	
I'm not sure if I do something wrong, however I can see the GeoTIFF, so nothing seems to be wrong.

Before I add any GeoTIFF to the Map, I do several translations with gdal:

```
//Translate to EPSG:3857
gdalwarp
	-t_srs,
	EPSG:3857,
	-r,
	near,
	-of,
	GTiff,
	INPUT,
	OUTPUT
```
	
```
//Create COG
gdal_translate
	INPUT,
	OUTPUT,
	-co,
	TILED=YES,
	-co,
	COPY_SRC_OVERVIEWS=NO,
	-co,
	COMPRESS=DEFLATE
```

```
//Add Overviews
gdaladdo 
	INPUT,
```
	
```
Openlayers TIFF-Source:
const source = new GeoTIFF({
		sources: [
			{
				url: getFileRefUrl(path.value) || '',
			},
		],
	});
```

**Comment by ahocevar** [comment]
What is the url you pass to the GeoTIFF source? I don't see the `getFileRefUrl()` definition in your snippet.

**Comment by ahocevar** [comment]
And are you sure your range request support in the above is correct? To rule out various sources of problems, I'd

* try with geotiff.js directly (without OpenLayers)
* upload the GeoTIFF to an S3 storage or similar, with built in range request support.
