### ISSUE TITLE
Layers are not rendered when the map comes back from a popup window asynchronously.

### ISSUE THREAD

**Issue by NoriSte** [openlayers/openlayers#13525]
**Describe the bug**
The map renders nothing when is moved back **asynchronously** after closing a popup window.

**To Reproduce**
1. Go to the ["External map" example](https://openlayers.org/en/latest/examples/external-map.html)
2. Open it in CodeSandbox
3. Modify the `main.js`'s `resetMapTarget` file as following
```diff
-map.setTarget(localMapTarget);
+setTimeout(() => map.setTarget(localMapTarget), 1000);
```
_Or start directly from [this sandbox](https://codesandbox.io/s/external-map-bug-p4n3mv?file=/main.js) that already includes the above steps_

4. Click the  "Open external map" button rendered in the app
<img width="1115" alt="Screenshot 2022-03-30 at 09 42 49" src="https://user-images.githubusercontent.com/173663/160779977-c13b2f75-de48-44c8-a665-4863f515c793.png">

5. Wait for the map to be loaded in the popup
6. Close the popup
7. Wait for a second
8. The map is brought back in the main window, but empty
<img width="1114" alt="Screenshot 2022-03-30 at 09 43 21" src="https://user-images.githubusercontent.com/173663/160779935-291a717e-7335-42f7-bf91-74a9d4d3e9fc.png">

Please note that the map "is working" because by dragging it, new tiles are loaded (in the next screenshot I have the DevTools's network opened that shows the new tiles loaded after dragging the map)

<img width="1283" alt="Screenshot 2022-03-30 at 09 43 47" src="https://user-images.githubusercontent.com/173663/160780304-6fb0da64-9940-487f-a80d-3168833aea65.png">

**Expected behavior**
I expect the map to correctly render all the layers instead of showing empty.

Thanks for the hard work.\Stefano

**Comment by MoonE** [comment]
To me it looks like a bug in Chromium as It works fine in Firefox. 
The canvas is there and the draw calls for the tiles seem to be executed, but the canvas is not refreshed on the screen.

It works if you force recreation of the layer canvases when setting the target:
```js
  setTimeout(() => {
    map.setTarget(localMapTarget);
    // hasRenderer, getRenderer are not in the api, but this should work as a workaround.
    map.getAllLayers().forEach(function (l) {
      if (l.hasRenderer()) {
        l.getRenderer().container = null;
      }
    });
  }, 1000);
```

**Comment by NoriSte** [comment]
First of all, sorry not to mention the browser and not to test it on different browsers...

Then, thanks a lot for the suggested solution, really appreciated it!
