### ISSUE TITLE
olMap.on no longer missing typedef doe keyboard events

### ISSUE THREAD

**Issue by alasdair-macleod** [openlayers/openlayers#13522]
After upgrading to ol 6 (6.13.0 to be precise) the olMap.on method no longer accepts keydown events:
I now see the following error:

  The last overload gave the following error.
    Argument of type 'string' is not assignable to parameter of type '("error" | "change" | "click" | "dblclick" | "pointermove" | "propertychange" | "postrender" | "precompose" | "postcompose" | "rendercomplete" | "singleclick" | "pointerdrag" | ... 5 more ... | "change:view")[]'.

711     this.olMap.on('keydown', (event: MapBrowserEvent<KeyboardEvent>)

**Expected behavior**
I expect this function to recognise keyboard events and that this is probably a missing type definition somewhere?

Thanks

Alasdair Macleod

**Comment by ahocevar** [comment]
There is no `keydown` event on `ol/Map`. If you want to handle `keydown` events, you should listen to the DOM event, e.g.
```js
map.getTargetElement().addEventListener('keydown', onkeydown);
```

**Comment by alasdair-macleod** [comment]
Thanks again
