### ISSUE TITLE
WebGlTile in a group => opacity of group ignored (Tile are always 100% opacity)

### ISSUE THREAD

**Issue by jcarbou** [openlayers/openlayers#13524]
May be this bug is fix by https://github.com/openlayers/openlayers/issues/13507

See https://codesandbox.io/s/wms-image-custom-proj-forked-dfc1vm?file=/main.js

The map contains a single layer of type Group (ol/layer/Group).
The group contains a single layer of type WebGlTile (ol/layer/WebGlTile ).

After 3 seconds the code change the opacity of the group (from 1 to 0.5)

=> The WebGlTile layer has still opacity to 100% !

Note : If I change the type of the layer from WebGlTile to Tile (ol/layer/Tile), the layer opacity is well apply. The issue is only for WebGlTile

**Comment by mike-000** [comment]
It is working with 6.14.1 https://codesandbox.io/s/wms-image-custom-proj-forked-67ox89

**Comment by tschaub** [comment]
Fixed by #13509
