### ISSUE TITLE
Interaction longer recognises drawstart drawend events

### ISSUE THREAD

**Issue by alasdair-macleod** [openlayers/openlayers#13523]
**Describe the bug**
since upgrading to openlayers 6 (6.13.0) Interaction longer recognises drawstart or drawend events

In the error messages below, this.currentInteraction is an instance of Interaction. 

  Overload 1 of 3, '(type: EventTypes, listener: (event: BaseEvent) => unknown): void', gave the following error.
    Argument of type '"drawstart"' is not assignable to parameter of type 'EventTypes'.
  Overload 2 of 3, '(type: "propertychange" | "change:active", listener: (event: ObjectEvent) => unknown): void', gave the following error.
    Argument of type '"drawstart"' is not assignable to parameter of type '"propertychange" | "change:active"'.
  Overload 3 of 3, '(type: (EventTypes | "propertychange" | "change:active")[], listener: (event: Event | BaseEvent) => unknown): void', gave the following error.
    Argument of type 'string' is not assignable to parameter of type '(EventTypes | "propertychange" | "change:active")[]'.

443       fn => this.currentInteraction!.un('drawstart', fn),

  Overload 1 of 3, '(type: EventTypes, listener: (event: BaseEvent) => unknown): EventsKey', gave the following error.
    Argument of type '"drawend"' is not assignable to parameter of type 'EventTypes'.
  Overload 2 of 3, '(type: "propertychange" | "change:active", listener: (event: ObjectEvent) => unknown): EventsKey', gave the following error.
    Argument of type '"drawend"' is not assignable to parameter of type '"propertychange" | "change:active"'.
  Overload 3 of 3, '(type: (EventTypes | "propertychange" | "change:active")[], listener: (event: Event | BaseEvent) => unknown): EventsKey[]', gave the following error.
    Argument of type 'string' is not assignable to parameter of type '(EventTypes | "propertychange" | "change:active")[]'.

457       fn => this.currentInteraction!.on('drawend', fn),

**Expected behavior**
Is this a missing type definition or is there something I've missed int the update notes?

Thanks

Alasdair Macleod

**Comment by ahocevar** [comment]
Type checks are stricter now. Since `drawstart` and `drawend` are specific to `ol/interaction/Draw`, your `this.currentInteraction` should be typed `ol/interaction/Draw`, and not `ol/interaction/Interaction`.

**Comment by alasdair-macleod** [comment]
Thanks, as always, for the feedback.
