### ISSUE TITLE
COG trouble with non-square pixels

### ISSUE THREAD

**Issue by m-mohr** [openlayers/openlayers#13573]
**Describe the bug**
I'm loading a COG, but only the upper part is shown.

**To Reproduce**
1. Go to https://codesandbox.io/s/cog-forked-x0mxoc?file=/main.js (this is the cog example from openlayers just with a different URL)

**Expected behavior**
It should show completely, like in e.g. geotiff.io or QGIS:
![image](https://user-images.githubusercontent.com/8262166/163389009-97e39811-1233-437e-947c-065c1f997e6b.png)

**Comment by M393** [comment]
Looks like the pixel scale meta data is not correctly applied.
https://exiftool.org/TagNames/EXIF.html <- 0x830e
![image](https://user-images.githubusercontent.com/56256405/163393400-803b13ed-f2e6-4afd-b174-74a0dabde740.png)

Add an osm layer to see that the image is incorrectly stretched:
```js
import OSM from "ol/source/OSM";

// ...

  layers: [
    new TileLayer({
      source: new OSM()
    }),
    new TileLayer({
      source: source
    })
  ],
```

**Comment by m-mohr** [comment]
@M393: Yes, indeed, if I do that in OpenLayers, the image is not located correctly. In QGIS and geotiff.io it is correctly located though:
![image](https://user-images.githubusercontent.com/8262166/163394901-4df498f5-ab32-4877-84ea-2b60b41dbf2c.png)

So is this an error in OL? Or is this a poorly generated COG and the other tools are more tolerant/robust?

**Comment by tschaub** [comment]
I haven’t checked the metadata, but are these non-square pixels (x resolution different from y resolution)?

it is a current known limitation that OpenLayers requires square pixels for all raster types (not only GeoTIFF).  See also https://github.com/openlayers/openlayers/issues/13053#issuecomment-983125589

**Comment by m-mohr** [comment]
Looks like the pixels are indeed non-square.

**Comment by tschaub** [comment]
@m-mohr - I agree we can improve the situation here.  If we can't resample or otherwise work with non-square pixels, we could make the error known.

**Comment by tschaub** [comment]
@m-mohr - Do you still have that example data handy?  It looks like geotiff.io doesn't work with https://demo.nextgis.com/api/resource/5511/cog (the non-square data mentioned in #13053).  I'd be curious to see non-square pixels working on geotiff.io.

**Comment by m-mohr** [comment]
No, not at the moment. The server is currently offline, I hope they fix that over the weekend.

**Comment by m-mohr** [comment]
@tschaub Here's a new signed link to the example file: https://openeo.vito.be/openeo/1.1/jobs/552e3e33-4fe0-42ca-b93c-7f1cd3a91224/results/assets/MjUyNTRjNGRiMTkzMGNhNzQwNjg0OTJmM2NhOWIyZjM0N2JhMWU3ZTI0ZTAzY2U0OTMzOTlmZWE1NmVhOTQzN0BlZ2kuZXU%3D/08f1bfaeeaa18448c3e02ca1d16cc5a8/openEO.tif?expires=1651313745
