### ISSUE TITLE
How to get more zoom levels than XYZ source supports?

### ISSUE THREAD

**Issue by kalucky0** [openlayers/openlayers#13576]
I have a XYZ tile source that supports only zoom levels between 13 and 16. I would like to increase that to at least 14-17. Leaflet has [LimitZoom and ContinuousZoom](https://zverik.github.io/Leaflet.LimitZoom/) which can help achieve that, but how can I do this using OpenLayers 6.14.1?

My current code:

```js
let map = new ol.Map({
    target: 'map',
    layers: [
        new ol.layer.Tile({
            source: new ol.source.XYZ({
                url: '...',
            }),
        })
    ],
    view: new ol.View({
        center: ol.proj.fromLonLat([-87.33, 79.49]),
        zoom: 13,
        minZoom: 13,
        maxZoom: 16,
    })
});
```

**Comment by ahocevar** [comment]
All you have to do is configure the XYZ source with `minZoom: 13` and `maxZoom: 16`. No need to configure anything on the view.

**Comment by kalucky0** [comment]
That works. Thanks.
