### ISSUE TITLE
iphone11ProMax ios15.4.1  Error rendering MVT

### ISSUE THREAD

**Issue by jak983464779** [openlayers/openlayers#13585]
**TypeError: null is not an object (evaluating 'context.scale') /common.js:133248:14 draw_**
**Uncaught (in promise)  Object {name: "TypeError",message: "null is not an object (evaluating 'ctx.fillStyle = 'rgba(0,0,0,0)'')"**
**stack: "getBlankImage@http://172.20.10.2:8080/common.js:54943:6\nhandleImageError_**
**TypeError: null is not an object (evaluating 'context.scale') /common.js**
**TypeError: null is not an object (evaluating 'context.canvas') **

**Comment by ahocevar** [comment]
Does your map have many layers? This could be the problem. iOS has very strict canvas memory limits, so i usually only works with a maximum of 2 or 3 layers.

**Comment by jak983464779** [comment]
What's the maximum memory on ios? Can errors be avoided by setting pixelRatio and cacheSize？

**Comment by jak983464779** [comment]
There are now six MVT layers and one WMTS layer, I will continue to add layers for further consideration。Do you have any good optimization tips?

**Comment by ahocevar** [comment]
Not setting a `cacheSize` (i.e. using the bare minimum), not setting an opacity on layers and using `renderMode: 'vector'` on `VectorTile` layers usually helps.

See https://twitter.com/rikschennink/status/1442443774748082185 for an interesting thread about canvas and memory size.

**Comment by jak983464779** [comment]
Ok, thank you very much
