### ISSUE TITLE
Missing extent for MVT VectorTileLayer?

### ISSUE THREAD

**Issue by capooti** [openlayers/openlayers#13592]
**Describe the bug**

I have a few MVT layers in my OpenLayers map, and everything seems to work well. However their initial extent seems not being set. MVT layers are from TiMVT.

**To Reproduce**

This is how I create a layer:

```
const vectorTileLayer = new VectorTileLayer({
    source: new VectorTile({
      format: new MVT(),
      url: url,
      tileLoadFunction: tileLoader,
    }),
    visible: isVisibleByDefault,
  });
```

At this point, the extent is undefined:

// here vectorTileLayer.getExtent() returns undefined

As the layers are behind oauth - that is why I am using tileLoadFunction, to set the token - is it my responsibility to set the initial extent in such a case?

**Expected behavior**

Not sure if this is a bug or just depends by having the MVT server behind oauth.

**Comment by ahocevar** [comment]
A layer never sets its extent automatically. You'd have to configure it manually, if you want to restrict the layer's extent. This is not specific to vector tile layers. Also note that this is the extent that the layer will be clipped to, not the displayed extent of the map. If you want to know that, you'd have to do something like
```js
map.getView().calculateExtent();
```

**Comment by capooti** [comment]
@ahocevar thanks a lot for your great and quick answer, as usual.

Good to know that we manually have to set the extent in OpenLayers. At the end what I did was to query the MVT api endpoint of the layer (tilejson.json) and get the extent from there.

This is obviously not a bug, so closing it, many thanks again!
