### ISSUE TITLE
GeoTIFF not working with legacy build

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13606]
**Describe the bug**
GeoTIFFs are not working with legacy build since v6.13.0.

**To Reproduce**
Open simple example in https://jsbin.com/xomuhus/edit?html,js,output It works with version 6.12. Change `v6.12.0/build/ol.js` to a later release and observe the error in the console.

**Expected behavior**
Legacy build on latest browsers (I was using Chrome 100 and 101 and Edge 100) should support API methods.

**Comment by ahocevar** [comment]
Ok, a chunk loading problem. We've had that before. Need to check what's going on here.

**Comment by ahocevar** [comment]
It turns out this is not a problem with the legacy build, but with jsdelivr.net. The requests for the dynamic import chunks (e.g. https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.14.1/build/231.ol.js) return a 403 with

> Package size exceeded the configured limit of 50 MB. Try https://github.com/openlayers/openlayers.github.io/tree/master/en/v6.14.1/build/231.ol.js instead.

If you copy the legacy build to your local server, it should work fine.

**Comment by mike-000** [comment]
Same problem.  I do have `ol.js` but not `231.ol.js`  Why would the application expect worker script to be created on the server?
![image](https://user-images.githubusercontent.com/49240900/165482383-c15dd41e-08ad-4b97-b597-15af9bfb0f1d.png)

**Comment by ahocevar** [comment]
Oh, I see our scripts that create ol-dist.zip and ol.zip for the releases do not include these extra chunks indeed. I created https://github.com/openlayers/openlayers.github.io/issues/124 for this.

**Comment by ahocevar** [comment]
Release artifacts on https://github.com/openlayers/openlayers/releases/tag/v6.14.1 are updated and now include the dynamic chunks.

**Comment by ahocevar** [comment]
The other reported problem here is https://github.com/openlayers/openlayers.github.io/issues/113.

**Comment by ahocevar** [comment]
Redeployed v6.14.1, works now from cdn.
