### ISSUE TITLE
Calling setStyle in WebGLTile results in source channel loss

### ISSUE THREAD

**Issue by chaichontat** [openlayers/openlayers#13622]
**Describe the bug**
Setting `style` after but not during `WebGLTile` instantiation results in the layer ignoring channels >4.

**To Reproduce**
This is an example with two 3-color COGs
https://codesandbox.io/s/wonderful-driscoll-9g84lc?file=/index.js

**Expected behavior**
All channels should still be available. Example included in the MRE.

**Comment by chaichontat** [comment]
Fixed MRE.

**Comment by lubojr** [comment]
Looking at the sandox this symptom has been already fixed somewhere between OL9 and OL10 (updating the version in the sandbox between 9.0.0 and 10.0.0 removes the issue)

**Comment by ahocevar** [comment]
Thanks for the update, @lubojr. So I'm closing this.
