### ISSUE TITLE
transform fails for three-dimensional coordinates

### ISSUE THREAD

**Issue by Sec42** [openlayers/openlayers#13624]
**Describe the bug**
If you use ol.proj.transform with three-dimensional coordinates, it produces incorrect results.  

**To Reproduce**

    proj4.defs("EPSG:4978:gc", "+proj=geocent +datum=WGS84 +ellps=WGS84 +units=m +no_defs");
    proj4.defs("EPSG:4978:my", "+proj=longlat +datum=WGS84 +ellps=WGS84 +no_defs");

    ol.proj.proj4.register(proj4);

    const p_xyz = new ol.proj.Projection({
      code: 'EPSG:4978:gc',
      extent: [-170.0, -80.0, 170.0, 80.0]
    });
    const p_lla = new ol.proj.Projection({
      code: 'EPSG:4978:my',
      extent: [-170.0, -80.0, 170.0, 80.0]
    });

    ptxyz=[ 5584000, 2844000, 3448000 ];
    console.log("source",ptxyz);

    pt_o=new ol.proj.transform(ptxyz, p_xyz, p_lla);
    console.log("openlayers",pt_o);

    pt_4=proj4("EPSG:4978:gc","EPSG:4978:my",ptxyz);
    console.log("proj4",pt_4)

**Output**

    source Array(3) [ 5584000, 2844000, 3448000 ]
    openlayers Array(3) [ 26.990304649234826, 0, 3448000 ]
    proj4 Array(3) [ 26.990304649234826, 28.965718227798618, 779337.8584198505 ]

**Expected behavior**

Same result for ol.proj.transform() as for proj4()

**Comment by mike-000** [comment]
It is proj4 which does not take 3d coordinates - if you try `pt_4=proj4("EPSG:4978:gc","EPSG:4978:my",ptxyz.slice(0,2));` you get the same result as OpenLayers.

**Comment by Sec42** [comment]
While it is nice to be able to reproduce the broken output with proj4, I'm not sure it helps with this issue.

I found https://github.com/openlayers/openlayers/issues/2879 which references https://github.com/openlayers/openlayers/pull/2887 which looks to me like it should work with three dimensions in openlayers.

**Comment by mike-000** [comment]
`ol.proj.transform` will accept more than 2 dimensions, but it does not do the transforming itself, the first  XY pair is passed to the appropriate transform function for the projections https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.addCoordinateTransforms which expect only 2 dimensions.  Changing that would be a breaking change as custom functions not based on proj4 could be using `.reverse()` to swap the axis order.

**Comment by Sec42** [comment]
Maybe I'm missing something, but those functions would still work as long as you only pass 2 dimensions. And seeing that they do not work correctly when passing three dimensions currently anyway, what's the issue with just passing what the user specified?

Even if you think that to be problematic & want to keep old behaviour for custom transforms, it should be possible to behave properly for proj4-based projections?

**Comment by mike-000** [comment]
OpenLayers already allows XYZ, XYM and XYZM layouts.  Only the X and Y part is passed to the transform functions.  The specification could change at a major release, or new transform3d methods could be added for ol.proj and geometries so the user explicitly requests 3 dimensions are used.

**Comment by ahocevar** [comment]
I don't agree that fixing this would be a breaking change. The transform function knows the number of coordinates passed to it, so it can make decisions based on it. I'm going to create a pull request with a fix.

**Comment by mike-000** [comment]
> I don't agree that fixing this would be a breaking change. The underlying transform function knows the number of coordinates passed to it, so it can make decisions based on it. I'm going to create a pull request with a fix.

Yes, they can check the number passed, but existing functions do not need to, so this would break if used with XYZ or XYM geometry:

```
addCoordinateTransforms(
    'EPSG:4326',
    projLatLon,
    function(coordinate) { return coordinate.reverse(); },
    function(coordinate) { return coordinate.reverse(); }
);
```

**Comment by ahocevar** [comment]
@mike-000 The above will fail in these cases, yes. But I think this can be seen as a bug fix, not as a breaking change. I'll ad a note in the changelog.

**Comment by Sec42** [comment]
Thank you very much for this fix. I'm looking forward to test it in the next tagged version.

**Comment by ahocevar** [comment]
@Sec42 You can already try it now with `npm install ol@dev`.

**Comment by Sec42** [comment]
Thanks for the pointer. Haven't used `npm` at all so far. Will try on the weekend.

**Comment by mike-000** [comment]
Pull requests also produce a preview of the legacy build, which can be copied or linked for testing https://jsbin.com/nepavid/edit?html,console,output
