### ISSUE TITLE
Icon tooltip

### ISSUE THREAD

**Issue by geraldo** [openlayers/openlayers#13635]
Would be great to have a parameter to add browser tooltips that appear on icon hover. For sure you always can make a tooltip, but this is more work. An easy usable icon title would also be great for accessibility. I imagine something similar as [Leaflet marker title](https://leafletjs.com/reference.html#marker-title).

**Comment by mike-000** [comment]
You could do it via the style when hovering over icons or anything else which hit detects https://codesandbox.io/s/select-hover-features-forked-x9u9oy?file=/main.js

**Comment by geraldo** [comment]
Ok, thanks for your hints to create the tooltips with plain styles, till now I always did it using html divs. Even this is quite more work than adding a simple title parameter, it gives you a lot of control of the output. Here a test with icons: https://codesandbox.io/s/icon-forked-bztbzn?file=/main.js
