### ISSUE TITLE
RGB COG with float values not shown?

### ISSUE THREAD

**Issue by m-mohr** [openlayers/openlayers#13639]
**Describe the bug**
It looks like COGs that contain floats can not always be rendered correctly (at least it is the only difference I see right now to COGs that work for me and contain ints).

**To Reproduce**
1. Go to https://codesandbox.io/s/cog-forked-pt8yxd?file=/main.js
2. It doesn't show anything. I also can't get pixel values on pointer move.

**Expected behavior**
I'd expect to render similarly to what QGIS shows for the same COG with the same min/max values:
![image](https://user-images.githubusercontent.com/8262166/166424546-9ebd0125-dac9-4d5b-a6ea-55572a3e2199.png)

**Comment by mike-000** [comment]
It may be a problem with the tile grid.  https://codesandbox.io/s/cog-forked-wptn6m?file=/main.js  There is only 1 zoom level and I would not expect so many tiles at level 0.

**Comment by m-mohr** [comment]
@mike-000 Are you saying that I should generate the COG differently (e.g. multiple zoom levels?) or that this looks like an issue in OL?

**Comment by mike-000** [comment]
Tiles were being requested but going the `TileState.ERROR`, as geotiff.js is throwing an error which can be logged by adding `.catch` to the code https://codesandbox.io/s/cog-forked-nhb37m?file=/main.js  Not sure if that is due to the data or the requests being invalid.

**Comment by m-mohr** [comment]
Interesting, it says "Unsupported data format/bitsPerSample". I'll try to check why this might be thrown...

**Comment by m-mohr** [comment]
The error occurs in geotiffimage.js, function arrayForType. The arguments passed are format = undefined, bitsPerSample = undefined, size = 65536. So it's weird that the values are undefined.

The undefined values originate from getArrayForSample, where for the sampleIndex'es 0 and 1 it tries to read from the fileDirectory, but only 0 is defined in there.

If I change two functions slightly in geotiffimage.js, it at least doesn't throw the error any more, but not so sure whether it is meaningful:

```js


  getSampleFormat(sampleIndex = 0) {
    if (!this.fileDirectory.SampleFormat || this.fileDirectory.SampleFormat.length === 0) {
      return 1;
    }

    return typeof this.fileDirectory.SampleFormat[sampleIndex] !== 'undefined'
      ? this.fileDirectory.SampleFormat[sampleIndex] : this.fileDirectory.SampleFormat[0];
  }

  getBitsPerSample(sampleIndex = 0) {
    if (!this.fileDirectory.BitsPerSample || this.fileDirectory.BitsPerSample.length === 0) {
      return;
    }

    return typeof this.fileDirectory.BitsPerSample[sampleIndex] !== 'undefined'
      ? this.fileDirectory.BitsPerSample[sampleIndex] : this.fileDirectory.BitsPerSample[0];
  }
```

**Comment by m-mohr** [comment]
Closing as this seems to be either in scope for geotiff.js or for the COG generator. Thanks for the help from mike.
