### ISSUE TITLE
how to make an ol.style.Text clickable?

### ISSUE THREAD

**Issue by scil** [openlayers/openlayers#13638]
I have a style.Text with ol.geom.Point.

How could I click the text and run some code?

```
<script>

    let labelStyle = new ol.style.Style({
        text: new ol.style.Text({
            font: 'bold 20px serif',
            text: 'here',
            fill: new ol.style.Fill({
                color: 'rgba(255, 0, 0, 1)'
            })
        })
    });

    let vectorSource = new ol.source.Vector();

    let vectorLayer = new ol.layer.Vector({
        source: vectorSource
    });

    let labelFeature = new ol.Feature({
        geometry: new ol.geom.Point([12956325, 4851028])
    });

    labelFeature.setStyle(labelStyle);

    vectorSource.addFeature(labelFeature);
    let map = new ol.Map({
        target: 'map', 
        layers: [

            new ol.layer.Tile({  
                source: new ol.source.OSM()  
            }),

            vectorLayer
        ],
        view: ...
    });
</script>
```

**Comment by scil** [comment]
I tried a normal text, sometimes it's clickable, sometimes not.

I trid an icon font to display an triangle, it's not clickable always.

**Comment by M393** [comment]
Your example doesn't include the hit detection, so it's hard to say what may be the problem.
Here is an example with working hitdetection: 
https://openlayers.org/en/latest/examples/icon.html
You may click the `Edit` button at the top-right to reproduce your problem and share the link with us here.

**Comment by scil** [comment]
> Your example doesn't include the hit detection, so it's hard to say what may be the problem. 

Thank you.  But I did not use events on map. I am using `ol.interaction.Select`

**Comment by mike-000** [comment]
If you need to see that you have selected text you would need to use style functions so the same text is displayed when selected and not selected https://codesandbox.io/s/street-labels-forked-0icpnj?file=/main.js
