### ISSUE TITLE
index.js should match shape of global ol

### ISSUE THREAD

**Issue by JoshMcCullough** [openlayers/openlayers#13646]
`src/ol/index.js` does not match the shape of what result from importing `ol` directly via a script tag. For instance, `ol.proj` is not exported from `index.js`. This is an issue when re-packaging ol within another library for ingestion directly in the browser. Also there is no global ol definition available (which again defines the shape of the global `ol` object).

**To Reproduce**
```js
import * as ol from 'ol';

window.ol = ol;

window.ol.proj.get('...'); // throws error because `proj` does not exist on `ol`.
```

**Expected behavior**
`import * as ol from 'ol'` should match the shape of:

```html
<script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.14.1/build/ol.js"></script>
```

Alternatively, provide another entry point which matches the global `ol` variable's shape, e.g. `import * as ol from 'ol/global'`. Currently, I need to write my own `olGlobal` constant which exports the parts of `ol` that I need to embed.

**Comment by ahocevar** [comment]
Unfortunately, this would make it impossible for bundlers to achieve good tree-shaking. The closest you can get in your application is something like this:
```js
import * as ol from 'ol';
import * as layer from 'ol/layer';
import * as source from 'ol/source';
import * as proj from 'ol/proj';
// and so on

ol.layer = layer;
ol.source = source;
ol.proj = proj;
```
But this would cause un unnecessarily big build size of your application, for the same reason. So if you need a standalone build of OpenLayers, building the global object with only what you need is recommended. Like this:

https://github.com/phpmyadmin/phpmyadmin/blob/9550066810cdcc63ae8cac2055fc5e9e896caba7/js/src/ol.mjs

**Comment by JoshMcCullough** [comment]
Okay, that is essentially what I'm doing now (bundling what we need only).

I'm not sure I understand how having e.g. an `ol/global.js` which matches the shape of the global variable would be any different (size-wise) than pulling all of ol via a script tag, though. (Assuming it's been run through a minifier, etc.)

**Comment by ahocevar** [comment]
You're right, that would be the same. But we decided to keep the full build out of the `ol` package, to avoid users complaining about the huge file size, and encouraging the approach you're following.
