### ISSUE TITLE
Prototype Pollution (minimist < 1.2.6) vulnerability

### ISSUE THREAD

**Issue by manzolo** [openlayers/openlayers#13642]
The [minimist](https://www.npmjs.com/package/minimist) package is affected by vulnerability:
https://security.snyk.io/vuln/SNYK-JS-MINIMIST-2429795

└─ ol@npm:6.14.1
   └─ ol-mapbox-style@npm:7.1.1 (via npm:^7.1.1)

└─ ol-mapbox-style@npm:7.1.1
   └─ @mapbox/mapbox-gl-style-spec@npm:13.23.1 (via npm:^13.20.1)

├─ @mapbox/mapbox-gl-style-spec@npm:13.23.1
│  └─ minimist@npm:1.2.5 (via npm:^1.2.5)

is it possible to upgrade it?

**Comment by ahocevar** [comment]
Please use the latest (`npm install ol@dev`). We're constantly keeping our dependencies up to date.

**Comment by ahocevar** [comment]
Tagged releases in the `latest` channel run the same automated tests as the releases in the `dev` channel. So yes, it's safe to use those in production.

**Comment by tschaub** [comment]
Closing as fixed by #13501.
