### ISSUE TITLE
Draw shapes example don't work with parcel

### ISSUE THREAD

**Issue by arekgotfryd** [openlayers/openlayers#13651]
**Describe the bug**
Currently if I copy code from below example 
[https://openlayers.org/en/latest/examples/draw-shapes.html](https://openlayers.org/en/latest/examples/draw-shapes.html)
and set it up to run locally on my machine I would get following error

🚨 Build failed.

@parcel/transformer-js: Browser scripts cannot have imports or exports.

 example\main.js:1:1
  > 1 | import 'ol/ol.css';
  >   | ^^^^^^^^^^^^^^^^^^^
    2 | import Draw, {
    3 |   createBox,

  example\index.html:7:5
    6 |     
  > 7 |     <script src="https://unpkg.com/elm-pep@1.0.6/dist/elm-pep.js"></script>
  >   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ The environment was originally created here
    8 |     
    9 |     <script src="https://cdn.polyfill.io/v3/polyfill.min.js?features=fetch,requestAnimationFrame,Element.prototype.classList,TextDecoder"></script> 

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/draw-shapes.html
2. Copy code from that page and create three files:
main.js, index.html and package.json under common directory
3. Run npm install to install dependencies
4. Run npm start

**Expected behavior**
I would expect this example to run without an issue in my local environment after copying 
code from the page and installing dependencies. I believe that this might be the case for all of the examples
and I'm willing to provide pull request which fix that issue for all of them at once.

**Comment by ahocevar** [comment]
@arekgotfryd Thanks for willing to fix this! Recent versions of parcel do not bundle in dev mode, but use modules as supported by the browser. Therefore, the fix would be to change a single line of code, from
```js
<script src="main.js"></script>
```
to
```js
<script type="module" src="main.js"></script>
```
Would be great if you could submit a pull request that changes the template accordingly.
