### ISSUE TITLE
Etag not use

### ISSUE THREAD

**Issue by eternalsilencer** [openlayers/openlayers#13657]
i use openlyaer xyz request tile, then i response  etag, but openlaer second request don not use the browserCache

**Comment by ahocevar** [comment]
OpenLayers cannot bypass the browser's caching strategy, so this must either be a matter of misreading the output from the developer tools or the server log, or an issue with the response headers involved in caching, or a browser bug. Note that for resources with an Etag, when no other cache related headers are set, the browser will issue an 'OPTIONS' request to see if the Etag is still the same. I suspect that what you're seeing in the dev tools or the server log are these 'OPTIONS' requests.

**Comment by eternalsilencer** [comment]
> OpenLayers cannot bypass the browser's caching strategy, so this must either be a matter of misreading the output from the developer tools or the server log, or an issue with the response headers involved in caching, or a browser bug. Note that for resources with an Etag, when no other cache related headers are set, the browser will issue an 'OPTIONS' request to see if the Etag is still the same. I suspect that what you're seeing in the dev tools or the server log are these 'OPTIONS' requests.

I use the vue framework. I know that headers can be added to this place（setTileLoadFunction ）, but I need to manually cache it myself. If I don't rewrite the setTileLoadFunction function, openlayer receives the browser's etag request, and the next time I request the same resource, it will not carry if not match flag

**Comment by ahocevar** [comment]
Here is a good article that explains how ETags work: https://xpertdeveloper.com/http-etag-explained/. I was wrong in saying that the browser sends an `OPTIONS` request to check if the resource needs to be re-fetched. The browser does send a `GET` request with an `If-None-Match` header (which cannot be influenced by JavaScript). And the server then either returns a 200 status with the requested resource as body, or - if the resource has not changed - a 304 status without response body.

That said, it is normal that you are seeing requests, and those that are already cached should be responded with a 304 status.

Again, nothing that OpenLayers or Vue can change. And nothing you should be trying to handle in your application.

**Comment by eternalsilencer** [comment]
> Here is a good article that explains how ETags work: https://xpertdeveloper.com/http-etag-explained/. I was wrong in saying that the browser sends an `OPTIONS` request to check if the resource needs to be re-fetched. The browser does send a `GET` request with an `If-None-Match` header (which cannot be influenced by JavaScript). And the server then either returns a 200 status with the requested resource as body, or - if the resource has not changed - a 304 status without response body.
> 
> That said, it is normal that you are seeing requests, and those that are already cached should be responded with a 304 status.
> 
> Again, nothing that OpenLayers or Vue can change. And nothing you should be trying to handle in your application.

![image](https://user-images.githubusercontent.com/51810383/167831004-c7efa7c1-ccb5-4f9e-97d9-716d67048280.png)
I use the openlayer example to load the map, the first time it returns 200, the second time the image does not request the server, it is loaded from the memory cache, but the server returns the etag for the first time, you can use this official example to see

**Comment by ahocevar** [comment]
I don't know what you're expecting, but look at the "General" section in the dev tools.

First request:
<img width="588" alt="Untitled1" src="https://user-images.githubusercontent.com/211514/167834540-8c60d13e-9323-431a-9175-021e0281b5a7.png">

Second request:
<img width="588" alt="Untitled2" src="https://user-images.githubusercontent.com/211514/167834614-48fc07f0-e398-4bc6-b35a-a779b947c836.png">

As you can see, the second request does not cause a data transfer, but is served from memory cache.

**Comment by eternalsilencer** [comment]
> I don't know what you're expecting, but look at the "General" section in the dev tools.
> 
> First request: <img alt="Untitled1" width="588" src="https://user-images.githubusercontent.com/211514/167834540-8c60d13e-9323-431a-9175-021e0281b5a7.png">
> 
> Second request: <img alt="Untitled2" width="588" src="https://user-images.githubusercontent.com/211514/167834614-48fc07f0-e398-4bc6-b35a-a779b947c836.png">
> 
> As you can see, the second request does not cause a data transfer, but is served from memory cache.

The first time you access the picture, the server returns Etag, then the second time you visit the picture, it should carry the if not match flag instead of getting it from the browser cache. According to my understanding, it should be like this

> I don't know what you're expecting, but look at the "General" section in the dev tools.
> 
> First request: <img alt="Untitled1" width="588" src="https://user-images.githubusercontent.com/211514/167834540-8c60d13e-9323-431a-9175-021e0281b5a7.png">
> 
> Second request: <img alt="Untitled2" width="588" src="https://user-images.githubusercontent.com/211514/167834614-48fc07f0-e398-4bc6-b35a-a779b947c836.png">
> 
> As you can see, the second request does not cause a data transfer, but is served from memory cache.

The first time you access the picture, the server returns Etag, then the second time you visit the picture, it should carry the if not match flag instead of getting it from the browser cache. According to my understanding, it should be like this

**Comment by ahocevar** [comment]
That's exactly what happens, and the browser does that. I have no idea why you think OpenLayers can do something wrong here, as this is something that cannot be influenced by JavaScript code. And in fact, the whole request is not even triggered by OpenLayers, it is just an `src` set on an `Image`.

So if the server returns a 200 despite the `If-None-Match` header with the matching etag, then this is a problem on the server side, not in OpenLayers.
