### ISSUE TITLE
GeoTiff: Issue with alpha band and no-data value NaN

### ISSUE THREAD

**Issue by m-mohr** [openlayers/openlayers#13666]
**Describe the bug**
I have a COG with a no-data value NaN (i.e. GDAL no-data values is set to the string "nan", but I also pass Number.NaN in the Source options as nodata value). It seems that NaN as no-data value is not correctly recognized although an alpha band is added. When I try to get the pixel value via the `getData` method, I get `[NaN, NaN, NaN, 255]` instead of `[NaN, NaN, NaN, 0]`. I also can't use the styling functionality due to that.

**To Reproduce**
Tried the example file with the cog and the cog-stretch examples. I can't provide on a host where you can directly access it, but here's the file for download: https://www.filehosting.at/file/details/3363216/nan.tiff
The source has been initialized as follows:
```js
const source = new GeoTIFF({
  normalize: false,
  sources: [
    {
      url: 'http://localhost/nan.tiff',
      nodata: NaN,
    },
  ],
});
```

**Expected behavior**
NaN as no-data value is handled correctly

**Comment by tschaub** [comment]
Hey @m-mohr - it looks like there might be some things we could do better here.  Should we reopen this?  I'm curious if you found a way around.

In addition to the nan issue, the experience isn't that great with non-tiled GeoTIFFs.

**Comment by tschaub** [comment]
We currently use `NaN` to indicate that there is not a nodata value.  I can look into handling this a different way.

**Comment by tschaub** [comment]
I put up #13669 as a proposed fix.  Needs more testing.

**Comment by m-mohr** [comment]
Hey @tschaub,
thanks for looking into this. Honestly, I wasn't so sure when I was closing this what the issue actually is. As I also hadanother  issues with no-data in general, I thought it is just my misunderstanding of what I'm reporting in #13588 and closed this one in favor of the other one.
But yesterday I actually got no-data for non-NaN mostly working and it seems that this is indeed still an issue as your PR also suggests. So re-opening this for #13669 and further testing based on that PR. Thanks again!
