### ISSUE TITLE
GeoTiff: Data not shown outside of "native" resolution

### ISSUE THREAD

**Issue by m-mohr** [openlayers/openlayers#13670]
**Describe the bug**
I'd like users to freely zoom in and out in COGs although they have limited resolutions. For example, I have a COG with a single resolution, but would still like to freely pan and zoom. Therefore, I use `geotiff.getView()` to get the "auto view", but create a new View only from the projection and then use `fit` to pan and zoom the view the extent. With my COGs, it's then the case that some parts of the image are hidden although in the visible area of the map and they only get shown when panning or zooming in.

I've made a screencast to visualize the behavior:

![ol-issue2](https://user-images.githubusercontent.com/8262166/168036279-1a64ff7c-396f-41d1-b0f9-2f79fb87cefd.gif)

**To Reproduce**
Here's also a CodeSandbox with the issue: https://codesandbox.io/s/cog-forked-srce6i
I don't have a host that supports Range requests at hand right now, so I uploaded the file here so that you can download it: https://www.filehosting.at/file/details/3363216/nan.tiff (it's the same file as in #13666)
(I know it has a bit weird tile size etc, but I've also seen this with other less strange files.)

**Expected behavior**
The COG should be shown for all visible areas.

**Comment by mike-000** [comment]
It seems to be due to the large number of tiles (636) needed to display the extent   The WebGL tile layer renderer uses a cache size of 512.,

**Comment by m-mohr** [comment]
Oh, indeed. I can confirm that setting the cacheSize to 1024 works in this case. Thank you!
