### ISSUE TITLE
dead release link in download ?

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#13687]
this link
https://github.com/openlayers/openlayers/releases/download/v6.14.1/v6.14.1-dist.zip
and the 2 others
are not found 

on this page
https://openlayers.org/download/

one` v `not necessary in the url in the file name?? or other side the v is missing in release page for a good build in download page ??

and i dont understand the use of what is in the zip ??
from this link
https://github.com/openlayers/openlayers/releases/download/v6.14.1/6.14.1-dist.zip
<img width="500" alt="Capture d’écran 2022-05-20 à 20 13 07" src="https://user-images.githubusercontent.com/328101/169588376-483159e2-5b31-470d-967d-945a1149da47.png">

**Comment by ahocevar** [comment]
Thanks for reporting the dead links. I fixed the downloads now.

The zip contains the legacy build, i.e. what you can include in a script tag and access through the `ol` namespace, e.g. `ol.Map`.

**Comment by MoonE** [comment]
The scripts beside ol.js are loaded when [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#spawning_a_dedicated_worker) are used. For example if you use [geotiffs](https://openlayers.org/en/latest/apidoc/module-ol_source_GeoTIFF-GeoTIFFSource.html) it will run a web worker which is started with one of these scripts.

**Comment by ahocevar** [comment]
Actually he other files are not web workers (these are inlined in `ol.js`), but dynamic imports (TIFF codecs for the GeoTIFF source).

**Comment by jipexu** [comment]
ok thanks ...
