### ISSUE TITLE
getData() issue with GeoTIFF tile pyramid

### ISSUE THREAD

**Issue by mika2523** [openlayers/openlayers#13706]
**Describe the bug**
In case of GeoTIFF tile pyramid, when more than one tile represents the layer at the given zoom level, getData() only returns values for one of the tiles. 

**To Reproduce**
1. Go to https://codesandbox.io/s/cog-pyramid-forked-rc4e29?file=/index.html
2. Wait until the browser output tab loads (map should appear)
3. Hover mouse over any part of land in the map in the browser output, and observe the color lookup values (directly under map) change 
3. Zoom in over any land near 0th meridian (West Africa, West Europe)
4. At the highest zoom level with two tiles stacked side by side, getData() only returns values for the right tile (presumably because it was loaded last?)

**Expected behavior**
getData() should return values for all tiles representing the layer at a given zoom level, not just one tile.

**Notes**
1) This example is derived from OpenLayers GeoTIFF tile pyramid example (https://openlayers.org/en/latest/examples/cog-pyramid.html), by straightforward addition of the getData() functionality from https://openlayers.org/en/latest/examples/cog-math.html example. 
2) The GeoTIFF tile pyramid in this example has only one tile per zoom level for all lower zoom levels, and then getData() works fine. But the highest zoom level contains two tiles stacked side by side. getData() works only for one of them (the right one representing the Eastern hemisphere, likely due to it being loaded last). 
3) I have confirmed this behavior in another example with even more (eight) tiles at a higher zoom level, still, only one (bottom right) tile is seen by getData().

**Comment by ahocevar** [comment]
Thanks for reporting this. There is indeed some extra care needed to make `getData()` work for this case. @mika2523 Do you think you'd be able to draft a pull request with a fix? If not let us know, but I think it will take a while until this can be addressed.

**Comment by mika2523** [comment]
Sorry, at this point drafting patches is a bit beyond my ability. But I do think that DataTile and GeoTIFF sources, along with methods like getData() represent important functionality that has got a lot of interest in the community, as evidenced by other recent bug reports and feature requests.

**Comment by mike-000** [comment]
The fix appears to be straightforward, instead of using `.getRenderSource()` which returns the last source used anywhere on the frame the renderer needs to determine the last source suitable for rendering at the coordinate, as in https://codesandbox.io/s/cog-pyramid-forked-dlsqp6?file=/main.js:1402-2065 (like everything else related to tile pyramids there is a lack of data suitable for including a test in a PR).

**Comment by mika2523** [comment]
Thanks to @mike-000 for showing a way to handle this issue. Is this going to get incorporated in one of the upcoming ol releases? Also, I would recommend adding the lookup functionality demonstration to the GeoTIFF tile pyramid example (https://openlayers.org/en/latest/examples/cog-pyramid.html), if possible.
