### ISSUE TITLE
The hit detection in styles with custom rendering at Retina display does not work well

### ISSUE THREAD

**Issue by hangbiaozhang** [openlayers/openlayers#13714]
**Describe the bug**
The hit detection in styles with custom rendering at Retina display does not work well.
`window.devicePixelRatio === 2`

**To Reproduce**
1.  Add a feature by custom rendering style and point geometry To map
2. Draw a fill color circle at renderer, center point 
3. Add 'click' listener To map
4. Get feature by call `map.forEachFeatureAtPixel()` at the listener function, `hitTolerance = 0`
5. At Retina display click out of the circle can still get the feature, the active area is double the radius

**Expected behavior**
The active area only in circle

**Debug place**
At `ol.render.canvas.ExecutorGroup.forEachFeatureAtCoordinate` function
`var transform = composeTransform(this.hitDetectionTransform_, hitTolerance + 0.5, hitTolerance + 0.5, 1 / resolution, -1 / resolution, -rotation, -coordinate[0], -coordinate[1])`
Is it necessary to consider `frameState.pixelRatio` when calculating transform
Just a personal opinion, hope it helps

**Comment by ahocevar** [comment]
@hangbiaozhang Thanks for reporting this! Do you think you could create a pull request with your suggested fix?

**Comment by hangbiaozhang** [comment]
@ahocevar I created a pull request #13722

**Comment by hangbiaozhang** [comment]
@ahocevar 
Thanks for reply
I find another way to fix the problem, change the custom renderer function. So I close the pull request and issue.

```
feature.setStyle(
  new Style({
    renderer(coordinates, state) {
      const scalePixel = function (value) {
        if (
          state.context.canvas.width === 1 &&
          state.context.canvas.height === 1
        ) {
          return value;
        } else {
          return state.pixelRatio * value;
        }
      };
      const [x, y] = coordinates;
      const ctx = state.context;
      ctx.beginPath();
      ctx.arc(x, y, scalePixel(30), 0, 2 * Math.PI, true);
      ctx.fillStyle = '#FFFF00';
      ctx.fill();
      ctx.strokeStyle = 'rgba(255,0,0,1)';
      ctx.stroke();
    },
  })
);
```
