### ISSUE TITLE
Blurry vector map between zoom levels

### ISSUE THREAD

**Issue by jdduarte** [openlayers/openlayers#13710]
I suspect this is not really a bug but something that can be improved. Opening it here since I didn't find any mention of it somewhere else.

**Describe the bug**
I have a vector base map (tile data from MapTiler) using a `MapboxVectorLayer` (also tried using the [ol-mapbox-style](https://github.com/openlayers/ol-mapbox-style) plugin with the same result) which displays blurred lines when between zoom levels.

Might be similar to #12963 but the proposed resolution there doesn't apply here as well I think since in a vector map smooth scrolling is something more of a reasonable expectation.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/vector-tile-info.html
2. Zoom in and out the see the blurred lines

Examples:

![blur](https://user-images.githubusercontent.com/161992/170696536-ee446579-cca2-4c86-8790-4fd0a5285a2e.png)

![no-blur](https://user-images.githubusercontent.com/161992/170696546-eca599a4-503c-4232-b2d1-750c346b50ad.png)

**Expected behavior**
Ideally the vector lines would always display in a clear way.

**Note:** Using the same source in a MapLibreGL map doesn't have the problem described.

**Comment by M393** [comment]
The default render mode for `ol/layer/VectorTile` is `'hybrid'` which renders lines and polygons to an intermediate canvas tile for each integer zoom level, to get better render performance. To render directly to the map canvas you can set [`renderMode: 'vector'`](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorTile-VectorTileLayer.html)

**Comment by jdduarte** [comment]
Thanks so much, that solves the issue completely. Although, like you suggested, the map becomes visibly slower.
