### ISSUE TITLE
Add More Style Expression Operator like 'sqrt', 'distance'

### ISSUE THREAD

**Issue by linjiacheng** [openlayers/openlayers#13739]
I have a geotiff with two bands, u and v bands to calculate wind speed, can you provide more operator like 'sqrt', so I can use expression like
`['sqrt', ['+', ['^', ['band', 1], 2], ['^', ['band', 2], 2]]]`

ref:  https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#sqrt

**Comment by mike-000** [comment]
Where not supported `sqrt` can be implemented as
`['^', ['+', ['^', ['band', 1], 2], ['^', ['band', 2], 2]], 0.5]`

**Comment by linjiacheng** [comment]
Silly me

**Comment by jahow** [comment]
Hi, I think such operator would make a lot of sense and help simplify expressions/make them more readable. Besides, we're still trying to be as compatible as possible with mapbox expressions.

@linjiacheng would you be willing to help with such a contribution? A good reference would be this PR: https://github.com/openlayers/openlayers/pull/13363
