### ISSUE TITLE
Dragging an overlapping vertex of a polygon results in an invalid geometry (open exterior ring).  

### ISSUE THREAD

**Issue by hargasinski** [openlayers/openlayers#13736]
**Describe the bug**
When dragging (ol/interaction/modify) a vertex that overlaps with the first vertex of the exterior ring of the same polygon, the exterior ring of the polygon isn't closed anymore. It appears that the final vertex in the exterior ring isn't updated to match the first vertex and the ring becomes open. In my case, the two vertices are overlapping because they snapped to each other.

**To Reproduce**
1. Go to https://codesandbox.io/s/draw-and-modify-features-forked-vdzj3e?file=/main.js
2. Drag the two overlapping vertices. 
3. The first and last vertices are logged to the console at `modifystart` and `modifyend`. In `modifyend`, they're not the same anymore and so the exterior ring of the polygon isn't closed.

**Expected behavior**
The exterior ring of the polygon to remain closed after the interaction. When dragging two overlapping vertices, I would expect either:

- only one of the vertices to be dragged at a time **or**
- if the first vertex in the ring is one of the vertices being dragged, the final vertex to be updated to match the first one.

I tried to find the source of the issue and I believe it's [these lines](https://github.com/openlayers/openlayers/blob/main/src/ol/interaction/Modify.js#L1032). When the polygon is being modified, only two segments for the polygon are being tracked, whereas for two overlapping vertices, there are four segments that need to be updated. Usually this isn't an issue as when overlapping vertices are dragged, the two segments connect to the same vertex. But in the case of the first vertex, it finds one segment for it, and then a segment for the overlapping vertex.

I would be happy to open a PR for this, so that more than two segments can be tracked.

**Comment by ahocevar** [comment]
Thanks for reporting this, @hargasinski, and for your offer to provide a pull request. Which would be greatly appreciated!

**Comment by hargasinski** [comment]
No worries @ahocevar! I opened #13745 with the fix.
