### ISSUE TITLE
Update Checkbox value inside Openlayers Sidebar after we change a layer visibility using JS Code

### ISSUE THREAD

**Issue by oabuthiab** [openlayers/openlayers#13740]
i use openlayers sidebar to manager my layers, however users can remove a layer using a button.
once the button is clicked JS changes the visibility of this layer and removes it from the map , the code used is :

item.setVisible(false);

this works however the checkbox inside sidebar remains unchanged (checked) even when the layer is no longer visibile, how can i refresh the vlaue of checkboxes (inside sidebar) knowing that openlayers generates different IDs for each box whenever its value is changed or a layer is added.

is there a code (openlayers code) to update or refresh checkboxes inside sidebar.

thank you

**Comment by M393** [comment]
OpenLayers does not have a Sidebar component, are you using an extension?
Maybe this example will help with your issue: https://codesandbox.io/s/layermenu-with-state-53g4r

**Comment by oabuthiab** [comment]
> Sounds like you are using [ol-ext](https://github.com/Viglino/ol-ext), try reporting your issue there.

thanks 
so true, i am using ol extension to manage my layers, i have just reported this issue there
