### ISSUE TITLE
Ios15.5 Changing VectorLayer visibility due to maxZoom breaks map interactions

### ISSUE THREAD

**Issue by jak983464779** [openlayers/openlayers#13746]
A vector layer, on top of an OSM layer, with a `maxZoom` configured, causes map interactions to stop working correctly when pinch-zooming in past the configured `maxZoom` (i.e. when the layer disappears). What happens is that pinch-zooming causes unwanted rotation afterwards, and panning is slower than the finger movement.

This happens on iOS 15.5.

**Comment by ahocevar** [comment]
Can this be reproduced with one of the our examples from https://openlayers.org/en/latest/examples/ ?

**Comment by jak983464779** [comment]
> Can this be reproduced with one of the our examples from https://openlayers.org/en/latest/examples/ ?

Go to
https://codesandbox.io/s/vector-layer-forked-fhcbkr
or
https://codesandbox.io/s/cluster-forked-5yg6d9

**Comment by ahocevar** [comment]
Thanks for the reproduction case. I can reproduce the problem. I have modified the first one a bit, and will be using https://codesandbox.io/s/vector-layer-forked-orth46 as a starting point for further investigation.

**Comment by jak983464779** [comment]
Thank you very much and look forward to your solution as soon as possible

**Comment by ahocevar** [comment]
> Loading MVT data through VectorTileLayer and VectorTileSource also creates problems

That's a separate issue. See #8956.

**Comment by forth-eorlingas** [comment]
> > Can this be reproduced with one of the our examples from https://openlayers.org/en/latest/examples/ ?
> 
> Go to https://codesandbox.io/s/vector-layer-forked-fhcbkr or https://codesandbox.io/s/cluster-forked-5yg6d9

I posted the same issue a week before this one and created the examples that were used here.
(https://github.com/openlayers/openlayers/issues/13725)

So @ahocevar either that issue or this one can be closed/redirected. And thanks for taking a look.

**Comment by Skizu** [comment]
I added `touchend` and `touchstart` listeners to `ol/MapBrowserEventHandler.js`, creating `pointerup` events for each `trackedTouches_` which was not active within `event.touches`. This resolved the "sticky finger" bug; however, with a large caveat whenever the event was fired the maps' touch events were unresponsive for a second or so. The easiest way to mitigate this issue is by reverting [#12792](https://github.com/openlayers/openlayers/pull/12792/files).

**Comment by ahocevar** [comment]
Please try the potential fix in #13770 and report if it fixes the problem for you.

**Comment by forth-eorlingas** [comment]
Works much better on iOS 15.6 beta 3, but I still get occasional unwanted behaviour, for example: 

1) sudden 180 map rotation
2) moving map becomes slow and it's not possible to zoom in
3) a few unusual rotations and then it goes back to normal
4) map begins to zoom when using one finger

Some could be unrelated, but none of these happen on Android 12.

**Comment by forth-eorlingas** [comment]
In my tests it is now back to breaking virtually every time when zooming past min/maxZoom.
