### ISSUE TITLE
Cluster fails when using GeoJSON as input

### ISSUE THREAD

**Issue by Lucienxhh** [openlayers/openlayers#13764]
**Describe the bug**
It's too ridiculous and wastes me 2 days finding it. 

When you read data from an URL to create `VectorSource` (like `vectorSource_1`) and then set it as the source of Clusters, Clusters works. However, when you read data from a variable to create `VectorSource` (like `vectorSource_2`), it fails that when zooming in and zooming out, the total number of clusters are not same on each zoom.

In details, when data is read from URL, "EPSG:4326" and "EPSG:3857" both works. However, when data is read from variable, "EPSG:4326" works and "EPSG:3857" fails.

**To Reproduce**

```
const vectorSource_1 = new VectorSource({
    url: 'test.json',
    format: new GeoJSON({
	    dataProjection: 'EPSG:3857',
	    featureProjection: 'EPSG:3857',
    })
})
const vectorSource_2 = new VectorSource({
    features: new GeoJSON().readFeatures(geojsonObject),
})
```
As described, `vectorSource_1` works and `vectorSource_2` fails when zooming in and out. Note that `test.json` is a standard GeoJSON file, and `geojsonObject` is exactly the same as `test.json`. No matter what `dataProjection` it is, when `featureProjection` is "EPSG:4326", both `vectorSource_1`and `vectorSource_2` work. When `featureProjection` is "EPSG:3857", `vectorSource_1` works and `vectorSource_2` fails.

In fact, the points in my `GeoJSON` file is around 100, and when zoom is set as 16, both `vectorSource_1` and `vectorSource_2` can provide many clusters. However, when zoom is set as 9 or lower, `vectorSource_1` will keep a cluster of total number and `vectorSource_2` will underestimate the total number or even do not display a cluster. 
**Expected behavior**
I use _console.log_ to output `vectorSource_1` and `vectorSource_2` for comparison and find that they have many differences. I think the reason is lies in the differences.

What's more, I find that `VectorSource` (i.e., `ol/source/vector`) supports two formats of data. One is `GeoJSON` and another is `Feature` (or `Feature Collection`). I use `VectorSource.addFeature` or `VectorSource.addFeatures` to load data and they both fail when zooming. Note that **fail** in this issue refers to "it could display clusters but the total number is not consistent when zooming".

**Comment by Lucienxhh** [comment]
![11](https://user-images.githubusercontent.com/72843445/173481464-f259f796-bc69-4c81-a587-6a129de85a86.png)
![22](https://user-images.githubusercontent.com/72843445/173481478-10e1e4b5-0cdb-4afd-b4ff-b1d4fc102ac7.png)
![33](https://user-images.githubusercontent.com/72843445/173481486-3c9a1841-f3b5-41a0-95b8-2b63d151e293.png)
![44](https://user-images.githubusercontent.com/72843445/173481488-12e2dec7-146b-47e8-b467-483f9942d2a1.png)
![55](https://user-images.githubusercontent.com/72843445/173481493-7f190d65-8c01-49e8-86fe-0486b3358948.png)

You can see the total number is decreasing and the cluster finally disappears.

**Comment by ahocevar** [comment]
You'll have to provide a runnable example to back your issue, e.g. by clicking "Edit" on one of the examples on https://openlayers.org/en/latest/examples and modifying it to show your problem.

**Comment by Lucienxhh** [comment]
```
	import {GeoJSON} from 'ol/format';
	import {
		Cluster,
		Vector as VectorSource,
		OSM
	} from "ol/source";
	import {Vector as VectorLayer, Tile as TileLayer} from "ol/layer";
	import {
		Circle as CircleStyle,
		Fill,
		Stroke,
		Style,
		Text,
	} from "ol/style";
	import {Map, View} from "ol";
	import {transform} from 'ol/proj'
	const geojsonObject = {
		"type": "FeatureCollection",
		"crs": {
			"type": "name",
			"properties": {
				"name": "EPSG:4326"
			}
		},
		"features": [{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.77647676171875,
						32.929162889038096
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.83861818017579,
						32.9240130477295
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.76806535424805,
						32.92212477258302
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.77527513208008,
						32.88041105798341
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.84308137597657,
						32.868738084350596
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.76858033837891,
						32.86135664514161
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.85166444482422,
						32.956628709350596
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.79776277246094,
						32.97173491052247
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.78849305810547,
						32.921438127075206
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.84136476220704,
						32.92349806359864
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						32.89455,
						115.81388333333334
					]
				},
				"properties": "FPP"
			},
			{
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						115.84102143945313,
						32.95611372521974
					]
				},
				"properties": "FPP"
			},
		]
	}
	const vectorSource = new VectorSource({
		features: new GeoJSON().readFeatures(geojsonObject),
	})
	const styleCache = {}
	const clusters = new VectorLayer({
		source: new Cluster({
			distance: 40,
			minDistance: 20,
			source: vectorSource,
		}),
		style: function(feature) {
			const size = feature.get('features').length;
			let style = styleCache[size];
			if (!style) {
				style = new Style({
					image: new CircleStyle({
						radius: 10,
						stroke: new Stroke({
							color: '#fff',
						}),
						fill: new Fill({
							color: '#3399CC',
						}),
					}),
					text: new Text({
						text: size.toString(),
						fill: new Fill({
							color: '#fff',
						}),
					}),
				});
				styleCache[size] = style;
			}
			return style;
		}
	})
	const map = new Map({
		layers: [
			new TileLayer({
				source: new OSM(),
			}),
			clusters,
		],
		target: "clusters",
		view: new View({
			center: [115.801196, 32.909336],
			projection: "EPSG:4326",
			// center: transform([115.801196, 32.909336], "EPSG:4326", "EPSG:3857"),
			// projection: "EPSG:3857",
			zoom: 10,
			maxZoom: 19,
		}),
	});
```
when `projection` is "EPSG:4326" it works. when  `projection` is "EPSG3857" it fails.

**Comment by ahocevar** [comment]
When using a static GeoJSON, you need to tell the `GeoJSONormat#readFeatures()` method the feature projection, which is the view projection. See https://codesandbox.io/s/simple-forked-hzifqz?file=/main.js, especially this section:
```js
const vectorSource = new VectorSource({
  features: new GeoJSON().readFeatures(geojsonObject, {
    featureProjection: map.getView().getProjection()
  })
});
```

**Comment by Lucienxhh** [comment]
> When using a static GeoJSON, you need to tell the `GeoJSONormat#readFeatures()` method the feature projection, which is the view projection. See https://codesandbox.io/s/simple-forked-hzifqz?file=/main.js, especially this section:
> 
> ```js
> const vectorSource = new VectorSource({
>   features: new GeoJSON().readFeatures(geojsonObject, {
>     featureProjection: map.getView().getProjection()
>   })
> });
> ```
 @ahocevar, thank you for your suggestions, though it seems not work well.
i comment lines 124 and125, and set EPSG:3857 as projection, clusters fails when zooming out. 
as pictures shown, there are 11 points at beginning. when zooming out, the number of points gradually decreases to 2, and finally disappears.
![1](https://user-images.githubusercontent.com/72843445/173758109-fc8adae6-6d06-4c90-9578-9af3c89d6aba.png)
![2](https://user-images.githubusercontent.com/72843445/173758848-d088f875-3b19-4736-a2b3-3227a2316b90.png)
![3](https://user-images.githubusercontent.com/72843445/173758134-8c5380b2-d1d1-46bb-846a-40a26f3e2ba5.png)
![4](https://user-images.githubusercontent.com/72843445/173758139-486cebea-d7d7-40e2-bd40-eb85dc543cd9.png)

**Comment by ahocevar** [comment]
This is because your data is incorrect. One of your points had invalid coordinates:
```js
coordinates: [32.89455, 115.81388333333334]
```
The latitude (`115.81388333333334`) exceeds the validity extent of EPSG:3857.
I changed the coordinates to 
```js
coordinates: [115.81388333333334, 32.89455]
```
And it works.

**Comment by Lucienxhh** [comment]
@ahocevar thank you for your correction. i follow your correction and the problem is solved. but i still have a question, why "EPSG:4326" works and "EPSG:3857" fails? 115 is an invalid latitude, so no matter what projection it is, the result should be consistent. the inconsistence confuses me and wastes me too much time to find why.

**Comment by ahocevar** [comment]
The difference is only that when you configure a `VectorSource` with a URL, it will automatically transformed to the view projection. If you use `GeoJSONFormat#readFeatures()`, you have to provide the view projection yourself to get the features transformed properly. Since the GeoJSON data is in EPSG:4326, it will work on a view in EPSG:4326 without a transform. That's the difference that you call inconsistency.

**Comment by Lucienxhh** [comment]
Thanks for the discussion. understand and closing
