### ISSUE TITLE
Legacy build with now more than ol.js, ol.js.map and ol.js.LICENSE.txt, normal?

### ISSUE THREAD

**Issue by ThomasG77** [openlayers/openlayers#13767]
**Describe the bug**

Since v6.14.1

I expect only files ol.js, ol.js.map and ol.js.LICENSE.txt like in https://github.com/openlayers/openlayers.github.io/tree/master/en/v6.14.0/build whereas in https://github.com/openlayers/openlayers.github.io/tree/master/en/v6.14.1/build, the structure has changed with numerous files e.g ol.js.map, ol.js.LICENSE.txt, ol.js, ol.css.map, ol.css, 629.ol.js.map, 629.ol.js, 611.ol.js.map, 611.ol.js, 54.ol.js.map, 54.ol.js.LICENSE.txt, 54.ol.js, 395.ol.js.map, 395.ol.js, 382.ol.js.map, 382.ol.js, 356.ol.js.map, 356.ol.js, 247.ol.js.map, 247.ol.js.LICENSE.txt, 247.ol.js, 231.ol.js.map, 231.ol.js, 226.ol.js.map and 226.ol.js

The same structure can be found also in [v6.14.1-dist.zip](https://github.com/openlayers/openlayers/releases/download/v6.14.1/v6.14.1-dist.zip) in releases page https://github.com/openlayers/openlayers/releases/tag/v6.14.1 

**Expected behavior**

I would expect to keep the same files structure.
It works if you include all files but there is no mention of the changes in the release notes.
I do not know if it's a bug/regression or a feature

**Comment by jipexu** [comment]
yes it will be so more simple and easy to understand to have a more simple build ... as previous ...
https://github.com/openlayers/openlayers/issues/13687

**Comment by ahocevar** [comment]
And it would make the legacy build even bigger.

**Comment by jipexu** [comment]
@ahocevar yes true ! 
.. so if i understand is it a half way between a modules way and an old school way ...
so if i use a non module environnement...
`<script type="text/javascript" src="ol.js"></script>`
is it enough to have the geotiffs decoders available if i need in the script ??
 (...dynamically imported when needed...)

thanks for your lights

**Comment by jipexu** [comment]
perfect thanks !

**Comment by ahocevar** [comment]
`ol.js.LICENSE.txt` is auto-created by Webpack. The content is defined by settings in the respective dependencies.
