### ISSUE TITLE
How to make webglpointslayer render multiple worlds？

### ISSUE THREAD

**Issue by zhuzhye** [openlayers/openlayers#13773]
I use webglpointslayer to render features, but webglpointslayer only renders one world. I want to render multiple worlds, similar to wrapx. How can I solve this problem to render multiple worlds

**Comment by MoonE** [comment]
WrapX has been implemented with #13528, but it is not yet released.
In case you are using [npm](https://www.npmjs.com/package/ol) you can use ol@dev to get the latest version from master.
Working example: https://deploy-preview-13528--ol-site.netlify.app/examples/webgl-points-layer.html
