### ISSUE TITLE
Area calculation differs between  OpenLayers and PostGIS

### ISSUE THREAD

**Issue by Rskut** [openlayers/openlayers#13780]
In OpenLayers I draw a 5 meter * 5 meter rectangle.

If I calculate the area of the geometry in OpenLayers I get 25 m^2 but in PostGIS I'm getting 25.04.

OpenLayer:

code snippet drawing the rectangle:

```
const factor = getPointResolution('EPSG:3857', 1, cursorCoordinate);
const forceHeight = 5 / factor;
```

Measuring:

```
const factor = getPointResolution('EPSG:3857', 1, firstCoordinate);
const squareMeter = polygon.getArea() * Math.pow(factor, 2);

//squareMeter = 25.00
```

PostGIS:
https://postgis.net/docs/ST_Area.html

```
SELECT 
	ST_Area(ST_Transform(postgis_area_geometry, 4326)::geography, true) 
FROM 
	geometry_table 
WHERE 
	id=xxx;
	
//Result use_spheroid=true = 25.04
//Result use_spheroid=false = 24.98
```
	
I'm not sure if do something wrong in openlayers or in postgis. I'm not even able to understand what Point-Resolution means.

QGIS shows me 25.04 too..

Geometry in GeoJson 3857:

`{"type":"Polygon","crs":{"type":"name","properties":{"name":"EPSG:3857"}},"coordinates":[[[856385.579794264,6863294.22127374],[856393.675958321,6863295.424757587],[856394.879442168,6863287.32859353],[856386.783278111,6863286.125109684],[856385.579794264,6863294.22127374]]]}`

**Comment by mike-000** [comment]
The OpenLayers equivalent of the `use_spheroid=true` method is the spherical `getArea()` method https://openlayers.org/en/latest/apidoc/module-ol_sphere.html#.getArea which for your polygon returns 24.944.  The `use_spheroid=false` method uses a more accurate ellipsoidal calculation which has no equivalent in OpenLayers (see #13572).  Any of these global calculation methods applied to small distances (less than 10 meters) will incur considerable rounding errors relative to the final result.  For polygons less than 1km across when using spherical mercator projection where the point resolution is easily calculated as `cos(latitude)` - something at latitude 60 appears twice the size of the same object at the equator (see https://openlayers.org/en/latest/examples/draw-and-modify-geodesic.html) - simply applying the point resolution to the planar area is likely to be as or more accurate than a more complex calculation.  However when polygon dimensions exceed 1km the variation in point resolution across the polygon would become significant and this simple method would become inaccurate.

**Comment by Rskut** [comment]
Fortunately, none of my geometries should exceed 1 km, so I can go with your suggestion, thank you :)
