### ISSUE TITLE
retired ESRI server for this example

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#13782]
Hi
**Describe the bug**
No map
The server is now retired (4/5/22) :  
**To Reproduce**
1. Go to '(https://openlayers.org/en/latest/examples/xyz-esri-4326-512.html)'
2. and see
3. no map

**Expected behavior**
instead ESRI_Imagery_World_2D – we have to use World_Imagery  as a replacement ?

https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/announcements/notification-that-old-esri-raster-basemaps-will-be-retired-esri_imagery_world_2d-and-esri_streetmap_world_2d/
i will try to make PR for the correction

Thanks

**Comment by mike-000** [comment]
The replacement map uses 256x256 tiles https://codesandbox.io/s/xyz-esri-4326-512-forked-6eshil?file=/main.js so it is no longer a good example of using 512x512 tiles.

**Comment by jipexu** [comment]
@mike-000  thanks, so what to do with this example ? remove ?  or modify 
ArcGIS REST with 512x512 Tiles ==> ArcGIS REST with 256x256 Tiles
and some other small text correction ?

**Comment by jipexu** [comment]
@ahocevar ok i will do this...
