### ISSUE TITLE
About the problem of converting EPSG:54004 to EPSG:3857

### ISSUE THREAD

**Issue by lovesL** [openlayers/openlayers#13789]
Hello friends, I have a problem。
![image](https://user-images.githubusercontent.com/27960630/175478855-2403e532-c58d-4600-9be9-5e4aaed233c0.png)
I want to convert Wkid:54004 to EPSG3857, but it doesn't work. Hope you can give me some help

 "ol": "^6.14.1",

**Comment by mike-000** [comment]
54004 is an ESRI alias for World Mercator (EPSG:3395)

To use it in OpenLayers you will need to include and register the proj4 definition:

```
proj4.defs("EPSG:3395", "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs");
register(proj4);
```

**Comment by lovesL** [comment]
> proj4.defs("EPSG:3395", "+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs");
> register(proj4);

Thank you, friends from afar
