### ISSUE TITLE
Keyboard events from "contenteditable" elements trigger map controls

### ISSUE THREAD

**Issue by ZakarFin** [openlayers/openlayers#13785]
**Describe the bug**
Pressing + or - on a "content editable" div zooms the map.

**To Reproduce**
1. Go to any example like https://openlayers.org/en/latest/examples/bing-maps.html
2. Run this on console to create a content editable div on map
```
var div = document.createElement('div');
div.textContent = 'Edit me +- ';
var input = document.createElement('input');
input.value = 'This works +-';
div.appendChild(input);
div.setAttribute('contenteditable', true);
div.style = 'background-color: red; position: fixed; top: 40%; left: 40%;';
document.getElementById('map').appendChild(div);
```
3. Focus on the input next to the red text and press + or - (input value changes and map isn't zoomed)
4. Click on the the text on the red background to edit it and press + or - (text changes but map is zoomed)

**Expected behavior**
Map isn't zoomed when editing the input field content nor when editing the editable text.

I think the fix would be to add a check for content editable on this line: https://github.com/openlayers/openlayers/blob/v6.14.1/src/ol/events/condition.js#L253
```
  return tagName !== 'INPUT' && tagName !== 'SELECT' && tagName !== 'TEXTAREA' && !originalEvent.target.isContentEditable;
```
I don't have the dev env set up so I can't test this change though. This problem occurs on our app that uses the https://draftjs.org editor as part of an app with OpenLayers map.

**Comment by jipexu** [comment]
your suggestion seems ok for the behavior
https://deploy-preview-13786--ol-site.netlify.app/examples/accessible.html
with your point 2

I still have a check who is not ok  (probably make typo mistake ..)

**Comment by ZakarFin** [comment]
Thanks for working on this! I hope it gets merged :)
