### ISSUE TITLE
VectorTile infinite loading loop

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#13797]
**Describe the bug**
The vector tile layer may load tiles forever.

I'm exporting a map as a multi-page pdf, but for one specific task the export never completes.
The specific steps required to reproduce are in the linked codesandbox.

**To Reproduce**
1. Go to https://codesandbox.io/s/vectortilelayer-tile-loading-bug-ppqluq?file=/main.js
2. The map will get stuck in a rendering loop, tiles loading never completes

**Expected behavior**
The map should load tiles once and fire a rendercomplete event at the end.

**Comment by mike-000** [comment]
It seems to be related to size.  Commenting out either `map.setSize(step.size);` or `size: step.size,` fixes it. ` fit()` defaults to the current size, so why do you need both?

**Comment by M393** [comment]
The resulting map extent is different when the size option is omitted when calling `fit`. 
I updated the codesandbox to better show the problem.

Looks like the viewport size is not updated when setSize is called. But even when I add this it still does not complete unless I throw in a `renderSync` call, not sure why it helps.

Also tried to update the size of the map target element in combination with `ùpdateSize`. This allows to drop the size from `fit`, but it also does not complete.

So the problem seems to be somewhere in the vector tile loading logic.

**Comment by mike-000** [comment]
Yes, it is a loading issue.  It can be fixed by specifying an explicit `cacheSize` in the vector tile source options.  The default is insufficient to cover the entire viewport if the map size is increased.
