### ISSUE TITLE
Option "preload" on WebGLTile layer with transparency produces some rendering artifacts

### ISSUE THREAD

**Issue by llienher** [openlayers/openlayers#13790]
Hi,

**Describe the bug**
We noticed that using a webGLTile layer with transparency where we applied "preload" to "Infinity" was producing some artifact on the map, thus making it unusable ... That issue was not visible on other layers without transparency.

**To Reproduce**
I have created a small example that reproduce the issue.
Two layers:
- fond-pourortho with transparency and where the issue is visible with preload: Infinity.
- swissimage has no issue so far.

Simply comment line 54 to hide the rendering issue  (default to preload: 0), or uncomment it to check out with value "Infinity".
https://codesandbox.io/s/webgl-fond-pourortho-swissimage-21ws7m?file=/main.js:1578-1641

**Expected behavior**
I would expect that the fond-pourortho tiles to render correctly.

**Comment by lysek** [comment]
I encountered the same problem: https://jsfiddle.net/fnvr0xsp/
