### ISSUE TITLE
Get the source of coordinate system information

### ISSUE THREAD

**Issue by lovesL** [openlayers/openlayers#13815]
hi, man, `https://epsg.io/?format=json&q=${ coord }`, what parameters do I need to add to get whether this coordinate system is EPSG or ESRI
![image](https://user-images.githubusercontent.com/27960630/177452052-e27f437f-8e5c-48fc-993e-a59cbc5f659d.png)
I want to get the value of this proj4js
![image](https://user-images.githubusercontent.com/27960630/177452962-d6d56d7c-460d-4069-b921-e2943ace6b70.png)

-----------------------------
I found a try in this demo
https://openlayers.org/en/latest/examples/reprojection-by-code.html 

thanks 😊😊

**Comment by ahocevar** [comment]
Duplicate of https://github.com/maptiler/epsg.io/issues/184.

**Comment by ahocevar** [comment]
What exactly do you want to know?

**Comment by lovesL** [comment]
> you
I'm sorry, I didn't express it clearly enough. I want to use https://epsg.io/?format=json&q=${ coord } to query whether my coord belongs to EPSG or ESRI. I saw that you used this API in the official DEMO, I thought you would know some information.

**Comment by lovesL** [comment]
![image](https://user-images.githubusercontent.com/27960630/177727514-f11db9a5-c311-492f-95a1-6c6c970b933d.png)

**Comment by ahocevar** [comment]
We're not the maintainers of epsg.io. I think you'll have to wait for an answer on https://github.com/maptiler/epsg.io/issues/184.

**Comment by lovesL** [comment]
thanks
