### ISSUE TITLE
ol.sphere.getArea is throwing error

### ISSUE THREAD

**Issue by maddy10s** [openlayers/openlayers#13813]
`Math.abs(wgs84Sphere.getArea(coordinates));	` gives below error in openlayers 6.12.0
	TypeError: n.getType is not a function
	    at Object.t [as getArea] (me-lib/openlayers/ol.js:2:1269619)
	    
sample coordinates that we use in our unit tests
                        "coordinates": [[[-8432259.459178813,5324959.300258331],[-8431791.282380566,5324949.745629795],[-8432111.36243651,5324550.839888432],[-8432011.038836885,5325102.619686366],[-8432259.459178813,5324959.300258331]]]

**Comment by ahocevar** [comment]
`getArea()` expects an `ol/geom/Geometry` as argument, not a GeoJSON coordinates array.

**Comment by maddy10s** [comment]
Thanks for pointing it out
