### ISSUE TITLE
Canvas.toDataURL() doesn't respect layer opacity

### ISSUE THREAD

**Issue by DamirKontrec** [openlayers/openlayers#13816]
While taking a screenshot of the map, using Canvas element's toDataURL() method, if any of the layers has an opacity other than 100%, I am not getting the accurate image of the map. Although map displays fine on screen, the exported image displays raster layer at 100% opacity, and overlaying vector layer is not displayed (both layers' opacity is set to 50%). I've noticed this behaviour in OpenLayers v6.14.1, but the same code worked as expected in v6.0.0.

Tested in:
Chrome 103.0.5060.66
Firefox 102.0.1

CodePen Examples:
WORKS - OpenLayers v6.0.0:
https://codepen.io/flekinjo/pen/VwXegQa

DOES NOT WORK - OpenLayers v6.14.1:
https://codepen.io/flekinjo/pen/qBobgdz

To reproduce the issue, click on the "Export image" button in provided CodePen examples.

Expected behavior:
Canvas' toDataURL() method should return the image respecting layers' opacities.

**Comment by mike-000** [comment]
The map can have multiple canvases.  See https://openlayers.org/en/latest/examples/export-map.html for an example of how to combine and export them.

**Comment by DamirKontrec** [comment]
Thank you @mike-000 !

Implementing the export the proper way (as described in example you linked) fixes the issue. Must have missed this change in release notes when updating OpenLayers in my app, sorry about that.
