### ISSUE TITLE
Please add support to delete multiple overlays

### ISSUE THREAD

**Issue by lovesL** [openlayers/openlayers#13822]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/27960630/177909697-6d76748a-e704-4244-978c-94f43f280685.png)
![image](https://user-images.githubusercontent.com/27960630/177909844-36bf9318-4377-4e4e-be93-54607121b6fb.png)

**Describe the solution you'd like**

**Comment by lovesL** [comment]
> 
Forgive me for being a bit obsessive, I always like to write it down, I currently delete it with a loop, thanks, man

**Comment by ahocevar** [comment]
If you use `map.getOverlays()` to get all overlays that are currently on the map, you get an `ol/Collection`. To remove all features from that collection, simply call
```js
map.getOverlays().clear();
```

**Comment by lovesL** [comment]
> If you use `map.getOverlays()` to get all overlays that are currently on the map, you get an `ol/Collection`. To remove all features from that collection, simply call
> 
> ```js
> map.getOverlays().clear();
> ```

Thanks, you let me know more about openopenlayer again  😊
