### ISSUE TITLE
On 6.14.1, Vector layers partially not shown.

### ISSUE THREAD

**Issue by kochizufan** [openlayers/openlayers#13820]
**Describe the bug**
On 6.14.1, Vector layers partially not shown.  
Please see reproduced html at next chapter.  

Is this bug? And if it is bug, are there any work around?

**To Reproduce**
https://code4history.dev/ShibeContour/index_ol6_bugonly.html
This site is what includes bug, which uses OpenLayers 6.  
Only upper half of polygon is shown and some text features also not shown.  

Souce code is:
https://github.com/code4history/ShibeContour/blob/main/index_ol6_bugonly.html

**Expected behavior**
https://code4history.dev/ShibeContour/index_ol5_bugonly.html
This site is what expected, which uses OpenLayers 5.  
Whole Polygon & all texts are shown.   

Souce code is:
https://github.com/code4history/ShibeContour/blob/main/index_ol5_bugonly.html

**Comment by kochizufan** [comment]
I also checked history.

v.6.1.1 works well
https://code4history.dev/ShibeContour/index_ol6.1.1_history_ok.html

But from v6.2.0, this error occured.
https://code4history.dev/ShibeContour/index_ol6.2.0_history_ng.html

So I assume the difference between 6.1.1 and 6.2.0 causes this error.

**Comment by ahocevar** [comment]
You're using a VectorTile layer where a Vector layer would be more appropriate, because the url does not handle different tiles. Alternatively, you can make the 6.2.0 and above version work by making the tile url unique per tile, e.g. by changing
```js
url: "./shibe.geojson",
```
to
```js
url: "./shibe.geojson?{z}-{x}-{y}",
```
But a better fix would be to use a Vector layer instead:
```js
const shibeLayer = new ol.layer.Vector({
  source: new ol.source.Vector({
    attributions: 'Rendered with <a href="https://www.maptiler.com/desktop/">MapTiler Desktop</a>',
    format: new ol.format.GeoJSON(),
    url: "./shibe.geojson",
  }),
  style: function(feature, resolution) {
    return [new ol.style.Style({
        stroke: new ol.style.Stroke({color: "#ff0000ff", width: 3}),
        fill: new ol.style.Fill({color: "#ff000066", width: 3}),
        text: new ol.style.Text({
            font: "Bold 20px/1 Verdana",
            text: feature.get("町村"),
            fill: new ol.style.Fill({color: "#ff0000ff"}),
            stroke: new ol.style.Stroke({color: "#ffffffff", width: 1}),
            overflow: true
        })
    })];
  }
});

**Comment by kochizufan** [comment]
Thank you! 
Sorry I misundersood what layer should use for each data sources.
With changing VectorTile to Vector, it become pretty better.
