### ISSUE TITLE
WMS-Map does not react after a few interactions in the map

### ISSUE THREAD

**Issue by David-brn** [openlayers/openlayers#13831]
**Describe the bug**
In Chrome and Safari on IOS devices, the map gets stuck when zooming in and out. The map does not react anymore. 

I was able to directly reproduce the error in OpenLayers in the example: "Single Image WMS".
the additional line: maxResolution: 2000,
causes the map window to no longer react correctly when zooming with a pinchZoom beyond the visibility limit.
It seems like a finger is still on the display. Although you only perform one move (panning), a rotation is made.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/wms-image.html
2. Set the maxResolution to 2000 in the new ImageLayer
3. Do simple interactions like zoom and rotate on a IOS device.

Code sample to reproduce:

`import 'ol/ol.css';
import ImageWMS from 'ol/source/ImageWMS';
import Map from 'ol/Map';
import OSM from 'ol/source/OSM';
import View from 'ol/View';
import {Image as ImageLayer, Tile as TileLayer} from 'ol/layer';

const layers = [
  new TileLayer({
    source: new OSM(),
  }),
  new ImageLayer({
    extent: [-13884991, 2870341, -7455066, 6338219],
    maxResolution: 2000,
    source: new ImageWMS({
      url: 'https://ahocevar.com/geoserver/wms',
      params: {'LAYERS': 'topp:states'},
      ratio: 1,
      serverType: 'geoserver',
    }),
  }),
];
const map = new Map({
  layers: layers,
  target: 'map',
  view: new View({
    center: [-10997148, 4569099],
    zoom: 4,
  }),
});
`

**Expected behavior**
The map should react when I zoom in and out and rotate.

**Comment by ahocevar** [comment]
This is probably related to the issues that are fixed with #13771. Can you try if the problem also occurs after `npm install ol@dev`?

**Comment by carraram** [comment]
I came here to report the exact same bug. A couple details about my own experience of this bug:

- It happens when the `minZoom` property is set and the map reaches the zoom level where the layer is supposed to be hidden
- Reproduced on the Layer Zoom Limits example: https://openlayers.org/en/latest/examples/layer-zoom-limits.html
- Reproduced on iphone 8 and iPhone 13, so it doesn't look last-iOS related

**Comment by David-brn** [comment]
Sorry for the delay.
I can also confirm that  `ol@dev` is working.

When will this version be released?

**Comment by ahocevar** [comment]
The latest release (v6.15.1) contains this fix.
