### ISSUE TITLE
Possible deprecated feature in use: Event.Path

### ISSUE THREAD

**Issue by supertrip86** [openlayers/openlayers#13862]
Hi, a simple question: I am using OpenLayers for a project of mine. However, when I use functions like the one below:

        map.on('singleclick', function (event) {
            const name = map.forEachFeatureAtPixel(event.pixel, function (feature) {
                return feature.get('name');
            });
        });

The following warning appears in my browser's console:

![178942087-7b966ece-a1ec-4cda-80e1-2c598ba5e4e0](https://user-images.githubusercontent.com/40668622/180155798-8eb2c89f-fc82-40e9-84f5-14f3aad87c41.png)

Is it safe to keep using such method? If not, will it be corrected anytime soon?

**Comment by ahocevar** [comment]
The warning will go away when the deprecated property gets removed. If you still find it annoying, another way would be to revert #12330, assuming we don't need to support Internet Explorer any more. Or yet another to only copy the properties that we know we need. 

What do people think?

**Comment by supertrip86** [comment]
Thank everybody for your reply. I don't mind the issue on the browser's console, as long as there will be no risk of having the application not working in the upcoming future.
Thanks for your clarification :)
