### ISSUE TITLE
Examples using proj4 do not load correctly in CodeSandbox

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13865]
**Describe the bug**
Most examples which use proj4 have `"proj4": "^2.7.5"` in the package.json.  The `^` is not understood by CodeSandbox and must be edited out before the example will load.

In some cases (e.g. Print to Scale) proj4 is completely missing.

**To Reproduce**
Open an example in CodeSandbox and see error.

**Expected behavior**
Examples should load without needing edits.

**Comment by jipexu** [comment]
@mike-000 is it the same case for this example ? https://openlayers.org/en/latest/examples/d3.html
who dont work in CodeSandbox

**Comment by mike-000** [comment]
No, that one does not show any errors, and d3 is loaded from unpkg.com, not via package.json.

**Comment by jipexu** [comment]
but you confirm it doesn't work  in CodeSandbox ?

**Comment by mike-000** [comment]
The example loads but renders an empty d3 svg.

**Comment by ahocevar** [comment]
@mike-000 Can you please report this to codesandbox.io? I think this is clearly their issue, because in `devDependencies`, they specify the `parcel` dependency with `^` as well.

**Comment by mike-000** [comment]
I don't think CodeSandbox uses `devDependencies` as it still works when edited out.  And there is the still the issue of the missing proj4 in the Print to Scale package.json  The only obvious difference between that and other examples is it has resources specified in its html template, but I cannot see how that is related.
