### ISSUE TITLE
`import GeoTIFF from 'ol/source/GeoTIFF';` fails in Svelte app using rollup

### ISSUE THREAD

**Issue by mradamcox** [openlayers/openlayers#13867]
**Describe the bug**
I have a Svelte app that uses OpenLayers heavily, and it's been working great. However, I am now trying to add a GeoTIFF source to my map. When I add `import GeoTIFF from 'ol/source/GeoTIFF';` (which I see in the OL COG example), I get the following error when the Svelte component rebuilds:

```
[!] Error: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
https://rollupjs.org/guide/en/#outputformat
Error: Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.
```

If I remove that import statement, the app rebuilds without error like normal.

Looking around a bit, I learned that you can output different bundle formats in rollup, but switching from `iife` to the default `es` causes other issues. I am new to Svelte and rollup (and frankly npm all around), so maybe there are some underlying problems with the way my app has been configured all along.

**To Reproduce**
I used this template to create the svelte app: https://github.com/thismatters/django-svelte. So to reproduce, use these steps:

1. Create the new app: `npx degit thismatters/django-svelte-template svelte`
2. `cd svelte`
3. `npm install ol`
4. In `src/App.svelte` add `import GeoTIFF from 'ol/source/GeoTIFF';` within the script tags
5. `npm run dev` and you'll see the error I mentioned above.
6. comment out the GeoTIFF line (and add any other ol import statements) and you'll see you can run the dev command without error.

**Expected behavior**
Import the GeoTIFF source module in this environment without error.

**Comment by ahocevar** [comment]
I don't know what the `thismatters/django-svelte-template` does, but when creating a Svelte app from scratch with the Vite template, it works fine (i.e. replace step 1 with npm create vite@latest svelte -- --template svelte).

That said, I think there must be a problem with the rollup configuration in `thismatters/django-svelte-template`, so it's probably worth reporting the error there.

**Comment by mradamcox** [comment]
Thanks for testing it out. `thismatters/django-svelte-template` actually just wraps this template https://github.com/sveltejs/template, so the same issue occurs using `npx degit sveltejs/template svelte-app` for step 1. However, I see now that that repo has a pretty huge deprecation warning, urging a switch to vite, so that's really the direction I should go anyway.

On the OpenLayers side of things, it seems like this issue could be indicative of an inconsistency between how the GeoTIFF source is written as compared to all the other code. But I think for me this is a non-issue now.

**Comment by ahocevar** [comment]
The GeoTIFF source depends on geotiff.js, which other sources don't. That library uses dynamic imports, which would result in code splitting, which is not allowed in rollup when `format: 'iife'` is configured in `rollup.config.js`, like the error message says.

But the fix is easy: in `rollup.config.js`, in the `output` section, add `inlineDynamicImports: true`.

**Comment by mradamcox** [comment]
Ah, that works indeed. Many thanks! I really appreciate the help.
