### ISSUE TITLE
return value snapped is deprecated from 6.14.1

### ISSUE THREAD

**Issue by bookmountain** [openlayers/openlayers#13861]
I originally used v6.5.0 and use snapTo function in Snap instance

upgrade to 6.14.1 and snapped is deprecated from returned Result type of snapTo function
snapTo only return vertex & vertexPixel those 2 values,
How do I get snapped boolean value on 6.14.1? 

Does the value that snapTo returned not equal to null mean snapped value is true?

thanks.

**Comment by MoonE** [comment]
In previous versions snapTo always returned an object with `snapped` set to a boolean, Since 6.14.0 it only returns an object when it snapped to something.
https://github.com/openlayers/openlayers/commit/49acb39f72833e8db34c8115d621ca6410738281
