### ISSUE TITLE
Reprojection example can overload WMS server

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13866]
**Describe the bug**
Reprojecting the EPSG:4326 tile WMS source to EPSG:3857 is slow and may overload the server.

**To Reproduce**
Open https://openlayers.org/en/latest/examples/reprojection.html on a wide screen, select WMS EPSG:4326 as the base map, the equatorial and mid latitude reproj tiles appear quite quickly.  Pan north or south and the rendering gets very slow as the number of source tiles requested increases exponentially with latitude.  Eventually most of the tiles are rendered, but there may be some gaps and load errors on the console.

**Expected behavior**
The example should be reasonably fast and not request more tiles than the server can handle.  Possible solutions might be to restrict the maximum width of the map, to specify a tile grid to limit the zoom level of source tiles, or to use ImageWMS or an alternative cached XYZ source (e.g. https://github.com/openlayers/openlayers/issues/13782#issuecomment-1161720327) which is more able to handle the load - or better queue management.

**Comment by ahocevar** [comment]
Thanks for reporting this, @mike-000. I think configuring `tileSize: 512` on the TiledWMS source should be enough to achieve an acceptable performance.

**Comment by ahocevar** [comment]
Or, even better, just change the service url to `https://ahocevar.com/geoserver/gwc/service/wms` and the WMS version to `1.1.1`. Then cached versions of the tiles will be delivered.

**Comment by mike-000** [comment]
> Or, even better, just change the service url to `https://ahocevar.com/geoserver/gwc/service/wms` and the WMS version to `1.1.1`. Then cached versions of the tiles will be delivered.

That is better but with a 1920px wide window it still overloads if panning to the high arctic or antarctic . Although the reproj tiles are handled in the main tile queue each requires many source tiles, which are loaded simultaneously without queueing - using an additional queue for source tiles needed for reprojection restricts the number of simultaneous requests on the server and prevents overload: https://codesandbox.io/s/reprojection-forked-r2421m?file=/main.js
