### ISSUE TITLE
Version 6.15.1 does not work in Internet Explorer 11

### ISSUE THREAD

**Issue by MattiL** [openlayers/openlayers#13878]
Version 6.15.1 does not seem to work in Internet Explorer 11 on Windows 10 21H2.

**To Reproduce**
1. Go to https://openlayers.org with Internet Explorer 11.
2. See errors SCRIPT1002: Syntax error ol.js (2,1386) and SCRIPT5009: ol is not defined openlayers.org (244,3)

**Expected behavior**
OpenLayers 6.15.1 works in Internet Explorer 11.

**Comment by mike-000** [comment]
In the legacy build there is a block of code which is not transpiled.  The messages in it correspond to quick-lru https://github.com/sindresorhus/quick-lru/blob/main/index.js which is a dependency of geotiffjs.  I'm not sure why it was not transpiled.

**Comment by tschaub** [comment]
https://blogs.windows.com/windowsexperience/2022/06/15/internet-explorer-11-has-retired-and-is-officially-out-of-support-what-you-need-to-know/
