### ISSUE TITLE
Is it useful about openlayers6 use ol.inherits?

### ISSUE THREAD

**Issue by shanshan1405** [openlayers/openlayers#13885]
openlayers3 operates ol.inherits(ol.control.MeasureControl, ol.control.Control) is workable, and i can see openlayers3 methods about inherits that link to https://openlayers.org/en/v3.20.1/apidoc/ol.html#.inherits, openlayer6 can not find relative link.

**Comment by MoonE** [comment]
`ol.inherits` was replaced by [`class extends`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/extends)

**Comment by tschaub** [comment]
As @MoonE mentions, use `extends` to extend an OpenLayers class.

See these examples for inspiration:
 * https://openlayers.org/en/latest/examples/custom-controls.html
 * https://openlayers.org/en/latest/examples/custom-interactions.html

**Comment by shanshan1405** [comment]
@tschaub @MoonE thanks.
