### ISSUE TITLE
Revert IE workarounds

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#13883]
For the next major release, we could remove support for IE.  There are years of IE workarounds in the library, so we may not get them all out, but we could remove some of the obvious ones.

I'll use this ticket to link to candidate reverts:

 - [x] #12734
 - [x]  #10989
 - [x]  #10824
 - [x]  #10612
 - [x]  #12891
 - [x]  #12785
 - [x]  #12740
 - [x]  #11865

**Comment by mike-000** [comment]
Plus other workarounds in ol/math and ol/obj, and any references to `msSaveBlob`, `msToBlob` and `msImageSmoothingEnabled`.

**Comment by tschaub** [comment]
We’ll likely find more, but I’ll close this one as done.
