### ISSUE TITLE
label and graticule steps ?

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#13886]
Hi
In this example :
https://openlayers.org/en/latest/examples/graticule.html

When I look at the example it seems really strange to me that the labels show irregular intervals while the grid looks  (should be?) regular?
the intervals are 3' or 3'.01'' or 2'.59''
<img width="1119" alt="Capture d’écran 2022-07-26 à 21 07 56" src="https://user-images.githubusercontent.com/328101/181228803-00055e88-6c18-4cbf-93ee-bc03681b5329.png">
Is there a particular reason I don’t understand? Are these the rounding of the calculations?
Anyway, I’ll wait rather for something less destabilizing ... Or I’m too Cartesian ... Or am I still missing something?

Thanks for your light !...

**Comment by mike-000** [comment]
I think it is because the default intervals are not well suited to the default format

for DMS instead of  `0.5, 0.2, 0.1, 0.05, 0.01, 0.005, 0.002, 0.001`

intervals such as

`30/60, 20/60, 10/60, 5/60, 2/60, 1/60, 30/3600, 20/3600, 10/3600, 5/3600, 2/3600, 1/3600`

would be more suitable

**Comment by mike-000** [comment]
Or should `ceil` be `round` here? https://github.com/openlayers/openlayers/blob/main/src/ol/coordinate.js#L171

**Comment by jipexu** [comment]
That works https://29r9yf.csb.app/   yes !!  That seems works well !

**Comment by jipexu** [comment]
i dont know if it is ok in all context but works here to display only degree with hemisphere when the minutes and seconds are both at 0
https://codesandbox.io/s/graticule-forked-s24rqm

**Comment by mike-000** [comment]
I don't think is is necessary to change the default function, it is easy to remove 00s in a custom function based on it https://codesandbox.io/s/graticule-forked-jppefq?file=/main.js

**Comment by jipexu** [comment]
@mike-000 work well too ... @tschaub has solve in the Pr ... so the life is cool ! thanks @ both
