### ISSUE TITLE
Tile load sequence violation error when using setState

### ISSUE THREAD

**Issue by MSBilgin** [openlayers/openlayers#13894]
Hi,

I use openlayers in an Android app with Spatialite. I use XYZ layer's **tileUrlFunction** to send tile requests to the Android native side. On the native side it gets raster tile data from Spatialite DB and send back to the JS (openlayers) side. On the JS side updating tile with the image data, so it draw a basemap. I use this strategy successfully with ol5 but after i updated to latest ol6 I got **Tile load sequence violation error**. This error occurs when updating tile image data and calling setState function of tile.

[codesandbox sample code](https://codesandbox.io/s/upbeat-shape-s54g0l?file=/src/index.js)

**Comment by mike-000** [comment]
The tileUrlFunction can be called when a tile is already loaded.  For loading use the tileLoadFunction https://codesandbox.io/s/amazing-microservice-nm5mhc

**Comment by MSBilgin** [comment]
I managed the code to work with **tileLoadFunction** , works like a charm, thank you so much. Also note that before ol6, i calculate **y** value by **(y * -1) - 1** for mbtiles format. Now this calculation done by ol6.  [You can find explanations in release doc](https://github.com/openlayers/openlayers/releases/tag/v6.0.0)
