### ISSUE TITLE
where can i find the difference of openlayers apidoc between old version and latest version? for example v-3.20.1 and v-6.15.1.

### ISSUE THREAD

**Issue by shanshan1405** [openlayers/openlayers#13918]
i am using latest openlayers, and  i find more difference when compared with old appcation using openlayers-v3, i can't find latest api in connection with v3. where can i find the difference of openlayers apidoc between old version and latest version? for example v-3.20.1 and v-6.15.1.

**Comment by M393** [comment]
https://github.com/openlayers/openlayers/releases or https://github.com/openlayers/openlayers/blob/v6.15.1/changelog/upgrade-notes.md

**Comment by shanshan1405** [comment]
@M393 thank you
