### ISSUE TITLE
Error extending classes in CodeSandbox

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13921]
**Describe the bug**
Error in CodeSandbox if application attempts to subclass `ImageTile` in latest dev versions.

**To Reproduce**
Simple example which demonstrates subclassing `ImageTile` https://codesandbox.io/s/simple-forked-ijj5xm?file=/main.js works up to 7.0.0-dev.1659038103619 but produces error if a later version is used.  However the Zoomify example which internally uses a subclass continues to work https://codesandbox.io/s/zoomify-forked-8jeghl 

Also tried with both Tile and WebGL tile layers and reprojection.  `release` is not logged with WebGL tile layer (separate issue perhaps).

**Expected behavior**
Simple subclassing should work..

**Comment by M393** [comment]
The timestamp fits this merge commit https://github.com/openlayers/openlayers/commit/3c5403259acf5fe6491c25a4333378b0d43cf11e

**Comment by mike-000** [comment]
That is the last working version, the first version to break it is 7.0.0-dev.1659039074785 which would be the merging of #13891

**Comment by tschaub** [comment]
@mike-000 - What is the error you are seeing and in what browser?

Your sandbox example works for me in Chrome 103.

**Comment by mike-000** [comment]
When I change it to a later version (e.g. https://codesandbox.io/s/simple-forked-js8oy3) I get `Class constructor ImageTile cannot be invoked without 'new'` in Chrome.

**Comment by tschaub** [comment]
The problem is occurring in code that codesandbox is transpiling.  Your custom tile class looks like this:
```js

var CustomTile = function (_ImageTile) {
  (0, _inherits3.default)(CustomTile, _ImageTile);

  function CustomTile() {
    (0, _classCallCheck3.default)(this, CustomTile);
    return (0, _possibleConstructorReturn3.default)(this, (CustomTile.__proto__ || Object.getPrototypeOf(CustomTile)).apply(this, arguments));
  }

  (0, _createClass3.default)(CustomTile, [{
    key: "getImage",
    value: function getImage() {
      console.log("getImage");
      return (0, _get3.default)(CustomTile.prototype.__proto__ || Object.getPrototypeOf(CustomTile.prototype), "getImage", this).call(this);
    }
  }, {
    key: "release",
    value: function release() {
      console.log("release");
      return (0, _get3.default)(CustomTile.prototype.__proto__ || Object.getPrototypeOf(CustomTile.prototype), "release", this).call(this);
    }
  }]);
  return CustomTile;
}(_ImageTile3.default);
```

And it looks like the problem is in this `apply` call: `Object.getPrototypeOf(CustomTile)).apply(this, arguments));`

**Comment by tschaub** [comment]
Here is a working version of your sandbox using Parcel: https://codesandbox.io/s/admiring-wright-ngj7bs?file=/main.js

So maybe a vite.config.js issue.

**Comment by tschaub** [comment]
And here is a working version using VIte: https://codesandbox.io/s/winter-rain-uby4k8?file=/package.json

I added `@babel/core` as a dev dependency.  May be another way to do it by disabling transpilation.
