### ISSUE TITLE
Still available too early 

### ISSUE THREAD

**Issue by Parzavil3** [openlayers/openlayers#13925]
https://mobile.twitter.com/settings/download?%24fallback_url=market%3A%2F%2Fdetails%3Fid%3Dcom.twitter.android&referrer=utm_source%3Drweb%26utm_medium%3Ddownload&_branch_match_id=link-743584181678125821&_branch_referrer=H4sIAAAAAAAAAz2MywrCMBAAvyYeG0zVg1CkIL2J%2BAVl293SpXmU7Yb8vvEizGkYZlXdj7u1WliVpIF9bzzHza7L59wP79fVPYy7LOD9BPM2ZvFdANlITdsbN1SQFNgfph0YTfucU2j%2Bt4iSGE9CC4mQdFnDeKQsM9VSCk3G3X4uEHIO1WEq0SfAL1Dl%2BdCYAAAA

**Comment by jipexu** [comment]
and what ? not funny spam ?... i will even not click on this ...
