### ISSUE TITLE
VectorTileLayer render mode `vector` is rendered after the `postrender` event

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#13938]
**Describe the bug**
With render mode `vector` the `postrender` is firing too soon.

**To Reproduce**
In a layer swipe it is necessary to place the `ctx.restore` in a timeout as in https://codesandbox.io/s/layer-swipe-forked-fdtie7?file=/main.js  Remove the timeout and it does not work.

**Expected behavior**
Possibly related to #11606 but this example only styles polygons - there are no declutter items, so no obvious reason to render after the event

**Comment by ahocevar** [comment]
In your codesandbox, the blue layer is rendered before the green layer, because of the order in the map's `layers` array. So if register
```js
blue.on('prerender', () => console.log('blue prerender'));
green.on('prerender', () => console.log('green prerender'));
blue.on('postrender', () => console.log('blue postrender'));
green.on('postrender', () => console.log('green postrender'));
```
the log will look like
```
blue prerender 
blue postrender 
green prerender 
green postrender 
```
which is totally expected.

**Comment by mike-000** [comment]
Yes, that is expected and the CodeSandbox uses the same layer order as https://openlayers.org/en/latest/examples/layer-swipe.html  What is not expected is a timeout is needed after the final `postrender` event for this swipe to work when it is not needed in the main example, nor with a VectorTile layer using the default hybrid mode.

**Comment by ahocevar** [comment]
The problem is that for the VectorTileLayer renderer, the `postRender` method is called as part of the TileLayer renderer's `renderFrame` method, which is before vectors are rendered.

I'm going to create a pull request with a potential fix.

**Comment by bjornharrtell** [comment]
@ahocevar I believe I still see this problem in some recent adventures trying to use openlayers as serverside tile renderer.
