### ISSUE TITLE
WebGL Tiles rendered using alpha-channel in band math do not show up on iOS

### ISSUE THREAD

**Issue by mn-prp** [openlayers/openlayers#13934]
**The Problem** 

My project involves requesting png files from a server with rgba-encoded data, which I style client-side. This works beautifully in all browsers on desktop (specifically, MacBook Pro) but fails in iOS.

**To Reproduce**

I've put together a reproduction in [this repository](https://github.com/mn-prp/openlayers-webgl-tile-issue), where I have a Mock Service Worker returning an example png, which I pain gray anywhere there is a non-zero value in the blue channel. This is obviously a simplification of the real business logic in my application, but it does reproduce the problem. MSW can be a bit finicky to get working, but a simple `npm install && npm start` should be enough to reproduce.

**Expected behavior**
The gray streaks representing data should appear on all devices consistently, but it does not on iOS. 

Example of expected behavior:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/105884647/182725450-dd1ead65-4eca-4ebb-a2d7-6f5364ffd433.png">

**Comment by mn-prp** [comment]
Upon further examination, we found this problem to be due to alpha premultiplication on iOS, but if there is a way for openlayers to handle this, it would be nice.

**Comment by mike-000** [comment]
> Upon further examination, we found this problem to be due to alpha premultiplication on iOS,

Does that mean that even tile textures are premultiplied in IOS?  Does the fix in #13570 work with IOS?

**Comment by mn-prp** [comment]
> Does the fix in #13570 work with IOS?

The parallel is suggestive, and I suspect they're related problems, but I'm not calling `layer.getData()` directly, I'm just passing a style expression to the `style` attribute of `WebGLTile`. I'd need to dig more into the openlayers source code to see where/how the fix in that PR could be translated to this context. 

The map layer renders as expected (i.e., predictably, minus the alpha-channel data) if we preprocess the images server-side to remove the alpha channel data, leaving no transparency.

**Comment by mike-000** [comment]
I just ran my CodeSandbox on IOS Safari via BrowserStack.  There is a black hole at the top of Everest where the alpha is 0, which does not happen on Windows.

![image](https://user-images.githubusercontent.com/49240900/183113834-eff5271f-5f3c-48d1-abf2-903efabfb34b.png)

**Comment by mn-prp** [comment]
I can confirm that the black hole appears on iOS but not on MacBook Pro.

**Comment by mike-000** [comment]
Using a third party PNG parser and loading into data tiles renders correctly plus the current `getData()` works as expected https://codesandbox.io/s/simple-forked-nxy41s?file=/main.js

**Comment by mn-prp** [comment]
Adding a dependency isn't ideal, but, all things considered, this is a straightforward and easy solution. Thanks.
