### ISSUE TITLE
Module parse failed: Unexpected token (1:0)

### ISSUE THREAD

**Issue by Kirbylix** [openlayers/openlayers#14008]
**Describe the bug**
build an Angular project with ol

**To Reproduce**
build an Angular project with ol
Angular Version: 14.1,0
ol Version: 6.15.1

**ERROR**
```./node_modules/ol/ol.css:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .ol-box {
|   box-sizing: border-box;
|   border-radius: 2px;
```

**Comment by ahocevar** [comment]
Maybe you tried to `import 'ol/ol.css'`? This is not supported by Angular. The most common way to import a dependency's css is to configure the `architect/build/options/styles` Array in `angular.json, e.g.
```json
            "styles": [
              "src/styles.scss",
              "node_modules/ol/ol.css"
            ],
```

**Comment by Kirbylix** [comment]
great, thanks has worked.
i had the import in my style.less inside ...
