### ISSUE TITLE
API documentation for openlayer2 404 Not Found

### ISSUE THREAD

**Issue by meor9zcu12** [openlayers/openlayers#14000]
I need to fix a project with openlayer2 shortly and cannot migrate to latest version with limited time.

The API documentation in [https://openlayers.org/two/](https://openlayers.org/two/), i.e. [http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers-js.html](http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers-js.html) is inaccessible, hence I have no idea how to fix my project.

**Comment by tschaub** [comment]
I think you'll need to use the wayback machine for that: https://web.archive.org/web/20200701150732/http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers-js.html

**Comment by tschaub** [comment]
The https://openlayers.org/two/ page now links to the web archive for examples and API docs.
