### ISSUE TITLE
v6 jsdelivr path has changed

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#14029]
**Describe the bug**
The v7 release has changed the jsdelivr path for previous versions.

**To Reproduce**
Multiple sites which use v6 legacy build via jsdelivr are not working, for example.
https://labs.os.uk/public/os-data-hub-examples/os-maps-api/zxy-27700-basic-map (select OpenLayers from dropdown list)
https://developers.arcgis.com/openlayers/maps/display-a-map/
https://www.newforestmarathon.co.uk/wp-content/maps/half_marathon/

https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.15.1/
has moved to 
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/dist/en/v6.15.1/

**Expected behavior**
Previously working versions should not be affected by new version releases.

**Comment by mike-000** [comment]
For further confusion
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/dist/en/latest/build/
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/dist/en/latest/css/
contain v6.15.1
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/dist/en/latest/legacy/
contains v7.0.0

**Comment by ahocevar** [comment]
Fixed by pushing the contents from before the new website build chain to the `master` branch of https://github.com/openlayers/openlayers.github.io, and added a `README.md` there to inform about the purpose of that branch.

**Comment by tschaub** [comment]
I guess we need more strongly worded warnings against using the “not for production” urls in production.

I can restore some of the old content in the master branch of that repo.  But it is a really bad idea using a url that points to the head of a branch in production.

**Comment by tschaub** [comment]
Thanks, @ahocevar 

Let’s talk about a dedicated package or some other solution to give people stable urls if we are going to continue documenting how to use the legacy build.  Those `@master` and `@main` urls are a hazard.

**Comment by ahocevar** [comment]
Agreed, @tschaub.

**Comment by jldelacalle** [comment]
thanks to all, especially to @mike-000 ,  for the clarifications.
