### ISSUE TITLE
ol.interaction.defaults is not a function

### ISSUE THREAD

**Issue by pnoe** [openlayers/openlayers#14020]
Hello,
migrating from ol 6.15.1 to ol7.0.0, I have the following error :
```
const map = new ol.Map({
		interactions: ol.interaction.defaults({ doubleClickZoom: false }).extend([select, translate]),
		controls: ol.control.defaults({
			attribution: false
		}),
		target: 'map',
                ...
```
in Firefox console : 
  Uncaught TypeError: ol.interaction.defaults is not a function

Bye !

**Comment by M393** [comment]
Does `ol.interaction.interaction.defaults(/* ... */)` work? This function has been moved, but it should be re-exported with the old name.

**Comment by ahocevar** [comment]
It should be `ol.interaction.defaults.defaults` now.

**Comment by hweri69** [comment]
Similary it is now ol.control.defaults.defaults

**Comment by pnoe** [comment]
Yes, it works with ol.interaction.defaults.defaults and ol.control.defaults.defaults.
Thanks a lot.
