### ISSUE TITLE
v7.0.0 assertion urls lead to 404

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#14028]
**Describe the bug**
v7.0.0 assertion urls lead to 404

**To Reproduce**
https://codesandbox.io/s/vector-tile-info-forked-5511r5 shows https://openlayers.org/en/v7.0.0/doc/errors/#68 which is a 404.

**Expected behavior**
Valid urls

**Comment by tschaub** [comment]
Those will need to be changed to the non-versioned urls.  Might be even more useful just to include the actual message in the error.

**Comment by ahocevar** [comment]
I think we can include the actual message in the error easily. All messages are still present as comments in the code. I'm creating a pull request now.

**Comment by tschaub** [comment]
Sounds good.  In the meantime, I pushed https://github.com/openlayers/openlayers.github.io/commit/2d815f9186bdef5ed4396aabc99967d8adffbde9.
