### ISSUE TITLE
package.json not found

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#14024]
**Describe the bug**
The examples and apidocs try to load the current version from https://raw.githubusercontent.com/openlayers/openlayers.github.io/build/package.json 
but it returns a `404` error.
If you are browsing an older version you no longer get the info to switch to the latest 

**To Reproduce**
1. Go to https://openlayers.org/en/v6.15.1/examples/accessible.html
2. No info about outdated version
3. See error in console

**Expected behavior**
The `package.json` should be available at the URL above.

**Comment by tschaub** [comment]
I started to fix this up by propagating the change in #14025 to the content in the openlayers.github.io repo, but needed to board a plane.  I'll continue making changes when back on the ground unless someone else has fixed it up already.

**Comment by tschaub** [comment]
The scripts for deployed versions of the API docs have been updated.  Examples still need updating.

**Comment by tschaub** [comment]
Examples updated with https://github.com/openlayers/openlayers.github.io/commit/f48da45e5955292715d6b2ea9e54744ec88e1387.  When that deploys, things should be working again.
