### ISSUE TITLE
Examples without requiring Node.js

### ISSUE THREAD

**Issue by namedgraph** [openlayers/openlayers#14037]
I am baffled by the assumption of OpenLayers that their users are also using (or should be using) Node.js. Never before so much machinery was required to deploy a simple client-side application.

Can you please provide vanilla JS versions of your examples? Or at least instructions on how to get there? Because now I have to resort to third-party sites for that.

**Comment by M393** [comment]
You'd need to use the [legacy build](https://openlayers.org/download/) and convert all uses of the imported classes to their equivalent legacy versions.
```patch
-import Map from 'ol/Map';
-import {fromLonLat} from 'ol/proj';
-const coordinate = fromLonLat([10, 50]);
-new Map(/* … */);
+const coordinate = ol.proj.fromLonLat([10, 50]);
+new ol.Map(/* … */);
```

**Comment by ahocevar** [comment]
There are two options:

1. Just click "Edit" on any of the examples. That will open a copy of the example on https://codesandbox.io, where you can edit the example without the need to install Node.
2. I have just created #14038 to link from the README to our example repository that shows how to use OpenLayers with Skypack.

For production builds, please do use a Node based setup.

**Comment by mike-000** [comment]
> You'd need to use the [legacy build](https://openlayers.org/download/) and convert all uses of the imported classes to their equivalent legacy versions.
> 
> ```diff
> -import Map from 'ol/Map';
> -import {fromLonLat} from 'ol/proj';
> -const coordinate = fromLonLat([10, 50]);
> -new Map(/* … */);
> +const coordinate = ol.proj.fromLonLat([10, 50]);
> +new ol.Map(/* … */);
> ```

Or you could refer to the version 4 examples https://openlayers.org/en/v4.6.5/examples/ for the syntax.  Although there have been some breaking changes since then many will work with version 7 by simply updating the links

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/dist/en/v7.0.0/legacy/ol.css" type="text/css">
    <script src="https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/dist/en/v7.0.0/legacy/ol.js"></script>

although it would be better to download your own copy and link to that - and by setting a size for the map div

    <style>
      .map {
        width: 100%;
        height: 400px;
      }
    </style>

**Comment by namedgraph** [comment]
The 7.0 CSS and JS files do not load for me:
```
Package size exceeded the configured limit of 50 MB. Try https://github.com/openlayers/openlayers.github.io/tree/master/dist/en/v7.0.0/legacy/ol.css instead.
```
```
Package size exceeded the configured limit of 50 MB. Try https://github.com/openlayers/openlayers.github.io/tree/master/dist/en/v7.0.0/legacy/ol.js instead.
```

**Comment by mike-000** [comment]
It seems to intermittent an problem with jsdelivr - which is why it would be better to download to your own system via https://openlayers.org/download/

**Comment by mike-000** [comment]
> The 7.0 CSS and JS files do not load for me:
> 
> ```
> Package size exceeded the configured limit of 50 MB. Try https://github.com/openlayers/openlayers.github.io/tree/master/dist/en/v7.0.0/legacy/ol.css instead.
> ```
> 
> ```
> Package size exceeded the configured limit of 50 MB. Try https://github.com/openlayers/openlayers.github.io/tree/master/dist/en/v7.0.0/legacy/ol.js instead.
> ```

That was incorrect link, try replacing `master` with `main`.

**Comment by Zhanes** [comment]
The problem with adding GitHub directly is that Github have Cross-Origin Read Blocking to avoid doing it from a browser. Do you know what happens with the jsdelivr? It worked for my until today

**Comment by mike-000** [comment]
> The problem with adding GitHub directly is that Github have Cross-Origin Read Blocking to avoid doing it from a browser. Do you know what happens with the jsdelivr? It worked for my until today

It is working now https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/v7.0.0/legacy/ol.js  NB use `@main` not `@master`

**Comment by namedgraph** [comment]
@mike-000 and where can I find https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.6.1/css/ol.css? One of my applications broke broke because that file is gone...

**Comment by mike-000** [comment]
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/v6.6.1/css/ol.css (or download from https://github.com/openlayers/openlayers/releases/tag/v6.6.1)

**Comment by vinxi2** [comment]
>     1. Just click "Edit" on any of the examples. That will open a copy of the example on https://codesandbox.io, where you can edit the example without the need to install Node.

I'm sorry if it's a dumb question but if I click on "Edit" in the "Simple Map" example it links me to:
https://codesandbox.io/s/qy3lyj?file=/main.js

and in the main.js there are "import" lines, it doesn't seem to be a "plain javascript / non-Node.js" version.

Am I wrong?

**Comment by M393** [comment]
That's the expected behaviour.

> Or you could refer to the version 4 examples https://openlayers.org/en/v4.6.5/examples/ for the syntax.

See https://github.com/openlayers/openlayers/issues/14037#issuecomment-1222326846

**Comment by prusswan** [comment]
Legacy build examples is still quite useful for more elementary usage where client-side JS is sufficient - usable within a local html file, or served from a simple local file server which can be Python or Node or something else), and server-side JS becomes an unnecessary distraction.

I would be interested in a simple mapping table between the new syntax and legacy syntax, @ahocevar, is there any way this can be achieved by adapting the build process used to create the legacy build files?

For now, apart from the OL4 examples as shared by @mike-000, [ol-ext](https://viglino.github.io/ol-ext/) is also a good source of examples using the "simpler" legacy syntax.

**Comment by ahocevar** [comment]
@prusswan I'm not exactly sure what you mean, because code will run on the client (browser) regardless of which technique you choose. Anyway, the mapping is 100% deterministic:

### Default exports
```js
import VectorLayer from 'ol/layer/Vector.js'`
```
maps to
```js
ol.layer.Vector
```
### Named exports
```js
import { defaults } from 'ol/control/defaults.js';
```
maps to
```js
ol.control.defaults.defaults
```
The mapping is always created from the exports listed in the [https://openlayers.org/en/latest/apidoc](API) docs, not any re-exports:
<img width="964" alt="Untitled" src="https://github.com/user-attachments/assets/a8ebefa1-849f-493e-8f3c-a580b358ffbc">

**Comment by prusswan** [comment]
The difference lies in the need for bundler/build tools to create the final
JS (e.g. making NodeJS a requirement), using Skypack is just delegating
this task to an online service but does not eliminate it. If you compare
this with Leaflet (even though it is not as "advanced" as OL), it can be
used without build tools, which makes it accessible to more users.

Anyway, the mapping shown will be helpful for someone trying to convert any
of the latest examples to "legacy" style. Thanks
