### ISSUE TITLE
VRT in GeoTiff

### ISSUE THREAD

**Issue by xycarto** [openlayers/openlayers#14031]
I have two COG files on S3. These tiles are in a seamless grid. I can easily access them using `GeoTiff` in the following method:

```
import {Map, View} from 'ol';
import TileLayer from 'ol/layer/WebGLTile';
import GeoTIFF from 'ol/source/GeoTIFF';
import proj4 from 'proj4';
import {register} from 'ol/proj/proj4';
import {get as getProjection} from 'ol/proj';

proj4.defs("EPSG:2193","+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs");
register(proj4)
const nztmProjection = getProjection('EPSG:2193');

const resolutions = [  8960,  4480,  2240,  1120,  560,  280,  140,  70,  28,  14,  7,  2.8,  1.4,  0.7,  0.28,  0.14,  0.07 ];

const urlHM = 'https://tile-service-raster.s3.us-east-1.amazonaws.com/cogs/as-raster-tile/HM_COG.tif'
const urlHN = 'https://tile-service-raster.s3.us-east-1.amazonaws.com/cogs/as-raster-tile/HN_COG.tif'

const cogSourceHM = new GeoTIFF({
  sources: [
    {
      url: urlHM,
      tileSize: 256,
    }
  ],
  convertToRGB: true,
});

const cogSourceHN = new GeoTIFF({
  sources: [
    {
      url: urlHN,
      tileSize: 256,
    }
  ],
  convertToRGB: true,
});

const cogUNIT = new TileLayer({
  sources: [cogSourceHM, cogSourceHN],
  crossOrigin: 'anonymous',
})

const map = new Map ({
  layers: [cogUNIT],
  target: 'map',
  view: new View({
    projection: nztmProjection,
    center: fromLonLat([176.0,-38.68], nztmProjection),
    zoom: 6,
    maxZoom: 6,
    minZoom: 10,
    resolutions: resolutions,
    constrainResolution: true,
    smoothResolutionConstraint: true
  })
});
```

What would it take to use `GeoTiff` to access a VRT of the two files, rather than loading all the files individually?  

Something like:

```
const url = 'http://localhost:5173/cog/cog.vrt'

const cogSource = new GeoTIFF({
  sources: [
    {
      url: url,
      tileSize: 256,
    }
  ],
  convertToRGB: true,
});
```

Please forgive me if this is a naive question.  To me it seems the VRT is close to a web ready format already being an XML document and possesses the necessary information regarding the extents, projections, resolutions, etc.    Would it be possible to add an option to `GeoTiff` to declare the input is a VRT, then Openlayers would look inside the VRT for the collection of GeoTiffs? Openlayers seems to know where my COGs are supposed to be and the VRT is just a wrapper to these COGs.

Ideally, if a person could use the VRT, in some cases there would be no need for conversion to mosaics or tiled formats. One could create their collection of COGs, make a vrt, load this onto S3, and access the COGs using this document. This would truly be serverless solution.

**Comment by ahocevar** [comment]
One thing that would bring you very close is using a `sourcesFromTileGrid()` creation function, like shown in https://openlayers.org/en/v7.0.0/examples/cog-pyramid.html.

**Comment by tschaub** [comment]
See if this example could be adapted to work with your data: https://openlayers.org/en/latest/examples/cog-pyramid.html

Not as flexible as full VRT support, but it makes it possible to stitch together multiple GeoTIFFs.

**Comment by xycarto** [comment]
Thank for pointing me to the tile pyramid example.  I will see if I can work out how to manipulate this use multiple adjacent COGs.

If I am correct, you are suggesting the ` sourcesFromTileGrid()` is really where I should be focusing in the example?

**Comment by xycarto** [comment]
Thanks to all for your suggestions on this. I exhausted my knowledge in tilegrids based on the suggestion given and will stick with my workaround for now.

Ideally, the base structure of the geotiffs would not need to be altered into pyramid structure since the Geotiff is already doing this for me.  If a vrt could be used in the future, that would amazing.

Thanks again for the awesome tools Openlayers provides and all the work you put in!

**Comment by xycarto** [comment]
This is not quite VRT usage, but I did manage to load multiple COGs with a function. 

```
const urls = [
  'https://tile-service-raster.s3.us-east-1.amazonaws.com/cogs/as-raster-tile/HM_COG.tif',
  'https://tile-service-raster.s3.us-east-1.amazonaws.com/cogs/as-raster-tile/HN_COG.tif'
]

function getSourceURLs(urls) {
  var urlArray = [];
  urls.forEach(address => urlArray.push(
    new GeoTIFF({
        sources: [
          {
            url:address,
            tileSize: 256,
          },
        ],
        convertToRGB: true,
        interpolate: false,
      }), 
    ))
    return urlArray
}

const cog = new TileLayer({
  crossOrigin: 'anonymous',
  sources: getSourceURLs(urls)
})

```

My thinking is, eventually I can go back and use the VRT as the "list" of needed COGs. For now, this is a good compromise for me.  The base data and storage format doesn't change.

Here is an example in action. An NZTM site, pulling two COGs, over top of a base layer (base layer is there to help me know if if the COGs align with existing data). https://dragonfly-science.github.io/qgis-cog-tiler/  

I might have had a unique case in COG usage and Openlayers.
