### ISSUE TITLE
This page is not available

### ISSUE THREAD

**Issue by arunthatham** [openlayers/openlayers#14040]
**Describe the bug**
The raster reprojection page was having good description. unfortunately it is removed now. Could you please restore?

**To Reproduce**
https://openlayers.org/en/latest/doc/tutorials/raster-reprojection.html

**Comment by M393** [comment]
Seems to be available at https://openlayers.org/doc/tutorials/raster-reprojection.html now

**Comment by tschaub** [comment]
@M393 is correct about the new location.  Apologies for the broken links.
