### ISSUE TITLE
ImageWMS UpdateParams - object is not extensible

### ISSUE THREAD

**Issue by Gaetanbrl** [openlayers/openlayers#14044]
**Describe the bug**

With React 18.2 / Node 18, i get a critical error when i try to update WMS params : 

```
Uncaught TypeError: Cannot add property CQL_FILTER, object is not extensible
    at assign (<anonymous>)
    at ImageWMS.updateParams (ImageWMS.js:483:1)
```

My code : 

```
componentDidUpdate () {
        ........
        cqlFilter = navigationType === "epci" ? `id_epci=${epci.siren}` : `id_com=${territoire.insee}`;
	carLayer.getSource().updateParams({
		CQL_FILTER: cqlFilter
	})
       .......
}
```

Here the OL code from ImageWMS that return an error (on Object.assign method): 

https://github.com/openlayers/openlayers/blob/31a42949e6b81389bd1718dcdc5d03f0f7c3426c/src/ol/source/ImageWMS.js#L474-L479

Where :

`this.params_` content is :

```
{
  CRS: "EPSG:3857",
  FORMAT: "image/gif",
  FORMAT_OPTIONS: "dpi%3A113",
  LAYERS: "xxxxx",
  STYLE: "default",
  STYLES: "",
  CQL_FILTER: "",
  TRANSPARENT: true,
  VERSION: "1.3.0"
}
```

And `params` content is : 
```
{
  CQL_FILTER: 'insee="22300"',
}

```
**To Reproduce**

Update ImageWMS params with React.

**Expected behavior**
Update the ImageWMS params.

**Comment by mike-000** [comment]
Was the `params` object you passed to the  constructor extensible?
https://github.com/openlayers/openlayers/blob/main/src/ol/source/ImageWMS.js#L109
Maybe `this.params_ = Object.assign({}, options.params);` would be safer at that line.

**Comment by Gaetanbrl** [comment]
> Was the params object you passed to the constructor extensible?

Saw default CQL_FILTER and STYLES missing from default `options.params` object.

Why couldn't we add new object to ImageWMS params like CQL_FILTER if not already defined ? Because sometime we need to add a new param. This works out of React (JS Vanilla).

Don't really understand this point.

Next, i try to change CQL_FILTER now and i get this error : 

`Uncaught TypeError: Cannot assign to read only property 'CQL_FILTER' of object '#<Object>'`

`Params ` object : 

```
{
  CQL_FILTER: 'insee="22300"',
}
```

`this.params_` object (same as `options.params`): 

```
{
  CRS: "EPSG:3857",
  FORMAT: "image/gif",
  FORMAT_OPTIONS: "dpi%3A113",
  LAYERS: "xxxxx",
  STYLE: "default",
  STYLES: "",
  CQL_FILTER: "",
  TRANSPARENT: true,
  VERSION: "1.3.0"
}
```

**Comment by Gaetanbrl** [comment]
> Maybe this.params_ = Object.assign({}, options.params); would be safer at that line.

Yeah, sur i dunno why we try to change params directly here.

**Comment by ahocevar** [comment]
Yes, that would be a good change to make. Pull request anyone?
