### ISSUE TITLE
olProj.transform() removes z-coordinates in OL7 when using an old proj4

### ISSUE THREAD

**Issue by Mortal** [openlayers/openlayers#14043]
**Describe the bug**
After updating to OpenLayers 7.0.0 in a codebase that uses proj4 version 2.5.0, features read and written using ol/format/GeoJSON are missing z-coordinates, and olProj.transform applied with 2D CRS'es on points with Z-coordinates result in projected points where the Z-coordinate is `undefined`.

**To Reproduce**
1. In the openlayers repository root, downgrade proj4 to version 2.5.0 in package.json and run `npm i`
2. Run `npm run test-node`

**Expected behavior**
Unit tests run without problems

**Actual behavior**
The unit test for `ol.proj.getTransform()`, `accepts a dimension` fails with `Error: expected undefined to equal 100` when trying to reproject some points where the z-coordinate is set to 100. This error matches the behavior we observed in our application (that uses proj4 version 2.5.0) when updating from OL 6.14.0 to OL 7.0.0.
```
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.<computed> [as be] (node_modules/expect.js/index.js:69:24)
      at Context.<anonymous> (file:///opt/openlayers/test/node/ol/proj.test.js:753:28)
      at processImmediate (node:internal/timers:466:21)
```

The proper solution is for the application that uses OpenLayers to use both an up-to-date OpenLayers as well as an up-to-date proj4. However, when studying the release notes for OL 7.0.0 we didn't consider the fact that we had to also update proj4 in our application.

Is there a way that OpenLayers could specify a minimum supported proj4 version?

Note that if I repeat the above "steps to reproduce" on OL 6.14.0, all unit tests in OpenLayers pass with no problems. In other words, OL7 bumped the minimum supported proj4 version. I think it's fair that OpenLayers expects users to use an up-to-date proj4, but I don't think this is explicitly stated anywhere in release notes, FAQ or documentation as far as I can tell.

**Comment by mike-000** [comment]
That would be the result of a v6.15 breaking change when support for projections which take 3 coordinates was added https://github.com/openlayers/openlayers/blob/main/changelog/upgrade-notes.md#fixed-coordinate-dimension-handling-in-olprojs-addcoordinatetransforms That would also require a compatible version of proj4, which was not mentioned in those notes.

**Comment by ahocevar** [comment]
I have update the required proj4 version in the docs, see #14061.
