### ISSUE TITLE
[6.3.1]Package size exceeded the configured limit of 50 MB

### ISSUE THREAD

**Issue by jldelacalle** [openlayers/openlayers#14041]
Since a couple of days ago we can't access the 6.3.1 package, does anyone know why?

**Comment by mike-000** [comment]
Are you wanting legacy build, etc?  https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/v6.3.1/build/ol.js

**Comment by jldelacalle** [comment]
We have always worked with this version 
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.3.1/build/ol.js
but now it seems to be inaccessible.

**Comment by mike-000** [comment]
See also #14029  In any case jsdelivr can be intermittently unreliable and it would be better to download the dist files from the OpenLayers releases page https://github.com/openlayers/openlayers/releases/tag/v6.3.1 to your own system.

**Comment by jldelacalle** [comment]
thanks
