### ISSUE TITLE
Openlayers v 6.12 does not work!

### ISSUE THREAD

**Issue by ricef** [openlayers/openlayers#14050]
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.12.0/build/ol.js
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@master/en/v6.12.0/css/ol.css
These two urls does not return any file since two days, so my maps doesn't work!
Console error in the broswer:
Failed to load resource: the server responded with a status of 403 () 
How can I do, I'm not interested in Open Layers 7

**Comment by mike-000** [comment]
Use
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/v6.12.0/build/ol.js
https://cdn.jsdelivr.net/gh/openlayers/openlayers.github.io@main/dist/en/v6.12.0/css/ol.css
or better still download the dist files from https://github.com/openlayers/openlayers/releases/tag/v6.12.0 to your own system.

**Comment by pfeely** [comment]
This has currently broken CDN in a few ways
No versions of v6 are listed in the Delvr menu

OL Latest no longer works either

https://openlayers.org/en/latest/css/ol.css
https://openlayers.org/en/latest/build/ol.js

**Comment by mike-000** [comment]
See #14055
