### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by irvingvjuarez** [openlayers/openlayers#14058]
**Describe the bug**
In the [Custom projection](https://openlayers.org/doc/tutorials/raster-reprojection.html) section of the tutorials (in the documentation) it's told that `{ register }` is imported from "ol/proj", but that's not true, it comes from "ol/proj/proj4".

Bad experience when you find the solution out of the official documentation

**Comment by ahocevar** [comment]
Thanks for reporting this, will be fixed with #14059
