### ISSUE TITLE
set view error

### ISSUE THREAD

**Issue by lovesL** [openlayers/openlayers#14068]
**Is your feature request related to a problem? Please describe.**
![14FFDF9F-8372-44EB-A62A-4A258721DE10](https://user-images.githubusercontent.com/27960630/187132910-9e38653d-e63e-4ad3-a4a3-83797726244e.png)
What does it mean？
**Describe the solution you'd like**
 "ol": "^6.10.0",

**Comment by lovesL** [comment]
<img width="764" alt="image" src="https://user-images.githubusercontent.com/27960630/187142799-c73b4287-ddf4-488e-bb72-a3ce380a1f3e.png">
How should I set it up?

**Comment by mike-000** [comment]
```
map.setView(
  new View({
      center: [11276062, 4235056],
      zoom: 4,
  })
);
```

as used in https://openlayers.org/en/latest/examples/reprojection-by-code.html

**Comment by lovesL** [comment]
> ```
> map.setView(
>   new View({
>       center: [11276062, 4235056],
>       zoom: 4,
>   })
> );
> ```
> 
> 在[https://openlayers.org/en/latest/examples/reprojection-by-code.html中使用](https://openlayers.org/en/latest/examples/reprojection-by-code.html)

Unhandled Rejection (TypeError): view.then is not a function

But I get this error with my code

**Comment by lovesL** [comment]
thanks man

**Comment by grallewellyn** [comment]
I am seeing the same error. For some reason it isn't registering that my options.view is a proper View instance and is skipping the first if statement
```
  setView(view) {
    if (!view || view instanceof View) {
      this.set(MapProperty.VIEW, view);
      return;
    }
    this.set(MapProperty.VIEW, new View());

    const map = this;
    view.then(function (viewOptions) {
      map.setView(new View(viewOptions));
    });
  }
``` 
In my code, this prints true: 
```
let newView = new View({
                    maxZoom: viewOptions.maxZoom,
                    minZoom: viewOptions.minZoom,
                    projection: mapProjection,
                    maxResolution: viewOptions.maxResolution
                });
console.log(newView instanceof View);
```

My map object looks like:
```
new Ol_Map({
                target: container,
                layers: [vectorLayer],
                controls: [],
                interactions: defaultInteractions({
                    altShiftDragRotate: false,
                    pinchRotate: false,
                    shiftDragZoom: false,
                    keyboard: false
                })
            });
```
I also tried the example above and multiple other View constructor objects throughout the openlayers code and get the same error. I am not sure why openlayers isn't detecting that my View object is properly constructed 

I am using openlayers v7.0.0 and tried v6.13.0

@lovesL How did you resolve this before?
