### ISSUE TITLE
Legacy build 'control.defaults' and 'interaction.defaults' broken

### ISSUE THREAD

**Issue by gtnewton** [openlayers/openlayers#14078]
Adding controls or interactions with code like `controls: ol.control.defaults({attribution: false})` fails, producing the error 'ol.control.defaults is not a function'. 

Similarly, adding an interaction like this `interactions: ol.interaction.defaults().extend([new ol.interaction.DragRotateAndZoom()])` produces the error 'ol.interaction.defaults is not a function'

This is only a problem when using the 'legacy' full build. [Link to jsfiddle demo](https://jsfiddle.net/8cqavd01/)
This was working on the latest OL v6

**Comment by MoonE** [comment]
See #14020

**Comment by gtnewton** [comment]
Thanks. I missed that!
