### ISSUE TITLE
API documentation version selection

### ISSUE THREAD

**Issue by KaiVolland** [openlayers/openlayers#14080]
**Is your feature request related to a problem? Please describe.**

When using the openlayers documentation it is hard to quickly change the version for the API docs.
I have a bookmark set to https://openlayers.org/en/latest/apidoc/.
But as I'm using ol in many different projects it would be nice if there was an easy way to switch between versions from the apidocs.

**Describe the solution you'd like**

I just played around and i think a dropdown might be a nice solution:

![ol_api_dropdown](https://user-images.githubusercontent.com/1849416/187692971-bdfcc4c9-76b1-4877-91ee-ad4c1253095f.gif)

What do you think?

**Comment by marcjansen** [comment]
I really like this! :+1: on a PR implementing this. Thanks in advance. Let's wait some time for others to react.

**Comment by marcjansen** [comment]
Please go ahead and create a PR please, @KaiVolland. TIA
