### ISSUE TITLE
Cannot see the Marker on the map

### ISSUE THREAD

**Issue by jdang67** [openlayers/openlayers#14087]
Using Angular, I can create a map and add the marker with the code below without any exceptions.
The problem is, that I cannot see the marker anywhere on the map. Searching google, I can see many people have the same problem without any solution. I am not sure if I'm missing something or a bug in your code.

Regards,

Jdang

```js
    
// private markerSource = new ol.source.Vector();
    private vectorSource = new VectorSource({
        features: []
    });

 private vectorLayer = new VectorLayer({
        source: this.vectorSource
  });

 this.map = new Map({
            target: 'map',
            layers: [
                this.vectorLayer,
                new TileLayer({ source: new OSM() }),
            
            ],
            view: new View({
                projection: 'EPSG:4326',
                center: this.mapCenter,
                zoom: 8,
                maxZoom: 18
            })
        });

 singleClick(event: any) {
        this.onClick.emit(event);
        console.log("event: ", event)

        this.addMarker(event.coordinate[0], event.coordinate[1])
    }

 private addMarker(lon: number, lat: number): void {

        const feature = new Feature({
            type: 'icon',
            geometry: new Point(fromLonLat([lon, lat], 'EPSG:4326') ),

        });

        const iconStyle = new Style({
            image: new Icon({
                anchor: [0.5, 1],
                anchorXUnits: 'fraction',
                anchorYUnits: 'pixels',
                src: '../../../assets/icons/Location.png',
            }),
        });

        feature.setStyle(iconStyle);
        feature.setGeometryName("Some Place");

        this.vectorSource.addFeature(feature);
        console.log('added marker ... ', this.vectorSource.getFeatures());
    }
```

**Comment by MoonE** [comment]
You have your vector layer below the tile layer, try putting the tile layer first in the `layers` array or set a higher `zIndex` on the vector layer.

**Comment by jdang67** [comment]
Nothing help @MoonE 
```js
 private vectorLayer = new VectorLayer({
        source: this.vectorSource,
        zIndex: 1000
  });

 this.map = new Map({
            target: 'map',
            layers: [
                new TileLayer({ source: new OSM() }),
                this.vectorLayer,
            
            ],
            view: new View({
                projection: 'EPSG:4326',
                center: this.mapCenter,
                zoom: 8,
                maxZoom: 18
            })
        });
```

**Comment by MoonE** [comment]
The geometry, by default, is stored as a property on the Feature with the name `geometry` and is accessible by either `getGeometry()` or `get('geometry')`. Using `setGeometryName('Some Place')` it tries to read the geometry from a property that is `undefined` and without a geometry no marker will be rendered. 

So simply remove the `setGeometryName` call.

**Comment by jdang67** [comment]
Looks like there are mage bugs in the software.  I can see the maker now but the size or imgSize properties do not work. I have to use the scale to make the image smaller

Thanks

![image](https://user-images.githubusercontent.com/8005940/188041734-8d72edec-57f5-4e47-9c4a-2af91dedf4c9.png)

**Comment by jipexu** [comment]
some bugs probably as all software ... many bugs i dont think ....

**Comment by MoonE** [comment]
Using the `scale` option is the correct way to change the rendered size of your icon.
`imgSize` and `size` are not meant for this. See the [Icon documentation](https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html) for an explanation on what use case they have.
