### ISSUE TITLE
Unexpected value when WKT feature parsing

### ISSUE THREAD

**Issue by verd1c** [openlayers/openlayers#14081]
I am trying to parse a WKT linestring that originates from a postgresql DB that has the following format:

LINESTRING(51.65 25.15 1, 51.65 25.15 1, ...)

where the points are x,y,z where z is the altitude. However, when I try to parse it as:

var feature = new ol.format.WKT().readFeature('LINESTRING(51.65 25.15 1, 51.65 25.15 1)');

I get an error about the altitude metric:

WKT.js:369 Uncaught Error: Unexpected `1` at position 23 in `LINESTRING(51.65 25.15 1, 51.65 25.15 1)`

Is this correct behavior? If yes how would I parse this linestring into a feature while having the z metric?

**Comment by ahocevar** [comment]
Yes, this is correct behavior. For 3d coordinates, your WKT should look different:
```js
var feature = new ol.format.WKT().readFeature('LINESTRING Z (51.65 25.15 1, 51.65 25.15 1)');
```

See it in action in https://codesandbox.io/s/sad-butterfly-7nkbt1?file=/src/index.js.
