### ISSUE TITLE
Tile request timing changed for layers in a LayerGroup

### ISSUE THREAD

**Issue by jasontk19** [openlayers/openlayers#14098]
I am not sure that this is necessarily a bug rather than just a change in expected behavior but, after perusing the release notes a few times I wasn't able to determine which particular change would have caused this behavior.  We recently upgraded from version 6.1 => 7.0 and noticed a change in tile loading behavior for layers within a LayerGroup.  In this example, we have 20 TileLayers that belong to a single LayerGroup.  In version 6.1 you can see that the requests get sent concurrently, causing imagery to show quite quickly 👍🏻 

![Screen Shot 2022-09-07 at 10 22 35 AM](https://user-images.githubusercontent.com/1480000/188934201-16966b56-90f6-4c8c-beff-572c223f0828.png)

After upgrading to version 7.0 it appears that each TileLayer in the LayerGroup requests imagery one at a time, causing the requests to be sent sequentially which has a very visible impact on imagery load times 🤔 

![Screen Shot 2022-09-07 at 10 26 43 AM](https://user-images.githubusercontent.com/1480000/188934422-bdf819a3-4a04-41ea-99ac-61d6c2ec1fb0.png)

The only differences in code between the two examples above were changes to the ol and ol-mapbox-style package versions.  I am hoping someone can help point me in the right direction towards how to get the loading behavior we see in the first screenshot.  

Also, thanks to everyone who contributes to this project and helps keep it alive.  We depend on it quite heavily in our application and so, appreciate the continued support 👏🏻

**Comment by ahocevar** [comment]
Would you be able to provide a minimal example? This would help finding the change that caused this by doing a `git bisect`.

**Comment by jasontk19** [comment]
Yes,[ here is barebones example](https://codesandbox.io/s/granule-layer-tile-loading-3vkktq?file=/main.js) of what we're doing.  For some reason the imagery isn't showing in this example (I must have something misconfigured) but, you can see the requests go out sequentially in the network tab which is the primary concern.

**Comment by jasontk19** [comment]
I've traced it down to whats listed as version `6.4.4-dev.1603221180680` in codesandbox.  I'm just not sure if/how this version translates to a commit to see what the change was.

**Comment by ahocevar** [comment]
Thanks for the investigation, @jasontk19. Then this was probably #11646. Not sure yet though if the old or the new behavior is the intended one.

**Comment by ahocevar** [comment]
Ok, the new behavior is the intended one. In versions prior to #11646, the tiles were not handled by the tile queue.

To get faster tile loading, you can use the map's `maxTilesLoading` property. The default value is 16, which means no more than 16 tiles are loading at any time. Try setting that to a (much) higher value.

**Comment by jasontk19** [comment]
Changing the `maxTilesLoading` to 64 seemed to have no impact on how many tiles were loaded at once.  Because of the way these layers are configured, a single layer may only cover a very small portion of the map and therefore there may only be one tile per TileLayer to be requested when you are zoomed all the way out.  Is there something about the fact that it's many different layers with so few tiles each that causes this loading behavior?  I guess I need to understand how the tile queue works better to know how we could get around this.

**Comment by ahocevar** [comment]
The tile queue manages all layers of the map, so it should not make a difference when you have many layers with few tiles.

Any chance you could fix the codesandbox you linked above? It would help if it actually showed a map. Also, I'm unclear why you're giving each layer a different className (which is bad for performance). Also, setting the `preload` option to `0` means that no lower resolution tiles will be preloaded. Not sure if this is what you want.

**Comment by jasontk19** [comment]
Sure thing, the codesandbox is working as expected now 👍🏻   Giving each a different className was just a shot in the dark on my part trying to see if it made a difference, we don't normally do that and I've since removed it.  The `preload: 0` was an intentional choice in the context of our larger app to cut down on total tile requests; we do our own preloading of tiles for prev/next days.

**Comment by ahocevar** [comment]
Thanks @jasontk19 for the reproduction case and the investigation. It turns out that the problem was the way WMTS sources generate the source key. I created #14100 with a fix.

**Comment by jasontk19** [comment]
Awesome, thanks for your help @ahocevar!
