### ISSUE TITLE
Cannot access the documentation and examples of the Openlayers 2 version

### ISSUE THREAD

**Issue by ramongarver** [openlayers/openlayers#14117]
**Describe the bug**
As a developer I cannot access the documentation and examples of the Openlayers 2 version.

**To Reproduce**
1. Go to 'https://openlayers.org/two/'
2. Click on '[API Documentation](http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers-js.html)', [Development Examples](http://dev.openlayers.org/examples/)', [2.13.1 Release Examples](http://dev.openlayers.org/releases/OpenLayers-2.13.1/examples/) or [Test Suite](https://openlayers.org/two/tests/).
3. See error '404 Not Found'

**Expected behavior**
The requested URL is found in the server.
The resources are accessible.

**Comment by tschaub** [comment]
The https://openlayers.org/two/ page now links to the web archive for examples and API docs.

**Comment by ramongarver** [comment]
Thank you for your promptness.
