### ISSUE TITLE
hasFeatureAtPixel fails when the icon is large or when the scale of the icon is directly set to 10 or larger

### ISSUE THREAD

**Issue by sunvictor** [openlayers/openlayers#14113]
```
const imageFeature = new ol.Feature({
  geometry: new geom.Point([114.21695891356348, 22.41699017631581])
})
const image = new Image(145, 561);
image.src = require("./icons/002.png");
imageFeature.setStyle(new style.Style({
  image: new style.Icon({
    src: require("./icons/002.png"),
    opacity: 1,
    anchorXUnits: "fraction",
    anchorYUnits: "pixels",
    anchor: [0.5, 281],
    scale: 1,
  })
}))

const imageLayer = new layer.Vector({
  source: new source.Vector({
    features: [imageFeature]
  }),
  zIndex: 10
})
map.addLayer(imageLayer);
map.on("click", (e) => {
  if (map.hasFeatureAtPixel(e.pixel)) {
    console.log("ok")
  }
})
```
![002](https://user-images.githubusercontent.com/33149691/189820894-082808dd-2bba-411a-918c-ff5a90eb3238.png)

**Comment by MoonE** [comment]
For large images you have to increase the [`renderBuffer`](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html) from the default of 100 px.

**Comment by sunvictor** [comment]
> 对于大图像，您必须[`renderBuffer`](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html)从默认的 100 px 增加。

Thanks for fixing this.

**Comment by sunvictor** [comment]
> For large images you have to increase the [`renderBuffer`](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html) from the default of 100 px.

Thanks for fixing this.
