### ISSUE TITLE
Options<ImageWMS>, Options<TileWMS> ... are not useable for layer constructor

### ISSUE THREAD

**Issue by bad-ch** [openlayers/openlayers#14120]
We have done an update from Openlayers 6.9 to 7.1. In the typescript definition we have now a problem. If we use the responsible option types (in the example below Options<TileWMS>) for creating a new layer we get an error during compile:

const tileLayerOptions: LayerOptions<TileWMS>
Argument of type 'import("../ol/layer/Layer").Options<import("../ol/source/TileWMS").default>' is not assignable to parameter of type 'import("../ol/layer/BaseTile").Options<import("../ol/source/TileWMS").default>'.
  Types of property 'map' are incompatible.
    Type 'Map | null | undefined' is not assignable to type 'Map | undefined'.ts(2345)

example (error on the last line):

const tileLayerOptions: Options\<TileWMS\> = {
  visible: layer.isChecked,
  opacity: layer.opacity,
  extent,
  minResolution,
  maxResolution,
  source: new TileWMS(tileWmsSourceOptions)
};
const wmsTileLayer = new TileLayer(**tileLayerOptions**);

**Comment by ahocevar** [comment]
You're using the option types incorrectly. For example, the TileLayer options are located in the `ol/layer/Tile` module, not in `ol/layer/Layer`.

**Comment by bad-ch** [comment]
But the ol/layer/Tile has no options. If I want import the Options with:

import { Options } from 'ol/layer/Tile';

I get:

Module '"ol/layer/Tile"' has no exported member 'Options'. Did you mean to use 'import Options from "ol/layer/Tile"' instead?

**Comment by ahocevar** [comment]
Try
```js
import { Options } from 'ol/layer/BaseTile';
```

**Comment by bad-ch** [comment]
:o)
