### ISSUE TITLE
Print to scale example

### ISSUE THREAD

**Issue by pierrickpelletier** [openlayers/openlayers#14121]
Hi all and thanks for this awesome librairy !

**Describe the bug**
In the Print to scale example, OL return a blank image when i export in A0 format,  300DPI quality and map rotation.

**To Reproduce**
1. Go to [https://openlayers.org/en/latest/examples/export-pdf.html](https://openlayers.org/en/latest/examples/export-pdf.html)
2. Select A0 format
3. Select 300DPI resolution
4. Apply a rotation on the map
5. Click on Export PDF button

**Comment by M393** [comment]
Most likely you don't have enough memory/gpu memory or your browser limits the possible canvas size.

**Comment by pierrickpelletier** [comment]
Canvas size : 9933px x 14043px less than chrome canvas size limit
Config: i7 - 16Go - RTX2070

**Comment by M393** [comment]
For me it takes a *very* long time to complete, but I did get a map.
[map.pdf](https://github.com/openlayers/openlayers/files/9583243/map.pdf)

**Comment by M393** [comment]
Did not apply a rotation ...

With rotation there are two canvases:
![image](https://user-images.githubusercontent.com/56256405/190622115-ed882138-e4a8-47a0-8c07-14d9c96cdc99.png)
16996 x 16907 = 287,351,372 (at ~45deg, depends on rotation)
14,043 x 9,933 = 139,489,119

[Maximum area](https://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element): 268,435,456 pixels (e.g., 16,384 x 16,384)

So depending on rotation you are over the limit. with the first canvas.

**Comment by pierrickpelletier** [comment]
Effectively ! Thank you very much for the explanations @M393
