### ISSUE TITLE
Cannot use search or scroll in menu on Openlayers website API page for v4.6.5 

### ISSUE THREAD

**Issue by Delzaros** [openlayers/openlayers#14123]
**Describe the bug**
On de API v4.6.5 page of the Openlayers website the search bar does not work and I cannot scroll at all in the menu. In the console I found an error stating that "currentVersion" has been redeclared. One is declared on line 56 and then redeclared on line 59. I'm guessing this stops javascript execution. Its hard to navigate the website atm and its been like this for a few weeks now. Not sure where I should have reported this bug but I thought I should atleast let you know somewhere.

**To Reproduce**
1. Go to 'https://openlayers.org/en/v4.6.5/apidoc/'
2. Try to use the search bar, on the left side of the screen, or try to scroll the menu beneath it
3. See error in console

**Expected behavior**
The search bar to filter the menu & the being able to scroll in the menu

**Comment by ahocevar** [comment]
Thanks for reporting this. Fixed with https://github.com/openlayers/openlayers.github.io/commit/b58470f00a7f36ca1d1c974e3ddf364f0c0c138d.
