### ISSUE TITLE
Print to scale example is broken

### ISSUE THREAD

**Issue by daboudii** [openlayers/openlayers#14129]
**Describe the bug**
The `Print to scale example` is broken 

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/print-to-scale.html'
2. Click on 'Export PDF'
3. See error in console : `Uncaught ReferenceError: html2canvas is not defined`

**Expected behavior**
The pdf page should be printed

**Comment by M393** [comment]
Works for me. Maybe it was a temporary outage of https://html2canvas.hertzen.com/dist/html2canvas.min.js?

**Comment by daboudii** [comment]
My bad, noscript was on for `hertzen.com` 🤦‍♂️
