### ISSUE TITLE
Rotation between -5° and 5° snaps back to 0°

### ISSUE THREAD

**Issue by mathe1** [openlayers/openlayers#14128]
When I rotate the view with the mouse, each intermediate step is displayed correctly and remains there as soon as I release the left mouse button.

Except in the range between -5° and +5° does the view reset to 0° as soon as I release the mouse button.

How can I make it work in this range as well as in the other 350°?

**To Reproduce**
1. move pointer into view
2. hold left mouse button and the key for rotate function
3. move a little bit for some degrees
4. release the mouse button
5. See how the view snap back to 0° rotation

**Expected behavior**
As I rotate to e.g. 3° the fine rotated view should stay at 3° after release the mouse button.

**Comment by mike-000** [comment]
https://openlayers.org/en/latest/apidoc/module-ol_View.html#~ViewOptions
> Rotation constraint. false means no constraint. true means no constraint, but snap to zero near zero. A number constrains the rotation to that number of values. For example, 4 will constrain the rotation to 0, 90, 180, and 270 degrees

That is because the default rotation constraint is `true`.  Specify `constrainRotation: false,` for no snapping.
