### ISSUE TITLE
Low performance for a GeoJSON with a total of 68,921 vertices

### ISSUE THREAD

**Issue by erwinkn** [openlayers/openlayers#14127]
**Describe the bug**
When loading a GeoJSON of 7882 MultiPolygons with a total of 68,921 vertices, the OpenLayers map becomes very slow to navigate. 
Considering OpenLayers can handle [LineStrings with 700,000+ vertices](https://openlayers.org/en/latest/examples/fractal.html), it seems like rendering this amount of vector data should not cause performance issues.

**To Reproduce**
1. Go to https://github.com/erwinkn/openlayers-vector-performance.git
2. Clone the repository and run `npm install` in the root folder
3. Run `npm dev` and navigate to http://localhost:5173/
4. Move around the map

**Expected behavior**
The map is smooth to navigate.

Note: there are quite a lot of exactly overlapping MultiPolygon in that GeoJSON, as it was naively created from a dataset that has multiple rows linked to the same area. I don't know whether this could be the source of the performance issue, but I thought I'd mention it.

**Comment by MoonE** [comment]
LineStrings are simplified on-the-fly; points that result in less than 0.5 pixel distance are simply omitted. Although for each Polygon at least two points are drawn. 

In the example you linked only one LineString exists and it can be simplified very efficiently.
In your example there are lots of low-res polygons which cannot be simplyfied much further so there is not much reduction in data. And as you noted the dupilcate polygons are also detrimental.

For increased performance you can try the new (experimental) webgl renderer for lines and polygons as in https://openlayers.org/en/latest/examples/webgl-vector-layer.html

```js
import { Map, View } from "ol";
import TileLayer from "ol/layer/Tile";
import { OSM, Vector as VectorSource } from "ol/source";
import GeoJSON from "ol/format/GeoJSON";
import WebGLVectorLayerRenderer from "ol/renderer/webgl/VectorLayer";
import Layer from "ol/layer/Layer";
import { packColor } from "ol/renderer/webgl/shaders";
import "ol/ol.css";

class WebGLLayer extends Layer {
  createRenderer() {
    return new WebGLVectorLayerRenderer(this, {
      fill: {
        attributes: {
          color: function (feature) {
            return packColor([255, 255, 255, 0.2]);
          },
        },
      },
      stroke: {
        attributes: {
          color: function (feature) {
            return packColor([0, 0, 200, 0.8]);
          },
          width: function () {
            return 1.5;
          },
        },
      },
    });
  }
}

async function renderMap() {
  const res = await fetch("/electricity_prices.json");
  const data = await res.json();

  const view = new View({
    center: [0, 0],
    zoom: 1,
  });

  const features = new GeoJSON().readFeatures(data, {
    dataProjection: "EPSG:4326",
    featureProjection: "EPSG:3857",
  });

  const source = new VectorSource({
    features,
  });
  new Map({
    target: "map",
    layers: [
      new TileLayer({
        source: new OSM(),
      }),
      new WebGLLayer({ source }),
    ],
    view,
  });

  view.fit(source.getExtent());
}

renderMap();
```

**Comment by ahocevar** [comment]
Alternatively, you can use an `ol/layer/VectorImage` instead of an `ol/layer/Vector`. Or use `geojson-vt`, like shown in the https://openlayers.org/en/latest/examples/geojson-vt.html example.

**Comment by erwinkn** [comment]
Thanks for the suggestions! `geojson-vt` and the experimental WebGL renderer seem to be the best option for my use case.

I have updated my test repository to showcase a comparison between a simple vector layer, a vector tile layer with `geojson-vt`, a WebGL vector layer and the same dataset in MapLibre GL (which also uses WebGL).

In case anyone's interested, here's a live deployment: https://openlayers-vector-performance.vercel.app/
