### ISSUE TITLE
getClosestPoint() delivers wrong coordinates

### ISSUE THREAD

**Issue by motto76** [openlayers/openlayers#14147]
Hello,

I have noticed some strange behavior associated with the getClosestPoint function when drawing.

The following image shows a line being drawn and the point snapped to a LineString feature.
![getClosestPoint-Issue](https://user-images.githubusercontent.com/114415844/192460375-1e93b0ad-4d6e-4012-9197-1b2877394692.PNG)

Depending on the quadrant (red lines including numbers) the mouse pointer is in when clicked, the correct or an incorrect coordinate is determined.
The correct coordinate of the snapped point is: 428340, 5889960 (so it is also in the event:  
![Click-Event](https://user-images.githubusercontent.com/114415844/192460490-e94953cc-1530-4c7f-a5f9-b96bf778e76e.PNG)
)

Event.coordinate returns a clicked position: 
![Event coordinate](https://user-images.githubusercontent.com/114415844/192460602-7a982d1d-6418-4dc5-a9e9-6146e383f9bb.PNG)

What did I try:
```
clickOnMap = map.on('click', (event) => {

console.log(lineStringVectorSource
    .getClosestFeatureToCoordinate(event.coordinate)
    .getGeometry()!
    .getClosestPoint(event.coordinate)

....
```

The results look like this:

Cursor in 1st quadrant -> wrong result:
![Q1](https://user-images.githubusercontent.com/114415844/192460811-1d90f635-588c-4a5d-b283-4e255bcb51c8.PNG)

Cursor in 2nd quadrant -> wrong result:
![Q2](https://user-images.githubusercontent.com/114415844/192460833-779975a0-87d3-4b5c-88d8-0c45afc3c734.PNG)

Cursor in 3rd quadrant -> wrong result:
![Q3](https://user-images.githubusercontent.com/114415844/192460848-50b29be2-856a-49f2-a395-7d28a5a4e5ef.PNG)

Cursor in 4th quadrant -> correct result:
![Q4](https://user-images.githubusercontent.com/114415844/192460856-2a079226-43d9-4a58-a3ac-55f1838798f0.PNG)

In three of the four cases a coordinate value (X or Y) of the click position is returned as part of the coordinate of the closest point.

**Comment by tschaub** [comment]
Hi @motto76 - I haven’t looked closely at the values above yet, but wanted to clarify that the method returns a point on the geometry that is not necessarily one of the vertices.  So the returned coordinate location may be on an edge between two vertices in a line, for example.

**Comment by motto76** [comment]
Hello tschaub,

You are right, the points are on the LineStrings.
What can I do so that I always get the snapped coordinate (as it is in the click-event as 'coordinate_')?

**Comment by MoonE** [comment]
The click event is fired before interactions handle the click event (See code below). The console output may have the snapped coordinate when you expand the object after the snap interaction has handle the event. The console data is displayed somewhat dynamic.
https://github.com/openlayers/openlayers/blob/5e8223ddcb0b55c92345f86cd4418a0ec474fb0f/src/ol/Map.js#L1131-L1142

To get the snapped coordinate you could handle the click in a timeout so it is after the Snap interaction did its thing.
```js
clickOnMap = map.on('click', (event) => {
  setTimeout(function () {
    console.log(lineStringVectorSource
    .getClosestFeatureToCoordinate(event.coordinate)
    .getGeometry()!
    .getClosestPoint(event.coordinate)
  }, 0);
```

**Comment by motto76** [comment]
Thanks MoonE,

I used the "setTimeout" and it works now as expected.
