### ISSUE TITLE
Coordinate type could be more explicit

### ISSUE THREAD

**Issue by rooby** [openlayers/openlayers#14166]
**Describe the bug**
The Coordinate type is `number[]`, however it would more accurately be `[number, number]`

**Comment by MoonE** [comment]
In many cases Coordinate can be also three or four numbers.
http://localhost:8080/apidoc/module-ol_geom_Geometry.html#~GeometryLayout

Maybe change it to something like `[number, number] | [number, number, number] | [number, number, number, number]` in the meantime and have different typedefs for coordinates with only xy and coordinates with more number in the long run.

**Comment by rooby** [comment]
@MoonE  Oh yeah, I forgot about that. Thanks.

**Comment by tschaub** [comment]
Nothing in the library limits the number of dimensions in a coordinate.   I’m not sure it makes sense for the type to do so.

**Comment by rooby** [comment]
Ah ok, no worries. Thanks for the quick reply.
