### ISSUE TITLE
Latest Chromium warns about canvas's willReadFrequently

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#14175]
**Describe the bug**
Getting a warning from latest Chromium:
> Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

https://github.com/openlayers/openlayers/blob/daf604b0a83e841d0ebbf9e79d7f6a7a18a540ce/src/ol/render/canvas/ExecutorGroup.js#L222-L228

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/custom-hit-detection-renderer.html
2. Move the mouse over the map
3. See warning in console

**Expected behavior**
Maybe its worth investigating a performance gain here.

Also warns at this line:
https://github.com/openlayers/openlayers/blob/daf604b0a83e841d0ebbf9e79d7f6a7a18a540ce/src/ol/style/IconImage.js#L111

**Comment by lwz7512** [comment]
Same issue for me, nowhere to set canvas context parameter `setting` for method ` createCanvasContext2D` with:

```
const canvas = document.createElement(‘canvas’);
const ctx = canvas.getContext(‘2d’, {willReadFrequently: true});
```

**Comment by ahocevar** [comment]
I'm going to create a pull request to address this. We don't want to set `willReadFrequently: true` for all contexts we create. Only for those we use for hit detection and style symbols.
