### ISSUE TITLE
performance issue when adding vector layers to openLayers map where it's consuming too much memory/GPU usage when upgrading to v.6 and v.7

### ISSUE THREAD

**Issue by eddyadaimy** [openlayers/openlayers#14177]
I was updating Openlayer from version 5 to version 7 since I use it for my web application and it seems I'm experiencing performance issues where it consumes too much memory and GPU power. I tried using vector image layer rather than vector layer, but there was no difference. Additionally, my web application requires over 200 vector layers, all of which were functional in version 5, but in versions 6 and 7, it completely stalls (where it's affecting the zooming and mouse event functionality). any advice on this matter?

**Comment by ahocevar** [comment]
Can you share a minimal reproduction case that shows the issue?

**Comment by nobodo** [comment]
Not sure if this helps, but I have noticed similar behaviour with vector tile layers (with MVT format) and after some investigations I noticed that the tile queue gets saturated and does not get cleared at any point. I have also experienced cases where the map was trying to load tiles without obeying the minZoom/maxZoom limits that I have set for the source. This was happening when I was using ol-mapbox-style for the styling (and setting the zoom limits).

After setting the sources & urls in more traditional way, things started to work much nicer.

**Comment by eddyadaimy** [comment]
I was using className property for my vectorLayers, so i removed it and set my own class_name property inside property attribute

**Comment by ahocevar** [comment]
@digoburigo `ol/layer/Base` and subclasses have a `className` config option. For each subsequent layer with a different `className`, a new rendering canvas is created. By not using different `className` for each layer, the original poster's performance issue was fixed.

@nobodo That seems unrelated, but if you're seeing issues with `ol-mapbox-style`, please report them on https://github.com/openlayers/ol-mapbox-style/issues/new.
