### ISSUE TITLE
CSS transform scale interferes with interactions (mouse/touch events)

### ISSUE THREAD

**Issue by didkan** [openlayers/openlayers#14179]
**Describe the bug**
If the map, or a ancestor, is scaled using css transform scale(), mouse and touch events get offset.
It is like the anchor coordinate for the interaction (eg DoubleClickZoom, MouseWheelZoom, PinchZoom) is calculated using the original size.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/zoom-constrained.html
2. Open dev tools, find the `id="map"` element and add `transform: scale(0.5)` to it (to effectively scale the map to half its size)
3. Hover the map and double click or mouse wheel zoom and see that the anchor point used when zooming is not directly under the mouse cursor.

**Expected behavior**
Zooming should use an anchor point directly under the mouse cursor.

**Comment by mike-000** [comment]
See also #13283
