### ISSUE TITLE
Can we use tailwind css in openlayers?

### ISSUE THREAD

**Issue by elamandeep** [openlayers/openlayers#14182]
can we use tailwind css in openlayers? I am facing difficulty.

**Comment by nboisteault** [comment]
I think you'll get answers if you tell which difficulties you're facing.

**Comment by elamandeep** [comment]
I think map is not visible may be conflict between tailwind css file and openlayer css file. 
Here's the code below 👇

[test.zip](https://github.com/openlayers/openlayers/files/9747571/test.zip)

**Comment by elamandeep** [comment]
> I think map is not visible may be conflict between tailwind css file and openlayer css file. Here's the code below 👇
> 
> [test.zip](https://github.com/openlayers/openlayers/files/9747571/test.zip)
> 
> But it's working in codesandbox . Don't know why?🤔 https://codesandbox.io/s/openlayer-tailwind-mey8ij?file=/src/App.js


### Issue fixed .
Just include ol.css file path inside css file.
```css

@import "../node_modules/ol/ol.css";

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base{

  html,body{
    @apply m-0 w-full;
  }
}

``` 
after that process is same as per given in tailwind css docs
