### ISSUE TITLE
ol.style.Icon.getSize() returns null

### ISSUE THREAD

**Issue by si-ev** [openlayers/openlayers#14181]
OpenLayers verison: 7.1.

Suppose I want to put a marker on my map and then to get its size. The following code

```
 myMarker = new ol.style.Icon({ src: './marker.png' });  
 console.log('Marker size', myMarker.getSize());
```
returns null

while 

```
 myMarker = new ol.style.Icon({ src: './marker.png' });
 setTimeout( () => console.log('Marker size', myMarker.getSize(), 500);
```

returns correct dimensions.

That's, probably, because I didn't specified image size parameter in the icon constructor, so the correct dimensions were set only after the EventType.LOAD occured.

**Comment by MoonE** [comment]
> That's, probably, because I didn't specified image size parameter in the icon constructor, so the correct dimensions were set only after the EventType.LOAD occured.

Yeah, that's correct. 

Are you seeing a problem with that? What would be your expected behaviour?
