### ISSUE TITLE
There is a problem with tile loading

### ISSUE THREAD

**Issue by MADAO-Chen** [openlayers/openlayers#14198]
**Describe the bug**
When moving or zooming the map, there will be tile stuck occasionally. After observing the console, there is no error, tile request is normal
![WechatIMG124](https://user-images.githubusercontent.com/57648957/195820573-d4408543-a57a-4d3b-a1f8-c099fe2edd20.png)

**Comment by tschaub** [comment]
That does look like a problem.  Please bring you application to the shop in the morning.  We should have it all fixed are ready for pick up at the end of the day.

**Comment by MADAO-Chen** [comment]
This is my problem.I manipulate canvas rotate() in the style renderer function
