### ISSUE TITLE
Allow interactive `HTMLCanvasElement`  in IconStyle

### ISSUE THREAD

**Issue by JakobMiksch** [openlayers/openlayers#14202]
**Is your feature request related to a problem? Please describe.**

In the [IconStyle](https://openlayers.org/en/v6.14.1/apidoc/module-ol_style_Icon-Icon.html) it is possible to add a `HTMLCanvasElement` to the `img` property. This works well for static `HTMLCanvasElement`s. But now I have an interactive `HTMLCanvasElement` that reacts on mouse hover. It is rendered as static image, but does not react on mouse interaction within the map.

Is it possible to add interactive `HTMLCanvasElement`s in IconStyles, is there any settings I have missed?

**Describe the solution you'd like**

It should be possible to add interactive `HTMLCanvasElement`s to IconStyles.

**Comment by ahocevar** [comment]
An icon style will always just render the image represented by the SVG. If you want to use an interactive SVG, use `ol/Overlay` instead.

**Comment by JakobMiksch** [comment]
Thanks for the answer. I am closing.
