### ISSUE TITLE
ol.control.Control - Hover & Text copy

### ISSUE THREAD

**Issue by thn80** [openlayers/openlayers#14224]
Hello,

in my example at [https://codepen.io/gott18/pen/NWzKgGq](https://codepen.io/gott18/pen/NWzKgGq) there is an ol.control.Control element which has some default transparency on hover. How can I disable this transparency on hover?

Furthermore, it is not possible to select the text in the Control to copy it. Can this also be changed? If 'yes', how?

Thanks a lot in advance,

Thomas

**Comment by ahocevar** [comment]
Either don't give your custom control the `ol-control` class, or use css to override the semi-opaque background color, e.g.
```css
div.mycontrol:hover {
  background-color: #ffffff;
}
```

**Comment by thn80** [comment]
Thanks for the hint, this works for the transparency.

Is it also possible to make the text in the Control selectable via the mouse to be able to copy it?

**Comment by ahocevar** [comment]
Sure, just set
```css
.mycontrol {
  -webkit-user-select: text;
}
Note that all content inside the map viewport is set to `-webkit-user-select: none`, so you have to override that for elements where you want text selection to work.
