### ISSUE TITLE
geometry.getExtent is not a function error with property called 'geometry'

### ISSUE THREAD

**Issue by rdewit** [openlayers/openlayers#14220]
**Describe the bug**
OpenLayers 7.1 gives the following error when a GeoJSON feature has a `geometry` property that it cannot handle: 

**TypeError** `geometry.getExtent is not a function`

**To Reproduce**
1. Go to the [forked GeoJSON example](https://codesandbox.io/s/geojson-forked-5dsjn3?file=/main.js:2123-2178) 
2. Note that there is one feature with a property called `geometry` with a string value `foobar`
3. See error
4. It looks like internally, feature.getGeometry calls `this.get('geometry')`, where it assumes that the property value is actually an instance of Geometry where, in this case, it's a string.

**Expected behavior**
OL should not give an error when a feature has a `geometry` attribute.

**Comment by ahocevar** [comment]
`geometry` is the default geometry name, so if you're expecting features with a `geometry` property that is not the feature's geometry, you have to configure the GeoJSON format with a different `geometryName`, e.g.
```js
new GeoJSON({geometryName: 'geom'});
```
See https://codesandbox.io/s/geojson-forked-jg48kx?file=/main.js for an updated codesandbox with the correct configuration.

**Comment by rdewit** [comment]
@ahocevar, unfortunately this is not a real solution when one does not have control over the data.

I'm a bit puzzled why a feature attribute/property that happens to have the same name as the `geometryName` should override the geometry that has been set previously using `setGeometry` with that attribute/property using `setProperties`.

There must have been a good reason for the `geometry` field sharing the storage (in `values_`) with the feature attributes/properties but it is error prone. For what it's worth: other libraries that I tried out to find out what was wrong with our GeoJSON did not trip over (I used http://geojson.io/ and https://geojsonlint.com/ which use mapbox and Leaflet respectively).

I guess this is not easily fixed (if you agree this is not an ideal situation) as it would require the geometry property to be isolated from the feature attributes.

**Comment by ahocevar** [comment]
@rdewit You're right, but you can solve the problem without knowing anything about the data you're consuming. Just set `geometryName` to something that is very unlikely to be used as attribute, e.g. `roalds_fancy_geometry_field`.

The `Feature` class we're currently using is a candidate for removal, in favor of GeoJSON or another simple object literal. So the problem will disappear in a future version.

**Comment by rdewit** [comment]
@ahocevar, thanks, that's a good workaround. I'll close the issue.
