### ISSUE TITLE
calculation function

### ISSUE THREAD

**Issue by lovesL** [openlayers/openlayers#14223]
Hello, may I ask if openlayers is similar to ArcGIS to calculate whether two features intersect or cross

**Comment by mike-000** [comment]
OpenLayers does not have a method for finding intersection between two geometries unless one is a point or extent, but you can integrate third party libraries such as turf.js

For any combination of LineStrings and Polygons
```
const format = new GeoJSON();
const intersects = (turf.lineIntersect(format.writeFeatureObject(feature1), format.writeFeatureObject(feature2)).features.length > 0);
```
or for combinations of Polygons and MultiPolygons
```
const format = new GeoJSON();
const intersects = (turf.intersect(format.writeFeatureObject(feature1), format.writeFeatureObject(feature2)) !== null);
```
For an example using `lineIntersect` see https://stackoverflow.com/a/67446689/10118270
