### ISSUE TITLE
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true

### ISSUE THREAD

**Issue by NeluQi** [openlayers/openlayers#14221]
![image](https://user-images.githubusercontent.com/16963395/196656222-6465f2f9-ada8-408c-93aa-ac50e90abaae.png)

Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

**Comment by ahocevar** [comment]
See #14203, #14204, #14215 for those that are already fixed. Are you seeing this warning in any other context still, after `npm install ol@dev`?

**Comment by westsiderz** [comment]
Is this fix available in the Production version?

**Comment by adilorenzodema** [comment]
> See #14203, #14204, #14215 for those that are already fixed. Are you seeing this warning in any other context still, after `npm install ol@dev`?

Sorry, Which is the fixed ol version?

**Comment by ahocevar** [comment]
Now with `ol@latest` (v7.2.2)

**Comment by jpellizzari** [comment]
Upgrading to `7.2.2` fixed the issue for me. Thanks!
