### ISSUE TITLE
Reprojection with EPSG.io Search not working

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#14235]
**Describe the bug**
The Reprojection with EPSG.io Search example is not working with many projections.
In any version since 6.6.0 projections such as 27700 and 3031 are not working.  Presumably something has changed in the epsg.io response as later v6 versions used to work.  Earlier versions do still work.

**Comment by mike-000** [comment]
3031 is now working, the 27700 definition is causing an error in proj4 2.7.4 and above

**Comment by mike-000** [comment]
A simple fix would be to remove any `+nadgrids` from the proj4 definitions - the difference would not be noticeable at the scale of the example reprojections.  However this also affects #14122 and at a local level the difference if `+nadgrids` is discarded is significant - a GeoJSON projected on to an EPSG:27700 basemap would be displaced by about 100 meters https://codesandbox.io/s/simple-forked-q3dv3b?file=/main.js compared with definitions using either `+towgs84` or `+datum=OSGB36`.

**Comment by ahocevar** [comment]
This looks like an ugly workaround. A better workaround would be to use https://spatialreference.org/ instead of https://epsg.io/.

A better fix would be to see if @klokan would be able to add an API parameter to tell epsg.io to prefer a parameter transform over a grid transform, or to provide the grid files referenced in the projection definitions as part of the API.

**Comment by klokan** [comment]
We are keen to help to fix this properly... and assist with this PR.

The latest epsg.io supports the higher quality transformations which Proj9 allows... but it is usable with older Proj/Proj4js as well of course.
 
The API provides a list of available transformations with ?transformations=true - so it is only about filtering the unsupported away - and picking from those supported the one with the highest accuracy... similarly to how it is done on https://epsg.io/transform 

We could start to use the standard OpenLayers MapTiler API provided for OL examples... the EPSG Coordinates API is properly documented at: https://docs.maptiler.com/cloud/api/coordinates/

**Comment by AliFlux** [comment]
I second that. The maptiler coordinates API is more suitable for this use-case, because we can pick (or ignore) a transform from the list according to our client compatibility

**Comment by mike-000** [comment]
> A better workaround would be to use https://spatialreference.org/ instead of https://epsg.io/.

It seems the EPSG.io wkt definitions are compatible with proj4 without having to load the grid files, and with datum give a better result than simply disregarding the `nadgrids`.
