### ISSUE TITLE
MousePosition control reports invalid coordinates when world wraps

### ISSUE THREAD

**Issue by pkExec** [openlayers/openlayers#14231]
**Describe the bug**
MousePosition control reports invalid coordinates when world wrap is on (default).

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/mouse-position.html
2. Pan the map horizontally. Notice how longitude exceeds valid values(-180 to 180) when map wraps.
![Capture](https://user-images.githubusercontent.com/7925305/197560392-d7d1988b-ddec-480a-90a7-84f97180152e.JPG)

**Expected behavior**
The control should report correct coordinates regardless of world wrapping.

**Possible regression of https://github.com/openlayers/openlayers/issues/3899** ?

**Comment by ahocevar** [comment]
This is not a regression, but a duplicate of #3899. So I created a fix in #14232.
