### ISSUE TITLE
How to stop map event(singleclick)

### ISSUE THREAD

**Issue by MADAO-Chen** [openlayers/openlayers#14243]
**Describe the bug**
`js 
new Select().on('select',funcction(e){
console.log('select')
})

new Map().on('singleclick',funciton(e){
console.log('singleclick')
})

`
echo：
singleclick
select

**To Reproduce**
https://codepen.io/MADAO-Chen/pen/KKRLzBq

**Expected behavior**
stop map event singleclick

**Comment by M393** [comment]
You can use `stopPropagation` for this:
```js
map.on("singleclick", function (e) {
  console.log("singleclick", e);
  e.stopPropagation();
});
```

**Comment by MADAO-Chen** [comment]
> You can use `stopPropagation` for this:
> 
> ```js
> map.on("singleclick", function (e) {
>   console.log("singleclick", e);
>   e.stopPropagation();
> });
> ```

use 'stopPropagation' ,the 'select' event does not trigger

**Comment by M393** [comment]
As the map event is fired before interactions are handled you need to delay event handling:
```js
new Select().on('select',funcction(e){
  console.log('select');
  e.mapBrowserEvent.singleClickHandled = true;
})

new Map().on('singleclick',funciton(e){
  setTimeout(function () {
    if (e.singleClickHandled) {
      return;
    }
    console.log('singleclick');  
  }, 0);
});
```
