### ISSUE TITLE
Scaling ol.style.Circle - Ugly Result

### ISSUE THREAD

**Issue by thn80** [openlayers/openlayers#14240]
Hi,

in my example at [https://codepen.io/gott18/pen/WNyvprQ](https://codepen.io/gott18/pen/WNyvprQ) I created an ellipsis by scaling ol.style.Circle and recognized that the result looks very ugly (pixelated, different stroke width between top/bottom and left/right).

Is there any chance to make an ellipsis used in a style more beautiful (without using an image file as icon)?

Thanks,

Thomas

**Comment by mike-000** [comment]
When scaling RegularShape and Circle styles pixelation can be avoided by setting a larger radius then scaling down:

      radius: 80,
      scale: [1, 0.25],


To avoid scaling the stroke set the style geometry as an ellipse https://codepen.io/mike-000/pen/ExRjmvB

**Comment by ahocevar** [comment]
You could use a custom symbol, like shown in https://openlayers.org/en/latest/examples/earthquake-custom-symbol.html. In your example, it could look like this: https://codepen.io/ahocevar/pen/MWXwmqx
```js
const canvas = document.createElement('canvas');
canvas.width = 200;
canvas.height = 50;
const ctx = canvas.getContext('2d');

// Draw the ellipse
ctx.beginPath();
ctx.ellipse(100, 25, 24, 98, Math.PI / 2, 0, 2 * Math.PI);
ctx.strokeStyle = 'red';
ctx.lineWidth = 2;
ctx.stroke();

var stylefn = function() {
  return new ol.style.Style({
    image: new ol.style.Icon({
      img: canvas,
      imgSize: [canvas.width, canvas.height]
    })
  });
};
```
