### ISSUE TITLE
Missing city in Belgium

### ISSUE THREAD

**Issue by axiertech** [openlayers/openlayers#14249]
Somehow, Zwinjdrecht, Antwerpen does not show up in the query:
https://nominatim.openstreetmap.org/search.php?q=Zwinjdrecht,Antwerpen,Belgium&format=jsonv2

Not a big place, has some sister names in other countries, but still, it is a place on the map where people live :)

**Comment by vmarc** [comment]
Try Zwijndrecht instead of Zwinjdrecht.

**Comment by axiertech** [comment]
Thanks, wasn't sure where the issue was. But a spelling mistake is of course not an open layers issue.
Also, another query shows strange results.
This one works perfect in the browser:
https://nominatim.openstreetmap.org/search.php?q=Upplands%20V%C3%A4sby,Sverige&format=jsonv2
But shows nothing when fetched with curl.
All other curl-respones are without problems, only this one returns emtpy with curl.

**Comment by vmarc** [comment]
curl query works ok for me when I put the url between double quotes. Still, issues with nominatim queries are unrelated to OpenLayers I think.

**Comment by axiertech** [comment]
What does your curl call look like?

**Comment by ahocevar** [comment]
This is the OpenLayers issue tracker. For issues with OpenStreetMap data, please go to https://openstreetmap.org/. Thanks!
