### ISSUE TITLE
Automatically call updateSize when target element is rendered in shadowDom slot

### ISSUE THREAD

**Issue by MichielKadaster** [openlayers/openlayers#14247]
**Is your feature request related to a problem? Please describe.**
When a target element is is added to webcomponent slot, the map remains blank.
The reason for this is that the map starts to render when target element is added to DOM at its original location (not in the slot); however, the target element is then copied into the shadowRoot of the webcomponent and remains blank.
To prevent this issue, you have to call updateSize() after listening to the `slotchange` event of the webcomponent.

Example code HTML where a openlayers target element is a assigned to a slot of the `webcomponent-map` webcomponent:
```html
<webcomponent-map id="map-webcomponent">
    <div id="openlayers-map-target" slot="map-slot"></div>
</webcomponent-map>
```

JS code to update the map by listening to slotchange event:
```js
this.querySelector("#map-webcomponent").shadowRoot.addEventListener('slotchange', () => {
    this.map.updateSize();
});
```

**Describe the solution you'd like**
It would be a nice feature if OpenLayers would be able to check whether the target element is rendered by listening to the `slotchange` event.
I don't know if that's possible but I think it would solve some issues for many users.
Other users seem to set a timeout (See: https://stackoverflow.com/questions/60775376/i-cant-display-the-openlayer-map-properly-until-after-a-window-resize), which would not be optimal as you don't know how when the slot element is done rendering.
It took us quite some time to figure out what caused the timing issue and come up with the solution to listen to the `slotchange` event.
Otherwise, I think it would be great if this behaviour (and the slotchange solution) would be described in the documentation as webcomponents are becomming more and more popular.

**Comment by tschaub** [comment]
Thanks for the report and for the work figuring this out, @MichielKadaster.

It sounds like a good addition to have the map listen for `slotchange` on the target element.  I think that could be done by adding an additional listener here: https://github.com/openlayers/openlayers/blob/428354cbfca1c4580cb41a655d4e277bcb7b32e8/src/ol/Map.js#L1297

Would you be willing to put together a pull request?

**Comment by MichielKadaster** [comment]
I looked into it a little more and I'm not sure it's possible, unfortunately.
The `slotchange` event is fired from the webcomponent (not the target element).
The slotted element (i.e. the target element) does not seem to have an event which fires when the element is slotted.
Only the webcomponent itself has an event which fires when its slots change.
As far as I can see there is no way to add a listener to the event when only the target element is known.

Unless there is some other way, I think the `updateSize` function cannot be called by OL but only from the users code.
So I think it would be best to mention this somewhere in the documentation until someone comes up with a solution.
