### ISSUE TITLE
Could not load pbf format data from ArcGIS FeatureServer/MapServer by ol.format.MVT class

### ISSUE THREAD

**Issue by RicardoHWu** [openlayers/openlayers#14244]
From [FeatureLayer](https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer-.htm) and [MapServer](https://developers.arcgis.com/rest/services-reference/enterprise/query-map-service-layer-.htm) document we know that the FeatureServer or the MapServer support pbf as response format since 10.7.1, but I can't convert arraybuffer to features by the **readFeatures** function in **ol.format.MVT** class, here is my code
```
let vectorTileLayer = new ol.layer.VectorTile({
        source: new ol.source.VectorTile({
            format: new ol.format.MVT(),
            tileUrlFunction:(tileCoord)=>{
                let currentExtent= tileGrid.getTileCoordExtent(tileCoord);
                return 'https://services3.arcgis.com/GVgbJbqm8hXASVYi/arcgis/rest/services/Trails/FeatureServer/0' +
                    '/query/?f=pbf&' +
                    'returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=' +
                    encodeURIComponent('{"xmin":' +currentExtent[0] +',"ymin":' +currentExtent[1] +',"xmax":' +currentExtent[2] +',"ymax":' +currentExtent[3] + '}') +
                    '&geometryType=esriGeometryEnvelope&inSR=102100&outFields=*&resultType=tile' +
                    '&outSR=102100';
            }
        })
    });
```
My openlayers version is 6.14.0. Thanks  for all

**Comment by mprins** [comment]
ths service requires a token, did you set that? 
https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/Public_Wildfire_Perimeters_View/FeatureServer/?f=pjson

**Comment by RicardoHWu** [comment]
> 

I test this code with a local feature service and replace with a online service when writing this issus. Now I replace a service from the ArcGIS JS Smaple without token, can you please try it again？ 
**https://services3.arcgis.com/GVgbJbqm8hXASVYi/arcgis/rest/services/Trails/FeatureServer/0**

**Comment by mike-000** [comment]
It seems to be an Esri-specific pbf implementation https://github.com/Esri/arcgis-pbf/tree/main/proto/FeatureCollection  You would probably need a custom format based on the Esri parser to read features (otherwise use an Openlayers supported format, your code works if `/query/?f=pbf&` and `new ol.format.MVT()` are replaced with `/query/?f=json&`  and `new ol.format.EsriJSON()`).

**Comment by RicardoHWu** [comment]
> It seems to be an Esri-specific pbf implementation https://github.com/Esri/arcgis-pbf/tree/main/proto/FeatureCollection You would probably need a custom format based on the Esri parser to read features (otherwise use an Openlayers supported format, your code works if `/query/?f=pbf&` and `new ol.format.MVT()` are replaced with `/query/?f=json&` and `new ol.format.EsriJSON()`).

I will try it later, Thanks for your suggestion

**Comment by mike-000** [comment]
There is a third-party parser available which will convert an ERSI pbf into a GeoJSON object.  That will allow ESRI pbf to be used directly in OpenLayers by subclassing the GeoJSON format https://codesandbox.io/s/simple-forked-k2wlg6?file=/main.js
