### ISSUE TITLE
Raster Reprojection codesandbox examples are not working.

### ISSUE THREAD

**Issue by StreetLamb** [openlayers/openlayers#14242]
I am encountering `Cannot read properties of undefined (reading 'WGS84')` while running these codesandbox examples that have proj4 as dependency:
- [Raster Reprojection](https://codesandbox.io/s/2yws18)
- [Reprojection with EPSG.io Search](https://codesandbox.io/s/l90hi1)
- [Image Reprojection](https://codesandbox.io/s/srbkrl)

However, dropping proj4 version from `2.8.0` to `2.3.15` seems to solve the issue.

**Comment by mike-000** [comment]
A recent codesandbox update seems to have a introduced a problem when importing proj4, examples which do not involve OpenLayers are also affected.  Using old versions of proj4 may have compatibility issues, a quick fix to continue using the latest proj4 with codesandbox is to add `<script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.8.0/proj4.js"></script>` to the html and comment out the import.

**Comment by StreetLamb** [comment]
Thank you for your input and suggestion. I will close this since it's an unrelated issue.
