### ISSUE TITLE
Questions to FullScreen-Control

### ISSUE THREAD

**Issue by motto76** [openlayers/openlayers#14255]
I'm experimenting with the FullScreen Control (OL 6.14.1) and have some questions (no idea if I'm in the right place).

1. Can I swap the default button from OL for my own?
2. Is it possible to hide the button of the control and then tell the control via event or similar that I want to switch to FullScreen mode and back again?

**Comment by MoonE** [comment]
This should toggle fullscreen with a custom button:
```js
const control = new FullScreen();
map.addControl(control);
const yourButton = document.createElement('button');
yourButton.innerText = 'Click me';
document.body.appendChild(yourButton);
yourButton.addEventListener('click', function () {
  control.element.querySelector('button').click();
});
```
Hide the control with css:
```css
.ol-full-screen { display: none; }
```

You may not need to have your own custom button though. You can use the `target` option to place it somewhere else and you can style it pretty much to your liking with the other options and some custom css.
https://openlayers.org/en/latest/apidoc/module-ol_control_FullScreen-FullScreen.html

**Comment by motto76** [comment]
Thanks for the tips.
