### ISSUE TITLE
Can element outside the map be dragged into the map

### ISSUE THREAD

**Issue by zhangminggeek** [openlayers/openlayers#14250]
I can't listen for any events when I'm dragging elements outside the map into the map, anyone who can help me please, thanks

**Comment by M393** [comment]
You should be able to handle the dropping on the map target element:
```js
map.getTargetElement().addEventListener('drop', function (event) {
  console.log('Element dropped');
});
```
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event

**Comment by M393** [comment]
This should get you the coordinate at the event location: 
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#getEventCoordinate

**Comment by zhangminggeek** [comment]
> This should get you the coordinate at the event location: https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#getEventCoordinate
> 
> ```js
> map.getTargetElement().addEventListener('drop', function (event) {
>   const coord = map.getEventCoordinate(event);
>   console.log('Element dropped at', coord);
> });
> ```

I got result [13373331.557173893, 3538458.466011465]，This is clearly wrong. Is there something wrong?

**Comment by M393** [comment]
By default the view projection is in EPSG:3857. If you expect EPSG:4326 you need to [convert](https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.toLonLat) it:
```js
toLonLat(coord)
```
The coordinate in EPSG:4326:
```js
[
  120.13468137407227,
  30.27120419528896,
]
```

**Comment by zhangminggeek** [comment]
> By default the view projection is in EPSG:3857. If you expect EPSG:4326 you need to [convert](https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.toLonLat) it:
> 
> ```js
> toLonLat(coord)
> ```
> 
> The coordinate in EPSG:4326:
> 
> ```js
> [
>   120.13468137407227,
>   30.27120419528896,
> ]
> ```

That's great. It worked. You saved me.
