### ISSUE TITLE
WebGLTile can't show with google map

### ISSUE THREAD

**Issue by laydll** [openlayers/openlayers#14254]
![image](https://user-images.githubusercontent.com/49605772/199468803-914a3867-591e-4273-b265-b4e5326ae9e7.png)

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/49605772/199468910-d5bc9484-8ebc-49d4-a0f7-6c7773295ede.png">

WebGLTile can't show with google map, but i seem the network of get image form google map is success, why it can't show in the page

**Comment by mike-000** [comment]
WebGL needs cross-origin access to images.  This is requested automatically when tiles are rendered directly, but if you are reprojecting a tile source such as XYZ which does not have a `crossOrigin` default you need specify `crossOrigin: 'anonymous'`.

**Comment by laydll** [comment]
> 

thank you~, after i add `crossOrigin = 'anonymous'`, it can work now

![image](https://user-images.githubusercontent.com/49605772/199638539-35c2c6ba-8562-4bb8-be50-8e951760cb73.png)
