### ISSUE TITLE
getting Unimplemented type: 4 error while consuming vector tiles

### ISSUE THREAD

**Issue by geogeek11** [openlayers/openlayers#14261]
When I try to consume vector tiles, I get the following error : 

Error: Unimplemented type: 4
Which points to the [line](https://github.com/mapbox/pbf/blob/bfaaa5daea7e2a57e5e0b22cca75037113000e33/index.js#L207) in [pbf project](https://github.com/mapbox/pbf)

I have tested the issue with ol@7.1.0 and ol@6.4.1 and it occurs in both versions.

This a minimal example to reproduce the issue

      import 'ol/ol.css';
      import React, { useEffect } from 'react';
      import { Map } from 'ol';
      import MVT from "ol/format/MVT";
      import VectorTileLayer from "ol/layer/VectorTile";
      import VectorTileSource from "ol/source/VectorTile";
      import View from 'ol/View';
      import { OSM } from 'ol/source';
      import TileLayer from 'ol/layer/Tile';

      function App() {
        useEffect(() => {
          
          const vt = new VectorTileLayer({
            declutter: true,
            renderMode: "vector",
            source: new VectorTileSource({
              format: new MVT(),
              url: "http://localhost:3000/vt/tiles/{z}/{x}/{y}.pbf"
            })
          });
      
          const map = new Map({
            layers: [
              new TileLayer({
                source: new OSM(),
              })
              ,
              vt
            ],
            view: new View({
              center: [-13629900, 4544290],
              zoom: 10,
            }),
          });
      
          map.setTarget("map")
        }, []);
      
      
      
      
        return (
          <div className="App">
            <header className="App-header">
              <div id="map" style={{ height: "100vh", width: "100vw" }} ></div>
            </header>
          </div>
        );
      }
      
      export default App;

I have tried to tile the vector tiles using multiple tools such as Tippecanoe, Geoserver(XYZ tiles), and Maptiler engine. none of them solves the issue.

**Comment by ahocevar** [comment]
The first thing to do is to configure the `VectorTileSource` with
```
minZoom: 3,
maxZoom: 11,
```
to match the zoom levels you have available.

The second thing to do is to configure the `VectorTileSource` also with the `extent` you have tiles available for. If that's not possible, make sure that you serve the tiles in a way that a 404 status is returned from tiles that do not exist. I assume the error comes from the fact that when requesting an inexistent tile, you get a HTML error page with a 200 status instead of a tile.

**Comment by geogeek11** [comment]
Thanks a lot
