### ISSUE TITLE
Interaction Link modification

### ISSUE THREAD

**Issue by Wockeez** [openlayers/openlayers#14276]
At the moment, the latest version of openlayers has an interaction Link that has query parameters x,y,z,r,l, it may be possible to determine the display in the address bar of the browser of choice. For example, only x,y or y,z. And by default, all data in the address bar will be displayed.
The problem is that I can have 100 vector layers and the `l` parameter in the request can be very large, I would like to hide its display from the address bar in the browser

<img width="695" alt="image" src="https://user-images.githubusercontent.com/59292278/200295523-f43369c2-3fff-43a6-95a8-2c947456e3db.png">

**Comment by ahocevar** [comment]
Please upgrade to the latest dev version of OpenLayers

    npm install ol@dev

There you can configure which parameters you want to include:
```js
new Link({
  params: ['z', 'x', 'y']
});

**Comment by Wockeez** [comment]
Thanks, it worked, I would like to see this functionality in the next release
