### ISSUE TITLE
How to accomplish what registerLayerRenderers([]) previously handled?

### ISSUE THREAD

**Issue by Tomcariello** [openlayers/openlayers#14289]
Hi! I'm new to openlayers & have been exploring the API & various projects. I noticed that `registerLayerRenderers` worked in v5.3.3 but not in v7.1.0. What is the recommended approach to accomplish this same task in the current version of OL?

I'm sorry if this is the wrong place to ask this. I've searched & found others asking but no responses. ([stackoverflow](https://stackoverflow.com/questions/64868433/how-to-use-api-in-ol6-instead-of-map-getrenderer-registerlayerrendererslayer))

Thanks! I appreciate all the effort you have put into this application!

**Comment by ahocevar** [comment]
Without knowing what you want to achieve, I can only give a very general answer on this question about a non-API method:

There is no need to register a layer renderer on the map any more. You can now configure a layer directly with an appropriate renderer. In the simplest case by defining a `render` function on the `Layer` constructor, like shown in https://openlayers.org/en/latest/examples/svg-layer.html. Or - and this is also non-API - by overriding a `Layer`'s `createRenderer` method.

**Comment by Tomcariello** [comment]
For context, I am researching possibilities of implementing a wind-map in OL ([windy.com](https://www.windy.com/?39.215,-76.754,5)). I came across [ol-wind](https://github.com/gberaudo/olwind) & was attempting to get it to work with the current version of OL.

Thanks for the feedback. I will review that example & see what I can do.
