### ISSUE TITLE
Select interaction no longer works after upgrading from 6.15.1 to 7.1.0

### ISSUE THREAD

**Issue by easbar** [openlayers/openlayers#14283]
This used to work  with OL 6.15.1 (taken from the mapbox-vector-tiles example):

```javascript
const layer = 
    new VectorTileLayer({
      declutter: true,
      source: new VectorTileSource({
        format: new MVT(),
        url:
          'https://{a-d}.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/' +
          '{z}/{x}/{y}.vector.pbf?access_token=' +
          key,
      }),
      style: createMapboxStreetsV6Style(Style, Fill, Stroke, Icon, Text),
    })
    
// this is the code that no longer seems to do what it was supposed to do:    
const hover = new Select({
	condition: click,
	style: null,
	layers: [layer],
	hitTolerance: 5
})
hover.on('select', () => {
	console.log('hello')
})
map.addInteraction(hover)
```

But with OL 7.1.0 it no longer works (nothing is logged to the console when I click a feature). Same thing when I use the `pointerMove` condition instead of `click`.

**Comment by ahocevar** [comment]
The Select interaction never worked with `ol/render/Feature` features. Your example sort of worked with v6.15.1 in a way that it fired the `select` event, but selection also did not work. Now the `Select` interaction only handles `ol/Feature` instances to avoid these issues in the first place (see https://github.com/openlayers/openlayers/commit/44289a3a31adaf9c554769dcb9c806037be2045c#diff-8346a3db45b41a588250b4a5108efe79945d826e22fa47f1a7c5d9accc84c8ed).

You have two options:
1. Configure the `MVT` format with `featureClass: Feature`
2. Do not use the `Select` interaction, which does not make sense for `VectorTile` layers anyway. For your use case, I think it would be enough to use `map.getFeaturesAtPixel()`. Or look at https://openlayers.org/en/latest/examples/vector-tile-selection.html for a proper way to select features from a `VectorTile` layer.

**Comment by easbar** [comment]
Thanks a lot for your quick reply :heart: 

> Configure the MVT format with featureClass: Feature

Yes, this works!

> Do not use the Select interaction, which does not make sense for VectorTile layers anyway.

Oh, ok. Can you explain why this doesn't make sense? Basically we use a VectorTileLayer to show a layer of lines (like all the roads of a city) that is served in Mapbox Vector Tile format and I'd like to be able to hover the single roads to show a little popup on top of the map, so we need to execute some code whenever the select event is fired:

https://github.com/graphhopper/graphhopper-maps/blob/f24e27526336c848d08e9b1291c7c263a15518fc/src/layers/UseRoutingGraphLayer.tsx#L57-L104

**Comment by M393** [comment]
The Select interaction tracks Feature objects. As each tile has its own Features the select interaction only tracks the Feature for that exact tile. Ideally you should track features by their id. The feature id should be same on all tiles if they are correctly generated.

**Comment by easbar** [comment]
> For your use case, I think it would be enough to use map.getFeaturesAtPixel()

Ok, that also seems to work. I did something like this:

```javascript
const layer = 
    new VectorTileLayer({
      declutter: true,
      source: new VectorTileSource({
        format: new MVT(),
        url:
          'https://{a-d}.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/' +
          '{z}/{x}/{y}.vector.pbf?access_token=' +
          key,
      }),
      style: createMapboxStreetsV6Style(Style, Fill, Stroke, Icon, Text),
    })
    
map.on('click', (e) => {
    const features = map.getFeaturesAtPixel(e.pixel, {
        layerFilter: l => l ===layer,
        hitTolerance: 5
     })
    console.log(features)
})    
```
