### ISSUE TITLE
How openlayers works under the hood?

### ISSUE THREAD

**Issue by elamandeep** [openlayers/openlayers#14299]
Hello 👋 Openlayers team! I want to know how openlayers works under the hood? And any suggestion regarding `JS framework` that I can use with `openlayers`.

**Comment by ahocevar** [comment]
OpenLayers is object oriented and imperative. For a map, it needs a container element, which can be a simple div element in the docunebt (as shown in the majority of the [examples](https://openlayers.org/en/latest/examples/)), but also works in a shadow DOM (as shown in https://openlayers.org/en/latest/examples/es2015-custom-element.html).

For more specific information, please ask more specifically.

**Comment by elamandeep** [comment]
Thanks
