### ISSUE TITLE
Changelog v7.0.0 release

### ISSUE THREAD

**Issue by pelord** [openlayers/openlayers#14306]
**Describe the bug**
There is a strange change in the changelog. 

`Remove Mou...`

![image](https://user-images.githubusercontent.com/7397743/202283014-a30025e7-88e7-4474-aca5-23b947492b95.png)

**Comment by ahocevar** [comment]
I see the full changelog on https://github.com/openlayers/openlayers/releases/tag/v7.0.0. Where were you looking?

**Comment by pelord** [comment]
https://github.com/openlayers/openlayers/releases

**Comment by ahocevar** [comment]
Maybe GitHub is cropping the release notes of each release on that view to keep it scrollable.

**Comment by pelord** [comment]
Exact. Its not a real issue... But feel free to fix it or not!

**Comment by ahocevar** [comment]
We cannot change that - it's a GitHub feature.
