### ISSUE TITLE
Incorrect rendering in vector context of rotated tile layers

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#14308]
**Describe the bug**
As described in https://github.com/openlayers/openlayers/issues/14168#issuecomment-1318248557  rendering to the vector context of tile layers breaks down close to view rotations of 90 and 270 degrees, affecting stroke width, text scale and precision of geometry.

**To Reproduce**
Compare vector context rendering on a tile layer https://codesandbox.io/s/scalerings-forked-srro95 at close to 90 degrees rotation with the expected behavior seen if using the vector context of a vector layer https://codesandbox.io/s/scalerings-forked-iub5kx

It can also be seen in the Flight Animation example which has both a tile layer and a vector layer used for completed flights, but uses the vector context of the tile layer for animating flights in progress.  The Marker Animation example which uses the vector context of its vector layer is not affected.

**Expected behavior**
Consistency in the vector contexts of tile and vector layers.

**Comment by ahocevar** [comment]
Do you have any clue what the reason for that behavior is, @mike-000 ?

**Comment by mike-000** [comment]
I suspect it is related to the transform used to construct the CanvasImmediateRenderer.  I resurrected an old codesandbox of the Icon and Label Scale example which included vector context, and added a option for using the context of either layer https://codesandbox.io/s/icon-scale-new-forked-h6ghu3?file=/main.js  Icon and text scale and rotate with view are all inconsistent when the raster layer context is used when rotated.
