### ISSUE TITLE
Slow performance at box selection example

### ISSUE THREAD

**Issue by ynixt** [openlayers/openlayers#14316]
**Describe the bug**
Clicking on any feature causes lag. Text on "Selected regions" and style of features takes too long to being update after the click.

A screenshot of chrome performance tab on the click time
![image](https://user-images.githubusercontent.com/6382990/202606836-ba0349fe-ee85-4c20-92e1-25a3e01a560e.png)

**To Reproduce**
1. Open ['box selection example'](https://openlayers.org/en/latest/examples/box-selection.html)
2. Click on any feature
3. See the lag

I was also be able to reproduce locally on versions 7.1.0 and 7.1.1-dev.1668701704879

**Expected behavior**
No lag :)

**Comment by mike-000** [comment]
For an immediate response in a Select interaction you need `condition: click`.  The default `condition: singleClick` has a 250ms delay to ensure it is not the first of a double click.

**Comment by ynixt** [comment]
> For an immediate response in a Select interaction you need `condition: click`. The default `condition: singleClick` has a 250ms delay to ensure it is not the first of a double click.

Unfortunately this not solves the problem. I have tested with both conditions. Also.. the delay is between 1 and 1.5 seconds.
The crazy thing is that [select hover features example](https://openlayers.org/en/latest/examples/select-hover-features.html) has no delay.

**Comment by mike-000** [comment]
How does that compare with the Select Features example https://openlayers.org/en/latest/examples/select-features.html with Hover action type selected?

**Comment by ynixt** [comment]
> How does that compare with the Select Features example https://openlayers.org/en/latest/examples/select-features.html with Hover action type selected?

I got confused the "condition" with "toggleCondition". With condition click I was able to have no delay.
Very thanks!
