### ISSUE TITLE
Canvas2D: Multiple readback operations using getImageData warning

### ISSUE THREAD

**Issue by keepitrealsimple** [openlayers/openlayers#14322]
**Describe the bug**
Chrome gives warning "Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true." when calling map.getFeaturesAtPixel or map.forEachFeatureAtPixel functions quick few times.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/vector-tile-info.html with Chrome
2. Zoom in/out and move mouse fast over info points
3. See warning in console

**Expected behavior**
Map application should work without warnings.

**Comment by mprins** [comment]
please check reported issues and fixes before filing another duplicate issue: https://github.com/openlayers/openlayers/issues?q=willReadFrequently

**Comment by keepitrealsimple** [comment]
My bad. I thought that those fixes were already deployed in 7.1.0 and so reported new issue. I will close this report.
