### ISSUE TITLE
Cloud Optimized GeoTIFF (COG) example url 404 not found

### ISSUE THREAD

**Issue by mrpan** [openlayers/openlayers#14329]
**Describe the bug**
![image](https://user-images.githubusercontent.com/3354097/203025467-dbc674bc-df59-4e1e-b1a3-8315d4775836.png)
![image](https://user-images.githubusercontent.com/3354097/203025546-4565050a-5d9a-4195-a22d-b459fb94ec04.png)

**Comment by mike-000** [comment]
Already fixed in dev version https://openlayers.org/en/main/examples/cog.html
