### ISSUE TITLE
View.fit - the rotation of the map is discarded

### ISSUE THREAD

**Issue by gonzobard777** [openlayers/openlayers#14335]
## Describe the bug
I do this:
```javascript
const view = new View();

const map = new Map({
  layers: [
    new TileLayer({
      source: new OSM(),
    }),
    new Graticule({
      showLabels: true,
      wrapX: true,
    }),
  ],
  target: 'map',
  view,
});

view.fit([
  ...fromLonLat([169.73848463261447, 41.47716968829406]),
  ...fromLonLat([215.7069052351526, 77.18482550711026]),
]);
```

### Expected behavior

The extent is selected on the map, which has a rotation.
When I pass such an extent to a new map, I expect that the rotation will not go away, that is, the result should look like this:

![expected](https://user-images.githubusercontent.com/45559041/204003665-dc99986b-bbdd-436d-92fb-3c1598814e03.png)

### How the map is behaving now

As you can see - the rotation of the map encoded in the extent has disappeared somewhere:

![behaving_now](https://user-images.githubusercontent.com/45559041/204005807-825f7e1f-272b-4184-a003-fc089d5eabe1.png)

## To Reproduce
Please see the prototype:
https://stackblitz.com/edit/js-ufcbdg

**Comment by ahocevar** [comment]
An `extent` is a rectangle defined by the southwest and northeast corner. It is impossible to encode rotation in a rectangle defined by two opposite corners.

**Comment by gonzobard777** [comment]
ok.
Is it possible to encode a rotation from a polygon?

![expected2](https://user-images.githubusercontent.com/45559041/204011971-5c24c608-22a7-456d-a048-ef8a6dfcb350.png)

I did like this:

```javascript
view.fit(
  new Polygon([
    [
      [...fromLonLat([152.91 , 72.87])],
      [...fromLonLat([215.71 , 77.18])],
      [...fromLonLat([232.37 , 52.91])],
      [...fromLonLat([169.74, 41.48])],
      [...fromLonLat([152.91 , 72.87])],
    ],
  ])
)
```

but the rotation is not taken into account on the map again

**Comment by ahocevar** [comment]
`fit()` will always just adjust center and zoom of the view, and use the current view rotation. To achieve what you want, you'd have to calculate the rotation from one of the polygon's edges, e.g.
```js
const viewportPolygon = new Polygon([
  [
    [...fromLonLat([152.91, 72.87])],
    [...fromLonLat([215.71, 77.18])],
    [...fromLonLat([232.37, 52.91])],
    [...fromLonLat([169.74, 41.48])],
    [...fromLonLat([152.91, 72.87])],
  ],
]);
const topLeft = viewportPolygon.getCoordinates()[0][0];
const topRight = viewportPolygon.getCoordinates()[0][1];

const rotation = Math.sin(topLeft[1] - topRight[1] / topLeft[0] - topRight[0]);

view.fit(viewportPolygon);
view.setRotation(rotation);
```

**Comment by gonzobard777** [comment]
godly!
thank you!
