### ISSUE TITLE
COG - GeoTIFF is not defined 

### ISSUE THREAD

**Issue by Gaetanbrl** [openlayers/openlayers#14330]
> OpenLayers 7.1.0

**Describe the bug**

I try to create a COG layer with simple ol.js and ol.css file import from HTML (no package or npm env).

So, i use this code as geat example : 

https://codesandbox.io/s/cog-forked-3314si?file=/main.js:554-671

But when i'd just try to create GeoTIFF source i get this error all the time :  

> GeoTIFF is not defined 

```
ol.js:1 Uncaught ReferenceError: GeoTIFF is not defined
    at Qh (ol.js:1:198796)
    at new ic (ol.js:1:199966)
    at <anonymous>:1:1
```

This is the code : 

```
let tiffSrc = new ol.source.GeoTIFF({
    sources: [{
        url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/21/H/UB/2021/9/S2B_21HUB_20210915_0_L2A/TCI.tif'
    }, ]
})
```

**To Reproduce**

Need a simple OpenLayers lib import without NPM or build or whatever :

1. open browser
2. open console
3. try this code :

```
tiffSrc = new ol.source.GeoTIFF({
    sources: [{
        url: 'https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/21/H/UB/2021/9/S2B_21HUB_20210915_0_L2A/TCI.tif'
    }, ]
})
```

**Expected behavior**

Create GeoTIFF source.

**Comment by ahocevar** [comment]
When using the full build, you also need to add the geotiff.js library in a script tage before OpenLayers. See https://github.com/geotiffjs/geotiff.js/#usage.

**Comment by Gaetanbrl** [comment]
Thanks @ahocevar , this works better ! I think this issue will help many native web coder.
I close.
