### ISSUE TITLE
What's the best way to use to openlayers with threejs via aync/await?

### ISSUE THREAD

**Issue by MeRahulAhire** [openlayers/openlayers#14336]
Hi @ahocevar, I'm trying to make a 3D demo of Nasa's black marble by utilising both React-three-fiber and openlayer as a [canvasTexture](https://r105.threejsfundamentals.org/threejs/lessons/threejs-canvas-textures.html) to my sphere. 

I'm using a `ImageLayer` to load an image size of 5MB in dimension of 13500 x 6750px which takes few second to load. The problem is Threejs's [textureloader](https://threejs.org/docs/#api/en/loaders/TextureLoader) work asynchronously. so It fires up even before the canvas is properly loaded and gives me the following error: 
```bash
THREE.WebGLRenderer: Texture marked for update but no image data found.
```
**This is my code inside OpenLayers component**
```js
import Map from "ol/Map";
import View from "ol/View";
import TileLayer from "ol/layer/Tile";
import ImageLayer from "ol/layer/Image";
import Static from "ol/source/ImageStatic";
import Projection from "ol/proj/Projection";
import { useEffect } from "react";

export default function OpenLayers() {
  useEffect( async() => {
    var map = new Map({
      target: "map",
      view: new View({
        projection: "EPSG:4326",
        extent: [-180, -90, 180, 90],
        center: [0, 0],
        zoom: 2,
        maxZoom: 10,
      }),
    });
    const image_2016 = new ImageLayer({
      source: new Static({
        url: "/assets/img/BlackMarble_2016.webp",
        projection: new Projection({
          code: "BlackMarble_2016",
          units: "pixels",
          extent: [-180, -90, 180, 90],
        }),
        imageExtent: [-180, -90, 180, 90],
      }),
    });
    map.addLayer(image_2016);
}, []);
  return (
    <>
      <div id="container" style={{ height: '0', overflow: "hidden" }}>
        <div id="map" style={{ height: "6570px", width: "13500px" }}></div>
      </div>
    </>
  );
}
```

And I'm calling canvas directly in other component independent of this `OpenLayers` component and both are actually inside of a parent component `app.jsx`
```js
const mapContainer = document.getElementById("map");
      const mapCanvas = useRef(mapContainer.getElementsByTagName("canvas")[0]);
      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    
      if (mapCanvas.current) {
        mapCanvas.current.needsUpdate = true;
      }
         <mesh
            name="Sphere"
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
          >
            <meshStandardMaterial>
              <canvasTexture
                ref={textureRef}
                attach="map"
                image={mapCanvas.current}
                flipY={false}
              />
            </meshStandardMaterial>
          </mesh>
```
From this [conversation](https://github.com/pmndrs/react-three-fiber/discussions/2638) in R3F git, Paul Henschel suggested me if I can make openlayer work asynchronously I can solve this issue.

So my question is how how do I approach it? I'm aware of #12509 but I didn't got when should I use and when to avoid `'postrender'` or `'rendercomplete'`. Should I create ref inside of postrender function and then pass it via `forwarRef`?

I've stuck on this from past 3 days, your suggestion will be utmost helpful for me. 
I'd love to hear your take on it.

**Comment by MeRahulAhire** [comment]
Edit : One thing I've realised it that this issue can be mitigated if `OpenLayer` has a way to tell when the canvas is completely loaded. 
@ahocevar, is there any way to get this working? I tried forwardRef and all but they didn't seemed to work. This is my [codeSandbox Demo](https://codesandbox.io/s/ol-r3f-99e1gs?file=/src/nasa-black-marble/comp/earth.jsx) in case if you need more information.

**Comment by ahocevar** [comment]
The easiest way to do something the canvas finished rendering all contents for the current viewport is to use
```js
map.once('rendercomplete', () => {
  // do something with the rendered map contents
});

**Comment by MeRahulAhire** [comment]
oh, Thanks for that, I'll use it with `useState` but I've encountered with another problem that my static images are getting blurred on canvas. They aren't as crisp like original image. Code is same as per above only width and height are changed to match the image dimension?

**Original image : 8000x4000px**
![BlackMarble_2012_8k webp (8001×4000) - Google Chrome 29-11-2022 16_20_29](https://user-images.githubusercontent.com/42251052/204510535-17946f26-69ff-48e4-929d-9cba2bd0f289.png)

**OpenLayer's version**
![BlackMarble_2012_8k webp (8001×4000) - Google Chrome 29-11-2022 16_23_47](https://user-images.githubusercontent.com/42251052/204511194-f3c51f5d-218d-4067-9842-2f1827d4fe3e.png)

Now due to GitHub's compression the difference may not be significant but its clearly visible on my end. Any idea on how to solve it @ahocevar?

**Comment by MeRahulAhire** [comment]
Any suggestions @ahocevar...

**Comment by ahocevar** [comment]
I don't think this is related to the topic of this issue.

**Comment by MeRahulAhire** [comment]
Ok I'll create another issue.
