### ISSUE TITLE
Cursor doesn't snap to features when the view is rotated 45 degrees

### ISSUE THREAD

**Issue by rooperl** [openlayers/openlayers#14343]
**Describe the bug**

Cursor doesn't snap to features if the view is rotated 45/135/225/315 degrees.

**To Reproduce**

Demo: https://codesandbox.io/s/ol-rotation-snap-problem-btt58d?f=

1. Draw two points on the map
2. Try drawing a linestring between the two points
3. → Cursor doesn't properly snap to the points

**Expected behavior**

Cursor should snap to features if the view is rotated 45 degrees.
See the original snap interaction demo: https://openlayers.org/en/latest/examples/snap.html

**Comment by mike-000** [comment]
Also the tolerance is noticeably reduced at other angles, e.g. at 60 degrees the tolerance on the x axis is about half of what is expected, while the y axis is relatively unaffected.

It should be working as expected in https://deploy-preview-14344--ol-site.netlify.app/en/latest/examples/snap.html
