### ISSUE TITLE
Make Draw interactions sketchFeature_ available

### ISSUE THREAD

**Issue by attrib** [openlayers/openlayers#14357]
**Is your feature request related to a problem? Please describe.**

When drawing a line I added a overlay with a cancle and confirm button, so the user can easily finish drawing the line. Also when right clicking I remove the last point. For this to work I need to know the current points of the feature, the user is currently drawing.

![image](https://user-images.githubusercontent.com/679305/205441363-44828add-fe72-423c-8e5e-59ce742c1190.png)

This is the code I'm currently using:

```javascript
    this.draw = new Draw({
      type: 'LineString',
      features: null,
      stopClick: true,
      style: this.style(),
      minPoints: 2,
      condition: (event) => {
        if (event.type === 'pointerdown') {
          // Right click remove last point
          if (event.originalEvent.button === 2) {
            this.draw.removeLastPoint()
            if (this.draw.sketchFeature_ && this.draw.sketchFeature_.getGeometry().getCoordinates().length > 2) {
              const coords = this.draw.sketchFeature_.getGeometry().getCoordinates();
              this.confirmOverlay.setPosition(coords[coords.length - 1])
              this.cancelOverlay.setPosition(coords[coords.length - 1])
            }
            else {
              this.confirmOverlay.setPosition(undefined)
              this.cancelOverlay.setPosition(undefined)
              if (!this.draw.sketchFeature_) {
                this.map.removeInteraction(this.draw) // no points left, right click remove drawing
              }
            }
            return false
          }
          // Left click add new point
          else if (event.originalEvent.button === 0) {
            if (this.draw.sketchFeature_ && this.draw.sketchFeature_.getGeometry().getCoordinates().length > 1) {
              this.confirmOverlay.setPosition(event.coordinate)
              this.cancelOverlay.setPosition(event.coordinate)
            }
            return true
          }
        }
        return false
      }
    });
```

**Describe the solution you'd like**

The function works, but has the down sight I'm using `sketchFeature_` which is a `private` variable of the Draw interaction.

Would be nice if there would be a official supported way to retrieve the `sketchFeature` while drawing.

**Comment by MoonE** [comment]
You can use the drawstart event to get the sketch feature:
https://github.com/openlayers/openlayers/blob/1e3d0de6c31011a845b1acd498f38445fb15c4ee/src/ol/interaction/Draw.js#L1502-L1504

**Comment by attrib** [comment]
Stupid me, forgot if I get it from there I have it as reference and have always the updated version.

That what I forgot to think about.

Big thanks for the quick response and examples.
