### ISSUE TITLE
export-map example extracting canvas blocked by firefox

### ISSUE THREAD

**Issue by pnoe** [openlayers/openlayers#14363]
Hi,
with https://openlayers.org/en/latest/examples/export-map.html
in latest Firefox (all extensions disabled) on latest Ubuntu,
when clicking "Download PNG" I have the following message in the console : 

Blocked https://openlayers.org/en/latest/examples/export-map.html from extracting canvas data because no user input was detected. [export-map.js:102:26]

and the map.png file is not the map.

With chromium, no error in console and the file map.png is fine.

Bye, many thanks for openlayers !

​

**Comment by pnoe** [comment]
https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting
"Some websites, particularly those using HTML5 Canvas, look at this unique combination of factors and assign you a number, or a “fingerprint”, which makes you identifiable across the Web. This “fingerprint” is potentially used to profile you for targeted content without the use of cookies. "

**Comment by ahocevar** [comment]
So to fix this, we'd have to trigger the png url creation upon a user interaction, e.g. click on the button. @pnoe, do you think you'd be able to provide a pull request with such a change?

**Comment by pnoe** [comment]
@ahocevar , I would be delighted to do that but I'm afraid this is beyond my skills (javascript with modules, openlayers repository organisation, git pull requests...) !
Sorry.

**Comment by pnoe** [comment]
Strange, I tried again with the same result : message in console, no user message and garbage downloaded as map.png.
With Firefox windows or android it works well without any user message. 
I sent a message to mozilla support...

**Comment by pnoe** [comment]
Mozilla support response :
Do you have "privacy.resistFingerprinting" enabled in about:config?

And yes it was enabled, and back to "false" solved the problem.
Sorry !
