### ISSUE TITLE
ClusterLayer is showing inconsistent number of features based on zoom level

### ISSUE THREAD

**Issue by frodobaggins23** [openlayers/openlayers#14365]
**Describe the bug**

Hi,

I have a strange issue with `ol/source/Cluster` layer. 

Let me describe our usecase first ...

We use clusters to visualise number of devices on the map. 

```
import { Cluster } from 'ol/source';
import VectorSource from 'ol/source/Vector';

  const clusterSource = new Cluster({
      distance: 50,
      source: new VectorSource(),
    });

    this.machinePositionsLayer = new VectorLayer({
      source: clusterSource,
      updateWhileAnimating: true,
      updateWhileInteracting: true,
      style: this.getMachinePositionsStyle,
      zIndex: 6,
      className: 'telematics',
    });
```
Each device in the layer is represented as a Feature added to the source of ClusterSource layer
```
const vectorSource = (this.machinePositionsLayer.getSource() as Cluster).getSource();

const feature = new Feature({
        geometry: new Point(transform(
          x.location.coordinates[0],
          this.transformOptions.dataProjection,
          this.transformOptions.featureProjection,
        )),
      });

vectorSource?.addFeature(feature);
```
of course, we clear the source layer every time we add/remove items

```
 vectorSource?.clear();
```

styling features is done via a dedicated style function that creates different styles based on number of features in the cluster (either an individual icon or clustered circle)

```
 this.machinePositionsLayer = new VectorLayer({
      source: clusterSource,
      updateWhileAnimating: true,
      updateWhileInteracting: true,
      style: this.getMachinePositionsStyle, // <----- this is the styling fn
      zIndex: 6,
      className: 'telematics',
    });

...
getMachinePositionsStyle = (feature: Feature, resolution: number) => {
    const features = feature.get('features');
    const size = features.length;

    if (size > 1) {
      const strokesStyles = this.getMachineClusterStrokesStyles(features);

      const machineClusterStyle = [
        new Style({
          image: new CircleStyle({
            radius: MAIN_MAP_TELEMATICS_MACHINE_CLUSTER_CIRCLE_RADIUS - 1,
            stroke: new Stroke({
              color: MAIN_MAP_TELEMATICS_MACHINE_CLUSTERS_COLORS.DEFAULT,
              width: MAIN_MAP_TELEMATICS_MACHINE_CLUSTER_STROKE_WIDTH,
            }),
            fill: new Fill({
              color: '#ffffff',
            }),
          }),
          text: new Text({
            text: size.toString(),
            font: 'bold 16px Arial',
            fill: new Fill({
              color: MAIN_MAP_TELEMATICS_TEXT_COLOR,
            }),
            offsetY: 1,
          }),
        }),
        ...strokesStyles,
      ];

      return machineClusterStyle;
    }

    const machinePosition: PositionDetailTo = feature.get('features')[0].get('machinePosition');

    const machine: PositionMachineTo | undefined = machinePosition.machine;
    const driver: PositionDriverTo | undefined = machinePosition.driver;

    const hasNeededResolution = resolution < 5;

    // https://openlayers.org/en/latest/examples/rich-text-labels.html
    const machineText = [
      `${machine?.name ?? machine?.gpsUnit ?? ''}`, 'bold 14px Roboto',
      ` ${machine?.licencePlate ?? machine?.gpsUnit ?? ''}`, '',
    ];
    const driverText = [
      '\n', '',
      `${driver?.name ?? ''}`, 'bold 14px Roboto',
    ];
    const isSelected = this.selectedMachineGpsUnit === machine?.gpsUnit;

    const singleMachineStyle = new Style({
      image: new Icon({
        src: isSelected ? this.getMachineStrokeIcon(machine?.group) : this.getMachineIcon(machine?.group),
        scale: 1.25,
        rotation: machinePosition.azimuth || 0,
      }),
      text: hasNeededResolution ? new Text({
        text: driver ? [...machineText, ...driverText] : machineText,
        fill: new Fill({
          color: MAIN_MAP_TELEMATICS_TEXT_COLOR,
        }),
        font: 'normal 14px Roboto',
        placement: 'point',
        textAlign: 'left',
        backgroundFill: new Fill({ color: '#fff' }),
        padding: [10, 10, 6, 10],
        offsetX: 40,
      }) : undefined,
    });

    return singleMachineStyle;
  }

```

**The problem is ...**

Under some circumstances (not always, but frequently) when the user zooms in and out, some devices "disappear" from the clusters. Typically, the more the user zooms out, the less items are visible (either clustered or as individual icons). Even more, the styling function receives less features in such case. (!!)

zoom 0
![image](https://user-images.githubusercontent.com/46576318/205992059-0625241a-5b78-49cb-a5d9-70a5b12f19e5.png)

in the styling function
```
(feature: Feature, resolution: number) => {
    const features = feature.get('features');
    const size = features.length;

// size [10,3,1,1,1]
// resolution [some number]

```

zoom -1
![image](https://user-images.githubusercontent.com/46576318/205992321-8a702855-3136-4643-8d50-4557871c2fd2.png)

in the styling function
```
(feature: Feature, resolution: number) => {
    const features = feature.get('features');
    const size = features.length;

// size [10,1,1]
// resolution [some number -1]

```

zoom -2
![image](https://user-images.githubusercontent.com/46576318/205992386-f4f99c94-94aa-44b0-978d-8dd8bc2f1ed8.png)

in the styling function
```
(feature: Feature, resolution: number) => {
    const features = feature.get('features');
    const size = features.length;

// size [4,1]
// resolution [some number -2]

```

As the styling function receives different number of features in different zoom levels I suppose the problem cannot be in the styling itself but rather elsewhere.
We do NOT add or remove any items to/from the layer during user visual interactions (moving around the map, zooming). The number of items in the layer should be the same all the time.

As I mentioned earlier, this problem does not occur always (on every zoom interaction). Unfortunately, I was not able to identify the exact moment when this happens. Sometimes the cluster appear OK, sometimes not. I have strong suspicion that the occurrence of this problem might depend on the relative position of the individual features.

**Expected behavior**
The clusters should always show all features , not just some. No matter what the zoom level is, the sum of icons + numbers in the clusters should always equal the total number of features in the layer. 

Could you pls help me investigate what is going wrong here?

Many thanks

**Comment by ahocevar** [comment]
You'll probably find out yourself when you create a minimal standalone example to reproduce the issue. This would also increase the likelihood that someone can help you here.

**Comment by frodobaggins23** [comment]
It turned out it was a problem with the data. Some geometries were coming with incorrect latitude (over 90deg) and transform function was returning `NaN`. Therefore broken points were not showing in the map and when clustered, they "killed" the respective cluster. 

I am closing this ticket.
