### ISSUE TITLE
Make `ol/style/flat#toStyle()` an API method

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#14367]
**Is your feature request related to a problem? Please describe.**
While the flat style syntax is intended for static styling it can make code more legible if the syntax is used to define styles later used in complex style functions, for example https://codesandbox.io/s/measure-style-forked-2xyr16?file=/main.js.  This requires the `toStyle()` method, which is not part of the API.

**Describe the solution you'd like**
Document the `toStyle()` method as part of the API (maybe also moving the import to `ol/style.js`?).  Alternatively a new API method which can also handle `Array<FlatStyle>` and return `Array<Style>`.  Also, while is it reasonable that `text-value` should not be undefined, if an empty string is specified it should be allowed.

**Comment by JakobMiksch** [comment]
I would find this useful as well. My use case is to create a basic style using the flat style notation. And afterwards I would like to add more advanced style functionality, like adding a custom geometry. Here a example how I could image such an implementation:

```js
// style defined in the flat style, but afterwards we have a regular style object
const blueLineStyle = toStyle({
              "stroke-color": "blue",
              "stroke-width": 2,
            })

// now we have access to all functions of a regular style object
blueLineStyle.setGeometry(myGeometry)

```

**Comment by mike-000** [comment]
'ol/style/flat#toStyle()' was removed in version 8.  You can write your own function to do what is used to do

```
function toStyle(flatStyle) {
  const styles = new VectorLayer({style: flatStyle}).getStyleFunction()(new Feature());
  return styles.length > 1 ? styles : styles[0];
}
```

**Comment by jahow** [comment]
@JakobMiksch supporting geometry modification on the fly is something that the flat style format will have to address at some point. Could you maybe describe a bit more why you're using the geometry function on your style? We might be able to provide common use cases such as computing a centroid, simplifying a geometry etc. and I'd be curious to hear if your use case falls into this.

**Comment by JakobMiksch** [comment]
Hi @jahow in my use case I have a point layer where many points reference other points somewhere else. To visualize that I need three styles:
1. the original point
2. the referenced point (with a custom geometry)
3. and a line string to connect both of them

the original point I can style using the flat style, but the referenced point I cannot, because there I need to set a custom geometry.

I can easily work around this, by using the traditional styling notation. But from the dev experience point of view, it would be much more convenient to style all different points with flat style.

**Comment by JakobMiksch** [comment]
here an attempt to have this function in TypeScript:

```ts
/**
 * Convert a flat style to a classic OpenLayers style
 * @param flatStyle The flat style to convert to
 * @returns The classic version of the style
 */
const toStyle = (flatStyle: FlatStyle): Style[] | Style | undefined => {
  const vectorLayer = new VectorLayer({ style: flatStyle })
  if (!vectorLayer) return
  const styleFunction = vectorLayer.getStyleFunction()
  if (!styleFunction) return
  const newFeature = new OlFeature()
  const fakeResolution = 1
  const styleResponse = styleFunction(newFeature, fakeResolution)
  if (!styleResponse) return

  if (Array.isArray(styleResponse)) {
    return styleResponse?.length > 1 ? styleResponse : styleResponse[0]
  } else {
    return styleResponse
  }
}

```

**Comment by alphaandromeda** [comment]
Hi,

I tried the following approach:
```
function toStyle(flatStyle) {
  const styles = new VectorLayer({style: flatStyle}).getStyleFunction()(new Feature());
  return styles.length > 1 ? styles : styles[0];
}
```

But without success. My flatstyle comes from an external json-file (and works for a vectorlayer) but not for [ol/interaction/Select], so I tried to convert the flatstyle to a real style.

This is how I load data:
```
    $.getJSON ('ExternalStyle.json', function(data) 
    {
         let theRealStyle = toStyle (data); // returns null!
    }
```

This is the jsonfilecontent:
```
[
  {
    "filter": ["==", ["get", "symkey"], 11010101],
    "icon": "minus",
    "style": {
    "stroke-color": "green", 
    "stroke-width": 8 
    }
  },
  
   {
    "filter": ["==", ["get", "symkey"], 14000100],
    "style": {
    "fill-color": "#ff0000b3"
    }
  },
   {
    "filter": ["==", ["get", "symkey"], 14000200],
    "style": {
    "fill-color": "#ff7000b3"
    }
  }]
```

I would really apprecciate any help! 
Cheers Mike
