### ISSUE TITLE
CDN problem AddLayer is not defined 

### ISSUE THREAD

**Issue by Tibicenas** [openlayers/openlayers#1436]
Hi, i has the cdn loading OK in my html, and y can see the map, but when i try to add markers or add a geolocation function like this (who has a marker indeed) i get the problem AddLayer is not defined... some help?
direction

  var geolocation = new ol.Geolocation({
    projection: view.getProjection(),
    tracking: true
  });

  $("#js-btn--geolocate").on('click', function(){
    var position = geolocation.getPosition();

    var point = new ol.layer.Vector({
      source: new ol.source.Vector({
        features: [
          new ol.Feature({
            geometry: new ol.geom.Point(position)
          })
        ]
      })
    });
    
    map.addlayer(point);
    view.setCenter(position);
    view.setResolution(2.388657133911758);
    return false;
  });

**Comment by ahocevar** [comment]
The method name is `addLayer`, not `addlayer` nor `AddLayer`.

**Comment by Tibicenas** [comment]
Not working anyway :S

**Comment by ahocevar** [comment]
Your snippet does not show if or where you assign an ol.Map to your map variable. So likely there is something else wrong with your app code.
