### ISSUE TITLE
Rendering strategy

### ISSUE THREAD

**Issue by aparzi** [openlayers/openlayers#14379]
I have to render a large number of data on several layers. Specifically I would like to render, since, 500K figures (between polygons, points and lines). At the moment the map slows down and the browser also becomes very very slow, until it crashes.
How could I handle the situation?

Thanks

**Comment by mike-000** [comment]
See also #9372 and #13409

**Comment by Rskut** [comment]
500.000 Points with webgl probably, 500.000 Polygons no, at least not at once. You can try but you should not show 500.000 geometries at once

**Comment by aparzi** [comment]
@Rskut thanks. 

I have two questions:

1. With what strategy could I show 500K figures if I don't have to upload them at the same time?

1. Do you think openlayers can render reactively 45K figures?

**Comment by Rskut** [comment]
In one of the projects I work on, I had to render about 35K Polygons with relatively complex styles and geometries. It did work well.

Further approaches and information on this topic:
https://www.w3.org/community/maps4html/2020/04/07/better-web-maps-with-new-browser-features/
https://github.com/mapbox/geojson-vt +  https://openlayers.org/en/latest/examples/geojson-vt.html 
https://github.com/openlayers/openlayers/pull/13461

**Comment by aparzi** [comment]
Okay thank you. 
Can i contact you again?

**Comment by aparzi** [comment]
Hi @Rskut,
the geojson-vt library seems to work fine but at the moment only with dots. Does it also support linestrings?

**Comment by Rskut** [comment]
It should support linestrings and polygons too. Tiny linestrings may be filtered out, you should check the documentation

**Comment by aparzi** [comment]
@Rskut 
I solved. But my problem is that I have to zoom a lot to see the linestrings. Do you know why?

**Comment by Rskut** [comment]
@aparzi you could check your options, tolerance or indexMaxPoints f.e.

**Comment by aparzi** [comment]
I solved, thanks. In geojson file the coordinates were wrong.
