### ISSUE TITLE
Codepen link broken in docs

### ISSUE THREAD

**Issue by sebakerckhof** [openlayers/openlayers#14378]
In the docs (e.g. https://openlayers.org/en/latest/examples/wms-tiled.html ), you have an 'edit' button in the right top to open it in codesandbox. But these seem broken and just bring me to a generic page: https://codesandbox.io/api/v1/sandboxes/define

**Comment by mike-000** [comment]
It is working for me now.  Maybe a temporary network issue?

**Comment by sebakerckhof** [comment]
Weird, I still get the error, but did some further testing and I get the error on chrome on linux and firefox on android, but not with edge and firefox on linux and chrome on android.
The issue seems to be that the codepen button is a html link to https://codesandbox.io/api/v1/sandboxes/define, but the button also has a JS click event handler that prevents the default behavior (go to the url) and opens a popup instead. This seems to be blocked in some cases by the browser (or an extension).
I tried incognito mode where I don't have adblockers and there it also failed.

**Comment by mike-000** [comment]
I get that page if I right click the button and select Open in new tab.  Not sure why the button needs an href when the js action is to call `form.submit()`?

**Comment by sebakerckhof** [comment]
Seems no longer to be an issue
