### ISSUE TITLE
Heatmap local maximum

### ISSUE THREAD

**Issue by yotamN** [openlayers/openlayers#14381]
**Is your feature request related to a problem? Please describe.**
There is a weight function which is great to decide how the heatmap looks but something that I don't think is possible to make easily is a local maximum one.

**Describe the solution you'd like**
A way to get the highest dot in the rendered area, I guess I could do it somehow myself but an API from the library could be easier I think.

**Comment by yotamN** [comment]
Actually it doesn't seem I can do it myself, I don't have access to all of the features from inside the weight function (or ideally from a pre function because I don't want to run it for every iteration necessarily)

**Comment by mike-000** [comment]
Declare the max value as a global and recalculate at each change of view state https://codesandbox.io/s/heatmap-earthquakes-forked-wog5nl?file=/main.js

**Comment by yotamN** [comment]
Oh cool, didn't think of `getFeaturesInExtent`, thanks
