### ISSUE TITLE
TypeError parsing GML (target.addEventListener is not a function)

### ISSUE THREAD

**Issue by ghschier** [openlayers/openlayers#14389]
In the Method **GMLBase.readFeatureElementInternal** the nodevalue is put in a wrapper-object, when the node has attributes.
The actual nodevalue has the key "\_content\_" in the wrapper-object, the attributes are pushed as key-value-pairs.

The "getGeometry"-Method of the Feature doesn't take care about that, it gives back the wrapper instead of the geometry.

This results in a TypeError ("target.addEventListener is not a function") in **Feature.handleGeometryChanged_**, because the
first argument given to the listen-method is not a geometry.

**Comment by ahocevar** [comment]
Can you create a test case that shows the problem?

**Comment by ahocevar** [comment]
Thanks, I see. Do you think you'd be able to create a pull request with a fix?

**Comment by ghschier** [comment]
I solved the problem for me by modifying `Feature.getGeometry`, so that it returns the geometry instead of the wrapper. IMO that would be the best solution.

> Do you think you'd be able to create a pull request with a fix?

I didn't do that before. How do I create a pull request?

**Comment by ahocevar** [comment]
This should be fixed in the format, not in `ol/Feature`. See https://github.com/openlayers/openlayers/blob/main/CONTRIBUTING.md#contributing-code for instructions. Thanks in advance.
