### ISSUE TITLE
Typescript: "protected" instead of "private"

### ISSUE THREAD

**Issue by ghschier** [openlayers/openlayers#14392]
I found it often useful, to extend a class and modify its behaviour by overriding internal methods.
This is not possible (anymore), because some methods are declared "private" (Example: **applySelectedStyle_/restorePreviousStyle_** in **interaction/Select**).

IMO internal methods should be declared "protected" instead.

**Comment by ahocevar** [comment]
Private methods and properties are intentionally private. If there's a good case for widening their scope, we can discuss that for individual methods or properties.

**Comment by ghschier** [comment]
Thank you @ahocevar for the reply. OL is a great library and I respect your decision.
But: there are of course (nasty) ways in Typescript to override private methods. It would just make life easier, if they were generally "protected"...

**Comment by ahocevar** [comment]
Well, if you have to go about that with nasty workarounds, you're at least reminded that you're doing something you shouldn't be doing.
