### ISSUE TITLE
can I use openlayers library in react native expo project?

### ISSUE THREAD

**Issue by ikart3689** [openlayers/openlayers#14410]
expo version : 45.0.0
platform : Android

can I use openlayers library in react native expo project and also someone suggest me that openlayers library is used for offline purpose or not?

**Comment by ahocevar** [comment]
The only way to use OpenLayers with React Native is a web view. Offline scenarios are not a problem, using the usual Progressive Web App techniques.

**Comment by ikart3689** [comment]
> The only way to use OpenLayers with React Native is a web view. Offline scenarios are not a problem, using the usual Progressive Web App techniques.

ok thank you

**Comment by ikart3689** [comment]
> The only way to use OpenLayers with React Native is a web view. Offline scenarios are not a problem, using the usual Progressive Web App techniques.
