### ISSUE TITLE
WMS encoding of commas is incorrect

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#1441]
The comma in the BBOX should not be url encoded see also: http://trac.osgeo.org/openlayers/ticket/491 for some background

this came up when comparing WMS requests between OpenLayers and ol3 in https://github.com/openlayers/ol3/issues/1440#issuecomment-31167693

**Comment by bartvde** [comment]
Feel free to submit a PR @stewberticus

**Comment by ThomasG77** [comment]
For people hitting the issue, you can always managed the issue using `imageLoadFunction` without changing code in the library. See below excerpt.
There is maybe a better approach but at least, it's an immediate solution to the issue

```js
const layers = [
  new TileLayer({
    source: new OSM(),
  }),
  new ImageLayer({
    extent: bbox,
    source: new ImageWMS({
      url: url,
      params: {'LAYERS': 'Tache_urbaine_1980_R43'},
      ratio: 1,
      imageLoadFunction: function(image, src) {
        const urlToPatch = new URL(src)
        // Use something like 
        let newUrl = `${urlToPatch.protocol}//${urlToPatch.hostname}${urlToPatch.pathname}?`
        const queryParams = []
        for (const [key, value] of urlToPatch.searchParams.entries()) {
          queryParams.push(`${key}=${value}`)
        }
        newUrl += queryParams.join('&')
        console.log(newUrl)
        image.getImage().src = newUrl;
      }
    }),
  }),
];
```
