### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by aparzi** [openlayers/openlayers#14425]
In a function (renderOnMap) I have the following code:
```js
    const tileIndex = geojsonvt(json, {
      extent: 4096,
      debug: 1,
    });
    const format = new GeoJSON({
      // Data returned from geojson-vt is in tile pixel units
      dataProjection: new Projection({
        code: 'TILE_PIXELS',
        units: 'tile-pixels',
        extent: [0, 0, 4096, 4096],
      }),
    });
    const vectorSource = new VectorTileSource({
      tileUrlFunction: function (tileCoord) {
        // Use the tile coordinate as a pseudo URL for caching purposes
        return JSON.stringify(tileCoord);
      },
      tileLoadFunction: function (tile, url) {
        const tileCoord = JSON.parse(url);
        const data = tileIndex.getTile(
          tileCoord[0],
          tileCoord[1],
          tileCoord[2]
        );
        const geojson = JSON.stringify(
          {
            type: 'FeatureCollection',
            features: data ? data.features : [],
          },
          replacer
        );
        const features = format.readFeatures(geojson, {
          extent: vectorSource.getTileGrid().getTileCoordExtent(tileCoord),
          featureProjection: map.getView().getProjection(),
        });
        tile.setFeatures(features);
      },
    });
    layer.setSource(vectorSource);
    openlayers_service.map.addLayer(layer);
```
my geojson contains 50K figures and the memory rises a bit when I run this function, once the execution is finished the memory doesn't go back to the way it was before, indeed if I run the function several times, it continues to increase.  I noticed that by setting tileIndex as undefined the memory goes back to the way it was before.  This function can be performed multiple times by the user, using a simple checkbox

**Comment by ahocevar** [comment]
This is not a memory leak in OpenLayers. The resources bound by `tileIndex` won't be released, because you're creating them in a closure (i.e. your `renderOnMap` function). This is a memory leak in your application.

**Comment by aparzi** [comment]
Thanks @ahocevar.
Could you advise me how to fix it?

**Comment by aparzi** [comment]
@ahocevar could I declare tileIndex as a global variable and set it to undefined when I don't need it?

**Comment by ahocevar** [comment]
Doesn't have to be global, but outside the `renderOnMap` function or any closure.

**Comment by aparzi** [comment]
I am using angular, so as a variable of a service it would not fit but rather in the function that calls renderOnMap ?

**Comment by aparzi** [comment]
@ahocevar 
I tried to create a function that returns the source vector and then add it to the map of openlayers, but the problem remains. How can I do?

**// Helper class**
```
export function getVectorTileSource(tileIndex, format, projection): VectorTile {
    const vectorTileSource = new VectorTileSource({
        tileUrlFunction(tileCoord) {
            // Use the tile coordinate as a pseudo URL for caching purposes
            return JSON.stringify(tileCoord);
        },
        tileLoadFunction(tile: any, url) {
            const tileCoord = JSON.parse(url);
            const data = tileIndex.getTile(
                tileCoord[0],
                tileCoord[1],
                tileCoord[2]
            );
            const geojson = JSON.stringify(
                {
                    type: 'FeatureCollection',
                    features: data ? data?.features : []
                },
                replacer
            );
            const features = format.readFeatures(geojson, {
                extent: vectorTileSource.getTileGrid().getTileCoordExtent(tileCoord),
                featureProjection: projection
            });
            tile.setFeatures(features);
        },
    });

    return vectorTileSource;
}
```

**// Component A which use Helper class**
```
public async changeValueCheckbox(value) {
    if (value.checked) {
       const vectorTileSource = getVectorTileSource(tileIndex, format, projection);
       layer.setSource(vectorTileSource);
       map.addLayer(layer);
    } else {
       map.removeLayer(layer);
    }
}
```

**Comment by ahocevar** [comment]
Hard to say without seeing that in context. You can always use the Chrome Developer Tools' "Memory" Tab and create a heap snapshot to see where resources are bound.

**Comment by aparzi** [comment]
if I don't add map.addLayer the memory leak doesn't happen

**Comment by aparzi** [comment]
@ahocevar I found my problem. My figures have a great deal of properties. Do you have an idea how to fix it?

**Comment by aparzi** [comment]
@ahocevar any idea?

The properties key, for each feature, contains an array of 50 elements plus other keys.  By setting the empty properties the memory does not increase.  what do you think about it?

**Comment by ahocevar** [comment]
Properties take up memory, but don't cause a memory leak. And OpenLayers will keep the properties in the tile cache. Maybe this is why it looks like a memory leak to you.

**Comment by aparzi** [comment]
Okay understood. If I delete a layer does openlayers clear the cache?  because it seems to me that memory  always busy.

**Comment by aparzi** [comment]
even as I zoomed it took up more memory.  perhaps because I loaded new tiles.

**Comment by ahocevar** [comment]
Correct. The tile cache holds two zoom levels worth of tiles at the current viewport size.

When you remove a layer from the map and remove all references to its source and the layer, garbage collection will eventually get rid of the cached resources.

**Comment by aparzi** [comment]
@ahocevar Thanks.

So to "clean up" the memory don't I just delete the layer with map.removeLayer(layerName) ?

**Comment by ahocevar** [comment]
No. You need to remove all references to the layer and - more important - its source in your application

**Comment by aparzi** [comment]
Okay thanks 😊

**Comment by alex1221** [comment]
@aparzi How did you solve it in the end ? How to release layers and sources?
