### ISSUE TITLE
Geolocation-orientation implementation

### ISSUE THREAD

**Issue by victorfg** [openlayers/openlayers#14420]
Hi there,

I would like to implement into my project this functionality https://openlayers.org/en/latest/examples/geolocation-orientation.html
but I don't find the exemple code like other examples.

Is it somewhere?

Thanks

**Comment by ahocevar** [comment]
See https://github.com/openlayers/openlayers/blob/v7.2.2/examples/geolocation-orientation.js

**Comment by victorfg** [comment]
Thank you @ahocevar , I already implemented in https://catalonia-map-viewer.vercel.app (version mobile not desktop) and I tested in two iphones and works fine in chrome but not in safari. Is it normal?

Thanks

**Comment by victorfg** [comment]
For anyone that test geolocation in Safari and it doesn't work, you have to enable it in _Settings -> Privacy._
