### ISSUE TITLE
How to prevent Polygon simplification in custom style function?

### ISSUE THREAD

**Issue by Rskut** [openlayers/openlayers#14427]
On high zoom levels, when a polygon fills the entire screen, the geometry is simplified.

Here is a fiddle. If you zoom in too closely, you can see in the console that at some point the initial 9 coordinates are reduced to 6-8.

https://jsfiddle.net/dtkoyfsh/6/

Is there any way to prevent this behavior when there are not too many polygons visible in the view?

**Comment by mike-000** [comment]
The geometry should not be simplified if it fits inside the layer's `renderBuffer`. Specifying a large `renderBuffer` will help - but `renderBuffer` cannot be infinite, so simplification could still occur at _very_ high zoom levels.

**Comment by Rskut** [comment]
Thank you, Mike. I have a similar problem to the one you provided an example of. In my case, the text has a custom position based on the non-simplified geometry, which starts to jump because the geometry changes.
