### ISSUE TITLE
Performance drops with many Wms layers

### ISSUE THREAD

**Issue by werrolf** [openlayers/openlayers#14436]
We are seeing drastic, nonlinear performance reduction ("off a cliff") when panning / zooming / rotating an Openlayers map as soon as it contains more than 15~16 Wms image layers, depending on screen size.

With 18 Wms image layers in FullHD on Openlayers 7.2.2, single animation frames can take more than a second. With 17 layers, performance doubles to ~500ms per frame. With 15 layers or less, performance is basically fine (all frames faster than 200ms).

## To reproduce
@ThorstenHi and I have prepared a single-file demo that should show this nicely: https://gist.github.com/werrolf/911bbd428aa453b021d0735547a40f0f

Open this HTML in your browser of choice, wait a few seconds until all layers have finished intial requests, then zoom in one step or try panning.

You can step down the number of layers by adding e.g. `?layers=15` to your url.

Because this definitely depends on the number of pixels rendered, the map is forced to a somewhat FullHDish pixel size.

Note that if you use Chrome Inspector or similar, it should be undocked and ideally placed on a different screen. Otherwise it will improve performance :)

This demo uses the Openlayers 7.2.2 official build from the CDN.

Note that even though these Wms servers are all public access, their operators may not expect high traffic. Please be gentle :)

## Affected versions
This has originally been observed on Openlayers 6.14. Demonstrating this without an official build has proven difficult though.

6.15 and 7.x. Changelogs have mentioned canvas performance / memory usage improvements, so we stepped through these. All in all 7.2.2 is ~10% faster than 6.14. This is impressive in itself, but the nonlinear dropoff remains, and at some point map interactions still get too slow for reasonable use.

As for browsers, I've tried Chromium 83 up to Google Chrome 108 and also Firefox 108. There was no discernable difference unfortunately.

## Is this a bug?
Probably not. Chrome performance capture shows that two thirds of the CPU time is spent not in Openlayers code, but in the [canvas drawImage method](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage), and more than half of that time goes into decodeImage. The nonlinear aspect is highly suspect though.

We are somewhat hopeful that there are some ways in which the opaque canvas API may be used in a more efficient way. I am totally not an expert on canvas :]

We would also appreciate any guidance on how to push the performance cliff further out with different Openlayers usage on our end :)

**Comment by ahocevar** [comment]
Without having investigated the issue in-depth, my guess for the non-linear performance drop is some kind of browser, memory  or GPU optimization beyond the control of OpenLayers. However, you can easily boost both performance and user experience of such an application by doing two things:

1. Think about the user experience
    * From a cartographic standpoint: is it worth looking at a map that combines more than 16 topics on a single map?
    * From a bandwidth standopoint: are you aware of the amount of data you're transferring with each pan or zoom interaction?
2. Optimize! In this case it is easy
    * The list of layers contains several WMS layers that com from the same WMS service endpoint. Combine those, using the `LAYERS` param.
    * Use `TileWMS` instead of `ImageWMS` sources, with a tile size of 512 pixels. It will help the browser cache regions that you have already requested, and smaller images are more efficient to handle. If, for some reason, you have to stick with `ImageWMS` sources, configure them with `ratio: 1` to load only the viewport extent.

**Comment by tschaub** [comment]
I notice that changing to tiled layers slows down the loading but improves the panning/zooming performance.  So the size of the image being decoded is clearly important (vs just the number of pixels re-drawn).

It could be that there would be a performance gain if the canvas image layer renderers stored the layer's image as a canvas element instead of an image element.  This would presumably make the `drawImage` calls more efficient (assuming image decoding would not need to happen on each render frame).  But it may also come with a memory penalty (if one canvas per layer consumes more memory than one image per layer).

I imagine the situation would also be improved if there were a webgl image layer renderer (there is a webgl tile layer renderer, but not one for image layers).  In the case of webgl rendering, we don't decode images on every render frame.

@werrolf - Perhaps you have ruled this out already, but if you can rework your application logic so that MapServer renders more of the layers in a single group, I think that would improve things.

**Comment by werrolf** [comment]
Thank you both for taking the time to respond so quickly :)

We do have a lot of distinct data layers in some projects. Ignoring the reproduction case for a moment, some users can go 50~60 distinct object types within a single application.

In these more extreme applications we currently have little room left to rebalance Wms services and layers within individual Wms services. Too many image layers are bad for performance, as we see here, but putting too many Wms layers into one mapfile or mapproxy can also be bad (esp when deactivating one layer).

@ahocevar we will definitely try ratio = 1 and also a 100% tiled version. Tiling may well be the only way in the end. Though I'm a bit concerned about the request volume on zoom operations, with firewalls involved and all that, that part should scale linearly.

@tschaub it makes some intuitive sense to me that scanning through a very large png busts CPU caches, and performance drops off a cliff, while tiles are better for localized access. The weird thing is that all of these images are equally large, 15~16 of them are no problem, and the eighteenth one breaks things completely.

With a tile grid, decode load on pan should drop to almost nothing, while staying the same overall on zoom. So that is definitely the next thing for us to try.

The surprising thing is that these applications have been started on Openlayers 2, and performed fine. It's a bit surprising to me that browsers can stack a bunch of large `<img>` tags on top of each other so much more efficiently than they handle canvas elements. There was no tiling involved then either. Different usage of the same browser toward a very similar end goal, completely different performance profile :\

As for the rework of layers-per-request, I was actually phantasizing about doing the opposite, if it weren't for the surprising client performance implications.

A WebGL renderer for raster layers would be amazing :)

**Comment by fhaefker** [comment]
Hello, everyone,

we can find the same situation in different projects. It would be great to find a central and timely solution. If we can provide this financial support, we will be happy to do so.

What would be necessary to speed up the topic a bit?

Kind regards
Frederik Häfker

**Comment by ahocevar** [comment]
@fhaefker What I can offer is make the changes suggested by @tschaub. i.e. store the image as canvas element instead of an image. This would avoid the time spent decoding the image, which seems to be the primary reason for the performance drop. If you'd be willing to sponsor me on https://github.com/sponsors/ahocevar/, I'd be willing to work on this in the next couple of days.

**Comment by fhaefker** [comment]
Hello @ahocevar

Many thanks. We will sponsor you - you should have received an email message from me.

Best regards
Frederik

**Comment by ahocevar** [comment]
@fhaefker @werrolf Please test if #14444 improves the situation for you.

**Comment by werrolf** [comment]
Yes, this definitely solves our issue. The performance gains are quite incredible. Many thanks!
