### ISSUE TITLE
Add feature existing layer

### ISSUE THREAD

**Issue by aparzi** [openlayers/openlayers#14435]
Hi @ahocevar,
How can I add a figure to an existing layer by geojson-vt integration?

**Comment by ahocevar** [comment]
I guess by recreating the source with a new geojson-vt and an updated GeoJSON.

**Comment by aparzi** [comment]
ok @ahocevar,
isn't there a way to cycle through all the tiles?

**Comment by aparzi** [comment]
@ahocevar I would like to get all the figures of a layer of type VectorTileLayer

**Comment by ahocevar** [comment]
Please remember: vector tiles are a rendering format, not a data format. So you should not be working with geometries of features in vector tiles.

There is a `getFeaturesInExtent()` method on `ol/source/VectorTile`. But it will only give you recently rendered features, and these will be simplified to the rendered resolution, and clipped at or near tile boundaries.

**Comment by aparzi** [comment]
sure clear. Potentially my layer could reach 200k of inserted data, geojson-vt can handle it and I need to allow the insertion too. How could I do?

**Comment by aparzi** [comment]
> ok @ahocevar, isn't there a way to cycle through all the tiles?

@ahocevar is there any way to do this?

**Comment by aparzi** [comment]
@ahocevar All right.  in general, to manage a large amount of work such as 400/500k and possibly insert other figures, would you advise me otherwise, is it also ok to recreate the geojson and use geojson-vt?

**Comment by ahocevar** [comment]
It's perfectly fine to use geojson-vt in this scenario and recreate the source when the GeoJSON changes. It's actually the only way to manage such an amount of features on the client. You don't have to recreate the GeoJSON though, if you have it in memory as JavaScript object literal already.

**Comment by aparzi** [comment]
@ahocevar thanks, so i have to delete the old layer, create a new one with the new geojson right?  If not it would take some time to render with 200k features?

**Comment by ahocevar** [comment]
You can keep the layer. Either recreate the source with a new geojson-vt instance, or just replace the geojson-vt instance and call `refresh()` on the source afterwards.

**Comment by aparzi** [comment]
@ahocevar Thanks

**Comment by aparzi** [comment]
Hi @ahocevar, excuse me. It is possible update layer avoid blink effect? I use refresh() method but cause blink effect.

**Comment by fffahim** [comment]
One work around to ignore the blink can be adding a new layer having the latest data and remove the older one afterward

**Comment by aparzi** [comment]
Thanks @fffahim.

I added a dummy layer which I remove later
