### ISSUE TITLE
MouseEvent.mozPressure is deprecated

### ISSUE THREAD

**Issue by raojala** [openlayers/openlayers#14437]
**Describe the bug**
Warning in browser console: "MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead. [MapBrowserEventHandler.js:265](webpack://treact-template/node_modules/ol/MapBrowserEventHandler.js)"

**Comment by mike-000** [comment]
Similar to #13862 (same line of code but different deprecated property being reported by a different browser)

**Comment by ahocevar** [comment]
Will be fixed with https://github.com/openlayers/openlayers/pull/14438
