### ISSUE TITLE
control.defaults function in UMD builds

### ISSUE THREAD

**Issue by hppltq** [openlayers/openlayers#14431]
**Describe the bug**
We are still using the UMD build rather than ES modules, and it seems that in recent builds, the `ol.control.defaults()` function is wrapped into an additional defaults object - i.e., `ol.control.defaults.defaults()`

**To Reproduce**
1. Build from the source using `npm run build-full`
2. Load the resulting build/full/ol.js file from a script
3. `ol.control.defaults` is an object containing a single `defaults()` function

**Expected behavior**
In previous versions, the `defaults()` function was available from `ol.control`

**Comment by ahocevar** [comment]
See See https://github.com/openlayers/openlayers/issues/14020
