### ISSUE TITLE
No icon display at initial set visible (7.2.2)

### ISSUE THREAD

**Issue by dermoench42** [openlayers/openlayers#14433]
Having a combined style of icon and test used by the gpx wpt features shows some wired behaviour:

- after the layer is set to visible, only the text is displayed.
- after the map is moved both text and icon are display.
- turning the layer on/off afterward the display of the features works as expected.

1. Take a gpx layer
2. center the initial map position/zoom to contain the extent of the gpx
3. Use a combined style
4. reload map

**Expected behavior**
- see both, text and icon on initial set visible

Style:
```js
case 'Point':
                let content = feature.get('name');
                let fontsize = 9;
                let textpos = Math.max(6, 15 - (content.length * fontsize / 3.1));
                let svg = `<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="30px" height="30px" viewBox="0 0 30 30" enable-background="new 0 0 30 30" xml:space="preserve">
                <circle fill="#FFFFFF" stroke="${iconColor}" stroke-width="1.5" cx="15" cy="11" r="10" />
                <path fill="${iconColor}" stroke="none" d="M 12 21 l 3 9 l 3 -9 z" />
                <text x="${textpos}" y="14" style="font-size: ${fontsize}px" fill="#000000">${content}</text>
                </svg>`;
                let img = new Image();
                img.src = 'data:image/svg+xml,' + encodeURIComponent(svg);
                return new Style({
                    image: new Icon({
                        img: img,
                        imgSize: [30, 30],
                        scale: 2,
                        displacement: [0, 30]
                    }),
                    text: new Text({
                        text: content,
                        fontsize: 15,

                    })
                });
```
![no-icon-at-initial-visibility](https://user-images.githubusercontent.com/19437799/211743115-9cf36b35-aba6-42ed-9fd1-bf623ead4430.gif)

**Comment by M393** [comment]
The [`img` option](https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html) states:
>  If the src option is not provided then the provided image must already be loaded.

You can use the `src` option instead with your URL.

**Comment by dermoench42** [comment]
The img src option is used, see the code. An external url is not wanted, because the svg is generated -> the provided img is available instantly.

**Comment by ahocevar** [comment]
@dermoench42 `img` will only be available after its `load` event is fired. @M393's advice is correct.

**Comment by M393** [comment]
Use the `src` option of the Icon, not the Image.
```js
new Style({
    image: new Icon({
        src: 'data:image/svg+xml,' + encodeURIComponent(svg),
```

**Comment by dermoench42** [comment]
Aaah, communication is sometimes difficult. That works.
