### ISSUE TITLE
NgRx / readonly store issues with OpenLayers

### ISSUE THREAD

**Issue by A5H73Y** [openlayers/openlayers#14434]
**Describe the bug**
When creating a Feature from a Geometry from a readonly store, there are errors relating to the readonly properties of the Geometry.

**To Reproduce**
1. Add an object with a Geometry to an NgRx store.
2. Create a Feature using that Geometry.
3. See error and a black map.

**Expected behavior**
The feature to be created and added to the layer as would normally happen when not using a store.

**Error Stacktrace**
```
TypeError: Cannot assign to read only property 'listeners_' of object '[object Object]'
    at Polygon.addEventListener (Target.js:68:58)
    at listen (events.js:63:10)
    at Feature.handleGeometryChanged_ (Feature.js:242:39)
    at Feature.dispatchEvent (Target.js:114:11)
    at Feature.notify (Object.js:176:12)
    at Feature.set (Object.js:215:14)
    at Feature.setGeometry (Feature.js:260:10)
    at new Feature (Feature.js:140:14)
```

**Comment by ahocevar** [comment]
Reproduction case please?

**Comment by mike-000** [comment]
The same would happen if you simply froze a geometry (or any other observable object).  You would need to clone it before using in a feature which needs to listen for changes https://codesandbox.io/s/modify-icon-forked-3f6nzn?file=/main.js

**Comment by A5H73Y** [comment]
@mike-000 Thanks for that, that solved my issue in this case.
Is the original issue an actual bug, or is that just the nature of readonly objects / geometries?

**Comment by mike-000** [comment]
I don't think it is a bug   `ol​/Observable` and its subclasses are intended to updateable.
