### ISSUE TITLE
Issue with ESRI Vector Tiles

### ISSUE THREAD

**Issue by vuratek** [openlayers/openlayers#14449]
Hi,

Not sure if this is OL issue or OLMS, but here is what I noticed:
ESRI vector tiles basemaps worked fine in OL 6.x and its corresponding OLMS. The newer version sort of works, but throws an error (the map can still function).

I am using EPSG:4326

1) issue one: probably ESRI error as their TileServer incorrectly (??) describes its tiles. It uses EPSG:3857 structure for rows/columns (1x1, 4x4, 16x16, ...) vs (1x2, 2x4, 4x8, ...). So in order to prevent OL using their definition, I replaced the TileServer reference to nothing, otherwise OL fails to work; unless I am missing a step: 
```
fetch('https://www.arcgis.com/sharing/rest/content/items/cc8072363d614d96b08b2361a09979a5/resources/styles/root.json?f=pjson')
    .then(response => {
        return response.json();
    })
    .then (data => {
        data.sources.esri.url = '';
        applyStyle(layer, data, "", undefined, tileGrid.getResolutions());
        
    })
```
2) The map loads but keeps throwing following error:
`
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
    at getTileJson (util.js:163:31)
    at apply.js:525:5
    at new Promise (<anonymous>)
    at setupVectorSource (apply.js:524:10)
    at assignSource (apply.js:226:20)
    at onChange (apply.js:310:15)
    at apply.js:368:15
`

**To Reproduce**
Here is my code:
```
import MVT from 'ol/format/MVT.js';
import Map from 'ol/Map.js';
import VectorTileLayer from 'ol/layer/VectorTile';
import VectorTileSource from 'ol/source/VectorTile';
import View from 'ol/View.js';
import { applyStyle } from 'ol-mapbox-style';
import { get as projGet } from "ol/proj";
import {createXYZ} from 'ol/tilegrid';

function tileUrlFunction(tileCoord) {
  return (
    'https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_GCS_v2/VectorTileServer/tile/{z}/{y}/{x}.pbf'
  )
    .replace('{z}', String(tileCoord[0] + 1))
    .replace('{x}', String(tileCoord[1]))
    .replace('{y}', String(tileCoord[2]));
}

    const tileGrid = createXYZ({
        extent: [-180, -90, 180, 90],
        tileSize: 512,
        maxResolution: 180 / 512,
        maxZoom: 15,
    });
  
  const layer = new VectorTileLayer({
    declutter: true,
    source: new VectorTileSource({
        format: new MVT(),
        projection: 'EPSG:4326',
        tileGrid: tileGrid,
        tileUrlFunction: tileUrlFunction,
    }),
  });

    const map = new Map({
    layers: [
        layer
    ],
    target: 'map',
    view: new View({
        center: [0, 0],
        minZoom: 0,
        zoom: 0,
        projection: projGet("EPSG:4326"),
    }),
    });

    fetch('https://www.arcgis.com/sharing/rest/content/items/cc8072363d614d96b08b2361a09979a5/resources/styles/root.json?f=pjson')
    .then(response => {
        return response.json();
    })
    .then (data => {
        data.sources.esri.url = '';
        applyStyle(layer, data, "", undefined, tileGrid.getResolutions());
        
    })
    .catch(error => {
        console.error("Error processing.");
    });

```

**Expected behavior**
- either have the ability to ignore the default ESRI settings
- or not throw Error

Perhaps there is another way of loading ESRI vector tile layers?

Anyway, thanks in advance and great job on maintaining this awesome library!
Otmar

**Comment by mike-000** [comment]
OpenLayers only supports the standard EPSG:3857 Mapbox tilejson specification https://github.com/mapbox/tilejson-spec
For vector tiles in other projections see https://openlayers.org/en/latest/examples/vector-tiles-4326.html for a hardcoded tile grid solution.

ESRI uses a service json for custom tile grids and projections.  Another option is to fetch and parse that to create a tile grid in a custom projection as in https://github.com/OrdnanceSurvey/OS-Data-Hub-API-Demos/blob/master/OSVectorTileAPI/OpenLayers/map.js

**Comment by ahocevar** [comment]
Regarding issue 1, that's indeed a problem with the way Esri references the tiles in the TileJSON. They are aware of the problem, but haven't fixed it yet. However, you can work around it using the `transformRequest` option, as shown in the [esri-transformrequest](https://unpkg.com/ol-mapbox-style@9.4.0/dist/examples/esri-transformrequest.html) example:

https://github.com/openlayers/ol-mapbox-style/blob/336c77b6a83f97423affa17e250ce8640f99bdc1/examples/esri-transformrequest.js#L8-L14

And issue 2 probably comes from the way you're removing the tilejson from the source, so it will solve itself when you apply the solution for issue 1 correctly. Your modified code could look like this:
```js
import 'ol/ol.css';
import VectorTileLayer from 'ol/layer/VectorTile.js';
import VectorTileSource from 'ol/source/VectorTile.js';
import {Map, View} from 'ol/index.js';
import {applyBackground, applyStyle} from 'ol-mapbox-style';
import {createXYZ} from 'ol/tilegrid.js';

const url =
  'https://www.arcgis.com/sharing/rest/content/items/cc8072363d614d96b08b2361a09979a5/resources/styles/root.json?f=pjson';

// Match the server resolutions
const tileGrid = createXYZ({
  extent: [-180, -90, 180, 90],
  tileSize: 512,
});

const layer = new VectorTileLayer({
  declutter: true,
  source: new VectorTileSource({
    projection: 'EPSG:4326',
    tileGrid: tileGrid,
  }),
});
applyStyle(layer, url, {
  resolutions: tileGrid.getResolutions(),
  transformRequest(url, type) {
    if (type === 'Source') {
      return new Request(
        url.replace('/VectorTileServer', '/VectorTileServer/')
      );
    }
  },
});
applyBackground(layer, url);

new Map({
  target: 'map',
  layers: [layer],
  view: new View({
    projection: 'EPSG:4326',
    zoom: 0,
    center: [0, 30],
  }),
});
```
The above is basically the https://openlayers.org/en/latest/examples/vector-tiles-4326.html example with your style json and the `transformRequest` option.

**Comment by mike-000** [comment]
As in https://github.com/openlayers/ol-mapbox-style/issues/603 it will also work without a `transformRequest` by using `https://basemaps.arcgis.com/arcgis/rest/services/World_Basemap_GCS_v2/VectorTileServer/resources/styles/` as the style url
https://codesandbox.io/s/vector-tiles-4326-forked-dfbxpw?file=/main.js

**Comment by vuratek** [comment]
Thanks a lot, that did the trick!

**Comment by ahocevar** [comment]
I just published v9.5.0, which adds a new `projection` option. With that option, your above example can be simplified to https://github.com/openlayers/ol-mapbox-style/blob/v9.5.0/examples/esri-4326.js (see it live on https://unpkg.com/ol-mapbox-style@9.5.0/dist/examples/esri-4326.html)

**Comment by mike-000** [comment]
Does it also need a `maxResolution` option to determine the tile grid?  ESRI uses a single tile at level 0 while in https://openlayers.org/en/latest/examples/vector-tiles-4326.html MapTiler uses 2 tiles.

**Comment by ahocevar** [comment]
For Esri, the above setup works. For MapTiler it does not. The rationale behind the addition of the `projection` option to ol-mapbox-style was the assumption of a standard tile grid for each projection, which is defined by zoom level 0 filling a single tile at the projection's validity extent as obtained from the EPSG database. For other setups, more manual work is necessary.

**Comment by vuratek** [comment]
I would like to add, that while the simplification works, it only loads the default ESRI country styling. I had to combine both of your original answers to get it working. Try different urls to see the difference. 

```
//        let url = 'https://www.arcgis.com/sharing/rest/content/items/cc8072363d614d96b08b2361a09979a5/resources/styles/root.json?f=pjson';
//        let url = 'https://www.arcgis.com/sharing/rest/content/items/55253142ea534123882314f0d880ddab/resources/styles/root.json?f=pjson';
        let url = 'https://www.arcgis.com/sharing/rest/content/items/670c2a9ee3b949a8991b99df425abd0d/resources/styles/root.json?f=pjson';
        const tileGrid = createXYZ({
            extent: [-180, -90, 180, 90],
            tileSize: 512,
            maxResolution: 180 / 256,
            maxZoom: 22,
        });

        let layer = new VectorTileLayer({
            declutter: true,
            source: new VectorTileSource({
                projection: 'EPSG:4326',
                tileGrid: tileGrid,
            }),
        });

        applyStyle(layer, url, {
            resolutions: tileGrid.getResolutions(),
            transformRequest(url, type) {
            if (type === 'Source') {
                return new Request(
                url.replace('/VectorTileServer', '/VectorTileServer/')
                );
            }
            },
        });
        applyBackground(layer, url);
```

**Comment by vuratek** [comment]
Also, if anyone else is interested in finding additional ESRI 4326 basemaps:

https://www.arcgis.com/home/group.html?id=702026e41f6641fb85da88efe79dc166&view=list&categories=%5B%22%2FCategories%2FGCS+WGS84%22%5D#content

**Comment by ahocevar** [comment]
@vuratek Your code can be simplified to
```js
import 'ol/ol.css';
import {apply} from 'ol-mapbox-style';

apply(
  'map',
  'https://www.arcgis.com/sharing/rest/content/items/670c2a9ee3b949a8991b99df425abd0d/resources/styles/root.json?f=pjson',
  {
    projection: 'EPSG:4326',
    transformRequest(url, type) {
      if (type === 'Source') {
        return new Request(
          url.replace('/VectorTileServer', '/VectorTileServer/')
        );
      }
    }
  }
);
