### ISSUE TITLE
Failed to resolve module

### ISSUE THREAD

**Issue by antongithubuser** [openlayers/openlayers#14456]
**Describe the bug**
When I import from ol@v7.2.2/layer/Vector.js browser trows an error:
TypeError: Failed to resolve module specifier "rbush". Relative references must start with either "/", "./", or "../".

I think, than an error near Vetor.js, BasicVector.js. 

**Expected behavior**
Import from ol@v7.2.2/layer/Vector.js whithout errors.

[BaseVector.txt](https://github.com/openlayers/openlayers/files/10496472/BaseVector.txt)
[Vector.txt](https://github.com/openlayers/openlayers/files/10496473/Vector.txt)

**Comment by ahocevar** [comment]
rbush is not available as ES module, this is why you're getting the error. Please use a bundler to build your application, or [Skypack](https://github.com/openlayers/ol-skypack) if it's just for quick prototyping.

**Comment by antongithubuser** [comment]
Ok, will use bundler

**Comment by raiden909** [comment]
how can i apply it in laravel frameworks?

**Comment by ahocevar** [comment]
Not specific to Laravel, but you can always create a bundle with only what you need. This is what was done in phpMyAdmin: https://github.com/phpmyadmin/phpmyadmin/pull/16959

**Comment by raiden909** [comment]
i just really hate when i follow the quick start in openlayers and try to apply it on the laravel the map did not show up and also the issue's like rbush, and some of import the module is always error please guide me sir

your help means a lot 
<img width="931" alt="Screenshot_1" src="https://github.com/openlayers/openlayers/assets/78341865/8ab73b11-6876-4d58-95e3-20f39f595b75">

**Comment by ahocevar** [comment]
Ok, looks like you're not using a bundler (like I suggested above when I linked to phpMyAdmin), but script elements with `type="module"`. For that to work, you'll need to specify an [import map](https://github.com/openlayers/openlayers/issues/8552#issuecomment-1987290100).

**Comment by raiden909** [comment]
i still try i gonna come back again thank you for your time
