### ISSUE TITLE
Make `collectSourceAttributions_` of `ol/control/Attribution` accessible for custom attribution controls

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#14453]
**Is your feature request related to a problem? Please describe.**
To write own attribution controls it would be nice if the `collectSourceAttributions_` method would be accessible so the code does not need to get duplicated.

**Describe the solution you'd like**
For me the nicest solution would be if the method would be exported as a function that accepts a `FrameState` and returns an object containing the attributions and a collapsible property.

i.e.:
```
/**
 * Collect a list of visible attributions and determines the collapsible state.
 * @param {import("../Map.js").FrameState} frameState Frame state.
 * @return {{
 *   attributions: Array<string>,
 *   collapsible: boolean
 * }} Attribution texts and collapsible state.
 */
export function collectSourceAttributions(frameState) {
// ...
```

The only 'major' code change in the control would then be to check `this.overrideCollapsible_` outside of this function call.

**Comment by simonseyock** [comment]
I can provide a PR if wanted.

**Comment by simonseyock** [comment]
As I wrote the code anyways, I just pushed it to PR: https://github.com/openlayers/openlayers/pull/14454

**Comment by ahocevar** [comment]
I'd be interested to learn more about a use case for a custom Attributions control, and how making the `collectSourceAttributions` method `@protected` or `@public` helps with that use case. Can you share code for such a custom control, along with an explanation what you're trying to achieve?

The reason why I'm asking is because I'd like to think about alternatives that might be more obvious to the application developer than a poorly named `collectSourceAttributions()` method which a custom control would have to call.

**Comment by simonseyock** [comment]
I would like to have full control over how the actual html is generated and the easiest way I see to do this is something like this:

```
  map.on('postrender', (e) => {
    if (!e.frameState) {
      return;
    }
    attributions = collectSourceAttributions(e.frameState).attributions;
    // call custom render function that processes attributions (if changed)
  });
```

One reason to do this is to use a framework for styling the controls in a similar way the rest of the app is styled. Sometimes it is necessary to change the structure and markup and it is hard to change that otherwise.

I don't think the name is very far fetched and this is something I am missing in openlayers for a longer time now. The existing controls in openlayers are not customizable much. For most controls that is not much of a hazzle because it easy to rewrite them. But for attributions it is kind if annoying.

**Comment by simonseyock** [comment]
The `collectSourceAttributions` won't solve all problems I had in the past. I once had the requirement to print the actual layer names before the matching attribution. This would still not be possible and requires different code, but that is ok, it does something fundamentally different form the normal openlayers control.

But for now I just want use react components from a frontend library. I don't have a big problem with duplicating the code in the other codebase, but I thought it might be nice for other users of openlayers as well.

**Comment by ahocevar** [comment]
Thanks @simonseyock for taking the time to describe your requirement.

For the use cases you describe, I think we are close to a usable API already, thanks to the relatively new `map.getAllLayers()` method and modern JavaScript.

```js
const attributions = map.getAllLayers()
  .map(l => inView(l.getLayerState(), frameState.viewState) && l.getSource().getAttributions()?.(frameState))
  .filter(a => a);
const uniqueAttributions = Array.from(new Set(attributions.flat()));
```
It does the same as the outdated `collectSourceAttributions()` method. This approach allows you to easily create a mapping between layer and attribution as well.

Obviously, a nicer API would look something like this:

```js
const attributions = map.getAllLayers()
  .map(l => l.getAttributions(map.getView()))
  .filter(a => a);
const uniqueAttributions = Array.from(new Set(attributions.flat()));
```
If you agree, I think adding a `getAttributions(view)` method to the `Layer` API would make sense.

**Comment by simonseyock** [comment]
Yes, that looks like a nice and flexible API.

**Comment by simonseyock** [comment]
The only problem with implementing this is that the attribution getter method of the source will need a frame state. I think these only exist in render cycles, is that correct? So it would either be possible to change the signature of the attribution getter to accept only a view state as this might be all you need inside the attribution getter, but I don't know the exact reasons why the frame state is an argument to the attributions getter.

Another possibility would be to pass the frame state into the `getAttributions` method. This ties the call to be made inside a `postrender` callback. But I don't think this is that bad because you need to recalculate the attributions at some point anyways.

**Comment by simonseyock** [comment]
Of course the second possibility is a not breaking change, which probably makes it more favorable.

**Comment by simonseyock** [comment]
Code could look like this: https://github.com/openlayers/openlayers/pull/14454/files

**Comment by ahocevar** [comment]
@simonseyock You don't need much of the frame state. Only the resolution, which you can get from the view, and the extent, which you can also get from the view (`calculateExtent()`). This is why I suggested to pass the view instead of the frame state.

**Comment by ahocevar** [comment]
Or were you only talking about the `inView()` helper function?

**Comment by ahocevar** [comment]
Ah, I see now. Well, the `getAttributions()` getter on the source just returns the attribution function, which has to be called with a frame state when the user calls it. But internally, you can call it with an object that just contains the needed properties.

**Comment by ahocevar** [comment]
Ideally we'd call the attribution function with `extent` and `resolution`. Not with a `View`, and not with a`FrameState`. This is probably worth a breaking change, but not within the scope of this issue or #14454.

**Comment by ahocevar** [comment]
@simonseyock I took the liberty to create #14476 with my suggested approach. Would that pull request help with your use case? If you agree, it could replace #14454.

**Comment by simonseyock** [comment]
Yes, these functions look very handy for creating custom map controls. Not only for attributions but also for layer tree components.
