### ISSUE TITLE
Bing map layer not displayed when using COOP and COEP headers

### ISSUE THREAD

**Issue by Akbalder** [openlayers/openlayers#14463]
**Describe the bug**
When OpenLayers is on a html page served with the following headers
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```
Bing map layer isn't displayed.

**To Reproduce**
1. Host an OpenLayers map having a BingMap layer on a server having the headers
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```
2. The following url fails to load
```
GET https://dev.virtualearth.net/REST/v1/Imagery/Metadata/RoadOnDemand?uriScheme=https&include=ImageryProviders&key=xxxxxxxxxxxxxx&c=en-us&jsonp=olc_42
```
with the error
```
net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200
```
3. Bing map layer isn't displayed

**Expected behavior**
The virtualearth url should loads correctly to display the Bing map layer.

I guess that it is because the jsonp function in OpenLayers doesn't specify a crossorigin.

**Comment by ahocevar** [comment]
@Akbalder Can you please test if #14464 fixes the issue?

**Comment by Akbalder** [comment]
It works with this modification.

**Comment by Akbalder** [comment]
Thank you :)
