### ISSUE TITLE
OGC { Maps, Features, Coverage, Records } Support

### ISSUE THREAD

**Issue by itsgifnotjiff** [openlayers/openlayers#14460]
**Is your feature request related to a problem? Please describe.**
The OGC has moved on from WMS, WFS, WCS and Catalogues and as the default Javascript library I would love to be able to use the new standards with my favorite tool.
**Describe the solution you'd like**
Given the OGC APIs standards are web friendly (json/geojson responses over XML and many others) I would love to see basic support for the four major APIs, being Maps, Features, Coverages and Records mirroring the WMS WFS WCS and GetCapabilities parser (which now would be much easier to implement) so I can start building demos for the ECMWF, OGC, WMO and ECCC.

**Comment by ahocevar** [comment]
@itsgifnotjiff Contributions to add support for more of the new OGC standards are always welcome. And since the basic concepts are already available in OpenLayers, you can build applications on top of these new standards now already, because in the end it's just http, urls, images and geojson.

**Comment by itsgifnotjiff** [comment]
Yes sir, I am just not sure if I can simply use a WMS layer in OpenLayers to call and interact with an OGC Maps service. I've noticed the new [OGCMapTiles](https://openlayers.org/en/latest/examples/ogc-map-tiles.html) example and wanted to know if the rest of the APIs are in the roadmap to 8.x. Thank you again MR. @ahocevar for your wonderful work.

**Comment by ahocevar** [comment]
@itsgifnotjiff For the Maps API, you'd have to use an Image layer and a custom ImageUrlFunction. The roadmap is determined by what gets contributed, so if you or someone else adds an OGCMap layer by means of a pull request, it will get added.

**Comment by walkermatt** [comment]
I'm working on an OGC Features API example which uses the bbox loading strategy. I'll hopefully submit a PR shortly.

**Comment by boeckMt** [comment]
I have a basic implementation of OGC API Maps with `ol/source/ImageTile`, so could be similar to `ol/source/TileWMS.js`

https://codesandbox.io/p/devbox/ogc-map-tiles-forked-wf33gc?workspaceId=ws_7J5TaAfLHmz19UqdzL6mEK

It is not fully implemented (all [parameters](https://github.com/opengeospatial/ogcapi-maps/tree/master/openapi/parameters)) and there are some artifacts at the tile edges, but maybe someone can help me to make it better :)
