### ISSUE TITLE
```VectorSource``` initialized with an existing ```Collection``` should be properly disposed

### ISSUE THREAD

**Issue by KotoriK** [openlayers/openlayers#14466]
**Is your feature request related to a problem? Please describe.**
For now, ```VectorSource``` can be initialized with a ```Collection```, and changes will be sync by adding listeners on this ```Collection```. However, those listeners can not be removed and might cause memory leaking.
**Describe the solution you'd like**
Remove those listeners mentioned above in ```dispose()```, which can be called by developers manually.

**Comment by ahocevar** [comment]
Before finishing my review of #14467, may I ask what exactly your use case is? I'm trying to figure out if exposing `dispose()` (which we usually try to avoid) is the appropriate fix, or if it would be better to expose a new `setFeaturesCollection()` method.

**Comment by KotoriK** [comment]
> Before finishing my review of #14467, may I ask what exactly your use case is? I'm trying to figure out if exposing `dispose()` (which we usually try to avoid) is the appropriate fix, or if it would be better to expose a new `setFeaturesCollection()` method.

I'm creating an editor based on OpenLayer. In my case, I need a temp layer to render a FeatureCollection, the layer and the VectorSource will be disposed later. 

IMO ```dispose()``` is more appropriate as it provide a more accurate semantics. It indicates the object can be marked as 'Garbage Collect Safe' after calling this method, and that is what current implementation of ```dispose()``` is actually doing.

**Comment by ahocevar** [comment]
JavaScript garbage collects anything that is not referenced anywhere any more. So as soon as you remove any reference to your feature collection, it will be garbage collected if the source is also not referenced anywhere any more.

The reason why I'm hesitant to add `dispose()` for `ol/source/Vector` to the API is that we're planning to get rid of `Collection` anyway at some point, and `ol/source/Vector` does not need `dispose()` for any other use case than the one you mentioned. So if you want to continue with that approach, please add a more verbose prose description to `dispose()` that explains this only use case where it is needed. Also, please look at `ol/source/Raster` for the correct way to override `dispose()` - you'll be overriding `disposeInternal()`, and only add an API marker for `dispose`.

**Comment by KotoriK** [comment]
Thanks for your detailed explanation. 

I rethink about the problem I met, it is caused by applying the same FeatureCollection to multiple temporary VectorSource. 
That's because I treated VectorSource as a 'heavier' object. After reading your explanation. I realize using VectorSource directly will better meet my use case.

I agree with your concerns, and I understand for now it's not necessary to apply this patch.
