### ISSUE TITLE
Rotated vector layer text styles not displaying at correct location when context is clipped and translated

### ISSUE THREAD

**Issue by kevmcgrath** [openlayers/openlayers#14478]
**Describe the bug**
We're working on a modified spyglass using the latest version of OL, but instead of showing hidden layers centered around the cursor, we display them in a translated area above and to the right of the cursor. 

The issue is that when the context for vector layers containing _rotated_ text styles are clipped and translated, the location of these styles appear at the _original_ location on the map, not the _translated_ location. This does not occur for non-rotated text styles.

**To Reproduce**
1. Go to https://codesandbox.io/s/ol7-rotate-translate-issue-qzext2?file=/src/index.js
2. Hover the mouse over Miami. The blue box shows the spyglass area. The red box shows the hidden layers revealed by the spyglass, which are clipped and translated via prerenders and postrenders. Note that both the blue "1" and _non-rotated_ red "2" vector layer text styles are properly displayed over Miami, Florida.

![image](https://user-images.githubusercontent.com/42700439/216621447-8f905a89-4cb3-4970-88d8-8d1d516e8153.png)

3. A third vector layer text style - a green "3" - has a non-zero rotation value. It's also being clipped and translated should display on top of the red "2". However, it incorrectly displays in the original non-translated location of Miami from the main map. Any rotation value != 0 causes the translation to fail. 

![image](https://user-images.githubusercontent.com/42700439/216622459-c59a58e7-f3f2-418c-97e8-c81b690aa26f.png)

**Expected behavior**
The green "3" should be translated and superimposed on top of the red "2". I've only been able to accomplish this by removing the rotation option (~Line 106 of index.js) and/or setting the value to 0.

![image](https://user-images.githubusercontent.com/42700439/216623973-d556937d-aec9-41e2-b1c8-bc57932f85b6.png)

**Comment by mike-000** [comment]
The `translate` will result in any context `rotate` needed to perform the rendering being incorrectly anchored.  It also renders incorrectly when the view is rotated.

**Comment by ahocevar** [comment]
@mike-000 Thanks for your assessment. Do you think you'd be able to provide a fix?

**Comment by mike-000** [comment]
I don't think a prerender translate is compatible with the renderer's requirement to draw rotated text or images.  A better option might be to use superimposed maps sharing a view as in https://codesandbox.io/s/layer-spy-forked-i4rwq0?file=/main.js  As in other examples `getRenderPixel` must be used to correctly handle view rotation.

**Comment by mike-000** [comment]
This particular problem a prerender translate on a vector layer can be fixed by #14483  But it does not mean translate is always safe to use, there may be other as yet undiscovered side effects on vector layers, and on other layer types.

**Comment by mike-000** [comment]
There is a related issue with prerender context scale.  e.g. if the Magnify example is implemented with duplicate layers and a spy to layers with prerender scale https://codesandbox.io/s/magnify-forked-3jb2yg?file=/main.js  Non-rotated text is magnified as expected, but #14483 is needed to magnify rotated text.
