### ISSUE TITLE
ReferenceError: ResizeObserver is not defined

### ISSUE THREAD

**Issue by motto76** [openlayers/openlayers#14474]
We have raised the OL version in our project from 6.14.1 to 7.2.2 and changed the imports from "ol/PluggableMap" to "ol/Map".

When we start our project in the browser everything runs as it should, but in our tests we get the following error in various places:

  ```
ReferenceError: ResizeObserver is not defined

       97 | }
       98 |
     > 99 | const map = new Map({})
          | ^
```

Does anyone have an idea what is missing here?

**Comment by ahocevar** [comment]
Your tests are probably running on JSDom, where `ResizeObserver`, which we use now to be able to resize the map in all possible scenarios, is not supported. You'll need to use a polyfill for that. See e.g. https://stackoverflow.com/questions/64558062/how-to-mock-resizeobserver-to-work-in-unit-tests-using-react-testing-library.

**Comment by motto76** [comment]
Thanks for the tip. Following code before creating the map has solved our problem.

```
window.ResizeObserver =
  window.ResizeObserver ||
  jest.fn().mockImplementation(() => ({
    disconnect: jest.fn(),
    observe: jest.fn(),
    unobserve: jest.fn()
  }))

const map = new Map({})
```
