### ISSUE TITLE
Text label `offsetX` behavior with `placement: line`

### ISSUE THREAD

**Issue by pt3326** [openlayers/openlayers#14475]
I've recently noticed that `offsetX` attribute doesn't work on text labels for lines with `placement: line`. In fact, `offsetY` seems to be working correctly. Is it a proper behavior or a bug? Is there any other way to control x-axis offset in the similar way as y offset when `placement` attribute is set to `line`?

**Comment by ahocevar** [comment]
What would you expect `offsetX` to do? To be consistent with `offsetY`, it would mean an offset along the line, measured from - where? That would probably heavily depend on `textAlign`, but in which way?

**Comment by pt3326** [comment]
Well, that's a good point. I wasn't aware of how it works underneath and couldn't find a proper explanation in docs (or even a note) so it wasn't so obvious for me at first glance.
