### ISSUE TITLE
Can't find OpenLayers in the old Javascript fashion

### ISSUE THREAD

**Issue by icemagno** [openlayers/openlayers#14473]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when some guys starts to develop things thinking everyone are using Node. Some people do not like this and still developing ( or maintaining ) old vanilla Javascript.

**Describe the solution you'd like**
Please where the heck I can find OpenLayers to use in my pure vanilla Javascript application?

I am not obliged to use Node

**Comment by mike-000** [comment]
Links and download are on https://openlayers.org/download/

**Comment by tschaub** [comment]
@icemagno - feel free to reopen with more detail if you can’t find what you need on page that @mike-000 linked.

**Comment by icemagno** [comment]
Thanks. Where can the people find this information without asking here?

**Comment by ahocevar** [comment]
@icemagno When you go to https://openlayers.org/, and click 'latest release', you're taken directly to the page that @mike-000 mentioned. Like @tschaub said, if you're missing something on that page, let us know how we can improve it.

**Comment by icemagno** [comment]
Yea but there is not clear the package have any "no-Node" version of OpenLayers. I was there before and ended thinking the package is only a Node version. You could put something like "Find vanilla JS version here". Another thing is the CSS was not in the ```dist``` folder (together with ol.js) and I need to search it by myself inside the root. I wasn't able to use modern code anyway. Things like ```new Map``` didn't work and even with the package you pointed I still need to use it like ```new ol.Map```. Don't know if I miss something.
