### ISSUE TITLE
let `box_: RenderBox` be accessible on `DragBox`

### ISSUE THREAD

**Issue by behoney** [openlayers/openlayers#14479]
I'm always frustrated when I'm using `DragBox`.
`DragBox` is one of the interactive features of Openlayers and an user interaction results in  `renderBox` to show where the user select.
Currently, providing a classname(;default is `ol-dragbox`) is the only way to style, because `renderBox` is set as private field of `DragBox`.

There's no way to control `renderBox` even if a developer creates an extended class of `DragBox`.
For example, I'm trying to implement buttons which set certain width-height ratio of `DragBox`. So `setPixels` function of `RenderBox`(; which is `box_` of `DragBox`) seems a proper function to call for my case.

With this context, I'd like to suggest Openlayers provides getter function for `box_` field on `src/ol/interaction/DragBox.js`.

**Comment by behoney** [comment]
If this feature request is acceptable, I'd like to make PR with [this](https://github.com/behoney/openlayers/commit/6d20f5d26f4eb926f535acfc99321e9e7207ab12).

**Comment by ahocevar** [comment]
For your use case, I think `ol/interaction/Extent` is a better fit than `ol/interaction/DragBox`. It provides `getExtent()` and `setExtent()` methods. Let us know if that works for you.

**Comment by behoney** [comment]
> For your use case, I think `ol/interaction/Extent` is a better fit than `ol/interaction/DragBox`. It provides `getExtent()` and `setExtent()` methods. Let us know if that works for you.

@ahocevar Of course, actually, that’s the way i tried on my previous work. At that time, What i did is like mocking ‘Dragbox’ by handling drag-related events manually. And then I got to know that I could’ve saved my time when if Openlayers provided a method to access ‘box_’(‘RenderBox’) of ‘DragBox’.

Is there strong reason for ‘RenderBox’ staying in private?

**Comment by behoney** [comment]
If so, it's better to keep it private.
What i wanted is both styling `box` with css and controlling it with its API.
Thanks anyway 😄
