### ISSUE TITLE
Map is not rendering

### ISSUE THREAD

**Issue by elamandeep** [openlayers/openlayers#14482]
Hi there! I need help. My map is not rendering. Even I passed the array inside `useEffect`  in the layer but still, it's not rendering. Also, It's built-in function is not working. Such as `map.addLayer()`

```jsx
 const layerArr = useMemo(
    () => [
      new TileLayer({
        source: new OSM(),
      }),
      vector,
    ],
    [vector]
  );

  useEffect(() => {
    const mapObj = new ol.Map({
      target: mapRef.current,
      layers: layerArr,
      controls: [],
      view: new View({
        center: transform(
          [77.6953125, 24.206889622398023],
          "EPSG:4326",
          "EPSG:3857"
        ),
        zoom: 5,
      }),
    });

    setMap(mapObj);
  }, [layerArr]);

```
Here's my codesandbox
 https://codesandbox.io/s/clever-antonelli-cj6mmr?file=/src/App.js

**Comment by elamandeep** [comment]
also please look at this discussion https://github.com/openlayers/openlayers/discussions/14481#discussion-4822427

**Comment by ahocevar** [comment]
The reason why the map does not render is because the `target` container does not have any dimension. Make sure to use css to give the `#map`  a `height` in `styles.css`, e.g.
```js
#map {
  position: absolute;
  top: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  overflow: hidden;
}
```

**Comment by elamandeep** [comment]
> The reason why the map does not render is because the `target` container does not have any dimension. You can give the `#map` a `height` in `styles.css`, e.g.
> 
> ```js
> #map {
>   position: absolute;
>   top: 0;
>   bottom: 0;
>   width: 100%;
>   height: 100%;
>   overflow: hidden;
> }
> ```

i did that it still not working

**Comment by behoney** [comment]
> > The reason why the map does not render is because the `target` container does not have any dimension. You can give the `#map` a `height` in `styles.css`, e.g.
> > ```js
> > #map {
> >   position: absolute;
> >   top: 0;
> >   bottom: 0;
> >   width: 100%;
> >   height: 100%;
> >   overflow: hidden;
> > }
> > ```
> 
> i did that still it is not working

@elamandeep Your app has 2 of `ol-viewport` and what you see is perhaps the first one. so you cannot check the rendered result.

<img width="516" alt="image" src="https://user-images.githubusercontent.com/9066602/216833778-6f6b3e7c-9ec8-4c80-910c-b749f100dcde.png">

first, remove `StrictMode` in `/sandbox/src/index.js` which causes your component render twice.
And then, if the result is what you wanted, you have to prevent creating `ol.Map` instance twice in your `Map.jsx` somehow.

**Comment by elamandeep** [comment]
> > > The reason why the map does not render is because the `target` container does not have any dimension. You can give the `#map` a `height` in `styles.css`, e.g.
> > > ```js
> > > #map {
> > >   position: absolute;
> > >   top: 0;
> > >   bottom: 0;
> > >   width: 100%;
> > >   height: 100%;
> > >   overflow: hidden;
> > > }
> > > ```
> > 
> > 
> > i did that still it is not working
> 
> @elamandeep Your app has 2 of `ol-viewport` and what you see is perhaps the first one. so you cannot check the rendered result.
> 
> <img alt="image" width="516" src="https://user-images.githubusercontent.com/9066602/216833778-6f6b3e7c-9ec8-4c80-910c-b749f100dcde.png">
> 
> first, remove `StrictMode` in `/sandbox/src/index.js` which causes your component render twice. And then, if the result is what you wanted, you have to prevent creating `ol.Map` instance twice in your `Map.jsx` somehow.

it's working but it's not plotting my points. What is the reason?

**Comment by elamandeep** [comment]
@behoney and @ahocevar  please help me in sorting out my problem. I'm unable to plot my points on the map.

**Comment by ahocevar** [comment]
You should make sure that you create the OpenLayers map only once, and not every time the respective `useEffect()` function is called. I usually create the map outside of React, and only call `map.setTarget()` in the `useEffect()` function.

See https://codesandbox.io/s/fancy-dew-gq09c9?file=/src/components/map/Map.jsx for an updated codesandbox.

**Comment by elamandeep** [comment]
Thanks for giving ur precious time to my problem.
