### ISSUE TITLE
Use KeboardEvent#key instead of KeyboardEvent#charCode

### ISSUE THREAD

**Issue by WebKieth** [openlayers/openlayers#14490]
https://github.com/openlayers/openlayers/blob/main/src/ol/interaction/KeyboardZoom.js#L78
I just want to know why...
Why '==' instead of '==='
Why `'+'.charCodeAt(0)` - it have no sense

**Comment by jahow** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode

> A number that represents the Unicode value of the character key that was pressed.

**Comment by WebKieth** [comment]
Its deprecated
![Снимок экрана от 2023-02-06 22-29-18](https://user-images.githubusercontent.com/12966747/217066738-803c61e0-805e-43ae-a55a-400b8d2702bb.png)
`
(keyEvent.key === '+' || keyEvent.key == '-')
`
Simpler and also works

**Comment by ahocevar** [comment]
You are absolutely right, @WebKieth. Thanks for spotting this. Would you be able to provide a pull request with your suggested improvement?

**Comment by ahocevar** [comment]
Fixed with #14492. Thanks, @WebKieth.
