### ISSUE TITLE
Access `Map` object from within custom `renderer:...` function (Or option to prevent culling)

### ISSUE THREAD

**Issue by thehappycheese** [openlayers/openlayers#14498]
### Problem Description

For custom `renderer` functions passed into `Style` objects, 
- The pixel coordinates passed to the `RenderFunction` may be offscreen-culled,
  this breaks my custom renderer (see reason/example below)
- The `renderer` function does not receive a reference to the `Map` object,
- There is no documented way to obtain the `Map` instance from the `render/State`.
- This means it is difficult to use the function `Map.getPixelFromCoordinateInternal()` (one way to solve my problem)
- Because the `Style` object depends on a `renderer` function that must be passed the `Map` instance, it causes mess and code-order problems when initialising the `Map` object

### Proposed solution

May I please have help with a way to:

- get the `Map` object in custom `RenderFunction`
- OR  a way to call `getPixelFromCoordinateInternal` inside `RenderFunction`
- OR a way to prevent offscreen culling of pixel coordinates passed to `RenderFunction` for line strings

Maybe there is already a way and I'm just not seeing it?

### Motivating Example

I write a custom renderer called `custom_renderer_with_SLK_ticks` and apply it to a vector layer style as shown below:

```typescript
let get_layer_state_road_ticks = map => new VectorLayer({
	source: state_road_only_vector_source,
	style: new Style({
		renderer: custom_renderer_with_SLK_ticks(map)
	}),
	minZoom: 12,
});
```

Why does it take the parameter `map`?
- The map object is needed only for the function `getPixelFromCoordinateInternal`
- Manually mapping the coordinates to pixles is required because:
  - the argument `_pixelCoordinates` (see below) may already have offscreen geometry culled which makes tickmark positions inaccurate

```typescript
import { RenderFunction } from 'ol/style/Style';
import { toContext } from 'ol/render'
// ...
let custom_renderer_with_SLK_ticks:(map:Map)=>RenderFunction = (map:Map) => (_pixelCoordinates, state) => {
	// ...
	// retrieve the full non-offscreen-culled pixel coordinates (will be discarded after using to calculate tickmark positions)
	let coords = state.geometry.getCoordinates()?.map(item => map.getPixelFromCoordinateInternal(item)) ?? [];
	// the following feature properties are used to set tickmark positions
	let slk_from = state.feature.get('START_SLK');
	let slk_to = state.feature.get('END_SLK');
	// ...
	let  geometry: LineString = state.geometry.clone() as LineString;
	let renderContext = toContext(state.context);
	// ... 
	// for each tickmark
	geometry.setCoordinates(item)
	renderContext.drawGeometry(geometry);
	// ...
}
```
PS: Not shown in the snippet above, I have to manually cull offscreen tickmarks to avoid heavy performance penalty.

<details>

<summary>Click to see full custom renderer code (a bit hard to read)</summary>

```typescript
let custom_renderer_with_SLK_ticks:(map:Map)=>RenderFunction = (map:Map) => (_pixelCoordinates, state) => {
	// There are a lot of bugs when the pixel ratio is not 1
	// (had issues several versions of open layers ago... maybe no problems now)
	let pixel_ratio = window.devicePixelRatio ?? 1;
	var context = state.context;
	

	let canvas_size_x = context.canvas.width / pixel_ratio;
	let canvas_size_y = context.canvas.height / pixel_ratio;

	let coords = state.geometry.getCoordinates()?.map(item => map.getPixelFromCoordinateInternal(item)) ?? [];
	var network_type = state.feature.get("NETWORK_TYPE");


	var slk_from = state.feature.get('START_SLK');
	var slk_to = state.feature.get('END_SLK');
	let mls = linestring_measure(coords.map(item => new Vector2(...(item as [number, number]))));
	let ticks;
	let decimal_figures;

	if (network_type === "Main Roads Controlled Path" && state.resolution > 4) {
		return;
	}

	if (state.resolution < 0.3) {
		decimal_figures = 2
		//ticks = linestring_ticks(mls, slk_from, slk_to, 0.001, 10, canvas_size_x/pixle_ratio, canvas_size_y/pixle_ratio);
		ticks = linestring_ticks(mls, slk_from, slk_to, 0.001, 10, canvas_size_x, canvas_size_y, decimal_figures);
	} else if (state.resolution < 1.4) {
		decimal_figures = 1
		//ticks = linestring_ticks(mls, slk_from, slk_to, 0.01, 10, canvas_size_x/pixle_ratio, canvas_size_y/pixle_ratio);
		ticks = linestring_ticks(mls, slk_from, slk_to, 0.01, 10, canvas_size_x, canvas_size_y, decimal_figures);
	} else if (state.resolution < 4) {
		decimal_figures = 0
		//ticks = linestring_ticks(mls, slk_from, slk_to, 0.1, 10, canvas_size_x/pixle_ratio, canvas_size_y/pixle_ratio);
		ticks = linestring_ticks(mls, slk_from, slk_to, 0.1, 10, canvas_size_x, canvas_size_y, decimal_figures);
	} else {
		decimal_figures = 0
		//ticks = linestring_ticks(mls, slk_from, slk_to, 0.1, 10, canvas_size_x/pixle_ratio, canvas_size_y/pixle_ratio);
		ticks = linestring_ticks(mls, slk_from, slk_to, 1, 1, canvas_size_x, canvas_size_y, decimal_figures);
	}
	let tickmarks = ticks.map(item => [
		[
			[item[0][0].x, item[0][0].y],
			[item[0][1].x, item[0][1].y]
		],
		item[1],
		item[2]
	]);
	context.save();
	var renderContext = toContext(context);
	(renderContext as any).extent_ = [0, 0, canvas_size_x, canvas_size_y];  // manual ovveride extent calculation to fix problems when devicePixleRatio is not == 1
	renderContext.setFillStrokeStyle(
		road_network_styles[network_type].getFill(),
		road_network_styles[network_type].getStroke()
	);
	var geometry: LineString = state.geometry.clone() as LineString;
	for (let [item, label, label_rotation] of tickmarks) {
		label_rotation += Math.PI / 2;
		geometry.setCoordinates(item)
		renderContext.drawGeometry(geometry);
		if (label && state.feature.get("CWY") != "Right") {
			let text_style = custom_render_tick_text.clone()
			text_style.setText(label)
			if (Math.abs(label_rotation) > Math.PI / 2) {
				label_rotation += Math.PI;
				text_style.setTextAlign("right");
			}
			text_style.setRotation(label_rotation);
			renderContext.setTextStyle(text_style);
			(renderContext as any).drawText_(item[1], 0, 2, 2);
			renderContext.setTextStyle(null as any);
		}
	}
	context.restore();
}

```

</details>

> CONTEXT: the purpose of this renderer is to add special hatchings or tick marks along the length of road polylines which indicate distance along the road. The linear scale does not necessarily line up with REAL distance along the road and requires both
> 1. that I read other feature parameters to determine the scale/position
> 2. AND I need to do calculations on the FULL un-culled linestring geometry to position the tick marks

Many thanks to all for this awesome project! <3 :)

**Comment by mike-000** [comment]
Specifying the vector layer with a very large `renderBuffer` will prevent loss of offscreen pixel coordinates.

**Comment by ahocevar** [comment]
I think a render function is not the appropriate tool for what you are trying to achieve. You should be using the `geometry` property of the style, and return a `MultiLineString` with your tickmarks. Look at https://openlayers.org/en/latest/examples/line-arrows.html for inspiration.

**Comment by ahocevar** [comment]
> Specifying the vector layer with a very large `renderBuffer` will prevent loss of offscreen pixel coordinates. See also #14427.

This will decrease performance, and the resulting tickmarks will still be inaccurate, because the geometry in pixel coordinates is quantized for the current resolution, so the tickmark positions will be inaccurate.

**Comment by thehappycheese** [comment]
> I think a render function is not the appropriate tool for what you are trying to achieve. You should be using the `geometry` property of the style, and return a `MultiLineString` with your tickmarks. Look at https://openlayers.org/en/latest/examples/line-arrows.html for inspiration.

@ahocevar this is a good suggestion I will investigate this approach further :)

From a quick glance though I do wonder how the performance/features will go... With my current approach I dynamically adjust the number of tick marks depending on the zoom level, and also render text labels beside some of them. The render function does feel like the right approach to avoid the overhead of storing / retrieving the generated tick geometry.

In the past I have tried adding several MultiPoint geometry layers to achieve a similar effect, but you end up having to have multiple layers for different zoom levels and it does not perform well, but it is hard to guess if this Style `geometry` approach might perform better?

I'll try your suggestion out next week and link some images!

**Comment by ahocevar** [comment]
@thehappycheese:

> From a quick glance though I do wonder how the performance/features will go... With my current approach I dynamically adjust the number of tick marks depending on the zoom level, and also render text labels beside some of them. The render function does feel like the right approach to avoid the overhead of storing / retrieving the generated tick geometry.

The same advantages apply when you use the `geometry` of the style. No additional geometries will be stored or retrieved for the tick marks. They are just rendered instead of the original geometry. And you can dynamically adjust the number of tick marks depending on the zoom level just as well, when used in a style function.

**Comment by thehappycheese** [comment]
Hi @ahocevar,

I have tried the `Style({geometry: function (feature){...}})` approach and I have come to the conclusion that it may be unsuitable as replacement for my existing custom renderer; If I have understood everything correctly then I would suggest my original issue is still valid for this situation:

1. The custom geometry function can only return geometry (eg MultiPoint seems suitable); it cannot return metadata. This means I cannot archive
    - unique per-point text labels, on some points but not others
    - rotations such that I could set `new Style({image:new Icon({..., rotation:???})})` for each generated point
3. The custom geometry function only receives a single argument 'feature',
  and therefore the output geometry cannot be modified for different zoom levels
  (ok a work-around may be to just add more layers and set the layers min/max zoom levels, but that really doesn't seem ideal since I want a lot of different zoom levels of detail)

Below are some images of the tickmark effect I am trying to achieve. The last screenshot with the red dots shows my best attempt to get the custom `geometry:` approach to work.

Custom `renderer:` Approach - Zoomed out:
![Zoomed Out Example](https://imgur.com/oUJfnXL.png)

Custom `renderer:` Approach - Medium zoom:
![Medium Zoom Example](https://imgur.com/cvkgEQj.png)

Custom `renderer:` Approach - Full Zoom:
![Full Zoom Example](https://imgur.com/WGSEiaR.png)

`geometry:` Approach:
Unable to get unique label per point, rotated `image` for each point, or varying level of details for different zooms:
![geometry: based approach](https://i.imgur.com/U1chSJb.png)

I know supporting this is a bit niche, but where I work people LOVE having these tickmarks. Finding a way to make them better/faster easier to implement in new map applications would be a big win :)

Many thanks

**Comment by ahocevar** [comment]
The solution is a style function which sets a static `geometry` on the `Style`, not a `geometry` function for a static style:
```js
vectorLayer.setStyle((feature, resolution) => {
  const originalGeometry = feature.getGeometry();
  const tickMarks = calculateTickMarks(originalGeometry, resolution);
  return tickMarks.map(tickMark => new Style() {
    geometry: tickMark.geometry,
    text: new Text({
      text: tickMark.text,
      rotation: tickMark.rotation
    })
  })
};

**Comment by thehappycheese** [comment]
> ... an array of styles (one for each tick mark):

@ahocevar whoa ok I would never have thought to try that... that's a lot of style instances!

Ok I'll try it soon and see if it performs well with lots of ticks. That is the nice clean implementation I'm looking for :)

Thanks again for your help!

**Comment by thehappycheese** [comment]
@ahocevar I have tried out your suggestion and it is a nice clean approach; but performance-wise I think this doesn't work.
When panning around the performance seems to be good (I guess this is due to the clever render cache open layers does). However when zooming, the ticks are re-generated for all visible line strings at once and this introduces a heavy lag spike that is very unpleasant. Could be mitigated by having fewer tickmark levels of detail I guess... but there is no restriction when using the custom renderer.

![Performance test results](https://imgur.com/DwxZMKX.png)

Note for the test the custom renderer was drawing labels too. I did not yet implement the labels for the new approach... probably the difference would be even more significant with labels:

```javascript
// perfectly replicates the look of custom renderer, but without labels:
var state_road_vector_layer_ticks_geometry = new ol.layer.Vector({
	source: state_road_only_vector_source,
	style:(feature, resolution) =>{
		let tick_marks = custom_style_geometry(feature, resolution);
		return tick_marks.map(tick_mark => new ol.style.Style({
			geometry: tick_mark.geometry,
			image:new ol.style.RegularShape({
				stroke: road_network_styles[feature.get("NETWORK_TYPE")].getStroke(),
				radius: tick_mark.major ? 6 : 2,
				points: 2,
				angle:  tick_mark.rotation
			})
		}));
	},
	minZoom: 16
});
```

I think this style-per marker technique is very tidy though and likely helpful for other use cases.
Many thanks :)

**Comment by ahocevar** [comment]
You should be able to boost performance by setting the icon cache size to a high value (maybe 1000 or 2000). See https://openlayers.org/en/latest/apidoc/module-ol_style_IconImageCache-IconImageCache.html. Or - even better - create your own cache (with stroke, radius and angle as cache keys) for the `RegularShape` styles, instead of creating a new instance for each tick mark.

**Comment by thehappycheese** [comment]
@ahocevar thankyou so much for your patient assistance :) I will make an attempt to optimize the cache!

**Comment by thehappycheese** [comment]
Hi @ahocevar,

So with icon cache the performance difference is now indiscernible during use.

### When panning:

The custom renderer performs a tiny bit worse, but is generally fast enough not to cause dropped frames.
The style/geometry approach makes much better use of cache and consistently outperforms the custom renderer.

### When zooming

Both the custom renderer and the style based approach cause minor stuttering / frame drops when zooming. The custom renderer is typically not as bad as the style/geometry approach... but now with the icon cache, they both feel about the same.

![Benchmark comments](https://imgur.com/0DI0f9S.jpg)


<details>

<summary>Click for new code with cache</summary>

```javascript
function custom_style_geometry(feature, resolution){
	const coords = feature.getGeometry().getCoordinates();
	var slk_from = feature.get('START_SLK');
	var slk_to = feature.get('END_SLK');
	let tick_marks;
	let decimal_figures;
	if (resolution < 0.1) {
		decimal_figures = 2;
		tick_marks = linestring_ticks_geometry(coords, slk_from, slk_to, 0.001, 10, decimal_figures);
	} else if (resolution < 1) {
		decimal_figures = 1;
		tick_marks = linestring_ticks_geometry(coords, slk_from, slk_to, 0.01, 10, decimal_figures);
	} else if (resolution < 2){
		decimal_figures = 0;
		tick_marks = linestring_ticks_geometry(coords, slk_from, slk_to, 0.1, 10, decimal_figures);
	} else {
		decimal_figures = 0;
		tick_marks = linestring_ticks_geometry(coords, slk_from, slk_to, 1, 1, decimal_figures);
	}
	return tick_marks;
}



let tick_image_cache = {}
for(let i=-180;i<=180;i++){
	let angle = i/180*Math.PI;
	tick_image_cache[i+"true"] = new ol.style.RegularShape({
		stroke: new ol.style.Stroke({
			color: 'rgba(50, 255, 255, 255)',
			width: 2,
		}),
		radius: 6,
		points: 2,
		angle:  angle
	})
	tick_image_cache[i+"false"] = new ol.style.RegularShape({
		stroke: new ol.style.Stroke({
			color: 'rgba(50, 255, 255, 255)',
			width: 2,
		}),
		radius: 2,
		points: 2,
		angle:  angle
	})
}

let tick_text_fill_and_stroke = {
	fill: new ol.style.Fill({
		color: "#000"
	}),
	stroke: new ol.style.Stroke({
		color: '#fff',
		width: 1,
	})
}

var state_road_vector_layer_ticks_geometry = new ol.layer.Vector({
	source: state_road_only_vector_source,
	style:(feature, resolution) =>{
		let tick_marks = custom_style_geometry(feature, resolution);
		return tick_marks.map(tick_mark => {
			let text_rotation = tick_mark.rotation + Math.PI / 2;
			let text_align = "left";
			if (Math.abs(text_rotation) > Math.PI / 2) {
				text_rotation += Math.PI;
				text_align = "right";
			}
			let text = (tick_mark.major && (feature.get("CWY")==="Left" || feature.get("CWY")==="Single")) ? {
				text: new ol.style.Text({
					text      : tick_mark.text,
					textAlign : text_align,
					offsetX   : Math.cos(tick_mark.rotation+Math.PI/2)*8,
					offsetY   : Math.sin(tick_mark.rotation+Math.PI/2)*8,
					rotation  : text_rotation,
					font      : "bold 16px sans-serif",
					...tick_text_fill_and_stroke,
				})
			} : {};
			let lookup_image = tick_image_cache[Math.round(tick_mark.rotation/Math.PI*180)+""+tick_mark.major]
			return new ol.style.Style({
				geometry: tick_mark.geometry,
				image:lookup_image,
				...text,
			})
		});
	},
	
	minZoom: 12
});
```

</details>

Again really appreciate your help thanks so much
I still feel somehow both methods are a bit of a hack and it should be possible to make hatchings work with less performance impact. But I guess the issue can be closed unless you have any ideas where to go from here ?

**Comment by ahocevar** [comment]
You can definitely cache the text styles too, using text and rotation as cache keys. You'd create cache entries lazily as you need them, when they're not in the cache yet. You could even use `getAnimating()` and `getInteracting()` from the view and pause creating new texts during zooming, then use the map's `moveend` Event to do a final render where all missing texts are created.

Even if done on the renderer level, tick marks would not perform much better. With proper caching and performance optimisations on the application level, the style geometry approach should be appropriate.

You could also create a [3rd party library](https://openlayers.org/3rd-party/) when you're happy with the result and think that it could be useful for others.

**Comment by thehappycheese** [comment]
Hi @ahocevar that sounds doable. I might have a go at the library. Thanks again  :)
