### ISSUE TITLE
Draw Interaction doesn't handle successive clicks if they were performed very fast

### ISSUE THREAD

**Issue by become-iron** [openlayers/openlayers#14502]
**Describe the bug**

Draw Interaction doesn't handle successive clicks if they were performed very fast.

**To Reproduce**

1. Go to https://codesandbox.io/s/draw-features-forked-j42gq7 (Drag Pan interaction is removed)
2. Start drawing a polygon
3. Try to draw many points while moving cursor and clicking very fast
4. No point is added to geometry

Demonstration: [Screencast from 11-02-23 22:42:59.webm](https://user-images.githubusercontent.com/8668962/218261285-757c9674-8030-4bf1-8e1d-bf7f32dcabc3.webm). While moving a cursor I were clicking very fast trying to add points

**Expected behavior**

I would like points to be added, even if there was little delay between successive clicks.

If it's by design, is there a way to work around?

**Comment by MoonE** [comment]
If you are moving and clicking very fast some of those events might be `drag` events. These are not handled by the Draw interaction.
Use this to check:
```js
map.on('pointerdrag', (e) => console.log(e.type, e.dragging));
```
I don't think there is a way to make it work currently.

**Comment by become-iron** [comment]
Yes, that seems to be the case

But the problem is that professional GIS users draw points very quickly while vectorizing images...

**Comment by M393** [comment]
There is the [moveTolerance](https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html) config which might help in this case.
