### ISSUE TITLE
GeoTIFF getResolutions calculation uses incorrect value for image height

### ISSUE THREAD

**Issue by spoyd** [openlayers/openlayers#14510]
The `getResolutions()` function of `GeoTIFF.js` uses the value `fileDirectory.ImageHeight`.
It should really be using `fileDirectory.ImageLength` like the other methods in this file.

**Comment by spoyd** [comment]
Added pull request to fix this: https://github.com/openlayers/openlayers/pull/14511

**Comment by tschaub** [comment]
Thanks for reporting the issue and providing a fix, @spoyd!
