### ISSUE TITLE
Error in Safari 11.1.2 - ReferenceError: Can't find variable: ResizeObserver

### ISSUE THREAD

**Issue by lwsweb** [openlayers/openlayers#14529]
When creating a new map using Safari 11.1.2, we see the following error:
> ReferenceError: Can't find variable: ResizeObserver

I'm not sure if this old version of Safari is expected to be supported or not.  This error does not occur in the latest version of Safari.  I'm guessing the issue started in relation to #14305.  OpenLayers 6.15.1 did not have this error in the same browser.  Thanks!

**Comment by ahocevar** [comment]
This should be simple to fix on the application level - just include a polyfill for `ResizeObserver`, e.g. https://www.npmjs.com/package/resize-observer-polyfill.

**Comment by lwsweb** [comment]
Thank you for your help.  We were able to get this working again using the link you provided.
