### ISSUE TITLE
Area calculation not proper while drawing a polygon intersecting it's own shape

### ISSUE THREAD

**Issue by aashirwadgupta** [openlayers/openlayers#1453]
I was trying to draw and measure area of a polygon using openlayer3, It gave correct values for proper figures in which line continuation didn't intersect. 
But when I draw a figure in which line continuation did intersect the area was coming as subtraction of the two areas. 
Please find the images for more clarity
Image 1 - Here the figure has been drawn in a continuation pattern
![error in area for intersection figure](https://cloud.githubusercontent.com/assets/12935036/9329892/c398603c-45f8-11e5-855f-c25b40bfe263.JPG)

Image 2 - A simple triangle is drawn which has more area then the previous figure as mentioned in image-1
![proper area for regular figure](https://cloud.githubusercontent.com/assets/12935036/9329899/d580627c-45f8-11e5-9528-f6d654aa6c58.JPG)

**Comment by bartvde** [comment]
so why do you mention openlayers3 but your screenshots are from version 2?
