### ISSUE TITLE
Change how viewNotMoving is calculated for PointsLayer

### ISSUE THREAD

**Issue by jeremy-smith-maco** [openlayers/openlayers#14544]
**Describe the bug**
I was implementing heatmaps that change with live values in our project and it would seemingly randomly stop updating with live values and when moving features around it would not update too. I did a bunch of debugging and such and found out that in the `PointsLayer` class, the `viewNotMoving` variable in the `prepareFrameInternal` method was being calculated as `false` every render. 

The root of the cause was to do with my interactions as they were calling handleUp methods of other interactions which calls `endInteraction` on the `View` of the map even though the `beginInteraction` was not called which causes the `viewHints[ViewHint.INTERACTING]` count to go negative. The `View` class handles negative values in the `getAnimating` and `getInteracting` methods by checking if the count is above 0.

https://github.com/openlayers/openlayers/blob/main/src/ol/renderer/webgl/PointsLayer.js#L519

Obviously I should just handle the interactions better but I think when calculating the `viewNotMoving` variable, it should either use the result of the `getAnimating` and `getInteracting` methods and put them into the `frameState`, or instead of just checking `!frameState.viewHints...` to instead check if they are <= 0. It could potentially save future people from having to dig down the rabbit hole, or maybe users should just handle their interactions properly. Not sure.

**To Reproduce**
1. Have heatmap layer
2. Call `endInteraction` on the map's view
3. Heatmap no longer updates

Example: https://codesandbox.io/s/snap-forked-2em51i?file=/main.js
(although in this example it also seems to break the modify as well, will re-render when you move the map though)

**Expected behavior**
The heatmap should continue to update even when the interaction count is a negative number.

**Comment by ahocevar** [comment]
@jahow Can you take a look at this please?

**Comment by jahow** [comment]
@jeremy-smith-maco I submitted a PR which should fix the issue in your codesandbox. Thanks a lot for the preliminary research!

**Comment by jeremy-smith-maco** [comment]
Much appreciated, thanks guys!
