### ISSUE TITLE
Area calculation not proper while drawing a polygon intersecting it's own shape

### ISSUE THREAD

**Issue by aashirwadgupta** [openlayers/openlayers#1454]
I was trying to draw and measure area of a polygon using Openlayers v3.7.0, It gave correct values for proper figures in which line continuation didn't intersect. 
But when I draw a figure in which line continuation did intersect the total area was coming as subtraction of the two figures which forms as a result of line intersection. 
Please refer the image below for more details.

![open layer 3 polygon areas issue](https://cloud.githubusercontent.com/assets/12935036/9330147/9d872692-45fa-11e5-80a0-fb343241d7a8.JPG)

**Comment by bartvde** [comment]
This issue tracker is for OpenLayers 2

If you're talking about OpenLayers 3 you need to use https://github.com/openlayers/ol3 instead

I'm now very confused.
