### ISSUE TITLE
Counld consider WKT readfeature support "Z" dimension?

### ISSUE THREAD

**Issue by L-hikari** [openlayers/openlayers#14558]
**Is your feature request related to a problem? Please describe.**
Hi~ When i use WKT to read like `POINT(10 10, 10)`,  I got a error "Uncaught Error: Unexpected `,` at position 11 in `POINT(10 10, 10)`", I think because of the  wkt `POINT(10 10, 10)` include "Z" dimension "10" cause TokenType not match. Counld consider support "Z" dimension for WKT?

**Describe the solution you'd like**
I hope "Z" dimension do not handle, like GeoJSON reader. Maybe i counld new a pull request

**Comment by mprins** [comment]
Please validate your input with the WKT spec as your example is not according to specification for POINT Z (x y z)

**Comment by L-hikari** [comment]
> @L-hikari Please validate your input with the WKT spec as your example is not according to specification for `POINT Z (x y z)`

@mprins Thanks!
