### ISSUE TITLE
StaticImage not rendering in iOS Safari/Chrome

### ISSUE THREAD

**Issue by mediafreakch** [openlayers/openlayers#14555]
**Describe the bug**

Image rendered using `ImageStatic` class doesn't render on iOS (Safari/Chrome) if it exceeds certain dimensions.

**To Reproduce**

*Prerequisites*: Use iOS 15 or later

1. Go to [CodeSandbox](https://7pv3l2.csb.app/)

**Expected behavior**

An image should appear. You can zoom and pan the image.

**Actual result**

No image appears on iOS.

**CodeSandbox**

https://codesandbox.io/s/openlayers-7-ios-canvas-limit-exceeded-7pv3l2?file=/main.js

**Other notes**

In the developer console there's a warning like the following:

> Canvas area exceeds the maximum limit (width * height > 16777216)

**Comment by mediafreakch** [comment]
I updated the codesandbox example to do exactly that, yet the image didn't show up with `ol@7.3.0`. However downgrading the codesandbox to `ol@7.2.2` made the problem go away. So it seems the issue was introduced in 7.3.0.

**Comment by mediafreakch** [comment]
Probably https://github.com/openlayers/openlayers/pull/14444 ?

**Comment by ahocevar** [comment]
Yes, you are probably right @mediafreakch. The problem that #14444 solved could alternatively be solved by working with only the part of the image that the renderer currently needs, like e.g. the ImageWMS source. If someone feels up for such a change, a pull request would be welcome.

**Comment by mediafreakch** [comment]
Will #14444 be rolled back? A bad performance is better than a broken feature... Otherwise we're stuck on 7.2.2 until this is resolved for iOS devices.

**Comment by ahocevar** [comment]
A rollback of #14444 will be part of the change that also makes it work on iOS.  Otherwise it's too much back and forth, because like you rely on having #14444 rolled back, others rely on #14444 being there.
