### ISSUE TITLE
External map example does not render a map

### ISSUE THREAD

**Issue by RobQuincey** [openlayers/openlayers#14569]
**Describe the bug**
The [External Map example](https://openlayers.org/en/latest/examples/external-map.html) does not render a map in the external window it opens

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the [External Map example](https://openlayers.org/en/latest/examples/external-map.html) 
2. Click on 'Open external map' button
3. A new browser window is opened, but there is no map in it

**Expected behaviour**
Map should be rendered. I believe this is just a CSS issue. The `map` class for the external map has a height of 100%, I believe this could be fixed by simply switching this to use viewport units `vh` and `vw`.

Happy to open a PR for this if you confirm the issue.

**Comment by MoonE** [comment]
Thanks for identifying the problem. 

Not sure why this example stopped working, but your proposed solution sounds good.

**Comment by MoonE** [comment]
Looks like the added `<!DOCTYPE html>` in aa7be0baeb49e7951b4d670cd9cf0d91234d0fbe was responsible for this.

Please do provide a PR, @RobQuincey.

**Comment by RobQuincey** [comment]
Good spot @MoonE, I've submitted a PR that just makes it use 100vh and vw instead, which should be fine for this example.
