### ISSUE TITLE
Contributing page has link to what looks like defunct mailing list

### ISSUE THREAD

**Issue by RobQuincey** [openlayers/openlayers#14567]
**Describe the bug**
The `CONTRIBUTING.md` page has a link to join the dev mailing list here - https://groups.google.com/g/openlayers-dev - This appears to have not been used properly for a number of years and the most recent messages are all spam.

**Expected behaviour**
Page should not have the link on. If there is a separate place where these kinds of discussions take place, that should be linked to, otherwise it should just be removed.

I am happy to quickly do this if someone can confirm that this list is now defunct and if there is an alternative.

**Comment by ahocevar** [comment]
Confirmed. Please submit a pull request that removes the link. Thanks for your help!
