### ISSUE TITLE
About Raster Reprojection

### ISSUE THREAD

**Issue by zym-2020** [openlayers/openlayers#14570]
I want to load tiles from different projection systems at the same time（**EPSG:3857**, **EPSG:4326**）and make them completely coincide,  wath should I do?

I referred to this example: 
>https://openlayers.org/en/latest/examples/reprojection.html

But I don't know if TMS's tiles are the same as this

```
new TileLayer({
  visible: true,
  source: new XYZ({
    url: ’...‘
    projection: "EPSG:3857",
  }),
}),

new TileLayer({
  source: new XYZ({
    url: '...',
    projection: "EPSG:4326",
  }),
}),
```
this is my layers and View is **4326**

Hope for your reply, thank you！

**Comment by ahocevar** [comment]
Looks correct. If the sources you're using provide the projections you specify, the above should work.

**Comment by zym-2020** [comment]
@ahocevar It does work.But different projection tiles will have shifts, and I wonder if there is a way to make the tiles coincide exactly

**Comment by mike-000** [comment]
If the layers do not coincide you may need to specify a custom tile grid for the EPSG:4326 source

By default OpenLayers will use a tile grid a single tile wide at zoom 0

    tileGrid: createXYZ({
      extent: [-180, -90, 180, 90],
      maxResolution: 360 / 512,
      maxZoom: ???,
    }),

However many EPSG:4326 sources use a grid which is a single tile high (and therefore 2 tiles wide) at zoom 0

    tileGrid: createXYZ({
      extent: [-180, -90, 180, 90],
      maxResolution: 180 / 512,
      maxZoom: ???,
    }),

**Comment by zym-2020** [comment]
@mike-000  Thanks, that's really the reason you said
