### ISSUE TITLE
TileGrid.getTileRangeExtent() does not take into account the origin corner

### ISSUE THREAD

**Issue by sguimmara** [openlayers/openlayers#14578]
**Describe the bug**

We are using OpenLayers in the [Giro3D](https://giro3d.org) project, notably to process tiled sources. While trying to use the `getTileRangeExtent()`, I found what looks like a bug.

A `TileGrid` whose origin is at the top left corner will compute an incorrect extent for a given `TileRange`. The computed extent will start at the top edge of the grid, then continue upward, out of bounds, instead of starting at the bottom edge and continue upward.

![image](https://user-images.githubusercontent.com/5512096/225695067-9c7e588d-0721-4677-9b44-2cfbc1a82a39.png)

**To Reproduce**

Add this unit test in `TileGrid.test.js`:

```js
  describe('getTileRangeExtent', () => {
    it('returns the whole grid extent for zoom level zero', () => {
      const tilegrid = new TileGrid({
        resolutions: [1],
        origin: [0, 10],
        tileSize: 10,
      });

      const extent = tilegrid.getTileRangeExtent(0, new TileRange(0, 0, 0, 0));

      expect(extent[0]).to.be(0);
      expect(extent[2]).to.be(10);
      expect(extent[1]).to.be(0); // got: 10
      expect(extent[3]).to.be(10); // got : 20
    });
  });
```

**Expected behavior**

The origin of the grid should not change the computation result.

**Comment by ahocevar** [comment]
I may be missing something, but the expecation of your test looks wrong to me. With a tile size of 10, and an origin at [0, 10], I expect the tile range of the top left tile at zoom zero to have an extent of [0, 10, 10, 20]. The extent your test is expecting is empty.

**Comment by sguimmara** [comment]
> I may be missing something, but the expecation of your test looks wrong to me. With a tile size of 10, and an origin at [0, 10], I expect the tile range of the top left tile at zoom zero to have an extent of [0, 10, 10, 20]. The extent your test is expecting is empty.

Indeed, my test was a bit naive. The real case happened with the `Stamen` source. Here is an updated test case : 

```js
  describe('getTileRangeExtent', () => {
    it('returns the whole grid extent for zoom level zero', () => {
      const source = new Stamen({layer: 'watercolor'});

      const tileGrid = source.tileGrid;
      const extent = tileGrid.getExtent();
      const tileRange = new TileRange(0, 0, 0, 0);
      const tileExtent = tileGrid.getTileRangeExtent(0, tileRange);

      expect(extent[0]).to.eql(tileExtent[0]);
      expect(extent[1]).to.eql(tileExtent[1]);
      expect(extent[2]).to.eql(tileExtent[2]);
      expect(extent[3]).to.eql(tileExtent[3]);
    });
  });
```

My expectation is that the root tile should have the same extent as the grid itself, but instead, the computed root tile extent is outside the gridextent.

**Comment by ahocevar** [comment]
Yes this is indeed a problem. Out of curiosity: how did you find out about this? It's used nowhere in the library, and neither `getTileRangeExtent()` nor `TileRange` are part of the API.

So the fix I'm going to propose is the removal of the `getTileRangeExtent()` method. The reason for the miscalculation is that originally, when that method was written, our internal tile grids had tile coordinates increasing left to right and bottom to top.

**Comment by sguimmara** [comment]
> Out of curiosity: how did you find out about this? 

We have a three.js based 3D library to display 3D maps (for example [this one](https://giro3d.org/examples/planar_mapbox.html))

I'm trying to solve a problem that would make use of the `getTileRangeExtent()`:

The 3D map is subdivided into tiles that have their own extent that is unrelated to the tiling scheme of the underlying OpenLayer sources. The map tiles can even be rectangular.

To create the texture to apply to a 3D map tile, we fetch all the OL tiles that overlap this 3D map tile, then compose them by stitching them on a pseudo-canvas.

Since the extent of the OL tile range is bigger than the map tile extent, we need to compute the relationship between the two so that we only display the part of the texture that intersects the map tile extent, hence why I needed to compute the extent of the tile range.

Now instead of using `getTileRangeExtent()`, I used a more brute-force approach by computing the union of the extents of all the tiles in the tile range, and it works.

> It's used nowhere in the library, and neither `getTileRangeExtent()` nor `TileRange` are part of the API.

We are using OpenLayers in a bit unorthodox fashion : we do the rendering ourselves, but we leverage OL's capabilities to compute tile grid, resolve zoom levels, compute tile  extents, resolve tile URLs, etc. It's extremely useful because a lot can go wrong with tiling schemes and OL handles a lot of the complexity, so we'd rather avoid rewriting this part. A bit like a middleware for vector and image sources.

> So the fix I'm going to propose is the removal of the `getTileRangeExtent()` method.

I thought it was a useful function but feel free to remove it.

**Comment by ahocevar** [comment]
Ok, sounds great! Sounds like what you're doing now is something like:
```js
function getTileRangeExtent(z, minX, minY, maxX, maxY) {
  const extent = createEmpty();
  for (let x = minX; x <= maxX; ++i) {
    for (let y = minY; y <= maxY; ++j) {
      extend(extent, tileGrid.getTileCoordExtent([z, x, y]);
    }
  }
  return extent;
}
```
With a bit more knowledge about how tiles work, this could be simplified to:
```
function getTileRangeExtent(z, minX, minY, maxX, maxY) {
  const bottomLeft = getBottomLeft(tileGrid.getTileCoordExtent([z, minX, maxY]);
  const topRight = getTopRight(tileGrid.getTileCoordExtent([z, maxX, minY]);
  return [...bottomLeft, ...topRight];
}

**Comment by sguimmara** [comment]
> Ok, sounds great! Sounds like what you're doing now is something like:
> 
> ```js
> function getTileRangeExtent(z, minX, minY, maxX, maxY) {
>   const extent = createEmpty();
>   for (let x = minX; x <= maxX; ++i) {
>     for (let y = minY; y <= maxY; ++j) {
>       extend(extent, tileGrid.getTileCoordExtent([z, x, y]);
>     }
>   }
>   return extent;
> }
> ```
> 
> With a bit more knowledge about how tiles work, this could be simplified to:
> 
> ```js
> function getTileRangeExtent(z, minX, minY, maxX, maxY) {
>   const bottomLeft = getBottomLeft(tileGrid.getTileCoordExtent([z, minX, maxY]);
>   const topRight = getTopRight(tileGrid.getTileCoordExtent([z, maxX, minY]);
>   return [...bottomLeft, ...topRight];
> }
> ```

Yes that's something very similar indeed !
