### ISSUE TITLE
examples link is dead

### ISSUE THREAD

**Issue by ewerybody** [openlayers/openlayers#1458]
I would have loved to see these: But the link on
The **examples directory** is full of useful examples.

namely: "http://openlayers.org/dev/examples/" is no more :(

**Comment by ahocevar** [comment]
Where did you find this link? Then we can change that page. The examples are now hosted at http://dev.openlayers.org/examples/.

**Comment by ahocevar** [comment]
As far as I can tell, the links on http://openlayers.org/two/ are correct.

**Comment by ewerybody** [comment]
Directly on the frontpage of this project:
https://github.com/openlayers/openlayers#using-openlayers-in-your-own-website

On http://openlayers.org/two/ there is another one broken under "**hosted examples**" a little down the page. linking to "http://openlayers.org/dev/examples/"

**Comment by ewerybody** [comment]
But yea: I was already clicking around in the ol3 stuff! Awesome :]

**Comment by ewerybody** [comment]
nice! :]
the link on http://openlayers.org/two/ is still broken. Under "hosted examples" a little down the page. linking to "http://openlayers.org/dev/examples/" but I dunno if you're actually into this *shrug*

**Comment by ahocevar** [comment]
Pull request for the other broken link created. See openlayers/openlayers.github.io#54.
