### ISSUE TITLE
applyTransform for empty extent will get NaN

### ISSUE THREAD

**Issue by dennis-leee** [openlayers/openlayers#14625]
**Describe the bug**
applyTransform for empty extent will get a extent with NaN, use this extent as param to fit view will throw error.

**To Reproduce**
simple code is below
```javascript
import { applyTransform, createEmpty } from 'ol/extent';
import { getTransform } from 'ol/proj';

function fit(geomOrExtent) {
  // default value
  let extent = createEmpty();
  if (isArray(geomOrExtent)) {
    // assignment by case
  }

  extent = applyTransform(extent, getTransform('EPSG:4326', 'EPSG:3857'));
  map.getView().fit(extent);
}
```

then get error
<img width="613" alt="image" src="https://user-images.githubusercontent.com/22017489/228728865-77f2f818-e6b8-4965-aac7-42d39694ef0c.png">

i found it actually cause by `fromEPSG4326` which return by `getTransform('EPSG:4326', 'EPSG:3857')`
more precisely, it's caused by `Math.tan` will transform `Infinity` to `NaN`.
see below
<img width="849" alt="image" src="https://user-images.githubusercontent.com/22017489/228727872-7b7dac45-0b75-4027-b0d0-cd9634426f47.png">

**Expected behavior**
`fromEPSG4326` can handle empty extent (`Infinity`) correctly

btw, the background is that my user use EPSG:4326, but tile service use EPSG:3857
so I need to do a conversion at the input and output.

**Comment by mike-000** [comment]
I agree a empty extent should be empty in any projection.  However, it is likely any application code would need to test `isEmpty` at some point in code such as yours.  Even if `applyTransform` made a special case (similar to `getArea`) for an empty extent you would still get a `Cannot fit empty extent provided as 'geometry'` assertion at the next line.
