### ISSUE TITLE
Incorrect coordinate layout when reading geometries in EPSG:4326 from GML2 data

### ISSUE THREAD

**Issue by MagicCrazyMan** [openlayers/openlayers#14620]
**Describe the bug**
I published a MultiPolygon(in `EPSG:4326`) via `geoserver` and fetch GML2 data, `geoserver` returned a GML2 data with srsName `http://www.opengis.net/gml/srs/epsg.xml#4326` and coordinates in layout `(longitude, latitude)`.
But when i tried to read features with `ol/format/GML2`, coordinate layout of features swap to `(latitude, longitude)`, which seems like incorrect.

I did some debug and found that, in function `ol/format/GML2#readFlatCoordinates`, seems like it detects coordinate layout different between `geoserver` (or others GIS tools → [CRS Support of GML](https://gdal.org/drivers/vector/gml.html#crs-support))

GML:
```
<?xml version="1.0" encoding="UTF-8"?>
<wfs:FeatureCollection xmlns="http://www.opengis.net/wfs" xmlns:wfs="http://www.opengis.net/wfs"
  xmlns:test="test" xmlns:gml="http://www.opengis.net/gml"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="test http://localhost:8080/geoserver/test/wfs?service=WFS&amp;version=1.0.0&amp;request=DescribeFeatureType&amp;typeName=test%3Agmltest
                      http://www.opengis.net/wfs http://localhost:8080/geoserver/schemas/wfs/1.0.0/WFS-basic.xsd"><gml:boundedBy>
    <gml:null>unknown</gml:null>
  </gml:boundedBy><gml:featureMember>
    <test:gmltest fid="gmltest.1">
      <test:the_geom>
        <gml:MultiPolygon srsName="http://www.opengis.net/gml/srs/epsg.xml#4326">
          <gml:polygonMember>
            <gml:Polygon>
              <gml:outerBoundaryIs>
                <gml:LinearRing>
                  <gml:coordinates xmlns:gml="http://www.opengis.net/gml" decimal="." cs="," ts=" ">-36.17906769,49.69821404
  108.67644794,53.99659729 122.86111268,-12.19850481 54.08698063,-49.59443911
  -36.17906769,-23.80413959 -33.17019941,12.73211806 -36.17906769,49.69821404</gml:coordinates>
                </gml:LinearRing>
              </gml:outerBoundaryIs>
            </gml:Polygon>
          </gml:polygonMember>
        </gml:MultiPolygon>
      </test:the_geom>
      <test:FID>0</test:FID>
    </test:gmltest>
  </gml:featureMember></wfs:FeatureCollection>
```

**To Reproduce**
1. read GML2 data above using `ol/format/GML2`
2. unable to display feature or display a wrong feature in map

**Expected behavior**
Read features from GML2 data correctly

**Comment by ahocevar** [comment]
The SRS Code `http://www.opengis.net/gml/srs/epsg.xml#4326` has `neu` (lat/lon) axis orientation in OpenLayers. If that does not work for your use case, you could apply the workaround shown in #2122, i.e.
```js
import {addProjection, Projection} from `ol/proj`;
addProjection(
    new Projection('http://www.opengis.net/gml/srs/epsg.xml#4326', 'enu')
);

**Comment by MagicCrazyMan** [comment]
sorry for replying so late. I tried the solution, it works, thanks so much. I will close this issue.
