### ISSUE TITLE
[Question] Snap LineString to LineString

### ISSUE THREAD

**Issue by fmg-lydonchandra** [openlayers/openlayers#14642]
Hi, is there an easy way to snap a LineString to another LineString ? 
Or snap left side of rectangle polygon to a LineString ?

Other than modify and each vertex manually ?
Each LineString has 100 vertices. Something like batch snapping, even though I haven't seen this anywhere yet.

**Comment by ahocevar** [comment]
Maybe take a look at https://openlayers.org/en/latest/examples/tracing.html.

**Comment by fmg-lydonchandra** [comment]
yes thank you. i think this will do it.
