### ISSUE TITLE
Feature with custom svg renderer disappears randomly on render change

### ISSUE THREAD

**Issue by xouillet** [openlayers/openlayers#14644]
**Describe the bug**

When creating a  feature on a `VectorLayer` with a custom renderer, we experience render failure when the render function draws a different svg on the canvas. One way to reproduce it easily is to have a "selected" renderer, and we experience that feature disappears on first selection often, and works better after that, but we can still experience render failure randomly.

I've created a minimal project to reproduce this behaviour here: https://github.com/xouillet/ol_playground/blob/main/main.ts

Don't know if its related, but these features also flicker from time to time when updated (moved, or map panning/zooming), but it's harder to reproduce. When this happen, all the features with custom renderer disappear/reappear, even if they are not in the same layer.

**To Reproduce**

1. Go to https://codesandbox.io/p/github/xouillet/ol_playground/main?file=main.ts
2. Click on the feature (the grey box in the middle of the map)
3. Often it will disappear on first click
4. Click elsewhere, it will reappear
5. Click on it again, it will have the selected color (dark red)
6. Click outside/on it multiple time, you may experience another render failure

**Expected behavior**

That the render is correct each time

**Comment by MoonE** [comment]
When you construct an Image from a data url it is still not immediatly available. You need to listen to its load event and rerender the map. 

Here is an updated example:
https://codesandbox.io/p/github/xouillet/ol_playground/csb-190t8o/draft/jovial-villani?file=%2Fmain.ts

As a side note, a Polygon should start and end with the same point. An easy way to construct a polygon is
```ts
import {fromExtent as polygonFromExtent} from "ol/geom/Polygon.js";
const polygon = polygonFromExtent([ 
  pose.x - robot_width,
  pose.y - robot_length,
  pose.x + robot_width,
  pose.y + robot_length,
]);
```

**Comment by xouillet** [comment]
That did the trick, indeed. Thank you very much !

Closing this issue.
