### ISSUE TITLE
forEachFeatureAtPixel finds feature far away from clicked pixel in FireFox

### ISSUE THREAD

**Issue by nebucaz** [openlayers/openlayers#14640]
**Feature is detected far away from feature**

Clicking far away from the feature finds it anyway in Firefox despite hit tolerance is 0.

**To Reproduce**
1. Open Firefox 111.0.1 (64-bit)
2. Go to https://openlayers.org/en/latest/examples/hit-tolerance.html
3. in the blue water click near the green line. 
4. At bottom left the "A feature got hit" is displayed even though the pointer is far off the green line (see attached screenshot)

<img width="485" alt="Screenshot 2023-04-05 at 21 01 36" src="https://user-images.githubusercontent.com/961682/230183100-3f0a5ff6-815c-4e2b-a50e-14c3bc8b8ccd.png">

**Expected behavior**
The same test in another browser (e.g. Safari) the "A feature got hit" text is only displayed when the pointer is exactly above the green line

**Comment by mike-000** [comment]
Also cannot reproduce on Windows 10 Firefox 111.0.1 (64-bit)

**Comment by nebucaz** [comment]
Experiencing it **only** in Firefox 111.0.1 (64-bit) on **macOS Ventura 13.3** (22E252)

Not in: 
- Safari Version 16.4 (18615.1.26.11.22)
- Chrome Version 112.0.5615.49 (Official Build) (arm64)
- Microsoft Edge Version 112.0.1722.34 (Official build) (arm64)

The problem in firefox seems to be related to this extension: [CanvasDefender](https://addons.mozilla.org/en-US/firefox/addon/no-canvas-fingerprinting). When removing the extension, everything works as expected.
