### ISSUE TITLE
renderBuffer not work

### ISSUE THREAD

**Issue by younggis** [openlayers/openlayers#14662]
i used vectortile to render point layer,but image clipped in vectortile edges,like this:
![image](https://user-images.githubusercontent.com/16437628/231408031-ccb7be30-20f9-4606-9d34-a12df5ecce33.png)

view some issue,i try to set renderBuffer,but not work.

note: ol version is 6.4.3

thanks

**Comment by M393** [comment]
Do you know with what buffer size the tiles were generated?

> Vector tiles are usually generated with a buffer, so this value should match the largest possible buffer of the used tiles. It should be at least the size of the largest point symbol or line width.

From the `ol/layer/VectorTile` [`renderBuffer`](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorTile-VectorTileLayer.html) api doc.

The icon size has to be considered when generating the tiles.

**Comment by younggis** [comment]
@M393 
No matter how much I set it up, it doesn't work。like this
![image](https://user-images.githubusercontent.com/16437628/231422848-379e0409-96ed-45e9-84a4-4784a0cd67ab.png)
