### ISSUE TITLE
renderBuffer not work

### ISSUE THREAD

**Issue by younggis** [openlayers/openlayers#14665]
i used vectortile to render point layer,but image clipped in vectortile edges,like this:
![image](https://user-images.githubusercontent.com/16437628/231408031-ccb7be30-20f9-4606-9d34-a12df5ecce33.png)

view some issue,i try to set renderBuffer,but not work.
No matter how much I set it up, it doesn't work。like this
![image](https://user-images.githubusercontent.com/16437628/231617817-26c2e210-c3df-462f-b451-b816e1ffced2.png)

note: ol version is 6.4.3

thanks

**Comment by ahocevar** [comment]
The client-side renderBuffer won't help if the consumed tiles don't have a buffer that duplicates the tiles on neighbouring tiles. So this is not an OpenLayers issue, but a problem with the used tiles.

**Comment by younggis** [comment]
@ahocevar  
Thank you for your answer.

but I tried buffer the tile,it also not work. your mean is buffer tile in database and set renderbuffer in openlayers,Not a single one can be omitted?

**Comment by ahocevar** [comment]
I remember we had an issue in older versions of OpenLayers, so you may want to try the latest version. But if your tiles are correct, you don't need a `renderBuffer` on the client, unless your symbols are larger than the default (100 pixels).

**Comment by younggis** [comment]
@ahocevar 
I tried v7.3.0 、 v6.4.3 and v6.15.1
Perhaps I'm wrong, I'll try again. It would be even better if you could provide an example. Thank you.

**Comment by ahocevar** [comment]
This is covered by a rendering test. See https://github.com/openlayers/openlayers/blob/7b8964059e7b9a419d2b22585ef377c15f02b651/test/rendering/cases/layer-vectortile-renderbuffer/main.js.
