### ISSUE TITLE
Translate interaction with geographic coordinates changes geometry shape

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#14666]
**To Reproduce**
In https://codesandbox.io/s/translate-features-forked-dj5tfn select a state a translate it up or down.  Notice the shape changes with latitude.  That does not happen when not using geographic coordinates.  If using geographic coordinates with a polar view projection the results could be very unexpected. 

**Expected behavior**
As with Draw, Modify and Snap the interaction should work internally with view coordinates and transform any changes back to the user projection (and as with those interactions Circle geometry might need special attention).

**Comment by mike-000** [comment]
As expected Circle geometry (including Circle geometry nested in a GeometryCollection) does need a special case, in particular when the view projection is non-parallel.  This arises from the transform from user projection creating a non-standard Circle where radius is defined by both axes instead of `[cx + r, cy]`  and the current `setCenter` and `setRadius` methods not allowing for that.  The modify interaction is also affected by this as in https://codesandbox.io/s/modify-features-forked-k5euf0?file=/main.js where modifying the Circle center changes the radius in view projection and modifying the radius it is not aligned with the pointer.  Additionally the Draw interaction is returning a non-standard Circle geometry when the drawing is transformed to user projection.

**Comment by mike-000** [comment]
The original issue will need the problem with circles to be resolved as Circle transforms between non-parallel projections will produce results which do not comply to [cx + r, cy] and the setCenter() method does not allow for that.  Existing non-parallel tests using Mollweide did not catch that for Modify as the parallels are parallel.  A Circle in a view with radius in view units will transform to user projection (and vice versa) and look the same, however if the radius is changed when the geometry is not [cx + r, cy] compliant (even `circle.setRadius(circle.getRadius())`) it might no longer look the same.  My aim was to ensure all user facing Circle geometry was both [cx + r, cy] compliant and looked the same as it did in view projection (and when non [cx + r, cy] geometry was used internally setCenter() and getExtent() worked as expected).

**Comment by ahocevar** [comment]
@mike-000 With "original issue" I was referring to transforming a state, moving it north or south. If that's done entirely in view coordinates, I don't see how circle transforms come into play.

**Comment by ahocevar** [comment]
Better to do this with the `flatCoordinates` of the respective geometry, but in general yes. And I'd do the same for Circle geometries. If `transform()` does the right thing on a `Circle`, the radius will be adjusted properly.

**Comment by mike-000** [comment]
Is there a historic reason why Circle needs to override the SimpleGeometry translate method (which does use flat coordinates)?  Instead it uses `setCenter()` which currently does not allow for the possibility of a non [cx + r, cy] radius (which is going to happen when transforming between non-parallel projections).

**Comment by ahocevar** [comment]
@mike-000 That method was overridden as a result of an issue that you raised: #9415.
