### ISSUE TITLE
求助！当浏览器缩放比例不为100%时，使用ImageCanvas绘制的Image图层位置发生偏移

### ISSUE THREAD

**Issue by wenlc000** [openlayers/openlayers#14661]
代码如下：
![image](https://user-images.githubusercontent.com/49868062/231332835-bcb734cf-2926-4d4d-b60a-305415a2fa85.png)
![image](https://user-images.githubusercontent.com/49868062/231332925-36aac917-abc1-4ab5-a294-4e5d1815eb1e.png)

**Comment by younic1989** [comment]
Generally，pixelRatio is lost in somewhere. Check your code.

**Comment by wenlc000** [comment]
> 

Thank you, it has been resolved

**Comment by wenlc000** [comment]
.
