### ISSUE TITLE
Geometry Rendering Issue in CanvasImmediateRenderer with 200% Display Scaling on Windows

### ISSUE THREAD

**Issue by Rskut** [openlayers/openlayers#14688]
There is an issue with how geometries are rendered using CanvasImmediateRenderer, as they appear offset. This can be reproduced by setting a custom scaling in Windows 10 or 11 via System -> Display -> Custom scaling.

I have created a JSFiddle example: https://jsfiddle.net/vwmpn7eb/74/

I pass two styles to the layer: the first one renders the polygon using a custom rendering function (red), while the second style is rendered without the custom renderer function (green). I observe the same behavior in Safari on an iPhone. Am I missing something here?

**Comment by mike-000** [comment]
Use either

            const polygon = new ol.geom.Polygon(pxGeometry)

            const olContext = ol.render.toContext(state.context, {
              pixelRatio: 1
            });


or

            const polygon = new ol.geom.Polygon(pxGeometry)
            polygon.scale(1 / state.pixelRatio, undefined, [0, 0]);

            const olContext = ol.render.toContext(state.context);

**Comment by Rskut** [comment]
thx for your help!
