### ISSUE TITLE
Raster reprojection without tiled source?

### ISSUE THREAD

**Issue by jasontk19** [openlayers/openlayers#14705]
I am trying to reproject WMS image layers from EPSG:4326 into EPSG:3857.  My map view is configured to use 3857: 
```
  const mapObject = new Map({
    view: new View({
      projection: 'EPSG:3857',
      center: [0, 0],
      zoom: 0,
    }),
  });
```

and my layer source is configured to use 4326:
```
const params = new URLSearchParams({
      STYLES: style.name,
      FORMAT: 'image/png',
      TRANSPARENT: true,
      EXCEPTIONS: 'application/vnd.ogc.se_inimage',
      TIME: timeStep,
      DIM_reference_time: issuance,
      dataset,
      layers: layerName,
      ratio: 1,
    });

const source = new ImageWMS({
      projection: 'EPSG:4326',
      url: WMS_URL,
      params: Object.fromEntries(params),
      resolutions,
      imageLoadFunction(img, src) {
        if (getLoadedSteps().length !== allTimeSteps.length) {
          // eslint-disable-next-line no-param-reassign
          img.getImage().src = src;
        }
      },
    });
    const subLayer = new ImageLayer({
      source,
    });
```

The raster reprojection docs show an example using tiled layers, which in my experimentation works fine.  However, if I try to use an ImageLayer with an ImageWMS source, the WIDTH, HEIGHT, and BBOX params sent in the WMS request are wrong. As you can see the image requested is just 1x1 px and the BBOX coordinates are in 3857 format.

<img width="630" alt="Screen Shot 2023-04-25 at 10 02 10 AM" src="https://user-images.githubusercontent.com/1480000/234336059-32402475-cec7-4ba2-828e-e2dec412f7f3.png">

Please advise if I am going about this the wrong way or misunderstand how this should work.  Does raster reprojection only support tiled sources?  We cannot use tiled WMS for performance reasons.

**Comment by mike-000** [comment]
It works as expected here https://codesandbox.io/s/wms-image-forked-h1xspr?file=/main.js  Are you `resolutions` meaningful for EPSG:4326?

**Comment by jasontk19** [comment]
Thanks for the pointer Mike, the resolutions were definitely the issue.  

For some background and clarification:  Our WMS service handles meridian/antimeridian crossing requests that are made for 4326 but does not handle 3857 properly.  So my objective was to keep the map in 3857 while making the WMS requests in 4326 and then reprojecting them.

Now I am seeing something else that is curious.  The WMS request is being made with what looks like correct `WIDTH` and `HEIGHT` params now but, the `BBOX` extent doesn't extend past 210 degrees longitude when the viewport is showing out to 298.

<img width="1341" alt="Screen Shot 2023-04-25 at 2 48 27 PM" src="https://user-images.githubusercontent.com/1480000/234400528-8936435b-697a-4c9c-a43b-8b7dad55684f.png">
<img width="651" alt="Screen Shot 2023-04-25 at 2 48 42 PM" src="https://user-images.githubusercontent.com/1480000/234400540-b1b2a435-94af-46e4-bd76-39c6c4eb22ac.png">

If I set both the map and layer projections to EPSG:4326, this behaves as desired and the request BBOX more closely matches the viewport.  But, as mentioned previously, we would like the map to be in 3857.
<img width="1334" alt="Screen Shot 2023-04-25 at 2 51 50 PM" src="https://user-images.githubusercontent.com/1480000/234400902-faf0c18c-27c2-427f-9e38-f79d30952c15.png">
<img width="661" alt="Screen Shot 2023-04-25 at 2 51 58 PM" src="https://user-images.githubusercontent.com/1480000/234400905-cc313e35-11b5-4646-8fcf-48915685ed6c.png">

**Comment by jasontk19** [comment]
The code now:

```
const mapObject = new Map({
  view: new View({
    projection: 'EPSG:3857',
    center: [0, 0],
    zoom: 0,
    extent: [-40037508.34, -20048966.1, 40037508.34, 20048966.1],
  }),
});

const resolutions = [];
const maxResolution = 180;
for (let i = 0; i < 20; i++) {
  resolutions[i] = maxResolution / 2 ** i;
}
const params = getParams(layerTime);
const source = new ImageWMS({
  projection: 'EPSG:4326',
  url: WMS_URL,
  params: Object.fromEntries(params),
  resolutions,
  imageLoadFunction(img, src) {
    if (getLoadedSteps().length !== allTimeSteps.length) {
      // eslint-disable-next-line no-param-reassign
      img.getImage().src = src;
    }
  },
});
const subLayer = new ImageLayer({
  source,
});
```
