### ISSUE TITLE
With version 7, the WMS image gets blurry in many cases

### ISSUE THREAD

**Issue by sbrunner** [openlayers/openlayers#14718]
**Describe the bug**
If the ratio is not a round int, or map width or map height is not even, the image is blurry...

**To Reproduce**
1. Go to 'https://sbrunner.github.io/ngeo/ol7b.html'
3. See that the map is a little blurry

**Expected behavior**
The map is pixel perfect

**Comment by mike-000** [comment]
The image will be drawn at a fractional pixel position on the layer canvas, so some blurring is to be expected unless interpolation is disabled (which would have the same effect as offsetting the drawn image to an integer pixel position - pixel perfect but in slightly wrong position).

**Comment by sbrunner** [comment]
I understand that, but why don't create a WMS query do not have fractional pixel (I hope that a pull request will be accepted :-) )

**Comment by mike-000** [comment]
I think it is the calculation of the size that is at fault, it should be an integer value greater than the view size on both sides

e.g instead of

    const requestWidth = ceil(
      (this.ratio_ * getWidth(extent)) / imageResolution,
      DECIMALS
    );

use

    let requestWidth = ceil(
      getWidth(extent) / imageResolution,
      DECIMALS
    );
    requestWidth += 2 * ceil(
      ((this.ratio_ - 1) * requestWidth) / 2,
      DECIMALS
    );

and similarly for `requestHeight`.
That would also apply to other subclasses of ImageSource which have a `ratio` option.

**Comment by sbrunner** [comment]
Looks good, thanks, I will try with it :-)

**Comment by mike-000** [comment]
There could still be a problem if the map center is changed, but no image update is needed if it does not exceed the margin.  If it moves a fraction of a pixel the output would blur again.  I think a user drag is always a whole pixel, but a programmatic change or change of map size could do it, as can be seen with ImageCanvas where bright red and green pixels are blurred into dull yellow https://codesandbox.io/s/simple-forked-0g8ckv?file=/main.js

**Comment by sbrunner** [comment]
Effectively, but I don't think that we want to automatically query again the layer in this case...
