### ISSUE TITLE
Problem with GeoTIFF

### ISSUE THREAD

**Issue by aparzi** [openlayers/openlayers#14720]
Hi everyone, I working with a GeoTIFF file, when I load GeoTIFF layer on map I don't any errors but I get an empty page and browser crashing. Someone colud help me?

I used openlayers version 6.8.1

```
const source = new GeoTIFF({
                sources: [
                    {
                        url: 'https://openlayers.org/data/raster/no-overviews.tif'
                    },
                ],
            });
            const tileLayer = new WebGLTileLayer({
                source
            });
            tileLayer.setProperties({name: `tiff_layer_${tiffLayer._id}`});
            this.map.addLayer(tileLayer);
```

**Comment by aparzi** [comment]
@ahocevar can you help me, please?

**Comment by mike-000** [comment]
If you are using version 6.8.1 your map will need a view using projection EPSG:32618 (reprojection of GeoTIFF was not supported until version 7.2.0).  If you have no other layers you could set the view with `source.getView()` as in https://openlayers.org/en/latest/examples/cog.html

**Comment by mike-000** [comment]
You can keep OSM and reproject it to the same projection as the GeoTIFF  https://codesandbox.io/s/cog-forked-qkmi4d?file=/main.js  Any projections you might need (expect EPSG:3857 and EPSG:4326) must be defined with proj4.

If you upgrade to version 7.2.0 you will be able to keep the OSM in EPSG:3857 and reproject the GeoTIFF to that.

**Comment by aparzi** [comment]
@mike-000 So the geotiff must be 32618 and the other layers (vectorTileLayer) I have to reproject them, right?

p.s. I can't upgrade openlayers it would break too many implemented functionality.

**Comment by mike-000** [comment]
Vector Tiles cannot be reprojected in any version. If you must have vector tiles and GeoTIFF in different projections you will need to upgrade.

**Comment by aparzi** [comment]
Thanks @mike-000. I will update the version. In this case can I also draw on the geotiff layer keeping the OSM layer under the hood?

**Comment by aparzi** [comment]
@mike-000 I upgrade the version at 7.2.0 and this is code:

```
            const tileLayer = new TileLayer({
                source: new GeoTIFF({
                    normalize: false,
                    sources: [
                        {
                            url: 'https://openlayers.org/data/raster/no-overviews.tif'
                        }
                    ],
                    wrapX: true,
                }),
                zIndex: 999999
            });
            tileLayer.setProperties({name: `tiff_layer_${1234567}`});
            this.openlayersService.map.addLayer(tileLayer);
``` 

But not work, I keep seeing OSM layer.

**Comment by mike-000** [comment]
https://codesandbox.io/s/cog-forked-iv3km6?file=/main.js

or you could use `fromEPSGCode` as in 
https://deploy-preview-14692--ol-site.netlify.app/en/latest/examples/cog-projection.html

**Comment by aparzi** [comment]
Thanks @mike-000. 
Can I reproject any GeoTIFF to epsg:3857 projection?

**Comment by mike-000** [comment]
Yes, both those examples have EPSG:3857 view.

**Comment by aparzi** [comment]
Thanks, I close this issue. I solved.

Thanks so much.

**Comment by aparzi** [comment]
@mike-000 the geotiff works correctly with version 7.3.0, reprojecting it in EPSG:3857. But when I move on the map errors are logged, even if they seem irrelevant.

Can you help me?

**Comment by mike-000** [comment]
That error is from proj4.  It is probably caused by panning to a position where a transform between the projections is invalid.  Setting a layer extent on the GeoTIFF layer might fix it https://codesandbox.io/s/cog-forked-ekxktz?file=/main.js

**Comment by aparzi** [comment]
Ok @mike-000, thanks you so much.
Rendering tiff files works fine but I can't get it to work when the files are large.
For example, reprojecting a tiff file I get a file larger than a gigabyte, in this case the browser crashes.
Could you help me?

**Comment by Rskut** [comment]
You need a COG, https://openlayers.org/en/latest/examples/cog.html

**Comment by aparzi** [comment]
okay thanks. What is a COG? How it works?

**Comment by Rskut** [comment]
It`s basically a tiled Image and works like OpenStreetMap f.e.
You could use gdal (CLI) to generate the geotiff to a COG. This is what I do currently in our Application, when a user uploads a TIFF.

```
//convert to EPSG:3857
await procExec('gdalwarp', [
	'-t_srs',
	'EPSG:3857',
	'-r', 'near',
	'-of', 'GTiff',
	data.inputPath,
	outputPath3857,
]);

//convert to COG
await procExec('gdal_translate', [
	outputPath3857,
	cogOutputPath,
	'-co',
	'TILED=YES',
	'-co',
	'COPY_SRC_OVERVIEWS=NO',
	'-co',
	'COMPRESS=DEFLATE',
]);

//add overviews
await procExec('gdaladdo', [
	cogOutputPath,
]);
```

I had some issues with my custom stream function, not sure what`s you backend setup:

https://github.com/openlayers/openlayers/issues/13519

**Comment by aparzi** [comment]
@Rskut seems to work better already. overviews what would it be? At the moment to load the geotiff on the map I have to zoom a lot and it loads a few pixels at a time.
I used GDAL at the backend and create the GeoTiff with the generated path

**Comment by aparzi** [comment]
@Rskut maybe it depends on the connection which is slow to download the whole geotiff?

**Comment by Rskut** [comment]
GeoTIFF overviews are lower-resolution versions of the original GeoTIFF file, created to enable efficient and faster access to the data. 
COG is designed to optimize data access by allowing clients to download only the visible tiles within the current view extent, rather than the entire GeoTIFF file. 
Overviews facilitate this process by enabling the display of the entire GeoTIFF at lower resolutions. 
The 'gdaladdo' command is used to generate these overviews automatically, creating different levels of detail for various zoom levels 
Starting from a specific GDAL version (not sure which one), the 'gdaladdo' command automatically generates overviews with different levels of detail for various zoom levels. 
In earlier versions, you may need to manually specify the zoom levels for creating the overviews.

**Comment by aparzi** [comment]
@Rskut fantastic. I Solved.

Thank you so much.
