### ISSUE TITLE
Documentation of `style` short notation 

### ISSUE THREAD

**Issue by JakobMiksch** [openlayers/openlayers#14733]
**Is your feature request related to a problem? Please describe.**

Meanwhile it is possible to write styles in a short notation like this:

```
    style: {
        "fill-color": "yellow",
        "stroke-color": "black",
        "stroke-width": 4,
      },
```
However, I did not find any documentation about this. I just found it in some other code.

**Describe the solution you'd like**

It would be great to describe in the docs how to use this short style notation. Maybe this is documented already, but I have not found it yet. If so, please let me know.  Otherwise I can try to document it.

**Comment by tschaub** [comment]
The flat types are documented here: https://openlayers.org/en/latest/apidoc/module-ol_style_flat.html.  Then methods like [`layer.setStyle()`](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html#setStyle) link to that page.

But clearly this is not very discoverable.  I think the `setStyle` method could use a short example and could have a “see the flat style docs” link.  Then we could also have examples on the flat style page.

Any ideas or doc contributions you can make are welcome.

**Comment by JakobMiksch** [comment]
I added a minor example in the PR https://github.com/openlayers/openlayers/pull/14740

**Comment by tschaub** [comment]
Thanks for the documentation improvement.
