### ISSUE TITLE
Fixed icon size

### ISSUE THREAD

**Issue by aparzi** [openlayers/openlayers#14737]
Is it possible settings fixed icon size after specific zoom level? I would like that the icons not scaling

**Comment by aparzi** [comment]
@mike-000 I used a VectorTIleLayer

**Comment by mike-000** [comment]
> @mike-000 I used a VectorTIleLayer

Icons bigger than the tiles would not display correctly unless you use `declutter`.

**Comment by aparzi** [comment]
@mike-000 ok thanks.
