### ISSUE TITLE
Texts are not drawn when using placement:'line' and repeat

### ISSUE THREAD

**Issue by jaakko-solita** [openlayers/openlayers#14741]
**Describe the bug**
Texts are not drawn when using `placement:'line'` and `repeat`

**To Reproduce**
1. Go to https://codesandbox.io/s/line-arrows-forked-ileurz?file=/main.js
2. Draw a line, line gets drawn, but it has no Text labels 
3. Remove `placement:'line'` and `repeat`, text gets drawn

**Expected behavior**
Text labels should be drawn every 10 pixels

**Comment by mike-000** [comment]
Your labels are longer than 10 pixels.  If you increase the repeat interval to 20 you will see labels repeated

**Comment by jaakko-solita** [comment]
Thanks, with value 20 it works

May I suggest improvements. Now the user has to know the width of the labels beforehand for this feature to work properly which is often hard or impossible. One of these suggestions would improve the situation imo:

1) If two or more labels would overlap because `repeat` is too small, draw the first one only so at least one label gets drawn
2) `repeat` should define the gap between the labels

**Comment by mike-000** [comment]
> 1\. If two or more labels would overlap because `repeat` is too small, draw the first one only, so at least one label gets drawn

That can be achieved by specifying `overflow: true,` in the Text options in combination with `declutter: true` in the VectorLayer options.

> 2\. `repeat` should define the gap between the labels

`repeat` is intended to be equivalent to `symbol-spacing` in Mapbox style specifications.

**Comment by ahocevar** [comment]
> That can be achieved by specifying overflow: true, in the Text options in combination with declutter: true in the VectorLayer options.

`overflow: true` should be enough, regardless of the `declutter` option.

**Comment by mike-000** [comment]
> `overflow: true` should be enough, regardless of the `declutter` option.

Without the declutter option they will overlap and become difficult to read.
