### ISSUE TITLE
Can't render two tiff files almost the same

### ISSUE THREAD

**Issue by aborruso** [openlayers/openlayers#14757]
Hi,
I have created this codesandbox example, in which I render without any style a tiff:
https://codesandbox.io/s/cog-test-aspect-kriw38?file=/main.js

![image](https://github.com/openlayers/openlayers/assets/30607/bb3cb9d4-1206-49c5-b176-0aed62721e3b)

The tiff source is this https://andy-aws.s3.eu-north-1.amazonaws.com/input.tiff

If I replace it with a very similar tiff (https://andy-aws.s3.eu-north-1.amazonaws.com/sample_dnw_byte.tiff) I have no rendering.

I'm sure it's an error of mine, but I don't understand what it is.

Thank you

**Comment by mike-000** [comment]
There is a problem will the calculated tile grid - the tiles have a negative height.

**Comment by aborruso** [comment]
> There is a problem will the calculated tile grid - the tiles have a negative height.

Thank you very much @mike-000 

Could you help to understand?

If I extract metadata using gdalinfo I have this for the tiff that works

```
    "proj:transform":[
      342040.0,
      70.0,
      0.0,
      8521860.0,
      0.0,
      -70.0
    ]
```

and this one for the other

```
    "proj:transform":[
      365540.0,
      -70.0,
      0.0,
      8506680.0,
      0.0,
      70.0
    ]
```

Is it related to these parameters?

**Comment by aborruso** [comment]
> There is a problem will the calculated tile grid - the tiles have a negative height.

Using gdal 3.7, I have tried to retile it

```
gdal_translate -co TILED=YES sample_dnw_byte.tiff sample_dnw_byte_tiled.tiff
```

But I have the same NO result :(

https://andy-aws.s3.eu-north-1.amazonaws.com/sample_dnw_byte_tiled.tiff

**Comment by aborruso** [comment]
> There is a problem will the calculated tile grid - the tiles have a negative height.

Forcing the warp it seems to work.

```
gdalwarp -t_srs EPSG:32736 sample_dnw_byte.tiff sample_dnw_byte_warped.tiff
```

Thank you very much

**Comment by mike-000** [comment]
`source.getView().then(() => {console.log(source.getTileGrid())});`

**Comment by aborruso** [comment]
> source.getView().then(() => {console.log(source.getTileGrid())});

Thank you again, really useful
