### ISSUE TITLE
Duplicate labels on a Feature for VectorTiles (Text Style)

### ISSUE THREAD

**Issue by aparzi** [openlayers/openlayers#14762]
Hi,
is it possible to manage the duplication of the labels in the type of vector tile?

**Comment by elhamAm** [comment]
I am also experiencing duplicate labels when I try to have a VectorTileLayer using a VectorTileSource that brings in labels for polygons. My placement for the style of text label is line. Please help fix this. These labels are repeated along the tile borders but it should not look at the tiles but rather the polygons right? I also tried using the declutter attribute that was recommended in another issue.
