### ISSUE TITLE
What happened to ScaleLine geodesic: false? 

### ISSUE THREAD

**Issue by TheDevelolper** [openlayers/openlayers#14773]
**Describe the bug**
I'm looking to make the Scale line non geodesic, I can see that this was possible in prior versions of open layers but why was this removed? 

``` javascript
    new ol.ScaleLine({
          units: 'metric',
          bar: true,
          steps: 4,
          text: true,
          minWidth: 140,
          geodesic: false //<-- no longer an option
    })
```

Is there any way to achieve it with the modern version? I can't see any examples anywhere?

**Comment by mike-000** [comment]
It will be non-geodesic if there are no transforms available for the view projection, as in https://openlayers.org/en/latest/examples/wms-no-proj.html

**Comment by TheDevelolper** [comment]
Thank you for your prompt response. The more I look into this the more complicated it seems to get. Drawing interactions don't seem to be geodesic by default yet the map does. I can see how this makes sense in some cases. 

So I'm thinking aloud here. 

I need to do trandforms on my interactions, when I get measurements for things I need to also transform so that I can get accurate distances I think. 

The problem is that when I look at my calculated distances they never match up with the scale line.

**Comment by mike-000** [comment]
You are correct, interactions are not geodesic by default, for that you will need a custom geometry function such as in https://openlayers.org/en/main/examples/draw-and-modify-geodesic.html or https://codesandbox.io/s/draw-features-forked-1kv9m5?file=/main.js

The ScaleLine shows the scale at the view center (regardless of where it is located relative to the map div).  In most global projections there is a considerable difference in scale between the equator and poles, so comparing a feature with the ScaleLine when the view is centered much further north or south will not produce a valid comparison.

I presume you are using `ol.sphere.getDistance`.  That method requires geographic coordinates, so what view projection are you using?  If you are using an EPSG:4326 view the x and y axis will have different scales, the ScaleLine will show the mean of those, so comparisons in one dimension will not be valid.

**Comment by TheDevelolper** [comment]
Hi Mike, Thanks for confirming, I'd seen the examples using custom geometry functions. I have taken a step back however and thought about what we actually need for now. It turns out it doesn't need to be totally accurate. My lead dev also had some examples of measurements that seem to be good enough. 

He also pointed out that trying to match with the scale line is a bad strategy because we don't know exactly where the anchor point is. Depending on your zoom level those scales can be vastly different. 

So I think I have what I need for the moment but if I have other questions I'll raise them. I'm trying to use GPT where possible so that I'm not asking so many questions here. 

Thank you for all your help.
