### ISSUE TITLE
map.forEachFeatureAtPixel on MapboxVector layer in non-visible LayerGroup gives TypeError: frameState.declutterTree is null'

### ISSUE THREAD

**Issue by rdewit** [openlayers/openlayers#14776]
**Describe the bug**
Doing a `map.forEachFeatureAtPixel` on some MapboxVector layers that are part of a non-visible LayerGroup gives the following error: `TypeError: frameState.declutterTree is null`.

Somehow OL does not seem to respect the LayerGroup not being visible and attempts to query the underlying MapboxVector layer, resulting in the error.

**To Reproduce**
1. Go to https://codesandbox.io/s/select-hover-features-forked-p0ntqs?file=/main.js
1. Observe that hovering over the map shows 'Feature found' messages
1. Open the console and run `toggleVis()`, which will change the visibility of the LayerGroup that the MapboxVector layer is in. 
1. When hovering over the now-blank map, observe the error showing up.

**Expected behavior**
Ideally this error would not occur.

**Comment by mike-000** [comment]
I do not get the an error with the OL dev version https://codesandbox.io/s/select-hover-features-forked-nyco8n?file=/main.js so presumably already fixed by #14599

**Comment by rdewit** [comment]
Thanks, @mike-000. I can confirm that the dev version does not have the issue. Closing.
