### ISSUE TITLE
The animate function should not trigger a rotation if called multiple times with same properties

### ISSUE THREAD

**Issue by karussell** [openlayers/openlayers#14785]
**Describe the bug**

The animate function should not trigger a rotation if it is called with the exact same animate properties.

When I run the following animation multiple times:
```
view.animate({
  zoom: 7,
  center: fromLonLat([14.250512, 51.433444]),
  rotation: -6,
});
```
Everything is fine and the second animation does nothing as expected.

**To Reproduce**

Replace `rotation: -6` in the previous example with `rotation: -6.2` and **the animation restarts from 0 although the first animation should have set the rotation already to -6.2** and the second call should not trigger an animation. At least this was my understanding.

You can try it out via clicking "rotate clockwise" multiple times [here](https://codesandbox.io/s/animation-forked-hsmdz3?file=/main.js:1424-1568). And the "counterclockwise" button is the expected behaviour - i.e. it won't do anything if clicked on it multiple times.

**Expected behavior**

The second animation with the same rotation property should not rotate.

**Comment by mike-000** [comment]
It does not happen if `constrainRotation: false` is specified in the view options.  Unless `constrainRotation: false` is specified the view will snap to 0 with any user interaction or when an animation starts if it is within 5 degrees of 0.

**Comment by jahow** [comment]
This makes sense from a code point of view but it is still quite counter-intuitive. Maybe we could improve developer experience on this specific case?

**Comment by mike-000** [comment]
> This makes sense from a code point of view but it is still quite counter-intuitive. Maybe we could improve developer experience on this specific case?

It is not specific to this case.  The same happens if an animation exceeds other constraints, such as view extent.  The view remains in that state until a user interaction or another animation is triggered before snapping back to comply with the constraint.  The only exception seems to be `multiWorld: false,` which is enforced during animations (and also has no `smooth` option).
