### ISSUE TITLE
COG GeoTIFF: CustomAggregateError in Firefox

### ISSUE THREAD

**Issue by aborruso** [openlayers/openlayers#14817]
Hi,
I have built a sample page starting from the code below. 
A live URL is here https://andybandy.it/progetti/tmp/cog-nogeo-map/

It works in Chrome, but I have these errors in firefox console:

```
AggregateError: Request failed
    CustomAggregateError https://andybandy.it/progetti/tmp/cog-nogeo-map/assets/index.6486f5bb.js:5865
    fetch https://andybandy.it/progetti/tmp/cog-nogeo-map/assets/index.6486f5bb.js:5962
index.6486f5bb.js:1341:11
    error https://andybandy.it/progetti/tmp/cog-nogeo-map/assets/index.6486f5bb.js:1341
    GeoTIFFSource https://andybandy.it/progetti/tmp/cog-nogeo-map/assets/index.6486f5bb.js:7056
```

If I run it locally using `npm start` and `VITE v3.2.7`, it works both in Chrome and Firefox.

Is it something that could depend on the settings of the server that makes the TIFF available, or is my JavaScript code incorrect?

Thank you

```javascript
import GeoTIFF from "ol/source/GeoTIFF.js";
import Map from "ol/Map.js";
import TileLayer from "ol/layer/WebGLTile.js";

const urlParams = new URLSearchParams(window.location.search);
const mapParam = urlParams.get('map') || '10_1155';

if (!mapParam) {
  throw new Error('Missing "map" parameter in URL');
}

const source = new GeoTIFF({
  convertToRGB: true,
  sources: [
    {
      //url: `./tif/${mapParam}.tif`
      url: "./tif/10_1155.tif"
      //url: "https://andy-aws.s3.eu-north-1.amazonaws.com/10_1155.tif"
    }
  ]
});

const map = new Map({
  target: "map",
  layers: [
    new TileLayer({
      source: source
    })
  ],
  view: source.getView()
});
```

**Comment by MoonE** [comment]
Looks like this server ignores the [`Range`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) header when the `accept-encoding` header includes `gzip`.

This seems to be the relevant issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1467010

Could it be a problem with the nginx version? Maybe look into upgrading it.

**Comment by aborruso** [comment]
Thank you very much @MoonE.

If I wanted to ask the server manager to change the settings, what should I ask him?
Is there a page where I can read the specs a server should have, to properly manage a call to a COG file?

**Comment by MoonE** [comment]
Other than respecting the Range header there is nothing special need to make your COG file work.
The library will send a Range request for the  first 65537 bytes of the file. This should contain all the meta information. After that more range requests are made to the data that is currently needed.

You'd want the server to respond to a Range request like this:
```sh
curl 'https://andybandy.it/progetti/tmp/cog-nogeo-map/tif/10_1155.tif' \
  -H 'accept:*/*' \
  -H 'range:bytes=0-1' \
  -H 'Accept-Encoding: gzip, deflate, br, identity'
```
... with just the first two byte of the file.

As a random example: This server will respond with the requested range.
```sh
curl 'https://people.math.sc.edu/Burkardt/data/tif/bali.tif' \
  -H 'accept:*/*' \
  -H 'range:bytes=0-1' \
  -H 'Accept-Encoding: gzip, deflate, br, identity'
```

Admittedly I do not really know the  details of  why it does not work with your server or why  firefox sends a different header than chrome.

**Comment by aborruso** [comment]
just having a server capable of responding correctly and everything works
