### ISSUE TITLE
the map does not response to the mouseover on old browsers like safari v11

### ISSUE THREAD

**Issue by scil** [openlayers/openlayers#14812]
**Describe the bug**
when the mouse moves over the map, the map does not response.

**Comment by scil** [comment]
because map uses pointer events which not supported by old browsers, https://developer.mozilla.org/en-US/docs/Web/API/Element/pointermove_event#browser_compatibility


solution: 
just use https://github.com/jquery-archive/PEP, and I do not add ` touch-action="none"`  which seems being required by PEP.

**Comment by mprins** [comment]
elm-pep dependency was removed with #11173 (on Jun 11, 2020)
