### ISSUE TITLE
Error in drawing features on WebGLPointsLayer layer

### ISSUE THREAD

**Issue by zhuzhye** [openlayers/openlayers#14835]
I encountered an error while using WebGLPointsLayer to draw elements, and I also encountered this issue when viewing the official example. All newly downloaded software packages have this issue. May I ask if there is an error in the code

![image](https://github.com/openlayers/openlayers/assets/60699706/e033a4f0-a65c-460b-bbde-080708f782df)
https://openlayers.org/en/latest/examples/icon-sprite-webgl.html

**Comment by mike-000** [comment]
A bug was introduced in the last release which is fixed in the dev version https://openlayers.org/en/main/examples/icon-sprite-webgl.html

**Comment by MoonE** [comment]
You have to  provide a type-hint for now, see which fixed this example: #14791

**Comment by MoonE** [comment]
Fixed by #15121
