### ISSUE TITLE
MultiPoint geometry rendering in WebGL

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#14850]
**Describe the bug**
As observed in https://github.com/openlayers/openlayers/issues/14849#issuecomment-1597871286 some MultiPoint geometries do not render correctly in a WebGL vector layer, with points having one of the coordinates at or near zero.

**To Reproduce**
https://codesandbox.io/s/webgl-vector-layer-forked-y46fct?file=/main.js

**Expected behavior**
Render as expected (i.e. in  the same way as collection of Point geometries derived from the MultiPoint).

**Comment by jahow** [comment]
Thanks for the catch @mike-000, I'll look into it.
