### ISSUE TITLE
Timezone should be added or renamed: "Europe/Kyiv"

### ISSUE THREAD

**Issue by alexkleinwaechter** [openlayers/openlayers#14851]
Hi,
according to this stackoverflow post the timezone name changed in 08/2022 

from:
"Europe/Kiev"

to:
"Europe/Kyiv"

With the .Net GeoTimeZoneService I get the new variant and can't convert it with your tool.

Best!
Alex

**Comment by mprins** [comment]
There seems to be no place in the OpenLayers code that holds that string. Please point out where the change should be made if I'm mistaken

**Comment by alexkleinwaechter** [comment]
Oh Sorry!
I posted the issue to the wrong project. I’m a true master of my browser
tabs.

Please delete!
A very small Alex.

Mark Prins ***@***.***> schrieb am Di. 20. Juni 2023 um 18:03:
