### ISSUE TITLE
Loading geotiff (COG) layer, when wrapX is true, the nodata value is unexpectedly rendered

### ISSUE THREAD

**Issue by xmsuperman** [openlayers/openlayers#14871]
**Describe the bug**
When the geotif (COG) layer is loaded, wrapX: true is enabled in the source, and nodata is correctly set. When the style is set, the nodata value becomes 0 and is rendered。

single channel

The range of tif values
-300 ~ 300

Nodata Value:
-999

**To Reproduce**
`let extent4326 = [-180, -90, 180, 90];
        let projection = new Projection({
            code: 'EPSG:4326',
            extent: extent4326,
            worldExtent: extent4326,
            global: true
        });

let source = new GeoTIFF({
            sources:
                [
                    {
                        url: 'http://xxxx.cog.TIFF',
                        max: 300,
                        min: -300,
                        bands: ["1"],
                        nodata: -999,
                    },
                ],
            normalize: false,
            interpolate: false,
            wrapX: true,
        });

let geotifLayer = new WebGLTileLayer({
            source: source,
            style: {
                color: [
                    "interpolate",
                    ["linear"],
                    ["band", 1],                    
                    233,
                    [0,0,128,1],
                    236,
                    [0,0,164,1],
                    239,
                    [0,0,205,1],
                    242,
                    [0,0,246,1],
                    245,
                    [0,12,255,1],
                    248,
                    [0,48,255,1],
                    251,
                    [0,80,255,1],
                    254,
                    [0,116,255,1],
                    257,
                    [0,152,255,1],
                    260,
                    [0,188,255,1],
                    263,
                    [0,224,251,1],
                    266,
                    [25,255,222,1],
                    269,
                    [51, 255,196,1],
                    272,
                    [80,255,167,1],
                    275,
                    [109,255,138,1],
                    278,
                    [138,255,109,1],
                    281,
                    [167,255,80,1],
                    284,
                    [196,255,51,1],                    
                ],
            }
        });

this.map = new Map({
            target: 'map',
            layers: [
                new WebGLTileLayer({
                    source: new GeoTIFF({
                        sources:
                            [
                                {
                                    url: '/worldimage.tiff',                                                                       
                                },
                            ],
                        //normalize: false,
                        interpolate: false,     
                        wrapX: true,                   
                    })
                }),               
                geotifLayer,
            ],                    
            view: new View({                
                projection: projection,
                //projection: "EPSG:4326",
                center: [0, 0],
                zoom: 3,               
            }),
        })`

**Expected behavior**
The nodata value can be correctly ignored

This issue can be reproduced in @Openlayers v7.4.0

**Comment by mike-000** [comment]
nodata adds an alpha band to the output, you need to use `['band', 2]` as alpha in the style.

**Comment by xmsuperman** [comment]
I don't quite understand what you mean. Could you please provide me with detailed guidance? Do I need to process data or something?

**Comment by mike-000** [comment]
See also #14593   Also note the non-standard meaning of `wrapX: false` in GeoTIFF #13952 -  although `wrapX: true` works as expected if the source is reprojected.

**Comment by xmsuperman** [comment]
Thank you very much，my problem has been solved!
