### ISSUE TITLE
In ol/style/Icon,Can the scale attribute be set with two parameters to specify the scaling of width and height

### ISSUE THREAD

**Issue by Lazydd** [openlayers/openlayers#14896]
In ol/style/Icon,Can the scale attribute be set with two parameters to specify the scaling of width and height,Currently, there is only one parameter

**Comment by ahocevar** [comment]
The `scale` parameter already accepts either a `number` or a `Size`, which is `[scaleX, scaleY]` for different scales for width and height.

**Comment by Lazydd** [comment]
> 该`scale`参数已经接受 a`number`或 a `Size`，它们`[scaleX, scaleY]`用于不同的宽度和高度比例。

Sorry, I tried yesterday but I can't do it. Today I can do it again, lol!
