### ISSUE TITLE
Dynamic background color change doesn't work

### ISSUE THREAD

**Issue by kikuchan** [openlayers/openlayers#14894]
**Describe the bug**
Dynamic background color change doesn't work as expected for vector layers.

**To Reproduce**
1. Run the following code
2. Zoom in/out
3. You'll see the background color is not changed as expected

```js
import './style.css';
import {Map, View} from 'ol';
import Graticule from 'ol/layer/Graticule';

function background(resolution) {
  const color = resolution < 10000 ? '#88f' : '#f88';
  console.log(resolution, color);
  return color;
}

const map = new Map({
  target: 'map',
  layers: [
    new Graticule({
      background,
    })
  ],
  view: new View({
    center: [0, 0],
    zoom: 0,
  })
});
```

**Expected behavior**
The background color is changed when the zoom level (resolution) is changed.

**Comment by guisaliba** [comment]
Had this same issue too, thank you for addressing it.
