### ISSUE TITLE
ol.layer.Layer maxZoom property causes zooming bug on android devices

### ISSUE THREAD

**Issue by Apkovy** [openlayers/openlayers#14893]
Setting property maxZoom on ol.layer.Layer causes zooming the whole page instead of the map itself on most of the android devices.

1. Go to https://openlayers.org/en/latest/examples/layer-zoom-limits.html.
2. Pinch zoom over threshold zoom level 14.
3. From this point, instead of the map the whole page is zoomed and the view is broken.

There is no problem on iPhones and some android devices. We observed that the bug can be reproduced on approximately 80% of the android devices at least on google chrome and samsung internet browser.

Problem: Samsung S21 Ultra 5G, Samsung Note 20 Ultra, Samsung Galaxy Note 9
No problem: Samsung s10e, Xiaomi Redmin Note 9 pro

I am using the library version 7.1.0, but the problem is also in the newest version. I think, that I saw this issue even years ago on one android phone. It really might be a very old problem, although I can't imagine it has been unobserved and unresolved till now.

**Comment by mike-000** [comment]
See #13495

**Comment by Apkovy** [comment]
1. There is no need to place one finger on some ui control for this to happen. It happens even when pinch zooming on a blank map only.

2. There is direct connection between layer's "maxZoom" or "minZoom" property and this behaviour. This problem does not occur on a map with layers without these properties set. And even on the maps with such a layers active, it only happens when you pinch zoom over this threshold zoom. On the example I provided, it is zoom 14. Try to reach zoom 14 and get over it. Then this happens.

**Comment by mike-000** [comment]
A different cause in your case (a change of elements as the layer visibility changes) but the same fix should work https://deploy-preview-14906--ol-site.netlify.app/en/latest/examples/layer-zoom-limits.html
