### ISSUE TITLE
The arrow lines between multiple points should not overlap

### ISSUE THREAD

**Issue by wangshunshun** [openlayers/openlayers#14899]
How to set the arrow lines between multiple points so that they do not overlap and have gaps between them.

![image](https://github.com/openlayers/openlayers/assets/26266527/45073419-449c-4520-b401-850ca2596e10)

**Comment by MoonE** [comment]
You can use lineDash and lineDashOffset for this:
```js
new Stroke({
  color: 'red',
  lineDash: [99999, 10],
  lineDashOffset: -10,
})
```
This line-dash pattern will alternate with 99999 px of line and 10px of gap. By using and offset of -10 px, the line will  start with the 10 px gap, then draw a continuous line.

If you need a gap on both ends you could draw two lines, each with a line-dash style, that meet at a midpoint between  the icons it connects.

Here is a working example: 
https://codesandbox.io/s/connecting-line-with-gap-3ygjpc?file=/main.js

**Comment by wangshunshun** [comment]
Okay, thank you
