### ISSUE TITLE
When the opacity of the feature is set to 0, its click event will not be triggered

### ISSUE THREAD

**Issue by Lazydd** [openlayers/openlayers#14924]
This is an example：https://codesandbox.io/s/overlay-forked-hhtfm6?file=/main.js, And when the map is moving, the feature will no longer flash. How can I solve this problem.

**Comment by tanhh326** [comment]
https://openlayers.org/en/latest/examples/?q=animation

**Comment by Lazydd** [comment]
> https://openlayers.org/en/latest/examples/?q=animation

不太行，写了半天没写出来

**Comment by mike-000** [comment]
To update the style while panning use `updateWhileInteracting: true` in the layer options.
To hit detect an invisible feature you will need to add a Circle or RegularShape with transparent fill to the style.
https://codesandbox.io/s/overlay-forked-twymhj?file=/main.js

**Comment by Lazydd** [comment]
> To update the style while panning use `updateWhileInteracting: true` in the layer options. To hit detect an invisible feature you will need to add a Circle or RegularShape with transparent fill to the style. https://codesandbox.io/s/overlay-forked-twymhj?file=/main.js

Thanks

**Comment by mike-000** [comment]
> can you add an option to control the hidden things would also work

@ahocevar maybe that should be the default?  It seems inconsistent that a zero opacity icon can cause a visible icon to be decluttered, but it is not hit detected.  Does opacity really need to be included in hit detection instructions?  Does anyone use opacity to avoid hit detection?  How it is different to transparency or the intervals between line dash which are hit detected?  If any change is made text and image behaviour should be consistent.

**Comment by ahocevar** [comment]
@mike-000 Yes, to be consistent with what was decided and implemented for polygons in #7750, an `Icon` style with `opacity: 0` should be hit detected.

For `Text` styles, the situation is a bit different because `Text` does not have an opacity. Instead, `Text` has `Fill` and `Stroke` that can have a color with an alpha of zero. I honestly don't know if that is already handled the same way as wehen rendering polygons or not.

**Comment by mike-000** [comment]
#9986 and #10007 extended #7750 to Circle geometry, Circle style and RegularShape but not to text fill.  Transparent fill in text is current not hit detected, and because text fill defaults if undefined it is necessary to specify `fill: null` to use no fill (which is not documented in the API).
