### ISSUE TITLE
KeyboardPan and KeyboardZoom/mousewheelzoom not working with Custom elements

### ISSUE THREAD

**Issue by BHDBvde** [openlayers/openlayers#14931]
**Describe the bug**
When using custom-elements the MouseWheelzoom is working out of the box. However the keyboardZoom and keyBoardPan are not working. If you set the tabindex then the KeyBoard options are working, but then the MouseWheelZoom is not working.
They should both work is what I think.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/es2015-custom-element.html
2. The mousewheelZoom is working, keyBoardZoom and pan are not working
3. Set the tabindex see:
4. In main.js, you have to programmatically set the tabIndex:

    div.style.width = '100%';
    div.style.height = '100%';
    div.tabIndex = '0'; // add tabIndex here
See https://codesandbox.io/s/es2015-custom-element-forked-h656nl?file=/main.js for a working example with this change.
5. The keyboardZoom and pan are working, the mousewheelZoom is not working

**Expected behavior**
That both the MouseWheelZoom and the KeyBoardZoom and Pan are working

**Comment by ahocevar** [comment]
Your reproduction case is not the appropriate way to add the `tabIndex`. Instead, in main.js, you have to programmatically set the `tabIndex`:
```js
    div.style.width = '100%';
    div.style.height = '100%';
    div.tabIndex = '0'; // add tabIndex here
```
See https://codesandbox.io/s/es2015-custom-element-forked-h656nl?file=/main.js for a working example with this change.

**Comment by BHDBvde** [comment]
I changed the reproduction part.

**Comment by ahocevar** [comment]
For me everything works as expected with the change I suggested. Please try if it works for you too.

**Comment by BHDBvde** [comment]
No in this example you can not use the mouseWheelZoom and Pan. I want that the KeyBoard and the mouse Zoom and Pan work.

**Comment by ahocevar** [comment]
Ok, I can reproduce. Thanks for the bug report.

**Comment by BHDBvde** [comment]
Does this (https://github.com/openlayers/openlayers/pull/16094) also fix this?

**Comment by ahocevar** [comment]
@BHDBvde Yes it should. See the https://openlayers.org/en/latest/examples/es2015-custom-element-a11y.html example for usage (i.e. place the `tabindex` on the custom element).

**Comment by BHDBvde** [comment]
Thanks that example seems to work.
