### ISSUE TITLE
How can I use the renderer method to customize rendering and add text annotations

### ISSUE THREAD

**Issue by tanhh326** [openlayers/openlayers#14955]
https://codesandbox.io/s/style-renderer-forked-kkc7lq?file=/main.js
![image](https://github.com/openlayers/openlayers/assets/82007768/bef55e30-b52f-4f8c-92ce-e193d3f06370)

> I do this and there is a difference

**Comment by mike-000** [comment]
A style array with the custom style drawing the polygon and a standard text style for the labels will work https://codesandbox.io/s/style-renderer-forked-fxrd88?file=/main.js

**Comment by tanhh326** [comment]
It worked. Thank you.
