### ISSUE TITLE
Update Base.getZIndex() docstring and type definition to include undefined for unmanaged layers

### ISSUE THREAD

**Issue by oshawa-connection** [openlayers/openlayers#14967]
**Describe the bug**
When calling getZIndex on "unmanaged" layers i.e. those that do not explicitly set a zIndex, the method can return undefined (which makes sense).
However, the docstring and the type definition state that this it should return 0 in this case. Is this a bug or have I misunderstood something? I'm happy to submit a PR if needed!.

https://github.com/openlayers/openlayers/blob/0b90e813b8800cf8902b15edeebbdf48704d1a64/src/ol/layer/Base.js#L286

I'm using ol v7.4.0 if it makes a difference!

**Comment by ahocevar** [comment]
@oshawa-connection We don't have tsc configured to use `strictNullChecks` yet, so `undefined` is an allowed value for the type `number`. But we are in the process of preparing for `strictNullChecks`, so a pull request to change the type of the return value to `{number=}` would be appreciated.
