### ISSUE TITLE
Docs: BaseVector.getFeatures shows incorrect return value

### ISSUE THREAD

**Issue by m-mohr** [openlayers/openlayers#14968]
The documentation has a small quirk:

![grafik](https://github.com/openlayers/openlayers/assets/8262166/bd8d7795-883b-41f3-acb3-1322305fd165)

It shows `PromiseFeatureLike>>` instead of `Promise<Array<FeatureLike>>`

**Comment by tanhh326** [comment]
This problem is caused by not escaping the nested `<>` in the tmpl template, please give me a chance to troubleshoot if it's a `jsdoc` problem or something else
