### ISSUE TITLE
Selected Layer refresh linkage lost

### ISSUE THREAD

**Issue by MannyKSoSo** [openlayers/openlayers#14965]
When I attempt to use a selected layer and set its style, I need the layer to refresh periodically as to pull new data in, but when the layer refreshes, I end up losing that link to the original feature and would have to re-click/re-select the feature for the style to come back/be selected again.

You can see how that works with this link: [codesandbox example](https://codesandbox.io/s/select-layer-refresh-vrm2v2?file=/main.js)

Select a layer then click the refresh button and you will see the style will get lost (as its technically a new feature). I have attempted to set the feature's id manually after its ingested (which might be a nice feature for the format option to have the ability to select a property for the id, but not a biggie), which did not end up re-selecting the feature.

What I would like to be able to do is if the layer gets selected and while it's still in that selection state and the layer gets refreshed that they get relinked correctly. Not sure if this is 100% possible or if there is something I can do to better/change to get this kind of seamless reselection.

**Comment by mike-000** [comment]
You can add new features back to the selected features collection after the refresh has completed based on the original feature id, but it does fire fire a selected event.  You can either let the interaction style the features, otherwise you will need to set the selected style yourself as you add them to the collection.  https://codesandbox.io/s/select-layer-refresh-forked-2kv9p6

**Comment by MannyKSoSo** [comment]
I can confirm that this does work and does support what I was looking for. I needed to make a few modifications to the actual reselection process as I had values that weren't being reload (or weren't part of that layer), but I managed to get them correctly reapply to the select.
