### ISSUE TITLE
Overzooming vector tiles without data loading from server

### ISSUE THREAD

**Issue by MarcelGeo** [openlayers/openlayers#14987]
**Is your feature request related to a problem? Please describe.**
If vector tile layer i going overzoomed without proper tiles on server (max zoom on tile server is 14), data are loading with 404 error codes, but layer can be visible in renderMode: 'vector' without problems. 
 

**Describe the solution you'd like**
Allow loading data for vector tiles until specific zoom level ( example: 14). But visivibility of layer will be until maxZoom: (example 19). Vector tiles can be overzzomed without loading data from tile server with zoom constrain.

```
new ol.source.VectorTile({
  maxDataLoadingZoom: boolean | undefined
})
```

**Comment by M393** [comment]
This should be possible by setting maxZoom of 14 on the VectorTile source and maxZoom of 19 on the VectorTile layer.

**Comment by MarcelGeo** [comment]
Ok. After research, it is possible to use custom tile grid with proper zoomin options:

```
const tileGrid = createXYZ({
        extent: getProjection('EPSG:3857').getExtent(),
        tileSize: 512,
        maxZoom: 14
})
```

For me, you can close this issue. Thanks :) @M393

**Comment by MarcelGeo** [comment]
Thanks. Closing.
