### ISSUE TITLE
Vector tiles - symbols not updated

### ISSUE THREAD

**Issue by oyvindi** [openlayers/openlayers#14993]
I got a case using vector tiles, via `ol-mapbox-style`. The reason for using `ol-mapbox-style` instead of the OL "native" is that the tiles uses data from multiple sources, hence divided into several layers (`using apply()` ). These are then added to a `LayerGroup`.

This is a single page React application, with multiple sections. There are two different map styles (let's call them `style1` and `style2`), where I use two different versions of the mapbox style doc when initializing `ol-mapbox-style` with `apply()`. That means, when switching to another page (or section), the current map is destroyed, and a new instance is created with it's layers etc.

When switching from one instance to the next, the vector tiles are rendered with the same colors as the previous instance. When zooming/panning outside the "home"-extent, some of the tiles gets rendered with the correct colors. When reloading the page and section, everything looks fine.

I tried the following to no avail:
- renamed all the sources in `style2`
- calling dispose() on every layer when deleting map
- calling refresh() in the source (tiles are reloaded, but no effect on render)

I can only speculate what's happening, perhaps there is some cache somewhere that needs to be cleared. Also, I am not 100% sure if this is caused by `OL` or `ol-mapbox-style`.

Versions:
`ol - 7.4.0`
`ol-mapbox-style : 10.7.0`

**Comment by ahocevar** [comment]
We're going to handle this in https://github.com/openlayers/ol-mapbox-style/issues/959, closing here.
