### ISSUE TITLE
Type incompatibility between CanvasVectorLayerRenderer and LayerRenderer<any>

### ISSUE THREAD

**Issue by BendixP** [openlayers/openlayers#15004]
**Describe the bug**
When updating ol from 7.4.0 to 7.5.0 we get the following type error:
![image](https://github.com/openlayers/openlayers/assets/38940823/678d1462-2df7-4bcc-acbc-4d62d75e59bc)
Apparently in one case the method renderFrame() is allowed to return null and in the other not.

**Expected behavior**
The code should compile without errors as in 7.4.0

**Comment by MoonE** [comment]
The possible `null` return was missing, and added to VectorLayer with 7.5.0, but it is now missing in the parent class.
