### ISSUE TITLE
WebGL styling issue after updating from v7.4.0 to v7.5.*

### ISSUE THREAD

**Issue by jeroenvheel** [openlayers/openlayers#15025]
**Describe the bug**
After upgrading from v7.4.0 to v7.5.* the styling we where using is changed.
The size of the symbols are not working correctly and all layers are semi transparent.

The icon on the Vector layer is still working as expected.

The code we use to style the layer.
```ts
style: {
  symbol: {
    symbolType: 'image',
    src: '..some source path..',
    size: ['interpolate', ['exponential', 2.4], ['zoom'], 2, 1, 26, 60],
    rotateWithView: false,
    offset: [0, 0]
  }
}
```

**v7.5.1 behavior**
![image](https://github.com/openlayers/openlayers/assets/228655/065d02f8-8e10-4562-adaf-1cafe70254f5)

**Expected behavior**
![image](https://github.com/openlayers/openlayers/assets/228655/2cad8cb3-d704-46a0-a8a3-f2f2d3e8f12f)

**Comment by mike-000** [comment]
See #14837.  The change did not get added to the upgrade notes.

**Comment by jahow** [comment]
That's right, this was overlooked in the mentioned PR, I'll add it to the upgrade notes.

**Comment by jeroenvheel** [comment]
Made some changes to the size and its working better.

The next question i have is why is the image transparent ?
the color property is required?
I have set it to white to make sure the colors are normal.

**Comment by jahow** [comment]
Yes, you have to specify a color to have the points show up.

**Comment by jeroenvheel** [comment]
Thanks for the help!!
