### ISSUE TITLE
Fix type definition of placeholderTiles options of BingMaps source

### ISSUE THREAD

**Issue by adube** [openlayers/openlayers#15026]
**Describe the bug**
A `placeholderTiles` options has been recently introduced in #14832

Its type definition is `boolean`, i.e. it is typed as a required parameter to set among the options.  However, it seems showcased as an "optional option", i.e. the code and example assume that it can be left undefined. That's all fine.

When used in a TypeScript project, since the property is not optional, we are force to set it, which does not allow to let the default behaviour of leaving it undefined to be a possible option.

**To Reproduce**
It is a minor technical issue, and it is not really reproducible.

**Expected behavior**
It should be possible to leave the option undefined.

**Comment by adube** [comment]
I'll provide a PR for that.

**Comment by mike-000** [comment]
> left undefined, which is the same as setting it to `false`

for Roads and Aerial with Labels it is, but for Aerial and Ordnance Survey it is the same as setting it to `true`.

**Comment by adube** [comment]
I've adjusted the PR and the description of this issue to reflect this.  Thanks for pointing it out.
