### ISSUE TITLE
ImageWrapper page is out of data in `main` API

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#15023]
**Describe the bug**
In the code ImageWrapper extends EventTarget, it was changed by #14945, and the `getImage()` method was also changed to return `ImageLike`.  But this is not reflected in https://openlayers.org/en/main/apidoc/module-ol_Image-ImageWrapper.html  The page title in the browser tab shows v7.5.1-dev.  The same on multiple browsers so not a cache issue.

Clicking on the `ol/Image` link at the top of the page does go to an updated page with new functions https://openlayers.org/en/main/apidoc/module-ol_Image.html  The page title in the browser tab shows v8.0.0-dev.

**Expected behavior**
All pages should be v8.0.0-dev.

**Comment by MoonE** [comment]
The website is from https://github.com/openlayers/openlayers.github.io/tree/main/dist/en/main
Apparently there are three old files there.
The Stamen source no longer exists and should has been removed.
> $ grep '7\\.5\\.1' -r dist/en/main
```
./apidoc/module-ol_source_Stamen.html:    <title>OpenLayers v7.5.1-dev API - Module: ol/source/Stamen</title>
./apidoc/module-ol_source_Stamen.html:            This documentation is for OpenLayers v<span id="package-version">7.5.1-dev</span>. The <a id="latest-link" href="#" class="alert-link">latest</a> is v<span id="latest-version"></span>.
./apidoc/module-ol_source_Stamen-Stamen.html:    <title>OpenLayers v7.5.1-dev API - Class: Stamen</title>
./apidoc/module-ol_source_Stamen-Stamen.html:            This documentation is for OpenLayers v<span id="package-version"
7.5.1-dev</span>. The <a id="latest-link" href="#" class="alert-link">latest</a> is v<span id="latest-version"></span>.
./apidoc/module-ol_Image-ImageWrapper.html:    <title>OpenLayers v7.5.1-dev API - Class: ImageWrapper</title>
./apidoc/module-ol_Image-ImageWrapper.html:            This documentation is for OpenLayers v<span id="package-version">7.5.1-dev</span>. The <a id="latest-link" href="#" class="alert-link">latest</a> is v<span id="latest-version"></span>.
```

**Comment by ahocevar** [comment]
Thanks for digging into this, @MoonE, and thanks for reporting it, @mike-000. I removed these files.

**Comment by MoonE** [comment]
@ahocevar Looks like there are more old files there:

```sh
du -sh dist/en/{v7.5.1,main}
```
>66M	dist/en/v7.5.1
80M	dist/en/main

```sh
diff -rq dist/en/{v7.5.1,main} | sort | grep '^Only'
```
>Only in dist/en/main/apidoc/scripts: bootstrap.bundle.min.js
Only in dist/en/main/apidoc/scripts: jquery.min.js
Only in dist/en/main/apidoc/scripts: jquery.min.map
Only in dist/en/main/apidoc/styles: bootstrap.min.css
Only in dist/en/main/apidoc/styles: site.css
Only in dist/en/main/apidoc: logo-70x70.png
Only in dist/en/main/apidoc: module-ol_PluggableMap-PluggableMap.html
Only in dist/en/main/apidoc: module-ol_PluggableMap.html
Only in dist/en/main/apidoc: module-ol_control.html
Only in dist/en/main/apidoc: module-ol_interaction.html
Only in dist/en/main/apidoc: module-ol_layer_VectorTileRenderType.html
Only in dist/en/main/apidoc: module-ol_source_StadiaMaps-StadiaMaps.html
Only in dist/en/main/apidoc: module-ol_source_StadiaMaps.html
Only in dist/en/main/apidoc: module-ol_source_arcgisRest.html
Only in dist/en/main/apidoc: module-ol_source_mapguide.html
Only in dist/en/main/apidoc: module-ol_source_static.html
Only in dist/en/main/examples/data: fish.png
Only in dist/en/main/examples/resources: layout.css
Only in dist/en/main/examples/resources: logo-70x70.png
Only in dist/en/main/examples/resources: map-background.jpg
Only in dist/en/main/examples/resources: prism
Only in dist/en/main/examples: 1405.js
Only in dist/en/main/examples: 1405.js.map
Only in dist/en/main/examples: 1475.js
Only in dist/en/main/examples: 1475.js.map
Only in dist/en/main/examples: 2874.js
Only in dist/en/main/examples: 2874.js.map
Only in dist/en/main/examples: 4283.js
Only in dist/en/main/examples: 4283.js.map
Only in dist/en/main/examples: 4342.js
Only in dist/en/main/examples: 4342.js.map
Only in dist/en/main/examples: 4890.js
Only in dist/en/main/examples: 4890.js.map
Only in dist/en/main/examples: 5293.js
Only in dist/en/main/examples: 5293.js.map
Only in dist/en/main/examples: 5561.js
Only in dist/en/main/examples: 5561.js.map
Only in dist/en/main/examples: button-title.css
Only in dist/en/main/examples: css
Only in dist/en/main/examples: stadia-maps.html
Only in dist/en/main/examples: stadia-maps.js
Only in dist/en/main/examples: stadia-maps.js.map
Only in dist/en/main/examples: style-expressions.html
Only in dist/en/main/examples: style-expressions.js
Only in dist/en/main/examples: style-expressions.js.map
Only in dist/en/main/examples: wms-image-svg.html
Only in dist/en/main/examples: wms-image-svg.js
Only in dist/en/main/examples: wms-image-svg.js.map
Only in dist/en/main/examples: worker.html
Only in dist/en/main/examples: worker.js
Only in dist/en/main/examples: worker.js.map
Only in dist/en/main/ol/events: KeyCode.d.ts
Only in dist/en/main/ol/events: KeyCode.d.ts.map
Only in dist/en/main/ol/events: KeyCode.js
Only in dist/en/main/ol/render/canvas: style.d.ts
Only in dist/en/main/ol/render/canvas: style.d.ts.map
Only in dist/en/main/ol/render/canvas: style.js
Only in dist/en/main/ol/render/webgl: BatchRenderer.d.ts
Only in dist/en/main/ol/render/webgl: BatchRenderer.d.ts.map
Only in dist/en/main/ol/render/webgl: BatchRenderer.js
Only in dist/en/main/ol/render/webgl: LineStringBatchRenderer.d.ts
Only in dist/en/main/ol/render/webgl: LineStringBatchRenderer.d.ts.map
Only in dist/en/main/ol/render/webgl: LineStringBatchRenderer.js
Only in dist/en/main/ol/render/webgl: PointBatchRenderer.d.ts
Only in dist/en/main/ol/render/webgl: PointBatchRenderer.d.ts.map
Only in dist/en/main/ol/render/webgl: PointBatchRenderer.js
Only in dist/en/main/ol/render/webgl: PolygonBatchRenderer.d.ts
Only in dist/en/main/ol/render/webgl: PolygonBatchRenderer.d.ts.map
Only in dist/en/main/ol/render/webgl: PolygonBatchRenderer.js
Only in dist/en/main/ol/renderer/webgl: shaders.d.ts
Only in dist/en/main/ol/renderer/webgl: shaders.d.ts.map
Only in dist/en/main/ol/renderer/webgl: shaders.js
Only in dist/en/main/ol/source: StadiaMaps.d.ts
Only in dist/en/main/ol/source: StadiaMaps.d.ts.map
Only in dist/en/main/ol/source: StadiaMaps.js
Only in dist/en/main/ol/source: arcgisRest.d.ts
Only in dist/en/main/ol/source: arcgisRest.d.ts.map
Only in dist/en/main/ol/source: arcgisRest.js
Only in dist/en/main/ol/source: mapguide.d.ts
Only in dist/en/main/ol/source: mapguide.d.ts.map
Only in dist/en/main/ol/source: mapguide.js
Only in dist/en/main/ol/source: static.d.ts
Only in dist/en/main/ol/source: static.d.ts.map
Only in dist/en/main/ol/source: static.js
Only in dist/en/main/ol: expr
Only in dist/en/main/ol: resolution.d.ts
Only in dist/en/main/ol: resolution.d.ts.map
Only in dist/en/main/ol: resolution.js
Only in dist/en/main: build
Only in dist/en/main: css
Only in dist/en/main: doc
Only in dist/en/main: legacy
Only in dist/en/v7.5.1/apidoc: module-ol_Image-ImageWrapper.html
Only in dist/en/v7.5.1/apidoc: module-ol_source_Stamen-Stamen.html
Only in dist/en/v7.5.1/apidoc: module-ol_source_Stamen.html

**Comment by mike-000** [comment]
https://openlayers.org/en/main/apidoc/module-ol_Image.html#~LoadFunction still has a link to ImageWrapper which now goes to 404.

**Comment by ahocevar** [comment]
I have deleted https://openlayers.org/en/main now. It will be rebuilt when the next pull request is merged.
