### ISSUE TITLE
WebGL tile layer errors out after some time of inactivity/computer no usage

### ISSUE THREAD

**Issue by tarmooo** [openlayers/openlayers#15069]
**Describe the bug**
using webgl tile layer errors out when computer comes back from sleep and shows white map.
console has following error:
Uncaught TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'
![image](https://github.com/openlayers/openlayers/assets/6084225/6353f839-7041-46d4-8740-43642b07b536)

**To Reproduce**
1. open map where tile layer with webgl is displayed
2. unfocus broser and leave it like that for some time - perhaps even put computer to sleep and wake it up.
3. profit - see empty(white) tile webgl layer 
![image](https://github.com/openlayers/openlayers/assets/6084225/55998e14-8cea-4f5a-9daa-57c6d85a010c)

**Expected behavior**
not to error out and still show webgl tile layer?

**Comment by mprins** [comment]
does #15066 fix your problem?

**Comment by tschaub** [comment]
Thanks for the report.  You should be able to use the fix from #15066 in the `ol@dev` package.  And it shouldn’t be too long before the next release.

Please reopen if the problem persists.
