### ISSUE TITLE
Full WebGL rendering on MVT layer

### ISSUE THREAD

**Issue by gtnewton** [openlayers/openlayers#15060]
I wanted to compare vector tile rendering in OL to MapLibre so I constructed a set of PBF vector tiles that cover zoom levels 0-14.

The two maps are here: https://hcmc.uvic.ca/people/greg/tiles/openlayers.html
and here: https://hcmc.uvic.ca/people/greg/tiles/maplibre.html
(if it helps, there's a styled version of the OL map here: https://hcmc.uvic.ca/people/greg/tiles/openlayers_styled.html)

Using the same vector tiles, the MapLibre map zooms in as far you like with no degradation in quality, but the OL map does not.

As I understand it this is the result of OL rasterizing the tiles whereas MapLibre uses WebGL rendering for everything.

I'm not clear on the issue though: is my experience a result of me not knowing what I'm doing? or is OL not able to render the vector tiles using WebGL?

Can someone explain what I'm doing wrong? And if I'm not doing anything wrong, can someone tell me if WebGL vector tile rendering is on the horizon?

I'm not sure if this is a bug report or a feature request.

**Comment by MoonE** [comment]
A webgl renderer is being worked on, e.g. #14445 but so far there is no text rendering. To test the current state you'd need to use an unreleased v8.0.0 version, e.g ol@dev via npm.
Here is [an examle](https://deploy-preview-15050--ol-site.netlify.app/en/latest/examples/webgl-vector-tiles.html)

**Comment by ahocevar** [comment]
The OpenLayers map is not configured correctly. As far as I can tell, your tiles are available down to zoom level 14, but it appears you haven't set `maxZoom: 14` on the `VectorTile` source. When you do that, you can zoom in as far as you want and will also get crisp rendering.

Also, you can avoid the configuration hassle and get the same style as for the maplibre map by using ol-mapbox-style to parse the style json:
```js
import {apply} from "ol-mapbox-style";
import {useGeographic} from "ol/proj";

useGeographic();
apply('map', "https://hcmc.uvic.ca/people/greg/tiles/vi.json").then((map) => {
  map.getView().setCenter([-121.72, 50.69]);
  map.getView().setZoom(6);
})
```

I have created a codesandbox with that: https://codesandbox.io/s/withered-sky-nvn9d3.

**Comment by gtnewton** [comment]
Thanks to you both. Both responses are massively useful.
