### ISSUE TITLE
The specifier “pbf” was a bare specifier, but was not remapped to anything

### ISSUE THREAD

**Issue by speich** [openlayers/openlayers#15071]
When I either use a local copy of OL or the CDN and import the module MVT, I run into the import error:

`Uncaught TypeError: The specifier “pbf” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.`

It is caused from the line 11 in the module MVT.js

import PBF from 'pbf';

**Comment by speich** [comment]
I tried to solve it with an importmap, 

```javascript
    <script type="importmap">
        {
            "imports": {
                "pbf": "./node_modules/pbf/index.js",
                "rbush": "./node_modules/rbush/index.js",
                "quickselect": "./node_modules/quickselect/index.js"
            }
        }
    </script>
```

but then I run into the next error:

Uncaught SyntaxError: ambiguous indirect export: default

**Comment by ahocevar** [comment]
I don't think pbf is compatible with browser imports, because it is published as CommonJS module. You'll have to use a bundler.

**Comment by speich** [comment]
I guess you are right, thanks  for the info.
