### ISSUE TITLE
Prefix variables used in WebGL 'get' expressions

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#15099]
Currently, when a `get` expression is used in a WebGL style, it is assumed that the corresponding variable [will be prefixed](https://github.com/openlayers/openlayers/blob/4fc0a26edc6bb7e4cafa1d38e4ce3e3d78091ef6/src/ol/style/expressions.js#L522) with `a_` in a vertex shader and `v_` in a fragment shader.  This is the same prefix that we use internally for attributes and varyings.

Instead, we should separate the user data/variables from the ones used internally by the library.  This was done for `var` expressions in #12023.  We should do something similar for variables used in `get` expressions (e.g. prefix with `a_prop_` and `v_prop_` - or drop the `a_` and `v_` altogether since in some cases these might not be attributes or varyings and instead might be computed and made available in the shader (as in #14491)).

**Comment by jahow** [comment]
Done in #15121
