### ISSUE TITLE
Upgrade notes link returns 404 in v8.1.0 section

### ISSUE THREAD

**Issue by nboisteault** [openlayers/openlayers#15092]
**To Reproduce**
1. Go to 'https://github.com/openlayers/openlayers/releases/tag/v8.1.0'
2. Click on 'upgrade notes'
3. See 404 error

**Comment by MoonE** [comment]
Seems to be working now, do you still have this issue?

**Comment by tschaub** [comment]
I corrected the link on the release page.  Thanks for the report.
