### ISSUE TITLE
ImageWMS imageLoadFunction asynchronous loading is broken

### ISSUE THREAD

**Issue by tobi238** [openlayers/openlayers#15093]
**Describe the bug**
The imageLoadFunction of ol/source/ImageWMS was useful to load images with post requests or - in general - through XHR requests, where the src of the image element would be set to a data URI when the content is loaded. This does no longer work in version 8 of OpenLayers.

**To Reproduce**
1. Setup an ImageWMS Source with a custom imageLoadFunction.
2. Use any asynchronous code to set the image.src to a data URI.
3. This results in the WMS image not being rendered on the map. The console shows the error message: "DOMException: The source image cannot be decoded."

**Stackblitz Example**
Here is an example implementation for OpenLayers version 7 and 8:
Working V7: https://stackblitz.com/edit/vite-abvayd?file=main.js
Broken V8: https://stackblitz.com/edit/vite-gkegv7?file=main.js

**Expected behavior**
According to the current documentation of the imageLoadFunction (https://openlayers.org/en/latest/apidoc/module-ol_Image.html#~LoadFunction) it should be possible to use a custom http request to load the image and apply it as a data URI.
This setup worked in version 7 of Openlayers and broke after we updated our codebase.

**Comment by mike-000** [comment]
#15094 will fix your compatibility issue.  In version 8 you also have the option of replacing your `imageLoadFunction` with a custom load function as in https://openlayers.org/en/latest/examples/wms-image-svg.html

**Comment by fperucic** [comment]
yes, async loading works with `tileLoadFunction` in `TileWMS` source, but not in `imageLoadFunction` for `ImageWMS` source.

It can be solved by using a custom `ImageSource` as in svg example, but then you are giving up on useful `ImageWMS` methods: `getFeatureInfoUrl`, `getLegendUrl`, `updateParams`

**Comment by tobi238** [comment]
> It can be solved by using a custom `ImageSource` as in svg example, but then you are giving up on useful `ImageWMS` methods: `getFeatureInfoUrl`, `getLegendUrl`, `updateParams`

That's the point why we also depend on the `imageLoadFunction.`

**Comment by ahocevar** [comment]
@fperucic Instead of calling `updateParams` you can just modify the `params` object you created the loader with. But you're right, the `getFeatureInfoUrl()` and `getLegendUrl()` methods should be made available as standalone functions in the `ol/source/wms` module.
