### ISSUE TITLE
Simpler way of changing extent of source / tile grid

### ISSUE THREAD

**Issue by velle** [openlayers/openlayers#15105]
I need to set an extent on an XYZ data source, because the default extent is larger than what my tile set covers. 

**Tile set that only covers a small area**

I have a dataset generated with gdal2tiles.py, in EPSG:3857. But the tiles only cover a small area of 1x1km. Its easy to have the map shown in OpenLayers, but when panning outside this area it looks for tiles that are not there which results in HTTP 404 error. I believe the proper solution is to specify an extent. 

**Can't use the extent of the layer**

The extent that can be specied on the layer applies according to the CRS set by the map. In my scenario the map CRS may change. 

**My current code for setting extent on source / tile grid**

First define the tilegrid. 

```
const projExtent = ol.proj.get('EPSG:3857').getExtent();
const startResolution = ol.extent.getWidth(projExtent) / 256;
const resolutions = new Array(22);
for (let i = 0, ii = resolutions.length; i < ii; ++i) {
  resolutions[i] = startResolution / Math.pow(2, i);
}
// evalues to the following array, which is the same as the default for epsg3857
// resolutions: [156543.03392804097, 78271.51696402048, 39135.75848201024, 19567.87924100512, 9783.93962050256, 4891.96981025128, 2445.98490512564, 1222.99245256282, 611.49622628141, 305.748113140705, 152.8740565703525, 76.43702828517625, 38.21851414258813, 19.109257071294063, 9.554628535647032, 4.777314267823516, 2.388657133911758, 1.194328566955879, 0.5971642834779395, 0.29858214173896974],

var customTileGrid = new ol.tilegrid.TileGrid({
    origin: [-20037508.342789244, 20037508.342789244],
    extent: [1124285.663144, 7623728.179027,1126114.607908, 7625560.953335],
    resolutions: resolutions,
    tileSize: [256, 256],
    minZoom: 14,
    maxZoom: 19,
});

```

Then create the source with that tilegrid:

```
var source = new ol.source.XYZ({
    projection: "EPSG:3857",
    url: 'http://localhost:5000/red/{z}/{x}/{-y}.png',
    tileSize: [256, 256],
    tileGrid: customTileGrid,
});
```
Thats a lot of code, when all I want to change is the extent of the source / tile grid. 

**One possible solution**

I'm not experienced enough to know what would be the best solution. But the following is one solutions I could come up with. 

```
var source = new ol.source.XYZ({
    projection: "EPSG:3857",
    url: 'http://localhost:5000/red/{z}/{x}/{-y}.png',
    tileSize: [256, 256],
    tileGrid: extendDefaultGridTile({
        extent: [1124285.663144, 7623728.179027,1126114.607908, 7625560.953335],
    }),
});
```
extendDefaultGridTile should return a function which the XYZ constructor will apply on the default grid tile.

**Comment by mike-000** [comment]
If you are needing that frequently you could create a custom XYZ class taking an additional `extent` option which uses `createXYZ` to obtain the default grid then uses its resolutions, origin and minZoom in a custom grid for the source


```
class customXYZ extends ol.source.XYZ {
  constructor(options) {
    const tileGrid = ol.tilegrid.createXYZ({
      extent: options.projection
        ? ol.proj.get(options.projection).getExtent()
        : undefined,
      tileSize: options.tileSize,
      minZoom: options.minZoom,
      maxZoom: options.maxZoom,
    });
    const baseOptions = Object.assign(
      {
        tileGrid: new ol.tilegrid.TileGrid({
          extent: options.extent,
          origin: tileGrid.getOrigin(0),
          resolutions: tileGrid.getResolutions(),
          tileSize: tileGrid.getTileSize(0),
          minZoom: tileGrid.getMinZoom(),
        }),
      },
      options
    );
    delete baseOptions.extent;
    super(baseOptions);
  }
}
```


Then use it to construct your sources

```
var source = new customXYZ({
    projection: "EPSG:3857",
    url: 'http://localhost:5000/red/{z}/{x}/{-y}.png',
    extent: [1124285.663144, 7623728.179027,1126114.607908, 7625560.953335],
    tileSize: [256, 256],
    minZoom: 14,
    maxZoom: 19,
});
```

**Comment by velle** [comment]
I will use that solution. Thanks :)

**Comment by kbatchu** [comment]
Did this work? I am trying to do exactly the same but the map does not display. I have tried with EPSG:3857 and EPSG:4326 but no luck. If I do not set the extent like in the above code, it does display but with 404 errors if it goes out of the layer's extent.

**Comment by mike-000** [comment]
@kbatchu  EPSG:3857 source with limited extent being displayed in EPSG:4326 https://codesandbox.io/s/simple-forked-htfx9m?file=/main.js

**Comment by kbatchu** [comment]
It worked. Thank you!
