### ISSUE TITLE
ol@8.1: DomException when using ImageStatic source with imageLoadFunction

### ISSUE THREAD

**Issue by mediafreakch** [openlayers/openlayers#15109]
**Describe the bug**

The following console error appears when using ImageStatic source with a custom imageLoadFunction: 

```
DOMException: The source image cannot be decoded. (Image.js:190)
```

The same example works with ol@7.5.2 . If this is not a bug but rather a breaking change, some guidance on how to fix it would be great.

**To Reproduce**

1. Go to https://stackblitz.com/edit/vitejs-vite-bjqfaj
2. Open devtools console

**Expected behavior**

- An image appears that can be zoomed into
- No console error

**Actual result**

- Browser console error as noted above appears
- No image

**Comment by ahocevar** [comment]
This has been fixed already with #15094 and #15103. You can install `ol@dev` to get the fix. See https://stackblitz.com/edit/vitejs-vite-n2h3n5 for your code with the updated dependency.

**Comment by ahocevar** [comment]
Also worth noting: there is now a better loader API which allows you to skip the data URI creation step. Instead of creating an ol/source/StaticImage, you create an ol/source/Image with a static loader, and a custom load function: 
```js
  new ImageSource({
    loader: createStaticLoader({
      url: 'sample.jpg',
      projection,
      imageExtent: imageExtent,
      load: async (image, src) => {
        let blobOptions = {};
        try {
          const { data: buffer, headers } = await axios.get(src, {
            responseType: 'arraybuffer',
            onDownloadProgress: (progress) => {
              console.log(
                'Download progress:',
                Math.floor((progress.loaded / progress.total) * 100)
              );
            },
          });

          const mimeType = headers['content-type'];
          blobOptions.type = mimeType && mimeType;

          const blob = new Blob([buffer], blobOptions);
          return createImageBitmap(blob);
        } catch (e) {}
      },
    }),
  })
```
https://stackblitz.com/edit/vitejs-vite-sqjnux.

**Comment by pelord** [comment]
Does a patch release is planned to push theses fixes?
@ahocevar

**Comment by pelord** [comment]
ol@dev fix the issue for olSourceImageWMS  with imageLoadFunction

**Comment by ahocevar** [comment]
We‘re going to publish another minor release soon, @pelord
