### ISSUE TITLE
render/canvas/Executor - text.split() fails 

### ISSUE THREAD

**Issue by rgreenwood** [openlayers/openlayers#15106]
I don't know if this is considered a bug. I'm labeling numeric data from a PostgreSQL database. I use the postgres function jsonb_build_object() so the JSON look like:
`"label": 600`
(the value is not quoted). This causes an error in render/canvas/Executor.js  
```
    const chunks = textIsArray
      ? text
      : text.split('\n').reduce(createTextChunks, []);
```
because .split() is not a method of a number. 

This is in at least OL 7.5 and 8.1

Obviously I can cast the value to text in postgres but I think that `"label": 600` is valid JSON.

Thanks

**Comment by MoonE** [comment]
The text label is required to be a string.
See https://openlayers.org/en/latest/apidoc/module-ol_style_Text-Text.html
