### ISSUE TITLE
WebGLTile Layer does not update palette textures when calling setStyle

### ISSUE THREAD

**Issue by malaretv** [openlayers/openlayers#15100]
**Describe the bug**
:wave:
When using `setStyle()` on a WebGLTileLayer, palette textures are not updated. 

**To Reproduce**
https://codesandbox.io/s/cog-style-forked-c3x64c?file=/main.js

The above is a very quickly put together forked example of Change Tile Layer Style.
It defines two palette styles, one that is black and red, and one that is black and blue.

1) Open page and notice red palette in use.
2) Select 'blue palette' and notice nothing changes

**Expected behavior**
When changing the layer style of a webgltile layer the new palette should take effect.

**Comment by tschaub** [comment]
Fixed by #15101 (thank you!)
