### ISSUE TITLE
Chrome rendering error for ol.style.Text with missing pixels?

### ISSUE THREAD

**Issue by hillmb79** [openlayers/openlayers#15134]
I have an OpenLayers-based application I am maintaining which uses a simple style function for point feature geometries to render an image icon (using SVG file derived from feature properties) along with text label using the ol.style.Text module like so:

```
      return (feature, resolution) => {
        return [
          new Style({
            text: new Text({
              font: this.fontSize + 'px NunitoSanBold,serif',
              text: this.dataBlockText(feature),
              fill: new Fill({ color: this.fontColor }),
              offsetY: this.yOffset
            }),
            image: new Icon({
              rotation: this.degToRadians(feature.get('heading')),
              color: this.color,
              src: this.getIcon(feature),
              scale: this.scale
            })
          })
        ]
      }
```

For some reason I don't understand, and it's not consistent (it works fine for some features such as top-left JBU8458 in both images below), the text in Chrome often appears distorted or missing pixels.  Often it's bad enough to unreadable - the bottom-right feature in Firefox can be clearly read as UAL674, but in Chrome it's unclear, and even worse for the other 2 features shown VXP9492 and FDX3951.

Chrome:
![OpenLayersChromeError](https://github.com/openlayers/openlayers/assets/26581644/6b82625d-6e70-445a-9da9-e6ce1d9c6930)

Firefox:
![OpenLayersFirefoxText](https://github.com/openlayers/openlayers/assets/26581644/6576c647-f5c5-4ab8-b933-2ecede7e451b)

The project has been using OpenLayers 6.3.1, and in troubleshooting this I've tried both upgrading to latest 7.x and 8.x as well as downgrading to 5.x to see if any change results but it does not.  I've also searched through the OpenLayers issues on GitHub and didn't find anything which looked like my specific issue, so just hoping for some other idea to try?

Thank you

**Comment by mike-000** [comment]
It may be a Chrome or hardware problem.  Does the problem persist if you change "Use hardware acceleration when available" in the Chrome settings?

**Comment by hillmb79** [comment]
Wow, turning off the "Use hardware acceleration when available" in Chrome does indeed resolve the problem entirely.  That is unfortunate as this is for a public-facing application, but I guess we can give this guidance to users if they complain about it.  Thanks for your help!
