### ISSUE TITLE
Icon cache for RegularShapes

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#15147]
With the new style expressions, should there be some kind of IconCache for RegularShapes?

An example like https://openlayers.org/en/latest/examples/regularshape.html that is [implemented with style expressions](https://github.com/MoonE/openlayers/commit/f96b1a4b5789324542d1cfd0e288c36ed0e6b9fc) will re-render the RegularShape canvas for every drawn feature.

Even if the RegularShape is only re-rendered when the resulting style actually changed that will not help  much when the features are in a random order.

**Comment by ahocevar** [comment]
I'm wondering if it wouldn't be sufficient to change the default icon cache size from 32 to a higher number, and use it for all `Image` styles, not just icons. I imagine this would be quite a small change.
