### ISSUE TITLE
WHY the result of GetLength are differents from POSTGIS?

### ISSUE THREAD

**Issue by wwwwhhhzzzccc** [openlayers/openlayers#15145]
/**************** in Openlayers 8.x*****************/
import { getLength } from 'ol/sphere.js'
import { LineString } from 'ol/geom.js'
const line = new LineString([[114, 30], [114, 31]]).transform('EPSG:4326', 'EPSG:3857')
console.log(getLength(line))
------
result is: 111195.08023353448

/**************** in pgAdmin(postgresql+postgis) *****************/
SELECT st_length(st_geomfromgeojson('
{"type":"LineString","coordinates":[[114,30],[114,31]]}
'),TRUE)
------
result is: 110860.92556607934

why two results are differents??????

how can i make those to equal?

**Comment by mike-000** [comment]
OpenLayers is using a sphere, PostGIS with the second parameter TRUE is using a spheroid which takes account of polar radius being smaller than equatorial.  Change TRUE to FALSE to use a sphere in PostGIS.

If you need a spheroid calculation in OpenLayers you could base it on the Vincenty algorithm used in Openlayers 2 https://github.com/openlayers/ol2/blob/master/lib/OpenLayers/Util.js#L756 as in https://codesandbox.io/s/measure-forked-w9lfck?file=/main.js where it is updated to ES6, uses the current OpenLayers coordinate arrays, and returns the result in meters.

**Comment by MoonE** [comment]
@mike In your example `sinSigma` and `cos2SigmaM` should not be re-declared inside the loop. Getting `NaN` for length.

**Comment by mike-000** [comment]
> @mike In your example `sinSigma` and `cos2SigmaM` should not be re-declared inside the loop. Getting `NaN` for length.

Thanks, fixed now.

**Comment by wwwwhhhzzzccc** [comment]
Change TRUE to FALSE to use a sphere in PostGIS
-——————————————
i did it，then the result is 1 in postgis

additionally, the result is 0.9988824 in openlayers8.0 when i chosen EPSG:4326

**Comment by wwwwhhhzzzccc** [comment]
> > @mike In your example `sinSigma` and `cos2SigmaM` should not be re-declared inside the loop. Getting `NaN` for length.
> 
> Thanks, fixed now.

thank you very much. your method is usefull to me and the result is nearly equal to in POSTGIS.
 
then, we have a new getLength, what about a new getArea?  :-)

at last. i want know which result is more accurate? OL or POSTGIS

**Comment by Rskut** [comment]
Check out the following issue: https://github.com/openlayers/openlayers/issues/13780

**Comment by mike-000** [comment]
Over a distance of 100km spherical geometry will be much more accurate that flat geometry and using spheroid calculations will further improve the accuracy.  For spheroid area you would need a third party library such as https://geographiclib.sourceforge.io/html/js/index.html as in https://codesandbox.io/s/measure-forked-rmz9f8?file=/main.js  See also #13572.

**Comment by wwwwhhhzzzccc** [comment]
@Rskut @mike-000 thanks so much!
