### ISSUE TITLE
Raster reprojection assumes that projected pixels are square

### ISSUE THREAD

**Issue by julienrf** [openlayers/openlayers#15144]
**Describe the bug**

It seems that raster reprojection always tries to display square target pixels, which can lead to mis-alignments in some cases.

In the screenshot below I project a 5×5 pixels image where my intent is that each pixel of the source image covers an area of 3km by 2km. The blue circles show the expected centers of each pixels. The source projection is Lambert Conformal Conic and the target projection is Web Mercator.

![image](https://github.com/openlayers/openlayers/assets/332812/3e63f872-2d44-42fb-b822-0cbf02ff69cf)

We see that vertically the pixels are correctly aligned with their expected centers. However, horizontally we observe a mis-alignment. This is because OpenLayers tries to draw perfect squares only. On the left of the screenshot, we see that the first column of pixels of the  source image is repeated twice. The resulting projected column extends too far to the east. Ultimately, the 5×5 source image looks like a 7×5 image in the result.

**Expected behavior**

Instead, I would expect the pixels of the destination to be stretched so that the total number of “projected pixels” is exactly the same as the number of pixels of the source image.

Note that in my real use case, my “pixels” are actually square … in their source projection. They cover a 2km by 2km area, but when they are projected, the result may not be perfectly square, leading to similar mis-alignments.

It seems #4124 can not help for this use case, unless I missed something?

Is there a way to preserve the amount of source pixels in the projection result? Would the situation be different if I was using GeoTiff files instead of projecting PNG images?

**Comment by mike-000** [comment]
You are seeing the effect of stretching a small image with interpolation disabled, then upscaling it.  That would have affected non-reprojected ImageStatic before version 8 https://codesandbox.io/s/static-image-forked-thmnkw?file=/main.js but is now fixed by stretching and upscaling in one operation https://codesandbox.io/s/static-image-forked-zwvccm?file=/main.js  #15013 will fix this for reprojection.

**Comment by julienrf** [comment]
Thank you for your quick answer and detailed analysis. I confirm that my code works with #15013:

![image](https://github.com/openlayers/openlayers/assets/332812/90e3ab83-badd-432d-9ab7-527af8a07400)
