### ISSUE TITLE
ol-mapbox-style 

### ISSUE THREAD

**Issue by pelord** [openlayers/openlayers#15157]
**Describe the bug**
Since v8, ol-mapbox-style is set as a dev dependency. https://github.com/openlayers/openlayers/blob/c7969f5255edd8cbe5ece89ab026fe0f6f69cef1/package.json#L95 

Although, into the [upgrade notes](https://github.com/openlayers/openlayers/blob/main/changelog/upgrade-notes.md#removal-of-ollayermapboxvector) but you now refer to ol-mapbox-style to create MapboxVectorLayer.

**Expected behavior**
Does ol-mapbox-style is not suppose to be a peer dependency?

**Comment by ahocevar** [comment]
The package.json of the repository is different from the one of the npm package. The ol package does not depend on ol-mapbox-style, and recent versions of ol-mapbox-style have ol as peer dependency.

**Comment by alecarn** [comment]
But it depended on it in version 7.4.0. See this screenshot below from distributed `package.json` of `ol-v7.4.0` vs `ol-v8.1.0`
![image](https://github.com/openlayers/openlayers/assets/133774929/71cc95f6-af03-468c-aa43-316782b12c29)
![image](https://github.com/openlayers/openlayers/assets/133774929/e6d3c91b-0651-439d-a178-89552b58e9de)

**Comment by ahocevar** [comment]
Yes, that‘s correct. Removing it (because it was a circular dependency of ol/layer/MapboxVector was a breaking change, hence the major release bump to v8.

**Comment by alecarn** [comment]
It was not clear to us that this dependency was removed when reading the release note. But that suits us and we will continue our test with this new version, thanks to the entire OL team
> To avoid a circular dependency between the ol and ol-mapbox-style packages, this layer has been removed. If you have been using ol/layer/MapboxVector, you can easily switch to using MapboxVectorLayer from the ol-mapbox-style package, version 11 or greater.
