### ISSUE TITLE
map not filling the whole screen

### ISSUE THREAD

**Issue by prosperva** [openlayers/openlayers#15158]
I am trying to have the map fill the whole screen but it seems not to be working. I have tried changing map extent ( [-7669225.024844417, -1593163.3223518212, 6221427.756461145,
                4121848.1076710387]) but it got me so far. Here is a screenshot:

![image](https://github.com/openlayers/openlayers/assets/1531271/fc0e8868-9e48-43d9-9198-0798f6867c38)

I would like to fill the whole screen including the white background area.

**Comment by MoonE** [comment]
Please provide a complete example. It's infeasible to help with just what you provided here.

**Comment by prosperva** [comment]
Found a solution
