### ISSUE TITLE
popup positioning

### ISSUE THREAD

**Issue by prosperva** [openlayers/openlayers#15167]
I looked at this example https://openlayers.org/en/latest/examples/overlay.html and saw that it uses bootstrap popover. Is there a way to implement this in openlayers without using bootstrap. I have tried positioning property on the overlay and I don't want to use autopan as it moves the map. I would like to keep the popup in view

Working code

https://jsfiddle.net/frc642zq/1/

**Comment by mike-000** [comment]
In the css replace `left: 50%;` with `transform: translateX(-50%);` https://jsfiddle.net/erbd5j8s/

**Comment by prosperva** [comment]
It does not work, the popup is still out of view

**Comment by prosperva** [comment]
The idea is basically to have the arrow appear either left, right, top or bottom depending on available view

**Comment by mike-000** [comment]
Determine which quadrant of the viewport the click was made in and add extra class information to the element for that

```
  var pixel = map.getPixelFromCoordinate(coordinate);
  var size = map.getSize();
  var hPosition = pixel[0] < size[0] / 2 ? 'left' : 'right';
  var vPosition = pixel[1] < size[1] / 2 ? 'top' : 'bottom';
  container.className = 'ol-popup ol-popup-' + hPosition + ' ol-popup-' + vPosition;
```
Than add any css which is specific to those classes https://jsfiddle.net/uk7vqsfy/
