### ISSUE TITLE
Small static images incorrectly displayed on layer

### ISSUE THREAD

**Issue by sampov2** [openlayers/openlayers#15186]
**Describe the bug**
OpenLayers ImageLayer renders small (static) images incorrectly.

**To Reproduce**
I've provided example code that reproduces the issue:  https://github.com/spatineo/openlayers/blob/bug-small-static-images/examples/very-small-static-image.js . See screenshot below.

![image](https://github.com/openlayers/openlayers/assets/770750/82b087d3-a3a3-428f-b3d9-3109e5572b4a)

The example code has two image layers, both with a single static image. The images are generated via 2d canvas. The difference between the images is their size (left one 300x300 vs 30x30 pixels on the right). They are placed next to each other on the map. The map also has feature layers that have a polygon for each extent of the image to show the expected area where the image should be rendered.

As you can see from the image, the small image is not rendered within the given imageExtent. Neither zooming nor panning has any effect on the rendering behaviour.

**Expected behavior**
I would expect both images to look approximately the same on the rendered map, except for the loss of fidelity for the image that has fewer pixels.

**Comment by mike-000** [comment]
In both cases you were using `putImageData` on a 300 x 150 pixel canvas, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas#attributes.  You need to size the canvas to match the `imageData` https://codesandbox.io/s/simple-forked-fylcd8?file=/main.js

**Comment by sampov2** [comment]
Thank you for the quick response! Indeed you are correct, this explains the issue and specifying canvas width and height fixes this.
