### ISSUE TITLE
Custom Build / Legacy Build still possible in OL8?

### ISSUE THREAD

**Issue by deweydb** [openlayers/openlayers#15206]
I'm looking for a way to make a reduced dist of ol.js 
Similar to what is described in this outdated tutorial:
https://dolmenweb.it/viewers/openlayer/doc/tutorials/custom-builds.html
Is there some way to still do this with OL8?

**Comment by deweydb** [comment]
Also similarly described here in french:
https://openlayers.org/workshop/fr/custom-builds/create.html

**Comment by MoonE** [comment]
Yes, this is still possible. See here for an example using webpack:
https://github.com/phpmyadmin/phpmyadmin/blob/3c21a0e0d20affcd39171dc09d993c03a59b9ece/js/src/ol.mjs
https://github.com/phpmyadmin/phpmyadmin/blob/3c21a0e0d20affcd39171dc09d993c03a59b9ece/webpack.config.cjs#L196-L221

**Comment by deweydb** [comment]
@MoonE thank you so much you saved me. I was so stuck!

**Comment by geographika** [comment]
Thanks @MoonE - using webpack works great for me. Custom builds for MapServer viewer can be seen in https://github.com/geographika/ol-mapserver
