### ISSUE TITLE
WebGLPointsLayer does not work correctly with useGeographic

### ISSUE THREAD

**Issue by prusswan** [openlayers/openlayers#15207]
**Describe the bug**

As title. `WebGLPointsLayer` does not seem to respect the featureProjection specified at the Vector source (e.g. EPSG:4326) and creates features with geometry in the projection of EPSG:3857.

**To Reproduce**
1. Refer to: https://codesandbox.io/s/webgl-points-layer-forked-wc6p5d

Above is adapted from the WebGLPointsLayer example (combined with Popup, Vector Layer examples)

2. Enable `useGeographic()` and observe that the `WebGLPointsLayer` points are plotted at the wrong locations (somewhere near Africa).

**Expected behavior**

`WebGLPointsLayer` should work with `useGeographic()` in the same manner as regular `VectorLayer` (used with `WebGLVectorLayerRenderer`, or not)

**Comment by mike-000** [comment]
Also noted in https://github.com/openlayers/openlayers/issues/14811#issuecomment-1581597665

**Comment by prusswan** [comment]
@mike-000 thanks, I first ran into this issue with one of the dev builds (https://cdn.jsdelivr.net/npm/ol@8.1.1-dev.1695883797965/dist/ol.js) so probably the issue has not being fully fixed.

**Comment by mike-000** [comment]
Yes, #15118 only fixed the original issue in #14811, not WebGLPointsLayer or HeatMap.
