### ISSUE TITLE
Polygons, that cross the 180 meridian, disappear

### ISSUE THREAD

**Issue by veinara** [openlayers/openlayers#15218]
**Describe the bug**
OL version: latest
The "wrapX" option of vectorLayer is true

Polygons, that cross the 180 meridian, disappear, when the map edge moves over the said meridian.
![disappearing_polygon](https://github.com/openlayers/openlayers/assets/240089/e40955f3-3170-44b4-a7a7-5942a499ecbb)

I tried with splitting the polygons to Multipolygons, but the styles of the polygon don't allow me to use that.
![image](https://github.com/openlayers/openlayers/assets/240089/3be51b2c-c54d-41ce-98f0-4fab5fa7d9e5)

**To Reproduce**
1. Add the polygon
2. Move the edge of the map
3. The polygon disappears

https://codesandbox.io/s/silly-pare-j4xvyf?file=/src/index.js

**Expected behavior**
The polygons to stay visible.

Any suggestions will be greatly appreciated!

**Comment by jahow** [comment]
Hi! Thanks for reporting the issue and providing a reproduction case. The codesandbox you linked uses an old version of OL (6.4.3), and unfortunately I couldn't witness the same visual result as the one showing in the videos.

Could you maybe provide a working reproduction case using a more recent OL version? thanks!

**Comment by mike-000** [comment]
If geometries cross the antimeridian you should ideally use `wrapX: false`.  But if you must wrap and the stroke within the MultiPolygon produced by splitting is a problem you could style the stroke and fill separately and use a MultiLineString geometry based on the original Polygon outline for the stroke - example using turf.js to dynamically split the geometries in a style https://codesandbox.io/s/polygon-over-antimeridian-forked-qnskk2?file=/src/index.js (creating new features when loading the source would be more efficient).

**Comment by veinara** [comment]
That did the trick.
Thank you very much!
