### ISSUE TITLE
There is a slight gap below the text

### ISSUE THREAD

**Issue by Lazydd** [openlayers/openlayers#15215]
There's a little gap below, or how does it center in the vertical direction
![image](https://github.com/openlayers/openlayers/assets/71319962/0763f769-8d8d-44ee-bc93-376110442296)

[example](https://codesandbox.io/s/cluster-forked-mz9hrd?file=/main.js)

**Comment by MoonE** [comment]
Your label characters are entirely above the text baseline. This can be corrected with a padding when you know what characters will be used (as you have already found out).
![image](https://github.com/openlayers/openlayers/assets/4426597/c3917e23-4240-4173-a92b-9e079df2b0a8)
