### ISSUE TITLE
Icon distortion on `WebGLPoints` layer

### ISSUE THREAD

**Issue by kikuchan** [openlayers/openlayers#15228]
**Describe the bug**
Icons are distorted on `WebGLPoints` layer when `icon-rotate-with-view: true` is used with non-square viewport.

**To Reproduce**
Something like
```js
const vector = new WebGLPointsLayer({
  source: new VectorSource({
    url: '/data/2012_Earthquakes_Mag5.kml',
    format: new KML({
      extractStyles: false,
    }),
  }),
  style: {
    'icon-src': '/data/icon.png',
    'icon-rotate-with-view': true,
  },
});

const raster = new TileLayer({
  source: new XYZ({
    url: '/data/tiles/satellite/{z}/{x}/{y}.jpg',
    transition: 0,
  }),
});

new Map({
  layers: [raster, vector],
  target: 'map',
  view: new View({
    center: [15180597.9736, 2700366.3807],
    zoom: 2,
    rotation: Math.PI / 2,
  }),
});
```
![actual](https://github.com/openlayers/openlayers/assets/445223/ec886b5c-df7f-48e2-a00f-942582e6558f)

**Expected behavior**
The icons should be displayed without distortion.

**Note**
I tried to implement it as a test code, but I realized it cannot be expressed as a test code because the current test framework uses a square viewport. It only happens when with non-square viewport.

**Comment by mike-000** [comment]
> I tried to implement it as a test code, but I realized it cannot be expressed as a test code because the current test framework uses a square viewport. It only happens when with non-square viewport.

Rendering tests run in a 256 x 256 page viewport.  It should be possible to reduce the map viewport size within that, e.g. `map.setSize([256, 128]);`


The bug can also be seen when using

```
{
  "icon-src": "data/icon.png",
  "icon-width": 18,
  "icon-height": 28,
  "icon-color": "lightyellow",
  "icon-rotate-with-view": true,
  "icon-displacement": [
    0,
    9
  ]
}
```

in https://openlayers.org/en/latest/examples/webgl-points-layer.html
and fixed in https://deploy-preview-15229--ol-site.netlify.app/en/latest/examples/webgl-points-layer.html

**Comment by kikuchan** [comment]
Thank you for the information!
Unfortunately, the `map.setSize` didn't work as expected in the test environment, but I have finally managed to compose a test code.
