### ISSUE TITLE
COG support for OpenLayers 6?

### ISSUE THREAD

**Issue by fjacupar** [openlayers/openlayers#15247]
I'm trying to use a GeoTiff source for a TileLayer in order to load a COG file from a URL in Openlayers 6 but I get errors when import Geotiff source like this: 

`import GeoTIFF from 'ol/source/GeoTIFF.js'`

Is it possible to use GeoTiff source in OL6 or is it mandatory to use the geotiff library directly?

Thanks in advance.

**Comment by mike-000** [comment]
`ol/source/GeoTIFF` was added in version 6.7.0 https://github.com/openlayers/openlayers/releases/tag/v6.7.0

**Comment by fjacupar** [comment]
@mike-000 thanks! I thought it was added from 6.0.0 version.
