### ISSUE TITLE
safari auto-extract process change the folder name

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#15245]
Hi
if i go here (https://github.com/openlayers/openlayers/releases/download/v8.1.0/v8.1.0-package.zip)
i get a folder named v8

should not be v8.1 or better(ol-v8.1 or something like this ?) ?

Thanks

**Comment by draunger** [comment]
Hey @jipexu I want to work on this can you assign it to me

**Comment by ahocevar** [comment]
If I download https://github.com/openlayers/openlayers/releases/download/v8.2.0/v8.2.0-package.zip (or the same for v8.1.0), I get the same contents as in the npm package. There is definitely no folder named `v8`.

@jipexu Can you clarify what exactly you were not happy with?

**Comment by jipexu** [comment]
Hi @andreas no problem with the content of the folder i just want to say when i download :  the name of the folder is "v8" and not "ol-v8.1" or "ol-v8.2" ... in clear i miss "ol" in the name of the downloaded folder ... but perhaps is only a detail or intentional ? But for me if there is no technical constraint a folder name with "ol" and the "version" will be more explicit... 
Thanks an happy new years @all ! ...

<img width="676" alt="Capture d’écran 2024-01-10 à 10 09 34" src="https://github.com/openlayers/openlayers/assets/328101/535a2ad1-0c4c-4242-a257-d24ea1c405c1">

**Comment by ahocevar** [comment]
@jipexu Isn't that specific to your OS or the auto-extract settings you've configured?

**Comment by jipexu** [comment]
hummmm .... good question ! ... I hadn't considered it from that angle ...
[MacOS Monteray 12.7.1 (21G920)] let me see for the the auto-extract settings that i have never explored and never parametred ...

**Comment by jipexu** [comment]
ok you are right !
It is the auto-extract process of safari who change the name of the folder !!! 
if i remove the option in the safari preferences>general  the name is correct i get "v8.2.0-package" instead of "v8" !!!
Damn SAFARI ! 
So sorry for this. But now i know why ...
Thanks

**Comment by ahocevar** [comment]
Probably because Safari takes everything before the first `"."` as folder name.
