### ISSUE TITLE
`view.getResolution()` returns underlying projection's resolution though using `useGeographic()`

### ISSUE THREAD

**Issue by kikuchan** [openlayers/openlayers#15249]
**Describe the bug**
When using `useGeographic()`, `view.getResolution()` returns underlying projection's resolution instead of the user resolution.

**To Reproduce**
```js
import View from 'ol/View';
import { useGeographic } from 'ol/proj';

useGeographic();

const view = new View({
  center: [0, 0],
  zoom: 2,
});

console.log(view.getResolution());
```

**Expected behavior**
`view.getResolution()` should return `0.3519564973994651` instead of `39135.75848201024` in this case.

**Comment by mike-000** [comment]
That is consistent with how `resolution`, `resolutions`, `minResolution`, `maxResolution` are specified in the View constructor, and the corresponding setters.  The API does not say any of those should be in user projection.  The only place where resolutions are in user projection in the loaders and strategies of vector sources.

**Comment by kikuchan** [comment]
Oh, I understand about consistency. Thanks.
Indeed, it's surely difficult...
I thought it would be very useful if the `getResolution()` returned the actual resolution based on user coordinates, and maybe we can use user projection for `resolution`, `minResolution`, `maxResolution`, but I realize we cannot determine that user specified `resolutions` should be treated as for an underlying projection, or a user projection...

Although, if I really want to know the actual resolution of units of user projection, how do I obtain it without a private `toUserResolution` function? (it is not marked as an API)
Add another `view.getUserResolution` API or somthing?

(In my case, user resolution is very useful to switch view between projections that are incompatible each other)

**Comment by mike-000** [comment]
To meaningfully switch between incompatible projections you need to use point resolution https://openlayers.org/en/latest/examples/projection-and-scale.html

**Comment by kikuchan** [comment]
I didn't know that API. Thank you, I'll try it!
