### ISSUE TITLE
Drawing feature issue with latest chrome version

### ISSUE THREAD

**Issue by sanova** [openlayers/openlayers#15248]
**Describe the bug**
Drawing line or polygon geometry with Draw control the geometry doesn't follow the pointer. Last portion of geometry doesn't appear till sketch is ended by clicking on map to add new vertex.

**To Reproduce**
1. OS: Debian 11 
2. Google Chrome version: 118.0.5993.70 (Official Build) (64-bit)
3. OL version: 7.3.0
4. Activate draw control and draw linestring or polygon 

**Expected behavior**
You should see the geometry following the pointer during sketch.

**Comment by ahocevar** [comment]
Can this be reproduced with one of the official examples that include the Draw interaction? https://openlayers.org/en/latest/examples/?q=draw

**Comment by sanova** [comment]
Yes, i have the issue also with the official example. 
Trying with firefox on same machine it works perfectly.
I'm trying with different older chrome version (117) and it has the same behaviour (before updating from old old version it perfectly worked)
On ubuntu 20.04 it works with the two chrome versions (117 and 118). So it is so strange.

**Comment by sanova** [comment]
It is an issue related to the chrome on my machine. Testing it in other os/machines with random chrome version it works.
It is not an openlayers bug.
I'm sorry
