### ISSUE TITLE
Flat Style Multiple String Expression Combining

### ISSUE THREAD

**Issue by MannyKSoSo** [openlayers/openlayers#15246]
I am attempting to combine the combination of two (possibly more) fields into one String Expression where I have multiple fields I want to combine into a single text. I'm not sure if its currently possible to combine the fields in the String Expression to do multiple getters like the following:

```
style: {
    'text-value': [['get', 'adm0name'], ' ', ['get', 'adm1name']],
    'text-font': '16px sans-serif',
    'text-fill-color': 'white',
    'text-stroke-color': 'gray',
    'text-stroke-width': 2,
 }
```
above example is using the [style expression](https://openlayers.org/en/latest/examples/style-expressions.html) data.

I have also created a quick [code sandbox](https://codesandbox.io/s/style-expressions-forked-cqtcl4?file=/main.js) just to quickly create an example to mess around with to try and get the "text-value" property to work. I know it works with a single ['get', 'adm0name'] but it doesn't with both as provided. Ideally, I would like to stick with just the flat style as I didn't want to provide a style function as it was going to increase complexity when I add the data and only need to adjust it slightly based on the field(s) I want to grab.

Any insight would be helpful!

**Comment by ahocevar** [comment]
What's missing here is a `concat` string operator or something similar. If that's implemented, your `text-value` could look like this:
```js
'text-value': ['concat', ['get', 'adm0name'], ' ', ['get', 'adm1name']],

**Comment by MannyKSoSo** [comment]
I'm guessing this `concat` or something similar could be introduced into the [ol/style/expressions.js](https://github.com/openlayers/openlayers/blob/main/src/ol/style/expressions.js) Operators? Or is there a different place it would need to go in order to introduce the value?

**Comment by ahocevar** [comment]
@MannyKSoSo That's for WebGL. For flat styles with the Canvas 2d renderer, you'll also have to modify `ol/style/expr/cpu.js`.
