### ISSUE TITLE
default `size` for the `fit` function behaves unintuitively

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#15268]
**Is your feature request related to a problem? Please describe.**
If you work on an app that uses multiple openlayers map, the default size value is very unintuitive. The actual size default value is the size of the first map in the dom. One would expect that the size is from the map that uses the view. I know that the view does not have a reference to the map.

**Describe the solution you'd like**
I would suggest to move the size out of the options object and make it a parameter (`view.fit(extent, size, options)` . This will remind the developer to think about it.

This would be a breaking change.

Also I would consider removing the default. In every case I encountered while working with openlayers so far, the map was known at the point where `.fit` was called.

**Comment by ahocevar** [comment]
Maybe the documentation needs an update. Since quite a while, `fit` does not use the size of the first map in the dom, but the actual size of the map the view is associated with. The `size` parameter is only necessary for a view that has not been associated with a map yet.

Maybe you want to create a pull request that fixes the documentation?

**Comment by simonseyock** [comment]
Ok, then it is bugged. I will look into that.

**Comment by simonseyock** [comment]
If `setTarget` is called from a react mount callback the call of `getComputedSize` returns a CSSStyleDeclaration that does not contain `width` and `height`.
That is no problem in `updateSize` because it uses the `offsetWidth` and calculates the actual size from there. But in `updateViewportSize_` the problem occurs.
This leads to the question: Why is `updateViewportSize_` in `Map.js` a different logic from `updateSize`, anyways? I don't see any reason for that.

I would suggest passing the size as a parameter to `updateViewportSize_`.

**Comment by mike-000** [comment]
> the actual size of the map the view is associated with

A view can be associated with multiple maps.  In this example https://codesandbox.io/s/side-by-side-forked-qwqf8v?file=/main.js both `calculateExtent()` and `fit()` are defaulting to the size of the second map - if map sizes can be independently updated it could be either map.

**Comment by simonseyock** [comment]
Ok, according to implementation then the size that would be used, would be the map where one of the following events occured last:
* setSize
* resize event
* setView
* setTarget

I would then write that the size can not be determined correctly if more than one map is used with one view. Is this features used often? I think it might be used for overview maps, but in any application I work with, we actually use a different view.

**Comment by simonseyock** [comment]
See the linked PR for a formulation.
