### ISSUE TITLE
8.1 - no NPM - GeoTIFF is not defined

### ISSUE THREAD

**Issue by Gaetanbrl** [openlayers/openlayers#15272]
**Describe the bug**
## Version

Version : v8.1.0
Load : from release dist/ol.js inside index.html (old school import style)

## Description

Hi,
I try to use OL 8.1.0 to view a simple TIFF file.

If i use openlayers as Vite dependancy (start serve with NPM), it works.

But if i load OpenLayers from ol.js file without NPM, i get an error :
`ReferenceError: GeoTIFF is not defined`

```
    <script
        type="text/javascript"
        src="lib/openlayers/8.1.0/ol.js"
    ></script>
```

When i debug ol lib, i can find `ol.source.GeoTIFF` function :

![image](https://github.com/stuartmatthews/leaflet-geotiff/assets/16317988/316ccbc0-93b1-47de-a4b0-928dfdf89832)

**Do you reproduce this behavior ? Need i to import GeoTIFF lib before ol in v8.x ?**

Thanks.

GB

**To Reproduce**
1. import OL with ol.js file without npm (in index.html so)
```
    <script
        type="text/javascript"
        src="lib/openlayers/ol.js"
    ></script>
```

2 Create a layer with this code

Here is the code inspired by OL examples  : 

```
const layer = new ol.layer.WebGLTile({
    source: new ol.source.GeoTIFF({
		sources: [
			{
                               // from example
                              url: 'https://openlayers.org/data/raster/no-overviews.tif',
                              overviews: ['https://openlayers.org/data/raster/no-overviews.tif.ovr'],
			},
		],
	}),
});
```

Try.

**Expected behavior**

Expected to work as OL example.

**Comment by Gaetanbrl** [comment]
If i add lib GeoTIFF it seems work better : 

`<script src="https://cdn.jsdelivr.net/npm/geotiff"></script>`

**Comment by mike-000** [comment]
Yes, https://openlayers.org/download/

> The full build of the library does not include all dependencies: the geotiff and ol-mapbox-style packages are omitted. If you use these, you'll need to add additional script tags.

**Comment by Gaetanbrl** [comment]
Oh thanks !
