### ISSUE TITLE
ol/proj4js not working with esm.sh modules

### ISSUE THREAD

**Issue by arbakker** [openlayers/openlayers#15274]
**Describe the bug**

I cannot get openlayers to work with [proj4js](https://github.com/proj4js/proj4js) while using [esm.sh](https://esm.sh/) modules. When using a package bundler like parcel.js this does work. So I am not sure this is actually a bug in openlayers, since it occurs in the interaction between proj4js, openlayers and esm.sh.  But right know I do not know how to continue to debug this issue, so any suggestions are welcome. 

**To Reproduce**

1. clone https://github.com/arbakker/ol-proj4-esm-issue
2. navigate to `failing-esm-example` dir
3. serve out example with `python3 -m http.server 8181` or some other webserver
4. visit [`http://localhost:8181`](http://localhost:8181) in your browser
5. both coordinate pairs should be converted to `EPSG:28992`, however the one converted by openlayers is not converted

There is also an code example that does work, which uses regular javascript package dependencies (and parcel for a bundler). To run:

1. navigate to `succeeding-yarn-example`
2. run `yarn install`
3. run `yarn start`
4. visit [`http://localhost:1234`](http://localhost:1234) in your browser
5. both coordinate pairs are converted to `EPSG:28992`

**Expected behavior**
Both coordinate pairs in the `failing-esm-example` example should be converted to `EPSG:28992`.

**Comment by ahocevar** [comment]
You have a typo in the proj4 import. It should be
```js
        import proj4 from 'https://esm.sh/proj4@2.9.2';
```
instead of
```js
        import proj4 from 'https://esm.sh/proj4@2.9.2"';
```
But changing that does not solve the problem.

I suspect this is an issue with esm.sh, because the same thing works fine with skypack.

**Comment by arbakker** [comment]
Indeed, it works with skypack. I opened an issue at esm.sh. Thanks!
