### ISSUE TITLE
GeoTIFF layers do not support TIFFs with GeoTransform/rotation

### ISSUE THREAD

**Issue by loganwilliams** [openlayers/openlayers#15294]
**Describe the bug**
When trying to add a certain GeoTIFF to an OpenLayers map, it renders in an incorrect location. The GeoTIFF in question is https://unnerving-monsoon.ams3.cdn.digitaloceanspaces.com/Georgia/2023-10-30-06-47-55_UMBRA-04.tif. This is not reproduced in QGIS or other COG tools.

**To Reproduce**
1. Go to https://www.cogeo.org/map/ and use the URL above. The TIFF renders correctly, using Marblecutter.
2. Go to https://geotiffjs.github.io/cog-explorer/ and use the URL above. The TIFF renders in an incorrect location, using OpenLayers.

It can also be reproduced by adding the following source to an OpenLayers map:

```
const source = new GeoTIFF({
  normalize: true,
  bands: [1, 1, 1],
  sources: [
    {
      url: 'https://unnerving-monsoon.ams3.cdn.digitaloceanspaces.com/Georgia/2023-10-30-06-47-55_UMBRA-04.tif',
      bands: [1, 1, 1],
      max: 300,
    },
  ],
});
```

**Expected behavior**
The projection and extent is read and interpreted correctly.

**Comment by loganwilliams** [comment]
After looking into this some more, I think it might be a bug or unsupported feature in geotiff.js. Any insights appreciated.

**Comment by mike-000** [comment]
Also the image is also rotated 90 degrees compared with the correctly placed one.

**Comment by loganwilliams** [comment]
Possibly related to this issue from over a year ago: https://github.com/geotiffjs/geotiff.js/issues/313

**Comment by ahocevar** [comment]
> Possibly related to this issue from over a year ago: [geotiffjs/geotiff.js#313](https://github.com/geotiffjs/geotiff.js/issues/313)

I don't think that's the problem. If the GeoTIFF image in question uses a projection with an axis order different than `enu`, and is encoded with that flipped axis order, the problem is that OpenLayers always assumes x/y axis order. To display such a GeoTIFF properly, an extra raster reprojection step would be necessary, with a transform that just swaps x and y.

**Comment by mike-000** [comment]
@ahocevar The GeoTIFF is misplaced in the reported UTM projection but reasonably close to the expected position, rotated and slightly smaller than expected.  Swapping axes would make it much more displaced.

**Comment by mike-000** [comment]
After checking the two outputs more thoroughly the top left corner as seen in OpenLayers is in the correct position - the image is rotated slightly less then 90 degrees around that point (which should be at top right when corrected) and is also downscaled.  It does seem related to https://github.com/geotiffjs/geotiff.js/issues/313

**Comment by loganwilliams** [comment]
Fixing the calculation of the resolution in Geotiff.js (I'll file a PR for Geotiff.js soon) corrected the error in size, but it is still rendered in an incorrect position and rotation. I think that this problem is on the OpenLayers side, which would need to make use of the transformation properties of the TIFF in the rendering of the image.

**Comment by loganwilliams** [comment]
The changes to geotiff.js are in this PR: https://github.com/geotiffjs/geotiff.js/pull/403

**Comment by mike-000** [comment]
Your example link is no longer working.  Are you are to recreate it?

To support rotation I think the tilegrid would need to be considered to be in a custom rotated or skewed projection derived from the reported projection similar to the images in #12601.  If the reported projection needs a proj4 lookup as in https://openlayers.org/en/latest/examples/cog-projection.html some changes to proj4 registration process would be needed as transforms between the rotated projection and any other possible view projections could not be defined until then.

**Comment by carmenmarquez** [comment]
It happens the same to me https://github.com/openlayers/openlayers/issues/15370

**Comment by mike-000** [comment]
A fix is definitely possible, there is some discussion about and links to Umbra COGs in https://github.com/stac-utils/stac-layer/issues/61.  While https://github.com/geotiffjs/geotiff.js/pull/403 will fix the scale issue, it is necessary to consider the tile grid to be in a rotated projection for it to be positioned correctly.  A recent change to geotiff.js https://github.com/geotiffjs/geotiff.js/pull/361 does the opposite of that, and it now returning the larger bounding box which encloses the rotated tile grid in an unrotated projection, which is of no use to OpenLayers (and probably of limited use to Leaflet) so OpenLayers will need to apply the old method directly.  Currently to work correctly the unrotated projection must be defined before the rotated one, and there seems to be a problem with a reverse transform, so this example simply reprojects the base layer to the COG's rotated projection https://codesandbox.io/s/cog-forked-dl795h?file=/main.js
