### ISSUE TITLE
Reprojection artifacts with certain GeoTIFFs that have overviews

### ISSUE THREAD

**Issue by malaretv** [openlayers/openlayers#15331]
We're seeing visual artifacts in the form of gridlines when reprojecting certain geotiffs.
It seems to happen with geotiffs whose overview dimensions aren't cleanly divisible.

<img width="531" alt="Screenshot 2023-11-14 at 10 43 03 AM" src="https://github.com/openlayers/openlayers/assets/381932/8d9884c5-afcc-4d5a-aed6-5491944b577f">

**Steps to reproduce the behavior**
1. Go to https://codesandbox.io/s/cog-forked-pznhqf?file=/main.js
2. Notice the grid lines when using viewing this EPSG:4326 geotiff in EPSG:3857

The example above using a modis geotiff from here copied to one of our servers:
https://modis-vi-nasa.s3-us-west-2.amazonaws.com/MOD13A1.006/2018.01.01.tif

its overview dimensions reported by `gdalinfo` are:
```
29820x11617, 14910x5809, 7455x2905, 3728x1453, 1864x727, 932x364, 466x182
```
**Expected behavior**
No visual artifacts like in https://openlayers.org/en/latest/examples/geotiff-reprojection.html

**Comment by mike-000** [comment]
Which browser are you using?  Your example works as expected on Windows with Chrome and Edge, but I see the lines with Firefox.

**Comment by malaretv** [comment]
I'm on MacOS Apple Silicon and seeing the artifacts on:
Safari 17.0
Chrome 119.0
Firefox 118.0.2

Coworkers also tried:

Windows 7 - Chrome, Firefox, and Edge all show the artifacts

Ubuntu 20.04 - Firefox shows the artifacts. Chrome seems to work as expected!

**Comment by mike-000** [comment]
It is not specific to GeoTIFF, I can reproduce the lines in Firefox using data tiles with the same tile grid and sizes

![image](https://github.com/openlayers/openlayers/assets/49240900/d14bed17-7b84-4aa5-89a8-4895280ba59e)

**Comment by mike-000** [comment]
I can remove those lines by ensuring tiles are aligned to whole pixels during reprojection to avoid unwanted interpolation which is only expected at the edges of the tile grid where the resulting corrupted data is removed.  This patched version fixes the problem on Firefox and Android Chrome https://codesandbox.io/s/cog-forked-n6p687?file=/main.js  Are you able to test with other systems?

**Comment by malaretv** [comment]
@mike-000 amazing!

Looking good here on MacOS M1 seems fixed in all the browsers that were having issues before:
Safari 17.0
Chrome 119.0
Firefox 118.0.2

Don't have access systems other than this at the moment
