### ISSUE TITLE
style renderer context.rotate

### ISSUE THREAD

**Issue by zj91zj** [openlayers/openlayers#15347]
https://codesandbox.io/s/style-renderer-forked-r45p68?file=/main.js:1314-1351
I have a similar code to https://codesandbox.io/s/style-renderer-forked-r45p68?file=/main.js:1314-1351, then I have to rotate image 90degree, in  style renderer funtion. How can I do? thanks

**Comment by mike-000** [comment]
You need to translate the context to the position around which you wish to rotate, then rotate, and draw relative to that position.  The width and height to be drawn also needs recalculating to accommodate the rotation. https://codesandbox.io/s/style-renderer-forked-zj54nq?file=/main.js

**Comment by zj91zj** [comment]
i got it , thanks.
