### ISSUE TITLE
Build issue involving @babel/parser

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/openlayers#15358]
Something in the webpack/babel ecosystem has troubles with OpenLayers source. Seen with 8.1.0 but also 7.5.2.

```
ERROR in ./node_modules/ol/View.js 492:17
Module parse failed: Unexpected token (492:17)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|        * @param {number} value Value.
|        * @return {number} Resolution.
>        */function(value){const resolution=maxResolution/Math.pow(power,value*max);return resolution;};}/**
|    * Get the view rotation.
|    * @return {number} The rotation of the view in radians.
 @ ./node_modules/ol/Map.js 3:832-860 257:101-105 257:164-168 583:45-49 583:121-125 583:192-196 598:434-438 598:456-460
 @ ../../../../tmp/broccoli-319713Y10kuPxroEZW/cache-218-webpack_bundler_ember_auto_import_webpack/app.cjs
```

Currently trying to figure out the root cause but this started to occur after a regeneration of a lockfile, so it's a minor/patch level dependency upgrade somewhere in this tooling.

**Comment by ahocevar** [comment]
Interesting. Can you provide a reproduction repository, @bjornharrtell ? Thanks in advance.

**Comment by bjornharrtell** [comment]
Here is one https://github.com/bjornharrtell/ol-issue-15358. Unfortunately it is deep rabbit hole due to ember. Perhaps it's possible to produce a more lean reproduction.

**Comment by bjornharrtell** [comment]
Tried to make minimal reproduction at https://github.com/bjornharrtell/ol-issue-15358-2 but can't reproduce yet so perhaps this is a problem in the ember toolchain.

**Comment by ahocevar** [comment]
I spent some time on this now too, without any further insights. I'm pretty sure this is a problem with the ember toolchain, probably something in broccoli or ember-auto-import. There is a way to make the error messages go away, but that's by not using babel for ol:

In `ember-cli-build.js`:
```js
let app = new EmberApp(defaults, {
  autoImport: {
    skipBabel: [
      {
        package: 'ol',
        semverRange: '*',
      },
    ],
  },
});
```

**Comment by ahocevar** [comment]
I was able to track this down to a problem in @babel/parser: https://github.com/babel/babel/issues/16111. An example from `ol/View.js`:
```js
  /**
   * Return a function that returns a value between 0 and 1 for a
   * resolution. Exponential scaling is assumed.
   * @param {number} [power] Power.
   * @return {function(number): number} Resolution for value function.
   */
  getResolutionForValueFunction(power) {
    power = power || 2;
    const maxResolution = this.getConstrainedResolution(this.maxResolution_);
    const minResolution = this.minResolution_;
    const max = Math.log(maxResolution / minResolution) / Math.log(power);
    return (
      /**
       * @param {number} value Value.
       * @return {number} Resolution.
       */
      function (value) {
        const resolution = maxResolution / Math.pow(power, value * max);
        return resolution;
      }
    );
  }
```
The parentheses after `return` get lost in the AST, and babel complains about the resulting code:
```js
getValueForResolutionFunction(power){const logPower=Math.log(power||2);const maxResolution=this.getConstrainedResolution(this.maxResolution_);const minResolution=this.minResolution_;const max=Math.log(maxResolution/minResolution)/logPower;return/**
       * @param {number} resolution Resolution.
       * @return {number} Value.
       */function(resolution){const value=Math.log(maxResolution/resolution)/logPower/max;return value;};}
```

**Comment by bjornharrtell** [comment]
That's some great detective work @ahocevar, thank you.

**Comment by bjornharrtell** [comment]
Resolved in @babel/generator, see https://github.com/babel/babel/issues/16111#issuecomment-1833493585. I will close this as no longer relevant.
