### ISSUE TITLE
How to set the zIndex of the overlay？

### ISSUE THREAD

**Issue by tanhh326** [openlayers/openlayers#15357]

**Comment by RobQuincey-DC** [comment]
Example: https://openlayers.org/en/latest/examples/layer-z-index.html

API docs: https://openlayers.org/en/latest/apidoc/module-ol_layer_Layer-Layer.html#setZIndex

For future reference, you are better off asking for help from the community on StackOverflow - https://stackoverflow.com/questions/tagged/openlayers

**Comment by tanhh326** [comment]
Overlay is not a subclass of layer

**Comment by RobQuincey-DC** [comment]
Oh I see, I thought you meant layer. An overlay is just a HTML element so can you just use CSS `z-index` on the element

**Comment by tanhh326** [comment]
![image](https://github.com/openlayers/openlayers/assets/82007768/8e309e84-818f-43fa-a1d9-1e1fba636d5a)

But the `overlay` nodes are all wrapped in a built-in element, and I can only set the external `div` `css z-index` to achieve this

**Comment by ahocevar** [comment]
I'd be interested to hear more about your use case, and why do you want to set a `z-index`. Maybe what you want is a vector layer with `Point` geometry features?

Overlays appear in the order they were added to the map. But @RobQuincey-DC is right, you can use pure css. Just configure the overlay with a custom `className`, and set a z-index in the css for that class.

**Comment by tanhh326** [comment]
Sorry, I read it wrong, it's the className property of overlay.
