### ISSUE TITLE
Script crashes when on drawing LineString from existing coordinates

### ISSUE THREAD

**Issue by moduld** [openlayers/openlayers#15367]
**Describe the bug**
Hello.
I try to draw a line that has only origin and destination. So I set the maxPoints : 2 (for options of the Draw class). 
But when I try to draw a line based on existing coordinates, I get the error ERROR TypeError: Cannot read properties of null (reading 'getGeometry'). 

ERROR TypeError: Cannot read properties of null (reading 'getGeometry')
    at Draw.modifyDrawing_ (Draw.js:1522:42)
    at Draw.appendCoordinates (Draw.js:1787:10)

**To Reproduce**
1. Go to this example https://codesandbox.io/p/sandbox/draw-and-modify-features-cxz3dk?file=%2Fmain.js
2. Replace the addInteractions function by the code below:

function addInteractions() {
  draw = new Draw({
    source: source,
    type: typeSelect.value,
    maxPoints: 2,
  });
  map.addInteraction(draw);
  snap = new Snap({source: source});
  map.addInteraction(snap);
  draw.appendCoordinates([
    [
        -12526802.69811565,
        5223970.689581122
    ],
    [
        -10985575.684457522,
        5247452.234244971
    ]
])
}

3. Select Geometry type - LineString
4. Open the browser console and observe errors.

**Expected behavior**
Script shouldn't crash

**Comment by ahocevar** [comment]
You don‘t have a geometry yet to append to, right? This is why you get an error.

**Comment by moduld** [comment]
Sorry, I didn't understand your thoughts. I need to restore a line from existing coordinates with possibility to modufy the points. I create a new Draw and use it's method appendCoordinates. The Modify model doesn't have any methods to set points outside.

**Comment by moduld** [comment]
How can I use the extent for my purposes? Is there any example?

**Comment by ahocevar** [comment]
Try this:
```js
    const feature = new Feature(
      new LineString([
        [-12526802.69811565, 5223970.689581122],
        [-10985575.684457522, 5247452.234244971],
      ]),
    );
    source.addFeature(feature);
    draw.extend(feature);
```

**Comment by moduld** [comment]
Yes, this workaround works. 
But would be great to change the behavior of the Draw class. So if we have already created Draw class with type: LineString and maxPoints e.g. 2 , and we call appendCoordinates method of the class, it should automaticaly create the Feature of LineString.
Anyway thank you for your help!

**Comment by ahocevar** [comment]
@moduld I don't understand what you'd expect: when you have a Draw interaction with `maxPoints: 2` and want to `appendCoordinates()` with 2 points. you're already done drawing. Why use a Draw interaction for that in the first place?

**Comment by moduld** [comment]
I expect it becase currently the 'drawend' event fires only when the maxPoints is set. So I supposed that there is a comparison logic that compares existing coordinates length with the maxPoints and if the values are equals - creates the LineString and adds it to the source.
Also I it's enough to add only the Feature of LineString to the source to make it work. No need to extend the Draw.

**Comment by ahocevar** [comment]
I created #15371 to fix this issue.

@moduld Still not sure what you're trying to achieve, but the use case you're describing sounds like you'd be better off just creating a feature and adding it to the source, without a Draw interaction involved:
```js
const feature = new Feature(
      new LineString([
        [-12526802.69811565, 5223970.689581122],
        [-10985575.684457522, 5247452.234244971],
      ]),
    );
    source.addFeature(feature);
```
