### ISSUE TITLE
Layer group opacity not applied to vector tile labels

### ISSUE THREAD

**Issue by silvester-pari** [openlayers/openlayers#15362]
**Describe the bug**
When changing the opacity of a layer group using `setOpacity()`, it doesn't seem to affect labels rendered for vector tile layers within that group. Changing the opacity of the layer directly does indeed produce the expected outcome. Doing the same for vector layers works as expected. This only seems to be a problem for labels, since e.g. the `fill-color` behaves correctly.

**To Reproduce**
1. Go to CodeSandbox https://slg36z.csb.app
2. Change the opacity of `vector` and `vectortile` sliders, it should fade out/in the labels of the corresponding layers
3. Change the `group` slider, it only changes opacity of the `vector` layer labels, while the `vectortile` labels stay unaffected

**Expected behavior**
Changing the group opacity should affect all child layers, including labels of vector tiles.

**Comment by ahocevar** [comment]
Thanks for reporting this, @silvester-pari. I created #15365 to fix this.
