### ISSUE TITLE
WMTS Capabilities parser don't supports BoundingBox in Layer node

### ISSUE THREAD

**Issue by ltshb** [openlayers/openlayers#15363]
**Describe the bug**
Some WMTS server uses the `BoundingBox` instead of `WGS84‌Bounding‌Box` on the `Layer` node but the ol/format/WMTSCapabilites parser ignore `BoundingBox`. `BoundingBox` is valid as specified in the OGC standard.

**To Reproduce**

Here is an example of a server that uses `BoundingBox`

https://wmts.geo.bs.ch/1.0.0/WMTSCapabilities.xml

Using the answer of this server with the `ol/format/WMTSCapabilities`, the `BoundingBox` of the layers is then missing the parsed results.

**Expected behavior**
Also parse the `BoundingBox` as specified in the OGC Standard.

**Comment by shimoncohen** [comment]
@ltshb Was this issue fully resolved? :)

**Comment by ahocevar** [comment]
Yes, that should be fully resolved. Closing.
