### ISSUE TITLE
Document that flat ColorExpression can be 'none'

### ISSUE THREAD

**Issue by StefanBrand** [openlayers/openlayers#15387]
**Describe the bug**
The docs don't give an indication that fill and stroke can be set to the special string `'none'`. Behaviour is implemented in:

https://github.com/openlayers/openlayers/blob/3fe9f3661b1ed431e549538842f67a846e908db3/src/ol/render/canvas/style.js#L318

https://github.com/openlayers/openlayers/blob/3fe9f3661b1ed431e549538842f67a846e908db3/src/ol/render/canvas/style.js#L387

**Context**

This is relevant because the `case` [flat expression](https://openlayers.org/en/latest/apidoc/module-ol_expr_expression.html#~Expression) requires a fallback value. The fallback cannot be left out so in order to avoid a color in unspecified cases, `'none'` must be given as a fallback value.

**Comment by tschaub** [comment]
Does `transparent` work for your use case?

I agree we should add dice to clarify when to use which.

**Comment by StefanBrand** [comment]
Yes, `transparent` achieves the same result, thank you!

```json
        {
          "filter": ["!", ["!", ["get", "prop"]]],
          "style": {
            "fill-color": [
              "match",
              ["get", "prop"],
              0,
              "#ffffff",
              1,
              "#ffffcc",
              2,
              "#c2e699",
              3,
              "#78c679",
              4,
              "#31a354",
              5,
              "#006837",
              "transparent"
            ]
          }
        }

```

![image](https://github.com/openlayers/openlayers/assets/8948865/fc18e7ac-c160-4c85-a039-3f4d745a3e9b)
