### ISSUE TITLE
ol/webgl is prepending style match statement to icon-src value

### ISSUE THREAD

**Issue by timkeane** [openlayers/openlayers#15395]
**Describe the bug**
ol/webgl is prepending style match statement to icon-src value.

Rendering fails with the following error:

Helper.js:
WebGL: INVALID_VALUE: texImage2D: bad image data

GET http://localhost:5173/match,get,Enforceable_Commitment,Y,data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2248%22%20height%3D%2248%22%20viewBox%3D%220%200%2048%2048%22%20%3E%3Ccircle%20fill%3D%22%22%20stroke%3D%22%23000%22%20stroke-width%3D%223%22%20cx%3D%2224%22%20cy%3D%2224%22%20r%3D%2219%22%2F%3E%3Ccircle%20fill%3D%22%23008450%22%20stroke%3D%22%23fff%22%20stroke-width%3D%223%22%20cx%3D%2224%22%20cy%3D%2224%22%20r%3D%2216%22%2F%3E%3Cpath%20fill%3D%22%23fff%22%20transform%3D%22translate(12%2C%2012)%22%20d%3D%22M20.285%202l-11.285%2011.567-5.286-5.011-3.714%203.716%209%208.728%2015-15.285z%22%2F%3E%3C%2Fsvg%3E,N,data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2248%22%20height%3D%2248%22%20viewBox%3D%220%200%2048%2048%22%20%3E%3Ccircle%20fill%3D%22%22%20stroke%3D%22%23000%22%20stroke-width%3D%223%22%20cx%3D%2224%22%20cy%3D%2224%22%20r%3D%2219%22%2F%3E%3Ccircle%20fill%3D%22%23CC0202%22%20stroke%3D%22%23fff%22%20stroke-width%3D%223%22%20cx%3D%2224%22%20cy%3D%2224%22%20r%3D%2216%22%2F%3E%3Cpath%20fill%3D%22%23fff%22%20transform%3D%22translate(13.2%2C%2013.2)%20scale(0.9%200.9)%22%20d%3D%22M24%2020.188l-8.315-8.209%208.2-8.282-3.697-3.697-8.212%208.318-8.31-8.203-3.666%203.666%208.321%208.24-8.206%208.313%203.666%203.666%208.237-8.318%208.285%208.203z%22%2F%3E%3C%2Fsvg%3E,data:image/svg+xml;utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2248%22%20height%3D%2248%22%20viewBox%3D%220%200%2048%2048%22%20%3E%3C%2Fsvg%3E 404 (Not Found)

**To Reproduce**
Run example code from https://github.com/timkeane/ol-web-gl-issue

**Expected behavior**
The icon source should load from the provided data URI

**Comment by jahow** [comment]
@timkeane thanks for your report, unfortunately the style format described [here](https://openlayers.org/en/latest/apidoc/module-ol_style_flat.html) isn't yet supported by the WebGL renderers (including the WebGLPoints) class. This is still a work-in-progress, WebGL renderers will hopefully support the "flat" styles very soon.

In the meantime, please refer to examples such as [this one](https://openlayers.org/en/latest/examples/filter-points-webgl.html) for filtering in webgl.

**Comment by timkeane** [comment]
@mike-000 provided the solution
