### ISSUE TITLE
Option to crop GeoTIFF source tiles to tile grid extent not respected if reprojected

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#15417]
**Describe the bug**
This can be seen in the example for #15402 if non-zero nodata value is specified
![image](https://github.com/openlayers/openlayers/assets/49240900/a4cd6239-76b7-418c-85a4-af35fbbf57d5)
and possibly with other example sources if they are reprojected.

**Expected behavior**
Without reprojection the misleadingly named `wrapX` option in GeoTIFF is used to crop the output to the tile grid extent on both the x and y axes regardless of the source projection being global.  This is unrelated to what reprojection expects `wrapX` to mean - whether the output will be repeated on adjacent worlds on the x axis when reprojected to a global projection.  While it would be possible for ReprojDataTile to use this to crop the input to reprojection, with a major release pending can this be renamed to something more appropriate, as it should be possible to both crop to the original local extent and repeat in a global projection.

**Comment by ahocevar** [comment]
@mike-000 Please help me understand the problem. Is the goal to clip the GeoTIFF to the area marked red?

![289278743-a4cd6239-76b7-418c-85a4-af35fbbf57d5](https://github.com/openlayers/openlayers/assets/211514/3622d260-d7ea-4ed4-ad27-a7c5748f4eae)

I assume the area marked red is (or should be) the source extent?

**Comment by mike-000** [comment]
> I assume the area marked red is (or should be) the source extent?

Yes, the source tile grid extent, as happens without reprojection (i.e. in a rotated world) https://jsfiddle.net/nrxpjhqv/

**Comment by ahocevar** [comment]
Why do you keep talking about a source tile grid extent? The source extent does not have to align with tile boundaries.
