### ISSUE TITLE
error if GeoTiffs origin is set to the lower left corner

### ISSUE THREAD

**Issue by maxschmi** [openlayers/openlayers#15428]
**Describe the bug**
I create several GeoTiffs in python, where the origin was set to the lower left corner. The result in OpenLayers was, that all my cells had 0 as value.
When I retranspose my GeoTiff, so that the upper left corner is the origin, all is represented as expected.

**To Reproduce**
1. Download the test setup with a given GeoTiff: [tif_test.zip](https://github.com/openlayers/openlayers/files/13672169/tif_test.zip)
3. extract the content an cd into th directory
4. Install the npm packages: `npm i`
5. Start the vite server `npm start`
6. open a Browser and see the black image. If you open the console and click on a pixel, you will see the value

**Expected behavior**
The tif_layer should show data between 10-360 in greyscale, no matter how the origin is defined. At least as long as the pixel size is then set to (1,1) and not (1,-1)

**Comment by mike-000** [comment]
The data is being rendered in the wrong position, and with `wrapX: false` limiting the output to the tilegrid extent you will not see it https://codesandbox.io/s/cog-forked-vvsm5p?file=/main.js

**Comment by mike-000** [comment]
This is probably due to https://github.com/geotiffjs/geotiff.js/pull/361  If I use the build from #15402 which uses the original bounding box algorithm it renders inside the tilegrid extent https://jsfiddle.net/17az2dmb/ although your proj4 definition may not be correct.  See also https://github.com/geotiffjs/geotiff.js/pull/414

**Comment by mike-000** [comment]
The proj4 definition is correct, it looks like the ModelTransform must be always be applied, as it can flip the projection as well as rotate or skew it https://jsfiddle.net/fcb4nrtm/

**Comment by mike-000** [comment]
You had a normal top left origin with a ModelTransformation flipping the grid.  I have updated #15402 to handle this as well as rotation or skew specified by ModelTransformation.
