### ISSUE TITLE
Empty Encryption Key

### ISSUE THREAD

**Issue by swetha8612** [openlayers/openlayers#15431]
**Is your feature request related to a problem? Please describe.**
As part of our company's security policy, we run all our application through fortify scan. Fortify scan raised a flag in Tile.js file where  empty key has been used. It is suggesting not to use empty encryption key. Could you please suggest something. Thank you.

**Describe the solution you'd like**
As per fortify, "Encryption keys should never be empty and should be obfuscated and managed in an external source."

**Comment by fredj** [comment]
This is a false positive, `key` is not an encryption key

**Comment by swetha8612** [comment]
Thank you for confirming.
