### ISSUE TITLE
Quickstart using npm create app fails to install StadiaMaps

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [openlayers/openlayers#15452]
**Describe the bug**

NodeJS install from node-v20.10.0.pkg

$ npm --version
10.2.3

Following [https://openlayers.org/doc/quickstart.html](https://openlayers.org/doc/quickstart.html) fails to install _/my-app/node_modules/ol/source/StadiaMaps.js_ yet "npm install ol" does install it.

**To Reproduce**
Follow steps at [https://openlayers.org/doc/quickstart.html](https://openlayers.org/doc/quickstart.html)

**Expected behavior**

StadiaMaps.js should install.

**Comment by ahocevar** [comment]
This is because the underlying templates had a fixed version (ol@7.x) in its lockfile. I just fixed the templates. If you retry now, the latest version of the ol package, which contains Stadia Maps, will be instlaled.

**Comment by tschaub** [comment]
Please reopen if this continues to be a problem.
