### ISSUE TITLE
loss of performance vector tile with lots of features

### ISSUE THREAD

**Issue by fabienwnklr** [openlayers/openlayers#15458]
When i add vector tile and it containing lot of data, `zoom` and `panning` lagging, see example here :
[codesandbox](https://codesandbox.io/p/devbox/style-expressions-forked-fxlzwh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqfbolcp0006356hselcr07q%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqfbolcp0002356h2nwpkjb2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqfbolcp0003356hy41qcrgl%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqfbolcp0005356hwm1o7w6h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B46.80781759%252C53.19218241%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqfbolcp0002356h2nwpkjb2%2522%253A%257B%2522id%2522%253A%2522clqfbolcp0002356h2nwpkjb2%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqw476sn0002356hoei9j64y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A46%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A46%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqw476sn0002356hoei9j64y%2522%257D%252C%2522clqfbolcp0005356hwm1o7w6h%2522%253A%257B%2522id%2522%253A%2522clqfbolcp0005356hwm1o7w6h%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clqw1644t006d356ht9mxg4t6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqw1644t006d356ht9mxg4t6%2522%257D%252C%2522clqfbolcp0003356hy41qcrgl%2522%253A%257B%2522id%2522%253A%2522clqfbolcp0003356hy41qcrgl%2522%252C%2522activeTabId%2522%253A%2522clqw16h80004n356h3t1wtt25%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqggxfsq00tv356glepoabxg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqggxfuf0016eght2hf2c1o0%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clqw16h80004n356h3t1wtt25%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A21.614583333333343%257D)

maybe i do semething wrong ? Thanks !

**Expected behavior**
For example, [this website](https://panoramax.ign.fr/#focus=map&map=15.35/43.492244/-1.471196&pic=659e542a-2ae5-443e-94e6-149c6b0793d9&speed=250&theme=default&xyz=56.81/-17.41/30) use same endpoint but they using `maplibre` (no lag here..)

**Comment by ahocevar** [comment]
The flat styles you're using in that examples are not yet optimized for a lot of data. Try using [ol-mapbox-style](https://npmjs.com/package/ol-mapbox-style). It has the advantage of supporting the same Mapbox Style JSONs that MapLibre uses. If that's not what you want, use classic styles (ol/style/Style) with style functions.

**Comment by fabienwnklr** [comment]
thanks for answer, but i need to use conditionnal logic for style , so i try to use function (or style expressions) and if i do something like this, lag again .. [codesandbox](https://codesandbox.io/p/devbox/vector-tile-ol-8-fxlzwh?file=%2Fmain.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqfbolcp0006356hselcr07q%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqfbolcp0002356h2nwpkjb2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqwgl5dq01f2356hw7yunqmn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqfbolcp0005356hwm1o7w6h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B46.80781759%252C53.19218241%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqfbolcp0002356h2nwpkjb2%2522%253A%257B%2522id%2522%253A%2522clqfbolcp0002356h2nwpkjb2%2522%252C%2522activeTabId%2522%253A%2522clqw476sn0002356hoei9j64y%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqw476sn0002356hoei9j64y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A46%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A46%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clqwgkk0f00xy356hwnjvszn6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clqfbolcp0005356hwm1o7w6h%2522%253A%257B%2522id%2522%253A%2522clqfbolcp0005356hwm1o7w6h%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clqwgnn8k01nw356h6oh9rlfs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqwgnn8k01nw356h6oh9rlfs%2522%257D%252C%2522clqwgl5dq01f2356hw7yunqmn%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwgl34001ez356hheqgx7tp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqwgl5ms0009edjx5dyiamqx%2522%257D%255D%252C%2522id%2522%253A%2522clqwgl5dq01f2356hw7yunqmn%2522%252C%2522activeTabId%2522%253A%2522clqwgl34001ez356hheqgx7tp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A21.614583333333343%257D)

**Comment by ahocevar** [comment]
Your second example (with classic styles) creates a new Circle style for every call of the style function. You should cache that Circle style, or pre-create one with each color you want.

**Comment by fabienwnklr** [comment]
yup, i try `ol-mapbox-style` and it's clearly more efficiant, the only negative point that i don't have any json style, so i need to create it.

Thank's for you'r answer !
