### ISSUE TITLE
Option to integrate Google Maps Tiles (using the new Map Tiles API recently released, no hacks or licensing issues)

### ISSUE THREAD

**Issue by ShelleyLake** [openlayers/openlayers#15461]
Dear team,
I noticed that Google recently released an API to get Google Maps Tiles, using an API-Key and thus **without** hacks or other workarounds that directly access their servers, thus violating their license.

[Map Tiles API overview](https://developers.google.com/maps/documentation/tile/overview)

That is why I wanted to ask if it would be possible to integrate this service as is already done with Bing Maps Tiles and other providers.

From the documentation I understand that, once the API-Key is obtained, the procedure consists of a POST-type request that returns a SESSION_TOKEN, to be used in subsequent requests to the Tiles server.

[Satellite Tiles](https://developers.google.com/maps/documentation/tile/satellite)

```
curl -X POST -d '{
  "mapType": "satellite",
  "language": "de-DE",
  "region": "DE"
}' \
-H 'Content-Type: application/json' \
"https://tile.googleapis.com/v1/createSession?key=YOUR_API_KEY"
```

`curl "https://tile.googleapis.com/v1/2dtiles/z/x/y?session=YOUR_SESSION_TOKEN&key=YOUR_API_KEY"`

Thank you in advance.

J.

**Comment by tschaub** [comment]
I put up a draft pull request adding a new Google source: https://github.com/openlayers/openlayers/pull/15465

As mentioned there, we don't currently have a Google billing account for OpenLayers, so can't create a key for the examples.  I'll look into any options they might have that wouldn't incur costs for the project (may not be possible).

**Comment by ShelleyLake** [comment]
@tschaub 
Thank you very much for your interest.
I am a small hobby developer and have registered an API-Key by providing a credit card.
Google has a usage limit within which the card is not charged. For my (limited) needs, in several years of using the Key for the Google-Maps-Javascript-API-V3 version, I have never paid a penny.
Once again, thanks for your interest.
J.
