### ISSUE TITLE
Apple iPhone 5s, iOS 12.5.7, cannot open OpenLayers V8 examples.

### ISSUE THREAD

**Issue by MADAO-Chen** [openlayers/openlayers#15467]
Apple iPhone 5s, iOS 12.5.7, cannot open OpenLayers V8 examples.
![WechatIMG11](https://github.com/openlayers/openlayers/assets/57648957/f859a95e-642e-4bce-9049-143e7688b884)
![WechatIMG12](https://github.com/openlayers/openlayers/assets/57648957/f4dc7964-cbab-4a73-a908-cfa548bd7157)
![WechatIMG13](https://github.com/openlayers/openlayers/assets/57648957/78d8a244-1529-45ff-8716-a1042c5e8474)

IOS:12.5.7
safari:605.1.15
openlayers:v8

**Expected behavior**
Can be used normally

**Comment by jahow** [comment]
Could reproduce on an iphone 7 with iOS 12, this error shows up:
![image](https://github.com/openlayers/openlayers/assets/10629150/bbeff94d-ed4f-4b8a-8632-c81cc7fe5761)

This apparently comes the optional chaining operator `?.` from this line:
https://github.com/colorjs/color-parse/blob/6d0f7c1009f451948aa92c055371805174a7e381/index.js#L146

Indeed this operator is only supported from iOS 13+, see: https://caniuse.com/mdn-javascript_operators_optional_chaining

**Comment by ahocevar** [comment]
Nonetheless, if you're using OpenLayers in your own application, you can transpile your code if you need to target older browsers.

For the examples on openlayers.org, I think we'll stick with untranspiled code. The iOS/Safari version in question has a market share of 0.27 %, according to browsersl.ist.

**Comment by MADAO-Chen** [comment]
Can't find variable: ResizeObserver at Map.js 
npm install resize-observer
import { install } from 'resize-observer';

if (!window.ResizeObserver) install();
fix
