### ISSUE TITLE
GeoJSON.readFeatures throws error when coordinates are empty (since 8.2)

### ISSUE THREAD

**Issue by GastonZalba** [openlayers/openlayers#15464]
**Describe the bug**
In Open Layer 8.2, the method readFeatures from GeoJSON throws error if a LineString has empty coordinates. The error was introduced in 4c7bd4a1e98c98ff5dab7479061c543520166e4d. The error message is: 
```
TypeError: Cannot read properties of undefined (reading 'length')
    at GeoJSON.js:407:47
    at xw (GeoJSON.js:315:18)
    at ww.readFeatureFromObject (GeoJSON.js:125:22)
    at ww.readFeaturesFromObject (GeoJSON.js:175:36)
    at ww.readFeatures (JSONFeature.js:53:17)
```

**To Reproduce**
```js
const exampleData =  {
    type: 'FeatureCollection',
    features: [
        {
            type: 'Feature',
            geometry: {
                type: 'LineString',
                coordinates: []
            },
            properties: {}
        }
    ]
};

const features = new GeoJSON().readFeatures(exampleData);
```

**Expected behavior**
Parse the feature successfully as previous versions (returning an feature with an empty geometry).

**Comment by ahocevar** [comment]
This has been fixed with #15388 already. Please `npm install ol@dev` until the latest version contains this fix.
