### ISSUE TITLE
How can a VectorSource containing regular features return an array of render features?

### ISSUE THREAD

**Issue by sebakerckhof** [openlayers/openlayers#15470]
I'm upgrading from ol 8.1.0 to 8.2.0 and saw a lot of types have changed due to the introduction of render features.
However, one thing is not clear to me, if I have a source of type `VectorSource<Feature>`, then I can only add and remove regular features (looking at the signatures of `addFeature` and so on). But when I call `getFeatureById` on that source the return type is `Feature<Geometry> or RenderFeature[]`. Is this the intended return type? And how can this return a render feature if only regular features can be added to the source?

**Comment by ahocevar** [comment]
Yes, that's intended, and happens when the GeoJSON format is configured with `ol/render/Feature` as `featureClass`. And if you upgrade to ol@dev you'll get a fix that determines the correct type depending on which `featureClass` the GeoJSON format was configured with.

**Comment by sebakerckhof** [comment]
Clear, thanks
