### ISSUE TITLE
Hit detection when overlays and feature positions overlap.

### ISSUE THREAD

**Issue by lawyer888** [openlayers/openlayers#15479]
**Is your feature request related to a problem? Please describe.**

describing involves the interaction between overlays and features within the same layer. Specifically, when a feature passes through an overlay and the mouse hovers over the overlay, the feature is selected instead of the overlay.

In the scenario of drawing a line on the map using LineString or MultiLineString, there is a need to overlay icons representing the features or turning points of the line segments at both ends. These icons can be adjusted freely in terms of size and position. However, a problem arises when these icons overlap with the line segment below - it becomes difficult to distinguish and interact with the icons when the coordinates of the icon overlap with the line segment.

**Describe the solution you'd like**
To address this issue, I have contributed a code snippet for detecting and determining whether the mouse is hovering over the range of the icons at the ends of the line segments. This code snippet returns a boolean value to be used as a filter in the ol/interaction/Select API, ensuring that only the icons are selected and not the lines of feature passing through them. This is an important requirement as it applies not only to icons at the ends of line segments, but also to other types of feature.

like this :  
```js
let overstation = []; // This is to listen to the mouse coordinates on the map
const nodeSelectionOperation = () => {
  let selectInteraction = new Select({
    condition: pointerMove,
    filter: (feature, layer) => {
      if (feature.getGeometry().getType() === "MultiLineString") {
        let coordinates = feature.getGeometry().getCoordinates();
        let startPoint = coordinates[0][0];
        let endPoint = coordinates[0][1];
        let segobj = new SegmentFilter();
        let resobj = segobj.lineFilter(
          startPoint,
          endPoint,
          "MultiLineString",
          overstation,
          0.0015
        );
        return resobj;
      }
    },
  });
  /* The SegmentFilter class is used to filter features that have overlays above them. 
  This is to avoid the issue where the select operation may hit the feature instead of the overlay when the mouse hovers over the overlay. */
  map.value.addInteraction(selectInteraction);
};
```

**Comment by lawyer888** [comment]
like this.....

**Comment by lawyer888** [comment]
![Uploading 20240111114200.png…]()

**Comment by ahocevar** [comment]
Before digging into details: is there any reason why you're using `Overlay`s for your icons? These could just as well be point features in a vector layer.

**Comment by lawyer888** [comment]
> Before digging into details: is there any reason why you're using `Overlay`s for your icons? These could just as well be point features in a vector layer.

In my project, there are many features, and there are complex filtering and judging requirements for the interaction of many states and data. There will be thousands of features, especially many line segments, each with different properties and statuss，and there will be requests and communication involved as well. If I put the icons into the feature system, Every time I write logic, I have to consider excluding these icons, making it difficult to avoid the integration of icon logic with features as a whole，On the other hand, the separate overlay system only has a few of nodes, Static information does not involve communication, so I can manage these overlays separately, which is relatively easy. Even if there are changes, I don't need to adjust them in the logic of the feature system.

**Comment by lawyer888** [comment]
> Before digging into details: is there any reason why you're using `Overlay`s for your icons? These could just as well be point features in a vector layer.
this is my personal opinion, but indeed using features can facilitate interaction. I just didn't consider that in cases with very limited interaction, such issues may arise. It can be considered a minor issue. For example, an icon only has one interaction, which is to click and display static information, so I didn't think much and just used it.
Besides ,I agree with what you said.

**Comment by ahocevar** [comment]
> If I put the icons into the feature system, Every time I write logic, I have to consider excluding these icons

Not if you put your icons on a separate layer and use `Layer.getFeatures(pixel)` or `Map.getFeaturesAtPixel()` with a layer filter. Then you have a clear separation. Also, there is https://www.npmjs.com/package/ol-marker-feature, if you want to combine the convenience of an Overlay with the convenience of a Feature.

But to address the issue you're encountering: all you need to do is configure the overlay with

**Comment by lawyer888** [comment]
> > If I put the icons into the feature system, Every time I write logic, I have to consider excluding these icons
> 
> Not if you put your icons on a separate layer and use `Layer.getFeatures(pixel)` or `Map.getFeaturesAtPixel()` with a layer filter. Then you have a clear separation. Also, there is https://www.npmjs.com/package/ol-marker-feature, if you want to combine the convenience of an Overlay with the convenience of a Feature.

OK, I understand. Actually, I had considered placing them on different layers before, but at the beginning of the project, I didn't think that a few icons would have a significant impact, so I didn't do that, and I didn't consider the limitations of overlays. Thank you for your response.
