### ISSUE TITLE
WebGLPoints loading point text properties does not take effect

### ISSUE THREAD

**Issue by z0aiyx** [openlayers/openlayers#15483]
I used WebGLPointsLayer to load map points, and I wanted to set descriptive text for the loaded points, but it didn't work. How do I write it to get the desired effect,Here is my code.

    let vectorSource;
    if (gras.type == "FeatureCollection") {
      vectorSource = new VectorSource({
        features: new GeoJSON().readFeatures(gras, {
          dataProjection: "EPSG:4326",
          featureProjection: view.getProjection().getCode()
        })
      });
    } else if (gras.geometryType) {
      vectorSource = new VectorSource({
        features: new EsriJSON().readFeatures(gras, {
          dataProjection: "EPSG:4326", 
          featureProjection: view.getProjection().getCode()
        })
      });
    }
    let pointsLayer = new WebGLPointsLayer({
      source: vectorSource,
      style: {
        'circle-radius': 15,
        'circle-fill-color': "#ff3f3f",
        "circle-displacement": [0,0],
        "circle-opacity": 0.95,
        "text-value": "123"
      }
    });
   map.addLayer(pointsLayer);

**Comment by jahow** [comment]
Test is not supported by WebGL vector renderers right now. AFAIK there's no funding for this evolution yet, but every contribution is welcome!

**Comment by z0aiyx** [comment]
Okay, thank you very much for your answer. I would like to ask again if I want to perform point aggregation, but can't I load it using WebGLPointsLayer,
Because it cannot display text, it cannot display how many points have been aggregated. Because I have a large number of points, using vectorLayer aggregation feels a bit sluggish. Do you have any good solutions。

**Comment by ahocevar** [comment]
@z0aiyx Maybe what you're looking for is [ol/source/Cluster](https://openlayers.org/en/latest/apidoc/module-ol_source_Cluster-Cluster.html)?

**Comment by z0aiyx** [comment]
> @z0aiyx也许您正在寻找的是[ol/source/Cluster](https://openlayers.org/en/latest/apidoc/module-ol_source_Cluster-Cluster.html)？

Yes, I am using Cluster, and this is the current implementation code.
`const source = new VectorSource({
  features: features,
});
const clusterSource = new Cluster({
  distance: parseInt(distanceInput.value, 10),
  minDistance: parseInt(minDistanceInput.value, 10),
  source: source,
});
const styleCache = {};
const clusters = new VectorLayer({
  source: clusterSource,
  style: function (feature) {
    const size = feature.get('features').length;
    let style = styleCache[size];
    if (!style) {
      style = new Style({
        image: new CircleStyle({
          radius: 10,
          stroke: new Stroke({
            color: '#fff',
          }),
          fill: new Fill({
            color: '#3399CC',
          }),
        }),
        text: new Text({
          text: size.toString(),
          fill: new Fill({
            color: '#fff',
          }),
        }),
      });
      styleCache[size] = style;
    }
    return style;
  },
});`
What I want to do now is to put the aggregated layer into WebGLPoints, but WebGLPointsLayer cannot set text and display the number of aggregated points.
`import WebGLPointsLayer from 'ol/layer/WebGLPoints.js';
const clusterSource = new Cluster({
  distance: parseInt(distanceInput.value, 10),
  minDistance: parseInt(minDistanceInput.value, 10),
  source: source,
});
const clusters = new WebGLPointsLayer({
	source: clusterSource
	style:{
		“text-value”:”200”
	}
})`

**Comment by ahocevar** [comment]
With the aggregated points, I don't think you'd notice any performance gain when using WebGL. What was your reason to use WebGL here in the first place?

**Comment by z0aiyx** [comment]
> 通过聚合点，我认为您在使用 WebGL 时不会注意到任何性能提升。您最初在这里使用 WebGL 的原因是什么？

OK, I want to load a large number of points on the map, but now it is too stuck. I want to use WebGL loading to optimize it. I think it may be the stuck animation caused by my point aggregation. I try to remove the animation. Thank you very much for your reply.

**Comment by ahocevar** [comment]
If stuck when loading, switching to WebGL rendering won't help, because loading happens before rendering. What you can try is load your data with the GeoJSON format and use `featureClass: RenderFeature` as format. This will speed up loading significantly.
