### ISSUE TITLE
Resolution Mismatch in WFS Loader with `useGeographic()` Option

### ISSUE THREAD

**Issue by JakobMiksch** [openlayers/openlayers#15489]
**Describe the Bug**
When using a custom loader for a WFS source with the `useGeographic` option, there is a mismatch between the resolution provided by the loader function and the view's resolution.

**To Reproduce**

1. Open the [CodeSandbox example](https://codesandbox.io/p/sandbox/vector-wfs-forked-77s85n).
2. Check the log statements in the developer tools for resolution discrepancies.

**Expected Behavior**
When using a loader function for a WFS source with `useGeographic`, the resolution provided by the loader function should be the same as the view's resolution.

**Comment by ahocevar** [comment]
Not really. In such a setup, the view will be in Web Mercator, which has different units per pixel than the user projection (geographic coordinates), resulting in different resolutions.

**Comment by JakobMiksch** [comment]
Alright, Thanks a lot for the clarification!
I am closing this issue.
