### ISSUE TITLE
Invalid geojson in Tooltip on Hover example

### ISSUE THREAD

**Issue by ElGerys** [openlayers/openlayers#15510]
[This geojson file](https://openlayers.org/data/vector/ecoregions.json) is either invalid or has failures according to https://www.itb.ec.europa.eu/json/geojson/upload and https://geojson.io/. Nevertheless, it works like a champ as shown in the OL examples web site (and also in my laptop with the OL example code). I just created a geojson file (multipolygon or polygon) with GDAL (ogr2ogr) and tried to reproduce the 'Tooltip on Hover' example but it is not displayed as expected (I modified the code accordingly, basically the url link for the geojson). This new geojson is valid according to both online geojson validators. Please find attached my geojson file for testing and understand if the error is on my side

**Comment by mike-000** [comment]
The example file is slightly non-compliant as it has features in Greenland and Antarctica with no properties object.  If you hover over these regions the tooltip shows "undefined".  Adding an empty properties object  `"properties": { },` to those features would make it fully compliant.  Your file works as expected with a default style in https://openlayers.org/en/latest/examples/drag-and-drop.html

**Comment by ElGerys** [comment]
Amazing, many thanks for the neat reply. Sorry for being a newbie about OL, would you mind please to take a look at the main.js and index.html files I am using here? please find them enclosed below. I basically changed colors and the line where 'ECO_NAME' has been specified, not sure what I am doing wrong and why the mb.json file is not displayed, many thanks again!
[myfiles.zip](https://github.com/openlayers/openlayers/files/14069654/myfiles.zip)

**Comment by ElGerys** [comment]
I rechecked things here and my mistake, it seems that the path to the geojson file was the problem, sorry for the noise and thanks again!
