### ISSUE TITLE
Add parameter "imageLoadFunctionAsync" for ImageWMS 

### ISSUE THREAD

**Issue by mar-mar** [openlayers/openlayers#15518]
**Is your feature request related to a problem? Please describe.**
For ImageWMS using fetch inside imageLoadFunction 
* need to execute _URL.createObjectURL_
* ignores rendering optimization using ImageBitmap 

**Describe the solution you'd like**
Add parameter for sources
imageLoadFunctionAsync: (src) => Promise<HTMLImageElement|ImageBitmap|HTMLCanvasElement|...>

If imageLoadFunctionAsync is specified, then imageLoadFunction is ignored

For ImageWMS: ImageBitmap will be possible to create inside the function imageLoadFunctionAsync (_fetch > blob > createImageBitmap(blob) > ImageWrapper.image\__)

It would also be convenient for other sources (including tile ones)

**Comment by ahocevar** [comment]
`ol/source/ImageWMS` is a bit legacy, I'm even thinking about removing it. Have you tried using `ol/source/Image` with `createLoader()` from `ol/source/wms`? That gives you the flexibility you want.

**Comment by mar-mar** [comment]
Thanks
getImageInternal was overridden from ` ol/source/ImageWMS ` (use getParams, getFeatureInfo, updateParams)
```
this.loader = {
...
  load: (image, src) => {
     this.image.setImage(image);
     return this.imageLoadFunction_(this.image, src);
  }
}
```

**Comment by mar-mar** [comment]
Right now i'ts more convenient to me to use `ol/source/ImageWMS`
In the future I will try to switch to a `ol/source/Image`

**Comment by ahocevar** [comment]
So can we close this?
