### ISSUE TITLE
draw interaction issue of snapping to vertices

### ISSUE THREAD

**Issue by sharsmita** [openlayers/openlayers#15526]
**Describe the bug**
When drawing a polygon with draw interaction it tries to snap to the nearest vertices and not able to select a point close to the vertices. Is there a way to stop the snapping. It is there in the openalyers example link as well. attaching video.
**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/draw-and-modify-features.html'
2. Click on 'geometry type Polygon'
3. draw a polygon with more than three points and select a point close to a vertices. 

**Expected behavior**
The user should be able to select a point closer to one of the vertices in a polygon.
[openlayers_draw.zip](https://github.com/openlayers/openlayers/files/14127665/openlayers_draw.zip)

**Comment by ahocevar** [comment]
You can remove the `Snap` interaction from the example (click the "Edit" button at the top right), then there won't be any snapping.

**Comment by sharsmita** [comment]
Hi, @ahocevar Thanks for reverting to my query. I have an example where I am not using the snap interaction and it still does snap it to the closest vertices. Please have a look at this 
[openlayers_demo.zip](https://github.com/openlayers/openlayers/files/14139362/openlayers_demo.zip)

**Comment by ahocevar** [comment]
@sharsmita That's a different issue, and only affects the first vertex of the polygon. You can configure the Draw interaction's `snapTolerance` to a smaller value than the default of `12`. You can also set the `clickTolerance` to a smaller value than the default of `6` if you want to be able to draw another vertex after a very small pointer move.

**Comment by sharsmita** [comment]
Thanks, that works!
