### ISSUE TITLE
Projections other than WebMercator are not working on OGCVectorTile

### ISSUE THREAD

**Issue by doublebyte1** [openlayers/openlayers#15521]
**Describe the bug**

The [OGCVectorTile](https://openlayers.org/en/latest/apidoc/module-ol_source_OGCVectorTile-OGCVectorTile.html) class supports a parameter called `Projection`, which describes the projection of the tile grid. According to the documentation, it supports a ProjectionLike object, which defaults to 'EPSG:3857'. 

The issue is that 3857 is the only projection supported by the class. Using any other projection will cause the layer to fail to display, silently.

**To Reproduce**

 This works:
```
                  new VectorTileLayer({
                    title: 'Natural Earth',
                    visible: true,
                    source: new OGCVectorTile({
                      projection: 'EPSG:3857',
                      url: 'https://maps.gnosis.earth/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WebMercatorQuad',
                      format: new MVT({
                        dataProjection: 'EPSG:3857',
                        featureProjection: 'EPSG:3857'
                       }),
                    }),
                  })  
```
This also works (using EPSG:3857 as default):

`                  new VectorTileLayer({
                    title: 'Natural Earth',
                    visible: true,
                    source: new OGCVectorTile({
                      url: 'https://maps.gnosis.earth/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WebMercatorQuad',
                      format: new MVT({
                       }),
                    }),
                  }) `

However, this does not work:

`                  new VectorTileLayer({
                    title: 'Natural Earth',
                    visible: true,
                    source: new OGCVectorTile({
                      projection: 'EPSG:4326',
                      url: 'https://maps.gnosis.earth/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WorldCRS84Quad',
                      format: new MVT({
                        dataProjection: 'EPSG:4326',
                        featureProjection: 'EPSG:4326'
                       }),
                    }),`

According to the network inspector, a request to "https://maps.gnosis.earth/ogcapi/tileMatrixSets/WorldCRS84Quad" is issued and it receives a 200 response, but nothing happens after that (no tiles are requested).

**Expected behavior**
We should see a map like in the case of WebMercator tiles, but projected in WGS84.

![mercator-map](https://github.com/openlayers/openlayers/assets/1038897/bb452ebe-7429-441c-9127-8dbc9ffe8e92)

**Comment by mprins** [comment]
I'd expect that matrix set request to return a json response, but (in the browser) if returns a HTML response, that might be unexpected

**Comment by ahocevar** [comment]
Vector tiles do not support client side reprojection. If you want to consume an EPSG:4326 service, your map's view projection also needs to be EPSG:4326. Also note that you do not need to specify `featureProjection` and `dataProjection` on the MVT format.

**Comment by ahocevar** [comment]
> I'd expect that matrix set request to return a json response, but (in the browser) if returns a HTML response, that might be unexpected

If that's the case, then you won't get it to work with my suggestion above. That might be a problem of the service you're consuming.

**Comment by doublebyte1** [comment]
> Vector tiles do not support client side reprojection. If you want to consume an EPSG:4326 service, your map's view projection also needs to be EPSG:4326. Also note that you do not need to specify `featureProjection` and `dataProjection` on the MVT format.

Thanks for the comment @ahocevar . My view is indeed in 4326, but that does not change anything. I am unable to show any 4326 vector tiles.

```
,
    view: new View({
        center: [0,0],
        zoom: 2,
        projection: 'EPSG:4326'
    })
```

**Comment by doublebyte1** [comment]
> > I'd expect that matrix set request to return a json response, but (in the browser) if returns a HTML response, that might be unexpected
> 
> If that's the case, then you won't get it to work with my suggestion above. That might be a problem of the service you're consuming.

@ahocevar the same service works without problems, with a WebMercatorQuad Tile matrix set

![vectortiles-mercator](https://github.com/openlayers/openlayers/assets/1038897/c51797a6-63b7-411d-ac82-465dacf638bb)

**Comment by mike-000** [comment]
> I'd expect that matrix set request to return a json response, but (in the browser) if returns a HTML response, that might be unexpected

The url for a json response is https://maps.gnosis.earth/ogcapi/tileMatrixSets/WorldCRS84Quad?f=json

**Comment by doublebyte1** [comment]
> > I'd expect that matrix set request to return a json response, but (in the browser) if returns a HTML response, that might be unexpected
> 
> The url for a json response is https://maps.gnosis.earth/ogcapi/tileMatrixSets/WorldCRS84Quad?f=json

I would expect the client to get the right format, by using content negotiation. There should be no need to enforce it with the "f" parameter.

**Comment by mike-000** [comment]
> I would expect the client to get the right format, by using content negotiation. There should be no need to enforce it with the "f" parameter.

Yes, it does return a json when the application sets a `Accept: application/json` header.  The reason no tiles are loaded is the calculated tile grid has an incorrect extent `[90, -360, 450, -180]` https://codesandbox.io/s/ogc-vector-tiles-forked-pkzctf

**Comment by doublebyte1** [comment]
> > I would expect the client to get the right format, by using content negotiation. There should be no need to enforce it with the "f" parameter.
> 
> Yes, it does return a json when the application sets a `Accept: application/json` header. The reason no tiles are loaded is the calculated tile grid has an incorrect extent `[90, -360, 450, -180]` https://codesandbox.io/s/ogc-vector-tiles-forked-pkzctf

Unfortunately I cannot open your sandbox. Here is my code: https://github.com/ogcincubator/ogcapi-tiles-map/blob/master/main.js

**Comment by mike-000** [comment]
The codesandbox is based on https://openlayers.org/en/latest/examples/ogc-vector-tiles.html with the main.js changed to

```
const map = new Map({
  target: 'map',
  layers: [
    new VectorTileLayer({
      source: new OGCVectorTile({
        url:
          'https://maps.gnosis.earth/ogcapi/collections/NaturalEarth:cultural:ne_10m_admin_0_countries/tiles/WorldCRS84Quad',
        format: new MVT(),
        projection: 'EPSG:4326',
      }),
      background: '#d1d1d1',
      style: {
        'stroke-width': 0.6,
        'stroke-color': '#8c8b8b',
        'fill-color': '#f7f7e9',
      },
    }),
  ],
  view: new View({
    center: [0, 0],
    zoom: 1,
    projection: 'EPSG:4326',
  }),
});

setTimeout(() => {
  console.log(map.getLayers().item(0).getSource().getTileGrid().getExtent());
}, 5000);
```

**Comment by doublebyte1** [comment]
Thank you @mike-000! Indeed the grid with in 4326 does not look right:
`[90, -360, 450, -180]`
While the grid in 3857 looks like this:
`[-20037508.342789244, -20037508.342789244, 20037508.342789244, 20037508.342789244]`

I assume the problem is in this file?
https://github.com/openlayers/openlayers/blob/main/src/ol/tilegrid/TileGrid.js

**Comment by mike-000** [comment]
It will be an incorrect extent passed to that constructor at https://github.com/openlayers/openlayers/blob/main/src/ol/source/ogcTileUtil.js#L293

**Comment by mike-000** [comment]
The parser is not using the `orderedAxes` property in the json, and defauiting to the Lat/Lon `axisOrientation` for EPSG:4326.

**Comment by mike-000** [comment]
https://github.com/openlayers/openlayers/pull/15524 fixes the axis order when a projection is specified in the constructor, but there is a separate issue that specifying the projection should not be necessary, the crs in the TileMatrixSet could be used but isn't.
