### ISSUE TITLE
Incomplete Text Rendering Across Vector Tiles in OpenLayers 6.9

### ISSUE THREAD

**Issue by huhaote** [openlayers/openlayers#15527]
When rendering point data using vector tiles in OpenLayers 6.9, there is an observed problem where text labels, extending beyond the span of individual vector tiles, get truncated across tile boundaries. 
![image](https://github.com/openlayers/openlayers/assets/10611597/0a11a216-8ea2-46fa-b75d-e14a48598a30)

**Comment by ahocevar** [comment]
This will be fixed with #15466.

**Comment by huhaote** [comment]
> 这将通过 #15466 修复。

Does this mean this issue will be fixed in 9.0?

**Comment by ahocevar** [comment]
yes
