### ISSUE TITLE
Feature and "geometry" prop name

### ISSUE THREAD

**Issue by levelost** [openlayers/openlayers#15555]
**Describe the bug**
feature.set('geometry', 'some value') replace Geometry object. A property with the key "geometry" may come from an external source.

**To Reproduce**
1. const features = new GeoJSON.readFeatures(featuresWhithGeometryProp);
// { "type": "Feature",  "geometry": {"type": "Point", "coordinates": [102.0, 0.5]}, "properties": {"geometry": "111"}},
2. feature[0].getGeometry().getType();
3. See error.

**Comment by ahocevar** [comment]
If you have something like this, you need to configure the GeoJSON format with the `geometryName` constructor option, e.g.
```js
const format = new GeoJSON({geometryName: 'the_geom'});
const features = format.readFeatures(featuresWithGeometryProp);
console.log(feature.getGeometry().getType());
// 'Point'
console.log(feature.get('geometry'));
// '111'
```

**Comment by levelost** [comment]
Thanks, but the fact is that the absence of the "the_geom" key in external data is also not guaranteed. To be safe, geometry should not be in the feature properties (and cluster features too).

We had to write an extension to the Feature class to get around this.

**Comment by ahocevar** [comment]
You could easily safeguard against this by either knowing your data - simply inspect the first feature of your GeoJSON, look at the keys in the `properties` and choose a different name - or, even simpler, choose a random geometry name long and strange enough to decrease the likelihood of having such a property in your data to almost zero. Something like `ol_feature_geometry_${Math.round(Math.random * 10000)}`.

The reason for this design is that we support features with multiple geometries. That would be awkward if the feature had a single geometry field isolated from the rest of the properties.

**Comment by levelost** [comment]
This way you could make an array.
```ts
const geoms = feature.getGeometries();
```

**Comment by ahocevar** [comment]
We're not going to change this now, but we have plans to get rid of the `ol/Feature` API entirely in the near future.

**Comment by rdewit** [comment]
Related to: https://github.com/openlayers/openlayers/issues/14220 (for cross-reference purposes)
