### ISSUE TITLE
`prerender` event fires after rendering has started when `declutter: true`

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#15564]
**Describe the bug**
I expected #15466 would have fixed #11606 as the `postrender` event should (and does) now fire after the declutter items are rendered.  However the the `prerender` event now appears to fire too late, i.e. after the polygon/linestring rendering.

**To Reproduce**
Update https://codesandbox.io/s/trusting-edison-vnzsk?file=/main.js (demonstrated in #11606) to use the dev version. Observe the declutter items are now clipped but the background is no longer clipped.  The workaround using a timeout has no effect (so this would break a layer swipe, such as that by ol-ext).

**Expected behavior**
 `prerender` event should fire before any rendering.

**Comment by ahocevar** [comment]
Thanks for reporting this, @mike-000. f6cd74a should have taken care of this, but it seems you have found a case that has not been covered. I already see what's going on, stay tuned for the pull request that fixes it.
