### ISSUE TITLE
Clear RenderBox on DragBox Deactivation

### ISSUE THREAD

**Issue by behoney** [openlayers/openlayers#15571]
**Is your feature request related to a problem? Please describe.**

Users usually interact map with `Dragbox` and that interaction could be canceled as it fires `boxcancel` event according to [document](https://openlayers.org/en/v7.5.2/apidoc/module-ol_interaction_DragBox.DragBoxEvent.html#event:boxcancel).

Developers might need to implement "canceling drag" case, such like "when user press Escape, stop to drag". But there's no functions to handle this except `setActive(false)`.

But when developer stops DragBox interaction with `setActive(false)`, the `RenderBox`, which indicates where user drags, happens to remain. The `RenderBox` should be cleared by calling its own [`disposeInternal`](https://github.com/openlayers/openlayers/blob/f2c05afbd128428035f51945bbc74dc00aeaed7b/src/ol/render/Box.js#L52) function.

I simply reproduced with [stackblitz](https://stackblitz.com/edit/vitejs-vite-zqw5mk?embed=1&file=main.js)

FYI) It's hard to access `_box` of `DragBox` for Developers because it's private field.

**Describe the solution you'd like**

clear existing `RenderBox` when deactivate(`setActive(false)`) `Dragbox`.

I hope to work on this feature request if it's accepted to improve developer experience.

**Comment by M393** [comment]
A method to programmatically cancel the DragBox would be nice to have.

Sharing my implementation of and ESC-cancelable DragBox. It ain't pretty, but works for me.
```js
class CancelableDragBox extends ol.interaction.DragBox {
    constructor(options) {
        super(options);

        this.originalBoxEndCondition = options.boxEndCondition || this.defaultBoxEndCondition;

        this.boundOnKeyDown = this.onKeyDown.bind(this);
        options.boxEndCondition = this.cancelableBoxEndCondition.bind(this);

        this.canceled_ = false;
        this.pointerId_ = undefined;

        this.on('boxstart', this.onBoxStart.bind(this));
    }
    onBoxStart(evt) {
        const viewport = this.getMap().getViewport();
        viewport.addEventListener('keydown', this.boundOnKeyDown);
        this.canceled_ = false;
        this.pointerId_ = evt.mapBrowserEvent.originalEvent.pointerId;
    }
    onKeyDown(event) {
        if (event.key === 'Escape' && !event.ctrlKey && !event.altKey && !event.metaKey) {
            this.canceled_ = true;
            const mapBrowserEvent = {
                originalEvent: new PointerEvent('pointerup', {
                    pointerId: this.pointerId_,
                }),
                pixel: [ 10000, 10000 ],
                type: 'pointerup',
            };
            this.handleEvent(mapBrowserEvent);
        }
    }
    cancelableBoxEndCondition(evt, startPixel, endPixel) {
        const ok = !this.canceled_ && this.originalBoxEndCondition.call(this, evt, startPixel, endPixel);

        const viewport = this.getMap().getViewport();
        viewport.removeEventListener('keydown', this.boundOnKeyDown);
        this.pointerId_ = undefined;

        return ok;
    }
};
```

**Comment by ahocevar** [comment]
Pull request accepted. The fix should be simple by overriding `setActive()`:
```js
setActive(active) {
  if (!active) {
    this.box_.setMap(null);
    this.dispatchEvent(
      new DragBoxEvent(
        DragBoxEventType.BOXCANCEL,
        mapBrowserEvent.coordinate,
        mapBrowserEvent,
      ),
    );
  }
  super.setActive(active);
}
