### ISSUE TITLE
Browser memory will not be released when i remove wms layer

### ISSUE THREAD

**Issue by XiaoYang943** [openlayers/openlayers#15575]
openlayers add geoserver wms server,but the browser memory not released when i remove layer

## 1. here is add layer
`const createImageLayer = (data) => {
    ...
    let source = new ImageWMS({
      ratio: 1,
      url: VUE_APP_GIS_PATH,
      // url: 'http://localhost:8080/geoserver/gis/wms',
      params: {
        VERSION: '1.1.1',
        LAYERS: `${attribute}`,
      },
      // projection: 'EPSG:3857',
      serverType: 'geoserver',
    });
    let layer = new ImageLayer({
      source: source,
      properties: { id },
      zIndex: zIndex,
    });
    curMap.map.addLayer(layer);
  };`
## 2. here is remove layer
`curMap.map
        .getLayers()
        .getArray()
        .find((item) => {
          if (item?.getProperties()?.id === id) curMap.map.removeLayer(item);
        });` 
## 3. But the program's memory is not released in win11 task manager
- I added about 20 WMS layers
- The memory has grown by over 100 megabytes
## 4. here is version
- openlayers:7.5.1
- electron:13.0.0
- system:windows11

thanks for help.
good luck.

**Comment by ahocevar** [comment]
Several things to consider here: first of all, 20 layers is a lot. And if they all are served by the same GeoServer instance, it is besser to combine them to a single request. Next, images are cached, and won't be released immediately. If images were requested for each of the 20 layers, they will be cached by Electron, unless you have very restrictive cache headers configured on your GeoServer that prevent caching. Furthermore, keep in mind that the garbage collector might not clear the layers immediately if there is no pressure. And finally, it could be a good idea to upgrade to the latest version of OpenLayers.

**Comment by XiaoYang943** [comment]
Thanks for your help. I will try upgrading the version of Openlayers or combining these layers into layer groups with GeoServer.
