### ISSUE TITLE
Observable properties missing in API doc for Source classes

### ISSUE THREAD

**Issue by jmacura** [openlayers/openlayers#15578]
**Describe the bug**
This is an issue of the [API documentation](https://openlayers.org/en/latest/apidoc/).
Some classes have properly described _Observable Properties_, like [VectorLayer](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html). But some others miss this part of documentation, like [VectorSource](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html), despite the fact that they do have observable properties.
Reading through https://github.com/openlayers/openlayers/tree/main/config/jsdoc/api the problem seems to be that the `@observable` annotations are missing in the JSDoc comments for relevant getters/setters.
This seems easy to fix, I might do it myself, but I am unsure which properties shall be marked as observable...? All which have a getter/setter defined?

**Comment by ahocevar** [comment]
That's intentional. The fact that the mentioned classes are `Observable`s is an implementation detail that we do not want to expose through the user facing API. We might change the implementation to not use `Observable`s any time.

**Comment by jmacura** [comment]
I must say I am confused. What is the purpose of the "Observable Properties" list in the API doc then? Like e.g. for `Layer` class:
![image](https://github.com/openlayers/openlayers/assets/5598693/660c95ef-a062-40b4-9bca-e1e2150ccef9)

**Comment by ahocevar** [comment]
My above comment was referring to `Source`. For `Layer` we do expose the observable properties and their events, and you can use them. For `Source` we use them internally, but don't expose them.

**Comment by jmacura** [comment]
> My above comment was referring to `Source`. For `Layer` we do expose the observable properties and their events, and you can use them. For `Source` we use them internally, but don't expose them.

Now I am very curious about the reasons behind it. Why `Layer` and its subclasses have properties which are aimed at public usage, but `Source` and its subclasses have only properties which are considered internal? Even though that `Source` (or `VectorSource` might be a better example) emits public events, just like `Layer`, and provides getters/setters for its properties, just like `Layer`. Would you be so kind and elaborate a bit about that? Thank you!

**Comment by ahocevar** [comment]
You're mixing "observable properties" with class/instance properties. `Source` does not have any observable properties.

What is the reason why you opened this issue in the first place? What is your use case for wanting observable properties on `Source`?

**Comment by jmacura** [comment]
> What is the reason why you opened this issue in the first place? What is your use case for wanting observable properties on `Source`?

The reason was that I was thinking there is a missing part in a documentation, so I thought I could verify it and make a fix. But...

> You're mixing "observable properties" with class/instance properties. `Source` does not have any observable properties.

You are right. Seems like I misunderstood the docs: ([VectorSource](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html) inherits from) [Source](https://openlayers.org/en/latest/apidoc/module-ol_source_Source-Source.html) inherits from [BaseObject](https://openlayers.org/en/latest/apidoc/module-ol_Object-BaseObject.html), which inherits from [Observable](https://openlayers.org/en/latest/apidoc/module-ol_Observable-Observable.html). The documentation for `BaseObject` states:

> Classes that inherit from this have pre-defined properties, to which you can add your owns. The pre-defined properties are listed in this documentation as 'Observable Properties', and have their own accessors (...) You can add your own observable properties with object.set('prop', 'value'), and retrieve that with object.get('prop'). You can listen for changes on that property value with object.on('change:prop', listener).

From that I deduced that any property set on any class which extends `BaseObject` must be observable, but now I can see it is not the case. `Source` class properties like `attributions`, `attributionsCollapsible`, `projection` or `state` cannot be listened neither with `propertychange` nor `change:attributions` and similar listeners.

Sorry for making ado about nothing. I guess this issue can be closed.
