### ISSUE TITLE
The distance measured by the circle and line segment in OpenLayers is not the same.

### ISSUE THREAD

**Issue by hankaibo** [openlayers/openlayers#15582]
**Describe the bug**
In OpenLayers, there are two points A and B. 
A circle is drawn with A as the center and AB as the radius. 
Through geometry.getRadius(), a distance S1 can be obtained. 
On the other hand, measuring AB as a line segment gives a distance S2. 
At this point, it is found that S1 > S2. 
Why is this? 
Shouldn’t they be equal?

**To Reproduce**
1. Go to https://myhospital-svelte.vercel.app/ 
2. Draw circle
3. Open Browser console(F12)
![circle](https://github.com/openlayers/openlayers/assets/5361465/b838d067-be6e-47c2-b575-2327a84aa898)
S1=2055m

1. Go to https://openlayers.org/en/latest/examples/measure-style.html
2. Draw line
![line](https://github.com/openlayers/openlayers/assets/5361465/68cca5f0-e0af-431d-babb-273cbad79dd1)
S2=1610m

**Expected behavior**
S1=S2

**Comment by potion-cellar** [comment]
The radius of a circle geometry, despite being in map units (meters for EPSG:3857), is not actually a measurement for the distance on the ground.

You need to use methods from `ol/sphere` to actually get the great sphere distance given the radius of the Earth.

For instance, you could use `ol/sphere -> getLength()` against a geometry created from the extent of the Circle geometry in question, and divide that by 8.

When doing that, I get the same distance as measuring with the line segment per the openlayers example.

**Comment by hankaibo** [comment]
Thank you very much for your answer. 
However, I still don’t quite understand why we divide by 8. 
What I can think of is based on the distance measured by the line segment.
I will give it a try. 
Thank you.

**Comment by potion-cellar** [comment]
> However, I still don’t quite understand why we divide by 8.

For the particular trick I did, `getLength()` adds the length of all four sides of the extent together, but we only want the length of half (/ 2) of one of the sides (/ 4).

**Comment by hankaibo** [comment]
I truly appreciate your help.
Unfortunately, my English is not good enough, and I'm a beginner, sigh!
I constructed a line segment with the center of the circle and the last coordinate of the circle as the two ends,
and then measured their length.
The problem is solved, but I found a strange phenomenon, which should be  due my misunderstanding. 
Here is the code:

```js
const line = new LineString([
	[-11000706.48267012, 4599925.709030858],
	[-10998658.283823326, 4599947.8227707315]
]);
console.log('sphere.getLength()--->', getLength(line), ',line.length()--->', line.getLength());
// ===> sphere.getLength()---> 1609.098756749408 ,line.length()--->'2048.3182207611635

```

**Comment by potion-cellar** [comment]
Like the circle's getRadius(), line's getLength() is not an actual measurement on the ground.

This is due to the default Web Mercator projection -- as you get closer to the poles, the apparent size of things gets larger. (This is common in many other projections, which is outside of the scope of a simple GitHub comment)

The getLength() function in sphere actually accounts for this which is why it returns a different (and accurate) value.

A good starting point that might help you understand might be here: https://en.wikipedia.org/wiki/Tissot%27s_indicatrix?wprov=sfla1

**Comment by hankaibo** [comment]
Thank you. I have check it out.
