### ISSUE TITLE
Flickering map when using webview on a NOTHING phone

### ISSUE THREAD

**Issue by mgurzixo** [openlayers/openlayers#15593]
Hello,

When bumping OL version to V9, I found that, only on the Nothing phone, the map was flickering randomly when panning or zooming.
Most of the time, the map was perfect, but sometimes, it went completely black. This occurred mostly around zoom levels 3,4,5.

This occurred on 2 Nothing phones with different Android versions (V12 & V13) and any webview version.

This did not occurred on any other Android, Ios or Web platforms.

I was able to pinpoint this regression to commit #15344 .

When investigating, I found that the test `has.js#WORKER_OFFSCREEN_CANVAS ` is usually false on all my test systems, and so the `transform.js#toString()` was always using the DOM.

After this commit, this test is not performed anymore, and the new transform calculus makes this specific phone flickering for an unknown reason.

As a quick fix, I re-added the test, and so used the previous DOM transform. This solved the problem.

It looks like there are daemons lurking around there...

Michel

**Comment by ahocevar** [comment]
Would you be able to share the transform values on the canvas that cause the map to flicker?

**Comment by mgurzixo** [comment]
I will instrument the code, do a run and pastebin the result.
I should be able to do this by the end of the week

**Comment by ahocevar** [comment]
So far so good. But can you mark the transforms that cause the map to disappear or flicker?

**Comment by mgurzixo** [comment]
I just checked, and it looks like the transforms do NOT change, except when I change screen orientation from portrait to paysage.
Panning or zooming does not change values. Maybe the `m̀at` should be cached, or OL is performing useless calculations?

But the flickering is definitively panning and zoomLevel dependent. I could have to do with fractional zoom levels?

Anyway, the new `matrixPrecision` initialization solves completely the problem on all my test systems (Ios, Android, browsers, electron). I keep this value in my fork and I recommend the update of OL.

Thanks for all the hard work on this exceptional product!

Michel

**Comment by ahocevar** [comment]
The problem is: the reason for #15344 was that the precision of the matrix parameters was too high, so canvases could not be grouped together any more, even if their transform was de facto the same.

I'd really like to fix this issue, but since I'm not able to reproduce the issue I have to rely on reports here. So can you please provide a minimal example with code that causes your devices in question to flicker? And also a video that shows *when* and *how* the flickering occurs?

**Comment by mgurzixo** [comment]
I did a video, available [here](https://transfer.sh/V8au0xj4Bq/VID_20240301_143540.m4v) .
As the app is actually under embargo, I started to cleanup everything except the map, and I was surprised to see that everything became OK.
The flickering starts to occur as soon as a marker is visible, or not far away in the margins.
This marker is  in a vector layer:
```
 poiSource = new VectorSource({
    features: myPlaces.getMarkersFeatures().value,
  });
  const poiLayer = new VectorLayer({
    source: poiSource,
  });
```
and the style is done with:
```
let myCanvas = document.createElement("canvas");
      let myContext = myCanvas.getContext("2d");
      myCanvas.width = upngImage.width;
      myCanvas.height = upngImage.height;
      const upngImageData = new ImageData(
        new Uint8ClampedArray(rgba8),
        upngImage.width,
        upngImage.height,
      );
      myContext.putImageData(upngImageData, 0, 0);

      myStyle = new Style({
        image: new Icon({
          anchor: options.anchor,
          anchorXUnits: "fraction",
          anchorYUnits: "fraction",
          crossOrigin: "anonymous",
          img: myCanvas,
          rotation: options.rotation,
          displacement: options.displacement,
          opacity: options.opacity,
          scale: options.scale || DEFAULTS.SCALE,
          color: options.color,
          rotateWithView: options.rotateWithView,
        }),
      });
```
the width and height are 64x64px
and rgba8 is created with:
```
rgba8 = composeBitmap(
          new Uint8ClampedArray(stencil),
          upngImage.width,
          upngImage.height,
          options.strokeColor || DEFAULTS.STROKE_COLOR,
          options.fillColor || DEFAULTS.FILL_COLOR,
        );
```
stencil is an array of RGBA pixels created with UPNG.toRGBA8() from the [upng-js](https://github.com/photopea/UPNG.js) library.

If I remove this marker, or if it is far away from the viewport, everything is OK.
I have other markers in this layer, created from SVG images, that does NOT cause any problem.

So, it looks like there is a bad interaction when a feature in a vector layer is created from a canvas, which does not occur when the (nearly) same image is created from an SVG.

I am using [Quasar](https://quasar.dev/) which uses vue3 and [capacitor](https://capacitorjs.com/) underneath. The exact same code works OK with any browser (chromium, firefox) on the same phone. It occurs only when using the webview.

I have plenty of workarounds to solve this problem and I do not need support, but it is not a good thing to leave questions unanswered.

I am not very fluent in creating a simple OL example from scratch and making it run in a webview, but I am ready to test on this particular phone any test that you could create.

**Comment by ahocevar** [comment]
Thanks for this excellent report, @mgurzixo. Reading that I assume the problem is not the transform itself, but the fact that with the change the marker layer is combined with the base map, at least sometimes.

As a test, can you  add the config option `className: 'poi'` to the `poiLayer`, and see if the issue persists?

**Comment by mgurzixo** [comment]
When adding this option:
```
  const poiLayer = new VectorLayer({
    source: poiSource,
    className:"poi",
  });
```
Everything works OK with both the old and the new initialization. The markers are OK and there is absolutely no flickering.

I suspect a phenomenon of [moiré](https://en.wikipedia.org/wiki/Moir%C3%A9_pattern) between the poiLayer canvas and the tileLayer canvas; maybe you don´t apply **exactly** the **very same** transformation to both layers and there is a very slight difference in the rotation part. We are talking about _physical_ pixels here and this explanation is compatible with everything observed.

There is actually a move towards [hardware composition](https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome/). Depending on the hardware rounding errors, number of pixels of the screen and so on... this phenomenon could or could not occur. Maybe also you can do things in a webview (authorizations, direct access to hardware, part of it running in kernel space ...) that you cannot do with a browser just running in userland. 

For myself, I switched everything from bitmap to SVG, so I am not concerned anymore and markers are crisper ;)

I still suggest using the `[1e6, 1e6, 1e6, 1e6, 1e7, 1e7]` initialization, and provide a switch (could be an option when creating the layer) to fallback to the old DOM method, just in case...

Thank you @ahocevar  for taking so much care to make a perfect product

Michel

**Comment by ahocevar** [comment]
Can you test one more thing for me: with the original code (without `className`), what is `document.querySelectorAll('.ol-layer canvas').length` when rendering is correct, and what when there's the flicker?

**Comment by mgurzixo** [comment]
It is always 1 and does not vary, flickering or not.

Code is:
```
console.warn(`[OL.transform.toString] length:${document.querySelectorAll('.ol-layer canvas').length}`);
```
I sampled it both in `transform.js#toString()`and in my `view.on("change:center")`handler.

**Comment by mgurzixo** [comment]
BTW, I don't know precisely the internals of OL, but are you aware of [that](https://www.peterlunch.com/snippets/javascript-round)?

**Comment by ahocevar** [comment]
> BTW, I don't know precisely the internals of OL, but are you aware of [that](https://www.peterlunch.com/snippets/javascript-round)?

Yes, that's exactly how we do it.

**Comment by ahocevar** [comment]
> I still suggest using the [1e6, 1e6, 1e6, 1e6, 1e7, 1e7] initialization, and provide a switch (could be an option when creating the layer) to fallback to the old DOM method, just in case...

That would break a test, and deoptimise composition by using multiple canvases. Since you can use the `className` config in userland to achieve that, you have a viable option to fix this strange problem which is very likely a hardware problem on the device in question.

**Comment by mgurzixo** [comment]
I understand that, and it makes sense as long as there is a workaround available. OL strength and weakness is all the layer processing to mix apples and oranges (ie. different projections, rotations, resolutions and constraints) onto the same display. This means that we users should avoid throwing other bitmaps (especially hand-made) into this complexity, and stick to vectors, SVG and standard HTML.
BTW, I think that it is not a hardware problem but a hardware particularity ;)

**Comment by ssundell** [comment]
I'm having similar issues with plain desktop Chrome: when zooming, the map flickers, and on some zoom levels it goes blank completely. WMS and vector tile layers seem to work ok, but if you add a vector layer, flickering starts. Adding the `className` parameter removes flickering.

Not sure if I can help much with debugging, just came to comment that it's probably not just an issue related to Nothing phone hardware; the hardware I'm using is a Lenovo laptop with Intel graphics...

**Comment by ahocevar** [comment]
#15620 should fix this problem.

**Comment by ahocevar** [comment]
For that pull request, you can test with the full build: https://deploy-preview-15620--ol-site.netlify.app/en/latest/ol/dist/ol.js and https://deploy-preview-15620--ol-site.netlify.app/en/latest/ol/ol.css

**Comment by jankosk** [comment]
I have similar map flickering issues with tile layers when zooming on desktop Chrome with Intel graphics. Applying the patch in #15620 seems to work for me.

**Comment by bjornharrtell** [comment]
Also seeing this flickering primarily on the combination Windows and Chrome.

**Comment by ahocevar** [comment]
@bjornharrtell Thanks for reporting. Can you please also check if #15620 fixes the problem for you?

**Comment by ahocevar** [comment]
#15620 is now merged, so ol package users please test if the issue is fixed by doing an `npm install ol@dev`.

**Comment by bjornharrtell** [comment]
@ahocevar limited testing indicates that #15620 is effective in our case.
