### ISSUE TITLE
Default Styles for Modifying Feature Broke in Upgrade from 8.2 to 9.0

### ISSUE THREAD

**Issue by eflowbeach** [openlayers/openlayers#15599]
I noticed when I upgraded from 8.2 to 9.0 that my editing styles broke for my LineString. It took me a couple of hours, but in the documentation here: https://openlayers.org/en/latest/apidoc/module-ol_style_Style-Style.html  I noticed that it has the default style as:
` styles['Circle'] = styles['Polygon'].concat(
   styles['LineString']
 );`

when I believe it should be:
` styles['Circle'] = styles['Point'].concat(
            styles['LineString']
        );`

The latter bit of code, fixed the issue.

**Comment by eflowbeach** [comment]
I guess I also had to comment out zIndex for this to work. 
` styles['Point'] = [
            new ol.style.Style({
                image: new ol.style.Circle({
                    radius: width * 2,
                    fill: new ol.style.Fill({
                        color: blue,
                    }),
                    stroke: new ol.style.Stroke({
                        color: white,
                        width: width / 2,
                    }),
                }),
                // zIndex: Infinity,
            }),
        ];`

**Comment by ahocevar** [comment]
Can this be seen in any of the examples from https://openlayers.org/en/latest/examples/ ? Or do you have any live example to reproduce this?

**Comment by ahocevar** [comment]
@eflowbeach @kjellmf It would be good to have a minimal standalone example (e.g. in a repository with code created with `npm create ol-app my-app`, codesandbox or jsfiddle) to investigate this further.

**Comment by eflowbeach** [comment]
@ahocevar @kjellmf Ok, I think I figured it out! It's actually because I set declutter to true in a separate layer which causes the dot to disappear. Here's the bare bones code, sorry my organization doesn't allow npm...

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Draw and Modify Features</title>
    <!-- <script src="https://cdn.jsdelivr.net/npm/ol@v9.0.0/dist/ol.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@v9.0.0/ol.css"> -->
    <script src="ol/ol.js"></script>
<link rel="stylesheet" href="ol/ol.css">
    <style>
        .map {
            width: 100%;
            height: 400px;
        }
    </style>
</head>

<body>
    <div id="map" class="map"></div>
    <form>
        <label for="type">Geometry type &nbsp;</label>
        <select id="type">
            <option value="Point">Point</option>
            <option value="LineString">LineString</option>
            <option value="Polygon">Polygon</option>
            <option value="Circle">Circle</option>
        </select>
    </form>

    <script>
        const raster = new ol.layer.Tile({
            source: new ol.source.OSM(),
        });

        const source = new ol.source.Vector();
        const vector = new ol.layer.Vector({
            source: source
        });

        const timeOfArrivalSource = new ol.source.Vector();
        const timeOfArrivalLayer = new ol.layer.Vector({
            source: timeOfArrivalSource,
            visible: false,
            declutter: true                       // <-------------------------- Adding this breaks it
        });

        // Limit multi-world panning to one world east and west of the real world.
        // Geometry coordinates have to be within that range.       
        const map = new ol.Map({
            layers: [raster, vector, timeOfArrivalLayer],
            target: 'map',
            view: new ol.View({
                center: [-11000000, 4600000],
                zoom: 4,
                // extent,
            }),
        });

        const modify = new ol.interaction.Modify({ source: source });
        map.addInteraction(modify);

        let draw, snap; // global so we can remove them later
     
        function addInteractions() {
            draw = new ol.interaction.Draw({
                source: source,
                type: 'LineString'
            });
            map.addInteraction(draw);
            snap = new ol.interaction.Snap({ source: source });
            map.addInteraction(snap);
        }      
        addInteractions();
    </script>
</body>
</html>
```

**Comment by ahocevar** [comment]
Thanks a lot @kjellmf. This is a good find and should be enough information to fix it.

**Comment by ahocevar** [comment]
The problem is that array optimization is not as advanced as I thought in JavaScript - setting a very high zIndex on a style makes the ZIndexContext either extremely slow or break entierly. Working on a fix.
