### ISSUE TITLE
this.fill_.loading is not a function in ol/style/RegularShape.js

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#15601]
I used to have the following in Openlayers 8 (Which worked 100%).  

```
      var flashStyle = new ol.style.Circle({
        radius,
        snapToPixel: false,
        fill: new ol.style.Stroke({
          color: 'rgba(239, 70, 35, ' + opacity + ')',
          opacity
        })
      });
```

Now, in Openlayers 9 it throws an error:

`RegularShape.js:140 Uncaught TypeError: this.fill_.loading is not a function`

at ol/style/RegularShape.js

```
this.imageState_ =
      this.fill_ && this.fill_.loading()
        ? ImageState.LOADING
        : ImageState.LOADED;
```

**Comment by M393** [comment]
`fill` expects a [`ol.style.Fill`](https://openlayers.org/en/latest/apidoc/module-ol_style_Fill-Fill.html), not [`ol.style.Stroke`](https://openlayers.org/en/latest/apidoc/module-ol_style_Stroke-Stroke.html).

Also opacity is not a valid option to either and `snapToPixel` is not used by [`ol.style.Circle`](https://openlayers.org/en/latest/apidoc/module-ol_style_Circle-CircleStyle.html).
Try:
```js
      var flashStyle = new ol.style.Circle({
        radius,
        fill: new ol.style.Fill({
          color: 'rgba(239, 70, 35, ' + opacity + ')',
        })
      });
```
