### ISSUE TITLE
setOpacity on Vector Layer with 'declutter' set causes layer to disappear.

### ISSUE THREAD

**Issue by malaretv** [openlayers/openlayers#15611]
**Describe the bug**
This one has me a bit stumped!

As of v9.0 calling setOpacity on a VectorLayer when `declutter` is enabled causes that layer to disappear.

**To Reproduce**
Steps to reproduce the behavior
(Apologies for not linking directly to an example as CodeSandbox won't let users create their own drafts anymore without paying)

1. Go to https://openlayers.org/en/latest/examples/vector-labels.html
2. Edit codesandbox example to add `declutter: true` to vectorPoints layer definition (or seemingly to *any* vector layer defined also causes the issue). Then add the following at the end of the example code:
```js
 setTimeout(() => {
  vectorPoints.setOpacity(0.5);
}, 2000);
```
3. Run example, and watch vectorPoints layer disappear after 2 seconds when `setOpacity` is called

**Expected behavior**
The layer to correctly update it's opacity without vanishing

**Comment by ahocevar** [comment]
Thanks @malaretv for the bug report and the reproduction case. I think I should be able to fix it quickly with the information you provided. Stay tuned for a pull request with a fix.

**Comment by ahocevar** [comment]
#15614 fixes this issue.

**Comment by malaretv** [comment]
Awesome! Linking that PR against my application I can confirm it fixes the issues reported here.

Thanks for the quick fix @ahocevar!
