### ISSUE TITLE
Add https://github.com/openlayers/openlayers/pull/15448 to breaking changes of OL `v9.0.0`

### ISSUE THREAD

**Issue by JakobMiksch** [openlayers/openlayers#15613]
the PR https://github.com/openlayers/openlayers/pull/15448 is a breaking change IMHO and should be noted in the release notes / upgrade guide of [`v9.0.0`](https://github.com/openlayers/openlayers/releases/tag/v9.0.0). 

If you agree, I can make a PR for that.

**Comment by ahocevar** [comment]
@JakobMiksch Please go ahead. The previous behavior was unexpected, so yes it can be considered a breaking change: if people worked around it the workaround now has to be removed.

**Comment by JakobMiksch** [comment]
@ahocevar I added it to the breaking changes / upgrade guide: https://github.com/openlayers/openlayers/pull/15616
