### ISSUE TITLE
COG GeTIFF is not recognized

### ISSUE THREAD

**Issue by ElGerys** [openlayers/openlayers#15632]
**Describe the bug**
I have 4 COG GeoTIFFs that are derived from the original GeoTIFF (files and metada enclosed here):

- Original GeoTIFF: mb_pd.tif (138K)
- 4 types of derived COGs:
mb_pd_cr.tif (4,7K)  -> multi-band file
mb_pd_hs.tif (26K)  -> single-band file
mb_pd_sl.tif (106K) -> single-band file
mb_pd_tri.tif (85K)  -> single-band file

[metadata.txt](https://github.com/openlayers/openlayers/files/14565490/metadata.txt)

After playing with options in the `ol/source/GeoTIFF.js` (eg. `allowFullFile` in GeoTIFFSourceOptions), the multi-band `mb_pd_cr.tif`and single-band `mb_pd_hs.tif`do not display in the map view. Surprisingly, the single-band `mb_pd_sl.tif` and `mb_pd_tri.tif` files do render without problems. The weird thing is that similar COG files do render perfectly (all types above). In all type cases, the GeoTIFFs were created programmatically, so there are no changes between files of the same type. 

So, I suspect these files are not being handled by the GeoTIFF.js as the other working files. I imagine that there should be a bug. 

**To Reproduce**
I use the following piece of code to display the COG files as follows:

```
const relief = {
  color: [
	'case',
	[
	  'all',
	  ['==', ['band', 1], 0],
	  ['==', ['band', 2], 0],
	  ['==', ['band', 3], 0],
	  ['==', ['band', 4], 1],
	],
	[0, 0, 0, 0.0],
	[
	  'color',
	  ['*', ['band', 1], 255],
	  ['*', ['band', 2], 255],
	  ['*', ['band', 3], 255],
	  ['band', 4],
	],
  ],
};

const slope = {
  color: [
	'case',
	['>', ['band', 2], 0],
	[
	'interpolate',
	  ['linear'],
	  ['band', 1],
	  0, [0, 89, 179, 0.01],
	  76, [255, 234, 0, 5.0],
    ],
	[0, 0, 0, 0],
  ],
};

const tri = {
  color: [
	'case',
	['>', ['band', 2], 0],
	[
	'interpolate',
	  ['linear'],
	  ['band', 1],
	  0, [0, 89, 179, 0.01],
	  540, [255, 172, 28, 15.0],
    ],
	[0, 0, 0, 0],
  ],
};

--
	new WebGLTileLayer({
  	  title: 'CN225-DN',
	  style: relief,
  	  source: new GeoTIFF({
		sources: [{
		  url: 'raster/mb_pd_cr.tif',
		  nodata: 0,
		}],
  	  }),
	}),
--
	new WebGLTileLayer({
	  title: 'CN225-DN',
	  source: new GeoTIFF({
		sources: [{
		  url: 'raster/mb_pd_hs.tif',
		}],
	  }),
	}),
--
	new WebGLTileLayer({
  	  title: 'CN225-DN',
	  style: slope,
  	  source: new GeoTIFF({
		normalize: false,
		sources: [{
		  url: 'raster/mb_pd_sl.tif',
		  nodata: 0,
		}],
  	  }),
	}),
--
	new WebGLTileLayer({
  	  title: 'CN225-DN',
	  style: tri,
  	  source: new GeoTIFF({
		normalize: false,
		sources: [{
		  url: 'raster/mb_pd_tri.tif',
		  nodata: 0,
		}],
  	  }),
	}),

```

**Expected behavior**
I would appreciate that someone does tests with these files in order to render them without problems and check if this has to do with the way the `GeoTIFF.js` file handles these 4 COG types. I am using OL v8.2.0. Many thanks in advance for the support.

**Comment by mike-000** [comment]
All those files work for me in v8.2.0 and v9.0.0.  It might be a browser or server issue such as noted in https://github.com/openlayers/openlayers/issues/14926#issuecomment-1644641656 .

What happens if you load from a blob as in https://openlayers.org/en/latest/examples/cog-blob.html ?

**Comment by ElGerys** [comment]
Thanks for the reply, the `"ranges` trick in `.htaccess` did not work unfortunately, it keeps saying:

`Failed to load resource: the server responded with a status of 416 (Range Not Satisfiable)
`
What else can it be done to overcome this issue? I will try the `blob` option as suggested.

**Comment by ElGerys** [comment]
After some more tests, I get this:

AggregateError: Request failed
    CustomAggregateError utils.js:151
    fetch blockedsource.js:153
[console.js:62:10](http://localhost:5173/node_modules/ol/console.js)
    error console.js:62
    GeoTIFFSource GeoTIFF.js:482

Any thoughts?

**Comment by ElGerys** [comment]
Found it finally. After reading some posts about `apache2`, it seems that my OL directory has to be placed in `/var/www`. Once there, all COG GeoTIFF files loaded correctly. For some reason (most likely due to the way `apache2.conf` has been modified), there are restrictions to send requests from directories outside `/var/www`(at least what I understood from these tests). Hopefully this will help someone else out there!
