### ISSUE TITLE
MultiPolygonGeometry with empty coordinates throws an undefined error

### ISSUE THREAD

**Issue by yphanikiran** [openlayers/openlayers#15636]
**Describe the bug**
When an MultiPolygonGeometry with empty coordinates is passed to readFeature() method, throws undefined error as shown in the below screenshot

![image](https://github.com/openlayers/openlayers/assets/145588190/2d04dae3-583e-4027-85e0-1a71f47134ac)

**To Reproduce**
1. Create an object with empty coordinates array 
```
const featureObject = {
    "type": "Feature",
    "id": "test",
    "properties": {},
    "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
            [
                [],
                []
            ]
        ]
    }
}
```
2. pass it readFeature method
```
const geojsonFormat = new GeoJSON({
    dataProjection: 'EPSG:4326',
    featureProjection: 'EPSG:3857'
});
const feature = this.geojsonFormat.readFeature(featureObject) as Feature;
```
3. we will get an error in the console as below
![image](https://github.com/openlayers/openlayers/assets/145588190/0ad89f47-1060-48f9-9ce6-cca3d28ecf72)

**Expected behavior**
when a MultiPolygonGeometry with empty coordinates is passed to readFeature() method, it should handle it without throwing an error

**Comment by ahocevar** [comment]
The GeoJSON you're throwing at the `GeoJSON` format here is invalid. You can verify that at https://geojsonlint.com.

At the very least, to get a valid GeoJSON, you'd have to remove the empty coordinate pairs:
```json
{
    "type": "Feature",
    "id": "test",
    "properties": {},
    "geometry": {
        "type": "MultiPolygon",
        "coordinates": [
            []
        ]
    }
}
```
