### ISSUE TITLE
 ERROR  Failed to compile with 1 error    

### ISSUE THREAD

**Issue by T0-cxy** [openlayers/openlayers#15646]
ERROR  Failed to compile with 1 error                                                                          17:48:39

 error  in ./node_modules/ol-wind/dist/ol-wind.esm.js

Module parse failed: Unexpected token (14:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| class WindLayerRender extends CanvasLayerRenderer {
>   context;
|   containerReused;
|   container;

 @ ./src/utils/MapClass.js 21:0-36 339:28-37
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/map/map.vue?vue&type=script&lang=js
 @ ./src/components/map/map.vue?vue&type=script&lang=js
 @ ./src/components/map/map.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/dashboard/index.vue?vue&type=script&lang=js
 @ ./src/views/dashboard/index.vue?vue&type=script&lang=js
 @ ./src/views/dashboard/index.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.31.87:9528&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by ahocevar** [comment]
Nothing from `ol` in the code or tree. Are you sure you have imported the CanvasLayerRenderer?
