### ISSUE TITLE
Add a silent option to the removeFeature method of the vector source.

### ISSUE THREAD

**Issue by ger-benjamin** [openlayers/openlayers#15642]
Hello,

**Is your feature request related to a problem? Please describe.**

In a project, I'm using ol/source/Vector (through cluster source). In this project, I can have up to 5000 features in the layer, and have the possibility to add and remove almost ever feature at once.

To remove feature, we can use [removeFeature](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html#removeFeature), or [clear](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html#clear). But in my case, clear/re-add some is not a good option.

The problem is that removing feature is only done one by one. Triggering events through the source.changed() for each feature. That can be very slow in a complex project. 

**Describe the solution you'd like**

I would like to have a `silent` option in the `removeFeature` method of the `ol.source.Vector` to not emit event each time a feature is removed.
Or eventually a `removeFeatures` next to the `removeFeature`, as we already have a `addFeatures` next to the `addFeature`.

**Demo**

I've made a demo using a new `silent` option: https://codepen.io/bgerber/pen/zYXKERZ
In the demo, you can add or remove 5000 features on the map, with or without the new `silent` option.
Each time the source is changed, I simulate a sync task that take 0.3ms.

**Comment by ahocevar** [comment]
If you have a vector source with a lot of changes, you might want to consider using the `useSpatialIndex: false` option on the source.

The demo in your code pen does not replicate the actual behavior, because when the source `change` event is triggered, a `requestAnimationFrame` is triggered to re-render, but not every `change` event will cause a re-render. These changes are usually grouped into a single re-render.

**Comment by ger-benjamin** [comment]
Hi @ahocevar ,

My demo don't represent the complexity of my project, it just tries to demonstrate a problem. Still I have added `useSpatialIndex: false`, but that's not really relevant for this demo.

I also don't do a `source.on('change')` in my project. Still, if I remove 3000 features at once, it took me more than 2s. Using the same override as in the demo allows me to avoid this issue. I'll try to dig further in my project to find why I've this issue. But even if I fix it, I probably will keep this `silent` option. Having it directly in Ol would be appreciated. Calling N times `source.changed` for N features is probably not a nice thing to do. And in my dummy demo, we effectively have 5000 changes.

**Comment by ahocevar** [comment]
> I also don't do a source.on('change') in my project.

That's triggered internally to notify the layer of the changes.

**Comment by ger-benjamin** [comment]
Closed and done with #15643
