### ISSUE TITLE
如何只监听图层变化？

### ISSUE THREAD

**Issue by stdue** [openlayers/openlayers#15656]
在做图层管理的时候想使用 `map.on` 来监听图层变化的某个事件以完成图层数组的生成，但是并没有找到一个仅在图层数组增删时触发的事件(`change:layergroup`是最类似的一个，但它是没有效果的，也就是监听并不生效)，请问有没有一个事件能准确监听图层的增加/删除，或者我使用`change:layergroup`的方式有误？谢谢🙏

**Comment by mike-000** [comment]
To listen for addition/removal of individual layers you can use layer Collection events

```
map.getLayers().on('add', handler);
map.getLayers().on('remove', handler);
```

**Comment by jacklinna** [comment]
> To listen for addition/removal of individual layers you can use layer Collection events
> 
> ```
> map.getLayers().on('add', handler);
> map.getLayers().on('remove', handler);
> ```

good idea

**Comment by stdue** [comment]
good idea
