### ISSUE TITLE
MapTiler satellite tiles in examples

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#15668]
**Describe the bug**
`https://api.maptiler.com/tiles/satellite/{z}/{x}/{y}.jpg` used in multiple examples is no longer listed in MapTiler documentation and returns status 204 beyond zoom level 6.

**Expected behavior**
The following are listed, any of which should work to zoom 22 and could be used instead
`https://api.maptiler.com/tiles/satellite-v2/{z}/{x}/{y}.jpg`
`https://api.maptiler.com/maps/satellite/{z}/{x}/{y}.jpg` (tileSize 512)
`https://api.maptiler.com/maps/satellite/256/{z}/{x}/{y}.jpg`

**Comment by tschaub** [comment]
I'm able to zoom in past level 6 on https://openlayers.org/en/latest/examples/full-screen.html and see requests for [https://api.maptiler.com/tiles/satellite/{z}/{x}/{y}.jpg urls](https://api.maptiler.com/tiles/satellite/20/286136/450425.jpg?key=get_your_own_D6rA4zTHduk6KOKTXzGB) that respond as expected.  Are you still seeing 204s for the same?

I do think it makes sense to move to one of the documented tilesets, just curious where you were seeing the 204s.

**Comment by mike-000** [comment]
It does seem to vary with location.  In that example you get 204s if you zoom out and pan around.  In the WFS example on a wide screen it opens  with a mix of 204s and black tiles.
