### ISSUE TITLE
WebGL Vector Layer wrapX support

### ISSUE THREAD

**Issue by pedrolopes10** [openlayers/openlayers#15674]
Hi guys, as in a merged pull request that WebGLPointsLayer wrapX support would be nice to have the same using WebGL Vector Layer.

Example:
https://openlayers.org/en/latest/examples/webgl-vector-layer.html

Thanks

**Comment by jahow** [comment]
It should be supported already, but it looks like there is a bug: the layer is rendered again on the right but not on the left.

**Comment by pedrolopes10** [comment]
Works perfectly! Thanks
