### ISSUE TITLE
Problem with setFill() for styling VectorTile

### ISSUE THREAD

**Issue by mihailokg** [openlayers/openlayers#15681]
In ol@9.1.0 when I am creating new ol.layer.VectorTile({}) and styling it, I am having issue with setFill() which makes additional semitransparent layer at the top of the other layers.

1. Use style 
    ```js
      let selectionStyle = new ol.style.Style({
        text: new ol.style.Text({
          text: text,
          overflow: true,
          font: `12px sans-serif`,
          padding: [5, 10, 5, 10],
          textAlign: 'center',
          justify: 'center',
          textBaseline: 'middle',
          fill: new ol.style.Fill({
            color: '#fff',
          }),
          backgroundFill: new ol.style.Fill({
            color: '#454545',
          }),
          backgroundStroke: new ol.style.Stroke({
            color: '#fff',
            width: 1,
          }),
        }),
        stroke: new ol.style.Stroke({
          color: '#000',
          width: 2,
        }),
        fill: new ol.style.Fill({ color: 'rgba(255, 255, 255, 0.5)' }),
      });
    ```
2. Create layer
    ```js
      const myLayer = new ol.layer.VectorTile({
        properties: { name:'Test' },
        visible: true,
        renderMode: 'vector',
        source: new ol.source.VectorTile({
          format: new ol.format.MVT({
            idProperty: 'id',
          }),
          tileLoadFunction: ...,
          url: `some_url`,
        }),
        style: selectionStyle,
      });
    ```
3. **If I remove fill** from the style **it will be ok** and without that additional layer but I need Fill to style myLayer

If I use
```js
        selectionStyle.setFill(
          new ol.style.Fill({
            color: 'rgba(252, 220, 215, 0.5)'
          })
        );
```
it will as well make that additional ghost layer on some VectorTiles. Additionally on the web side, on mouse hover will cause map to flicker when moving cursor around.

**Expected behavior**
Fill in Style should Fill VectorTile and should not create any additional layers above. Please check notes on attached image. 

<img width="413" alt="Screenshot 2024-03-28 at 12 09 07" src="https://github.com/openlayers/openlayers/assets/27783775/4fd8876d-86e2-4dae-a6cb-9d43ece7745d">

**Comment by ahocevar** [comment]
Hard to say what's wrong without runnable code, but what happens if you remove the `backgroundFill` and `backgroundStroke`?

**Comment by mihailokg** [comment]
> Hard to say what's wrong without runnable code, but what happens if you remove the `backgroundFill` and `backgroundStroke`?

If I remove last line in Style fill: new ol.style.Fill({ color: 'rgba(255, 255, 255, 0.5)' }), then it is not colouring element and all is ok with text label everywhere, but if you want to colour those VectorTiles with fill: new ol.style.Fill({ color: 'rgba(252, 220, 215, 0.5)' }), it will draw that Ghost layer above some text labels.

If I leave "fill" option in Style I have to remove from ol.layer.VectorTile renderMode: 'vector' and to default it to 'hybrid' which render everything correctly.

**Comment by ahocevar** [comment]
It would be good to have a minimal example (jsfiddle, codepen, codesandbox or similar) that shows the problem. Maybe you can click "Edit" on https://openlayers.org/en/latest/examples/vector-tile-selection.html and modify it to expose the issue?

**Comment by mihailokg** [comment]
Check image and try this code https://codesandbox.io/p/sandbox/vector-tile-selection-forked-2l6llr

<img width="518" alt="Screenshot 2024-03-28 at 7 11 41 PM" src="https://github.com/openlayers/openlayers/assets/27783775/c8c19e54-9204-4622-8e0c-5be08ecf3a75">

**Comment by ahocevar** [comment]
Thanks for the reproduction case. `git bisect` shows that eeb4c3e2f0db9cbf417e850873198695815da9a8 is the first bad commit.

**Comment by ahocevar** [comment]
@mihailokg An easy workaround for now is to split the style into two styles, and give the text style a z-index higher than that of the fill and stroke:
```js
const selectedCountry = [
  new Style({
    stroke: new Stroke({
      color: '#000',
      width: 2,
    }),
    fill: new Fill({
      color: 'rgba(252, 220, 215, 0.5)',
    }),
  }),
  new Style({
    zIndex: 1,
    text: new Text({
      text: 'text',
      overflow: true,
      font: `12px sans-serif`,
      padding: [5, 10, 5, 10],
      textAlign: 'center',
      justify: 'center',
      textBaseline: 'middle',
      fill: new Fill({
        color: '#fff',
      }),
      backgroundFill: new Fill({
        color: '#454545',
      }),
      backgroundStroke: new Stroke({
        color: '#fff',
        width: 1,
      }),
    }),
  }),
];

**Comment by mihailokg** [comment]
Thanks for the info. Will try and see if this will resolve also flickering when mouse move. Will let you know asap.

**Comment by mihailokg** [comment]
I see in example that this is fixing issue, but for some reason in my real life code it doesn't resolve it. Just switching renderMode from vector to hybrid resolve the issue about semi transparent box above text label, but still has issues with flickering when on mouse move on the web. I am searching if something else is causing the problem.

**Comment by ahocevar** [comment]
#15685 fixes the rendering issue with what you call "ghost layers" (which actually are the polygon fills of neighboring tiles).

The other issue might be due to poor select/re-render logic in your application - you might want to take the https://openlayers.org/en/latest/examples/vector-tile-selection.html example as source for inspiration on how to do mouseover or selection with vector tiles.
