### ISSUE TITLE
IGC: new file format

### ISSUE THREAD

**Issue by llarquere** [openlayers/openlayers#15689]
**Actual flight recorders use the new format of IGC files**
The reference is at https://www.fai.org/sites/default/files/igc_fr_specification_with_al8_2023-2-1_0.pdf
Among the changes, the date (day) of flight is now stored in a new header (HFDTEDATE).
Another header (the I), which describes adds to the fixes is not computed.

**Modifying ol/format/IGC to parse more data from files .igc**
In the context of OpenLayers, not all data of the new format is usable
but some are mandatory (time of fix, exact position ...)

**Comment by ahocevar** [comment]
Are you going to provide a pull request? What are the details of the changes in the `IGC` format's API (versioning, how to obtain metadata) are you envisioning?

**Comment by llarquere** [comment]
> Are you going to provide a pull request? What are the details of the changes in the `IGC` format's API (versioning, how to obtain metadata) are you envisioning?

Yes i can do a pull-request with the two subjects (date and header I lad/lod).
But i can not figure out all the changes between the current IGC.js and the actual format used by flight-recorders.
My intent is first to display flights of my friends and mine,
and let a clean place in the code for other developers and other changes in the format.

**Comment by ahocevar** [comment]
> The whole new igc format is a lot of work and must be done "step by step" no ?

Maybe, so anything useful you can contribute is welcome. Will it be possible to detect the version of the used format (e.g. by a header in the igc file) and run the correct reader, or will users have to specify the version manually?

**Comment by llarquere** [comment]
> > The whole new igc format is a lot of work and must be done "step by step" no ?
> 
> Maybe, so anything useful you can contribute is welcome. Will it be possible to detect the version of the used format (e.g. by a header in the igc file) and run the correct reader, or will users have to specify the version manually?

The reference document (https://www.fai.org/sites/default/files/igc_fr_specification_with_al8_2023-2-1_0.pdf)
don't specify a version info in a header or part of header (as i can read ...),
and the flight recorders do not necessarily follow recommendations,

so I think not to modify the structure of the code
and take into account a (new) header (e.g. "I") when/if it is read,
thus we can ensure backward compatibility.

**Comment by ahocevar** [comment]
Fixed with #15696.
