### ISSUE TITLE
Flickering map when panning or zooming using Linux with specific font scaling (version 9.0.0 and 9.1.0)

### ISSUE THREAD

**Issue by jankosk** [openlayers/openlayers#15704]
Hello,

When upgrading OL to version 9.0.0 or version 9.1.0 I'm noticing map flickering when panning or zooming the map. This happens at least with Tile layers and Image layers.

The fix in issue [#15593](https://github.com/openlayers/openlayers/issues/15593) seemed to fix the problem for me, but it was reverted in [#15652 ](https://github.com/openlayers/openlayers/pull/15652/commits) and did not land in version 9.1.0.

Weirdly, this only happens with specific font scaling settings.

I'm using desktop Chrome with Intel graphics.

**Comment by ahocevar** [comment]
Did you try with the latest dev version? `npm install ol@dev`

**Comment by jankosk** [comment]
I tried the dev version but I still get flickering. Downgrading to 8.2.0 works.

**Comment by ahocevar** [comment]
@jankosk What is your layers stack? Just a Tile or Image layer, or combined with a Vector layer? Do you maybe have a reproduction case, or instructions on how to reproduce with one of the official examples?

**Comment by jankosk** [comment]
Unfortunately, I'm not able to reproduce this with one of the official examples. This seems to happen when a Tile layer or Image layer is combined with a custom layer. The custom layer extends the Layer class, but I haven't been able to pinpoint the exact reason for it yet.

**Comment by ahocevar** [comment]
@jankosk Can you create a minimal example with a custom layer that triggers the behavior? Usually the reason for the flickering is that the Composite map renderer thinks it can reuse the previous layer's canvas, but the renderer of the custom layer sets a different width or height on the canvas, which clears the previous content.

**Comment by jankosk** [comment]
This seems to be the case here as well. The renderer of the custom layer calculates the width and height for the canvas differently than e.g. Tile layer in the overridden `renderFrame` method. By changing the calculation of width and height to be similar with Tile layer the flickering stops.

Not sure if this is a bug with open layers anymore, but the difference in calculating the width and height is also present in version 8.2.0, but it seems to work.

**Comment by ahocevar** [comment]
> Not sure if this is a bug with open layers anymore, but the difference in calculating the width and height is also present in version 8.2.0, but it seems to work.

In 8.2.0, the container of the previous layer was not being reused in the first place, so what I described above did not happen.

**Comment by ahocevar** [comment]
@jankosk #15727 should fix this issue, at least if you change your custom layer code to not set a width and height on a reused canvas.

**Comment by jankosk** [comment]
This looks good and seems to work for me. I'm able to just call the prepareContainer method in the custom renderer and remove the width and height calculation
