### ISSUE TITLE
Map rotation causes layer clipping

### ISSUE THREAD

**Issue by tomasgreen** [openlayers/openlayers#15702]
**Describe the bug**
Rotating the map causes vector layer clipping.

![Screenshot 2024-04-05 at 08 41 38](https://github.com/openlayers/openlayers/assets/5195324/000904c2-98d5-47ae-bc58-2e1488c1226c)

**To Reproduce**
1. Create a map with a vector layer and a few poygons
2. Make sure that the size of the window is not square.
3. Rotate and pan.

**Expected behavior**
Should not be clipping the layer.

**Workaround**
Use VectorImage layer instead.

**Comment by ahocevar** [comment]
Duplicate of #15680, `npm install ol@dev` to get a fixed version.
