### ISSUE TITLE
the height of the background is not fit with text when text style set with backgrounFill

### ISSUE THREAD

**Issue by Frank-Chan** [openlayers/openlayers#15716]
**Describe the bug**
I'm setting a text label for a feature on a vector layer, and giving it a background fill to visually separate it from the background.
However, when I set the background fill, it does not span the entire height of the text label.The more lines, the greater the height of the background from the actual height.
![image](https://github.com/openlayers/openlayers/assets/8639688/5a356e71-cdcc-46d5-ae03-d2ff9f04a30f)

**To Reproduce**
1. You can see the issued demo to [codesandbox](https://codesandbox.io/p/devbox/rich-text-labels-fontstyle-forked-pc9dmd?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu7sv1tz00062a66664iq60k%2522%252C%2522sizes%2522%253A%255B82.95215869311552%252C17.04784130688448%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu7sv1ty00022a66ik1y2yp3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu7sv1tz00042a66k2g2jkx5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu7sv1tz00052a66yslk6l7x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu7sv1ty00022a66ik1y2yp3%2522%253A%257B%2522id%2522%253A%2522clu7sv1ty00022a66ik1y2yp3%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clu7sv1tz00052a66yslk6l7x%2522%253A%257B%2522id%2522%253A%2522clu7sv1tz00052a66yslk6l7x%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522cluauczsg01w02a66qfw48hfh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluauczsg01w02a66qfw48hfh%2522%257D%252C%2522clu7sv1tz00042a66k2g2jkx5%2522%253A%257B%2522id%2522%253A%2522clu7sv1tz00042a66k2g2jkx5%2522%252C%2522activeTabId%2522%253A%2522clu7svhzb00c22a66pwuz6hh9%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu7sv1ty00032a66r4l35cu4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu7szyls000cdcguecv75id0%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clu7svhzb00c22a66pwuz6hh9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Afalse%252C%2522sidebarPanelSize%2522%253A0%257D)

2. The main code is below:
```js
import GeoJSON from 'ol/format/GeoJSON.js';
import Map from 'ol/Map.js';
import VectorLayer from 'ol/layer/Vector.js';
import VectorSource from 'ol/source/Vector.js';
import View from 'ol/View.js';
import {Fill, Stroke, Style, Text} from 'ol/style.js';

const map = new Map({
  target: 'map',
  view: new View({
    center: [0, 0],
    zoom: 2,
    extent: [-13882269, 2890586, -7456136, 6340207],
    showFullExtent: true,
  }),
});

const labelStyle = new Style({
  text: new Text({
    //font: '13px Calibri,sans-serif',
    font: '13px Microsoft,Yahei',
    fill: new Fill({
      color: '#000',
    }),
    stroke: new Stroke({
      color: '#fff',
      width: 4,
    }),
    padding: [0, 0, 0, 0],
    overflow: false, 
  }),
});
const countryStyle = new Style({
  fill: new Fill({
    color: 'rgba(255, 255, 255, 0.6)',
  }),
  stroke: new Stroke({
    color: '#319FD3',
    width: 1,
  }),
});

const vectorLayer = new VectorLayer({
  background: 'white',
  source: new VectorSource({
    url: 'https://openlayers.org/data/vector/us-states.json',
    format: new GeoJSON(),
  }),
  style: function (feature) {
    const id = feature.getId();
    const textStyle = labelStyle.getText();
    textStyle.setFont('13px Calibri,sans-serif');
    textStyle.setBackgroundFill(
      new Fill({
        color: 'blue',
      })
    );
    textStyle.setBackgroundStroke(
      new Stroke({
        color: 'red',
        width: 2,
      })
    );
    textStyle.setStroke(
      new Stroke({
        color: '#b4ebaf',
        width: 4,
      })
    );
    textStyle.setText([
      id,
      'bold 23px/23px Times,New,Roman',
      '\n',
      '',
      ` ${feature.get('name')}`,
      '900 11px/11px Times,New,Roman',
      '\n',
      '',
      `${feature.get('density')} people/mi²`,
      'italic 11px/11px Calibri,sans-serif',
    ]);
    return [countryStyle, labelStyle];
  },
});

map.addLayer(vectorLayer);
```
**Expected behavior**
The background height equal to the text height .

**Comment by ahocevar** [comment]
The codesandbox you provided does not work for me, but it looks like you're using fonts that are not available, which could be the source of the problem.

**Comment by Frank-Chan** [comment]
> The codesandbox you provided does not work for me, but it looks like you're using fonts that are not available, which could be the source of the problem.

I have been paste the code，and find the problem is from the  function 'getTextDimensions'，which is in the js file 'ol/render/canvas.js'。The solution that i can think of is below:
![image](https://github.com/openlayers/openlayers/assets/8639688/fad66a00-21dd-433d-8e06-9eea91f24b01)

**Comment by ahocevar** [comment]
Thanks @Frank-Chan, now I see the problem. You are right. Would you be able to create a pull request with your suggested fix?

**Comment by Frank-Chan** [comment]
Created [pull#15717](https://github.com/openlayers/openlayers/pull/15717)
