### ISSUE TITLE
Update MapTiler maps in examples

### ISSUE THREAD

**Issue by bolollo** [openlayers/openlayers#15721]
**Describe the bug**
Some examples use maps that are outdated or old versions.

**To Reproduce**
List of examples:

- https://openlayers.org/en/latest/examples/declutter-group.html
- https://openlayers.org/en/latest/examples/layer-zoom-limits.html
- https://openlayers.org/en/latest/examples/mapbox-layer.html
- https://openlayers.org/en/latest/examples/offscreen-canvas.html
- https://openlayers.org/en/latest/examples/topojson.html
- https://openlayers.org/en/latest/examples/xyz-retina.html
- https://openlayers.org/en/latest/examples/mapbox-style.html

**Expected behavior**
Update to a new version or change to an updated style

**Comment by ahocevar** [comment]
Thanks @bolollo. Are you able to provide a pull request with updates to these examples?

**Comment by bolollo** [comment]
Yes, @ahocevar I'll prepare a PR with the updates. Thanks
