### ISSUE TITLE
How to get extent

### ISSUE THREAD

**Issue by Lazydd** [openlayers/openlayers#15729]
I don't know how to set this value
![image](https://github.com/openlayers/openlayers/assets/71319962/3ad6d7e9-3aa5-411d-9937-527b0e9343fd)

**Comment by ahocevar** [comment]
You only need to do this when you want to restrict panning of the map to a known bounding box, e.g. of a country. If the bounding box is known in geographic coordinates, you can calculate these values with
```js
extent: [...fromLonLat([lowerLeftLon, lowerLeftLat], ...fromLonLat([upperRightLon, upperRightLat])]
```
