### ISSUE TITLE
declutter change from v8 to v9

### ISSUE THREAD

**Issue by rgreenwood** [openlayers/openlayers#15745]
The release notes for v9 say "_Decluttered items in Vector and VectorTile layers now maintain the render order of the layers and within a layer. They do not get lifted to a higher place in the stack any more._" My issue may be related this and maybe I just don't understand the full implications of this change or what's being said in the release notes. 
With v8 the label for the bottom polygon layer is above the feature in the top line layer:
![image](https://github.com/openlayers/openlayers/assets/2641005/4f359fb0-3eea-4170-9635-422de007fcb2)
With v9 I the label for the bottom polygon layer is under the line feature on the layer above it:
![image](https://github.com/openlayers/openlayers/assets/2641005/a243e017-ab40-482c-a2d2-b91e88c8e0e8)
Is this the expected behavior? I assumed that all labels were lifted above all features before decluttering. 

**main.js**
```js
import {Feature, Map, View} from 'ol/index.js';
import {Vector as VectorLayer} from 'ol/layer.js';
import {LineString} from 'ol/geom.js';
import {Vector as VectorSource} from 'ol/source.js';
import {fromExtent} from 'ol/geom/Polygon.js';
import {getCenter} from 'ol/extent.js';
import {Style, Fill, Stroke, Text} from 'ol/style.js';
import {VERSION} from 'ol/util.js';

const square = [-12e6, 3.5e6, -10e6, 5.5e6];
const polyLayer = new VectorLayer({
  declutter: true, // 'separate',
  source: new VectorSource({
    features: [
      new Feature({
        geometry: fromExtent(square),
      }),
    ],
  }),
  style: new Style({
    fill: new Fill({
      color: '#77f'
    }),
    text: new Text({
      font: 'bold 14px sans-serif',
      stroke: new Stroke({color: '#ffffff', width: 6}),
      text: 'Polygon\nLabel',
    })
  })
});

const lineLayer = new VectorLayer({
  // declutter: true, // 'separate',
  source: new VectorSource({
    features: [
      new Feature({
        geometry: new LineString([[-12e6, 3.5e6], [-10e6, 5.5e6]]),
      }),
    ],
  }),
  style: new Style({
    stroke: new Stroke({
      color: '#f00',
      width: 12
    }),
  })
});

window.map = new Map({
  target: 'map',
  view: new View({
    center: getCenter(square),
    zoom: 3,
  }),
  layers: [polyLayer, lineLayer],
});

console.log(VERSION);
```
**index.html**
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Declutter Test</title>
    <link rel="stylesheet" href="node_modules/ol/ol.css">
    <style>
      .map {
        width: 100%;
        height: 400px;
      }
    </style>
  </head>
  <body>
    <div id="map" class="map"></div>
    <script type="module" src="main.js"></script>
  </body>
</html>
```

**package.json**
```js
{
  "name": "declutter-test",
  "dependencies": {
    // one of the other:
    "ol": "8.2.0"
    "ol": "9.1.0"
  },
  "devDependencies": {
    "vite": "^3.2.3"
  },
  "scripts": {
    "start": "vite",
    "build": "vite build"
  }
}
```

**Comment by ahocevar** [comment]
What you're observing is exactly what the release notes meant. The render order is now the same, regardless of the `declutter` setting of the layer. If you now want the polygon labels to be on top of the line layer, you'd need to add a third layer, which can use the same source as the first, but with a style that only renders the labels. This won't have any performance implications.

**Comment by rgreenwood** [comment]
Got it. I was afraid that would be the answer.
