### ISSUE TITLE
openlayers circle markers cut off at border with WMS tile

### ISSUE THREAD

**Issue by Mujahid-Iqbal** [openlayers/openlayers#15747]
How can I resolve this?

import Tile from 'ol/layer/Tile';
import TileWMS from 'ol/source/TileWMS';

export function wmsLayer(layerName: string) {
  const wmsSource = new TileWMS({
    url: ***********',

    params: { LAYERS: layerName, MAP: layerName, TILED: false, FORMAT: 'image/png' },

    serverType: 'mapserver',
    
    projection: 'EPSG:3857',
  });
  

  // Creating the TileLayer
  const tileLayer = new Tile({
    source: wmsSource,
    visible: false,
    opacity: 0.6,
    zIndex: 15
  });
  tileLayer.setProperties({ layerName: layerName });
  return tileLayer;
}

![Screenshot from 2024-04-16 11-57-27](https://github.com/openlayers/openlayers/assets/96714960/dd468e6b-01e9-4221-810a-83331258cc36)

**Comment by mprins** [comment]
add a gutter: https://openlayers.org/en/latest/apidoc/module-ol_source_TileWMS-TileWMS.html

**Comment by Mujahid-Iqbal** [comment]
Thank you soo much!! @mprins
