### ISSUE TITLE
map.removeLayer() on a VectorLayer with `declutter` causes other vector layers to disappear

### ISSUE THREAD

**Issue by malaretv** [openlayers/openlayers#15766]
**Describe the bug**

As of recent builds calling `map.removeLayer()` on a VectorLayer when `declutter` is enabled causes all vector layers to disappear.

**To Reproduce**
Steps to reproduce the behavior
(Apologies for not linking directly to an example as CodeSandbox won't let users create their own drafts anymore without paying)

1. Go to https://openlayers.org/en/latest/examples/vector-labels.html
2. Edit codesandbox example to add `declutter: true` to vectorPoints layer definition. Then add the following at the end of the example code:
```js
 setTimeout(() => {
  map.removeLayer(vectorPoints)
}, 2000);
```
3. Run example, and watch layers disappear after 2 seconds when `map.removeLayer` is called

**Expected behavior**
Only the requested layer should disappear from map

**Comment by M393** [comment]
I was just looking into why some of my features area disappearing...

**Comment by ahocevar** [comment]
Thanks @malaretv @M393 for the detailed descriptions. #15768 will fix this.
