### ISSUE TITLE
Potential type bug in vector layer types in combination with render features

### ISSUE THREAD

**Issue by sebakerckhof** [openlayers/openlayers#15764]
**Describe the bug**
I'm looking into ways to improve performance of large geojson sets.
I found the RenderFeature in the API docs and wanted to give it a try, but although I can create a vector source with it, the types of the vector layer do not accept this source.

**To Reproduce**
In a typescript project, create:
```
const source = new VectorSource<RenderFeature>();
const layer = new VectorLayer({ source });
```

Then you'll get a type error: `Type 'VectorSource<RenderFeature>' is not assignable to type 'VectorSource<Feature<Geometry>>'.`

Either I'm not understanding how to use the RenderFeature, or the type is too strict.

**Comment by ahocevar** [comment]
What about
```js
const source = new VectorSource({
  format: new GeoJSON({
    featureClass: RenderFeature
  }),
  url: 'your-data.geojson'
});

**Comment by sebakerckhof** [comment]
That would work, but then I could as well just cast `as VectorSource<Feature>`.
But it's not clear to me if `VectorLayer` is supposed to work with vector sources containing render features, and if so, isn't it a bug that the cast is needed?

**Comment by ahocevar** [comment]
The VectorSource does work with RenderFeature features in v9.x. And you don't need a type cast, you just need to define the type. Did you do this with a version older than 9.x? The following works fine for me with v9.1.0:
```ts
import VectorSource from "ol/source/Vector.js";
import GeoJSON from "ol/format/GeoJSON.js";
import RenderFeature from "ol/render/Feature.js";

const source = new VectorSource<RenderFeature>({
  format: new GeoJSON({ featureClass: RenderFeature }),
});

const features = source.getFeatures();
console.log(features);

**Comment by sebakerckhof** [comment]
Yes, that works, but passing that source to the vector layer is what gives the error. 
I didn't try this pre 9.x

**Comment by sebakerckhof** [comment]
Yes, but passing that source to VectorLayer would give an error.

The code you posted first works because it types the source as `VectorSource<Feature<Geometry>>`.
In that case I can pass it to the VectorLayer, but 
```
const features: RenderFeature[] = source.getFeatures();
```
Gives an error that Feature is not assignable to RenderFeature

On the other hand, if I type the VectorSource as `VectorSource<RenderFeature>>`, then passing it to the layer gives an error.

**Comment by ahocevar** [comment]
#15767 will fix this.
