### ISSUE TITLE
ImageLayer ImageStatic has incorrect vertical position on map on zoom levels <6.

### ISSUE THREAD

**Issue by gsaukov** [openlayers/openlayers#15778]
A Large Static image layer on a map is sometimes incorrectly shifted north tens of kilometres. 
However when zooming in to zoom level >10 it is always correct.

See screenshot below, London is shifted north tens of kilometres. Sometimes shift could be even hundreds.

<img width="683" alt="Screenshot 2024-04-26 at 16 25 41" src="https://github.com/openlayers/openlayers/assets/48772739/51047270-eb6d-463d-a289-b935950734c7">

![Screenshot 2024-04-26 at 17 00 42](https://github.com/openlayers/openlayers/assets/48772739/5f0bcc7b-94a9-46df-ac2a-0c46b0884879)

```
    let map = new ol.Map({
        target: 'map',
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM()
            })
        ],
        view: new ol.View({
            center: ol.proj.fromLonLat([4.992, 54.1]),
            zoom: 3
        })
    });
    let extent = [-30.00791652541571,29.099583419121316,-0.00791664423876881,59.09958329838346]
    let projection = new ol.proj.Projection({code:'EPSG:4326'})
    let imageStatic = new ol.source.ImageStatic({
        url: "https://raw.githubusercontent.com/gsaukov/ghsl-client/master/src/assets/90ss/GHS_POP_E2025_GLOBE_R2023A_4326_90ss_V1_0_R2_C6.png",
        imageExtent: extent,
        attributions: 'none',
        projection: projection,
        interpolate: false,
    })
    // static image
    let imageLayer = new ol.layer.Image({
        source: imageStatic,
        opacity: 1,
        visible: true,
    });

    map.addLayer(imageLayer);
```

Please take a look at [codepen](https://codepen.io/gsaukov/pen/abxMYdw) where you can easily reproduce it.

OL version 8.2.0

**Comment by mike-000** [comment]
That is caused by creating a new projection

    let projection = new ol.proj.Projection({code:'EPSG:4326'})

which does not have `extent` or `getPointResolution` defined.

Instead you should use the predefined projection which includes those

    let projection = ol.proj.get('EPSG:4326')

**Comment by gsaukov** [comment]
@mike-000 WOW thank you so much. Works exactly as i need! So if anyone is making the same mistake he knows the answer!
