### ISSUE TITLE
VectorTile renderMode vector Firefox regression

### ISSUE THREAD

**Issue by keepitrealsimple** [openlayers/openlayers#15772]
**Describe the bug**
Firefox gets pretty much stuck when using VectorTile renderMode vector. It looks like GPU utilization goes 100% and won't come down. Tested on Windows and Mac. Chrome, Edge and Safari seems to work ok but maybe get a little bit slower. Issue is present on OL 9.1.0 and it was working fine in OL 8.2.0.

**To Reproduce**
1. See attachment zip -> Extract -> npm install -> npm start (It is fork from https://openlayers.org/en/latest/examples/canvas-tiles-tms.html with added renderMode:vector)
2. Zoom all the way up -> zoom all the way in -> zoom all up -> zoom all in -> Try to move map
3. Browser becomes unresponsive

**Expected behavior**
Map should work without jamming browser with normal usecase

[ol-910-firefox-mvt-rendermode-bug.zip](https://github.com/openlayers/openlayers/files/15104296/ol-910-firefox-mvt-rendermode-bug.zip)

**Comment by ahocevar** [comment]
Thanks for the report. I can reproduce the issue. I'm working on improvements.
