### ISSUE TITLE
VectorLayer Canvas is wrongly transformed/sized in vesion 9.1.0 when map is rotated 90 degrees.

### ISSUE THREAD

**Issue by BeGj** [openlayers/openlayers#15777]
**Describe the bug**
The VectorLayer canvas has both wrong height, width and a weird CSS transformation when the map is rotated 90 degrees. This makes vectors disappear when close to the left or right side of the map container. This only happens in version 9-1 and not in 9.0.0 or 8.2.0
![image](https://github.com/openlayers/openlayers/assets/357860/eab710fa-33d2-4adc-ac88-c78273ad6333)
![image](https://github.com/openlayers/openlayers/assets/357860/53f7ecc8-6b4a-4379-b355-40e14be540f3)

**To Reproduce**
See instructions and code in https://github.com/BeGj/ng-openlayers-canvas-bug
For those unfamiliar with angular you can see the relevant code in https://github.com/BeGj/ng-openlayers-canvas-bug/blob/main/src/app/app.component.ts and https://github.com/BeGj/ng-openlayers-canvas-bug/blob/main/src/app/app.component.html

**Expected behavior**
The VectorLayer canvas should be equal size as the rest of the map container so that the vectors do not clip outside without being outside the actual view.

**Comment by BeGj** [comment]
Update: Does not happend in v9.0.0, only v9.1.0

**Comment by BeGj** [comment]
Looks like the same bug as in https://github.com/openlayers/openlayers/issues/15680 that was supposed to be fixed in https://github.com/openlayers/openlayers/pull/15683

**Comment by BeGj** [comment]
If this is fixed in https://github.com/openlayers/openlayers/pull/15683, when is 9.1.1 planned on begin released? @ahocevar

**Comment by ahocevar** [comment]
@BeGj For now you can `npm install ol@dev`. v9.2 will be released soon.
