### ISSUE TITLE
WebGLTileLayer with palette style stops working after map.removeLayer/map.addLayer

### ISSUE THREAD

**Issue by malaretv** [openlayers/openlayers#15786]
**Describe the bug**
WebGLTileLayers with a style that includes a palette seem to break when removed and added back to map.

**To Reproduce**
1. Go to https://codesandbox.io/p/sandbox/cog-style-forked-2vg3p9?file=%2Findex.html%3A22%2C68 (A modified cog-style example w/ a button added to `addLayer()`/`removeLayer()` from map)
2. Click 'Add / Remove layer' button multiple times and see there is no problem.
3. Switch layer style to 'NDVI w/ palette 1'
4. Click 'Add / Remove layer' button multiple times and see there is now a black layer
5. Note in console warnings/errors (vary by browser) something along the lines of:
`WebGL warning: bindTexture: `tex` is from a different (or lost) WebGL context.` or `WebGL: INVALID_OPERATION: bindTexture: object does not belong to this context`

**Expected behavior**
That the WebGLTileLayer shows with proper style when added back to map

**Comment by tschaub** [comment]
Thanks for the report, @malaretv.  I've proposed a fix in #15787.

Hope you're well.

**Comment by malaretv** [comment]
Thanks to you @tschaub!! And likewise :)
