### ISSUE TITLE
Graticules badly rendered on certain projections

### ISSUE THREAD

**Issue by oxyeez** [openlayers/openlayers#15784]
**Describe the bug**
Since 9.1.0, when using a polar projection (eg: EPSG:32661), the graticules are not rendered on the entire extent when the map is rotated. Looks like the map is rotated but not the extent of the graticules layer.

**To Reproduce**
1. Go to [this exemple](https://openlayers.org/en/latest/examples/reprojection-by-code.html)
2. Search for "EPSG:32661" projection
3. Toggle "Show graticule"
4. Rotate the map for about 45° using shift+alt+drag

**Expected behavior**
The graticule layer is not rendered on the full extent.

![image](https://github.com/openlayers/openlayers/assets/72406368/9fe3debc-8ae0-4c9e-9c19-dfba96bd5307)

**Comment by mike-000** [comment]
It seems to be fixed in the development version https://openlayers.org/en/main/examples/reprojection-by-code.html (see #15683)

**Comment by oxyeez** [comment]
Oh great, I haven't seen this merge request. I close the issue.
