### ISSUE TITLE
DomException on WMS imageloaderror

### ISSUE THREAD

**Issue by PhilippeTh** [openlayers/openlayers#15794]
**Describe the bug**
When querying data from a *time-aware* WMS source, the data continually updates as time progresses and thus times that are far in the past will become unavailable as new times are getting added. If you query for such a layer on a timestep that is no longer available, you will get something like this as a result to let you know:
```
<ogc:ServiceExceptionReport xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd">
<script/>
<ogc:ServiceException code="NoMatch" locator="time">temps en dehors des heures valides / time outside valid hours</ogc:ServiceException>
</ogc:ServiceExceptionReport>
```

I'm currently using OpenLayers V6.15.1 in my application, where I simply use the imageloaderror and it works as expected:
```
imageLayer.getSource().on("imageloaderror", (e) => {
  // handle error and update time information
});
```

When using latest versions of OpenLayers (`>6.15.1`), when querying for WMS layers for a time that has expired, the error doesn't get handled inside the imageloaderror and when you look at the console, you will see `DOMException: The source image cannot be decoded.` even though it should be handled right there.

**To Reproduce**
Here's a codesandbox where I took your basic tutorial with WMS layers and added the imageloaderror handler and queried for an expired time: [wms-image DomException](https://codesandbox.io/p/sandbox/wms-image-domexception-j6r7kn?file=%2Fmain.js%3A34%2C52&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvqqfd7x0006356ixrbrcrzc%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvqqfd7w0002356ijzrsou1j%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvqqfd7w0003356ie7jqnlz2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvqqfd7x0005356iig16ie3u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvqqfd7w0002356ijzrsou1j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvqqfd7w0001356i864uhbju%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvqylbc00002356iwh4vvkrp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A34%252C%2522startColumn%2522%253A52%252C%2522endLineNumber%2522%253A34%252C%2522endColumn%2522%253A52%257D%255D%252C%2522filepath%2522%253A%2522%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvqqfd7w0002356ijzrsou1j%2522%252C%2522activeTabId%2522%253A%2522clvqylbc00002356iwh4vvkrp%2522%257D%252C%2522clvqqfd7x0005356iig16ie3u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvqqfd7w0004356imueuf2da%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvqqfd7x0005356iig16ie3u%2522%252C%2522activeTabId%2522%253A%2522clvqqfd7w0004356imueuf2da%2522%257D%252C%2522clvqqfd7w0003356ie7jqnlz2%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvqqfd7w0003356ie7jqnlz2%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Open the browser console and you'll see that the DOMException appears in the console.

**Expected behavior**
The error for that layer should be handled entirely from imageloaderror instead of triggering the imageloaderror + a DomException that's unhandled.

**Comment by ahocevar** [comment]
This is nothing to worry about, @PhilippeTh. The DOMException you're seeing is a handled exception and triggers a fallback to a different decoding method. Your users won't see the DOMException.

**Comment by PhilippeTh** [comment]
Ah well then if it's desired behavior @ahocevar then you can close this ticket right away. I wasn't upgrading past 6.15.1 because I thought the newer versions introduced an error during error handling. I'll just open a ticket on my side to ignore that error if anyone asks and proceed to upgrade to 9.1 as this was the only blocker. Thanks!
