### ISSUE TITLE
As map rotates the map view gets more narrow and does not fill original width

### ISSUE THREAD

**Issue by hardin13** [openlayers/openlayers#15795]
**Describe the bug**
As map rotates the map view gets more narrow and does not fill original width of the map. 

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/vector-layer.html
2. Zoom in on the vector layer so if fills the entire screen then use control + shift to rotate the map. 
3. As you rotate from 70 to 110 degrees the view will get narrower then wider again. 
![image](https://github.com/openlayers/openlayers/assets/14926835/5d97dd13-7457-4cef-b3dc-ab0847768c27)

**Expected behavior**
The width of the view should not change.

**Comment by mike-000** [comment]
Similiar to #15784 and fixed in https://openlayers.org/en/main/examples/vector-layer.html

**Comment by hardin13** [comment]
Thanks. Looks like that version should solve it. Any ideas when 9.1.1 will be production?

**Comment by ahocevar** [comment]
v9.2 will be released soon. In the meantime, `npm install ol@dev`.
