### ISSUE TITLE
DEV: VectorLayer with `declutter` and `opacity` < 1 does not clear between renders

### ISSUE THREAD

**Issue by malaretv** [openlayers/openlayers#15793]
**Describe the bug**
I was testing out latest npm release `9.1.1-dev.1714573976514` in my application to try out some recent fixes.
I noticed that `VectorLayer`s with `declutter` and `opacity` < 1 now do not clear between renders

**To Reproduce**
1. Go to https://codesandbox.io/p/sandbox/vector-layer-forked-2x8f83?file=%2Fmain.js%3A15%2C5
The above is a modifed version of the Vector Layer example with `opacity: 0.8` and `declutter: true` added to layer 
3. Pan the map, notice layer rerenders with no clearing of the previous frame.

<img width="784" alt="Screenshot 2024-05-03 at 09 57 57" src="https://github.com/openlayers/openlayers/assets/381932/53a78f52-9edf-421e-b289-623942977cfc">

**Comment by ahocevar** [comment]
Thanks for reporting this, @malaretv. Working on a fix now.
