### ISSUE TITLE
Clipped features in rotated view

### ISSUE THREAD

**Issue by marcovo-peercode** [openlayers/openlayers#15797]
**Describe the bug**
In a rotated view, features are clipped unnecessarily. This leads to features missing on the map, where they should actually be drawn. This only seems to affect non-square views.

**To Reproduce**
1. Go to the [cluster example](https://openlayers.org/en/latest/examples/cluster.html) (Is there a way to fix 'latest' to '9.1.0'?)
2. Zoom in such that the entire view is filled with features
3. Rotate the view using alt+shift
4. Starting at a specific rotation (in my own case 59 degrees, but presumably dependent on the aspect ratio), the features can seen to be clipped

**Expected behavior**
The features should not disappear upon rotating.

**Versions**
As far as I can tell, this bug was introduced in version 9.1.0. Version 9.0.0 does seem to work as expected.

Screengrab:
![Naamloos](https://github.com/openlayers/openlayers/assets/48310153/cb9ad3c3-fb39-444d-90b3-1a03983ca1ef)

**Comment by mike-000** [comment]
See #15795

**Comment by marcovo-peercode** [comment]
Ah I did look in open issues but forgot to search closed issues. Good to see it has been picked up.
