### ISSUE TITLE
webgltilelayer style filter

### ISSUE THREAD

**Issue by nssang00** [openlayers/openlayers#15805]
**Describe the bug**

In openlayers v9.1.0, filter is used when applying the style of WebGLVectorTileLayerRenderer, and the three filters below work.
geometry-type does not work.
filter: ['==', ['get', 'layer'], 'water'],
filter: ['<=', ['resolution'], 10],
filter: ['>=', ['zoom'], 9],

LineString also doesn't work.
filter:['==',['geometry-type'],'Polygon']

**To Reproduce**
3. See error

**Expected behavior**

**Comment by nssang00** [comment]
```javascript
//ol/render/canvas/style.js
export function rulesToStyleFunction(rules) {
  const parsingContext = newParsingContext();
  const evaluator = buildRuleSet(rules, parsingContext);
  const evaluationContext = newEvaluationContext();
  return function (feature, resolution) {
    evaluationContext.properties = feature.getPropertiesInternal();
    evaluationContext.resolution = resolution;
   // if (parsingContext.featureId) {
      const id = feature.getId();
      if (id !== undefined) {
        evaluationContext.featureId = id;
      } else {
        evaluationContext.featureId = null;
      }
    }
 //   if (parsingContext.geometryType) {  //Since this part is not true, the geometry value cannot be obtained.
      evaluationContext.geometryType = computeGeometryType(
        feature.getGeometry(),
      );
    }
    return evaluator(evaluationContext);
  };
}
```

**Comment by jahow** [comment]
Thank you for your report, indeed the geometry type had somehow become unusable in expressions. I have come up with a fix, see https://github.com/openlayers/openlayers/pull/16087

**Comment by jahow** [comment]
Hey @nssang00 , the issue should be fixed on main, could you please try the latest version and confirm that it works? Thanks
