### ISSUE TITLE
Multistyle multigeometry draw bug

### ISSUE THREAD

**Issue by levelost** [openlayers/openlayers#15819]
**Version 9.1.0**

**Describe the bug**
If a feature contains multi-geometry (for example, Multipoint) and several styles, then the rendering is performed in a sequence of styles, which is why the points look incorrect.
![multi](https://github.com/openlayers/openlayers/assets/41239674/ea3edec2-0907-40a2-97b2-dba8f5337585)

**To Reproduce**
1. Create multipoint feature.
2. Set style array with icon (subsequent icons are smaller than previous ones).
3. Zoom out.

**Expected behavior**
I would like to see a rendering similar to several single points with the expected ZIndex.

**Comment by ahocevar** [comment]
@levelost Can you please explain in more detail (or provide a mock image) of what you'd expect to see? The above image looks correct to me. Also, it would be good if you could share the code that produced the above image, to make sure we're talking about the same thing.

**Comment by levelost** [comment]
```js
const styles = [
  new Style({
    image: new CircleStyle({
      radius: 10,
      fill: new Fill({color: '#000'}),
      stroke: new Stroke({color: '#f00', width: 2})
    })
  }),
  new Style({
    image: new CircleStyle({radius: 6, fill: new Fill({color: '#fff'})})
  })
];

const layer = new VectorLayer({
    source: new Vector({
      features: [
        new Feature({geometry: new Point([-100000, -100000])}),
        new Feature({geometry: new Point([100000, -100000])}),
        new Feature({geometry: new Point([100000, 100000])}),
        new Feature({geometry: new Point([-100000, 100000])})
      ]
    }),
    style: () => styles
});
```
![1](https://github.com/openlayers/openlayers/assets/41239674/d2b9a2ee-b99d-4304-828e-cf501c7002f7)

```js
const layer = new VectorLayer({
  source: new Vector({
    features: [
      new Feature({
        geometry: new MultiPoint([
          [-100000, -100000],
          [100000, -100000],
          [100000, 100000],
          [-100000, 100000]
        ])
      })
    ]
  }),
  style: () => styles
});
```
![2](https://github.com/openlayers/openlayers/assets/41239674/15a10830-7318-4ed2-a1de-4eab2dbf9c6a)

**Comment by ahocevar** [comment]
The rendered result you're seeing is correct and intentional. If you want the points of a feature with a MultiPoint geometry rendered as if they were distinct features with Point geometries, you'd have to use a style like this:
```js
const points = (geometry) => [
  new Style({
    geometry,
    image: new Circle({
      radius: 10,
      fill: new Fill({color: '#000'}),
      stroke: new Stroke({color: '#f00', width: 2}),
    }),
  }),
  new Style({
    geometry,
    image: new Circle({radius: 6, fill: new Fill({color: '#fff'})}),
  }),
];

layer.setStyle((feature) =>
    feature
      .getGeometry()
      .getPoints()
      .map((point) => styles(point))
      .flat())
```
