### ISSUE TITLE
viewport Bug

### ISSUE THREAD

**Issue by jak983464779** [openlayers/openlayers#15817]
Using the Vue framework, a universal component was encapsulated, and two maps were created by introducing the component on one page;
The newly created one will be displayed normally, while the previous one will not be displayed. The dom structure
The first created canvas in the middle was lost
![image](https://github.com/openlayers/openlayers/assets/49120355/ab4050ef-c9c2-44df-aaf8-bdd878af4f29)
![image](https://github.com/openlayers/openlayers/assets/49120355/d62c0f2f-c88f-4e37-ac97-8c88962b531f)

First creation：no has canvas
![image](https://github.com/openlayers/openlayers/assets/49120355/9f9b13c5-ddb6-4f93-b290-add25854e948)

Second creation：has canvas
![image](https://github.com/openlayers/openlayers/assets/49120355/4d0b2ba8-c705-45f6-a601-ddfed88b4fb8)

**Comment by ahocevar** [comment]
You cannot share layers between maps. Without seeing your code, I guess that's the problem. However, sources can be shared between layers.
