### ISSUE TITLE
Regression on Drawing Rectangle with RenderEvent.context (Rotating the Map)

### ISSUE THREAD

**Issue by ismailsunni** [openlayers/openlayers#15820]
**Describe the bug**
We have a code to draw a rectangle to visualize an area of interest. It has semi transparent outer black filling and a transparent rectangle in the middle.
It has fixed size and location relative to the map view (i.e. it will stay there no matter what we do: pan, zoom, or rotate). It works as expected when we use OL 9.0.0.

![image](https://github.com/openlayers/openlayers/assets/1421861/fc7c0967-bc19-4d1c-b243-81fa457d8522)

Unfortunately, when we upgrade to 9.1.0, there is an issue when we rotate the map (e.g. using ALT+SHIFT+mouse movement). The rectangle is moved around.
![image](https://github.com/openlayers/openlayers/assets/1421861/d51e0e87-2c6a-4da4-8f3e-95cc1969584c)

I have created a codesanbox to show the bug.
- with OL 9.0.0: https://codesandbox.io/p/sandbox/print-rectangle-ol-9-0-0-swfsyr
- with OL 9.1.0: https://codesandbox.io/p/sandbox/print-rectangle-ol-9-1-0-nfcw7n
- with OL 9.1.1-dev.1715581613988: https://codesandbox.io/p/sandbox/print-rectangle-ol-9-1-1-dev-w95y9m

**To Reproduce**
1. Open the codesandbox links above
2. Try to rotate the maps with ALT+SHIFT+mouse movement
3. The one with OL 9.0.0 will rotate the basemap, but the rectangle stay in the location. The one with OL 9.1.0 will move the rectangle.

**Expected behavior**
I expect that the behaviour stays the same as in OL 9.0.0 where it stays in the same location even if we rotate the map.

**Comment by ahocevar** [comment]
@ismailsunni Your sandboxes are private, so I cannot view them. Anyway, I think this issue is the same as #15680. If so, it is fixed already in `ol@dev`.

**Comment by mike-000** [comment]
I managed to access the v9.0.0 sandbox.  It is not the same issue as #15680.  You should use `getRenderPixel` as in https://openlayers.org/en/latest/examples/layer-swipe.html to calculate your pixel positions instead of assuming the orientation of the canvas.

**Comment by ismailsunni** [comment]
hi @ahocevar thanks for the reply.

I have tried with `ol@dev`, but it still has similar issue (although different in term of how it move). I have the sandbox for `ol@dev` [here](https://codesandbox.io/p/sandbox/print-rectangle-ol-9-1-1-dev-w95y9m).

I also have fixed the links to the sandboxes in my issue above so you can access it (there was a typo in the URL).

Some gif for illustration:
OL v9.0.0 (normal):
![Peek 2024-05-13 22-00 - OL v9 0 0 normal](https://github.com/openlayers/openlayers/assets/1421861/02bcf64e-e84e-4941-a352-e806ceed1bdd)

OL v9.1.0 (bug)
![Peek 2024-05-13 21-59 - bug OL v9 1 0](https://github.com/openlayers/openlayers/assets/1421861/38ff9309-3e6e-41ed-9e0b-411e3b86b6a8)

OL v9.1.1-dev.1715581613988 (bug):
![Peek 2024-05-13 21-59 - bug OL v9 1 1-dev](https://github.com/openlayers/openlayers/assets/1421861/9a6a16e5-82b1-42c3-a0a9-536a8ab3fbd0)

**Comment by ismailsunni** [comment]
hi @mike-000 
thanks, your hint seems promising. I will try tomorrow.

But, it seems there is some changes in 9.1.0 that create the regresion. Because previously I don't need to do anything more to make it work.

**Comment by mike-000** [comment]
> it seems there is some changes in 9.1.0

Yes, the vector layer now shares a canvas with the tile layer, which rotates as the view rotates.

Even before that change your example could have worked without a vector layer, you could have applied the postrender processing directly to the tile layer using `getRenderPixel` to calculate the pixel positions.

**Comment by ahocevar** [comment]
@ismailsunni Here is the postrender code that will work with any layer in any version:
```js
tileLayer.on('postrender', function (event) {
  const context = event.context;
  const size = map.getSize();
  const [width, height] = size;
  const [minx, miny] = size.map((n) => n * 0.25);
  const [maxx, maxy] = size.map((n) => n * 0.75);

  context.save();
  context.beginPath();
  // Outside polygon, must be clockwise
  context.moveTo(...getRenderPixel(event, [0, 0]));
  context.lineTo(...getRenderPixel(event, [width, 0]));
  context.lineTo(...getRenderPixel(event, [width, height]));
  context.lineTo(...getRenderPixel(event, [0, height]));
  // Inner polygon, must be counter-clockwise
  context.moveTo(...getRenderPixel(event, [minx, miny]));
  context.lineTo(...getRenderPixel(event, [minx, maxy]));
  context.lineTo(...getRenderPixel(event, [maxx, maxy]));
  context.lineTo(...getRenderPixel(event, [maxx, miny]));

  context.closePath();
  context.fillStyle = 'rgba(0, 5, 25, 0.75)';
  context.fill();
  context.restore();
});
```

See it live: https://codesandbox.io/p/sandbox/print-rectangle-ol-9-1-1-dev-forked-fm5vph

@mike-000's advice to always use `getRenderPixel()` when drawing to a canvas in a postrender event is correct.

Your code worked by chance in v9.0.0, because it played well with internal implementation details by that time. This isn't a regression or a bug in OpenLayers, but apologies for the internal change that broke your code.

**Comment by ismailsunni** [comment]
Thanks @ahocevar and @mike-000 
using getRenderPixel works!

Best regards.
