### ISSUE TITLE
ACCUSATION MESSAGES DISPLAYED ON THE MAP ON LAT LON 51.94599:7.7041138

### ISSUE THREAD

**Issue by clegeard** [openlayers/openlayers#15838]
**Describe the bug**
When zooming on latitude 51.94599 and longitude 7.7041138, some lines are drawn on the map naming a person and telling he's [edited]

**To Reproduce**
1. Zoom on the position mentioned above

**Expected behavior**
This should not appear on the map

**Comment by ahocevar** [comment]
@clegeard OpenLayers is a software to *display* maps, but does not provide the displayed content. Is that happening with one of the maps we use in the official examples, https://openlayers.org/en/latest/examples/? If so, can you share the link please?

**Comment by fredj** [comment]
It was vandalism and it has been reverted with https://www.openstreetmap.org/changeset/151429883

**Comment by clegeard** [comment]
> @clegeard OpenLayers is a software to _display_ maps, but does not provide the displayed content. Is that happening with one of the maps we use in the official examples, https://openlayers.org/en/latest/examples/? If so, can you share the link please?

Yes it is visible also on the map you are sharing 
https://openlayers.org/en/latest/examples/accessible.html
![image](https://github.com/openlayers/openlayers/assets/30863390/14e5d0ea-cf66-4bce-b83a-bd04e2d410e0)

It's in Germany, near the city Munster. I attached a screenshot of our map with the location pinned.
You have to zoom in to see the messages
![image](https://github.com/openlayers/openlayers/assets/30863390/dc4988f9-d116-4d06-a36f-0139711e211a)
![image](https://github.com/openlayers/openlayers/assets/30863390/92cd1128-11c3-426c-a3d8-3c4254e26291)

**Comment by clegeard** [comment]
> It was vandalism and it has been reverted with https://www.openstreetmap.org/changeset/151429883

it's also visible on the map you linked
![image](https://github.com/openlayers/openlayers/assets/30863390/22a702a6-b1a8-4258-9c0e-cb827e77377f)

**Comment by tschaub** [comment]
As @fredj pointed out, this is an issue with vandalism in OpenStreetMap.  If the same thing were to show up in Bing Map Tiles (for example), OpenLayers would also not be able to make any changes to correct this.  After OpenStreetMap cleans things up, anyone using OpenStreetMap via OpenLayers or any other map library will see the cleaned up results.  Until then, we can't do anything about it here.

**Comment by ahocevar** [comment]
As @fredj pointed up above, this has been reverted already with https://www.openstreetmap.org/changeset/151429883. It takes a while for the change to propagate to all map renderings that might be used on openlayers.org.

**Comment by clegeard** [comment]
> As @fredj pointed up above, this has been reverted already with https://www.openstreetmap.org/changeset/151429883. It takes a while for the change to propagate to all map renderings that might be used on openlayers.org.

Are you sure, because if I go to the link you are referring me to, I can see the spam messages there.
Or is it normal that they are still visible there?

**Comment by ahocevar** [comment]
OpenStreetMap is versioned, so you can create a permalink to any older revison.
