### ISSUE TITLE
VectorLayerOptions does not use the same generic type as VectorLayer

### ISSUE THREAD

**Issue by KyllianGautier** [openlayers/openlayers#15837]
**Describe the bug**
VectorLayerOptions does not have the same generic type as VectorLayer
![image](https://github.com/openlayers/openlayers/assets/12836335/b5173a61-e1fb-4614-ba76-5c05c376eed3)
![image](https://github.com/openlayers/openlayers/assets/12836335/f5cf77e0-4fde-4015-aa55-52e75a366b18)

**To Reproduce**
Use a VectorLayer by instantiate it with a VectorLayerOptions:
`(options?: OLVectorLayerOptions<OLFeatureLike>) => new OLVectorLayer<OLFeatureLike>(options)`
See that the required types are not the same since the v9.2.1.
Before the v9.2.0, the types were both `VectorSource`.

**Expected behavior**
We can instantiate a VectorLayer with an Option object that uses the same required generic type as VectorLayer.
Such as ClusterLayer and ClusterLayerOptions for example

**Comment by ahocevar** [comment]
@KyllianGautier The type of the Options has to include the source, because the options are used for several BaseVector layer subclasses. For the VectorLayer, the source type is determined and does not require generics. Does this cause a real-life problem?

**Comment by KyllianGautier** [comment]
@ahocevar Ok, I understand. I tryed to adapt, but I still have some very strange problems with the typing :
Here I created a factory to instantiate a VectorLayer:
![image](https://github.com/openlayers/openlayers/assets/12836335/0a100f33-7de2-4de3-98b9-87e3f3172e66)

**Comment by ahocevar** [comment]
Maybe you got some of the imports wrong? This works fine for me:
```ts
import { FeatureLike as OLFeatureLike } from 'ol/Feature.js';
import { Options as OLBaseVectorLayerOptions } from 'ol/layer/BaseVector.js';
import OLVectorLayer from 'ol/layer/Vector.js';
import OLVectorSource from 'ol/source/Vector.js';

export const vectorLayer = <F extends OLFeatureLike>(options?: OLBaseVectorLayerOptions<OLVectorSource<F>>) => new OLVectorLayer<F>(options);
```

**Comment by KyllianGautier** [comment]
@ahocevar Unfortunately, I have errors in typescript trying your solution:
![image](https://github.com/openlayers/openlayers/assets/12836335/3b64de52-01ff-4afa-8a8b-5a18537bb2c1)

**Comment by ahocevar** [comment]
Thanks @KyllianGautier, you are right. In #15843 I made it so the options and the layer have the same generics again - both the `FeatureType`, no longer `SourceType<FeatureType>`.

**Comment by KyllianGautier** [comment]
@ahocevar thanks for this fix. I still have issue with typing in typescript :'(
I am able to give a `TileLayer<TileSource>` as a `Layer<Source, Renderer>`.
But I can't give a `VectorLayer<FeatureLike>` as a `Layer<Source, Renderer>`.

![image](https://github.com/openlayers/openlayers/assets/12836335/72e2e0d5-86e7-490e-ad5a-9c9addc1a302)

I'm sorry to disturbing you, but I don't find solution, and I don't know how to get the info to understand if I'm doing something wrong.

**Comment by ahocevar** [comment]
> But I can't give a VectorLayer<FeatureLike> as a Layer<Source, Renderer>.

Correct, that's no longer the type signature.

> You can test a simple example of the typing problem in Typescript:
   `export const vectorLayer: OLVectorLayer<OLFeatureLike> = new OLVectorLayer<OLFeature>();`

That's also expected. There is no inheritance relationship between the allowed types of `FeatureLike` - `Feature` and `RenderFeature` only have a small subset of a common API. So you have to decide when you declare the variable what you're going to store there. The following will work.

```ts
export const vectorLayer: OLVectorLayer<OLFeature> = new OLVectorLayer<OLFeature>();
```

**Comment by KyllianGautier** [comment]
Thanks for the details. I tried what you proposed, and I still have issues in Typescript:
![image](https://github.com/openlayers/openlayers/assets/12836335/310e01ad-a06e-4f14-8eb6-4deca15d197c)
![image](https://github.com/openlayers/openlayers/assets/12836335/5be135a0-e042-439a-b433-9f3af9660606)

**Comment by ahocevar** [comment]
@KyllianGautier  You're still using the old type signature for the options. This should now be:
```ts
import { Feature as OLFeature } from 'ol';
import OLVectorLayer, { Options as OLVectorLayerOptions } from 'ol/layer/Vector.js';
import OLVectorSource from 'ol/source/Vector.js';

const options: OLVectorLayerOptions<OLFeature> = {
  source: new OLVectorSource<OLFeature>()
}
```

**Comment by KyllianGautier** [comment]
@ahocevar Ok, problem solved, thanks for the support.

I have an additional question about the Layer.getSource() method. How can we type the source returned by a VectorLayer ?

If I use a Custer source for example, I instantiate a VectorLayer with this cluster source, and i'm not able to use the Cluster source specific methods such as setDistance() or setMinDistance():

![image](https://github.com/openlayers/openlayers/assets/12836335/38e6d515-463c-4d04-8ee4-00d828dbc7d2)

**Comment by ahocevar** [comment]
In #15869, the source type is added back as 2nd type parameter to vector and vectortile layers.
