### ISSUE TITLE
用于银河麒麟系统时，web多次缩放地图后，前端不再发出瓦片请求

### ISSUE THREAD

**Issue by ABYSS0918** [openlayers/openlayers#15836]
**Describe the bug**
在windows系统上一切正常，只是瓦片加载速度比较慢但没有bug，用于银河麒麟系统时，web多次缩放地图后，前端不再发出瓦片请求，导致地图瓦片不再刷新，并不是网页卡死，还能继续拖拽缩放，只是图片不再更新，也没有报错，等待一分钟甚至更久后，请求又开始发送，图片加载的速度很慢，30s-40s更新一张图，请问这个问题应该怎么解决？

**To Reproduce**
1. 进入网页
2. 多次缩放
3. 瓦片不更新，不发请求

**Comment by ahocevar** [comment]
Sounds like a bad Internet connection. When the tile queue is saturated with tiles waiting to finish loading, no more tiles will be requested until the queued tiles are loaded or or errored.

**Comment by ABYSS0918** [comment]
> Sounds like a bad Internet connection. When the tile queue is saturated with tiles waiting to finish loading, no more tiles will be requested until the queued tiles are loaded or or errored.

May I ask how to solve this problem?

**Comment by ABYSS0918** [comment]
> > Sounds like a bad Internet connection. When the tile queue is saturated with tiles waiting to finish loading, no more tiles will be requested until the queued tiles are loaded or or errored.
> 
> May I ask how to solve this problem?

To add, the service for obtaining tiles is local and deployed offline

**Comment by ABYSS0918** [comment]
> > > Sounds like a bad Internet connection. When the tile queue is saturated with tiles waiting to finish loading, no more tiles will be requested until the queued tiles are loaded or or errored.
> > 
> > 
> > May I ask how to solve this problem?
> 
> To add, the service for obtaining tiles is local and deployed offline

Where can I see the waiting logic when the queue is full in the source code

**Comment by boborua** [comment]
跟操作系统关系不太大，看浏览器

**Comment by ABYSS0918** [comment]
> 跟操作系统关系不太大，看浏览器

好的谢谢，后端优化了之后已经没有出现这个bug了
