### ISSUE TITLE
Modify interaction options and cluster source options optional

### ISSUE THREAD

**Issue by KyllianGautier** [openlayers/openlayers#15840]
Modify interaction options are required in the constructor, but all others interactions have optional options.
Same case for the cluster source.

**Describe the solution you'd like**
Make the Modify interaction options and the cluster source options optional.

**Comment by mike-000** [comment]
Modify requires either `source` or `features` and throws an error "The modify interaction requires features, a source or a layer" if not supplied (the reference to layer seems to be outdated).  Options should not be optional for Draw, a valid `type` is required.  The docs for ClusterSource are incorrect as it also throws a runtime error if source is missing.

**Comment by KyllianGautier** [comment]
@mike-000 Oh that's true, thanks, I fixed on my side.

**Comment by mike-000** [comment]
I think the ClusterSource runtime error is a bug and the docs are correct as the error also occurs if the documented `setSource(null)` is used.  That means no options are mandatory and the `options` parameter can be optional.  I have created #15842 to fix that.
