### ISSUE TITLE
Control ScaleLine - Error Cannot read properties of undefined (reading 'toFixed')

### ISSUE THREAD

**Issue by edsonmsj** [openlayers/openlayers#15852]
The error you're encountering, TypeError: Cannot read properties of undefined (reading 'toFixed'), indicates that the count variable is undefined when the code tries to call the toFixed method on it.

Error:
ScaleLine.js:352 Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed')
    at ScaleLine.updateElement_ (ScaleLine.js:352:15)
    at ScaleLine.render (ScaleLine.js:487:10)
    at Map.dispatchEvent (Target.js:119:11)
    at Map.renderFrame_ (Map.js:1633:10)
    at Map.animationDelay_ (Map.js:1449:10)

Code:
  const html = this.scaleBar_
      ? this.createScaleBar(width, count, suffix)
      : count.toFixed(decimalCount < 0 ? -decimalCount : 0) + ' ' + suffix;

    if (this.renderedHTML_ != html) {
      this.innerElement_.innerHTML = html;
      this.renderedHTML_ = html;
    }
    
 Code implements Map:
  const scaleControl = new ScaleLine({
        units: "metric",
        bar: false,
        text: true,
        minWidth: 150,
        maxWidth: 150,
      });
      
       const mapInstance = new Map({
        controls: [overviewMapControl, scaleControl],
        target: mapRef.current!,
        layers: [
          ...dataLayers,
        ],
        view: new View({
          projection: "EPSG:4326",
          center: [-38.2999, -12.6153],
          zoom: 16,
        }),
      });

It is necessary to check the variable to avoid the error.

**Comment by mike-000** [comment]
The error is reproduceable with rapid zooming in or out.
`count` could be undefined only if set in https://github.com/openlayers/openlayers/blob/main/src/ol/control/ScaleLine.js#L333-L337 at the first pass through the `while` loop.

**Comment by edsonmsj** [comment]
I managed to solve the problem by overriding the class method:

import ScaleLine from "ol/control/ScaleLine";
import { METERS_PER_UNIT, getPointResolution } from "ol/proj";
const DEFAULT_DPI = 25.4 / 0.28;
const LEADING_DIGITS = [1, 2, 5];
class CustomScaleLine extends ScaleLine {
  getScaleForResolution() {
    const resolution = getPointResolution(
      this.viewState_.projection,
      this.viewState_.resolution,
      this.viewState_.center,
      "m"
    );
    const dpi = this.dpi_ || DEFAULT_DPI;
    const inchesPerMeter = 1000 / 25.4;
    return resolution * inchesPerMeter * dpi;
  }
  updateElement_() {
    const viewState = this.viewState_;

    if (!viewState) {
      if (this.renderedVisible_) {
        this.element.style.display = "none";
        this.renderedVisible_ = false;
      }
      return;
    }

    const center = viewState.center;
    const projection = viewState.projection;
    const units = this.getUnits();
    const pointResolutionUnits = units == "degrees" ? "degrees" : "m";
    let pointResolution = getPointResolution(
      projection,
      viewState.resolution,
      center,
      pointResolutionUnits
    );

    const minWidth =
      (this.minWidth_ * (this.dpi_ || DEFAULT_DPI)) / DEFAULT_DPI;

    const maxWidth =
      this.maxWidth_ !== undefined
        ? (this.maxWidth_ * (this.dpi_ || DEFAULT_DPI)) / DEFAULT_DPI
        : undefined;

    let nominalCount = minWidth * pointResolution;
    let suffix = "";
    if (units == "degrees") {
      const metersPerDegree = METERS_PER_UNIT.degrees;
      nominalCount *= metersPerDegree;
      if (nominalCount < metersPerDegree / 60) {
        suffix = "\u2033"; // seconds
        pointResolution *= 3600;
      } else if (nominalCount < metersPerDegree) {
        suffix = "\u2032"; // minutes
        pointResolution *= 60;
      } else {
        suffix = "\u00b0"; // degrees
      }
    } else if (units == "imperial") {
      if (nominalCount < 0.9144) {
        suffix = "in";
        pointResolution /= 0.0254;
      } else if (nominalCount < 1609.344) {
        suffix = "ft";
        pointResolution /= 0.3048;
      } else {
        suffix = "mi";
        pointResolution /= 1609.344;
      }
    } else if (units == "nautical") {
      pointResolution /= 1852;
      suffix = "NM";
    } else if (units == "metric") {
      if (nominalCount < 1e-6) {
        suffix = "nm";
        pointResolution *= 1e9;
      } else if (nominalCount < 0.001) {
        suffix = "μm";
        pointResolution *= 1000000;
      } else if (nominalCount < 1) {
        suffix = "mm";
        pointResolution *= 1000;
      } else if (nominalCount < 1000) {
        suffix = "m";
      } else {
        suffix = "km";
        pointResolution /= 1000;
      }
    } else if (units == "us") {
      if (nominalCount < 0.9144) {
        suffix = "in";
        pointResolution *= 39.37;
      } else if (nominalCount < 1609.344) {
        suffix = "ft";
        pointResolution /= 0.30480061;
      } else {
        suffix = "mi";
        pointResolution /= 1609.3472;
      }
    } else {
      throw new Error("Invalid units");
    }

    let i = 3 * Math.floor(Math.log(minWidth * pointResolution) / Math.log(10));
    let count, width, decimalCount;
    let previousCount, previousWidth, previousDecimalCount;
    while (true) {
      decimalCount = Math.floor(i / 3);
      const decimal = Math.pow(10, decimalCount);
      count = LEADING_DIGITS[((i % 3) + 3) % 3] * decimal;
      width = Math.round(count / pointResolution);
      if (isNaN(width)) {
        this.element.style.display = "none";
        this.renderedVisible_ = false;
        return;
      }
      if (maxWidth !== undefined && width >= maxWidth) {
        count = previousCount;
        width = previousWidth;
        decimalCount = previousDecimalCount;
        break;
      } else if (width >= minWidth) {
        break;
      }
      previousCount = count;
      previousWidth = width;
      previousDecimalCount = decimalCount;
      ++i;
    }
    const displayCount =
      count !== undefined
        ? count.toFixed(decimalCount < 0 ? -decimalCount : 0)
        : "0";

    const html = this.scaleBar_
      ? this.createScaleBar(width, count, suffix)
      : displayCount + " " + suffix;

    if (this.renderedHTML_ != html) {
      this.innerElement_.innerHTML = html;
      this.renderedHTML_ = html;
    }

    if (this.renderedWidth_ != width) {
      this.innerElement_.style.width = width + "px";
      this.renderedWidth_ = width;
    }

    if (!this.renderedVisible_) {
      this.element.style.display = "";
      this.renderedVisible_ = true;
    }
  }
}

export default CustomScaleLine;

**Comment by ahocevar** [comment]
@edsonmsj Wouldn't that make sense to change directly in `ScaleLine.js`? So if you're able to create a pull request, it would be appreciated!

**Comment by edsonmsj** [comment]
I will be reading the contribution guidelines and after that I will be looking to make a pull request with the solution I reported here.
