### ISSUE TITLE
Can't run/compile angular/typescript application with OL > 9.0.0 

### ISSUE THREAD

**Issue by rockfarmor** [openlayers/openlayers#15858]
**Describe the bug**
I've just upgraded to OL 9.2.3 from OL 8.1.0 and now OL can't compile due to what I think is internal import errors.
Previously I've been using OL together with package @types/ol for typedefinitions, but now it seems like OL has it's own.

After installing OL >9 i get errors like this  when trying to run/compile my application:

Multiple export errors like this for GeoJSON:
> Error: node_modules/ol/format/GeoJSON.d.ts:2:36 - error TS2307: Cannot find module 'geojson' or its corresponding type declarations.
> 2 export type GeoJSONObject = import("geojson").GeoJSON;

Errors like this:

> Error: node_modules/ol/layer/Heatmap.d.ts:89:99 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<FeatureLike> | VectorTile<FeatureLike>'.
>   Type 'VectorSource<FeatureType>' is not assignable to type 'VectorSource<FeatureLike>'.
>     Types of property 'setLoader' are incompatible.
>       Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<FeatureLike>) => void'.
>         Types of parameters 'loader' and 'loader' are incompatible.
>           Types of parameters 'arg4' and 'arg4' are incompatible.
>             Type '((arg0: FeatureType[]) => void) | undefined' is not assignable to type '((arg0: FeatureLike[]) => void) | undefined'.
>               Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: FeatureLike[]) => void'.
>                 Types of parameters 'arg0' and 'arg0' are incompatible.
>                   Type 'FeatureLike[]' is not assignable to type 'FeatureType[]'.
>                     Type 'FeatureLike' is not assignable to type 'FeatureType'.
>                       'FeatureLike' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'FeatureLike'.
>                         Type 'RenderFeature' is not assignable to type 'FeatureType'.
>                           'RenderFeature' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'FeatureLike'.
> 
> 89 declare class Heatmap<FeatureType extends import("../Feature.js").FeatureLike> extends BaseVector<import("../source/Vector.js").default<FeatureType>, WebGLPointsLayerRenderer> {

> Error: node_modules/ol/layer/VectorImage.d.ts:165:35 - error TS2344: Type 'VectorSource<FeatureType>' does not satisfy the constraint 'VectorSource<Feature<Geometry>>'.
>   Types of property 'setLoader' are incompatible.
>     Type '(loader: FeatureLoader<FeatureType>) => void' is not assignable to type '(loader: FeatureLoader<Feature<Geometry>>) => void'.
>       Types of parameters 'loader' and 'loader' are incompatible.
>         Types of parameters 'arg4' and 'arg4' are incompatible.
>           Type '((arg0: FeatureType[]) => void) | undefined' is not assignable to type '((arg0: Feature<Geometry>[]) => void) | undefined'.
>             Type '(arg0: FeatureType[]) => void' is not assignable to type '(arg0: Feature<Geometry>[]) => void'.
>               Types of parameters 'arg0' and 'arg0' are incompatible.
>                 Type 'Feature<Geometry>[]' is not assignable to type 'FeatureType[]'.
>                   Type 'Feature<Geometry>' is not assignable to type 'FeatureType'.
>                     'Feature<Geometry>' is assignable to the constraint of type 'FeatureType', but 'FeatureType' could be instantiated with a different subtype of constraint 'Feature<Geometry>'.
> 
> 165     constructor(options?: Options<import("../source/Vector.js").default<FeatureType>> | undefined);

I'm maintaining a very large OpenLayers based application as well as a inner-source library based on OpenLayers, and I need som information that can point me in the right direction to fix this.

**To Reproduce**
Upgrade application from OL < 9 to OL > 9

**Expected behavior**
The application should compile/run

**Comment by ahocevar** [comment]
The first problem should go away when you install `@types/geojson`. For the rest, I‘d need a reproduction repository or a TS playground link to investigate.

**Comment by ahocevar** [comment]
I'm aware of these problems, and I'm working on a bigger overhaul of the layer and source generics to make them functional again.

**Comment by ahocevar** [comment]
@rockfarmor It would be good if you could test #15869. The procedure would be to clone `git@github.com:ahocevar/openlayers.git`, switch to the `consistent-vector-generics` branch, run `npm run build-package && cd build/ol && npm link`, go to your project, and run `npm link ol`.

**Comment by bkuster** [comment]
@ahocevar i tried your proposed fix. and most of the errors do go away, just the one remains in `VectorTileLayer.d.ts`:

![image](https://github.com/openlayers/openlayers/assets/11855207/50c6d875-9ad9-4e52-8ed8-08c29f060ce1)

using node 20 & ts 5.4

**Comment by ahocevar** [comment]
Thanks for the feedback, @rockfarmor. I fixed that one, and added a test in #15869 to make sure we pass `tsconfig`s with `skipLibCheck: false` in the future.
