### ISSUE TITLE
when dragging map, it stuck

### ISSUE THREAD

**Issue by zj91zj** [openlayers/openlayers#15865]
I want to display more than 2000 point and line features, displaying different shapes and text according to locationName and resolution, but when dragging the map, it will be a bit stuck.

https://codesandbox.io/p/devbox/gss2l9?file=%2Fmain.js%3A151%2C20

**Comment by ahocevar** [comment]
You will have to make the sandbox public so others can open it. 2000 features is not much, so I guess there is a problem with the way you specify the styles.

**Comment by zj91zj** [comment]
> You will have to make the sandbox public so others can open it. 2000 features is not much, so I guess there is a problem with the way you specify the styles.

thanks for attention, please visit https://codesandbox.io/p/devbox/gss2l9?file=%2Fmain.js%3A6%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwkdf5bc0006356iffqtlaax%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwkdf5bc0002356i0hv1nrte%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwkdf5bc0004356iwdezbwjh%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwkdf5bc0005356ito70337v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B51.04220549073702%252C48.95779450926298%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwkdf5bc0002356i0hv1nrte%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkdf5bc0001356ig7bkjm0y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwkdjls30002356j6xv2adgf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A6%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A6%252C%2522endColumn%2522%253A9%257D%255D%252C%2522filepath%2522%253A%2522%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwkdf5bc0002356i0hv1nrte%2522%252C%2522activeTabId%2522%253A%2522clwkdjls30002356j6xv2adgf%2522%257D%252C%2522clwkdf5bc0005356ito70337v%2522%253A%257B%2522id%2522%253A%2522clwkdf5bc0005356ito70337v%2522%252C%2522activeTabId%2522%253A%2522clwkdgxck00a6356iap0boz8d%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clwkdgxck00a6356iap0boz8d%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clwkdf5bc0004356iwdezbwjh%2522%253A%257B%2522id%2522%253A%2522clwkdf5bc0004356iwdezbwjh%2522%252C%2522activeTabId%2522%253A%2522clwkdfirp006l356i6brqsmdn%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwkdf5bc0003356i54oth126%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clwkdf6eu000ad9f8cn7deul7%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Development%2522%252C%2522id%2522%253A%2522clwkdfirp006l356i6brqsmdn%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by ahocevar** [comment]
It's like I thought. The problem is that you're creating new Style objects with every style function call. It is better to reuse style objects, i.e. cache them and return a reference to the cached styles in the style function.

**Comment by zj91zj** [comment]
I know， thanks
