### ISSUE TITLE
Previously working WebGLPointsLayer styles crash in 9.2.3

### ISSUE THREAD

**Issue by Innok-Louis** [openlayers/openlayers#15868]
**Describe the bug**  
We are using WebGLPointsLayer with 'flat styles' (dont quite work the same way for webGLPointslayer as far as i can tell).  
One of our layer styles sets the scale of the shape rendered by looking up if one of a number of attributes is set on a feature.

```
'shape-scale': [
	'case',
	['==', ['get', 'A'], 'true'], 1,
	['==', ['get', 'B'], 'true'], 2,
	3
],
                
```

This works fine up to ol 9.2.2

Once you use 9.2.3, it crashes giving this error:

```
Error: Could not find a common output type for the following case operation: ["case",["==",["get","A"],"true"],1,["==",["get","B"],"true"],2,3]
```

I have looked at the changes in 9.2.3 but i don't have enough insight into ol's inner working to understand why they would have any influence on this.

**To Reproduce**  

I made i minimal reproducable example: https://codepen.io/Innok-Louis/pen/qBGaOpN

1.  open example
2.  open dev tools to see error
3.  change version to 9.2.2 to see the error disappear

**Expected behavior**  
Some insight on why this happens.   
For now we moved our dependency from ^9.0.0 to 9.2.2 to prevent any more production systems grabbing the version that crashes.  
Happy to provide any more info to help find the root cause.

**Comment by Innok-Louis** [comment]
Our style uses 'case' looking up attributes for almost every part of the style, but only 'shape-scale' causes the error.

**Comment by M393** [comment]
It works when scale is an array with x and y scale.
```js
  'shape-scale': [
    'case',
    ['==', ['get', 'A'], 'true'], [1 ,1],
    ['==', ['get', 'B'], 'true'], [2, 2],
    [3, 3]
  ],
```

**Comment by Innok-Louis** [comment]
Thanks for the explanation @M393.

As we're not scaling two-dimensionally, I switched to shape-radius, as recommended by the docs.

From my end this issue is closed.

**Comment by tarangrathod** [comment]
Hi @ahocevar i still see a similar error 

Reproducible: [example](https://codesandbox.io/p/sandbox/icon-sprite-webgl-26zffc?file=%2Fmain.js%3A80%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwrqm7m600063p6g7b8t7vo3%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwrqm7m500023p6gw83fbfek%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwrqm7m500033p6gvsa85ocf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwrqm7m500053p6gp1q49f2n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwrqm7m500023p6gw83fbfek%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrqm7m500013p6gws0478z0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clwrqnqv400353p6gq5xej2hr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A80%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A80%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwrqm7m500023p6gw83fbfek%2522%252C%2522activeTabId%2522%253A%2522clwrqnqv400353p6gq5xej2hr%2522%257D%252C%2522clwrqm7m500053p6gp1q49f2n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrqm7m500043p6gwotaygpd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwrqm7m500053p6gp1q49f2n%2522%252C%2522activeTabId%2522%253A%2522clwrqm7m500043p6gwotaygpd%2522%257D%252C%2522clwrqm7m500033p6gvsa85ocf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwrqm7m500033p6gvsa85ocf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 
 It fails in 9.2.4 but works in 9.2.2 all fine, you can downgrade the version 9.2.2 and see it working .

Error: 
```
Error: Could not find a common output type for the following match operation: ["match",["get","shape"],"light",0.5,0.7]
    at Array.parseMatchArgs (expression.js:418:11)
    at eval (expression.js:547:36)
    at parseCallExpression (expression.js:568:10)
    at parse (expression.js:136:12)
    at buildExpression (gpu.js:200:27)
    at expressionToGlsl (styleparser.js:17:49)
    at parseCommonSymbolProperties (styleparser.js:68:19)
    at parseIconProperties (styleparser.js:263:3)
    at parseLiteralStyle (styleparser.js:436:5)
    at new WebGLPointsLayer (WebGLPoints.js:14:69)
    at XMLHttpRequest.eval (main.js:132:5)
```
Styles i am using
`
const style = {
  variables: {
    filterShape: 'all',
  },
  filter: [
    'any',
    ['==', ['var', 'filterShape'], 'all'],
    ['==', ['var', 'filterShape'], ['get', 'shape']],
  ],
  'icon-src': 'data/ufo_shapes.png',
  'icon-width': 128,
  'icon-height': 64,
  'icon-color': [
    'interpolate',
    ['linear'],
    ['get', 'year'],
    1950,
    oldColor,
    2013,
    newColor,
  ],
  'icon-offset': [
    'match',
    ['get', 'shape'],
    'light',
    [0, 0],
    'sphere',
    [32, 0],
    'circle',
    [32, 0],
    'disc',
    [64, 0],
    'oval',
    [64, 0],
    'triangle',
    [96, 0],
    'fireball',
    [0, 32],
    [96, 32],
  ],
  'icon-size': [32, 32],
  'icon-scale': ['match', ['get', 'shape'], 'light', 0.5, 0.7],
};` 
    For better understanding point of failure which is this ` 'icon-scale': ['match', ['get', 'shape'], 'light', 0.5, 0.7],`
