### ISSUE TITLE
Nonexistent Road is being displayed on the map with an inappropriate title

### ISSUE THREAD

**Issue by rachhill** [openlayers/openlayers#15879]
**Describe the bug**
I'm using the WP Go Maps plugin version 9.0.38 on my website and when I zoom in on my business location there is an extra road that goes nowhere that doesn't even exist and it's named inappropriately. 

See attached screenshot of circled road. 

The business in question is located at Lat/Lon 39.1455172,-88.5232553 (I wasn't able to utilize the street address as it couldn't locate it even though this address has been official for many, many years now just under a different business name).

<img width="1265" alt="Screenshot 2024-05-28 at 8 04 33 AM" src="https://github.com/openlayers/openlayers/assets/60271138/a5e4538f-a3c0-4520-8a07-ae0a4285c834">

**Comment by tschaub** [comment]
Here is another page with some information on what you can do: https://www.openstreetmap.org/fixthemap

**Comment by rachhill** [comment]
Thank you for the extra information. I’ve submitted a notice to their Vandalism team about the issue.

Thanks,

Rachel Hill
Web Developer



900 N. Third St., Suite C
Effingham, IL 62401

***@***.***
P: 217.342.2661

thinkcreatedo.com
