### ISSUE TITLE
Feature collection disordered after having drawn a specifing number of features or vertices

### ISSUE THREAD

**Issue by bohmanng** [openlayers/openlayers#15896]
**Describe the bug**

https://github.com/openlayers/openlayers/assets/80331711/749b4644-c12e-4342-b294-f7df434b7af4

When drawing a new feature to a vector source, it seems one can draw nine features and remove them one after one in timely reverse order without any problems using the source.removeFeature(features[_features.length-1]_) technique.
But, if one draws more than a specific number of features (or vertices in a line string or polygon, respectively), the timely order of features (or vertices) gets mixed up. Sometimes, the end of disturbed order is set to somewhere in the mid of the original sequence and one can start deleting in reverse order from that point. But sometimes there are blocks of feature, or, there is even no predictabel order at all.

In my current case that specific number of vertices or features is 10.

But, this problem is not only a prominent one when removing features drawn. This problem is also relevant when trying to programmatically attach a new line string to the end of the very line string drawn before.
The latter case is also where that error appeared to me the first time. Namely on a web GIS system dating from 2016 which I took over from a former colleague. Until now, I thought it might be a specific error coded by that colleague in one of his subroutines.

But unfortunately, this mix-up in features' order might be somewhere in the very basic routines in OpenLayers.
Although, I still cannot understand why I should be the first one having such problems.

**To Reproduce**
Code snippet used for 'Delete Last Feature' button is as follows:

_var features = source.getFeatures();
if (features.length > 0) {
	var lastFeature = features[features.length - 1];
	source.removeFeature(lastFeature);
}_

**Expected behavior**
Is it possible to add some sort of time-flag (maybe per uuid based on current date and time info) to each vertex or feature, respectively, to insure the timely order of features or to make all the features in a collection (more) comparable to each other? That would also help as standardised attribute for the distinguishing the features by an 'object ID', commonly needed for GIS reasons.

**Comment by M393** [comment]
By default the `VectorSource` uses a spatial index for its features, which does not preserve the insertion order. 

You can try using the [`useSpatialIndex: false`](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html) option, if you don't have many features.
Alternatively use [`features`](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html) option with a [`Collection`](https://openlayers.org/en/latest/apidoc/module-ol_Collection-Collection.html) and use the Collection to access the last feature.

**Comment by bohmanng** [comment]
Many thanks for this quite valuable piece of information! Will check & try it out asap.

In my humble opinion, that info might be worth an own example since there are only some examples dealing with undoing the last vertex in a draw. Accordingly, one gets easily mislead that working with features is similar to vertices. As said before, it seems my former colleague did not know about that fact either ;)

**Comment by bohmanng** [comment]
[useSpatialIndex: false](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html) worked for me :)
Thanks for the quick help!
