### ISSUE TITLE
layerState is undefined in inView function

### ISSUE THREAD

**Issue by haluvibe** [openlayers/openlayers#15913]
**Describe the bug**

In this file: src/ol/layer/Layer.js

It can be that layerState is undefined in the inView function.

This causes an error at this line

export function inView(layerState, viewState) {
  if (!layerState.visible) { <---------- here is the line causing the error because layerState can be undefined which throws an error

**To Reproduce**
1. Go to https://maps.nhvr.gov.au/?networkLayerContext=NATIONAL_MAP&view=Category
2. Click on select a network and select some segments and open the console.
3. See error

**Expected behavior**

Will error out because layerState is potentially undefined. Extremely simple to fix, just change it to:   

src/ol/layer/Layer.js
export function inView(layerState, viewState) {
if (!layerState || !layerState.visible) {

This works without causing any unwanted side effects.

**Comment by ahocevar** [comment]
Can you please provide a minimal standalone example that shows *how* we can run into calling `inView()` with an undefined `layerState`?

**Comment by ahocevar** [comment]
Still waiting for a reproducible example, then I'll look into it.

**Comment by jay08111** [comment]
you can jump over this error by using 
```
  setTimeout(() => {
               yourlayerstate.addLayer(vectorLayer);
        }, 0);
```
it seems very awkward, your co workers will ask you what does this set timeout do, though

**Comment by ahocevar** [comment]
Who can provide a reproducible example, so we can check why this problem occurs and eventually fix it?

**Comment by jay08111** [comment]
I tried to make an example of it, #16259 Please let me know if I did something wrong, @ahocevar
