### ISSUE TITLE
Removing all features in a render.FeaturesOverlay

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers#1593]
I'm thinking it would be useful to add a (exported) function to remove all features from an overlay. At the moment, I have to set up a getFeatures()/removeFeature() loop which ISTM would be better encapsulated in the library. It looks like setFeatures(new ol.Collection()) also works, but this is not intuitive; the more intuitive setFeatures(), setFeatures([]) or setFeatures(null) don't work. Perhaps enabling setFeatures() (i.e. 'features' is undefined) would be better than having an extra function.

**Comment by TimMcCauley** [comment]
Works!
