### ISSUE TITLE
KML with Nested MultiGeometry is not Rendered

### ISSUE THREAD

**Issue by ismailsunni** [openlayers/openlayers#15931]
**Describe the bug**
KML with nested `MultiGeometry` is not rendered when loaded into Open Layers. Based on the KML Reference, it should be possible to have a nested MultiGeometry tag (see [here](https://developers.google.com/kml/documentation/kmlreference#contained-by_15))

I have the sample code below that show the bug.

- [KML with nested MultiGeometry](https://codesandbox.io/p/sandbox/kml-nested-multigeometry-x82fwx)
- [KML without nested MultiGeometry](https://codesandbox.io/p/sandbox/kml-without-nested-multigeometry-97cml8)

Preview:
- With nested MultiGeometry
   ![image](https://github.com/openlayers/openlayers/assets/1421861/8d59a0b6-6ae4-4755-b146-6cfc3c1351df)
- Without nested MultiGeometry
   ![image](https://github.com/openlayers/openlayers/assets/1421861/2bb8c276-aa39-41df-92fc-790109e98651)
- Loaded in Google Earth
   ![image](https://github.com/openlayers/openlayers/assets/1421861/b746703d-1651-4489-b2fd-cf53c079c731)

The sample files can be found [here](https://gist.github.com/ismailsunni/327b42e2a0682b0317dd908778a4fdfb). Both sample files can be loaded in Google Earth

The difference is below (see the nested **`MultiGeometry`** tag)
```
 <MultiGeometry>
                    <MultiGeometry>
                        <Polygon>
                            <extrude>1</extrude>
                            <tessellate>1</tessellate>
                            <altitudeMode>absolute</altitudeMode>
                            <outerBoundaryIs>
                                <LinearRing>
                                    <coordinates>9.51417142486868,47.4851074227347,498.0 9.528776569238,47.4855038943916,443.0 9.51422435474779,47.4864630990936,498.0 9.51417142486868,47.4851074227347,498.0</coordinates>
                                </LinearRing>
                            </outerBoundaryIs>
                        </Polygon>
                        <Polygon>
                            <extrude>1</extrude>
                            <tessellate>1</tessellate>
                            <altitudeMode>absolute</altitudeMode>
                            <outerBoundaryIs>
                                <LinearRing>
                                    <coordinates>9.51420229254557,47.4837514318466,498.0 9.52878826264392,47.4840913867986,443.0 9.51417142486868,47.4851074227347,498.0 9.51420229254557,47.4837514318466,498.0</coordinates>
                                </LinearRing>
                            </outerBoundaryIs>
                        </Polygon>
                    </MultiGeometry>
                </MultiGeometry>
```

**To Reproduce**
1. Open the codesandbox links above to see the difference between KML that has nested `MultiGeometry` tag and the one not.
2. See the KML is not rendered if the KML has nested  `MultiGeometry`

**Expected behavior**
Open Layers should be able to load and render KML with nested `MultiGeometry`.

**Comment by mike-000** [comment]
t seems to depend on what other geometries are present

not working (no feature added)

                <MultiGeometry>
                    <MultiGeometry>
                        <Polygon>
                        </Polygon>
                        <Polygon>
                        </Polygon>
                    </MultiGeometry>
                </MultiGeometry>

not working (no feature added)

                <MultiGeometry>
                    <MultiGeometry>
                        <Polygon>
                        </Polygon>
                    </MultiGeometry>
                    <MultiGeometry>
                        <Polygon>
                        </Polygon>
                    </MultiGeometry>
                </MultiGeometry>

working as expected (feature added)

                <MultiGeometry>
                    <Polygon>
                    </Polygon>
                    <MultiGeometry>
                        <Polygon>
                        </Polygon>
                        <Polygon>
                        </Polygon>
                    </MultiGeometry>
                </MultiGeometry>

working as expected (feature added)

                <MultiGeometry>
                    <Polygon>
                    </Polygon>
                    <MultiGeometry>
                        <Polygon>
                        </Polygon>
                        <Polygon>
                        </Polygon>
                    </MultiGeometry>
                    <MultiGeometry>
                        <Polygon>
                        </Polygon>
                        <Polygon>
                        </Polygon>
                    </MultiGeometry>
                </MultiGeometry>

also as expected (feature with nested empty GeometryCollection added)

                <MultiGeometry>
                    <MultiGeometry>
                    </MultiGeometry>
                </MultiGeometry>

**Comment by ismailsunni** [comment]
Thanks @mike-000 interesting finding. I haven't checked those more detailed cases. Also thanks for the fix. How can I try your fix?

Btw, if you need a real test file, you can also find it here https://developers.google.com/kml/documentation/us_states.kml

My samples are obviously stripped down for easier debugging.

Thanks!

**Comment by mike-000** [comment]
@ismailsunni I found the cause and #15932 fixes it.  While

                <MultiGeometry>
                    <Polygon>
                    </Polygon>
                </MultiGeometry>

can be represented as a MultiPolygon in OpenLayers there is no such thing as a MultiMultiPolygon and

            <MultiGeometry>
                <MultiGeometry>
                    <Polygon>
                    </Polygon>
                </MultiGeometry>
            </MultiGeometry>

must be represented as a MultiPolygon nested in a GeometryCollection
