### ISSUE TITLE
webgl - stroke-pattern-start-offset

### ISSUE THREAD

**Issue by nssang00** [openlayers/openlayers#15944]
**Is your feature request related to a problem? Please describe.**

In addition to the spacing, a starting point is needed to start drawing.
Can you add additional features?

**Describe the solution you'd like**
```javascript
    let startOffsetExpression = '0.';
    if ('stroke-pattern-start-offset' in style) {
      startOffsetExpression = expressionToGlsl(
        fragContext,
        style['stroke-pattern-start-offset'],
        NumberType,
      );
    }
    fragContext.functions['sampleStrokePattern'] =
    `vec4 sampleStrokePattern(sampler2D texture, vec2 textureSize, vec2 textureOffset, vec2 sampleSize, float spacingPx, float startOffsetPx, float currentLengthPx, float currentRadiusRatio, float lineWidth) {
  float currentLengthScaled = currentLengthPx * sampleSize.y / lineWidth;
  float spacingScaled = spacingPx * sampleSize.y / lineWidth;
  float uCoordPx = mod(currentLengthScaled + startOffsetPx, (sampleSize.x + spacingScaled));
  uCoordPx = clamp(uCoordPx, 0.5, sampleSize.x - 0.5);
  float vCoordPx = (-currentRadiusRatio * 0.5 + 0.5) * sampleSize.y;
  vec2 texCoord = (vec2(uCoordPx, vCoordPx) + textureOffset) / textureSize;
  return samplePremultiplied(texture, texCoord);
}`;
    const textureName = `u_texture${textureId}`;
    let tintExpression = '1.';
    if ('stroke-color' in style) {
      tintExpression = builder.getStrokeColorExpression();
    }
    builder.setStrokeColorExpression(
      `${tintExpression} * sampleStrokePattern(${textureName}, ${sizeExpression}, ${offsetExpression}, ${sampleSizeExpression}, ${spacingExpression}, ${startOffsetExpression}, currentLengthPx, currentRadiusRatio, v_width)`,
    );
  }
```

**Comment by jahow** [comment]
Yes this is indeed a feature that we didn't have time to implement last year, unfortunately. The implementation should be very similar to the dash offset though, so I'll dare to mark this as "good first PR". If anyone feels like tackling this, please feel free to ask for pointers here.

**Comment by nssang00** [comment]
expected result: ㆍ|ㆍ&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;ㆍ|ㆍ&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;ㆍ|ㆍ
actual result:      ㆍ|ㆍ&nbsp;&nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;&nbsp;ㆍㆍ| &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;| &nbsp;&nbsp;&nbsp;&nbsp;ㆍㆍ|

image size -> {width:5, height:13};
```javascript
const line_vertical = {
  'stroke-pattern-src': 'vertical.png',
  'stroke-width': 5,
  'stroke-offset': 0,
  'stroke-pattern-start-offset':20, 
  'stroke-pattern-spacing': 40,
};

const line_vertical_circle1 = {
  'stroke-pattern-src': 'circle.png',
  'stroke-width': 5,
  'stroke-offset': 0,
  'stroke-pattern-start-offset':17, 
  'stroke-pattern-spacing': 80,
};

const line_vertical_circle2 = {
  'stroke-pattern-src': 'circle.png',
  'stroke-width': 5,
  'stroke-offset': 0,
  'stroke-pattern-start-offset':23, 
  'stroke-pattern-spacing': 80,
};

let styles = [line_vertical, line_vertical_circle1, line_vertical_circle2];
```

Expected results and actual results are different.
And, even if 'stroke-pattern-spacing' is the same, an error still occurs if the image width and height of stroke-pattern-src are not the same.

The height of the image is fixed to 13 and the width is 5.
When I changed line_vertical['stroke-pattern-spacing'] = 37.5, I got the desired result.
The height of the image is fixed to 13 and the width is 10.
When I changed line_vertical['stroke-pattern-spacing'] = 35, I got the desired result.
The height of the image is fixed to 13 and the width is 20.
When I changed line_vertical['stroke-pattern-spacing'] = 30, I got the desired result.

**Comment by jahow** [comment]
Could you please post a picture of the result to have a better understanding of your issue? Also if that's not related to the stroke-pattern-offset feature, I'd kindly ask you to open a new issue so that people don't get confused. Thanks!
