### ISSUE TITLE
Polyfill vulnerability issues

### ISSUE THREAD

**Issue by arazi-NI** [openlayers/openlayers#15950]
Hi, I'm using an old version of OpenLayers (5.3.0) and I saw you're using Polyfill. As you can see, Polyfill has been compromised: https://news.ycombinator.com/item?id=40791829

I have two questions:
1. Is OpenLayers 5.3.0 compromised?
2. Do latest versions of OpenLayers not use Polyfill anymore? Is it a good alternative to just update my dependency?

Thank you!

**Comment by ahocevar** [comment]
OpenLayers won't use these polyfills unless you load them yourself. So no version of OpenLayers is compromised, but apps built on top of any version of OpenLayers, if it loads any of these polyfills, is. All you need to do is check your application code and remove the script tags that load these polyfills, if any.

**Comment by arazi-NI** [comment]
Oh, got it. That's great, then we don't need to do anything, thank you a lot for the quick reply.

I assume by the script tags that load the polyfills you mean the one below, right?
```xml
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList"></script>
```

**Comment by arazi-NI** [comment]
Oh, I got it. That's great, then! Thanks a lot for the quick reply and for saving me the trouble of upgrading it. :)

**Comment by ahocevar** [comment]
>     <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList"></script>

Yes, exactly. All script tags like this should be removed.

**Comment by arazi-NI** [comment]
Got it. Thanks again! Have a great day :)
