### ISSUE TITLE
Zooming without loading tiles

### ISSUE THREAD

**Issue by kanik588** [openlayers/openlayers#15960]
Can we map show bigger on specific zoom without loading tile.
it seem if I set maxZoom of vectorTileSource it works but how we can set maxzoom dynamically?

**Comment by andrew-cmdltt** [comment]
Is this method (setMaxZoom on the picture from the ol doc) impossible to complete during the app render? Can you give more details about the problem, please? 
![68911661-d119-4997-aed1-6b5b000a2f37](https://github.com/openlayers/openlayers/assets/66057583/f8552117-bd6b-478f-9fb4-770c92d58e0b)

**Comment by kanik588** [comment]
setMaxZoom in layers, hides or not render layer for larger zooms but setting maxzoom in source works fine for overzoom situation.

**Comment by andrew-cmdltt** [comment]
Yes, the property maxZoom needs to limit the layer zoom. And if we pass this value during change resolution, for example, by mouse wheel, our layer will become unvisible. I just realized. What if you set the property zoom or maxZoom in configs of your map server, which gives you data for render? For example, the geoserver has sld styles, where you can control scale of layer visialization. I don't use the vector tiles on my projects, but for image tiles it's our case:) 
https://gis.stackexchange.com/questions/58968/display-points-labels-starting-at-certain-zoom-level

**Comment by kanik588** [comment]
setting maxzoom for layer is not my problem.
I want to set maxzoom for source to use tiles from zoom 10 in map zoom 14.
the best suggestion for openlayers is adding a scale option to ol.View in this case we cam make map show bigger with hi quality rendering vectors.

**Comment by ahocevar** [comment]
@kanik588 For this specific case, configure the source with `maxZoom: 10`, then when the view is zoomed to zoom 14, tiles from zoom 10 will be used.

**Comment by kanik588** [comment]
@ahocevar I need to change maxzoom during app running not initializing.

**Comment by ahocevar** [comment]
@kanik588 In this case you could temporarily replace the source with a differently configured one. Then after printing, switch back to the original one. Both with `setSource()`.

**Comment by andrew-cmdltt** [comment]
@kanik588 Do you try to print by using the standard printing option of the browser (ctrl + P)? And what if you set require zoom manual and print the map on this resolution? Hm, but it's bad idea to make users to change zoom manual. So, yes, I agree with @ahocevar in this case we can use special events to modify source before and after printing.

**Comment by andrew-cmdltt** [comment]
It seems to me that we need to wait for the end of layer rendering to get better quality of image. Even I chenge resolution by programming way at once I get not finaly prepared to print image. How is your layer heavy to render and how long your render performs? I have an idea. Try to export image in, for example pdf, and then print it. By this official solution:
https://openlayers.org/en/latest/examples/export-pdf.html

**Comment by kanik588** [comment]
I tested changing the source at runtime, and it worked, good idea! 
However, I believe OpenLayers would benefit from having a scale option for layers or views as well.

**Comment by ahocevar** [comment]
@kanik588 It does already - you can configure the map with a `pixelRatio`. It defaults to `window.devicePixelRatio`, but you can set an arbitrary value there.

**Comment by kanik588** [comment]
@ahocevar pixleRatio is key of my problem, unfortunately it isnt changeable at runtime but I created a new map for printing with 2X & 4X pixleRatio also changed html2canvas scale option and now everything is fine.
thanks for your helps.
