### ISSUE TITLE
Slow map loading speed with 4k resolution and raster images

### ISSUE THREAD

**Issue by ABYSS0918** [openlayers/openlayers#15974]
**Describe the bug**
The loading speed of using raster images (256 * 256) on a 4k screen is slow, but it is fast at a resolution of 1920 * 1080. It seems that the lag is caused by increasing the number of requests. Can this only be optimized by using vector images?

**To Reproduce**
1. High resolution loading of WMS
2. Move or zoom the map
3. The loading speed of the map is very slow

**Comment by ahocevar** [comment]
This can be fixed by either choosing 512x512 pixel tiles, if available, or configuring the map with `maxTilesLoading` set to a larger value than the default of `16`.

**Comment by ABYSS0918** [comment]
> This can be fixed by either choosing 512x512 pixel tiles, if available, or configuring the map with `maxTilesLoading` set to a larger value than the default of `16`.

Thank you very much for your reply. I will try using tiles with a size of 512 * 512, but I have a question. Is this optimization limited for the front-end, and more performance optimization needs to be placed on the back-end?

**Comment by ahocevar** [comment]
You can try, and if it still feels slow, inspect the transfer times. If they are slow, optimization on the server might be in order.

**Comment by ABYSS0918** [comment]
> You can try, and if it still feels slow, inspect the transfer times. If they are slow, optimization on the server might be in order.
Thank you, changing the tiles to 512 can already meet the efficiency requirements!
