### ISSUE TITLE
WebGLTileLayer setStyle uses band 1 instead of alpha band, different behavior than TileLayer({style: ...})

### ISSUE THREAD

**Issue by maxschmi** [openlayers/openlayers#16000]
**Describe the bug**
When setting a WebGLTileLayer's Styling with setStyle, I get a different result than setting the same Style at construction of the TileLayer.
When using `setStyle` the alpha band is not considered, even though the styling uses `["!=", ["band", 2], 0],` and instead the first band is queried for this expression line. So erveywhere where the first band is 0 the styling for NoData is used. This is a bug.

When using the same style definition while creating the TileLayer, the result is as expected.

**To Reproduce**
I created a minimal reproducible example on [Sandbox](https://codesandbox.io/p/github/maxschmi/ol_tile_style_error/main?file=%2Fmain.js%3A46%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clypu5mm200062a69zkbyo8k0%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clypu5mm200022a69g7eeajkb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clypu5mm200042a69b682y5uj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clypu5mm200052a69fuo7e5bt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clypu5mm200022a69g7eeajkb%2522%253A%257B%2522id%2522%253A%2522clypu5mm200022a69g7eeajkb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clypuqkiq00022a69439mulww%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A46%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A46%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clypuqkiq00022a69439mulww%2522%257D%252C%2522clypu5mm200052a69fuo7e5bt%2522%253A%257B%2522id%2522%253A%2522clypu5mm200052a69fuo7e5bt%2522%252C%2522activeTabId%2522%253A%2522clypuawd900jv2a69ce7guudm%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clypuawd900jv2a69ce7guudm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clypu5mm200042a69b682y5uj%2522%253A%257B%2522id%2522%253A%2522clypu5mm200042a69b682y5uj%2522%252C%2522activeTabId%2522%253A%2522clypu5o47005n2a694t5ze2oo%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clypu5mm200032a69945wj5w8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clypu5nmb000pdji6bwxla115%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clypu5o47005n2a694t5ze2oo%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Open this and go to line 46 in main.js. If you comment out this line, there won't be a hole inside the layer. If the line is active, there will be a hole where the first band is 0, even though only the 

Here is the style set to my TileLayer: 
```
const style = {
  color: [
    "case",
    ["!=", ["band", 2], 0],
    ["color", 147, 68, 144, 1],
    ["color", 0, 0, 0, 0],
  ],
};
```
The TileLayer has only 1 band and no nodata, but -9999 set as nodata value. So the alpha band is allways be 255.

On Top of the map is the actual pixel value at the pointer, showing that the alpha band is 255 in the hole as it should be.

**Expected behavior**
The map styling with `setStyle` should be the same as using `TileLayer({style:...})`.
Using `tileLayer.setStyle` with a styling line `["!=", ["band", 2], 0],` should query against band 2 and not against band 1.

**Comment by mike-000** [comment]
It seems to be related to calling `setStyle()` before the source is ready.  If called after `await tifLayer.getSource().getView()` it works as expected.

**Comment by mike-000** [comment]
#16006 should protect against this happening, although I suspect there could be other situations such as calling `setSource()` to update to newly created source which is not ready where a similar issue might occur, but I have not been able to reproduce any.

**Comment by mike-000** [comment]
```
const tifLayer = new TileLayer({
  style: style,
});

tifLayer.setSource(source);
```

does have the same issue, but #16006 also fixes that.
