### ISSUE TITLE
y coordinate becomes NaN

### ISSUE THREAD

**Issue by tony-0tis** [openlayers/openlayers#16017]
**Describe the bug**
The y coordinate in location.href becomes NaN when using `useGeographic()`, `map.addInteraction(new Link())` and
```
const geolocation = new Geolocation({
	trackingOptions: {
		enableHighAccuracy: true,
	},
	tracking: true,
	projection: view.getProjection(),
});
geolocation.once('change:position', ()=>{
	view.setCenter(geolocation.getPosition());
	view.setResolution(2.388657133911758);
});
```
Or when start tracking by button click
```
let startTracking = false;
document.querySelector('.location').addEventListener('click', ()=>{
        startTracking = !startTracking;
	geolocation.setTracking(startTracking);
})
```

**Comment by mike-000** [comment]
You should not use `projection: view.getProjection(),` if you are using geographic coordinates as geographic coordinates will be returned if the option is omitted.  In a more general situation where you might have user coordinates you could handle any scenario with `projection: getUserProjection() || map.getView().getProjection(),`

**Comment by tony-0tis** [comment]
Thanks for the clarification. 
In the “Geographic Coordinates” example, this point is not clarified
