### ISSUE TITLE
TileLayer set className with filter css attribute can not effect

### ISSUE THREAD

**Issue by menghany** [openlayers/openlayers#16018]
**Describe the bug**
I added a className attribute to tileLayer, but it has a filter: initial !important; style by default, which prevents my CSS from taking effect.
this example also broken https://openlayers.org/en/latest/examples/semi-transparent-layer.html
```js
import TileLayer from 'ol/layer/Tile'
import { XYZ } from 'ol/source'
new TileLayer({
source: new XYZ(
    {
      url: import.meta.env.VITE_GOOGLE_TILE_URL,
      crossOrigin: 'anonymous'
    }
 ),
className: 'ol-tile-filter-css'
})
```
![image](https://github.com/user-attachments/assets/ba0fa1d0-a6ae-42c5-b72a-d53fd5296083)
![image](https://github.com/user-attachments/assets/2f0a128b-c8ec-4263-86fe-0087977ac333)

**Comment by ahocevar** [comment]
The `filter: initial !important;` style is not set by OpenLayers. You need to find out who sets that.

**Comment by ahocevar** [comment]
> this example also broken https://openlayers.org/en/latest/examples/semi-transparent-layer.html

That example works fine for me as well. Maybe a browser extension or ad blocker is causing the behaviour you're experiencing?

**Comment by menghany** [comment]
> Member

I apologize deeply. I just checked, and it turns out the issue was caused by a plugin in my browser.
I'm sorry, I took up your valuable time.
