### ISSUE TITLE
Dragging the map is laggy on mobile phone in portrait mode

### ISSUE THREAD

**Issue by Akbalder** [openlayers/openlayers#16023]
**Describe the bug**
Dragging the map is laggy on a mobile phone when in portrait mode. There is no issue when the mobile phone is in landscape mode. On heavy maps, it can become unusable. I tested on a Pixel 7a on Chrome but other users confirmed that they have the issue on other devices.

**To Reproduce**
1. On your mobile phone, go to https://8rgx7k.csb.app/ (It's just the "Vector Layer" example with the map displayed on the full page)
2. Put your mobile phone in landscape mode and drag the map. The movement is completely smooth.
3. Put your mobile phone in portrait mode and drag the map. The movement is laggy.

**Expected behavior**
The movement should be as smooth in portrait mode as in landscape mode.

**Comment by Makio64** [comment]
I would recommend you to test / use the webgl version for this use case.
 
From what i saw in the source code, the Webgl renderer make the heavy computational work in webworker ( compute the polygon with an offscreenCanvas ) and render it using Webgl polygon which is much faster than drawing it on canvas.

**Comment by ahocevar** [comment]
The problem here is the missing meta tags for proper scaling on mobile. Add the following to the `head` section of the HTML document:
```html
<meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
```
Try it here: https://mvw2ls.csb.app/

**Comment by Akbalder** [comment]
Thank you for your help. On a more complex page, just adding the viewport doesn't solve the issue. Are there other things to be careful about?

**Comment by ahocevar** [comment]
Do you have an example for such a "more complex page"?

**Comment by Akbalder** [comment]
I forgot that I tried a setting "Display Desktop Site" in my web browser on my mobile phone. With this setting disabled, your solution works for my page too.
Thank you for your help. This is not a bug so I'll close it.
