### ISSUE TITLE
Ol & Assetmapper in symfony: t.view.then is not a function

### ISSUE THREAD

**Issue by matfire** [openlayers/openlayers#16024]
**Describe the bug**
When using Assetmapper to manage js files, setting a view in a new map (in a Stimulus controller), either in the constructor or through the `.setView` method, throws the error:
```js
t.view.then is not a function
```

**To Reproduce**
- Create a symfony project with Assetmapper and Stimulus
- Create a new controller in assets/controllers (i.e ol_controller.js)
- Paste this code
```js
import {Controller} from "@hotwired/stimulus";
import Map from 'ol/Map.js';
import OSM from 'ol/source/OSM.js';
import TileLayer from 'ol/layer/Tile.js';
import View from 'ol/View.js';

export default class extends Controller {
    static targets = ["mapContainer"]

    connect() {
        this.map = new Map({
            target: this.mapContainerTarget,
            layers: [
                new TileLayer({
                    source: new OSM(),
                }),
            ],
            view: new View({center: [0, 0]})
        })
    }
}
```
- create a view (index.html.twig, for example)
- paste this section in the twig file:
```twig
    <div {{ stimulus_controller('openlayers') }}>
        <div style="width: 100vw; height: 50vh;" {{ stimulus_target('openlayers', 'mapContainer') }}></div>
    </div>
```
- navigate to that page

**Expected behavior**
A map should appear on the page, or at leas no error should be thrown in the console.

**Comment by M393** [comment]
Can you provide a stack trace for the error:
> t.view.then is not a function

Also your view configuration is incomplete, it also needs a zoom or resolution, otherwise no map will be visible
```js
new View({
  center: [0, 0],
  zoom: 4,
})
```

How is `this.mapContainerTarget` resolved? Sorry I don't know the framework.

**Comment by matfire** [comment]
Thanks for the quick reply:

here's the stack trace:
```
Error connecting controller

TypeError: t.view.then is not a function
    at new gs (Map-bd313fa6d31162eeb77789d97acf8861.js:7:144844)
    at t.connect (openlayers_controller-271359f440ef8f162ac90c4a0f7f3c75.js:11:20)
    at V.connect (stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7:26908)
    at t.connect (stimulus-static-actions.index-df6865081f45d68e152f2140636af5df.js:7:1820)
    at U.connectContextForScope (stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7:29710)
    at Z.scopeConnected (stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7:36991)
    at H.elementMatchedValue (stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7:35160)
    at B.tokenMatched (stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7:17027)
    at F.tokenMatched (stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7:15724)
    at stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7:15618

{identifier: 'openlayers', controller: t, element: div}
handleError @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
handleError @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
connect @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
t.connect @ stimulus-static-actions.index-df6865081f45d68e152f2140636af5df.js:7
connectContextForScope @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
scopeConnected @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
elementMatchedValue @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
tokenMatched @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
tokenMatched @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
(anonymous) @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
tokensMatched @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
elementMatchedAttribute @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
elementMatched @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
addElement @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
refresh @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
start @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
start @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
start @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
start @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
start @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
start @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
start @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
await in start (async)
start @ stimulus.index-b5b1d00e42695b8959b4a1e94e3bc92a.js:7
startStimulusApp @ loader-e1ee9ace0562f2e6a52301e4ccc8627d.js:13
(anonymous) @ bootstrap-4a0f10d3b854a9e34bddc2ecfd644e59.js:6
```

My bad, must have forgotten to copy the zoom value, but the error is the same.
`this.mapContainerTarget` resolves to an HTMLElement (in this case, the child div in the example above)

**Comment by M393** [comment]
Looks like this error happens directly in the constructor:
https://github.com/openlayers/openlayers/blob/b03d5125abf37bc314a325c922a5e95a41992f73/src/ol/Map.js#L498-L503
Though not sure why `options.view` wouldn't be an instance of `ol/View` ...

Try finding out what `view` is at that time.

**Comment by matfire** [comment]
seems like view has this value when the check calls .then:
``js
{
    "disposed": false,
    "pendingRemovals_": null,
    "dispatching_": null,
    "listeners_": null,
    "revision_": 0,
    "ol_uid": "1",
    "values_": {
        "center": [
            0,
            0
        ],
        "zoom": 4,
        "rotation": 0,
        "resolution": 9783.93962050256
    },
    "hints_": [
        0,
        0
    ],
    "animations_": [],
    "projection_": {
        "code_": "EPSG:3857",
        "units_": "m",
        "extent_": [
            -20037508.342789244,
            -20037508.342789244,
            20037508.342789244,
            20037508.342789244
        ],
        "worldExtent_": [
            -180,
            -85,
            180,
            85
        ],
        "axisOrientation_": "enu",
        "global_": true,
        "canWrapX_": true,
        "defaultTileGrid_": null
    },
    "viewportSize_": [
        100,
        100
    ],
    "targetCenter_": [
        0,
        0
    ],
    "nextCenter_": null,
    "maxResolution_": 156543.03392804097,
    "minResolution_": 0.0005831682455839253,
    "zoomFactor_": 2,
    "minZoom_": 0,
    "constraints_": {},
    "targetRotation_": 0,
    "targetResolution_": 9783.93962050256
}
```

**Comment by ahocevar** [comment]
Maybe there are different versions of OpenLayers involved? The code cited by @M393 should maybe be changed to `options.view instanceof Promise` instead of `!(options.view instanceof View)`.

**Comment by M393** [comment]
Can you inspect your transpiled code and check how the View is created?
Maybe it's wrapped in a Proxy for auomagical data binding.

**Comment by matfire** [comment]
doesn't look like it. Seems there's no transpilation happening. They're only esmodules and seems like they're being loaded as is.
this is the network response:
```js
import {Controller} from "@hotwired/stimulus";
import Map from 'ol/Map.js';
import OSM from 'ol/source/OSM.js';
import TileLayer from 'ol/layer/Tile.js';
import View from 'ol/View.js';

export default class extends Controller {
    static targets = ["mapContainer"]

    connect() {
        let map
        try {
            map = new Map({
                target: this.mapContainerTarget,
                layers: [
                    new TileLayer({
                        source: new OSM(),
                    }),
                ],
                view: new View({center:[0,0], zoom: 4})
            })
        } catch (e) {
            console.log(e)
        }

    }
}
```
in the meanwhile I also tried storing the map in a let variable instead of inside the class, trying to see if it would change anything (spoiler: it didn't)

**Comment by matfire** [comment]
After more experimentation, it looks like it's an issue with AssetMapper and the way it handles imports and such. Switching from it to Vite allows the `ol` package to work as expected.

Thank you for the help in debugging this :)
