### ISSUE TITLE
Cluster's geometryFunction return type does not allow "null"

### ISSUE THREAD

**Issue by NiclasSchmitz** [openlayers/openlayers#16020]
**Describe the bug**
In a _TypeScript_ project you will get an error if you try to return `null` from `ol/source/Cluster`'s geometryFunction. Currently, only `ol/geom/Point` is allowed as return type.

In regards to the [documenation](https://openlayers.org/en/latest/apidoc/module-ol_source_Cluster-Cluster.html), the geometryFunction should return `null` if a feature should not be considered.

```
Type '(feature: Feature<Geometry>) => Point | null' is not assignable to type '(arg0: Feature<Geometry>) => Point'.
  Type 'Point | null' is not assignable to type 'Point'.
    Type 'null' is not assignable to type 'Point'.
```

**To Reproduce**
```typescript
const clusterSource = new ClusterSource({
  source: new VectorSource(),
  geometryFunction: (feature) => {
    const geometry = feature.getGeometry();
    if (geometry && geometry.getType() === "Point") {
      return geometry as Point;
    } else {
      return null;
    }
  },
});
```

**Expected behavior**
`null` should be a valid return type of the geometryFunction.

**Comment by ahocevar** [comment]
You can either add `strictNullChecks: false` to your `tsconfig.json`, or submit a pull request adding `null` as return type.

**Comment by NiclasSchmitz** [comment]
I would like to submit a pull request.
