### ISSUE TITLE
Disrupted rendering when returning true from hasFeatureAtPixel callback

### ISSUE THREAD

**Issue by alpinisme** [openlayers/openlayers#16029]
**Describe the bug**
I have a vector layer on my map, where I have 4 polygons drawn. They show up fine. I also have a `pointermove` event on the map to change the cursor based on what the user is hovering over. Inside that pointermove callback, I check whether there is a feature at the given pixel. At first I used map.hasFeatureAtPixel, but that was behaving strangely, so I switched to map.forEachFeatureAtPixel, inside of which I just set a flag. Strangely, this worked. So I dug into the code, and I noticed that these end up calling very similar code internally, so I tried returning `true` from my `map.forEachFeatureAtPixel` callback, and sure enough the problem returned.

Now, what was happening? The polygons I have in this layer were turning black when I grabbed another one. But, oddly, there was a pattern. If I grabbed the first polgyon, the other three blacked out. If I grabbed the second, the final two blacked out. If the third, only the last blacked out. And if I grabbed the last, none blacked out. Interesting.

But annoyingly, although it is easy to reproduce and reliable given a certain code configuration, removing a click handler or even just removing the map box streets vector layer can stop the problem. It would seem to therefore be a race condition or some shared state that is being disrupted. In any case, it was all I could do to narrow the behavior to a "minimal pair" of works/doesn't work in my codebase, but I didn't have the ability or energy to make it work in a minimal reproduction...it may be quite challenging.

```js
    this.map.on('pointermove', (e) => {
      let cursor = 'grab'
      const originalEvent = e.originalEvent as PointerEvent
      const pixel = this.map.getEventPixel(originalEvent)

      this.map.forEachFeatureAtPixel(
        pixel,
        () => {
          cursor = 'pointer'
          return true // **COMMENTING THIS LINE OUT STOPS THE PROBLEM**
        },
        { layerFilter: (layer) => layer.get('isClickable') === true }
      )
      this.map.getViewport().style.cursor = cursor
    })
```

In any case, by modifying some openlayers code, I was actually able to get the desired behavior. Specifically,  in Layer.js

```js
  forEachFeatureAtCoordinate(
    coordinate,
    frameState,
    hitTolerance,
    checkWrapped,
    callback,
    thisArg,
    layerFilter,
    thisArg2,
  ) {
    let result;
    const viewState = frameState.viewState;

    /**
     * @param {boolean} managed Managed layer.
     * @param {import("../Feature.js").FeatureLike} feature Feature.
     * @param {import("../layer/Layer.js").default} layer Layer.
     * @param {import("../geom/Geometry.js").default} geometry Geometry.
     * @return {T|undefined} Callback result.
     */
    function forEachFeatureAtCoordinate(managed, feature, layer, geometry) {
      return callback.call(thisArg, feature, managed ? layer : null, geometry);
    }

    const projection = viewState.projection;

    const translatedCoordinate = wrapX(coordinate.slice(), projection);
    const offsets = [[0, 0]];
    if (projection.canWrapX() && checkWrapped) {
      const projectionExtent = projection.getExtent();
      const worldWidth = getWidth(projectionExtent);
      offsets.push([-worldWidth, 0], [worldWidth, 0]);
    }

    const layerStates = frameState.layerStatesArray;
    const numLayers = layerStates.length;

    const matches = /** @type {Array<HitMatch<T>>} */ ([]);
    const tmpCoord = [];
    for (let i = 0; i < offsets.length; i++) {
      for (let j = numLayers - 1; j >= 0; --j) {
        const layerState = layerStates[j];
        const layer = layerState.layer;
        if (
          layer.hasRenderer() &&
          inView(layerState, viewState) &&
          layerFilter.call(thisArg2, layer)
        ) {
          const layerRenderer = layer.getRenderer();
          const source = layer.getSource();
          if (layerRenderer && source) {
            const coordinates = source.getWrapX()
              ? translatedCoordinate
              : coordinate;
            const callback = forEachFeatureAtCoordinate.bind(
              null,
              layerState.managed,
            );
            tmpCoord[0] = coordinates[0] + offsets[i][0];
            tmpCoord[1] = coordinates[1] + offsets[i][1];
            result = layerRenderer.forEachFeatureAtCoordinate(
              tmpCoord,
              frameState,
              hitTolerance,
              callback,
              matches,
            );
          }
          // if (result) {   **MOVEd THIS DOWN OUTSIDE THE LOOP** 
          //  return result;
          // }
        }
      }
    }
   if (result) { return result } // **THIS LINE IS THE NEW LOCATION**
    if (matches.length === 0) {
      return undefined;
    }
    const order = 1 / matches.length;
    matches.forEach((m, i) => (m.distanceSq += i * order));
    matches.sort((a, b) => a.distanceSq - b.distanceSq);
    matches.some((m) => {
      return (result = m.callback(m.feature, m.layer, m.geometry));
    });
    return result;
  }
```

By making that change (or unmaking it), I am able to cause the problem to appear or disappear at will. It seems very strange, and I don't understand why it's happening. Anyone have any ideas? 

https://github.com/user-attachments/assets/1b93e026-bc58-4949-ac8c-b4b5bd6bf9a1

**Comment by ahocevar** [comment]
Not that it would solve your problem, but because I see it so often:
```js
      const originalEvent = e.originalEvent as PointerEvent
      const pixel = this.map.getEventPixel(originalEvent)
```
can and should be simplified to
```js
      const pixel = e.pixel
```
And another thing that will not fix your issue but, you should set the cursor on the target element, not the viewport:
```
this.map.getTargetElement().style.cursor = cursor
```
The change you made in OpenLayers  is effectively the same as not returning `true` in the `forEachFeatureAtPixel` callback. The question is: can you create a minimal example in a codesandbox or jsfiddle, outside of your code base, that exposes the problem? Maybe you're handling the pointermove event in a bad context (e.g. a render function)?

**Comment by alpinisme** [comment]
Those are good suggestions. Thank you. 

You are right that my change was effectively not to return true (but that was all I was trying to show -- although moving the return statement was probably not the best way to do that). Part of my confusion about this issue was stemming from the fact that I didn't actually expect `forEachFeatureAtPixel` to stop executing the loop when a truthy value was returned. I think if nothing else, adding a clear comment on that might be useful documentation. 

I don't have a lot of the time at the moment to dedicate to creating a minimal reproduction, but I will try. I can comment some about the context, though: this event listener is added in the constructor of a class that represents our openlayers map. It is definitely only constructed once per map instance, and we don't see any issues with maps being constructed unexpectedly. If I log this event registration, it only happens once and where expected.

**Comment by alpinisme** [comment]
Additionally, what seems most strange is that returning _earlier_ from this callback is causing seemingly a delay in rendering.

**Comment by ahocevar** [comment]
> I didn't actually expect forEachFeatureAtPixel to stop executing the loop when a truthy value was returned.

100% agreed - we should have deprecated and removed that method a long time ago. To avoid that confusion, we created "getFeaturesAtPixel()" instead.

**Comment by ahocevar** [comment]
> Additionally, what seems most strange is that returning earlier from this callback is causing seemingly a delay in rendering.

So I'm asking again: are you running that code in a render function (prerender/postrender), a style function, or something similar?

**Comment by alpinisme** [comment]
> So I'm asking again: are you running that code in a render function (prerender/postrender), a style function, or something similar?

I just double checked, and the only time `forEachFeatureAtPixel` is called in our codebase is that one callback quoted in my initial report: `map.on('pointermove', ...)`

**Comment by ahocevar** [comment]
Please provide a minimal example in a codesandbox or jsfiddle to show the problem. You can use the "Edit" button on any of the examples in https://openlayers.org/en/latest/examples/ to get started with a codesandbox. When done, don't forget to make the codesandbox public or visible to anyone who has the link.

**Comment by alpinisme** [comment]
I just upgraded to 10.0.0, and I'm no longer able to reproduce the bug. I don't know what changed, but my desire to create a minimal reproduction has evaporated, so I'm closing this issue. Thanks for your time!
