### ISSUE TITLE
WebGL Vector Layer example flashes on hover or click

### ISSUE THREAD

**Issue by Sidders22** [openlayers/openlayers#16039]
**Describe the bug**
The OSM TileLayer in [this example](https://openlayers.org/en/latest/examples/webgl-vector-layer.html) goes blank when hovering over features with a mouse (desktop; Chrome/Edge/Firefox) and when tapping via mobile (only tested on Chrome).

**Expected behavior**
I expect all layers to be stable when interacting with the map.

**Comment by MoonE** [comment]
Bisecting points to commit dafcf563ac10f25c84c08c3501676d54466c3475 @jahow

**Comment by jahow** [comment]
thank you for looking into this!

**Comment by kikuchan** [comment]
According to the MDN document of the `gl.deleteBuffer()`,
> Normally you don't need to call this method yourself, when the buffer object is dereferenced it will be marked as free.

So it would be unnecessary to delete the buffers. Perhaps, is there anything related to leak?

Anyway, I've not yet to figure out the exact reason, but the old buffers required to be kept active in some frames between the `this.getLayer().changed()` and the actural next `renderFrame()` in this case.
I've posted a PR for this issue to fix by delaying the deletion until the next frame.

**Comment by cherealnice** [comment]
I'm having the same issue. Is the PR ready to be merged? Is there anything I can do to speed up the process?
