### ISSUE TITLE
Rendering error when tile source provides only a sub extent of the view projection

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#16038]
**Describe the bug**
When a tile layer's source extent is outside the current view extent an error occurs during rendering at this line because `tilesByZ[z]` is undefined.
https://github.com/openlayers/openlayers/blob/ff9fa42a28ffc710ccfe602fcd176e1359c1c233/src/ol/renderer/canvas/TileLayer.js#L636

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/wmts-hidpi.html
2. Pan Austria outside the view
3. See error

**Expected behavior**
No error, just don't render the layer.

**Comment by tdewolff** [comment]
I can second this bug. Probably happened in the v10 release? I'm using the new `ImageTileSource` in the `TileLayer` that defines an extent:

```js
    const layer = new TileLayer({
      extent: extent,
      source: new ImageTileSource({
        maxZoom: 14,
        interpolate: true,
        loader: (z, x, y, options)=>{
            ...
        },
      }),
    });
```

**Comment by tdewolff** [comment]
@ahocevar Thanks for the quick fix! When do you think there will be new patch/minor release, approximately?

**Comment by tdewolff** [comment]
I've updated to the GitHub repo and this bug is still happening. Line 637 of ol/renderer/canvas/TileLayer.js says that `tilesByZ[z]` is undefined. I've added `if (!tilesByZ[z]) { return; }` right before to fix it, but surely there is a better way to fix this.

**Comment by M393** [comment]
I can say it fixes the error I had.

**Comment by tdewolff** [comment]
Yes, that fixed the issue, thank you!
