### ISSUE TITLE
打包部署后页面空白

### ISSUE THREAD

**Issue by panzhaoyang-520** [openlayers/openlayers#16046]
本地启动正常，页面正常显示，但是部署服务后页面打开空白，然后报错如下：

Refused to create a worker from 'blob:https://xxx/d607ca2a-d2eb-4b2b-a5f8-8c9a7a0bc8d5' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

使用的ol 8.2.0版本，webpack4.xx，显示webgl.js第四行里面的worker报错，但是不知道怎么解决
之前页面启动时候报错，加了transpileDependencies: ["ol", "color-parse"]后就正常了，但是部署服务用域名访问就不显示地图了，不知道是哪里的问题

webgl.js:4 Uncaught DOMException: Failed to construct 'Worker': Access to th

请帮忙看一下，非常感谢

**Comment by ahocevar** [comment]
If you use Content Security Policy, you need to grant the required rights. The error message you get says pretty much everything you have to do.

**Comment by panzhaoyang-520** [comment]
> 如果您使用内容安全策略，则需要授予所需的权限。您收到的错误消息几乎说明了您必须执行的所有操作。

你好，请问下我应该怎么改呢，之前没有遇到过这种问题

**Comment by ahocevar** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP.

Closing, not an OpenLayers issue.

**Comment by panzhaoyang-520** [comment]
> See https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP.
> 
> Closing, not an OpenLayers issue.

感谢你，我在页面加入了<meta http-equiv="Content-Security-Policy" content="default-src 'self' 'unsafe-inline'; worker-src blob:;">这行，目前只有火狐浏览器可以访问地图，谷歌浏览器还是白屏，不知道该如何解决了

**Comment by panzhaoyang-520** [comment]
> > See https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP.
> > Closing, not an OpenLayers issue.
> 
> 感谢你，我在页面加入了这行，就是这个目前只有火狐浏览器可以访问地图，谷歌浏览器还是白屏，不知道该如何解决了
