### ISSUE TITLE
Incorrect render order of Draw Interaction

### ISSUE THREAD

**Issue by levelost** [openlayers/openlayers#16049]
**Describe the bug**
Polygons are drawn under the circles.

**To Reproduce**
1. https://openlayers.org/en/latest/examples/draw-and-modify-features.html
2. Draw several circles on top of each other (to reduce transparency).
3. Draw a polygon on circles.
4. The polygon appears under the circles.
![scr](https://github.com/user-attachments/assets/657f9ae2-7b2f-45df-9c6f-6cfe772e433a)

**Expected behavior**
The last figure drawn should be on top.

**Comment by levelost** [comment]
`useSpatialIndex: false` did not work.

**Comment by ahocevar** [comment]
Circles are points and will always be rendered on top of polygons. This has nothing to do with spatial index or the Draw interaction, it is the basic rendering order (polygon - line - point). To control that, you need to use z-index on your styles.
