### ISSUE TITLE
TS7016: Could not find a declaration file for module

### ISSUE THREAD

**Issue by YuriiDmytryshyn** [openlayers/openlayers#16043]
**Describe the bug**
"ol": "6.5.0" - TS7016: Could not find a declaration file for module.
I saw you added in [v6.6.0](https://github.com/openlayers/openlayers/releases/tag/v6.6.0), but version 6.5.0 should still work as CommonJS?
import Map from 'ol/Map'; - Could not find a declaration file for module.

**To Reproduce**
only install version 6.5.0

**Expected behavior**
Must see module

**Comment by M393** [comment]
If you want types for ol v6.5 you can install [@types/ol@6.5.3](https://www.npmjs.com/package/@types/ol/v/6.5.3)

**Comment by YuriiDmytryshyn** [comment]
I did it but "npm i --save-dev @types/ol", with "npm i --save-dev @types/ol@6.5.0" all good.
Thank you, @close
