### ISSUE TITLE
Single-band GeoTIFFs behave as if they have three bands in style expressions

### ISSUE THREAD

**Issue by ddohler** [openlayers/openlayers#16065]
**Describe the bug**
For the purpose of style expressions, single-band GeoTIFFs behave as if they have 3 identical bands, which unexpectedly places the alpha band generated by the `nodata` source parameter into the fourth band.

**To Reproduce**
1. Construct a `GeoTIFF` source to a single-band GeoTIFF. In case it's important, the file that exhibited the issue for me has the following `gdalinfo` output:
    ```
    Band 1 Block=512x512 Type=Float32, ColorInterp=Gray
    NoData Value=nan
    Overviews: 38016x46208, 19008x23104, 9504x11552, 4752x5776, 2376x2888, 1188x1444, 594x722, 297x361
    ```
I constructed my GeoTIFF source as follows:
```javascript
const source = new GeoTIFF({
      normalize: false,
      interpolate: false,
      sources: [{ url: <no public source but I suspect any single-band GeoTIFF with a no-data value will work>, nodata: NaN, bands: [1] }],
});
cogLayer.setSource(source);
```
`cogLayer` is a `WebGLTileLayer()`.

Style the layer using something like
```javascript
cogLayer.setStyle({
      color: ["color", 255, 0, 0, ["band", 2]], // <-- Expecting this to be the nodata alpha band
    });
```

**Expected behavior**
I expected the above snippets to result in a GeoTIFF layer that displays bright red wherever there is data, and be transparent elsewhere, like this:

![image](https://github.com/user-attachments/assets/b151d32b-1163-4e20-954d-0b7e0350c9f4)

But the actual behavior is that the transparency mirrors the data band:
![image](https://github.com/user-attachments/assets/e0885fe3-3807-4b46-a89d-b50f3419d804) 

[The docs for the `'band'` operator say](https://openlayers.org/en/latest/apidoc/module-ol_expr_expression.html#~ExpressionValue):
> [TileImage](https://openlayers.org/en/latest/apidoc/module-ol_source_TileImage-TileImage.html) sources have 4 bands: red, green, blue and alpha. [DataTileSource](https://openlayers.org/en/latest/apidoc/module-ol_source_DataTile-DataTileSource.html) sources can have any number of bands, depending on the underlying data source and [configuration](https://openlayers.org/en/latest/apidoc/module-ol_source_GeoTIFF.html#~Options).

Since `GeoTIFF` [inherits from `DataTileSource`](https://openlayers.org/en/latest/apidoc/module-ol_source_GeoTIFF-GeoTIFFSource.html), I took this to mean that the number of bands accessible by the `'band'` operator would be equal to the number of bands in the source, and so `['band', 1]` would be the data band and `['band', 2]` would return the alpha nodata mask. But that is not what actually happens; from within the style expression, `["band", 1]`, `["band", 2]`, and `["band", 3]` all return the same value, which is the same as the GeoTIFF's single band. The alpha value, on the other hand, is accessible via `["band", 4]`.

I hope this is clear, but I'm happy to provide any other info that would be helpful if it isn't!

**Comment by mike-000** [comment]
See #16000
It should be fixed in version 10.0.0

**Comment by ddohler** [comment]
Hmm, that does seem like a very similar issue, but I upgraded to 10.0.0 in an attempt to fix this because I saw that it had changes to style expression handling, and I'm still seeing the same behavior even under 10.0.0 (confirmed by logging `ol.VERSION` to the console).

I tried wrapping my `setStyle()` call so that it happens after the source is ready and didn't see different results:
```javascript
    cogLayer
      .getSource()
      .getView()
      .then(() => {
        cogLayer.setStyle({
          color: [
            "case",
            ["==", alpha, 0],
            "#00000000",
            ["interpolate", ["linear"], b1, ...ramp],
          ],
        });
      });
```

So I think what I am seeing may be subtly different; I'll try to put together a minimal sandbox for reproduction.

**Comment by ddohler** [comment]
Okay, I've set up a minimal [sandbox ](https://codesandbox.io/p/sandbox/dazzling-hawking-xrgwpl?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzjr5ayf00072a695b5n23tw%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzjr5ayf00032a69i7madqdh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzjr5ayf00042a69ae67jmz9%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzjr5ayf00062a69jwich2ya%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzjr5ayf00032a69i7madqdh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjr5ayf00022a69hp0cm3js%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clzjr5ayf00032a69i7madqdh%2522%252C%2522activeTabId%2522%253A%2522clzjr5ayf00022a69hp0cm3js%2522%257D%252C%2522clzjr5ayf00062a69jwich2ya%2522%253A%257B%2522id%2522%253A%2522clzjr5ayf00062a69jwich2ya%2522%252C%2522activeTabId%2522%253A%2522clzjr5sfh00142a6936bx0usc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzjr5ayf00052a69m4kvy0oi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzjr5sfh00142a6936bx0usc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzjr5ayf00042a69ae67jmz9%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzjr5ayf00042a69ae67jmz9%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) for this.

There are two definitions of the `alpha` band; using band 2 results in unexpected partial transparency in areas where there is data:
![image](https://github.com/user-attachments/assets/819230fa-f9c8-4ca3-a728-024e68afa8f0)
Commenting out the band 2 definition and uncommenting the band 4 definition displays red everywhere that there is data, as expected:
![image](https://github.com/user-attachments/assets/bfa9074f-0d9f-478e-a6f3-336276713c50)


Please let me know if you need anything else!

**Comment by mike-000** [comment]
Thanks, that is reproducible with the test data used in #16006 if the layer (without source) is added to a map with preset view and the source is set after a delay.
