### ISSUE TITLE
Premultiplied-alpha applied twice on WebGLTileLayer

### ISSUE THREAD

**Issue by kikuchan** [openlayers/openlayers#16074]
**Describe the bug**
Styling a tile by `color` operator with alpha value on WebGLTile layer, darken the color unexpectedly.

**To Reproduce**
```js
import Map from 'ol/Map.js';
import OSM from 'ol/source/OSM.js';
import TileLayer from 'ol/layer/WebGLTile.js';
import View from 'ol/View.js';

const map = new Map({
  layers: [
    new TileLayer({
      source: new OSM(),
      style: {
        color: ['color', 255, 255, 255, 0.5],
      },
    }),
  ],
  target: 'map',
  view: new View({
    center: [0, 0],
    zoom: 2,
  }),
});
```
**Expected behavior**
The tile should be rendered as if `rgba(255, 255, 255, 0.5);` (transparent white), but it is rendered as if `rgba(128, 128, 128, 0.5);` (transparent gray) instead.

**Comment by kikuchan** [comment]
This would be easy...?
```diff
diff --git a/src/ol/layer/WebGLTile.js b/src/ol/layer/WebGLTile.js
index 15c701ec7c..e4aa6a0acc 100644
--- a/src/ol/layer/WebGLTile.js
+++ b/src/ol/layer/WebGLTile.js
@@ -255,10 +255,11 @@ function parseStyle(style, bandCount) {
         Uniforms.TILE_TEXTURE_ARRAY
       }[0],  v_textureCoord);

+      color.rgb *= color.a;
+
       ${pipeline.join('\n')}

       gl_FragColor = color;
-      gl_FragColor.rgb *= gl_FragColor.a;
       gl_FragColor *= ${Uniforms.TRANSITION_ALPHA};
     }`;
```

**Comment by mike-000** [comment]
It works as expected when the color is defined using `'array'`. These layers should look the same but `layer2` is darker.

```
const layer1 = new TileLayer({
  source: new OSM(),
  style: {
    color: ['array', ['band', 1], ['band', 2], ['band', 3], 0.5],
  },
});

const layer2 = new TileLayer({
  source: new OSM(),
  style: {
    color: [
      'color',
      ['*', ['band', 1], 255],
      ['*', ['band', 2], 255],
      ['*', ['band', 3], 255],
      0.5,
    ],
  },
});
```

**Comment by kikuchan** [comment]
Hi @mike-000, thank you for the information!
I didn't know that the `color` was expressed this way.

Unfortunately, my previous method doesn't work with this notation because `['array', 1, 1, 1, 0.5]` is simply compiled into `vec4(1.0, 1.0, 1.0, 0.5)`, which is too bright in the shaders.

Although this notation currently doesn't work as expected in `styleparser` for the same reason, I like it because it's natural and straightforward, especially when combined with the `band` operator, as in your code. Besides, it's easily convertible and consistent with other notations such as `['color', 255, 255, 255, 0.5]` and `"rgba(255, 255, 255, 0.5)"`.

To fully support this notation, `['color', r, g, b, a]` needs to be compiled into `vec4(r/255.0, g/255.0, b/255.0, a)` without any pre-multiplied alpha. This breaks existing `styleparser` and many tests, but it's worth it. So I'll compose a PR to fix the issue in this way for consistentency and naturally expected behavior.

What do you think about this?

Thanks.

**Comment by jahow** [comment]
Wait, if I recall correctly alpha premultiplication is always done at the latest stage possible in the fragment shaders. It should not be a concern during expressions compilation for instance.

Also I'm surprised that you can express a color using `array` and the expression compiler just running with it. I feel like there should be a distinction between an Array[4] and a Color, since there is a conversion operator, but I might be wrong (didn't look much more into this, sorry).

**Comment by kikuchan** [comment]
Hi @jahow, thank you for your comment!

> alpha premultiplication is always done at the latest stage possible in the fragment shaders.

Yes, basically this is the most common approach, but actually its timing is up to a shader author I think.
In fact, the current fragment shader generated for `WebGLTileLayer` looks like [this](https://github.com/openlayers/openlayers/blob/aa400270c347643a7b59da95ae929e53daf7576a/test/browser/spec/ol/layer/WebGLTile.test.js#L421-L434):
```glsl
void main() {
  if (
    v_mapCoord[0] < u_renderExtent[0] ||
    v_mapCoord[1] < u_renderExtent[1] ||
    v_mapCoord[0] > u_renderExtent[2] ||
    v_mapCoord[1] > u_renderExtent[3]
  ) {
    discard;
  }
  vec4 color = texture2D(u_tileTextures[0], v_textureCoord);
  color = vec4((getBandValue(4.0, 0.0, 0.0) / 3000.0), (getBandValue(1.0, 0.0, 0.0) / 3000.0), (getBandValue(2.0, 0.0, 0.0) / 3000.0), 1.0);
  gl_FragColor = color;
  gl_FragColor.rgb *= gl_FragColor.a;
  gl_FragColor *= u_transitionAlpha;
}
```

The right-hand side of the second `color` variable assignment `vec4((getBandValue(4.0, 0.0, 0.0) / 3000.0), ..., 1.0)` is generated by `expressionToGlsl(..., ColorType)`, and the statement is forged and injected by `${pipeline.join('\n')}`: https://github.com/openlayers/openlayers/blob/aa400270c347643a7b59da95ae929e53daf7576a/src/ol/layer/WebGLTile.js#L254-L262 This indicates that the author might believe premultiplication is not applied during the `pipeline` process.


> I'm surprised that you can express a color using array and the expression compiler just running with it.

Yeah, I was surprised too, haha, but I like it now.
The author might consider using an `array` to express a color:
```js
const red = normalize(['band', 1]);
const green = normalize(['band', 2]);
const nir = normalize(['band', 4]);

layer.setStyle({
  color: ['array', nir, red, green, 1],
});
```

**Comment by mike-000** [comment]
> The author might consider using an `array` to express a color:

Some examples use it, e.g. https://openlayers.org/en/latest/examples/cog-stretch.html

**Comment by jahow** [comment]
Ok, thanks a lot @kikuchan for looking into great detail into this! Indeed, the strategies are different: the vector renderers do the alpha premultiplying as early as possible, i.e. when writing a color into the shader or reading from a texture. The tile renderer does it at the end before rendering, which means it can show colors which had alpha applied two times (or more).

The early premultiplication was done in https://github.com/openlayers/openlayers/pull/14685

I honestly don't remember why it was needed instead of just doing the premultiplication at the end of the shader. I'll keep looking.
