### ISSUE TITLE
Regression: new required dependecy "rbush"

### ISSUE THREAD

**Issue by KyllianGautier** [openlayers/openlayers#16083]
Building project that required openlayers does not longer work without also including rbush dependecy:

![image](https://github.com/user-attachments/assets/c1435d9b-e684-4eb6-aa32-a8b87a29615a)

Previously it wat not required, is that a regression ?

**Comment by ahocevar** [comment]
This is probably caused by #15979. @MoonE, I think `@types/rbush` needs to be a `dependency`, not a `devDependency`, given the way it is being used.
