### ISSUE TITLE
break ts change after update 9.24 to 10.0.0

### ISSUE THREAD

**Issue by codeflyA** [openlayers/openlayers#16089]
in v10 polygonVectorLayer infer to
![image](https://github.com/user-attachments/assets/7447ecf1-cacd-4227-b007-c573bd80e616)
![image](https://github.com/user-attachments/assets/0490c433-b127-4242-9744-3056878808f6)
but version 9.24 infer to ![image](https://github.com/user-attachments/assets/39176017-8590-4302-be32-06ebf98ddb68) break changes？ the issue relate to https://github.com/openlayers/openlayers/issues/15830

**Comment by M393** [comment]
Generics of VectorLayer did change with v10: #15869 #15887

Could you clarify what your issue/bug with this is?

**Comment by codeflyA** [comment]
> Generics of VectorLayer did change with v10: #15869 #15887
> 
> Could you clarify what your issue/bug with this is?

ok thanks

**Comment by ahocevar** [comment]
Type generics were badly broken in v9.2, and should be fixed in v10.
