### ISSUE TITLE
type error in ts

### ISSUE THREAD

**Issue by hubenchang0515** [openlayers/openlayers#16091]
**Describe the bug**
```
error TS2322: Type 'ImageTileSource' is not assignable to type 'DataTileSource<DataTile>'.
  The types returned by 'getReprojTile_(...)' are incompatible between these types.
    Type 'ImageTile' is missing the following properties from type 'DataTile': loader_, data_, error_, size_, and 4 more.
```

**To Reproduce**
```ts
new WebGLTileLayer({
    source: new ImageTileSource({
        url: props.url,
        wrapX: true,
}),
```

**Expected behavior**
use WebGLTileLayer to render image tile

**Comment by ahocevar** [comment]
#16097 should fix this.

**Comment by boeckMt** [comment]
This also happens for all sources that depend on the deprecated `ol/source/TileImage.js`.
Like `ol/source/OSM`, `ol/source/TileWMS` ...
e.g.

```js
import WebGLTileLayer from 'ol/layer/WebGLTile';
import OSM from 'ol/source/OSM';

new WebGLTileLayer({
    source:  new OSM()
}),
```

Is there a workaround for this? I couldn’t find anything in the [releases Notes](https://github.com/openlayers/openlayers/releases)

**Comment by ahocevar** [comment]
You can use `ol/layer/Tile` instead of `ol/layer/WebGLTile`.

**Comment by boeckMt** [comment]
Thanks for the quick response!
Maybe it doesn't make a difference in the OSM example, but there might be a performance improvement for other sources if they are used with `ol/layer/WebGLTile`?

Is it planned to migrate `ol/source/TileWMS` (and the other sources which depend on TileImage), so it extends `ol/source/ImageTile`?

**Comment by ahocevar** [comment]
There should not be any performance difference. And yes, it is planned to change the tile image sources to become more modular (with ready-to-use loaders), similar to the image sources, and extend `ol/source/ImageTile`. There is no ETA for this though.
