### ISSUE TITLE
API methods missing in version 10.0.0 documentation

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#16113]
**Describe the bug**
Some methods are missing from classes in the version 10.0.0 documentation.  Seen in format classes, but others might be affected.

**To Reproduce**
For example 

https://openlayers.org/en/v9.2.4/apidoc/module-ol_format_GeoJSON-GeoJSON.html
has 10 methods
https://openlayers.org/en/v10.0.0/apidoc/module-ol_format_GeoJSON-GeoJSON.html
has 3 methods

https://openlayers.org/en/v9.2.4/apidoc/module-ol_format_KML-KML.html
has 11 methods
https://openlayers.org/en/v10.0.0/apidoc/module-ol_format_KML-KML.html
has 7 methods

**Expected behavior**
If the missing methods are not deprecated they should continue to be shown.

**Comment by ahocevar** [comment]
Good find @mike-000, thanks for reporting this. I think this comes from the newly introduced `@override` annotations. I'll see if I can fix our JSDoc plugins to handle that properly.
