### ISSUE TITLE
codesandbox reported an error

### ISSUE THREAD

**Issue by Lazydd** [openlayers/openlayers#16110]
![image](https://github.com/user-attachments/assets/241abb71-dece-44c3-8900-6d1210324129)

{"error":"This endpoint requires the params `files` or `parameters` in order to work. See https://codesandbox.io/docs/importing#create-wizard for more details."}

**Comment by ahocevar** [comment]
Maybe a temporary problem? Or does this only happen with a specific example? Please provide a list of steps to reproduce the problem.

**Comment by Lazydd** [comment]
> Maybe a temporary problem? Or does this only happen with a specific example? Please provide a list of steps to reproduce the problem.

It seems that this happens when you right-click and open a new tab

**Comment by ahocevar** [comment]
That makes sense, because then codesandbox will not be able to receive the data we send along with the request. Please just click the button, don't open it in a new tab.

**Comment by Lazydd** [comment]
> 这是有道理的，因为这样 codesandbox 将无法接收我们随请求发送的数据。请单击按钮，不要在新选项卡中打开它。

ok
