### ISSUE TITLE
Namespace RBush has no exported member 'default'

### ISSUE THREAD

**Issue by frontmatec-phd** [openlayers/openlayers#16138]
**Describe the bug**
when compiling the angular project, the angular compiler complains the rbush namespace has no 'default' member.
This most likely occurs because of the newly added dependency to @types/rbush, which does not present a default member.

![image](https://github.com/user-attachments/assets/2a0b52e5-7645-47f8-87c3-d846e142c053)

**To Reproduce**
1. use newest ol in your angular project
3. compile the angular project
5. See error

**Comment by M393** [comment]
Which version of @types/rbush do you have installed? The new v3.0.4 seems to have an issue, try v3.0.3.

**Comment by frontmatec-phd** [comment]
Downgrading the package-lock.json manually fixes the issue. 
It seems like the issue is the 3.0.4 version.

**Comment by zernolo** [comment]
I have the same isssue with ng on windows 11, but not in Ubuntu.
On windows 11 I've tryied to add modles with npm or yarn, but nothing helped.
On ubuntu everythig goes well.

**Comment by ahocevar** [comment]
Until this is fixed, we can force version 3.0.3 of @types/rbush. I created #16194 with that change.
