### ISSUE TITLE
TileLayer loop over not iterable

### ISSUE THREAD

**Issue by marcomilone** [openlayers/openlayers#16134]
Sorry,
I don't know how to reproduce it,
btw Sentry is reporting me this:

I'm under ol 10.0
cannot upgrade to 10.1
because ol-mbtiles depends from 10.0 (no more)

Btw I hope this will be useful to someone.

TypeError
S[f] is not iterable

../../node_modules/ol/renderer/canvas/TileLayer.js https://omitted.com/assets/index-Ck1MHxBJ.js in Qoe.renderFrame at line 636:24

```javascript
    const uid = getUid(this);
    const time = frameState.time;

    // look for cached tiles to use if a target tile is not ready
    for (const tile of tilesByZ[z]) {
      const tileState = tile.getState();
      if (
        (tile instanceof ReprojTile || tile instanceof ReprojDataTile) &&
        tileState === TileState.EMPTY
```

**Comment by MoonE** [comment]
Looks like  #16038. 

If you can't upgrade to v10.1.0, maybe downgrade to v9.2.4?

**Comment by marcomilone** [comment]
Thanks a lot,
sorry I searched for the bug in the issues to avoid a double issue.

I will not downgrade, at the end the error is not blocking my app

**Comment by marcomilone** [comment]
duplicate https://github.com/openlayers/openlayers/issues/16038.
