### ISSUE TITLE
Map not update when reprojected.

### ISSUE THREAD

**Issue by oxyeez** [openlayers/openlayers#16136]
**Description**
When setting a new projection from the code, the map is not updated for the new projection.

**To Reproduce**
1. Go to [this ol example](https://openlayers.org/en/latest/examples/reprojection-by-code.html)
2. Select a new projection ex: EPSG:32661 (UPS North).
3. The map is well updated.
4. Select another projection ex: EPSG:32761 (UPS South).
5. The map is not updated. To update it correctly we need to make an explicit action triggering the refresh of it, like "Render reprojection edges" for exemple.

**Expected behavior**
In the previous versions, on change of the projection in the view, or set of a new view with different projection, the map was updated for the new projection without the need to force its refresh.

**Comment by mike-000** [comment]
If you zoom in and out the map switches from arctic to antarctic and back again.  It is using cached reproj tiles for the wrong projection.  This appears to have been introduced by #15905.  It works as expected if you use a WebGLTile layer, which once had a similar issue which was fixed by #14015.

**Comment by mike-000** [comment]
#16141 will fix this
https://deploy-preview-16141--ol-site.netlify.app/en/latest/examples/reprojection-by-code.html
