### ISSUE TITLE
The `removeLastPoint` function in the official example is not functioning correctly.

### ISSUE THREAD

**Issue by mostafaznv** [openlayers/openlayers#16150]
**Describe the bug**
The `removeLastPoint` function in the official example does not work properly; in fact, it does not work at all.
I'm unsure if I'm misunderstanding its functionality or if it's a bug.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/draw-features.html
2. Add two polygons, some points, and line strings to the map
3. Click on the `Undo` button
4. It does not have any effect

**Expected behavior**
I expect the `Undo` button to remove the last item I added to the map, particularly polygons and multi-polygons.

**Comment by ahocevar** [comment]
Your expectation is wrong: the `removeLastPoint()` function removes the previously drawn vertex of a LineString or Polygon geometry. Could we document it better to make that clearer?

**Comment by mostafaznv** [comment]
Thank you for your response. It seems I misunderstood the situation.
Yes, I believe it would be beneficial to document it with a more explicit description.

I intend to close this issue, but before doing so, is there an alternative method to undo the entire polygon?

**Comment by ahocevar** [comment]
Register a listener to the `drawend` event, and store the event object's `feature` for deletion:
```js
let lastDrawnFeature;
drawInteraction.on('drawend', e => {
  lastDrawnFeature = e.feature;
});

function deleteLastFeature() {
  if (!lastDrawnFeature) {
    return;
  }
  vectorSource.removeFeature(lastDrawnFeature);
}

**Comment by mostafaznv** [comment]
Thank you very much.
