### ISSUE TITLE
V10 seems to introduce a detached tile image memory leak

### ISSUE THREAD

**Issue by anthonn** [openlayers/openlayers#16156]
If zooming some and panning around a lot in this example:
https://openlayers.org/en/v9.2.4/examples/draw-features.html
Then the following detached elements can be found in chrome debugger:

![Screenshot 2024-09-04 172921](https://github.com/user-attachments/assets/412fb7f2-d2c6-4b0c-9b56-b62f5ff89bfb)

There are both new and deleted detached images.

But if doing the same for a long time in this example (v10.1.0):
https://openlayers.org/en/latest/examples/draw-features.html
Then the following detached elements can be found in chrome debugger:

![Screenshot 2024-09-04 173629](https://github.com/user-attachments/assets/64d3a230-cf3a-475a-8990-82d0e1704e33)

There are no deleted images at all! Only 22000+ new detached images.

I guess this might be a new raised caching limit, but then this limit has been raised alot between version 9 and 10. 

(A lot of IOS users have started getting map crashes in my application also, which might be due to this. It could be something else also)

**Comment by anthonn** [comment]
No unfortunately I have only seen what happens and not why.

**Comment by ahocevar** [comment]
@anthonn Can you check see if you still get iOS crashes with https://deploy-preview-16157--ol-site.netlify.app/en/latest/examples/draw-features.html? #16157 should fix the memory leak.

**Comment by anthonn** [comment]
The crashes was in the application I'm building which has 4 wms layers 1 wmts and multiple vector layers on top and hundreds/thousands of vectors with texts.
So to really test I need to use it in that environment. Guess I could add the code changes to my dev environment, but it will take some time before I can do that, since I have some other urgent things at work. (Have stepped back ol in the mean time).

I will try to test when I get the time. Thanks for the quick response and fix!
