### ISSUE TITLE
WebGL Vector Layer flickering since 10.0.0

### ISSUE THREAD

**Issue by sandman7920** [openlayers/openlayers#16152]
It flashes a white light onMouseMove setting a new style on hover.
Example: https://openlayers.org/en/latest/examples/webgl-vector-layer.html

Tests are done on Windows 11, Arch Linux Wayland, and Ubuntu Xorg.
![image](https://github.com/user-attachments/assets/291e134f-fa6d-493e-99f1-b3e1ea8664de)

Windows Info
![win](https://github.com/user-attachments/assets/23c0d2e9-c657-44de-b534-21a5abfae75f)

Linux Info
![image](https://github.com/user-attachments/assets/19e02ae8-ed9b-4e67-9f71-85ce4882bd11)

[Screencast_20240903_153320.webm](https://github.com/user-attachments/assets/0c2048f2-98fd-4f0e-9e04-8545d72a0772)

Edit:
Same on Android.
If it's helpful during Active Pan everything is OK.

**Comment by mike-000** [comment]
Fixed by #16055 https://openlayers.org/en/main/examples/webgl-vector-layer.html

**Comment by sandman7920** [comment]
Thank you.
