### ISSUE TITLE
TileLayer with extent does not wrapX

### ISSUE THREAD

**Issue by tdewolff** [openlayers/openlayers#16175]
While specifying a TileLayer such as

```js
    const tileLayer = new TileLayer({
      extent: imageExtent,
      maxZoom: maxZoom,
      source: new ImageTileSource({
        interpolate: false,
        loader: (z, x, y, options)=>{
          // ...
        },
      }),
    });
```

the `extent` prevents the tile layer from repeating across duplicate worlds left and right, it seems that `wrapX` is not implemented, even though it is set implicitly for `ImageTileSource`. Is this a bug or intended? How can I achieve that it wraps around?

PS: marvelous work this library!

**Comment by mike-000** [comment]
You are limiting the layer extent, `wrapX` is a source property.  You can prevent tiles being served by setting a tile grid with limited extent, for example https://stackblitz.com/edit/js-cuyflt?file=index.html,package.json,index.js

**Comment by tdewolff** [comment]
Thank you very much, that is working flawlessly!!
