### ISSUE TITLE
After updating to V10, .getFeaturesInExtent returns empty array

### ISSUE THREAD

**Issue by nandekonst** [openlayers/openlayers#16204]
After updating Open Layers to version 10.1.0 I changed 
`layer?.getSource()?.getFeaturesInExtent(extent)`

to `layer?.getFeaturesInExtent(extent)`

Before the update, it would return an array with RenderFeatures, whereas now it's returning an empty array. Below you will find the function where this is occuring for reference. Can't find out where this is going wrong. `extent` is an array filled with 4 coordinates, FE: `[257371.85875, 594546.5039843749, 257371.85875, 594546.5039843749]`

``` private static isFeatureWithinBounds(layer: BaseLayer, extent: Extent, documentIds: string[]): boolean {
    if (layer instanceof VectorTileLayer) {
      return (
        layer
          ?.getFeaturesInExtent(extent)
          ?.some(
            feature =>
              feature instanceof RenderFeature &&
              this.toGeometry(feature).intersectsExtent(extent) &&
              (documentIds.includes(feature.getProperties().identificatie) ||
                documentIds.includes(feature.getProperties().planid))
          ) ?? false
      );
    }
    return false;
  }
```
Thanks for your reaction.

**Comment by ahocevar** [comment]
This has been fixed already with #16190.

**Comment by nandekonst** [comment]
@ahocevar When will this be released?

**Comment by ahocevar** [comment]
When #16203 is reviewed and merged, otherwise we’d have a version with a severe tile layer rendering bug.
