### ISSUE TITLE
Modify in ref do not work in Vue

### ISSUE THREAD

**Issue by wrzrmzx** [openlayers/openlayers#16207]
**Describe the bug**
In my vite project, code like this:
```
const modify = ref(new Modify({
  deleteCondition: singleClick,
  source,
}))
map.addInteraction(modify.value)
```
The map can't be modified with a modify in ref, and the log:
```
Argument of type '{ on: ModifyOnSignature<EventsKey>; once: ModifyOnSignature<EventsKey>; un: ModifyOnSignature<void>; ... 27 more ...; dispose: () => void; }' is not assignable to parameter of type 'Interaction'.
  Type '{ on: ModifyOnSignature<EventsKey>; once: ModifyOnSignature<EventsKey>; un: ModifyOnSignature<void>; ... 27 more ...; dispose: () => void; }' is missing the following properties from type 'Interaction': map_, values_, applyProperties, revision_, and 9 more.
```
but when my code like this, it works:
```
const modify = new Modify({
  deleteCondition: singleClick,
  source,
})
map.addInteraction(modify)
```

**To Reproduce**
1. Here to see the bug: https://github.com/wrzrmzx/my-app2/blob/main/src/pages/index.vue#L129 
2. Here to see the original: https://github.com/wrzrmzx/my-app2/blob/caf15de9dc1624d9a8f2b0bc034bf3b19c745737/src/pages/index.vue#L129 

**Expected behavior**
```Modify``` is supposed to work in a ref

**Comment by ahocevar** [comment]
In general it is very bad practice to make any complex object reactive with a Vue `ref`. Use a `shallowRef` instead.

**Comment by wrzrmzx** [comment]
> In general it is very bad practice to make anything other than a simple value or object literal reactive with a Vue `ref`. Use a `shallowRef` instead.
> 
> The `ref()` function will create a proxy object for every property of the object passed to the `ref()` function - also traversed into nested properties. I doubt that's what you wanted.
> 
> `shallowRef()` will only create a proxy object for the value you pass to it - no traversal.

Thanks for helping!
