### ISSUE TITLE
Tile reprojection broken in v10.2.0

### ISSUE THREAD

**Issue by keepitrealsimple** [openlayers/openlayers#16218]
**Describe the bug**
Tile reprojection is broken in v10.2.0. Maybe this is tilecache issue or something. Reprojection kind of works but when zooming out the map has empty tiles.

[ol-1020-tile-reproj-bug.zip](https://github.com/user-attachments/files/17108654/ol-1020-tile-reproj-bug.zip)
![ol-1020-tile-bug-example](https://github.com/user-attachments/assets/1b4c864c-cf86-4a59-894d-f2e567748942)

**To Reproduce**
1. See attached zip project -> extract -> npm install -> npm run dev
2. Zoom in with scrollwheel and then start to zoom out (It might need few tries but for me it happens almost every time)
3. See empty tiles on map

**Expected behavior**
Reprojected tiles should work as it did with previous versions (Even on v10.1.0).

**Comment by ahocevar** [comment]
Unfortunately I cannot reproduce. @keepitrealsimple Your example is similar to https://openlayers.org/en/latest/examples/scaleline-indiana-east.html. Do you see the same problem in that example?

**Comment by ahocevar** [comment]
Actually I can reproduce with https://openlayers.org/en/latest/examples/scaleline-indiana-east.html. It is important to zoom out with the `-` button, not with scroll zooming.

**Comment by keepitrealsimple** [comment]
Yes I see the same problem in that example and I can reproduce it with just scroll wheel. I just compared chrome and firefox and it seems that it is easier to reproduce with firefox for some reason. But with both browsers I can reproduce it.

**Comment by ahocevar** [comment]
Ok, thanks for the bug report. Investigating.

**Comment by keepitrealsimple** [comment]
Did more testing and it seems that map size has something to do with it. When I have my browser maximized on my monitor (2560x1440) then I can reproduce it everytime. But when browser is smaller window then it is harder to reproduce. I also added this animate sequence at the end of my provided code to make testing easier. With that and browser maximized I can reproduce it everytime.
`setTimeout(() => {
  const view = map.getView();
  
  view.animate({ zoom: 16, duration: 1000 }, () => {
    view.animate({ zoom: 10, duration: 1000 });
  });
}, 2000);`

**Comment by ahocevar** [comment]
#16221 fixes this issue.

**Comment by keepitrealsimple** [comment]
Nice. Thank you!

**Comment by cristianmadularu** [comment]
Any plans to merge and release it soon? We are experiencing the same issue. Thank you!

**Comment by ahocevar** [comment]
When the pull request gets a review, I'll merge and publish immediately.

**Comment by cristianmadularu** [comment]
Thank you :)
