### ISSUE TITLE
API to retrieve decluttered features from the viewport

### ISSUE THREAD

**Issue by potion-cellar** [openlayers/openlayers#16247]
Hello,

I'm interested in potentially contributing this functionality to openlayers, or finding the best approach to doing this and perhaps tweaking the documentation / adding an example. I would love to hear your thoughts on the matter.

## Background / Use Case
We have a use case where we need to get an array of features from our vector tile layers after they have been decluttered. This is so that we can show some additional data below point labels that end up getting rendered (in our particular use case, weather data for cities, peaks, POI, etc).

As far as we're aware, openlayers does not provide an official api for doing this, beyond a pixel-per-pixel basis. We can get ALL of the features from the `VectorTileLayer` easily (`getFeaturesInExtent()`), but have no standardized or efficient way of determining which of those features are actually being displayed.

Technically, one could use a single call to `map.getFeaturesAtPixel()` for the center of the viewport with a huge `hitTolerance` to get the final array of features that have been rendered after decluttering, but in practice this is extremely slow and nonviable. There is also the opposite -- iterating over everything from `getFeaturesInExtent()` while calling `map.getFeaturesAtPixel()` for each pixel relevant to a point feature, but that is of course also prohibitively slow for many use cases considering the thousands of features typical for vector tiles.

## What we're currently doing
We do have an unsupported and rather suboptimal way of doing this, at least from a DX perspective. From the end user's perspective though this methodology is performant and has served us well in production for several years:

1. Add an event listener to the map -- we're using `postrender` in this case
2. Get the declutter trees from the `frameState` of the `MapEvent` (the documentation suggests we don't do this)
3. Use the standard `RBush` functions (`all()` or `search()`) to get a flat array of all the features in the declutter tree
4. Dedupe and filter the array based on our needs

This seems to reliably give us a list of all the features in the viewport that are actually being displayed.

## Discussion
With the steps above in mind, is there a technical or specific reason why there is no standardized way of doing this in the library or why the documentation dissuades against looking at this part of the `frameState`? If not, this would be a nice feature to have and I'm certainly happy to contribute something.

I haven't dug into the code too much so I'm not sure what the level of effort here is. To me, a nice and simple DX that would probably take care of a bunch of people's use cases, using data that I already know is available in the latest `frameState`,  would be a method like

```typescript
function getDeclutteredFeatures (
    pixelExtent: Extent, 
    opts?: {
        declutterValue?: string | true
        layerFilter?: (layerCandidate: Layer) => boolean
    }
): Array<FeatureLike>
```

Maybe this would live on the `Map` class, or maybe the `FrameState`, maybe just as a glorified abstraction of the the last state of `frameState.declutter` RBush methods for the desired declutterValue...This does seem like a pretty inflexible and specific method, I'm sure there may be a more acceptable implementation in mind.

Would love to hear any thoughts on the matter -- maybe there is a way to do this already that we've completely overlooked -- but if not it feels like it might be worth adding at least *something* standardized even if it is just being able to get the decluttered features in the current viewport.

Or maybe, what we're currently doing with `frameState.declutter` is acceptable and the documentation could be adjusted to reflect that (or even adding an example of it)... (the Typescript types are also wrong for this object, btw, that could be addressed too).

**Comment by ahocevar** [comment]
What you're doing is correct, given your data and the current library code. The reason why we don't add this to the official and supported API is because it is an internal thing, has been changed frequently, and makes assumptions about the structure of the data (i.e. deduping by feature id).

That said, if you need the decluttered features, continue doing what you're doing, but do so at your own risk, as it may stop working in future versions.

To make it easier for yourself and potential other users who might be interested in doing the same at their own risk, it would be great if you could submit a pull request with only the TypeScript type fixes you mentioned.

Another way of doing this would be to take control of the whole decluttering process yourself, e.g. using the [labelgun](https://www.npmjs.com/package/labelgun) package within a style function or in a prerender hook.

**Comment by potion-cellar** [comment]
Thanks @ahocevar . The documentation was pretty clear in that we are expecting this way of doing things to break at any time!

Pulled the source down to see if I could submit PR for a resolution to the issue I was having types.

The problem is that `frameState.declutter` returns `RBush<DeclutterEntry>`, with `RBush` being the default export from the `rbush` package.

However, if one wants to reference that type ahead of time, openlayers only makes available a default export from `ol/structs/RBush` which is a wrapper that provides a very different set of functions. Thus I can't see any way of statically typing the correct reference to `RBush`.

I'm not really sure what a good resolution for this, as generally throughout the library, `RBush` refers to the wrapper and not the library. In `ol/structs/RBush`, I could re-export `RBush_` as a named export (`export {RBush_ as RBush}`) but seems like that is a potential cause for headaches.

**Comment by ahocevar** [comment]
Well, from what you describe I don't think the type is wrong. In this [typescript playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwLIEMwF84DMoRHAcggBsCBuAKAoGMIA7AZ3hDTgF446BTAdzlTAAKAJSUKLMADp6ggpCZQudACZcoBADRwuANyXw2APkQU4cYFjiCAhLv2ScKEFwDKMFDC4B+SaurEAVxhPKGETMzNFGACoOkozdFM4WkZ4KAAjAIYACwBBKCgUAE92OAB5dIArLmoYSR0UQK4GQTs6OsdnNw8uXxrA4LVRJIysvILih2gAURRqbMFRnPzCooBJT3wjcIiUpjhG4lKl8dWNrhBJQ5F4iMOpqFn5xcyc6faoEu2EJIjk+gYJF6xAgAHMXmN3jBPsM-uhhEl4ZQkUA), the `all()` method of `rbush` is used and correctly recognized by TypeScript - the `ol/structs/RBush` wrapper does not have an `all()` method.

**Comment by potion-cellar** [comment]
@ahocevar Yes, that is correct. No issue there. The problem arises when you need the type ahead of time, for instance in a function that would take an `RBush`:

```
const getPointsFromRBush = (rbush: RBush<DeclutterTree>) => {
    ...
}
```

There is no way to properly type the `RBush` above unless you are aware it is accessible as a `peerDependency`. Otherwise the only suggest is the default export from `ol/structs/RBush` which is incorrect.

**Comment by ahocevar** [comment]
@potion-cellar All you need to do is

    npm install rbush @types/rbush

and in your code
```js
import RBush from 'rbush';
import { DeclutterEntry } from 'ol/render/canvas/Executor'

const getPointsFromRBush = (rbush: RBush<DeclutterEntry>) => {
    ...
}
```

**Comment by potion-cellar** [comment]
@ahocevar Yep, that's what we've been doing. In fact we don't even need to install the libraries as installing `ol` results in `rbush` types being accessible from `node_modules` anyways (though you have to know to import the library).

The "needing to know to install and/or import a type from a separate library" was just some development friction that we encountered and that's what I wanted to potentially take a look at if there was a clean fix. Just uncommon and a little unintuitive. But again, knowing we're doing something fairly unsupported :)

Sorry about all the back and forth and appreciate the discussion.

**Comment by ahocevar** [comment]
Sure, no worries! Just wondering what exactly you encoutnered. Because in an empty file, as soon as I type
```js
import RBush from 'rbush'
```
I get a hint in VS Code when hovering over 'rbush' that I should try to install `@types/rbush`.

**Comment by potion-cellar** [comment]
@ahocevar It's writing that import out in the first place that is unintuitive if you didn't know that openlayers was consuming that library. Easy enough once you realize that, but we didn't know to import from that library until I actually took a look at the openlayers source code.

**Comment by ahocevar** [comment]
Alright, @potion-cellar - well I guess you had to look into the source code anyway to figure out the procedure you crafted 👍

**Comment by potion-cellar** [comment]
Fair enough haha. I'll close this since it seems like overall there's not much useful that can be contributed at this time.
