### ISSUE TITLE
Handle object in OGC Tile TileMatrixSet crs

### ISSUE THREAD

**Issue by kudlav** [openlayers/openlayers#16287]
**Describe the bug**

CRS property defined by OGC API - Tiles schema can be a `string` and also an `Object`:
1. `"crs": "http://www.opengis.net/def/crs/EPSG/0/5514"`
2. `"crs": { "uri": "http://www.opengis.net/def/crs/EPSG/0/5514" }`
3. `"crs": { "wkt": {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json","type": "ProjectedCRS",...} }`
4.  `"crs": { "referenceSystem": {"MD_ReferenceSystem":{"referenceSystemIdentifier":{"RS_Identifier": ...} }`

https://github.com/opengeospatial/ogcapi-tiles/blob/1.0.0/openapi/schemas/common-geodata/crs.yaml

The source projection is obtained from TileMatrixSet CRS here:
https://github.com/openlayers/openlayers/blob/26f7490e22e71710db69e729c914c939517b3d07/src/ol/source/ogcTileUtil.js#L252

It expects that `tileMatrixSet.crs` is always a `string`:
https://github.com/openlayers/openlayers/blob/26f7490e22e71710db69e729c914c939517b3d07/src/ol/source/ogcTileUtil.js#L51

But it can be an `Object` as well. Later in the code, the crs object is incorrectly handled as a `Projection`:
https://github.com/openlayers/openlayers/blob/26f7490e22e71710db69e729c914c939517b3d07/src/ol/proj.js#L169-L182

**To Reproduce**
1. Use OGC Map Tiles example https://openlayers.org/en/latest/examples/ogc-map-tiles.html
2. Load the following documents: [tiles.json](https://gist.githubusercontent.com/kudlav/965e71731e75ae6e53c4f42055e607ca/raw/ced0b18dc0787d20e7bff8c126252f64c894d12e/tiles.json) and [tileMatrixSet.json](https://gist.githubusercontent.com/kudlav/965e71731e75ae6e53c4f42055e607ca/raw/ced0b18dc0787d20e7bff8c126252f64c894d12e/tileMatrixSet.json)
3. Map is loaded without any warning but it's in Mercator instead of `EPSG:5514`.

**Expected behavior**

1. `"crs": "http://www.opengis.net/def/crs/EPSG/0/5514"` is handled correctly
2. `"crs": { "uri": "http://www.opengis.net/def/crs/EPSG/0/5514" }` should be handled the same as 1. and try to load it using the `crs.uri` string
3. `"crs": { "wkt": {"$schema": "https://proj.org/schemas/v0.7/projjson.schema.json","type": "ProjectedCRS",...} }` should throw Unsupported CRS
5. `"crs": { "referenceSystem": {"MD_ReferenceSystem":{"referenceSystemIdentifier":{"RS_Identifier": ...} }` should throw Unsupported CRS

Variants 3 and 4 cannot be easily converted to proj4 definition so it should at least throw an Unsupported CRS error.

Here is  a possible patch:
https://github.com/openlayers/openlayers/compare/main...kudlav:openlayers:kudlav-ogcapi-crs

**Comment by tschaub** [comment]
Thanks for the solid report @kudlav.

I put together #16291 with a fix before seeing your [proposed fix](https://github.com/openlayers/openlayers/compare/main...kudlav:openlayers:kudlav-ogcapi-crs). Our code changes were identical, so that is nice. I like the explicit types you added, so I'll grab those.

**Comment by tschaub** [comment]
I added an edited version of your commit to #16291.
