### ISSUE TITLE
Firing of tile loading events for GeoTIFF source depends on layer's visibility

### ISSUE THREAD

**Issue by christophfriedrich** [openlayers/openlayers#16298]
**Describe the bug**
When a layer is not visible, its GeoTIFF source gets loaded anyway, but the corresponding `tileloadstart` and `tileloadend` events are not firing.

**To Reproduce**
1. Clone the `cog` example: https://openlayers.org/en/latest/examples/cog.html
2. In that code, add `source.once('tileloadend', () => alert('done!'))` below the definition of `source`
3. Run `npm start` and open the page in the browser
4. See the alert as expected
5. Open the Network tab in your browser's dev tools
6. Back in the code, add `visible: false` to the options in `new TileLayer(...)` and save the file
7. Vite will reload the page
8. See that the request to the source is showing up in the dev tools, but no alert is being displayed
9. Go back to step 2 and replace `tileloadend` with `tileloadstart` to confirm for the other event

**Expected behavior**
Loading events fire when something gets loaded, regardless of any other conditions.
(I would understand it if the source wouldn't get loaded at all when it's not visible anyway, but since it _is_ being loaded, logically the events should fire too.)

**Other remarks**
I added "for GeoTIFF source" to the title as I didn't investigate whether this also happens for other sources. Also, I would assume that the same bug would happen for the `tileloaderror` event, but didn't know how to provoke it.

**Comment by mike-000** [comment]
That is equivalent to defining a TileJSON (or Bing) source and not using it in either a layer or map.  The JSON will be read immediately to obtain the source definitions it contains (tile grid, tile urls, etc.).  GeoTIFF uses a partial content request https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range to obtain similar information held in the file which is required before any tiles can be loaded.  In the example no tiles will be loaded (also using range requests) until `source.getView()` resolves.

**Comment by mike-000** [comment]
The `tileloadstart` and `tileloadend` events will fire when a tile object is created and its loader is called.  As in https://openlayers.org/en/latest/examples/data-tiles.html no network requests may be needed.
