### ISSUE TITLE
Examples using https://ahocevar.com/geoserver are not working

### ISSUE THREAD

**Issue by iamvdo** [openlayers/openlayers#16303]
**Describe the bug**
https://ahocevar.com/geoserver is returning 404 errors for several days.
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ahocevar.com/geoserver/gwc/service/tms/1.0.0/ne:ne_10m_admin_0_countries@EPSG%3A900913@pbf/1/0/0.pbf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.
```
cc @ahocevar 
Thanks!

**Comment by ahocevar** [comment]
That server is often under heavy load due to folks finding it necessary to scrape it for widely available Natural Earth tiles with standard styles. It will come back up eventually.
