### ISSUE TITLE
Image layer with static source unexpected clipping

### ISSUE THREAD

**Issue by Grumgog** [openlayers/openlayers#16334]
**Describe the bug**
Image layer with static as source was clipping unexpected when view change with default mouse interaction (pan map, zooming).
![изображение](https://github.com/user-attachments/assets/a640adfe-fd6e-47e9-8f17-5bd89143b984)

**To Reproduce**
example project with reproduction:
Github: https://github.com/Grumgog/ol_bug_clipping
StackBlitz: https://stackblitz.com/~/github.com/Grumgog/ol_bug_clipping
**Expected behavior**
Image layer display without any clipping across entire map and independent from view configuration.

I try interact with image layer through polygon feature, for edit position of layer, but layer clip a image unpredictable.

**Comment by mike-000** [comment]
I think it is doing unnecessary reprojections.  If the image extent is in the view projection the image projection should be the same projection.

**Comment by Grumgog** [comment]
Thanks for answering.

Yes, indeed reason was mismatch of projections. I solved problem with replacing custom projection of image source with map view projection. [Example ](https://openlayers.org/en/latest/examples/static-image.html) of using static image misleaded me. In my case I expected distortion of image from mismatch projection or completely no display image.
