### ISSUE TITLE
Openlayers7 load mvt,style is error

### ISSUE THREAD

**Issue by hongjiansong** [openlayers/openlayers#16343]
I use openlayers 7 API load vector layer,but found the style and data is error when I zoom in or out the map; I don't know why
![1](https://github.com/user-attachments/assets/07c489b1-fbf9-4913-8f0b-a6e6a410f43b)

**Comment by ahocevar** [comment]
Looks like winding order issues in your tiles. But before changing tiles, try with the latest version of OpenLayers.

**Comment by hongjiansong** [comment]
thanks for your answer, I check the data of tiles is ok. 
I forget that, the many polygons are overlapped, I don't konw does it affect the tiles.

**Comment by ahocevar** [comment]
Overlapping polygons are not a problem. Did you try with the latest version of OpenLayers? How did you validate the tiles?

**Comment by hongjiansong** [comment]
Year, I try it using the version 10.2.1 of OpenLayers, bug no works.
But I found there many multipolygons type in this vector data, and I change the type to polygon, the tiles looks ok. Only a little tiles's style is error, it's interesting
![1st](https://github.com/user-attachments/assets/29cdb3f6-8903-40f1-a80e-5bf0e865606c)
![2nd](https://github.com/user-attachments/assets/42a297fe-8403-4cd2-b6bf-e3fdbf2c1e96)
![3rd](https://github.com/user-attachments/assets/9385eb7f-523a-4278-b7d3-4bce19793a9f)
![4th](https://github.com/user-attachments/assets/93712d07-d477-41b8-803c-ebd75326950c)

**Comment by ahocevar** [comment]
Please share one of the faulty tiles, and the original data for that tile. What do you use to encode the tiles?

**Comment by hongjiansong** [comment]
Sorry，Long time no response;
I try to generate mvt by java code and postgresql database, It works well.
I guess  QGIS  generate mvt maybe has some problem.
Thanks for anyway.
