### ISSUE TITLE
VectorImage type declaration errors

### ISSUE THREAD

**Issue by bad-ch** [openlayers/openlayers#16347]
Stack:
- OL v10.2.1 
- Typescript v5.3.3 

After the update from OL 8.2 to 10.2.1, I get the error **"Type 'VectorSource<Feature>' is missing the following properties from type 'Feature': id_, geometryName_, style_, styleFunction_, and 13 more.ts(2344)"** for a VectorImageLayer.

In my opinion I have the same effects like in the issue #15897

**Comment by ahocevar** [comment]
In which context do you get that error? Can you share the code that triggers it?

**Comment by bad-ch** [comment]
![image](https://github.com/user-attachments/assets/ecc4aed6-d9ab-41d8-97ee-4a56cef45cce)

**Comment by bad-ch** [comment]
![image](https://github.com/user-attachments/assets/17ae857a-f9f9-4263-9d2c-9a818ca8b558)

**Comment by ahocevar** [comment]
Thanks for the details, will be fixed with #16348.
