### ISSUE TITLE
OL 10.2.1: Getting error "ImageTile getImage() returns null" after which no new tiles are loaded 

### ISSUE THREAD

**Issue by topie9** [openlayers/openlayers#16364]
**Describe the bug**
Happens in OL v10.2.1 and does not happen in v9.2.4.

When moving and zooming the map I'm getting error message in browser console that ImageTile getImage() returns null. When getting the error, new tiles won't be loaded anymore. Happens at least with WMTS source, but can also be reproduced with OSM source. 

Frequency and effects of the issue seem to depend on the browser and layer source. With Chrome (v130.0.6723.117) and Safari (v18.0 (19619.1.26.111.10, 19619)) the issue happens every time in WMTS Tile Transitions example. With Firefox (v132.0.2) the issue is more difficult to reproduce.

Depending on map layer configuration and browser the effects can be:
- only error message in browser console
- new tiles won't be loaded
- map goes fully white and is unresponsive
  

**To Reproduce**
1. Go to WMTS Tile Transitions example: https://openlayers.org/en/latest/examples/wmts-dimensions.html
2. Move Sea-level slider value back and forth. 

<img width="1511" alt="ol-v10-issue-img1" src="https://github.com/user-attachments/assets/5640c9b9-3df4-4ee6-9c84-023a1429c836">

After getting error in the console. Sea-level slider does nothing and map only displays tiles which have been loaded already.

<img width="1494" alt="ol-v10-issue-img2" src="https://github.com/user-attachments/assets/84bee0e4-3cba-4dcc-9825-38617e204d0c">

Issue is also reproducible in example https://openlayers.org/en/latest/examples/full-screen-source.html when zooming the map in and out repeatedly in full screen mode.

**Comment by ahocevar** [comment]
Unfortunately I am absolutely unable to reproduce this. Could it be that you're using a browser plugin that manipulates the DOM, e.g. an ad blocker?
