### ISSUE TITLE
ol.source.changed can not update data correctly

### ISSUE THREAD

**Issue by tmKnight01** [openlayers/openlayers#16366]
**Describe the bug**
I am using vue3 ol. When the _features data is updated, the layer cannot be rendered normally, but init can load the data correctly in the layer.

**To Reproduce**
`watch(
  markerLayers,
  (_layers) => {
    if (Object.keys(_layers).length > 0) {
     
      Object.keys(_layers).forEach((_m) => {
        const layer = _layers[_m];
        if (layer && layer.source) {
        
          const _lots = propItemsVal.value.filter((_f) => _f.type === _m);
          console.log("_lots", _lots);

          if (_lots.length > 0) {
            const _features = prepareMarkers(_lots[0]);
            console.log("_features", _features);
          
            layer.source.clear(true);
            layer.source.addFeatures(_features);
    
            layer.source.changed()
          } else {
            console.warn(`No items found for type: ${_m}`);
          }
        } else {
          console.warn(`Layer or layer source not found for type: ${_m}`);
        }
      });
    }
  },{ deep: true });`

That is to say, when init page is called, layer.source is updated normally, but when the layer data changes, it cannot be updated normally. Please help me, thank you very much

**Expected behavior**
Normal rendering after layer data is updated

**Comment by ahocevar** [comment]
As a rule of thumb, never make anything from OpenLayers reactive in Vue. As for this issue, it will be hard to answer your question without knowing what `markerLayers` is, except for "don't do it!".

**Comment by tmKnight01** [comment]
thank you for reply,  markerLayers is a collection of ol-source-vector references related to the layer type




      <div v-if="propItemsVal.length > 0">
        <template v-for="(_k, _i) in propItemsVal" :key="_i">
          <ol-animated-clusterlayer
            :animationDuration="500"
            :distance="mapRef.value?.map.getView().getZoom() >= 13 ? 0 : 40"
            :styles="LotsLayerData.vectorStyle.pending"
            :title="_k.type"
            :zIndex="40"
            :visible="true"
          >
            <ol-source-vector
              :ref="
                (el) => {
                  if (el) {
                    nextTick(() => {
                      markerLayers[_k.type] = el;
                    });
                  }
                }
              "
              :projection="mapState.name"
            />
            <ol-style :overrideStyleFunction="overrideStyleFunction"></ol-style>
          </ol-animated-clusterlayer>
        </template>
      </div>





and  i find if change   `  markerLayers[_k.type] = el;` to  ` markerLayers[_k.type] = { ...el };`, after shallow copying and assigning, the layer data can be updated normally, but this will cause infinite rendering due to watch(markerLayers)...
<img width="1882" alt="000ab7a426e17bdf865a5b6b6dc2f2c" src="https://github.com/user-attachments/assets/e9c15bbb-8610-42ad-92d8-3e325ce08a9a">

**Comment by tmKnight01** [comment]
> 根据经验，永远不要在 Vue 中将 OpenLayers 中的任何内容变为响应式。至于这个问题，如果你不知道是什么`markerLayers`，就很难回答你的问题，只能说“别这么做！”。

ok I will tried to change the layer collection to a non-responsive way to update

**Comment by tmKnight01** [comment]
> As a rule of thumb, never make anything from OpenLayers reactive in Vue. As for this issue, it will be hard to answer your question without knowing what `markerLayers` is, except for "don't do it!".

ok I will tried to change the layer collection to a non-responsive way to update

**Comment by tmKnight01** [comment]
> > As a rule of thumb, never make anything from OpenLayers reactive in Vue. As for this issue, it will be hard to answer your question without knowing what `markerLayers` is, except for "don't do it!".
> 
> ok I will tried to change the layer collection to a non-responsive way to update

Its work!!   i use no-reactive makerlayers, and then update it by manually,the layer data  was update and switch normally.
thanks!
