### ISSUE TITLE
Incorrect drawing order of multiple styles

### ISSUE THREAD

**Issue by levelost** [openlayers/openlayers#16373]
See https://github.com/openlayers/ol-mapbox-style/discussions/1216

The third style is drawn second. Full code in the sandbox:
https://codesandbox.io/p/sandbox/heuristic-tdd-ymsvrf

![scr](https://github.com/user-attachments/assets/7126ea93-c880-4283-9e68-d089ebe45eb6)

**Comment by ahocevar** [comment]
Thanks for the bug report. Can you please provide an example that uses OpenLayers styles directly, without ol-mapbox-style?

**Comment by levelost** [comment]
VectorTileLayer and StyleFunction too:
https://codesandbox.io/p/sandbox/ol-styles-forked-n2sycq?workspaceId=4c85bd12-2428-448e-8638-7ecd9fd42a9f

But a regular StyleFunction has a slightly different drawing order in principle.

**Comment by levelost** [comment]
There is a suggestion. The problem is in ZIndex. Without it, the order of styles is predictable:
https://codesandbox.io/p/sandbox/ol-styles-function-forked-57rksy

![scr](https://github.com/user-attachments/assets/989d974c-88ca-4a58-a9cc-275b2c923446)

**Comment by ahocevar** [comment]
The above example (with zIndex) looks correct too. Or am I missing something?

I think the problem might be decluttering - when the layer is configured with `declutter: true` and the circle styles with `declutterMode: 'none'` (this is what ol-mapbox-style does). Is that the case?

**Comment by levelost** [comment]
I changed the example for clarity. The second style overlaps the third.
![scr](https://github.com/user-attachments/assets/3006cc8a-eac3-4cdf-b665-81d7a383fe96)

**Comment by ahocevar** [comment]
Thanks, @levelost. This should help to investigate the issue further.

**Comment by ahocevar** [comment]
Good find, @levelost! Would you be able to create a pull request?
