### ISSUE TITLE
Does the webGL draw a face and support the loading of the face border line on the mobile end?

### ISSUE THREAD

**Issue by xuhao-xiaofei** [openlayers/openlayers#16381]
Use webGL to draw a face. The border needs to be loaded on the face. The edge line on the PC can be loaded normally, but the edge line of the face cannot be loaded on the mobile end. Tripartite parts: ol-9.2.4 latest version.
Excuse me: Is it not supported by mobile devices or other reasons?

**Comment by jahow** [comment]
It should work; please provide at least a screenshot and ideally a live reproduction case, thanks! Also, have you tried with the latest version of OpenLayers?

**Comment by xuhao-xiaofei** [comment]
> 它应该可以工作；请至少提供一张截图，最好是现场再现的案例，谢谢！另外，您是否尝试过最新版本的 OpenLayers？
现在最新版的不是9.2.4吗？使用ol-9.2.4的版本

**Comment by jahow** [comment]
Hi, it would be super helpful if you could write in English, thanks a lot :slightly_smiling_face:

**Comment by xuhao-xiaofei** [comment]
Excuse me, isn't the latest version of 9.2.4? Version ol-9.2.4 used

**Comment by xuhao-xiaofei** [comment]
I didn't find how to upload the picture normally, only through this project please see.

**Comment by xuhao-xiaofei** [comment]
> no, 10.2.1 is the latest! also you can try using `npm install ol@dev` to use the latest commits on the main branch.

https://github.com/xuhao-xiaofei/xiaofei_project.git

This is my project. The photo is placed in it. The border line is still not displayed on the phone, but the polygon frame on the web has a red wire frame.I didn't find how to upload the picture normally, only through this project please see.

**Comment by jahow** [comment]
You can simply copy paste an image into the comment you're writing to upload it to github.

It sounds like the WebGL renderer might have an issue in your case, but without a reproduction case to investigate (e.g. with https://codesandbox.io/) I'm afraid it'll be difficult to help you.

**Comment by xuhao-xiaofei** [comment]
[https://github.com/xuhao-xiaofei/xiaofei_project/blob/main/photo.jpg](url)
This picture link, you have a look.

**Comment by xuhao-xiaofei** [comment]
> You can simply copy paste an image into the comment you're writing to upload it to github.
> 
Hello, do you have a plan?

**Comment by jahow** [comment]
Like I said, without a proper way to investigate the issue (which is likely a bug), there's no way for me or anyone to assist you further. Also, please do not open duplicate issues, thank you!

**Comment by xuhao-xiaofei** [comment]
I'm very sorry. For reasons on my side, I can't provide you with a complete picture. I can only give you a rough hand-drawn description of the situation. The first picture is a normal picture displayed on the PC end. I use a black wireframe on the outer frame. The second picture is displayed on the mobile end. The black wire frame cannot be displayed on the mobile end. Is my question caused by the failure of the mobile device to adapt to the PC, or is this not supported on the mobile device? Here's a link to the picture. Thank you!

**Comment by xuhao-xiaofei** [comment]
I'm very sorry. For reasons on my side, I can't provide you with a complete picture. I can only give you a rough hand-drawn description of the situation. The first picture is a normal picture displayed on the PC end. I use a black wireframe on the outer frame. The second picture is displayed on the mobile end. The black wire frame cannot be displayed on the mobile end. Is my question caused by the failure of the mobile device to adapt to the PC, or is this not supported on the mobile device? Here's a link to the picture. Thank you!
https://github.com/xuhao-xiaofei/project/blob/main/3434.png

**Comment by xuhao-xiaofei** [comment]
> 就像我说的，如果没有合适的方法来调查问题（很可能是 bug），我或任何人都无法进一步帮助您。另外，请不要打开重复的问题，谢谢！

I'm very sorry. For reasons on my side, I can't provide you with a complete picture. I can only give you a rough hand-drawn description of the situation. The first picture is a normal picture displayed on the PC end. I use a black wireframe on the outer frame. The second picture is displayed on the mobile end. The black wire frame cannot be displayed on the mobile end. Is my question caused by the failure of the mobile device to adapt to the PC, or is this not supported on the mobile device? Here's a link to the picture. Thank you!

https://github.com/xuhao-xiaofei/project/blob/main/3434.png
