### ISSUE TITLE
Error in postRenderFunction of CanvasTileLayerRenderer

### ISSUE THREAD

**Issue by M393** [openlayers/openlayers#16413]
**Describe the bug**
FrameState in postRenderFunction may be null,
https://github.com/openlayers/openlayers/blob/a70874dcfec390bf61a8b25bd202e135d5322338/src/ol/Map.js#L74-L76
but the function in CanvasTileLayerRenderer does not handle null values.
https://github.com/openlayers/openlayers/blob/a70874dcfec390bf61a8b25bd202e135d5322338/src/ol/renderer/canvas/TileLayer.js#L855-L859

**To Reproduce**
This was reported to me by an error reporter script, so not sure how to reproduce.

**Expected behavior**
No error should occur.

**Comment by ahocevar** [comment]
`postrender` functions will only be called when there is a framestate (see https://github.com/openlayers/openlayers/blob/154a3f96e20c4d27f8ec0319c8dd1139b29615ee/src/ol/Map.js#L1231-L1238), so it's probably only a an issue with the type.

**Comment by M393** [comment]
Thanks for pointing this out. 
This has been fixed by #16268, but is not yet released.
