### ISSUE TITLE
Error in OpenLayer after Upgrading Angular from 14 to 15

### ISSUE THREAD

**Issue by mani-mworks** [openlayers/openlayers#16414]
After upgrading from Angular 14 to Angular 15, I'm encountering an error related to OpenLayer's `ol.css` during `npm start` or `npm build`.

**Error Details:**

```shell
./node_modules/ol/ol.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> :root,
| :host {
|   --ol-background-color: white;
```

**Steps to Reproduce:**

1. Upgraded Angular version from 14 to 15.
2. Installed project dependencies with `npm install`.
3. Ran `npm start` or `npm build`.

**Expected Behavior:**  
The application should build or start without issues.

**Actual Behavior:**  
Build fails with the above error related to `ol.css`.

**Environment Details:**

- **Angular Version:** 15
- **OpenLayer Version:** 7.5.2
- **Node Version:** 14.21.3
- **npm Version:** 6.14.18 
- 
**Troubleshooting Steps Taken:**

1. Checked the Webpack configuration to verify CSS loaders.
2. Searched for similar issues and potential solutions online.
3. Attempted adding missing CSS loaders, but the error persists.

**Request for Support:**  
Looking for guidance on how to resolve this issue, including:

- Correct configuration for handling `ol.css` in Angular 15.
- Any recommended changes to Webpack or Angular settings.

**Comment by M393** [comment]
Does https://github.com/webpack/webpack/releases/tag/v5.97.0 fix this for you?
>Bug Fixes
> [CSS] Parsing strings on Windows
