### ISSUE TITLE
removeSourceTiles of VectorTileSource is not cleaning up correctly

### ISSUE THREAD

**Issue by MoonE** [openlayers/openlayers#16423]
A different key is used when adding tiles than when removing tiles `this.getKey()` vs `tile.getKey()`, it has to be the same.
https://github.com/openlayers/openlayers/blob/4b86823e5739d3b30f62e2102900d7df22646a3f/src/ol/source/VectorTile.js#L229

https://github.com/openlayers/openlayers/blob/4b86823e5739d3b30f62e2102900d7df22646a3f/src/ol/source/VectorTile.js#L290-L300

Line 296 has to be 
```js
const index = this.tileKeysBySourceTileUrl_[sourceTileUrl].indexOf(tileKey); 
```

Currently `index` is always `undefined` and `.splice(undefined, 1)` will always remove the first element, which works  as long as there is only one element in the array.

**Comment by MoonE** [comment]
@ahocevar I'm not sure which would be the correct key. Is it `this.getKey()`?

**Comment by ahocevar** [comment]
@MoonE Yes, `this.getKey()` is the correct key. The bug is exactly what you said - trying to use the key instead of its index as array index.

**Comment by ahocevar** [comment]
`tile.getKey()` is the correct key, not `this.getKey()`:
```diff
diff --git a/src/ol/source/VectorTile.js b/src/ol/source/VectorTile.js
index 3ac7769dd3..daed45547c 100644
--- a/src/ol/source/VectorTile.js
+++ b/src/ol/source/VectorTile.js
@@ -289,11 +289,12 @@ class VectorTile extends UrlTile {
     const sourceTiles = tile.sourceTiles;
     for (let i = 0, ii = sourceTiles.length; i < ii; ++i) {
       const sourceTileUrl = sourceTiles[i].getTileUrl();
-      const tileKey = this.getKey();
+      const tileKey = tile.getKey();
       if (!this.tileKeysBySourceTileUrl_[sourceTileUrl]) {
         return;
       }
-      const index = this.tileKeysBySourceTileUrl_[sourceTileUrl][tileKey];
+      const index =
+        this.tileKeysBySourceTileUrl_[sourceTileUrl].indexOf(tileKey);
       if (index === -1) {
         continue;
       }
```
