### ISSUE TITLE
"ReferenceError: Worker is not defined" build error on upgrading from 10.2.1 to 10.3.0 and/or 10.3.1 

### ISSUE THREAD

**Issue by mprins** [openlayers/openlayers#16436]
**Describe the bug**
After upgrading our project from 10.2.1 to 10.3.0 and 10.3.1 our test suite fails with the message "ReferenceError: Worker is not defined".
Typical stacktrace points to `webgl.js`:

```
  ● Test suite failed to run

    ReferenceError: Worker is not defined

      1 | import { Map as OlMap } from 'ol';
    > 2 | import { Layer as BaseLayer, Vector as VectorLayer, Group as LayerGroup } from 'ol/layer';
        | ^
      3 | import { Vector as VectorSource, ImageWMS, WMTS, XYZ, TileWMS } from 'ol/source';
      4 | import { LayerManagerModel, LayerTypes } from '../models';
      5 | import { OlLayerHelper } from '../helpers/ol-layer.helper';

      at create (../../node_modules/ol/worker/webgl.js:4:11)
      at Object.<anonymous> (../../node_modules/ol/render/webgl/VectorStyleRenderer.js:23:39)
      at Object.<anonymous> (../../node_modules/ol/renderer/webgl/VectorLayer.js:7:1)
      at Object.<anonymous> (../../node_modules/ol/layer/WebGLVector.js:5:1)
      at Object.<anonymous> (../../node_modules/ol/layer.js:16:1)
      at Object.<anonymous> (src/lib/openlayers-map/open-layers-layer-manager.ts:2:1)
      at Object.<anonymous> (src/lib/openlayers-map/openlayers-map.ts:10:1)
      at Object.<anonymous> (src/lib/map-service/map.service.ts:2:1)
      at Object.<anonymous> (src/lib/map/map.component.ts:2:1)
      at Object.<anonymous> (src/lib/map/map.component.spec.ts:1:1)
```
see eg. https://github.com/Tailormap/tailormap-viewer/actions/runs/12179604586/job/33972116224?pr=772

Note that we don't actually use webgl

**To Reproduce**
1. Go to '[Tailormap/tailormap-viewer](https://github.com/Tailormap/tailormap-viewer)'
2. Check out and run `npm i ol`
3. run tests `npm test`

**Expected behaviour**
At least some indication in the upgrade notes or just a painless upgrade

**Comment by mprins** [comment]
this seems a different issue than https://github.com/openlayers/openlayers/issues/16271

**Comment by jahow** [comment]
I suspect that because the `ol.layer` module now also includes `WebGLVector`, which in turns uses the `VectorStyleRenderer` class. Importing this class causes a worker to be created, which leads to the error you're having.

As for why the test suites are failing: I think it is because the Jest configuration you are using does not support the Worker API. Jest runs on Node which does not have the `Worker` global API set up like in browsers, Using an environment like [JSDom](https://www.npmjs.com/package/jest-environment-jsdom) might help, or you can simply define a `Worker` stub like suggested here: https://github.com/jestjs/jest/issues/3449

Alternatively, by doing more focused imports of the OL classes you will also avoid pulling unused features like the WebGL renderers. For instance do this:
```js
import BaseLayer from 'ol/layer/Layer';
import VectorLayer from 'ol/layer/Vector';
import LayerGroup from 'ol/layer/Group';
```

Instead of this:
```js
import { Layer as BaseLayer, Vector as VectorLayer, Group as LayerGroup } from 'ol/layer';
```

Hope that helps!

**Comment by bjornharrtell** [comment]
I'm not having luck polyfilling Worker, stuck on URL.createObjectURL issues (looks like polyfills doesn't support blob urls).

**Comment by mprins** [comment]
I have:
- added `jsdom-worker` as a dev dependency
- added `setupFiles: ['jsdom-worker'],` in the projects base jest config: https://github.com/Tailormap/tailormap-viewer/pull/772/commits/7ca13908d3488c1e7623b6bd5dbe027b79cd1baf

**Comment by bjornharrtell** [comment]
@mprins much appreciated! Appears to work in vite/vitest projects too.

**Comment by wolfcreative** [comment]
Faced the same problem in next.js. I had to rollback to an older version of ol

**Comment by jahow** [comment]
@wolfcreative couldn't you apply one of the solutions presented in that thread? please let us know if none of them worked out.

**Comment by wolfcreative** [comment]
@jahow your solution with the 'ol/layer' option definitely didn't work:
`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

The solution using 'jsdom-worker' is difficult in next.js (I'm trying to make changes to next.config.js). My first attempt did not solve the problem. I'll try again later.

**Comment by wolfcreative** [comment]
@jahow ~~your solution with the 'ol/layer' option definitely didn't work:
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.~~ It works, but only with the --turbo flag

The solution using 'jsdom-worker' is difficult in next.js (I'm trying to make changes to next.config.js). My first attempt did not solve the problem. I'll try again later.

**Comment by M393** [comment]
In other places where browser-only code is used, it is done with lazy initialization, e. g.:
https://github.com/openlayers/openlayers/blob/1f2441945e4fd7659ae837834c936b18517cdfd4/src/ol/webgl.js#L119-L133

Maybe something like:
```patch
diff --git a/src/ol/render/webgl/VectorStyleRenderer.js b/src/ol/render/webgl/VectorStyleRenderer.js
index f62e13cd37..49eda2f264 100644
--- a/src/ol/render/webgl/VectorStyleRenderer.js
+++ b/src/ol/render/webgl/VectorStyleRenderer.js
@@ -20,7 +20,13 @@ import {
 import {colorEncodeId} from './utils.js';
 
 const tmpColor = [];
-const WEBGL_WORKER = createWebGLWorker();
+let WEBGL_WORKER;
+function getWebGLWorker() {
+  if (!WEBGL_WORKER) {
+    WEBGL_WORKER = createWebGLWorker();
+  }
+  return WEBGL_WORKER;
+}
 let workerMessageCounter = 0;
 
 /**
@@ -424,6 +430,7 @@ class VectorStyleRenderer {
       renderInstructionsTransform: transform,
       customAttributesSize: getCustomAttributesSize(this.customAttributes_),
     };
+    const WEBGL_WORKER = getWebGLWorker();
     WEBGL_WORKER.postMessage(message, [renderInstructions.buffer]);
 
     // leave ownership of render instructions
```

**Comment by jahow** [comment]
Good point @M393, that would probably fix many issues! If anyone feels like doing such a PR with this change please go ahead.
