### ISSUE TITLE
setTileLoadFunction() triggers error when called asynchronously on OSM source

### ISSUE THREAD

**Issue by marcovo** [openlayers/openlayers#16444]
**Describe the bug**
When calling `setTileLoadFunction()` in a deferred(/promise) manner on an `OSM` source, OpenLayers throws an exception `imageTile.getImage() is null` and rendering is glitched.

**To Reproduce**
1. Clone https://github.com/openlayers/ol-vite
2. Replace `main.js` with the code below
3. Reload the page. For me, in more than half of the page loads the exception occurs.

```js
import './style.css';
import {Map, View} from 'ol';
import TileLayer from 'ol/layer/Tile';
import OSM from 'ol/source/OSM';

const osm = new OSM();

setTimeout(() => {
  osm.setTileLoadFunction(function(tile, src) {
    tile.getImage().src = src;
  });
});

const map = new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: osm
    })
  ],
  view: new View({
    center: [0, 0],
    zoom: 2
  })
});
```
Exception as reported in devtools:
```
Uncaught TypeError: imageTile.getImage() is null
    defaultTileLoadFunction TileImage.js:316
    load ImageTile.js:155
    loadMoreTiles TileQueue.js:123
    handlePostRender Map.js:1205
    postRenderTimeoutHandle_ Map.js:1645
3 [TileImage.js:316:62](http://localhost:5173/node_modules/ol/source/TileImage.js)
    defaultTileLoadFunction TileImage.js:316
    load ImageTile.js:155
    loadMoreTiles TileQueue.js:123
    handlePostRender Map.js:1205
    postRenderTimeoutHandle_ Map.js:1645
```

Observations:
 - When replacing `setTileLoadFunction()` in `changed()`, the behaviour is similar, so the problem likely is somewhere in `changed()`
 - When using `setTimeout()`, the exception occurs. When performing `setTileLoadFunction()` (or `changed()`) synchrously, the exception does not occur
 - The exception happens since OpenLayers 10.0. Behaviour is correct with OpenLayers 9.2.

Tested on Firefox+Windows.

**Observed workaround**
Use `tileLoadFunction = ` setter instead of `setTileLoadFunction()`, but this is not official API.

**Expected behavior**
No exception should be thrown.

**Comment by mike-000** [comment]
I cannot reproduce this, but it seems related to #16364.  A change to the source will dispose of tiles and refresh the source.

**Comment by marcovo** [comment]
For me the issue is still reproducable even when using:
```json
  "dependencies": {
    "ol": "dev"
  }
```
(resolving to `ol@10.3.2-dev.1733499492405`)

**Comment by ahocevar** [comment]
@marcovo I also cannot reproduce with ol@10.3. But I think your build setup is wrong. You're not supposed to clone ol-vite, but run

    npx create-ol-app my-app

instead. I'm pretty sure your app runs with an older `ol` version due to the way you set up the test project.

**Comment by marcovo** [comment]
I don't suppose the different approach `git`<->`npx` should matter here, but I have reran the reproduction using `npx` now and document it below. I'm running this from WSL2.

```
$ node --version
v18.20.5

$ npm --version
10.8.2

$ npx create-ol-app my-app
Need to install the following packages:
create-ol-app@1.2.0
Ok to proceed? (y) y


added 32 packages, and audited 33 packages in 844ms

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ cd my-app/

 ---> Replace main.js file contents with those shown in initial post

$ npm start
```

Now, heading to http://localhost:5173/ gives me the mentioned exception.

In `node_modules/ol/util.js`, I find this version:
```
export const VERSION = '10.3.0';
```

I update:
```
$ npm update

changed 9 packages, and audited 32 packages in 9s
```

Now I see the following version, still with the same exception behaviour:
```
export const VERSION = '10.3.1';
```

I update the dependency and update:
```
  "dependencies": {
    "ol": "dev"
  }
```

```
$ npm update

changed 1 package, and audited 32 packages in 2s
```

Now I see the following version, still with the same exception behaviour:
```
export const VERSION = '10.3.2-dev.1733614996166';
```
When putting a `debugger;` or `console.log()` in a file in the `node_modules/ol` directory, I see those appearing in the browser, verifying that the reproduction is indeed using the correct code. (It does take restarting the vite server to show up - it is quite tricky, I guess vite does not expect you to change node_modules code.)

When using Firefox and using Ctrl+F5, either one of the following happens:
 - The map loads correctly, with a total request count of 46
 - The map does not load correctly (showing all white), with no exceptions, and a total request count of 30 (consistently)

When using Firefox and using F5, either one of the following happens:
 - The map loads correctly, with a total request count of 24
 - The map does not load correctly, with a total request cound of 24 (consistently), and showing a checkerboard map with a number of copies of the mentioned exception. (Zooming in/out does not lead to new tiles being loaded - it appears one static image.)

![afbeelding](https://github.com/user-attachments/assets/9def365e-24a0-4c6a-ba8a-b75197bd618c)

Copying the last exception message:
```
Uncaught TypeError: imageTile.getImage() is null
    defaultTileLoadFunction TileImage.js:316
    load ImageTile.js:155
    loadMoreTiles TileQueue.js:123
    handlePostRender Map.js:1205
    postRenderTimeoutHandle_ Map.js:1645
    setTimeout handler*renderFrame_ Map.js:1643
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    handleTileChange_ Map.js:1371
    handleTileChange TileQueue.js:98
    dispatchEvent Target.js:114
    changed Tile.js:132
    handleImageLoad_ ImageTile.js:104
    listenImage Image.js:243
    promise callback*listenImage Image.js:241
    load ImageTile.js:156
    loadMoreTiles TileQueue.js:123
    handlePostRender Map.js:1205
    postRenderTimeoutHandle_ Map.js:1645
    setTimeout handler*renderFrame_ Map.js:1643
    animationDelay_ Map.js:1448
    render Map.js:1481
    dispatchEvent Target.js:114
    changed Observable.js:70
    handleLayerChange_ Group.js:151
    dispatchEvent Target.js:114
    changed Observable.js:70
    handleSourceChange_ Layer.js:233
    dispatchEvent Target.js:114
    changed Observable.js:70
    setTileLoadFunction UrlTile.js:163
    <anonymous> main.js:9
    setTimeout handler* main.js:8
[TileImage.js:316:62](http://localhost:5173/node_modules/ol/source/TileImage.js)
    defaultTileLoadFunction TileImage.js:316
    load ImageTile.js:155
    loadMoreTiles TileQueue.js:123
    handlePostRender Map.js:1205
    postRenderTimeoutHandle_ Map.js:1645
    (Async: setTimeout handler)
    renderFrame_ Map.js:1643
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    handleTileChange_ Map.js:1371
    handleTileChange TileQueue.js:98
    dispatchEvent Target.js:114
    changed Tile.js:132
    handleImageLoad_ ImageTile.js:104
    listenImage Image.js:243
    (Async: promise callback)
    listenImage Image.js:241
    load ImageTile.js:156
    loadMoreTiles TileQueue.js:123
    handlePostRender Map.js:1205
    postRenderTimeoutHandle_ Map.js:1645
    (Async: setTimeout handler)
    renderFrame_ Map.js:1643
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    dispatchEvent Target.js:114
    changed Observable.js:70
    handleLayerChange_ Group.js:151
    dispatchEvent Target.js:114
    changed Observable.js:70
    handleSourceChange_ Layer.js:233
    dispatchEvent Target.js:114
    changed Observable.js:70
    setTileLoadFunction UrlTile.js:163
    <anoniem> main.js:9
    (Async: setTimeout handler)
    <anoniem> main.js:8
```


When using Chrome and using either Ctrl+F5 or F5, either one of the following happens:
 - The map loads correctly, with a total request count of 51
 - The map does not load correctly (showing all white), with no exceptions, and a total request count of 35 (consistently)

I must note, the total request counts did fluctuate a bit over the period I tested. It started being consistently 50/34, after a while consistently 51/35, then again after some time the tests were consistently showing 52/36. Not sure why, but I assume that is unrelated.


Also, I mentioned that setting a positive amount of milliseconds still reproduces the issue, this is not entirely true I think. Setting it to 1 millisecond, the above still holds. Setting it to `1000` milliseconds, I get mostly normal behaviour, however when zooming at the 1000ms mark, I do get the following exception a number of times, after which the page continues working normally again:
Firefox:
```
Uncaught TypeError: imageTile.getImage() is null
    defaultTileLoadFunction TileImage.js:316
    load ImageTile.js:155
    loadMoreTiles TileQueue.js:123
    handlePostRender Map.js:1205
    postRenderTimeoutHandle_ Map.js:1645
    setTimeout handler*renderFrame_ Map.js:1643
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    render Map.js:1481
    handleViewPropertyChanged_ Map.js:1378
    dispatchEvent Target.js:114
[TileImage.js:316:62](http://localhost:5173/node_modules/ol/source/TileImage.js)
    defaultTileLoadFunction TileImage.js:316
    load ImageTile.js:155
    loadMoreTiles TileQueue.js:123
    handlePostRender Map.js:1205
    postRenderTimeoutHandle_ Map.js:1645
    (Async: setTimeout handler)
    renderFrame_ Map.js:1643
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    renderFrame_ Map.js:1598
    animationDelay_ Map.js:1448
    (Async: FrameRequestCallback)
    render Map.js:1481
    handleViewPropertyChanged_ Map.js:1378
    dispatchEvent Target.js:114
```

Chrome:
```
Uncaught TypeError: Cannot set properties of null (setting 'src')
    at ImageTile.defaultTileLoadFunction [as tileLoadFunction_] (ol_source_OSM.js?v=dd410048:1242:28)
    at ImageTile.load (chunk-HLNA5AWN.js?v=dd410048:1314:12)
    at TileQueue.loadMoreTiles (ol.js?v=dd410048:15925:14)
    at Map.handlePostRender (ol.js?v=dd410048:18598:19)
    at ol.js?v=dd410048:18975:14
```

This would imply I guess, that the issue here is really a race condition somewhere, only occurring when `changed()` is called within some very specific time frame from initial load.

When calling `setTileLoadFunction()` outside `setTimeout()` or not calling it at all, the behaviour mentioned above disappears and the map is consistently shown functioning perfectly well.

I now note that while Firefox using F5 still produces the same checkerboard behaviour, however at this moment it consistently produces a different checkerboard than before:
![afbeelding](https://github.com/user-attachments/assets/d7bcb1c7-5a04-453f-8699-5a05116f8650)

**Comment by mike-000** [comment]
I can reproduce it now, the timeout needed depends on map size, browser cache and network speed - setting a small `maxTilesLoading` in the options for a large map makes it more likely to occur, even with a timeout of 500ms.  Tiles appear to be disposed while they are queued, causing the error when attempting to load them and leaving the queue full.

**Comment by mike-000** [comment]
Possibly related: constantly moving the slider can result in https://openlayers.org/en/latest/examples/wmts-dimensions.html no longer updating - but no errors are logged.

**Comment by MelkorCC** [comment]
> Tiles appear to be disposed while they are queued, causing the error when attempting to load them and leaving the queue full.

@mike-000 maybe a naive question from me, but is there a reason why there is no error handling that prevents the TileQueue from filling up and never recovering again?

**Comment by mike-000** [comment]
@MelkorCC  Load errors are handled.  Unexpected errors caused by tiles being disposed as a result of user action while queued or loading are not currently caught, and will need to be prevented.

**Comment by ahocevar** [comment]
@mike-000 I doubt that's related. If there is no error, I don't see how the tile queue could be saturated with disposed tiles.

I did a lot of debugging during the work on https://github.com/openlayers/openlayers/issues/16364, so I'll try to reproduce with the other methods mentioned here.

**Comment by mike-000** [comment]
> If there is no error, I don't see how the tile queue could be saturated with disposed tiles.

It seems similar to

> The map does not load correctly (showing all white), with no exceptions, and a total request count of 35 (consistently)

If `dispose` removes the listener the queue might be blocked waiting for disposed tiles which will never load.

**Comment by ahocevar** [comment]
#16455 should fix this issue.

**Comment by mike-000** [comment]
It fixes the case described in https://github.com/openlayers/openlayers/issues/16444#issuecomment-2525667977  The layer now partially renders, then refreshes and fully renders with no errors logged.  I have not attempted the WMTS dimensions case as that was harder to reproduce.

**Comment by marcovo** [comment]
When installing #16455 (`npm i --save openlayers/openlayers#pull/16455/head`), this seems to fix the behaviour I described in https://github.com/openlayers/openlayers/issues/16444#issuecomment-2525465978. Using that branch, I cannot reproduce the erroneous behaviour and exceptions when refreshing (F5 / Ctrl+F5) any more, and also the exceptions when scrolling during a `setTimeout(changed, `000)` don't appear any more.

Great!
