### ISSUE TITLE
Shared tile source workarounds?

### ISSUE THREAD

**Issue by WillieMaddox** [openlayers/openlayers#16466]
Greetings,

I posted an issue over at the ol-ext repo concerning the new tile cache behavoir in OL v.10.  I was not able to get my issue resolved so I thought I would ask here.  

Here is the issue in full detail: Viglino/ol-ext#1112.

In short, is there a way to force 2 or more layers to still use the same tile source cache the way it was done pre v.10?

If not, is there a workaround?

Thanks

**Comment by ahocevar** [comment]
If the server sends cache and/or etag headers, then no additional downloads will be triggered either - just like before v10, unless the tiles have changed, in which you'll get newer versions, which might be desirable anyway.

**Comment by WillieMaddox** [comment]
That's weird.  When I switch to the matching layer on the other layer switcher, chrome dev tools shows that new entries are coming in under the network tab.  In the case of OSM, when I search for the same tile, I can see from the Response Headers that the Etag's match, but the newer tile has `X-Cache: HIT` while the older tile has `X-Cache: MISS`.  Also, the Response values are the same for both tiles and the timings are about the same too.  This all seems to indicate the browser is double downloading the tiles.  Am I wrong?

**Comment by MoonE** [comment]
>the newer tile has `X-Cache: HIT` while the older tile has `X-Cache: MISS`. 

That sounds like it is downloading only once because the etag matches.
Do the Transferred size values differ? In Chrome you can hover with the mouse over the Size column. In Firefox this is a separate column.

**Comment by WillieMaddox** [comment]
I checked and the transferred sizes were the same and in doing so I found the problem...

Apparently, when `Disable cache` is checked in google dev tools it doesn't reset when you close dev tools.  What's worse is that it is applied to EVERY google tab not just the one in which it was set.  I unchecked `Disable cache` and now everything is perfect.  

Thanks for the help!
