### ISSUE TITLE
map loadstart or loadend listener causes WebGLTile style color expression to not receive GeoTIFFSource nodata-based alpha band

### ISSUE THREAD

**Issue by jcphill** [openlayers/openlayers#16486]
I'm using ol.layer.WebGLTile to view a ol.source.GeoTIFF of one single-band COG with a nodata value. As described in the docs, an alpha band with 0 for nodata pixels and 1 otherwise is passed to the WebGLTile style color expression as band 2. This works when I call map.on('dblclick', ...) but if I add a no-op listener for 'loadstart' or 'loadend' then `['band' 2]` in the color expression retrieves band 1 rather than the generated alpha band (not sure what is supposed to happen when a missing band is accessed). Adding the listener after the layer has loaded has no effect. The problem does not occur if the GeoTIFF source has two source urls.

The attached reproducer loads two identical maps with a style color of red where band 2 is not 1 and listens for dblclick on the first and loadend on the second. The first map shows the image and the second is red.

[nodatabug.html.txt](https://github.com/user-attachments/files/18173881/nodatabug.html.txt)

**Comment by mike-000** [comment]
That may be related to #16000 and #16065 as it works as expected if bands 3 and 4 are used instead of 1 and 2.

**Comment by jcphill** [comment]
I think I see the problem. `handleSourceUpdate_()` is only called if the layer source _property_ is changed:
https://github.com/openlayers/openlayers/blob/0ec298039445511783b3f57f1a61fdb316c9f458/src/ol/layer/WebGLTile.js#L327
If the source is only set in the constructor then `handleSourceUpdate_()` is never called. A fix would be to call `handleSourceUpdate_()` at the end of the `WebGLTileLayer` constructor.

I can confirm that in my test case if I create the layer without a source first and then call `layer.setSource(source)` the issues goes away.
