### ISSUE TITLE
Rendering test documentation says to run make

### ISSUE THREAD

**Issue by jcphill** [openlayers/openlayers#16495]
**Describe the bug**
Old instructions for running rendering tests with make:
https://github.com/openlayers/openlayers/blob/32a701ff65e3a8cf520e35a97a482db3b23dc82c/test/README.md?plain=1#L35-L44

**To Reproduce**
1. Go to 'https://github.com/openlayers/openlayers/tree/main/test#rendering-tests'
2. See instructions to run `make serve` and `make test-rendering`

**Expected behavior**
Updated instructions with more detail than at https://github.com/openlayers/openlayers/blob/main/DEVELOPING.md#running-tests

**Comment by ahocevar** [comment]
That README should probably just link to https://github.com/openlayers/openlayers/tree/main/test/rendering#readme. I'm going to fix that right now.
