### ISSUE TITLE
Endless animation loop when passing wrapX to WMTS source with non-global projection

### ISSUE THREAD

**Issue by manisandro** [openlayers/openlayers#16493]
Consider the following minimal example
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WMTS</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@latest/ol.css">
    <style>
        #map {
            width: 100%;
            height: 100vh;
        }
    </style>
</head>
<body>
    <div id="map"></div>
    <script src="https://cdn.jsdelivr.net/npm/proj4/dist/proj4.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/ol@latest/dist/ol.js"></script>
    <script>
        proj4.defs('EPSG:2056', '+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs');
        ol.proj.proj4.register(proj4);
        const projection = ol.proj.get('EPSG:2056');

        const wmtsSource = new ol.source.WMTS({
            "urls":[
                "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/2056/{TileMatrix}/{TileCol}/{TileRow}.jpeg"
            ],
            "layer":"ch.swisstopo.swissimage",
            "format":"image/jpeg",
            "projection":ol.proj.get("EPSG:2056"),
            "matrixSet":"2056_28",
            "tileGrid":new ol.tilegrid.WMTS({
                "extent":[2419995.748807363,1030006.6631994816,2900009.7274287273,1350004.292478853],
                "origin":[2420000,1350000],
                "resolutions":[4000,3750,3500,3250,3000,2750,2500,2250,2000,1750,1500,1250,1000,750,650,500,250,100,50,20,10,5,2.5,2,1.5,1,0.5,0.25,0.09999999999999999],
                "matrixIds":["0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"],
                "tileSize":[256,256]
            }),
            "wrapX":true,
            "requestEncoding":"REST"
        });

        const map = new ol.Map({
            target: 'map',
            layers: [
                new ol.layer.Tile({
                    source: wmtsSource,
                }),
            ],
            view: new ol.View({
                center: [2600000, 1200000],
                zoom: 2,
                projection: projection,
            }),
        });
    </script>
</body>
</html>
```

With `"wrapX":true` (even though it makes no sense in a non-global projection), openlayers will end up requesting animation frames forever:

![image](https://github.com/user-attachments/assets/2cde2644-4873-4b71-9156-b32de697d4ab)

Tested with openlayers 10.3.1.

**Comment by ahocevar** [comment]
To make wrapX work, you need to call `setExtent()` on the used projection, with the correct bounds:
```js
const projection = ol.proj.get('EPSG:2056');
projection.setExtent(transformExtent([5.96, 45.82, 10.49, 47.81], 'EPSG:4326', 'EPSG:2056'));
```
But like you said - why would you configure `wrapX: true` for a non-global projection?

**Comment by manisandro** [comment]
Sure, this is a badly generated configuration. I just noticed the CPU running at full throttle and I investigated why that was. I'm happy with closing this as not-a-bug, the only point perhaps worth evaluating is whether ol should catch this or not.

**Comment by ahocevar** [comment]
@manisandro Did you try what happens when you set the projection extent?

**Comment by manisandro** [comment]
With the line
```
projection.setExtent([2485071.58, 1074261.72, 2837119.8, 1299941.79]);
 ```
added to the example above I still get the endless animation loop.

**Comment by ahocevar** [comment]
> the only point perhaps worth evaluating is whether ol should catch this or not.

Here it won't help to check for whether an `extent` is specified for the projection when `wrapX` is used. And opportunities for other configuration mistakes are plenty.. The one thing I notice is that the `origin` of your corner is not a corner of the extent, which it probably should be because no resolution dependent `origins` are specified. This is something that could be cought by OpenLayers. See here:
```js
                "extent":[2419995.748807363,1030006.6631994816,2900009.7274287273,1350004.292478853],
                "origin":[2420000,1350000],
```
Maybe it's enough to omit the `origin`.

**Comment by mike-000** [comment]
This is not specific to WMTS.  XYZ sources which default to `wrapX: true` can be configured with custom tile grids and projections:

        const xyzSource = new ol.source.XYZ({
            "urls":[
                "https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/2056/{z}/{x}/{y}.jpeg"
            ],
            "projection":ol.proj.get("EPSG:2056"),
            "tileGrid":new ol.tilegrid.TileGrid({
                "extent":[2419995.748807363,1030006.6631994816,2900009.7274287273,1350004.292478853],
                "origin":[2420000,1350000],
                "resolutions":[4000,3750,3500,3250,3000,2750,2500,2250,2000,1750,1500,1250,1000,750,650,500,250,100,50,20,10,5,2.5,2,1.5,1,0.5,0.25,0.09999999999999999],
                "tileSize":[256,256]
            }),
        });

More realistically it would affect examples such as https://labs.os.uk/public/os-data-hub-examples/os-maps-api/zxy-27700-basic-map#openlayers if using the latest release and the extent was specified on the tile grid instead of constraining the view.

**Comment by mike-000** [comment]
This also affects legitimate wrappable sources which have a limited tile grid extent in a global projection, for example

```
const key = 'ufArYa1UUPHJcOYbiJDaKkA7Fb4oCkEs';
const fullGrid = createXYZ({ maxZoom: 16 });

const map = new Map({
  layers: [
    new TileLayer({
      source: new OSM(),
    }),
    new TileLayer({
      source: new XYZ({
        url:
          'https://api.os.uk/maps/raster/v1/zxy/Road_3857/{z}/{x}/{y}.png?key=' +
          key,
        tileGrid: new TileGrid({
          extent: transformExtent(
            [-10.76418, 49.528423, 1.9134116, 61.331151],
            'EPSG:4326',
            'EPSG:3857'
          ),
          origin: fullGrid.getOrigin(),
          resolutions: fullGrid.getResolutions(),
          minZoom: 7,
        }),
      }),
    }),
  ],
  target: 'map',
  view: new View({
    center: fromLonLat([178, 55]),
    zoom: 0,
  }),
});
```

The problem was introduced by #16365 which only checks for IDLE and ERROR tile states.  Tiles outside the grid extent will be EMPTY, and only reproj tiles are checked for that state.

**Comment by ahocevar** [comment]
Isn't this also fixed by #16509?

**Comment by mike-000** [comment]
A quick test running with the full builds from #16509, #16365 and #16362 (the last before #16365) shows #16509 is an improvement as it uses less resources than #16365, but it is still in a loop.  #16362 uses no resources after the map renders.

**Comment by ahocevar** [comment]
@mike-000 So it seems like changing

https://github.com/openlayers/openlayers/blob/4c8d1c534405e054652fe9bf643f1fd85677520b/src/ol/renderer/canvas/TileLayer.js#L686-L688

to something like
```js
 if (tileState !== TileState.ERROR && tileState !== TileState.EMPTY) { 
   this.renderComplete = false; 
 } 
```
would be a sensible fix.

If you want to create a small pull request with this change, ideally with a test, it would be appreciated.

**Comment by mike-000** [comment]
Could we simply ignore all EMPTY tiles by removing the

`(tile instanceof ReprojTile || tile instanceof ReprojDataTile) &&`

line - is there a reason for that being specific to reprojection?

**Comment by ahocevar** [comment]
@mike-000 You added that code, I don't know.
