### ISSUE TITLE
Infinite reloading of a tile

### ISSUE THREAD

**Issue by tomass** [openlayers/openlayers#16508]
**Infinite reloading of a tile**
With incorrect vector tile url OpenLayers tries to reload tile indefinitely.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a html with the source provided below
2. Zoom until 7 level
3. Network traffic shows infinite reloading of vector tiles (which all produce 404).

**Expected behavior**
If tile request gets 404 there is no point to retry.
**Note:** error is not reproducible with say 10.2.1 version.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple OpenLayers Map</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@latest/ol.css">
    <style>body { margin: 0; padding: 0; } #map { width: 100%; height: 100vh; }</style>
</head>
<body>
    <div id="map"></div>

    <script src="https://cdn.jsdelivr.net/npm/ol@latest/dist/ol.js"></script>
    <script>
        const map = new ol.Map({
            target: 'map',
            layers: [
                new ol.layer.Tile({ source: new ol.source.OSM() }),
                new ol.layer.VectorTile({
                    source: new ol.source.VectorTile({
                        format: new ol.format.MVT(),
                        url: 'https://something.bad/{z}/{x}/{y}.pbf'
                    }),
                    style: new ol.style.Style()
                })
            ],
            view: new ol.View({
                center: ol.proj.fromLonLat([0, 0]), // Center of the map [longitude, latitude]
                zoom: 2 // Initial zoom level
            })
        });
    </script>
</body>
</html>
```

**Comment by ahocevar** [comment]
@tomass Thanks for reporting this. Can you provide a full reproduction case, i.e. with tile url that causes the problem? I cannot reproduce with the above code.

**Comment by tomass** [comment]
Id does infinite reloading on my FF 128.5.0esr after some specific zoom level (with exact code as posted above)
![paveikslas](https://github.com/user-attachments/assets/7fd75af4-6706-4a9d-805b-8a85417dd70b)

I've also checked with Chrome 131.0.6778.204 - it can also be reproduced.
I've checked on linux and windows.

Cannot think of what could be the difference... have you zoomed in till zoom level 6 or 7 (or maybe even more)?

**Comment by tomass** [comment]
Maybe different version is coming using "latest"... Can you try with this:

`<script src="https://cdn.jsdelivr.net/npm/ol@10.3.1/dist/ol.js"></script>` - reproduces
`<script src="https://cdn.jsdelivr.net/npm/ol@10.3.0/dist/ol.js"></script>` - reproduces
`<script src="https://cdn.jsdelivr.net/npm/ol@10.2.1/dist/ol.js"></script>` - works fine

**Comment by ahocevar** [comment]
Ok, I can reproduce with the current main branch. Thanks for the detailed description. Looking into a fix now.
