### ISSUE TITLE
protocol relative tile urls break file:// URLs

### ISSUE THREAD

**Issue by pagameba** [openlayers/openlayers#1729]
In the [developer's guide](https://github.com/openlayers/ol3/wiki/Developer-Guide#wiki-running-examples), we suggest to users that they can run the examples like this:

>  Then, either open one of the example html files from the examples directory directly in your browser, or start a simple web server, for example

The recent change to protocol relative urls in #1694, #1692, and #47 removes the ability to load HTML files with the file:// protocol.  I suppose the easiest fix is to change that in the developer's guide, but I am not sure this is the best approach.

**Comment by regevbr** [comment]
I overcame that issue by creating the following module - https://www.npmjs.com/package/cordova-network-interceptor which intercepts and fixes bad network requests cause by relative protocol used in scripts. Hope that helps!
