### ISSUE TITLE
GPX: read extensions tags

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#1791]
See http://www.topografix.com/GPX/1/1/#type_extensionsType

**Comment by dvmac** [comment]
I've encountered an issue related to this thread and when I asked the question on gis.stackexchange, no-one could help so I'm wondering if anyone from the team can?
http://gis.stackexchange.com/questions/199610/openlayers-3-gpx-shape-issue

Essentially, when the extensionsNode is read, has the feature been created already? Shapes are being interpreted as Routes and I'd like to intercept this and correct the problem but I don't know how unfortunately. Any help would be appreciated. File attached, thanks.

[MyBigDayOut.gpx.zip](https://github.com/openlayers/ol3/files/411466/MyBigDayOut.gpx.zip)
