### ISSUE TITLE
Map moveend (and postrender) events are triggered non-stop

### ISSUE THREAD

**Issue by theoutlander** [openlayers/openlayers#1823]
(Copying my email from the DL as per @tschaub: https://groups.google.com/forum/#!topic/ol3-dev/Dq-Hhe-qddc)

I've had a hard time finding a list of events that I can listen to. So, I've played around with the code/examples and experimented in the debugger to see what I can actually listen to. My immediate use-case is to find out when the map has completed zooming. However, I haven't found a specific event for that. The closest event was MoveEnd. If someone knows a better event, please let me know.

The problem I'm facing is that the moveend event is triggered repeatedly (non-stop...forever!). I'm not sure why or if it is expected?

I'm simply rendering a vector layer and listening for a "moveend" event on the map so that I can redraw my vector based off the new extent/zoom level. 

This is how I'm registering an event handler: 
this._olMap.on('moveend', _mapMoveEndHandler);

Here's the callstack for the repeated calls:

IDM$Common$Client$Map$Core$Map$.render._mapMoveEndHandler (IDM.Common.Client.Map.js:805)
goog.events.EventTarget.fireListeners (ol-whitespace.js:8494)
goog.events.EventTarget.dispatchEventInternal_ (ol-whitespace.js:8538)
goog.events.EventTarget.dispatchEvent (ol-whitespace.js:8453)
ol.Map.renderFrame_ (ol-whitespace.js:27828)
goog.async.AnimationDelay.doAction_ (ol-whitespace.js:16427)

Here's the lib I'm referencing:
http://ol3js.org/en/master/build/ol-whitespace.js

Suggestions and insights welcome.

Thanks,
Nick

**Comment by philip-firstorder** [comment]
This still happens in ol 6.1.1.

I put a console.log on moveend and it triggers forever after some combination of .fit(extent) & viewport resize.

I load an ImageStatic layer which I fit inside the viewport everytime I resize the viewport or the browser window.

Very hard to reproduce, I get it only in 1 in 20 cases, but I got 10 times today and on mobile it gets the phone hot while draining the battery.

**Comment by tschaub** [comment]
@philip-firstorder could you please open a new ticket with as much information as possible so others could try to reproduce the issue?

**Comment by philip-firstorder** [comment]
Will do today, maybe I can find the reason too.
