### ISSUE TITLE
GeoJSON writing needs to account for the crs

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#2078]
Currently, the GeoJSON format writes features/geometries without a crs member.  In cases where geometries are not Geographic/WGS84, this produces invalid GeoJSON.

I don't think it makes sense to use the current `defaultProjection` for this purpose.  Instead a `projection` option could be used to transform features when reading and properly serialize features with a crs member when writing.

**Comment by WillieMaddox** [comment]
This has been on the TODO list for some time.  Any idea when it might get incorporated into ol3?
