### ISSUE TITLE
Support for layer extent

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#2091]
Layer rendering can currently be restricted given `minResolution` and `maxResolution`.  It would also be useful to limit rendering based on an extent.  Providing a layer with an `extent` option would limit the requests for image/tile or vector data based on that extent.

Note that this is different than specifying a custom tile grid for a source.  It should be possible, for example, to have a standard XYZ grid but only request tiles in a limited extent (without necessarily restricting the view to this same extent).

**Comment by rfcsantos** [comment]
@elemoine "Quick note: sources already have an extent option/property that may fulfill the same need". Is that possible? We can set the layer extent and a source extent? i can't find the way of doing that? I only can set the layer extent? can you provide me more information? thank you

**Comment by bartvde** [comment]
@rfcsantos this was changed, follow the history in the ticket. Only layers now have extent, not sources.

**Comment by rfcsantos** [comment]
Ok, thank you.

**Comment by ahocevar** [comment]
I'm currently working on a change that allows tile grids to be configured with an extent. Stay tuned.

**Comment by probins** [comment]
will that also fix #2623? This is something I've been meaning to come back to. Bbox is part of the definition of WM(T)S layers so needs to be in the source. At the moment create source from capabilities is ignoring the bbox, but this should be what determines the extent used by the url function, as anything outside that won't have any corresponding tiles

**Comment by ahocevar** [comment]
Yes @probins, this will also fix #2623.

**Comment by probins** [comment]
look forward to that, then :-)
