### ISSUE TITLE
TiledWMS and GeoServer

### ISSUE THREAD

**Issue by pramsey** [openlayers/openlayers#2143]
GeoServer will try and delegate requests to its internal GeoWebCache, but only if TILED=TRUE on the request URL (or if you hit the GWC endpoint directly). Using the following 

```
          new ol.layer.Tile({
            source: new ol.source.TileWMS({
              /** Note use of workspace osm in the WMS url */
              url: 'http://localhost:8080/geoserver/osm/wms',
              projection: 'EPSG:3857',
              extent: [-20037508.34,-20037508.34,20037508.34,20037508.34],
              params: {
                /** Workspace spec'ed above means we don't need it here */
                'LAYERS': 'osm',
                /** PNG for street maps, JPG for aerials */
                'FORMAT': 'image/png',
              },
              /** @type {ol.source.wms.ServerType} */ 
              serverType: 'geoserver'
            })
          })
```

does not generate a request that GeoServer recognizes as suitable for tiling, even though the serverType is set to geoserver. If you add TILED:TRUE to the params, then things start to work, but I'd expect a "TileWMS" source to handle that for me, generally.

**Comment by tschaub** [comment]
If this is still relevant and someone wants to implement a solution based on the suggestion above, please open a new ticket with your proposed solution.
