### ISSUE TITLE
ol.style.Stroke icons

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#2234]
Ability to add icons to a `ol.style.Stroke` (eg. direction arrow)

See https://developers.google.com/maps/documentation/javascript/symbols#add_to_polyline

**Comment by dennisguse** [comment]
Was this ever implemented?

**Comment by fredj** [comment]
no, it's not implemented

**Comment by dennisguse** [comment]
@fredj Are there any plans to do this?
Or was this feature not needed anymore?
And what would be a suitable approach for implementation (from todays perspective)?
