### ISSUE TITLE
Api docs not listing function params

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers#2253]
Example is layer.Vector.renderOrder: the null/undefined values are not being output.

There is a more general problem that function params are not being output.

**Comment by probins** [comment]
I think this issue has changed since I originally created it, but the general problem of function params not being listed is still there. I've just been looking for example at ol.Map's forEach methods. The callback param for forEachFeatureAtPixel refers to "the 2nd argument to this function" but nowhere does it say what the 2nd (or 1st) argument should be.

**Comment by marcjansen** [comment]
#3741 adds prose docs for the mentioned methods. I agree that a generic and autogenerated rendering of the function arguments / return types would be great.

**Comment by probins** [comment]
yeah, as I recall, there used to be something like this, but it didn't work properly, which was why I created this issue in the first place. As you say, having autogeneration of this stuff would be good, but if it's a lot of hassle to set up, then having prose descriptions as in 3741 will do.
