### ISSUE TITLE
More convenient way of detecting when a source is loaded.

### ISSUE THREAD

**Issue by pagameba** [openlayers/openlayers#2320]
It is currently inconvenient to tell when a source has finished loading features, you need to do something like this:

```
var key = source.on('change', function() {
  if (source.state == 'ready') {
    source.unByKey(key);
    // do something with the source
  }
});
```

which works but is not obvious to users first coming to the library.

@elemoine has suggested adding a load() method to source which would be used to register a function to be called when a source's state changes to ready.

**Comment by mikeu** [comment]
Has there been any further movement on this issue of detecting when a source's features are loaded, or is the change-event method mentioned above still the best way to accomplish this?

FWIW, as somebody new to ol3, testing it out to see whether I want to start upgrading from ol2, my first instinct was to look for the ability to pass a callback to the constructor, much like ajax calls in jQuery. Something like

    var src = new ol.source.GeoJSON({
      url: 'http://path.to/resource',
      success: callbackFunction
    });

As I said, I've only just started playing with ol3 and haven't investigated the source much, so not sure how that fits into its consistency. I'd certainly be happy with either that or the `load` method option already discussed.

**Comment by elemoine** [comment]
On Sat, Feb 28, 2015 at 12:57 AM, Michael Underwood
<notifications@github.com> wrote:
>
> Has there been any further movement on this issue of detecting when a source's features are loaded, or is the change-event method mentioned above still the best way to accomplish this?

Yes, that is still the best way to accomplish this.





-- 
Eric Lemoine

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 94
Mail : eric.lemoine@camptocamp.com
http://www.camptocamp.com

**Comment by bittailor** [comment]
I just used the change-event *workaround* today and noticed it needs to look like this since the state property can't be accessed directly :

```javascript
var key = source.on('change', function() {
  if (source.getState() == 'ready') {
    source.unByKey(key);
    // do something with the source
  }
});
```

**Comment by hutch120** [comment]
Using `source.on('change', myFunc)` I only see the first feature in the set on the first trigger.

Is it possible to trigger `myFunc` after the feature set completely loaded into the olSource object?

Basically I'm trying to find a feature in the set which requires it to be fully loaded first.

E.g.

    var key = source.on('change', function() {
      if (source.getState() == 'ready') {
        source.unByKey(key);
        var olFeatures = source.getFeatures(); // olFeatures.length === 1
      }
    });

BTW: I tried putting window.setTimeout around my code and getFeatures returns the entire feature list.

**Comment by arekgofi** [comment]
Still needed
