### ISSUE TITLE
Investigate code removal issue with define

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#2362]
I'm only using a single renderer, so I'm compiling with defines to avoid inclusion of code for the others.  It looks like the compiler cannot be as aggressive about code removal in this case as it can in other cases.  I'm not sure yet whether this is due to the define, but I wanted to ticket it for investigation later.

In my compiled output, the `goog.isDef` function gets renamed to `u`.  There are many places in the code where I see `u(void 0)`.  Since `void 0` is the compiler's byte-saving spelling of `undefined`, I assumed it could do some dead code removal here.

For example, I see compiled output like the following:

``` js
u(void 0) ? ((void 0).push(t, r), b = void 0) : b = [t, r];
```

and

``` js
u(void 0) && (void 0).call(void 0, s);
```

(And nine more like this.)

It looks to me like these are cases where a function has an optional argument that is never used due to a define (in my case, I think only the WebGL renderer calls these functions with optional arguments, and I'm using `ol.ENABLE_WEBGL=false`).

Experimenting with the compiler, I see that it does do dead code removal for more explicit cases where optional arguments are not used.  I'm curious if there is something different with defines.

This came up as an issue for me because I'm concatenating the compiled output together with other code and was trying to pass the whole thing through another compiler.  The `(void 0).call(void 0, s)` expression above was "incorrectly" compressed to `void 0.call(void 0, s)`.  The first form (which exists in our code base but is unreachable) is a runtime error.  The second a parsing error.

**Comment by fredj** [comment]
defines are not used anymore, closing
