### ISSUE TITLE
Implement WMTS GetFeatureInfo

### ISSUE THREAD

**Issue by bianchimro** [openlayers/openlayers#2368]
Implement GetFeatureInfo functionality on ol.source.WMTS to access information from WMTS layers, similarly to what has been done for ol.source.TileWMS and ol.source.ImageWMS.

**Comment by sarametz** [comment]
I have built on this by adding REST encoding functionality along with populating this from the WMTS capabilities in #3150. Please have a look at this if you're interested.

**Comment by jbelien** [comment]
Any follow up on this topic ? :)
