### ISSUE TITLE
Group "static" functions separately from instance methods

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#2392]
In cases where we assign functions to a constructor, it would be useful if the docs separated these from the method listing.  The two groups could be called "Methods" and "Functions" on a doc page.  For example, the [`ol.geom.Polygon` doc](http://ol3js.org/en/master/apidoc/ol.geom.Polygon.html) could list `ol.geom.Polygon.circular` under "Functions" and the rest of the methods under "Methods."

If this is more trouble than its worth, blame it on #2345.

**Comment by fredj** [comment]
@tschaub is is still relevant?
