### ISSUE TITLE
Assertion Error while map annimation with ol.source.XYZ

### ISSUE THREAD

**Issue by jacmendt** [openlayers/openlayers#2459]
After upgrading my OL3 version to ol3 gamma 3 my application crushes sometimes with the following error trace:

Uncaught AssertionError: Assertion failed ol-debug.js:3277
goog.asserts.doAssertFailure_ ol-debug.js:3277
goog.asserts.assert ol-debug.js:3292
ol.renderer.canvas.TileLayer.prepareFrame ol-debug.js:78234
ol.renderer.canvas.Map.renderFrame ol-debug.js:80080
ol.Map.renderFrame_ ol-debug.js:87389
goog.async.AnimationDelay.doAction_ ol-debug.js:68502

This error occurres when i add more than 1 different TMS layer and zoom in. Than the animation of the map zoom behavior seems to fail. If i go back to my older ol3 version everything works. In parallel to this error it seems to have problems to load TMS tiles from the server. But the tiles are available.

Add second layer
![addsecondlayer](https://cloud.githubusercontent.com/assets/5071511/3719844/91556a22-164a-11e4-8db6-48f36da55bba.png)

Zoom in and it failes
![animation_failed](https://cloud.githubusercontent.com/assets/5071511/3719845/95b46352-164a-11e4-993b-f937dd6bfe42.png)

**Comment by megaten** [comment]
Thanks for this thread. I've had the problem with 3.17 ol-debug.js
I have the message and the Layer is not displayed. 
So, everything is ok with ol.js
