### ISSUE TITLE
features remain in an interaction's overlay when clearing an ol.source

### ISSUE THREAD

**Issue by hutzelknecht** [openlayers/openlayers#2485]
when clearing features from an ol.source, selected features remain visible in a map, because they remain in the interaction's overlay.

```
layer.getSource().clear()
interaction.getFeatures() // the collection of selected features is not empty
```

either clear() needs to truley delete the features or the interaction needs binding with the source ???

**Comment by tschaub** [comment]
Please open an issue with an example demonstrating the problem if this is still valid.
