### ISSUE TITLE
ol.proj.transform

### ISSUE THREAD

**Issue by matiasbarone** [openlayers/openlayers#2500]
When I use the function `ol.proj.transform` and the second coordinate is a string the function return NaN in the second coordinate. The first coordinate works fine with number or text.
##### Here are four test that I made

`ol.proj.transform([-50, -50], 'EPSG:4326', 'EPSG:3857')`
`[-5565974.539663679, -6446275.841017161]`

`ol.proj.transform(["-50", -50], 'EPSG:4326', 'EPSG:3857')`
`[-5565974.539663679, -6446275.841017161]`

`ol.proj.transform(["-50", "-50"], 'EPSG:4326', 'EPSG:3857')`
`[-5565974.539663679, NaN]`

`ol.proj.transform([-50, "-50"], 'EPSG:4326', 'EPSG:3857')`
`[-5565974.539663679, NaN]`

The test were made with the Version: v3.0.0-gamma.3-34-g819fd83

**Comment by jkossis** [comment]
Did anyone ever determine why this happens? I am getting the same thing and can't figure it out....my 2nd coordinate is always NaN!

**Comment by jasonglisson** [comment]
Using v3.2 this still seems to be an issue.

**Comment by ahocevar** [comment]
Just make sure you pass numbers as coordinates, not strings. If you still get NaN, then your coordinates are probably outside the validity extent of EPSG:3857, i.e. beyond +/- 85 degrees.

**Comment by jasonglisson** [comment]
Yep! That was it. I can't believe how long it took me to get that. Didn't make sense to me since I was working with numbers the entire time, but somewhere along the way it was converted to a string. So anyone else that has this issue, wrap your lon and lat values in Number().

**Comment by christophfriedrich** [comment]
Another cause for NaNs can be that you specify latitude and longitude in the wrong order (remember OL expects long first, lat second).
