### ISSUE TITLE
Source in ol.layer.Base?

### ISSUE THREAD

**Issue by eriktim** [openlayers/openlayers#2522]
When trying to process all my map's sources, I ran into the fact that `ol.layer.Base` (which are returned by `map.getLayers().getArray()`) has no `getSource()` method, while `ol.layer.Layer` has. This kinda makes sense. However, both have a `getSourceState()` method, which might be confusing if there is no source.

I am willing to make a PR for this, but I am not sure whether this is desired or not.

**Comment by vangoo** [comment]
hi guys i use ol4 and typescript;

i get all layer with this;

```
let map: ol.Map;
....
let layers = map.getLayers();
let layer = layers.forEach(function (layer) {
                if (layer.get('title') == "title") {
                    result = layer;
                    return;
                };
            });

layer.getSource(); // does not exist on type Base
```

how can i get source of layer.Base?

**Comment by bartvde** [comment]
since group layers don't have a source, you can either check if your layer is an instance of group layer or you can check if layer has a getSource method

**Comment by vangoo** [comment]
on this case layer never has a getSource method because map.getLayers() return ol.Collection<ol.layer.Base>

**Comment by bartvde** [comment]
ah ok, then it's typescript specific indeed, I don't know anything about the typescript bindings, sorry

**Comment by vangoo** [comment]
Ah it's sad for me.  Thanks for comment.

**Comment by ilpise** [comment]
The source for `ol.layer.Base` is inside it's properties
Is possible to get it
`layer.getProperties().source`

Then, to get the url, for example
`layer.getProperties().source.getUrl()`
