### ISSUE TITLE
www.openlayers.org - API is not reachable via TLS

### ISSUE THREAD

**Issue by yoshimo** [openlayers/openlayers#2665]
Quite a few pages out there sent requests to your API like http://www.openlayers.org/api/theme/default/style.css ,
unfortunately this page isn't served over TLS and therefore causes nasty mixed-content warnings in recent browsers.

**Comment by dracoTrier** [comment]
please consider reopening this issue as nowadays, even tiny project websites run on TLS and openlayers not supporting TLS makes it impossible for those tiny solutions to integrate an open map.
Webbrowsers don't display non-tls content anymore at all on websites which have hsts configured.
