### ISSUE TITLE
Reloading a vector source when URL changes

### ISSUE THREAD

**Issue by acanimal** [openlayers/openlayers#2683]
Hi,
following Bart's recommendation I open this ticket so the issue can be commented.

It starts with https://groups.google.com/forum/#!topic/ol3-dev/PjFBy5mxwgo and https://groups.google.com/forum/#!topic/ol3-dev/H6tZaFUUO4E topics on the forum.

Once a vector layer with its source pointing to some URL is created, there is no way to update the layer (really the source) content other than loading, cleaning and adding new features by hand.

Although manually loading is the most flexible option, I think it is a bit confusing. I a user loads data initially setting an `url` property, why we need to load content manually if we want update the source?

It could be easy to have a `setUrl()` that updates the `url`property and invokes the `loadFeaturesFromURL()` method.

Any opinions?

PS: I offer as voluntary to make the code changes. But I don't know when I have enough free time :)

**Comment by akrherz** [comment]
I ran into this issue and it appears that all is now necessary is:

```
function reload() {
       var geojsonFormat = new ol.format.GeoJSON();
	vectorLayer.setSource(new ol.source.Vector({
		url: '/my/urlhere,json',
		format: geojsonFormat
	}));
}
```

I found that calling `clear()` causes a re-fetch of the remote resources, so the above would load the data twice?

**Comment by elemoine** [comment]
@akrherz note that setting a url and format on the vector source is not mandatory, you can do things  manually if you want to fully control the behavior of your vector source. This is what I would use:

```js
function loadSource(source, url) {
  $.ajax(url, function(response) {
    var geojsonFormat = new ol.format.GeoJSON();
    source.clear(true);
    source.addFeatures(geojsonFormat.readFeatures(response));
  });
}

var vectorLayer = new ol.layer.Vector({
  source: new ol.source.Vector()
});

// initial loading of the vector source
loadSource(vectorLayer.getSource(), initialUrl);
```

**Comment by akrherz** [comment]
@elemoine when I call `source.clear(true);` in your example, this causes the source to load the data.  So the code example loads the data twice.

**Comment by elemoine** [comment]
@akrherz in my example the source does not have a `url` so I don't understand how `clear` could load the source. What am I missing?

**Comment by akrherz** [comment]
@elemoine I am unsure what to say, when I try your code example in my app (no public access) and simply call `vectorLayer.getSource().clear(true);` on the chrome devel console, this single action causes the app to refetch the geojson data from the server.
![one](https://cloud.githubusercontent.com/assets/210858/7544995/ba971b38-f597-11e4-9318-a852875cf934.png)
![two](https://cloud.githubusercontent.com/assets/210858/7544998/bfc6187a-f597-11e4-8ea5-0f33296de69b.png)

**Comment by elemoine** [comment]
I'd need to see your code.

**Comment by akrherz** [comment]
@elemoine if it does not do this when you try it, it likely means I am doing something wrong.  It isn't worth your bother.  Thanks for the responses and work on openlayers.

**Comment by Neznaykas** [comment]
Hello. I faced with the same problem.
How use this in ol.source.ServerVector with bbox?

When i call clear() it consumed a lot of resources.
Please, give a small example.

**Comment by elemoine** [comment]
What ol3 version do you use? Note that ServerVector was removed in 3.5.

**Comment by Neznaykas** [comment]
Oh, I used the last version (v3.2.1).

As I understand the new version does not have this problem?
Then I will update the version of the library, and use an existing solution.

Thank you.
