### ISSUE TITLE
fitExtent: have options such as maxZoom

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#2723]
theoretically an extent can have xmin = xmax and ymin = ymax (when you get the extent of a source and it has a single point in it).

It would be nice if the fitExtent method of the view accepted options such as maxZoom (which are available on fitGeometry).

Thoughts?

**Comment by bartvde** [comment]
I believe @malaretv is working on this one

**Comment by adube** [comment]
I would also be interested in such a feature.  I'm also willing to work on this, so please let me know if you want me to.

**Comment by tsauerwein** [comment]
See also: https://github.com/openlayers/ol3/pull/3482

**Comment by fredj** [comment]
fixed with #2340
