### ISSUE TITLE
ol.layer.Heatmap linestring support

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#2817]
Add a new `geometryFunction` param as in `ol.source.Cluster`

**Comment by SakamotoLfe** [comment]
Is it possible to make a heatmap with linestring? I need to make a heatmap with linestrings with Open Layers 3 and AngularJS. 
To see the code I'm using, there's the [https://stackoverflow.com/questions/61731556/linestring-heatmap-with-open-layers-3](link)

**Comment by jahow** [comment]
The heatmap can only work with point geometries (not multi point either). You will have to somehow convert your line strings to points, either by taking their vertices individually or interpolating between them.

**Comment by jahow** [comment]
...or petition for the implementation of a webgl-based linestring renderer ;)

**Comment by SakamotoLfe** [comment]
I was trying to make with points but it got too heavy, more or less than 300 thousands of features, and the projection wasn't right! Even when I put "projection: 'EPSG:4326'" it doesn't work! Do you have some ideia about how to make it lighter to AngularJS? Also, I can open a petition but I can't update my Open Layers to 6 or newer, so for me it isn't going to help
