### ISSUE TITLE
Mousewheel-Zoom will scroll whole page in Firefox

### ISSUE THREAD

**Issue by marcu** [openlayers/openlayers#2831]
This issue occurs in Firefox (tested with Firefox 32.0.3). It does not occur in Safari.

Reproduction steps: 1) go to http://openlayers.org/en/v3.0.0/examples/simple.html 2) Adjust window height so that vertical browser scrollbars appear 3) Move the cursor over the map, scroll down for zooming out one step -> whole page will scroll down; expected behavior would be: only map zooming, no page scroll 4) Scroll up for zooming in again, whole page will scroll up

**Comment by cs09g** [comment]
This no longer happens in FF.

**Comment by fredj** [comment]
Thanks for reporting @cs09g , closing this issue
