### ISSUE TITLE
Cannot find an equivalent to the 'loadend' event in OpenLayers 2

### ISSUE THREAD

**Issue by klickagent** [openlayers/openlayers#2832]
I searched the api documentation for a long time and could not find the answer to my question:
What is the equivalent to the OpenLayers 2 event register code for the 'loadend' event?
I basically want to fire a function when all tiles of the baselayer are loaded completely.

(OpenLayers 2 Code: map.baseLayer.events.register('loadend' , false, function(){ alert('tiles loaded'); });

**Comment by tschaub** [comment]
See #3248 for proposed tile loading events for image tile sources.
