### ISSUE TITLE
Export Map - Include scale in on the exported picture

### ISSUE THREAD

**Issue by jtcolton** [openlayers/openlayers#2850]
Is it planned to include the scale of the map on the exported picture file. 

It is nice to have a way to export the map easily but a map without a scale is almost useless.

http://openlayers.org/en/v3.0.0/examples/export-map.html

**Comment by tschaub** [comment]
This sounds like something that should be handled at the application level.

**Comment by ThomasG77** [comment]
Just for a follow up, it's done by ol3-ext if people need it http://viglino.github.io/ol3-ext/examples/map.canvas.control.html
