### ISSUE TITLE
IndexSizeError exceptions in IE when display layers in canvas renderer

### ISSUE THREAD

**Issue by cbertozzi** [openlayers/openlayers#2861]
when displaying more than one WMS/Vector layer, IE raises that exception without draw nothing. Chrome works well in the same OS (Windows 8/8.1)

Exception is raised from "drawImage" function of the context 2d of the canvas. After a brief investigation I got that the source dimension of the image passed in argument, is bigger than the image real dimensions. So, my workaround was the next: 

``` diff
diff --git a/src/ol/render/canvas/canvasreplay.js b/src/ol/render/canvas/canvasreplay.js
index 5d7b35a..485233b 100644
--- a/src/ol/render/canvas/canvasreplay.js
+++ b/src/ol/render/canvas/canvasreplay.js
@@ -285,7 +285,7 @@ ol.render.canvas.Replay.prototype.replay_ = function(
         // Remaining arguments in DRAW_IMAGE are in alphabetical order
         var anchorX = /** @type {number} */ (instruction[4]) * pixelRatio;
         var anchorY = /** @type {number} */ (instruction[5]) * pixelRatio;
-        var height = /** @type {number} */ (instruction[6]);
+        var height = /** @type {number} */ (Math.min(image.height, instruction[6]));
         var opacity = /** @type {number} */ (instruction[7]);
         var originX = /** @type {number} */ (instruction[8]);
         var originY = /** @type {number} */ (instruction[9]);
@@ -293,7 +293,7 @@ ol.render.canvas.Replay.prototype.replay_ = function(
         var rotation = /** @type {number} */ (instruction[11]);
         var scale = /** @type {number} */ (instruction[12]);
         var snapToPixel = /** @type {boolean} */ (instruction[13]);
-        var width = /** @type {number} */ (instruction[14]);
+        var width = /** @type {number} */ (Math.min(image.width, instruction[14]));
         if (rotateWithView) {
           rotation += viewRotation;
         }
```

Hope this helps the developers

**Comment by slonsjo** [comment]
We have the same issue, also see http://stackoverflow.com/questions/24774180/fixed-size-of-an-icon-openlayers3. Recreate by testing with http://jsfiddle.net/6RS2z/8/ and change the size to a greater value.

**Comment by DanielSundberg** [comment]
I've got this as well using a large (1792x1792) SVG. The above patch did not solve my problem. I had to revert to using a 50x50px sized PNG.

**Comment by bencevans** [comment]
We've also been having issues with the Canvas rendering in IE11. Unfortunately the above patch didn't fix it for us either. I've tried setting the imgSize as per #4409 also without luck.

Below i'm printing out the values passed to [`drawImage`](https://github.com/openlayers/ol3/blob/89ebf0a182524610622f124b8a47887013e53bd7/src/ol/render/canvas/replay.js#L354) in src/ol/render/canvas/replay.js

The size of the SVG is milipixels out from the size I've specifies. I shall try changing the SVG sizes and also try using PNGs in place to see if there's any difference.

```js
context.drawImage(image, originX, originY, w, h,
              x, y, w * pixelRatio, h * pixelRatio);
```
<img width="1032" alt="screen shot 2016-12-12 at 11 48 51" src="https://cloud.githubusercontent.com/assets/638535/21098453/3accef2c-c061-11e6-879a-241e4ae9284c.png">

**Comment by bencevans** [comment]
I can also confirm that it works as expected in Edge. However IE11 even acting in Edge mode fails.

**Comment by ahocevar** [comment]
See https://github.com/openlayers/openlayers/issues/6281#issuecomment-268962325, closing as duplicate.
