### ISSUE TITLE
Implement Word Wrap on Text Style

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#2915]
Can't wordwrap for text style be implemented like:

http://jsfiddle.net/BaG4J/2/

??

**Comment by Centai** [comment]
I would also appreciate, if word wrap could be implemented for ol3 since this is the only issue for me, which prevents me from upgrading.

**Comment by 1Map** [comment]
Any feedback on this 5 year old issue?

**Comment by ahocevar** [comment]
You can use a line break (`'\n'`) to break text into lines. And you can use a third party utility to word wrap text as a preprocessing step. So this issue should be fixed.
