### ISSUE TITLE
Viewport issue on various browsers (ie, firefox, safari)

### ISSUE THREAD

**Issue by falkzilm** [openlayers/openlayers#2917]
Hi there,

i created a simple OSM OpenLayers Map, using the whole website to display.
But here the problem occurs, i got a white bar under the map which is approximately around 50-100px in height but with the Mozilla Firefox inspector i only can see that it should differ for around 5px. 

In Google Chrome the problem does not occur for no specific reason.

I attached a screenshot and the HTML as PNG.
![map-html](https://cloud.githubusercontent.com/assets/2149622/4922730/977d7732-6514-11e4-9836-9ac3d264de0b.png)
![bug](https://cloud.githubusercontent.com/assets/2149622/4922734/9e1cca52-6514-11e4-9bab-c792c6f3ad68.png)

**Comment by emilyashley** [comment]
Incase anyone else searches for this, I'm having the same issue of css not affecting the map canvas's height, I think the trick is to utilize updateSize.

my example:
 ```
var setHeight = function(){
        var frameHeight = $(window).height();
        $('#map').css({'height': frameHeight 'px'})
    }
    setHeight();
    map.updateSize();
```
