### ISSUE TITLE
GroundOverlay KMLs are not supported

### ISSUE THREAD

**Issue by stevenpetryk** [openlayers/openlayers#2941]
As far as I can tell, GroundOverlays in KMLs are not supported. I found a pull request https://github.com/ericfong/openlayers/commit/888bacf65d2b6a551662ff4aa7896806e9465461, which is for OpenLayers 2, and which was never merged into the project. I feel like GroundOverlays are not an uncommon feature of KMLs and thus an implementation in OpenLayers would be extremely pertinent.

It seems like it would be similar to parsing Placemarks, which _are_ supported, except the image is scaled to a particular extent on the map. I'll try to make a pull request, but does anybody have a desire for this feature?

**Comment by tamarmot** [comment]
Google Earth Web Plugin is not a solution as it is being permanently deprecated. +1 for adding this feature to openlayers.

**Comment by stevenpetryk** [comment]
Yeah, the deprecation notice was issued in December. Although, I feel like Google may have something similar up their sleeve (based on WebGL, maybe).

**Comment by ponceta** [comment]
If this is developped, it could be great to propose an enhancement on the gdal package to go to the latest version of ol3.
https://github.com/OSGeo/gdal/blob/11ab6f3132d025e9ccdee9d4dda817786cead5b3/gdal/swig/python/scripts/gdal2tiles.py#L1995

**Comment by olegsv** [comment]
Was there any progress with support of GroundOverlay feature on Openlayers?

**Comment by eric-g-97477** [comment]
I would like to see this issue reopened. I am hoping that GroundOverlay support can be added.
