### ISSUE TITLE
canvasFunction_

### ISSUE THREAD

**Issue by xlhomme** [openlayers/openlayers#2951]
Parameters for canvasFunction_ are not well suited. We need to be able to apply functions to get the coordinate from a pixel and pixels from a coordinate
like map.getPixelFromCoordinate / map.getCoordinateFromPixel
Canvas Extend does not take rotation and transalation correctly.

**Comment by hkollmann** [comment]
Hi,

If you look at Antonio's example http://acanimal.github.io/thebookofopenlayers3/chapter03_04_imagecanvas.html you see that map is needed to calculate the correct pixel positions to draw onto the canvas.

The reference to the map comes from outside the canvasfunction. With this it's not possible to share the canvasfunction with different layers.

It would be great if we can have the current map as an Parameter to the canvasfunction.

Best regards
Henner Kollmann

**Comment by fredj** [comment]
> This issue is duplicated with #2984.

**Comment by hkollmann** [comment]
But this issue is not duplicated. In #2984 there is a problem with rotation. Here i would like to have the current map as Parameter to the canvasFunction
