### ISSUE TITLE
ImageCanvas canvasFunction and rotation

### ISSUE THREAD

**Issue by darkzeb** [openlayers/openlayers#2984]
Using canvasFunction and ol.Layer.Image with a ol.Source.ImageCanvas causes problems:
A) with rotation: see http://jsfiddle.net/r9q2f01t/embedded/result/

B) with object placement under Firefox: step to reproduce
1) open Antonio's example http://acanimal.github.io/thebookofopenlayers3/chapter03_04_imagecanvas.html under Firefox 33.1.1
2) zoom / unzoom
3) see that pies are not located at the right place between two zoom/unzoom
The problem B is not reproductible under Chrome.

See this discussion for more details : https://groups.google.com/forum/#!topic/ol3-dev/C_r9MJ2roTY

**Comment by Minishlink** [comment]
Hello,

It seems the issue is not completely fixed... See http://jsfiddle.net/r9q2f01t/3 (I'm using 3.8.2 on this jsfiddle)

When rotating, it can occur that the pie charts move...

And @darkzeb, I'm working on the same project as you: upgrading from 3.1.1 to 3.8.2 doesn't solve the issue. Did you have any luck with it ? (the vs layer being on the wrong position)

**Comment by darkzeb** [comment]
Hi,

The project in which I was using this function is over for a long time and
I don't remember which OL3 version we finally used but it was working
without any problem.

Good luck to you
Seb

2015-08-10 16:32 GMT+02:00 Louis Lagrange <notifications@github.com>:

**Comment by emmanuelmillionaer** [comment]
@Minishlink  How did you solve the rotation problem? I have the same issue! Thanks!

**Comment by emmanuelmillionaer** [comment]
I think the problem In this example: http://jsfiddle.net/r9q2f01t/4/

Is how the distance between the map-extent and the canvas is calculated:
Its not taking the rotation into account:

     http://jsfiddle.net/r9q2f01t/4/

How could we fix that? Thanks

**Comment by Minishlink** [comment]
@emmanuelmillionaer, I unfortunately don't have any fix for this rotation problem. I don't have any clue right now...
[calculcateExtent](https://github.com/openlayers/ol3/blob/dcfeff11bfa8c3285791f1b82a335c844bf95709/src/ol/view.js#L276) seems to get rotation into account, but it may be buggy and I haven't taken the time to look into this.

**Comment by hccampos** [comment]
You basically have to draw everything relative to the center of the canvas and map, rather than using the extent and you need to compensate for the map rotation.

Here is an example: https://codesandbox.io/s/54qk96564k

**Comment by TheCuda** [comment]
@hccampos Check your example again, please. If you zoom out and/or in, the points multiply (I think this wasn't intended). Also if you rotate the map and then move it, the points will not be rendered in the middle of the view.

This example is quite buggy.
![unknown](https://user-images.githubusercontent.com/6231330/36780526-8c7635da-1c73-11e8-8b36-ad7d028829d2.png)

**Comment by hccampos** [comment]
@TheCuda Sorry, I had forgotten to clear the canvas before drawing the points again. If you try again it should work.

**Comment by TheCuda** [comment]
@hccampos That looks much better. Thank you for revising :)
