### ISSUE TITLE
Overview map control ignores base map projection

### ISSUE THREAD

**Issue by relet** [openlayers/openlayers#2998]
..defaults to EPSG:3857. 

IMHO, it should default to the base map projection, and allow a view (or projection) parameter to assign a different view projection.

**Comment by MrJH** [comment]
+1 for #3007

**Comment by relet** [comment]
Oh, I didn't notice this hadn't merged. Can someone help me with this?

**Comment by MrJH** [comment]
Seems that there is a merge conflict on #3007  - that's why it hadn't merged before.
