### ISSUE TITLE
pinch zoom broken in Safari (7.1.2)?

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#3054]
Has anyone else noticed this, pinch zooming seems broken in Safari?

I also get in this mode now on pinch zoom out:

![screen shot 2014-12-16 at 16 46 53](https://cloud.githubusercontent.com/assets/319678/5456352/32438952-8543-11e4-98af-240e8020a2a6.png)

**Comment by klokan** [comment]
Suggested implementation in #3817
