### ISSUE TITLE
Slow load WMS tile requests lock browser from other HTTP requests

### ISSUE THREAD

**Issue by crh3675** [openlayers/openlayers#3063]
I have implemented code to load TileWMS data.  Sometimes our development WMS service is slow to respond. This would not be a huge issue except that we can't perform other HTTP requests from within the browser until all WMS tiles have loaded.  It is almost like the WMS calls become synchronous in nature. 

To reproduce, put a web form on the same page that loads an OL3 map using TileWMS and try to submit the form before the map has rendered.

Is there a method to cancel the WMS requests before they have completed?

**Comment by dropyghost** [comment]
Can you share some tips in the load code?, Im also having an issue with slow WMS service, where ol get an invalid tile and never try to get a right one. The only way is restarting the app and doing zoom and panning really slow.
