### ISSUE TITLE
Add an encodeBBox param

### ISSUE THREAD

**Issue by stewberticus** [openlayers/openlayers#3092]
ol3 now forces bbox's to use url encoding we should allow the dev to specify. Especially when using version 1.1.1 of WMS where the commas are actually part of the specification

**Comment by sfreytag** [comment]
I've run into an example of this, trying to use a WMS 1.1.1 server from ol6.3.1. I had a read around this, #1441 and #8635. This  seemed like the best one to carry on the discussion, given it had the most recent activity.

I've monkeypatched my ol/source/TileWMS.js `getRequestUrl_` method to have a fix where BBOX is not encoded. If a PR is still accepted, I can work this up into one.
