### ISSUE TITLE
Image resolution not separated for source.ImageStatic

### ISSUE THREAD

**Issue by lhethert** [openlayers/openlayers#3112]
Hi there,

Apologies if this has been raised before, but I couldn't find an existing ticket, and this seems like a fairly simple fix to make.

When adding an ImageLayer with an ImageStatic source to a map, I can correctly specify the extent for the image, however, the image extends beyond the extent specified for the image. The image is not square. I've found a solution to the issue, specified here:

https://groups.google.com/forum/#!searchin/ol3-dev/imagestatic/ol3-dev/9RUM9ljssVM/KNyPibI-wyEJ

And the code modifications they suggest work correctly.

Not-fixed:
![screen shot 2015-01-12 at 4 40 34 pm](https://cloud.githubusercontent.com/assets/4288888/5699361/cf4a71fc-9a79-11e4-9e03-c1223af056e1.png)

Fixed:
![screen shot 2015-01-12 at 4 39 15 pm](https://cloud.githubusercontent.com/assets/4288888/5699351/91776894-9a79-11e4-9d8f-8ecc58c7a323.png)

Let me know if you need any more info.
Cheers,
Lachlan Hetherton
lhethert@fastmail.fm

**Comment by ahocevar** [comment]
Ideally, you could create a pull request with that fix.
