### ISSUE TITLE
Properly separate dependencies and devDependencies in package.json

### ISSUE THREAD

**Issue by aindlq** [openlayers/openlayers#3157]
Is it necessary to have 'closure-util', 'jsdoc' and all other bunch of stuff in dependencies, maybe it make sense to move them to devDependencies. See https://docs.npmjs.com/files/package.json#devdependencies

I assume people who are using npm openlayers package really need only content of dist folder, and don't need to build everything on they own, right?

**Comment by elemoine** [comment]
There are people who want to get openlayers using npm, and build openlayers together with their app, or create a custom build of openlayers.

**Comment by artemkozlov** [comment]
This is perfectly fine. They can just install it with 'npm install openlayers --dev' and get all devDependencies.

**Comment by elemoine** [comment]
I'm not a npm/node expert. If openlayers is a node dependency of my project, how do I specify in my project's `package.json` file that I also want to get the dev dependencies of openlayers.

**Comment by artemkozlov** [comment]
Basically project's package.json looks like this one:

{
  "dependencies": {},
  "devDependencies": {}
}

with  `npm install openlayers --save`, openlayers will be added to `dependencies` and npm will fetch only openlayers own `dependencies` it won't fetch `devDependencies`. With  `npm install openlayers --save-dev` it will add openlayers to `devDependencies` and fetch everything.

**Comment by artemkozlov** [comment]
@tschaub Any comments on this?

**Comment by claycephas** [comment]
Is there a separate npm package that will give only the built openlayers js? Consumers of openlayers shouldn't have to install all the build dependencies just to use the compiled (dist) openlayers package.

**Comment by aindlq** [comment]
Just want to bring this up one more time. It is especially relevant for people who are trying to use jspm as package manager (see https://github.com/jspm/registry/issues/885 and https://github.com/jspm/jspm-cli/issues/1309).

> dependencies are required to run, devDependencies only to develop, e.g.: unit tests, Coffeescript to Javascript transpilation, minification

- https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies/22004559#22004559

If people a willing to accept this change I can provide PR.

**Comment by ahocevar** [comment]
One caveat here: The OpenLayers npm package does not ship with build artefacts, so everything that's needed to build `ol.js`, `ol-debug.js` and ol.css is in `dependencies`, so the postinstall task can build the artefacts.

**Comment by aindlq** [comment]
@ahocevar  I've just checked latest tar.gz from npm and there is dist folder with ol.css,  ol-debug.css,  ol-debug.js,  ol.js.

**Comment by ahocevar** [comment]
@aindlq Thanks for investigating! In this case, a pull request would be appreciated.

**Comment by probins** [comment]
I think there are 3 groups of people here:

1. those who only want the built versions
2. those who want to create a custom build
3. those who want to run the full CI, including PhantomJS and all the rest

Those in (1) don't want any dependencies (apart possibly from proj4js) and don't want the source either; those in (2) want the source and the compiler/closure-util, but don't want jsdoc etc either.

I'd agree that the current setup doesn't really suit (1) or (2).

**Comment by probins** [comment]
ah, sorry, just remembered that creating a custom build needs jsdoc to create `info.json`, so perhaps what's needed is a separate runtime package with just the built versions

**Comment by ahocevar** [comment]
> ah, sorry, just remembered that creating a custom build needs jsdoc to create info.json, so perhaps what's needed is a separate runtime package with just the built versions

But even in this case it's ok to move it to devDependencies, right? Or am I missing something?

**Comment by probins** [comment]
the current package is ok for custom builders, as you can just install dependencies. devDependencies is large because of PhantomJS etc, which you only need if you're running the full CI with tests.

**Comment by ahocevar** [comment]
Not sure I understand, but if there are ways to improve the experience for (1) and (2), I'd still say a pull request would be desirable. I don't think we need to cover (3) with the npm package, because for that, users would clone the git repo.

**Comment by ahocevar** [comment]
> I don't think we need to cover (3) with the npm package, because for that, users would clone the git repo.

Which implies that everything needed for (3) should be in `devDependencies`, and everything needed for (1) and (2) in `dependencies`, right? Isn't that what we currently have?

**Comment by probins** [comment]
If you clone the repo, you still need to run `npm install`, which comes from `package.json`. The point is that (1) don't need what is currently in `dependencies`.

**Comment by ahocevar** [comment]
Ok, so let's keep things as they are, because we want to encourage users to do (2), i.e. create custom builds.

**Comment by probins** [comment]
I assume that (1) are wanting to install as part of a server-side build/bundle process, like the jspm mentioned, so would see a separate runtime package as appropriate for that.

There will be more variations as the dependency on Closure library and compiler goes.

**Comment by probins** [comment]
I'm thinking that (1) could be handled without too much effort, and without needing to publish anything on npmjs. Each release currently includes a dist zip, like https://github.com/openlayers/openlayers/releases/download/v3.20.1/v3.20.1-dist.zip. If this included a basic package.json (no dependencies), then people could download it, unzip it, and `npm install` could use the folder as the dependency in their project. Alternatively, a separate tarball with a package.json could be created, which npm could download as a package dependency (AFAIK, npm can't handle a zipfile, only a tarball). This could then be documented under https://openlayers.org/download/.

**Comment by BasieP** [comment]
Oke so right now the given option for (1) is to download a zipfile every release. Unzip it by hand and put it somewhere locally (in all your local projects if you don't have a nexus)
Then commit those files in all your projects and start builds. 

Now, given that (1) is by far your biggest group of users, why do you let them go through all that? 
Why not let (2) or (3) go through some extra steps? Those groups are WAY smaller, and it would be reasonable for those groups too take that extra effort since they are more accustomed too those special steps anyway. 

From a business perspective the choice right now seems rather harch on your customers..

**Comment by BasieP** [comment]
@ahocevar can you point me to some documentation on the custom build option? So far i have lots of trouble getting dependencies (yes cooperate walls) and right now the latest closure compiler is not getting through our firewall/proxy making like 5 programs relying on openlayers unreleasable... 

Problems like that scare big spenders away from projects like openlayers and here i have seen some colleagues lean more towards leaflet because 'it works' (not wondering why openlayers doesn't). 

I still don't see a scenario where you (as a developer of a product that uses openlayers) would want to have all those depencies.. So i'm probably missing something. 

Therefor again the question: is there a document or page where i can learn about that concept. 
As you said earlier in this topic: you like to encourage people from using it. 
I'm curious.

**Comment by probins** [comment]
https://openlayers.org/en/latest/doc/tutorials/

**Comment by ahocevar** [comment]
@BasieP Consider using the [ol](https://npmjs.com/package/ol) package instead. Works like any modern JavaScript package with standard bundlers and minifiers, so you don't have to struggle with Closure Compiler.

**Comment by tschaub** [comment]
Yes.  Please use the ol package it includes only the dependencies that it uses.  And your application can do the same.
