### ISSUE TITLE
Include generated extern in release

### ISSUE THREAD

**Issue by olivergeorge** [openlayers/openlayers#3202]
Currently there's a node task to generate an openlayers extern file for use in other google closure compile pipelines (#2479).  This is great but it's not included in the release zip which adds work downstream.

Seems like it would logical to add this to the release process so it's available in the release zip file.

**Comment by olivergeorge** [comment]
Hi @ahocevar - Looks like you wrote the generate-externs.js script.  I was wondering if you would mind commenting on this issue.

**Comment by elemoine** [comment]
I guess we can add the externs file.

Do you Closure Compiler for your application code? If so, why don't you compile your app and ol3 together? Just curious.

**Comment by olivergeorge** [comment]
That would be fantastic.  Thank you.

My app is a clojurescript app and while the clojurescript compiler uses
Google Closure it has more strict requirements on the source code.

(Ah, i see you were kind enough to reply to my ol3-dev post.  Thanks for
that.)

The other thread of discussion related to this is associated with  packaged
up for use with clojurescript apps.

https://github.com/cljsjs/packages/issues/23

Perhaps the CLJSJS guys will find a way to reduce the strictness so that
OL3 can be compiled natively.

**Comment by ahocevar** [comment]
Adding the externs file to the distribution would be no problem. @olivergeorge, would you be able to create a pull request for that?

**Comment by olivergeorge** [comment]
Thanks @ahocevar 

I'm quite unfamilar with your build process.  Mind giving me a few clues.

Is this vaguely heading in the right direction...

```
diff --git a/build.py b/build.py
index 603a975..cc22c1d 100755
--- a/build.py
+++ b/build.py
@@ -208,6 +208,15 @@ def build_ol_js_map(t):
     _build_js(t)


+def _build_ext_js(t):
+    t.run('node', 'tasks/build.js', 'build/ol.ext.js')
+
+
+@target('build/ol.ext.js', SRC, SHADER_SRC, 'config/ol.json', NPM_INSTALL)
+def build_ol_ext_js(t):
+    _build_ext_js(t)
+
+
 @target('build/ol-debug.js', SRC, SHADER_SRC, 'config/ol-debug.json',
         NPM_INSTALL)
 def build_ol_debug_js(t):
```

**Comment by olivergeorge** [comment]
Hi Andreas,

Looks like we've worked out native compilation so this is no longer a
blocker for us.  I do think it's potentially a good idea for others.  It
was kind of confusing for me to find the externs necessary to compile
openlayers in the release but not the externs necessary to compile
alongside openlayers.  I'm too intimidated by your release process to help
though.  Apologies.  Hopefully someone more familiar is willing to make the
change.

Best of luck
cheers, Oliver

**Comment by Chris-Dixon** [comment]
Adding the externs to the distribution would be a great help for me as well.

**Comment by fredj** [comment]
the externs are gone: #8273
