### ISSUE TITLE
ol.View#fitGeometry issue with ol.geom.GeometryCollection

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#3217]
`ol.View#fitGeometry`calls [geometry.getFlatCoordinates](https://github.com/openlayers/ol3/blob/master/src/ol/view.js#L482) but the function is not defined for `ol.geom.GeometryCollection`

**Comment by DanielDornhardt** [comment]
I just ran into the same thing I think, wanting the map to zoom+center around all of my features.

**Comment by bartvde** [comment]
@malaretv is this also in scope for your fitGeometry changes?
