### ISSUE TITLE
Documentation for ol.proj.Projection.prototype.getPointResolution

### ISSUE THREAD

**Issue by bill-chadwick** [openlayers/openlayers#3285]
A small thing ...

The current documentation for ol.proj.Projection.prototype.getPointResolution reads

/**
- Get the resolution of the point in degrees. For projections with degrees as
- the unit this will simply return the provided resolution. For other
- projections the point resolution is estimated by transforming the center
- pixel to EPSG:4326, measuring its width and height on the normal sphere,
- and taking the average of the width and height.
- @param {number} resolution Resolution.
- @param {ol.Coordinate} point Point.
- @return {number} Point resolution.
  */

The function description is a bit wrong. It should be something like

/**
- Get the resolution of the point. For projections with degrees as
- the unit this will simply return the provided resolution. For other
- projections the point resolution in projection units is estimated 
- by transforming the center pixel to EPSG:4326, 
- measuring its width and height on the normal sphere,
- and taking the average of the width and height.
- @param {number} resolution Resolution.
- @param {ol.Coordinate} point Point.
- @return {number} Point resolution.
  */

The function is useful for determining the nominal resolution of a point on the Web Mercator projection. With that projection, resolution in metres per pixel changes with latitude. The function is used, for example, in calculating the length of the bar in the ScaleLine control.

**Comment by bill-chadwick** [comment]
There are perhaps some further issues with this function. 

For both ol.proj.EPSG3857 and ol.proj.EPSG4326 it is overridden.

There are other projections, EPSG:27700 (British National Grid) and UTMs that would benefit from overriding this in the same way.  In these particular cases the function would simply return the resolution unchanged (as is done for EPSG4326).
 
There is currently no easy way of doing this for proj4 based ol.proj.Projection objects. This could be addressed by adding say a fixedResolution attribute to ol.proj.Projection (with getters and setters) or making it possible to provide a replacement getPointResolution function (again with a getter and setter).

**Comment by ahocevar** [comment]
I think both suggestions would make sense. For making the built-in `getPointResolution` method more useful, a `pointResolutionEqualsResolution` and a `sphere` option would make sense (e.g. if you want a scaleline control on the Mars). For being able to provide a custom `getPointResolution` method, it would be enough to add an `@api` annotation to it and add a `getPointResolution` option to `olx.proj.ProjectionOptions`.

@bill-chadwick Would you be able and willing to create a pull request for that?

**Comment by bill-chadwick** [comment]
Andreas,

Willing - yes, able - maybe.

With the olx constructor option for a custom method I can see how one might
proceed along the lines of

http://openlayers.org/en/v3.3.0/examples/wms-custom-proj.js, providing a
function as a constructor option

With code like the below,

proj4.defs("EPSG:27700", '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717' +
    ' +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs');

/* limit the bounds of the UK projection for the graticule */
ol.proj.get('EPSG:27700').setExtent([0, 0, 800000, 1400000]);
ol.proj.get('EPSG:27700').setWorldExtent([-10, 49, 6, 63]);


I think we would need something like

ol.proj.get('EPSG:27700').setGetPointResolutionFunc(myFunc);

BTW the docs for WorldExtent should probably state that extent
coordinates must be EPSG:4326

I would like to concentrate on finishing my update/generalization of the
ol.Graticule before embarking on this (though the two are related).
I feel I am nearly there with it.

Perhaps the sphere (Mars) projection option could be left for another time.

Bill

**Comment by ahocevar** [comment]
Sounds good. Whatever you're able to contribute will be much appreciated, and the sphere option can definitely wait.

**Comment by bill-chadwick** [comment]
I think a setGlobal function is needed for proj4 constructed projections.

**Comment by ahocevar** [comment]
We could also flip the coin and support something like
```js
ol.proj.createFromProj4({
  code: 'EPSG:27700',
  global: false,
  getPointResolution: function(resolution) { return resolution; }
});
```

**Comment by bill-chadwick** [comment]
That looks sensible. I gues we should keep the getters and setter too.

The next bit is slightly off topic - please move it to a new issue if appropriate

I also want to factor the basic path interpolation routine ol.geom.flat.geodesic.line_ out of geodesicflatgeom.js as it is a generalised method of converting an a-b path from one projection to another (to a supplied accuracy). I think perhaps, namespace 'ol.geom.flat.path', public function name 'transform' and sourcefile name 'pathflatgeom.js'.  geodesicflatgeom.js would then use the transform function in the new namespace. What do you think ?

The routine works well transforming a British Grid (EPSG:27700) graticule to EPSG:3857.
I plan also to use it for to find parallel paths separated by a fixed distance for the EPSG:3857 graticule.

**Comment by bill-chadwick** [comment]
The path transform might actually sit best in the ol.proj namespace as a function named transformPath, alongside e.g. transfromExtent.

**Comment by ahocevar** [comment]
Moved the off-topic path transformation piece to #3317 for discussion.

**Comment by bill-chadwick** [comment]
Some more thoughts on ol.proj.Projection ...

Whilst working on a generalised graticule it has come to my attention that non-global projections might need to decline to transform from EPSG:4326, outside their worldExtent, or to EPSG:4326, outside their extent. Likewise getPointResolution might need to return invalid if the point requested lies outside the projection's extent. Some non-global projection mathematics, such as the Transverse Mercator EPSG:27700, is likely to behave improperly well outside it's intended area of use. 

Do you have any suggestions for how this might be handled or if indeed any attempt to do so should be made ? A low perfomance impact solution is of course desiarable.

**Comment by bill-chadwick** [comment]
I hope this is what is needed.

https://github.com/openlayers/ol3/compare/master...bill-chadwick:master

Its hard to do the tests update on Windows as the build's test system does not seem to work on Windows.

**Comment by ahocevar** [comment]
Thanks a lot for bearing with me, despite all the issues you've been facing. Be assured that your work is much appreciated.

Looking at your diff now.

**Comment by ahocevar** [comment]
The diff looks good. I think `#setOptions()` the way it is now is a bit of overkill. If we want that, we can make ol.proj.Projection inherit from ol.Object. So for now it would be better to remove `#setOptions()`. The rest looks good, just remove the stable marker from any new methods that you introduced. Then you can safely create a pull request from your branch. Thanks again for the great work!

**Comment by bill-chadwick** [comment]
Thanks for the encouragement.

I will remove the setOptions and stable. 

If the options parameter to addProj4Projection  were made non optional, then the projection code could be got from them rather than from a separate parameter. That way folk might be encouraged to consider further ol3 appropriate, options beyond just the projection code. If the graticule is used, projection extents are vital.

The new addProj4Projection method should I think, become the standard way for adding a proj4 projection. If so, then proj.jsdoc may need updating - that is the bit that goes

Note that Proj4js does not support projection extents. If you want to add one for creating default tile grids, you can add it after the Projection object has been created with setExtent, for example, ol.proj.get('EPSG:1234').setExtent(extent).

New tests for ol.proj.Projection are still TODO. I may PR without them If I continue to struggle getting them to run on Windows.

BTW the projection extent in the Sphere Mollweide example is wrong. It should be 

sphereMollweideProjection.setExtent([
-9009954.605703328 * 2, -9009954.605703328,
9009954.605703328 * 2, 9009954.605703328]);

as the projection has an extent that is twice as wide as it is high. I will do a PR to fix that when I eventually PR my graticule work.

**Comment by ahocevar** [comment]
> If the options parameter to addProj4Projection were made non optional, then the projection code could be got from them rather than from a separate parameter. That way folk might be encouraged to consider further ol3 appropriate, options beyond just the projection code. If the graticule is used, projection extents are vital.

Very good point! Thinking that one step further, the `ol.proj.Projection` constructor could take care of checking for proj4 projections. Then the proj4 specific code from `ol.proj.get()` could be moved to the constructor, and you could always create a projection using the constructor instead of being forced to use `ol.proj.get()` or `ol.proj.addProj4Projection()` when you want proj4 transforms added:
```js
proj4.defs('EPSG:1234', epsg1234def);
var epsg1234 = new ol.proj.Projection({
  code: 'EPSG:1234',
  extent: [1, 2, 3, 4]
});
```

**Comment by bill-chadwick** [comment]
I think that for backwards compatibility the proj4 code will have to be
left in ol.proj.get for now.

If we do proj4 work in the ol.proj.Projection constructor, why not make the
proj4 definition just be another olx.ProjectionOptions item ? something like










*var epsg27700 = new ol.proj.Projection(   {          code:
'EPSG:27700',       proj4: '+proj=tmerc +lat_0=49 +lon_0=-2
+k=0.9996012717' +                ' +x_0=400000 +y_0=-100000 +ellps=airy
+datum=OSGB36 +units=m +no_defs',       extent: [0, 0, 800000,
1400000],       worldExtent: [-10, 49, 6, 63],       global: false,
getPointResolution: function (resolution, point) { return resolution; }
});*

With that approach, folk might worry about what happens to the projection
when it goes out of scope.
I think in balance that's why I favour ol.proj.addProj4Projection as it
'adds' the projection to ol.proj.projections_
library. we would have









*/*** Create a proj4 projection and add it to the projection library*
@param {(string|Object)} proj4def Proj4 definition string,* @param
{olx.ProjectionOptions} options Projection options, code must be
specified.* @return {ol.proj.Projection | undefined} Projection.*
@api*/ol.proj.addProj4Projection = function(proj4def, options) {*

*...}*

used thus









*ol.proj.addProj4Projection(    '+proj=tmerc +lat_0=49 +lon_0=-2
+k=0.9996012717' +    ' +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36
+units=m +no_defs',   {   code: 'EPSG:27700',       extent: [0, 0, 800000,
1400000],       worldExtent: [-10, 49, 6, 63],       global: false,
getPointResolution: function (resolution, point) { return resolution; }
});*

**Comment by bill-chadwick** [comment]
Or perhaps you were thinking ol.proj.addProjection would be called after
constructing a projection ?

**Comment by ahocevar** [comment]
The change I have in mind would be backwards compatible. `ol.proj.addProjection` would also be called in the constructor. I'm trying to come up with a pull request for just this one change, so don't worry about it for now.

**Comment by ahocevar** [comment]
@bill-chadwick #3362 is what I had in mind.
