### ISSUE TITLE
Add padding to ol.View

### ISSUE THREAD

**Issue by TobiasLohner** [openlayers/openlayers#3294]
Quite simmilar to http://openlayers.org/en/v3.2.1/examples/center.html, i'd like to pad the whole view to a smaller part of the map canvas, so every fitGeometry/fitExtent() call and all controls would use that padding.

There should be a ol.View.setPadding() method for dynamic adjustments.

See this example as a usecase:
![Restricted View](https://cloud.githubusercontent.com/assets/609110/6428191/adef57b8-bf98-11e4-918f-538ef4cb9eef.png)

**Comment by christdg** [comment]
Ive come up with a work around that does the job.

**Comment by jalik** [comment]
I agree with @TobiasLohner, I recently needed this feature, but giving the padding on every fitGeometry() is painful so I didn't go further... I am waiting for something similar to that : https://developers.google.com/maps/documentation/android/map#map_padding

I don't know how OL3 works under the hood but it should be easy to implement as it's just a matter of modifying the view's virtual size.

**Comment by sookoll** [comment]
I need it basically every project with ol. fit to extent is covered but setCenter, setZoom, animate are not.

**Comment by jalik** [comment]
Hello, just to know if this feature request has found a solution since its creation ?
It's still something really useful, to be able to set a virtual padding on the map to recalculate center accordingly. Thank you.

**Comment by isokosan** [comment]
I've also had to write a custom solution for this but for things like setPosition on overlay elements I'm still having trouble hacking my way around. It would be awesome if we could have this functionality.

Thanks for the great work OL team, amazing product!

**Comment by peteresteris** [comment]
Greetings. isokosan, I am trying with this option and it doesn't work for me. I need to put a map with padding [0,0,0,0] and later change it to [700,0,200,0]. But I didn't  see the change. If I begin with first padding, it remains that way and viceversa.

**Comment by ahocevar** [comment]
The View now has a padding option. See   https://github.com/openlayers/openlayers/pull/11755
