### ISSUE TITLE
Support opacity in all styling rules

### ISSUE THREAD

**Issue by vmx** [openlayers/openlayers#3347]
Currently some styling rules don't support the `opacity` property, for example `ol.style.Fill` or `ol.style.Circle`. In order to make it transparent you would need to use an `rgba()` color. This feels counter-intuitive to me as you have an `opacity` property on `ol.layer.Vector`.

In addition the styling feels a lot like CSS which also supports the `opacity` property.

**Comment by bartvde** [comment]
I agree with this, I think we have discussed it in the past but not everyone was in favour or something

**Comment by spyroSlevin** [comment]
Hi vmx, so, its nice to see that  I am not the only one with that issue. Check my [suggestion](https://github.com/openlayers/ol3/issues/4315) and this [SO issue](http://stackoverflow.com/questions/33323119/set-opacity-with-color-literal-in-openlayers-style)
