### ISSUE TITLE
Points in KML are not rendered as push-pins (compare to Google Earth)

### ISSUE THREAD

**Issue by JayBlanchard-FugroSDES** [openlayers/openlayers#3371]
When importing KML with distinct coordinated for points OL3 does not render the push-pin (default marker) indicating those points.

**Comment by bartvde** [comment]
Can you share a KML file that exhibits this?

**Comment by JayBlanchard-FugroSDES** [comment]
https://gist.github.com/JayBlanchard-FugroSDES/f53daede0a64690a0040.js

**Comment by JayBlanchard-FugroSDES** [comment]
https://gist.github.com/JayBlanchard-FugroSDES/f53daede0a64690a0040

**Comment by gberaudo** [comment]
I confirm the provided KML displays in google earth.
However, the OL3 KML formatter outputs no features.
See initial discussion at https://groups.google.com/forum/#!topic/cesium-dev/isvSJHR5CZo.
