### ISSUE TITLE
OGC and CQL filters doesn't work with geoserver if there is a national character in a condition

### ISSUE THREAD

**Issue by m407** [openlayers/openlayers#3478]
``` xml
<ogc:Filter xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns="http://www.opengis.net/ogc">
  <ogc:PropertyIsLike escape="\" singleChar="_" wildCard="%">
    <ogc:PropertyName>name</ogc:PropertyName>
     <ogc:Literal>%Ё%</ogc:Literal>
  </ogc:PropertyIsLike>
</ogc:Filter>
```

Such filter shows nothing when applied to a layer in a geoserver layer preview (it uses ol3 in its latest version for now 2.7.0). With ASCI characters everything works fine.
The reason is that the request is sent by GET method where all parameters are URL-encoded and geoserver fails to decode them correctly. 
The good option would be using POST method when sending request.

**Comment by bartvde** [comment]
cc @jodygarnett @aaime we should talk about at which level to fix this?

**Comment by jodygarnett** [comment]
It looks like this should of been raised as a GeoServer issue?
