### ISSUE TITLE
The modify interaction should not add and remove a vertex on a single click

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#3487]
When using the modify interaction, a `pointerdown` event results in a vertex being added to a geometry.  A `singleclick` results in a vertex being deleted from a geometry.  So when a user clicks on a segment of a line or polygon, we first add and then remove a vertex.  This means the geometry revision is incremented twice, and anybody interested in monitoring whether geometries are being revised will be mislead.

If we want to keep the same behavior (no point added for click), we could wait until a move event to insert the vertex.  If we want to change the behavior so that a point is added for a click, we may have to track the sequence of events and modify the delete condition so we don't delete on `pointerdown`, `pointerup`, `singleclick` (with no other events in the sequence).

**Comment by probins** [comment]
I think this one was fixed with #3635
