### ISSUE TITLE
create JSFiddle does not take into account url params

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#3491]
So if you are viewing an example with the DOM renderer for example, the JSFiddle will be the default canvas renderer instead. Maybe we don't want to support this though. Just opening up for discussion.

http://openlayers.org/en/master/examples/simple.html?renderer=dom

**Comment by ahocevar** [comment]
I made it so the exampleNS renderer code is removed from the example JS on purpose. It is mostly a testing feature IMHO, not something we want our users to do. So I'd appreciate if things could stay as they are.

**Comment by bartvde** [comment]
cool, closing as WONTFIX

**Comment by ahocevar** [comment]
I see now what you meant. It would be possible to change the map configuration in the example code snippet with client side code to match the renderer specified in the command line. I'm reopening in case someone wants to do this.

**Comment by jonataswalker** [comment]
A little bit off topic, but what about the "extras files"? Like 'data/kml/2012_Earthquakes_Mag5.kml' loaded in the [Earthquake Clusters](http://openlayers.org/en/v3.5.0/examples/earthquake-clusters.html)
