### ISSUE TITLE
Zoom controls don't listen to touchend

### ISSUE THREAD

**Issue by dteunkenstt** [openlayers/openlayers#3500]
On touch devices, the zoom buttons don't loose focus after being tapped.
Looking into the code, I figured it would be an easy fix, because the buttons only listen to mouseout and focusedout, but adding touchend still didn't result in a loss of focus.

Currently, the code in ol.control.Zoom is:

``` javascript
 goog.events.listen(inElement, [
   goog.events.EventType.MOUSEOUT,
    goog.events.EventType.FOCUSOUT
  ], function() {
    this.blur();
  }, false);
```

I verified: this.blur() gets called when goog.events.EventType.TOUCHEND has been added, but to no avail. You actually need to tap somewhere else for the focusout to kick in, after which the this.blur() does work. I'm not sure where to continue.

**Comment by pgiraud** [comment]
Looks like the c7a3fcd426d32aca06c67bbef2be5f0511ae7659 as something to do with this.

**Comment by fredj** [comment]
On mobile devices, the default behavior is to keep the focus after a touch.

Example: See http://getbootstrap.com/css/#buttons-options

**Comment by fredj** [comment]
Or http://openlayers.org/en/master/examples/animation.html (the buttons below the map)

**Comment by pgiraud** [comment]
You're right, I figured that out too. But that's a bit annoying and I wished we could prevent this default behavior.

**Comment by fredj** [comment]
reminder: it was added to workaround an issue with chrome 33. See #1761

**Comment by fredj** [comment]
Leaflet handles it by [focusing the map](https://github.com/Leaflet/Leaflet/blob/master/src/control/Control.Zoom.js#L68) after a click on the button
