### ISSUE TITLE
jsFiddle does not work on iOS

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#3501]
![img_1860](https://cloud.githubusercontent.com/assets/319678/7022445/2eb8c78e-dd2c-11e4-9192-47cedb41cb84.PNG)
The code block seems to be encoded or something.

**Comment by ahocevar** [comment]
But the result works - I think this is not something we can fix on the OpenLayers side.

**Comment by fredj** [comment]
jsFiddle is not used anymore, closing
