### ISSUE TITLE
setStyle function does not receive same argument regarding ol.Feature or ol.layer.Vector

### ISSUE THREAD

**Issue by mylen** [openlayers/openlayers#3502]
I am using a custom style that render the feature appearance differently in function of the feature geometry.

I am using a featureStyleFunction as described in the API:

> ol.feature.FeatureStyleFunction()
> 
> src/ol/feature.js, line 295
> A function that takes a {number} representing the view's resolution. It returns an Array of > ol.style.Style. This way individual features can be styled. The this keyword inside the function references the ol.Feature to be styled.

I am using setStyle on a vector and on a feature regarding the context. 

1- When drawing the feature, I am setting it's style on drawend event:

```
olDraw.on('drawend', function(e) {
    e.feature.setStyle(mapCtrl.getDefaultStyle(e.feature));
}, this);
```

2- When loading the feature from my data file, I am using that code:

```
  vector.setStyle(this.getDefaultStyle());
```

In the case 1, the style function is called with the **feature** as parameter.
In the case 2, the style function is called with the **resolution** as parameter. And the **this** variable is a reference to the feature.

I therefore check the type of the parameter in my function likewise:

```
getDefaultStyle: function() {
  //...//
  return function(feature) {
    if (!(feature instanceof ol.Feature)) {
      feature = this;
    }
    //...//
  }
```

The API documentationon style function attached to a vector does not exists at the time I am writting that issue:
http://openlayers.org/en/v3.4.0/apidoc/ol.style.html#StyleFunction

**Comment by fredj** [comment]
fixed with #6413
