### ISSUE TITLE
Enhance CONTRIBUTING.md

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#3519]
With:

1) at the sprint we added assertion messages for all assertions, so please when you add a new assertion, also add the message for those
2) any method with the @api annotation must have a good one sentence plain text description. Additional detail is great if it adds value. It's also nice to use full sentences.
3) all examples (also the ones in existing pull requests) must use the new templating system for details see: https://github.com/openlayers/ol3/blob/master/examples_src/readme.md
4) pull requests now show increase or decrease in test coverage, if test coverage drops below an overall threshold (which we have currently set at 65%), the PR will fail. It would be good wherever possible to increase test coverage with your PR of course, and the output from istanbul / coveralls can provide useful insights into what is tested (which might be different than what you expect for some cases). To run locally use npm install followed by npm run test-coverage (or ./build.py test-coverage) and check the HTML output in the coverage directory with a browser.

**Comment by marcjansen** [comment]
:+1:

**Comment by elemoine** [comment]
Sounds good. I'd just not write "at the sprint" in the CONTRIBUTING.md doc. But maybe it's obvious...

**Comment by bartvde** [comment]
Right I only copy-pasted this in an issue so I don't forget about it, will change the wording.

Also need to revisit the structure of CONTRIBUTING.md maybe a bit?

**Comment by tschaub** [comment]
I think the `CONTRIBUTING.md` doc is becoming (or at risk of becoming) a barrier to contributing.  I think it's a good idea that we try to document everything, but I don't think everything should continue to go in this same doc.  While it is just a naming thing, I'd be more in favor of dumping everything into a reference `manual.md` and keeping `CONTRIBUTING.md` very succinct.

**Comment by bartvde** [comment]
I agree on the overwhelming part
