### ISSUE TITLE
Node driven development environment

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#3532]
We've been slowly transitioning to Node based tasks for too long, and we're in an awkward state where not everybody is clear on where things should be done (`build.py` or a Node task for example).  Here's my proposal for how the development environment should work.
## System dependencies
- Node >= 0.10 (for all dev related tasks)
- Java >= 1.7 (for the compiler)
### Download & install
- Clone the repo (or if you don't have git, download an archive)
- Run `npm install`

This installs all project dependencies locally.
### Run the tests
- Run `npm test`

This runs a linter and then executes all tests (in whatever scriptable browser can run all tests).  Setting an environment variable can run an extended test suite.  For example, on Travis we would build everything and assert that the compiler doesn't complain with something like `OL_EXTENDED_TESTS=true npm test`.

The only prerequisite to running `npm test` is to download/clone the repo and run `npm install`.
### Start a development server
- Run `npm start`

This builds the examples, starts a development server, and starts watching files.  The development server can be used to run examples and the tests.  When source files change, examples are rebuilt (if appropriate), and any attached browsers reload.

The only prerequisite to running `npm start` is to download/clone the repo and run `npm install`.

These primary lifecycle tasks could be done _without_ installing Java assuming a developer doesn't run the extended tests (that make assertions about builds making it through the compiler).  So we could have contributors to the library that would only need to have Node installed.  This is fairly common for JavaScript developers.

The above tasks could also be accomplished without Python if we move away from `gjslint`.  I'm not advocating for this right now, but I do intend to move to ESLint and think we can get better functionality from that than `gjslint`.
## Additional development tasks

Developers should also be able to build profiles of the library, build the API docs, and more (add your suggestions below).  These things can be (and already are) authored as separate Node based tasks.

If there are tasks that need to be frequently repeated during development and greatly benefit from being run only on the necessary files, the tasks should accept the appropriate arguments (like a file list).  And we could have a Makefile that facilitates incremental task runs.

**Comment by elemoine** [comment]
That sounds good to me. A few minor comments below.

> Run npm test

So, if I understand correctly, you'd like that `npm test` basically replace `build.py check`. So the developer would run `npm test` before creating a PR.

We could still have a `check` target that runs `OL_EXTENDED_TESTS=true npm test`, which we would need anyway for the `ci` target (see below). 

 

> For example, on Travis we would build everything and assert that the compiler doesn't complain with something like OL_EXTENDED_TESTS=true npm test.

Ok, but for Travis, I guess we could still have a `ci` target (`make ci`) that takes care of everything. 

And developers with all the dependencies installed on their machine could even run `make ci` locally, which is useful when, for example, you do not understand why the Travis build doesn't pass for your branch.

**Comment by ahocevar** [comment]
:+1: on @tschaub's proposal. I think `OL_EXTENDED_TESTS=true npm test` makes sense as a replacement for the ci target - and it follows the npm life cycle conventions.

**Comment by elemoine** [comment]
> I think OL_EXTENDED_TESTS=true npm test makes sense as a replacement for the ci target

Note that the `ci` target does much more than `OL_EXTENDED_TESTS=true npm test`. It also runs the rendering tests, compiles the examples, runs the examples in PhantomJS, and builds the API doc.

So, as I understand it, Tim's intent is not to replace the `ci` target by `OL_EXTENDED_TESTS=true npm test`. With just `node` installed, developers will be able to do `npm test`, which will just run the linter and the tests. And if they're brave enough to install Java, they will also be able to compile the ol3 code by doing `OL_EXTENDED_TESTS=true npm test`.

This indeed lowers the barrier of entry. Developers can get by with just `node`. If they want to go further they can install `java` and run the compiler. If they want to go even further they can use `make` (and run the `ci` target for example).

**Comment by tschaub** [comment]
I think we're thinking the same thing.

**Comment by fredj** [comment]
@tschaub can we close this issue?
