### ISSUE TITLE
ol.format.WFS - readFeatures() - transformation only works when dataProjection and featureProjection are set

### ISSUE THREAD

**Issue by cvenzin** [openlayers/openlayers#3590]
Eventually not a bug, but the documentation of the method readFeatures for the ol.format.WFS is missleading. Transformation is only applied if both properties are set. The defaultDataProjection of the format seems not to be used and is actually also not listed as a valid property for the ol.format.WFS.

Code:
if (!goog.isNull(featureProjection) && !goog.isNull(dataProjection) && !ol.proj.equivalent(featureProjection, dataProjection))

**Comment by bartvde** [comment]
WFS/GML has no default data projection. Unlike GeoJSON and KML which have a default data projection.

dataProjection will be read from the GML is this not the case for you?

**Comment by cvenzin** [comment]
No it didnt. I just debugged and found that it reads the correct srs code from the gml, but writes it to the property srsName which is never read again. 
ol.format.Feature.transformWithOptions only reads the property dataProjection from the opt_options.

![srs](https://cloud.githubusercontent.com/assets/9008716/7229115/5aabafc6-e760-11e4-9ed0-c6969f4e1c1b.PNG)

**Comment by cvenzin** [comment]
context['srsName'] = node.firstElementChild.getAttribute('srsName');
should be changed to
context['dataProjection'] = node.firstElementChild.getAttribute('srsName');

![unbenannt](https://cloud.githubusercontent.com/assets/9008716/7229193/1fb6c77e-e761-11e4-9af3-413961967373.PNG)

**Comment by ariandora** [comment]
Hello Guys,
We are having some issues on this regards - cannot parse a GML xml format with `(new ol.format.WFS()).readFeatures()` method.
Please take a look below:

`JavaScript`:

`var format, xmlDoc;
var xmlhttp = new XMLHttpRequest();
xmlhttp.onreadystatechange = function () {
if (xmlhttp.readyState === 4) {
format = new ol.format.WFS();
xmlDoc = xmlhttp.response;
vector = new ol.layer.Vector({
source: new ol.source.Vector({
format: format
})
});
console.log(xmlDoc)
var features = format.readFeatures(xmlDoc);
console.log(features)

}
};

xmlhttp.open("GET", "test.xml", true);
xmlhttp.send();`

`test.xml`:

`<?xml version='1.0' encoding="UTF-8" ?>
<wfs:FeatureCollection
xmlns:ms="http://mapserver.gis.umn.edu/mapserver"
xmlns:gml="http://www.opengis.net/gml"
xmlns:wfs="http://www.opengis.net/wfs"
xmlns:ogc="http://www.opengis.net/ogc"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://mapserver.gis.umn.edu/mapserver http://testt/maps?SERVICE=WFS&VERSION=1.1.0&REQUEST=DescribeFeatureType&TYPENAME=WFSLayer&OUTPUTFORMAT=text/xml;%20subtype=gml/3.1.1 http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd">
<gml:boundedBy>
  <gml:Envelope srsName="EPSG:27700">
    <gml:lowerCorner>357212.190000 172510.920000</gml:lowerCorner>
    <gml:upperCorner>357293.680000 172547.840000</gml:upperCorner>
  </gml:Envelope>
</gml:boundedBy>
<gml:featureMember>
<ms:WFSLayer>
<gml:boundedBy>
  <gml:Envelope srsName="EPSG:27700">
    <gml:lowerCorner>357212.190000 172510.920000</gml:lowerCorner>
    <gml:upperCorner>357293.680000 172547.840000</gml:upperCorner>
  </gml:Envelope>
</gml:boundedBy>
<ms:msGeometry>
<gml:Polygon srsName="EPSG:27700">
<gml:exterior>
<gml:LinearRing>
<gml:posList srsDimension="2">357231.510000 172529.130000 357228.280000 172529.910000 357228.390000 172530.400000 357227.110000 172530.710000 357223.140000 172531.670000 357222.770000 172530.110000 357219.900000 172530.810000 357220.280000 172532.360000 357215.800000 172533.440000 357214.090000 172536.120000 357214.810000 172539.140000 357212.190000 172539.770000 357213.520000 172545.260000 357216.140000 172544.630000 357216.920000 172547.840000 357227.800000 172545.200000 357227.220000 172542.770000 357229.840000 172542.150000 357234.400000 172541.060000 357254.270000 172536.310000 357268.930000 172532.820000 357274.370000 172531.520000 357273.560000 172528.110000 357275.110000 172527.740000 357293.680000 172523.270000 357291.430000 172513.940000 357290.710000 172510.920000 357287.410000 172511.720000 357287.640000 172512.690000 357282.100000 172514.020000 357281.730000 172512.470000 357278.910000 172513.140000 357279.290000 172514.700000 357273.750000 172516.030000 357273.520000 172515.060000 357270.310000 172515.830000 357271.200000 172519.530000 357267.990000 172520.300000 357268.110000 172520.790000 357266.170000 172521.260000 357262.860000 172522.060000 357262.480000 172520.500000 357259.570000 172521.210000 357259.940000 172522.760000 357254.690000 172524.030000 357254.580000 172523.550000 357251.370000 172524.320000 357248.160000 172525.100000 357248.280000 172525.590000 357243.030000 172526.860000 357242.650000 172525.300000 357239.730000 172526.010000 357240.110000 172527.560000 357234.860000 172528.830000 357234.740000 172528.350000 357231.510000 172529.130000 </gml:posList>
</gml:LinearRing>
</gml:exterior>
</gml:Polygon>
</ms:msGeometry>
<ms:identifier>20693</ms:identifier>
<ms:floor>gf</ms:floor>
<ms:testt_number></ms:testt_number>
<ms:fascia_size>18</ms:fascia_size>
<ms:activity_size>18</ms:activity_size>
<ms:postcode>BS8 4UN</ms:postcode>
<ms:street_number>BLOCK A - D</ms:street_number>
<ms:road_name>HOTWELLS HOUSE , HOTWELL ROAD</ms:road_name>
<ms:fascia></ms:fascia>
<ms:activity>DWELLINGS</ms:activity>
<ms:testt_area_ft2>11000</ms:testt_area_ft2>
<ms:fascia_master></ms:fascia_master>
<ms:primary_activity>DWELLINGS</ms:primary_activity>
<ms:use_class></ms:use_class>
<ms:holding_company></ms:holding_company>
<ms:trading_floors></ms:trading_floors>
<ms:misc_text></ms:misc_text>
<ms:testt_area_m2>1020</ms:testt_area_m2>
<ms:category></ms:category>
<ms:misc_size>18</ms:misc_size>
<ms:secondary_activity></ms:secondary_activity>
<ms:linecolor>0 0 0</ms:linecolor>
<ms:fillcolor>255 255 208</ms:fillcolor>
<ms:linewidth>1</ms:linewidth>
<ms:field1></ms:field1>
<ms:field2></ms:field2>
<ms:field3></ms:field3>
<ms:field4></ms:field4>
<ms:field5></ms:field5>
<ms:field6></ms:field6>
<ms:field7></ms:field7>
<ms:field8></ms:field8>
<ms:field9></ms:field9>
<ms:field10></ms:field10>
<ms:field11></ms:field11>
<ms:field12></ms:field12>
<ms:field13></ms:field13>
<ms:field14></ms:field14>
<ms:field15></ms:field15>
<ms:field16></ms:field16>
<ms:field17></ms:field17>
<ms:field18></ms:field18>
<ms:field19></ms:field19>
<ms:field20></ms:field20>
<ms:field21></ms:field21>
<ms:field22></ms:field22>
<ms:field23></ms:field23>
<ms:field24></ms:field24>
<ms:field25></ms:field25>
</ms:WFSLayer>
</gml:featureMember>
</wfs:FeatureCollection>`

**Comment by danail-vasilev** [comment]
I am interested in ariandora's question as well!
Could you please assist ?
Thank you !

**Comment by ahocevar** [comment]
For the example pasted above, two things are important:

 1. Provide a transform for EPSG:27700. One way to do that is use [proj4](http://proj4js.org/).
 1. Pass the correct featureNS and featureType to the `ol.format.WFS` constructor.

This ist the proj4 definition for EPSG:27700 (from https://epsg.io/):
```js
proj4.defs("EPSG:27700","+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs");
```

This is the working layer definition (where `xml` is the url of your WFS GetFeature response):
```js
var vector = new ol.layer.Vector({
  source: new ol.source.Vector({
    url: xml,
    format: new ol.format.GML({
      featureNS: 'http://mapserver.gis.umn.edu/mapserver',
      featureType: 'WFSLayer'
    })
  })
});
```

See this working codepen: https://codepen.io/ahocevar/pen/wyJYRJ
