### ISSUE TITLE
ol.source.Vector#clear issue

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#3600]
Go to http://openlayers.org/en/master/examples/vector-layer.html?mode=raw and type:

``` javascript
vectorLayer.getSource().clear();
```

In the console.

All the feature should be removed but it's not the case

**Comment by elemoine** [comment]
What happens is that the renderer reloads the layer when `vectorLayer.getSource().clear()` is called. I am not sure what the expected behavior is in this case.

**Comment by bartvde** [comment]
Right I actually sometimes use this to force a reload. Or is there another way to achieve this?

**Comment by elemoine** [comment]
If you really want a "static source" you should not configure your source with a loader or a url (a default loader is created when the `url` option is set), and use something like this instead:

```js
var source = new ol.source.Vector();
$.ajax('features.json').then(function(response) {
  var geojsonFormat = new ol.format.GeoJSON();
  var features = geojsonFormat.readFeatures(response,
      {featureProjection: 'EPSG:3857'});
  source.addFeatures(features);
});
```

Opinions?

**Comment by bartvde** [comment]
this makes sense to me @elemoine

**Comment by fredj** [comment]
I think that the function should behave the same as previously (v3.4.0)

**Comment by elemoine** [comment]
Try to do `vectorSource.clear()` in http://openlayers.org/en/v3.4.0/examples/vector-wfs.html and you will observe the same.

**Comment by fredj** [comment]
ok, at least we have the same behavior everywhere but is that what is expected?
The function documentation is "Remove all features from the source" but it's not the case; the features are reloaded.

**Comment by elemoine** [comment]
> ok, at least we have the same behavior everywhere but is that what is expected?

Note that http://openlayers.org/en/v3.4.0/examples/vector-wfs.html uses the v3.4.0 branch. So we already had the problem you're reporting in v3.4.0 and before. But it's more visible now…

**Comment by phipex** [comment]
This error occurs also in this example http://openlayers.org/en/v3.10.1/examples/earthquake-clusters.html?mode=raw, but does not occur in this one  http://openlayers.org/en/v3.10.1/examples/cluster.html, as they say more above it seems that only occurs in static sources
