### ISSUE TITLE
add layer switcher widget

### ISSUE THREAD

**Issue by Matthias84** [openlayers/openlayers#3622]
Hi,

while I migrate from OL2 I'm confused that v3 doesn't ships with an Layer switcher. I guess OL is in use for more complex GIS like projects than leaflet, so it's not to hard to predict that in this scenario people need to offer multiple baselayers and to switch between them of course ;)

Currently there are different approachs by 3rd parties to realize such widgets:
- https://github.com/omniscale/anol/tree/master/examples/layerswitcher
- https://github.com/walkermatt/ol3-layerswitcher

Please add such control upstream to make it easier for users to build basic webmap applications with the framework

**Comment by elmuSSo** [comment]
I know it motivated me to dig deeper into the code to write my own switcher, but I can also see that lack of layerswitcher is an obstacle for beginning ol3 devs. So I also support this issue.

**Comment by thiagogcm** [comment]
+1

**Comment by fredj** [comment]
we will not add a layer switcher to OpenLayers, please use a third party widget.
