### ISSUE TITLE
rightHanded option is ignored in WKT feature format

### ISSUE THREAD

**Issue by samjrdn** [openlayers/openlayers#3651]
When exporting a feature to WKT format, the _rightHanded_ option is ignored and the coordinates are formatted based on how the geometry was constructed. A work-around is to transform the feature's geometry first, order the coordinates by passing the _right_ parameter to the _getCoordinates_ method, create a new geometry from the transformed and ordered coordinates, and finally write the new geometry using the WKT _writeGeometry_ method. This manual processing could be avoided by adding support for the _rightHanded_ option to the WKT _writeFeature_ method.
Also, the documentation could be updated to indicate which formats support the _rightHanded_ option, and which do not.

**Comment by tschaub** [comment]
http://openlayers.org/en/master/apidoc/ol.format.GeoJSON.html#writeFeatures does say that not all formats support the option (but GeoJSON does).  It would be straightforward to add support for WKT.  And the docs could likely be improved.  This would be a welcome pull request.
