### ISSUE TITLE
lack of methods on edit feature style

### ISSUE THREAD

**Issue by MajedDH** [openlayers/openlayers#3654]
`ol.style.Style` doesn't have any setters for other style types.

I have a feature with style with `ol.style.Text` only .. 
I want to add image to it's style but there is no `setImage` method . and `getImage` returns null
I'm i forgetting some thing? 
I am supposed to edit style without making a new style object right ?

**Comment by umphy** [comment]
From the 3.5.0 [API docs] (http://openlayers.org/en/v3.5.0/apidoc/ol.style.Style.html), you can pass in a options hash with a text and an image when _initialising_ the `ol.style.Style` object. But you're right in that it doesn't have a set method for an image.

From the [vector icon example] (http://openlayers.org/en/v3.5.0/examples/icon.html), you can see an `ol.style.Style` object initialised with an image of type `ol.style.Icon`.

Hope that helps.

**Comment by MajedDH** [comment]
of course it helps :) thanks @umphy 
it just would be easier to change image from set method instead of making a whole new style object with all other properties
