### ISSUE TITLE
Tooltips do not appear in the canvas when doing an export

### ISSUE THREAD

**Issue by riverstream** [openlayers/openlayers#3675]
Using the following example with tooltips:

http://openlayers.org/en/v3.5.0/examples/measure.html

If you add screen capture (export map) to the same example:

http://openlayers.org/en/v3.0.0/examples/export-map.html

It does not export the tooltips.  This will make the export not usable since you need to have the measurements (or any other tooltip text) available as part of the export.  

I understand the tooltips are in a different div but it would be correct if they were also exported as part of the map.  (Or at least give an option such as showInCanvas: true/false for flexibility)

For example:

Old Code:
measureTooltip = new ol.Overlay({
    element: measureTooltipElement,
    offset: [0, -15],
    positioning: 'bottom-center'
  });
New Code:
measureTooltip = new ol.Overlay({
    element: measureTooltipElement,
    offset: [0, -15],
    positioning: 'bottom-center',
    showInCanvas: true
  });

**Comment by tsauerwein** [comment]
If you are exporting the map like in the ["Export map" example](http://openlayers.org/en/master/examples/export-map.html) you are basically just making a copy of the map canvas. Overlay elements, like you are saying, are HTML DOM elements, they are not rendered onto the map canvas. If you would want them to be exported with the map, you first would have to render them onto the canvas. This *[somehow](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas)* seems to be possible, but there are restrictions (like images would have to be inlined as `data:` urls). So it's not as easy as adding a new parameter to the options.

**Comment by fredj** [comment]
wontfix

**Comment by riverstream** [comment]
I would like to re-open this case.  This can be fixed.  Thanks.

**Comment by fredj** [comment]
If you need to add something to the canvas before exporting the image you can do it by directly writing into the canvas [here](https://github.com/openlayers/ol3/blob/v3.18.2/examples/export-map.js#L39).

**Comment by riverstream** [comment]
The problem is that if you add screen capture (export map) to the example:

http://openlayers.org/en/v3.0.0/examples/export-map.html

It does not export the tooltips. This will make the export not usable since you need to have the measurements (or any other tooltip text) available as part of the export.

**Comment by fredj** [comment]
The purpose of this example is not to be a full featured png export demo.

If you need to have text elements (tooltips) exported to the image you can draw on the canvas using the canvas API: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text

**Comment by riverstream** [comment]
Thanks, but that is a miserable work-around.  I will no longer pursue this since no one else has interest.

**Comment by ahocevar** [comment]
Were you planning to work on a solution for this @riverstream? If so, how were you planning to address the problem?

**Comment by riverstream** [comment]
Andreas good to hear from you.  I did not have time to pursue a solution.  Do you see an easy way to resolve this?  I think it would be beneficial to resolve this in the long-run for all users.  One means of use was we had a web based system that runs on tablets and we needed to capture and send back to the server a map image.  And of course the tooltips were not exported to the image.  Maybe I am the only one that has interested in resolving this.  Do you think enough people are using the export map feature to pursue this further?  Maybe not.

**Comment by ahocevar** [comment]
@riverstream If you can provide a pull request - fine. Otherwise it probably won't happen.

**Comment by dfung-ai** [comment]
@riverstream Do we have a solution yet?  Looking forward to.  I need this for the exact same reason.  Thanks!

**Comment by riverstream** [comment]
Not yet dfung.  I am not sure there is enough interest.

**Comment by dfung-ai** [comment]
Thanks!  

I am going to just put Text in the styles of the vector features.  This is not as nice as using tooltips, but it does the job for now.

**Comment by llashe** [comment]
Hello! I am interested on this now. Does anyone know how to solve the problem of the tooltips not being shown in the export map?

Thanks in advance!

**Comment by fredj** [comment]
I've updated the export map example and added an overlay, see #9571

**Comment by yossefaz** [comment]
For those who has the same issue, I achieved this by using the html2canvas library.
I first select the div that contains all the overlays, and pass it through the main function of this library. Like so : 

```
  const overlaycanva = await html2canvas(
    [...document.querySelectorAll(".ol-overlaycontainer")][0],
    {
      backgroundColor: null,
    }
  );
```
Then I just had to add this canvas on the top of the map canvas. All in one : 

```
  const overlaycanva = await html2canvas(
    [...document.querySelectorAll(".ol-overlaycontainer")][0],
    {
      backgroundColor: null,
    }
  );
  const mapCanvas = NewCanvas(width, height);
  const mapContext = mapCanvas.getContext("2d");
  Array.prototype.map.call(
    document.querySelectorAll(".ol-layer canvas"),
    (canvas) => {
      if (canvas.width > 0) {
        const opacity = canvas.parentNode.style.opacity;
        mapContext.globalAlpha = opacity === "" ? 1 : Number(opacity);
        // Get the transform parameters from the style's transform matrix
        const matrix = canvas.style.transform
          .match(/^matrix\(([^\(]*)\)$/)[1]
          .split(",")
          .map(Number);
        // Apply the transform to the export map context
        CanvasRenderingContext2D.prototype.setTransform.apply(
          mapContext,
          matrix
        );
        mapContext.drawImage(canvas, 0, 0);
        mapContext.drawImage(overlaycanva, 0, 0); //<===Here I add the overlaycanvas on the top of the map canvas
      }
    }
  );
```

Please note that the html2canvas is an async function. Then if you use it, you have to take care of this (I did this trick inside an async method so just by using the await keyword I handle this)

**Comment by basilmohammed** [comment]
Hello! 
I am interested on this now. 
Does anyone know how to solve this?
Thanks in advance!
