### ISSUE TITLE
getFeaturesAtCoordinate returns an empty array

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/openlayers#3703]
I have some features at the same coordinate and when I check using sourceFeatures.getFeaturesAtCoordinate(coord) I get an empty array. Digging on source (ol-debug) I can see this method - it is here that things happen.

```
ol.source.Vector.prototype.forEachFeatureAtCoordinateDirect =
    function(coordinate, callback, opt_this) {
  var extent = [coordinate[0], coordinate[1], coordinate[0], coordinate[1]];
  return this.forEachFeatureInExtent(extent, function(feature) {
    var geometry = feature.getGeometry();
    goog.asserts.assert(goog.isDefAndNotNull(geometry),
        'feature geometry is defined and not null');
    if (geometry.containsCoordinate(coordinate)) {
      return callback.call(opt_this, feature);
    } else {
      return undefined;
    }
  });
};
```

If I change this 
`if (geometry.containsCoordinate(coordinate)) {`
to 
`if (ol.extent.containsCoordinate(extent, coordinate)) {` 

then I get what I expect -- 3 features
[Live Example](http://plnkr.co/edit/Q470os?p=preview)

**Comment by jonataswalker** [comment]
I think this requires some attention. It is useful but doesn't work as expected.

**Comment by marcjansen** [comment]
Can you come up with a test case that fails but shouldn't?

**Comment by jonataswalker** [comment]
[This fails](http://plnkr.co/edit/Tx8Zv5?p=preview)

[This is modified using ol-debug.js](http://plnkr.co/edit/Q470os?p=preview)

**Comment by marcjansen** [comment]
Thanks. I meant a unit test, but nonetheless this may be usefull. I won't have time today, but I'll probably look at this tomorrow.

**Comment by alvinlindstam** [comment]
As you noted, i think geometry.containsCoordinate is wrong in this situation since many geometries (points, lines etc) does not contain anything and always returns false.

However, your solution ol.extent.containsCoordinate(extent, coordinate) would generate many false positives since it would return all features whose extent intersects the coordinate.

I think the proper way to do it is testing against geometry.intersectsExtent, and created PR ol.extent.containsCoordinate(extent, coordinate)

**Comment by jonataswalker** [comment]
@alvinlindstam  with your modification the number of features is as expected. Good job!

**Comment by marcjansen** [comment]
OK, so the original reason why an `ol.geom.Point` doesn't contain a coordinate representing itself is because `ol.geom.Point` inherits `containsXY` from `ol.geom.SimpleGeometry`, where it is defined as a method that always returns false.

Honestly I don't know if this is intentional or a bug. I think @elemoine or @tschaub usually know best which direction to take from now.

Here is a failing unit test:

```diff
diff --git a/test/spec/ol/source/vectorsource.test.js b/test/spec/ol/source/vectorsource.test.js
index df782e7..0a52f72 100644
--- a/test/spec/ol/source/vectorsource.test.js
+++ b/test/spec/ol/source/vectorsource.test.js
@@ -37,6 +37,24 @@ describe('ol.source.Vector', function() {
 
     });
 
+    describe('#getFeaturesAtCoordinate', function(){
+
+      it('returns empty array when on empty source', function(){
+        var got = vectorSource.getFeaturesAtCoordinate([0, 0]);
+        expect(got).to.be.an(Array);
+        expect(got).to.be.empty();
+      });
+
+      it('returns a single point at the coordinate', function() {
+        vectorSource.addFeature(pointFeature);
+        var got = vectorSource.getFeaturesAtCoordinate([0, 0]);
+        expect(got).to.be.an(Array);
+        expect(got).to.have.length(1);
+        expect(got).to.eql([pointFeature]);
+      });
+
+    });
+
     describe('#isEmpty', function() {
 
       it('returns true', function() {

```

**Comment by alvinlindstam** [comment]
Yes. LineString, MultiPoint and MultiLinestring also inherit the false-returning function. I assumed it was intentional.

**Comment by alvinlindstam** [comment]
Also, the implementation for containsXY/containsCoordinate on Polygons does not return true for all coordinates intersecting the polygon. As described in http://www.ecse.rpi.edu/Homepages/wrf/Research/Short_Notes/pnpoly.html#Point%20on%20an%20Edge the containing-algorithm will only return true for one of them, as two non overlapping polygons cannot contain the same area.

I added a test case for this at: https://github.com/alvinlindstam/ol3/commit/53154b770d2f5a11fb9b9f68c7b8c248fd49d77d#diff-c7cd06e8bd66f9197d3c2aa345c25a83R129

It uses two polygons, both with a boundary along the y-axis. Only one of them (the upper) will return true for containsCoordinate([0, 0]), while I would expect both of them to be returned on getFeaturesAtCoordinate.
