### ISSUE TITLE
custom tile origin and zoom offset with XYZ sources

### ISSUE THREAD

**Issue by saerdnaer** [openlayers/openlayers#3707]
Im porting an map from OpenLayers 2 to version 3 which uses a bitmap overlay with custom tile origin. It looks like the current XYZ source code doesn't allow to set a own tileGird and therefore no tileOrign, compare https://github.com/openlayers/ol3/blob/master/src/ol/source/xyzsource.js#L22-L26

My experiment is online at http://jsfiddle.net/L60452v8/5/

Is this a bug in the XYZ source? What's the best way to solve this problem?

**Comment by ahocevar** [comment]
Just use an `ol.source.TileImage` with your custom tile grid.

**Comment by saerdnaer** [comment]
Then I have to provide the tileUrlFunction, I assume:
```
        source: new ol.source.TileImage({ 
            tileUrlFunction: ol.TileUrlFunction.createFromTemplates(
                ol.TileUrlFunction.expandUrl('http://saerdnaer.de/ma/misc/fmi/zoom_{z}/{y}_{x}.png')),
            tileGrid: customGrid
        })
```
But ol.TileUrlFunction is undefined. What are I doing wrong?
http://jsfiddle.net/L60452v8/6/

**Comment by ahocevar** [comment]
ol.TileUrlFunction does not export anything currently. Maybe we should change that?

In the meantime, you'd have to provide your own tile Url function.

**Comment by saerdnaer** [comment]
For anyone having the same problem, here is my current solution: http://jsfiddle.net/saerdnaer/L4ss70d0/

```
    new ol.layer.Tile({
        source: new ol.source.TileImage({
            tileUrlFunction: function (tileCoord, pixelRatio, projection) {
                if (tileCoord === null) return undefined;

                z = tileCoord[0] + 15;
                x = tileCoord[1];
                y = -tileCoord[2]-1;

                if ( z < 17 || x < 0 || y < 0) return undefined;

                return 'http://saerdnaer.de/ma/misc/fmi/zoom_' + z + '/' + y + '_' + x + '.png';
            },
            tileGrid: customGrid
        })
    }),
```

Don't ask my about this strange offsets, I don't know why the orginal author of our OL2 code did this. My next step is to get the extend wright. It looks like the orgin option of a tilegrid.XYZ doesn't have any effect. Still have to read this up in the source code.

**Comment by GammaGames** [comment]
With OL3 I had to use `y = -tileCoord[2] - 1;`. Not sure exactly why, maybe the server I'm using for tile images starts at 0 instead of 1.
