### ISSUE TITLE
Respect layer extent for requests from ol.source.ImageWMS

### ISSUE THREAD

**Issue by Martin-Wegner** [openlayers/openlayers#3729]
Please add an option to avoid world wrapping for ol.source.ImageWMS.
The combination of GeoServer and Oracle Spatial has problems with world wrapping.

When you zoom in and then zoom out in the example http://jsfiddle.net/31tdjn38/1/ then you can see a request like:
http://maps.dwd.de/geoserver/dwd/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/png&TRANSPARENT=true&LAYERS=dwd:bluemarble&CRS=EPSG:4326&STYLES=&WIDTH=1200&HEIGHT=768&BBOX=-135,-210.9375,135,210.9375

OpenLayers 3 generates a BBOX of [-210.9375, -135, 210.9375, 135] but the given extent is [-180, -90, 180, 90].

This looks like a bug?

**Comment by ahocevar** [comment]
Just add an extent to the configuration of the layer that you use the source with:

```
new ol.layer.Image({
  extent: [-180, -90, 180, 90],
  source: new ol.source.ImageWMS({...})
});
```

**Comment by Martin-Wegner** [comment]
As you see in my given example I use the ol.layer.Image extent!

**Comment by ahocevar** [comment]
The ratio is added to the request extent, which should not happen. I updated your fiddle with a configured ratio of 1, which avoids such requests: http://jsfiddle.net/ahocevar/31tdjn38/2/. But this is a bug indeed.

**Comment by Martin-Wegner** [comment]
OK thanks.
The ratio 1 works in most cases but not in all :(
Sometimes requests with a BBOX [-90.01062447546653, -180, 88.93468802453347, 180] are created :(
Can you fix that too?
