### ISSUE TITLE
getState() on ol.TileVector

### ISSUE THREAD

**Issue by plepe** [openlayers/openlayers#3746]
I was unsure if I shouldn't post this to StackOverflow instead, but I'm pretty sure this is a bug, not a question

 ol.source.TileVector has a function `getState()` which - according to the documentation - returns the state of the source, e.g. 'loading'. When I try to get the state, it is always 'ready', regardless of the apparent state. As far as I can analyze the code, the state is never changed.

Example:

``` js
var src = new ol.source.TileVector({
  url: "something/{z}/{x}/{y}.json",
  tileGrid: new ol.tilegrid.XYZ()
});
var lyr = new ol.layer.Vector({
  source: src,
  visible: true
});
map.addLayer(lyr);

lyr.on('change', function() {
  console.log(src.getState());
});
```

The change handler is called many times, for each tile which has been successfully loaded. The state is always 'ready'. I'm using v3.5.0, compiled from source.

**Comment by ahocevar** [comment]
This is not a bug, it is just poor design unfortunately. The `change` event is a generic event which is triggered every time something changes. The `state` of a source is ready as soon as the source is ready to send requests to the server, which - for `ol.source.TileVector` - is as soon as it is configured.

Having said that, it's valid to have this ticket and to keep it open until we have a better solution for tracking loading from vector sources.

**Comment by plepe** [comment]
I see. Waiting for improvements :-)

**Comment by plepe** [comment]
Btw, I guess the correct object to listen for a change would be `src`, but that didn't change much ...

```js
src.on('change', function() {
  console.log(src.getState());
});
```
