### ISSUE TITLE
Overlay map pointerup event not be listened

### ISSUE THREAD

**Issue by xuchengli** [openlayers/openlayers#3762]
If I create a map on overlay, the map pointerup event will not be listened,  but the pointerdown is ok.

**Comment by tsauerwein** [comment]
Could you please provide a JSFiddle showing your problem? Something like http://jsfiddle.net/n0ddgwb7/

**Comment by xuchengli** [comment]
The sample code is:  http://jsfiddle.net/6dcoesd2/

**Comment by xuchengli** [comment]
Is there any method to resolve the problem? thanks.

**Comment by tsauerwein** [comment]
I can confirm that there is a problem with the events, when there is a 2nd map inside an overlay. As a work-around you could directly listen on `mousedown/up` on the overlay element. But that probably doesn't help you that much as panning the 2nd map doesn't work either...

**Comment by micoFinlandes** [comment]
Same issue, my setup is a modalWindow over wicket page and there the map sticks to the mouse when clicked and only gets out when clicked elsewhere.

**Comment by xuchengli** [comment]
I resolved the issue by register the event on map viewport div element. The sample code as:
http://stackoverflow.com/questions/30702054/openlayer-3-map-pointer-up-event-can-not-be-triggered-when-the-map-created-on-o

**Comment by oukjweather** [comment]
I'm getting a similar occurrence to happen without using an overlay map on OL 3.8.2. The mouse up event does fire and I can see it trigger the pointer up event, 

I see this line get called.
  this.fireEvent(ol.pointer.EventType.POINTERUP,
      pointerEventData, browserEvent);


It fails to listen for it though on ol.MapBrowserEventHandler.prototype.handlePointerUp_

**Comment by tomkcook** [comment]
This still appears to be a problem, and not only where there are overlays.  See [this jsfiddle](https://jsfiddle.net/mnmmkjds/).  The `pointerdown` and `pointerdrag` events work fine, but after releasing the mouse button, the square keeps rotating - the `pointerup` event has been missed.  Weirdly, if you then click _outside_ the map (though still in the iframe containing the map in jsfiddle), the `pointerup` event fires and the rotation stops.
