### ISSUE TITLE
ol.control.OverviewMap missing options from OL2

### ISSUE THREAD

**Issue by KlemenSpruk** [openlayers/openlayers#3781]
How can I lock zoom to 1 level in ol.control.OverviewMap?

There are missing options from OL2:

numZoomLevels: 1
minRatio: 0, maxRatio

**Comment by adube** [comment]
It is not currently possible to do that.  A PR would be welcome.  I'd be happy to test it if you're willing to work on this.

**Comment by thinkpadder1** [comment]
I think it should use ol.View rather than one-off options like numZoomLevels etc as it will give it much more control (restricting rotation, resolution control, different projections, different center, etc).
