### ISSUE TITLE
Enhancement: Make ol.style.Icon scalable in both X and Y.

### ISSUE THREAD

**Issue by pconnell99** [openlayers/openlayers#3803]
Currently the scale parameter of an **ol.style.Icon** has a scale parameter that takes a single float value between 1 and 0 the defines the scale of the icon.  To make the Icons more useful to model real-world items (cars, planes, ships etc.) they would need to be scalable in both X and Y axis.

Suggested that this is done to allow this.  What would be involved?  I have been looking in **ol.render.canvas.Replay.prototype.replay_** and 'fiddling' with values in there seems to perform scaling and rotation.

**Comment by pconnell99** [comment]
Feeding in custom x/y coords (debug) into replay_ (case **ol.render.canvas.Instruction.DRAW_IMAGE**) and moving the rotation IF clause in **ol.vec.Mat4.makeTransform2D** above the scale works - no skewing.

I'm manipulating the scale, scale clause in 
`ol.vec.Mat4.makeTransform2D(
                localTransform, centerX, centerY, scale, scale,
                2, -centerX, -centerY);`

**Comment by pconnell99** [comment]
Nobody?

**Comment by tschaub** [comment]
It would be nice to allow `scale` to be either a `number` or `Array.<number>` (instead of adding `scaleX` and `scaleY`).  Not sure how others feel about that.

**Comment by pconnell99** [comment]
That is what I did, it passed build and works, but making the document/api updates is a bit beyond my knowledge of the codebase.

Is anyone willing to 'sponsor' (i.e. do) thus update for me?


On 25 June 2015 16:18:20 BST, Tim Schaub <notifications@github.com> wrote:
>It would be nice to allow `scale` to be either a `number` or
>`Array.<number>` (instead of adding `scaleX` and `scaleY`).  Not sure
>how others feel about that.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/openlayers/ol3/issues/3803#issuecomment-115289772

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pconnell99** [comment]
Looking at the codebase I'll need to rewire the webgl render a bit as well to use scale[0] and scale[1] throughout.  As to the scale parameter - as it's still experimental, should we just switch to an Array<number> ongoing, defaulted to [1,1] if not set?

The hardest part for me at the moment is getting up to speed with HOW to successfully edit the codebase so it passes validation at every point - changing the type has consequences throughout the codebase I'm not aware of (does me switching the rotation matrix transform above the scale cause issues?  No idea, it just worked).
