### ISSUE TITLE
map.getLayers().setAt issue

### ISSUE THREAD

**Issue by vazquezornelas** [openlayers/openlayers#3811]
Hi. I have the problem when i send to order my layers according i am loading the second time if i set the function setAt with the same position it give me this error:

Uncaught TypeError: Array.prototype.forEach called on null or undefined
    at forEach (native)
    at Sa (http://geoactiva.dev:8080/geoactivaV2.0/js/plugins/ol3/ol-3.6.js:23:625)
    at G.l.Vj (http://geoactiva.dev:8080/geoactivaV2.0/js/plugins/ol3/ol-3.6.js:231:45)
    at ad (http://geoactiva.dev:8080/geoactivaV2.0/js/plugins/ol3/ol-3.6.js:43:187)
    at nf.l.dispatchEvent (http://geoactiva.dev:8080/geoactivaV2.0/js/plugins/ol3/ol-3.6.js:41:328)
    at nf.l.Vn (http://geoactiva.dev:8080/geoactivaV2.0/js/plugins/ol3/ol-3.6.js:80:72)
    at OrdenaCapas (http://geoactiva.dev:8080/geoactivaV2.0/:497:23)
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)

**Comment by marcjansen** [comment]
Have you tried ol-debug.js? What is the error then?

**Comment by vazquezornelas** [comment]
Hi. I am traying to change order the layers.

var Pos=0;
var Pos2=1;
var LayerTarget=map.getLayers().getArray()[Pos];
var LayerSource=map.getLayers().getArray()[Pos2];

map.getLayers().setAt(Pos,LayerTarget);
map.getLayers().setAt(Pos2,LayerSource);

i got the this error some times and some times dosent:

Uncaught TypeError: Array.prototype.forEach called on null or undefinedSa @ ol-3.6.js:23l.Vj @ ol-3.6.js:231ad @ ol-3.6.js:43l.dispatchEvent @ ol-3.6.js:41l.Vn @ ol-3.6.js:80OrdenaCapas @ administrador:105MueveCapa.$.ajax.success @ VM6323:166jQuery.Callbacks.fire @ jquery-2.2.1.js:3073jQuery.Callbacks.self.fireWith @ jquery-2.2.1.js:3185done @ jquery-2.2.1.js:8253jQuery.ajaxTransport.send.callback @ jquery-2.2.1.js:8600

**Comment by elemoine** [comment]
You need to provide more information. I just tried with http://openlayers.org/en/master/examples/vector-layer.html in things work as expected.

```
var layer0 = map.getLayers().getArray()[0];
var layer1 = map.getLayers().getArray()[1];
map.getLayers().setAt(0, layer0);
map.getLayers().setAt(1, layer1);
```

and I don't get any error.

**Comment by probins** [comment]
not sure if this is the problem here, but if you try and `setAt` beyond the current length of the collection, it inserts `undefined` entries in the collection, which will then cause errors for anything iterating over the collection https://github.com/openlayers/ol3/blob/master/src/ol/collection.js#L269 for example `map.getLayers().setAt(3, layer0);` in the vector-layer example.

That shouldn't cause a problem in the simple replace case given here, but it would if you were removing layers and then trying to set at a position that no longer exists.

**Comment by vazquezornelas** [comment]
Here is my site.  http://geoactiva.no-ip.biz/geoactivaV2.0/index.php
press ENTRAR.

Move the layer order.
The first time it did. The second time send the error.

This is the function that order the layers.

for(var Grupo=Grupos.length-1 ;Grupo >=0; Grupo--){
			var Capas=Grupos[Grupo].children;
			for(var n= Capas.length-1 ;n >=0;n--){								
				LayerSource=map.getLayers().getArray()[Pos];
				Pos2=null;
				map.getLayers().getArray().forEach(function(lyr,Position){					
					if(lyr.get('name')==Capas[n].Capa.idcapa){
						LayerTarget=lyr; Pos2=Position;
						return;
					}
				});
				if(LayerSource != LayerTarget){										
					map.getLayers().setAt(Pos,LayerTarget);
					map.getLayers().setAt(Pos2,LayerSource);
				}
				Pos++;
			}			
		}					
		for(var n= Tematicos.length-1; n >=0 ; n--){
			LayerSource=map.getLayers().getArray()[Pos]; Pos2=null;
			map.getLayers().getArray().forEach(function(lyr,Position){
				if(lyr.get('name')=="Tematico_"+Tematicos[n].Tematico.idtematico){											
					LayerTarget=lyr; Pos2=Position;
					return;
				}
			});
			if(LayerSource != LayerTarget){
				map.getLayers().setAt(Pos,LayerTarget);
				map.getLayers().setAt(Pos2,LayerSource);
			}
			Pos++;
		}		
		for(var n= MapasCalor.length-1; n>=0; n--){
		   LayerSource=map.getLayers().getArray()[Pos]; Pos2=null;
			map.getLayers().getArray().forEach(function(lyr,Position){
				if(lyr.get('name')=="MapaCalor_"+MapasCalor[n].id){
					LayerTarget=lyr; Pos2=Position;
					return;
				}
			});
			if(LayerSource != LayerTarget){				
				map.getLayers().setAt(Pos,LayerTarget); 
				map.getLayers().setAt(Pos2,LayerSource);
			}
			Pos++;
		}

**Comment by dpmcmlxxvi** [comment]
I'm having the same problem with 3.5.0 and 3.6.0. There is no error with 3.4.0. See this [jsfiddle](https://jsfiddle.net/o737rw77/). Clicking the "Swap" button works once but not twice. The example above by @elemoine doesn't actually change the layer positions which may be why the error isn't seen.

The first time the layers are swapped it works fine. But the second time the following error is thrown

    TypeError: can't convert undefined to object

When ol-debug.js is used the error thrown is

    AssertionError: Assertion failed: listeners already registered

**Comment by probins** [comment]
yes, this can be reliably reproduced in the vector-layer example too.
```
function chg(){
  var layers=map.getLayers();
  var layer0 =layers.item(0);
  var layer1 = layers.item(1);
  layers.setAt(0, layer1);
  layers.setAt(1, layer0);
}
chg();
chg();
```
The debug msg is from ol.layer.Group.prototype.handleLayersAdd_. Because the listener key is based on the layer Uid, which will have been created by the previous action. Presumably the assumption is that you won't add the same layer twice to the same collection?

**Comment by probins** [comment]
no, I think I see what the problem is. When you swap the layers like this, you are adding a layer that is already in the collection. I think the solution is to remove both layers, then insert/push them both.

**Comment by probins** [comment]
so changing my function to the following works fine:
```js
function chg(){
  var layers=map.getLayers();
  var layer1 = layers.pop();
  var layer0 = layers.pop();
  layers.setAt(0, layer1);
  layers.setAt(1, layer0);
}
chg();
chg();
```

**Comment by probins** [comment]
The current docs for ol.Collection.remove "Remove the first occurrence of an element from the collection" implies that an element, i.e. an object instance, can be in a collection more than once. But the change in #3528, which creates the event listener based on Uid, means that this is no longer the case. Are there valid use cases for this? If not, I'd suggest changing the docs to make it clear that an instance can only be present once in a collection. It might also be a good idea to change the assert "listeners already registered" to the more helpful "object already in collection".

**Comment by dpmcmlxxvi** [comment]
Okay. Thanks for looking into it. I worked around it by removing one of the layers to be swapped and then inserting it at the desired location. I was trying to avoid this because I am monitoring the *change:length* event and removing/inserting layers was causing undesired side effects. But, I found a work around by having my application track if a layer is being moved and have it avoid the undesired behavior. If this is intended behavior then so be it.

**Comment by vazquezornelas** [comment]
But what about if you want swap position 4 and position 6 in a map that has 15 positions ?

**Comment by probins** [comment]
have a dummy layer to set temporarily? create refs for 4 and 6; put dummy in 6, put 6 in 4, put 4 in 6. Bit of a pain, but it should work.

**Comment by dpmcmlxxvi** [comment]
To swap non-adjacent layers, you could move the invisible layer up first then move the visible layer down second. See [here](https://jsfiddle.net/nfmshxqr/1/). If you are doing something more complicated like partially visible layers, spy layers, etc, it might get more complicated and have to do the dummy layer suggested by @probins.

**Comment by probins** [comment]
alternatively use removeAt/insertAt (making sure you adjust the insertAt position to reflect the fact that you've just removed one :smiley: )
