### ISSUE TITLE
Populating the Tile Cache

### ISSUE THREAD

**Issue by Morgul** [openlayers/openlayers#3814]
For our application, we would like to be able to force the loading of tiles for a specific geographic location. We already have the bounds of the user's data related to the map on application startup, so it should be easy for us to calculate a reasonable amount of that to preload. Our users very infrequently scroll around the map, but rather work in predefined areas, so we should be able to greatly improve our user experience with this kind of preloading. (Additionally, this would allow for an 'offline' workflow.)

I am aware of the `preload` option on the layers, but that is much more limited than what we're looking to do. What I think would be needed would be an api function that allowed us to pass in an `Extent`, and openlayers would use it's normal tile loading logic to queue up those tiles. Alternatively, simply exposing the TileCache in a meaningful way would allow my application to implement that logic and simply push that into the cache.

Is there a way to do this from the application side and I'm missing it? If not, what are the thoughts about exposing something like this?

**Comment by elemoine** [comment]
> Is there a way to do this from the application side and I'm missing it?

Not that I know.



> If not, what are the thoughts about exposing something like this?

I haven't looked at the details, but exposing something like this would make sense to me.
