### ISSUE TITLE
Unable to change the Source for a Draw interaction

### ISSUE THREAD

**Issue by awj** [openlayers/openlayers#3846]
A quick glance at the code suggests it should be easy to make the Source that is the eventual feature destination of ol.interaction.Draw an editable property. We have some workflows where that can change, and updating the property is easier than unbinding and rebuilding the interaction.

**Comment by ralphstodomingo** [comment]
Is there no solution right now than to rebuild the interaction? Looking at `ol.interaction.Select` there is an option to supply the `layers` property a filter function.

**Comment by awj** [comment]
@ralphstodomingo just took another dive into the code, and no there isn't at this time.
