### ISSUE TITLE
No Features after drawend in bounded layer of ol.interaction.Draw

### ISSUE THREAD

**Issue by KluSa** [openlayers/openlayers#3852]
I moved from ol 3.4 to 3.6.
There is no feature in bounded layer of ol.interaction.Draw after drawend-event. The behaviour seems to be different from version 3.4

**Comment by bartvde** [comment]
Please show your issue with a jsFiddle

**Comment by alvinlindstam** [comment]
This changed in https://github.com/openlayers/ol3/pull/3573

**Comment by samadd** [comment]
I have just migrated from ol 3.3 to 3.6 and have also come up against this as a breaking change.

I was calling a function on the drawend event which was bound to a layer, and in that function extracting the coordinates of the new feature in said layer, and passing them to another part of the application to store in a separate model.

This no longer works now the feature does not exist in the layer's collection at drawend. I'm at a bit of a loss as to how to come up with a reliable and non-ridiculous workaround in the absence of any access to the created feature when drawend is fired.

Any chance of re-introducing the old functionality somehow? I understand the need to keep the API simple, but it would make things a lot simpler if I were able to inspect the contents of a newly drawn feature at the end of the drawing process!

**Comment by bartvde** [comment]
cc @gberaudo

**Comment by sergkr** [comment]
Some frameworks (for example, ExtJS) take the approach of dispatching two events for each logical event. For example, there would be a "beforeexpand" and an "expand" event for a panel. The "before" version allows the user to run custom logic before the default behavior of expanding the panel actually takes place. They can also return false from the "before" event handler to cancel the event from proceeding any further.

Has this kind of approach been considered for OpenLayers? Seems like it ought to satisfy both camps.

**Comment by bartvde** [comment]
yes it has been considered see the discussion in #3573

**Comment by alvinlindstam** [comment]
Applications could use the source's events to detect the added feature, and if check if it's added by the draw interaction: http://jsfiddle.net/ym37kdny/

Is that enough for your needs?

**Comment by samadd** [comment]
@alvinlindstam 

Thanks! That approach appears to work perfectly for my purposes.
