### ISSUE TITLE
Animation with "start" parameter is not working

### ISSUE THREAD

**Issue by costales** [openlayers/openlayers#3897]
Following the [documentation](http://openlayers.org/en/v3.5.0/apidoc/ol.animation.html),

A [normal animation](http://jsfiddle.net/abgcvqw3/45/) is working fine.

But an [animation with a delay](http://jsfiddle.net/abgcvqw3/46/) (parameter: start added to previous example) is not working.

Thanks in advance!

**Comment by alvinlindstam** [comment]
Your link to the docs is for OpenLayers 3.5.0, but your jsfiddle uses 3.0.0. Current release is 3.7.0.

Are you still having the issue if you use more recent builds?

**Comment by alvinlindstam** [comment]
Your link to the docs is for OpenLayers 3.5.0, but your jsfiddle uses 3.0.0. Current release is 3.7.0.

Are you still having the issue if you use more recent builds?

**Comment by costales** [comment]
Hi @alvinlindstam, 3.5.0 is not working either:
OL 3.5.0: http://jsfiddle.net/abgcvqw3/56/
OL 3.7.0: http://jsfiddle.net/abgcvqw3/57/
Thanks in advance!

**Comment by alvinlindstam** [comment]
Ok. I took a quick peek at the source code. ol.animation.pan expects "start" to be a time stamp, not a delta. So if you want the animation to start a second later, set start to (new Date()).getTime()+1000.

**Comment by jonataswalker** [comment]
If you delay 10 secs:
```javascript
var start = +new Date() + 1000 * 10;
map.beforeRender(pan);
map.getView().setCenter(newCenter);
```
You will have 2 firing from `map.getView().setCenter()`, the first immediately and the last, 10 seconds later. So, it looks like, something will have to be done on the lib itself to synchronize this.

**Comment by costales** [comment]
Thanks, as @alvinlindstam said, that is the way, but as @jonataswalker it's not working right.

**Comment by fredj** [comment]
See https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#use-viewanimate-instead-of-mapbeforerender-and-olanimation-functions
