### ISSUE TITLE
ol.control.MousePosition reports invalid lat/lon on wrapped maps.

### ISSUE THREAD

**Issue by pconnell99** [openlayers/openlayers#3899]
When I implement a 'many world's wrapX implementation with my vector layer and a tiled map layer, the mouseposition control reports invalid coordinates

Example is at https://jsfiddle.net/smtxcdeo/ - put your mouse over world +1 or -1 and the coordinates system reported is greater that 180/-180.

```
map.addControl(new ol.control.MousePosition({
className: "mapCoords",
projection: "EPSG:4326",
            coordinateFormat: function(coordinate) {
                return ol.coordinate.format(coordinate, '{y}\', {x}\'', 4);
            },
            target: 'coordinates',
            undefinedHTML: ""
}));
```

Is this by design? Is this a bug? How would I get it to report the correct lat/lon (mouseover of a feature on the other 'worlds' returns a co-ordinate within world 1 as expected - this causes other issues with popups etc.)

**Comment by jeansouza** [comment]
I've created a function to resolve the "problem" in the app that I'm building, maybe useful for somebody:

  ```
/**
   * @author Jean Souza [jeancfsouza@gmail.com] - Paulo Remoli [paulo002@gmail.com]
   *
   * @function normalizeLongitude
   */
  var normalizeLongitude = function(longitude) {
    var correctedLongitude = longitude;
    var originalLongitude = longitude;

    if(longitude > 180 || longitude < -180) {
      longitude = longitude < 0 ? longitude * -1 : parseFloat(longitude);

      var isDivisionResultEven = (parseInt(longitude / 180) % 2) === 0;
      var divisionResult = isDivisionResultEven ? parseInt(longitude / 180) : Math.ceil(longitude / 180);

      if(divisionResult > 0)
        correctedLongitude = (originalLongitude < 0) ? originalLongitude + (divisionResult * 180) : longitude - (divisionResult * 180);
    }

    return correctedLongitude;
  };
```

**Comment by chander** [comment]
+1 - this bug is annoying.  However, the fix would need to also account for projections other than EPSG:4326 that might also wrap, which might be harder than this...

Won't this do the same thing, but without the complexity (when your control is defined to use the EPSG:4326 projection):

```
/**
 * @function correctLongitude
 * Take a longitude that is wrapped around the IDL multiple times and unwrap it to a value
 * that is between -180 and 180.
 */
function correctLongitude(value) {
    // Remove wraps after the first wrap.
    v= v % 360;
    // If we are still outside the bounds then adjust as needed.
    if (value < -180) {
        value += 360;
    }
    if (value > 180) {
        value -= 360;
    }
    return value;
}
```

**Comment by mstenta** [comment]
I just received a bug report in [farmOS](http://github.com/farmOS/farmOS) that I traced to this issue. Here is the report for reference: https://github.com/farmOS/farmOS/issues/33

To summarize: if you zoom all the way out on the map, and then pan the map over to the right a LOT (like see the same continent pass a few times), and then draw a polygon, the longitude coordinates of the polygon are all HUGE (like 800+ when they should be <180).

**Comment by jeansouza** [comment]
Thanks for the reply.


--
Jean Souza

2017-05-18 12:39 GMT-03:00 Michael Stenta <notifications@github.com>:

**Comment by chander** [comment]
So I hacked around this for now like so - basically overriding the output of the map's getCoordinateFromPixel function to correct the coordinates.  

I believe this should fix these coordinate issues with the mouse Position control, draw controls, and probably some others as well (most anything that depends on this function to convert a pixel to a map coordinate.)  This also should work for many different base map projections, but the wrap thing is really only an applicable case for a limited set of projections.  Feedback is appreciated, as always.:

```

/**
 * Save a reference to the original function so that we can use it in
 * the function we use to correct for bad coordinates.
 */
map._original_getCoordinateFromPixel=map.getCoordinateFromPixel

/**
 * @author Chander Ganesan [chander@gridgeo.com]
 * So this is a hack that I put in to handle the case where
 * mouse clicks return an invalid coordinate.  It's an issue that
 * is documented here:
 * 
 * https://github.com/openlayers/openlayers/issues/3899
 * 
 * Basically, we take the map coordinates, reproject them to WGS84
 * and then correct for longitude overlap - then we reproject them
 * back to the map projection and return the value.  
 */
map.getCoordinateFromPixel=function (pixel) {
    var map_proj=map.getView().getProjection();
    var loc=map._original_getCoordinateFromPixel(pixel);
    if (loc) {
        var loc2=ol.proj.toLonLat(loc, map_proj);
       
        // Sometimes it's possible for these coordinates to be
        // waaaay off due to wrapX- here we handle that by taking
        // the longitude and making sure that it isn't outside the
        // bounds of WGS84 (-180/180)
        loc2[0] = loc2[0] % 360; // Remove wraps after the first wrap
        if (loc2[0] < -180) {
            loc2[0] += 360
        }
        if (loc2[0] > 180) {
            loc2[0] -= 360;
        }

        loc=ol.proj.fromLonLat(loc2, map_proj)
    }
    return loc
}
```

**Comment by chander** [comment]
As a side note.  When using a EPSG:3857 base layer, and zoomed out (like ZL 2)  in many cases WMS services in single tile mode don't display properly across the entire map when the map straddles the IDL (you'll get tiles to one side of the IDL, but not the other.).  The fix above seems to correct that issue as well.

**Comment by PatrickHarriss** [comment]
The ol.coordinate.toStringHDMS method handles normalizing the geometries correctly no matter how many times you have crossed the 180 lines. If you want that format for your mousepointer that is all you need. If you need decimal coordinates you could use the following method. 

function normalizeCoordinate (coordinateIn) {

var dms = (ol.coordinate.toStringHDMS(coordinateIn, 14)).split(" ");
var latDegrees = dms[0].slice(0,-1);
var latMinutes = dms[1].slice(0,-1);
var latSeconds = dms[2].slice(0,-1);
var latDirection = dms[3];

var lonDegrees = dms[4].slice(0,-1);
var lonMinutes = dms[5].slice(0,-1);
var lonSeconds = dms[6].slice(0,-1);
var lonDirection = dms[7];

var decimalLat = parseFloat(latDegrees) + parseFloat(latMinutes / 60.0) + parseFloat(latSeconds / 3600.0);
var decimalLon = parseFloat(lonDegrees) + parseFloat(lonMinutes / 60.0) + parseFloat(lonSeconds / 3600.0);

if (lonDirection == 'W') {
   decimalLon = (-1) * decimalLon;
}

if (latDirection == 'S') {
   decimalLat = (-1) * decimalLat;
}

return [decimalLon,decimalLat];

}

**Comment by PatrickHarriss** [comment]
Here is another way of taking a decimal coordinate and normalizing the longitude so it is between -180 and 180. 
`
// returns the modulo of a / b, depending on the sign of b
function modulo (a,b) {
   var r = a % b;
   return r * b < 0 ? r + b : r;
}


function normalizeCoordinate (coordinateIn) {
   var longitude = coordinateIn[0];
   var latitude = coordinateIn[1];
   var normalizedLongitude = modulo(longitude + 180, 360) - 180;
   return [normalizedLongitude,latitude];
}
`

**Comment by mstenta** [comment]
Looking into this again for farmOS: https://github.com/farmOS/farmOS-map/issues/49

Curious: do you think this is something that should be fixed here in OpenLayers? Or downstream in my (and other) projects? Seems like an OL issue to me. Can this issue be reopened?

**Comment by mstenta** [comment]
@chander I tried `getCoordinateFromPixel()` as described in [your comment](https://github.com/openlayers/openlayers/issues/3899#issuecomment-307234774) above and found that it broke the draw interaction outside of the original map view's longitude. In other words, you can draw shapes on the map after it loads, but if you wrap around once east or west, the draw pointer no longer shows under my mouse pointer, and drawing shapes is not possible.

Presumably, the draw interaction uses `getCoordinateFromPixel()`, and this override causes that to stop working outside the normal -180 to +180 longitude range.

**Comment by mstenta** [comment]
Ah... if I add `wrapX: true` to the options passed into `new Draw()`, I am able to begin drawing... but I can't seem to finish drawing.  Double-click doesn't work to finish a polygon.  I can draw a point, however, and it appears that the longitude is correct for that point!  So I just need to figure out what's wrong with double-click for lines/polygons...

**Comment by mstenta** [comment]
@fredj can we reopen this issue? I think it was prematurely closed by the Stale bot.

**Comment by chander** [comment]
Odd, I'm using it without issue - but that particular project is using openlayers ^4.6.4; it's possible that I'll encounter the same issue on upgrade.  IIRC wrapX is kind of required for cross-IDL drawing.

**Comment by mstenta** [comment]
@chander Double-click to finish polygon works for you after crossing IDL?

`wrapX` did fix my first issue (inability to draw after crossing IDL). But I'm still unable to finish polygons.

**Comment by chander** [comment]
Actually, I must have misread. After crossing the IDL double click does not stop drawing, and drawings still end up with a weird set of coordinates. IIRC cross-idl drawings are (in general) another defect (though I’m not sure I opened a defect for them.

**Comment by mstenta** [comment]
Thanks @chander - good to know!

I spent some time digging into this and I think I found a solution to the root problem...

There is a single function `toEPSG4326()` which is responsible for converting coordinates from `EPSG:3857` to `EPSG:4326`: https://github.com/openlayers/openlayers/blob/6fe5c886148a325c881bd63aae635b44268ae37b/src/ol/proj/epsg3857.js#L129

If we add your logic (from your first comment) to that function, it seems to fix the issue in both the `MousePosition` control (described in the this issue's original description), as well as the issue I experienced with drawing shapes.

I created a pull request: https://github.com/openlayers/openlayers/pull/10274

I also created a gist which illustrates how to implement a temporary workaround by replacing the transform function with a custom one: https://gist.github.com/mstenta/3d7e6a02c37bbf9dd246116712c6bd8b

**Comment by chander** [comment]
@mstenta Great. So I think that solves part of the issue. The other issue IIRC (it’s been awhile since I looked at this issue) is that there’s no good way (once you fix the cords) how to determine the direction of the drawing (I.e., does it span all the way around the world to the other side of the IDL or does it cross the IDL.)

IIrc the best fix I had come up with was to shift to a projection where you stick the IDL  on the other side of the world, and then use that projection for storing/creating the drawing (where the IDL isn’t an issue) or something along those lines. Doing that poses a whole range of other technical challenges (I can see then how you could store the drawing, but rendering it in a wms service might prove challenging when reprojecting to wgs84 or spherical Mercator .)

The other option is to split the drawing into two geometries, one with the part on one side of the IDL and the other with the part in the other side (that case obviated the need for any projection trickery, but has its own set of challenges.)

I’m guessing that these kinds of challenges are what prevented a real fix from getting implemented thus far.

**Comment by chander** [comment]
As a side note, we have a similar issue generally with WMS services (not ol related) but that’s an easier case, since we can tell from the bbox if we have an IDL crossing and split wms requests (we do it via a proxy) into two (one on each side of the IDL) and then merge the two images.  That’s much easier since bboxes are generally easy to differentiate as IDL crossing due to zoom levels limiting the request-able areas.

**Comment by mstenta** [comment]
Thank you for the feedback @chander - I hadn't considered the case where drawings cross the date line. And in fact @mike-000 brought up the same consideration in the PR comments.
