### ISSUE TITLE
Zoom sensitivity on OS X to high

### ISSUE THREAD

**Issue by Turbo87** [openlayers/openlayers#3924]
I am using ol3 on a MacBook Air with OS X Yosemite and when I try to zoom using two fingers on the touchpad it zooms reeeeally fast. If I move my finger for only a millimetre it basically zooms through all available zoom levels.

**Comment by tschaub** [comment]
I agree it would be nice to make touchpad zooming on OSX more natural.

**Comment by Turbo87** [comment]
leaflet seems to throttle the events, which causes pauses between each zoom. the only other thing I've found on this topic is http://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers.

**Comment by Turbo87** [comment]
looking at https://github.com/openlayers/ol3/blob/master/src/ol/interaction/mousewheelzoominteraction.js it seems like that is actually a more or less direct port of the leaflet behavior.

**Comment by Turbo87** [comment]
looks like there is also some code in the closure-library that deals with or maybe even causes this:

https://github.com/google/closure-library/blob/master/closure/goog/events/mousewheelhandler.js#L216-L237

**Comment by Turbo87** [comment]
seems like this was fixed, thanks :)
