### ISSUE TITLE
Map crashes when trying to calling view#fit with an infinite extent

### ISSUE THREAD

**Issue by alvinlindstam** [openlayers/openlayers#3925]
ol.view#fit throws an error and clears the map when called with an infinite extent. Obviously Infinity can't be fitted to the view, but a more gracious behaviour could be nice.

Example: http://jsfiddle.net/7av5agym/2/

What would be the proper response to calling it with `[Infinity, Infinity, -Infinity, -Infinity]`? No-op or zooming out as much as possible?

**Comment by landryb** [comment]
I've hit that exact same issue, and i think fit() should check if all passed values are finite, ie checking extent.filter(isFinite).length == 4 maybe....
