### ISSUE TITLE
Getting postrender events before anything gets drawn

### ISSUE THREAD

**Issue by jtorresfabra** [openlayers/openlayers#3974]
Hi, 

I'm doing some integration of ol3 in the osgjs 3D scenegraph. It works quite well so far (http://webkeux.com/openlayers3). I just getting canvases in a postrender event and stick them to my 3D tiles. Controls: Mouse wheel to zoom, left button to rotate and right button to pan. 

But I'm having an awkward issue: 

In the initialization of the map I'm getting postrender events before the map is painted. I had to "hack" the code to check that the first pixel is not transparent, to continue requesting that tile image. This is not a very good solution because I probably need to paint transparent tiles too. 

This is the URL without the check and some debug info painted in each tile(http://webkeux.com/openlayers3-error/). As you can see some tiles are drawn transparent because the postrender events fires before the map is painted. 

Any idea of why I'm getting postrender events before the map gets painted? 

Relevant code I used:

```
var postRender = function ( event ) {
                var viewport = that.map.getViewport();
                var canvas = viewport.getElementsByTagName( "canvas" )[ 0 ];
                that.map.unByKey( key );
                var canvasCopy = cloneCanvas( canvas );
                defer.resolve( canvasCopy );
            };

var key = this.map.once( 'postrender', postRender );
view.fit( extent, [ 128, 128 ], { constrainResolution: false } );
```

**Comment by elemoine** [comment]
The `postrender` event is emitted at the end of each render/animation frame (executed in a requestAnimationFrame callback). When `postrender` is emitted there may be tiles that are still being loaded for a layer. Not fully sure this answers your question.

**Comment by jtorresfabra** [comment]
@elemoine thanks for your answer. So is there a method to know when the map is totally rendered? I tried also with moveend event.

**Comment by elemoine** [comment]
There are no map-level events at the moment. There are layer-level events though. See http://openlayers.org/en/master/examples/tile-load-events.html and http://openlayers.org/en/master/examples/image-load-events.html for examples.

**Comment by jtorresfabra** [comment]
@elemoine It seems tileloadend also arribes before it should. http://webkeux.com/openlayers3-error/  Maybe I'm doing somehting wrong...

**Comment by jtorresfabra** [comment]
Umm ok I was not doing it right, I need to check that every tile inside the map has ended.

**Comment by jtorresfabra** [comment]
Anyway it would be very nice to have an event when the map has completed the render.

**Comment by bampakoa** [comment]
@jtorresfabra Did you find any solution to this?
