### ISSUE TITLE
Add 'movestart' event on map. 

### ISSUE THREAD

**Issue by shaunakv1** [openlayers/openlayers#3985]
Just like there is a 'moveend' event available on map, it would be very convenient to have a `movestart` event.

**Use Case**
In case when triggering a `ol.animation.pan` I may want to toggle once before the animation starts and toggle it back once after animation ends. 
We have to remember here that animation might not actually happen based on where we are panning to. So just doing something before triggering pan is not enough, because toggle back might not happen if it doesn't actually pan (`moveend') doesn't get called in this event. 

**fix 1**
This can be fixed , if `moveend` is called even if the actual move doesn't happen, if pan was triggered. 

**fix2**
`movestart` event should be provided which just like `moveend` _doesnt_ get called if there is no movement happening in the map. 

Currently it is possible to achieve this using `map.beforeRender` but, it just seems too much ugly coding to achieve something very simple. 

*\* current  solution**

``` javascript
           var pan = ol.animation.pan({
                duration: 700,
                source: map.getView().getCenter()
            });

            map.beforeRender(function(map, frameState) {
              var stillPanning = pan(map, frameState); // returns false panning is done

              if (stillPanning){
                 // do movestart stuff here
                 if(!everDone){
                       doSomething();
                       everDone = true;
                  }
              }
              else{
                 // do move end stuff here
                 undoSomething();
                 everDone = false; 
              }              
              return stillPanning;
            });

            map.getView().setCenter(geom);    
```

This could all have been done in two simple  `map.on("movestart")` and  `map.on("moveend")` callbacks like it was supported in OpenLayers2. 

Here's a [jsFiddle](http://jsfiddle.net/j2cP4/114/) that demonstrates what I need to do with the non-ideal solution I posted.  Try pressing the pan-map second time and see how `moveend` does not fire, but animation end does. 
## update

I have updated my original question and answer on stackoverflow to summarize the discussion here: 

[http://stackoverflow.com/questions/31896300/openlayers-3-movestart-event-on-map/31897512](http://stackoverflow.com/questions/31896300/openlayers-3-movestart-event-on-map/31897512).
Thanks!

**Comment by elmuSSo** [comment]
I would also like to see movestart event.

**Comment by shaunakv1** [comment]
@elmuSSo I have working example of a solution in my stack-overflow question. Its not ideal but works just fine. Still agree it would be good to have that event generated by the OL3

**Comment by milovanderlinden** [comment]
+1, this is really a great miss when upgrading an ol2 application that uses navhistory to ol3. And please, don't tell me to look at the permalink example ;-)

**Comment by ahocevar** [comment]
@milovanderlinden I'm failing to understand how a movestart event would help you with navigation history. Are you sure you commented on the correct ticket?

**Comment by milovanderlinden** [comment]
Yes, I am. Sorry if I got you confused.

I have an application using ol2 that has had http://dev.openlayers.org/releases/OpenLayers-2.6/doc/apidocs/files/OpenLayers/Control/NavigationHistory-js.html implemented on custom buttons since day 1. So when I cherry-picking upgraded it, I discovered that the navigation control was missing in ol3. Then I tried to recreate it "ol3-style", but I noticed that there is no setCenter(center, zoom); so I tried to call the actions individually, to find out they firing seperate moveend events and when I added rotation, even 3. 

Then I got stuck in un('moveend') not un-ing the way I wanted, duplicating movend triggers. And finally, using moveend complicated array manipulation for the back and forward arrays. So I stopped trying.

It would be nice if I could rewrite duplicate https://github.com/cscott530/leaflet-history for ol3. It uses movestart.

Perhaps this is the wrong discussion. But I am strongly in favour of having a movestart event.

**Comment by joaorodr84** [comment]
Hi. It seems the 'movestart' event is still not available in OpenLayers 3.17.1. Are you planning to add that event? It is really useful. Thanks

**Comment by ahocevar** [comment]
You can simulate a movestart event with the following code:
```js
function onpropertychange() {
  console.log('movestart');
  map.getView().un('propertychange', onpropertychange);
  map.on('moveend', function() {
    map.getView().on('propertychange', onpropertychange);
  });
};
map.getView().on('propertychange', onpropertychange);
```

**Comment by shaunakv1** [comment]
Listening to `map.getView().on('propertychange', onpropertychange);` will also get triggered when the user zooms and not just on pan though.

**Comment by fredj** [comment]
@shaunakv1 try to use `'change:center'` instead of `'propertychange'`

**Comment by shaunakv1** [comment]
Center updates when the map zooms we well, so it still gets triggred: 

Example: 
[http://jsfiddle.net/5mwpq7g1/2/](http://jsfiddle.net/5mwpq7g1/2/)

**Comment by joaorodr84** [comment]
@ahocevar Thank you for your precious suggestion. It seems to work exactly like I wanted. :)

@fredj Thanks. I use 'change:center' and it it triggers only on pans. ;)

@shaunakv1 In your fiddle, the 'movestart' event gets triggered on each mouse move. I use 'change:center' everywhere. And so, it only gets triggered once ant the start of a pan. See my [fiddle](http://jsfiddle.net/z8k21vhz/).

Thank you to all of you. :D

**Comment by cs09g** [comment]
but this solution creates a lot of moveend event. maybe the side effect is when you add two listeners on movestart event, it runs 4 times(2 x 2).

**Comment by ischas** [comment]
@joaorodr84 If you zoom with mousewheel or doubleclick, 'change:center' will be triggered as well.

**Comment by cs09g** [comment]
@ischas that's expected behavior. it's the same when you use 'moveend' event. zoom event triggers moveend event as well.

**Comment by ahocevar** [comment]
@cs09g  We're talking about `movestart` here, not `moveend`.

**Comment by cs09g** [comment]
@ahocevar I mean, zoom events trigger movestart as moveend does

**Comment by ischas** [comment]
@cs09g It was mentioned by @joaorodr84 that the 'change:center' were just triggered on pans. And this is wrong and this is what I've said.

**Comment by cs09g** [comment]
@ischas oh, you're right, i'd missed that mention.

**Comment by shaunakv1** [comment]
@joaorodr84 even in your fiddle it gets triggered when you zoom using your mouse, and it isn't doing the wrong thing. Center indeed changes when you zoom with mouse wheel and that counts as a pan. I was just pointing it out.

**Comment by joaorodr84** [comment]
@shaunakv1 @ischas 

You are absolutely right. With mousewheel and doubleclick zoom, the center also changes. I hadn't noticed, but it is clearly true. It makes perfect sense. My mistake! :) Thanks for ponting it out.  have to change my code now, because I want tis behaviour:

- normal drag pan --> triggers my onPan callback
- zoom --> triggers an my onZoom callback
- zoom by mouse wheel --> even though the center changes, I want to trigger ONLY my onZoom callback
- zoom by double click --> even though the center changes, I want to trigger ONLY my onZoom callback

I think I am almost there. Thanks again. :)

**Comment by dbaston** [comment]
```
  map.on('moveend', function() {
    view.on('propertychange', onpropertychange);
  });
```

Should this be `map.once` ?

**Comment by wayofthefuture** [comment]
I don't understand why we don't have movestart, moveend, zoomstart, and zoomend. It doesn't make any sense. We have switched a huge application over to OL3 from OL2 and these events are the heart of our application. So now we are just plain @#$#@&.

**Comment by wayofthefuture** [comment]
I was able to get it working using ahocevar's solution above. The only problem now is that it is kind of interfering with the "singleclick" event. If you don't click the map perfectly it will trigger the movestart and not the singleclick event. When I say perfectly, if there is ANY x/y movement of the motion when you click, it will interpret it as a movestart event and not a singleclick event. Anyone have any ideas of how to make the movestart event less sensitive or the singleclick take prevalence over the movestart event? Thanks.

**Comment by ahocevar** [comment]
Reading all this, I think a `movestart` map event would make sense to make people's lives easier. Accepting pull requests.

**Comment by shaunakv1** [comment]
Thank you for adding a official 'movestart' event @ahocevar !!
