### ISSUE TITLE
Getting an error when using forEachLayerAtPixel

### ISSUE THREAD

**Issue by gerald27** [openlayers/openlayers#3991]
Hi guys,

Anyone encountered this problem. So I was using forEachLayerAtPixel for hit detection so that I can change the cursor when hovering to a wms layer but the problem is that I always getting this error:

Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

Btw this is my code.

```
olmap.on('pointermove',function(evt) { 
    if (evt.dragging) {
        return;
    }
    var pixel = olmap.getEventPixel(evt.originalEvent);
    var hit = olmap.forEachLayerAtPixel(pixel, function(layer) {
        return true;
    });
    olmap.getTargetElement().style.cursor = hit ? 'pointer' : '';
});
```

Regards,
Gerald

**Comment by alvinlindstam** [comment]
See https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image.

Use the crossOrigin option on you Image/TileImage sources if you can. Otherwise the image data will not be available to ol3.

**Comment by DavidHequet** [comment]
or you are using SVG image with IE (all version)
