### ISSUE TITLE
moveend/forEachFeature Combination Delayed

### ISSUE THREAD

**Issue by nickwebha** [openlayers/openlayers#4034]
I have this (mostly working) code.

```
map.on("moveend", function(event) {
    var view = event.map.getView();
    var zoom = view.getZoom();
    var factor = configuration.map.zoom.maximum - zoom;
    var scale = 1;

    if ( factor > 0 )
        scale = .5 / factor;

    if ( scale <= configuration.unit.scale.dropoff )
        scale = 0;

    markers.forEachFeature(function(feature) {
        feature.get("icon_style").setScale(scale);
    });
});
```

Every time I zoom in or out I resize (via `setScale()`) icons on a vector layer.

The issue is it always happens one zoom too late. For example, zooming into my maximum level it should be set to 1 but nothing happens. If I zoom out one level it should be set to .5 but it scales to 1. Next zoom out it should be scaled to .25 but it scales to .5. Ect...

I am not sure if I am doing something wrong or callbacks are happening too late within OpenLayers 3.8.2...

**Comment by tsauerwein** [comment]
I would recommend taking a look at [StyleFunctions](http://openlayers.org/en/master/apidoc/ol.style.html#.StyleFunction). I think they are more appropriate for your use-case.

    var iconStyle = ...;
    var style = ...;

    function styleFunction(feature, resolution) {
      // calculate `scale` with the resolution parameter
      iconStyle.setScale(scale);
      return [style];
    }
    ...
    var vector = new ol.layer.Vector({
      source: ...
      style: styleFunction
    });

Here is an example: http://openlayers.org/en/master/examples/earthquake-clusters.html

**Comment by nickwebha** [comment]
If I am understanding this correctly this style (which includes the icon scale) would be set for all elements in the vector layer, right? If so that is an issue. In my project some icons have different style attributes (such as opacity). These need to be controlled independently at any given moment.

Am I correct in my understanding?

**Comment by ahocevar** [comment]
No. The styleFunction is called for each feature, with the feature and the resolution as arguments.

**Comment by nickwebha** [comment]
As a little experiment I removed my old feature size-changing code and replaced it with styleFunction:

    map.addLayer(new ol.layer.Vector({
    	source:	markers,
    	style:	function(feature, resolution) {
    		console.log(resolution);
    		feature.get("icon_style").setScale(resolution);
    		return [ feature.get("feature_style") ];
    	}
    }));

I do not get the console log output nor does the icon change size. It seems not to be called at all?
