### ISSUE TITLE
webgl support in export-map example

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#4042]
`preserveDrawingBuffer` must be `true`

**Comment by photostu** [comment]
Can you elaborate where this should be placed?

**Comment by fredj** [comment]
See https://github.com/openlayers/ol3/blob/master/src/ol/renderer/webgl/webglmaprenderer.js#L99
And the spec: https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1

`preserveDrawingBuffer` is `false` by default for performance reasons but it must be `true` to export the canvas with `toDataURL`

**Comment by photostu** [comment]
So you are suggesting a custom build to facilitate this?

**Comment by gberaudo** [comment]
Is it possible to change this value afterwards?

**Comment by photostu** [comment]
I'm also investigating capturing the pixel data of the canvas and placing into another canvas, but so far no luck

**Comment by photostu** [comment]
I modified the min.js file to solve this, FYI.

**Comment by gberaudo** [comment]
According to the WEBGL specification, there are other ways to get the
content of the buffer:

While it is sometimes desirable to preserve the drawing buffer, it can
cause significant performance loss on some platforms. Whenever possible
this flag should remain false and other techniques used. Techniques like
synchronous drawing buffer access (e.g., calling readPixels or toDataURL in
the same function that renders to the drawing buffer) can be used to get
the contents of the drawing buffer. If the author needs to render to the
same drawing buffer over a series of calls, a Framebuffer Object
<https://www.khronos.org/registry/webgl/specs/1.0/#WEBGL_FRAMEBUFFER> can
be used
