### ISSUE TITLE
ol.interaction.modify leaves vertexes behind if feature geometry is modified/replaced

### ISSUE THREAD

**Issue by kulmegil** [openlayers/openlayers#4087]
1) Map with active ol.interaction.modify 
(it has a collection of features that are modifiable at the given time)

2) one of the feature geometries is modifed or replace outside of ol.interaction.modify
(e.g. I have a different interaction that specifically handles moving geometries by drag, so that user can move entire polygon)

3) If geometry was replaced with different one then vertexes are orphaned. If it was simply modified (e.g. it's coordinates were translated into new location) then vertexes are only misplaced and dragging them will still modify the geometry. 

4) When removing feature from collection (deselecting it on map), interaction will cleanup only those vertexes that are still positioned "inside" of modified geometry shape. 

Wile deactivating/removing ol.interaction.modify from map will also remove all vertexes, but reactivateing/readding will readd orphans as well.
![vertex_lost](https://cloud.githubusercontent.com/assets/570575/9718900/e9faacee-557f-11e5-85ba-8dad54ab3439.png)

**Comment by alvinlindstam** [comment]
Excellent error report.

This has already been fixed in https://github.com/openlayers/ol3/pull/4011
