### ISSUE TITLE
Features are not updated on vertex deletion in ol.interaction.Modify

### ISSUE THREAD

**Issue by ghost** [openlayers/openlayers#4118]
https://jsfiddle.net/wn8pv1Lz/
If you move or add a vertex, the area is updated properly. If you delete a vertex (by clicking on it), "modifyend" is fired, but the geometry is not updated and the area remains the same.

**Comment by alvinlindstam** [comment]
Yes, currently the modifyend event is triggered before the vertex is deleted. I consider this a bug, and have submitted a PR: https://github.com/openlayers/ol3/pull/4036
