### ISSUE TITLE
Overview map - ol.control.OverviewMap -  bounding rectangle error in a rotated map

### ISSUE THREAD

**Issue by Sverre-Iversen** [openlayers/openlayers#4119]
The rectangle in the overview map representing the area in the main map is changing in shape when the main map is rotated. A map rotation should not result in a change in the rectangle's shape if the size of the viewport is fixed.

Example: http://openlayers.org/en/v3.9.0/examples/overviewmap.html - turn on the overview map and rotate the main map.

See  also the related comments in #4116

**Comment by ahocevar** [comment]
Thanks @Sverre-Iversen for the bug report. Do you think you'd be able to provide a pull request? I think the desired behaviour for the overview map would be that the rectangle rotates instead of the map.
