### ISSUE TITLE
ol.control.FullScreen doesn't fire any event

### ISSUE THREAD

**Issue by jonataswalker** [openlayers/openlayers#4125]
Trying to answer this question http://gis.stackexchange.com/q/162136/50718 I realized that the only way to listen to `fullscreenchange` on webkit browsers for instance is:

``` javascript
document.addEventListener("webkitfullscreenchange", function(evt) {
    console.log(evt);
});
```

Should the docs be changed or the event be listened on `ol.control.FullScreen` instead of [`goog.global.document`](https://github.com/openlayers/ol3/blob/d3c8880b22c61b617989f4e3b5d9eaba1364385c/src/ol/control/fullscreencontrol.js#L70)?

**Comment by jonataswalker** [comment]
Since there's a great effort to get free of Closure Library dependency and `ol.control.FullScreen` itself has no event:
```javascript
//src/ol/control/fullscreencontrol.js
  goog.events.listen(goog.global.document,
      goog.dom.fullscreen.EventType.CHANGE,
      this.handleFullScreenChange_, false, this);
```
Is it worthy writing own fullscreen controller?

**Comment by azerbini** [comment]
@jonataswalker is there any reason why you closed this ticket? As far as I know, FullScreen still has no event.

**Comment by sookoll** [comment]
@jonataswalker, this issue should be reopen, since no event has fired in 4.2.0

**Comment by jonataswalker** [comment]
Well ... reopened.

**Comment by fredj** [comment]
The standard `fullscreenchange` event must be used, see:
 https://developer.mozilla.org/en-US/docs/Web/Events/fullscreenchange

**Comment by rasa2k** [comment]
This is still an issue I think

**Comment by philip-firstorder** [comment]
Can someone please merge @rasa2k changes?

**Comment by ahocevar** [comment]
Do we have a pull request with those changes?

**Comment by devel0** [comment]
Sure, opened PR #10564
