### ISSUE TITLE
ol.interaction.Translate and allowed drag destination extent (bug + feature request)

### ISSUE THREAD

**Issue by kulmegil** [openlayers/openlayers#4158]
I think this class needs some way to configure allowed drag extent - preferably one that can be dynamically changed without rebuilding class (for maps with restricted extent of view/operation)

Furthermore, it's possible now to drag a features outside world extent - they becomes unselectable (although keeps rendering).

**Comment by fmetdotmetoc** [comment]
This is still an issue. Not sure why this was closed. #4158 and #5378 link to each other without any solution to the problem.
