### ISSUE TITLE
how to get closest feature from tileWMS layer

### ISSUE THREAD

**Issue by yatenj** [openlayers/openlayers#4185]
Hi,
I want to find closest feature by a mouse click(coordinate) on map from tileWMS layer.
I was looking for documentation. using 
vectorSource.getClosestFeatureToCoordinate(coordinate) closest feature can be retrived.
This function is available for vector, cluser and tileVector source only..
but my layer source is tileWMS.

How to get closest feature of tileWMS source layer.
is there any other method/tool to achive this?

BR

**Comment by javimolla** [comment]
Maybe this example is what you need: http://openlayers.org/en/v3.0.0/examples/getfeatureinfo-tile.html

**Comment by yatenj** [comment]
javimolla, Thanks for reply.
This example gives feature info about a feature on which clicked.
My requirement is about to get nearest feature.
suppose in this example if I am clicking any where in the sea area, a nearest country to that click is to be shown as result.

BR

**Comment by javimolla** [comment]
Oh, sorry, it's true

Then it depends on the map server: in Geoserver there is a parameter of buffer to search on additional pixels [WMS vendor parameters] (http://docs.geoserver.org/latest/en/user/services/wms/vendor.html). But no standard on WMS

I found an answer on [stackexchange] (http://gis.stackexchange.com/questions/7871/specifying-arcgis-server-wms-getfeatureinfo-tolerance) that may help you. I didn't test it
