### ISSUE TITLE
ZoomSlider Control Fractional Zoom

### ISSUE THREAD

**Issue by GeorgeNarcis** [openlayers/openlayers#4251]
It seems that currently ZoomSlider Control doesn't support fractional zoom. Looking at the source code  I saw that the resolution is constrained using view.constrainResolution. 
For my use case I really needed the fractional zoom functionality so I manually overwrote ol functions.
 I was wondering if this should't be a configurable option, to enable or not the fractional zoom for the slider ?

Note: I am using Zoomify source for an image viewer

**Comment by ahocevar** [comment]
This is something you can easily configure on the view:
```js
map.getView().contrainResolution = function(resolution) {
  return resolution;
};
```
If you are already doing this, you're doing it the right way.

**Comment by GeorgeNarcis** [comment]
If I use this function, I lose the ability to change the resolution, the image can t be zoomed any more using the mouse wheel, the resolution remaining constant.

**Comment by ahocevar** [comment]
In this case, you'll have to conditionally reuse the original `ol.View#constrainResolution()` function, e.g.
```js
var view = map.getView();
var constrainResolution = view.constrainResolution;
view.constrainResolution = function(resolution, delta, direction) {
  return delta ?
    constrainResolution.call(view, resolution, delta, direction) :
    resolution; 
}
```

**Comment by ahocevar** [comment]
It may make sense to add a `constrainCenter` boolean property. If set to false, you would get fractional zoom.

**Comment by raiyni** [comment]
Would it make sense to add an option `contrainResolution` and if that's true, constrainResolution

here https://github.com/openlayers/openlayers/blob/master/src/ol/control/ZoomSlider.js#L284

and 

here https://github.com/openlayers/openlayers/blob/master/src/ol/control/ZoomSlider.js#L222

otherwise, animate to exact resolution
