### ISSUE TITLE
Do not use WGS84BoundingBox for TileGrid calculation

### ISSUE THREAD

**Issue by olt** [openlayers/openlayers#4256]
`ol.source.WMTS.optionsFromCapabilities` uses `WGS84BoundingBox` for calculation of the tile grid if available in the WMTS capabilities (added with 6ee0d9f92702e86e97513975ba2f12a01217eeee)

There are two issues with that:
- From the OGC WMTS spec: "This WGS84BoundingBox can be approximate, but SHOULD be as precise as practical."
- Transforming WGS84BoundingBox back to the projection of the TileMatrixSet does not need to return  the input BBOX. 

The following GeoJSON shows that the correct transformation of a BBOX is not reversible: https://gist.github.com/anonymous/2445ea91a8ac7b15bf39

**Comment by ahocevar** [comment]
So this means: use the bbox in matrix set projection if advertised, and fall back to wgs84bbox if not advertised? Can you create a pull request for that?

**Comment by olt** [comment]
Ok, I dug a bit deeper into the code. The tile grid calculation seems to be right. But it fails with the assert in https://github.com/openlayers/ol3/blob/v3.10.1/src/ol/tilegrid/tilegrid.js#L131
Maybe it makes sense to build the union of both tileRanges? Not sure if this would interfere with something else...

Using the native projection first and WGS84 box as a fallback should work. Not sure how common this is though (will have to add it to MapProxy), but I'm also not sure how common correctly projected WGS84 bounding boxes are ;-)
