### ISSUE TITLE
Respect view constraints when setting view properties

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#4265]
Currently, if you have a view with constraints, they are not respected when you directly set view properties.  For example, the following view has a center constraint based on the provided `extent`:

``` js
var view = new ol.View({
  projection: 'EPSG:4326',
  extent: [-180, -90, 180, 90],
  center: [0, 0],
  zoom: 1
})
```

I can now set the view center to something far outside this constraint:

``` js
view.setCenter([0, -1000]);
```

The view gladly asks the map to render the same.  And if I ask the view for the center, it reports what I set:

``` js
view.getCenter(); // [0, -1000]
```

This makes constraints seem a bit pointless.  Unless you are an interaction or some other code that knows to call something like `view.constrainCenter(maybeInsideMaybeOutside)`.

I think we've discussed this before, but I wanted to bring it up again.  What would happen if we made the convenient setters (e.g. `setCenter(center)`) respect the constraints and provided a different way to bypass the constraint (e.g. `setCenter(center, {constrain: false})`) or `unconstrainCenter(center)`)?

**Comment by elemoine** [comment]
I don't anticipate major problems with that, except that we'll break applications that (correctly) rely on the setters not applying the constraints.

The view currently exposes `constrainX` functions that one can use to get constrained values. For example:

```js
view.setCenter(view.constrainCenter(center));
```

So we do provide the functionality already. For that reason I think I wouldn't break people's applications (and upset them).

**Comment by ahocevar** [comment]
I agree with @tschaub that users expect constraint to be applied if they are set as constructor options (like e.g. an `extent`). I know that @elemoine likes the concept of `set*()` methods just setting properties, but we are not consequent with that either.

Another story is that it is very awkward to turn off constraints that are set as default, without the user asking for it (e.g. zoom constraint snapping to powers - see #4251, the zoom control relies on additional delta and direction handling).

**Comment by elemoine** [comment]
@ahocevar note that I did not say anything regarding "`set*()` methods just setting properties". I just said that the proposed change may break existing applications.
