### ISSUE TITLE
Memory Leaks in IE and Firefox

### ISSUE THREAD

**Issue by GeorgeNarcis** [openlayers/openlayers#4266]
I have an application developed using OL3, in which maps can be recreated quite often. My problem is that when I "destroy" a map and create a new one I'm seeing a constant increase in memory utilization looking at the task manager.
     I have created a basic fiddler with the problem here: http://jsfiddle.net/aLyrc95u/. It can be reproduced by clicking on create and destroy maps button and looking at the task manager.
    My app has many other features than this basic example so the increase in memory is even more drastic. On Chrome it seems to work just fine but on IE 11  and Firefox the memory goes crazy.
    I am not sure if I correctly release OL3 resources or this is a browser related problem. The code for cleaning old maps is the one presented in the fiddler.

**Comment by fredj** [comment]
See also #3420
