### ISSUE TITLE
ol.interaction.Snap doesn't snap on circle geometries

### ISSUE THREAD

**Issue by syerad** [openlayers/openlayers#4304]
The snap interaction doesn't snap on circle geometries!
Is this an intended behaviour of the snapping tool or a bug?
If there is any possibilty to snap on circles, please let me know...

**Comment by ahocevar** [comment]
Snapping to circles is not implemented.

**Comment by syerad** [comment]
Any reason why it's not implemented?

**Comment by ahocevar** [comment]
No funding, no contribution, not trivial to implement, not requested before.
