### ISSUE TITLE
Graticule wrapX

### ISSUE THREAD

**Issue by fito1987** [openlayers/openlayers#4308]
Hi there,

in Open Layers 2 the graticule control had the option of setting wrapX to true.

Is this something that can still be done in version 3, or is there a chance that this could be implemented?

Cheers
Rod

**Comment by ahocevar** [comment]
This could be implemented by drawing meridians and parallels for each world that's visible on the map, to a translated canvas. We'd accept pull requests if anyone wants to fix this.
