### ISSUE TITLE
Canvas tiles example no canvasFunction API

### ISSUE THREAD

**Issue by ChouGary** [openlayers/openlayers#4323]
Canvas tiles example only show xyz,
no way to show 「tile extent、tile url、tile json url、related features number」 for tile debug .
![image](https://cloud.githubusercontent.com/assets/8294943/10748647/50c934b0-7c9d-11e5-8de8-a18e263d23eb.png)

http://openlayers.org/en/master/examples/canvas-tiles.html
need api  『canvasFunction』 show custome message, like D3 sample
http://openlayers.org/en/v3.10.1/examples/d3.html

**Comment by ahocevar** [comment]
Would you be willing to create a pull request? Basically all you need to do is add a `textFunction` option to `olx.source.TileDebugOptions` in `externs/olx.js` and use that function in [`src/source/tiledebugsource.js`](https://github.com/openlayers/ol3/blob/master/src/ol/source/tiledebugsource.js#L113-L114), with a default of what we currently have.
