### ISSUE TITLE
Undefined zoom on moveend

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#4333]
I have a `moveend` listener that does the following:

```
var view = map.getView();
var zoom = view.getZoom();
```

Periodically, `zoom` is `undefined`.  This is unexpected.  Debugging now.

**Comment by tschaub** [comment]
Also unexpected:
```js
view.setZoom(1.5);
view.getZoom(); // undefined
```

**Comment by tschaub** [comment]
So, the two are related.  The `view.getZoom()` call only works when the current resolution matches a value returned for an integer zoom in `view.constrainResolution(maxZ, z)`.  We can do better than this.  In addition, it looks like `moveend` is getting called for non-integer zoom levels on touch devices (not sure if this is a feature or a bug).

**Comment by bartvde** [comment]
Right I've also seen this recently.

**Comment by bartvde** [comment]
Running into this one again.

**Comment by mlegenhausen** [comment]
+1

Maybe is seems to be possible to zoom in resolutions that are between zoomlevels, so no constrained resolution can be matched.

**Comment by dbazile** [comment]
Is there a suitable workaround for this other than peeking at private APIs (e.g., `view.maxResolution_`)?

**Comment by tschaub** [comment]
Getting this same issue in the 4.0 release.  I'll come up with a test case.
