### ISSUE TITLE
HR extension from a GPX file

### ISSUE THREAD

**Issue by xlhomme** [openlayers/openlayers#4352]
Here is an extract of my GPX file :
< trk>  
    < trkseg>
      < trkpt lat="48.897541388869286" lon="2.23947923630476" >
        < ele>49.0</ele>
        < time>2015-09-29T10:01:55Z< /time>
        < extensions>
          < gpxtpx:TrackPointExtension>
            < gpxtpx:hr>104< /gpxtpx:hr>
            < gpxtpx:cad>61< /gpxtpx:cad>
          < /gpxtpx:TrackPointExtension>
        < /extensions>
      < /trkpt> 

How to extract the extension informations form this GPX file ? 

 in the TRKPT_PARSERS_ function of the GPX format,
 there is no line to extract the extension part : Something like this :  'extensions': ol.format.GPX.parseExtensions_ 
ol.format.GPX.TRKPT_PARSERS_ = ol.xml.makeStructureNS( ol.format.GPX.NAMESPACE_URIS_,
 { 'ele': ol.xml.makeObjectPropertySetter(ol.format.XSD.readDecimal),
   'time': ol.xml.makeObjectPropertySetter(ol.format.XSD.readDateTime) }); 

xl

**Comment by fredj** [comment]
You can pass a `readExtensions` property to `ol.format.GPX`:
```javascript
new ol.format.GPX({
  readExtensions: function(feature, extensionsNode) {
    // ...
  }
});
```
See #2420

**Comment by xlhomme** [comment]
Hi 

 but there is no call for the  function that we can add to the readExtensions property in the following function :
```javascript
ol.format.GPX.RTEPT_PARSERS_ = ol.xml.makeStructureNS(
    ol.format.GPX.NAMESPACE_URIS_, {
      'ele': ol.xml.makeObjectPropertySetter(ol.format.XSD.readDecimal),
      'time': ol.xml.makeObjectPropertySetter(ol.format.XSD.readDateTime)
    });
```
