### ISSUE TITLE
Feature Animation Example raises IndexSizeError in Internet Explorer 11

### ISSUE THREAD

**Issue by wlerner** [openlayers/openlayers#4409]
The Feature Animation Example raises an IndexSizeError in Internet Explorer 11 (v. 11.09600.18097).  

![error pic 2](https://cloud.githubusercontent.com/assets/14095650/11125651/1f843942-8939-11e5-91f6-f3530816df7e.PNG)

![error pic 1](https://cloud.githubusercontent.com/assets/14095650/11125619/fd2774cc-8938-11e5-9662-869ed6179539.PNG)

![error pic 3](https://cloud.githubusercontent.com/assets/14095650/11125781/c1e87978-8939-11e5-8ec7-b75a0c089278.PNG)

This error is reproducible.  I am using version 3.11.0 of OL.

Is it possible that a canvas is being rendered with a size of zero and that IE cannot render an element with a size of zero?

**Comment by tschaub** [comment]
I've been seeing this as well.  In the debugging I've done, I've seen calls to `context.drawImage(image, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight)` where `sWidth` and `sHeight` are non-integer values.

There have been a few changes recently that affect the calculation of values sent to `drawImage`.  I'll take some time now to see if I can come up with a simple case that fails.

@wlerner if you can put together a simple example that demonstrates the problem, that would be great.

**Comment by tschaub** [comment]
Ok, after a lot of (painful) debugging, I've determined that the error we were seeing was due to using an SVG as the source for `ol.style.Icon` *without* explicitly setting the `size`.  In other browsers, the resulting image had a non-zero size.  In IE, the image had 0 width and height, so we end up calling `context.drawImage()` with 0 for `sWidth`, `sHeight`, `dWidth`, and `dHeight`.  This results in the `IndexSizeError`.

There could still be a bug in the library, but I couldn't identify a regression.  @wlerner I'd be curious to see if you can reproduce the problem with a simple example.

**Comment by tschaub** [comment]
Wow, not sure how I missed that you said (in both the title and description): http://openlayers.org/en/v3.11.1/examples/feature-animation.html

I am not seeing this error with Internet Explorer 11.0.9600.17937.  Maybe if I leave this machine on long enough for an upgrade, I'll see it.

**Comment by wlerner** [comment]
Without looking at the code, might I suggest a test for width and height?  For example, if this is how the canvas is rendered:
```
            newCanvas = doc.createElement('canvas'); 
            newCanvas.width = bounds.width; 
            newCanvas.height = bounds.height; 
            context.drawImage(canvas, bounds.left, bounds.top, bounds.width, bounds.height, 0, 0, bounds.width, bounds.height); 
```
Then this is the test:
```
            if (newCanvas.width <= 0 && newCanvas.height <= 0) { 
            context = newCanvas.getContext("2d"); 
            context.drawImage(canvas, bounds.left, bounds.top, bounds.width, bounds.height, 0, 0, bounds.width, bounds.height); 
            } 
```

**Comment by wlerner** [comment]
The Feature Animation Example issue continues to raise an IndexSizeError in Internet Explorer 11 (v. 11.09600.18097) with OpenLayers 3 (v. 3.11.2). 

![error pic 6](https://cloud.githubusercontent.com/assets/14095650/11539111/6086b518-98f3-11e5-9d95-3a45d468a74d.PNG)

![error pic 5](https://cloud.githubusercontent.com/assets/14095650/11539063/39c2d060-98f3-11e5-9ea3-35358573a93b.PNG)

**Comment by wlerner** [comment]
My IT staff updated the version of IE on my IS at work.  The Feature Animation Example issue continues to raise an IndexSizeError in Internet Explorer 11 (v. 11.0.9600.18124) with OpenLayers 3 (v. 3.11.2).

![error pic 9](https://cloud.githubusercontent.com/assets/14095650/11758413/bd360cea-a038-11e5-9988-657b40316b38.PNG)
![error pic 8](https://cloud.githubusercontent.com/assets/14095650/11758416/c1377612-a038-11e5-9d86-e732e84ac452.PNG)

**Comment by wlerner** [comment]
The Custom Animation Example (formerly the Feature Animation Example) raises an IndexSizeError in Internet Explorer 11 (v. 11.09600.18097) and Firefox (v. 36.0.4) with OpenLayers 3 (v. 3.12.0). 

![error pic 14](https://cloud.githubusercontent.com/assets/14095650/11821737/0bab1944-a339-11e5-87c2-b7901bdabef2.PNG)

![error pic 13](https://cloud.githubusercontent.com/assets/14095650/11821745/10f3c3ce-a339-11e5-8341-efddfa78b2cc.PNG)

**Comment by ahocevar** [comment]
I'm unable to reproduce this. Any specific steps you took to trigger the error @wlerner?

**Comment by wlerner** [comment]
There are no specific steps taken to trigger the error.  Sometimes the error happens fairly quickly when the page is loaded and other times is can take a while.  @tschaub found the issue on November 12th (comment above).  

I was able to reproduce the error this morning using Firefox (v. 42) on a Mac.  It took ~5 minutes for the error to manifest itself using the example below:

http://openlayers.org/en/v3.12.1/examples/feature-animation.html

![screen shot 2015-12-18 at 8 19 23 am](https://cloud.githubusercontent.com/assets/14095650/11897746/3a89129c-a560-11e5-9bd6-842cc7c05827.png)

**Comment by ahocevar** [comment]
I got none of these. I'm also on OSX and left the example running for at least an hour in both Safari and Firefox. @tschaub could not reproduce the problem either, see https://github.com/openlayers/ol3/issues/4409#issuecomment-156276703 (he was seeing a different, unrelated issue).

**Comment by wlerner** [comment]
I can still reproduce this issue with ease on different computers, with different operating systems, and different browsers.  I modified the example slightly today to speed the process up of having the error occur.

The original code:
```
window.setInterval(addRandomFeature,1000);
```

The modified code:
```
window.setInterval(addRandomFeature, 10);
```

With this simple change I can manifest the error much more quickly.  

While @tschaub could not reproduce the problem, he did identify the problem https://github.com/openlayers/ol3/issues/4409#issuecomment-156265897 here.  Additionally, he did mention that he had been examining this issue https://github.com/openlayers/ol3/issues/4409#issuecomment-156217186 here.

Normally, I would agree that this is a fringe case and might be left alone.  I am pursuing this issue in particular as I am using this exact animation in a project and seeing the same issue.  The fact that I can replicate this with the example provided in the OL3 examples makes this an easy error to demonstrate.

The error I mentioned in Safari (https://github.com/openlayers/ol3/issues/4409#issuecomment-165776349) is not the same as the ```IndexSizeError``` and was only something I pointed out while investigating the ```IndexSizeError``` on my Mac at home.  I apologize for redirecting the focus of my original posting.

**Comment by ischas** [comment]
I was able to reproduce this with Win10 Pro V1511...
...on Firefox V42.0 and V43.0.1 (with Firebug V2.0.13, OL on master and 3.12.1):
![image](https://cloud.githubusercontent.com/assets/8558126/11908901/efd5f7ac-a5e0-11e5-9a82-4d60d2546fef.png)
...on IE 11 V11.20.10586.0 (OL on master):
![image](https://cloud.githubusercontent.com/assets/8558126/11908993/fa39f1f2-a5e1-11e5-8433-2bc87f45afdf.png)
...on Chrome V47.0.2526.106 (OL on master and 3.12.1) the tab hangs-up:
![image](https://cloud.githubusercontent.com/assets/8558126/11909030/4dd04ce4-a5e2-11e5-831f-f4a8c861b07c.png)

No problem with Edge.

Surprisingly, the error occurs on different lines. IE11 states a memory problem.

**Comment by wlerner** [comment]
The Custom Animation Example (formerly the Feature Animation Example) raises an IndexSizeError in Internet Explorer 11 (v. 11.09600.18163)

http://openlayers.org/en/v3.12.1/examples/feature-animation.html

![error pic 16](https://cloud.githubusercontent.com/assets/14095650/12397620/556723ee-bddc-11e5-9c42-4e54665ec135.PNG)

![error pic 15](https://cloud.githubusercontent.com/assets/14095650/12397613/4e714c04-bddc-11e5-80c4-55bd9f27cbfc.PNG)

![ie version pic 1](https://cloud.githubusercontent.com/assets/14095650/12397648/829a339c-bddc-11e5-9db6-a065369c3f3b.PNG)

**Comment by wlerner** [comment]
The Custom Animation Example continues to raise an IndexSizeError in Internet Explorer 11 (v. 11.09600.18163) with OL v. 3.13.1.

![error pic 17](https://cloud.githubusercontent.com/assets/14095650/12893086/30e61174-ce5d-11e5-977b-313c55d5fab2.PNG)

![error pic 18](https://cloud.githubusercontent.com/assets/14095650/12893137/7dc5ca84-ce5d-11e5-9e82-825c1b5e57aa.PNG)

**Comment by wlerner** [comment]
The Custom Animation Example continues to raise an IndexSizeError in Inernet Explorer 11 (v.11.09600.18204) with OL v. 3.14.0.  

http://openlayers.org/en/v3.14.0/examples/feature-animation.html

![error pic 20](https://cloud.githubusercontent.com/assets/14095650/13297684/860d0a6c-db01-11e5-99e0-1bb4b513cf29.PNG)

![error pic 19](https://cloud.githubusercontent.com/assets/14095650/13297652/5dde9da8-db01-11e5-8f1d-9b03913d3252.PNG)

**Comment by tschaub** [comment]
@wlerner are you able to reproduce this while running the example in "development" mode (http://openlayers.org/en/v3.14.0/examples/feature-animation.html?mode=raw)?  We'd have a better stack trace if not using the full ("production") build.

We also see a lot of these unhandeled `IndexSizeError` in applications at work from users on IE 11 - just more evidence that this is a real issue.

**Comment by tschaub** [comment]
Ideally, you could also break on these errors and report back some detail about the values being passed to the `drawImage` call.

**Comment by wlerner** [comment]
I am able to reproduce this while running in the "development" mode.  Below are some more screenshots that I hope are helpful.

![error pic 22](https://cloud.githubusercontent.com/assets/14095650/13299103/a23498a8-db07-11e5-8e3b-1540cc4bccf1.PNG)

![error pic 21](https://cloud.githubusercontent.com/assets/14095650/13299074/83986b90-db07-11e5-81e1-aec470bd369e.PNG)

![error pic 23](https://cloud.githubusercontent.com/assets/14095650/13299139/d16450e6-db07-11e5-88b5-f8048364782d.PNG)

**Comment by tschaub** [comment]
Thanks @wlerner.  That is getting more useful.  The `x` and `y` values look like potential problems in that last screenshot.  It would be great to have values for these in your [first screenshot](https://cloud.githubusercontent.com/assets/14095650/13299074/83986b90-db07-11e5-81e1-aec470bd369e.PNG):

 * `this.imageOriginX_`
 * `this.imageOriginY_`
 * `this.imageWidth_`
 * `this.imageHeight_`
 * `x`
 * `y`

**Comment by wlerner** [comment]
You read my mind..

![error pic 25](https://cloud.githubusercontent.com/assets/14095650/13300216/14c03210-db0d-11e5-8012-62bfe224282d.PNG)

**Comment by icholy** [comment]
I'm having the exact same issue after switching to using SVGs with `ol.style.Icon`. Adding the `size` property didn't help.

**Comment by icholy** [comment]
Here's a test case: https://github.com/icholy/svg_error_example 
I created a repo instead of a gist so I can include the svg.

**Comment by ahocevar** [comment]
`imgSize` is the property you should be setting, not `size`.

**Comment by icholy** [comment]
@ahocevar thank you!
