### ISSUE TITLE
simple text styling example

### ISSUE THREAD

**Issue by Matthias84** [openlayers/openlayers#4422]
Hi there, currently there is an pretty [advanced example](http://openlayers.org/en/v3.11.1/examples/vector-labels.html) about how to use text labels. This is IMHO to complex for everybody who just wants to get started, so can you please add a simple example to show the necessary snipets?

**Comment by tschaub** [comment]
I agree the existing example is a bit overwhelming.  I'd be in favor of removing it and replacing it with a basic example.

**Comment by Matthias84** [comment]
Thanks @tschaub :-) To me it was pretty confusing, that I have to style text explicitly, whyle usual features get a default styling.
