### ISSUE TITLE
wcs support

### ISSUE THREAD

**Issue by topwood** [openlayers/openlayers#4451]
I find an example uses a ol.source.Raster to generate data based on another source.[Raster](http://openlayers.org/en/v3.9.0/examples/shaded-relief.html). but why not ol3 support OGC wcs service. And,it seems that ol3 do not support read wfs getcapabilites, but support wmts and wms.
will you do this work in the future?

**Comment by bartvde** [comment]
For WFS GetCapabilities I suggest looking into JSONIX instead

**Comment by thiagogcm** [comment]
+1
