### ISSUE TITLE
KML: <outline> from <PolyStyle>

### ISSUE THREAD

**Issue by jaforom** [openlayers/openlayers#4466]
Hi all,

If I load the attached KML, OL3 doesn't show it because the KML has a PolyStyle with outline=0. This KML only has a LineString (MultiGeometry), so PolyStyle shouldn't affect to LineString appearance, I think. If the value of outline is 1, or if I delete the outline element, OL3 loads the KML right and shows the LineString. Any idea about this?

Thanks
[doc.txt](https://github.com/openlayers/ol3/files/40087/doc.txt)

**Comment by toddsoc** [comment]
I noticed the same problem.
[simple_line.kml.zip](https://github.com/openlayers/openlayers/files/1420237/simple_line.kml.zip)

The problem is at line 1048 of src/format/kml.js

The offending lines are:
if (outline !== undefined && !outline) {
    strokeStyle = null;
}

This results in a null stoke style being returned.
