### ISSUE TITLE
Clustering threshold feature not present in openlayers 3

### ISSUE THREAD

**Issue by Devlin1001** [openlayers/openlayers#4526]
In openlayers 2.8 there was a threshold associated with the cluster strategy as per ticket:
https://trac.osgeo.org/openlayers/ticket/1815

This feature has never been ported to openlayers 3.
http://openlayers.org/en/master/apidoc/ol.source.Cluster.html

**Comment by pke** [comment]
Hmm... So that means at the moment, when using clustering only the clustered items style is used? I had also hoped that individual features are not clustered if there is only one feature that would go into the cluster.

**Comment by bartvde** [comment]
You can handle all this in your style functions

**Comment by bartvde** [comment]
See this for an example: http://jsfiddle.net/bartvde/3dv1wdho/6/

**Comment by pke** [comment]
Thanks, how would that work if the default style should display some (dynamic) property of the feature?

**Comment by bartvde** [comment]
then you would maintain a styleCache for those ones as well, and return that one based on the feature attribute

**Comment by pke** [comment]
Not sure I understand. When the threshold is 4, and all 4 features have different properties, their style would be different. However you can only return one style object from the style function, can't you? If you were to return an array of styles, then they would just be composed on top each other, wouldn't they?

**Comment by bartvde** [comment]
You can simple return a different style based on the feature attribute, there are many ol3 examples that showcase this

**Comment by bartvde** [comment]
Ah I see what you mean now

**Comment by bartvde** [comment]
then the only solution would be to add the individual features of the cluster below the threshold to the source as well

**Comment by freemindaz** [comment]
Hello. Interested in the burning question for me. Why not work with clustering ol.geom.MultiPoint.? and will you add this functionality in the future?

**Comment by fredj** [comment]
> Why not work with clustering ol.geom.MultiPoint.? and will you add this functionality in the future?

See #4917
