### ISSUE TITLE
File ol.js does't contain abstract classes.

### ISSUE THREAD

**Issue by winsento** [openlayers/openlayers#4531]
The file ol.js does't contain abstract classes.
For example:

```
formatXMLFeature = function(opt_options) {
  ol.format.XMLFeature.call(this, opt_options);
};
ol.inherits(formatXMLFeature, ol.format.XMLFeature);
```

This code return `Uncaught TypeError: Cannot read property 'prototype' of undefined` because `ol.format.XMLFeature` is not defined.

**Comment by winsento** [comment]
Why `ol.xml` contain only 2 methods `getAllTextContent` and `parse`? How i can extend ol.format.XMLFeature?

**Comment by probins** [comment]
> How i can extend ol.format.XMLFeature?

with difficulty. I just had a similar issue trying to create a custom format to handle data from a MongoDB, where the geometry is GeoJSON but the attributes are at the top level and not in a separate 'properties' object. First you have to create a custom build which exports the class you want to extend. This isn't enough though if you want to use the xhr featureloader, as this needs `getType()` and `readProjection()`, which are in obfuscated form. AFAIK, the only way to get this to work is to compile your custom format in with the ol build so these functions are similarly obfuscated. I decided this was more trouble than it was worth, and created my own format object with `readFeatures` etc, and my own loader function.

One of the disadvantages of GCC advanced builds, I'm afraid. The situation should improve if and when the current structure is converted to ES6 modules, as you would then be able to extend the exported classes/functions as you like.

**Comment by fredj** [comment]
closue compiler not used anymore, closing
