### ISSUE TITLE
[UX] Search on API should include option parameters

### ISSUE THREAD

**Issue by jnachtigall** [openlayers/openlayers#4550]
I had a specific question (a so called unknown Unknown: I had no idea how to solve it). 

After searching the web and stackoverflow I knew it what something like `wrap` or `wrapDateLine` or similiar (now a so called known Unknown: at least I knew now that it had something to do with a setting like `wrap`). So I headed to the [API docs](http://openlayers.org/en/v3.11.2/apidoc) and typed `wrap` into the "Search Documentation" input field: No results.

After googling a lot more (many old results again) I eventually found that it is `wrapX` at http://openlayers.org/en/v3.11.2/apidoc/ol.source.Vector.html Still even an API search for `wrapX` returns nothing.

I think that the "options" parameters are really important. Not being able to find these easily is cumbersome. Please include the "options" of classes/constructors in the search

**Comment by marcjansen** [comment]
I agree abd we had discussions about this back in the days. Didn't @tschaub mention a nice way to include these results and highlight the match?
