### ISSUE TITLE
WFS 1.0.0 support could be better

### ISSUE THREAD

**Issue by taviroquai** [openlayers/openlayers#4569]
Hi,

I saw #2574 was closed but here is my situation:

I have 2 WFS sources.
1. uses WFS 1.0.0
2. uses WFS 1.1.0

I can read second source with no workaround and the features geometry as parsed correctly.

For case 1, I had to do the following workaround and it works fine with GML2.

```
    var gmlformat = (item.layer.wfs_version === '1.0.0' ? new ol.format.GML2 : new ol.format.GML3);
    var format = new ol.format.WFS({
        'gmlFormat': gmlformat
    });
```

Please consider.

**Comment by ahocevar** [comment]
If you find a way to set the GML version early enough in the parsing process (after determining the version of the WFS response), then please consider submitting a pull request.

**Comment by taviroquai** [comment]
Hi,

I'm trying to follow the ol3 architecture but its not easy for me...

Where is the implementation of ol.format.WFS.readFeatures? I found an implementation at ol.format.GMLBase.prototype.readFeaturesInternal. Is this implementation that is called?

What is the workflow when calling ol.format.WFS.readFeatures() ?

Thanks!
