### ISSUE TITLE
Feature text with background color

### ISSUE THREAD

**Issue by omnik** [openlayers/openlayers#4577]
I don't found how to create background box for ol.Feature text style.
Is it possible? It would be great if ol3 has such feature.

**Comment by ahocevar** [comment]
You can set a  `stroke` on your `ol.style.Text` to create a halo. A rectangular box is not possible.

**Comment by sanderd17** [comment]
The easiest to add a rectangular background is using an image. Creating a data-uri for an svg image is quite easy. Just do `data:image/svg+xml;utf8," + encodeURIComponent("<svg>...</svg>")` with a rectangle in the svg definition.

**Comment by szel** [comment]
I found this issue in 2017 and would like to elaborate. Why it is not possible? Seems like quite basic feature..

**Comment by ahocevar** [comment]
With the new text renderer, an image is created for the text anyway. That image could be given a stroke and fill. For `ol.style.Text`, there could be new `backgroundFill`, `backgroundStroke` and ´padding´ properties. Anyone interested in creating a pull request?

**Comment by marcjansen** [comment]
sounds like a nice improvement, @ahocevar.

**Comment by pavle-lekic-htec** [comment]
I have a problem, I have set the backgroundFill but for some reason it doesn't work. I'm using openlayers 4.4.2
Here is the code:

```
return new ol.style.Style({
        image: new ol.style.Icon({
            anchor: [0.5, 0.5],
            opacity: 1,
            scale: 1,
            src: 'public-images/map/stena_port_unselected.png'
        }),
        text: new ol.style.Text({
            offsetY: 20,
            text: portName,
            placement: 'point',
            textAlign: 'center',
            fill: new ol.style.Fill({color: 'rgb(255, 169, 163)'}),
            backgroundFill: new ol.style.Fill({color: 'black'}),
            padding: [3, 5, 3, 5]
        })
    });
```

Can you please help me? Am I doing something wrong?

**Comment by bartvde** [comment]
this code is not in 4.4.2, please try the latest release 4.6.2

**Comment by aaron1uk** [comment]
is there anyway yet implemented to have a radius setting to curve the background box?

**Comment by ahocevar** [comment]
No, there is not.
