### ISSUE TITLE
Node / npm - Cygwin - Windows

### ISSUE THREAD

**Issue by kalbermattenm** [openlayers/openlayers#4586]
I just had to update Node/npm for another project and ran into some problems. I am working on Windows 7 using @bill-chadwick's solution to run all the make commands through Cygwin.

I had to install Node 4.2.3 (and npm 3.5.2). Running a fresh install of the npm dependencies in ol3 made the `npm install` command hang up. The only way I managed to make it work was to run the following commands before `npm install`:

```
npm config set registry http://registry.npmjs.org/
npm config set strict-ssl false
```

After that, the whole `npm install` ran without errors (solution found <a href="https://github.com/npm/npm/issues/7862#issuecomment-161131935" target=_blank> here</a>). 

I do not know if I am the only one having this problem (and if this is again a Windows specialty)... ?

I also do not know what the two commands above really change... (that's never so good...)

Had anyone the same problem and is ol3 compatible with the given Node/npm versions ?

**Comment by fredj** [comment]
@kalbermattenm can we close this issue ?

**Comment by kalbermattenm** [comment]
Yes... sorry... Thanks ;-)
