### ISSUE TITLE
Black area around and inside map

### ISSUE THREAD

**Issue by najeebabualshar** [openlayers/openlayers#4624]
Hello .
I have a problem when use Ol3 with mapproxy and mapnik to get the layers from OSM database.
when I convert my work from Ol2 to Ol3 I see smoothing wrong when I zoom in/out in map I get some black area and Thank you for help :)

This is my code to show the map

``` js
map = new ol.Map({
            loadTilesWhileAnimating: true,
            loadTilesWhileInteracting: true,
            target : "map",
            controls: ol.control.defaults({
                attributionOptions: /** @type {olx.control.AttributionOptions} */ ({
                    collapsible: false
                    })
            }).extend([mousePositionControl]),
            view: new ol.View({
               projection: "EPSG:4326",
               center: myLatLng,
               zoom : 6
            }),
            overlays: [overlay],
            layers: [new ol.layer.Tile({
                                    title: "base Layer",
                                    type: 'base',
                                    visible: true,
                                    source: new ol.source.TileWMS({
                                      projection: "EPSG:4326",
                                      url: 'http://localhost:8080/service?',
                                      params: {
                                        'LAYERS': "baseLayer"
                                      }
                                    })
                                  })
            ]
        });
```

Some image from my problem this map for Iraq

![index1](https://cloud.githubusercontent.com/assets/16572668/12138265/4cd3aaa2-b460-11e5-9970-f92d41b9bdd8.png)
![index2](https://cloud.githubusercontent.com/assets/16572668/12138266/4cd587aa-b460-11e5-9d2a-5868ee2a214b.png)
![index3](https://cloud.githubusercontent.com/assets/16572668/12138267/4cd96992-b460-11e5-9fa4-a935618ed932.png)

**Comment by ahocevar** [comment]
This looks like a resolution problem, maybe related to #4627.

**Comment by fredj** [comment]
@najeebabualshar Can you please test with the latest release (v3.13.0)?

**Comment by najeebabualshar** [comment]
@ahocevar Thank you for your support :)
I want to help me more....  If you have any example how to do this change give me Plz :) 
Thank you so much :)

**Comment by najeebabualshar** [comment]
@fredj Thank you for your support :)
I updated the release yesterday but  I still  get same problem  .... 
Do you have another solutions ??
Thank you so much :)
