### ISSUE TITLE
Interaction.Select layers option doesn't work

### ISSUE THREAD

**Issue by syerad** [openlayers/openlayers#4631]
If I create a new new ol.interaction.Select like this:

``` javascript
 self.selectHandler = new ol.interaction.Select({
                    layers: [testLayer],
                    style: selectedFeaturesStyle
});
```

The interaction doesn't recognize the layers option and select features from
all layers underneath the click position instead of selecting features only from the testLayer.

**Comment by ahocevar** [comment]
Can you provide a bit more context? What version of OpenLayers are you using? What is `testLayer` in your snippet? I just tried this with the select-features example and a second layer, and it worked fine.

**Comment by syerad** [comment]
OL-Version is 3.9.
The ```testLayer``` is an ```ol.layer.Vector```.
Don't know why it isn't working.
To solve this problem, I'm using the filter option.

**Comment by ahocevar** [comment]
Have you tried to upgrade to the latest version?

**Comment by bartvde** [comment]
Any update on this @syerad ?

**Comment by syerad** [comment]
Didn't try it out with the newest version. I will update this issue if I've tested it!
