### ISSUE TITLE
add backgroundColor to ol.Feature with the ol.style.Text

### ISSUE THREAD

**Issue by qly612525** [openlayers/openlayers#4636]
Hi all,

I want to use ol.Feature to make a "Marker" like the example, but the marker should adhere the title which has the background Color and stroke Line.

I use the ol.style.Text to fixed the title, and the ol.style.Icon to the marker icon.

how do I to deal with the text background color

**Comment by szel** [comment]
+1 and possible duplicate of #4577.

**Comment by ahocevar** [comment]
Closing as duplicate of #4577.
