### ISSUE TITLE
FullScreen Label

### ISSUE THREAD

**Issue by fatalcaron** [openlayers/openlayers#4648]
An issue on mobile for the FullScreen label. The unicode doesn't work for me. I test on Galaxy S6 and Nexus 5p

**Comment by ahocevar** [comment]
The devices should support it. Make sure that your server's encoding is UTF-8.

**Comment by AlexCaron88** [comment]
When I access the official link Openlayers the same problem occurs (Only on mobile): http://openlayers.org/en/v3.12.1/examples/full-screen.html

**Comment by marcjansen** [comment]
![screenshot_2016-01-11-22-33-01](https://cloud.githubusercontent.com/assets/227934/12247244/6446a552-b8b3-11e5-84ef-463fc2a7e3ba.png)

Confirmed on my galaxy s6

**Comment by ahocevar** [comment]
Hm, not good. Any suggestions for a different symbol?

**Comment by marcjansen** [comment]
An inline css background image?

**Comment by fredj** [comment]
Same issue with chrome on a Nexus 5X

**Comment by bartvde** [comment]
Was there no issue with: http://openlayers.org/en/v3.11.0/examples/full-screen.html ?

**Comment by fredj** [comment]
No issue with v3.11.0

**Comment by marcjansen** [comment]
![screenshot_2016-01-12-09-55-47](https://cloud.githubusercontent.com/assets/227934/12258977/d15f0350-b912-11e5-8829-b47facee8d66.png)

Not an issue, but not exactly pretty either.

**Comment by richnic** [comment]
Same issue with Chrome on Galaxy S7.
Some suggestions for an alternative symbol that can be displayed (and looks good) on Galaxy S7:

- ol.control.FullScreen({ label: "\u2039\u200a\u203a" })
- ol.control.FullScreen({ label: "\u279a" })

![labels](https://user-images.githubusercontent.com/38283296/38632936-b3b87fd0-3dad-11e8-9627-dfe0f6adb5f3.png)

Can anyone check the compatibility with other mobile devices?

**Comment by m2rt** [comment]
Same on android 7.1.1 E5823
