### ISSUE TITLE
Vector source projection

### ISSUE THREAD

**Issue by jgalrito-i9** [openlayers/openlayers#4686]
Would be useful to specify Vector source projection. Otherwise features are not reprojected if I change the view projection.

**Comment by tschaub** [comment]
@jgalrito-i9 ideally, your vector data carries its own coordinate reference system information.  For example, GeoJSON is assumed to be in geographic/wgs-84.  Same goes for KML.  GML includes CRS info.  When you use a self-describing vector source with a view that is in a different projection, the library will transform vector coordinates for you.

You can see this in action with the [vector layer example](http://openlayers.org/en/master/examples/vector-layer.html).  In this case, the vector data is geographic/wgs-84 and the view is Web Mercator, and the library does the transform for you.

If you are working with vector data that doesn't carry its own CRS info (or have a well defined default), you should be able to use the `dataProjection` option for your format/parser.

If you can provide more detail on the format of your data (with links to an example), we can provide more help.

**Comment by jgalrito-i9** [comment]
My source is a simple array of objects with lat and lon properties (among others). How can I define a custom format?

**Comment by jgalrito-i9** [comment]
Another issue is that I need to specify the loader function to use angular's $http service when requesting the features. Is it possible to do this **and** use a custom format/parser?
