### ISSUE TITLE
SVG tiles not rendered in IE11

### ISSUE THREAD

**Issue by aristid** [openlayers/openlayers#4701]
ol.layer.Tile() can display SVG tiles in Firefox and Chrome (see svg.html). However, in IE11 no tiles are shown and no errors are reported. After patching the OpenLayers source (see svg-fix.html) IE is able to render SVG tiles just fine.

[svg-tiles.zip](https://github.com/openlayers/ol3/files/98871/svg-tiles.zip)

I first thought it might be a security issue with tainted canvas etc., but it's not. In ol.ImageTile.prototype.handleImageLoad_() (lines 128-136 of src/ol/imagetile.js) naturalWidth and naturalHeight properties are used to determine whether the tile is loaded. These properties do not work for SVG images in IE. 

I'm not sure why OpenLayers checks for naturalWidth in ol.ImageTile.prototype.handleImageLoad_() but not in ol.Image.prototype.handleImageLoad_() or ol.style.IconImage_.prototype.handleImageLoad_().

If the check is needed, maybe it can be done in this manner:
   if (goog.userAgent.IE && this.image_.complete ||
      this.image_.naturalWidth && this.image_.naturalHeight) {
    this.state = ol.TileState.LOADED;
  } else {
    this.state = ol.TileState.EMPTY;
  }

At https://stereochro.me/ideas/detecting-broken-images-js it's claimed that "During the onload event, IE correctly identifies any images that weren't downloaded as not complete.". I haven't verified this.

**Comment by ahocevar** [comment]
I'd say if this is not present in `ol.Image`, then it should not be necessary in `ol.ImageTile` either. Would you be willing to create a pull request to fix this?

**Comment by aristid** [comment]
Well, on closer examination there exists a TileState.EMPTY which is checked against all over the code, but there is no ImageState.EMPTY. Being an outsider to OpenLayers I'm a bit afraid to break something by simply removing the naturalWidth check.

**Comment by fredj** [comment]
See https://github.com/openlayers/ol3/pull/663

**Comment by fredj** [comment]
See https://connect.microsoft.com/IE/feedbackdetail/view/925655/svg-image-has-0x0-size-in-ie11
