### ISSUE TITLE
Display issue on GeoJSON file

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#4715]
This file does not display correctly in ol3, but does in QGIS: https://raw.githubusercontent.com/datasets/lme-large-marine-ecosystems/master/offshore/json/lme66-offshore.geojson

![screen shot 2016-01-25 at 16 58 00](https://cloud.githubusercontent.com/assets/319678/12556178/e5aaf144-c384-11e5-813c-cd141c7c038d.png)

![screen shot 2016-01-25 at 16 58 48](https://cloud.githubusercontent.com/assets/319678/12556181/ebf8024e-c384-11e5-938f-2c304400c7e6.png)

**Comment by bartvde** [comment]
Another dataset that fails: https://raw.githubusercontent.com/datasets/geo-boundaries-world-110m/master/countries.geojson

but works fine in QGIS:

![screen shot 2016-01-25 at 17 03 25](https://cloud.githubusercontent.com/assets/319678/12556327/9ad5168a-c385-11e5-8af9-2dc47ee7531b.png)

**Comment by ahocevar** [comment]
I bet in QGIS, you're looking at those in EPSG:4326 as view projection. Coordinates near the poles cannot be transformed to EPSG:3857, which is the view projection in OpenLayers. You'd need to use an ol.View with `projection` set to EPSG:4326.

**Comment by bartvde** [comment]
Good point @ahocevar

**Comment by bartvde** [comment]
Would there be a way for us to fail more gracefully (assert) or not worth the trouble?

**Comment by ahocevar** [comment]
It would be possible, but it would slow down coordinate transforms in debug mode.

**Comment by bartvde** [comment]
Okay, I'll close this one. Thanks for clearly stating the issue here ;-)

**Comment by fredj** [comment]
The geojson is correctly displayed in the vector-layer example

**Comment by ahocevar** [comment]
Ah, so only the auto-zooming to the data extent is the issue.

**Comment by bartvde** [comment]
Oh really? And that also uses EPSG:3857 right @fredj?
I was using the drag and drop example.

**Comment by ahocevar** [comment]
@bartvde so that check would be easy - we could assert that we don't `ol.View#fit` to extents with `NaN` coordinates.

**Comment by bartvde** [comment]
It's not NaN but Infinity:

```
0: -20037508.342789244
1: -Infinity
2: 20037508.34278926
3: 18440002.895114224
```

**Comment by ahocevar** [comment]
So the check would have to be for Infinity, -Infinity and NaN. All these values can occur with coordinate transforms outside the world bounds.

**Comment by bartvde** [comment]
Would we do the check just for the fitting of an extent?

**Comment by ahocevar** [comment]
Looking at the source code of `ol.View#fit`, I think it would be best to do the NaN/Infinity/-Infinity check on the coordinates that are passed to `setCenter`, and another sanity check on the value passed to `setResolution`. Both in the respective methods. Better than in `ol.View#fit`.

**Comment by bartvde** [comment]
Good suggestion

**Comment by fredj** [comment]
In the [second dataset](https://raw.githubusercontent.com/datasets/geo-boundaries-world-110m/master/countries.geojson), some coordinates are outside the world boundaries (for example 180.000000000000142, -90.095554572290979, etc ...)
