### ISSUE TITLE
Bbox loadingstrategy with ratio

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#4719]
I created a function to create a bbox loadingstrategy with a ratio, similar to the bboxRatio of openlayers2.

The commit in my forked repository is:
https://github.com/simonseyock/ol3/commit/023043d95f0ca669fbbf65d301093a82a88df3ee

I still have some questions before i would create a pull request:
1. do i need to goog.require('ol.extent') because i want to use the ol.extent.scaleFromCenter function which is not public?
2. Should i rather add an assert or throw an error if ratio is smaller than 1? - Or should i leave it like that?

**Comment by simonseyock** [comment]
I created an jsfiddle to play around with this functionality:

https://jsfiddle.net/simon_seyock/qmws0nxw/4/

it just outputs 'load' if another extent is requested.

**Comment by avilaton** [comment]
Fiddling with the fiddle I noted that also `ol.extent.clone` is not public.
