### ISSUE TITLE
No more WMTS Tiles are loaded after some zooming and panning

### ISSUE THREAD

**Issue by bschaepper** [openlayers/openlayers#4739]
At some point no more Requests are made to fetch WMTS images, after some zooming and panning. We also add and remove/destroy layers extensively, so that might be an issue. 
This behavior started to appear with version 3.12, some changes have been made in this area as far as I know. In 3.13 there was a fix for a similar issue (#4594), involving raster re-projection and TileCache. Maybe this is a similar problem?

**Comment by ahocevar** [comment]
Can you share a minimal example that exposes the issue?

**Comment by igrcic** [comment]
Hi Andrea,

We didn't have time to further investigate the issue, so we cannot provide exact steps to reproduce it. We are just certain that it does happens regularly with v3.13

For the time being we have reverted to 3.11.2, where the issue doesn't occur.

**Comment by ahocevar** [comment]
Maybe related to #4961?

**Comment by bschaepper** [comment]
Was probably fixed with #4961, so I'll close this issue.
