### ISSUE TITLE
Vector layer opacity is aplied to features instead of layer as a whole

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/openlayers#4758]
When setting opacity to the vector layer, I would expect uniform opacity across all the layer:

``` javascript
var vectorLayer = new ol.layer.Vector({
    source: vectorSource,
    style: styleFunction,
    opacity: 0.5
});
```

Currently, if multiple features are overlapping, opacity of their union is aggregated.

**Comment by ahocevar** [comment]
Untested, but what if you use
```js
var vectorLayer = new ol.layer.Image({
  source: new ol.source.ImageVector({
    source: vectorSource,
    style: styleFunction,
  }),
  opacity: 0.5
});
```
instead? Alternatively, you can set a different blend mode in a layer prerender function, similar to what is shown in the [Blend Modes example](http://openlayers.org/en/v3.13.0/examples/blend-modes.html).

**Comment by jan-tosovsky-cz** [comment]
ol.layer.Image works fine, but doesn't trigger render event on map move. I've tried also another suggested approach and it works as well.
```javascript
vectorLayer.on('precompose', setLayerAlpha);

function setLayerAlpha(evt) {
  evt.context.globalAlpha = opacity;
};
```
Thanks a lot!

**Comment by jan-tosovsky-cz** [comment]
To isolate effect just for rendering the layer data it is a must to wrap it by save/restore methods
```javascript
vectorLayer.on('precompose', function setLayerAlpha(evt) {
   evt.context.save();
   evt.context.globalAlpha = opacity;
};

vectorLayer.on('postcompose', function doSomething(evt) {
   evt.context.restore();
   // do something
};
```

**Comment by icemagno** [comment]
What if I have a lot of vector layers and need to change opacity for each one dynamically using a slider bar?

**Comment by ahocevar** [comment]
This issue should be fixed now anyway. See #6981.
