### ISSUE TITLE
Some WMTS services from ArcGIS Online are retired soon.

### ISSUE THREAD

**Issue by patrickarlt** [openlayers/openlayers#4797]
I just got an email from the ArcGIS Online content team that they are retiring some services used in Open Layers examples:
- http://openlayers.org/en/v3.12.1/examples/wmts.html
- http://openlayers.org/en/v3.2.0/examples/wmts.html
- http://openlayers.org/en/v3.5.0/examples/wmts.html

The official blog post for the retirement is https://blogs.esri.com/esri/arcgis/2016/01/13/legacy-demographic-maps-retire-march2016/.

Thought you guys might appreciate the heads up.

**Comment by bartvde** [comment]
thanks for the heads-up @patrickarlt

**Comment by bartvde** [comment]
@patrickarlt so this now needs an account to access, how can we get one for openlayers?

Important Note: This item requires an ArcGIS Online organizational subscription or an ArcGIS Developer account and consumes credits. To access this item, you'll need to do one of the following:
Sign in with an account that is a member of an organizational subscription
Sign in with a developer account
Register an application and use your application's credentials

**Comment by patrickarlt** [comment]
Since you are just using these services as WMTS examples I would probably recommend just finding different services. The developer accounts are only for individuals and accessing the demographic services now requires credits which will cost you money.

**Comment by bartvde** [comment]
makes sense, thanks for explaining
