### ISSUE TITLE
2.5D / 3D - Is there a plan to support those?

### ISSUE THREAD

**Issue by speechlogger** [openlayers/openlayers#4802]
Needed features would be:
1) Tilt map
2) Buildings heights
3) Heights to polygons
4) Load 3D objects from .OBJ (or other 3D format) files

Do you have a recommended solution at this point?

Thanks

**Comment by gberaudo** [comment]
@elemoine did some experiments with tilting in https://github.com/elemoine/ol3/tree/tilt.
