### ISSUE TITLE
KML placemark icons without hotspots are drawn in the wrong place

### ISSUE THREAD

**Issue by tamarmot** [openlayers/openlayers#4829]
I have created test files in Google Earth with a placemark, one with a pushpin icon that has a hotspot, one with a diamond icon that does not.  When they load in google earth, the diamond icon one is drawn so the center is where the tip of the pushpin is.

In OpenLayers, it is drawn offset vertically.

When I look at kmlformat.js, the anchor units for all icons from google are set to [0.5, 0] but I'm pretty sure that google has all those weird ones with hotspots, so the anchor units should be [0.5, 0.5] to center the anchor.  I have tried making that change but the icon is still drawn in the wrong place; I think the issue is with the offset.

[kml_and_image_files.zip](https://github.com/openlayers/ol3/files/128933/kml_and_image_files.zip)

Open layers screenshot:
![openlayers_screenshot](https://cloud.githubusercontent.com/assets/5769968/13024757/14f57cac-d1af-11e5-853a-359ff4fb671d.png)

Google earth screenshot:
![google_earth_screenshot](https://cloud.githubusercontent.com/assets/5769968/13024758/14f64754-d1af-11e5-90de-e1a8da312f59.png)

**Comment by lowzonenose** [comment]
I confirm that there's a problem with the positioning of the marker in OpenLayers 3.
If no tag '_hotspot_' is present in the KML, the marker is centered by default ...

On the other side, if we put in place this tag (_hotspot_), vertical positioning is drawn to the wrong place...
[jsfiddle - read kml] (http://jsfiddle.net/lowzonenose/1dnrn1hu/embedded/result,js,html,css/)
[jsfiddle - write kml] (http://jsfiddle.net/lowzonenose/yh4stufb/embedded/result,js,html,css/)

**Comment by lowzonenose** [comment]
A small change in the following source code allows to properly manage the creation of the tag 'hotspot'.
See the method **ol.format.KML.writeIconStyle_**:

```
(...)
if (size) {
    iconProperties['w'] = size[0];
    iconProperties['h'] = size[1];
    var anchor = style.getAnchor(); // top-left
    var origin = style.getOrigin(); // top-left
    if (origin && iconImageSize && origin[0] !== 0 && origin[1] !== size[1]) {
      iconProperties['x'] = origin[0];
      iconProperties['y'] = iconImageSize[1] - (origin[1] + size[1]);
    }
    if (anchor && anchor[0] !== 0 && anchor[1] !== 0 ) { // the fix is here !  
      var hotSpot = {
        x: anchor[0],
        xunits: ol.style.IconAnchorUnits.PIXELS,
        y: size[1] - anchor[1],
        yunits: ol.style.IconAnchorUnits.PIXELS
      };
      properties['hotSpot'] = hotSpot;
    }
  }
(...)
```

**Comment by ahocevar** [comment]
@lowzonenose Would you be able to provide a pull request with a fix?
