### ISSUE TITLE
Unfilled polygon hit detection

### ISSUE THREAD

**Issue by jsalankey** [openlayers/openlayers#4846]
The canvas replay renderer is currently inserting a default fill for the hit detection instructions for any polygon, regardless of whether it is filled or not:

https://github.com/openlayers/ol3/blob/master/src/ol/render/canvas/canvasreplay.js#L1334

My team would prefer to only hit detect polygons that are actually filled when hovering over the interior and not hit detect unfilled ones. The fillStyle from the actual polygon is right there on the `state` in that function, so why not just use that? There isn't a good way to work around this short of overriding the whole function (that I can see). Would this give you any heartburn to change? Or to be made configurable?

**Comment by fredj** [comment]
#7750
