### ISSUE TITLE
Unclear type of olx.style.IconOptions#img property

### ISSUE THREAD

**Issue by jumpinjackie** [openlayers/openlayers#4856]
In my continued adventure in automatically generating a TypeScript definition for OpenLayers, I found a possible ambiguity in the `img` property of `olx.style.IconOptions`

The type of this property is currently `Image|HTMLCanvasElement|undefined`

https://github.com/openlayers/ol3/blob/master/externs/olx.js#L6184

Does Image refer to `ol.Image` or is it a `<img>` tag element?

If former, then `Image` should be qualified and the correct type should be `ol.Image|HTMLCanvasElement|undefined`

If latter, then the correct type should be `HTMLImageElement|HTMLCanvasElement|undefined`

**Comment by ahocevar** [comment]
The latter. The Closure Compiler seems to make a difference between an image created with `new Image()` `{Image}` and one created with `document.createElement('IMG')` (`{HTMLImageElement}`). But if your suggested change works, then go for it. Thanks.

**Comment by fredj** [comment]
closure-compiler is not used anymore, closing.
