### ISSUE TITLE
View rotation center is incorrect with WebGl renderer

### ISSUE THREAD

**Issue by GerardPerche** [openlayers/openlayers#4858]
After switching to the webgl map renderer (by adding renderer : 'webgl', in my map construction), I noticed that the rotation center does not match with the view center.
I have also checked this is issue does not occur when renderer is set to either DOM or Canvas.
OS: iOS 8.4 
Browser:  a UIWebView, in a native app.

**Comment by fredj** [comment]
https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#drop-of-support-for-the-experimental-webgl-renderer
