### ISSUE TITLE
Documentation for ol.Overlay incorrect

### ISSUE THREAD

**Issue by jvanulde** [openlayers/openlayers#4872]
In the stopEvent option documentation `ol-overlaycontainer` should be `.ol-overlay-container`.

**Comment by tschaub** [comment]
Actually, both [`ol-overlaycontainer`](https://github.com/openlayers/ol3/blob/6e7b130a45aa81ea8bf0d0888c2c4103310d26e9/src/ol/map.js#L278) and [`ol-overlay-container`](https://github.com/openlayers/ol3/blob/6e7b130a45aa81ea8bf0d0888c2c4103310d26e9/src/ol/overlay.js#L99) are class names.  Yes confusing.  Which documentation are you referring to?

**Comment by jvanulden** [comment]
[http://openlayers.org/en/v3.13.1/apidoc/ol.Overlay.html](url)
