### ISSUE TITLE
How to disable the zoom snap during the "Pinch Zoom"?

### ISSUE THREAD

**Issue by krzbor** [openlayers/openlayers#4873]
How to disable the zoom snap during the "Pinch Zoom"?

**Comment by Shane98c** [comment]
Bumping this, it's one of the main complaints from our users.  We'd love to see a fix!

**Comment by ahocevar** [comment]
There is currently no way to disable it, but you can configure your view with `zoomFactor: 1.1` to get very small resolution steps.
