### ISSUE TITLE
Select interaction only propagates if the condition is 'pointermove'

### ISSUE THREAD

**Issue by Distem** [openlayers/openlayers#4882]
Was testing issue #4854 and noticed that interaction.Select event only propagates for pointerMove condition. Which causes a problem when you have separate click interactions attached to different layers.

**Comment by Distem** [comment]
Returning `!mapBrowserEvent.originalEvent.defaultPrevented;` instead of `ol.events.condition.pointerMove(mapBrowserEvent);` in `interaction.Select.handleEvent` just need to make sure to call `preventDefaults()` when you need to. Don't know if this is the best approach though.

**Comment by ahocevar** [comment]
Can you create a test case or an example that shows your issue? I usually add pointermove interactions to the map before click interactions, and never ran into issues with that.

**Comment by Distem** [comment]
http://jsfiddle.net/6QaHA/255/
Hovering lines works, but click is never fired - only points layer click is fired.

**Comment by ahocevar** [comment]
I see now what you mean. You can only have one select interaction per condition. I updated your fiddle to a state where I think it does what you want: http://jsfiddle.net/6QaHA/259/

**Comment by Distem** [comment]
Ok, thanks for the info, I was assuming that it should be possible to add multiple interactions due to the layers options, as in our application we add/remove a lot of layers with different styles/click functionality it was making more sense for me to add separate interactions per layer type.

**Comment by ahocevar** [comment]
@Distem I agree that the current behaviour is somewhat unexpected. Even returning `true` from `interaction.Select.handleEvent` could make sense I guess, but I don't know why it was decided to `return false` in the first place. Maybe @tonio can help here?

**Comment by Distem** [comment]
preventing defaults seems to work for me for now I have to keep track of the order of the interactions to make sure that they propagate correctly. 
Would be good to support z-index for interactions and unmanaged layers, as at the moment have to call `setMap(null)` - `setMap(map)`, to keep the order of these layers. Using `Collection.insertAt` is not an option really as sometimes you want to mix the order of unmanaged layers and interactions.

**Comment by VirtualGit** [comment]
I'm facing the same issue and I'd like to up the thread. Is the solution proposed by @Distem acceptable ?

> Returning `!mapBrowserEvent.originalEvent.defaultPrevented;` instead of `ol.events.condition.pointerMove(mapBrowserEvent);` in `interaction.Select.handleEvent`

If yes, I could try to make a PR (never done that !)

I'm quite new to OL (and not a JS expert), but it appears to me as a good solution.
