### ISSUE TITLE
Use record instead of typedef in olx.js

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#4920]
in `externs/olx.js` we have:

``` javascript
/**
 * @typedef {{
 *   a: number,
 *   b: string
 * }}
 */
olx.foo.Bar;

/**
 * @type {number}
 */
olx.foo.Bar.prototype.a;

/**
 * @type {string}
 */
olx.foo.Bar.prototype.b;
```

The `@typedef` is used by the closure-compiler to check the types and the `olx.foo.Bar.prototype.*` by jsdoc.

The (new ?) `@record` annotation can be used instead:

``` javascript
/**
 * @record
 */
olx.foo.Bar;

/**
 * @type {number}
 */
olx.foo.Bar.prototype.a;

/**
 * @type {string}
 */
olx.foo.Bar.prototype.b;
```

Documentation: https://github.com/google/closure-compiler/wiki/Structural-Interfaces-in-Closure-Compiler

**Comment by gberaudo** [comment]
Would be a great simplification of the externs and be consistent with how we handle classes.

**Comment by ahocevar** [comment]
@jumpinjackie, would this help for your #4827 effort?

**Comment by jumpinjackie** [comment]
@ahocevar Not really :) My plugin doesn't handle `@record` currently, but don't let that stop you.
