### ISSUE TITLE
Option to disable resolution constraints

### ISSUE THREAD

**Issue by pkovac** [openlayers/openlayers#4922]
In some usecases, it may be ideal to disable resolution contraints entirely. In ol.View there is no clear way to disable the constraint behavior (making constrainResolution always return the same resolution it was given as input when no delta or direction are specified.) While I can set resolution through setResolution, the stock ol.control.ZoomSlider and ol.interaction.DragZoom call constrainResolution, and there is no way to disable this behavior. Being able to adjust the resolution constraints for a view at runtime would also be helpful in this case, though recreating the view is an acceptable workaround. It might also be useful to expose more options on these controls/interactions regarding animation and use of contraints.

As a workaround, I've extended the base View class in my project and overridden constrainResolution(). This might be adequate for some cases, but it would be ideal to solve this in another way.

**Comment by ahocevar** [comment]
I agree that some way to disable resolution constraints would be desirable.

**Comment by fredj** [comment]
fixed with #9137
