### ISSUE TITLE
Overlay.stopEvent not working as intended combined with the pointermove event?

### ISSUE THREAD

**Issue by okon3** [openlayers/openlayers#4953]
What is the "stopEvent" in the Overlay component supposed to do in case of pointermove event on the map?

The documentation states this:

> Whether event propagation to the map viewport should be stopped. Default is true. If true the overlay is placed in the same container as that of the controls (CSS class name ol-overlaycontainer-stopevent); if false it is placed in the container with CSS class name ol-overlaycontainer.

But in this example if I open the popup I can't click on the link cause the pointermove gets fired over and over even if I'm on the poup

https://jsfiddle.net/sma7qkoz/1/

Thanks,
Luca

**Comment by ahocevar** [comment]
`stopEvent` works as expected on the element specified for `ol.Overlay`. But the popover component you use for the popup creates markup that his not a child of the element, so that won't work. I'd suggest you use a popup like in http://openlayers.org/en/v3.14.1/examples/popup.html. With that, things will work as expected.

**Comment by okon3** [comment]
I think I updated the fiddle accordigly but still as soon as I hover the red marker wich is under the popup form the blue marker the popup changes to the red one..

https://jsfiddle.net/sma7qkoz/4/

**Comment by ahocevar** [comment]
You're right, the documentation is misleading. The `ol-overlaycontainer-stopevent` container does not stop all events: https://github.com/openlayers/ol3/blob/v3.14.1/src/ol/map.js#L287-L295. Maybe you want to submit a pull request to improve the documentation?

**Comment by ahocevar** [comment]
A solution for your problem is simple though:
```js
 container.onmousemove = function(e) {
   e.stopPropagation();
 };
```
See updated fiddle: https://jsfiddle.net/sma7qkoz/5/.

**Comment by simonseyock** [comment]
I think this behaviour of overlays is related to the behaviour of controls: https://github.com/openlayers/ol3/issues/4196
This can be solved with stopping the propagation, though, but it needs to be disabled again if a draw interaction is active. 

Another solution is to modify the condition of the interaction. Like in this example:
https://jsfiddle.net/simon_seyock/3yzfhzrj/4/

**Comment by simonseyock** [comment]
I think this behaviour of overlays is related to the behaviour of controls: https://github.com/openlayers/ol3/issues/4196
This can be solved with stopping the propagation, though, but it needs to be disabled again if a draw interaction is active. 

Another solution is to modify the condition of the interaction. Like in this example:
https://jsfiddle.net/simon_seyock/3yzfhzrj/5/

**Comment by cs09g** [comment]
I checked the link @ahocevar linked, it seems it doesn't work at all. 
hover the blue one and move mousepointer upward slowly. then when it is on the position of red one that it still looks under the blue one's div, red one's overlay appears.

**Comment by Vanit** [comment]
@ahocevar's solution worked for me after I changed it to 'pointermove'. 

```
$('.ol-overlay-container').on('pointermove', function(e){
    e.stopPropagation();
});
```

**Comment by cs09g** [comment]
@Vanit Working solution! but your approaching that uses "ol-overlaycontainer-stopevent" class looks like handling out side of API. it should be handling through something like object inside of API.

**Comment by Vanit** [comment]
@cs09g Yep, ideally this should be fixed in the API, but this was just a workaround for an immediate project that can't wait for the fix.

**Comment by Bear4** [comment]
@Vanit Thanks!
