### ISSUE TITLE
Export ol.sphere constants

### ISSUE THREAD

**Issue by sebasbaumh** [openlayers/openlayers#4954]
Beside `ol.Sphere` to create a new sphere with a custom radius there are already two constants defined:  `ol.sphere.WGS84` and `ol.sphere.NORMAL`.
I would like to export both of them in the public API.

This will enable users to for example calculate the haversine distance on a WGS84 sphere without having to define them on their own. And it is similar to providing the user with standard projections like EPSG:4326 in `ol.proj`.

I will create a pull request to solve this.

**Comment by ahocevar** [comment]
I don't find the ticket right now, but it was decided in the past to not make these exportable. In addition, there have been discussions whether the radius used for ol.sphere.NORMAL makes sense.

Mabye others think different now, but I still think `ol.sphere.WGS84` and `ol.sphere.NORMAL` should **not** be made exportable.

**Comment by bartvde** [comment]
Right I also remember this @ahocevar with the measurement example work IIRC

**Comment by ahocevar** [comment]
See #2359:

> As ol.Sphere.WGS84 (and ol.Sphere.NORMAL) simply provides a radius to ol.Sphere, I'm wondering if it wouldn't be better to have these radii stored in an enum or something rather than as separate symbols.

That point is still valid, so to me it feels wrong to make something exportable that is likely to go away soon.

**Comment by sebasbaumh** [comment]
There is even an example at least for the WGS84 sphere at http://openlayers.org/en/v3.14.1/apidoc/ol.Sphere.html stating:

    var wgs84Sphere= new ol.Sphere(6378137);

So maybe just leaving out `ol.sphere.NORMAL` makes sense?

@bartvde: I am currently working on the measurement part and try to re-use things already created in OpenLayers. And if there is a constant sphere that is used in OpenLayers, I would like to open it up to the library users.

@ahocevar: Would it be feasible to add a constant to `ol.sphere` for that and use it for `ol.sphere.WGS84` as well? Whereby I still would think that the user should not need to create another instance of a constant object ;-)

**Comment by ahocevar** [comment]
In my opinion, `ol.Sphere` should not be an object at all. Its only member property is `radius`. Instead, we should have an `ol.sphere` namespace that provides static functions to be called with a radius, and constants for common radii.

Other opinions?

**Comment by sebasbaumh** [comment]
@ahocevar Yes, that sounds even better to me. As long as there is nothing else beside the radius and sphere does just provide static functionality, we could create `ol.sphere` with constants for the radii and static functions.

In my opinion it also kind of stands out compared to the rest of the API: `ol.Sphere` is in `ol` and not in `ol.sphere` - but in contrast `ol.sphere.WGS84` is in `ol.sphere`. This is much different to example `ol.proj.Projection` and `ol.proj` static functions.

**Comment by fredj** [comment]
see #7643
