### ISSUE TITLE
Expose TileCache

### ISSUE THREAD

**Issue by Morgul** [openlayers/openlayers#5032]
I've run into an interesting scenario where I would like to clear the current `tileCache` in a given source. Currently, `tileCache` is a private variable, so I can't access it from production builds (despite it not being named with a `_`).

For now, I've worked around this with the following:

``` javascript
layer.getSource().setTileLoadFunction(layer.getSource().getTileLoadFunction());
```

Is there any reason not to publicly expose the cache via a `getTileCache()` function? I understand it's currently not documented, but it would be very useful to be able to work with (and I've been playing with it in debug builds; the API seems pretty solid). I'd be fine with putting it under the `experimental` flag.

Additionally, exposing the tile cache would allow me to write my own code to solve #3814.

If that's not something that you guys feel should be exposed, could we please get some ability to clear the cache?

**Comment by ahocevar** [comment]
One thing I think would make sense is a `clear()` method on all `ol.source.Source` subclasses. We have that on `ol.source.Vector` already.

In addition, I've started to question the usefulness of a tile cache for sources that send sensible cache headers - there is a browser cache, right? But #4961 makes it impossible to set a tile cache size of 0.

**Comment by Morgul** [comment]
@ahocevar Removing the tile cache would hurt my use case; I'm subclassing `source.XYZ` and implementing a websocket based source; it has the advantage of really good compression and being lightning fast; downside of circumventing the browser's cache.

Still while as a bare minimum a `clear()` would be really useful, I still just want access to the cache directly. Heck, I'd love to be able to implement my own tile cache; so I'd be for full get/set functionality. Which, to your point, would allow for a dummy tile cache that just relies on the browser's cache.

**Comment by ahocevar** [comment]
I wouldn't want to remove the tile cache, I'd just like to make its use optional.

**Comment by Morgul** [comment]
Ah, ok, that could work. I still like supporting alternative tile cache implementations, but that could dovetail nicely with changes to make it optional, I think.

**Comment by electricowl** [comment]
I'm using OL4 right now and have an ImageWMS source in an Image layer. I am able modify the source successfully with updateParams().  So far I have been unable to get the layer to update on the map although I can see that the request is sent correctly to Geoserver. 

If I don't change anything the map zooms and sends new requests for the layer which get shown correctly. If I use updateParams() the layer does not update on the map as I would expect and when zooming the layer requests are sent to the server but do not appear on the map at all, only the original tile is displayed at any zoom level.

It seems to me that this issue is linked to caching, but I don't know how to verify this.

What can I do other than delete the layer and add it again?

**Comment by Morgul** [comment]
@electricowl Only just saw your message thanks to the stale bot. If you're still struggling with this, here's the solution that we use in production (and have since I filed this issue...)

```javascript
class MyLayerWraper
{

  // ...a class that is backed by an `olLayer` / `olSource`, but has some custom logic

 redraw()
    {
        const source = this.source;
        if(source)
        {
            if(source.getTileLoadFunction)
            {
                // This forces a tileCache.clear(), something we can't do directly in production builds.
                // See: https://github.com/openlayers/ol3/issues/5032
                source.setTileLoadFunction(source.getTileLoadFunction());
            } // end if

            // If the above doesn't work, this should.
            source.changed();
        } // end if
    } // end redraw
}
```

As you can see, we've found a way to work around the tilecache not exposing a clear function. We have to do this frequently in our application, because the underlying data has changed without the map moving.
