### ISSUE TITLE
ol.source.WMTS.optionsFromCapabilities: Access to undefined property Constraint throws error

### ISSUE THREAD

**Issue by AnWeber** [openlayers/openlayers#5038]
The property OperationsMetadata.GetTile.DCP.HTTP.Get.Constraint is required in a WMTS File but is only optional according to OWS XSD. 

WMTS File: http://laermkartierung1.eisenbahn-bundesamt.de/mb3/WMTSCapabilities.xml
GetCapabilities XSD: http://schemas.opengis.net/ows/1.1.0/owsGetCapabilities.xsd

Error in File: src/ol/source/wmtssource.js (Line: 460)

Error Stacktrace:
TypeError: Cannot read property 'length' of undefined
    at Object.ol.array.find (ol-debug.js:5327)
    at Function.ol.source.WMTS.optionsFromCapabilities (ol-debug.js:107148)

**Comment by oterral** [comment]
Similar to https://github.com/openlayers/openlayers/issues/6835
