### ISSUE TITLE
Improvement : generalize anchor for ol.style.image

### ISSUE THREAD

**Issue by DavidHequet** [openlayers/openlayers#5057]
Hi,

I was trying to do a style array like this:

``` js
var style = [];
style.push(new ol.style.Style({
            image: new ol.style.Icon({
                opacity: 1,
                scale: 1,
                src: styleCache[fake_resolution][themekey][svgSize],
                anchor: [0.5, 0],
                anchorOrigin: 'bottom-left'
            })
        }))
style.push(new ol.style.Style({
            image: new ol.style.Circle({
                stroke: new ol.style.Stroke({
                    color: '#0059FF',
                    width: 3
                }),
                radius: 20,
            })
        }))
```

But there is no way to set an anchor or offset for ol.style.Circle or ol.style.RegularShape.
It could be great to set somthing to move my circle up :)

![capture](https://cloud.githubusercontent.com/assets/3728916/13819844/45c9bdce-eb9b-11e5-8bf2-3f1ff28771c2.PNG)

**Comment by kulmegil** [comment]
btw, as for ol.style.Circle - even getters for anchor and size are unavailable (actually marked as private and not exposed in release version)

**Comment by ahmadazimi** [comment]
There is no idea about this?

**Comment by ryanewtaylor** [comment]
This is something that we could use as well. We'd like to be able to render badges that indicate how many features are clustered over our custom symbol.

Example: 
![image](https://user-images.githubusercontent.com/1215819/28974914-1b310834-7906-11e7-86a1-e55b9b1fe6b6.png)

Example source: https://ant.design/components/badge/

**Comment by g-hawk** [comment]
It was e very useful function select anchor for circle and shape.
![immagine](https://user-images.githubusercontent.com/26896972/35673223-349ef0a0-0741-11e8-8479-0e5457097f88.png)
How to see from image, red point shows feature position and shape position is misleading.
Thanks.

**Comment by HarelM** [comment]
+1.
I'm using a font to generate text for icons etc so I'm able to do it using text and offsets.
Here's the relevant snippet:
```ts
new style.Style({
	text: new style.Text({
		font: "normal 6px IsraelHikingMap",
		text: this.resources.getCharacterForIcon("icon-circle"),
		offsetY: -24,
		offsetX: 10,
		fill: iconFill
	}),
})
```
`IsraelHikingMap` is a custom font generated with icomoon app site.
`icon-circle` is a circle drawn with svg, much like how fontawesome works.
```ts
public getCharacterForIcon(icon: string) {
        let character = this.iconsCache.get(icon);
        if (character) {
            return character;
        }
        let i = document.createElement("i");
        i.classList.add(`${icon}`);
        document.body.appendChild(i);
        let style = getComputedStyle(i, ":before");
        character = String.fromCharCode(style.content.toString().charCodeAt(1));
        document.body.removeChild(i);
        this.iconsCache.set(icon, character);
        return character;
    }
```
