### ISSUE TITLE
forEachFeatureAtPixel() fails to detect feature by alternate geometries (rendered from styles)

### ISSUE THREAD

**Issue by kulmegil** [openlayers/openlayers#5073]
forEachFeatureAtPixel() might fail feature detection when pixel belongs to another geometry - not defined by geometry name, but rendered specifically using styles.

In the example below camera (feature) primary geometry is point type while it's visibility cone is polygon type. It was mostly a decoration in the past but I want to make it interactive now. The red area indicates where forEachFeatureAtPixel() successfully works. It appears that extent from primary geometry (extended by some pixel value?) plays major role on feature detection area.

ol v3.12.1

![foreachfeatureatpixel fail](https://cloud.githubusercontent.com/assets/570575/13882781/374cbe8a-ed27-11e5-801f-5cb029f6c902.png)

**Comment by tsauerwein** [comment]
Can you check if this is not related to the `renderBuffer` setting, see https://github.com/openlayers/ol3/issues/5029#issuecomment-196232162?

**Comment by kulmegil** [comment]
@tsauerwein 
They are similar, because they are related to renderBuffer.

The problem here relates more to handling multiple geometries on same ol.Feature - only "primary" geometry buffer is taken into consideration on detection. If those geoms were placed on separate feature instances there would be no issue.

**Comment by tsauerwein** [comment]
> The problem here relates more to handling multiple geometries on same ol.Feature - only "primary" geometry buffer is taken into consideration on detection.

True, the hit-detection only checks features inside the feature source that intersect with a bbox of 100px (or the value you have set with `renderBuffer`) around the position. Geometries that are created inside style functions are not considered.

> ps I have workaround my case in a ugly way - because changing polygon to primary would break to many things in my code I'm copying extent value from polygon to point. ;)

You could also use a multi-geometries in your feature source that each contain the point and the polygon.
