### ISSUE TITLE
Modify interaction and Box/Square geometry

### ISSUE THREAD

**Issue by sandman7920** [openlayers/openlayers#5095]
Some versions ago in Draw interaction 'geometryFunction' was introduced, and now it's easy to draw custom geometry type
http://openlayers.org/en/v3.14.2/examples/draw-features.html

``` javascript
if (value !== 'None') {
          var geometryFunction, maxPoints;
          if (value === 'Square') {
            value = 'Circle';
            geometryFunction = ol.interaction.Draw.createRegularPolygon(4);
          } else if (value === 'Box') {
            value = 'LineString';
            maxPoints = 2;
            geometryFunction = function(coordinates, geometry) {
              if (!geometry) {
                geometry = new ol.geom.Polygon(null);
              }
              var start = coordinates[0];
              var end = coordinates[1];
              geometry.setCoordinates([
                [start, [start[0], end[1]], end, [end[0], start[1]], start]
              ]);
              return geometry;
            };
          }
          draw = new ol.interaction.Draw({
            source: source,
            type: /** @type {ol.geom.GeometryType} */ (value),
            geometryFunction: geometryFunction,
            maxPoints: maxPoints
          });
          map.addInteraction(draw);
        }
```

Is it possible to have something like that in ol.interaction.Modify, or is there another way to customize geometry.

Now i put name property to feature in draw and then in modifyinteraction.js (ugly hack and ugly code /poor javascript skills/) depends on the value of the property i make custom geometry

P.S.
Is there plan to add rectangle geometry or something like that.

P.S. 2
Sorry for my English

**Comment by ahocevar** [comment]
You can customise the geometry of the features that you get with the modify event when you listen to `modifyend`. Not sure though if this is what you are looking for.

**Comment by sandman7920** [comment]
Nope i want to have same interactions in ol.interaction.Draw and ol.interaction.Modify

**Comment by ahocevar** [comment]
What kind of API are you envisioning? Where exactly do you want to hook into, and what custom modifications do you want to apply to the geometry?

**Comment by sandman7920** [comment]
[https://dl.dropboxusercontent.com/u/67118717/ol3.mp4](url)
[https://dl.dropboxusercontent.com/u/67118717/output.gif](url)

**Comment by sandman7920** [comment]
The goal is to modify rectangular shape without insert new vertex left_min, top_right modification

**Comment by sandman7920** [comment]
My current modification are in:
ol.interaction.Modify.handleDownEvent_
```javascript
        for (var i = 0, ii = segmentDataMatches.length; i < ii; ++i) {
            var segmentDataMatch = segmentDataMatches[i];
            var segment = segmentDataMatch.segment;
            if (segmentDataMatch.feature.get('name') === 'box') {
                var c = segmentDataMatch.geometry.getCoordinates();
                if (ol.coordinate.equals(c[0][0], vertex)) this.onEdge=1; //console.log('bottom_left');
                else if (ol.coordinate.equals(c[0][1], vertex)) this.onEdge=2; //console.log('bottom_right');
                else if (ol.coordinate.equals(c[0][2], vertex)) this.onEdge=3; //console.log('top_right');
                else if (ol.coordinate.equals(c[0][3], vertex)) this.onEdge=4; //console.log('top_left');
            }
```
ol.interaction.Modify.handleDragEvent_
```javascript
            case ol.geom.GeometryType.POLYGON:
                if (!box) {
                    coordinates[depth[0]][segmentData.index + index] = vertex;
                } else {
                    if (i == 0) {
                        var c = coordinates[0];
                        var si = segmentData.index;
                        if (!this.onEdge) {
                            if (si == 0) {
                                c[0][1] = c[1][1] = c[2][1] = c[5][1] = vertex[1];
                                vertex[0] = this.downP[0];
                            }
                            if (si == 1) {
                                c[1][0] = c[2][0] = c[3][0] = vertex[0];
                                vertex[1] = this.downP[1];
                            }
                            if (si == 2) {
                                c[2][1] = c[3][1] = c[4][1] = vertex[1];
                                vertex[0] = this.downP[0];
                            }
                            if (si == 3) {
                                c[3][0] = c[4][0] = c[5][0] = c[0][0] = vertex[0];
                                vertex[1] = this.downP[1];
                            }
                        } else {
                            if (this.onEdge == 1) {
                                c[0][0] = c[3][0] = c[4][0] = vertex[0];
                                c[0][1] = c[1][1] = c[4][1] = vertex[1];
                            } else if (this.onEdge == 2) {
                                c[1][0] = c[2][0] = vertex[0];
                                c[0][1] = c[1][1] = c[4][1] = vertex[1];
                            } else if (this.onEdge == 3) {
                                c[1][0] = c[2][0] = vertex[0];
                                c[2][1] = c[3][1] = vertex[1];
                            } else if (this.onEdge == 4) {
                                c[0][0] = c[3][0] = c[4][0] = vertex[0];
                                c[2][1] = c[3][1] = vertex[1];
                            }
                        }
                    }
                }
                segment[index] = vertex;
                break;
```
ol.interaction.Modify.handleUpEvent_
```javascript
if (this.boxFeature != null) {
        this.features_.remove(this.boxFeature);
        var g = this.boxFeature.getGeometry();
        var e = g.getExtent();
        var c=[];
        c.push([e[0], e[1]]);
        c.push([e[2], e[1]]);
        c.push([e[2], e[3]]);
        c.push([e[0], e[3]]);
        c.push([e[0], e[1]]);
        g.setCoordinates([c]);
        this.features_.push(this.boxFeature);
        this.boxFeature=null;
    }
```

**Comment by ahocevar** [comment]
An API for that could look like this:
```
new ol.interaction.Modify({
  features: new ol.Collection([myFeature]),
  insertVertex: false
});
myFeature.getGeometry().on('change', function(e) {
  var coordinates = e.target.getCoordinates();
  // do something with the geometry
  e.target.setCoordinates(coordinates);
  myFeature.changed()
});
```
That would require a pull request that introduces an `insertVertex` option - when false, only existing vertices can be modified.

However, even now you can get a long way with just the geometry change listener above.

**Comment by sandman7920** [comment]
I think it will be better insertVertex property to be feature based not interaction based
```javascript
DataExtractor.modify = new ol.interaction.Modify({
    features: DataExtractor.select.getFeatures(),
    style: DataExtractor.Styles.overlayStyle,
    pixelTolerance: 15,
    deleteCondition : function(evt) {
        return ol.events.condition.platformModifierKeyOnly(evt) && ol.events.condition.click(evt)
    }
```

**Comment by ahocevar** [comment]
> I think it will be better insertVertex property to be feature based not interaction based

Not sure I understand. What would an API for that look like?

**Comment by sandman7920** [comment]
insertVertex: this.features_.count() == 1 && this.features_.at(0).get('insertVertex')

**Comment by ahocevar** [comment]
Ok, so an `insertVertexCondition`, would work like `condition`.

**Comment by sandman7920** [comment]
Great thanks.

**Comment by sandman7920** [comment]
Or maybe:
```javascript
new ol.interaction.Modify({
  features: getFeaturesCollection(),
  customModifier: function (currentPoint, featureGeometry) {
      return handled;
  }
});
```

**Comment by levu42** [comment]
Is there any chance for this to get merged soon?

**Comment by ahocevar** [comment]
It looks like we have not received a pull request for this yet.

**Comment by havlicekj** [comment]
Hi,
I am trying to make modification of rectangles work and I have run into the same issue. When I tried this piece of code from @ahocevar I found few issues with it:

```
myFeature.getGeometry().on('change', function(e) {
  var coordinates = e.target.getCoordinates();
  // do something with the coordinates
  e.target.setCoordinates(coordinates);
  myFeature.changed()
});
```
1. It causes infinite recursion, because setCoordinates calls `changed()` which causes the handler to be called again. I can work around this by adding `if (e.target.getRevision() % 2) return;` at the beginning of the handler, but that seems like a horrible hack. Am I missing something?
2. Without knowing which point was changed, it is very difficult to turn the polygon into a rectangle (using bounding box of all vertices works only when we expand the box). I don't think the change event can provide this information, because it has to be generic, so some new api may be needed - possibly something like like `geometryFunction` as the original poster suggested. It would be called with geometry being modified (and possibly extra information, like specific point being modified) and return new geometry. Do you think this a good idea?
3. Even though this code can be used to change geometry to a rectangle visually, the Modify interaction still uses the original geometry for some reason, so when I want to modify the box again, the displayed geometry does not match what can be clicked on. I have no idea how to solve this one, any suggestions?

**Comment by mikepence** [comment]
Just encountered this. It is a strange omission that `ol.interaction.Modify` does not accept a geometryFunction so that a feature that I am editing does not behave like a feature I am creating.

**Comment by Renaud009** [comment]
So, how should we implement such interaction? By using insertVertexCondition?

**Comment by rhyst** [comment]
Also just encountered this. 

I think @mikepence has a good suggestion that `Modify` should accept a `geometryFunction` just like `ol.interaction.Draw` does. Is there a technical reason for not implementing this? (I appreciate that it might be that there's not enough developer time etc.)

**Comment by ahocevar** [comment]
We'd accept a pull request that adds a `geometryFunction`.

**Comment by so4001** [comment]
私は日本で働くエンジニアです。以下のサイトの記事を書きました。この問題の参考になるかもしれません。

https://sun-san-tech.com/javascript/openlayers/285/
