### ISSUE TITLE
Incorrect docs about ol.source.Raster 

### ISSUE THREAD

**Issue by drnextgis** [openlayers/openlayers#5121]
[This](http://openlayers.org/en/v3.14.2/apidoc/ol.source.Raster.html) page says:

> A source that transforms data from any number of input sources using an array of ol.raster.Operation functions to transform input pixel values into output pixel values.

But `operation` option is not an array.

**Comment by itjope** [comment]
PR #7378 fixes this.

**Comment by fredj** [comment]
fixed with #7378
