### ISSUE TITLE
Memory leak with zooming in and out of a layer containing clustered features.

### ISSUE THREAD

**Issue by oukjweather** [openlayers/openlayers#5169]
Starting with the base example http://openlayers.org/en/v3.15.0/examples/cluster.html, if you zoom in and out a bunch of times and look at how the memory behaves, particularly on Chrome, you will notice it grows. I performed a timeline on it and plotted out memory performed and even after doing a garbage collect found that the low end my memory would return to kept growing and the top end also kept growing.

**Comment by oukjweather** [comment]
![screen shot 2016-04-04 at 4 21 35 pm](https://cloud.githubusercontent.com/assets/8658773/14263657/79a04f88-fa81-11e5-999f-a61b9bd0a8c7.png)

This was the result from my last test on it. I started my test with a js heap of 93MB and it returned to 176 MB after doing a garbage collect by the end of the test before beginning its upward climb again.

**Comment by cmortazavi** [comment]
This causes the map to crash when using a large amount of features (200000features will cause the map to crash)
