### ISSUE TITLE
Some Problems in ol.source.WMTS when requesting GeoServer

### ISSUE THREAD

**Issue by rerintang** [openlayers/openlayers#5185]
I have checked _wmtssource.js_ , and found the TODO line: "add support for TileMatrixLimits". Then how could I load a WMTS source which is defined using _TileMatrixLimits _? I confused when I tried to load WMTS published by GeoServer / GeoWebCache. I discovered that the demo of GeoWebCache is still using OpenLayer 2.x.
So I wonder if there is a way to use ol3 loading GeoWebCache WMTS, or add the support for TileMatrixLimits in the next version. Thank you~

**Comment by fredj** [comment]
TileMatrixLimits support added in #5589
