### ISSUE TITLE
Difference between ol.js and ol-debug.js

### ISSUE THREAD

**Issue by MathieuCattin** [openlayers/openlayers#5204]
I am in special context.
I use OpenLayers in the Lutece Project, and i execute two instance of maps in the same page. When I create a point in the first map with ol.js library i detect an error.
But when i repeat the same action with the ol-debug.js library it's work.

The stack trace is this: 
    Uncaught TypeError: a.slice is not a function ol.js:439 
    ho @ ol.js:439
    Go @ ol.js:468
    l.Sc @ ol.js:472
    l.Ad @ ol.js:439

The method call to enter in the ol library is : 
    new ol.format.GeoJSON().writeFeature(feature, {
             featureProjection: projFeature,
             dataProjection: projData
    })

Thanks for your help

**Comment by cs09g** [comment]
check whether you're accessing some value directly like,
```
getLayers().getArray()[0].values_.source
``` 
instead
```
getLayers().getArray()[0].getSource() 
```
