### ISSUE TITLE
OL3 ImageCanvas renderFunction bad performance

### ISSUE THREAD

**Issue by WernerRaath** [openlayers/openlayers#5249]
So I'm experimenting using an [Esri opensource example (**windy.js**)](https://github.com/Esri/wind-js) and rendering it on OpenLayers 3 using something similar to [the OL3 D3 example](http://openlayers.org/en/v3.15.0/examples/d3.html).

**windy.js** renders a wind-animating map on a canvas.

First, I render the windy.js to a canvas and update it every 0.5 seconds:

```
g_windy = new Windy({
    canvas: $("#canvas")[0],
    data: //Some data
});
//map is an OL3 Map object
function redraw() {
  windy.stop();

  setTimeout(function() {
    var mapSize = map.getSize();
    var extent = map.getView().calculateExtent(mapSize);

    extent = ol.proj.transformExtent(extent, 'EPSG:3857', 'EPSG:4326');

    var canvas_bounds = [
        [0,0],
        [mapSize[0]*2, mapSize[1]*2]
      ]; 

      var map_projected_bounds = [
        [
          extent[0],
          extent[1]
        ],
        [
          extent[2],
          extent[3]
        ]
      ];

    windy.start(
      canvas_bounds,
      mapSize[0]*2, mapSize[1]*2, 
      map_projected_bounds
    );
  }, 500);
}

redraw();
```

My **canvasFunction** implementation references the canvas that windy.js renders to and returns it:

```
var canvasFunction = function(extent, resolution, pixelRatio, size, projection) {
  canvas = $("canvas#canvas")[0];
  canvas.setAttribute('width', map.getSize()[0]*4);
  canvas.setAttribute('height', map.getSize()[1]*4);
  return canvas;
};
```

I now add the layer to my map:

```
var canvasLayer = new ol.layer.Image({
  source: new ol.source.ImageCanvas({
    canvasFunction: canvasFunction,
    projection: 'EPSG:3857',
    ratio: 1
  })
});

map.addLayer(canvasLayer);
map.getView().on('change:center', redraw);
map.getView().on('change:resolution', redraw);

setInterval(function() { map.updateSize();}, 1);
```

My result gives me the **windy.js** layer on my map, but I am stuck with one issues:
- The windy.js canvas has zero performance issues and runs smoothly, but the OL3 layer is very laggy.

Copying the canvas is not a perfect implementation of what we are trying to achieve, but it is more efficient that doing a pull-request from OL3 and adding functionality that can support this feature.

**Comment by fredj** [comment]
can you provide a jsfiddle? it's hard to tell without testing it.

Add the `setInterval(function() { map.updateSize();}, 1);` looks suspicious: is it really needed to call the function every millisecond?
