### ISSUE TITLE
Not all features are returned from GML3 documents with many featureMember elements

### ISSUE THREAD

**Issue by beakdoctor** [openlayers/openlayers#5256]
If you perform a WFS GetFeature request to an ArcGIS Server (I've tried up to 10.3.1), the resulting FeatureCollection contains many featureMember elements, one for each feature. This is different from the default geoserver response, which contains a single featureMembers element that hosts each feature.

Geoserver can also be configured to return GML3 data like this, according to http://docs.geoserver.org/latest/en/user/data/app-schema/wfs-service-settings.html

Openlayers GML parser will in this case only return the last element, and this seems to be due to way the featureMember parser is constructed (with ol.xml.makeReplacer). If it is contructed with ol.xml.makeArrayPusher all features are returned.

I'm not confident enough to say this is clearly right or wrong, but I have commited this fix with a test case to my fork and I was wondering if I should send a pull request.

**Comment by bartvde** [comment]
What format are you using? If GML try with ```ol.format.WFS```

**Comment by beakdoctor** [comment]
I was using `ol.format.GML3`. It does indeed work as expected with `ol.format.WFS`! Why do they differ in this regard? Is it some WFS extension to the GML3 format? I can see that the WFS format alters the FEATURE_COLLECTION_PARSERS object to use makeArrayPusher for featureMember.

**Comment by bartvde** [comment]
I don't remember the exact details, but there should be something in older github issues somewhere ;-)

**Comment by bartvde** [comment]
Any chance you can verify if #5358 also fixed this for you?
