### ISSUE TITLE
Interim tiles shown when we switch time dimension

### ISSUE THREAD

**Issue by oterral** [openlayers/openlayers#5269]
Here an [example](http://codepen.io/oterral/pen/BKOwLZ), Click on play button.

The problem is the tiles of 2013 are shown when the layer switch between year 1944 to 1947.

I think the interim tiles are displayed when there is no tiles requested at the same place, even when we use `useInterimTilesOnError: false`

Any way to avoid this flicker?

**Comment by gjn** [comment]
@fredj care to take a look?

**Comment by oterral** [comment]
Weird it works, the bug seems fixed with version 3.20.1 but it is worse with version 4.0.1

**Comment by ahocevar** [comment]
@oterral If you'd be able to analyse what fixed it and what broke it again with `git bisect`, that would be helpful.

**Comment by oterral** [comment]
No, I'll try if have time this week.

**Comment by oterral** [comment]
All is linked to the regressionn describe in this issue https://github.com/openlayers/openlayers/issues/6289 and the fix https://github.com/openlayers/openlayers/pull/6290

**Comment by ahocevar** [comment]
So you're saying that fix in #6290 broke things for you?

**Comment by oterral** [comment]
Ok in fact the regression describe in #6289 seemed to have fixed this issue but it has removed the nice transition between tiles when we change time of a layer so it has not really fixed this issue.

The PR #6390 has re-introduced this bug but worse because the interim tiles doesn't disappear anymore when we switch time. 

I think the interim tiles don't disappear anymore because the `else` [here](https://github.com/openlayers/openlayers/pull/6290/files#diff-a32c17702fd55487d797d02bd01c03d6L140) has disappeared and has been replaced by a `if`.

**Comment by ahocevar** [comment]
This does not make sense to me. #6390 only introduced `@deprecated` annotations, and did not change any code.

**Comment by ahocevar** [comment]
Oh, you mean #6290. Look at the test there. It is expected behavior that interim tiles for the previous time are shown until the new time is loaded.

**Comment by oterral** [comment]
yes sorry mistyping.

**Comment by oterral** [comment]
Yes we have a special usecase here. When tiles are empty we returns 204 responses. Then the image is detected  as an error so if we have set `useInterimTilesOnError:false` the interim tile should disappear.

**Comment by ahocevar** [comment]
So are you saying that the `useInterimTilesOnError` option is ignored or does not work as intended?

**Comment by oterral** [comment]
Yes

**Comment by ahocevar** [comment]
Would you be able to create a pull request with a fix?

**Comment by oterral** [comment]
I'll try :)

**Comment by oterral** [comment]
Sorry can't find the problem. I'm missing something probably.
