### ISSUE TITLE
node_modules very large

### ISSUE THREAD

**Issue by DanielSundberg** [openlayers/openlayers#5284]
OpenLayers related stuff takes up a lot of space in node_modules:
![2016-04-28 08_33_10-c__code_coreweb_coreinsats_source_insatsrapportweb_node_modules - windirstat](https://cloud.githubusercontent.com/assets/1454200/14881331/c9847c12-0d33-11e6-9e2c-614e89519037.png)

I'm only building a very simple map control using OpenLayers/Javascript, do I really need to get OpenLayes coverage folder and closure-utils on my system?
![2016-04-28 08_43_28-c__code_coreweb_coreinsats_source_insatsrapportweb_node_modules - windirstat](https://cloud.githubusercontent.com/assets/1454200/14877448/61745c48-0d1d-11e6-8dec-f3209cef35ef.png)

I know I could use the ol.js directly but having all dependencies specified in package.json is very nice.

**Comment by fredj** [comment]
closure-util was removed in #7570
