### ISSUE TITLE
New Feature: Text in Scaleline

### ISSUE THREAD

**Issue by sweco-seachr** [openlayers/openlayers#5311]
I was working on a project that wanted a scale in the application, I found out that it was quite simpel to implement this in the scalelinecontrol.js and looks nice at the same time. See Picture. 
For now I have hard coded a array in scalelinecontrol.js, but want to add a parameter to constructor instead. 
![scaleline](https://cloud.githubusercontent.com/assets/17084259/15013861/67a40ffc-1202-11e6-9127-785903f5c377.png)

Current solution is bounded to the resolution.

Use case:
The user want to see the scale on the OL3 map, as the see in several of the desktop programs. By sending a array when creating scalelinecontrol.js, you can easy display this in the scale line box.

**Comment by cs09g** [comment]
+1 for custom scaleline text for each level
