### ISSUE TITLE
cant set sketchPoint in draw interaction (for modifying color and geometry)

### ISSUE THREAD

**Issue by itayod** [openlayers/openlayers#5312]
I couldn't find an option to set the sketchPoint property for change its color.
also I was wondering why id the draw interaction not a class with subclasses for every type
instead of one big class with many modes?
that way for my opinion the code will be more clean and readable,
and also every user could extend this basic class in order to create a different behavior for his own geometry types (geometryFunction isn't good enough for what I need).

**Comment by tsauerwein** [comment]
The draw interaction takes a `style` property for the sketch features, see in the API docs: http://openlayers.org/en/master/apidoc/ol.interaction.Draw.html

**Comment by raiis** [comment]
My question is similar to this - with current style implementation it is no possible to have dynamic styling. E.g. user selects in which color to draw line and in drawing process can change color to other. 
After 'featuradd' those are set as properties, but is any way how to achieve  similar behavior while drawing?
