### ISSUE TITLE
New Feature: Triggering tile load events on ol.sourceVector when tile loading strategy is employed

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/openlayers#5325]
On tiled source it is possible to count tileloadstart/tileloadend/tileloaderror events to check if all tiles have been loaded:
http://openlayers.org/en/master/examples/tile-load-events.html
It would be nice to do the same for ol.sourceVector if loading strategy is set to ol.loadingstrategy.tile

Thanks :-)

**Comment by ahocevar** [comment]
If you want tile load events, you should use `ol.source.VectorTile`. What might make sense though would be the introduction of an `addfeatures` event, which would be triggered when the source's `addFeatures` method is called.

**Comment by jan-tosovsky-cz** [comment]
1. The intended goal is to enable kind of progress bar, similar to that in the linked example. 
2. The secondary goal is to capture a moment when all tiles are loaded to perform subsequent steps (which don't make any sense when loading is in progress).
3. While addFeatures might be handy in certain scenarios, I don't think it is sufficient for those aforementioned ones.

**Comment by ahocevar** [comment]
There are no tiles when you use an `ol.loadingstrategy.tile`, there are only extents that follow a tiling scheme. So when you zoom in, no new data will be loaded at all. When you zoom out, only the regions that previously had no data coverage will be loaded, using extents that follow the provided `tileGrid`.

Again, if you want real tiles, use `ol.source.VectorTile` with an appropriate data source.

**Comment by ahocevar** [comment]
What you can also do is configure a custom `loader` on the source. With that, you can keep track of when loading of an extent starts and when it finishes.

**Comment by jan-tosovsky-cz** [comment]
Thanks for clarification. I supposed when tile strategy is used, it is always complemented with custom URL function, which takes resolution as a parameter:
`url: function(extent, resolution) { ... }`
In this particular case only data for the given zoom level are loaded.
If this assumption was incorrect, a custom loader seems to be a more sensible option here.

**Comment by jan-tosovsky-cz** [comment]
Hmm, an ideal entry point seems to be customized `ol.featureloader.xhr` loader, especiallly that inner `loadFeaturesXhr()` method with success/failure function params. If those could be customized to increase my global counter (or trigger new `tileloadend`/`tileloaderror` events), it would be nice. 
```javascript
ol.featureloader.xhr = function(url, format) {
  return ol.featureloader.loadFeaturesXhr(url, format,
      /**
       * @param {Array.<ol.Feature>} features The loaded features.
       * @param {ol.proj.Projection} dataProjection Data projection.
       * @this {ol.source.Vector}
       */
      function(features, dataProjection) {
        this.addFeatures(features);
      }, /* FIXME handle error */ ol.nullFunction);
};
```
But that `loadFeaturesXhr()` method seems to be private and cannot be used as intended, see the commented code:
```javascript
var vectorSource = new ol.source.Vector({
   loader: ol.featureloader.xhrX(url, format),
   strategy: ol.loadingstrategy.tile(tileGrid)
});

// forked method, but the inner 'loadFeaturesXhr' method seems to be private and cannot be used 
ol.featureloader.xhrX = function(url, format) {
   /*
      return ol.featureloader.loadFeaturesXhr(url, format,
         function(features, dataProjection) {
            this.addFeatures(features);
            // when tile loading succeeds
            tilesLoaded++;
         },
         function() {
            // when tile loading fails
            tilesLoaded++;
         });
   */
   // just returning the original loader
   return ol.featureloader.xhr(url, format);
}
```
Would that loadFeaturesXhr() method become public? I'd like to avoid touching the original OL3 sources and I can't see any other place where to count loaded tiles.

Btw, the total count of tiles to load can be determined in the custom url function:
```javascript
var url = function(extent, resolution) {
   tilesToLoad++; // when a new tile is needed, this counter is incremented
   var tileCoord = tileGrid.getTileCoordForCoordAndResolution(ol.extent.getCenter(extent), resolution);
   return 'tiles/' +
      tileCoord[0] + '/' +
      tileCoord[1] + '/' +
      (Math.pow(2, tileCoord[0]) + tileCoord[2]) + '.json';
}
```

**Comment by ahocevar** [comment]
As I said already, it is easy to configure your own loader, instead of using the built-in `ol.featureloader.xhr`. See e.g. http://openlayers.org/en/latest/examples/vector-esri.html.

**Comment by jan-tosovsky-cz** [comment]
@ahocevar thanks for that link to the custom loader. It was not indeed as hard as expected to make a my customized one. The progress component works, but there is still issue in the strategy function as it doesn't call my loader in every case. I'll investigate and eventually report a new issue.
