### ISSUE TITLE
Issue regarding webgl renderer

### ISSUE THREAD

**Issue by jacmendt** [openlayers/openlayers#5331]
Dear openlayers team. 

I am working on a project, where I use webgl shaders for producing different kind of maps. As a base system (interactions, base maps, etc.) I am trying to use ol3, which works in first tests very well.  

When working on the project, I stumbled over some strange behavior and I am not yet sure if it is due to my webgl code or due to some strange behavior of the ol3 webgl renderer. 

I created a [Fiddle](https://jsfiddle.net/jacmendt/ubjfbq6t/) where I tried to reproduce the problem. Basically I wrote some code which extracts the texture data of a given canvas and draws it with a webgl program on a new canvas. The input canvas is thereby a ol3 map. When I use ol3 with a canvas renderer the program runs correctly, but when I use ol3 with webgl renderer I am `sometimes` (meens not copy interaction) missing some tiles. The result than looks like this:

![ol3-webgl-problem](https://cloud.githubusercontent.com/assets/5071511/15172430/4c3622c4-1756-11e6-8bc0-15c41f45352d.png)

It looks a bit like missing tiles. I produced that error in a chromium browser (Version 49.0.2623.108 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)). Further when I run the same fiddle in my firefox browser (45.0) the copying of the webgl based map does not work at all, what confuses me even more. I would expect at this point that the output with webgl renderer is the same as with the canvas renderer.

If you thing the issue sections isn't the right place to discuss this topic do not hesitate to close it. Otherwise I would be happy to get some feedback on this topic.

P.S. I really like the WebGL Inspector addon of the chrome browser. But in my setup this addon also does not work with ol3.

**Comment by tsauerwein** [comment]
Have you tried to do the export in a `postcompose` event like in the [export example](http://openlayers.org/en/master/examples/export-map.html)?

https://jsfiddle.net/ubjfbq6t/3/

This should ensure that the map canvas is ready.

**Comment by jacmendt** [comment]
Yes, in the normal application i hook within the postcompose event and there i identify the behavior for the first time. For a better exploration of this problem i switch to manually triggering the copy event, but it stays the same. Like you see in the image above, the map is already loaded complete, but the copying does not use all tiles.

**Comment by fredj** [comment]
https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#drop-of-support-for-the-experimental-webgl-renderer
