### ISSUE TITLE
Clarify API description for ol.source.Vector with combination of ol.loadingstrategy.tile

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/openlayers#5348]
It should be emphasized that tile strategy for vector tiles support only data in a single resolution (zoom level). While it may be obvious, there are scenarios where vector data are specially crafted for each zoom level - with variable level of details. Such tiles could be loaded using a custom loader, however, this loader is called only if the particular extent is not processed yet. Unfortunately, this check ignores the zoom level (and there is no option for this), so when tiles for the particular extent were already loaded/cached, they will never be reloaded again for a different zoom level.

**Comment by ahocevar** [comment]
Yes, vector layers are for WFS style data, i.e. unsimplified features, fetched by extents. Pull request welcome to make the docs clearer about this.
