### ISSUE TITLE
SSL Required in the editable ArcGIS REST example

### ISSUE THREAD

**Issue by afogelberg** [openlayers/openlayers#5351]
The example page with editable ArcGIS REST Feature Service throws the error SSL Required:
http://openlayers.org/en/latest/examples/vector-esri-edit.html?q=ar

**Comment by fredj** [comment]
See also #5276

**Comment by bartvde** [comment]
I could change serviceUrl to use https for the AGS services but this will lead to mixed content warnings I guess

**Comment by fredj** [comment]
fixed with 2e5ecd1efb518697a4aac4ad2e71afe26462613c
