### ISSUE TITLE
About heatmap's feature's weight

### ISSUE THREAD

**Issue by ZoeHuang13** [openlayers/openlayers#5373]
My data is (lonlat,peoplecount), and the number of people range from 10 to 1000.
But the heatmap's feature's weight range from 0 to 1.
So I need to  normalize the number of people to  (0,1)?

**Comment by fredj** [comment]
> So I need to normalize the number of people to (0,1)?

yes, you must set the `weight` property to a value from 0 to 1

**Comment by ZoeHuang13** [comment]
I think this restriction is very inconvenient. Is it possible to cancel this limitation? Otherwise, we have to do the normalization by ourself.

**Comment by Distem** [comment]
> Otherwise, we have to do the normalization by ourself.

Internal normalization doesn't really make sense. Say your heatmap data can go from 0 to 1000, but in your current data the max value is 100 - with internal normalization the weight for 100 will be 1.0, when if you normalize the data with your data limit the weight for 100 will be 0.1 - therefore the resulting heatmaps will be different. 
Also adding a new point with value >100 will result in weight >1.0 therefore the weights for all of the points will need to be re-calculated which might not be what you want. 

I guess that is the main reason why you have to normalize the weights.

**Comment by cs09g** [comment]
Right, If you add the data at once and will not add anymore, then it's fine for auto normalization from OL. but if you need to add new data when heatmap exists, all the weight should be recalculated.
