### ISSUE TITLE
Ability to modify pixels after loading a raster tile (before rendering the tile)

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/openlayers#5396]
It is possible to manipulate individual pixels:
http://openlayers.org/en/latest/examples/image-filter.html
However, it only works as expected for a topmost layer which is completely opaque.
If that layer is transparent, pixel colors are blended with the layers in the background which prevents from using this method for specific needs.

If raster tiles need to be manipulated dynamically according to user settings, moreover this processing is isolated to a specific layer with customizable transparency, it would be better to manipulate tile data just after loading tiles - before rendering them to the canvas. This would be even more efficient than manipulating all pixels on postcompose event as it process all pixels in the map on every rerendering (when moving the map or changing the map size).

While for vector sources it is possible to specify a custom loader, there is missing a similar ability for raster data. But instead of implementing all the raster rendering to the canvas, maybe a custom entry point in the form of new 'postTileLoadMethod' parameter could be sufficient here. It would pass the original pixels (RGBA), manipulate them and then send them back for standard processing.

**Comment by tsauerwein** [comment]
Have you seen [ol.source.Raster](http://openlayers.org/en/master/apidoc/ol.source.Raster.html)?
http://openlayers.org/en/master/examples/color-manipulation.html
http://openlayers.org/en/master/examples/raster.html

**Comment by jan-tosovsky-cz** [comment]
Yes, tried, found some problems, gave up:

1.  When the layer is zoomed or moved, it jumps unexpectedly aside and then it returns back - can be seen on that color-manipulation example. In one discussion (I cannot find any more) there was a suggestion to specify the extent which was marked as answer that fixed the problem. Not tested.

2.  While my pixel operation is correct when map is rendered for the first time, when map is zoomed, weird pixel values (not corresponding to the source data) are passed to my method. I suspect some remnants of rerendering the layer are colliding here.

3.  The entire (and same) scene seems to be processed several times (when logging raster.on('beforeoperations') method) which is rather discouraging for my CPU intensive processing.

But I agree the concept of raster layer is very close to my idea. However, until that (2) is fixed, I am stuck.

**Comment by jan-tosovsky-cz** [comment]
Ad 1. That workaround was related to a static image, which is not my case. I'll file a separate issue for this.

Ad 2. After careful debugging I found those artefacts were caused by edge case in my pixel processing.

Ad 3. Still unclear if each pixel (in my tiled source) is processed several times or not.

**Comment by thhomas** [comment]
I am experiencing issue 1 when layer is zoomed or moved it jumps unexpectedly. Have you filed an issue for this? I would be interested to follow it.

**Comment by jan-tosovsky-cz** [comment]
@thhomas  not yet, please do, I am investigating another approaches (currently WebGLFragment Shader) so not interested any more.

**Comment by uazure** [comment]
I'd would be happy to see functionality to modify image data for raster tiles. The best option that I have now is to hack `tileLoadFunction` to return image that was modified right after being loaded.
But that doesn't cover all the cases. For example, if color for raster layer should be adjusted, then I have to re-fetch the rasters to trigger image manipulation logic which is in `tileLoadFunction`

**Comment by uazure** [comment]
I've found a solution to the problem.

Idea is the following:
0) create `class ColorCanvasTile extends Tile` that has a canvas with the initially loaded data and a coloredCanvas that is updated on renders if color changes. To adjust color you may use getImageData/putImageData of the canvas context.

1) When creating source provide a `tileClass: ColorCanvasTile` in options. The `source` should have color property set, like `source.set('color', myColor)`. Don't forget to call `source.changed()` after changing color property to trigger re-rendering of the layer

2) ColorCanvasTile in it's `geImage(layer)` method implementation can get the source's color like this
`layer.getSource().get('color')` and check if it's changed then coloredCanvas should be updated and then given back. You must make sure that original canvas is returned when tileLoadFunction expects it.

I spend 2 days investigating how OL actually renders tile layers and where it's possible to put hacks to make it change tile colors on fly without re-fetching them before finding this solution.
I can say that openlayers documentation rather sucks. It doesn't help a lot to understand the responsibility of different classes and their relation to other classes.

**Comment by bodhifan** [comment]
Hi @uazure, I face the same problem, after search Tile class I cann't find the initial canvas. I just want to modify pixels color after image tile loaded. could you share your code with me? or tell me how to implement it？
