### ISSUE TITLE
SVG ol.style.Icon does not render in some browsers

### ISSUE THREAD

**Issue by dtreiter** [openlayers/openlayers#5412]
**Issue:** When using an `ol.style.Icon` with an inline SVG source, it will render correctly in Chrome and Safari, but will not appear in Firefox, Edge, or IE11.

**Example:** https://jsfiddle.net/kk32q47q/1/
Note: I also demonstrate an `ol.style.Circle` icon as well as manually inserting an SVG into the DOM. Both work correctly.

**Expected behavior:** Renders a black SVG square icon on the map.

**Actual behavior:** Doesn't render the SVG square in Firefox, Edge, or IE11.

**Comment by fredj** [comment]
See #4701

**Comment by spatialillusions** [comment]
This was working up until 3.12 but then something broke in IE again. http://jsfiddle.net/5jx0dzpu/9/ 
See #4090, for my usecase I have now transitioned to canvas icons instead.

**Comment by aAXEe** [comment]
I have the same problem.

I tried to create an `<img>` element with the source set to the svg .. but the problem is the same.

Updated fiddle: https://jsfiddle.net/kk32q47q/8/

Error message in the js console with Firefox:
```
NS_ERROR_NOT_AVAILABLE: 
context.drawImage(image, originX, originY, w, h,
ol-debug.js (line 50604)
```

Basic code:
```
  const img = document.createElement('IMG')
  img.src = 'data:image/svg+xml;charset=utf-8,' + svg
  const imgSize = [img.naturalWidth, img.naturalHeight]

  const iconStyle = new ol.style.Style({
    image: new ol.style.Icon({
      img: img,
      imgSize: imgSize
    })
  })
```

**Comment by ahocevar** [comment]
Your code above will not work, because the `naturalWidth` and `naturalHeight` of the image are not available before it is loaded. You can either set the `src` instead of the `img` on `ol.style.Icon`, or use code like this:
```js
const img = document.createElement('IMG');
img.onload = function() {
  const imgSize = [img.naturalWidth, img.naturalHeight];
  const iconStyle = new ol.style.Style({
    image: new ol.style.Icon({
      img: img,
      imgSize: imgSize
    })
  });
};
img.src = 'data:image/svg+xml;charset=utf-8,' + svg;
```

**Comment by aAXEe** [comment]
Thanks for the hint. Do you have a source for this? 
I don't find anything about this and is didn't change the effect.

But it helped me to find the problem: firefox rejected the src and didn't load any image.
After some research I found the reson and solution for this:

Some browser care "more" about a valid URI. Just placing the `<svg>...</svg>` inside the src attribute violates the encoding. See [this article](http://dbushell.com/2013/02/04/a-primer-to-front-end-svg-hacking/) and a [live demo](http://dbushell.com/demos/svg/utf8uri/test2.html).
As you can see chrome loads the example with invalid encoding just fine.

The same applies to our problem. Just encode the svg into valid UTF8!
```
img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg)
```
See also the updated fiddle: https://jsfiddle.net/kk32q47q/12/

Sidenote: even with correct encoding the original svg from @dtreiter makes problems.

**Comment by JamesMilnerUK** [comment]
If you're having this error potentially try using the src property as opposed to creating a custom image element. That made the `NS_ERROR_NOT_AVAILABLE:` dissapear.

So:

```
      var src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent( iconSVG );

        var iconStyle = new ol.style.Style({
            "image": new ol.style.Icon({
                src : src,
                "imgSize":[labelWidth, 66],
                "anchor": [0.5, 0.5],
                "offset": [0, -50]
            })
        });
```

Rather than:

```
  var imageElement = new Image();
        imageElement.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent( iconSVG );

        var iconStyle = new ol.style.Style({
            "image": new ol.style.Icon({
                src : imageElement,
                "imgSize":[labelWidth, 66],
                "anchor": [0.5, 0.5],
                "offset": [0, -50]
            })
        });
```

**Comment by romanzoller** [comment]
Some information in case anyone else is trying to get SVG icons working in IE11:

Re @ahocevar 
> Your code above will not work, because the naturalWidth and naturalHeight of the image are not available before it is loaded. You can either set the src instead of the img on ol.style.Icon, or use code like this: [...]

While this is generally correct for sane browsers, as far as I can tell (by testing myself) this doesn't work in IE11 either, because IE11 is also buggy with respect to naturalWidth/naturalHeight and just returns 0x0, see also [this SO question](https://stackoverflow.com/questions/22822921/how-can-i-get-width-and-height-of-svg-on-image-load-in-ie-11).

As far as I can tell, if you want to get SVG icons working in IE11, you have to set `"imgSize"`, which can be done in one of these ways:
- Set it to constant width/height, if you are lucky enough to have SVGs that are all the same size or if you do some build-time or server-side pre-processing.
- [Parse the SVG using DOMParser or jQuery](https://github.com/kangax/fabric.js/issues/1053#issuecomment-92100710) or an ugly regexp to extract width and height.
- Attach an `<img>` to the DOM and wait for it to load as suggested on [SO](https://stackoverflow.com/questions/22822921/how-can-i-get-width-and-height-of-svg-on-image-load-in-ie-11), with the caveat that this is probably slow, certainly ugly, and may significantly increase code complexity because you now have to handle the fact that initializing styles is asynchronous.

**Comment by vipcxj** [comment]
> Some information in case anyone else is trying to get SVG icons working in IE11:
> 
> Re @ahocevar
> 
> > Your code above will not work, because the naturalWidth and naturalHeight of the image are not available before it is loaded. You can either set the src instead of the img on ol.style.Icon, or use code like this: [...]
> 
> While this is generally correct for sane browsers, as far as I can tell (by testing myself) this doesn't work in IE11 either, because IE11 is also buggy with respect to naturalWidth/naturalHeight and just returns 0x0, see also [this SO question](https://stackoverflow.com/questions/22822921/how-can-i-get-width-and-height-of-svg-on-image-load-in-ie-11).
> 
> As far as I can tell, if you want to get SVG icons working in IE11, you have to set `"imgSize"`, which can be done in one of these ways:
> 
> * Set it to constant width/height, if you are lucky enough to have SVGs that are all the same size or if you do some build-time or server-side pre-processing.
> * [Parse the SVG using DOMParser or jQuery](https://github.com/kangax/fabric.js/issues/1053#issuecomment-92100710) or an ugly regexp to extract width and height.
> * Attach an `<img>` to the DOM and wait for it to load as suggested on [SO](https://stackoverflow.com/questions/22822921/how-can-i-get-width-and-height-of-svg-on-image-load-in-ie-11), with the caveat that this is probably slow, certainly ugly, and may significantly increase code complexity because you now have to handle the fact that initializing styles is asynchronous.

Why this still not work? I have set the imgSize.
```js
new ol.style.Icon({
      color: "#cc3388",
      imgSize: [68.673, 68.674],
      src: "data:image/svg+xml,%3c%3fxml version='1.0' encoding='iso-8859-1'%3f%3e %3csvg version='1.1' id='Capa_1' fill='white' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' x='0px' y='0px' width='68.673px' height='68.674px' viewBox='0 0 68.673 68.674' style='enable-background:new 0 0 68.673 68.674%3b' xml:space='preserve'%3e %3cg%3e %3cpath d='M67.682%2c30.151L53.394%2c19.149V7.684c0-1.404-1.141-2.544-2.544-2.544c-1.402%2c0-2.543%2c1.14-2.543%2c2.544v7.548L35.889%2c5.668 c-0.915-0.703-2.188-0.703-3.104%2c0L0.992%2c30.151c-1.113%2c0.856-1.32%2c2.453-0.463%2c3.566c0.855%2c1.112%2c2.453%2c1.319%2c3.566%2c0.463 l2.793-2.15v28.961c0%2c1.403%2c1.14%2c2.543%2c2.544%2c2.543h49.493c1.403%2c0%2c2.543-1.14%2c2.543-2.543V31.784l3.11%2c2.396 c0.463%2c0.356%2c1.008%2c0.529%2c1.551%2c0.529c0.763%2c0%2c1.517-0.341%2c2.018-0.992C69.001%2c32.604%2c68.794%2c31.007%2c67.682%2c30.151z M29.103%2c30.664 c1.717%2c0%2c3.107%2c1.393%2c3.107%2c3.108c0%2c1.718-1.391%2c3.109-3.107%2c3.109s-3.109-1.394-3.109-3.109 C25.994%2c32.057%2c27.386%2c30.664%2c29.103%2c30.664z M21.189%2c36.565c1.717%2c0%2c3.108%2c1.393%2c3.108%2c3.107s-1.392%2c3.107-3.108%2c3.107 c-1.718%2c0-3.108-1.394-3.108-3.107C18.081%2c37.954%2c19.472%2c36.565%2c21.189%2c36.565z M24.026%2c49.432c-0.001%2c0-0.002%2c0-0.004%2c0h-0.365 l0.404%2c1.619c0.031%2c0.127%2c0.003%2c0.261-0.077%2c0.362c-0.081%2c0.104-0.204%2c0.164-0.335%2c0.164h-0.642l-0.22%2c2.734 c-0.018%2c0.223-0.201%2c0.391-0.423%2c0.391h-2.353c-0.221%2c0-0.404-0.168-0.422-0.391l-0.219-2.734h-0.643 c-0.131%2c0-0.254-0.062-0.334-0.164s-0.108-0.235-0.076-0.362l0.404-1.619h-0.365c-0.119%2c0-0.232-0.049-0.312-0.136 c-0.08-0.09-0.12-0.204-0.111-0.321l0.424-5.272c0.019-0.222%2c0.203-0.392%2c0.424-0.392H23.6c0.221%2c0%2c0.404%2c0.17%2c0.422%2c0.392 l0.418%2c5.188c0.01%2c0.038%2c0.016%2c0.077%2c0.016%2c0.118C24.455%2c49.243%2c24.277%2c49.427%2c24.026%2c49.432z M32.8%2c46.349 c-0.08%2c0.085-0.191%2c0.135-0.309%2c0.135h-0.725l0.568%2c2.346c0.025%2c0.057%2c0.039%2c0.115%2c0.039%2c0.182c0%2c0.234-0.189%2c0.419-0.428%2c0.424 c-0.002%2c0-0.003%2c0-0.005%2c0h-0.693l-0.298%2c4.874c-0.014%2c0.226-0.199%2c0.396-0.424%2c0.396h-2.786c-0.225%2c0-0.409-0.174-0.423-0.396 l-0.299-4.874h-0.693c-0.13%2c0-0.252-0.061-0.333-0.162c-0.081-0.101-0.109-0.234-0.079-0.359l0.587-2.428h-0.725 c-0.116%2c0-0.229-0.049-0.309-0.135c-0.08-0.085-0.122-0.197-0.114-0.314l0.502-8.225c0.014-0.223%2c0.199-0.396%2c0.424-0.396h5.709 c0.225%2c0%2c0.409%2c0.177%2c0.423%2c0.396l0.503%2c8.225C32.921%2c46.149%2c32.879%2c46.264%2c32.8%2c46.349z M47.483%2c36.353 c1.719%2c0%2c3.109%2c1.393%2c3.109%2c3.108s-1.394%2c3.106-3.109%2c3.106c-1.715%2c0-3.107-1.391-3.107-3.106S45.766%2c36.353%2c47.483%2c36.353z M39.571%2c30.664c1.717%2c0%2c3.107%2c1.393%2c3.107%2c3.108c0%2c1.718-1.392%2c3.109-3.107%2c3.109c-1.717%2c0-3.107-1.394-3.107-3.109 C36.46%2c32.057%2c37.853%2c30.664%2c39.571%2c30.664z M43.235%2c46.349c-0.078%2c0.085-0.189%2c0.135-0.309%2c0.135h-1.062l-0.479%2c7.822 c-0.013%2c0.225-0.197%2c0.396-0.423%2c0.396h-2.786c-0.226%2c0-0.41-0.174-0.425-0.396l-0.479-7.822h-1.062 c-0.116%2c0-0.229-0.05-0.311-0.135c-0.08-0.085-0.121-0.199-0.113-0.314l0.502-8.225c0.015-0.224%2c0.199-0.396%2c0.424-0.396h5.71 c0.225%2c0%2c0.409%2c0.176%2c0.424%2c0.396l0.502%2c8.225C43.357%2c46.149%2c43.316%2c46.264%2c43.235%2c46.349z M50.628%2c49.296 c-0.08%2c0.087-0.193%2c0.136-0.312%2c0.136h-0.842l-0.393%2c4.884c-0.021%2c0.221-0.201%2c0.391-0.424%2c0.391h-2.354 c-0.223%2c0-0.404-0.17-0.422-0.391l-0.396-4.884h-0.843c-0.118%2c0-0.23-0.049-0.312-0.136c-0.08-0.09-0.121-0.204-0.111-0.321 l0.424-5.272c0.019-0.222%2c0.203-0.392%2c0.424-0.392h4.818c0.221%2c0%2c0.404%2c0.17%2c0.422%2c0.392l0.424%2c5.272 C50.748%2c49.092%2c50.707%2c49.206%2c50.628%2c49.296z'/%3e %3c/g%3e %3c/svg%3e"
 })
```

**Comment by rkaravia** [comment]
> Why this still not work? I have set the imgSize.
@vipcxj: I believe IE only supports base64 data urls, as a first step, you could test if your data url works as src of an <img> element.

**Comment by vipcxj** [comment]
@rkaravia, I have tested, a simple html only with the img of this src is valid in ie 11

**Comment by MadalenaGoncalves** [comment]
I'm having this problem now. In my case, I'm updating the styles of a feature rendered with ol.Icon.
**Example**: https://jsfiddle.net/madalenagoncalves/f4sqnkgt/4/

This example breaks only on Firefox and not on Chrome. However, in my original code (quite more complex), the issue happens also on Chrome.

Am I doing something wrong or is it a problem with the API or with the browsers?
Thanks for the help.

**Comment by MadalenaGoncalves** [comment]
@rkaravia thanks for the reply and for the link to the stackoverflow question! That was helpful.

**Comment by si-ev** [comment]
It seems, I've caught the same bug.  The following snippet renders svg in Chrome and Vivaldi, but not in Firefox.
 
https://jsbin.com/juhehumezo/1/edit?html,css,js,output

**Comment by ahocevar** [comment]
@si-ev The svg in your example lacks a width and height. When a browser renders svg as `Image`, it needs to know the size. You can try to render that svg as image in any browser, and the results will not be consistent:
```svg
<svg viewBox="0 0 120 120" version="1.1"
  xmlns="http://www.w3.org/2000/svg">
  <circle cx="10" cy="10" r="10" fill="blue"/>
</svg>
```

![test](https://user-images.githubusercontent.com/211514/198096000-959136cc-7eea-463d-a107-c175cfa52c4c.svg)

That said, what size would you expect when rendering that svg?
