### ISSUE TITLE
Consider adopting Bazel Closure Rules

### ISSUE THREAD

**Issue by jart** [openlayers/openlayers#5420]
Greetings. I noticed [closure.md](https://github.com/openlayers/ol3/blob/master/doc/tutorials/closure.md) says you use the Closure Compiler for this project. In that case, you may want to consider adopting [Closure Rules for Bazel](https://github.com/bazelbuild/rules_closure) as your build system. This is an effort to open source the build system Google uses internally for JavaScript. Since you're already writing JavaScript in a very Googley way, you have the most to benefit from Closure Rules.

As maintainer of the Closure Rules project, I would be greatly honored if ol3 considered adopting it. I want you to know that I will do everything in my power to help your migration be successful.

Is migrating something you would consider?

**Comment by fredj** [comment]
closure-compiler is not used anymore, closing.
