### ISSUE TITLE
Viewport's canvas not resizing when embedded in a Polymer  webcomponent's shadowdom

### ISSUE THREAD

**Issue by spiderkeys** [openlayers/openlayers#5435]
I've been trying to figure out how to get an OL3 map properly wrapped in a polymer element (using polymer 1.5) and have been running into an issue where the viewport's canvas is not getting properly resized at the time of map creation, and thus the map does not render until the window dispatches a "resize" event. I initially tried to manually fire one off after the map was created to force this behaviour, but it seems like there is some kind of timing issue and I have to delay the "resize" event for a bit after creating the map to get it to resize. I couldn't find any kind of "map ready" event to trigger off of, rather than just setting a timeout with 1 second after creating the map. The code for my component can be found here:

https://github.com/OpenROV/openrov-cockpit/blob/master/src/plugins/gps/public/webcomponents/orov-map.html

Is this an issue with putting an OL3 in a polymer element or is there a better way to handle map creation when wrapping it like this? Thanks.

**Comment by spiderkeys** [comment]
Here is the DOM before and after for the ol-viewport element:

When page displays, before resizing the window or otherwise causing a window 'resize' event to fire:
![before](https://cloud.githubusercontent.com/assets/859469/15809115/1be8393a-2b3e-11e6-98c9-b842b23c5bf7.png)

After resizing or forcing a resize event:
![after](https://cloud.githubusercontent.com/assets/859469/15809116/1f99ecf4-2b3e-11e6-8633-503823e86eee.png)

**Comment by ahocevar** [comment]
Calling `ol.Map#updateSize()` should help, once your application's resize operation is completed. Note that OpenLayers only listens to browser window resize events.

**Comment by spiderkeys** [comment]
In my code, ol.Map#updateSize() is called here:

https://github.com/OpenROV/openrov-cockpit/blob/master/src/plugins/gps/public/webcomponents/orov-map.html#L122

If I don't set the timeout to fire the browser resize event with the short delay afterwards, the canvas never resizes. I'm not sure why I need to fire a resize event after using the updateSize() command and am more confused about why I can't immediately fire the event, rather than delaying it with a timeout.

**Comment by BartTK** [comment]
Same for me. When the map gets resized externally, I have to delay the updateSize() call for about 300ms. Calling it directly or with a shorter delay has no effect.

**Comment by cs09g** [comment]
@BartTK What about to use something like ```map.once('postrender', function())```

**Comment by BartTK** [comment]
That doesn't do the trick. On the external resize, I registered that handler and force the map to render. The updateSize() gets called but has not effect.

**Comment by BartTK** [comment]
That doesn't do the trick. On the external resize, I registered that handler and force the map to render. The updateSize() gets called but has not effect.
