### ISSUE TITLE
DWithin filter

### ISSUE THREAD

**Issue by bartvanandel** [openlayers/openlayers#5458]
I know support for OGC filtering is still experimental, but are there any plans to include the DWithin filter? Example filter:

``` xml
<ogc:DWithin>
    <ogc:PropertyName>Location</ogc:PropertyName>
    <gml:Point srsName="EPSG:4326" xmlns:gml="http://www.opengis.net/gml">
        <gml:pos>123.45 54.321</gml:pos>
    </gml:Point>
    <ogc:Distance units="http://www.opengeospatial.org/se/units/metre">15</ogc:Distance>
</ogc:DWithin>
```

My first (and only) attempt for now was to patch it in externally to a version loaded from npm. Besides being a very ugly hack, I'm probably using the wrong methods, but I did not have much time to dive deep.

``` js
import ol from 'openlayers';

// Attempt to patch DWithin filter into loaded npm package
const DWithin = function(propertyName, point, opt_srsName, distance, opt_units) {
    goog.base(this, 'DWithin');
    this.propertyName = propertyName;
    this.point = point;
    this.srsName = opt_srsName;
    this.distance = distance;
    this.units = opt_units || 'http://www.opengeospatial.org/se/units/metre';
};
goog.inherits(DWithin, ol.format.ogc.filter.Filter);

ol.format.WFS.GETFEATURE_SERIALIZERS_['http://www.opengis.net/ogc']['DWithin'] =
    ol.xml.makeChildAppender(function(node, filter, objectStack) {
        ol.format.WFS.writeOgcPropertyName_(node, filter.propertyName);
        ol.format.GML3.prototype.writeGeometryElement(node, filter.point, objectStack);

        const distanceNode = ol.xml.createElementNS('http://www.opengis.net/ogc', 'Distance');
        distanceNode.setAttribute('units', filter.units);
        ol.format.XSD.writeStringTextNode(distanceNode, filter.distance+'');
        node.appendChild(distanceNode);
    });
```

Anyone with more experience on the `openlayers` internals?

NB: at this point it would actually be fine if we could just insert a raw piece of XML as one of the filters, so we can combine custom, (still) unsupported filter types with existing filters.

**Comment by tsauerwein** [comment]
> NB: at this point it would actually be fine if we could just insert a raw piece of XML as one of the filters, so we can combine custom, (still) unsupported filter types with existing filters.

`ol.format.WFS()#writeGetFeature()` returns a XML node which you could modify. Something like this:

```js
var featureRequest = new ol.format.WFS().writeGetFeature({...});
var query = featureRequest.childNodes[0];
var filter = query.childNodes[0];

var within = document.createElement('DWithin');
var propertyName = document.createElement('PropertyName');
propertyName.textContent = 'the_geom';
...
filter.appendChild(dwithin);
```

But if you could provide a PR that adds support within ol3, that would be great.

**Comment by bartvanandel** [comment]
> `ol.format.WFS()#writeGetFeature()` returns a XML node which you could modify.

Okay, I suppose that's one way to do it. Not quite the same as supplying raw XML as a filter though, which would be a bit easier to reuse.

> But if you could provide a PR that adds support within ol3, that would be great.

Well yes, but to quote myself:
> I'm probably using the wrong methods, but I did not have much time to dive deep.

and:
> Anyone with more experience on the openlayers internals?

I really have no idea where to start at this point, and we're a bit short on time atm.

If you'd ask me, there is only one way to do this, and that would be the right way: diving into the OL and OGC documentation head first and build the filter according to both specs. It doesn't feel right to create a half-baked solution which would work for our case, but be incomplete and maybe even incompatible with other (valid) uses of the `<DWithin/>` stuff.

**Comment by tsauerwein** [comment]
I would recommend you to take a look at how the bbox filter is implemented. You would need to do the following:

* Add a class `ol.format.ogc.filter.Dwithin` (similar to [ol.format.ogc.filter.Bbox](https://github.com/openlayers/ol3/blob/e289bfb/src/ol/format/ogc/filter.js#L356)).
* Add a convenience function `ol.format.ogc.filter.dwithin` (similar to [ol.format.ogc.filter.bbox](https://github.com/openlayers/ol3/blob/e289bfb/src/ol/format/ogc/filter.js#L73))
* Implement a function `ol.format.WFS.writeDwithinFilter_` (similar to [ol.format.WFS.writeBboxFilter_](https://github.com/openlayers/ol3/blob/e289bfb/src/ol/format/wfsformat.js#L572))
* Register your function in [ol.format.WFS.GETFEATURE_SERIALIZERS_](https://github.com/openlayers/ol3/blob/e289bfb/src/ol/format/wfsformat.js#L728) (similar as for [BBOX](https://github.com/openlayers/ol3/blob/e289bfb/src/ol/format/wfsformat.js#L736))
* And then please also add a test (similar to [this one](https://github.com/openlayers/ol3/blob/7080c50/test/spec/ol/format/wfsformat.test.js#L471)).

**Comment by bartvanandel** [comment]
Sounds like a plan. I'll see what I can come up with, if time allows for it. Thanks for the info!

**Comment by cpsTinK** [comment]
You have happened?

**Comment by bartvanandel** [comment]
@cpsTinK Time still hasn't allowed for it, I'm sorry.
