### ISSUE TITLE
Overlay not correctly positioned

### ISSUE THREAD

**Issue by pgiraud** [openlayers/openlayers#5459]
In the following example, I first add an overlay to the map (green icon). After a click on this icon, I create a new overlay that I add to the map. The second overlay doesn't take its positioning configuration into account correctly. In order to have the correct positioning I need to either click on the map after the overlay is added or call `map.renderSync` in the javascript.

http://run.plnkr.co/9CzGlBUACCrL6UDe/
http://plnkr.co/edit/3R8yGo186e3JLnAocTRs

**Comment by kolosov-sergey** [comment]
Ran into the same problem. After adding overlay on the map it's positioned in 'top-left', though I provided 'center-center' in the params. After any click on the map overlay jumps to its expected position.

See the demo https://jsfiddle.net/996d97gy/1/

**Comment by nagytech** [comment]
My PR resolves your issue.  Please try it out.

**Comment by fredj** [comment]
should be fixed with #6567

**Comment by b310L** [comment]
replace direction:'ltr' instead direction:'rtl'
