### ISSUE TITLE
SVG for background crops and zooms incorrectly

### ISSUE THREAD

**Issue by adz** [openlayers/openlayers#5467]
I have modified the static image example, http://openlayers.org/en/latest/examples/static-image.html by changing the image url on line 16 to this https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg.

Here's a jsfiddle (zoom out a few times to see the issue):
http://jsfiddle.net/modunLr4/

This was working in my project, but started doing this behaviour since using the latest chrome stable (51). In firefox, no image appears at all.

In contrast, using a PNG works correctly.

**Comment by ahocevar** [comment]
This is a known issue in Chrome and Firefox, unrelated to OpenLayers. The workaround is to give the `<svg>` element of the image file a width and height, e.g.
```xml
<svg id="svg2" xmlns="http://www.w3.org/2000/svg" width="900" height="900" viewBox="0 0 900 900" version="1.1">
```
for the file you linked above.

**Comment by adz** [comment]
Thanks @ahocevar ! It's odd that it only started on Chrome upgrade to 51.

I am using images from a third party, and the <svg> tags contain viewBox, x and y -- but not width and height. The example I used had none of these, sorry.

When I inspect the image it appears to be 150x150 px, but I have viewBox="0 0 5500 5500". I guess chrome is interpreting the ratio, but perhaps we're projecting into 5500x5500?

If I download an SVG and manually add in width/height, then everything looks ok. 
However, I likely won't be able to do this easily....

I'm wondering why the viewbox isn't enough?

**Comment by bmrainc** [comment]
@adz how to set the svg tag?Can you show me a example?I donot know how to do!

**Comment by adz** [comment]
@bmrainc the svg is plain text, actually, xml. You can just edit in a text file. The top tag being <svg... /> where the "..." is its attributes can have width and height attributes added. Read more here https://developer.mozilla.org/en-US/docs/Web/SVG especially the attributes reference.
