### ISSUE TITLE
Add support for WMS Capabilities 1.1.0 and 1.1.1

### ISSUE THREAD

**Issue by tchandelle** [openlayers/openlayers#5476]
The method `ol.format.WMSCapabilities.prototype.read` is not returning : 
- `<SRS>` tags and attributes (from `<BoundingBox>` tag)
- `<VendorSpecificCapabilities>`.
- `<UserDefinedSymbolization>`

**Comment by Manjulajntuk** [comment]
i want to pass external wms url and layer name to overlay on my base map can you provide the code with example. From user interface  we have to take or wms url and layer name like in the example where i have seen http://bhuvan.nrsc.gov.in/map/bhuvan/bhuvan2d.php# in that tools tab add layer --> wms layer in that they are taking only wms url and layer name like  want i am expected but i didnt understand how they are able to do can you provide sample code for that i so i can do.

**Comment by jbelien** [comment]
Any chance OL could read WMS 1.1 `<BoundingBox>` element ?
It uses `SRS` instead of `CRS` !

```xml
<BoundingBox SRS="EPSG:900913" minx="282751.506615" miny="6361844.97915" maxx="712444.741077" maxy="6710219.08322" />
```

Thanks 🎉

**Comment by jbelien** [comment]
If I'm not mistaken, here is the line that should be "improved": https://github.com/openlayers/openlayers/blob/master/src/ol/format/WMSCapabilities.js#L317

**Comment by jbelien** [comment]
@ahocevar Is it worth submitting a PR to allow correct read of WMS 1.1 `<BoundingBox>` element ?

**Comment by ahocevar** [comment]
@bartvde, what do you think?

**Comment by bartvde** [comment]
I think we had this discussion before (#2944), back then I was in favour only if we could truly version the WMS format (and not conflate WMS 1.3.0 with some exceptions for WMS 1.1.x).

**Comment by bartvde** [comment]
but I probably don't feel so strong about this anymore ;-)

**Comment by jbelien** [comment]
About the `<BoundingBox>` element, the only modification would be related to this : https://github.com/openlayers/openlayers/blob/master/src/ol/format/WMSCapabilities.js#L317

Can I base a new PR on #2944 ?

**Comment by bartvde** [comment]
sure, reviving #2944 would be a good option @jbelien
