### ISSUE TITLE
Events not stopped when using IE10

### ISSUE THREAD

**Issue by jlap** [openlayers/openlayers#5478]
I stumbled upon an issue using internet explorer 10 and openlayers 3.14

There seems to be a regression between ol 3.13 and 3.14 regarding event propagation in internet explorer 10.

The issues I have can be reproduced right in the openlayers examples, like these two:

http://openlayers.org/en/v3.14.0/examples/measure.html
http://openlayers.org/en/v3.14.0/examples/popup.html

In the popup example, in ie10, if you click on the popup, be it in the body or the "x" button, the event goes through and another popup will open up. A popup will also open every time you click the "+" or "-" button to zoom in or out.

The problem is also visible with the measure tool, you may start drawing a line by clicking the +, -, or the attribution buttons.

All of these issues are not occurring if you visit the[ 3.13 version](http://openlayers.org/en/v3.13.0/examples/popup.html) of the examples. The issue is still present with the [master](http://openlayers.org/en/master/examples/popup.html) hosted version of the examples.

**Comment by jlap** [comment]
I just noticed this seems to fit with the switch from using goog.events to ol.events, might be related.

**Comment by ahocevar** [comment]
Hm. Very unlikely. We use `event.stopPropagation()`, which is supposed to work in IE since version 9. And the closure event system used the same in this case. @jlap, any help you could provide to fix this would be much appreciated.

**Comment by jlap** [comment]
Spent some time git bisecting, the exact commit introducing the issue is: 3f2d79b7fe2ac40e3669e1cab9d0c168656d4485

**Comment by ahocevar** [comment]
Ok, so your guess was correct. And still, I cannot figure out why this change causes an issue in IE10 only. I verified that `src/ol/map.js` registers the `ol.events.Event.stopPropagation` function on mousedown (ol.events.EventType.MOUSEDOWN), that the listener is called when clicking inside an open popup, and that it calls evt.stopPropagation(). To my knowledge, the old code with `goog.events.*` did exactly the same.
