### ISSUE TITLE
Source XYZ limit pan

### ISSUE THREAD

**Issue by oufresh** [openlayers/openlayers#5481]
Hello,

I'm quite new of Openlayer, we're setting up a server with Tiles to be loaded with ol.Source.XYZ. Since we want to have a subset of all tiles (a restricted area) we would like the user not to pan the map far from the area of interest.

I searched on the internet but I didn't find an easy solution of this issue. Only somthing on Stackoverflow like this:

http://gis.stackexchange.com/questions/127011/how-can-i-dynamically-restrict-pan-extents-on-an-image-layer-in-openlayers-3

In case of different zoom we must, every time, calculate the new Extent. Right?

Will you introduce in a future release a feature like this? If not can you suggest me, if possible, a method to fix this problem?

Thanks a lot.

**Comment by max9599** [comment]
![image](https://cloud.githubusercontent.com/assets/9418189/24589646/c3244df2-17e6-11e7-896c-12e2539bf92a.png)

Same problem for me with latest OpenLayers. View 'extent' setting is not restricting user to drag over extent area, when zoom is too small. How can I solve this problem ? There are a lot of similar questions on StackOverFlow, but there are no good solution for it yet...

**Comment by Zuzon** [comment]
set view min/max resolution or zoom

**Comment by mimiqkz** [comment]
More than a year, why is there no solution to this?

**Comment by bartvde** [comment]
because no one provided a patch or funding?

**Comment by oufresh** [comment]
Please, can anyone tell us if there is a workaround or a possible solution to this problem?

**Comment by oufresh** [comment]
Any news of limiting pan in version 5?
If not we can close this issue...

**Comment by jahow** [comment]
There is a PR in progress to implement this in v6: #9137 
For v5 you'll have to stick to recomputing the extent at every zoom level.
