### ISSUE TITLE
Support editing circles

### ISSUE THREAD

**Issue by tst-ppenev** [openlayers/openlayers#5510]
Hi.

I saw that Open Layers 3 did not come with support for modifying circles in `ol.interaction.Modify`.  I have an implementation of that I can contribute, pending signing a Contributor License Agreement.

Please, let me know if you are accepting a pull-request for this issue.

Thanks,

---

Pavel

**Comment by ahocevar** [comment]
Pull request accepted. Thanks.

**Comment by bartvde** [comment]
@tst-ppenev any update on your pull request?

**Comment by tst-ppenev** [comment]
I'm still waiting for the developer agreement to be signed and transmitted.  My fork with the implementation of the feature is at <https://github.com/openlayers/ol3>.

**Comment by jkossis** [comment]
Any news on if this pull request will be accepted? This seems to be a well-desired feature.

**Comment by ahocevar** [comment]
@jkossis The pull request is accepted, but the question is whether the author will be able to contribute it - we are waiting for @tst-ppenev's organisation to submit the contributor's license agreement.

**Comment by rxnh8255** [comment]
@tst-ppenev Can I modify circles Now?please show me some code,thanks

**Comment by tst-ppenev** [comment]
Well, this is a new feature accessed through mouse interaction. There isn't any code you need to add to use it, just create some circles and add them to the collection of modifiable objects.

The pull request (https://github.com/openlayers/ol3/pull/5704) has not been merged, yet, so you'll have to do that yourself before building OpenLayers, or use my fork (which doesn't include other latest merges).

Here's a screencast of the <examples/draw-and-modify-features.html> from my fork.

[Draw-and-modify-circles.webm.zip](https://github.com/openlayers/ol3/files/459625/Draw-and-modify-circles.webm.zip)

Unfortunately, GitHub doesn't allow direct upload of <.webm>, so it's zipped.

**Comment by tst-ppenev** [comment]
Oh, and I did hear that licenses are cleared from my organization before I opened the pull request.

**Comment by rxnh8255** [comment]
thanks,can u send me a debug version of the ol.js,I could not build from your fork

**Comment by tst-ppenev** [comment]
@rxnh8255,

I presume you need this:
[ol-debug.js.zip](https://github.com/openlayers/ol3/files/459853/ol-debug.js.zip)

**Comment by rxnh8255** [comment]
Yes,I need this
Thank you veeeeeeeeeeeeeeeeeeery much!!!

**Comment by fredj** [comment]
fixed with #6457
