### ISSUE TITLE
`getLength` method for Circle, MultiLineString, LinearRing, Polygon, MultiPolygon

### ISSUE THREAD

**Issue by tchandelle** [openlayers/openlayers#5519]
`getLength` method was available in ol2 for every geometry type. In ol3, it's missing for :
- Circle ( = `2 * PI * r`) (and also getArea() = `PI * r^2`)
- MultiLineString ( = sum of length of LineString ?)
- LinearRing (`ol.geom.flat.length.linearRing` ?)
- Polygon ( = sum of length of LinearRing ?)
- MultiPolygon ( = sum of length of Polygon ?)

**Comment by bill-chadwick** [comment]
Take care with the getLength method on LineString if you are using Web Mercator (3857) or Lat / Lon (4326) coordinates as you won't get a distance in surface meters. This is because the computation is done in ol.geom.flat.length.lineString using Pythagoras on the projected plane.

If you want length answers in surface meters and surface area answers in square metres,  use ol.Sphere.prototype.haversineDistance and ol.Sphere.prototype.geodesicArea .

**Comment by bill-chadwick** [comment]
See https://github.com/openlayers/ol3/pull/4372

**Comment by tchandelle** [comment]
I'm using projected coordinate systems

**Comment by bill-chadwick** [comment]
What are you using the length and area results for?

**Comment by tchandelle** [comment]
The user can create new features with line string, polygon or circle geometry. The system needs to display length and/or area of created geometry.

It used to work with getLength and getArea methods from OL2.

**Comment by bill-chadwick** [comment]
If you are using standard web Mercator mapping (EPSG:3857) then look at

http://openlayers.org/en/latest/examples/measure.html?q=measure

Try with and without the geodesic check box. You will find the big square field widths come out at around 2.0km and 1.6km depending on your choice (double click to drop a label) . Clearly, the answers cant both be correct ! The geodesic one is the 'proper' answer, close to what you would measure if you were there. The non-geodesic one is the width of the field on a Web Mercator map of it printed at a scale of 1:1. 

With 3857, scale changes with the reciprocal of the cosine of latitude. Look at the scale bar example 

http://openlayers.org/en/latest/examples/scale-line.html

and see how its width changes as you move a map north/south

ol2 had getGeodesicLength(projection) functions on geometries which ol3 currently lacks.

I suspect your OL2 project may have been displaying wrong answers.

**Comment by tchandelle** [comment]
We work with EPSG:3949 (or similar). Our ol2 project works fine, I compared the result before (ol2 getLength) and after (`SELECT SDO_GEOM.SDO_LENGTH(geometry, 2, 'unit=m') ...`) the feature is saved in our database and I get the same result.

**Comment by bill-chadwick** [comment]
You will be OK with 3949 as that is a class of projection that has reasonably constant scale over its extent.
