### ISSUE TITLE
disabling default control event

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#5525]
Hi, I'm trying to disable all the event on the map.
The one thing I found is removing all the interactions. but map is still moving by control actions.

is there a way to disable event on default controls? 
without hiding control buttons

**Comment by tsauerwein** [comment]
You can also instantiate the map without controls or only with the controls you need:

```
var map = new ol.Map({controls: []}); 
// or
var map = new ol.Map({controls: ol.control.defaults({zoom: false, rotate: false})}); 
```
See: http://openlayers.org/en/latest/apidoc/ol.control.html#defaults and http://openlayers.org/en/latest/apidoc/ol.Map.html

**Comment by cs09g** [comment]
Yes, but with the control icons, I couldn't disable the events.

**Comment by bartvde** [comment]
can you explain why you want the visuals, but not the event handling? What is your use case?

**Comment by cs09g** [comment]
I'm making a function that can disable all the events. but if there's controls then I still can able to use the event by the controls then it doesn't mean disable all the events. however, if I remove the controls when the function's called, it's like having two functionalities(disable events, hiding controls).

**Comment by tsauerwein** [comment]
I am not sure I understand, but regarding the UX it might be confusing for your users if they see the zoom controls and can click them, but nothing happens.

**Comment by cs09g** [comment]
I agree with you. I feel that is right. but I think interactions and controls working should be synchronized. because to disable zoom functionality, we should remove the control and disable the interactions.
