### ISSUE TITLE
Zoom Sliders can't drag by touch

### ISSUE THREAD

**Issue by ChouGary** [openlayers/openlayers#5526]
open 
http://openlayers.org/en/latest/examples/zoomslider.html?q=slider
Zoom Sliders can't drag by touch
￼and test by Chome developer tools has same problem
![image](https://cloud.githubusercontent.com/assets/8294943/16403316/738e9afe-3d26-11e6-812c-9c292a781dc1.png)

test v3.16.0 or v3.14.0 Zoom Sliders can't drag by touch,
test v3.13.0 ok 
http://openlayers.org/en/v3.13.0/examples/zoomslider.html?q=slider

**Comment by cs09g** [comment]
can't touch drag map as well.

**Comment by gpcboekema** [comment]
We encounter the same problem for touch.

After some investigation:
The ol.control.ZoomSlider.prototype.handleDraggerDrag_ is subsequently fired by mouse, touch and pointer events (at least in chrome). Touch events have the clientX and clientY in the touches and changedTouches properties of the event object, while mouse and pointer have them available in the event object.

If no clientX and clientY is available it causes a crash.

`Assertion failed: calculated resolution outside allowed bounds (%s <= %s <= %s) 0.02625 NaN 3440.64`
`Assertion failed: calculated value (%s) ouside allowed range (0-1) NaN `

![image](https://cloud.githubusercontent.com/assets/1437671/22461812/1f8211b8-e7ab-11e6-815c-bfd75ae784b1.png)

When not using touch events (by commenting out the draglistener for touchmove and touchend) it works (in Chrome).

Tested in:
Chrome version 56.0.2924.76 beta (64-bit)
FF version 51.0.1 (32-bit)  (no support for pointerevents and touchevents)
Edge version 38.14393.0.0 works fine.

Tested with: [http://openlayers.org/en/latest/examples/zoomslider.html?q=slider&mode=raw](url)

**Comment by bartvanandel** [comment]
Is this fix also part of the current 4.0.1 version? I'm still experiencing the issue in FireFox 51.0.1 (32-bit). Both mouse drag and pointer drag don't work.

**Comment by bartvde** [comment]
#6422 is part of the 4.0.0 release so yes

**Comment by bartvanandel** [comment]
By the way, we are using pep.js polyfill which may be interfering here I suppose. Let's see if I can find out.
