### ISSUE TITLE
Not stopping pending tile requests

### ISSUE THREAD

**Issue by ardean80** [openlayers/openlayers#5532]
I'm using ol.layer.Tile with ol.source.XYZ to load tiles from a specific tile server. 
Panning and zooming the map I noticed that the old pending tile requests (for example, the ones made to load a previous zoom level) are not automatically aborted, they keep going until they get a response.

**Comment by ahocevar** [comment]
This is correct, and there is currently no easy way to change this. The reason why we didn't consider this case was because there is no good way to abort a pending requests for an Image element's `src`. You would have to load all images using `fetch` or `XMLHttpRequest`.

Do you have an application or example where the current behaviour is problematic? As long as you have not set `loadTilesWhileAnimating` and `loadTilesWhileInteracting` to `true` on the map, there should not really be many useless tile requests.

**Comment by ardean80** [comment]
When a user quickly (but not continuously, so that loadTilesWhileAnimating and loadTilesWhileInteracting wound not have effect) switch from a zoom level to another one, keeping alive old requests could slow down some (already slow) tile servers. I know that some important work should be done to improve server performances, but may also be useful to limit useless requests from the client.

**Comment by ahocevar** [comment]
We'd very gladly accept pull requests to improve this, if someone has an idea for a fix that does not complicate the code too much.

**Comment by fredj** [comment]
According to http://stackoverflow.com/a/5278475, setting `src` to an empty string abort the request

**Comment by ahocevar** [comment]
Actually that is not correct. Setting `src`to an empty string means to set `window.location.href` as `src`:
```
> var img = document.createElement('IMG');
< undefined
> img.src=""
< "" = $1
> img.src
< "http://stackoverflow.com/questions/5278304/how-to-cancel-an-image-from-loading/5278475" = $2
```

**Comment by tsauerwein** [comment]
> Actually that is not correct. Setting `src` to an empty string means to set window.location.href as src:

But there will be no new request made to `window.location.href`! This seemed to be the case, but no longer:  https://www.nczonline.net/blog/2009/11/30/empty-image-src-can-destroy-your-site/

**Comment by fredj** [comment]
I've tried with:
```
var img = document.createElement("IMG");
img.src = "http://imgsrc.hubblesite.org/hu/db/images/hs-2015-02-a-hires_jpg.jpg";
// wait
img.src = "";
```
(source https://jsfiddle.net/nw34gLgt/)
And the image loading was stopped (but yes, `img.src` was wrong after that (equal to `window.location.href`))

**Comment by ahocevar** [comment]
In which way was image loading stopped? Did the server receive a HTTP abort?

**Comment by ahocevar** [comment]
@tsauerwein:

> But there will be no new request made to window.location.href!

And are you sure that this wasn't just because the site that you tried with had cache headers set to tell the browser not to re-fetch?

**Comment by tsauerwein** [comment]
> And are you sure that this wasn't just because the site that you tried with had cache headers set to tell the browser not to re-fetch?

In that case you would see a new request in the dev tools, which is not the case. Here are the (resolved) issues for Webkit and Firefox: https://bugs.webkit.org/show_bug.cgi?id=30303 https://bugzilla.mozilla.org/show_bug.cgi?id=531327

**Comment by fredj** [comment]
> In which way was image loading stopped? Did the server receive a HTTP abort?

no HTTP abort, the loading simply stopped (in the Network tab), after this the HTTP code was 200 (which is highly suspicious ...)

**Comment by ahocevar** [comment]
Question is whether these deviations from the standard are here to stay. If you read the ticket comments there, not everyone was happy.

That aside, what changes would be needed to get to a point where we could abort image loading on the side of our library? We can always set the src to a blank image instead if needed. But I think there will be more work to do before we even get to that point. There is at least one other unresolved issue with the tile queue (#5053), which might be related.

**Comment by ahocevar** [comment]
#5795 might contain some of the code needed to fix our tile loading behaviour.

**Comment by tschaub** [comment]
Totally untested, but #5816 proposes a `tile.abort()` method.
