### ISSUE TITLE
Unexpected rendering for Raster layer

### ISSUE THREAD

**Issue by thhomas** [openlayers/openlayers#5537]
When using a Raster layer, the zooming/panning is not rendered well. Some intermediate tiles are displayed before expected ones.
It can be experienced in [color manipulation example](http://openlayers.org/en/latest/examples/color-manipulation.html?q=raster).

@jan-tosovsky-cz experienced it too in his [comment](https://github.com/openlayers/ol3/issues/5396#issuecomment-221995596)

**Comment by thhomas** [comment]
![ol3-raster](https://cloud.githubusercontent.com/assets/5190928/18582702/b8330b1c-7c06-11e6-955b-161496b716e6.gif)

**Comment by fredj** [comment]
fixed with #6564
