### ISSUE TITLE
curve line geometry

### ISSUE THREAD

**Issue by itayod** [openlayers/openlayers#5582]
Hi,
I am building an indoor navigation application and I want the line string geometry corners be curved (by given radius).
I have searched for a build in solution all over the project and the internet and after I did not find one I have created new geometry "curve line".
can I send  a pull request of this new geometry?
Thanks.

**Comment by ahocevar** [comment]
Yes, please submit a pull request. Since this sounds like a complex change, please don't be upset if there'll be a review process that requires you to make changes to your solution.

**Comment by ahocevar** [comment]
See #896.
