### ISSUE TITLE
Mapguide issue changing settings after Layer Created

### ISSUE THREAD

**Issue by flipper44** [openlayers/openlayers#5602]
item.getSource().get('displayDpi') will get Any and all key values,
but none of the key values are able to be set item.getSource().set('displayDpi', 300).

I am trying to do some Higher Quality Printing with higher DPIS, also its nice to be able to set this post fact for different devices.

I tried a few others like hidpi, metersperunit etc and can't change them after the layer is created either.,

**Comment by ahocevar** [comment]
Your issue description sounds very cryptic to me. Can you please provide more context, code snippets etc.?

**Comment by flipper44** [comment]
You can't change any settings that aren't params on mapguide layers after
the layer source is created, such as displaydpi, clip, etc. They are all
assumedly not available to changinging...if you look at the mapguide image
API nothing can be changed on the layer source besides params.

**Comment by ahocevar** [comment]
Do you want to provide an improvement pull request?

**Comment by flipper44** [comment]
Not sure how to do that, will have to wait til Monday.

**Comment by ChouGary** [comment]
you can use item.getSource().updateParams({'SETDISPLAYDPI': 300})
but img width height will follow ol.Map#pixelRatio, 
and there is no set pixelRatio method after map Created,
and no  set hidpi in  ol.source.ImageMapGuide after layer created

http://openlayers.org/en/master/apidoc/ol.source.ImageMapGuide.html#updateParams
https://trac.osgeo.org/mapguide/wiki/HttpApi/RenderingService#SetDisplayDpi1.0
