### ISSUE TITLE
Modular handling of proj4js

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers#5628]
As part of the conversion to modules, I would like to import proj4js in a standard way as a module instead of creating a global. There is currently the `setProj4` function, but this is not really standards-compliant. To support both those who want to use Proj4 and those who don't, I think you would have to have 2 separate classes, one of which imports Proj4 and another which doesn't, but I'm not sure how you would implement that without changing the API.

So what I've done is disable proj4js in OL, and implement the functionality in my app. Code like the following supports the most common case of transforming in/out of 4326, assuming `ol` and `proj4` are imported:

``` javascript
function addProjection(projCode, projDef) {
  // add the projection to Proj4 defs
  proj4.defs(projCode, projDef);
  // add the projection object to ol.proj
  ol.proj.addProjection(new ol.proj.Projection({
    code: projCode,
    units: 'm' // could be taken from proj4.defs
  }));
  // get transform functions from Proj4 ...
  var proj4Transform = proj4('EPSG:4326', projCode);
  // ... and add to ol.proj
  ol.proj.addCoordinateTransforms('EPSG:4326', projCode,
      proj4Transform.forward, proj4Transform.inverse);
}
```

This is similar to what is done in `examples/wms-custom-proj.js`. However, the current `ol.proj` code supports transforms in/out of all the added projections `ol.proj.projections_`. ATM this can't be done in the app, because no function to get the list of current projections exists. For the moment, I am maintaining my own duplicate list, but it would be better to add this export.

Any comments, or other/better ways of doing this?

**Comment by ahocevar** [comment]
We could expose a function that does what's currently done as last step in the `ol.proj.Projection` constructor:
```js
ol.proj.registerProjection('myProjCode',
    function(otherProjCode) {
      return proj4(myProjCode, otherProjCode).forward;
    },
    function(otherProjCode) {
      return proj4(myProjCode, otherProjCode).inverse;
    });

**Comment by probins** [comment]
So you mean the developer would supply functions referring to the local `proj4` function to `registerProjection`?

here's my amended function to transform into/out of all existing projections:
``` javascript
var projections = ['EPSG:4326', 'EPSG:3857'];
function addProjection(projCode, projDef) {
  if (projections.indexOf(projCode) === -1) {
    // add the projection to Proj4 defs
    proj4.defs(projCode, projDef);
    // add the projection object to ol.proj
    ol.proj.addProjection(new ol.proj.Projection({
      code: projCode,
      units: 'm' // could be taken from proj4.defs
    }));
    projections.forEach(function(code) {
      // get transform functions from Proj4
      var proj4Transform = proj4(code, projCode);
      // ... and add to ol.proj
      ol.proj.addCoordinateTransforms(code, projCode,
          proj4Transform.forward, proj4Transform.inverse);
    });
    projections.push(projCode);
  }
}
```
This is simple enough, so there's no real need to expose `ol.proj.projections_`.

There is another issue here, which is that `proj4js` includes transforms for 3857 so there's no need for OL's version of this if you're using `proj4js`. In fact, if you're not using 3857 there's no need for this conversion at all. So this should be optional, a dependency of having a layer in 3857 and not using `proj4js`, not `require`d in all maps as at present.

Another minor point is that fetching the def from epsg.io, as in `examples/wms-image-custom-proj.html`, depends on there being a `proj4` global with the callback function - `setProj4()` won't help here.

**Comment by probins** [comment]
having a `registerProjection` function like this would simplify moving the handling of proj4js into apps. Apps would define where the proj4js module would come from. If this became the recommended way of using proj4js, and the examples changed to use it, then the current proj4js handling could be deprecated/removed and the `ENABLE_PROJ4JS` flag would no longer be needed.

**Comment by probins** [comment]
@ahocevar I'm thinking `registerProjection` could be extended to include the proj4js def as an optional param. It could then execute `addProjection`, passing `axis`/`to_meter`/`units` to the `Projection` constructor if this param were present, and the proj4js handling there would no longer be needed. This object could handle both the proj4js names (`axis`) and the OL names (`axisOrientation`), so someone wanting to register a non-proj4js projection could pass an `ol.Projection` option object as a `def` param, though creating a proj4-style function for the forward/inverse functions might be a bit too complicated for most people/use cases.

This could be further simplified if `proj4js.defs()` were changed to return the added def (looks like it doesn't do this atm). Then apps could do `var def = proj4.defs(code, def); registerProjection(... def);` or even `registerProjection(... proj4.defs(code, def));`. Also, it looks like `proj4js.defs` does accept the def object, so I'm thinking of changing my apps to use that - more JS-friendly than the string literal def, which is basically a legacy from Proj.

**Comment by probins** [comment]
and continuing on this line of thought: 4326 and 3857 could be added in the same way and the current (non-api) classes removed. These aren't really classes anyway, as you don't need >1 of them, and I think it would be better if all projections were handled in the same way, regardless of where the definition and transform functions are coming from.

**Comment by probins** [comment]
These changes don't have to be implemented at the same time, so I propose splitting this into separate PRs:
- [x] change code so define flag is only referenced if projection/transform not in `projections`/`transforms` #6933. This means define flag will be ignored if apps ensure projections/transforms are added before use
- [ ] add new proj4 def option to `proj.Projection` constructor; if this is present, use that, and there's no need to access proj4 global. This means `proj4.defs()` can be run in apps not in OL
- [ ] add new `proj.registerProjection` function as discussed with reference to proj4 object for forward/inverse functions, and optional proj4 def. If def present, create Projection object and call `addProjection`; call `addCoordinateTransforms` for all `proj.projections`. This means that OL no longer needs to reference the proj4 object directly, but can use the reference provided by the app
- [ ] for this to work, apps need to have a list of which projections have already been added; they could keep their own list as in my example, but as OL is already keeping such a list in `proj.projections` it would probably be better/simpler to have a simple lookup, either by exposing `projections.get` or by adding an optional check param to `proj.get`: if this param is true, return the projection/null without attempting to create it
- [ ] document this as preferred way of using proj4js transforms, and change/create examples; deprecate existing way; existing code will still be 'required' but it's only a small amount of code

Then, at some later stage, a breaking change: set define flag to false by default and warn people code will be removed in a later version. Or alternatively, include warning in step 5 above, and remove code and define flag in next breaking release.

The other objective - making 4326/3857 optional, not 'required' - is related to proj4js, but is not part of the changes to proj4js handling, so I'll create a separate issue for that.
