### ISSUE TITLE
ol.format.WFS#writeGetFeature for WFS 1.0.0

### ISSUE THREAD

**Issue by drnextgis** [openlayers/openlayers#5633]
I want to make request to WFS 1.0.0 server, but it looks like now I can't generate WFS GetFeature POST request body? [Here](https://github.com/openlayers/ol3/blob/a575749793554034d02f5d06ddbdccec5a667e27/src/ol/format/wfsformat.js#L781) I see that 1.1.0 version is hardcoded and gmlFormat option (ol.format.GML2 for WFS 1.0.0) is not taken into account.

**Comment by bartvde** [comment]
PR welcome @drnextgis
