### ISSUE TITLE
Icon Example: changes made with bootstrap v4

### ISSUE THREAD

**Issue by levu42** [openlayers/openlayers#5659]
In Bootstrap v4 (currently alpha) there will be some changes that aren't backwards compatible. One of them is the change from `.popover('destroy')` to `.popover('dispose')`. The `destroy` version is at least used in the icon example, which therefore doesn't work with the up-and-coming bootstrap version.

**Comment by ischas** [comment]
Since v4 is still in alpha (and will stay in that state for a long time) I do not see any necessity to change anything by now.

**Comment by wnordmann** [comment]
-- 
Typed with thumbs and sent with love from Boomerang
<http://boomerangandroid.com/?utm_source=b4a_signature&utm_medium=b4a_email_sig&utm_campaign=play_promote>

-----Original Message-----
[openlayers/ol3] Icon Example: changes made with bootstrap v4 (#5659)
