### ISSUE TITLE
GeoJson.readFeatures() not return an ol.Collection

### ISSUE THREAD

**Issue by AlvaroLQueiroz** [openlayers/openlayers#5661]
**readFeatures()** could have the possibility of return an **ol.Collection**. Because when features in **ol.interaction.Modify** is defined with **Array.<ol.Feature>** not work.

**Comment by tsauerwein** [comment]
I am not sure I correctly understand. Do you want to read features from a GeoJSON and set them on a modify interaction? [ol.Collection](http://openlayers.org/en/master/apidoc/ol.Collection.html) takes an array as constructor argument:
```
var features = new ol.format.GeoJSON().readFeatures(...);
var interaction = new ol.interaction.Modify({
  features: new ol.Collection(features)
});

```
