### ISSUE TITLE
One provide per file

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#5679]
If the library were organized so that there was one `goog.provide()` per file, and the name of the provide was mapped directly to the path, we could release with a CommonJS-friendly set of modules and still support the current builds.

For example, if `src/ol/foo/bar.js` included the following:

``` js
goog.provide('ol.foo.Bar');
goog.require('ol.bam');

ol.foo.Bar = function() {
  this.baz = ol.bam.baz();
};
```

We could write a transform (e.g. for use with [`jscodeshift`](https://github.com/facebook/jscodeshift)) that rewrote this to something like `package/foo/Bar.js`:

``` js
var $ol$foo$Bar = {};
var $ol$bam = require('../bam');

$ol$foo$Bar = function() {
  this.baz = $ol$bam.baz();
};

module.exports = $ol$foo$Bar;
```

And then we could publish the content in `package` to npm, so people could do this in their applications:

``` js
var Bar = require('ol/foo/Bar'); // assuming the package 'ol' was available, which it isn't
```

This would be a lot easier without the dependency on the Closure Library (see #4128).  With that gone, a valid question is "why would we still use `goog.provide()`?".  I'm not convinced we need to keep using it, but there are build tools and other things that need to change before we remove it.  My point here is that we could have a release that had _both_ CommonJS friendly artifacts (perhaps published as a separate package) and the existing sources/tools for custom builds (and the existing gargantuan full build).

**Comment by marcjansen** [comment]
Plus one for one provide per file.

**Comment by probins** [comment]
the conclusion from https://github.com/openlayers/ol3/issues/5226#issuecomment-216159657 was that putting enums in their own file would lead to circular dependencies

**Comment by probins** [comment]
what's the advantage of this proposal over using `goog.module`? If we're changing to standard modules, whether that's CJS or ES6, the bulk of the work is changing the scope: replacing the current global refs `ol.xxx` with imported vars. With this proposal, that would still need to be done at some point. With `goog.module` that would be done now but, once it's done, a transform from `var x = goog.require(x)` to `var x = require(x)` is a much simpler transform than what's proposed here.

**Comment by gberaudo** [comment]
There are several kinds of enums, see https://github.com/openlayers/ol3/issues/5226#issuecomment-215126637. It is hard to tell how many enums will be problematic.

**Comment by tschaub** [comment]
Here is a branch with a test that can get us started: https://github.com/openlayers/ol3/compare/one-provide

When `npm run test-node` (or `make test-node`) passes, we'll have one provide per file, with names like the path.

This means we would move things like `src/ol/color/color.js` to `src/ol/color/index.js` (assuming this has `goog.provide('ol.color')`).

I'll deal with enums as they come up.  We can have a single provide per file while still grouping enums with constructors.  We'll end up with things like this (in `src/ol/source/vector.js`):
```js
goog.provide('ol.source.Vector');  // no surprise, named like the file path

/**
 * Bla bla ...
 */
ol.source.Vector = function() {};

/**
 * @enum {string}
 */
ol.source.Vector.EventType = {
  // hey, not such a surprising name either

  // and with transpiled releases, people might do this:
  // var EventType = require('ol/source/Vector').EventType;

  // or in the glorious future:
  // import {EventType} from 'ol/source/Vector';

  // ...
};
```

**Comment by probins** [comment]
further to [my previous comment](https://github.com/openlayers/ol3/issues/5679#issuecomment-237486360), you could combine @tschaub's proposal with `goog.module`:
1. using a similar transform to that in the initial post, *convert* the current code to `goog.module`, transforming the vars using `$ol$foo$Bar` or similar convention, *and* passing over all the comments, i.e. including all the type and api info. This should retain compatibility with existing apps and builds, whilst converting the code into module format
2. a transform to convert that to CJS for use with existing module systems/loaders/tools should be simple
3. `$ol$foo$Bar`-style vars could then be converted to normal `var Bar` or whatever file by file without any external effect

Changing to one file per provide and renaming filenames to match provides/modules needs to be done anyway. As I noted in https://github.com/openlayers/ol3/issues/5226#issuecomment-223244650, renaming does not create as many merge conflicts as I thought, but I still think it would be a good idea to have a clear-out of existing PRs, and possibly a feature freeze, before starting on such fundamental changes.

**Comment by tschaub** [comment]
See #5693 for one step in this direction.  I've added the `test-node` script to that branch, so if that gets merged, others can use the same to guide follow-up work.

**Comment by tschaub** [comment]
Anybody else who wants to continue work on this can run `npm run test-node` to see where we need to rework provides.

The `make ci` target now runs `make test-node` - a subset of the tests in `test/node` that asserts that files are named like their first provide.  And "named like their first provide" means:

 * take the first `goog.provide()` in a file
 * split the arg on '.', transform to lowercase, and join by the path separator
 * if the file name is `index.js`, add `/index.js`, otherwise add `.js`
 * this should now be the relative path within our `src` directory

The remaining work is to remove all but the first `goog.provide()` from all files.

**Comment by ahocevar** [comment]
> var Bar = require('ol/foo/Bar'); // assuming the package 'ol' was available, which it isn't

It is now :smile:. Big props to @javascript for transferring the ol package to us. Thank you so much!

**Comment by ahocevar** [comment]
> var Bar = require('ol/foo/Bar'); // assuming the package 'ol' was available, which it isn't

It is now :smile:. Big props to @Javascript for transferring the `ol` package to us. Thank you so much!

**Comment by ahocevar** [comment]
> var Bar = require('ol/foo/Bar'); // assuming the package 'ol' was available, which it isn't

It is now :smile:. Big props to @Javascipt for transferring the `ol` package to us. Thank you so much!

**Comment by Javascipt** [comment]
@ahocevar, You're welcome, good luck with your project, keep it up!

**Comment by probins** [comment]
is this now complete?

**Comment by thomasgwatson** [comment]
I've just switched to using the 'ol' package and ES2015 module system.

Naively assumed that it would *reduce* my production bundle size (via webpack) however it has actually increased it by a couple of hundred kbs. We import ~20 ol objects, so perhaps simpler apps would see an actual reduction.

Am I really mistaken to believe it ought to reduce bundle size or does this just highlight how well optimized the Openlayer minified dist build is?

Not sure if this is the right thread to discuss this in
