### ISSUE TITLE
Add parsing of kml:NetworkLinkControl tag

### ISSUE THREAD

**Issue by oterral** [openlayers/openlayers#5705]
http://docs.opengeospatial.org/is/12-007r2/12-007r2.html#38

**Comment by davidoesch** [comment]
an ETA on this @fredj  ?

**Comment by boecklic** [comment]
ping @fredj : sth you consider implementing sometime or wont do?

**Comment by fredj** [comment]
@boecklic We're accepting pull requests if anyone wants to add the support for this tag.
