### ISSUE TITLE
Map crashes when clustering with a large amount of features

### ISSUE THREAD

**Issue by cmortazavi** [openlayers/openlayers#5742]
If you use the openlayers example for clustering 
http://openlayers.org/en/latest/examples/cluster.html

and you change the number of features to 200,000 then the map will crash once you zoom in too far.  This should be fixed since clustering will need to be used with large amounts of data.

**Comment by ChouGary** [comment]
hello ,i has same problem as you,the best solution is Supercluster.
https://github.com/mapbox/supercluster/
https://www.mapbox.com/blog/supercluster/

**Comment by cmortazavi** [comment]
This is a leaflet plugin?  Is there an openlayers solution?

**Comment by ahocevar** [comment]
Supercluster is not a Leaflet plugin. It can be used with OpenLayers, preferably an `ol.layer.VectorTile`. If anyone wants to create an official example, pull requests are welcome.

We could also improve `ol.source.Cluster` by not clustering the whole layer extent, but only the visible extent with a buffer. Clusters would have to be recreated when panning then. Also for this improvement, pull requests are welcome.

**Comment by ThomasG77** [comment]
I've created [a supercluster demo](https://webgeodatavore.github.io/supercluster/demo/index-ol.html) based on this thread  and the code is also available on [this Github repo](https://github.com/webgeodatavore/supercluster/commits/ol3-version).

If I submit a PR, adding some worker code (for perfs reasons) is ok although less ol3 related?

**Comment by ahocevar** [comment]
You mean a pull request to improve `ol.source.Cluster` performance by introducing workers? I was more thinking about a pull request adding a supercluster example, and getting rid of `ol.source.Cluster`.

**Comment by ahocevar** [comment]
But then again, removal of `ol.source.Cluster` may be too much. What did you really have in mind @ThomasG77?

**Comment by ThomasG77** [comment]
@ahocevar To push a supercluster demo. Didn't plan to touch `ol.source.Cluster` and no opinion on removing/keeping it.

**Comment by ahocevar** [comment]
Ok cool, please go ahead @ThomasG77. Keep it as simple as possible though.

**Comment by cmortazavi** [comment]
Is there any chance of getting a fix for the ol.source.Cluster.  I think the api itself should handle the worker rather than us having to handle it.  The worker makes it difficult for our application to work since we have many clustered layers which can be turned on and off at run time and our feature definition is dynamic.  Instead of a plugin, I think the original api should be fixed.  What is the problem with the ol.source.Cluster?  is it a memory leak?

**Comment by ChouGary** [comment]
hello , i make supercluster with 200000 sample.
woker is not required.
https://jsfiddle.net/d5gwvz2y/2/

var index = supercluster({
    radius: 40,
    maxZoom: 16
});
index.load(points);
index.getClusters([-180, -85, 180, 85], 2);

**Comment by cmortazavi** [comment]
So does this mean ol.source.Cluster won't be improved upon?  In my mind this is a bug and it should be fixed.  The supercluster is a good workaround but it won't work with what we are trying to do.  Why can't ol.source.Cluster get fixed?

**Comment by fjorgemota** [comment]
Hey.

I just want to share that I created a OpenLayers extension that works pretty much like `ol.source.Cluster`, but uses SuperCluster instead of the code used by `ol.source.Cluster`. The unique additional required option is the Map's View..the rest is pretty much the same as `ol.source.Cluster` with a few changes here and there to work with SuperCluster.

Here is the link to anyone interested: https://github.com/fjorgemota/ol-supercluster - The package is already available as `ol-supercluster` in npm, and it works well with `ol-ext`'s AnimatedCluster. :)

I hope this helps anyone. I may send a PR to this project if it's of interest of the developers.
