### ISSUE TITLE
Mouse over with transform scale

### ISSUE THREAD

**Issue by balkarov** [openlayers/openlayers#5747]
Hello

I need use transform scale for my page. But mouse navigation works not correct on the map. Look screenshot. And http://jsfiddle.net/balkarov/bfpep2uv/
How can I fix it?

![tooltip](https://cloud.githubusercontent.com/assets/6030335/17771434/9017bc30-654b-11e6-9541-748e2dbc3397.png)

**Comment by bill-chadwick** [comment]
It would be good to understand why you need the document level transform

<body style="transform: scale(1.5, 1.5) translate(106.667px, 3.88889px);">

  <div id="map" class="map"></div>

</body>

**Comment by balkarov** [comment]
We use transform scale in our project. It does not suit us zoom.

**Comment by balkarov** [comment]
Can somebody help me?

**Comment by ahocevar** [comment]
What do you mean by "it does not suit us zoom"? You can customize the appearance of all controls with css, and you have full control over the resolutions your map will displayed in.

**Comment by balkarov** [comment]
No. We need use this case, use transform scale. 
How to fix this problem?
Look, I found this problem the highcharts 
https://github.com/highcharts/highcharts/issues/2405

But someone did so to solve this problem
Before hack: http://jsfiddle.net/kzoon/v3aa8/
After hack: http://jsfiddle.net/f4z8pay9/

**Comment by balkarov** [comment]
Did you fix it in highcharts?
