### ISSUE TITLE
ol.style.Image classes should defer rendering to the layer renderer

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#5775]
Currently `ol.style.Image` subclasses render an image to an AtlasManager. Instead, layer renderers should decide what to do with the information stored in an Image style. For example in the case of `ol.style.Circle`, the Canvas renderer could more efficiently just render a circle with the provided radius, fill and stroke, instead of the style having to add an image to the AtlasManager for every radius-fill-stroke combination.

**Comment by ahocevar** [comment]
Also see #5748.

**Comment by tschaub** [comment]
Agreed.  It would be nice if the AtlasManager became a WebGL specific thing.

**Comment by ahocevar** [comment]
@wglas85, if you want to work on this, here is a brief outline of what I have in mind:

#### 1. Create a new `ol.style.Shape` class
A `ol.style.Shape` would be configured with a `ol.Size` and a `ol.geom.Geometry` (can also be a `ol.geom.GeometryCollection`. The geometry defines the shape in pixel space, bounded by a rectangle with extent `[0, 0, size[0], size[1]]`.

#### 2. Make `ol.style.RegularShape` inherit from `ol.style.Shape`
All rendering code can be removed, and the shape will be described as `ol.geom.Geometry` instead.

A related refactoring would be to merge `ol.style.Icon` and `ol.style.Image` into a single class.

#### 3. Update point renderers
This change mostly involves `ol.renderer.vector.renderPointGeometry_`,  `ol.render.canvas.Immediate.prototype.drawPoint` and `ol.render.canvas.Immediate.prototype.drawPoint` (and WebGL counterparts, if any). Now that `ol.style.Style#getImage()` can return an `ol.stlye.Icon` or an `ol.style.Shape`, we do not always get an already rendered image any more. These functions are now responsible for creating and caching images (and making an AtlasManger handle them for WebGL only) from the geometry and size defined in an `ol.style.Shape`.

With these changes in place, `ol.style.*` classes do not have any logic any more, and are just containers for properties. And AtlasManager will no longer be an implicit dependency of `ol.style.RegularShape`, reducing the size of builds that do not need a WebGL renderer.

**Comment by wglas85** [comment]
@ahocevar could you please tell me how to temporarily activate the immediate canvas renderer, so I can start by implementing this bare-bone render without having to tackle all the replay complexities?

**Comment by ahocevar** [comment]
You won't need to touch any code inside functions of the replay or immediate APIs. This change would be mostly about removing all rendering code from ol.style.RegularShape, and replacing it with ol.render.toContext calls in the functions I listed above (which are both higher level than the immediate and replay APIs.

**Comment by wglas85** [comment]
@ahocevar I have performed first steps on this issue, there need some topics to be discussed, I'm going to arrange a meetup...

**Comment by wglas85** [comment]
@ahocevar I made some more progress, we still have to decide on some topics, most notable the software layer at which we render the shapes to pixels, when needed and which scaling to apply...
