### ISSUE TITLE
getStyleFunction() for ol.layer.Image ?

### ISSUE THREAD

**Issue by michaelletzgus** [openlayers/openlayers#5825]
Hi all!

I'm using a map with a lot of different types of layer - including an ol.layer.Image for performance reasons. I prefer to style these layers with layers style function, not with per-feature styles.
Problem:
When looping over all layers the Image layer causes some problems because its interface is different from the "normal" layers.

Currently I'm using hacks like this:

``` javascript
ol.layer.Image.prototype.getStyleFunction = function() {
if (typeof this.getSource().getStyleFunction === "function") { 
        return this.getSource().getStyleFunction()
    } else {
        console.log('! This', this, 'image layer has no styled source!')
    }
}
```

The same problem occurs with getSource() - when hitting the image Layer getSource().getSource() is required.

Is there any better way to solve these problems? Or does an ol3 solution to this already exist?

Best regards
 Michael

**Comment by ahocevar** [comment]
In my opinion we should get rid of `ol.source.ImageVector`, and instead give `ol.layer.Vector` a `renderMode` property, like we have for `ol.layer.VectorTile`. That `renderMode` could be set to `image` to get what `ol.source.ImageVector` currently provides. Opinions?

**Comment by bartvde** [comment]
I agree that would be a simpler paradigm

**Comment by michaelletzgus** [comment]
Good idea! Same feature, cleaner interface.
