### ISSUE TITLE
Is it possible to add lineDashOffset  to the line style?

### ISSUE THREAD

**Issue by AnatolyAG** [openlayers/openlayers#5866]

**Comment by ahocevar** [comment]
It would be possible using the `CanvasRenderingContext2D`'s native `lineDashOffset` property for the canvas renderer, but it is currently not implemented in OpenLayers. We'd accept pull requests to implement it.

**Comment by AnatolyAG** [comment]
Yes, I know that there is a property in the context of 2d, but I set styles for the layer (them there are two or maybe three), and I can not set this property on a straight line.

**Comment by ahocevar** [comment]
@AnatolyAG would you be willing to provide a pull request that adds a `lineDashOffset` property to ´ol.style.Stroke`?

**Comment by marcjansen** [comment]
That would be great, @AnatolyAG. If you need any help with the PR, just tell us.

**Comment by AnatolyAG** [comment]
Yes, add this property is not bad in terms of compliance Context2d. Although this property is not particularly in demand. Therefore, it may immeet sense to write an expander that anyone should be able to add themselves to the code support.

**Comment by AnatolyAG** [comment]
I tried to extend the definition of this property, but faced with the problem of how to add it to the `Ol.` of your code, without making changes to the `Ol.`.

**Comment by AnatolyAG** [comment]
I added in my code

```
ol.style.Stroke.prototype.getLineDashOffset = function() {
  return this.lineDashOffset_;
}; 


```
```
ol.style.Stroke.prototype.setLineDashOffset = function(lineDashOffset) {
  this.lineDashOffset_ = lineDashOffset;
  this.checksum_ = undefined;
}; 
```

but then faced with the problem of how to add all this to the renderer.
I came to the conclusion that it is necessary to redefine the function
`ol.render.canvas.Immediate.prototype.setContextStrokeState_`
which is located  in immediate.js

```

/**
 * @param {ol.CanvasStrokeState} strokeState Stroke state.
 * @private
 */
ol.render.canvas.Immediate.prototype.setContextStrokeState_ = function(strokeState) {
  var context = this.context_;
  var contextStrokeState = this.contextStrokeState_;
  if (!contextStrokeState) {
    context.lineCap = strokeState.lineCap;
    if (ol.has.CANVAS_LINE_DASH) {
      context.setLineDash(strokeState.lineDash);
    }
    context.lineJoin = strokeState.lineJoin;
    context.lineWidth = strokeState.lineWidth;
    context.miterLimit = strokeState.miterLimit;
    context.strokeStyle = strokeState.strokeStyle;
    this.contextStrokeState_ = {
      lineCap: strokeState.lineCap,
      lineDash: strokeState.lineDash,
      lineJoin: strokeState.lineJoin,
      lineWidth: strokeState.lineWidth,
      miterLimit: strokeState.miterLimit,
      strokeStyle: strokeState.strokeStyle
    };
  } else {
    if (contextStrokeState.lineCap != strokeState.lineCap) {
      contextStrokeState.lineCap = context.lineCap = strokeState.lineCap;
    }
    if (ol.has.CANVAS_LINE_DASH) {
      if (!ol.array.equals(
          contextStrokeState.lineDash, strokeState.lineDash)) {
        context.setLineDash(contextStrokeState.lineDash = strokeState.lineDash);
      }
    }
    if (contextStrokeState.lineJoin != strokeState.lineJoin) {
      contextStrokeState.lineJoin = context.lineJoin = strokeState.lineJoin;
    }
    if (contextStrokeState.lineWidth != strokeState.lineWidth) {
      contextStrokeState.lineWidth = context.lineWidth = strokeState.lineWidth;
    }
    if (contextStrokeState.miterLimit != strokeState.miterLimit) {
      contextStrokeState.miterLimit = context.miterLimit =
          strokeState.miterLimit;
    }
    if (contextStrokeState.strokeStyle != strokeState.strokeStyle) {
      contextStrokeState.strokeStyle = context.strokeStyle =
          strokeState.strokeStyle;
    }
  }
};  
```

but I'm not sure what I'm doing right.

**Comment by ahocevar** [comment]
As a rule of thumb, you can search the code for `lineDash`. In both the immediate and replay APIs. At every occurrence, you add equivalent lines for `lineDashOffset`.

**Comment by AnatolyAG** [comment]
is if I add to the library, so I can not update the centralized `Ol`, and how to make your extension module, that would not break compatibility, rewrite your code in all the definitions that are found in the API?
