### ISSUE TITLE
ol.style.RegularShape#getPoints may return double amount of points given to the constructor

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#5875]
The method getPoints of ol.style.RegularShape returns double the amount of points given to the constructor if a radius2 was provided.

I think this follows the logic that the points given to the constructor are applied to each circle, thus resulting in the double amount.
But this means that the constructor option `points` and the points returned from getPoints are different from each other, which is not comprehensible by distinguished names or the documentation.

I can think of the following solutions:
1. Match the meanings by having to specify the total amount of points for both circles in the constructor.
2. Match the meanings by letting getPoints only return the number of points on one circle.
3. Distinguish the meanings by renaming the methods name to getTotalPoints or something similar.
4. Distinguish the meanings by documentation only.

I can create a PR for one of these solutions.

And btw i think it would be nicer to have this doubling of points in the constructor, where it can be found easily and not in both the methods draw_ and drawHitCanvas_

**Comment by Zyets** [comment]
There is also similar unobvious behaviour with radius2 option: if you don't pass it, than it will be set eaual to primary radius, so getRadius2 will return a number;

**Comment by ahocevar** [comment]
Pull request welcome, thanks in advance!
