### ISSUE TITLE
Support filtering using feature ids

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/openlayers#5877]
I'd like to work on supporting `ogc:FeatureId` in the `ol.format.ogc.filter` namespace.

The functionality would be equivalent to the OL2 implementation described at http://dev.openlayers.org/releases/OpenLayers-2.13.1/doc/apidocs/files/OpenLayers/Filter/FeatureId-js.html.

**Comment by tsauerwein** [comment]
Yes, that makes sense.

**Comment by tschaub** [comment]
FWIW, I think we should drop `ogc` from the `ol.format.ogc.filter` namespace.  We're not going to have other filter formats and we have other OGC things outside of `ol.format.ogc` (e.g. `ol.format.GML`).  I know this is unrelated to your proposal here, but if anybody is feeling like collapsing the namespace a bit, I'd be in favor.

**Comment by bartvde** [comment]
Makes sense to me, I think we came from ol.format.wfs.filter and I suggested changing to ogc back then since that is the OGC namespace, but dropping it altogether makes sense.

**Comment by madalinul** [comment]
Any news on this?

**Comment by bjornharrtell** [comment]
Sorry, no longer on my TODO list. :(
