### ISSUE TITLE
setUrls() on ol.source.WMTS causes Template URLs to change template placeholders

### ISSUE THREAD

**Issue by bylexus** [openlayers/openlayers#5881]
Hi,
A WMTS Source takes template URLs in the form `http://my-mapservice/1.0.0/{TileMatrix}/{TileRow}/{TileCol}` during constuction time:

```
var source = new ol.source.WMTS({
  /// .....
  urls: ['http://my-mapservice/1.0.0/{TileMatrix}/{TileRow}/{TileCol}']
});
```

During initialization, ol.source.WMTS uses the private `createFromWMTSTemplate()` function to parse and replace the URL template.

However, if you later re-set the URLs using the `setUrl` function, the wrong URL template function is set and you have to use `{x}`, `{y}`, `{z}` instead:

```
source.setUrls(['http://my-mapservice/1.0.0/{z}/{y}/{x}']);
```

It seems that this is caused during `setUrls` in `ol.source.UrlTile`, about here: https://github.com/openlayers/ol3/blob/v3.12.1/src/ol/source/urltilesource.js#L182

I think `setUrl()` needs to be overridden in ol.source.WMTS to fix this issue.

**Comment by marcjansen** [comment]
Somne questions:

* Is this behaviour still present in latest master?
* Can you create a minimal test currently failing?
* Are you able and willing to work on a solution, i.e. PR?

**Comment by bylexus** [comment]
* From my code investigations, I would say it is still the case, as setUrl() from UrlTile is used instead of the WMTS-own function.
* I try to create a test case and update this ticket accordingly.
* Not sure if I am able to, but I'll try my best :-)

**Comment by marcjansen** [comment]
Cool, looking forward to it!

**Comment by bylexus** [comment]
A working test case:
```javascript
// Using OpenLayers 3.18.2:
// ol.source.WMTS.setUrl() sets a wrong URL Template function, which causes
// created Tile URLs to be wrong after setting a new URL:
// @see Github Iussue here: https://github.com/openlayers/ol3/issues/5881

var olSrc = new ol.source.WMTS({
    projection: ol.proj.get('EPSG:3857'),
    requestEncoding: 'REST',
    urls: ['http://my-map-host/wmts/1.0.0/{TileMatrix}/{TileRow}/{TileCol}.jpeg'],
    tileGrid: new ol.tilegrid.WMTS({
        matrixIds: [0,1,2,3,4,5,6,7],
        origin: [2690000, 1285000],
        resolutions: [4000, 3750, 3500, 3250, 3000, 2750, 2500, 2250]
    })

});

// Default Case, after initialization: Tile URL is created correctly:
// Expected value for tileUrl1: http://my-map-host/wmts/1.0.0/2/8/9.jpeg
var tileUrl1 = olSrc.tileUrlFunction([2,9,-9],1,olSrc.getProjection());
console.log(tileUrl1); // output: "http://my-map-host/wmts/1.0.0/2/8/9.jpeg"

// Set new URL(s) with setUrls(), tileUrl now is wrong:
// Expected value for tileUrl2: http://my-map-host/wmts/1.0.0/2/8/9.jpeg
olSrc.setUrls(['http://my-map-host/wmts/1.0.0/{TileMatrix}/{TileRow}/{TileCol}.jpeg']);
var tileUrl2 = olSrc.tileUrlFunction([2,9,-9],1,olSrc.getProjection());
console.log(tileUrl2); // output: "http://my-map-host/wmts/1.0.0/{TileMatrix}/{TileRow}/{TileCol}.jpeg"

// Set new URL(s) with {x},{y},{z} instead works:
// Expected value for tileUrl3: http://my-map-host/wmts/1.0.0/2/8/9.jpeg
olSrc.setUrls(['http://my-map-host/wmts/1.0.0/{z}/{y}/{x}.jpeg']);
var tileUrl3 = olSrc.tileUrlFunction([2,9,-9],1,olSrc.getProjection());
console.log(tileUrl3); // output: "http://my-map-host/wmts/1.0.0/2/8/9.jpeg"
```

**Comment by bylexus** [comment]
Dear maintainers,
I already investigated some time into the problem and I *think* I have a feasible solution which may be merged. Should I open a new issue for a pull request, or may I refer to this issue in a PR?

**Comment by bartvde** [comment]
you can refer to this issue in a PR

**Comment by bylexus** [comment]
Dear all,
Just wanted to let you know that I created a pull request (https://github.com/openlayers/ol3/pull/5883) which fixes the problem. Hope this is a feasible solution, I'm glad to provide a saner solution if it doesn't fit into the code concept.
Thanks for consider merging.
