### ISSUE TITLE
Throttling tile (xhr) requests

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/openlayers#5912]
When tile map is zoomed over several levels and then moved, lot of tile requests are generated. While many of them become soon obsolete, they are kept in the queue (so downloaded). In case of larger tiles (ca 500 kB per tile) I am quickly experiencing freezing the browser, out of memory errors in the developer console, even crashes.

Would it be possible to throttle tile request in certain (even very short) interval? It would IMHO skip some, but still ensure those for final extent be requested
https://remysharp.com/2010/07/21/throttling-function-calls

It could improve overall performance even in case of common tiles (50 kB per tile).

**Comment by sunny-g** [comment]
Same as #5532.

**Comment by fredj** [comment]
See #6939
