### ISSUE TITLE
getResolutionForZoom

### ISSUE THREAD

**Issue by wayofthefuture** [openlayers/openlayers#5939]
We have some layers where we need to set the maxResolution based on zoom levels. Is there a way to get the resolution for a specified zoom level, or just get all the resolutions for the current map view? Currently if we use getResolutions() it will return undefined as we didn't pass resolutions in the constructor. We are using the default resolutions.

Is there a list of the default resolutions or a way to get a list of the ones currently being used in the view? Since the layer constructor options only take max/minResolution we are required to pass that into the constructor when creating the layer.

Thanks.

**Comment by ahocevar** [comment]
There is a way to get the resolution for a zoom level, but it's a bit awkward:
```js
var resolutionForZ10 = view.constrainResolution(view.getMaxResolution(), 10);
```
So I agree it makes sense to provide an API function to get the view resolution for a given zoom level.

**Comment by aalbericio** [comment]
I came accross this issue and fixed it with:

>> **view.constrainResolution(view.getMaxResolution(), (zoom - MAP_MIN_ZOOM), 0);**

Where **MAP_MIN_ZOOM** is the minimum zoom for the Map and **zoom** is the integer you want to calculate the resolution for.

I hope this helps!
