### ISSUE TITLE
Remove closure-util update from postintall scripts

### ISSUE THREAD

**Issue by cwmrowe** [openlayers/openlayers#5943]
It's a common trend these days to install packages for the front end via NPM, so this is how I have installed OpenLayers. 

However, unfortunately the OpenLayers package forces NPM to install closure with `closure-util update` as its in the `postinstall` scripts. 

Closure is not necessary for the front end use case and it can cause problems for people who are behind corporate proxies as reported here: https://github.com/openlayers/closure-util/issues/76

I'm looking forward to when #5623 is implemented as I'm sure it will resolve this issue, and also mean that I no longer have to package the whole OpenLayers source code in my application (yes, I am using `dist/ol.js`).

But in the mean time, is it acceptable to remove the `postinstall` script and ask developers to run `closure-util update` manually if they need to?

**Comment by probins** [comment]
see discussion in #3157. If you're just using the build in `dist/` then you don't need `install.js` either. `closure-util update` should be changed, as closure library no longer needs to be updated (see discussion at end of #4128). If this is just for your own use, it might be simpler to just create your own local package for the OpenLayers dist files and not use the NPM one.

**Comment by Status420** [comment]
But including the .js files manually defeats the point of using a package manger, the reason we'd like these installed via Node is to not have to keep the files locally and for easy updates.  What might be better is to have the .js files deployed via Bower instead.

**Comment by probins** [comment]
as an update to this, the Closure lib/compiler has not been updated in closure-util for several months now, so there is no real need for update to be run. However, I'm not sure that removing it from postinstall fixes the problem, does it? closure-util is a dependency of the ol package, so anyone installing that also has to install closure-util, and part of that install is downloading the latest lib/compiler, which will also run into the same proxy issues, right? ISTM the basic issue here is the same as #3157: the ol package is intended for those using the compiler to create custom builds, not for accessing the full builds which are available on cdn.

**Comment by gberaudo** [comment]
It is actually possible to compile with OL3 without using closure-util.
We do it in a pilot project, the goal would be there to only depend on the closure-compiler npm package. It would make sense to not call closure-util update in this case in order to prevent downloading the closure library and an extra compiler version.
I will give feedback on this setup as soon as it is tested enough.

**Comment by probins** [comment]
I think that only applies if you're compiling app code with OL, right? If you're not doing that and not providing the compiler with `goog.provide/require`, then you have to provide the compiler with a list of what you want exported. The current build script uses closure-util to do that. That could be changed, but as the longer-term plan is to change to ES6 modules anyway, I'm not sure it makes sense to spend much time on that atm.

**Comment by gberaudo** [comment]
It is fine to depend on closure-util and download it together with the other dependencies.
It is small and indeed needed to generate the full/custom builds exports (see tasks/generate-exports.js).
But there is no need to download the closure compiler and library for that (calling `closure-util update`).

**Comment by probins** [comment]
so having the compiler package as an ordinary `package.json` dependency does not cause the proxy problems caused by closure-util update? If so, I'd agree that would be a good solution.

**Comment by abhijitgujar86** [comment]
closure is indeed a very good util for fine level optimization. If someone needs the only js it very simple just download minified from /dist folder . why to change the development settings ? In fact every high end developer who want to optimize and save kb will be happy to see a function that loads only that class you need and not all of it. I am now making it compulsory for my team to use closure compiler.

**Comment by fredj** [comment]
closure-util was removed in #7570
