### ISSUE TITLE
Testsuite errors and oddities in IE 9

### ISSUE THREAD

**Issue by marcjansen** [openlayers/openlayers#6005]
When running the testsuite in IE 9 I observe the following
- Two `Error Access is denied` (known issue, already mentioned to be ignorable [here](https://github.com/openlayers/ol3/wiki/Release-Procedure#run-unit-tests))
- `Uncaught error outside test suite: Error: 'io' is undefined (http://my-host:3000/test/loader.js:21)`
- Another oddity is that the suite only produces reliable output if the developer console is open, otherwise lots of errors with regard to undefined `console` are logged.

I do not think these should block the next release. Other opinions?

Please respond to this within the next hours, so I can continue releasing (which turns out to be harder than expected)

**Comment by ahocevar** [comment]
Please proceed with the release, the IE9 errors you mentioned are more related to the test suite and our use of the global `console` in debug mode than to the library itself. So they can definitely be ignored.

**Comment by marcjansen** [comment]
Thanks for the feedback, Andreas.
