### ISSUE TITLE
custom build with override method

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#6006]
Hello,

I want to make custom build with override method. So I made my js which includes all override methods in. and pushed the file path to variable 'paths' in function 'getDependencies' in build.js file. 
But it doesn't work with my override method. It just worked with original method. 

How can I use my js without modifying original OL codes? 
override methods are based on the methods in ol-debug.js 

Thank you in advance.

**Comment by fredj** [comment]
closure-compiler is not used anymore, closing.
