### ISSUE TITLE
setStyle on a pre-rendered Vector feature with ol.layer.VectorTile

### ISSUE THREAD

**Issue by bencevans** [openlayers/openlayers#6026]
I'm puzzled as to why the following isn't rendering the new style and unable to find a function to redraw. Is there another way this should be done?

``` js
map.on('click', function (e) {
  var pixel = map.getEventPixel(e.originalEvent);
  map.forEachFeatureAtPixel(pixel, function (feature) {
    feature.setStyle(new ol.style.Style({
      stroke: new ol.style.Stroke({color: 'rgba(255,255,255,0.5)'}),
      fill: new ol.style.Fill({color: 'rgba(255,255,255,0.5)'})
    }));
  });
});
```

**Comment by ahocevar** [comment]
I created a fiddle with your code above, and it works fine. See https://jsfiddle.net/898qab9o/.

**Comment by bencevans** [comment]
Is there a reasons why this may not work using a VectorTile layer then? I'm using the following to build up the layer and if I put a console.log in the `forEachFeatureAtPixel` i'm getting the correct features but unable to change the style.

```js
var vectorLayer = new ol.layer.VectorTile({
  projection: 'EPSG:26717',
  source: new ol.source.VectorTile({
    projection: 'EPSG:26717',
    format: new ol.format.GeoJSON(),
    url: 'http://localhost:9001/mapper/comp/000/0/9999/{z}/{x}/{y}.geojson?epsg=26717&cache=false',
    tileGrid: ol.tilegrid.createXYZ({
      extent: extent,
      maxZoom: 19,
      minZoom: 15
    }),
    tilePixelRatio: 2
  }),
  style: new ol.style.Style({
    fill: new ol.style.Fill({
      color: 'rgba(255, 255, 255, 0.6)'
    }),
    stroke: new ol.style.Stroke({
      color: '#319FD3',
      width: 1
    }),
    text: new ol.style.Text({
      font: '12px Calibri,sans-serif',
      fill: new ol.style.Fill({
        color: '#000'
      }),
      stroke: new ol.style.Stroke({
        color: '#fff',
        width: 3
      })
    })
  })
});
map.addLayer(vectorLayer);

map.on('click', function (e) {
  var pixel = map.getEventPixel(e.originalEvent);
  map.forEachFeatureAtPixel(pixel, function (feature) {
    feature.setStyle(new ol.style.Style({
      stroke: new ol.style.Stroke({color: 'rgba(255,255,255,1)'}),
      fill: new ol.style.Fill({color: 'rgba(255,255,255,1)'})
    }));
  });
});
```

**Comment by ahocevar** [comment]
This is indeed a bug then.

In general, it is better to use layer styles instead of feature styles. What I do for highlighting is that I set an attribute on features I want to highlight, and handle the highlighting in the layer style function.

**Comment by bencevans** [comment]
Ah. I'm using OpenLayers 3.18.2 from npm.

I'm wondering if there's a hook missing to redraw the vectors from the ol.[layer/source].VectorTile as setting attributes and doing it using the layer style function isn't having an affect either, at least I think I've implemented it as you suggested.

```js

const featureStyle = new ol.style.Style({
  fill: new ol.style.Fill({color: 'rgba(255,0,0,1)'}),
  stroke: new ol.style.Stroke({color: 'rgba(0,0,0,0)', width: 0, lineJoin: 'square'}),
  zIndex: 1
});

const featureHoverStyle = new ol.style.Style({
  fill: new ol.style.Fill({color: 'rgba(255,255,255,0.2)'}),
  stroke: new ol.style.Stroke({color: 'rgba(255,255,255,0.2)', lineJoin: 'square'}),
  zIndex: 1
});

const featureSelectedStyle = new ol.style.Style({
  fill: new ol.style.Fill({color: 'rgba(255,255,255,0.4)'}),
  stroke: new ol.style.Stroke({color: 'rgba(255,255,255,0.4)', lineJoin: 'square'}),
  zIndex: 1
});

function featureStyler(feature) {
  if (feature.get('state') === 'selected') {
    return featureSelectedStyle;
  } else if (feature.get('state') === 'hover') {
    return featureHoverStyle;
  }
  return featureStyle;
}

var vectorLayer = new ol.layer.VectorTile({
  projection: 'EPSG:26717',
  source: new ol.source.VectorTile({
    projection: 'EPSG:26717',
    format: new ol.format.GeoJSON(),
    url: 'http://localhost:9001/mapper/comp/000/0/9999/{z}/{x}/{y}.geojson?epsg=26717&nocache=true',
    tileGrid: ol.tilegrid.createXYZ({
      extent: extent,
      maxZoom: 19,
      minZoom: 15
    })
  }),
  style: featureStyler
});
map.addLayer(vectorLayer);

map.on('pointermove', function (e) {
  var pixel = map.getEventPixel(e.originalEvent);
  map.forEachFeatureAtPixel(pixel, function (feature) {
    console.log(feature);
    feature.set('state', 'hover');
  });
});

map.on('click', function (e) {
  var pixel = map.getEventPixel(e.originalEvent);
  map.forEachFeatureAtPixel(pixel, function (feature) {
    feature.set('state', 'selected');
  });
});
```

**Comment by ahocevar** [comment]
That would explain the issue. Can you try with a different `forEachFeatureAtPixel` function to verify?
```js
  map.forEachFeatureAtPixel(pixel, function (feature) {
    feature.set('state', 'selected');
    vectorLayer.setStyle(featureStyler);
  });
```

**Comment by bencevans** [comment]
That is setting the styles! However it's applied to what I assume is the shape clipped to the tile rather than applying to the whole shape by id.

![ol-demo](https://cloud.githubusercontent.com/assets/638535/19692396/b31e5e1e-9acf-11e6-98f5-67125d938296.gif)

**Comment by ahocevar** [comment]
That's expected. When your features have an id set, you can mark your highlight features differently, i.e. by using an object literal with highlighted feature ids:
```
// in forEachFeatureAtPixel:
highlightedFids(feature.getId()) = true;

// in the style function
if (highlightedFids[feature.getId()]) {
  // use highlight style
} else {
  // use standard style
}
```

**Comment by bencevans** [comment]
@ahocevar do you have any tips on how to render point icons using VectorTiles? They're also getting clipped by the tile's boundary :'(

**Comment by ahocevar** [comment]
@bencevans Fix your vector tiles - they need a buffer to include geometries from neighboring tiles.

**Comment by Stezii** [comment]
I also tried to set the 'state' but it didn't work since my features are of type ol.render.Feature (read-only). My setup is nearly the same (ol.layer.VectorTile with ol.source.VectorTile), however I'm using ol.format.MVT and Ol v. 4.1.0. Can you tell me, why I'm just receiving the non-editable features?

**Comment by Questionboy** [comment]
I use ol.format.GeoJSON and OpenLayers 4.1.1, and want to change the style by click.
[the demo of geojson-vt](http://openlayers.org/en/latest/examples/geojson-vt.html). however, the style of selected feature isn't change.
