### ISSUE TITLE
Jump over zoomlevels on mousewheel zoom

### ISSUE THREAD

**Issue by samimussbach** [openlayers/openlayers#6032]
Is there any possibility to "jump over" zoomlevels that are within a mousewheel zooming event without triggering requests to the mapserver e.g. with some kind of time interval which the user has to spend on a zoomlevel before requesting the tiles? The tiles are not shown to the user anyway, so it is unnecessary load to the mapserver which in turn reduces the responsiveness for the user.

I made a custom build and played with `ol.MOUSEWHEELZOOM_TIMEOUT_DURATION` and `ol.MOUSEWHEELZOOM_MAXDELTA` but they both does not seem to solve my problem.

In OL2 we had `new OpenLayers.Control.Navigation({mouseWheelOptions: {interval: 100}})` which kind of tackled this problem. I am not aware of anything alike in OL3.
How could this be achieved in OL3?

**Comment by cs09g** [comment]
maybe similar with #5532

**Comment by ahocevar** [comment]
Related to #5532, but a separate issue. Currently tiles are added to the queue immediately. We have some tile queue/cache overhaul on the task list anyway, so I'll keep this issue in mind.

**Comment by samimussbach** [comment]
I am by no means familiar with the internals but shouldn't this specific case be relatively easily tackled by adding a config variable? 
It should be something like the time in ms between requesting the last zoom level and adding new request to the tile queue, so that the user can fine-tune the value for the specific use-case.

**Comment by bartvde** [comment]
@samimussbach do you mean something like #6036 ?

**Comment by samimussbach** [comment]
@bartvde I'm not so sure. Isn't #6036 "only" to make MOUSEWHEELZOOM_TIMEOUT_DURATION configurable within the Instantiation of the Interaction (which is great and I was looking forward to, thanks for that).
But as I understand it this directive defines the time before reacting to the mousewheel event and does not prevent the loading of the tiles.
I pulled the current master and built openlayers, but to be honest I could not see any effect of the new timeout variable. Therefore I'm quite sure to initialize it wrongly. This is my definition in ol.Map:

```
interactions: [
      new ol.interaction.MouseWheelZoom({
            timeout: 500
       })
 ],
```

I purposely killed any other interactions but it seems to have no effect whether i set it to 1 or 1000

**Comment by ahocevar** [comment]
> It should be something like the time in ms between requesting the last zoom level and adding new request to the tile queue, so that the user can fine-tune the value for the specific use-case.

This is not the interaction's job. The renderer requests tiles. If we add a setting now with the current tile queue in placer, it would have to be a map option.

**Comment by samimussbach** [comment]
@ahocevar I see. But this could basically be a map option, right? The initial rendering would be less performant as it waits for some ms before loading initially but it might be a good starting point to give the user the possibility to fine-tune this.
