### ISSUE TITLE
Dragging and dropping the GML layer in openlayers3

### ISSUE THREAD

**Issue by mfarook** [openlayers/openlayers#6043]
I am trying to add local GML files by drag and drop to map using openlayers3.The GML is not getting added up and results in

ol.js:87 Uncaught ka {message: "Assertion failed. See http://openlayers.org/en/v3.18.2/doc/errors/#25 for details.", code: 25, name: "AssertionError"}
When i look at the above link, the error code 25 is for Cannot fit empty extent provided as geometry. I am following the examples from https://openlayers.org/en/latest/examples/drag-and-drop.html and even added ol.format.GML in formatconstructors.

**Comment by bartvde** [comment]
Can you show us your GML file?

**Comment by mfarook** [comment]
[landuse.txt](https://github.com/openlayers/ol3/files/558417/landuse.txt)

**Comment by bartvde** [comment]
I'm guessing this needs to get parsed with ol.format.WFS instead

**Comment by mfarook** [comment]
Well, Even i had tried with that before. It did not work. It is raising the same error.
