### ISSUE TITLE
Openlayers 3 button styling (hover and focus)

### ISSUE THREAD

**Issue by bwyss** [openlayers/openlayers#6046]
In my humble opinion the styling for the ol button hover and focus is not correct.

The issue description: when you click to zoom, each click event on the zoom button makes the zoom button show the 'focus' styling (a blue border around the button). The focus should not persist after the click event IMHO.

I resolved this in my own code base by adding this css:

```
button:focus {
  outline: 0;
}

.ol-control {
    background-color: none;
    border-radius: 4px
}

.ol-control:hover {
    background-color: none;
}
.ol-control button:focus {
    text-decoration: none;
    background-color: #6A90B6;
}
```

Here is the normal behavior (of the zoom button css): http://jsfiddle.net/YoannBureau/f0z15rgj/
Here is a better behavior (again IMHO): http://jsfiddle.net/ydar2w65/

**Comment by ahocevar** [comment]
The behavior is browser specific, and what you are seeing comes from the last pressed button having the focus. And having visual feedback when a button has a focus is important for accessible maps.

I do agree that this behavior is strange though. A proper fix would be to `blur()` the button element after it is pressed. We'd accept a pull request for that.

**Comment by fredj** [comment]
#4364
