### ISSUE TITLE
Modify interaction "modifyend" event, doesn't return the modifyed feature

### ISSUE THREAD

**Issue by AviFix** [openlayers/openlayers#6048]
Hi,

The "modifyend" event on the "ol.interaction.Modify" returns the original feature instead of the modifyed one.

`this.modify.on('modifyend', (e: any) => {

```
    let features = e.features.getArray();
    for (let i = 0 ; i < features.length ; i++) {
         let rev = features[i].getRevision();
         if (rev > 1) {
             // Do somthing
            // console.log(features[i]);
           }
     }
  });`
```

Thanks
Avi

**Comment by ahocevar** [comment]
Can you provide some context, i.e. what you want to achieve?

**Comment by AviFix** [comment]
Hi,

I updated to the last version and it is ok
