### ISSUE TITLE
could it be possible to load irregular map tiles for custom tile grids

### ISSUE THREAD

**Issue by xwhsky** [openlayers/openlayers#6057]
W're researching irregular vector tile loading strategy to test whether vector density in each tile makes difference to whole map loading. However, we encountered difficulties  when rendering irregular  vector tiles using opnelayers, with WFS source loading function not quite fitting. Could it be possible to load irregular map tiles for custom tile grids, thanks a lot? @ahocevar 

Effect of expression as follows:
http://dimensionaledge.com/wp-content/uploads/2015/03/quadgrid.gif

**Comment by ahocevar** [comment]
This is currently not supported in OpenLayers.
