### ISSUE TITLE
Close rings when creating polygons

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#6063]
It would be straightforward for the polygon and multi-polygon constructors to close any open rings when creating polygons.  This would save trouble down the line with rendering.

**Comment by bjornharrtell** [comment]
Sounds good but I think it requires a bit of refactoring of the existing Draw interaction because it seems it actually depend on the sketch polygon not being closed. At least that's what I concluded when working on https://github.com/openlayers/ol3/pull/6027.

**Comment by cs09g** [comment]
Does that mean whatever it's created by coordinates or by drawing mode, it should be close ring for polygon?
