### ISSUE TITLE
Addition of ol.format.CQL

### ISSUE THREAD

**Issue by omarkljung** [openlayers/openlayers#6130]
I'd like to add CQL formatting similar to how it worked in OL2 with ol.format.filter.

Today we need to use both OL2 and OL3 for this dependency in an old application that relies heavily on CQL. OGC filter doesn't work due to big filters that exceeds browser URL max lenght, limitation to only GET-requests and gateways that does not allow HTML-chars.

Would that be an acceptable addition?

**Comment by bartvde** [comment]
Sure, makes sense to me at least.

**Comment by ahocevar** [comment]
@omarkljung Depending on your use case, it might make more sense to create a standalone CQL utility instead. Other than version 2, OpenLayers 3 does not have a filter API for filtering features in an ol.source.Vector.

That said, can you describe what you were planning to work on?

**Comment by omarkljung** [comment]
Yes, and since it doesn't we need to add that ourselves. We handle it as a standalone utility today only that it depends on OL2 instead of OL3 like the rest.

I intend to use the formatter to render a ol.format.filter to a CQL-string that will be used in the request parameter. Also, to read CQL that we get from config and parse it to a ol.format.filter to be used elsewhere.

We can keep the utility to ourselves if we do it. Just thought it might be interesting for others as well.
We can continue to use the OL2 formatters since we only handle the raw outputs, OGC Filter XML and CQL string.

**Comment by bjornharrtell** [comment]
I for one would be glad to see it added to `ol.format.filter`.

**Comment by omarkljung** [comment]
Would it be OK to move the OGC Filter serializers from ol.format.WFS somewhere else?

**Comment by bartvde** [comment]
@omarkljung can you elaborate on what exactly you would want to move? Most of the filter stuff is separate already AFAICT.

**Comment by omarkljung** [comment]
The serializer logic in `ol.format.WFS` that handles the OGC namespace. The OGC Filter is not exclusive to WFS AFIK so if it was separated it would be cleaner when using it elsewhere.

I'd like a separate formatter for just `ogc:Filter` that can both parse and serialize.
This would then be used when going from `ogc:Filter` XML to CQL an back again.
Or perhaps when constructing a `ol.format.SLD` in the future.

And another question, should a formatter for CQL be placed in the `ol.format` or `ol.format.filter` namespace?

**Comment by bartvde** [comment]
Okay sounds good, makes sense to me.
I'd personally put a CQL formatter in the ```ol.format``` namespace

**Comment by cpsTinK** [comment]
You have happened?

**Comment by onack** [comment]
This would be very usefull for taking a CQL_FILTER from a WMS layer to make a WFS request with. Its this issue dead?
