### ISSUE TITLE
Overview map keeps making requests

### ISSUE THREAD

**Issue by ArcelorGIS** [openlayers/openlayers#6157]
When I open the overview map control it keeps sending requests to the map server for some reason.
I've set it so it doesn't zoom in or out with the map, and it seems to stop the moment I've zoomed in a little bit. But when I zoom back out to my full view it just starts again.

Seems like a bit of overkill just for a little extra map in the bottom of my screen :)

**Comment by bartvde** [comment]
Please show us in a jsFiddle, I cannot reproduce this in our examples.

**Comment by ArcelorGIS** [comment]
I'm not able to reproduce it quickly outside our code either. I'll test some more and try to get back to you by monday!

**Comment by fredj** [comment]
see #8290
