### ISSUE TITLE
ol.source.Vector with spatial index and ol.Collection for features is broken

### ISSUE THREAD

**Issue by w3rt3r** [openlayers/openlayers#6183]
I got a simple map that request geojson features dynamically based on extent of the map from a WFS (geoserver). 

For some reason, I need to only load the features on the extent. So after map pan (map.on('moveend')) I clear a ol.Collection and repopulate the Collection with the new requested features. 

The problem happen on the first clear (move the map). I get the error message:

    Cannot read property 'forEach' of undefined

The error seams to come from the event propagation of the pop event and append in the function

    ol.source.Vector.prototype.removeFeatureInternal

Here is a sample code and the jsbin of the reproductible error

```javascript
var myCollection = new ol.Collection();

var myLayer = new ol.layer.Vector({
    source: new ol.source.Vector({
        features: myCollection
    })
})

function myUpdateFunction() {
    // var url = 'https://raw.githubusercontent.com/johan/world.geo.json/master/countries/USA/WY.geo.json'
    var url = "https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json";
    $.get(url).then(function(result) {
        var format = new ol.format.GeoJSON({
            defaultDataProjection: "EPSG:4326",
            featureProjection: "EPSG:3857"
        });
        var features = format.readFeatures(result);

        myCollection.clear();
        myCollection.extend(features);
    });
}

var map = new ol.Map({
    layers: [
        new ol.layer.Tile({source: new ol.source.OSM()}),
        myLayer
    ],
    target: 'map',
    controls: ol.control.defaults({
        attributionOptions:({collapsible: false})
    }),
    view: new ol.View({center: [0, 0],zoom: 2})
});

map.on('moveend', function(e) {
    myUpdateFunction();
});

```
https://jsbin.com/tivezamufi/1/edit?html,js,console,output

**Comment by ahocevar** [comment]
You have found a bug. It looks like using a vector source with spatial index *and* a collection of features is broken. You can configure your source with `useSpatialIndex: false` to work around the bug.

However, what you are doing here is very inefficient. Instead of using a collection with the source, you could use an array, and simply call `myLayer.getSource().clear()` and `myLayer.getSource().addFeatures(features)`. Or, even better, look into using an `ol.strategy.bbox` with your vector source.

**Comment by tchandelle** [comment]
@ahocevar : Is this a bug? Or bad documentation? I always thought it was supposed to be that way.

**Comment by ahocevar** [comment]
It's a bug. The source should work with *both* spatial index and a collection of features (although it is super inefficient).

**Comment by tchandelle** [comment]
> `options.useSpatialIndex` ... When set to false, the features will be maintained in an ol.Collection ...

and 

> `getFeaturesCollection` ... Will be null unless the source was configured with useSpatialIndex set to false ...

made me think otherwise.

**Comment by ahocevar** [comment]
@tchandelle The documentation for `#getFeaturesCollection()` is indeed misleading.

**Comment by labbitroma** [comment]
We have the same bug with interaction Select. Clearing collection `ol.interaction.Select.getFeatures()` triggers the bug randomly:

```
var selectedFeatures;
        map.getInteractions().forEach(function (interaction) {
            if (interaction instanceof ol.interaction.Select) {
                selectedFeatures = interaction.getFeatures();
                selectedFeatures.clear(); //error if there are many features selected
            }
        });
```

**Comment by labbitroma** [comment]
This bug happens if you add more than one feature with the same ID to the layer.

**Comment by ahocevar** [comment]
> This bug happens if you add more than one feature with the same ID to the layer.

Good find @labbitroma. We only make sure that a feature with the same id is not added again when using a spatial index, but not when using a collection.

So if someone wants to fix that, a pull request would be welcome.

**Comment by BasieP** [comment]
When will this bugfix be released? i am currently having the same problems
