### ISSUE TITLE
ol.interaction.Draw deleteCondition not working with Point feature

### ISSUE THREAD

**Issue by MerlinDuChaos** [openlayers/openlayers#6188]
Hi,

I'm not able to delete a point no matter which condition I write in deleteCondition.
It works with LineString and Polygon but not with Point features.

My version of OpenLayers is 3.19.1

Here is an excerpt of the code I'm using (it's TypeScript in Angular2 btw):

```
private _drawnFeatures: ol.Collection<any> = new ol.Collection<any>();

this._drawingSource = new ol.source.Vector({ features: this._drawnFeatures, wrapX: false });

this._drawingLayer = new ol.layer.Vector({
	source: this._drawingSource
});

this._drawInteraction = new ol.interaction.Draw({
	features: this._drawnFeatures,
	type: type,
	freehandCondition: ol.events.condition.altKeyOnly
});

var modify = new ol.interaction.Modify({
	features: this._drawnFeatures,
	deleteCondition: evt => { return ol.events.condition.shiftKeyOnly(evt) && ol.events.condition.singleClick(evt) }
});
```

**Comment by tchandelle** [comment]
It's not bug, it works as intended. If you read doc for `deleteCondition`, it's said that it's for deleting vertices. By definition, a vertex *is a point where two or more curves, lines, or edges meet* (wikipedia). So a single point is not a vertex.

However, what do you mean, when you said it works with LineString and Polygon ? When I try, it doesn't let me delete a vertex of a triangle.

**Comment by MerlinDuChaos** [comment]
Well this code is obviously not enough to make it work, but using the exemple here : http://openlayers.org/en/latest/examples/draw-and-modify-features.html
and tweaking it to match what I wanted to do, I could make it work.

Thanks for the explanation about the vertices.  How am I supposed to do it then ?  Should I reimplement myself the fact that when you click on a point while holding the shift key (for example) the point must be removed ?

**Comment by diegofps** [comment]
I managed to make this work on OpenLayers 4.6.3 using the following code (I think it also works on 3.x.y). With this I am able to delete Points by pressing the Shift + Click and insert new points by Clicking anywhere.

```javascript
modify = new ol.interaction.Modify({
    source: sourceVector,
    condition: evt => {
        if (!ol.events.condition.shiftKeyOnly(evt)) 
            return true;

        feature = sourceVector.getClosestFeatureToCoordinate(evt.coordinate);

        if (!feature) 
            return false;
    
        pixel1 = evt.pixel;
        pixel2 = olMap.getPixelFromCoordinate(feature.getGeometry().getCoordinates());

        if (sdistance(pixel1, pixel2) <= 100)
            sourceVector.removeFeature(feature);
        
        return false;
    }
});
```

sdistance is just a squared distance function, defined as:

```javascript
function sdistance(p1, p2)
{
    dx = p1[0] - p2[0];
    dy = p1[1] - p2[1];
    return dx*dx + dy*dy;
}
```

**Comment by nboisteault** [comment]
Hi,
Is there any official solution to delete a point by click with a `POINT` or `MULTIPOINT` vector?
@diegofps solution works but I'd like to avoid using `getClosestFeatureToCoordinate` function has it forces to use the `useSpatialIndex` parameter which changes feature order.
Thanks for any hint.

**Comment by mike-000** [comment]
Modify is intended to modify features, not remove them, so the minimum number of vertices must be retained - 1 for a Point, 2 for a LineString, and 3 for a Polygon.  It does seem wrong that a MultiPoint cannot be reduced to 1 point, that would be easy to implement https://codesandbox.io/s/modify-test-forked-ptjswh?file=/main.js
