### ISSUE TITLE
Style Bug When Overlaps is False and Outline is Used

### ISSUE THREAD

**Issue by x9xjdzz9** [openlayers/openlayers#6199]
When I set "overlaps" to false on a vector source where the features should have different styles, the correct styles are not used. It only seems to happen when "overlaps" is false and my polygons have a stroke style.

Example: https://jsfiddle.net/x9xjdzz9/g7avmh15/

**Comment by raiyni** [comment]
To add more documentation to the bug, it happens when the strokes are the same color.

**Comment by ahocevar** [comment]
Thanks for the bug report. I can confirm the issue.

**Comment by ahocevar** [comment]
Pull request: #6359
