### ISSUE TITLE
Context menu (right click) on map makes the drag control activate on safari

### ISSUE THREAD

**Issue by lpblais** [openlayers/openlayers#6200]
Can be tested here:

http://openlayers.org/en/latest/examples/bing-maps.html

A right click on the map brings up the context menu.
A left click on the map closes the context menu.
The mouse movement now drags the map without the left button being pressed

LP.

**Comment by cs09g** [comment]
reproducible using magic mouse on Mac

**Comment by ahocevar** [comment]
Bug confirmed.
