### ISSUE TITLE
constrainResolution broken for delta = -0.5

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#6212]
constrainResolution is broken for delta = -0.5, and I believe all deltas between -1 and 0.

This means that in practice you cannot zoom out with zoom control delta = 0.5, as in this example:
https://jsbin.com/kefogomogi/edit?html,output

I think the reason is that essentially olView.constraints_.resolution is broken, as can be seen:

```
olView.constraints_.resolution(2.9, -0.5, 0)
2.9562622252024005
```

Also, might be related here, that even for integer zoom levels, constrainResolution doesn't return whole numbers, but some 5% off ones. I believe this can result in non-integer zoom blurriness.

```
olView.constraints_.resolution(1, -1, 0)
2.09039306640625

and

olView.constraints_.resolution(1, 1, 0)
0.5225982666015625
```

I believe these should be exactly 2.0 and 0.5 to have pixel perfect zoom for integer levels.

**Comment by tschaub** [comment]
@hyperknot - I too have seen fishy behavior with the resolution constraint.  It would be good to know if things were working differently in a previous release.

**Comment by hyperknot** [comment]
@tschaub it's really simple to test it, as in my example you just need to click the zoom + once and the zoom - once. The - button won't work. I tried it back till 3.1.0 by editing the js library url and it was all the same.
