### ISSUE TITLE
WFS GetFeatures XML parsed by ol.format.WFS does not store the SRS Name in the feature or geometry.

### ISSUE THREAD

**Issue by shivbhaw** [openlayers/openlayers#6235]
I currently need to know the srs in which a feature was loaded in. But it seems that once the feature is parsed from ol.format.WFS, the SRS for the geometries are not stored. Ive checked the entire returned object, looked for methods on the classes and dove into the code and found no answer.

Is there a way that I can get the SRS for a features geometry, and if not, can we turn this into a feature request?

This is an example of my WFS GetFeature Response. Ive changed the values, but the format is the same.
```
<nsp:FeatureType gml:id="id_123">
  <nsp:featureCenterProperty>
    <gml:Point srsName="urn:x-ogc:def:crs:EPSG:900913" srsDimension="2">
      <gml:pos>2 2</gml:pos>
    </gml:Point>
  </nsp:featureCenterProperty>
  <nsp:featureExtentProperty>
    <gml:Polygon>
      <gml:exterior>
        <gml:LinearRing srsName="urn:x-ogc:def:crs:EPSG:900913">
          <gml:posList srsDimension="3">1 1 0 2 2 0 3 3 0 4 4 0 1 1 0</gml:posList>
        </gml:LinearRing>
      </gml:exterior>
    </gml:Polygon>
  </nsp:featureExtentProperty>
  <nsp:property1>123</nsp:property1>
  <nsp:property2>456</nsp:property2>
  <nsp:property3>789</nsp:property3>
</nsp:FeatureType>
```

**Comment by bartvde** [comment]
There is a readProjection method on the format

**Comment by shivbhaw** [comment]
I did see that, but with that I can only read the projection as long as I have the XML data. But I would like to get the SRS for the feature at a later point.

**Comment by bartvde** [comment]
We don't store projection info on geometries, and IIRC that was a design decision made early on in the project. I don't think that will be revisited to be honest.

**Comment by shivbhaw** [comment]
Why did you go with this decision? In openscales, for Flash, the srsName was stored in the Geometry, and this was very convenient.

**Comment by bartvde** [comment]
I don't recall to be honest it was years ago, maybe @ahocevar or @tschaub remember the rationale though.

You can always store any custom property on geometry or feature, or layer, whatever is the correct level for you, since they all extend ```ol.Object```

**Comment by ahocevar** [comment]
Neither @tschaub nor myself were involved in that decision. However, maybe it helps to understand how things currently work: on an `ol.source.Vector`, features are always stored with geometries in the projection of the view. Whether this makes sense or not is debatable, see https://groups.google.com/d/msgid/ol3-dev/CAKdrn%2Bd5tqqbF6t--h_pnoup%3DD-ErdpvkqmbRf17WHco-a8GSw%40mail.gmail.com.
