### ISSUE TITLE
ol.control.Attribution -> intersection test and uniqueAttributions only considering sources of type ol.source.TileImage

### ISSUE THREAD

**Issue by cvenzin** [openlayers/openlayers#6237]
Why are only sources of the type ol.source.TileImage considered in these tests?
In my opinion, it doesn't make sense if I have a TileWMS with attributions "Swisstopo" and an ImageWMS with attributions "Swisstopo", that the ol.control.Attribution shows the attribution "Swisstopo" twice.
In addition, if I have layers with sources of type ol.source.Vector or ol.source.ImageWMS only covering Zurich, I do not expect these attributions showing up when the current map extent is only covering Bern for example.

**Comment by ahocevar** [comment]
A very valid issue, and a reminder that the whole attribution handling needs to be massively overhauled and simplified.

**Comment by marcjansen** [comment]
plus one for simplification
