### ISSUE TITLE
wmts-dimensions example broken

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#6245]
http://openlayers.org/en/latest/examples/wmts-dimensions.html

The wmts server at scalgo.com respond with a "Unknown theme." message.

**Comment by bartvde** [comment]
ping @thomasmoelhave

**Comment by thomasmoelhave** [comment]
Thanks for the ping. We'll look into it ASAP.

**Comment by fredj** [comment]
Thanks @thomasmoelhave

**Comment by thomasmoelhave** [comment]
We have strengtenhed our token system and this legacy token is no longer accepted - I had not realized that change would affect this example. Sorry.

I will submit a pull request with a new long-term token later this week.
