### ISSUE TITLE
console undefined in IE 9

### ISSUE THREAD

**Issue by schmidtk** [openlayers/openlayers#6248]
IE 9 does not define `window.console` until developer tools is opened. This causes a page failure when calling `console.assert`.

Discussion and quite a few solutions are on [StackOverflow here](http://stackoverflow.com/questions/3326650/console-is-undefined-error-for-internet-explorer/16916941).

At minimum, the compatibility instructions for IE could include a note on this behavior since the scope is very limited (IE 9, `ol.DEBUG=true`, developer tools not opened).

**Comment by ahocevar** [comment]
Would it be enough to include a `console` polyfill in addition to the https://cdn.polyfill.io polyfills we already include?

**Comment by schmidtk** [comment]
Yeah that should fix it.

**Comment by tschaub** [comment]
I forget if there is a reason not to just throw instead of relying on console.assert.

**Comment by ahocevar** [comment]
The idea was to make it easier to strip this out of compiled code. Browserify can be configured to strip out all console statements. But if there is another way, then why not get rid of it.

**Comment by fredj** [comment]
All `console.assert` have been removed
