### ISSUE TITLE
Clustering based on feature property (i.e. attributive clusters)

### ISSUE THREAD

**Issue by aberenyi** [openlayers/openlayers#6257]
Gents - this was a really great feature in OL2.

Any plans on implementing this?

Cheers

**Comment by ahocevar** [comment]
What exactly are you referring to?

**Comment by aberenyi** [comment]
I cannot describe better than you did [here](http://dev.openlayers.org/sandbox/ahocevar/offline/examples/strategy-cluster-extended.html).


> Attributive cluster-strategy uses a customized cluster strategy. This strategy is configured to cluster features of the same clazz only. You should be able to see all red points (clazz = 4) even though the data is clustered. A cluster now contains only features of the same clazz.

**Comment by marcjansen** [comment]
Now that's a nice example 😉

**Comment by marcjansen** [comment]
AFAICT that example was there to show how you could extend ol2, it was a showcase of the capabilities to exten the cluster strategy.

**Comment by aberenyi** [comment]
FWIW I'm still using that here and there 😉

**Comment by jffaust** [comment]
It was a really great feature. An alternative to this is to group your data beforehand and then have one layer per cluster but then the clusters could overlap.
I guess we'll have to implement our own clustering ourselves and then just user a standard vector source.

**Comment by ahocevar** [comment]
You can achieve that by configuring the `geometryFunction` of `ol/source/Cluster`.
