### ISSUE TITLE
ol.source.ImageVector + ol.interaction.Select toggle unselect issue

### ISSUE THREAD

**Issue by DavidHequet** [openlayers/openlayers#6262]
Hi,

there is a bug in ol.interraction.select combined with imagevector layer: You can normaly select by single click or add to selection, but impossible to remove from selection

step to reproduce in this jsfiddle,i juste edited the select-features example to replace ol.layer.vector with ol.layer.Image( ... new ol.source.ImageVector ... )
https://jsfiddle.net/davidhequet/ddhhtdyv/2/

1. Clic to select a feature
2. shift+click to add feature to selection
3. shift+click to remove feature from selection (wich works in standard vector layer) : nothing happens

I tried a custom toggleCondition, the selected Featurs is not detected in map.ForEachFeatureAtPixel

Thank you,
David

**Comment by xaadim** [comment]
Hi David,
Did you finally find a solution?

Thank you

**Comment by dugasmark** [comment]
Same for me on 4.2.0, any solution?

**Comment by dugasmark** [comment]
This solves the problem for me
https://github.com/openlayers/openlayers/pull/6719

**Comment by tiagowippel** [comment]
same here....
