### ISSUE TITLE
Custom builds without closure-util

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers#6263]
For my own purposes I've implemented a custom build process that replaces closure-util and `tasks/build.js` with https://www.npmjs.com/package/google-closure-compiler. This comes with grunt and gulp plugins and is very easy to use. I'm using gulp, and the gulpfile looks like this:
```
var gulp = require('gulp');
var closureCompiler = require('google-closure-compiler').gulp();

var compileOptions = require('./build/mmregbuild.json').compile;
compileOptions.js = ['src/ol/**.js', 'build/ol.ext/**.js', 'build/mmexports.js', 'build/closure/base.js'];
compileOptions.js_output_file = 'build/output.min.js';

gulp.task('default', function () {
  return closureCompiler(compileOptions)
  .src() // needed to force the plugin to run without gulp.src
  .pipe(gulp.dest('.'));
});
```
`mmregbuild.json` is the same config file used by the current `build.js`, so it's simply taking the `compile` object from this.
`build.js` currently uses closure-util for `getDependencies` as well as running the compiler, but this is not really needed, as you can simply pass all the `src/` files to the compiler and let it sort out which ones are needed.
Apart from `src/`, the compiler needs the 3 other items in the `js` option. These are produced by running `tasks/build-ext.js` and `tasks/generate-exports.js`, neither of which uses closure-util, and by copying `base.js` from Closure library. The first two could be incorporated in the gulpfile, but for my own purposes I'm happy to run these separately beforehand. `build.js` also adds a standard header, but this can easily by added to the output_wrapper.

There is one issue, which is that the package uses the latest compiler release and ol does not compile with this: my custom build produces screenfuls of warnings and the output code doesn't work. When I copy `compiler.jar` currently used by closure-util to the compiler pkg, the output is the same as that produced by `build.js`. ol compiles with the later July release, which is supposed to be 'much faster', though the output is a bit larger. Most of the warnings from the latest release are to do with `@abstract`, so this would have to be investigated.

As an additional bonus, the Closure team recently released a [JS version](https://www.npmjs.com/package/google-closure-compiler-js) of the compiler, which has a similar gulp option. Some simple compiles I tried with this worked fine, so this looks promising, as custom builders would no longer have to install Java. However, it can't be used with ol until the issues with the latest compiler are resolved. I'm also not sure that all the compiler options that ol uses are included.

Full CI uses closure-util for other things, but ISTM this process is simpler for custom builders. You could create a separate package for this, but if we say that `dependencies` in `package.json` is for custom builds, and `dev-dependencies` is for CI, I think closure-util, glob, handlebars, marked, metalsmith, metalsmith-layouts, and temp can be moved to `dev-dependencies` and replaced with google-closure-compiler. The current `postinstall` script can be moved to the CI process, which would also fix #5943.

**Comment by gberaudo** [comment]
Thanks for sharing your experiments @probins.
Have you tried with an older version of the `google-closure-compiler` npm package?

**Comment by probins** [comment]
I thought of doing that, but that wouldn't include recent bug fixes etc to the npm pkg. I think it's simpler just to download the old compiler manually and stick it in node_modules instead of the supplied one

**Comment by probins** [comment]
one other thing: if custom builders get rid of closure-util and hence closure lib, that frees up 23MB :-)

**Comment by fredj** [comment]
FYI I've started to fix the code for the new version of the compiler, see:
https://github.com/openlayers/ol3/compare/update_cc

**Comment by tschaub** [comment]
Thanks for the work on this @probins.  It is definitely the right direction to remove our dependency on `closure-util`.

I'd also like to completely remove our dependency on the Closure Library - no `goog.require()` or `goog.provide()`.  I did some initial work getting rid of these in our library, but ran into trouble trying to get the Compiler to behave the same way it does with `goog.provide()` *without* actually having `goog.provide()` calls in our code.  I suppose as an interim solution we could have our own implementations of these functions (keeping the names the same).

**Comment by probins** [comment]
@tschaub I'm not sure this is worth spending time on. The build process also needs `exportSymbol` and `exportProperty` from `goog/base.js`, and uncompiled load also needs it. These are all external dependencies from the `goog` namespace. But they're all in one file, and this file can just be copied, for example into `src/`, and passed to the compiler. It doesn't need to be updated, or kept in sync with the Closure library version, should that ever change. So there's no longer any need for the Closure lib as a whole to be downloaded. I was originally thinking of changing `tasks/build.js` to ignore Closure lib, but I decided that using the compiler package with grunt or gulp is a simpler solution, especially as many people will already be using these for other things. Uncompiled load could use [rawgit](https://rawgit.com/google/closure-library/master/closure/goog/base.js).

**Comment by probins** [comment]
_update_: I've been experimenting further with the JS compiler, which now has a command-line option. Rather bizarrely, this compiler does not handle `manageClosureDependencies`, so you cannot throw a glob of source files at it as you can with the Java version. You would have to implement something like closure-util's `getDependencies()` to feed it with the files in the right sequence. So I've concluded that it's simpler to stick with the Java package for now.

**Comment by probins** [comment]
now obsolete
