### ISSUE TITLE
Missing hidpi option for ol.source.ImageArcGISRest

### ISSUE THREAD

**Issue by alperdincer** [openlayers/openlayers#6272]
Hi,

I'm working on a multi layer project that ArcGIS Server is one of the providers and I'm having problems with ol.source.ImageArcGISRest and ol.layer.image. As I checked, the map extent is not suitable with the extent in the URL? 

I tried different things to fix it, but I can't. But I found a issue if the map width is larger than 1000px, than image is not aligned to map. 

Also I realized that even I'm not using the retina screen, my image size sent to server is doubled due to pixelRatio. 

Any ideas to fix the problem?

**Image that has 800px width :**
<img width="810" alt="width-800px" src="https://cloud.githubusercontent.com/assets/1174240/21286463/316ec8f6-c45d-11e6-8e27-cb46daecc467.png">

**Image that has 1200px width :**
<img width="1212" alt="width-1200px" src="https://cloud.githubusercontent.com/assets/1174240/21286464/317033d0-c45d-11e6-9439-72c35a442ac5.png">

**Comment by bartvde** [comment]
Any chance of providing a jsFiddle?

**Comment by alperdincer** [comment]
You can use this as sample, but in this example it gets "404 Image width is not in range. Valid range is from 1 to 2048." error in MacBook Pro Retina screen. It is working normal on external monitor that has no retina property. 

Is it possible to change to PixelRatio even it is working on retina displays?

Sample Address : https://jsfiddle.net/wngx5v6g/

**Comment by ahocevar** [comment]
Other image layer types have a `hidpi` Option. When set to `false`, the image will always be requested with a pixel ratio of 1.  `ol.source.ImageArcGISRest` does not have this, but we'd accept a pull request to add it.
