### ISSUE TITLE
geojson-vt integration

### ISSUE THREAD

**Issue by femski** [openlayers/openlayers#6273]
For large datasets, Openlayer's GeoJSON performance is poor compared to geojson-vt. There should be a way take geojson-vt output an feed it into Openlayer easily. Too bad there are no working example for geojson-vt and ol3 integration. Are there any efforts on to improve big data capabilities of ol3 to handle large GeoJSONs using a librray similar to geojson-vt ?

**Comment by ahocevar** [comment]
It should be straightforward and easy to use geojson-vt generated tiles with `ol.layer.VectorTile` and `ol.source.VectorTile`. Probably with a custom `tileLoadFunction` on the VectorTile source.

If someone wants to give it a try, we'd accept a pull request for an example.

**Comment by drnextgis** [comment]
@ahocevar geojson-vt `getTile` method returns raw Mapbox feature and we cannot parse it because appropriate method are not part of OpenLayers API. How we can cope with it?

**Comment by oterral** [comment]
@drnextgis `readGeometry` function is part of the api for some others format so I think you can propose a PR making this function part of the api.

Remove the `@private` annotation and just add `@api` annotation to the function doc like this:

```
/**
 * @param {Object} rawFeature Raw Mapbox feature.
 * @return {ol.geom.Geometry} Geometry.
 * @api
 */
ol.format.MVT.readGeometry_ = function(rawFeature) {
```

then rename `ol.format.MVT.readGeometry_` to `ol.format.MVT.readGeometry`

**Comment by ahocevar** [comment]
Before deciding on a pull request, I'd like to see the code you are using. I'm sure you can also get all features instead of just a geometry from geojson-vt.

**Comment by drnextgis** [comment]
Something like this:

```
> tileIndex = geojsonvt(geojsonObject);
> JSON.stringify(tileIndex.getTile(0,0,0).features);
"[{"geometry":[[[-64,460],[4160,460]],[[-64,3636],[4160,3636]]],"type":2,"tags":null},{"geometry":[[[-64,460],[4160,460],[-64,460]]],"type":3,"tags":null},{"geometry":[[[-64,1551],[4160,1551]]],"type":2,"tags":null},{"geometry":[[2048,2048]],"type":1,"tags":null},{"geometry":[[[-64,460],[4160,460]],[[-64,3636],[4160,3636]]],"type":2,"tags":null},{"geometry":[[[-64,460],[2048,460],[2048,2907],[-64,460]]],"type":3,"tags":null},{"geometry":[[[-64,1551],[2048,1551]]],"type":2,"tags":null},{"geometry":[[[-64,460],[4160,460]],[[-64,3636],[4160,3636]]],"type":2,"tags":null}]"
```

**Comment by ahocevar** [comment]
The above returns GeoJSON, not PBF. You should be able to parse that with `ol.format.GeoJSON#readFeatures()`.

**Comment by drnextgis** [comment]
This is not valid GeoJSON, `type` member should be string, but is an number instead.

**Comment by ahocevar** [comment]
And how would `ol.format.MVT` help you here?

**Comment by drnextgis** [comment]
I thought that `getTile` feature's format is the same as VectorTileFeature [here](https://github.com/mapbox/vector-tile-js). But it looks like geojson-vt returns feature in [custom](https://github.com/mapbox/geojson-vt/blob/master/src/feature.js#L6) format and we can not use existing OpenLayers formats for reading them.

**Comment by ahocevar** [comment]
These features look different indeed. However, it looks trivial to turn those features into valid GeoJSON by using `JSON.stringify()` with a replacer function.

**Comment by femski** [comment]
This (typescript code) works for me (mostly). However, I see some erratic behavior - with polygons disappearing as I zoom and pan. I guess there is some configuration issue. But performance on even moderate size geojson is much improved over native GeoJSON of ol3. It would be nice if it always worked.

	let census_style = new ol.style.Style({
                	stroke: new ol.style.Stroke({
                    color: 'blue',
                    lineDash: [4],
                    width: 3
                }),
                fill: new ol.style.Fill({
                    color: 'rgba(0, 255, 255, 0.3)'
                })
            },
        );

	new ol.layer.VectorTile({source: this.vectorSrc,
                        renderOrder : function(feature1: ol.Feature, feature2: ol.Feature): number {
                                                return 1
                                        },
                            style: census_style
                        })


            this.vectorSrc = new ol.source.VectorTile({
            renderMode: 'image',
            preload: Infinity,
            format: new ol.format.GeoJSON(),
            projection: 'EPSG:3857',
            tileGrid: ol.tilegrid.createXYZ({maxZoom: 12}),
            tilePixelRatio: 16,
            url: '{z}/{x}/{y}',

            tileLoadFunction : (tile:any, src:any) => {
                tile.setLoader(() => {

                    let coord = tile.getTileCoord();

                    let z =  coord[0];
                    let z2 = 1 << coord[0];
                    let tx = coord[1];
                    let ty = -coord[2]-1; //

                    if (this.tileIndex) {

                        let tile1 = this.tileIndex.getTile(coord[0], tx, ty)

                        if (tile1){

                            let features = tile1.features;

                            let ol_features: ol.Feature[] = [];

                            for (let i = 0; i < features.length; i++) {
                                let feature = features[i];

                                let type = feature.type;

                                let points: ol.Coordinate[][] = [];

                                for (let j = 0; j < feature.geometry.length; j++) {

                                    let geom = feature.geometry[j];

                                    let pt: ol.Coordinate[] = [];
                                    for (var k = 0; k < geom.length; k++) {

                                        let x = (geom[k][0] / extent + tx) / z2;
                                        let y = (geom[k][1] / extent + (ty)) / z2;
                                        let c = [((x - 0.5) * 2) * 6378137 * Math.PI, -((y - 0.5) * 2) * 6378137 * Math.PI];
                                        pt.push([c[0], c[1]]);

                                    }
                                    points.push(pt);

                                }

                                ol_features.push(new ol.Feature({
                                        geometry: new ol.geom.Polygon(points),
                                    })
                                );


                            }

                            tile.setFeatures(ol_features);
                            tile.setProjection(ol.proj.get('EPSG:3857'));
                        }
                    }
                });
            }
        });

       this.map.getView().on('change:resolution', (e:any) => {
                    this.vectorSrc.refresh();
                });

**Comment by drnextgis** [comment]
I've made example of integration of geojson-vt and OpenLayers here https://github.com/drnextgis/ol3/commit/1a6caea14c466f366d78cdf62ae0e7b4b4210272. But I have one problem: when I run this example using development server (`make serve`) all works fine, but if open example in jsfiddle (click `Edit` button) it doesn't work, [example](https://jsfiddle.net/qpzudgg8/).

**Comment by femski** [comment]
There was one bug in my code:

       tileLoadFunction : (tile:any, src:any) => {

            // populate features here

              tile.setLoader(() => {

                    tile.setFeatures(ol_features);
                    tile.setProjection(ol.proj.get('EPSG:3857'));

                });

ie. setLodaer should only be called at least and at most once.
With that it works 100% of time. No need to refresh source on zoom change. 

I also got @drnextgis code to work with one simple change:

replace:

     var tileCoords = url.split('/');
      var x = parseInt(tileCoords[0], 10);
      var y = parseInt(tileCoords[1], 10);
      var z = parseInt(tileCoords[2], 10);
with:

               let coord = tile.getTileCoord();
                let z =  coord[0];
                let z2 = 1 << coord[0];
                let x = coord[1];
                let y = -coord[2]-1; //

with that it works.

My issue is now is if I switch to webgl renderer - I get vectorSuurce.loadFeatures  not a function.

For now I am very happy that we can get ol3 to work with geojson-vt. Hurray !

**Comment by ahocevar** [comment]
I have updated @drnextgis's fiddle to work 100%: http://jsfiddle.net/qpzudgg8/2/.

**Comment by drnextgis** [comment]
@ahocevar thanks for help! I've made PR https://github.com/openlayers/openlayers/pull/6381 with your updates.

**Comment by ahmedshahab** [comment]
How to make geojson-vt work above 24 zoom levels or what could be the alternative?
