### ISSUE TITLE
ol.interaction.draw freehand polygon draw generates duplicate vertices

### ISSUE THREAD

**Issue by rwlnd** [openlayers/openlayers#6288]
Hi all, 

During my search to find a way to check if a polygon is self-intersecting (http://stackoverflow.com/questions/41248324/openlayers3-check-if-polygon-is-self-intersecting) I ran across the following finding:

When drawing a polygon by freehand (hold SHIFT) using ol.interaction.Draw, the interaction seems to periodically draw multiple vertices at the same location.

I am currently using turf-kinks to determine if a polygon is self intersecting and because of the duplicated vertices, I get intersects for the polygon, even tho it actually isn't.

visual illustration (I styled the vertices transparent so it's easy to spot the 'doubles'):

![polygon-01](https://cloud.githubusercontent.com/assets/9771588/21384782/43cceee4-c76c-11e6-8b5d-23d920dd4b27.PNG)

![polygon-02](https://cloud.githubusercontent.com/assets/9771588/21384785/473c0f42-c76c-11e6-963d-d0927b9e1303.png)

Any workarounds to avoid this in the meanwhile?

**Comment by ChouGary** [comment]
https://jsfiddle.net/td8k43wz/
 draw.on('drawend',function(f){
  f.feature.setGeometry(f.feature.getGeometry().simplify(f.target.getMap().getView().getResolution()));
})

**Comment by ahocevar** [comment]
@rwlnd Does @ChouGary's approach help in your case? If so, I think you can close this issue.

**Comment by rwlnd** [comment]
@ahocevar this could be a possible solution I guess but I don't really want to simplify the geometry.
Currently, my workaround is to remove the duplicate coordinates on drawend myself.

```
function removeDuplicateCoordinates(feature) {
    var coordinates = feature.getGeometry().getCoordinates()[0];
    var dictionary = {};
    var filteredPolygonCoordinates = [];
    filteredPolygonCoordinates.push(coordinates[0]);
    for (var i = 1; i < (coordinates.length - 1) ; i++) {
        var key = coordinates[i][0] + '' + coordinates[i][1];
        if (!dictionary[key]) {
            dictionary[key] = coordinates[i];
            filteredPolygonCoordinates.push(coordinates[i]);
        }
    }
    filteredPolygonCoordinates.push(coordinates[(coordinates.length - 1)]);
    feature.getGeometry().setCoordinates([filteredPolygonCoordinates]);
}
```

It's ok for me to close this but I just wanted to point this out as I am currently upgrading an openlayers2 component to openlayers3 and in openlayers2 this problem did not seem to occur. I thought that maybe it would be cleaner to have the same behaviour in openlayers3 but in case someone comes across the same problem, I hope this issue can at least help a bit.
