### ISSUE TITLE
Explicitly require the renderer

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#6303]
We currently offer runtime renderer configuration with `renderer: 'canvas'` or `renderer: 'webgl'` as map options.  This was a nice idea, but it has the major drawback of not being able to explicitly depend on just one renderer.  We assumed everybody would be using Closure Compiler build flags like `ENABLE_WEBGL=false`.  Instead people use the full build - which includes far more code than anybody needs - since it is far more convenient than using the Closure Compiler.  While the WebGL renderer has been gaining functionality, it is still incomplete, and I don't think there has been a good reason to push it on all of our users for 2.5 years.

So, I think it would make sense to specify more explicitly which renderer an application depends on.  I see two alternatives for doing this.

### Alternative 1

Make it so the `renderer` option accepts a renderer constructor instead of a string.  Keep the Canvas renderer the default.

People who want to use the Canvas renderer would not change any application code.  People who want to use the WebGL renderer would do this:
```
var map = new ol.Map({
  renderer: ol.renderer.webgl.Map,
  // ...
});
```
To get a smaller build with the Closure Compiler, people using the WebGL renderer would set `ENABLE_CANVAS=false` (as they have to now).  The downside of this alternative is that all layer renderer types are still required for each layer type. 

### Alternative 2

Create a new map constructor that pulls in the WebGL renderer.  Keep the `ol.Map` constructor using the Canvas renderer.  Create new layer renderers that pull in WebGL layer rendering code.  Keep the existing layer constructors using Canvas rendering code.

People who want to use the Canvas renderer would not change any application code.  People who want to use the WebGL renderer would do this:
```
var map = new ol.WebGLMap({
  layers: [
    new ol.layer.WebGLTile({
      // ...
    })
  ]
});
```

There would be no renderer-related build flags in this alternative.  Everybody could get smaller builds just by using the correct type of map and layer.

**Comment by ahocevar** [comment]
I have been thinking through this toda as well, and I think **Alternative 2** is the way to go.

**Comment by probins** [comment]
I would suggest a third alternative: split map.js in two. Move the map class definition to a new file, called, say, BaseMap. Have map.js inherit from basemap, and add the defaults in createOptionsInternal(). Then Map would remain as is for bc, and people who did not want 2 renderers and all the other defaults could use BaseMap and add what they did want in their apps. BaseMap would be an addition to the api, and could have any new functions it needed. This would also enable specifying the renderer at run time:
```js
var map = new BaseMap();
var renderer = has.webgl ? 'webgl' : 'canvas';
import(`./renderer/${renderer}.js`).then(module => {map.setRenderer(module)});
```
or similar.

This fixes part of the problem, but not the problem of the map renderers, like renderer.canvas.Map, requiring all layer types, whether they're needed or not. I think what's needed is for apps to add for example renderer.canvas.TileLayer to the map, which should import renderer.canvas.Layer, which should import renderer.canvas.Map. What I don't know is how you would implement that while keeping bc.

So my real preference would be to wind down development of ol3 and move to a new ES6-based ol4, with a similar but different api. This would enable a complete rethink of the dependency structure. I would prefer to get rid of all the build flags, as they're globals and don't really fit in with ES6 static module dependencies.

**Comment by ahocevar** [comment]
From an API/usability perspective, I'm -1 on @probins's suggestions above.

**Comment by probins** [comment]
then we should be able to get rid of the ENABLE flags too, right?

**Comment by probins** [comment]
of @tschaub's 2 alternatives, I too prefer the 2nd, as it removes the build flags. But I presume that it too would mean splitting map.js in two: the renderer bit and the rest of the code would be common. It also means an api change, as the renderer option is currently stable. That's probably not much of an issue in practice, as most people probably don't define it, but just use the default.

**Comment by tschaub** [comment]
> There is also no need for the map renderer to create the layer renderer instances, so we can also remove the dependency on all the layer renderers. I'm working on a pull request for this.

This sounds great @ahocevar.  I've been troubled by this as well.

As far as I can see, we'll still need to rely on defines to get rid of unwanted renderer code, right?

Things would be far more straightforward if we could agree on having just a single rendering strategy.

**Comment by tschaub** [comment]
@ahocevar - I put up a few commits that remove the layers and layer renderers as dependencies of the map renderers.  See #6312 (still WIP).

**Comment by ahocevar** [comment]
> Things would be far more straightforward if we could agree on having just a single rendering strategy.

Agreed. The other available rendering strategy could be some kind of an add-on (maybe similar to the way we integrate proj4js).

**Comment by probins** [comment]
a quick workaround to the 'far more code than anybody needs' problem would be to publish 2 not-quite-so-full builds, one for each renderer. These could either be in addition to the current `ol.js` full build, or the canvas one could replace that on the assumption that most people probably don't use webgl.

#6312 makes it clear that just dealing with the map renderer does not fix this issue; the layer renderers have to be specifiable at runtime as well. So apps have to decide which renderer they want to use, and then have some way of creating both the appropriate map renderer and the appropriate layer renderers for the layer/renderer type(s) they want to use.

**Comment by probins** [comment]
thinking about the layers a bit more, it's actually not that difficult to make them renderer-specific. With the new structure, `ENABLE_WEBGL` is only used in `create_renderer()` (such as https://github.com/openlayers/ol3/blob/master/src/ol/layer/tile.js#L45). So create new renderer-specific files for each layer type; for example `layer/tilecanvas.js`, which requires the canvas renderer and has a `create_renderer()` which returns it. webgl similarly. Then apps would import from these depending on which renderer they want to use. `layer/tile.js` could remain as is for bc. Alternatively, to make things easier for the majority who use canvas, the canvas version could replace `layer/tile.js`, meaning that existing apps using canvas would not need changing. webgl apps would though have to be changed to use the webgl layer renderer, meaning it's not bc.

`ENABLE_WEBGL` is also used in `has.js`, which adds a dependency on `ol.webgl`. This makes little sense, and it would be better to move it out of `has.js`. However, it's marked `api stable`, and moving it for example to `ol.webgl.has` would also break bc.

**Comment by tschaub** [comment]
Yes, layer constructors need to be specific too.  I've updated **Alternative 2** above to reflect this.

**Comment by tschaub** [comment]
The map and layer renderers have become plugins in #6855.
