### ISSUE TITLE
error when modifying polygon

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#6310]
I just run into the following error while playing around, editing a simple polygon.

Unfortunately I have no idea what triggered the bug, I was just (double) clicking around for testing.

The polygon was created simply by a draw interaction.

3.20.1 / Chrome / OS X 10.11.6

```
Assertion failed: uid (%s) of value (%s) does not exist 137 Objectdepth: Array[1]feature: ol.Featuregeometry: ol.geom.Polygonindex: 4ol_uid: 137segment: Array[2]__proto__: Object
ol.structs.RBush.update @ ol-debug.js:34819
ol.interaction.Modify.handleUpEvent_ @ ol-debug.js:69494
ol.interaction.Pointer.handleEvent @ ol-debug.js:18627
ol.interaction.Modify.handleEvent @ ol-debug.js:69539
ol.Map.handleMapBrowserEvent @ ol-debug.js:41784
boundListener @ ol-debug.js:3441
ol.events.EventTarget.dispatchEvent @ ol-debug.js:3859
ol.MapBrowserEventHandler.handlePointerUp_ @ ol-debug.js:17027
boundListener @ ol-debug.js:3441
ol.events.EventTarget.dispatchEvent @ ol-debug.js:3859
ol.pointer.PointerEventHandler.fireNativeEvent @ ol-debug.js:16802
ol.pointer.NativeSource.pointerUp @ ol-debug.js:15645
ol.pointer.PointerEventHandler.eventHandler_ @ ol-debug.js:16591
boundListener @ ol-debug.js:3441

Uncaught TypeError: Cannot read property 'minX' of undefined
    at ol.structs.RBush.update (ol-debug.js:34823)
    at ol.interaction.Modify.handleUpEvent_ (ol-debug.js:69494)
    at ol.interaction.Modify.ol.interaction.Pointer.handleEvent (ol-debug.js:18627)
    at ol.interaction.Modify.handleEvent (ol-debug.js:69539)
    at ol.Map.handleMapBrowserEvent (ol-debug.js:41784)
    at ol.MapBrowserEventHandler.boundListener (ol-debug.js:3441)
    at ol.MapBrowserEventHandler.ol.events.EventTarget.dispatchEvent (ol-debug.js:3859)
    at ol.MapBrowserEventHandler.handlePointerUp_ (ol-debug.js:17027)
    at ol.pointer.PointerEventHandler.boundListener (ol-debug.js:3441)
    at ol.pointer.PointerEventHandler.ol.events.EventTarget.dispatchEvent (ol-debug.js:3859)
ol.structs.RBush.update @ ol-debug.js:34823
ol.interaction.Modify.handleUpEvent_ @ ol-debug.js:69494
ol.interaction.Pointer.handleEvent @ ol-debug.js:18627
ol.interaction.Modify.handleEvent @ ol-debug.js:69539
ol.Map.handleMapBrowserEvent @ ol-debug.js:41784
boundListener @ ol-debug.js:3441
ol.events.EventTarget.dispatchEvent @ ol-debug.js:3859
ol.MapBrowserEventHandler.handlePointerUp_ @ ol-debug.js:17027
boundListener @ ol-debug.js:3441
ol.events.EventTarget.dispatchEvent @ ol-debug.js:3859
ol.pointer.PointerEventHandler.fireNativeEvent @ ol-debug.js:16802
ol.pointer.NativeSource.pointerUp @ ol-debug.js:15645
ol.pointer.PointerEventHandler.eventHandler_ @ ol-debug.js:16591
boundListener @ ol-debug.js:3441
```

**Comment by ahocevar** [comment]
Can you reproduce it again? If so, a link to an example and step-by-step instructions for triggering the bug would help.

**Comment by hyperknot** [comment]
OK, I tried to play around, and I remember this bug also happening before. No exception now, but the bug (or possibly a related bug) is clearly visible here:

https://youtu.be/40v1JzOUo8k

**Comment by ahocevar** [comment]
Looks like someone's modifying coordinates without calling `changed()` on the geometry. We'd still need a link to an official example or a working JSFiddle that reveals the issue.

**Comment by hyperknot** [comment]
The example code is super small, I could try doing it on an official example. For the actual manual method of triggering the bug, I still couldn't figure out 100% reliably.

**Comment by elimau** [comment]
i have got the error happening on an open-layers 4 example. To make it happen, just move vertices and click around at the same time randomly very quickly.
screenshot here: [https://postimg.org/image/ilyzgmash/](url)

**Comment by dbaston** [comment]
I'm still getting this error in v4.1.1.

**Comment by ahocevar** [comment]
@dbaston Can you please describe the steps to reproduce in v4.1.1? I'm not seeing the issue any more.

**Comment by PerryRylance** [comment]
I've come across a similar issue in 4.2.0, according to this duplicate issue

https://github.com/openlayers/openlayers/issues/6815 

This happens when I have

- A select interaction
- A modify interaction on the select interactions features
- And I start drawing a polygon

If I comment out the modify interaction code, the issue goes away

A potential workaround until this is fixed is to make the modify interaction inactive, and then activate it when the select event fires on the select interaction (and there are objects selected)

**Comment by megawac** [comment]
I'm seeing this as well in v4.2.0 in some internal code when underlying `Collection` is cleared and then repopulated and followed by the user attempting to modify the vertexs of the feature. When `ol.structs.RBush.prototype.update` attempts to update, `items_` doesn't have the features uuid in its collection causing a type error.

**Comment by oleg-l** [comment]
I'm getting similar behavior on v4.6.4 when I add select, modify and draw 'Poligon' (or 'LineString') interactions simultaneously:
var select = new ol.interaction.Select({ wrapX: false });
var modify = new ol.interaction.Modify({ features: select.getFeatures() });
var map = new ol.Map({
	interactions: ol.interaction.defaults().extend([select, modify]),
	...
});
...
var draw = new ol.interaction.Draw({
	source: source,
	type: 'Poligon'
});
map.addInteraction(app.draw);

To avoid this I remove select & modify before adding draw.

**Comment by stralopple** [comment]
I fixed this issue by providing a source, instead of features to the modify interaction.

**Comment by stralopple** [comment]
Though this is admittedly a workaround. modifying the feature manually using, say, `someFeature.getGeometry().translate([x, y])` causes the same issue.

**Comment by precisionterrain** [comment]
Similar issue. 

Dodgy hack workaround (side effects not observed but could exist):

In the function "ol.structs.RBush.prototype.update" add the following line

`
var item = this.items_[ol.getUid(value)];
if (!item) return; // <== added line
`

**Comment by Chris1234567899** [comment]
Issue still exists in v 5.0.0

**Comment by tohu12** [comment]
And my hack workaround without update OL source file:
```javascript
// my javascript (ES6) script
import RBush from 'ol/structs/RBush';

const RBushUpdateOrig = RBush.prototype.update;

RBush.prototype.update = function () {
    try {
        RBushUpdateOrig.apply(this, arguments);
    } catch (e) {
        console.warn('RBushUpdateOrig', e);
    }
};
```
Maybe it helps somebody :)

**Comment by denov** [comment]
why is this closed?  this still seems to be an issue in 5.0.  @precisionterrain seems to have the fix.

**Comment by ahocevar** [comment]
Reopened. The dodgy workarounds here look dangerous to me. It would be better to fix the problem at the root, which appears to be that the vertex rtree and the geometries get out of sync. Pull requests with a fix along these lines are greatly appreciated.

**Comment by dbrnz** [comment]
@ahocevar, although #9036 fixes the `Cannot read property 'minX' of undefined` error it breaks feature modification.

I've tried using both [v6.0.0-beta.1](https://github.com/openlayers/openlayers/releases/tag/v6.0.0-beta.1), as well as 5.3.0 with just #9036 applied, and in both cases the end point of a selected LineString becomes detached from the line when the mouse pointer is moved.

A selected LineString with mouse pointer on lower end of line:
<img width="63" alt="screen shot 2019-02-19 at 5 38 46 pm" src="https://user-images.githubusercontent.com/239220/52990819-d4a2d980-346e-11e9-9f63-2f4516d26366.png">

Pointer moved -- LineString becomes unselected and the 'end-point' detaches:
<img width="75" alt="screen shot 2019-02-19 at 5 38 58 pm" src="https://user-images.githubusercontent.com/239220/52990825-da002400-346e-11e9-87f6-281db32fbfdb.png">

Sometimes the point/line follows the mouse when it is moved very slowly. 

Trying to move points on polygons results in similar behaviour.


A feature remains selected, and the point and attached lines follow the mouse pointer, in the unpatched 5.3.0 release.

**Comment by ahocevar** [comment]
@dbrnz Can you please provide a minimal example that shows the issue?

**Comment by dbrnz** [comment]
@ahocevar I haven't (yet) got a minimal example but I can confirm that the issue is to do with having a ``pointerMove`` condition on the Select. In fact I'm wondering if my use of styles are causing visual confusion between having the line selected and having a point showing at the end of an unselected line...

**Comment by bryantqo** [comment]
Still seeing this on 5.3.3. Draw a line from right to left. Drag a new vertex from the middle up. Alt click to delete the starting point.

`Uncaught TypeError: Cannot read property 'minX' of undefined
    at u.update (RBush.js:115)
    at e.handleUpEvent (Modify.js:858)
    at e.handleEvent (Pointer.js:131)
    at e.handleEvent (Modify.js:691)
    at e.handleMapBrowserEvent (PluggableMap.js:931)
    at e (events.js:41)
    at e.dispatchEvent (Target.js:95)
    at e.handlePointerUp_ (MapBrowserEventHandler.js:167)
    at e (events.js:41)
    at e.dispatchEvent (Target.js:95)`

**Comment by li-plaintext** [comment]
I am experiencing the issue as well.
http://openlayers.org/en/latest/examples/modify-features.html?q=modify&mode=raw

To reproduce it on examples as above,
select any of polygons first, holding "shift" and click on the edge of selected polygon, then click on the same point without releasing click, in the meanwhile, moving around your cursor, it raises "minx" issue.

**Comment by bryantqo** [comment]
I was looking at this again late last night. The error is being called because the feature in the event doesn't appear to be in the collection of all features. I am going to do some more digging to try to find out why and where the feature is getting removed.

**Comment by bojanbizjak** [comment]
Same issue on polygon node editing on v5.3.0

**Comment by kevinstadler** [comment]
Simple Polygon modification (dragging of a vertex) still gives me the `Uncaught TypeError: Cannot read property 'minX' of undefined` even in v6.0.1, but only when using the `features` option (with an a priori filled `Collection`). Using the `source` option everything seems to be fine, but I need to provide a custom Collection for my use case.
@ahocevar is it possible that the fix above only works when a full `VectorSource` is provided because of different internal handling of these two options?

**Comment by bojanbizjak** [comment]
Is that fixed? We still use the bryantqo patch in 6.4.3.

**Comment by bryantqo** [comment]
I completely forgot this was a thing. We still have the hack in place on our app.

**Comment by ahocevar** [comment]
Unfortunately noone has provided a reproducible test case. If anyone is able to, please go ahead!

**Comment by bryantqo** [comment]
Sadly I have not been able to produce a reliable test case as its a fairly flaky bug. I will try to dig into my old code to do so but will be dependent on what the boss man says ^_^
