### ISSUE TITLE
ol.geom.Polygon adjacent polygons display incorrectly

### ISSUE THREAD

**Issue by quentin-ol** [openlayers/openlayers#6327]
Adjacent polygons are missing edges:
![screen shot 2017-01-04 at 14 05 27](https://cloud.githubusercontent.com/assets/15086178/21643134/e79566ee-d286-11e6-9c55-28dd4ac0ac8f.png)

code excerpt:
```javascript
polygonOne = new ol.geom.Polygon([[
	[0,0], [0,100], [100,100], [100,0]
]]);
polygonTwo = new ol.geom.Polygon([[
	[100,0] ,[100,100], [200,100], [200,0]
]]);
```
Note that, adding a "space" between the two polygons results in the expected behavior:
![screen shot 2017-01-04 at 14 06 06 1](https://cloud.githubusercontent.com/assets/15086178/21643148/00da7040-d287-11e6-8d53-cf376d2acc3e.png)

code excerpt:
```javascript
polygonTwo = new ol.geom.Polygon([[
	[101,0] ,[101,100], [201,100], [201,0]
]]);
````
 is the jsfiddle that demonstrates the issue: 
http://jsfiddle.net/quentin_ol/y145prfx/10/

**Comment by bartvde** [comment]
your polygons are not valid, the first coordinate needs to get repeated at the end

**Comment by quentin-ol** [comment]
@bartvde thanks. So it means that geometries are described using the GeoJSON specifications (https://tools.ietf.org/html/rfc7946#page-23), i.e. a linear ring.
It'd be nice to add this to the API documentation: http://openlayers.org/en/latest/apidoc/ol.geom.Polygon.html

Note to self: the `getCoordinates` hints us at this.

**Comment by bartvde** [comment]
I agree that a change to the api docs would make sense @quentin-ol are you up for a PR to add this?

**Comment by quentin-ol** [comment]
I'd be happy to contribute.
