### ISSUE TITLE
Drag handler gets called after up handler when pinching

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#6330]
On touch devices (Chrome and Safari on the iPad I tested), we're getting periodic `handleDragEvent_` calls in the `DragPan` interaction *after* the `handleUpEvent_` call in the `PinchZoom` interaction for gestures that don't feel like they include a drag.  This drag is cancelling the animated zoom at the end of a pinch, complicating the fix for #6315 (see #6324 for a partial fix).

It may be that we could increase the tolerance for drag on touch devices.  Or perhaps there is something broken with the order of events (getting `mousemove` after `pointerup`).

**Comment by ahocevar** [comment]
@tsauerwein, could you maybe take a look at this please?

**Comment by tschaub** [comment]
Worked around this in #6444.
