### ISSUE TITLE
pointermove event not work on Chromium 55.0.2883.75

### ISSUE THREAD

**Issue by marcelino-m** [openlayers/openlayers#6334]
pointermove event not work, This work on different version of Firefox and chromium but not in Chromium 55.0.2883.75

Any advice?

**Comment by ahocevar** [comment]
Can you share your code that does not work? Also, make sure to use a recent version (e.g. 3.20.1) of OpenLayers. Old versions are known to break with the introduction of pointer events in Chrome 55.

**Comment by marcelino-m** [comment]
If you try  http://openlayers.org/en/latest/examples/mouse-position.html this no work on  Chromium 55.0.2883.75

**Comment by ahocevar** [comment]
Also see #6242.

**Comment by ahocevar** [comment]
The reason is that the MousePosition control listens to mouse events. It should listen to pointer events instead.

Pull request with a fix welcome.

**Comment by probins** [comment]
works fine on 55.0.2883.103 (CrOS), so I suspect this is a chrome issue that will be fixed as later versions are rolled out on other OSs

**Comment by probins** [comment]
and maybe MousePosition should be renamed PointerPosition :-)

**Comment by ahocevar** [comment]
Renaming the control is something we can do in v4. It is marked stable for 3.x.

**Comment by marcelino-m** [comment]
In my particular case, my code is:
```js
map.on('pointermove', (event: any) => {
    // code...
})
```
This is ok?
On Firefox works, but not in Chromium 55.0.2883.75, 
@probins  you suggest this is a Chromium issue?

**Comment by ahocevar** [comment]
Ok, so we're not talking about the MousePosition control here.

**Comment by ahocevar** [comment]
I can also confirm that both the snippet above an the `mouse-position` example work on Chromium version 55.0.2883.95.

**Comment by probins** [comment]
@marcelino-m 2883.75 is an old version. If you upgrade to the latest release, you should find the problem goes away

**Comment by marcelino-m** [comment]
Ok, thanks @probins.
