### ISSUE TITLE
How to adopt an image to a vector point in OL3 

### ISSUE THREAD

**Issue by asithakavinda** [openlayers/openlayers#6340]
Hi,
i want to visualize a point with a .png icon rather than standard circle or square in Open Layers 3. But i was unable to figure it out. Could anyone help me to fix it?
At the moment i face this following problems; How do we assign a box size for the icon? How to define the  position configuration? Which ol.style. has to be applied?

kind regards
 
Thanks!

**Comment by DavidHequet** [comment]
https://openlayers.org/en/latest/examples/icon.html

**Comment by asithakavinda** [comment]
Thank you very much for the Reply!
This is exactly, what i required.

Thank You again!
