### ISSUE TITLE
ol.Interaction.Draw start point

### ISSUE THREAD

**Issue by nexiss** [openlayers/openlayers#6347]
Is there a way that I can initialize my ol.Interaction.Draw as it was already clicked once by the user? That would allow me to place the center of the circle just passing a point (x,y) to the Interaction forcing the user to draw the figure at the coordinates I want to, just letting the user set the radio.

```
var source = new ol.source.Vector({wrapX: false});
var vLayer = new ol.layer.Vector({
	source: source
});

myMap.addLayer(vLayer);

var drawIn = new ol.interaction.Draw({
	source: source,
	type: "Circle"		
});

myMap.addInteraction(drawIn);
```
How could I at least trigger an event with the coordinates I want to, as the user had clicked on the canvas by himself? I found this:
[http://stackoverflow.com/questions/35944733/open-layers-3-initialize-draw-interaction-with-first-node-on-linestring](http://stackoverflow.com/questions/35944733/open-layers-3-initialize-draw-interaction-with-first-node-on-linestring)
where a user says that using this makes the thing I want to achieve, but its not working:

```
var event = $.Event('click'); //create a click event in your draw method using JQuery 
event.coordinate = [1174072.754460305,332653.94709708635];// set your starting coordinate
draw_interaction.startDrawing_(event);// tell your interaction to start drawing
```

**Comment by fredj** [comment]
You should be able to simulate events with something like:
```js
var pixel = map.getPixelFromCoordinate([1174072, 332653]);
var down = new PointerEvent('pointerdown', {
  clientX: pixel[0],
  clientY: pixel[1],
});
map.getViewport().dispatchEvent(down);
```

(untested)

**Comment by ChouGary** [comment]
i write a sample  place the center to (map.getView().getCenter();)
just draw with drag mouse.
https://jsfiddle.net/r3ts9q7v/

   draw = new ol.interaction.Draw({
      source: source,
      type: 'Circle',
      maxPoints:2,
      freehand:true,
      geometryFunction : function(coordinates, geometry) { 
              if (!geometry) {
                geometry = new ol.geom.Circle(null);
              } 
              var pt1 = map.getView().getCenter();
              var pt2 = coordinates[1];
              var radius = Math.sqrt( (pt1[0]-pt2[0])*(pt1[0]-pt2[0]) + (pt1[1]-pt2[1])*(pt1[1]-pt2[1]) );
              geometry.setCenterAndRadius(pt1, radius); 
              coordinates.splice(0,2); 
              coordinates.push(pt1)
              coordinates.push(pt2)
              return geometry;
            }
    });
    map.addInteraction(draw);
