### ISSUE TITLE
Right-clicking while translating block the interaction

### ISSUE THREAD

**Issue by tchandelle** [openlayers/openlayers#6350]
1. Go to http://openlayers.org/en/v3.20.1/examples/translate-features.html with Chrome or IE11
2. Select a country
3. Drag it around
4. While still holding left-button, right-click
5. Leave context menu by clicking outside the browser page
6. Cursor is still grabbing and it's not possible anymore to move any other features

Step 4 and 5 can also be replaced by going into debug into a translating event

**Comment by tchandelle** [comment]
Another effect due to the same problem can be produced by using the DragZoom. Hold Shift-key and drag a box. Do step 4 and 5. The zoom didn't occurred and the box is still displayed.

![dragbox1](https://cloud.githubusercontent.com/assets/19923657/21844134/ccdf3ac0-d7ed-11e6-84e7-691497222374.gif)

**Comment by ahocevar** [comment]
Pull request welcome.
