### ISSUE TITLE
Highlight active API docs section (was: No API docs for ol.Overlay.Positioning)

### ISSUE THREAD

**Issue by jnachtigall** [openlayers/openlayers#6352]
Steps to reproduce:
1. Not knowing what setPositioning does. So [looking it up](http://openlayers.org/en/latest/apidoc/ol.Overlay.html#setPositioning)
2. Says "how the overlay is positioned relative to its point on the map." with type ol.Overlay.Positioning linking to http://openlayers.org/en/latest/apidoc/ol.Overlay.html#.Positioning (N.B. the `.` (dot) before Positioning)
3. Do not know if the links are just broken or if it is missing docs, but could not find anything about what would be the needed position input for `setPositioning`.
4. Inserting `Positioning` into the topleft "Search Documentation" input box also only leads me to http://openlayers.org/en/latest/apidoc/ol.Overlay.html#.Positioning

In the end I have no idea what `setPositioning` does and how to use it.

**Comment by jnachtigall** [comment]
There's some documentation in this [book](https://books.google.de/books?id=HnFuBgAAQBAJ&pg=PA266&lpg=PA266&dq=setPositioning+overlay&source=bl&ots=PYXsyWwvR5&sig=mvo3Z2ZxQreEqlP_P0fcZPt2r-4&hl=de&sa=X&ved=0ahUKEwj_z5iW6rnRAhWEd1AKHSsjBLwQ6AEIWTAI#v=onepage&q=setPositioning%20overlay&f=false) ;)

![2017-01-11 11_00_27-openlayers 3 _ beginner s guide - thomas gratier paul spencer erik hazzard - g](https://cloud.githubusercontent.com/assets/3307404/21843992/37bf2784-d7ed-11e6-843d-ac41842e057a.png)

**Comment by tchandelle** [comment]
Documentation for `ol.Overlay.Positioning` is at the bottom of the page you linked, under **Type Definitions**

**Comment by tchandelle** [comment]
Indeed, it's not very visible.
We could either add a big empty margin at the bottom of the api so that the anchor is always displayed at the top of the page.
Or highlight the active anchor title.

**Comment by ahocevar** [comment]
Pull request welcome.

**Comment by jnachtigall** [comment]
+1 For Hightlighting the active section, renaming the title appropriately. Maybe just a another background color or just a quick highlight (flash) which fades after 2-3 seconds.

@tchandelle Thanks, indeed I missed it. Still, the API docs does not say what is the default Positioning value is. I'd guess it's 'bottom-left' as it is the first mentioned but might be totally wrong.

**Comment by probins** [comment]
under constructor options: "Default is 'top-left'". There is no default for `setPositioning`, as the assumption is you know what you want to set it to :-)
