### ISSUE TITLE
EPSG:28992 Reprojection is incorrect using TileWMS.

### ISSUE THREAD

**Issue by HeercoGrond** [openlayers/openlayers#6363]
Example at https://jsfiddle.net/66Lo5n69/.

The tiles do not match the other reprojection. Additionally, manually adding EPSG:28992 by doing the following is broken:
`proj4.defs("EPSG:28992","+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.2369,50.0087,465.658,1.9725,-1.7004,9.0677,4.0812 +units=m +no_defs");
    var proj28892 = ol.proj.get('EPSG:28892');
    proj28892.setExtent([483.87, 308912.81, 275904.19, 636380.52])
`

We're using Openlayers 3.19.1, but this problem was put on the backburner since then.

Debugging the code shows that proj28892 is always null, as such I can't set the extent.

**Comment by bartvde** [comment]
you have typos 28892 versus 28992

**Comment by HeercoGrond** [comment]
Right, you are correct, however fixing the typos (changing everything to 28992) still gives me null if I try to do `proj28992 = ol.proj.get('EPSG:28992');` , which is the basis of the problem. It skips over the step it seems.

**Comment by ahocevar** [comment]
In your snippet, you are not including proj4, which is required if you do not have custom transform functions configured. I have updated your fiddle, and everyting looks good there: https://jsfiddle.net/66Lo5n69/1/.

**Comment by HeercoGrond** [comment]
Thank you! I figured out the problem, I wasn't reassigning proj4 to the ol using `ol.proj.setProj4(proj4)`. It works amazingly now.
