### ISSUE TITLE
ol.events classes is undefined in ol.js

### ISSUE THREAD

**Issue by kn-id** [openlayers/openlayers#6366]
```ol.events.Event``` and ```ol.events.EventTarget``` is undefined in ol.js.

**Comment by ahocevar** [comment]
Those are not exported because they are not API. What were you thinking you'd need them for?

**Comment by kn-id** [comment]
I tought they was part of the API because the API docs are available. http://openlayers.org/en/master/apidoc/ol.events.Event.html
http://openlayers.org/en/master/apidoc/ol.events.EventTarget.html

I'm building some controls and use them in my code.

**Comment by kn-id** [comment]
Is there any idea to make them exported in the next release @ahocevar? The problem comes when my code inherits ol.events.Event to create some custom event object and event type. I think this problem is limiting the openlayers users.

**Comment by ahocevar** [comment]
@kn-id If you want to use custom events on OpenLayers, you do not need to extend any classes:
```js
var a = new ol.Observable();
a.on('foo', function(e) {
  console.log(e);
});
a.dispatchEvent({type: 'foo', value: 'bar'});
```

**Comment by kn-id** [comment]
@ahocevar thanks for your answer.
