### ISSUE TITLE
Ol.Source strategy or options getter ?

### ISSUE THREAD

**Issue by moccand** [openlayers/openlayers#6368]
in a webapp i refresh the ol.source.vector by defining a new one with a new URL. But I'm not able to create the new one with the same options than the initial one.

Getting the loading strategy by a dedicated getter (or a more general getter on all options set while creating the ol.source) would help.

**Comment by ahocevar** [comment]
You could also create an options object that you use again for the new source:
```js
var vectorOptions = {
  url: myurl,
  strategy: mystrategy
};
var source = new ol.source.Vector(vectorOptions);
vectorOptions.url = newUrl;
var newSource = new ol.source.Vector(vectorOptions);
```
