### ISSUE TITLE
openlayers poor tiles resolution with cordova

### ISSUE THREAD

**Issue by hishamkaram** [openlayers/openlayers#6369]
openlayers poor tiles resolution 
code : the[ basic example](https://openlayers.org/en/latest/examples/accessible.html) with cordova 
![capture](https://cloud.githubusercontent.com/assets/24391550/21963488/b04b475a-db44-11e6-8ea4-ba9fb0fd309d.PNG)

**Comment by ahocevar** [comment]
This is not OpenLayers's fault. The OSM source uses tiles with a pixel ratio of 1. If you want higher resolution for your tiles, you need a tile source that supports HiDPI devices, like e.g. Bing.
