### ISSUE TITLE
duplicated methods to remove overlay from map

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#6374]
Hi, I'm just thinking there's two methods which seems having the same functionality.

Those are overlay.setMap() and map.removeOverlay(overlay). To remove overlay from the map, we can choose one of the methods. and in that case, we can simply use setMap() as when we add the overlay to the map. 

Could you tell me what is the advantage of having two methods? and what is the difference between two of them?
Thanks,

**Comment by ahocevar** [comment]
The difference between the two is simply that `map.addOverlay()/removeOverlay()` keeps a collection of overlays of the map in `map.getOverlays()`, whereas overlays added/removed with `overlay.setMap()` do not go into that collection.

**Comment by cs09g** [comment]
That is inner logic. But, on the screen, both looks the same. what can be difference by putting into the collection?

**Comment by ahocevar** [comment]
Just your convenience/preference. Choose whatever you prefer.

**Comment by probins** [comment]
`map.getOverlays()` returns the collection, so if you use `setMap` directly, your overlay will not be included. Also collections are observable, so you can add event listeners to them, and you can also itererate through them with `forEach()` etc. OTOH, you may well not need/use these options, and in this case using `setMap` is probably slightly more efficient.

**Comment by probins** [comment]
the same btw applies to controls too

**Comment by cs09g** [comment]
Thanks, @probins @ahocevar
