### ISSUE TITLE
ol.source.Zoomify scaling problem

### ISSUE THREAD

**Issue by JonasGutermuth** [openlayers/openlayers#6384]
There is some problem with height and width of a Zoomify source. I've made a jsfiddle (http://jsfiddle.net/daps01h0/) to show the problem. You can see a Zoomify image surrounded by a red VectorLayer rectangle. If you change the variable "scale" (line 1) to 1/8, 1/4, 1/2, 1, 2, 4, 8, 16, ... it works perfect. With other numbers the VectorLayer is not around the Image.

**Comment by ahocevar** [comment]
Why are you trying to modify the image size in the first place? It has to match the image size that the server provides. When you set a different size, it is expected that you get incorrect results.

**Comment by JonasGutermuth** [comment]
So is it possible to resize the image to for example 50%? To fit different images with defferent imageresolutions to the same vector element

**Comment by ahocevar** [comment]
It is possible, by using different projections. Can you update your fiddle with a 2nd image of different size, then I'll edit it to show you how it's done.

**Comment by JonasGutermuth** [comment]
Thanks a lot. Here is a fiddle with a 2nd image: http://jsfiddle.net/fsrmbk2h/. How can I get the new Image the same width as the first image (in the VectorLayer-Box)

**Comment by ahocevar** [comment]
Actually the Zoomify source currently does not take a projection option. I've submitted #6387 to fix this. See http://jsfiddle.net/fsrmbk2h/2/ for a fiddle that works with the latest debug version by manually setting the private `projection_` property of the source. When #6387 is merged, that won't be necessary any more.
