### ISSUE TITLE
ImageWMS should have its own pixelRatio option

### ISSUE THREAD

**Issue by panutat** [openlayers/openlayers#6385]
Can ImageWMS have its own pixelRatio option so we can specify value independent of the map pixelRatio when hidpi is set to false? Without this the resolution of the WMS layer and the map is always tied. It would be nice to have flexibility in using a lower resolution WMS layer image and scaling up to fit the map. This can be a performance improvement as some WMS services render faster at lower resolution.

**Comment by ahocevar** [comment]
Not configuring the `serverType` or setting `hiDPI: false` is not an option for you? Both will result in images being fetched with a pixel ratio of 1.

**Comment by panutat** [comment]
I would like to use something like 0.5 for the WMS layer itself. We have real-time rendering on our WMS server and it takes a lot less time to render 600x400 image than 1200x800 image. We don't mind losing the resolution in some instances to gain response performance. It would be nice to use the 600x400 over 1200x800 map. Hope I was able to elaborate that well. Thanks.

**Comment by ahocevar** [comment]
Makes sense. Like `ol.source.TileImage` has a `tilePixelRatio` property, `ol.source.Image` (and subclasses) could have a `pixelRatio`. It should be an easy pull request to add that.
