### ISSUE TITLE
Map control inside hidden IFRAME does not work in Firefox

### ISSUE THREAD

**Issue by valtrig** [openlayers/openlayers#6388]
In _Firefox_, when a map is placed inside an `<iframe>` which is initially styled `display: none`, an error occurs and the map is not rendered when the `<iframe>` is subsequently made visible. _Chrome_ on the other hand seems to be handling the situation correctly. You can run [this fiddle](https://jsfiddle.net/btjLf4ej/) in both browsers in order to reproduce the issue.

I've actually tracked the problem down to [Firefox bug 548397](https://bugzilla.mozilla.org/show_bug.cgi?id=548397), which seems to be hitting `ol.Map.prototype.updateSize`. Apparently, in this situation, `getComputedStyle` returns `null` in _Firefox_, causing an error when the `computedStyle` variable is used further down the line.

I'm not familiarised enough with _OpenLayers_ source code in order to suggest a proper fix, but I'm currently working around the issue by simply placing a nullability test on `computedStyle` before using it:
```Javascript
ol.Map.prototype.updateSize = function() {
  var targetElement = this.getTargetElement();

  if (!targetElement) {
    this.setSize(undefined);
  } else {
    var computedStyle = getComputedStyle(targetElement);
    computedStyle && this.setSize([
      targetElement.offsetWidth -
          parseFloat(computedStyle['borderLeftWidth']) -
          parseFloat(computedStyle['paddingLeft']) -
          parseFloat(computedStyle['paddingRight']) -
          parseFloat(computedStyle['borderRightWidth']),
      targetElement.offsetHeight -
          parseFloat(computedStyle['borderTopWidth']) -
          parseFloat(computedStyle['paddingTop']) -
          parseFloat(computedStyle['paddingBottom']) -
          parseFloat(computedStyle['borderBottomWidth'])
    ]);
  }
};
```

This seems to be working and I haven't noticed any side-effects so far, but I surely haven't done any extensive testing.

**Comment by jsalankey** [comment]
I encountered this same problem. My app extends the ol.Map class anyway so I simply overrode the updateSize method to do a `this.setSize(undefined)` if the computedStyle is null.

**Comment by sascha-hendel** [comment]
Had the same proble, even with newest ol 4.x. 
valtrig's solution works for me, too.

**Comment by ahocevar** [comment]
A pull request with the solution outlined above would be welcome.
