### ISSUE TITLE
Calling getPixelFromCoordinate after change:resolution event gives wrong values

### ISSUE THREAD

**Issue by jgalrito-i9** [openlayers/openlayers#6389]
I made a plunkr with a call to getPixelFromCoordinate right after change:resolution and with a setTimeout 500ms after. I suppose this happens because of the zoom animation. Is there no way to catch the final resolution after changing it?

https://plnkr.co/edit/w8KKF2eGYdEz8vDLIgI1

**Comment by tchandelle** [comment]
With the [`moveend` event](http://openlayers.org/en/latest/apidoc/ol.MapEvent.html#event:moveend) ?

**Comment by jgalrito-i9** [comment]
Gotcha. Shouldn't it be called viewportchangeend or something? The name looks a bit misleading.
