### ISSUE TITLE
Custom fill in Vector features with unclosed Polygon geometries

### ISSUE THREAD

**Issue by jgalrito-i9** [openlayers/openlayers#6391]
From 3.19.0 onwards, a custom fill in unclosed Polygon geometries such as:
```
new ol.geom.Polygon([[
        [-10, 0],
        [-7, 7],
        [7, 7],
        [10, 0],
        [7, -7],
        [-7, -7]
      ]])
```
causes the feature to be filled without the last vertex. However, this does not happen with the default style.

https://plnkr.co/edit/w8KKF2eGYdEz8vDLIgI1

**Comment by ahocevar** [comment]
Starting with 3.19, unclosed polygons are invalid, and you have to expect unexpected results 😄.
