### ISSUE TITLE
Ol.interaction.draw issue

### ISSUE THREAD

**Issue by sskram** [openlayers/openlayers#6392]
Enabling freehand in Ol.interaction.draw disables all the possible motions like zoom,pan through mouse scroll and drag. Calling setZoom function using the keys + , - works. 

Openlayer v3.20.1 
Build is taken from http://openlayers.org/en/v3.20.1/build/ol.js

**Comment by ahocevar** [comment]
This is not a bug, it's a necessity. How would you want to draw freehand without a modifier key while still being able to zoom and pan? By default, when `freehand: true` is not configured, holding the shift-key will still enable freehand mode. Maybe that's what you are looking for then.
