### ISSUE TITLE
Two problems:  heatmapLayer.setSource and heatmap colors added

### ISSUE THREAD

**Issue by homeandr777** [openlayers/openlayers#6394]
First Heatmap colors added: 
I explain in an example: you see the pictures, and that way is working openlayers heatmap, the overlapped colors are added. So I need for example if 1 color point has the maximum weight, that after zoom in the overlapped area with 2  color point, has the same color that has 1 set 
![bxzuo](https://cloud.githubusercontent.com/assets/21321724/22186899/a98a6be4-e0fd-11e6-95e3-cc8dab170c80.jpg)

Second problem heatmapLayer.setSource is not cleaned
If I call the setSource features and every time I add new source the old source is not cleaned from the resources. one Is calculated another  R-tree and every indexing growing extremly up
So how can I clean the source and after cleaning add the source.

**Comment by tomasjuran** [comment]
I'm having the same problem about the overlapping colours. Any solutions yet?
