### ISSUE TITLE
Is trac/osgeo data still needed ?

### ISSUE THREAD

**Issue by strk** [openlayers/openlayers#6395]
See https://trac.osgeo.org/osgeo/ticket/1855 - please speakup to get a backup data or confirm removal is ok with you. Thanks.

**Comment by bartvde** [comment]
@strk I discussed with @ahocevar and we think a backup would be fine.
Any chance there is a backup of our blog as well, it seems we lost the blog around a year ago when OSGeo migrated servers. TIA.

@openlayers/core please speak up now if you don't agree. TIA

**Comment by strk** [comment]
@bartvde please request the backup on the trac ticket referenced in the issue description, and file another ticket for the blog backup (I've no idea where it could be)

**Comment by bartvde** [comment]
I will if I remember my osgeo id credentials ;-)

**Comment by strk** [comment]
@bartvde if you don't there's a new "password forgot" service (see https://www.osgeo.org/osgeo_userid)

**Comment by bartvde** [comment]
thanks that worked. Closing this one.
@openlayers/core please reopen if you disagree.
