### ISSUE TITLE
StyleFunction bug with ol.Layer.Vector in OpenLayers >= 3.19.1

### ISSUE THREAD

**Issue by pedros007** [openlayers/openlayers#6401]
After upgrading from OpenLayers-3.15.1 to 3.19.1, one of my `ol.Layer.Vector` layers styled with a `styleFunction` started displaying artifacts.  I expected two yellow squares displayed, but I get one yellow square and one triangle.  [Here's a jsfiddle](https://jsfiddle.net/pschmitt/wt8af29h/).  

![artifact](http://imgur.com/xJeri1f.png)

As suggested by #6061, the artifact goes away if I add a stroke.  Unlike #6061, I think the geometries for my polygons are valid.

**Comment by ahocevar** [comment]
Should be fixed with #6364. That fix will be in the next release and is in master already.
