### ISSUE TITLE
ol.interaction.Select and feature movement

### ISSUE THREAD

**Issue by oufresh** [openlayers/openlayers#6408]
Hello,

I'm currently using the ol.interaction.Select to change the feature style when the mouse is hover a feature:

	hoverInteraction = new ol.interaction.Select({
		filter: _ClusterStyleHoverFilter,
  		condition: ol.events.condition.pointerMove,
  		style: _ClusterStyleHover
	});
	map.addInteraction(hoverInteraction);

_ClusterStyleHoverFilter is a function that filter the correct layer and the features in a cluster: it returns true if the feature is not clustered.

_ClusterStyleHover is the function that create the style for the "hover" effect different from the style function we use for the cluster.

My problem is when the feature changes its position. If the cursos is hover a feature and it changes the position the feature with the new position is drawn becuse the map is refreshed with changed() function of the layer but the feature in the old position still reamain on the map under the cursor with the hover style. The result is that I have the feature drawn in the new position and the same feature drawn in the old position with the hover style.
I wondering if there is a method to "invalidate" the hover style when, in this case, the feature changes its position or something else appens.
The movement is simply done by changing the coordinates of the geometry of the feature and refresh the map. Every update is done in an asyncronus way and position are updated by stomp client listening on an ActiveMq Topic.
Can you please help me?

Thanks for all.

Best regards

**Comment by ahocevar** [comment]
You may want to provide a JSFiddle to show your issue in a live example.

**Comment by oufresh** [comment]
Hello this is the link where you can find the example

https://jsfiddle.net/oufresh/ytc26fju/

Click the button StartMove and go over the feature with the mouse. Wait for the feature to move leaving the mouse in the same position. When the feature go up you can see the feature changing position but under the mouse the the feaure drawn before still remain.
Note: I used only one feaure so the cluster style function is used to draw only this feature. I simplified it.

Thanks a lot

**Comment by lucas-bremond** [comment]
Same question here, any elegant solution to this problem?

**Comment by oufresh** [comment]
Hello. I hadn't worked on ol for a year but in my last solution I didn't use the addInteraction API.
I set a property of the faeture when the mouse is hover searching the faeture near the mouse coordinates. Then in the style function I fill the circle with different colours depending on the property. That worked form.
You might check with the new version of ol.
