### ISSUE TITLE
feature is not passed to style function when set via .setStyle()

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#6411]
I'm using style functions. They work well when set on a layer level.

However, when I'm trying to set styles to individual features using `feature.setStyle(stylefunction)`, it doesn't work. The problem is that the feature is not passed on to the style function, only the resolution.

So normally it's calling a `styleFunc(feature, resolution)` but when set via `.setStyle()` it's calling `styleFunc(resolution)`.

version: 3.20.1

**Comment by ahocevar** [comment]
This is intentional and documented. See http://openlayers.org/en/latest/apidoc/ol.html#.FeatureStyleFunction. The feature will be `this`.

If you think the documentation could be improved here, please submit a pull request.

**Comment by hyperknot** [comment]
But this way how can I use the same function for both cases?

I cannot image but a very ugly hack using generic variable names (a, b, c)
and somehow rewriting them to feature, resolution based on if "this" is
present.

**Comment by ahocevar** [comment]
You are right. We should discuss whether we want a breaking change that `ol.Feature` uses the same style function signature as `ol.layer.Vector`.

In the meantime, you can do something like this:
```js
function featureStyleFunction(resolution) {
  return layerStyleFunction(this, resolution);
}

**Comment by marcjansen** [comment]
I agree this is a bit odd API-wise. but a change here would affect nearly all users,  I guess.

**Comment by ahocevar** [comment]
Actually we can make this change without breaking existing applications. Pull request to come.

**Comment by hyperknot** [comment]
Wow it looks great. I didn't know about function.length, especially that
it's been there since JavaScript 1.1!
