### ISSUE TITLE
map.js sets constants in different namespace

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers#6414]
Map sets 3 constants on the ol namespace https://github.com/openlayers/openlayers/blob/master/src/ol/map.js#L47-L85, something which won't work in a modular structure. I don't know whether there are other similar examples elsewhere, but for this to work they would need to be defined in index.js, not map.js. In this case, it looks like they're only used in map.js, so I'm thinking it would be better if they were defined in ol3 in the `ol.Map` namespace. When these are converted to ES modules, OTOH, they can be simple vars, as can `createOptionsInternal()`, as none of these need to be exported.

**Comment by fredj** [comment]
The es6 modules migration should have fixed this issue.
