### ISSUE TITLE
Version 3.20.0 broke something with minZoom

### ISSUE THREAD

**Issue by ogo-adp** [openlayers/openlayers#6415]
Please have a look at this jsfiddle which runs with version 3.20.1 : https://jsfiddle.net/202a443s/1/

In this sample I have set "minZoom" to less than zero on ol.View :
- with version 3.20.0 and upper :  if you zoom out and if zoom goes under 0, panning the map will become slow and sluggish. The more you zoom under 0, the more the map will be slow when panning.
- with version 3.19.1 : everything is smooth for all zooms.

Please also note that once the map goes under zoom 0, it will also become sluggish when panning when zoom comes back over 0, but I could not demonstrate this with this sample. This is however the behavior wee see in our app which use a custom tile source (I can't do a Jsfiddle with that). Somehow our app cannot run smoothly at all with versions > 3.19.1 because of this.

**Comment by ahocevar** [comment]
This is because we switched back to using an intermediate canvas for tile layer rendering, like we did before v3.14.0. The reason is because the intermediate canvas is always created for a zoom level that is available for the tile source. Which will be 0 in your example, even if the zoom level is -10.

Out of curiosity: why are you using negative zoom levels? I'm surprised it works at all, and I could not think of a use case why someone would want that.

**Comment by ogo-adp** [comment]
Our map show an airport (a tile map).

This map is surrounded by radar circles which go very var outside the visible tiled map.

We need to be able to zoom out very far out of the bounds of the tiled map to be able to see all radar circles (for planes in approach or departing).

Sorry for me bad english, hope your understand what I mean

**Comment by ogo-adp** [comment]
Was this change the source of the behaviour I see ? 
https://github.com/openlayers/openlayers/pull/6082

I can also confirm that event without the minZoom problem, our app seems less snappy with version 3.20.1 than with 3.19.1. This is very subjective and hard to measure (we have two targets : chrome on Windows, and IOS 10)

**Comment by ahocevar** [comment]
Yes, #6082 was the change that caused the behaviour you are seeing. Does your application have multiple tile layers? If so, that would explain the reduced snappiness. And we have a plan to improve that in the future.

Regarding the negative zoom levels, you should probably change the tile grid setup of your tile layers, and modify your application to not use negative zoom levels - I still consider negative zoom levels an ugly hack, and we should probably forbid zoom levels < 0.

**Comment by ogo-adp** [comment]
Thank for your response :) I also forgot to tell you in my first question than I find OL to be a fantastic framework for map applications ...

We use only one tile layer. We need two zoom steps less than the minimum zoom level. As the minimum zoom level is 0 or one, the "real" minimum goes under 0. If the tile map would have a minimum zoom at 2 would it work to go down to 0 ? In fact the problem is caused by the zoom going under 0 or the zoom being lower than the minimum zoom level of the tile source ?

Moreover I suspect there may be a bug in the new implementation because :
- if I zoom lower than the minimum zoom level of the tile source, I see in the profiler that the application is spending a lot of time (something like 40%) in "clearRect". Maybe OL is trying to clear an "gigantic" surface (just a guess ?)
- if I zoom lower than the minimum zoom level, the map stutters, but will continue to stutter even if I zoom back to normal zoom levels. I was not able to demonstrate this in my jsfiddle sample, but this is what we see in our app. Any clue of what could be the cause of this ?

**Comment by ogo-adp** [comment]
I've made a test in our app. If I change zoom levels used by tile layers to be for example 2 to 10 (instead of 2 to 8) and set minZoom to 0, I also have the problem (sluggishness forever at soon as I zoom out to level 0). So zoom does not need to be negative at all to have this problem. In this case, at zoom 0 a tile is displayed at normal size (256pixels), not reduced at all.

**Comment by ahocevar** [comment]
Please provide a JSFiddle that shows the issue, instead of letting us guess what's going on in your application. I'd like to close this issue and create new tickets for the underlying problem(s), but we need to be able to identify them.

**Comment by ahocevar** [comment]
> * if I zoom lower than the minimum zoom level of the tile source, I see in the profiler that the application is spending a lot of time (something like 40%) in "clearRect". Maybe OL is trying to clear an "gigantic" surface (just a guess ?)

This is correct. It results from the oversampling of the tile layer and the large tile ranges.

> * if I zoom lower than the minimum zoom level, the map stutters, but will continue to stutter even if I zoom back to normal zoom levels. I was not able to demonstrate this in my jsfiddle sample, but this is what we see in our app. Any clue of what could be the cause of this ?

Maybe you are using OpenLayers v3.13.1 or older in your app? In these old versions, the canvas was never shrunk once its size was increased.

**Comment by ogo-adp** [comment]
We were using version 3.19.1 before having this problem.

I think I have found were the problem is, and you can somehow reproduce it with the jsfiddle given in my first post. You have to : 
- use chrome (tested with v56 only on windows)
- make the map very big on screen before running the sample
- zoom out under 0. It will become very sluggish
- zoom in again. You will see that it stays somehow sluggish, but it will only happen if the map is big on screen (and probably if your pc is not very fast)

I fiddled with the OL code, and found this in ol/renderer/canvas/tilelayer.js, line 179 and next :
` if (canvas.width != width || canvas.height != height) {`
`      canvas.width = width;`
`      canvas.height = height;`
    } else {
     ` context.clearRect(0, 0, width, height);`
}

The problem is that this code can create gigantic canvas, and chrome doesn't like that at all (or my gpu or both I don't know). Safari on IOS does not seem to be affected by that.

For example on my screen which is 1920x1200 (HD screen), i get this :
- at zoom 0 : 2304x1280
- at zoom -4 : 7936x5120 which is more than 17x the size of the screen. Once chrome has created a canvas of this size it seems like it will stay sluggish forever.

If i replace the code with this one (which is incorrect and stupid but just to explain my point) :
` if (canvas.width != width || canvas.height != height) {`
   `   canvas.width = Math.min(width,1920);`
 `     canvas.height = Math.min(height,1200);`
   `   console.log ('new canvas  ' + width + ' ' + height);`
  `  } else {`
   `  context.clearRect(0, 0,  Math.min(width,1920), Math.min(height,1200));`
    `}`
Then the map is displayed incorrectly but flies again not matter what I do with the zoom.

Hope it will help you (and sorry again for my poor wording in english)

**Comment by ogo-adp** [comment]
We were using version 3.19.1 before having this problem.

I think I have found were the problem is, and you can somehow reproduce it with the jsfiddle given in my first post. You have to : 
- use chrome (tested with v56 only on windows)
- make the map very big on screen before running the sample
- zoom out under 0. It will become very sluggish
- zoom in again. You will see that it stays somehow sluggish, but it will only happen if the map is big on screen (and probably if your pc is not very fast)

I fiddled with the OL code, and found this in ol/renderer/canvas/tilelayer.js, line 179 and next :
` if (canvas.width != width || canvas.height != height) {`
`      canvas.width = width;`
`      canvas.height = height;`
    } else {
     ` context.clearRect(0, 0, width, height);`
}

The problem is that this code can create gigantic canvas, and chrome doesn't like that at all (or my gpu or both I don't know). Safari on IOS does not seem to be affected by that.

For example on my screen which is 1920x1200 (HD screen), i get this :
- at zoom 0 : 2304x1280
- at zoom -4 : 7936x5120 which is more than 17x the size of the screen. Once chrome has created a canvas of this size it seems like it will stay sluggish forever.

If i replace the code with this one (which is incorrect and stupid but just to explain my point) :
` if (canvas.width != width || canvas.height != height) {`
   `   canvas.width = Math.min(width,1920);`
 `     canvas.height = Math.min(height,1200);`
   `   console.log ('new canvas  ' + width + ' ' + height);`
  `  } else {`
   `  context.clearRect(0, 0,  Math.min(width,1920), Math.min(height,1200));`
    `}`
Then the map is displayed incorrectly but flies again not matter what I do with the zoom.

Hope it will help you (and sorry again for my poor wording in english).

**Comment by ogo-adp** [comment]
Changing the code like this does indeed fix the issue completely for us (correct rendering, and normal performance) :
    var widthC = Math.min(width, 2 * size[0]);
    var heightC = Math.min(height, 2 * size[1]);
    if (canvas.width != widthC || canvas.height != heightC) {
      canvas.width = widthC;
      canvas.height = heightC;
    } else {
     context.clearRect(0, 0, widthC, heightC);
    }

Intuitively I don't get how the intermediate canvas would need to be more than two times bigger than the viewport when zoom > 0. When zoom <= 0, when only one tile can be displayed, maybe something could be done to use a very small canvas ? Just my two cents.

The new PinchZoom default behavior also allow to zoom out to very low (and negative) values ...

**Comment by ahocevar** [comment]
Good suggestions, thanks @ogo-adp. See #6439 for a fix of your negative zoom levels problem, and an improvement for sluggish panning/zooming in general.
