### ISSUE TITLE
Optimization proposal for overlays

### ISSUE THREAD

**Issue by ogo-adp** [openlayers/openlayers#6416]
When a map contains a lot of overlays, panning could be made faster by implementing updateRenderedPosition() (in overlay.js) a bit differently. 

Currently it does position the overlay using top/left style properties. But by using translate3d() css transform, it could be made faster because this transform does use the gpu. Other mapping frameworks make use of this trick.

Here is a very crude implementation using translate3d() to play with it :

`ol.Overlay.prototype.updateRenderedPosition = function (pixel, mapSize) {`
     `  var offset = this.getOffset();`
         `   var left = Math.round(pixel[0] + offset[0]);`
         `   var top = Math.round(pixel[1] + offset[1] - mapSize[1]);`
          `  var newTransform = 'translate3d(' + left + 'px,' + top + 'px,0px)';`
       `     var style = this.element_.style;`
           ` if (style.transform !== newTransform)`
           `     style.transform = newTransform;`
          `  this.setVisible(true);`
`        };`

**Comment by ahocevar** [comment]
Just out of curiosity: what is your reason to prefer `ol.Overlay` objects and not use `ol.layer.Vector`?

**Comment by ogo-adp** [comment]
We use ol.overlay to generate "stickers" for moving objects (which are based on on.layer.Vector). We need HTML/CSS to display mixed text, icons, colors (and probably some CSS animations in the near future). It would be very hard to do this with only ol.layer.Vector.

**Comment by ahocevar** [comment]
Pull request welcome. But please ensure that this also works on IE9.
