### ISSUE TITLE
Rotated map distorts gradually

### ISSUE THREAD

**Issue by norric** [openlayers/openlayers#6418]
When rotating a map using certain angles, an offset problem is introduced on the canvas. This offset subsequently increases slowly for each render.

This issue was initially discovered in an application with an arbitrary rotation and a number of features changing position every second. It would then take about 30 min before the issue started to appear.

In the jsfiddle below, I managed to reproduce the problem using a very basic map and a loop around renderSync().

By adding a dark background and opacity to the tile layer, the problem presents itself using thin, light lines appearing on the left and top edges of the canvas. It happens after about one minute.

![map offset](https://cloud.githubusercontent.com/assets/2145089/22432684/02a0160c-e716-11e6-9c9d-2c2950f91a59.gif)
See animated gif of an initial period. It just keeps getting worse after that.

Some observations:
- It is reset by resizing the window
- It only happens on some rotations
- It can be reproduced on all releases since 3.15.0

https://jsfiddle.net/norric/ke6p0arb/

**Comment by ahocevar** [comment]
It would be good to know the change exactly that introduced this problem. To find out, you could do a `git bisect` with a local copy of OpenLayers.

**Comment by norric** [comment]
Hi Andreas,

Bisect tells me that https://github.com/openlayers/openlayers/pull/5024/commits/600c139a617cdb7ad24194eb6b40677ad865c631 is the one.

**Comment by ahocevar** [comment]
Thanks for the investigation @norric. So #5024 was responsible for this change. Do you think you'd be able to provide a fix, without reverting 600c139? If so, we'd gladly accept a pull request.

**Comment by norric** [comment]
It looks to me like https://github.com/openlayers/openlayers/commit/600c139a617cdb7ad24194eb6b40677ad865c631 did not actually introduce the bug itself, but rather make it show.

This can be seen just by applying the first part of the diff:
```diff
-  var width = frameState.size[0] * pixelRatio;
-  var height = frameState.size[1] * pixelRatio;
-  this.canvas_.width = width;
-  this.canvas_.height = height;
+  var width = Math.round(frameState.size[0] * pixelRatio);
+  var height = Math.round(frameState.size[1] * pixelRatio);
+  if (this.canvas_.width != width || this.canvas_.height != height) {
+    this.canvas_.width = width;
+    this.canvas_.height = height;
+  } else {
+    this.context_.clearRect(0, 0, width, height);
+  }

```
Before this change, the canvas was cleared by setting the dimensions, which means the drawing state got reset as well. When using `clearRect`, the state is kept. This also explains why the distortion disappears after resizing the window, as I mentioned earlier.

I have not managed to find what is causing this "bad drawing state", but I've made some observations. 

This part of the code has changed quite a bit up until now but by looking at the old version first. I've tried to encapsulate code in `save`/`restore` calls just to find out where the bad state is "leaking" from (I'm not suggesting to add them, I know they are avoided for performance reasons).

By wrapping the rotation operations like below, the bug does _not_ appear:
```diff
if (rotation) {
  this.context_.translate(width / 2, height / 2);
+ this.context_.save();
  this.context_.rotate(rotation);
  this.context_.drawImage(this.renderCanvas_,
      Math.round(pixelExtent[0]), Math.round(pixelExtent[1]));
  this.context_.rotate(-rotation);
+ this.context_.restore();
  this.context_.translate(-width / 2, -height / 2);
}
```

By moving them one step in to wrap the `drawImage` instead, the bug _does_ appear:

```diff
if (rotation) {
  this.context_.translate(width / 2, height / 2);
  this.context_.rotate(rotation);
+ this.context_.save();
  this.context_.drawImage(this.renderCanvas_,
      Math.round(pixelExtent[0]), Math.round(pixelExtent[1]));
+ this.context_.restore();
  this.context_.rotate(-rotation);
  this.context_.translate(-width / 2, -height / 2);
}
```

That should indicate there is a problem with the counter-rotation at the end, right? But I cannot see any issue there.

I've made the same tests on the latest version of the code and reached the same conclusion by testing the `ol.render.canvas.rotateAtOffset` calls.

Any ideas? I'm suspecting a browser bug here. Especially since I have not managed to reproduce it in Firefox, but only Chrome and Safari, on multiple platforms.

**Comment by tschaub** [comment]
I'd be curious to know if there was a measurable performance impact if we do this:
```js
if (rotation) {
  this.context_.save();
  this.context_.translate(width / 2, height / 2);
  this.context_.rotate(rotation);
  this.context_.drawImage(this.renderCanvas_,
      Math.round(pixelExtent[0]), Math.round(pixelExtent[1]));
  this.context_.restore();
}
```

**Comment by ahocevar** [comment]
Good call @tschaub. This does not have a measurable performance impact, as we don't have anything except a transform on the context stack. Probably it's even faster than applying transforms. I created #6477. @norric, can you please verify that #6477 fixes the issue for you?

**Comment by norric** [comment]
I can confirm that https://github.com/openlayers/openlayers/pull/6477 fixes the issue.

Thanks a lot!
