### ISSUE TITLE
Add lineDotDash option to ol.style.Stroke

### ISSUE THREAD

**Issue by yaugenka** [openlayers/openlayers#6420]
It would be nice to have an extra lineDotDash option in ol.style.Stroke for dot-dash pattens.
Type Array.<number> | undefined.
The array would hold 4 values:
1. line width
2. width between elements (lines or dots)
3. number of consecutive dashes
4. number of consecutive dots

**Comment by fredj** [comment]
[ol.style.Stroke](http://openlayers.org/en/latest/apidoc/ol.style.Stroke.html) already has a `lineDash` option; what would this new option provide?

**Comment by yaugenka** [comment]
With lineDash you draw a patten like "- - -"
With lineDotDash you would be able to draw like "- . - . -" (with dots on the same level as dashes).

**Comment by ahocevar** [comment]
With `lineDash` you get anything you want, depending on your dash array. For a dash-dotted line, try a dash array like `[9, 3, 3, 3]`.
