### ISSUE TITLE
pinchzoom issue

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#6423]
- open http://openlayers.org/en/master/examples/simple.html on a mobile device
 - pinch zoom
 - on pinch release, the intermediate tiles are displayed

**Comment by fredj** [comment]
```
dec39151a01dbca5aafa9178d73520a863b70980 is the first bad commit
commit dec39151a01dbca5aafa9178d73520a863b70980
Author: Thomas Chandelle <thomas.chandelle@1spatial.com>
Date:   Wed Jan 11 10:21:21 2017 +0100

    Consider pointerdown only if the last pointerup has been emitted

:040000 040000 f3aa493faa6a4e8de125177e3509b62f9ca40486 bddb78f479f2b83800f215e2bed2ae76c5b43dbb M      src
```

**Comment by tchandelle** [comment]
Indeed I can reproduce the issue, Sorry about that, forgot to test it back then.
This commit solved #6350.

**Comment by fredj** [comment]
```diff
diff --git a/src/ol/interaction/pointer.js b/src/ol/interaction/pointer.js
index 048ff27..068b32b 100644
--- a/src/ol/interaction/pointer.js
+++ b/src/ol/interaction/pointer.js
@@ -187,8 +187,7 @@ ol.interaction.Pointer.handleEvent = function(mapBrowserEvent) {
     if (mapBrowserEvent.type == ol.MapBrowserEventType.POINTERDRAG) {
       this.handleDragEvent_(mapBrowserEvent);
     } else if (mapBrowserEvent.type == ol.MapBrowserEventType.POINTERUP) {
-      this.handleUpEvent_(mapBrowserEvent);
-      this.handlingDownUpSequence = false;
+      this.handlingDownUpSequence = this.handleUpEvent_(mapBrowserEvent);
     }
   } else {
     if (mapBrowserEvent.type == ol.MapBrowserEventType.POINTERDOWN) {
```

fixes the issue but I haven't tested #6350

**Comment by tchandelle** [comment]
It solved both issues. But it introduces a new one ...
1. Go to http://localhost:3000/build/examples/translate-features.html
2. Select a country, move it, it works
3. Move it again, it pan the map instead
4. Move it again, it works again
5. GOTO 3

**Comment by tchandelle** [comment]
````diff
diff --git a/src/ol/interaction/dragpan.js b/src/ol/interaction/dragpan.js
index 30cb906..80867c4 100644
--- a/src/ol/interaction/dragpan.js
+++ b/src/ol/interaction/dragpan.js
@@ -93,7 +93,7 @@ ol.interaction.DragPan.handleDragEvent_ = function(mapBrowserEvent) {
 ol.interaction.DragPan.handleUpEvent_ = function(mapBrowserEvent) {
   var map = mapBrowserEvent.map;
   var view = map.getView();
-  if (this.targetPointers.length === 0) {
+  if (this.targetPointers.length <= 1) {
     if (!this.noKinetic_ && this.kinetic_ && this.kinetic_.end()) {
       var distance = this.kinetic_.getDistance();
       var angle = this.kinetic_.getAngle();
`````

Solved the three issues, pass tests. But I'm not confident about it.

**Comment by fredj** [comment]
See https://github.com/openlayers/openlayers/compare/master...fredj:primaryAction

This revert the fix for #6350 and add a condition to `ol.interaction.Translate` to discard not "primary action" events. (left click is a primary event, middle and right click aren't).

The same should be done for the zoom box

**Comment by tchandelle** [comment]
It doesn't work neither. `handleDownEvent_` never receive right click events.

**Comment by tschaub** [comment]
@fredj I like the look of your changes in https://github.com/openlayers/openlayers/compare/master...fredj:primaryAction.  I couldn't tell if @tchandelle's [comment above](https://github.com/openlayers/openlayers/issues/6423#issuecomment-276373192) was related to that or to an alternative fix that didn't work.

I'm proposing #6445 as a fix for pinch zooming.  It feels to me like allowing pointer interactions to stop propagation of drag and up events would help the situation.  And it looks like pointer interactions would benefit from the primary action condition.  But if #6445 fixes things for the release, I think it is worth getting in.
