### ISSUE TITLE
GeoJSON in EPSG:25832 isn't drawn at the right location

### ISSUE THREAD

**Issue by 503e2** [openlayers/openlayers#6425]
I have the following GeoJSON:
`
{
	"type": "FeatureCollection",
	"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::25832" } },               
	"features": [{ 
    	"type": "Feature", 
      "geometry": { 
      	"type": "Point", 
        "coordinates": [ 434843.551471853628755, 5791841.897497965022922 ] 
      } 
   }]
}
`

This should lie in Germany like in the following screenshot:
![bildschirmfoto_2017-01-31_16-59-58](https://cloud.githubusercontent.com/assets/5585945/22472981/8f392308-e7d7-11e6-9857-0aed7e26f9ca.png)
But OpenLayers puts it into France:
![unbenannt](https://cloud.githubusercontent.com/assets/5585945/22473101/e687ef90-e7d7-11e6-93ca-8480645e7323.jpg)

Here is a [JSFiddle-Testcase](https://jsfiddle.net/e6f0bun3/)

This happens with OpenLayers 3.20.1 and pro4js 2.3.17
I think it is a OpenLayers problem because just transforming the coordinates from EPSG:25832 to EPSG:3857 with proj4js gives the correct result ([JSFiddle](https://jsfiddle.net/7whq8umq/))

**Comment by ahocevar** [comment]
This is a usage error on your end. When transforming features this way with `ol.format.GeoJSON`, you also need to provide the correct `featureProjection`. Updated fiddle: https://jsfiddle.net/e6f0bun3/1/.
