### ISSUE TITLE
.fit() doesn't work properly for circle geometries

### ISSUE THREAD

**Issue by glenselle** [openlayers/openlayers#6428]
We have logic in our application to center features within the map's view. However, we've noticed that if we have a feature that's a circle geometry, the view's `.fit()` method doesn't correctly center the view on the feature. Instead it appears off-center. The below JSfiddle shows this happening.

```
var circle = new ol.Feature({
  geometry: new ol.geom.Circle([0,0], 5000),
  name: 'My Circle'
})

var map = new ol.Map({
  target: 'map',
  layers: [
    new ol.layer.Tile({
      source: new ol.source.OSM({
        layer: 'osm'
      })
    }),
    new ol.layer.Vector({
      source: new ol.source.Vector({
        features: [circle]
      })
    })
  ],
  view: new ol.View({
    center: [-11000000, 4600000],
    zoom: 4
  })
});

map.getView().fit(circle.getGeometry(), map.getSize())
```

http://jsfiddle.net/rLb2hj2d/

**Comment by Patchez** [comment]
The `flatCoordinates` for the ol.geom.Circle in the JSFiddle are [0, 0, 5000, 0] which might explain the extent we are getting. 
https://github.com/openlayers/openlayers/blob/master/src/ol/view.js#L722

**Comment by ahocevar** [comment]
This is indeed a bug, thanks for reporting! Pull request with a fix welcome.
