### ISSUE TITLE
map blurry 

### ISSUE THREAD

**Issue by rezvanshiravi** [openlayers/openlayers#6430]
hi 
Hi,
I have LayerTile.
When I publish that Layer in OL 3, quality of my map view is low (blured, ).
But same layer when I published using OPENLAYERS 2, quality is good.

in both I have used TileWMS as it is published in GeoServer.
I try solution that was exist but not solved my problem.
My code attached below. if I have error code please inform me.
Thanks :)

var projection = new ol.proj.Projection({
	  code: 'EPSG:32639',
	  units: 'm', 
	});
	ol.proj.METERS_PER_UNIT=90;

var map = new ol.Map({
	
	  controls: ol.control.defaults({
          rotate: false
        }),
	  target: 'map',
	  interactions:  ol.interaction.defaults().extend([keyboardPan, keyboardZoom]),
		keyboardEventTarget: document
	});

var BaseLayer_view=new ol.View({
		center: Base_center,
		zoom:0,
		minZoom:0,
        maxZoom:9,
		extent:Base_bounds,
        maxResolution: 40.65,	
        projection:projection		
	});
	var BaseLayer = new ol.layer.Tile({
	
	  visible: true,
	
	  source: new ol.source.TileWMS(({
		projection:projection,
		url: 'http://localhost:8080/geoserver/wms',
		params: {'LAYERS': '', 'TILED': true, 'VERSION': '1.3.0',  'CRS': 'EPSG:32639'},
		
		})),
		serverType: 'geoserver',
		opacity: 1
	  });

**Comment by ahocevar** [comment]
You need to make sure your view resolutions match your tile grid resolutions. I'd do something like this:
```js
var source = new ol.source.TileWMS({
  projection: projection,
  tileGrid: ol.tilegrid.createXYZ({
    extent: Base_bounds,
    maxZoom: 9
  }),
  url: 'http://localhost:8080/geoserver/wms',
  params: {LAYERS: '', TILED: true}
});

var view = new ol.View({
  projection: projection,
  resolutions: source.getTileGrid().getResolutions(),
  extent: Base_bounds,
  center: Base_center,
  zoom: 0
});
```

**Comment by rezvanshiravi** [comment]
thanks very lot
