### ISSUE TITLE
pinchzoom does not seem to respect minZoom and maxZoom anymore

### ISSUE THREAD

**Issue by ogo-adp** [openlayers/openlayers#6433]
Sorry if it already has been reported.

Repro here with and ipad or iphone : https://jsfiddle.net/3uvvzh8m/
With current version (3.20.1), you can zoom in and out as much as you want when pinching which does not respect min and max zoom constraints.
With version 3.19.1 you could not pich outside of min and max zoom constraints.

**Comment by ahocevar** [comment]
This changed with v3.20.0. See the [Release Notes](https://github.com/openlayers/openlayers/releases/tag/v3.20.0). To get the previous behaviour, configure your map with custom interactions like this:
```js
        interactions: ol.interaction.defaults({pinchZoom: false}).extend([
          new ol.interaction.PinchZoom({
            constrainResolution: true // force zooming to a integer zoom
          })
        ]),
```

**Comment by ogo-adp** [comment]
Thanks for your response. With this modification, it works most of the time, but I'm still able to pinch past min and maxZoom by pinching one zoom step at a time. So the constraint is still not always respected 

jsfiddle here : https://jsfiddle.net/1pnk30rL/

Would it be possible to reopen this issue ?

**Comment by ahocevar** [comment]
Maybe the same issue as #6330.

**Comment by tschaub** [comment]
See #6444 for a proposed fix.
