### ISSUE TITLE
When ol.source.VectorTile.tilePixelRatio == 1, polygons aren't rendering

### ISSUE THREAD

**Issue by MattBlissett** [openlayers/openlayers#6435]
Polygons in VectorTile layers don't render when the tilePixelRatio is 1.

[Here is an example.](http://bitbucket.matt.blissett.me.uk/2016/02/openlayers-polygons/)  There are two VectorTile layers, only for zoom 0, in EPSG:4326 projection, and each layer has two identical tiles.

The first layer has 4096px tiles, and shows the triangle with corners (points) labelled '4'.

The second layer has 256px tiles, and shows the points labelled '2', but not the triangle. If the tilePixelRatio is changed to e.g. 1.001, the '2' triangle appears.

**Comment by ahocevar** [comment]
This issue has been fixed in master. You can verify that by using https://openlayers.org/en/master/build/ol-debug.js.

**Comment by ahocevar** [comment]
This broke with https://github.com/openlayers/openlayers/commit/ccdb955cd9b253ae15306fecc1a2e6e6efd72722, and https://github.com/openlayers/openlayers/commit/a671687133be619c52b653a9f916ae50a9eb9c06 fixed it.

**Comment by MattBlissett** [comment]
Thanks very much, using the master build works exactly as expected! :)
