### ISSUE TITLE
'dpi' parameter is invalid

### ISSUE THREAD

**Issue by abezr88** [openlayers/openlayers#6438]
Error in chrome when have two monitors of different size, or zoom in the browser (not always)
GET https://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_…6763653%2C6281406.695538039&BBOXSR=3857&IMAGESR=3857&DPI=80.99999785423279 404 ('dpi' parameter is invalid)

Should be fixed in line 211 of src/ol/source/imagearcgisrest.js
- params['DPI'] = 90 * pixelRatio;
+ params['DPI'] = Math.round(90 * pixelRatio);

**Comment by bartvde** [comment]
please provide a pull request

**Comment by fredj** [comment]
note: dpi value for geoserver is already rounded: https://github.com/openlayers/openlayers/blob/v3.20.1/src/ol/source/imagewms.js#L282 (but not for mapserver)
