### ISSUE TITLE
Provide way to determine if all tile sources have finished loading

### ISSUE THREAD

**Issue by marisn** [openlayers/openlayers#6447]
At the moment it is not possible to determine if all tiles of map have finished loading. In #3248 a workaround was proposed by counting `tileload` events (present in two examples: "Tile load events" and "Export PDF"). Unfortunately this technique will fail if number of tiles is larger than 16 - after loading first 16 tiles, there is a moment when number of loading tiles is 0 (as per `tileload` event counting or `map.tileQueue_.isEmpty()`). Thus a different approach is needed to determine if all tiles have been loaded. Similar functionality was asked in #2832 (to be on a par with OL 2).

I have come up with a solution that satisfies me (marisn/openlayers@8541ebcb879a12ab8e1af853ccf5c8004a171cbf) by monitoring `map.frameState_.wantedTiles` as it will contain also tiles that have not been requested yet (and thus no `tileloadstart` event has fired!). In #2832 an event was asked for, still I found it to be not so practical, as event should not fire if all tiles already have been loaded (i.e. thanks to caching). A variable to check after each rendering is better as it allows to know in `postrender` function if the current rendering is complete. The downside of monitoring loading events is already spotted with PDF generation example as #5780. 
Unfortunately my hack does not extend to non-tiled sources (i.e. `ol.source.Image`), although it could be useful to know if all layers have finished loading.

**Comment by flipper44** [comment]
I agree with the last statement especially, knowing that all tile, vector, and image layers have completed rendering is a ridiculous coding process..Made even worse if your layers are dynamic and not hard coded..A ViewRenderComplete would be an awesome feature for printing and image exporting. I've been forced into a timed delay just to play it safe for all the same reasons you mentioned.

**Comment by rensrongen** [comment]
I've similarly been forced into using timed delays.
There appears to be no reasonable/safe way to check whether an image source has completely loaded AND rendered.

Adding a 'renderComplete' event would make a great and rather obvious addition.

**Comment by hutch120** [comment]
Also see: https://github.com/openlayers/openlayers/issues/2320
