### ISSUE TITLE
Export map

### ISSUE THREAD

**Issue by rezvanshiravi** [openlayers/openlayers#6448]
Hi 
I want to export map in png or pdf. but it's not working. The "SecurityError: The operation is insecure." had shown in console. 
Is there a way to do this without change web servers properties?
My code for export png is attached.
Please show me a solution.

 document.getElementById('export-pdf').addEventListener('click', function() {
        map.once('postcompose', function(event) {
          var canvas = event.context.canvas;
		  canvas.crossOrigin="Anonymous";
          canvas.toBlob(function(blob) {
            saveAs(blob, 'map.png');
          });
        });
        map.renderSync();
      });

**Comment by marisn** [comment]
Please ask support questions on mailing list or support forums.
Your error message means that your canvas is tainted. Check if all layers are coming from the same site or include your site into Access-Control-Allow-Origin header. If you are not in control of the source web server, then you are out of luck. CORS is the Google keyword you are looking for.

**Comment by Newborn262** [comment]
I want some one that  God at what they do
I want
All headers
Layers
That all some from that same sites

**Comment by ahocevar** [comment]
God won't help with that. You need to take care of these configurations yourself. A long time ago, bad people used to do bad things, so browsers invented the same origin policy. Now these bad people can no longer harm you.
