### ISSUE TITLE
Bug in vector tiles mapbox format

### ISSUE THREAD

**Issue by nqlong** [openlayers/openlayers#6449]
I used the ol_debug.js from master branch and request wmts from geoserver. This is my test page http://146.148.49.207:8081/geoserver/www/vectortiles/home.html.
![image](https://cloud.githubusercontent.com/assets/7588864/22620257/5855f684-eb3a-11e6-9e60-82ee9452b97a.png)

And the console show the error 404 when request the tile is outside the extent. How can I fix that. 
Thanks.

**Comment by ahocevar** [comment]
You'll have to configure an `extent` for your `ol.layer.VectorTile` instance. You'll get the extent from GeoServer's layer configuration page or the capabilities document.
