### ISSUE TITLE
clustering during zoom

### ISSUE THREAD

**Issue by freder** [openlayers/openlayers#6451]
hi,

I personally think that the experience would be way nicer, if (un)clustering happened *during* zooming – not after.
is there any way to accomplish this out of the box? if not, where would be a good starting point to modify the relevant source code?

thanks in advance.

**Comment by tchandelle** [comment]
Have you tried the `updateWhileAnimating` option on the layer ?

**Comment by freder** [comment]
thanks @tchandelle – I must have overlooked that.
`updateWhileInteracting` did the trick.

**Comment by bartvde** [comment]
@freder next time please can you not cross-post in 3 different channels
