### ISSUE TITLE
features disappear when zoom limit is hit

### ISSUE THREAD

**Issue by freder** [openlayers/openlayers#6456]
as I'm zooming in and hit the `maxZoom` limit, all of the features suddenly disappear.

![features-disappear_](https://cloud.githubusercontent.com/assets/724844/22660021/298e4470-eca0-11e6-8eba-7c3f472f81ce.gif)

also: is it possible to make `maxZoom` a *hard* limit – rather than going beyond and then bouncing back? (as you can see in the gif.)

**Comment by ahocevar** [comment]
The cause for your features disappearing is hard to tell without seeing your code, preferably in a JSFiddle.

Regarding the fact that zooming goes past maxZoom and then bounces back, I'm ccing @tschaub, as he might have a simple fix for that.

**Comment by freder** [comment]
simplifying the code for the fiddle, I actually found a mistake – so, never mind.
