### ISSUE TITLE
ol.layer.Heatmap tests and example broken

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#6464]
I cannot figure out what's wrong, but `ol.layer.Heatmap` is not available in the tests and the `heatmap-earthquakes.html` example. Can anyone take a look please?

**Comment by fredj** [comment]
The example works for me (master) with chrome and firefox

**Comment by ahocevar** [comment]
Interesting, you're right. But it does not work in Safari. Very strange.

**Comment by ahocevar** [comment]
For some reason, `src/ol/layer/heatmap.js` is not loaded at all in Safari, although it is added by the loader.

**Comment by ahocevar** [comment]
Does anyone else see this issue on Safari on a reacent macOS? If not, I'll close this. Maybe just something broken with my Safari.

**Comment by ahocevar** [comment]
It turned out the issue was caused by uBlock, my ad blocker.
