### ISSUE TITLE
test_rendering error with chrome 56

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#6469]
With chrome 56 on ubuntu, the ol.rendering.style.LineString / different strokes / tests the WebGL renderer fails with:
```
Error: Uncaught Error: expected '17.28' to be below 14.6 (http://localhost:3000/node_modules/expect.js/index.js:96)
```

**Comment by fredj** [comment]
Same issue with firefox 51.0.1

**Comment by tchandelle** [comment]
Yes, I had some issues with the rendering test for #6322. The rendering of line dash was too different from one browser to the other.

**Comment by fredj** [comment]
also fails with `make test-rendering`

**Comment by fredj** [comment]
working now

**Comment by ahocevar** [comment]
Yes, thanks to the switch from resemblejs to pixelmatch, which filters out antialiasing differences.
