### ISSUE TITLE
test_rendering error with firefox

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#6471]
With firefox 51.0.1 on ubuntu, the ol.rendering.layer.VectorTile / vector tile layer / renders correctly with the canvas renderer  rendering test fails with:
```
Error: Error: expected '11.64' to be below 11.6 (http://localhost:3000/node_modules/expect.js/index.js:96)
```
same with `make test-rendering`

**Comment by ahocevar** [comment]
We should change all our rendering tests to use larger reference images, and maybe a different image diff tool. For now, many rendering tests only pass on Firefox/Linux.

**Comment by ahocevar** [comment]
And only on some Firefox versions there it seems.

**Comment by bartvde** [comment]
didn't we get pointed to https://github.com/mapbox/pixelmatch a while ago?

**Comment by ahocevar** [comment]
Yes, I think we should use that, and bigger reference images. See #4288.
