### ISSUE TITLE
Rendering issue for tileSize: [192, 256]

### ISSUE THREAD

**Issue by kollhof** [openlayers/openlayers#6473]
I probably am missing something, but it appears that there is a rendering issue when the `tileSize` for a source is taller than wide.

To reproduce the issue I have used the following:
https://jsfiddle.net/f1zvwfqo/1/

```javascript
var source = new ol.source.XYZ({
	tileSize: [192, 256]
});

var map = new ol.Map({
  layers: [
    new ol.layer.Tile({
      source: new ol.source.TileDebug({
        projection: 'EPSG:3857',
        tileGrid: source.getTileGrid()
      })
    })
  ],
  target: 'map',
  view: new ol.View({
    center:[0, 0],
    zoom: 1
  })
});
```
When the map renders, it looks as if an extra set of tiles (bottom row) is not being rendered.
The issue does not appear when the `tileSize` is wider than tall, e.g `[256, 192]`.

I have started to step through the code to better understand what is going on.
My assumption so far is that the `tileRange` is not being calculated correctly:
https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/canvas/tilelayer.js#L125

**Comment by ahocevar** [comment]
Issue confirmed. Thanks for the investigation. Do you think you'd be able to create a pull request with a fix?

**Comment by kollhof** [comment]
I am going to give a try.

**Comment by kollhof** [comment]
After some more debugging, I believe the tile range is actually being calculated correctly. 
I have narrowed down the problem to the calculation of the canvas dimensions in: https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/canvas/tilelayer.js#L183

It is incorrectly using`tilePixelSize[0]` rather than `tilePixelSize[1]` to calculate the height.

The webgl renderer does not appear to have this problem and is using the correct `tilePixelSize[1]`:
https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/webgl/tilelayer.js#L176
