### ISSUE TITLE
Size of Icon feature is calculated wrong

### ISSUE THREAD

**Issue by NicolaiS** [openlayers/openlayers#6480]
When adding an icon feature, the extent of the image is calculated wrong.
The feature is detected as a sub-rectangle of the real image extent.
The result is that when I move the map to only show a part of the image, the image disappear.

A more detailed explanation and runnable example code can be found at my stackoverflow question: 
http://stackoverflow.com/questions/42089668/size-of-icon-feature-is-calculated-wrong

**Comment by cs09g** [comment]
isn't it resolved at the link(stackoverflow)?

**Comment by ahocevar** [comment]
Yes, it is.
