### ISSUE TITLE
is 'ol.events.Event.prototype.preventDefault =' a mistake ?

### ISSUE THREAD

**Issue by JaysonHwang** [openlayers/openlayers#6484]
I start to read source code of openlayer(v4.0.0).And I find line 48 in "/src/ol/events/event.js".
```
/**
 * Stop event propagation.
 * @function
 * @api stable
 */
ol.events.Event.prototype.preventDefault =
```

I thought it might be a mistake only in this new version,so i try to find the same line in older versions.But it start to confuse me that they are the same.I can't understand.Can anyone help?

**Comment by fredj** [comment]
`ol.events.Event.prototype.preventDefault` is equal to `ol.events.Event.prototype.stopPropagation` defined above, see https://github.com/openlayers/openlayers/blob/v4.0.0/src/ol/events/event.js#L56-L58

Without the jsdoc blocks, it should read:
```js
ol.events.Event.prototype.preventDefault = ol.events.Event.prototype.stopPropagation = function() {
  this.propagationStopped = true;
};

```

**Comment by JaysonHwang** [comment]
Wow,I never write jsdoc blocks between statements.It would take me long time to figure it out without you help.thank you. @fredj
