### ISSUE TITLE
4.0.0 touch zoom 'jump'

### ISSUE THREAD

**Issue by rossholdway** [openlayers/openlayers#6485]
Hi,

Congrats on the 4.0.0 release! Having recently updated to 4.0.0 i've noticed that when zooming on a touch device (in this instance an iPhone 7) if you place one finger on the screen before the other and zoom, it can cause a 'jumping' effect. This is not present on v3.20.1. 

Maybe it has something to do with #6444 or #6445 as these worked on zoom logic? ~~I've also noticed that it occurs more often if you start the zoom with your fingers further apart.~~

In this screen recording, I'm trying to zoom in on "Clapham Junction" and "Wimbledon". You can see how I sometimes can't keep them centered (at one point I lose "Clapham Junction"), as it jumps out of view.

https://www.youtube.com/watch?v=s_78ksSR8ds

I'll try and put together a demo asap. Any ideas as to what might be causing this?

Thanks,
Ross

**Comment by ahocevar** [comment]
Just to make sure: the issue I am seeing can be reproduced with the following steps:

1. Place one finger on the map
2. Move the finger
3. While still moving the first finger, place a second finger on the map.
4. The map jumps.

This can be seen with any of the v4.0.0 examples, and does not happen with v3.20.1.

Is this the issue you are seeing, or a different one?

**Comment by rossholdway** [comment]
Yes, this is the exact issue I am seeing.

**Comment by ahocevar** [comment]
Ok, thanks for the confirmation. Debugging now.

**Comment by ahocevar** [comment]
#6486 fixes the issue for me. @rossholdway, can you verify?

**Comment by rossholdway** [comment]
@ahocevar Thanks for the quick response. I can confirm #6486 fixes the issue for me (when building examples and when running on the original device that I discovered the bug on.)

**Comment by rossholdway** [comment]
@ahocevar On further inspection on my device I'm getting some strange view animations. I'll test and get back to you to make sure this hasn't introduced any other issues.

**Comment by rossholdway** [comment]
@ahocevar Ok all looks good to me 👍 . It was a config error on my part (just wanted to be sure). Thanks.

**Comment by ahocevar** [comment]
Thanks for the feedback @rossholdway. I updated the pull request to also handle the kinetic properly. If you don't mind and could test again, that would be much appreciated.

**Comment by rossholdway** [comment]
Thanks for the quick fix and merge @ahocevar @tschaub. I've tested again (against master with the fix applied) on my device and it looks good.
