### ISSUE TITLE
No modifyend fired for an ol.interaction.Modify

### ISSUE THREAD

**Issue by tamarmot** [openlayers/openlayers#6487]
I have a collection of points that I pass to an ol.interaction.Modify as follows:

```
this.stationRepositioner = new ol.interaction.Modify({
	                        	name: "stationRepositioner",
	                        	features: this.stationsFeatures
	                        });
```

Obviously the above is very simple and matches the documentation and examples. 

What happens is with modifying any point EXCEPT for the first one, I get an error in the ol.structs.RBush.prototype.update -- the Uid of the passed in value is not one of the elements in the list.  Uncannily, the coordinates are an exact match for one of them.

This issue persists in 3.20.1 and in 4.0.0

Because the code crashes out in RBush.prototype.update it never fires the modifyend which I am waiting for.

```
ol.structs.RBush.prototype.update = function(extent, value) {
  ol.DEBUG && console.assert(ol.getUid(value) in this.items_,
      'uid (%s) of value (%s) does not exist', ol.getUid(value), value);

  var item = this.items_[ol.getUid(value)];
// HERE ITEM IS NULL BUT IT IS USED ANYHOW
  var bbox = [item.minX, item.minY, item.maxX, item.maxY];
  if (!ol.extent.equals(bbox, extent)) {
    if (ol.DEBUG && this.readers_) {
      throw new Error('Can not update extent while reading');
    }
    this.remove(value);
    this.insert(extent, value);
  }
};
```

**Comment by ahocevar** [comment]
This looks like either a bug, or your app trying to delete features in a listener that is related to the modify interaction. Would you be able to create a codepen that shows the issue?

**Comment by tamarmot** [comment]
Yes, that's my next step, isolating the problem code.  I will remove the delete listener to see if that is the issue, in the short term.

**Comment by thedarkside** [comment]
Came across this issue too! Any solutions so far? @tamarmot

**Comment by stralopple** [comment]
@thedarkside the solution I found was to change 

```javascript
var modify = new ol.interaction.Modify({
    features: select.getFeatures()
});
```

to
```javascript
var modify = new ol.interaction.Modify({
    source: vectorLayer.getSource()
});
```

I suspect that adding the features directly causes them to fall out of sync, but using a common source does not.
