### ISSUE TITLE
临时层中的图元无法全部删除

### ISSUE THREAD

**Issue by boyucjz** [openlayers/openlayers#6490]
var features = source.getFeatures();
for (x in features) 
 {
           var properties = features[x].getProperties();
           source.removeFeature(features[x]);
 }

       创建了一个临时层，手工在临时层上画多边形。 以上是清空临时层所有图元的代码，如果只画一个多边形，可以删除；如果画2个以上多边形，最后一次画的图元第一次无法删除，再次点击删除按钮才能全部删除。使用的版本是3.19。
       现在临时使用循环删除解决了这个问题，请高人回复一下这是什么原因，谢谢。

var features = source.getFeatures();
 for(var n=0;n<10;n++)
  {
      for (x in features) 
     {
           var properties = features[x].getProperties();
           source.removeFeature(features[x]);
    }
}

**Comment by ahocevar** [comment]
In English, please.

**Comment by boyucjz** [comment]
Has been modified.
