### ISSUE TITLE
Circle modifying interaction doesn't work constantly

### ISSUE THREAD

**Issue by tchandelle** [openlayers/openlayers#6495]
If you try this [CodePen](https://codepen.io/tchandelle/pen/rjPqBq), changing the radius multiple times, you'll notice that sometime it fails.

And here is a test that fails: tchandelle@0764be77c4544c9f181215865a3baf23cdd2201a

**Comment by ahocevar** [comment]
Confirmed. I can constistently reproduce when I move the pointer slowly from the center of the circle to a bit beyond the right edge of the circle, and then try to modify. It fails.

A pull request with a fix would be welcome.
