### ISSUE TITLE
Using ES2015 ol package from TypeScript

### ISSUE THREAD

**Issue by achimha** [openlayers/openlayers#6496]
#Trying use the `ol` package from TypeScript:

```
import Map from 'ol/map';
```

I get `Could not find a declaration file for module 'ol/map'. '/foo/node_modules/ol/map.js' implicitly has an 'any' type.`

Has anybody managed to make it work with TypeScript?

**Comment by ahocevar** [comment]
See #6494, it has some hints that might help you get started.

**Comment by ca0v** [comment]
I've had some success but finding it more convenient to stick with the pre-built ol.js.  I was able to get a custom build down to [72KB](https://raw.githubusercontent.com/ca0v/ol4-lab/master/built/index-min.js) over-the-wire with manual changes to rbush/index.js.  One big drawback is the need to cast everything (e.g. `let map = <ol.Map>new Map({})`).  I believe the next big step for ol is to convert each module to typescript.

**Comment by ahocevar** [comment]
Not everyone likes TypeScript. I think it is better to not make OpenLayers depend on it, because it will limit interoperability elsewhere.

**Comment by achimha** [comment]
The goal should be to provide proper typings so that it can be used conveniently from TypeScript.

While not everybody likes TypeScript, it seems to become pretty dominant in the >ES5 world, probably most users of the ES2015 package will want to use it from TypeScript.

Currently OL does not have TypeScript typings but DefinitelyTyped has them, although outdated: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/openlayers

Would it make sense to provide those typings as part of OL?

**Comment by ahocevar** [comment]
If there is a tool that can create TypeScript typings from our existing Google Closure type annotations, then it would make sense - if it does not make things less compatible for users of other bundlers and minifiers.

**Comment by ca0v** [comment]
@ahocevar I respect your opinion immensely and realize I could be wrong but I moving toward typescript will not limit interop.  It should have the opposite effect as well as drastically reduce the code size (you won't have to rely on documentation conversions to enforce scope or reference prototype).  I'm not asking for a defense of your opinion but I am having a hard time seeing how typescript could possibly limit interop.

But to the point of this issue, I think the current ES2015 code base can be coupled with typescript definitions to solve typescript interop but I'm not sure how to do it.  I tried the below but if effected the output file (it stopped in-lining the ol/map source).

```
declare module "ol/map" {
    export default ol.Map;
}
```

**Comment by achimha** [comment]
I see no need whatsoever to make use of TypeScript within the openlayers codebase. That is not necessary. However, openlayers should be useable from TypeScript because this is what the majority of >ES5 developers use.

I believe this can be best done by using the ES2015 module approach of the `ol` package and including typings.

**Comment by ca0v** [comment]
@achimha I agree and I've been trying to figure out how on-and-off most of today and I'm getting no where.  Maybe the typescript community can help:
http://stackoverflow.com/questions/42253982/tsc-why-does-introducing-a-module-declaration-effects-the-contents-of-the-outfi

**Comment by jumpinjackie** [comment]
@achimha There's already a full API surface d.ts for OpenLayers 3.20 here (https://github.com/jumpinjackie/jsdoc-typescript-plugin/blob/master/typings/openlayers.baseline.d.ts)

I'm looking at how to provide sufficient hooks in the plugin so that we can bolt on piecemeal ES2015 module declarations here:

https://github.com/jumpinjackie/jsdoc-typescript-plugin/issues/86

**Comment by ca0v** [comment]
@jumpinjackie Looks great! Have you tried this with tsc -outFile?  My experience has been that because if finds the d.ts declaration it doesn't inline the ol module.

**Comment by vrmerlin** [comment]
I'm having the same problem here. I'm trying to use ol in an Angular2 project, and getting a stream of "Cannot find module" errors. Is that because the .d.ts file is missing? Is there a solution being worked?

**Comment by ca0v** [comment]
@vrmerlin Maybe not just your d.ts but you tsconfig.json settings.  See https://github.com/ca0v/ol4-lab/blob/master/tsconfig.json for possible help.  I think @jumpinjackie generated the typings you need as long as your not compiling to a single -outFile.

**Comment by lucastheisen** [comment]
@achimha , for what its worth, I was able to get the `ol@4.1.0` package to work in my typescript application with a little _coercion_.  You just need to add a `devDependency` on the `@types/openlayers`, then add a couple declaration for each module you use:
```
declare module "ol/layer/tile" {
    export default ol.layer.Tile;
}

declare module "ol/map" {
    export default ol.Map;
}

declare module "ol/source/xyz" {
    export default ol.source.XYZ;
}

declare module "ol/view" {
    export default ol.View;
}
```
_Notice each declaration is really just an re-export of the corresponding @types module_

In my project i just add a new type definition through the tsconfig:
```
    "typeRoots": [
      "./app/viewer-openlayers/@types/",
      "./node_modules/@types/"
    ]
```
then add the above declarations as `app/viewer-openlayers/@types/ol/index.d.ts`.

Its kind of annoying to have to add entries for each module I use, but at least i have my types...

**Comment by craigsnyders** [comment]
@lucastheisen any chance you could create a basic repo with that method? I can't get it working in an existing project using Typescript 2.3.4 + webpack2

**Comment by lucastheisen** [comment]
@craigsnyders , sure, here you go: https://gitlab.com/pastdev/typescript-openlayers

**Comment by niftydevelopment** [comment]
@lucastheisen I am very thankful for this solution.

But can you explain why this extra "app/viewer-openlayers/@types/ol/index.d.ts" is needed?
I can´t wrap my head around it.

Tnx again :)

**Comment by lucastheisen** [comment]
@niftydevelopment , its needed to _align_ the `import` for [ol](https://www.npmjs.com/package/ol) (the openlayers es2015 module version) and the type definition (provided by `@types/openlayers`) which is written for [openlayers](https://www.npmjs.com/package/openlayers) and not broken up into modules.  Specifically, you need to use `import 'ol/map'` to import map module but the typings are all under ol itself (something like `import ol`)...

In trying to write _why_ i realize it is hard to explain...  And know I didn't do a very good job...

**Comment by svvac** [comment]
Here seems to be [a more complete typings file][1] that claimed to be generated from jsdoc.

  [1]: https://github.com/jumpinjackie/mapguide-react-layout/blob/84e9c19c0389a1ed1d85db8681ae9d5fe895e086/src/internal_typings/openlayers.d.ts

**Comment by wulfsberg** [comment]
I would love TypeScript definitions for the ES package version.
I see there is a https://github.com/angular/clutz project under the Angular umbrella, to convert Closure annotations to TypeScript definitions, which sounds very promising.
But it seems Clutz doesn't play well with Windows, which I am currently on. Does anybody have a setup where they can test whether the OpenLayers annotations can easily be processed by this tool?

(I think you would make a lot of people very happy if you could pack the type definitions with the ES distribution of OpenLayers).

**Comment by agxs** [comment]
The `typeRoots` section should go in the `compilerOptions` section according to https://www.typescriptlang.org/docs/handbook/tsconfig-json.html and not at the root level like the above linked example.

**Comment by scottfrenzy** [comment]
I imported @types/ol.  I use angular 9, so I used `npm install --save @types/ol`
