### ISSUE TITLE
ol.style.Icon Rotation and polar projection

### ISSUE THREAD

**Issue by ch08532** [openlayers/openlayers#6497]
I'm trying to display point features on a layer that are styled with an icon (ex: a vessel represented as a triangle). These icons are rotated based on the vessels heading. Under Mercator projection this works perfectly but when reprojected in polar north projection (EPSG:3413) the icons do rotate but do not accurately represent the heading of the vessel. Is this a bug or do I need to perform some calculation before setting the rotation option? If its the latter, does anybody know how to calucate this? Thanks

**Comment by ahocevar** [comment]
This is not a bug, and it's why we call the style property `rotation` and not `heading`. Displayed rotation angles matching headings is one of the key features of a Mercator map. For other projections, you need to calculate rotation angles for headings yourself.

**Comment by ch08532** [comment]
If anybody knows this calculation or can point me into the right direction that would be greatly appreciated.  Thanks

**Comment by ch08532** [comment]
If anybody needs to rotate an ol.style.Icon to represent a point in context of a heading in EPSG:3413, here is my working implementation:

var factor = 0.0;

//pos is [lon,lat] coordinate in polar coordinates
var distance = Math.sqrt(pos[1] * pos[1] + pos[0] * pos[0]); //Use Pythagoras Theorem to find the long side (the hypotenuse)
var deg = Math.atan2(pos[0], pos[1]); //Use the Tangent Function to find the angle
var polarCoor = { distance: distance, deg: deg * (180 / Math.PI) };  
factor = 180 + polarCoor.deg;
   
//now set rotation attribute in ol.style.Icon
rotation: ((factor + track.heading) * (Math.PI / 180)),

**Comment by KhaledOmara** [comment]
@ch08532 So how to calculate the rotation in EPSG:4326 (Used in GPS)
