### ISSUE TITLE
ol 3 map not displayed in Android webview

### ISSUE THREAD

**Issue by mikel2000** [openlayers/openlayers#6500]
I'm trying to display an openlayers 3 map in an Android webview. Only the zoom controls and the copyright are displayed, the map itself not. Javascript is enabled for the webview, right to access the internet is granted. I tested on a Nexus 5 with Android 7 (API 24).

If I load exactly the same js code in Chrome on Android, the map is displayed fine. Any ideas?

**Comment by cs09g** [comment]
Does the same URL work on web browsers?

**Comment by mikel2000** [comment]
Yes. Like I wrote, if I load exactly the same js code in Chrome on Android, the map is displayed fine.

**Comment by fredj** [comment]
Are you using cordova?

**Comment by ischas** [comment]
Wild guess: You need a polyfill.

**Comment by mikel2000** [comment]
In the meantime I managed to display the map but I'm not happy about this solution, as the map is pretty blurry. It works only, if I set "pixelRatio:1", call map.setSize and pass the half of width/height of the container div. If I pass just the full width/height, nothing is displayed.

**Comment by mikel2000** [comment]
> Are you using cordova?

No, just plain Android SDK in Android studio.

**Comment by mikel2000** [comment]
I made some additional test:
I just loaded several example maps from here http://openlayers.org/en/v3.2.1/examples/ into my webview. Not a single map was displayed. Additionally I loaded some of the examples in the official Android WebView Browser Tester with exactly the same result. So now I'm sure that it's not a problem of my specific map or webview but a general problem displaying openlayer maps on an Android webview.

**Comment by mikel2000** [comment]
Additionally I made some tests with leaflet. The map is displayed without problems. So probably I'll switch to leaflet. For that reason I'm closing this bug.

**Comment by fredj** [comment]
v3.2.1 is pretty old; you should try with the latest version (v4.0.1): http://openlayers.org/en/latest/examples/

**Comment by TheRDavid** [comment]
Just thought I'd mention this is still an issue. We're experiencing open layers not loading tiles on Android Studio Emulators **on Windows** (no such issue on Linux or Mac) across multiple machines, emulated devices, Android and Openlayers versions.

**Comment by Crewchief85** [comment]
My openlayers maps won't load in WebView on Android Studio using Windows...  Is there a fix for this?

**Comment by hosseinbzh** [comment]
and this problem for me! I dont know what to do!

**Comment by MaannSevlani** [comment]
I’m still facing issue with openlayers map not being loaded on android web view. Is this issue solved for others? Let us know what is the issue and how it got resolved. Thanks in advance.
