### ISSUE TITLE
Problem with drawing in freehand mode when last point is close to the first point

### ISSUE THREAD

**Issue by tchandelle** [openlayers/openlayers#6501]
Go to http://openlayers.org/en/latest/examples/draw-freehand.html

Draw a LineString or Polygon like this gif :

![freehand](https://cloud.githubusercontent.com/assets/19923657/23022222/0140fd2a-f450-11e6-8252-9c34ccdef45d.gif)

**Comment by ahocevar** [comment]
Confirmed. Looks like this problem occurs when the pointerup event occurs within the tolerance of the start point.

**Comment by fredj** [comment]
Same issue if a small line is drawn in freehand mode.

Maybe the tolerance test should ne be used in freehand mode

**Comment by tchandelle** [comment]
If we don't use tolerance in freehand mode, is [this test](https://github.com/openlayers/openlayers/blob/b05136ea537d621890a9d2a982338b24903cd4f0/test/spec/ol/interaction/draw.test.js#L735-L739) still correct ?

**Comment by ahocevar** [comment]
I think the above test should continue to pass. Testing for tolerance in freehand mode does make sense in my opinion, but there must be something wrong in the way we handle it.
