### ISSUE TITLE
ol.interaction.Draw condition not being passed events

### ISSUE THREAD

**Issue by adamal** [openlayers/openlayers#6503]
When I give a custom (as in not one of OL's predefined ones) `condition` function to an ol.interaction.Draw, the `condition` is only called with `'pointerdown'` events.

**Background:**
I am trying to build a point feature selector, which selects features when they are clicked (and a polygon is not being drawn), or by a drawn polygon. 

To this end I am trying to juggle an `ol.interaction.Select` and an `ol.interaction.Draw`, which both respond to `'click'` events, but only according to (mutually exclusive) conditions defined by me.

If I log all events received by either interaction's `condition`, I see that the `Select` interaction receives many (such as `'pointerdown'`, -`up'`, -`move'`, `'click'` and `'singleclick'`), while the `Draw` interaction only receives `'pointerdown'`, making it impossible to handle `'click'`.

[This plunk illustrates](http://plnkr.co/edit/DM9xF5?p=preview) (enable dev tools to see log messages).

I have also submitted this issue as a [stackoverflow question](http://stackoverflow.com/questions/42139461/custom-condition-for-openlayers-3-draw-interaction)

**Comment by ahocevar** [comment]
Your custom condition needs to return `true` if it is met. The custom conditions in your Plunker always return `undefined`.

**Comment by adamal** [comment]
The conditions in the plunker are meant to illustrate the difference in which events are passed to the Select and Draw interaction. They are not intended to "work". 

From the condition in `ol.interaction.Draw`, it is impossible to return `true` on `'click'` events, for example, since the `condition` is only passed `'pointerdown'` events.

**Comment by ahocevar** [comment]
Whether an interaction takes on an event and passes it on to subsequent interactions depends on the return value from the condition, so you cannot just log something there without returning true ever.

**Comment by adamal** [comment]
I think we may be talking past each other. Let me try to clarify the way I understand it, by taking a step back: 

When creating a new ol.interaction.Draw, you can pass it an `options` object containing a `condition`. 

This `condition` is a function that accepts an `ol.MapBrowserEvent` and returns `true` if that event should "be handled". 

I have (perhaps wrongly) assumed that "be handled" indicated that the event should trigger the addition of a point (at the coordinates of the "handled" MapBrowserEvent) to the polygon being drawn.

By this assumption, I initially passed a `condition` similar to:

```
function(e) {
    if (myCondition && e.type === "click") {
        return true;
    }
}
```

However, this function never returned `true` because `e.type` was always `"pointerdown"`.

Have I misunderstood the purpose of `condition`?

**Comment by ahocevar** [comment]
I think the documentation of the `condition` option of the `ol.interaction.Draw` constructor needs to be improved. The draw interaction decides on pointerdown whether a sequence of events should be handled by it, so the condition is always evaluated with a `pointerdown` event. So maybe the custom condition function you are looking for is simply
```js
function(e) {
    if (myCondition) {
        return true;
    }
}
```

On the other hand, the Select interaction can be used with different types of events, so the condition is evaluated with every mapbrowserevent.

**Comment by bgschiller** [comment]
I'm having the same issue. I'd like to be able to say 
```
   condition: function(evt) {
        /* "return true if event is a click, with or without shift" */
    }
```

but my custom condition callback is never reached while I'm holding down shift.

**Comment by bgschiller** [comment]
Wait, nevermind. I was able to do what I needed by passing

```
freehand: false,
freehandCondition: ol.events.condition.never
```

to the options for Draw. Turns out, shift-click was being caught by the freehand drawing code.
