### ISSUE TITLE
Add delete option to ArcGIS edit example

### ISSUE THREAD

**Issue by afogelberg** [openlayers/openlayers#6506]
The data in the [ArcGIS edit example](http://openlayers.org/en/latest/examples/vector-esri-edit.html) is covering large parts of the world. It would be good to enhance the example with a delete option to be able to clean some data.

**Comment by bjornharrtell** [comment]
Noo, there are some great works of art right there.

**Comment by afogelberg** [comment]
I agree. But it's kind of hard to create new great art at the moment.

**Comment by bjornharrtell** [comment]
Depends on the scale. I can see both Cuba and Bahamas are up for grabs.

**Comment by afogelberg** [comment]
Let's hope nobody gets greedy and grabs the whole world.

**Comment by bartvde** [comment]
I had expected Esri Portland to clear up the data once in a while to be honest.

**Comment by bartvde** [comment]
looks like it's less crowded now, maybe they are clearing it up
