### ISSUE TITLE
feature.getProperties() and the feature geometry

### ISSUE THREAD

**Issue by icemagno** [openlayers/openlayers#6508]
I'm trying to copy the properties from a feature (a polygon) to another (a point).

```
var polyGeom = polyFeature.getGeometry().getExtent();
var polyProps = polyFeature.getProperties();

var center = ol.extent.getCenter( polyGeom );
var pointGeom = new ol.geom.Point( center );
var pointFeature = new ol.Feature({
   geometry: pointGeom,
});
```

Inspecting `polyProps ` I can see a geometry object:

`{ geometry: Object, name: "theName", distance: 67.7283026166835, operator: null, featureId: "helipad-button" }`

and when I try to set the point properties with polygon properties:

`pointFeature.setProperties( polyProps );`

I'm overriding the point geometry too.... What I'm doing wrong? Why are properties not simply properties?

BTW: Using the very new release 4.0.1! Congratulations!

**Comment by ahocevar** [comment]
OpenLayers features follow loosely the OGC Simple Features concept, in which a geometry is also just a property of the feature. This way, your feature can even have multiple geometries. So maybe all you need/want to do is add a point geometry as additional property to your existing polygon feature?
```js
polygonFeature.set('center', new ol.geom.Point(center));
```
For rendering, you can make your style use a different geometry than the one referenced by the feature's `geometryName`:
```js
new ol.style.Style({
  geometry: function(feature) {
    return feature.get('center');
  }
  // ...
});
```

**Comment by icemagno** [comment]
So my point can be a line or a polygon at same time? Weird... Ok. Understood.
