### ISSUE TITLE
OL 4 with Tileserver GL

### ISSUE THREAD

**Issue by lukaszbel** [openlayers/openlayers#6510]
I've built my own server with using Tileserver GL and OSM data. Tileserver gives me a REST address which I can use in OL configuration as a data source, but resolution on the level of buildings is not efficient. You can see on this example:
https://openmaptiles.org/docs/website/openlayers3/

In the future do you expect any support for Tileserver GL?

**Comment by ahocevar** [comment]
@lukaszbel Your tile grid's `maxZoom` setting should be 14, because it seems your tile server only provides tiles up to z14.

However, this won't fix the issue that the resolution will be insufficient when you zoom in beyond z14. See #6453 for a suggested improvement that will fix this. When #6454 is merged, you'll be able to create your tile grid like this:
```js
ol.tilegrid.createXYZ({
  maxZoom: 17 // pregenerate images up to z17, then switch to vector mode
  loadZooms: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14] // only tiles with z <= 14 are available
});
```

**Comment by lukaszbel** [comment]
Thank you for answer. Few days ago I asked the autors of Tileserver GL and they wrote me:

> OpenLayers does not have yet all the functionality required - such as over zoomed redraw of vector tiles for example or collision on captions.
https://github.com/klokantech/tileserver-gl/issues/66
Is the problem in Tileserver GL or in OL? If I use Mapbox GL JS then streets view zoom loks ok, but my project use OL and tiles vector from OSM looks very well.

**Comment by ahocevar** [comment]
> Is the problem in Tileserver GL or in OL?

It is probably only a configuration problem. I'm sure you can configure TileServer GL to provide all zoom levels up to 22. But the snippet I posted above will make your current configuration look nice in OpenLayers, except for the decluttering of labels and curve labelling which are still missing in OpenLayers (but are being worked on).

**Comment by lukaszbel** [comment]
I am gis analyst, not programmer so sorry for my incompetence. 
Below is my actual code with your suggestion, but the resultat is te same, still maxzoom is 14.
http://pastebin.com/LW1ww3vJ

The code is the same like https://openmaptiles.org/docs/website/openlayers3/ only url addresses are to my localhost.

**Comment by ahocevar** [comment]
@lukaszbel You'll have to build OpenLayers from the branch of my pull request #6454 - it is still work in progress and not merged yet.

**Comment by klokan** [comment]
> ... [it] looks nice in OpenLayers, except for the decluttering of labels ... which are still missing in OpenLayers (but are being worked on).

@ahocevar could you please provide more info on who works on the label collision in OpenLayers?
I expect a basic bounding box collision algorithm would solve the label clutter on vector tiles.
Related to (BTW MapBox engineers are amazing!):
https://www.mapbox.com/blog/label-collisions/
https://www.mapbox.com/blog/better-label-placement-in-mapbox-studio/

Shall we make a related OpenLayers ticket? I have not seen one yet...

**Comment by ahocevar** [comment]
No one is working on that yet. Please go ahead and create a ticket.

**Comment by ahocevar** [comment]
See https://github.com/openlayers/openlayers/pull/7022, which adds an API that can be used to plug in 3rd party renderers. The two examples I have added there use Labelgun for decluttering, and custom code to render text along lines.
