### ISSUE TITLE
OL4 - apparently ol.proj.transform doesn't "parseFloat()" coordinates

### ISSUE THREAD

**Issue by cjeanneret** [openlayers/openlayers#6514]
Hello,

I had a small headache with a proj transformation for a map center. While using `view.setCenter()` it kept pointing the [0,0] coordinates.

After some tests and struggles, it appears the float values weren't floats (coming from a JSON loaded via jquery) but string, and that I had to `parseFloat()` them while loading in the ol.proj.transform.
As I could `grep` parseFloat() in the ol code, I suspect its call isn't done everywhere.

Might be good to have a check on that.

Cheers,

C.

**Comment by tschaub** [comment]
Please use parseFloat in your application.  The argument to view.setCenter() must be an array of numbers.
