### ISSUE TITLE
settings view properties does not populate after map initialize

### ISSUE THREAD

**Issue by bayramucuncu** [openlayers/openlayers#6516]
ol.View() has some properties to set some view options like;

- `setZoom()`
- `setCenter()`

But oliView() does not contain function for other properties `setExtent(), setProjection(), setMinzoom() maxZoom()`

So I need create a new view and set the map.  In this stuation we have some problems. For example I set the minZoom and max Zoom via a  new view. But some times later I need to set an extent. When I set an extent via a new `ol.View()` the min zoom and max zoom settings does not work.

I noticed this issue while I was working with angularjs. I created seperated map otons as directive:

```
<ol-map>
   <ol-zoom level="4" min="4" max="15"></ol-zoom>
   <ol-extent box="1,2,3,4"></extent>
</ol-map>
```

**Comment by ahocevar** [comment]
In pure OpenLayers, like you said, you would just create a new view and call
```js
map.setView(new ol.View({
  extent: myExtent,
  zoom: map.getView().getZoom(),
  center: map.getView().getCenter()
}))
```.
You should maybe design your Angular components in a way that allows you to replace the view of a map with a new one.
