### ISSUE TITLE
ol.array.linearFindNearest

### ISSUE THREAD

**Issue by danielpce** [openlayers/openlayers#6517]
I need to change the order the tiles are loaded. I searched in ol-debug.js and I found that ol.array.linearFindNearest decides the order. Is it possible to change ol.array.linearFindNearest?

**Comment by ahocevar** [comment]
What do you mean by "change the order the tiles are loaded"? What is your use case? `ol.array.linearFindNearest` is only used to determine the zoom level of the tiles to be loaded.

**Comment by danielpce** [comment]
For the fractional case zoom the tiles with a higher z loads only after 1/3 of the zoom increase. I would like to take the tiles only after 1/5 of the zoom increase. In ol.array.linearFindNearest is the decision 

if (arr[i - 1] - target < target - arr[i]) {
	return i - 1;            
} else {
        return i;
}

which is arr[i - 1] + arr[i] < 2*target
In my case it is something like x < 2*target/3

If I change this decision It solves my issue
