### ISSUE TITLE
All of the elements in the temporary layer cannot be deleted

### ISSUE THREAD

**Issue by boyucjz** [openlayers/openlayers#6528]
var features = source.getFeatures();
for (x in features) 
 {
           var properties = features[x].getProperties();
           source.removeFeature(features[x]);
 }
Create a temporary layer, hand drawing polygons on the temporary layer. The above is empty the temporary layer of all primitive code, if only to draw a polygon, can be removed; if draw more than 2 polygons, the last time the first draw primitives cannot be deleted again, click the delete button to delete all. The version used is 3.19.
Now delete the temporary use of circulation to solve this problem, please reply this is what reason, thank you.

var features = source.getFeatures();
 for(var n=0;n<10;n++)
  {
      for (x in features) 
     {
           var properties = features[x].getProperties();
           source.removeFeature(features[x]);
    }
}

**Comment by ahocevar** [comment]
Deleting from an array while reducing the number of entries in the array will always fail. You can either call `source.clear()` to remove all features, or remove features in a while loop:
```js
var features = source.getFeatures();
while (features.length) {
   source.removeFeature(features.pop());
}
```
