### ISSUE TITLE
ol.featureloader.xhr doco missing success and failure params

### ISSUE THREAD

**Issue by hutch120** [openlayers/openlayers#6531]
Hi Guys,

Just wanted to report a doco issue.

I was trying to see how to detect the failure of ol.source.vector http request, and seemed like this was not possible by reading the doco, here:

http://openlayers.org/en/latest/apidoc/ol.featureloader.html#.xhr

It only shows params for url and format.

Then I looked at source code, and turns out there are params for success and failure too, just what I needed. :)

I'm guessing the document creator is not picking up these params for some reason.

Cheers

**Comment by ahocevar** [comment]
This is not exactly true. `ol.featureloader.xhr` takes two arguments, `url` and `format`. It uses an internal function, `ol.featureloader.loadFeaturesXhr`, which takes the arguments you mention. However, errors are currently [not handled](https://github.com/openlayers/openlayers/blob/v4.0.1/src/ol/featureloader.js#L90). If you are willing to create a pull request, it would make sense to add a failure callback as optional 3rd argument to `ol.featureloader.xhr`.
