### ISSUE TITLE
Feature request: adjust imagery offset

### ISSUE THREAD

**Issue by dhivehi** [openlayers/openlayers#6534]
It would be nice if u can add a feature to adjust imagery offset. Or is there any such feature in openlayers?

**Comment by ahocevar** [comment]
You'd have to be more specific. What is your use case? What imagery? What offset?

**Comment by dhivehi** [comment]
Imagery offset means the adjustment needed to bring to satellite imagery layer (by panning it) to correct the position of the satellite imagery which reflects the actual GPS position of an object appears in the imagery.` For example: There are a difference of approximately 10 feet in the position of an object in google imagery & bing imagery. So one layer needs to be permanently moved (panned) to match another imagery layer by using an offset. You can also see this feature in openstreet maps editor. Because Bing imagery is little far away from actual GPS position of an object appears. 
![image](https://cloud.githubusercontent.com/assets/18715293/23316269/8ab2f4b8-faeb-11e6-814e-c5f21c4eba4b.png)

**Comment by ChouGary** [comment]
http://viglino.github.io/ol3-ext/examples/map.geoimage.html

**Comment by dhivehi** [comment]
That's for static images. What i'm looking for is, imagery offset for tiled layers

**Comment by ChouGary** [comment]
like this demo?
https://codepen.io/anon/pen/YZQzGE?editors=1010

**Comment by dhivehi** [comment]
Thank you! It solved my problem.

**Comment by ahocevar** [comment]
Caveat: the codepen above uses internal non-API properties. To achieve such offsets, it is better to create an `ol.tilegrid.TileGrid` with an appropriate `origin` from scratch. But in general, the approach to set an offset through a modified tile grid origin is a viable one.
