### ISSUE TITLE
layer switcher gotcha

### ISSUE THREAD

**Issue by wayofthefuture** [openlayers/openlayers#6552]
So we are trying to modularize and use the NPM version of OpenLayers along with Webpack and CommonsChunk plugin. The problem is we can't move over and modularize it because in order to have the layer switcher, we must include that script globally in index.html. Since ol would then no longer be a global variable, it requires us to keep the ol.js source file in index.html and leave it global. Hence, the gotcha is we can't fully modularize OpenLayers because of the global variable layer switcher requirement.

Any word on when the "ol3-layerswitcher" module will be imported and combined into the official openlayers 4 project? It would see this as an important feature for those trying to debug/monitor applications that continually remove/add layers.

**Comment by falconxunit** [comment]
Open layers

**Comment by anzeznidarsic** [comment]
What if you expose _ol_ object globally via ProvidePlugin: https://webpack.github.io/docs/shimming-modules.html > _ProvidePlugin_ section?

**Comment by ahocevar** [comment]
It should be possible to use a module loader and bundler with ol3-layerswitcher. See walkermatt/ol3-layerswitcher#48.

**Comment by wayofthefuture** [comment]
Yes I have tried with both the provide plugin and webpack. I will look at that link and try again. OpenLayers is great, and I know how hard it can be when there are so many other things on the todo list. I think the layer switcher is one of those fundamental things the framework should have. Great job btw guys.
