### ISSUE TITLE
Creating your first map sample code does not work

### ISSUE THREAD

**Issue by staplesj** [openlayers/openlayers#6562]
I am trying to learn how to use OpenLayers. Following the Tutorials in the Documentation, I have tried to start with the sample code given under Creating your first map.
The sample page displays nothing.
It would be helpful if the samples in your tutorial actually work!!

**Comment by bartvde** [comment]
Are you talking about http://openlayers.org/workshop/en/basics/map.html ?

**Comment by fredj** [comment]
Or https://openlayers.org/en/latest/doc/tutorials/concepts.html ?

**Comment by staplesj** [comment]
I was referring to this one: https://openlayersbook.github.io/ch01-getting-started-with-openlayers/example-01.html

Incidentally, http://openlayers.org/workshop/en/basics/map.html does not work either.

**Comment by bartvde** [comment]
We don't maintain the openlayers book

**Comment by fredj** [comment]
@staplesj you should report your issue to https://github.com/openlayersbook/openlayersbook.github.io/issues

**Comment by bartvde** [comment]
Our workshop doesn't work since the demo.opengeo.org service is down, we should probably use a different service in our workshop

**Comment by rmdobservations** [comment]
Blue marble does not work. I have been using   
```
new ol.layer.Tile({
          source: new ol.source.OSM()
        }),
```

also
```
var layers = [
        new ol.layer.Tile({
          source: new ol.source.TileWMS({
            url: 'https://ahocevar.com/geoserver/wms',
            params: {
              'LAYERS': 'ne:NE1_HR_LC_SR_W_DR'
            }
          })
        })
      ];
```

I have been working my way through the Beginners Openlayers3. There are some outdated functions that need to be replaced as well. I am slowly making a list with solutions. Would it help to post these here or on my own github?

**Comment by bartvde** [comment]
As I said that WMS is down, so bluemarble down is to be expected. If it's related to the OpenLayers book, this repo is not a good place to ticket those issues but use the link that @fredj provided.

If you're not sure post them on your own github first and we can help you decide where to put them.

cc @acanimal is there any active development on the book of openlayers these days?

**Comment by rmdobservations** [comment]
Yes, I am learning OL3 using many sources and fixing things along the way. I'll see if I can post something helpful on my github. It is nice to have an alternative WMS when one fails.

**Comment by acanimal** [comment]
Link https://openlayersbook.github.io/index.html is the companion of *OpenLayers3 Cookebook* from PackPub written by @ThomasG77 (I wrote the *OpenLayers2 Cookbook* 😄  ).

I wrote too [The Book of OpenLayers3](https://leanpub.com/thebookofopenlayers3) with the samples at [http://www.acuriousanimal.com/thebookofopenlayers3](http://www.acuriousanimal.com/thebookofopenlayers3/) 🎉

**Comment by bartvde** [comment]
Ah too many books to keep track of @acanimal ;-) thanks for your feedback

**Comment by fredj** [comment]
http://openlayers.org/workshop/en/basics/map.html fixed with https://github.com/openlayers/workshop/pull/72
