### ISSUE TITLE
Consistent min/max zoom support for sources and layers

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#6563]
Some sources support a `maxZoom` option (e.g. `ol.source.XYZ`).  Views support a `maxZoom` option.  It would be consistent for layers to support a `maxZoom` option (instead of making people calculate `minResolution`).  In addition, it would be convenient if layers supported a `minZoom` option (instead of making people calculate `maxResolution`).  And then it would be nice to add `minZoom` and `maxZoom` support to sources where it makes sense.

**Comment by aalbericio** [comment]
+1

All layers should support minZoom and maxZoom so we don't have to deal with resolutions.

Moreover, I can't see the "getResolutionForZoom" exposed in the View.

Related question: how do I easily calculate resolution for a given zoom right now?

Thanks!
