### ISSUE TITLE
Raster calculations cause unwanted transition effects

### ISSUE THREAD

**Issue by igorti** [openlayers/openlayers#6564]
`ol.layer.Image` with raster source shows strange transition effects when panning around and zooming in/out, see example below. Raster operations performed on pixels are very simple and basically the same as in [Sea Level example](https://openlayers.org/en/latest/examples/sea-level.html) - assigning a colour based on index value.

![transitions2](https://cloud.githubusercontent.com/assets/711438/23652311/b0c7c6f2-0328-11e7-9f6a-7d0ca7833abb.gif)

I would appreciate any thoughts on what might cause these unwanted transitions. Please see [code example](https://codepen.io/anon/pen/PpbYXM) for details on implementation.

**Comment by thhomas** [comment]
related to #5537 ?

**Comment by igorti** [comment]
Yes, indeed - Color Manipulation example that you are referencing seems to have same effects. I think that time it takes to load tiles with underlying data affects how noticeable this effect is. It also looks like once tiles are cached layer is rendered correctly. Could possible solution be to wait until all tiles are loaded?

**Comment by ahocevar** [comment]
#6642 should fix the issue. @igorti, can you please confirm?

**Comment by igorti** [comment]
Thank you, Andreas! This fix seems to help a lot. Panning around doesn't create this effect anymore. Zooming in/out seems to be working much better, although I can still notice this effect when zooming out and tiles not being in cache, see the video. Once cached it works perfectly.

![mar-27-2017 18-15-20](https://cloud.githubusercontent.com/assets/711438/24366623/f56c31f2-1319-11e7-8cfd-854dc8a3ee79.gif)

**Comment by ahocevar** [comment]
@igorti I updated the pull request. Can you please test again? Thanks.

**Comment by thhomas** [comment]
I tested your version on Color Manipulation example and the rendering is now good.
Thanks @ahocevar.

**Comment by igorti** [comment]
Indeed, I also tested with the most resent commit d613900 and with it works perfectly now. Thanks you, Andreas!

**Comment by igorti** [comment]
Thank you, Tim and Andreas!

**Comment by tschaub** [comment]
Thanks for posting the example @igorti and for helping get to the bottom of the problem @ahocevar.  The changes in #6658 should result in more consistent rendering and less unnecessary  source processing in the worker.
