### ISSUE TITLE
map.forEachFeatureAt not working with anchors and offsets

### ISSUE THREAD

**Issue by emilielalague** [openlayers/openlayers#6565]
Hello,
I could not find any documentation on the web regarding this issue so I'm assuming it is a bug.
What happens is that when I use a large anchor(see the example below) for an icon and then click on the icon, the map.forEachFeatureAt function can't find any feature.
With no anchors, the code works as expected.
The same problems seems to occur with ol.style.Text and large offsets.

```js
map = new ol.Map({
    target : "map",
    view : new View()
});

style = new ol.style.Style({
    image : new ol.Style.Icon({
        src : <path to an image>,
        anchor : [2, 2]
    })
});
source = new ol.source.Vector();
layer = new ol.layer.Vector({
    source : source,
    style : style
});
map.addLayer(layer);
map.on("singleclick", function(evt){
    map.forEachFeatureAt(evt.pixel, function(feature, layer){
        console.log("Hit!");
    });
})
```

**Comment by fredj** [comment]
This is known limitation.
See https://github.com/openlayers/openlayers/blob/master/doc/faq.md#why-are-my-features-not-found

**Comment by emilielalague** [comment]
Great thanks !!

Emilie LALAGÜE
Ingénieur Etudes et Développement
AKKA I&S
19, Avenue Neil Armstrong – 33700 MERIGNAC - France
Port : +33(0)6 51 86 15 60  - Tél : +33(0)5 33 51 68 51
Mail : mailto:emilie.lalague@akka.eu
www.akka-technologies.com <https://www.akka-technologies.com/>

[http://www.akka.eu/img/outlook/SIGNATURE-AKKA-2016-5_02.jpg]




[http://www.akka.eu/img/outlook/SIGNATURE-AKKA-2016-5_04.jpg]<https://www.linkedin.com/company/akka-technologies>

[http://www.akka.eu/img/outlook/SIGNATURE-AKKA-2016-5_05.jpg]<https://www.facebook.com/AKKATech>

[http://www.akka.eu/img/outlook/SIGNATURE-AKKA-2016-5_06.jpg]<https://twitter.com/akka_tech>



[http://www.akka.eu/img/outlook/SIGNATURE-AKKA-2016-5_08.jpg]






De : Frédéric Junod [mailto:notifications@github.com]
Envoyé : mardi 7 mars 2017 17:14
À : openlayers/openlayers
Cc : LALAGUE Emilie; Author
Objet : Re: [openlayers/openlayers] map.forEachFeatureAt not working with anchors and offsets (#6565)


This is known limitation.
See https://github.com/openlayers/openlayers/blob/master/doc/faq.md#why-are-my-features-not-found
