### ISSUE TITLE
Overlay position determined before overlay is visible in the DOM.

### ISSUE THREAD

**Issue by nagytech** [openlayers/openlayers#6566]
Under the condition where the overlay container is not initially visible (ie. the style on the `.ol-overlay-container` is `display: none`) the rendered location is incorrect.  (See also #5459)

A call to `setPosition` on an overlay initiates a rendering sequence which should determine the position of the overlay within the map frame.  However, since the overlay position is determined before the container is visible the container's height and width cannot be taken into account when evaluating the overlay's `positioning` configuration.

Accordingly, the problem originates at [this point](https://github.com/openlayers/openlayers/blob/ac84e560bc4a2b7e0e37cf306decf0e676a9cf05/src/ol/overlay.js#L486) and [this point](https://github.com/openlayers/openlayers/blob/ac84e560bc4a2b7e0e37cf306decf0e676a9cf05/src/ol/overlay.js#L510) in `updateRenderedPosition` where the `offsetHeight` and `offsetWidth` properties of the container are `0`.

**Comment by tschaub** [comment]
I think you meant to open a pull request against [`openlayers:master`](https://github.com/openlayers/openlayers/compare/master...nagytech:overlay-offset-visible)

**Comment by nagytech** [comment]
Right you are, thanks.
