### ISSUE TITLE
Pinch zoom setting old behavior with constrainResolution does not work for two finger scroll. 

### ISSUE THREAD

**Issue by jun1111** [openlayers/openlayers#6572]
The release notes for 3.20.0 says: "Now the pinch zoom keeps the user selected zoom level even if it is a fractional zoom. To get the old behavior set the new constrainResolution parameter to true". 

We have set constrainResolution for PinchZoom like the following. However this does not work for two fingers scroll on trackpad. I am using an MacBook Pro. When two finger scroll finishes, the map almost always end with a fractional zoom value. 

      map = new OpenLayers.Map({
        target: target,
        layers: layerCollection,
        interactions: OpenLayers.interaction.defaults({
          altShiftDragRotate: false,
          dragPan: false,
          MouseWheelZoom: false,
          pinchRotate: false,
          pinchZoom: false
        }).extend([
          new OpenLayers.interaction.DragPan({
            kinetic: kinetic
          }),
          new OpenLayers.interaction.MouseWheelZoom({
            duration: duration
          }),
          new OpenLayers.interaction.PinchZoom({
            constrainResolution: true
          })
        ]),
        view: view
      });

**Comment by aAXEe** [comment]
I don't think that this kind of zooming is handled via the `PinchZoom` .. but I'm not sure.

Can you test the behaviour if you remove the `PinchZoom`?

```
  map = new OpenLayers.Map({
    target: target,
    layers: layerCollection,
    interactions: OpenLayers.interaction.defaults({
      altShiftDragRotate: false,
      dragPan: false,
      MouseWheelZoom: false,
      pinchRotate: false,
      pinchZoom: false
    }).extend([
      new OpenLayers.interaction.DragPan({
        kinetic: kinetic
      }),
      new OpenLayers.interaction.MouseWheelZoom({
        duration: duration
      })
    ]),
    view: view
  });
```

**Comment by aalbericio** [comment]
Hello,

**constrainResolution: true** does not work as expected in 4.3.3.

I've also set this option to "true" but I still get fractional zoom values. You can reproduce this by:

1) Start an animated zoom-in 
2) Before the end of the animation, perform a PAN
3) Get the fractional zoom :(

Obs: If I only ZOOM-in without any PANning, zoom gets integer values as expected.

Hope this can help on fixing the issue.

**Comment by jhwegener** [comment]
Still not working in 4.4.2!

**Comment by IsabellaAzu** [comment]
Still not working in v5.1.3...
(MacBook Chrome)
