### ISSUE TITLE
Suggestion: Usage section for other framework/library at README.md

### ISSUE THREAD

**Issue by allenhwkim** [openlayers/openlayers#6573]
Hi, thanks for this great module first.

I have spent some time to make this work conveniently with ReactJS, and I think this would be useful for other developers. The repository name is [react-openlayers](https://github.com/allenhwkim/react-openlayers).

Can you add the section like the following into README.md if you think it's useful for developers?

## Usage 
 * [React](https://github.com/allenhwkim/react-openlayers)
 * Other framework.

**Comment by fredj** [comment]
Hi,

We have a [page](http://openlayers.org/3rd-party/) that lists the OpenLayers plugins and libraries.
Please open a pull request at https://github.com/openlayers/openlayers.github.io (the file to update is https://github.com/openlayers/openlayers.github.io/blob/build/src/pages/3rd-party/index.hbs)
