### ISSUE TITLE
ol.source.Stamen throws 503s at certain zoom level thresholds

### ISSUE THREAD

**Issue by glenselle** [openlayers/openlayers#6574]
It appears the `ol.source.Stamen` tile source is trying to request tiles at zoom levels it doesn't support and in doing so, begins throwing 503s for every tile request. It also appears there are differing zoom levels to trigger the 503s depending on the location. It most often occurs at zoom levels 17-20. 

The following fiddle will throw nine 503s for every one of its tile requests.

http://jsfiddle.net/1mpu5afb/

**Comment by fredj** [comment]
I don't see any 503 errors in the jsfiddle, maybe a temporary issue?

**Comment by glenselle** [comment]
@fredj do a little panning, and then zoom way in and out -- it'll start happening -- it's very random

just tried it myself and here's what I'm seeing:

<img width="1437" alt="screen shot 2017-03-10 at 13 21 50" src="https://cloud.githubusercontent.com/assets/1056932/23809798/a79c47d8-0594-11e7-9094-183fe2a142c7.png">

**Comment by fredj** [comment]
yes, I also see some 503 error, always for the zoom level 18.
Stamen supports this zoom level but they apparently have some issues with their tile server
