### ISSUE TITLE
Will Bing Maps AJAX V7 Control ending have an effect on OpenLayers use of Bing?

### ISSUE THREAD

**Issue by flipper44** [openlayers/openlayers#6575]
Emails received
As announced in June 2016, end of life for Bing Maps AJAX V7 Control (V7) and SOAP Web Services offerings will take place on June 30, 2017.

Action: Migrate to Bing Maps Version 8 Control (V8) before June 30, 2017.

After June 30, support for the V7 control will end and service availability will no longer be guaranteed. To help avoid any unforeseen complications arising from migrating last minute, we encourage you to migrate to the V8 control prior to June.

**Comment by bartvde** [comment]
We are not using the AJAX control

**Comment by flipper44** [comment]
Thanks.
