### ISSUE TITLE
Feature style shouldn't be applied when it's not clustered in cluster layer

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#6576]
Hello,

I want to cluster features which is already existed as a feature object with some image icon. So, I created cluster layer and added them then it ignored features' style and just applied cluster layer's style on all of them when even feature is not clustered state which means there's no reason to show as clustered style.

here is the example from ol cluster example:
https://codepen.io/anon/pen/ryjveq

I think it'd be better if feature displays with its own style when it solely exist at its position.

Thanks,

**Comment by ahocevar** [comment]
You can easily achieve that with a custom style function. Something like inhttp://openlayers.org/en/latest/examples/earthquake-clusters.html.
