### ISSUE TITLE
Error using projection EPSG:404000

### ISSUE THREAD

**Issue by oonsamyi** [openlayers/openlayers#6584]
I just create a map with **view**:
```
this.map = new ol.Map({
  target: this.params.mapDOM,
  view: new ol.View({
    projection: 'EPSG:404000'
  })
});
```
But it does not work. Error:
**ol.js:112** _Uncaught TypeError: Cannot read property 'D' of null_

If I create a projection using the class [ol.proj.Projection](http://openlayers.org/en/latest/apidoc/ol.proj.Projection.html):
```
this.map = new ol.Map({
  target: this.params.mapDOM,
  view: new ol.View({
    projection: ol.proj.Projection({ code: 'EPSG:404000' })
  })
});
```
It is working.

**Comment by ahocevar** [comment]
That's expected, because OpenLayers does not come with a projection with code 'EPSG:404000'. Also note that `ol.proj.Projection` is a constructor, so it should be `new ol.proj.Projection({ code: 'EPSG:404000' })`.
