### ISSUE TITLE
Raster Source Example does not work

### ISSUE THREAD

**Issue by isuruAb** [openlayers/openlayers#6586]
Example which is in this page does not work properly in  edit view(https://codepen.io/pen?&editors=1110).
example : https://openlayers.org/en/latest/examples/raster.html?mode=raw
![screenshot from 2017-03-14 13-44-43](https://cloud.githubusercontent.com/assets/7692626/23891453/7593a30a-08bc-11e7-8a91-b337a5fccd15.png)

**Comment by ahocevar** [comment]
You need to insert your Bing API key, as shown in the source.
