### ISSUE TITLE
Shaded relief image tiles 16 bit images

### ISSUE THREAD

**Issue by NyakudyaA** [openlayers/openlayers#6587]
I am trying to render a shaded relief using the http://openlayers.org/en/latest/examples/shaded-relief.html with my custom srtm tiles. How did you generate png tiles that are 16bit with images? Most of the tools we found scale down the image to 8bit

**Comment by fredj** [comment]
We didn't generate them, we use the files from mapbox.
See https://www.mapbox.com/blog/dynamic-hill-shading/
