### ISSUE TITLE
geojson projection parsing

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#6591]
In this code block: https://github.com/openlayers/openlayers/blob/master/src/ol/format/geojson.js#L469

It can happen that people have set defaultDataProjection on the format, but because the GeoJSON has a CRS that is not known to ol, the readProjection will not return the defaultDataProjection in that case.

Shouldn't this look like:

```
  if (crs) {
    if (crs.type == 'name') {
      projection = ol.proj.get(crs.properties.name);
    } else if (crs.type == 'EPSG') {
      // 'EPSG' is not part of the GeoJSON specification, but is generated by
      // GeoServer.
      // TODO: remove this when http://jira.codehaus.org/browse/GEOS-5996
      // is fixed and widely deployed.
      projection = ol.proj.get('EPSG:' + crs.properties.code);
    } else {
      ol.asserts.assert(false, 36); // Unknown SRS type
    }
  }
  if (!projection) {
    projection = this.defaultDataProjection;
  }
}
```

so that it will always default to defaultDataProjection if not found?

**Comment by ahocevar** [comment]
I think the current behavior is correct. I think applications should be able to make a pre-flight check for available projections, and to load missing projections. If we added a new customisable function which gets called when `ol.proj.get` does not succeed, it would be easier to do that. Something like:
```js
ol.proj.setCreate(function(projCode) {
  // do something to load/define the projection
  return projection;
});
```
The default for that function could be a part of the current `ol.proj.get` function:
```js
function(projCode) {
  var projection = null;
  if (ol.ENABLE_PROJ4JS) {
    var proj4js = ol.proj.proj4.get();
    if (typeof proj4js == 'function' &&
        proj4js.defs(code) !== undefined) {
      projection = new ol.proj.Projection({code: code});
      ol.proj.addProjection(projection);
    }
  }
  return projection;
}
```
`ol.proj.get` could then look something like this:
```js
ol.proj.get = function(projectionLike) {
  var projection = null;
  if (projectionLike instanceof ol.proj.Projection) {
    projection = projectionLike;
  } else if (typeof projectionLike === 'string') {
    var code = projectionLike;
    projection = ol.proj.projections.get(code);
    if (!projection) {
      projection = ol.proj.create_(code);
    }
  }
  return projection;
};
```

**Comment by bartvde** [comment]
In the case I encountered, the projection is known, but not in the form of the crs tag in the GeoJSON (one of the EPSG urn forms). But I guess your suggestion could work for those cases as well. Or does proj4js handle the urn forms now (older versions did, not sure about the current proj4js).

**Comment by ahocevar** [comment]
proj4 does not handle that. So if you define a custom creator function, you could make it handle different urn formats too.
