### ISSUE TITLE
ol.Style.Icon offset/anchor + rotate

### ISSUE THREAD

**Issue by AnttiRumpunen** [openlayers/openlayers#6597]
Hi, I have the following problem: I have an wind direction arrow with coordinates and I have a background image which points to the same coordinate as wind direction arrow. This arrow needs to be moved to the correct position relative to the background image (inside the white circle) and rotated there. So far I haven't found a solution how to do it...

This is what I want to achieve: https://i.imgur.com/Fu7i9vX.png. This is the code I use: https://jsfiddle.net/AJR80/phwq2v1k/. In the JSFiddle wind arrow has large red background for testing purposes to see the image edges.

Is it possible to do what I want or is there a go around available?

Cheers,
Antti

**Comment by ahocevar** [comment]
It is possible by specifying a custom geometry for the 2nd style, with an offset from the original geometry. See https://jsfiddle.net/phwq2v1k/4/.

**Comment by AnttiRumpunen** [comment]
Thanks! I'll have a go with that solution!

**Comment by AnttiRumpunen** [comment]
Okay, it kind of worked since the code moves the arrow to new coordinates. I bit hackish way to solve the problem. Is there a way to solve this in another way with offsets/anchors whatever without altering coordinates? Was expecting Openlayers to support this kind of operation.

**Comment by Hgq1001** [comment]
How do you solve the rotation of the wind direction icon angle?
