### ISSUE TITLE
Map not render, after the click popup link!

### ISSUE THREAD

**Issue by alibarut** [openlayers/openlayers#6602]
Hi everybody.

I use popup link for google navigation but map is not render the after link click. This map canvas turn white board :)

This popup link
<a class="btn btn-default" href="http://maps.google.com/maps?daddr=37.856206,32.47161&amp;ll=" target="_blank">GİT</a>

Images attached.

![popup](https://cloud.githubusercontent.com/assets/1423055/24034039/5140afe6-0af8-11e7-81eb-1c6f5fa9eaf8.jpg)
![aferclick](https://cloud.githubusercontent.com/assets/1423055/24034040/51452fa8-0af8-11e7-9aa7-78d26e9debd7.jpg)

**Comment by alibarut** [comment]
I found solution. Popup **stopEvent** property set **true** resolve this problem. Thanks.

popup = new ol.Overlay({
                    element: element,
                    positioning: 'bottom-center',
                    stopEvent: true,
                    offset: [0, -50]
                });

**Comment by zhaoweijing2003** [comment]
i also meet this issue,when i close a dialog
