### ISSUE TITLE
Zoomify source doesn't support custom tile size

### ISSUE THREAD

**Issue by hajjimurad** [openlayers/openlayers#6608]
I use Zoomify tileSource to display images in high-resolution, but it uses fixed tile-size=DEFAULT_TILE_SIZE
I'd like to make a pull-request to make Zoomify supporting custom tile-size.
Would you accept that?

**Comment by fredj** [comment]
yes, thanks

**Comment by lasselaakkonen** [comment]
I needed this same feature and have implemented it in https://github.com/lasselaakkonen/openlayers/tree/6608-zoomify-custom-tile-size.

To implement this, I needed to pass `TileGrid` around. Maybe there is a way to access `TileGrid` from `Zoomify.Tile_`, which would avoid passing `TileGrid` around and storing `tileSize_`?

**Comment by martinweihrauch** [comment]
@lasselaakkonen: can you contact me as I have the same issue and we would like to implement it? you can e-mail me at info (at) smartinmedia (dot) com.
Thx, Martin

**Comment by fredj** [comment]
fixed with #6608
