### ISSUE TITLE
Zoom with box also selects text in page in IE11

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#6618]
![selection_144](https://cloud.githubusercontent.com/assets/319678/24155583/8910e38c-0e54-11e7-8160-1a2502975802.png)

**Comment by bartvde** [comment]
If the map has the focus, it doesn't happen

**Comment by fredj** [comment]
setting `-ms-user-select: none` to the viewport should do the trick (manually tested on https://www.browserstack.com/)

**Comment by bartvde** [comment]
but we have that set on the viewport already right?

**Comment by bartvde** [comment]
![selection_145](https://cloud.githubusercontent.com/assets/319678/24156329/8fe25cac-0e56-11e7-84e5-d27f4f42dcd5.png)

**Comment by fredj** [comment]
I thought the same but this css rule is for the child elements of the viewport

**Comment by fredj** [comment]
See https://github.com/openlayers/openlayers/blob/master/src/ol/map.js#L238-L246

**Comment by bartvde** [comment]
ah right it's set on the canvas element right now, so you suggest to move it to the parent div?

**Comment by fredj** [comment]
it was previously on the viewport (see 3c099a96b76b5396d8f667cd09fc807d25bae970) but it was changed later on (see 3d62b67172b4ab509ba506523baa3a13bb73da1c)

**Comment by bartvde** [comment]
let's ping @ahocevar since he was involved in those commits

**Comment by ahocevar** [comment]
I think this was a mistake on my end. The [selctor](https://github.com/openlayers/openlayers/commit/3d62b67172b4ab509ba506523baa3a13bb73da1c#diff-3516ee1642f5448498cb4ebff5a4db98R1) should have been changed to `.ol-viewport, .ol-unselectable`, not `.ol-viewport .ol-unselectable`.

**Comment by bartvde** [comment]
thanks @ahocevar I've opened up #6627 with that fix and confirmed it does the trick

**Comment by drnextgis** [comment]
It is impossible to select text in overlay-based popups after this change. Compare: [4.0.1](http://openlayers.org/en/v4.0.1/examples/popup.html) and [4.1.0](http://openlayers.org/en/latest/examples/popup.html). What about adding `user-select` option to `.ol-overlay-container`?

**Comment by ahocevar** [comment]
> What about adding user-select option to .ol-overlay-container?

@drnextgis Sounds reasonable. Do you want to create a pull request?
