### ISSUE TITLE
Create example for consuming ArcGIS vector tile package

### ISSUE THREAD

**Issue by cmortazavi** [openlayers/openlayers#6619]
It would be helpful to have an example of consuming an ArcGIS exploded vector tile map package.  As of right now there is no example to do so and users are not even sure if it's possible.  Note: ArcGIS vector tile packages only go to L15.  It seems like the rest is calculated on the fly.

**Comment by ahocevar** [comment]
I cannot provide immediate help on the example. But on a related note, I'm working on a pull request to avoid upscaling of pre-rendered vector tile images beyond Z15 in #6454. That's very much work in progress still though.

**Comment by cmortazavi** [comment]
Does this mean that openlayers cannot support ARCGIS generated vector tiles?

**Comment by ahocevar** [comment]
It can, but for now you have to configure the layer with `renderMode: 'vector'`.

**Comment by cmortazavi** [comment]
Ok so I try that and what happens is that it only goes to L15.  This is because ARCGIS generates vector tile packages with only 15 levels of detail.  So I'm wondering if I can zoom in past level 15 in openlayers even though there are only 15 levels of detail generated by ARCGIS.  And if there is a way to do this, how do I go about implementing this?  ArcGIS is able to consume their own packages and zoom in all the way to level 20 even though there are only 15 LOD's generated.  How are they doing this?

**Comment by ahocevar** [comment]
View resolutions / zoom levels are independent from layer source zoom levels. Just configure your tile grid properly, and leave the view's resolutions untouched. With `renderMode: 'vector'` on the vector tile layer, it will work out of the box.

**Comment by cmortazavi** [comment]
Andreas,

Thank you for your help and I appreciate it a lot but I still could not get it to work.  I apologize if I seem slow, vector tiles are new to me.

I did what you said but it still won't let me zoom in further.  Well, it'll let me zoom in but then the images/vectors become all pixelated.  I attached a zip with the html I'm using.  You can see the issue yourself (my tile server is hosted on the cloud.  Any help you can give on this would be much appreciated.

Thanks,
Cameron
[test20.zip](https://github.com/openlayers/openlayers/files/868682/test20.zip)

**Comment by ahocevar** [comment]
The `renderMode: 'vector'` property needs to be set on the `ol.layer.VectorTile` instance, not the `ol.source.VectorTile`.

**Comment by cmortazavi** [comment]
Oh wow.  Dumb mistake on my part.  This is awesome!  Thanks so much for your help! This is exactly what I was looking for.

**Comment by shunshizhechang** [comment]
I have a question : the name rule of VectorTile of geoserver is inconsistent with openlayers. for example,the number of VectorTile by geoserver (geojson) is [1,2,4,9],however  openlayers is  [1,4,8]. how to deal with this problem? thanks.

**Comment by ahocevar** [comment]
@shunshizhechang You'll need to specify a correct `tileGrid` on your `ol.source.VectorTile` instance.
