### ISSUE TITLE
WMS layers from ESRI fail on devices with "HiDPI"

### ISSUE THREAD

**Issue by darkpaw** [openlayers/openlayers#6621]
Layers from an ESRI WMS service fail when viewed on an iPad or Windows 7 Desktop with "Font size" set to 125%. Any other layers also stop working. 

We're using ol3-cesium, but I see that they are using the OL repo as a dependency.

I have tested a patch locally which replaces this assertion with just a console warning, and it seems to work OK:

https://github.com/openlayers/openlayers/blob/master/src/ol/source/imagewms.js#L288

```
- ol.asserts.assert(false, 8); // Unknown `serverType` configured
+ console.log("HiDPI not implemented for this server type. (" + this.serverType_ + ")");
```

ESRI software does seem to have a "dpi" setting, but crashing instead of falling back to standard DPI does seem like a bug that will show up for other servers.

**Comment by fredj** [comment]
What's the value of `serverType` ?

**Comment by darkpaw** [comment]
Ah, it was "esri", which I had assumed was there for a reason, but I see it's not in the list in the documentation. I suppose it still shouldn't crash at that point though, either ignore it for being invalid or raise an error on setting the invalid value initially? As it is, it just breaks the map.

Thanks!
