### ISSUE TITLE
Stability issues when zooming and panning OL3

### ISSUE THREAD

**Issue by knopr** [openlayers/openlayers#6624]
We are working on an application with OpenLayers. While the desired functionality is in place, we are encountering stability issues when panning and zooming in the map of the application. The app uses between 3 – 15 layers that are projected on a map that the user can show or hide. The amount of memory increases with every zoom and pan action, while it does not seem to be releases by the garbage collector. Eventually, the application becomes slower and crashes. There are no evident memory leaks or javascript errors when this happens. When looking at a regular example, on for instance https://openlayers.org/en/latest/examples/cluster.html, this behavior can be reproduced by zooming in and out for a while: the memory that the browser uses seems to keep growing. The difference with the app I’m working on is that is uses the entire screen and has a couple of layers, thus the problem emerges faster. 

My question: how can I prevent the app from crashing or release the memory? I’ve already tried cacheSize on the layers/ sources and OL4 (same behavior).

**Comment by ahocevar** [comment]
This is because the tile cache size can only be limited for the source's own tile cache, not for reprojected tile caches. I have just created #6626 to fix this.
