### ISSUE TITLE
ol.source.ImageWMS ratio of 1 not respected in v4.0.1 ?

### ISSUE THREAD

**Issue by theram** [openlayers/openlayers#6629]
In version 3.20.1, the below would display a single image, the size of the viewport, in v.4.0.1 it seems to request image double the size. 

Setting pixelRatio: 1 on the ol.Map, seems to 'fix' it (i.e. it requests an image the size of the viewport), however as I'm on a HDPI device, this isn't ideal.

(Apologies if I have missed a v3 - v4 change somewhere)

```
lyr = new ol.layer.Image({             
    source: new ol.source.ImageWMS({
         url: '/path/to/mapfile',
         params: {'LAYERS': 'layername', 'FORMAT': 'image/png', 'VERSION': '1.1.1'},
         ratio: 1,
         serverType: 'mapserver'
   })
});
```

**Comment by ahocevar** [comment]
is your goal to not request higher resolution images from the WMS? Then just remove the `serverType` configuration option.

**Comment by theram** [comment]
Thanks for quick response. 

Not really, the goal is to have a single high resolution image that fits the viewport exactly - it's a grid with labels round the edges. The image and those labels were appearing correctly in 3.20.1 on my MBP Retina, however in 4.0.1 the labels have disappeared off the edges. 

E.g.
In 3.20.1, the above OL config requested a high res 1200x1200 image that "fit" exactly in my 600x600 canvas

In 4.0.1, the same OL config seems to now request a 2400x2400 image, meaning labels round the edges etc. don't show.

Removing the serverType config option returns a 600x600 image, which do make the labels visible once again, however at lower resolution on my HDPI device, making them appear a touch fuzzy.

**Comment by ahocevar** [comment]
This is a regression, thanks for reporting. I created #6631, which should fix the regression. Can you please verify?

**Comment by theram** [comment]
Yep, that seems to have fixed it! Nice one thanks. Should I do anything further? (like close the issue? not sure of the etiquette... :)

**Comment by ahocevar** [comment]
The issue will be closed when the pull request is merged, so nothing more to do on your end.
