### ISSUE TITLE
Support for 3D WFS-T

### ISSUE THREAD

**Issue by Jenselme** [openlayers/openlayers#6630]
Currently the GML serializers will never use the Z coordinates when serialiazing a point. See:
- In GML2: [getCoords_](https://github.com/openlayers/openlayers/blob/master/src/ol/format/gml2.js#L473)
- In GML3: [writePos_](https://github.com/openlayers/openlayers/blob/master/src/ol/format/gml3.js#L566) and [getCoords_](https://github.com/openlayers/openlayers/blob/master/src/ol/format/gml3.js#L591)

This means that edition through WFS-T of 3D layers cannot work. What I expect is: edition works and OpenLayers uses the Z provided by the server in the `GetFeature` request.

I looked into it yesterday and even if it is easy to add the Z coordinates to the request, it is not easy in these methods to know if we are working with 3D geometries or not since OpenLayers will always add Z even if it is not present in the response from the server. We could add Z to all requests, even for 2D geometries, but, in this case, the WFS-T server is likely to reject the transaction.

The solution I see is to add a boolean `3D` option to `olx.format.WFSWriteTransactionOptions`. We could then use it to add or not the Z coordinate. Before doing this and proposing a PR, I would like feedback on this solution and eventually a better solution.

**Comment by Jenselme** [comment]
Any thoughts on this? I think WFS-T 3D could be a nice feature for OL.

**Comment by bartvde** [comment]
I agree it would be useful, and I can't think of a better solution than the one you outlined.
