### ISSUE TITLE
cant get ol.source to redraw tiles on tileurl changed when view projection is diffrent then source projection

### ISSUE THREAD

**Issue by pksorensen** [openlayers/openlayers#6632]
I have a ol source that based on a menu changes the tile url:
```
                           if (oldUrl !== url) {
                                oldUrl = url;
                                source.setTileUrlFunction((coord, a, p) => url.replace("{Z}", coord[0].toString()).replace("{X}", coord[1].toString()).replace("{Y}", (-coord[2] - 1).toString()));
                                source.changed();
                                source.refresh();
                            }
```
this works well when the view projection is the same as the source projection, but when a different view projection is used - the layer wont redraw before zooming to a new tile layer.

Is this by design or a bug that we can fix?

**Comment by ahocevar** [comment]
Sounds like a bug. Looks like reprojected tile caches are not cleared when the source changes. Do you want to try to fix it?

**Comment by pksorensen** [comment]
If its easy for someone else that knows exactly what to to, i dont mind not doing it :) But if time permits and no one else has done it before the weekend, i will give it some hours to try :)

**Comment by igorti** [comment]
Actually, this seems to be happening even when projection is the same. 

I tried to follow the code and it could track it down to the point that source's `canExpireCache` returns `true` and `scheduleExpireCache` on the `ol.renderer.Layer` is called but [this postRenderFunction](https://github.com/openlayers/openlayers/blob/v4.1.1/src/ol/renderer/layer.js#L153) never gets called. @ahocevar Any suggestion on what might be going on here and where to look further?

**Comment by ahocevar** [comment]
@igorti Does setting `loadTilesWhileAnimating: true` and `loadTilesWhileInteracting: true` on the map fix the issue for you?

**Comment by igorti** [comment]
@ahocevar No, unfortunately it doesn't help. It might still be a cache issue, since I noticed that explicitly calling `source.tileCache.clear()` does trigger tile reload. I guess it's not ideal though since accessing `tileCache` object is internal API only.

**Comment by ahocevar** [comment]
@igorti Out of curiousity: Does 5e3d522dfa9276dd8978fcef33c31ba59c623d56 fix your problem?

**Comment by igorti** [comment]
@ahocevar That commit doesn't seem to make any difference. But! Now that I was setting up a simplified example in Codepen for you, I came to realise that this problem is probably due to how I was changing source's url. I was composing it in the `getTileUrl` function and I was changing the url by setting some member variables that `getTileUrl` would then use and call `refresh` to trigger reload. I changed the code to set new url with `setUrl` method and it works perfect now. Sorry for hijacking this thread as it's probably not related to @pksorensen issue as I thought it was.

**Comment by yaugenka** [comment]
I face the same problem as @igorti described. When I had a tile source url updated via `setUrl` method the tiles were refreshing fine, but as soon as I utilized `tileUrlFunction` they won't update once loaded. If my url has changed and I  zoom the map then new tiles are loaded from the new url but zooming back to the original zoom level won't update the tiles (no call to  'tileUrlFunction' happens). Calling `source.changed()` method does increase the revision counter but won't update the tiles. Calling `source.refresh()` method does refresh the map but as far as notice visually it first clears the cache and then fetches new tiles. So probably it is something related to the cache.

**Comment by yaugenka** [comment]
Important to notice that my view and source projections are the same.
