### ISSUE TITLE
Fit to extent ignores maxZoom in OL 4.0.1

### ISSUE THREAD

**Issue by peder280370** [openlayers/openlayers#6640]
Hi,
I upgraded my project from OL 3.19.0 to OL 4.0.1, and as far as I can see, ol.View.fit() does not respect the "maxZoom" option anymore.

Example. When the olLayer in the snippet below is a vector layer with a single point, the view should zoom to the point at a zoom level of 12, however, it will in fact yield a zoom level of 28.
```
map.getView().fit(olLayer.getSource().getExtent(), map.getSize(), {
                                padding: [20, 20, 20, 20],
                                maxZoom: 12
                            });
console.log("ZOOM " + map.getView().getZoom()); // Prints out 28
```

**Comment by fredj** [comment]
The `fit` function arguments have changed in 4.0.0:
https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#simplified-olviewfit-api
