### ISSUE TITLE
getPixelFromCoordinate not working

### ISSUE THREAD

**Issue by mathiasleroy** [openlayers/openlayers#6647]
Using the latest version 4.0.1 (`<script src="//cdnjs.cloudflare.com/ajax/libs/openlayers/4.0.1/ol.js"></script>`)
, I can't get `getPixelFromCoordinate()` to give me other than `null` :

	var center = map.getView().getCenter();
	
	console.log('center', center);
	console.log('center proj', ol.proj.transform(center, 'EPSG:3857', 'EPSG:4326'));
	
	console.log(map.getPixelFromCoordinate(center));
	console.log(map.getPixelFromCoordinate([0, 0]));
	console.log(map.getPixelFromCoordinate(ol.proj.transform(center, 'EPSG:3857', 'EPSG:4326')));

would show in the console : 

>	center [8596889.351125063, 3330551.4114113324]
	center proj [77.22717099999998, 28.645093000000003]
	null
	null
	null

**Comment by simonseyock** [comment]
This is because the view is not initialized at that point. If you call this at a later point it will show the correct pixel coordinates. For example you can call it once on postrender.

See: https://codepen.io/anon/pen/GWYKQZ?editors=1011#anon-login

**Comment by mathiasleroy** [comment]
Thanks, that was it. 
I notice the response is exactly  `map.getSize())  / 2` which is available before the `map.once('postrender',  )`

    map.getSize().map(function(x) { return x / 2; })

And because of that I noticed it is only the center relative to the map itself, not the viewport / the whole visible page
