### ISSUE TITLE
OL4 zoom to feature(extent) with animation

### ISSUE THREAD

**Issue by lehmannwebdev** [openlayers/openlayers#6648]
Hi

I would like to change ol v3.20.1 to 4.0.1 but have a problem with zoom to feature with animation.
Example: https://jsfiddle.net/6gLweox7/3/

Old method "beforeRender(pan, zoomAnimation)" was removed from OLv4.

I can't find any example for solve this problem.

**Comment by ahocevar** [comment]
You can easily achieve this by passing a `duration` option as 2nd argument to `ol.View#fit()`:
```js
view.fit(vectorLayer.getSource().getExtent(), {duration: 1000});
```

**Comment by lehmannwebdev** [comment]
Thank you very much!

**Comment by kingofnull** [comment]
don't work please full working example for fit animate.

**Comment by ahocevar** [comment]
See https://codepen.io/ahocevar/pen/GQWYRb?&editors=1010# for a working example.

**Comment by kingofnull** [comment]
thanks so much. that was my bad. Sorry
