### ISSUE TITLE
Allow for better scale dependant styling in vector tiles

### ISSUE THREAD

**Issue by cmortazavi** [openlayers/openlayers#6650]
Consider the following situation.  Vector Tiles  up to L15 are generated and the features are being displayed via vector renderType.  If a feature is suppose to only show up at level 19 it will be in the level 15 tile and the styling information for the layer will show it as as having a certain (minScale).  The problem is that the style function of the vector source is not being hit when you zoom past level 15 (I'm assuming the style function is the place where you decide whether or not to show the feature).  Therefore we must either show the feature at L15 and below or not show it at all

**Comment by ahocevar** [comment]
For now, you have to configure your `ol.layer.VectorTile` instance with `renderMode: 'vector'` to get the desired result.

In the future, pre-rendered images will be generated for all zoom levels - even those that are not provided by the source.

**Comment by cmortazavi** [comment]
I'm not sure this solves the issue.  The issue is that I have features that are only suppose to be shown at L17, L18, and L19.  My tiles only go from 0-15.  The features are in the L15 tile.  So far so good.  

The layer has a minzoom=17 so my thought here is to limit the extent of the feature in the style function.  Here I can check the resolution and decide whether or not the map is at the correct scale to display the feature.  So at L15 the style function determines not to show this feature.  However, the style function doesn't get hit again when I zoom down to L16 or L17 or deeper,  

Is there another way where I can achieve what i want?

**Comment by cmortazavi** [comment]
By the way, renderMode is already set to vector.

**Comment by ahocevar** [comment]
@cmortazavi What you are seeing is another issue that will be fixed with the planned improvements.

**Comment by cmortazavi** [comment]
Oh ok I see.  Thank you.  We could greatly benefit from this improvement.
