### ISSUE TITLE
Pan feature in ol3 don´t work in mobile chrome

### ISSUE THREAD

**Issue by nunogomes123** [openlayers/openlayers#6651]
The exemples in http://tsauerwein.github.io/ol3/mapbox-gl-js/examples/ don´t work when I try pan in mobile chrome in my smartphone. The pan dont wont in my mobile chrome, but are working in my mobile IE. These exemples are working in my descktop chrome. Same months ago these exemples were working in my mobile chrome, but some update damaged the pan feature in maps. What can I do to fix?

**Comment by ahocevar** [comment]
The official examples are hosted at https://openlayers.org/en/latest/examples/. Those should work for you, don't they?

**Comment by nunogomes123** [comment]
The exemples with ol4 are working, but the problem is with exemples with ol3. My project is using ol3...

**Comment by bartvde** [comment]
All examples are available per version, e.g. http://openlayers.org/en/v3.19.1/examples/ for 3.19.1

**Comment by nunogomes123** [comment]
For exemple. This exemplo doesn´t work: http://openlayers.org/en/v3.2.1/examples/accessible.html
I am using v3.2.1 and I can´t change now. 
How do I fix this issue?

**Comment by bartvde** [comment]
v3.2.1 is too old, you can't expect us to answer this

**Comment by nunogomes123** [comment]
ok, I understand!
