### ISSUE TITLE
Google Map with openlayers 4

### ISSUE THREAD

**Issue by nunogomes123** [openlayers/openlayers#6653]
I can use ol4 with google maps? They have a good integration?
In ol3 I had a lot of problems with integration ol3 and google maps.

**Comment by bartvde** [comment]
It's the same with 4

**Comment by osamaahmed32** [comment]
Most of my target is Dubai. but later it will be applied to other countries. Map zoomin, zoomout and bottom text from openstreetmap is coming but map is not coming. sometimes it comes when I try to zoomin 2 times.

I am using this code

<style>
 .qvvenuemap {
    height: 500px;
    width: 100%;
 }
</style>

<div class="qvvenuemap" id="venuemap"></div>

<script src="https://openlayers.org/api/OpenLayers.js"></script>
<script>
window.onload =  function(){
	initvenue();
};

function initvenue() {
    var mymap = new OpenLayers.Map("venuemap");
    mymap.addLayer(new OpenLayers.Layer.OSM());

    var lonLat = new OpenLayers.LonLat( 55.2778 ,25.1987 )
          .transform(
            new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
            mymap.getProjectionObject() // to Spherical Mercator Projection
          );
          
    var zoom=15;

    var markers = new OpenLayers.Layer.Markers( "Markers" );
    mymap.addLayer(markers);
    
    markers.addMarker(new OpenLayers.Marker(lonLat));
    
    mymap.setCenter (lonLat, zoom);
}
</script>

in console I am getting this

Uncaught TypeError: Cannot read property 'w' of null
    at initialize.adjustZoom (OpenLayers.js:185)
    at initialize.zoomTo (OpenLayers.js:195)
    at initialize.zoomIn (OpenLayers.js:197)
    at d.onZoomClick (OpenLayers.js:742)
    at initialize.triggerEvent (OpenLayers.js:138)
    at initialize.buttonClick (OpenLayers.js:146)
    at initialize.triggerEvent (OpenLayers.js:138)
    at initialize.handleBrowserEvent (OpenLayers.js:138)
    at HTMLDivElement.<anonymous> (OpenLayers.js:63)
