### ISSUE TITLE
ol.geom.Geometry.transform('EPSG:4326', 'EPSG:3857') return different shape geometry

### ISSUE THREAD

**Issue by RenoSun** [openlayers/openlayers#6656]
I was using Turf.js to create the buffer geometry from my geojson (LL84), and try to use OL3 transform the buffer result to (WGS 84 / Pseudo-Mercator)
`var geojson = val.geometry;

geojson = turf.buffer(geojson, $('#bufferDist').val(), $('#bufferUnit').val());

geojson = geojson.geometry;   

geojsonWGS84P = geojson.geometry;    

var buffFeatures = (new ol.format.GeoJSON()).readFeatures(geojson);

var buffFeaturesWGS84P = (new ol.format.GeoJSON()).readFeatures(geojson);

console.log(GeomToWKT(buffFeatures[0].getGeometry()));

console.log(GeomToWKT(buffFeaturesWGS84P[0].getGeometry().transform('EPSG:4326', 'EPSG:3857')));
....`

(WKT Format To Show The Difference) ()
Buffer Geometry Originally With Correct Shape in LL84(EPSG:4326)
POLYGON((-124.43847495785431 49.350874677789,-124.43847002149431 49.351197398726995,-124.43846804522627 49.35121481977854,-124.43846272532966 49.35123152598614,-124.43845426412847 49.35124688198649,-124.43844298341547 49.35126030376679,-124.43842931221388 49.35127128087569,-124.43841377046097 49.35127939583649,-124.43839694923399 49.351284340024506,-124.4383794882706 49.3512859254045,-124.4380445360306 49.351283541776496,-124.43802690416622 49.351281667755906,-124.43800998301558 49.35127636971326,-124.43799443076253 49.3512678537271,-124.43798085234478 49.351256451044684,-124.43796977592353 49.3512426051974,-124.43796163233955 49.351226854748674,-124.43795673835473 49.35120981234546,-124.43795528433093 49.351192140887974,-124.43796066409092 49.350869571426976,-124.43796266011002 49.35085217317054,-124.43796799115303 49.35083549194157,-124.43797645494378 49.350820160677245,-124.43798773033998 49.35080676109293,-124.4380013895184 49.35079580161009,-124.4380169142078 49.35078769806524,-124.43803371535363 49.35078275793181,-124.43805115546871 49.350781168653675,-124.43838566430871 49.35078340080468,-124.43840328667955 49.35078526487022,-124.4384202010948 49.35079054930493,-124.43843575041089 49.35079904880275,-124.4384493305198 49.35081043314883,-124.4384604138194 49.35082426004884,-124.43846856971133 49.35083999231252,-124.43847348133023 49.35085701872418,-124.43847495785431 49.350874677789))
![image](https://cloud.githubusercontent.com/assets/5566783/24466982/939c6ace-1467-11e7-8d83-718640be3739.png)

Buffer Geometry Transformed With Incorrect Shape from LL84(EPSG:4326) to WGS 84 / Pseudo-Mercator (EPSG:3857)
POLYGON((-13852427.667399867 6334608.560003408,-13852427.117886787 6334663.708715286,-13852426.897889635 6334666.685751363,-13852426.30568145 6334669.540630686,-13852425.363784842 6334672.164777557,-13852424.108021617 6334674.458391265,-13852422.586150419 6334676.334241798,-13852420.856050398 6334677.720987309,-13852418.983519975 6334678.565887439,-13852417.039774423 6334678.83680915,-13852379.753061626 6334678.429476793,-13852377.79029146 6334678.109230016,-13852375.906637589 6334677.203860594,-13852374.175368698 6334675.748584948,-13852372.663826147 6334673.800009371,-13852371.430804577 6334671.433928135,-13852370.524264952 6334668.742375268,-13852369.979469055 6334665.830044652,-13852369.817607867 6334662.810217703,-13852370.416480009 6334607.687397028,-13852370.638675839 6334604.714277215,-13852371.232124832 6334601.863688392,-13852372.17430971 6334599.243790519,-13852373.429481072 6334596.953990312,-13852374.950013857 6334595.081169537,-13852376.678214375 6334593.696388479,-13852378.548509376 6334592.852189752,-13852380.489934105 6334592.580604676,-13852417.72728784 6334592.962047604,-13852419.68900119 6334593.280589954,-13852421.571905281 6334594.183624938,-13852423.302847233 6334595.63606884,-13852424.81457804 6334597.581492877,-13852426.048365306 6334599.944315507,-13852426.956275044 6334602.632738779,-13852427.503033958 6334605.542314763,-13852427.667399867 6334608.560003408))
![image](https://cloud.githubusercontent.com/assets/5566783/24467142/33c59ebc-1468-11e7-943b-56a72a6e5d1e.png)

Expected correct result in (EPSG:3857) should be looks like following after the transform:
POLYGON((-13852433.041088914 6334608.478287566,-13852432.491575914 6334663.626997866,-13852432.165765489 6334666.62646258,-13852431.260703495 6334669.504622373,-13852429.81121335 6334672.150736377,-13852427.873066032 6334674.462991982,-13852425.520834234 6334676.352422205,-13852422.84502307 6334677.746328808,-13852419.948587788 6334678.59107946,-13852416.94297243 6334678.854171301,-13852379.656260429 6334678.446839701,-13852376.659029001 6334678.118553629,-13852373.78342717 6334677.211866205,-13852371.139954286 6334675.761618264,-13852368.830189794 6334673.823537778,-13852366.94288989 6334671.472098422,-13852365.550576927 6334668.79765781,-13852364.706752637 6334665.902985368,-13852364.443842245 6334662.899313265,-13852365.042713245 6334607.776490865,-13852365.370597754 6334604.78029465,-13852366.276487913 6334601.90556631,-13852367.72559829 6334599.262693038,-13852369.662284242 6334596.953158988,-13852372.01217863 6334595.065648356,-13852374.685047448 6334593.672639995,-13852377.57825474 6334592.827624273,-13852380.58070374 6334592.563049097,-13852417.81805774 6334592.944492797,-13852420.815099165 6334593.270652209,-13852423.690954318 6334594.1751379175,-13852426.335144877 6334595.623203365,-13852428.646092108 6334597.559219937,-13852430.535019081 6334599.908813976,-13852431.92936113 6334602.58172391,-13852432.775553463 6334605.475267722,-13852433.041088914 6334608.478287566))
![image](https://cloud.githubusercontent.com/assets/5566783/24467333/eb592e18-1468-11e7-862b-4d03858fd6c9.png)

**Comment by ahocevar** [comment]
Your unexpected result looks expected to me. If you want your expected result, you have to buffer Web Mercator coordinates, not WGS84 coordinates.

**Comment by RenoSun** [comment]
Yeah, I directly buffer the GeoJson in WGS84.Pseudo-Mercator coordinate system, and I have to adjust the buffering value to get my expected buffer polygon. So...transform the original feature geometry (LL84) into WGS84.Pseudo-Mercator coordinate first, and then buffer it will work. However, if I buffer the feature in LL84 first, and then transform the buffered feature geometry into WGS84.Pseudo-Mercator will return the result that I don't expect to see.

http://www.gistutor.com/concepts/9-beginner-concept-tutorials/46-gis-buffer.html

**Comment by RenoSun** [comment]
I think Turf.js did the Geodesic Buffering with my LL84 geojson, and I transform the result geojson it into WGS 84.Pseudo-Mercator. Therefore, it will not give me the result that I expected to see that only Euclidean Buffering will provide me. Should always transform the original feature into the final coordinate system of the buffering result first, than buffer it with the appropriate buffering method in order to get the correct result.
