### ISSUE TITLE
Y-axis direction for ol.source.Vector

### ISSUE THREAD

**Issue by hajjimurad** [openlayers/openlayers#6665]
I use **ol.source.Zoomify** as a source for tiles and **ol.source.Vector** on top of it to display shapes.
But the problem is that the shapes have coordinates based of another coordinates system (left-top corner as a center and Y-axis points downwards), and they appear in wrong places. 
![image](https://cloud.githubusercontent.com/assets/11183111/24611538/c02616de-1882-11e7-986c-5f6f74990db3.png)
You can play with that here: https://jsfiddle.net/muradx/of0eu5km/3/

Therefore I have to put minus before every y-coordinate, which is dirty, because I use it in lots of the places.

I can't just convert coordinates in th DB to the fit coordinate system of OpenLayers (where Y-axis points upwards), because the data is also used in another applications.

I've also found such reply to a bit similar situation: http://gis.stackexchange.com/questions/203081/direction-of-the-y-axis-in-openlayers/203090, but the annotations there are loaded altogether with GeoJSON and this is not my case, since I create annotations one by one.

How can I override such behavior?

**Comment by ahocevar** [comment]
You can use something like `ol.proj.transform()` to transform coordinates manually.

**Comment by hajjimurad** [comment]
That was my first idea, but **ol.source.Vector** doesn't support projections. Here is the source code

```
ol.source.Vector = function(opt_options) {
  var options = opt_options || {};

  ol.source.Source.call(this, {
    attributions: options.attributions,
    logo: options.logo,
    projection: undefined,
    state: ol.source.State.READY,
    wrapX: options.wrapX !== undefined ? options.wrapX : true
  });

...
}
```

**Comment by ahocevar** [comment]
That's why you need to transform coordinates before adding them to the vector source, unless you configure your source with a `url`.
