### ISSUE TITLE
The units of getRadius on circles depends upon the current map projection

### ISSUE THREAD

**Issue by andrewkfiedler** [openlayers/openlayers#6668]
I'm not sure the history behind the decision or if there was intention behind it (I couldn't find any open or closed issues relating to it).

Is there a reason for coupling the measurement units to the projection units?  

I would prefer it stay in one consistent unit of measurement (preferably meters), but I'm interested to hear what others think.

**Comment by ahocevar** [comment]
The radius of a circle is not really a measurement, but a construction parameter. Hence it's units is map units, just like the center coordinate. You can easily convert the result of `getRadius()` into a geodesic measure in meters. See the http://openlayers.org/en/latest/examples/measure.html example for inspiration.

**Comment by andrewkfiedler** [comment]
I ended up using `getMetersPerUnit` to do this.  Thanks for the reply.
