### ISSUE TITLE
KML file doesn´t fit

### ISSUE THREAD

**Issue by nunogomes123** [openlayers/openlayers#6674]
Hi,

I am importing KML files to my map, but aren´t fit.
I am using the code: map.getView().fit(KMLSource.getExtent(), map.getSize());
The KMLSource.getExtent() show infinity values:
 0:Infinity
 1:Infinity
 2:-Infinity
 3:-Infinity

What can I do to have correct values in my KMLSource.getExtent() and center my KML in my map?

Thanks,
Nuno

**Comment by ahocevar** [comment]
Looks like your KML data is not loaded yet. Try
```js
var key = KMLSource.on('change', function() {
  if (KMLSource.getState() == 'loaded') {
    ol.Observable.unByKey(key);
    map.getView().fit(KMLSource.getExtent());
  }
});
