### ISSUE TITLE
upload kml file

### ISSUE THREAD

**Issue by nunogomes123** [openlayers/openlayers#6676]
Hi,

I am trying to upload a kml file to my map, but it isn´t working. I am using OL4.
My code Source is:
                    var kmlSource = new ol.source.Vector({
                        projection: 'EPSG:3857',
                        text: e.target.result   //my kml file 
                    });

Is something wrong with my source?

Thanks
Nuno

**Comment by ahocevar** [comment]
There is no `text` option on `ol.source.Vector`, and I doubt that your KML's `projection` is `'EPSG:3857'`. Why don't you configure your `ol.source.Vector` with the `url` of the source instead?

**Comment by nunogomes123** [comment]
Hi,
I would like to configure my ol.source.Vector with the url, but how to get it from my uploaded kml file?
I am using a FileReader. My code is:

            reader.onload = (function (theFile) {
                return function (e) {

                    var kmlSource = new ol.source.Vector({
                            url: ???,
                            format: new ol.format.KML()
                    });

                    loadLayerFromFile(kmlSource);

                };
            })(f);

Thanks,
Nuno
