### ISSUE TITLE
get url from a upload kml file

### ISSUE THREAD

**Issue by nunogomes123** [openlayers/openlayers#6678]
Hi,
I am trying to upload a kml file to my map, but it isn´t working. I am using OL4.
I would like to configure my ol.source.Vector with the url, but how to get it from my uploaded kml file?
My code is:

function handleFileSelect(evt) {

    var files = evt.target.files;
    for (var i = 0, f; f = files[i]; i++) {

        if (f.name.indexOf(".kml") != -1) {
            var reader = new FileReader();

        reader.onload = (function (theFile) {
            return function (e) {

                var kmlSource = new ol.source.Vector({
                        url: ???,
                        format: new ol.format.KML()
                });

                loadLayerFromFile(kmlSource);

            };
        })(f);
            reader.readAsText(f);
        }
}
}

Thanks,
Nuno

**Comment by ahocevar** [comment]
You cannot configure `ol.source.Vector` with a `url` if your data comes from a `FileReader`. Instead, you will have to parse the file manually with `ol.format.KML#readFeatures`, and use the `features` config option of `ol.source.Vector`.
