### ISSUE TITLE
Using removeLastPoint should set a new this.finishCoordinate_

### ISSUE THREAD

**Issue by rmichaelis** [openlayers/openlayers#6684]
When using removeLastPoint on a LineString, the this.finishCoordinate_ should be set with the new last coordinate of the LineString.
Otherwise to click on location of the just removed coordinate will cause the drawing to end.
https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/draw.js#L611

**Comment by fredj** [comment]
confirmed
