### ISSUE TITLE
Performance issue on Firefox with layer extent

### ISSUE THREAD

**Issue by tchandelle** [openlayers/openlayers#6685]
We have a lot of layers to display (more than 200). On Chrome and IE, there is no problems. But on Firefox, big performance issue, moving on the map is very slow.

But if I remove the `extent` on my 200 `ol.layer.Image`, it's nearly as fast as the other browser.

**Comment by tchandelle** [comment]
Here is an example, compare it with different browsers, and remove the extent to see the difference.

https://codepen.io/tchandelle/pen/wJVyEq

**Comment by tchandelle** [comment]
The code causing the problem is [src/ol/renderer/canvas/layer.js:63-68](https://github.com/openlayers/openlayers/blob/55ace18509913e576a92469c0ae9f481d0cca9fa/src/ol/renderer/canvas/layer.js#L63-L68). Couldn't we clip the image only if it's larger than the extent ?

**Comment by ahocevar** [comment]
Actually you'd only want to clip it if the layer extent intersects the view extent, but not if it contains the view extent. Do you want to create a pull request?

**Comment by tchandelle** [comment]
Yes, that's what I had in mind. Submitting now ...
