### ISSUE TITLE
WFS GML3 does not have correct srsProjection

### ISSUE THREAD

**Issue by Hanmac** [openlayers/openlayers#6688]
i have wfs/gml3 in the following form:
```xml
<wfs:FeatureCollection xmlns:gml="http://www.opengis.net/gml" xmlns:wfs="http://www.opengis.net/wfs" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd http://www.opengis.net/gml http://schemas.opengis.net/gml/3.1.1/base/gml.xsd">
    <gml:boundedBy>
        <gml:Envelope srsName="EPSG:4326">
            <gml:lowerCorner>47.141223013472548 5.5612518515690752</gml:lowerCorner>
            <gml:upperCorner>55.102916878371701 15.578555265395364</gml:upperCorner>
        </gml:Envelope>
    </gml:boundedBy>
    <gml:featureMember>
    </gml:featureMember>
</wfs:FeatureCollection>
```
with the srsName inside the Envolope in the head of wfs instead of the gml extra.

that might be fixed with extending ``ol.format.WFS.prototype.readProjectionFromNode`` with this:
```javascript
if (node.hasAttribute('srsName')) {
    return node.getAttribute('srsName');
}
```

==
currently inside a loader i do `` format.readFeatures(response);``

```javascript
new ol.source.Vector({
    format: new ol.format.WFS({
        gmlFormat: new ol.format.GML3()
    }),
    loader: function(extent, resolution, projection) {
        var src = this;
        //local file
	$.ajax('vg.gml').then(function(response) {
             // THIS function does not return the correct value
	     srcProjection = src.getFormat().readProjection(response);
             data = src.getFormat().readFeatures(response);

             
             // need to switch X and Y because for unknown reason the data is wrong
            for (var i=0;i<data.length;i++) {
                data[i].getGeometry().applyTransform(function (coords, coords2, stride) {
                    for (var j=0;j<coords.length;j+=stride) {
                         var y = coords[j];
                         var x = coords[j+1];
                         coords[j] = x;
                         coords[j+1] = y;
                     }
                });
                // needed to get from srcProjection to wanted projection
                data[i].getGeometry().transform(srcProjection, projection);
            }
		
            src.addFeatures(data);
        });
    }
})
```

it works correct for now but it does not when the features / the file is in a different projection then the map view projection.

i needed the swap of  the X and Y values, for some reason. (the service url does return gml2 and gml3 data, but i use gml3 one) openlayers3 has no option for

also i am not sure why the ``getGeometry().transform`` is needed.

I currently have v3.20.1 but the source of v4 shows it might not be fixed there.

might be related to #6235

**Comment by Hanmac** [comment]
i found more reason why WFS + GML is still wrong.

in addition for ``ol.format.WFS.prototype.readProjectionFromNode``
```javascript
if (node.hasAttribute('srsName')) {
    return node.getAttribute('srsName');
}
```

``ol.format.WFS.prototype.readFeaturesFromNode`` does need to read the Projection like
```javascript
  var context = /** @type {ol.XmlNodeStackItem} */ ({
    'featureType': this.featureType_,
    'featureNS': this.featureNS_,
    'srsName' : this.readProjectionFromNode(node)
  });
```

And ``ol.format.GMLBase.prototype.readGeometryElement`` does need to take care if the context already has srsName.
so setting it there does reset the data.
For that i don't have an idea yet how to fix that.

**Comment by MkkOF** [comment]
have met the problem, but no idea

**Comment by Hanmac** [comment]
@MkkOF i did try it there:
https://github.com/openlayers/openlayers/compare/master...Hanmac:master
but i didn't manage to check if it works that way.

i tested the changes on a compiled copy, but didn't manage to test the changes with a build
(currently not on a system to do a test-build)

**Comment by Hanmac** [comment]
you guys need to check this problem if i can get a 'Pull request accepted' label for this
