### ISSUE TITLE
Uncaught TypeError: a.addEventListener is not a function

### ISSUE THREAD

**Issue by hamzasanoma** [openlayers/openlayers#6690]
I am using requirejs to include the library in the project and I get this error, but if I include it in the head tag of the html page it works fine! any help?

**Comment by hamzasanoma** [comment]
Got it.

**Comment by spongessuck** [comment]
What was it?

**Comment by nickdb93** [comment]
@hamzasanoma I really don't even know what to say to you right now, but I know I want it to be mean. I'll settle for this:

Please post your explanation.

**Comment by leonardofmed** [comment]
In my case the problem was a missing `Polygon()` declaration:
````
let my_layer = new VectorLayer({
	source: new VectorSource({
		features: new Feature({
			geometry: new Polygon(polygon), // <- Missing new Polygon() here
			name: 'My Polygon'
		})
	}),
	style: new Style({
		stroke: new Stroke({
			color: '#319FD3',
			width: 1
		})
	})
});
this.map.addLayer(my_layer);
````
