### ISSUE TITLE
Compiling v. 4.0.1 with Closure Compiler throws warnings

### ISSUE THREAD

**Issue by BogusII** [openlayers/openlayers#6698]
When trying to follow [this](https://openlayers.org/en/latest/doc/tutorials/closure.html) tutorial, I'm flooded with Closure Compiler warnings (more than 1700) "bad type annotation" (with the types like ol.Coordinate, ol.Size etc.).
I can't find the definisions of these types in any file of the current code (4.0.1), as I could find them in older version (namely 3.14.2). Is it an issue with current version, or am I missing something?

**Comment by cs09g** [comment]
In my case, I've not counted how many but it makes a lot of "ERR! compile". Weird thing is it works very well. One of them is "ERR! compile externs/olx.js:4429: WARNING - Bad type annotation. Unknown type TileJSON"

**Comment by marcjansen** [comment]
@BogusII & @cs09g Can you please check if the changes in #6704 fix your issue? TIA

**Comment by cs09g** [comment]
@marcjansen I actually uses [this way](https://github.com/openlayers/openlayers/tree/master/tasks) for my custom build. then I guess 'typedef.js' is being automatically added but it still occurs the same.

**Comment by BogusII** [comment]
@marcjansen Yes, this change fixes my issue. I'd overlooked the typedefs.js file while searching for type definisions somehow. Thanks a lot!
