### ISSUE TITLE
ol.tilegrid.WMTS.createFromCapabilitiesMatrixSet

### ISSUE THREAD

**Issue by mpnewcomb** [openlayers/openlayers#6699]
I'm not sure how WMTS is working correctly. WMTS document says tile coordinates (row, column) are positive, but after parsing a capabilities document, the tile sizes have negative values.

In ol-debug.js, line 76628, it says: "top-left origin, so height is negative"... nowhere in the WMTS spec is this true.

Bottom line, I'm getting negative tile coordinates from the WMTS layer which should not be possible...

**Comment by sz332** [comment]
Hello, we are facing probably the same issue.

We tried to work with WMTS and a custom gridset configured in Geoserver, and Openlayers is not rendering anything, although the returned capabilities XML file looks correct.

**Comment by filipheymans** [comment]
I've encountered a similar problem (maybe the same), i'm using 3 different wmts base layers. The first layer renders ok. The other 2 renders nothing, I'm using the following code to render each of them:
`        
fetch('https://tile.informatievlaanderen.be/ws/raadpleegdiensten/wmts?service=wmts&version=1.1.0&request=GetCapabilities').then(function(response) {
        return response.text();
      }).then(function(text) {
        var parser = new ol.format.WMTSCapabilities();
        var result = parser.read(text);

        var options = ol.source.WMTS.optionsFromCapabilities(result, {
          layer: 'grb_bsk',
          matrixSet: 'GoogleMapsVL',
          style: 'default',
          format: 'image/png'
        });

          var layer = new ol.layer.Tile({
            source: new ol.source.WMTS(/** @type {!olx.source.WMTSOptions} */ (options))
          });
          map.addLayer(layer);`

I did some debugging in the OL code and noticed an empty matrix set is returned by
ol.tilegrid.WMTS.createFromCapabilitiesMatrixSet().
![image](https://user-images.githubusercontent.com/20460813/29447120-8af7a5d4-83f0-11e7-8143-1e33115165ae.png)

The function does not match an available matrix set when the TileMatrix identifiers don't get prefixed by their TileMatrixSet identifier.

**Comment by filipheymans** [comment]
I have a PR ready for review

**Comment by ahocevar** [comment]
cc @fredj @bartvde, would you accept that fork as a pull request?

**Comment by bartvde** [comment]
@filipheymans can you show the GetCapabilities output of that service please?

**Comment by fredj** [comment]
@bartvde the capabilities should be this one:
https://tile.informatievlaanderen.be/ws/raadpleegdiensten/wmts?service=wmts&version=1.1.0&request=GetCapabilities

**Comment by fredj** [comment]
Looks like this prefix is optional (but I found nothing about it in [the spec](http://www.opengeospatial.org/standards/wmts)), our test capabilities (from IGN) doesn't use a prefix.

**Comment by fredj** [comment]
@filipheymans a pull request  would be greatly appreciated, thanks !

**Comment by filipheymans** [comment]
I've created a possible fix for this case, please provide any feedback. 

@fredj Yeah, the specs aren't very clear about if the tile matrix identifier should be prefixed or not: only that it should be unique IN its tile matrix set.

**Comment by jbelien** [comment]
Well, that's funny ! I'm struggling with WMTS in OpenLayers ... I'm looking for some explanation/help in the issues and I find an issue speaking about `tile.informatievlaanderen.be`, the WMTS I'm struggling with ! Quite unexpected ! 😂 

Any update on that issue ? Can #7167 be merged ?
Thanks !

**Comment by bampakoa** [comment]
I am facing the same issue with @mpnewcomb . I am getting negative tile coordinates resulting in TileOutOfRange exception when using **https://geoportal.asig.gov.al** in [this](https://codepen.io/bampakoa/pen/vRKvWW?editors=0110) codepen. Any help you would be really appreciated.

Thanks

**Comment by jbelien** [comment]
@fredj Friendly ping ; could PR #7167 could be reviewed ? Thanks :)

**Comment by fredj** [comment]
@jbelien I'm on it
