### ISSUE TITLE
getPixelFromCoordinate breaks after map scroll wraps

### ISSUE THREAD

**Issue by squaregoldfish** [openlayers/openlayers#6700]
If you scroll a map in one direction all the way round the globe, getPixelFromCoordinate starts to give invalid coordinates.

As an example (screenshot from Chrome console below):
* Load a map, centred roughly on [0, 0]
* `map.getPixelFromCoordinate([0, 0])` returns a reasonable answer
* Scroll east, going all the way around the world to cross the Atlantic and return to [0, 0]
* `map.getPixelFromCoordinate([0, 0])` now gives a negative x pixel value, even though the same point is visible on the screen.

I've tried this on a few maps from the examples page, and I get the same result, so I don't think I've done anything silly.

I haven't dug deeply into this, but it seems to be an issue with the `frameState.coordinateToPixelTransform` not taking the wraparound into account.

I'll look into either a fix or workaround and add my findings...

**Comment by ahocevar** [comment]
The behaviour you are seeing may be unexpected, but it is intentional. Because when you went around the world once, the pixel for `[0, 0]` is way beyond the visible viewport. However, `map.getPixelFromCoordinate([180, 0])` should return the same pixel that you had with `[0, 0]` before going around the world.

**Comment by squaregoldfish** [comment]
`map.getPixelFromCoordinate([180, 0])` doesn't work - it always gives the same result as `map.getPixelFromCoordinate([0, 0])` or any multiplications of 180.

**Comment by ahocevar** [comment]
Sorry, I meant multiplications of 360. Here is what you can do to see how it works, e.g. in https://openlayers.org/en/latest/examples/simple.html:
```js
map.getPixelFromCoordinate(ol.proj.fromLonLat([0, 0])); // [543, 200]
map.getView().setCenter(ol.proj.fromLonLat([360, 0]));
map.getPixelFromCoordinate(ol.proj.fromLonLat([0, 0])); // [-481, 200] - outside viewport
map.getPixelFromCoordinate(ol.proj.fromLonLat([360, 0])); // [543, 200]
```

**Comment by squaregoldfish** [comment]
Ah, that makes more sense. (Still getting the hang of projecting between co-ordinates and pixels!) I can make a bit of logic that works out how many times I've been round the world to offset the pixels.
