### ISSUE TITLE
'Draw and Modify Features' example got a bug after v3.18.2

### ISSUE THREAD

**Issue by hajjimurad** [openlayers/openlayers#6709]
If you draw LineString in the following Example
http://openlayers.org/en/latest/examples/draw-and-modify-features.html,
where ending point is very close to the starting point, you'll end up with the following
![image](https://cloud.githubusercontent.com/assets/11183111/25013452/e06b2b3e-2073-11e7-80c4-21ee5c287de4.png)
I.e. drawing doesn't stop, when you release mouse button.

The bug appeared in version **v3.19.0**, but in **v3.18.2** the behavior was correct.

**Comment by tschaub** [comment]
Without bringing in the modify interaction, a difference in behavior can be seen in these two examples:

 * http://openlayers.org/en/v3.18.2/examples/draw-features.html
 * http://openlayers.org/en/v3.19.0/examples/draw-features.html

When you draw a line in freehand mode in 3.18.2 drawing did not stop in this sequence: shift, down, drag, up (not near the first point).  I think this could be described as a bug.

When you do the same in 3.19.0, drawing does stop in this sequence: shift, down, drag, up (not near the first point).  This could be described as a bug fix.

In 3.18.2, if the up occurs close to the down, drawing finishes.  This could be called an accidental feature.  In 3.19.2, if the up occurs close to the down, drawing *doesn't* finish.  I'd call this a bug.

So, there are probably different interpretations of what is correct and what is a bug.  But I think that the least unexpected behavior would be to have drawing finish on up when you are in freehand mode - regardless of whether or not you are close to the first point.

You can see that freehand polygon drawing is also inconsistent in 3.19.0.  Drawing finishes on up (expected) *except* if the up is near the down (unexpected).

**Comment by hajjimurad** [comment]
Thanks for detailed explanation. I've just checked the latest version 4.1.0 and it looks that there is no such bug anymore (while it existed in 4.0.1). Was it fixed by purpose or it's a side effect?

**Comment by fredj** [comment]
See also #6501
