### ISSUE TITLE
Custom build error

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#6712]
[custom build](https://github.com/openlayers/openlayers/tree/master/tasks) makes a lot of "ERR! compile... - Bad type annotation. Unknown type ..."

![image](https://cloud.githubusercontent.com/assets/7428017/25036021/28849762-212c-11e7-8d90-94946ead4143.png)
 
build.json looks like below:
```javascript
{
"export": [
    "ol.color.asArray",
    "ol.color.asString",
    ... methods what I need
],
"compile": {
    "externs": [
      "externs/oli.js",
      "externs/olx.js"
    ],
    "define": [
      "ol.ENABLE_WEBGL=false",
      "ol.ENABLE_PROJ4JS=false",
      "ol.DEBUG=false"
    ],
    "compilation_level": "ADVANCED",
    "output_wrapper": "(function(){%output%})();",
    "use_types_for_optimization": true,
    "manage_closure_dependencies": true,
    "rewrite_polyfills": false
  }
}
```

#6698 doesn't fix this issue because the way of custom build is already having 'typedef.js'

**Comment by tschaub** [comment]
Can you try with manage_closure_dependencies: false?

**Comment by cs09g** [comment]
@tschaub Error happens the same.

**Comment by polar** [comment]
I have a similar issue, not so much for a custom build, but to use the externs to build an app where I want to just use `ol.js`.  The file generated by `tasks/generate-extern.js` does not generate a file that can be compiled. It seems that it needs `oli.js`, `olx.js`, and `typedefs.js`, and even then still it gets Bad Type Annotation Errors.  I'm going about this all wrong, why shouldn't this task just generate the  exported symbols used in ol.js and all the typedefs?

**Comment by tschaub** [comment]
With `v4.1.0` and the following `config.json`, running `node tasks/build.js config.json ol.min.js` works for me.

```json
{
  "exports": [
    "ol.Map",
    "ol.View",
    "ol.control.defaults",
    "ol.layer.Tile",
    "ol.source.OSM"
  ],
  "compile": {
    "externs": [
      "externs/bingmaps.js",
      "externs/cartodb.js",
      "externs/closure-compiler.js",
      "externs/esrijson.js",
      "externs/geojson.js",
      "externs/oli.js",
      "externs/olx.js",
      "externs/proj4js.js",
      "externs/tilejson.js",
      "externs/topojson.js"
    ],
    "extra_annotation_name": [
      "api", "observable"
    ],
    "compilation_level": "ADVANCED",
    "manage_closure_dependencies": true,
    "rewrite_polyfills": false
  }
}
```

@cs09g or @polar - can you provide a complete example that demonstrates the problem you are seeing?

I'll keep experimenting with different exports.

**Comment by tschaub** [comment]
@cs09g - with your partial example above, it looks like you are missing (at least) the `externs/tilejson.js`.  This is consistent with the error you are seeing.

**Comment by cs09g** [comment]
@tschaub [this json](https://jsfiddle.net/yL1nm78v/) is what I tried so far. including `externs/tilejson.js` didn't make a difference yet.

**Comment by afogelberg** [comment]
I'm experiencing similar problems with my custom in build OL 4.1.0. I have to add a complete list of externs to avoid errors even though the sources are not exported. For example excluding "externs/cartodb.js" will throw 
```
ERR! compile ../node_modules/openlayers/src/ol/source/cartodb.js:133:
WARNING - Bad type annotation. Unknown type CartoDBLayerInfo
```
My custom build looks like this:
```
{
  "exports": [
    "ol.Map",
    ...
  ],
  "umd": true,
  "compile": {
    "externs": [
      "externs/closure-compiler.js",
      "externs/geojson.js",
      "externs/esrijson.js",
      "externs/oli.js",
      "externs/olx.js",
      "externs/proj4js.js",
      "externs/tilejson.js",
      "externs/topojson.js"
    ],
    "define": [
      "ol.ENABLE_WEBGL=false",
      "ol.ENABLE_PROJ4JS=true",
      "ol.ENABLE_RASTER_REPROJECTION=false"
    ],
    "extra_annotation_name": [
      "api", "observable"
    ],
    "compilation_level": "ADVANCED",
    "manage_closure_dependencies": true
  }
```

**Comment by cs09g** [comment]
hint from @afogelberg 
I added all the js inside externs, then it's resolved. I'm not sure this is the right way to do but the build file size is almost same so it's not a big deal to add unused file.

the one thing it says as ERR! compile is
WARNING - unknown @define variable ol.DEBUG with below code.
maybe it's deprecated or something.

```javascript
"define": [
  "ol.DEBUG=false"
]
```

**Comment by darkscript** [comment]
I am having issues too,  am trying to compile my custom classes exclusively,  so that my min version will only contain codes from several of my files and not contain ol codes. am using the json below as input:
`{
  "exports": ["*"],
  "umd": false,
  "src": [
    "src/ros/*.js"
  ],
  "compile": {
    "externs": [
      "node_modules/openlayers/externs/ol-externs.js",
      "node_modules/openlayers/externs/oli.js",
      "node_modules/openlayers/externs/olx.js",
      "node_modules/openlayers/externs/cartodb.js",
      "node_modules/openlayers/externs/proj4js.js",
      "node_modules/openlayers/externs/tilejson.js",
      "node_modules/openlayers/externs/topojson.js",
      "node_modules/openlayers/externs/esrijson.js",
      "node_modules/openlayers/externs/geojson.js",
      "node_modules/openlayers/externs/bingmaps.js",
      "node_modules/openlayers/externs/closure-compiler.js"
    ],
    "define": [
      "goog.DEBUG=false"
    ],
    "js": [
    ],
    "jscomp_error": [
      "*"
    ],
    "jscomp_off": [
      "lintChecks",
      "analyzerChecks"
    ],
    "extra_annotation_name": [
      "api", "observable"
    ],
    "compilation_level": "ADVANCED",
    "warning_level": "VERBOSE",
    "generate_exports": false,
    "output_wrapper": "(function(){%output%}).call(window);",
    "use_types_for_optimization": true
  }
}`
I generated ol-externs. js and placed it on externs folder. I keep getting "unsatisfied dependency 'ol. Map'". If I include ol.debug.js in src section I end up with a combination of ol +my custom classes. I just need my custom classes alone compiled. Any ideas?

**Comment by cs09g** [comment]
@darkscript so, your code is ol-externs.js? I recommend you to keep separate OL and your code until it's done to use. then, you can simply merge and minifying both files. don't mix it up when you build OL itself.

**Comment by darkscript** [comment]
The custom classes to be compressed are inside ros folder in [https://github.com/darkscript/custom-build-for-my-openlayers-api-using-closure/tree/master/src/ros](github link), I just need to minimize the files to one single min js. If I include link to ol files in src folder, then I end up with combined ol + my files. If I exclude ol files in src, then there this this error below of which I thought it would be solved by using ol-extern.js
`ERR! Unsatisfied dependency "ol.Map" in script: C:\Users\Sam\Documents\sam\ros_compiled\src\ros\main.js`

**Comment by fredj** [comment]
closure-compiler is not used anymore, closing.
