### ISSUE TITLE
ol.style.text.getfont() has a  format  problem

### ISSUE THREAD

**Issue by xiaoq07** [openlayers/openlayers#6713]
when i use a text i do this: 
var text =new ol.style.text({
   font:'normal normal 20px sans-serif'
});
then  
 text.getFont();// 'normal normal 20 sans-serif';
tet.setFont('normal normal 20px sans-serif');
now  
 text.getFont();//'normal normal 20px sans-serif'

fontsize has unit  'px'.

**Comment by ahocevar** [comment]
OpenLayers does not change the text in any way when setting or getting it. Can you provide a live example that shows the issue?

**Comment by xiaoq07** [comment]
sorry.it‘s my mistake. i get the wrong number.
thanks for you help
