### ISSUE TITLE
Function finishDrawing does not check if the minPoints condition is fullfiled.

### ISSUE THREAD

**Issue by rmichaelis** [openlayers/openlayers#6714]
Thus using finishDrawing function could return invalid geometries. Such as a line with only one point.
https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/draw.js#L640

**Comment by tschaub** [comment]
Can you provide an example or describe steps to reproduce the issue you are seeing?  Are you calling `finishDrawing()` yourself?

**Comment by rmichaelis** [comment]
I just want to stop drawing by pressing a key.
Then when the key is pressed, I call by myself the finishDrawing function.
If I'm drawing a line, and if only the first point is clicked, then calling finishDrawing  will finish the drawing (as expected) but with an invalid geometry. (a line with only 1 point)
