### ISSUE TITLE
Improve Clustering performance by clustering the only the visible extent (with a buffer)

### ISSUE THREAD

**Issue by cmortazavi** [openlayers/openlayers#6717]
This would help with the performance issue when zooming into a clustered map.  If you zoom into a clustered map with a large amount of features then performance seriously suffers and sometimes the map might even crash.

**Comment by ahocevar** [comment]
Pull request accepted.

**Comment by crisley2016** [comment]
Some applications I write rely on the fact that ol.source.Cluster clusters *all* features, even if they are not displayed within the visible extent.  With this change, is there the ability to enable the old functionality?
