### ISSUE TITLE
Allow text selection in overlays

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#6720]
from https://github.com/openlayers/openlayers/issues/6618#issuecomment-294102180:

It is impossible to select text in overlay-based popups after this change. Compare: [4.0.1](http://openlayers.org/en/v4.0.1/examples/popup.html) and [4.1.0](http://openlayers.org/en/latest/examples/popup.html). What about adding `user-select` option to `.ol-overlay-container`?

**Comment by drnextgis** [comment]
PR https://github.com/openlayers/openlayers/pull/6729
