### ISSUE TITLE
IndexSizeError in IE11 with SVG,PNG on VerctorLayer

### ISSUE THREAD

**Issue by waegen** [openlayers/openlayers#6726]
I'm currently using a combination of SVG and PNG icons in my Map. 

I need to use the PNGs as IE11 is not able to colorize the SVGs correctly. But  i get an IndexSizeError when the images are to be drawn or redrawn.

I have prepared a [plunkr](http://plnkr.co/edit/hn2EQ3mrnkmFX75yYD8f?p=preview) that shows the error when one clicks on the Icons in IE11. When the getFeaturesUnderPixel() initiates replayHitDetection() and the redraw is called we get the error.
In my example I have linked Version 3.16.0 (which i'm currently using) but the error also occurrs in master branch.

This issue does not occurr in Chrome or Firefox browsers.

**Comment by ahocevar** [comment]
See https://github.com/openlayers/openlayers/issues/6281#issuecomment-268962325, closing as duplicate.
