### ISSUE TITLE
Needs exception handling

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#6733]
When the Icon size is null so [getAnchor](https://github.com/openlayers/openlayers/blob/f0457bf075fadc11f07e6206b4a68d6ef161e8c9/src/ol/style/icon.js#L232) returns null and when it tries to use its value from array 
[imageAnchor](https://github.com/openlayers/openlayers/blob/master/src/ol/render/canvas/immediate.js#L869), it occurs error. 
`Uncaught TypeError: Cannot read property '0' of null`

What about to add some condition to avoid the exception like,
```javascript
var imageAnchor = imageStyle.getAnchor();
...
var imageSize = imageStyle.getSize();
this.imageAnchorX_ = imageAnchor && imageAnchor[0];
this.imageAnchorY_ = imageAnchor && imageAnchor[1];
this.imageHeight_ = imageSize && imageSize[1];
...
this.imageWidth_ = imageSize && imageSize[0];
```

**Comment by ahocevar** [comment]
How are you running into this? Because of a misconfiguration? Can you share your code?

**Comment by cs09g** [comment]
It appeared when I work with [animated cluster](https://github.com/Viglino/OL3-AnimatedCluster). So, I'm not sure exactly which made this happen. I'll let you know once I figured it out.

**Comment by cs09g** [comment]
When Icon feature is created and try to set style before it's added to map, it happens. the size value is null unless it's not exist on a map.

**Comment by cs09g** [comment]
preload image solved it.
