### ISSUE TITLE
ol.map.skipFeature & ol.map.unskipFeature as public method in API

### ISSUE THREAD

**Issue by tohu12** [openlayers/openlayers#6735]
This two method is not accesable in OL API, but it usefulThis two method is not accessible in API, but i think that they will be useful as public method for next use.
It's possible, make this methods accessible in ol.map ?

**Comment by ahocevar** [comment]
These methods will not become part of the official API, because they are an internal implementation detail. If you want to skip features, style them with a style function that returns null instead of a style.
