### ISSUE TITLE
Adjacent VectorTile covers styled feature, which disappears on TileGrid boundary. 

### ISSUE THREAD

**Issue by shaula** [openlayers/openlayers#6736]
I based this bug report upon this example: http://openlayers.org/en/latest/examples/geojson-vt.html?q=vector+layer

I got a VectorTile layer that loads only tiles from layer 14 and shows its data also in higher and lower zoom levels.

While the features (styled as black rectangles) are fully visible when zooming in:
![features-fuly-visibile](https://cloud.githubusercontent.com/assets/1000979/25312501/3a61c838-281b-11e7-8c09-eb41cf3744b7.png)

I got some strange effects at the tile boundaries, where its partly hidden:
![feature-partly-hidden](https://cloud.githubusercontent.com/assets/1000979/25312498/37f01154-281b-11e7-905e-cc9aa01a1d71.png)

The code is at: https://jsfiddle.net/1tmy30ef/2/

Am I doing something wrong?

**Comment by ahocevar** [comment]
Your features are points, and the adjacent tile does not know about the neighbouring tile. You are also using a big symbol, which may go beyond tile borders. For this reason, vector tile sources repeat point features on neigbouring tiles when they are expected to be rendered with big symbols.

That said, there is nothing wrong on the OpenLayers and application side, but the vector tiles are generated in a wrong way.
