### ISSUE TITLE
Overlay autoPan not working if position is set before map.addOverlay

### ISSUE THREAD

**Issue by NisStrom** [openlayers/openlayers#6739]
The example from the API for ol.overlay is incorrect:
```
var popup = new ol.Overlay({
  element: document.getElementById('popup')
});
popup.setPosition(coordinate);
map.addOverlay(popup);
```

If the position ist set in the config passed in ol.Overlay call or setPostion is called before map.addOverlay the autopanning does not work because it needs a reference to map wich is set to late in map.addOverlay.

If the setPosition call is placed after map.addOverlay it works but it gives the ugly effect that the element is first position in the top-left corner of the map area before it is placed the correct position. 
Another thing is that the position property in Overlay options does not really work with autopanning.

**Comment by gisdream** [comment]
the position property in Overlay options does not really work with autopanning.
i meet too

**Comment by TheNaderio** [comment]
Same here.

The popup opens but there is absolute no panning :(
