### ISSUE TITLE
How to judge the end of the map load?

### ISSUE THREAD

**Issue by kmiracle** [openlayers/openlayers#6742]
How to judge the end of the map load?
How to judge a vector layer load end?
The postcompose event is not triggered by a vector layer load

**Comment by ahocevar** [comment]
To know when a map is loaded, you have to monitor loading progress of all of its sources. For vector sources that are configured with a `url`, a `'change'` event will be triggered when it is loaded. I have created a CodePen which prints 'loaded' to the console when loading has finished: https://codepen.io/anon/pen/JNRWBB?editors=0010#. If you need to know when the map is loaded to e.g. create a screenshot, call `map.renderSync()` when loaded, before taking the screenshot.
