### ISSUE TITLE
Labels of circular geometries are positioned in the center instead of within geometry

### ISSUE THREAD

**Issue by naemar** [openlayers/openlayers#6743]
Labels of circular geometries are positioned in the center of the geometry. But due to readability and logic, in my point of view it should be placed within the actual geometry.

So in this example the yellow and light green label are placed in the center as well, making the dark green label unreadable:

![unbenannt](https://cloud.githubusercontent.com/assets/9743519/25333778/0104f98a-28ec-11e7-8d08-d083a22ca1f7.PNG)

**Comment by ahocevar** [comment]
You can define your own label position in a style function. Instead of configuring an `ol.style.Text` in the style you use to symbolize the polygon, create a separate `ol.style.Style` with an `ol.style.Text` and a point `geometry` that represents your desired label point.
