### ISSUE TITLE
setMinZoom, setMaxZoom doesn't work when view has resolution property

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#6746]
If you give resolutions property when you create view for map, setMinZoom and setMaxZoom doesn't work. 

example's [here](https://codepen.io/anon/pen/ybaWXv?editors=0011)

**Comment by cs09g** [comment]
What about to have setMinResolution/setMaxResolution or setResolutions likewise getResolutions

**Comment by cs09g** [comment]
any comment please?

**Comment by ahocevar** [comment]
If your goal is to fix `setMinZoom()` and `setMaxZoom()` for the case where the view was constructed with `resolutions`, then please submit a pull request.

**Comment by cs09g** [comment]
Right, setting minimum/maximum zoom is the goal. not restriction of resolutions. I'll have a look. Thanks.

**Comment by cs09g** [comment]
fixed with #7521
