### ISSUE TITLE
Toggle ol.Feature visibility

### ISSUE THREAD

**Issue by 10lojzo** [openlayers/openlayers#6749]
Now, if I want to make feature invisible, I have three options:

1. Remove the feature from ol.Collection(or plain array and redraw)
2. Set the style to null or undefined or empty style
3. Add each feature to new layer and set the visibility on layer itself

The first solution works, but requires additional code to store the invisible features in another array, which leads to another messy code if I'm working with all features regardless of their visibility in other parts of the code(I have to iterate or join both arrays etc.).

The second solution works only partially. The features are really invisible optically, but they are active, they are triggering events, for example modify interaction is active on them etc.

The third solution is absolutely inappropriate I think.

**Comment by ahocevar** [comment]
Option 2 is preferable. Just make sure that interactions with their own style (like e.g. `ol.interaction.Modify` have a style that also respects your visibility setting on features. This can most easily be accomplished by setting `feature.setStyle(function() {}));`.

**Comment by 10lojzo** [comment]
For `ol.interaction.Modify` I use custom style function. But passed feature parameter of the style function is not the original feature but only temporary interaction feature which does not contain my custom data. Probably I can solve this by setting the temporary variable in modifystart evenhandler, which is a little bit cumbersome. Anyway, the modify interaction is still active on the feature regardless of the style. Moreover, with default modify interaction options property `pixelTolerance` the feature becomes even more vulnerable for unintended modifications by user. I must be absolutely sure these features are not changed when invisible.

**Comment by ahocevar** [comment]
You can configure your Modify interaction with a collection of `features`. Add only the features you want to be modified to that collection.

**Comment by 10lojzo** [comment]
I end up with option 1, separating the visible and invisible features to different collections. I think that the UI should be separated from the logic anyway. Maybe it would break the ol code structure, but I think it is a basic functionality to be able to show/hide the objects on the map per feature, as it was in openlayers 2, or as it is possible in other map libraries.

**Comment by Jerry-goodboy** [comment]
I got the same problem, but I find the best answer to solve this problem, I am using the V5.3.0 API, so here is my solution:

* First, you have to set the layer's style option to null, all layers are best to set null;
* Second, you can use the setStyle function of the feature to control the show/hide of the feature, if it set null, the feature will not be rendered in the layer, otherwise, the feature will be rendered in the layer with its own style which you set.

Honestly speaking, I never thought of ol API will handle the problem like this, the logic confuses me a lot, I hope it will be optimized in the future.
