### ISSUE TITLE
Support for ESRI Vector basemap

### ISSUE THREAD

**Issue by shaunakv1** [openlayers/openlayers#6752]
Is it a possibility to add support for [ESRI's vector basemaps](http://www.arcgis.com/home/group.html?id=30de8da907d240a0bccd5ad3ff25ef4a&focus=maps)? I am trying to get an [example](https://codepen.io/anon/pen/PmpPxK) together., and have started a [stackoverflow question](http://stackoverflow.com/questions/43671343/how-to-display-esri-vector-base-map-in-openlayers-3), which describes the issue in much details and has a partially working example. 
Essentially I am stuck on being able to use ESRI styles. 

[Esri's leaflet port](https://github.com/Esri/esri-leaflet-vector) is able to do this in this example. And some information on esri style IDs is available [here](https://github.com/Esri/esri-leaflet-vector/blob/master/src/Basemap.js). 

Here's the code I have so far: 

```
var map = new ol.Map({
  layers: [
    new ol.layer.VectorTile({
      source: new ol.source.VectorTile({
        format: new ol.format.MVT(),
        
        tileGrid: ol.tilegrid.createXYZ({maxZoom: 22}),
        tilePixelRatio: 16,
        url: 'https://basemaps.arcgis.com/v1/arcgis/rest/services/World_Basemap/VectorTileServer/tile/{z}/{y}/{x}.pbf'
      })
    })
  ],
  target: 'map',
  view: new ol.View({
    center: [0, 0],
    zoom: 2
  })
});
```
Which renders the tiles without any styles for the vector tiles: 

![image](https://cloud.githubusercontent.com/assets/732604/25513123/d8981ae2-2ba0-11e7-9e78-bbf6e6783a58.png)

With some guidance, on how to get a working example, I am willing to attempt contribute this feature.

**Comment by ahocevar** [comment]
ESRI uses Mapbox Style objects for styling. In the [Leaflet example](https://esri.github.io/esri-leaflet/examples/vector-basemap.html) you'll see that a `resources/styles/root.json` file is loaded. That is the style file, and you can use the [ol-mapbox-style](https://npmjs.com/package/ol-mapbox-style) package create a fully styled OpenLayers map from the information contained in that style file. If you want to apply the style manually, use the [mapbox-to-ol-style](https://npmjs.com/package/mapbox-to-ol-style) package instead.

**Comment by hoogw** [comment]
perfect, but with one question. 
    
           esri's root.json,   sprite and glyphs are not full URL, the are only last part as see below 

In your example, those not full URL works,  but, I have test it in mapbox js api, it failed, error is can't parse URL,

I have to change those url to a full URL, to make it works.


                                       root_json = {

                                                          "version" : 8,
                                                          "name": "test",

                                                          //"sprite" : original_rootJson.sprite,    // original is not a full URL, not work  "../sprites/sprite"   
                                                          // "sprite" : "https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/2020_USA_Median_Age/VectorTileServer/resources/sprites/sprite",
                                                          "sprite" : _sprite,

                                                          

                                                          // "glyphs" : original_rootJson.glyphs,      // original is not a full URL, not work  "../fonts/{fontstack}/{range}.pbf" 
                                                          // "glyphs" : "https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/2020_USA_Median_Age/VectorTileServer/resources/fonts/{fontstack}/{range}.pbf",
                                                          "glyphs" : _glyphs,

                                                        

                                                          // root json  specification :   https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/
                                                          "sources" : {

                                                                                    "esri" : {
                                                                                                "type" : "vector",

                                                                                                //  By supplying TileJSON properties such as "tiles", "minzoom", and "maxzoom" directly in the source:
                                                                                                "tiles": [
                                                                                                              // "https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/2020_USA_Median_Age/VectorTileServer/tile/{z}/{y}/{x}.pbf"
                                                                                                                _tile_pbf
                                                                                                          ],

                                                                                                // "maxzoom": 14
                                                                                                // By providing a "url" to a TileJSON resource
                                                                                                // not work,yet
                                                                                                //  "url" : "https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/Esri_Childrens_Map/VectorTileServer/tile/{z}/{y}/{x}.pbf"
                                                                                                //  "url": "http://api.example.com/tilejson.json"

                                                                                            }
                                                                      },

                                                          "layers":  original_rootJson.layers     


                                          } // root_json

**Comment by ahocevar** [comment]
A lot has happened since this issue was closes. With the latest version of [ol-mapbox-style](https://npmjs.com/package/ol-mapbox-style), it is now easy to create a map from a Mapbox style document. And it also works for Esri style documents with relative urls. Example with the above style resource: https://codesandbox.io/s/infallible-tdd-h39j9?file=/src/index.js

This is all that's needed:
```js
import createMap from "ol-mapbox-style";

createMap(
  "map",
  "https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/2020_USA_Median_Age/VectorTileServer/resources/styles/root.json"
);

**Comment by hoogw** [comment]
@ahocevar   very cool, I create another test,  found a possible bug, 

Can you take a look if that bug can be fixed?

The feature ID is always undefined, which should be a real id, should not be undefined.

                                  
                                            // bug, need fix, feature ID is always undefined
                                            var featureId = features[0].getId();


 [https://codesandbox.io/s/young-water-uquvh](https://codesandbox.io/s/young-water-uquvh)


You can also check the console.log 
            
                                           console.log('feature featureId', featureId, features)


all the features, all id is undefined,

**Comment by hoogw** [comment]
I mean the feature Id should be   ZIP Code/45 - 53 years of age, instead of undefined

I create the [code sandbox link](https://codesandbox.io/s/young-water-uquvh?file=/src/index.js:1013-1145), 
I try to get feature id, but it always undefined.
Should be a bug with easy fix, but I don't know how, it should be inside openlayers api

this is root.json  
from   https://tiles.arcgis.com/tiles/P3ePLMYs2RVChkJx/arcgis/rest/services/2020_USA_Median_Age/VectorTileServer/resources/styles/root.json

                                         {
            "id": "ZIP Code/45 - 53 years of age",
            "type": "fill",
            "source": "esri",
            "source-layer": "ZIP Code",
            "filter": [
                "==",
                "_symbol",
                5
            ],
            "minzoom": 7.21,
            "maxzoom": 9.95,
            "layout": {},
            "paint": {
                "fill-color": "#FAB679",
                "fill-outline-color": "#D6D6D6"
            }
        },
        {
            "id": "ZIP Code/53 - 86 years of age",
            "type": "fill",
            "source": "esri",
            "source-layer": "ZIP Code",
            "filter": [
                "==",
                "_symbol",
                6
            ],
            "minzoom": 7.21,
            "maxzoom": 9.95,
            "layout": {},
            "paint": {
                "fill-color": "#FFDABF",
                "fill-outline-color": "#D6D6D6"
            }
        },

**Comment by ahocevar** [comment]
What you're looking at is the layer id, not the feature id. So instead of `feature.getId()`, you'll want to ask for `feature.get('layer')`.

**Comment by hoogw** [comment]
I test it  
                        feature.get('layer').

   I did get layer name, but not get layer id,  above example, layer name is  only "ZIP Code", which is from  "source-layer": "ZIP Code",

   I want the layer-id,   should be same as  "id": "ZIP Code/45 - 53 years of age",

     zip code layer have many age group, root.json define which age group use which symbol by 
  
          "filter": [
            "==",
            "_symbol",
            5
        ],




I could loop through root.json, find that age group by layer name and symbol value, extra coding, not good, may fail, if filter format changed. 

How can I get layer ID "ZIP Code/45 - 53 years of age",   not the layer name "ZIP Code"

**Comment by hoogw** [comment]
How to get layer id instead of get layer name?

                    feature.get('layer').

This only get layer name,  it is "ZIP Code",  I try to get layer id, should be "ZIP Code/45 - 53 years of age",  but don't know how.  

The layer id defined in root.json file

**Comment by hoogw** [comment]
I compare with mapbox, this is a feature object in mapbox (vector tile)

                            layer: {id: "County:1/45 - 53 years of age", type: "fill", source: "esri", source-layer: "County:1", minzoom: 3.96, …}
                           properties: {_symbol: 5}
                           source: "esri"
                           sourceLayer: "County:1"
                          state: {}
                          type: "Feature"
                         _vectorTileFeature: Co {properties: {…}, extent: 4096, type: 3, _pbf: Js, _geometry: 7785, …}  



This is openlayes ,  feature object (vector tile) 
                                 
                            0: RenderFeature
                                         ends_: [14]
                                         extent_: (4) [....]
                                          flatCoordinates_: (14) [...]
                                          flatInteriorPoints_: null
                                          flatMidpoints_: null
                                          id_: undefined
                                          ol_uid: "169"
                                          properties_: {_symbol: 4, layer: "County:2"}        
                                          type_: "Polygon"
                                          __proto__: Object


You can see, that openlayers put 'layer' inside 'properties_' and only collect source-layer name. 
Mapbox, do it differently,   mapbox collect detailed info for 'layer', and you can read the layer's id, fill, color etc...

Openlayers might need improvement by include detailed info into a separated properties named 'layer'  from  feature
  Those  'layer' properties, should include all detailed info such as layer id, fill, color etc....(those info can get from root.json layer definition)

**Comment by hoogw** [comment]
@ahocevar   

I use work around method to get it works on my local only, when upload[ to codesandbox](https://codesandbox.io/s/young-water-uquvh?file=/src/index.js), some how not showing map, 

not sure why, it was working yesterday without work around.

**Comment by ahocevar** [comment]
This is not something that can be changed in OpenLayers. It has to be fixed in ol-mapbox-style. Please create a feature request issue in https://github.com/openlayers/ol-mapbox-style/.

**Comment by hoogw** [comment]
a new[ feature request](https://github.com/openlayers/ol-mapbox-style/issues/311#issue-766806653) created

**Comment by hoogw** [comment]
@ahocevar   
Can you add layer similar as mapbox? this is [mapbox's layer definition](https://docs.mapbox.com/mapbox-gl-js/api/map/#queryrenderedfeatures-returns):

                         Each feature includes top-level layer, source, and sourceLayer properties. The layer property is an object representing the style layer to which the feature belongs. Layout and paint properties in this object contain values which are fully evaluated for the given zoom level and feature.

**Comment by hoogw** [comment]
with 6.3.0, it works

[codesandbox sample](https://codesandbox.io/s/gallant-goldstine-dd40f?file=/src/index.js)

**Comment by hoogw** [comment]
codesandbox,  working sample:


 [ arcgis Vector tile, hover, highlight](https://codesandbox.io/s/sweet-river-mdjhb?file=/index.html)

It has problem, not stable, sometime strange thing happen, special for circle feature, not correct, not properly works


[Without hover hightlight](https://codesandbox.io/s/youthful-poincare-weo2l?file=/src/index.js), seems works fine,
