### ISSUE TITLE
Reload Layer

### ISSUE THREAD

**Issue by Ballantines42** [openlayers/openlayers#6754]
Hello,

I want to reload my LayerGroup, my group consists of a WMS source and a WFS source.

For reload, I use 👍 
    Layers.lay_evt_picto.getLayers().a[1].getSource().clear(); //WFS
    Layers.lay_evt_picto.getLayers().a[0].getSource().updateParams({ "time": Date.now() }); //WMS
    map.updateSize();

But a layer blink, Is there a way to recharge the layers without flashing ?

**Comment by ahocevar** [comment]
First of all, do not use internal properties (`a`). For WMS layers, there should be no blinking in the latest version of OpenLayers. For WFS, you could switch to a new source when it is loaded (`layer.setSource()`), instead of calling `clear()` on the existing source.
