### ISSUE TITLE
how to subclass DragPan for custom touch management?

### ISSUE THREAD

**Issue by giohappy** [openlayers/openlayers#6758]
I need to control DragPan on mobile devices to disable dragging with only one finger. I guess you aready saw this feature in some mobile browser maps, where a message says "use both the fingers to drag".
I thought it was pretty easy but I stumbled against the protected ol.Pointer/ol.DragPan variables, which make it impossible to subclass it easily (without a custom OL3 build).

Protected/private fields make customization a pain, and I can't/don'want to use the ol-debug.js just for this. What's your suggestion?

**Comment by fredj** [comment]
Instead of subclassing DragPan, did you try to create a custom `condition`?

**Comment by fredj** [comment]
Or with something like:
```
var dragPan = new ol.interaction.DragPan();
map.addInteraction(dragPan);

var pointers = 0;
map.on('pointerdown', function() {
  pointers++;
  if (pointers === 2) {
    dragPan.setActive(false);
  }
});
map.on('pointerup', function() {
  pointers--;
  if (pointers === 1) {
    dragPan.setActive(true);
  }
});
```
https://codepen.io/anon/pen/ZKeaWo

**Comment by giohappy** [comment]
The last solution you suggest is what I'm already using, but I want to create a self-contained component, exactly what an interaction is meant to be.

I haven't tried with conditions, but it wouldn't be enough because I need to trigger a custom event to let others know that a specific kind of dragpan is going to happen. I could do it within the condition itself but it would be quite a bad design.
Anyway what should be the easier way, within a condition, to know if two pointers are being used?

**Comment by giohappy** [comment]
@fredj I can stop drag interaction but do you know how could I pass the (single pointer) drag event back to the browser to allow page scrolling?

**Comment by fredj** [comment]
`touch-action: none` set on the viewport prevent the page scrolling
