### ISSUE TITLE
view.getHints undefined in ol-debug.js

### ISSUE THREAD

**Issue by mblinsitu** [openlayers/openlayers#6762]
In my application I use `view.getHints()[ol.ViewHint.INTERACTING]` to figure out whether the view change events are due to local interaction.

When I use the CDN `ol.js` (version 4.1.0), `ol.ViewHint` and `view.getHints()` are undefined.
When I use the CDN `ol-debug.js`, all is fine.

Is this intended, or is it a bad side effect of the minimization of the `ol.js` library?

Thanks,
michel

**Comment by ahocevar** [comment]
It's intended, because the `getHints()` method is not part of the official API.

**Comment by mblinsitu** [comment]
Is there an official way then to find out if an interaction or an animation is ongoing?
I need this to ignore requests coming from a server while the user is interacting with the map.
I would rather not have to redefine the interactions to do exactly what `getHints()` is doing...

Cheers,
michel

**Comment by ahocevar** [comment]
Yes, there is. [`ol.View#getAnimating()`](http://openlayers.org/en/latest/apidoc/ol.View.html#getAnimating)

**Comment by mblinsitu** [comment]
Indeed, but there is no `ol.View#getInteracting()` :-(

**Comment by ahocevar** [comment]
We'd accept a pull request to add `ol.View#getInteracting()`.

**Comment by mblinsitu** [comment]
The pull request is here: https://github.com/openlayers/openlayers/pull/6764
