### ISSUE TITLE
how to preserve page scrolling (instead of panning) on mobile device?

### ISSUE THREAD

**Issue by giohappy** [openlayers/openlayers#6767]
I need to let user scroll page on mobile devices instead of panning the map. I've tried various approaches but nothing stops the map (canvas element) from grapping the event and stopping the native event handling (scrolling).

**Comment by ahocevar** [comment]
Just configure your map without an `ol.interaction.MouseWheelZoom`.

**Comment by giohappy** [comment]
@ahocevar I'm talking about mobile devices, it' about pointer (touch) events.
The desired behaviour is: 

- user clicks are managed by ol3, to fire my own methods on foreachFeatureAtPixel
- pinch zoom and drag zoom with two pointers should be managed by ol3
- pan (one pointer) should be ignored by ol3 to let the user scroll the page

It's a mixed behaviour that can be managed from outside ol3 but I'm not able to make ol3 ignore the third case.

**Comment by ahocevar** [comment]
In this case you'd have to configure your map without an `ol.interaction.DragPan`.

**Comment by giohappy** [comment]
I already tried it but the page doesn't scroll. Probably the event handling mechanism grabs the event at a deeper level.

**Comment by giohappy** [comment]
@ahocevar why did you close this issue? I have tried disabling every interaction and control, but still the various handlers grab the event and prevent page scrolling, so it isn't solved...

Just as an example in Leaflet It can done simply disabling the drag (https://jsfiddle.net/geg8yLe3/6/), and it was my first try with OL too.

A typical usage is an embedded map like in Booking.com. If you pan on the map a message appears saying to use two fingers to pan the map.

**Comment by giohappy** [comment]
I got it: canvas doesn't touch scrolls on mobile. I've implemented my own "touchmove" handler to scroll from code.

**Comment by ahocevar** [comment]
@giohappy I reopened the ticket. Please provide a live example that shows the issue, or close if you feel the issue is resolved.

**Comment by giohappy** [comment]
The issue is with canvas on mobile devices, where the browser doesn't scroll with touchmove on the canvas.
A minimal fix can be to force scroll through a touchmove handler:

  ```
var pageScroll = 0,
pageScrollOffset = 0,
lastTouchY = 0,
mapScrolling= false;
window.startTouchScroll = function() {
$('#map').bind('touchmove', function(e) {
  mapScrolling= true;
  e.preventDefault();
  var touch = e.originalEvent.touches[0] || e.originalEvent.changedTouches[0];
  var elm = $(this).offset();
  var maxScroll = $(this).height();
  var x = touch.pageX - elm.left;
  var y = touch.clientY - elm.top;
  if (lastTouchY != 0) {
    pageScrollOffset = lastTouchY - y;
    if (pageScroll + pageScrollOffset > $(document).height() - $(window).height()) pageScrollOffset = 0;
    pageScroll += pageScrollOffset;
    if (pageScroll < 0) pageScroll = 0;
  }
  lastTouchY = y;
  if (x < $(this).width() && x > 0) {
    if (y < $(this).height() && y > 0) {
      $('html,body').scrollTop(pageScroll);
    }
  }
});
$('#map').bind('touchend', function(e) {
  e.preventDefault();
  lastTouchY = 0;
  mapScrolling= false;
});
};

$('body').bind('touchend', function(e) {
if (!mapScrolling) {
  pageScroll = $(this).scrollTop();
}
});

window..endTouchScroll = function(){
$('#map').unbind ('touchmove');
$('#map').unbind('touchend');
};
```

**Comment by cs09g** [comment]
what about to set meta tag `<meta name="viewport" content="user-scalable=no" />`

**Comment by data-ux** [comment]
I'm struggling with the same problem. I have a OL map without any interactions. Starting a touch scroll gesture on top of the map doesn't do anything.

I think the sensible expectation would be that a map without interactions acts like a static image.

**Comment by falinsin** [comment]
Any solution about this?
I ask for this in stackoverflow some days ago and still no answer  :-(

I´m very very pressed from my users for find a solution. I hope not to change all my program and be forced to use other library because the work is done a month ago.

A simple solution could do de work for me and save my day. Anybody know some work arround?

Sorry my English is not perfect, thank you in advance.

**Comment by fredj** [comment]
What about this: https://codepen.io/fredj/pen/vRzqQe/

This is a map without any interactions or controls (~ static image), starting a touch scroll gesture on top of the map works as expected.

The trick is to force a `touch-action: auto` to the viewport.

**Comment by falinsin** [comment]
Thanks fredj but if I do this users can't move the map. Map looks like an static image.
A solution like a button for activate or deactivate drag in mobile could do the work.
Other more elegant solution do Google Maps where only can drag pan the map with two fingers in touch devices.

But I can manage with a way of activate / deactivate drag map with a custom button. How can this be done?

**Comment by ahocevar** [comment]
See #7904 for an elegant solution.

**Comment by KenVanLee** [comment]
my solution, currently only tested on safari mobile

stopPropagation for all the children of the viewport for touchstart,touchmove and touchend:

`    Array.from(map.getViewport().children).forEach(function(element) {
        ['touchstart','touchmove','touchend'].forEach(function(type){
            element.addEventListener(type,function(e){               
                if(e.touches){
                    if(e.touches.length === 1){
                        e.stopPropagation();                    
                    };
                }    
            })
        })
    }, this);
`

replace the DragPan Interaction with a new DragPan that only react to 2 touches, based following link [https://stackoverflow.com/questions/42769202/openlayer-two-finger-movement-dragpan](url)

`    var dragPanIndex = map.getInteractions().getArray().findIndex(function(element){return element instanceof DragPan});
    map.getInteractions().removeAt(dragPanIndex);
    map.getInteractions().insertAt(dragPanIndex, new DragPan({
        condition: function(olBrowserEvent){
            if(olBrowserEvent.originalEvent.touches){
                return olBrowserEvent.originalEvent.touches.length === 2;
            }
            return true
        }
    }));
`

**Comment by ayacoub1** [comment]
hi , any update on this , i need to use two fingers to zoom and one finger should scroll only ?

**Comment by isthisstackoverflow** [comment]
I used a mix of (from fredj above)

```css
.ol-viewport {
  touch-action: auto !important;
}
```

and manually added the DragPan like so (idea from KenVanLee above)

```js
map.addInteraction(new DragPan({
    condition: e =>
      e.originalEvent.touches
        ? e.originalEvent.touches.length > 1
        : e.originalEvent.type === 'pointerdown'
}))
```

to achieve the effect that

* dragging must be done with 2 fingers, 1 finger scrolls on mobile
* desktop behaves 'just normal'

Maybe you can make some use of these snippets / adjust them to your needs.

**Comment by isthisstackoverflow** [comment]
@ayacoub1 I put together a [codepen](https://codepen.io/HansB1984/pen/OJLogga) for [my feature request](https://github.com/openlayers/openlayers/issues/9936) to show what I mean (and have a temporary solution).

Maybe you can make some use of it. It's mostly code thrown together from others in this and related threads.
