### ISSUE TITLE
Performance of ol.Collection clear method

### ISSUE THREAD

**Issue by 10lojzo** [openlayers/openlayers#6768]
I have `ol.source.Cluster` with `ol.source.Vector` as a source. The `ol.Collection` represents the `features` property of the vector source.

1.) If I do not create the new instance of ol.Collection after every time the `clear` method of `ol.Collection` is called, the `ol.Collection` gets very slow on next push method calls.
http://jsfiddle.net/mattti/bca9t92c/1/

2.) If the clear method of `ol.source.Vector` is not called before the clear method of the `ol.Collection` is called,  the `ol.Collection` clear method performs very slow.
http://jsfiddle.net/mattti/bca9t92c/2/

3.) The only solution i found is to create a new ol.Collection, which in turn requires me to create new instances of ol.source.Cluster and ol.source.Vector, as these objects **do not have** the observable setters `setSource` and `setFeatures` respectively(please consider adding these methods to the relevant objects).
http://jsfiddle.net/mattti/bca9t92c/

In fiddle open the browser console to see the timer outputs of clear and push methods of each scenario.

**Comment by ahocevar** [comment]
What you're describing is all expected. If you consider that calling `ol.Collection#clear()` triggers an event with the removal of every item, which will in turn change the underlying vector source of the cluster source, which will cause the cluster to be recalculated.

The preferred solution to replace the features of a vector source is
```js
source.clear();
source.addFeatures(newFeatures);
```
There is also no good reason in this scenario to use an `ol.Collection` for the vector source's features. It just adds unnecessary overhead.

**Comment by 10lojzo** [comment]
Still the problem 1.) persists and has nothing to do with the performance of clear method itself. It is strange that the ol.Collection gets slow **after** the clear method was called. It is **empty** and all the following push methods are significantly slower. Why?
