### ISSUE TITLE
Tapping on map on Android doesn't always work after a Chrome fix

### ISSUE THREAD

**Issue by mustaqahmed** [openlayers/openlayers#6776]
After we fixed [an old bug](https://crbug.com/632067) with PointerEvents in Chrome 58, an issue in OpenLayer's tap handling got exposed: a tap on Android doesn't always work.  More precisely, until Chrome 57 we used to (wrongly) suppress <code>pointermove</code> events in a small ("slop-suppression") region around the <code>pointerdown</code> point, which we fixed in Chrome 58.  After the fix, in OpenLayers tap doesn't work unless it's a very quick tap---the pointermoves within the old slop-region is perhaps triggering a pan followed by a "move end" event.

This is evident from the following examples:
- [box-selection.html](https://openlayers.org/en/latest/examples/box-selection.html)
- [moveend.html](https://openlayers.org/en/latest/examples/moveend.html)

I confirmed that it's not a Chrome bug through adding a hack <code>pointermove</code> listener through devtools that drops the move events close to the <code>pointerdown</code>.  I will close the [new Chrome bug](https://crbug.com/718540).

**Comment by fredj** [comment]
https://github.com/openlayers/openlayers/blob/v4.1.1/src/ol/mapbrowsereventhandler.js#L239-L262

**Comment by fredj** [comment]
In Chrome 58 on Nexus 5X, I've the following `pointerdown` / `pointermove` sequence (with the corresponding `clientX`, `clientY` value):
 - `pointerdown` 275.80999755859375 312.3810119628906
 - `pointermove` 275.80999755859375 311.16900634765625
 - `pointermove` 275.4289855957031 310.85699462890625

And because the position are [not exactly the same](https://github.com/openlayers/openlayers/blob/v4.1.1/src/ol/mapbrowsereventhandler.js#L278-L286) it prevents [click events](https://github.com/openlayers/openlayers/blob/v4.1.1/src/ol/mapbrowsereventhandler.js#L166-L168).

**Comment by ischas** [comment]
It would be great if there will be a patch release for this. Our mobile client is nearly unusable with Android and Chrome at the moment.

**Comment by boomdrak** [comment]
We have done some testing and may have found a link between different Android versions.

When we try to click many random positions on the map we get events fired from places where it should not be clickable and vice versa.

Regard this as possible additional information

So far we have tested will the following setup`s:

* iOS 10.3.1,  Chrome 58.0.3029.83 -> Click works in map
* Android 6 Huawei Honor 7, Chrome 58.0.3029.83 -> Click works in map
 **But**
* Android 7, Sony (don’t remember model), Chrome 58.0.3029.83 -> the click doesn’t work anymore.

**Comment by wouterij** [comment]
I can confirm that this weekend tapping on the map stopped working in Chrome 58.0.3029.83 on Android. As fredj mentions, every tap is registered as a move of one or two pixels. 

Doesn't work on
* Sony Z1 Compact, Android 5.1.1 with Chrome 58.0.3029.83
* Nexus 4, Android 5.1.1 with Chrome 58.0.3029.83

Does work on
* Sony Z1 Compact, Android 5.1.1 with Firefox 53.0.2
* Nexus 4, Android 5.1.1 with with Firefox 53.0.2
* iPhone SE, iOS 10.3.1 with Safari
* iPad 3rd Gen, iOS 9.3.5 with Safari

**Comment by netgis** [comment]
I can confirm the tapping bug for the new Samsung devices with Android 7.0.0:

Doesn't work as expected on

- Samsung Galaxy S7, Android 7.0.0 with Chrome 58.0.3029.83
- Samsung Galaxy S8, Android 7.0.0 with Chrome 58.0.3029.83

Does work as expected on

- Samsung Galaxy S5, Android 5.5.0 with Chrome 58.0.3029.83

I think it's the combination Android 7 with Chrome 58.0.3029.83

**Comment by ischas** [comment]
As mentioned before,

* Samsung S5 with Android 6.0.1 and Chrome 58 

doesn't work. So it's not exclusively Android 7.

**Comment by tomduffey** [comment]
what i have found with the tap on android to select features:
it returns the wrong evt.pixel - i confirmed this with the right click (hold tap long time) to see what  evt.pixel  it returns. i found that the right click(hold tap long) returns the right value on android mobile. Other testing has shown any click event gives the wrong evt.pixel value on mobile. This becomes obvious when i move the click to southwest direction 25 past the hour on a clock. When i click there it affects the item elsewhere on the map showing the pixel is wrong.

**Comment by tomduffey** [comment]
i will look for a way to test the click at the JavaScript level or with jquery to see if the problem is there - i would then assume it is an android and chrome problem. if it works there - i will look at the openlayers level to see what event information it is using

**Comment by huntw999** [comment]
I will do some testing on the javascript side and compare pixel returned on the click event

**Comment by geogprof** [comment]
I am having similar problems on Galaxy S7 with Chrome 64.0.3282.137 and Android 7.0. However, using Firefox with Android 7 on the same phone and everything works.

**Comment by Peter-Optiway** [comment]
For those still having issues try setting `moveTolerance` on when initializing the map
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html
