### ISSUE TITLE
pre-build npm package

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#6781]
Right now, the openlayers npm package (at version 4.1.1) installs 13000 files which take 116 MB in total, even when using `yarn`. The install process is also quite lengthy, with closure util compilation and so.

I don't understand why does openlayer choose this install-and-compile everything route, when the -dist.zip contains only 3 files totalling 3 MB in total. I believe that the contents of that -dist.zip should be the one published to npm (with package.json and so on).

In my understanding (and it seems to be the common way for most npm packages), npm is a distribution channel for compiled / distributable packages, not source code.

Even if looking only at map libraries, Leaflet has a pre-compiled, dependency less package, which even contains the full source code and the documentation. But the important bit is that the dist folder is present and doesn't need any dependency nor process to generate it, upon install. Custom build is still possible, as well as installing the dependencies, but for 99% of the users it'll never be actually run.

I strongly recommend going for a minimalistic, dist-folder based npm package in the future. Until that time, openlayers will be always hand downloaded and unzipped to my `non-npm` folders.

**Comment by tschaub** [comment]
If you are only interested in a full build of the library (not recommended for production), you don't need to install anything.  Instead, include this in your markup:
```html
<script src="https://openlayers.org/en/v4.1.1/build/ol.js"></script>
```

If you are using a module bundler like `webpack`, `browserify`, or `rollup`, then you should install the [`ol` package](https://www.npmjs.com/package/ol) - this lets you `require` or `import` just what you need for your application.

I agree with you that the `openlayers` package isn't useful unless you are using `closure-util` to create a custom build.

**Comment by hyperknot** [comment]
Thanks. The whole "ol" vs. "openlayers" npm package was not clear. 4.0 is the reason why I had an other go at using npm supplied openlayers.  So I tried looking everywhere on the website, the release page links only to the "openlayers" package without mentioning anything about the new "ol" one. So pretty much no way of knowing this information based on the website.

OK, now with the ol one, I think it's not really compatible with using commonjs / require with browserify. I had a look at the browserify gist, but it is using new style modules, not `require('ol')` style ones.

Is it possible to mix those modules with a project already using `require` statements everywhere?

**Comment by blindfish3** [comment]
I have hit a similar issue as I couldn't get openlayers to compile when running `npm install --save-dev openlayers`.  I got a 502 error when trying to download closure-library and it didn't re-attempt the download :/

Using require from the ol package might be an option; but with what looks like 400 modules to choose from it would be nice to have a shortcut to pull in core/commonly used modules...

**Comment by fredj** [comment]
closure-util is not used anymore, closing.
