### ISSUE TITLE
Drag the Map from the right border to the left border 4 times . The right half of the map cannot be drawed on 

### ISSUE THREAD

**Issue by xingchch** [openlayers/openlayers#6782]
This happend on below official example. 

http://openlayers.org/en/latest/examples/draw-and-modify-features.html

Drag the whole map from righ side to left side 4 times. right side can not be drawed, but left side works.  

![Uploading 未命名截图.png…]()

**Comment by ahocevar** [comment]
Draw coordinates will be different when you shift the world across several date lines. We recommend to configure a view extent to avoid date line shifts across several worlds when using drawing tools. Something like
```js
new ol.View({
  extent: ol.proj.get('EPSG:3857').getExtent(),
  // ...
});
```
