### ISSUE TITLE
How openlayer loads tile images?

### ISSUE THREAD

**Issue by bjdash** [openlayers/openlayers#6783]
We have a requirement where the map data needs to be secured. So to do that we have added a proxy server that validates the user and makes the call back to a geo server. To do that we have followed the approach mentioned here https://github.com/openlayers/openlayers/issues/5401. We make an `XMLHttpRequest` and upon getting the response convert it to image url and set the source of tile.
```
if (this.readyState == 4 && this.status == 200) {
    // code taken from
    // https://github.com/openlayers/openlayers/issues/5401
    var arrayBufferView = new Uint8Array(this.response);
    var blob = new Blob([arrayBufferView], {
            type: 'image/png'
        });
    var urlCreator = window.URL || window.webkitURL;
    var imageUrl = urlCreator.createObjectURL(blob);
    tile.getImage().src = imageUrl;
}
```
But if some user doesnt want to go through our proxy server and use direct url of geoserver then they face the CORS issue and the request is blocked.

I see that while loading images, openlayer doesn't make XMLHttpRequests. Can any one share a code snippet on how to load the image or point me where is it in the source files?

**Comment by ahocevar** [comment]
By default, the `tileLoadFunction` just sets the image's `src`, so the browser loads the image. To configure the underlying `Image` element to handle CORS, you simply need to configure your source with `crossOrigin: 'anonymous'`.
