### ISSUE TITLE
Open Layers changing format options in GetMap call in IE11

### ISSUE THREAD

**Issue by moylbr** [openlayers/openlayers#6788]
[chrome_log.txt](https://github.com/openlayers/openlayers/files/988916/chrome_log.txt)
[ielog.txt](https://github.com/openlayers/openlayers/files/988917/ielog.txt)

Hi,
I have found a difference in behaviour when doing a map call that displays the legend in the map using Geoserver.  It works in Chrome but the legend does not appear in IE11.  This behaviour has occurred in the last few months but I have not been able to track it to a specific version of either Geoserver or OpenLayers so I'm guessing it's a change in IE.

Looking at the geoserver log I noticed that the GetMap call had different results between IE and Chrome.

In IE the format options in the GetMap call changed itself to
FormatOptions = {DPI=94}

Whereas in Chrome it stayed as
FormatOptions = {LAYOUT=show_legend}

I wrote a simple test case by modifying one of the OL demos.  The code is

<!DOCTYPE html>
<html>
  <head>
    <title>Test case</title>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.1.1/css/ol.css" type="text/css">
    
    
    <script src="https://openlayers.org/en/v4.1.1/build/ol.js"></script>
  </head>
  <body>
    <div id="map" class="map"></div>
    <script>
      var layers = [
        new ol.layer.Tile({
          source: new ol.source.OSM()
        }),
        new ol.layer.Image({
          extent: [-13884991, 2870341, -7455066, 6338219],
          source: new ol.source.ImageWMS({
            url: 'http://127.0.0.1:8080/geoserver/wms',
            params: { 'LAYERS' : 'topp:states', 'format_options' : 'layout:show_legend' },
            ratio: 1,
            serverType: 'geoserver'
          })
        })
      ];
      var map = new ol.Map({
        layers: layers,
        target: 'map',
        view: new ol.View({
          center: [-10997148, 4569099],
          zoom: 4
        })
      });
    </script>
  </body>
</html>

and I have attached a copy in the file basic3.txt along with the Geoserver logs from the IE and Chrome calls.

The show_legend refers to the technique used in http://docs.geoserver.org/latest/en/user/services/wms/decoration.html
and the show_legend.xml files looks like this

<layout>

    <decoration type="legend" affinity="bottom,right" offset="5,5" size="auto"/>
</layout>

The code has worked previously in both Chrome and IE and I've simplified it down to remove any of my code as well.

I've also raised this with the Geoserver team as I don't know where the change to the GetMap request is occurring.

My environment details are as follows.

Geoserver version = 2.11.0
git revision = 43069ede17858a25592f14b5e159c20cd25619fc
git branch = origin/master
build date = 22-Mar-2017 19:08
geotools version = 17.0
geotools revision = cf34347a4544cac900c09f2e5de4c5fb138c8637
geowebcache version = 1.11.0
geowebcache revision = 1.11.x/02b79570ae64d548f9fb39bcab5edc9cb4d0c99
hudson build = -1

Tomcat : 7.0.56
JVM 1.8.0.131-b11
Windows 8.1
IE Vers : 11.0.9600.18639
Update Vers 11.0.41 (KB4014661)
Chrome Vers : V58.0.3029.96 (64 bit)

Any thoughts or suggestions on this would be greatly appreciated.

Brendan
[basic3.txt](https://github.com/openlayers/openlayers/files/988951/basic3.txt)

**Comment by bartvde** [comment]
can you try with uppercase FORMAT_OPTIONS ?

**Comment by moylbr** [comment]
Thank you.  That worked and it is now displaying in IE and Chrome.  Is it case sensitive?

**Comment by bartvde** [comment]
yes looking at the code it's case-sensitive

**Comment by bartvde** [comment]
see here: https://github.com/openlayers/openlayers/blob/master/src/ol/source/imagewms.js#L274

**Comment by moylbr** [comment]
Thank you.  I had not thought to try that.
