### ISSUE TITLE
Geojson-vt rendering doesn't work for other geometries than Polygon

### ISSUE THREAD

**Issue by oterral** [openlayers/openlayers#6789]
[Example with a line ](https://codepen.io/anon/pen/aWqwxm?editors=0010)

**Comment by ahocevar** [comment]
Are you sure this has to do with the geometry type? From a quick glance at the code pen, it looks like the generated features are valid and have the correct tile pixel coordinates. Maybe something is wrong with the `tileGrid` or `tilePixelRatio` definition for the source?

**Comment by fredj** [comment]
the issue is here:
https://github.com/openlayers/openlayers/blob/master/examples/geojson-vt.js#L31

the geometry is always (linestring or polygon) something like `[[x1, y1], [x2, y2], ...]` so the current code works well for `*Polygon` but not for the other types.

**Comment by ahocevar** [comment]
The example could be fixed easily though. @oterral, are you up for creating a pull request?
