### ISSUE TITLE
Features at vector source should have different ID

### ISSUE THREAD

**Issue by drnextgis** [openlayers/openlayers#6803]
I've stumbled upon an unexpected behaviour. I need to merge data from GeoJSON files into one vector source (see [example](https://jsfiddle.net/_DR_/5o9nb34j/)). But features comes from these datasets has the same feature id. As you can see [here](https://github.com/openlayers/openlayers/blob/3ff33699c881a80a341d2f8c5a7decb78976e995/src/ol/source/vector.js#L221) ids of features should be different otherwise it will be discarded. Please add information about this to ol.source.Vector documentation.

**Comment by ahocevar** [comment]
Pull request welcome.

**Comment by drnextgis** [comment]
https://github.com/openlayers/openlayers/pull/6806

**Comment by ahocevar** [comment]
Fixed with #6806.
