### ISSUE TITLE
readTransactionResponse haven't any return?

### ISSUE THREAD

**Issue by bigzkq** [openlayers/openlayers#6804]
Hi!
When I try to parse insertIds(fid) from the geoserver's response, I only obtained a empty Obect.
I don't know why this, this is  my source for readTransactionResponse : 
<wfs:WFS_TransactionResponse...>
 <wfs:InsertResult>
  <ogc:FeatrueId fid="test.888"></ogc:ogc:FeatrueId>
 </wfs:InsertResult>
...
Hope have a good answer.
Thx.

**Comment by bartvde** [comment]
It works fine in the unit tests see: https://github.com/openlayers/openlayers/blob/master/test/spec/ol/format/wfs/TransactionResponse.xml

https://github.com/openlayers/openlayers/blob/master/test/spec/ol/format/wfs.test.js#L177

**Comment by bigzkq** [comment]
Thank your testing, I'm newcomer. I had found the reasons, that is wfs version. But why not support wfs(1.0.0),  I'm very hard to understand it.
Very thanks!

**Comment by bartvde** [comment]
Why do you need WFS 1.0.0?
