### ISSUE TITLE
Constrain mouse zoom to level values

### ISSUE THREAD

**Issue by felixveysseyre** [openlayers/openlayers#6808]
Hello,

I made a visualization application based on OpenLayers.
I recently updated the version used from 3.18 to 4.1.
I noticed a change in the the zooming interaction.
With 3.18, zooming with the mouse wheel was changing the zoom factor step by step.
With 4.1, zooming is more continuous and reach some intermediary values.

Is it possible to constrain the zoom to the level of definition of my source ?

Thanks for you awesome work

**Comment by adube** [comment]
`contrainResolution` may be what you're looking for:

      var map = new ol.Map({
        interactions: ol.interaction.defaults({mouseWheelZoom: false}).extend([
          new ol.interaction.MouseWheelZoom({
            constrainResolution: true // force zooming to a integer zoom
          })
        ]),
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        target: 'map',
        view: new ol.View({
          center: [0, 0],
          zoom: 2
        })
      });

Also, please use http://stackoverflow.com/questions/tagged/openlayers-3 for such questions.  You can close this if this fixes your issue.

Happy Coding!

**Comment by felixveysseyre** [comment]
Thanks a lot, it made the trick !

Before posting here, I took a look a the documentation but I guess I did not look in the correct class.
