### ISSUE TITLE
KML IconStyle - Add Color Support

### ISSUE THREAD

**Issue by jhaverkost** [openlayers/openlayers#6809]
The KML `<IconStyle>` in OpenLayers does not properly support coloring icons. According to the KML reference guide, `<IconStyle>` extends `<ColorStyle>` and should support the `<color>` element. However, OpenLayers seems to ignore this element.

From my investigation, it looks like this can be fixed by making a few simple changes:

- Add a color parser to ol.format.KML.ICON_STYLE_PARSERS_
- Add the newly parsed color to the ol.style.Icon created by ol.format.KML.IconStyleParser_
- For completeness, it looks like ol.format.KML.ICON_STYLE_SEQUENCE_ and ol.format.KML.ICON_STYLE_SERIALIZERS_ would also need to be updated.

If I find some time, I will attempt to submit a fix for this issue. Having never contributed to OpenLayers before, it may take some time.

**Comment by lysek** [comment]
I ran into this issue today, can someone please take a look at this. Here is the KML example:
```
<?xml version="1.0"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
   <Document>
      <description>KML icon color demo</description>
      <name>kml.icon</name>
      <open>1</open>
      <Style id="123">
         <IconStyle>
            <color>FF0000FF</color>
            <Icon>
               <href>/path/to/icon.png</href>
            </Icon>
         </IconStyle>
      </Style>
      <Folder>
         <name>Icons</name>
         <Placemark id="456">
            <description>A point</description>
            <name>17E 49N</name>
            <styleUrl>#123</styleUrl>
            <visibility>1</visibility>
            <Point>
               <altitudeMode>absolute</altitudeMode>
               <coordinates>17,49,0</coordinates>
            </Point>
         </Placemark>
      </Folder>
   </Document>
</kml>
```
