### ISSUE TITLE
Double Tap to Zoom - Not working on Samsung Galaxy

### ISSUE THREAD

**Issue by traildex** [openlayers/openlayers#6811]
Our Android/iOS app has used openlayers 3 for a couple years now.

Double tapping the map to zoom always worked fine. As did using forEachFeatureAtPixel for our objects.

Two weeks ago it stopped working on my Galaxy Note 4
Last week it stopped working on my Galaxy S5

Currently on OL 4.0.1, I tried 4.1.1 and rolling back to 3.20.1
No better or worse, the two functions above do not work.
No errors in console.log
No changes to my code in months
The map flickers a tad when tapping sometimes
If I tap like a madman I can sometimes get forEachFeatureAtPixel to work occasionally
All other touch functions work fine: drag map, two finger map rotate, etc

Works fine on iPad and iPhone. In fact the following example works on iPad/iPhone but NOT on either of my Galaxy devices
https://openlayers.org/en/latest/examples/custom-icon.html

I'm guessing the issue is related to Galaxy updates as both my devices had recent auto software updates.

**Comment by ischas** [comment]
Related to #6776?

**Comment by traildex** [comment]
@ischas
yes that sounds related, thx

**Comment by fredj** [comment]
@traildex please test on http://openlayers.org/en/master/examples/simple.html

Reopen the issue is the problem persist.
