### ISSUE TITLE
Draw new linestring with select and modify interactions

### ISSUE THREAD

**Issue by wilco73** [openlayers/openlayers#6815]
Hello,

I need to draw point and linestring, and can select and modify them.
But when I try to draw a new linestring, I have an error "Cannot read property 'minX' of undefined".

At first I thought it was because my code was too complicated, but when I try to do the same thing in a simple example, I have the same issue.

https://codepen.io/wilco73/pen/xdzjLG

In this example, you cannot draw a linestring properly. The problem arises when the modify and the select interactions have the same source, but I want to modify only the selected features.

**Comment by PerryRylance** [comment]
Wilco - set the modify interaction to be inactive, and then activate it when the user makes a selection
