### ISSUE TITLE
Point Vector

### ISSUE THREAD

**Issue by Ballantines42** [openlayers/openlayers#6820]
Hello,

My layer is a  ol.layer.Vector  and my source is ol.source.Vector and my style is a img camera.png : 

Result : 
 
![cam](https://cloud.githubusercontent.com/assets/27500104/26148100/dad4e0d8-3af5-11e7-9efb-da2525166781.JPG)

But when I put my mouse over an element, A blue point appears :
 
![cam2](https://cloud.githubusercontent.com/assets/27500104/26148194/23da01d2-3af6-11e7-89df-e22d50e4a300.JPG)

I don't want blue point, what to do ?

**Comment by ahocevar** [comment]
You have to modify the style for the layer you populate with the features that you hover over.

**Comment by Ballantines42** [comment]
Sorry but I don't understand , Please can you more explain ?

**Comment by ahocevar** [comment]
You have to share your code. We cannot explain more when we don't know more about what you're doing.

**Comment by Ballantines42** [comment]
var vectorSource = new ol.source.Vector({
                format: new ol.format.GeoJSON(),
                projection: "EPSG:3857",
                url: function(extent) { return geoserver.getWfsUrl('v_syn_lay_camera_dirce', extent.join(','));},
                strategy: ol.loadingstrategy.bbox
            });

var styleLayer = new ol.style.Style({
                        image: new ol.style.Icon({
                            src: './resources/images/camera_48.png',
                            scale: 0.4,
                        })
                    });

 var Layer = new ol.layer.Vector({
                    title: "EXTERNE",
                    visible: true,
                    preview: "./resources/images/logo_camera.png",
                    projection: "EPSG:3857",
                    source: vectorSource,
                    style: styleLayer
                });

map.addLayer(Layer);

You need another part of my code ?

**Comment by ahocevar** [comment]
Please format your code using Markdown. You do not show the code that is used to highlight features on mouseover, so what you posted does not help.

**Comment by cs09g** [comment]
blue point is default style. and it's about hover interaction or event.

**Comment by Ballantines42** [comment]
I have resolve my problem, thanks for your help !

**Comment by Pim92** [comment]
Same problem, here, can you give your solution, please?
