### ISSUE TITLE
'clearRect' of null

### ISSUE THREAD

**Issue by tSte** [openlayers/openlayers#6822]
Today, I tried to update older project from of mine from OL 3.14.0 to 4.1.1 and ran into strange problems...

I have this code:
```js
goog.require('ol.Map');
goog.require('ol.View');
goog.require('ol.layer.Tile');
goog.require('ol.source.TileWMS');
goog.require('ol.proj');
goog.require('ol.proj.Projection');

const proj = new ol.proj.Projection({
  units: 'm',
  code: 'EPSG:102067',
  extent: [
    -591853.953599996, -1335325.79404671, -164933.953599996, -1132205.79404671
  ]
});

ol.proj.addProjection(proj);

const map = new ol.Map({
  view: new ol.View({
    center: [-378374.06625, -1233729.73125],
    zoom: 2,
    projection: proj
  }),
  target: 'map',
  layers: [
    new ol.layer.Tile({
      source: new ol.source.TileWMS({
        url: 'https://zbgisws.skgeodesy.sk/zbgis_dmr3_wms/service.svc/get',
        params: { 'LAYERS': '0' }
      })
    })
  ]
});
```

I compile this using the GCC v.20160911.0.0 with advanced optimizations. When I run this code, the `<canvas>` element is drawn to the `target` element and all of the WMS tiles are fetched correctly. But they are not drawn to the map. Each interaction with map (e.g. pan, zoom, ...) produces errors:

`$JSCompiler_StaticMethods_ol_layer_Layer_prototype$getSource$$($JSCompiler_StaticMethods_drawTileImage$self$$inline_785$$.$f$).$getOpaque$($frameState$$inline_787$$.$viewState$.projection) || $JSCompiler_StaticMethods_drawTileImage$self$$inline_785$$.**_$a$_**.clearRect($x$$inline_788$$, $y$$inline_789$$, $w$$inline_790$$, $h$$inline_791$$);` 

_Cannot read property 'clearRect' of null._ - [context of the ol.renderer.canvas.TileLayer](https://github.com/openlayers/openlayers/blob/9b9ac0376085a52d58abc831205c6a9cba14a7bb/src/ol/renderer/canvas/tilelayer.js#L266) is `null`.

I am not sure weather this is a bug or I made a mistake, but... could you please explain how is this supposed to work? Because when I tried to track a class that is responsible for the `context` property, I ended up with empty hands.

I understand that `ol.renderer.canvas.TileLayer` creates new `context` if it is not `null`, but that is all I was able to track. 

I see that:
it inherits from `ol.renderer.canvas.IntermediateCanvas`
that inherits from `ol.renderer.canvas.Layer`
that inherits from `ol.renderer.Layer`
that inherits from `ol.Observable`

but none of those seem to introduce the `context` property. Could you, please, explain me, what is the issue here?

Note: I don't have this issue with openlayers@4.0.0

**Comment by ahocevar** [comment]
Looks like a compiler issue, or at least something related to compilation. Works fine with a full build: https://codepen.io/anon/pen/JNadjX?editors=1010.

**Comment by fredj** [comment]
Closing due to lack of response.
