### ISSUE TITLE
Webgl polygon rendering

### ISSUE THREAD

**Issue by ondrejlaga** [openlayers/openlayers#6823]
I have a simple map with one feature, if I switch renderer to canvas, everything is ok, but if I switch renderer to webgl, feature is hidden and sometimes browser freeze. Is it a problem with bad feature or with rendering?
[renderer.zip](https://github.com/openlayers/openlayers/files/1007630/renderer.zip)

**Comment by ahocevar** [comment]
I'd consider the WebGL renderer a bit experimental. Is there any reason why you cannot use the standard Canvas renderer?

**Comment by gberaudo** [comment]
@ondrejlaga, FWIW, there is a warning in firefox when moving the mouse:
`Error: WebGL warning: drawElements: Drawing to a destination rect smaller than the viewport rect.`

The polygon looks complex, maybe it is a corner case not triangulated properly. @GaborFarkas any idea?

**Comment by GaborFarkas** [comment]
If the canvas renderer can draw it, then it is certainly not a bad feature, but there is something wrong with the renderer. I will look into it soon. Thank you for the extra information @gberaudo, it will be a good starting point. It is something bigger than a triangulation error AFAICS. When I tested the renderer on very bad polygons, it could still draw them, just not correctly/accurately.

**Comment by GaborFarkas** [comment]
Now this is something really weird you should definitely try out @gberaudo, @ahocevar.

- First of all, the triangulation algorithm has a long way to go. Thank you for the example data, @ondrejlaga, I will try to fix it up somewhat based on that.

- There are several different problems. When the select event is associated with a pointer move event, we get an [Assertion error 30](http://openlayers.org/en/latest/doc/errors/#30) sometimes. Still need to figure out the nature of the bug. With the default click event, there is no problem.

- What is weird, the polygon disappears on greater zoom levels, as the flat coordinates are supplied as strings. An ugly fix in `ol.render.webgl.PolygonReplay.prototype.drawPolygon` mapping the flat coordinates to `Number` solves this issue. There might be a chance, the 2D canvas's drawing methods actually accept coordinates as strings. The coordinates are coming from the `ol.geom.flat.simplify.quantize` function, and again, they are coming as strings only on greater zoom levels.

**Comment by fredj** [comment]
@ondrejlaga the GeoJSON is invalid; the coordinates are encoded as string instead of number

fixed version here: https://gist.github.com/fredj/ea28e945e49bc93e26339fdafb99c300
