### ISSUE TITLE
Click on map (Samsung Chrome Android)

### ISSUE THREAD

**Issue by fontsie** [openlayers/openlayers#6824]
I try to select feature in this example: http://openlayers.org/en/latest/examples/select-features.html
Only works is Hover, Click events are not fire.

Chrome version: 58.0.3029.83
Samsung S7 Android 7

**Comment by bartvde** [comment]
see https://github.com/openlayers/openlayers/issues/6776

**Comment by fontsie** [comment]
Ok, I'll test using master version. I let you know.

**Comment by cs09g** [comment]
the thing that hover works in mobile is weird as well.

**Comment by fredj** [comment]
@fontsie I'm closing this issue, add a comment if you still doesn't work for you

**Comment by fontsie** [comment]
Fixed in 4.2.0 with 'moveTolerance'
