### ISSUE TITLE
ol.interaction.Snap: addFeature significantly faster then passing in an ol.Collection<ol.Feature>

### ISSUE THREAD

**Issue by cvenzin** [openlayers/openlayers#6828]
I discovered a strange behavior using the ol.interaction.snap. If I use the `features` property to pass in an ol.Collection (around 3000 features), removing the interaction from the map with `removeInteraction `takes up to 5 sec (Browserfreeze, tested with Chrome 58). If I use the addFeature method to add all the 3000 features, removing the interaction from the map with `removeInteraction `is instantaneous.

```
addOrUpdateSnapping() {
    if (this.snap) {
      this.map.removeInteraction(this.snap);
    }
    const features: ol.Collection<ol.Feature> = new ol.Collection([]);
    const currentExtent = this.map.getView().calculateExtent(this.map.getSize());
    const currentResolution = this.map.getView().getResolution();
    this.map.getLayers().forEach((layer: ol.layer.Layer) => {
      if (layer.getVisible() && currentResolution > layer.getMinResolution() && currentResolution < layer.getMaxResolution()) {
        const layerExtent = layer.getExtent();
        if (!layerExtent || (layerExtent && ol.extent.intersects(currentExtent, layerExtent))) {
          if (layer instanceof ol.layer.Vector) {
            features.extend(layer.getSource().getFeatures());
          } else if (layer.get("hxgnVectorSource")) {
            features.extend(layer.get("hxgnVectorSource").getFeatures());
          }
        }
      }
    });
    // do not pass in the collection directly -> removing the interaction will be super slow
    this.snap = new ol.interaction.Snap({
      features: new ol.Collection([])
    });
    features.forEach(feature => {
      this.snap.addFeature(feature);
    });
    this.map.addInteraction(this.snap);
    console.log(`SnapService: snap interaction added, number of features = ${features.getLength()}`);
  }
```

**Comment by cvenzin** [comment]
here is an example to reproduce the behavior: [codepen](https://codepen.io/cvenzin/pen/NjENRX)

**Comment by markus659** [comment]
I have also noticed this. Thank you @cvenzin for providing a workaround.

**Comment by domiSchenk** [comment]
what is the status on this issue?

**Comment by ahocevar** [comment]
It's still not recommended to use an ol.Collection here.

**Comment by domiSchenk** [comment]
I created for every `ol.layer.Vector` its own `ol.interaction.Snap` and used its `ol.source.Vector`.
Some layer do have quite a lot of Features or a lot of Vertices, this results in bad performance.
(They are added at the startup, if I add them later my app freezes for 5-10 sec [depending on machine])
So Im looking for some solution
