### ISSUE TITLE
ol.interaction.Select

### ISSUE THREAD

**Issue by BouchProg** [openlayers/openlayers#6830]
Hello,

I use ol.interaction.Select but when fly over feature, my icon disappears.

    var selectPointerMove = new ol.interaction.Select({
        condition: ol.events.condition.pointerMove,
        style: []
    });

What should I put in style to keep my basic icon?

thanks for your help

**Comment by cs09g** [comment]
You can put style function which brings 'feature' and 'layer' parameter. and check 'feature' in the function through console. then it will help you out. BTW, you better post this kind of query in StackOverflow with tag "openlayers".
