### ISSUE TITLE
Parsed WMTS Capabilities object leads to an error in ol.source.WMTS.optionsFromCapabilities

### ISSUE THREAD

**Issue by cvenzin** [openlayers/openlayers#6835]
The WMTS Capabilites documents found on [zg.ch](https://www.zg.ch/behoerden/direktion-des-innern/geoportal/geodaten-einbinden/web-map-tile-service-wmts) are not fully supported by the ol.source.WMTS.optionsFromCapabilities function. I think the constraint property is missing in the WMTSCapabilities object.

See this [example](https://codepen.io/cvenzin/pen/rmQedE?editors=1010) using the [https://maps.zg.ch/basisplan_sw_tiled_lv03/ExtendedCapabilities.xml](https://maps.zg.ch/basisplan_sw_tiled_lv03/ExtendedCapabilities.xml) capabilites document.

**Comment by fredj** [comment]
`Constraint` is optional in `OperationsMetadata`
