### ISSUE TITLE
How can get the image of each tile layers.

### ISSUE THREAD

**Issue by nqlong** [openlayers/openlayers#6836]
Hi everyone, I have a goal to detect any feature exists on each layer when the map view change. My way is to access all tile on each layer in map view and detect which pixel is not transparent.
I have searched all issues and found the tileLoadFunction maybe can be used. I have tried but it doesn't work. 
I also found the example [http://openlayers.org/en/latest/examples/image-filter.html]. It used the canvas from the layer.tile with source BING map. I tried to change to use WMTS source and it gave me the CORS problem.
Anyone can give me the hint or something can solve my problem.
Thank you

**Comment by ahocevar** [comment]
You could register a listener for the source's `tileloadend` event, which gives you a reference to the loaded tile. But it won't solve the problem that you'll get CORS errors when you're trying to analyse the image. It is better to proceed like in the image-filter example, and configure your source with `crossOrigin: 'anonymous'`. That requires that the server that provides the tiles sends proper CORS headers.

**Comment by nqlong** [comment]
Hi @ahocevar 
Thank you for your support. I have solved the CORS problem and use the tileloadend event. I have tested tileloadend event. So, it just get new tile from server and doesn't give the loaded tiles. Correct me if I  am wrong. Actulaly, I want to getImage from each sourcetile on map view. Thank you so much.
I reference your old post #2636

**Comment by ahocevar** [comment]
When you have set CORS headers properly, you can also access the canvas in a postcompose listener. That's easier then managing the tiles and getting the tiles that are in the map view.

**Comment by nqlong** [comment]
I also used the postcompose listener to get tile. It works but it still have a problem.  I have many tileWMS layers and want to get seperate tile layers the the map view for filtering. The event postcompose just return canvas with all tile layers. So it doesn't work with me. Whatever, thank you so much. If you have any idea, please  let me know.
