### ISSUE TITLE
ol.object.set()  juge properties error

### ISSUE THREAD

**Issue by xiaoq07** [openlayers/openlayers#6846]
ol.Object.prototype.set = function(key, value, opt_silent) {
  if (opt_silent) {
    this.values_[key] = value;
  } else {
    var oldValue = this.values_[key];
    this.values_[key] = value;
    if (oldValue !== value) { //it's can't juge tow array
      this.notify(key, oldValue);
    }
  }
};

when the value is two same array, it is wrong.
like  [1,2]===[1,2] // it‘s false
Should you fix it?
thanks.

**Comment by ahocevar** [comment]
The current behaviour is intentional, and produces results the expected results:
```js
var arr1 = [1, 2];
var arr2 = [1, 2];
arr1 === arr1; // true
arr1 === arr2; // false
ol.array.equals(arr1, arr2); // true
```
When your application sets arrays on an object and you get notified that a value has changed, you can still do an `ol.array.equals` check to decide whether the old array has the same values as the new one.
