### ISSUE TITLE
Issues with dragpan on ol-3.4.0 version

### ISSUE THREAD

**Issue by 4l4l4l** [openlayers/openlayers#6847]
Hello, i have some issues with draw points with dragpan interaction. I fix this problem by next code:

```
            var test = undefined;
            map.getInteractions().forEach(function (interaction) {
                if(interaction instanceof ol.interaction.DragPan) {
                    test = interaction;
                    map.removeInteraction(interaction);
                }
            });
            // some draw functions and etc
            draw.on('drawend', function(e2) {
                map.removeInteraction(this);
                map.addInteraction(test);
                //some actions
            });
```
I remove it from map interactions but after i draw a point on map i enable it. If i dont do this, my point doesnt appear on map.

**Comment by ahocevar** [comment]
Can you please check if the issue persists in the latest version (v4.1.1)? Thanks.

**Comment by 4l4l4l** [comment]
Sorry, i cant check it. We want to finish our work on 3.4.0 and we are stuck on it right now. I said it to my teamleader about changing to the new version, but we cant. As we can see 
new ol.source.Vector({ loader: function }) load function in vector was changed a bit and other things too.

**Comment by ahocevar** [comment]
Can't you isolate the problem in a minimal example, e.g. by creating a [CodePen](https://codepen.io)?

**Comment by 4l4l4l** [comment]
The real problem was on map. When i changed it top OSM raster all works well. Sorry for this post.
