### ISSUE TITLE
ol.extent.getArea is not in the Api

### ISSUE THREAD

**Issue by polar** [openlayers/openlayers#6854]
The functions ol.extent.getWidth and ol.extent.getHeight and ol.extent.isEmpty are in the api, but why not ol.extent.getArea?

Cheers,
-Polar

**Comment by cs09g** [comment]
Can I create a PR?

**Comment by fredj** [comment]
@cs09g yes, please create a PR

**Comment by polar** [comment]
Thanks!

Cheers,
-Polar
