### ISSUE TITLE
remove @private from addFeature_ to allow more features on map to be modifiable

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#6857]
Interaction is known for map layer itself but Modify interaction is for features on map. So, when you need to enable modification for features which is created after interaction's added to view, there's no way to add more features to modify. "addFeature_" is the one that makes more features be modifiable, and unfortunately it's private method for now. Is it okay to be public?

**Comment by ahocevar** [comment]
`ol.interaction.Modify` is constructes with `features`, which is an `ol.Collection`. The collection has an `add` method, which you should be using for adding features.

**Comment by cs09g** [comment]
But I don't see how to access `add` method from `ol.interaction.Modify`. To use `add`, you need to use `features_` which is private.

**Comment by ahocevar** [comment]
The `features` collection is a required configuration option of `ol.interaction.Modify`. So you do have the collection already from the time you constructed the interaction. The method you'll want to use on the collection is `push`, not `add`. Sorry for that.

**Comment by cs09g** [comment]
Thanks, but then should keep tracking the collection for add/remove features after modify interaction added to the view?
