### ISSUE TITLE
canvas.toDataURL("image/png"); got wrong url? 

### ISSUE THREAD

**Issue by winer632** [openlayers/openlayers#6859]
Below is my code. 
When I use getMapBase64(), I got wrong dataURL. And it seems I got only one layer?
However when I save the map as map.png, upload it to linux server, then call getBase64("http://115.159.218.200:4000/map.png") , I can get right dataURL.
What's the problem with my code in function getMapBase64()?

```
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="/ol.css" type="text/css">
    <style>
      .map {
        height: 256px;
        width: 512px;
      }

    </style>
    <title>OpenLayers example</title>
  </head>
  <body>
    <h1>My Map</h1>
    <div id="map" class="map"></div>
    <a id="export-png" class="btn btn-default"><i class="fa fa-download"></i> Download PNG</a>
    <script src="/loader.js" type="text/javascript"></script>
    <script type="text/javascript">
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
              title: 'Global Imagery',
              source: new ol.source.TileWMS({
              crossOrigin: 'anonymous',
              url: 'https://ahocevar.com/geoserver/wms',
              params: {'LAYERS': 'nasa:bluemarble', 'VERSION': '1.1.1'}
            })
          })
        ],
        view: new ol.View({
          projection: 'EPSG:4326',
          center: [0, 0],
          zoom: 0,
          maxResolution: 0.703125
        })
      });


      var dataURL='';


      function getMapBase64(){

          map.once('postcompose', function(event) {
              var canvas = event.context.canvas;
              dataURL = canvas.toDataURL("image/png");
          });
          map.renderSync();
      }



      // function getBase64(url){
      //     console.log("getBase64");
      //     //通过构造函数来创建的 img 实例，在赋予 src 值后就会立刻下载图片，相比 createElement() 创建 <img> 省去了 append()，也就避免了文档冗余和污染
      //     var Img = new Image();
      //     Img.src=url;
      //     Img.onload=function(){ //要先确保图片完整获取到，这是个异步事件
      //         var canvas = document.createElement("canvas"), //创建canvas元素
      //         width=Img.width, //确保canvas的尺寸和图片一样
      //         height=Img.height;
      //         canvas.width=width;
      //         canvas.height=height;
      //         canvas.getContext("2d").drawImage(Img,0,0,width,height); //将图片绘制到canvas中
      //         dataURL=canvas.toDataURL('image/png'); //转换图片为dataURL
      //     };
      // }


      getMapBase64();
      // getBase64("http://115.159.218.200:4000/map.png");

      console.log("dataURL is "+dataURL);

    </script>
  </body>
</html>
```

**Comment by ahocevar** [comment]
Your `console.log` is executed before the `dataURL` is assigned. It is assigned in an `onload` listener. If you move the `console.log` into the onload listener, you will see the `dataURL`.

**Comment by winer632** [comment]
I changed my code according to your advice, but still get wrong dataURL.

<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="/ol.css" type="text/css">
    <style>
      .map {
        height: 256px;
        width: 512px;
      }
    </style>
    <title>OpenLayers example</title>
  </head>
  <body>
    <h1>My Map</h1>
    <div id="map" class="map"></div>
    <a id="export-png" class="btn btn-default"><i class="fa fa-download"></i> Download PNG</a>
    <script src="/loader.js" type="text/javascript"></script>
    <script type="text/javascript">
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
              title: 'Global Imagery',
              source: new ol.source.TileWMS({
              crossOrigin: 'anonymous',
              url: 'https://ahocevar.com/geoserver/wms',
              params: {'LAYERS': 'nasa:bluemarble', 'VERSION': '1.1.1'}
            })
          })
        ],
        view: new ol.View({
          projection: 'EPSG:4326',
          center: [0, 0],
          zoom: 0,
          maxResolution: 0.703125
        })
      });


      var dataURL='';


      function getMapBase64(){

          map.once('postcompose', function(event) {
              var canvas = event.context.canvas;
              dataURL = canvas.toDataURL("image/png");
              console.log("dataURL is "+dataURL);
          });
          map.renderSync();
      }

    </script>
  </body>
</html>

**Comment by ahocevar** [comment]
The GeoServer you are using is not configured to send CORS headers to other domains than openlayers.org. You'll have to use a different tile source.

**Comment by winer632** [comment]
Thank you, I will try.
