### ISSUE TITLE
OSGeo-Live project maintainer is needed

### ISSUE THREAD

**Issue by astroidex** [openlayers/openlayers#6860]
* we from OSGeo-Live project tried to contact the OpenLayers project
* the are looking for a new maintainer for OL on OSGeo-Live

work to do: 
* decide which version to put on OSGeo-Live version
* update OL version in sh https://github.com/astroidex/OSGeoLive/blob/master/bin/install_openlayers.sh
* update documentation 
** https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/overview/openlayers_overview.rst
** https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/quickstart/openlayers_quickstart.rst
** version https://github.com/OSGeo/OSGeoLive-doc/blob/master/conf.py

Please volunteer.

**Comment by bartvde** [comment]
hey Astrid, how did you try to contact before this attempt? I will look at your request today. Can I just PR on osgeolive repo?

**Comment by astroidex** [comment]
Yes - pull request would be fine see http://wiki.osgeo.org/wiki/Live_GIS_Disc#Git_migration

bartvde - would be great if we could add you as contact person.

**Comment by marcjansen** [comment]
> how did you try to contact before this attempt?

@astroidex wrote to me personally, and I failed to even respond. Mea culpa, @astroidex, your mail was marked important, but somehow I ignored it for quite a while. Sorry.

Ping me again if there is additional help you need. I won't be available to work as official contact person. but will help when time permits it.

**Comment by bartvde** [comment]
@astroidex do you or anyone else know what the legacy projects are that need openlayers 2 on the OSGeo Live?

```and OpenLayers 2.13.1 for legacy demos in OSGeoLive```

**Comment by bartvde** [comment]
since ideally I'd like to get rid of openlayers 2 on the OSGeo live and only use the latest stable (so 4.1.1)

**Comment by bartvde** [comment]
ah I found one here: https://github.com/OSGeo/OSGeoLive/blob/aaec0fddf95fd5ebf6b1af19dad41719075e9b15/app-conf/mapnik/local.html#L21

**Comment by bartvde** [comment]
but that seems to be the only one as far as I can tell

**Comment by astroidex** [comment]
* would be great to have OpenLayer 4.x installed. 

* please have a look at the package list and update OpenLayers to the version you will install
https://docs.google.com/spreadsheets/d/1Q5BaEgQtgw4O1bXyeWMlM8XtAOhUgcjZ7Y2O0FZc2H0/edit?hl=en_GB#gid=2014800150

**Comment by bartvde** [comment]
@astroidex PR for OSGeoLive and OSGeoLive-docs opened. Updated the spreadsheet as well with the version, but not as yet the field 11.0 comment. I'm happy to be point of contact going forward.

**Comment by astroidex** [comment]
great! Thanks @bartvde

**Comment by astroidex** [comment]
Please add yourself to the following file too https://github.com/OSGeo/OSGeoLive-doc/blob/master/contributors.csv

Then you will show up in the list https://live.osgeo.org/en/sponsors.html

**Comment by bartvde** [comment]
thanks for the pointer, done in the PR

**Comment by fredj** [comment]
@bartvde can we close this issue?
