### ISSUE TITLE
Map freezing when pinch zooming on ipad

### ISSUE THREAD

**Issue by ogo-adp** [openlayers/openlayers#6861]
We are getting this error on IOS 10.3.2 on safari, trying to migrate an app from 3.19.1 to 4.1.1, and when making fast pinch zoom in and out. All the map disappear (only the overlays stay there) and the map freeze completely. 

We also get this unhandled exception from webkit : DOM Exception 11 : The object is in an invalid state

From the stack trace (of the minified code) the offending line is the drawImage() call from this function :
 `function qv(a) { zt.call(this, a); this.u = yh(); this.j = null } u(qv, zt); qv.prototype.O = function (a, b, c) {
    Bt(this, "precompose", c, a, void 0);
    var d = this.Y();
    if (d) {
        var e = b.extent, f = void 0 !== e && !Ua(e, a.extent) && nb(e, a.extent);
        f && At(c, a, e);
        var e = this.A(), g = c.globalAlpha;
        c.globalAlpha = b.opacity;
        c.drawImage(d, 0, 0, +d.width, +d.height, Math.round(e[4]), Math.round(e[5]), Math.round(d.width * e[0]), Math.round(d.height * e[3]));
        c.globalAlpha = g;
        f && c.restore()
    } this.cf(c, a, b)
};`

For now i'm unable to repro this in a jsfiddle.

**Comment by ogo-adp** [comment]
Possible explanation of cause of crash here (canvas of zero size) :
https://stackoverflow.com/questions/4554551/webkit-uncaught-error-invalid-state-err-dom-exception-11

**Comment by ahocevar** [comment]
Can you provide a link to the application that triggers the problem? And please provide a stack trace with an unminified build.

**Comment by ogo-adp** [comment]
No sorry, I cannot provide a link to the application.

Messing with ol-debug.js, I see that the crashing function is ol.renderer.canvas.IntermediateCanvas.prototype.composeFrame

Adding some traces, I see that when crashing : 
context.canvas.clientWidth=1020
context.canvas.clientHeight=764
image.width=0
image.height=0
dx=NaN
dy=NaN
dw=0
dh=0

dw & dh are probably the cause of this exception

**Comment by ahocevar** [comment]
Full stack trace please.

**Comment by ogo-adp** [comment]
I'm unable to capture a stack trace on an ipad, is there a way ? Could you help me on this ?

Further trace of imageTransform : [1,0,0,1,null,null]

**Comment by ogo-adp** [comment]
I found a way to get a stack trace.  

- animationDelay function (near line 30946)
- in renderFrame_() (near line 32008)
- renderFrame() (near line 23326)
- composeFrame() (near line 68096)
- drawImage() -> crash

**Comment by ahocevar** [comment]
Looks like an invalid render transform. Impossible to tell without seeing your code what causes this. Please continue trying to reproduce in a CodePen.

**Comment by ogo-adp** [comment]
Thanks for your help. The application is complex, and working perfectly fine on chrome on Windows. The problem only happen on IOS. I will investigate further

**Comment by ogo-adp** [comment]
I've spent more time on this. 

In fact there are two distincts problem which lead to map freezing when pinch zooming on ipad :
1) The one for which I filed this issue. The exception is due to a projection problem caused by an object very much outside of the map when the real problem (2) happen. This can be ignored.
2) The real cause. Sometimes and only on ipad it seems ol.Kinetic.prototype.end() can compute a duration of 0 when doing some combination of pinch zooming, rotating and zooming, while having kinetic enabled. So, this.initialVelocity_ is not computed properly (division by zero), then ol.Kinetic.prototype.getDistance() returns Infinity, then ol.View.prototype.animate() will receive a bad animation.targetCenter which will lead to map being centered to [null, null] (via ol.ViewProperty.CENTER). Bad things happen then (map freeze)

Doing this simple correction in ol.Kinetic.prototype.end() does fix the problem for me (but it may not be the proper fix):

before : `this.initialVelocity_ = Math.sqrt(dx * dx + dy * dy) / duration;`
after : `this.initialVelocity_ = duration > 0 ? Math.sqrt(dx * dx + dy * dy) / duration : 0;`

I suspect there is another problem however (which I believe is also present in older pre v4 versions). When pinch zooming on ipad, sometimes the map is recentered whith a bad location very far away from the good one. It may be related to this (and is till present after this little fix).

**Comment by ogo-adp** [comment]
Hi again,

I looked at the code for the second problem (bad recenter of the map).

When doing simulteanously pan, zoom and rotate, it seems to me that `ol.View.prototype.updateAnimations_()` does something wrong for panning. It seems that animation.targetCenter is not computed correctly if there will also be a resolution change (and maybe also a rotation change - see `calculateCenterZoom()` and `calculateCenterRotate()` in the same function that do also alter the center). 

If I remove `this.set(ol.ViewProperty.CENTER, [x, y]);` then I loose the kinetic animation of panning, but then the recenter bug disappear. So I think the culprit is animation.targetCenter. 

Could you look at it ahocevar ?

**Comment by ogo-adp** [comment]
Here is a repro for bug 1 (map centered to [null,null]) :
[https://codepen.io/anon/pen/EXYPEr]

- open codepen with an ipad
- make rapid pinches (enlarge fingers) starting from the bottom left of the map and going to the center, try also to pan and rotate at the same time
- when the pinch is done, the center of map will be displayed below the map
- sometimes, the map goes nowhere (full grey), and the center displayed below the map will be [null,null]

**Comment by ogo-adp** [comment]
Here is a repro for bug 2 (map zooming erratically) : https://codepen.io/anon/pen/JJPXYd

nb: this repro contains the fix for bug 1 (to allow producing bug 2 without crashing safari)

- open codepen with an ipad
- make rapid pinches (enlarge on narrow fingers) around France, try also to pan and rotate at the same time
- when a dragPan interaction occur you will get kinetic computation results on the bottom of the map
- sometimes, the map will zoom erratically (in general in the region of Groenland)
- you will then see that dragPan computed a large value for distance

**Comment by sorny** [comment]
We have the exact same issue with an application running on iOS 10.3.2, Openlayers 4.1.1

The "white screen" only occurs if users use pinch-to-zoom, no reports by users using doubletap-to-zoom or using zoom control...

I tried your velocity divByZero fix, seems to work. Pushing it to a testflight and will report back the feedback of previously affected users.

About bug 2: Also reproduceable, not that severe at the moment since it only occurs on pinch/pan/rotate combo

**Comment by ogo-adp** [comment]
I've renamed this issue as the 'DOM Exception 11' was a side effect of bug 1.

**Comment by ahocevar** [comment]
@ogo-adp I am not familiar with the Kinetic code. But it looks like the calculation of a `0` duration and the far-off target center are related. Are you willing/able to dig more into this? We'd definitely accept a pull request with a fix.

**Comment by ogo-adp** [comment]
@ahocevar Yes, I'll look at it :)

**Comment by ogo-adp** [comment]
I'm unable to provide a PR, but I have a simple fix proposal for both bugs.

The fix is very simple. In `ol.Kinetic.prototype.end` just after `var duration = this.points_[lastIndex + 2] - this.points_[firstIndex + 2];` insert this code :
` // we don't want a duration of 0 (divide by zero)
  // we also make sure the user panned for at least one frame time (1/60s) to compute sane displacement values
  if (duration < 1000 / 60) {
    return false;
  }`

@ahocevar  Could you do the commit for me ?

**Comment by ahocevar** [comment]
Se #6902. Thanks @ogo-adp for the hard work isolating and fixing the issue.

**Comment by ogo-adp** [comment]
Thanks @ahocevar for commit the fix, and thanks also to @sorny for confirming the bug

**Comment by sorny** [comment]
Thanks for the fix @ogo-adp @ahocevar 
Currently testing the fix, will report back with results :)
