### ISSUE TITLE
Old tiles don't disappear when ALL new tiles fail in OpenLayers 4.1.1

### ISSUE THREAD

**Issue by cmdelatorre** [openlayers/openlayers#6866]
This issue I asked in SO: https://stackoverflow.com/questions/44289210/old-tiles-dont-disappear-when-all-new-tiles-fail-in-openlayers-4-1-1

I add it here because I think it may be a bug with `useInterimTilesOnError`.
I expect that `useInterimTilesOnError: false` then if all the tiles fail with 404, the Tile layer should be erased. Currently, the last loaded tiles just remain there.

**Comment by ahocevar** [comment]
Can you provide a CodePen that shows the issue?

**Comment by cmdelatorre** [comment]
I'm sorry, but I can't right now because the tiles server is not public. Also, there's some non-trivial logic around it: a progress bar, a transition (or buffer) layer, etc. It'll take some time to prepare something to show. I'll try to do it soon.

**Comment by oterral** [comment]
Could be related to https://github.com/openlayers/openlayers/issues/5269 @cmdelatorre did you try the last version? 

If there is still a problem try to set also the `cacheSize` property to 0 , [see doc](http://openlayers.org/en/master/apidoc/ol.source.TileImage.html)

**Comment by cmdelatorre** [comment]
Thanks for the comments @oterral . If with _last version_ you mean what's in the master branch, then no: I've only installed the latest release. So good point, I will try _master_.
I didn't try `cacheSize` to 0. I can do that. I'm just afraid the user experience may be affeceted.

So, thanks for the comments!

**Comment by cmdelatorre** [comment]
This issue is fixed in OL 4.2
