### ISSUE TITLE
A question about the map drag range .

### ISSUE THREAD

**Issue by wangbingqian110** [openlayers/openlayers#6869]
I got a map with the following code:
` var map = new ol.Map({`
        `target: 'map',`
        `layers: [`
         ` new ol.layer.Tile({`
           ` source: new ol.source.OSM()`
          `})`
       ` ],`
       ` view: new ol.View({`
         ` center: ol.proj.fromLonLat([37.41, 8.82]),`
          `zoom: 4`
        `})`
     ` });`
I would like to limit the drag range of this map,just like [Google Maps](http://www.google.cn/maps).What should I do?

**Comment by cs09g** [comment]
You can set `extent` to the [view](http://openlayers.org/en/latest/apidoc/ol.View.html)

**Comment by wangbingqian110** [comment]
@cs09g I used your method and set the view as follows:
`view: new ol.View({`
       `center: [2035059.44078, 2152466.71621],`
       `zoom: 4,`
       `extent: [-20037508, -20037508, 20037508, 20037508],`
       `})`
The results are shown in Fig：
![image](https://cloud.githubusercontent.com/assets/22422711/26676517/a8751930-46fa-11e7-85c6-451211ec32f9.png)
This is not the result I want.How can i set it up like this:
![image](https://cloud.githubusercontent.com/assets/22422711/26676598/ea9b069e-46fa-11e7-927e-6172c6741593.png)

**Comment by cs09g** [comment]
`extent` constraints center of the map. As far as I know, there's no way to limit draggable range up to the map size(extent).

**Comment by wangbingqian110** [comment]
@cs09g Okey,thank you very much for your answer.I have just found a new method：Bind a 'pointerdrag' event to the map,calculate the new extent when the map is dragged.The code is as follows:
   ```
map.on('pointerdrag', function () {
var differenceTop = 20037508 - (map.getView().getResolution()) * (map.getSize()[1] / 2);
    var differenceBottom = 20037508 - (map.getView().getResolution()) * (map.getSize()[1] / 2);
    var differentLeft = 20037508 - (map.getView().getResolution()) * (map.getSize()[0] / 2);
    var differentRight = 20037508 - (map.getView().getResolution()) * (map.getSize()[0] / 2);
    var zoom = map.getView().getZoom();
    var center = map.getView().getCenter();
    theView = new ol.View({
        projection: projection,
        maxZoom: 20,
        minZoom: 3,
        center: center,
        zoom: zoom,
        extent: [0 - differentLeft, 0 - differenceBottom, differentRight, differenceTop],
    });
    map.setView(theView);
});
```
