### ISSUE TITLE
Layer of first level can not be loaded

### ISSUE THREAD

**Issue by fishScola** [openlayers/openlayers#6873]
When add two layers to a map at first time, one of them can not load the first level data.It was very strange
 to me! I wrote an example on jsfiddle: [https://jsfiddle.net/fishScola/Ls7cgps8/](https://jsfiddle.net/fishScola/Ls7cgps8/)

Please help me, thanks!

**Comment by ahocevar** [comment]
This is not a bug in OpenLayers. You are configuring `minResolution` and `maxResolution` on your tile layer. The `maxResolution` threshold is exclusive, so you need to set a slightly higher `maxResolution`, e.g.:
```js
maxResolution: resolutions[0] + 1e-10
```

**Comment by jacobking** [comment]
WHY？@ahocevar
