### ISSUE TITLE
Touch select event missunderstanding

### ISSUE THREAD

**Issue by JanBojko** [openlayers/openlayers#6877]
I have spent a lot of time with issue in the webview on Galaxy Tab S2. I was not able to use either _ol.interaction.Select_ _singleclick_ or _click_ event, it doesn't matter if _hitTolerance_ has been used or not. It took several touches on a tablet screen to finally select a feature, it was quite tricky. We tried to debug it in the native android app and it worked only in cases when ACTION DOWN, ACTION MOVE and ACTION UP within the tablet had exactly same coordinates. Simply there is always slight dragging, when a user tries to do only click/touch. 
After tests with _map.on("click"_ click we have realized, that it has the same corrupted behavior as the previous one and more catching _pointermove_ was impossible because of an entire map slowness..

```
            //Don't work
            map.on("click", function (evt) {
                app.showMessage(evt.coordinate[0]);
            });
```
Finally we tried below code and it works as a charm... We can build the selection upon this code:
```
            map.getViewport().addEventListener('click', function (evt) {
                map.getEventCoordinate(evt);
                //Pick a feature from particular layer etc.
            });
```
The question is why it is happening as so, that there is the difference between _map.on_ and _map.getViewPort().addEvent_ Has somebody the same issue ?

Openlayers 4.1.1 has been used.

**Comment by fredj** [comment]
see #6776
