### ISSUE TITLE
AppendCoordinate to Linestring within Multilinestring does not work

### ISSUE THREAD

**Issue by Skuriles** [openlayers/openlayers#6878]
I use a multilinestring with several linestrings (0 to n).
I'm searching for an improvement to add dynamically data to the last linestring or append a new linestring.
This is all working so far.

-> Problem is I have to use MultiLineString.getCoordinates, then add coordinate and then do MultiLineString.setCoordinate. For me this seems a little bit "oversized" to just add one coordinate to the last linestring. 

So I created a plunkr:
http://plnkr.co/edit/YveaufbC4zyZpVD4yL5g?p=preview

In this plunkr I take the last linestring and use LineString.AppenCoordinate(coord), but the MultiLineString seems not to be affected by this way. 

-> For our project it could be, that we have 10.000+ coords and  there is at least 1 new coord every second added to the multilinestring. So I'm a little bit worried to use "SetCoordinates" every time instead of simply appending coordinates to the last linestring.

Is this just a missing feature or are there any reasons to prevent appendcoordinate working in multilinestring?

**Comment by ahocevar** [comment]
Coordinates are stored as flat array on the geometry. Every time you call `getCoordinates()` on the geometry, you get a fresh array that represents the geometry. To append a coordinate with the least overhead, you should be doing something like this:
```js
// execute these two lines only once:
var geometry = layer.getSource().getFeatures()[0].getGeometry();
var coordinates = geometry.getCoordinates();

// execute these two lines every time you append to the first line string:
coordinates[0].push(ol.proj.fromLonLat([lon, lat]));
geometry.setCoordinates(coordinates);
```

**Comment by Skuriles** [comment]
This is what I'm doing right now... thought that this is not the best solution as the coordinates are fully replaced everytime. 
Thanks for clarification!
