### ISSUE TITLE
missing 'move' event for map 

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#6880]
How to trigger event while the map is moving? 
I tried `pointerdrag` for dragging map event but it doesn't assure map is dragged.
it's just for mouse pointer's dragging(drag about 1px):
![dragging](https://user-images.githubusercontent.com/7428017/26909324-f188f584-4c3a-11e7-9ce3-357463070038.gif)

with PC, it's hard to do just 1px dragging but in mobile device, when you just touch the map, it could recognize as 1px drag.

**Comment by ahocevar** [comment]
I think #6890 should help here.

**Comment by cs09g** [comment]
@ahocevar once the PR merged, i will test that event.
