### ISSUE TITLE
Problem with reprojection of ol.source.ImageStatic

### ISSUE THREAD

**Issue by Shekenix** [openlayers/openlayers#6882]
Hello, i have problem with changing image projection.
Problem occured when i changed projection from default to tmerc, then Chrome browser crashed after page loaded (15-20 seconds) - mobile - android 5 and lower. Here is the link of my test template:

https://radar-opadow.pl/test.php

Regards

**Comment by ahocevar** [comment]
I don't see any problem on the page you linked. Can you provide a CodePen to play with, and describe the steps necessary to reproduce the issue?

**Comment by Shekenix** [comment]
Yes.
Generaly i dont' think that You will see the error in child window, but i created also CodePen for You codepen.io/Sheken/pen/xrZdrW. To reproduce the issue i recorded screen on Galaxy Tab3. Here is the video. http://radar-opadow.pl/projerror.mp4. Page crashed after 2 minutes.

**Comment by Shekenix** [comment]
I think that i found the bug in Library.
The problem is with the following function.

`/**
 * @private
 */
ol.reproj.Image.prototype.reproject_ = function() {
  var sourceState = this.sourceImage_.getState();
  if (sourceState == ol.ImageState.LOADED) {
    var width = ol.extent.getWidth(this.targetExtent_) / this.targetResolution_;
    var height =
        ol.extent.getHeight(this.targetExtent_) / this.targetResolution_;

    this.canvas_ = ol.reproj.render(width, height, this.sourcePixelRatio_,
        this.sourceImage_.getResolution(), this.maxSourceExtent_,
        this.targetResolution_, this.targetExtent_, this.triangulation_, [{
          extent: this.sourceImage_.getExtent(),
          image: this.sourceImage_.getImage()
        }], 0);
  }
  this.state = sourceState;
  this.changed();
  alert('reproject');
};`

On mobile devices it sems like infinity loop. Test my page one more time and look. You can't close alert.

**Comment by ahocevar** [comment]
Looks like complex reprojection operations overwhelm your mobile device. Try to play with the `reprojectionErrorThreshold` configuration option of your `ol.source.OSM`. The default is 0.5. Set it to 1, 2 or even bigger.

To lower the impact on browser memory, you can also configure your `ol.source.OSM` with a smaller `cacheSize`. The default is 2048, so try 1024 - one cache is created for both the data projection and the view projection.

**Comment by ahocevar** [comment]
Oh, and you have indeed identified a bug @Shekenix.

@petrsloup, can you please take a look? The bug can also be reproduced with the `reprojection-image.html` example. `ol.reproj.Image.prototype.reproject_` is called with every render frame as soon as the `ol.source.Image` is loaded.
