### ISSUE TITLE
Suggestions for small improvements to ol.proj

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers#6885]
1. simplify handling of sphere radii. `ol.proj.Units` and `ol.proj.EPSG4326` are currently using `ol.sphere` objects to get a radius. This means importing a file which creates a sphere object for a particular radius and then using the radius of that object. This seems an over-complicated way of defining a constant to me, and I would suggest just defining the radius in `ol.proj.Units` and `ol.proj.EPSG4326`, removing the dependency on `ol.sphere`. If these constants were widely used in the library, you could store them in one place, perhaps in a `SPHERERADIUS` enum, but they're not.
2. consistent use of projection code/object in params:
    * docs say apps don't need to use `Projection` objects, as `ProjectionLike` can be used in all options instead. But this is not true of `getPointResolution`, so I'd suggest changing this. Strictly speaking, I suppose this is an api change, but it shouldn't break anything.
    * `proj.transforms` is keyed on projection code, which is also used by `get()`, but `add()` and `remove()` use a Projection object. This is not api, so won't affect any apps, but it seems unnecessarily confusing to me, and I would suggest changing `add`/`remove` to use code as well.

**Comment by ahocevar** [comment]
+1 on everything except the last item (use projection code for adding/removing transforms). Are you able to provide a pull request?

**Comment by fredj** [comment]
`ol.control.MousePosition` and `ol.Geolocation` could also accept `ol.ProjectionLike`, see #6892

**Comment by probins** [comment]
@ahocevar what don't you like about the last item? (not a major issue, just interested)

**Comment by ahocevar** [comment]
@probins: Not that it adds much overhead, but do not use `ol.proj.get` much internally.

**Comment by probins** [comment]
I'll close this, as most of the issues now fixed
