### ISSUE TITLE
When setting global is true, point feature is also repeated.

### ISSUE THREAD

**Issue by wangbingqian110** [openlayers/openlayers#6896]
When I set the global is true,the map can be repeated,but the point on the map repeated too,I want the points on the map do not repeat.How can I do it?
![qq 20170609170950](https://user-images.githubusercontent.com/22422711/26968987-b40b93ae-4d36-11e7-99ef-cfc022b9961a.png)

```

var iconFeature = new ol.Feature({
                        geometry: new ol.geom.Point([longitude,latitude]),
                    });
DataSource.addFeature(iconFeature);
```

**Comment by bartvde** [comment]
Use ```wrapX: false``` on the vector source

**Comment by wangbingqian110** [comment]
Thank you very much! I solved the problem with the method you provided.
I still have a problem:I designed a function that pops up a message box after I click on the point.When the point is close to the map boundary,part of the message box is outside the map,is there a way to make the message box all inside the map?

![qq 20170609173030](https://user-images.githubusercontent.com/22422711/26969754-6eb347e0-4d39-11e7-8475-a00ea06a5966.png)
![qq 20170609173054](https://user-images.githubusercontent.com/22422711/26969753-6ead47f0-4d39-11e7-9219-fbca8d11191b.png)

I used overLay to display the message box.

**Comment by bartvde** [comment]
if you are using ````ol.Overlay```, try setting autoPan to true

**Comment by wangbingqian110** [comment]
I tried setting autoPan to true,and I found that only when position is not within the current map extent will take effect,but the position of the overlay already within the extent of the map,Is there any other solution?

**Comment by bartvde** [comment]
Original issue resolved with ```wrapX```
