### ISSUE TITLE
Scaling canvas with text with 125% DPI since v4.x

### ISSUE THREAD

**Issue by phrei** [openlayers/openlayers#6915]
I've created two identical fiddles with different OpenLayers-Versions:

[OpenLayers v3.18.0](https://jsfiddle.net/NoRyb/L8wqk8gx/) and [OpenLayers 4.1.1](https://jsfiddle.net/NoRyb/332tqhgk/)

The objective is to export a PNG in high resolution. I didn't include the actual exporting of the file. It is explained [here](https://www.kreidefossilien.de/webgis/dokumentation/beispiele/export-als-png-hoehere-aufloesung) if interested.

It all worked fine up to the newer version (I think until a 4.x version). 

If you have the DPI-Setting in windows on 100%, both fiddles do the same - but if you change your DPI-Setting to 125%, the latter fiddle does not update the text *Some text!* and it becomes really small and is located in the wrong place.

The map stays like that, until I click into it (or I call `map.updateSize()`). So I thought, I add `map.updateSize()` at the end of `precompose` - but no matter where I do it, the exported image is wrong as the `updateSize()` seems to be async and happening *AFTER* postcompose.

I didn't find a breaking change regarding this issue. Am I overlooking something or is it a bug? Any suggestion for a workaround?

**Comment by ahocevar** [comment]
Changing the canvas size in `precompose` is not a supported operation. If you want a higher resolution map for printing, you should proceed like in the http://openlayers.org/en/latest/examples/export-pdf.html example, by using `ol.Map#setSize`.

**Comment by phrei** [comment]
@ahocevar I did not know about this. Thank you. However: If in that example I only change the resolution (not the format), I get different images (and both zoomed out from the original position).

I would like to see the same image but with higher resolution (so that I'm able to zoom into the resulting image in an image viewer without becoming blurry).

**Comment by ahocevar** [comment]
In that case, you'll need to create a new map for printing, which you configure with a higher `pixelRatio`, e.g. 2.  The map can get the same `layers` and `view` assigned as your original map.

**Comment by phrei** [comment]
Okay that works like a charm! Thank you.
