### ISSUE TITLE
Improve docs for projection properties not in proj4js

### ISSUE THREAD

**Issue by probins** [openlayers/openlayers#6919]
`extent`, `worldExtent`, `global`, `getPointResolution` are in the OL-supplied projection objects, but not in those supplied by proj4js. They can be set on a projection object, but the current docs aren't very helpful in explaining where/when these are used (or what happens if they're not present). `worldExtent`, `extent`, and `global` are, for example, used by Graticule, but the Graticule docs don't mention this.

**Comment by bill-chadwick** [comment]
Would be worth mentioning that setGetPointResolution should be used to return resolution unchanged for projections like 27700 (and UTM) which have essentially constant scale (equal sized pixels) over their extent.
