### ISSUE TITLE
Error installing Openlayers 4.2.0 with node

### ISSUE THREAD

**Issue by derekwatling** [openlayers/openlayers#6921]
I am running Windows 10 and use Node to download OpenLayers and make a custom build. While trying to download 4.0.2 I recieved the error below.

I can't find C:\npm-debug.log to include.

![ol4 2 0-install-error](https://user-images.githubusercontent.com/2980145/27079978-4016dbf0-503a-11e7-949f-2885c9b5dd91.gif)

**Comment by fredj** [comment]
This is because you're using node 4.x and `tasks/build-ext.js` is in ECMAScript 6:
`"use strict";` should be added at the top of this file.

**Comment by derekwatling** [comment]
Thank you. I have upgraded to node 6.11.0 and this step is now working.
