### ISSUE TITLE
Problem with custom build of OpenLayers 4.2.0

### ISSUE THREAD

**Issue by derekwatling** [openlayers/openlayers#6924]
I am working on Windows 10. I have been working with OpenLayers 3 since 3.14 and creating a custom build for our site. Today I saw v4.2.0 was available but have experienced a few issues in attempting to create my custom build:

1.  "npm install openlayers" gave "SyntaxErrorror: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode".
After posting a question regarding this I upgraded to node 6.11.0 and sucessfully installed OL4.2.0.

2. When I tried to build: "Error: missing `server' JVM at `C:\Program Files (x86)\Java\jre1.8.0_131\bin\server\jvm.dll'"
A bit more reserch and I created a "server" subdirectory under "bin" and copied the contents of the "client" directory (including jvm.dll) into it.

3. Now I am getting numerous "WARNING - Bad type annotation." for types that I am not using or knowingly including in the build. I am attaching the full output as a .txt file and the build configuration json file (renamed to end in .txt so I can upload it here). My build command is:
C:\node_modules\openlayers>node tasks/build.js C:\node_modules\ol-custom.json C:\node_modules\ol4.js

[build-output.txt](https://github.com/openlayers/openlayers/files/1071718/build-output.txt)
[ol-custom.json.txt](https://github.com/openlayers/openlayers/files/1071728/ol-custom.json.txt)

Any help with this would be greatly appreciated.

**Comment by fredj** [comment]
for 3. rty to add [all these](https://github.com/openlayers/openlayers/blob/master/config/ol.json#L5-L16) in your ol-custom.json file

**Comment by derekwatling** [comment]
Thank you for the quick response. However I am not using any of that functionality and have sucessfully manged to build many previous versions. The last was v4.0.1.

**Comment by derekwatling** [comment]
I added the extra compile.externs into the build configuration json and it is working.
