### ISSUE TITLE
Simple Map freezes browser (based on Zoomify)

### ISSUE THREAD

**Issue by hajjimurad** [openlayers/openlayers#6925]
The following simple code makes my browser crazy, it freezes immediately.
CPU and RAM usage is growing.

    const imWidth = 31871;       
    const imHeight = 17770;

    const imWidthSmall = 19122.6;   
    const imHeightSmall = 10662;  

    const koef = imWidth / imWidthSmall;

    var map = new ol.Map({
    layers: [
        new ol.layer.Tile({   
        source: new ol.source.Zoomify({
            size: [imWidth, imHeight],
            url: "http://207.154.205.4/testers_numbers_borders_resized_zoomify_256/primary/"
        })
        })
    ],    
    target: 'map',
    view: new ol.View({
        center: [imWidth / 2, imHeight / 2],
        zoom: 0
    })
    });

The sample can be found here, [https://jsfiddle.net/dqrvmwtv/2/](url) , but you won't be able to open it, because it'll freeze your browser.

Checked on versions **4.0.0, 4.1.1**

**PS:** this sample is created from this one http://jsfiddle.net/sk5cLj4n/41/, but all the projections were removed.

**Comment by ahocevar** [comment]
Take a look at the [Zoomify exmaple](https://openlayers.org/en/latest/examples/zoomify.html). You will need to configure the view with an appropriate set of resolutions. The default EPSG:3857 resolutions are way off when your coordinate system is pixel based. The minimal code for your example would be:
```js
const imHeight = 17770;
const imWidth = 31871;

const zoomify = new ol.source.Zoomify({
  size: [imWidth, imHeight],
  url: "http://207.154.205.4/testers_numbers_borders_resized_zoomify_256/primary/"
});

var map = new ol.Map({
  layers: [
    new ol.layer.Tile({
      source: zoomify
    })
  ],
  target: 'map',
  view: new ol.View({
    resolutions: zoomify.getTileGrid().getResolutions(),
    center: [imWidth / 2, imHeight / 2],
    zoom: 0
  })
});
```
