### ISSUE TITLE
`projectionLike` not an instanceof `_ol_proj_Projection_` in ol/webpack

### ISSUE THREAD

**Issue by sunny-g** [openlayers/openlayers#6926]
I'm using the `ol` package with webpack and I periodically run into this issue where `ol.proj.get` returns `null`, even when given the Map's default projection object.

In this particular case, I'm creating a layergroup of `XYZ` sources and am not specifying the `projection` of the source, as the docs say it defaults to `'EPSG:3857'`. Any tips on where I can go from here?
<img width="469" alt="screen shot 2017-06-13 at 9 25 37 pm" src="https://user-images.githubusercontent.com/2055636/27115424-743199c6-507f-11e7-97d8-37c8b9c2b63e.png">
<img width="449" alt="screen shot 2017-06-13 at 9 25 52 pm" src="https://user-images.githubusercontent.com/2055636/27115425-745b7106-507f-11e7-910d-a54d920f252e.png">

**Comment by ahocevar** [comment]
Are you using the latest version? This problem should have been fixed with #6643.

**Comment by sunny-g** [comment]
@ahocevar I am using 4.2.0. I also forgot to mention that the resulting error is:
```js
tilegrid.js:149 Uncaught TypeError: Cannot read property 'getExtent' of null
    at Object._ol_tilegrid_.extentFromProjection (tilegrid.js:149)
    at Object._ol_tilegrid_.wrapX (tilegrid.js:35)
    at _ol_source_XYZ_._ol_source_Tile_.getTileCoordForTileUrlFunction (tile.js:287)
    at _ol_source_XYZ_._ol_source_TileImage_.createTile_ (tileimage.js:214)
    at _ol_source_XYZ_._ol_source_TileImage_.getTileInternal (tileimage.js:294)
    at _ol_source_XYZ_._ol_source_TileImage_.getTile (tileimage.js:239)
    at _ol_renderer_canvas_TileLayer_.prepareFrame (tilelayer.js:144)
    at _ol_renderer_canvas_Map_.renderFrame (map.js:161)
    at _ol_Map_.renderFrame_ (map.js:1250)
    at _ol_Map_.<anonymous> (map.js:179)
```

Is there any other information I can provide?

**Comment by ahocevar** [comment]
Are you also using proj4js in your application?

**Comment by sunny-g** [comment]
@ahocevar yes I am, for certain UTM projections. Do I need to set additional EPSG:3857 and 4326 as proj4 defs or something?

**Comment by sunny-g** [comment]
Seems to be an issue with my using a `ol` twice in two different projects - once within a local npm package Im working on, and once within an application that uses the former local npm package. Solution was to (in the application's `webpack.config.js`) to set a `resolve.alias` for `ol` pointing to the application's installed `ol`. Thanks for your help @ahocevar !

**Comment by keithamoss** [comment]
Sorry to bump an old question folks.

@sunny-g I'm having the exact same issue you had:

- A local npm project and an application both using `ol`
- The application throwing the `Cannot read property 'getExtent' of null` error where the local npm project creates the map and layers, but where the `source` objects come from the `ol` imported by the application.

I've tried adding an alias to webpack as you suggested, but it hasn't resolved the error for me. In my application's `webpack.config.js` I have:

```json
resolve: {
        alias: {
            ol: path.resolve(__dirname, "node_modules/ol/"),
        },
    },
```

In case you meant the opposite, I also tried pointing it at my local npm package's version of `ol`.

Any tips? :)

Webpack 3.11.0
ol 4.6.5

**Comment by timkeane** [comment]
i am having this issue as well when using a library that uses ol in another project that also uses ol.

ol.format.TopoJSON gets null from ol.proj.get for featureProjection when reading features even though it is getting passed along ESPG:3857 from the view

works fine in the library project

ol 4.6.5 
webpack 4.10.2

**Comment by keithamoss** [comment]
I didn't end up solving the issue - but I did work around it by making OpenLayers only a dev dependency of the other library (which we had forked for other reasons anyway). This way only the main application is installing OpenLayers, and the other library uses that install of OpenLayers when it's included.

Would still love to find a less hacky solution though.

**Comment by timkeane** [comment]
thanks for the reply... did you try the other way around by any change?
have the library proj have a full dependency and the app proj have the dev
dependency?

**Comment by keithamoss** [comment]
No, but I'd expect a similar result?

I ultimately ended up down a nightmarish Webpack hole. Having a fresh look now I've found this thread:

https://github.com/webpack/webpack/issues/4160

There's a range of simple "This solution worked for me" replies in there for making `resolve.alias` work that would be worth trying.
