### ISSUE TITLE
proj4 errors when zooming in on reprojection example

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#6927]
Go to: http://openlayers.org/en/latest/examples/reprojection.html?q=reprojection

Zoom in.

```

proj4.js:1 Uncaught TypeError: Cannot read property 'x' of null
    at D (proj4.js:1)
    at tc (proj4.js:3)
    at H (proj4.js:1)
    at I (proj4.js:1)
    at inverse (proj4.js:1)
    at ol.js:33
    at Sb (ol.js:32)
    at Av (ol.js:701)
    at new hw (ol.js:739)
    at zw.k.Nc (ol.js:751)
D @ proj4.js:1
tc @ proj4.js:3
H @ proj4.js:1
I @ proj4.js:1
inverse @ proj4.js:1
(anonymous) @ ol.js:33
Sb @ ol.js:32
Av @ ol.js:701
hw @ ol.js:739
k.Nc @ ol.js:751
Vv.sd @ ol.js:721
hi.Jg @ ol.js:174
k.Sp @ ol.js:293
(anonymous) @ ol.js:279
```

**Comment by fredj** [comment]
it works with proj4js v2.3.15

see also #6722

**Comment by ahocevar** [comment]
`ol.reproj.calculateSourceResolution` calculates the source resolution for the center of the source tile. That center may be outside the validity extent of the target projection, and newer proj4.js versions fail on such coordinates.

**Comment by ahocevar** [comment]
I'm working on a pull request to fix this.

**Comment by bartvde** [comment]
thanks @ahocevar

**Comment by PacoDu** [comment]
There is the same issue in OL 6

See: https://openlayers.org/en/latest/examples/reprojection.html?q=reproject and set view projection to EPSG:3413
