### ISSUE TITLE
ol.Collection.clear() taking ages to run.

### ISSUE THREAD

**Issue by benclarkeRGS** [openlayers/openlayers#6929]
I create my Modify Interaction like below:

```
    session.ModifyFeatures = new ol.Collection();

    session.Modify = new ol.interaction.Modify({
        features: session.ModifyFeatures,
        deleteCondition: function (event) {
            return ol.events.condition.never(event);
        }
    });

    session.Map.addInteraction(session.Modify);

```

Then as you can see from the code above, the Modify interaction has been created and added to the Map. 

I have tried adding 10000 features to `session.ModifyFeatures` and this roughly takes around 2 seconds, which is ok for the amount of features that I am adding. 

The problem arises when you call `session.ModifyFeatures.clear()` as this takes around 40 seconds to execute.

I was wondering if there a better way to clear a `ol.Collection` that wont take as long?

**Comment by craigsnyders** [comment]
Could you just remove the existing interaction and create a new one?
