### ISSUE TITLE
low performance when add a graticule overlay to map and zoom-in to big scale

### ISSUE THREAD

**Issue by kevanTai** [openlayers/openlayers#6932]
as title, for 4.2.0 version, when add a graticule(line) overlay to map and zoom in to big scale, it have low performance if drag map.

**Comment by kevanTai** [comment]
as graticule example --> https://openlayers.org/en/latest/examples/graticule.html
when zoom in to big scale, then to move map, the map  move very lag.

but test on openlayers 2 version, same with the case (show graticule labels on map and zoom in to big scale then move map), it not have lag issue

for Ol2 graticule example -->  http://dev.openlayers.org/examples/graticule.html

**Comment by JackD83** [comment]
Its caused by the line dash. Remove it and its fast again. Same happens on all dashed lines and large zoom factors

**Comment by kevanTai** [comment]
Great~!!! 👍 

I just tested it (remove  line dash), it can fast to draw when zoom-in to big scale and move map.

Very thanks, JackD83 and bartvde ....  : )
