### ISSUE TITLE
Memory hunger and high CPU usage, eventually Aw, Snap out of memory

### ISSUE THREAD

**Issue by simon998yang** [openlayers/openlayers#6940]
Hi,

I'm doing a simple testing after I experienced out of memory issue in my project. Here is my testing code(just replaced 'url' to '????' as the server url is bit sensitive)
Just open the page, not doing anything else. In chrome task manager, I see the CPU is constantly high(go up down 15%-35%), and the memory usage spikes from time to time (from 400M to 1GB, 2GB,3GB), and could eventually reach 'Snap, out of memory'.  Please help ...

```
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.2.0/css/ol.css" type="text/css">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="https://openlayers.org/en/v4.2.0/build/ol.js" type="text/javascript"></script>
    <title>OpenLayers example</title>
  </head>
  <body>
    <h2>My Map</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
      var paras = {'LAYERS': '4,0,65,61','VERSION': '1.1.1','FORMAT': 'image/png'};
      var projection = new ol.proj.Projection ({'code': 'EPSG:4326'});
              
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Image({
            source: new ol.source.ImageWMS({'url':'????','params':paras, 'projection':projection})
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([130.9769230478005, -12.487059768379256]),
          zoom: 10
        })
      });
    </script>
  </body>
</html>
```

**Comment by ahocevar** [comment]
Your map view is in a different projection than your layer source. This means OpenLayers will reproject all images it receives from your WMS. You could either display your map in EPSG:4326 by configuring your view with `projection: projection` and setting the center directly (without `ol.proj.fromLonLat`), or you could try if your WMS supports Web Mercator (usually EPSG:3857) by looking at its GetCapabilities response. Then you'd have to omit the `projection` config option on the ImageWMS source.

**Comment by simon998yang** [comment]
Thanks! Your instruction helped to resolve the problem.
