### ISSUE TITLE
Any examples of a layer renderOrderFunction? How is it supposed to work?

### ISSUE THREAD

**Issue by ralphstodomingo** [openlayers/openlayers#6941]
I made something like this:
```
export function layerRenderOrderFunction(featureA, featureB) {
  return featureA.get('zIndex') - featureB.get('zIndex');
}
```
where zIndex is a positive float. I can say that this attribute is never undefined, so why does this not work?

**Comment by ralphstodomingo** [comment]
Closing this since I solved it by using the `zIndex` property in the style object. I didn't see any documentation of it though, except for a single page where there was an example of `ol.style.Style` and it was really easy to miss.

**Comment by cs09g** [comment]
`ol.style.Style`  has [getZIndex](http://openlayers.org/en/latest/apidoc/ol.style.Style.html#getZIndex) method

**Comment by ralphstodomingo** [comment]
Thanks, I really missed it! I have to say it's not where you'd look firsthand if you want to order features around, though.

**Comment by cs09g** [comment]
right, it takes some time to be familiar with OL structures
