### ISSUE TITLE
Feature request: overzoom' for MVT layers in renderMode: image

### ISSUE THREAD

**Issue by craigsnyders** [openlayers/openlayers#6942]
It would be great to support underzoom and overzoom (see https://github.com/mapbox/vector-tiles/issues/21) when using an ol.source.VectorTile in `renderMode: 'image'`.

Example use case:
Create an MVT dataset with zoom levels 5 - 10.
When on zoom 11+, OL should 'reuse' the z10 vector data.
When on zoom 0-4, OL should use the lowest zoom level available: z5.

Current behaviour: tiles get very pixellated as OL scales the **image** tile for higher zoom levels.
![image](https://user-images.githubusercontent.com/3810017/27323463-90275df4-5599-11e7-89e7-57b504dc6fce.png)

Expected behaviour: data remains sharp, whilst still utilising **image** tiles for speed.
![image](https://user-images.githubusercontent.com/3810017/27323546-d14d67d8-5599-11e7-83fd-56d694abdc0d.png)

Note: over/under-zoom effectively works in `renderMode: 'vector'`.

**Comment by ahocevar** [comment]
Implemented in v4.2.0, without the need to specify an additional option. See #6779.

**Comment by craigsnyders** [comment]
So perfect, thank you!
