### ISSUE TITLE
GML2 read wfs1.0.0 wrong coordinate order

### ISSUE THREAD

**Issue by MkkOF** [openlayers/openlayers#6944]
i use ol.format.gml2 to read features got from wfs1.0.0 (eari arcgis server ),debug and found that coordiante in each feature is (latitude,longitude), but in browser ,gml data in response looks like (longitude, latitude), what‘s the reason?

var vectorSource = new ol.source.Vector({
        projection: 'EPSG:4326',
        loader: function (extent, resolution, projection) {
            var extent_ = ol.proj.transformExtent(extent, 'EPSG:3857', 'EPSG:4326');
            var url = serviceUrl +"&outputFormat=GML2" +"&bbox=" + extent_.join(',') ;
            console.log("url:" + url);
            $.ajax({
                async: false,
                url: url,
                dataType:"xml",
                success: function (response) {
                    if (response.error) {
                        alert(response.error.message + '\n' + response.error.details.join('\n'));
                    } else {
                        console.log(response);
                        var features = gmlFormat.readFeatures(response, {
                            featureProjection: 'EPSG:4326',
                            dataProjection: 'EPSG:4326'
                        });
                        if (features.length > 0) {
                            vectorSource.addFeatures(features);
                        }
                    }
                }
            });
        },
        strategy: ol.loadingstrategy.bbox
    });

**Comment by MkkOF** [comment]
ol.format.GML2.prototype.readFlatCoordinates_ = function(node, objectStack) {
  var s = ol.xml.getAllTextContent(node, false).replace(/^\s*|\s*$/g, '');
  var context = /** @type {ol.XmlNodeStackItem} */ (objectStack[0]);
  var containerSrs = context['srsName'];
  var axisOrientation = 'enu';
  if (containerSrs) {
    var proj = ol.proj.get(containerSrs);
    if (proj) {
      axisOrientation = proj.getAxisOrientation();
    }
  }
  var coordsGroups = s.trim().split(/\s+/);
  var x, y, z;
  var flatCoordinates = [];
  for (var i = 0, ii = coordsGroups.length; i < ii; i++) {
    var coords = coordsGroups[i].split(/,+/);
    x = parseFloat(coords[0]);
    y = parseFloat(coords[1]);
    z = (coords.length === 3) ? parseFloat(coords[2]) : 0;
    if (axisOrientation.substr(0, 2) === 'en') {
      flatCoordinates.push(x, y, z);
    } else {
      flatCoordinates.push(y, x, z);
    }
  }
  return flatCoordinates;
};

epsg:4326 is neu!!!

**Comment by bartvde** [comment]
it is neu according to the EPSG database

you will need to override the axis order, code sample I've used before:

```
// override the axis orientation for WMS GetFeatureInfo
var proj = new ol.proj.Projection({
  code: 'http://www.opengis.net/gml/srs/epsg.xml#4326',
  axis: 'enu'
});
ol.proj.addEquivalentProjections([ol.proj.get('EPSG:4326'), proj]);
```

**Comment by bartvde** [comment]
make sure the code matches what is in your GML as the SRS

**Comment by MkkOF** [comment]
@bartvde  thanks, i'will have a try!

**Comment by bartvde** [comment]
did you get it to work @MkkOF ?

**Comment by MkkOF** [comment]
@bartvde  actually,no. i'm not quite sure whether i have done in right way:
it looks like that: 
before create vectorSource
 add the code 
  var proj = new ol.proj.Projection({
        code: 'http://www.opengis.net/gml/srs/epsg.xml#4326',
        axis: 'enu'
    });
    ol.proj.addEquivalentProjections([ol.proj.get('EPSG:4326'), proj]);
am i wrong?

**Comment by bartvde** [comment]
what is the srsName in your GML file? Can you post a snippet?

**Comment by MkkOF** [comment]
@bartvde  i just understand your idea, it's works! thanks again!
