### ISSUE TITLE
Is it possible to load FDO xml format to ol3 ?

### ISSUE THREAD

**Issue by AlenKelemen** [openlayers/openlayers#6947]
Please advice me is it possible to load FDO xml (see example1) format to ol3 ?
[example1.txt](https://github.com/openlayers/openlayers/files/1094731/example1.txt)

**Comment by AlenKelemen** [comment]
FDO xml example:

`<?xml version="1.0" encoding="utf-8"?>
<FeatureSet>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://fdo.osgeo.org/schemas/feature/TempSchema" xmlns:fdo="http://fdo.osgeo.org/schemas" xmlns:gml="http://www.opengis.net/gml" xmlns:TempSchema="http://fdo.osgeo.org/schemas/feature/TempSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
<xs:element name="Havarija" type="TempSchema:HavarijaType" abstract="false" substitutionGroup="gml:_Feature">
<xs:key name="HavarijaKey">
<xs:selector xpath=".//Havarija"/>
<xs:field xpath="FeatId"/>
</xs:key>
</xs:element>
<xs:complexType name="HavarijaType" abstract="false" fdo:geometryName="Geom">
<xs:annotation>
<xs:documentation></xs:documentation>
</xs:annotation>
<xs:complexContent>
<xs:extension base="gml:AbstractFeatureType">
<xs:sequence>
<xs:element name="FeatId" fdo:readOnly="true" fdo:autogenerated="true">
<xs:simpleType>
<xs:restriction base="xs:int"/>
</xs:simpleType>
</xs:element>
<xs:element name="Geom" type="gml:AbstractGeometryType" fdo:hasMeasure="false" fdo:hasElevation="false" fdo:srsName="Default" fdo:geometricTypes="point " fdo:geometryTypes="point multipoint "/>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
</xs:schema>
<Features>
<Feature>
<Property>
<Name>FeatId</Name>
<Value>8</Value>
</Property>
<Property>
<Name>Geom</Name>
<Value>POINT (694215.41080978001 5026758.0898206998)</Value>
</Property>
</Feature>
</Features>
</FeatureSet>`

**Comment by AlenKelemen** [comment]
I assume nobody had any experience with this. I 'll manage in some other way, thanks.

**Comment by RenoSun** [comment]
I think you can simply convert xml into json/geojson through writing/using JavaScript.

Then, load the the geojson by using OL3.

Something like this maybe?
https://github.com/abdmob/x2js

**Comment by AlenKelemen** [comment]
Of course you are right. It seems that solution is to write xml to json parser with curve geometries converter on client side. Thank you RenoSun.
