### ISSUE TITLE
Is it possible to work in offline with openlayers?

### ISSUE THREAD

**Issue by DipakRai** [openlayers/openlayers#6951]
I am trying to build an offline GIS based web application. But found no clue with openlayers API docs of how to go ahead with it.
Any help as to how to go about it would be of great help.

**Comment by ahocevar** [comment]
OpenLayers works well in offline environments. It's your application's responsibility to provide offline capabillities, using standard browser techniques. For offline storage of tiles, you'll want to use a custom `tileLoadFunction` for the sources of your `ol.layer.Tile` or `ol.layer.VectorTile` layers. And for vector layers, you won't configure the sources with a `url`, but with `features`.
