### ISSUE TITLE
In KML, the ExtendedData without value are not correctly read

### ISSUE THREAD

**Issue by rmichaelis** [openlayers/openlayers#6959]
KML having a "Data" tag without "value" tag, uses the previous found data value as current value.

```
<ExtendedData>
<Data name="fid">
   <value>5127060</value>
</Data>
<Data name="image"/>
</ExtendedData>
```
The feature property  "image" will have "5127060" as value.

Here is a jsfiddle example :
https://jsfiddle.net/d45uksp2/

https://github.com/openlayers/openlayers/blob/master/src/ol/format/kml.js#L1094

**Comment by fredj** [comment]
@rmichaelis can you test if #6964 fixes your issue?
