### ISSUE TITLE
DeviceOrientation not absolute in Chrome 50+

### ISSUE THREAD

**Issue by nagytech** [openlayers/openlayers#6974]
Since Chrome 50, the `alpha` attribute on `DeviceOrientationEvent` as raised from the `deviceorientation` DOM event has been supplied as a value relative to that of the initial `alpha` value.   This is indicated by the `absolute` property containing a value of `false`.  As a result, using  `ol.DeviceOrientation` to rotate the map view leads to inconsistent results.

This behaviour is similar to that of Safari on iOS, which OpenLayers has already accounted for through normalizing `alpha` into the `getHeading` method.  However, while the solution on iOS is to utilize the `webkitCompassHeading` propery of the event,  Chrome provides no such interface. 
 
Since Chrome 50, the `deviceorientationabsolute` event has been implemented (_see, DeviceOrientation Event Specification sec 4.2_) in order to assure the caller that the `alpha` property will contain an absolute value.

Note that while the W3C spec is still in draft, and MDN [has issued a caution](https://developer.mozilla.org/en-US/docs/Web/API/Window/ondeviceorientationabsolute) that the feature is non-standard, there is currently no other convenient way to obtain the device's absolute `alpha`.  Additionally, it is possible that different devices will report different values according to their orientation (ie. portrait vs landscape).  I have attempted to resolve possible inaccuracies across devices by applying an offset using `gamma` constrained to intervals of PI/2.  So far, this works for me on my S8 with Chrome 59 but will require further testing.  As a result, I have provided configuration values for utilizing the `deviceorientationabsolute` event, as well as that for calculating the offset via `gamma`.

I will issue a pull request shortly to address this issue. If anyone can assist with testing on other devices, it would be appreciated.

**Comment by fredj** [comment]
We will deprecate `ol.DeviceOrientation`, see #7189
