### ISSUE TITLE
Add tileClass to TileWMS TileImage.call as it is in WMTS TitleImage.call

### ISSUE THREAD

**Issue by ZachTRice** [openlayers/openlayers#6978]
Currently WMTS' TitleImage.call contains [titleClass](https://github.com/openlayers/openlayers/blob/master/src/ol/source/wmts.js#L163)
This should be added to the TileWMS' TitleImage.call [here](https://github.com/openlayers/openlayers/blob/v4.2.0/src/ol/source/tilewms.js#L42)

I have an PR ready, having tested using layers in NASA Worldview.

**Comment by ahocevar** [comment]
Please send a pull request. Don't forget to add the option in `externs/olx.js` both for the typedef and as type.

**Comment by fredj** [comment]
fixed with #6980
