### ISSUE TITLE
the Camera doesn't work

### ISSUE THREAD

**Issue by KillDragon** [openlayers/openlayers#6979]
I set the camera， but id doesn't work

**Comment by bartvde** [comment]
can you give more details?

**Comment by KillDragon** [comment]
var camera=ol3d.getCesiumScene().camera;
camera.setView({
destination:Cesium.Cartesian3.formDegrees(89,38,500),
orientation:{
heading:1.0,
pitch:0,
roll:0.5
}
});

**Comment by bartvde** [comment]
this is ```openlayers``` issue tracker not ```ol-cesium```

**Comment by KillDragon** [comment]
How do I fix it
