### ISSUE TITLE
How to draw a sector？

### ISSUE THREAD

**Issue by 298029lkk** [openlayers/openlayers#6985]
Can use ol.style.RegularShape ?

**Comment by 298029lkk** [comment]
The regularShape do not support sectors.
I want a shape like
![sector](https://user-images.githubusercontent.com/25260495/27940877-0b766aea-6300-11e7-9f2a-70d987fce63e.jpg)
any advice?

**Comment by ch08532** [comment]
Look at turf.js. It has a sector feature that will generate a geojson feature object containing a polygon. You can load it using ol.format.geojson:readFeature method. This will create an ol.feature which you can use.

**Comment by craigsnyders** [comment]
In the past I've done this using `ol.interaction.Draw` with interactionType `Circle`and a heavily customised `geometryFunction`.

In the geometryFunction, you can draw a regular shape pretty close to a circle e.g. 128 sided polygon. Then use some maths and take the first n points from that polygon to be your _arc_. Then simply append your center point coordinate and you'll have your _sector_.

I managed to get my interaction to draw shapes like this:
![image](https://user-images.githubusercontent.com/3810017/28997566-d0669d90-7a0f-11e7-9698-0b77206b06e2.png)
Each _sector_ is a separate polygon.  Clicking a _sector_ would change it's background colour.

**Comment by savasturk** [comment]
> In the past I've done this using `ol.interaction.Draw` with interactionType `Circle`and a heavily customised `geometryFunction`.
> 
> In the geometryFunction, you can draw a regular shape pretty close to a circle e.g. 128 sided polygon. Then use some maths and take the first n points from that polygon to be your _arc_. Then simply append your center point coordinate and you'll have your _sector_.
> 
> I managed to get my interaction to draw shapes like this:
> ![image](https://user-images.githubusercontent.com/3810017/28997566-d0669d90-7a0f-11e7-9698-0b77206b06e2.png)
> Each _sector_ is a separate polygon. Clicking a _sector_ would change it's background colour.

Could you share the resource for this drawing, please?

**Comment by nobodyguy** [comment]
You can use [Turf.js](https://turfjs.org/docs/#sector) together with OpenLayer's ability to [parse GeoJSON](https://openlayers.org/en/latest/examples/turf.html) into standard features to achieve this.
