### ISSUE TITLE
Animated SVG Icon only updates when dragging the map.

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#6989]
I'm using an animated svg icon in `ol.style.Icon`, but the animation only advances while the map is being interacted with. If I add the following it works, but it seems pretty hacky.

``` js
setInterval(() => map.render(), 0);
```

**Comment by mprins** [comment]
Icon is drawn as part of the canvas, so itmakes Sense  to have to animate the map to redraw the canvas

**Comment by icholy** [comment]
Thing is, the animation advances one frame for each render. I'd expect the animation to advance at a constant speed regardless of frame rate.
