### ISSUE TITLE
WFS Format does not correctly read 3D features with GML3

### ISSUE THREAD

**Issue by Sol1du2** [openlayers/openlayers#6990]
Hello :)

The `ol.format.WFS` is not correctly reading 3D features with GML3. Looking at the source code, the function `readFlatPosList_ `does check for the srsDimension but on the wrong node (at least according to what geoserver sends me for GML 3.1.1). There is a comment mentioning that the dimension attribute is from the 3.0.1 but the documentation mentions openlayers support 3.1.1, so I imagine this is a bug? It should be easy enough to fix it by looking for the attribute in the right node.

**Comment by bartvde** [comment]
Can you show your GML output?

cc @Jenselme

**Comment by Sol1du2** [comment]
Yes, of course. :)

Here's a sample, filtered for 2 Features, from geoserver v2.11.1 :

`<wfs:FeatureCollection xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:cite="http://www.opengeospatial.net/cite" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" numberOfFeatures="2" timeStamp="2017-07-07T08:46:51.885Z" xsi:schemaLocation="http://www.opengeospatial.net/cite http://192.168.99.100:8080/geoserver/wfs?service=WFS&version=1.1.0&request=DescribeFeatureType&typeName=cite%3Adl_3 http://www.opengis.net/wfs http://192.168.99.100:8080/geoserver/schemas/wfs/1.1.0/wfs.xsd">
<gml:featureMembers>
<cite:dl_3 gml:id="dl_3.1">
<cite:the_geom>
<gml:MultiLineString srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" srsDimension="3">
<gml:lineStringMember>
<gml:LineString>
<gml:posList>
4.47809212 51.92373181 43.80370511 4.47807517 51.92376401 43.68967084 4.47805822 51.92379621 43.83243658 4.47809178 51.92380297 43.70402609 4.47809568 51.92380375 43.65502487 4.47811264 51.92377155 43.72265914 4.47812959 51.92373935 43.7882934 4.47812532 51.92373849 43.82089473 4.47809212 51.92373181 43.80370511
</gml:posList>
</gml:LineString>
</gml:lineStringMember>
</gml:MultiLineString>
</cite:the_geom>
</cite:dl_3>
<cite:dl_3 gml:id="dl_3.2">
<cite:the_geom>
<gml:MultiLineString srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" srsDimension="3">
<gml:lineStringMember>
<gml:LineString>
<gml:posList>
4.47819033 51.92371185 43.70141855 4.47817379 51.9237439 43.75378441 4.47815726 51.92377596 43.69115027 4.47818807 51.92378204 43.67794078 4.4781925 51.92378291 43.62683941 4.47820903 51.92375085 43.70037356 4.47822557 51.92371879 43.7912077 4.47822251 51.92371819 43.78340864 4.47819033 51.92371185 43.70141855
</gml:posList>
</gml:LineString>
</gml:lineStringMember>
</gml:MultiLineString>
</cite:the_geom>
</cite:dl_3>
</gml:featureMembers>
</wfs:FeatureCollection>`

**Comment by Sol1du2** [comment]
So, my suggestion to fix this problem, based on what I understood from the code, is the following:

The methods defined in `ol.format.GML3.prototype.GEOMETRY_PARSERS_` are where the node with the srsDimension is located. So the following lines could be added to those methods:

var context = objectStack[0];
context['srsDimension'] = node.getAttribute('srsDimension');

Then on `ol.format.GML3.prototype.readFlatPosList_` the following line:

`var containerDimension = node.parentNode.getAttribute('srsDimension');`

should be changed to:

`var containerDimension = context['srsDimension'];`

**Comment by Sol1du2** [comment]
Hello.

I have applied a fix for this issue in my base code but since I did not receive the pull request flag I am not sure if I should submit it or not.

**Comment by kratosmat** [comment]
Hi all,
I have a similar problem, I have geoserver vector layer with 3 dimension (even if up to now it is 0) and when I try to get WFS in GML3 the coordinate are wrong.

If I have well understood you have fixed this issue, isn't it?

**Comment by Sol1du2** [comment]
Hello Kratosmat.

Yes, I have fixed it in a pull request and it was merged, so if you clone from the repository it should work for you.

**Comment by kratosmat** [comment]
Hi Joao,
Thanks a lot for the quick answer.
Could you give me the number of pull request? I cannot find it.

Do you know when the next release will go out? I'm not so expert to compile
and include it in my project based on boundless sdk.

Regards,
Matteo.

On 17 Sep 2017 19:55, "João Gouveia" <notifications@github.com> wrote:

Hello Kratosmat.

Yes, I have fixed it in a pull request and it was merged, so if you clone
from the repository it should work for you.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openlayers/openlayers/issues/6990#issuecomment-330065809>,
or mute the thread

**Comment by bartvde** [comment]
It's not yet in a release, should be in 4.4
we normally release every month

**Comment by Sol1du2** [comment]
The pull request is #7141 but it has been closed. I believe you can still reach it with the direct link in the number. But if you don't know how to build it's best to wait for the 4.4 like bartvde said. :)

**Comment by kratosmat** [comment]
Ok,
Thanks a lot,

Matteo.
