### ISSUE TITLE
WFS Format does not write srsDimension for transaction

### ISSUE THREAD

**Issue by Sol1du2** [openlayers/openlayers#6991]
Hello. :)

I noticed that, although the writeTransaction function receives hasZ, it does not add the srsDimension to the geometry node. This makes the transaction fail on geoserver. I was wondering if it would be possible to add the dimension to the node for the transaction to work.

**Comment by bartvde** [comment]
Do you want to create a pull request for this?

**Comment by Sol1du2** [comment]
Yes that would be great.

**Comment by Sol1du2** [comment]
I have made the necessary changes to add the srsDimension. Unfortunately these changes, make the unit tests on ol.format.GML3 to fail because the xml now has an extra attribute. 

I am not sure what is the right procedure here to create a pull request. Should I change the unit tests as well?

**Comment by bartvde** [comment]
Yes I think updating the unit test XML would make sense in this case

**Comment by Sol1du2** [comment]
Ok. I'll do that and submit the pull request :)
