### ISSUE TITLE
re-using vectortilesource does not currently work

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#6994]
Only one layer will get rendered, see this test project https://github.com/theduckylittle/ol-multilayer-vectortile-bug @theduckylittle

There are 2 code paths that currently block the rendering:

https://github.com/openlayers/openlayers/blob/4a0f97ac6ad4e11df16604913d7e770b91a406b9/src/ol/renderer/canvas/vectortilelayer.js#L115
https://github.com/openlayers/openlayers/blob/4a0f97ac6ad4e11df16604913d7e770b91a406b9/src/ol/renderer/canvas/vectortilelayer.js#L437

**Comment by bartvde** [comment]
So in renderTileImage, the layer revision is always 2, but for the second layer run the renderedTileRevision is already set to 2

```
green : 2 : -1
red : 2 : 2
```

**Comment by bartvde** [comment]
I assume this happens since the replayGroups are stored on the vector tile

**Comment by theduckylittle** [comment]
That has been my assumption since the *Tile* considers itself "rendered" it doesn't bother with subsequent redraws.
