### ISSUE TITLE
Geometry.Translate problems for Features created from Points where string parameters are used for longitude and latitude

### ISSUE THREAD

**Issue by aiasso** [openlayers/openlayers#7000]
Create a point feature using longitude and latitude parameters that are strings:

var longitude = "31.918201";
var latitude = "14.88172";
var pointFeature = new ol.Feature(new ol.geom.Point([longitude, latitude]));

if this Feature is placed into a Vector layer and the Feature is operated on during a drag-drop or other action where the Feature's Geometry is accessed and translated using the Translate() function, the Feature disappears.  The Feature does show up initially on the map in its layer, but any Translate() done on it causes it to disappear.  The issue is resolved if the longitude and latitude are cast to Floats in the constructor using the Javascript parseFloat() function:

var pointFeature = new ol.Feature(new ol.geom.Point([parseFloat(longitude), parseFloat(latitude)]));

this behavior was discovered while attempting to implement the drag-drop examples for dragging and repositioning a Feature.  Recommend that the behavior is to either cast the input parameters internally in the constructor to floats, or throw an exception if non-numeric javascript types are passed in.

To replicate, use the demonstration below and change the Feature Point created to initialize using the longitude and latitude variables defined above, rather than the hardcoded [0,0] parameters.  Attempt to drag the point Feature.

http://openlayers.org/en/latest/examples/custom-interactions.html?q=drag

**Comment by aiasso** [comment]
Also noted, if there are multiple Features in the Vector layer that are created from String parameters, and one of the Features is accessed and translated using Translate(), all of the Features disappear, which indicates that the problem may be on the redraw of the Vector layer for any Features that are created using javascript string parameters.

**Comment by ahocevar** [comment]
Please, as stated elsewhere, respect the data types shown in the API docs. You are not supposed to pass strings as coordinates.
