### ISSUE TITLE
webpack warning

### ISSUE THREAD

**Issue by SnuggleE** [openlayers/openlayers#7006]
I am working in a project using vue-cli,webpack.when I created a map with openlayers,there is a warning:

`[HMR] ./~/openlayers/dist/ol-debug.js
Critical dependencies:
74815:483-490 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/openlayers/dist/ol-debug.js 74815:483-490`
Though the map is showed normally，the problem is strange.
openlayers version:3.20
Any ideas?

**Comment by ahocevar** [comment]
Use the [ol](https://npmjs.com/package/ol) package instead of [openlayers](https://npmjs.com/package/openlayers). It will also give you much smaller build sizes.

**Comment by SnuggleE** [comment]
@ahocevar I see the method you mentioned above,but I need import all the objects I need manually .
 I have resolved the problem  by specify noParse in webpack config file.
Many thanks!

**Comment by kping** [comment]
I face the same problem , How to fix it ?
