### ISSUE TITLE
Style Circle disappears on water layers on zoom

### ISSUE THREAD

**Issue by BhuvanaSanthoshkumar** [openlayers/openlayers#7009]
I am drawing 3 circles in openlayers map using the following style code. On zoom the circles on sea region seem to  get disappeared. Attached is the screen shot. Please let me know if any further details is needed.

Note: 1 in 5 times, the circle looks proper on zoom out but the other 4 times the circle disappear in sea region.
![error](https://user-images.githubusercontent.com/10462041/28031376-b538b558-65c4-11e7-9b06-fa7a777c607e.PNG)

 var width=[3,2,1];
var radius =[33,88,110];
			for (var i = 0; i < radius.length; i++) {
				var markerSet = [];
				iconFeature = new ol.Feature({
					geometry:	new ol.geom.Point(ol.proj.transform([Number(locations[0].longitude), Number(locations[0].latitude)], 'EPSG:4326', 'EPSG:3857')), 
					name: locations[0].city,
					id: guid()
				});

				iconStyle = new ol.style.Style({
					image: new ol.style.Circle({
						
						radius: radius[i],
						stroke: new ol.style.Stroke({
							color: [169, 19, 19, 1],
							width: width[i]
						}),
					})
				});

**Comment by ahocevar** [comment]
Looks like sea polygons have a higher z-index than your circle style. Try to configure a high `zIndex for your `iconStyle`.

**Comment by BhuvanaSanthoshkumar** [comment]
Hello, Thanks for your reply. I tried zIndex but still no luck. :(

	iconStyle = new ol.style.Style({
					zIndex: 1000,
					image: new ol.style.Circle({
						radius: radius[i],
						stroke: new ol.style.Stroke({
							color: [169, 19, 19, 1],
							width: width[i]
						}),
					})
				});

**Comment by BhuvanaSanthoshkumar** [comment]
Instead of Style if i assign Zindex to ol.layer.Vector then the issue is fixed.
