### ISSUE TITLE
forEachFeatureAtPixel regression in Firefox

### ISSUE THREAD

**Issue by ThomasG77** [openlayers/openlayers#7010]
When I go to http://openlayers.org/en/latest/examples/kml.html on Firefox and hover, it returns multiple codes whereas it return only one code when using Chrome

Firefox screenshot (Version 54 64 bits, Ubuntu 16.04)
![selection_693](https://user-images.githubusercontent.com/642120/28032649-8814e34e-65ab-11e7-9730-42b5639aae45.png)

Chrome screenshot (Version 59.0.3071.115 64 bits, Ubuntu 16.04)
![selection_694](https://user-images.githubusercontent.com/642120/28032582-4b865732-65ab-11e7-977a-12e8a62c0204.png)

It related to `forEachFeatureAtPixel` function.

Can you reproduce?

In fact, going back to 3.0.0 e.g http://openlayers.org/en/v3.0.0/examples/kml.html, it never has worked for this sample on FF (PS: on Linux)

**Comment by cs09g** [comment]
on Windows, it's fine. need to check on Ubuntu.

**Comment by ThomasG77** [comment]
I've checked on Windows too and it works. It seems to be platform related.

**Comment by greggian** [comment]
I just tried to reproduce this on Ubuntu 16.04 in Firefox 54 (64-bit) and it appears to behave as expected for me. I get the same behavior in Chrome and Firefox of one item on hover.

Maybe some other variable, like screen density or touchscreen support?

**Comment by ThomasG77** [comment]
Thanks for your feedbacks @cs09g @greggian.
I will close as it seems specific to my computer more than only the platform.
I will take a look on screen density, dpi as it seems to be the only clues and reopen if I find out more
