### ISSUE TITLE
The information "y" on ol.source.tileDebug is not correct !

### ISSUE THREAD

**Issue by romanoledergerber** [openlayers/openlayers#7012]
The information "y" on the pseudo tile source => ol.source.tileDebug is not correct !

When you download this tile direct:
https://tile.openstreetmap.org/z/x/y.png you will see a different image !

The right tile is y - 1, then the image is correct.

**Comment by ahocevar** [comment]
`ol.source.TileDebug` shows the internal tile coordinates that OpenLayers uses. Actually to translate to the XYZ tiling scheme that OSM uses, the transformation is `-y - 1`.
