### ISSUE TITLE
'strict mode' commit not included in npm

### ISSUE THREAD

**Issue by christophmayrhofer** [openlayers/openlayers#7016]
I just wanted to install via npm i -s openlayers in a node 4 app. However, the latest commit with 'strict mode' in build-ext.js does not seem to be used. I still get the same error: 

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by ahocevar** [comment]
I just published v4.3.0-beta.2, which includes [that fix](https://github.com/openlayers/openlayers/commit/0982dc05511a1b331d7c39e8ac891b94d828e3f5).
