### ISSUE TITLE
A solid LineString does not drawn on certain angles

### ISSUE THREAD

**Issue by mimiqkz** [openlayers/openlayers#7019]
I have a moving solid line moving in different angles on the OSM. The line position is being updated every 4 seconds. It was drawn by using LineString, vectorContext and drawFeature(). 

It is so weird that at certain angles, the line disappear, but as soon you move the line to a different angle, it re-appear. 
This problem doesn't happen to a dotted line, only a solid line. Is this has to do something with the style of the line?

**Comment by ahocevar** [comment]
Hard to guess without seeing your code on a stripped down codepen.

**Comment by mimiqkz** [comment]
Hi, sorry
Here is a demo of the problem. You click on the circle, hold it to create a line. If you drag the line around, you can see that it's not drawn at some certain angle. I need to update the position of these features per tick.
https://jsfiddle.net/melody_ace/7re8g47h/38/

**Comment by mimiqkz** [comment]
Here is a demo with the dash line. The problem doesn't occur here. So is this because of the styling issue?
https://jsfiddle.net/melody_ace/yfh6510j/3/

**Comment by ahocevar** [comment]
Sorry, I cannot reproduce the issue. I tried in all the browsers I have on MacOS. Have you tried this on different devices? This sounds very much like a graphics card issue on a specific machine to me.

**Comment by cs09g** [comment]
Chrome on Windows
first one: I can't draw the line at all angles.
second one: disappears on some angles and maybe with that angles, it's blinking when it changes the position.
![dragging](https://user-images.githubusercontent.com/7428017/28517935-2d356ef2-70a1-11e7-8795-d95020d8fd5e.gif)
![dragging2](https://user-images.githubusercontent.com/7428017/28518005-632c511a-70a1-11e7-9e07-b20e75b1dee8.gif)
