### ISSUE TITLE
Poor Graticule Performance in Chrome

### ISSUE THREAD

**Issue by greggian** [openlayers/openlayers#7020]
I noticed when using the Graticule feature in Chrome, some intermediate zoom levels render very slowly relative to other zoom levels. Sometimes a zoom action will lock up for a number of seconds.

Steps to reproduce:
- Open http://openlayers.org/en/latest/examples/graticule.html in Chrome
- Zoom in about 5 zoom levels
- Notice that the animation gets slower as you continue to zoom in.
- If you continue to zoom in, it begins to render quicker again.

I was able to reproduce this in Chrome Version 59.0.3071.115 (Official Build) (64-bit) on Windows 7 and Ubuntu 16.04

**Comment by greggian** [comment]
I also tested this in Firefox and did not see significant lag when zooming in.

**Comment by greggian** [comment]
I noticed that if I remove the lineDash stroke style on the graticule, performance is much better. So this may be specific to Chrome and lineDash styling.

**Comment by greggian** [comment]
Another variable that seems to help is keeping the lineDash but using a lineCap other then the default of 'round'. Using square or mitre appears to perform better for me.

**Comment by greggian** [comment]
Profiling showed that it was the the actual context.stroke call that was taking all the time. This was odd to me because the zoom levels with the most lag were not the zoom levels with the most meridian and parallels.

I dug in a bit more to try and find out why there was lag only at a particular range of zoom levels. I put some debug statements in the ol.render.canvas.Immediate.moveToLineTo_ when it calls transform2D to transform the coordinates into pixel coordinates. Some of the values coming back look odd. Particularly the very small second y coordinate on each pxl.

```
mer (4) [528767.5812680495, 6061542.210183, 528767.5812680495, 6069185.913011513]
pxl (4) [297.5933333333378, 600.0000000000582, 297.5933333333378, 4.0745362639427185e-10]

mer (4) [534333.5558077132, 6061542.210183, 534333.5558077132, 6069185.913011513]
pxl (4) [734.5, 600.0000000000582, 734.5, 4.0745362639427185e-10]

mer (4) [539899.5303473768, 6061542.210183, 539899.5303473768, 6069185.913011513]
pxl (4) [1171.4066666666622, 600.0000000000582, 1171.4066666666622, 4.0745362639427185e-10]
```

Hoping this helps!

**Comment by ahocevar** [comment]
Does the situation improve when you use Math.round() on the pixel coordinates?

**Comment by greggian** [comment]
Unfortunately, that does not appear to help. Thanks for the suggestion.

**Comment by greggian** [comment]
It looks like it wasn't the meridians but the parallels that were problematic. Super wide parallels were being created and this seemingly causes issues in Chrome in some cases.
