### ISSUE TITLE
Render all feature geometries and style them separately

### ISSUE THREAD

**Issue by yaugenka** [openlayers/openlayers#7024]
A feature may have several geometries. The most common case is a combination of a shape geometry  with a label point. It would be nice to have a possibility to render all of them at a time and style each one separately.

**Comment by ahocevar** [comment]
You can. Let's say your feature has a default geometry (attribute name `'geometry'`), and a second geometry (attribute name `'geometry2'`). Then you can configure your layer with a style like this:
```js
style: [
  new ol.style.Style({
    // style for the default geometry
  }),
  new ol.style.Style({
    geometry: 'geometry2'
  })
]
```
See http://openlayers.org/en/latest/apidoc/ol.style.Style.html#setGeometry for more details.

**Comment by yaugenka** [comment]
Fantastic! Thank you, @ahocevar

**Comment by yaugenka** [comment]
@ahocevar, one question please. Is it possible to identify geometry type in a geometry collection to style them differently? E.g. I have a geometry collection with a polygon and a point geometries and would like to render feature name for the point geometry only.

**Comment by ahocevar** [comment]
Yes it's possible. Try `geometry.getType()`.

**Comment by yaugenka** [comment]
Ok. I have managed to achieve it by looping through geometries in a collection, checking their type and setting a specific geometry in an array of styles for a feature.
But it seems to be a pretty heavy piece of code for such a simple need. Aren't there some easier way to archive it? Probably some kind of geometry_type property in ol.style.Style would make the life easier.

Here is the fiddle I played with [https://jsfiddle.net/yaugenka/3qakq4mn/5/](url)

**Comment by ahocevar** [comment]
Define a style function! It gives you all the flexibility you need.

**Comment by ahocevar** [comment]
It's easier if you create styles by type, and just set the geometry for the respective style in the style function. See https://jsfiddle.net/3qakq4mn/7/:
```js
var text = new ol.style.Text({
  text: '',
  font: '30px sans-serif',
  fill: new ol.style.Fill({
    color: 'red'
  })
})
var styles = {
  'Polygon': new ol.style.Style({
    stroke: new ol.style.Stroke({
      color: 'red',
      width: 2
    })
  }),
  'Point': new ol.style.Style({
    image: new ol.style.Circle({
      radius: 5,
      fill: new ol.style.Fill({
        color: 'blue'
      })
    }),
    text: text
  })
};
var stylesArray = [];
function stylefunction(feature, resolution) {
  text.setText(feature.get('name'));
  var geoms = feature.getGeometry().getGeometries();
  var length = geoms.length;
  for (var i = 0; i < length; ++i) {
    var geom = geoms[i];
    var type = geom.getType();
    var style = styles[type];
    style.setGeometry(geom);
    stylesArray[i] = style;
  }
  stylesArray.length = length;
  return stylesArray;
};
```

**Comment by yaugenka** [comment]
Your solution looks neater than mine. Thank!

**Comment by MV88** [comment]
@ahocevar 
I have a similar case but i have the following problem.
for "Point" or "MultiPoint" i want to use two or three different style in order to render a marker, shadow etc.

that is different from your example where you are returning a single ol.Style.Style and not an array for each geom in the geom collection.

Should I use StyleGeometryFunction? But i don't know how.
