### ISSUE TITLE
Secondary geometry stops rendering if the main one goes off the screen

### ISSUE THREAD

**Issue by yaugenka** [openlayers/openlayers#7027]
I have a gml3 feature with 2 geomeries: polygon and point. As far as I see from the console the point is rendered as the default geometry. When I move the map so that the point is off the screen, the polygon geometry stops rendering. See this video [https://youtu.be/zePksKfUjWk](url)

The feature was rendered by my localhost geoserver, so I tried to put it into a fiddle for your convinience but could not make it read from a string. Anywasy here is the link to the fiddle [https://jsfiddle.net/yaugenka/sdLrmp48/19/](url)

And here is the gml3 feature itself
`<?xml version="1.0" encoding="UTF-8"?><wfs:FeatureCollection xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:wfs="http://www.opengis.net/wfs/2.0" xmlns:by="by" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" numberMatched="1" numberReturned="1" timeStamp="2017-07-17T19:42:26.981Z" xsi:schemaLocation="http://www.opengis.net/wfs/2.0 http://localhost:8080/geoserver/schemas/wfs/2.0/wfs.xsd by http://localhost:8080/geoserver/wfs?service=WFS&amp;version=2.0.0&amp;request=DescribeFeatureType&amp;typeName=by%3Acountry http://www.opengis.net/gml/3.2 http://localhost:8080/geoserver/schemas/gml/3.2.1/gml.xsd"><wfs:member><by:country gml:id="country.fid--2985128a_15d38844c10_3641"><by:id>59065</by:id><by:name>My Polygon</by:name><by:geom><gml:Polygon srsName="urn:ogc:def:crs:EPSG::4326" srsDimension="2"><gml:exterior><gml:LinearRing><gml:posList>47.353705 -89.831528 47.353705 89.831528 -47.353705 89.831528 -47.353705 -89.831528 47.353705 -89.831528</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></by:geom><by:label><gml:Point srsName="urn:ogc:def:crs:EPSG::4326" srsDimension="2"><gml:pos>26.00742 0</gml:pos></gml:Point></by:label></by:country></wfs:member></wfs:FeatureCollection>`

**Comment by ahocevar** [comment]
The GML format sets the `geometryName` of each feature whenever it parses a geometry, so in your case the label becomes the default geometry. The `geometryName` should be configurable when reading GML and WFS. We'd accept a pull request with a fix.

**Comment by yaugenka** [comment]
If I put the point geometry before the polygon one then it all works correctly. But probably that is because my point is within the polygon. At least this is a workarround.
