### ISSUE TITLE
Problem with Geolocation using Mozilla Firefox

### ISSUE THREAD

**Issue by rodoriigo** [openlayers/openlayers#7029]
Hi for all,

I'm beginner with OL and while I was studying I had a problem with geolocation with the Mozilla Firefox browser.
When I use geolocation with Google Chrome, it works correctly, however when I use it with Mozilla Firefox, I got the following errors (using either ol.js or ol-debug.js):

![ol_debug_js](https://user-images.githubusercontent.com/10956242/28295683-c1854050-6b38-11e7-87e4-fd79ed64573c.png)

![ol_js](https://user-images.githubusercontent.com/10956242/28295684-c188ba28-6b38-11e7-8659-d9e40120f144.png)

The JS code is:

```
$(document).ready(function() {

	var view = new ol.View({
		center: [-6217890.205764902, -1910870.6048274133],
		zoom: 4,
		maxZoom: 18,
		minZoom: 2
	});

	var baseLayer = new ol.layer.Tile({
		source: new ol.source.OSM()
	});

	var map = new ol.Map({
		target: 'mapa',
		controls: ol.control.defaults().extend([
			new ol.control.ScaleLine(),
			new ol.control.ZoomSlider()
		]),
		renderer: 'canvas',
		layers: [baseLayer],
		view: view
	});

	var geolocation = new ol.Geolocation({
            projection: view.getProjection(),
            tracking: true
        });

       $('#geolocation').click(function() {

           var position = geolocation.getPosition();

           var point = new ol.layer.Vector({
              source: new ol.source.Vector({
                  features: [new ol.Feature({
                      geometry: new ol.geom.Point(position)
                  })]
              })
           });

          map.addLayer(point);

          view.setCenter(position);
          view.setResolution(2.388657133911758);
          return false;
      });

});
```

I thank you in advance.

Best Regards,

**Comment by greggian** [comment]
Seems to be working in Firefox here for me. Did you "Allow Location Access" when prompted in Firefox?

**Comment by rodoriigo** [comment]
Hi greggian,
Yes, I did.
For some reason, when I rebooted my machine it starts to work.
Thank you so much.
