### ISSUE TITLE
Some locations in the map for India is not locateable

### ISSUE THREAD

**Issue by rajatagarwal2303** [openlayers/openlayers#7031]
Hi Concerned,

I am using the openlayer openstreet view API for my website but for some latitude & longitude the map does not show the name of the local near by areas. 

Can you please help me in order to do so.

For example : https://www.indiamart.com/kaushalenterprises/enquiry.html

**Comment by ahocevar** [comment]
This is not an OpenLayers issue, but an issue with the data you are using.
