### ISSUE TITLE
Is it possible to add text to point style using webgl renderer

### ISSUE THREAD

**Issue by bdbrandt** [openlayers/openlayers#7036]
I have a fairly complex mapping application which I am trying to switch from using the canvas renderer to using the webgl renderer. There is a layer of point features within the application that incorporates text within its styling. When I switch the map to using the webgl renderer I am getting the error "Uncaught TypeError: a.Db is not a function" when rendering that layer with the text included in the style, but if I remove the text the layer renders perfectly (albeit without text) using webgl. Does webgl not support rendering text in the feature style? If it does, could someone point me to an example of this in action?

Thanks for reading this.

**Comment by bdbrandt** [comment]
Just to add an example, here is the style which I am using for my point features (with text):

style = new ol.style.Style({
                image: new ol.style.Circle({
                    opacity: 1,
                    scale: 1,
                    radius: radius,
                    stroke: stroke,
                    fill: new ol.style.Fill({
                        color: [colorArr['r'],colorArr['g'],colorArr['b'],0.8]
                    }),
                    atlasManager: atlasManager
                }),
                text: new ol.style.Text({
                    scale: 1,
                    text: size.toString(),
                    fill: new ol.style.Fill({
                        color: '#fff'
                    }),
                    stroke: new ol.style.Stroke({
                        color: 'rgba(0, 0, 0, 0.6)',
                        width: 3
                    })
                })
            });

With radius, stroke, colorArr, and size being defined further up in the style function. When I remove the text portion of this style to make it the following it works with webgl, but does not as above.

style = new ol.style.Style({
                image: new ol.style.Circle({
                    opacity: 1,
                    scale: 1,
                    radius: radius,
                    stroke: stroke,
                    fill: new ol.style.Fill({
                        color: [colorArr['r'],colorArr['g'],colorArr['b'],0.8]
                    }),
                    atlasManager: atlasManager
                })
              });

**Comment by gberaudo** [comment]
Hi @bdbrandt, text support has been added recently by https://github.com/openlayers/openlayers/pull/6793, which is available in v4.3.0-beta.2. Which version of OpenLayers are you using?

**Comment by bdbrandt** [comment]
That's probably it. I'm using 4.2.0. I'll switch to 4.3.0-beta 2. Thank you!
