### ISSUE TITLE
map movestart event can not work

### ISSUE THREAD

**Issue by dyh333** [openlayers/openlayers#7037]
as the title, my part code is below. while the 'moveend' can show normally, but 'movestart' can not work. 
does anyone know why?  my ol vesrion is 4.1.1

`map.on('movestart', function(evt){
                console.log('222');
            });
map.on('moveend', function(evt){
			console.log('333');
		});
`

**Comment by cs09g** [comment]
`movestart` event is added on version 4.2.0. check [v4.2.0 change log](https://github.com/openlayers/openlayers/blob/master/changelog/v4.2.0.md)

**Comment by dyh333** [comment]
@cs09g  thanks. i will try
