### ISSUE TITLE
ol.3 vs ol.4 changed behavior "change:resolution" setting a dynamic extent

### ISSUE THREAD

**Issue by dogotaru** [openlayers/openlayers#7038]
Hello guys,

I have been using OL.3 in such a manner that on zooming in and out, map is setting another view with a different extent, so it will always be impossible to move the map past the boundaries of the set of tiles. Given the nature of extent, one extent for all zoom levels wouldn't allow it, hence this trick.

Zooming in or out .on("change:resolution") I am doing:
var view = new ol.View({options with different extents based on zoom level and auto calculated viewport size});
view.setCenter(view.constrainCenter(event.target.getCenter()))
view.setZoom(theNextZoomLevel)
view.setRotation(event.target.getRotation())
map.setView(view);

When zooming out the most and if all tiles of the zoom level fit inside the viewport, the extent is set to 0. In my case: extent=[0, -6700, 0, 6700]. That way you cannot horizontally move the map at all.
This is dynamic, because viewport size varies, on the same zoom level the tiles' set may or may not entirely fit.

If you zoom in from a level that has 0 as extent, horizontally for example, catch that with "change:resolution", the event.target.getCenter() will not give a correct position on the map (center of the target), but event.target.getCenter() will return something that inherits 0 horizontally from the extent set. In this case setCenter will be just set to 0 and not to the cursor position on the map.

In OL.3 this works as expected.

Please see the 2 identical jsfiddles, one with ol.3.13.1 and the other one with ol.4.2.0
Ol.4 https://jsfiddle.net/5y33jrq9/
OL.3 https://jsfiddle.net/qr6at9Lj/ 

Thank you for your great work

**Comment by ahocevar** [comment]
As far as I can tell, both fiddles behave exactly the same way. Also, I am failing to understand if or where exactly you are suspecting a bug in OpenLayers v4.2.0.

**Comment by dogotaru** [comment]
Hi,
well, try the following: as soon as the page finishes loading, don't interact with the map, except only double click on a rightmost zone on the map. In my case Madagascar does it as a good example of the behavior that I am signaling.
You'll surely notice that in ol3 the target (Madagascar) gets zoomed in, and in ol4 the center of the map is being the target, even if you double clicked on Madagascar.
You are absolutely right, in terms of code, both fiddles are the same, behavior is not though.
The same happens whatever zoom method you chose for zoom, not only double click, also mouse scroll and shift drag.
Appreciate your time checking this, thanks ahocevar

**Comment by ahocevar** [comment]
You were relying on a bug in OpenLayers 3, which was fixed with #6332. When the center is constrained to an extent with zero width, the west/east position is not supposed change upon zooming.

**Comment by dogotaru** [comment]
Still, I am changing the view and the second view is not restricted by the extent.
Also event.target.getCenter() does not return the target's geographic position at all (ol4 example returns [0, -1215043.0016211623]). What if the target position is actually needed? like in my case.
You really say the behavior is 100% normal?

**Comment by dogotaru** [comment]
Constraining the target is rather a job for view.constrainCenter() , not really something applied by default to any target, correct me if I'm wrong.

**Comment by ahocevar** [comment]
When you register a `change:resolution` listener on the first view, the center will be restricted by the extent of that view. And coordinates are always in view projection. So to get the geographic position of `[0, -1215043.0016211623]`, you have to use `ol.proj.toLonLat( [0, -1215043.0016211623])`.
