### ISSUE TITLE
Polyline stops rendering at certain resolution and extent

### ISSUE THREAD

**Issue by ashchurova** [openlayers/openlayers#7039]
I have created CodePen sample for this issue:

https://codepen.io/ashchurova/pen/rwXjzP

If you continue zoom in using current map center you will see the line will stop rendering at some point.

This particular line crosses meridian and it renders fine in world 0 but if you view it in world -1 or 1 it will not render properly certain resolution and extent. Please assist. Thank you.

**Comment by bjornharrtell** [comment]
Setting `wrapX` to `false` on the `ol.source.Vector` seems to resolve your issue.

**Comment by ashchurova** [comment]
Just tried this solution in my sample and it didn't work for me.

**Comment by bjornharrtell** [comment]
Are you sure? I modified your sample and it works - https://codepen.io/anon/pen/xLKKVP

**Comment by ashchurova** [comment]
I was setting it as source.wrapX=false; and that didn't make a difference. I see you set this property during initialization but that stops line to be rendered in the neighboring worlds and I don't think this is a desired behavior for us. I noticed initially this line was rendered fine in world 0. But we need wrapping enabled too.

**Comment by bjornharrtell** [comment]
Ok, I'm not certain but perhaps it can be considered a bug. I don't think there is an easy workaround.

**Comment by ahocevar** [comment]
This is not an OpenLayers bug. Depending on browser and platform, very long linestring segments can become a problem because of the coordinate range required to represent that segment in pixel space for rendering. A workaround is to modify the linestring beforehand to add more vertices for very long segments. You can e.g. use turf's `along` function to achieve this. See http://openlayers.org/en/latest/examples/turf.html for an example.

**Comment by ashchurova** [comment]
But this line renders fine in world 0. If there was a problem with long line segments it would not render properly in every case. Am I right to assume that?

**Comment by ahocevar** [comment]
It's really a matter of the coordinate range. With even longer line segments, the same can happen in "world 0", as you call it.

**Comment by ashchurova** [comment]
Alright, I will give turf a try, I am already using it in my project. Thanks.
