### ISSUE TITLE
lineDashOffset has no effect

### ISSUE THREAD

**Issue by gkresic** [openlayers/openlayers#7040]
Tested on `ol.style.Stroke`. LineDash works correctly, but offset is ignored.

See live example: https://codepen.io/gkresic/pen/gRVXgL

To test browser support (works on mine Chrome 60): https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineDashOffset

OpenLayers 4.2.0

**Comment by ahocevar** [comment]
`lineDashOffset` is not supported by the immediate renderer, which is used for rendering regular shapes. That functionality would have to be added to `ol.render.canvas.Immediate.prototype.setContextStrokeState_` in `src/ol/render/canvas/immediate.js`. We'd accept a pull request for that.

**Comment by fredj** [comment]
fixed with #7042
