### ISSUE TITLE
Uncaught TypeError: c.Y is not a function

### ISSUE THREAD

**Issue by emrekorkutor** [openlayers/openlayers#7043]
I'm using ol 4.2.0. I get this error regularly and I can not define a pattern. But mostly when I try to zoom out with mouse scroll. Is there any idea?

ol.js:617 Uncaught TypeError: c.Y is not a function
    at Mt (ol.js:617)
    at Ot.b (ol.js:624)
    at Array.forEach (<anonymous>)
    at Ot.sd (ol.js:625)
    at hi.Jg (ol.js:174)
    at G.k.Sp (ol.js:293)
    at G.<anonymous> (ol.js:279)

**Comment by ahocevar** [comment]
Please load `ol-debug.js` instead of `ol.js` to get a more meaningful stack trace. And also provide a stripped down example that exposes the issue you are seeing.

**Comment by fredj** [comment]
Closing due to lack of response
