### ISSUE TITLE
Canvas not defined or null reference IE issue

### ISSUE THREAD

**Issue by BhuvanaSanthoshkumar** [openlayers/openlayers#7046]
I have nearly 20k data to be drawn, so I am looping through each data to frame the icon feature(below is the code). In chrome it seem to be working fine but in IE, I get unable to get property of canvas in line iconStyle=new ol.style.Style Attached the screenshot as well.  Can I get help on this?

            var locations = data;
            var iconStyle, markerSet = [];

            for (var i = 0; i< locations.length; i++) {
               
                var iconFeature = new ol.Feature({
                    geometry: new ol.geom.Point(ol.proj.transform([Number(locations[i].longitude), Number(locations[i].latitude)], 'EPSG:4326', 'EPSG:3857')),
                    name: locations[i].city,
                    id: guid()
                });
            
                    **iconStyle = new ol.style.Style({**
                        image: new ol.style.Circle({
                            radius: 12,
                            fill: new ol.style.Fill({
                                color: [0, 82, 136, 1]
                            })
                        }),
                        text: new ol.style.Text({
                            font: '15px Roboto-Regular',
                            text: (i + 1) + '',
                            fill: new ol.style.Fill({
                                color: '#000'
                            })
                        })
                    });
                 
                 iconFeature.set('type', options.locationsType);
                 iconFeature.set('cords', [locations[i].latitude, locations[i].longitude]);
                  iconFeature.set('sites', locations[i].sites);

                iconFeature.set('category', locations[i].category);
                iconFeature.set('params', locations[i]);
                iconFeature.setStyle(iconStyle);
                markerSet.push(iconFeature);
            }

![image](https://user-images.githubusercontent.com/10462041/28566874-147efde4-714e-11e7-8779-91edf6464b3e.png)

**Comment by ahocevar** [comment]
You are probably using IE in some kind of compatibility mode. Make sure you have `<!DOCTYPE html>` as first line in your HTML, and also add `<meta http-equiv="X-UA-Compatible" content="IE=Edge">` to your HTML document's `<head>`.

**Comment by BhuvanaSanthoshkumar** [comment]
Its there on my header already. Please note if i use some 3000 data, website is rendering properly but when the data counts increases more than 5k then this kind of error comes in. Also some time when the feature loops runs I get  OUT OF MEMORY exception.
