### ISSUE TITLE
XHR errors (404s) break rendering for the whole map when using ol.layer.VectorTile

### ISSUE THREAD

**Issue by aberenyi** [openlayers/openlayers#7047]
This is a quite weird issue and I'm just guessing the root cause.

I'm trying to render a few layers from Mapbox using `ol.{layer,source}.VectorTile`. 
It works just fine if the layer's extent more-or-less covers the whole planet.

However, layers with smaller coverage (i.e. `layer.getExtent() !== ol.proj.get('EPSG:3857').getExtent()`) break the rendering *even for the base layer* after a few zoom interactions.

Pen [here](https://codepen.io/aberenyi/full/eEmRJW/) - try to zoom in on the blobs in Peru.

Cheers

**Comment by ahocevar** [comment]
This was fixed with #6972. See [updated pen](https://codepen.io/ahocevar/full/EvavQB) which uses OpenLayers v4.3.0-beta.2.
