### ISSUE TITLE
How to make overlay  repeated when setting global is true.

### ISSUE THREAD

**Issue by wangbingqian110** [openlayers/openlayers#7049]
Hi:
When I set the global is true,the map can be repeated.How to make overlay repeat too,just like set wrapX: true on the vector source.

**Comment by ahocevar** [comment]
That is not supported. You'd have to create a 2nd overlay with different coordinates. Consider using a vector layer instead of using an overlay.

**Comment by wangbingqian110** [comment]
@ahocevar thank you very much for your answer.
