### ISSUE TITLE
OSM layer for Map shows wrong boundaries of India with Pakistan

### ISSUE THREAD

**Issue by rajatagarwal23** [openlayers/openlayers#7055]
Dear Concerned,

There is a concern that the border for India with Pakistan is displayed wrong in Open layer map.

Please help us to rectify the same.

URL : https://www.indiamart.com/kaushalenterprises/enquiry.html
Steps to visit :
Step 1 : Open the above url.
Step 2 : Open the Map link in contact us section.

Please help how to correct it as it is wrong.

I am using Below is JS code to display Map

Call: https://openlayers.org/api/OpenLayers.js

map = new OpenLayers.Map("map");
var mapnik = new OpenLayers.Layer.OSM();
map.addLayer(mapnik);
var lonlat = new OpenLayers.LonLat(77.2294831,28.6518578).transform(
new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
new OpenLayers.Projection("EPSG:900913") // to Spherical Mercator
);
var zoom = 14;
var markers = new OpenLayers.Layer.Markers( "Markers" );
map.addLayer(markers);
markers.addMarker(new OpenLayers.Marker(lonlat));
map.setCenter(lonlat, zoom);

**Comment by bartvde** [comment]
stop opening up new issues when your issue gets closed, get in touch with openstreetmap instead
