### ISSUE TITLE
Exception when passing initial extent to ol.interaction.Extent

### ISSUE THREAD

**Issue by marcosox** [openlayers/openlayers#7057]
When creating a new `ol.interaction.Extent`, if an initial extent is passed in the options as the docs say, an exception is thrown:

    var extent = new ol.interaction.Extent({
        extent: rectangle.getGeometry().getExtent()
    });
    map.addInteraction(extent);

The error is:

    Uncaught TypeError: Cannot read property 'getSource' of undefined
    at ol.interaction.Extent.createOrUpdateExtentFeature_ (ol-debug.js:65290)
    at ol.interaction.Extent.setExtent (ol-debug.js:65349)
    at new ol.interaction.Extent (ol-debug.js:64992)

see the [JFiddle](https://jsfiddle.net/ewe7orzf/1/) for a demo (uncomment line 26 to see the error).

What I'm trying to do is to have the extent interaction overlap the existing rectangle. (I actually hide the rectangle, use the extent interaction as a modify tool, and update the rectangle geometry when the interaction is finished)

**Comment by ahocevar** [comment]
Thanks for the bug report. See #7059 for a fix.
