### ISSUE TITLE
I want to add a Marker for a particular position in openalyer map

### ISSUE THREAD

**Issue by rajatagarwal23** [openlayers/openlayers#7058]
Dear Concerned,

I want to add a marker for a particular position in the openlayer map which i am using. Please suggest me how to add such a marker because addlayer function is not working here.

Below is the code used : 

<!DOCTYPE html>
<html>
  <head>
    <title>XYZ Esri</title>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.2.0/css/ol.css" type="text/css">
    
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script src="https://openlayers.org/en/v4.2.0/build/ol.js"></script>
    <style>
    #map{ width:1000px; height:500px; }
    </style>
  </head>
  <body>
    <div id="map" class="map"></div>
    <script>
      var attribution = new ol.Attribution({
        html: 'Tiles © <a href="https://services.arcgisonline.com/ArcGIS/' +
            'rest/services/World_Topo_Map/MapServer">ArcGIS</a>'
      });

      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.XYZ({
              attributions: [attribution],
              url: 'https://server.arcgisonline.com/ArcGIS/rest/services/' +
                  'World_Topo_Map/MapServer/tile/{z}/{y}/{x}'
            })
          })
          
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([72.9798925,21.1682432]),
          zoom: 14
        })
      });
      

    </script>
  </body>
</html>

**Comment by bartvde** [comment]
please ask this type of usage questions on stackoverflow instead with the openlayers tag

https://stackoverflow.com/questions/tagged/openlayers
