### ISSUE TITLE
Text decorations support

### ISSUE THREAD

**Issue by yaugenka** [openlayers/openlayers#7071]
It would be nice to have a possibility to define such style.Text decorations as underline, overline and line-through, ideally with style.Stroke options for the line.

**Comment by ahocevar** [comment]
Currently not. But contributions are always welcome.

**Comment by aparzi** [comment]
@ahocevar it is possible draw a text with underline?

**Comment by aparzi** [comment]
@ahocevar okay thanks.
Is anyone already working on it?  otherwise I could see it if I can

**Comment by ahocevar** [comment]
@aparzi I don't think anyone is working on it. If you want to give it try, a pull request would be welcome.

**Comment by Rasm-P** [comment]
@aparzi Did you eventually have a go at creating a solution for this issue? Text decorations support would be a nice addition.

**Comment by aparzi** [comment]
Hi @Rasm-P,
I made some attempts but I could not implement it.  Can you give me some more information?  eg file to edit, if I can follow some previous commit, etc...

Thanks

**Comment by Rasm-P** [comment]
Hi @aparzi. I sadly don’t have the information on where to start. Maybe @ahocevar has? I was mostly looking to hear if there was any progress on the issue.

**Comment by aparzi** [comment]
In this moment no progress. but I might try again having more information from @ahocevar
