### ISSUE TITLE
More features in view, more stutters the draw circle move along with the cursor

### ISSUE THREAD

**Issue by xingchch** [openlayers/openlayers#7074]
http://jsfiddle.net/xccxcc/vkm2rg46/41/

There are 2 layers in a map , one you can add 50000 features   , another is a empty layer with draw interaction. 

More features in view, more stutters the draw circle move along with the cursor
and the FPS is droped a lot too.

**Comment by ahocevar** [comment]
Both layers in your fiddle use the `vectorSource`, so we are rendering 100000 features, not 50000. With `lalvector` changed to use `lalvectorSource`, responsiveness should be acceptable in zoom levels where you can distinguish features and do not just see a black map.

If you want to speed things up significantly, you can use an `ol.layer.Image` with an `ol.source.ImageVector` for the `vector` layer. See http://jsfiddle.net/vkm2rg46/42/ for an updated fiddle with the suggested changes made.

**Comment by xingchch** [comment]
thanks a lot , I made a  mistake and confused me a lot . tanks for help me found the bug.
