### ISSUE TITLE
ol.Overlay should autoPan when its size changes

### ISSUE THREAD

**Issue by LeoniePhiline** [openlayers/openlayers#7083]
Hi everybody,

I am using the currently latest OpenLayers v4.2.0 (and the ol3-popup.js plugin from https://github.com/walkermatt/ol3-popup).

On a map application, on click of a feature, I open a popup showing the feature's title (which can autoPan just fine). Then, I fetch more feature details via ajax and replace the popup's content with the HTML response, which makes the popup/Overlay get bigger while not changing its positions. 

Means, in the ajax response callback, I call:
 popup.show(sameCoordsAsBefore, newHtmlContentString);

Internally, ol.Overlay.Popup.prototype.show does call ol.Overlay.prototype.setPosition, which sets the ol.Overlay.Property_.POSITION property.
However, ol.Object.prototype.set checks for oldValue !== value and does not notify any event listeners if new and old position are equal.

This way, ol.Overlay.prototype.handlePositionChanged, which is a listener to the 'change:position' event, is never called, and ol.Overlay.prototype.panIntoView_ never invoked.

Given my small map viewport, the popup which has grown due to added content - after its first positioning - is never fully inside the viewport.

I propose introducing an event for changes of overlay size, and an ol.Overlay.prototype.handleSizeChanged event handler, which also invokes ol.Overlay.prototype.panIntoView_ if ol.Overlay.autoPan is true.

Generally: Panning might not only be necessary at an Overlay's position change, but also at its size change.

I believe that this should rather be part of the OpenLayers core, than of the popup plugin.

In any case, none of the relevant methods (be it handlePositionChanged or panIntoView_) are public. So without weird workarounds of adding a proxy method to ol.Overlay.prototype or ol.Overlay.Popup.prototype, which grants me access to protected (but not "legally" private!) methods like handleSizeChanged (to then call manually after changing the Overlay's content and thus changing its size).

Thank you for your awesome work on OpenLayers.

**Comment by ahocevar** [comment]
Why don't you just create a new Overlay? You can reuse the `element`.

**Comment by LeoniePhiline** [comment]
That would be a hack.
