### ISSUE TITLE
Scale line control does not adjust for latitude in EPSG:4326

### ISSUE THREAD

**Issue by wallw-bits** [openlayers/openlayers#7086]
Note the difference between the [example in EPSG:3857](http://openlayers.org/en/latest/examples/scale-line.html?q=scale+line), which appears to work because the scale is adjusted as you pan far north or south; and the [codepen in EPSG:4326](https://codepen.io/anon/pen/KvWzRK), which is incorrect because it always shows the scale relative to the equator even when the view is far north or south.

The EPSG:4326 projection implementation returns a constant for `getMetersPerUnit()` rather than adjusting it per the center coordinate's latitude. That may or may not be intentional from an API perspective, but the scale line should respond appropriately.

We were already overriding `ScaleLine.prototype.updateElement_` to add more unit support, so I replaced the original block that calculates `pointResolution` with the following:

```
var p1 = ol.proj.toLonLat(viewState.center, viewState.projection);
var p2 = viewState.center.slice();
p2[0] += viewState.resolution;
p2 = ol.proj.toLonLat(p2, viewState.projection);

var pointResolution = vincentyDistance(p1, p2);
```

That appears to work pretty well except that it could probably use some clamping in the event that the center is out of the projection's valid extent.

**Comment by ahocevar** [comment]
Thanks for reporting this @wallw-bits. See #7087 for a fix.

**Comment by wallw-bits** [comment]
No problem. Thanks for the quick fix!
