### ISSUE TITLE
Does OL3 work in Android 4.4 webview?

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#7089]
OL works nicely newer version of android webview but it doesn't in android 4.4 webview.
I've searched about android 4.4 webview then people said it has something wrong with meta name=viewport.

I used OL2 but that was working well though there's a android webview issues but OL3 doens't work well.
sometimes work, sometimes not. 

*polyfill added for requestAnimationFrame
*should use OL2 for android 4.4 webview?

**Comment by cs09g** [comment]
`<meta name="viewport" content="width=device-width,initial-scale=0.9" />` fixes map not appear problem on Android 4.4 webview. need test on other version of android webview. if that works, i'll close this.

**Comment by ahocevar** [comment]
If this is not an OpenLayers issue, then please close this ticket.

**Comment by cs09g** [comment]
it may happen on android webkit browser(< android 4.4). guess it's about effects on canvas size changing on that webview? 
anyway, need more research but we decided to use OL2 on that device. 
Thanks.
