### ISSUE TITLE
ol.ImageTile doesn't load() properly after errors

### ISSUE THREAD

**Issue by mattlovett** [openlayers/openlayers#7090]
We use a tile source that often fails, so our code includes a listener that calls load() on the tile to retry after an error.

We recently noticed that when we load a large map, if there are errors, then the same map image gets displayed in several places on the map. I think this is due to one of the recent changes in ol.ImageTile.

Here's what happens when a tile load error happens:
- ImageTime.handleImageError_() sets the image_ to point to a blank tile.
- Our code gets a callback telling us about the error, and we call load()
- The default loading function does "imageTile.getImage().src = src;"

This has just set a real source onto the 'blank' tile. Each time we get a load error we do the same thing, and all of the failing tiles end up sharing the same 'blank' image. I think a simple fix would be so set up a new image each time we attempt the load... but there may be something even easier.

**Comment by ahocevar** [comment]
This might be related to a few bugs we recently fixed. Can you please try the latest OpenLayers from master to see if the issue persists?

**Comment by mattlovett** [comment]
I've got a unit test that fails on master, and a code change for master that fixes it. Here's a patch that contains both... I can open up a PR if you prefer to accept the patch that way.
[tile-loading.txt](https://github.com/openlayers/openlayers/files/1210715/tile-loading.txt)

**Comment by mattlovett** [comment]
I've also created a codepen.. but I don't know if there is a CDN for the master version of OL3, so the codepen is using an older version. https://codepen.io/anon/pen/MvmeRE?editors=1111

**Comment by mattlovett** [comment]
Hello again.

I downloaded the above codepen, and edited index.html to load a local version of ol-debug.js, built from master. The behaviour on master is slightly different from latest - rather than repeat an incorrect tile, the map appears blank, so there are still bugs around re-trying to load() tiles.

Running the codepen with an ol-debug with master & the above patch fixes the issue.

Please let me know if you want me to open up a PR with the change.

Yours, Matt

**Comment by ahocevar** [comment]
I think a better fix would be your first suggestion: to set the blank image's data uri as src of a new image, instead of setting the blank image on error. Would you be able to create a pull request with that?

**Comment by mattlovett** [comment]
Sure, I've opened up a PR with a change along those lines.

**Comment by mattlovett** [comment]
@ahocevar 
Hello Andreas,

Thanks for working on that fix. That addresses the problem I reported... but I've been doing some more testing and I think I've hit another snag. If we have a map with many layers on it - perhaps base mapping and then imagery over the top - then if an imagery tile fails to load then we get a white square on the map, obscuring the base map.

I'm wondering if better error behaviour would be to add transparent tiles to the map, rather than white ones... but I haven't thought it through yet. I'd appreciate your opinion.

Yours, Matt

**Comment by mattlovett** [comment]
@ahocevar 

Please ignore my earlier comment - this fix looks good to me, and if I find any other issues I'll handle them separately.

Thanks for your fix!

Yours, Matt
