### ISSUE TITLE
Layer constructor options missing zIndex

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#7091]
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] If reporting a bug, I have tried with the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/)

Layer classes that inherit from `ol.layer.Layer` don't have `zIndex` documented even though it seems like they all inherit from `olx.layer.LayerOptions`.

**Comment by fredj** [comment]
The following typedefs are missing the zIndex documentation:
 * olx.layer.HeatmapOptions
 * olx.layer.ImageOptions
 * olx.layer.TileOptions
 * olx.layer.VectorOptions
 * olx.layer.VectorTileOptions

**Comment by icholy** [comment]
Looks like `map` is missing in `olx.layer.HeatmapOptions`
