### ISSUE TITLE
ol.source.ImageArcGISRest params.LAYERS is not work

### ISSUE THREAD

**Issue by dyh333** [openlayers/openlayers#7099]
- [ ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [* ] If reporting a bug, I have tried with the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/)
- [* ] If reporting a bug, I have created a [CodePen](https://codepen.io/dyh333/pen/brRbwv?editors=0010) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

I am trying to using ol.source.ImageArcGISRest to load a map layer, but I hope control the Visible of layers. 
for example, the [rest](https://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Specialty/ESRI_StateCityHighway_USA/MapServer) has three layers, and I want to only show the first layer. the ol document tells that set the 'LAYER' param to control, but it seems not work.
![image](https://user-images.githubusercontent.com/1221313/29159552-8eb9bb04-7de1-11e7-8386-bf5ac959dacb.png)

**Comment by bartvde** [comment]
can you show your issue in a codepen?

**Comment by filsterjisah** [comment]
try the following:
params: { LAYERS: 'show:0' },
