### ISSUE TITLE
ol.interaction.snap support for multiple layers

### ISSUE THREAD

**Issue by jakubbican** [openlayers/openlayers#7100]
We'd like to enable user to snap to any vector geometry in a map while drawing/editing new features.

Currently, we can add all current features to features collection of ol.interaction.snap. Or we can add one "virtual" layer/vector source and add all the features. In both cases, all features are duplicated and it is necessary to update the collection or source whenever map viewport is changed during draw action.

So we have a change request to extend the ol.interaction.snap so that more sources/layers can be added (or all visible vector features in a map can be used).

**Comment by am2222** [comment]
@jakubbican could you find any better solutions for this issue?

**Comment by jakubbican** [comment]
Not yet. We'll be trying some workarounds soon.

**Comment by TDesjardins** [comment]
Not tested and just an idea... what about adding multiple snap-interactions for every source you want to snap?

**Comment by iSpring** [comment]
> Not tested and just an idea... what about adding multiple snap-interactions for every source you want to snap?

Good idea ! Need to have a try.

**Comment by berkayoruc** [comment]
Is there any better solutions for multiple layers snapping?

**Comment by vojtech-osvald** [comment]
Here is what we finally do in our solution (with jakubbican):
```javascript
import { Vector as layerVector } from 'ol/layer';
import { Snap } from 'ol/interaction';

--------

let interactions = [];
this.map.getLayers().forEach((layer) => {
  if (layer instanceof layerVector) {
    let interaction = new Snap({
      source: layer.getSource()
    });
    interactions.push(interaction);
  }
});

for(let snap of interactions ) {
  this.map.addInteraction(snap);
}
```

Plus the interaction collection is saved in memory in order to be able to remove the interactions later.

**Comment by berkayoruc** [comment]
Thank you @vojtech-osvald

**Comment by seonglae** [comment]
> Here is what we finally do in our solution (with jakubbican):
> 
> ```js
> import { Vector as layerVector } from 'ol/layer';
> import { Snap } from 'ol/interaction';
> 
> --------
> 
> let interactions = [];
> this.map.getLayers().forEach((layer) => {
>   if (layer instanceof layerVector) {
>     let interaction = new Snap({
>       source: layer.getSource()
>     });
>     interactions.push(interaction);
>   }
> });
> 
> for(let snap of interactions ) {
>   this.map.addInteraction(snap);
> }
> ```
> 
> Plus the interaction collection is saved in memory in order to be able to remove the interactions later.

This solution only snaps with latest layer for me. Is there other solution?
