### ISSUE TITLE
HTTP/2 concurrent tile requests

### ISSUE THREAD

**Issue by freekvw** [openlayers/openlayers#7101]
This is not so much a bug as a potential for better performance when loading many tiles over HTTP/2 (let me know if another forum would be more appropriate).
What I would expect when switching to HTTP/2 for tile servers, is that when e.g. loading a full screen of tiles, all those tiles will be requested more-or-less simultaneously (using multiplexing over a single socket).  What I'm observing in practice with OpenLayers, using the epsg-4326 example that runs on an HTTP/2 server, is the following (see also screenshots at the bottom):
- In Firefox, 16 tiles are being loaded concurrently (hitting the OpenLayers [`maxTotalLoading` limit](../blob/master/src/ol/map.js#L977)).
- In Chrome, 6 tiles are being loaded concurrently, while another 10 are "Queueing".
- Surprisingly, when loading the HTTP/2 tiled-image example at [https://http2.golang.org/gophertiles?latency=30](https://http2.golang.org/gophertiles?latency=30), Chrome does load many more tiles concurrently.

I have been doing some testing in our own application, where I can get a decent speed-up in Firefox (around a factor 2 in my test case) when increasing `maxTotalLoading` from 16 to 128.  Unfortunately Chrome does not want to request more than 6 tiles concurrently, but I suspect it should be possible to get a decent speed-up there, too, if it would.

So the questions are:
- Would it make sense for OpenLayers to schedule more concurrent tile requests to HTTP/2 servers?
- Does anyone have a clue why Chrome chooses to queue OpenLayer's tile requests, and can we do anything about it?  I have been searching the internet for answers on this, but so far to no avail.

Firefox/OpenLayers:
![screenshot_20170810_112829](https://user-images.githubusercontent.com/394365/29164948-7b904b58-7dc1-11e7-9265-49dd5f30aab8.png)

Chrome/OpenLayers:
![screenshot_20170810_112659](https://user-images.githubusercontent.com/394365/29164917-65533904-7dc1-11e7-9726-d7d6d8436a5d.png)

Chrome/Gopher:
![screenshot_20170810_113818](https://user-images.githubusercontent.com/394365/29164956-80543c1c-7dc1-11e7-94e6-c2b793694bbb.png)

**Comment by tschaub** [comment]
Thanks for raising this issue @freekvw.  I created an example that demonstrates the slow loading: https://codepen.io/tschaub/pen/ZJaJOb

![gophertiles](https://user-images.githubusercontent.com/41094/29338409-1128a64a-81e3-11e7-92dd-a104f1d3c8ed.gif)

It will be good to see what we can do to improve this.

**Comment by fredj** [comment]
Recent version of Chrome are now loading more than 6 tiles concurrently, see:
https://http2.golang.org/gophertiles?latency=30

**Comment by freekvw** [comment]
Note that this issue specifically occurs in combination with OpenLayers.  Apparently scheduling in Chrome is done differently depending on how the tiles are loaded: directly as <image> elements on the screen vs. what OpenLayers does (off-screen/canvas rendering?).

**Comment by fredj** [comment]
@freekvw see https://codepen.io/fredj/full/aVBGNP/

In Chrome 62 linux, all the 16 tiles are being loaded concurrently.

**Comment by freekvw** [comment]
I see, that's great :-)

**Comment by meijer3** [comment]
I have a client that has slow, shared-resoucred citrix clients. Indeed is leaflet and Esri fast, and openlayers still slow.
sometimes 10fold. I narrowed it down to the HTTP2 request that the others make, and openlayers is still on 1.1.
Its a bit unclear for me of this threat was solved, or that chrome was just faster.

**Comment by tschaub** [comment]
@meijer3 can you share any more information about the setup?  Ideally, an example map.  If not that, what layer, source, browser, and version of OpenLayers?
