### ISSUE TITLE
SVG ol.style.Icon opacity not working in IE11/Edge.

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#7109]
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] If reporting a bug, I have tried with the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/)
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Setting the opacity in `ol.style.Icon` doesn't have any effect when using an SVG.

**Example:** https://codepen.io/anon/pen/oeegWJ

**Comment by ahocevar** [comment]
I just checked your codepen in all browsers I have available, and setting the opacity does have the expected effect on the icon. Can you describe steps to reproduce?

**Comment by icholy** [comment]
@ahocevar If I open that codepen (unmodified) in ie11 or edge the icon gets rendered with full opacity rather than `0.4` as specified in `ol.style.Icon`.

**Comment by ahocevar** [comment]
This appears to be a browser bug, that you can easily work around by drawing the SVG to a canvas first. See https://codepen.io/anon/pen/gxxbVM:
```js
var iconCanvas = document.createElement('CANVAS');
iconCanvas.width = iconCanvas.height = 64;
iconCanvas.getContext('2d').drawImage(icon, 0, 0);

// ...

var imgStyle = new ol.style.Icon({
  img: iconCanvas,
  imgSize: [64, 64],
  // ...
});
```

**Comment by icholy** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4774361/
