### ISSUE TITLE
False positive from forEachFeatureAtPixel and hasFeatureAtPixel on VectorTile layers at non-native resolutions

### ISSUE THREAD

**Issue by craigsnyders** [openlayers/openlayers#7112]
It appears as though `map.forEachFeatureAtPixel` and `map.hasFeatureAtPixel` are giving false positives for 'overzoomed' VectorTile layers. It is as though there's a large hitTolerance set, but I can confirm that this works as expected on normal Vector layers and also VectorTile layers where tiles are available for the current zoom level.

In the gif below I've got a `source.VectorTile` with tiles available in z5-z10 (orange polygons) and a source with VectorTiles available at the current zoom (blue polygons).

![openlayers hitbox](https://user-images.githubusercontent.com/3810017/29236007-c0fc1ed8-7efc-11e7-805a-721859ac53da.gif)

The 'orange polygons' `source.VectorTile` is configured with:
```
tileGrid: ol.tilegrid.createXYZ({
  minZoom: 5,
  maxZoom: 10
}),
```
The code I'm using to change the cursor:
```
map.on('pointermove', (e) => {
  let hit = map.hasFeatureAtPixel(e.pixel);
  map.getViewport()['style'].cursor = hit ? 'pointer' : '';
});
```

**Comment by ahocevar** [comment]
I created a fix. See #71120
