### ISSUE TITLE
WebGL line renderer producing artifacts

### ISSUE THREAD

**Issue by GaborFarkas** [openlayers/openlayers#7121]
Follow-up to #6953.

This is a tough problem, as it seems like the artifacts are bottom miters where the GPU projects the coordinate very far when it runs out of floating point precision. Currently, the quality of the lines (i.e. number of artifacts) depend on the video card of the client machine, as I do not have any artifacts using a similar setup to @tschaub:

![screenshot from 2017-08-14 13-42-00](https://user-images.githubusercontent.com/9150102/29270421-ffb3a492-80f6-11e7-998d-054190cd711b.png)

On the other hand, I have far less, much better, but similar artifacts when I try to render very detailed layers on small scale.

The tough part is, we cannot calculate a reference distance to make the renderer self-aware, as the reference distance will also suffer from the same floating point precision problem. For example, trying to calculate the angle bisection's length of the current triangle and comparing the miter's length to it seems futile.

My current idea is setting a threshold to the bottom miter, just like the miter limit on the top miter. If the threshold is low enough, the artifacts disappear, however if we have a long and wide enough line on a large enough scale, the limit starts to take effect in an undesirable way, resulting in a "chopstick" line:

![screenshot from 2017-08-14 13-36-42](https://user-images.githubusercontent.com/9150102/29270725-64168408-80f8-11e7-9e65-77a899ffc672.png)

What do you think about my approach? Should we stick with it for now or try to come up with a better solution?

**Comment by jahow** [comment]
Hi,
Just a small input from an OpenLayers user/fanboy. The mentioned artefacts look awfully like a divide-by-zero case. Maybe this comes from the dot products in the linestring vertex shader? I've looked into it a bit and unless I'm wrong these products are used in divisions for miter operations, without a failsafe in case of very low value:
https://github.com/openlayers/openlayers/blob/master/src/ol/render/webgl/linestringreplay/defaultshader.glsl#L40

I haven't digged further and you're probably aware of that already, but maybe that'll help. Also your work on the webgl renderer is _impressive_.

**Comment by GaborFarkas** [comment]
Hello @jahow,

Thank you for your input. You are right, the dot product can be zero if the angle of the two segments are 0° or 180°. Unfortunately, making the procedure failsafe does not solve the issue. Glad you like my work on the WebGL renderer.

**Comment by PhilippePinheiroLIST** [comment]
I have similar visual effects on Openlayer 4.6.5 when I use the wegl renderer.
And it disappears when zooming or unzooming.

![ex1](https://user-images.githubusercontent.com/16240437/75137847-ff121d00-56e8-11ea-8a50-f15617037995.jpg)
![ex2](https://user-images.githubusercontent.com/16240437/75137850-00dbe080-56e9-11ea-9dd5-b8c81c753a1d.jpg)
