### ISSUE TITLE
Switching to map full view on one tab hides(display:none) the map container in the other tab

### ISSUE THREAD

**Issue by giridharkl** [openlayers/openlayers#7123]
Hi,
I have a similar issue. My environment is Angular 4, using openlayers npm package. In my application i have multiple tabs. Each tab contains a location map. When I resize the browser window, only the last tab content holds the map and the other tabs lose the map. However when I checked the map in other tab the property "display:none" on the canvas. If I disable it the map shows up again. I tried capturing the window:resize event and call map.updateSize() as suggested in the previous comments. The event gets triggered, but the map do not re-appear in the tab content.

I tried the following code:
@HostListener('window:resize', ['$event']) onResize(event) { //debugger; //event.target.innerWidth; this.map.updateSize(); }
This did not yield expected result. Also tried the following code:
ngAfterViewChecked() { //debugger; if (this.locMap.nativeElement.getAttribute('height') != '200px' || this.locMap.nativeElement.getAttribute('widht') != '300px') { this.map.updateSize(); } }

Please help me to resolve this issue. Even an idea how to go about it would be of great help. I know this is closed issue.
Thanks
Giri

**Comment by GISerWYJ** [comment]
@giridharkl any updates on this issue?thanks!
