### ISSUE TITLE
Not rendering TileWMS on iPhone

### ISSUE THREAD

**Issue by TheBoXon** [openlayers/openlayers#7129]
For some reason all my WMS Tile layers are not rendering on iPhone's and iPad's, what could be the problem? Regular ImageWMS renders just fine but i cannot use that for all features as it will take too long to load.

Here's part of my code:
`	  var testLayer = new ol.layer.Tile({
		  source: new ol.source.TileWMS({
				url: 'http://localhost/WMSServer',
				params: {'LAYERS': 'mylayer,andanotherone'},  
		  })
	  });
`

...
`      var map = new ol.Map({
		controls: [],
        layers: testLayer,
        target: 'map',
		allOverlays:true, 
        view: new ol.View({
          center: [1658377.765675, 8357930.420814],
          zoom: zoom
        })
      });`

Any ideas on how to solve?

**Comment by ahocevar** [comment]
Impossible to guess from the code snippets you provided. Maybe you're maxing out phone memory by stacking too many layers? Also note that there is no `allOverlays: true` option.

**Comment by TheBoXon** [comment]
I think i have isolated the problem, it has nothing to do with the above code. For some reason if i comment out these lines that gets the users position everything works on iOS aswell, but then i cannot get the user position.

The isolated code that's causing the trouble:
`		if ("geolocation" in navigator) {
		  navigator.geolocation.getCurrentPosition(do_something);
		} else {
		  // geolocation IS NOT available
		}
		
		
		function do_something(position) {
				  console.log(position);
			var latUser = position.coords.latitude;
			var longUser = position.coords.longitude;
			
			var newCoord = ol.proj.transform([longUser, latUser], 'EPSG:4326', 'EPSG:3857');
			
			//console.log(newCoord);
			map.setView(new ol.View({
					center: newCoord,
					zoom: zoom
			 }));


			// Adds map marker...
			addmarker(latUser, longUser, 'marker.png');


		}`

The above code works on PC and Android, but not on iOS.

Any suggestions?

**Comment by ahocevar** [comment]
Not related to OpenLayers. But you should also set an `ol.View` on devices that do not support geolocation.
