### ISSUE TITLE
getClosestPoint() doesn't intersect original Feature?

### ISSUE THREAD

**Issue by leo-mao** [openlayers/openlayers#7130]
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] If reporting a bug, I have tried with the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/)
- [x]  If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Hello I'm using Openlayer v4.3.1 and trying the following codeblock:
```javascript
var point =  feature.getGeometry().getClosestPoint(evt.mapBrowserEvent.coordinate);
console.log(feature.getGeometry().intersectsCoordinate(point));
```

console always logs `false`, this really wondering me, considering intersectsCoordinate() defination  `point` shall belong to `Feature` right?
I also pulled an issue [here](https://stackoverflow.com/questions/45701189/openlayer4-closestpoint-doesnt-intersect-feature)

**update Tue 2017-08-15 23:32:16 UTC**: It seems `getClosestPoint()` always return a wrong `point`.

**Comment by ahocevar** [comment]
The underlying `containsXY` always returns false `ol.geom.LineString`. I'd suggest we remove the definition of `#intersectsCoordinate()` from `ol.geom.Geometry`, and only define it for `ol.geom.Polygon` and `ol.geom.MultiPolygon`. Pull reqeusts for that accepted.

**Comment by leo-mao** [comment]
@ahocevar  nooo, I don't `intersectsCoordinate()` is to blame but `getClosestPoint()`, I also manually verified that `point` returned from `getClosestPoint()` was not in the `Feature`.

I'm in such a situation, would you please help me?
> I want to draw a GPS track using GeoJSON on the Openlayer, and if I click the the track, I can get the coodinate and other extra information(e.g. speed, time) of this point.
> So I made a `feature` with a `geometry` of type 'LineString', which contained a list of coordinates. Besides I saved extra information in `properties`, 
which looked like:
```json
properties:{"point1":{"time":"201701010001","speed":"1"},"point2":{"time":"201701010002","speed":2}}
```
>I used `a ol.interaction.Select()` object to tell me which feature were selected, but I still need a method which could return which specific `point` in the feature was closest to the  `Pixel` I clicked(Considering HitTolerance the `Pixel` I clicked is always not on the `feature`).

So do you have any alternative method recommand instead of

**Comment by ahocevar** [comment]
Then you must be doing something wrong. See https://openlayers.org/en/latest/examples/igc.html. The points you get from `getClosestPoint()` there are definitely on the line.

**Comment by ahocevar** [comment]
Closing due to lack of response. Please create a new ticket with a minimal codepen that shows the issue, if the issue persists.

**Comment by regiscamimura** [comment]
I'm having the same issue, can we please re-open this ticket? I have a jsfiddle for it: https://jsfiddle.net/regiscamimura/m6zLhjdg/4/

As you can see, I added a point to the map, used 

`line.getGeometry().getClosestPoint(coord)`

 to calculate the closest point, and yet the found point's coordinates does not intersects the line. Also, one of the point's extent is in the forEachFeatureIntersectingExtent results, while the second doesn't even have any results. Ideas?

**Comment by ahocevar** [comment]
I can confirm that there is an issue with `getClosestPoint().`. Investigating now.

**Comment by ahocevar** [comment]
Here is an updated fiddle: https://jsfiddle.net/v27mq0nu/. This is what I found out:

* With OpenLayers v6.0.0, the underlying issue (missing implementation of `containsXY`) is fixed.
* For the first point, the closest point is reported to intersect the line.
* For the second point, floating point inaccuracies (inherent to JavaScript) cause the test to fail.
* With an extent with a 1 millimeter buffer around the second point, the test passes as well for that one. This is to work around the floating point inaccuracies.

**Comment by regiscamimura** [comment]
Awesome, thanks!
