### ISSUE TITLE
how could i get pointerout & pointerenter event 

### ISSUE THREAD

**Issue by MkkOF** [openlayers/openlayers#7132]
why never get pointerout and pointerenter event? my code 
var interaction = new ol.interaction.Interaction({
            handleEvent: function (evt) {
                var type = evt.type;
                console.log(type);
                if (eventType == type) {
                    var feature = that.map.forEachFeatureAtPixel(evt.pixel, function (feature) {
                        return feature;
                    });
                    callback.call(this, feature);
                } else {
                    return true;
                }
            }
        });
 map.addInteraction(interaction);

**Comment by ahocevar** [comment]
The map does not handle these events. See http://openlayers.org/en/latest/apidoc/ol.MapBrowserEvent.html for events that the map handles.
