### ISSUE TITLE
geolocation on iOS not working

### ISSUE THREAD

**Issue by TheBoXon** [openlayers/openlayers#7134]
Everything works exactly as it's supposed to on PC and Android.

But when i toggle geolocation tracking on, openlayers stops rendering all of my ol.layer.Tile on iPad's and iPhones. It finds my position and marks it on the map just as it's supposed, but like said, stops rendering the Tile layers.

ol.layer.Image Loads just fine though.

Code is available here: https://pastebin.com/TuU7Mx0Z

Any ideas?

**Comment by ahocevar** [comment]
Please prrovide a working code pen, and reduce the amount of code to the minimum required to expose the issue. Your snippet seems incomplete. At least I cannot find where the view's center is set to the geolocation's coordinates.

**Comment by ahocevar** [comment]
Closing due to lack of response.
