### ISSUE TITLE
Feature requests: Immediately render the linedash of ol.style.Stroke in WebGL mode

### ISSUE THREAD

**Issue by stuartZhang** [openlayers/openlayers#7155]
Hello guys,

The line-dash feature for ol.style.Stroke works very well in Canvas-rendering mode.

Cloud you please make the line-dash feature for ol.style.Stroke in WebGL mode available as well?

**Comment by stuartZhang** [comment]
I have discovered that the ol.style.Stroke configuration parameters "strokeStyleLineCap", "strokeStyleLineDash", "strokeStyleLineDashOffset" and "strokeStyleLineJoin" are ignored in the JS file "ol-v4.3.1/ol/ol/render/webgl/linestringreplay.js".

Why?

**Comment by ahocevar** [comment]
These are not implemented for the WebGL renderer.

**Comment by DwieDave** [comment]
Will this option be implemented into the WebGL Renderer in the future?

**Comment by ahocevar** [comment]
In v6, there is a new WebGL renderer for points only.

**Comment by DwieDave** [comment]
Will it support `lineDash` on a LineString Stroke as well?
