### ISSUE TITLE
Class ol.style.RegularShape   didn't have Function  setRadius() 

### ISSUE THREAD

**Issue by xiaoq07** [openlayers/openlayers#7156]
ol.style.RegularShape didn't have  Function setRadius() ,

now  i want to change the radius, so  i must create a new  ol.style.RegularShape,
 is it right?

**Comment by ahocevar** [comment]
Yes, that's right. It is because the shape is rendered to a canvas. So instead of changing the radius dynamically in a style function, it is better to create a new RegularShape style for each radius and cache the styles with the radius as key.

**Comment by xiaoq07** [comment]
thanks for you
