### ISSUE TITLE
Language Issue --name_en not in English

### ISSUE THREAD

**Issue by BhuvanaSanthoshkumar** [openlayers/openlayers#7157]
There is an issue in our site, few chinese area are not in English. I am trying to pass "name_en" then too no luck. On debugging found in this place(olms.js) its not in english for name_en. Could you please help me resolve this issue?

![image](https://user-images.githubusercontent.com/10462041/29456841-3872cace-8435-11e7-98e8-6962b3d5e3a2.png)

**Comment by ahocevar** [comment]
Looks like that is OSM data. To fix it, go to openstreetmap.org, find the geometry with that wrong name, and fix it with the editor that is included there.
