### ISSUE TITLE
The example Measure doesn t work, only the development option but the code below doesn t work

### ISSUE THREAD

**Issue by angelrh83** [openlayers/openlayers#7173]
This issue tracker is for reporting bugs or feature requests, not for asking questions. For usage questions, refer to the (documentation)[http://openlayers.org/en/latest/doc/].

Ready to submit your bug or feature request? Make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] If reporting a bug, I have tried with the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/)
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by fredj** [comment]
These functions have been exported in #7140
