### ISSUE TITLE
ol.Sphere.getLength and ol.Sphere.getArea area not exposed

### ISSUE THREAD

**Issue by jesperhansson** [openlayers/openlayers#7175]
The new ol.Sphere.getLength and ol.Sphere.getArea (from 4.3.0) functions seems to be missing in the minified ol.js. 
It works fine in the ol-debug.js

[The measure example](http://openlayers.org/en/latest/examples/measure.html?q=area) is also broken because of this.

**Comment by fredj** [comment]
These functions have been exported in #7140
