### ISSUE TITLE
update @mapbox dependencies

### ISSUE THREAD

**Issue by gueuze** [openlayers/openlayers#7176]
When installing ngx-openlayers with npm, I get the following warnings. The developer of ngx-openlayers has advised that some or all of these are openlayers dependencies and suggested I report this to you so that the dependencies can be updated and we can benefit to any future updates by mapbox:

```
npm WARN deprecated vector-tile@1.3.0: This module has moved: please install @mapbox/vector-tile instead
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead
npm WARN prefer global marked@0.3.6 should be installed with -g
```

**Comment by fredj** [comment]
We're already using `@mapbox/vector-tile` (see 8690bb7c125) and the other packages are not installed by OpenLayers (see https://github.com/openlayers/openlayers/blob/master/package.json)
