### ISSUE TITLE
how to clear feature in openlayer map

### ISSUE THREAD

**Issue by Vishal90111** [openlayers/openlayers#7178]
I am trying to clear makers on ol map on change of input field. it will draw maker on map on change of input field but it add new maker again and again when i change input. i want to draw one maker at a time and clear previous one.
   

     function el(id) {
            return document.getElementById(id);
        } 
    el('suggesionBox').addEventListener('change', function() {
            var city= new ol.Feature({
                geometry: new ol.geom.Point(ol.proj.fromLonLat([long, lat])),
            });
    
            city.setStyle(new ol.style.Style({
                image: new ol.style.Icon ({
                    crossOrigin: 'anonymous',
                    src: '../../img/bpostmakericon.png'
                })
            }));
    
            var makerSource = new ol.source.Vector({
                features: [city]
            });
            var makerVector = new ol.layer.Vector({
                map: map,
                source: makerSource
            }); 
        });

Appreciate Your Help

i tried this makerSource.clear(); and makerSource.removefeatures() but it not works

**Comment by ahocevar** [comment]
You always add a new layer when the 'change' event is triggered. Change your code to only create a source once, and set a new feature on it:
```js
var markerSource = new ol.source.Vector();
var markerVector = new ol.layer.Vector({
  source: markerSource
});
map.addLayer(markerVector);

el('suggesionBox').addEventListener('change', function() {
  markerSource.clear();
  var city = new ol.Feature({
    geometry: new ol.geom.Point(ol.proj.fromLonLat([long, lat])),
  });
  markerSource.addFeature(city);
});
```
