### ISSUE TITLE
how to get current position latitude and longitude

### ISSUE THREAD

**Issue by Vishal90111** [openlayers/openlayers#7180]
I am refering a below example to track current position of user

http://openlayers.org/en/latest/examples/geolocation.html?q=geolocation

 geolocation.on('change:position', function() {
        var coordinates = geolocation.getPosition();
        positionFeature.setGeometry(coordinates ?
          new ol.geom.Point(coordinates) : null);
console.log(coordinates)
      });

coordinates value if different. how can i get latitude and longitude of current position.

**Comment by ahocevar** [comment]
Please describe the bug in the library that you are seeing, if any, or your feature request, if any. Otherwise please close this ticket and ask your questions on https://stackoverflow.com - you'll also find many answers there already, tagged with 'openlayers'.
