### ISSUE TITLE
deviceOrientation.setTracking doesn't work on any Android device

### ISSUE THREAD

**Issue by rshchang88** [openlayers/openlayers#7184]
rotate the map based on ol.DeviceOrientation({ tracking: true}).  iOS works, but no Android device (phone/tablet) works.  Heading is always "undefined"

deviceOrientation.on('change:heading', function (event) {
    var heading = event.target.getHeading();
    map.getView().setRotation(-heading + currentMap.MapRotation);

    //rotation degree
    var deg = (-heading * 180 / Math.PI).toFixed(2) + "deg";
    $(".mapCompass img").css({ "transform": "rotate(" + deg + ")" });
});

**Comment by fredj** [comment]
`ol.DeviceOrientation` is now deprecated in OpenLayers, see #7189
