### ISSUE TITLE
function ol.source.Vector.prototype.clear,the param 'fast=true' is invalid

### ISSUE THREAD

**Issue by codingmiao** [openlayers/openlayers#7185]
in function [ol.source.Vector.prototype.clear L370](https://github.com/openlayers/openlayers/blob/v4.3.1/src/ol/source/vector.js#L370)
even though the parm opt_fast is true,the code 'this.loadedExtentsRtree_.clear();' will still be executed,

so,when i create a vectorSource like this:
```
var vectorSource = new ol.source.Vector({  
                loader: function(extent, resolution, projection){  
                    //send http-get and build features  
                    var fs = ...;  
                    vectorSource.clear(true);  
                    vectorSource.addFeatures(fs);  
                },  
                strategy: ol.loadingstrategy.bbox  
            }); 
```

and add the Vector to map,It's going to keep executing the loader function

**Comment by ahocevar** [comment]
That's expected behavior and consistent with other source types and configurations. Calling `clear()` on the source that has a loader or url configured means you want to re-fetch everything.

What were you trying to achieve?

**Comment by fredj** [comment]
Closing due to lack of response.
