### ISSUE TITLE
Invalidate the new VectorImageTile cache on a refresh

### ISSUE THREAD

**Issue by mmomtchev** [openlayers/openlayers#7186]
The new VectorImageTile cache makes impossible reusing a VectorTile source with a new URL.
I had to add:
        source.sourceTiles_ = {};
after:
        source.refresh();
to make it work. Otherwise the already loaded tiles don't get replaced.

**Comment by ahocevar** [comment]
I think this will be fixed with #7172.

**Comment by dbauszus-glx** [comment]
Can this be re-opened? I just ran into the same issue with ol 10.2.1.

The VectorTile source.refresh() method did not work until I called source.sourceTiles_ = {}; after the refresh.

@mmomtchev thanks for finding this workaround which will help us in the meantime.

**Comment by ahocevar** [comment]
A completely different issue, but similar symptoms. Will be fixed with #16328.
