### ISSUE TITLE
ol.source.VectorTile ignores custom tilegrid for projection

### ISSUE THREAD

**Issue by AlesJiranek** [openlayers/openlayers#7199]
If i pass custom tile grid to ol.source.VectorTile, it is not saved to this.tileGrids_ and therefore it is ignored by ol.source.VectorTile.prototype.getTileGridForProjection.

It is necessary to save it to tileGrids_ in ol.source.VectorTile constructor. 

See #7200

**Comment by ahocevar** [comment]
The problem is not the tile grid, but the tile grid's extent, which is not respected when source tiles are loaded. I have created #7206 with a fix.
