### ISSUE TITLE
Map error Measure

### ISSUE THREAD

**Issue by wender440** [openlayers/openlayers#7204]
The latest version v4.3.1 is experiencing an error while taking measurements on the map, I'm using the Google Chrome browser.
![ol3](https://user-images.githubusercontent.com/8501003/29946564-3e9227be-8e7c-11e7-83cc-29187f713933.PNG)

**Comment by tschaub** [comment]
Thanks for the report @wender440.  This was addressed in #7140.  I'll push out a patch release with this fix.
