### ISSUE TITLE
CartoDb Source example  Response for preflight is invalid (redirect) error

### ISSUE THREAD

**Issue by seymacengiz94** [openlayers/openlayers#7218]
Hello, 
I saw CartoDb source example on openlayers web site and create a map on carto. It's seem completely what I want on carto map. But when I  tried on my c# application with openlayers, I'm getting this console error:

    XMLHttpRequest cannot load https://seymacengiz.cartodb.com/api/v1/map. Response for preflight is invalid (redirect)

This map include only one row, a point data. Also at first, it was working. So,What's changed?Is this problem because of codes or map settings?

       var mapConfig = {
            'layers': [{
                'type': 'cartodb',
                'options': {
                    'cartocss_version': '2.1.1',
                    'cartocss': '#layer { marker-width: 7; marker-fill: #FFB927; marker-fill-opacity: 0.9; marker-line-color: #FFF; marker-line-width: 1; marker-line-opacity: 1; marker-placement: point; marker-type: ellipse; marker-allow-overlap: true; }',
                    'sql': 'select * from isim'
                }
            }]
        };

        var cartoDBSource = new ol.source.CartoDB({
            account: 'seymacengiz' ,
            config: mapConfig
        });

        var map = new ol.Map({
            layers: [
              new ol.layer.Tile({
                  source: new ol.source.OSM()
              }),
              new ol.layer.Tile({
                  source: cartoDBSource
              })
            ],
            target: 'map',
            view: new ol.View({
                center: [0, 0],
                zoom: 2
            })
        });

**Comment by marcjansen** [comment]
Is this probably related to #7216?

**Comment by fredj** [comment]
@seymacengiz94 can you test if #7219 fixes this issue?

**Comment by seymacengiz94** [comment]
I fixed this issue with changing a part of ol.js file. I created my own js file and copied ol.js to mine. this code block in js file:

    function cx(a){var b=JSON.stringify(a.i);if(a.o[b])dx(a,a.o[b]);else{var c="https://"+a.B+".cartodb.com/api/v1/map";a.C&&(c+="/named/"+a.C);var d=new XMLHttpRequest;d.addEventListener("load",a.Pl.bind(a,b));d.addEventListener("error",a.Ol.bind(a));d.open("POST",c);d.setRequestHeader("Content-type","application/json");d.send(JSON.stringify(a.i))}}

then changed cartodb.com to carto.com. I used my js file instead of ol.js. It works now thank you
