### ISSUE TITLE
map.forEachLayerAtPixel misses layers

### ISSUE THREAD

**Issue by sbowler** [openlayers/openlayers#7222]
Based on the numerous issues, you guys are probably sick of this, but I'm also still having issues with the map.forEachLayerAtPixel not including an ol.layer.Image layer with an ImageStatic source on a canvas map. If I zoom in enough so the image is quite large it seems to work better than when I'm more zoomed out. I believe this broke like many others shortly after 3.18.2. 

I'm going to try to use a custom layerFilter function and see if that will help get the layer, but I doubt it based on your docs. I'll also try to get you guys a fiddle or something showing the issue if I can. Thanks for all your guys great work on this.

After a little further investigation it does appear this works perfectly with webGL. However, webGL is not wrapping the geoJSON vector map and isn't always filling in the polygons (countries) for whatever reason at this point so.

The images are PNG images that tend to have a fair bit of transparency, i.e. aren't usually very square.

**Comment by sbowler** [comment]
This is the closest I've gotten to setting up something similar, https://codepen.io/anon/pen/WEWgBg

**Comment by sbowler** [comment]
Something else I've noticed that might be helpful.

If an image is slightly tilted clockwise maybe 20 degrees or so then there seems to be some interesting behavior. Clicking around and on the left side of the image or so fails to be detected while clicking on the right side of the image appears to work. However, clicking outside of the image to the right of it results in it thinking the image was clicked on when it was not.

**Comment by ahocevar** [comment]
Thanks for the bug report. See #7225 for a fix. Please verify that it works for you.

**Comment by sbowler** [comment]
Like a glove. Seems to work flawlessly. Thanks for the quick response. You guys are amazing.

On an unrelated note, do you know why the webGL map stuff is so broken? I suspect it is related to my hack of geoJSON vector layers. I'm hoping to be able to transition soon to some OSM MBTile data that you guys better support natively and I suspect that might resolve the webGL issues.

**Comment by bjornharrtell** [comment]
@sbowler, AFAIK the OL WebGL renderer is experimental and still has known issues and probably unknown too. It was almost dropped completely from the project but @GaborFarkas has been doing impressive progress on it.

**Comment by sbowler** [comment]
That's about my understanding as well. I really appreciate all the work @GaborFarkas has done for WebGL to date. I think it's really needed to compete with other mapping libraries when it comes to vector data. I hope it keeps progressing.
