### ISSUE TITLE
text style was for short time rotated even though rotateWithView is false (on Android)

### ISSUE THREAD

**Issue by mayheki** [openlayers/openlayers#7224]
I've tested version 4.3.1 and 4.3.2.
when ol.layer.vector has opacity option and map has been rotated, text style was rotated shown as short time.
but text style was set rotateWithView is false.  I confirmed on android os 5.0.2 mobile phone. 
On 4.2.1 version, It didn't reproduced.

**Comment by ahocevar** [comment]
Can you please provide a code pen that shows the issue?

**Comment by mayheki** [comment]
I wrote the reproduced source using cluster layer example.
It does not chrome browser on Pc, But you can check android mobile chrome.
https://codepen.io/mayheki/pen/mMYbzj
