### ISSUE TITLE
Can't display geoserver layer group within openlayers

### ISSUE THREAD

**Issue by HeavenlyHost** [openlayers/openlayers#7227]
So here is the situation. I have been using openlayers to draw layers supplied by geoserver and at the individual layer level all looks good, however when configuring geoserver to provide a layer group (which should be seen as just another layer by open layers), it does not render. There is not even an error message it simply does not render.

So to clarify

Geoserver - provides the tiles over wms, the example attached contains two layers, the first is a simple world shape file, the second is a geoserver layer group containing two layers.

Incidentally if I remove the other layers from the geoserver group and only have one in the list then openlayers will display this single item on the map, but not if the layer group contains multiple items.

Code below...

[test-index.zip](https://github.com/openlayers/openlayers/files/1280549/test-index.zip)

**Comment by ahocevar** [comment]
Not an OpenLayers issue. Your test code looks sane. Use your browser's dev console to check the requests that OpenLayers makes, and see if there are any error messages from GeoServer.
