### ISSUE TITLE
zoom doesn't work while tracking gps

### ISSUE THREAD

**Issue by cuici** [openlayers/openlayers#7228]
Hello,
With the version 4.3.2, in the sample "[Geolocation Tracking with Orientation](https://openlayers.org/en/latest/examples/geolocation-orientation.html)" it is not possible to zoom (buttons or mousewheel) when the tracking is on. is-it a bug ? how to allow zooming ?
In the ol3.x versions this problem doesn't appear. 
Thanks

**Comment by ahocevar** [comment]
That example is very aggressively setting the position provided by the Geolocation component, so the behavior is intentional.

If you don't want that, you can use a different technique to update the map position:
```diff
--- a/examples/geolocation-orientation.js
+++ b/examples/geolocation-orientation.js
@@ -161,10 +161,7 @@ function updateView() {
 var geolocateBtn = document.getElementById('geolocate');
 geolocateBtn.addEventListener('click', function() {
   geolocation.setTracking(true); // Start position tracking
-
-  map.on('postcompose', updateView);
-  map.render();
-
+  geolocation.on('change:position', updateView);
   disableButtons();
 }, false);
```

**Comment by cuici** [comment]
it works, thanks !
