### ISSUE TITLE
Not compatible with browser es modules

### ISSUE THREAD

**Issue by ojhaujjwal** [openlayers/openlayers#7237]
The browsers have started to support es6 modules natively. You can use es6 modules natively with script type=module. However, we must specify js extension in import statements.

```js
like `import _ol_ from './index';` // this doesn't work because it will try to load from the URL without js extension.

like `import _ol_ from './index'.js;` // this works
```

Here's what I did in a file `maplayer.js`:
```js
import { transform } from '/node_modules/ol/proj.js';
```

But, the file proj.js includes an import statement without js extension. So, here's the result:

![image](https://user-images.githubusercontent.com/4995501/30239574-9b382522-957f-11e7-9ab4-cdde095e1842.png)

**Comment by tschaub** [comment]
This was addressed in https://github.com/openlayers/openlayers/commit/f118338c0a095780287a22a85288403b583cbab6 (part of #7223) and will be available in the next release.  Note the comment in the pull request about lack of "bare import" support in browsers.

**Comment by ojhaujjwal** [comment]
thanks.
