### ISSUE TITLE
Modify interaction and Point geometry lying on another geometry segment

### ISSUE THREAD

**Issue by sandman7920** [openlayers/openlayers#7248]
If we have **Point** lying on **LineString** segment, **Modify interaction** snap on the **LineString segment** instead of Point.
In this scenario Point cannot be moved without modifying (insert new vertex) **LineString** geometry first. 

P.S.
LineString is for example, same is valid for Polygon

**Comment by ahocevar** [comment]
I guess this is something we cannot fix in a way that makes everyone happy. Someone else might expect the line to be picked up first.

I've seen applications where users have separate modes for modifying points and lines. You could do that too.

**Comment by sandman7920** [comment]
But if someone want to insert a new vertex into line, he just can pick point with offset and then drag it into new location.

I think existing vertex, point must be with high priority over predicted one.

**Comment by ahocevar** [comment]
Can you provide a codepen that shows your situation? If you pick the point on its edge, it should be picked up instead of the line anyway.

**Comment by sandman7920** [comment]
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Draw and Modify Features</title>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.3.2/css/ol.css" type="text/css">
    <script src="https://openlayers.org/en/v4.3.2/build/ol.js"></script>
  </head>
  <body>
    <div id="map" class="map"></div>
    <script>
      var raster = new ol.layer.Tile({
        source: new ol.source.OSM()
      });

      var source = new ol.source.Vector();
      var vector = new ol.layer.Vector({
        source: source,
      });

      var map = new ol.Map({
        layers: [raster, vector],
        target: 'map',
        view: new ol.View({
          center: [0, 0],
          zoom: 6
        })
      });

      var modify = new ol.interaction.Modify({source: source});
      map.addInteraction(modify);
      
      var first = [0, 0];
      var second = [1000000, 0];
      
      source.addFeature(new ol.Feature({
            geometry: new ol.geom.LineString([first, second])
      }));
      
      source.addFeature(new ol.Feature({
            geometry: new ol.geom.Point([(first[0] + second[0])/2, (first[1] + second[1]) / 2])
      }));
      
    </script>
  </body>
</html>

```

**Comment by sandman7920** [comment]
[https://codepen.io/sandman7920/pen/ZXzggX]()

**Comment by ahocevar** [comment]
You're right, this feels like wrong behavior. Thanks for reporting and explaining the issue. We'd appreciate a pull request with a fix.

**Comment by sandman7920** [comment]
This [commit](https://github.com/sandman7920/openlayers/commit/0919efdc6130db62ce67964d8d723fff87b81dbc) fixes the issue (i hate new `pixelTolerance` parameter in pointDistanceToSegmentDataSquared)

@ahocevar can you take a look

**Comment by sandman7920** [comment]
New pen

https://codepen.io/sandman7920/full/dEdJvX

**Comment by koba-1** [comment]
For example I cannot pick the vertex of the LineString and the Point at the same time. Is there a way to do this?
![image](https://user-images.githubusercontent.com/49639986/59861570-65d47f00-9381-11e9-8b65-bad102fe5093.png)

**Comment by D3kion** [comment]
Try this
https://codepen.io/D3kion/full/LYNdrwo

> For example I cannot pick the vertex of the LineString and the Point at the same time. Is there a way to do this?
> ![image](https://user-images.githubusercontent.com/49639986/59861570-65d47f00-9381-11e9-8b65-bad102fe5093.png)

**Comment by koba-1** [comment]
> Try this
> https://codepen.io/D3kion/full/LYNdrwo
> 
> > For example I cannot pick the vertex of the LineString and the Point at the same time. Is there a way to do this?
> > ![image](https://user-images.githubusercontent.com/49639986/59861570-65d47f00-9381-11e9-8b65-bad102fe5093.png)

I works... thank you. 
But I see another bug, try to pick a vertex and release it above another vertex, and than pick it again... You are now grabbing two vertex at once.

**Comment by D3kion** [comment]
> > Try this
> > https://codepen.io/D3kion/full/LYNdrwo
> 
> It works... thank you.
> But I see another bug, try to pick a vertex and release it above another vertex, and than pick it again... You are now grabbing two vertexes at once.

Wow... Thanks! 
That's was hard to repeat 👍
