### ISSUE TITLE
KML support for GroundOverlay and ScreenOverlay

### ISSUE THREAD

**Issue by raiyni** [openlayers/openlayers#7255]
The KML parser lacks support for https://developers.google.com/kml/documentation/kmlreference#groundoverlay and https://developers.google.com/kml/documentation/kmlreference#screenoverlay

GroundOverlay is an overlay image that moves with the map.

ScreenOverlay is an overlay image that stays fixed in view. 

It would be a job. Probably convert each one to a Control/Overlay but that could lead to export problems. Or a fixed image feature but that wouldn't solve the problem a screenoverlay creates.

**Comment by bartvde** [comment]
#2941

**Comment by raiyni** [comment]
Hmm, wonder why my search didn't return it. Will close this and work on that then since the PRA is already in place.

**Comment by raiyni** [comment]
Wonder why my search didn't bring that up. Still leaves out ScreenOverlay but they are decently similar.

**Comment by raiyni** [comment]
What would be the preferred method of doing this? 

Passing the map object into ol.format.KML.readFeatures so that an overlay/control can be attached? Or make it a second function call on the KML to return the overlay/control? Or something different like creating a new feature type so that it can be hidden with the layer and exported with KML export?

**Comment by Skuriles** [comment]
Are there any news on this issue?

**Comment by raiyni** [comment]
No immediate progress. Been occasionally working on it in my downtime.

**Comment by skyval** [comment]
Are there any news on this issue?

**Comment by raiyni** [comment]
I stopped progress once the transition to v5 started and in the meantime our mapping requirements at work have slowed down.

**Comment by skyval** [comment]
Ok, I understand... I place image using ImageStatic and use coordinates from KML in imageExtent, but I can't rotate it. Is in there an any option to rotete ImageStatic?

**Comment by eric-g-97477** [comment]
I would like to see this ticket reopened in the hopes that someone can resolve it.

**Comment by mike-000** [comment]
@eric-g-97477  This should be possible with support for a transform matrix in projections as in #15402 making it much simpler https://jsfiddle.net/mthw1zjy/  than the method in https://github.com/openlayers/openlayers/issues/4949#issuecomment-495940972 which required integration with proj4.  All that would then be needed would be a `readGroundOverlay` method similar to `readCamera` using OpenLayers XML parsing to obtain the required properties of each overlay (name, west, south, east, north, href, rotation, drawOrder, color) to create a layer group of overlays.  

Support for a `color` option in ImageStatic, similar to Icon and fill-pattern, would be needed in some cases such as the example in https://developers.google.com/kml/documentation/kmlreference#groundoverlay

```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<GroundOverlay>
   <name>GroundOverlay.kml</name>
   <color>7fffffff</color>
   <drawOrder>1</drawOrder>
   <Icon>
      <href>http://www.google.com/intl/en/images/logo.gif</href>
      <refreshMode>onInterval</refreshMode>
      <refreshInterval>86400</refreshInterval>
      <viewBoundScale>0.75</viewBoundScale>
   </Icon>
   <LatLonBox>
      <north>37.83234</north>
      <south>37.832122</south>
      <east>-122.373033</east>
      <west>-122.373724</west>
      <rotation>45</rotation>
   </LatLonBox>
</GroundOverlay>
</kml>
```
In that example both the image and color have semi-transparency which would need handling as in #15295
