### ISSUE TITLE
Should ol.format.Wkt#writeGeometry(ol.geom.Geometry) accept options?

### ISSUE THREAD

**Issue by gkresic** [openlayers/openlayers#7256]
Documentation says nothing about options:

https://openlayers.org/en/latest/apidoc/ol.format.WKT.html#writeGeometry

but source code uses it:

https://github.com/openlayers/openlayers/blob/master/src/ol/format/wkt.js#L406

**Comment by fredj** [comment]
yes, the `@param` doc tag is missing
