### ISSUE TITLE
make ol.interaction.Draw.abortDrawing_ public?

### ISSUE THREAD

**Issue by giohappy** [openlayers/openlayers#7261]
I've been using a hack to abort the sketch currently being drawn:

`drawInteraction.setActive(false); // this will call ol.interaction.Draw.abortDrawing_()
drawInteraction.setActive(true);`

Is there any problem to exposing ol.interaction.Draw.abortDrawing_ through the API?

**Comment by fredj** [comment]
@giohappy what about #6526 ?

**Comment by giohappy** [comment]
sorry @fredj I looked for related issues but I couldn't find it. I will close this.
