### ISSUE TITLE
 changed the  browser  device pixel ratio but  getPixelFromCoordinate() is not change

### ISSUE THREAD

**Issue by wxqqq** [openlayers/openlayers#7268]
when The browser changes the scale translation  then fun getPixelFromCoordinate is still  original value,

is it a issue?

**Comment by tschaub** [comment]
Are you referring to the device pixel ratio (what is "changes the scale translation")?

Can you provide an example that demonstrates the issue?

**Comment by xiaoq07** [comment]
yes ， i mean i   changed the  window.devicePixelRatio，  
i did a canvas animation .
like this:
  map.on('postcompose',evt=>{
       ....
     let piex = map.getPixelFromCoordinate([50,50]);
})   
after changed it, the piex is not  change but the vector had scale.
![image](https://user-images.githubusercontent.com/8252997/30578396-22bccfac-9d46-11e7-9164-33a21e80e234.png)
the red circle shuld overlay the green circle
