### ISSUE TITLE
Setting cacheSize in ol.source.VectorTile breaks mapbox vector tiles.

### ISSUE THREAD

**Issue by wayofthefuture** [openlayers/openlayers#7271]
Ok so this has been a very hard issue to understand and isolate. I've got about 20 hours in isolating this problem. I removed as many culprits as possible and probably have found a bug with the cacheSize property of a vector tile source.

If you set the cacheSize to 0 or to a low number, then pan around for a little while, eventually the map will get tripped up and you will start seeing blank tiles. I've tested this with two vector tile sources and repeatedly swapped back and forth. I could be wrong, but I've been able to replicate the problem several times now and on multiple computers via CodePen. I have verified this in Chrome 60.0.3112.113, Chrome 61.0.3163.79, Edge 40.15063.0.0 and Safari 10.1.2. There is a link to the CodePen below which can replicate the problem. It tries to auto pan to replicate it easier. After it's done just pan around and it should hopefully happen for you.

Note that the automatic animations in the CodePen are not required to replicate the issue. All you have to do is pan around for a little while and it will happen. I just created the animation to make it easier to replicate. Please also note that I am willing to fund the fixing of this bug. Andreas is on vacation so I didn't want to bother him with these kind of things. Thanks for your help.

CodePen:
https://codepen.io/wayofthefuture/pen/ZXQydR

![screenshot from 2017-09-18 16-31-32](https://user-images.githubusercontent.com/5134107/30565691-ec13cfa8-9c8e-11e7-9e28-c74d2396b3b7.png)

**Comment by mbleichner** [comment]
We had a similar problem. After a full day of debugging and trial and error, I came down with a possible fix. It would be great if you could check it out:
https://github.com/mbleichner/openlayers/commit/10045ada69b349770cfdf343e33483e853ee28cd

If this works and produces no new issues, I can submit a pull request.

**Comment by ahocevar** [comment]
Looks like a safe change. Please submit a pull request.

**Comment by wayofthefuture** [comment]
Wow, very nice!
