### ISSUE TITLE
Text along lines: baseline is not taken into account when rendering stroke

### ISSUE THREAD

**Issue by brncsk** [openlayers/openlayers#7276]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue. – Not applicable.

When rendering labels along lines (introduced in #7239) in tandem with a non-default `textBaseline` property and a `stroke`, the stroke gets rendered as if the baseline was not set (see attached screenshot).

```javascript
new ol.style.Text({
  placement: 'line',
  textBaseline: 'top',
  stroke: new ol.style.Stroke({
    width: 2,
    color: 'white'
  })
})
```

<img width="217" alt="screen shot 2017-09-20 at 14 05 33" src="https://user-images.githubusercontent.com/1205180/30643099-e551c10e-9e0d-11e7-9a72-681f6c8d4655.png">

**Comment by ahocevar** [comment]
Thanks for reporting this issue. See #7287 for a fix.
