### ISSUE TITLE
ol.style.Circle on HDPI screens

### ISSUE THREAD

**Issue by sandman7920** [openlayers/openlayers#7277]
Currently ```ol.style.Circle``` and ```ol.style.RegularShape```, do not take ```DEVICE_PIXEL_RATIO``` into account.

This is my current workaround
```javascript
var HDPICircle = (function() {
    var ratio = ol.has.DEVICE_PIXEL_RATIO;
    var scale = 1 / ratio;
    return function (opts) {
        var shape = opts instanceof ol.style.Circle ? opts : new ol.style.Circle(opts);
        shape.setRadius(shape.getRadius() * ratio);
        var stroke = shape.getStroke();
        if (stroke !== undefined) {
            stroke.setWidth(stroke.getWidth() * ratio);
        }
        shape.setScale(scale);
        return shape;
    }
})();
```

It will be nice to have ```autoScaleDPI: bool``` in constructor opts (or at least scale property).

I think ```scale``` property must be passed to ```ol.style.RegularShape``` constructor

**Comment by bartvde** [comment]
there are many tickets on this already see #1574 #6144 etc
