### ISSUE TITLE
Bing Maps culture option don't have effect for all imagerySets

### ISSUE THREAD

**Issue by itsmsc** [openlayers/openlayers#7279]
Bing Maps culture option don't have effect for the imagerySets 'RoadOnDemand' and 'AerialWithLabelsOnDemand'. There is no Placeholder {culture} in the API-Response.
If have found a solution for this: https://msdn.microsoft.com/en-us/library/ff701709.aspx . If you call the REST-API with the parameter culture or alias c, the JSON-Response contains the correct &mkt - Parameter for this imagerySets.

Please add the culture - Option to the initial API-Call. 

Thank you!

**Comment by itsmsc** [comment]
Perhaps it is not described clearly enough, let me describe it more precisely:

The tiles returned for imagery type "Road" are not up to date (see https://social.msdn.microsoft.com/Forums/en-US/3d6d966d-d5d5-45ee-8259-d8a9d37e0fef/rest-imagery-api-tiles-out-of-date-when-comparing-to-bing-maps-website?forum=bingmapsservices ). Localization works fine.

Using the imagery type "RoadOnDemand" with more up to date tiles, the culture option from OpenLayers don't have effect. The reason for this, is a missing placeholder {culture} in parameter imageUrl in JSON-response from the API-Call https://dev.virtualearth.net/REST/v1/Imagery/Metadata/RoadOnDemand?..... To use localized tiles, the culture (c) parameter must added to the API Call (by example https://dev.virtualearth.net/REST/v1/Imagery/Metadata/RoadOnDemand?uriScheme=https&include=ImageryProviders&key=xxx&c=de-DE). In this case, the parameter imageUrl inside JSON-Response has the correct localization in Url (?mkt=de-DE). Without the parameter, it returns allways ?mkt=en-US .

Please add the parameter c with the value from options.culture to the BingMaps-API-Call.

**Comment by fredj** [comment]
yes, confirmed. patch to come
