### ISSUE TITLE
unnecessary opt_this / thisArg parameters

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#7284]
In some places in the openlayers source code there are unnecessary opt_this / thisArg paramters. All of these could be replaced by use of the javascript builtin .bind method of functions. Additionally es6 and es6 transpilers offer the locally bound arrow functions which even lessen the need for this parameters.

Smaller function signatures are an advantage, also the code gets a little more coherent.

Is a PR wanted?

https://github.com/openlayers/openlayers/search?q=opt_this
https://github.com/openlayers/openlayers/search?q=thisArg

**Comment by marcjansen** [comment]
I would love to habe less this param in the methods. I'd be plus 1, but I think others should weigh in as well. This would also be an API breaking change, and would force us to release a 5.0.0

**Comment by simonseyock** [comment]
I could prepare it and rebase it when enough PRs are gathered to justify a version 5.0.0, if this change is not enough.

**Comment by tschaub** [comment]
@simonseyock - this would be appreciated.  We're working toward a 5.0 release now (details on the wiki next week) and plan to do one more 4.x release with recent changes.  So this shouldn't have to wait for too long.

**Comment by simonseyock** [comment]
This will also make the bindTo property of the listenerObj unneeded.

**Comment by simonseyock** [comment]
I just started to work on it a little bit, so you can see what it looks like.

**Comment by simonseyock** [comment]
I started to work on it a little bit so you can see how it would look like.

**Comment by simonseyock** [comment]
We would need to decide how to deal with eventlisteners that are class methods. I see two possibilities:
1. bind the listener at the point where `ol.events.listen` is called. This causes a new function to be created each time this part is called. but as these functions are really small I don't think it is much of a problem. On the other hand it is not easy to use `ol.events.unlisten` anymore without storing the key and use `ol.events.unlistenByKey` (what is better anyhow in my opinion)
2. bind the listener in the constructor. It could look like this: `this.boundHandleSomething_ = this.handleSomething.bind(this)` or even `this.handleSomething_ = this.handleSomething_.bind(this)` as the method is useless without `this` anyways. This produces new code noise, but not in the function parameters what i would prefer.

**Comment by simonseyock** [comment]
Like this for example:

```
ol.control.MousePosition = function(opt_options) {

  var options = opt_options ? opt_options : {};

  ...

  ol.control.Control.call(this, {
    element: element,
    render: render,
    target: options.target
  });
  
  this.handleProjectionChanged_ = this.handleProjectionChanged_.bind(this):

  ol.events.listen(this,
      ol.Object.getChangeEventType(ol.control.MousePosition.Property_.PROJECTION),
      this.handleProjectionChanged_);
  
  ...

}

**Comment by simonseyock** [comment]
On the other hand ol.events.unlisten is very rarely used and can easily be replaced by unlistenByKey.

**Comment by tschaub** [comment]
In the case of `ol.events.listen()`, the `opt_this` argument [is unnecessary](https://github.com/openlayers/openlayers/blob/0503e3384d4326701e8e1d1bd16a0aef4ec436f4/src/ol/events.js#L13) when it is the same as `target`.  So that will get rid of some unnecessary `bind` calls.  In cases where we do need to pass a method as a callback, I think `bind`ing in the constructor as you have done makes sense.

**Comment by simonseyock** [comment]
Ok, i am following this pattern:
1. Is the target this? -> jsut remove the parameter
2. Is the handler added in the constructor? -> pass this.handler.bind(this)
3. Is the handler added in a method of the same class? -> bind handler in constructor: this.handler = this.handler.bind(this)
4. Is the handler added in a method of a child class? -> bind handler in constructor of base class: this.handler = this.handler.bind(this)

I am encountering some problems though. I give feedback as soon as I investigated this further.

**Comment by simonseyock** [comment]
I created a commit where I removed the opt_this of the ol.events functions. ( https://github.com/openlayers/openlayers/pull/7286/commits/db5c3c986bba5f8808f1a58dea3a2b76abb57132 ) 
The problems i encountered where most caused by the way some tests where written. Some properties are harder to test with .bind() (for example a simple equality of functions).
