### ISSUE TITLE
iOS11 - Map with clusters performance issue after rotation

### ISSUE THREAD

**Issue by alallo** [openlayers/openlayers#7294]
Hi guys,
If you open this [Cluster example](https://openlayers.org/en/latest/examples/cluster.html) in an iPad with iOS 11 you can see a performance issue. Try to:

1 - Rotate the map
2 - Move the map to the right (or to the left)

The map will move very slowly making it almost unusable. If you try with a map without clusters everything is working well.

Any thought on this?

Thank you

**Comment by ogo-adp** [comment]
I can confirm that

On IOS 10 everything is fine

On IOS 11.0 and IOS 11.0.1 panning is very slow as soon as you rotate the map

By patching ol.render.canvas.TextReplay.prototype.drawText() and making it an empty function, rendering is fast again but oviously text is not drawn. So it has something to do with text drawing on canvas. I did'nt go farther.

**Comment by ahocevar** [comment]
So maybe https://openlayers.org/en/master/examples/cluster.html works better? Text rendering has been completely reworked since the last release.

**Comment by ogo-adp** [comment]
Good catch @ahocevar ... Yes it's fast again with latest dev version :)

FYI, I think the slow code was in ol.render.canvas.Replay.prototype.replay_. In DRAW_TEXT switch, on IOS as pixelRatio is 2,  context.setTransform.apply(context, localTransform) is called and is slow on IOS 11. However forcing this call on PC (and pixelRatio at 1) with chrome was slow too, so this rework is welcomed for everyone :)
