### ISSUE TITLE
MultiPoint rendering

### ISSUE THREAD

**Issue by fperucic** [openlayers/openlayers#7296]
Was trying out the latest development code and noticed MultiPoints are not rendering correctly.

Can be seen in `modify-test.html` and in this codepen.

[https://codepen.io/anon/pen/MEojzg?editors=1010](https://codepen.io/anon/pen/MEojzg?editors=1010)

**Comment by bartvde** [comment]
your CRS is set to EPSG:3857 but your coordinates are in 4326?

**Comment by fperucic** [comment]
when tried with https://openlayers.org/en/v4.0.1/build/ol.js everthing works as expected

**Comment by ahocevar** [comment]
Issue confirmed, working on a fix.
