### ISSUE TITLE
Can't zoom the map with scroll when it has a Draw interaction with freehand: true

### ISSUE THREAD

**Issue by trevorblades** [openlayers/openlayers#7300]
If I set `freehand: true` in a new `ol.interaction.Draw`, I can't zoom the map using my scroll wheel. 

It seems this is due to this line: https://github.com/openlayers/openlayers/blob/v4.3.4/src/ol/interaction/draw.js#L312 where we're stopping event propagation if freehand mode is on. This seems a bit too greedy, and it might be better to only stop event propagation when freehand mode is on *and* the event is a `mousedown` or `mousemove`.

**Comment by ahocevar** [comment]
The change you propose makes sense. Would you be able to provide a pull request?

**Comment by trevorblades** [comment]
@ahocevar for sure! I'll put something together this week
