### ISSUE TITLE
ol.format.GeoJSON (readFeatures) reading geometry_name 

### ISSUE THREAD

**Issue by EduardoNogueira** [openlayers/openlayers#7303]
We are working with wfs layers that we don't know the geometry name beforehand and we cannot use the geometryName parameter from the ol.format.GeoJSON. The wfs layers are hosted on a geoserver that returns the geometry_name field in the geojson output format. We are wondering if that could be an option like `readGeometryNameFromFeature` that in the case of the geometryName option being unset looks for a geometry_name field on the geojson.
We are available to do a PR, if you interest in include this feature on openlayers.

Geoserver output format docs:
http://docs.geoserver.org/stable/en/user/services/wfs/outputformats.html#json-and-jsonp-output

**Comment by ahocevar** [comment]
A GeoJSON document will always have the geometry as "geometry" property. This can also be seen in the snippet on the doc page you linked.

Why exactly do you want to use a different geometry name in the features that are read from the GeoJSON?

**Comment by EduardoNogueira** [comment]
When we send wfs transactions to geoserver as the default geometry name is "geometry", if it doesn't correspond to the one declared in the feature model it will throw an error and because geometry_name isn't in the properties we can't call `setGeometryName` programmatically. By reading the geometry_name from the geojson this problem won't happen.
