### ISSUE TITLE
getFeatureInfoUrl doesn't work for reprojected raster

### ISSUE THREAD

**Issue by oterral** [openlayers/openlayers#7304]
When we use WMS with the on-the-fly reprojection the getFeatureInfoUrl needs the equivalent resolution and the coordinates requested in  the original projection, not those from the current view.

Since `ol.reproj.calculateSourceResolution`is not exportable, I see 2 solutions:

 1) Make `ol.reproj.calculateSourceResolution` exportable
or
 2) Automatically recalculate the resolution and the coordinate requested in the `getFeatureInfoUrl` function

What do you think?
The 2nd solution seems more clean.

**Comment by ahocevar** [comment]
I agree that 2 is the way to go. Are you able to create a pull request?

**Comment by oterral** [comment]
Yes I'm on it
