### ISSUE TITLE
Openlayers 4 Draw interaction removeLastPoint on a touch device

### ISSUE THREAD

**Issue by JanBojko** [openlayers/openlayers#7308]
I tried to use the function ol.interaction.Draw.removeLastPoint() on a touch device during a feature creation. The method works correctly, but the "cursor" point remains on the last position. After another touch a new point is created correctly. This behaviour is logical in a browser, because when I move with a mouse and the cursor position is changing and the point below it as well, however on a touch device it is not possible. I am not able to remove this pointer position/point after removeLastPoint(). A user might be confused, that he removes a point and nothing change until he touches the screen.

**Comment by JanBojko** [comment]
I made a workaround via styles and some editing attribute. Haven't figured out to handle it with a polygon.
`geometry: function (feature) {
                var coordinates;
                if (feature.getGeometry().getType() == 'LineString') {
                    coordinates = feature.getGeometry().getCoordinates();
                    //Don't show last point (browser pointer)
                    if (feature.get('drawing') == true) {
                          coordinates.pop();
                    }
                    return new ol.geom.MultiPoint(coordinates);
                }
}
`

**Comment by echocompany** [comment]
2018 bug still present

**Comment by ahocevar** [comment]
We are happy to accept a pull request with a fix.

**Comment by echocompany** [comment]
I lack understanding of the process to modify code 

I Change the code in function removeLastPoint for type LineString:
```
coordinates = this.sketchCoords_;
coordinates.splice(-2, 1);
this.geometryFunction_(coordinates, geometry);
if (coordinates.length >= 2) {
    this.finishCoordinate_ = coordinates[coordinates.length - 2].slice();
}
```
to
``` coordinates = this.sketchCoords_;
coordinates.splice(-1, 1);//remove last pset
this.geometryFunction_(coordinates, geometry);
this.sketchPoint_.getGeometry().setCoordinates(coordinates[coordinates.length - 1].slice());//set pointer to last pset
if (coordinates.length >= 2) {
    this.finishCoordinate_ = coordinates[coordinates.length - 1].slice();//set finishCoordinate to last pset
}
```
But the last point in coordinate - is a pointer not a point? How to fix it?

If i move the last coordinate to last-1 coordinate, that`s removes ok - but when user add point by touch, i have duplicate the points

**Comment by presto41** [comment]
I added yesterday a new [ask on StackOverflow about removeLastPoint() problem](https://stackoverflow.com/questions/54985377/own-removelastpoint-function-for-polygons-in-openlayers). Maybe will you help me with that?
