### ISSUE TITLE
ScaleLine control does not respect metersPerUnit of the projection

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#7309]
- [X] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [X] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [X] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue. -> snippet here

I've been using the following projection and scalebar code to create a metric scalebar for an image viewer, using zoomify raster tiles.

```
var getPointResolution = function(a) {
  return a
}

var projOptions = {
  code: 'customcode',
  units: 'pixels',
  extent: [0, 0, width, height],
  metersPerUnit: 1 / data.pixelsPerMeter,
  getPointResolution: getPointResolution,
}

var olProj = new ol.proj.Projection(projOptions)

var olView = new ol.View({
  projection: viewer.olProj,
  minZoom: 1,
  maxZoom: viewer.maxNativeZoom,
})

var controlScale = new ol.control.ScaleLine({
  units: 'metric',
  target: ...,
})

map.addControl(controlScale)
```

This worked perfectly in all 3.x and 4.x versions up till 4.2.0. It displays totally different values starting from 4.3.0, including the latest 4.3.4 version. The displayed value is 1000 m instead of 5 mm for example.

Since this was not in the release notes, I believe it is a bug.

**Comment by sebalaini** [comment]
same problem here, the scale value is 100.000 greater than the real value.
It seems that already in V3 was a problem, a lot of people talk about this bug.

Also when you move the map in x y axis the scaleLine changes width without modifying the actual zoom.
Here my code:

```
Proj4js.defs["EPSG:27700"] = "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs";

var projection = new ol.proj.Projection({
code: 'EPSG:27700',
units: 'm'
});

controls: ol.control.defaults({
  attributionOptions: ({
  collapsible: false
  })
}).extend([
  // add the actual scale in "m"
  new ol.control.ScaleLine({units:'metric', target: 
document.getElementById('map_extras')})
]),
layers: [layers, orders],
target: 'mapdiv',
view: new ol.View({
projection: projection,
    center: ol.proj.fromLonLat([parseInt(setPos[0]), parseInt(setPos[1])], projection),
resolution: 2.8,
resolutions: [2.8, 1.4, 0.7, 0.28, 0.14, 0.07],
})
```
Here 2 screenshot to see that the width changes just moving the x y axis.

![capture](https://user-images.githubusercontent.com/17096352/31942565-a868bb38-b8bd-11e7-973e-319bf92452e2.PNG)
![capture2](https://user-images.githubusercontent.com/17096352/31942566-a87d2000-b8bd-11e7-9df3-f6539129507e.PNG)

It's a Work project so I don't have a CopePen.

**Comment by yurykovshov** [comment]
I suppose these changes in scaleline.js has broken it.
https://github.com/openlayers/openlayers/pull/7087/files#diff-2924cafbc70baae54a9effb87d39a1f8

**Comment by ahocevar** [comment]
Please, can someone provide a CodePen? I tend to believe that the snippets posted here had configured things in a way to make them work with the broken ScaleLine in previous versions.

Because if I add a ScaleLine to the [Zoomify example](https://openlayers.org/en/latest/examples/zoomify.html), I get the expected result - no further configuration made, so 1 pixel equals 1 meter, and the scale line looks correct.

**Comment by hyperknot** [comment]
OK, I'll look into making a CodePen. Is there any dummy codepen you are using for bug reports I can fork from?

**Comment by ahocevar** [comment]
You can create one from any of the examples at https://openlayers.org/en/latest/examples/, by clicking "Edit" below the bottom right of the map.

**Comment by yurykovshov** [comment]
For example: https://codepen.io/kosades/pen/wPJMva

**Comment by ahocevar** [comment]
Thanks for the codepen @yurykovshov. So the issue here is that the `metersPerUnit` of the projection are not respected.

**Comment by ahocevar** [comment]
@sebalaini, your issue is unrelated to the problem described in this ticket. Try to configure your projection differently:
```js
var projection = new ol.proj.Projection({
  code: 'EPSG:27700',
  units: 'm',
  getPointResolution: function(resolution, coordinate) {
    return ol.proj.getPointResolution(projection, resolution, coordinate);
  }
});
```

**Comment by ahocevar** [comment]
@sebalaini Your issue is a different one. You simply need to configure your projection differently. See https://github.com/openlayers/openlayers/issues/3285#issuecomment-77334771.

**Comment by hyperknot** [comment]
@ahocevar I'm finally done with my CodePen as well:

https://codepen.io/hyperknot/pen/RjLdJR?editors=0010

Shows mm-s with 4.2.0, shows km-s with 4.5.0.

**Comment by ahocevar** [comment]
Yes. You can use https://openlayers.org/en/master/build/ol.js.

**Comment by hyperknot** [comment]
@ahocevar it works with master / after the PR! 

I am using the same metersPerUnit option, so can I be safe in using the next version (4.5.1?)
