### ISSUE TITLE
Feature Request: Only render Circle and LineString labels when they fit

### ISSUE THREAD

**Issue by Abyss777** [openlayers/openlayers#7317]
Hello,

I've noticed useful feature #7292 implemented in last release.
It would be nice to have the same for Circles and LineStrings.
Users of our project allowed to draw own geozones of three types: Polygon, Circle and LineString. There is a mess of labels if map is zoomed out a lot, but with #7292 everything is looks very nice but with polygons only.

I think Extent can be used to determine if label fit LineString.

**Comment by ahocevar** [comment]
If you configure labels to follow lines (with the new `placement: 'line'` option, you get the same for linestrings.

For circles, we’d accept a pull request. Also note that the next release of OpenLayers will have full label decluttering.
