### ISSUE TITLE
ol install via npm not working due to file naming 

### ISSUE THREAD

**Issue by tompap** [openlayers/openlayers#7318]
I noticed this working that version 4.4.0 is not working
when installing from npm

ERROR in ./~/ol/plugins.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./PluginType.js in /home/mcore/src/www/frontend/node_modules/ol
resolve file
  /home/mcore/src/www/frontend/node_modules/ol/PluginType.js doesn't exist
  /home/mcore/src/www/frontend/node_modules/ol/PluginType.js.webpack.js doesn't exist
  /home/mcore/src/www/frontend/node_modules/ol/PluginType.js.web.js doesn't exist
  /home/mcore/src/www/frontend/node_modules/ol/PluginType.js.js doesn't exist
  /home/mcore/src/www/frontend/node_modules/ol/PluginType.js.json doesn't exist

with 4.3.2 the import are using "lowercase" so it's working. The problem is at least from 4.4.0

**Comment by bartvde** [comment]
see: https://github.com/openlayers/openlayers/pull/7249#issuecomment-334613554
