### ISSUE TITLE
Is Arc cluster possible??

### ISSUE THREAD

**Issue by BhuvanaSanthoshkumar** [openlayers/openlayers#7320]
Is cluster of Arcs possible? I am trying to cluster Arcs as we do for point features? Because when point feature is clustered and the user tries to draw arcs,it is drawn at different places but they actually belong to the clustered point .

I am trying something like this but that doesn't work.

 this.clusterSource = new ol.source.Cluster({
                distance: parseInt(50, 10),
                source: this.arcSource
            });

  var flightsLayer = new ol.layer.Vector({
                source: this.clusterSource
});
 map.addLayer(flightsLayer);

Any help on this please?

**Comment by ahocevar** [comment]
You have to configure a `geometryFunction` on the `Cluster` source. It takes a feature as argument and returns a point geometry. All you have to do is return a sensible point for the arc in the provided feature.
