### ISSUE TITLE
Error using the latest version 4.4.0 of npm with webpack.

### ISSUE THREAD

**Issue by juusechec** [openlayers/openlayers#7324]
With the last test travis execution update from 4.3.4 to 4.4.0 version. And get some errors.
Source code: http://github.com/AgenciaImplementacion/mobile-geoportal
Travis test: https://travis-ci.org/AgenciaImplementacion/mobile-geoportal/builds/284292245

ERROR in ./~/ol/tilegrid.js
Module not found: Error: Can't resolve './tilegrid/TileGrid.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/tilegrid.js 8:0-60
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../Feature.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 6:0-41
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../format/Feature.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 7:0-55
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../format/JSONFeature.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 8:0-63
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/tilewms.js
Module not found: Error: Can't resolve '../source/TileImage.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/tilewms.js 12:0-59
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/xyz.js
Module not found: Error: Can't resolve '../source/TileImage.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/xyz.js 2:0-59
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/tilewms.js
Module not found: Error: Can't resolve '../source/WMSServerType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/tilewms.js 13:0-67
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/style/style.js
Module not found: Error: Can't resolve '../style/Circle.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/style'
 @ ./~/ol/style/style.js 3:0-51
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/style/style.js
Module not found: Error: Can't resolve '../style/Fill.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/style'
 @ ./~/ol/style/style.js 4:0-47
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/style/style.js
Module not found: Error: Can't resolve '../style/Stroke.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/style'
 @ ./~/ol/style/style.js 5:0-51
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../Collection.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 5:0-47
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../CollectionEventType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 6:0-65
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction/select.js
Module not found: Error: Can't resolve '../CollectionEventType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/interaction'
 @ ./~/ol/interaction/select.js 2:0-65
 @ ./src/modules/shapefile/popup.js
 @ ./src/modules/shapefile/shapefile.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../ObjectEventType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 7:0-57
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../source/Source.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 18:0-53
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../source/State.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 19:0-51
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../source/VectorEventType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 20:0-71
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/layer/vector.js
Module not found: Error: Can't resolve '../LayerType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/layer'
 @ ./~/ol/layer/vector.js 2:0-45
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/layer/tile.js
Module not found: Error: Can't resolve '../LayerType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/layer'
 @ ./~/ol/layer/tile.js 2:0-45
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/style/circle.js
Module not found: Error: Can't resolve '../style/RegularShape.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/style'
 @ ./~/ol/style/circle.js 2:0-63
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/layer/vector.js
Module not found: Error: Can't resolve '../layer/Layer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/layer'
 @ ./~/ol/layer/vector.js 3:0-49
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/layer/tile.js
Module not found: Error: Can't resolve '../layer/Layer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/layer'
 @ ./~/ol/layer/tile.js 3:0-49
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/layer/vector.js
Module not found: Error: Can't resolve '../style/Style.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/layer'
 @ ./~/ol/layer/vector.js 5:0-49
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction/select.js
Module not found: Error: Can't resolve '../style/Style.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/interaction'
 @ ./~/ol/interaction/select.js 13:0-49
 @ ./src/modules/shapefile/popup.js
 @ ./src/modules/shapefile/shapefile.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/layer/tile.js
Module not found: Error: Can't resolve '../layer/TileProperty.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/layer'
 @ ./~/ol/layer/tile.js 4:0-63
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './PluggableMap.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 2:0-50
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/control.js
Module not found: Error: Can't resolve './Collection.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/control.js 1:0-46
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './Collection.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 1:0-46
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './PluginType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 3:0-46
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/plugins.js
Module not found: Error: Can't resolve './PluginType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/plugins.js 1:0-46
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './CenterConstraint.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 2:0-58
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './Object.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 3:0-38
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/overlay.js
Module not found: Error: Can't resolve './Object.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/overlay.js 3:0-38
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './ResolutionConstraint.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 4:0-66
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './RotationConstraint.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 5:0-62
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './ViewHint.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 6:0-42
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './ViewProperty.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 7:0-50
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/overlay.js
Module not found: Error: Can't resolve './MapEventType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/overlay.js 2:0-50
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/overlay.js
Module not found: Error: Can't resolve './OverlayPositioning.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/overlay.js 4:0-62
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/tilegrid.js
Module not found: Error: Can't resolve './proj/Units.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/tilegrid.js 7:0-46
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './proj/Units.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 19:0-46
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/proj.js
Module not found: Error: Can't resolve './proj/Units.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/proj.js 7:0-46
 @ ./~/ol/tilegrid.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/tilegrid.js
Module not found: Error: Can't resolve './extent/Corner.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/tilegrid.js 4:0-52
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/extent.js
Module not found: Error: Can't resolve './extent/Corner.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/extent.js 2:0-52
 @ ./~/ol/tilegrid.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../geom/GeometryCollection.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 9:0-73
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../geom/LineString.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 10:0-57
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../geom/MultiLineString.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 11:0-67
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../geom/MultiPoint.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 12:0-57
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../geom/MultiPolygon.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 13:0-61
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './geom/Polygon.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 14:0-50
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../geom/Polygon.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 15:0-51
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/format/geojson.js
Module not found: Error: Can't resolve '../geom/Point.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/format'
 @ ./~/ol/format/geojson.js 14:0-47
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './geom/GeometryType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 13:0-60
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/style/style.js
Module not found: Error: Can't resolve '../geom/GeometryType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/style'
 @ ./~/ol/style/style.js 2:0-61
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction/select.js
Module not found: Error: Can't resolve '../geom/GeometryType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/interaction'
 @ ./~/ol/interaction/select.js 8:0-61
 @ ./src/modules/shapefile/popup.js
 @ ./src/modules/shapefile/shapefile.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/view.js
Module not found: Error: Can't resolve './geom/SimpleGeometry.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/view.js 15:0-64
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../events/Event.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 11:0-51
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction/select.js
Module not found: Error: Can't resolve '../events/Event.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/interaction'
 @ ./~/ol/interaction/select.js 5:0-51
 @ ./src/modules/shapefile/popup.js
 @ ./src/modules/shapefile/shapefile.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../events/EventType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 12:0-59
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/source/vector.js
Module not found: Error: Can't resolve '../structs/RBush.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/source'
 @ ./~/ol/source/vector.js 21:0-53
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/canvas/ImageLayer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 8:0-78
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/canvas/Map.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 9:0-64
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/canvas/TileLayer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 10:0-76
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/canvas/VectorLayer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 11:0-80
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/canvas/VectorTileLayer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 12:0-88
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/webgl/ImageLayer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 13:0-76
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/webgl/Map.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 14:0-62
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/webgl/TileLayer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 15:0-74
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/map.js
Module not found: Error: Can't resolve './renderer/webgl/VectorLayer.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/map.js 16:0-78
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction/select.js
Module not found: Error: Can't resolve '../interaction/Interaction.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/interaction'
 @ ./~/ol/interaction/select.js 9:0-73
 @ ./src/modules/shapefile/popup.js
 @ ./src/modules/shapefile/shapefile.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction/select.js
Module not found: Error: Can't resolve '../layer/Vector.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/interaction'
 @ ./~/ol/interaction/select.js 10:0-51
 @ ./src/modules/shapefile/popup.js
 @ ./src/modules/shapefile/shapefile.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction/select.js
Module not found: Error: Can't resolve '../source/Vector.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/interaction'
 @ ./~/ol/interaction/select.js 12:0-53
 @ ./src/modules/shapefile/popup.js
 @ ./src/modules/shapefile/shapefile.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/extent.js
Module not found: Error: Can't resolve './extent/Relationship.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/extent.js 3:0-64
 @ ./~/ol/tilegrid.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/proj.js
Module not found: Error: Can't resolve './Sphere.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/proj.js 2:0-38
 @ ./~/ol/tilegrid.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/proj.js
Module not found: Error: Can't resolve './proj/EPSG3857.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/proj.js 4:0-52
 @ ./~/ol/tilegrid.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/proj.js
Module not found: Error: Can't resolve './proj/EPSG4326.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/proj.js 5:0-52
 @ ./~/ol/tilegrid.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/proj.js
Module not found: Error: Can't resolve './proj/Projection.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/proj.js 6:0-56
 @ ./~/ol/tilegrid.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/asserts.js
Module not found: Error: Can't resolve './AssertionError.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/asserts.js 1:0-54
 @ ./~/ol/format/geojson.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/featureloader.js
Module not found: Error: Can't resolve './format/FormatType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/featureloader.js 2:0-60
 @ ./~/ol/source/vector.js
 @ ./src/modules/geoserver/cargar-servicio.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './Kinetic.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 2:0-40
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/DoubleClickZoom.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 3:0-80
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/DragPan.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 4:0-64
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/DragRotate.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 5:0-70
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/DragZoom.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 6:0-66
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/KeyboardPan.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 7:0-72
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/KeyboardZoom.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 8:0-74
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/MouseWheelZoom.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 9:0-78
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/PinchRotate.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 10:0-72
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/interaction.js
Module not found: Error: Can't resolve './interaction/PinchZoom.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/interaction.js 11:0-68
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/control.js
Module not found: Error: Can't resolve './control/Attribution.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/control.js 2:0-64
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/control.js
Module not found: Error: Can't resolve './control/Rotate.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/control.js 3:0-54
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/control.js
Module not found: Error: Can't resolve './control/Zoom.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol'
 @ ./~/ol/control.js 4:0-50
 @ ./~/ol/map.js
 @ ./src/modules/map/map.js
 @ ./src/modules/init/main.js

ERROR in ./~/ol/events/condition.js
Module not found: Error: Can't resolve '../MapBrowserEventType.js' in '/home/jorge/workspace/mobile-geoportal/node_modules/ol/events'
 @ ./~/ol/events/condition.js 1:0-65
 @ ./~/ol/interaction/select.js
 @ ./src/modules/shapefile/popup.js
 @ ./src/modules/shapefile/shapefile.js
 @ ./src/modules/init/main.js

**Comment by bartvde** [comment]
Please check out 4.4.1
