### ISSUE TITLE
Unable to properly extend source.Source because ol.js calls the minified method names

### ISSUE THREAD

**Issue by MontyD** [openlayers/openlayers#7326]
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

When trying to extend the source.Vector class I've found that methods such as forEachFeatureInExtent and others are not getting called as the renderer is calling the minified method names. At the moment I'm working around this by using ol-debug, which does not have the same problem as method names are not minified. This is not ideal though.

Example using ol.js where the minified method names are called: 
https://codepen.io/MontyD/pen/ZXrPwG (check the console, and see that the ac and de methods are called, but not the forEachFeatureInExtent method as expected)

Example using ol-debug.js where the correct methods are called:
https://codepen.io/MontyD/pen/LzQaKz

Thank you very much for all your hard work on this library, and let me know if you need anything else from me.

**Comment by tschaub** [comment]
The [`ol` package](https://www.npmjs.com/package/ol) allows you to properly inherit from things in the library.  For example, you could do something like this:

```js
import VectorSource from 'ol/source/vector';
import ol from 'ol';

function CustomSource(options) {
  // do whatever you want

  VectorSource.call(this, options);
};

ol.inherits(CustomSource, VectorSource);

export default CustomSource;
```

The Closure Compiler generated full builds do not allow this level of flexibility.
