### ISSUE TITLE
Pluggable Map (in projects that include ol3 source and compile with closure)

### ISSUE THREAD

**Issue by waxenegger** [openlayers/openlayers#7332]
I thought I'd mention an issue that I ran into. It's a setup with openlayers that probably not too many projects use I assume and on top I use PluggableMap directly instead of CanvasMap. So feel free to ignore if you think it's of too specific a nature.

I compile with the openlayers library sources included and the new PluggableMap approach caused an issue for me due to the closure compiler and its mangling with the advanced optimization.
https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/canvas/map.js#L70 uses (I assume for that matter) string notation to define the functions on the class. 

What happens then for me is that in https://github.com/openlayers/openlayers/blob/master/src/ol/pluggablemap.js#L1421 the "handles" function call becomes mangled and therefore the call fails.

Listing the handles in the compiler's externs prevents that from happening. Perhaps that's the envisioned way of dealing with such issues in the specific setup I use but I wonder if a consistent approach isn't maybe cleaner (such as calling the respective methods in the same 'string notation' as their declaration - though it doesn't look to nice. or defining extern rules for the few affected functions to begin with)

**Comment by tschaub** [comment]
Thanks for the report @waxenegger.  I think that we should use bracket notation with `handles` for consistency (and to avoid having to use externs.  So it looks to me like an oversight that we use dot notation [where calling](https://github.com/openlayers/openlayers/blob/8a08ab646341586e1a8eb6ea50de038fa19219a0/src/ol/pluggablemap.js#L1421) `candidate.handles()`.

If you are able to put together a pull request to fix this, that would be appreciated.
