### ISSUE TITLE
Text rendering problem with scale in ol >= 4.4.0

### ISSUE THREAD

**Issue by ogo-adp** [openlayers/openlayers#7334]
We are trying to upgrade our app from 4.3.4 to 4.4.1 and we encounter a rendering problem.

We use features with point geometries and a text style to draw moving objects on a map. We can scale them according to some rules (map zoom or other). By using special fonts (like fontawesome) we can draw complex shapes of any size and get pixel perfect and fast rendering at any scale (like a vector rendering).

With ol >= 4.4.0 we do not get pixel perfect rendering anymore but some sort of pixelated rendering. 

Please look at this repro : https://codepen.io/anon/pen/KXoQmv?editors=0010

On this repro we use scale, and this does not render properly on 4.4.1 but render perfectly on 4.3.4.

I did not find a way to get back to previous behavior.

**Comment by ahocevar** [comment]
This is because text is now pre-rendered to images, for better performance. Have you tried changing the font size and stroke width instead of the scale? Or use a font size for the highest possible scale, and scale down instead of up?

**Comment by ogo-adp** [comment]
Yes, I've tried this, but it does not give good results. Shape is blurry, and for a reason I don't understand yet, sometimes ol does not render the shape properly (bad font used) in 4.4 (will dig further, this is probably a second problem).

About the performance choice, are you sure that drawImage() on canvas is any faster than fillText() especially when doing scaling of image ?

**Comment by ahocevar** [comment]
The issue with the wrong font used is maybe that you are using a web font which is not loaded yet when the images are pre-rendered. This was the same previously, but you probably never noticed because another fillText() call would use the font as soon as it's loaded.

Regarding performance: We did a lot of profiling, and rendering text with drawImage is definitely much faster than calling fillText() and strokeText() over and over. That's for the common use case of rendering text for labels of course. What you're doing would probably be better solved with an ol.style.Icon that uses an SVG image with the symbol you want to use.

**Comment by ahocevar** [comment]
Looking at the new code in `ol/render/canvas/textreplay`, I see that it should be doable to apply the scale before pre-rendering instead of afterwards. If you are willing to create a pull request, that would be welcome.

**Comment by ogo-adp** [comment]
Yes I use a web font. With ol 4.3 rendering is ok 1/2 second after application load, ans stays ok forever, but not with ol 4.4. I then assume there is an image cache. I don't know any way to let ol know that the font is ready (we call changed() on feature when changing scale but it does not seem to do anything on ol 4.4) ? And provided that we use a lot of different scales and rotations, we could end up with a gigantic number of cached images, could we ?

Regarding performance, I'm a performance nut myself (chrome profiler is my second home :) ) and have done everything possible to make my application as fast as possible (and succeeded on this). This is a complex app with a lot of objects on screen (a one year project). I didn't find any bottleneck with fillText (my understanding on this is that text drawing is done by the gpu on any modern browser -even on canvas- but maybe i'm wrong).

**Comment by ahocevar** [comment]
Yes, there is an image cache. To track the loading state of a web font, something like https://www.npmjs.com/package/webfontloader can be used. We could also clear the image cache when `changed()` is called on the layer, if that helps.

Different rotations will not impact the number of cached text images, because images are pre-rendered without rotation.

**Comment by ogo-adp** [comment]
Sorry to say that, but in my opinion, the problem with web font loading is a bug in ol. This could break many applications. It was working fine before (as expected) because fillText was called during each render, so as soon as the font was loading the rendering was correct forever. But now, because of the cache (a technical detail unknown to the developper using ol), wrong images renders are put in cache before the font is ready, and moreover i see no way to clear the cache. Having to use a special package to wait for font loading feels convoluted.

There is also a problem with ol 4.4 on Safari (at least on ios 10). When rendering features with high magnification (or high scale if you want), safari will stutter and then completely crash. It was running fine before.

I also did some performance profiling in chrome on Windows. For that we can reproduce an exact same load on our application before and after upgrade and measure it with profiler. Here are the results :

ol 4.3.4 : 
 - rendering + painting : 761ms
 - fillText : 14.0% cpu -> we don't use stroke on text, so only fillText is called
 - drawImage : 4.5% cpu

ol 4.4.1 :
- rendering + painting : 821ms
- drawImage : 16.2% cpu

I don't see here the new version being "much faster". drawImage() consumes 16.2% vs fillText+drawImage at 18.5% but globally the cost of rendering + painting is a bit worse than before. So no gain here at least for us.

**Comment by ahocevar** [comment]
#7340 fixes the problem that text with wrong fonts is stored in the label cache.

**Comment by ahocevar** [comment]
#7346 fixes the scale issue.

**Comment by ogo-adp** [comment]
Many thanks for all your hard work on this @ahocevar 

We are using npm with our application. Is there any possibility to get the compiled ol.js and ol-debug.js to make some tests with app instead of a codepen ?

**Comment by ahocevar** [comment]
I just updated the master website with the changes in #7346, so you will have an updated https://openlayers.org/en/master/build/ol.js and https://openlayers.org/en/master/build/ol-debug.js in a few minutes.

**Comment by ogo-adp** [comment]
Did some tests with the new version.

The scale issue fix does work (#7346)

However fix #7340 does not appear to work. I'm still getting the wrong symbol because the font is not yet loaded

**Comment by ahocevar** [comment]
#7340 is not in master yet, so it's not included in the build I pointed you to.

**Comment by ogo-adp** [comment]
Oups yes, did not read your previous response correctly.
