### ISSUE TITLE
ol.layer.Raster rendering issue with ol >= 4.4.0

### ISSUE THREAD

**Issue by thhomas** [openlayers/openlayers#7335]
The ol.layer.Raster does not display at start anymore. It renders when zooming.
Can be seen on [color manipulation example](http://openlayers.org/en/latest/examples/color-manipulation.html). At start, no layer is displayed on map but when zooming in, the layer renders.

**Comment by tschaub** [comment]
`git bisect` shows that 16e6d137004d8797463d25b6c7a0ecd6c440bccd is the first bad commit.
