### ISSUE TITLE
4.4.0 Content Security Policy issue with generated inline png content

### ISSUE THREAD

**Issue by heikkipora** [openlayers/openlayers#7336]
4.4.0 (and 4.4.1) cause the browser to report a Content Security Policy violation for directive "img-src 'self'" (when CSP is enforced)

Likely introduced by PR https://github.com/openlayers/openlayers/pull/7136
and similar to an already solved issue https://github.com/openlayers/openlayers/issues/6934

**Comment by ahocevar** [comment]
Thanks for reporting this. I created #7337, which should fix it.

**Comment by heikkipora** [comment]
That was quick, thanks! 👍
