### ISSUE TITLE
Tiles not loaded for VectorTile source with custom TileGrid and tile loader

### ISSUE THREAD

**Issue by bobobobo** [openlayers/openlayers#7342]
I have an application that has a VectorTile layer with custom tile url and loader functions. The layer is created using the following code.

```
ol.layer.VectorTile({
    visible: true,
    extent: extent,
    source: new ol.source.VectorTile({
      format: new ol.format.MVT(),
      projection: 'EPSG:3006',
      tileGrid: new ol.tilegrid.TileGrid({
        origin: [218128, 6126002],
        resolutions: [4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8, 4, 2, 1, 0.5]
      }),
      tilePixelRatio: 2,
      cacheSize: 32,
      overlaps: false,
      tileUrlFunction,
      tileLoadFunction
    })
  })
}
```

This works in Openlayers 4.1.1 but after upgrading version 4.2.0 or later the tiles are not loaded. After some investigation I found that this seems to be caused by `ol.source.VectorTile.prototype.getTileGridForProjection` that is used by `ol.source.Tile.prototype.getTileCoordForTileUrlFunction`. The TileGrid returned from `getTileGridForProjection` does not match the resolutions on the TileGrid passed to the source which causes Openlayers to try to load tiles for resolutions that I don't have tiles for (ie the tile url function returns undefined). If I override `getTileGridForProjection` on my source and have it return the source TileGrid and then all the tiles are loaded correctly. 

I am not sure how this should be fixed but I am happy to create a pull request if someone could point me in the right direction.

**Comment by ahocevar** [comment]
OpenLayers now uses different tile grids for loading and displaying vector tiles. Are you currently using v4.4.x? Because there were some issues with the new loader initially after the change. Also, did you check the release notes for 4.3 and 4.4? The `tileLoadFunction` needs to be changed, and there is no `tilePixelRatio` option any more.

Please report back here if following the upgrade notes does not fix your issue. In that case it would be good to see your code live in a codepen.

**Comment by bobobobo** [comment]
I am using 4.4.1 and I have changed the `tileLoadFunction`. The problem is that the `tileLoadFunction` is not called at all if `tileUrlFunction` returns undefined for any tile.

**Comment by ahocevar** [comment]
That's expected, but only for tiles that the `tileUrlFunction` returns `undefined` for. Do you also use a custom `tileUrlFunction`? Can you show the issue in a codepen?

**Comment by bobobobo** [comment]
Since all my tiles are in an offline store I cannot share them. I have tried to replicate the problem in codepen: https://codepen.io/anon/pen/jGxzLK?editors=1010 . The example does not have any real map data, it only logs calls to tileUrlFunction and tileLoadFunction.

The example has an object which contains all tiles available (in our case downloaded offline). The tileUrlFunction returns undefined if the tile is unavailable offline. The tileLoadFunction only logs that is has been called.

If I run this example with Openlayers 4.1.1, the tileUrlFunction is called for tile 6/27/55 (found) and then the tileLoadFunction is called.

With Openlayers 4.4.1 it tries alot of other tiles that is not found:
tile not found 11/1058/-665
tile not found 6/27/54
tile found 6/27/55
tile not found 6/28/54
tile not found 6/28/55

but tileLoadFunction is never called even though tile 6/27/55 is found

I hope this helps you understand my problem.

**Comment by ahocevar** [comment]
Thanks for the test case. I managed to come up with #7349, which fixes the issue. It took me a while to find the problem, and I'm glad you reported this issue because this was a mean and hard-to-find bug that made debugging vector tile loading a challenge.
