### ISSUE TITLE
"full viewport" sized images not being requested on initial and outer zooms for sources based on ol.source.Image

### ISSUE THREAD

**Issue by jumpinjackie** [openlayers/openlayers#7348]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

This is a problem I am experiencing with the MapGuide `ol.source.ImageMapGuide` source, but that is a bit hard to demonstrate at the moment due to #7325, but the problem is equally observable with the `ol.source.ImageWMS` and possibly any other source that inherits from `ol.source.Image`

For the purpose of explaining the problem, load the [Single Image WMS example](http://openlayers.org/en/latest/examples/wms-image.html?q=wms)

Inspect the WMS request made in your browser dev tools, if you check the size of the image in the WMS request, you can see that OL has crunched the request for an image of this size below:

![wms_image_size](https://user-images.githubusercontent.com/563860/31447424-adaff946-aeed-11e7-9bee-58dcdd881e0a.png)

As you zoom out, the image in the WMS GetMap request gets smaller and smaller. MapGuide has this same observable problem, but where it is probably harmless for WMS it affects MapGuide as we have certain viewer operations/features that rely on the assumption that [requested map image size = map viewport size] and this kind of behavior is breaking those viewer operations/features due to this faulty assumption.

Is there a way to instruct OpenLayers to **not do this** and always request full viewport sized images at all possible zoom levels?

**Comment by ahocevar** [comment]
Just don't set an `extent` on the layer.

**Comment by jumpinjackie** [comment]
Yep, that was indeed the case. Problem solved.
