### ISSUE TITLE
Read fees / access constraints (ol.format.WMTSCapabilities)

### ISSUE THREAD

**Issue by dbretschneider** [openlayers/openlayers#7373]
In our openlayers application the user has to be informed about fees / access constraints (e.g. print output) dynamically.
For WMS everthing works fine. For WMTS only _ServiceType_, _ServiceTypeVersion_ and _Title_ are received.

Any plans to extend wmts parser?

openlayers version: 4.4.2
demo url: https://jsfiddle.net/va83172c/
service url: https://www.wmts.nrw.de/geobasis/wmts_nw_dop20/1.0.0/WMTSCapabilities.xml

> We are aware that the current service capability isn't valid against ogc wmts schema (wrong attribute KeywordList). We are working on that issue.
> With valid capability document (on local webserver) the parser can't read fees / access constraints too.

**Comment by fredj** [comment]
@dbretschneider see #7375

**Comment by dbretschneider** [comment]
Thanks for fast reply and fix.
