### ISSUE TITLE
Openlayer 4.4.1 GeoJSON VT mapInteraction select problem

### ISSUE THREAD

**Issue by antochoy** [openlayers/openlayers#7374]
Hi,  I have project

I try OL 4.4.1 with geoJSON VT,
1. but when select feature only partially, not all
2. many duplicate label

example http://124.40.255.210:8111/gis_v2/
example selectlayer: Batas Kecamatan Sukoharjo

please help me

thank you

![okrs150uqh_bdcdmy_ryug](https://user-images.githubusercontent.com/8154322/31765215-e6063778-b4ed-11e7-86b8-a4cb59f98b4b.png)
![t02311t-s6ujexng1iu4fa](https://user-images.githubusercontent.com/8154322/31765327-33c74cea-b4ee-11e7-8676-a84047af3f04.png)

**Comment by ahocevar** [comment]
This is all expected and due to the nature of vector tiles.

You can improve selection by relying on `ol.Feature#getId()` instead of using `ol.interaction.Select` if same features have same ids on different tiles. You could avoid duplicate labels by adding label points to your vector tiles, instead of labeling polygons directly.

**Comment by antochoy** [comment]
Can you give me example using improve selection by relying on ol.Feature#getId()

**Comment by ahocevar** [comment]
See https://github.com/openlayers/openlayers/issues/5248#issuecomment-211878312.

**Comment by antochoy** [comment]
I have this:

`        vectorLayer[iddata] = new ol.layer.VectorTile({
            source: sumber,
            style: function(feature, resolution) {
                var myStyle = new ol.style.Style({
                    placement: "point",
                    textAlign: "center",
                    textBaseline: "middle",
                    fill: new ol.style.Fill({
                        color: feature.get("fill_color")
                    }),
                    stroke: new ol.style.Stroke({
                        color: feature.get("stroke_color"),
                        width: 1
                    }),
                    text: new ol.style.Text({
                        text: resolution < 30 ? feature.get(datalabel) : "",
                        font: "12px Arial",
                        fill: new ol.style.Fill({
                            color: "#F7DA1A"
                        }),
                        stroke: new ol.style.Stroke({
                            color: "#333",
                            width: 2 
                        }),
                        textAlign : "center",
                    })
                });
                return myStyle;
            }

        });`

**Comment by zhang90030** [comment]
@antochoy, you should add the code in singleclick event. 
`vectortileLayer.change();`
The change method will render again.
