### ISSUE TITLE
Openlayers development

### ISSUE THREAD

**Issue by exotfboy** [openlayers/openlayers#7384]
Hi, I am working on a project based on openlayer4, and I need to customize some `layer` `feature` and etc, now I have not found callbacks like `onAdd` `onRemove` for these classes.

For example, when I create a new `Layer`, I would like to set some options before it is added to the map, since these options can only be retrieved from the `Map` object. However I have not found some methods like `onAdd` `onRemove` or something else like `Leaflet` does.

Additionally
, I would like to build my application with openlayers together just like this [tutorial](http://openlayers.org/en/latest/doc/tutorials/closure.html).

After setup, I meet some problems:

1 Export certain variables 
Openlayer itself export `ol` namespace, and my app export `app`  package, and how to remove `ol`?

2  API methods keeping
Closure library is used to package the application, I am afraid some api may be obfuscated.

However when I dig into ol's source codes:

```
/**
 * Get the layer source.
 * @return {ol.source.Source} The layer source (or `null` if not yet set).
 * @observable
 * @api
 */
ol.layer.Layer.prototype.getSource = function() {
  var source = this.get(ol.layer.Property.SOURCE);
  return /** @type {ol.source.Source} */ (source) || null;
};
```
As show, the `getSource` is a api method, it is not compressed after release. I noticed there are some annotations, but which take effect during the building?

**Comment by ahocevar** [comment]
Building application and OpenLayers together with closure-util is a dead-end road, and will be discontinued in OpenLayers 5.x.

You should consider using the [ol](https://npmjs.com/package/ol) package. No need to worry about namespaces or exports. Just use mainstream bundlers like Webpack, and treat OpenLayers like any other JavaScript library as a mere dependency of your ES2015 application.

If you are not ready yet for ES2015, you can also follow [this tutorial](https://openlayers.org/en/latest/doc/tutorials/browserify.html) and work with CommonJS.

**Comment by exotfboy** [comment]
How about the layer extends?

**Comment by ahocevar** [comment]
All possible, but if what you are extending is not part of the API, you’re doing it at your own risk. For hooks on adding and removing layers, see ol.Collection‘s events.

**Comment by exotfboy** [comment]
@ahocevar  Thanks, but I am still not sure about the working mechanism of ol. After read the ol.Collection's event, not clear enough.

Is there a way for the `layer` to know that it is being add to a map?

**Comment by marcjansen** [comment]
The map has a central collection of layers, which is an ol.Collection, which in turn can notify listeners of changes. HTH

**Comment by exotfboy** [comment]
@marcjansen  It means that the map can receive the events for layers adding to the map, but how can a layer know that it is being added to a map and get the map reference ?

**Comment by marcjansen** [comment]
>  how can a layer know that it is being added to a map

@exotfboy I don't think it can right now. Nonetheless I do not think this is the right place to ask such questions.

**Comment by exotfboy** [comment]
I think this is the right place for asking this kind of questions since this is not related how to use the standard ol apis, instead we need to enhance the apis.

It is rather  a common requirement for a layer or something else to do some initialization job  when added to map
