### ISSUE TITLE
view.animate + overlay autopan = error

### ISSUE THREAD

**Issue by marcodelpercio** [openlayers/openlayers#7385]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [X] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [X] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [X] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [X] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Hi,

We're trying to combine view.animate and an overlay popup with the latest openlayers version 4.4.2 (at the moment). Let me explain the scenario:
We have markers in various points on the map, when the user clicks on a marker, wherever it is located the view animates scrolling vertically to make sure that the maker is vertically centered (i.e. the new center of the map is: the current longitude of the current map center, and the latitude of the marker clicked). Once the view is vertically centered on the marker, a popup overlay opens eventually with autopan. 
So if the marker was close to the very top of the view it auto-pans a little bit down to make room for the overlay,... if the marker was close to the very right of the view it auto-pans a little bit to the left to make enough room for the overlay.... etc. etc. You got the idea.

I have created a codepen based on your latest example of popup Overlay [http://openlayers.org/en/latest/examples/popup.html](url) which has autopan active. Instead of having markers on the map just click on a point and you'll see the described behaviour. The view will pan vertically to center on the clicked point latitude and then the popup overlay will open eventually with auto-pan to make enough room.
The overlay setPosition() call is inside the callback for view.animate() when the animation completes, so in theory the popup auto-pan should kick-in only when the view.animate() is complete.
It all seems to work but try to click next to the very right boundary of the view (or next to the very left boundary of the view) and you'll see that the auto-pan does not happen and a Javascript error comes up in the console.
More specifically the error is the following:
``` 
Uncaught TypeError: Cannot read property 'length' of null
    at ol.View.updateAnimations_ (ol-debug.js:16002)
    at ol.View.animate (ol-debug.js:15947)
    at ol.Overlay.panIntoView_ (ol-debug.js:31407)
```
See screenshot for details
![panintoview_error](https://user-images.githubusercontent.com/7857757/31878231-4c570c9c-b7d1-11e7-9a4e-65640528f1e2.png)

The codepen is the following: [https://codepen.io/marcodelpercio/pen/zEQOER](url)

I hope it helps
Many thanks

**Comment by kedaranmol** [comment]
@marcodelpercio 
I just had a similar situation and I fixed the issue by wrapping the **setPosition** in a **setTimeout** call, this must be done in all places where you use **setPosition**. Do something like this,
`function (completedNormally) {
      setTimeout(() => {
        overlay.setPosition(coordinate)
      }, 0)
    }`

P.S: This is just a workaround till somebody can dig into the issue and find a proper fix.

**Comment by marcodelpercio** [comment]
Thanks kedaranmol but...I prefer not to use timeoutbased workaround
