### ISSUE TITLE
ol.proj.equivalent function

### ISSUE THREAD

**Issue by flexf1t** [openlayers/openlayers#7386]
Hello,
I've noticed that ol.proj.equivalent function does not compare some projection options/params, for example axisOrientation and extent. 
So it leads to this behavior:
`var proj = new ol.proj.Projection({ code: "EPSG:3857" });`
`var proj_neu = new ol.proj.Projection({ code: "EPSG:3857", axisOrientation: 'neu' });`
`ol.proj.equivalent(proj , proj_neu) // -> true`
This behavior is not what i was expecting and it breaks my application.
I think it is not good. May be i just miss something?
So, in my opinion it has two solutions:
1. add some new comparsions to the existing function ol.proj.equivalent (it works fine for me):
`var equalAxis = projection1.getAxisOrientation() === projection2.getAxisOrientation();`
`var equalExtent = projection1.getExtent() === projection2.getExtent();`
`var equal = equalUnits && equalAxis && equalExtent;`
2. add some new comparsions to the new function (for example ol.proj.equivalentHarder, etc) 

Thanks

**Comment by fredj** [comment]
yes, it make sense to also compare the extent and the axis orientation

**Comment by fredj** [comment]
see #7388
