### ISSUE TITLE
moveend event triggered at the map init

### ISSUE THREAD

**Issue by timedata** [openlayers/openlayers#7387]
Hi we just update our project to latest version (4.4.2).

And something happened wrong , then we realized moveend event triggered at the start (map init).
Its happening sometimes not all times.

Its not happened before (4.2.0), i think its new.

**Comment by timedata** [comment]
HaritaSabitleri.projection3857View = new ol.View({
            extent: [1551854.4910793854, 3529596.2228973815, 6248145.508920615, 5870403.7771026185],
            projection: 'EPSG:900913',
            center: [3900000, 4700000],
            zoom: 6,
            maxZoom: HaritaSabitleri.maxZoom,
            minZoom: HaritaSabitleri.minZoom
        });

this is the init view.

HaritaSabitleri.map = new ol.Map({
            layers: [
                HaritaSabitleri.vectorLayer,
                HaritaSabitleri.cosmeticLayer
            ],
            target: divId,
            renderer: 'canvas',
            view: HaritaSabitleri.projection3857View,
            controls: ol.control.defaults({
                attribution: false
            }).extend([
                new ol.control.ScaleLine({units: 'metric'}),
                HaritaSabitleri.overViwMap,
                HaritaSabitleri.mousePositionControl,
                new HaritaSabitleri.customLayerSwitcherControl()
            ])
        });

map init

HaritaSabitleri.map.on('moveend', OpenLayersLib.mapMoved);

moveend event

**Comment by cs09g** [comment]
This has been happened from older version. but I'm not sure triggering `moveend` at map initialization is correct behavior.

**Comment by nboisteault** [comment]
Is `moveend` event triggered at initialization in OpenLayers 9?

**Comment by ahocevar** [comment]
Yes it is, and it's consistent.
