### ISSUE TITLE
Zoomify source should support custom TileGrid extents

### ISSUE THREAD

**Issue by lasselaakkonen** [openlayers/openlayers#7390]
Zoomify source always sets the TileGrid extent as `[0, -size[1], size[0], 0]`:
https://github.com/openlayers/openlayers/blob/eeb20cf/src/ol/source/zoomify.js#L80-L85

When only using OpenLayers 4 this is not a issue, but when migrating from OpenLayers 2 this causes issues. I have not used OL3, so I don't know how Zoomify works there. Maybe there is a reason for it, but OL4 places the Zoomify tiles below the X axis, while OL2 placed the tiles above the X axis. Meaning coordinates set in OL2 do not match to coordinates in OL4.

By giving the Zoomify source the extent as `[0, 0, size[0], size[1]]`, coordinates would be in the first quadrant, instead of the fourth. This seems to work, but are there some other consequences of changing the Zoomify source TileGrid extent?

**Comment by lasselaakkonen** [comment]
Can I send a pull request for this?

**Comment by ahocevar** [comment]
Yes, please send a pull request.
