### ISSUE TITLE
Snap is inaccurate

### ISSUE THREAD

**Issue by MickBis** [openlayers/openlayers#7396]
Hi guys,

I have two rectangles, where one of them I have snapped each corner to the other rectangle. I would expect the two rectangles to be identical, but the coordinates vary slightly as seen from here:

POLYGON((
10.167364554245518 56.18787846260361,
10.168360269808542 56.18838480140357,
10.167417382292504 56.188958954664315,
10.16642166672948 56.18845262344044,
10.167364554245518 56.18787846260361))

POLYGON ((
10.167364554245516 56.187878462603607,
10.168360269808542 56.188384801403572,
10.167417382292504 56.188958954664315,
10.16642166672948 56.18845262344044,
10.167364554245516 56.187878462603607))

I have tried with Openlayers 4.4.2 and 3.19.1

Kind regards,
Mick

Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [X ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [X] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [X] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by mprins** [comment]
Those numbers seem equal within the limits of  the IEEE 754 Standard for storing numeric values that JavaScript adheres to.

**Comment by MickBis** [comment]
I guess you're right.

It was causing me to have some issues with finding points on the lines/intersections. I dealt with it by rounding up to 9 digits, since I don't need any more precision than that.
