### ISSUE TITLE
Edge tile stretching for XYZ source

### ISSUE THREAD

**Issue by yurykovshov** [openlayers/openlayers#7400]
I have created a simple example with XYZ source, which shows a sample image from DeepZoom pyramid: https://jsfiddle.net/q1upru60/1/
It uses last version 4.4.2.
As you can see the tiles on the edges (right and bottom are stretched to fill the 256*256 tilesize). Which is incorrect IMO, because DeepZoom format has a cropped tiles on edges.

BUT I found that until the 3.19 version there was a fine behavior: https://jsfiddle.net/57L2st7d/1/
As you can see everything is fine, and OL doesn't stretch the tiles on edges.
Starting from 3.20 tiles will be stretched...

If my code is correct - Is it a bug or is it an intentional feature?

Thanks!

PS. [Original image](https://embed.smartzoom.com/sample_files/sample.jpg)
PSS. Right now we use Zoomify source to show DeepZoom images. But with Zoomify source you cant specify different tile sizes (only 256). That's why we started to try out the XYZ source.

**Comment by ahocevar** [comment]
It's not a bug - the XYZ source simply assumes a fixed tile size. You should be using the Zoomify source. A pull request to make the tile grid of the Zoomify source configurable would be appreciated.

**Comment by yurykovshov** [comment]
#7379

**Comment by yurykovshov** [comment]
Ok, thanks.
I will reference the links to Custom tile size for Zoomify source:
Issue #6608
Pull request #7379
