### ISSUE TITLE
change:resolution fires multiple times

### ISSUE THREAD

**Issue by afogelberg** [openlayers/openlayers#7402]
change:resolution fires multiple times when zooming. For example:
```
map.getView().on('change:resolution', function(e) {
  console.log('Changed resolution');
});
```
will print 'Changed resolution' about ten times every time zoom level is changed. See for example  https://codepen.io/parsifal/pen/bYNaKB

The problem appears from ol 3.20.0. 

Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [ x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
This change comes from the new animation framework and from the improved wheel zoom. OpenLayers is now much more loosely bound to zoom levels, and the view always has the currently rendered resolution.

What is your use case for only wanting that event to fire once? You could use the map's `moveend` event instead.

**Comment by ahocevar** [comment]
Ok, then change your code to
```js
      function onResolutionChange(evt) {
        if (view.getAnimating()) {
          return;
        }
        var mapZoom = parseInt(view.getZoom(), 10);
        if (mapZoom > clusterMaxZoom) {
          source.setDistance(0);
        } else if (mapZoom <= clusterMaxZoom) {
          source.setDistance(clusterDistance);
        }
      }
```
This will ignore the event until the zoom animation has stopped.

**Comment by afogelberg** [comment]
It doesn't seem to work after all. The view is animating each time the event is fired, thus the cluster distance will never be set. I could add a flag for the animation and execute the function when the animation is finished but it seems like an ugly workaround.

**Comment by ahocevar** [comment]
Then use the map‘s moveend event and re-cluster only when the resolution is different than the previous one.

**Comment by afogelberg** [comment]
Yes, using `moveend `in combination with `movestart` I can make it work, as in below. Considering how `change:resolution` behaves since the new animation framework, should it still be included in ol?
```javascript
      var clusterDistance = 60;
      var clusterMaxZoom = 4;
      map.on('movestart', onMovestart);

      function onMovestart(evt) {
        var mapZoom = parseInt(view.getZoom(), 10);
        map.once('moveend', function(evt) {
          var currentZoom = parseInt(view.getZoom(), 10);
          if (currentZoom !== mapZoom) {
            if (mapZoom > clusterMaxZoom) {
              options.source.setDistance(0);
            } else if (mapZoom <= clusterMaxZoom) {
              options.source.setDistance(clusterDistance);
            }
          }
        })
      }
```

**Comment by ahocevar** [comment]
Knowing when the resolution changes, even during animations, makes sense in different contexts. I think one improvement would be to fire a last `'change:resolution'` event when the view is no longer animating.

**Comment by afogelberg** [comment]
> I think one improvement would be to fire a last 'change:resolution' event when the view is no longer animating

Sounds good to me

**Comment by JoshMcCullough** [comment]
Definitely agree that a final event after animating completes is needed!

**Comment by ahocevar** [comment]
Use the map's `moveend` event for that instead.

**Comment by JoshMcCullough** [comment]
Yes, I'm using it now but still suggest making `change:resolution` and other events have a final post-animation event fired. Thanks!
