### ISSUE TITLE
Tile.XYZ "stretches" cropped tiles from Deep Zoom format

### ISSUE THREAD

**Issue by martinweihrauch** [openlayers/openlayers#7403]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [X] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

On OL3, you could use the "Tile.XYZ" function to present Deep Zoom images. In the latest version, OL4 stretches the "cropped" tiles of the borders.
Explanation: On the outer right and bottom border, tiles may be smaller than e. g. 256 x 256, if the image cannot be divided by 256 evenly. These tiles are now "stretched" out / resized to 256, which makes the images unusable.

The Zoomify function cannot be used for tiles other than 256 x 256 (e. g. 192), so is also not usable.

We would be delighted, if that issue could be fixed.

Martin

**Comment by ahocevar** [comment]
#7379 added support for custom tile sizes to `ol.source.Zoomity`. So you should now be able to use that.

**Comment by hackermd** [comment]
I experience this issue also with the base class ``ol.source.TileImage`` in the latest version ``4.6.4``. This used to work in the past with version ``3.14.2``. IMO the base class shouldn't assume that all tiles have the same size. Is this behaviour intended?

Unfortunately, I can't use ``ol.source.Zoomify``, because I require a custom URL without the Zoomify ``{TileGroup}`` placeholder. Any suggestions for a workaround?

**Comment by ahocevar** [comment]
You could use `#setTileUrlFunction()` to set a custom tileUrlFunction.

**Comment by hackermd** [comment]
Thanks @ahocevar for your immediate reply! Using `setTileUrlFunction` works!

**Comment by lromor** [comment]
Sorry for necrobumping, but for this workaround doesn't work anymore. Right now it is required to pass the url property during instantiation of the Zoomify source. Changing it afterwards using `setTileUrlFunction` doesn't seem to work for me.
