### ISSUE TITLE
Modify interaction "modifyend" event, return all feature, not only the modifyed feature

### ISSUE THREAD

**Issue by ChouGary** [openlayers/openlayers#7404]
when i modify one feature, Modify interaction "modifyend" event
return all feature in source, not only the modifyed feature.

https://codepen.io/anon/pen/qVdEdo
var modify = new ol.interaction.Modify({
  source: vector.getSource()
});
modify.on('modifyend',function(evt){
console.log(evt.features.getArray().length);
})
![image](https://user-images.githubusercontent.com/8294943/32208849-1bbbc602-be40-11e7-9989-93f713b2b412.png)
 it's difficult to get modifyed feature in 179 features

no get modifyed feature method in api
http://openlayers.org/en/latest/apidoc/ol.interaction.Modify.html

**Comment by ChouGary** [comment]
i find another way,this issue can close
set every feature on('change') event at modifystart

https://github.com/openlayers/openlayers/blob/f6eeee37d2e4b13f9ff65acb6b671d9d4c35b505/src/ol/interaction/modify.js#L258
line 258 ol.events.listen(feature, ol.events.EventType.CHANGE,
      this.handleFeatureChange_, this);
will trigger change event

set every feature un('change') event at modifyent

**Comment by kuige** [comment]
Yes, return all the features is strange, I have the same problem !

**Comment by RyanRutkin** [comment]
Please re-open this issue. This issue still exists, and the Feature.on('change') workaround suggested is ugly.

**Comment by kou2014** [comment]
here is a sample code.
`let modifyedFeatures = [];
let geometryChangeListener;
modifyInteraction.on('modifystart', (e) => {
  modifyedFeatures.length = 0; 
  const features = e.features;
  features.forEach((feature) => {
	geometryChangeListener = feature.getGeometry().on('change', () => {
	  if(modifyedFeatures.indexOf(feature) === -1){
		  modifyedFeatures.push(feature);
	  }
	});
  });
});

modifyInteraction.on('modifyend', () => {
  if (geometryChangeListener) {
	unByKey(geometryChangeListener);
	geometryChangeListener = null;
  }
});`
