### ISSUE TITLE
LineString styles 

### ISSUE THREAD

**Issue by kardash** [openlayers/openlayers#7405]
How can I create a style of line in OpenLayers.js like below?
![default](https://user-images.githubusercontent.com/10165520/32226556-8158ca6c-be51-11e7-85f8-a43a1b85e33b.PNG)

**Comment by icholy** [comment]
Please ask usage questions on StackOverflow: https://stackoverflow.com/questions/tagged/openlayers

**Comment by kardash** [comment]
I already find solution for this: https://jsfiddle.net/kardash/mxour67h/5/

**Comment by ahocevar** [comment]
Thanks for sharing the solution!
