### ISSUE TITLE
Fire another change:resolution after animation

### ISSUE THREAD

**Issue by afogelberg** [openlayers/openlayers#7409]
Since the new animation framework in ol 3.20, multiple change:resolution is fired. Each change:resolution is fired during the view animation and thus it's not possible to skip all events and listen to the change after the animation has finished.

As suggested in #7402 this could be improved by firing another change:resolution after the animation has finished.

**Comment by fredj** [comment]
And it should also be the case for `change:rotation` and `change:center`
