### ISSUE TITLE
`ol.interaction.Interaction.handleEvent` documented misleadingly

### ISSUE THREAD

**Issue by glen-nu** [openlayers/openlayers#7413]
I refer to [Interaction](http://openlayers.org/en/latest/apidoc/ol.interaction.Interaction.html), the paragraph that reads:

> Method called by the map to notify the interaction that a browser event was dispatched to the map. The function may return `false` to prevent the propagation of the event to other interactions in the map's interactions chain. Required.

I assumed this would only happen if the function explicitly returned `false`, i.e. the way it does in some other libraries like [Lodash](https://lodash.com/docs/4.17.4#forEach) (and jQuery I believe?). 

I tried to create my own interaction to handle keyboard events and failed to specify a return value. This actually stopped event propagation because the return values were evaluated on falsey-ness rather than explicitly being `false`. I believe the line is [here](https://github.com/openlayers/openlayers/blob/master/src/ol/pluggablemap.js#L859).

If this is intended, it would be good for the docs to describe this behaviour by referring to the return value as falsey rather than `false`

**Comment by ahocevar** [comment]
Thanks for reporting this issue. A pull request that fixes the documentation would be greatly appreciated.

**Comment by fredj** [comment]
fixed with #7426
