### ISSUE TITLE
setResolution doesn't parse variable

### ISSUE THREAD

**Issue by sebalaini** [openlayers/openlayers#7415]
When you use the function setResolution() and you pass a number inside an array it doesn't accept this number and broke your Resolutions array when you move the zoom.

I created a cookie function to remember the last position and zoom with centerOn and setResolution but it seems that setResolution doesn't accept that number.

I take the number and go to that resolution level but when you move the zoom level the map disappears.

The solution was parseFloat that number from the array and it works.

    view.centerOn( [setPos[0], setPos[1]] , map.getSize(),  [($(window).innerWidth()/2), ($(window).innerHeight()/2)]);

    map.getView().setResolution(parseFloat(setPos[2]));

**Comment by ahocevar** [comment]
What do you store in the cookie? Also note that `View.fit()` is more appropriate than `View.centerOn()` in your case.

**Comment by sebalaini** [comment]
sorry for the delay.... actually I take the resolution from the session storage, this is what inside: 507726.29125178396,182835.0562589193,2.8
I suppose they are numbers, or at least the coordinate works perfectly without need to use parseFloat()

**Comment by ahocevar** [comment]
So I assume we can close this? The expected type for coordinates is always number, not string.

**Comment by sebalaini** [comment]
we can close, I solve the problem. I simply don't understand why the coordinates work and the resolution not, booth are taken from session storage and it quite weird that just resolution is a string and not a number. There is some difference in the core?
