### ISSUE TITLE
textAlign 'start' and 'end' are interchanged

### ISSUE THREAD

**Issue by mariowilde** [openlayers/openlayers#7419]
As of v4.4.0 there is a bug in the ol.style.Text textAlign option. 'start' and 'end' each have the effect that would be expected from the other one.

Codepens:
v4.4.2: https://codepen.io/anon/pen/wPMNxW
v4.3.4: https://codepen.io/anon/pen/RjrvYb

**Comment by jsikorski** [comment]
We have noticed the same issue.

**Comment by ahocevar** [comment]
Previously, `start` and `end` depended on the text direction. Workaround: use `left` and `right` for LTR text, and `start` and `end` for RTL text (currently not supported, see #7367).
