### ISSUE TITLE
Text style using FontAwesome font broke in 4.4.0+

### ISSUE THREAD

**Issue by jtpetro** [openlayers/openlayers#7424]
We are currently trying to upgrade from 4.2.0 to 4.4.2 and we are having a problem displaying a text style using the font awesome font. Below are CodePens showing this working in 4.3.4 and not working in 4.4.0. 

[CodePen using OL 4.3.4](https://codepen.io/jtpetro/pen/EbyJwx)
[CodePen using OL 4.4.0](https://codepen.io/jtpetro/pen/bYeKWP)

We have also tried building master this morning and testing locally to see if #7340 were to allow the font to render.

**Comment by ahocevar** [comment]
You have a typo in the value for the `textBaseline` property. It's supposed to be `'bottom'`, not `'Bottom'`.

**Comment by jtpetro** [comment]
I apologize for cluttering up the issue board for this. I wasn't even looking at that line since it previously worked. Thanks for the help!
