### ISSUE TITLE
Tiles not loading on Android Emulator

### ISSUE THREAD

**Issue by TheRDavid** [openlayers/openlayers#7427]
This issue has already been reported, but closed here: https://github.com/openlayers/openlayers/issues/6500
without being resolved.

Across Openlayers versions (including the latest), android devices and android os versions, Openlayer Maps do not load tiles on Android Emulators in Android Studio (both 2.3.3 and 3).
This does however only occur on Windows machines.
There is no error output, neither on the android-, nor the remote chrome console. I guess this may not be an Openlayers, but an emulator-bug, but I felt it was worth mentioning.

Again, the issue only occurs on emulated Android devices on Windows, it works fine on real devices and Mac- and Linux machines.

![image](https://user-images.githubusercontent.com/8162333/32490302-93a6b09a-c3aa-11e7-85e9-dc7a35e63b33.png)

Cheers, David

**Comment by fredj** [comment]
Do you have any error reported ?

**Comment by TheRDavid** [comment]
Yes, sorry, I just spotted them now in Logcat:

5638-5704/com.example.me.myapplication E/eglCodecCommon: glUtilsParamSize: unknow param 0x000088ff

6124-6199/com.example.me.myapplication E/EGL_emulation: tid 6199: eglChooseConfig(840): error 0x3004 (EGL_BAD_ATTRIBUTE)

6124-6199/com.example.me.myapplication E/chromium: [ERROR:gl_surface_egl.cc(289)] eglChooseConfig failed with error EGL_BAD_ATTRIBUTE

6124-6199/com.example.me.myapplication E/chromium: [ERROR:gl_surface_egl.cc(441)] No suitable EGL configs found.

There are no errors in the chrome console though and I can even see that the tiles are being served - they can be displayed in the network-preview tab.

**Comment by TheRDavid** [comment]
So the last three errors also occur on a mac (where the tiles are showing).
The first seems to be due to the host gpu and is supposed to be fixable by disabling the emulated device from using the host gpu. 
I disabled it, but am still getting it afterwards. 

But I don't think it's related.

**Comment by williwasser** [comment]
I had the same problem on my emulator (API 25). Adjusting the settings for OpenGL solved the problem.
![grafik](https://user-images.githubusercontent.com/9991399/32787320-8ebdabea-c956-11e7-8b56-892dcac9e456.png)

**Comment by fredj** [comment]
@williwasser thanks for the information

**Comment by fredj** [comment]
closing

**Comment by Crewchief85** [comment]
Changing my OpenGL settings does not solve this issue for me.
