### ISSUE TITLE
Determine what to do about failing tests

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7437]
I'm seeing frequent test failures that eventually resolve themselves after restarting the Travis job.  Given how long it takes to run a CI job, it is getting pretty painful to prepare a pull request.  I'm going to use this ticket to list the failed tests as they come up:

 - [x] `Edge 15.15063.0 (Windows 10 0.0.0) ol.render.canvas ol.render.canvas.checkFont() clears the label cache for fonts that become available FAILED` (#7440)
 - [ ] `Edge 15.15063.0 (Windows 10 0.0.0) ol.View #animate() clears the ANIMATING hint when animations are cancelled FAILED
	Error: expected 1 to equal 2`
 - [ ] `Edge 15.15063.0 (Windows 10 0.0.0) ol.View #animate() completes multiple staggered animations run in parallel FAILED
	Error: expected false to equal true`
 - [ ] `07 11 2017 21:56:26.180:ERROR [launcher.sauce]: Can not start safari (macOS 10.12)
  Failed to start Sauce Connect:
  7 Nov 21:56:26 - Sauce Connect could not establish a connection.` ([build failure](https://travis-ci.org/openlayers/openlayers/builds/298793515), #7456)

We should either:
 * decide these are bugs in the tests and fix them
 * decide these are bugs in the code and fix them
 * throw in the towel and change the tests to fail less often

**Comment by bartvde** [comment]
yes saw this one as well in https://github.com/openlayers/openlayers/pull/7420#issuecomment-342116814

**Comment by ahocevar** [comment]
Found two more:

 * `Edge 15.15063.0 (Windows 10 0.0.0) ol.View #animate() clears the ANIMATING hint when animations are cancelled FAILED
	Error: expected 1 to equal 2`
 * `Edge 15.15063.0 (Windows 10 0.0.0) ol.View #animate() completes multiple staggered animations run in parallel FAILED
	Error: expected false to equal true`

**Comment by tschaub** [comment]
I've seen those as well.  I copied those up to the list at the top.  Feel free to edit and add more.

I also updated the title to reflect that our goal should really be to determine why these are failing.

**Comment by mike-000** [comment]
Another one?  Adding a checkbox to an example in #9931 doesn't seem related to ol.TileQueue

```
Chrome 77.0.3844 (Linux 0.0.0) ol.TileQueue #loadMoreTiles() works when tile queues share tiles FAILED
	Error: Uncaught Error: expected 5 to equal 0 (/home/circleci/repo/node_modules/expect.js/index.js:102)
```
