### ISSUE TITLE
Is it possible to support async create url on tileUrlFunction return?

### ISSUE THREAD

**Issue by btredback** [openlayers/openlayers#7441]
i try to defined tileUrlFunction that return promise obj. but it seems to only support return string url immediately. 
or is it my incorrect usage?
Is it necessary to support async create tile url?

**Comment by ahocevar** [comment]
That's not possible. But why don't you wait with creating and assigning the whole source until you know your tile url?

**Comment by btredback** [comment]
@ahocevar 
emmmm,i try to use cesium's google earth provider/metadata function to display in openlayer's layer.but cesium's func return is async, and then first load map is not url info,its need wait async result. I don't know if other people will meet same requirement and i haven't found a good way to solve this problem.

**Comment by ahocevar** [comment]
Like I said:
```js
var layer = new ol.layer.Tile();
function onMetadataAvailable(metadata) {
  layer.setSource(new ol.source.XYZ(
    tileUrlFunction: function(/* ... */) { /* ... */ }
  ));
}
```
