### ISSUE TITLE
Update OverviewMap after `map.getView().fit()`

### ISSUE THREAD

**Issue by opessoa** [openlayers/openlayers#7442]
Hi guys.

I have fit my map using `map.getView().fit()` and the OverviewMap is not updating.

When I click on the map, it update. If in the console debugger I call overview.render() function, it get updated too.

It's a bug? How can I work around this?

```
function fitOnLayer(layerName){
	var layer = getLayer(layerName);
	if(layer){
		if(layer.getSource().getState() === 'ready'){
			if (layer.getSource().getFeatures().length > 0) {
				map.getView().fit(layer.getSource().getExtent(), map.getSize());
				overviewMap.render();//does not update here!
				console.info(map.getView().getCenter());
				console.info(map.getView().getZoom());
		    }
		}
	}
}
```

**Comment by fredj** [comment]
looks like you're using the old api for `ol.View#fit()` see:
https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#simplified-olviewfit-api

**Comment by opessoa** [comment]
Thanks @fredj this works perfectly!
