### ISSUE TITLE
Modify Alt+Click vertex delete condition not working on Linux Ubuntu

### ISSUE THREAD

**Issue by michalseidl** [openlayers/openlayers#7463]
Hello,
I am trying to make working Alt+Click vertex delete but even in official examples this feature does not work. Ubuntu 16, Chromium, Firefox.

http://openlayers.org/en/latest/examples/modify-features.html

I tried this but nothing changed. I can only see that only altKey or singleClick is true but not both at the same time I hold Alt and click on vertex.

```
    var modify = new ol.interaction.Modify( {
      features: modifySelect.getFeatures( ),
      deleteCondition: function(event) {
        console.log('Alt', event.originalEvent.altKey);
        console.log('SClik', ol.events.condition.singleClick(event));
        return event.originalEvent.altKey && ol.events.condition.singleClick(event);
      }
    } );
```

Michal

**Comment by fredj** [comment]
Most of the window manager on Linux (unity, gnome, ...) map the `alt` key, the mouse events are not forwarded to the applications.

**Comment by michalseidl** [comment]
Thanks, I had no idea about that. Both these alternatives work as expected

```
        if (ol.events.condition.singleClick(event) && event.originalEvent.shiftKey ) {
          console.log('Shift');
          return true;
        }
        if (ol.events.condition.singleClick(event) && event.originalEvent.ctrlKey ) {
          console.log('Ctrl');
          return true;
        }
```

Michal
