### ISSUE TITLE
how do I add openlayers as a library to my oracle jet project?

### ISSUE THREAD

**Issue by vikrameswar** [openlayers/openlayers#7466]
I created an oracle jet project using ojet create, build, serve commands. Alternatively, I have also created the project using NetBeans 8.2 IDE. I am not able to add open layers as a library. I want to create a web application which would consist of maps.

**Comment by icholy** [comment]
Please ask usage questions on StackOverflow: https://stackoverflow.com/questions/tagged/openlayers

**Comment by ThomasG77** [comment]
See https://github.com/lucasjellema/jet-and-openlayers
