### ISSUE TITLE
官网中的例子draw-and-modify-features.html中，给ol.interaction.Draw类设置style属性，如var style = new ol.style.Style({       fill: new ol.style.Fill({         color: 'rgba(255, 255, 255, 0.2)'       }),       stroke: new ol.style.Stroke({         color: '#ffcc33',         width: 2       }),       image: new ol.style.Circle({         radius: 7,         fill: new ol.style.Fill({           color: '#ffcc33'         })       }),       text: new ol.style.Text({         font: '微软雅黑',         offsetX: 2,         offsetY: -18,         text: '单击画面',         scale: 1.2       })     })，绘制线和面时，会出现两个text的内容“单击画面”

### ISSUE THREAD

**Issue by liulina40** [openlayers/openlayers#7467]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [ ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by liulina40** [comment]
运行代码可以看见效果：https://github.com/liulina40/opnelayerExamples/blob/master/draw-and-modify-features.html

**Comment by exotfboy** [comment]
Can't you distinguish `title` from `content` when you post the issue? It is difficult to know exactly about what you are asking once you put them all in the title.

You'd better re-format your question.

**Comment by mynokia6680** [comment]
你要用styleFunction，因为你画面的时候其实是也用了线和点的样式

你把style替换成


    var styleFunction = function(feature){
    var styles=[];
    if(feature.getGeometry().getType()=="Point"){

    styles.push(
      new ol.style.Style({
          text: new ol.style.Text({
            font: '微软雅黑',
            offsetX: 2,
            offsetY: -18,
            text: '单击画图',
            scale: 1.2,
                  stroke: new ol.style.Stroke({
            color: '#ffcc33',
            width: 2
          }),
        })
      })
    )
  }
  else if(feature.getGeometry().getType()=="Polygon"){
    styles.push(  new ol.style.Style({

      fill: new ol.style.Fill({
        color: 'rgba(255, 255, 255, 0.2)'
      }),
      stroke: new ol.style.Stroke({
        color: '#ffcc33',
        width: 2
      }),
      image: new ol.style.Circle({
        radius: 7,
        fill: new ol.style.Fill({
          color: '#ffcc33'
        })
      }),
    })
    );
  }
  else if(feature.getGeometry().getType()=="LineString"){
    styles.push(  new ol.style.Style({

      fill: new ol.style.Fill({
        color: 'rgba(255, 255, 255, 0.2)'
      }),
      stroke: new ol.style.Stroke({
        color: '#ffcc33',
        width: 2
      }),
      image: new ol.style.Circle({
        radius: 7,
        fill: new ol.style.Fill({
          color: '#ffcc33'
        })
      }),
    })
    );
  }


    return styles
  }

**Comment by cs09g** [comment]
could you write in proper english?
