### ISSUE TITLE
is there no lib version instead of es2016 version package?

### ISSUE THREAD

**Issue by kavinforever** [openlayers/openlayers#7469]
i cannot use ol package in my app when no loaders configed,
is there a version including lib version?

**Comment by ahocevar** [comment]
See https://github.com/openlayers/openlayers/blob/master/README.md#getting-started for various options to obtain the library. If yo want a full build (only recommended for testing), you can use the one from [cdnjs](https://cdnjs.com/libraries/openlayers), or download a zip from the [Releases](https://github.com/openlayers/openlayers/releases) page.

We strongly recommend configuring a bundler, as described on https://npmjs.com/package/ol/.
