### ISSUE TITLE
Vector layers rotate against the vector base layer

### ISSUE THREAD

**Issue by soberdor** [openlayers/openlayers#7471]
since 4.5.0 vector layers on top of a vector map are rotating against the rotating direction of the map.

**Comment by ahocevar** [comment]
Can you please elaborate? A code snippet or - even better - a codepen would help.

**Comment by ahocevar** [comment]
I am able to reproduce the issue. Working on a fix now.

**Comment by soberdor** [comment]
Thank you for looking into it! (I didn't find the time to put a codepen together and a rollback to 4.4.2 provided a quick fix)
