### ISSUE TITLE
Opacity transition causes unwanted effects on transparent layers

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#7472]
Go to https://openlayers.org/en/v4.5.0/examples/wms-tiled.html. That example has a WMS layer with transparency. The new opacity transition that fades in tiles makes the loading of these tiles look awkward.

Maybe it's enough to disable the opacity transition in this case and document that it is not recommended to use it for layers with transparency? Or is there a better solution?

**Comment by fredj** [comment]
So it will mean to disable the transition by default when a source is [opaque](https://github.com/openlayers/openlayers/blob/master/src/ol/source/tile.js#L41)?

**Comment by ahocevar** [comment]
That could be a good solution. @tschaub, what do you think?

**Comment by ahocevar** [comment]
I have looked into this, and I think the case of the wms-tiled example is a corner case. There are not many WMS layers with semi-opaque polygon fills out there, and users can always set `transition: 0` on the source.

That said, I think it makes sense to just change the example and not make any decisions based on the `opaque` setting in the library. #7510 makes that change.
