### ISSUE TITLE
Firefox: Using code generated image sometimes doesn't display

### ISSUE THREAD

**Issue by raiyni** [openlayers/openlayers#7473]
From what I can find, this is only producible on Firefox. I can't 100% reproduce it outside of our working environment but I can trigger it by chance sometimes. 

1. Make an image from a canvas data url. 
2. Add the image to the feature style.

May take multiple attempts to produce the bug.

Clicking on the map or resizing the window causes it to draw properly. 

Copy and paste what is in the text box a few times and hit Draw Label.
https://codepen.io/anon/pen/mqMmXy?editors=1010#0

Here's a clip of it happening.
https://streamable.com/52xe9

**Comment by ahocevar** [comment]
According to the documentation, an `img` that you pass to `ol.style.Icon` has to be loaded already. This is not the case right after you set the `src` of that image. To make things work, you can simplify your code and pass the `src` to your `ol.style.Icon`:
```js
  var png = canvas.toDataURL();

  var style = new ol.style.Style({
    image: new ol.style.Icon({
      src: png,
      anchor: [0.5, 0],
      anchorYUnits: "px"
    })
  });
```

**Comment by ahocevar** [comment]
Also note that the kind of style you are trying to create here (text with background) will be supported directly by the library soon. See #7454.

**Comment by raiyni** [comment]
Then you get
`TypeError: Argument 1 of CanvasRenderingContext2D.drawImage could not be converted to any of: HTMLImageElement, SVGImageElement, HTMLCanvasElement, HTMLVideoElement, ImageBitmap.`

That kind of styling with a background and border will be supported properly but it still doesn't change that this happens.

**Comment by raiyni** [comment]
Will you be able to explicitly state line breaks and individually color each line?

**Comment by ahocevar** [comment]
> Will you be able to explicitly state line breaks and individually color each line?

No, the background is per text style. But you'll be able to achieve this by creating multiple text styles with different offsetY.
