### ISSUE TITLE
Hit detection returns false positives on decluttered layers

### ISSUE THREAD

**Issue by congying2** [openlayers/openlayers#7474]
1、map.forEachFeatureAtPixel()  the result Contains data that is not displayed;
2、 But I want to the result of display data，not contain the result of not visilble data;
3、Can ol.layer.Vector  add option for map.forEachFeatureAtPixel() ,for filter data(visible data),not all data of the source???

**Comment by ahocevar** [comment]
The hit detection returns false positives because it works on a canvas with a different size than the rendered map. So there will be less omitted features due to decluttering. We're definitely accepting pull requests to improve this.

**Comment by congying2** [comment]
feature para of style function include visible attributes ?  So that i can do other things.

**Comment by congying2** [comment]
Thank you  very much.

**Comment by bartvde** [comment]
@congying2 have you been able to confirm that the fix works for you?

**Comment by congying2** [comment]
@bartvde No,I'm trying to do it，
@ahocevar  Can you release a new version and Provide a example?  So that I can test it, Thank you!

**Comment by ahocevar** [comment]
@congying2 You can now test with https://openlayers.org/en/master/build/ol.js.

**Comment by congying2** [comment]
@ahocevar  Thank you,  map.forEachFeatureAtPixel() work fine;
   but how I can get the collections of visible features ?

**Comment by ahocevar** [comment]
You cannot get access to the visible features.

**Comment by djibarian** [comment]
I’m having the opposite problem. I want all features to be returned, but it seems only the visible ones are. Is there any way to get all the features at a specific pixel, including the hidden ones due to decluttering?
