### ISSUE TITLE
Need to add set style feature to Google Layer

### ISSUE THREAD

**Issue by balab2020** [openlayers/openlayers#7478]
We are trying to use Google Map custom styles feature to style the map. It is possible to have from OL google layer since it create map instance using google api.

How can I make changes and contribute here? 

Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by balab2020** [comment]
Code snippet on this issue.

OpenLayers.Layer.Google.prototype.setstyle = function (mapLayer) {
        this.type = 'styled';      
        var mapStyle = [];
        var styledMapType = new window.google.maps.StyledMapType(mapStyle, { name: "styled" });
        var googleMapObj = mapLayer.mapObject;
        googleMapObj.mapTypes.set('styled', styledMapType);
        googleMapObj.setMapTypeId('styled');
   }

**Comment by balab2020** [comment]
Can I contribute on this issue?

**Comment by ahocevar** [comment]
Wrong issue tracker, this is for OpenLayers 3+.
