### ISSUE TITLE
Can I apply the style on bing map

### ISSUE THREAD

**Issue by balab2020** [openlayers/openlayers#7479]
Bing Map Api supports styling the map layer, Openlayers uses their Imaginery REST service to display Map. Can I apply style to bing map layer while loading it.

Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
Yes you can. Configure the source with the style name as `imagerySet`. See https://openlayers.org/en/latest/examples/bing-maps.html.
