### ISSUE TITLE
When i place a marker over the static image it got misplaced. Any idea why that is happening ?

### ISSUE THREAD

**Issue by initiuminc1** [openlayers/openlayers#7486]
I am using openlayes to create an indoor map. I have the points positions coming from server. But when i plot it on the image layer it got misplaced

**Comment by ahocevar** [comment]
Probably a projection mismatch. You’ll need to provide some code if you want help. And the issue tracker is not the place for usage questions. Go to https://stackoverflow.com/, and make sure to search for existing answers first.
