### ISSUE TITLE
imageVector geometryFunction didn't work on 4.5.0

### ISSUE THREAD

**Issue by ChouGary** [openlayers/openlayers#7487]
i create a geometryFunction sample on codepan
test  v4.4.2 is ok!

v4.5.0 with image vector layer
https://codepen.io/anon/pen/XzZJby?editors=0010
![image](https://user-images.githubusercontent.com/8294943/33004821-cabcd1ba-cdfd-11e7-8d23-9253e5f29d6d.png)

v4.5.0 with vector layer
https://codepen.io/anon/pen/JOpjgz?editors=0010
![image](https://user-images.githubusercontent.com/8294943/33004830-d801b214-cdfd-11e7-9d80-efd4713039be.png)

v4.4.2 with image vector layer
https://codepen.io/anon/pen/BmYyoW?editors=0010
![image](https://user-images.githubusercontent.com/8294943/33004868-0e90c9c8-cdfe-11e7-8ccb-2b2a7fa69b3d.png)

**Comment by jeroenvheel** [comment]
I have the same problem.
All my layers are image vector layers.
Maybe its The new declutter function that is introduced in v4.5.0 ?

**Comment by ahocevar** [comment]
Is anyone able to find the responsible commit, e.g. by doing a `git bisect`? A pull request with a fix would also be welcome.

**Comment by ahocevar** [comment]
I think there is no need for a pull request any more. ol.source.ImageVector will be deprecated after #7501, and the new `renderMode: 'image'` mode for `ol.layer.Vector` does not have the issue described here.
