### ISSUE TITLE
GeoJSON SimpleStyle Spec

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#7490]
MapBox extended the GeoJSON spec to allow basic styling. https://github.com/mapbox/simplestyle-spec Is this something that would be considered for inclusion in the geojson format?

**Comment by ThomasG77** [comment]
For your information, Mapbox may have extended the spec but icons are coming from their web services.
If you look for instance at https://github.com/mapbox/simplestyle-spec/blob/master/1.0.0/example.geojson, you will Github displays an overview using the spec. If you use the debugger from your browser, you will see that bus icon url is https://a.tiles.mapbox.com/v4/marker/pin-m-bus+ace@2x.png?access_token=pk.eyJ1IjoiZ2l0aHViIiwiYSI6IjEzMDNiZjNlZGQ5Yjg3ZjBkNGZkZWQ3MTIxN2FkODIxIn0.o0lbEdOfJYEOaibweUDlzA

If no public web service is available, the spec is useless...
To my knowledge, Wikimedia provide a similar endpoint (not for public use) https://maps.wikimedia.org/v4/marker/pin-m-bus+ace@2x.png using their vector tiles server [Karthoterian](https://github.com/kartotherian/kartotherian#markers)

**Comment by icholy** [comment]
@ThomasG77 the format could accept a template string/function for creating an icon url from the name.

**Comment by fredj** [comment]
@icholy it should not be added to the OpenLayers's GeoJSON format. The right solution would be to create an external project, as it was done for the mapbox vector-tile style:
https://github.com/boundlessgeo/mapbox-to-ol-style
