### ISSUE TITLE
Circle creation and modification have not the same behavior

### ISSUE THREAD

**Issue by jalik** [openlayers/openlayers#7491]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

The current behavior when creating a circle is not the same then when you modify it :

- When creating the circle, you need to click the center first, then click the radius after, so the circle is finally drawn, on mobile device it's not very nice since you do things really aproximatively since you don't see the size of the circle, I mean when you click for the radius, it could be nice to be able to drag your finger to see how big the circle is, currently dragging is causing the map to pan which does not happen in modification mode.
- When modifying the circle, you can see it changing while resizing, on mobile devices it's very nice because the map does not move, you can drag your finger and the circle will resize.

The code to reproduce this behavior is available in official examples : http://openlayers.org/en/latest/examples/draw-and-modify-features.html

**Comment by ahocevar** [comment]
When drawing circles, configure your `ol.interaction.Draw` with `freehand: true` to get the same behavior as when modifying a circle.

**Comment by jalik** [comment]
@ahocevar Thank you for the tip, now that I know it's seems obvious that freehand is the option I was looking for.. however I still don't understand why by default freehand is disabled when creating a circle, but enabled when modifying it.

Shouldn't it be better if it the behavior was homogenous ?
I would say that by default freehand is a better option for circle drawing since you see the surface covered by the circle while drawing.

**Comment by ahocevar** [comment]
There is no such thing as freehand when modifying features. Making circle drawing freehand by default, while keeping other geometry types vertex-by-vertex, seems less consistent to me.

**Comment by jalik** [comment]
@ahocevar Nevermind, it's a personal point of view, some people will prefer freehand by default, others not, it was just a suggestion. But since we have the `freehand` option we can have both behaviors, so it's fine.
Thank you again.
