### ISSUE TITLE
Vector layer does not dispose of itself properly

### ISSUE THREAD

**Issue by lasselaakkonen** [openlayers/openlayers#7493]
To me it seems like Vector layers are not disposed of properly in v4.5.0.

OL4.5.0 + Vector layer
https://jsfiddle.net/lasselaakkonen/twxhwyhn/5/

OL4.4.2 + Vector layer
https://jsfiddle.net/lasselaakkonen/ax747wvp/2/

Testing with Chrome 62.0.3202.94 (Official Build) (64-bit) on macOS, e.g. using Chrome Dev Tools Performance tab:

- Open one of the fiddles
- Run it
- Click Show button
- Click Hide button
- Open dev tools
- Start performance recording
- Do a couple GCs
- Show + Hide a couple times
- Do a couple GCs
-> OL4.5.0 does not dispose of all listeners/nodes and OL4.4.2 does dispose of everything

Taking heap snapshots also seem to confirms this.

OL4.5.0 without a Vector layer does not have this issue:
https://jsfiddle.net/lasselaakkonen/h64yescv/2/

Is `map.setTarget(null)` the correct way of disposing of a OL map?

What functions could be called to dispose of the Vector layer in OL4.5.0?

**Comment by ahocevar** [comment]
You are right. This is because vector layers now register a listener to the static ol.render.canvas.labelCache.

When you remove vector layers from the map before unlinking the map, that listener should be unregistered by the map renderer‘s removeUnusedLayerRenerers function.

**Comment by ahocevar** [comment]
I created #7495 with a possible fix.
