### ISSUE TITLE
CORS problems with WebGL renderer

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#75]
Firefox does not display images without CORS headers that have the crossorigin attribute set. After b872b5a74f7cd688bf7bde64823bd7b55feda35a, when using the WebGL renderer, tiles still do not display and a Security Error ('This operation is insecure') is thrown in [webglmaprenderer.js#L286](https://github.com/openlayers/ol3/blob/e5d39724c93bf1f2b0331964de070e41a8335e9a/src/ol/renderer/webgl/webglmaprenderer.js#L286).

**Comment by nikoladim123** [comment]
Why do i get this problem when i do this on localhost without even pulling any foreign data. just trying to getImageData(); from another canvas layer on my same page.
