### ISSUE TITLE
Is there any legal restriction to use google map tiles layer as tilesimage source

### ISSUE THREAD

**Issue by ankur021188** [openlayers/openlayers#7503]
Is there any legal restriction to use google map tiles layer as tilesimage source?
eg. code:
` new ol.Map({layers: [
		  new ol.layer.Tile({
			source: new ol.source.TileImage({
			url: '**https://maps.google.com/maps/vt/lyrs=p&hl=en&x={x}&y={y}&z={z}&s=Ga**',
			projection: 'EPSG:3857',
			wrapX: true
			})
		  })
		],
		target: 'map',
		view: new ol.View({
		  center: [0, 0],
		  zoom: 2,
		  projection: 'EPSG:3857'
		})
	  });`

**Comment by ahocevar** [comment]
It is illegal. Refer to the terms of use.

**Comment by ankur021188** [comment]
Thanks for the update, could you please provide me an example or describe the procedure of using google maps with openlayers 4+, which can also support clustering?

**Comment by ahocevar** [comment]
It's illegal, so it is not supported in OpenLayers.
