### ISSUE TITLE
SVG icons can not be found at pixel (not clickable)

### ISSUE THREAD

**Issue by iagafonov** [openlayers/openlayers#7506]
Icons with base64 svg src is properly drawn, but can not be found with functions like
`map.hasFeatureAtPixel` or `map.forEachFeatureAtPixel`
manual sizing, providing img instead of src - does not help

[JSFilddle](https://jsfiddle.net/3q665d04/1/)

I found that
`ol.render.canvas.ReplayGroup.prototype.replayHitDetection_`
try to check empty imageData, and finds nothing.
Maybe it make sense to add boolean property to `ol.style.Icon`, by which it becomes clickable at whole size or custom clickable shape property

**Comment by ahocevar** [comment]
The SVG icon you created is huge - it is beyond the `renderBuffer` of 100 pixels. I have updated your fiddle to give the SVG a viewBox, use fractions for both x- and y- anchor, and render it at your intended location (with ol.proj.fromLonLat). See https://jsfiddle.net/3q665d04/2/.

**Comment by iagafonov** [comment]
@ahocevar Thank you very much!
