### ISSUE TITLE
click events and interactions are "propagated" to elements outside OL map on Android and iOS

### ISSUE THREAD

**Issue by lasselaakkonen** [openlayers/openlayers#7509]
When there is a map, which listens to click events or has a selection interaction, which trigger opening another element on top of the map. Clicking the map causes the click to be also triggered on the element that is opened on top of the map.

**Steps to reproduce**

Using `map.on('click', ...)` https://jsfiddle.net/lasselaakkonen/h38ma0zw/13
Using Select interaction with `click` condition https://jsfiddle.net/lasselaakkonen/3sh2ko1m/1/

- Render a map
- Attach a click handler, which when triggered, shows an element on top of the map
- Click the map (or a feature if using Select interaction)
-> The click/interaction handler is triggered
-> The handler shows the new element on top of the map, as it should
-> THEN the click event is also triggered on the new element, this should not happen
(-> In those fiddles clicking on the modal closes the modal)

**Reproduced on**
- Samsung Galaxy S8, Android 7, Chrome, Samsung browser, WebView
- Samsung Tab A, Android 7, Samsung Browser
- Huawei Honor 6, Android 6, Chrome, WebView
- iOS 10 Safari

**Not reproduced on**
- macOS Chrome, Safari, Firefox
- iOS 11 Safari

One workaround for the fiddles is to call `setTimeout(showModal, MAGICVALUE)` instead of `showModal()`.

What is going on? Is there a way to stop the propagation of the click events/interactions?

**Comment by jonathan-chin** [comment]
this is way way late. but I came across this exact issue and finally found a solution.

switching the event from `click` to `singleclick` seems to fix this.
