### ISSUE TITLE
precompose and postcompose not called on vector layers on webgl renderer

### ISSUE THREAD

**Issue by geraldo** [openlayers/openlayers#7515]
I try to apply color changes on vector layers using webgl, but fail on the first step. I need to hook into **precompose** and **postcompose** events, but they don't get called on ol.vector.Layer.

Here is the related [codepen](https://codepen.io/gkogler/pen/QOBVbe) (based on the [Vector Layer example](http://openlayers.org/en/latest/examples/vector-layer.html)).

Is this a bug or an expected behavior?

**Comment by ahocevar** [comment]
What is your reason for not using the standard canvas renderer?

**Comment by geraldo** [comment]
I want to apply some color effects to show water flowing in rivers (visually something like [that](http://andywoodruff.com/blog/the-rain-on-terrain/). And that for it would be more efficient to use webgl renderer.

Ok, I just found out to use ol.source.ImageVector and that gives me access to pre- and postcompose. So now it should be possible to apply shaders to the geometries.
