### ISSUE TITLE
jscomp_off : unnecessaryCasts not works with OL 4.5

### ISSUE THREAD

**Issue by giova86** [openlayers/openlayers#7520]
I'm using 'jscomp_off : unnecessaryCasts' to re-compile OpenLayers and i have error message like this : 

_ERR! compile java.lang.NullPointerException: No warning class for name: unnecessaryCasts
ERR! compile    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864)
..._

Could you say me what change from OpenLayers 4.2 to 4.5 can cause this error?

Thank you

**Comment by fredj** [comment]
`unnecessaryCasts` check was removed from the google closure compiler; you can safely remove it from your `jscomp_off` list
