### ISSUE TITLE
FullScreen control button is losing css classes

### ISSUE THREAD

**Issue by 1thierry1** [openlayers/openlayers#7523]
Some css classes might be added to the control buttons for a custom look and feel (using jqueryUI for example).
These classes are definitively lost by the "FullScreen" control button after the first click.

Before click, the button element is (which is OK):
`<button class="ol-full-screen-false ui-button ui-corner-all ui-widget" ...`

After click, the button element is (ui- classes are lost):
`<button class="ol-full-screen-true" ...`

See [codepen](https://codepen.io/1thierry1/pen/OOBraa).

A correction may be to change the way button.className is updated (just toggle true/false suffix):

```javascript
ol.control.FullScreen.prototype.handleFullScreenChange_ = function() {
  var button = this.element.firstElementChild;
  var map = this.getMap();
  if (ol.control.FullScreen.isFullScreen()) {
  
//    button.className = this.cssClassName_ + '-true';
    button.className = button.className.replace(this.cssClassName_ + '-false', this.cssClassName_ + '-true')

    ol.dom.replaceNode(this.labelActiveNode_, this.labelNode_);
  } else {

//    button.className = this.cssClassName_ + '-false';
    button.className = button.className.replace(this.cssClassName_ + '-true', this.cssClassName_ + '-false')

    ol.dom.replaceNode(this.labelNode_, this.labelActiveNode_);
  }
  if (map) {
    map.updateSize();
  }
};
```

**Comment by fredj** [comment]
good catch.
Instead of using `button.className.replace` it would be simpler to use `classList`, something like:
```js
button.classList.replace(this.cssClassName_ + '-false', this.cssClassName_ + '-true');
```
