### ISSUE TITLE
ol.format.GeoJSON dataProjection and featureProjection seem unefficient

### ISSUE THREAD

**Issue by rbonnefoi** [openlayers/openlayers#7529]
Dear all,

I am facing problems with GeoJSON format and the ability of transforming read features from a source file using a 'dataProjection' to an ol.source.Vector which is supposed to use a 'featureProjection'.

However, whichever the projection code used to define the parameters 'dataProjection' or 'featureProjection' while using the readFeatures() method of ol.format.GeoJSON, the result is still the same, without any transformation.

Am i misunderstanding something or is there a bug ?

Best regards,

Remi.

**Comment by rbonnefoi** [comment]
While I am not able to explain how I solved my problem, the readFeatures() is actually as expected.

Sorry for this bad issue request...

Anyway, many thanks for the job done.

Remi.

**Comment by shenchaoran** [comment]
mark
