### ISSUE TITLE
Calling ol.interaction.Draw#removeLastPoint when there are no coordinates causes an exception

### ISSUE THREAD

**Issue by walkermatt** [openlayers/openlayers#7532]
I've found that when `removeLastPoint` is call when there are no sketch coordinates left an unhandled exception occurs.

I've created the following examples. The first demonstrates the problem; the second demonstrates a fix which I've committed with a test to https://github.com/walkermatt/ol3/commit/90d8224a08faf2e7c3cac115308417cd16df0e6f and would be happy to submit as a pull-request.

* [Draw Features - removeLastPoint - error](https://codepen.io/walkermatt/pen/KybozN)
* [Draw Features - removeLastPoint - fixed](https://codepen.io/walkermatt/pen/ooJyJd)

To test the demos open devtools, start drawing a feature then click the "removeLastPoint" button until no points remain in your sketch. In the first example I get the following stacktrace:

    TypeError: Cannot read property 'length' of undefined
    at ol.geom.Polygon.ol.geom.SimpleGeometry.setLayout (ol-debug.js:13340)
    at ol.geom.Polygon.setCoordinates (ol-debug.js:15498)
    at ol.interaction.Draw.geometryFunction [as geometryFunction_] (ol-debug.js:60327)
    at ol.interaction.Draw.removeLastPoint (ol-debug.js:60788)
    at HTMLButtonElement.removeButton.onclick (pen.js:30)

**Comment by fredj** [comment]
Pull request welcome.

**Comment by walkermatt** [comment]
Great, I'll get a CLA signed and send a PR over.

**Comment by ahocevar** [comment]
@walkermatt CLA received. Thanks!

**Comment by Osmiogrzesznik** [comment]
The problem still exists if Draw.removeLastPoint() is called during drawing of a Circle geometry. If you mark the center point of a circle and then call to the method is executed, it results in a 

 ```
v5-3-0_build_ol.js:7 Uncaught TypeError: Cannot read property 'length' of undefined
    at e.removeLastPoint (v5-3-0_build_ol.js:7)
```

Sorry, if this is vague but i am not ready yet to bundling the application together with its dependencies, with node, and quite inexperienced on github.  I am currently looking through source code and it seems that src/ol/interaction/draw.js
and it seems that 
https://github.com/openlayers/openlayers/blob/c767091faf7de8340aa3eb06ede5930e519c01ac/src/ol/interaction/Draw.js#L815 (lines 815 to 830) do not check for circle geometry and then 
https://github.com/openlayers/openlayers/blob/c767091faf7de8340aa3eb06ede5930e519c01ac/src/ol/interaction/Draw.js#L830
tries to access length on declared only and undefined yet `coordinates` variable.

in minified file (ver5.3.0) from https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js
i included  through script tag , 

the error is thrown as below:
```javascript
e.prototype.removeLastPoint = function() {
    if (this.sketchFeature_) {
        var t, e = this.sketchFeature_.getGeometry();
        this.mode_ === Ac.LINE_STRING ? ((t = this.sketchCoords_).splice(-2, 1),
        this.geometryFunction_(t, e),
        t.length >= 2 && (this.finishCoordinate_ = t[t.length - 2].slice())) : this.mode_ === Ac.POLYGON && ((t = this.sketchCoords_[0]).splice(-2, 1),
        this.sketchLine_.getGeometry().setCoordinates(t),
        this.geometryFunction_(this.sketchCoords_, e)),
        0 === t.length && (this.finishCoordinate_ = null),//<-- this line throws the error
        this.updateSketchFeatures_()
    }
```

I am not sure i could handle the change myself, however i would like to point it out.
Apologies if my comment may be confusing, it's actually first time when i submit/comment issue on large project.
