### ISSUE TITLE
error calculationg bounding box when switching from v4.5.0 to v4.6.0

### ISSUE THREAD

**Issue by geomoes** [openlayers/openlayers#7544]
I use the code underneath to get geojson from PostGis. In v.4.5.0 the extent gives me correct lng,lat values, so that the query returns geojson. When using v.4.6.0 I get strange lng-values for the extent (e.g. bbox=-540,49.52186539653559,540,49.67807036260169), so that my PostGis-query fails.
 
```
        source: new ol.source.Vector({
            projection: "EPSG:4326",
            attributions: [new ol.Attribution({
                html: options.attribution
            })],
            strategy: options.loadingstategy,
            loader: function(extent, resolution, projection) {
                var extent = ol.proj.transformExtent(extent, projection.getCode(), ol.proj.get('EPSG:4326').getCode());
                $.ajax({
                    type: "GET",
                    dataType: "json",
                    url: "./mapdata/get_geojson.php?" +
                        "geotable=" + options.geotable +
                        "&fields=" + options.fields +
                        "&srid=" + options.srid +
                        "&where=" + options.where +
                        "&bbox=" + extent.join(","),
                    context: this
                }).done(function(data) {
                    var format = new ol.format.GeoJSON();
                    this.addFeatures(format.readFeatures(data, {
                        dataProjection: "EPSG:4326",
                        featureProjection: "EPSG:3857"
                    }));

                });

            }
        }),
```

**Comment by ahocevar** [comment]
Which `loadingStrategy` are you using?

**Comment by geomoes** [comment]
the loadingstategy is defined in my layersettings:

loadingstategy: ol.loadingstrategy.bbox,

**Comment by ahocevar** [comment]
Thanks for the bug report. This is a regression caused by #7530. I'll see if we can improve that or have to revert #7530. We'll publish a bugfix release when done.

**Comment by geomoes** [comment]
As far as I can see the problem lies in the following line of code:
var extent = ol.proj.transformExtent(extent, projection.getCode(),'EPSG:4326');
which returns a wrong value for the longitude (-540 and 540) whereas the latitude values are correct.

**Comment by raiyni** [comment]
What would the remedy be for this then? Custom build is probably the safest?
