### ISSUE TITLE
draw interaction low performance

### ISSUE THREAD

**Issue by ChouGary** [openlayers/openlayers#7553]
i'm  try to upgrade imagevector layer from 4.4.2 to 4.6.2
about openlayer 4.6.0 upgrade notes **deprecation of ol.source.ImageVector**
draw interaction is very slow in 4.6.2 renderMode: 'image' compare with 4.4.2 image vector

bad performancein 4.6.2 **renderMode: 'image'** 
https://codepen.io/anon/pen/mqZxqq?editors=0010

good performancein 4.4.2 **image vector** 
https://codepen.io/anon/pen/xPoWPV?editors=0010

test condition draw triangle in this resolution
![image](https://user-images.githubusercontent.com/8294943/33749706-33dc2ca8-dc0a-11e7-835b-e99fabbe6b89.png)

**Comment by ahocevar** [comment]
Thanks for the bug report. See #7554 for a fix. We'll create a patch release when that is merged.
