### ISSUE TITLE
Scale Line and Projection EPSG:27700

### ISSUE THREAD

**Issue by sebalaini** [openlayers/openlayers#7556]
I search a lot about this problem but I don't find a solution, so... I'm using a projection and the scaleLine display the value 100.000 greater than the real value, How can I solve this problem?

Here my OpenLayer4 code:

```
Proj4js.defs["EPSG:27700"] = "+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs";

var projection = new ol.proj.Projection({
code: 'EPSG:27700',
units: 'm'
});

controls: ol.control.defaults({
  attributionOptions: ({
  collapsible: false
  })
}).extend([
  // add the actual scale in "m"
  new ol.control.ScaleLine({units:'metric', target: 
document.getElementById('map_extras')})
]),
layers: [layers],
target: 'mapdiv',
view: new ol.View({
projection: projection,
    center: ol.proj.fromLonLat([parseInt(setPos[0]), parseInt(setPos[1])], projection),
resolution: 2.8,
resolutions: [2.8, 1.4, 0.7, 0.28, 0.14, 0.07],
})
```

Also, something that I saw is when you move the map on the x y axis the scaleLine sometimes changes without modifying the actual zoom, it seems to be a common problem when you are using a different projection

**Comment by raiyni** [comment]
> the scaleLine sometimes changes without modifying the actual zoom, it seems to be a common problem when you are using a different projection

That's because the definition of a unit of measure changes based on where you are at on the Earth due to having to flatten a round object to a flat image.

**Comment by sebalaini** [comment]
ok, but I'm speaking that if you move the map something about 4 mm the scale from 82px pass to 128px and just in some zone. For example, if I pan on X-axis I start with 82 then 128 then again 82 and so on. 
All of this in the same city, not from 2 different countries far away from each other.

**Comment by ahocevar** [comment]
All you have to do is configure the projection with a custom `getPointResolution` function:
```js
var projection = new ol.proj.Projection({
  code: 'EPSG:27700',
  getPointResolution: function(r) { return r; },
  units: 'm'
});
```

**Comment by sebalaini** [comment]
oh, it's so easy. I tried to find a solution on google but no one talk about this and in the documentation neither. Many thanks.
