### ISSUE TITLE
Rendering a vector layer as an image and zooming while a feature is selected makes the feature invisible.

### ISSUE THREAD

**Issue by qorsmond** [openlayers/openlayers#7557]
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Using renderMode: 'image' on a vector layer then zooming in or out while a feature is selected makes the selected feature disappear. When the renderMode is changed to 'vector' it works as expected.
Pen:  https://codepen.io/qorsmond/pen/aVebrm

**Comment by ahocevar** [comment]
Thanks for the bug report. See #7559 for a fix.
