### ISSUE TITLE
Whether the basemap's projection of MVT vector tile is no longer expected to be EPSG:4326？

### ISSUE THREAD

**Issue by tangqinGiser** [openlayers/openlayers#7560]
Excuse me, whether the basemap's projection of MVT vector tile is no longer expected to be EPSG:4326？
I found the value of  defaultDataProjection was changed on August 29, and did not find  where I can set or modify it.
![cz0yrnnx 5jsu5wq_k3nhb](https://user-images.githubusercontent.com/30792630/33816551-b37eb04a-de74-11e7-84ce-bcf93fbb403f.png)

**Comment by ahocevar** [comment]
MVT vector tiles have coordinates in pixel space relative to the tile origin, and are expected to be in the view projection. Same as before that change. The projection code you're pointing out is not even used or read. To avoid confusion, I have changed it back to `''` in #7562.

**Comment by tangqinGiser** [comment]
Excuse me，Which version of ol.js and ol-debug.js can be used in this function?[#7560](https://github.com/openlayers/openlayers/issues/7560)
Is the next version available?

**Comment by ahocevar** [comment]
It is in all v5.0.0-beta versions, which are available as npm package ol.

**Comment by tangqinGiser** [comment]
When can I get this  package of v5.0.0-beta versions?

**Comment by tangqinGiser** [comment]
thanks~ I found it~
