### ISSUE TITLE
Several labels are show and hide  with declutter : true.

### ISSUE THREAD

**Issue by mayheki** [openlayers/openlayers#7572]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [ ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

I've tested declutter : true on 4.6.4 version.  It was fixed by #7561.
But some labels and icon styles are show and hide still repeatly (after rotated + flicking or moving the map).
https://codepen.io/mayheki/pen/qpWaGp

Thank you.

**Comment by ahocevar** [comment]
4.6.4 does not include #7561. That's not in any release yet - it will be in 5.0.0.
