### ISSUE TITLE
How to add shadowBlur shadowColor attribute for ol.style.fill

### ISSUE THREAD

**Issue by congying2** [openlayers/openlayers#7573]
How to add shadowBlur shadowColor attribute for ol.style.fill ?

**Comment by ahocevar** [comment]
This is not supported.

**Comment by ahocevar** [comment]
Shadow can be achieved by rendering the geometry again with an offset. Blur is probably more complicated.

**Comment by riasol** [comment]
Is it about implementing shadowColor, shadowBlur of html5 canvas?

**Comment by congying2** [comment]
yes,  how to use the attribute of HTML5  canvas?

**Comment by ahocevar** [comment]
Oh I see now what you mean. It should be possible to add style properties for those. We’d accept pull requests for that.

**Comment by congying2** [comment]
thank you, where is the example?
