### ISSUE TITLE
When using overflow: true on a text style decluttering seems to fail

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#7592]
See some of the screenshots here:

![selection_442](https://user-images.githubusercontent.com/319678/34004241-a2fd98e6-e0f7-11e7-8337-eb7833f5b199.png)
![selection_440](https://user-images.githubusercontent.com/319678/34004242-a31ad9e2-e0f7-11e7-8847-9fbb50a31669.png)

**Comment by ahocevar** [comment]
Seems to happen with MultiPolygon geometries only. Might be the same with MultiPoint and MultiLineString.

**Comment by ahocevar** [comment]
This has been fixed.
