### ISSUE TITLE
Add named exports for all lowercase modules

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7617]
The transform for modules left us with a single default export for each module.  This works well for modules that export a constructor or enum (e.g. `ol/Map` and `ol/geom/GeometryType`).  For all of the lowercase modules, we should use named exports instead.  For example, `ol/array` should have named exports for each of the array functions.

See #7586, #7581, and #7584 for inspiration.

**Comment by bjornharrtell** [comment]
@tschaub would it not be sensible to rework enums like `GeometryType` into constants? (and so GeometryType module would become `geometrytype`)

**Comment by tschaub** [comment]
@bjornharrtell we still use enums as types, so I think these should stay as they are.

**Comment by tschaub** [comment]
See #7779.
