### ISSUE TITLE
triggering a click event (or any other) doesn't seem to work

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#7629]
Hello,

I'm testing our software (with an openlayers component) using Cypress.
Now can cypress trigger click events on elements like this:
cy.get('div.ol-viewport').click();

it works on a normal canvas (cy.get('canvas').click()) or a normal element (div/span etc.)
but somehow it doesn't do anything when i use openlayers.

I did some debugging openlayers and noticed that openlayers doesn't listen to the click event.
It does listen to the 'pointerdown' event (and lots of others) but that's about as far as i can work out the complex event model of openlayers.

in cypress you can trigger any event from any object like so:
cy.get('div.ol-viewport').trigger('pointerdown', options);

The problem is that i simply don't know what options i have to provide. I can see huge objects with lots of complex types when i debug in chrome, but i can't imagine i have to provide them all. Especially since the browser doesn't know half of them, so when manually clicking i don't think the browser supplies more then just an x, y and perhaps some extra's like the mousebutton, or keys that are been holded down.

Can someone help me figure out how to simulate a click on a map (or feature) in openlayers?

**Comment by BasieP** [comment]
Any devs got some thoughts on this?
having your application testable is a real must nowadays and that includes openlayers.

So far i haven't been able to trigger any event...

**Comment by ddmng** [comment]
@BasieP don't know if you solved this but, after googling a little, I solved simple clicks this way:
```js
    cy.get(selectors.map)
      .trigger('pointerdown', 250, 250).trigger('pointerup', 250, 250)
      .trigger('pointerdown', 250, 500).trigger('pointerup', 250, 500)
      .trigger('pointerdown', 500, 500).trigger('pointerup', 500, 500)
      .trigger('pointerdown', 500, 250).trigger('pointerup', 500, 250)
      .trigger('pointerdown', 250, 250).trigger('pointerup', 250, 250)
```

Anyway this is not so useful if you have to click on a specific feature: it seems you have to carefully pick the right coordinates, but it's not so easy when you have a map w/ scrolling and zoom.
