### ISSUE TITLE
declutter layers style conflict  with ol.interaction.Select  ol.events.condition.pointerMove？

### ISSUE THREAD

**Issue by congying2** [openlayers/openlayers#7641]
declutter layers style conflict  with the style of ol.interaction.Select when condition ol.events.condition.pointerMove ？

**Comment by ahocevar** [comment]
Please provide more information.

**Comment by congying2** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <title>declutter</title>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.6.4/css/ol.css" type="text/css">
    
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
    <script src="https://openlayers.org/en/v4.6.4/build/ol.js"></script>
    <style>
    html, body, .map {
      margin: 0;
      padding: 0;
      width: 100%;
      height: 100%;
      position:relative;
    }
    </style>
  </head>
  <body>
    <div id="map" class="map"></div>
    <script>

      var raster = new ol.layer.Tile({
        source: new ol.source.Stamen({
          layer: 'toner'
        })
      });

      var map = new ol.Map({
        layers: [raster],
        target: 'map',
        view: new ol.View({
          center: [0, 0],
          zoom: 2
        })
      });
      map.on("click",function(e){
        console.log(e.coordinate);
      });

      var farray=[{x:11623320.269157037,y:3013453.403114792,name:"error highlight feature"},
    {x:8218509.281222142, y:4774562.534805249,name:" feature"},
    {x:7944558.971848071, y:10801469.341034828,name:" feature"},
    {x:8649002.624524258, y:5009377.085697312,name:" feature"},
    {x:8962088.692380339, y:5518141.945963446,name:" feature"},
    {x:9470853.552646473, y:5948635.289265558,name:" feature"},
    {x:10958012.374962859, y:5752956.496855505,name:" feature"},
    {x:12993071.816027395, y:5792092.255337518,name:" feature"},
    {x:14597637.913789816, y:6574807.42497772,name:" feature"}
    ];

    var featuresss=[];
    for (var i = 0; i < farray.length; i++) {
      var singlef=farray[i];
      var feature=new ol.Feature(new ol.geom.Point([singlef.x,singlef.y]));
      feature.set("name",singlef["name"]);
      feature.set("zindexh",i);
      featuresss.push(feature);
    }

    var labelStyle=new ol.style.Style({
      image:new ol.style.Icon({
             anchor: [0.5, 1],
             anchorXUnits: 'fraction',
             anchorYUnits: 'fraction',
             opacity: 1,
             src:"https://openlayers.org/en/v4.6.4/examples/data/icon.png",
             scale:1.0,
             offset:[0,0],
             size:[35,53]
           }),
      text:new ol.style.Text({
        textAlign: "center",
        textBaseline: "middle",
        font: "bold 22px Arial",
        text: "",
        fill: new ol.style.Fill({
          color:'rgba(255,0,0,0.9)'
        }),
        stroke: new ol.style.Stroke({
          color:'rgba(0,255,0,0.7)',
          width: 3
        }),
        offsetX: 0,
        offsetY: -60,
        rotation:0,
        exceedLength:true
      })
   });
   var styles=[labelStyle];
    function normalStyle(feature,resolution){
      var name=feature.get("name");
      labelStyle.getText().getFill().setColor("rgba(255,0,0,0.9)");
      labelStyle.getText().setText(name);
      labelStyle.setZIndex(feature.get("zindexh"));
      console.log(name);
      return styles;
    }


    function VectorOverlayStyle(feature,resolution) {
      var name=feature.get("name");
      labelStyle.getText().getFill().setColor("rgba(0,2,255,0.7)");
      labelStyle.getText().setText(name);
      labelStyle.setZIndex(feature.get("zindexh"));
      console.log(feature.getGeometry().getCoordinates());
      return styles;
    }

      var vector=new ol.layer.Vector({
        source:new ol.source.Vector({
    			  features:featuresss,
    				useSpatialIndex:true
    			}),
        declutter:true
      });
      vector.setStyle(normalStyle);
      map.addLayer(vector);


      var selectPointerMove=new  ol.interaction.Select({
        style:VectorOverlayStyle,
        condition: ol.events.condition.pointerMove,
        layers:function(_layer){
            return true;
        }
      });
      map.addInteraction(selectPointerMove);

    </script>
  </body>
</html>

**Comment by congying2** [comment]
When the mouse enters "error highlight feature" ，Alternate scintillation feature???

**Comment by congying2** [comment]
`<title>declutter</title> <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script> <script src="https://openlayers.org/en/v4.6.4/build/ol.js"></script> <style> html, body, .map { margin: 0; padding: 0; width: 100%; height: 100%; position:relative; } </style>
<script>
  var raster = new ol.layer.Tile({
    source: new ol.source.Stamen({
      layer: 'toner'
    })
  });

  var map = new ol.Map({
    layers: [raster],
    target: 'map',
    view: new ol.View({
      center: [0, 0],
      zoom: 2
    })
  });
  map.on("click",function(e){
    console.log(e.coordinate);
  });

  var farray=[{x:11623320.269157037,y:3013453.403114792,name:"error highlight feature"},
{x:8218509.281222142, y:4774562.534805249,name:" feature"},
{x:7944558.971848071, y:10801469.341034828,name:" feature"},
{x:8649002.624524258, y:5009377.085697312,name:" feature"},
{x:8962088.692380339, y:5518141.945963446,name:" feature"},
{x:9470853.552646473, y:5948635.289265558,name:" feature"},
{x:10958012.374962859, y:5752956.496855505,name:" feature"},
{x:12993071.816027395, y:5792092.255337518,name:" feature"},
{x:14597637.913789816, y:6574807.42497772,name:" feature"}
];

var featuresss=[];
for (var i = 0; i < farray.length; i++) {
  var singlef=farray[i];
  var feature=new ol.Feature(new ol.geom.Point([singlef.x,singlef.y]));
  feature.set("name",singlef["name"]);
  feature.set("zindexh",i);
  featuresss.push(feature);
}

var labelStyle=new ol.style.Style({
  image:new ol.style.Icon({
         anchor: [0.5, 1],
         anchorXUnits: 'fraction',
         anchorYUnits: 'fraction',
         opacity: 1,
         src:"https://openlayers.org/en/v4.6.4/examples/data/icon.png",
         scale:1.0,
         offset:[0,0],
         size:[35,53]
       }),
  text:new ol.style.Text({
    textAlign: "center",
    textBaseline: "middle",
    font: "bold 22px Arial",
    text: "",
    fill: new ol.style.Fill({
      color:'rgba(255,0,0,0.9)'
    }),
    stroke: new ol.style.Stroke({
      color:'rgba(0,255,0,0.7)',
      width: 3
    }),
    offsetX: 0,
    offsetY: -60,
    rotation:0,
    exceedLength:true
  })
});
var styles=[labelStyle];
function normalStyle(feature,resolution){
var name=feature.get("name");
labelStyle.getText().getFill().setColor("rgba(255,0,0,0.9)");
labelStyle.getText().setText(name);
labelStyle.setZIndex(feature.get("zindexh"));
console.log(name);
return styles;
}

function VectorOverlayStyle(feature,resolution) {
  var name=feature.get("name");
  labelStyle.getText().getFill().setColor("rgba(0,2,255,0.7)");
  labelStyle.getText().setText(name);
  labelStyle.setZIndex(feature.get("zindexh"));
  console.log(feature.getGeometry().getCoordinates());
  return styles;
}

  var vector=new ol.layer.Vector({
    source:new ol.source.Vector({
			  features:featuresss,
				useSpatialIndex:true
			}),
    declutter:true
  });
  vector.setStyle(normalStyle);
  map.addLayer(vector);


  var selectPointerMove=new  ol.interaction.Select({
    style:VectorOverlayStyle,
    condition: ol.events.condition.pointerMove,
    layers:function(_layer){
        return true;
    }
  });
  map.addInteraction(selectPointerMove);

</script>`

**Comment by congying2** [comment]
`function VectorOverlayStyle(feature,resolution) {
  var name=feature.get("name");
  labelStyle.getText().getFill().setColor("rgba(0,2,255,0.7)");
  labelStyle.getText().setText(name);
  labelStyle.setZIndex(feature.get("zindexh"));
  console.log(feature.getGeometry().getCoordinates());
  return styles;
}

  var vector=new ol.layer.Vector({
    source:new ol.source.Vector({
			  features:featuresss,
				useSpatialIndex:true
			}),
    declutter:true
  });
  vector.setStyle(normalStyle);
  map.addLayer(vector);


  var selectPointerMove=new  ol.interaction.Select({
    style:VectorOverlayStyle,
    condition: ol.events.condition.pointerMove,
    layers:function(_layer){
        return true;
    }
  });
  map.addInteraction(selectPointerMove);`

**Comment by congying2** [comment]
Please help me, @ahocevar , 
the example :
https://codepen.io/congying2/pen/jYBWYQ

**Comment by ahocevar** [comment]
What if you just use `map.getFeaturesAtPixel()` instead of a Select interaction? I'm afraid I cannot help you with the Select interaction - I've given up on that a long time ago.

**Comment by tomchadwin** [comment]
I wonder if this is the same issue I'm facing with https://github.com/tomchadwin/qgis2web/issues/608#issuecomment-360559589

**Comment by angusscown** [comment]
There is something going on with declutter.   If I have a layer that has declutter set to true and interactions for an overlay such as pointermove and am looking for map.forEachFeatureAtPixel I get a lot of errors thrown.  I remove the declutter everything works as normal.  Is it possible that the declutter is altering the objects (features) in a way that is not compatible with other parts of the OL system?   I can dig deeper if required.  I'd have to build an example outside of my internally facing system.

**Comment by ahocevar** [comment]
@angusscown Decluttering does not alter features in any way. Have you tried v4.6.5 or a recent v5.0.0 beta? There were several issues fixed.

**Comment by angusscown** [comment]
@ahocevar  v4.6.5  fixed my issues with vector tiles labelling declutter.

**Comment by prebm** [comment]
This issue is still happening with v5.3.0 as you can see in the updated [CodePen](https://codepen.io/anon/pen/wRgLNY). Is there any other way/example to highlight labels on hover?

**Comment by ahocevar** [comment]
@prebm If you do not use the Select interaction, but just change the style of the highlighted feature (detected with `map.getFeaturesAtPixel`), things will work as expected.

**Comment by prebm** [comment]
@ahocevar Ok, thanks. I will try that.
