### ISSUE TITLE
Broken Vector layer rendering when layer has different extent from view and renderMode: "image" is set

### ISSUE THREAD

**Issue by kluthje** [openlayers/openlayers#7653]
If you have a Vector layer with renderMode: "image", and layer extent defined, and the extent is different from view extent, the vectors on the map are cut off and translated incorrectly. Can be seen in https://codepen.io/anon/pen/MrjqQK . Pan and zoom the map and see how the polygon rendering behaves. It is rendered correctly if you remove renderMode: "image" or set the layer extent to be the same as the View extent or remove the layer extent. Tested in openlayers 4.6.4.

![capture](https://user-images.githubusercontent.com/2275703/34300406-8547c882-e730-11e7-8172-91c34fad4d01.PNG)

Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
Confirmed. Pull request with a fix accepted.

**Comment by mmomtchev** [comment]
I have this (or a related) problem even with the layer extent set to the view extent. The problem disappears if the the renderMode is 'vector'. Anything new on this issue? Or a workaround with renderMode: image?

https://jsfiddle.net/mmomtchev/hjsm0qp2/36/

**Comment by ahocevar** [comment]
@mmomtchev This hasn't been fixed yet. We're still accepting a pull request to fix it.

**Comment by mmomtchev** [comment]
Ok, I will try to look into it, I just needed a confirmation that it was indeed a bug. I got around it by removing the extent and bounding the GeoJSON itself.

**Comment by mmomtchev** [comment]
This affects only the canvas renderer, webgl seems to work

**Comment by ahocevar** [comment]
@mmomtchev The webgl renderer does not have an `image` mode and ignores that setting.
