### ISSUE TITLE
Re-use overlay instance

### ISSUE THREAD

**Issue by strarsis** [openlayers/openlayers#7657]
I want to use a single overlay instance among multiple OL maps. This doesn't seem to be possible with OpenLayers, `Ol.map.addOverlay(overlayObj)` on multiple maps results with the overlay shown only the map where it has been invoked last and not on all of them.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).

Related issue: https://github.com/openlayers/openlayers/issues/7282

**Comment by ahocevar** [comment]
It‘s a single dom element, and as such it can never be rendered twice.
