### ISSUE TITLE
ol.interaction.draw should have user-defined funcions to handle 'click' or other browser events.

### ISSUE THREAD

**Issue by zhhuan** [openlayers/openlayers#7658]
Recently when I use the openlayers's ol.interaction.draw to draw lineString, however I found I can't control the click event that is default to add a point the layer. I want to add a tooltip that show the length of string meanwhile, but I cant't control this.Openlayers should support the function.

take a look at my target: ![baidu measure](https://map.baidu.com/) 
![image](https://user-images.githubusercontent.com/10020346/34331915-1f7bd650-e966-11e7-9750-92e956ccdaeb.png)

**Comment by ThomasG77** [comment]
I'm not sure I understand your issue here. You can see the [measure example](http://openlayers.org/en/latest/examples/measure.html) in the official documentation that do more or less what you want.
