### ISSUE TITLE
Declutter selection error

### ISSUE THREAD

**Issue by Sk3p** [openlayers/openlayers#7664]
Hi, I found a bug:
with the declutter option in a vector layer when I try to select features with a text style, selection is possible only for features with the text label visible in the viewport.

In the example if you click on the linestring at the top (Feature 1) this is not selecteable until the label is visible.

https://codepen.io/anon/pen/YYNgeP?editors=0010

**Comment by ahocevar** [comment]
Confirmed. Pull request with a fix welcome.
