### ISSUE TITLE
the conflict between modify interaction and translate interaction

### ISSUE THREAD

**Issue by Lisz112** [openlayers/openlayers#7665]
When I use ol.interaction.Modify and ol.interaction.Translate in the meantime, I found that if I add the modify interaction before the translate interaction, the modify interaction will not response. For example, when I write code like this    
```
          select = new ol.interaction.Select();
          map.addInteraction(select);

	  modify = new ol.interaction.Modify({
			features: select.getFeatures(),
		  });
          map.addInteraction(modify);

	  translate = new ol.interaction.Translate({
			features: select.getFeatures(),
		  });
	  map.addInteraction(translate);
```
If I click **in** a polygon and drag, the whole feature will move and if I click **on the edge** of the polygon, the modify interaction has no response, instead, the whole feature will move as well.
This bug will not show up if I change the order of the two interactions.

**Comment by ahocevar** [comment]
The order of interaction defines the behavior, because each interaction decides on its own which events to handle. So this is not a bug.
