### ISSUE TITLE
mousewheel+ctrl key do map zoom

### ISSUE THREAD

**Issue by rezvanshiravi** [openlayers/openlayers#7666]
Hi
I have an embedded map on a page. when I scroll page and reach to the map div, map zooms instead of scrolling page. I want to enable map zoom only by mouse wheel+ctrl key like google.
please  give me a right code.

Best Regards.

**Comment by raiyni** [comment]
It's not too pretty but maybe there is a better way

`var i = new ol.interaction.MouseWheelZoom();

var oldFn = i.handleEvent;
i.handleEvent = function(e) {
  var type = e.type;
  if (type !== "wheel" && type !== "wheel" ) {
    return true;
  }
  
  if (!e.originalEvent.altKey) {
    return true
  }

  oldFn.call(this,e);
}

var map = new ol.Map({
  interactions: ol.interaction.defaults({mouseWheelZoom: false}).extend([i]),
  layers: [
    new ol.layer.Tile({
      source: new ol.source.OSM()
    })
  ],
  target: 'map',
  view: new ol.View({
    center: [0, 0],
    zoom: 2
  })
});`
