### ISSUE TITLE
Remove/update http://openlayers.org/en/latest/examples/osm-vector-tiles.html

### ISSUE THREAD

**Issue by ThomasG77** [openlayers/openlayers#7672]
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Due to Mapzen shutdown (see [announcement](https://mapzen.com/blog/shutdown/), the example http://openlayers.org/en/latest/examples/osm-vector-tiles.html will not work.
The action can be to remove the sample or to update it with another endpoint from "OpenMapTiles" or "Mapbox" or another vector tile provider if any.

**Comment by ThomasG77** [comment]
Follow-up With this announcement about 
[Long-term support for Mapzen maps, vector & terrain tiles](https://mapzen.com/blog/long-term-support-mapzen-maps/), this issue is now about creating an account for OpenLayers project using https://developers.nextzen.org and changing end-point url in the sample.

**Comment by matkoniecz** [comment]
Mapzen is still closed.

**Comment by matkoniecz** [comment]
Mapzen is still closed.
