### ISSUE TITLE
Missing tag for v4.6.4

### ISSUE THREAD

**Issue by geojs** [openlayers/openlayers#7674]
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

When I am looking the API doc or the release page for the v4.6.4, I have a 404 error: 
http://openlayers.org/en/latest/apidoc/ol.Map.html
click the link "src/ol/map.js" :
https://github.com/openlayers/openlayers/blob/v4.6.4/src/ol/map.js
=> 404 error

https://openlayers.org/download/
click the link " v4.6.4 release page"
https://github.com/openlayers/openlayers/releases/tag/v4.6.4 
=> 404 error

**Comment by ahocevar** [comment]
Tag created. Fixed.

Thanks for reporting this.
