### ISSUE TITLE
Icon font rendering broken since 4.4.0

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#7675]
Scenario: using FontAwesome for icons on map markers, like this:

```
new ol.style.Style({
  text: new ol.style.Text({
    text: '\uF013',
    font: 'normal 30px FontAwesome',
  }),
})
```

This code works perfectly up till 4.3.4, but is broken starting from 4.4.0.

Reproducable codepen here:
https://codepen.io/hyperknot/pen/NXgZyW?editors=0010

**Comment by hyperknot** [comment]
Will be in 4.7.0?

**Comment by ahocevar** [comment]
In 5.0.0.

**Comment by hyperknot** [comment]
How is it possible to get a build which fixes this? The https://openlayers.org/en/master/build/ol.js one, as of today, is still reproducing this bug.

**Comment by ahocevar** [comment]
The [ol package](https://npmjs.com/package/ol) has a 5.0.0-beta.5 version with the fix.

**Comment by hyperknot** [comment]
Is beta 6 also usable, or I'd better stay on 5?

**Comment by ahocevar** [comment]
When I last checked, there was no beta 6 yet. It's best to always use the latest, so use 6.
