### ISSUE TITLE
Should feature.clone() clone the style too?

### ISSUE THREAD

**Issue by raiyni** [openlayers/openlayers#7679]
It can create weird situations when you are  modifying the cloned feature for some reason. Doesn't seem intuitive if you don't already know it doesn't clone the style.

https://codepen.io/anon/pen/opojBB

```
var f2 = f1.clone();


f2.getStyle().setImage(new ol.style.Icon({
          color: '#ff0000',
          crossOrigin: 'anonymous',
          src: 'https://openlayers.org/en/v4.6.4/examples/data/dot.png'
        }));
```

See how both are now red

**Comment by cs09g** [comment]
I think it shouldn't be sync with target and cloned feature. its behavior seems like Object.assign(target) instead Object.assign({}, target) though I didn't check the code yet.

**Comment by simonseyock** [comment]
If feature.clone would clone the style, it would be more in line with the rest of the code (the geometry is cloned also and style.clone is deep, too). But on the other hand styles are meant to be shared between features. We should clarify the documentation either way.

**Comment by Cavva79** [comment]
Would be nice to be able to choose with a parameter to clone styles and eventually parameters too.
