### ISSUE TITLE
Rework the UTFGrid source

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7687]
Breaking changes:
 * rename module to `ol/source/UTFGrid.js`
 * rename `forDataAtCoordinateAndResolution` to `getData`, make it return data instead of accept a callback, make it fetch a tile if `preemptive` is false (queuing up async callbacks on events like `mousemove` is A Bad Idea™)

**Comment by fredj** [comment]
@tschaub for the second point; if there's no data when `getData` is called; the tile is fetched but `null` is returned ?
