### ISSUE TITLE
vectorsource.clear() function is clearing features from the view but not iternally from the source.

### ISSUE THREAD

**Issue by anujvictor** [openlayers/openlayers#7689]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [ ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by anujvictor** [comment]
i have a search criteria to display features. and an onclick function but it seems that features keeps adding in the vector source.

**Comment by raiyni** [comment]
Have an example?

```
var rome = new ol.Feature({
  geometry: new ol.geom.Point(ol.proj.fromLonLat([12.5, 41.9]))
});

rome.setStyle(new ol.style.Style({
  image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
    color: '#8959A8',
    crossOrigin: 'anonymous',
    src: 'https://openlayers.org/en/v4.6.4/examples/data/dot.png'
  }))
}));

var vectorSource = new ol.source.Vector({
  features: [rome]
});

var vectorLayer = new ol.layer.Vector({
  source: vectorSource
});

var rasterLayer = new ol.layer.Tile({
  source: new ol.source.TileJSON({
    url: 'https://api.tiles.mapbox.com/v3/mapbox.geography-class.json?secure',
    crossOrigin: ''
  })
});

var map = new ol.Map({
  layers: [rasterLayer, vectorLayer],
  target: document.getElementById('map'),
  view: new ol.View({
    center: ol.proj.fromLonLat([2.896372, 44.60240]),
    zoom: 3
  })
});


console.log(vectorSource);
vectorSource.clear();

console.log(vectorSource.getFeatures());
```

works just fine

**Comment by RalphLAtGitHub** [comment]
Using clear() with opt_fast=true may have caused your problem.

**Comment by ahocevar** [comment]
@anujvictor Can you provide a minimal example that shows your issue?
