### ISSUE TITLE
There is no build.js in tasks directory

### ISSUE THREAD

**Issue by SVoyt** [openlayers/openlayers#7690]
Trying to build OL, documentation says ```node tasks/build``` but there is no such file in repository

**Comment by ahocevar** [comment]
We are currently restructuring things in preparation for the [5.0 release](https://github.com/openlayers/openlayers/wiki/OpenLayers-v5.x). If you need a full build of OpenLayers, please use the 4.6.4 release for now. If you want to use the latest, there is no need to build anything. Just import the modules you need in your application code.
