### ISSUE TITLE
ol.style.Icon color does not work properly

### ISSUE THREAD

**Issue by mathiasleroy** [openlayers/openlayers#7699]
The doc says you can define `color` in ol.style.Icon

But it's not working. 
Here is a fiddle where I set `color` to red, but the icon appears black if `fill` is not defined in the SVG circle.
http://jsfiddle.net/0qo7g3r2/1/

If you define `fill` in the svg then that color is displayed.

[EDIT on v4.6.4]
On another map of mine which is using v4.6.4, color works if the fill is white.
if the fill is 'blue' then the color property can only be blue, not green nor red ; or it will render black.
if the fill is black then it will always render black, whatever the color property.
So I guess `color` of ol.style.Icon is kind of superposed on the `fill` of svg.

**Comment by Turbo87** [comment]
@mathiasleroy this seems to work as intended. The `color` is multiplied with the actual colors in the image you're using, so `#ffffff` will use the `color` that you specify, while `#000000` will stay the same.

**Comment by wzwxwc** [comment]
I had the same problem

**Comment by mattgreenfield** [comment]
As per the docs here https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html
`color` doesn't set the colour, it 'tints' the icon with that colour. I believe this also works with .png sources.
I've yet to find a solution to an SVG where I want one colour to change and the other to remain white.
