### ISSUE TITLE
ol npm version differes in proto names from openlayers version, instanceof break

### ISSUE THREAD

**Issue by seidlmic** [openlayers/openlayers#7714]
Hello,
I tried switch from `openlayers` package to `ol` package but i quickly found i have to change a lot of my code. Mainly the class/module names changed from `ol.layer.Tile` -> `Tile` and all prototypes names changed into `_ol_layer_Tile`

1)  Is this a final stage?
2) Is there feature/tool/instruction how to convert code?

Thanks Michal

**Comment by bartvde** [comment]
You should do instanceof checks with imports, e.g.:
```
import TileWMSSource from 'ol/source/tilewms';
olSource instanceof TileWMSSource
```

**Comment by seidlmic** [comment]
Hi, it is not so easy, as I try to write my own library based on ol package and use it externaly in other system (GeoExt, ...). and my  own old code and the old design `ol.source....` is used there. 

But some refactoring with `sed` looks to help the problem.

I hope that npm ol package name convection is final :)

**Comment by bartvde** [comment]
I'm not sure it will be, maybe @ahocevar or @tschaub can comment on that

**Comment by seidlmic** [comment]
Thanks for comment. Right now I solved it with refactoring `'instanceof'`and with penalty I have to use both libraries/packages. Old one for GeoEtx, ... code and  new `ol` I use in my new library.

M
