### ISSUE TITLE
Tile queues does not refresh(In VectorTileLayer)

### ISSUE THREAD

**Issue by ntjtomohide** [openlayers/openlayers#7715]
## Environment(Client)
- macOS High Sierra 10.13.2
- Processor 2.5 GHz Intel Core i5
- Memory 8 GB 1600 MHz DDR3
- Browser FirefoxNightly 59.0a1 (2018-01-16) (64-bit)

***

## Procedure
1. Go to example page (https://openlayers.org/en/master/examples/mapbox-vector-tiles.html)
2. Change the zoom level frequently
3. Some of the tiles will stop rendering(Please see a snapshot)

![image](https://user-images.githubusercontent.com/19971824/35037226-432035d6-fbba-11e7-8df5-ec354b8f9230.png)

***

## Confirmed
When I checked it, it seemed like a direct cause that the tile queue could not be updated.
I wrote the following code and it was possible to avoid the event that the rendering stops.

``` js
const clearQueue = () => {
  map.tileQueue_.tilesLoading_ = 0
  map.tileQueue_.tilesLoadingKeys_ = {}
}
setInterval(clearQueue, 100)
```

Is there any way to solve this problem from the ground up?

Looking forward to hearing from you.

**Comment by fredj** [comment]
related to #7271 ?

**Comment by ntjtomohide** [comment]
Thank you for response!!

It seems related it.
I'll try to migrate to latest version.

We will reply the result after testing.

**Comment by ntjtomohide** [comment]
Sorry for making you wait.
I tried it up to the latest version, but it can't resoleve issues.

OS: macOS High Sierra(10.13.2)
Browser: Firefox 60.0a1 (2018-01-30) (64-bit)
Openlayers: v^4.6.4

It seems not correctly update maxTotalLoading in PluggableMap.(Doesn't decrement)
Also, this issue cause in Vector Tile Layer only.(Tile Image Layer doesn't cause this issue.)

Could you help me to resolve this issue?

**Comment by ahocevar** [comment]
The fix is not in v4.6.4. You can use ol v5.0.0-beta.5 if you need the fix.

**Comment by 1258876595** [comment]
I have got the same issue in my project,especially when zooming out.
I avoid it by setting renderMode:'vector',just as writen in api doc about ol.layer.VectorTile,
but do not know why.Could you help me to explanate what cause this issue detail?
new ol.layer.VectorTile({
		renderMode:'vector'
})

**Comment by ahocevar** [comment]
For an explanation, please look at the fix that was linked above, and confirm that it works with the latest 5.0 beta.

**Comment by ntjtomohide** [comment]
Thank you for your reply.
We'll try to use the version 5.0.0beta!!

**Comment by heikkipora** [comment]
I can confirm that the issue (present in 4.6.5) cannot be reproduced with 5.0.0-beta.10
