### ISSUE TITLE
map.forEachFeatureAtPixel pbm with decluttering

### ISSUE THREAD

**Issue by moccand** [openlayers/openlayers#7717]
Features without labels while layer declutting option is enable are not found while using map.forEachFeatureAtPixel 

2 cases found : 
1) features not fully drawn because located at the map border :their labels are outside the map.
2) features fully drawn but without label because of label density and decluttering option

**Comment by moccand** [comment]
oops already discussed few days ago. I should have upadatetd my search before posting a new issue ...

#7664

**Comment by moccand** [comment]
fix for #7664 works only for select interaction. I still have the same issue with map.forEachFeatureAtPixel

**Comment by moccand** [comment]
fix for #7664  works only for select interaction. I still have the same issue with map.forEachFeatureAtPixel

**Comment by ahocevar** [comment]
The select interaction and forEachFeature at pixel use the same internal set of functions. Are you sure you have tested with the fix? Note that there is no release yet with this fix.

**Comment by moccand** [comment]
tested with 4.6.5 and it works nicely.
Thanks !
