### ISSUE TITLE
Small improvements for browserify tutorial

### ISSUE THREAD

**Issue by cholmes** [openlayers/openlayers#7719]
Hi, I was trying to do the browserify tutorial and got confused on the order of the steps, as it wasn't clear that you need to run the two commands after adding them to your script.

I made a branch with the fix, but then got scared on making a pull request due to all the checkboxes. But happy to make a PR for it.

https://github.com/cholmes/openlayers/commit/c52624a9be5e5c726f140c3811b9f3bf5b84db26

Also I had an error when I first tried running:

Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://192.168.0.119:8080
Hit CTRL-C to stop the server
module.js:538
    throw err;
    ^

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cholmes/Repos/new-project/node_modules/babelify/index.js:2:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
^Chttp-server stopped.

I managed to fix this myself, by doing: npm install --save-dev babel-core

Not sure if that was something with my set up, or if babel-core should be added to one of the install lines - I'm guessing others maybe have babel-core installed globally? I'm just getting started with javascript development, so that tutorial was my introduction to any of these concepts. Happy to make a PR for that one too if desired.

**Comment by ahocevar** [comment]
Thanks for willing to help with our documentation @cholmes! Please create a pull request, and don't worry about the checkboxes ;-).

I just ran through the tutorial myself and noticed two things:

 * It is indeed necessary to add `babel-core` as dev dependency. You can add that to the same pull request.
 * It looks like recent versions of watchify require a different order of arguments. So the "start" script line in `package.json` should read `"start": "watchify -g cssify index.js --outfile bundle.js & http-server",`.
 * It is not necessary to run `npm run build` before starting the dev server with `npm start`. The former is for creating a minified build (for deployment), and the latter is for testing locally.
