### ISSUE TITLE
Lines change appearance unnecessarily when zooming with renderMode: 'image'

### ISSUE THREAD

**Issue by codetrend** [openlayers/openlayers#7730]
Zoom in and out with each of the following jsfiddles which are the same except for the version of OpenLayers:

a) [OpenLayers 4.5.0 ](http://jsfiddle.net/wadefleming/34jesu6r/) - lines do not change width during zoom transition
b) [OpenLayers 4.6.0](http://jsfiddle.net/wadefleming/p5o0f6f9/2/) (and later) - when zooming in, lines become wide and blurry during the transition. When zooming out, lines become very narrow during the transition.

When using renderMode: 'vector' behaviour is as expected with both versions.

Expected behaviour: Lines do not change width while zooming with renderMode: 'image' as in 4.5.0 and earlier.

-----------------------------------------------------------------------------------------------------------
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
`renderMode: 'image'` is an option that was introduced with v4.6.0. So with v4.5.x and your snippet, you get the same as if you had `renderMode: 'vector'` in v4.6.x.

**Comment by codetrend** [comment]
I see - thank you for looking into this so promptly. 

Do if I do use this option, the zooming behaviour I have described is expected?

**Comment by ahocevar** [comment]
Yes, that zooming behavior you are seeing with `renderMode: 'image'` is expected. It's the same as what earlier versions had with `ol.layer.ImageVector` layers.
