### ISSUE TITLE
OpenLayers ol.format.WFS reaFeatures with EPSG:4326

### ISSUE THREAD

**Issue by Oryon86** [openlayers/openlayers#7733]
I try to use readFeatures method from ol.format.WFS but it doesn't work in my case.

I'm getting a lot of features from WFS in EPSG:4326. When I try to transform coordinates from these features into an other EPSG like EPSG:2154. It will return these features but coordinates are wrong...

If I try with EPSG:3949 -> EPSG:2154 ==> it works fine !

Code :

var wfsFormat = new ol.format.WFS({
                    gmlFormat: new ol.format.GML3(),
                    featureNS: layer.name.namespaceURI
                });

var features = wfsFormat.readFeatures(document,
            {   
                dataProjection: sourceProjection, //EPSG:4326 
                featureProjection: projection //EPSG:2154
            } 
);

**Comment by bartvde** [comment]
please don't open up github issues and stackoverflow questions

https://stackoverflow.com/questions/48380083/openlayers-ol-format-wfs-reafeatures-with-epsg4326
