### ISSUE TITLE
GML3 - WFS (DefaultSRS = EPSG:4326) Bad parsing

### ISSUE THREAD

**Issue by Oryon86** [openlayers/openlayers#7736]
I have a GetFeature response from WFS server which have EPSG:4326 as default srs : 

Example of GetFeature (WFS 1.1.0) Latitude/Longitude format
```
<gml:MultiCurve>
<gml:curveMember>
<gml:LineString>
<gml:posList>
48.43280195733815 4.7228979270717497 48.432722674997414 4.7228950702474055 ...
</gml:MultiCurve>
</gml:curveMember>
<gml:LineString>
<gml:posList>
```

GML3 parsing this response like this :

```
ol.format.GML3.prototype.readFlatPosList_ = function(node, objectStack) {
  var s = ol.xml.getAllTextContent(node, false).replace(/^\s*|\s*$/g, '');
  var context = objectStack[0];
  **var containerSrs = context['srsName'];**
  var containerDimension = node.parentNode.getAttribute('srsDimension');
  var axisOrientation = 'enu';
  if (containerSrs) {
    var proj = ol.proj.get(containerSrs);
    axisOrientation = proj.getAxisOrientation();
  }
...
```
context['srsName'] can change axisOrientation to 'neu' (EPSG:4326)

context('srsName'] is only setted here : 

```
ol.format.GMLBase.prototype.readGeometryElement = function(node, objectStack) {
  var context = /** @type {Object} */ (objectStack[0]);
  context['srsName'] = node.firstElementChild.getAttribute('srsName');
  ...
```

Attribute 'srsName' not available in geometry node

This method initialize 'context' property and 'srsName' is never initialized why?

```
ol.format.WFS.prototype.readFeaturesFromNode = function(node, opt_options) {
  var context = /** @type {ol.XmlNodeStackItem} */ ({
    'featureType': this.featureType_,
    'featureNS': this.featureNS_
  });
```

In my case, this property is never setted and i can't change axisOrientation to get geometry coordinates like this : 

[ 4.7228979270717497, 48.43280195733815, 4.7228950702474055, 48.432722674997414 ... ]

This format is needed to transform coordinates to an other coordinates system.

**Comment by bartvde** [comment]
you should be able to override the axis orientation of the projection before you parse with something like:

```
// override the axis orientation for WMS GetFeatureInfo
var proj = new ol.proj.Projection({
  code: 'http://www.opengis.net/gml/srs/epsg.xml#4326',
  axis: 'enu'
});
ol.proj.addEquivalentProjections([ol.proj.get('EPSG:4326'), proj]);
```

Make sure the code matches what you get back in your GML as the srsName

**Comment by Oryon86** [comment]
In my case, context['srsName'] is null and i never go into the 'if': 

```
if (containerSrs) {
    var proj = ol.proj.get(containerSrs);
    axisOrientation = proj.getAxisOrientation();
  }
```

And it's required to change axisOrientation property to 'neu'

If axisOrientation is 'enu', i get back coordinates like this : 

[ 48.43280195733815, 4.7228979270717497, 48.432722674997414, 4.7228950702474055, ... ] // Wrong

**Comment by bartvde** [comment]
what srsName is in your GML response?

**Comment by Oryon86** [comment]
EPSG:4326

**Comment by Oryon86** [comment]
Hi,

Is there a solution for this kind of problem? Or there will be a fix?

Thanks for the answer

**Comment by jessyst** [comment]
I have a similar issue, well an issue in the same piece of code. My geometry looks like this:

```
<dk:geom3d>
<gml:Curve srsDimension="3" srsName="http://www.opengis.net/gml/srs/epsg.xml#25832">
<gml:segments>
<gml:LineStringSegment interpolation="linear">
<gml:posList>
702947.343 6160237.201 46.75363692804333 702944.863 6160236.271000001 46.723636928043334 702943.393 6160235.821 46.78363692804333 702942.064 6160235.171 46.85363692804333 702940.974 6160234.081 46.863636928043334 702940.294 6160232.691000001 46.88363692804333 702940.064 6160231.721000001 46.82363692804333 702940.333 6160230.691000001 46.863636928043334 702941.514 6160229.852000001 46.80363692804333 702946.483 6160228.091 46.95363692804333 702953.473 6160225.562000001 47.123636928043325 703020.358 6160200.103 47.363636928043334 703027.7880000001 6160197.0540000005 47.21363692804333 703029.358 6160197.484 47.20363692804333
</gml:posList>
</gml:LineStringSegment>
</gml:segments>
</gml:Curve>
</dk:geom3d>
```

 So it tries to get:
`var containerDimension = node.parentNode.getAttribute('srsDimension');`

This results in the node gml:LineStringSegment

The actual srsDimention is 2 nodes up so it never converts the coordinates correct. It assumes that is has 2 dimensions

**Comment by Oryon86** [comment]
Hi,
I revive my question : 

"Is there a solution for this kind of problem? Or there will be a fix?"

Thanks for the answer

**Comment by Hanmac** [comment]
@Oryon86 this Pr might fix your problem: #7368 but for unknown reason it fails on the tests,
and i don't know how to fix this

**Comment by Oryon86** [comment]
Indeed, that's what I need. 

I don't know who can help you to fix this...

**Comment by adunham1962** [comment]
@bartvde is there any way this can be looked at?  Potentially some help with @Hanmac 's pull request #7368 ?  We are also having this issue with WFS layers.  The geometry nodes don't have an srsName attribute, but the gml:Envelope node does (urn:ogc:def:crs:EPSG::4326).  In the geometry node function, the code assumes a projection of EPSG:3857, which of course reverses the coordinates of features returned by the service in question.

**Comment by bartvde** [comment]
@adunham1962 I will see if I can find some time / energy to look at this, but to be honest I have not worked on this codebase in a long time

**Comment by adunham1962** [comment]
@bartvde , much appreciated.  Only tagged you since you appeared in the thread.  Feel free to pass this along to someone who isn't avoiding GML :)

**Comment by username-number** [comment]
I'm seeing the same issue @Hanmac  and @adunham1962. 

It would be great if something along the lines of https://github.com/openlayers/openlayers/pull/7368 could get accepted. @ahocevar what changes would be required to https://github.com/openlayers/openlayers/pull/7368 for it to get accepted?

**Comment by ahocevar** [comment]
#7368 would need to be reworked to not use imports instead of `ol.` namespaced symbols, and a test case that shows what did not work before, but does work after the change.
