### ISSUE TITLE
ol.Sphere.prototype.offset returns not accurate result.

### ISSUE THREAD

**Issue by sfedyna** [openlayers/openlayers#7737]
Hello

I've tried to figure out how to calculate destination point from start point, distance and bearing.
So I found method ol.Sphere.prototype.offset in your source code and tried to use it. That method returns not acceptable result. 

I compared results with google maps method google.maps.geometry.spherical.computeOffset and saw this:

var wgs84Sphere= new ol.Sphere(6371009);
wgs84Sphere.offset([8.9654,56.142588], 71, 315) = [8.966253997373613, 56.14301383429615]

google.maps.geometry.spherical.computeOffset(new google.maps.LatLng(8.9654, 56.142588), 71, 315) = [8.965850995148587, 56.14213142587573]

Where
8.9654, 56.142588 - start point in WGS84 (LatLon)
71 - distance in meters
315 - bearing in degrees

So you can see that difference between results is very big.
8.966253997373613 - 8.965850995148587 = 0.000403
56.14301383429615 - 56.1421314258757 = 0.000883

Can you help me to make results more accurate?

**Comment by ahocevar** [comment]
OpenLayers coordinates are [lon, lat], not [Lat, Lon]. So flipping the coordinates of the array should improve the result.

**Comment by sfedyna** [comment]
Your comment is very helpful.
Thanks a lot.
