### ISSUE TITLE
view.fit to extent actually don't fit

### ISSUE THREAD

**Issue by iGureEV** [openlayers/openlayers#7739]
It seems, that `fit` method check that at least one dimension should fit to calculate resolution to zoom? Shouldn't it take account both dimensions?

```javascript
var mapSize = map.getSize();
var extent = map.getView().calculateExtent( mapSize );
map.getView().fit( extent, mapSize );
console.log( extent, map.getView().calculateExtent( mapSize ) );
```

will output for example:
[4065803.7028887253, 6545812.793114994, 4070389.924585836, 6547226.87813827]

here extent y-axis is actually bigger than current map view y-axis.

Evident at the scale of less than 5 km.
Repeats issue #1611

Example, see https://jsfiddle.net/guruz/k20g84kv/

**Comment by ahocevar** [comment]
You have to use the `constrainResolution: false` option of `View#fit()`. See https://jsfiddle.net/zqnmntc7/ for an updated fiddle.

Also note that you are using `View#fit()` with an incorrect 2nd argument. To achieve what you want, use
```js
map.getView().fit(extent, {constrainResolution: false});
```
