### ISSUE TITLE
Geolocation getHeading returns undefined/0

### ISSUE THREAD

**Issue by siimots** [openlayers/openlayers#7742]
Issue: Geolocation does not return heading with getHeading function.

Demo: https://openlayers.org/en/latest/examples/geolocation.html

Tested browsers:
Android with latest Chrome: returns undefined
Android with latest Firefox: returns 0

(Heading works with standard HTML5 API and leaflet)
(Yes, I walked around to get different position reports)

**Comment by fredj** [comment]
Do you have better results with the device orientation example?
https://openlayers.org/en/latest/examples/device-orientation.html

**Comment by siimots** [comment]
Nope, it is also not working.

But this one is working:
https://mdn.mozillademos.org/en-US/docs/Web/API/Detecting_device_orientation$samples/Orientation_example?revision=1350174

From:
https://developer.mozilla.org/en-US/docs/Web/API/Detecting_device_orientation

**Comment by siimots** [comment]
Found out that
`trackingOptions: { enableHighAccuracy: true }`
is needed for Geolocation heading!

**Comment by fredj** [comment]
Good find ! I will update the geolocation example
