### ISSUE TITLE
ol.view extent doesn't work properly

### ISSUE THREAD

**Issue by sebalaini** [openlayers/openlayers#7744]
If you apply an `extent` to a layer and then also to the `view` you have a lot of white space around the layer.

I use the same extent for the layer and for the view. I add a screenshot, the location display the coordinates of the upper right corner of the layer, and in the console the coordinates I use for the extent of both layers and view.

Here a CodePen: https://codepen.io/sebalaini/pen/wpRVYL

![capture](https://user-images.githubusercontent.com/17096352/35433795-97ecf342-027c-11e8-9ad7-1a88fce9715d.PNG)

**Comment by ahocevar** [comment]
Not sure what you are trying to achieve, but see my updated CodePen for what I think you wanted: https://codepen.io/ahocevar/pen/xpvgXX.

The problem in your code is that the initial center of the view is not the center of the extent. To fix this, I am using `View#fit()` in my CodePen.

**Comment by sebalaini** [comment]
What I want to achieve is to have the view and the layer with the same size without all this white space around the layer.

Your CodePen also if you zoom out you have a lot of white space around, something I didn't put on the CodePen is the CSS style, the `map` div is all the window. so `width: 100% height: 100%` on all devices

**Comment by ThomasG77** [comment]
From my understanding, what you want is not possible ATM but I could be wrong.
The ratio for the map view depends from devices height and width and your layer extent may not have the same ratio: you will always have some borders due to the difference.
Using `map.getView().fit(extent, {constrainResolution: false});` (already illustrated in @ahocevar CodePen) can limit the issue.

**Comment by sebalaini** [comment]
I see, so the extent of the view and the layer are different due to the screen resolutions (especially in desktop) and the ratio 1.1 of the layer?  The extent of the layer and of the view are not strictly related?
The `{constrainResolution: false}` I don't know if I can use it, at the moment we are using WMS and we are going to switch to WMTS but we want to cache the tiles for performance so I've to check with the team.
