### ISSUE TITLE
OpenLayers Raster Example doesn't work

### ISSUE THREAD

**Issue by user201000** [openlayers/openlayers#7747]
OpenLayers Raster Source Example (editing version using codepen) doesn't work, maybe it has something wrong.. can you please check it
http://openlayers.org/en/latest/examples/raster.html

**Comment by raiyni** [comment]
You didn't link anything in the codepen.

The example works fine for me. You need to link to it with https.

**Comment by user201000** [comment]
Can you please explain more, how should I link it with http

**Comment by fredj** [comment]
This is because the api key of the Bing layer needs to be set in the js panel of codepen.
