### ISSUE TITLE
animate callback error

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#7748]
Normal function as a callback of `View.animate` works well but some functions which include `animate` doesn't work.  

[https://codepen.io/cs09g/pen/RQbXNq](https://codepen.io/cs09g/pen/RQbXNq)

**Comment by ahocevar** [comment]
In such cases you need to decouple the new animation from the animation event handler, simply by wrapping your function in `setTimeout`. See https://codepen.io/ahocevar/pen/KQKdbK for an updated fiddle.

**Comment by nikhilem** [comment]
@ahocevar  #7385 can be solved similarly using setTimeout. Is this a permanent solution or will it be fixed internally?

**Comment by tschaub** [comment]
I think it would be better behavior if the callback were called in the next tick, after all animation cleanup is done.  It should be possible to start another animation from the callback.  I'll put together a fix for this.
