### ISSUE TITLE
Load animated GIF on map

### ISSUE THREAD

**Issue by 100phel** [openlayers/openlayers#7753]
Hello, 

I would like to use GIF as a source of ImageWMS on OpenLayers Map. Currently, the map displays only the first frame of the GIF.

This request is connected to https://github.com/openlayers/openlayers/issues/4133

I tried Andreas Hocevar's approach to use canvas but did not manage to display the canvas on the map.

Here is my question on stackoverflow: https://stackoverflow.com/questions/48463981/use-gif-as-a-source-of-imagewms-on-openlayers-map

**Comment by qcawsome** [comment]
Workaround solution.
https://stackoverflow.com/questions/34596117/animated-gif-in-openlayers-3

**Comment by 100phel** [comment]
Thanks qcawsome, but the gif needs to be a layer on the map, for example a radar layer that conforms to the boundaries of the United States, not a div with a set width and height. So, when you would zoom in and out, the gif image would "stick" to the boundaries (changing its size respectively).

**Comment by 100phel** [comment]
The solution is in the new release of OpenLayers v4.6.5. Below is the example from their official website of how the animated WMS layer can be achieved:

https://openlayers.org/en/latest/examples/wms-time.html

**Comment by ZihengSun** [comment]
@100phel the layer in the example is not a GIF. The time control doesn't make sense in our case. This issue persists for me. Could you please give a direct example to load a GIF image? 
It is so difficult to just display a animated GIF in OpenLayers.

**Comment by 100phel** [comment]
I don't think it is possible to use GIF as a source of ImageWMS in the new version of Open Layers. My team and I tried different approaches, without success.

**Comment by jahow** [comment]
On the master branch Openlayers maps are now composed of a stack of HTML elements, as such it should be possible to have a proper GIF layer (which was not possible before as all layers were copied to a single canvas).

**Comment by gberaudo** [comment]
Rendering GIFs on the canvas is tricky. You will need to decode the GIF yourself so that you can draw each frame. See http://slbkbs.org/jsgif/ and https://stackoverflow.com/questions/48234696/how-to-put-a-gif-with-canvas

**Comment by ZihengSun** [comment]
@100phel  @gberaudo Thanks for the replies! Canvas looks so inconvenient for GIF. @jahow I'd like to try on the master branch. Would you please give some starting example snippets for using the stack of HTML elements?

**Comment by jahow** [comment]
You can take a look at #8931 which added a custom layer type.
