### ISSUE TITLE
ImageWMS "ratio" option only works when "serverType" is set

### ISSUE THREAD

**Issue by alfonx** [openlayers/openlayers#7755]
OL 4.6.4

The ["ratio" option of ImageWMS](https://openlayers.org/en/latest/apidoc/ol.source.ImageWMS.html) only works together with "serverType". Otherwise the ratio option is ignored.

The correct image size is also requested with serverType: 'blabla'. It doesn't work when serverType is not defined.

I recommend it should also work, even when serverType is unset. Or the documentation should be updated. Thanks.

See longer description here: https://gis.stackexchange.com/a/269950/1230

**Comment by fredj** [comment]
It's already mentioned in the documentation:
http://openlayers.org/en/latest/apidoc/ol.source.ImageWMS.html

For `serverType`:

_The type of the remote WMS server: `mapserver`, `geoserver` or `qgis`. Only needed if `hidpi` is `true`. Default is `undefined`._

And because `hidpi` is `true` by default, `serverType` is mandatory.

**Comment by alfonx** [comment]
> It's already mentioned in the documentation
From your viewpoint as OL developer that documentation probably makes sense.

But from a pure API users point of view, that is not very clear. Where is the connection between the `ratio`-option and `serverType`? The default value of `serverType` is incompatible with the default value of `hidpi`? Why is `blabla` a valid input for `serverType` ?

I think OL can improve the documentation here. Would it be helpful that I make a suggestion? Or does the majority not share my confusion? (Could be just me being bad at reading OL documentation)

So, feel free to close the ticket or I will try to help. ;-)

**Comment by ahocevar** [comment]
I think there is some confusion here. The `ratio` option works fine, even without `serverType` set. The `serverType` is only required when `hidpi` is set to true, because requesting images with a non-standard dpi is different for the supported server types.
