### ISSUE TITLE
Polygon created using fromExtent doesn't show up on map

### ISSUE THREAD

**Issue by PatrickHarriss** [openlayers/openlayers#7756]
Please see the codepen I have created here - https://codepen.io/PHarriss/pen/NyGzXq Use the create polyon button in the upper left corner to test the functionality. 

I am having an issue when I create a polygon using the ol.geom.Polygon.fromExtent (I assume any creation of a polygon will have this issue though) where it will not display on the map. If I am on the initial instance of the map it will work fine and create the polygon and the resulting polygon will be visible across all instances of the wrapping map. If I cross the 180 latitude a couple of times so the longitudes are > 180 (+ or -) then the polygon will no longer display on the map. 

After further testing I found that if I set the wrapX property on the vector to false then the polygon will display correctly but it is only visible in that particular instance of the wrapped map. So if you pan all the way out you will only see it once instead of multiple times like you do when drawing the polygon in the initial map instance. 

As a workaround I will try to normalize all of the longitudes in the polygon to be between -180 and 180 and see if that helps but this seems to be a defect in the way openlayers is handling wrapping of the longitudes.

**Comment by raiyni** [comment]
> As a workaround I will try to normalize all of the longitudes in the polygon to be between -180 and 180 and see if that helps but this seems to be a defect in the way openlayers is handling wrapping of the longitudes.

That happens in most mapping softwares I have found. I have attempted to fix it but it created issues when using extent based feature fetching.

**Comment by PatrickHarriss** [comment]
Normalizing the geometries seems to work fairly well in that the geometries will show up on all instances of the map regardless of how far you pan left or right. However, when you normalize the geometries when drawing a polygon that spans the 180 line it doesn't work well, this is where you need the longitudes that are > 180 or < -180. 

I think my best option at the moment is to set the wrapX attribute to false and use the longitudes that openlayers produces even if this means that the geometries will only show in the single map instance, at least they will show up. 

This still seems to be a defect in the way openlayers implements wrapping of geometries though.

**Comment by raiyni** [comment]
See https://github.com/openlayers/openlayers/issues/6088 for further investigation into the problem. If you want to do a custom build, you can fix it but you will run into problems if you do any loading from extent services. Or you can use a vector tile source.

**Comment by PatrickHarriss** [comment]
Thanks, I've settled on just setting the wrapX attribute to false for the vector layers that are causing issues. It's a work around that I can live with for now I think.
