### ISSUE TITLE
IE/Edge error on cloning a layer in a variable

### ISSUE THREAD

**Issue by sebalaini** [openlayers/openlayers#7758]
With the latest version of OL4, If you clone a layer from a previous window in IE and Edge it doesn't work.

The main 2 layers I use parameters and so, I don't need to clone the layer, but the drawing layer I called it from the windows it opens the "print window" and insert the "draw layer" as a variable.

With the production version, it works on all the other browsers, but not in IE/Edge

I use: 
`
var mainWin = window.opener;
var markLayer = mainWin.markLayer;

map = ....
   layers: [layers, pmfeatlayer, markLayer],
....
`

SCRIPT438: Object doesn't support property or method 'getLayerStatesArray'

  this.getLayers().forEach(function(layer) {
    layer.getLayerStatesArray(states);
  });

Reproducible also in Chrome with the debug version, it doesn't happen with the previous version. I was using the debug version with a CDN now I called it locally, I downloaded the code.

ol-debug.js:17395 Uncaught TypeError: layer.getLayerStatesArray is not a function
    at ol-debug.js:17395
    at ol.Collection.forEach (ol-debug.js:8289)
    at ol.layer.Group.getLayerStatesArray (ol-debug.js:17394)
    at ol.Map.ol.PluggableMap.renderFrame_ (ol-debug.js:18670)
    at ol.Map.<anonymous> (ol-debug.js:17624)

In IE/Edge the error happens if you draw something but if you don't draw anything the map is visible and it works. 
In Chrome with the debug version even if you don't draw anything you don't have the map and you already have the error.

**Comment by fredj** [comment]
The `getLayerStatesArray` function is not exported: it it not available in the production version.

For the issue you are seeing with the debug version; can you create a minimal codepen example that demonstrate the issue?

**Comment by sebalaini** [comment]
the issue with the debug (On chrome) I think is because I was using the production on the main and the debug on the print, I had the error at the second time I opened the print page.

If in the production version there is no such function how it works on all the other browsers and the problem is just on IE/edge?

There is a better way to clone a layer?

I don´t think I can create a CodePen, how can I add more pages? maybe a github repo.

The project structure is:
- www.URL/Index.html: `map,  feature layer, marker layer`with a button that opens a new page 
- same URL/print/print.html: with `map`(created from cero again) `feature layer`(created from cero but updated with parameters stored in a var and taken from the main page) `marker layer` stored directly in a var from the main page and inserted into the `layers` array

**Comment by sebalaini** [comment]
@fredj here I've done a little project and I have the same problem.

Repo:
https://github.com/sebalaini/Map_ol4

Live:
https://sebalaini.github.io/Map_ol4/

You can click on the print button and you will have the map, draw a map marker and click again on the print, no map it will show.
