### ISSUE TITLE
Vector Label Decluttering disable in webgl

### ISSUE THREAD

**Issue by treasureMoment** [openlayers/openlayers#7760]
http://openlayers.org/en/latest/examples/vector-label-decluttering.html?q=label

WebGL 
renderer:['webgl']
 var vectorLayer = new ol.layer.Vector({
        source: new ol.source.Vector({
          url: 'https://openlayers.org/en/v4.6.4/examples/data/geojson/countries.geojson',
          format: new ol.format.GeoJSON()
        }),
        style: function(feature) {
          labelStyle.getText().setText(feature.get('name'));
          return style;
        },
        declutter: true
      });
declutter disable

**Comment by ahocevar** [comment]
The webgl renderer does not support decluttering.

**Comment by treasureMoment** [comment]
How to achieve？help

**Comment by fredj** [comment]
The webgl renderer is gone, see https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#drop-of-support-for-the-experimental-webgl-renderer
