### ISSUE TITLE
get() only works for explicitly set() options on ol.Map/ol.View

### ISSUE THREAD

**Issue by ChrisHSandN** [openlayers/openlayers#7762]
The behavior of get() is different on ol.Map/ol.View compaired to ol.layer.*

```
var view = new ol.View({
    foo: 'bar'
});
view.get('foo'); //undefined

var tile = new ol.layer.Tile({
     foo: 'bar'
});
tile.get('foo'); //bar
```

if the value is explicitly set with a set() call then get() works as expected e.g.
```
var view = new ol.View();
view.set('foo', 'bar');

view.get('foo'); //bar
```
[https://jsfiddle.net/6qLe9pmL/](https://jsfiddle.net/6qLe9pmL/)

**Comment by fredj** [comment]
The properties in the constructor options only works for `ol.layer.Base` and all its subclasses.

**Comment by ChrisHSandN** [comment]
Thanks for clarify that, however this seems a bit inconsistent given that both classes inherit the get() method from ol.Object

Is accessing the properties directly through view.options.* the only way to get access to them?

**Comment by fredj** [comment]
Yes this is inconsistent that only `ol.layer.Base` has this feature (I think that it was a mistake to do this in the first place).
The only reliable way to get/set property to an object is to use the get and set functions without adding something to the constructor option.
