### ISSUE TITLE
Importing ES modules in browser does not work

### ISSUE THREAD

**Issue by bjornharrtell** [openlayers/openlayers#7766]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by bjornharrtell** [comment]
Demonstrated by https://codepen.io/anon/pen/jZrmXg?editors=1111.

The problem seem to be that bare imports are used for some external dependencies. The error is `Uncaught TypeError: Failed to resolve module specifier "rbush". Relative references must start with either "/", "./", or "../".`.

**Comment by tschaub** [comment]
Browsers don't have a good story yet for bare import specifiers.  There is ongoing work on the [Loader spec](https://whatwg.github.io/loader/) that is related.  And there are people experimenting with using Service Workers to handle these.  But the module story for browsers is still not complete - so this is not really an OpenLayers issue.

In the meantime (and maybe forever), it still makes sense to use a bundler.

**Comment by probins** [comment]
I'm rather late on this thread, but I did set up a ES version of OL usable in the browser back in the summer https://github.com/probins/oles but I've had 0 time to take this further. Until 3rd-party dependencies are converted upstream into minified ES modules (which probably won't happen until Node's implementation of ES modules is complete), it's easy enough to create a quick hack to convert them; this is much the same as the previous hack to make them compatible with `goog.require`. Most of them are only used by vector tiles, which are probably only a minority interest.

However, although the OL code can be used, it's less than optimal as the code needs restructuring so you can import only those chunks of code the user needs when they are needed. This is true of all existing JS code, not just OL. For example, proj4js also needs restructuring so you can import just one projection when the user loads a file/layer that uses it.

The loader spec is effectively obsolete and replaced by module script loading in HTML and dynamic `import()` from JS. In principle, this works well. I've been using it in Chrome for some time. However, Firefox has still not enabled it by default (planned in version 60), and AFAIK no minifier currently fully handles import/export. There are various proposals for preloading dependencies, and for extending `import` to handle other file types, such as HTML and CSS, but this is all still WIP. Plus there's the whole question of Node's implementation, which is also WIP.

So I'd agree it makes sense atm to concentrate on traditional bundle/builds. Once the current efforts are complete, I hope to find time to return to my browser-compatible version and make some suggestions on optimising the code for browser loading.
