### ISSUE TITLE
Get rid of externs

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7768]
Having externs requires that people who use the Closure Compiler maintain a more complicated build configuration that potentially breaks any time we release (e.g. with a new externs file they don't know about).

Most of the current externs files (e.g. `geojson.js`) can be replaced by using bracket notation in the few places that we read/write data (e.g. in `GeoJSON.js` there are four places where we need to quote object `'properties'`, and these could be reduced to two - one where reading and one where writing).  For type checking, we can add to the current `typedefs.js` file.

We are working separately to redistribute `externs/olx.js`, but I think we should separately start redistributing the other externs files.

**Comment by gberaudo** [comment]
Will it still be possible in application code to use a geojson extern for example? Or will it conflict with the definition in `typedefs.js`?

Because otherwise application code will have to migrate all their use of the dot notation to brackets.

**Comment by ahocevar** [comment]
@gberaudo Your application will not be affected by this suggested change. If you choose to use externs for your application, it will not conflict with any of your dependencies.

**Comment by gberaudo** [comment]
Great!

**Comment by ahocevar** [comment]
The code base does not rely on the externs in the `externs/` directory any more. So all that's left to be done here is remove the `externs/` directory.

The only case where these externs might be useful is application build stacks that use Closure Compiler in advanced mode. For those, these externs (if not available elsewhere) could be provided in more suitable, separate repositories/packages, and don't need to be maintained by the OpenLayers team.
