### ISSUE TITLE
WebGL error

### ISSUE THREAD

**Issue by Shekenix** [openlayers/openlayers#7773]
Hello. I have found webGL error with new version of Chrome. Check Your example here:
https://openlayers.org/en/latest/examples/reprojection-image.html?q=proj4

When You set some reprojected StaticImage to map object, webGL engine crashes.
I don't know if the problem occurs on any os, but i found it at Windows 10 platform.

Windows 10, Chrome 64.0.3282.140 (64-bit)

**Comment by gberaudo** [comment]
I tested with Firefox and Chromium on Linux and got no WebGL crash.

**Comment by Shekenix** [comment]
I recorded video to show You how problem look. The browser crashes and reprojection does not work.
I have application with reprojected images and bug kill my functionallities. I was searching the problem yesterday and i thought that something with my app is wrong, but later found the same error in your example.

[http://radar-opadow.pl/image_reprojection.mp4](url)

**Comment by gberaudo** [comment]
@Shekenix,:
- you are actually using the OpenLayers canvas 2d renderer;
- but your browser uses WebGL to accelerate the 2d canvas rendering;
- and there is a bug in your video drivers / chrome making it crash.

You should update your drivers and/or check your browser config reguarding WebGL acceleration.

@fredj, I think we should close this issue.
