### ISSUE TITLE
KML parses ExtendedData values as html

### ISSUE THREAD

**Issue by raiyni** [openlayers/openlayers#7775]
If an ampersand is present in a value for ExtendedData, the field is parsed as an html entity.

See the difference between:

```
<kml>
  <Document>
    <Placemark>
      <Point>
        <coordinates>0,0</coordinates>
      </Point>
      <ExtendedData>
        <Data name="test">
          <value>3&lt</value>
        </Data>
      </ExtendedData>
    </Placemark>
  </Document>
</kml>
```

and

```
<kml>
  <Document>
    <Placemark>
      <Point>
        <coordinates>0,0</coordinates>
      </Point>
      <ExtendedData>
        <Data name="test">
          <value>3&lt;</value>
        </Data>
      </ExtendedData>
    </Placemark>
  </Document>
</kml>
```

The value for test is a proper html entity and the top isn't.

https://codepen.io/anon/pen/WMGpoR?editors=0010#0

https://codepen.io/anon/pen/EQgmGK?editors=0010#0

Open the console for each and you see the value for test isn't set unless the entity is escape.

**Comment by marcjansen** [comment]
is the upper snippet well formed and valid xml?

**Comment by raiyni** [comment]
https://www.w3schools.com/xml/xml_validator.asp

Reports that the top is invalid xml.
