### ISSUE TITLE
Text rendering performance

### ISSUE THREAD

**Issue by adam987** [openlayers/openlayers#7778]
Recently we have updated OpenLayers from version 4.2.0 to 4.6.4.

After the update, we had noticed a performance issue related to a text rendering. We investigated this issue and came to the following conclusions:

* We have found that previously (in version 4.2.0), texts were drawn using HTML5 "fillText" method. In 4.6.4, texts are drawn as images.
* To reduce the number of image generations OpenLayers uses the cache https://github.com/openlayers/openlayers/blob/72ca7b28c6cfcff3b7b2e218bcc649cc1740b321/src/ol/structs/lrucache.js#L27.
* However, the text images cache has fixed size of 2048. https://github.com/openlayers/openlayers/blob/72ca7b28c6cfcff3b7b2e218bcc649cc1740b321/src/ol/render/canvas.js#L98
* We have only few texts and only few levels of zoom, but cache seems to be too small for us (as updateWhileAnimating is set to true). When zooming in and out, the cache is practically continuously cleared. It causes a drastic performance decrease (FPS drop).

I think that enabling users to change LRUCache size can be helpful in similar situations. Can we get some advice on how we can improve performance for now? Will the concept of adjustable cache size be introduced in the next versions? 

We can prepare proper pull request if needed (we will appreciate the advice where this option could be provided).

**Comment by gralin** [comment]
adjustable cache size 👍
