### ISSUE TITLE
ol.style.stroke.width can't be set to 0

### ISSUE THREAD

**Issue by trojan-ann** [openlayers/openlayers#7786]
I have set the ol.style.stroke.width to 0,but I stil see the point have 1px stroke

**Comment by marcjansen** [comment]
Can you provide a codepen?

**Comment by trojan-ann** [comment]
here you are. [https://codepen.io/Vein/pen/bLgxwX](url). In the js block,line 19,I have set the strokeWidth to 0，but I stil see the stroke of the point in the map

**Comment by trojan-ann** [comment]
there is something confused me that when I set the strokeWidth to 0.00000001, there is no stroke in the point

**Comment by cs09g** [comment]
right, it's true. I guess, somewhere in the code, there's missing type check. used `width ? width : defaultvalue` instead `isNaN(+width) ? width : defaultvalue`

**Comment by fredj** [comment]
The width value is correctly passed to the canvas but it's ignored (setting the value to 1).

See https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineWidth :
_When setting, zero, negative, Infinity and NaN values are ignored_

**Comment by ahocevar** [comment]
Also what's the point of having a stroke with a width of 0? Just configure your style without an `ol.Stroke`.

**Comment by christophfriedrich** [comment]
Setting the width to 0 is the workaround that people come up with when they either (a) think that not configuring a stroke probably causes the default to be used or (b) discover that not supplying a stroke breaks the rendering (see my separate issue). There seems to be no documentation that explicitly says "just leave it out" to style without a stroke -- this possibility is only indirectly implied by the "optional" flag of `Style`'s `stroke` property.
