### ISSUE TITLE
HiDPI / retina / pixelRatio zoom levels for tiled image sources (Zoomify, etc.)

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#7795]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

When viewing tiled raster images, I believe the right selection strategy for HiDPI screens is to always have close to 2x (or DEVICE_PIXEL_RATIO *) the number of pixels on the zoom level, except on the last zoom level, where 1x sampling should be allowed. 

Unlike on an OSM map with labels, a tiled image sources should underzoom by default on HiDPI screen. That is, an photograph or scanned document is automatically "Retina" or HiDPI if looked at a level lower.

I've almost finished porting the reference IIIF implementation from OpenSeaDragon to OpenLayers, but this one just puzzled me.

// Also, should I wait more before everything settles for 5.0.0 or is Zoomify.js considered stable now?

**Comment by crubier** [comment]
This problem is still there on latest versions. And it's funny but I keep seeing its consequences  everywhere on the web. It is impacting:

 - The application I build at www.sterblue.com
 - Our competitor at www.scopito.com 
 - This astronomy web app https://scope.avocco.com/case/20/eWKcUiIXpuQU9V0z

On all of these, if you zoom in with a retina screen, the image is blurrier than it should be.

**Comment by crubier** [comment]
And my PR #9110 did not fix it, unfortunately

**Comment by guatedude2** [comment]
The problem from looking at the code in `src/ol/source/Zoomify.js` is on line 42 of`CustomTile`. when changing that line to:
```
this.tileSize_ = [512, 512]
```

It fixes the problem, I also tried removing the custom zoomify class on line 254 and it fixes the problem as well. I'm not entirely sure what the `CustomTile` does different than the `ZoomifyTileClass`
```
tileClass: ZoomifyTileClass,
```

**Comment by crubier** [comment]
@guatedude2 no changing tileSize does not work at all. Here is the result

<img width="840" alt="Screenshot 2019-05-03 at 13 09 35" src="https://user-images.githubusercontent.com/2954572/57136437-c47b7480-6da4-11e9-8875-86c2791e6b3e.png">

**Comment by crubier** [comment]
You gave me false hopes !

**Comment by guatedude2** [comment]
Are the images you’re using retina @2x?

**Comment by guatedude2** [comment]
Basically your tile images should report as 256x256 but the images should be 512x512 otherwise it doesnt work

**Comment by crubier** [comment]
I get your point, but even then the problem is not fixed, because as we see in the screenshot above, the images would be displayed 2 times larger. So even if images are 512 they would then be displayed on 512 pixels so still not retina.

I might have not understood your suggestions.

**Comment by guatedude2** [comment]
In order to render retina tiles you need 512x512 tiles and set the pixel ratio to 2 meaning it draws a 512x512 image as a 256x256. Check this example out https://openlayers.org/en/latest/examples/xyz-retina.html
Try using this source for your test:
`url: 'https://tileserver.maptiler.com/grandcanyon@2x/{z}/{x}/{y}.png?{TileGroup}',`

**Comment by crubier** [comment]
> I'm not entirely sure what the CustomTile does different than the native ImageTile.

It manages cases where tiles are "cropped" on sides of the images. Without this the last tiles row and column on the right and bottom are distorted if the image size is not a multiple of tile size.

**Comment by crubier** [comment]
Ok I think I fixed this https://github.com/openlayers/openlayers/pull/9489
