### ISSUE TITLE
Remove lib argument for raster sources

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7796]
Currently, raster sources take an `operation` and an optional `lib`.  The `lib` can include functions that get serialized and made available in the worker.  The `data` object passed to operations is already a place for user-provided values.  The `lib` option should be removed in favor of passing any serializable functions via the `data` object.

**Comment by tschaub** [comment]
I'm going to remove the 5.0 milestone from this.  We can deprecate this sometime in 5.x and remove it in 6.

**Comment by saurabhgis** [comment]
I want to store pixel value in array and want to do some operation on array value, I declared the array in lib:{..} but not able to push values in that array.. my primary purpose is to add values into array which will be available outside raster source....please suggest

**Comment by tschaub** [comment]
You can use the data object in the operations events for this purpose.  I don’t have a link handy, but one of the raster examples shows this.

**Comment by saurabhgis** [comment]
@tschaub Sir I have tried lots of more but not able to do this task, my requirement is to save pixel values in array and calculate the average pixel values..i have tried before, after operation but not succeed. 

I also tried to declare array variable in lib function but push method not working, request to suggest some solution.

**Comment by saurabhgis** [comment]
@tschaub If you have any link related to data object inside operations, please share

**Comment by tschaub** [comment]
In the raster example, properties are added to the `event.data` in the `beforeoperations` listener: https://github.com/openlayers/openlayers/blob/17b37a90da545dcf1f04548186812699d0efcb71/examples/raster.js#L101-L104

Those data properties are accessed (and updated) in the source's operation: https://github.com/openlayers/openlayers/blob/17b37a90da545dcf1f04548186812699d0efcb71/examples/raster.js#L67-L80.  This is the function that runs in a worker.

And then the values are accessed again in the `afteroperations` listener (back in the main thread): https://github.com/openlayers/openlayers/blob/17b37a90da545dcf1f04548186812699d0efcb71/examples/raster.js#L106-L108
