### ISSUE TITLE
Look for an alternative to the JWT plugin for our Travis config

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#7798]
See https://blog.travis-ci.com/2018-01-23-jwt-addon-is-deprecated. We are using the plugin to pass credentials to other remote services. We need to check if there are different ways to integrate these services. This is especially crucial for our tests, which are run through ~~coveralls~~ SauceLabs.

**Comment by marcjansen** [comment]
Coveralls is only for the coverage... which is right now not calculated / posted.

**Comment by ahocevar** [comment]
I meant SauceLabs, sorry.

**Comment by ahocevar** [comment]
This is the article that describes what we did: https://docs.travis-ci.com/user/sauce-connect/. An alternative would be to have the credentials in there in clear text, which does not feel right either.

**Comment by fredj** [comment]
According to https://docs.travis-ci.com/user/sauce-connect/, the credentials can also be set as environment variables in the travis settings page: https://travis-ci.org/openlayers/openlayers/settings

**Comment by fredj** [comment]
> Sure, but others can dump them if they want to.

The environment Variables can be hidden from the build log

**Comment by DanielRuf** [comment]
> The environment Variables can be hidden from the build log

It's just the log. Dumping env is normally still possible for everyone afaik.

**Comment by fredj** [comment]
#8883
