### ISSUE TITLE
DEVELOPING.md refers to old process

### ISSUE THREAD

**Issue by bradh** [openlayers/openlayers#7804]
https://github.com/openlayers/openlayers/blob/master/DEVELOPING.md refers to the old Makefile based process.

- [X ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [X ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [X] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [N/A] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
Thanks for creating this ticket @bradh. We're in the process of changing everything to be purely ES module based, so our new DEVELOPING.md will be very short. Contributions to improving that document are of course welcome, otherwise we'll update it as we get closer to the 5.0 release.

**Comment by raiyni** [comment]
What about including the usage of a standardized formatting tool like Prettify?

**Comment by raiyni** [comment]
What about including a more advanced formatter than `.editorconfig` like Prettify?

**Comment by fredj** [comment]
fixed
