### ISSUE TITLE
Does translate interaction is available in Openlayers 4 ? 

### ISSUE THREAD

**Issue by kingofnull** [openlayers/openlayers#7819]
Actually I'm searching for a interaction like `Transform` in version 3 that can scale , rotate and move vector feature on ol4 but I didn't find any working example. 
I also need to combine it with modify interaction. 
So please if it is steal available in offer me an example that can does thoese or If it's not guide me how to do that. 

Thanks

**Comment by raiyni** [comment]
You would have to write your own based on Pointer, like Translate is. 

See https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/Translate.js

**Comment by kingofnull** [comment]
@raiyni I did it before but the modify don't works any more! you can find it here:
https://gist.github.com/kingofnull/0ad644be69d8dd43c05721022ca5c3a5

**Comment by kingofnull** [comment]
Thanks! I test again and wow the translate works like a charm. And about combining it with modify it need to add before modify interaction and it works without conflicting the modify interaction. here if my final code:

```
var map = new ol.Map({...});
var featureDrager = new ol.interaction.Translate();
var modify = new ol.interaction.Modify({...});
map.addInteraction(featureDrager);
map.addInteraction(modify);
```
