### ISSUE TITLE
Production build behaving different from debug

### ISSUE THREAD

**Issue by EvanVujcec** [openlayers/openlayers#7829]
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

When using ol.js I recieve the following error (its an AngularCLI project so webpack is used):
```
ERROR TypeError: a.U is not a function
    at U.k.Gb (scripts.bundle.js:689)
    at RimComponent.displayCoord (webpack-internal:///../../../../../src/app/rim/rim.component.ts:32)
    at ZoneDelegate.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:388)
    at Object.onInvoke (webpack-internal:///../../../core/esm5/core.js:4961)
    at ZoneDelegate.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:387)
    at Zone.runGuarded (webpack-internal:///../../../../zone.js/dist/zone.js:151)
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:129)
```

When using ol-debug.js the following code works as intended and throws no errors meaning I can't get any traceback for CodePen but the problem comes from the vectorSource.addFeature:

```javascript
static displayCoord(pos) {
    const tCoord = ol.proj.fromLonLat([pos.coords.longitude, pos.coords.latitude]);
    coord[0] = tCoord[0];
    coord[1] = tCoord[1];
    map.getView().animate({center: coord, zoom: 17});
    vectorSource.addFeature(new Feature({
      geometry: new Point(coord)
    }));
}
```

This is exceptionally confusing since I've never seen a debug behave so different from a production build.

Send Help

**Comment by raiyni** [comment]
Without your code, or a codepen with this issue, it's hard to say what is wrong with your webpack.

**Comment by EvanVujcec** [comment]
@raiyni https://github.com/RelationalImageMap/web-app/blob/master/src/app/rim/rim.component.ts

OpenLayers is the only external JS library currently being used so when I `ng serve` the scripts.bundle.js contains only a direct copy of ol.js. Webpack doesn't seem to do anything to it.

**Comment by raiyni** [comment]
Have you tried with https://github.com/openlayers/openlayers/tree/beta ?
Previously, ol wasn't proper ES modules.

**Comment by EvanVujcec** [comment]
Don't know what the issue was but I decided to just refactor everything using the type definitions from @types/openlayers which is probably what I should have done in the first place.

Thanks anyway @raiyni
