### ISSUE TITLE
Export PDF example doesn’t work properly

### ISSUE THREAD

**Issue by Hareck** [openlayers/openlayers#7830]
http://openlayers.org/en/latest/examples/export-pdf.html?q=pdf
This example doesn’t work properly:
1. If Page **size = ‚A5‘** the example doesn’t work, no pdf export. The example got hung up. 
Only a reload of example page is possible.
2. If used the **Export PDF**  Button a second time without changes of **Page size** and **Resolution** the example also got hung up, no pdf export.
Tested with browser:
Google Chrome Version 64.0.3282.167 (Official Build) (64-Bit)
Firefox 58.0.2 (64-Bit)

**Comment by fredj** [comment]
@trenneman can you please take a look at this issue?

**Comment by trenneman** [comment]
@fredj Sure - it's been a while since I worked with ol3, but I'll have a look.
It seems the development mode of the examples is broken. Will that be fixed any soon? It's hard to debug for now.

**Comment by fredj** [comment]
The development mode has changed a lot, you can find the new instructions here:
https://github.com/openlayers/openlayers/blob/master/DEVELOPING.md

Thanks!
