### ISSUE TITLE
Zoom slider broken in Safari

### ISSUE THREAD

**Issue by ChristianSiegert** [openlayers/openlayers#7846]
**Summary:**
Zoom slider control is broken in Safari.

**Steps to reproduce:**
1. Open http://openlayers.org/en/latest/examples/zoomslider.html in Safari.
2. Center the map over a landmass (anything other than water) to see changes when zooming.
3. Drag the map’s zoom slider up and down several times.

**Actual result:**
The slider does not move down, only up.

**Expected result:**
The slider will move up and down, following the mouse cursor.

**Environment:**
Tested and found broken in Safari 11.0.3 and [Safari Technology Preview Release 49 (Safari 11.2, WebKit 13606.1.3.3)](https://developer.apple.com/safari/technology-preview/) on macOS 10.13.3. The zoom slider works in Firefox and Chrome.

You can [see the bug in action](https://youtu.be/bk3aRZ9pXSQ?t=25s).

**Comment by torre9** [comment]
Is this issue fixed? If so, then why is this issue still open? I am seeing this same issue on version 3.20.1 on Multiple browsers like Chrome, IE 11. But the weird thing is that it works fine on Firefox.
