### ISSUE TITLE
Vector tiles MVT format on custom projection is rendered 0.5m differently on y axis from geojson or topojson

### ISSUE THREAD

**Issue by panterz** [openlayers/openlayers#7856]
I have created a WMTS layer that accepts either geojson or topojson or mvt format. Because of the high density of data I would like preferably to cache the tiles in pbf format, however there are rendering issues compared to a WFS geojson or wmts of the same layer in geojson or topojson format. The vector tiles layer in mvt format is mislocated by 0.45 on y axis, whereas all the other formats are being rendered accurately. I had to manually decreased the y origin of that zoom level. 
Any ideas of why this could be happening?

**Comment by chrismayer** [comment]
Did you use GeoServer / GWC for the creation of the MVTs? If yes, I had some similar effect a few month ago:

The reason were the resolutions which were used by  GeoServer / GWC. These resolutions were derived from scales and have been rounded. So it came to an offset (like you described), if I used the "non-rounded" resolutions in my layer properties. By setting the rounded resolutions in my VT-layer everything worked fine.

Hope this helps somehow.
