### ISSUE TITLE
ol.source.Vector#forEachFeature skips features without geometry

### ISSUE THREAD

**Issue by mkedo** [openlayers/openlayers#7862]
When calling forEachFeature(callback, opt_this), the callback is not called with features that have no geometry.

Code that shows the issue:
https://codepen.io/anon/pen/LQdrVa
`
var source = new ol.source.Vector();
source.addFeature(new ol.Feature());

console.log(source.getFeatures().length); // 1

source.forEachFeature(function (f){
  console.log("forEachFeature"); // won't show up
}); 
`

If it is by design then the docs don''t state it clearly.
Excerpt from the api docs:
https://openlayers.org/en/latest/apidoc/ol.source.Vector.html#forEachFeature
"Iterate through all features on the source, ...."

Tested with v4.6.4

**Comment by fredj** [comment]
I don't know if it's by design but you can you use the `getFeatures()` function instead:
```
source.getFeatures().forEach(function(f) {
  console.log("forEachFeature");
});
```

This function returns an Array of features
