### ISSUE TITLE
using image and vector tiles out of WM(t)S getCapabilities

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#7869]
Gentlemen, 

I can't find any examples of my problem, so i post the question here. Perhaps together we can work out a nice new example.

The problem i have is that we have geoserver with serveral services running (TMS, WMS, WMTS) but all have problems.
- TMS has almost no meta-data, so we can't show our users copyright info (attributions) or figure out if a layer is a base layer or an overlay.
- WMS does provide all that, but it doesn't provide supported response types of the layers (png, jpeg or x-protobuf;type=mapbox-vector)
- WMTS does provide the supported response types, but i miss attributions and also information about the layer being a baselayer or an overlay.

Now i noticed that our server (geoserver) does return a valid (vector)tile when we provide our ol.source.TileWMS with a 'params.FORMAT' string containing (i.e.) 'application/x-protobuf;type=mapbox-vector'.
Combined with a trick in our geoserver configuration (adding a specific Keyword to figure out the layer supports that particular format), we can use the WMS getCapabilities to give us both image as vector tiles.

BUT!.
nothing happens in openlayers..
i see requests in my browser requesting uri's like these:
http://server.local/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=application%2Fx-protobuf%3Btype%3Dmapbox-vector&TRANSPARENT=true&LAYERS=ks%3Abuildings&WIDTH=256&HEIGHT=256&CRS=EPSG%3A28992&STYLES=&BBOX=135798.4%2C455732.80%2C135952%2C455886.4

Now i can handle the fact that a ol.layer.Tile layer doesn't work with vector tiles, but how do i use the ol.layer.VectorTile based on the information i got from the WMS capabilities?

so far i've tried:

- using ol.layer.VectorLayer containing an ol.source.WMTS, but i don't know how to format the url. and providing the WMS url only hangs the rest of openlayers (stops all layers from loading)
- using ol.layer.VectorLayer containing an ol.source.TileWMS, but although i see valid http calls (that do provide data) the data isn't interpreted as and image..
- using ol.layer.VectorTile containing an ol.source.VectorTile with the TMS url. I do get 200 OK, responses and url's are formatted correctly, but i never get data. All responses are 0 bytes
- using ol.layer.VectorLayer containing an ol.source.VectorTile with wmts url

**Comment by ahocevar** [comment]
This has been done before with WMTS. See https://2016.foss4g-na.org/sites/default/files/slides/Foss4G_VTs_FINAL.pdf. You can do the same with WMS. All you need is the `tileGrid` and `tileUrlFunction` of your source, and configure an `ol.source.VectorTile` with that.
