### ISSUE TITLE
GeoJSON.readFeatures gone?

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#7878]
I'm in the process of migrating our entire codebase from the old browserify version using the bundled 'ol.js' to the new ol package for 5.0 beta, using Webpack, to solve some issues which won't be backported to 4.x.

I think everything went well with replacing the imports, except for GeoJSON.readFeatures (and possibly other parts of GeoJSON).

Before we had this:
```
var geojsonFormat = new ol.format.GeoJSON()
var features = geojsonFormat.readFeatures(data.features_geojson)
```

Now, I'm trying to do:
```
const GeoJSON = require('ol/format/GeoJSON').default
var features = GeoJSON.readFeatures(data.features_geojson)
```

But it doesn't work, telling me that readFeatures is not a function.

Now, at this point I normally ripgrep the examples on the master branch, or the full repo on the master branch, but to my biggest surprise `readFeatures` is not present even a single time on the master branch.

Yet, somehow it's still present in the 5.0.0-beta.5 npm package, so I'm even more confused. What happened to readFeatures?

**Comment by ThomasG77** [comment]
You simply didn't replace well the code when you made the changes. You should instanciate GeoJSON e.g below code:

```
const GeoJSON = require('ol/format/GeoJSON').default;
const geojsonFormat =new GeoJSON();
const features = geojsonFormat.readFeatures(data.features_geojson)
```

**Comment by tschaub** [comment]
```shell
$ grep -r readFeatures src | wc -l
      59
```

For the GeoJSON format, the implementation is here https://github.com/openlayers/openlayers/blob/ca4dfb9ec3ac7b7138296f0f7e39f38b1d0f6ec9/src/ol/format/JSONFeature.js#L49-L55

And here is an example that uses it: https://github.com/openlayers/openlayers/blob/ca4dfb9ec3ac7b7138296f0f7e39f38b1d0f6ec9/examples/geojson.js#L163-L165

And here is how you can use it in 5.x:
```js
import GeoJSON from 'ol/format/GeoJSON';

const format = new GeoJSON();
format.readFeatures(/** your data here */);
```

**Comment by hyperknot** [comment]
Sorry, this was very much my bad, in the big refactoring of replacing strings, I've removed all readFeatures from ol source, and of course I didn't find them.

@ThomasG77 right now it's GeoJSON, actually, it's really annoying to jump between OL4 <> OL5 beta, as the whole project's imports need to be rewritten. Does anyone have a good workaround for this?
