### ISSUE TITLE
Webpack production build fails with 5.0.0-beta

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#7879]
- [X] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [X] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [X] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [X] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

I'm using Create React App for it's polished development and production Webpack configs, to bundle an app using OL5 beta. It's not actually using React, but Create React App is simply the best resource for a production ready Webpack setup.

Development / watch mode works perfectly.
However production build terminates, with the following message:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/ol/index.js:24

Read more here: http://bit.ly/2tRViJ9
```

The links goes here: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

The first point in the linked page asks to open an issue here, so I believe this has something to do with OL and not with webpack config. Still it's strange as the development mode seems to work fine, probably the issue is not too big.

**Reproducible case**

```
npm install -g create-react-app
create-react-app oltest
cd oltest
yarn add ol@5.0.0-beta.7
echo -e "import ol from 'ol'\n$(cat src/App.js)" > src/App.js
yarn build
```

**Comment by fredj** [comment]
maybe related to #7870

**Comment by fredj** [comment]
I've published a new beta release: 5.0.0-beta.7
Can you test with this one?

**Comment by hyperknot** [comment]
@fredj nope, the same with beta 7.

Reproducible case:

```
npm install -g create-react-app
create-react-app oltest
cd oltest
yarn add ol@5.0.0-beta.7
echo -e "import ol from 'ol'\n$(cat src/App.js)" > src/App.js
yarn build
```

**Comment by raiyni** [comment]
Webpack doesn't like the `let` keyword.

**Comment by hyperknot** [comment]
OK, the core of the issue here is that 
1. UglifyJS and many browsers only work on ES5 code
2. OL5 beta started to publish ES6 code to npm

AFAIK, the front-end-on-npm ecosystem so far considers the standard approach to publish ES5 code to npm, just like with OL 4 did. 

This seems to be indeed the case: I did a grep in my bigger node_modules folder and none of the modules had any `let` keyword in, and if they had, it was just in an optional "src" folder, not in the main js code.

So we can say that right now, the standard approach is to publish ES5 compiled version to npm.

Now, if OL 5 wants to brake this tradition and publish ES6 code to npm, there needs to be additional instructions in how to babelify it's code as well during build. This would effect every single project ol is used in! The problem is not just UglifyJS, the actual problem is browsers not supporting ES6 (like IE10).

I think, somewhere hidden in this thread is the configuration needed to make webpack babelify module's code, not just user's code, but I'm not so sure about it: https://github.com/webpack/webpack/issues/2972

But please understand that with this approach you are requiring all of your users to implement a very unusual configuration in their build setup, what will have to be solved on a case-by-case bases, as each build config is quite different.

Right now, the only workaround with OL 5 is to copy the ol source code into a user side folder, and replace all includes from `'ol/some/thing'` to `'./ol/some/thing'`. This workaround actually works, the bundled code is transformed to ES5. The downside is that we've pretty much included ol's source code in a project.

**Comment by simonseyock** [comment]
To process a folder out of node_modules with babel-loader you have to modify the include/exclude options. i.e. `exclude: /(node_modules.(?!ol))/` does work. `exclude: /node_modules/, include /node_modules/ol` should work, too. Or maybe even remove the exclude.

But I agree that this is rather uncommon. The lodash library for example is written in es6 and modularized (https://github.com/lodash/lodash). But if you look at the published code you see that all modules are commonjs es5. (another example is rxjs https://github.com/ReactiveX/rxjs).

I would normally expect code inside of node_modules to be es5. This should be possible to do by just running babel over the openlayers source before publishing (without webpack). After it can still be imported via es6 imports but is valid es5 and works with normal webpack builds where node_modules are excluded from babel-loader.

**Comment by hyperknot** [comment]
Yes, I think the key is to make it modular, which works perfectly fine with ES5 modules. Only the ES6 features need to be babel-ified, like `let`.

The is would be not to require users to change their webpack/browserify/rollup/etc. whichever custom build system they came up with. For example in create-react-app there is no `exclude` directive.

**Comment by simonseyock** [comment]
> This should be possible to do by just running babel over the openlayers source before publishing (without webpack)

That means use the npm package `babel-cli` like this: `babel src/ol -d dist` (would publish to dist folder)

**Comment by ThomasG77** [comment]
A working example using existing @tschaub minimum sample for OpenLayers 5.0.0-beta.7 https://gist.github.com/ThomasG77/064382a2462f65cfc78fe18d4254290e

**Comment by hyperknot** [comment]
@ThomasG77 while a nice example, do you agree that by going this path OL5 is saying, that "out of all the tens of thousands of modules in the npm ecosystem, OL5 is going to be an anti-pattern which will not work with any module bundler, unless manually configured to do so"?

**Comment by ThomasG77** [comment]
@hyperknot I just added a solution to the issue but I understand your point :)

As you already stated, current publishing strategy is not user friendly as I need to add custom things instead of using a solution that works out of the box for most cases and users.
I'm also using Parcel JS instead of Webpack and didn't solve the issue to use OpenLayers 5 with it so I understand your pain.
So, I would follow your recommendation to publish transpiled ES6 to ES5 like most other npm packages. There is [a good recipe](https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/) for this purpose.

**Comment by panuchka** [comment]
Currently modularising our Openlayers implementation and ran into this problem as well. Had to spend a lot of time to handle the babelification of the library and to figure out why it didn't work on IE11. Easiest answer was to add the babel-polyfill as hyperknot mentioned earlier.

I too would highly recommend that future ol npm releases are es5, since this is really not very developer friendly. Since we have to add babel-polyfill, the bundle size is getting a bit larger as well, which is not very nice for a performance critical sites.

**Comment by jirihajek** [comment]
I found out that this is an issue with an old Webpack only, the latest version works well. The latest production version of react-scripts (1.1.4) uses an old Webpack, but if you install react-scripts@next (2.0.0), it uses a newer Webpack version which is able to build OL5.

Not sure whether this can be considered a solution, but possibly yes.

**Comment by gimerstedt** [comment]
i would not suggest openlayers to anyone with the current method of publishing. i have yet to upgrade to OL5, still on openlayers4.x. i am using webpack4 and typescript to compile (no babel). 
it's not exactly straight forward to upgrade with both additional compilation of a dependency as well as missing (or out of date) type definitions.
