### ISSUE TITLE
ScaleLine shows wrong values in version 4.6.4 for EPSG-4326

### ISSUE THREAD

**Issue by olsinao** [openlayers/openlayers#7883]
In version 4.6.4 Scale Line is showing the wrong value when using km or miles.

In example https://openlayers.org/en/latest/examples/epsg-4326.html

After changing the units to "metric", the Scale Line displays 100,000 times the correct value.

**Comment by raiyni** [comment]
Issue appears fixed in `5.0.0-beta.7`

**Comment by pedros007** [comment]
Indeed, this was found/fixed in #7694 for metric values.
