### ISSUE TITLE
WMTS render quality degradated in some cases since OL version 4

### ISSUE THREAD

**Issue by cvenzin** [openlayers/openlayers#7887]
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

The resampling of images does not work that well anymore on newer ol versions as you can see in the example (change from version 3.10.1 to any 4.x). The WMTS quality appears very bad if you are far away from the defined ScaleDenominators:
https://codepen.io/cvenzin/pen/wyEJZQ

**Comment by Abdullah0991** [comment]
I have the same issue using v4.6.5, @cvenzin have you found a solution?
