### ISSUE TITLE
tap on android mobile not finding features due to wrong pixel being returned

### ISSUE THREAD

**Issue by huntw999** [openlayers/openlayers#7895]
I had problems with openlayers on android mobile. It was not finding the features. I found the pixel being returned had the wrong pixel value. I put this into codepen to be run on the debug mode. when running this in debug mode i pring to console the map.on('click'........ value for evt being returned with the pixel value that is wrong. I determined it was wrong and then compared it to the pixel returned by the context menu library that helps with a custom contextmenu. this library (contexmenu) returns the proper pixel. I will look at how these two libraries come up with the wrong and right pixel values. I will report back my results. 

when testing this on chrome browser run in mobile mode which is obtained after selecting f12 to activate developer tools and clicking on mobile view (top left second icon) in developer tab

summary: the left click on android mobile returns the wrong pixel in openlayers map.on('click'......

this causes features methods that use the pixel value to fail

codepen:

https://codepen.io/williamhunt/project/editor/DyLLjB

**Comment by MatejDularRealis** [comment]
I have the same issue. Chrome for Android 7 returns wrong "event.pixel" for touch clicks on map if "user-scalable" metatag option is enabled and current page-scale is not 1 (a user zooms a page a bit on mobile phone). Wrong values seem to be already those in event.originalEvent attributes. Is seems as a Chrome's bug, not OL, but i'm not sure. It was all OK in Chrome for Android 6 as it is in other browsers I tested.

This is quite a problem, one that makes our public web page with OL map full of clickable features half unusable on touch devices.

**Comment by huntw999** [comment]
in the codepen link above - i use ol-contextmenu to show the correct value being returned - i am looking at both event handlers to see why ol-contextmenu works - for now - we are using one context menu with al l our needed clicks - i will stay on this to get a better solution

**Comment by huntw999** [comment]
i am assuming the ol-contextmenu is getting the click event the right way - i will look at it more closely and compare it to openlayers - i may modify ol-contextmenu to handle the left and right clicks that i need if it can be done without a lot of work

**Comment by fredj** [comment]
Same issue on mobile in the 'editor' view: https://codepen.io/williamhunt/project/editor/DyLLjB
But it works in the 'full' view:  https://codepen.io/williamhunt/project/full/DyLLjB/

**Comment by MatejDularRealis** [comment]
fredj: I guess your second example only works until your page's scale is 1, this is until you zoom the page (pinch-to-zoom) on a mobile. That's because the first "non-fullscreen" example is scaled for you automatically by browser and second (fullscreen) isn't.

**Comment by huntw999** [comment]
the codepen example will work on normal screens - it will not work on mobile screens - you can use chromes mobile screen viewer to test this - to be clear - I am getting the wrong pixel values when i use openlayers on mobile and then map.on('click'.... - i get the right values from contextmenu framework listed above - this leads me to believe they are pulling the pixel value differently - my next work will look to see where they are pulling it
