### ISSUE TITLE
Wrong ScaleLine calculation for non-degree based maps with Imperial-like units

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#7907]
When the map is non-degree based (such as a Zoomify scanned document) the pointResolution calculation is wrong in ScaleLine.js, when using Imperial-like units.

The problem is with this lines:
https://github.com/openlayers/openlayers/blob/85d4642450a1f9bebb0e0280fd20dcf78cfca5cb/src/ol/control/ScaleLine.js#L182-L184

The correct behaviour should be to always run
```
pointResolution *= projection.getMetersPerUnit();
```
when `projection.getUnits() != Units.DEGREES`.

That is, the correct fix is to remove 
```
&& units == ScaleLineUnits.METRIC
``` 

from the condition.

This is only happening on non-degree based maps when using Imperial-like units, which must be quite a niche.

If needed, I can make an example code, but it should be logical to see why this is the case. I can also submit a PR.

**Comment by raiyni** [comment]
Same issue as https://github.com/openlayers/openlayers/issues/7883

Have you tried the latest beta build? Was fixed for me in 0.7 when I tested it.

**Comment by hyperknot** [comment]
I'm on latest beta and km/metric units work. Only Imperial/US etc. doesn't.

**Comment by ahocevar** [comment]
@hyperknot Please create a pull request. Curious to see if your suggested change breaks any tests.
