### ISSUE TITLE
Display attributions when print (@media print)

### ISSUE THREAD

**Issue by jbelien** [openlayers/openlayers#7909]
Hello everyone,

When you print a page containing a map the `ol-attribution` is not displayed because of `display: none;` on `ol-control` for `@media print` !

I think it would be nice to display `ol-attribution` and keep other `ol-control` hidden of course.

--- 

I tweaked it with CSS like this (but I'm not really proud of this :P) :
```
@media print {
  .ol-attribution {
    display: block !important;
    height: 1.5em !important;
  }
}
```

**Comment by jbelien** [comment]
Any interest to submit a PR with this ?

**Comment by fredj** [comment]
And what about removing all the `@media print` from OpenLayers and let the applications taking care of it?

**Comment by jbelien** [comment]
Probably an even better idea 👍

**Comment by jbelien** [comment]
Thanks @fredj !

Maybe notify people that `@media print` was removed.
Because if they use to print, the controls will now be displayed on the print !

**Comment by fredj** [comment]
> Thanks @fredj !
> 
> Maybe notify people that `@media print` was removed.
> Because if they use to print, the controls will now be displayed on the print !

yes, sure. See #9572

**Comment by jbelien** [comment]
Sorry I missed it !

Thanks a lot ❤️
