### ISSUE TITLE
WebBrowser Control - Unable to draw the square on Maps by using OpenLayers

### ISSUE THREAD

**Issue by anilmuvva** [openlayers/openlayers#7920]
We have WebBrowser (System.Windows.Forms) controller in windows application. Webbrowser controller is displaying a site which is using OpenLayers 3 framework.

In webBrowser control- we are able to render the map, Which is good but we are unable to draw the square on the map and unable to move the maps by dragging. In IE11 browser, Drawing and Moving the maps by dragging is working. I thought initially that is a Compatibility issue in WebBrowser as it uses IE7 by default, so We have added registry entry and HTML Met tag to allow the Browser to use the Feature emulation as IE11 but still draw feature on map does not work. 

Any suggestions on this? I have searched on this topic (WebBrowser+OpenLayers3) in StackOverflow and other places also but No Luck.

**Comment by anilmuvva** [comment]
Any help on the above issue is appreciated

**Comment by fredj** [comment]
polyfills are probably needed for IE, try to add them as it's done in the examples:
https://github.com/openlayers/openlayers/blob/master/examples/templates/example.html#L14

**Comment by RalphLAtGitHub** [comment]
With an IE9 emulation via the meta element
`<meta charset="utf-8" http-equiv="X-UA-Compatible" content="IE=9">`
the WebBrowserControl and OpenLayers are working for me. A running example (NavTools) you can download here: https://lechterbeck.wixsite.com/nauticalsoftware
Select "Miscellaneous" and then "Link to OpenSeaMap".

Disadvantage: you are restricted to IE9 scope.

Hope it helps.

**Comment by MagicWang** [comment]
i meet same problem, even webbrowser load official examples cannot drag. and polyfills not work.

**Comment by RalphLAtGitHub** [comment]
Please post your code for further review.
