### ISSUE TITLE
OL5 beta.8 broke feature drawing "blue line"

### ISSUE THREAD

**Issue by hyperknot** [openlayers/openlayers#7922]
The "blue line" style for interactive feature drawing is broken in OL5 beta.8. It's working well in beta.7.
If needed I can try to make a reproducible case.

**Comment by ahocevar** [comment]
If possible, please create a CodeSandbox that shows the issue.

**Comment by hyperknot** [comment]
OK, I'm creating one. I think the official example should reproduce it.

**Comment by ahocevar** [comment]
Even better, then we don't need a CodeSandbox. Which official example?

**Comment by hyperknot** [comment]
Yes, I can confirm, "draw-shapes" does it. No interactive part.

**Comment by ahocevar** [comment]
Looks like it works in master, unless I'm missing what the issue is. Can you confirm?

**Comment by hyperknot** [comment]
OK, I created CodeSandbox for it:
https://codesandbox.io/s/p3y4256q7x

No rectangle visible while drawing for beta.8.

**Comment by ahocevar** [comment]
Thanks @hyperknot. I ran git bisect, and 6d1e8cb38b988e0cc7bf7abcd5014297ff8e6bcf is the first bad commit.
