### ISSUE TITLE
make challenges

### ISSUE THREAD

**Issue by tlepkowski** [openlayers/openlayers#7924]
I believe this is a bug because I've followed the steps in DEVELOPING.md and getting errors.  Nodejs is good, Java good, Make good. Pytho good. Latest Openlayers forked.   Working in Ubuntu with all the luxuries of sudo.  This might be more a documentation 'bug' than actual code bug.  I'm getting the following error after any attempt at a make command on the top level directory  of the project.
$ make check-deps
make: *** No rule to make target 'check-deps'.  Stop.

**Comment by raiyni** [comment]
make isn't used for the build anymore. Try npm test

**Comment by tlepkowski** [comment]
Thanks! 'npm test' looked promising, then blew up in defaultmapshder/Locations.js.. Module not found....
What other npm targets should be tried?

**Comment by ahocevar** [comment]
`npm run serve-examples` to run the official examples on a local dev server. Just look in `package.json`'s `scripts` section, there you see all targets.

**Comment by marcjansen** [comment]
docs need an update, though

**Comment by fredj** [comment]
DEVELOPING.md has been updated, closing
