### ISSUE TITLE
Nomenclature grid Openlayers

### ISSUE THREAD

**Issue by andrii555** [openlayers/openlayers#7926]
Hello! I work on a project where I use OpenLears v4 . There was an interesting task where it is necessary to implement a nomenclature grid. Something similar I found written on Leaflet. http://nakarte.tk/#m=5/46.25585/41.08887&l=O/Ng . I want to know how to implement this grid on Openlayers? Maybe someone has already done the same?

**Comment by raiyni** [comment]
You can probably hack it out of https://openlayers.org/en/latest/examples/graticule.html

**Comment by raiyni** [comment]
Or overriding https://github.com/openlayers/openlayers/blob/master/src/ol/source/TileDebug.js

**Comment by andrii555** [comment]
It's not so easy to do. Can you help me with this?

**Comment by raiyni** [comment]
https://codesandbox.io/s/mqn3wj5qkp

go to the custom.js and in the last function, change the text value

**Comment by andrii555** [comment]
https://jsfiddle.net/andrii555/setmtbsq/ my resoult. But I need to display the coordinates inside the cell
