### ISSUE TITLE
ol.interaction.DragAndDrop expects incorrect formatConstructors parameter

### ISSUE THREAD

**Issue by levinzz** [openlayers/openlayers#7931]
From the [DragAndDrop](https://openlayers.org/en/latest/apidoc/ol.interaction.DragAndDrop.html) API :

> formatConstructors : Array.<function(new:ol.format.Feature)>\| undefined

=> the `formatConstructors` parameter is expected to be an array of functions.

However in the [DragAndDrop example ](http://openlayers.org/en/latest/examples/drag-and-drop.html):

```typescript
var dragAndDropInteraction = new ol.interaction.DragAndDrop({
        formatConstructors: [
          ol.format.GPX,
          ol.format.GeoJSON,
          ol.format.IGC,
          ol.format.KML,
          ol.format.TopoJSON
        ]
      });
```

=> the `formatConstructors` parameter is an array of types.

In practice, if you comply to the API, and provide an array of functions, the event passed to 
```dragAndDropInteraction.on('addfeatures', (event) => {...}) ```
will contain `undefined` as features 

However, features are created properly from the same KML file when you define `formatConstructor` like in the examples.

If you're in pure Javascript, you won't notice the difference. If you're using TypeScript however, the type mismatch between expected type and provided type breaks project compilation.

**Comment by ahocevar** [comment]
The `formatConstructors` parameter is an array of constructors. In the Closure type system, the type `function(new:ol.format.Feature)` means a function that, when called with the `new` keyword, returns an instance of `ol.format.Feature`. Maybe that's incorrectly translated to TypeScript.

Note that the TypeScript types for OpenLayers are not maintained by the OpenLayers organisation, so maybe this issue should be created somewhere else.

**Comment by levinzz** [comment]
Ok I get it. I misunderstood the meaning of the type (it translates differently in TS). I opened [an issue on DefinitelyTyped repository](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/24115). 

Thank you
