### ISSUE TITLE
Displaying number (metric) on Scaleline (projectionCode: EPSG:4326)

### ISSUE THREAD

**Issue by albercik** [openlayers/openlayers#7934]
Hi all,

I have a problem with displaying proper number on a Scaleline.
Map works in **EPSG:4326** projection mode but I want to display scale in 'metric' mode.
My application has to support several different projection codes (e.g. EPSG:4326, EPSG:27700)
I have attached two screen shoots:

1. For EPSG:2700 everything works fine.
![correct scaleline epsg27700](https://user-images.githubusercontent.com/650724/36981728-cc4c85ae-2085-11e8-9f06-61ca84e039e6.png)

2. For EPSG:4326 I have wrong number (5'000'000 km) on the scaleline. 
![wrong scaleline - epsg4326](https://user-images.githubusercontent.com/650724/36981620-8cb8b110-2085-11e8-9f6c-eb2392317a00.png)

I have checked sources and when remove 3 lines (179 -  181) from https://github.com/openlayers/openlayers/blob/5cb983c760c00cd22de6fbcd5d971a6296d8dd0b/src/ol/control/ScaleLine.js#L179
then scale number is correct:

![correct scaleline - epsg4326](https://user-images.githubusercontent.com/650724/36982121-f9b6ca62-2086-11e8-8449-6e00de246a2b.png)

**Has anyone had this problem before?**
Or maybe I have a problem with my configuration.

Thanks.

**Comment by bartvde** [comment]
see #7907 #7908 ?

**Comment by albercik** [comment]
Probably this is the same issue.
I tried to install ol@5.0.0-beta.8 where this bug should be fixed but somehow I have other errors during compilation.

**Comment by raiyni** [comment]
Because ol@5.0.0-beta.8 is es6 code, so you have to transpile it. see https://github.com/openlayers/openlayers/issues/7879

**Comment by ahocevar** [comment]
Fixed with #7908.
