### ISSUE TITLE
Wrong ImageWMS position (only at maximum zoom)

### ISSUE THREAD

**Issue by luca76** [openlayers/openlayers#7936]
- [X] I am submitting a bug or feature request, not a usage question.
- [X] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [X] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using 
the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Using latest Openlayers 4.6.4.

Codepen (the file is a TS)
https://codepen.io/luca1976/pen/OQYYrN

Online version of the page demoing the problem:
https://webapps.comune.trento.it/gis/mobile/ol4/index.html

To reproduce problem:
1) go to https://webapps.comune.trento.it/gis/mobile/ol4/index.html
2) at bottom, click on "layers" button (the 2nd button from RIGHT)
3) select "Adunata alpini" (scroll the list), then click the button "APPLICA LE MODIFICHE" at top of the list
4) at maximum zoom, the added WMS layer is in wrong position; try to zoom IN 3 or 4 times and it will be in the right position (center of map)

To test only the WMS layer, use this URL:

http://webapps.comune.trento.it/ogc
and select the layer name "adunata_alpini"

**Comment by luca76** [comment]
**WRONG position (maximum zoom)**

![schermata del 2018-03-05 17-02-32](https://user-images.githubusercontent.com/5095918/36985274-11fb9282-2097-11e8-8634-10a8bdc70d6f.png)

**Comment by luca76** [comment]
**RIGHT position**

![schermata del 2018-03-05 17-02-52](https://user-images.githubusercontent.com/5095918/36985300-242cafcc-2097-11e8-8b15-bc86b6483632.png)

**Comment by ahocevar** [comment]
Please provide a runnable code pen that isolates the issue.

**Comment by luca76** [comment]
I've solved the problem by putting "extents" property of  ol.layer.Image:

```
 let alpini_wms = new ol.layer.Image({
      source: new ol.source.ImageWMS({
        url: "http://webapps.comune.trento.it/ogc",
        projection:'EPSG:25832',
        params: {
          LAYERS: 'adunata_alpini',
        }
      }),
      visible: false,
      extent: [663393, 5102084, 664814, 5104747]
    });
```
