### ISSUE TITLE
can't detect the end of loading of all layers

### ISSUE THREAD

**Issue by openappz** [openlayers/openlayers#7937]
I have a map with multiple layers but I can't detect the end of loading of all layers

**Comment by ahocevar** [comment]
You basically do the same as shown in https://openlayers.org/en/latest/examples/tile-load-events.html, but add the same tile event listener function to all sources.

**Comment by openappz** [comment]
problem that I have a dynamic complex map I can't detect numbre of layers or add listener to all source

**Comment by openappz** [comment]
tileloadend not work when have multiple dynamic layers how I can put event in all layers
