### ISSUE TITLE
Label issue with point feature on version 4.6.4

### ISSUE THREAD

**Issue by debaser75** [openlayers/openlayers#7941]
After upgrading my web app to 4.6.4, only some of my point features were being labeled. In researching the problem, I revisited the [Vector Labels example page](https://openlayers.org/en/latest/examples/vector-labels.html?mode=advanced). When you change the text setting to 'wrap' for the points, the points and the labels disappears.  Chrome reports the following error on it's console tab:

vector-labels.js:68 Uncaught TypeError: Cannot read property 'value' of undefined
    at getText (vector-labels.js:68)
    at createTextStyle (vector-labels.js:103)
    at pointStyleFunction (vector-labels.js:167)
    at hk.<anonymous> (ol.js:274)
    at hk.k.$c (ol.js:274)
    at kj.bh (ol.js:205)
    at K.k.pq (ol.js:135)
    at K.<anonymous> (ol.js:120)

I use the stringDivider function that is in this example (I copied and pasted it into my web app).  What's really weird: all of my labels fail to draw if I do NOT use stringDivider on my string.  I tried truncating my string using` text.substring(0,8)` but none of them appear.  

I don't display any points, I only need the labels.  Here's an example of the geoJson that's returned by for these points: http://rainpursuit.org/huc_points.php?bbox=-9499479.219739275,4198609.526676447,-9382759.877547814,4265721.237510831

**Comment by raiyni** [comment]
Have a codepen example?

**Comment by ahocevar** [comment]
The issue can be reproduced with the `vector-labels.html` example, as described by @debaser75. I can confirm that labels and symbols disappear when switching `Text:` to `Wrap` for points.

**Comment by ahocevar** [comment]
See #7944, which fixes the example.
