### ISSUE TITLE
Get rid of externs/olx.js and src/ol/typedefs.js

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#7947]
We have everything in place now for moving type definitions from `externs/olx.js` to other places. The new typedefs for copying/pasting into other places (class modules for classes, `src/ol/types.js` for things like FrameState) can be found in the temporary `externs/xol.js` file.

An example pull request for part of the work is #7946, which is based on #7609. Additional pull requests should remove types from `externs/olx.js` as they are moved to other places.

The desired result is outlined in #7838, which also involves getting rid of `src/ol/typedefs.js`, whose types are redistributed to the place where they are used if there is only one and its internal only, or to `src/ol/types.js`.

This issue keeps track of progress. Here are the namespaces to tick away:

- [x] #7953 `ol`
- [x] #7965 `ol/control`
- [x] #7953 `ol/events`
- [x] #7983 `ol/extent`
- [x] #7968 `ol/format`
- [x] #7971 `ol/geom`
- [x] #7989 `ol/interaction`
- [x] #8016 #8025 `ol/layer`
- [x] `ol/pointer`
- [x] #7971 `ol/proj`
- [x] `ol/render`
- [x] `ol/renderer`
- [x] #8084 `ol/reproj`
- [x] #8032 #8041 `ol/source`
- [x] `ol/structs`
- [x] #8076 `ol/style`
- [x] #8075 `ol/tilegrid`
- [x] `ol/vec`
- [x] `ol/webgl`

**Comment by ahocevar** [comment]
I'm taking on `ol`.

**Comment by ahocevar** [comment]
I'm also taking on `ol/events`.

**Comment by tschaub** [comment]
I'll do `ol/control`.

**Comment by tschaub** [comment]
I'll take `ol/format` next.

**Comment by ahocevar** [comment]
Working on `ol/extent` now.

**Comment by ahocevar** [comment]
Now taking on `ol/interaction`.

**Comment by romanzoller** [comment]
I will have a look at `ol/layer`.

Thanks @ahocevar for the intro to the topic and greetings from the [OSGeo Code Sprint](https://wiki.osgeo.org/wiki/OSGeo_Code_Sprint_2018)

![basecamp](https://user-images.githubusercontent.com/23193956/37781838-d6473f1c-2df1-11e8-8164-1886bdae53f1.jpeg)

**Comment by romanzoller** [comment]
I will have a look at `ol/source` tomorrow, which seems to be the biggest chunk left => it should keep me busy on the train ride back from the code sprint :-)

**Comment by fgravin** [comment]
hi guys, what's going on on this task ? @ahocevar ?
Seems the list of what is done is not up to date.

What's left ? we have some time to push things this week.

**Comment by ahocevar** [comment]
I was out for 2 weeks and need some time to catch up. If possible, could anyone who contributed to this effort update the ticket description so we have a better overview of what's left?

cc @fgravin

**Comment by romanzoller** [comment]
I'm already on that, I cannot update the description myself, but I will just post a list of changes here in a few minutes.

**Comment by pfirpfel** [comment]
I take ol/tilegrid

**Comment by pfirpfel** [comment]
Starting with ol/render now.

**Comment by pfirpfel** [comment]
Now taking `ol/structs`

**Comment by fgravin** [comment]
seems that nothing to do in `ol/renderer`

i take `ol/render`

**Comment by pfirpfel** [comment]
@fgravin Done that already here: #8081
Besides ol.LoadingStrategy and reviewing/merging my pull requests, there should not be anything left to do.

**Comment by fgravin** [comment]
@pfirpfel ok i'll let you on that then.

@ahocevar is there some other tasks we could help on toward ol 5.0 release ?

**Comment by ahocevar** [comment]
@fgravin The next task is to get rid of `oli.` interfaces. In addition to doing the same thing we did for `olx.*`, this requires to change all object properties listed in `oli.` interfaces to use bracket instead of dot notation (e.g. `this['coordinate'] = options.coordinate` instead of `this.coordinate = options.coordinate`).

**Comment by tschaub** [comment]
@fgravin (and others), see the [5.0 Milestone](https://github.com/openlayers/openlayers/milestone/36) for additional work toward the release.

We should ticket the work to redistribute `oli.js` separately.

There is also a fair bit of work to get rid of the legacy `ol.foo.Bar` notation (see #7970).  A search for `\bol\..*` reveals 1146 results in 329 files.  TypeScript is looking pretty good right now...
