### ISSUE TITLE
VectorTiles incorrect tile rendering 

### ISSUE THREAD

**Issue by rafpl** [openlayers/openlayers#7951]
VectorTile layer sometimes cuts parts of features. (ol-4.6.4)
This seems to happen during bitmap rendering, because it looks like a cut on a tile boundary, see picture:
![image](https://user-images.githubusercontent.com/16087962/37155884-c291f90c-22e4-11e8-9824-9912fb8bea76.png)
(The line should go to red circle. When I use Vector layer it renders correctly)

Any idea how to find workaround or further debug it?

**Comment by ahocevar** [comment]
This kind of rendering issue usually comes from vector tiles without sufficient buffer and overlap. You need to make sure that geometries in your tile set are not cut off at the tile boundary.

**Comment by rafpl** [comment]
Do you mean renderBuffer parameter form layer.VectorTile options? I increased to 10000, did not help.
I'll check how tippecanoe handled this line in tiles...

**Comment by ahocevar** [comment]
You cannot influence that from OpenLayers. It's how the tiles were created. tippecanoe usually works great with the default settings.

**Comment by rafpl** [comment]
I checked the content of my tiles and found the problem:
Tippecanoe converted some of input lines to MultiLineString and my style function did not support it.
OL works correctly. Thanks for help!
