### ISSUE TITLE
Memory leak when rendering a Vector Layer with renderMode: 'image'

### ISSUE THREAD

**Issue by erinc-petrode** [openlayers/openlayers#7954]
When rendering a VectorLayer, CanvasImageRenderer creates a CanvasVectorRenderer.
CanvasVectorRenderers add an event listener to ol/render/canvas/labelCache.
CanvasImageRenderers do not dispose of their CanvasVectorRenderer, leaving that listener, keeping the whole layer in memory indefinitely.
In addition, due to duplicate plugins being added to layerRendererPlugins, CanvasImageRenderer actually creates two VectorImageRenderers, leaving another hanging listener.

CodePen: https://codepen.io/erinc-petrode/pen/PRobvV

- [x] I am submitting a bug or feature request, not a usage question.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers.
- [x] If reporting a bug, I have created a [CodePen] that shows the issue.

**Comment by ahocevar** [comment]
Thanks for investigating this. Any chance you able to provide a pull request with a fix?

**Comment by erinc-petrode** [comment]
I have a fix for this, just need to run and write tests.
