### ISSUE TITLE
Plan to develop the 3D map engine？

### ISSUE THREAD

**Issue by daounet** [openlayers/openlayers#7955]
Plan to develop the 3D map engine？ On the map, the right key can be dragged。  like  this  http://lbs.gaode.com/api/javascript-api/example/map/map3d

**Comment by raiyni** [comment]
http://openlayers.org/ol-cesium/

**Comment by daounet** [comment]
Sorry       That's not the truth
You can change the visual angle, like a game, with a stereo.
[http://lbs.gaode.com/api/javascript-api/guide/create-map/3d-map#show-3d-map](url)

**Comment by raiyni** [comment]
That is literally the 3d library receiving support...

**Comment by fredj** [comment]
#4802
