### ISSUE TITLE
Remove defaultDataProjection as a format option

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#7967]
Formats should have a default data projection, but this does not need to be exposed as an option while reading and writing.  For example, GeoJSON and KML will have a default data projection of Geographic/WGS-84 set.  If a user wants to override this when reading or writing, they use the `dataProjection` option.  Having `defaultDataProjection` as an option only adds confusion.

**Comment by gberaudo** [comment]
The option can be useful, for example when configuring a vector source.
But the name is confusing and unconsistent with the name used for the projection of the features.

What about simply renaming the `defaultDataProjection` option passed to formats like `GeoJSON` to `dataProjection`? Then it would be consistent with the `featureProjection` that these formats accept.

Reading the `src/ol/format/GeoJSON.js` code I see:
```
  this.defaultDataProjection = getProjection(
    options.defaultDataProjection ?
      options.defaultDataProjection : 'EPSG:4326');


  if (options.featureProjection) {
    this.defaultFeatureProjection = getProjection(options.featureProjection);
  }
```

Which would become:
```
  this.defaultDataProjection = getProjection(options.dataProjection ? options.dataProjection : 'EPSG:4326');

  if (options.featureProjection) {
    this.defaultFeatureProjection = getProjection(options.featureProjection);
  }
```

**Comment by ahocevar** [comment]
I agree with @gberaudo here. Renaming the option to `dataProjection` sounds reasonable.

It's much more convenient API-wise to configure a source with a url and a format than with a custom loader where `readFeatures(data, {dataProjection: myProj})` would be called, if someone has to deal e.g. with a GeoJSON data set that has a non-standard projection.
