### ISSUE TITLE
Printing the map from the canvas is incomplete even after tiles loaded and postrender fired

### ISSUE THREAD

**Issue by AsharGhani** [openlayers/openlayers#7969]
I am trying to print the map that I create on the fly. However the image that I am getting from the map canvas sometimes looks half baked:

[https://i.stack.imgur.com/RSnbT.png](https://i.stack.imgur.com/RSnbT.png)

In the screen shot, the top portion is the openlayers map that eventually got rendered and the bottom portion is what I captured from the canvas after postrender.

I am starting from the official Export PDF example, but I am working with a map that just got created. I keep a track of the tiles loading and the tiles loaded through the tileloadstart and tileloadend map events. I also tried incorporating the postrender event as per this answer on stackoverflow. When all the tiles have been loaded I wait for the postrender event to capture the map image from the canvas.

The problem:

I think the problem has to do with the postrender event firing off two early and I don't know how much time to wait after the event before capturing the image from the canvas. I started with a delay of 100 milliseconds and then moved to 1 second and it seemed like it was working fine. But if I add more layers I had to take the delay to 3 seconds for it to start behaving correctly. So I don't know what the delay should be for maps with a lot of layers.

I also get the problem that sometimes the tileloadstart and tileloadend event keeps on firing even after postrender because some tiles had yet to be loaded and even though the tile load count had equalized.

I have created a codepen to demonstrate the issue: Print map using tile loading and postrender events
You would need to enter a Bing Maps Key at the top of the javascript file. A Bing Map Key can be generated from: https://www.bingmapsportal.com/. With the BingMap layer the problem is reproducible more consistently. In the code pen I am also capturing the problem when tileloadstart is called after the postrender and writing an error to the top of the page. Also please note that the behavior is inconsistent and you might have to reload several times for it to reproduce.

**Comment by jahow** [comment]
Hi,

The `postrender` event will be called several times and does not guarantee that all your tiles are loaded. You need to listen on `tileloadstart` and `tileloadend/tileloaderror` events on the source of the background layer, and increment/decrement a counter based on these. When the counter is zero, the full image will be available on the `postrender` event.

See example code:
```javascript
let source = map.getLayers().item(0).getSource()

let tilesCount = 0
source.on('tileloadstart', e => { tilesCount++ })
source.on(['tileloadend', 'tileloaderror'], e => { tilesCount-- })

let postRenderHandler = e => {
  if (tilesCount === 0) {
    map.un('postrender', postRenderHandler)
    options.loadedCallback()
  }
}

// bind postrender on another thread
setTimeout(function () {
  map.on('postrender', postRenderHandler)
})
```

**Comment by AsharGhani** [comment]
Hi Jahow,

What you describe is exactly what I am doing, Sorry I forgot to link to the codepen initially. Please see the codepen here:

[Print map using tile loading and postrender events: https://codepen.io/_ashar/pen/NyoZgo](https://codepen.io/_ashar/pen/NyoZgo)

**Comment by jahow** [comment]
Oh, ok, well I hadn't realized that the new opacity fading of image tiles would jeopardize this solution.
You should look into [this example](http://openlayers.org/en/latest/examples/tile-transitions.html) for a way to disable opacity transitions.

Hope that helps!
