### ISSUE TITLE
ol.style.text - gap between two line text

### ISSUE THREAD

**Issue by Bear4** [openlayers/openlayers#7976]
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Is there any oportunity to remove space between two line text in label feature?
In API I don't find any oportunity, maybe in library code?
In OpenLayers v2.13 there wasn't any blank space in OL v4.6.4 (and lower) it is. Styling text in label look better for me in previous version OpenLayers. 
Maybe is better option no space between two line and when I need it I just put it... ?
![space_text_line](https://user-images.githubusercontent.com/8928341/37326353-15b7c08e-2692-11e8-8e66-81be5d94f3a3.jpg)

```
text: new ol.style.Text({ 
            text: 3.5 +'\nbar' 
        })
```

**Comment by ahocevar** [comment]
Starting with v6, you'll be able to control the line height. You can set a line-height in the font of the style:
```js
import TextStyle from 'ol/style/Text';
new TextStyle({
  font: '12px/1 sans-serif'
});
```
The `/1` sets a line-height of 1, which is lower than the default of 1.2.

See #9307.
