### ISSUE TITLE
Move Tolerance Stops Scroll

### ISSUE THREAD

**Issue by JackFrostStudios** [openlayers/openlayers#7988]
Issue:
When you make use of the new moveTolerance setting in ol.Map (https://openlayers.org/en/latest/apidoc/ol.Map.html) then scrolling will freeze if you move your finger back over the original position you put your finger down.
The bigger the moveTolerance the easier this is to see - we have had to set ours to 5px as some android devices were really struggling with the click bug.
Related PR:
https://github.com/openlayers/openlayers/pull/6778
https://github.com/openlayers/openlayers/pull/6834

Fix:
It looks like it should be a relatively easy fix; we could just check whether dragging is true in the isMovingFunction: https://github.com/openlayers/openlayers/blob/e0e9c2677d5e108d4093006449c5f340f25ccb0e/src/ol/MapBrowserEventHandler.js#L303

I'm at work at the moment but I can have a look when I get home :)

**Comment by stefanocrosta** [comment]
Confirm the issue! @JackFrostStudios did you eventually get home :-D ? 
Any confirmation from OpenLayers team that that could be the way to go to solve it?

**Comment by ThomasTraspedini** [comment]
Hello, I'm experiencing this issue in OL 4.2, is it already fixed in last stable version?

Thank you!

**Comment by stefanocrosta** [comment]
Thanks @ahocevar ... 
any plan to fix this nevertheless? Do you consider it as a bug?
It becomes more apparent when the tolerance size is large, and it is quite disturbing to see the scrolling freeze when going over the initial 'click' position...

**Comment by stefanocrosta** [comment]
Sure! Not even worth a codePen:

1. Take any map example
2. Set tolerance to a higher value (very large, like 50, will help you identify the issue better, but the behaviour obviously happens at any value).
3. Start dragging to move the map. At first, the map won't move until you have dragged more than 50 pixels. That's expected
4. Keep dragging farther, then while still dragging, go back over the same are you started the drag; there, the map will STOP moving again, until you quit that the tolerance zone. That's definitely not expected!

For touchscreen usage it's usually better to set an higher tolerance; and that makes the problem very apparent.

As @JackFrostStudios suggests, a solution would be to always return true in that function (or in the one calling it) once moving has started.

Hope this is clear!
