### ISSUE TITLE
Missing release notes & archives for 4.6.5

### ISSUE THREAD

**Issue by joux3** [openlayers/openlayers#8002]
Release notes and "latest release" tag are missing on https://github.com/openlayers/openlayers/releases.

Zip archive links result in 404 on https://openlayers.org/download/.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).

**Comment by ahocevar** [comment]
Thanks for the reminder, I'm adding them right now.
