### ISSUE TITLE
Reprojecting image with custom placement / rotation

### ISSUE THREAD

**Issue by daanoz** [openlayers/openlayers#8022]
Hi,

I guess the following falls under feature request, since I could not really find an existing layer capability that could support this.

So we have an image, which represents a detailed place on earth. With respect to size, think about the floorplan of an airport. On that floorplan we have certain features, with GEO coordinates that we would like to position and draw on the floor plan, for example an airplane. So to do that, we want to rotate/scale/reproject our floorplan image in such a way that it fits actual position on the worldmap, possibly even overlaying the worldmap, a bit like [reprojection-image.html example](http://openlayers.org/en/latest/examples/reprojection-image.html).

For the image we have certain reference points, of which we also know the geo coordinate. E.g. pixel 10,25 on the image is geo coordinate 5.627004, 14.73573. Using the 3 reference-points we can deduct the rotation and the scale on the floor-plan. We are struggling quite a bit to get image to be reprojected correctly, getting it to actually reproject does not seem to be so trivial. Ignoring the projection, even rotating the image is already not possible in the [ol.source.ImageStatic](http://openlayers.org/en/latest/apidoc/ol.source.ImageStatic.html) class.

So the only way we could possibly see this already being supported, is generating some kind of custom projection, but also this does not seem very doable at the moment. So we are looking for a way to overlay the image in such a way that it can match the underlaying coordinate system. I do think this would be a usecase that would not only benefits us?

Here is a [codepen](https://codepen.io/Daanoz/pen/qojKXe), trying to demonstrate roughly what I mean, note though that I took the image from internet, just as an example, it could be that it's not 100% accurate.

Thanks,
Daan

(as an additional complexity, we have the image mentioned above also available as an XYZ tiled source, but to not make this more complex than it already is, I left it out of the story)

- [X] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [X] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [X] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [X] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by Viglino** [comment]
Hello,
Have a look at this ol extension to place an image on a map (center, rotate, scale): http://viglino.github.io/ol-ext/examples/layer/map.geoimage.html
If you want to calculate position/rotation on ground control points, this project may help: https://github.com/Viglino/Map-georeferencer
@+
