### ISSUE TITLE
OpenLayers 4.6.5 - Map Remove Tiles Transition

### ISSUE THREAD

**Issue by AdnanBoota** [openlayers/openlayers#8024]
We were using the openlayers v4.2.0, and the tiles transition was not performed by default, but in the latest v4.6.5, in which the tiles transition is activated by default, which we can't control.

The problem is when there are small layers (like 1 or 2), v4.6.5 works fine, but when there are many layers (like 10), the transition takes a lot of time to be applied on the all the activated layers on the map, which is very slow for our application.

Is it possible to disable the transition of layers in v4.6.5 like we had in v4.2.0

Thanks in advance!

**Comment by ahocevar** [comment]
To remove the tile transition, simply configure the source with `transition: 0`.
