### ISSUE TITLE
Making canvasFunction() async

### ISSUE THREAD

**Issue by nyurik** [openlayers/openlayers#8027]
The `ImageCanvas.canvasFunction` is synchronous, making it cumbersome to work with in async environment. I think it would be great to allow consumers to return `observable` and `thenable` objects in addition to pure canvas. The `ImageCanvas` implementation should function as follows:

```js
function setInternalCanvasAndRefresh(newCanvas) {
  // set cached image to the given canvas
}

const result = obj.canvasFunction(...);
if (typeof result.then === 'function') {
  // promise
  result.then(setInternalCanvasAndRefresh);
} else if (typeof result.subscribe === 'function') {
  // observable
  result.subscribe({
    next: setInternalCanvasAndRefresh
  });
} else {
  // assuming this is the canvas itself
  setInternalCanvasAndRefresh(result);
}
```

------
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
I agree that the `ol/source/ImageCanvas` API should support asynchronous canvas generators. To be more in line with the rest of the library (and agnostic about the way async is implemented), the API could look like this:
```js
const source = new ImageCanvas({
  canvasFunction: (extent, res, pixelRatio, size, proj) => {
    source.setLoader(callback => {
      myAsyncCanvasFunction(ext, res, pixelRatio, size, proj)
        .then(result => {
          source.setCanvas(result);
          callback()
        })
        .catch(e => callback(e));
    });
  }
});
```

**Comment by nyurik** [comment]
@ahocevar I'm not sure I understood your example.  My code was the implementation of the ImageCanvas side. The API would simply allow user's `canvasFunction` to return a promise or an observable instead of the canvas object:

Current usage:

```js
const source = new ImageCanvas({
  canvasFunction: (...) => { return myCanvas; }  // synchronous usage
}
```

New capabilities:

```js
const source = new ImageCanvas({
  // Asynchronous usage - returns a promise
  canvasFunction: (...) => {
    return new Promise((accept) => {
       accept(myCanvas)
    });
  }
}
```

```js
const source = new ImageCanvas({
  // Asynchronous usage - returns an observable object
  canvasFunction: (...) => { return {
    subscribe: (o) => {
       // call o.next(myCanvas) whenever new canvas is available 
      }
    }
  } }
}
```

Basically with promise it's a OL-initiated, async request for canvas, and with observable, OL subscribes to a stream of canvas updates initiated by the user.
