### ISSUE TITLE
KML styling problem

### ISSUE THREAD

**Issue by Albert8017** [openlayers/openlayers#8035]
I have added drag and drop to my map, based on https://openlayers.org/en/latest/examples/drag-and-drop.html. Styling works for f.i. gpx but fails for kml.

Whatever I try (vector source styling or layer styling), I can't get the kml features styled the way I want. Kml files with a style included are shown using that style but I cannot replace the style with my style. Kml with points but without a style are shown using a terrible old Google style push pin.

`var styleFunction = function (feature, resolution) {
  console.log("in styleFunction()");
  var featureStyleFunction = feature.getStyleFunction();
  if (featureStyleFunction) {
    return featureStyleFunction.call(feature, resolution);
  } else {
    return defaultStyle[feature.getGeometry().getType()];
  }
};

var dragAndDropInteraction = new ol.interaction.DragAndDrop({
  formatConstructors: [
    ol.format.GeoJSON,
    ol.format.TopoJSON,
    ol.format.EsriJSON,
    ol.format.IGC,
    ol.format.GPX,
    ol.format.KML
  ]
});

map.addInteraction(dragAndDropInteraction);

dragAndDropInteraction.on('addfeatures', function (event) {
  console.log("in dragAndDropInteraction");
  const ext = event.file.name.split('.').pop().toLowerCase();
  console.log("  ext: " + ext);
  let vectorSource;
  let layer;
  switch (ext) {
    case 'gpx':
      vectorSource = new ol.source.Vector({
        features: event.features,
        format: new ol.format.GPX(),
        // readExtensions: 
      });
      break;
    case 'kml':
      vectorSource = new ol.source.Vector({
        features: event.features,
        format: new ol.format.KML({
          extractStyles: false,
          // showPointNames: false,
          // extractAttributes: true,
          // writeStyles: false
        }),
      });
      break;
    default:
      break;
  }
  if (vectorSource) {
    map.addLayer(new ol.layer.Vector({
      source: vectorSource,
      style: styleFunction 
    }));
    map.getView().fit(vectorSource.getExtent());
  }`

An example at [jsfiddle](https://jsfiddle.net/Albert8017/2upevLgo/) and a simple test file [test.zip](https://github.com/openlayers/openlayers/files/1854809/test.zip).

Thanks.

**Comment by jairperrut** [comment]
I did this and worked:

```javascript

// other things...

var dragAndDropInteraction = new ol.interaction.DragAndDrop({
  formatConstructors: [
  function(){return new ol.format.KML({extractStyles:false})},
    ol.format.GeoJSON,
    ol.format.TopoJSON,
    ol.format.EsriJSON,
    ol.format.IGC,
    ol.format.GPX,
    ol.format.KML
  ]
});

// other things..

dragAndDropInteraction.on('addfeatures', function (event) {    
  let vectorSource = new ol.source.Vector({
	          features: event.features
  });  
  map.addLayer(new ol.layer.Vector({
    source: vectorSource,
    style: styleFunction 
  }));
  map.getView().fit(vectorSource.getExtent());
});
```

**Comment by robbitt** [comment]
@jairperrut has a good solution.  It saved me from combing through code aimlessly.  Its strange that only KML files had this styling problem.
