### ISSUE TITLE
FlexBox Height Sizing

### ISSUE THREAD

**Issue by sbowler** [openlayers/openlayers#8040]
First, thanks for all your guys great work. I really appreciate it. You've always been very responsive and helpful.

So for years I've had issues with the canvas height growing when resizing the browser window. Normally to work around this I've set some static height on an element for the map to live in, but I'd really like to get away from that and use flexbox containers so the navigation bar can be as tall as needed and have everything just fit better as needed from browser to browser.

I've tried to put together a fiddle to help illustrate the issue, https://jsfiddle.net/9f61u33e/8/ . It may be a bit complicated for what may be needed minimally to reproduce, but is closer to the real world application layout and styling.

**To reproduce,** if you shrink down the browser window width and then make the window wider you should see a scroll bar appear and the canvas will grow taller and taller the wider you make the window.  

There was a similar issue you guys fixed years ago, but I couldn't find anything very recent or open that appeared to be related. Let me know if you have any ideas or changes you would like me to try and test. A gist or whatever would work. Thanks a bunch.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by fredj** [comment]
Linked issue is closed https://github.com/WefNET/womaps2/issues/1

**Comment by sbowler** [comment]
I'm not sure the stated fix is relevant to this. However, I do believe I was mostly able to resolve the issue I had by adding a minimum height of 0 if I recall correctly, which leads me to believe the issue may be more to do with flexbox bugs in browsers than OL fault. I don't have time to look at this right now, but I'll be adding a map to another app soon and will be dealing with this again.

**Comment by daudihusbands** [comment]
I've found this solution here: https://android.wekeepcoding.com/article/14549081/Openlayers+3+resizing+in+flexbox+column+layout%3F
```css
.container {
  height: 100%; /* Fill the window */
  display: flex; /* Magic begins */
  flex-direction: column;
}
#map {
  min-height: 0; /* Let the content overflow */
  flex: 1; /* Fill the available space */
}
```

**Comment by seidlmic** [comment]
I have the same problem with 5.3.0. I have created simple demo https://www.pastiebin.com/5d4afcadf0f76 (just copy to new html file and open) If you remove magic line with min-height: 0 the problem will appear. I can not say if it is bug or expected behaviour? But the trick mentioned above helps.

**Comment by ojathelonius** [comment]
> I've found this solution here: https://android.wekeepcoding.com/article/14549081/Openlayers+3+resizing+in+flexbox+column+layout%3F
> 
> ```css
> .container {
>   height: 100%; /* Fill the window */
>   display: flex; /* Magic begins */
>   flex-direction: column;
> }
> #map {
>   min-height: 0; /* Let the content overflow */
>   flex: 1; /* Fill the available space */
> }
> ```

I had to use `min-height: 0` on the container as well for this to work.
