### ISSUE TITLE
Force update on pointer style image without mousemove

### ISSUE THREAD

**Issue by rutgr** [openlayers/openlayers#8043]
have a pointer as part of an `ol.interaction.draw` and the possibility to update the style of the image dynamically. When the style parameters are updated the change is represented as soon as the mouse is moved.

But I want to see the change instantly. I've tried the `refresh()`, `changed()` and `renderSync()` option (where applicable) on the map, the interaction and layer and source the interaction is bound to without success (probably due to the fact the pointer is drawn in a private layer). Still the change is only effective as soon the mouse is moved. Also tried to dispatch an mousemove (on document, map & layer level) event without success.

What would be the way to have the change of style being applied immediately?

**Comment by pcezar-i9** [comment]
I have a similar problem. The user can change on preset styling of some features. This started when updated from 4.5.0 to 4.6.5
