### ISSUE TITLE
Using ES2015 ol package from Angular cli

### ISSUE THREAD

**Issue by BrkCoder** [openlayers/openlayers#8046]
#Trying use the ol package from Angular cli Project writing in TypeScript:

import Map from 'ol/map';
I get Could not find a declaration file for module 'ol/map'. '/foo/node_modules/ol/map.js' implicitly has an 'any' type.

Has anybody managed to make it work with TypeScript?
Please Provide a way to work with it in TypeScript, There are many people who use angular cli as their main tool and we need this support.
I would be happy to build a typings library for this package but I don't know from where to start,
Please provide some guidlines.

Best Regards,
Barak

**Comment by jumpinjackie** [comment]
You can try this typings for OL I've made:

https://github.com/jumpinjackie/mapguide-react-layout/blob/master/src/internal_typings/openlayers.d.ts

**Comment by idevtech** [comment]
I added  "@types/ol": "4.6.1" to my React project package.json file and npm retrieved all the type definitions for OpenLayers. The only thing I found cumbersome is the definitions are very granular so you have to import all kinds of specific types for OL. Maybe I'm missing something but have not been able to find a way to import the entire OL definition like other libraries. Appears there is an index.d.ts file necessary in the /ol folder.
