### ISSUE TITLE
ol.Overlay: let the user manage z-index

### ISSUE THREAD

**Issue by levinzz** [openlayers/openlayers#8056]
I'm creating popups on a map using ol.Overlay. When I click on a popup, I want it to get to the front (z-index above other popups z-index). I manage the z-indexes myself within the application and update z-index values when needed.

However, I found currently no way to update an ol.Overlay z-index using its API. 

My current workaround is through complex DOM manipulation but I feel this is really a hack.

**Comment by fredj** [comment]
This kind of feature should be handled in application code, not in OpenLayers
