### ISSUE TITLE
Modify.prototype.removeVertex not getting called when modifying LineString

### ISSUE THREAD

**Issue by and01** [openlayers/openlayers#8065]
When migrating from OL3 to OL4 the following feature has been killed:

While modifying a LineString there was the ability to remove vertices when clicking on them.

You can test the expected behavior here:
https://tsauerwein.github.io/ol3/mapbox-gl-js/examples/modify-test.html
http://openlayers.org/en/latest/examples/modify-test.html?q=modify

Has this feature been removed on purpose?

**Comment by fredj** [comment]
Yes, it's a new behavior in version 4.x.
See https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#olinteractionmodify-deletes-with-alt-key-only

**Comment by and01** [comment]
awesome, thanks!

**Comment by fredj** [comment]
@and01 I had the same issue last week :-)
