### ISSUE TITLE
Scale line issue in print preview

### ISSUE THREAD

**Issue by richnic** [openlayers/openlayers#8066]
Please have a look at the openlayers example [Scale Line](https://openlayers.org/en/latest/examples/scale-line.html).
On the screenshots below you can see that the length of the scale line in relation to the continents is different in browser window and print preview.

In the print preview the map is shrinked to fit onto the paper. That's appreciated.
But the scale line is not shrinked in the same way and remains wide. Therefore in the print preview the bar has not the right length in relation to the content shown in the map.
Is there something wrong or missing in the code of the scale-line-example?

(Tested in IE11, Firefox, Chrome and Opera)

![image](https://user-images.githubusercontent.com/38283296/38613063-f11439ac-3d88-11e8-9fa3-47e27b4e0f8d.png)

![image](https://user-images.githubusercontent.com/38283296/38613077-064ba738-3d89-11e8-87f7-6e549ee3c81b.png)

- [X] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [X] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [X] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by fredj** [comment]
To avoid the map deformation on print, you will need to update the size before printing.
See https://github.com/openlayers/openlayers/pull/6908#issuecomment-311806140
