### ISSUE TITLE
Opacity transition with preloaded tile causes some unexpected behavior.

### ISSUE THREAD

**Issue by yjwoo14** [openlayers/openlayers#8067]
To reproduce the behavior, go to https://openlayers.org/en/latest/examples/wmts-dimensions.html and do the following.

1. Set the sea-level slider to 100M
2. Zoom one level in.
3. Changing the slider causes flickering. (See attachment)

![flickering](https://user-images.githubusercontent.com/2172213/38613449-4390549e-3d8a-11e8-8188-92b6bf0a6a33.gif)

As far as I understood, this is because opacity transition can be made from preloaded tiles in a higher zoom level (#7267 may be relevant) and getting preloaded tiles does not check the dimension (which contains this slider value).

In my experiments, I could get around this issue by using only preloaded tiles whose key matches to the current key of tile. 

* Add condition `this.getKey() == tile.key` on line 143
https://github.com/openlayers/openlayers/blob/568b3d3559b4388c732dbe7b0e35d53f5b9d2f49/src/ol/source/Tile.js#L140-L143

Any opinion  would be appreciated.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
It would be interesting to see how the change you suggest affects fade-in user experience for maps with just one dimension. If that does not case a decrease in quality, we'd accept a pull request.

**Comment by yjwoo14** [comment]
I went through sources to find out the ones setting 'key' and only `UrlTile` (including its child classes) calls `setKey()`. `TileImage` and `VectorTileSource` inherits directly from `UrlTile`, and  `TileImage` source sets `key`  when creating tiles. However, `VectorTileSource` does not set `key` at all, so my fix prevents from using preloaded vector tiles in the opacity transitions, so I would also suggest the following:

* Add `this.key = this.getKey();` on line 173
https://github.com/openlayers/openlayers/blob/004f91a020bd8f3d69d5c758e8a7537937059b56/src/ol/source/VectorTile.js#L164-L174

**Comment by dimin** [comment]
I've had the same problem with setting different tile urls setUrl() on a source. The animation would always jump to the very first source url that was set. The solution was to set distinguishing optional keys for each source which would select proper tiles form cache for animation.

There were a few minor fixes needed in the repos for proper passing of optional keys through tile sources: #8641
