### ISSUE TITLE
Add TypeScript index.d.ts definition file to /ol so entire library can be imported

### ISSUE THREAD

**Issue by idevtech** [openlayers/openlayers#8068]
After importing "@types/ol": "4.6.1" into my React project using npm there appears to be just individual type definition files for most of the classes. This leads to an excessive number of "import" statements for OpenLayers functionality.

For example, in /ol/geom there are individual TypeScript definition files for circle, point, polygon, etc. This results in each of these geom classes needing to be imported.

Maybe I'm missing something but have not been able to find a way to import the entire OL definition like other libraries. Appears there would be an index.d.ts file necessary in the /ol folder. At a minimum a definition file for the high level classes (all the /ol child folders) would be helpful.

**Comment by tschaub** [comment]
We don't currently maintain any TypeScript definitions in the repository, but it is possible that we will use TypeScript in the future.  For now, the library is authored and will be published as ES modules.  If you are using the 4.6.1 release, you might be getting TypeScript definitions from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/openlayers, which is maintained separately (and I am not sure if any maintainers of this repo are involved).

In the 5.0 release, you will be able to import multiple constructors from a few common modules.  As @fredj points out, see #8110 for details.  This is not the same as importing the whole library with a single import statement.  And at this point, we don't have plans to export everything in the library from a single module.  The library can be thought of as a collection of packages, except you only have a single dependency.

Separately, I think it would make sense to help out with or more actively get involved in maintaining the TypeScript definitions for the library.  I'll close this issue, but will poke around to figure out who is involved making these definitions available and see if we can make it easier.
