### ISSUE TITLE
API docs of ol.Geolocation: URL scrambled in trackingOptions

### ISSUE THREAD

**Issue by marcjansen** [openlayers/openlayers#8072]
API docs of ol.Geolocation: URL scrambled in trackingOptions

The URL `https://www.w3.org/TR/geolocation-API/#position_options_interface` which we reference in `ol.Geolocation.js` like this:

```js
/**
 * @typedef {Object} Options
 * @property {boolean} [tracking=false] Start Tracking right after
 * instantiation.
 * @property {GeolocationPositionOptions} [trackingOptions] Tracking options.
 * See {@link http://www.w3.org/TR/geolocation-API/#position_options_interface}.
 * @property {module:ol/proj~ProjectionLike} [projection] The projection the position
 * is reported in.
 */
```

… somehow gets turned into this when actually rendering the generated API docs:

```
Tracking options. See href="http://www.w3.org/TR/geolocation-API/#position\_options\_interface">www.w3.org/TR/geolocation-API/#position\_options\_interface}.
```

![foo](https://user-images.githubusercontent.com/227934/38719761-ecbc6ebc-3ef3-11e8-8c9d-e9f7872801c7.png)

**Comment by fredj** [comment]
fixed, see https://openlayers.org/en/master/apidoc/module-ol_Geolocation.html
