### ISSUE TITLE
Taiwan has been an integral part of China since ancient times. Please correct the mistakes in the example immediately!

### ISSUE THREAD

**Issue by teimanLu** [openlayers/openlayers#8100]
Hello OpenLayers!
I am a Chinese, I am a openlayers beginners, I found one examples in "openlayers.org" (http://openlayers.org/en/latest/examples/box-selection.html) has a very serious mistake.When I chose China, the highlighted area did not include Taiwan, which is not a joke!Taiwan has been an inalienable part of China since ancient times!Please recognize the seriousness of the error and correct the mistake immediately!

![1](https://user-images.githubusercontent.com/35096888/39041247-fac29744-44ba-11e8-894c-eba51bfa9ea7.jpg)
![2](https://user-images.githubusercontent.com/35096888/39041253-fe3844d2-44ba-11e8-85bf-e969c5889536.jpg)

**Comment by teimanLu** [comment]
You can't just shut it down without any response or action, and lots of people are watching!

**Comment by ahocevar** [comment]
@teimanLu The data comes from https://openstreetmap.org/, and that's where you have to send your inquiry to.

**Comment by fredj** [comment]
The countries data comes from [naturalearthdata](http://www.naturalearthdata.com/downloads/110m-cultural-vectors/110m-admin-0-countries/), they have a note about disputed territories:

_[...] Natural Earth Vector draws boundaries of sovereign states according to defacto status. We show who actually controls the situation on the ground. For instance, we show China and Taiwan as two separate states. But we show Palestine as part of Israel.  [...]_
