### ISSUE TITLE
SVG image as layer is blurry in OpenLayers 4

### ISSUE THREAD

**Issue by Kardzhilov** [openlayers/openlayers#8105]
As shown here: https://jsfiddle.net/status420/mhfn9anm/2/
When you use a SVG file in a image layer it does not scale properly always being at the minimum scale making it useless.

This has apparently been an issue for [over a year](https://github.com/openlayers/openlayers/issues/4633), but no solution has appeared. Since that last issue is ignored because it is wrongly closed i am making a new one here.

**Comment by itsonit** [comment]
snap to fixed integer values as described here: https://github.com/openlayers/openlayers/issues/4633#issuecomment-289269380 with this example here: https://openlayers.org/en/latest/examples/mousewheel-zoom.html does't fix it...

**Comment by IonIo** [comment]
Any progress here?

**Comment by fredj** [comment]
If you use a `ol.source.ImageStatic` source, the image will be blurry when zoomed. Even if the image is a svg file.

**Comment by karvex** [comment]
Also waiting for a solution for this matter. Seems like OpenLayers 3, OpenLayers 4 and OpenLayer 5 has the same issue. Haven't tried OpenLayers 2 though.

**Comment by svpasumarthy** [comment]
any fix for this issue yet? or anyone with alternative approach?

The solution that was suggested for OL5 in stackoverflow is not useful when you have a large svg since it treats the svg image as an icon and if the center of the icon is not in the viewport of the map it will hide the icon. We need a better layer or handler for this to be useful.

**Comment by svpasumarthy** [comment]
Is there a beta for ol6 or date for the official release of ol6? Very excited to try. Everyone is eagerly waiting for the svg layer feature.

**Comment by ahocevar** [comment]
The release is scheduled for this month. In the meantime, you can try master, which contains the new renderer code already.

**Comment by svpasumarthy** [comment]
@ahocevar Do you already build the ol.js file for master or do we have to download the project and do it ourselves? I am not very familiar with your process. Any help will be appreciated.

**Comment by ahocevar** [comment]
I just published `ol@6.0.0-beta.1`.

**Comment by henkkelder** [comment]
I've been searching for documentation or an example of this new rendering. I have been unable to. Is there an example or documentation?

**Comment by ahocevar** [comment]
@henkkelder You'll want to configure `ol/Layer`'s `render` property. See https://openlayers.org/en/master/apidoc/module-ol_layer_Layer-Layer.html.
