### ISSUE TITLE
ol.layer.Vector Icon problem in renderMode='image'

### ISSUE THREAD

**Issue by christophew** [openlayers/openlayers#8119]
Hi,

I'm upgrading to ol 4.6.5.
When changing from image layers to ol.layer.Vector + 'image' I ran into a problem.

Icon styles are not drawn the first time they are added to the layer (by addFeatures).
It requires a forced redraw before they are drawn.

Setup:
- ol.source.Vector
- ol.layer.Vector (renderMode: 'image')
- ol.style.Icon with 'src' property
- feature is added by addFeature

I reproduced the problem starting from an official example: https://openlayers.org/en/latest/examples/icon.html?q=Icon
=> I changed how the feature is added to the source.Vector

The problem:
First time you click, the feature is added but not drawn.
Second time you click a redraw is triggered and the feature is actually drawn.

Codepen: https://codepen.io/christophew/pen/ZoWeQX

**Comment by christophew** [comment]
Forced redraw: for instance with a map.render()
The map is also redrawn when clicked, resized, panned, ..

I'm guessing that the problem occurs when the Icon is still loading while the ol.layer.Vector is being drawn in 'image' mode. The layer should redraw when the Icons are actually loaded, but this doesn't happen.
As I don't known when the Icons are actually loaded, my only workaround is triggering a map.render() after some arbitrary wait time. Ex. setTimeout(() => map.render(), 1000);

**Comment by mmomtchev** [comment]
map.render() doesn't fix the issue for me, but a source.refresh() does
Me too I guess it is some kind of timing issue with the renderer drawing the map before the image is loaded. I get different results across different browsers so maybe it is a race condition.

**Comment by ChouGary** [comment]
test with loaded image before add feature, it's ok.
var img1 = new Image();
var iconStyle = new ol.style.Style({
  });
img1.onload = function(evt) {
	console.log('loadend');	  
   iconStyle.setImage(new ol.style.Icon({ 
      imgSize:[img1.width,img1.height],
      img: img1
    })
  )
}
img1.src = 'https://openlayers.org/en/v4.6.5/examples/data/icon.png';

	  map.once('click', function(evt) {
	      var iconFeature = new ol.Feature({
        geometry: new ol.geom.Point([0, 0]),
        name: 'Null Island',
        population: 4000,
        rainfall: 500
      });

      iconFeature.setStyle(iconStyle);
		vectorSource.addFeature(iconFeature);
	});
	
https://codepen.io/anon/pen/bMBGda?editors=0010
