### ISSUE TITLE
TypeScript (Help Wanted)

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#8120]
I'd like to see if we can publish TypeScript definitions for the 5.0 release.  My understanding is that these can be published as [`@types/ol`](https://www.npmjs.com/package/@types/ol) or in the `ol` package itself.  I assume we'll need more than a single `index.d.ts` since we do not make everything exportable from a single module.  I'm hoping we can automatically generate the TypeScript definitions from existing JSDoc annotations in the code.  Perhaps this will be a migration path away from JSDoc annotations to authoring in TypeScript, but initially I think our goal should be to publish TypeScript definitions that are in sync with the code.

I'll be doing some more reading, but if anybody has experience and knowledge that they can spread, please let us know.

**Comment by marcjansen** [comment]
Ping @kaivolland @atd-schubert

**Comment by tschaub** [comment]
@yairtawil - given your work on DefinitelyTyped/DefinitelyTyped#22894, I'm curious what you would suggest in terms of automating TypeScript definition files.

**Comment by atd-schubert** [comment]
As long as you can also insert your TypeScript type definitions into your own module you should not apply them to DefinitelyTyped (DT). In addition there is [already a definition on DT](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/ol).

My recommendation is to insert a new definition based on the existing one with the help of the current definition author (@yairtawil). After that you can set the current type definition on DT as deprecated and maintain it in your module directly.

I can also help you a litte bit, if you wish.

**Comment by marcjansen** [comment]
Please help, @atd-schubert. Your feedback is much appreciated.

**Comment by chrismayer** [comment]
Wouldn't it make sense to have more members defined in the TypeScript types? In the Definition Files at https://github.com/DefinitelyTyped/DefinitelyTyped/ all classes are modelled like this

```
import * as ol from 'openlayers';

export default ol.layer.Vector;
``` 

Does it make sense to have the members like ``extent`` and ``visible`` defined there as well?

I just started with this TypeScript things, so sorry if I am wrong.

**Comment by chrismayer** [comment]
> Maybe another topic for our FOSSGIS Hacking-Event in Essen 

Good idea ...

**Comment by beginor** [comment]
maybe it is time to switch to typescript 😄

**Comment by jumpinjackie** [comment]
I've already made such a JSDoc plugin to auto-generate `d.ts` files from JSDoc documentation.

https://github.com/jumpinjackie/jsdoc-typescript-plugin

An example of `openlayers.d.ts` generated by this plugin:

https://github.com/jumpinjackie/jsdoc-typescript-plugin/blob/master/typings/openlayers.baseline.d.ts

I've been using it to generate typings for OpenLayers in my own projects for many releases now.

Despite the name suggesting it's a general purpose plugin, sadly it is not. It's just handles the OpenLayers case, which it handles very well.

**Comment by tschaub** [comment]
Our current plan is this:
 * migrate from type annotations for the Closure Compiler to TypeScript annotations in comments - this is similar to what webpack is doing (see webpack/webpack#6862 and subsequent work)
 * consider authoring in TypeScript

We're not going to block the 5.0 release on this, so I'll remove the milestone.

**Comment by fgravin** [comment]
Hi, i just want to push back to a tool used by google to move from closure to typescript:
https://github.com/angular/clutz

- goog.provide/require to import/export
- functions to classes
- closure JSDOC type annotation to typescript types

I think this tool could have been more used for all the tasked we've done for es6 module migration, maybe it can still be usefull and maybe people that were using openlayers and closure in their project could find this usefull.

**Comment by gberaudo** [comment]
For the converter, see https://github.com/angular/clutz#gents---closure-to-typescript-converter.

**Comment by ahocevar** [comment]
The codebase is now annotated with JSDoc types that TypeScript understands. This work is complete, but there's one TypeScript issue that keeps us from running tsc type checks as part of our CI: Microsoft/TypeScript#27215.

**Comment by joshferrell** [comment]
Is there a workaround for us to use in the meantime for our types, other than rolling back to v4? That bug seems to be getting kicked along and doesn't show any signs of getting resolved soon.

**Comment by idevtech** [comment]
What's the status of getting TypeScript definitions for v5.x  now that TS v3.4.3 is released? Not being able to use TS for OpenLayers v5.x is holding up deployment of a project.

**Comment by hanreev** [comment]
i have manually generated [typescript declaration fo openlayers v5.3.2](https://github.com/hanreev/openlayers-docset/tree/master/typings) using JSDoc.
This declaration includes all documented API.

**Comment by ahocevar** [comment]
A regression in TypeScript 3.6 is currently affecting us: microsoft/TypeScript#33106.

**Comment by KaiVolland** [comment]
Hey @hanreev,

I just forked your repository and it looks really great. :tada: 

As we'd like to include the creation of `.d.ts` files within the CI-Pipeline we'd really appreciate if you could come up with some ideas or even a PR to include your templates and plugins within openlayers directly.

If you don't have the time and you don't mind I'm gonna try to do so.

**Comment by hanreev** [comment]
@KaiVolland with pleasure. it will be very helpful.

**Comment by KaiVolland** [comment]
As @bampakoa state here https://github.com/openlayers/openlayers/issues/8448#issuecomment-539017463 the next typescript version will probably allow the generation of declaration files from js doc directly:

https://devblogs.microsoft.com/typescript/announcing-typescript-3-7-beta/
https://github.com/microsoft/TypeScript/pull/32372

So we can easily create the `.d.ts` files with just adding `declaration: true` to the tsconfig.

![https://media.giphy.com/media/rmi45iyhIPuRG/giphy.gif](https://media.giphy.com/media/rmi45iyhIPuRG/giphy.gif)

**Comment by tschaub** [comment]
I opened https://github.com/microsoft/vscode/issues/82054 to describe the type of behavior I think it would be good to avoid.  Having `*.d.ts` files published may make things nicer for TypeScript developers, but I think it would be unfortunate to lose the "Go to Definition" functionality and other features that let you navigate JavaScript sources in VSCode.

**Comment by fjorgemota** [comment]
It's possible to add a tag (not sure which is more appropriate) so the stale bot doesn't mark this issue as stale anymore?
