### ISSUE TITLE
Consider keeping ol.source.ImageVector

### ISSUE THREAD

**Issue by ThomasG77** [openlayers/openlayers#8142]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

I've made a case to manage vector like a raster layer using `ol.source.imageVector` and styling it.
I combined this output to process raster with it using `ol.source.Raster`. From my understanding, as OpenLayers will remove the `ol.source.ImageVector` due to deprecation, it will not be possible to process it within `ol.source.Raster`.
You can see the demo at http://bl.ocks.org/ThomasG77/5bf03d9c2acaa4562fecb94aadfb04e4 to demonstrate my current way of doing. In this demo, it's a simple case but it could be more complex operations between vector and raster inputs.

**Comment by ahocevar** [comment]
The use case you are pointing out is valid. However, `ol.source.ImageVector` has been removed already, and with image rendering built into the vector renderer now, there are probably simpler ways to achieve what you are looking for. All it takes would be to add support for vector sources to the [`createRenderer`](https://github.com/openlayers/openlayers/blob/ce84c3bf574d29bd18000539aa54a51dd305ed3d/src/ol/source/Raster.js#L485-L493) function. Then a vector layer renderer configured for `RenderMode.IMAGE` could be used to create the images for the raster source.

We'd accept a pull request for this approach.

**Comment by ThomasG77** [comment]
> All it takes would be to add support for vector sources to the `createRenderer` function.

Not sure I understand: a vector source does not contains style so if I add support for vector within `createRenderer`, it would generate a raster "styleless" I can't use.

> Then a vector layer renderer configured for RenderMode.IMAGE could be used to create the images for the raster source.

If you consider that you can change the signature in `ol.source.Raster` to add a `ol.layer.Vector` with `RenderMode.IMAGE` as an input instead of an array of `ol.source`.

At the moment, I miss the point, sorry. I'm wrong, I misunderstood?

**Comment by shaunakv1** [comment]
+1 

@ahocevar  I second this request.  I think layer clipping becomes very convenient with ` ol.source.ImageVector`. Here's a[ link to my example
](https://shaunakv1.github.io/OpenLayers3_Raster_Manipulation_Examples/landcover_layer_clipping.html) that uses `ol.source.ImageVector`  to clip the basemap and landcover layer to display only South Carolina state. 

Code for the above example is in its [GitHub Repo](https://github.com/shaunakv1/OpenLayers3_Raster_Manipulation_Examples/blob/master/js/landcover_layer_clipping.js)

**Comment by ahocevar** [comment]
Good point about the missing style @ThomasG77. In this case it might indeed make sense to create a new ImageVector source, which would be only a few lines of code because of the new image rendering support in the Vector renderer. Pull request welcome.

**Comment by ahocevar** [comment]
Also see #8216.

**Comment by ahocevar** [comment]
For @ThomasG77's use case, I created #8226. With that change, a vector layer can be used as source for the raster source.

For @shaunakv1's use case, I fixed #8216. With that change, clipping can be implemented in a much more convenient way, as shown in the code pen linked from there.

**Comment by ahocevar** [comment]
For @ThomasG77's use case, I created #8226. With that change, a vector layer can be used as source for the raster source.

For @shaunakv1's use case, I fixed #8216. With that change, clipping can be implemented in a much more convenient way, as shown in the code snippets there.
