### ISSUE TITLE
mvt vectortile with multiPolygon not displayed

### ISSUE THREAD

**Issue by songyumeng** [openlayers/openlayers#8148]
I want to dispaly some MVT vectortile ,but I found some polygon is not displayed like this.The white background color should be same as others.
![image](https://user-images.githubusercontent.com/29563916/39518533-d87ce07a-4e35-11e8-83f5-22c851e2fbf8.png)

I debug the source code and found that

![image](https://user-images.githubusercontent.com/29563916/39518750-cd7acdbc-4e36-11e8-91ea-56b834ff91af.png)

`ends` does not match `endss`.  I think ` endss.push(ends.slice(prevEndIndex, i))` has some problems ， when `i=0` and `prevEndIndex=0` , `ends[0]` has to be `[]` .

I modify` endss.push(ends.slice(prevEndIndex, i))` to `endss.push(ends.slice(prevEndIndex))`,the background color is displayed correctly.
![image](https://user-images.githubusercontent.com/29563916/39519276-b3f87dec-4e38-11e8-9854-30f6c557d460.png)

Is this a bug?

**Comment by ahocevar** [comment]
Can you share a live example that shows the issue?

**Comment by songyumeng** [comment]
Thanks for your reply.
There is an example: [examples](https://codepen.io/songyumeng/pen/rvYjXy).
The background color of "10,164,-148" tile  should be red.
![image](https://user-images.githubusercontent.com/29563916/39702521-ba4adf98-5237-11e8-92e6-10efd7c3da2e.png)

**Comment by songyumeng** [comment]
I try to add a function flips the linearRingIsClockwise in format/MVT. But a I encountered some new issue after that.

My data is like this:
![image](https://user-images.githubusercontent.com/29563916/84348078-b3777680-abe6-11ea-857e-562d3f676e4f.png)

But he shows like this
![image](https://user-images.githubusercontent.com/29563916/84348155-d86be980-abe6-11ea-8aa8-c434881b6143.png)

I think it may be a problem in `MVT.js#L204 ~ L216` .
I may need a little more time to test and fix.

**Comment by songyumeng** [comment]
I try to add a funcrion flips the linearRingIsClockwise in format/MVT, but I encountered new problems:

I have two holes in the rectangle，like this
![image](https://user-images.githubusercontent.com/29563916/84353651-20443e00-abf2-11ea-9565-6f7f5ce775a0.png)

But aflter i fix linearRingIsClockwise check，it show like this：
![image](https://user-images.githubusercontent.com/29563916/84353785-5bdf0800-abf2-11ea-9b7b-ee0912d5cb8c.png)

I think it may be a problem in `format/MVT.js#L204~#L216`
I may need a little more time to test and fix.

**Comment by ahocevar** [comment]
Thanks for your investigation @songyumeng. Take your time. Would be great if you could fix the whole issue.

Maybe also take a look at https://github.com/mapbox/vector-tile-js/blob/a9a9102/lib/vectortilefeature.js#L129-L193, to compare how they convert tile geometries to GeoJSON.

For rendering tests, which we'd definitely need, I think it would be good if you could create GeoJSON from your test geometries, use  [geojson-vt](https://github.com/mapbox/geojson-vt) to convert them them to MVT, and render those in comparison to the original GeoJSON.
