### ISSUE TITLE
Vector source issue when working with vector layer in Angular 5

### ISSUE THREAD

**Issue by cristianmurillo87** [openlayers/openlayers#8149]
Hello, I'm trying Openlayers 4 with es2015 modules and Angular 5. When instantiating classes like Vector layers and sources, errors related to name conflicts (maybe because the names are the same) keep appearing and aliases for the import statements seem not to fix the problems:

`import { Vector as VectorSource } from 'ol/source/vector';`
  `import Vector as 'ol/layer/source';`
`...`

`this.myVectorLayer = new Vector({`
   `    source : new VectorSource({`
      `    url : 'http://url/to/file.geojson',`
      `    format : new GeoJSON()`
   `    });`
`    });`

**Comment by ahocevar** [comment]
Your imports are not valid. Try something like this instead:
```js
import VectorSource from 'ol/source/vector';
import Vector from 'ol/layer/vector';
import GeoJSON from 'ol/format/geojson';

this.myVectorLayer = new Vector({
  source : new VectorSource({
    url : 'http://url/to/file.geojson',
    format : new GeoJSON()
  });
});
```

**Comment by cristianmurillo87** [comment]
It works perfectly....thank you very much!
