### ISSUE TITLE
Feature request: don't check "crs" property on GeoJSON object when default one is provided in constructor

### ISSUE THREAD

**Issue by mainakae** [openlayers/openlayers#8152]
As stated in  #8147, GeoJSON objects with CRS property are checked for type "name" (rejecting "EPSG", see #8151).

A possible sensible solution could be to stop checking for CRS in the GeoJSON object if _defaultDataProjection_ and/or _featureProjection_ are provided during ol.format.GeoJSON instantiation.

This fix would allow to load **valid GeoJSON** without messing with proxies, altering back-ends or coding any deeper into GeoJSON implementation.

**Comment by ahocevar** [comment]
A pull request should also implement the change suggested in https://github.com/openlayers/openlayers/issues/7967#issuecomment-375658146 (rename `defaultDataProjection` to `dataProjection`). When `dataProjection` is provided on the `GeoJSON` format instance or in the read options, the `crs` on the GeoJSON object should be ignored.
