### ISSUE TITLE
Feature request: accept type "EPSG" on GeoJSON CRS property

### ISSUE THREAD

**Issue by mainakae** [openlayers/openlayers#8153]
As noticed in #8147, GeoJSON format implementation is not accepting type "EPSG", contrary to error documentation (as of 4.6.5 release, or 2d413bb36de263eb383452bb23e7badeeefbd070).

Being **valid GeoJSON** according to the [fifth](http://wiki.geojson.org/GeoJSON_draft_version_5) and [sixth](http://wiki.geojson.org/GeoJSON_draft_version_6) draft specifications, this library should accept it.

There's another related feature request (#8152) that would fix a wider spectrum of problems (as faulty CRS definitions in GeoJSON objects), but still I think it's not the right fix for the present feature request.

This feature request would render #8151 (fixing error documentation) obsolete, as it would fix the deeper problem.

**Comment by ahocevar** [comment]
I'd rather not implement more logic to get the projection from the GeoJSON, because the final standard does not have/recommend the use of a `crs` object.

**Comment by mainakae** [comment]
Good enough for me too!
