### ISSUE TITLE
Feature Request: Support Nominatim Search API

### ISSUE THREAD

**Issue by bentrm** [openlayers/openlayers#8154]
I would like to be able to parse [Nominatim API](https://wiki.openstreetmap.org/wiki/Nominatim) results and add them to the map directly. 

* The APIs results can be delivered in XML and JSON. I'd prefer JSON for ease of implementation.
* Every results holds `lat` and `lon` properties that describe the items centroid(?).
* If the parameter `polygon_geojson` is set, the result items have a valid `geojson` property of the places outline.
* results are weighted for importance which may be interesting for styling features of result sets.

I sketched up a `NominatimJSONSearch` solution that checks wether the result sets items are GeoJSON defering to the existing `ol.format.GeoJSON` to parse for a valid geometry. If `geojson` is not present, a simple point geometry is created. **May I send a PR?**

Future iterations _may_ include a NominatimSearchSource that uses the maps current bounding box as a search filter.

***

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
This feature request is a perfect example for a plugin, and there exists one already: https://github.com/jonataswalker/ol-geocoder. See https://openlayers.org/3rd-party/ for more plugins.
