### ISSUE TITLE
Get rid of externs/oli.js

### ISSUE THREAD

**Issue by pfirpfel** [openlayers/openlayers#8158]
Based on [this comment](https://github.com/openlayers/openlayers/issues/7947#issuecomment-382763378).

> The next task is to get rid of `oli.` interfaces. In addition to doing the same thing we did for `olx.*`(see #7947), this requires to change all object properties listed in `oli.` interfaces to use bracket instead of dot notation (e.g. `this['coordinate'] = options.coordinate` instead of `this.coordinate = options.coordinate`).

**Comment by tschaub** [comment]
Before converting to bracket notation, it would be good to demonstrate that this is necessary.

**Comment by ahocevar** [comment]
Actually we do not need to convert to bracket notation. The 5.x full build does not mangle object properties (see console log in https://codepen.io/anon/pen/mLqrgJ when clicking on the map), and users who build their application together with the library won't suffer from mangling anyway.

So to move this forward: getting rid of `oli.js` works the same way as getting rid of `olx.js`.

**Comment by tschaub** [comment]
`oli.js` is a bit different from `olx.js` in that we don't use the former for type checking at all.  So we don't need new `@typedef` when we remove `oli.js`.  Instead, we remove all the `@implements` annotations.
