### ISSUE TITLE
Long continuous scrolling mouse, the  google map  can not load normally 

### ISSUE THREAD

**Issue by jimtion** [openlayers/openlayers#8162]
when i use the program to control the mouse rolling for a long time. At first，the map is normal,but after about 4 four hours,The map no longer loads tiles properly. the map.tileQueue_.tilesLoading_=16,I try to make map.tileQueue_.tilesLoading_ is 0,but this can not have a good result. Sometime the map have some blank，when i move  the map，the blank is still in map，the ol3 can not request these tiles again. i also try clear tileCache， and control the tileQueue_ length，but these methods can not solve  problems

**Comment by ahocevar** [comment]
Probably a duplicate of #7271, and fixed in master.

**Comment by ahocevar** [comment]
Probably a duplicate of
