### ISSUE TITLE
Ship ol.js with NPM

### ISSUE THREAD

**Issue by Niondir** [openlayers/openlayers#8176]
Hey, Im new to OpenLayers. I'm very confused by alle the imports when using WebPack and examples. All the documentation wants me to use WebPack but all the examples just ignore that classes need to be imported.

I would like to see the `ol.js` and `ol.css` shipped with NPM to at least be able to install OpenLayers with NPM without knowing all the imports.

Or do I miss something? Using the webpack imports I'm not even able to add a marker to the map. The example gives me `new OpenLayers.Layer.Markers("Markers");` but the API doc seems not to know anything about markers.

**Comment by ahocevar** [comment]
Looks like you were looking at OpenLayers v2 API docs. There is no `OpenLayers.Layer.*` in recent versions of OpenLayers.

For v4, he imports yo need are shown in the [API docs](https://openlayers.org/en/latest/apidoc), right next to the class/package name. v5, when released, will also have that documented.

If you really want to use a full build (not recommended for production), you can download it from the [releases](https://github.com/openlayers/openlayers/releases) page.
