### ISSUE TITLE
Change default import recommendation for ol.Map

### ISSUE THREAD

**Issue by ThomasG77** [openlayers/openlayers#8178]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

In http://openlayers.org/en/latest/apidoc/ol.Map.html, change in the documentation `import Map from 'ol/map';` as `Map` is already a function in JavaScript e.g 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
I clearly never use `Map` but I wonder if this collision is a good thing (although semantically current situation is OK)

**Comment by tschaub** [comment]
I think we should leave things as they are.  If people want to use the native `Map` constructor in the same module that imports from `ol/Map`, they can choose a different name for the import.  There is no global pollution, so this only affects people who use both in the same module.
