### ISSUE TITLE
Allow scaling zoom delta in ol.interaction.MouseWheelZoom

### ISSUE THREAD

**Issue by icholy** [openlayers/openlayers#8183]
For my application, the jumps between zoom levels are too high. I've set `constrainResolution` to false, but this doesn't help because I'm not using a trackpad. I was hoping for a way to scale the zoom delta value.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).

**Comment by python1981** [comment]
Documentation indicates this should be possible but I cannot seem to get it working with either version 4 or 5.

https://openlayers.org/en/latest/apidoc/module-ol_interaction.html
