### ISSUE TITLE
I am using OpenLayers2, in the initial page load i added some locations after that i need to do filtering so that i refresh the map and need to add new locations. In here i used "ol.strategy.refresh()" and i try to bind new locations, when i debug and checked its bind but in the map its display the locations which are loaded in the initial page load. In here i am using angularjs directive. Please help me to solve this problem...

### ISSUE THREAD

**Issue by Nishan-Than** [openlayers/openlayers#8198]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [ ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by bartvde** [comment]
this issue tracker is for openlayers 3 and higher, not 2

Please use stackoverflow instead
