### ISSUE TITLE
Graticule Latitude Label Text Cut Off

### ISSUE THREAD

**Issue by greggian** [openlayers/openlayers#8199]
In the current version of OpenLayers, the Graticule Latitude Text Labels are cut off. Note how the N/S suffix is missing. http://openlayers.org/en/latest/examples/graticule.html

I checked older versions to see when it was introduced and it first appears in [v4.4.0](http://openlayers.org/en/v4.4.0/examples/graticule.html). The labels were not cut off in version v4.3.4 and the expected behavior can be seen for comparison. http://openlayers.org/en/v4.3.4/examples/graticule.html

There were a lot of changes betweeen v4.3.4 and v4.4.0 so I am having a hard time finding the offending change. I'd appreciate any help narrowing down the issue/fix.

**Comment by fredj** [comment]
same issue in the 5.x branch

**Comment by fredj** [comment]
probable because the text is centered by default
