### ISSUE TITLE
In Openlayers 4 missing NavigationHistory control feature whereas it exists in Openlayers 2

### ISSUE THREAD

**Issue by amufeetha** [openlayers/openlayers#8206]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
Try the [ol-hashed](https://npmjs.com/package/ol-hashed) package, which is a combination of OpenLayers 2 permalink and navigation history. For the latter, it uses the browser's history, i.e. back and forward buttons.
