### ISSUE TITLE
I am using OpenLayer 2, i displayed map with its location data to my web screen after that when i open the print preview button of browser map is not display, help me why..??

### ISSUE THREAD

**Issue by Nishan-Than** [openlayers/openlayers#8212]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [ ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by Nishan-Than** [comment]
Please help me to give an idea to display map on the print preview screen

**Comment by bartvde** [comment]
This issue tracker is not for OpenLayers 2, but for 3 and up. Please post your question on stackoverflow instead with the openlayers tag
