### ISSUE TITLE
Smooth zooming in open layers 2 in case of TMS layer

### ISSUE THREAD

**Issue by dixitgoyal** [openlayers/openlayers#8214]
Hi admin, i'm facing issue in zooming open layers map when i embedd tiled image via TMS layer. Any kind of help will be appreciated.

**Comment by ahocevar** [comment]
Please consider upgrading to a recent version of OpenLayers (4 or 5 beta).

**Comment by dixitgoyal** [comment]
But transformation box is not available in recent version.
