### ISSUE TITLE
Transformation box is not available in latest version

### ISSUE THREAD

**Issue by dixitgoyal** [openlayers/openlayers#8215]
Is there any way to make transformation box for circle feature under modify interaction

**Comment by ahocevar** [comment]
You can use the [Transform interaction](http://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html) from the [ol-ext](http://viglino.github.io/ol-ext/index.html) library.

**Comment by dixitgoyal** [comment]
Hi ahocevar, it would be really helpful if you can tell me how to implement code mentioned in below fiddle in latest version of open layers.

http://jsfiddle.net/expedio/L529bqb5/
