### ISSUE TITLE
Mousedown, mouseup, mousemove events are missing in latest version

### ISSUE THREAD

**Issue by dixitgoyal** [openlayers/openlayers#8219]

**Comment by ahocevar** [comment]
OpenLayers 3+ is built around pointer events. On the map, you can listen for `pointermove`. If you need other events, simply register for native browser events on the map's target element, and use the map's `getEventPixel()` or `getEventCoordinate()` method to get the view pixel or coordinate for the event.

Example:
```js
map.getTargetElement().addEventListener('mousedown', function(e) {
  console.log('mousedown', map.getEventPixel(e), map.getEventCoordinate(e));
});
```

**Comment by will-moore** [comment]
Using OpenLayers 5.3.0 I seem to find that this e.g. ```mousedown``` events are ignored, but ```click``` events work OK:

```
# I think this worked in OpenLayers 3 but not in OpenLayers 5?
map.on('mousedown', function(event) {
    console.log("map mousedown")
});
```

**Comment by ahocevar** [comment]
@will-moore That also did not work in OpenLayers 3. If you need to listen to mouse events, register them on the map's target element (`ol/Map#getTargetElement`). If pointer events (emulated by OpenLayers on browsers that don't natively support them) work for you, you can use the `pointerdown` event instead.
