### ISSUE TITLE
Regular Polygon handler missing in latest version

### ISSUE THREAD

**Issue by dixitgoyal** [openlayers/openlayers#8220]
Actually i wan to draw the circle with move event of regular polygon handler, but i'm unable to implement the same in latest version of open layers

**Comment by ahocevar** [comment]
Drawing in OpenLayers 3+ works differently. You do not need such a handler. You can draw a circle directly using the `ol/interaction/Draw` interaction with `type: 'Circle'`. See https://openlayers.org/en/v5.0.0-beta.13/examples/draw-features.html. If you want to draw a regular polygon that approximates a circle instead, configure the interaction with `geometryFunction:  createRegularPolygon(32)` (where 32 is the number of vertices for the circle-like shape).

Example:
```js
import Draw, {createRegularPolygon} from 'ol/interaction/Draw';

new Draw({
  source: source,
  type: 'Circle',
  geometryFunction: createRegularPolygon(32)
});
```

**Comment by ahocevar** [comment]
In this case, configure the Draw interaction also with `freehand: true`.

**Comment by dixitgoyal** [comment]
I there any trigger available for complete drawing?

**Comment by ahocevar** [comment]
There is `'drawend'`. See http://openlayers.org/en/beta/apidoc/module-ol_interaction_Draw-Draw.html.
