### ISSUE TITLE
Error using typescript types with openlayers

### ISSUE THREAD

**Issue by BobbyT** [openlayers/openlayers#8228]
Hello,

I'm currently using OpenLayers 4.6.4 with `@types/openlayers` 4.6.4  in my TypeScript Angular 6 project.

When I'm including the types in my project 
```import * as ol from 'openlayers';```
I'm getting the following error (ol-debug.js):

`Uncaught Error: Uncaught (in promise): TypeError: map.getOverlayContainerStopEvent is not a function`

Without the types, however, the error doesn't occur:
```declare var ol: any;```

Any idea what might go wrong?

Here is the function where it fails:

```
ol.control.Control.prototype.setMap = function(map) {
  if (this.map_) {
    ol.dom.removeNode(this.element);
  }
  for (var i = 0, ii = this.listenerKeys.length; i < ii; ++i) {
    ol.events.unlistenByKey(this.listenerKeys[i]);
  }
  this.listenerKeys.length = 0;
  this.map_ = map;
  if (this.map_) {
    var target = this.target_ ?
      this.target_ : map.getOverlayContainerStopEvent(); // <--- THIS LINE
    target.appendChild(this.element);
    if (this.render !== ol.nullFunction) {
      this.listenerKeys.push(ol.events.listen(map,
          ol.MapEventType.POSTRENDER, this.render, this));
    }
    map.render();
  }
};
```

**Comment by 8byr0** [comment]
Hi BobbyT,
Using OpenLayers with TypeScript is a bit tricky and its behaviour is not exactly the same as in pure js applications.

By the way, you cannot import using `import * as ol from 'openlayers'`

You need to import all the required components manually.

For example, a basic map would be : 
```javascript
import Map from 'ol/map'
import TileLayer from 'ol/layer/tile'
import OSMSource from 'ol/source/osm'
import View from 'ol/view'

// [...]

 let map = new Map({
        layers: [
          new TileLayer({
            source: new OSMSource()
          })
        ],
        target: 'map',
        view: new View({
          center: [0, 0],
          zoom: 2
        })
      });
```

From my experience it is the only way to do it. A trick I found is to manually declare all components in an interface, see this repo I created : [Link to repo](https://github.com/8byr0/ol-angular-demo/blob/master/src/app/ol-comp/oldef.ts)

```javascript
import OlMap from 'ol/map'
import OlView from 'ol/view'
import OlLayerTile from 'ol/layer/tile'
import OlSourceOSM from 'ol/source/osm'




var ol = {
  Map: OlMap,
  View: OlView,
  layer: {
    Tile: OlLayerTile
  },
  source:{
    OSM: OlSourceOSM
  }
}

export default ol;
```

Using this simple trick you can reuse the same structure as in JS examples and documentation. All you have to do is 
```javascript
import import ol from './oldef' // Where oldef.ts is your definition file
```

I know it's not really a long-term solution but it's the only one I personnally found to deal with this issue. If you've got other ideas, feel free to share !

Best regards!
