### ISSUE TITLE
Geolocation example issue

### ISSUE THREAD

**Issue by Adrien98** [openlayers/openlayers#8235]
I have created a [CodePen](https://codepen.io/anon/pen/eKmNQX?&editors=1010) to illustrate the problem, I'm programming an equivalent geolocation application with Angular and there are some bugs : (not the same bugs with Chrome and Firefox, I'm using the last versions)

- Chrome : when I'm changing the navigation tab and reopen it (I'm not closing the tab but only swap it) I see that (with a `console.log("on")`) the `geolocation.on` function is exectued every time I do this experience.

- Firefox : same thing but also every five seconds the `geolocation.on` function is executed with no reason ...

That's very problematic because I'm working with GeoJSON files on servers ... But also the map refocuses incessantly.

![2018-05-30 11_59_23-geolocation](https://user-images.githubusercontent.com/31937302/40713725-f10b04c4-6400-11e8-997e-cb7eae7b8aa2.png)

(I have only pressed one time the track checkbox)

**Comment by fredj** [comment]
`geolocation.on('change:position')` is called every time a change is detected by the browser but OpenLayers doesn't check if the coordinates have really change. This is probably what happens in your example.

**Comment by Adrien98** [comment]
@fredj Is there a way to prevent incessant calls from the function or navigators are blocking the situation ?

**Comment by fredj** [comment]
You can add a test in the callback to check if the position really changed

**Comment by Meesgieling** [comment]
To fix the Firefox problem of updating every 5 seconds you can call geolocation.once instead of geolocation.on as said here https://openlayers.org/en/latest/apidoc/ol.Geolocation.html#once
