### ISSUE TITLE
Mapping tool

### ISSUE THREAD

**Issue by anavidi** [openlayers/openlayers#8237]
Hi. I'm a Dot Net Developer and I'm looking for a 3rd party tool that allows me to show objects on a USA map (taken from a database) and once you click on each individual object on the map, it takes you 1+ level deeper, so you can obtain more information about that particular object. Does your company have such tool that is integrated into Visual Studio?

Thanks,

Al

**Comment by ahocevar** [comment]
OpenLayers can do this, but it's JavaScript. Not sure if this is what you are looking for.
