### ISSUE TITLE
All unit tests failing after importing ol in a Create-React-App app.

### ISSUE THREAD

**Issue by lduros** [openlayers/openlayers#8239]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

I have created a file and React component, which imports some of the OL classes at the top of the file using the import notation. Now whenever I run jest tests, using `yarn test`, I get the following error:

```
 ● renders correctly

    /Users/lduros/Development/quartet-ui/node_modules/ol/map.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _ol_ from './index.js';
                                                                                                    ^^^^
    
    SyntaxError: Unexpected identifier
      
      at new Script (vm.js:74:7)
      at Object.<anonymous> (src/plugins/epcis/src/components/MapBody.js:21:12)
```

Has anyone encountered something like this?

Here is what I'm importing in my MapBody.js file, and everything works fine from the UI in the app, it's only when running tests, and those tests don't even interact directly with the MapBody.js file, it only happens during loading:

```
import React, {Component} from "react";
import "ol/ol.css";
import Map from "ol/map";
import View from "ol/view";
import Tile from "ol/layer/tile";
import OSM from "ol/source/osm";
import proj from "ol/proj";
import Point from "ol/geom/point";
import Feature from "ol/feature";
import Vector from "ol/source/vector";
import Style from "ol/style/style";
import Icon from "ol/style/icon";
import VectorLayer from "ol/layer/vector";
````

Many thanks,

**Comment by lduros** [comment]
Nevermind, I found another thread on this.

Thanks,

**Comment by jpuskar** [comment]
Feel free to post a link...

**Comment by orpheus** [comment]
yeah link to thread please

**Comment by bryanSME** [comment]
@lduros - this page is the top result on google with  `"import Feature from 'ol/Feature';" "jest"`.  Where is this other link?
