### ISSUE TITLE
event.pixel and getPixelFromCoordinate() problem

### ISSUE THREAD

**Issue by ghost** [openlayers/openlayers#8240]
This very strange as **getFeaturesAtPixel( event.pixel )** returns an object but **getFeaturesAtPixel(getPixelFromCoordinate([-0.0508, 51.5160]))** returns null.
Can someone end this nightmare!!

       var vectorLayer = new ol.layer.Vector({
        source: new ol.source.Vector({
          url: 'https://openlayers.org/en/v4.6.5/examples/data/geojson/countries.geojson',
          format: new ol.format.GeoJSON()
        })
      });

         var map = new ol.Map({
                   layers: [ vectorLayer],
                   target: 'map',
                   view: new ol.View({
                                center: [0, 0],
                                 zoom: 1
                    })
                });

       map.on('click', function(evt) 
      {  
		  var pixel = map.getPixelFromCoordinate([-0.0508, 51.5160]);
                  
                  //returns an Object
		  console.log(map.getFeaturesAtPixel(evt.pixel));  

                  //returns  null
		  console.log(map.getFeaturesAtPixel(pixel));  
	  });

**Comment by bartvde** [comment]
is your map in EPSG:4326? If it's in spherical mercator (3857) you will need to provide the coordinate in that projection

**Comment by bartvde** [comment]
so indeed you need to provide the coordinate in EPSG:3857 instead

**Comment by bartvde** [comment]
Use ```ol.proj.fromLonLat``` to do thathttps://openlayers.org/en/latest/apidoc/ol.proj.html#.fromLonLat

**Comment by kasterbe** [comment]
Results are null

var coords = ol.proj.fromLonLat([-0.0508, 51.5160], new ol.proj.Projection("EPSG:3857"));
also
var coords = ol.proj.fromLonLat([-0.0508, 51.5160], new ol.proj.Projection("EPSG:4326"));
var pixel = map.getPixelFromCoordinate(coords);
console.log(map.getFeaturesAtPixel(pixel)); // null

**Comment by bartvde** [comment]
did you try swapping lon and lat values?

**Comment by bartvde** [comment]
so:

```
var coords = ol.proj.fromLonLat([51.5160, -0.0508]);
```

**Comment by kasterbe** [comment]
yes still returns null.

**Comment by bartvde** [comment]
please show a jsFiddle or similar then with the issue

**Comment by kasterbe** [comment]
https://jsfiddle.net/qe7ddaed/6/

**Comment by ramanamuttana** [comment]
```
var geometry = polyFeature.getGeometry();
var coordinate = geometry.getCoordinates();
var pixel1 = map.getPixelFromCoordinate(coordinate);
```

console.log(coordinate[0]);

> output:7.129808
but map.getPixelFromCoordinate(coordinate);
console.log(pixel1);
output:null
what is the reason ?????

here is the below code ,,since it is in the EPSG:3857 why i am getting the null values ???
```
var polyFeature = new ol.Feature({
    geometry: new ol.geom.Point(
        ol.proj.toLonLat([7.129808, 50.618671], new ol.proj.Projection("EPSG:3857")))
}); 

var vectorLayer = new ol.layer.Vector({
    source: new ol.source.Vector({
        features: [polyFeature]
    })
});

var centerPoint = ol.proj.toLonLat([7.128499, 50.617803], new ol.proj.Projection("EPSG:3857"));

var osmLayer = new ol.layer.Tile({
source: new ol.source.OSM()
});

var view = new ol.View({
center: centerPoint,
zoom: 18
});

var map = new ol.Map({
target: 'map',
layers: [ osmLayer,vectorLayer]
});

var geometry = polyFeature.getGeometry();
var coordinate = geometry.getCoordinates();
var pixel1 = map.getPixelFromCoordinate(coordinate);
map.setView(view);
```

**Comment by ahocevar** [comment]
Your map has not been rendered yet, so the pixel/coordinate transform has not been calculated yet. Change the last 2 lines of your snippet to:
```js
map.once('postrender', function() {
  var pixel1 = map.getPixelFromCoordinate(coordinate);
});
map.setView(view);

**Comment by ramanamuttana** [comment]
map.once('postrender', function() {
 var geometry = polyFeature.getGeometry();
var coordinate = geometry.getCoordinates();
var pixel1 = map.getPixelFromCoordinate(coordinate);
});
map.setView(view)

 it worked with the above code  ,,thanks
