### ISSUE TITLE
map inside "display:table" div container is squeezed when Device Pixel Ratio > 1

### ISSUE THREAD

**Issue by piotr-gawron** [openlayers/openlayers#8253]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

-------------
I couldn't provide CodePen example because if the code is in the iframe the problem doesn't appear...

-------------
The problem appears when the map is inside a container that has css style "display:table", but only on devices that have Device Pixel Ratio > 1. It's easy to reproduce on normal screens by running Chrome, clicking on toggle device toolbar and choosing a device that has Device Pixel Ratio bigger than one.

Here is the simple test page that I shows the error:
```
<html>
<head>
    <script src="https://openlayers.org/en/v4.6.5/build/ol.js"></script>
    <link rel="stylesheet" href="https://openlayers.org/en/v4.6.5/css/ol.css" type="text/css">

    <script type="text/javascript">
      //<![CDATA[

      function initMap() {
        var map = new ol.Map({
          layers: [
            new ol.layer.Tile({
              source: new ol.source.OSM()
            })
          ],
          target: 'mapDiv',
          view: new ol.View({
            center: [0, 0],
            zoom: 2
          })
        });
      }

      //]]>
    </script>
<body onload="initMap();" style="width:100%;height:100%;margin:0">
<div style="display: table; width: 100%; height: 100%;">
    <div style="display:table-row">
        <div style="min-width:357px; display:table-cell">
        </div>
        <div style="display: table-cell; height: 100%; width: 100%;">
            <div id="mapDiv" style="width: 100%; height: 100%;"></div>
        </div>
    </div>
</div>
</body>
</html>
```

When the page is opened in a browser with Device Pixel Ratio = 1 everything is normal. However with ratio>1 the map is squeezed, zooming doesn't work properly, and click coordinates are not corresponding to the place on map. For the convenience I put the example on one of our dev machines: https://minerva-dev.lcsb.uni.lu/bug.html

Here is how the problematic map looks like:
![squeezed](https://user-images.githubusercontent.com/6151055/41093582-01958b6a-6a4c-11e8-9f9f-dc3185e542dd.png)

And just for the comparison, here is how it looks like when ratio = 1:
![good](https://user-images.githubusercontent.com/6151055/41093596-07129ee8-6a4c-11e8-90a0-9d653e4783c1.png)

**Comment by ahocevar** [comment]
100% height of what? There is no parent container with a defined height on your page.
