### ISSUE TITLE
UMD support

### ISSUE THREAD

**Issue by taoqf** [openlayers/openlayers#8254]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

Could ol support umd ?
I could not find a ol.js or any js file in umd style in npm.
I used to use a amd loader when I am developing.
Now I have to use openlayers back.

**Comment by taoqf** [comment]
I'm trying to help generate umd files but I could not find where is the 'ol' package's source code. 
I wish there is a subfolder 'umd' in package ol. Could any one help me or just point me out how could I contribute? many thanks. @tschaub

**Comment by aberenyi** [comment]
What are you after exactly?

Do these help?
https://unpkg.com/openlayers@4.6.5/dist/ol.js
https://unpkg.com/openlayers@4.6.5/dist/ol.css
https://cdnjs.com/libraries/openlayers

**Comment by taoqf** [comment]
I wish I could write my code like this:
```js
const Map = require('ol/map');
const map = new Map();
```
And I use a amd loader to load js modules, now I have to `require('openlayers');`
I do want use `ol` instead of 'openlayers'. because I could not generate js files rightly use webpack when I publish my project.

**Comment by ThomasG77** [comment]
@taoqf You need to use `ol` package and use ES6 `import`.
There are several examples pointed in [`ol` package on npmjs](https://www.npmjs.com/package/ol)
If you really need to keep `require`, [babel-plugin-transform-es2015-modules-commonjs](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs) should do the job.

**Comment by aberenyi** [comment]
From what you've said I'd say it's more like a `webpack` config issue than an `ol`/`openlayers` one.

I'm using `webpack` with `ol`, so I can confirm it's doable.

If you share a bit more info about the issue that you're having w/ `webpack` I might be able to help.

**Comment by taoqf** [comment]
Actually, I use TypeScript in my project, and I use umd output when I'm debugging, and use commonjs when I bundle the files use webpack.
I't nothing to do with webpack @aberenyi 
my code always like this:
```ts
import Map from 'ol/map';
const map = new Map();
```

**Comment by taoqf** [comment]
Where is the `ol` project thing? can I contribute if you guys do not have time.

**Comment by taoqf** [comment]
I just with there is a folder in release.
like this:
https://unpkg.com/ol@4.6.5/umd/*.js
which are umd output style.

**Comment by taoqf** [comment]
@ahocevar How can I contribute? I really need this.
https://github.com/taoqf/openlayers
I try to rewrite it using typescript, but it's really a lot work to do. and I don't have that much time now.
It will be very kind if there is a umd module when I am developing my project.

**Comment by ahocevar** [comment]
@taoqf It should be straightforward to use something like [babel-plugin-transform-es2015-modules-umd](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-umd) to transform our modules into umd format?

If you want to help out with TypeScript, stay tuned for new tickets here that we'll be adding soon. We want to investigate the use of JSDoc TypeScript annotations, which is what Webpack and others have been using too recently.

**Comment by taoqf** [comment]
I will use babel when I build my project.
I only need umd when I am developing

**Comment by ahocevar** [comment]
For what purpose? If it's for easier debugging, don't source maps work for you?

**Comment by taoqf** [comment]
I'm afraid source maps don't work for me. 
I use an umd loader to load all my js file when i'm debugging.

**Comment by ahocevar** [comment]
You should start using source maps instead.

**Comment by taoqf** [comment]
I think maybe it should be me who close this issue.
because I don't think you understood me and my problem is resolved.
you will know this better when you try typescript.
I don't want change my code before I build my project with webpack and babel.
I just want use and umd loader while I am debugging and use commonjs when I build my project with webpack.
source maps is not a good solution for my use case.

**Comment by taoqf** [comment]
Or give me a direct how can I contribute to `ol`'s building script if you are so kind.
