### ISSUE TITLE
WMS size

### ISSUE THREAD

**Issue by sebalaini** [openlayers/openlayers#8259]
How OL4 determine the size of a WMS tile? 

I own the server and I use Mapserver/cache to create the map, I have an xml that creates me the cache and have it's own grid. 

Both xml and map files have:

`SIZE 250 250`

Even though the request from OL4 is 256 X 265 and I use `ratio: 1` in `ol.source.TileWMS`

In order to speed up the tile request I would like to reduce the size and have smaller images.
I'm already using `  preload: Infinity,` but I need to cut off the size of the images.

**Comment by bartvde** [comment]
the tilegrid associated with the source has a default tileSize of [256, 256]

**Comment by sebalaini** [comment]
So in the source I need to add `tileGrid` and then add an array with [200X200] ?

**Comment by bartvde** [comment]
look at this example which has a non-standard tilesize: https://openlayers.org/en/latest/examples/xyz-esri-4326-512.html?q=tilesize

**Comment by bartvde** [comment]
ah sorry that is XYZ source and you are asking about TileWMS, so yes create a tilegrid with tileSize [250,250]

**Comment by sebalaini** [comment]
thanks :) if I want an inferior size like 100X100 I need to reduce also the mapserver config or OL4 will ask for what the grid value is?

**Comment by sebalaini** [comment]
it seems not, thanks you :)
