### ISSUE TITLE
Create a clustering algorithm that is administrative boundary/polygon aware 

### ISSUE THREAD

**Issue by nigel-v-thomas** [openlayers/openlayers#8262]
Dear all,

I'd like to request a new feature in clustering, would it be possible to make clusters administrative boundary aware? By this I mean something like this:

![6129eef2-1f33-11e5-8674-86a728a76363](https://user-images.githubusercontent.com/1025109/41229273-4bee25da-6d73-11e8-829f-3c14d68f5cc9.png)
[Source https://thefoodassembly.com/](https://thefoodassembly.com/)

Can you suggest an approach for this with OpenLayers?

Thanks,
Nigel

- [ x ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ x ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ x ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ x ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by fredj** [comment]
please use stackoverflow to ask this kind of question: https://stackoverflow.com/questions/tagged/openlayers
