### ISSUE TITLE
Avoid pixel doubling for a mobile display - OpenLayers

### ISSUE THREAD

**Issue by Adrien98** [openlayers/openlayers#8265]
https://gis.stackexchange.com/questions/285896/prevent-pixel-doubling-for-a-mobile-display-openlayers

I have created a StackExchange topic on GIS but the question seems to be harder than I thought. So I'm posting this topic in GitHub too. To sum up, I want to display my layers on mobile but OpenLayers is automatically doubling every pixel of the layer, something I would like to avoid (so the layer is blurry)

It is an OpenLayers parameter which can not be changed or no ?

**Comment by ahocevar** [comment]
Just configure your map with
```js
    devicePixelRatio: 1
```

**Comment by GISerWYJ** [comment]
I have a same issue. I use ol 5 in a cordova app, my basemap is  a ArcGIS Server tile service with a local coordinate system, the map is always blurry (tile is doule size on mobile phone, pixel ratio > 2), and it seems to be the ol/Map pixelRatio value cannont make an effect on this. here is the sample code:

```
proj4.defs('EPSG:2436', '+proj=tmerc +lat_0=0 +lon_0=117 +k=1 +x_0=500000 +y_0=0' +
      ' +ellps=krass +towgs84=15.8,-154.4,-82.3,0,0,0,0 +units=m +no_defs');
register(proj4);
```
```
this.map = new Map({
      target: 'map',
      pixelRatio: 1,
      layers: [
        new Tile({
          source: new XYZ({
            url: 'http://112.30.63.69:6080/arcgis/rest/services/hfMap/MapServer/tile/{z}/{y}/{x}',
            projection: 'EPSG:2436',
            tileSize: 256,
            tilePixelRatio: 1,
            tileGrid: new TileGrid({
              extent: [398530.95986140973, 3422296.6396190766, 673169.0091375083, 3606711.5917823147],
              resolutions: resolutions,
              tileSize: [256, 256],
              origin: [-5123300.0, 1.00023E7]
            })
          })
        })
      ],
      view: new View({
        center: fromLonLat([117.27465, 31.87304], 'EPSG:2436'),
        zoom: 2,
        enableRotation: false,
        projection: 'EPSG:2436',
        resolutions: resolutions
      })
    });
```

// this is the normal resolution viewed in desktop , device ratio = 1
![image](https://user-images.githubusercontent.com/12789732/45593868-101e1100-b9c2-11e8-9627-8f7e0a5b73c2.png)

// this is the one viewed in iPhone5 , which looks blurry,device ratio = 2
![image](https://user-images.githubusercontent.com/12789732/45593885-989cb180-b9c2-11e8-8b64-bf3f3e11c168.png)

How can I solve this? @ahocevar ,Thank you!
