### ISSUE TITLE
[Question] How can I render React JS / Angular component html template as point on map?

### ISSUE THREAD

**Issue by balab2020** [openlayers/openlayers#8267]
Hi,

I need to render a point which has run-time behavior with respect to data feed by backend. I would like to render component html from React JS, Angular or Knockout JS.

Please suggest.

Thanks,
Balamurugan

Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by balab2020** [comment]
I think that I am asking similar to marker in Openlayers 2.

**Comment by ahocevar** [comment]
That would be `ol/Overlay`. But don'd create maps with more than a handful of overlays. If you have more, create an `ol/layer/Vector` instead.

**Comment by balab2020** [comment]
@ahocevar Thanks for input.

My requirement is showing more points on map. Every point should render a html template which can have dynamic behavior with data using some framework. In my case, I am using Knockout JS to render the html template. 

Can overlay be used to render more items on map?

**Comment by ahocevar** [comment]
Try yourself. It works, but performance is better with vector layers and features. You have several options there to style text labels, but no template support.
