### ISSUE TITLE
Scale Line Control incorrect for EPSG:4326 projection

### ISSUE THREAD

**Issue by greggian** [openlayers/openlayers#8279]
I noticed that using the default ScaleLine control when the map projection is set to "EPSG:4326", causes an incorrect scale value.

Here is a sample pen, using the scaleline control example with only the map projection changed:
https://codepen.io/anon/pen/OEOavV
Notice the "500000000 km" scale value. I believe it should be closer to "5000 km". If you change the map projection back "EPSG:3857", I see the expected value.

I am not 100% sure of the cause but in some initial debugging, removing the following line resolves the issue (at least for my exact use case): https://github.com/openlayers/openlayers/blob/master/src/ol/control/ScaleLine.js#L210

**Comment by ahocevar** [comment]
This has been fixed already a while ago in #7908.
