### ISSUE TITLE
Valid GeoJSON will not render

### ISSUE THREAD

**Issue by KhaledSharif** [openlayers/openlayers#8284]
Valid GeoJSON, produced on geojson.io, will not render in OpenLayers. I have created two pens on CodePen to demonstrate this.

[This pen works normally, as it is taken from the OL examples + some minor modifications](https://codepen.io/khaledsharif/pen/vrpgVw)

[This pen has different GeoJSON and is unable to render.](https://codepen.io/khaledsharif/pen/eKygQy) No errors appear in the console.

Please note that even with the valid CRS specified (which I believe is EPSG:4326), the GeoJSON still does not render.

**Comment by ahocevar** [comment]
When using inline GeoJSON (i.e. provided to the format as `features` instead of `url`, you need to pass an object with the `featureProjection` as 2nd argument to the `readFeatures()` function. I have updated your codepen: https://codepen.io/anon/pen/qKprEv.
