### ISSUE TITLE
Graticule in Polar Stereo Projections

### ISSUE THREAD

**Issue by jangell** [openlayers/openlayers#8288]
Graticule in polar stereo projections are displaying incorrectly.

I've found that the meridians go from the pole to the latitude of the center of the top of the viewport, which doesn't reach the corners (with the viewport containing or above the pole) or disappears entirely (with the viewport below it). The parallels appear to stretch from the longitude of the upper corner closer to the prime meridian to the longitude of the lower corner on the same side.

In addition, the parallels try to iterate around the map when the viewport crosses the prime meridian, going from -180 to 180 even when the viewport does not contain the pole, and at higher zooms this runs out of lines unless maxLines is set high.

I've created a CodePen [here](https://codepen.io/jangell/pen/dKJBZj) to demonstrate the issue (on the left), along with a partial workaround (on the right). The projection is defined using proj4, with the following string:
`+proj=stere +lat_0=90 +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=3396190 +b=3376200 +units=m +no_defs`

Map reference and projection reference URLs are listed in the comments in the first few lines of the CodePen.

**Comment by ahocevar** [comment]
If you're willing to work on improvements, we'd gladly accept a pull request. Looks like your workaround could be a good starting point.

**Comment by jangell** [comment]
I'd be happy to.
