### ISSUE TITLE
[advice] use glm reader from node.js

### ISSUE THREAD

**Issue by cyrilchapon** [openlayers/openlayers#8289]
Hello :)

I'm trying to parse a gml document, and convert it to GeoJSON, from Node.js

I tried to import OpenLayers, and shim it using webpack (shimming window, document, etc.)

But for the specific case of gml reader, this uses a "dom"-like API for xml.

Is there a way to use GML reader, and GeoJSON writer, from Node.js (without a DOM implementation) ?

**Comment by afogelberg** [comment]
I use [jsdom](https://www.npmjs.com/package/jsdom) and [xmlserializer](https://www.npmjs.com/package/xmlserializer) to read gml with OpenLayers in Node.js.

**Comment by cyrilchapon** [comment]
😱 can you please provide some example or something ?

> Also, how did you install openlayers ? (`ol` or `openlayers` package ?)

> Did you transpile something ?

**Comment by afogelberg** [comment]
I transpile ol package to es5. You can see my setup in [geomangler](https://github.com/afogelberg/geomangler).

**Comment by cyrilchapon** [comment]
Hey @afogelberg thanks about it 😄 

As far as I can see, you actually patch `global` with XmlSerialiser and dom to make OpenLayer work, and transpile OpenLayer on `postinstall script that's it ?`

**Comment by afogelberg** [comment]
That's is @cyrilchapon :thumbsup:
