### ISSUE TITLE
dispathevent  Invalid

### ISSUE THREAD

**Issue by TheStylite** [openlayers/openlayers#8300]
##MyIssure

	hello,Sometimes, the dispatchEvent event of openlayers does not completely realize the effect of custom events. The following is the code I developed:

    map.on('pointermove',function (evt) {
    
        map.forEachFeatureAtPixel(evt.pixel,function (feature) {
        
            feature.dispatchEvent('click');
        })
    });

    circle.on('click',function () {
        console.log('i am out');
        this.setStyle(new ol.style.Style({
            image:new ol.style.Circle({
                radius:30,
                fill:new ol.style.Fill({
                    color:'blue'
                })
            })
        }))
    });

	Sometimes, in the browser, when the load is completed, the click effect can be achieved. Once the console is opened or F5 is pressed to refresh the browser, the dispatchEvent click event will fail and become a MouseMove event,This is a small problem I encountered during the development process to test the problem. It's been an afternoon, but none of them have been solved。What is the best solution?

**Comment by ahocevar** [comment]
Why dispatch a click event? Why not just
```js
map.on('pointermove',function (evt) {
    map.forEachFeatureAtPixel(evt.pixel, function(feature) {
      console.log('i am out');
      this.setStyle(new ol.style.Style({
          image:new ol.style.Circle({
              radius:30,
              fill:new ol.style.Fill({
                  color:'blue'
              })
          })
      }))
    })
});
