### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by taoqf** [openlayers/openlayers#8304]
Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [x] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

I'm trying rewrite this project use TypeScript. But got a problem:

https://github.com/taoqf/openlayers/blob/1699ca0f181d352edf87f2ead7ed2163a79166c3/src/ol/featureloader.ts#L134

could anyone help me? @andy-ms, you have time? I think it is a `this` thing.

I think it will be great if written in ts.

**Comment by andy-ms** [comment]
Doesn't look like a compiler bug. `loadFeaturesXhr` is declared with `this: VectorSource`. That's a this-parameter, meaning the function can't be called with a normal call expression, which doesn't set `this`.

**Comment by taoqf** [comment]
https://github.com/openlayers/openlayers/blob/master/src/ol/featureloader.js
this is origin js file.
I tried to rewrite it using typescript.

**Comment by taoqf** [comment]
Yes, I think it's a bad idea using `this` here, so I plan to remove it. many thanks.
