### ISSUE TITLE
Error on using sidebar to openlayers

### ISSUE THREAD

**Issue by paulorosouza** [openlayers/openlayers#8307]
Good afternoon

I'm using the sidebar (https://github.com/Turbo87/sidebar-v2) for OpenLayers, but using ol.js directly from the site (// openlayers.org/en/master/build/ol.js" ) started to present the following error

ReferenceError: undefined $ o is not defined [Learn More] Projection.js: 80: 2
_and
Projection.js: 80: 2
If
epsg3857.js: 52: 2
<anonymous>
epsg3857.js: 73: 2
<anonymous>
http://openlayers.org/en/master/build/ol.js:1:2

That since Thursday, 06/22/2018.

Has any modification been made to this js?

**Comment by ThomasG77** [comment]
Already answered or at least, mention how to fix the issue on short term at https://stackoverflow.com/questions/50994830/error-on-using-sidebar-for-openlayers
