### ISSUE TITLE
Allow adding request headers to ol.layer.VectorTile requests

### ISSUE THREAD

**Issue by coder123456** [openlayers/openlayers#8308]
Can we please have an easy way to add headers to a vector tile request. Passing authentication token using Header is a common use case.

**Comment by ahocevar** [comment]
You can configure the VectorTile source with a custom `tileLoadFunction`. Is that easy enough? See http://openlayers.org/en/master/apidoc/module-ol_source_VectorTile.html:
```js
function(tile, url) {
  tile.setLoader(function() {
    var data = // ... fetch data
    var format = tile.getFormat();
    tile.setProjection(format.readProjection(data));
    tile.setFeatures(format.readFeatures(data, {
      // featureProjection is not required for ol/format/MVT
      featureProjection: map.getView().getProjection()
    }));
    // the line below is only required for ol/format/MVT
    tile.setExtent(format.getLastExtent());
  };
});
```

**Comment by ahocevar** [comment]
No response from issue creator, closing.

**Comment by rajanski** [comment]
there is example code on the right side, if you scroll a bit down: https://openlayers.org/en/master/apidoc/module-ol_source_VectorTile.html
It uses fetch, and this describes how to add headers using fetch: 
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#supplying_request_options

also: https://developer.mozilla.org/en-US/docs/Web/API/fetch
