### ISSUE TITLE
Style file is missing in Readme Example

### ISSUE THREAD

**Issue by SelimAbidin** [openlayers/openlayers#8312]
Hello,

`import "ol/ol.css";`

Style code is missing in [Readme](https://github.com/openlayers/openlayers/blob/master/src/ol/README.md)' example. Since some features doesn't work properly without ol.css.

Thank you.

**Comment by fredj** [comment]
Isn't the css import specific to webpack?

**Comment by ahocevar** [comment]
@fredj Parcel supports it out of the box (see https://github.com/openlayers/openlayers/blob/eef39d3d1d34055250c88eb31725b382a632222f/doc/tutorials/bundle.md), and most other bundlers support it too with a bit of configuration.
