### ISSUE TITLE
finishCondition not triggered for some types

### ISSUE THREAD

**Issue by joseahr** [openlayers/openlayers#8313]
I've seen that when using `finishCondition` property in `ol/interaction/draw`, will not trigger the event for points and boxes (type `circle`). [See codepen](https://codepen.io/anon/pen/ERpLdm?&editors=1010).

I would like to have this feature for all the types.

An example use case:

I need to draw features, and check if intersects or it's contained by other feature.

BTW, I workaround this in `drawend` event, by checking if it intersects and removing the feature.

Why finishCondition is not called for these types?
It would be nice if finishCondition were called for these types in order to avoid this duplicated code.

Thanks in advance.

**Comment by cazacugmihai** [comment]
Hi! 

Please reopen this issue because it is still actual (e.g. it is not triggered for circle). 

Thank you!

**Comment by ahocevar** [comment]
If someone can provide a pull request with a fix, it would be much appreciated!

**Comment by zta6** [comment]
@ahocevar has this issue been fixed? I've looked around for the PR that could have fixed it but can't find it. If it was fixed what openlayers version is the fix in?

**Comment by ahocevar** [comment]
For Circle, the finishCondition is now triggered. The fix is already in `ol@dev` and will be in the next release.

**Comment by zta6** [comment]
what about for `Box`?

**Comment by MoonE** [comment]
@ahocevar, the finishCondition does not seem to be called for circles.
I'm not even sure how it should work. For lines and polygons you can always add more points but a circle, point or box requires a set amount of points only. The finishCondition only controls if the drawing should be finished, not if the point should be discarded.

**Comment by ahocevar** [comment]
@MoonE For points, the finishCondition is not called. But all other types, it is now. A circle is finished with the 2nd point. This is new since the recent changes that @mike-000 made in #11753.

**Comment by MoonE** [comment]
I can't seem to get the finishCondition function called for box or circle because `sketchCoords_.length` is never greater than `minPoints_` for circles as you don't have to click at the same position twice to finish. @mike-000  could you have a look at this?
The following change fixes this.
```patch
diff --git a/src/ol/interaction/Draw.js b/src/ol/interaction/Draw.js
index 207fdf677..fafdacdd0 100644
--- a/src/ol/interaction/Draw.js
+++ b/src/ol/interaction/Draw.js
@@ -695,7 +695,9 @@ class Draw extends PointerInteraction {
       let potentiallyDone = false;
       let potentiallyFinishCoordinates = [this.finishCoordinate_];
       const mode = this.mode_;
-      if (mode === Mode.LINE_STRING || mode === Mode.CIRCLE) {
+      if (mode === Mode.CIRCLE && this.sketchCoords_.length >= this.minPoints_) {
+        at = true;
+      } else if (mode === Mode.LINE_STRING) {
         potentiallyDone = this.sketchCoords_.length > this.minPoints_;
       } else if (mode === Mode.POLYGON) {
         const sketchCoords = /** @type {PolyCoordType} */ (this.sketchCoords_);
```

**Comment by ahocevar** [comment]
@MoonE I'd be in favor of the change you outlined above. It also makes the code easier to read. Would you be able to create a pull request with that change? Thanks in advance.

**Comment by mike-000** [comment]
@MoonE No double click is needed for Circle as `maxPoints` is always set to 2 https://github.com/openlayers/openlayers/blob/main/src/ol/interaction/Draw.js#L296 so `Mode.CIRCLE` is the same as `Mode.LINE_STRING` with `maxPoints` set to 2 by the application

**Comment by MoonE** [comment]
Thanks for your responses @ahocevar and  @mike-000. I create #11821 to resolve this issue.
