### ISSUE TITLE
Poor image quality at low zoom levels

### ISSUE THREAD

**Issue by danzaharescu** [openlayers/openlayers#8316]
Hello all,

At a first impression, the quality of the rendering seems really good.
However, at low zooms the quality of the image often decreases.
Please check this example from demo:
http://openlayers.org/en/latest/examples/static-image.html
At lowest zoom, the image seems broken (check the lines from the bottom left area = 'Not a complete survey...'). I have downloaded the image and opened it with Irfan viewer, also directly with the browser and put it into a small html application inside a canvas.
Every one of these tests gave a much greater quality of the image at low zoom.
It could be the case, that OpenLayers is designed to work with already prepared images at many zoom levels, so no fix should be implemented, or does it look like a real problem that should be fixed ?
Please let me know if any additional clarification is needed on this topic (ex: screenshots, etc..).

My regards,
Dan

**Comment by fredj** [comment]
This is expected in this demo.
Viewing the image directly in a browser (zoomed 500%) and in OpenLayers at the same zoom gives me the same quality result.

**Comment by danzaharescu** [comment]
Thanks for the quick reply.
But the problem occurs at low zooms (not high). So try to make the image as small as possible.
I cannot upload a html file, it seems, but it is very small, so I copy the contents:
So, you may simply copy paste the content, put it in a html file, and directly open it with a browser.
Then, check the same zoom with OpenLayers.

<!DOCTYPE html>
<html>
<body>
<p>Image to use:</p>
<img id="test" width="256" height="242"
src="https://imgs.xkcd.com/comics/online_communities.png" alt="The Test">
</body>
</html>

**Comment by fredj** [comment]
ok, I see it now. I misunderstood low zoom

**Comment by ahocevar** [comment]
OpenLayers outputs the source image to a target canvas that matches the screen resolution. In this process, the image gets anti-aliased, which causes some blur. Like @fredj said, this is expected. You can configure your map with `pixelRatio: 2` to get a higher resolution output canvas, at the cost of slower rendering.

**Comment by danzaharescu** [comment]
Your advice works, than you.
