### ISSUE TITLE
Support Sandbox.io to replace CodePen?

### ISSUE THREAD

**Issue by ThomasG77** [openlayers/openlayers#8324]
With OpenLayers 5.0 release (and ES6 modules), there is now way to share quickly a demo for demonstrating issue without going through WebPack/Parcel.
It was codepen role. I've investigated how to do it using Sandbox.io (discovered via https://twitter.com/openlayers/status/924003219293925376)

You will find [a small demo](https://bl.ocks.org/ThomasG77/raw/4051f9a8fc90fd6fd1a2785363f70974/) to make a call to their API and create the sandbox (PS: change the JS code block when creating `index.js` as it seems to be cached due to repeated tests).

The idea would be about making the call when clicking on a button (like it was with Codepen) for creating Sandbox.io sample from official sample.
At the moment, I only want to know if it would be considered OK to work on this feature

**Comment by ahocevar** [comment]
We will be working on a new example generator in the next weeks, with nicer looking examples. We will be creating tickets to invite contributors to help. The first steps can be seen in the `site` branch already. A working replacement for codepen will be appreciated, also if you can contribute to make it work with the new examples. So yes, you can consider this as an OK. Just don't start this work with the current example setup/template.

**Comment by fredj** [comment]
See #9103

**Comment by prusswan** [comment]
Examples that can work without bundling (like the one at https://openlayers.org/en/latest/doc/quickstart.html) is still desirable for some situations (e.g.  offline use). Is there any way to use the ES modules/examples without running a bundler? (maybe prebundled ol.js with ES syntax? does this make sense?)
