### ISSUE TITLE
Use ES6 classes and inheritance

### ISSUE THREAD

**Issue by gberaudo** [openlayers/openlayers#8328]
The OpenLayers5 code is using constructor functions and inheritance using util.inherits().
ES6 introduced the concept of class which:
- is well understood by IDEs;
- allow using `super` in constructor and methods;
- is a prerequisite to using typescript as JSDoc or direct typescript authoring as described in #8120.

I have started experimenting with [lebab](https://github.com/lebab/lebab) for transforming our 250 constructors to classes.
Before I invest more time:
- is a PR welcome?
- have anyone already experimented with such transform?

**Comment by gberaudo** [comment]
@ahocevar, have you had time to investigate typescript already?
What is your opinion about this issue?

**Comment by ahocevar** [comment]
@gberaudo I didn't have time to investigate that yet.

**Comment by tschaub** [comment]
@gberaudo contributions welcome on #8385.  I've run an auto-transform and done a fair bit of manual cleanup.  Remaining work is listed on that PR.
