### ISSUE TITLE
ol-debug.js and ol-debug.css not found in 5.0.0

### ISSUE THREAD

**Issue by kochizufan** [openlayers/openlayers#8330]
- [x] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [x] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [x] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

I checked 5.0.0, but no ol-debug.js and ol-debug.css found.
Are they deprecated?
Are there any build command to create ol-debug.js and ol-debug.css by myself?

**Comment by ahocevar** [comment]
We don’t generate these any more. ol.js and ol.css have working source maps now (ol.js.map and ol.css.map), so you don‘t need ol-debug.js and ol-debug.css any more.

**Comment by kingofnull** [comment]
There is any way to generate from source?

**Comment by ahocevar** [comment]
For `ol-debug.js`, you can e.g. create a rollup configuration like this:
```js
// Rollup configuration for the full build

import noderesolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import buble from 'rollup-plugin-buble';

export default {
  input: 'build/index.js',
  output: [{file: 'build/ol-debug.js', format: 'iife'}],
  plugins: [noderesolve(), commonjs(), buble()]
};
```
Save that to `rollup-config.js`, and then run `npm run build-index && rollup --config rollup-config.js`.

**Comment by kingofnull** [comment]
Thank you so much @ahocevar

**Comment by sverrirs** [comment]
The sourcemaps do not enable the same level of step-through debugging and troubleshooting as the old `ol-debug.js` allowed devs to do. It is a shame that you don't consider including this in the official build given the fact that it is so easy to generate as you point out. 

I'd really like to encourage the OL team to reconsider the decision for not providing a debug dist package for v5.x.

In any case the docs should be updated to make this omission of the debug package clearer: https://github.com/openlayers/openlayers/wiki/OpenLayers-v5.x#users-of-a-full-build-oljs-or-ol-debugjs

**Comment by mortac8** [comment]
I am stuck on OpenLayers 4.6 because I'm using the ol-debug.js so I can have access to ol.Tile to extend it.  Can anyone tell me how I can get access to ol.Tile in OpenLayers 6 builds?

**Comment by kingofnull** [comment]
> I am stuck on OpenLayers 4.6 because I'm using its ol-debug.js so I can have access to ol.Tile to extend that class for some custom functionality we need (ol.Tile is not accessible using the OL 4.6 minified ol.js).
> 
> Can anyone tell me how I can create a class that extends ol.Tile in OpenLayers 6 (where ol.Tile doesn't seem to exist on the main 'ol' object)?
> 
> Note: Our codebase still uses RequireJS and I am just 'requiring' the main ol.js or ol-debug.js file to get my ol object.

I recommend you to switch to node and build method but a fast and dirty way is to build ol-debug as mentioned and then for extending class run your code after page loaded and after a delay using setTimeout.
