### ISSUE TITLE
Uncaught TypeError: Cannot read property 'array_' of undefined

### ISSUE THREAD

**Issue by rafik73github** [openlayers/openlayers#8336]
Hello
An error has occurred since version 5.0.0:
Uncaught TypeError: Cannot read property 'array_' of undefined
    at Q.remove (Collection.js:226)
    at Q.forEach (Collection.js:135)
    at Cl.<anonymous> (villages.php:437)
    at Cl.h (events.js:41)
    at Cl.w.dispatchEvent (EventTarget.js:96)
    at Cl.K.notify (Object.js:172)
    at Cl.K.set (Object.js:192)
    at Cl.As.setActive (Interaction.js:89)
    at Object.setActive (villages.php:549)
    at HTMLFormElement.optionsForm.onchange (villages.php:1111)

The error concerns the lines of my code:

`selectedFeatures.forEach(selectedFeatures.remove, selectedFeatures);`

all code:

```
var Select = {
        init: function() {
          this.select = new ol.interaction.Select(
          {
          style:selectedStyle
		  //,
		 // condition: ol.events.condition.click
          }
          );
          map.addInteraction(this.select);

          this.setEvents3();
        },
        setEvents3: function() {
          var selectedFeatures = this.select.getFeatures();
	
          this.select.on('change:active', function() {
            selectedFeatures.forEach(selectedFeatures.remove, selectedFeatures);
	
          });
```

The problem occurs when I want to deactivate the interaction.
It worked properly with version 4.6.5.

Greetings

Thank you for your interest in making OpenLayers better!

To keep this project manageable for maintainers, we ask you to please check all boxes below before submitting an issue.

- [ ] I am submitting a bug or feature request, not a usage question. Go to https://stackoverflow.com/questions/tagged/openlayers for questions.
- [ ] I have searched GitHub to see if a similar bug or feature request has already been reported.
- [ ] I have verified that the issue is present in the latest version of OpenLayers (see 'LATEST' on https://openlayers.org/).
- [ ] If reporting a bug, I have created a [CodePen](https://codepen.io) or prepared a stack trace (using the latest version and unminified code, so e.g. `ol-debug.js`, not `ol.js`) that shows the issue.

**Comment by ahocevar** [comment]
Please see the [release notes](https://github.com/openlayers/openlayers/releases), especially the section **Removal of optional this arguments**. You need to change the code inside the `change:active` handler to something like
```js
selectedFeatures.forEach(selectedFeatures.remove.bind(selectedFeatures));
```
