### ISSUE TITLE
Bundle size is too big

### ISSUE THREAD

**Issue by cs09g** [openlayers/openlayers#8337]
Hi, I've been using OL with custom build with version 4.5. The build I've customized with build.json is about 240kb. but with 5.0 served from npm, its bundle size is 1.7mb. I just followed [bundle tutorial](https://github.com/openlayers/openlayers/blob/master/doc/tutorials/bundle.md) to load basic OSM map though. How can I include only things that are really required?

**Comment by ahocevar** [comment]
You can enable tree shaking for the parcel bundler, using the `--experimental-scope-hoisting` option on the `build` task. See  see parcel-bundler/parcel#392. This will significantly reduce your bundle size.

You can also try using different bundlers. Rollup is known to produce small bundles, and an example configuration is linked from the [ol package](https://npmjs.com/package/ol) README.

When comparing final bundle sizes, I'd also recommend comparing gzipped sizes. Closure compiler, which was used for custom builds in v4.x, uses very aggressive name mangling which leaves less room for gzip compression. Also keep in mind that the Parcel bundle includes all your application code, which the browser had to fetch with another expensive server request in the v4.x scenario you described.

**Comment by bartvde** [comment]
I'm also running into this one just now

```
> node scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  788.3 KB (-828.67 KB)  build/static/js/main.f40f7a95.js
  23.35 KB               build/static/css/main.679cd9e7.css

The bundle size is significantly larger than recommended.
Consider reducing it with code splitting: https://goo.gl/9VhYWB
You can also analyze the project dependencies: https://goo.gl/LeUzfb

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  http://bit.ly/2vY88Kr

```

**Comment by bartvde** [comment]
This is what I get in my app currently

![selection_612](https://user-images.githubusercontent.com/319678/42216133-11e4e022-7ec1-11e8-8656-c9426f2bde28.png)

**Comment by cs09g** [comment]
separating import and add `--no-source-maps` makes it smaller. But if we could choose specific methods in classes, that would be much better. does it even possible to do this?

**Comment by the-vampiire** [comment]
@bartvde what did you use to generate that image?

**Comment by cs09g** [comment]
@the-vampiire try [bundle analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer)

**Comment by the-vampiire** [comment]
@cs09g neat man thanks
