### ISSUE TITLE
there is no moving event for map in ol5

### ISSUE THREAD

**Issue by mysisi** [openlayers/openlayers#8340]
in my case (like this [d3 Integration](http://openlayers.org/en/latest/examples/d3.html) ), i use Image for my layer and ImageCanvas for source, i use canvasFunction to draw my own data, while the zoom or center is changed, canvasFunction is used to recalculate data position in canvas. But during the moving, the data will get scale with the map, I expect is there something like moving event, i can use to render my ImageCanvas so that i won't be larger or smaller.......

**Comment by raiyni** [comment]
http://openlayers.org/en/latest/apidoc/module-ol_MapEvent-MapEvent.html#event:moveend

**Comment by mysisi** [comment]
@raiyni is there any showcase?

**Comment by bartvde** [comment]
https://openlayers.org/en/latest/examples/moveend.html?q=moveend

**Comment by mysisi** [comment]
@bartvde this case is about moveend, while i want to call canvasFunction when moving.

**Comment by ahocevar** [comment]
@mysisi The events for that would be `change:center` and `change:resolution`.

**Comment by mysisi** [comment]
@ahocevar thx, i see ol canceled all map fires related to change

**Comment by ahocevar** [comment]
Can we close this @mysisi?

**Comment by mysisi** [comment]
@ahocevar i still wonder when will you add change:resolution or change:center events to ol?
