### ISSUE TITLE
IE11 not supported anymore

### ISSUE THREAD

**Issue by cvenzin** [openlayers/openlayers#8356]
Openlayers does not work anymore with Internet Explorer 11:
See for example https://openlayers.org/en/latest/examples/zoomify.html

Error: Const must be initialized

IE11 does not support something like:
for(const a of [1, 2, 3]){
}

**Comment by bart-256** [comment]
I can confirm. Map is not loading anymore on IE11 for any of the examples at openlayers.org and my project. I've tried to set compatibility through "browserslist" in packages.json:
```
  "browserslist": [
    "ie 11"
  ]
```
but that didn't help.

In IE11 console it shows it's an error on line 24 in ol/obj.js

**Comment by ahocevar** [comment]
Thanks for the report. We can add a transpilation to the examples build process, and document along the way how users can do the same in their build configurations.
