### ISSUE TITLE
Polygon freehand drawing won't work properly on OL5

### ISSUE THREAD

**Issue by 0trenixjetix** [openlayers/openlayers#8360]
An example of this is[here](http://openlayers.org/en/latest/examples/draw-freehand.html?q=draw
)
after drawing a polygon (a triangle with no freehand drawing) freehanded drawings won't close consistently.
This broke my app so i downgraded to OL4.
I would like to know how to solve this situation or if there is a change that i don't know how to implement but after reading the changelog of OL5 and trying extensively to draw with modifier keys i think it is a bug.
I am looking forward to upgrade and i wish you can explain me how does it work.

**Comment by 0trenixjetix** [comment]
Hi, this problem has reappeared on the next builds and drawing polygons is still a problem. The draw example doesn't work propperly. Check by yourself.
![drawfail](https://user-images.githubusercontent.com/8699204/44892197-b93aeb00-ace3-11e8-947d-e6382cf55b27.gif)

**Comment by fredj** [comment]
[draw-freehand](http://openlayers.org/en/latest/examples/draw-freehand.html) is working for me on chrome

**Comment by sbrunner** [comment]
OK for me on Firefox ...

**Comment by ahocevar** [comment]
@0trenixjetix Can you provide more detailed steps to reproduce?

**Comment by 0trenixjetix** [comment]
I'm using the [draw-features example](http://openlayers.org/en/latest/examples/draw-features.html) without freehand activated by default. If you try to do like in my gif, i still see the problem.

Just try to draw a polygon first without freehand and later add some freehanded line, if you release "fast" the Shift key you may end losing your drawing, after that drawings are somewhat inconsistent. 
![drawfail2](https://user-images.githubusercontent.com/8699204/44919882-d3ee7d80-ad3e-11e8-81b2-c03d0aa13179.gif)

**Comment by fredj** [comment]
I can reproduce the issue:
 * http://openlayers.org/en/latest/examples/draw-features.html
 * select Polygon
 * draw a polygon without using the shift key
 * draw an other polygon with shift key

-> the polygon disappear

**Comment by 0trenixjetix** [comment]
When it's ready im going to upload a gif.

**Comment by 0trenixjetix** [comment]
Here you go
![drawfail2](https://user-images.githubusercontent.com/8699204/44923168-c5589400-ad47-11e8-8ce5-d02f0731930f.gif)

**Comment by fredj** [comment]
The first bad commit is fa75b78bf9a64c0abadf11c8efa1f897c4221029

This patch fixes the issue:
```diff
diff --git a/src/ol/interaction/Draw.js b/src/ol/interaction/Draw.js
index 63713f836..f89b33e94 100644
--- a/src/ol/interaction/Draw.js
+++ b/src/ol/interaction/Draw.js
@@ -834,7 +834,7 @@ export function handleEvent(event) {
   this.freehand_ = this.mode_ !== Mode.POINT && this.freehandCondition_(event);
   let move = event.type === MapBrowserEventType.POINTERMOVE;
   let pass = true;
-  if (this.lastDragTime_ && event.type === MapBrowserEventType.POINTERDRAG) {
+  if (!this.freehand_ && this.lastDragTime_ && event.type === MapBrowserEventType.POINTERDRAG) {
     const now = Date.now();
     if (now - this.lastDragTime_ >= this.dragVertexDelay_) {
       this.downPx_ = event.pixel;
```

But I'm really not sure it's the good way to fix it.

**Comment by ahocevar** [comment]
@fredj I tested your fix, and I do not notice any negative side effects. Thanks for the investigation, and feel free to create a pull request.
