### ISSUE TITLE
still no webworker support...

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#8361]
Hi there,

I was hoping openLayers 5 would add some up to date features like webworkers and stepless zooming..

I like openlayers, but software like mapBox is WAY better with this kind of stuff.
Now i can try to contribute, since you finally took the annoying closurecompiler out..

So what is the roadmap? do you guys have like a 'master plan' to get back in the race?
Where can i best start?

**Comment by bbogda** [comment]
Webworkers - it's very desirable thing.
Some kind of stepless zooming olv4 and v5 have... You can zooming among levels on sidebar but it does not work deftly.

**Comment by ahocevar** [comment]
See #8423 for a better discussion on using controls and interactions for continuous zooming.

**Comment by BasieP** [comment]
The topic was webworkers, not zooming and controls...

**Comment by ahocevar** [comment]
Sorry, misread @bbogda's comment as ticket description.

**Comment by ahocevar** [comment]
@BasieP You could start looking into how vector replays are created. That could potentially be done in a worker. However, replaying (which is usually more expensive) needs to happen in the main thread because workers cannot access `CanvasRenderingContext2D` methods and properties.

**Comment by gberaudo** [comment]
[In the news today](https://blog.chromium.org/2018/08/chrome-69-beta-av1-video-decoder-css.html): `OffscreenCanvas` has landed in chrome 69 beta. It allows `2d` and `WebGL` rendering in workers. Firefox already supports it [behind a flag](https://hacks.mozilla.org/2016/01/webgl-off-the-main-thread/).
