### ISSUE TITLE
[Question] ol.format.KML: why is the default image pointing to Google Maps?

### ISSUE THREAD

**Issue by dennisguse** [openlayers/openlayers#8365]
I just observed that the default image style in KML points to a Google URL:
`DEFAULT_IMAGE_STYLE_SRC = 'https://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png';`

Is this URL actually used within Openlayers?
And if yes, does it mean that Openlayers may contact this URL (in case the image is necessary)?

https://github.com/openlayers/openlayers/blob/93eca62cf26eae7b7042a0cd2761e9af95d446c0/src/ol/format/KML.js#L192

**Comment by raiyni** [comment]
Yes, it's the default image used for pins if no style is provided.

**Comment by dennisguse** [comment]
I verified it: loading a simple KML without defining the icon, triggers loading the image from 
https://github.com/openlayers/openlayers/blob/93eca62cf26eae7b7042a0cd2761e9af95d446c0/src/ol/format/KML.js#L192

However, this default behavior might be problematic for two reasons.
**First,** the browser leaks information to a third-party instance.
**Second,** in case of network limitations no image is loaded at all.

Would you be open for a _change request_?
One solution would be to add a parameter to ol.format.KML defining if external resources should be accessed.

**Screenshot: downloading from Google Maps**
![image](https://user-images.githubusercontent.com/2820825/42597217-5e621184-8558-11e8-970d-678ddd226fc6.png)

**Screenshot: failure to load from Google Maps - here browser is offline**
![image](https://user-images.githubusercontent.com/2820825/42597849-8144cd20-855a-11e8-9a84-0b06f0f25fa7.png)

I used the following KML:
`<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Placemark>
    <name>Simple placemark</name>
    <description>Attached to the ground. Intelligently places itself 
       at the height of the underlying terrain.</description>
    <Point>
      <coordinates>-122.0822035425683,37.42228990140251,0</coordinates>
    </Point>
  </Placemark>
</kml>
`

**Comment by raiyni** [comment]
I think it's kind of your own problem if your web browser can't access the Google API because it is offline. You can already provide a style function, a style object to your vector layer, or set the style of each point to null. 

```
point.setStyle(null);
```

And KML files can inherently already access external end points by definition. You can provide an absolute URL to an image file for the style, you can access an absolute URL for Screen Overlays, you can access an absolute URL for Ground Overlays, you can create Network Links to external sources, and you can create links in KMZ files. Granted, not all of these features are supported in OpenLayers yet. So I personally don't see anything wrong. There isn't anywhere in OpenLayers where that is currently an option for vector/tile layers, so why KML?

**Comment by dennisguse** [comment]
I see - so the solution you are suggesting is that I need to override the defaults for the `ol.format.KML`.
Works like charm (see below) [@simonseyock].

However, my issue is that Openlayers accesses a Google server by default.
With the regard to the icons even  [Google says](http://kml4earth.appspot.com/icons.html)
> These URLs are treated as URIs (or aliases) to the corresponding file stored locally which is especially important for closed/standalone environments where the domain maps.google.com cannot be accessed but the icons are still displayed. That is one of the benefits of choosing one of the standard Google icons as opposed to custom icons.
--

_Potential solution:_
To solve this, we could encode the image as base64-URL (it should not be that large) and actually include it in openlayers?

`<link rel="icon" type="image/gif" href="data:image/gif;base64,R0lGODlhQABAAPABABEREf///yH5BAAAAAAALAAAAABAAEAAAAJujI+py+0Po5y02ouz3rz7D4biSJbmiabqyrbuC8cYAMgUbU94Hu384/s1gsIFsZg4Ig/KZaC5hCKlRarQ+sPytDmuzSsDx8Qw8svsQrfULPbKrYKn5Cj6yW7Cl/TOvv8PGCg4SFhoeIiYqLjYUQAAOw=="/>`


_My workaround:_
How to use DnD for KML without applying the KML's default style and thus use the style of the VectorLayer.
```
new ol.interaction.DragAndDrop(
	{
	  formatConstructors: [
		function() { return new ol.format.KML({
                  defaultStyle: null,
                  extractStyles: false
                })}
	  ]
	}
```

**Comment by dennisguse** [comment]
@stale (bot): I still consider this an issue.
