### ISSUE TITLE
Why 'ol/Collection' does not has 'IndexOf' function?

### ISSUE THREAD

**Issue by Abdullah0991** [openlayers/openlayers#8367]
Hi,

Why the ol.Collection doesn't has 'IndexOf' function so we can use it with 'removeAt' function?

**Comment by ahocevar** [comment]
It should not be needed. Try
```js
const index = collection.getArray().indexOf(item);
collection.removeAt(index);
```

**Comment by Abdullah0991** [comment]
Thanks @ahocevar I already know this trick, so you just relay on the native 'Array' functions.

**Comment by ahocevar** [comment]
Correct, @Abdullah0991.
