### ISSUE TITLE
https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.4/ol-debug.js throws error on simple maps

### ISSUE THREAD

**Issue by novumcoder** [openlayers/openlayers#8374]
Im trying to debug OpenLayers Version 4.6.4 trying to understand on how clusters are working. so i tried to load the non-minified version using ol-debug.js. now my map is not working anymore as it is missing methods.

something wrong here?

![grafik](https://user-images.githubusercontent.com/6917790/42574410-a338c17a-851e-11e8-99bd-be1f850aefa5.png)

**Comment by ahocevar** [comment]
Looks like you were using methods that are not part of the supported API. Please make sure to only use methods that are documented in https://openlayers.org/en/v4.6.4/apidoc/
