### ISSUE TITLE
(bug) Raster source cause webworkers threads memory leak

### ISSUE THREAD

**Issue by asafMasa** [openlayers/openlayers#8375]
Steps to reproduce:
1. Create a raster source layer -> web worker created
2. Remove the layer -> layer removed but the webworker isn't terminated or disposed and cause webWorkers thread's leak

Reference: (from the package that you use at Raster source)
https://github.com/tschaub/pixelworks/issues/74

code example: (how to add layer that cause memory leak)
    let source = new OSM();

    const result = new ImageLayer({
        source: new Raster({
            sources: [source],
            operation: (pixels) => pixels[0],
            operationType: 'image'
        })
    });
    mapObject.addLayer(result);

**Comment by EvertEt** [comment]
@asafMasa  I am seeing problems related to this when cycling trough multiple rasterSources, each leaving behind a webworker. Do you know of any workaround?

**Comment by tschaub** [comment]
Calling `source.dispose()` now terminates the workers.
