### ISSUE TITLE
Feature request: ol/interaction/Select~Select without a selection style

### ISSUE THREAD

**Issue by kobbe** [openlayers/openlayers#8379]
I am currently trying to use a layer with a layer style (function) and a select interaction to handle all select logic. The problem I am having is that the select interaction forces a new select style on me.

I request that the select interaction optionally would not alter the style of any feature.

(I can not apply the same style to the select interaction since I have many layers with different styles)

**Comment by ahocevar** [comment]
The Select interaction puts all selected features on a separate layer, which has the Select interaction's style. If you do not want or need that, I'd recommend not using the Select interaction at all. A simple selection logic can be implemented with a few lines of code, using `ol/Map~Map#getFeaturesAtPixel()`. See http://openlayers.org/en/v5.0.3/examples/vector-tile-selection.html for inspiration.

**Comment by Octansf** [comment]
Hi ahocevar I like to know how implement the simple selection logic but the link is broken. Can you show me how to achieve this goal?
Thanks a lot

**Comment by M393** [comment]
Here is the current link: http://openlayers.org/en/latest/examples/vector-tile-selection.html

**Comment by Octansf** [comment]
Thanks M393 but that implementation it not possible when you have more than 10.000 polygons in layer. The canvas  struggle when the all elements in layer try to render and the page go to a slow . The styled must be in a Vector Tile Layer nota Vector Layer.
