### ISSUE TITLE
Geolocation example track position not working

### ISSUE THREAD

**Issue by bernardobelchior** [openlayers/openlayers#8380]
## Problem

The *track position* checkbox does not work on the [Geolocation](http://openlayers.org/en/latest/examples/geolocation.html?q=control) example, returning 
> Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).

## Possible Reason Behind Problem 

The API requires the website to be secure (aka HTTPS).

## Environment
Tested on *Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)* and *Firefox Developer Edition 62.0b7 (64-bit)*.

**Comment by bartvde** [comment]
access the example through https://

https://openlayers.org/en/latest/examples/geolocation.html?q=control
