### ISSUE TITLE
IE 11 support (without transpilation)

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#8384]
When converting to `const` and `let`, it was an oversight on our part that IE 11 does not support `const` or `let` in `for..in` loops.  Unfortunately, this means that all consumers have to set up special rules (e.g. in webpack) to transform the `ol` dependency.  It would be nice for consumers to be able to retain IE 11 support with minimal effort.

Options:
 1. use `for (var foo in bar)` instead of `for (const foo in bar)` in the source
 2. transform sources before publishing
 3. make everybody do more work to get IE 11 support

I like that we don't currently transform before publishing because there are clear limits to the syntax we use.  If we do transform, we will need to decide how far ahead of our target browsers to go - and we risk writing code with crappy performance when transpiled.  But, we could probably control things with our linter rules.

**Comment by marquetd** [comment]
> I like that we don't currently transform before publishing because there are clear limits to the syntax we use. 

Agree
