### ISSUE TITLE
Mark event handler as 'passive'

### ISSUE THREAD

**Issue by jhwegener** [openlayers/openlayers#8387]
Seen in Chrome console on http://openlayers.org/en/latest/examples/mousewheel-zoom.html
`
[Violation] Added non-passive event listener to a scroll-blocking '<event>' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
`

`<event>` is out of
* touchstart
* mousewheel
* wheel

**Comment by ahocevar** [comment]
Actually we cannot set our `mousewheel` and `wheel` listeners to passive because we need to call `preventDefault` on them. Otherwise both the map and the page would scroll.

**Comment by neave** [comment]
The warnings are still displayed so this issue isn’t fixed. It can be fixed by implementing my solution in bug https://github.com/openlayers/openlayers/issues/9482 and declaring the passive behavior, whether it is passive or not.

**Comment by matthiasdailey-ccri** [comment]
Would it be possible to add `{passive: false}` to get rid of the warning message in Chrome?

![image](https://user-images.githubusercontent.com/18034092/68715807-d0749a00-0570-11ea-93f6-2992202e8ff3.png)

I know it's not necessarily your job to cater to the whims of browser manufacturers... Whether or not the Chrome team used their influence to overreach — the goal of making the web more responsive is good, but I don't like the warning message. I understand that they added it to gain visibility on this important feature, but that doesn't mean I have to like it. In any case, it seems that the warning is here to stay. 

A clean DevTools console is a good thing, and false-positive warnings and errors just tend to "cry wolf" and de-sensitize us to the important errors. So to this end, I think it would be good to add `{passive: false}`.

To implement the this, you could set `{passive: false}`, which would allow you to `preventDefault`. But there are browser compatibility considerations — see https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection)
