### ISSUE TITLE
Threshold for clusters

### ISSUE THREAD

**Issue by ojathelonius** [openlayers/openlayers#8389]
Is there a simple way to have a threshold for clusters ? Let's say I do not want to cluster a given set a features unless this cluster would contain over 5 elements.

Solutions online suggest modifying the style function to add a threshold, as shown in the following snippet : 
```javascript
layer.setStyle(function(feature) {
    let size = feature.get('features').length;
    let style;
    if (size > threshold) {
        // Cluster style
    } else {
        // Normal feature style
    }
}
```
However this solution **only allows threshold = 1** ; indeed, features will **still be clustered** no matter the number, albeit with the normal feature style instead of the cluster style.

Other solutions suggest using `minResolution` and `maxResolution` to only display the cluster layer if the threshold is met : 
```javascript
var clusterLayer = new ol.layer.Vector({
    visible: true,                                        
    minResolution: clusteringThreshold,
    cluster: true,
});
```
It seems that this solution requires having two layers with redundant data to work, and it feels more like a hack...

I gave it a shot in the ol.source.Cluster.prototype.cluster_ function and ended up with the following : 

```javascript
// Original (OL3) code
var neighbors = this.source_.getFeaturesInExtent(extent);
ol.DEBUG && console.assert(neighbors.length >= 1, 'at least one neighbor found');
neighbors = neighbors.filter(function(neighbor) {
  var uid = ol.getUid(neighbor).toString();
  if (!(uid in clustered)) {
    clustered[uid] = true;
    return true;
  } else {
    return false;
  }
});

// Add the following
// If one element has more too many neighbors, register it as a cluster of one 
// Size-based styling should be handled separately, in the layer style function

let THRESHOLD = 3; // will be passed as a parameter in the cluster options
if(neighbors.length > THRESHOLD) {
     this.features_.push(this.createCluster_(neighbors));
} else {
    for(var j = 0 ; j < neighbors.length ; j++) {
        this.features_.push(this.createCluster_([neighbors[j]]));
    }
}
```

Am I missing something or is this feature really lacking in OpenLayers ?

**Comment by ahocevar** [comment]
You can get access to the features of a cluster from the cluster feature's `features` property. With that in a style function, you can do something like
```js
const noClusterStyles = [];
vectorLayer.setStyle(feature => {
  const features = feature.get('features');
  if (features.length > 5) {
    return clusterStyle;
  } else {
    noClusterStyles.length = features.length;
    for (let i = 0; ii = features.length; i < ii; ++i) {
      noClusterStyles[i] = noClusterStyle;
    }
    return noClusterStyles;
  }
});
```
In the above snippet, `clusterStyle` is an `ol/Style` you want to use for clustered features, and `noClusterStyle` is an `ol/Style` you want to use for individual features when below the threshold.

**Comment by ojathelonius** [comment]
I didn't think about using the geometry of each feature, thank you. I wish I had found this solution earlier.

Is it a design choice that makes ol/source/Cluster come with very few features out of the box ? It seems like many people have to either override it, or implement complex style functions in order to customize it. 

Do you think that it would be helpful to provide more functionalities through additional parameters (e.g. cluster threshold, maximum zoom till decluster, feature-property based clustering...) ?

**Comment by bartvde** [comment]
@ojathelonius I think @ThomasG77 also did an integration with Supercluster from mapbox: https://webgeodatavore.github.io/supercluster/demo/index-ol.html

https://github.com/openlayers/openlayers/pull/5848
