### ISSUE TITLE
ol/interaction/Draw/createRegularPolygon is not support odd number or Bug?

### ISSUE THREAD

**Issue by iamplex** [openlayers/openlayers#8394]
I'm use createRegularPolygon with odd number param
[http://jsfiddle.net/zy_plex/kzac216p/](http://jsfiddle.net/zy_plex/kzac216p/)

![draw](https://user-images.githubusercontent.com/11267832/42866803-2e0dfbae-8aa0-11e8-8760-ab8eb909c2db.gif)
you can see the mouse point sometimes would leave the sketch

can fix that?

**Comment by ahocevar** [comment]
Pull request welcome. The mouse point is on the circle that all regular polygon vertices are on. A fix would change the start angle of the regular polygon to match the sketch.

**Comment by iamplex** [comment]
I'd gladly to fix this issues. It's done, now start angle always match the sketch
