### ISSUE TITLE
Coloring SVG icons on Retina screens

### ISSUE THREAD

**Issue by Turbo87** [openlayers/openlayers#8406]
I'm trying to use the `color` property of the `Icon` style class in combination with an SVG image. It mostly works okay, but when viewing the result on a Retina screen I noticed that the image wasn't as crisp anymore.

It seems that the canvas that is used for coloring the icon uses a lower resolution than the native screen. I suspect scaling the canvas with the `DEVICE_PIXEL_RATIO` value might solve the problem.

**Comment by ahocevar** [comment]
Right. Actually, it would be `frameState.pixelRatio`. Would you be able to provide a pull request?

**Comment by Turbo87** [comment]
When I tried, it scaled the canvas but the only rendered one fourth of it. Not sure how to tell the renderer to scale it down again.

**Comment by Turbo87** [comment]
what? it's still an issue? should I open a new one after it's closed?!

**Comment by Turbo87** [comment]
see above

**Comment by Turbo87** [comment]
see above

**Comment by MoonE** [comment]
Should be fixed by #11277 in v6.4.3
