### ISSUE TITLE
Old version CSS 3.14.1 resource not found

### ISSUE THREAD

**Issue by RubMart** [openlayers/openlayers#8407]
CSS file for version 3.14.1 disappear. This file is cached in CDN Cloudfare, but not accesible in common link: http://openlayers.org/en/v3.14.1/css/ol.css

If access via browser to the file the response is a 404, File not found 

Another CSS files version such as 3.10.1 or 3.20.1 are available in your correct links:
http://openlayers.org/en/v3.10.1/css/ol.css
http://openlayers.org/en/v3.20.1/css/ol.css

**Comment by raiyni** [comment]
If you are using this in production, don't serve from the Openlayers website. Host the files yourself or access it from a cdn.

https://cdnjs.com/libraries/openlayers/3.14.1
