### ISSUE TITLE
"not a constructor" error: DragPan, PinchZoom, TileDebug

### ISSUE THREAD

**Issue by michaelletzgus** [openlayers/openlayers#8415]
In version 5.1.2 from v5.1.2-dist.zip

`ol.interaction.DragPan()`

gives an error message:  _TypeError: ol.interaction.DragPan is not a constructor_

Same problem with `ol.interaction.PinchZoom()` and `ol.source.TileDebug()`.

All of them are working fine with 5.0.x.

**Comment by ahocevar** [comment]
Thanks for the report. This is an issue with the full build only, the [ol package](https://npmjs.com/package/ol) works fine. I'm going to fix the issue now.

**Comment by tschaub** [comment]
Thanks for the reports.  The debug build is clearly broken right now.  Please do not try to use https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.1.2/build/ol.js or the ol.js build in the release archive.

Using the library with a module bundler works.  If you are able to move to a module bundler, please do.  For inspiration, see [ol-parcel](https://github.com/openlayers/ol-parcel), [ol-webpack](https://github.com/openlayers/ol-webpack), or [ol-rollup](https://github.com/openlayers/ol-rollup).  I just confirmed that all three work with the 5.1.2 release.  I recognize that none of this is particularly helpful to beginners.  Contributions to improve the documentation are welcome.

We'll put out another release with a fixed version of the legacy full build.

**Comment by michaelletzgus** [comment]
v5.1.3 works! :-)

**Comment by arjendk** [comment]
I'm having this issue with ol.tilegrid.WMTSTileGrid on the full build version 6.1.1.

`TypeError: ol.tilegrid.WMTSTileGrid is not a constructor`

Using ol.tilegrid.WMTS, which *is* available according to code inspection, results in the error:

`TypeError: e is undefined`

Is there a solution/workaround?

**Comment by ahocevar** [comment]
The name is ol.tilegrid.WMTS. See https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_WMTS-WMTSTileGrid.html

**Comment by arjendk** [comment]
Thanks Andreas! It looks like my `resolutions` and `matrixIds` don't match up and result in the "e is undefined" error. Sorry for the false report!
