### ISSUE TITLE
No basic examples ? Nothing working, no accessibility for beginners...

### ISSUE THREAD

**Issue by THLCX** [openlayers/openlayers#8416]
Hello

I'm trying to use your OpenLayers 5 library, but you did not made a simple up-to-date wiki or concrete examples for really basic stuff like putting a marker...
Moreover, dead links on your website like this link on the quickstart page https://openlayers.org/en/v5.1.2/apidoc/ol.source.html , etc... That's clearly untested.
And some examples does not work ("import declarations may only appear at top level of a module").

Your tutorial starts with : 
"Building an OpenLayers Application" https://openlayers.org/en/latest/doc/tutorials/bundle.html

But most users may NOT want to create an entire application, just embed some maps on their websites !
What about simply using a .js library ?

To really be useful to people, you should : 
- Make an easily installable project (.js and dependancies... Not starting by linux command lines and installations... Seriously, we are talking about a Javascript lib...)
- Make clear examples about basic cases (add a marker, etc...)
- Test all examples and ensure all wikis are up-to-date.

I just lost an entire hour trying to find something as basic as : 
"how to display a map and multiple marker"...

**Comment by THLCX** [comment]
Solved : Switched to Google Maps... At least it is simple to approach and use, with clear tutorials...

**Comment by tschaub** [comment]
@THLCX your points are valid, and it is helpful to have people bringing attention to things that are broken (like the broken link you mention).

It may not be clear to those that stumble across it on the internet, but this project represents an immense amount of work by people who have contributed code for others to use freely.  I agree that the website is useless for beginners, and a lot of us have entirely rethought it.  An overhaul will take considerable effort and time - and unfortunately people with the right attitude, ability, and time to volunteer are in short supply.

Enjoy your Saturday.

**Comment by THLCX** [comment]
Thanks for you replies. Sorry for my annoyance, I was quite disappointed at the time of the first post.
I'll try the @J-F-O solution.
However, despite the great efforts and good results that I congratulate you for, your library may not be a viable alternative to Google Maps if there is no accessibility :(

**Comment by rduivenvoorde** [comment]
@THLCX please consider to be a little more polite before having so much criticism to a voluntary based project. I'm not even a contributor to OL5, but I feel even offended. 

Looking at your 'github'-activity it does not look like you ever 'gave something back' to community or other projects.
If you are happy with Google Maps (and it's potential costs, and it's privacy and non-free activities) OR really needs some of it's unique functions, feel free to use it. 

If you want 'Change': help by giving information about how accesibility could be improved in FOSS projects, OR even better: add it yourself.

**Comment by THLCX** [comment]
@rduivenvoorde I'm sorry you feel offended.
I edited the comments I wrote when I was really disappointed.
Not contributing do not imply that we should say nothing when there is disappointement.
I understand you can feel offended, but please understand I feel disappointed using the work of so many people - especially good developpers - and see so basic problems.
My emotion comes from the gap between quality of code, and lack of accessibility.
I will follow OpenLayers development, and hope accessibility for basic usage and fast install within php projects (without command lines) and tutorials will be improved.
