### ISSUE TITLE
Problems with fractional zoom (with example)

### ISSUE THREAD

**Issue by pjsg** [openlayers/openlayers#8423]
I'm using v5.1.3 and I'm trying to have the map interactions and controls adjust the zoom by 0.5 (rather than the default of 1). It seems that this ought to be easy -- so I tried:

```
map = new ol.Map({
    controls: ol.control.defaults({zoomOptions:{delta:0.5}}),
    interactions: ol.interaction.defaults({zoomDelta: 0.5}),
    target: document.getElementById('map'),
    layers: [
      new ol.layer.Tile({
            source: new ol.source.OSM()
      })
    ],
    view: new ol.View({
      center: ol.proj.fromLonLat([0, 0]),
      zoom: 1,
      maxZoom: 8,
    })
  });
  ```

but it doesn't work as expect. This is a jsfiddle that demonstrates the problem: http://jsfiddle.net/udfz1053/7/

In particular, if you click the PLUS sign, the zoom goes to 1.5 (this is good). If you click again, it goes to 2.5 (bad). If you now click the MINUS sign, then nothing happens at all. I suspect that the function returned by createSnapToPower is at fault, but I'm not certain what the fix ought to be. It doesn't seem right that I have to override some function inside the view object.

**Comment by ahocevar** [comment]
It's much easier to do this by configuring the view with `zoomFactor: 1.5` (instead of the default of `2`). The numbering of the zoom levels will change with this, so in your console.log, just display `view.getZoom() / 2`, and your `minZoom` and `maxZoom` in the view need to be multiplied by 2.

I have created an updated fiddle with these changes: http://jsfiddle.net/onrbek6j/.

**Comment by pjsg** [comment]
Thanks for this solution. It still isn't clear to me what is wrong with my original solution (except that it doesn't work). 

What do people believe that the + & - buttons are supposed to do? I can think of (at least options):

1 adjust the zoom by the specified amount (exactly). If the zoomDelta is 0.5 and the current zoom is 3.1, then pressing + would move to 3.6, and pressing minus would move to 2.6

2 adjust the zoom by the specified amount and then round to the nearest multiple of the adjustment amount. If the zoomDelta is 0.5 and the current zoom is 3.1, then pressing + would move to 3.5 and pressing - would move to 2.5

Also, pressing the + & - keys on the keyboard should behave the same as the buttons (assuming that they have the same zoomDelta).

If there is consensus on which of behaviors 1 or 2 is correct, then I could put up a PR to fix it. My personal feeling is that behavior 1 is correct. My rationale is that otherwise you can only end up with odd zoom numbers by using the drag-zoom option or a specific setZoom call.

[For the purposes of this ticket, it doesn't matter whether you think in zooms or resolutions]

**Comment by pjsg** [comment]
On further reading, the current behavior of the + & - buttons seems to be documented as part of the View documentation. In which case, the bug would appear to be that the drag-zoom and the continuous two-finger zoom on OSX are the bugs as they can end up with any zoom/resolution. Now, it is fairly obvious to me that implementing the snap behavior for the drag-zoom and the continuous two-finger zoom would be wrong (as it would be a terrible user experience), the documentation seems to demand it.

**Comment by ahocevar** [comment]
@pjsg Thanks for your investigations. Based on what we currently have, the desired behavior for the +/- buttons and keys would be option 2:

> 2 adjust the zoom by the specified amount and then round to the nearest multiple of the adjustment amount. If the zoomDelta is 0.5 and the current zoom is 3.1, then pressing + would move to 3.5 and pressing - would move to 2.5

If you could create a pull request, that would be great.

**Comment by pjsg** [comment]
I've also discovered that the `ol/interaction/MouseWheelZoom~MouseWheelZoom` always zooms by 1 increment per mousewheel click. This probably ought to be settable and probably ought to be set by `ol.interaction.defaults({zoomDelta: 0.5})`

**Comment by pjsg** [comment]
THinking some more about the two options -- the second option has the unfortunate effect of making the following two sequences have different effect:

1 Zoom by 1, Zoom by 1 (say from a mouse wheel)
2 Zoom by 2 (say from a faster mousewheel)

I suspect that the goal of the resolutionConstraint is to round the zoom to an integer value *when it makes sense*. Thus for a zoomDelta of 0.3, the resulting values ought to be

1.0, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3.0

Another approach would be to just round to integer if within half of the zoomDelta, otherwise not.

1, 1.3, 1.6, 2, 2.3, 2.6 3   going up

and

3, 2.7, 2.4, 2, 1.7, 1.4, 1 going down.

**Comment by ahocevar** [comment]
Thinking this through I would say you're right @pjsg - option 1 produces more predictable results.

**Comment by pjsg** [comment]
Seems to be the same as issue #6212.

Also, does anybody know what the `opt_direction` parameter is supposed to do? In *all* case that I can find, this is either omitted or set to 0. The docs aren't helpful either!

https://openlayers.org/en/latest/apidoc/module-ol_View-View.html#constrainResolution

**Comment by ahocevar** [comment]
The `opt_direction` option is passed to `ol/array/linearFindNearest` and is documented there: https://github.com/openlayers/openlayers/blob/b8c912560247271ef12eeeb41360c60385175e3b/src/ol/array.js#L65-L72

**Comment by Walleza1** [comment]
Hello, 
Sorry to dig this up, but i've met the same issue. I'm using zoom levels for another thing so the proposed solution about zoomFactor can't work for me. Did someone have another solution ? 

The [documentation]( https://openlayers.org/en/latest/apidoc/module-ol_interaction.html#.defaults) actually mentions :
> zoomDelta - number - Zoom level delta when using keyboard or mousewheel zoom.

But after taking look at the `ol/interaction.js`, we don't use zoomDelta in constructor : 

```javascript
 const mouseWheelZoom = options.mouseWheelZoom !== undefined ?
    options.mouseWheelZoom : true;
  if (mouseWheelZoom) {
    interactions.push(new MouseWheelZoom({
      condition: options.onFocusOnly ? focus : undefined,
      constrainResolution: options.constrainResolution,
      duration: options.zoomDuration
    }));
}
```
