### ISSUE TITLE
Openlayers 4: Manipulating image brightness

### ISSUE THREAD

**Issue by mghildiy** [openlayers/openlayers#8424]
Hi,

I am working on an application. Application renders image in browser. Openlayers 4 is used.

I want to add a functionality wherein user can act on a slider to vary image brightness.

Can it be done?

**Comment by fredj** [comment]
Hi, what about using a [CSS filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/brightness) to change the brightness?
The downside is that only the whole map can be changed, not individual layers

**Comment by ahocevar** [comment]
You can also use a Raster source or just a `postcompose` listener on the layer to change brightness. See e.g. https://openlayers.org/en/v4.6.5/examples/color-manipulation.html for inspiration.

**Comment by mghildiy** [comment]
Hi,

Thanks a lot for links above.
I followed the second one(http://openlayers.org/en/latest/examples/image-filter.html), and am able to make progress.

But I face an issue. Image brightness does change, but when I hover cursor on image or click the image, it returns back to its original brightness it had when image loaded.

What do I miss here?
As mentioned in code, my last piece of code(after changing the RGB values for all pixels):

`ctx.putImageData(output, 0, 0);`
 `this.map.render;`
