### ISSUE TITLE
Cancel old image source requests

### ISSUE THREAD

**Issue by josepgomes** [openlayers/openlayers#8425]
Hello,
I noticed that in the recent ol versions wms requests are managed differently. In the 2.10 version, if i zoom in and out, the previous wms requests are canceled.

![image](https://user-images.githubusercontent.com/3487504/43063731-909c545c-8e54-11e8-85e1-9286a6306287.png)

Nowadays, every single request is processed.

![image](https://user-images.githubusercontent.com/3487504/43063775-c0e3a1e2-8e54-11e8-8963-48fec34c8391.png)

This leads to a very low performance.

Is it possible to cancel a wms request when we already ask for another one?

Many Thanks!

**Comment by ahocevar** [comment]
OpenLayers now uses a TileQueue, which continues to load tiles until its tile cache is saturated. You can enforce that images are dropped when you configure the `source/TileWMS` with a small `cacheSize`, e.g.
```js
new TileWMSSource({
  cacheSize: 16,
  // ...
});
```

**Comment by josepgomes** [comment]
This is true for ImageWMS, too?

**Comment by ahocevar** [comment]
No, that's only the case for tiles. For ImageWMS, you could achieve that with a custom `imageLoadFunction` on the source, e.g.
```js
const blankSrc = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=';
let oldImg;
new ImageWMSSource({
  imageLoadFunction: function(image, src) {
    if (oldImg) {
      oldImg.src = blankSrc;
    }
    const img = image.getImage();
    img.addEventListener('load', function() {
      oldImg = undefined;
    });
    img.src = src;
  }
});
```

**Comment by josepgomes** [comment]
@ahocevar , i tested that solution, but the performance is still very bad, taking some times more than 5 seconds to completely load all the requests. This is because the browser will process all the "ok" status requests. Is there no way to abort requests like in ol2? Thanks for your time!

**Comment by josepgomes** [comment]
I tested the abort state, but for the browser is still a 200 status. It seems that there isn't anything that really cancels the request, right?

**Comment by josepgomes** [comment]
Can you tell me where is the request made? Did not found any xhr doing the request. Thanks.

**Comment by ahocevar** [comment]
It‘s just setting the src on the Image, no XHR. You‘d have to combine setting the ABORT state with the snippet I posted above.

**Comment by josepgomes** [comment]
My solution is this:

ol/source/image.js
```typescript
/**
* @private
* @type {HTMLImageElement}
*/
this.previousImageElement = new Image();

/////////////////////////////////////////////////////////////////////////////////

_ol_source_Image_.defaultImageLoadFunction = function(image, src) {
  this.previousImageElement.onload = () => {
    image.getImage().src = this.previousImageElement.src;
  };
  this.previousImageElement.src = src;
};
```

ol/source/imagewms.js
```typescript
this.image_ = new _ol_Image_(requestExtent, resolution, pixelRatio,
      url, this.crossOrigin_, this.getImageLoadFunction());

/////////////////////////////////////////////////////////////////////////////////

_ol_source_ImageWMS_.prototype.getImageLoadFunction = function() {
  return this.imageLoadFunction_.bind(this);
};
```

**Comment by josepgomes** [comment]
https://github.com/openlayers/openlayers/pull/8430

**Comment by ahocevar** [comment]
It looks like you need a combination of debouncing and aborting pending requests. You could try a custom `imageLoadFunction` like this:
```js
      imageLoadFunction: function(image, src) {
        if (timeout) {
          clearTimeout(timeout);
        }
        // debounces loading
        timeout = setTimeout(function() {
          if (previousImage && previousImage.state == 1) {
            // aborts previous image loading
            previousImage.getImage().src = 'data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22/%3E';
          }
          previousImage = image;
          image.getImage().src = src;
        }, 50);
      },

**Comment by ahocevar** [comment]
> Like i said, i will try to understand why this works.

Look here: 
https://github.com/openlayers/openlayers/pull/8430#pullrequestreview-140631871. The performance gain you're seeing is because of the debouncing, which is a result of your double loading. This should have the same effect:
```
imageLoadFunction: function(image, src) {
    this.timeout && clearTimeout(this.timeout);
    this.timeout = setTimeout(() => {
      image.getImage().src = src;
    });
}

**Comment by josepgomes** [comment]
I tested that solution, as you can see it doesn't cancel any request.

![image](https://user-images.githubusercontent.com/3487504/43255527-f87b2674-90c1-11e8-86d0-4b6883b391d1.png)

**Comment by josepgomes** [comment]
This is my code's result.

![image](https://user-images.githubusercontent.com/3487504/43255640-4c952ee4-90c2-11e8-8ff1-cdedecb6c48c.png)

**Comment by ahocevar** [comment]
You're cancelling only requests that are made by what you call `this.previousImageElement`, which is not used to display an image anywhere. You're loading every image into that element, and in addition into the image wrapper's image element.

**Comment by ahocevar** [comment]
Ok, I see now: your code does what you want it to do because the cache headers of your WMS allow the browser to cache the requests that were made by `this.previousImageElement`, so when they are loaded again by the image wrapper's image element, they are not refetched.

That said, your solution also works without your pull request (#8430), with this `imageLoadFunction`:
```js
imageLoadFunction: function(image, src) {
  this.previousImageElement = this.previousImageElement || new Image();
  this.previousImageElement.onload = () => {
    image.getImage().src = src;
  };
  this.previousImageElement.src = src;
},
```
So can we close this?

**Comment by josepgomes** [comment]
Yes, all fine by me.

**Comment by ahocevar** [comment]
Thanks @josepgomes, and sorry for the back and forth on this.
