### ISSUE TITLE
Add 'extent' to Graticule options

### ISSUE THREAD

**Issue by Benjaki2** [openlayers/openlayers#8427]
**Description**
It appears that the `ol/Graticule` inherits its extent from the map's projection extent. I am proposing to add an `extent` option (and `setExtent`/ `getExtent` methods) with the default continuing to be the projection extent.

**Reason for request**
I would like to apply layer-swipe like functionality to graticules.
https://openlayers.org/en/latest/examples/layer-swipe.html

**Comment by HerrCraziDev** [comment]
Would this allow repeating graticules along the X axis ?

**Comment by ahocevar** [comment]
@HerrCraziDev No, unfortunately not.

**Comment by HerrCraziDev** [comment]
@ahocevar It would be great to have a way to repeat them along the x axis. Is it possible to create several graticules and offset them so it looks like if there were only one, but wrapped ?
