### ISSUE TITLE
(bug) loadTilesWhileInteracting  flag doesn't work on raster layer

### ISSUE THREAD

**Issue by asafMasa** [openlayers/openlayers#8429]
* define map 
new OLMap({  loadTilesWhileInteracting: true, loadTilesWhileAnimating: true });
* set RasterLayer
const source = new OSM();
new ImageLayer({
			source: new Raster({
				sources: [source],
				operation: (pixels) => pixels[0],
				operationType: 'image'
			})
		})
* check for loadTilesWhileInteracting
expected: should work
actual: it doesn't

**Comment by ahocevar** [comment]
An image layer does not load tiles from its source, so there is no `loadTilesWhileInteracting` property. Maybe you were looking for a `postcompose` listener?
```js
const layer = new TileLayer({
  source: new OSM()
});
layer.on('postcompose', e => {
  const context = e.context;
  const canvas = context.canvas;
  const width = canvas.width;
  const height = canvas.height;
  const input = context.getImageData(0, 0, width, height).data;
  const output = context.createImageData(width, height);
  for (let pixelY = 0; pixelY < height; ++pixelY) {
    for (let pixelX = 0; pixelX < width; ++pixelX) {
      const index = (pixelY * width + pixelX) * 4;
      // Manipulate rgba of the pixel:
      output[index] = input[index]; // -> r
      output[index + 1] = input[index + 1]; // -> g
      output[index + 2] = input[index +2]; // -> b
      output[index + 3] = input[index +3]; // alpha
    }
  }
  context.putImageData(output, 0, 0);
});
```
This will be executed with every render frame.

**Comment by ahocevar** [comment]
You can do the same kind of color manipulation with the approach I outlined below. Just change the code inside the inner `for` loop to the one you find in the `color-manipulation` example, using `input[index]` and oputput[index]` for the pixel you're modifying, where `index .. index + 3` are the RGBA values of the pixel.

**Comment by yairtawil** [comment]
HI @ahocevar , 
I've got an error on this function `context.getImageData(...`

```
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
```

**Comment by ahocevar** [comment]
@yairtawil This is because you're requesting data from a server that does not send CORS headers, or because you're not setting the `crossOrigin` property in your tile layer source.

**Comment by yairtawil** [comment]
@ahocevar ,
I'm putting `crossOrigin: 'Anonymous'` or `crossOrigin: null` 
but still getting same error.. (`Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.`)
any idea ?

```javascript
const source = new XYZ({
	url: url,
	crossOrigin: 'Anonymous',
	projection: 'EPSG:3857'
});
```

**Comment by ahocevar** [comment]
Then it's probably that

> you're requesting data from a server that does not send CORS headers

You can find that out in the network pane of your dev console.

**Comment by ahocevar** [comment]
The `loadTilesWhileAnimating` and `loadTilesWhileInteracting` options have been removed.

**Comment by cascading-jox** [comment]
> The `loadTilesWhileAnimating` and `loadTilesWhileInteracting` options have been removed.

I just found myself looking for a way to do just what those options used to do, but in openlayers 7. Is there an alternative configuration available today that you can use for updating an image layer while panning?

**Comment by ahocevar** [comment]
Although not related, you can set the `ratio` option to `2`

**Comment by cascading-jox** [comment]
> Although not related, you can set the `ratio` option to `2`

I don't see a `ratio` option for any relevant classes that I use. My layer is a `ol/layer/Image` with a `ol/source/ImageStatic` source. My issue looks exactly like when you are panning in the [Image Reprojection demo](https://openlayers.org/en/latest/examples/reprojection-image.html).

**Comment by ahocevar** [comment]
The `ImageStatic` source does not have a `ratio` option indeed, but it could be added.

Note that the `loadTilesWhileAnimating` and `loadTilesWhileInteracting` options never had an effect on `Image` sources, because they are not tiled.

**Comment by cascading-jox** [comment]
> The `ImageStatic` source does not have a `ratio` option indeed, but it could be added.
> 
> Note that the `loadTilesWhileAnimating` and `loadTilesWhileInteracting` options never had an effect on `Image` sources, because they are not tiled.

Ah that makes sense. We are using static images a lot together with open layers, so it would be a very welcome addition to be able to update the layer while panning! Using `ratio` seems like an option. I'll look into how the `ratio` option is implemented.
