### ISSUE TITLE
Observable.on does not respect external context.

### ISSUE THREAD

**Issue by Vasiliy13** [openlayers/openlayers#8431]
Can you please provide the reason why you removed the `opt_this` argument?

https://github.com/openlayers/openlayers/commit/d7c48314b88b3dfd598265c220f0c40781d07bb5#diff-a3c20f84c3e2fa5a948c6c57621b4e49L100

**Comment by ahocevar** [comment]
TL;DR: There is no need for `opt_this`. Instead of
```js
myObject.on('change', function() {
  console.log(this.getProperties())
}, myObject);
```
you now say
```js
myObject.on('change', function() {
  console.log(this.getProperties())
}.bind(myObject));
```

**Comment by Vasiliy13** [comment]
Ok, thanks for response.
