### ISSUE TITLE
[FeatureRequest]: add ol.layer.Vector.setRenderMode('image' || 'vector')

### ISSUE THREAD

**Issue by dennisguse** [openlayers/openlayers#8436]
`ol.layer.Vector `allows to define the `renderMode` in the constructor.
However, the `renderMode` cannot be changed (or I overlooked something) after constructing a vector.

For performance reason, I would like to change the `renderMode` to `image` as sometimes (depending on the amount of features) the performance might be insufficient while in general `vector` works.
So, I would like to let the user change the `renderMode` depending on his needs _after_ loading the features.

_Working solutions:_
At the moment, the solution be to recreate the `vector` (including coping all other settings) and replace it in the layergroup.

_Desired solution:_
Adding `ol.layer.Vector.setRenderMode('image' || 'vector')`

_My workaround:_ creating new `ol.layer.Vector`, copying all (relevant) attributes, and set renderMode accordingly.

```
    var collectionLayers = this.getMap().getLayerGroup().getLayers();

    for(let i = 0; i < collectionLayers.getLength(); i++) {
        let layer = collectionLayers.item(i);

        if (layer instanceof ol.layer.Vector) {
            let layerNew = new ol.layer.Vector({
                source: layer.getSource(),
                style: layer.getStyle(),
                renderMode: this._shouldBeFast ? "image" : "vector" //TODO should use ol.layer.VectorRenderType
            });

            collectionLayers.setAt(i, layerNew);
        }
    }
```

**Comment by dennisguse** [comment]
From my understanding `ol.layer.Vector.getRenderMode()` is only called by `CanvasImageLayerRenderer` at https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/canvas/ImageLayer.js#L201

If I got it right, this check is only used when _constructing_ the `CanvasImageLayerRenderer`
https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/canvas/ImageLayer.js#L56

Therefore, changing the `ol.layer.Vector.renderMode` will not trigger a recreating the `CanvasImageLayerRenderer`, right?

@ahocevar 
How could I trigger the _re-evaluation_ of the `renderMode` after `CanvasImageLayerRenderer` got constructed?

**Comment by ahocevar** [comment]
@dennisguse When the vector layer has `renderMode: 'image'` set, it will use an image renderer. To notify the map renderer of the renderer change, it should be enough to call `this.changed()` on the layer, i.e. in the `setRenderMode` function.

**Comment by fredj** [comment]
@dennisguse can we close this issue?

**Comment by dennisguse** [comment]
@fredj Sure. For my use case, I implemented the described workaround.

**Comment by fredj** [comment]
Thanks @dennisguse !
