### ISSUE TITLE
'Uncaught Error' with WebGL Renderer

### ISSUE THREAD

**Issue by Jinkwon** [openlayers/openlayers#8438]
I tried to use webgl renderer with vector tile, but I couldn't initialize map engine at all.
Is it not supported spec?

![2018-07-26 10 15 32](https://user-images.githubusercontent.com/1798916/43235751-d8a91b44-90bc-11e8-9569-f37138a59252.png)

**Comment by tschaub** [comment]
The WebGL renderer does not support vector tile rendering.  Pull requests to update the documentation would be appreciated.
