### ISSUE TITLE
White screen of death on Mobile full screen example: "ReferenceError: Clipboard is not defined"

### ISSUE THREAD

**Issue by gerdneuman** [openlayers/openlayers#8440]
The [Mobile full screen example](http://openlayers.org/en/latest/examples/mobile-full-screen.html) fails with `ReferenceError: Clipboard is not defined` on both Firefox and Chrome:

![image](https://user-images.githubusercontent.com/12525563/43259329-0d03cd9e-90d6-11e8-938b-2ecfc3a2293b.png)

**Comment by fredj** [comment]
Thanks for the bug report, the [geolocation-orientation](http://openlayers.org/en/latest/examples/geolocation-orientation.html) example is also broken.

**Comment by ahocevar** [comment]
All examples that use the `example-verbatim.html` template are affected.

**Comment by fredj** [comment]
@ahocevar I'm preparing a fix

**Comment by ahocevar** [comment]
Thanks @fredj.
