### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by Skuriles** [openlayers/openlayers#8442]
The new API docs can not be used correctly.
A click on a item in left side navigation menu does refresh the whole page and shows the item link, before reload you can see that the submenu was opened, too.

=> Fix it that click on item opens submenu, because currently it is not possible to get to a submenu point directly.

Also the search seems to be broken, too. I can't search for "Fires" or can't find an overview about events.

And maybe there are some methods missing: Search for "addLayer" and you only get the PluggableMap Method "addLayer", but a addLayer on a normal map instance still works?!!!

So there are a lot of small issues, or did I miss something

**Comment by ahocevar** [comment]
Thanks for the report! We are in the process of reworking our JSDoc annotations (#8345). When done, we will also switch to a different doc generator. So these issues should be fixed for the next release.

**Comment by Skuriles** [comment]
Thanks for Quick response. I will wait for next release now!
