### ISSUE TITLE
When panning the map, every point is shaking too much

### ISSUE THREAD

**Issue by Jinkwon** [openlayers/openlayers#8444]
When panning the map, every point is shaking too much.
But circle and line string are fine though.
I'm curious why it is so different.

### Test url
http://openlayers.org/en/latest/examples/draw-features.html

### Example gif
![shaking](https://user-images.githubusercontent.com/1798916/43296966-70f8dbf6-9189-11e8-842f-f636f33b15c8.gif)

**Comment by Jinkwon** [comment]
@tschaub 
How can I use integer pixels? Could you give me some advice?
Shaking symbol issue should be resolved in my project.
But if not I need to fix origin source codes by my self. :(

**Comment by ahocevar** [comment]
@Jinkwon Configure the `Circle` style with `snapToPixel: false`, e.g.
```
new Circle({
  snapToPixel: false,
  radius: 10,
  // ...
});

**Comment by Jinkwon** [comment]
@ahocevar Thanks so much!! issue resolved. 👍

**Comment by Jinkwon** [comment]
@ahocevar Thanks for your effort! I read 5.2 version changelog about snapToPixel.
And also text does not shake again.
