### ISSUE TITLE
Get response code in tileloaderror

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#8445]
I have a `ol.layer.Tile` with a source of `ol.source.TileWMS` where I have a listener on tileloaderror.  My question is how can I get the response code / message from this function.  

What i do need to test for is: 
`Status Code: 400 Missing or Invalid token supplied`

My current code is:
```
baseLayer.getSource().on('tileloaderror', function (e) {
            progress.addLoaded();
});

```

**Comment by fredj** [comment]
It doesn't seems possible to get the details of an image load error.
[The error callback function](https://github.com/openlayers/openlayers/blob/v5.1.3/src/ol/ImageTile.js#L105) receives an `Event` as argument but without any details of the cause of the error.

**Comment by ahocevar** [comment]
You can configure your TileWMS source with a custom `tileLoadFunction` and send image requests with `fetch` or `XMLHttpRequest` instead of using the default behavior of setting the image's `src`. See 
https://github.com/openlayers/openlayers/issues/4213#issuecomment-145149625 for inspiration.

**Comment by umbe1987** [comment]
Say I have written my function (e.g. `imageLoadFunction` like the one suggested in [this SO answer](https://stackoverflow.com/a/29790150/1979665), which should handle exceptions that is what I need).
How would I use that?
Given that `img` is a (e.g.) `ol.layer.Image` object, should I do something like:

`img.source.setImageLoadFunction(imageLoadFunction(img, img.source))`
?

**Comment by ahocevar** [comment]
Documentation updated with #8470.
