### ISSUE TITLE
KML Parser feedback

### ISSUE THREAD

**Issue by Skuriles** [openlayers/openlayers#8446]
Hello all,
I've already tried to ask on SO, but there are no answers so far.
https://stackoverflow.com/questions/51520423/openlayers-add-kml-layer-no-error-feedback

Problem: If you import corrupt KML files (or KML files with not supported features in OL) you don't get any feedback from the "addLayer" method. The layer will be added anyway. 
The only thing I can check after the layer has been added is if the extent isFinite or not. This check can't be done while loading as the postcompose event is fired multiple times (and every new layer has extent infinite at start, so this is no reliable check). 

Is there any chance to get some feedback or some kind of error event to check if a KML filed could be loaded completely? Or this just not implemented?

**Comment by mrmister91** [comment]
Does anyone have an answer to this yet? I am also interested.

Also, your question was deleted from stackoverflow.
