### ISSUE TITLE
DragBox Interaction not selecting projected features.

### ISSUE THREAD

**Issue by hazelnutmonkey** [openlayers/openlayers#8457]
Using the DragBox example here: https://openlayers.org/en/latest/examples/box-selection.html

When I use the DragBox to do a select of a feature (for example, the United States), it correctly grabs the feature and also all of the projected features (when infinite panning right or left).

However, when panning to the right or left and using the DragBox to select a projected feature, it will not select any features.

**Comment by ahocevar** [comment]
This is not an issue with the DragBox interaction itself, but with the example code of the `box-selection.html` example. The `boxend` handler could handle that if changed to
```js
dragBox.on('boxend', function() {
  // features that intersect the box are added to the collection of
  // selected features
  const extent = dragBox.getGeometry().getExtent();
  const projWidth = getWidth(map.getView().getProjection().getExtent());
  const worldsAway = Math.round(extent[0] / projWidth);
  extent[0] = extent[0] - worldsAway * projWidth;
  extent[2] = extent[2] - worldsAway * projWidth;
  vectorSource.forEachFeatureIntersectingExtent(extent, function(feature) {
    selectedFeatures.push(feature);
  });
});
```

**Comment by hazelnutmonkey** [comment]
Thank you for your response. I tested your code and it does indeed work. 

I'm not sure if this issue should be closed now or if the example code should be updated to reflect your more correct way of using the DragBox interaction.

**Comment by raulromano** [comment]
Hi, Everyone.
I still have the same problem. Through the API methods, provided in the documentation, I can't identify which coordinates (latitude and longitude) are selected in the dragbox.
Can someone help me?
