### ISSUE TITLE
How to get layer name from getFeaturesAtPixel?

### ISSUE THREAD

**Issue by daudihusbands** [openlayers/openlayers#8460]
using version 5. how do I get layer name?
I've tried this:
`    const features = this.map.getFeaturesAtPixel(evt.pixel, {

      layerFilter: ((layerCandidate: layer.Layer) => {

        if (layerCandidate.get('name') === 'my layer') {

          return true;

        }

        return false;

      }

      )});`

Thanks for your help

**Comment by simonseyock** [comment]
The layer name is no openlayer specific property. It depends on how the layer name has been set. Questions like this are better suited for stackoverflow (use the tag `openlayers`).

**Comment by daudihusbands** [comment]
Thanks. I figured it. Silly mistake. I needed to first call layer.set('name', 'something') before I could call layer.get('name').
