### ISSUE TITLE
Assert in Feature.createStyleFunction

### ISSUE THREAD

**Issue by cabesuon** [openlayers/openlayers#8462]
There is an assert on the _Feature_ function _createStyleFunction_, line 291.
I am using Ionic. This is the module import,
`import Style from 'ol/style/style';`
and this is the invocation,
 ```
const circle = new Circle({
      radius: 6,
      fill: new Fill({
        color: '#3399CC'
      }),
      stroke: new Stroke({
        color: '#fff',
        width: 2
      })
    });
    const style = new Style({
      image: circle
    })
    this.positionFeature.setStyle([style]);
```
If I use style as the parameter to the function, the assert condition fails that's why I pass a one element array and it works.
I am not sure why it fails because `style instanceof Style` should be true. Maybe is something with the import, that's the only difference with the examples.

Regards,
Manuel

**Comment by ahocevar** [comment]
Looks like a version mismatch of `ol`, probably caused by using dependencies that require different versions of `ol`.

What is the output of `npm ls ol`?

**Comment by cabesuon** [comment]
The output is -> ``-- @ol5.1.3`

You are right, It was my mistake on the import, with `import Style from 'ol/style/Style` it works.

The weird thing is that I actually check `style instanceof Style` in my code with `import Style from 'ol/style/style'`  before calling the function and it was `true`

One last thing, the url in the assert message it was not working.

Anyways, thank you very much.

Regards,
Manuel
