### ISSUE TITLE
map.getLayer(layerName) is not present in the API

### ISSUE THREAD

**Issue by AhammadAliPK** [openlayers/openlayers#8468]

**Comment by AhammadAliPK** [comment]
looking for a method from a map class to get a layer by its layername , we have map.getLayers . but each time we need iterate over all added layers on the map in order to get a single layer

**Comment by ahocevar** [comment]
`layerName` is not a property in OpenLayers. However, if you set a name on a layer with `layer.set('name', 'layerName'), you'll be able to find that later with e.g.
```js
map.getLayers().getArray().find(layer => layer.get('name') == `layerName`);
```

**Comment by AhammadAliPK** [comment]
yes you are right , 
Thanks much . 
I'm doing that . but I'm bit curious to know whether you guys want to make it that way , as making layerName as property and then create a method to get layer name without traversing all the layers ?

**Comment by ahocevar** [comment]
Internally, we would still traverse the layer. So no, we're not considering your suggested change.

**Comment by AhammadAliPK** [comment]
okay
