### ISSUE TITLE
Unable use openlayer library with angular 5 as it require type def and that is not present with latest npm package

### ISSUE THREAD

**Issue by PrasadBhalekar** [openlayers/openlayers#8472]
![image](https://user-images.githubusercontent.com/4089583/43518333-6460fc42-95a9-11e8-8477-1cfca66edcf9.png)

**Comment by Diaaz** [comment]
We are having the same problem using openlayers 5 using the NPM ol package with Angular 6 and typings from definitely typed @types/ol. Workaround is reverting to Openlayers 4.6 using the NPM openlayers package and @types/openlayers.

**Comment by PrasadBhalekar** [comment]
Thanks
Let us know when we will get new @types def for open layer version 5

**Comment by OSHistory** [comment]
The @types/ol package was basically a wrapper around the @types/openlayers. Since 
version 5.0.0 only the ol package is supported. There are plans to publish the typings 
directly with the ol package. See: 

https://github.com/openlayers/openlayers/issues/8448

**Comment by fredj** [comment]
See #9178
