### ISSUE TITLE
Clipping effect when panning the map with "renderMode: 'image'"

### ISSUE THREAD

**Issue by benVigie** [openlayers/openlayers#8473]
Hi guys,

I have to render a lot of features in my map, so I'm playing with `renderMode` to optimize the drawing time. So far so good, I'm able to display a huge bunch of items by using `renderMode: 'image'` option on my `VectorLayer`.

The downside is the image rendering just draw the viewport area, and if you move over the map there is a clipping effect due to the redrawing delay. Even if I'm using the `renderBuffer` option (which works perfectly with vector drawing btw), the painted area is still the map dom size.

I made a fiddle to see the difference between the 2 render mode. You can easily switch render mode, pan the map and see the clipping effect on image rendering: https://jsfiddle.net/27uLjg9o/111/ 

[The documentation](http://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html) doesn't mention a specific behaviour when using `renderBuffer` with `renderMode: 'image'`. So do I miss something ?

**Comment by ahocevar** [comment]
The `renderBuffer` option has nothing to do with the rendered map size, it is only about the extent for querying features from the source. Other image layer types (e.g. `ol/layer/ImageWMS`) have a `ratio` config option. If someone wants to implement that for `ol/layer/Vector` in `image` mode, a pull request would be appreciated.

**Comment by benVigie** [comment]
Thanks for your response @ahocevar !

It's definitely something we want to implement, we will be happy to contribute 😃.
But I'm still not sure to understand what the `renderBuffer` option do. If I modify my fiddle to add a third layer (vector rendering with `renderBuffer` off), we can see that the area around the rendered map are not painted if you pan.

Updated fiddle: https://jsfiddle.net/27uLjg9o/133/

Features are requested rightly, but all hidden part of the circle will not be rendered, whereas the vector layer with `renderBuffer` will paint the extended zone. If we modify the `image` renderer, can't we use the same `renderBuffer` to extend the painted zone ?

**Comment by ahocevar** [comment]
`renderBuffer` is the option you use to account for styles such as large circles or thick lines, to make sure that there are no features missing at the edges of the viewport.

The difference in rendering is as follows: For vector rendering, the canvas `clip()` function is applied to the extent extended by the `renderBuffer`. This way, all features that were queried from the source are correctly rendered within the map viewport, and may be cut off outside the map viewport. For image rendering, an image is generated for the exact extent of the map viewport. Image rendering of vector layers uses the image renderer, which has no concept of a `renderBuffer`.

**Comment by sky93** [comment]
From what version we can use this?
