### ISSUE TITLE
fonts with spaces are not parsed correctly

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#8474]
i had some trouble with the new fontawesome in openlayers.

I could render it on a canvas (see this jsfiddle: https://jsfiddle.net/zp25vg7n/20/) but not with openlayers.

After some debugging i figured out it was because of this line in css.js:
cache[font] = family.split(/,\s?/);

of fonts contain spaces the regex (the '\s') doesn't match the entire font family
with fontawesome 5 the font is (unfortunatly) "Font Awesome 5 Free" (they didn't think that through)
But is is correct. Font names can contain spaces. 

So can that be changed into something more flexible?
see:
https://stackoverflow.com/questions/4031900/split-a-string-by-whitespace-keeping-quoted-segments-allowing-escaped-quotes

**Comment by BasieP** [comment]
oké..

not telling truth here... works accually pretty nice...
problem is that i draw the marker before the fonts are loaded.

Because of the caching of fonts in the css.js file when i redraw the marker the next time... it still doesn't draw well..
so i have to do some magic to make sure my fonts are loaded before i draw that marker...

anyone got suggestions?

**Comment by ahocevar** [comment]
Try rendering the symbols using `ol/style/Text` instead of `ol/style/Icon`. That way, OpenLayers will ensure that the text is rendered after the font is loaded.

**Comment by BasieP** [comment]
well unfortunatly that doesn't work...
see this fiddle: https://jsfiddle.net/zp25vg7n/65

The first time you load it it runs directly, and it fails (you see a square block instead of the fontawesome char)

when you run it again (or add a setTimeout to the script) it does work..

ctrl-f5 again and it's broken again

**Comment by ahocevar** [comment]
You found a bug, which only reveals itself for fonts that are available for a specific weight range only. See #8474 for a fix, which will make `ol/style/Text` styles work.
