### ISSUE TITLE
Map Graticule not working properly

### ISSUE THREAD

**Issue by msp166** [openlayers/openlayers#8479]
Hello everyone,

I stumbled upon an issue as I was viewing the example for adding a Graticule to the map. There is an issue in the GetMerdianPoint function which is causing things to break.

Example: http://openlayers.org/en/latest/examples/graticule.html

**Comment by msp166** [comment]
It looks like the code being served for Graticule.js is outdated. 

In webinspector the line throwing the error is: point = this.meridiansLabels_[index];
However, the code in master at line 367 shows: point = this.meridiansLabels_[index].geom;

**Comment by geocodezip** [comment]
It is this issue:
https://github.com/openlayers/openlayers/issues/8434

the distribution file hasn't been updated since that fix

**Comment by ahocevar** [comment]
Since this was a regression, we will create a bug fix release.

**Comment by geocodezip** [comment]
Is the schedule for bug fix releases documented somewhere?  When might there be one?

**Comment by michaelletzgus** [comment]
For my application I fixed ol.js from the 5.1.3 release "manually", you only have to insert a ".geom" two times in line 1... ;)
