### ISSUE TITLE
Conflict between pinchzoom and a simple tab event in draw mode

### ISSUE THREAD

**Issue by fouzi-bentounsi** [openlayers/openlayers#8488]
I noticed a problem on phone and tablet, there is a confusion between the end of pinchzoom, it draws a new point as if there was a touchdown, it is possible to notice this at this example http://openlayers.org/en/latest/examples/draw-features.html in case of a polygon.

**Comment by ahocevar** [comment]
While not a huge problem, I agree that this is visually disturbing.

Probably the Draw interaction should not render a cursor circle on movestart. Is anyone willing and able to provide a pull request?
