### ISSUE TITLE
Map scaling

### ISSUE THREAD

**Issue by smolenski-mikolaj** [openlayers/openlayers#8494]
Hi there,

I wonder if there is a way to scale map wrapper or even .map element itself in order to achieve map which shows a larger amount of layers and other data. I am able to scale map wrapper and it looks ok, but then the problem are pointer events which are not working properly. 

I really enjoy openlayers, it is great library for making really complex map apps!

**Comment by TDesjardins** [comment]
@smolenski-mikolaj Have you tried method/function updateSize() on map object after rescaling?

**Comment by TDesjardins** [comment]
@smolenski-mikolaj Could this be closed?

**Comment by smolenski-mikolaj** [comment]
It could be closed. I haven't found the answer, but it not needed anymore. Thanks for Your help!

**Comment by TDesjardins** [comment]
@smolenski-mikolaj Would be good to know if you tried to use method/function `updateSize()` !?
