### ISSUE TITLE
examples not working

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#8496]
none of the examples are working in latest of chrome or firefox.

The site does, but the code on the side (the one supposed to be copy and pasteable) is not.

when i copy/paste the code to a local .html file i get errors about the import statements.
Also when i read the file, i can't find any reference to a .js file containing the javascript file containing openlayers.

Since import/export only works on modules and the examples are not modules.
Perhaps it's good to simply use the pre-compiled version of openlayers and the 'old' way of pointing to objects (using the ol.x.x notation (namespaces))

If there is a need to show people how to use openlayers in their own NPM modules, please provide a decent example..

**Comment by sookoll** [comment]
There isn't any precompiled openlayers anymore. They (who?) decided, that everybody uses some complex build and packaging tools also for simple web page with map, so they trash all that work out of the box and provide only es6 modules. It will take years until es6 is fully implemented in most browsers, but they (who?) don't care about what community expect. In my opinion, it is too early to not to provide prebuild es5 build.

**Comment by BasieP** [comment]
oke i thought i was good at ranting....

read this sookoll
https://openlayers.org/download/

**Comment by ahocevar** [comment]
`color-manipulation.html` example fixed with #8420.
