### ISSUE TITLE
ol5: render changes features positions

### ISSUE THREAD

**Issue by jkopponen** [openlayers/openlayers#8498]
Hi,
We changed openlayers version from 4.6.5 to 5.1.3.
We noticed that when first time map is rendered (with 5.1.3 version) the view looks exactly same than with old version (4.6.5) of openlayers. But when map is rendered again some features moves little bit on the screen. I made some debugging and look source code and I found the reason:
In PluggableMap.renderFrame function in version 4.6.5 there is:
```
    viewState = view.getState();
    var center = viewState.center;
    var pixelResolution = viewState.resolution / this.pixelRatio_;
    center[0] = Math.round(center[0] / pixelResolution) * pixelResolution;
    center[1] = Math.round(center[1] / pixelResolution) * pixelResolution;
```
and in 5.1.3
```
      viewState = view.getState();
      let focus = this.focus_;
      if (!focus) {
        focus = viewState.center;
        const pixelResolution = viewState.resolution / this.pixelRatio_;
        focus[0] = Math.round(focus[0] / pixelResolution) * pixelResolution;
        focus[1] = Math.round(focus[1] / pixelResolution) * pixelResolution;
      }
```
So in 4.6.5 version, rounding of 'center' is done always but in 5.1.3 version only on first time.

**Comment by ahocevar** [comment]
Thanks for reporting this. #7871 indeed introduced a regression here.
