### ISSUE TITLE
ol/sphere.js gives warnings

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#8502]
When compiling with webpack i get this warning:
"There are multiple modules with names that only differ in casing." for the sphere.js.

I know it's not a big deal (since javascript is case insensitive) but it would be more readable if the modules indeed have different names

**Comment by ahocevar** [comment]
Maybe you have leftovers from a 4.x version of ol somewhere in your project? OpenLayers 5.x does not have a `Sphere.js` file anywhere.

**Comment by BasieP** [comment]
this one i mean:
https://github.com/openlayers/openlayers/blob/master/src/ol/sphere.js

**Comment by ahocevar** [comment]
Yes, all lowercase. So where does the ambiguity in your app come from?

**Comment by BasieP** [comment]
yaehexcuse me..

I referenced 'ol/Sphere.js' which works nice on windows... but throws the warning..
The warning message made me think the fault lay inside the acual file.
