### ISSUE TITLE
Do not place polygon vector labels in holes

### ISSUE THREAD

**Issue by jakubbican** [openlayers/openlayers#8508]
If a vector label is placed on top of a polygon with hole (donut polygon), the label may appear inside the hole. This is quite confusing as the label is not describing the outer polygon but something inside.

See the sample of parcel with hole with another parcel.

![image](https://user-images.githubusercontent.com/8542644/44015790-a227c59c-9ed2-11e8-8b05-4eec297d3bc8.png)

**Comment by ahocevar** [comment]
How are you labelling the polygon? Because the `ol/geom/Polygon`'s `getInteriorPoint` method does make sure labels are not placed in holes. See https://github.com/openlayers/openlayers/blob/33ef64c9120ad7ba3ce26951356c2e1bbbc360c9/test/spec/ol/geom/polygon.test.js#L552-L562.

**Comment by jakubbican** [comment]
Sorry, you're right! We did another test and it seems ok:
![image](https://user-images.githubusercontent.com/8542644/44076702-6d16be92-9fa1-11e8-9d77-331b280a0e1f.png)

Sorry for this. We have to doublecheck our code and find what's wrong.
