### ISSUE TITLE
Draw Shapes - Star

### ISSUE THREAD

**Issue by RenoSun** [openlayers/openlayers#8512]
Hi dear OpenLayers developers,

The user is not able to draw a **star** using Draw Shapes example. However, I have not problems drawing other shapes.

https://openlayers.org/en/latest/examples/draw-shapes.html?q=draw

Thanks!

**Comment by ChouGary** [comment]
https://openlayers.org/en/v5.0.3/examples/draw-shapes.html?q=draw
in v5.0.3 is ok

5.1.0 release note 
> Geometry constructor and setCoordinates no longer accept null coordinates
![image](https://user-images.githubusercontent.com/8294943/44073522-e7b1a962-9fc6-11e8-8f37-972bfa68ac17.png)
![image](https://user-images.githubusercontent.com/8294943/44073614-4a4aaa92-9fc7-11e8-9071-44832d7d9f63.png)

geometry = new Polygon(null);
=>geometry = new Polygon([]);

**Comment by fredj** [comment]
This issue was fixed with #8483
