### ISSUE TITLE
Efficiently rendering hundreds of unique vector map features

### ISSUE THREAD

**Issue by xenethyl** [openlayers/openlayers#8514]
I'm working on an application that needs to render hundreds of unique vector map features on ol.layer.Vector layers with renderMode set to "image" on a canvas-based map. Each feature has three things that make it unique:

1. Icon
2. Associated polygonal geometry
3. Textual label

Of the three things, the icon that's used tends to be reused between features. So, although I'm putting hundreds of features on the map there may only be a dozen unique icons in use.

The second and third things, though, will be unique for each feature that gets drawn.

With my current implementation I'm creating a new ol.style.Style object for each feature (because each one has a unique appearance), but my performance is quite bad (in the single digits for FPS). I've commented that logic out from my application and instead rendered everything using a single layer-defined ol.style.Style and my performance is perfect (~60 FPS), but unfortunately I can't move forward with that approach because the features are no longer drawn uniquely.

Am I missing something that would alleviate this issue and give me good performance with so many unique features?

**Comment by ahocevar** [comment]
It's a good idea to cache entire icon styles. Usually you can use the icon file name as cache key.

For associated polygons and labels, you can use the `style.setGeometry()` and `getText().setText()` methods of `ol/style/Style`.

**Comment by xenethyl** [comment]
Thanks @ahocevar. I'm still going to end up with a unique ol.style.Style object for each feature, though, aren't I? Each feature needs to be labelled uniquely with unique geometry, so I can't reuse styles across my features. I can reuse ol.style.Icon instances where the icons are reused, and maybe ol.style.Text instances if a label is reused, but I still need to create unique parent ol.style.Style objects to house the reused style parameter objects, which I think will continue to result in poor performance. Right?

**Comment by ahocevar** [comment]
You can change the label text by using `ol/style/Text`'s `setText()` method, so you can do something like
```js
import {Style, Text} from 'ol/style'; 
const style = new Style({
  text: new Text({
    text: ''
  })
});
vectorSource.setStyle(function(feature) {
  style.getText().setText(feature.get('text');
  return style;
});

**Comment by xenethyl** [comment]
Ah, I see. Thanks for the example. Let me refactor some things and give this a try.

I was under the impression that the performance increase I saw by making each feature render identically was due to the underlying replay for the style being identical (i.e. it was the same cached canvas) and thus there was less rendering overhead being incurred.

Could you briefly explain the rendering pipeline for image-based vector map features? When I create an ol.Feature object and assign an ol.style.Style object as its style, is that computed/rendered once and saved off as an in-memory canvas to be replayed whenever the map needs to repaint? It would seem that if I go the route of a style function on the parent layer that every time the map needs to repaint I'm going to be re-generating that underlying (potentially cached?) replay canvas, which would result in lesser performance.

**Comment by ahocevar** [comment]
In `image` render mode, a new replay is created when a new image is requested (i.e. after an interaction or animation where zoom, center or rotation of the view changed). In `vector` mode, a new replay is created when the resolution or center has changed, but not during map interaction and animation. The style function is called for each feature upon replay creation.

It is always better to use a layer style function instead of storing a `style` on the feature, because feature styles can use up a fair amount of memory.

With only a few hundred features, you should be able to get 60fps even with `renderMode: 'vector'`. If you get lower FPS, then there is potential for improvement by changing style management. Only if your feature count goes into the 10000s, then you might be better of with `renderMode: 'image'`.

**Comment by xenethyl** [comment]
Thanks again @ahocevar. This discussion has been really helpful.

After refactoring things to use a style function instead of generating a style for each feature I found that my performance was the same. Digging a bit deeper, I found that it had to do with empty layers. Take a look at these examples:

1. Plain map: https://jsfiddle.net/m1eak069/
2. Map with 10 empty layers: https://jsfiddle.net/twj4gp93/
3. Map with 10 layers, each with one point: https://jsfiddle.net/L4m9n6f7/

If you click and drag the map around in example 1 or 3 you'll notice a smooth 60 FPS frame rate. Clicking and dragging the map around in example 2 results in a very choppy 15-20 FPS. The issue seems to be a bit worse the larger the map is, so you may want to expand the size of the bottom right viewport in JSFiddle.

Am I doing something wrong here, or are we looking at a bug?

**Comment by ahocevar** [comment]
You should not be using `renderMode: 'image'`. In that mode, OpenLayers creates a canvas with the full viewport size for each layer, and composes those into a single target map image. That is a very expensive operation. Just remove the `renderMode: 'image'` configuration, and you'll be fine.

Note: `renderMode: 'image'` is only useful for single layers with 10000s of features.

**Comment by xenethyl** [comment]
I understand what you're saying, but there shouldn't be any reason that a set of 10 empty layers would result in far worse performance than 10 layers with one feature each. The 10 empty layers should be no-ops as far as rendering is concerned.

The only way I could see this happening is if the canvas created for layers with data on them is restricted to the extent of the data while an empty layer creates a canvas of the full viewport size.

I do have a desire to support layers with 10,000+ features, so `renderMode: 'image'` is important to me.

It still seems like something is wrong here...

**Comment by ahocevar** [comment]
If you can make rendering of 0 features a no-op, we’d appreciate a pull request.

Note that rendering 10 image or tile layers on top of each other is never a good idea though, for the reasons mentioned above.

**Comment by xenethyl** [comment]
Thanks again @ahocevar, and sorry if any of this comes across as argumentative. I'm just trying to understand the most-performant way to use OL for my use case.

My app displays data from about a dozen categories that update over time. As a result, I'm constantly adding/removing features from the sources associated with each category. I originally architected this to use one layer for each category, but based on what we're discussing here it sounds like I'd get better performance if I instead used a single layer and a single source.

Feature count is also really important to me, because the data sets I'm displaying can sometimes be very large (thousands per category). Thus, I'd like to develop using `renderMode: 'image'` to give me extra performance bandwidth to work with.

I removed `renderMode: 'image'` from my vector layer creation and my framerate was far more consistent (though still low), but interactions ended up being more laggy so the user experience is still not great.

To maybe frame my question better, if you had to display 10 categories of data each with 2,000 data points that changed over time (i.e. every few seconds you had to remove features from a layer and add new ones to it), are there any tricks or must-dos that would help? Should I expect to achieve a high frame rate with that amount of data and updating?

**Comment by ahocevar** [comment]
20000 features will render best in a single layer with `renderMode: 'image'`. Addition and removal of features is best achieved by using `ol/layer/Vector`'s `setSource() method, otherwise you are sacrificing performance with spatial index updates.

If interactions like highlighting are needed, I would recommend to use an additional highlight layer, and not change the style of the main layer for highlighting.

**Comment by xenethyl** [comment]
Excellent, that's exactly the type of insight I was looking for. Thanks so much.

Could you explain how I should be using `setSource()` to add/remove features? When I update the map and remove 500 features and add 1000 to it, you're suggesting that I not call `addFeature()` and `removeFeature()` on the source and instead build a new source with all the features I want rendered (including ones that remain untouched)?

**Comment by ahocevar** [comment]
Yes, that's exactly what I would suggest. Create a new source with
```js
layer.setSource(new Source({
  features: allFeatures
}));
```

**Comment by xenethyl** [comment]
Interesting. I would have expected to incur a greater overhead by generating a new source each time rather than updating an existing one. I'll give that a shot.

**Comment by jgalrito** [comment]
> If interactions like highlighting are needed, I would recommend to use an additional highlight layer, and not change the style of the main layer for highlighting.

@ahocevar I'm trying to optimize applying a different style to hovered features (since my main vector layer has ~10000 features) so I tried using this technique, but it seems adding/removing features to this highlight layer still forces the rest of the map to rerender. Might I be missing something or is this normal behaviour? Is there no "layer frame" cached that prevents having to redraw layers that haven't changed?

**Comment by ahocevar** [comment]
@jgalrito Vector layers that did not change (i.e. in my suggestion above the original layer) only replay cached render instructions. Whereas layers that changed (i.e. in my suggestion the highlight layer) have to create a new set of render instructions.

**Comment by gunner963** [comment]
Hi, so I am using a single style function for my layer , but in my case data is coming at a rate of 5Hz, new Geom, new Rotation 5 times a second,
and also Icon changes with zoom I have 2 possibilities for it and 1 default .
so my machine should always be in the center so I am adding it for the very 1st time bu below code ,   
 
```
const feature = new Feature({ geometry: new Point([0, 0]) })
    feature.set('zoomLevel', this.zoomLevel)
    feature.setId(0)
    feature.set('name', this.mainVehicleName)
    feature.set('icon', this.getIconType(this.zoomLevel))
    **this.vehicleFeature= feature // cached stored as class variable**
    const source = new VectorSource({
      features: [feature],
      wrapX: false
    })

    this.vehicleLayer= new VectorLayer({
      source,
      zIndex: 10,
      style: styleFunction
    })

    this.olMap.addLayer(this.vehicleLayer)
```

and my style function is 
```
const vehicleStyle= {}

export const styleFunction= (feature, resolution) => {
  const icon = feature.get('icon')
  if (!icon) {
    return null
  } else if (icon === 'type1') {
    if (!vehicleStyle['type1']) {
      vehicleStyle['type1'] = new Style({
        image: new Icon({
          src: '../../assets/icon/type1.svg',
          rotation: 0,
          scale: feature.get('zoomLevel') / 7

        }),
        text: new Text({
          offsetY: 22,
          text: feature.get('name'),
          font: '20px roboto condensed',
          fill: new Fill({
            color: 'white'
          })
        })
      })
    }
    return vehicleStyle['type1']
  } else if (icon === 'type2') {
    if (!vehicleStyle['type2']) {
      vehicleStyle['type2'] = new Style({
        image: new Icon({
          src: '../../assets/img/type2.svg',
          rotation: Math.PI / 2, (as icon is 90 degrees flipped here)
          scale: feature.get('zoomLevel') / 20

        }),
        text: new Text({
          offsetY: 22,
          text: feature.get('name'),
          font: '20px roboto condensed',
          fill: new Fill({
            color: 'white'
          })
        })
      })
    }
    return vehicleStyle['type2']
  } else {
    if (!vehicleStyle['default']) {
      vehicleStyle['default'] = new Style({
        image: new Icon({
          src: '../../assets/img/type2.svg',
          rotation: 0,
          scale: feature.get('zoomLevel') / 7

        }),
        text: new Text({
          offsetY: 22,
          text: feature.get('name'),
          font: '20px roboto condensed',
          fill: new Fill({
            color: 'white'
          })
        })
      })
    }
    return vehicleStyle['default']
  }
}
```
and myUpdateFunction which gets called 5 times a second is
```
  private handleMotionOfVehicle(newState: Machine) {
// vehicleFeature cached when added for the 1st time in **bold** text above
    this.vehicleFeature.set('zoomLevel', this.zoomLevel)
    this.vehicleFeature.set('name', newState.name ? newState.name : 'vehicle1')
    this.vehicleFeature.set('icon', this.iconType(this.zoom))
    this.vehicleFeature.setGeometry(new Point([newState.position.X, newState.position.Y]))
    const newRotation= (newState.position.rotation- (Math.PI / 2))
    if (newRotation!== this.previousRotation) {
      this.previousRotation= newRotation
      this.olMap.getView().setRotation(newRotation)
    }
    this.olMap.getView().setCenter(new Point([newState.position.X, newState.position.Y])).getCoordinates())
  }
```
now when I zoom in and out map and all the objects start jerking 
the whole map jerks kind of toe and fro movement for this particular feature and all others behave the same , I am not using animation...
Please help if I am doing anything wrong 
Thanks

**Comment by k7moorthi** [comment]
> Yes, that's exactly what I would suggest. Create a new source with
> 
> ```js
> layer.setSource(new Source({
>   features: allFeatures
> }));
> ```

Can't we use `addFeatures()` instead of `setSource()`?

I mean pushing features into an array and use `addFeatures()` along with source`.clear()` for clearing the source.

Which one you would recommend for better performance? `addFeatures()` with `clear()` or `setSource()`?

**Comment by ahocevar** [comment]
These two should be equivalent:
```js
const source = layer.getSource();
source.clear(true);
source.addFeatures(allFeatures);
```
and
```js
layer.setSource({
  features: allFeatures
});
Note the that the first example calls `clear(true)`. The `true` argument means that any event notifications (which make the process slow) are skipped.

**Comment by k7moorthi** [comment]
@ahocevar 

> You should not be using `renderMode: 'image'`. In that mode, OpenLayers creates a canvas with the full viewport size for each layer, and composes those into a single target map image. That is a very expensive operation. Just remove the `renderMode: 'image'` configuration for all layers, and you'll be fine.
> 
> Note: `renderMode: 'image'` is only useful for single layers with 10000s of features.

If those 10k features are points then instead of using 10k features with point geometry, if I use one feature with multi point geometry (which consists of 10k coordinates), will it boost the performance?

**Comment by ahocevar** [comment]
@k7moorthi It will improve performance, but not in the rendering phase. Less features means faster loading and parsing.

**Comment by k7moorthi** [comment]
@ahocevar I can see that a custom wrapper on top op `rbush` is written in Openlayers and used internally but I can't find it on Openlayers API Docs (I assume that it is not exposed publicly). Is my assumption true? or is there a way to access it?

By the way thank you so much for your help that you have done so far 👍

**Comment by ahocevar** [comment]
Your assumption is correct @k7moorthi

**Comment by k7moorthi** [comment]
> @ahocevar
> 
> > You should not be using `renderMode: 'image'`. In that mode, OpenLayers creates a canvas with the full viewport size for each layer, and composes those into a single target map image. That is a very expensive operation. Just remove the `renderMode: 'image'` configuration for all layers, and you'll be fine.
> > Note: `renderMode: 'image'` is only useful for single layers with 10000s of features.
> 
> If those 10k features are points then instead of using 10k features with point geometry, if I use one feature with multi point geometry (which consists of 10k coordinates), will it boost the performance?

For this same scenario, if I use a single feature with 10k geometries in it, will it give the same kind of performance as mentioned in your below answer:

> @k7moorthi It will improve performance, but not in the rendering phase. Less features means faster loading and parsing.

**Comment by hajjimurad** [comment]
> @jgalrito Vector layers that did not change (i.e. in my suggestion above the original layer) only execute cached render instructions. Whereas layers that changed (i.e. in my suggestion the highlight layer) have to create a new set of render instructions, which involves evaluating style functions etc.

I have also issues with the performance of drawing on the vector layer with hundreds of polygons (or a dozen of polygons with thousands of points)

1. As I see `renderMode` is not longer supported for the VectorLayer. Is the any alternative for `renderMode` in the latest version? 
2. The idea I had in mind is to draw a new polygon on the additional vector layer (without any polygons) and to merge the newly drawn polygon into the original layer (with the rest of the polygons) after. But it feels like it doesn't help and the rendering performance is the same. I.e. both vector layers a being always rendered completely.
3. Are the any ways to avoid the rendering of the vector layers that don't change. 

Thanks!

**Comment by ahocevar** [comment]
The replacement for `renderMode: 'image'` is to use [`ol/layer/VectorImage`](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorImage-VectorImageLayer.html).
