### ISSUE TITLE
New projection disables repeating tiles (continuous world view)

### ISSUE THREAD

**Issue by monsieur-poirot** [openlayers/openlayers#8523]
Example: https://jsfiddle.net/8wm9cxth/5/

Reproduce: pan map left or right

Desired result: map tiles should repeat (like on default projection)

Is there a way to enable it?

**Comment by RalphLAtGitHub** [comment]
Please try: 	ol.proj.get('EPSG:3395').setGlobal(true);

**Comment by monsieur-poirot** [comment]
@RalphLAtGitHub 

That solved it, thank you. I'm closing this
