### ISSUE TITLE
CORS issues with custom tileLoadFunction

### ISSUE THREAD

**Issue by elielwaltrick** [openlayers/openlayers#8526]
I'm trying to create a custom loader function to load tiles from a tileserver but I'm having issues with CORS. As seen in the code below, I have already set the "crossOrigin" option, but it's still not working. I thought maybe the backend is not sending the proper headers, but I'm also sending the authorization cookies and it still doesn't work. 

When I remove the loader function and simply let OpenLayers do the work, it works perfectly. 

Any ideas?

```
  new  ol.layer.Tile ({
    source: new ol.source.XYZ({
      url: 'https://tileserver-a.mydomain.com/tiles/{z}/{x}/{y}.png?v=1',
      crossOrigin: 'anonymous',
      tileLoadFunction: function (tile, src) {
                          var client = new XMLHttpRequest();
                          client.open('GET', src);
                          client.withCredentials = true;
                          client.setRequestHeader('Accept','*/*');
                 
                          client.onload = function () {
                            var data = 'data:image/png;base64,' + btoa(unescape(encodeURIComponent(this.responseText)));
                            tile.getImage().src = data;
                          };

                          client.send();
                        }
    })
  })

```

**Comment by ahocevar** [comment]
The `crossOrigin: 'anonymous'` option only sets the crossorign attribute on the image element of the tile. For custom loaders I'd recommend you use object urls, like shown in https://github.com/openlayers/openlayers/blob/master/src/ol/Tile.js#L24-L40.
