### ISSUE TITLE
Performance problem with IOS 12 beta

### ISSUE THREAD

**Issue by ogo-adp** [openlayers/openlayers#8531]
To reproduce :
- take an iOS device
- open the clustered features sample on openlayers site
- move "cluster distance" slider a little bit to the left to display a good amount of clusters (to cover Africa for example)
- pan the map, it will be fast
- now rotate the map, and try again to pan the map. On iOS 11 it will still be smooth and fast. On iOS 12 it will be very very slow and choppy (even with very latest beta). However if you pan to the top and make clusters disappear it will be fast again
- rotate back the map to 0 degrees, it will be fast again on IOS 12 again (with clusters visible or not)

The problem have nothing to do with clusters, it is related to the number of features displayed on screen at the same time when the map is rotated. Openlayers 4 does also suffer from this badly. It makes Openlayers nearly unusable with rotation and a good amount of features (even a few dozens) starting from iOS 12 ...

**Comment by ahocevar** [comment]
Thanks for reporting this. Looks like a Safari issue. It would be great if you could produce a test case that does not involve OpenLayers, so we can file a Safari bug report.

**Comment by ogo-adp** [comment]
Maybe a return of #7294 ?

**Comment by ahocevar** [comment]
Unlikely. Did you do any profiling to see where the time is spent?

**Comment by ogo-adp** [comment]
Well I had the habit of hacking with jsfiddle and ol-debug.js because I can only debug iOS using internet sites but it seems it is not possible anymore. Any way I could find ol-debug.js somewhere ?

**Comment by ahocevar** [comment]
You can use https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.1.3/build/ol.js, which has a source map. See http://openlayers.org/en/latest/doc/quickstart.html.

**Comment by ogo-adp** [comment]
Yes I saw that, but I don't think a source map would help me to override some methods directly in jsfiddle. Anyway I did a test with 4.6.5. The slow method is ol.render.canvas.drawImage in which the only slow call is "context.drawImage" (only when the map is rotated). Is sees nothing special with this drawImage that could explain the bad performance. If I replace it with a rect() call for example it is slow too. I'm puzzled.

You can play with the (dirty) sample here : https://jsfiddle.net/c4qv9afb/882/

**Comment by ahocevar** [comment]
Thanks for the continued effort. So for a Safari bug report, it seems a simple [JSPerf](https://jsperf.com) case where `drawImage` is performed on a rotated target canvas should be enough. Would you be able to create such a JSPerf case?

**Comment by ahocevar** [comment]
So maybe it's the `globalAlpha`, or the use of a transform matrix (`setTransform` instead of `rotate`)?

**Comment by ogo-adp** [comment]
Nope same result if I force them to default values : https://jsfiddle.net/c4qv9afb/892/

**Comment by ogo-adp** [comment]
My latest fiddle still does rotate everything, so rotation is done elsewhere. I'm 99% sure that the problem is caused by rotation (plus maybe something else). If I add ol.render.canvas.rotateAtOffset=function(){}; the tiles don't rotate anymore but the features still do (and this is still slow) : https://jsfiddle.net/c4qv9afb/903/
If I revove the drawImage call it is fast again

**Comment by ahocevar** [comment]
The features are still rotated because their geometry coordinates are transformed to `pixelCoordinates` (see `transform2D` call quite at the top of the `replay_` function in `ol/canvas/Replay.js`). So there is no canvas context transform involved.

**Comment by ogo-adp** [comment]
Ok understood. Bu why in the hell removinf the single line "context.drawImage(image, originX, originY, w, h, x, y, w * scale, h * scale)" make the thing fast again ? And why is this line fast when the map isn't rotated ?

**Comment by ahocevar** [comment]
Good question. I don't have an iOS 12 device to test. It would be nice if this could be reproduced with plain canvas operations, without OpenLayers. Otherwise we cannot create a good Safari bug report.

**Comment by ogo-adp** [comment]
I investigated further. The problem could be related to context save/restore. Calling context.restore() just before context.drawImage make the map fast again on iOS 12. Does rotation implies a context.save() somewhere ?

**Comment by ogo-adp** [comment]
Doing context.restore() and context.save() before context.drawImage() make the performance normal again in all situations on iOS 12 : https://jsfiddle.net/c4qv9afb/1012/
When rotation is applied, something seems to be altered in context that make drawImage() very slow. Do you have any clue ?

**Comment by ahocevar** [comment]
It might be a `context.clip()` mask. That might be more expensive to calculate on a rotated canvas.

**Comment by ogo-adp** [comment]
You are right. Making ol.render.canvas.ReplayGroup.prototype.clip an empty function does make drawImage() fast again without save/restore

**Comment by ahocevar** [comment]
Cool, thanks for the continued investigation. Can you create a JSPerf and a Safari bug from the information we gathered now?

**Comment by ogo-adp** [comment]
I've made a jsperf to demonstrate the problem : https://jsperf.com/ios-12-canvas-clip-perf-problem

The clipping problem occurs as soon a the clip is no more a straight rectangle (this is what happen when the map is rotated)

Results on iOS11 (iphone) : 
- fast clip (no rotation) is 32% slower than no clip
- slow clip (no rotation) is 44% slower than no clip
-> no real perf difference between the two

Results on iOS12 (ipad) :
- fast clip (no rotation) is 22% slower than no clip (better perf than iOS 11)
- slow clip (no rotation) is 99% slower than no clip. To be more precise it is 93x slower. This is really abysmal ...

Results on PC (chrome/firefox/IE) :+1: 
- no real difference between the slow and fast clip
- no clip is always the fastest

I'm not an apple developper and don't have an apple account to file a safari bug. Could someone do the safari bug filing ?

Could openlayers be modified to not do any clipping ? Because clipping have a cost even on PC

**Comment by ahocevar** [comment]
Thanks @ogo-adp. I submitted a bug report: https://bugreport.apple.com/web/?problemID=43637911.

> Could openlayers be modified to not do any clipping ?

Clipping is necessary with simplified line and polygon geometries, and when rendering vector tiles. Saving/restoring context to remove the clip mask (for rendering points on vector layers) is also expensive, so I'm not sure if we'd gain performance in the end. But if you want to try, please go ahead.

**Comment by ogo-adp** [comment]
Thanks for your help @ahocevar

**Comment by ogo-adp** [comment]
Bug still there in safari with beta 11

**Comment by ogo-adp** [comment]
I did not test 12.0 final but bug is still there in 12.1 beta ...

**Comment by ahocevar** [comment]
There has been no reaction so far on the bug I created.

**Comment by ogo-adp** [comment]
Thanks for your input. I'm not surprised.

This bug should impact every openlayer app, and IOS 12 is being deployed, so let's hope a lot of people will complain ...

**Comment by ahocevar** [comment]
@ogo-adp Maybe the reason why the Apple ticket did not get attention is because the jsperf link is broken. Can you please double-check or recreate https://jsperf.com/ios-12-canvas-clip-perf-problem?

**Comment by stsje** [comment]
Can this issue be opened again? 
It is still a problem in the newest 6.2.1 release.

**Comment by ahocevar** [comment]
Still no comment from Apple.
