### ISSUE TITLE
Draw Shapes example throws error when drawing star

### ISSUE THREAD

**Issue by bernardobelchior** [openlayers/openlayers#8534]
The Draw Shapes example throws an error `TypeError: e is null` when drawing a star shape. The other shapes are fine.
You can see it [here](http://openlayers.org/en/latest/examples/draw-shapes.html?q=draw). 

Browser: Firefox Developer Edition 62.0b19 (64-bit)
OS: Linux 4.18.3

**Comment by fredj** [comment]
Thanks for the bug report, this issue was fixed with #8483
