### ISSUE TITLE
Issue in speed of loading tile

### ISSUE THREAD

**Issue by dixitgoyal** [openlayers/openlayers#8535]
When I embedded XYZ tiles, it loads every tile in around 1.2s but when I embedded same image file in html normally. It takes only 35ms to load.

**Comment by ahocevar** [comment]
Can you share your code so others can reproduce this?

**Comment by dixitgoyal** [comment]
var mapTileGrid = new ol.tilegrid.TileGrid({
      extent: tileExtent,
      minZoom: mapMinZoom,
      resolutions: mapResolutions
    });

    var layer = new ol.layer.Tile({
      source: new ol.source.XYZ({
        projection: 'PIXELS',
        tileGrid: mapTileGrid,
        url: tilesprefix+"{z}/{x}/{y}.jpg"
      })
    });

var map = new ol.Map({
      target: 'olmap2',
      layers: [ layer ],
      view: new ol.View({
        projection: ol.proj.get('PIXELS'),
        extent: mapExtent,
        maxResolution: mapTileGrid.getResolution(mapMinZoom)
      }),
      controls: []
    });

**Comment by dixitgoyal** [comment]
![screenshot from 2018-08-22 19-30-09](https://user-images.githubusercontent.com/11810114/44467991-dc113380-a641-11e8-8576-c270a26a0904.png)

Actually image type is **binary/octet-stream** here, it should be jpeg.

**Comment by ahocevar** [comment]
Do you have that code live somewhere, e.g. in a CodePen or JSFiddle, pointing to a real server?

**Comment by ahocevar** [comment]
What if you remove `projection: PIXELS`? That probably triggers raster reprojection on the client, which can be slow.

**Comment by dixitgoyal** [comment]
Code is on my local system, by removing **projection: PIXELS?** nothing happened.

**Comment by dixitgoyal** [comment]
Do you have any idea of **binary/octet-stream**

**Comment by dixitgoyal** [comment]
Please have a look at this and check speed of tile loading in console.

https://codepen.io/dixitgoyal/pen/LJVVoM

**Comment by ahocevar** [comment]
I cannot reproduce. Loading times are about the same when loaded by OpenLayers and in an `IMG` element.

**Comment by fredj** [comment]
If you look at the network tab in the chrome dev tools, you will see that the time is mostly spent at waiting for a response from the server (Waiting (TTFB)).

It could be a good idea at a Cache-Control header in the response.
