### ISSUE TITLE
Add setStroke and setFill to RegularShape

### ISSUE THREAD

**Issue by Nols1000** [openlayers/openlayers#8536]
The class https://github.com/openlayers/openlayers/blob/v5.1.3/src/ol/style/RegularShape.js can be initialized with options stroke and fill, but later on it is not possible to change the stroke or fill with a setter.
Is there a reason for that?

**Comment by ahocevar** [comment]
The RegularShape class creates a canvas with the shape - once upon construction - which is reused. It's equally expensive to create a new RegularShape when you need a different stroke or fill.
