### ISSUE TITLE
OSM Tiles shows labels only in country specific letters (chinese,cyrlic,...)

### ISSUE THREAD

**Issue by npgeomap** [openlayers/openlayers#8538]
Hi,
for some time the default OSM Layer: `ol.source.OSM()` shows letters **only** in country specific labels, e.g. chinese letters when panning over China or Japan.
![image](https://user-images.githubusercontent.com/4803504/44582844-32e24e80-a7a3-11e8-84c8-66c1fde25b80.png)
Sample: [http://tsauerwein.github.io/ol3/mapbox-gl-js/examples/center.html?q=openstreetmap](url)

I know this is not an openlayers issue but since ol.source.OSM() is a basic default layer it affects openlayers.

greetings Christian

**Comment by fredj** [comment]
If the style of the OSM tiles doesn't fits your needs you should try to use mapbox, Bing or an other source.
There's nothing we can do to change the OSM tile style
