### ISSUE TITLE
Internet Explorer 11: Could not complete the operation due to error 887a0005

### ISSUE THREAD

**Issue by hawkaa** [openlayers/openlayers#8539]
Hi there, OpenLayers contributors and community,

We have our OpenLayers-based application connected to Sentry for error tracking. The error we've seen most frequently the last couple of months is the following error:

```
 Could not complete the operation due to error 887a0005
```

The stack traces points to the following lines:

- https://github.com/openlayers/openlayers/blob/141fe5fe4929b92bea3cd85a75898bb2a8463dfa/src/ol/renderer/canvas/TileLayer.js#L329
- https://github.com/openlayers/openlayers/blob/141fe5fe4929b92bea3cd85a75898bb2a8463dfa/src/ol/renderer/canvas/TileLayer.js#L237

The errors' origin is uniformly spread across our customers, our servers, and our releases, Windows versions, except that all origin from Internet Explorer 11.  The error message is sometimes preceeded with "Error: Not enough space to complete the operation" (translation from Norwegian, might be inaccurate). I'm unable to reproduce the issue. We're running OpenLayers 4.4.2.

It could be related to the following issue: https://stackoverflow.com/questions/46914128/indexsizeerror-on-drawimage-on-ie-and-edge, although we haven't seen the issue on Edge. However, we don't believe many of our customers use edge.

I'm not sure if it's a bug or not, but I wanted to let the community know about this problem.

**Comment by fredj** [comment]
We're also seeing some of these 887a0005 errors in our sentry. The origin is also from Explorer 11 and always from Windows Phone.

**Comment by ahennr** [comment]
For the project I'm currently working in I can confirm this issue as well. In particular, this problem occurs in OpenLayers version 5.3.0 in IE11 (Version 11.0.9600.19236) if ~10-15 TileWMS layers are added to the map. Did you find any solution or any workaround that fixed this problem @hawkaa or @fredj, perhaps in the IE11 settings?

**Comment by hawkaa** [comment]
We have not seen the error in two months now. We're running on 5.3.0. We've done substantial changes to our application since then, but nothing actively to fix the issue.

**Comment by fredj** [comment]
#9133 drastically reduces the default tile cache size used by the tile layers. The could help with this IE11 issue

**Comment by ahennr** [comment]
Thanks a lot @hawkaa and @fredj. As #9133 is merged, I'll give it a try and report my results here :smiley:
