### ISSUE TITLE
change of map's projection does not work correct with v5.x

### ISSUE THREAD

**Issue by mbc-github** [openlayers/openlayers#8545]
With v5.x my site do not work any more (I configured to use the swissprojection).

*** maybe the bug is related with swiss projection only (EPSG:21781) ***

To track down the problem, I tried the example in the FAQ, but it does not work, either the map or the simple projection transform do not work (tested on win7/
chrome with openlayers v.5.1.3)
<code>
var swissProjection = new ol.proj.Projection({
  code: 'EPSG:21781',
  extent: [485869.5728, 76443.1884, 837076.5648, 299941.7864],
  units: 'm'
});
ol.proj.addProjection(swissProjection);

 swissCoord = ol.proj.transform([8.23, 46.86], 'EPSG:4326', 'EPSG:21781');

(2) [8.23, 46.86]`
</code>

as you can see, I get the lon / lat coordinates instead of Swiss coordinates

----------------
Trying to display the map, I get only a blue box, no map no streets, no names, from the FAQ example:
[http://openlayers.org/en/latest/doc/faq.html#how-do-i-change-the-projection-of-my-map-](url)
<code>
var map = new ol.Map({
	target: 'map',
	view: new ol.View({
		projection: swissProjection,

		center: ol.proj.transform([8.23, 46.86], 'EPSG:4326', 'EPSG:21781'),
		zoom: 0
	}),
	layers: [
	  new ol.layer.Tile({
		source: new ol.source.OSM()
	  })
	],
});
</code>
![chrome_screenshot](https://user-images.githubusercontent.com/41478564/44632049-b1421a80-a974-11e8-9398-d916db442b77.jpg)
Please FIX the FAQ code for change projection.

**Comment by ahocevar** [comment]
Please see https://openlayers.org/en/v5.1.3/examples/wms-image-custom-proj.html and "Changes in proj4 integration" in the [v5.0.0 release notes](https://github.com/openlayers/openlayers/releases/tag/v5.0.0). I have also updated the FAQ with #8546.

**Comment by mbc-github** [comment]
Thanks a lot,

after adding the line:

`  
ol.proj.proj4.register(proj4)

`

the site work flawlessy with v5.1.3
