### ISSUE TITLE
setGeometryName prevend render vectorlayers

### ISSUE THREAD

**Issue by MSZ006AEUG** [openlayers/openlayers#8548]
`function drawLineString() {
    const lineString = new LineString([]);
    lineString.setCoordinates(plot_data);
  
    const feature = new Feature(
      lineString.transform('EPSG:4326', 'EPSG:3857')
    );
    feature.setGeometryName("pathway");
  
    const vectorsource = new VectorSource({
      features: [feature]
    });
  
    const linelayer = new VectorLayer({
      source: vectorsource,
      style: new Style({
        stroke: new Stroke({color: '#0000FF', width: 4})
      })
    });
  
    map.addLayer(linelayer);
}`

This is my code render LineString on map.  And 

`function drawMarkers() {
    const markerFeatures = [];
    for(i = 0; i < plot_data.length; i++) {
      var markerFeature = new Feature({
        type: 'icon',
        geometry: new Point(fromLonLat(plot_data[i]))
      });
      markerFeature.setGeometryName("marker" + (i + 1));
      markerFeatures.push(markerFeature);
    }
  
    for(i = 0; i < plot_data.length; i++) {
      markerFeatures[i].setStyle(new Style({
        image: new Icon(/** @type {module:ol/style/Icon~Options} */ ({
          scale: 0.10, 
          anchor: [0.4, 0.7],
          crossOrigin: 'anonymous',
          src: 'src/car.png'
        }))
      }));
    }
  
    const vectorsource = new VectorSource({
      features: markerFeatures
    });
  
    const markerlayer = new VectorLayer({
      source: vectorsource
    });
  
    map.addLayer(markerlayer);
}`

This is my code render markers on map.

These code are fine without `feature.setGeometryName`. When I use `feture.setGeometryName`, LineString and markers don't show on my map. In this situation, no bugs shows in browser.

Please help. Thank you

**Comment by ahocevar** [comment]
It's because you point the feature away from its geometry. Do this instead:
```js
var markerFeature = new Feature({
  type: 'icon'
});
markerFeature.setGeometryName("marker" + (i + 1));
markerFeature.setGeometry(new Point(fromLonLat(plot_data[i])));
```
However, I wonder what you want to achieve by changing the geometry name.

**Comment by MSZ006AEUG** [comment]
That works. Thank you.

I wanted to get geometry name through ol/interaction/Select event.
