### ISSUE TITLE
geojson-vt only works with polygons

### ISSUE THREAD

**Issue by stephanebury** [openlayers/openlayers#8550]
I tried to use geojson-vt example : only polygons are visible.
if i replace the geojson with a feature collection of polygons, it's ok.
But if i replace the geojson with a feature collection of points, geojson-vt  works but nothing is visible on the map.

Could you help me, thx ?

**Comment by ahocevar** [comment]
Maybe the `replacer` in that example is not suitable for your file. You may have to modify it.

**Comment by stephanebury** [comment]
The function JSON.stringify with a callback _replacer_ doesn't work for me. I have error message

> Cannot read property 'geometry' of null

So I have written this code to show a geojson with vectorTile:

      var vtToGeojson = function(features) {
        var geojsonFeatures = [];
        features.forEach(function(feature){
            if (feature.geometry) {
				var type;
				var rawType = feature.type;
				var geometry = feature.geometry;

				if (rawType === 1) {
					type = 'MultiPoint';
					if (geometry.length == 1) {
					  type = 'Point';
					  geometry = geometry[0];
					}
				} else if (rawType === 2) {
					type = 'MultiLineString';
					if (geometry.length == 1) {
					  type = 'LineString';
					  geometry = geometry[0];
					}
				} else if (rawType === 3) {
					type = 'Polygon';
					if (geometry.length > 1) {
					  type = 'MultiPolygon';
					  geometry = [geometry];
					}
				}

				var geojsonFeature = {
					'type': 'Feature',
					'geometry': {
					'type': type,
					'coordinates': geometry
					},
					'properties': feature.tags
				};
				geojsonFeatures.push(geojsonFeature);
            }            
        });

        return JSON.stringify({
            type: 'FeatureCollection',
            features: geojsonFeatures
        });               
      }; 

```
     var url = './data/geojson/points.geojson';
      fetch(url).then(function(response) {
        return response.json();
      }).then(function(json) {
        var tileIndex = geojsonvt(json, {
          extent: 4096
        });
        var vectorSource = new ol.source.VectorTile({
          format: new ol.format.GeoJSON(),
          tileLoadFunction: function(tile) {
            var format = tile.getFormat();
            var tileCoord = tile.getTileCoord();
            var data = tileIndex.getTile(tileCoord[0], tileCoord[1], -tileCoord[2] - 1);
            var features = format.readFeatures(vtToGeojson(data ? data.features : []));
		
            tile.setLoader(function() {
              tile.setFeatures(features);
              tile.setProjection(tilePixels);
            });
          },
          url: 'data:'
        });
```

This works fine for me.
Thx for your help.
