### ISSUE TITLE
openlayers + types/openlayers

### ISSUE THREAD

**Issue by hasaniadnan** [openlayers/openlayers#8559]
Hi when trying to use the openlayers types 4.6.12 with openlayers 5.1.3 it is not able to find the import types. Import needs to be done manually in typescript for instance: import * as ol from "openlayers"; 

Is there an actual types/openlayers version matching to the current openlayers version?

**Comment by Zuzon** [comment]
openlayers 5 did not support typings from definitely typed package. Native support of TS in openlayers will be done very soon.

**Comment by shenAwesome** [comment]
I am having the same issue. the @types don't match the 5.1.3. Hope the native support will come soon. Thank you for your hard work
