### ISSUE TITLE
openlayers fails to render properly when map is enclosed in an accordion

### ISSUE THREAD

**Issue by greenelk** [openlayers/openlayers#8562]
I've got an issue getting openlayers to draw a map which is enclosed in a bootstrap accordion. When i expand the entry the map does not render until I resize the window. 

I've put a very cut down example here https://jsfiddle.net/greenelk/jtdhvs07/

**Comment by fredj** [comment]
You need to manually call `updateSize` when the size of the element has changed.
In the case of this bootstrap accordion, the [`shown.bs.collapse`](https://getbootstrap.com/docs/4.0/components/collapse/#events) event can be used.

See the updated jsfiddle: https://jsfiddle.net/fredj/7xgt6apf/. 
The function is:
```
$('#collapseOne').on('shown.bs.collapse', function () {
  map.updateSize();
});
```
