### ISSUE TITLE
Night and Day Layer

### ISSUE THREAD

**Issue by pedrolopes10** [openlayers/openlayers#8570]
Is there a way to accomplish the following layer:

![preview](https://user-images.githubusercontent.com/5683649/44931877-0ad28c80-ad5b-11e8-9414-10e921bee443.jpg)

https://github.com/rossengeorgiev/nite-overlay

I've tried to adapt with regular Circles ( https://jsfiddle.net/5mvk1oc9/ ) and also with circular polygons but with no success.

Thanks for this great library, it has been a pleasure working with it!

**Comment by RalphLAtGitHub** [comment]
I have not found a simple solution until today. From my point of view you will have to calculate the actual solar position, compute a circle (in parametric form) around the opposite point with the different radii for civil twilight, nautical twilight etc., create a polygon from each circle with a suitable increment, split the polygons if necessary at the antimeridian, transform the polygons to your projection and add them as features to a vector source. Any better idea is welcome!

**Comment by pedrolopes10** [comment]
Hi @RalphLAtGitHub! The first part is all done on the library 'nite-overlay'. If you check the fiddle https://jsfiddle.net/5mvk1oc9/ I've done the same but with perfect circles. I couldn't apply a new projection or do a circular polygon with the calculated points.

**Comment by RalphLAtGitHub** [comment]
Hi @pedrolopes10, ol.geom.Circle generates the perfect circle in the Mercator projection. You need a circle on the sphere (i.e. see here:   [https://math.stackexchange.com/a/1349100](url)) which is transformed to the Mercator projection. Depending on the position of the sun, this results in an ellipse or a sinusoid.

**Comment by pjsg** [comment]
I have a custom rendered day/night layer that works reasonably well in ol5. It does use WebGL to do the calculations. Check out https://pskreporter.info/pskmap for an example. As a gimmick, it also draws the shadow of the moon during solar eclipses.

**Comment by ThomasG77** [comment]
I've more or less done a library to generate a GeoJSON of night & days and then display it in OpenLayers. Not as good as mentioned Google maps "nite-overlay" that display civil twilight, nautical twilight, astronomical twilight and night but it does display night & days.
See https://github.com/webgeodatavore/GeoJSON.Terminator/ and associated [OpenLayers demo ](https://rawgit.com/webgeodatavore/GeoJSON.Terminator/master/demo/index.html)

**Comment by TagLoomis** [comment]
@pedrolopes10 I cleaned up the code more as it was a little embarrassing.  I added "vertices" as a class member , which is referenced by the code.  I've tested in each of the fours seasons for proper view.  

https://jsfiddle.net/5mvk1oc9/65/

![sunshadow](https://user-images.githubusercontent.com/16214775/49702289-7e323880-fbab-11e8-9542-7db55b6ed0a5.png)

**Comment by ThomasG77** [comment]
FYI, https://viglino.github.io/ol-ext/examples/layer/map.daynight.html with related issue https://github.com/Viglino/ol-ext/issues/411

**Comment by jmgomezpoveda** [comment]
There's another nice implementation using OpenLayers at https://pskreporter.info/pskmap
