### ISSUE TITLE
can't add base64 image string as style for vector layer

### ISSUE THREAD

**Issue by AhammadAliPK** [openlayers/openlayers#8571]
I have tried to add a base64 image string as style for a vector layer , but it is not working , 

var style = new olStyle({
      image: new olIcon({
        //imgSize: [20, 20],
        //img: image,
        src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAC4AAAAuCAYAAABXuSs3AAAAAXNSR0IB2cksfwAAAAlwSFlzAAAOxAAADsQBlSsOGwAACcpJREFUaIHtmX9QlHUex18LCyu/YUFlPQNUWBTRI0RQuixM2kkqTxskDAOrwWmuGkMQHMvTkxlThzzmCpNGrUQskVA5cChmJErlRyp3VLbCRAvpGr8EFoSF3eX+eJ4V8McKpN3djJ+ZZ4bl+T6fz+v7fr4/Pt/PI+X/1KT/bYDx2gPw39segA8zyW3+N3ivg9wLcImFCwToO13jtt8CboazFi8pYCv+bRwGZm5jAvTAwLD7JsbZgbGCS8RAVsOA7UXgXuA6MAFwBmzE9v1AF9AntnMV4a+LHTCKHTD7vi/g3ARsL0IZgXne3t7BQUEhQUrljNnu7u52Egm0tV3ra2io+6Gq6tsLGo3mAnBO7IzbsM4axgI9VnAJgtJSwAVBpS4gMj4hIWFldHRkaGionYeHx+2e/WNre3vsuepqfV5eXum+ffsOACUIb8AN6ER4C6MeOmMBt7op0ORnoqJ2bfnb1oTg4HkjGnZdvkyrRsMg4OHlhcvUqXjI5ahUKplKpYp67bXXorZs2ZJz/PjxrYAWkAPXEN6ESXRjsQOjATcrbSNCXwNmb9++/WBaWtpMc6OLpaWcKyigsbKS7itX6NNqAZigUOAwZQreISEELV9OoEpFUFAQx44di9u1c2fYhtTUOKBW9N3OkPIWbbTg1ggTrhMI2LdvX/FLL700EeCX2lqOrF+P+ssvMQHOMhl2cjlOvr4AGAcG6PjuOy6fO8fZvXvxVamI2bmTKXPnkrJhg98kz8nFCfEJUSK8C9Ahwv8mxc1q2yNMQI/09PR8M/SFo0fJiI6mH5jt74+VnR2m3l4kgFQqRQIYZDJsfHxwlEoxGQycKimhoqSE1MOHCX7+eeJfjHdvaW45mpKSEoGguB1Dy+Ud4UcDLhXB2yMjI7M3bdrkDVBz4gRvR0cTERlJSHQ0RxIT8Zw9G1uplAGDAV13N906Hf30YOwRnF3R61n7bganPznIithYcq2sCF+5kuTk5KllZWW7i4qKViIsl33cZaJaAh+udgcQlZGRsQLgV7Wa95YtwxNYk52N3MeH7wsL+bmwELy9ab96lX69HkQHVjIZrXo9QWFhLHsziflRT1Ph78/bMTF8EhTEH5RKdu3a9XRRUdGfgWOAA0NL5G3h76a4eTcciI+PXztnzhwAjm7ciA54OCwMuY8PAMolSyguLESu0QjLj0x2Y0exdgCdHuY/twKAKUolId7eFGs0fLB2LdtOnWLWrFkkJia+mp2dfVKMK8WC6pbAzWv2dSAsNiZmMUBDVRX/LihA6e3Ntbo6vszIYIKHB4VZ/8AKsJPLsQZa29sB8JDLMQJu6Pnm4/04urrR9ssvNGs0LAAqy8r4obycgEWLWBkT82h2dvYC4LQYe8CSoncyCSADdDKFIjRs4UJrgDMHD2ICejQaIrdvZ7JSib6vjxVv/ZXc1avpbm/nChDg7c1gfz/fabV4AL7+vqz++3t0tLbgFRhIyKoXKM89hBEo3b+fgEWLCAsNRaFQhGq12lOAI8JYHxO4eXxbA3ZLFyyY4+rqCkBTdTXOCNP+6o8/8lRaGgDffHqYSwiL/ZOrVvF6Vham/n7ef/NNvjp0iBp1PWvs7Xn0+VhMJhMFW9++sQWry74AwNHRkYiIiODc3FyHYQxjVhyECeLi5+cXANDd3IyusRE7Uc0fPv2U7nffxVEup2RvNlrg4IkTzH/mmRsONubksOyVV1gREcGxzExmhYdTX1HBxe/VeMqgXw8dGi0tDQ1MnDYNn2nTZgBOgI6hDPSWcX63oTII2Li7u08AaK6vp1erxcnXlwGdDpnnQzc8moz9vLVx4whoswU8/jjv7HiHSxfOA2Brby8sG3oBoBtobWpi4rRpODs5yRBe3D3Z8iWM8GSNlUxGp64dg9EAQFvjZSaIw+l2ZuvkTE9bq4UwonfJ7Q5Qt5ol8EERuL/t2rVegEkzZmCnUGAa6MME9Pf0IBHjrcnKshjIc+ZMlqVtGo4ICGNRBrhPfQgAnU5nPmxY7MFo1vHOOrX6IjDXafJkHL28aK2pwdbBASMgERUKW7rUoqPgiIhhv4bQuwFPhYJJ06cD0PBTQwPC+LZiHBuQ+VhlBHorKipqOzs7Y1xcXPAKmUdTZSXWDg4Y9fob4OMxCULW9tiTSwDouX6dqqrK80APwgS9Y5Z4t6GiB2Rarba6qqLCFKlSWS18IY4z72dh6OmxOHuMfX309vbi6OZmMQDA4vg1AFRXVlJfX1+FMDn7GGeuYkJcDoGKw5999lWkShUxfeFCApcv51RBAc4yGVJb21sebGlsZOOCBbRqtWwrLWXOE0+MuG9tLUUG/AT8KTycOeIwOpKXdwY4i5CrdDBOxRHBB4CBAwcOfJCclBQREBjIc9vf4VRBAV16PfbOzrc8lLdtG+e0WlyB915+mb0//zzivuukibQi7G6vfvghAHWXLrFnz54sBKXNlYI72t2GigkhV3EDCpM3bDhRXFz87CR/JetzckmKW8X6hx9m6kwlHVebMRqNWNvYcPn0aYIAaxnoNRo2PfIIEltbpFZWuHlOQvOvC2iBjI8/4qGAAABS09JKEDJDV4RT1rjTWjO8QVTB7uTJk+t27NgRlJqa6hX2Qizpg0ZeX70afU0Ns0RnBoQDpEwuw9QDUpmei2fOgHjvIsLyl/nRARa/GA/A7t27LxcUFLyBkIn2MYpT/2jATQiz3A34NS0tLVrh6Xnyxfh4eURcHEWBgbz/xhvUfP01IMhlAvrbhXzcKAbpEB0+Gx7OXzIzmR4SAkBOTk5HUlLSSqAJYT7dVe3RgJvhDQgrlxyojU9IWNrc0pKTnJzs6x0UxM7ycr49WcI3hw/xY3kpnRot3eLDMkCuULBwyWLCY2IJi4q64TgzM7Nh3bp1ccB50Xc7o6yxjBYchEl6DUH52pSUlKUVFRVbN2/eHDt37lxCnlIR8pQKAG1dHR1aLTCIq6cChVI5wmFtbS3p6el5R44c2Qw0MlSeGNUJf7TgZngTQt2jHWFEtOXn56/Nz88//mpi4poV0dGL54eG2rg4O6Pw80Ph5zfCQVeXjuqqKsPnBZ+XZWVl7Qf+KcZ3ZmRZ4p4XhMzwA2IgB4TdrXBPdvYXe7Kz5/v7+wfPmzdvvo+Pj6+zs5MMJJKurq6+pqamn86ePVtdX19/HqhGKL25IExEs9L3rQRnNrMqOjGwveinQq1Wl6vVanuE04stQ0VPHcKyaiO2t2OofjJc5ftW9BwewHwZGCozOyAkR93D2ppPMg4IKYR5RzRfYwIeL/hwG2SoRGxEUK9PhLw58zKr+j9R2DfbzRB3Shfv6eeU+/EN6J5/77mdPfjq9nvbA/Df2/4DnjKtYvrFCfMAAAAASUVORK5CYII='
        
        
      })
    })
    return style;​

**Comment by ahocevar** [comment]
I don't see any reason why the above should not work. Any kind of errors in the console? Can you share some live code?

**Comment by AhammadAliPK** [comment]
yeah , i will share , please give a couple of minutes

**Comment by AhammadAliPK** [comment]
@ahocevar , working fine . caused by some other issue . sorry

**Comment by MiesSuomesta** [comment]
> @ahocevar , working fine . caused by some other issue . sorry

What was the issue ?
