### ISSUE TITLE
mouse position control can't transform projection from epsg2332 to epsg4610 with v5.2.0

### ISSUE THREAD

**Issue by zyb284629791** [openlayers/openlayers#8584]
ol.proj.js scripts, there are some difference between v5.2.0 and v4.6.5, in the function 'getTransformFromProjections', at v5.2.0 there are less code than v4.6.5 to define own projecion,
````
if (ol.ENABLE_PROJ4JS && !transform) {
    var proj4js = ol.proj.proj4.get();
    if (typeof proj4js == 'function') {
      var sourceDef = proj4js.defs(sourceCode);
      var destinationDef = proj4js.defs(destinationCode);

      if (sourceDef !== undefined && destinationDef !== undefined) {
        if (sourceDef === destinationDef) {
          ol.proj.addEquivalentProjections([destinationProjection, sourceProjection]);
        } else {
          var proj4Transform = proj4js(destinationCode, sourceCode);
          ol.proj.addCoordinateTransforms(destinationProjection, sourceProjection,
              proj4Transform.forward, proj4Transform.inverse);
        }
        transform = ol.proj.transforms.get(sourceCode, destinationCode);
      }
    }
  }
````
 as you can see, in v5.2.0, those codes are gone,due to this case,my mouse position control doesn't work while i use epsg2332 with map projection and epsg4610 for mouse position control, i can't get normol lat and lon but epsg2332 coornidate , if there are some new method or function can solve this problem, please tell me how to solve it. thanks 
}

**Comment by geocodezip** [comment]
Also asked on SO:
https://stackoverflow.com/questions/52179464/mouse-position-control-cant-transform-projection-from-epsg2332-to-epsg4610-with

**Comment by zyb284629791** [comment]
@geocodezip yes,that question was asked by myself... and I've solved this problem, thanks~~
