### ISSUE TITLE
Add types for EsriJSON*

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#8597]
`npx tsc` reveals things like this:

```
src/ol/format/EsriJSON.js(304,12): error TS2304: Cannot find name 'EsriJSONGeometry'.
src/ol/format/EsriJSON.js(404,27): error TS2304: Cannot find name 'EsriJSONPoint'.
src/ol/format/EsriJSON.js(452,13): error TS2304: Cannot find name 'EsriJSONPolyline'.
src/ol/format/EsriJSON.js(506,13): error TS2304: Cannot find name 'EsriJSONMultipoint'.
src/ol/format/EsriJSON.js(523,13): error TS2304: Cannot find name 'EsriJSONPolygon'.
```

We got rid of these types in #8273.  Similar to #8596, we need to add in `@typedef`s for those that we use.  In addition, I think we'll want to quote property access on these objects - but this should probably be confirmed.

**Comment by schmidtk** [comment]
@tschaub Would it be preferred to add TS type declarations for these in `types`, similar to the extensions I added for DOM API's? That should also allow dot property access, but we'll still want to confirm.
