### ISSUE TITLE
Add types for GeoJSON

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#8598]
`npx tsc` reveals things like this:
```
src/ol/format/GeoJSON.js(84,15): error TS2304: Cannot find name 'GeoJSONFeature'.
src/ol/format/GeoJSON.js(92,30): error TS2304: Cannot find name 'GeoJSONGeometry'.
src/ol/format/GeoJSON.js(92,46): error TS2304: Cannot find name 'GeoJSONGeometryCollection'.
src/ol/format/GeoJSON.js(117,38): error TS2304: Cannot find name 'GeoJSONObject'.
```

We got rid of these types in #8273. Similar to #8596, we need to add in `@typedef`s for those that we use. In addition, I think we'll want to quote property access on these objects - but this should probably be confirmed.

**Comment by fredj** [comment]
could we use https://www.npmjs.com/package/@types/geojson instead of adding `@typedef`?

**Comment by ahocevar** [comment]
In the spirit of publishing TypeScript friendly JavaScript, I think adding these typedefs makes sense.

**Comment by ahocevar** [comment]
That’s correct. If it’s really enough to `npm install @types/geojson`, we could do as @fredj suggested.

**Comment by tschaub** [comment]
See #8615 for a PR that makes use of `@types/geojson`.  Good suggestion @fredj.  This still works with our "pure JS" approach (with JSDoc comments).
