### ISSUE TITLE
ol.interaction.Draw 

### ISSUE THREAD

**Issue by mrpan** [openlayers/openlayers#8604]
when i use ol.interaction.Draw to draw line ,i found the line of using interaction is different from the line of using coordinate ,the example is     https://codepen.io/giserpan/full/NLaqqB    ,the result like this:
![image](https://user-images.githubusercontent.com/3354097/45204116-da39a800-b2b0-11e8-9f5a-d3a2888fad00.png)

**Comment by 0trenixjetix** [comment]
Are you sure that you are interacting correctly?
I mean, you can fail to do pixel-perfect lines, it's normal.

**Comment by mrpan** [comment]
> Are you sure that you are interacting correctly?
> I mean, you can fail to do pixel-perfect lines, it's normal.

this situation does not always happen ，i check the source code ,the event parameter sometimes has changed , I didn't find the root cause

**Comment by cs09g** [comment]
The way to reproduce this issue is dragging map while draw the line. `condition` always returns true no matter line is drawn or not, but `e.coordinate` inserts into `coordinates_drawing`. so it's not synchronized.
