### ISSUE TITLE
Current version of Mouse Position Example fails on Android OS

### ISSUE THREAD

**Issue by richnic** [openlayers/openlayers#8605]
https://openlayers.org/en/latest/examples/mouse-position.html (v5.2.0) is broken on Android OS: The coordinates are not shown. However, the old version https://openlayers.org/en/v5.1.3/examples/mouse-position.html still works fine.

Details:
- Tap on the map, then drag the map => coordinates are not shown.
- Tap on Zoom in/out controls or Attributions control, then drag the map => coordinates are shown.

Tested with Samsung Internet 7.2.10.33 and 7.4.00.70.

**Comment by ahocevar** [comment]
Confirmed, and it affects all touch devices. `git bisect` says c74b9c1d55fc91216aa73895c1e247f82b96e851 is the first bad commit:
```
commit c74b9c1d55fc91216aa73895c1e247f82b96e851
Author: ahocevar <andreas.hocevar@gmail.com>
Date:   Tue Jul 31 08:33:15 2018 +0200

    Do not prevent default on pointermove
    
    Instead, only prevent default on handled pointerdown events. This makes
    the `focus` condition work with interactions that involve dragging on
    touch devices.
```
