### ISSUE TITLE
Firefox 60.2.0esr on Windows 10 Pro version 1803 on Parallels does not show zoom plus and minus controls

### ISSUE THREAD

**Issue by MattiL** [openlayers/openlayers#8606]
Firefox 60.2.0esr on Windows 10 Pro version 1803 on Parallels version 14.0.0 (45124), macOS 10.13.6 (17G65), MacBook Pro (13-inch, Late 2011) does not show zoom plus and minus controls. The control area appears all white e.g. in the following example but zooming by pressing the place where the plus and minus should appear works.
https://openlayers.org/en/latest/examples/static-image.html

**Comment by ahocevar** [comment]
Maybe this is a graphics driver problem? I just tried with Firefox 61 on MacOS, and the controls look fine.

**Comment by fredj** [comment]
Looks fine with Firefox 60.0 on Windows 10
