### ISSUE TITLE
how to zoom to layer which is invisible at load time?

### ISSUE THREAD

**Issue by AhammadAliPK** [openlayers/openlayers#8612]
I have a layer which , its maxResolution is set as 10 while adding on the map. It will only visible at a that zoom level. But when user clicks on a button called zoomto layer against that layer, i want to zoom to that particular layer . But when i tried to take extent of that layer its always getting infinity as its not visible in the map , my code ,

    let lay = this.mapService.getLayerByName(layer.layerName);
    let resolution = lay.getMaxResolution();
    let map = this.mapService.getMap();
    let zoom = Math.floor(map.getView().getZoomForResolution(resolution)+1);
    map.getView().setZoom(zoom);
    let layerExtent = lay.getSource().getExtent();
    console.log("layerExtent",layerExtent)
    this.mapService.fitExtent(layerExtent);
    map.getView().fit(lay.getSource().getExtent(), map.getSize());
    map.getView().setZoom(zoom);](url)
is there any way to zoom to a layer which is not visible at that moment ?

**Comment by bojko108** [comment]
Hello, we had the same problem and decided to calculate the extent from the source table and 
wrote a custom function on the server which returns the extent on demand (with http request).

If your data is static you can just store the extent value to a variable and use that variable.
