### ISSUE TITLE
GeoJSON.readFeatures missing from documentation

### ISSUE THREAD

**Issue by ffxsam** [openlayers/openlayers#8620]
https://openlayers.org/en/latest/apidoc/module-ol_format_GeoJSON-GeoJSON.html

`readFeatures` is missing from the documentation (and possibly other methods).

**Comment by ahocevar** [comment]
We are currently reworking the API docs to use TypeDoc instead of JSDoc. When done, this and other issues with the API docs should be fixed.

**Comment by fredj** [comment]
Fixed, see:
https://openlayers.org/en/master/apidoc/module-ol_format_GeoJSON-GeoJSON.html
