### ISSUE TITLE
Contradiction between collapsible docs and OSM source

### ISSUE THREAD

**Issue by jonenst** [openlayers/openlayers#8621]
the OSM() source has a default behavior of hidding the attribution behind a button in the bottom right corner even on large screens (see it here https://openlayers.org/en/latest/examples/simple.html )

On https://openlayers.org/en/latest/apidoc/module-ol_control_Attribution-Attribution.html, it reads

> If you use an OSM source, [collapsible] should be set to false — see href="http://www.openstreetmap.org/copyright">www.openstreetmap.org/copyright OSM Copyright —

Shouldn't the OSM source create an Attribution object with collapsible set to false on its own, instead of providing only a copyright string ?

**Comment by ahocevar** [comment]
`ol/control/Attribution` is responsible for displaying the attributions that the source provide. A source does not create an attribution control. And currently sources cannot override that behavior of the control.

I agree that it would make sense for sources to be able to hint the attribution control to not collapse the attribution, and we'd accept a pull request for that.
