### ISSUE TITLE
Overlay 里的positioning属性，设置为bottom-center的时候，图标没效果

### ISSUE THREAD

**Issue by zhangquans** [openlayers/openlayers#8632]
![image](https://user-images.githubusercontent.com/43264972/45537886-17191800-b838-11e8-8213-cd88e8c64daa.png)

**Comment by ahocevar** [comment]
Are you reporting a bug? Please provide more context, including a live example to demonstrate the issue.

**Comment by zhangquans** [comment]
var faultDiv=document.getElementById("faultDiv");
    var layer = new ol.layer.Vector({
        source: new ol.source.Vector()
    });
    var myView= new ol.View({
        projection: 'EPSG:4326',
        center: [104, 30],
        zoom: 10
    });
    var map = new ol.Map({
        layers: [
            new ol.layer.Tile({
                source: new ol.source.OSM()
            }),
            layer
        ],
        target: 'map',
        view:myView
    });

    var anchor = new ol.Feature({
        geometry: new ol.geom.Point([104, 30]),
    });

   anchor.setStyle(new ol.style.Style({
        image: new ol.style.Icon({
            src: '/on-line.png',
        })
    }));
    layer.getSource().addFeature(anchor);
    function  getDiv(){
        var imagediv=" <div id='deviqi'><img src='/on-line.png' ></div>";

            faultDiv.innerHTML=imagediv;
            var overlay1=new ol.Overlay({
                element:document.getElementById("deviqi"),
                position:[104,30],
                positioning:"bottom-center"
            });
            map.addOverlay(overlay1);

    }

    setInterval("getDiv()",3000);

> 你是否报告了一个错误？请提供更多上下文，包括演示此问题的实例。

**Comment by ahocevar** [comment]
Please describe the issue in plain English.
