### ISSUE TITLE
Custom Control - PointerEventHandler error with SVG on IE9

### ISSUE THREAD

**Issue by aalices** [openlayers/openlayers#8633]
Hello all!

First of all, I've read that IE9 is no longer supported in OL but there might be a workaround for this.
So, I wanted to create a custom `Control` for my map, so I created a structure like this:
```
<div>
  <button>
    <svg><path /><svg>
  </button>
<div>
```
And set the wrapping `div` as `Control`'s `element`. It works fine for most browsers but on IE9 it crashes here: https://github.com/openlayers/openlayers/blob/master/src/ol/pointer/PointerEventHandler.js#L358 with an error `Object doesn't support property or method 'contains'` as the `continer` attribute is of type `SVGPathElement` . 
Any ideas for making it work ?

**Comment by fredj** [comment]
What about not passing the `div` to your custom `Control` and register a `onclick` event listener?

**Comment by aalices** [comment]
@fredj I'll try that in a moment but would it be still reasonable to make it a custom `Control` and just a non-OL HTML element?

**Comment by fredj** [comment]
@aalices yes, that a good question! (I personally never create a control by extending `Control`)
