### ISSUE TITLE
optionsFromCapabilities() treading on layer [& config] specified image format?

### ISSUE THREAD

**Issue by gknapp** [openlayers/openlayers#8636]
I'm passing a WMTS capabilities object to [WMTS.js : optionsFromCapabilities()](https://github.com/openlayers/openlayers/blob/v5.2.0/src/ol/source/WMTS.js#L291).

Near the end of the function, it builds a list of URLs. I do not have any `OperationsMetadata` in my capabilities so my URL list is empty.

The URL list is then built from the layer's collection of `ResourceURL` tags. As this is done in one function / scope, the `.forEach` used to iterate through the list is stamping on `format`. This ends up in function return result.

This behaviour doesn't match the function comment, and treads on both a) the first layer format b) the config format (if specified).

The [code in question](https://github.com/openlayers/openlayers/blob/v5.2.0/src/ol/source/WMTS.js#L435):

```js
if (urls.length === 0) {
  requestEncoding = WMTSRequestEncoding.REST;
  l['ResourceURL'].forEach(function(element) {
    if (element['resourceType'] === 'tile') {
      format = element['format'];
      urls.push(/** @type {string} */ (element['template']));
    }
  });
}
```

If this behaviour is unintended, I'm happy to raise a PR / fix.

I'm not sure if this is compounded by my resource URLs being different image formats. This means the map rendered is somewhat Frankenstein, comprised of tiles of differing formats.

**Comment by fredj** [comment]
@gknapp feel free to submit a pull request (ideally with a new test in https://github.com/openlayers/openlayers/blob/master/test/spec/ol/source/wmts.test.js). Thanks!
