### ISSUE TITLE
Polygons remain on map visually after being removed

### ISSUE THREAD

**Issue by ffxsam** [openlayers/openlayers#8649]
I found a bug where if I click a polygon to edit it (and the style changes), and then I remove the feature, it remains on the map visually (even though `VectorSource.getFeatures()` doesn't list it). Once I click on the map, it vanishes.

My workaround is to set the opacity to zero before removing it, so it's not visible, as it's strictly a cosmetic artifact.

```js
feature.setStyle(
  new Style({
    image: new ImageStyle({ opacity: 0 }),
  })
);
this.vectorSource.removeFeature(feature);
```

**Comment by cs09g** [comment]
or try to call `map.updateSize` method.

**Comment by uct8086** [comment]
> I found a bug where if I click a polygon to edit it (and the style changes), and then I remove the feature, it remains on the map visually (even though `VectorSource.getFeatures()` doesn't list it). Once I click on the map, it vanishes.
> 
> My workaround is to set the opacity to zero before removing it, so it's not visible, as it's strictly a cosmetic artifact.
> 
> ```js
> feature.setStyle(
>   new Style({
>     image: new ImageStyle({ opacity: 0 }),
>   })
> );
> this.vectorSource.removeFeature(feature);
> ```

this method worked.
