### ISSUE TITLE
Has the binding event for 'ol/interaction/Modify' changed ?

### ISSUE THREAD

**Issue by Southjor** [openlayers/openlayers#8652]
This code can worked in openlayer4.* but not in openlayer5.*

modify.on('modifystart', function (e) {
        try {
            //给地图画布增加鼠标移动事件
            if (canvasMap.addEventListener) {
                //"mousemove"  can not worked
                canvasMap.addEventListener("mousemove", addOverlayAndRemove);
            }
            console.log('modifystart');
        } catch (e) {
        }
    });

**Comment by fredj** [comment]
I don't remember when it has changed but it works if you use `pointermove` instead of `mousemove`
