### ISSUE TITLE
Use of vendor-specific Fullscreen API causes TypeScript errors

### ISSUE THREAD

**Issue by schmidtk** [openlayers/openlayers#8660]
TypeScript 3.1 [removed several vendor-specific types](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#some-vendor-specific-types-are-removed-from-libdts), including the vendor prefixed fullscreen API (`webkitIsFullScreen`, `webkitRequestFullscreen`, etc). This is causing a number of TypeScript errors because those are no longer defined.

The recommended fix is to define them locally, as needed to meet minimum support browsers.

**Comment by fredj** [comment]
yes, it's would be nice to have this ! We could create a `types/fullscreen.d.ts` file and put all the vendor-specific types.

**Comment by schmidtk** [comment]
@fredj I have started working this, but I'm unable to assign it to myself in GitHub. Can you assign it?

And how should we approach splitting type files? I started creating `types/dom.d.ts` so the file name would correspond to where the non-vendor API is defined [in the TypeScript repo](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts), but I can organize them by browser API as well.

Tagging @tschaub in case he has design input on this.

**Comment by fredj** [comment]
I've no strong opinion on the filename. Just start with `types/dom.d.ts`, we can change it if needed
