### ISSUE TITLE
TypeScript errors caused by generics in Object signatures

### ISSUE THREAD

**Issue by schmidtk** [openlayers/openlayers#8673]
This appears to be a TypeScript bug (documented in Microsoft/TypeScript/issues/27215), so this is currently a tracking issue.

A number of TypeScript errors are caused by using generic types in Object signatures. This is most prevalent in the format stack. Here's an example error:

```
src/ol/format/GPX.js:54:7 - error TS2322: Type '{ [x: string]: T; }' is not assignable to type '{ [x: string]: { [x: string]: (arg0: Element, arg1: any[]) => any; }; }'.
  Index signatures are incompatible.
    Type 'T' is not assignable to type '{ [x: string]: (arg0: Element, arg1: any[]) => any; }'.

54 const GPX_PARSERS = makeStructureNS(
         ~~~~~~~~~~~
```

The generic type should be `Object<string, Parser>`, but TypeScript doesn't seem to resolve that.

**Comment by schmidtk** [comment]
New issue for tracking: https://github.com/microsoft/TypeScript/issues/26883

Currently in the TS backlog.

**Comment by ahocevar** [comment]
#9999 worked around these issues by adding `// @ts-ignore` to places affected by that TypeScript issue. We should revisit this when that issue is fixed.
