### ISSUE TITLE
Enhancement: Kml Filtering

### ISSUE THREAD

**Issue by aimdev** [openlayers/openlayers#8694]
Currently loading large Kml files takes a long time as all the kml items are returned.
Suggest a bounding box object be passed to filter the file to return only those items within the bounds, the bounds derived from the box coordinates of the current map view.

To prevent all items being returned at higher levels, each kml object has extra fields which defines the minimum and maximum zoom values which filter kml items can be retrieved

Bounds derived thus
var glbox = map.getView().calculateExtent(map.getSize());
var box = ol.proj.transformExtent(glbox, 'EPSG:3857', 'EPSG:4326'); 
Zoom derived thus
var zoomLevel = map.getView(). getZoom();

**Comment by ke5stl** [comment]
another kind of filtering that could be useful is allowing a path prefix to limit which items get handed back.

eg: if the kml has several folders, and you only want items from one or more of those folders (not all).

allow a regex to be given that must match the current folder path for the items within to be returned?
