### ISSUE TITLE
webgl map is blurred

### ISSUE THREAD

**Issue by q2434006** [openlayers/openlayers#8695]
When I render the map using webgl mode, the map basemap text is blurry;
![image](https://user-images.githubusercontent.com/12470760/45927562-aaa0c600-bf67-11e8-94df-9a2e21745ac7.png)
```
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="https://openlayers.org/en/v5.2.0/css/ol.css" type="text/css">
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=requestAnimationFrame,Element.prototype.classList,URL"></script>
  <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.2.0/build/ol.js"></script>
  <style>
    .half {
      padding: 0 10px;
      width: 40%;
      float: left;
    }
  </style>
</head>

<body>
  <div class="half">
    <h4>Canvas</h4>
    <div id="canvasMap" class="map"></div>
  </div>
  <div class="half">
    <h4>WebGL</h4>
    <div id="webglMap" class="map"></div>
  </div>
  <script>
    var layer = new ol.layer.Tile({
      source: new ol.source.OSM()
    })
    var view = new ol.View({
      center: [0, 0],
      zoom: 1
    })
    var map1 = new ol.Map({
      target: 'canvasMap',
      layers: [layer],
      view: view
    })

    var map2 = new ol.WebGLMap({
      target: 'webglMap',
      layers: [layer],
      view: view
    })
  </script>
</body>

</html>
```

**Comment by TaylorDale** [comment]
Been experiencing this issue with an active project for a while now and I've just tried a plain new map - doesn't fix it.

Glad someone else has pointed this out! Seems to happen no matter what.

**Comment by fredj** [comment]
Hi, the experimental WebGL renderer has been removed from the lib, see https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#drop-of-support-for-the-experimental-webgl-renderer

**Comment by TaylorDale** [comment]
Cheers. This option is getting selected for me in 5.3 by default? 

All of the maps in the demos in openlayers.com are showing blurry too.
