### ISSUE TITLE
How to get all points inside polygons?

### ISSUE THREAD

**Issue by ShahriatHossain** [openlayers/openlayers#8704]
I am using openlayers version 4.x. I need to integrate a feature in my project that I want to get all points inside a polygon. Is it possible?

Thanks in advanced.

**Comment by wallw-bits** [comment]
Use `vectorSource.forEachFeatureIntersectingExtent()` with `polygonGeom.getExtent()`. That will get you the extent shortcut for most of them. After that you will need to either implement point-in-poly yourself (there are numerous sources online for this) or use a library like https://github.com/bjornharrtell/jsts. OpenLayers only provides geometry intersection with extents.

**Comment by geocodezip** [comment]
Also asked on StackOverflow: 
https://stackoverflow.com/questions/52498982/how-to-get-all-points-inside-a-polygon-in-openlayers-4-x

**Comment by ahocevar** [comment]
Closing, sufficiently answered.

**Comment by wallw-bits** [comment]
That depends on how you constructed your point layer.
