### ISSUE TITLE
GeometryLayout docs busted

### ISSUE THREAD

**Issue by ffxsam** [openlayers/openlayers#8712]
https://openlayers.org/en/latest/apidoc/module-ol_geom_GeometryLayout.html

![openlayers org_en_latest_apidoc_module-ol_geom_geometrylayout html](https://user-images.githubusercontent.com/12532733/46050707-37c85400-c0fb-11e8-9e77-e96dba1cbe4b.png)

**Comment by ahocevar** [comment]
Sorry for that, we are having issues with the doc generation process at the moment. We are working on a new process. This issue will be fixed when done.
