### ISSUE TITLE
Cannot pan for original extent when zoomed in

### ISSUE THREAD

**Issue by kasibkismath** [openlayers/openlayers#8720]
Why cannot I pan across to the original map extent when zoomed in. When zoomed in the extent gets smaller than the original extent.

Is there any particular configuration which stops this behavior?

**Comment by IsSexy** [comment]
Could we get a code snippet? It shouldn't automatically update your extent when zooming.

**Comment by kasibkismath** [comment]
var matrixIds = new Array(14);
		for (var i = 0; i < 14; ++i) {
		  matrixIds[i] = "EPSG:27700:" + i;
		}
		
		var resolutionsArray = [896.0, 448.0, 224.0, 112.0,
            56.0, 28.0, 14.0, 7.0, 3.5, 1.75,
            0.875, 0.4375, 0.21875, 0.109375
        ]
		
      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.WMTS({
				name: "OS Maps WMTS",
                url: "<layer_uri>",
                layer: "Road 27700",
                matrixSet: "EPSG:27700",
                format: 'image/png',
                projection: "EPSG:27700",
                tileGrid: new ol.tilegrid.WMTS({
                    origin: [-238375.0, 1376256.0],
                    resolutions: resolutionsArray,
                    matrixIds: matrixIds
                }),
                style: '',
                crossOrigin: "Anonymous"
            })
        })
        ],
        view: new ol.View({
          center: [529449,189252],
          zoom: 13,
		  maxZoom: 16,
		  minZoom: 13,
		  extent: [529449-500,189252-500,529449+500,189252+500]
        })
      });
