### ISSUE TITLE
Var geometry = new ol.geom.linestring () is not supported in the new version;

### ISSUE THREAD

**Issue by zhangquans** [openlayers/openlayers#8721]
ol.js:sourcemap:1544 Uncaught TypeError: Cannot read property 'length' of undefined
    at r.e.setLayout (ol.js:sourcemap:1544)
    at r.setCoordinates (ol.js:sourcemap:2217)
    at new r (ol.js:sourcemap:2186)
    at canvas:95

**Comment by fredj** [comment]
Geometry constructor no longer accept null coordinates.
See https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#v510
