### ISSUE TITLE
svg image size is 0 on ie11

### ISSUE THREAD

**Issue by rogue2yjg** [openlayers/openlayers#8722]
> version: openlayers 5.2

var imgStatic = new ol.source.ImageStatic({
    url: 'img/House_Plan_3.svg',
    projection: projection,
    imageExtent: extent 
});
        
var img = imgStatic.getImageInternal(extent).getImage();
img.onload = function() {
    console.log('img size: ' + img.width + ',' + img.height); **// width and height is 0 on ie11**
}

**Comment by ahocevar** [comment]
Duplicate of #8700.

**Comment by Lucas0819** [comment]
@ahocevar Can I use an SVG as layer on IE11？I have set imageSize and no more IndexSizeError at all.But it doesn't work.

**Comment by ahocevar** [comment]
Yes you can. The only issue I know of is that IE11 needs SVGs with a properly set width and height and viewport size.

**Comment by rogue2yjg** [comment]
@ahocevar 
I have configured the imageSize of the ImageStatic source appropriately, and I can read the width and height of the svg in img.onload function, but the svg is not rendered on the page.
