### ISSUE TITLE
forEachFeatureAtPixel does'nt work with layer type geojson ( geometry type Polygon)

### ISSUE THREAD

**Issue by megaten** [openlayers/openlayers#8723]
Hello,
The forEachFeatureAtPixel does'nt work with layer type geojson with relase 5.13 & 5.2.0, Ok with 4.6.5

With the release 4.6. forEachFeatureAtPixel  fire when the mouse in hover the polygon, with the relase 5.2.0 it fire only on the limit of the polygon.

To test it change the Ol library from ol4 to ol5 on the script.

Hope to be useful

Megaten

[forEachFeatureAtPixel.zip](https://github.com/openlayers/openlayers/files/2422980/forEachFeatureAtPixel.zip)

**Comment by ahocevar** [comment]
The zip appears to be corrupt, but the behavior you are describing might be due to #7750, which appeared first in v5.2.0.

**Comment by megaten** [comment]
The issue is also running in 5.1.3

**Comment by ahocevar** [comment]
Please share a working demo of the issue. The zip you linked is corrupt.

**Comment by megaten** [comment]
I hope this new one is better.
[forEachFeatureAtPixel.zip](https://github.com/openlayers/openlayers/files/2423549/forEachFeatureAtPixel.zip)

**Comment by ahocevar** [comment]
This is indeed because of the change introduced with #7750. Getting hit detection on polygons that are not filled can be now be achieved by adding a fill with zero opacity:
```js
fill: new Fill({color: 'rgba(0, 0, 0, 0)'})
```

**Comment by megaten** [comment]
Ok thanks a lot ANdreas.
My new coding 
var opacityctry = 0.1;         //  Défault
var vccolor     = [0, 0, 0, opacityctry];

var poictry = new ol.style.Style({                    //************ poictry  ******
    stroke: new ol.style.Stroke({
        color: vccolor,        // forth parameter = opacity  [255,255,0,0.8]
        fill: {color: 'rgba(0, 0, 0, 0)'},               //  <====== new for 5.2.0
        width: 1
        })
    });
