### ISSUE TITLE
ImageLayer doesn't update when OverviewMap control is displayed

### ISSUE THREAD

**Issue by Inikaam** [openlayers/openlayers#8728]
Hi all,
When you use an ImageLayer with ImageWMS source and an OverviewMap control, there is something strange : 
while the overview map is not displayed, the image layer is correctly updated when you scroll or move the map.
But after dislaying it once, the overview map image is updated but not the main map image when you scroll or move the map. All server calls are done, image is returned, but not displayed. I did some trys on Firefox and Chrome, with OL 5.2.0 and 4.6.x, and seen the same bug.

Here's a feedle with it, just zoom and unzoom with overview map displayed to see the bug :
http://jsfiddle.net/Inikaam/7qkjprfa/7/

**Comment by IsSexy** [comment]
So, I assume it has something to do with calling the source from two different "maps". Once you open the overview with your original code it is constantly firing the loadstart and loadend events, solved it by having two separate sources.

Here is the updated code, works okay so far:

`var source = new ol.source.ImageWMS({
        url: 'https://ahocevar.com/geoserver/wms',
        params: {'LAYERS': 'ne:ne'},
        serverType: 'geoserver',
        crossOrigin: 'anonymous'
      });
      
var source2 = new ol.source.ImageWMS({
        url: 'https://ahocevar.com/geoserver/wms',
        params: {'LAYERS': 'ne:ne'},
        serverType: 'geoserver',
        crossOrigin: 'anonymous'
      });

source2.on('imageloadstart', function(evt) {
  console.log('loadingStart2');
});
source2.on('imageloadend', function(evt) {
  console.log('loadingEnd2');
});

source.on('imageloadstart', function(evt) {
  console.log('loadingStart');
});
source.on('imageloadend', function(evt) {
  console.log('loadingEnd');
});

var ovMap = new ol.control.OverviewMap(
  {
    collapsed: true,
    collapsible: true,
    layers: [
      new ol.layer.Image({
        source: source2
      })
    ]
  }
);

var map = new ol.Map({
  layers: [
    new ol.layer.Image({
      source: source
    })
  ],
  controls: [ovMap],
  target: 'map',
  view: new ol.View({
    extent: [14471533.80, -5465442.18, 18256396.49, -4865942.28],
    center: [16363965.145, -5165692.23],
    projection: 'EPSG:3857',
    maxZoom: 22,
    minZoom: 6,
    zoom: 8
  })
});`

**Comment by Inikaam** [comment]
Hi IsSexy,
Thanks for your help, it works fine.

But it seems i must always duplicate all layers i want to display in overview map, especially if i want see the same layers on both overview and main map. It's a problem when i add or remove layers dynamically.

I run with it for now, but thats need to be fix i think.

**Comment by IsSexy** [comment]
I'll do a deep dive into their code later today, I agree that it shouldn't be a problem, and with larger data sets I feel duplicating sources could cause issues.

**Comment by remiHau** [comment]
Hello. Did you find another fix for this issue? I have his problem in my application and I'm not confortable with the idea of duplicating sources. Thanks in advance for your help.
