### ISSUE TITLE
Freshly cloned repo is generating errors when running tests

### ISSUE THREAD

**Issue by halybee** [openlayers/openlayers#8734]
Hi!

So I just freshly cloned OpenLayers and ran the tests. I seem to have an error when executing them with Firefox: 

`Firefox 62.0.0 (Windows 10 0.0.0) ol.rendering.style.Text #render Text along an ugly upside down path, keep text upright renders text along a linestring with `textAlign: 'center'` FAILED`

 I haven't made any changes to it. The steps I've followed are these:

git clone https://github.com/openlayers/openlayers.git
cd openlayers
npm install
npm test // WORKS ✔️ 
npm test -- --browsers Firefox // has the above error ❌ 

Any idea what might be happening?

**Comment by ahocevar** [comment]
Canvas implementations of different browsers and platforms produce slightly different results, which also change across versions. In this case it's nothing to worry about. It's just that the reference image has too many differences from the rendered test result. We could raise the tolerance threshold, but then we would also risk to miss real test failures.

**Comment by benVigie** [comment]
I had the same issue in my PR https://github.com/openlayers/openlayers/pull/8637 !

Tests work well on chrome, but I have the same error on Firefox. It seems the tolerance of this test is now too low to pass the test. I exported the 2 images rendered for this test and they seems fine (test render and test difference) as you can see here https://github.com/openlayers/openlayers/pull/8637#issuecomment-422157465

**Comment by ahocevar** [comment]
Pull request with a fix that increases the tolerance for that test welcome.

**Comment by benVigie** [comment]
Perfect ! I can make a new PR with the updated tolerance soon 😄

**Comment by fredj** [comment]
fixed with #8740
