### ISSUE TITLE
how to get 'intellij idea' tip when writing the code in  openlayers5 and angular 6 

### ISSUE THREAD

**Issue by sbjw** [openlayers/openlayers#8745]
In the last few days, I've been combining openlayers 5 with angular 6 use development tool “intellij idea”. The code was run, but when writing the code has no tip in 'intellij idea'.

Then  I run the code

`npm uninstall ol`
`npm install @type/openlayers`
`npm install  openlayers`

The 'intellij idea' has tip when writing the code.

english is very best, forgive me!.

**Comment by fredj** [comment]
See #9178
