### ISSUE TITLE
Type Error related to RenderFeature

### ISSUE THREAD

**Issue by wallw-bits** [openlayers/openlayers#8751]
ol/renderer/vector.js contains this:
```javascript
/**
 * @param {import("../render/ReplayGroup.js").default} replayGroup Replay group.
 * @param {import("../Feature.js").default|import("../render/Feature.js").default} feature Feature.
 * @param {import("../style/Style.js").default} style Style.
 * @param {number} squaredTolerance Squared tolerance.
 */
function renderFeatureInternal(replayGroup, feature, style, squaredTolerance) {
  const geometry = style.getGeometryFunction()(feature);
  if (!geometry) {
    return;
  }
  const simplifiedGeometry = geometry.getSimplifiedGeometry(squaredTolerance);
  const renderer = style.getRenderer();
  if (renderer) {
    renderGeometry(replayGroup, simplifiedGeometry, style, feature);
  } else {
    const geometryRenderer = GEOMETRY_RENDERERS[simplifiedGeometry.getType()];
    geometryRenderer(replayGroup, simplifiedGeometry, style, feature);
  }
}
```
There's a `tsc` error on the `getSimplifiedGeometry` call: 
```
src/ol/renderer/vector.js(133,30): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type '((squaredTolerance: number) => Geometry) | (() => RenderFeature)' has no compatible call signatures.
```
That particular error can be fixed in `RenderFeature`, but it causes more errors down the line. The root cause is that `RenderFeature.getGeometry()` and `RenderFeature.getSimplifiedGeometry()` both return the `RenderFeature` type rather than a `Geometry`. The call to the `renderGeometry` function there is specifically typed as `Geometry` and not `RenderFeature` (and cast to `SimpleGeometry` in that function).

Any suggestions on the best way to address this?

**Comment by ahocevar** [comment]
What about changing the signature of the `renderGeometry` function in `src/ol/renderer/vector.js`, so it also accepts a `RenderFeature`?
```js
/**
 * @param {import("../render/ReplayGroup.js").default} replayGroup Replay group.
 * @param {import("../geom/Geometry.js").default|import("../render/Feature.js")} geometry Geometry.
 * @param {import("../style/Style.js").default} style Style.
 * @param {import("../Feature.js").default|import("../render/Feature.js").default} feature Feature.
 */
function renderGeometry(replayGroup, geometry, style, feature) {
```
If that does not work, we'd need to create a new geometry parent class that only has a `getFlatCoordinates()` method.

**Comment by ahocevar** [comment]
That looks a bit odd indeed. In this case I'd say the cast to `SimpleGeometry` down the line is the most pragmatic option we have.
