### ISSUE TITLE
WebGLRenderingContext problem

### ISSUE THREAD

**Issue by Shekenix** [openlayers/openlayers#8752]
Hello, I have found a webgl error. To reproduce the problem, just move the map until the image disappears from the view. Error occurs only with custom projection (proj4) of the static image.

Video:

http://lowcysniezyc.pl/wp-content/uploads/2018/09/screencast-codesandbox.io-2018.09.30-00-01-14-1.webm

and Codesandbox:

https://codesandbox.io/s/ol06x3m1nz

Thank you and please help me.

**Comment by Shekenix** [comment]
I think, i have found a solution. If image is outside the window, the image parameter returns null, so webgl can't create a texture. I don't know that this try is the right direction, but if i have replaced Your code in a Context.js by the following lines, error disappears. (i just create transparent image 
instead of returning null in the image parameter)

`export function createTexture(gl, image, opt_wrapS, opt_wrapT) {
  var texture = createTextureInternal(gl, opt_wrapS, opt_wrapT);
  if(image){
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, image);
    return texture;
  }
  else{
    var img = new Uint8Array([ 255, 0, 0, 0 ]);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, img);
  }
  return texture;
}`

**Comment by Shekenix** [comment]
Can You fix this error in the new library version?

**Comment by jahow** [comment]
Hi,

The next version will not include a webgl renderer for image layers, so the issue will not be present anymore. Depending on your needs, you will have the possibility to use webgl rendering for edge cases and/or custom layer types.
