### ISSUE TITLE
Should we get rid of instanceof checks?

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#8771]
Reviewing pull requests that fix TypeScript type errors, I saw that `instanceof` checks were introduced in many places. Although it's a clean and readable way to check whether a value we get is what we expect, I'm a bit concerned about this for two reasons:

 1. **Performance**: some of our `instanceof` checks (e.g. event conditions for move events in `ol/events/condition.js`) are executed very often, and according to https://jsperf.com/duck-vs-instanceof they are 3 times slower than duck type checks.

 1. **Environments where the  [ol](https://npmjs.com/package/ol) package is used in multiple versions**: In these cases, `instanceof` checks will not return true when the constructors are from different versions of `ol`. We have seen this problem often in the past e.g. with `ol/Style` instances created by third party libraries (e.g. the [ol-mapbox-style](https://npmjs.com/package/ol-mapbox-style) package). 

What do others think? Should we try to get rid of `instanceof` checks?

**Comment by fredj** [comment]
+1 to remove them

**Comment by gberaudo** [comment]
I think it would be great to limit them as calls to `instanceof` require importing the tested class. For example it creates a circular dependency:
```
(!) Circular dependency: node_modules/ol/src/ol/source/Vector.js -> node_modules/ol/src/ol/featureloader.js -> node_modules/ol/src/ol/source/Vector.js
```

In many cases duck typing should be enough.

**Comment by ahocevar** [comment]
Ok, I'm working on a pull request.
