### ISSUE TITLE
Vector Tile Edges Clipping Markers

### ISSUE THREAD

**Issue by pjdufour** [openlayers/openlayers#8775]
When using a VectorTile layer (with GeoJSON vector tile source), the circle markers for points are cutoff on the tile edge.  Use of `renderBuffer` and  `renderMode` have not discernible effect.  Screenshot below.  Happy to provide more information if neeed.

```
        var vectorLayer = new ol.layer.VectorTile({
            source: vectorSource,
            style: function(feature) {
              return new ol.style.Style({
                image: new ol.style.Circle({
                  radius: 8,
                  fill: new ol.style.Fill({color:'rgba(0,0,255,0.8)'}),
                  stroke: new ol.style.Stroke({color: 'black', width: 2})
                })
              });
            }
          });
```

![image](https://user-images.githubusercontent.com/1438253/46381234-6bfbc180-c673-11e8-8466-567aa844b77b.png)

**Comment by ahocevar** [comment]
This is a problem with your vector tile source, not with OpenLayers. Neighbouring tiles need to repeat points that are close to the edge of a tile.
