### ISSUE TITLE
getRadius gives the diameter

### ISSUE THREAD

**Issue by atur** [openlayers/openlayers#8778]
getRadius function of a circle feature return the diameter and not the radius of a circle
openlayers5

**Comment by ahocevar** [comment]
Where are you seeing this issue? According to the tests, the radius is returned correctly.

Here we create a circle with a radius of 1:

https://github.com/openlayers/openlayers/blob/97f6171b4c0c4e66b7b7136d0623bc78d018020d/test/spec/ol/geom/circle.test.js#L9-L11

And here we assert that `getRadius` returns a radius of 1:

https://github.com/openlayers/openlayers/blob/97f6171b4c0c4e66b7b7136d0623bc78d018020d/test/spec/ol/geom/circle.test.js#L133-L139

**Comment by atur** [comment]
In your example above it works. In my case i have an openstreetmap layer with projection EPSG:3857. Over this layer i add a layer with the same projection in which i draw manually a circle with a radius of 500m (to draw i take for orientation the scale from openstreet map). Furthermore I add, for this test, a third layer with a predefined circle feature of 500m radius.  See [attached image](https://mdata.mnhn.lu/include/circle.png)
The manually drawed circle (bold circle) returns a getRadius() meter value which is far over 500m (+-30%). And the third test circle with a predefined radius of 500m dosent fits with the scale of 1000m. 

Does it has some thing to do with the projection?

**Comment by ahocevar** [comment]
You are measuring distances in Web Mercator coordinate space, which will never give you accurate results except on the equator.

You'll have to use the `getLength()` function from `ol/sphere` to get geodesic length measurement. See https://openlayers.org/en/latest/examples/measure.html for an example.

**Comment by fredj** [comment]
@atur does it answer you question? can we close this issue?

**Comment by FrankyBoy** [comment]
> You are measuring distances in Web Mercator coordinate space, which will never give you accurate results except on the equator.
> 
> You'll have to use the `getLength()` function from `ol/sphere` to get geodesic length measurement. See https://openlayers.org/en/latest/examples/measure.html for an example.

The problem with that answer is: getLength() does not work with Circles. https://github.com/openlayers/openlayers/blob/v6.5.0/src/ol/sphere.js#L76

So this issue is still unresolved as far as I can tell.

**Comment by FrankyBoy** [comment]
Just in case someone comes along and needs the proper solution for this: https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html

    let poly = fromCircle(geom);
    let length = getLength(poly);
    let radius = length / (2 * Math.PI);
