### ISSUE TITLE
Back and forward buttons don't work in Chrome when mouse pointer is over map

### ISSUE THREAD

**Issue by tapioko** [openlayers/openlayers#8790]
Clicking mouse's back or forward button has no effect when mouse pointer is over a map. Expected the page to change.

Test here: https://openlayers.org/en/latest/examples/simple.html (Version is currently 5.2.0)

Tested with
Chrome  69.0.3497.100 (NOT working)
Edge 40.15063.674.0 (working)
Firefox 62.0.3 (working)

**Comment by ludvigeriksson** [comment]
This is still a problem in version 5.3.3. I would expect the default behavior to be to only scroll using the left mouse button. Now the map captures all of them (left, right, scroll, back forward).
