### ISSUE TITLE
How to change the marker icon direction on map?

### ISSUE THREAD

**Issue by ShahriatHossain** [openlayers/openlayers#8791]
Dear experts,
I have integrated openlayers in one of my project where I am adding marker icons like pushpin inside of a polygon. Pushpin or marker icons adding automatically calculating the space by rows and columns inside the polygon. Is it possible to change the direction of pushpin or marker icon according to the shape of polygon? 

Has any feature in openlayers code base to make it possible?

**Comment by fredj** [comment]
You can set the rotation of a icon style with the `rotation` property:
https://github.com/openlayers/openlayers/blob/v5.2.0/src/ol/style/Icon.js#L42
