### ISSUE TITLE
Polygon intersectsExtent failure

### ISSUE THREAD

**Issue by hmdavidjunior** [openlayers/openlayers#8795]
Hi, 

I found an algorithm error on Polygons intersectsExtent that returns false in the case where it should have responded true. Here is an image attached to show the case:

![example](https://user-images.githubusercontent.com/18619965/46635116-42ceab80-cb21-11e8-8aa2-59c0fd18f2ad.png)

The logic error occurs when : 
1.  the outer ring contains the extent 
2.  there is a hole that contains all the 4 vertices of the extent
3.  the hole border intersects with the extent

To fix the problem, the method "intersectsLinearRingArray" on "ol\geom\flat\intersectextent.js" must be modified from:
```
export function intersectsLinearRingArray(flatCoordinates, offset, ends, stride, extent) {
  if (!intersectsLinearRing(
    flatCoordinates, offset, ends[0], stride, extent)) {
    return false;
  }
  if (ends.length === 1) {
    return true;
  }
  for (var i = 1, ii = ends.length; i < ii; ++i) {
    if (linearRingContainsExtent(flatCoordinates, ends[i - 1], ends[i], stride, extent)) {
      return false;
    }
  }
  return true;
}
```

to :
```
export function intersectsLinearRingArray(flatCoordinates, offset, ends, stride, extent) {
  if (!intersectsLinearRing(
    flatCoordinates, offset, ends[0], stride, extent)) {
    return false;
  }
  if (ends.length === 1) {
    return true;
  }
  for (var i = 1, ii = ends.length; i < ii; ++i) {
    if (linearRingContainsExtent(flatCoordinates, ends[i - 1], ends[i], stride, extent)) {
      if (!intersectsLineString(flatCoordinates, ends[i - 1], ends[i], stride, extent)) {
        return false;
      }
    }
  }
  return true;
}
```
After checking if "linearRingContainsExtent", all we have to do is check if the extent intersects with the hole border using "intersectsLineString" method. 

thanks

**Comment by ahocevar** [comment]
Your proposed fix sounds good. Are you able to provide a pull request? Please also add a new test with your example that shows the flaw in the algorithm.

**Comment by hmdavidjunior** [comment]
Ok, I will try.

**Comment by hmdavidjunior** [comment]
Created tests and modified as instructed. Pull request done.
