### ISSUE TITLE
Is it possible to rotate only the map not the marker icons?

### ISSUE THREAD

**Issue by ShahriatHossain** [openlayers/openlayers#8797]
I have following code to rotate the map:

var view = new ol.View({
                center: [12897114.681643894, -3757835.403069977],
                maxZoom: 19,
                zoom: 8,
                minZoom: 3,
                rotation: Math.PI / 6,
                enableRotation: true
            });

var map = new ol.Map({
            layers: [aerial, raster],
            loadTilesWhileInteracting: true,
            target: document.getElementById("map"),
            view: view,
            controls: ol.control.defaults({
                attribution: true,
                zoom: false
            })
        });

I am also adding some marker icons on the map. Now I want to rotate the map only. But when I rotate the map all the maker icons also rotating with map. I want marker icons will no rotate. Is it possible?

**Comment by ahocevar** [comment]
Not with raster layers, because these are pre-generated images. If you want icons to stay upright, you need to use vector or vector tile layers.
