### ISSUE TITLE
graticule intervals option

### ISSUE THREAD

**Issue by PBrockmann** [openlayers/openlayers#8800]
It would be nice to have a intervals option to get fix intervals for displaying a graticule.

I don't see this option from:
https://openlayers.org/en/latest/apidoc/module-ol_Graticule-Graticule.html

`intervals: [30, 10]`
would limit graticules to 30 and 10 degrees intervals only.

**Comment by cs09g** [comment]
does it mean like this? 
![07d3f4da-84dd-4593-a44d-fc7dfc96f275](https://user-images.githubusercontent.com/7428017/46856578-cb12c080-ce41-11e8-848c-fe9db77bfc85.gif)

**Comment by PBrockmann** [comment]
Thanks for this new option implemented so quickly.

@cs09g: Not what you described but rather intervals that don't depend on zoom level.
