### ISSUE TITLE
pre-defined Cluster font is ** LOST ** and replaced with Font of the Browser.

### ISSUE THREAD

**Issue by MaqSaid** [openlayers/openlayers#8802]
If I resize my map, I want the map to retain the predefined  font family/type. As soon as I start zooming the map, the text in the clusters in the map  start switch from coded font using "import TextStyle from "ol/style/text";" to the font of the BROWSER being used, which is so annoying. I want the predefined font to be always  ** RETAINED ** within the text of the  clusters for all user actions of zoom-in and zoom-out.

**Comment by ahocevar** [comment]
Please provide a live example that shows the issue.

**Comment by MaqSaid** [comment]
Till I arrange for an example, I come up with a quick solution by setting in chrome all fonts to Wingdings and instead of using one single font in code, used the alternative fonts for font as seen below
 new TextStyle({
                textAlign: "center",
                textBaseline: "middle",
                font: "13px Helvetica, Arial, sans-serif". Now if it cannot find the default font 13px Helvetica, it picks alternative font Arial instead of taking it from browser.

**Comment by MaqSaid** [comment]
@ahocevar I am answering my own question, as the problem was our Non Standard font does not seems to work in Chrome, so decided to go with the other Not standard font goes well with FireFox and Chrome, so  now ** problem is solved and would change above TextStyle as below and not bother to put alternate Standard fonts.
new TextStyle({
textAlign: "center",
textBaseline: "middle",
font: "13px My-Not-Standard Font"
