### ISSUE TITLE
Info page wmts

### ISSUE THREAD

**Issue by AllroadsNL** [openlayers/openlayers#8807]
[version and format turned around?](https://openlayers.org/en/latest/apidoc/module-ol_source_WMTS-WMTS.html)

> 

version | string | 'image/jpeg' | Image format.
-- | -- | -- | --
format | string | '1.0.0' | WMTS version.

[Example = format: 'image/png'](https://openlayers.org/en/latest/examples/wmts.html?q=WMTS)

**Comment by fredj** [comment]
@AllroadsNL Thanks for the bug report ! Will be fixed with #8808
