### ISSUE TITLE
missing binding in Snap Interaction Example

### ISSUE THREAD

**Issue by rosedo** [openlayers/openlayers#8810]
It can be reproduced in the example : http://openlayers.org/en/latest/examples/snap.html
- select LineString in the dropdown menu below the map
- draw a LineString on the map (double click to finish the line)
- check the Modify radio button below the map
- click on the LineString to select it
- check the Draw radio button below the map

In the console tab of devtools :

> Collection.js:214 Uncaught TypeError: Cannot read property 'array_' of undefined
>     at Collection.remove (Collection.js:214)
>     at Collection.forEach (Collection.js:130)
>     at Select.<anonymous> (snap.js:56)
>     at Select.e (events.js:41)
>     at Select.Target.dispatchEvent (Target.js:95)
>     at Select.BaseObject.notify (Object.js:152)
>     at Select.BaseObject.set (Object.js:171)
>     at Select.Interaction.setActive (Interaction.js:82)
>     at Object.setActive (snap.js:60)
>     at HTMLFormElement.S.onchange (snap.js:128)

Changing this line fixes the problem : `selectedFeatures.forEach(selectedFeatures.remove, selectedFeatures);`
by adding the binding `selectedFeatures.remove.bind(selectedFeatures)`

**Comment by fredj** [comment]
fixed with #8812
