### ISSUE TITLE
getCoordinates() return null in openlayers/src/ol/geom/Circle.js

### ISSUE THREAD

**Issue by mittaus** [openlayers/openlayers#8813]
### Method getCoordinates() in openlayers/src/ol/geom/Circle.js return null

Code from openlayers: https://github.com/openlayers/openlayers/blob/master/src/ol/geom/Circle.js

```javascript
 /**
   * @inheritDoc
   */
  getCoordinates() {
    return null;
}
```

My code:

```javascript
const type = feature.getGeometry().getType()
const coordinates = feature.getGeometry().getCoordinates()
console.log(coordinates) //output: null
console.log(feature.getGeometry().flatCoordinates)//output: (4) [-8579256.224871174, -1350857.2689411168, -8563485.72652561, -1350857.2689411168, __ob__: Observer]
```

**Should I return the values of the flatCoordinates property of the Circle Object?**

**Comment by ahocevar** [comment]
Wouldn’t it make more sense to use `getCenter()` and `getRadius()`?

**Comment by mittaus** [comment]
It's true that what you mention makes sense.
So the getCoordinates method in Circle.js does not add anything. It could be removed or failing to return a result such as:  `[lon, lat, radio]`

It is an opinion.
regards
