### ISSUE TITLE
5.2.0 Map unusable after setting null rotation

### ISSUE THREAD

**Issue by saedelman** [openlayers/openlayers#8814]
Doing a map.getView().setRotation() without any arguments (or passing an undefined variable) blows up the map object. All layers become blank, including any tile layers. There is no recovery possible other than reloading the page. There should be better error checking in the setRotation function to prevent this. This was a bear to track down.

**Comment by fredj** [comment]
There's no input validation in the library; it's the responsibility of the caller to provide valid parameters.

**Comment by saedelman** [comment]
This makes sense from a performance standpoint, but in this case, there is a catastrophic failure of the library from which there is no recovery. In that instance, I strongly believe we should have some sanity checking to prevent the library from blowing up.

**Comment by ahocevar** [comment]
We are in the process of completing type annotations for TypeScript. Once that is complete, you can use TypeScript with the option `checkJS: true` to validate your code at build time.

**Comment by saedelman** [comment]
Excellent.
