### ISSUE TITLE
How do I navigate the new API docs?

### ISSUE THREAD

**Issue by ablakey** [openlayers/openlayers#8819]
I'm having a very hard time navigating to the basics in the API docs now that it's changed since I last used OpenLayers a year ago. I mainly struggle to find class instance methods. 

For example, I want to figure out how to properly disconnect my `Map` object's event handlers but I can't find documentation for any methods.

Am I missing something obvious or has discoverability taken a bit of a dive?

Thank you.

**Comment by cs09g** [comment]
true, it gets very hard to find methods.

**Comment by ThomasG77** [comment]
At the moment, I use mostly OpenLayers v4.6.5 apidoc http://openlayers.org/en/v4.6.5/apidoc/ to quickly find out my way in class inheritances, methods and properties. This version of API docs misses some latest methods or options but as they mostly did not change, it's enough to wait for the doc improvements. The only annoying drawback from my viewpoint I have to deal with is the difference between (never remember the convention change):

    import Map from 'ol/Map'; // v 5.x
    import Map from 'ol/map'; // v4.6.5

**Comment by ablakey** [comment]
@ahocevar if it's a transient issue then that's completely understandable. Thank you.

@ThomasG77 I had no idea how to get to the old docs. That helps a lot. Thanks!
