### ISSUE TITLE
Feature duplicated/rendered multiple times after zooming

### ISSUE THREAD

**Issue by josh-channin** [openlayers/openlayers#8821]
[JSFiddle](https://jsfiddle.net/18xs659y/3/)

**Bug description:** I've setup an example here where I'm loading a coastal state feature class layer from a NOAA arcgis service. 

What I'm noticing, using forEachFeatureAtPixel() that **after zooming in and out**, the feature has been "duplicated" and "added the map multiple times". This is visually evident by noticing that the opacity of the feature is slowly getting less and less transparent as they are "duplicated".

In the fiddle, if you open the console, and move the mouse over the feature, you'll notice I'm logging the event for pointermove, as well as every feature at the pixel. The expectation is that there would only be one feature. However if you continue to zoom in and out, to different levels, you'll notice there are more and more features at a single pixel. 

Any additional information regarding this symptom would be most appreciated.

**Comment by ahocevar** [comment]
Looks like the service does not provide an `objectIdFieldName`, so features do not get unique ids (accessible through `feature.getId()`). So OpenLayers cannot know which features are loaded already.

You'd have to change your source to not use an extent based loader, but load all data in advance.
