### ISSUE TITLE
doc page of ol/source/State is empty

### ISSUE THREAD

**Issue by pixelatorz** [openlayers/openlayers#8823]
the doc page at: https://openlayers.org/en/latest/apidoc/module-ol_source_State.html is empty. 

Referral through: https://openlayers.org/en/latest/apidoc/module-ol_source_Source-Source.html#getState

**Comment by fredj** [comment]
The API doc is currently broken with the new TypeScript types. 
The next release should have better docs again.

**Comment by fredj** [comment]
see #8449 for more info about the new api doc
