### ISSUE TITLE
some Openlayers 3 functionalities don't work in Mozilla Firefox but they work in Chrome

### ISSUE THREAD

**Issue by peyman-ghasemi** [openlayers/openlayers#8831]
In my angularjs project, I have an Openlayers 3 map which has some utilities like drawing shapes and surface calculation of rectangles or circles, zoom and etc. this functionalities work well in chrome and old Mozilla Firefox versions but they don't work in Mozilla Firefox new versions. Is there anyone who knows what should I do ?

**Comment by cs09g** [comment]
well, I've tested [ol-3.20.1 example](http://openlayers.org/en/v3.20.1/examples/draw-and-modify-features.html) on FF developer edition. it looks working well. can you able to separate the part of ol from your project to reproduce the issue?

**Comment by aghapeyman** [comment]
Hello, thank you for your answer. I've tested this example. It works well but mine doesn't work. my openlayer version is 3.4 . do you think that it is my problem?

**Comment by cs09g** [comment]
try to reproduce your problem with [v3.4.0 example](http://openlayers.org/en/v3.4.0/examples/). it works as expected for me. with FF 62.0.3 on OSX

**Comment by aghapeyman** [comment]
I've tested these examples, but I can not see the map .
here is my screenshot
![openlayer](https://user-images.githubusercontent.com/15654005/47266563-50365d80-d545-11e8-86e2-cb6c4b462b1a.jpg)
