### ISSUE TITLE
Open Layer 3.14.1 upgrade to Open Layer 4.6.1

### ISSUE THREAD

**Issue by mitchlau** [openlayers/openlayers#8835]
Once i upgrade to Openlayer to 4.6.1 there is lots of change i have to make
However, i cannnot figure it out how to make below code work

`
  var length = Ext.getCmp('mapViewPanel').controller.getView().getMap().getInteractions().array_.length;

        for(var x=0; x<length ;x++){

            try{
                if(Ext.getCmp('mapViewPanel').controller.getView().getMap().getInteractions().array_[x].name =='initDrag'){
                    Ext.getCmp('mapViewPanel').controller.getView().getMap().getInteractions().array_.splice(x,1);
                    x= x-1;
                }
            }catch(error){
            }
        }
`
In Openlayer3 getView().getMap().getInteractions() can get ol.Collection
In Openlayer4 getView().getMap().getInteractions() can get something on the picture below
as a result, getView().getMap().[??????]  how to get ol.collection?

![screen shot 2018-10-17 at 1 07 27 pm](https://user-images.githubusercontent.com/10535856/47110301-a6d22d80-d20d-11e8-9a88-78a8eeb9e569.png)

**Comment by ahocevar** [comment]
Replace `.array_` in your code with `.getArray()`, which is part of the exported API. It is a good idea to always refer to the API documentation of the version you are using. In this case https://openlayers.org/en/v4.6.1/apidoc/.
