### ISSUE TITLE
overview map is not so intuitive

### ISSUE THREAD

**Issue by kuige** [openlayers/openlayers#8836]
First, please take a look at this example, I think it's better than OpenLayers's current overview map.

https://openseadragon.github.io/examples/ui-viewport-navigator/

In this example, the background of the overview map won't change or resize when panning or zooming in the map, it's always the thumbnail of the whole map, and I can quickly and intuitively navigate to any position, which makes it much clear and easy to understand. Plus, when dragging the rectangle box, the viewport of the map changes in real time, which results in a better experience.

So, I think OpenLayers's overview map should behave like the example above, at least adding an option for it.

**Comment by ahocevar** [comment]
You can configure `ol/control/OverviewMap` with a custom `view` already. If you create a view with `resolutions` set to an array with a single entry, you'll get the desired behavior.

**Comment by kuige** [comment]
@ahocevar Hi, ahocevar, I have set the overview map with the resolutions parameter, 

````
new OverviewMap({
    collapsed: false,
    view: new View({
       resolutions: [ view.getMaxResolution() ]
    })
 })
````

When I panning or zooming the map, the overview map is no longer resized, however, its position still changed. Did I miss something?

**Comment by cs09g** [comment]
as the example you linked, overview map is not resizable and not movable. only the square on the overview map moves as you drag the map. when you do not modify `ol.css` or use `className` for ol-overviewmap size, the overview map will be moved because map is bigger than its container.

**Comment by kuige** [comment]
I think the overview map should automatically be contained in its container, no matter what the dimensions of container are, just like css background size, `background-size: contain`, so the overview map will never 'overflow' its container.

I have set the width and height of the container much bigger than the overview map using css, however, the position of the overview map still can't be locked.

**Comment by ahocevar** [comment]
What if you also configure the view's `extent` with the center of your map as both bottom left and top right, e.g. `extent: [0, 0, 0, 0]`?

**Comment by kuige** [comment]
I have set the `extent` and `resolutions` parameters of the overview map, but it's still not working.

Here is the demo: https://jsfiddle.net/sangelee/kd40t5va/

**Comment by cs09g** [comment]
`extent` doesn't work for overviewmap though. seems to be fixed? https://jsfiddle.net/kd40t5va/15/

**Comment by ahocevar** [comment]
The right way to fix this would be an option to restrict the view to an extent, as attempted in #2777 and #7062. Unfortunately both pull requests were incomplete and are now outdated. But if anyone wants to take a stab, a pull request for that would still be appreciated.
