### ISSUE TITLE
geometryWriter is not a function esriJSON

### ISSUE THREAD

**Issue by ashfaq-ahmed** [openlayers/openlayers#8839]
Hi, I am trying to store the drawn features to firebase server. I write them to json using esriJSON formatter. I works for all shapes (LineString, Polygon) but gives error when writing a Circle feature.

I have a button which triggers esriJSON conversion, here is the code
```
var esrijsonFormat = new ol.format.EsriJSON();
save.onclick = function() {
  var features = source.getFeatures();
  var v = esrijsonFormat.writeFeatures(features, {featureProjection: map.getView().getProjection()});
  writeAnnotationsData(seriesId, v); //Sends to the db
}
```
When there is no circle feature, it works fine, but if there is a Circle feature in these features, i get following error
```
Uncaught TypeError: geometryWriter is not a function
  at Function.ol.format.EsriJSON.writeGeometry_ (ol-debug.js:39355)
  at ol.format.EsriJSON.writeFeatureObject (ol-debug.js:39417)
  at ol.format.EsriJSON.writeFeaturesObject (ol-debug.js:39462)
  at ol.format.EsriJSON.ol.format.JSONFeature.writeFeatures (ol-debug.js:37358)
  at HTMLButtonElement.save.onclick (viewer.js:221)
```
Am I doing it wrong?

**Comment by bartvde** [comment]
probably not supported / implemented

**Comment by fredj** [comment]
> probably not supported / implemented

The `Circle` geometries (and the `GeometryCollection`) are not supported by EsriJSON.
See https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm

But we should not crash when trying to write geometries of this type.
