### ISSUE TITLE
Make it possible to import the library outside a browser

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#8846]
It should be possible to import `ol` modules outside a browser (e.g. in Node) without needing a DOM/HTML implementation.  This does not mean that all functionality in the library needs to work outside a browser, just that importing a module should not require DOM access.  This should be possible if all DOM related access is done lazily.

**Comment by fredj** [comment]
See also #7914

**Comment by KaiVolland** [comment]
I'll have a look at this, lets see if i can do something.

**Comment by KaiVolland** [comment]
Im not sure which way to go here.
1. Are we looking for actual code changes that add all kind of checks to the modules? 
2. Or is the usage of a polyfill package – like [jsdom](https://www.npmjs.com/package/jsdom) – what we want?

I think 1. will blow up the code but 2. might increase the build size.

**Comment by ahocevar** [comment]
@KaiVolland The goal is not to add any checks or a compatibility layer. It is simply to use functionality that depends on the DOM lazily. Not sure if many of those that are relevant are left. Good examples are `ol/has.js` and `ol/pointer/PointerEvent.js`, which access the DOM as side effects. A positive side effect of such a change would also be that these side effects get removed.

Example from `ol/pointer/PointerEvent`:
```js
/**
 * Checks if the `buttons` property is supported.
 */
(function() {
  try {
    const ev = new MouseEvent('click', {buttons: 1});
    HAS_BUTTONS = ev.buttons === 1;
  } catch (e) {
    // pass
  }
})();
```
could be changed to something like
```js
let HAS_BUTTONS;
/**
 * Checks if the `buttons` property is supported.
 */
function hasButtons() {
  if (HAS_BUTTONS !== undefined) {
    return HAS_BUTTONS;
  }
  try {
    const ev = new MouseEvent('click', {buttons: 1});
    HAS_BUTTONS = ev.buttons === 1;
  } catch (e) {
    // pass
  }
};
```
Consumers would then access `hasButtons()` instead of `HAS_BUTTONS`.

**Comment by KaiVolland** [comment]
Thx @ahocevar for the clarification. I did some further investigations and found some other relevant passages. As i'm offline until April 16 – and someone likes to work on this in the meantime – i'll leave my notes in this ticket:

-  `document` used in constructor: **Attribution, FullScreen, MousePosition, OverviewMap, Rotate, ScaleLine, Zoom, ZoomSlider, ZoomToExtent, Overlay, PluggableMap, Box, VectorTileLayer, Composite, PointsLayer, IconImage, Helper**
-  `window` used: **has.js**
- `document` used: **xml.js**
- contains IIFE that uses `document`: **webgl.js**
- imports Attribution: **control.js**
- imports xml.js: **format.js**
- imports has.js: **render.js**
- imports `pixelworks` package which uses `document`: **Raster.js**
- imports has.js: **Geolocation.js**
- contains IIFE that uses `MouseEvent`: **PointerEvent**

**Comment by ahocevar** [comment]
Thanks @KaiVolland.

> document used in constructor: Attribution, FullScreen, MousePosition, OverviewMap, Rotate, ScaleLine, Zoom, ZoomSlider, ZoomToExtent, Overlay, PluggableMap, Box, VectorTileLayer, Composite, PointsLayer, IconImage, Helper

Only relevant if any of those creates a singleton instance. Otherwise we can consider these calls lazily already.

**Comment by fredj** [comment]
Note: [`esm`](https://www.npmjs.com/package/esm) can be use to find them:
```bash
$ npm i esm
[...]
$ node -r esm src/ol/has.js
/home/fredj/code/ol3/src/ol/has.js:1
ReferenceError: window is not defined
    at Object.<anonymous> (/home/fredj/code/ol3/src/ol/has.js:40:35)
    at Generator.next (<anonymous>)
```

**Comment by ahocevar** [comment]
We have made improvements for this already. I'm removing this issue from the v6.0.0 milestone, but keep it open.

**Comment by AidasK** [comment]
Could you be more specific about those improvements? Does openlayers work now without a browser? It's a nice feature and I would like to see it in release of v6.

**Comment by ahocevar** [comment]
@AidasK See the tickets referenced here for improvements that were made. You cannot create a map without a browser, but you can use many features of OpenLayers. Like geometry operations.

If you're looking for a way to create maps on a server with OpenLayers, you can look into Puppeteer. That works well and is also used by our rendering tests.

**Comment by bjornharrtell** [comment]
I sometimes use parts of OpenLayers in Node and it works well in some cases, fx. for GeoJSON and WKT formats. But when I try to use the WFS format it looks like the base `xml` module is dependent on a browser global `document`. I'm currently trying to figure out how to rework this to be able to inject an external polyfill for `document`.

**Comment by bjornharrtell** [comment]
Should not be closed, https://github.com/openlayers/openlayers/pull/10262 is ready.

**Comment by tschaub** [comment]
When [modules](https://nodejs.org/api/esm.html#esm_ecmascript_modules) are stable in Node (perhaps with the [v14 release](https://nodejs.org/en/about/releases/)), we can add `"type": "module"` to our published `package.json`.  This will allow for direct import of modules in Node scripts (which can be done now [with `esm`](https://www.npmjs.com/package/esm)).

There will be additional work that we can do to make our modules more useful outside of a browser, but we can open specific issues for that as things come up.

**Comment by tschaub** [comment]
@ahocevar - do you think one of #10954 or this issue should still be open?

**Comment by ahocevar** [comment]
@tschaub Thanks for the pointer - I reopened #10954.

**Comment by ahocevar** [comment]
Also reopening this one, which is about importing, whereas #10954 is about rendering.
