### ISSUE TITLE
Use es6 default parameters

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#8849]
I've made some test to use the [es6 default parameters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) in the library.

For example for the `constrainRotation` function in `ol/View`:
```diff
-  constrainRotation(rotation, opt_delta) {
-    const delta = opt_delta || 0;
+  constrainRotation(rotation, delta = 0) {
     return this.constraints_.rotation(rotation, delta);
   }

 ```

This feature is supported by [Bublé](https://buble.surge.sh/guide/#supported-features) and the transformed function is:
```js
  View.prototype.constrainRotation = function constrainRotation (rotation, delta) {
    if ( delta === void 0 ) delta = 0;
    return this.constraints_.rotation(rotation, delta);
  };

```
JSDoc also supports it and adds a `Default` column in the parameters's description:
![jsdoc_default](https://user-images.githubusercontent.com/100959/47431927-45760580-d79d-11e8-9971-9295c9054f56.png)

What do you think of this?

**Comment by tonio** [comment]
:+1: Looks good. So we're sure documented default value is correct.
