### ISSUE TITLE
Suggestion: WFS-T examples within "Openlayers Examples"

### ISSUE THREAD

**Issue by rmuellerjr** [openlayers/openlayers#8854]
Just a suggestion, but can you add another example page for WFS-T in OpenLayers 5? The API examples are slim and there are tons of StackOverflow pages with people trying to piece together code (mostly Openlayers 3 - due to lack of clear examples). I'm currently trying to modify the "Editable ESRI REST" and "WFS Get" examples to get this to work. 

Thanks!

**Comment by ahocevar** [comment]
Pull request welcome. The main reason why we don't have one is because we don't have access to a reliable WFS-T service that also accepts edits. So a contributor would have to provide such a service as well.

**Comment by rmuellerjr** [comment]
Gottcha. Makes sense

**Comment by rmuellerjr** [comment]
Thanks. I was able to get the WFS-T to work with Openlayers 5. Is there a way to submit code even without an sample server/service in the interim?

**Comment by bartvde** [comment]
Maybe submit a tutorial? https://github.com/openlayers/openlayers/tree/master/doc/tutorials

**Comment by rmuellerjr** [comment]
Sure. I will get a few things cleaned up and submit that way. Cheers!
