### ISSUE TITLE
ol.style.Text  forEachFeatureAtPixel

### ISSUE THREAD

**Issue by 498056852** [openlayers/openlayers#8857]
let layer = new ol.layer.Vector({
            source: new ol.source.Vector({
            wrapX: false
            })
 });
let style = new ol.style.Style()
let newText = new ol.style.Text({
                text: 'this is a text',
                font: '13px Microsoft-YaHei',
                placement: 'point',
                textAlign: textAlign,
                fill: new ol.style.Fill({ color: fillColor}),
                backgroundFill: new ol.style.Fill({ color: backgroundFill}),
                padding: [8,8,8,8]
 });
style .setText(newText);

map.on("click", function (evt) {
  map.forEachFeatureAtPixel(evt.pixel, function(feature) {
        console.log(feature)
  })
})

when i click the feature (click the text), sometime, forEachFeatureAtPixel will return the feature, but sometime forEachFeatureAtPixel will not return the feature. the style of feature is ol.style.Text

**Comment by cs09g** [comment]
I think, you may click the background of text so it doesn't return any feature.

**Comment by ThomasG77** [comment]
You may try to play with `hitTolerance` option (see the [API detail](http://openlayers.org/en/latest/apidoc/module-ol_PluggableMap-PluggableMap.html#forEachFeatureAtPixel)) to lessened the issue.

**Comment by 498056852** [comment]
> I think, you may click the background of text so it doesn't return any feature.

no,i click the text .also, it doesn't return the feature

**Comment by 498056852** [comment]
> You may try to play with `hitTolerance` option (see the [API detail](http://openlayers.org/en/latest/apidoc/module-ol_PluggableMap-PluggableMap.html#forEachFeatureAtPixel)) to lessened the issue.

but, if we change hitTolerance  ,another layers will be influenced.

**Comment by bianji1** [comment]
I am also,when the text character number is odd ,  return the feature , esle, no return.

**Comment by bianji1** [comment]
I play with icon option of ol.style.style,the icon is a small picture(height and width is 2 
px ),the feature is return everyclick.
