### ISSUE TITLE
Feature hidden by another

### ISSUE THREAD

**Issue by sylvainbeo** [openlayers/openlayers#8866]
Hi all,
Using OL i've just noticed that if a feature hide another one (a smaller one), OpenLayers does not seem to draw the hidden feature. But the problem is if the front feature has got transparency, the hidden one still does not show...is it a bug ? 

Is there a way to force OL to draw all the features ?

Thanks.

**Comment by ahocevar** [comment]
There is no such optimization. Even the hidden feature should be drawn. Can you share a minimal live example that shows the issue?

**Comment by sylvainbeo** [comment]
@ahocevar I'm goint to try.

**Comment by elemoine** [comment]
> There is no such optimization. Even the hidden feature should be drawn. Can you share a minimal live example that shows the issue?

I provided the same answer to @sylvainbeo (whose is a colleague of mine). I am not rotted! ;-)

**Comment by sylvainbeo** [comment]
@ahocevar Well, i trying to reproduce  the case.. but cannot (works fine here : http://jsfiddle.net/u3oL8wp9/)

But here is a screenshot of my app :

Look at all the circle. The layer has got an opacity (you can see rood behind the circle). Now look at the big circle and the one overlapping it. How comes we cannot see the big one behind ? Am i missing something there ?

![image](https://user-images.githubusercontent.com/632751/47753954-9dc76e80-dc99-11e8-82d6-3dbf0c25c1b0.png)

**Comment by ahocevar** [comment]
What's happening is this: you are rendering all features fully opaque (i.e. with an opacity of 1), and then you dim down the layer by setting the layer's opacity to 0.8. Instead, you should leave the layer's opacity at the default of 1, and give the circle fill an RGBA color with 0.8 as alpha, e.g. `'rgba(125, 212, 16, 0.8)'` or `[125, 212, 16, 0.8]`.

**Comment by sylvainbeo** [comment]
@elemoine We have 4 layers, in order :
- osm
- purple lines
- purple circles
- small white circles

Rendering is vector.

@ahocevar Ok i'm going to check thaht. But in my fiddle that's exactly what i do, and i works well.

**Comment by sylvainbeo** [comment]
@ahocevar Ok, i've just tried what you proposed and it works. Thank you, and @elemoine  for the review.

I'm still confused, but i've got a solution :)
