### ISSUE TITLE
Version 4.6.4 no longer available?

### ISSUE THREAD

**Issue by GoossensMichael** [openlayers/openlayers#8890]
We use version 4.6.4 of openlayers but this version suddenly disappeared. Now we receive the following error:

```
GET https://openlayers.org/en/v4.6.4/css/ol.css net::ERR_ABORTED 404 
GET https://openlayers.org/en/v4.6.4/build/ol.js net::ERR_ABORTED 404
```

Version 4.6.5 is still available though but we still need 4.6.4

Is this an error or are we forced to upgrade?

**Comment by ThomasG77** [comment]
Related to https://github.com/openlayers/openlayers.github.io/commit/adbe2872b226e5de92e9324b7513034df788bfcb
I already provided a similar answer for a near similar issue https://github.com/openlayers/openlayers/issues/8331#issuecomment-401632460
