### ISSUE TITLE
openlayers 5.3.0: Uncaught TypeError: imageStyle.getImageState is not a function

### ISSUE THREAD

**Issue by levu42** [openlayers/openlayers#8894]
https://github.com/openlayers/openlayers/blob/7321541de83db157de38417cc83e32bd3eca397d/src/ol/renderer/vector.js#L103

    Uncaught TypeError: a.getImageState is not a function
    at Ua (vector.js:103)
    at e.renderFeature (VectorLayer.js:404)
    at e.<anonymous> (VectorLayer.js:353)
    at e.prepareFrame (VectorLayer.js:370)
    at e.renderFrame (Map.js:159)
    at e.renderFrame_ (PluggableMap.js:1232)
    at e.<anonymous> (PluggableMap.js:191)

with this JS code to generate a style:

    var drawCanvas = document.createElement('canvas');
    // ... some drawing on the canvas is done ...
    return [new ol.style.Icon({
      img: drawCanvas,
      crossOrigin: 'anonymous',
      imgSize: [drawCanvas.width, drawCanvas.height]
    })];

**Comment by ahocevar** [comment]
Not sure what you're doing with the array from the above snippet. If that's the return of a style function or what you pass to `setStyle()`, it's wrong. You have to return an `ol.style.Style` (or an array thereof), which should look like this:
```js
return new ol.style.Style({
  image: new ol.style.Icon({
    img: drawCanvas,
    crossOrigin: 'anonymous',
    imgSize: [drawCanvas.width, drawCanvas.height]
  })
});
```

**Comment by levu42** [comment]
@ahocevar oh, okay, yes, I used this as a style, didn't know I have to put it into an ol.style.Style. Okay, then it's my fault, sorry!
