### ISSUE TITLE
Printing the map - scale line and overlay issues

### ISSUE THREAD

**Issue by aalices** [openlayers/openlayers#8898]
I want my map component to be printable and to contain its scale line and an overlay if currently visible. I am using `object-fit: cover` CSS rule so it fits nicely no matter what paper size is chosen. It all works well on Chrome however on Safari and Firefox the scale line is not in the right size and what's more my popup which is controlled by an Overlay is not positioned correctly. I also tried to use of this piece of code https://github.com/openlayers/openlayers/pull/6908#issuecomment-311806140 so the map i scaled correctly. This breaks stuff on Chrome and does not help in other browser.
Example from Firefox:
1. What the map looks like (I moved it a bit so the reference for scale line is clear):
![image](https://user-images.githubusercontent.com/8770183/48207038-13090280-e370-11e8-9d96-479f7026bed8.png)

2. Generated PDF that should be printed later:
![image](https://user-images.githubusercontent.com/8770183/48207109-3e8bed00-e370-11e8-8c4d-94e903d16e14.png)

As you can see the popup is far away from the red point and scale line is not the same as in web browser. Has anyone solved a problem like this?

ol version: 5.1.3

**Comment by bernhardreiter** [comment]
To give a hint: If this scale line is an official OL function, this could be a defect. A next step would be to get a problem report that has a minimal code setup to show the problem (and with the most current OL version).

As for the main problem: What I've read and tried so far let me believe: printing via the browser's printing capabilities cannot be controlled in all aspects. You gain more control when using a client side javascript library like jsPDF as in this example https://openlayers.org/en/latest/examples/export-pdf.html

**Comment by bernhardreiter** [comment]
Note a related issue seems to be https://github.com/openlayers/openlayers/issues/8066. However the solution proposed there is something that still might be a problem according to your report.
