### ISSUE TITLE
MousePosition control stops updating coordinates if mouse is pressed

### ISSUE THREAD

**Issue by anthonn** [openlayers/openlayers#8899]
The control for showing the mousepointer current position, MousePosition, stops updating the coordinate if the mouse is down.

In this example if dragging the point around, the coordinate stays stuck until mouse and feature is released.

Now 'mousemove' is used to update MousePosition, problem could be solved by instead listening on 'pointermove'. Could this be the solution?

I also found that if listening to the event "document.onmousemove" outside of ol, the added listening function will not be triggered if the mouse is down over the map. But if pressing the mousebutton outside of the map the function is still triggered. Might instead be this that is the source of the problem?
I have really tried to find why this is happening, but could not find it.

https://stackblitz.com/edit/typescript-ddawzn?file=index.ts

Tested on win 10, Chrome 70.0.3538.77 (Official Build) (64-bit)

**Comment by anthonn** [comment]
Dummy comment in order to keep issue active,

**Comment by anthonn** [comment]
Dummy comment in order to keep issue active,

**Comment by ahocevar** [comment]
This issue has been fixed with the removal of our custom pointer events abstraction (#9888).
