### ISSUE TITLE
Impossible to specify tilegrid for renderer

### ISSUE THREAD

**Issue by Zuzon** [openlayers/openlayers#8907]
Hello. I'm using a raster reprojection functionality. Most of my layers have custom resolutions, but renderer is working only by default tile grid, and maps are blurry, because of renderer tileGrid and reprojected map tilegrid mismatch.
So, now renderer is calling map tiles by single tileGrid, which is default by projection and not editable.
Is there any chance, to set custom tileGrid for renderer?
P.S. I'm using custom view zoom by resolution (not level), that why i need precise zoom toggle.

One more moment. If layer have custom resolutions which are very 'close' to each other - renderer could skip some zoom level, and never show it. So i think it's a bug

**Comment by Zuzon** [comment]
Any chance to solve this problem?

**Comment by ahocevar** [comment]
Maybe, if you can provide a minimal example in a CodePen or similar that shows the issue.
