### ISSUE TITLE
problem with rotation number

### ISSUE THREAD

**Issue by BasieP** [openlayers/openlayers#8935]
Hi there..

I am playing with rotations (simply by moving map with alt-shift and rotating it)
But I ran into a 'bug' or weirdness..

When i rotate to the left (ccw) i sometimes get a view rotation of -0.1, and sometimes 6.1...

Also, when i rotate to the left and back, i sometimes get a rotation of more then 6.5 (which is more then 2 * Pi)

Documentation says it returns a number in radians. Now i am not a math prof, but aren't radians numbers between 0 and 2 * Pi?

It's kinda hard working with a number if i don't know the bounderies.. Right now (to check if you swapped the map 180 degrees) i have to use the Modulus operator to make sure i get normal values.
I do something like 

```javascript
const rot = view.getRotation();
while (rot < 0)
    rot = rot + 2 * Math.PI;
rot = rot % (2 * Math.PI);
```

so is it hard to put something like that in the openlayers code? so i won't have to do it all the time?

**Comment by ahocevar** [comment]
This should be fixed indeed. Something similar is done already for rotation animation:

https://github.com/openlayers/openlayers/blob/9163558511715d5f391388e949110fecfc414198/src/ol/View.js#L469

The same could be done in `setRotation()`, then the view's rotation state would never exceed the allowed range. Would you be willing to create a pull request?
