### ISSUE TITLE
Label disappears  after remove then add a vector tile layer

### ISSUE THREAD

**Issue by oterral** [openlayers/openlayers#8945]
All in the title.

How to reproduce:
- open https://codesandbox.io/s/84zv4m3r7j
- open the console then choose the sandbox JS context in the list at top-left
- Execute:
 
```
var layer = map.getLayers().item(0);
map.removeLayer(layer);
```

- Wait the layer is removed

- Execute:

```
map.addLayer(layer);
```

-----> labels disappears for the current zoom level.

**Comment by ahocevar** [comment]
Fixed in master.

**Comment by oterral** [comment]
Nice thx !!1
