### ISSUE TITLE
Decluttering does not work for multipolygons

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#8954]
When rendering multipolygons on a vector layer with `declutter: true, overflow: true`, all labels for a multipolygon are rendered. This can be reproduced with a modified `vector-layers` example:
```diff
--- a/examples/vector-layer.js
+++ b/examples/vector-layer.js
@@ -15,6 +15,7 @@ const style = new Style({
     width: 1
   }),
   text: new Text({
+    overflow: true,
     font: '12px Calibri,sans-serif',
     fill: new Fill({
       color: '#000'
@@ -27,6 +28,7 @@ const style = new Style({
 });
 
 const vectorLayer = new VectorLayer({
+  declutter: true,
   source: new VectorSource({
     url: 'data/geojson/countries.geojson',
     format: new GeoJSON()
```

**Comment by ahocevar** [comment]
This is fixed.

**Comment by jhwegener** [comment]
What is the expected behaviour for decluttering on mulitpolygons? I would expect, that labels are visible, if nothing collides with the box around each label, but it seams, that only one box is created around all labels:
https://jsfiddle.net/janhenningwegener/rnhk8jw5/60/ (see red box around labels "A multi polygon")

**Comment by ahocevar** [comment]
The expected current behaviour is for a multipolygon to be treated as one geometry, with a bounding box that covers the labels for all its parts.

**Comment by jhwegener** [comment]
Ok, I don't understand why this is handled like this. One bug in this behaviour is, that this is working only, if all parts of the multipolygon are visible. If e.g. only one part is visible, the bounding box of only this label is used. You can see this, if you pan the map in the fiddle a bit.

**Comment by ahocevar** [comment]
I'm not saying it is good behaviour, I'm just saying it is the current (expected, implemented) behaviour.

**Comment by ahocevar** [comment]
If you have a change in mind that does not negatively affect performance, a pull request would be welcome.

**Comment by jhwegener** [comment]
The change in my mind is easy to say: Make an own label bounding box for each polygon of the multipolygon. Then the decluttering should work as I expect it.
The only problem with a PR: where are this coordinates for the bounding box coming from. Can't find the place in the code. Only see them at this place in Executor.js, where the box for the R-tree is put together. Perhaps you can give me a hint?

**Comment by jhwegener** [comment]
Thx for fixing this issue!
