### ISSUE TITLE
iOS Total canvas memory use exceeds the maximum limit

### ISSUE THREAD

**Issue by Farkal** [openlayers/openlayers#8956]
We are developing an application with multiple layers (raster images). 
When I try to render our application on an Ipad if I try to display only tow layers and zoom in and zoom out i get 'Total canvas memory use exceeds the maximum limit (256 MB)'
I try with http://openlayers.org/en/latest/examples/canvas-tiles.html and i get the same error after zooming in and out some time.
I get the same result on my MacBook but it take more time because the limit is (2151 MB).
It's linked with the last webkit update -> https://github.com/WebKit/webkit/commit/5d5b478917c685e50d1032ccf761ca53fc8f1b74#diff-b411cd4839e4bbc17b00570536abfa8f
So is there a workaround ? (Using WebGL ? it's not really good with raster images. Limit cache size ?)

EDIT:
After some investigations it's seams linked with projection:
On this exemple -> https://openlayers.org/en/latest/examples/simple.html?q=simple I can move, zoom etc... when I check the safari dev console no other canvas are created.
But on this exemple -> https://openlayers.org/en/latest/examples/canvas-tiles.html all the canvas of the tile debug are created and make the app crash after some time.
So i think it's related with tiles reprojected.
Same with this exemple: https://codepen.io/unhurried/pen/KrKjKN if I move on the left map everything is fine but if I move on the right map there is a lot of canvas creation.

**Comment by fredj** [comment]
Internally, OpenLayers is caching the tiles in a [TileCache](https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/source/Tile.js#L75) with a default size of 2048 items.

This could explain why the canvas-tiles example crashes the browser. Is it better if you reduce the size ?
```js
// ...
new ol.layer.Tile({
  source: new ol.source.OSM({
    cacheSize: 12
  })
})
// ...
```

**Comment by Farkal** [comment]
It change nothing, the function seems to never get called (i put console log inside and nerver saw it) even with **cacheSize: 12**.

**Comment by fredj** [comment]
`this.context_` contains `CanvasRenderingContext2D`, the code to set the size to `0` should be:
```js
const context = this.context_[key];
context.canvas.width = context.canvas.height = 0;
```

**Comment by Farkal** [comment]
Yes but this doesn't change the fact that this function is never called :confused:

**Comment by ahocevar** [comment]
@Farkal Then you're not saturating the cache. I've set a breakpoint in that function and it gets called very soon when navigating around in a vector tile map (e.g. the mapbox-vector-tiles example). It won't be called in the canvas-tiles example. For that one you'd have to patch things differently:
```js
import Tile from `ol/Tile`;

const disposeInternal = Tile.prototype.disposeInternal;

Tile.prototype.disposeInternal = function() {
  if (this.canvas_) {
    this.canvas_.width = this.canvas_.height = 0;
  }
  disposeInternal.call(this);
};
```

**Comment by Farkal** [comment]
Ok I found the problem with no saturation that was because I didn't set the projection for VectorTileSource (our server only serve EPSG:4326 tiles so didn't think I need to specify it).
So with the projection disposeInternal is raised in VectorImageTile.
Your code work for computer but no for the iPad. It work with one VectorTileLayer with cacheSize: 25. But I have 3 VectorTileLayer and when I add the others it's raise the limit (256Mo).
If I reduce cacheSize when i zoom and unzoom I get empty tiles.
I also get lot of random crashes that close my debug console on the mac so it's hard to debug (thanks Apple).
After more investigation I find the pixelRatio was 2 on the iPad and generate tile of 4Mo so i reduce it to 1 and get tiles of 1Mo. Then i could increase the cache size and display all my layers.
But it's much more laggy (than my vector implementation) and I still get random crashes :confused:

**Comment by jeroenvheel** [comment]
I also have this error on my iPad i tried to change the pixel ratio because on the iPad it is set to 2 and when I force it to 1 I can zoom and pan a little longer.

I’m using a WMS layer

**Comment by jeroenvheel** [comment]
Try the pixel ratio @NathanNovak

**Comment by NathanNovak** [comment]
@jeroenvheel can you give me an example?

**Comment by soberdor** [comment]
Same issue, a built-in solution for this would be extremely helpful! (That's the final hurdle that separates our project from using custom-styled vector tiles)

**Comment by ahocevar** [comment]
@soberdor Yes we could do that. Any takers for a pull request?

**Comment by ahocevar** [comment]
I am currently working on better tile caching to avoid this issue.

**Comment by sc0ttdav3y** [comment]
I have verified that the issue remains on OpenLayers 6.0.1 for iOS 12 and iOS 13. It's certainly better, but it's not gone. 

We are experimenting with different `cacheSize` attributes and it does seem to have an effect, although it also makes the UI crappier.  

I'm doing it experimentally at present, but perhaps one of the more knowledgeable OL devs can work out a ratio of tiles to canvas MB, so we can then work out the highest `cacheSize` for a given amount of RAM (e.g. 224M is your iPad Air or iPad Mini).

**Comment by Peter-Optiway** [comment]
Why is this issue closed, i still have this issue, and once you run out of Canvas Memory you get alot of `null reference errors` and everything gets broken.

**Comment by ahocevar** [comment]
@Peter-Optiway We cannot work around this iOS limitation in the library any further. So what you have to do is put some extra effort into the layer organisation of your map. Use as few layers as possible at a time. Also make sure to use the latest version (v6.4.x), where we have reduced the default `cacheSize` even further than before. And don't set a custom `cacheSize`.

**Comment by Peter-Optiway** [comment]
Hi @ahocevar thanks for your fast response, i managed to get access to a Mac and i think i found way to lower the amount of canvases for `VectorTileSource` and `VectorTileLayer`, it seems to create canvases for tiles that don't have any features on them, in my case 704x704 pixels and each of them eat 1.89 MB memory, and it seems about half of my tiles are empty.

**Comment by ahocevar** [comment]
@Peter-Optiway Setting the canvas width and height to 1 there sounds like a good change. Feel free to submit a pull request for that.

Regarding empty tiles handling, I think that would be tricky and add a lot of extra case handling in many places.

**Comment by mfacca** [comment]
@ahocevar I still have problems with ImageLayer and TileLayer on my iPad (iOS 12 and Safari 12.5). I noticed that in classes ol/reproj/Image.js and ol/reproj/Tile.js there is a disposeinternal method, so I tried to dispose the canvas in that method but I obtain an error at runtime, because the canvas is used somewhere even if the Image has been disposed.
Therefore I avoided to dispose the canvas but I just set the size to 0. All runtime errors disappeared, my iPad is happy. but when I pan or zoom in the map my image service disappears while loading the new image.

**Comment by Peter-Optiway** [comment]
I rewrote our entire vector layer handling to only use one OLLayer, this solves the issue more or less, we still get canvas errors but they are almost non existent.
One major drawback is that when one "layer" changes all vectors has to be redrawn...

**Comment by mfacca** [comment]
@Peter-Optiway  My problem is about ImageLayer. In my opinion there is a memory leak about canvases not released correctly.
I believe further investigation by the developers is needed. I don't have enough experience in OpenLayers source code.

**Comment by mfacca** [comment]
> @Peter-Optiway We cannot work around this iOS limitation in the library any further. So what you have to do is put some extra effort into the layer organisation of your map. Use as few layers as possible at a time. Also make sure to use the latest version (v6.4.x), where we have reduced the default `cacheSize` even further than before. And don't set a custom `cacheSize`.

I apologize for my insistence but I think the question should be reopened because there is room for improvement.
As mentioned before, I modified the source code of ol/reproj/Image.js and ol/reproj/Tile.js and disposed the canvas in the method **disposeinternal**. The result is that on iPad the error about memory use limit disappeared.
The problem is that I don't have enough knowledge of ol source code, so I don't know how to apply code changes in the right way.
I hope some developers can take my suggestions into account.

**Comment by ahocevar** [comment]
You are right, this is a known issue with image layers, that was introduced with v6. See #9578.

**Comment by ahocevar** [comment]
@mfacca Regarding disposal of canvas `ol/reproj/Image` and `ol/reproj/Tile`, we'd appreciate a pull request. You could even apply the changes directly inside GitHub, using "Edit" when viewing the respective file.

**Comment by mfacca** [comment]
> @mfacca Regarding disposal of canvas `ol/reproj/Image` and `ol/reproj/Tile`, we'd appreciate a pull request. You could even apply the changes directly inside GitHub, using "Edit" when viewing the respective file.

Thank you very much for your reply. As I mentioned before, if I dispose the canvas I obtain an error at runtime because somewhere it is used even if it is disposed. If I set the size to zero all errors disappears but wher I pan or zoom the map the image disappears unteel it is reloaded. And I can't go any further. I hope someone who has a better understanding of ol source code can help. 
In the meantime I will study the source code, maybe I can correctly make the necessary changes.

**Comment by xsfavisf** [comment]
Hello, I am experiencing the same problem with the latest version of OL 6.12.0. Has anyone found a solution ?

**Comment by t-muko** [comment]
Hello everyone,
WebGL raster image renderer seems to work well even with multiple image and vector layers. See my reply in #12908 [issuecomment-1023572875](https://github.com/openlayers/openlayers/issues/12908#issuecomment-1023572875l)

I still don't know what is the root cause for the crash with the raster tile layer. Maybe it is memory issue after all?

**Comment by xsfavisf** [comment]
After several days of testing I have found a workaround to try to always keep the canvas memory below its maximum limit to avoid rendering problems in the VectorTile layers, I have created a pull request here:

[https://github.com/openlayers/openlayers/pull/13321](url)
