### ISSUE TITLE
Bézier curve supports for vector layer

### ISSUE THREAD

**Issue by schedul-xor** [openlayers/openlayers#896]
Why don't vector layers support Bézier curves? I would like to know if there is/was a critical reason.

**Comment by ChouGary** [comment]
ol3 have turf.along  example
http://openlayers.org/en/latest/examples/turf.html?q=turf
you can try turf.bezier
http://jsfiddle.net/ntkuqe2a/

http://turfjs.org/docs/#buffer

**Comment by fredj** [comment]
Duplicate of #5582
