### ISSUE TITLE
Proposal - publish an index in Collection remove event

### ISSUE THREAD

**Issue by roemhildtg** [openlayers/openlayers#8961]
Right now, there doesn't appear to be any way to get the index of the removed element. 

```javascript
collection.on('splice', (collectionevent) => {
     const index  = collection.getArray().indexOf(collectionevent.element);
})
collection.on('remove', (collectionevent) => {
    // no way to get index of removed element
})
```

The use case would be lets say I have a list of elements for layers. If one layer gets removed, I'd like to update that list by removing the index of the list element that should be removed. But that's not really possible without some sort of index property. 

This proposal would add the `index` to the collectionevent's, so that I can automatically get the index for inserted and removed elements. 

Thoughts?

**Comment by fredj** [comment]
Hi @roemhildtg,

It's a good idea ! see #8964
