### ISSUE TITLE
drawImage slow in tile layer renderer when rendering lower z tiles or when rotating

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#8971]
The current implementation of the tile layer renderer creates a canvas 1.5 times the size of the viewport when using lower z tiles, and even bigger when rotating.

This causes a significant slowdown in rendering performance for HiDPI tiles, i.e. for vector tiles and for raster tiles when the server provides them (e.g. the `wmts-hidpi` example). 

The slowdown is caused by too much time spent in drawImage operations, which occur with every render frame.

To reproduce the issue, just open the `mapbox-style` example, which initially is set to z 11.6. Panning is very slow at the initial zoom (which triggers a 1.5 scale), but when zooming to an integer zoom level (e.g. with +/-), which results in a canvas with the size of the viewport, panning is smooth again. The same can be observed when rotating, and the result is worst when at the initial zoom and rotated.

The previous implementation did have a large canvas too (the intermediate canvas), but that was only recreated when its tile range did not contain the full viewport, and not with every render frame.

@tschaub, do you have an idea for a fix of the current implementation, or do we need to go back to using an intermediate canvas?

**Comment by tschaub** [comment]
If too many drawImage calls are the problem, we should be able to demonstrate it with a raster tile layer.  Not denying there is an alt solution, just questioning the problem.

**Comment by tschaub** [comment]
Reading again, it sounds like wmts- hidpi might demonstrate the problem.

**Comment by ahocevar** [comment]
Right. wmts-hidpi, when modified to use 100% of the browser window, shows the problem too.
