### ISSUE TITLE
build ol

### ISSUE THREAD

**Issue by stephanebury** [openlayers/openlayers#8979]
Thx for ticket  #8949 but I cannot build ol.js.
I Have taken the package.json from the trunk to the last release v5.3.0.
This is the same thing with the trunk.

the shx module create the build directory and do the unix command but when i do 
npm run build-legacy the script is blocked in the generate index
![image](https://user-images.githubusercontent.com/19145310/48698925-99330d80-ebe8-11e8-9b0e-f8357becafcf.png)

Could you help me please, id'like to contribute to ol.

Thx.

**Comment by ahocevar** [comment]
Thanks for reporting your findings here. This is a bug in https://github.com/openlayers/jsdoc-plugin-typescript. It uses node's `path.join()` to generate the JSDoc module path, but should either use `path.join.posix()` or replace `\` with `/` in the result.

If you want do provide a fix, a pull request there would be appreciated.

**Comment by stephanebury** [comment]
the pull request is in jsdoc-plugin-typescript openlayers/jsdoc-plugin-typescript/pull/1

Thx

**Comment by ahocevar** [comment]
Thanks @stephanebury! I have just published v1.0.3 of [`jsdoc-plugin-typescript`](https://npmjs.com/package/jsdoc-plugin-typescript). Can you please try if the issue is fixed for you with that?

**Comment by stephanebury** [comment]
Sorry for the delay.
Thx @ahocevar. The issue is fixed.
