### ISSUE TITLE
New Feature Proposal

### ISSUE THREAD

**Issue by joldenb** [openlayers/openlayers#8986]
I recently implemented a specific solution to allow users to drag labels around and draws a line from the label back to the map feature, for the purposes of clarifying labels that may be overlapping. The decluttering option for vector labels only partially worked for my needs.  Here is an example:
![image](https://user-images.githubusercontent.com/5224522/48731514-74e02c80-ebfa-11e8-8a8c-d7771af699b8.png)

If it would be useful to people, I can generalize the solution and submit it as a pull request.

**Comment by marcjansen** [comment]
Looks quite nice. I think at least an example without too much code is justified. If you'd be so kind to submit one, that would be awesome. TIA.

**Comment by am2222** [comment]
looks great it would be nice if you please share your solution too

**Comment by joldenb** [comment]
Awesome! I will work on putting this together and get back to you. Thanks,
Joe
