### ISSUE TITLE
<input> in the overlay can't work

### ISSUE THREAD

**Issue by callmegaga** [openlayers/openlayers#8993]
**Describe the bug**

When I add a \<input type="text"\> in the overlay,the \<input\> can't be focused,so I can't input anything with it.
I have test it work well at openlayers with version 5.1.3, but on 5.2.0, it can't work.

**To Reproduce**
Here is my code:

var element = document.getElementById("popup");
var popup = new Overlay({
        element: element,
        positioning: 'bottom-center',
        stopEvent:false,
    });
my_map.addOverlay(popup);

$('#popup').attr("data-content","\<input type='text' \>");

$('#popup').popover({
            'placement': 'top',
            'html': true,
});
$('#popup').popover('show');

When the overlay show on the map ,I click the input but the input can't be the input state,so i can't input anything

**Comment by tschaub** [comment]
Try the same without `stopEvent: false`.  See https://codesandbox.io/embed/o5v9jo76pq for an example.

The next release of the library dispenses with the `stopEvent` handling.

**Comment by moon9sky** [comment]
I have try without  stopEvent: false, the \<input\> work right,But I need to listen to the click event on the map DOM,So I have to set stopEvent: false.

**Comment by wwwYing** [comment]
> Try the same without `stopEvent: false`. See https://codesandbox.io/embed/o5v9jo76pq for an example.
> 
> The next release of the library dispenses with the `stopEvent` handling.

Is this a bug?Should we fix this?
