### ISSUE TITLE
ForeachFeatureAtPixel with thousands points.

### ISSUE THREAD

**Issue by Shekenix** [openlayers/openlayers#8997]
It is posible to disable some Feature components in foreachFeatureAtPixel? This function is slow for thousands coordinates made by Point component or even Multipoint coordinates with different coordinate styles. I dont need mapping all Feature components on the map. Do You have any solution?

I don't need filtering features in foreachFeatureAtPixel but exclusion from mapping.

http://lowcysniezyc.pl/wp-content/uploads/2018/11/ro.jpg

**Comment by hucbmz** [comment]
遇到了同样的性能问题，有解决方案吗
