### ISSUE TITLE
Code Intellisence In VSCode

### ISSUE THREAD

**Issue by GISerWYJ** [openlayers/openlayers#8999]
I'm using VSCode to integrate ol@5.3 in my angular application, I installed the ol package through npm, seems it can't have auto imports or code intellisense for ol package, but when i copy any one the file in ol source(let's say Layer.js) to my project folder, auto imports or code intellisense are automaticlly enabled, why ? is the vscode issue or ol package issue? thank you!

**Comment by WoShiSunWuKong** [comment]
I have the same confusion.

**Comment by ahocevar** [comment]
The reason why the `ol` package does not work with IntelliSense is because it is transpiled to ES5, so TypeScript does not recognize the classes.

For the next release, there will be two packages: one transpiled to ES5, and another with the original sources and fully TypeScript/JSDoc annotated.

**Comment by WoShiSunWuKong** [comment]
> The reason why the `ol` package does not work with IntelliSense is because it is transpiled to ES5, so TypeScript does not recognize the classes.
> 
> For the next release, there will be two packages: one transpiled to ES5, and another with the original sources and fully TypeScript/JSDoc annotated.

Which date is planned to be updated v5.4? thank you

**Comment by ahocevar** [comment]
v6.0 will be released in February. In the meantime, you may want to try what I suggested in https://github.com/openlayers/openlayers/issues/8448#issuecomment-441777821.
