### ISSUE TITLE
render() in reproj.js ignores original context options

### ISSUE THREAD

**Issue by xylosper** [openlayers/openlayers#9001]
**Describe the bug**
One can customize canvas context in "precompose" event.
For instance, one can disable antialiasing:

```js
layer.on("precompose", evt => { 
    evt.context.imageSmoothingEnabled = false
})
```

When using ImageStatic source with projection, redner() in reproj.js is called for mapped triangulation.
In render(), new context for canvas is created inside, and everything user set in "precompose" event just ignored.

**To Reproduce**
1. Use Image layer with ImageStatic source with non-EPSG:3857 projection
2. DIsable antialiasing in "precompose" event for the layer
3. The static image is still antialiased

**Expected behavior**
The antialiasing in static image should be disabled.

**Comment by ablakey** [comment]
I spent hours tracking down why my draw tools suddenly stopped showing the blue pin/lines while drawing. I can't exactly piece together why it happened, but commenting this out fixed the issue. 

```
this.map.on('precompose', (evt: any) => evt.context.imageSmoothingEnabled = false);
```

 I then tried with the related PR patch and the issue went away. Leaving this comment here for the next poor soul who searches for this problem.

Thanks for reporting and the related fix.

ol/interaction/Draw Draw draw marker invisible missing empty interactions
