### ISSUE TITLE
setExtent VectorTileLayer renderMode vector

### ISSUE THREAD

**Issue by Farkal** [openlayers/openlayers#9007]
**Describe the bug**
When using setExtent on VectorTileLayer (with VectorSource on MVT format) if I set the renderMode image or hybrid the extent work. But if I set renderMode to vector (and i need it today) the extent stop work (it's seems waiting for pixel, when I zoom out i saw all my points and when I zoom in they disappear).

**To Reproduce**
1. Create VectorTileLayer
2. Set renderMode to vector
3. Call setExtent() on VectorTileLayer

**Expected behavior**
Setting the extent from lon lat box like when the renderMode is image.

**Comment by ahocevar** [comment]
Thanks for the bug report. `vector` render mode has been removed from the library. What were your reasons to use `vector` mode?
