### ISSUE TITLE
GeoRSS Parser

### ISSUE THREAD

**Issue by adjenks** [openlayers/openlayers#9011]
_Originally posted by @bartvde in https://github.com/openlayers/openlayers/pull/1250#issuecomment-33111620_

Do you plan on still adding this feature? I would like to use it.

**Comment by ThomasG77** [comment]
> Do you plan on still adding this feature?
Can't answer on this point but you don't need to wait for GeoRSS support.
You may look at https://gis.stackexchange.com/questions/291943/where-is-the-georss-feature (disclosure:I wrote the answer) to solve the issue.

**Comment by adjenks** [comment]
@ThomasG77 Thank you. I was going to look for something like that.
