### ISSUE TITLE
TileArcGISRest.getTileUrlFunction() returns unbounded function

### ISSUE THREAD

**Issue by spazzarama** [openlayers/openlayers#9015]
It appears a recent change has reintroduced returning an unbounded function from `UrlTile.getTileUrlFunction()` similar to #4695. The change is here:
https://github.com/openlayers/openlayers/blame/85abe3695a48b10e26a9bbf95144e81e5888f448/src/ol/source/UrlTile.js#L73

This causes a problem when working with ol.source.TileArcGISRest and using getTileUrlFunction() - specifically this breaks how ol3-google-maps interacts with tile sources.

This is because the `this.tileUrlFunction` property is overwritten by the original unbounded `options.tileUrlFunction` later in the constructor by the call to `setTileUrlFunction`. Perhaps the call to setTileUrlFunction is now superfluous?

**To Reproduce**
1. Go to http://jsfiddle.net/py0r67h1/
2. The code will attempt to retrieve the getTileUrlFunction from the TileArcGISRest source and call it directly
3. See error in console, or in alert (caused by this being undefined)

**Expected behavior**
The result from UrlTile.getTileUrlFunction() should be bound to this, so that subsequent calls work correctly.

**Comment by spazzarama** [comment]
It actually looks like the commit that I reference correctly removes the call to setTileUrlFunction from the constructor, however it was added in again by this one: https://github.com/openlayers/openlayers/blame/aad836dfb2d09ee98627f3c8b3630888c503d94c/src/ol/source/UrlTile.js#L88

**Comment by ahocevar** [comment]
Thanks for sharing your findings, they made it easy to find and fix this issue. See #9020.
