### ISSUE TITLE
Changes in the map?

### ISSUE THREAD

**Issue by djdenki** [openlayers/openlayers#9016]
I haven't seen any option to request a change in the map... that is why I write here..

At this location: Rudolf-Diesel-Straße 21, 97424 Schweinfurt, Deutschland

There should stand: Hartmann Rollladen & Sonnenschutz GmbH

Can you fix this please?

**Comment by ahocevar** [comment]
Please go to https://openstreetmap.org/. If you have an account there, you can make changes yourself. Note that changes you make there are subject to moderation.
