### ISSUE TITLE
about resolution

### ISSUE THREAD

**Issue by zhouyaxi** [openlayers/openlayers#9017]
I used getResolution() in my program ,and code is map.getView().getResolution(),console.log in browser.I got different number(float) in different zoomlevel.when the zoomlevel is 3,tthe result is  0.17578125 ,if zoomlevel is 4, the results is  0.087890625.I want know how to calculate(get) the result number！

**Comment by jahow** [comment]
The resolution of a map is the ratio of projection units to screen units. If one pixel covers a 4 meter x 4 meter square, the resolution will be 4.

**Comment by zhouyaxi** [comment]
> The resolution of a map is the ratio of projection units to screen units. If one pixel covers a 4 meter x 4 meter square, the resolution will be 4.

Now I'm going to draw a circle with a given radius,and the circle should change its radius with the zoomlevel change!how  to do it?
