### ISSUE TITLE
map view OSM reprojection translate/shifts coordinates when building with angular-cli

### ISSUE THREAD

**Issue by AnthonNilsson** [openlayers/openlayers#9019]
When using the ol/source/OSM with angular everythin works good when in development mode or building without the buildOptimizer flag set.

This is the start image of the project:
![image](https://user-images.githubusercontent.com/7062803/49233828-251e1400-f3f7-11e8-962b-b2362118a686.png)

The view:s center is set to the middle of Stockholm.

But if building the project with angular-cli and using the optimization, aot and buildOptimizer flags on this will instead be the startup view of the project:
![image](https://user-images.githubusercontent.com/7062803/49234032-8e058c00-f3f7-11e8-9450-1a1c6ec96d42.png)

The center of the map is now shown approx. 5 km away from before. Mostly north of the original position. 
Points and lines will also be shown in the wrong position compared to the underlying OSM map.

The only difference between the two examples is the buildOptimizer that is false in the first example and then true.

I supply my code here, to reproduce:
npm install
npm run build (with buildOptimizer set to true or false in angular.json)

[ol optimization problem.zip](https://github.com/openlayers/openlayers/files/2629879/ol.optimization.problem.zip)

**Comment by AnthonNilsson** [comment]
I think this problem started to show when I updated from ol 4.6.5 to 5.3.0

**Comment by AnthonNilsson** [comment]
Thanks for the reply @kzc. I have really little time to do anything right now so I will have to come back with those files later. I guess you saw that all files for reproducing the bug is supplied already. There is no unminified version as you pointed out though.

**Comment by kzc** [comment]
If you generate the `dist - buildOptimizer true - unminified` directory as described above and it does not work then it's an `angular-cli` problem. Otherwise create a ticket in the `terser` project and post a link to that generated directory with the (working) generated unminified files.

**Comment by fegyi001** [comment]
I also suffered from the same problem with OSM layer (also with BingMaps) using an Angular production build with the cli. I did some OL code research and it seems that I finally managed to solve the problem with the following import:

`
import { addCommon as addCommonProjections } from 'ol/proj.js';
`

And before you initialize the map, run it:

`
addCommonProjections();
`

This implicitely adds the default OL projections to your bundle, which I guess are omitted during the tree-shaking.

Hope that works!

**Comment by AnthonNilsson** [comment]
@fegyi001 That did the trick! Big thanks!

I only added the rows you supplied and then the little test project I supplied here started to work. I will try this later with the full app, but really should work there also.

**Comment by marcjansen** [comment]
@fegyi001 or @AntonNilsson we probably need better docs here. Do you think you can help us by providing a PR?

**Comment by kzc** [comment]
> import { addCommon as addCommonProjections } from 'ol/proj.js';
> And before you initialize the map, run it:
> addCommonProjections();

Looking at the code below, `import "ol/proj.js";` ought to be enough shouldn't it? 

https://github.com/openlayers/openlayers/blob/97ab5133a093d319e0219ccf52e28ce880461860/src/ol/proj.js#L500-L510

But if the project works correctly without the workaround in development builds it suggests that this module is already implicitly loaded which should run `addCommon();` as a side effect. This calls into question whether the array form of webpack `sideEffects` is working correctly or whether something is amiss with angular-cli build optimizer and pure annotations or something.

https://github.com/openlayers/openlayers/blob/97ab5133a093d319e0219ccf52e28ce880461860/package.json#L111-L114

**Comment by ahocevar** [comment]
@marcjansen This issue was fixed with #8893, so with future releases this workaround won't be needed any more.

**Comment by AnthonNilsson** [comment]
@marcjansen Ok great! Thanks for the input.

**Comment by karlvr** [comment]
We had a similar issue using `gulp-uglify` 3.0.1, it produced a version of OpenLayers 5.3.0 that included decimal places in the `x` component of the map tile URL, which resulted in 404 responses from [a-c].tile.openstreetmap.org.

We resolved this using the Uglify options:

```
compress: {
	collapse_vars: false
}
```

We tried the fix above (`addCommonProjections()`), however it didn't resolve the issue in our case. We will test again with the next OL release and investigate further.

**Comment by kaiiorg** [comment]
I got both the work around from @fegyi001 and manually adding `"proj.js"` to `ol`'s package.json to work. Both prevent the application from throwing the same error as in #8815, but now my basemap is missing despite the network request log showing successful request and delivery of the tiles (both from our local mapproxy install and the osm cdn): 
![image](https://user-images.githubusercontent.com/14365919/52978802-6e4b8780-3398-11e9-8de4-0a6180e5a5bf.png)

Any ideas on how to fix that?
