### ISSUE TITLE
[4.6.4] problem with kml  and URL() parsing in IE11

### ISSUE THREAD

**Issue by SmnDesmet** [openlayers/openlayers#9033]
**Describe the bug**
kml files can't be read by openlayers in Internet Explorer

**To Reproduce**
- Work with kml files in openlayers
- open your openlayers in Internet explorer

**Expected behavior**
It shows the kml layer in openlayers with the styles. But in Internet explorer we get the error 'SCRIPT445: Object doesn't support this action; ol.js (48752,21)'

** further explanation **
The problem here is that on line 48752 in the debug-ol.js file uses URL(). As found on https://developer.mozilla.org/en-US/docs/Web/API/URL, the URL() constructor is not supported in Internet Explorer 11.

**Comment by fredj** [comment]
See https://github.com/openlayers/openlayers/blob/master/README.md#supported-browsers

A polyfill is required for `URL`.
