### ISSUE TITLE
forEachFeatureAtPixel not detecting the geometry type properly

### ISSUE THREAD

**Issue by 0trenixjetix** [openlayers/openlayers#9048]
I got a program that each time i make a drawing it stores it in a data structure.
Then i got a listener that calls the [context menu extension](https://github.com/jonataswalker/ol-contextmenu). But to call the appropiate context menu i have to look for the appropiate feature.
The main thing is that for each feature at pixel detects a Polygon as a Point

**To Reproduce**
When the open context menu listener  fires whose code is like this:
```
contextmenu.on('open', function(evt) {
last_selected_feature = map.forEachFeatureAtPixel(evt.pixel, ft => ft, {
        hitTolerance: 10
    });
//Do things with the feature like
if (last_selected_feature && last_selected_feature.getGeometry().getType() == "Polygon" && vector.getSource().getFeatures().includes(last_selected_feature)) {
//Display context menu of polygon 
}else if(last_selected_feature && last_selected_feature.getGeometry().getType() == "Point"){
    alert("BUG in forEachFeatureAtPixel"); //this line was my initial debug 
    }
}
```
I put an alert that calls whenever the detected polygon is incorrect and it detects a Point instead of a Polygon like half of the time, especially when it didn't fire before. The second time i call the context menu it doesn't have that problem but it can detect the geometry type like 50% of the times.

The expected behavior is to have a nice menu like this:
![image](https://user-images.githubusercontent.com/8699204/49693584-401b2180-fb77-11e8-80d7-cabfc5462eb2.png)
But instead i get this because the polygon is not detected properly:
![image](https://user-images.githubusercontent.com/8699204/49693589-588b3c00-fb77-11e8-91cd-a9ab5330e0e2.png)
Having this menu means that i can work with the feature.

To solve this issue temporarily i made this:
-Given that i have each feature stored in a data structure and id that corresponds to their position. (For example: First feature gets id 0 and position 0, second feature the same). And that the deletion case i also worked out with a reset of the id's. I wrote this code that looks for the feature given that coordinate, in that pixel of the vector layer and works perfecly but it's just a patch for the forEachFeatureAtPixel bug 
```    for (var i = 0; i < featureMap.length; i++) { //Feature map is where i store the features and their info
        var coord = map.getCoordinateFromPixel(evt.pixel);
        if (featureMap[i][0].getGeometry().intersectsCoordinate(coord)) {// [i][0] is the actual feature in place i
            var back_feat = last_selected_feature;
            last_selected_feature = featureMap[i][0];
            console.log("found feature " + i);
            if (back_feat.getGeometry().getType() == "Point") {
		console.log("The output was corrected thanks to this patch");
		alert("The output was corrected, still fucked up");//Commented in production
            }
        }
    }
```
To test this behaviour i wrote the alert line and it fires like 50% of the time. 
![image](https://user-images.githubusercontent.com/8699204/49693483-8c189700-fb74-11e8-8469-73d7fa43e0f5.png)
This patch meant that the feature geometry type would be obviously correct and i would only get an alert when i corrected it instead of simply failing. 
I hope you correct this because it means much in production and the workaround is quite ugly for me.

**Comment by ahocevar** [comment]
@0trenixjetix The first feature that gets detected by `forEachFeatureAtPixel()` is the draw cursor of the draw interaction, because it is on top of the polygon. You can add a `layerFilter` to the `forEachFeatureAtPixel()` options to make sure the feature you get is from the vector layer (https://jsfiddle.net/5b1kr2cv/3/):
```js
map.forEachFeatureAtPixel(evt.pixel, ft => ft, {
  hitTolerance: 10,
  layerFilter: layer => layer === vector
});
```
Or you can change the `forEachFeatureAtPixel` callback to only return a truthy value when a polygon is detected (https://jsfiddle.net/5b1kr2cv/4/):
```js
map.forEachFeatureAtPixel(evt.pixel, ft => ft.getGeometry().getType() == 'Polygon' ? ft : null, {
  hitTolerance: 10
});
```

**Comment by 0trenixjetix** [comment]
Thank you a lot. I think we can close this issue finally.
