### ISSUE TITLE
remove cluster layer but it is still on calculating

### ISSUE THREAD

**Issue by wwwYing** [openlayers/openlayers#9049]
**Describe the bug**

I make a map with a cluster layer,and I add 200 features to the map,and update there coordinates per second.So the page have a very high cpu usage.But when I remove the cluster layer,the cpu usage doesn't reduce.

I want to know is this a bug?Or there is other way to remove the cluster layer thoroughly.

**Here is my js code**

    var vectorSource  = new ol.source.Vector({});
    var clusterSource = new ol.source.Cluster({
        source:vectorSource
    });

    var layer = new ol.layer.Vector({
        source:clusterSource ,
    });

    var map = new ol.Map({
        layers: [
            layer
        ],
        target: 'map',
        view: new ol.View({
            center: [0, 0],
            zoom: 15,
        })
    });

    var allFeatures = [];
    var count = 200;
    for (var i = 0; i < count; i ++){
        var feature = new ol.Feature({geometry: new ol.geom.Point([Math.random() * 10 , Math.random() * 10])});
        allFeatures[i] = feature;
        vectorSource.addFeature(feature)
    }

    setInterval(function () {
        for (var i in allFeatures){
            allFeatures[i].getGeometry().setCoordinates([Math.random() * 10 , Math.random() * 10]);
        }
    },1000);

    setTimeout(function () {
        map.removeLayer(layer)
    },5000);

**Comment by fredj** [comment]
This is expected: the cpu usage is more or less the same if the layer is attached to the map or not.
