### ISSUE TITLE
Earthquakes Heatmap example blur and radius inputs have no effect on Internet Explorer 11

### ISSUE THREAD

**Issue by MattiL** [openlayers/openlayers#9051]
Earthquakes Heatmap example's blur and radius inputs have no effect on Internet Explorer 11 on Windows 7 and 10.

1. Go to https://openlayers.org/en/latest/examples/heatmap-earthquakes.html with Internet Explorer 11 on Windows 7 or 10
2. Move blur and radius inputs
3. See no change

**Expected behavior**
To see the heatmap blur and radius change on moving blur and radius inputs.

**Comment by jahow** [comment]
The `input` event is not handled by IE, the example should be updated to also listen to the `change` event.
