### ISSUE TITLE
create custom polygon style from point feature

### ISSUE THREAD

**Issue by remiglobal** [openlayers/openlayers#9053]
hi

i wanted to create a custom polygon style for a point feature. So far i have tested the following code but failed. No error but nothing displayed on the map.

var myPolyArray = [[0,0],[5,0],[5,5],[0,5],[0,0]];
var featureSelectedStyle = new ol.style.Style( {

	fill: new ol.style.Fill( {color: 'rgba(192,122,192,1)'} ),
	stroke: new ol.style.Stroke({color: 'rgba(255, 204, 0, 0.2)', width: 2}),
	geometry: function(feature) {
			return new ol.geom.MultiLineString([myPolyArray]); 
		}		
} );

I have been looking at 2-3 example on geometry function but failed to understand. Am i missing something?

**Comment by jeroenvheel** [comment]
Have you seen this example?
https://openlayers.org/en/latest/examples/polygon-styles.html

**Comment by remiglobal** [comment]
yup. i did. but is the coordinates the actual coordinates or are they just some reference to the center of the feature?

i need something like in the geoserver custom wkt shapes.

**Comment by ThomasG77** [comment]
It's real coordinates. This coordinates are using Spherical Mercator coordinates with scientific notation.

**Comment by remiglobal** [comment]
is the coordinates in this example are real or reference?

https://openlayers.org/en/latest/examples/earthquake-custom-symbol.html

**Comment by remiglobal** [comment]
i have solved my problem. thanks for the responses.
