### ISSUE TITLE
getEventPixel(event) with Jquery fails due to event.changedTouches being undefined

### ISSUE THREAD

**Issue by richardjr** [openlayers/openlayers#9062]
**Describe the bug**

When calling getEventPixel(event) from a jquery event for example:

```
var container = $('#' + map.get('target'));
container.on('mousemove', function (event) {
```

getEventPixel will fail due to:

```
const eventPosition = 'changedTouches' in event ?
      /** @type {TouchEvent} */ (event).changedTouches[0] :
      /** @type {MouseEvent} */ (event);

```
Because jquery (probably incorrectly) has event.changedTouches:undefined rather than changedTouches simply not existing. Using a standard event container.addEventListener('mousemove'.. etc works fine as changedTouches does not exist as one would expect.

The commit:

https://github.com/openlayers/openlayers/commit/4a066670c2a65277eb019ae88a5f13b2db895eed#diff-f5de2651a6f7d43376464e25e8101dec

Changed from:

`const eventPosition = event.changedTouches ? event.changedTouches[0] : event;
`

Which is able to cope with this situation. 

**To Reproduce**

var container = $('#' + map.get('target'));
container.on('mousemove', function (event) {
 var mousePosition = map.getEventPixel(event);
});

**Expected behavior**

While I suspect this is a jquery issue the test of ( 'changedTouches' in event ) isn't really valid as it doesn't account for undefined/object etc and maybe should be exists && isArray.

**Comment by ahocevar** [comment]
Thanks for reporting this. Note that you could also change your code to not rely on `getEventPixel` at all:
```js
map.on('pointermove', function(event) {
  const mousePosition = event.pixel;
});
```

**Comment by richardjr** [comment]
Cheers for the tip, this actually looks much cleaner way of doing it.

**Comment by ChrisHSandN** [comment]
As this was closed without a fix, for anyone finding this issue and looking for a solution, just use `event.originalEvent` rather than the original jQuery `event`:

```
$(map.getViewport()).on('some-event', (event) => {
  map.getEventPixel(event.originalEvent);
  map.getEventCoordinate(event.originalEvent);
})
```
