### ISSUE TITLE
Ant path or route with direction

### ISSUE THREAD

**Issue by HarelM** [openlayers/openlayers#9065]
**Is your feature request related to a problem? Please describe.**
I'm currently migration out of leaflet and I have this awesome feature there - ant-path:
https://github.com/rubenspgcavalcante/leaflet-ant-path
I couldn't find any equivalent with this library.

**Describe the solution you'd like**
I know animation is problematic due to how this library is written, but I did try and implement a simple solution using an icon at the end of a segment, much like the drawing example, but it has some problems - mainly that the arrow is bigger than the path itself:
https://github.com/IsraelHikingMap/Site/issues/868

My question/feature request would be to be able to draw a path that look like one of the following two options, is it possible?
![image](https://user-images.githubusercontent.com/3269297/50004080-a4424900-ffae-11e8-9b05-5dd1f1a04c70.png)

**Comment by fredj** [comment]
See https://codesandbox.io/s/kkqo051ryo
This is a simple example that more or less implements the ant-path animation.

The `animateLineDash` function in `animate-dash.js` take a stroke style and animate the dash offset. The function is used in `index.js` (bottom of the file) and calls `vector.refresh()` to trigger a refresh of the map.

**Comment by HarelM** [comment]
Cool!!!!! I didn't know that was possible. :-) Thanks!
In any case, I'm guessing that this might be problematic in terms of performance in some cases, thus the other two options that are listed above are still interesting, I think.

**Comment by HarelM** [comment]
Any comment regarding the "dash" shape described above?
