### ISSUE TITLE
MGRS lines overlay

### ISSUE THREAD

**Issue by sergektp** [openlayers/openlayers#9069]
Hello

We’re using OpenLayers in our Angular application. Among other things we use Graticule feature to display longitude/latitude lines, and it works really well. But now we need to add an option to display MGRS (Military Grid Reference System) grid lines over the map.

As I see OpenLayers API hasn’t got anything like this. Is there a chance that I missed something? or similar feature is in plans for next releases? Thank you.

**Comment by sergektp** [comment]
@ahocevar thank you for the feedback.
I see your point: the approach would be to extend `ol/Graticule`.
But also I’m thinking about an implementation using the OpenLayers API: e.g. to add a `VectorLayer` with polygon features representing MGRS zones, cells. Would it work or could you advice better strategy on this way?

**Comment by ahocevar** [comment]
Actually a vector layer would be an even better strategy. I'd use lines rather than polygons though.

**Comment by jahow** [comment]
Please note that on master the current implementation of `Graticule` uses a vector layer with a custom loading strategy where the features (lines and text) are regenerated on each bbox change, see:
https://github.com/openlayers/openlayers/pull/8944

**Comment by sergektp** [comment]
Thank you for the answers.
I've started work on MGRS grid using the suggested approach (based on the implementation of `ol\Graticule`), made some tests. All looks clear now.

**Comment by geotom** [comment]
> Thank you for the answers. I've started work on MGRS grid using the suggested approach (based on the implementation of `ol\Graticule`), made some tests. All looks clear now.

Hi. sounds interesting. Would you share your work? I was also tasked for an OL MGRS graticule

**Comment by nboisteault** [comment]
Hi @sergektp I'm also working on MGRS with OL. Would you share some hints?

**Comment by sergektp** [comment]
Hi
I just followed the described approach: used Graticule layer as reference on how to integrate with the map. Then basically it only needs to make 
`this.createGraticule_(renderExtent, center, resolution, squaredTolerance);`
for MGRS. The function calculates lines which present borders of 500km/100km squares  and coordinate grid lines inside 100km squares. The base idea: split renderExtent into, in general case, a number of extents – for each visible UTM zone. Then project extents into UTM space. Then calculate mesh of 500km/100km squares, coordinate grids in UTM space. Then project the resulting lines from UTM.
I used proj4 to convert Mercator to UTM and back, and made all calculations regarding 500/100km squares just according MGRS definitions.

**Comment by MiArmstrong** [comment]
@sergektp I apologize for the long after the fact ping.

I was wondering, like geotom, if you would be willing to share your work on this. Barring that, I would also appreciate any advice or resources you used when building this. I'm not very familiar with OL/mapping projections and such in general, so trying to figure this out has been a pain.

**Comment by nboisteault** [comment]
Hi @sergektp Would you please share your code to make your explanation even easier to understand? :)

**Comment by nboisteault** [comment]
We, at 3Liz company, would like to pay for a complete example of Graticule with MGRS grid.
@mike-000 Could you contact me please (email in my Github profile)?

**Comment by nboisteault** [comment]
I'm currently working at extending Graticule to display a MGRS grid.
WIP (draft) here: https://github.com/3liz/lizmap-web-client/pull/3236
I hope it will help someone.
