### ISSUE TITLE
Label is not being rendered at specified coordinate on Windows Webview

### ISSUE THREAD

**Issue by bindanisairam** [openlayers/openlayers#9074]
![_thumb_331806](https://user-images.githubusercontent.com/45877965/50200637-bf310680-037c-11e9-9d0d-ff2a0b9117de.png)
On Drawing a LineString, we tried to label the distance measure as a value at midpoint of the Line String.
So created a style of Text to position of MidPoint of the LineString.
However, the style is not being rendered at the given geometry position).
The weird thing is it only happens on Windows Device(We render Openlayers on WebView).
Is there any open issue on this?

**Comment by ahocevar** [comment]
You just opened an issue ;-). Which could benefit from a code snippet or a live example (e.g. on https://codesandbox.io) that shows your code. This will drastically increase the likelihood that someone can help you with this.

**Comment by bindanisairam** [comment]
The issue is only replicable on a WebView of a JavaFX Application on a particular resolution.
Codesandbox doesn't help in my case.
Does a Sample JavaFX Application with the issue replicated be of help here?
