### ISSUE TITLE
Click, MiddleClick prevents default V5.x.x

### ISSUE THREAD

**Issue by mkmladja** [openlayers/openlayers#9088]
**Prevent default changed behavior**
I noticed that in new version of OL Maps (V5+), pointerdown, middleClick... events will add preventDefault: true. 
In previous versions preventDefault was false, but i noticed this change.
Any changes in the API that we need to know? 
```javascript
if (mapBrowserEvent.type == MapBrowserEventType.POINTERDOWN) {
        var handled = this.handleDownEvent(mapBrowserEvent);
        if (handled) {
          mapBrowserEvent.preventDefault();
        }
        this.handlingDownUpSequence = handled;
        stopEvent = this.stopDown(handled);
}
```

**Comment by ahocevar** [comment]
The code you referenced above should only prevent default when the event was handled by an interaction. You may want to try latest master, where the order of DOM-elements was changed. Also, which element were you trying to listen on for click?
