### ISSUE TITLE
Postcompose event has no context anymore

### ISSUE THREAD

**Issue by cmsdkfz** [openlayers/openlayers#9100]
A recent code refactoring is not backward compatible. Now the precompose/postcompose event has no context in it, which is clear from this line because undefined is passed in:
https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/Composite.js#L62

Is this a mistake? or intended? I have some code replying on getting the context from the event.

**Comment by oterral** [comment]
@cmsdkfz see [changelog](https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#new-prerender-and-postrender-layer-events-replace-old-precompose-render-and-postcompose-events)

**Comment by cmsdkfz** [comment]
oops, hope I had noticed that.

**Comment by cmsdkfz** [comment]
thanks so much!

**Comment by cyrilpreiss** [comment]
Hi, the dom-to-image library is not working when the map includes a vector layer, any idea how to get a map screenshot when using a vector layer ?
