### ISSUE TITLE
View propertychange "resolution" issue with Chrome

### ISSUE THREAD

**Issue by umbe1987** [openlayers/openlayers#9105]
I know this problem is probably more related to my code rather than a real BUG in OL (v5.3.0), but maybe it is related to:

- #7409
- many concurrent onclick events?

**Zooming in and out causes an error in my application**

This is my app: https://www.wondermap.it/map.html
If you try it, it works in any browsers, except Chrome.
In Chrome, an error occurs when I open the sidebar on the left, then close it and try to zoom the map.
If you do that in Chrome, you'll see that the zoom is stopped and a console error occurs. Also, if you reopen the sidebar after that (specifically the "Layers" tab), it is not rendered properly (the opacity sliders and layer legends are not present).
Keeping the sidebar open while it has this problem and zooming again in the map "fixes it" (it renders properly again).

**OK**
![immagine](https://user-images.githubusercontent.com/15016826/50891810-70b3dc80-13fd-11e9-8d57-70777c93bda0.png)

**NOT OK**
![immagine](https://user-images.githubusercontent.com/15016826/50891850-7f01f880-13fd-11e9-8998-fef6cd453b3c.png)

I am rendering this panel each time the user zooms in and out in the map using this code:

```
map.getView().on('propertychange', function(evt) {
	switch (evt.key) {
		case 'resolution':
			// get HTML elements with "layer" class
			var layer_class = document.getElementsByClassName("layer");
			// update the ToC at each zoom
			toc_scroll[0] = toc.scrollLeft; // toc horizontal position
			toc_scroll[1] = toc.scrollTop; // toc vertical position
			toc_scroll = updateToc(map, EPSG32632, ol_layers, layer_class, zoom_icons, table_icons, input_sliders, toc, toc_scroll[0], toc_scroll[1]);

			break;
	}
});
```
The `updateToc()` method is supposed to render the panel each time the resolution changes.
In Chrome, the `updateToc()` seems not to pass the `layer_class` parameter correctly, at least this is what I am getting from following the dev console errors. But I still think it might be related to the way the View `'propertychange' resolution` is working.

**Comment by umbe1987** [comment]
Sorry solved.
Yes, indeed it seemed related to #7409.
I applied the solution suggested by @ahocevar and everything now seems to work on Chrome as well!
The updated working code is:

```
function onResolutionChange(evt) {
	if (map.getView().getAnimating()) {
		return;
	}
	toc_scroll[0] = toc.scrollLeft; // toc horizontal position
	toc_scroll[1] = toc.scrollTop; // toc vertical position
	toc_scroll = updateToc(map, EPSG32632, ol_layers, layer_class, zoom_icons, table_icons, input_sliders, toc, toc_scroll[0], toc_scroll[1]);
}

```
map.getView().on('change:resolution', onResolutionChange);

**Comment by umbe1987** [comment]
Sorry to reopen this issue, but the problem seems to be there again when I zoom with two fingers on mobile or use the mouse pad to zoom fast from desktop (always with Chrome only).
Is there a better way to ensure the change:resolution event won't trigger so many times?

**Comment by ThomasG77** [comment]
Try using debouncing in JavaScript (an article about it could be https://css-tricks.com/the-difference-between-throttling-and-debouncing/)

**Comment by umbe1987** [comment]
Thank you @ThomasG77. Will let you know as soon as I am testing it. Seems really what I need.

**Comment by umbe1987** [comment]
Turns out the issue was another one, but the debounce made my code much better, not calling my functions many times while zooming.

For the sake of knowledge, I used thi project to implement the bouncing: https://github.com/johndugan/javascript-debounce
