### ISSUE TITLE
Allow to use gradient colors with LineString

### ISSUE THREAD

**Issue by jalik** [openlayers/openlayers#9113]
**Description**
I am working on an app that displays vessels routes on a map.
Since I have the speed of the vessels at each positions, I did calculate the color to represent the speed, so I have a lot of segments to color, but for now they are all with a single color which is not accurate. I did not see anything about using a gradient for Stroke, only for Fill so I would like to know if it is possible to use a gradient of 2 colors for the stroke of a LineString ?

![screenshot_20190113_231905](https://user-images.githubusercontent.com/1948429/51104254-bc61df80-1789-11e9-8f26-98a9eefa1aca.jpeg)

**Solution**
I don't know a lot about Canvas but I know from what I've seen that it's kind of low level (complex) so
not sure if it will be easy to implement, but I would like to use an array of colors (ex: `['#ff0000', '#0000ff']`) instead of a single color, or maybe it should be an array of Style.

**Comment by jahow** [comment]
I'm pretty sure you can give a linear gradient as the `color` property of a stroke style. See for example how to define such a gradient to follow a line:
http://jsfiddle.net/5e7rfx30/

The hardest part may be finding out the right coordinates to use for the linear gradient though...

**Comment by jalik** [comment]
@jahow Thank you for the code!

Before posting the issue I did some searches and I ended up to the same conclusion, using `createLinearGradient`. But I am not familiar with Canvas even if your example is clear and easy to understand, like you said the hardest part is to calculate the pixel coordinates.. (for that, I can use `getPixelFromCoordinate()`).

I tried something based on your code but it's not working because from inside the function I don't have access to the map object, which would allow me to calculate the pixel coordinates. This is a `styleFunction` so it is called by OL, I cannot even add a new argument and using a `map` variable in the global namespace is not an option, I feel like I am blocked...
```
export function createRouteStyle(feature) {
  const props = feature.getProperties() || {};
  const maxSpeedInKnots = 10;
  const lineDash = props.broken ? [5, 10] : undefined;
  let color = null;

  if (typeof props.fromSpeed === 'number') {
    const can = document.createElement('canvas');
    const ctx = can.getContext('2d');
    // todo calculate gradient coordinates based on feature.fromCoordinates and feature.coordinates
    const grad2 = ctx.createLinearGradient(150, 150, 300, 50);
    grad2.addColorStop(0,
      rgbaToString([...rgbFromValue(props.fromSpeed, 0, maxSpeedInKnots), 1.0]));
    grad2.addColorStop(1,
      rgbaToString([...rgbFromValue(props.speed, 0, maxSpeedInKnots), 1.0]));
    color = grad2;
  } else {
    color = rgbaToString([...rgbFromValue(props.speed, 0, maxSpeedInKnots), 1.0]);
  }
  return new Style({
    stroke: new Stroke({
      color,
      lineDash,
      width: 2,
    }),
  });
}

export function rgbaToString(rgba) {
  return `rgba(${rgba.join(',')})`;
}

export function rgbFromValue(value, min, max) {
  const ratio = (value - min) / max;

  function dynamicRatio(r, t) {
    let n = t * 2;

    if (r < t) {
      n = r / t;
    } else if (r > t) {
      n = (t * 2 - r) / t;
    }
    return n;
  }

  return [
    Math.round(255 * ratio),
    Math.round(255 * dynamicRatio(ratio, 0.5)),
    Math.round(255 * (1 - ratio)),
  ];
}
```

**Comment by jahow** [comment]
Well, the most common way to handle this would be to declare a reference to the map object in the closure of the style function. I'm assuming that your style function is defined in an ES6 module, so what you could do for example would be to declare the map in another module as an export, and then import it in the one with the style function.

Something like:

`map.js`
```js
let map = new Map(...);
export function getMap() {
  return map;
}
```

`stylefunction.js`
```js
import { getMap } from 'map';

const map = getMap();

export function createRouteStyle(feature) {
  // you should always have access to the map object here
  ...
```

Please note that this discussion is probably not appropriate for an issue anymore, maybe gis.stackexchange.com would be better suited :)
