### ISSUE TITLE
Zoom out button icon is incorrect when running on iOS and Android

### ISSUE THREAD

**Issue by stevechadbourne** [openlayers/openlayers#9117]
**Describe the bug**
I'm using OpenLayers v5.3.0 with Cordova across UWP, iOS and Android. A simple map with no layers displays an incorrect icon for the zoom out button on iOS and Android, although it looks correct on UWP. See image for details:

[Image showing incorrect icon](https://user-images.githubusercontent.com/4307880/51160939-00fd9000-18dc-11e9-8f86-3bf660f1cf5f.png)

**To Reproduce**
I downloaded the distro and used ol.js and ol.css directly in my app.
I created a new empty map with no layers, just a basic view and map with ol.control.Zoom()

```javascript
    const latitude = -35.214679;
    const longitude = 173.536434;
    const projectedCoords = GetSpericalMercatorFromLatLong(latitude, longitude);

    const mapView = new ol.View({
        center: projectedCoords,
        zoom: 14
    });

    window.JobPageMap = new ol.Map({
        controls: [
            new ol.control.Zoom()
        ],
        target: _mapGuid,
        view: mapView
    });
```

**Expected behavior**
Zoom out icon should be a minus symbol across all platforms.

**Comment by ahocevar** [comment]
Make sure your page's encoding is set to UTF-8. Like in the official examples, you can achieve this by setting the following in the `<head>` of your HTML document:
```html
<meta charset="UTF-8">
```

**Comment by stevechadbourne** [comment]
Thanks Andreas. That fixed it.
