### ISSUE TITLE
The extend function mutates the arrays

### ISSUE THREAD

**Issue by jktravis** [openlayers/openlayers#9119]
**Describe the bug**
Using the `extend` module mutates the arrays.

This caused me a bit of an issue when combining multiple extents in succession. Since the array is mutated, the subsequent call using the new extent resulted in an incorrect extent. 

**Expected behavior**
`extend` should return the a new array with the modified values.

A simple solution would be to copy the arrays first

```javascript
function immutableExtend(extent1, extent2) {
// copy the arrays First
  const result1 = [...extent1];
  const result2 = [...extent2];

// The rest is original code
  if (result2[0] < result1[0]) {
    result1[0] = result2[0];
  }
  if (result2[2] > result1[2]) {
    result1[2] = result2[2];
  }
  if (result2[1] < result1[1]) {
    result1[1] = result2[1];
  }
  if (result2[3] > result1[3]) {
    result1[3] = result2[3];
  }
  return result1;
}
```

**Comment by ahocevar** [comment]
This behavior is intentional and documented. If you want a new extent, simply do something like
```js
const extendedExtent = extend(extent1.slice(), extent2);
```
