### ISSUE TITLE
Dont run under windows?

### ISSUE THREAD

**Issue by xpbliss** [openlayers/openlayers#9121]
I downloads the examples,  bu i run it under windows 32bit,  it always shows some wrong:
```
SyntaxError: import declarations may only appear at top level of a module
```
Anyone tell me how to do?  thanks!

**Comment by ahocevar** [comment]
Fixed with #9103. See https://59-4974939-gh.circle-artifacts.com/0/examples/reprojection-image.html for a preview of how the examples will look from the next release on.
