### ISSUE TITLE
Type of ol.coordinate, Typescript?

### ISSUE THREAD

**Issue by michaelletzgus** [openlayers/openlayers#9122]
ol.Coordinate is defined as a 2-tupel [number, number] for the XY format.

But when reading features from GPX files feature.getGeometry().getCoordinates() returns coordinates as XYZ or XYZM. When using TypeScript accessing a c[3] gives an error since c is a 2-tupel.

So, in fact, the behavior of getCoordinates() is wrong - or its signature.

Maybe ol.Coordinate should always be a 4-tupel?

**Comment by ahocevar** [comment]
In OpenLayers, it is defined as `Array<number>` (plain JavaScript with JSDoc types). Are you using external types? Those are not maintained by OpenLayers developers.

**Comment by michaelletzgus** [comment]
I tried to use [the npm package](https://www.npmjs.com/package/ol) which suggested to install [@types/ol](https://www.npmjs.com/package/@types/ol):

`Try `npm install @types/ol` if it exists or add a new declaration (.d.ts) file containing `declare module 'ol';`

As I understood the ongoing discussions regarding TypeScript the `.d`-files are created from JSDoc.
But @types/ol (which depends on @types/openlayers) defines:

`export type Coordinate = [number, number]`

Maybe the `@types/ol` is build upon an outdated version 4.6.3?

**Comment by ahocevar** [comment]
The [@types/ol](https://npmjs.com/package/@types/ol) package is not maintained by OpenLayers. So it will probably be better to create an issue there.

Note that the "Try npm install `@types/ol` if it exists or add a new declaration (.d.ts) file containing declare module 'ol';`" message does not come from OpenLayers.
