### ISSUE TITLE
Circle click popup displaced problem

### ISSUE THREAD

**Issue by makrolika** [openlayers/openlayers#9123]
Windows 7
Firefox, Chrome (latest)
Openlayer 5.3.0

I have a difficult problem with click a circle for a popup.

The mouse-cursor is changed on hover the circle, and by this feature i see, the clickable area for the circle is displaced in southeast from the circle, outside the circle. But, not every time. That is difficult to reproduce the problem.

![ol-vector-popup-001](https://user-images.githubusercontent.com/46843149/51427230-c48ca580-1bf5-11e9-99e8-de185a86ffb2.png)

The problem is, when i write more div boxes with text in the index.html there contain the div box for the map. In maximal browser window with and high is it not, or not every time. In minimalize the browser window is it. But, when i delete the div boxes with the text, is it not, or not every time. Browser window move/resize on Screen have effect? CSS position:absolute; have effect? There is not every time in southeast, is it many times in east, or only minimal displaced.  Myself don't understand the problem.

Here is a example: https://next.plnkr.co/edit/2E8AZLqTPf2iqI7W

OK, I don't know enough about Openlayer, but I need exactly this feature to display database content. This is not a problem so far, only this thing with the displacement breaks my project.

**Comment by makrolika** [comment]
I found ...
https://stackoverflow.com/a/51589258/9068374
Is there a safe solution? I'm not sure.

Put this on the end in the html/php file:

```
<script>
map.updateSize();
</script>
</body>
</html>
```

**Comment by ahocevar** [comment]
The problem with your markup and css is that your map container does not have a dimension. The css says width and height are 100%, but there is no parent container with any dimension, so width and height are undefined. Once you have fixed that, the problem should be resolved. When using a framework that adjusts container sizes, you'll need to listen to events that notify when the container of the map has resized, and call `map.updateSize()` in these listeners.
