### ISSUE TITLE
Autopan popup with image does not move as expected

### ISSUE THREAD

**Issue by hhaeb** [openlayers/openlayers#9125]
The popup do not move complete inside the map on first click when the popup contains a image. On a second click it moves as expected inside the map.

If i remove the images, the popup moves as expected and is seen compete inside of the map div on the first click.

go to:
https://www.hohenloher-perlen.de/index.php?id=restaurants-gaststaetten
click on the upper most icon and you will see half of the popup. CLick again it will come up complete.

Try other icons. If you try again a icon which you have seen before, it will move complete.

It seems ol calculates the size of the popup without calculating the image size. 

Tested on 4.6.5 and 5.3.0

**Comment by ahocevar** [comment]
Autopan only works if the size of the popup content is known. When the popup markup contains an image without `width` and `height` set, the size of the popup content will be unknown before the image has finished loading. So you'll need to preload the image before opening the popup.
