### ISSUE TITLE
Offline-tiles like OSMAnd with OpenLayers

### ISSUE THREAD

**Issue by makrolika** [openlayers/openlayers#9126]
Hello, i search for a solution to use offline-tile-maps like from OSMAnd with OpenLayers.

The problem is the loading of the tiles in the browser from the OSM server, when the files (html, css, js) are on my lokal computer stored. Since last year the loading of OSM tiles is lame to extremly lame to fall asleep. Not every time, but not rarely.

The use of offline tiles when creating an OL project can relieve the OSM server.

```
var map = new ol.Map({
    layers: [
      new ol.layer.Tile({
        source: new ol.source.OSMAnd(localmaps/tilefiles/germany.obf)
      })
    ]
});
```

**Comment by ahocevar** [comment]
The OSMAnd format is probably not a good choice, because there is nothing out of the box in OpenLayers that can handle them. You'll probably want to look into mbtiles instead.

However, the approach of loading a whole tileset through the browser is probably not a good idea. It is easy to set up your own server to serve tiles that OpenLayers can request with `ol/source/XYZ`.

You may find this resource helpful: https://gis.stackexchange.com/questions/202119/osm-offline-tiles-mbtiles-in-openlayers.

**Comment by makrolika** [comment]
I think the best way is to find a way to use the OSMAnd tiles packages, or similar

**Comment by ahocevar** [comment]
Please close this ticket if you're happy using a third-party library and a custom loader in OpenLayers.

**Comment by makrolika** [comment]
Restart this Issue, because it is not already solved for my interests.

For many years, I had coded few very simple really Android Apps. Thats very difficult and I have stopped it. To this time, it exists a methode to transform HTML pages to an App and I had make few with that. This methode don't exist longer.

Currently, I code HTML pages including OpenLayers Map and display it with a Simple Server App. That works fine and its free for all to use it. But I must use offline PNG Tiles and that is too much (1 GB) for a small territory and only few zoom levels. Just unzipping the tiles on the smartphone, which are in a zip file for copying, takes hours! So, for that, I search a methode to use like OBF Files wich in OSMAnd. The requirement is: use it offline. It must be work simple for users of my HTML-Apps with Maps.

**Comment by jahow** [comment]
You could take advantage of the PMTiles format and have a local `.pmtiles` file which will then be partially requested by the map when navigating. See https://openlayers.org/en/latest/examples/pmtiles-image.html

**Comment by ahocevar** [comment]
I've made good experience with Service Workers and downloading tiles for offline use by simply sending a GET request to the url for each tile, using [`tileGrid.forEachTileCoord`](https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_TileGrid-TileGrid.html#forEachTileCoord).

**Comment by makrolika** [comment]
@jahow , please post a working example. You have a Cross-Origin problem.

@ahocevar , and how do you use the downloaded tile files? Eventually so:
```
var mapsource = new ol.source.XYZ({
	attributions: '© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="nofollow">OpenStreetMap</a> contributors.',
	url: '../ol/tiles/png/{z}/{x}/{y}.png',
	wrapX: false
});
tileLayer.setSource(mapsource);
```
Thats my way already. But I search a better way with using like *.obf files.

**Comment by ahocevar** [comment]
@makrolika With service workers, you just use the original URL as if you were online.

I think in your case, a combination of both suggestions would be best: use a pmtiles file, host it on a server, use a service worker to cache it, and download the whole pmtiles file to the service worker cache before going offline.

**Comment by makrolika** [comment]
@ahocevar , you have understand my issue right?

I search for a methode to use OSM Tiles offline. Like local `'../ol/tiles/png/{z}/{x}/{y}.png'` without thousands of Tiles but with one file like *.obf or *.mbtiles or *.pmtiles, but really OFFLINE, in Maps wiht (my) layers, wich can use for everyone (local on PC or local on Smartphone) - real offline, completelly offline, without internet connection.

The map softwares use for this a `fetch()` (XHTTPRequest) and with that nothing works local/offline, because Cross-Origin. It is forbidden to request local files, except images with `<img src="">` and grab the image from that to canvas map. But that don't work with other files than images.

**Comment by jahow** [comment]
the `pmtiles` file needs to be served over HTTP, at least one initial time for it to be downloaded in the service worker; you cannot render a map using tiles coming from a `file://` url, unless you run your browser in unsafe mode and disable CORS.

**Comment by makrolika** [comment]
I know. And it work also not with a HTTP Server App on Android (tested). Cross origin is the big problem. Consider: The Maps are not only for me, but for all and also for people with nothing knowledge. It is a 100 % autark map without internet connection. It works, with thousands of offline tiles, but not so easy and it is not so easy to install it.

**Comment by ahocevar** [comment]
@makrolika Yes I understand your issue. CORS is something you can control on the server.
