### ISSUE TITLE
why does my vectorLayer has no ability of  rendering to much points on the map ?even more than 34 points

### ISSUE THREAD

**Issue by dengzengjian** [openlayers/openlayers#9134]
updatePointLayer() {
      this.pointLayer.setSource()
      var features = [];
    
      var mapInfo=[];
      for(let i=0;i<40;i++ ){
        mapInfo.push(this.mapInfo[i])//this.mapInfo  is an Array which contains much coodinates
      }
      mapInfo.forEach(element => {
        if (
          typeof element.LNG != "undefined" &&
          typeof element.LAT != "undefined" &&
          element.LNG !='0'&& element.LAT!='0'
        ) {
         
          var lat=Number(element.LAT),lng=Number(element.LNG)
          var pointFea=new Feature({geometry:new Point(proj.fromLonLat([lng,lat]))})
          pointFea.set("lng", Number(element.LNG));
          pointFea.set("lat", Number(element.LAT));

          // pointFea.getStyle().setText(new Text({text:element.gcmc,offsetY:20}));
          pointFea.setStyle(
            new Style({
              image: new Circle({
                radius: 8,
                fill: new Fill({
                  color: "red"
                })
              })
            })
          );
         
          features.push(pointFea);
        }
      });
      var vectorSource = new sVector({
        features: features
      });
      
      this.pointLayer.setSource(vectorSource);
    }
 at the firsr the points are not show and many debugger has been ruled out , at last,i try to decrease the quantity of the points, when the points was 34 ,the point rending well, but beyond the quantity ,nothing points was show. is anybody could  help me solve the problem ,thanks a lot

**Comment by ahocevar** [comment]
Hard to guess from your code, but if you run your updatePointLayer() function often, then that is what makes your application slow. By default, we have an icon cache size of 32 icons. When you always create a new Circle style, you saturate that cache all the time. So you should define the Circle style only once.

**Comment by dengzengjian** [comment]
> Hard to guess from your code, but if you run your updatePointLayer() function often, then that is what makes your application slow. By default, we have an icon cache size of 32 icons. When you always create a new Circle style, you saturate that cache all the time. So you should define the Circle style only once.

thanks for your help ,i have found that problem is cause by the data  of Json Format which coms from the background program
