### ISSUE TITLE
Rendering artefacts when changing style of a tile layer

### ISSUE THREAD

**Issue by walkermatt** [openlayers/openlayers#9135]
**Describe the bug**

I've been working with [ECMWF](https://www.ecmwf.int/) who are moving an application to OpenLayers. The application displays weather forecast via a `TileWMS` source and  `Tile` layer; users are allowed to switch style for any given layer. With `v5.3.0` and current `master` the user sees a flash of the previous style before tiles for the current style load if they zoom in, change style then zoom out.

I believe this is caused by `interimTile`s for the previous style being displayed and `ol/source/Tile~Tile#forEachLoadedTile` not checking the `tile.key` when checking if tiles are loaded.

**To Reproduce**

* Open https://codesandbox.io/s/8yq67pv11j
* Once the tiles have loaded, zoom in
* Change to the alternative style
* Once the tiles have loaded, zoom out
    * At this point you will see a flash of the previous style before tile for the current style load

**Expected behaviour**

When a user has interacted with the map then changed style only tiles with the same key should be rendered avoiding flashes of previous styles.

This [patched example](https://wms-tiled-switch-style-gf9lsgswz.now.sh/) attempts to fix both issues and behaves as expected. I'm used a locally packaged version of the `ol` package based on `master`.

In the example I'm patching `ol/Tile~Tile#getInterimTile` to disabling `interimTile`s (for all tile sources ATM which isn't ideal but proves the point) and 
patching `ol/source/Tile~Tile#forEachLoadedTile` to ensure that only tiles with the same key as the source are considered loaded.

The source can be seen here: [src/index.js](https://zeit.co/AdxvSHVwRENbFyNqkf1Ut3DZ/wms-tiled-switch-style/gf9lsgswz/source?f=src/src/index.js)

I'd be very happy to contribute fixes for both issues. My current feeling is that there two changes:

* Implement the option to disable `interimTile`s for a given tile source
* Update `ol/source/Tile~Tile#forEachLoadedTile` as in the example to only consider a tile loaded if it's `key` matches the source key.

Would you be happy for me to open pull requests for each?

**Comment by fredj** [comment]
See also #9136 (when the url is changed)

**Comment by walkermatt** [comment]
@fredj the issues highlighted are improved in current `master`, when building against `v5.3.0` there is still a flash of the previous style even with `interimTile`s disabled and the change to `forEachLoadedTile`.

**Comment by walkermatt** [comment]
@fredj I'm happy to prepare a couple of pull requests to address these issues if you think that's appropriate?

**Comment by ahocevar** [comment]
@walkermatt Did #9201 improve the situation? If not, please submit pull requests to address these issues.

**Comment by walkermatt** [comment]
@ahocevar I've just tested against a build based on the latest master and the issues are still evident; I'll prepare a couple of pull requests.

**Comment by ahocevar** [comment]
@walkermatt I thought this through again, and I think what you suggest regarding interim tiles makes sense, but the other way around - use interim tiles by default, but provide a way to delete them. With my changes in #9250, all you need to do in your application is call `source.clear()` before `source.updateParams()`. Will that work for you? Maybe you can also take a look at #9250 to see if everything is properly documented.

**Comment by ahocevar** [comment]
Waiting for feedback from @walkermatt. Did my suggestion above in combination with #9250 work for you?

**Comment by walkermatt** [comment]
@ahocevar yes, thanks. Calling `source.clear()` before `source.updateParams()` does the trick 👍

I guess in our case we could always sub-class the source to call `clear` when `updateParams` is called.

**Comment by walkermatt** [comment]
I've updated the test map to use current master and to use a subclassed `TileWMS` so that `clear` is called before `updateParams`: https://wms-tiled-switch-style-61mnfer4e.now.sh/ all looks good.

Subclassed `ol/source/TileWMS~TileWMS` for reference:

```javascript
/**
 * Subclassed TileWMS, clears tile cache when parameters are updated
 * @constructor
 * @extends {module:ol/source/TileWMS~TileWMS}
 * @param {Object=} opt_options Source options.
 */
var TileWMS2 = (function(TileWMS) {
  function TileWMS2(opt_options) {
    TileWMS.call(this, opt_options);
  }
  if (TileWMS) TileWMS2.__proto__ = TileWMS;
  TileWMS2.prototype = Object.create(TileWMS && TileWMS.prototype);
  TileWMS2.prototype.constructor = TileWMS2;
  TileWMS2.prototype.updateParams = function updateParams(params) {
      this.clear();
      TileWMS.prototype.updateParams.call(this, params);
  };
  return TileWMS2;
})(TileWMS);
```

**Comment by ahocevar** [comment]
Thanks for sharing this approach. Can we close this issue?
