### ISSUE TITLE
master 'Icon Symbolizer'

### ISSUE THREAD

**Issue by jingyebuchen** [openlayers/openlayers#9139]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**
![icon](https://user-images.githubusercontent.com/41276803/51580042-230b9980-1efe-11e9-8a4c-5e7e4974e349.png)
Under the latest master, the Overlay position of this example is not fixed.

**Comment by ahocevar** [comment]
Can you provide more context on the platform/browser you are using? I cannot reproduce.

**Comment by jingyebuchen** [comment]
> Can you provide more context on the platform/browser you are using? I cannot reproduce.

Platform:win10
Browser: Google Chrome 68.0.3440.75
When the mouse scrolls to zoom out

**Comment by fredj** [comment]
As suspected by Andreas, this is an issue with Chrome and the `will-change` rule.
See https://bugs.chromium.org/p/chromium/issues/detail?id=960953
