### ISSUE TITLE
How to know the geojson vector loaded ? 

### ISSUE THREAD

**Issue by xpbliss** [openlayers/openlayers#9140]
when i use as the following:
'''
var vector = new ol.source.Vector({
  format: new ol.format.GeoJSON(),
  url: 'https://openlayers.org/en/v4.1.0/examples/data/geojson/countries.geojson'
});
'''
How do i know the geojson feature load finished?

**Comment by ahocevar** [comment]
Not the nicest and most obvious solution I know, but:
```js
var vector = new ol.source.Vector({
  format: new ol.format.GeoJSON(),
  url: 'https://openlayers.org/en/v4.1.0/examples/data/geojson/countries.geojson'
});
vector.once('changed', function() {
  console.log('loaded');
});
```

**Comment by xpbliss** [comment]
there are not  that function!

**Comment by xpbliss** [comment]
there are not  that function! @ahoceva
