### ISSUE TITLE
Use more accurate algorithm for geodesic area measurement

### ISSUE THREAD

**Issue by lydonchandra** [openlayers/openlayers#9141]
**Is your feature request related to a problem? Please describe.**
Using OpenLayers geodesic area measurement, the geodesic area measurement is about 0.4% OFF compared to QGIS,
eg: if QGIS returns 1971 sq meters, OpenLayers returns 1979 sq meters.

**Describe the solution you'd like**
This is due to the use of different algorithm, how difficult is it to *port* QGIS algorithm to OpenLayers (cpp to javascript) ?
Is it simply cpp to javascript translation, or does OpenLayers need to include other libraries, to implement what QGIS has ?

QGIS measure area:
https://github.com/qgis/QGIS/blob/master/src/core/qgsdistancearea.cpp#L1022

cc @NathanW2

**Comment by ahocevar** [comment]
You can always use a 3rd party library for measurements, e.g. [@turf/area](https://www.npmjs.com/package/@turf/area). What's integrated in OpenLayers is a simple algorithm that works in most cases.

**Comment by lydonchandra** [comment]
@ahocevar 
any other 3rd party library suggestion?

 @turf/area uses the same algorithm as openlayers
https://github.com/Turfjs/turf/blob/master/packages/turf-area/index.ts#L72

"Robert. G. Chamberlain and William H. Duquette, "Some Algorithms for Polygons on a Sphere",
 * JPL Publication 07-03, Jet Propulsion
 * Laboratory, Pasadena, CA, June 2007 https://trs.jpl.nasa.gov/handle/2014/41271"
