### ISSUE TITLE
Reverse the feature order by "time"

### ISSUE THREAD

**Issue by xpbliss** [openlayers/openlayers#9142]
I get the  feature data from url,  and the draw the different circle on the map. the oldest time circle will overlay the newest time circle .    the feature's property is "time".
```
      var vectorSource = new ol.source.Vector({
          url: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/4.5_week.geojson',
          format: new ol.format.GeoJSON(),
        });
```
how to reverse the feature data  order by time , so that the newest is always on the top.

**Comment by fredj** [comment]
You can control the drawing order of a feature by setting the `zIndex` property of it's style:
https://openlayers.org/en/master/apidoc/module-ol_style_Style.html

**Comment by xpbliss** [comment]
@fredj ，How to set the zIndex?  I set its style but nothing.
```
var  style = new ol.style.Style({	        
            image: new ol.style.Circle({
              radius:5,
             fill: '#fff',
            }),			
            zIndex:100		
          });
```

**Comment by fredj** [comment]
You need to set a style function at the layer level. The function will receive a feature as argument and 
 return a style. Use the time to set the zIndex.

Something like (pseudo code, untested):
```js
new VectorLayer({
    source: new VectorSource({...}),
    style: function(feature) {
      return new Style({
        image: new Circle({...}),
        zIndex: Date.parse(feature.get('time'))
      });
    }
})
```

**Comment by xpbliss** [comment]
Thanks! @fredj.   all work well!
