### ISSUE TITLE
pointerdown, pointerup event does not documented

### ISSUE THREAD

**Issue by egaoneko** [openlayers/openlayers#9143]
Recently my team found `pointerdown` and `pointerup` event in the [code](https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/MapBrowserEventType.js#L49).

![image](https://user-images.githubusercontent.com/6583941/51592581-561c5000-1f33-11e9-917d-889f15f44ead.png)

Although `pointerdrag` and `pointermove` are documented, some events about browser mouse event does not documented at the API.

I faced a reported [issue](https://github.com/openlayers/openlayers/issues/8564) for using `mousedown` and `mouseup`. I want to use `pointerdown` and `pointerup` event.

I wonder it is just a documentation miss or should not you use this feature?

**Comment by ahocevar** [comment]
The map does not relay internal pointerdown and pointerup events. You can only use those in browsers where they are natively available.
