### ISSUE TITLE
Unlisten an event on map with the method "map.un()" doesn't work

### ISSUE THREAD

**Issue by lowzonenose** [openlayers/openlayers#9145]
**Describe the bug**
Unlisten an event on map with the method **map.un()** doesn't work...

```
map.on("pointermove", (e) => onPointerMoveMap(e));
map.un("pointermove", (e) => onPointerMoveMap(e)); // <-- FIXME always listening !? -->
```
**To Reproduce**
JSFiddle : https://jsfiddle.net/lowzonenose/sjhLco4q/

**Expected behavior**
To work around this problem, I use the method *unByKey* instead of *un* : 

```
import { unByKey } from "ol/Observable";
var key = map.on("pointermove", (e) => onPointerMoveMap(e));
unByKey(key);
```

**Comment by fredj** [comment]
It doesn't works because you are creating two callback functions: one for the `on` and one for the `un`.
You can use this instead:
```js
map.on("pointermove", onPointerMoveMap);
map.un("pointermove", onPointerMoveMap);
```

**Comment by fredj** [comment]
See https://jsfiddle.net/fredj/jLy9v1u4/2/

**Comment by lowzonenose** [comment]
Sorry and thanks a lot !

**Comment by jackchoumine** [comment]
> It doesn't works because you are creating two callback functions: one for the `on` and one for the `un`. You can use this instead:
> 
> ```js
> map.on("pointermove", onPointerMoveMap);
> map.un("pointermove", onPointerMoveMap);
> ```

I have two quesitions? 

1. How pass paramas when  on a event?
2. Can i remvoe all listeners using un('event-name')? if not ,How should i do?

**Comment by behoney** [comment]
> > It doesn't works because you are creating two callback functions: one for the `on` and one for the `un`. You can use this instead:
> > ```js
> > map.on("pointermove", onPointerMoveMap);
> > map.un("pointermove", onPointerMoveMap);
> > ```
> 
> I have two quesitions?
> 
> 1. How pass paramas when  on a event?
> 2. Can i remvoe all listeners using un('event-name')? if not ,How should i do?

1. Declare function that takes event parameter, for example `function onPointerMoveMap (evt) { console.log(evt); }`

2. not sure.

**Comment by jackchoumine** [comment]
> > > It doesn't works because you are creating two callback functions: one for the `on` and one for the `un`. You can use this instead:
> > > ```js
> > > map.on("pointermove", onPointerMoveMap);
> > > map.un("pointermove", onPointerMoveMap);
> > > ```
> > 
> > 
> > I have two quesitions?
> > 
> > 1. How pass paramas when  on a event?
> > 2. Can i remvoe all listeners using un('event-name')? if not ,How should i do?
> 
> 1. Declare function that takes event parameter, for example `function onPointerMoveMap (evt) { console.log(evt); }`
> 2. not sure.

If I need to pass my params other then event ? how?

**Comment by behoney** [comment]
> > > > It doesn't works because you are creating two callback functions: one for the `on` and one for the `un`. You can use this instead:
> > > > ```js
> > > > map.on("pointermove", onPointerMoveMap);
> > > > map.un("pointermove", onPointerMoveMap);
> > > > ```
> > > 
> > > 
> > > I have two quesitions?
> > > 
> > > 1. How pass paramas when  on a event?
> > > 2. Can i remvoe all listeners using un('event-name')? if not ,How should i do?
> > 
> > 
> > 
> > 1. Declare function that takes event parameter, for example `function onPointerMoveMap (evt) { console.log(evt); }`
> > 2. not sure.
> 
> If I need to pass my params other then event ? how?

It depends on code structure.
Callback functions(; listeners) are declared as `listener: (event: EventClass) => ?) => Return` as far as I know. So `onPointerMoveMap` function cannot get any other params except `event`.

I usually implement those kind of things with the concept of higher order function.
