### ISSUE TITLE
gap between tiles when use gcj02 projection

### ISSUE THREAD

**Issue by kyleinfo** [openlayers/openlayers#9146]
I wanted to fix the offset of map in china, and I saw @tschaub's https://github.com/openlayers/openlayers/issues/3522#issuecomment-222769406 so
I use [projzh](https://github.com/tschaub/projzh) to create gcj02 projection, but I found gap between tiles:

![15482371474066](https://user-images.githubusercontent.com/7193422/51598056-b1504180-1f37-11e9-8e47-1b391e245c75.png)

Source: https://jsfiddle.net/8sdjo67v/7/

Sorry for my pool English.

**Comment by ahocevar** [comment]
Make sure you also set the Baidu projection on the view:
```js
new ol.View({
  center: ol.proj.transform([121.4538, 34.465], 'EPSG:4326', 'GCJ02MC'),
  zoom: 7,
  projection: 'GCJ02MC'
})
```

Here is an update of your fiddle: https://jsfiddle.net/tjrnu8yd/

**Comment by kyleinfo** [comment]
Thank you，avoid raster reprojection，I got it。
