### ISSUE TITLE
JSTS example not working on IE11

### ISSUE THREAD

**Issue by KimmoHop** [openlayers/openlayers#9147]
**Describe the bug**
JSTS example on IE11 does not show buffered lines on the map. Console shows errors:

SCRIPT1002: Syntax error
jsts.min.js (8,1114)

HTML1506: Unexpected token.
jsts.html (253,3)

Uncaught (in promise) ReferenceError: 'jsts' is undefined
   at Anonymous function (https://openlayers.org/en/latest/examples/jsts.js:1:388)

**To Reproduce**
1. Go to 'https://openlayers.org/en/latest/examples/jsts.html'
2. no buffered lines on map

**Expected behavior**
Buffered lines ("worms") shown on the map

**Comment by fredj** [comment]
Recent versions of JSTS are only compatible with browsers that support ECMAScript 6
(cc @bjornharrtell)

**Comment by bjornharrtell** [comment]
Intentional. Support contract for IE11 has expired. :)
