### ISSUE TITLE
RotateWithView broken in semi-opaque layer

### ISSUE THREAD

**Issue by tweedlebee** [openlayers/openlayers#9151]
**Describe the bug**
The arrowheads are mis-positioned in the LineString Arrows example if you change the vector layer to be semi-transparent and rotate the view.

**To Reproduce**
1. Starting with https://openlayers.org/en/latest/examples/line-arrows.html
2. Set an opacity on the vector layer - e.g.,
      var vector = new ol.layer.Vector({
          opacity: .8,
3. Set a rotation on the view - e.g.,
        view: new ol.View({
            rotation: (45 * Math.PI / 180),

![openlayers issue](https://user-images.githubusercontent.com/47007704/51700835-0d6da100-1fde-11e9-8ca6-1852b6935ccd.jpg)

**Expected behavior**
Instead of attaching to their lines - the arrowheads are located elsewhere on the map.

**Comment by ahocevar** [comment]
This issue is fixed in master, thanks to the new composite renderer (#8923).

**Comment by tweedlebee** [comment]
That is good to hear - thanks! When do you anticipate a release that will include it?

**Comment by ahocevar** [comment]
v6.0.0 is likely to be released in February.
