### ISSUE TITLE
ol/TileState export missing on full openlayers build

### ISSUE THREAD

**Issue by keepitrealsimple** [openlayers/openlayers#9153]
**Describe the bug**
ol.TileState.ERROR is not available in full openlayers build. Currently only solution is to hardcode value 3 into failed tile state which is not the best practise.

**To Reproduce**
1. Use full openlayers build
2. Try to use ol.TileState.ERROR as in documentation
3. See that TileState is not exported

**Expected behavior**
ol.TileState (or atleast ol.TileState.ERROR) should be exported in full build so it can be used in application.

**Comment by ahocevar** [comment]
The full build does not export any enums. If you are using the full build, hardcoding the value is the way to go. Side note: using the full build is not recommended for anything beyond playing with the library and quick prototyping. For real world applications, always use the [ol package](https://npmjs.com/package/ol).

**Comment by keepitrealsimple** [comment]
Ok. Thanks for the explanation. I will close the issue.
