### ISSUE TITLE
I'm using OpenLayers in WPF WebBrowser and DragPan is not working

### ISSUE THREAD

**Issue by SabaSabouhi** [openlayers/openlayers#9158]
I'm using OpenLayers in a 'WebControl'  (WPF).
the function code looks like this:
var mapTile = new ol.layer.Tile({ source: new ol.source.OSM() });
mapView =  new ol.View({
   projection: 'EPSG:3857',
   center: ol.proj.fromLonLat([longitude, latitude]),
   zoom: 15
});

var mapInteractions = ol.interaction.defaults({
   mouseWheelZoom: true,
   dragPan: true,
   keyboardPan: false
});
map = new ol.Map({
   target: 'map',
   layers: [mapTile],
   view: mapView,
   interactions: mapInteractions
});

The 'mouseWheelZoom' works fine but the dragPan and keyboardPan are ignored and 
It seems that dragPan is always false and keyboardPan is always true.

**Comment by fredj** [comment]
See https://openlayers.org/en/latest/apidoc/module-ol_interaction.html#~defaults

It's `keyboard` instead of `keyboardPan`

**Comment by amancini** [comment]
i have try to add default interaction by its not  work 
   var options = {
			target: 'map',
			projection: 'EPSG:900913',
			interactions: ol.interaction.defaults({
				keyboard: true,
				altShiftDragRotate: false,
				onFocusOnly: false,
				constrainResolution: false,
				doubleClickZoom: true,
				mouseWheelZoom: true,
				shiftDragZoom: true,
				dragPan:true,
				pinchRotate:true,
				pinchZoom:true
				}),
			displayProjection: 'EPSG:4326',
			loadTilesWhileAnimating: true,
			loadTilesWhileInteracting: true,
			units: "m",
			minZoomLevel: 3,
			controls: ol.control.defaults({
				zoom: false}),
			view: new ol.View({
				center: ([-0.92, 52.96]),
				zoom: 6})
		};


	if(EXTENT_RESTRICTION)
		options.extend = new OpenLayers.extent.boundingExtent([-20037508, -20037508,20037508, 20037508.34]);
	else
		options.extend = null;

	map = new ol.Map(options);

**Comment by zpmmehrdad** [comment]
Hi,

You can use this code before to initialize the map:

 internal static void SetBrowserFeaturesToSupportGpu()
        {
            // FeatureControl settings are per-process
            var fileName = System.IO.Path.GetFileName(Process.GetCurrentProcess().MainModule.FileName);
            SetBrowserFeatureControlKey(
            "FEATURE_96DPI_PIXEL",
            fileName,
            1)
            ; // enable hi-dpi support
            SetBrowserFeatureControlKey(
            "FEATURE_BROWSER_EMULATION",
            fileName,
            00000)
            ; // turn off compatibility mode.
            SetBrowserFeatureControlKey(
            "FEATURE_AJAX_CONNECTIONEVENTS",
            fileName,
            1)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_ENABLE_CLIPCHILDREN_OPTIMIZATION",
            fileName,
            1)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_GPU_RENDERING",
            fileName,
            1)
            ; // use GPU rendering
            SetBrowserFeatureControlKey(
            "FEATURE_IVIEWOBJECTDRAW_DMLT9_WITH_GDI  ",
            fileName,
            0)
            ; // force directX
            SetBrowserFeatureControlKey(
            "FEATURE_NINPUT_LEGACYMODE",
            fileName,
            0)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_DISABLE_NAVIGATION_SOUNDS",
            fileName,
            1)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_SCRIPTURL_MITIGATION",
            fileName,
            1)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_SPELLCHECKING",
            fileName,
            0)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_STATUS_BAR_THROTTLING",
            fileName,
            1)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_VALIDATE_NAVIGATE_URL",
            fileName,
            1)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_WEBOC_DOCUMENT_ZOOM",
            fileName,
            1)
            ; // allow zoom.
            SetBrowserFeatureControlKey(
            "FEATURE_WEBOC_POPUPMANAGEMENT",
            fileName,
            0)
            ; // disallow auto-popups
            SetBrowserFeatureControlKey(
            "FEATURE_ADDON_MANAGEMENT",
            fileName,
            0)
            ; // disallow auto-addons/plugins
            SetBrowserFeatureControlKey(
            "FEATURE_WEBSOCKET",
            fileName,
            1)
            ;
            SetBrowserFeatureControlKey(
            "FEATURE_WINDOW_RESTRICTIONS",
            fileName,
            0)
            ; // disallow popups
        }


        internal static void SetBrowserFeatureControlKey(string feature, string appName, uint value)
        {
            using (var key = Registry.CurrentUser.CreateSubKey(
                String.Concat(@"Software\Microsoft\Internet Explorer\Main\FeatureControl\", feature),
                RegistryKeyPermissionCheck.ReadWriteSubTree))
            {
                key.SetValue(appName, (UInt32)value, RegistryValueKind.DWord);
            }
        }
