### ISSUE TITLE
How to display the WMS layer . If Server not geoserver 

### ISSUE THREAD

**Issue by antochoy** [openlayers/openlayers#9159]
Hi,
I am anto
How to display the WMS layer . If Server not geoserver 

Example this WMS URL from = https://data.go.id/dataset?res_format=wms
http://portal.ina-sdi.or.id/arcgis/rest/services/IGD/RupabumiIndonesia/MapServer

please help me

**Comment by bartvde** [comment]
Please ask usage questions on stackoverflow instead with the tag openlayers

https://stackoverflow.com/questions/tagged/openlayers
