### ISSUE TITLE
ol.style.Text dynamic postioning

### ISSUE THREAD

**Issue by muhammadshayan** [openlayers/openlayers#9160]
I am drawing a vector layer which has different geometries drawn over each other. Like shown below.
![image](https://user-images.githubusercontent.com/44779040/51836516-7462c100-2322-11e9-8b4d-80bd201a3982.png)

Now I have to display a text label for each geometry separately which is done easily. But the text position is static. Meaning: When i zoom in on a certain area, labels do not get moved to my current view:
![image](https://user-images.githubusercontent.com/44779040/51836729-0bc81400-2323-11e9-98aa-e75920bc2e76.png)

It would be very helpful if label text gets adjusted dynamically according to the view.

**Comment by cintek** [comment]
I'm also looking for a solution for this problem.
