### ISSUE TITLE
GetLegend requests

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#9163]
SLD enabled WMS servers can support GetLegendGraphic requests. I will need this for a project. If desired I can implement a function similar to the getGetFeatureInfoUrl of the ImageWMS class for openlayers. That would be a getGetLegendGraphicUrl

Some more information on the topic can be found here: http://suite.opengeo.org/ee/docs/4.5/geoserver/services/wms/get_legend_graphic/legendgraphic.html and in the sld specification chapter 10: http://portal.opengeospatial.org/files/?artifact_id=22364

**Comment by ahocevar** [comment]
Yes, please create a pull request. Thanks!

**Comment by KaiVolland** [comment]
@simonseyock Did you start working on this? Otherwise i'll try to implement the functionality.

**Comment by simonseyock** [comment]
@KaiVolland another project got in between. I was planning to do this in the next couple of days until end of next week. But if you want to do thisI won't stand in the way :)

**Comment by KaiVolland** [comment]
Ok thanks. I'll give it a try today.

**Comment by simonseyock** [comment]
@KaiVolland do you plan on finishing this? Else I will continue

**Comment by KaiVolland** [comment]
Sry for not giving feedback @simonseyock. Glad you just did it. :)
