### ISSUE TITLE
Documentation for "render" and "rendercomplete" events is wrong

### ISSUE THREAD

**Issue by christophfriedrich** [openlayers/openlayers#9168]
**Describe the bug**
When loading an `ol.layer.VectorTile` with `ol.format.MVT`, the events `render` and `rendercomplete` are not fired.

**To Reproduce**
1. Go to https://jsfiddle.net/christophfriedrich/7yce3jvd/5/
2. Click on 'Run'
3. See tiles loading
4. See no alerts

**Expected behavior**
Alert(s) with "render", and then alert(s) with "rendercomplete".

The [documentation](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorTile-VectorTileLayer.html) of VectorTileLayer's events is quite scarce, but I'd expect at least one firing of `rendercomplete` at some point.

> rendercomplete: Triggered when rendering is complete, i.e. all sources and tiles have finished loading for the current viewport, and all tiles are faded in

**Note**
Maybe somewhat related to #8786?

I'm not sure if this bug only applies to MVT, but haven't tested any other configuration.

**Comment by ahocevar** [comment]
`rendercomplete` is an event dispatched by `ol/Map`, not by layers.

**Comment by ahocevar** [comment]
Looks like we need to fix the documentation.

**Comment by ahocevar** [comment]
@christophfriedrich Doc improvements pull requests are always welcome. All I'm going to do now is separeate map render events from layer render events.

**Comment by christophfriedrich** [comment]
Well, I'd be happy to supply a PR, but unfortunately I don't know what those events do, so I can't write it down either. Hence the request.
