### ISSUE TITLE
ol.interaction.Select styles don't work when features have been styled with setStyle

### ISSUE THREAD

**Issue by glenselle** [openlayers/openlayers#9169]
We have a use-case where upon feature selection, we want to keep the current fill of the feature the same and only change the stroke to a different color to indicate selection. We've found that changing the fill and stroke of the feature is extremely confusing when zoomed in and multiple overlapping features exist (with different styling). I was expecting that just as the feature's properties are maintained in the collection of selected features and accessible within a style function on the select interaction, the original style of the feature would be as well.

However, it seems that setting styles directly on features makes it impossible to select them with the select interaction. Here is a JSfiddle demonstrating this behavior with OL 4.6.5 (see the comment in the code which, when uncommented, prevents selection from working): http://jsfiddle.net/0rmp3sf6/

Is this intended behavior? It seems like a bug. If this is how it should work, is it possible to accomplish a simple stroke style change while maintaining the fill?

**Comment by ahocevar** [comment]
This is by design. Styles set on a feature always override styles on a layer. Think of it as an analogy to css element vs. class styles.

**Comment by glenselle** [comment]
Ok, so then it's impossible to make the select interaction preserve the feature's original fill and only style the stroke for features whose style is set from their layer or directly on the feature?
