### ISSUE TITLE
NPM module usability concern

### ISSUE THREAD

**Issue by senakafdo** [openlayers/openlayers#9171]
Unless OL is bundled into a browser-compatible format, the NPM module is not usable as-is and suffers from dependency resolution issues around imports such as rbush (see #8552). 

However, if the [entire ol.js](https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js) is also included within the NPM module as an alternative, users would have a fallback option.

Can this be considered?

**Comment by ahocevar** [comment]
We discourage the use of the full `ol.js` build, and encourage you to use a bundler. The reward is that your build will only contain what your application uses, giving your users a faster loading experience.
