### ISSUE TITLE
Polygon & MultiPolygon intersectsExtent failure

### ISSUE THREAD

**Issue by chuckwagoncomputing** [openlayers/openlayers#9175]
**Describe the bug**
Polygon and MultiPolygon's intersectsExtent function returns false in cases where the tested extent is narrower than the polygon, and extending inside it. The code below will never print "collided" to console. If extent 'n' is changed so more than one edge extends out of the box, it *will* print "collided" to console. This fails for any edge "sticking out" of the larger rectangle, not just the top edge.

**To Reproduce**
```
window.addEventListener('load', function() {
	map = new ol.Map({
		layers: [
			new ol.layer.Tile({
				source: new ol.source.OSM()
			})
		],
		target: document.getElementById("map"),
		view: new ol.View({
			center: ol.proj.fromLonLat([-100.49577, 37.60572], 'EPSG:3857'),
			zoom: 13
		})
	});

	var vectorSource = new ol.source.Vector({
		features: []
	});

	var vectorLayer = new ol.layer.Vector({
		source: vectorSource
	});

	map.addLayer(vectorLayer)

	var o = [-11187597.46284663, 4524022.231466765, -11186622.98660283, 4523917.644560398]

	var p = new ol.geom.Polygon.fromExtent(o)

	vectorSource.addFeature(new ol.Feature(p))

	var n = [o[0] - 10, o[1] - 10, o[2] + 10, o[3] - 10]

	if (p.intersectsExtent(n)) {
		console.log("collided")
	}

	vectorSource.addFeature(new ol.Feature(new ol.geom.Polygon.fromExtent(n)))
});
```
[
![_home_david_mnwe_index html](https://user-images.githubusercontent.com/1531127/52129340-e37b3680-25fc-11e9-9e5c-856148b48c5c.png)
](url)

**Expected behavior**
Should return true. Above code should print "collided" to console.

**Comment by ahocevar** [comment]
Your extent is incorrect - the first corner needs to have lower coordinate values than the second corner. The correct extent would be
```js
var o = [-11187597.46284663, 4524022.231466765, -11186622.98660283, 4523917.644560398]
```
i.e. with 2nd and 4th value swapped.
