### ISSUE TITLE
Map do not work on Edge and Explorer

### ISSUE THREAD

**Issue by xpowert** [openlayers/openlayers#9180]
Hello, my OpenLayer map do not work on MS Edge and Explorer browsers, but works perfect on FireFox and Chrome.  I see a pink background and missing image icon. 

Direct link to map - http://www.rpbv.lv/uploads/Karte/ 

Image from Edge:
![image](https://user-images.githubusercontent.com/12520158/52201026-e717f300-2872-11e9-95d0-e9279eb91cf2.png)

Image from FireFox: 
![image](https://user-images.githubusercontent.com/12520158/52201063-03b42b00-2873-11e9-911a-cceee8a73390.png)

**Comment by jahow** [comment]
Hi,

I've tested your map both on Edge and IE 11 using an emulator and it worked fined. There is most likely something in your browser context/settings which makes the tile requests fail.

Also this is Openlayers 2 for which the correct repo is https://github.com/openlayers/ol2. Or you could try https://stackoverflow.com/questions/tagged/openlayers for support.

**Comment by xpowert** [comment]
Thanks

**Comment by prusswan** [comment]
On Edge 44 it does throw up some CORS-related errors. No problem on latest Chrome
