### ISSUE TITLE
GeoPackage as Layer Source

### ISSUE THREAD

**Issue by onlymate** [openlayers/openlayers#9182]
I need raster data for offline use. During my research I came across with "GeoPackage". Is it possible to use OpenLayers with the GeoPackage as source?

For Information:  [GeoPackage](https://www.geopackage.org/ )

Or maybe OpenLayers supports another, I call it "single-file-solution" for raster tiles?

**Comment by ahocevar** [comment]
You should be able to use a `XYZ` source with a custom loader that utilizes https://www.npmjs.com/package/@ngageoint/geopackage.

**Comment by ThomasG77** [comment]
I've done a demo for raster tiles visible at https://labs.webgeodatavore.com/partage/gpkg-raster-tiles/
Not for raster, but also done a demo using Geopackage as a vector source (untiled) https://labs.webgeodatavore.com/partage/trails/

**Comment by onlymate** [comment]
@ahocevar @ThomasG77 Thank you for answers. This seems to be a good solution. 

@ThomasG77 Your example is very helpful, thank you!
