### ISSUE TITLE
DragBox not extending to the end of the screen in Safari

### ISSUE THREAD

**Issue by djibarian** [openlayers/openlayers#9183]
**Describe the bug**
DragBox is not extending till the end of the screen in Safari Mac (12.0.3).

![2](https://user-images.githubusercontent.com/6604263/52207404-a5d91080-287d-11e9-94f9-cf79d3079ded.jpg)

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/full-screen.html
2. Click the fullscreen control
3. Shift+click and extend the box to the right and bottom of the screen
4. The box is not reaching the screen border by 1x, both right and bottom (although there is another problem and tiles don’t extend to the very bottom too)

**Expected behavior**
In Firefox and Chrome works perfectly fine, both the box extending to the end and tiles covering the entire bottom

![1](https://user-images.githubusercontent.com/6604263/52207415-aec9e200-287d-11e9-8ea3-5691e843b2ef.jpg)

**Comment by fredj** [comment]
> The box is not reaching the screen border by 1x, both right and bottom (although there is another problem and tiles don’t extend to the very bottom too)

Addressed in #9571
