### ISSUE TITLE
[example] wrong superficie unit in DB ? or wrong value in select ?

### ISSUE THREAD

**Issue by jipexu** [openlayers/openlayers#9188]
Hi

**Describe the bug**
wrong superficie unit in DB ? or wrong value in select ?
**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/cartodb.html
2. Choose on select **Show countries larger than** 
5000km2
3. 
- The nederland (... 41 500 km2 ...), Belgium (...30 688 km2...)  is not show
and same process if you choose some other value
100000 km2  only Russia (17 000 000 km2) no France and Ukraine (> 500 000 km2) ....

**Expected behavior**
show or hide country according to the true superficie

or i miss something ..?

Thanks

**Comment by jbelien** [comment]
I believe it's more an issue on @CartoDB's side than OL.

Even when you request countries bigger than 0 km², there are a countries missing (Belgium for instance).

**Comment by jipexu** [comment]
yes sure but the example is there ...
