### ISSUE TITLE
Not able to use Types in Typescript

### ISSUE THREAD

**Issue by Toterbiber** [openlayers/openlayers#9191]
Hello, maybe I'm to stupid but now I'm trying to upgrade von 4.6 to the latest version for many houres now and I don't get type checks and intellisence in typescript to work again.

I'm using the latest Angular Version with TypeScript and VSCode and what I did for simplification was:
- I created a new empty Angular Project (ng new) -> **Works**
- I added openlayers (npm install ol --save) -> **Works**
- I'm using Openlayers to create a Map or whatever -> **Works**
- But: I don't have any **type checking**, so everything appears to me as "any"
- Then I added the required lines in tsconfig.json like mentioned here on Github -> **My whole App doesn't work anymore**
- Then i realized there is no subfolder "src" so I changed that in tsconfig -> **Nothing changed**

My Imports look like this: 
import Map from 'ol/Map';

What can I do to make type checking work again with the latest version or is it just not possible at the moment? 
In the past we where using the  @types/openlayers package but as this seems outdated to me and is not part of openlayers I don't see a chance here.

**Comment by sbrunner** [comment]
You probably should try to use OpenLayers 6 beta:
https://www.npmjs.com/package/ol/v/6.0.0-beta.1

**Comment by fredj** [comment]
And see also #9178 description

**Comment by Toterbiber** [comment]
Thankts for answering but still not working with 6.0.0-beta.1 and updated tsconfig.json :-(

**Comment by ahocevar** [comment]
@Toterbiber Did you configure your `tsconfig.json` as explained in the [README](https://www.npmjs.com/package/ol/v/6.0.0-beta.1#typescript-and-vs-code-intellisense-support)? Double-check `baseUrl`, `paths` and `include`.

Also make sure you don't have the `@types/ol` package installed, and clear your TypeScript cache folder (Mac: `~/Library/Caches/TypeScript`, Windows: `%LOCALAPPDATA%\Microsoft\TypeScript`, Linux: `~/.cache/typescript/`) to get rid of `@types/ol` which might be saved there.

**Comment by Toterbiber** [comment]
Moved the discussion to this place: [#9178](https://github.com/openlayers/openlayers/pull/9178)

**Comment by leonkosak** [comment]
If I understand correctly - there is no type definitions for OL 5.3.x (https://www.npmjs.com/package/ol)

**Comment by balab2020** [comment]
Still no support to use ol with typescript ;(

**Comment by balab2020** [comment]
@ahocevar I tried your suggestion but it did not help me. Typescript is not allowing to set baseUrl & paths in typeconfig.js file. Mostly unwanted errors. We have not choice of leaving typescript in our project. Quick help in creating sample OSM maps using typescript will be much appreciated.

**Comment by ahocevar** [comment]
@balab2020 Don't you have a `tsconfig.json` file or equivalent? `baseUrl` and `path` are standard TypeScript compiler options, so maybe you have set them under a different section than `compilerOptions`?

**Comment by OSHistory** [comment]
@ahocevar @balab2020 There has been a new effort using a jsdoc plugin. The maintainer 
has merged the resulting typings to DefinetlyTyped. 
https://github.com/openlayers/openlayers/issues/8120#issuecomment-487140088
