### ISSUE TITLE
Zoomify source incorrectly updates url when calling setUrl

### ISSUE THREAD

**Issue by jacobmh1177** [openlayers/openlayers#9206]
**Describe the bug**
I can create a Zoomify source with a url template as described in the documentation. However, when I try to call .setUrl on this Zoomify source the url template is not parsed correctly leading to urls getting translated to something like:

http://mysource.com/%7BTileGroup%7D/0-0-0.jpg

The %7B and %7D map to { and } respectively which makes me think that the incorrect regex is being used to parse the zoomify url in setUrl.

**To Reproduce**
1. Create a Zoomify source with a valid url template
2. Call .setUrl to update the Zoomify source url template

**Expected behavior**
You should see that downloading tiles fails because the url was incorrectly parsed.

**Comment by ahocevar** [comment]
If the `Zoomify` source inherits from `ol/source/UrlTile` instead of `ol/source/TileImage`, it could pass a `tileUrlFunction` to the superclass's `options`, and would work out of the box. Anyone willing to create a pull reqeust?
