### ISSUE TITLE
CSS causes wrong coordinates for mouse interaction

### ISSUE THREAD

**Issue by tpluscode** [openlayers/openlayers#9208]
**Describe the bug**

In a fairly simple setup, where the map is placed in a container with constrained dimensions, the click interaction produces wrong coordinates

**To Reproduce**
This can be observed on the selection example
1. Go to https://openlayers.org/en/latest/examples/select-features.html?q=select
2. Select 'Hover' in the dropdown
1. Change the styles to narrow down the size of the topmost `div.container-fluid`. For example make it 500px wide
3. Observe how the highlighted country is off to the left
![hover](https://user-images.githubusercontent.com/588128/52637376-5f179600-2ecf-11e9-94fe-74dc7d0fdb5c.gif)

**Expected behavior**
The selection should be precise when the map (its parent?) is resized

**Comment by fredj** [comment]
You need to manually call the `updateSize` function when the size of the element has changed.

**Comment by tpluscode** [comment]
Hm, thank you for your quick reply.

Is this something OpenLayers would aim to implement so that no manual intervention is required?

For the time being I added [resize-observer-polyfill](https://github.com/que-etc/resize-observer-polyfill) which seems to get the job done.

**Comment by fredj** [comment]
OpenLayers is already listening to the [window resize event](https://developer.mozilla.org/en-US/docs/Web/Events/resize) and calls `updateSize` accordingly. But there's no plan to do it at the element level.

It would be very nice to add an entry in the [FAQ](https://github.com/openlayers/openlayers/blob/master/doc/faq.md) about it
