### ISSUE TITLE
Unable to select text object when size is increased OL3

### ISSUE THREAD

**Issue by justineguy** [openlayers/openlayers#9209]
This is the mouseDown event that is currently being used when selecting text labels. 
`this.mouseDown = function (e) {
                                    var features = e.map._ModifySketch.getSelectedObjects();
                                    if (features.getLength() === 0) {
                                        return false;
                                    }

                                    var feature = features.getArray()[0];
                                    if (feature) {
                                        clickedAnchor_ = getClickedAnchor(e.coordinate, feature);
                                        if (clickedAnchor_ !== ME.SKETCH_ANCHOR.NONE) {
                                            coordinate_ = e.coordinate;
                                            feature_ = feature;
                                            feature_._isEditing = true;
                                            if (clickedAnchor_ === ME.SKETCH_ANCHOR.SIZE) {
                                                origGeometry_ = feature.getGeometry();
                                                startY_ = e.coordinate[1];
                                                startFontSize_ = getFeatureTextSize(feature);
                                            }
                                            return true;
                                        }
                                    }
                                    return false;
                                };

Currently this is running on iOS, Android, and a Java Windows application. The iOS and Android are able to select the large text objects without any issues, but on windows once the text object has reached roughly 60% of the screen size it no longer becomes selectable.

Is there anything that can be done to improve the selection of text objects?

**Comment by ahocevar** [comment]
Configure the layer with a `renderBuffer` of e.g 200 pixels. The default is 100, meaning that text and icons more  than 50 pixels away from the geometry‘s coordinate won‘t be considered for selection.
