### ISSUE TITLE
KML NetworkLink support

### ISSUE THREAD

**Issue by mrmister91** [openlayers/openlayers#9213]
**Describe the bug**
It seems OL does not support NetworkLink in KML. This this a core feature of KMZ whereby the parent KML refers to other KMLs in sub-directories.

**To Reproduce**
1. Drag and drop a KML file that has a NetworkLink with a href to another KML

**Expected behavior**
The KML that is referred to in NetworkLink is loaded on the webmap.

**Test Data**
```
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.0">
	<Document>
		<name>My Content</name>
		<NetworkLink>
			<name>Part 1</name>
			<Link>
				<href>https://developers.google.com/kml/documentation/KML_Samples.kml</href>
			</Link>
			<visibility>1</visibility>
			<open>1</open> 
		</NetworkLink>
	</Document>
</kml>
```

**Comment by ThomasG77** [comment]
I've made [a working demo](https://raw.githack.com/webgeodatavore/ol3-extras-demos/master/kmz/demo-kmz.html) for this intent some years ago to uncompress kmz and follow `NetworkLink` element

**Comment by mrmister91** [comment]
> I've made [a working demo](https://raw.githack.com/webgeodatavore/ol3-extras-demos/master/kmz/demo-kmz.html) for this intent some years ago to uncompress kmz and follow `NetworkLink` element

Thanks^^ as we are already using another library for unzipping, we may decide to implement the "follow `NetworkLink` element" part independently. But good, this tells me that this functionality is not yet in OL.
(and sorry, this ticket is probably more a Feature Request than a Bug Report)
