### ISSUE TITLE
Openlayer map not showing most of the time

### ISSUE THREAD

**Issue by osamaahmed32** [openlayers/openlayers#9214]
Most of my target is Dubai. but later it will be applied to other countries. Map zoomin, zoomout and bottom text from openstreetmap is coming but map is not coming. sometimes it comes when I try to zoomin 2 times.

I am using this code

<div class="qvvenuemap" id="venuemap"></div>

<style> .qvvenuemap { height: 500px; width: 100%; } </style>

<script src="https://openlayers.org/api/OpenLayers.js"></script>
<script>
window.onload =  function(){
	initvenue();
};

function initvenue() {
    var mymap = new OpenLayers.Map("venuemap");
    mymap.addLayer(new OpenLayers.Layer.OSM());

    var lonLat = new OpenLayers.LonLat( 55.2778 ,25.1987 )
          .transform(
            new OpenLayers.Projection("EPSG:4326"), // transform from WGS 1984
            mymap.getProjectionObject() // to Spherical Mercator Projection
          );
          
    var zoom=8;

    var markers = new OpenLayers.Layer.Markers( "Markers" );
    mymap.addLayer(markers);
    
    markers.addMarker(new OpenLayers.Marker(lonLat));
    
    mymap.setCenter (lonLat, zoom);
}
</script>

in console I am getting this

Uncaught TypeError: Cannot read property 'w' of null
at initialize.adjustZoom (OpenLayers.js:185)
at initialize.zoomTo (OpenLayers.js:195)
at initialize.zoomIn (OpenLayers.js:197)
at d.onZoomClick (OpenLayers.js:742)
at initialize.triggerEvent (OpenLayers.js:138)
at initialize.buttonClick (OpenLayers.js:146)
at initialize.triggerEvent (OpenLayers.js:138)
at initialize.handleBrowserEvent (OpenLayers.js:138)
at HTMLDivElement. (OpenLayers.js:63)

**Comment by ahocevar** [comment]
This is OpenLayers 2 code, which is nor actively being developed any more. Please use a recent version of OpenLayers.

**Comment by osamaahmed32** [comment]
can i have any example for it sir.

**Comment by ahocevar** [comment]
https://openlayers.org/en/latest/examples/simple.html

**Comment by osamaahmed32** [comment]
thanks alot sir
