### ISSUE TITLE
Image disappears on certain resolutions after fast zooming with mouse wheel

### ISSUE THREAD

**Issue by hajjimurad** [openlayers/openlayers#9216]
I use OpenLayers to explore big tile-based images using Zoomify source.
And I started noticing that sometimes image can disappear while zooming out with mouse wheel (scroll down). It wasn't easy to reproduce, because the behavior is flaky. And the behavior is more stable on 'non-standard' images (tile size 1536x1536 and the image is vertically stretched)

1. Go to the example http://cssdeck.com/labs/csrch2es
2. Move the mouse point to the approximate center
3. Zoom out to 1 step with mouse-wheel
4. If image didn't disappear try multiple times. Maybe it depends on mouse position or some race conditions, I don't know. But mostly it disappears, when the mouse position is in the center, and if not - image gets zoomed out properly.

Here is also a video, where I reproduce it: https://screenpresso.com/=sUmyc
Unfortunately the fact that mouse wheel is scrolled is not visible there.

Any ideas, solutions and even workarounds are welcome.
You can play with the code here http://cssdeck.com/labs/csrch2es, but collapse all the panels and make the working area as big as possible. It's easier to reproduce, when the available space is wider.

Also you here is easier to reproduce http://68.183.68.22/index.html. Don't forget to keep your cursor around center of the image before you zoom out.

```javascript
    const size = [12375, 38162];
    const tileSize = 1536;
    const tilesUrl = `http://68.183.68.22/ol-issue-red/{z}/{x}/{y}`;

    const maxZoomLevel = 5;

    const view = new ol.View({
        center: [size[0] / 2, -size[1] / 2]
    });

    var map = new ol.Map({
        controls: ol.control.defaults().extend([
            new ol.control.OverviewMap(),
            new ol.control.ScaleLine()
        ]),
        interactions: ol.interaction.defaults({ mouseWheelZoom: false, }).extend([new ol.interaction.MouseWheelZoom({ duration: 0, timeout: 0 }),]),
        target: 'map',
        renderer: 'canvas',
        view: view
    });

    const zoomifySource = new ol.source.Zoomify({
        tierSizeCalculation: 'truncated',
        size: size,
        tileSize: tileSize
    });

    zoomifySource.setTileUrlFunction((tileCoordinate, pixelRatio, proj) => {
        const z = maxZoomLevel - (tileCoordinate[0]);
        const res = tilesUrl
            .replace('{z}', (z).toString())
            .replace('{x}', (tileCoordinate[1]).toString())
            .replace('{y}', (((-tileCoordinate[2]) - 1)).toString());
        return res;
    });

    zoomifySource.setTileLoadFunction((tile, url) => {
        fetch(url, { method: 'GET', })
            .then(response => { return response.blob(); })
            .then(function (blob) { tile.getImage().src = URL.createObjectURL(blob); });
    });

    map.addLayer(new ol.layer.Tile({ source: zoomifySource }));

    const extent = [0, -size[1], size[0], 0];
    const calculatedResolution = map.getView().getResolutionForExtent(extent);
    view.setResolution(calculatedResolution);
```

**Comment by ahocevar** [comment]
There's a lot of application code in your example. Please create a simpler, more stripped down example.

**Comment by hajjimurad** [comment]
Sorry, I've update the code.

Also I noticed that the behavior depends on the folloiwing factors:

1. `duration` parameter of `ol.interaction.MouseWheelZoom`. The bigger it is, the harder it reproduce. In my example it's set to 0, so there is no animation for zooming.
1. How wide is the map area. The wider it is, the easier to reproduce the bug. That's why it's set to 2000px in my example. And collapse the left panel here http://cssdeck.com/labs/csrch2es to see the example better.
1. The mouse pointer. Keep it in the image center while zooming to see the bug.

**Comment by ahocevar** [comment]
Your tile service does not deliver any tiles, so there is no way to reproduce this.

**Comment by hajjimurad** [comment]
It does, just collapse the panel on the left. Here is the video. https://screenpresso.com/=6beSe
As I said, I had to make the map 2000px wide to make the bug reproducible easier.

**Comment by ahocevar** [comment]
Sorry, your example does not load any images. Please provide an example that works out of the box.

**Comment by hajjimurad** [comment]
Could you give more details, what error do you get? Does it have anything to do with HTTPS? Do you see any HTTP-request for tiles is failing?

I tried with Chrome, Firefox and Edge from different PCs. The tiles are loaded everywhere and I've provided the video, how the map is loaded. Can you also confirm that the example from here http://68.183.68.22/index.html is also not available? 

Thank you

**Comment by ahocevar** [comment]
Ok, I see now! I did not recognize the squares as tiles. Thought those are UI elements.

Your issue is probably an incorrect configuration. I see several 404 errors on tiles (2/0/3, 2/1/3, 1/2/6 and 0/4/12). This could be the cause for the problem. Make sure to configure the layer or source or tile grid with a proper extent.

**Comment by hajjimurad** [comment]
I didn't put the tiles for levels 1 and 2 for simplicity. There are only level 5(default), 4, 3 available.
You don't need to zoom in, the bug appears only when zooming out (scroll down from initial state).

The bug is definitely not because of missing tiles. I'm not novice with OpenLayers (work for a couple of years already with it).  And this looks like a bug: for example, if I set duration=100 for `ol.interaction.MouseWheelZoom` the bug is gone.

**Comment by ahocevar** [comment]
I'm not able to reproduce this. But I don't have a mouse, only a trackpad. One reason I could think of would be exceeding the canvas size. If that's the case, your example should work with OpenLayers v6.x (beta already available on npm). Can you try that?

**Comment by hajjimurad** [comment]
Please try with mouse (1 scroll back to zoom out), with trackpad it's not reproducible. I simplified the example even more, by removing the resolutions as parameter.
Here is the latest video: https://screenpresso.com/=esL1c
You may see the the overview-control still has the original image shown, but it's not show in the main control.

I tried with the beta 6.0.0-beta (by building it locally with `npm run build-legacy`), an referring to the result `ol.js` from the example. But it doesn't work for me at all: the map is not loading properly. I guess the logic is significantly changed there. Thank you

**Comment by ahocevar** [comment]
Please try to set up and reproduce your demo with v6. You can use https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/master/build/ol.js for a version that uses the new renderer already.

**Comment by hajjimurad** [comment]
It works! You can also see it here http://68.183.68.22/index6.html. I can't reproduce the bug anymore.
Could you give more details about that bug and the plans for the next version?

**Comment by ahocevar** [comment]
Like I said, when zooming out while no lower resolution data is available, the resulting image is oversampled. This requires a larger canvas, and some browsers have a  canvas size limit.

The url function change is expected, see https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#new-internal-tile-coordinates.

The new release will be out in a few weeks. A beta is already available as npm package with `npm install ol@beta`.
