### ISSUE TITLE
Unable to set Draw (and Select) interaction overlayLayer zIndex

### ISSUE THREAD

**Issue by adraw** [openlayers/openlayers#9218]
**Describe the bug**
I was trying to do some drawing using Draw interaction, but all temporary drawings which I made were displayed under features from my other layers which have higher zOrder. I could not set zOrder of overlay layer because the overlay layer was not directly accessible from interaction. Thus i had to access private field like this: 

![image](https://user-images.githubusercontent.com/47631105/52793737-a25c3b00-306e-11e9-88cf-931014e62c15.png)

**To Reproduce**
1. Create a Layer and set the zIndex of this layer to high number (like 5000)
2. Populate layer with features
3. Create Drawing interaction and start drawing over the features you have on the layer you created
4. The temporary drawings are displayed under the features

**Expected behavior**
Either the drawings are always displayed over all other features, all there is a way to set z order of overlay layers

P.S: This issue is also present in SelectInteraction and probably other interactions too

**Comment by ahocevar** [comment]
You have full access to the sketch layer through the API:
```js
const layer = draw.getOverlay();
layer.setZIndex(Infinity);
```

**Comment by adraw** [comment]
Thank you. Somehow I didn't find it.
