### ISSUE TITLE
The types should be availavle in the npm package

### ISSUE THREAD

**Issue by sbrunner** [openlayers/openlayers#9223]
I can be useful to have those https://github.com/openlayers/openlayers/tree/master/types file(s) in the npm package to do the types check in the project.

**Comment by ahocevar** [comment]
To me it feels like these should be either part of TypeScript, or be provided as a DefinitelyTyped package. Also, we should revisit if we still need the prefixed properties (`moz*`, `webkit*`), or if all of them are available now without prefix.

**Comment by sbrunner** [comment]
Good question effectively :-)

**Comment by fredj** [comment]
According to https://caniuse.com/ we can safely remove the vendor prefix for the `transform` CSS property and the `moz` prefix for the fullscreen API

https://caniuse.com/#feat=transforms2d
https://caniuse.com/#search=fullscreen

**Comment by fredj** [comment]
See #9224
