### ISSUE TITLE
TileWMS Width/Height not being set

### ISSUE THREAD

**Issue by jt-helsinki** [openlayers/openlayers#9227]
TileWMS does not recognise the height/width properties when set in the params property.

**To Reproduce**
Create a new TileWMS object and add to layer. 
```
const wmsSource = new TileWMS({
        url: url,
        params: {
            'LAYERS': layerName,
            'VERSION': '1.1.1',
            'WIDTH':256,
            'HEIGHT':256
        },
        serverType: 'geoserver'
    });
```
Check the http request that is sent to server. The width/height in the URL are both set to 512.

**Expected behavior**
The width/height in the URL are both set to 256 as specified.

**Comment by jt-helsinki** [comment]
setting the pixel ratio to 1 on the Map object will fix this.

```
new ol.Map({
            view: view,
            pixelRatio: 1,
            maxTilesLoading: 16,
            layers: layers,
            loadTilesWhileInteracting: true

        });
```

**Comment by ahocevar** [comment]
Also, the are `PARAMS` are not the right place to set the tile size. It's the source's `tileGrid` that determines the tile size.
