### ISSUE TITLE
With declutter enabled on a vector tiles, some visible geometry isn't returned by hasFeatureAtPixel or forEachFeatureAtPixel

### ISSUE THREAD

**Issue by richorama** [openlayers/openlayers#9229]
**Describe the bug**

Version 5.3.0.

With declutter enabled on a vector tile layer, some visible geometry isn't returned by `hasFeatureAtPixel` or `forEachFeatureAtPixel` when zooming into the map (past the point that the groups are expanded).

**To Reproduce**

1. Set `declutter: true` on a vector layer.
2. Zoom in several levels, such that groups are expanded.
3. Call `hasFeatureAtPixel` or `forEachFeatureAtPixel` and see that some geometries are not returned.

This codepen demonstrates this:

https://codepen.io/richorama/pen/xMmgEQ?editors=1010

The `hasFeatureAtPixel` is called on mouse over (and changes the cursor), mouse click fires `forEachFeatureAtPixel`, and writes to the console.

**Expected behavior**

I expect any visible geometry to be returned by  `hasFeatureAtPixel` and `forEachFeatureAtPixel`.

**Comment by ahocevar** [comment]
Thanks for reporting this. I created #9230 to fix the issue.

**Comment by richorama** [comment]
awesome, thank you!

**Comment by richorama** [comment]
I'm still seeing this issue on 5.3.1

Codepen updated to use `latest`: https://codepen.io/richorama/pen/xMmgEQ?editors=1010

BTW I noticed that when set to `master` the points are rendered in the correct locations.

**Comment by ahocevar** [comment]
This fix will be in v6.0.0, not in v5.3.1.
