### ISSUE TITLE
ol.layer.Layer not included in full build ol.js

### ISSUE THREAD

**Issue by csozoli** [openlayers/openlayers#9234]
**Describe the bug**
The ol.layer.Layer class would need an @api annotation, otherwise it is not visible in full ol.js build.
The case where this is needed is e.g. layer tree traversal to distinguish “leaf” layer from group layer.

**To Reproduce**
An example of failure can be seen here: https://jsfiddle.net/tpcxL1e9/
Tested with v5.3.0.

**Expected behavior**

**Comment by ahocevar** [comment]
For this specific use case, it is probably enough to consider the layer a 'leaf' layer when it is not a group layer.

However, with the new renderer API, it might make sense to add `ol/layer/Layer` to the API. But I think we'll decide this once we have agreed on the final API around the layer's `render()` method. I'm leaving this ticket open as a reminder for that.

**Comment by fredj** [comment]
@ahocevar what do you this of adding `ol/layer/Layer` to the API?

**Comment by ahocevar** [comment]
Sure, why not @fredj

**Comment by fredj** [comment]
The `@api` annotation was added in 4a1cda715db97c9a36865d5e804e38458601f39a
