### ISSUE TITLE
WebGLMap not showing osm tiles

### ISSUE THREAD

**Issue by kaiiorg** [openlayers/openlayers#9241]
**Describe the bug**
I recently upgraded to angular 7.2.4 and ol 5.3.0, discovered the problem described by #8815 and #8962, and found the workaround to that in #9019 (though, I was only able to get it to work by manually adding `proj.js` to the `sideEffects` section of `ol`'s `package.js`). Right now, my osm base map isn't rendering at all, but it will render the point layer I add to it. 

What I know so far:
* This happens in both dev mode (using `ng serve --ssl`) and prod mode (`ng build -- prod`). 
* This occurs in both Firefox and Chrome. 
* The console reports no errors.
* The request log shows the osm tiles being requested and loaded. 
* Using inspect element, I can see that the `map` div has been attached to.

**To Reproduce**
I've simplified the code all the way down to:
`sandbox.component.ts`
```typescript
import { Component, OnInit, isDevMode } from '@angular/core';

import OlWebGLMap from 'ol/WebGLMap';
import OlOSM from 'ol/source/OSM';
import OlTileLayer from 'ol/layer/Tile';
import OlView from 'ol/View';

@Component({
  selector: 'app-sandbox',
  templateUrl: './sandbox.component.html',
  styleUrls: ['./sandbox.component.scss']
})
export class SandboxComponent implements OnInit {
  devSandBoxMessage = isDevMode() ? 'Development Sandbox' : 'YOU SHOULD NOT BE HERE!';

  _map: OlWebGLMap;
  _view: OlView = new OlView({
    center: [-89.600223, 37.378633],
    zoom: 13,
    projection: 'EPSG:4326'
  });

  constructor() {  }

  ngOnInit() {
    this._map = new OlWebGLMap({
      view: this._view,
      layers: [
        // this._baseMapLayer
        new OlTileLayer({
          source: new OlOSM()
        })
      ],
      target: 'map'
    });
  }
}
```
```html
<h1>{{devSandBoxMessage}}</h1>

<!--Map-->
<div id="map" class="map"></div>
```

![image](https://user-images.githubusercontent.com/14365919/53028951-80c3d080-342d-11e9-818b-b1aa6b915e08.png)
![image](https://user-images.githubusercontent.com/14365919/53028990-9b964500-342d-11e9-9f9d-79b645d127ed.png)

**Expected behavior**
Load the tiles from the osm cdn and render the tiles.

**Comment by kaiiorg** [comment]
On further testing, it looks like it works as expected when you use `ol/Map` instead of `ol/WebGLMap`. I see that `ol/WebGLMap` and its related components are being torn out of version 6 of open layers and I'm going to have to reimplement my maps anyway. 

I'm not sure how performant `ol/Map` will be; I've had to use WebGL to be able to get any decent performance in the past. I'll need to do further testing to see if I can't get it to work well enough for us. How hard would it be to change to web gl rendering in 6.0.0?

**Comment by jahow** [comment]
There was a shift in how webgl is used in OL starting from v6: the generic webgl renderer is gone and all layers are now by default rendered using canvas.

On top of that, a specific webgl renderer for point geometries was added: this renderer is able to render a high amount of points but does not currently support the OL style functions.

Assuming you used the webgl renderer for performance on vector layers containing points, you *may* be able to get the best of both worlds: reliability and cleanliness of the canvas renderer, performance of the webgl point renderer.

As an example the heatmap layer has been rewritten to use this, and an example of a map with 80k points was added as well: 
https://831-4723248-gh.circle-artifacts.com/0/examples/heatmap-earthquakes.html
https://831-4723248-gh.circle-artifacts.com/0/examples/icon-sprite-webgl.html
