### ISSUE TITLE
Add stylus only and touch only mode in drawing a shape

### ISSUE THREAD

**Issue by huyngkh** [openlayers/openlayers#9243]
**What is my problem?**
I work on a project which requires to draw and annotate on a map. I have used Openlayers as the main library to fulfill the requirement. It is good to draw on a map using a PC with a mouse but it is quite frustrated to draw on a tablet device with a stylus. While I am naturally drawing a new shape using a stylus my pinky finger frequently disrupts the drawing by accidentally touching on the tablet's screen. The unintentional touching from my smallest finger is going to draw some unexpected shape and break my current drawing.

**My solution**:
I have checked and found that browsers support to distinguish a click event by a mouse, a touch or a pen while Openlayers currently support mouse only. Therefore, I just add a small patch with few lines of code to the library to support stylusOnly (or penOnly) and touchOnly which has solved my problem (to do so, I add two more variables in ol/events/condition.js). When users access my system on their tablet they can set the Openlayer map to styleOnly mode to prevent accidentally touching by hand.

Besides, I also want free-hand drawing could work with stylus only then I have changed the condition in ol/interaction/Draw.js too.

**Comment by fredj** [comment]
fixed with #9244
