### ISSUE TITLE
Image renderer compute a new image recursively

### ISSUE THREAD

**Issue by benVigie** [openlayers/openlayers#9248]
**Describe the bug**
I'm using image renderer layer to improve peformance when a lot of features are displayed. I have more than 40K features to show, and the ability to draw once and be able to move smoothly on the map is very useful in this use case.

I updated my Openlayers version from `5.3.0` to the `latest`, and I noticed a strange behaviour: my CPU is used at 90-100% and the memory is overloaded by DOM nodes. Even if I don't interact with the map or the page, this behaviour occurs.

You can see the performance difference in the following capture. Same tests and data for both, the only difference is _localhost#2_ is using the latest Openlayers version, and  _localhost#3_ is using `5.3.0`
![capture](https://user-images.githubusercontent.com/3090329/53106056-424b1600-3500-11e9-99f6-bc742f4d7d17.PNG)

After some investigation, I found the problem: each time a layer is rendering a new image it will trigger a new image rendering, and so on over and over.

In details, `PluggableMap.renderFrame_` will result in a `LayerRenderer.loadImage()`. As soon as the image is loaded, `renderIfReadyAndVisible()` will call `layer.changed()`. The thing is each layer change update will trigger a new render. So basically, creating a new vector image will result by creating a new image again and again.

I noticed this MR (https://github.com/openlayers/openlayers/commit/ac3a1fb953eea4498abf04100e1971a2a43eaf3b#diff-002371d99083c84bf3a34b25e305767c) has changed the way events are sent since `5.3.0`. By calling `layer.changed()`, the full process of creating a new image is triggered. By reverting this commit, performance is back to normal. It's not the best solution as you obviously wanted this change, but maybe this is a good starting point.

**To Reproduce**
1. Create a map with an image renderer layer
2. Open `Performance monitor` in chrome dev tools (or other browser equivalent)
3. See CPU usage / js heap size / Dom nodes metrics

**Expected behavior**
The image renderer layer should only draw once and do nothing more if there is no interaction with the map. CPU usage and memory should be limited and used only on render actions.

**Comment by ahocevar** [comment]
Looks like a duplicate of #9211, which was fixed with #9217. Can you confirm please?

**Comment by benVigie** [comment]
Indeed, #9217 fix the issue. Awesome! 😃
