### ISSUE TITLE
esps3857.fromEPSG4326() is returning NaN for Y when Math.tan() returns negative value 

### ISSUE THREAD

**Issue by christian4423** [openlayers/openlayers#9249]
In the output file for proj.js I noticed that the function only converts the longitude. 

```
_ol_proj_.toLonLat = function(coordinate, opt_projection) {
  var lonLat = _ol_proj_.transform(coordinate, opt_projection !== undefined ? opt_projection : 'EPSG:3857', 'EPSG:4326');
  var lon = lonLat[0];
  if (lon < -180 || lon > 180) {
    lonLat[0] = _ol_math_.modulo(lon + 180, 360) - 180;
  }
  return lonLat;
};
```

I am not 100% sure why the latitude is being untouched

I was able to finish this function by added a few lines. 

```
_ol_proj_.toLonLat = function(coordinate, opt_projection) {
  var lonLat = _ol_proj_.transform(coordinate, opt_projection !== undefined ? opt_projection : 'EPSG:3857', 'EPSG:4326');
  var lon = lonLat[0];
  var lat = lonLat[1];
  if (lon < -180 || lon > 180) {
    lonLat[0] = _ol_math_.modulo(lon + 180, 360) - 180;
  }
  if (lat < -90 || lat > 90) {
    lonLat[1] = _ol_math_.modulo(lat + 90, 360) - 90;
  }
  return lonLat;
};

```

Things were working properly after that.

**Comment by ahocevar** [comment]
Not sure what you were trying to achieve, but latitudes are always in the range of -90 to 90. The reason why longitudes are not is because there is no other pragmatic way to express lines and polygons that cross the date line than using coordinates lower than -180 or higher than 180.

**Comment by christian4423** [comment]
Perhaps I should change the title to "Proj.toLonLat() is returning NaN"

I added the `IF` because there is already validation for the `lonlat[0]`. I was following convention... if it does not need to be included, I will remove it. That said, the statement in the condition fixed the issue. 

Without the statement in the second condition  ` return lonLat;` is returning an array with index[1] being `NaN`. 

This is what I was doing to get the error... nothing fancy

```
getCenterOfExtent(Extent){
    const xy =  olExtentUtil.getCenter(Extent);
    const latlng = Proj.toLonLat(xy, 'EPSG:3857');
    return latlng;
}
```
And like I said, the second index in `latlng` is `NaN`

**Comment by ahocevar** [comment]
This is expected for coordinates outside the projection's validity extent. For EPSG:3857, this is latitude -85.06 to 85.06 (see https://epsg.io/3857).

The change you suggested above would not change the latitude if it was `NaN` already.

**Comment by christian4423** [comment]
You are correct, I went to double check the values to respond to this post and I realized that it was not that function. It is the Proj,transform() function. 

More specifically... it is when the esps3857.fromEPSG4326() function is called from transform

Stepping through the code, I found this: 

![image](https://user-images.githubusercontent.com/6324867/53256381-b8cd4c80-3695-11e9-9c04-e06d77c28f43.png)

on line 105-106: 
`var y = _ol_proj_EPSG3857_.RADIUS * Math.log(Math.tan(Math.PI * (input[i + 1] + 90) / 360));`

Which is returning NaN because you cannot take the log of a negative number. 

By changing the formula to: 

`var y = _ol_proj_EPSG3857_.RADIUS * Math.log(Math.abs(Math.tan(Math.PI * (input[i + 1] + 90) / 360)));`

and passing: 5259029.15946701 into it I got 
![image](https://user-images.githubusercontent.com/6324867/53256995-28900700-3697-11e9-846a-e92f73a5f3d4.png)

**Comment by ahocevar** [comment]
Latitudes are expected to be in the range of -85.06 to 85.06. You are probably passing projected coordinates instead of longitudes and latitudes to `ol/proj/fromLonLat` or `epst3857/fromEPSG4326`.
