### ISSUE TITLE
KML placemark inline IconStyle overwrites IconStyle from styleUrl

### ISSUE THREAD

**Issue by hauschi84** [openlayers/openlayers#9252]
Styling `placemarks` in KML files can easily done using style IDs.
When inserting `placemarks` in the KML file, these IDs can be referenced usind the `styleURL` tag.
This works pretty fine! But for some icons (e.g. arrows) it can be necessary to also set a `heading` information! This can not be done in the predefined styles as this changes for each placemark.
Therefore it is required to have an inline `Style` tag that only containes the `heading` tag for this icon. Unfortunately it is not appending this information to the merged information from the style ID. It seems to overwrite the whole `IconStyle` information from the style IDs. At least it displays the default hotSpot icon from Google (yellow pin) using the heading information from the inline `IconStyle.`

**To Reproduce**
1. Extract [demo.zip](https://github.com/openlayers/openlayers/files/2888527/demo.zip)
to have a minimal example.
2. Load the contained KML into online [Google Earth](https://earth.google.com/web/) to see how it should look like.
3. Now use the same KML and display it as overlay using openlayers.

**Expected behavior**
The inline `IconStyle` options should only overwrite the options specified in the `IconStyle` of the referenced style ID instead of replacing the whole `IconStyle.`

**Comment by stoecker** [comment]
I'm also affected by this bug. Any chance for a fix soon?

**Comment by ahocevar** [comment]
If anyone is able to provide a pull request, we'd be glad to accept the fix.

**Comment by stoecker** [comment]
Wow. Instead of fixing a bug it will automatically close when nobody does anything. That's also a way to get rid of work to be done.

**Comment by fredj** [comment]
If you want this issue to be fixed, you should to get in touch with a company that provides support for OpenLayers. Some of them are listed on https://www.osgeo.org/service-providers/.

As far that I know, all of the core developers are maintaining the library on their free time.

**Comment by stoecker** [comment]
> If you want this issue to be fixed, you should to get in touch with a company that provides support for OpenLayers. Some of them are listed on https://www.osgeo.org/service-providers/.
> 
> As far that I know, all of the core developers are maintaining the library on their free time. 

I hope you don't use any of the many software products I develop or package in my free time.
