### ISSUE TITLE
Module not found: Error: Can't resolve 'ol/Canvasmap' in'ol-mapbox-style'

### ISSUE THREAD

**Issue by tanjinrong123** [openlayers/openlayers#9262]
import {apply} from 'ol-mapbox-style/index.js';在index.js 里面有import CanvasMap from 'ol/Canvasmap'; 可是下载的ol里面没有Canvasmap.js文件，而且apply函数里面要使用 map = new CanvasMap();这该怎么解决？

**Comment by ahocevar** [comment]
This is an issue with  your application. Ther is no ol/Canvasmap`. Either use ol/CanvasMap` with OpenLayers 5, or ol/Map` with OpenLayers 6.

**Comment by tanjinrong123** [comment]
ol-mapbox-style/index.js 是在npm下载的文件，文件本身配置有import CanvasMap from 'ol/Canvasmap。我也觉得很奇怪，没有ol/Canvasmap，为什么下载的文件里面会引用这个

**Comment by ahocevar** [comment]
CanvasMap, not Canvasmap please.
