### ISSUE TITLE
KML readFeatures incorrectly parses displayName

### ISSUE THREAD

**Issue by tlachy** [openlayers/openlayers#9265]
**Describe the bug**
If I try to parse/read kml file

    <kml xmlns="http://www.opengis.net/kml/2.2">
    <Document>
      <name>Kml Attribute Sample 1: Simple</name>
      <Placemark>
        <name>Some Point</name>
        <ExtendedData>
          <Data name="myNumber">
            <value>123</value>
          </Data>
          <Data name="myString">
		<displayName>Alias to myString</displayName>
            <value>the string value</value>
          </Data>
        </ExtendedData>
        <Point>
            <coordinates>16.334122,48.163808</coordinates>
        </Point>
      </Placemark>
        </Document>
    </kml>

 with 

        const features = new KML().readFeatures(data, {featureProjection: 'EPSG:3857', extractStyles: true});
       
it does not parse the displayName correctly

**To Reproduce**
1. Use the example from 'https://openlayers.org/en/latest/examples/kml.html'
2. use the KML file (in attachment) and call: 
    "const features = new KML().readFeatures(data, {featureProjection: 'EPSG:3857', extractStyles: true});"
3. readFeatures returns: 
![image](https://user-images.githubusercontent.com/6696293/53344055-03f39380-3912-11e9-847f-28cc86fe67a1.png)

**Expected behavior**
DisplayName is parsed/read as key for property like in google maps -
If you drag on drop KML file on google maps, it displays

![image](https://user-images.githubusercontent.com/6696293/53343811-84fe5b00-3911-11e9-88f9-ae26f25b69ac.png)

and I expect OL to parse it the same way

**Comment by ahocevar** [comment]
Is the behavior you see in Google Maps described in the KML specification?

**Comment by tlachy** [comment]
Hello, according to    
 http://docs.opengeospatial.org/is/12-007r2/12-007r2.html#139 the kml:displayName     
seems to be part of the standard.     
Also, usage of kml:displayName is used in this Google tutorial https://developers.google.com/kml/documentation/extendeddata

**Comment by ahocevar** [comment]
Thanks! Would you be able to provide a pull request?

**Comment by fredj** [comment]
What should be the new behavior? Do we want to keep storing the key / value and store the displayName as a separated property or store the displayName along the value.

```js
feature.get('myString') === 'the string value'
feature.get('displayName') === {'myString': 'Alias to myString'}
```
or
```js
feature.get('myString') === {value: 'the string value', displayName: 'Alias to myString'}

```

**Comment by ahocevar** [comment]
I‘d say the latter. What do you think @tlachy?

**Comment by tlachy** [comment]
Yes, the latter would be better.
