### ISSUE TITLE
WMS GetFeatureInfo examples broken due to 'X-Frame-Options'

### ISSUE THREAD

**Issue by chrismayer** [openlayers/openlayers#9269]
**Describe the bug**
The WMS GetFeatureInfo examples 

https://openlayers.org/en/v4.6.5/examples/getfeatureinfo-image.html and 
https://openlayers.org/en/latest/examples/getfeatureinfo-tile.html

are broken because the WMS used (https://ahocevar.com/geoserver/wms) has set `X-Frame-Options` to `sameorigin`. So showing the result of the GetFeatureInfo request in an IFrame is prohibited.

Tested on Firefox 65.0.1 (64-Bit) and Chromium 71.0.3578.98 (Official Build). Both on an Ubuntu 18.04.  

**To Reproduce**
1. Go to https://openlayers.org/en/v4.6.5/examples/getfeatureinfo-image.html or https://openlayers.org/en/latest/examples/getfeatureinfo-tile.html
2. Click somewhere in the map
3. See that the info box below the map stays empty.
4. By opening a developer console you could see the error due to the 'X-Frame-Options' 
![grafik](https://user-images.githubusercontent.com/1185547/53413177-9a37c000-39cb-11e9-8b32-6b09eb969cf6.png)

**Expected behavior**
By clicking in the map in one of the above mentioned examples one should see the result of the GetFeatureInfo request in the info box below the map.

**Comment by ahocevar** [comment]
I think the iFrame approach is a bit old school. What about updating the examples to use fetch to get feature info?

**Comment by chrismayer** [comment]
Absolutely!

What do think about querying the feature (instead of the HTML) and rendering some exemplary properties in the info box?

**Comment by ahocevar** [comment]
For the sake of simplicity, I'd prefer the HTML query.

**Comment by chrismayer** [comment]
> For the sake of simplicity, I'd prefer the HTML query.

Sure that should be fine for the examples.

**Comment by ahocevar** [comment]
@chrismayer Would you be willing to create a pull request?

**Comment by chrismayer** [comment]
Yes, I will prepare a PR.
