### ISSUE TITLE
The layer is not redrawn when the declutter property is changed

### ISSUE THREAD

**Issue by agiudiceandrea** [openlayers/openlayers#9272]
**Describe the bug**

Using openlayer 4.6.5,

it seems that changing the layer declutter property via

`lyr.setProperties({declutter: true})`
or
`lyr.set({'declutter':'true'})`

does not trigger the layer redraw.

**Comment by ahocevar** [comment]
`declutter` is not an observable property. You have to create a new layer (which can use the same source) with `declutter` set at construction time.

**Comment by agiudiceandrea** [comment]
Thanks @ahocevar!
The only working solution I've found to modify the declutter property on resolution change, is, in fact:

```
 var  lyr_1 = new ol.layer.Vector({
                declutter: true,
                source: lyr_source, 
                style: lyr_style,
                title: lyr_title
            });

 var  lyr_2 = new ol.layer.Vector({
                declutter: false,
                source: lyr_source, 
                style: lyr_style,
                title: lyr_title
            });

var layersList = [lyr_1];

var map = new ol.Map({
    layers: layersList,
    view: new ol.View()
});

map.getView().on('change:resolution', function (e) {
   if (map.getView().getZoom() > 18) {
       if (map.removeLayer(lyr_1)) {
			map.addLayer(lyr_2);
			layersList.splice(layersList.indexOf(lyr_1),1,lyr_2);
	   }
   }
   if (map.getView().getZoom() <= 18) {
       if (map.removeLayer(lyr_2)) {
			map.addLayer(lyr_1);
			layersList.splice(layersList.indexOf(lyr_2),1,lyr_1);
	   }
   }
});
```


I've also tried

```
map.removeLayer(lyr);
lyr.setProperties({declutter: true}) /* lyr.getProperties().declutter returns true
map.addLayer(lyr);

map.removeLayer(lyr);
lyr.setProperties({declutter: false}) /* lyr.getProperties().declutter returns false
map.addLayer(lyr);
```

with no success.

**Comment by ahocevar** [comment]
Why not simply something like
```js
const map = new Map({
  // ...
});
map.addLayer(new ol.layer.Vector({
  declutter: true,
  source: lyr_source,
  style: lyr_style,
  title: lyr_title,
  minResolution: map.getView().getResolutionForZoom(18)
});
map.addLayer(new ol.layer.Vector({
  declutter: false,
  source: lyr_source,
  style: lyr_style,
  title: lyr_title,
  maxResolution: map.getView().getResolutionForZoom(18)
});
```

**Comment by agiudiceandrea** [comment]
I've built the map by QGIS/qgis2web and it seems I need to also update the layersList array (which contains lots of layers in the actual map) in order to make other stuff work correctly and avoid to have greyed out layer items in the legend (using ol-layerswitcher).

**Comment by fredj** [comment]
There is a (non api) `setDeclutter` function in layer/vector but calling the function after the layer creation doesn't work either:
https://github.com/openlayers/openlayers/blob/v5.3.1/src/ol/layer/Vector.js#L156-L161

**Comment by fredj** [comment]
@agiudiceandrea I don't know ol-layerswitcher very much but you could put the two layers into a layer group ?
