### ISSUE TITLE
Initially expanded OverviewMap is blank

### ISSUE THREAD

**Issue by agiudiceandrea** [openlayers/openlayers#9274]
**Describe the bug**
Using openlayer 4.6.5

When the map is displayed with an initially expanded (collapsed: false) OverviewMap control added, the overview map is blank and is it only shows the layer after it is collapsed and then expanded again.

```javascript
var overviewMap = new ol.control.OverviewMap({
	  collapsed: false.
	  layers: new ol.layer.Tile({
		source: new ol.source.OSM()
             	}),
	  view: new ol.View(),
});
map.addControl(overviewMap);

```

**Comment by fredj** [comment]
I cannot reproduce this issue, see https://codepen.io/fredj/pen/NJypGo

**Comment by agiudiceandrea** [comment]
Thanks @fredj for your support!

Better looking at my code (that was actually more complex, initially generated by qgis2web QGIS plugin and then customised by me) I've found that the reported behaviour is caused by the use of **map.getView().fit()** to set the map view extent.

With a **not collapsed OverviewMap control**, if the map view extent is set **after** the OverviewMap control is added to the map, then the overview map is blank https://codepen.io/agiudiceandrea/pen/WmJQLM; if is set **before** https://codepen.io/agiudiceandrea/pen/LampqE, then the overview map is correctly visualised.

With a **collapsed OverviewMap control**, the overview map is ok regardless the map view extent is set **before** or **after** the control is added to the map.

Is this a normal behaviour or it should be fixed?

**Comment by ahocevar** [comment]
As stated in the docs, `fit()` uses the size of the first map it fits. You‘d have to pass it the size of the map as 2nd argument.

**Comment by agiudiceandrea** [comment]
Thanks @ahocevar. As you can see in the previously linked code snippets, the command to set the map view extent (generated by the QGIS/qgis2web plugin) is in fact:

```javascript
map.getView().fit([666205.581372, 4548772.644111, 671179.853857, 4552155.819337], map.getSize());
```

It works fine if it's executed before the control is added to the map
```javascript
map.getView().fit([666205.581372, 4548772.644111, 671179.853857, 4552155.819337], map.getSize());
map.addControl(overviewMap);
```

but not if it's executed after the control is added to the map
```javascript
map.addControl(overviewMap);
map.getView().fit([666205.581372, 4548772.644111, 671179.853857, 4552155.819337], map.getSize());
```
