### ISSUE TITLE
ol.layer.Image + ol.source.Raster loses attributions within it

### ISSUE THREAD

**Issue by ChrisHSandN** [openlayers/openlayers#9281]
**Describe the bug**
An attributions array on a ol.source.XYZ within a ol.layer.Tile _works as expected_: [jsfiddle](https://jsfiddle.net/chris_h/8mgL7s5p/)
```
new ol.layer.Tile({
  extent: ol.proj.transformExtent([-14.169172, 49.205882, 4.393046, 61.483786],'EPSG:4326','EPSG:3857'),
  source: new ol.source.XYZ({
    attributions: ['foobar'],
    url: 'https://nls-{0-3}.tileserver.com/nls/{z}/{x}/{y}.jpg',
    minZoom: 1,
    maxZoom: 14
  })
})
```
The same attributions array on a ol.source.XYZ within a ol.layer.Image / ol.source.Raster _never gets rendered_: [jsfiddle](https://jsfiddle.net/chris_h/8mgL7s5p/21/)
```
new ol.layer.Image({
  extent: ol.proj.transformExtent([-14.169172, 49.205882, 4.393046, 61.483786],'EPSG:4326','EPSG:3857'),
  source: new ol.source.Raster({
    sources: [
      new ol.source.XYZ({
        crossOrigin: 'anonymous',
        attributions: ['foobar'],
        url: 'https://nls-{0-3}.tileserver.com/nls/{z}/{x}/{y}.jpg',
        minZoom: 1,
        maxZoom: 14
      })
    ],
    operation: (pixels) => {
      return pixels[0];
    }
  })
})
```
**Expected behavior**
Both the examples should show "foobar" under the attributions icon.

**Comment by RalphLAtGitHub** [comment]
Please remove the attributions setting from the source definition and add at then end:
`map.getLayers().item(0).getSource().setAttributions("foobar");`

**Comment by fredj** [comment]
Thanks for the bug report, The `getAttributions` function should be added to the `Raster` source.

**Comment by ChrisHSandN** [comment]
Thanks @RalphLAtGitHub, I hadn't spotted the setAttributions() function on ol/source/Raster~RasterSource, that is a great workaround for now.

All the other user data based ol/source/* modules seem to have an 'attributions' in their options constructor so maybe this could also be considered for consistency.

**Comment by KaiVolland** [comment]
I'll try to work on this.
