### ISSUE TITLE
Icon Styles

### ISSUE THREAD

**Issue by jt-helsinki** [openlayers/openlayers#9282]
**Describe the bug**
Icon fonts are showing up as squares.

I have tried specifying the `@font-face` in both the main index.html and in the javascript. 

**To Reproduce**

```
let styles = []
let feature = new Feature({ geometry: geometry});
...
let iconProperties = {
                text: new Text({
                    text: \uf16a,
                    font: 'normal 25px My-Icon-Font',
                    offsetY: 0,
                    offsetX: 0
                })
            };
            styles.push(new Style(iconProperties));

...

return new VectorLayer({
            source: new VectorSource({
                features: [feature]
            }),
            style: styles
        });
```

Add the layer to your map. Icon displays as a square.

**Expected behavior**

A font icon displays.

**Comment by fredj** [comment]
It could be related to the font weight: `normal` is an alias to `400` so if the font doesn't have this weight squares are displayed.

For example, for [FontAwesome](https://fontawesome.com/), I use `'900 18px "Font Awesome 5 Free"'`

**Comment by jt-helsinki** [comment]
Thanks @fredj 

Let me try that.

**Comment by fuoridallarete** [comment]
@fredj I tried your solution, but it didn't solve the issue.
My code:
```
flag.setStyle(
      new Style({
        text: new Text({
          text: '\uf51d', // fas flag solid
          scale: 1,
          font: '900 18px "Font Awesome 5 Free"',
          offsety: -30,
          offsetx: -10,
          fill: new Fill({ color: 'red' }),
        })
      })   
    );
```

**Comment by fredj** [comment]
Hi @fuoridallarete,

I've put a small example in https://codesandbox.io/s/font-awesome-text-0ectn (the font is loaded in the index.html page)

**Comment by fuoridallarete** [comment]
Thanks for your quick answer (and solution) @fredj. It works. I was stupidly missing the css link in the html. 
xx
