### ISSUE TITLE
Issues in ol.source.raster

### ISSUE THREAD

**Issue by saurabhgis** [openlayers/openlayers#9283]
Dear All Users,
I am using openlayers raster source (ol.source.Raster) and want to store pixel values in declared public array but array not accessible inside operation "operation: function (pixels, data) {......." please help in this regard.

I also tried to declared that array in lib: but not succeed.....

...please suggest

**Comment by fredj** [comment]
Please ask usage questions on stackoverflow instead with the tag openlayers
https://stackoverflow.com/questions/tagged/openlayers
