### ISSUE TITLE
WMTS tile transitions broken

### ISSUE THREAD

**Issue by thomasmoelhave** [openlayers/openlayers#9284]
**Describe the bug**
The smooth WMTS tile transitions introduced with #5795 from #4455 are broken in v6.0.0-beta1. See  #4455 for an extensive discussion and motivation. This affects, among other things, the "WMTS Tile Transitions" example.

**To Reproduce**
1. Use npm run serve-examples
2. Visit http://localhost:8080/wmts-dimensions.html , drag the slider
3. Notice the map disappears when the dimension changes
4. Compare to the smooth behavior in the [v5.3.0 example](https://openlayers.org/en/v5.3.0/examples/wmts-dimensions.html).

**Expected behavior**
The tiles from the most-recently-acquired zoom setting should be rendered until the next tile is ready.  

I have created a [video showing the difference](https://scalgo.com/download/ol-v6.0.0-beta1-issue.mkv) between v6.0.0-beta1 and v5.3.0.

**What now?**

I understand there has been quite a lot of changes in v6.0.0 related to the internals of how layers are rendered. Does anyone have an idea about what happened, and how to fix it?

**Comment by thomasmoelhave** [comment]
I ran a git bisect and the first commit that has an issue is 5ba8795355077affc91b0b1e63a59a66dc637025. Maybe that's not a surprise since it looks like that's where the rendering changed to a new method.

**Comment by ahocevar** [comment]
Thanks for the bug report @thomasmoelhave. #9286 should fix this.

**Comment by thomasmoelhave** [comment]
Thanks @ahocevar!
