### ISSUE TITLE
Failing test (ol.control.ScaleLine)

### ISSUE THREAD

**Issue by KaiVolland** [openlayers/openlayers#9288]
**Tests - Failing**

Currently the `ol.control.ScaleLine` test is failing under the following requirements:
- Linux Mint 19.1 Tessa (Ubuntu 18.04)
- Node 8.11.3 or 10.15.0

```
Chrome 74.0.3723 (Linux 0.0.0) ol.control.ScaleLine projections affect the scaleline Projection's metersPerUnit affect scale for non-degree units FAILED
	Error: expected '0.000049999999999999996 nm' to equal '0.00005 nm'

```

IMHO it is a Bug in the Chrome-Version (74.0.3723) which gets [launched via puppeteer](https://github.com/openlayers/openlayers/blob/master/test/karma.config.js#L77).

Math.pow seems to be broken:

```js
// Chrome-Version (71.0.3578.98)
console.log(Math.pow(10, -5)); // 0.00001

// Chrome-Version (74.0.3723)
console.log(Math.pow(10, -5)); // 0.000009999999999999999
```

**To Reproduce**
1. Fresh checkout
2. `npm i`
3. `npm run test` or `npm run karma`

**Possible Solution**
The [current karma config](https://github.com/openlayers/openlayers/blob/master/test/karma.config.js#L77) uses the chrome binary which gets installed via puppeteer. This seems to be the canary/dev build and not the stable chrome version. I think it would be better to use the stable chrome version for the tests.
Of course this is not a bug within OpenLayers but it leads to failing tests which might be avoided.

**Expected behavior**
No test should fail.

**Comment by marcjansen** [comment]
> I think it would be better to use the stable chrome version for the tests.

I thought we had this already…

However, I would like to see such a change. Please create a PR.

**Comment by KaiVolland** [comment]
Currently used version of puppeteer is `^1.12.2` which [should use Chromium 73.0.3679.0](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md). In fact it installed 74.0.3723 for me.
Current stable version is [72.0.3626.121](https://omahaproxy.appspot.com/) which is used by pupepeteer 1.11.0. I'll prepare a PR soon.
