### ISSUE TITLE
Canvas elements not garbage collected on iOS 12

### ISSUE THREAD

**Issue by esseb** [openlayers/openlayers#9291]
**Describe the bug**
Safari on iOS 12 has a bug where it doesn't properly garbage collect canvas elements unless you explicitly give the canvas elements a width and height of `0` when they are no longer meant to be used. See https://bugs.webkit.org/show_bug.cgi?id=195325 and the reduced testcase I attached to that bug report.

I previously described this bug in https://github.com/openlayers/openlayers/issues/9166 but I'm creating a new issue now that I have more information since my bug is a bit different.

**To Reproduce**
1. Open https://dist-gkmkekevph.now.sh on an iPhone running iOS 12 (I'm using iOS 12.1.4 on an iPhone X)
2. If possible, connect the iPhone to a Mac and debug Safari on the iPhone via Safari on the Mac using devtools
3. Click the `Destroy map` button and then the `Create map` button
4. Repeat step 3 several times (it takes me about 14 destroy/create clicks before I get the error)
5. Safari either fails with the message "This web page was reloaded because a problem occured", or the map silently fails and becomes white and the console tab in devtools (if you did step 2) will show the message "Total canvas memory use exceeds the maximum limit (288 MB)."

**Expected behavior**
The map should continue to work fine no matter how many times you destroy and recreate the map in step 3.

**Further information**
The testcase uses ol@6.0.0-beta.2 and the source is available on https://github.com/esseb/openlayers-ios-canvas-memory

The testcase may make it seem like this bug is extremely obscure and unlikely to occur in the wild, but the severity of the bug depends on how developers use the map. My testcase doesn't create or hide a lot a of layers in order make it as simple as possible. I can hit the bug very quickly on https://www.yr.no/en/map/weather/1-72837/Norway/Oslo/Oslo/Oslo if I go from the "Map" tab to the "Overview" tab and back to the "Map" again a single time on an iPhone X.

Based on the reduced testcase I created for the bug report I sent to WebKit (see the description at the top) I believe OpenLayers has to explicitly give canvas elements a width and height of 0 when they are no longer necessary.

**Comment by esseb** [comment]
No problems on iOS 11 (tested on browserstack, I don't know the exact OS version since they don't list it).

No problems on Chrome v72.0.3626.121 on Samsung S9.

This issue is visible in Safari on Mac also, not just iPhone, but the higher canvas memory limit makes it much more difficult to trigger the bug there. However, if you open the testcase on Safari on Mac, open devtools and switch to the "Canvas" tab, then follow the test instructions to destroy/create the map several times you can see the list of canvas elements increase each time the map is recreated and (almost) never decrease.

**Comment by ahocevar** [comment]
We set the canvas width and height to 0 already for labels and vector tiles. We'd gladly accept a pull request to do the same elsewhere.

**Comment by esseb** [comment]
Do you have any hints where to begin? The canvas code in OpenLayers was a bit challenging to unwrap when I attempted yesterday.

**Comment by fredj** [comment]
@esseb we've added more canvas cleaning in #9306

**Comment by esseb** [comment]
@fredj I updated https://github.com/esseb/openlayers-ios-canvas-memory to use 6.0.0-beta-3 now, which includes your fix, available at https://dist-ccrpdkwnih.now.sh

Unfortunately there is no change. Safari warns "Total canvas memory use exceeds the maximum limit (288 MB)." after recreating the map about 9 times.

**Comment by fredj** [comment]
See #9556 and #9561

**Comment by ninaDeimos** [comment]
Is this possible that this problem is also present in ol@5.x?

**Comment by ahocevar** [comment]
Yes, it was only fixed in ol@6

**Comment by ninaDeimos** [comment]
Would it be possible to provide a backport to v5, since v6 might not come out very soon?

**Comment by ahocevar** [comment]
Please install v6, the betas are very mature already.

    npm install ol@beta

**Comment by alyywehby** [comment]
I am using ol@6.1.1 and facing the same issue! I am using openlayers with ionic and I have a lots of layers to load on map! After loading them for the second time i will get this issue. `Total canvas memory use exceeds the maximum limit (224 MB)` and after that non of the layers will load on map. Is there any work around or hack to solve this issue?

**Comment by ahocevar** [comment]
There has been a lot of work around this since 6.1.1. Please upgrade to the latest.

**Comment by alyywehby** [comment]
@ahocevar I upgraded the ol to 6.3.1 and I also set the pixel ratio property on the Map to 1.
`this.map = new Map({ pixelRatio: Math.min(window.devicePixelRatio, 1), projection: this.mapProjection, layers: [this.googleLayer] })`
and I still have the same issue.

**Comment by ahocevar** [comment]
Then you probably have too many layers. The solution is to re-organize your app to show less layers at the same time.
