### ISSUE TITLE
tileLoadFunction of format MVT throws error in ol 6.0.0

### ISSUE THREAD

**Issue by RobertOrthofer** [openlayers/openlayers#9293]
When creating a custom `tileLoadFunction` of `ol/source/VectorTile` in ol v6.0.0, the Projection, the Extent and the Features of the tiles have to be set in this exact order (see [documentation](https://openlayers.org/en/master/apidoc/module-ol_source_VectorTile-VectorTile.html))

According to the documentation, the extent of the MVT-tile should be set with `format.getLastExtent()`, resulting in an error, since `format.getLastExtent()`only returns the extent if the Features were read beforehand.

I have also tried to change the order to set the Features of the tile first and the extent after, which breaks all of the tiles. 

My workaround for now is calling a `format.readFeatures()` for no value, which most likely is not the intended use.

**Comment by ahocevar** [comment]
Hm. This is indeed a problem. Looks like we need to refactor how we parse and transform features when using the MVT format. Before #9231, this problem was obscured because we returned a default. This is something that should be fixed before we release v6.0.

**Comment by ahocevar** [comment]
To fix this, the VectorTileLayer renderer needs to be refactored. Currently, its `updateExecutorGroup_` method transforms geometries when they are first used. That is quite late in the process. It should be the responsibility of the loader to transform geometries. The loader should know about the view projection, so it should be possible to make such a chance.

Anyone willing to try?

**Comment by pakb** [comment]
I can give it a shot, I might need some guidance.
When you're talking about "the loader", are you talking about `featureloader.js` and specifically the `xhr.onload` part?

**Comment by ahocevar** [comment]
@pakb Thanks for willing to help out. Yes, that's what I'm talking about. Currently `ol/VectorTile` has a `load()` function which does not pass the view projection to `this.loader_`. But the projection information could be set on the source tile right after its creation in `ol/source/VectorTile#getSourceTiles()`, and then `ol/VectorTile#load()` could call `this.loader_(null, NaN, this.projection_)`.

**Comment by ahocevar** [comment]
@pakb Do you think you'll be able to handle this, or should I make the necessary changes? Without knowing your way around in the library, this could be a bit challenging.

**Comment by pakb** [comment]
Yes it is quite the challenge. Maybe it was a bit too optimistic for a first contribution.
If you can do it, it will be done way faster, as this is blocking other issues it’s maybe better this way
