### ISSUE TITLE
Missing documentation of ol/format/MVT

### ISSUE THREAD

**Issue by RobertOrthofer** [openlayers/openlayers#9294]
In master, most of the documentation of ol/format/MVT has gone missing (it is still available in ol v5.3.0).
The functionality however is still intact, but switching between different documentations inadvertently lead to bugs.

**Comment by ahocevar** [comment]
Thanks for reporting this @RobertOrthofer. Documentation of many functions marked with `@inheritDoc` appear to be missing. Maybe not only for the MVT format, but elsewhere too. I thought that was fixed already? Looks like the API docs need some more love before we can publish v6.0.

Any takers for a pull request?

**Comment by KaiVolland** [comment]
I'll try to work on this.

**Comment by KaiVolland** [comment]
I only get this working when adding `@api` to the abstract function in the parent class.
But the `readme.md` explicitly says to avoid this.

Should i try to fix this in the plugin code?

**Comment by ahocevar** [comment]
> Should i try to fix this in the plugin code?

That would be perfect, thanks!
