### ISSUE TITLE
V 5.2.0  cdn ol.js is not complete

### ISSUE THREAD

**Issue by Kacpar** [openlayers/openlayers#9297]
I use https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.2.0/build/ol.js
and one day things don't work.
v5.2.0 ol.js is 40KB 
v5.3.0 ol.js is 640KB

With v5.3.0 I get errors:
code: 6
message: "Assertion failed. See https://openlayers.org/en/v5.3.0/doc/errors/#6 for details."
name: "AssertionError"

**Comment by ahocevar** [comment]
The former was probably a download error, and the latter is an error in your application. If you follow the link to the assertion details, you'll see that you probably use an icon style without `img` or `src` defined.
