### ISSUE TITLE
More efficient measureTextWidth

### ISSUE THREAD

**Issue by Jinkwon** [openlayers/openlayers#9301]
measureText()  is so much slow API but we need it though.
In Openlayers case, cache the value only words. (low cache hit rate)
What if split word to separated character and measure it with cache, it can be more efficient hit the cache.

<img width="602" alt="2019-03-08 10 49 43" src="https://user-images.githubusercontent.com/1798916/54001811-e505c480-418f-11e9-86d6-8611331f4184.png">

**Comment by ahocevar** [comment]
We've had that before, but it gives incorrect results for fonts that have ligatures. This is a huge problem e.g. for Arabic languages, but even for the Latin alphabet (e.g. "fi").
