### ISSUE TITLE
Collect and report coverage (again)

### ISSUE THREAD

**Issue by KaiVolland** [openlayers/openlayers#9303]
**Code Coverage**
We used to collect and report coverage. But due to internal changes we temporarily stopped doing so.
We should reintroduce coverage collection and reporting to a service (most likely coveralls).

**Fix karma-coverage configuration**

**Comment by KaiVolland** [comment]
Couldn't make any progress on this.
Main problems i had:
- Finding an accurate config and tool chain
- Coverage calculation is based on transpiled files
- JavaScript heap out of memory

I'm kind of lost in the jungle of packages, plugins, preprocessors and reporters each comming with their own config. So i'll pause working on this for know.

**Comment by jahow** [comment]
Hi @KaiVolland, I'll look into this issue if that's okay and post progress here.

**Comment by KaiVolland** [comment]
Hey @jahow thats totally ok! Good luck.

**Comment by jahow** [comment]
Quick update: I managed to get the Istanbul coverage report working again, but *that required switching bublé for babel* in the webpack config used for the tests. Will make a PR soon with this change to see how CircleCI will handle the reports.

**Comment by jahow** [comment]
Draft PR created: #9388

**Comment by marcjansen** [comment]
Fixed with #9388
