### ISSUE TITLE
Stamen source terrain minZoom seems incorrect

### ISSUE THREAD

**Issue by bartvde** [openlayers/openlayers#9304]
https://github.com/openlayers/openlayers/blob/master/src/ol/source/Stamen.js#L77

minZoom is set to 4, but tiles are available for level 0

http://b.tile.stamen.com/terrain/0/0/0.png

**Comment by ahocevar** [comment]
I think it's safe to change this. The [documentation](http://maps.stamen.com/) does not mention any min zoom restrictions for terrain.

**Comment by fredj** [comment]
Same for the `watercolor`, tiles are available for level 0:
https://github.com/openlayers/openlayers/blob/master/src/ol/source/Stamen.js#L85

https://stamen-tiles-a.a.ssl.fastly.net/watercolor/0/0/0.jpg

**Comment by bartvde** [comment]
cool I'll create a PR
