### ISSUE TITLE
RTL text following a line

### ISSUE THREAD

**Issue by HarelM** [openlayers/openlayers#9309]
**Describe the bug**
The label set to a line is getting cut and misplaced when using RTL language.
The label breaks according to line angle changes, but the text is not written as it should.
Might be related to #7367.

**To Reproduce**
I have created a small stackblitz that can demonstrate the issue. Let me know if you need it with less code as I'm using olms in order to present a layer.
https://stackblitz.com/edit/angular-openlayers-mapbox-local-issue-with-labels

**Expected behavior**
The label should read סינגל הרצל multiple times.

**More details**
[Hertzel Single in OSM](https://www.openstreetmap.org/relation/2093275)
Here's an image of a green line with the same label - סינגל הרצל - you can see how the text breaks differently according to the line:
![image](https://user-images.githubusercontent.com/3269297/54083311-6729f080-432a-11e9-8d70-d16558e1f3e2.png)

This happens with latest stable version.
Let me know how I can help out, This is currently a show-stopper for us for using vector tiles.
I'd be happy to help out, but I'm guessing I'll only be able to help testing as I'm not very familiar with the ol code itself...

**Comment by ahocevar** [comment]
A fix would be quite involved, a workaround is to configure the `ol/style/Text` with `maxAngle: 0`. Then you'll only get labels that don't bend, so text is not split and RTL is kept.

**Comment by HarelM** [comment]
@ahocevar Thanks a lot for the quick response and possible workaround!
Let me know if I can assist in any way.

**Comment by HarelM** [comment]
I have added to the above example the `text-max-angle` in mapbox style and it doesn't seems to have any effect. Should I open an issue in ol-mapbox-style repository?

**Comment by ahocevar** [comment]
> I have added to the above example the text-max-angle in mapbox style and it doesn't seems to have any effect. Should I open an issue in ol-mapbox-style repository?

Yes please, and maybe even a pull request. Because the option is not supported there yet.

**Comment by HarelM** [comment]
@ahocevar now that max angle is solved, can you point me to the place in the code that cuts the text on the line and I'll see if I manage to understand it enough in order to fix it?

**Comment by ahocevar** [comment]
@HarelM The `drawTextOnPath` function in https://github.com/openlayers/openlayers/blob/8b50c3c6cbc37c89eaa0f7ea4a471368196eb4f2/src/ol/geom/flat/textpath.js is responsible for cutting the text.

**Comment by HarelM** [comment]
Yes, I looked at the code yesterday, got to textbuilder and executor and figured out that is way over my head...
I'm not even sure what's the right solution as the text is being cut in one place and rendered in another, as far as I could see...
If you have any thoughts of how to solve this I'll be happy to hear.
I also don't know how to solve this for a more general problem where you have both rtl and ltr text in the same sentence...
Having said that, solving this only for a single language would work for me.
In any case, I'll be happy to lend a hand but I feel I'll need some ramp-up before I can help and I'm not sure what would be the right way to achieve it...

**Comment by ahocevar** [comment]
I don't know enough about how RTL text works. But a few additional bits of information that might help you:

* The canvas used to render text (see `ol/render/canvas/Executor#getTextImage()`) has the default behavior (i.e. `dir="auto"`). So for text that is not split, it will work.
* When text is split (in `ol/geom/flat/textpath.drawTextOnPath`), we lose this logic.

A solution might be to use https://www.npmjs.com/package/@mapbox/mapbox-gl-rtl-text on the application level to reorder strings to be in proper rtl order, and add an option to OpenLayers to always use `dir="ltr"` for the canvas used to render text, or make it inherit the `dir` property from the map div.

**Comment by HarelM** [comment]
Thanks for the extra info! I'll take a look at the references you sent.
Do you have any clue as to how mapbox solved this? Do you know if they are using the referenced project?

**Comment by ahocevar** [comment]
> Do you have any clue as to how mapbox solved this? Do you know if they are using the referenced project?

They do. It is actually a package they created for this exact purpose.

**Comment by HarelM** [comment]
Ok, so I'll try and understand how it works and if it's possible to integrate it to solve this issue.
I would very much like to solve this but I don't have high hopes.
I'll report here in case I make any breakthrough.

**Comment by HarelM** [comment]
Sorry, but I won't be pursuing this issue.
I'll be happy to help out regarding RTL languages as I know both Hebrew and Arabic (to some extent).
Ping me if you need to make sure something is as expected.
Sadly it seems that openlayers does not meet the required performance I need for vector tiles.
The following example works well on desktop browser but is extremely sluggish on my mobile device (which is not state of the art but also not too bad):
https://openmaptiles.org/viewers/
I know ol 6 focuses on vector tile performance, but I'm not sure it will improve the user experience to a decent level and also I can't wait for it to stabilize...
Keep up the good work though!

**Comment by ramSeraph** [comment]
svg can do shaped text along a curve, is it possible to use that for fixing this problem? I have seen this fail with indic scripts as well.

**Comment by ahocevar** [comment]
@ramSeraph I tried this approach already, but the performance is very inferior to canvas rendering.

**Comment by ramSeraph** [comment]
@ahocevar Was trying to place the text on a path using svg at various possible locations on the path the reason for the performance degradation or any involvement of svg even if it is once for a text going to cause a performance degradation? 

I am asking because I think you can extract individual typological character( indivisible character clusters ) rendered blocks by rendering the text once using svg and can the reuse those indivisible rendered blocks with the current algorithm of placing the char blocks on the line manually.

I haven't really tested it.. but it might be possible

**Comment by ahocevar** [comment]
That would work, but I think it would make sense to compare that with the use of a bidi library and use individual chars rendered with the current approach. If you are interested in moving this forward, would you be able to investigate this further and submit a pull request eventually?

**Comment by ramSeraph** [comment]
@HarelM I am aware of the bounty, I am on that discussion. That's why I am a bit skeptical that it can be this simple. Let's see.
