### ISSUE TITLE
Zoom on a feature

### ISSUE THREAD

**Issue by Lory1990** [openlayers/openlayers#9316]
**Is your feature request related to a problem? Please describe.**
I want to zoom on a single feature, regardless the mouse pointer position

**Describe the solution you'd like**
I would like to zoom with the mouse theel or the touch gesture on a feature, the view should move and zoom at the same time to make the feature everytime at the "same" position

**Comment by ahocevar** [comment]
This is possible already using the `ol/View`'s `fit()` method:
```js
view.fit(feature.getGeometry());
```

**Comment by Lory1990** [comment]
Fantastic, when should i trigger this event? 

Now i trigger a view.fit() event on `map.on('moveend', handleMoveEnd)`

**Comment by Lory1990** [comment]
I added the event on `map.on('movestart', handleMoveStart)`.

User experience is better experience but the effect is not so smooth and sometimes does not work
