### ISSUE TITLE
Testing Vue components OL with jest isn't working (vue-cli-3, jest)

### ISSUE THREAD

**Issue by skortabeast** [openlayers/openlayers#9317]
I'm trying to test a map component in my application (created with 'vue-cli 3').
Tests are crashing at when inport Map
`import PluggableMap from './PluggableMap.js';
SyntaxError: Unexpected identifier
`

my jest config:
`module.exports = {
      moduleFileExtensions: [
        'js',
        'jsx',
        'json',
        'vue'
      ],
      transform: {
        '^.+\\.vue$': 'vue-jest',
        '.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$': 'jest-transform-stub',
        '^.+\\.jsx?$': 'babel-jest',
          '^.+\\.js$': 'babel-jest'
      },
      moduleNameMapper: {
        '^@/(.*)$': '<rootDir>/src/$1',
          "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": '<rootDir>/src/$1',
          "\\.(css|less|scss|sass)$": "identity-obj-proxy"
      },
      snapshotSerializers: [
        'jest-serializer-vue'
      ],
      testMatch: [
        '**/tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx)'
      ],
      testURL: 'http://localhost/',
      collectCoverage: true,
      coverageReporters: [
          "json",
          "html"
      ],
      collectCoverageFrom: [
          "**/*.{js,vue}",
          "!**/node_modules/**"
      ],
      coverageDirectory: '<rootDir>/tests/unit/coverage',
      coveragePathIgnorePatterns: [
          "<rootDir>/node_modules"
      ],
      transformIgnorePatterns: ['/node_modules/(?!.+/es/)',  "/node_modules/(?!(ol)/).*/",
    "node_modules/(?!(ol)/)" ],
      moduleDirectories: ["node_modules", "src"],
};
`
transformIgnorePatterns  isn't working

**Comment by bartvde** [comment]
this worked for me recently:

```
```json
    "transform": {
      "($ol).+\\.js$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "/node_modules/(?!ol)"
    ],
```

**Comment by skortabeast** [comment]
@bartvde  isn't working for me
![image](https://user-images.githubusercontent.com/10978770/54180356-521ca100-4493-11e9-9a99-d7c7b555fb73.png)

**Comment by bartvde** [comment]
what jest version are you on?

**Comment by bartvde** [comment]
see also previous discussion in #7401

**Comment by bartvde** [comment]
ah ok this looks like jest 23 I was using 24

**Comment by skortabeast** [comment]
https://github.com/vuejs/vue-test-utils/issues/1181#issuecomment-472129227
