### ISSUE TITLE
Shifted pointer pointermove

### ISSUE THREAD

**Issue by Lory1990** [openlayers/openlayers#9324]
**Browser**
Chrome
Firefox

**OL version**
5.3.1

**Describe the bug**
The pointer icon is shifted respect the feature

**To Reproduce**

1. Create a React app
2. Create map with multiple layers and feature
3. Add event listener `pointermove`

```
this.map.on('pointermove', (e) => {

  if (e.dragging) return;

  const pixel = map.getEventPixel(e.originalEvent);
  
  let hit = false;
  
  this.map.forEachFeatureAtPixel(pixel, (feature, layer) => {
    if (layer === 'BackLayer') {      
      hit = true
    }
  }
  
  map.getTargetElement().style.cursor = hit ? 'pointer' : '';
  
}
```

![Capture](https://user-images.githubusercontent.com/7715601/54294785-23e1b300-45b2-11e9-9d66-5b11c53ea9f7.PNG)

this behaviour does not happen everytime O.o

**Expected behavior**
Cursor pointer shows exactly on the feature, if outside the feature cursor must be the default one

**Comment by fredj** [comment]
you seem to have an icon in you screenshot; do you observe this while the cursor is above this icon or above the line? (or both?)

**Comment by Lory1990** [comment]
When the pointer is on the icon  it is the default one, outside the icon it turns into the Hand

Anyway don't care about the line and the poly, the icon represents a feature with specific position

**Comment by fredj** [comment]
can provide a minimal example in a CodePen or similar that shows the issue?
