### ISSUE TITLE
VectorImageLayer with ClusterSource disappears after loading

### ISSUE THREAD

**Issue by jippeholwerda** [openlayers/openlayers#9326]
**Describe the bug**
I'm using version 6.0.0-beta.3 in my Angular app and have the following map:

```typescript
this.clusterSource = new ClusterSource({
    distance: 10,
    source: this.broSource,
    geometryFunction: feature => new geom.Point(extent.getCenter(feature.getGeometry().getExtent()))
});

this.clusterLayer = new VectorImageLayer({
    source: this.clusterSource,
    style: new style.Style({
        image: new style.Circle({
            radius: 10,
            stroke: new style.Stroke({
                color: '#fff'
            }),
            fill: new style.Fill({
                color: '#3399CC'
            })
        }),
        text: new style.Text({
            text: '3',
            fill: new style.Fill({
                color: '#fff'
            })
        })
    })
});

this.map = new Map({
    target: 'map-canvas',
    layers: [this.clusterLayer],
    view: this.view,
    interactions: interaction.defaults({mouseWheelZoom: false})
});
```

When the cluster layer is loaded, the features in the layer can be briefly seen, after which they disappear again.

I've noticed the same behaviour when I use a VectorLayer instead of a VectorImageLayer,

A javascript version (5.3.0) with the exact same clustered layer is working correctly.

**Expected behavior**
For the cluster layer to remain visible.

**Comment by fredj** [comment]
Can you please provide a minimal example in a CodePen or similar that shows the issue ? Thanks

**Comment by jippeholwerda** [comment]
Is there a hosted version of the v6.0.0-beta.3 release somewhere that I can use in a CodePen?

**Comment by fredj** [comment]
That's actually not needed: this issue can be reproduced with the [cluster](https://openlayers.org/en/master/examples/cluster.html) example. The features disappear  as soon as the slider is changed.

**Comment by jippeholwerda** [comment]
Ah, so it seems to be an issue with 5.3.0 as well?

**Comment by fredj** [comment]
> Ah, so it seems to be an issue with 5.3.0 as well?

No, the example in version 5.3.0 works:
https://openlayers.org/en/v5.3.0/examples/cluster.html

But not the master version:
https://openlayers.org/en/master/examples/cluster.html

**Comment by fredj** [comment]
The change in the pull request #9329 fixes the cluster example.

**Comment by fredj** [comment]
@jippeholwerda The fix is now merged into master and will be available in the next (beta) release.
I'm closing this issue, if your problem still persist after using the new upcoming version please open a new issue.
