### ISSUE TITLE
Performance of much  Layer(vectorLayer) on map

### ISSUE THREAD

**Issue by vampire1995** [openlayers/openlayers#9331]
I use the method(addLayer) to add vectorLayer on map.when the number of VectorLayer is 1,it's ok!  
    But if the number is 2 or more,the performance getting  poorer and poorer.   </br>                                                               I need about 10 vectorLayer ,and the performance is also good ,could anybody help me,thank you!!

**Comment by ahocevar** [comment]
Try to update to OpenLayers 6 (currently ol@6.0.0-beta.3), that should give you much better performance with multiple layers.

**Comment by vampire1995** [comment]
> Try to update to OpenLayers 6 (currently ol@6.0.0-beta.3), that should give you much better performance with multiple layers.

I try to update to ol@6.0.0-beta.3 now.</br>But after the update ,I can't find Graticule.js in node_modules\ol,</br>then I copy the Graticule.js which in ol@5.2.0 to ol@6.0.0-beta.3,</br>and it report an error from Graticule.js: </br>  Cannot read property 'setFillStrokeStyle' of undefined(from Graticule.js:655)   </br>PS:The performance has definitely improved !

**Comment by ahocevar** [comment]
Please see the upgrade notes: https://github.com/openlayers/openlayers/blob/dfabcc0/changelog/upgrade-notes.md#the-olgraticule-has-been-replaced-by-ollayergraticule. `Graticule` is now a layer.

**Comment by vampire1995** [comment]
> Please see the upgrade notes: https://github.com/openlayers/openlayers/blob/dfabcc0/changelog/upgrade-notes.md#the-olgraticule-has-been-replaced-by-ollayergraticule. `Graticule` is now a layer.

I get it, thanks for your answer !
