### ISSUE TITLE
codesandbox not working for version 6

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#9332]
https://codesandbox.io/s/884vv79vxj
This is the simple example with the `ol` version changed to `6.0.0-beta.3` in `package.json`.

The map's div height is 0.

**Comment by fredj** [comment]
Looks like everything in the `head` tag of the `index.html` page is ignored by codesandbox

**Comment by ahocevar** [comment]
Maybe a temporary issue, because the examples used to work fine there. Can you please create a ticket at https://github.com/CompuIves/codesandbox-client?

**Comment by fredj** [comment]
> Looks like everything in the `head` tag of the `index.html` page is ignored by codesandbox

That's because we're using the default codesandbox template (`create-react-app`) and this template doesn't load the head tag.

patch to come

**Comment by fredj** [comment]
#9335 doesn't fix the issue, the map's height is still 0

Adding the following in the head fixes the issue.
```css
.map {
  width: 100%;
  height: 400px;
}
```

I think something changed between version 5 and 6
