### ISSUE TITLE
fromLonLat bad results with strings

### ISSUE THREAD

**Issue by hugo-hebert** [openlayers/openlayers#9334]
Issue I encountered when trying to use strings as coordinates.

ol.proj.fromLonLat(["6.840919", "47.481497"], "EPSG:3857")
ol.proj.fromLonLat([6.840919, 47.481497], "EPSG:3857")

These two lines return different results. 
The first returns : [ 761527.6196380304, -5238967.778897062 ]
And the second returns: [ 761527.6196380304, 6021023.848864606 ]

I checked on https://epsg.io/transform, and the string conversion seems broken.

**Comment by ahocevar** [comment]
Coordinates are expected to be `number`, so don't try to pass `string`s.

**Comment by ThomasG77** [comment]
A simple fix is to use map to cast String coordinates to Number coordinates e.g

    ol.proj.fromLonLat(["6.840919", "47.481497"].map(coord => Number(coord)), "EPSG:3857")

**Comment by ahocevar** [comment]
Or simply `fromLonLat(["6.840919", "47.481497"].map(Number));`
