### ISSUE TITLE
Is plan to asynchronously render features?

### ISSUE THREAD

**Issue by egaoneko** [openlayers/openlayers#9338]
As you already know, if the number of features or the execution time of style function increases, there is a performance issue because they are interpreted synchronously.

![image](https://user-images.githubusercontent.com/6583941/54436658-47555b00-4776-11e9-9219-807f57c07973.png)
* https://openlayers.org/en/latest/examples/synthetic-points.html?q=points

So I wonder does ol plan to asynchronously render features.

**Comment by ahocevar** [comment]
In version 6, instruction groups for vector tile layers are created asynchronously already. That was a major refactoring. For vector layers, this would also be possible, but a huge effort.

**Comment by egaoneko** [comment]
@ahocevar That's good news for me. I'll find things to contribute
