### ISSUE TITLE
Map scaleline in metric unit the zoom rate 5km and 5m repeated twice for two different zoom levels

### ISSUE THREAD

**Issue by Sarath199O** [openlayers/openlayers#9339]
**Describe the bug**
In the Map scaleline control in metric unit the zoom rate for 5km and 5m displayed twice for two different zoom levels

**To Reproduce**
1. Open openlayer scaleline control map(https://openlayers.org/en/latest/examples/scale-line.html)
2. Click zoom-in(+) icon
3. At 5km zoom resolution, if we press zoom in(+) button, the zoom rate stays at same(5Km) but the zoom level differs(gets one level zoomed in). The same happens at 5m zoom rate.

**Expected behavior**
Similar to 500km to 200km zoom rate or 50km to 20km zoom rate change happens when zoom in. This could also be changed to 5km to 2km and 5m to 2m for respective zoom rate during zoom in.

**Comment by ahocevar** [comment]
This depends on where the center of your map is, and has to do with the Web Mercator projection where longitudes are stretched to the poles. If you try what you describe e.g. over North Norway, you'll see the expected behavior.
