### ISSUE TITLE
Zoom Slider behaving odd on Chrome with force-device-scale-factor

### ISSUE THREAD

**Issue by 1Map** [openlayers/openlayers#9340]
I have my chrome to start with the extra parameter on my 4K screen "force-device-scale-factor=1.75"

With this setting, the zoom slider does not work as expected - thumb stays behind cursor.

With "force-device-scale-factor=1" it works as expected.

**Comment by 1Map** [comment]
I must say, I am working in v4.6.5 and want this fix in 4.6.5

**Comment by 1Map** [comment]
Please do not close as this is not fixed.

**Comment by ahocevar** [comment]
Please provide an example that shows the issue if it still occurs in latest master or the latest beta (v6.0.0-beta.8).

**Comment by 1Map** [comment]
Please read my comments above:
"I must say, I am working in v4.6.5 and want this fix in 4.6.5"

**Comment by ahocevar** [comment]
I did read that, hence my question. Tickets are more likely to get resolved when the ticket creator is able to provide the information that is asked for.

Another way to get tickets resolved is to buy support. If you're interested in going that route, you can find service providers e.g. on https://www.osgeo.org/service-providers/ (type "openlayers" in the search field)
