### ISSUE TITLE
Make zDirection controllable for image tiles

### ISSUE THREAD

**Issue by lutzhelm** [openlayers/openlayers#9343]
**Is your feature request related to a problem? Please describe.**
When image quality is more important than speed or low bandwidth use, it might be preferable to display tiles of the next higher resolution instead of the closest resolution if the current view resolution does not exactly match any tile source resolution. If I am not mistaken, it is currently not possible to set `zDirection` via any TileLayer or TileGrid option or via any other way.

https://github.com/openlayers/openlayers/blob/3f7c52c29f0fd667ee3356300cecfc53e88ff48a/src/ol/tilegrid/TileGrid.js#L523-L534

To demonstrate the problem, here are two screenshots of the same example of the [IIIF tile source](https://github.com/lutzhelm/openlayers/blob/iiif/src/ol/source/IIIF.js) I've been working on (see #9323), one with default `zDirection = 0` and one with `zDirection = -1`. The behavior will probably be the same for other image tile sources.

Closest resolution:
![Closest resolution](https://lutzhelm.github.io/iiif-zdirection-closestres.png)

Next higher resolution:
![Next higher resolution](https://lutzhelm.github.io/iiif-zdirection-higherres.png)

**Describe the solution you'd like**
`zDirection` could be an option of either `ol/tilegrid/TileGrid~TileGrid` or `ol/layer/Tile~TileLayer`. The latter case is probably preferable. `ol/renderer/canvas/TileLayer~CanvasTileLayerRenderer` could then initialize it's `zDirection` property according to the layer's `zDirection`.

https://github.com/openlayers/openlayers/blob/3f7c52c29f0fd667ee3356300cecfc53e88ff48a/src/ol/renderer/canvas/TileLayer.js#L64

**Comment by ahocevar** [comment]
Adding a `zDirection` option to tile layers sounds reasonable. Pull request accepted.

**Comment by lutzhelm** [comment]
Simply adding `zDirection` to the tile layer would have some unwanted side effects. I'm not too familiar with the OpenLayers code, but I identified some spots in the code that make me hesitant.

### `ol/tilegrid/TileGrid~TileGrid#getTileCoordForXYAndResolution`

`ol/tilegrid/TileGrid~TileGrid#getZForResolution` is also used by `ol/tilegrid/TileGrid~TileGrid#getTileCoordForXYAndResolution` via `ol/tilegrid/TileGrid~TileGrid#getTileCoordForXYAndResolution_`.
`ol/tilegrid/TileGrid~TileGrid#getTileCoordForXYAndResolution` is used by some tile sources.

**BingMaps**
The `BingMaps` source provides attributions dependent on the tile coordinates and resolution. If the source uses a different strategy for intermediate resolutions than the renderer, the wrong image providers might be attributed.

https://github.com/openlayers/openlayers/blob/3f7c52c29f0fd667ee3356300cecfc53e88ff48a/src/ol/source/BingMaps.js#L268-L272

Solution could be to add the `layerState` to the `attributionGetter` function parameters and calculate the `tileCoord` taking the tile layers `zDirection` into account.
https://github.com/openlayers/openlayers/blob/3f7c52c29f0fd667ee3356300cecfc53e88ff48a/src/ol/control/Attribution.js#L185-L190

**TileWMS**
`ol/sourc/TileWMS~TileWMS#getGetFeatureInfoUrl` uses `ol/tilegrid/TileGrid~TileGrid#getTileCoordForXYAndResolution` to determine the correct tile coordinates for the feature info request URL - which would be different from the tile coordinates used by the renderer.

https://github.com/openlayers/openlayers/blob/84bf801b5267201c1ca5b33d390c34e8f0db6d3b/src/ol/source/TileWMS.js#L171

Solution could be to add an optional zDirection parameter to `ol/sourc/TileWMS~TileWMS#getGetFeatureInfoUrl` to be able to pass the same value as to the tile layer.

**UTFGrid**
`ol/source/UTFGrid~UTFGrid#forDataAtCoordinateAndResolution` uses `ol/tilegrid/TileGrid~TileGrid#getTileCoordForXYAndResolution` to determine the correct tile from coordinates and resolution whose data is then passed to a callback. Not accounting for the correct `zDirection` would select the wrong tile.

https://github.com/openlayers/openlayers/blob/84bf801b5267201c1ca5b33d390c34e8f0db6d3b/src/ol/source/UTFGrid.js#L385-L389

Optional parameter `zDirection` could be a solution, but `forDataAtCoordinateAndResolution` would then already have five parameters.

### `ol/reproj/Tile~ReprojTile#constuctor`
I'm not familiar with how reprojection works. I just noticed that if the view has an intermediate zoom level, the `sourceZ_` has the same value for different `tileCoord[0]` values that originiate from different different `zDirection` options of the tile layer.

### `ol/loadingstrategy#tile`
Should not be a problem if the `zDirection` option is only available for `ol/layer/Tile~TileLayer` as the loading strategy is only used by `ol/source/Vector~VectorSource` that can't be used with a tile layer.

**Comment by ahocevar** [comment]
Thanks @lutzhelm for this thorough investigation. To play this safe, what if you just expose the `zDirection` option for the `Zoomify` source (not the layer) for now?

**Comment by lutzhelm** [comment]
Exposing `zDirection` for Zoomify will raise the question which option to prefer should anyone ever try to make `zDirection` a tile layer option. But since this didn't happen so far and a non default `zDirection` seems primarily useful for Zoomify and IIP (and hopefully IIIF) sources, this is probably the right way.

**Comment by lutzhelm** [comment]
Solved via #9361.
