### ISSUE TITLE
setResolutionConstrained is missing in 6.0.0-beta.3

### ISSUE THREAD

**Issue by GD-Aichi** [openlayers/openlayers#9349]
I miss the function "setResolutionConstrained" in the class of view.
upgrade-notes.md
"The `constrainResolution` option is now only supported by the `View` class. A `View.setResolutionConstrained` method was added as well."

**Comment by fredj** [comment]
ping @jahow

**Comment by jahow** [comment]
This option was not part of the 6.0.0-beta.3 release, it should be available as of beta4 or the actual release. Thanks

**Comment by ahocevar** [comment]
@jahow Your work is in 6.0.0-beta.3, but there is indeed no `View#setResolutionConstrained` method. Maybe that was meant to be the function that is now available as `View#adjustResolution`? It would be good if you could take another look at that and update the upgrade notes accordingly.

**Comment by jahow** [comment]
Sorry, will fix the upgrade notes
