### ISSUE TITLE
How to add or remove the Layer from map in ol@6.0.0-beta.3

### ISSUE THREAD

**Issue by vampire1995** [openlayers/openlayers#9354]
In ol@5.2.0, I used "removeLayer()" and "addLayer()" to hide or show Layer ,and everyting is ok! </br>But,in ol@6.0.0-beta.3 ,the above two methods dont work any more ,and report an error sometimes:</br>
**Uncaught TypeError: Cannot read property 'dispose' of undefined</br>
    at CompositeMapRenderer.<anonymous> (Map.js:281)
    at Map.PluggableMap.handlePostRender (PluggableMap.js:959)**

```
/**
   * @param {!import("../PluggableMap.js").FrameState} frameState Frame state.
   * @protected
   */
  scheduleRemoveUnusedLayerRenderers(frameState) {
    const layerStatesMap = getLayerStatesMap(frameState.layerStatesArray);
    for (const layerKey in this.layerRenderers_) {
      if (!(layerKey in layerStatesMap)) {
        frameState.postRenderFunctions.push(function() {
         this.removeLayerRendererByKey_(layerKey).dispose(); (Cannot read property 'dispose' of undefined)
        }.bind(this));
      }
    }
  }
}
```
</br>
I konw "layerStates" have been removed  From   [](https://github.com/openlayers/openlayers/pull/9072)  ,is it caused? And what should I do，I am a rookie about ol .........

**Comment by ahocevar** [comment]
ping @fredj

**Comment by fredj** [comment]
@vampire1995 what type of layer are you using ?

**Comment by fredj** [comment]
The layer renderer could be undefined if it has been removed between the time the postRender function is created and executed. See #9355

**Comment by vampire1995** [comment]
> The layer renderer could be undefined if it has been removed between the time the postRender function is created and executed. See #9355
Perfect!  It solved my problem： </br>
```
const layerRenderer = this.removeLayerRendererByKey_(layerKey);
          if (layerRenderer) {
            layerRenderer.dispose();
          }
```
</br>
And will it merge to  ol@6.0.0-beta.3 ?

**Comment by ahocevar** [comment]
@vampire1995 Please provide a test case or a code pen or similar so we can reproduce the issue. The fix in #9355 is only a workaround for something that might be severely broken, and we want to find that out.

**Comment by fredj** [comment]
I've tried to create a test case by adding and removing vector layers (with a mix of managed and unmanaged layer) but I was not able to reproduce the issue.

**Comment by vampire1995** [comment]
> @vampire1995 Please provide a test case or a code pen or similar so we can reproduce the issue. The fix in #9355 is only a workaround for something that might be severely broken, and we want to find that out.

**HTML**:</br>
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title></title>
  <link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">
  <script src="./src/static/jquery-1.8.3.min.js"></script>
</head>
<body>
  <div id="map" class="mapShow" style="height:1155px;width:100%"></div>
  <script src="./src/dropins/Map.js"></script>
</body>
</html>
```
</br>
**Javascript**:</br>

```
import "ol/ol.css";
import Map from "ol/Map.js";
import View from "ol/View.js";
import {
  Tile as TileLayer,
} from "ol/layer.js";
import VectorSource from "ol/source/Vector.js";
import VectorImageLayer from "ol/layer/VectorImage"
import {
  fromLonLat,
} from "ol/proj.js";
import TileJSON from 'ol/source/TileJSON.js';

var map
var view
var shipSource = new VectorSource({
  wrapX: false,
});
var shipLayer = new VectorImageLayer({
  source: shipSource,
});
var zoomchange1 = false 
var zoomchange2 = true

function mapHover() {
  map.on("pointermove", function (evt) {
    var feature = map.forEachFeatureAtPixel(evt.pixel, function (feature) {
      return feature;
    });
  })
}

function mapMove() {
  map.on('moveend', function (evt) {
    if (zoomchange1) {
      map.addLayer(shipLayer)
      zoomchange1 = false
      zoomchange2 = true
    }
  })
}

function moveStart() {
  view.on('change:resolution', function (evt) {
    if (zoomchange2) {
      map.removeLayer(shipLayer)
      zoomchange1 = true
      zoomchange2 = false
    }
  })
}

function init() {
  view = new View({
    center: fromLonLat([120, 30]),
    zoom: 7,
  });
  map = new Map({
    layers: [new TileLayer({
      source: new TileJSON({
        url: 'https://api.tiles.mapbox.com/v3/mapbox.geography-class.json?secure',
        crossOrigin: ''
      })
    })],
    target: "map",
    view: view
  });
  mapHover()
  mapMove()
  moveStart()
}

init()
map.addLayer(shipLayer)
```
You can reproduce the issue by changing zoom quickly with keep moving the mouse at the same time.</br>It will  occasionally appear，and you could do it a few more times.</br>
I think it's probably caused by 'change:resolution'.
@fredj

**Comment by fredj** [comment]
https://codesandbox.io/s/9z91jo8j5y

**Comment by fredj** [comment]
> In ol@5.2.0, I used "removeLayer()" and "addLayer()" to hide or show Layer

By the way, why aren't you using the [`setVisible`](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html#setVisible) function to hide or show the layer?

**Comment by vampire1995** [comment]
> I've tried to create a test case by adding and removing vector layers (with a mix of managed and unmanaged layer) but I was not able to reproduce the issue.

Thank you! This method is very useful to me， I didn't think of this before
