### ISSUE TITLE
Error: Unimplemented abstract method

### ISSUE THREAD

**Issue by ffxsam** [openlayers/openlayers#9356]
**Describe the bug**
This appears to be a breaking change in one of the recent releases, because I've never seen this before and it just cropped up fairly recently. It occurs when removing features from the map.

I don't have a reproduction because I can't actually tell what's setting it off. As far as the stack trace shows me, though, this is the path that leads to the error: (the red circle indicates the particular line in the stack trace; I'm showing files in order from most outward to inward)

As far as I remember, nothing in my code has changed.

### PluggableMap.js
```js
    this.animationDelay_ = function() {
      this.animationDelayKey_ = undefined;
      this.renderFrame_.call(this, Date.now()); 🔴 
    }.bind(this);
```
```js
    this.frameState_ = frameState;
    this.renderer_.renderFrame(frameState); 🔴 
```

### Map.js
```js
      if (layerRenderer.prepareFrame(frameState, layerState)) {
        layerRenderer.composeFrame(frameState, layerState, context); 🔴 
      }
```

### VectorLayer.js
```js
      features.sort(vectorLayerRenderOrder);
      for (var i = 0, ii = features.length; i < ii; ++i) {
        render(features[i]); 🔴 
      }
```
```js
      if (styles) {
        var dirty = this.renderFeature( 🔴 
          feature, resolution, pixelRatio, styles, replayGroup);
        this.dirty_ = this.dirty_ || dirty;
      }
```
```js
        loading = renderFeature( 🔴 
          replayGroup, feature, styles[i],
          getSquaredRenderTolerance(resolution, pixelRatio),
          this.handleStyleImageChange_, this) || loading;
```

### vector.js
```js
    var imageState = imageStyle.getImageState(); 🔴 
    if (imageState == ImageState.LOADED || imageState == ImageState.ERROR) {
      imageStyle.unlistenImageChange(listener, thisArg);
    } else {
      if (imageState == ImageState.IDLE) {
        imageStyle.load();
      }
      imageState = imageStyle.getImageState();
      imageStyle.listenImageChange(listener, thisArg);
      loading = true;
    }
```

### Image.js
```js
/**
 * @abstract
 * @return {import("../ImageState.js").default} Image state.
 */
ImageStyle.prototype.getImageState = function getImageState () {
  return abstract(); 🔴 
};
```

Leading to, finally:
```js
export function abstract() {
  return /** @type {?} */ ((function() {
    throw new Error('Unimplemented abstract method.');
  })());
}
```

**Comment by ahocevar** [comment]
Looks like you are using `ol/style/Image` directly, or a custom subclass of it that does not implement `#getImageState()`. In previous versions, you did not get a warning about this.

**Comment by ffxsam** [comment]
Hopefully I won't really need to use `ol/style/Image`. This is why I'm using it:

```js
    /**
     * Hack to fix an issue in OpenLayers where a polygon with edit styling
     * doesn't disappear from the map when removed.
     */
    feature.setStyle(
      new ol.Style({
        image: new ol.ImageStyle({ opacity: 0 }),
      })
    );
```
(don't worry about the nonstandard names.. `ImageStyle` is `require('ol/style/Image')`.

I had to add this hack, because any shapes that had styles applied do not disappear when removed.

**Comment by ahocevar** [comment]
Hard to guess what's going out without seeing a live example of the code that causes this behavior.

**Comment by ffxsam** [comment]
There's too much code to show, not to mention it's closed-source. Here are the relevant bits though:

I add the `ol.Select` interaction to the map, to allow the selection of shapes. After drawing a shape, I have this:

![image](https://user-images.githubusercontent.com/12532733/54773502-b815d080-4bd7-11e9-9346-205f39ec37c5.png)

Clicking it once changes the style (I think this is automatically built into OL) to show it's selected:

![image](https://user-images.githubusercontent.com/12532733/54773532-c95edd00-4bd7-11e9-8312-3f21af219625.png)

I hit delete which is handled by this code (in a `switch`):

```js
      case 'backspace':
      case 'delete':
        if (this.selectedFeatureIds.length === 0) return;
        this.removePolygonsByFeatureIds(this.selectedFeatureIds);
        break;
```

Which goes through the array of items to remove, calling `removeFeature` on each one:

```js
  removeFeature(feature) {
    const index = this.features.findIndex(
      feat => feat.getId() === feature.getId()
    );

    /**
     * Hack to fix an issue in OpenLayers where a polygon with edit styling
     * doesn't disappear from the map when removed.
     */
    // feature.setStyle(
    //   new ol.Style({
    //     image: new ol.ImageStyle({ opacity: 0 }),
    //   })
    // );
    this.vectorSource.removeFeature(feature);
    this.features.splice(index, 1);
  },
```

`this.features` is my own internal record of drawn features, it's not really relevant here. The issue is that once the special select styling (second image above) is applied, `vectorSource.removeFeature()` doesn't visually remove the polygon.

I don't know if this is enough code to be helpful. If you need to see something in particular, let me know.

**Comment by ffxsam** [comment]
For now, I uncommented my opacity hack, and added this code to stop the errors:

```js
ol.ImageStyle.prototype.getImageState = ol.ImageStyle.prototype.listenImageChange = () => {};
```

**Comment by ahocevar** [comment]
This is probably an issue with `ol/interaction/Select`, which is broken anyway in my opinion. If you find some time to isolate the problem with a minimal example, it would be great if you could create a new issue. I'm closing this one because we have deviated from it's topic too far already.
