### ISSUE TITLE
Support on the road to OL6

### ISSUE THREAD

**Issue by KaiVolland** [openlayers/openlayers#9358]
As far as we understand OL6 is around the corner.

What steps are needed to get to it eventually? And where can we help?

Some ideas:
- Reintroduce editable examples (live, via CodePen, via Fiddle, …)
- Link between used classes in examples and their API docs
- [ ] Better Usability in API Docs
  - More valuable searchresults (Ordering, eg. search for `view`)
  - Filter/Hide module-pages (checkbox?):
![image](https://user-images.githubusercontent.com/1849416/54741605-46318d00-4bbf-11e9-87c2-00ad54d6719c.png)
- Update workshop to work with OL6
- [ ] Update FAQs
- [ ] Named exports per directory
```js
import {Map, View} from 'ol';
import {OSM, VectorTile} from 'ol/source';
```

These are just some ideas of @marcjansen and me.

Any thoughts? Otherwise we'll try to work on some of the above.

**Comment by KaiVolland** [comment]
Indeed i expected the button to be right beside the copy button.

**Comment by ahocevar** [comment]
> Named exports per directory

We also want to re-export everything from `ol` and each directory, so people who do not care about tree-shaking could do
```js
import ol from 'ol';
const layer = new ol.layer.Tile();
```
or
```js
import control from 'ol/control'; 
const OverviewMap = new control.OverviewMap();
```
Also the naming of default exports could be improved (i.e. append the name of the containing directory') so IntelliSense finds them more easily, e.g.
```js
class OSMSource extends XYZ {}; // instead of `class OSM extends XYZ`
export default OSMSource
```
I think for the API docs it's fine to continue showing just one way to import. What's missing though is to show an import for named exports, which we use for utility functions (e.g. `ol/proj.get`).

**Comment by ahocevar** [comment]
> Indeed i expected the button to be right beside the copy button.

Then you would have to repeat it multiple times, because the new examples show html and css separately:

![Untitled](https://user-images.githubusercontent.com/211514/54745243-53ec1000-4bc9-11e9-8453-6e92ecce012f.png)

**Comment by ahocevar** [comment]
> * Better Usability in API Docs

Any improvements here are welcome. Note that we are planning for a dedicated website code sprint which might also include creating completely new API docs, so please do not spend too much time on it.

> Link between used classes in examples and their API docs

It would consider that low priority. It's probably better to make IntelliSense work better in codesandbox, to get help while editing the examples.

**Comment by ahocevar** [comment]
> * Update workshop to work with OL6

@tschaub and I will be reworking the workshop a bit next week.

**Comment by ahocevar** [comment]
Thanks @KaiVolland for the suggestions and any work you can take on regarding those.

I have converted the bullet points that would be nice to get addressed into todos, so we can track progress on this ticket.

**Comment by KaiVolland** [comment]
I'll try to work on the exports. I created a separate issue to be feature related #9376.

**Comment by tschaub** [comment]
Only on a small device, so can’t give a full response, but let’s have more discussion about the exports.  It is already possible to ‘import * as controls from “ol/controls”’.  I don’t think there is a reason to add a default export that readings all the named exports to object properties.

**Comment by KaiVolland** [comment]
> It is already possible to ‘import * as controls from “ol/controls”’. I don’t think there is a reason to add a default export that reassigns all the named exports to object properties.
Agreed.

**Comment by KaiVolland** [comment]
As i think im done with the migration of the rendering tests and the changes to the imports are canceled/frozen, I'm open for new input. Anything specific i can help with?

**Comment by marcjansen** [comment]
Have you checked the official workshop? I know this will probably also be reworked, but a quick check might be useful.

**Comment by ahocevar** [comment]
@tschaub and I will be changing the workshop for the upcoming FOSS4G-NA conference.

@KaiVolland, what about the api doc improvements you were planning to work on, e.g. displaying import snippets also for static functions?

**Comment by KaiVolland** [comment]
>@KaiVolland, what about the api doc improvements you were planning to work on, e.g. displaying import snippets also for static functions?

I skipped this due to your comment:

>Any improvements here are welcome. Note that we are planning for a dedicated website code sprint which might also include creating completely new API docs, so please do not spend too much time on it.

**Comment by ahocevar** [comment]
@KaiVolland i think at least showing import snippets for static functions would be a worthwhile improvement. Or does that sound like you would have to spend a lot of time to achieve it?

**Comment by KaiVolland** [comment]
I tried something: https://github.com/openlayers/openlayers/pull/9394

**Comment by ahocevar** [comment]
@KaiVolland #8846 is the last issue open marked with the v6.0.0 milestone, and I think it is something you could look into.
