### ISSUE TITLE
Remove events listener on features collection register by ol.interactionModify

### ISSUE THREAD

**Issue by volterra79** [openlayers/openlayers#9363]
Hi, i discoverd that when remove ol.interactionModify interaction from map, the interaction doesn't remove the following events on collection features.

**ol.events.listen(this.features_, ol.CollectionEventType.ADD,      this.handleFeatureAdd_, this);
ol.events.listen(this.features_, ol.CollectionEventType.REMOVE,    this.handleFeatureRemove_, this);**
 
The issue is visible when the modify interaction is removed from  map and i create a new one using the same collection features, above events are registered twice. I would like to remove these events when interaction is removed from map.
Thanks

**Comment by ahocevar** [comment]
`ol/interaction/Modify` with a collection is broken in my opinion. Same with `ol/interaction/Draw` and others that can be configured with a `features` collection. Try to configure the interaction with a `source` instead of `features`.
