### ISSUE TITLE
Unexpected animation with constrained zoom

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#9366]
**Describe the bug**
When starting to interact with a map that has a view with a `minZoom` that's higher than the initial `zoom` on the map, an unexpected zoom-out occurs.

**To Reproduce**
1. Go to https://codesandbox.io/s/98kw3q2vro
2. Pan the map
3. See the map zoom out

The minimal view configuration to reproduce this is:
```js
new View({
  center: [0, 0],
  zoom: 2,
  minZoom: 3
})
```

**Expected behavior**
Panning the map with the above setup does not lead to an unexpected zoom-out.

**Comment by ahocevar** [comment]
@jahow, can you please take a look at this?

**Comment by jahow** [comment]
Will do ASAP, thanks for the repro

**Comment by ahocevar** [comment]
This not only happens with the initial view configuration. It also happens every time the application sets e.g.
```js
map.getView().setZoom(2);
```
