### ISSUE TITLE
Critical (and mindblowing) performance bug with empty-source layers

### ISSUE THREAD

**Issue by aalbericio** [openlayers/openlayers#9367]
**Describe the bug**

Windows: 10 
Ram: 16Gb
CPU: i7
Browser: Chrome 73

**When we have layers using an empty source (no features!), performance and FPS drop in an unexpected and dramatic way.**

We're measuring both **ZOOM** and **PAN** actions,

Surprisingly, if we just add 1 simple (painted!) feature to every layer, PAN performance works as expected hitting 60fps.

Using that very same 1 feature on every layer, ZOOM interaction improves but not with the scale that PAN does.

**To Reproduce**
1. Go to https://codesandbox.io/s/7m0434on76
2. Pan (works fine)
3. Zoom works but it's kinda clunky (with very few features, 1/layer)
4. Now remove the 'olFeature' from the source array inside the loop and....boom!
5. Pan works incredibly slow with a huge drain on FPS (with 0 features painted/registered)
6. Zoom works even worse than before

**Expected behavior**
Regardless the number of layers, an empty source should not affect or impact performance since it's not really painting anything.

Indeed, it's always expected to get worse performance when more features are painted.

We reviewed the call tree and the method **IntermediateCanvas.drawImage** was consuming (scripting) our resources.

This is a (very) critical bug.

**Comment by aalbericio** [comment]
Extended information:

Using ol@6.0.0-beta.3, same project with 0 features/layer works fine but adding 1/layer hits the bug of unexpected performance drain again.

So, I understand there's some work being done in some direction but still a weird bug on the table.

Thanks.

**Comment by ahocevar** [comment]
A map with 100 layers is not a good idea. v6 shortcuts rendering when there are no features on a layer's source, but as soon as there are features, a canvas for the whole map viewport is created.

It would be interesting to hear about your use case and why you need 100 layers.

**Comment by aalbericio** [comment]
I have exagerated the issue in the example but we're experiencing this issue with 12 active layers, 26 lineString features distributed in 3 of those 12 layers and the rest, 9 layers, empty. As you can imagine, that is (or should be) a quite lightweight scenario for OpenLayers to handle. 

Please also read that, in your 6. 0.0b3 version, things appear to be changing but not fixing the issue by any means. 

We have also spent quite a few hours trying to determine where the issue was and isolating/sampling the issue for you. 

Last but not least, we're releasing a quite big product soon and would love this issue to be addressed (asap) since we do love OpenLayers but we also take a lot of care about performance and helping you, guys. 

Please, let us know if we can help you in any way. 

IMHO, this is a very big issue.

**Comment by ahocevar** [comment]
@aalbericio The `drawImage` call you noticed with v5 is gone with v6, but still a canvas for each layer is created. As a rule of thumb, you should not have more than 3 active layers on a map.

Since you are pointing out how critical OpenLayers is for your big product, and also mention how urgent this matter is to you, you might want consider getting professional support, which could in turn help improve both your application and OpenLayers. If you are interested, feel free to reach out to me by e-mail.

**Comment by ahocevar** [comment]
The issue with empty vector layers taking a lot of render time is fixed in v6.

**Comment by aalbericio** [comment]
@ahocevar 3 active layers is definetely a very limited number for our app (and I can bet for many others).

Anyway, I can ask my company how we can work on this issue (and in the future) with you. We will be happy to collaborate in present and future features but that is something I have to scale up and may take some time to unlock. 

Wether this collaboration takes shape or not, I still feel this is a big issue for the product and probably time to refactor some internals. 

I will reach you by email next week. 

Thanks for your time and effort on this great lib.

**Comment by aalbericio** [comment]
Glad to see this bug reopened.

Anyway, if it can help, I managed to workaround this by defining a "emptySource$" Observable and then:

emptySource$.subscribe((empty: boolean) => layer.setVisible(!empty));

This single subscription improves performance (a lot).
