### ISSUE TITLE
Heatmap problem in renderMode: 'image' 

### ISSUE THREAD

**Issue by ChenGuanglin0924** [openlayers/openlayers#9369]
In the past (Version 4.6.4), in ol.layer.Heatmap, when I set 'renderMode' to be 'image', the gradient of the point becomes 'black' and the gradient I set before disappeared. And setting 'renderMode' to be 'vector' display normally.
```
let layerOptions = {
    ...
    renderMode: 'image',
    gradient: ['#00c3ff', '#ffff1c', '#e9e9e9']
};
return new ol.layer.Heatmap(layerOptions);
```
![heatmap](https://user-images.githubusercontent.com/22443356/54862738-ec28f700-4d79-11e9-84ce-f69c14c11960.png)

**Comment by fredj** [comment]
The `renderMode` property is now ignored by the Heatmap layer.
