### ISSUE TITLE
Chrome crashes with error message "Render process gone"

### ISSUE THREAD

**Issue by HarelM** [openlayers/openlayers#9370]
**Describe the bug**
When using a heavy vector layer and zooming in and out sometime chrome crashes with the following error message:
![image](https://user-images.githubusercontent.com/3269297/54886005-862c9480-4e8b-11e9-9c1d-822c5737cad2.png)

**To Reproduce**
I was able to reproduce it here, but lately it's harder to do it, probably related to some timing issue:
https://stackblitz.com/edit/angular-openlayers-mapbox
Not entirely sure - zoom in and out while panning until this happens.

**Expected behavior**
The code should not make chrome crash.
I'm not sure I should open this here, I'm mainly wondering if someone else using this library has experienced this issue and have any insights...

**Comment by ShanonJackson** [comment]
Also having this problem on our React/Storybook library. Randomly happens after "N" Time - No code errors, was previously working perfectly on chrome 74

**Comment by anariba-hn** [comment]
Having this on Angular JS after an implementation of a library wish use `requestAnimationFrame(callback)` can´t resolve yet.

**Comment by tayyebi** [comment]
Having performance issue with this log:

```
[Violation] 'requestAnimationFrame' handler took <N>ms
[Violation] Forced reflow while executing JavaScript took <N>ms
```

Works fine on FF or IE, but really slow on chrome.
