### ISSUE TITLE
GPU memory leaks, openlayers4.6.5

### ISSUE THREAD

**Issue by cdhuangyong** [openlayers/openlayers#9371]
In the chrome environment, when the layer is changed from vector rendering mode to image rendering, when the hardware acceleration is turned on, the GPU memory leaks, what is going on?

**Comment by ahocevar** [comment]
Please either use a newer version of OpenLayers (in v6, we have a VectorImage layer), or create two layers with the same source, one with vector render mode, and one with image render mode.
