### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by MPParsley** [openlayers/openlayers#9373]
Could we get a roadmap and a list of supported versions?

I got this from the homepage but v5 & v6 are missing and the EOL date for each of the versions would be useful:
> * Latest v4: v4.6.5 released 2017-03-20 — docs, API & examples
> * Latest v3: v3.20.1, released 2016-12-12 — docs, API & examples
> * Latest v2: v2.13.1 (July 2013 i.e. really old) — you'll find everything you need on the 2.x page
> * Latest v1 — You're kidding, right?
> 
> Please consider upgrading to benefit of the latest features and bug fixes. Get best performance and usability for free by using recent versions of OpenLayers

**Comment by ahocevar** [comment]
Simple answer: The OpenLayers project always only supports the latest version. So we recommend to stay up to date with the latest.

If you need support for older versions, you should to get in touch with a company that provides support for OpenLayers. Some of them are listed on https://www.osgeo.org/service-providers/.
