### ISSUE TITLE
Enhancements to module exports

### ISSUE THREAD

**Issue by KaiVolland** [openlayers/openlayers#9376]
**Enhance exports**
Currently modules/classes can only be imported from the single file they are exported from.

Users may benefit from importing the whole library:
```js
import ol from 'ol';
const layer = new ol.layer.Tile();
```
... or a single namespace:
```js
import control from 'ol/control'; 
const OverviewMap = new control.OverviewMap();
```

>Also the naming of default exports could be improved (i.e. append the name of the containing directory') so IntelliSense finds them more easily, e.g.
```js
class OSMSource extends XYZ {}; // instead of `class OSM extends XYZ`
export default OSMSource
```

See suggestion of @ahocevar for reference: https://github.com/openlayers/openlayers/issues/9358#issuecomment-475170787

**Comment by ahocevar** [comment]
From https://github.com/openlayers/openlayers/issues/9358#issuecomment-476391827:

**Comment by KaiVolland** [comment]
Ok and as `import control from 'ol/control'; ` could be written as `import * as control from 'ol/control'` the exports are fine as is?

Renaming the classes is the remaining TODO here right?

**Comment by ahocevar** [comment]
> the exports are fine as is?

A quick sanity check could not hurt, to make sure that all exports that are marked `@api` are re-exported.

> Renaming the classes is the remaining TODO here right?

Right.

**Comment by KaiVolland** [comment]
@ahocevar should the classname be changed too? Or only the default export?


```js
// export
class BingMapsSource extends TileImage
[...]
export default BingMapsSource;

// import
import {BingMapsSource} from '../src/ol/source.js';
import BingMapsSource from '../src/ol/source/BingMaps.js';
```
vs
```js
// export
[...]
const BingMapsSource = BingMaps;
export default BingMapsSource;

// import
import {BingMaps} from '../src/ol/source.js';
import BingMapsSource from '../src/ol/source/BingMaps.js';
```

Renaming the default export name is just relevant for intellisense, while renaming the whole class will have a big impact on existing code.

**Comment by ahocevar** [comment]
Only the default export. But the change is simpler than what you have above:
```diff
diff --git a/src/ol/source/BingMaps.js b/src/ol/source/BingMaps.js
index 3d4ea68ab..24abe7a74 100644
--- a/src/ol/source/BingMaps.js
+++ b/src/ol/source/BingMaps.js
@@ -117,7 +117,7 @@ const TOS_ATTRIBUTION = '<a class="ol-attribution-bing-tos" ' +
  * Layer source for Bing Maps tile data.
  * @api
  */
-class BingMaps extends TileImage {
+class BingMapsSource extends TileImage {
   /**
    * @param {Options} options Bing Maps options.
    */
@@ -300,4 +300,4 @@ class BingMaps extends TileImage {
   }
 }
 
-export default BingMaps;
+export default BingMapsSource;
```

**Comment by KaiVolland** [comment]
Ah ok. Got it. I just have to keep `/src/ol/source.js` as it is.
