### ISSUE TITLE
Support offsetting/translating features through Style

### ISSUE THREAD

**Issue by jahow** [openlayers/openlayers#9377]
Currently, only a few style classes implement an offset option:
* `ol/style/Icon`: controls the part of the source image to render
* `ol/style/Text`: offsets the text in pixel space on X and Y axis

The general use case of offsetting a shape in pixel space is currently covered by providing a `geometry` function on the style which will compute a new geometry in world space by applying a delta to the coordinates. This is quite straightforward although not very intuitive.

Let's call this first use case "translating" instead of "offsetting".

A bit more complex use case is implementing a logic similar to the `line-offset` option of the [mapbox style spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-offset), or  [turfjs](https://www.npmjs.com/package/@turf/line-offset).

Example with mapbox: https://bl.ocks.org/danswick/3bae5a8443db94b78008e5ddba192015

Both use cases could be implemented in the rendering code of OpenLayers, e.g. with the following API:
```js
const style = new Style({
  fill: 'white',
  stroke: 'black',
  offsetX: 2,  // in pixels
  offsetY: 2,
  translateX: 0, // still in pixels
  translateY: 4
});
```

Related issues I found:
https://github.com/openlayers/openlayers/issues/5057
https://github.com/openlayers/openlayers/issues/6597
https://github.com/openlayers/openlayers/issues/7573 -> having a `translate` option would allow shadows (although not as nice as with `shadowColor` and `shadowColor` canvas properties)

**Comment by ahocevar** [comment]
Anchors and offsets of icons and text are a different thing, but I agree that the property names we use there are confusing. What we're trying to do here is translate and offset geometries. I think the `offset` we are talking about here is about offsetting a line from its geometry, as in mapbox-gl with the [`line-offset`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-offset) property. So this will be no x- and y-offset, just a single value. `translateX` and `translateY` work, but I wonder if it would not be nicer to use a single array like `translate: [translateX, translateY]`. Like in mapbox-gl's [`line-translate`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-translate).

`translate` would then be available for all geometries, `offset` only for (multi)linestrings and (multi)polygons.

**Comment by jahow** [comment]
> So this will be no x- and y-offset, just a single value.

Yes, good point.

> `translateX` and `translateY` work, but I wonder if it would not be nicer to use a single array like `translate: [translateX, translateY]`. Like in mapbox-gl's [`line-translate`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-translate).

Definitely. I was trying to stay close to the existing options on the Text style, but an array is nicer. Also the text options might be renamed to stay consistent.

> `translate` would then be available for all geometries, `offset` only for (multi)linestrings and (multi)polygons.

Agreed. All these options would go on the base Style object, right?

**Comment by ahocevar** [comment]
> All these options would go on the base Style object, right?

Right.

**Comment by ahocevar** [comment]
> Also the text options might be renamed to stay consistent.

I think we'll need an API review anyway, but should maybe save that for after v6.

**Comment by jahow** [comment]
Ruthless bot! Let's just keep this topic in mind if we rework the styling API at some point.

**Comment by ahocevar** [comment]
Yes! `Icon`, `Circle` and `RegularShape` styles now have a `displacement` option, where you can pass an array with `[xOffset, yOffset]`.
