### ISSUE TITLE
Click event on specific layer issue in OpenLayers 5

### ISSUE THREAD

**Issue by csandreas1** [openlayers/openlayers#9384]
I am trying to add click event on specific layer. Parcels and buildings. [Here ](https://gis.stackexchange.com/questions/316800/openlayers-5-click-event-on-specific-layer)is my question on stackexhange.

I get this error: Uncaught DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.

The point of what i am trying to achieve is to detect which layer is clicked to request data via ajax from different php file. Then im doing query according to the degrees i get when clicking on the map.

```
var wmsLayer = new ol.layer.Image({
  source: wmsSource
});
var map = new ol.Map({
  target: 'map',
  layers: [baseLayer, wmsLayer],
  view: new ol.View({
    center: ol.proj.fromLonLat([33.33386, 35.14710]),
    zoom: 14
  })
});

map.on('click', function (evt) {
  map.forEachLayerAtPixel(evt.pixel, function (layer) {
    if (layer==='web:Parcels') {
      console.log('parcels clicked');
    }
  });
});
```

![image](https://user-images.githubusercontent.com/21238024/55146588-8cea2e80-514d-11e9-9d7b-54172f79d61c.png)

**Comment by ahocevar** [comment]
You need a WMS server that supports CORS headers, and configure the WMS source accordingly:
```js
new ImageWMSSource({
  crossOrigin: 'anonymous'
});

**Comment by csandreas1** [comment]
I am receiving data from a Geoserver.
