### ISSUE TITLE
StyleFunction should return Style or Promise<Style>

### ISSUE THREAD

**Issue by jepetko** [openlayers/openlayers#9386]
It seems to be impossible to style a vector layer in asynchronous way. The current signature of the `StyleFunction` looks like this:

```js
(feature: Feature, resolution: number) => (Style | Style[] | null)
```

The implementation is as follows (OL version 5.3.0):

```js
    var render = function(feature) {
      var styles;
      var styleFunction = feature.getStyleFunction() || vectorLayer.getStyleFunction();
      if (styleFunction) {
        styles = styleFunction(feature, resolution);
      }
      if (styles) {
        var dirty = this.renderFeature(
          feature, resolution, pixelRatio, styles, replayGroup);
        this.dirty_ = this.dirty_ || dirty;
      }
    }.bind(this);
```

The styles are returned and applied immediately by the succeeding code (see `renderFeature`).

**SOLUTION:**

A promise of the style(s) can be returned.

New signature:

```js
(feature: Feature, resolution: number) => (Style | Style[] | Promise<Style> | Promise<Style[]> | null)
```

Usage:

```js
const styleFn = (feature, resolution) => {
 return Promise.resolve(new Style({
      stroke: new Stroke({
        color: 'rgb(255, 105, 180)',
        width: 1
      })
    }));
};

layer.setStyle(styleFn);
```

This feature will facilitate the involvement of promises, observables, workers and any kind of asynchronous stuff, respectively.

Note that the implementation of the style function like this does not solve the issue either because this would return a "constant" style for each feature (independent from the zoom level):

```js
// computeStyle returnes a Promise<Style> for the passed feature
computeStyle(feature).then((style) => {
	feature.setStyle(style);
});
```

This means that the promisifying the styles is the only option to get both advantages: asynchronous calculation of the style + re-calculation of the style on zoom level etc.

**Comment by ahocevar** [comment]
Not sure what you're trying to achieve. The style function is called for each feature when render instructions are created. For vector layers, this happens asynchronously in a `requestAnimationFrame()` cycle. For vector tile layers, it happens asynchronously when a tile has loaded, or in a `requestAnimationFrame()` cycle when the resolution has changed.

**Comment by jepetko** [comment]
Consider this high-sophisticated example: you want to draw a symbol into a canvas. This symbol depends on the resolution of the map. If there are many features, the user experience becomes very bad. One solution is, of course, usage of the cache, as shown in https://openlayers.org/en/latest/examples/earthquake-custom-symbol.html. In this example, the symbol (=canvas) is created once and then returned from the cache. In some situations, there is a need to recalculate the symbol. However, the recalculation itself (width, height, the radius of a circle, any detection what to draw into the canvas) would be still executed inside the main thread during the rendering. I would like to create a worker instance which would next an [Observable](https://rxjs-dev.firebaseapp.com/api/index/class/Observable) (kindof promise but more powerful) after every and each calculation. As soon as the recalculation is done (thus, "nexted"), the originally returned `Promise<Symbol>` gets resolved and (re-)rendered in the map (because `StyleFunction` is being used and the OL Renderer would wait for the promise to be resolved). 

I know that the DOM operations cannot be executed in workers; the idea is to split the symbol creation process into calculation and DOM manipulation. When we talk about asynchronous code, the DOM manipulation could still take place in the main thread but at some point in the future; any kind of asynchronous code (incl. HTTP requests, for instance) could be placed in the `StyleFunction` implementation.

I don't know the intrinsic implementation of the rendering mechanism itself but I think that the asynchronous creation of symbols could also improve the user experience. However, currently, the `setStyle` method does not support Promises at all, thus my feature request.

**Comment by Chris1234567899** [comment]
I agree with @jepetko . It has its use.
I try to render charts using chartjs into the map for example, but using the chart canvas directly in the style is very error prone (even tough here chartjs is the culprit). 
Making the style function async however, would allow me to convert the chart into an image first for example.

**Comment by mktcode** [comment]
We save some layer style settings in a database and they are fetched with a separate request. I don't want to delay the rendering of the map on one hand and on the other hand I don't want this request to be *somewhere* after map initialization but right where I configure my layers/styles.

```
return new VectorLayer({
  style: () => {
    return new Promise((resolve, reject) => {
      http.get("...").then(style => resolve(style));
    });
  },
  ...
});
```

That would be nice!

**Comment by bvx89** [comment]
Is it possible to make this issue un-stale again? My problem is that I have quite a computationally expensive style function, and I would like to be able to put it in a web worker in order to increase the performance of my application. Without any form of async style function, this is not possible, and the map performance is suffering as of now.

**Comment by jahow** [comment]
You should be able to have a synchronous style function which returns nothing unless the webworker has finished its task and sent back the value to the main thread (this also means that a new rendering of the layer should be requested when that happens).

**Comment by bvx89** [comment]
I assume that will result in a lot of management code on the users end in order to properly discard old results for each user interaction. Considering that inside a style function you have no way of knowing if the callback comes from the previous map move or the current move. 

For instance, how do we know when to apply the manual map render? One option is to call map render for each return from the async callback, but I think this would be detrimental to the performance (50 features === 50 map renders). Another option is to only call map render ones the map interactions has stopped, but then we are back to the first problem of managing/monitoring what state the map is in.

I think that perhaps the preferred way to do this is by having a new "batch-async" style function, that gives an array of all features to be rendered for the given frame State. I'm not that knowledgeable about the inner workings of Open Layers, but do you think something like that would be feasible? Also, having a cancellable token would be neat to know when to discard results from a async source.

**Comment by jahow** [comment]
I definitely get your point, being able to provide an async style function would be helpful in many cases and reduce the complexity of application code. This would probably be quite the undertaking to implement unfortunately.

**Comment by Toterbiber** [comment]
Is ther any workaround for that problem? I tryed to call feature.setStyle() inside the callback of my asnyc function. That results in a rerendering of the layer for each feature, but aside from that it works.

**Comment by johnnylc** [comment]
Any progress on this? I'm facing the same issue, and ended to call feature.setStyle() after the promise resolved.

**Comment by 9oelM** [comment]
I guess we can use offscreencanvas for now... I've been facing this issue as well because i'm drawing lots of styles from a dxf file, but it won't just be smooth. in ol^6.3.1, IIRC, we got offscreencanvas support. I think that's one alternative.
