### ISSUE TITLE
Full Screen Control labelActive Property default value not valid

### ISSUE THREAD

**Issue by yaozhongnan** [openlayers/openlayers#9393]
**Describe the bug**
In my project it not work, the example I saw on your website doesn't work either.
[your website site example](https://openlayers.org/en/latest/examples/full-screen.html)

still show ⤢ in full screen mode, not x 

![this](https://user-images.githubusercontent.com/42015945/55459342-eb1d8280-5621-11e9-8ddf-184fdd433a08.png)

I try 5.3.0 and 5.3.1 don't work

**Comment by fredj** [comment]
It works on Firefox but not on Chrome

**Comment by fredj** [comment]
This but is fixed in master with #9079 
See https://openlayers.org/en/master/examples/full-screen.html

**Comment by yaozhongnan** [comment]
@fredj I see https://openlayers.org/en/master/examples/full-screen.html, it works on my Chrome
I don't know the difference
And what can I do to make it work on my project like that example ?
very grateful

**Comment by fredj** [comment]
This fix will be included in the next release (version 6.0.0)

**Comment by yaozhongnan** [comment]
Ok, thanks a lot
