### ISSUE TITLE
Inconsistency between selection behaviour for polygons and circles without fill.

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9395]
As a result of https://github.com/openlayers/openlayers/pull/7750 if, for example, a large box is drawn over a small one the small box can be selected if fill is not defined, but if a large circle is drawn over a small one the small circle cannot be selected even if the CircleStyle has no fill.  Should the polygon fill hit detection logic also be applied CircleStyle for consistency?

**Comment by tschaub** [comment]
Yes.

**Comment by tschaub** [comment]
Bump

**Comment by tschaub** [comment]
@mike-000 - can you provide a simple example that demonstrates this problem?  If so, it would probably be straightforward for someone to debug and fix.  If not, this issue will eventually be closed by the stale bot.

**Comment by mike-000** [comment]
https://codesandbox.io/s/polygonstyles-p3pyb
From top to bottom in the codesandbox:
1. polygons
2. circle geometries using same style as the polygon
3. point geometries styled with circle style using same fill as the above.

Left column: overlapping geometries are styled with no fill
Right column: overlapping geometries are styled with transparent fill

Test clicking on areas A,B,C and on stroke in positions D and E
![image](https://user-images.githubusercontent.com/49240900/59069702-e8ecd400-88af-11e9-9d62-6a5578ede547.png)


Polygons with no fill
A, B, C no effect
D and E The polygon with that stroke is selected

Polygons with transparent fill
A lower left polygon is selected
B,C,D,E top right polygon is selected

Circles with no fill and with transparent fill,, and points using circle style with no fill
A lower left circle is selected
B,C,D,E top right circle is selected

Points using circle style with transparent fill
A, B, C no effect
D and E The circle with that stroke is selected


For all three geometry types I would have expected no fill and transparent fill to behave the same way as they do for polygons

**Comment by SimonA84** [comment]
I believe, that the behaviour from openlayers 4.6.5 where polygons without fillstyle are also detected is not bad too.

**Comment by mike-000** [comment]
Fixing a year old inconsistency probably isn't a priority over getting a major release out but I'll keep it alive until someone has time to look at it.

**Comment by mike-000** [comment]
The solution for Circle geometry is simple, as one line appears to have been left the wrong side of an `if` statement in #7750 https://codesandbox.io/s/polygon-styles-wtorl 

#7750 was never applied to CircleStyle so some reworking of ol/style/RegularShape will be needed to apply the same logic and should be a separate PR
