### ISSUE TITLE
Unexpected animation when starting to interact with the map

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#9396]
**Describe the bug**
This issue is similar to #9366. When starting to interact with a map that has a view whose zoom and center were set with `View#setZoom()` and `View#setCenter()` or `View#animate()` and are outside the restricted range, an unexpected zoom-out occurs.

**To Reproduce**
1. Go to https://codesandbox.io/s/3n2o1n5qm (uses `View#setZoom()` and `View#setCenter()` or https://codesandbox.io/s/o51l6l6qrz (uses `View#animate()`)
2. Pan the map
3. See the map zoom out

The minimal map configuration to reproduce this is:
```js
const map = new Map({
  layers: [new TileLayer({ source: new OSM() })],
  target: 'map'
});
const view = map.getView();
view.animate({
  center: [0, 0],
  zoom: 0
});
// or, instead of view.animate:
//view.setCenter([0, 0]),
//view.setZoom(0);
```

The same happens when the map is initially already configured with a view with `zoom` and `center`.

**Expected behavior**
Panning the map with the above setup does not lead to an unexpected zoom-out.

**Comment by ahocevar** [comment]
@jahow Would be great if you could take a look at this, because you already fixed #9366 which appears to be a similar issue.

**Comment by ahocevar** [comment]
#9399 should fix this.

**Comment by jahow** [comment]
Hi @ahocevar, 

Your PR does fix the issue but breaks the smooth center & resolution constraints (see https://164-4974939-gh.circle-artifacts.com/0/examples/extent-constrained.html).

The problem is that `0` is not a valid zoom level in this scenario, since the min resolution is constrained by the canvas size. I'll try to push an alternative fix today.

**Comment by ahocevar** [comment]
Ok, thanks @jahow.
