### ISSUE TITLE
Error catching for raster reprojections

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9401]
I have resorted to creating custom transforms with error catching between some projections and EPSG:3857/4326 using an intermediate projection such as EPSG:4269 (conveniently predefined in proj4.js) as nulls returned by proj4 are not being caught by OpenLayers own transforms.  While this often happens when a projection is used outside its normal extent, errors can occur within normal extents (e.g. the **Reprojection with EPSG.io Search** example when searching for 3031).  For a workaround example see https://stackoverflow.com/questions/54978836/openlayers-map-doesnt-render-with-a-non-standard-epsg-code/54985365#54985365 where two of the snippets wouldn't work without calling `reprojectionErrorHandler(['EPSG:3031', 'EPSG:3857']) ` The workaround is obviously inefficient and it looks like OpenLayers own direct transforms could easily do similar error catching - there might be some missing tiles and ragged edges, but that's acceptable compared with a crashed map.

**Comment by ahocevar** [comment]
This is a shortcoming of proj4. You can try mproj instead.

**Comment by mike-000** [comment]
I appreciate it's a proj4 problem but (since those transforms out of your control) there should be some attempt to catch bad transforms at problem points so the code can carry on displaying the rest of the map.  It would also stop your examples crashing.  Based on a previous workaround I used with the debug version of OL4 (redefining ol.proj.createTransformFromCoordinateTransform) I think this update would achieve the same in the latest version (the mproj idea of returning Infinity for unprojectable points seems to work and is more logical than simply skipping them).  Also could there be an OpenLayers example of mproj integration when time permits?



```
/**
 * Creates a {@link module:ol/proj~TransformFunction} from a simple 2D coordinate transform
 * function.
 * @param {function(import("./coordinate.js").Coordinate): import("./coordinate.js").Coordinate} coordTransform Coordinate
 *     transform.
 * @return {TransformFunction} Transform function.
 */
export function createTransformFromCoordinateTransform(coordTransform) {
  return (
    /**
     * @param {Array<number>} input Input.
     * @param {Array<number>=} opt_output Output.
     * @param {number=} opt_dimension Dimension.
     * @return {Array<number>} Output.
     */
    function(input, opt_output, opt_dimension) {
      const length = input.length;
      const dimension = opt_dimension !== undefined ? opt_dimension : 2;
      const output = opt_output !== undefined ? opt_output : new Array(length);
      for (let i = 0; i < length; i += dimension) {
        try {
          const point = coordTransform([input[i], input[i + 1]]);
        } catch (e) {
          const point = [Infinity, Infinity];
        }
        output[i] = point[0];
        output[i + 1] = point[1];
        for (let j = dimension - 1; j >= 2; --j) {
          output[i + j] = input[i + j];
        }
      }
      return output;
    });
}
```

**Comment by ahocevar** [comment]
For performance reasons, OpenLayers relies on what it gets as input, and we are not planning to change that.

For an mproj example, see https://github.com/openlayers/f4gna18-frenzy/blob/master/src/reprojection.js. A pull request that adds a similar example to the OpenLayers examples collection would be welcome.
