### ISSUE TITLE
How to listen to a Map rotation?

### ISSUE THREAD

**Issue by aalbericio** [openlayers/openlayers#9402]
Hello,

Is there any way to react/subscribe to a Map rotation (once the rotation has been applied)?

Something like an '**change:rotation**' would work.

Thanks.

**Comment by fredj** [comment]
Hi @aalbericio, you can listen to rotation changes by listening to the view: `view.on('change:rotation')`.
See this example: https://codesandbox.io/s/m75wj0zzwy

**Comment by aalbericio** [comment]
That should work, thanks!

I think I can use that change:rotation event merged with mouse up to get what I really need.
