### ISSUE TITLE
Keyboard zoom interaction custom zoom keys

### ISSUE THREAD

**Issue by joshferrell** [openlayers/openlayers#9413]
**Is your feature request related to a problem? Please describe.**
It's difficult to create custom keys for zooming other than <kbd>+</kbd> and <kbd>-</kbd>. This can be frustrating as you have to <kbd>shift</kbd> and press <kbd>+</kbd> in order to zoom and <kbd>-</kbd> is just a keyboard press. 

When zooming in chrome for example, you can simply press <kbd>ctrl</kbd>+<kbd>=</kbd> and <kbd>ctrl</kbd>+<kbd>-</kbd>. Another example is sometimes arrow key zoom is asked for where <kbd>&uarr;</kbd> zooms in and <kbd>&darr;</kbd> zooms out.

**Describe the solution you'd like**
An option in the `ol/interaction/KeyboardZoom` class that allows the setting of keyboard codes. Preferably something like:
```
import KeyboardZoom from 'ol/interaction/KeyboardZoom';
new Interaction.KeyboardZoom({
  zoomKeys: ['ArrowUp', 'Equal'],
  zoomOutKeys: ['ArrowDown', 'Minus'],
});
```
or even something like this to be even more flexible:
```
import KeyboardZoom from 'ol/interaction/KeyboardZoom';
import * as Condition from 'ol/events/condition';
new Interaction.KeyboardZoom({
  zoomKeys: [
    { code: 'Equal', condition: Condition.platformModifierKeyOnly },
    { code: 'ArrowUp', condition: Condition.always }
  ]
});
```

**Comment by fredj** [comment]
To be in line with other interactions we could add two new conditions in the constructor, something like:
```js
new KeyboardZoom({
  zoomInCondition: function(mapBrowserEvent) {...}
  zoomoutCondition: function(mapBrowserEvent) {...}
});
```
And a condition function could be:
```js
zoomInCondition: function(mapBrowserEvent) {
  if (platformModifierKeyOnly(mapBrowserEvent)) {
    const code = mapBrowserEvent.originalEvent.code;
    return code === 'ArrowUp' || code === 'Equal';
  }
}
```

**Comment by arcataroger** [comment]
Was this functionality ever added?
