### ISSUE TITLE
The rotate() method corrupts the extent of circle geometry

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9415]
**To Reproduce**

var center = [100000, 100000];
var radius = 50000;
var geom = new ol.geom.Circle(center, radius);
var turns = 10
for (var i=0; i<turns; i++) {
  geom.rotate(2*Math.PI/turns, center);
  console.log(geom.getCenter() + ' ' + geom.getRadius());
  var extent = geom.getExtent();
  console.log('' + extent);
}

var center = [100000, 100000];
var radius = 50000;
var geom = new ol.geom.Circle(center, radius);
var turns = 10
for (var i=0; i<turns; i++) {
  geom.rotate(2*Math.PI/turns, [200000, 200000]);
 // console.log(geom.getCenter() + ' ' + geom.getRadius());
  var extent = geom.getExtent();
  console.log(ol.extent.getWidth(extent) + ' ' + ol.extent.getHeight(extent));
}

**Comment by fredj** [comment]
> yes, that because the rotate function was not implemented for circle geometries

The same is true for the scale and transform functions
