### ISSUE TITLE
Add an option for disabling interim tiles

### ISSUE THREAD

**Issue by elemoine** [openlayers/openlayers#9419]
When displaying a tile, if that tile is not loaded yet, OpenLayers assumes that it is pertinent to display an "interim tile", that is a tile that has the same tile coordinates as the parent tile but with a different key – different PARAMS for a WMS source. The relevant code is [here](https://github.com/openlayers/openlayers/blob/81865f70e4220d0ba106c46815796fa44758873e/src/ol/source/TileImage.js#L329-L346).

That behavior is appropriate for some use-cases, as in the [wmts-dimensions](https://openlayers.org/en/latest/examples/wmts-dimensions.html) example. But it is not for other use-cases. For example think about the case of a WMS source where the LAYERS and FILTER params change based on user selections. In that case when the user unselects a layer in the UI you don't want to show "old" tiles. I am seeing very disturbing artifacts in an OL application because of interim tiles.

So I think it would make sense to add a `useInterimTiles` option to the tile sources. That option would default to `true`, but users would be able to set it to `false` for cases where "interim tiles" do not make sense.

Note that the issue I describe here is completely different from https://github.com/openlayers/openlayers/issues/5251. With "interim tiles" the latter refers to parent tiles at lower resolutions, while this issue refers to tiles with the same x/y/z but with different keys/params.

What do you think?

**Comment by ahocevar** [comment]
Since #9250, you can call `clear()` on a source to get rid of interim tiles. So assuming you currently call `updateParams()` on a WMS source, you could change that code to
```js
source.clear();
source.updateParams(newParams9;
```

**Comment by elemoine** [comment]
Thanks a lot for the quick answer @ahocevar. That makes sense. I'll give it a try.

**Comment by elemoine** [comment]
That does have an effect on our application. We still have problems but I guess they're unrelated to that particular Issue, so I am going to close it for now.

Thanks again!

**Comment by elemoine** [comment]
@ahocevar the other problems I have are related to what I think is a bug in the TileLayer renderer. The bug is with v5.3.0, master works fine. Is it worth reporting the issue? Do you plan to make a v5.3.1? I guess not…

**Comment by elemoine** [comment]
By the way, this is what fixes the problem I am seeing:

```diff
diff --git a/src/ol/renderer/canvas/TileLayer.js b/src/ol/renderer/canvas/TileLayer.js
index 4299e4d39..680e5ba80 100644
--- a/src/ol/renderer/canvas/TileLayer.js
+++ b/src/ol/renderer/canvas/TileLayer.js
@@ -234,7 +234,8 @@ class CanvasTileLayerRenderer extends IntermediateCanvasRenderer {
           canvas.width = width;
           canvas.height = height;
         } else {
-          if (this.renderedExtent_ && !equals(imageExtent, this.renderedExtent_)) {
+          if ((this.renderedExtent_ && !equals(imageExtent, this.renderedExtent_)) ||
+              this.renderedRevision != sourceRevision) {
             context.clearRect(0, 0, width, height);
           }
           oversampling = this.oversampling_;
```

Although I am not yet sure this is the correct fix for this.

**Comment by ahocevar** [comment]
@elemoine If you can, I'd suggest using v6, currently at 6.0.0-beta.5. We'll be releasing 6.0 final very soon.

**Comment by elemoine** [comment]
> @elemoine If you can, I'd suggest using v6, currently at 6.0.0-beta.5. We'll be releasing 6.0 final very soon.

Yep, maybe. The application I am working on (with others) is about to be released, so I guess it's not a good time for updating it to using 6.0.0-beta.5.

> Your fix above makes sense though. If you want, you can create a pull request against the v5.3.x branch, from which we can release v5.3.2.

Cool. I'll do that then. I can also provide an example demonstrating the problem.
