### ISSUE TITLE
map export rotated not working at v6.0.0-beta5

### ISSUE THREAD

**Issue by AidasK** [openlayers/openlayers#9436]
**Describe the bug**
map export rotated not working at v6.0.0-beta5
Result:
![map (23)](https://user-images.githubusercontent.com/2088484/56148775-b14e6380-5fb3-11e9-9e4a-cd684cd2e45b.png)

**To Reproduce**
- Go to the example: https://openlayers.org/en/master/examples/export-map.html
- Rotate the map (alt+shift+mouse pan)
- Export

Old version was working at: https://openlayers.org/en/latest/examples/export-map.html
Result 5.3.0:
![map (24)](https://user-images.githubusercontent.com/2088484/56148847-dc38b780-5fb3-11e9-8eea-96400dbff3ac.png)

**Comment by mike-000** [comment]
The **Export PDF** example is more significantly affected, the image is distorted and requires cropping on all four edges, although the output in previous versions also seems suspect.

For the png example a simple crop of the hidden overflow from the right and bottom of dom-to-image result appears to suffice:
```
document.getElementById('export-png').addEventListener('click', function() {
  map.once('rendercomplete', function() {
    domtoimage.toPng(map.getViewport().querySelector('.ol-layers'))
      .then(function(dataURL) {
        var img = new Image();
        img.onload = function() {
          var size = map.getSize();
          var canvas1 = document.createElement('canvas');
          canvas1.width = size[0];
          canvas1.height = size[1];
          var ctx1 = canvas1.getContext('2d');
          ctx1.drawImage(img, 0, 0, size[0], size[1], 0, 0, size[0], size[1]);
          var dataURL1= canvas1.toDataURL();
          var link = document.getElementById('image-download');
          link.href = dataURL1;
          link.click();
        };
        img.src = dataURL;
      });
  });
  map.renderSync();
});
```

**Comment by ahocevar** [comment]
An easier fix would be to use `domtoimage.toPng(map.getTargetElement()`, and do something like
```js
document.querySelectorAll('.ol-control').forEach(el => el.style.visibility = 'hidden');
```
before that. That should also work for the pdf example.

Any takers for a pull request?

**Comment by ahocevar** [comment]
And maybe html-to-image instead of dom-to-image-more would make the example work in Safari too.
