### ISSUE TITLE
Canvas renderer might throw TypeError: Cannot read property 'forEachFeatureAtCoordinate' of undefined

### ISSUE THREAD

**Issue by aberenyi** [openlayers/openlayers#9437]
**Describe the bug**
If a Vector Tile Layer has a composite source (e.g. `https://{a-d}.tiles.mapbox.com/v4/<source1>,<source2>/{z}/{x}/{y}.vector.pbf'`) and one of the sources is hidden at the given resolution/zoom level (e.g. polygons and their centroids), one might encounter a `VectorTileLayer.js:318 Uncaught TypeError: Cannot read property 'forEachFeatureAtCoordinate' of undefined` when trying to use `map.forEachFeatureAtCoordinate`.

**To Reproduce**
3. See error

**Expected behavior**
https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/renderer/canvas/VectorTileLayer.js#L262 should be `found = found || replayGroup && replayGroup.forEachFeatureAtCoordinate(coordinate, ...`

Cheers

**Comment by ahocevar** [comment]
That code has been completely reworked since 5.3. Do you see the same issue with master or ol@beta?

**Comment by 172476032** [comment]
I have  the same problem in my project，I use version 5.3.3。

**Comment by 172476032** [comment]
![QQ图片20190621090144](https://user-images.githubusercontent.com/21135209/59890385-39f9dd80-9403-11e9-922f-48b11bcddb33.png)
