### ISSUE TITLE
Manipulate color of 'terrain-lines" Stamen map

### ISSUE THREAD

**Issue by crabdul** [openlayers/openlayers#9438]
What steps would need to be taken to do color manipulation with the 'terrain-lines' Stamen map?
I want to achieve the same color manipulation that's done in the [Color manipulation example](https://openlayers.org/en/latest/examples/color-manipulation.html) with the 'watercolor' Stamen map. I'm happy to open a PR

**Comment by ThomasG77** [comment]
Just change the `watercolor` string in the sample with `terrain-lines` and it's done. Layer `terrain-lines` is already supported https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/source/Stamen.js#L37

**Comment by crabdul** [comment]
@ThomasG77 fantastic! I'll give it a try

**Comment by crabdul** [comment]
I can get `terrain` to work but not `terrain-lines` to change colour. No matter what hue value I change it to, the map looks like below:
![Screenshot 2019-04-17 at 09 32 39](https://user-images.githubusercontent.com/23074754/56273023-d649f000-60f3-11e9-8269-398e7a653c9b.png)

**Comment by mike-000** [comment]
Hue will have no effect on a grayscale image where all pixels have equal ratios of the primary colours.  To add colour you would need additional inputs to reduce or remove at least one of the RGB values of the pixels, for example:

```
function rgb2hcl(pixel) {
  var red = rgb2xyz(pixel[0]*redScale);
  var green = rgb2xyz(pixel[1]*greenScale);
  var blue = rgb2xyz(pixel[2]*blueScale);
```

**Comment by crabdul** [comment]
@mike-000 that is exactly what I was looking for! 
@fredj really appreciate the example, it looks great.

Thanks for your work on this project, it's superb
