### ISSUE TITLE
How the map can stay il the view element ?

### ISSUE THREAD

**Issue by daxpunk** [openlayers/openlayers#9445]
Hi,
is there a solution to fix the bottom of the view to the bottom of the map element and the the same to the top.
I have tested many solutions ... but when i drag vertically, it's over the map limits.

The problem here :
![Capture d’écran de 2019-04-18 20-44-28](https://user-images.githubusercontent.com/11540797/56384514-d72a7100-621c-11e9-84b0-a44110e48510.png)

and here : 
![Capture d’écran de 2019-04-18 20-44-23](https://user-images.githubusercontent.com/11540797/56384538-e8737d80-621c-11e9-97ac-4913425f2f07.png)

Dax

**Comment by ahocevar** [comment]
This has been resolved. You can try it using `ol@beta` already.

**Comment by daxpunk** [comment]
Hum, I have the same problem with theol@6.0.0-beta.6

When I drag the map after the layer top or after the layer bottom, I see the white background.
I don't know how to do to stop at the limits of the layer.

Regards
Damien

**Comment by ahocevar** [comment]
Configure the view with the extent you do not want to go past, e.g.
```js
import {get} from 'ol/proj';

const view = new View({
  extent: get('EPSG:3857').getExtent();
}):
```

**Comment by daxpunk** [comment]
super !! :)
thanks.
