### ISSUE TITLE
Can you tell me release date about openlayers 6?

### ISSUE THREAD

**Issue by purpletortoise-choi** [openlayers/openlayers#9446]
Hello.
After posting [that](https://github.com/openlayers/openlayers/wiki/OpenLayers-6:-call-for-funding,-last-call)
I really expect openlayers 6 to be released. 
Because I will migrate openlayers 6 from openlayers 5. 
But I don't know when it release date.

**Can you tell me release date about openlayers 6?**

Thank you. : )

**Comment by ThomasG77** [comment]
Just an addition but not a definitive answer (I'm not a core committer).
There is no release date exactly according to https://github.com/openlayers/openlayers/milestone/38
The only sure thing is that 2 more features at the moment have to be closed before the release.
You don't need the stable release to prepare your migration as there is already an Openlayers 6 beta 6 available e.g https://www.npmjs.com/package/ol?activeTab=versions
The official workshop has also been updated e.g https://github.com/openlayers/workshop
