### ISSUE TITLE
icons blurry on mouse down (>= v6.0.0.-beta3)

### ISSUE THREAD

**Issue by Swiod** [openlayers/openlayers#9449]
An icon is becoming blurry when clicked anywhere on the map. Seems that it is related to Point features, as Point styles in general are getting blurry when clicked somewhere on the map. Reproduced on Desktop (Chrome, FF and Edge)

1. go to https://openlayers.org/en/master/examples/icon.html?q=icon
2. click anywhere on the map
3. see how the icon is moved a little bit and becomes blurry

Some more examples: 
- https://openlayers.org/en/master/examples/cluster.html?q=cluster
- https://openlayers.org/en/master/examples/draw-features.html?q=draw

It seems as #9137 did change the behavior. Taking a look at DragPan interaction, setting the INTERACTING state moved from pointer move to pointer down.

**Comment by ahocevar** [comment]
Thanks for reporting this. #9450 moves the code that sets the interacting flag back to the pointerdrag listener.
