### ISSUE TITLE
Openlayer is not accessible in Iran

### ISSUE THREAD

**Issue by xcomhz** [openlayers/openlayers#9451]
**Describe the bug**
Openlayer.org and my application are not accessible in Iran. is there any problem the domain is blocked by owners or are you aware about that?
**To Reproduce**
when i try to open https://openlayers.org/ or my server address included ol application the browser shows 'waiting gor openlayer.org....' and do nothing , you could test by openning https://openlayers.org/

**Expected behavior**
there are many problem for our country sanctions, but i expect the open source and science to be respected. i think it is because of sanctions but i also think sanctions will be end a day!

**Comment by ThomasG77** [comment]
Hi,

The website source code is completely available on [github](https://github.com/openlayers/openlayers.github.io/), on the master branch

Command line solution (on Linux)

```
wget https://github.com/openlayers/openlayers.github.io/archive/master.zip
unzip master.zip
cd openlayers.github.io
# If using Python 2
python2 -m SimpleHTTPServer 8000
# Or if using Python 3
python3 -m http.server 8000
```

And open http://localhost:8000 to see below result: nearly offline website (maybe, some calls are made to some CDNs)

![OpenLayers - Welcome - Google Chrome_021](https://user-images.githubusercontent.com/642120/56442990-ef6cbf80-62f2-11e9-9a31-39e582121976.png)

Feel free to ask for GUI recipe if required
