### ISSUE TITLE
Support feature property access in fragment shaders

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#9454]
It is handy that users can leverage the `opacityCallback` to have access to a varying float derived from a feature in a custom fragment shader (as in #9390).  Instead of using the opacity varying for this purpose, it would be nice to have a 1st class way to do this and support more than a single float.

One option would be to add support for a `varyings` option for the WebGL point layer renderer.  This would take an object like this:
```
varyings: {
  v_foo: feature => feature.get('foo'),
  v_bar: feature => feature.get('bar')
}
```

@jahow - I’m curious to hear your thoughts.  This is something I'd be happy to take on if you agree it is a good idea.

**Comment by jahow** [comment]
Definitely, this was on my list of things to do eventually. The tricky part will be to make this work with the code here: https://github.com/openlayers/openlayers/blob/d5b868f4a6c94bd9e515884f5dd58385e5c04325/src/ol/renderer/webgl/PointsLayer.js#L283-L340

It'd great if you can take care of it! Thanks

**Comment by jahow** [comment]
This still has to be implemented, here is a work in progress for the record:
https://github.com/jahow/openlayers/tree/webgl-points-custom-attr
