### ISSUE TITLE
Render points as circles by if no texture or fragment shader are supplied

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#9455]
The WebGL points layer renderer is a handy way to render a lot of points even if you don't hand author the vertex or fragment shader.  I think the renderer would be more useful by default if we rendered points as circles if the user doesn't supply a `texture`.

@jahow - curious what you think about using a fragment shader with the `smoothstep` trick for rendering circles if a `texture` is not provided.

**Comment by jahow** [comment]
Yes great idea. At some point I was also thinking of providing a few pre-written shaders, this could be for example flat square and flat circle? IMO this would put less abstraction on the shader part compared to an implicit switch of shaders depending on the options given.
