### ISSUE TITLE
openlayers raster source

### ISSUE THREAD

**Issue by saurabhgis** [openlayers/openlayers#9456]
Sir

I am working on openlayers raster source, here i want to count the pixels inside each polygon feature but not able to do this task please suggest some solution.

Regards,
sbh.upd1@gmail.com

**Comment by mrpan** [comment]
you may ask or find some solution at https://stackoverflow.com/

**Comment by fredj** [comment]
Please ask usage questions on stackoverflow instead with the tag openlayers

https://stackoverflow.com/questions/tagged/openlayers
