### ISSUE TITLE
Ol 6 beta performance problem with multiple layers

### ISSUE THREAD

**Issue by jeroenvheel** [openlayers/openlayers#9457]
**Describe the bug**
When creating a map with multiple layers in the old version of openlayers the performance was okay now its not working any more panning and zooming is really slow

**To Reproduce**
create a map like this:
And when you start adding layers from the attached zip file you can see it gets slower and slower.
ol 6.0.0-beta6 https://codesandbox.io/s/14kkpqkxjl
ol 5.3.0  https://codesandbox.io/s/mjv0r8138y?fontsize=14

and then you can use the attached zip to add layers.

[gpx-files.zip](https://github.com/openlayers/openlayers/files/3101158/gpx-files.zip)
![ol-6b6 performance](https://user-images.githubusercontent.com/228655/56469467-77111600-643a-11e9-9834-1794af85e595.png)
![ol 6b6-code](https://user-images.githubusercontent.com/228655/56469468-7c6e6080-643a-11e9-907b-6433cbaabd57.png)

**Expected behavior**
The map is as fast a the pervious versions of Openlayers

**Comment by Jinkwon** [comment]
I found same issue. 
We add only 7 layers, and so slow performance with composite layers.
No issue with version 5.

**Comment by ahocevar** [comment]
What layer types were you using @Jinkwon? Vector?

**Comment by jeroenvheel** [comment]
@ahocevar is this because of that all layers has its own canvas layer. You mentioned this in a closed issue.

**Comment by jeroenvheel** [comment]
I forgot to mention i use a 4K screen with a map that fills the hole screen.
Itested it with the chrome stable and beta version and there the VectorImage layer are realy slow.
When I use Vector layer it is a little faster. I find that strange because in the previous version of openlayers the image rendering was the fastest way.

Today i tested it with firefox and firefox nightly and there the speed is much better when using the Vector layers.

**Comment by vindic** [comment]
Trying to update our WebGIS with OL6 and we are having the same problem with Firefox.

In the task manager it seems that the GPU is used heavily and his ram too (Test done on Windows 10 and Linux Ubuntu 18.04)

You can test here : 

Ol V6 : https://sig-delos.efa.gr/index.php?SIG=Delos&ol_version=6 

OL V5 : https://sig-delos.efa.gr/index.php?SIG=Delos

Weirdly V6 seems to work faster on Chrome.

Is there some configuration to be modified or code rewriting to do ?
