### ISSUE TITLE
layer.setMap() not always on top

### ISSUE THREAD

**Issue by Kai-W** [openlayers/openlayers#9461]
layer.setMap can be behind Layers that are added to the map with map.addLayer()
From jsDoc ot ol/layer/Layer.setMap(): "Sets the layer to be rendered on top of other layers on a map"
I had this Problem with a VectorLayer wit ZIndex > 0. As Workaround a ZIdex can be set to the temporaray Layer

**Comment by tschaub** [comment]
Please provide an example that demonstrates the problem.  You can start with one of the hosted examples (e.g https://openlayers.org/en/master/examples/simple.html).  Click the edit button and make changes that demonstrate your problem.  Then you can paste the URL to your example here.

**Comment by Kai-W** [comment]
https://codesandbox.io/embed/wnq1q843qw

**Comment by mrpan** [comment]
it't not the problem  if you change zindex, you  must promise the layer index is right!

**Comment by Kai-W** [comment]
I dont know waht you mean by promise the layer index right.
And i think it is a Problem. The behaviour changed vorm OL5 to 6 and i just found out breaks other Komponents.
For example ol/interaction/Draw internaly uses it (Mehtod updateState_()). I modified the example to show that too.

**Comment by ahocevar** [comment]
Thanks for the bug report @Kai-W. This was indeed a regression, and I have just created #9492 to fix it.
