### ISSUE TITLE
Problem when moving initial/end point of a polygon over another point 

### ISSUE THREAD

**Issue by angelocavallet** [openlayers/openlayers#9463]
When you drag/move the initial point of a polygon (the first point that you drawn) over another point of the same polygon, they get "merged" in a way that you cannot separate them anymore.
The same thing happens if you move/drag some point over the initial point.
The same behavior doesn't happen if you move another point (that isn't the initial point).

**How to reproduce:**
https://openlayers.org/en/latest/examples/draw-and-modify-features.html

Draw a polygon
(The northest point is the initial)

![image](https://user-images.githubusercontent.com/5768381/56662345-22f47480-667a-11e9-8869-4f1f9bb4dbf3.png)

Drag/move the initial point over another point
Try to separate them again

(Sorry, I can't add more print screens because something went wrong with github)

**Expected behavior**
The expected behavior is the same that happen when you move another point (that isn't the initial point).

**Comment by ahocevar** [comment]
The issue is still present. Here is a screencast of the unexpected behavior:
![Jun-04-2019 15-32-46](https://user-images.githubusercontent.com/211514/58883568-f6069900-86de-11e9-8ebe-e4e5005d51eb.gif)
