### ISSUE TITLE
LineString(coordinates, opt_layout) constructor not working with Coordinate array

### ISSUE THREAD

**Issue by brianwvincent** [openlayers/openlayers#9465]
**Describe the bug**
When instantiating a LineString with an Array of Coordinates (i.e. [[num1, num2], [num1,num2]]... etc. ), an exception is thrown, specifically: "**_Uncaught TypeError: this.setCoordinates is not a function
    at Object.e [as LineString] (ol.js:7)..._**"

**To Reproduce**
1) Create Array of Coordinates 
2) Attempt to instantiate LineString with step1 and Geometry Layout string as parameters
Code to reproduce the behavior:

WFS request:
$.ajax(url, {
                method: 'GET'
            }).done(function(response){

                // get array of features
                var fs = response.features;

                // create Array of coordinates
                fs.forEach(function(feature){
                    var coords = feature.geometry.coordinates;
                    coor_array.push(coords);
                });

               // instantiate LineString from Array of coordinates (per OpenLayers documentation)
                var lineString = ol.geom.LineString(coor_array,'XY');
                
                ... etc, etc, etc.
            });

**Expected behavior**
The expected behavior, per the OpenLayers docs, is to be able to instantiate a LineString when passing in an Array of Coordinates, and a Geometry Layout string as parameters.

**Comment by marcjansen** [comment]
Were you missing a `new`?

**Comment by brianwvincent** [comment]
I was and that's why I closed the issue.   Silly user error.

**Comment by marcjansen** [comment]
No worries, happens to everyone all the time.
