### ISSUE TITLE
Popup in example no longer moves with the map

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#9467]
**Describe the bug**
In the [popup example](https://openlayers.org/en/master/examples/popup.html) the overlap no longer pans with the map.

**To Reproduce**
1. Go to https://openlayers.org/en/master/examples/popup.html
2. Click on the map to open the popup
3. Pan the map and see the popup not move

![popup](https://user-images.githubusercontent.com/41094/56762252-aab2af80-675c-11e9-90c6-b52e905ab7f4.gif)

**Expected behavior**
The popup should pan with the map.  Just like in the [overlay example](https://openlayers.org/en/master/examples/overlay.html).

**Comment by ThomasG77** [comment]
FYI, work on Firefox but not on Chrome on my side. Seems related to #9139 but did not find a solution

**Comment by ahocevar** [comment]
Safari has a different issue with the same issue: the popup does move with the map, but the drop shadow for previous remains on the screen while panning until the user scrolls down on the example page and back up.

**Comment by s-haralampiev** [comment]
Has the issue been fixed, I am experiencing the same results. Is there any workaround for resolving this?

**Comment by tschaub** [comment]
@s-haralampiev - if you can provide detail on how someone else can reproduce the issue you are seeing, and if it matches the description of this ticket (popup does not move when panning the map), please reopen the issue.  Please include information on the browser you are using and the version of the library.

All v6 releases have the fix (300522e3cce32a9efee7831b1b722416529c26d5).  And I can confirm that the [popup example](https://openlayers.org/en/master/examples/popup.html) running the latest commit in the master branch (a5f5eaf36600c7e68a5bebb7bb968ea09ce6b2a4) does not demonstrate the issue in Chrome 83 or Safari 13.

**Comment by s-haralampiev** [comment]
Chrome Version 81.0.4044.138
"ol": "6.3.1",

![ezgif com-apng-to-gif (1)](https://user-images.githubusercontent.com/42935520/83445804-52b5a480-a456-11ea-85bb-da759f2eb312.gif)

**Comment by ThomasG77** [comment]
Does not reproduce with popup official example with OpenLayers "master"
Tried local OpenLayers 6.3.1 with this code https://gist.github.com/ThomasG77/822b9ac2cd180793021c7113ca8d533d (export from https://openlayers.org/en/master/examples/popup.html and replacement of maptiler background with OSM)

Both tested with Chrome Version 83.0.4103.61 (Ubuntu 64 bits)

**Comment by tschaub** [comment]
@s-haralampiev - can you provide the code for the example in the movie you made above?  @ThomasG77 's [gist](https://gist.github.com/ThomasG77/822b9ac2cd180793021c7113ca8d533d) is one example of how code can be shared.  Here is another version of that same example running ol@6.3.1: https://codesandbox.io/s/pensive-stonebraker-bcb85?file=/main.js

**Comment by s-haralampiev** [comment]
Here's a sandbox with the code 
https://codesandbox.io/s/distracted-engelbart-8722q

Now that I'm comparing the examples I think this issue could be due to the popover

**Comment by tschaub** [comment]
Here is a version that works: https://codesandbox.io/s/jolly-sutherland-129pm

This seems a bit redundant and like it should not be necessary, but I added `container: element` to the popup in `src/index.js`.
```diff
   overlay.setPosition(coordinate);
   $(element).popover({
+    container: element,
     placement: "top",
     animation: false,
     html: true,
```

In addition, I added `.popover-body {width: 250px}` to the styles in `index.html`.
```diff
         width: 100%;
         height: 400px;
       }
+      .popover-body {
+        width: 250px;
+      }
     </style>
   </head>
   <body>
```

And then I deleted `src/styles.css` since that wasn't being used.

**Comment by s-haralampiev** [comment]
Thank you @tschaub

**Comment by b310L** [comment]
replace direction:'ltr' instead direction:'rtl'
