### ISSUE TITLE
Event name documentation missing

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#9471]
**Describe the bug**
In the api documentation the names of special events do not appear.

**To Reproduce**
See for example https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html
under `Fires:` only the type of the event is shown (`DrawEvent`) but not the names. (`drawstart` and `drawend`)

**Expected behavior**
Like with the generic `change` events this should appear as: `drawstart (DrawEvent)`

**Comment by marcjansen** [comment]
Do you think you can come up with a PR?

**Comment by simonseyock** [comment]
I don't know if I have the time at the moment. But It depends on the root of the cause.

The current line in the code looks like `@fires DrawEvent` and was `@fires module:ol/interaction/Draw~DrawEvent` before  and `@fires ol.interaction.DrawEvent` before that.

If you look at https://openlayers.org/en/v4.6.5/apidoc/ol.interaction.Draw.html the events get documented correctly. 

I think the events were somehow autogenerated by the apidoc generator. Can you tell me if this was done before by some custom plugin for jsdoc and where the code for this plugin lives?

**Comment by marcjansen** [comment]
From the top of my head I cannot tell you where these come from. Maybe @ahocevar, @tschaub or @kaivolland can point you the right direction

**Comment by tschaub** [comment]
This change makes the event names show up for the draw interaction:
```diff
diff --git a/src/ol/interaction/Draw.js b/src/ol/interaction/Draw.js
index 3d28104..6943b00 100644
--- a/src/ol/interaction/Draw.js
+++ b/src/ol/interaction/Draw.js
@@ -134,13 +134,13 @@ const Mode = {
 const DrawEventType = {
   /**
    * Triggered upon feature draw start
-   * @event DrawEvent#drawstart
+   * @event module:ol/interaction/Draw~DrawEvent#drawstart
    * @api
    */
   DRAWSTART: 'drawstart',
   /**
    * Triggered upon feature draw end
-   * @event DrawEvent#drawend
+   * @event module:ol/interaction/Draw~DrawEvent#drawend
    * @api
    */
   DRAWEND: 'drawend'
```

I'll dig a bit more to see if we can make this work without the full longname.

**Comment by tschaub** [comment]
This may not be related, but I notice that in the `events.js` plugin we build up a `classes` object but never use it.

https://github.com/openlayers/openlayers/blob/fde36b237e6cc1c4a4c76ed95f7601f373f86f92/config/jsdoc/api/plugins/events.js#L6-L18

In https://github.com/openlayers/openlayers/commit/a75d944311e8949d73f396c5c2902c30d19467b2#diff-2315b0fa6968a2f0446c2937b99fe14a, we removed the one place data in this `classes` object was used.

**Comment by tschaub** [comment]
See https://github.com/openlayers/jsdoc-plugin-typescript/pull/5.

**Comment by simonseyock** [comment]
Thanks for the fix!
