### ISSUE TITLE
backgroundFill and backgroundStroke on text style not honored during postcompose animation

### ISSUE THREAD

**Issue by jure965** [openlayers/openlayers#9478]
During development of my app, I found out that backgroundFill and backgroundStroke on text style are ignored during postcompose animation.

Feature
![text1](https://user-images.githubusercontent.com/1488484/56882984-9c6ad900-6a65-11e9-89a4-eca606b42beb.png)
During postcompose animation
![text2](https://user-images.githubusercontent.com/1488484/56882993-a55baa80-6a65-11e9-998b-f279f65508bc.png)

I prepared a sample derived from animation example on OL examples page.
JsFiddle
https://jsfiddle.net/cmuqLx3r/

Same sample in pastebin form.
https://pastebin.com/9vRYD2wz

**Comment by mike-000** [comment]
vectorContext has other undocumentated limitations.  Another can be seen if you replace `text: "test text",` with `text: "test\ntext",`

**Comment by Yuki-Zhao** [comment]
i also met this problem. the backgroundFill of ol.style.Text doesn't show. only one point show.
![image](https://user-images.githubusercontent.com/22816207/75126093-5fa65780-56f3-11ea-878c-30fe6ce76848.png)

**Comment by mike-000** [comment]
@Yuki-Zhao  If you had a postcompose/postrender problem the background would not be displayed for any points.  If you see the background for only one point is more likely you are seeing something related to the problems described in #10098

**Comment by Yuki-Zhao** [comment]
![image](https://user-images.githubusercontent.com/22816207/75324646-5f07ef80-58b2-11ea-807b-c3f58e673659.png)
The background fill does't work

**Comment by Yuki-Zhao** [comment]
![39JZJ5RQP(4P~}YWL2JWW0I](https://user-images.githubusercontent.com/22816207/75324719-83fc6280-58b2-11ea-9e1c-91400941e3f5.png)
The backgroundFill of ol.style.Text doesn't work

**Comment by Yuki-Zhao** [comment]
![QQ图片20200226161016](https://user-images.githubusercontent.com/22816207/75324817-b4440100-58b2-11ea-8e00-870a5ed4c8fd.png)
The backgroundFill of ol.style.Text doesn't work

**Comment by Yuki-Zhao** [comment]
![ON~XU22$R(@I3{XMPIYE8$X](https://user-images.githubusercontent.com/22816207/75324989-f8cf9c80-58b2-11ea-8365-bae3646c3dd0.png)

The backgroundFill of ol.style.Text doesn't work

**Comment by mike-000** [comment]
But does it appear for just one point? https://codesandbox.io/s/vector-label-decluttering-ssve7

**Comment by Yuki-Zhao** [comment]
yes! and some level, the backgroundfill doesn't work . some leverl, it work. why?

**Comment by mike-000** [comment]
It's a decluttering bug #10098
