### ISSUE TITLE
Change the ScaleLine according to resolution

### ISSUE THREAD

**Issue by BenukEl** [openlayers/openlayers#9480]
I would like to change the ScaleLine unit according to the resolution. In my case, show distance in nautical unit when distance is more than one and meter when it is less.

To do this, I would like to add the FunctionUnits type in ScaleLine module and when units parameter is a FunctionUnits, executes it. 
The FunctionUnits will be a function(nominalCount: number, pointResolution: number)::{
    suffix: string
    pointResolution: number
}

I can make changes if you are agree.

**Comment by mrpan** [comment]
i think ,you can create a custom ScaleLine module to do this.

**Comment by fredj** [comment]
What about listening to the resolution change events and set the units accordingly?
Something like:
```js
map.getView().on("change:resolution", function(event) {
  var resolution = event.target.getResolution();
  if (resolution > 500) {
    scaleLine.setUnits("metric");
  } else {
    scaleLine.setUnits("degrees");
  }
});
```

**Comment by BenukEl** [comment]
Hello @fredj 
You probably right... It more simple...
Thank you !
I'll close this issue. If I can help to contribute tell me. I would like to help.
