### ISSUE TITLE
Use passive event listeners

### ISSUE THREAD

**Issue by neave** [openlayers/openlayers#9482]
Currently mouse and touch events in OpenLayers do not use passive events listeners, which show up as warnings in the console in Chrome. This can be easily fixed by patching events.js here: https://github.com/openlayers/openlayers/blob/e4f377fb4697907fd68a39f7bfcd6497c38c251a/src/ol/events.js#L174

by adding the following to events.js:

	var hasPassive = false;
	try {
		var _opts = Object.defineProperty({}, 'passive', {
			get: function() {
				hasPassive = true;
			}
		});

		window.addEventListener('_', null, _opts);
		window.removeEventListener('_', null, _opts);
	} catch (error) {}

and then amending line 174 to this:

	addEventListener(type, bindListener(listenerObj), hasPassive ? { passive: false } : false);

Also see: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners
I can PR this if it would help.

**Comment by fredj** [comment]
see #8387
