### ISSUE TITLE
Declutter conflicts with translate for points

### ISSUE THREAD

**Issue by Chris1234567899** [openlayers/openlayers#9483]
**Describe the bug**

The declutter function of vectorlayers is buggy for points. If declutter is true, you can select a point, but not interact with the selection anymore.
If declutter is false, everything works as expected.

**To Reproduce**
1. Go to https://codepen.io/anon/pen/OGYmxN
2. flip the declutter option  in the code between true and false
3. If false, you can drag the point, if true, you can't

**Expected behavior**
Interactions should always work, no matter if the layer has declutter activated or not.

Generally I would favor a rework of the declutter functionality, maybe incl;ude an optional function, where you can set the z-index on a feature individually, maybe let it depend on geometry type, zoom level etc). As it is now, it is very limited and intransparent.

**Comment by Chris1234567899** [comment]
This issue should still be open.

**Comment by ahocevar** [comment]
This has been fixed since v5.3. See updated fiddle with latest master: https://codepen.io/anon/pen/GbQEJm
