### ISSUE TITLE
Interaction Modify doesn't properly clear feature

### ISSUE THREAD

**Issue by lawrencesim** [openlayers/openlayers#9485]
When clearing the features from the source (on which modify interaction is tied to), modify interaction clears the features visually, but still interacts with the edges where the feature used to be.

Related to ticket #4043 but since that has no reply and is 4 years old, thought it best to resubmit.

Tested on version 5.3.0

**To Reproduce**
https://jsfiddle.net/ecob0p6w/18/

1. Create a feature (or several) with draw a feature button. 
2. Clear features with clear all features button. 
3. Hover where the old features used to be, you'll see the modify interaction still showing cursor interactions and modifying this "ghost" feature.

**Comment by mike-000** [comment]
It's because you use `source.clear(true);` to suppress removefeature events the modify interaction isn't informed.  With `source.clear();` the problem disappears.

**Comment by lawrencesim** [comment]
Ah dang. Forget where I picked up starting using the `opt_fast` parameter almost by default, but that explains it. Thanks!
