### ISSUE TITLE
KML string validation with extendedData

### ISSUE THREAD

**Issue by edellucien** [openlayers/openlayers#9496]
**Describe the bug**
When creating a KML String with KML.writeFeatures(), with extendedData, the format isn't validated correctly.

**To Reproduce**
1. Create an array of features, e.g. Line with style and custom property 'lineDash'.
2. Write a KML string with:
`featString = new KML({
extractStyles: true,
defaultStyle: [kmlStyle],
}).writeFeatures(exportFeatures);`

Output:
< kml
  xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.opengis.net/kml/2.2 
  https://developers.google.com/kml/schema/kml22gx.xsd">
  < Document>
    < name>Editor< /name>
    < Placemark>
      < ExtendedData>
        < Data name="lineDash">< value>1,10</value>< /Data>
      < /ExtendedData>
      < Style>
        < LineStyle>< color>ff0000ff< /color>< width>4< /width>< /LineStyle>
      </Style>
      < LineString>
        < coordinates>
          7.969207763671874,46.941824493511206 8.666839599609375,47.246610279847005 
          8.735504150390627,47.039246258977784
        < /coordinates>
      < /LineString>
    < /Placemark>
  < /Document>
< /kml>

3. Validate the KML string against the KML schema `kml22gx.xsd` fails:
[https://developers.google.com/kml/schema/kml22gx.xsd](https://developers.google.com/kml/schema/kml22gx.xsd)

**Expected behavior**
The tag < ExtendedData > should be located after the <Style> tag in the KML string.

**Comment by ahocevar** [comment]
Pull request welcome.

**Comment by edellucien** [comment]
@ahocevar here is the Pull request: https://github.com/openlayers/openlayers/pull/9500
