### ISSUE TITLE
VectorTile with URL & TileGrid no longer overzooms in OL6

### ISSUE THREAD

**Issue by ZachTRice** [openlayers/openlayers#9499]
**Describe the bug**
In ol v5.3.0, I am able to overzoom MVT vector tiles but I am unable to overzoom in ol v6.0.0-beta[x]

-----------
**Examples**

![ol5 3-zoom_in_out](https://user-images.githubusercontent.com/17348884/57241845-f50b1a80-6fff-11e9-81a8-d2e081afc77c.png)
_OpenLayers v5.3.0_
v5.3.0 Live example: https://zachtrice.github.io/projects/wv-vectors-ol5.3.0/?t=2019-04-23-T00%3A00%3A00Z&l=MODIS_Aqua_Thermal_Anomalies_All_v6_NRT,BlueMarble_ShadedRelief_Bathymetry&v=-77.625,-28.775390625000004,57.375,37.107421875

![ol6-zoom_in_out](https://user-images.githubusercontent.com/17348884/57241850-f6d4de00-6fff-11e9-952a-7258baf5fe92.png)
_OpenLayers v6.0.0-beta6_
v6.0.0-beta6 Live example: https://zachtrice.github.io/projects/wv-vectors-ol6/?t=2019-04-23-T00%3A00%3A00Z&l=MODIS_Aqua_Thermal_Anomalies_All_v6_NRT,BlueMarble_ShadedRelief_Bathymetry&v=-77.625,-28.775390625000004,57.375,37.107421875

-----------
**Client-side Code**

Codebase: https://github.com/nasa-gibs/worldview/tree/vector-build-ol-example
VectorTile code: https://github.com/nasa-gibs/worldview/blob/vector-build-ol-example/web/js/map/layerbuilder.js#L269-L341
createMap method: https://github.com/nasa-gibs/worldview/blob/vector-build-ol-example/web/js/map/ui.js#L719-L840

-----------
**Important Notes**
- `git bisect` reveals the regression was introduced in this commit: https://github.com/openlayers/openlayers/commit/32696638d299d4ea12bf4fad40f9d318bb3bc75e
- Here is our matrixSet object (useful when looking through our codebase)
![Screenshot_7](https://user-images.githubusercontent.com/17348884/57241251-8e393180-6ffe-11e9-8465-0f3f9a1f57ca.png)

**To Reproduce**
1. Click [v5.3.0 example](https://zachtrice.github.io/projects/wv-vectors-ol5.3.0/?t=2019-04-23-T00%3A00%3A00Z&l=MODIS_Aqua_Thermal_Anomalies_All_v6_NRT,BlueMarble_ShadedRelief_Bathymetry&v=-77.625,-28.775390625000004,57.375,37.107421875) link: zoom in & observe vector points
2. Click [v6-beta example](https://zachtrice.github.io/projects/wv-vectors-ol6/?t=2019-04-23-T00%3A00%3A00Z&l=MODIS_Aqua_Thermal_Anomalies_All_v6_NRT,BlueMarble_ShadedRelief_Bathymetry&v=-77.625,-28.775390625000004,57.375,37.107421875) link: zoom in & observe missing vector points

**Expected behavior**
I expect the overzoom behavior be persistent between versions and/or documentation be provided to revert to previous behavior.

**Comment by ahocevar** [comment]
Would you be able to provide a simpler reproducable example? To make it clear at first glance that this is not caused by application code.

**Comment by ahocevar** [comment]
Make sure your tile grid configuration is correct. If you e.g. have only tiles for z14 or lower, you need to configure the tile grid or the source with `maxZoom: 14`.

**Comment by ZachTRice** [comment]
@ahoceva Here is an example using a simplified version of the code

-----------
**Examples**

![OpenLayers v5 3 0 example - Edited](https://user-images.githubusercontent.com/17348884/57467397-6f31de00-7250-11e9-831a-f1a67e5e9bfd.gif)
_OpenLayers v5.3.0_
v5.3.0 Live example: https://zachtrice.github.io/sandbox/ol-9499-ol5/

![OpenLayers v6 0 0 example - Edited](https://user-images.githubusercontent.com/17348884/57467404-735dfb80-7250-11e9-9f58-576276b7f174.gif)
_OpenLayers v6.0.0-beta6_
v6.0.0-beta6 Live example: https://zachtrice.github.io/sandbox/ol-9499-ol6/

-----------
**Client-side code**
Openlayers v5.3.0: https://github.com/ZachTRice/zachtrice.github.io/blob/master/sandbox/ol-9499-ol5/index.html
Openlayers v6.0.0: https://github.com/ZachTRice/zachtrice.github.io/blob/master/sandbox/ol-9499-ol6/index.html

**Comment by ahocevar** [comment]
Your vector tile source needs to be configured with the correct projection if it's not the default (EPSG:3857). Something like
```js
const vectorSource = new VectorTileSource({
  url: 'https://uat.gibs.earthdata.nasa.gov/wmts/epsg4326/nrt/wmts.cgi' + urlParameters,
  format: new MVT(),
  projection: 'EPSG:4326', // required if different from the 'EPSG:3857' default
  tileGrid: new TileGrid({
    extent: [-180, -90, 180, 90],
    origin: [-180, 90],
    resolutions: [0.5625, 0.28125, 0.140625, 0.0703125, 0.03515625, 0.017578125, 0.0087890625],
    tileSize: [512, 512]
  })
});
```

**Comment by ZachTRice** [comment]
This seems to work except when I reload my link in my application and load the state at a lower zoom-level, the vector tile disappears again. I will put together a simplified demo to demonstrate this behavior.
