### ISSUE TITLE
Features disapear on zoom 2->3

### ISSUE THREAD

**Issue by keyermann** [openlayers/openlayers#9502]
I render my map at zoom 2. When I zoom at lvl3 feature ouest of Greenwich disapear.
(If I render directly at zoom lvl 3, the feature ouest of Greenwich are there too).

Before : 
![ol_avant_zoom](https://user-images.githubusercontent.com/1217483/57298734-37e9f280-70d3-11e9-9cf2-d9b083c52991.png)

After : 
![ol_apres_zoom](https://user-images.githubusercontent.com/1217483/57298748-3e786a00-70d3-11e9-94c4-2c1a2ca54e14.png)

Here is my code : 
```js
require('ol/ol.css')

import Map from 'ol/Map';
import View from 'ol/View';
import TileLayer from 'ol/layer/Tile';
import VectorLayer from 'ol/layer/Vector.js';
import XYZ from 'ol/source/XYZ';
import Vector from 'ol/source/Vector';
import GeoJSON from 'ol/format/GeoJSON.js';

var station_layer_source = new Vector({
    ,url: 'http://localhost/geojson/station/all'
    ,format: new GeoJSON()
    ,crossOrigin: 'anonymous'
});

var station_layer = new VectorLayer({
    source: station_layer_source
    ,renderers: ['Canvas', 'VML']
    ,visible: true
});

new Map({
    target: 'map',
    layers: [
        new TileLayer({
            source: new XYZ({
                url: 'https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        }),
        station_layer
    ],
    view: new View({
        center: [10, 0],
        zoom: 3
    })
});
```

**Comment by fredj** [comment]
Please provide a link to a minimal example (using https://codesandbox.io or similar) that demonstrates the issue, thanks

**Comment by keyermann** [comment]
I can't for now, but I will to do that in the next few days.
