### ISSUE TITLE
EsriJSON readGeometry mutate input

### ISSUE THREAD

**Issue by kekel87** [openlayers/openlayers#9510]
**Describe the bug**
Hello,
I read geometry from Esri back-end using EsriJSON `readGeometry()` function.

I found that the original geometry was modified (either by reading the geometry again or by a read only error message from `deep-freeze`).

We observe mutating code in `EsriJSON.js` : [l.259](https://github.com/openlayers/openlayers/blob/master/src/ol/format/EsriJSON.js#L259), [l.262](https://github.com/openlayers/openlayers/blob/master/src/ol/format/EsriJSON.js#L262) among others.

**Expected behavior**
The input geometry should not be mutated.

**Workaround**
I clone the input geometry, but I find it dirty.

**Comment by loicgasser** [comment]
This is because openlayers needs to re-organize the input geometries in something it can understand. EsriJSON defines rings and other things differently than let's say geojson for instance.
https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm

**Comment by bartvde** [comment]
I agree we should not be mutating the input, PR welcome
