### ISSUE TITLE
TileGrid origin causes missing and partial tiles

### ISSUE THREAD

**Issue by tweedlebee** [openlayers/openlayers#9514]
**Describe the bug**
When an oddball origin is set on a TileGrid, not all of the tiles will be drawn. At some zoom levels, partial tiles will be drawn.

**To Reproduce**
1. (Go to https://jsfiddle.net/kay99yor/1/ to see what it should presumably look like)
2. Go to https://jsfiddle.net/6hfs9tbx/6/
3. Zoom out 
4. A portion of the south-west corner of the map is missing
5. A portion of the north-east corner is black

**Expected behavior**
Regardless of origin,
- I would expect to see all tiles which are within the view, regardless of zoom level.
- I would expect areas for which there is no data to be transparent - not black.

**A little background**
 I modified the above fiddle from one I found at https://stackoverflow.com/questions/47612523/how-to-configure-openlayers-for-a-flat-11-pixel-coordinate-system?rq=1 in order to demonstrate what is happening in my somewhat more complex application.

In my real application, I have a Vector layer (with a pixel based projection) and an MVT layer that may be slightly misaligned from that Vector layer. I am using the TileGrid's origin to bring the MVT layer into alignment with the Vector layer. The problem is that the MVT layer has partial and disappearing tiles. I suspect (?) that the same problem affects this fiddle as affects my MVT layer.

**Comment by tweedlebee** [comment]
![TileGrid Origin Issue](https://user-images.githubusercontent.com/47007704/57552041-97950780-7338-11e9-8d86-dc336fe5d7e1.png)

**Comment by ahocevar** [comment]
The origin needs to match a tile grid corner. Did you verify that this is the case?

**Comment by tweedlebee** [comment]
I am a little unclear as to what you are asking.

The documentation says:

**origin** The tile grid origin, i.e. where the x and y axes meet ([z, 0, 0]).

Doesn’t this mean that the origin is the coordinate at which the _map’s_ x and y axis meet the tile’s [z, 0, 0]?

If so, whatever I set the origin to, defines where the top left grid corner will appear. In other words, it matches by definition. No?

**Comment by ahocevar** [comment]
> Doesn’t this mean that the origin is the coordinate at which the map’s x and y axis meet the tile’s [z, 0, 0]?

No. It is the projected coordinate at the top left corner of the tile with x=0 and y=0. The x and y axes in the documentation refer to the tile grid, not the map.

You cannot set arbitrary values here. Those need to match the tile grid layout that the server provides.

**Comment by tweedlebee** [comment]
So, this is what you are saying?

**origin** The tile grid origin, i.e. where the x and y axes of the tile grid meet the tile addressed by ([z, 0, 0]).
