### ISSUE TITLE
Blurred feature styles after rotation

### ISSUE THREAD

**Issue by aalbericio** [openlayers/openlayers#9521]
Hello all,

Obs: I only use Image/bitmap based layers and styles. 

When I rotate the Map, all my feature styles are rotated as well. This is expected since I have disabled live rotation.

Anyway, once the rotation is finished, the rotated features/styles seem a bit blurred. I can only get back to normal/crisp representation when rotation is set back to 0.

I have tried to call render(), etc map functions but blur is still there. 

Is there any map/view method I can call to get rid off these blur?

Thanks in advance.

**Comment by jahow** [comment]
Hi,

Could you please specify the version you are using and ideally a minimum reproduction sandbox? Thanks

**Comment by fredj** [comment]
ping @aalbericio
