### ISSUE TITLE
upgrade 3.x to 5.x

### ISSUE THREAD

**Issue by itisAliRH** [openlayers/openlayers#9527]
how can i upgrade from v3.16 to v5.x?
Is there a relevant explanation or migration plan?

**Comment by ThomasG77** [comment]
Just follow the releases notes at https://github.com/openlayers/openlayers/releases
You will need they contains "Upgrade notes" section. You will need to follow each upgrade instructions to be sure to apply all changes until reaching 5.x release notes.
