### ISSUE TITLE
Documentation for VectorTileLayer has duplicate options

### ISSUE THREAD

**Issue by Aords** [openlayers/openlayers#9535]
**Describe the bug**
[VectorTileLayer](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorTile-VectorTileLayer.html) has the options renderOrder and style show up twice in the options list.

**To Reproduce**
1. Go to [VectorTileLayer](https://openlayers.org/en/latest/apidoc/module-ol_layer_VectorTile-VectorTileLayer.html).
2. Scroll down to the options section.
3. See that renderOrder and style show up twice in the options list.

**Expected behavior**
Options should not be duplicated.

**Comment by tschaub** [comment]
Thanks for the report.  This was addressed in https://github.com/openlayers/openlayers/commit/e73931a9b25097451685a75308271a20c051d195, and the duplicate property is no longer in the documentation.
