### ISSUE TITLE
Make build setup ready for webworkers

### ISSUE THREAD

**Issue by fgravin** [openlayers/openlayers#9547]
**Is your feature request related to a problem? Please describe.**
Main thread is often too busy on rendering tasks, specially for vector rendering.

**Describe the solution you'd like**
It should be great to introduce webworkers to lighten main thread processing during heavy rendering tasks.
We would like to use a first webworker in the WebGL point renderer, that would be responsible of the creation of the buffers from the rendering instructions.

Introducing webworkers in openlayers build system can be quite challenging, we should list here the requirements and the implementation suggestions:
- webworkers should be loaded in serve-examples mode
- webworkers should be part of the build-package output
- it should be transparent for a third application that use openlayers code that depends on a worker (no specific action on the build system of the application)
- webworkers could make the build grow consequently, we need to optimize them so they don't fetch too much dependencies
- we should put all workers in one file so we load dependencies only once
- rollup looks like a good options to build and provide the worker
- shall we add a preapre-worker phase task during build system ?

**Comment by ahocevar** [comment]
@tschaub I think you had some ideas on how our build system could be modified to accommodate for workers. Can you please share these ideas here?

**Comment by fgravin** [comment]
An original work has been started in this old RP https://github.com/openlayers/openlayers/pull/8942/files and will be a base for our current work.

The idea is:

- For the build-package task
1. Run the package build
2. Add a webpack build that build the worker in `build/worker/worker.min.js`
3. Add a `prepare-worker` node task that will create a new js file that will contain an export of the blob content of the `worker.min.js` file.
```js
export default "blob of worker.min.js"
```
4. Replace `worker.js` by this new file in the `build/package` folder so the webworker can be used from a third party application. 
The `import Worker from './worker/worker.js'` will point on the blob of the worker.

- For the examples: use webpack `worker-loader`
https://github.com/webpack-contrib/worker-loader
It will end up with a `import Worker from './worker/worker.js`, Webpack will use its worker-loader to make it work in the serve-examples task.

- For the legacy-build, webpack-loader with `inline: true` should make the trick

**Comment by tschaub** [comment]
I put my ideas into #9550.

**Comment by fgravin** [comment]
Thanks @tschaub ! The implementation is great, i like the build task with rollup doing all the stuff at once.
I think we can move forward with your PR.
