### ISSUE TITLE
Cannot display my kml string

### ISSUE THREAD

**Issue by alexlionnel** [openlayers/openlayers#9554]
**Describe the bug**
I tried to import this kml data.
Openlayers can read features but these are not visible on the map.

`<?xml version="1.0" encoding="utf-8" ?>
<kml xmlns="http://www.opengis.net/kml/2.2">
	<Document id="root_doc">
		<Folder>
			<name>multiline</name>
			<Placemark>
				<styleUrl>#LineStyle00</styleUrl>
				<MultiGeometry>
					<LineString>
						<coordinates>7.77831300120992,45.1829836522005 8.40710690615978,46.5742520560659 9.39733352812806,46.7029815169218 9.81322870935474,46.2573795370361</coordinates>
					</LineString>
					<LineString>
						<coordinates>7.83772659852802,44.8809645325002 8.34769330884168,45.0790098568938 8.52593410079597,46.2969886019148 9.39733352812806,46.3613533323428 9.88749570600236,45.9256536186767</coordinates>
					</LineString>
				</MultiGeometry>
			</Placemark>
			<Placemark>
				<styleUrl>#LineStyle00</styleUrl>
				<MultiGeometry>
					<LineString>
						<coordinates>8.14469685133819,44.6086522114589 8.72893055829947,44.7571862047541 8.81805095427662,45.9702138166653 8.53583636701566,45.0839609900037 7.81297093297881,45.0493030582348</coordinates>
					</LineString>
					<LineString>
						<coordinates>9.24137283516806,46.2251971718221 9.27603076693695,45.6162077993116 9.5334896886487,45.5964032668723 9.53844082175854,45.8885201203529 9.75133954548172,45.5617453351034</coordinates>
					</LineString>
				</MultiGeometry>
			</Placemark>
		</Folder>
		<Style id="LineStyle00">
			<LabelStyle>
				<color>00000000</color>
				<scale>0.000000</scale>
			</LabelStyle>
			<LineStyle>
				<color>ff0000ff</color>
			</LineStyle>
			<PolyStyle>
				<color>00000000</color>
				<outline>0</outline>
			</PolyStyle>
		</Style>
</Document></kml>`

// JS
var map = new ol.Map({
                target: 'mapOL',
                layers: [],
                view: new ol.View({
                    center: ol.proj.transform([long, lat], 'EPSG:4326', 'EPSG:3857'),
                    zoom: 4
                }),
                controls: ol.control.defaults().extend(controls)
            });

// osm layer
var osmLayer = new ol.layer.Tile({
                source: new ol.source.OSM({
                    wrapX: false
                })
            });

map.addLayer(osmLayer);

// vector layer
var olLayer = new ol.layer.Vector({
                source: new ol.source.Vector({
                    wrapX: false
                })
            });

map.addLayer(olLayer);

var features = new ol.format.KML().readFeatures(kmlString ,{
                    dataProjection: "EPSG:4326",
                    featureProjection: "EPSG:3857"
                });
// console.log(features) ==> 2 features

olLayer.getSource().addFeatures(_features);

**Comment by fredj** [comment]
I suspect there's something wrong with the style defined in the kml: `<scale>0.000000</scale>` looks vers suspicious

**Comment by fredj** [comment]
It works if `<outline>0</outline>` is removed from the style
