### ISSUE TITLE
Mousewheel zooming different to trackpad zooming

### ISSUE THREAD

**Issue by dbrnz** [openlayers/openlayers#9564]
Each "click" of a mousewheel zooms be a factor of 2 yet zooming with a trackpad is smooth. This is despite `interaction/MouseWheelZoom.js` being used for both input devices. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a map.
2. Zoom using a mousewheel.
3. On the same system, zoom using a trackpad and compare the behaviour.

**Expected behaviour**
Mousewheel and trackpad zooming to be similar.

**Comment by jahow** [comment]
Hi,

I'm not sure I understood exactly what was the issue with mouse wheel zoom. Each mouse wheel tick will typically increase or decrease the zoom level by 1, while trackpads sent much finer events and will affect the zoom level proportionally of the user gesture.

Could you please specify the browser and device(s) you are using? thanks

**Comment by dbrnz** [comment]
Hmm, increasing/decreasing the zoom level by 1 for each mouse wheel tick causes very sudden and jerky zooming. Zooming on Google Maps is similar whether or not a mouse wheel or touchpad is used whereas the two are vastly different on an OpenLayers' map. PR #9565 makes the two comparable.

I've been testing on a MacBook Pro with a Microsoft mouse, using both Firefox and Chrome. The user who brought this issue to my attention runs Windows 10 on a desktop machine without a touchpad -- they complained about the rapid zooming with no fine control.

**Comment by icholy** [comment]
Related to #8183
