### ISSUE TITLE
convertToFunction method in Style.js returns different output when called with ol.js than with ol-debug.js

### ISSUE THREAD

**Issue by lahoneha** [openlayers/openlayers#9567]
**For setStyle method of feature.js, I get assertion error 41**
The code works fine with main project but when used in other dependent projects, it gives assertion error because object being passed is not an instance of Style when debugged through ol.js. But when I include ol-debug.js instead of ol.js it runs just fine.

My question is that is it a shortcoming of 'instanceof' or ol.js or my code. Since my code works all fine with ol-debug.js and I can not use this file in production what is the approach that I should follow?

`
/**
 * Convert the provided object into a style function.  Functions passed through
 * unchanged.  Arrays of ol.style.Style or single style objects wrapped in a
 * new style function.
 * @param {ol.StyleFunction|Array.<ol.style.Style>|ol.style.Style} obj
 *     A style function, a single style, or an array of styles.
 * @return {ol.StyleFunction} A style function.
 */
ol.style.Style.createFunction = function(obj) {
  var styleFunction;

  if (typeof obj === 'function') {
    styleFunction = obj;
  } else {
    /**
     * @type {Array.<ol.style.Style>}
     */
    var styles;
    if (Array.isArray(obj)) {
      styles = obj;
    } else {
**//This part throws assertion error 41**
      ol.asserts.assert(**obj instanceof ol.style.Style**,
          41); // Expected an `ol.style.Style` or an array of `ol.style.Style`
      styles = [obj];
    }
    styleFunction = function() {
      return styles;
    };
  }
  return styleFunction;
};`

Note **I am using an old version of ol.js**
**To Reproduce**
Not possible.

**Expected behavior**
Consistent behavior across projects with ol.js.

**Comment by qwrwt** [comment]
![OpenLayers](https://user-images.githubusercontent.com/6910694/58132343-a906cb00-7be6-11e9-8bec-53728385633b.PNG)

**Comment by qwrwt** [comment]
My question is why is the last query returning false when Ck is ol.style.Style class.
