### ISSUE TITLE
Is there a way to have a single javascript file with all the openlayers api

### ISSUE THREAD

**Issue by cmortazavi** [openlayers/openlayers#9580]
We have a windows form application which uses an openlayers map in a webbrowser control.  When openlayers was in version 4.x this was very simple to use because we just took the master openlayers js file and the master openlayers css file and added it to the windows form application and then we were able to use the api.  Is there any way we could do somethig similiar to this by using openlayers 5.x?  Even if you don't provide a master javascript/css file, is there anyway we can generate one?

**Comment by ThomasG77** [comment]
See https://github.com/openlayers/openlayers/issues/9391 (already an answer more or less to the same issue)

**Comment by mike-000** [comment]
Single minified builds and css are still available for situations where other options are impractical, see https://openlayers.org/en/master/doc/quickstart.html  I use downloaded copies of the js and css to run offline maps from an SD card.
