### ISSUE TITLE
Cannot get attribution of BingMaps source: Uncaught TypeError: Cannot read property 'viewState' of undefined

### ISSUE THREAD

**Issue by geomC** [openlayers/openlayers#9583]
**Describe the bug**
I have an initialized map with a background layer `myLayer` whoose source is an instance of `ol/source/BingMaps~BingMaps`. 
If I call `myLayer.getSource().getAttributions()` and call the function this expression returns, a `TypError` is thrown in [this line](https://github.com/openlayers/openlayers/blob/master/src/ol/source/BingMaps.js#L270)
```
ol-debug.js:54344 Uncaught TypeError: Cannot read property 'viewState' of undefined
```

**To Reproduce**
1. Get a bing maps API key
2. Host the following snippet, make sure `{your-api-key}` is replaced with the actual key
3. inspect the error in the console
```html
<!DOCTYPE html>
<html>
<head>
    <title>Bing Maps</title>
    <link rel="stylesheet" href="https://openlayers.org/en/v5.3.0/css/ol.css" type="text/css">
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>

</head>
<body>
<div id="map" class="map"></div>
<script>
    var bingSource = new ol.source.BingMaps({
        key: '{your-api-key}',
        imagerySet: 'AerialWithLabels'
    });
    var bingLayer = new ol.layer.Tile({
        source: bingSource
    });
    var map = new ol.Map({
        layers: [bingLayer],
        target: 'map',
        view: new ol.View({
            center: [-6655.5402445057125, 6709968.258934638],
            zoom: 13
        })
    });
    bingSource.on('tileloadend', provokeError);

    function provokeError() {
        var dynamicAttributionFunction = bingLayer.getSource().getAttributions();
        console.log(dynamicAttributionFunction()); // throws
    }
</script>
</body>
</html>

```

**Expected behavior**
The function call returns an attribution that can be used in another logic.

**Related Issues**
https://github.com/openlayers/openlayers/issues/7987
https://github.com/openlayers/ol-cesium/issues/607#issue-341055283

**Background**
Our companies app uses [mapfish](http://mapfish.github.io/mapfish-print/) and [GeoExt](https://geoext.github.io/geoext3/v3.1.0/docs/#!/api/GeoExt.data.MapfishPrintProvider) to print currently visible layers. The prints need correct attributions.

**Comment by mike-000** [comment]
The function must be called with the framestate, for example:

    map.on('moveend', provokeNoError);

    function provokeNoError(evt) {
        var dynamicAttributionFunction = bingLayer.getSource().getAttributions();
        console.log(dynamicAttributionFunction(evt.frameState));
    }

**Comment by geomC** [comment]
Thanks so far. Any idea how to achieve this if the logic that calls the attribution function is not within a callback registered to `map.on('someEvent')`?

The printing logic holds a reference to the map and iterates over the layers and it is called by a user interaction that does not target the map.

**Comment by geomC** [comment]
I tool another way to get hold on the attributions:
```javascript
myMap.
getControls().getArray()
.find(control => control instanceof ol.control.Attribution)
.renderedAttributions_ // evaluates to an array of strings
```
Closing this.
