### ISSUE TITLE
setOpacity doesn't work on ol/layer/Group

### ISSUE THREAD

**Issue by pakb** [openlayers/openlayers#9587]
**Describe the bug**
I have a couple layers displayed on my map, most react well to `setOpacity` and I have a reluctant one that doesn't change its transparency when `setOpacity` is applied

**To Reproduce**
https://s.geo.admin.ch/820917c58e and try to change opacity on both visible layers, the one with buildings and dwellings doesn't work when the other does (same code and same layer type `ol/layer/Tile`)

That's something new with OL6 betas as it's working fine on 5.3 (see https://s.geo.admin.ch/82092c7fd6)
I don't really know where to look for clues, we are using `setOpacity()` to set this property in our code.
layer creation here https://github.com/geoadmin/mf-geoadmin3/blob/845b8d131b909fa34116504c9cfcf2387303724b/src/components/map/LayersService.js#L540-L549
opacity set here https://github.com/geoadmin/mf-geoadmin3/blob/845b8d131b909fa34116504c9cfcf2387303724b/src/components/map/DefinePropertiesForLayerService.js#L50-L57

**Expected behavior**
Same behaviour when changing opacity.

**Comment by pakb** [comment]
Good thing opening issue is that people start to get interested, I had a talk with some colleagues and I'm not 100% sure we are not the one to blame here.
It seems to be related to one way we build layer called aggregate. It's a WMTS layer to a certain zoom level and then it switches to a WMS for latest up to date data.
I'll look into our code if we aren't by any chance using some kind of direct mutator (`layer.opacity = ...` instead of `layer.setOpacity(...)`) or other issues for this specific use case (there might me some `ol/layer/Group` involved)

**Comment by fredj** [comment]
yes, the opacity if broken with the Layer Groups, patch to come
