### ISSUE TITLE
[question] Mapbox layer example, feature under mouse cursor

### ISSUE THREAD

**Issue by pakb** [openlayers/openlayers#9593]
I'm trying to add `forEachFeatureAtCoordinate` capabilities to the mapbox `ol/layer/Layer` described in the [example](https://openlayers.org/en/master/examples/mapbox-layer.html) so that the integration with OL could be seamless between layers (instead of doing it via a local variable that I have to handle differently than calling `map. getFeaturesAtPixel(...)`)

I've seen that `render` is overwritten by a constructor param, is it possible to overwrite any arbitrary function or is it limited to a few chosen ones?

**Comment by jahow** [comment]
Using `render` in the layer constructor is an adhoc API introduced in #9525 so no, you cannot freely overwrite other methods.

I guess it would make sense to have another API for querying features such as `getFeaturesAtCoordinate`. It was also considered to add support for a general `getFeatures` custom callback, this could be used for querying features both for rendering and for picking (the argument could be a bounding box in both cases). @ahocevar food for thought!

Thanks @pakb

**Comment by ahocevar** [comment]
@jahow The idea was that layers implement

    getFeatures(Pixel): Promise<Array<Feature>>

and

    hit(Pixel): boolean

The former for getting features at a location, and the latter just returning whether there is something to query at a specific location. I don't think it makes sense to have a bounding box as argument.

**Comment by pakb** [comment]
That could be a great addition.
I agree with you @ahocevar , usually you want to know what's under the mouse cursor, so something expressed in pixel coordinate seems more appropriate for this use case.
But then if you take one use case we have with our app, we allow users to select a bounding box on the map, and return all feature infos that are inside it (via a request on a backend). It could be useful to be able to query with an extent if we went full vector tiles and wanted to have metadata imbedded inside the PBF features.

**Comment by jahow** [comment]
> The former for getting features at a location, and the latter just returning whether there is something to query at a specific location. I don't think it makes sense to have a bounding box as argument.

Well there can be a hit tolerance radius, but it's true that querying features for rendering and for picking will probably have different implementations anyway.

**Comment by ahocevar** [comment]
@pakb: 

> we allow users to select a bounding box on the map, and return all feature infos that are inside it (via a request on a backend)

With an `ol/source/Vector`, you can do that without a server request (assuming you have all features loaded).

> It could be useful to be able to query with an extent if we went full vector tiles and wanted to have metadata imbedded inside the PBF features.

Not sure what you mean here exactly, but getting that metadata through a server request to a feature service would be the way to go here. Remember: vector tiles are for rendering, not for querying data.
