### ISSUE TITLE
Problem with SVG icon color

### ISSUE THREAD

**Issue by d0bz** [openlayers/openlayers#9597]
Found problem when using fill parameter to change SVG path color in HEX then on map this icon is not visible at all. RGB and plain text are working

Demo:
https://jsfiddle.net/1hL4p5f3/

**Comment by fredj** [comment]
The problem is that the `#` characters are not allowed in data URIs, see:
https://www.chromestatus.com/features/5656049583390720

**Comment by ThomasG77** [comment]
Replace `#` with `%23` to solve the issue within OpenLayers. From my test https://jsfiddle.net/1ypef4m2/, it works within OpenLayers but breaks the SVG demo outside Openlayers.

**Comment by d0bz** [comment]
Will close issue as this is not Openlayers problem.
You can find work-around from @ThomasG77 comment.
