### ISSUE TITLE
Missing events in API documentation for View

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9607]
**Describe the bug**
`change:center` `change:resolution` and `change:rotation` are no longer listed in the master documentation https://openlayers.org/en/master/apidoc/module-ol_View-View.html As they are still working and it's inconsistent with similar change events in https://openlayers.org/en/master/apidoc/module-ol_Map-Map.html it's presumably unintended and maybe related to https://github.com/openlayers/openlayers/issues/9471.  Also "An View" is a grammar error.

**Comment by feyzullahyildiz** [comment]
same here https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html `drawstart` `drawend` are not at the doc

**Comment by mike-000** [comment]
> same here https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html `drawstart` `drawend` are not at the doc

That was covered by #9471 and has been fixed in OpenLayers 6.  The View documentation is a different issue, it was complete in OpenLayers 5 but some events are missing OpenLayers 6.

**Comment by ahocevar** [comment]
See #9773 for my findings on this issue. Unfortunately I was not able to fix it.
