### ISSUE TITLE
Support usage without a Bundler

### ISSUE THREAD

**Issue by mogoh** [openlayers/openlayers#9609]
I JavaScript bundler like Parcel is recommended by the documentation. In fact not using a bundler leads to some errors.

While using a bundler has many advantages, sometimes it is useful to not having to use a bundler.

* Configuring a bundler add an additional layer.
* A bundler needs to be installed and configured. A bundler can has it own errors.
* Bundled JavaScript is more complicated to debug if everything gets wrapped in a IIFE.
* While bundling files for production, in development, the opposite can be true. Recompling after every change of a file can slow down development.

Over all, having the option to not use a bundler would be nice. A documentation for that would be great.

I guess this takes minimal code changes. If I am not mistaken, ol should not use "bare" imports like 
`import { easeOut } from './easing';` but `import { easeOut } from './easing.js';`. But I do not really know what there is to do to achieve that.

**Comment by ThomasG77** [comment]
> Over all, having the option to not use a bundler would be nice.
If you want the option with `import` syntax and without bundler, not ready yet (at least for production). This answer is for overall JavaScript ecosystem and not particular to OpenLayers.

I've wrote an answer about various ways to use OpenLayers (with bundlers, jspm and standalone) https://stackoverflow.com/questions/51093964/why-examples-dont-work-a-struggle-with-imports/51110511#51110511

**Comment by tschaub** [comment]
@mogoh, for what it’s worth, the library already uses proper relative paths in our import specifiers (explicit, not implied file extensions; no “directory” imports with implied index files).  So, the library is ready for unbundled use, but as @ThomsaG77 points out, the same is not true of browsers and the JS modules ecosystem.

The library has dependencies that are not all published with the same rules we follow (proper relative paths).  Even if this were the case, bundling and minification is [still recommended](https://developers.google.com/web/fundamentals/primers/modules#bundle).

> Our general recommendation is to continue using bundlers before deploying modules to production. In a way, bundling is a similar optimization to minifying your code: it results in a performance benefit, because you end up shipping less code. Bundling has the same effect! Keep bundling.

While it adds extra overhead to the development process, getting comfortable using a bundler has benefits.

**Comment by mogoh** [comment]
Thank you for your help. I am not that experienced this JavaScript so bear with me, if I say something stupid.

> @mogoh, for what it’s worth, the library already uses proper relative paths in our import specifiers (explicit, not implied file extensions; no “directory” imports with implied index files).

@tschaub 
[Isn't this a counter example?](https://github.com/openlayers/openlayers/blob/6675f9be575ff52f6e051619f8273bc65752795c/src/ol/format/MVT.js#L7)

There are some others [examples](https://github.com/openlayers/openlayers/blob/6675f9be575ff52f6e051619f8273bc65752795c/src/ol/View.js#L24) and I think this is one reason, why it is not working that way.

> So, the library is ready for unbundled use, but as @ThomasG77 points out, the same is not true of browsers and the JS modules ecosystem.

Well, for me for now it is sufficient if my development browser supports it. The generall JS ecosystem on the other hand is of course a different problem.

> The library has dependencies that are not all published with the same rules we follow (proper relative paths).

rbush is an example, that, if I am not mistaken, just fixed that problem with version 3.0.0. rbush 3.0.0 is used now at the openlayers master branch. So there is no problem here (if again I am not mistaken). So, is there any other external library missing?

> Even if this were the case, bundling and minification is [still recommended](https://developers.google.com/web/fundamentals/primers/modules#bundle).
> 
> > Our general recommendation is to continue using bundlers before deploying modules to production. In a way, bundling is a similar optimization to minifying your code: it results in a performance benefit, because you end up shipping less code. Bundling has the same effect! Keep bundling.
> 
> While it adds extra overhead to the development process, getting comfortable using a bundler has benefits.

Yes, I will still use a bundler if my code is ready for production. The reason I am so unhappy with bundling is, that it makes debugging a bit more complicated. If my code runs unbundled than I am sure, it should run bundled or else bundling went wrong.

I know that bundling has been obligatory for years now and you JS developers are very familiar with it. I just think that we are (almost) at a point where bundling is not 
necessary and if we just go this extra step, we can have some extra benefits.

**Comment by tschaub** [comment]
> [Isn't this a counter example?](https://github.com/openlayers/openlayers/blob/6675f9be575ff52f6e051619f8273bc65752795c/src/ol/format/MVT.js#L7)
> 
> There are some others [examples](https://github.com/openlayers/openlayers/blob/6675f9be575ff52f6e051619f8273bc65752795c/src/ol/View.js#L24) and I think this is one reason, why it is not working that way.

Yes indeed.  We started out trying to be consistent, but as you point out, there is now lots of inconsistency.  I put together #9615 to bring consistency and a linter rule that errors if we don't include the file extension.

However, "bare" import specifiers still don't work "out of the box" in browsers.  So you cannot do this for example:

```js
import PBF from 'pbf';
```

And that is how we import 3rd party dependencies [in the library](https://github.com/openlayers/openlayers/blob/6675f9be575ff52f6e051619f8273bc65752795c/src/ol/format/MVT.js#L7).

**Comment by mogoh** [comment]
Very well, thank you so far. So if I understand this correct, than OpenLayers has done so far everything it could. Next step would be fixing OLs dependecies. Those are already using the new es module standard:

- [x] rbush
- [x] quickselect
- [ ] pbf
- [ ] pixelworks
- [ ] ieee754
- [ ] resolve-protobuf-scheme
- [ ] protocol-buffers-schema

After those are fixed, OL could import them the new way. But that means also importing with the relative path which means those are needed to be installed all next to `ol` (so we can link them with a relative path). That is probably true anyway as they are all installed in a `node_modules`-folder but it sounds like bad practice.

Feel free to disagree, if I said something stupid.

If there is nothing left to do for OL (for now) we can close this issue as far as I am concerned.
