### ISSUE TITLE
The number of layers cannot exceed 5 in version 12.1.2 of the operating system in Iphone

### ISSUE THREAD

**Issue by RoronoaZoro325** [openlayers/openlayers#9611]
&nbsp;&nbsp;&nbsp;&nbsp;In version  12.1.2（16C101）  of the operating system in Iphone,if you place more than 5 layers(VectorImage) on the map,<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;chrome,Safari and apps on the phone will appear white screen.  <br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;But that won't happen on the iphone5 or the inpone XR.
<br/>&nbsp;&nbsp;&nbsp;&nbsp;And which i use is version 6.0.0-beta.3 .

**Comment by ahocevar** [comment]
This has been fixed already. See #9584.

**Comment by RoronoaZoro325** [comment]
Thanks a lot!
