### ISSUE TITLE
WebGLMap vector data support limitations

### ISSUE THREAD

**Issue by gamreddy** [openlayers/openlayers#9612]
OpenLayers v5.3.0 API documentation page says: "The WebGLMap uses WebGL for rendering map layers. This renderer has **_limited support for vector data_** and no support for vector tiles". Can someone explain what are the limitations for vector data support?

**Comment by ahocevar** [comment]
The WebGLMap renderer is gone. We now have a dedicated WebGL points renderer for special uses. See e.g. https://openlayers.org/en/master/examples/filter-points-webgl.html.

**Comment by gamreddy** [comment]
What about lines and polygons? Are they not supported?

**Comment by jahow** [comment]
For now lines and polygons can only be rendered using the default canvas renderer and standard style objects.

**Comment by gamreddy** [comment]
Is there a way to access webgl context so that we can draw custom graphics?
