### ISSUE TITLE
Problem with OSM Map OpenLayers 5 : the map won't show

### ISSUE THREAD

**Issue by Wejden22** [openlayers/openlayers#9616]
var map3 = new ol.Map({
          layers:  new ol.layer.Tile({
            source: new ol.source.OSM()
          }) ,
        target: 'map-id3',
        view: new ol.View({
          center:ol.proj.fromLonLat([10.74,34.77]),
          zoom:12
        }) 

      });

**Comment by mike-000** [comment]
`layers: `must be an array
