### ISSUE TITLE
Static image of type SVG is not shown

### ISSUE THREAD

**Issue by ianmcderp** [openlayers/openlayers#9617]
**Describe the bug**
Image Static layers of type SVG are not shown on map.

Based on [Static Image example](https://openlayers.org/en/latest/examples/static-image.html), I tried the same with an SVG image (see [StackOverflow](https://stackoverflow.com/questions/34416412/how-can-i-use-a-svg-image-as-layer-on-openlayers-3) from ~2 years ago). Unfortunately, the SVG image is not shown.

**To Reproduce**
1. Use ImageStatic layer with SVG as illustrated in [gist](https://gist.github.com/ianmcderp/c9443338becbdf4bad0d5065897523f1) or [Codepen](https://codepen.io/ianmcderp/pen/WBgddr).
2. Image is not shown on map.

**Expected behavior**
Similar to the PNG in the original example, I expect an SVG image to be shown as well.

**Comment by fredj** [comment]
The browser can't determine the size of the svg image: apparently it fallback to a 150x150 px file.
```js
const img = new Image();
img.onload = (event) => {
  console.log(event.target.width, event.target.height);
}
img.src = 'https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg';
```
A `imageSize` can be passed to `ol.source.ImageStatic` to force a size, can you try this?

**Comment by ianmcderp** [comment]
Based on the image's viewBox `viewBox="0 0 900 900"`, I added an `imageSize: [900, 900]` property to the `ImageStatic` object: see [Codepen](https://codepen.io/ianmcderp/pen/LoJMKM).

**Comment by fredj** [comment]
Looks like `imageSize` doesn't work as expected

**Comment by mike-000** [comment]
It seems `imageSize `has no effect but it will work with an `imageLoadFunction   `https://stackoverflow.com/questions/52547179/openlayers-use-svg-as-layers-cant-work-on-ie11

**Comment by fredj** [comment]
The bug appear if the ratio between the image extent and the image size is the same, for example:
 * extent `[0, 0, 900, 900]`, image size `[900, 900]`
 * extent `[0, 0, 900, 900]`, image size `[512, 512]`

It "works" if the image size is set to `[900, 899] `

**Comment by ianmcderp** [comment]
Thank you @fredj for your insight, I really appreciate it.

I would like to provide a fix for this, but I am new to the code. Do you happen to have an idea where things may be broken or where I could start looking, respectively?

**Comment by fredj** [comment]
@ianmcderp you should start with the `handleImageChange` function:
https://github.com/openlayers/openlayers/blob/v6.0.0-beta.9/src/ol/source/ImageStatic.js#L112-L136

The `targetWidth != imageWidth` test is wrong if the ratio  between the image extent and the image size is the same
