### ISSUE TITLE
Translate interaction - event details missing info on purpose?

### ISSUE THREAD

**Issue by halybee** [openlayers/openlayers#9618]
Hi!

So I'm using the Translate interaction in my project. I'm listening to the `TRANSLATESTART` and `TRANSLATEEND` events. They both include the event's map coordinates in the details, but not the event's pixel, or the event itself. Was there a reason for this? (See 
https://github.com/openlayers/openlayers/blob/master/src/ol/interaction/Translate.js#L168)

I'd love to have access to the pixel. I know there are many workarounds but I was curious. If you guys are open to it, I'll gladly do a pull request where the events contain more info.

**Comment by ahocevar** [comment]
Would you consider using`ol/Map`'s [getPixelFromCoordinate()](https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#getPixelFromCoordinate) API method a workaround?

**Comment by halybee** [comment]
yes it's not a problem! it's just a pity since we already have the information a few calls before, and to have to re-poke Openlayers for an additional call.

**Comment by halybee** [comment]
also, having the original event helps knowing if modifier keys were pressed (for example) if we want to have special behavior

**Comment by ahocevar** [comment]
I see. Would you be able to create a pull request that adds an `originalEvent` property with the underlying event?

**Comment by halybee** [comment]
yes! will do in a couple of weeks, I am currently abroad with no computer!
