### ISSUE TITLE
Polygon vertices with count label

### ISSUE THREAD

**Issue by digoburigo** [openlayers/openlayers#9619]
**Is your feature request related to a problem? Please describe.**
I want to make a style that takes the geometry vertices (edges) and put a counter label on each vertice like 1, 2, 3 ... (like in the photo). I tried looking for a solution but i can't find any. Can someone help me to find a solution

![labal example](https://user-images.githubusercontent.com/28462822/58600154-cd534f00-8259-11e9-8fd2-39f8c3ba3e36.png)

**Describe the solution you'd like**
Somewhere in the geometry function in the style be able to set a label or iterate over the features and add a text base on the lenght

**Comment by mike-000** [comment]
https://codesandbox.io/s/polygonstyles-ow5sy

**Comment by digoburigo** [comment]
Thanks, the solution its perfect. I almost got to a solution similar, but didn't workout like expected. Thanks again! @mike-000
