### ISSUE TITLE
Icons in mapbox-vector-tiles example broken

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#9628]
The icons in the [mapbox-vector-tiles.html](https://openlayers.org/en/master/examples/mapbox-vector-tiles.html) examples, which should appear at high zoom levels, are no longer drawn.

`git bisect` shows that 2e34dd0fafdc40a0bdd2023db55514083b1da87c is the first bad commit.

/cc @fredj

**Comment by fredj** [comment]
This issue only occurs on Safari and with svg images.

**Comment by ahocevar** [comment]
Which is what I used. Can you fix it?

**Comment by fredj** [comment]
I've filed a Safari bug report and I'll add a workaround in OpenLayers
