### ISSUE TITLE
Transform extent

### ISSUE THREAD

**Issue by AdrianKujawski** [openlayers/openlayers#9642]
**Describe the bug**
I noted incorrect transform extent from EPSG:2180 to EPSG:4326 by a `ol/proj.transformExtent`.

**To Reproduce**
I created a simple [project](https://codesandbox.io/s/charming-driscoll-ecmgk) show a problem.
There I'm tranforming extent from EPSG:2180 to EPSG:4326 and vice versa.
In index.js I've tried transform extent by `ol/proj.transformExtent`. With each next transformation, the problem increases.

1.  EPSG:2180 -> [144693.28, 137212.44,  876500.35,  908411.19]
2. to EPSG:4326 -> [13.31, 48.98, 25.02, 55.90]
3. to EPSG:2180 -> [84052.07, 140035.90, 940596.49, 910198.34]

In index2.js I used  `ol/proj.transform` to transform extent's coordinates and results looks better.

1.  EPSG:2180 -> [144693.28, 137212.44,  876500.35,  908411.19]
2. to EPSG:4326 -> [14.14, 48.99, 25.02, 55.89]
3. to EPSG:2180 -> [144693.28, 137212.44, 876500.35, 908411.19]

Is it a problem with openlayers, proj4 or projection's definiton?

**Comment by ahocevar** [comment]
This is expected and neither a problem with OpenLayers nor proj4. It's because lines that connect points at the same latitude or longitude are not parallel in the two projections.
