### ISSUE TITLE
Drag selection + getFeaturesInExtent incorrect output

### ISSUE THREAD

**Issue by aalbericio** [openlayers/openlayers#9647]
**Describe the bug**
When using DragBox, getFeaturesInExtent using the dragBox.getGeometry().getExtent() produces a wrong output.

Buggy scenarios:

1) When map is not rotated, it seems it works with the DragBox Extent EXPANDED TO THE LEFT.

2) When map is rotated, the wrong DragBox Extent is EXPANDED to match the rotation value.

**To Reproduce**

1. Go to: https://codesandbox.io/s/emptysourceperformance-95dzz

You will see 2 lineStrings displayed.

2. Create a DragBox (using CTRL) that intersects 1 line but does not intersect any other line towards its left. Console log will output only that single Feature. That is the expected output.

3. Now, create a DragBox that intersects 1 line but does ALSO intersects "virtually" another one towards its left. Console log will output 2 Features! Eventhough we were only intersecting 1.

See atached picture if my explanation is not clear enough.

This bug affects every single version from 5.3.1 -> 6.0.0-b9

**Expected behavior**
getFeaturesInExtent should only return a list of Features inside the DragBox Extent; in this case: 1

Obs:

1) This bug also hits (as explained) bug #5496 

2) Something is wrong in version 6.0.0-x which has a peformance issue when drawing only these 2 Lines

3) This bug only affects LineString features. 

![how_to_reproduce_error](https://user-images.githubusercontent.com/656391/58882901-aa9fbb00-86dd-11e9-9583-2019c4719114.png)

**Comment by fredj** [comment]
I think it's a [documentation]( https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html#getFeaturesInExtent) issue:

*Get all features in the provided extent.*
should be changed to
 *Get all features whose bounding box intersects the provided extent.*

**Comment by aalbericio** [comment]
> I think it's a [documentation](https://openlayers.org/en/latest/apidoc/module-ol_source_Vector-VectorSource.html#getFeaturesInExtent) issue:
> 
> _Get all features in the provided extent._
> should be changed to
> _Get all features whose bounding box intersects the provided extent._

I firmly believe it is a bug. That method is not returning the correct Array of Features

**Comment by fredj** [comment]
In your screenshot, the two features are returned and it's the expected behavior: both features extent are intersecting the extent of the drag box.

If you want to know if the geometry itself (and not the extent) intersect the extent of the drag box you can use the `intersectsExtent` of the geometry.

See this updated codesandbox: https://codesandbox.io/s/emptysourceperformance-mn92p

**Comment by mike-000** [comment]
```
var features = [];
vectorSource.forEachFeatureIntersectingExtent(currentExtent, function(feature){ features.push(feature); });
console.log(features);
```
would return the expected array and the difference between `forEachFeatureInExtent` and `forEachFeatureIntersectingExtent` seems clear enough in the documentation.

A `getFeaturesIntersectingExtent` method would be a nice to have for consistency with the other methods.

**Comment by aalbericio** [comment]
I think I'm missing something here.

Look at this screenshot:

![drag_box_hit](https://user-images.githubusercontent.com/656391/58932801-7243bf80-8765-11e9-82e8-281454a8e557.png)

The blue DragBox is only hitting 1 Line but console.log is telling me it's hitting 2 LineStrings (because it's using a modified/wrong-in-my-opinion Box, the red one).

This wrong (in my opinion) behaviour is only happening when using LineStrings. When using default point features it just works great. I mean, "getFeaturesInExtent" is only returning the features inside de blue box.

Am I missing something? I'm expecting this method to only return those LineString features who actually intersect the blue Box which, in this case, is 1.

Some people is also experiencing something similar in issues like: #5496

**Comment by mike-000** [comment]
Only one of the LineStrings' geometries passes through the drawn extent but both of their extents cover the drawn extent  LineStrings have extents as in the screenshot, but a point's extent is just the single point.  You are using the method for testing feature extents intersecting an extent instead of testing feature geometry intersecting an extent.
![image](https://user-images.githubusercontent.com/49240900/58941268-521afd00-8773-11e9-9942-1fecb100456a.png)

5496 is a different issue involving the true extent of a rotated box 
![image](https://user-images.githubusercontent.com/49240900/58943008-c6a36b00-8776-11e9-9161-3845ddc8a057.png)

**Comment by aalbericio** [comment]
I think I'm getting the point...

I was expecting that "**getFeaturesInExtent**" returned what Mike defined as "**getFeaturesIntersectingExtent**" and what I really get is what I'd name as "**getFeaturesIntersectingFeaturesExtents**", or something like that.

Okay, I'm going to refactor my code but I will sum my vote to add this new "**getFeaturesIntersectingExtent**" method in the API.

Anyway, and that's a totally different topic, the performance issue pointed out for these 2 lines exists in version 6b. I'm not sure if you want me to file it or not....

Thanks

**Comment by mike-000** [comment]
Yes, it would be nice to have it in the API but it's easy to add a definition to a project.

```
import VectorSource from "ol/source/Vector";

VectorSource.prototype.getFeaturesIntersectingExtent = function(extent) {
  var features = [];
  this.forEachFeatureIntersectingExtent(extent, function(feature){ features.push(feature); });
  return features;
}
```
