### ISSUE TITLE
Open Layers 'instanceof' replacement for 'getZIndex'. How is the replacement serving the same purpose

### ISSUE THREAD

**Issue by lahoneha** [openlayers/openlayers#9648]
In the new version of open layers 'instanceof' is replaced with getZIndex. How is it serving the same purpose as checking whether the style is a style object or not. From online forum, getZIndex tells us about the rendering order of the object. Please see the example below:

ol.asserts.assert(obj instanceof ol.style.Style,41); is replaced with 
ol.asserts.assert(typeof(obj).getZIndex === 'function',41);

**Comment by DaniEll-AT** [comment]
disclaimer: I'm just a random developer, commenting your "issue"

Checking Types in JavaScript is tricky (for example read [this](http://tobyho.com/2011/01/28/checking-types-in-javascript/))

What we see here, is a change in type-checking. The first line uses "instanceof", the second one is perfoming so-called ["Duck Typing"](https://stackoverflow.com/a/3379721/3994580)
> If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.

**Comment by lahoneha** [comment]
appreciated thank you!
