### ISSUE TITLE
Stop using v3 TileJSON from mapbox

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#9652]
They are all returning HTTP 401 errors, see for example: https://openlayers.org/en/master/examples/icon.html

**Comment by jahow** [comment]
Fixed by https://github.com/openlayers/openlayers/pull/9562/commits/e0367677469c30acaa6ac51cd27125d4fb2cc907

**Comment by jahow** [comment]
Sorry, my bad, this commit only fixed one example
