### ISSUE TITLE
Handle rotation in the Box Selection example

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9656]
**Describe the bug**
The stale bot has closed the very old issue #5496 but it would be nice ti have an example which handled rotation in a way most might expect it to.

**To Reproduce**
See #5496

**Expected behavior**
https://codesandbox.io/s/boxselection-5cc8v

**Comment by fredj** [comment]
Thanks for the codesandbox @mike-000, I've opened a pull request based on your code.

**Comment by mike-000** [comment]
The PR in its present form won't fix the issue.  My codesandbox was also inefficient in that it compared every feature in the source against the rotated dragbox instead of only those in its extent when rotated.  Although there is slightly more code this https://codesandbox.io/s/box-selection-krl5z will be more efficient.  The ol/geom/Geometry API change to make the anchor optional is correct but in this case the coordinate used for the box is also required and cannot be defaulted when making a corresponding rotation of feature geometry.  @fredj if you wish to merge the API change I am willing continue a PR for the example.
