### ISSUE TITLE
Canvas size not set on first render of map.

### ISSUE THREAD

**Issue by finite2** [openlayers/openlayers#9664]
**Describe the bug**
Openlayers canvas does not always set its canvas size correctly from its targetElement.

In a react environment the targetElement has offsetWidth and offsetHeight set to zero despite this not being correct.

This appears to be some sort of race condition since a window resize, map.updateSize in a timeout function or in reacts componentDidUpdate method with set the canvas size correctly. It was also fixed if the dom order was changed such that the map was rendered prior to some other expensive js code.

**Expected behavior**
The canvas fills the div on first render (which happens to be width: 100vw, height 100vh).

**Solution**
the updateSize method in src/ol/PluggableMap.js already has a call to getComputedStyle with returns the correct width and height for this targetElement (even though the values for targetElement are wrong) thus we can simply replace targetElement.offsetWidth with parseFloat(computedStyle["width"]) and targetElement.offsetHeight with parseFloat(computedStyle["height"]) 

```
updateSize() {
    const targetElement = this.getTargetElement();

    if (!targetElement) {
      this.setSize(undefined);
    } else {
      const computedStyle = getComputedStyle(targetElement);
      this.setSize([
            parseFloat(computedStyle["width"]) -
            parseFloat(computedStyle['borderLeftWidth']) -
            parseFloat(computedStyle['paddingLeft']) -
            parseFloat(computedStyle['paddingRight']) -
            parseFloat(computedStyle['borderRightWidth']),
            parseFloat(computedStyle["height"]) -
            parseFloat(computedStyle['borderTopWidth']) -
            parseFloat(computedStyle['paddingTop']) -
            parseFloat(computedStyle['paddingBottom']) -
            parseFloat(computedStyle['borderBottomWidth'])
      ]);
    }
  }
```

**Comment by tschaub** [comment]
Are you able to put together an example that demonstrates the problem?
