### ISSUE TITLE
Examples only available for Webpack

### ISSUE THREAD

**Issue by Snickbrack** [openlayers/openlayers#9666]
**Is your feature request related to a problem? Please describe.**
I am not using Webpack in my project and I can't seem to get the source files without Webpack.
Why?

**Describe the solution you'd like**
Provide source files without forcing users to use Webpack.

**Comment by mrpan** [comment]
i think you need to learn it

**Comment by Snickbrack** [comment]
Okay, that wouldn't be a big problem if I could get Webpack to work in ASP.NET...

Why aren't any full files deployed?

**Comment by DavidHequet** [comment]
Hi, 
I'm also using OL in old application without webpack. There is no problem.
Full builded lib is available here https://openlayers.org/download/ (V5.3.0-dist.zip)

And exemple are simple to translate, js files use the right case

```
import Map from 'ol/Map.js' => replace "Map" with ol.Map
import View from 'ol/View.js' => replace "View" with ol.View
import TileLayer from 'ol/layer/Tile.js => replace TileLayer with ol.layer.Tile';
import OSM from 'ol/source/OSM.js' => replace OSM with ol.source.OSM
```
So the simple Map example become
```
      var map = new ol.Map({
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        target: 'map',
        view: new ol.View({
          center: [0, 0],
          zoom: 2
        })
      });
```
