### ISSUE TITLE
Missing release items for releases after 5.3.0

### ISSUE THREAD

**Issue by kalxas** [openlayers/openlayers#9667]
We recently tried to update OpenLayers in OSGeoLive and realized that the dist zip package is available up to 5.3.0 release.

Can you please provide provide the dist package for 5.3.3?

**Comment by kalxas** [comment]
https://github.com/OSGeo/OSGeoLive/blob/master/bin/install_openlayers.sh#L40

**Comment by mrpan** [comment]
see https://github.com/openlayers/openlayers/releases/tag/v5.3.3

**Comment by ahocevar** [comment]
We stopped providing distribution archives for bugfix releases. We encourage our users to use the [npm package](https://npmjs.com/package/ol). @kalxas, what is the dist archive used for on OSGeo Live?

**Comment by palmerj** [comment]
I find these really useful for playing around in sites like codepen. What are my options when using a site like this?

**Comment by ahocevar** [comment]
codesandbox.io is a similar site that works with npm packages. We use that also for the examples now. See https://openlayers.org/en/master/examples/

**Comment by palmerj** [comment]
OK thanks good to know
