### ISSUE TITLE
Problem on transformExtent with Y coordinates

### ISSUE THREAD

**Issue by qsivan** [openlayers/openlayers#9668]
I'm using ol 5.3.3 and trying to transform an extent from EPSG:4326 to EPSG:3857 but it results in a wrong result for Y coordinates while X coordinates are OK :

Ex : ol.proj.transformExtent(["2.224225", "48.815607", "2.469769", "48.902008"], "EPSG:4326", "EPSG:3857")

Result in [247599.59440966893, **-5039577.618739517**, 274933.42745701247, **-5026806.090671426**]

The correct result should be [247599.5944, 6243631.4800, 274933.4275, 6258250.5290]

**Comment by mike-000** [comment]
Extents (and coordinates) are defined as arrays of numbers.  Strings are likely to cause problems elsewhere, not just in transforms.  If you have obtained an array from, for example, splitting a string, a quick fix is

`ol.proj.transformExtent(["2.224225", "48.815607", "2.469769", "48.902008"].map(Number), "EPSG:4326", "EPSG:3857")`

**Comment by qsivan** [comment]
Thanks for your help, the transform is now correct with an array of numbers.
