### ISSUE TITLE
Mobile performance issue on simple full page map

### ISSUE THREAD

**Issue by onderaltintas** [openlayers/openlayers#9670]
Hello there,

I cannot express how much I love OpenLayers. I have a signed OpenLayers posters on my room walls and OpenLayers figurines on my desk. I even have "I (heart) OL" coffee mug.

**Describe the bug**
  Today, I want to mention a strange behaviour of OpenLayers on mobile environment. Without adding anything, just with simple base map, openlayers' map pan/zoom controls are working a bit clunky on mobile. I am using "Go Mobile!" tutorial on openlayers book for reference and for comparing I am using Leaflet example. I am aware of how functional is OpenLayers and Leaflet is lightweight and for simple tasks. On the other hand, both examples are constructed with just adding base map, so there shouldn't be this much difference.

**Openlayers Go Mobile Example Reference:**
https://openlayersbook.github.io/ch10-openlayers-goes-mobile/example-01.html
**Leaflet Example:**
http://bl.ocks.org/d3noob/raw/7654694/

**To Reproduce**
1. Open your mobile browser, open this issue page on your browser.
2. Go to: https://openlayersbook.github.io/openlayers_book_samples/chapter10/2360OS_10_01_mobile.html
3. Move/Zoom on map
4. Now go to: http://bl.ocks.org/d3noob/raw/7654694/
5. Move/Zoom on map

**Expected behavior**
Without adding anything, nearly same pan/zoom experience.

**Extra Details**
Mobile phone used: General Mobile GM 5 plus
Browser: 
1. Firefox: Movement/Pan problems
2. Chrome: Touch controls are also affecting mobile phone's own ui
Both browsers have recent versions or nearly recent.

**Comment by fredj** [comment]
The OpenLayers example from the openlayersbook uses a very old version of the library.
The example from the latest release is much better, see https://openlayers.org/en/latest/examples/mobile-full-screen.html

**Comment by marcjansen** [comment]
@onderaltintas did @fredj s hint help?

And also thank you for this super friendly issue. Much appreciated.

**Comment by onderaltintas** [comment]
It did helped but forgot to close this one. Thank you very much :)

**Comment by rgreenwood** [comment]
Where do we get OL figurines? I want!
