### ISSUE TITLE
WFS VectorSource: Potential infinite loop: exceeded 10001 iterations

### ISSUE THREAD

**Issue by palmerj** [openlayers/openlayers#9675]
**Describe the bug**
I get the following error when creating a WFS vector source:

```
Potential infinite loop: exceeded 10001 iterations
````

**To Reproduce**
1. Go to https://codesandbox.io/s/fervent-mayer-4p1dd

**Expected behavior**
Seems to be working ok on https://codepen.io/linzdemo/pen/NZPmQV?editors=1010. Maybe an issue with codesandbox?

Thanks

**Comment by palmerj** [comment]
Note I've tested this locally and it runs ok, so much to a problem with code running on codesandbox.io

**Comment by ahocevar** [comment]
This is due to a codesandbox config default. To turn the error off, create a `sandbox.config.json` in the root of the box‘s folder structure and set the `infiniteLoopProtection` option to `false`.

**Comment by palmerj** [comment]
OK thank you that worked. Issue closed
