### ISSUE TITLE
appendLinearRing doesn't update view

### ISSUE THREAD

**Issue by bucibucii** [openlayers/openlayers#9683]
https://codesandbox.io/s/static-dihnr

**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Comment by mike-000** [comment]
MultiPolygon is a single geometry object defined by multiple arrays of polygon coordinates.  It is **not** an array of Polygon geeometries, so the geometries returned by getPolygon() or getPolygons() are created on request from the coordinate arrays which is similar to clones and updating the Polygon geometry won't change the MultiPolygon:

```
  var g = featurePoly.getGeometry();
  var f = g.getPolygons();
  f[0].appendLinearRing(l);
  console.log(f[0].getLinearRings());
  var f = g.getPolygons();
  console.log(f[0].getLinearRings());
```

Instead you need to rebuild the MultiPolygon from the updated Polygons:

```
  var f = featurePoly.getGeometry().getPolygons();
  f[0].appendLinearRing(l);
  var m = new ol.geom.MultiPolygon([]);
  f.forEach(function(p){
    m.appendPolygon(p);
  });
  featurePoly.setGeometry(m);
```

The same applies if using getPoint() or getPoints() with MultiPoint and getLineString() or getLineStrings() with MultiLineString.
