### ISSUE TITLE
Selecting on a multi-icon WebGLMap causes incorrect icon draw and disappear

### ISSUE THREAD

**Issue by jellyedwards** [openlayers/openlayers#9688]
**Describe the bug**
If I setup a WebGLMap with a select interaction and many features (each of which has a different icon), a selection results in some icons disappearing and some others using the incorrect icon from a neighbouring feature.

**To Reproduce**
1. Go to [https://codesandbox.io/s/xg2zy](https://codesandbox.io/s/xg2zy)
2. You should see many icons, each with a randomized blue/green color.
3. If you click on one icon, e.g.:
![image](https://user-images.githubusercontent.com/14051992/59678907-7cce7200-91c5-11e9-8587-826a113bfbe8.png)
4. It turns red (expected as that's the select interaction style in this setup), however the icon below it seems to use the icon from the next icon down, and the icon in the top right disappears (top right of entire collection):
![image](https://user-images.githubusercontent.com/14051992/59679004-ae473d80-91c5-11e9-92e8-f653ad6b5df9.png)

**Expected behavior**
Only the selected icon should have any styling change.

This only happens with WebGLMap, and only if the icons differ in some way (e.g. color or icon source), here's what happens with WebGLMap + selection + the color of non-selected items is always blue:
![image](https://user-images.githubusercontent.com/14051992/59679281-4fce8f00-91c6-11e9-8822-07558cb0ca4b.png)

I realise this is perhaps quite a niche case so thanks for having a look!

**Comment by jahow** [comment]
Hi,

The WebGLMap class in OL 5.3 isn't supported anymore and has been removed as of OL 6 (beta). There is now a renderer dedicated to points rendering based on WebGL which may suit your needs, see for example: https://openlayers.org/en/master/examples/icon-sprite-webgl.html

Thanks!

**Comment by jellyedwards** [comment]
Thanks @jahow, I'll try that out!

Incidentally I thought I was using the latest (https://openlayers.org/en/latest/apidoc/module-ol_WebGLMap-WebGLMap.html and https://openlayers.org/en/latest/examples/symbol-atlas-webgl.html) but couldn't see where it says it's not supported, perhaps the documents need to be updated?
