### ISSUE TITLE
importing from the 'ol' package in node throws errors

### ISSUE THREAD

**Issue by kevinphelps** [openlayers/openlayers#9689]
**Describe the bug**
If you import from the 'ol' package in node, you get an error because `window` does not exist. I'm not trying to actually render a map in node, I'm just importing from `ol/*` in an Angular app that is server rendered.

**Expected behavior**
The issue is caused by this line: https://github.com/openlayers/openlayers/blob/master/src/ol/has.js#L40 (`master` is currently 51c8886d60a9f239d6b6372707641a93c9aa58fb)

Changing

```typescript
export const DEVICE_PIXEL_RATIO = window.devicePixelRatio || 1;
```

to 

```typescript
export const DEVICE_PIXEL_RATIO = typeof window !== 'undefined' && window.devicePixelRatio || 1;
```

will make it not throw when simply importing the module.

I would be happy to open a PR for this.

**Comment by heart-of-code** [comment]
There are several other packages with references to window and document. 

I'm not sure what kind of server-rendering framework you're using, but I was able to circumvent the problem using a null-loader for server-side builds and checking if the packages were defined before using them
