### ISSUE TITLE
Strange behavior with style function

### ISSUE THREAD

**Issue by DavidHequet** [openlayers/openlayers#9691]
**Describe the bug**
I encounter a strange bug on a vector layer styled by a function. You can see it in this gif
![2019-06-19_10h47_40](https://user-images.githubusercontent.com/3728916/59752824-35a6b680-9283-11e9-9b82-3461dbdbcb3d.gif)

I encounter  the same behavior on Chrome, firefox, IE11. But it work as expected on Edge (not the chromium based)

The datas ares hosted on github, feel free to analyse.

**To Reproduce**
1. Go to https://jsfiddle.net/davidhequet/vn1mdpqb/
2. zoom forward and backward
3. See error

**Comment by ahocevar** [comment]
This is an issue with your application. Some of your color strings are invalid, e.g. `'rgba(234, 124, 23, 1))'` instead of `'rgba(234, 124, 23, 1)'` (note the duplicate closing bracket).

Here is an updated codesandbox with the issue fixed: https://codesandbox.io/s/magical-clarke-436p5

**Comment by DavidHequet** [comment]
Oh sh*t i searched a lot and didn't see that!

Thank you!
