### ISSUE TITLE
Version 3.11.2 missing?  https://openlayers.org/en/v3.11.2/build/ol.js throws 404

### ISSUE THREAD

**Issue by sccoos** [openlayers/openlayers#9693]
**Describe the bug**
Our code pulls from https://openlayers.org/en/v3.11.2/build/ol.js and worked yesterday, but today we get a 404 error

**To Reproduce**
1. Go to 'https://openlayers.org/en/v3.11.2/build/ol.js'
2. See error

**Expected behavior**
js code should appear as seen at https://openlayers.org/en/v3.20.1/build/ol.js

**Comment by ahocevar** [comment]
Please download the dist archive of the version you want to use from https://github.com/openlayers/openlayers/releases/. The hosted builds should not be used in production, as they are subject to removal.

**Comment by sccoos** [comment]
Thanks for the quick reply.

Vicky Rowley
SCCOOS DMAC
(858) 246-2623
vrowley@ucsd.edu
http://sccoos.org
