### ISSUE TITLE
Canvas renderer might throw TypeError: Cannot read property 'forEachFeatureAtCoordinate' of undefined 

### ISSUE THREAD

**Issue by 172476032** [openlayers/openlayers#9707]
Describe the bug
If a Vector Tile Layer has a composite source (e.g. https://{a-d}.tiles.mapbox.com/v4/<source1>,<source2>/{z}/{x}/{y}.vector.pbf') and one of the sources is hidden at the given resolution/zoom level (e.g. polygons and their centroids), one might encounter a VectorTileLayer.js:318 Uncaught TypeError: Cannot read property 'forEachFeatureAtCoordinate' of undefined when trying to use map.forEachFeatureAtCoordinate. 
Expected behavior
https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/renderer/canvas/VectorTileLayer.js#L262 should be found = found || replayGroup && replayGroup.forEachFeatureAtCoordinate(coordinate, ...

![1](https://user-images.githubusercontent.com/21135209/59984039-63f80d80-9658-11e9-88f3-02f5760ef8a1.png)

**Comment by ahocevar** [comment]
Can you provide a minimal example (e.g. on codesandbox.io) that shows the issue so we can reproduce and debug it? I'd be curious find out why the replay group is undefined.

**Comment by 172476032** [comment]
Thank you for your reply.This is the url (https://codesandbox.io/s/github/172476032/olVectorTileLayerTest/tree/master/?fontsize=14) on codesandbox.io,and the url (https://github.com/172476032/olVectorTileLayerTest.git) on github.This project uses a GeoServer vector tile layer I posted on an external server,I don't know if you can debug this service layer abroad. Errors will occur when the map initialization level is lower than the map initialization level, and no errors will occur when the map initialization level is greater than the map initialization level.And，I also found another bug, which also causes errors when I click on the point feature（target.addEventListener is not a function），but，When I click about three times after, this error is no longer exist.，i can get the point feature information by clicking.The following screenshot：
![1](https://user-images.githubusercontent.com/21135209/60035337-2b4f4700-96df-11e9-8340-393da69e9e20.png)
![2](https://user-images.githubusercontent.com/21135209/60035338-2be7dd80-96df-11e9-9dc1-a8a6c9d9d155.png)
![3](https://user-images.githubusercontent.com/21135209/60035342-2db1a100-96df-11e9-95e8-723abbf0c71e.png)
![4](https://user-images.githubusercontent.com/21135209/60035343-2e4a3780-96df-11e9-8323-553c1bb93c54.png)

**Comment by ahocevar** [comment]
Thanks for providing additional context. Your suggested change makes sense. Would you be able to provide a pull request? Thanks!
