### ISSUE TITLE
Map interaction gets blocked by data loading or map rendering

### ISSUE THREAD

**Issue by jakubbican** [openlayers/openlayers#9708]
We have found a difference in map behavior whe ve upgraded OL from 4.6.5 to 5.3.0 in our project. The map interactions seem to get blocked by data loading and/or rendering so that some of the user actions get "consumed" without any action on the map.

See this video: https://1drv.ms/v/s!AqyEp6Py6-rzkdcuPdvh7v6J8n_UVQ

In the first 20 secs, the old OL version is used. You can see that every interaction results in map motion.

In the second half (especially at the end of the video approx from 36 sec), the data usually gets loaded immediatelly after the interaction and some of the user interactions are consumed with no map response.

**Comment by ahocevar** [comment]
You should improve this ticket by providing a live example that shows the issue. It is not really possible to draw any conclusions from the video.

**Comment by jakubbican** [comment]
We did a very deep investigation. Finally, we think that the issue is caused by our quite complex style function. We have to further analyze if we've just made it too complex during last few months or if there is some interferrence with new OL version.
