### ISSUE TITLE
VideoSource for use with ImageLayer

### ISSUE THREAD

**Issue by subdavis** [openlayers/openlayers#9713]
**Is your feature request related to a problem? Please describe.**

I'd like to (ab)use OpenLayers for video playback with layered geometry and pan/zoom controls.  I want something like [This mapboxgl demo](https://docs.mapbox.com/mapbox-gl-js/example/video-on-a-map/)

I've read through the related code, and the ImageLayer is clearly intended to support this, but falls short by not providing the mechanisms (like looping) and firing the `change()` event.

**Describe the solution you'd like**

I'd like to see 2 new modules: `ol/source/VideoStatic extends ImageSource` and `ol/Video extends BaseImage`.

## VideoStatic

Will look just like ImageStatic except with `this.video_ = VideoWrapper(...)` instead of `ImageWrapper`.

Again, I want OL to handle the nuance of re-rendering while the video plays.

I'm also concerned about `createCanvasContext2D(targetWidth, imageHeight)` in ImageStatic because `handleImageChange` will be called at 30-60Hz, totally unnecessary between frames.   

I could certainly hack it using the image rendering, but calling `setImage` right after initializing `Static` seems wonky, and the [solution here](http://tschaub.net/ol3-video/examples/video.js) is also kinda gross.  

I'd like to have the loop maintained internally with `requestAnimationFrame` and listen to the video's `onplayed` and `onpaused` (among others) events to only run the loop while the video is actively playing, controlling the broadcast of `change` events through the HTMLVideoElement api.  All I should have to do from my own code is `videoStatic.getVideo().currentTime = 10` to cause a re-render of the map. 

## Who will do it?

I'm already engaged in this work myself.  It's not a terribly large amount of work, but I'll need the maintainers help making sure it follows style and the API works nicely.

If this is deemed out-of-scope for the ol core, I'll maintain these classes as third-party (definitely not preferred) but would appreciate maybe a link on the third-party page?

Thanks developers!

**Comment by subdavis** [comment]
Wrote an initial implementation, and the performance is pretty unacceptable.  30-60FPS video as a map layer boils down to `drawImage` being too expensive.

It's certainly doable, and I'll leave some code samples later for future discussion, but this seems like an overall bad idea.

**Comment by jahow** [comment]
Hey,

This definitely sounded good at first! Now that we have a composite renderer that can take any html element as a map layer, maybe we can drop the idea of using a `<canvas>` altogether and simply put a native video element in the map?

**Comment by subdavis** [comment]
@jahow could you point me in the direction of that layer/source?  I've checked both the docs and the code and I don't see anything about using native elements as layers.  I only see overlay, which doesn't scale with the map and cannot be put under another layer

**Comment by jahow** [comment]
If you look at the base layer renderer class you'll see that the mechanic now revolves mainly around `prepareFrame` (which decides if a render is required or not) and `renderFrame` (which returns an HTML element to be added to the map).

All the renderers implement this to some degree, although I think all of them use `canvas` elements. But considering you have the frame state in the `renderFrame` method, you could theoretically output a video element and transform it (translate/scale/rotation) to match the map context.

Hope that is clear enough!

**Comment by th0mas-codes** [comment]
@subdavis Did you ever figure this out and gain more insight around this ?
