### ISSUE TITLE
ol.map: Single WMS Image failed to load with rotation

### ISSUE THREAD

**Issue by rmaddu** [openlayers/openlayers#9715]
When we are passing some rotation value through the **ol.View** for **ol.Map**, we are getting requested width or height value exceeds the maximum value from WMS service. The response is EMPTY, since our WMS service supports only 4096 is maximum width or height. But the Open layers calculated width and/or height are exceeds the 4096.
When we are passing rotation value is ZERO or some values randomly, an image is generated properly. This case NO maximum width or height issue.

**Our questions -**

- Do we have any maximum width or height limitation related issues with Openlayers? How you are calculating these widths and height values?

- For some rotation values, png/pdf is generated properly. For some rotations not. How the width and height are calculated using rotation? 

- How to trace the issue?

**Pseudocode:** 
<body>
    <h2>My Map</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
      var layers = [
        new ImageLayer({
          extent: [-9937226.13714463, 5325301.819704257, -9937056.5628553685, 5325493.7802957408],
          source: new ImageWMS({
            url: 'http://XXXXX/nwwms8/wms',
            params: {
              "LAYERS": ["XXX", "XXXX", "XXXX", "XXX", "XXXX", "XXXX", "XXXXE", "XXXX"]
            }
          })
        })
      ];
      var map = new ol.Map({
        target: 'map',
        layers: layers,
        view: new ol.View({
          zoom: 4,
          projection: "EPSG:3857",
          extent: [-9937226.13714463, 5325301.819704257, -9937056.5628553685, 5325493.7802957408],
          center: [-9937141.35, 5325397.7999999989],
          rotation: 0.45783372105883835,
          resolution: 0.21617183725660047
        })
      });
    </script>
  </body>

**Comment by mike-000** [comment]
A rotated image must enclose the viewport, so either dimension could be up to sqrt(2) times greater than the maximum of the unrotated dimensions, which in turn depend on the `hidpi `and `ratio `options used in the `ImageWMS `constructor.  You haven't specified which version you are using but WMS may also be affected by #9585 in OL6 and PDF generation by #9460 in all versions and #9665 in OL6.
![image](https://user-images.githubusercontent.com/49240900/60339804-b52e3700-99a1-11e9-9c55-9e5748b3ba9d.png)

**Comment by rmaddu** [comment]
- Attached the sample snap, how we have selected the map area. The issue is specific to A3 size. working fine with A4 size.

- We are using OpenLayers 4.6.4 version

- Is an issue with OpenLayers?

- Is an issue already fixed in OpenLayers 5 and OpenLayers 6?

- Our understanding is –
             If ((rotated image dimension*1.414)> maximum of the unrotated dimension)
               {
              Empty Image
               }
	Is our understanding correct? 

Our question:
1.	How to check proactively, whether the rotation angle (rotated image dimension) is within the limits or not? so that we can avoid an empty image from WMS service.

![SampleSnap](https://user-images.githubusercontent.com/52063294/60422199-1f94e080-9c09-11e9-9369-aab6971e8990.JPG)

**Comment by mike-000** [comment]
A3 at 300dpi will exceed 4096 width with `hidpi: false` and `ratio: 1` (which minimise the requested size) even without rotation.  The only obvious opportunity in a public method to see what OpenLayers is requesting seems to be via a custom image load function.  You could reduce the pdf dpi but that would reduce the quality of all layers, so an alternative workaround would be to scale down the WMS image request to a maximum of 4096 and then stretch the output back to what OpenLayers was expecting.  To simplify the demo I have used v5.3.0 full build and the` rendercomplete `event, and  because of issue #9460 changed `calculateExtent` and `fit` to `getResolution` and `setResolution` https://codepen.io/anon/pen/bPvExb

**Comment by rmaddu** [comment]
Thanks for your solution.
