### ISSUE TITLE
OL6: forEachLayerAtPixel and hit detection across multiple layers

### ISSUE THREAD

**Issue by xemoka** [openlayers/openlayers#9720]
**Describe the bug**
I'm having difficulties getting hit detection to work properly for an individual ImageLayer (ImageArcGISRest) layer when multiple layers are added to the map. If only the single imageLayer is added to the map, I can get my hit detection code to work properly (ignore transparent pixels for the same layer) but when adding other layers to the map (including Tile Maps, VectorTileLayers etc.) the same code stops ignoring transparent pixels and instead reports a hit if ANY layer has a non-transparent pixel. 

It appears as though if there's any non-transparent data on any layer it's returning true for any layer, not just the current.

Could this be due to the change of there being one canvas per layer in ol6 vs only one canvas in ol5?

See my reproduction at https://codesandbox.io/s/aged-frog-i7zwu?fontsize=14 , toggle the lines 134-136 to see what I'm getting at.

**Expected behavior**
I expect it to work similar to OL5, where the transparency of the given layer is only taken into consideration. This code works in OL5.

Am I just making a mistake?

**Comment by jahow** [comment]
Hi, it looks like this is indeed a bug from the library. Thanks a lot for sharing the reproduction case, I'll try to look into it.

**Comment by jahow** [comment]
@xemoka there is a documented workaround now, although it isn't a fix per se so I'm leaving this open just in case.

**Comment by HemenRohani** [comment]
I have same problem when adding openstreetmap base layer to map!

**Comment by HemenRohani** [comment]
I found the solution to this problem according to this [answer](https://stackoverflow.com/questions/61860054/map-foreachlayeratpixel-callback-function-has-an-empty-rgba-array/61871117#61871117).

add className to layer an add crossOrigin: 'anonymous' to layer source.
```
let layer = new TileLayer({
    className: 'layer',
    source: new TileWMS({
        url: 'http://localhost/geoserver/ns/wms',
        params: {
            'LAYERS': 'ns:layer',
        },
        serverType: 'geoserver',
        crossOrigin: 'anonymous',
    })
});
```
