### ISSUE TITLE
Use ol.source.ImageArcGISRest add ArcGISDynamicMapServiceLayer, How to get the features of this layer.

### ISSUE THREAD

**Issue by huishuohuadeTT** [openlayers/openlayers#9721]
Use ol.source.ImageArcGISRest add ArcGISDynamicMapServiceLayer, How to get the features of this layer.

**Comment by xemoka** [comment]
It's a little unclear what you're asking for, are you wanting to learn how to add a layer from an ArcGIS Dynamic Map Service or do you want to query it for the values of properties of a feature onClick (possibly returning geometry)? 

For the former: https://openlayers.org/en/latest/examples/arcgis-image.html

For the latter:
You need to make the request to Esri's JSON endpoint manually; the `${mapService.url}/identify` endpoint. 

Hook up an `onclick` event to your map (i.e.: `mapElement.on('click', infoClickHandler`), then write an `infoClickHandler` that identifies the pixel click location, loops through all the layers on the map, collects what mapServers to query, converts the pixel click location to coordinates, and queries each mapServer with the coordinates and enabled layers. 

```js
function infoClickHandler (event) {
    console.log('Info Click Handler Fired:', event)

    let currentInfos = [] // the array we'll fill with the data returned from arcgis Server

    // get pixel click location
    const pixel = this.mapEl.getEventPixel(event.originalEvent)

    // generate list of layers
    let layers = []
    this.mapEl.forEachLayerAtPixel(
    pixel,
    layer => {
        layers.push(layer)
    },
    {
        layerFilter: layer => {
        return (
            layer.get('ignoreInfo') !== true && // give your non-infoable layers a property to filter by, when creating the OpenLayersObject for the layer, make sure you `layer.set('ignoreInfo', true)` 
            !(layer instanceof VectorTileLayer) && // only if the layer is not a vector layer do we want to query
            !(layer instanceof VectorLayer)     // the ${mapServer}/identify endpoint;
        )
        },
        hitTolerance: 0
    }
    )

    // only if there are layers to query
    if ( layers.length > 0 ) {
        const clickCoordinate = this.mapEl.getCoordinateFromPixel(pixel)
        let mapServerInfo = []
        layers
            .forEach(layer => {
                const url = layer.getSource().getUrl() // collect mapServer URL
                const id = layer
                    .getSource()
                    .getParams()
                    .layers.replace('show:', '') // remove the visible component to just get the raw url
                const server = mapServerInfo.find(server => server.url === url) // see if server already exists in mapServerInfo
                if (!server) {
                    mapServerInfo.push({ url: url, layers: [id] }) // if not, it
                } else {
                    mapServerInfo.find(server => server.url === url).layers.push(id) // if so, add the ID of this layer for query
                }
            })

        console.log('Request for:', layers.map(layer => layer.get('name'))) // 'name' property is one I assign with layer.set('name', ${name})

        const requestUrls = mapServerInfo.map(server => { // for each mapServer, build a query object and add it to an array
            const query = {
            geometry: clickCoordinate, // where in CRS we clicked
            geometryType: 'esriGeometryPoint',
            sr: 3857,
            layers: `all:${server.layers}`, // query all the layer ids for htis map server built above
            tolerance: 5,
            mapExtent: mapElement.getView().calculateExtent(), // get map extent
            imageDisplay: `${mapElement.getSize()},72`,  // get map size/resolution
            returnGeometry: false, // I don't want geometry, but you might want to display it on a 'selection layer'
            f: 'json'
            }
            const url = new URL(`${server.url}/identify`)
            url.search = new URLSearchParams(query)
            return url
        })

        Promise.all(requestUrls.map(url => fetch(url))) // build a promise, fetch the data using the fetchAPI
            .then(responses =>
                Promise.all(responses.map(response => response.json())) // unwrap the response
            )
            .then(response => {
                let mergedResponses = [] // merge them together
                response.forEach(result => mergedResponses.push(...result.results))
                currentInfos.push(...mergedResponses)
            })
    }

    console.log(currentInfos) // do with these as you would, like throw them in a popup. 
}
```

**Comment by huishuohuadeTT** [comment]
目前在学习过程中使用了ol.source.ImageArcGISRest来加载Arcgis service的发布的动态图层，但是我在使用ol.interaction.select做点选、框选、圆选的时候是没有办法获取到该图层的要素。因为我要保留服务里的样式，比如(ArcMap的标注、符号系统、样式，参考附件)；那我使用ol.source.ImageArcGISRest加载图层，如何去实现ol.interaction.select的交互。



------------------ 原始邮件 ------------------
发件人: "Justin Robinson"<notifications@github.com>;
发送时间: 2019年6月28日(星期五) 凌晨0:26
收件人: "openlayers/openlayers"<openlayers@noreply.github.com>;
抄送: "真的"<1728448099@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [openlayers/openlayers] Use ol.source.ImageArcGISRest addArcGISDynamicMapServiceLayer, How to get the features of this layer. (#9721)




It's a little unclear what you're asking for, are you wanting to learn how to add a layer from an ArcGIS Dynamic Map Service or do you want to query it for the values of properties of a feature onClick (possibly returning geometry)?
 
For the former: https://openlayers.org/en/latest/examples/arcgis-image.html
 
For the latter:
 You need to make the request to Esri's JSON endpoint manually; the ${mapService.url}/identify endpoint.
 
Hook up an onclick event to your map (i.e.: mapElement.on('click', infoClickHandler), then write an infoClickHandler that identifies the pixel click location, loops through all the layers on the map, collects what mapServers to query, converts the pixel click location to coordinates, and queries each mapServer with the coordinates and enabled layers.
 function infoClickHandler (event) {     console.log('Info Click Handler Fired:', event)     let currentInfos = [] // the array we'll fill with the data returned from arcgis Server     // get pixel click location     const pixel = this.mapEl.getEventPixel(event.originalEvent)     // generate list of layers     let layers = []     this.mapEl.forEachLayerAtPixel(     pixel,     layer => {         layers.push(layer)     },     {         layerFilter: layer => {         return (             layer.get('ignoreInfo') !== true && // give your non-infoable layers a property to filter by, when creating the OpenLayersObject for the layer, make sure you `layer.set('ignoreInfo', true)`              !(layer instanceof VectorTileLayer) && // only if the layer is not a vector layer do we want to query             !(layer instanceof VectorLayer)     // the ${mapServer}/identify endpoint;         )         },         hitTolerance: 0     }     )     // only if there are layers to query     if ( layers.length > 0 ) {         const clickCoordinate = this.mapEl.getCoordinateFromPixel(pixel)         let mapServerInfo = []         layers             .forEach(layer => {                 const url = layer.getSource().getUrl() // collect mapServer URL                 const id = layer                     .getSource()                     .getParams()                     .layers.replace('show:', '') // remove the visible component to just get the raw url                 const server = mapServerInfo.find(server => server.url === url) // see if server already exists in mapServerInfo                 if (!server) {                     mapServerInfo.push({ url: url, layers: [id] }) // if not, it                 } else {                     mapServerInfo.find(server => server.url === url).layers.push(id) // if so, add the ID of this layer for query                 }             })         console.log('Request for:', layers.map(layer => layer.get('name'))) // 'name' property is one I assign with layer.set('name', ${name})         const requestUrls = mapServerInfo.map(server => { // for each mapServer, build a query object and add it to an array             const query = {             geometry: clickCoordinate, // where in CRS we clicked             geometryType: 'esriGeometryPoint',             sr: 3857,             layers: `all:${server.layers}`, // query all the layer ids for htis map server built above             tolerance: 5,             mapExtent: mapElement.getView().calculateExtent(), // get map extent             imageDisplay: `${mapElement.getSize()},72`,  // get map size/resolution             returnGeometry: false, // I don't want geometry, but you might want to display it on a 'selection layer'             f: 'json'             }             const url = new URL(`${server.url}/identify`)             url.search = new URLSearchParams(query)             return url         })         Promise.all(requestUrls.map(url => fetch(url))) // build a promise, fetch the data using the fetchAPI             .then(responses =>                 Promise.all(responses.map(response => response.json())) // unwrap the response             )             .then(response => {                 let mergedResponses = [] // merge them together                 response.forEach(result => mergedResponses.push(...result.results))                 currentInfos.push(...mergedResponses)             })     }     console.log(currentInfos) // do with these as you would, like throw them in a popup.  }

**Comment by huishuohuadeTT** [comment]
------------------ 原始邮件 ------------------
发件人: "Justin Robinson"<notifications@github.com>;
发送时间: 2019年6月28日(星期五) 凌晨0:26
收件人: "openlayers/openlayers"<openlayers@noreply.github.com>;
抄送: "真的"<1728448099@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [openlayers/openlayers] Use ol.source.ImageArcGISRest addArcGISDynamicMapServiceLayer, How to get the features of this layer. (#9721)




It's a little unclear what you're asking for, are you wanting to learn how to add a layer from an ArcGIS Dynamic Map Service or do you want to query it for the values of properties of a feature onClick (possibly returning geometry)?
 
For the former: https://openlayers.org/en/latest/examples/arcgis-image.html
 
For the latter:
 You need to make the request to Esri's JSON endpoint manually; the ${mapService.url}/identify endpoint.
 
Hook up an onclick event to your map (i.e.: mapElement.on('click', infoClickHandler), then write an infoClickHandler that identifies the pixel click location, loops through all the layers on the map, collects what mapServers to query, converts the pixel click location to coordinates, and queries each mapServer with the coordinates and enabled layers.
 function infoClickHandler (event) {     console.log('Info Click Handler Fired:', event)     let currentInfos = [] // the array we'll fill with the data returned from arcgis Server     // get pixel click location     const pixel = this.mapEl.getEventPixel(event.originalEvent)     // generate list of layers     let layers = []     this.mapEl.forEachLayerAtPixel(     pixel,     layer => {         layers.push(layer)     },     {         layerFilter: layer => {         return (             layer.get('ignoreInfo') !== true && // give your non-infoable layers a property to filter by, when creating the OpenLayersObject for the layer, make sure you `layer.set('ignoreInfo', true)`              !(layer instanceof VectorTileLayer) && // only if the layer is not a vector layer do we want to query             !(layer instanceof VectorLayer)     // the ${mapServer}/identify endpoint;         )         },         hitTolerance: 0     }     )     // only if there are layers to query     if ( layers.length > 0 ) {         const clickCoordinate = this.mapEl.getCoordinateFromPixel(pixel)         let mapServerInfo = []         layers             .forEach(layer => {                 const url = layer.getSource().getUrl() // collect mapServer URL                 const id = layer                     .getSource()                     .getParams()                     .layers.replace('show:', '') // remove the visible component to just get the raw url                 const server = mapServerInfo.find(server => server.url === url) // see if server already exists in mapServerInfo                 if (!server) {                     mapServerInfo.push({ url: url, layers: [id] }) // if not, it                 } else {                     mapServerInfo.find(server => server.url === url).layers.push(id) // if so, add the ID of this layer for query                 }             })         console.log('Request for:', layers.map(layer => layer.get('name'))) // 'name' property is one I assign with layer.set('name', ${name})         const requestUrls = mapServerInfo.map(server => { // for each mapServer, build a query object and add it to an array             const query = {             geometry: clickCoordinate, // where in CRS we clicked             geometryType: 'esriGeometryPoint',             sr: 3857,             layers: `all:${server.layers}`, // query all the layer ids for htis map server built above             tolerance: 5,             mapExtent: mapElement.getView().calculateExtent(), // get map extent             imageDisplay: `${mapElement.getSize()},72`,  // get map size/resolution             returnGeometry: false, // I don't want geometry, but you might want to display it on a 'selection layer'             f: 'json'             }             const url = new URL(`${server.url}/identify`)             url.search = new URLSearchParams(query)             return url         })         Promise.all(requestUrls.map(url => fetch(url))) // build a promise, fetch the data using the fetchAPI             .then(responses =>                 Promise.all(responses.map(response => response.json())) // unwrap the response             )             .then(response => {                 let mergedResponses = [] // merge them together                 response.forEach(result => mergedResponses.push(...result.results))                 currentInfos.push(...mergedResponses)             })     }     console.log(currentInfos) // do with these as you would, like throw them in a popup.  }
