### ISSUE TITLE
Calling setUrl on a vector tile source does not trigger tile loading

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#9726]
**Describe the bug**
When calling `setUrl` on a vector tile layer, new tiles do not load.

**To Reproduce**
1. Create a vector tile layer with a vector tile source, using `''` as the vector tile source url
2. Call `source.setUrl(url)` with a tile URL template
3. See that tiles are not loaded

**Expected behavior**
I expected new tiles to be loaded when setting the source URL.

I can see that the source change event is relayed by the layer and that triggers a map render.  And I can see that `load` is not getting called on the vector render tiles.  Didn't dig further to see where the disconnect is.

**Comment by ahocevar** [comment]
The root of the issue is that `''` as tile url means an empty tile, which happens e.g. internally for tiles outside the source extent. The bug is that once the tile state is set to `TileState.EMPTY`, no further attempts will be made to load the tile. I'm working on a fix for that now.
