### ISSUE TITLE
event.inversePixelTransform is undefined in getVectorContext()

### ISSUE THREAD

**Issue by gedaiu** [openlayers/openlayers#9727]
I migrated from ol 5.3.3 to 6.0.0-beta11

and it looks like the new `getVectorContext` can't be used on the post compose event:
```
this.map.olMap.on('postcompose', (event) => {
    const vectorContext = getVectorContext(event);
});
```

raises the error:
```
TypeError: event.inversePixelTransform is undefined
```

![image](https://user-images.githubusercontent.com/4217037/60289611-1826bc00-9917-11e9-9308-64eb636297ef.png)

**Comment by mike-000** [comment]
Each layer now has its own context, so `getVectorContext() `can't be used for the map.  See the Marker Animation example where `map.on('postcompose', moveFeature);` has changed to `vectorLayer.on('postrender', moveFeature);`

**Comment by gedaiu** [comment]
oh nice! I could not find this change in the changelog.
