### ISSUE TITLE
Heatmap layer WebGL warnings

### ISSUE THREAD

**Issue by fredj** [openlayers/openlayers#9730]
Warnings are displayed in the dev console when loading the heatmap-earthquakes example.
I guess it's related the the hit detection added in #9655

The warnings are:
```
WebGL: INVALID_OPERATION: useProgram: program not valid
WebGL: INVALID_OPERATION: getUniformLocation: program not linked
WebGL: INVALID_OPERATION: getAttribLocation: program not linked
WebGL-0x34f454258100]GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.
Helper.js:666 WebGL: too many errors, no more errors will be reported to the console for this context.
```

Maybe we should have a mechanism to deactivate the hit detection for a layer?

**Comment by fjorgemota** [comment]
This issue isn't stale.

It still happens on the latest OpenLayers beta:

![WebGL warnings on OpenLayers beta](https://user-images.githubusercontent.com/529864/63985633-dba64680-caa6-11e9-814c-3f631fa250b1.png)

By disabling the heatmap layer these errors disappear..so yeah, seems like it's a specific problem on the heatmap layer.
