### ISSUE TITLE
In SAFARI zoom in/out icons are disappearing

### ISSUE THREAD

**Issue by evescat** [openlayers/openlayers#9731]
In Safari 12.1.1 , after pointing with mouse cursor on the *zoom in* icon the *zoom out* icon disappears, and in reverse, pointing on *zoom out* makes *zoom in* disappears.

![image1](https://user-images.githubusercontent.com/52324846/60351521-3e576500-99c6-11e9-9dcf-7906ae14805b.png)

**Comment by ahocevar** [comment]
This was a known issue in v5.x, and should have been fixed in the meantime. See e.g. https://openlayers.org/en/master/examples/simple.html. Cam you confirm?

**Comment by evescat** [comment]
The link you sent above, the icons are displayed correctly. But here, https://openlayers.org/en/latest/examples/bing-maps.html (v5.3.0) the issue happens. I am not sure if the map you sent me is the latest version?

**Comment by ahocevar** [comment]
For that example, https://openlayers.org/en/master/examples/bing-maps.html is the latest.

**Comment by evescat** [comment]
Thanks, it works in the latest.
