### ISSUE TITLE
icon-sprite-webgl example cross-browser issues

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#9734]
- [x] When loading this example on Chrome 75.0.3770.90, the points layer does not show before the user interacts with the map (e.g. pan or zoom). On Safari 12.1.1, this also happens occasionally when reloading the page.
- [x] `Error: WebGL warning: drawElements: TEXTURE_2D at unit 0 is incomplete: The dimensions of `level_base` are not all positive.` (Firefox 67.0.4)
- [x] `Error: WebGL warning: drawElements: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)` (Firefox 67.0.4)
- [x] `WebGL: INVALID_VALUE: texImage2D: invalid image` (Safari 12.1.1)

**Comment by jahow** [comment]
Double-checked the example on listed browsers, I don't see these specific warnings anymore BUT the tile json source points to tiles served in HTTP, which causes a lot of other browser warnings.
