### ISSUE TITLE
filter-points-webgl example cross-browser issues

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#9735]
- [x] `WebGL: INVALID_OPERATION: drawElements: attempt to access out of bounds arrays` (Safari 12.1.1) 
- [x] `Error: WebGL warning: drawElements: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)` (Firefox 67.0.4)
- [x] `Error: WebGL warning: drawElements: Indexed vertex fetch requires 153604 vertices, but attribs only supply 0.` (Firefox 67.0.4)

**Comment by jahow** [comment]
Double-checked on both browsers, the warnings are gone.
