### ISSUE TITLE
WebGL hit detection transform does not take pixel ratio into account

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#9736]
When trying WebGL hit detection with the icon-sprite-webgl.html example on a Retina display (pixel ratio: 2), I noticed that hovered icons and hit detections do not align. With a pixel ratio of 1, hit detection works as expected.

**Comment by jahow** [comment]
This probably has to do with the fact we're not looking up the right pixel here:
https://github.com/openlayers/openlayers/blob/32d1d9214cf8510b9b9870955eec2c4800c3d205/src/ol/renderer/webgl/PointsLayer.js#L545

Will try to look into this ASAP. Thanks for the issue
