### ISSUE TITLE
a hightlight layer occur when switch layer 

### ISSUE THREAD

**Issue by Gentlemeng** [openlayers/openlayers#9739]
## help help help
**Describe the bug**
This highlight arises when I use the API "updateParams" to switch different layer

**To Reproduce**
1. Please visit the Web Site "http://61.149.5.137:38080/views/openlayer_jingjinji.html"
2. Click on the seconds tab "污染物类型地图"
3. select an category in left mune, click "确定"
4. Play the timeline in bottom
5. See hightlight （layer of dark color） when switch layer for an instant. 

**Expected behavior**
I don't know why it appeared for an instant and don't hope it appeared
(Please ignore my poor english)
![01](https://user-images.githubusercontent.com/25813927/60424849-cc7c5700-9c23-11e9-911c-d46e3590d18a.png)
![02](https://user-images.githubusercontent.com/25813927/60424862-d3a36500-9c23-11e9-9558-739ba0800345.png)

**Comment by mike-000** [comment]
It looks like a tile transition effect as individual tiles will load at different speeds.  Setting `transition: 0` in the `ol.source.TileWMS` options may help to reduce the effect, or you could consider using `ImageWMS` for your overlay layers.

**Comment by Gentlemeng** [comment]
> It looks like a tile transition effect as individual tiles will load at different speeds. Setting `transition: 0` in the `ol.source.TileWMS` options may help to reduce the effect, or you could consider using `ImageWMS` for your overlay layers.

It’s useful to setting `transition:0`,although it still exists,I am all gratitude
