### ISSUE TITLE
Cannot read property 'setWorldExtent' of null in VectorLayer

### ISSUE THREAD

**Issue by jippeholwerda** [openlayers/openlayers#9742]
After upgrading to version v6.0.0-beta.11, I get the following error when adding a VectorLayer to the map:

```
ERROR TypeError: Cannot read property 'setWorldExtent' of null
    at GeoJSON.getReadOptions (Feature.js:96)
    at GeoJSON.readFeatures (JSONFeature.js:47)
    ...
```

I did not encounter this problem when using version v6.0.0-beta.4. Am I missing something or did commit https://github.com/openlayers/openlayers/commit/76f44efbb6dc7bddac1c2dc8474f86373ef89654 break this?

**Comment by ahocevar** [comment]
Thanks for reporting this. The commit you linked may indeed be the cause. Looks like we need to handle the case where no projection is available. Can you provide a working example in codesandbox.io that exposes the problem?

**Comment by jippeholwerda** [comment]
Here it is: https://codesandbox.io/embed/gallant-snyder-56ogp

Zooming out one level should trigger the error.

**Comment by ahocevar** [comment]
Thanks for providing the sandbox. I hope someone will be able to look into this soon.

**Comment by ahocevar** [comment]
@jippeholwerda If you are able to provide a pull request with a fix, that would be even better.

**Comment by jippeholwerda** [comment]
@ahocevar Thanks for the fix! That's fast.

In my code, I'm wrapping the features with a custom class to provide some styling options, but I've simplified (not enough apparently) in the sandbox a bit.

And you're absolutely right about the missing `this`. Thanks for pointing out!

**Comment by jippeholwerda** [comment]
@ahocevar Any idea when the next release will be made?
