### ISSUE TITLE
Acces to DragBox's minArea property from DragZoom

### ISSUE THREAD

**Issue by logan-bounet** [openlayers/openlayers#9746]
Hello,

For my current project, i use the DragZoom object. I noticed that the dragEnd event is fired only when the drag zone is bigger than the minArea property. But as DragZoom extends DragBox, this property is not accessible from the DragZoom object because this object's constructor had only 3 parent 's properties that can be set.. 
It is an wanted behavior ? if yes can you explain me why please ? else can i change it by just add this property to the DragZoom constructor's options ?

https://github.com/openlayers/openlayers/blob/ac3072d88836a1d8510c484aceff6e0a5f56100f/src/ol/interaction/DragZoom.js#L43

Thank you

**Comment by fredj** [comment]
The `minArea` could be added to the parent constructor. Would you be willing to create a pull request?

Note: the [property](https://github.com/openlayers/openlayers/blob/1f86818250422162d104c717daaf2cf6e6460c10/src/ol/interaction/DragBox.js#L26-L27) from the parent's typedef must be be added to the DragZoom's [typedef](https://github.com/openlayers/openlayers/blob/1f86818250422162d104c717daaf2cf6e6460c10/src/ol/interaction/DragZoom.js#L10-L20)

**Comment by logan-bounet** [comment]
Hello,

Thank you ! Here is my MR : Add minArea typedef and ctor prop in DragZoom #9751
