### ISSUE TITLE
Custom feature is not highlighted when selected

### ISSUE THREAD

**Issue by yaozhongnan** [openlayers/openlayers#9749]
I created a custom feature on the map, It looks like a circle,I want it to be highlighted as an [example](https://openlayers.org/en/latest/examples/select-features.html) when it's selected.But it wasn't highlighted as I expected.What can I do to get the highlight?

Here's my code

```javascript
import Map from "ol/Map.js";
import View from "ol/View.js";
import Select from "ol/interaction/Select.js";
import { Vector as VectorLayer } from "ol/layer.js";
import Feature from "ol/Feature";
import geomCircle from "ol/geom/Circle";
import VectorSource from "ol/source/Vector.js";
import Style from "ol/style/Style";
import Fill from "ol/style/Fill";

const layer = new VectorLayer();

const source = new VectorSource();

const feature = new Feature();

const geom = new geomCircle([0, 0]);

geom.setRadius(0.5);
feature.setGeometry(geom);
feature.setStyle(
  new Style({
    fill: new Fill({
      color: "#36CBCB"
    })
  })
);

source.addFeature(feature);

layer.setSource(source);

const map = new Map({
  layers: [layer],
  target: "map",
  view: new View({
    center: [0, 0],
    zoom: 22
  })
});

const select = new Select();

map.addInteraction(select);

select.on("select", e => {
  alert("select");
});

```

Alert is executed when feature is clicked

my code on [codeSandBox](https://codesandbox.io/s/eloquent-darwin-pe5ht?fontsize=14) can be found

Thank you very much

**Comment by mike-000** [comment]
Styles set on features take precedence over both layer and interaction styles.  Change `feature.setStyle()` to `layer.setStyle()` and it will work as you expected.

**Comment by yaozhongnan** [comment]
> Styles set on features take precedence over both layer and interaction styles. Change `feature.setStyle()` to `layer.setStyle()` and it will work as you expected.

yes, thank you for clearing up my confusion, I see a change when use ``layer.setStyle()``
