### ISSUE TITLE
Layers don't render when the rotation is 0

### ISSUE THREAD

**Issue by gedaiu** [openlayers/openlayers#9753]
I am trying to display a custom vector layer(MVT) with points. All others layers are displayed correctly when the map is not rotated, but this MVT layer is missing. If I rotate the map, my MVT layer is rendered.

I am not sure how I can reproduce this issue outside my app...

**Comment by gedaiu** [comment]
my layer disappears here: https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/Composite.js#L118

**Comment by ahocevar** [comment]
This sounds like a bug, but we need a minimal example to reproduce the issue. Can you try create a codepen or codesandbox that shows the issue?

**Comment by gedaiu** [comment]
I can try... As far as I know it looks like the canvas of one of the vector layers is removed after another vector layer is rendered...

**Comment by gedaiu** [comment]
For some reason, I can't reproduce this issue outside my app... I think this issue is related to the fact that the container used by the `CanvasLayerRenderer` is reused. This makes the layers to render inside the same `div`, and then `element.childElementCount === 2` is true. 

I am not sure why you really remove the element if there are exactly 2 canvases there

**Comment by gedaiu** [comment]
I was able to hack it, by setting different opacity, for each layer

**Comment by ahocevar** [comment]
That's only a workaround though. Container reuse is something that could use more real-world tests, so I would really be eager to get a map configuration with a combination of layers that triggers the error.  Can you try to just resemble layer order and types of the layer stack of your app, e.g. a tile layer, a vector layer, an image layer, another tile layer...?

**Comment by ahocevar** [comment]
The `element.childElementCount === 2` is for vector tile layers, which have 2 elements in their container. Could it be that you had a tile layer on top of a vector tile layer in your app?

**Comment by gedaiu** [comment]
I have 4 base layers (XYZ) which only one is visible, a Vector layer with one animated point that shows the user position and a protobuf vector tile with some points. 

It's hard for me to resemble the exact setup, because I have to provide the api tokens for the pbf vector layer, which is not that easy to do right now.
