### ISSUE TITLE
Need for Discord Community for Discussions

### ISSUE THREAD

**Issue by darkscript** [openlayers/openlayers#9756]
**Is your feature request related to a problem? Please describe.**
The feature request is not related to any existing problem

**Describe the solution you'd like**
I just think the openlayers developers and users would benefit largely through a community where exchange of ideas can happen. Not sure if there already exist such a community, but discord is just amazing and I have seen open source projects growing from it, for instance https://discordapp.com/invite/HBherRA

**Comment by darkscript** [comment]
![image](https://user-images.githubusercontent.com/13992858/60702494-d514ac00-9f07-11e9-80cc-ad368e003429.png)
Just image how much all these channels would help all the developers, the core team will also gather info about new features required by users.

**Comment by xemoka** [comment]
This would be a huge benefit as a user—discord, gitter, spectrum, anything that's "officially sanctioned" would be a huge help; particularly with the OL6 update, I'm having difficulties finding anywhere talking about it aside from the donation campaign. Am I just unaware?

The mailing lists are quiet (dev and user), even though lots of development is going on. The blog is non-existent and the wiki here isn't really updated. The twitter barely has any activity. I get this is a utility and not a large project, but I'm surprised something that can garner such large donations doesn't have some kind of active public communication channel.

There's an inactive channel at the https://thespatialcommunity.org/ and an IRC chatroom on freenode that's silent. 

What can be done to improve OL's visibility and communications?

**Comment by CDBridger** [comment]
Could this be reopened?

**Comment by ahocevar** [comment]
There is an OpenLayers gitter channel already: https://gitter.im/openlayers/openlayers
