### ISSUE TITLE
WebGL renderer has issues with font rendering

### ISSUE THREAD

**Issue by Razi91** [openlayers/openlayers#9758]
**Describe the bug**
Text on WebGL is not rendered correctly: it's blurred and not cropped correctly

Canvas:
![Screenshot_20190705_122716](https://user-images.githubusercontent.com/5995454/60716708-5f690a00-9f20-11e9-96e9-413c620c7e1b.png)

WebGL:
![Screenshot_20190705_123003](https://user-images.githubusercontent.com/5995454/60716818-9dfec480-9f20-11e9-87c1-a17fb29d43f5.png)

**To Reproduce**
Create any text with stroke:
```js
return new Style({
    text: new Text({
        font: 'bold 16px Helvetica, sans-serif',
        text: feature.get('jpt_nazwa_'),
        zIndex: 10000,
        stroke: new Stroke({
            color: '#fff',
            width: 2
        })
    }),
    stroke: new Stroke({
        color: '#fff',
        width: 2
    })
})
```

**Expected behavior**
Text should look the same as with canvas renderer.

**Comment by ahocevar** [comment]
That WebGL renderer has been removed since v5.x.

**Comment by Razi91** [comment]
> That WebGL renderer has been removed since v5.x.

I used WebGLMap which is still in 5.x and it is NOT marked as deprecated.

If it will be removed, then how to deal with huge number of points to render? Default renderer gives me poor framerate of 4fps for SVG, while WebGL gives me about 40 fps.

Fiddle with comparison: https://jsfiddle.net/s9pLk4cj/

**Comment by ahocevar** [comment]
For points, we have a new WebGL point layer renderer. See the examples in https://openlayers.org/en/master/examples/
