### ISSUE TITLE
Pinch-to-zoom fails to work as intended in Safari / iPadOS 13

### ISSUE THREAD

**Issue by neave** [openlayers/openlayers#9760]
**Describe the bug**
Apple introduced “desktop-class” browsing in Safari in the new iPadOS 13. However this is causing major problems with the pinch-to-zoom gesture as that gesture now zooms the whole window rather than just the map.

**To Reproduce**
1. Use an iPad with the iPadOS beta
2. Go to an OL example such as https://openlayers.org/en/latest/examples/bing-maps.html
3. Try to pinch to zoom
3. See error

**Expected behavior**
The map should zoom, not the whole browser window. To fix this, I expect some sort of event listener will need preventDefault() applied to its event.

**Comment by adrian16724** [comment]
@neave hello paul i can help

**Comment by adrian16724** [comment]
> **Describe the bug**
> Apple introduced “desktop-class” browsing in Safari in the new iPadOS 13. However this is causing major problems with the pinch-to-zoom gesture as that gesture now zooms the whole window rather than just the map.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Use an iPad with the iPadOS beta
> 2. Go to an OL example such as https://openlayers.org/en/latest/examples/bing-maps.html
> 3. Try to pinch to zoom
> 4. See error
> 
> **Expected behavior**
> The map should zoom, not the whole browser window. To fix this, I expect some sort of event listener will need preventDefault() applied to its event.

hello paul i need help with star atlas

**Comment by fredj** [comment]
@neave I've installed the iPadOS and the pinch zoom works as expected. Can you please test again?

**Comment by neave** [comment]
@fredj This does seem to work now in iPadOS 13.1. Closing as resolved.
