### ISSUE TITLE
Cannot wrapX graticule in Openlayers 5

### ISSUE THREAD

**Issue by sebdog** [openlayers/openlayers#9761]
There is currently no feature to wrapX a graticule like in openlayers 2 and 3. Is there any way or plan to implement this?

**Comment by mike-000** [comment]
The OpenLayers 6 replacement https://openlayers.org/en/master/apidoc/module-ol_layer_Graticule-Graticule.html can be wrapped.

**Comment by sebdog** [comment]
Thanks, I can wait upon release.
