### ISSUE TITLE
Feature cannot be selected on map when longitude near 190

### ISSUE THREAD

**Issue by welltothebone** [openlayers/openlayers#9764]
**Describe the bug**
Feature cannot be selected on map when longitude near 190. Layer seems to added as an unmanaged layer to map even though map.addLayer(layer) is used to add the layer to the map. The select interaction is ignoring the layer and the layer is null in the filter function. 

**To Reproduce**
1. Add the attached geojson object (see below) as a vector layer to the map using map.addLayer(geojson) 
2. Define a new Select interaction with a filter function for vector layers and add it to the map, for example:
		    let select = new Select({
				filter(feature, layer) {
					if (layer instanceof Vector) {
						return true;
					}
					return false;
				},
				multi: true,
				hitTolerance: 10
			});

                        map.addInteraction(select);

3. Listen for events on defined select: 
          select.on('select', function(e) {
			.....
          });

**Expected behavior**
The feature can be selected on the map and is not ignored by the select interaction, the layer is not null in the filter function of the select interaction. 

**Workaround**
Change the longitude to for example 170 and add it to the map. The feature can be selected and is not ignored by the select interaction. 

geojson object:
{
	"type":"FeatureCollection",
	"features":[
			{
			"type":"Feature",
			"id":"f2",
			"geometry":{
				"type":"Point",
				"coordinates":[189.6,12.1]},
				"properties":{
					"id":"aaaeeebbbbbdd",
					"name":"name1"
					}
			}
			]
}

**Comment by mike-000** [comment]
You need to specify `wrapX: false` on the vector source to be able to interact with geometries outside the normal world extent (and using the same setting on the interaction will prevent selected features wrapping where unselected ones don't) https://codesandbox.io/s/select-features-iznep
