### ISSUE TITLE
Vector tile caches wrong zoomlevel tiles

### ISSUE THREAD

**Issue by sookoll** [openlayers/openlayers#9770]
I use tippencanoe to create pbf-tiles in web directory and Vue-application with ol v.5.3.3 to display them as layer. Everything works as expected, but if user zoom in quite fast, ol seems to cache more general tiles, so user can see only heavily generalised polygons on map. And as they are cached, no new requests are made to fetch appropriate tiles. Also, if user zoom in fast enough over 14 zoomlevel, no tiles are dispalyed at all. None of these happen, if user zooms in slowly to wait until each zoomlevel tiles are loaded.

This is what happens if user zooms in fast enough:
<img width="997" alt="Screenshot 2019-07-12 at 12 50 49" src="https://user-images.githubusercontent.com/1793122/61120454-b5e8c200-a4a5-11e9-99d3-ffabf6a12f52.png">

This is expected that user should see:
<img width="905" alt="Screenshot 2019-07-12 at 12 52 15" src="https://user-images.githubusercontent.com/1793122/61120455-b6815880-a4a5-11e9-8113-0013e2208825.png">

Also setting cacheSize=0 not help.

**Comment by mike-000** [comment]
Do you see any load errors on the console log suggesting the server cannot keep up with the requests from rapid zooming?  If requested tiles are not loading you are probably seeing the effect of the default `useInterimTilesOnError` vector tile layer option.

**Comment by sookoll** [comment]
No, I dont see any errors on console. All requested tiles finish loading.

**Comment by ahocevar** [comment]
Try to use v6.0.0-beta.11 instead of v5.3.3. The vector tile rendering and caching has completely been reworked.

**Comment by sookoll** [comment]
I tried 6.beta and it seems that it work better than 5.3. Raster teile rendering is some what weird, a lot of action occur on map all the time but vector teile issues are gone.

**Comment by YuhangCh** [comment]
> Try to use v6.0.0-beta.11 instead of v5.3.3. The vector tile rendering and caching has completely been reworked.

Unfortunately , I still seem to be stuck in a similar problem with v6.1.1:
The  vector tiles which been cached can't refresh to display the new properties when i update their origin data.
This is my vector tiles source , origin data store in postgresql.
```
  let riskVTSource = new VectorTileSource({
  cacheSize: 50,
  maxZoom: 15,
  format: new MVT({
    //idProperty: 'fid'
  }),
  url: 'http://xx:8080/geoserver-2.16/gwc/service/tms/1.0.0/' +
      '	xx:yy@EPSG%3A900913@pbf/{z}/{x}/{-y}.pbf'
});
```
layer :
```
export let riskVTLayer = new VectorTileLayer({
  name:'risk-map',
  source: riskVTSource,
  style: function (feature) {
    return createRiskLevelStyle(feature);
  }
});
```
When i update origin data ,problem occurred:

the zoom levels which not be cached return the correct (new) properties ,but the zoom levels had been cached still return the old properties ,it doesn't work even i refresh the page :
![Screen Recording 2020-02-10 at 16 25 30 2020-02-10 16_27_28](https://user-images.githubusercontent.com/20501203/74132841-4c3ebb00-4c22-11ea-8c5f-b9c32058fbba.gif)
i try to do a clear use the `source`'s `clear()` function ,but still doesn't work.
How can i clear the cached tiles manually?

**Comment by YuhangCh** [comment]
> > Try to use v6.0.0-beta.11 instead of v5.3.3. The vector tile rendering and caching has completely been reworked.
> 
> Unfortunately , I still seem to be stuck in a similar problem with v6.1.1:
> The vector tiles which been cached can't refresh to display the new properties when i update their origin data.
> This is my vector tiles source , origin data store in postgresql.
> 
> ```
>   let riskVTSource = new VectorTileSource({
>   cacheSize: 50,
>   maxZoom: 15,
>   format: new MVT({
>     //idProperty: 'fid'
>   }),
>   url: 'http://xx:8080/geoserver-2.16/gwc/service/tms/1.0.0/' +
>       '	xx:yy@EPSG%3A900913@pbf/{z}/{x}/{-y}.pbf'
> });
> ```
> 
> layer :
> 
> ```
> export let riskVTLayer = new VectorTileLayer({
>   name:'risk-map',
>   source: riskVTSource,
>   style: function (feature) {
>     return createRiskLevelStyle(feature);
>   }
> });
> ```
> 
> When i update origin data ,problem occurred:
> 
> the zoom levels which not be cached return the correct (new) properties ,but the zoom levels had been cached still return the old properties ,it doesn't work even i refresh the page :
> ![Screen Recording 2020-02-10 at 16 25 30 2020-02-10 16_27_28](https://user-images.githubusercontent.com/20501203/74132841-4c3ebb00-4c22-11ea-8c5f-b9c32058fbba.gif)
> i try to do a clear use the `source`'s `clear()` function ,but still doesn't work.
> How can i clear the cached tiles manually?

Sorry, eventually, I found out that this is a geoserver problem.
