### ISSUE TITLE
event does not take effect

### ISSUE THREAD

**Issue by LCLucky** [openlayers/openlayers#9776]
**Describe the bug**
Registration event to document does not take effect

**To Reproduce**
1.document.addEventListener('mouseup',function(e) {
       //dosomething;
});
but it did not   take effect

**Expected behavior**

**Comment by fredj** [comment]
Please create a minimal example on https://codesandbox.io or similar.

**Comment by illogicz** [comment]
https://codesandbox.io/s/polished-firefly-kyeq6

Openlayers is preventing the mouseup events from propagating.

**Comment by ahocevar** [comment]
This has been fixed in the meantime. See updated codesandbox with the latest `ol@dev`: https://codesandbox.io/s/hopeful-monad-1ksp7
