### ISSUE TITLE
OSM does not show Map

### ISSUE THREAD

**Issue by MaziarSangi** [openlayers/openlayers#9777]
I have added OSM to my website but it only shows me Plus minus Icons (not any map). I used following tut for adding OSM to my website: https://mediarealm.com.au/articles/openstreetmap-openlayers-map-markers/ #2317

**Comment by orpheus** [comment]
can you share your actual code?

**Comment by MaziarSangi** [comment]
> can you share your actual code?
Thanks for answering.
Solved  by changing OpenLayers.js file and setting width and height for map.
