### ISSUE TITLE
map size  is zero

### ISSUE THREAD

**Issue by NanXunbiubiu** [openlayers/openlayers#9780]
when i set the map DOM to display none and i resize the window, i have  a canvas need to get pixel from coordinate, then i have an error: the map.getSize() = [0,0].  Therefore i set the map DOM to display block , which is unuseful and the window is empty.

    ##var pixel = this._map.getPixelFromCoordinate(this.location);
    pixel = null
`
![image](https://user-images.githubusercontent.com/37281618/61354436-c2558c00-a8a4-11e9-8b4a-849c9a5d731e.png)
![image](https://user-images.githubusercontent.com/37281618/61354525-f2049400-a8a4-11e9-9baa-7cba52b95779.png)

**Comment by mike-000** [comment]
Call `map.updateSize();` after making changes to the map div.

**Comment by NanXunbiubiu** [comment]
it  does not work!

**Comment by NanXunbiubiu** [comment]
> Call `map.updateSize();` after making changes to the map div.

it does not work!

**Comment by mgurbuz-tr** [comment]
I've had this problem before. I solved the problem as follows. Can you try it?

map.setSize([200,200]); //Value does not matter.
map.updateSize();

**Comment by NanXunbiubiu** [comment]
> I've had this problem before. I solved the problem as follows. Can you try it?
> 
> map.setSize([200,200]); //Value does not matter.
> map.updateSize();

yes, but when you change windows size, map will be distortion
