### ISSUE TITLE
OpenLayers 2 Freeze often with Google Maps Traffic in Firefox 68+

### ISSUE THREAD

**Issue by NicoPietsch** [openlayers/openlayers#9782]
OpenLayers seems to be freezing if display Google Maps With Traffic info. If i remove the traffic info layer, everything worked fine. It is only in Firefox 68+. If i disable Caching in Firefox, everything worked also fine.
[google.txt](https://github.com/openlayers/openlayers/files/3401738/google.txt)

**Comment by NicoPietsch** [comment]
`<!DOCTYPE html>
<html lang="de-de">
<head>
   <meta charset="UTF-8">
   <title>Google OpenLayers Test</title>

   <script src="https://maps.google.com/maps/api/js?v=3&amp;client=FDG-HJHJDHDHDJSJS&sensor=false"></script>
   <script src="js/OpenLayers-2.13.1/OpenLayers.js"></script>
   <script src="https://code.jquery.com/jquery-3.4.1.min.js" type="text/javascript"></script>

   <style type="text/css">
      #map
      {
         left: 0;
         right: 0;
         top: 0;
         bottom: 0;
         position: absolute;
      }
   </style>

</head>
<body>
<div id="map">

</div>
</body>

<script type="text/javascript">
   var map;
   var gmap
   $( document ).ready( function()
   {
      init();
   });

   function init() {
      map = new OpenLayers.Map('map' );
      map.addControl(new OpenLayers.Control.LayerSwitcher());

      // the SATELLITE layer has all 22 zoom level, so we add it first to
      // become the internal base layer that determines the zoom levels of the
      // map.
      var gsat = new OpenLayers.Layer.Google(
         "Google Satellite",
         {type: google.maps.MapTypeId.SATELLITE, numZoomLevels: 22, visibility: false}
      );
      var gphy = new OpenLayers.Layer.Google(
         "Google Physical",
         {type: google.maps.MapTypeId.TERRAIN, visibility: false}
      );
      gmap = new OpenLayers.Layer.Google(
         "Google Streets", // the default
         {numZoomLevels: 20}
      );
      var ghyb = new OpenLayers.Layer.Google(
         "Google Hybrid",
         {type: google.maps.MapTypeId.HYBRID, numZoomLevels: 22, visibility: false}
      );

      map.addLayers([gsat, gphy, gmap, ghyb]);

      // Google.v3 uses EPSG:900913 as projection, so we have to
      // transform our coordinates
      map.setCenter(new OpenLayers.LonLat(10.2, 48.9).transform(
         new OpenLayers.Projection("EPSG:4326"),
         map.getProjectionObject()
      ), 5);

      map.setBaseLayer( gmap );

      /**
       * ---------------------------------------------------
       *
       *  without this everything worked fine
       *
       * ---------------------------------------------------
       */
       gTrafficLayer = new google.maps.TrafficLayer();
       gTrafficLayer.setMap( gmap.mapObject );
      /**
       * ---------------------------------------------------
       *  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       *
       * ---------------------------------------------------
       */


      var cache = OpenLayers.Layer.Google.cache[map.id];
      map.div.appendChild(gmap.mapObject.getDiv());
      cache.googleControl.appendChild(map.viewPortDiv);
      google.maps.event.trigger(map, 'resize');




   }
</script>
</html>`

**Comment by NicoPietsch** [comment]
`<!DOCTYPE html>
<html lang="de-de">
<head>
   <meta charset="UTF-8">
   <title>Google OpenLayers Test</title>

   <script src="https://maps.google.com/maps/api/js?v=3&amp;client=FDG-HJHJDHDHDJSJS&sensor=false"></script>
   <script src="js/OpenLayers-2.13.1/OpenLayers.js"></script>
   <script src="https://code.jquery.com/jquery-3.4.1.min.js" type="text/javascript"></script>

   <style type="text/css">
      #map
      {
         left: 0;
         right: 0;
         top: 0;
         bottom: 0;
         position: absolute;
      }
   </style>

</head>
<body>
<div id="map">

</div>
</body>

<script type="text/javascript">
   var map;
   var gmap
   $( document ).ready( function()
   {
      init();
   });

   function init() {
      map = new OpenLayers.Map('map' );
      map.addControl(new OpenLayers.Control.LayerSwitcher());

      // the SATELLITE layer has all 22 zoom level, so we add it first to
      // become the internal base layer that determines the zoom levels of the
      // map.
      var gsat = new OpenLayers.Layer.Google(
         "Google Satellite",
         {type: google.maps.MapTypeId.SATELLITE, numZoomLevels: 22, visibility: false}
      );
      var gphy = new OpenLayers.Layer.Google(
         "Google Physical",
         {type: google.maps.MapTypeId.TERRAIN, visibility: false}
      );
      gmap = new OpenLayers.Layer.Google(
         "Google Streets", // the default
         {numZoomLevels: 20}
      );
      var ghyb = new OpenLayers.Layer.Google(
         "Google Hybrid",
         {type: google.maps.MapTypeId.HYBRID, numZoomLevels: 22, visibility: false}
      );

      map.addLayers([gsat, gphy, gmap, ghyb]);

      // Google.v3 uses EPSG:900913 as projection, so we have to
      // transform our coordinates
      map.setCenter(new OpenLayers.LonLat(10.2, 48.9).transform(
         new OpenLayers.Projection("EPSG:4326"),
         map.getProjectionObject()
      ), 5);

      map.setBaseLayer( gmap );

      /**
       * ---------------------------------------------------
       *
       *  without this everything worked fine
       *
       * ---------------------------------------------------
       */
       gTrafficLayer = new google.maps.TrafficLayer();
       gTrafficLayer.setMap( gmap.mapObject );
      /**
       * ---------------------------------------------------
       *  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       *
       * ---------------------------------------------------
       */


      var cache = OpenLayers.Layer.Google.cache[map.id];
      map.div.appendChild(gmap.mapObject.getDiv());
      cache.googleControl.appendChild(map.viewPortDiv);
      google.maps.event.trigger(map, 'resize');




   }
</script>
</html>`

**Comment by fredj** [comment]
Hi, your question is for OpenLayers version 2 but this issue tracker is for OpenLayers version 3 (and higher).

OpenLayers version 2 is not maintained anymore, you should migrate to a more recent version. If you need a Google Maps layer take a look at http://mapgears.github.io/ol3-google-maps/
