### ISSUE TITLE
pointerMove select style is not rendered / Selected Objects type LineString

### ISSUE THREAD

**Issue by DwieDave** [openlayers/openlayers#9783]
**Describe the bug**
1. Select style is not rendered immediately - only after zoom event is triggered [style given via style attribute of `Select()` with condition pointerMove]

2. When binding to 'select' of the pointerMove-`Select()` the given objects in `e.selected` are of type "LineString" and therefor not styleable via `setStyle()` ["`.setStyle() is not a function`"]

**To Reproduce**
1. When zooming with the cursor above a selectable line the select-style is rendered but without zooming it isnt.

2. Console out` getType()` of the objects inside of `e.selected` => "LineString"

**Expected behavior**
1. Immediate render of select-Style on pointerMove/Hover

2. Expected the objects in `e.selected` to be features to call `setStyle()`

**System**

- Angular 8.0.3
- ol 5.3.3

**Screencast**

![pointerMove](https://user-images.githubusercontent.com/15933094/61454539-7a486f00-a961-11e9-944f-bbb31a8d99b2.gif)

**Comment by MiftahulxHuda** [comment]
Can I know, how you add the LineString in layer map? Whether you used a file kml?

**Comment by DwieDave** [comment]
I use vt-pbf for node.js to convert a geoJSON file to create a prebuffered (.pbf) vectorTiles server.
Which I add via `vectorTileLayer` applying the styles depending on the lines properties

**Comment by DwieDave** [comment]
Is this something i did wrong configuring the select or is it a bug?

**Comment by ahocevar** [comment]
You cannot `setStyle()` on a RenderFeature, which is the default feature class for `ol/source/MVT`. If you want to go that route, you need to configure your source like this
```js
import MVT from 'ol/format/MVT';
import Feature from 'ol/Feature';

new MVT({
  featureClass: Feature
});
```

**Comment by DwieDave** [comment]
Thanks! That solved the problem; So not an Issue! (closed)
