### ISSUE TITLE
ol.style.Icon rotation angle is wrong

### ISSUE THREAD

**Issue by Hgq1001** [openlayers/openlayers#9785]
with ol.style.Icon ，The actual rotation angle of the icon is inconsistent with the angle I set.  
How to deal with it

**Comment by blazery** [comment]
What rotation are you using?
acording to the docs [rotation ](https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html)should be provided in radians not degrees.
I had the same issue with text just a second ago
