### ISSUE TITLE
how to toggle the feature's visibility of VectorLayer ?

### ISSUE THREAD

**Issue by Jerry-goodboy** [openlayers/openlayers#9788]
I'm always frustrated when I wanna toggle the feature's visibility, because there is not any method to handle it. Only VectorLayer class has the setVisible method but the Feature class has not.

I learn some tips from this issue Toggle ol.Feature visibility #6749 , but ol's API still hasn't provided setVisible method. So here is the reason why I raise the issue again. If I wanna toggle the feature's visibility, what can I do? what is the best practice?

@twpayne @jomue @tonio @scharrier @j16sdiz

**Comment by twpayne** [comment]
@Jerry-goodboy please don't spam the developers with mentions when you need help. It's very rude. There's a discussion list for support.

**Comment by Jerry-goodboy** [comment]
> discussion

Sorry, where is the discussion list, I can't find it

**Comment by twpayne** [comment]
https://github.com/openlayers/openlayers#community and https://groups.google.com/forum/#!forum/openlayers-dev

**Comment by Jerry-goodboy** [comment]
> https://github.com/openlayers/openlayers#community and https://groups.google.com/forum/#!forum/openlayers-dev

Thanks

**Comment by Jerry-goodboy** [comment]
Anyone can help me? I still have no solution to this problem

**Comment by Jerry-goodboy** [comment]
Finally, I find the best answer to solve this problem, I am using the V5.3.0 API, so here is my solution:

* First, you have to set the layer's style option to null, all layers are best to set null;
* Second, you can use the setStyle function of the feature to control the show/hide of the feature, if it set null, the feature will not be rendered in the layer, otherwise, the feature will be rendered in the layer with its own style which you set.

Honestly speaking, I never thought of ol API will handle the problem like this, the logic confuses me a lot, I hope it will be optimized in the future.
