### ISSUE TITLE
mousePosition coords incorrect when XYZ layer wrapX=true

### ISSUE THREAD

**Issue by sowston** [openlayers/openlayers#9790]
I have a basemap XYZ layer of the entire globe with wrapX=true (the default).  If I continuously pan the layer left or right, the mousePosition coordinates increase infinitely and do not provide the correct X position (i.e. if I pan to the left past -180, the coordinates will continue to increase beyond -180 to -300, -400, -500 etc.  

Would it be possible to also allow the mousePosition to support the wrapX feature and provide back the correct X coordinate position?

**Comment by mike-000** [comment]
That is consistent with how pointer event coordinates work on a wrapping map, and tells you which copy of the world you are on.  Unlike ol/proj.transform ol/proj.toLonLat always returns normalised longitude and you can use that in the coordinateFormat function

```
new MousePosition({
  projection: 'EPSG:4326',
  coordinateFormat: function(coordinate) {
    var lonLat = toLonLat(coordinate, 'EPSG:4326')
    return lonLat.toString();
  }
});
```

**Comment by sowston** [comment]
ok got it, thats perfect.  thank u.
