### ISSUE TITLE
LineString unexpected behavior with an array of coordinates

### ISSUE THREAD

**Issue by himpatel** [openlayers/openlayers#9791]
**Describe the bug**
LineString unexpected behavior with an array of coordinates

Plnkr link
https://plnkr.co/edit/j0XkkMTr3hdH8WBW6Tma?p=preview

**To Reproduce**
Steps to reproduce the behavior. Check screenshot
![image](https://user-images.githubusercontent.com/15386655/61583721-90208480-ab59-11e9-919d-f97ed03ef037.png)

var coords = [[151.98060398811, 21.4650428879105], [155.38545671924, 15.6235261079453], [-179.6933, -29.0555], [-176.5991, -36.8406]];

			var lineString = new ol.geom.LineString(coords);
			// transform to EPSG:3857
			lineString.transform('EPSG:4326', 'EPSG:3857');

			// create the feature
			var feature = new ol.Feature({
				geometry: lineString,
				name: 'Line'
			});

			var lineStyle = new ol.style.Style({
				stroke: new ol.style.Stroke({
					color: '#ffcc33',
					width: 2
					//lineDash: [4,8]
				})
			});

			var source = new ol.source.Vector({
				features: [feature]
			});
			var vector = new ol.layer.Vector({
				source: source,
				style: [lineStyle]
			});
			map.addLayer(vector);

**Expected behavior**
Same set of coordinates draw a line correctly on Google maps
var flightPlanCoordinates = [
    {lat: 21.4650428879105, lng: 151.98060398811},
    {lat: 15.6235261079453, lng: 155.38545671924},
    {lat: -29.0555, lng: -179.6933},
    {lat: -36.8406, lng: -176.5991}
  ];

![image](https://user-images.githubusercontent.com/15386655/61583717-7c751e00-ab59-11e9-8857-77493eefff26.png)

**Comment by mike-000** [comment]
As specified that geometry doesn't cross the dateline.  To cross the dateline use

`var coords = [[151.98060398811, 21.4650428879105], [155.38545671924, 15.6235261079453], [360 -179.6933, -29.0555], [360 -176.5991, -36.8406]];
`

If you are planning to use editing interactions on features which cross the dateline set `wrapX: false` in the `ol.source.Vector` options.

**Comment by himpatel** [comment]
Appreciate your extremely quick response and putting across enhanced Plunker code. Thank you so much. It works perfectly. Never realized the line crossing the dateline. I think the code you gave should be added as a feature to LineString function/feature as a parameter. It will save some time for others.

To add to it, I found another way to get the same result from (1st answer):
https://stackoverflow.com/questions/54572040/openlayers-dateline-crossing-linestring-disappears

Just converted by co-ordinate array with this loop which also worked:
 function HandleDateline(array) {
        for (var i = 0; i < array.length ; i++) {
            if (array[i][0] > 0) {
                array[i][0] -= 360;
            }
        }
    }
