### ISSUE TITLE
CI does not create examples artifacts

### ISSUE THREAD

**Issue by ahocevar** [openlayers/openlayers#9798]
It seems that CircleCI is currently unable to build the examples. No error is triggered, but the `~/repo/build/examples` directory, which is the source for the `store_artifacts` task that runs after building the examples, is apparently empty.

**Comment by fredj** [comment]
The examples are back again, see for example:
https://circleci.com/gh/ahocevar/openlayers/294#artifacts/containers/0

I didn't investigate but I suspect #9801 to have fixes the issue.

**Comment by fredj** [comment]
I was wrong: the issue is still present:
https://circleci.com/gh/openlayers/openlayers/1753#artifacts/containers/0

For some reason the examples were correctly generated for your PR #9802

**Comment by ahocevar** [comment]
Nice, thanks for the investigation @fredj
