### ISSUE TITLE
Resurrect the Shared View example

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9799]
The previous example was lost as a result of https://github.com/openlayers/openlayers/commit/7fa2189fe997a87f28e9551242a71e1da211e5cc#diff-bfebe34154a0dfd9fc7b447fc9ed74e9  Obviously WebGL is no longer applicable but a side by side example of the use of a shared view such as for road and aerial would be useful.

**Comment by marcjansen** [comment]
Can you come up with a PR, that'd be awesome.
