### ISSUE TITLE
Loading events for Vector source are missing in the API documentation, but actually exist

### ISSUE THREAD

**Issue by IrvingWash** [openlayers/openlayers#9800]
In the API documentation you have described loading events for various source types, e.g. `tileloadstart` for XYZ source.
But such section for ol/source/Vector is missing on the website. The most interesting thing, such events do exist (`vectorloadstart`, etc).
I suggest you adding this into the documentation, because I found out about these methods only thanks to my more experienced collegue.

**Comment by ahocevar** [comment]
There is no `vectorloadstart` event. Did you mean to refer to something else?

**Comment by IrvingWash** [comment]
> There is no `vectorloadstart` event. Did you mean to refer to something else?

I have this code:
`if (layer !== null) {
      // events[0] = 'vectorloadstart'
      source.on(events[0], () => {
        this.setState({
          showLoadingError: false,
          spinnerVisibility: true,
        });
      });
      // vectorloadend
      source.on(events[1], () => {
        this.setState({
          showLoadingError: false,
          spinnerVisibility: false,
        });
      });
      // vectorloaderror
      source.on(events[2], () => {
        this.setState({
          showLoadingError: true,
        });
      });
    }`

And this works as I want.

**Comment by IrvingWash** [comment]
I have this code and it works fine. I use it to show a loading spinner.
```
    const events = ['vectorloadstart', 'vectorloadend', 'vectorloaderror']
    if (layer !== null) {
      source.on(events[0], () => {
        this.setState({
          showLoadingError: false,
          spinnerVisibility: true,
        });
      });
      source.on(events[1], () => {
        this.setState({
          showLoadingError: false,
          spinnerVisibility: false,
        });
      });
      source.on(events[2], () => {
        this.setState({
          showLoadingError: true,
        });
      });
    }
  };
```

**Comment by ahocevar** [comment]
These events must be triggered by a plugin or your application then. OpenLayers does not trigger them.
