### ISSUE TITLE
The "Limited Layer Extent" example doesn't load

### ISSUE THREAD

**Issue by mdb07a** [openlayers/openlayers#9805]
**Describe the bug**
When navigating to the "Limited Layer Extent" example page on openlayers.org, the example map data does not load in any browser I have access to (IE, Firefox, or Chrome). The map frame loads and generates the buttons, but the map content itself remains a gray static pattern. The likely cause seems to be a "401 Unauthorized" error when attempting to load the map tiles from Mapbox.

**To Reproduce**
1. Go to https://openlayers.org/en/latest/examples/layer-extent.html
2. Observe the map area near the top of the page, which will contain tiles of gray static images instead of the expected map content and functionality example.

**Expected behavior**
The map data should properly display and demonstrate the functionality the example is written to show.

**Comment by mike-000** [comment]
See #9652

**Comment by fredj** [comment]
fixed with #9964
