### ISSUE TITLE
Add an image with a polygon shape

### ISSUE THREAD

**Issue by Ilheu** [openlayers/openlayers#9809]
Hi,
I would like to add an image (with its coordinates) on a map inside a polygon shape, if it is bigger the image should be cropped and can't be outside of the polygon shape .... What should be the best option to do it ?

**Comment by ahocevar** [comment]
You'll probably want to use a [CanvasPattern](https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern) when setting the `color` or an `ol/Style/Fill`. See https://openlayers.org/en/latest/examples/canvas-gradient-pattern.html for an example
