### ISSUE TITLE
Use WKT Format read String error.

### ISSUE THREAD

**Issue by coolyzp** [openlayers/openlayers#9810]
When using openlayers to read WKT string, an error will be reported if there is only one Feature in GeometryCollection, such as  new WKT().readFeature('GEOMETRYCOLLECTION Z(LINESTRING Z(638689.3261000002 3450098.5727999993 14.596399999994901, 638689.3731488768 3450098.2765218425 14.597601194941259, 638689.4201977536 3450097.980243686 14.598802389887616, 638689.4672466302 3450097.6839655293 14.600003584833972, 638689.5142955069 3450097.387687373 14.60120477978033, 638689.5613443835 3450097.091409216 14.602405974726688, 638689.6083932603 3450096.7951310594 14.603607169673046, 638689.6554421369 3450096.498852903 14.604808364619402, 638689.7024910136 3450096.202574746 14.60600955956576, 638689.7495398903 3450095.90629659 14.607210754512117, 638689.796588767 3450095.610018433 14.608411949458475, 638689.8436376436 3450095.3137402763 14.60961314440483, 638689.8906865203 3450095.01746212 14.610814339351188, 638689.937735397 3450094.721183963 14.612015534297546, 638689.9847842737 3450094.424905807 14.613216729243904, 638690.0318331503 3450094.12862765 14.614417924190262, 638690.0788820271 3450093.8323494936 14.615619119136618, 638690.1259309037 3450093.536071337 14.616820314082975, 638690.1729797804 3450093.23979318 14.618021509029333, 638690.220028657 3450092.9435150237 14.61922270397569, 638690.2670775338 3450092.647236867 14.620423898922047, 638690.3141264104 3450092.3509587105 14.621625093868404, 638690.361175287 3450092.0546805537 14.622826288814762, 638690.4082241638 3450091.758402397 14.62402748376112, 638690.4552730405 3450091.4621242406 14.625228678707476, 638690.5023219171 3450091.165846084 14.626429873653834, 638690.5493707937 3450090.8695679274 14.627631068600191, 638690.5964196705 3450090.5732897706 14.628832263546549, 638690.6434685471 3450090.277011614 14.630033458492907, 638690.6905174238 3450089.9807334575 14.631234653439263, 638690.7375663004 3450089.6844553007 14.63243584838562, 638690.7846151772 3450089.3881771443 14.633637043331978, 638690.8316640538 3450089.0918989875 14.634838238278336, 638690.8380000005 3450089.051999999 14.634999999994761, 638690.8785672913 3450088.795597746 14.636178824797321, 638690.9254478636 3450088.4992929115 14.637541104119071, 638690.9723284361 3450088.2029880774 14.638903383440821, 638691.0192090084 3450087.906683243 14.640265662762571, 638691.0660895808 3450087.610378409 14.641627942084321, 638691.1129701532 3450087.3140735743 14.642990221406071, 638691.1598507256 3450087.01776874 14.644352500727821, 638691.2067312979 3450086.721463906 14.645714780049572, 638691.2536118703 3450086.4251590716 14.647077059371323, 638691.3004924427 3450086.1288542375 14.648439338693073, 638691.347373015 3450085.832549403 14.649801618014823, 638691.3942535874 3450085.536244569 14.651163897336573, 638691.4411341598 3450085.2399397343 14.652526176658323, 638691.4880147321 3450084.9436349003 14.653888455980074, 638691.5348953045 3450084.6473300657 14.655250735301824, 638691.5817758769 3450084.3510252316 14.656613014623574, 638691.6286564493 3450084.0547203976 14.657975293945324, 638691.6755370216 3450083.758415563 14.659337573267074, 638691.722417594 3450083.462110729 14.660699852588824, 638691.7692981664 3450083.1658058944 14.662062131910574, 638691.8161787387 3450082.8695010603 14.663424411232326, 638691.8630593112 3450082.573196226 14.664786690554076, 638691.9099398835 3450082.2768913917 14.666148969875826, 638691.9568204558 3450081.980586557 14.667511249197576, 638692.0037010283 3450081.684281723 14.668873528519326, 638692.0505816006 3450081.387976889 14.670235807841076, 638692.097462173 3450081.0916720545 14.671598087162826, 638692.1443427454 3450080.7953672204 14.672960366484576, 638692.1912233178 3450080.499062386 14.674322645806326, 638692.2381038901 3450080.202757552 14.675684925128076, 638692.2849844625 3450079.9064527173 14.677047204449826, 638692.3318650349 3450079.610147883 14.678409483771576, 638692.3787456072 3450079.3138430486 14.679771763093328, 638692.4256261796 3450079.0175382146 14.681134042415078, 638692.472506752 3450078.7212333805 14.682496321736828, 638692.5193873243 3450078.424928546 14.683858601058578, 638692.5662678967 3450078.128623712 14.685220880380328, 638692.6131484691 3450077.8323188773 14.686583159702078, 638692.6600290415 3450077.5360140433 14.687945439023828, 638692.7069096138 3450077.2397092087 14.689307718345578, 638692.7537901863 3450076.9434043746 14.690669997667328, 638692.8006707586 3450076.6470995406 14.692032276989078, 638692.8475513309 3450076.350794706 14.693394556310828, 638692.8944319034 3450076.054489872 14.69475683563258, 638692.9413124757 3450075.7581850374 14.69611911495433, 638692.988193048 3450075.4618802033 14.69748139427608, 638693.0350736205 3450075.165575369 14.69884367359783, 638693.0819541928 3450074.8692705347 14.70020595291958, 638693.1288347652 3450074.5729657 14.70156823224133, 638693.1757153376 3450074.276660866 14.70293051156308, 638693.22259591 3450073.980356032 14.70429279088483, 638693.2694764823 3450073.6840511975 14.70565507020658, 638693.3163570546 3450073.3877463634 14.70701734952833, 638693.3632376271 3450073.091441529 14.70837962885008, 638693.4101181994 3450072.795136695 14.70974190817183, 638693.4189999998 3450072.739 14.710000000006403, 638693.4562416861 3450072.4987132987 14.710297376706281, 638693.5021882124 3450072.2022621906 14.710664261980492, 638693.5481347385 3450071.905811082 14.711031147254703, 638693.5940812647 3450071.609359974 14.711398032528914, 638693.6400277908 3450071.3129088655 14.711764917803123, 638693.685974317 3450071.0164577574 14.712131803077334, 638693.7319208431 3450070.720006649 14.712498688351545, 638693.7778673694 3450070.423555541 14.712865573625756, 638693.8238138955 3450070.1271044323 14.713232458899967, 638693.8697604217 3450069.8306533243 14.713599344174177, 638693.9157069478 3450069.5342022157 14.713966229448388, 638693.961653474 3450069.2377511077 14.7143331147226, 638694.0076000001 3450068.941299999 14.71469999999681))')

**Comment by fredj** [comment]
your WKT doesn't seems to be valid: the opening parentheses are not closed

**Comment by coolyzp** [comment]
Sorry,I copied WKT again.

**Comment by coolyzp** [comment]
> 
> 
> your WKT doesn't seems to be valid: the opening parentheses are not closed

Sorry,I copied WKT again.

**Comment by fredj** [comment]
I've created a codesandbox from your comment and the feature is correctly parsed:
https://codesandbox.io/s/gallant-diffie-5cxch
