### ISSUE TITLE
VectorLayer loadFeatures is not defined

### ISSUE THREAD

**Issue by DwieDave** [openlayers/openlayers#9811]
So i wanted to add a geoJSON source using the VectorLayer (to fetch the json once and use it for the rest of the time):
**Thats how I added the Layer:**
<img width="514" alt="vectorlayer" src="https://user-images.githubusercontent.com/15933094/62124154-c8e2fb00-b2c9-11e9-8bfd-93ee5e1a2531.png">

**This error message I'm getting:**
![image](https://user-images.githubusercontent.com/15933094/62124132-bf599300-b2c9-11e9-93e0-580f4e8255ca.png)

When I use a VectorTileLayer its working fine but i get performance issues since OL is pulling the geoJSON on tile-change which is unnecessary.

Do i have to configure something different?
I did not find anything in the Docs.

**System**
Angular 8
ol 5.3.3

**Comment by fredj** [comment]
You code looks good but it's hard to tell without a minimal example.
Can you please create one on https://codesandbox.io or similar?

**Comment by DwieDave** [comment]
I actually had my import of VectorSource wrong which led to this error!
Thanks for your fast reply
