### ISSUE TITLE
PointerInteraction handleMoveEvent documentation bug

### ISSUE THREAD

**Issue by michalzielanski** [openlayers/openlayers#9814]
[`handleMoveEvent`](https://github.com/openlayers/openlayers/blob/v5.3.0/src/ol/interaction/Pointer.js#L143) function is not called when dragging. However, the [documentation](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Pointer-PointerInteraction.html) says it is:
> Function handling "move" events. This function is called on "move" events, **also during a drag sequence (so during a drag sequence both the handleDragEvent function and this function are called)**.

Documentation should be corrected.

**Comment by michalzielanski** [comment]
Up

**Comment by ahocevar** [comment]
Actually the documentation is correct. See https://codesandbox.io/s/simple-qeud6 and look at the log.

**Comment by michalzielanski** [comment]
Indeed, when only handleMoveEvent is defined it is as the documentation says, but when handleDownEvent and handleDragEvent are additionally defined, handleMoveEvent is no longer invoked during dragging.

See https://codesandbox.io/s/simple-rg6lz.

**Comment by ahocevar** [comment]
@michalzielanski You're absolutely right! Would you be willing to create a pull request for a documentation fix?
