### ISSUE TITLE
ol.interaction.RotateEventType: Rotate Angle Issue

### ISSUE THREAD

**Issue by rmaddu** [openlayers/openlayers#9815]
Below is the Psuedo code. We are calculating the rotate value for Text feature.
**Observation:** When we rotate the Text from Right to Left, the calculated angle is negative always.
**Expectation**: We are expecting positive value. But we are getting negative value. 
In example (http://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html), when we rotate from right to left, rotate angle is positive. How to achieve this?

ol.interaction.RotateEventType = {
    /**
     * Triggered upon feature rotation start.
     * @event ol.interaction.Rotate.Event#rotatestart
     * @api
     */
    ROTATESTART: 'rotatestart',
    /**
     * Triggered upon feature rotation.
     * @event ol.interaction.Rotate.Event#rotating
     * @api
     */
    ROTATING: 'rotating',
    /**
     * Triggered upon feature rotation end.
     * @event ol.interaction.Rotate.Event#rotateend
     * @api
     */
    ROTATEEND: 'rotateend'
};

 var interaction = Ext.Factory.mapinteraction({
            type: 'rotate',
            features: ....
        })
        
        interaction.on('rotatestart', me.handleRotateStart, me);
        interaction.on('rotating', me.handleRotating, me);
        interaction.on('rotateend', me.handleRotateEnd, me);

handleRotateStart: function (evt) {
...}

handleRotating: function (evt) {
...
}

 handleRotateEnd: function (evt) {
....
}

Attached the Image: 
                         
![Rotate](https://user-images.githubusercontent.com/52063294/62283058-58291380-b46e-11e9-8831-93d9a23d0ce7.JPG)
                        **First Text:** No rotation. Ready for rotation.
			**Second Text:** Rotated from right to left. By seeing the Text, we can assume that the text is rotated 30 degrees(approximately) from the horizontal (X-axis) axis. But the calculated angle is negative. How to get the positive value here?

**Comment by mike-000** [comment]
ol-ext issues should be raised at https://github.com/Viglino/ol-ext/issues but that is correct and is consistent with rotation measurement elsewhere in OpenLayers and JavaScript.  Clockwise rotation is positive, counter-clockwise is negative.

**Comment by rmaddu** [comment]
From next time onwards, I will post it there. 
Our question is  - do we have any alternative to get negative for clockwise and positive for counter-clockwise?
Also, how they have achieved in http://viglino.github.io/ol-ext/examples/interaction/map.interaction.transform.html example?

**Comment by mike-000** [comment]
You could simply negate the result.  The ol-ext result is the opposite to normal practice but notice how the code negates the result when applying it `e.feature.set('angle', startangle - e.angle); `
