### ISSUE TITLE
Unclickable zone with features/style/icons

### ISSUE THREAD

**Issue by mightymamont** [openlayers/openlayers#9818]
The part of feature's icon is not clickable (zone depends on anchor position).

Step 1. Create map with layer and feature.
Image size should be 300x100 px or larger.
```
let styleImage = new Icon({
	anchor: styleConfig.anchor || [0.5, 0.5],
	offset: [0,0],
	opacity: 1.0,
	scale: 1.0,
	rotation: 0.0,
	rotateWithView: true,
	anchorXUnits: 'fraction',
	anchorYUnits: 'fraction',
	size: imgSize,
	crossOrigin: 'anonymous',
	src: url
        }),
	style = new Style({image: styleImage});
					
        feature.setStyle(style);
```

Step 2. Map click event shoud be handled.
Step 3. Hover cursor pointer to icon and click - only part of image will be clickable.
![Снимок экрана (26)_LI](https://user-images.githubusercontent.com/3338049/62372891-43698000-b541-11e9-8fa7-5f540462e12b.jpg)

**Comment by ahocevar** [comment]
By default, hit detection only covers a 100x100px Square around the geometry. If you want more, configure your `ol/layer/Vector` with a `renderBuffer` > `100`.
