### ISSUE TITLE
FeatureLoader loads duplicate features on zoom in and out, with loading strategy set to tile

### ISSUE THREAD

**Issue by stevanpa** [openlayers/openlayers#9819]
**Describe the bug**
In my app I create a **GroupLayer** with various **Layers** that are rendered based on zoom levels. At the lower zoom levels, a **VectorLayer** with a **ClusterSource** is rendered. The source of the **ClusterSource** is based on a **VectorSource** with a **FeatureLoader** function and a **TileGrid LoadingStrategy**. I use the TileGrid LoadingStrategy instead of BBOX LoadingStrategy, because the Esri service that I use has a limit on the number of Features it can return in one call.

Initially the **Features** are loaded correctly. But when I zoom in and out the **GroupLayer** starts displaying duplicate, triplicate and quadruplicate features. Upon taking a closer look I see that zooming in and out, triggers the **FeatureLoader** function for the whole visible extent.

Is this a bug or a feature?

**To Reproduce**
I use the **FeatureLoader** below and I based it on one of the examples from the OL site https://openlayers.org/en/latest/examples/vector-esri.html
``` TypeScript
return (extent, resolution, projection) => {
    let url = `${this.url}/${this.layerId}${this.urlPostFix}&geometry=`;
    url += `${encodeURIComponent(`{xmin:${extent[0]},ymin:${extent[1]},xmax:${extent[2]},ymax:${extent[3]}}`)}`;
    if (this.queryString !== '') {
        url += this.queryString;
    }
    url += `&geometryType=esriGeometryEnvelope`;
    url += `&inSR=${this.epsgNr}`;
    url += `&outFields=*`;
    url += `&outSR=${this.epsgNr}`;

    this.http.get(url).subscribe(result => {
        const features = new EsriJSON().readFeatures(result, {
            featureProjection: projection
        });
        if (features.length > 0) {
            this.vectorSource.addFeatures(features);
        }
    });
};
```

**Expected behavior**
My expectation was that the **FeatureLoader** wouldn't be triggered for the **TileGrid** parts that have already been loaded. That is why a loading strategy has to be defined, right?

**Work around**
I did find a work around for the issue, but I am not sure if this is correct? I basically use the **extent** that has been passed on to the **FeatureLoader** to check if **Features** already exist in the **VectorSource**. If not I load the **Features** from the **FeatureLoader**. Is there an other way of doing this correctly?
``` TypeScript
return (extent, resolution, projection) => {
    let url = `${this.url}/${this.layerId}${this.urlPostFix}&geometry=`;
    url += `${encodeURIComponent(`{xmin:${extent[0]},ymin:${extent[1]},xmax:${extent[2]},ymax:${extent[3]}}`)}`;
    if (this.queryString !== '') {
        url += this.queryString;
    }
    url += `&geometryType=esriGeometryEnvelope`;
    url += `&inSR=${this.epsgNr}`;
    url += `&outFields=*`;
    url += `&outSR=${this.epsgNr}`;

    const featuresInExtent = this.vectorSource.getFeaturesInExtent(extent);

    this.http.get(url).subscribe(result => {
        const features = new EsriJSON().readFeatures(result, {
            featureProjection: projection
        });
        if (features.length > 0 && featuresInExtent.length === 0) {
            this.vectorSource.addFeatures(features);
        }
    });
};
```

**Comment by ahocevar** [comment]
This usually happens when the features you get from the server do not have a feature id.

**Comment by mike-000** [comment]
If the purpose of the loading strategy is to restrict the extent of individual loads to avoid exceeding the feature limit the grid can be restricted to the minimum zoom level which satisfies that.  The service in the example has a limit of 1000 features and requires grid zoom level 9 to keep below the limit for all tiles.  Once loaded no further requests are made for an extent.  The loader should avoid making requests outside the known extent of the data to prevent large numbers of unnecessary requests if zooming out to a global view.  https://codesandbox.io/s/vector-esri-v21jl

**Comment by stevanpa** [comment]
> This usually happens when the features you get from the server do not have a feature id.

That was it! Once I set the feature id for the features the problem doesn't arise anymore.

Thank you very much. 😃
