### ISSUE TITLE
Enable regeneration of image in ol.style.RegularShape

### ISSUE THREAD

**Issue by dnsdhrj** [openlayers/openlayers#9820]
### The problem
There's semantic error with `ol.style.RegularShape`.
(refer to #7398, note that `Circle` is subclass of `RegularShape`)

### Example
Although you can change a color of `Fill` of `RegularShape`, it doesn't regenerate image. This made some developers like me debug whole day long.

### Detail
`RegularShape` has no way to receive event when properties of its `Fill` or `Stroke` instance has changed.

### Considerations (these are just my thoughts)
- Making `Fill` and `Stroke` extend `BaseObject` (for event subscription) might cause slowdown.
- Internally calling `render` function whenever a property of `RegularShape` has changed (already implemented at [ol.style.Circle.setRadius](https://github.com/openlayers/openlayers/blob/c767091faf7de8340aa3eb06ede5930e519c01ac/src/ol/style/Circle.js#L61)) might cause slowdown under some circumstances.
- Creating new instance of `RegularShape` (which is a working solution) would not solve this bug-prone developing situation.

### The solution
Let developers choose when to regenerate image, by exposing `RegularShape.render` method from protected to public. Also, I suggest adding setter methods to `RegularShape` for dynamically changing its properties. I'll submit PR on this issue when ready.

**Comment by ahocevar** [comment]
The long term goal is to remove all rendering from the `ol/style` package entirely. It should be the responsibility of the renderer. So an API around rendering where it should not happen should at least not get an `@api` annotation. Simply removing the `@protected` annotation should be fine.

**Comment by dnsdhrj** [comment]
Oh I see.. So setter methods should be added after the renderer work is done, I suppose?
I'll just put setter methods in PR, and tell me if I should get rid of them.

**Comment by dnsdhrj** [comment]
dummy comment.
