### ISSUE TITLE
OSM Vector Tiles example

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9822]
The OSM Vector Tiles example no longer works as the old Mapzen service has been transferred to 
`https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}`  I am willing to do a PR but a new API key will be needed.  While I could use one created via my Github account, if it is to be managed by the development team it must be created by them at https://developers.nextzen.org/

**Comment by ThomasG77** [comment]
FYI, https://github.com/openlayers/openlayers/issues/7672 but it's like you: if no API key created for the OpenLayers org, can't make the fix/PR

**Comment by mike-000** [comment]
> FYI, #7672 but it's like you: if no API key created for the OpenLayers org, can't make the fix/PR

Here's a codesanbox of the fix temporarily using a key I generated (but could disable) https://codesandbox.io/s/osm-vector-tiles-w8j7z  It would be good to keep the example as I think its the only one using topojson vector tiles.
