### ISSUE TITLE
vector tile geoJSON format from tile.nextzen.org

### ISSUE THREAD

**Issue by gertcuykens** [openlayers/openlayers#9825]
mvt and topojson are working but geojson from nextzen doesn't work in openlayers only in tangram
example tile: https://tile.nextzen.org/tilezen/vector/v1/all/12/1207/1538.json?api_key=...
I assume halve the world is using one sort of vector tile geoJSON format the other halve some other vector tile geoJSON format ?
Can you confirm this please that openlayers expect different kind of geojson and point me to the docs? Thx
 
```js
import Map from 'ol/Map.js';
import View from 'ol/View.js';
import VectorTileFormat from 'ol/format/GeoJSON.js';
// import VectorTileFormat from 'ol/format/TopoJSON.js';
// import VectorTileFormat from 'ol/format/MVT.js';
import VectorTileLayer from 'ol/layer/VectorTile.js';
import {fromLonLat} from 'ol/proj.js';
import VectorTileSource from 'ol/source/VectorTile.js';
import {Fill, Stroke, Style} from 'ol/style.js';

var roadStyleCache = {};
var roadColor = {
  'major_road': '#776',
  'minor_road': '#ccb',
  'highway': '#f39'
};
var buildingStyle = new Style({
  fill: new Fill({
    color: '#666',
    opacity: 0.4
  }),
  stroke: new Stroke({
    color: '#444',
    width: 1
  })
});
var waterStyle = new Style({
  fill: new Fill({
    color: '#9db9e8'
  })
});
var roadStyle = function(feature) {
  var kind = feature.get('kind');
  var railway = feature.get('railway');
  var sort_key = feature.get('sort_key');
  var styleKey = kind + '/' + railway + '/' + sort_key;
  var style = roadStyleCache[styleKey];
  if (!style) {
    var color, width;
    if (railway) {
      color = '#7de';
      width = 1;
    } else {
      color = roadColor[kind];
      width = kind == 'highway' ? 1.5 : 1;
    }
    style = new Style({
      stroke: new Stroke({
        color: color,
        width: width
      }),
      zIndex: sort_key
    });
    roadStyleCache[styleKey] = style;
  }
  return style;
};

var map = new Map({
  layers: [
    new VectorTileLayer({
      source: new VectorTileSource({
        attributions: '',
        format: new VectorTileFormat({
          layerName: 'osm',
          layers: ['water', 'roads', 'buildings']
        }),
        minZoom: 12,
        maxZoom: 12,
        url: 'https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}.json?api_key=...'
        // url: 'https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}.topojson?api_key=...'
        // url: 'https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}.mvt?api_key=...'
      }),
      style: function(feature, resolution) {
        switch (feature.get('osm')) {
          case 'water': return waterStyle;
          case 'roads': return roadStyle(feature);
          case 'buildings': return (resolution < 10) ? buildingStyle : null;
          default: return null;
        }
      }
    })
  ],
  target: 'map',
  view: new View({
    center: fromLonLat([-74.0064, 40.7142]),
    minZoom: 12,
    maxZoom: 12,
    zoom: 12
  })
});
```

**Comment by mike-000** [comment]
`.json` is returning an object containing geojsons, one for each of the "layers" supported by `.topojson`.  It would need a custom tileLoadFunction to read features from each, so

            source: new VectorTileSource({
              attributions: '',
              format: new TopoJSON({
                layerName: 'layer',
                layers: ['water', 'roads', 'buildings']
              }),
              maxZoom: 19,
              url: 'https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}.topojson?api_key=' + key
            }),


would become

            source: new VectorTileSource({
              attributions: '',
              format: new GeoJSON(),
              maxZoom: 19,
              url: 'https://tile.nextzen.org/tilezen/vector/v1/all/{z}/{x}/{y}.json?api_key=' + key,
              tileLoadFunction: function(tile, url) {
                tile.setLoader(function(extent, resolution, projection) {
                  fetch(url).then(function(response) {
                    response.text().then(function(data) {
                      const jsons = JSON.parse(data);
                      const format = tile.getFormat();
                      const layers = ['water', 'roads', 'buildings'];
                      const features = [];
                      layers.forEach(function(layer) {
                        const layerFeatures = format.readFeatures(jsons[layer], {
                          featureProjection: projection
                        });
                        layerFeatures.forEach(function(feature) {
                          feature.set('layer', layer);
                          features.push(feature);
                        });
                      });
                      tile.setFeatures(features);
                    });
                  });
                });
              }
            }),

**Comment by gertcuykens** [comment]
Thx getting closer but I now have this error when trying the above?
```
Uncaught TypeError: Cannot read property 'getUnits' of null
    at equivalent (proj.js:399)
    at loop (VectorTileLayer.js:182)
    at CanvasVectorTileLayerRenderer.createReplayGroup_ (VectorTileLayer.js:169)
    at CanvasVectorTileLayerRenderer.getTile (VectorTileLayer.js:117)
    at CanvasVectorTileLayerRenderer.prepareFrame (TileLayer.js:187)
    at CanvasVectorTileLayerRenderer.prepareFrame (VectorTileLayer.js:143)
    at CanvasMapRenderer.renderFrame (Map.js:157)
    at Map.renderFrame_ (PluggableMap.js:1226)
    at Map.<anonymous> (PluggableMap.js:193)
```

**Comment by mike-000** [comment]
My code was for OL6.  OL5 has a `setProjection` method which must be called.  This code will work for both versions

              tileLoadFunction: function(tile, url) {
                if (tile.setProjection) { tile.setProjection(map.getView().getProjection()); }
                tile.setLoader(function(extent, resolution, projection) {
                  fetch(url).then(function(response) {
                    response.text().then(function(data) {
                      const json = JSON.parse(data);
                      const format = tile.getFormat();
                      const features = [];
                      ['water', 'roads', 'buildings'].forEach(function(layer){
                        const layerFeatures = format.readFeatures(json[layer], {
                          featureProjection: projection || tile.getProjection()
                        });
                        layerFeatures.forEach(function(feature){
                          feature.set('layer', layer);
                          features.push(feature);
                        });
                      });
                      tile.setFeatures(features);
                    });
                  });
                });
              }

**Comment by gertcuykens** [comment]
Works thx!
