### ISSUE TITLE
TextStyle use feature property as text

### ISSUE THREAD

**Issue by simonseyock** [openlayers/openlayers#9828]
It would be nice if the `TextStyle` could read a property of the feature as the text value of the style. This would make it easy to create labels for given vector sources.

Imagine you have a vectorsource where all features have a property `label` which you would like to display on the map. Currently you would define a featureStyleFunction that returns a different style for every feature, possibly cloning a common style to use the same configurations everywhere.

It would be nicer if you could just set an option `textProperty` or similar of the TextStyle to `'label'` which will then be used as text.

I just looked briefly into the code but this could maybe be done in the CanvasTextBuilder:
https://github.com/openlayers/openlayers/blob/ec10cda088cdfc447b0e94fce8fccf6d9d5d9ae0/src/ol/render/canvas/TextBuilder.js#L151
https://github.com/openlayers/openlayers/blob/ec10cda088cdfc447b0e94fce8fccf6d9d5d9ae0/src/ol/render/canvas/TextBuilder.js#L445

Apart from making it more comfortable to define a `TextStyle` it also might improve performance because there is no need to create or clone a new style for every feature.

If this is desired I can implement this as it is needed in our software as well.

**Comment by mike-000** [comment]
Would it improve performance over the current normal practice to which uses a single style?  https://openlayers.org/en/latest/examples/vector-label-decluttering.html

**Comment by simonseyock** [comment]
I was not aware that this does work. I think the performance gain would than be negligible and it would only be a little more convenient. I don't know if that is worth it.
