### ISSUE TITLE
Inconsistent forward and reverse EPSG:4326/EPSG:3857 transforms above latitude 85.

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9836]
As discussed in #9832  Obviously using proj4 is a workaround, but surely applying forward and reverse transforms should always end back where you started?  The difference can be seen in these examples when panning north https://codesandbox.io/s/scalerings-41dzr https://codesandbox.io/s/scalerings-4zfij  I have checked similar code originally written for OL3 where the behaviour is like the current proj4 example until version 3.18.0

**Comment by ahocevar** [comment]
Projections like EPSG:3857 have a validity extent, in this case from about -85 to 85 degrees in latitude. For coordinates outside the validity extent, forward and reverse cannot end up where you started. This is actually one of the problems in proj4, and the reason why I prefer to use mproj (although I'm a co-author/maintainer of proj4).

Closing as wontfix.
