### ISSUE TITLE
Select Interaction throws error on first select action with Vector Tile Layer Render Feature

### ISSUE THREAD

**Issue by defiantgoat** [openlayers/openlayers#9840]
**Describe the bug**
When using a Select interaction with a Vector Tile Layer (such as Mapbox), on the first Select that returns a RenderFeature an error is thrown. 

It seems RenderFeature object is passed to the listen function in ol/events.js. RenderFunction as the target doesn't seem to have an addEventListener method and an error is thrown.

![Screen Shot 2019-08-09 at 9 55 47 am](https://user-images.githubusercontent.com/3229911/62744911-16aaf080-ba8c-11e9-89d3-1d57e0f9205f.png)
![IMG_3567](https://user-images.githubusercontent.com/3229911/62744969-5bcf2280-ba8c-11e9-9270-e9225153a669.JPG)

**To Reproduce**
Create a simple mapping application with a Map object, a Vector Tile Layer (I was using Mapbox) and a Select Interaction. On the first click on a vector tile feature the error is thrown. Subsequent clicks seem to work however and select the render feature.

**Expected behavior**

I would expect RenderFeature and Feature would work the same with Select Interaction.

**Comment by defiantgoat** [comment]
This sample below will reproduce the error.
```
<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/css/ol.css" type="text/css">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
    </style>
    <script src="https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.3.0/build/ol.js"></script>
    <title>OpenLayers example</title>
  </head>
  <body>
    <h2>My Map</h2>
    <div id="map" class="map"></div>
    <script type="text/javascript">
     
     var key = 'YOUR_MAPBOX.KEY';

      var select = new ol.interaction.Select();

      select.on('select', ()=> {
        console.log('this will fire correctly after the first interaction throws an error with Render Feature')
      })

      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.VectorTile({
            source: new ol.source.VectorTile({
              attributions: '© <a href="https://www.mapbox.com/map-feedback/">Mapbox</a> ' +
                '© <a href="https://www.openstreetmap.org/copyright">' +
                'OpenStreetMap contributors</a>',
              format: new ol.format.MVT(),
              url: 'https://{a-d}.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/' +
                  '{z}/{x}/{y}.vector.pbf?access_token=' + key
            })
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([37.41, 8.82]),
          zoom: 4
        }),
        interactions: [
          select
        ]
      });

    </script>
  </body>
</html>
```

**Comment by fredj** [comment]
Same issue with version 6.0.0-beta.12: https://codesandbox.io/s/rendertile-select-oqs9d

**Comment by ahocevar** [comment]
The documented type for `features` of the `Select` interaction is a collection of `ol/Feature` instances. No surprise that it fails with `ol/RenderFeature`.

Using the Select interaction on VectorTile layers also will not give you the expected results near tile boundaries. The recommended way of selecting/highlighting in VectorTile layers is shown in https://openlayers.org/en/latest/examples/vector-tile-selection.html.

**Comment by defiantgoat** [comment]
@ahocevar Yes I have seen the example and read the documentation. In the large application I am working on there are already Select interactions attached to the map and many layers of which Vector Tile Layers are now being introduced.

I have found a way to bypass the initial error thrown on the first `select` that returns a `ol/RenderFeature` by using convoluted logic within the `condition` option of the `Select` interaction. I've also tried another scenario where a second `Pointer` interaction is introduced to handle `RenderFeatures` and leaves the existing `Select` for other `ol/Feature` selection. Both of these are ok solutions.

However, it still doesn't deny that there is a bug if `Select` will accept something other than an `ol/Feature` if it is the only thing it is meant to handle. It also doesn't explain why the error is thrown the first time and then the `Select` function actually starts working with RenderFeatures on subsequent clicks, highlighting them like regular Features.

I've found a work around, but I'd still suggest that this is a **bug** and needs to be fixed.

**Comment by defiantgoat** [comment]
Also, this documentation [ol/interaction/Select](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select.html) states that the filter function will take an `RenderFeature`. 

I guess I could write logic in the filter function to handle the RenderFeature as well, but by doing something else with it rather than passing it off to the SelectEvent.

**Comment by ahocevar** [comment]
You can also configure your `ol/format/MVT` to create instances of `ol/Feature` instead of `ol/render/Feature`:
```js
import Feature from 'ol/Feature';
import MVT from 'ol/format/MVT';

const format = new MVT({featureClass: Feature});
```

**Comment by defiantgoat** [comment]
@ahocevar That's great! I'm not sure how I missed that. Thank you.

**Comment by defiantgoat** [comment]
@ahocevar I just realized that could be a major performance issue. I guess that is why RenderFeature was created. However, I appreciate knowing it is an option.
