### ISSUE TITLE
My site doesn't work in IE but works fine in Chrome

### ISSUE THREAD

**Issue by urbancamo** [openlayers/openlayers#9842]
**Describe the bug**
Site not working in IE

**To Reproduce**
1. Go to http://www.wota.org.uk/mapping/index.html using IE or Edge

**Expected behavior**
I can't determine why the map tiles do not display in Edge or IE but do display in Chrome. I'd be really grateful for some clues please?

**Comment by mike-000** [comment]
You have a missing `//` in the thunderforest url which should begin `https://`  Chrome will tolerate that, while other browsers don't.

**Comment by urbancamo** [comment]
Hi @mike-000 

Many thanks for the tip, I'm guessing I copied that code from somewhere, but you are spot on, it works great now.

Hopefully this will help others who experience that issue.

Many thanks, Mark.
