### ISSUE TITLE
Create a simple method for adding a marker to a map

### ISSUE THREAD

**Issue by cwillmes** [openlayers/openlayers#9843]
*Objective*:
Currently, it is fairly hard to add a simple marker for a point coordinate to an OL map.

The most simple take on this, I can find goes like:

```
var layer = new ol.layer.Vector({
  source: new ol.source.Vector({
    features: [new ol.Feature({
      geometry: new ol.geom.Point(ol.proj.fromLonLat([6.937, 50.926]))})]})});
 map.addLayer(layer);
```

This is obviously quite some things to learn for beginners who just want to try to do a quick "hello world" in openlayers.

The leaflet equivalent for example looks like this:

```
var marker = L.marker([50.926, 6.937]).addTo(map);
```

*possible solution*:
Create a method/function like the `marker` function in leaflet to wrap all the complexity, shown in the example above, to make adding a marker to a map more simple.

From experience I can tell, that beginners chose leaflet over openlayers mostly because of the (unnecessary) complexity for basic things like adding a marker to a map in openlayers.

**Comment by mike-000** [comment]
I think anyone needing a lot of markers would simply create their own "one line" method by making your code (and there is more to consider, such as how to style the marker as most developers would want to choose icons to suit their site) into a basic javascript function (or with slightly more advanced javascript a custom method) taking a lonlat argument.  Here is a demo of setting up and using a custom `addMarker` method  https://codepen.io/mike-000/pen/eqPrNo  If no style is specified it will use the default style for kml features.

**Comment by cwillmes** [comment]
> I think anyone needing a lot of markers would simply create their own "one line" method by making your code (and there is more to consider, such as how to style the marker as most developers would want to choose icons to suit their site) into a basic javascript function (or with slightly more advanced javascript a custom method) taking a lonlat argument. Here is a demo of setting up and using a custom `addMarker` method https://codepen.io/mike-000/pen/eqPrNo If no style is specified it will use the default style for kml features.

Are you supporting this feature request? Or is that an argument against this request?
If the first, thanks! Having to write an own function is indeed to much to ask from beginners (like undergrad Geography students).
If you say, it is not necessary because you could write an own function, then I ask you, why should OL not provide such an one-liner function via its api?

**Comment by mike-000** [comment]
I don't think it would be useful in real world situations as developers would need to style markers to suit their applications (as in this example https://openlayers.org/en/master/examples/icon-color.html).  A downside of greater flexibility is it needs slightly more code, but anyone attempting to use any mapping library should know enough javascript to put code they use repeatedly into a function.  Maybe the example should be revised to reflect that? https://codepen.io/mike-000/pen/QeJZKX

**Comment by cwillmes** [comment]
Ok, I see. But how is a simple function for adding a marker not useful? Your example is even more complex to understand for beginners, it has even more lines, than the example I brought up initially.
I ask for additional functionality, to lower the entrance hurdle for beginners.
This should not interfere with existing functionality and practices. Pros like you can continue to hack what and how they want and feel like.

**Comment by frasersab** [comment]
I think some of these problems could also be overcome with some better tutorials as there is definitely a clear logical order to do things in openlayers, understand them would help. I think having multiple ways to do the same thing could become messy.

But maybe it could be worth writing your own 'openlayers-lite' that wraps everything you've talked about into something simple for the simple use cases

**Comment by Siedlerchr** [comment]
Have you looked at ol-ext?
http://viglino.github.io/ol-ext/

**Comment by frasersab** [comment]
Hi Siedlerchr, no I haven't. Looks like there's some really great stuff there.

But the reason I've made this issue is because I want to bring the default behavior of openlayers to what is the standard behavior for maps and something that immediately felt wrong to me.

I do think maybe the solution may need to be a bit more in-depth that what I initially suggested. But the accessibility should be separate from the mouse hover mechanism. Just like all other maps out there.
