### ISSUE TITLE
osm bubble-wrap

### ISSUE THREAD

**Issue by gertcuykens** [openlayers/openlayers#9845]
Can a osm specification style be made please. Going from raw osm data to vector tiles is already the wild wild west where everybody uses there custom properties. On top of that it takes a lot of clever thinking and resources to handle huge amount of raw osm data

https://github.com/tilezen/vector-datasource
https://github.com/paulmach/osmzen (go port)

If you made it this far then it becomes even more complex with the styling

https://github.com/tangrams/bubble-wrap

In my opinion openlayers is the best design compared to mapbox and tangrams, but writing osm styling from scratch is a huge amount of work making openlayers not a option. I think it's worth investing to make that process less painful by having a repo dedicated to go from raw osm to complete bubble-wrap like example for openlayers.

**Comment by ThomasG77** [comment]
There are converters that do Mapbox GL JSON styles to OpenLayers styles e.g https://github.com/terrestris/geostyler and https://github.com/openlayers/ol-mapbox-style
If you go through Tangrams styling (based on YAML), there are no converter to OpenLayers and you will need to do everything by hand.

**Comment by gertcuykens** [comment]
Agree but does Mapbox GL styles are based on proprietary vector tiles and have very different propertie fields then for example https://github.com/tilezen/vector-datasource. So as long there is no standard in converting osm to tile vector properties then you are as good as forced to use the client that comes with the tiles.

**Comment by mike-000** [comment]
All the tile services which include OSM data use different data structures and field names so each needs its own style function in OpenLayers.  Mapbox GL style json has become a defacto standard and if there is one available olms should be able to make it usable in OpenLayers.  For Mapzen see https://gis.stackexchange.com/questions/250989/mapbox-gl-js-styles-that-use-mapzens-vector-tiles  With the introduction of ESRI's OSM vector tile service there is another alternative to Mapzen which doesn't need an API key comes with a prebuilt (but editable) style https://developers.arcgis.com/vector-tile-style-editor/3e1a00aeae81496587988075fe529f71/quick which will work in OpenLayers https://codepen.io/mike-000/pen/pozgeBp

**Comment by ThomasG77** [comment]
> What I am trying to explain is that a large part of openlayers depend on tiles so especially with complex osm tiles you are always at the mercy of a tile vendor unless openlayers has a solution that helps you make your own osm tiles or collaborate with others to at least have a tile spec that guarantees certain properties in a osm vector tile.

OpenLayers is only one of the various client side libraries. All the JavaScript clients suffer from the same issue as it's not their roles. They only consume data sources and tiles are one of them. You may read about this vector tiles schema issue, in particular intellectual properties, at https://github.com/osm2vectortiles/osm2vectortiles/issues/387
Due to this history, the openmaptiles project has been created with a particular schema with an open source license e.g https://openmaptiles.org/schema/
You can self host vector tiles with this schema using openmaptiles repositories or use third party services providing vector tiles with this schema. There are Mapbox GL styles associated with this schema already available.

**Comment by gertcuykens** [comment]
Thanks for the examples, I understand that https://openmaptiles.org/schema/ and https://docs.mapbox.com/mapbox-gl-js/style-spec is the closest we have to a standard and https://github.com/openlayers/ol-mapbox-style is the way forward. Still can't believe that in case of generating tiles, importing osm into a database and launch a bunch of sql scripts is the best we can come up with.

**Comment by mike-000** [comment]
> Thanks for the examples, I understand that https://openmaptiles.org/schema/ and https://docs.mapbox.com/mapbox-gl-js/style-spec is the closest we have to a standard and https://github.com/openlayers/ol-mapbox-style is the way forward. Still can't believe that in case of generating tiles, importing osm into a database and launch a bunch of sql scripts is the best we can come up with.

You don't need to create tiles, there are hosted OpenMapTile compliant services such as MapTiler available and styles can be obtained using http://editor.openmaptiles.org/

To use the predefined OSM Bright style and MapTiler's OpenMapTile compliant OSM data simply make these changes to the ESRI example

    url: 'https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=' + key,

```
var url = 'https://raw.githubusercontent.com/openmaptiles/osm-bright-gl-style/master/style.json'
fetch(url).then(function(response) {
  response.json().then(function(glStyle) {
    olms.applyBackground(map, glStyle);
    olms.applyStyle(layer, glStyle, 'openmaptiles');
  });
});

```
The ESRI service isn't OpenMapTile compliant so the style jsons are not interchangeable.
