### ISSUE TITLE
openlayers can you draw some special shapes？

### ISSUE THREAD

**Issue by 1006569910** [openlayers/openlayers#9847]
I want to draw some special shapes on the map, such as curves, ellipses, fans and other shapes. Does openlayer support drawing of these graphics? Is there any way to do that?

**Comment by mike-000** [comment]
Yes, you can built on the 'Draw Shapes' example, but you need to set up a `geometryFunction` for the shape you require.  Here is the example extended to include a simple ellipse and oblique ellipse (which requires an extra click)  https://codesandbox.io/s/draw-shapes-fr7dz

**Comment by 1006569910** [comment]
Thanks for your reply. My question has been preliminarily solved
