### ISSUE TITLE
Question related to getCoordinateFromPixel

### ISSUE THREAD

**Issue by VirtualisProject** [openlayers/openlayers#9849]
I have the following Typescript function:
```
public drawNodeRelationLine() {
//node rendered in map
let centerOfNode = OlProj.fromLonLat([this.node.longitude, this.node.latitude]);

//container rendered in maplet coordinate = [this.nodeInfoContainer.nativeElement.getBoundingClientRect().x, this.nodeInfoContainer.nativeElement.getBoundingClientRect().y];
let centerOfNodeContainer = this.mapRef.getCoordinateFromPixel(coordinate);
}
```

The centerOfNodeContainer  property get's insane high values for my understanding, se image below: 
![image](https://user-images.githubusercontent.com/43247999/62872574-13c72e80-bd1e-11e9-84e3-eda62c27cd16.png)

What am i doing wrong here? I just want the coordinates relative to the positioning of the container. 

Thanks alot, 
really enjoy working with this amazing library.

**Comment by bojko108** [comment]
Hi, getCoordinatesFromPixel returns the coordinates in map view projection (https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#getCoordinateFromPixel) which in your case seems to be Web Mercator. You can transform them to geographic with https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.transform

**Comment by VirtualisProject** [comment]
Thanks, i managed to get the correct geolocation for my project using the following code:
```
let webMercatorCoordinates = this.mapRef.getCoordinateFromPixel([this.nodeInfoContainer.nativeElement.getBoundingClientRect().x, this.nodeInfoContainer.nativeElement.getBoundingClientRect().y]);

//Converting coordinates from Web Mercular to geographic coordinates:
let centerOfNodeContainer = OlProj.transform(webMercatorCoordinates, 'EPSG:3857', 'EPSG:4326'); 
```
