### ISSUE TITLE
TopoJSON writeFeatures get error:Unimplemented abstract method

### ISSUE THREAD

**Issue by Hexmm** [openlayers/openlayers#9851]
**Describe the bug**
When I try using ol/format/TopoJSON.writeFeatures(jsonData) to transform'GeoJSON' data to  'TopoJSON' data. But get a error: 'Unimplemented abstract method'

**To Reproduce**
1. import TopoJSON from 'ol/format/TopoJSON';
2. const format = new TopoJSON();
3. format.writeFeatures();
3. See error:
![image](https://user-images.githubusercontent.com/29647149/62928272-d381b200-bdea-11e9-939c-08db3989116b.png)

**In my opinion:**
I checked the ol source code,then can't find writeFeatures or writeFeatureObject function, which be found in GeoJSON.js  and EsriJSON.js.
So I guess, the function is lack in TopoJSON.js.

Forgive my poor english,if you read not fluently.

**Comment by ahocevar** [comment]
OpenLayers does not support writing of TopoJSON geometries. You may want to use a separate package for that, e.g. https://www.npmjs.com/package/topojson-server.
