### ISSUE TITLE
Problem using Ol.Geometry library to draw 2d line between two nodes using Angular/JS

### ISSUE THREAD

**Issue by VirtualisProject** [openlayers/openlayers#9852]
I am trying to draw a line between two features (drawn as overlay). I have two coordinates that follows the Web Mercular projection. 

I've read that i can use the Geometry library to draw lines between two objects, but whatever i do i get errors related to the Geometry library. 

Imports:
```
import OlMap from 'ol/Map';
import Overlay from 'ol/Overlay.js';
import VectorLayer from 'ol/layer/Vector.js';
import Geometry from 'ol/geom/Geometry';
import OlFeature from 'ol/Feature';
import * as OlProj from 'ol/proj'
```

function that used the Geometry library:
```
 public drawNodeRelationLine() {

        //Fetching node coordinates
        let centerOfNode = OlProj.fromLonLat([this.node.longitude, this.node.latitude]);

        //Fetching node-information-container coordinates
        let webMercatorCoordinates = this.mapRef.getCoordinateFromPixel([this.nodeInfoContainer.nativeElement.getBoundingClientRect().x, this.nodeInfoContainer.nativeElement.getBoundingClientRect().y]);

        console.log("WebMercatorCoordinates:", centerOfNode);
        console.log("centerOfNodeContainer:", webMercatorCoordinates);

        var start_point = Geometry.Point(centerOfNode[0], centerOfNode[1]);
        var end_point = Geometry.Point(webMercatorCoordinates[0], webMercatorCoordinates[1]);

        //Creating line:
        let line = OlFeature.Vector(Geometry.LineString([start_point, end_point]));

        //vector layer containing features
        this.vectorLayer.getSource().addFeatures(line);
    }
```

The following browser errors i get is the following: 
ol_geom_Geometry__WEBPACK_IMPORTED_MODULE_5__.default.Point is not a function

I guessed this had to do with Geometry not being declared as 'new', but following this article below i read that 'There is no constructor since Version 5.0.0', meaning this should work?
 https://github.com/openlayers/openlayers/issues/9046

Anyways, would appriciate some help on this, thanks alot.

**Comment by mike-000** [comment]
There is some OpenLayers 2 syntax in your code.  LineStrings should now be constructed directly from coordinates:

        limport LineString from 'ol/geom/LineString';

        let line = new OlFeature(new LineString([centerOfNode, webMercatorCoordinates]));

The removal of the Sphere constructor doesn't affect any other constructors

**Comment by VirtualisProject** [comment]
@mike-000 
Thanks, i switched out 'Geometry ' and imported 'Point' and 'LineString' directly from'ol/geom/LineString'; which solves my problem,
