### ISSUE TITLE
style is ignored in optionsFromCapabilities in WMTS.js

### ISSUE THREAD

**Issue by daudihusbands** [openlayers/openlayers#9860]
**Describe the bug**
'style' parameter is ignored in optionsFromCapabilities.
Error is in [openlayers/src/ol/source/WMTS.js](https://github.com/openlayers/openlayers/blob/master/src/ol/source/WMTS.js)  line 338.

Should be:
```return elt['Identifier'] == config['style'];```

instead of:
```return elt['Title'] == config['style'];```

**To Reproduce**
Using the sample from https://openlayers.org/en/latest/examples/wmts-layer-from-capabilities.html
```
 var parser = new WMTSCapabilities();
    var map;
    fetch(myGetCapabilitiesEndpoint).then((response) => {
      return response.text();
    }).then((text) => {
      var result = parser.read(text);
      var options = optionsFromCapabilities(result, {
        layer: 'myLayer',
        matrixSet: 'epsg:900913',
        style: 'myStyle'
      });

      map = new Map({
        layers: [
          new TileLayer({
            source: new OSM(),
            opacity: 0.7
          }),
          new TileLayer({
            opacity: 1,
            source: new WMTS(/** @type {!module:ol/source/WMTS~Options} */(options))
          })
        ],
        target: 'map',
        view: new View({
          extent: myExtent,
          origin: myOrigin,
          center: myCenter,
          zoom: 8,
        })
      });
    });
```

**Comment by jahow** [comment]
Hi,

This looks like a bug indeed. I'm marking this as PR accepted, would you be able to propose a fix? Thanks a lot
