### ISSUE TITLE
Setting opacity to undefined results in infinite loop

### ISSUE THREAD

**Issue by alihuber** [openlayers/openlayers#9863]
**Describe the bug**
Hello, I think I found a bug in Openlayers 6.0.0-beta.13, or at least unexpected behaviour that is not happening in ol version 5. If I set opacity to undefined on a TileLayer `PluggableMap.render()` will be called over and over again. At first I thought it is related to https://github.com/openlayers/openlayers/issues/9211 since I ran into an infinite loop, but it is unrelated.

**To Reproduce**
With ol6, if a layer is defined like this:
```javascript
const layer = new TileLayer({
  source: new OSM()
});
l.setOpacity(undefined);

const map = new Map({
  layers: [layer],
  target: 'map',
  view: new View({
    center: [0, 0],
    zoom: 2
  })
});

```
this will eventually result in an infinite loop. This happened in a project where layers are generated dynamically, `undefined` was set purely by accident.  
The infinite loop occurs in https://github.com/openlayers/openlayers/blob/master/src/ol/PluggableMap.js#L1259-L1262 where `animate` is never set to `false`.  
From what I can tell is that when `undefined` is set in https://github.com/openlayers/openlayers/blob/master/src/ol/layer/Base.js#L107, `state.opacity` is set to `NaN` for TileLayers. This is forwarded to https://github.com/openlayers/openlayers/blob/master/src/ol/renderer/canvas/TileLayer.js#L380-L396 when `alpha` is calculated. The difference between between ol5 and 6 would be:  
openlayers 6:
`const alpha = opacity * (transition ? tile.getAlpha(uid, frameState.time) : 1);`
openlayers 5:
`const alpha = transition ? tile.getAlpha(uid, frameState.time) : 1;`
Since opacity is `NaN`, in line 392 `alpha` will always be `NaN` and never be comparable to `1` and `frameState.animate` will always stay `true`.  
This bug seems easy to fix, but I can't come up with a pull request since I am not too familiar with the codebase and I have no idea what role opacity plays here, why it was introduced as a function parameter etc, but a simple `isNaN` check should do it.

**Expected behavior**
Setting opacity to `undefined` on a layer should not result in an infinite loop.

**Comment by tschaub** [comment]
Thanks for identifying this problem and writing up a great bug report.

I think the easiest fix would be to check for a number (between 0 and 1) as early as possible in the setter.

**Comment by alihuber** [comment]
Hello,

by checking in the setter you mean something like this?
```javascript
setOpacity(opacity) {
  this.set(LayerProperty.OPACITY, (typeof opacity === 'number' && (opacity >= 0 && opacity <= 1)) ? opacity : 1);
}
```
The fallback to `1` seems to go along with e.g. the constructor of Base.js.  

However, if something like this is done it seems to contradict with layer.test.js, the `it('returns a layerState with clamped values'` test will fail. It seems that setting negative or too high numbers is fixed by the `clamp` method. So is it preferred to do the sanitizing of the value insinde `clamp` or just leave it in the setter and alter the tests?  

Or, to be consistent with the current tests that check for the correct behaviour of clamping the opacity value, a simple check for a `number` in the setter would suffice?
```javascript
setOpacity(opacity) {
  this.set(LayerProperty.OPACITY, (typeof opacity === 'number') ? opacity : 1);
}
```

This will stop the loop for `undefined`, but I have a hard time understanding the code in TileLayer.js because any other value for opacity besides 1 results in the same loop, since e.g. 0.5 * 1 is still 0.5...

**Comment by tschaub** [comment]
@alihuber I agree the logic in the tile layer renderer looks suspicious.  What we mean to be doing is checking whether the tile opacity during a fade-in transition is not 1 – instead of whether the layer opacity is not 1.

In #9864 I created a fix for this.  In addition, I made it so setting opacity to a non-numeric value throws.  We are not consistent in enforcing valid types or ranges of values for layer properties.  But I think it makes sense to fail fast(er) in this case.  Ideally this would have pointed more quickly to a change you could make in your application, rather than having to dive deep into debugging an issue in the library.

Thanks for your work identifying the problem and suggesting a fix.
