### ISSUE TITLE
Objects drawn on openlayers are moving while zooming the map

### ISSUE THREAD

**Issue by siddickasharaf** [openlayers/openlayers#9866]
Hi friends,
I have drawn certain shapes on openlayers and its displaying on the map. The problem is these shapes are moving to a different location after zooming the map.

**Comment by ahocevar** [comment]
Would you mind sharing your code?

**Comment by siddickasharaf** [comment]
function addGridLayer(){
    var backString = document.getElementById('result').value;//"1;POLYGON((23.203125 46.7578125, 97.03125 27.0703125, 97.03125 -33.3984375, 23.203125 46.7578125));100;#FF0000;2;POLYGON((-95.625 33.3984375, -35.15625 39.0234375, -99.84375 -21.4453125, -95.625 33.3984375));200;#00FF00;3;POLYGON((-21.796875 -33.3984375, 9.140625 -23.5546875, -3.515625 -55.1953125, -21.796875 -33.3984375));#0000FF";								
    vLayerColorArray = new Array();
    var wkt = new OpenLayers.Format.WKT();
    var tempArray = backString.split(";");
    var k = 0;
    for (i = 0; i < tempArray.length; i = i + 3) {
        var wktString = tempArray[i];
        var colorString = tempArray[i + 1];
        var flag = true;
        
        for (x = 0; x < vLayerColorArray.length; x++) {
            if (colorString == vLayerColorArray[x]) {
                flag = false;
                break;
            }
        }
        if (flag) {
            k++;
            vLayerColorArray.push(colorString);
            style = {
                strokeColor: colorString,
                fillColor: colorString,
                fillOpacity: 0.5,
                strokeOpacity: 1
            };
            var vectorLayer = new OpenLayers.Layer.Vector("grid" + k, {
                style: style
            });
            vectorLayer.id = colorString;
            myMap.addLayer(vectorLayer);
        }
        var features = wkt.read(wktString);
        if (features) {
            var layerByColor = myMap.getLayer(colorString);
            layerByColor.addFeatures(features);
        }
    }
}

**Comment by ahocevar** [comment]
This is OpenLayers 2 code, and OpenLayers 2 has its own repository (github.com/openlayers/ol2). I would strongly suggest you use a recent version.

However, the root cause of the problem is that you are creating features with geographic coordinates and rendering them in a Web Merctor map, so you'll have to reproject them first.
