### ISSUE TITLE
openlayers ^6.0.0-beta.11 version oes not support

### ISSUE THREAD

**Issue by 1006569910** [openlayers/openlayers#9867]

**Comment by 1006569910** [comment]
map.once('rendercomplete', function(event) {
      console.log(event,'event')
      var canvas = event.context.canvas
      if (navigator.msSaveBlob) {
        navigator.msSaveBlob(canvas.msToBlob(), 'map.png');
      } else {
        canvas.toBlob(function(blob) {
          saveAs(blob, 'map.png');
        });
      }
    });
    map.renderSync();
Error reported by the above methods:Uncaught TypeError: Cannot read property 'canvas' of undefined
![22CFFAB9-9B43-49c6-82B6-9A2219839DEF](https://user-images.githubusercontent.com/41898623/63153648-6c116f80-c041-11e9-9742-44dc1f019157.png)

**Comment by ahocevar** [comment]
Thanks for reporting this @1006569910. `rendercomplete` event does not have a `context` property any more, because there is no map canvas any more in v6. We need to document this better.

**Comment by ahocevar** [comment]
If you were trying to export the map as image, here is the new code to achieve that: https://openlayers.org/en/master/examples/export-map.html
