### ISSUE TITLE
Issues loading vector tiles with source.setUrl()

### ISSUE THREAD

**Issue by tschaub** [openlayers/openlayers#9868]
It looks like #9855 wasn't a complete fix for vector tile loading issues when calling `source.setUrl()`.

59cdac004681e3b8ae7b775b01f942f1fb2aa59c is a commit that reworks the tests from #9855 so that they fail.  As the test is written currently, I don't think it is actually testing whether the queue fills up.

To see the problem in action, set up an example that calls `setUrl` on a vector tile source.  If you call it once with a new URL, the tile queue is empty after tiles load.  If you call it again with the original URL, the tile queue is not empty after tiles load.  This is what I was trying to write a test for, but it feels like the `tileloadend` events are part of the problem, so writing a test to demonstrate the issue is not straightforward.

**Comment by ahocevar** [comment]
Working on this now.
