### ISSUE TITLE
ol/source/OSM colour manipulation

### ISSUE THREAD

**Issue by RenoSun** [openlayers/openlayers#9874]
Hi All,

I would like to request a new feature allowing users to manipulate the colors of ol/source/OSM dynamically just like what we have for ol/source/Raster.

https://openlayers.org/en/latest/examples/color-manipulation.html

Thanks,
Reno

**Comment by ahocevar** [comment]
You can already do that. In the example you linked, just replace `ol/source/Stamen` with `ol/source/OSM`.

**Comment by RenoSun** [comment]
@ahocevar thank you very much. It's working! However, I will lose my ability using my OSM sources as  tiled layer (ol.layer.Tile) which is working great with extension like layer switcher.

Working:
` var raster = new Rasterce({
           sources: [new OSM({
                        attributions: '© <a href="/qbgis/">Town of Qualicum Beach 2018</a> ©<a href="https://www.mapbox.com/map-feedback/">Mapbox</a>',
                        url: 'https://{a-d}.tiles.mapbox.com/v4/rsun.9uq9sstg/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicnN1biIsImEiOiJjaWVvdDl2Z2QwaTNuc2ttMnJnZDN4c2E3In0.SFBk2zbv-cTaANXB-m3dfw',
                        maxZoom: 21
                    })],
                    visible: false,
                    name: '2018 Airphoto',
           operation: function(pixels, data) {
             var hcl = rgb2hcl(pixels[0]);
   
             var h = hcl[0] + Math.PI * data.hue / 180;
             if (h < 0) {
               h += twoPi;
             } else if (h > twoPi) {
               h -= twoPi;
             }
             hcl[0] = h;
   
             hcl[1] *= (data.chroma / 100);
             hcl[2] *= (data.lightness / 100);
   
             return hcl2rgb(hcl);
           },
           lib: {
             rgb2hcl: rgb2hcl,
             hcl2rgb: hcl2rgb,
             rgb2xyz: rgb2xyz,
             lab2xyz: lab2xyz,
             xyz2lab: xyz2lab,
             xyz2rgb: xyz2rgb,
             Xn: Xn,
             Yn: Yn,
             Zn: Zn,
             t0: t0,
             t1: t1,
             t2: t2,
             t3: t3,
             twoPi: twoPi
           }
         });`

Not Working:
`var raster = new Tile({
           sources: [new OSM({
                        attributions: '© <a href="/qbgis/">Town of Qualicum Beach 2018</a> ©<a href="https://www.mapbox.com/map-feedback/">Mapbox</a>',
                        url: 'https://{a-d}.tiles.mapbox.com/v4/rsun.9uq9sstg/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicnN1biIsImEiOiJjaWVvdDl2Z2QwaTNuc2ttMnJnZDN4c2E3In0.SFBk2zbv-cTaANXB-m3dfw',
                        maxZoom: 21
                    })],
                    visible: false,
                    name: '2018 Airphoto',
           operation: function(pixels, data) {
             var hcl = rgb2hcl(pixels[0]);
   
             var h = hcl[0] + Math.PI * data.hue / 180;
             if (h < 0) {
               h += twoPi;
             } else if (h > twoPi) {
               h -= twoPi;
             }
             hcl[0] = h;
   
             hcl[1] *= (data.chroma / 100);
             hcl[2] *= (data.lightness / 100);
   
             return hcl2rgb(hcl);
           },
           lib: {
             rgb2hcl: rgb2hcl,
             hcl2rgb: hcl2rgb,
             rgb2xyz: rgb2xyz,
             lab2xyz: lab2xyz,
             xyz2lab: xyz2lab,
             xyz2rgb: xyz2rgb,
             Xn: Xn,
             Yn: Yn,
             Zn: Zn,
             t0: t0,
             t1: t1,
             t2: t2,
             t3: t3,
             twoPi: twoPi
           }
         });`

**Comment by RenoSun** [comment]
@ahocevar thank you very much. It's working! However, I will lose my ability using my OSM sources as  tiled layer (ol.layer.Tile) which is working great with extension like layer switcher.

Working:
` var raster = new RasterSource({
           sources: [new OSM({
                        attributions: 'attr',
                        url: 'https://{a-d}.tiles.mapbox.com/v4/ID/{z}/{x}/{y}.png?access_token=TOKEN',
                        maxZoom: 21
                    })],
                    visible: false,
                    name: '2018 Airphoto',
           operation: function(pixels, data) {
             var hcl = rgb2hcl(pixels[0]);
   
             var h = hcl[0] + Math.PI * data.hue / 180;
             if (h < 0) {
               h += twoPi;
             } else if (h > twoPi) {
               h -= twoPi;
             }
             hcl[0] = h;
   
             hcl[1] *= (data.chroma / 100);
             hcl[2] *= (data.lightness / 100);
   
             return hcl2rgb(hcl);
           },
           lib: {
             rgb2hcl: rgb2hcl,
             hcl2rgb: hcl2rgb,
             rgb2xyz: rgb2xyz,
             lab2xyz: lab2xyz,
             xyz2lab: xyz2lab,
             xyz2rgb: xyz2rgb,
             Xn: Xn,
             Yn: Yn,
             Zn: Zn,
             t0: t0,
             t1: t1,
             t2: t2,
             t3: t3,
             twoPi: twoPi
           }
         });`

Not Working:
`var raster = new Tile({
           sources: [new OSM({
                       attributions: 'attr',
                        url: 'https://{a-d}.tiles.mapbox.com/v4/ID/{z}/{x}/{y}.png?access_token=TOKEN',
                        maxZoom: 21
                    })],
                    visible: false,
                    name: '2018 Airphoto',
           operation: function(pixels, data) {
             var hcl = rgb2hcl(pixels[0]);
   
             var h = hcl[0] + Math.PI * data.hue / 180;
             if (h < 0) {
               h += twoPi;
             } else if (h > twoPi) {
               h -= twoPi;
             }
             hcl[0] = h;
   
             hcl[1] *= (data.chroma / 100);
             hcl[2] *= (data.lightness / 100);
   
             return hcl2rgb(hcl);
           },
           lib: {
             rgb2hcl: rgb2hcl,
             hcl2rgb: hcl2rgb,
             rgb2xyz: rgb2xyz,
             lab2xyz: lab2xyz,
             xyz2lab: xyz2lab,
             xyz2rgb: xyz2rgb,
             Xn: Xn,
             Yn: Yn,
             Zn: Zn,
             t0: t0,
             t1: t1,
             t2: t2,
             t3: t3,
             twoPi: twoPi
           }
         });`

**Comment by mike-000** [comment]
Your raster source should be used in an ImageLayer, which should work with a layer switcher as well as any other layer:

```
var raster = new RasterSource({ sources: [new OSM({ attributions: 'attr', url: 'https://{a-d}.tiles.mapbox.com/v4/ID/{z}/{x}/{y}.png?access_token=TOKEN', maxZoom: 21 })], operation: function(pixels, data) { ...

var rasterLayer = new ImageLayer({ source: raster, visible: false, name: '2018 Airphoto' });
```

Depending on the operation it may be possible to perform colour manipulation directly on a tile layer using a globalCompositeOperation - see #9879

**Comment by RenoSun** [comment]
Hi @mike-000 ,

Thank you very much! Yes, it is working with layer switcher now! I am wondering if "preload" property of ol/layer/Tile will be implemented for ol/layer/Image. Do you know which one has better performance?

Thanks!
