### ISSUE TITLE
OpenLayers arrays are using way too much memory in map with vector tiles

### ISSUE THREAD

**Issue by fjorgemota** [openlayers/openlayers#9875]
**Describe the bug**

Even with a very low `cacheSize` (configured to `2`, which I think isn't even recommended), after navigating a bit on a map rendered by OpenLayers (with MVT vector tiles data) the page starts using way too much memory (like > 200MB), which slows down the experience dramatically on smartphones that doesn't have more than 1GB of RAM.

**To Reproduce**
1. Open a map with vector tiles ([example](https://openlayers.org/en/latest/examples/mapbox-vector-tiles-advanced.html?q=vector));
2. Navigate a bit on the map, zooming down and up, going to different places of the map;
3. See memory usage increase dramatically on Chrome DevTools;

**Expected behavior**
The memory usage should stay more or less the same (< 100 MB), probably by discarding old data automatically.

![High memory usage on map with vector tiles](https://user-images.githubusercontent.com/529864/63296702-17226300-c2a6-11e9-8d56-af2713c59435.png)

**Additional information**

Curiously, most of the memory is used specifically on...arrays (see image below), and that happens **only** on maps with vector tiles. 

![Statistics of memory usage](https://user-images.githubusercontent.com/529864/63296806-50f36980-c2a6-11e9-8243-9d9289acbe4e.png)

Also, this happens both on OpenLayers 5 and on OpenLayers 6, which means the problem isn't solved and it isn't specific to `cacheSize` (even throught cacheSize seems to help a bit to reduce the memory usage). Curiously, this library seems to be more optimized than Leaflet.VectorGrid, but this specific problem is bothering me a bit.

**Comment by pecet86** [comment]
Hello

on Firefox it looks even worse because FF itself has a cleaning problem.
If we don't use styling, this problem is smaller.
As with a friend yesterday we checked it looks that the most take the data contained in the picture:
![image](https://user-images.githubusercontent.com/20416374/63634098-0f6e1000-c652-11e9-8373-bfe5e47d1f06.png)

**Comment by pecet86** [comment]
I did the test myself by changing the storage in these arrays a bit including cache

![image](https://user-images.githubusercontent.com/20416374/63635529-fb330e80-c663-11e9-8c04-6afcd5884965.png)
![image](https://user-images.githubusercontent.com/20416374/63635536-0a19c100-c664-11e9-871c-5d1d0a844bd8.png)
![image](https://user-images.githubusercontent.com/20416374/63635541-1a31a080-c664-11e9-85dc-fe6a6b98bfa4.png)
![image](https://user-images.githubusercontent.com/20416374/63635557-2584cc00-c664-11e9-8fa9-8735b18bb21b.png)


![image](https://user-images.githubusercontent.com/20416374/63635576-3c2b2300-c664-11e9-968a-311356a90aba.png)
![image](https://user-images.githubusercontent.com/20416374/63635584-536a1080-c664-11e9-8911-ae603f310029.png)

orginal:
![image](https://user-images.githubusercontent.com/20416374/63635589-5ebd3c00-c664-11e9-9c38-13d360e8230c.png)

**Comment by fjorgemota** [comment]
I'm not sure if I understood your changes correctly, @pecet86, but...answer a question, please: Did the memory usage reduced there?

Also...@ahocevar and @tschaub, sorry for the ping, but do you guys have any ideas how to reduce the memory consumption on the vector tiles? I'm working on a product that uses OpenLayers 5.3 and on smartphones the maps are just crashing because of that  memory usage problem..which is VERY bad. I investigated a bit the problem and seems like the main problem here is basically the `replaysByZIndex_` attribute on `CanvasReplayGroup`, which grows a lot on maps with vector tiles after navigating on the map a bit. Is there a way to clear that attributes or any options that allow to reduce the memory consumption there?

**Comment by ahocevar** [comment]
Have you tried with a recent v6 beta? There were many significant improvements, including performance and memory improvements, since v5.3.

**Comment by pecet86** [comment]
@ahocevar 
a colleague will check more in the evening, there is a difference in memory quickly

but I still see the same code as I showed a possible fix

@fjorgemota
yes, memory usage has been reduced

I explain:
I noticed that there is a lot (depending on the data, in particular those with the same style) of the same tables.
The data in the array can only be a reference to "one object" but the declaration of arrays in such quantity causes that the memory is clogged with prolonged operation.

The quick solution that I have shown is caching the board and giving only references to it

I mean this piece of code:
`this.hitDetectionInstructions.push([ CanvasInstruction.SET_STROKE_STYLE, state.strokeStyle, state.lineWidth, state.lineCap, state.lineJoin, state.miterLimit, state.lineDash, state.lineDashOffset ]);`

**Comment by ahocevar** [comment]
@pecet86 Would you be able to create a pull request against `master` with your suggested changes?

**Comment by fjorgemota** [comment]
@ahocevar 	I tested with a recent v6 beta and found that there are peaks of memory usage (up to 210MB) in my testings, but that after navigating the memory reduces again.

So, yeah, fortunately the issue is fixed for v6 beta. Now I wonder if I should keep the issue open for v5, at least while v6 isn't released as stable yet...

**Comment by pecet86** [comment]
@ahocevar 
Sorry for the delay but I'm a little busy.

I understand that the fix for ol5 will not be anymore?
How will something come only to ol6?

**Comment by ahocevar** [comment]
@pecet86 You can fork this repository (by clicking the "Fork" button at the top of https://github.com/openlayers/openlayers, and then create a branch in your fork to create a pull request from.

**Comment by fjorgemota** [comment]
Now that v6 is released and doesn't have this problem, I'll close the issue.

Thanks for fixing this issue. =)
