### ISSUE TITLE
Single layer blend mode example

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9879]
There is no longer a blend mode example in version 6 as the old example blended multiple layers, but an example would still be useful as in many cases a layer canvas globalCompositeOperation would be much more efficient than using ol/source/Raster for color manipulation, for example to grayscale a base layer or to restore "washout" or "backdrop" raster tile services to full colour https://codesandbox.io/s/globalcompositeoperation-fktwf  There are limitations which should be noted as browsers such as IE don't support many of the operations.

**Comment by jahow** [comment]
Hi @mike-000,
How about an example with CSS effects applied to a layer element? this is not exactly the use case you're talking about but should be feasible.
