### ISSUE TITLE
When adding a Point (with Draw) the stylefunction is used on ALL existing features. Is that expected behavior?

### ISSUE THREAD

**Issue by flexjoly** [openlayers/openlayers#9881]
Hi,

I am new to Openlayers. But getting there! ;-)

At the moment I am working on adding Points to the map with Draw. That works perfectly. But the stylefunction in the VectorLayer is called not only for the new Point, but also on all existing Points.
**Is this normal?**

To be sure, that is was not something in my code, I used the [draw example](https://openlayers.org/en/master/examples/draw-features.html?q=draw) and added a stylefunction: 

```
function styleme(feature) {
  console.log(feature);
  return new Style();  // nothing added here yet
}

var vector = new VectorLayer({
  source: source,
  style: styleme
});

```
The behavior is the same. Console.log() shows every Point when adding a new one.

See: https://codesandbox.io/s/draw-features-iont5

Or am I doing something wrong? When adding the stylefunction to the Draw(), the stylefunction is called constantly when hovering/moving the mouse over the map, not waiting for a click.

Why not in the Draw object? Why is the stylefunction there not fired on the real draw/click-action?

Greetz, flexjoly

**Comment by flexjoly** [comment]
**UPDATE**
I thought I searched well.... but now I find: 
https://stackoverflow.com/questions/55457334/set-new-name-for-each-drawn-point-open-layer/

So the stylefunction in a VectorLayer is called on every change. 
The advice is to style inside the feature. 

Why not in the Draw object? Why is the stylefunction there not fired on the real draw/click-action?

**Comment by mike-000** [comment]
The stylefunction for a Draw is called for every change.  Every move of the pointer is a change, as the blue (with the default style) point which moves with it is styled by the Draw.  Depending on the geometry being drawn the interaction also styles sketch lines and polygons or circles.  If you draw a geometry with more than one point once the drawing is started the sketch drawing also moves with the pointer:  https://codesandbox.io/s/draw-features-8spmn  When the drawing is complete the new feature is added to the layer and is then styled by the layer style.  When drawing a point it completes at the first click, so no other style is used.

**Comment by flexjoly** [comment]
Hi Mike,
Thanks a lot for your explanation and code-example.

I need to decrease the rendering as low as possible. So I am now trying to work with a onclick-event on the Map. That is a bit more complex then I like, because Modify and Snap are also there. 
I can identify a click on the Map from a click on an existing Point. But clicking on the text of a Point is also identified as a Point. Still figuring this out ;-)

I am not sure whether this is the best way to go. So if there is a better way, please tell me! xxx

Greetz

**Comment by flexjoly** [comment]
Hi Mike,
Thanks a lot for your explanation and code-example.

I dived into the working of the events on the map. Because I dont like al this rendering for every pointermove or pointerover. But I see it is inside the core of openlayers (not only in Draw). So I have to leave that for now :flushed:

Greetz
