### ISSUE TITLE
Marker Cluster Positioning issue

### ISSUE THREAD

**Issue by pravinmitta** [openlayers/openlayers#9885]
I'm placing dynamic marker clusters with the coordinates returning from the server, But the marker clusters is by default going to [0,0] coordinates, This is the code i've used to create the cluster

    var count = locationJson.features.length;
    let feature = new Array(count);
    for (var i = 0; i < count; ++i) {
      feature[i] = new Feature(
        new Point(fromLonLat(locationJson.features[i].geometry.coordinates))
      );
    }
    const source = new VectorSource({
      features: feature
    });

    var clusterSource = new Cluster({
      distance: 40,
      source: source
    });

    var styleCache = {};
    var clusters = new VectorLayer({
      source: clusterSource,
      style: function(feature) {
        var size = feature.get("features").length;
        var style = styleCache[size];
        if (!style) {
          style = new Style({
            image: new CircleStyle({
              radius: 10,
              stroke: new Stroke({
                color: "#fff"
              }),
              fill: new Fill({
                color: "#3399CC"
              })
            }),
            text: new Text({
              text: size.toString(),
              fill: new Fill({
                color: "#fff"
              })
            })
          });
          styleCache[size] = style;
        }
        return style;
      }
    });

    var raster = new TileLayer({
      source: new OSM()
    });

    this.map.addLayer(raster);
    this.map.addLayer(clusters);

If any help regarding this is help full

**Comment by jahow** [comment]
Does the features get correctly placed if not inside a cluster source? It's hard to tell what could be wrong without having a reproduction case with sample feature coordinates. Thanks
