### ISSUE TITLE
VectorLabels for Point data fails to render using array of styles in combination with declutter:true

### ISSUE THREAD

**Issue by roneiv** [openlayers/openlayers#9893]
**Describe the bug**
Affected version: 5.3.0 as delivered by cdn.rawgit.com

I was trying to make use of decluttering when rendering some POINT features. For the respective layer there is a style function applied, which returns an array holding two styles. The two styles represent the featureStyle and the labelStyle. (The concept is taken from the OL Example https://openlayers.org/en/latest/examples/vector-label-decluttering.html?q=label)

I can make this approach work fine for Polygons, but for Point data - the label is not rendered when declutter is set to true. If you set declutter to false, the labels show up (but then no declutter mechanism).

The labels will be properly rendered with declutter:true if I merge the two styles into one, but passing an array of styles they will not render as long as declutter has true value.

**To Reproduce**
This is a codepen using declutter:true, where the stylefunction only returns one style object. Here everything works as expected.
https://codepen.io/eivindronnevik/pen/jONLPJd

This is a very similar example, using declutter:true, where the stylefunction returns two style objects. No labels are rendered.
https://codepen.io/eivindronnevik/pen/aboyveE
For the non-working example, setting declutter:false makes the labels render fine.

**Expected behavior**
The labels should be rendered regardless of declutter:true|false, and regardless whether there's an array of styles or single style applied in the styleFunction.

**Comment by mike-000** [comment]
As described in the API 

> Declutter images and text. Decluttering is applied to all image and text styles, and the priority is defined by the z-index of the style. Lower z-index means higher priority.

 the declutter option is decluttering styles, not features.  If I add `zIndex: -1,` to your labelStyle only the labels are rendered (note the zIndex priority is reversed in OpenLayers 6).

**Comment by roneiv** [comment]
@mike-000 Thank you for your input and explanation.

So if I understand you (and the API) correctly then, what I experience is actually the decluttering of the conflict between the image element of one style vs the text element of the other style? And then the image style/element is prioritized as it has a lower zIndex - hence I only see the feature rendered with no label.

And this works for polygons as there is no image-element of in the feature style that comes into play there, hence no conflict with the text of the other?

Sorry for generating some noise and spending your time on this, I felt I had a good reason to register the bug, but now it seems clear that this works as intended. I will close the issue.

Keep up the good work!

Kind Regards,

Eivind

**Comment by mike-000** [comment]
If an array is more convenient instead of a Circle image style you could use a Circle geometry style which, like a polygon, works because there is no conflict:

```
  var featureStyle = new ol.style.Style({
    geometry: new ol.geom.Circle(feature.getGeometry().getCoordinates(), 2*resolution),
    fill: new ol.style.Fill({
      color: '#990000'
    }),
    stroke: new ol.style.Stroke({
      color: '#000'
    })
  });
```
