### ISSUE TITLE
Vector Tile Layer style not working

### ISSUE THREAD

**Issue by henviso** [openlayers/openlayers#9894]
I have a simple map setup with a single VectorTileLayer on top of a OSM layer.
All I'm trying to do is simply change the color of the vector tile layer, but I'm unable to do it.
It works perfectly when I change the VectorTileLayer for a VectorLayer, that is why I think there may be a bug with VectorTileLayer style options.
Can you guys please help to find if this is just a silly mistake from me or a real bug. Thank you.

**To Reproduce**

As I'm running the vector tile server locally (it is a very specific one) I'm unable to give a code example that you guys can run. So I'm providing a my html and javascript but you can change the server for any vector tile server and it might give the same problem. I can provide a full example if necessary.

To reproduce just run yarn start:

package.json

```json
{
  "name": "webtiler",
  "version": "1.0.0",
  "description": "Web tiler",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "yarn install && parcel ./src/index.html",
    "build": "parcel build src/index.html --public-url ./"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ol": "5.3.0",
    "parcel-bundler": "^1.12.3"
  },
  "devDependencies": {}
}
```

index.html

```html
<!doctype html>
<html lang="en">
  <body>
      <div id="map" class="map"></div>  
      <script src="map.js"></script>
  </body>
</html>
```
map.js

```javascript
import 'ol/ol.css';
import { Map, View } from 'ol';
import { Tile as TileLayer, VectorTile as VectorTileLayer } from 'ol/layer';
import { OSM, VectorTile as VectorTileSource } from 'ol/source';
import { MVT } from 'ol/format'
import { fromLonLat } from 'ol/proj';
import {Style, Fill, Stroke} from 'ol/style';

const map = new Map({
  target: 'map',
  layers: [
    new TileLayer({
      source: new OSM()
    }),
    new VectorTileLayer({
      source: new VectorTileSource({
        format: new MVT(),
        url: 'http://localhost:8282/tiles/agrows/{z}/{x}/{y}.mvt'
      }),
      style: new Style({
        fill: new Fill({
          color: 'red'
        }),
        stroke: new Stroke({
          color: 'white'
        })
      })
    }),  
  ],
  view: new View({
    center: fromLonLat([0.0, 0.0]),
    zoom: 4
  })
});
```

**Expected behavior**

If your vector tile server has two points one on [0.0, 0.0] and another on [0.2, 0.2] coordinates, you should see red point features filled with white background right bellow Accra city in Ghana. But you will see no points just like the picture below:

<img width="679" alt="Screen Shot 2019-08-30 at 14 11 19" src="https://user-images.githubusercontent.com/926265/64039409-edccc700-cb30-11e9-9007-708651067cee.png">

But if you remove the style property from VectorTileLayer config options you will see the points rendered using default styles. Just like the picture bellow:

<img width="723" alt="Screen Shot 2019-08-30 at 14 09 01" src="https://user-images.githubusercontent.com/926265/64039378-dd1c5100-cb30-11e9-85dd-f300e486a9dd.png">

**Comment by mike-000** [comment]
Fill and Stroke alone style polygons and linestrings.  To style a point you need an image:

      style: new Style({
        fill: new Fill({
          color: 'red'
        }),
        stroke: new Stroke({
          color: 'white',
          width: 1.25
        }),
        image: new CircleStyle({
          radius: 5,
          fill: new Fill({
            color: 'red'
          }),
          stroke: new Stroke({
            color: 'white',
            width: 1.25
          })
        })
      })

Stroke should also be specified with a width.

**Comment by henviso** [comment]
Ok mike, that worked. My bad.

It is very hard to figure this out from the docs: https://openlayers.org/en/latest/apidoc/module-ol_style_Style.html#~StyleLike.

Could you give me some insight on which features does openLayers consider to be circles to be images? 

Why I'm asking this: When I look on https://openlayers.org/en/latest/apidoc/module-ol_style_Image-ImageStyle.html its easy to understand that icons are styled as images, but I'm having a hard time to understand the concept of circles being images and also by reading the same page I would guess regular polygons should be styled using image as well. 

One last Question, does the style you provided covers all geometry types? How you go for styling the entire layer with the same color?

**Comment by mike-000** [comment]
Only Point geometries require an image style (which can be an icon, regular shape or circle) because a Point is just single coordinate and doesn't have a shape.  All other geometry types have a shape which can be filled or its outline stroked.  The shape used to style a point doesn't need to use the same colors as the styles for other geometries (a red point styled inside a red polygon would be difficult to see) although in my simplified example they are the same.

**Comment by henviso** [comment]
Ok Mike, thank you.
Closing the issue.
