### ISSUE TITLE
KML Placemark's name is trimmed.

### ISSUE THREAD

**Issue by oterral** [openlayers/openlayers#9902]
**Describe the bug**
When we read a feature using the KML format with a Placemark's name with spaces, the spaces around text's content are removed. 

Its' caused by the automatic trim of all text content in [xsd.js](https://github.com/openlayers/openlayers/blob/master/src/ol/format/xsd.js#L97)

**To Reproduce**
1. Go to 'https://codesandbox.io/s/kml-522w5'
3. See there is no space in the feature's text

**Expected behavior**
The feature's text should be displayed with spaces before and after

I know google earth also trim the text by default but that's not the behavior  I need.

I see 2  solutions:
    - remove the trim() use but I guess it could break other applications behavior
or
   - add a parameter to readStirng and makes it configurablae via the constructor of the KML format.

if someone else as a workaroud I can also take it

**Comment by mike-000** [comment]
Just **KML Placemark's name is trimmed** would be a better title, the property is trimmed (even in the info box) and the style is simply a side effect of that.  As a workaround you could delimit whitespace with zero-width space `<kml><Placemark><name>&#8203;   Test   &#8203;</name>`

**Comment by oterral** [comment]
woww thanks @mike-000  I will try your workaround.

**Comment by oterral** [comment]
@mike-000 works like a charm thanks
