### ISSUE TITLE
OverviewMap shows incorrect box when view is rotated

### ISSUE THREAD

**Issue by mike-000** [openlayers/openlayers#9910]
This can be seen either of the examples:

![image](https://user-images.githubusercontent.com/49240900/64489554-a808b080-d24c-11e9-9ad7-827715a560b4.png)

Implementing the "TODO: This should rotate the extent rectangle instead of the overview map's view" comment in the code is easy, and a rotateWithView option/setter/getter can be used to produce either that behaviour or the current behaviour (but with the correct box), as in this demo https://codepen.io/mike-000/pen/QWLQKQP (debug full builds can still be useful!)
 
Is there a preferred default value for rotateWithView?

**Comment by ahocevar** [comment]
I would prefer `rotateWithView` to be `false` by default.
