### ISSUE TITLE
Problem parsing geojson locally host

### ISSUE THREAD

**Issue by pierrethiriet** [openlayers/openlayers#9913]
I have trouble loading locally host geojson with the current *OpenLayers* version (5.3.3). While I am trying to reproduce the [geojson example](https://openlayers.org/en/latest/examples/vector-layer.html?q=geojson) :

```js
import 'ol/ol.css';
import {Map, View} from 'ol';
import TileLayer from 'ol/layer/Tile';
import GeoJSON from 'ol/format/GeoJSON.js';
import OSM from 'ol/source/OSM';
import VectorLayer from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector.js';

// Layers 
const osm = new TileLayer({
  source: new OSM()
});

var vectorLayer_local = new VectorLayer({
  source: new VectorSource({
    format: new GeoJSON(),
    url: 'countries.geojson'
  })
});

// Map 
const map = new Map({
  target: 'map',
  layers: [osm, vectorLayer],
  view: new View({
    center: [0, 0],
  })
});
```
 I do face a parsing error with the geojson locally host: 
Consol log: `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`.
Obviously the *country.geojson* is on the computer and on the same folder than the js script...
But this issue does not exist when using the remote url:
```js
var vectorLayer_remote = new VectorLayer({
  source: new VectorSource({
    format: new GeoJSON(),
    url: 'https://openlayers.org/en/v5.1.3/examples/data/geojson/countries.geojson'
  })
});
```
It was working in the past without any trouble, so I am not sure If it is an error on my side or a bug somewhere.
Thanks

**Comment by mike-000** [comment]
Can you open http://localhost/your-path/countries.geojson directly from the browser? ` .geojson` may need to be set up in the server MIME types https://stackoverflow.com/questions/54041033/how-can-i-add-a-geojson-file-using-its-local-path-with-openlayers

**Comment by pierrethiriet** [comment]
Thank you. 
That might be the problem (I am still struggling with the windows configuration, but that's my problem...)
But what is strange is all the examples and previous small web map I did were working smoothly, but it was before using nodes. So it might be more related to nodes than to OpenLayers by itself.
