### ISSUE TITLE
How to set image overlay exact on top of the building in map 

### ISSUE THREAD

**Issue by pravinmitta** [openlayers/openlayers#9918]
i'm Getting 4 Bounds i'm trying to place on top of the building but it's not  setting on top of the building. Can anyone suggest me how to set it.
First image is where i'm placing the image and second is where and how it's appearing
![in location](https://user-images.githubusercontent.com/35287775/64544849-5b54d080-d345-11e9-8494-e23b6ad2480d.png)

**Comment by jahow** [comment]
Hi,

We'll need some sort of reproduction case to be able to answer you further, in something like Codepen or Jsfiddle. Thanks!
