### ISSUE TITLE
WFS examples don't work

### ISSUE THREAD

**Issue by tvogt** [openlayers/openlayers#9933]
**Describe the bug**
The WFS examples in the "examples" section do not work.

**To Reproduce**
1. Go to examples / WFS
2. Copy the code
3. Paste into index.html
4. open index.html in browser, or run npm start and go to localhost:1234
5. marvel at the error messages

**Expected behavior**
should give the result visible on the examples page

**Comment by siimots** [comment]
It would be nice if you could copy those error messages here.

CORS?
