### ISSUE TITLE
How to modify the four vertex

### ISSUE THREAD

**Issue by Yuki-Zhao** [openlayers/openlayers#9934]
we drawed the rectangular. we want to modify the rectangular by four vertex. 
![QQ图片20190916120050](https://user-images.githubusercontent.com/22816207/64933853-b58bef00-d879-11e9-88a3-0269b7ca3aba.png)

**Comment by Yuki-Zhao** [comment]
another vertex don't work,

**Comment by jahow** [comment]
Hi, sorry but I'm not sure what is the issue here. Do you want to move the whole polygon?

**Comment by Cootcha** [comment]
I think that you want to resize rectangle (all vertex) when you drag any vertex. If you draw rectangular, its like polygon, modify works same like for polygon. Every vertex move alone.  if you use geometryFunction  for own geometry, you set draw type (https://openlayers.org/en/latest/examples/draw-shapes.html)
Modify for own geometry isnt in openlayers, i think. Openlayers can modify only default type (polygon, point, line, circle). I try to solve simuliar problem, but its not EZ.
