### ISSUE TITLE
Map Export Example OL 6b15 gives SecurityError in IE11

### ISSUE THREAD

**Issue by onack** [openlayers/openlayers#9938]
**Describe the bug**
Map Export Example OL 6.0.0 beta 11(and 15 tested locally) gives SecurityError in Internet Explorer 11.1087.16299.0 on Windows 10 1903

**To Reproduce**
1. Go to https://openlayers.org/en/master/examples/export-map.html in IE11
2. Click on Download PNG
3. See error "Uncaught (in promise) SecurityError"

**Expected behavior**
Download PNG

**Comment by mike-000** [comment]
The example uses `html-to-image` which has limited browser support, but has the advantage that overlays can be exported with the map.  It also an issue with the Export PDF example.  For better browser support you would need a fallback to find and combine individual layer canvas as in https://codesandbox.io/s/export-pdf-6sbmc

**Comment by onack** [comment]
I thought all openlayers examples was supposed to be ie11 compatible as they have been adjusted to work with IE11 earlier as an example here: https://github.com/openlayers/openlayers/issues/8356
Its a great resource for those still requiring supporting the ancient browser. If it was up to me I'd only support evergreen browsers too.

**Comment by cgi-sho88** [comment]
I'm also having issues exporting my map into a png in IE11. It seems to work in other browsers. Upon many attempts, I am met with error messages in my logs in IE11. Is there anything that can be done with this as I desperately need this?

Thanks.
<img width="1680" alt="Screenshot 2020-02-07 at 11 34 52" src="https://user-images.githubusercontent.com/60778150/74030094-1beae880-49a6-11ea-869a-025a2c1ed7cc.png">

**Comment by mike-000** [comment]
html-to-image is not compatible with any version of IE.  You will need to use the workaround https://codesandbox.io/s/export-pdf-mswuh

**Comment by cgi-sho88** [comment]
> html-to-image is not compatible with any version of IE. You will need to use the workaround https://codesandbox.io/s/export-pdf-mswuh

Thank you for your rapid response. Does this mean that we cannot download to .png but .pdf only?

**Comment by mike-000** [comment]
You can add the  `.catch(function(error) {` code block to any export
