### ISSUE TITLE
Polygon that straddles the international dateline

### ISSUE THREAD

**Issue by phile13** [openlayers/openlayers#9939]
**Describe the bug**
I am using map.forEachFeatureAtPixel to highlight polygons as I move the cursor around.  It works on half of the polygon but as I move across the International Date Line it stops working.  

**To Reproduce**
1. Create a map using EPSG:3857 and a vector layer with wrapX = true
2. Create a EPSG:3857 polygon that straddles the Date Line (if it were in lat/lon it would have X coordinates from say -160 to -200)
3. Listen for 'pointermove' or 'singleclick' on map
4. call map.forEachFeatureAtPixel using event.pixel and a callback(feature,layer)
5. in Map.js there is a function forEachFeatureAtCoordinate that calculates worldsaway.  If the coordinate calculated by the pixel location is outside the bounds of the projection (ie -180 o 180 but in EPSG:3857) then that translates the coordinate to be on the opposite side of the world but it is not and thus does not return a hit for that location.

**Expected behavior**
I would expect that as I move across a polygon that it would continue to highlight even if I cross the International Date Line.

**Comment by jahow** [comment]
Could you please set up a quick reproduction case in Codepen or similar? It looks like this should definitely not happen. Thanks a lot

**Comment by phile13** [comment]
Hello,

  I have recreated the issue on jsfiddle

  https://jsfiddle.net/phile13/d2mp6g7q/

Thanks
Erick

**Comment by jahow** [comment]
Thanks a lot, I'll mark this as a bug for now although I'm not 100% sure this is unintended behaviour.

**Comment by jahow** [comment]
I'm not sure how we should go about fixing this, although I agree this is unexpected behaviour at best. When looking for features under the cursor, we first filter out features to only keep the ones whose extent intersect the hit region, and of course the polygon would not pass this check when outside of the projection extent.

**Comment by phile13** [comment]
Maybe if it is outside the projection you test the selected pixel in both
hemispheres.  My temporary fix is to add a second invisible polygon for
those that straddle the dateline but shifted to the other hemisphere and
with a property that is the feature that it is mimicking. When you mouse
over the original one it behaves as you would think, but when over the
invisible one it tells you to highlight the feature that is stored in its
properties.

Thanks and I will try to think a little more on how to fix this
Erick

**Comment by simonseyock** [comment]
@phile13 This problem should be solved with the new version 6 of openlayers.
The solution was to offset the clicked coordinates by +/- 1 world width.
Thanks for your help.

**Comment by phile13** [comment]
Just a heads up, I just changed my jsFiddle code to use version 6 js and
css and it didn't bring up a map at all.  I switched back to the 5.3
version and it worked again, but switched back to 6.0 and it did not.

Thanks
Erick

**Comment by ahocevar** [comment]
You need to give the map container a height. Neglecting to do so worked by chance in previous versions, but does not work any more. Here is an updated fiddle with the map height set to 500px: https://jsfiddle.net/z8majv17/

**Comment by phile13** [comment]
My bad, thanks so much for getting this fix out so quickly.

Erick
