### ISSUE TITLE
lags when zooming in or panning (slight on desktop, worst on mobile)

### ISSUE THREAD

**Issue by pir1981** [openlayers/openlayers#9940]
**Describe the bug**
I am currently working on a project using openlayers with vector tiles using mapbox style json for the design at the user side. But we are experiencing lags on zooming in and out and panning (slight on desktops and significant on touch devices, worst on mobile phones).

**To Reproduce**
JsFiddles for comparison:
openlayers with ol-mapbox-style:https://jsfiddle.net/ptxyrgn5/4/
leaflet with leaflet-mapbox-gl: https://jsfiddle.net/h3r4ej2m/2/
mapbox gl:https://jsfiddle.net/rb591784/1/
all 3 together: https://jsfiddle.net/ew1aLos0/10/

Panning: “grab” the map and do circles with the mouse, and you will see that you will repeatedly “lose” it (it gets stuck).
Zoom: zoom in and out, and you will see that the map gets stuck regularly, ignoring further zoom actions until it recovers

We have tested leaflet and mapbox-gl for comparison and neither of them show similar issues.

Does anyone else experience this, or is it just some settings, we have not set correctly?

We are adding the layer with ol-mapbox-style like this

```
var map = new ol.Map({
           target: 'map',
           view: new ol.View({
               center: ol.proj.fromLonLat([0, 0]),
               zoom: 2
           })
       });
olms.apply(map, 'https://api.maptiler.com/maps/basic/style.json?key=[KEY]');
```

**Expected behavior**
I would expect it to work just as smooth as the other two.

Is there a better way to implement openlayers or are there any options that I’m missing?

**Comment by isthisstackoverflow** [comment]
Which browser(s) are you using? I tried your example in current FF and it does not get lost/stuck.

**Comment by jahow** [comment]
I don't see anything wrong with your setup so I'd say it is a performance issue. Vector tile rendering has gotten better in version 6, could you maybe try to use the latest beta in your code and see if the locking is gone? Thanks

**Comment by jakubbican** [comment]
Should it be the similar behvior like this? https://github.com/openlayers/openlayers/issues/9916

**Comment by pir1981** [comment]
**Panning:**
So for the panning we now have have a solution. It seemed to be unrelated, as we had a mouse pointer change to a hand pointer, and this event was firing all the time during panning. We turned it off during panning and added after panning a 40ms delay and that seems to have solved it. If we find anything else on panning we will report it.

**Zoom**
We have tested 6.0.0 and ol-mapbox-style for zoom and there is no improvement over 5.3.

You can see the lagging when zooming (as we experience it) really well also with this example (potentially a different version but it exhibits the behaviour perfectly): https://openlayers.org/en/latest/examples/mapbox-style.html

On the other hand https://openlayers.org/en/latest/examples/mapbox-layer.html looks very promising. We would love to see this feature implemented in the stable version, as it is only then that we can use it in the live deployment.
What is the likelihood of this being implemented in the stable release and any idea on the timing?

**Comment by pir1981** [comment]
oh, and by the way.... thanks to everyone on this project for their amazing work!!

**Comment by ahocevar** [comment]
> On the other hand https://openlayers.org/en/latest/examples/mapbox-layer.html looks very promising. We would love to see this feature implemented in the stable version, as it is only then that we can use it in the live deployment.

That example uses a hack to get mapbox-gl synchronized with the OpenLayers view. It is beyond our influence if Mapbox adds an API for that. So I'd say don't use this unless you want to enter a world of pain similar to the one OpenLayers 2 had with integrating Google Maps layers.

**Comment by pir1981** [comment]
@anocevar any thoughts on how we could realize the fast behavior with openlayers alone? What are the alternatives?

**Comment by ahocevar** [comment]
@pir1981 Vector tiles are great in OpenLayers for thematic overlays. For base maps, it is better to use raster tiles. Are your vector tiles a base map or a thematic overlay?

**Comment by pir1981** [comment]
@ahocevar: we use vector tiles  for base map. We had raster tiles before, but switched as with vector we can push different users different styles, while using the same map provider.

**Comment by pir1981** [comment]
@ahocevar: as there seems to be no other option for vector tiles, we went with the mapbox-gl option and now 6.0.1 OpenLayers, taking the potential pain on. The performance is significantly better than what we started out with, but it would be amazing to see this implemented directly in OpenLayers.
