### ISSUE TITLE
Can anybody show me a heatmap example with geojson ?

### ISSUE THREAD

**Issue by uct8086** [openlayers/openlayers#9941]
i know , there is an official example for heatmap , but it's  kml style , 
Can anybody show me a heatmap example with geojson ?

thx !!!

**Comment by fredj** [comment]
You just have to use a `GeoJSON` format instead of `KML`.

See https://codesandbox.io/s/heatmap-earthquakes-geojson-cnud0
This example used the geojson output format from the [USGS Earthquake Catalog](https://earthquake.usgs.gov/earthquakes/search/)

**Comment by uct8086** [comment]
> You just have to use a `GeoJSON` format instead of `KML`.
> 
> See https://codesandbox.io/s/heatmap-earthquakes-geojson-cnud0
> This example used the geojson output format from the [USGS Earthquake Catalog](https://earthquake.usgs.gov/earthquakes/search/)

thx , i resolve like this :

```
      let HeatmapLayer = new Heatmap({
            source: new VectorSource(),
            radius: 18,
            shadow: 500,
            blur:45
        });
      let list = this.source.getFeatures();  //  this.source  get the target features 

      for(let item of list ) {              //  copy the feature to the heatmap layer
                let geometry = item.get('geometry');
                let coordinate = geometry.flatCoordinates;
                let feature = new Feature({
                    geometry: new Point(coordinate),
                  })
                HeatmapLayer.getSource().addFeature(feature);
        }
        this.map.addLayer(HeatmapLayer);  //  add heatmap layer to map

```

**Comment by maranza** [comment]
@uct8086 Do you mind sharing the whole code to implement this, if you still have it, i am faced with the same problem, i however do not understand where your source is coming from, source for features to be specific.
