### ISSUE TITLE
WebGL map blurred when the width is odd number

### ISSUE THREAD

**Issue by Emil-Zhou** [openlayers/openlayers#9943]
**Describe the bug**
The webGL map becomes blurred when the width of map canvas is odd number.

**To Reproduce**
1. Please open the sample [Shared Views](https://openlayers.org/en/latest/examples/side-by-side.html?q=webgl) 
2. Open the Dev Tools of Chrome, so that you can check the canvas width.
3. Change browser width by dragging the browser border, and stop at a odd number, such as '531'
![image](https://user-images.githubusercontent.com/16344877/65211010-d188ce00-dacf-11e9-8726-57f3f4d7bb75.png)

4. Slowly change the width of the browser and you'll easily see the difference of WebGL map between clarity and blur. The Canvas map not.

**Expected behavior**
1. Whether there are some accuracy issue, such as pixel should be integer. it's my guess.
2. I have a idea as workaround, add a event function to set the width of canvas element as even number after the width of canvas element has changed.

Thanks.

**Comment by jahow** [comment]
Hi,

The concept of WebGL map is gone in version 6. Please refer to the [upgrade nodes](https://github.com/openlayers/openlayers/blob/master/changelog/upgrade-notes.md#drop-of-support-for-the-experimental-webgl-renderer) regarding this. Thanks!

**Comment by Emil-Zhou** [comment]
Thanks for your reply.    

Wish OL better and better.
