### ISSUE TITLE
gml:Ring is not parsed

### ISSUE THREAD

**Issue by ninaDeimos** [openlayers/openlayers#9944]
**Describe the bug**
The following GML object cannot be parsed with `WFS.readFeatures(...)` and GML 3
```
<gml:Polygon srsName="EPSG:2056">
          <gml:exterior>
            <gml:Ring>
              <gml:curveMember>
                <gml:Curve>
                  <gml:segments>
                    <gml:LineStringSegment>
                      <gml:posList srsDimension="2">2679157.58918509 1249544.97110366 2679160.5179592 1249531.8040042 2679162.48698731 1249531.10875259 2679163.78701924 1249531.03199102 2679167.04398626 1249529.79604563 2679169.3785857 1249528.9095691 2679170.60896959 1249528.59495659 2679171.01301871 1249530.60601926 2679172.78700646 1249531.86194723 2679184.00700045 1249526.89895911 2679194.2988067 1249520.33057415 2679194.49080763 1249520.23163127 2679195.3809056 1249522.55058092 2679198.33199036 1249530.24154729 2679195.5670217 1249531.30851375 2679189.44303904 1249533.69665875 2679189.26099706 1249533.42563285 2679186.11804071 1249534.59264156 2679186.25306865 1249534.9917112 2679184.65801878 1249535.59578016 2679184.78405779 1249535.92869387 2679179.83600811 1249537.80175384 2679180.40205195 1249539.48578764 2679178.99809766 1249540.66476003 2679166.5151915 1249543.33899872 2679157.58918509 1249544.97110366</gml:posList>
                    </gml:LineStringSegment>
                  </gml:segments>
                </gml:Curve>
              </gml:curveMember>
            </gml:Ring>
          </gml:exterior>
</gml:Polygon>
```

The result of the parsing is just an JS object with the same structure as the GML object.

My debugging lead me to the finding, that within the `gml:exterior` Element the `gml:Ring` Element cannot be parsed. The only parser known at that stage is for the Element `gml:LinearRing`. But according to GML 3.2 `gml:Ring` is valid.

I tested this with ol@5.3.3

**To Reproduce**
Call `new WFS().readFeatures(...)` on the GML above.

**Expected behavior**
I expect the `readFeatures` function to return a feature with a valid geometry like
```
geometry: Polygon
  ...
  extent_: (4) [...] 
  flatCoordinates: (18) [...]
```

**Comment by jahow** [comment]
That looks like a shortcoming in the GML parsing code. I'll mark this issue as PR accepted, please feel free to propose an improvement and a supplementary test case to cover this. Thanks a lot!

**Comment by ahocevar** [comment]
Finally I was able to create a pull request with a fix. #13749.
