### ISSUE TITLE
OSMXML use, one way request, key's visualisation

### ISSUE THREAD

**Issue by AllroadsNL** [openlayers/openlayers#9948]
**Describe the bug**
When using OSM XML overpass request over other layers.
Two keys on a way, highway and bridge needs visualisation, but I do not get that.
The bridge visualisation is not visualised. tertiary highway is visualised.

![tertiaryOSMXML](https://user-images.githubusercontent.com/8817345/65330363-b47cf980-dbba-11e9-825f-71698fd86bf0.JPG)

When I place the 'bridge' in front in the style, the bridge is visualised.

![bridgeOSMXML](https://user-images.githubusercontent.com/8817345/65330383-bb0b7100-dbba-11e9-8088-9cd712fd86dd.JPG)

Looks that it have something to do with request overpass on the second key. 'bridge' and the styling of it.
If overpass can not do a new request on the same OSM way for a other key.

**To Reproduce**
`var styles = {
        'highway': {
          'tertiary': new ol.style.Style({
            stroke: new ol.style.Stroke({
              color: 'rgba(102, 153, 0, 1.0)',
              width: 2,
			  zIndex: 1,
            })
          }),
          '.*': new ol.style.Style({
            stroke: new ol.style.Stroke({
              color: 'rgba(255, 255, 255, 1.0)',
              width: 3,
			  zIndex: 1,
            })
          })
        },
        'bridge': {
          'yes': new ol.style.Style({
            stroke: new ol.style.Stroke({
              color: 'rgba(0, 0, 0, 1.0)',
              width: 5,
            })
			})
        }
		};
`
**Used vectorsource**
`	// Set vectorsource
      var vectorSource = new ol.source.Vector({
        format: new ol.format.OSMXML(),
        loader: function(extent, resolution, projection) {
          var epsg4326Extent =
              ol.proj.transformExtent(extent, projection, 'EPSG:4326');
          var client = new XMLHttpRequest();
          client.open('POST', 'https://overpass-api.de/api/interpreter');
          client.addEventListener('load', function() {
            var features = new ol.format.OSMXML().readFeatures(client.responseText, {
              featureProjection: map.getView().getProjection()
            });
            vectorSource.addFeatures(features);
          });
          var query = '(node(' +
              epsg4326Extent[1] + ',' + epsg4326Extent[0] + ',' +
              epsg4326Extent[3] + ',' + epsg4326Extent[2] +
              ');rel(bn)->.foo;way(bn);node(w)->.foo;rel(bw););out meta;';
          client.send(query);
        },
        strategy: ol.loadingstrategy.bbox
      });
`

 **Used walkermatt/ol-layerswitcher**
`		    overlayGroup9.getLayers().push(
			new ol.layer.Vector({
				title: 'Highway OSM,  <a href="" target="_blank">Legenda</a> ',
                visible: false,	  
        source: vectorSource,
        style: function(feature) {
          for (var key in hwstyles) {
            var value = feature.get(key);
            if (value !== undefined) {
              for (var regexp in hwstyles[key]) {
                if (new RegExp(regexp).test(value)) {
                  return hwstyles[key][regexp];
                }
              }
            }
          }
          return null;
        }
								})
								);`

Used style in OSM XML example with styling with ol. method
https://openlayers.org/en/latest/examples/vector-osm.html

**Expected behavior**

To see highway visualised above the bridge in one layer

**Comment by jahow** [comment]
Sorry but it's hard to tell if this is a bug from the code you copied, maybe try to set up a reproduction case? Or attempt to provide a Pull Request if you have a clear idea on how this can be fixed. Thanks

**Comment by AllroadsNL** [comment]
For me it also a question is it a bug or do I not understand the style.

I do not use node.js used the .ol method.

> Used style in OSM XML example with styling with ol. method
> https://openlayers.org/en/latest/examples/vector-osm.html

This example, when we place the bridge stylecode in this example we must get the same effect.
I believe. Or use extra a    zIndex:   higher number for highway.

        'bridge': {
          'yes': new Style({
            stroke: new Stroke({
              color: 'rgba(0, 0, 0, 1.0)',
              width: 5,
            })
			})
        }

**Comment by jahow** [comment]
Hm, well looking at the example the logic is to use the first style that matches the feature based on its attributes so yeah, bringing the `bridge` style up in the dict will make it so that this style is selected instead of the `highway` one. You could modify that logic to allow it to select multiple styles for one feature.

**Comment by jahow** [comment]
How about using this style function instead?
```js
var vector = new VectorLayer({
  source: vectorSource,
  style: function(feature) {
    var array = [];
    for (var key in styles) {
      var value = feature.get(key);
      if (value !== undefined) {
        for (var regexp in styles[key]) {
          if (new RegExp(regexp).test(value)) {
            array.push(styles[key][regexp]);
          }
        }
      }
    }
    return array;
  }
});
```

This way features should receive an array of matching styles instead of the first one.

**Comment by AllroadsNL** [comment]
I use a style named "hwstyles"

		    overlayGroup9.getLayers().push(
			new ol.layer.Vector({
				title: 'Highway OSM, (traag, zet aan/uit) <a href="xxxxx" target="_blank">Legenda</a> ',
                visible: false,	  
        source: vectorSource,
        style: function(feature) {
		var array = [];		
          for (var key in hwstyles) {
            var value = feature.get(key);
            if (value !== undefined) {
              for (var regexp in hwstyles[key]) {
                if (new RegExp(regexp).test(value)) {
                  array.push(hwstyles[key][regexp]);
                }
              }
            }
          }
          return array;
        }
								})
								)

all kinds of roads have a color.
but the key highway have roads that has a value that is not in the style, deliberately or written wrong value, etc. There you could say, all left overs, else value's, get a color white.
I did set them at the last in the style list, then the bridge. 
But all roads are white now.
I must change this code part in the style.
'.*': new ol.style.Style
The bridge got a lower, zIndex: 1 must be under the road visualised.

But is not.
![1line1layerzindex](https://user-images.githubusercontent.com/8817345/65500770-193c9a80-dec0-11e9-9b2e-571ac07d14ce.png)

Style codepart with ol.style

          'bus_guideway': new ol.style.Style({
            stroke: new ol.style.Stroke({
              color: 'rgba(64, 64, 64, 1.0)',
			  lineDash: ([9, 9]),
              width: 3,
			  zIndex: 2			  
            })
          }),
          '.*': new ol.style.Style({
            stroke: new ol.style.Stroke({
              color: 'rgba(255, 255, 255, 1.0)',
              width: 3,
			  zIndex: 2			  
            })
          })
		  },
         
	        'bridge': {
          'yes': new ol.style.Style({
            stroke: new ol.style.Stroke({
              color: 'rgba(0, 0, 0, 1.0)',
              width: 25,
			  zIndex: 1				  
            })
			})
        },

Once figured out the structure of style use, then I can go further.

I have a lot to do to make it usable for communication in the Openstreetmap community.
URL string lat/lon and layers, permalink. [construction site without bridge.](http://mijndev.openstreetmap.nl/~allroads/NLOSMOK/OSMOKNL/OSMOKNL.html)

Also a point is to retrieve Overpass OSM data.

As written on the example site OSMXML.

>  Note that panning and zooming will eventually lead to "Too many requests" errors from the Overpass API.

So I want only that the code retrieve data when it is on zoom 20 and higher.
To tackle this problem.

**Comment by AllroadsNL** [comment]
Hope someone else step up to give some advice.
Hints are welcome.
