### ISSUE TITLE
Mapbox Vetor Tiles label not rendered.

### ISSUE THREAD

**Issue by GISerWYJ** [openlayers/openlayers#9956]
**Describe the bug**
Mapbox vetor tiles label not rendered when another vector layer is on top of it.

**To Reproduce**
I have a working codesanbox demo.
[(https://codesandbox.io/s/mapbox-vector-tiles-yfncf?fontsize=14)](https://codesandbox.io/s/mapbox-vector-tiles-yfncf?fontsize=14l)
On my Desktop PC(chrome and Edge): label not rendered when a vector layer is added to the layer array.
![image](https://user-images.githubusercontent.com/12789732/65401263-8afde100-ddf9-11e9-9b32-e9ff5047ef81.png)

But On My Laptop(chrome and Edge):everything just works fine when the other vector layer exisits.
![image](https://user-images.githubusercontent.com/12789732/65401421-96054100-ddfa-11e9-9b23-89660dad6bed.png)

I can't figure it out why.

**Expected behavior**
label should be rendered correctly.

**Comment by ahocevar** [comment]
Thanks for the bug report, I can confirm this.

**Comment by GISerWYJ** [comment]
> Thanks for the bug report, I can confirm this.

Is it related to hardware? Because not every computer/mobile (browser) has the same issue.

**Comment by ahocevar** [comment]
> Is it related to hardware? Because not every computer/mobile (browser) has the same issue.

It has to do with sharing render containers. Depending on the device pixel ratio, OpenLayers decides to share or not to share the container.
