### ISSUE TITLE
Add Boolean 'isSnapped' to event or anything so you can find out whether a feature has been 'snapped'

### ISSUE THREAD

**Issue by flexjoly** [openlayers/openlayers#9958]
**Is your feature request related to a problem? Please describe.**
Our markers are styled as a small circle with a text-label. Snap is the only interaction which only matches with the circle/point. 
interaction/Select or map.getFeatureAtPixel also select a feature when clicking/hovering at the text-label. 
So far I could not find any other simple solution/workaround for this. 

Snap does exactly what we need. Only I could not find how to know if Snap found a feature. For it only changed the pixels/coordinate.

**Describe the solution you'd like**
As far as I can see, adding a boolean parameter to current event would solve this. This could be done in de handleEvent():
```
  Snap.prototype.handleEvent = function handleEvent (evt) {
    var result = this.snapTo(evt.pixel, evt.coordinate, evt.map);
    evt.isSnapped = false;
    if (result.snapped) {
      evt.coordinate = result.vertex.slice(0, 2);
      evt.pixel = result.vertexPixel;
      evt.isSnapped = true;
    }
    return PointerInteraction.prototype.handleEvent.call(this, evt);
  };
```
Of course it is better if such a boolean is initiated with the event itself, like the boolean 'dragging' in the MapBrowserEvent.

Another solution would be a new 'snapped' event... but that is more complicated and costs more performance, I think. 

Thanks in advance!

**Comment by jahow** [comment]
The Snap interaction works with geometries whereas hit detection uses the final render, which explains the difference. I'd say everything is working as intended here, maybe you could put the text labels in a different layer which would use the same source and exclude this layer from the hit detection?

It may be easier if you could set up a small reproduction case. Thanks a lot!

**Comment by flexjoly** [comment]
Hi Jahow,

Thanks for your fast reply.

>  hit detection uses the final render

sorry for my newby-reply on this: is there another, better hit-detection except interaction/Select or map.getFeatureAtPixel?
Or do I need to check the hit-dectection somewhere else?


> I'd say everything is working as intended here, 
yes it does!

Therefor I started this as feature-request 😉 

> maybe you could put the text labels in a different layer which would use the same source and exclude this layer from the hit detection?
I looked into that also, but I hoped to I did not need this workaround. Because I need to rewrite and decouple my nice Feature-object 😏 

> 
> It may be easier if you could set up a small reproduction case. Thanks a lot!
If needed I can do that, but my code is a bit large, so I hope it is clear enough without it 😬

**Comment by jahow** [comment]
> is there another, better hit-detection except interaction/Select or map.getFeatureAtPixel?

There isn't really, but you still can query the vector source using `getFeaturesAtCoordinate` if it's not too large.

> I looked into that also, but I hoped to I did not need this workaround. Because I need to rewrite and decouple my nice Feature-object

I understand, although in that case it would simply be a matter of splitting up your style.

**Comment by flexjoly** [comment]
For now I have made overruled the handleEvent(), so I can add the boolean to the event.

**Comment by jahow** [comment]
I'll mark this as PR accepted if someone wants to add this functionality to the snap interaction.

**Comment by flexjoly** [comment]
Wow!!

I forked openlayers and put the boolean into it (see [my commit](https://github.com/flexjoly/openlayers/commit/9c01a20a8cdd5c54d5388268afa15f6697a67f98)). 
But I have no test-environment etc and I am relatively new to OL. So I have no idea of it is good enough. 
First I need to do more debugging (I worked on other things today) and make sure this gets the job done.

**Comment by jahow** [comment]
Ok, to give you some pointers:
* the added `snapped` state should be exposed using a getter with the `@api` annotation, instead of directly exposing the variable like you did in your commit
* ideally this would also dispatch a `snapped` event, so that it would easier for consumers to react to this state's change; see for example:
https://github.com/openlayers/openlayers/blob/965d0541f2afea9cb98d602549cd50648ebc9d09/src/ol/source/Vector.js#L326-L327

Good luck!

**Comment by flexjoly** [comment]
Snapped-event!! I thought about that too, but it would be more complicated, so I did not mention that. 
Since an event is much better, I will try that!

Thank you so much for guiding me!

**Comment by ahocevar** [comment]
@jahow @flexjoly 

> the added snapped state should be exposed using a getter with the @api annotation, instead of directly exposing the variable like you did in your commit

Actually for events, we use instance properties and not getters. So @flexjoly's code here is good.

**Comment by flexjoly** [comment]
> @jahow @flexjoly
> 
> > the added snapped state should be exposed using a getter with the @api annotation, instead of directly exposing the variable like you did in your commit
> 
> Actually for events, we use instance properties and not getters. So @flexjoly's code here is good.

I had already changed it. 
But if you prefer without get/set I can change it back.

**Comment by simonseyock** [comment]
As I just mentioned in the PR:

> I am not convinced that the snap interaction is the right way to solve this problem. But i agree it is sensible to expose some more information about snapping.
>
> A feature collection would not be neccessary though, because you could still use a select for this or not?

But that apart: If you use `map.getFeatureAtPixel` you would have the same problems that the select interaction has - it also selects on labels. If you'd like to return the feature(s) that have been snapped to you would need to remember them in the snapTo method.

**Comment by flexjoly** [comment]
> I am not convinced that the snap interaction is the right way to solve this problem. 
Do you have any suggestions?
I searched/tried a lot things. But I could not find an 'easy' solution. 

I thought about asking to change interaction/Select so it could also match only with the coordinate of a feature. But that is exactly what Snap does....

> > A feature collection would not be neccessary though, because you could still use a select for this or not?
I responded to this already in #10037. 😉 

> But that apart: If you use `map.getFeatureAtPixel` you would have the same problems that the select interaction has - it also selects on labels. 

uh..... yeah indeed!
If a textlabel from Feature X is shown at the coordinate of Feature Y, `getFeatureAtPixel` will find both...
hhhmmmm

> If you'd like to return the feature(s) that have been snapped to you would need to remember them in the snapTo method.
Even more agreed now!
I also responded to this in #10037
I don't trust myself here 🙍

**Comment by flexjoly** [comment]
@ahocevar wrote in #10037:
>If you can elaborate a bit on what exactly you tried to achieve and what did not work, we should be able to either come up with a solution using existing features, or provide guidance on what should be added.

My problem is that when a user clicks on an existing text-label it must add a NEW marker in stead of selecting the feature from the textlabel.

NB! Markers are many times closer together then in the example below. So Zooming-in does not help enough to get a new marker at the same position of an already existing textlabel. 

I am making a map with Draw, Translate and some kind of select : 
![osm testing](https://user-images.githubusercontent.com/8533733/65956164-0b4fc200-e44a-11e9-85cf-0ae70eb3bec2.png)

**Comment by flexjoly** [comment]
@ahocevar wrote in #10037:
>If you can elaborate a bit on what exactly you tried to achieve and what did not work, we should be able to either come up with a solution using existing features, or provide guidance on what should be added.

My problem is that when a user clicks on an existing text-label it must add a NEW marker in stead of selecting the feature from the textlabel.

NB! Markers are many times closer together then in the example below. So Zooming-in does not help enough to get a new marker at the same position of an already existing textlabel. 

I am making a map with Draw, Translate and some kind of select : 
![osm testing](https://user-images.githubusercontent.com/8533733/65956164-0b4fc200-e44a-11e9-85cf-0ae70eb3bec2.png)

**Context** 
The map is used most of the time on a mobile phone. The users are at work outside (hard labor) and their bosses want them to log what is done at this map. So it should be as easy as possible for them; most of them even don't know much about internet, computers etc.

**Comment by ahocevar** [comment]
@flexjoly The easiest way to make things work for you would be to configure the layer with `renderBuffer: 10`. Replace `10` with the half of your maximum point size in pixels. Then labels will no longer be considered for hit detection, and as a bonus you'll get better hit detection performance.

**Comment by flexjoly** [comment]
😳 Rofl, this actually works perfect!!! 😮 👍 😻 

Sorry, I did bother you guys so long in the wrong direction.

I searched a lot, before starting this issue. I did not see any example or documentation on this. Is there any? I have seen the hitTolerance, but that does not help in this.

The documentation tells ([see VectorLayer](https://openlayers.org/en/latest/apidoc/module-ol_layer_Vector-VectorLayer.html)): 
> renderBuffer | number | 100 | 
The buffer in pixels around the viewport extent used by the renderer when getting features from the vector source for the rendering or hit-detection. Recommended value: the size of the largest symbol, line width or label.

The name `renderBuffer' did not ring any bells 😞 
From this documentation I would think that a hit-circle of 100 pixel is set around the pixel-coordinate. But that is not the case, for it is possible to click between a point/circle and textlabel, without selecting the feature. 
I think, it is a bit confusing on how this works. 

But my problem is solved perfectly! Thank you so much! ❤️ 
And I have learned a lot of this all ;-) I liked contributing and hope to do again!

**Comment by simonseyock** [comment]
There is actually another possibility to work around this if you have for example lines or polygons: you could have the same features in 2 different sources and have different styles on them, one for the hit detection and the other for the labels. Then you could filter the selection. This of course doubles the amount of features, and you need to keep one source in sync with the other, therefore it might not be the cleanest solution, but it should work.

**Comment by simonseyock** [comment]
But as I think about it, it should be normally totally fine with the renderBuffer

**Comment by jahow** [comment]
> There is actually another possibility to work around this if you have for example lines or polygons: you could have the same features in 2 different sources and have different styles on them, one for the hit detection and the other for the labels.

I suggested earlier to do this, only have one source but 2 different layers with different styles (one with labels, one without), which seemed like a "clean" way of handling this. @ahocevar's suggestion is definitely the most performant though ;)

> From this documentation I would think that a hit-circle of 100 pixel is set around the pixel-coordinate. But that is not the case, for it is possible to click between a point/circle and textlabel, without selecting the feature.

The render buffer is applied around the canvas where the features are rendered. A little bit hard to explain why it works in your case but basically, when doing hit detection the library will not look too far from the point you have clicked (only a few pixels instead of 100), and as such will not register a hit on the label of the points which are too far from the actual coordinate.
