### ISSUE TITLE
VectorTile Label Always Rendered on Topmost level

### ISSUE THREAD

**Issue by GISerWYJ** [openlayers/openlayers#9970]
**Describe the bug**
 After  #9957 , now the vectorTile label is always rendered on the **top level**.

**To Reproduce**
https://codesandbox.io/s/mapbox-vector-tiles-yfncf?fontsize=14
![image](https://user-images.githubusercontent.com/12789732/65475373-f1ded100-deb1-11e9-9b9d-9a2fdec19a6b.png)

two canvas elements exisit in the ol-layer element.
![image](https://user-images.githubusercontent.com/12789732/65476548-de356980-deb5-11e9-8c00-39a63a092191.png)

**Expected behavior**
vector tile label should rendered the same as the host vectorLayer.

**Comment by ahocevar** [comment]
Vector labels rendered on top of everything is by design.

**Comment by ahocevar** [comment]
What you can do to render labels next to their layer is to configure the layer with a className:

    new VectorTileLayer({
      className: ‘base‘
    })

**Comment by GISerWYJ** [comment]
add a 'className' worked for me ! Thank you for your reply .
