### ISSUE TITLE
Vector Tiles  render error with stroke > 1

### ISSUE THREAD

**Issue by finchcn** [openlayers/openlayers#9971]
**Describe the bug**
Vector Tiles  render error with stroke > 1

**To Reproduce**
1. Make MapBox Vector Tile Server with Polygon data
2. Create VectorTileLayer with style which stroke is 3
3. Will see some thiner line on boarder of tiles

**Expected behavior**
Render Vector Tiles without tile edges inner Polygon

**Comment by ahocevar** [comment]
You need to configure your server to buffer polygons at the tile boundaries. If you cut them too close at the boundary, you'll get the bahaviour you're observing.

**Comment by finchcn** [comment]
@ahocevar I use geoserver with vector tile plugin. Could you tell me how to configure for this issue?
