### ISSUE TITLE
Why feature sources do not contain loadstart and loadend events?

### ISSUE THREAD

**Issue by bayramucuncu** [openlayers/openlayers#9975]
Tile and Image soruces contain "tileloadstart" and "tileloadend" events. But, feature sources do not containd any event to get "loadstart" and "loadend", so we need to customize the feature sources using ajax calls. Do you have a plan to add load events in feature sources?

**Comment by flexjoly** [comment]
Hi, 
I had/have (?) the almost same question. For me it is more about: getting an event after **ALL** Features are loaded. 

I dived into it a little bit. The tileloadstart|end are triggered for EVERY tile/image before/after loading. 
This event is triggered as a kind of an extend on the change-event. So I guess you can use the change-event to get almost the same on the other sources.

Does this help?

Greetz, flexjoly

**Comment by bayramucuncu** [comment]
Change event fires after a feature add/remove on a source, am I right? But I need get an event before/after/error  ajax request to server.

**Comment by simonseyock** [comment]
We would accept a pull request here.

**Comment by flexjoly** [comment]
> @flexjoly, Change event fires after a feature add/remove on a source, am I right? But I need get an event before/after/error ajax request to server.

I would like this event also (but it is nice-to-have for us). If I have time this or next week I will try to make something.

@bayramucuncu Have you noticed that those are quite different Events then the `tileloadstart` and `tileloadend` ?

As far as I can see, this can be done in `ol/loadFeaturesXhr`

**Comment by bayramucuncu** [comment]
> > @flexjoly, Change event fires after a feature add/remove on a source, am I right? But I need get an event before/after/error ajax request to server.
> 
> I would like this event also (but it is nice-to-have for us). If I have time this or next week I will try to make something.
> 
> @bayramucuncu Have you noticed that those are quite different Events then the `tileloadstart` and `tileloadend` ?
> 
> As far as I can see, this can be done in `ol/loadFeaturesXhr`

Yes this can be done in `ol/loadFeaturesXhr`, and may be extra const like `FEATURELAOADSRAT`, `FEATURELOADEND`, `FEATURELOADERROR`.

I will try it as well.

**Comment by simonseyock** [comment]
A possibility would be to expand the loader with 2 optional arguments: success and error. The firing of the events could be done inside the source itself 
https://github.com/openlayers/openlayers/blob/7eb60fae239db9fe44f54900bc40bba87c0ab230/src/ol/source/Vector.js#L888
if the callbacks are not provided only `loadstart` would be fired.

**Comment by bayramucuncu** [comment]
> A possibility would be to expand the loader with 2 arguments: success and error. The firing of the events could be done inside the source itself
> https://github.com/openlayers/openlayers/blob/7eb60fae239db9fe44f54900bc40bba87c0ab230/src/ol/source/Vector.js#L888
> 
> 
> if the callback arguments are not executed only `loadstart` would be fired.

I think we do not need to expand `loadFeatures(extent, resolution, projection)` . Because it does not include the xhr process and events. I think the best place is `loadFeaturesXhr`. And we sholut fire a new event type in here.

**Comment by simonseyock** [comment]
I would not want to extend `loadFeatures` but fire the events in there. I would extend the `FeatureLoader` type to accept callbacks.
https://github.com/openlayers/openlayers/blob/14b931371dfc0c2538db475d551eb1f2c6473749/src/ol/featureloader.js#L26

This for me has 2 advantages:
1. The same callbacks can be called in custom loaders and the VectorSource would automatically fire the correct events.
2. The events are dispatched inside the class itself. This makes it easier to understand what happens in the class.

Alternatively you could of course specify that the loaders should fire the events on the source, but this seems a unclean to me.

**Comment by simonseyock** [comment]
the `xhr` function in featureloader.js implents the `FeatureLoader` type and calls `loadFeaturesXhr`.

**Comment by bayramucuncu** [comment]
> I would not want to extend `loadFeatures` but fire the events in there. I would extend the `FeatureLoader` type to accept callbacks.
> https://github.com/openlayers/openlayers/blob/14b931371dfc0c2538db475d551eb1f2c6473749/src/ol/featureloader.js#L26
> 
> This for me has 2 advantages:
> 
> 1. The same callbacks can be called in custom loaders and the VectorSource would automatically fire the correct events.
> 2. The events are dispatched inside the class itself. This makes it easier to understand what happens in the class.
> 
> Alternatively you could of course specify that the loaders should fire the events on the source, but this seems unclean to me.

Okay, it make sense. I have planned to create a new event type named `VectorSourceLoadEvent` and fire it in `loadFeatures ` function like following

- `this.dispatchEvent(new VectorSourceLoadEvent(VectorEventType.FEATURELOADSTART));`
- `this.dispatchEvent(new VectorSourceLoadEvent(VectorEventType.FEATURELOADEND));`
- `this.dispatchEvent(new VectorSourceLoadEvent(VectorEventType.FEATURELOADERROR));`

You can do it similar to this way.

**Comment by ahocevar** [comment]
Keep in mind that users can provide their own loaders by configuring a `tileLoadFunction`. If a listener was fired in the default `ol/featureloader/loadFeatures` function, it would only work if no `tileLoadFunction` was configured, or if it uses `loadFeaturesXhr`, which is the default `loadFeatuers` function, or if they configure their custom loader with the correct callbacks.

So a good place to implement this would be `ol/featureloader/xhr`, which would take `success` and `error` callbacks as additional arguments. The events would then be fired by those callbacks, whild would be given to the `xhr` function in `ol/source/Vector#loadFeatures`.

**Comment by simonseyock** [comment]
As I have some time on my hand, I will implement this.

**Comment by simonseyock** [comment]
@ahocevar I have some thoughts and questions about this. Do you have a short moment to answer these?

To support the `success` and `error` calls the `FeatureLoader` type would be extend to:
```
 * @typedef {function(this:(import("./source/Vector").default|import("./VectorTile.js").default),
 *           import("./extent.js").Extent,
 *           number,
 *           import("./proj/Projection.js").default,
 *           function(): void=,
 *           function(): void=): void} FeatureLoader
```

I was wondering if the `this` binding is really necessary as the target should be known when assigning the featureloader. It would make the type a little easier. Alternatively the target could be passed in. Both would be breaking changes and are not really necessary.

With individual success and failure callbacks for every request the `loadFeaturesXhr` function in the current from does not make this much sense anymore. I would refactor it a little.

The `xhr` function also does not make very much sense as it was intended to support both vector sources and vector tiles but is now only used by vector sources. I would move it into `source/Vector.js` as `createDefaultLoadFunction`.

To match things up I would also refactor the `defaultLoadFunction` in `source/VectorTile.js` to `createDefaultLoadFunction`.

Alternatively both default function creators could live in `featureloader.js`.

**Comment by simonseyock** [comment]
The `LoadFunction` type of `ol/Tile` has the tile passed in. To unify these loader function a change to pass the vector source / vector tile into the `FeatureLoader` would make sense. As this is a breaking change I would leave it for now and if desired I could create a second PR with breaking changes.
