### ISSUE TITLE
Sketch does not refresh in drawing interaction in 6.0.0-beta.15

### ISSUE THREAD

**Issue by dbauszus-glx** [openlayers/openlayers#9998]
I created a simple drawing interaction in my application which works as expected with 5.3.3.

If I upgrade the library to 6.0.0-beta.15 the rubberbanding / sketch redraw does no longer work.

I created a fiddle for v5.3.3 which shows the expected behavior. Is there a cdn with the beta library in order to show the problem in a fiddle?

The code is as follows:

```
const sourceVector = new ol.source.Vector();

const layerVector = new ol.layer.Vector({
  source: sourceVector
});

const map = new ol.Map({
  target: 'map',
  layers: [layerVector],
  view: new ol.View({
    center: ol.proj.fromLonLat([-0.108, 51.534]),
    zoom: 18
  })
});


const interaction = new ol.interaction.Draw({
	source: sourceVector,
	type: 'Polygon',
});
    
map.addInteraction(interaction);
```

**Comment by mike-000** [comment]
This reports itself as beta 11 (but may be an incorrectly numbered beta 12?) https://openlayers.org/en/master/build/ol.js

**Comment by dbauszus-glx** [comment]
How do you know the beta version?

When reporting the version from an error exception it logs 6.0.0

https://jsfiddle.net/goldrydigital/koy26Lhd/

More important the rubber band in drawing interaction works as expected. Could it be that I am missing a dependency in my build?

When I test beta 15 from the npm install I pack following modules when the rubber banding fails.

```
import formatMVT from 'ol/format/MVT';
import formatGeoJSON from 'ol/format/GeoJSON';

import sourceOSM from 'ol/source/OSM';
import sourceVectorTile from 'ol/source/VectorTile';
import sourceVector from 'ol/source/Vector';

import {bbox} from 'ol/loadingstrategy';

import layerTile from 'ol/layer/Tile';
import layerVectorTile from 'ol/layer/VectorTile';
import layerVector from 'ol/layer/Vector';

import {Circle, Fill, Stroke, Icon, Style, Text} from 'ol/style';

import {transform, transformExtent, fromLonLat} from 'ol/proj';

import {defaults, Draw, Modify} from 'ol/interaction.js';

import {createBox} from 'ol/interaction/Draw.js';

import {click} from 'ol/events/condition.js';

import {Map, View, Feature, Overlay} from 'ol';

import * as geom from 'ol/geom';

import {ScaleLine} from 'ol/control';
```

**Comment by mike-000** [comment]
A frequent error with imports is importing from the wrong module (e.g. source from layer or vice versa) but those look ok.

I also don't see any problem with this example https://openlayers.org/en/master/examples/draw-features.html (use the "edit" link to open in codesandbox then change the dependency version to beta 15) 

I got the full version by opening the .js source and searching for 6.0.0

**Comment by dbauszus-glx** [comment]
Odd, I re-installed ol@beta re-build package and it works fine now. Not sure why this was borked in previous build but happy to close and move on.
